### PR TITLE
[FIX #4268] Broken message counter when having more than 999 messages

### LINKED ISSUE #4268: Broken message counter when having more than 999 messages
### Description

*Type*: Bug

*Summary*: Message counter layout is broken when there are more than 999 messages unread. 4 digits number is too large to show in this blue circle

#### Expected behavior
Message counter should not be broken. I suggest showing `99+` value when there are more than 99 messages, so we still stick to use 3 digits that are shown fine

#### Actual behavior
image

### Reproduction

- Open Status
- Receive more than 999 messages in public/group chat
- Pay attention  to unread counter

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ovx**
fixes #4268

### Summary:

Show '99+' if the number of messages is greater than 99. Tested for counters in the main navigation, home screen overview, and the upper toolbar.

### Steps to test:
- Open Status
- Receive more than 999 messages in public/group chat
- Pay attention to unread counter

status: ready 

screenshot_1526557049
screenshot_1526557563
screenshot_1526557654

### CODE REVIEW

File: src/status_im/ui/components/common/common.cljs [hunk 1]
```diff
@@ -86,7 +86,7 @@
     [react/text (cond-> {:style (styles/counter-label size)}
                   accessibility-label
                   (assoc :accessibility-label accessibility-label))
-     value]]))
+     (if (<= value 99) value "99+")]]))
```
Comment (jeluard) [inline src/status_im/ui/components/common/common.cljs]: Can you use i18n here? And store this in `en.cljs` ?

**Review by jeluard — CHANGES_REQUESTED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/WFmeei for branch PR-4313

<blockquote><div><strong><a href="https://i.diawi.com/WFmeei">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/ui/components/common/common.cljs (hunk 1 above)
Comment (ovx) [reply src/status_im/ui/components/common/common.cljs]: fixed.

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/bHkTyx for branch PR-4313

<blockquote><div><strong><a href="https://i.diawi.com/bHkTyx">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/Xug1XQ for branch PR-4313

<blockquote><div><strong><a href="https://i.diawi.com/Xug1XQ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
