### PR TITLE
chat: fix broken chat delete logic

### LINKED ISSUE #1291: Deleted chat is shown again after app is relaucnhed
### Description

*Type*: Bug

*Summary*: Chat is deleted in Chats but after app relaunch it's shown again in Chats

#### Expected behavior
Deleted chat is not shown in chats
#### Actual behavior
after app is relaunched  deleted chat is shown again in Chats

### Reproduction
Video (on emulator): https://drive.google.com/open?id=0Bz3t9zSg1wb7ckNwRVZqNHZScG8
- Open Status
- Open Chats
- Delete some chat (e.g with Auction House)
- Close app
- Open app
- Check if Auction House is shown in Chats

### Additional Information
* Status version: 0.9.8-5-ga53e1afd+, 0.9.8 release
* Operating System: Android. Can reproduce both on real device Galaxy S6, Android 6.0.1 and on Android Emulator (Nexus 6P API 25)

#### Logs

### PR DESCRIPTION
**Pull request by janherich**
fixes #1291 

### Summary:
Chat is deleted in Chats but after app relaunch it's shown again in Chats...

### Steps to test:
* Open Status
* Open Chats
* Delete some chat (e.g with Auction House)
* Close app
* Open app
* Check if Auction House is shown in Chats

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
This issue should be fixed in different way, we need to keep group chat in the database.

**Comment by janherich** [comment]
@rasom I'm little bit confused, the previous logic retained deleted group chats in database (while marked as inactive), doing hard delete only when `debug?` was true. 
My PR retains this behaviour (group chat is not deleted from db, except for debug mode) but in addition, non-group chats are simply deleted (whenever `debug?` is true or false).

1. Was the former logic for group chat deletion somehow wrong ? (Issue #1291 mentions only one-to-one chats)
2. Should the one-to-one chats be kept in database as well, if yes, should the logic to perform  'logical delete' (while retaining data in realm) be also implemented with the inactive flag ?

File: src/status_im/chat/handlers.cljs [hunk 1]
```diff
@@ -392,10 +392,9 @@
 (defn delete-chat!
   [_ [_ chat-id]]
   (let [{:keys [debug? group-chat]} (chats/get-by-id chat-id)]
-    (when group-chat
-      (if debug?
-        (chats/delete chat-id)
-        (chats/set-inactive chat-id)))))
+    (when (and (not debug?) group-chat)
```
Comment (rasom) [inline src/status_im/chat/handlers.cljs]: As I understand this condition means that only group chats are removed (and inactivated at the same time) when `debug?` is `false`.

Comment (janherich) [inline src/status_im/chat/handlers.cljs]: My bad, there should be `if` instead of the `when` macro in place, will fix that.

**Comment by rasom** [comment]
Thanks @janherich, now it looks better :)
