### PR TITLE
[#12467] Remove default action icon in message actions list

### LINKED ISSUE #12467: Redundant "!" button in the "Message actions" in context menu for images
# Bug Report

## Problem 
IMAGE 2021-08-20 15:15:38

### Reproduction

1) Open Status
2) Start 1-1 chat
3) send image
4) Long tap on image message

### Additional Information

- Status version: nightly 20/08/21
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by rasom**
fix #12467

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/chat/message/message.cljs [hunk 1]
```diff
@@ -494,8 +494,10 @@
                                                     (on-long-press
                                                      (concat
                                                       [{:on-press #(re-frame/dispatch [:chat.ui/reply-to-message message])
+                                                        :id       :reply
```
Comment (flexsurfer) [inline src/status_im/ui/screens/chat/message/message.cljs:497]: last time it was string :)

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/chat/message/message.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/ui/screens/chat/message/message.cljs:497]: nope, it was a string only the first time :) I changed it to keyword in that PR

**Comment by churik** [comment]
Awesome, thank you @rasom !
Ready to be merged.
