### PR TITLE
fix: balances in network preferences after removing account

### LINKED ISSUE #19542: The balances are not shown in network preferences when the account with some assets is removed
follow up for https://github.com/status-im/status-mobile/pull/19150

### Steps to reproduce:
1. Recover a user with assets in "Account 1" and "Account 2" (Account 2 can be a watch-only account).
2. Remove "Account 2".
3. Check balances within preferences.

### Actual result:
Balances are not shown in the network preferences.

https://github.com/status-im/status-mobile/assets/52490791/5f7c594d-2144-4ad6-b41b-c33f2597d1af

### Expected result:
Balances should be shown in the network preferences even after removing an account.

### ENV:
Nightly 5 Apr 2024

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19542

### Summary
This PR fixes balances not showing in network preferences after removing an account. 

Also fixes `wallet/close-account-page` not being called if back button was pressed (or swipe gesture) instead of pressing on the X button

**On a side note**: I think we need to check for X button on-press if it is called on unmount in the entire wallet/app

### Demo

https://github.com/status-im/status-mobile/assets/29354102/889f9ff9-a32c-4c17-aa35-d3f9c8c94111

### CODE REVIEW

File: src/status_im/contexts/wallet/account/view.cljs [hunk 1]
```diff
@@ -28,6 +28,7 @@
       (let [{:keys [name color formatted-balance
                     watch-only?]} (rf/sub [:wallet/current-viewing-account])
             customization-color   (rf/sub [:profile/customization-color])]
+        (rn/use-unmount #(rf/dispatch [:wallet/close-account-page]))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/account/view.cljs:31]: > Also fixes wallet/close-account-page not being called if back button was pressed (or gesture) instead of pressing on the X button

I think we need to check for X button on-press in the entire wallet/app

File: src/status_im/contexts/wallet/events.cljs [hunk 2]
```diff
@@ -99,20 +99,20 @@
...
+        [:dispatch [:wallet/get-keypairs]]
+        [:dispatch-later
+         {:ms       100
+          :dispatch [:hide-bottom-sheet]}]
+        [:dispatch-later
+         {:ms       100
+          :dispatch [:pop-to-root :shell-stack]}]
+        [:dispatch-later
+         {:ms       100
+          :dispatch [:wallet/show-account-deleted-toast toast-message]}]]})
```
Comment (BalogunofAfrica) [inline src/status_im/contexts/wallet/events.cljs]: Why was this changed to a regular function?

Also checked out the branch and the function doesn't seem to be used 🤔

Comment (BalogunofAfrica) [reply src/status_im/contexts/wallet/events.cljs]: I suppose this is where it is supposed to be used:
https://github.com/status-im/status-mobile/blob/7efa1a0f793a7b8d1b519802214b0169be306f29/src/status_im/contexts/wallet/events.cljs#L123
 but it is still called like an event

Comment (OmarBasem) [reply src/status_im/contexts/wallet/events.cljs]: Oh I was testing something, should have reverted. Thanks @BalogunofAfrica!

Reverted.

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Thanks for your fix!
I've checked it on both platforms and it looks good 🙌.
Failed e2e are not related.
So, PR can be merged.
