### PR TITLE
Share all account addresses UI & some other addresses for permissions screen fixes

### LINKED ISSUE #18822: 'Confirm changes' button unexpected enabled state
**Steps:** 

1. Open token gated community home screen
2. Go to Addresses for permissions screen
3. Pay attention at 'Confirm changes' button's state (enabled/disabled)

**Expected result:** 

Case 1: 'Confirm changes' button should be disabled unless any changes were made on Addresses for permissions screen

Case 2: 'Confirm changes' button should be disabled when user unselects Account that holds tokens required for joining

**Actual result:** 

Case 1: 'Confirm changes' button is enabled despite any changes were made on Addresses for permissions screen

Case 2: 'Confirm changes' button remains enabled when user unselects Account that holds tokens required for joining

https://github.com/status-im/status-mobile/assets/97245802/6a3f2feb-8145-46e3-80c8-ef12c49b4ca8

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #18846: Implement Share all Addresses Toggle in Addresses for permissions Screen (status-mobile)
Figma: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-288172&mode=design&t=gYpBVKTLCKeLcJdg-4

### PR DESCRIPTION
**Pull request by ajayesivan**
This PR implements the Share all current and future addresses toggle UI (#18012) - fixes #18846 
and
fixes #18822

Figma: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-288172&mode=design&t=gYpBVKTLCKeLcJdg-4

#### Other fixes:
- The Confirm button remains enabled even after deselecting all addresses when the user has watch-only wallet accounts.
- Disable the Confirm button when the user deselects the accounts with the token required to join.
- Use community color for address checkbox

#### Testing Notes
Note: This PR only implements the UI functionality of the "share all current and future addresses" toggle.

- Users can only edit address selection if the toggle is off.
- If the user enables the toggle, it will automatically select all addresses and disable all address checkboxes.

#### Areas that maybe impacted
- Request to join community -> Addresses for permission drawer
- Wallet/account-permissions components - added customization color prop

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/events.cljs [hunk 1]
```diff
@@ -163,12 +163,15 @@
...
-          addresses       (set (map :address sorted-accounts))]
+    (let [accounts         (get-in db [:wallet :accounts])
+          sorted-accounts  (sort-by :position (vals accounts))
+          watched-accounts (remove #(:watch-only? %) sorted-accounts)
+          addresses        (set (map :address watched-accounts))]
       {:db (update-in db
                       [:communities community-id]
                       assoc
+                      :previous-share-all-addresses? true
+                      :share-all-addresses?          true
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/events.cljs:173]: I understand that the community object is not the right place to store the UI state for sharing all current and future addresses. If you have no objections, I will keep it here for now and move it out of the community object in a separate PR, along with the other UI states for the addresses on the permissions screen.

Related issue: https://github.com/status-im/status-mobile/issues/18844

File: src/status_im/contexts/communities/events.cljs [hunk 2]
```diff
@@ -218,12 +224,34 @@
 (rf/reg-event-fx :communities/toggle-selected-permission-address
  toggle-selected-permission-address)
 
+(defn toggle-share-all-addresses
+  [{:keys [db]} [community-id]]
+  (let [share-all-addresses? (get-in db [:communities community-id :share-all-addresses?])
+        accounts             (get-in db [:wallet :accounts])
+        sorted-accounts      (sort-by :position (vals accounts))
+        watched-accounts     (remove #(:watch-only? %) sorted-accounts)
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/events.cljs:232]: I have the same logic in three different events. Can you provide guidance on how to make it reusable?

Comment (ajayesivan) [reply src/status_im/contexts/communities/events.cljs:232]: 1

File: src/status_im/contexts/communities/events.cljs [hunk 3]
```diff
@@ -181,15 +184,18 @@
   (when community-id
     (let [accounts                      (get-in db [:wallet :accounts])
           sorted-accounts               (sort-by :position (vals accounts))
+          watched-accounts              (remove #(:watch-only? %) sorted-accounts)
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/events.cljs:187]: 2

File: src/status_im/contexts/communities/events.cljs [hunk 4]
```diff
@@ -163,12 +163,15 @@
 (defn initialize-permission-addresses
   [{:keys [db]} [community-id]]
   (when community-id
-    (let [accounts        (get-in db [:wallet :accounts])
-          sorted-accounts (sort-by :position (vals accounts))
-          addresses       (set (map :address sorted-accounts))]
+    (let [accounts         (get-in db [:wallet :accounts])
+          sorted-accounts  (sort-by :position (vals accounts))
+          watched-accounts (remove #(:watch-only? %) sorted-accounts)
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/events.cljs]: I have the same logic in three different events. Can you provide guidance on how to make it reusable? (1)

File: src/status_im/contexts/communities/events.cljs (hunk 3 above)
Comment (ajayesivan) [inline src/status_im/contexts/communities/events.cljs]: (2)

File: src/status_im/contexts/communities/events.cljs (hunk 2 above)
Comment (ajayesivan) [inline src/status_im/contexts/communities/events.cljs]: (3)

File: src/quo/components/wallet/account_permissions/view.cljs [hunk 5]
```diff
@@ -42,17 +42,19 @@
...
+    :or {customization-color :blue}}]
   [rn/view
    {:style               (merge (style/container theme) container-style)
     :accessibility-label :wallet-account-permissions}
    [rn/view {:style style/row1}
     [account-avatar/view
      {:size                32
       :emoji               emoji
-      :customization-color customization-color}]
+      :customization-color (:customization-color account)}]
```
Comment (cammellos) [inline src/quo/components/wallet/account_permissions/view.cljs:57]: do you not have access to `customization-color` already? (above seems to be destructured)

File: src/status_im/contexts/communities/events.cljs (hunk 4 above)
Comment (cammellos) [inline src/status_im/contexts/communities/events.cljs]: generally is best to `filter` first and after sort, since `filter` is `O(n)` while sorting is at least `O(n * logn)`

Comment (cammellos) [reply src/status_im/contexts/communities/events.cljs]: a function that takes the `db` or the accounts and returns the `addresses` correctly ordererd?

File: src/quo/components/wallet/account_permissions/view.cljs (hunk 5 above)
Comment (ajayesivan) [reply src/quo/components/wallet/account_permissions/view.cljs:57]: The `customization-color` extracted here and passed to the `account-avatar` component is specific to each account. Each account can have a different customization color, which is used for the background of the account emoji. On the other hand, the `customization-color` destructured in the function header is the customization color of the `account-permissions` component, which will be used for the checkbox.

Screenshot 2024-02-16 at 07 32 32

**Comment by pavloburykh** [comment]
Hey @ajayesivan! Thanx for the PR! Is it ready for testing or we are waiting for addressing review comments?

**Comment by ajayesivan** [comment]
Hi @pavloburykh, I have addressed all comments by @cammellos, now waiting for another look/review from others.

**Review by cammellos — APPROVED** [review]

File: src/status_im/contexts/communities/utils.cljs [hunk 6]
```diff
@@ -11,3 +11,10 @@
      constants/community-token-permission-become-admin        :t/admin
      constants/community-token-permission-become-member       :t/member
      fallback-to)))
+
+(defn sorted-watched-accounts
+  [db]
+  (->> (get-in db [:wallet :accounts])
+       (vals)
+       (remove :watch-only?)
```
Comment (Parveshdhull) [inline src/status_im/contexts/communities/utils.cljs]: Hi @ajayesivan, is `watched-accounts` name correct?

File: src/status_im/contexts/communities/events.cljs [hunk 7]
```diff
@@ -218,12 +221,32 @@
...
+  (let [share-all-addresses? (get-in db [:communities community-id :share-all-addresses?])
+        accounts             (utils/sorted-watched-accounts db)
+        addresses            (set (map :address accounts))]
+    {:db (update-in db
+                    [:communities community-id]
+                    (fn [community]
+                      (-> community
+                          (assoc :share-all-addresses? (not share-all-addresses?))
+                          (cond-> (not share-all-addresses?)
+                                  (assoc :selected-permission-addresses addresses)))))}))
```
Comment (Parveshdhull) [inline src/status_im/contexts/communities/events.cljs:235]: We can simply use
```
(cond-> (assoc community :share-all-addresses? (not share-all-addresses?))
  (not share-all-addresses?)
  (assoc :selected-permission-addresses addresses))
```

File: src/status_im/contexts/communities/events_test.cljs [hunk 8]
```diff
@@ -61,6 +67,40 @@
...
+                                                   "0x2" {:address  "0x2"
+                                                          :position 1}}}
+                          :communities {community-id {:share-all-addresses?          true
+                                                      :previous-share-all-addresses? true
+                                                      :previous-permission-addresses #{"0x1"}
+                                                      :selected-permission-addresses #{"0x1"}
+                                                      :airdrop-address               "0x1"}}}}
+        expected-db {:db (update-in (:db initial-db)
+                                    [:communities community-id]
+                                    assoc
```
Comment (Parveshdhull) [inline src/status_im/contexts/communities/events_test.cljs]: We can just use here
`(update-in inital-db [:db :communities ...`

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ajayesivan thank you for the PR. Ready for merge.
