### PR TITLE
fix: adjust community cards on discover page

### LINKED ISSUE #14443: fix discover communities screen stretching too much
# Bug Report

Communities discover page should look like this:
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=7202%3A475069&t=fc4U3iZRVexnAn93-0

After recent changes they now look like:

Screenshot 2022-11-25 at 13 38 41

Fix this

### PR DESCRIPTION
**Pull request by J-Son89**
Fixes https://github.com/status-im/status-mobile/issues/14443

Adjusted the discover card to use width relative to it's view size and margin handled outside. Some other refactors too.

Screenshot 2022-11-25 at 13 37 00

Screenshot 2022-11-25 at 13 37 07

### CODE REVIEW

File: src/quo2/components/community/community_card_view.cljs [hunk 1]
```diff
@@ -6,15 +6,11 @@
 
 (defn community-card-view-item
   [{:keys [name description locked
-           status tokens cover tags featured]} on-press]
+           status tokens cover tags width]} on-press]
   [rn/touchable-opacity {:on-press on-press}
-   [rn/view {:style (merge (style/community-card 20)
-                           {:margin-bottom 16}
```
Comment (J-Son89) [inline src/quo2/components/community/community_card_view.cljs:12]: cards design should care whether it is `featured` or not.
Also margin should be handled by it's container

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 2]
```diff
@@ -34,105 +31,102 @@
...
-    :horizontal                        true
-    :getItemLayout                     get-item-layout-js
     :keyboard-should-persist-taps      :always
     :shows-horizontal-scroll-indicator false
+    :separator                 [rn/view {:margin-bottom 16}]
     :data                              communities
-    :render-fn                         render-featured-fn}])
+    :render-fn                         (render-fn false "100%")}])
 
-(defn featured-communities-section [communities]
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/discover/view.cljs:83]: these cards can use the same rendered function

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 3]
```diff
@@ -34,105 +31,102 @@
...
+        communities-count (reagent/atom {:value (count communities)})
         ;;TODO move sorting to subscription
-        sorted-communities (sort-by :name communities)]
-    [rn/flat-list
-     {:key-fn                            :id
-      :getItemLayout                     get-item-layout-js
-      :keyboard-should-persist-taps      :always
-      :shows-horizontal-scroll-indicator false
-      :header                            (featured-communities-section communities)
-      :data                              sorted-communities
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/discover/view.cljs:120]: this header component was too advanced to be a `header` type component so I flattened the structure a bit.

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 4]
```diff
@@ -34,105 +31,102 @@
...
+                                        :justify-content :center}
+                      :resize-mode     :center
+                      :size            20
+                      :color           (colors/theme-colors
+                                        colors/neutral-50
+                                        colors/neutral-40)}]])
+
+(defn featured-list [communities view-size]
+  [rn/view {:style {:flex-direction :row
+                    :overflow :hidden
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/discover/view.cljs]: actually need to remove this []

**Comment by J-Son89** [comment]
@churik this is in a flow. should it get QA? It's just a fix on some design implementations

**Comment by pavloburykh** [comment]
@J-Son89 thanx for the PR! Tested, looks good to me. 

Got a couple of clarifying questions. 

Should those Discover page elements be implemented or this is out of scope of current PR? Below are screenshots from Figma:

1. All, Open, Gated buttons

Communities for Mobile – Figma 2022-11-28 14-13-56

Currently these buttons are not shown 

2. Header buttons on community page (Back, Search, Options)

Communities for Mobile – Figma 2022-11-28 14-17-39

Currently they look like this:

photo_2022-11-28 14 19 58

**Comment by J-Son89** [comment]
> @J-Son89 thanx for the PR! Tested, looks good to me.
> 
> Got a couple of clarifying questions.
> 
> Should those Discover page elements be implemented or this is out of scope of current PR? Below are screenshots from Figma:
> 
> 1. All, Open, Gated buttons
> 
> Communities for Mobile – Figma 2022-11-28 14-13-56
> 
> Currently these buttons are not shown
> 
> 2. Header buttons on community page (Back, Search, Options)
> 
> Communities for Mobile – Figma 2022-11-28 14-17-39
> 
> Currently they look like this:
> 
> photo_2022-11-28 14 19 58

Thanks @pavloburykh. So 1 is beyond the scope of this p.r as I was just fixing a ui issue that was brought in by some refactors.

and 2 should be fixed by another p.r I just merged today :) 
https://github.com/status-im/status-mobile/pull/14281

**Comment by pavloburykh** [comment]
Thanx @J-Son89 ! Based on that, PR is ready for merge as soon as it passes the Review. I will move it to the Review column. After approval you can go ahead and merge it in case if there will be no additional commits based on the review.

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 5]
```diff
@@ -34,105 +31,102 @@
...
-                                             colors/neutral-50
-                                             colors/neutral-40)}]]
-     [rn/view {:margin-top   8
-               :padding-left 20}
-      [featured-communities communities]]]))
-
-(defn other-communities []
+(defn discover []
   (let [communities (rf/sub [:communities/communities])
+        communities-count (reagent/atom {:value (count communities)})
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: atom should be defined outside render function
```clojure
(let [communities-count (reagent/atom {:value (count communities)}]
   (fn []
       (let [communities (rf/sub [:communities/communities])
```

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 6]
```diff
@@ -34,105 +31,102 @@
...
+                                            colors/white
+                                            colors/neutral-90)}}
+        [quo/button {:icon     true
+                     :type     :grey
+                     :size     32
+                     :style    {:margin-vertical 12}
+                     :on-press #(rf/dispatch [:navigate-back])}
+         :i/close]
+        [screen-title]
+        (featured-communities-header (:value  @communities-count))
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: `(` shouldn't be used , only `[`

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 7]
```diff
@@ -34,105 +31,102 @@
...
   [rn/flat-list
    {:key-fn                            :id
-    :horizontal                        true
-    :getItemLayout                     get-item-layout-js
     :keyboard-should-persist-taps      :always
     :shows-horizontal-scroll-indicator false
+    :separator                 [rn/view {:margin-bottom 16}]
     :data                              communities
-    :render-fn                         render-featured-fn}])
+    :render-fn                         (render-fn false "100%")}])
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: :render-data should be used instead

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 8]
```diff
@@ -34,105 +31,102 @@
...
-                   :type     :grey
-                   :size     32
-                   :style    {:margin-vertical 12
-                              :margin-left     20}
-                   :on-press #(rf/dispatch [:navigate-back])}
-       :i/close]
-      [screen-title]
-      [other-communities]])])
+        sorted-communities (sort-by :name communities)
+        view-size (reagent/atom 0)]
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: same for this atom

Comment (flexsurfer) [reply src/status_im2/contexts/communities/discover/view.cljs]: btw why do you create it here if its used only in featured-list

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 9]
```diff
@@ -34,105 +31,102 @@
...
+                                           (oops/oget % "nativeEvent.layout.width")))}
+   (when-not (= @view-size 0)
+     [rn/flat-list
+      {:key-fn                            #(str "featured" (% :id))
+       :horizontal                        true
+       :keyboard-should-persist-taps      :always
+       :shows-horizontal-scroll-indicator false
+       :separator                  [rn/view {:margin-right 12}]
+       :data                              communities
+       :render-fn                         (render-fn true @view-size)}])])
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: same here :render-data should be used, anon functions shouldn't  be used  for render-fn

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 10]
```diff
@@ -34,105 +31,102 @@
...
+(defn featured-list [communities view-size]
+  [rn/view {:style {:flex-direction :row
+                    :overflow :hidden
+                    :width "100%"
+                    :margin-bottom 24}
+            :on-layout #(swap! view-size (fn []
+                                           (oops/oget % "nativeEvent.layout.width")))}
+   (when-not (= @view-size 0)
+     [rn/flat-list
+      {:key-fn                            #(str "featured" (% :id))
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: it could be just :id , what featured gives ?

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 11]
```diff
@@ -34,105 +31,102 @@
...
-                         (rf/dispatch [:navigate-to :community {:community-id (:id item)}]))
-        :on-long-press #(rf/dispatch [:bottom-sheet/show-sheet
-                                      {:content (fn []
+(defn render-fn [featured? width]
+  (fn
+    [community-item]
+    (let [item (merge community-item
+                      (get mock-community-item-data :data)
+                      {:featured featured?})]
+      (if (= @view-type :card-view)
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: we shouldn't use global atoms, this should be passed as parameter

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 10 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: because the data for both of these is the same so then it creates duplicate keys. or am I wrong about this? 🤔

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 11 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: you're referring to @view-type? . That code was already there. I figured it's a placeholder until live data is being passed in. But not sure why it was like that.

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 10 above)
Comment (flexsurfer) [reply src/status_im2/contexts/communities/discover/view.cljs]: i mean `str "featured"` is constant, so key still will be duplicated

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 11 above)
Comment (flexsurfer) [reply src/status_im2/contexts/communities/discover/view.cljs]: yeah i know, but we should fix it, as you're working on it anyway :)

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 10 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: hmm, 

no other communities iss using `:id`, featured is using "featured + :id"

I will revisit anyway 👍

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 12]
```diff
@@ -4,19 +4,16 @@
...
-
+            [oops.core :as oops]
             ;; TODO move to status-im2
             [status-im.react-native.resources :as resources]
             [status-im.ui.screens.communities.community :as community]))
 
 (def view-type (reagent/atom :card-view))
 
-(def mock-community-item-data                               ;; TODO: remove once communities are loaded with this data.
+(def mock-community-item-data  ;; TODO: remove once communities are loaded with this data.
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/view.cljs:14]: Double semicolon should use a separate line.

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 13]
```diff
@@ -34,105 +31,102 @@
...
-                         (rf/dispatch [:communities/load-category-states (:id item)])
-                         (rf/dispatch [:dismiss-keyboard])
-                         (rf/dispatch [:navigate-to :community {:community-id (:id item)}]))
-        :on-long-press #(rf/dispatch [:bottom-sheet/show-sheet
-                                      {:content (fn []
+(defn render-fn [featured? width]
+  (fn
+    [community-item]
+    (let [item (merge community-item
+                      (get mock-community-item-data :data)
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/view.cljs]: I wish we could code against fake data as if the implementation was *final* so that when the real data is available, nothing needs to change. In other words, the view should never know if the data is real or not because it's not its concern.

For example, view components should already correctly use a subscription and the fake data should be hidden behind the subscription; global vars to hold fake data shouldn't be used; bindings with the word "fake" in them shouldn't be used, etc.

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 14]
```diff
@@ -34,105 +31,102 @@
...
    [quo/text {:accessibility-label :communities-screen-title
               :weight              :semi-bold
               :size                :heading-1}
     (i18n/label :t/discover-communities)]])
 
-(defn featured-communities [communities]
+(defn featured-communities-header [communities-count]
+  [rn/view {:flex-direction     :row
+            :height             30
+            :margin-bottom 8
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/view.cljs:62]: Could you please reformat this file? There are some misaligned things, like this line.

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 8 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/discover/view.cljs]: As @flexsurfer commented, this is going to cause an unnecessary rerender of the entire `discover` component whenever on-layout handler swaps the atom.

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 11 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: cool, I will update :)

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 13 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: yeah I agree, I'm not quite sure how long until we have access to these real data points. I will raise this discussion in the features breakdown today, as maybe it's a good idea to move all of this mock data to a centralised place similar to what you are describing.

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 14 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs:62]: sure :D

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 13 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/discover/view.cljs]: Thanks @J-Son89. This can save us some time in the future and it makes code review a bit easier (at least for me) because then everyone is on the same page to treat the data flowing as if it was production data.

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 8 above)
Comment (flexsurfer) [reply src/status_im2/contexts/communities/discover/view.cljs]: actually, it's not the problem, problem is that atom will be redefined with default value when one of subscription will change

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 15]
```diff
@@ -51,88 +47,94 @@
...
+                        :margin-bottom 24}
+                :on-layout #(swap! view-size
+                                   (fn []
+                                     (oops/oget % "nativeEvent.layout.width")))}
+       (when-not (= @view-size 0)
+         [rn/flat-list
+          {:key-fn                            :id
+           :horizontal                        true
+           :keyboard-should-persist-taps      :always
+           :shows-horizontal-scroll-indicator false
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs:95]: align map

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 16]
```diff
@@ -51,88 +47,94 @@
...
+           :separator                  [rn/view {:margin-right 12}]
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: thars weird separator

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 16 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: why so? it's a horizontal scroll in the designs

Comment (flexsurfer) [reply src/status_im2/contexts/communities/discover/view.cljs]: oh, then it could be like [rn/view {:width 12}]] because an empty separator with only a margin looks strange, yeah but anyway, now i know its like a gap between items

Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: okay, yeah that also makes sense.
