### PR TITLE
Remove old quo code from status_im2 namespace

### LINKED ISSUE #17273: Remove all old quo requires within status-im2 namespaces
find all usages of `[quo.` in `status-im2` namespace, and replace them by quo2 or other namespaces, also lint should fail (not just warning) for `[quo.` usage in `status-im2`

status_im2.common.qr_code_viewer
style.cljs
(:require [quo.design-system.colors :as colors]))
**replace by quo2 colors**

status_im2.common.theme
core.cljs
(:require [quo.theme :as quo]

status_im2.contexts.chat.messages.content
legacy_view.cljs
[quo.design-system.colors :as quo.colors]
[quo.react-native :as rn]
**replace by quo2 colors and react-native**

status_im2.contexts.chat.messages.content.text
style.cljs
[quo.platform :as platform]))
**replace by react-native.platform**

status_im2.contexts.quo_preview.community
community_card_view.cljs
(:require [quo.design-system.colors :as quo.colors]
data.cljs
(:require [quo.design-system.colors :as quo.colors]
**replace by quo2 colors**

status_im2.contexts.quo_preview.inputs
profile_input.cljs
[quo.react-native :as rn]))
**replace by react-native**

status_im2.contexts.quo_preview.notifications
activity_logs.cljs
[quo.theme/provider {:theme :dark}

status_im2.contexts.quo_preview.onboarding
small_option_card.cljs
[quo.react-native :as rn]
**replace by react-native**

status_im2.contexts.quo_preview.tags
tag.cljs
(:require [quo.react-native :as rn]
**replace by react-native**

status_im2.contexts.syncing.sheets.enter_password
view.cljs
[quo.core :as quo-old]

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #17273 

status: ready

### CODE REVIEW

**Comment by ajayesivan** [comment]
Testing lint in ci. I will request review once ready.

File: src/status_im2/common/theme/core.cljs [hunk 1]
```diff
@@ -31,5 +30,4 @@
 
 (defn set-theme
   [value]
-  (quo/set-theme value)
```
Comment (ajayesivan) [inline src/status_im2/common/theme/core.cljs]: @Parveshdhull, it appears that this was introduced during the [Refactor app theme management](https://github.com/status-im/status-mobile/pull/15455/files#diff-171c55d08d05cd1b3a6f75b068b1585a549769cc452d02b4c00a1556d351b3c8R23-R24) process. I am in the process of removing it as part of the refactoring. I wanted to inform you of this change and ensure that it does not impact any essential functionality.

File: scripts/lint-old-quo-usage.sh [hunk 2]
```diff
@@ -0,0 +1,11 @@
+#!/usr/bin/env sh
+
```
Comment (jakubgs) [inline scripts/lint-old-quo-usage.sh:2]:
```suggestion
set -euo pipefail
```

File: Makefile [hunk 3]
```diff
@@ -311,6 +311,7 @@ endef
 lint: export TARGET := clojure
 lint: ##@test Run code style checks
 	@sh scripts/lint-re-frame-in-quo-components.sh && \
+	sh scripts/lint-old-quo-usage.sh && \
```
Comment (jakubgs) [inline Makefile]: Is there any good reason why we are doing all of this silly `&& \` stuff? The only place I can think of is where `ALL_CLOJURE_FILES` is used, but that can be don in-line.

**Review by flexsurfer — APPROVED** [review]
it seems like `ns quo.theme` can be removed now

**Review by Parveshdhull — APPROVED** [review]

File: scripts/lint-old-quo-usage.sh (hunk 2 above)
Comment (ajayesivan) [reply scripts/lint-old-quo-usage.sh:2]: @jakubgs I added this.

To handle the scenario when the `grep` command does not find any matches and prevent it from causing script termination, `|| true` has been added to `grep`. I'm not completely sure if this is the right way to handle this. Let me know if you have any suggestions.

File: Makefile (hunk 3 above)
Comment (ajayesivan) [reply Makefile]: I just copied the code without paying much attention 😬. I've now corrected the line I added.

It seems there are multiple instances where we've used `&& \` where it may not be necessary. I think it's better to address this in a separate PR. @jakubgs, wdyt?

File: scripts/lint-old-quo-usage.sh (hunk 2 above)
Comment (jakubgs) [reply scripts/lint-old-quo-usage.sh:2]: If failure to find instances via `grep` is expected then you can just drop the `-o pipefail` part.

File: Makefile (hunk 3 above)
Comment (jakubgs) [reply Makefile]: That fair.

File: scripts/lint-old-quo-usage.sh (hunk 2 above)
Comment (ajayesivan) [reply scripts/lint-old-quo-usage.sh:2]: grep not finding any instances is expected.

Do you mean the entire line `set -euo pipefail` or just `-o pipefail` and keep `set -eu`?

I tried removing the `-o pipefail` part, but still the script terminates when grep doesn't find anything. It seems that the `-e` option is causing this behavior. When I removed `-e` and used `set -uo pipefail`, the script worked without needing the `|| true` part.

I have limited knowledge in this area.

Comment (jakubgs) [reply scripts/lint-old-quo-usage.sh:2]: Oh, i see now, you're grepping the files directly. That's fine then, using `|| true` is a good solution.

**Review by jakubgs — APPROVED** [review]

**Comment by ajayesivan** [comment]
From my understanding, the failing e2e tests are not related to this PR. Could someone from QA please confirm @status-im/mobile-qa?

**Comment by VolodLytvynenko** [comment]
hi @ajayesivan currently, there are e2e failures occurring due to data delivery issues. I can quickly check manually to see if everything is alright. Could you please point out the possible areas that may be impacted by this PR?

**Comment by ajayesivan** [comment]
Hi @VolodLytvynenko, This PR removes the old quo usage in the new code and replaces it with the quo2 counterpart. I don't think this one requires any manual testing. I found 1 preexisting UI issue and reported it here: https://github.com/status-im/status-mobile/issues/17407.

**Comment by VolodLytvynenko** [comment]
hi @ajayesivan one issue has been found that was introduced by this PR. The elements appear as light on the dark theme. This issue seems to affect only the old elements of the app, which I assume will be updated in the future. However, it looks a bit unattractive for now :) Is there something we can do to resolve this?

### Steps:
1. Enable dark mode on the app
2. Navigate to the old elements of the app

### Actual result:
image
image
image

File: src/status_im2/common/theme/core.cljs (hunk 1 above)
Comment (ajayesivan) [reply src/status_im2/common/theme/core.cljs]: We need to put this `quo/set-theme` usage back to fix the issue shared by @VolodLytvynenko here: https://github.com/status-im/status-mobile/pull/17404#issuecomment-1735060373. Otherwise, the old UI elements will be broken until we fully migrate everything.

I can put this back and exclude this file from the linting script for now and create a follow-up issue to remove this usage later. @flexsurfer What do you suggest?

Comment (flexsurfer) [reply src/status_im2/common/theme/core.cljs]: let's do the hack  for now, just set quo/set-theme to the atom and use atom here, so we could keep quo linting error, so nobody uses quo by mistake

Comment (flexsurfer) [reply src/status_im2/common/theme/core.cljs]: yeah i was wondering why you didn't remove quo.theme then, so it's still used

**Comment by ajayesivan** [comment]
@VolodLytvynenko I have fixed the issue you reported. Could you please test again? Thanks!

File: src/status_im2/common/theme/core.cljs (hunk 1 above)
Comment (ajayesivan) [reply src/status_im2/common/theme/core.cljs]: @flexsurfer correct me if I'm wrong, but from my understanding, we can't start removing code until we remove all status_im usage from status_im2.

I didn't get what you meant by 'set quo/set-theme to the atom and use atom here'. Could you please elaborate?

**Comment by VolodLytvynenko** [comment]
Hi @ajayesivan Thank you for fixed. Other issues are not related to this PR. Ready to be merged

File: src/status_im2/common/qr_code_viewer/style.cljs [hunk 4]
```diff
@@ -1,5 +1,5 @@
 (ns status-im2.common.qr-code-viewer.style
-  (:require [quo.design-system.colors :as colors]))
+  (:require [quo2.foundations.colors :as colors]))
```
Comment (J-Son89) [inline src/status_im2/common/qr_code_viewer/style.cljs:2]: 🙏
