### PR TITLE
fix: Scroll to bottom button click not working

### LINKED ISSUE #14557: "Scroll to the last message" button does nothing on IOS
# Bug Report

## Problem 
Scrolling to the end of the chat history doesn't work on IOS.

#### Expected behavior
scroll to the end of the chat history

#### Actual behavior

https://user-images.githubusercontent.com/4557972/207922271-eaf7c55b-ec5d-4330-817e-886da2c59f77.MP4
(I'm tapping here on the button constantly)

### Reproduction

1) Open Status
2) Send several big messages in order to see button
3) Scroll to the start of the history
4) Try to tap on the button "scroll to the last message" 

### Additional Information

- Status version: nightly 15/12/22
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ajayesivan**
Fixes #14557

### Summary
'Jump to' button's invisible area(area with no background color) was covering the 'scroll-to bottom' button. Both buttons have `absolute` position. Fixed it by adding `z-index: 1` to 'scroll to bottom' button.

#### Platforms
- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test
1. Open Status
2. Open a chat that has a lot of messages(should be able scroll and enable 'scroll to bottom' button)
3. Scroll to the top - until the scroll to bottom button appears
4. Click on the 'scroll to bottom' button and see if it scrolls to the latest message.

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by du82** [comment]
@ajayesivan  We should be using the button from the component. The height is also wrong.

**Comment by ajayesivan** [comment]
> @ajayesivan We should be using the button from the component. The height is also wrong.

Using dynamic-button component from quo2

**Comment by du82** [comment]
The button still doesn't match the height, and is now transparent when both should be solid

Screenshot_2022-12-16-23-00-29-52_65ad86f86fd2321a85272a99323da10f

**Comment by Parveshdhull** [comment]
> > @ajayesivan We should be using the button from the component. The height is also wrong.
> 
> Using dynamic-button component from quo2

We should not add another dynamic button for down arrow, [floating-shell-button](https://github.com/status-im/status-mobile/blob/develop/src/quo2/components/navigation/floating_shell_button.cljs) already has one. But currently hidden by default. We can use that.
https://github.com/status-im/status-mobile/blob/7b72391e6073af7a802c065c114b783dab1c2b47/src/status_im2/contexts/chat/messages/view.cljs#L77

**Comment by du82** [comment]
UI looks good to me!

**Comment by Parveshdhull** [comment]
Scroll to bottom still not working for me in ios.

Also please fix tests,
try `make lint-fix` or `make lint` to see errors

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 1]
```diff
@@ -186,5 +172,9 @@
         :inverted                     (when platform/ios? true)
         :style                        (when platform/android? {:scaleY -1})
         :on-layout                    on-messages-view-layout})]
-     (when @show-floating-scroll-down-button
-       [floating-scroll-down-button show-input?])]))
+     [quo/floating-shell-button
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/list/view.cljs:191]: Please, re-align this code hunk.

**Review by ilmotta — APPROVED** [review]
Unfortunately I can't test in iOS environments to help more in this PR review, but as far as I've checked it's working fine in the Android emulator.

Apart from indentation issues and the lint error, the code LGTM.

**Comment by ajayesivan** [comment]
Fixed the lint issue. 

I have tested on both iOS(Simulator) & Android(Device: Samsung Galaxy M30s) the scroll-to-bottom functionality is working fine. @Parveshdhull in case the scroll is still not working for you, could you please share more info that can help me reproduce the issue, like the device/simulator you are using?

**Comment by Parveshdhull** [comment]
Hi @ajayesivan,
Thank you for fixing tests.
I might have accidentally used old build or something, fix is working perfectly Thank you

**Comment by VolodLytvynenko** [comment]
Hi @ajayesivan! Could you please rebase the PR and resolve existing conflicts. After that we can perform manual testing. Thanx!

**Comment by ajayesivan** [comment]
> Hi @ajayesivan! Could you please rebase the PR and resolve existing conflicts. After that we can perform manual testing. Thanx!

Done 👍

**Comment by VolodLytvynenko** [comment]
@ajayesivan PR is tested and ready to be merged. Thanx for your job. Failures that are shown in e2e tests are not related to your PR
