### PR TITLE
fix: address is lost on re-render

### LINKED ISSUE #18494: Send flow: address is lost on re-render
On the send_input screen, trying to re-render the screen while on the send_input page causes routes not to be fetched. 

To fetch the routes again, the address needs to be reselected from the select_address screen. (seems the address is temporarily saved, then lost on re-render)

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18494 

### Summary

This PR fixes `:to-address` key is lost on re-render, causing some issues on developer experience. Key changes are:
- Add a new `:modal-view-ids` key to our db so we can maintain a vector of the ids in a modal stack, if there's any modal being displayed
- Added a new `:navigation/current-screen-id` sub which returns the current screen id being displayed. It can be the last element of `:modal-view-ids` or `:view-id`
- Added some checks on Address Input component in Select Address screen to prevent some events being dispatched on re-render if the screen is not the one currently displayed, to prevent clearing some keys in the db
- Not strictly related to this issue, but added some checks on Input Amount for suggested routes, similar to what I did on Select Address screen
- Updated some misuses of `:fx` and `:navigate-to-within-stack` in our send events, where we were not dispatching events and some side-effects where missing (like updating the db)

#### Platforms

- Android
- iOS

### Steps to test (for devs)

- Open Status
- Login
- Open wallet
- Select an account
- Select Send
- Input an address
- Select a token
- Input some amount
- Tap continue
- Trigger re-renders at different parts of the flow, and check address is not lost on re-render

### Steps to test (for QA)

- A smoke testing would be fine

status: ready

### CODE REVIEW

**Review by OmarBasem — APPROVED** [review]

**Review by shivekkhurana — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater ! Can you rebase your PR please?

**Comment by briansztamfater** [comment]
> Hi @briansztamfater ! Can you rebase your PR please?

Done!

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -50,7 +50,7 @@
    {:db (-> db
             (assoc-in [:wallet :ui :send :send-account-address] address)
             (update-in [:wallet :ui :send] dissoc :to-address))
-    :fx [[:navigate-to-within-stack [:wallet-select-asset stack-id]]]}))
+    :fx [[:dispatch [:navigate-to-within-stack [:wallet-select-asset stack-id]]]]}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:55]: I think we don't need to to this :thinking: 

In the previous code we are calling the effect `:navigate-to-within-stack` with its navigation parameters, the effect is defined in the ns `status-im.navigation.effects`.

In the new code we are calling the effect `:dispatch` and telling it to call the event `:navigate-to-within-stack` defined in `status-im.navigation.events`, this event is calling the previous mentioned effect.

So we are just adding a redirection.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 2]
```diff
@@ -66,10 +66,11 @@
...
               (assoc-in [:wallet :ui :send :selected-networks] selected-networks))
-      :fx [[:navigate-to-within-stack
-            (if token
-              [:wallet-send-input-amount stack-id]
-              [:wallet-select-asset stack-id])]]})))
+      :fx [[:dispatch
+            [:navigate-to-within-stack
+             (if token
+               [:wallet-send-input-amount stack-id]
+               [:wallet-select-asset stack-id])]]]})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:79]: Same comment as before about the event and the effect

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 3]
```diff
@@ -124,14 +124,16 @@
...
-                                (rf/dispatch [:wallet/clean-suggested-routes])
-                                (when-not (or
-                                           (empty? @input-value)
-                                           (<= input-num-value 0)
-                                           (> input-num-value (:amount @current-limit)))
-                                  (debounce/debounce-and-dispatch [:wallet/get-suggested-routes
-                                                                   @input-value]
-                                                                  100)))]
+                                (let [current-screen-id (rf/sub [:navigation/current-screen-id])]
+                                  (when (= current-screen-id :wallet-send-input-amount)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: This is a reasonable fix, but it'd be good to add a comment. it may be removed in a later refactor

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 4]
```diff
@@ -143,7 +145,9 @@
           :accessibility-label (str "container" (when @input-error "-error"))}
          [account-switcher/view
           {:icon-name     :i/arrow-left
-           :on-press      #(rf/dispatch [:navigate-back-within-stack :wallet-send-input-amount])
+           :on-press      (fn []
+                            (rf/dispatch [:wallet/clean-selected-token])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: :100:

File: src/status_im/contexts/wallet/send/select_address/view.cljs [hunk 5]
```diff
@@ -40,13 +41,15 @@
         :ens-regex             constants/regx-ens
         :scanned-value         (or (when recipient-plain-address? send-address) scanned-address)
         :address-regex         constants/regx-multichain-address
-        :on-detect-address     #(debounce/debounce-and-dispatch
-                                 [:wallet/validate-address %]
-                                 300)
+        :on-detect-address     #(when (= current-screen-id :wallet-select-address)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/select_address/view.cljs]: I'm wondering why this works.

This event should only be called when we are in the current screen, otherwise we can't call it (becuse there's no input mounted) right?

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 6]
```diff
@@ -128,10 +128,7 @@
 
 (defn- view-internal
   [_]
-  (let [on-close (fn []
-                   (rf/dispatch [:wallet/clean-suggested-routes])
-                   (rf/dispatch [:navigate-back-within-stack :wallet-select-asset]))]
-
+  (let [on-close #(rf/dispatch [:navigate-back-within-stack :wallet-select-asset])]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:140]: :+1:

File: src/status_im/navigation/events.cljs [hunk 7]
```diff
@@ -26,21 +26,26 @@
 
 (rf/defn navigate-to-within-stack
   {:events [:navigate-to-within-stack]}
-  [_ comp-id]
-  {:navigate-to-within-stack comp-id})
+  [{:keys [db]} comp-id]
+  (let [modal-view-ids (not-empty (:modal-view-ids db))]
+    (merge {:navigate-to-within-stack comp-id}
+           (when modal-view-ids
+             {:db (assoc db :modal-view-ids (conj modal-view-ids (first comp-id)))}))))
```
Comment (ulisesmac) [inline src/status_im/navigation/events.cljs]: Hey @briansztamfater 
I'd like to suggest a refactor because of two aspects:
1. use `:fx` to dispatch events/effects
2. make clearer the logic to handle  modals (btw, don't we have an event that handles this logic).

Just a question:
We are using `conj` on `modal-views-ids` is this a list or a vector? let's just be careful about it because they `conj` in different positions, do we care about the order?

my suggestion is:
1. Create a function that has the logic to append data to `modal-views-ids`:
```clojure
(defn- add-view-to-modals [modal-view-ids new-id]
  (if (seq modal-view-ids) ;; same as (not (empty? _))
    (conj modal-view-ids new-id)
    modal-view-ids))
```

2. Use it in the event handler and use `:fx`:
```clojure
{:db (update db :modal-view-ids add-view-to-modals (first comp-id))
 :fx [[:navigate-to-within-stack comp-id]]}
```

btw, why do we only `conj` when the modal-views-ids is not empty?

File: src/status_im/navigation/events.cljs [hunk 8]
```diff
@@ -49,13 +54,25 @@
 
 (rf/defn navigate-back-within-stack
   {:events [:navigate-back-within-stack]}
-  [_ comp-id]
-  {:navigate-back-within-stack comp-id})
+  [{:keys [db]} comp-id]
+  (let [modal-view-ids (not-empty (:modal-view-ids db))]
+    (merge {:navigate-back-within-stack comp-id}
+           (when modal-view-ids {:db (assoc db :modal-view-ids (pop modal-view-ids))}))))
```
Comment (ulisesmac) [inline src/status_im/navigation/events.cljs]: Same suggestion as before :eyes:

File: src/status_im/navigation/events.cljs [hunk 9]
```diff
@@ -49,13 +54,25 @@
...
+        comp-id-index  (when modal-view-ids (.indexOf modal-view-ids comp-id))
+        modal-view-ids (when modal-view-ids
+                         (if (>= comp-id-index 0)
+                           (subvec vec 0 (inc comp-id-index))
+                           vec))]
+    (assoc {:navigate-back-to comp-id}
+           :db
+           (if modal-view-ids
+             (assoc db :modal-view-ids modal-view-ids)
+             (dissoc db :modal-view-ids)))))
```
Comment (ulisesmac) [inline src/status_im/navigation/events.cljs]:
```clojure
(subvec vec 0 (inc comp-id-index)
;;      ^^^ is this the `vec` function?
```

Also it'd be good to simplify the logic a little, maybe extracting to a separate named function

File: src/status_im/subs/navigation.cljs [hunk 10]
```diff
@@ -0,0 +1,11 @@
...
+  (:require
+    [re-frame.core :as re-frame]))
+
+(re-frame/reg-sub
+ :navigation/current-screen-id
+ :<- [:view-id]
+ :<- [:modal-view-ids]
+ (fn [[view-id modal-view-ids]]
+   (let [modal-view-ids (not-empty modal-view-ids)]
+     (if modal-view-ids (last modal-view-ids) view-id))))
```
Comment (ulisesmac) [inline src/status_im/subs/navigation.cljs]: If `modal-view-ids` is a vector we can use `peek` (fast `last` for vectors) and it works with `nil`, so we don't need to check if it's `not-empty` or not.
so

```clojure
(fn [[view-id modal-view-ids]]
   (or (peek modal-view-ids) view-id))
```
should do the job, substitute `peek` for `last` if we are dealing with list or the type is unsure.

**Review by ulisesmac — COMMENTED** [review]
Hey @briansztamfater 

I left some comments, sorry for the late review!

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/events.cljs:55]: HI @ulisesmac, this is because we need to update `:modal-stack-ids` in app db, not just execute the push in `react-native-navigation`, also checked and this is how we are dispatching navigation events through the app in events. Without this, sub `:navigation/current-screen-id` would return wrong data.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 3 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: Will add!

File: src/status_im/subs/navigation.cljs (hunk 10 above)
Comment (briansztamfater) [reply src/status_im/subs/navigation.cljs]: Nice one, thanks for the suggestion!

File: src/status_im/navigation/events.cljs (hunk 7 above)
Comment (briansztamfater) [reply src/status_im/navigation/events.cljs]: Thanks for the suggestion @ulisesmac! I'll implement this refactor, looks much cleaner 💯 

> btw, why do we only conj when the modal-views-ids is not empty?

`:navigate-to-within-stack` is likely to be used when navigating within a modal stack, but it can happen that the same screen could be inside a modal stack _or_ inside the root stack, and still `:navigate-to-within-stack` can work for both situations. In the last case, there is no need to update `:modal-view-ids` because we would be just navigating within the root stack, that's why we do the check.

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs:55]: Really interesting.
It seems we are just delaying the evaluation of the navigation to let other re-frame updates successfully happen.

Too much to ask for :sweat_smile:  but if you are free at some point, could you please check (it's a long discussion, it's ok if you can't):
https://github.com/status-im/status-mobile/pull/18532#issuecomment-1909279658

Basically, I'm delaying the navigation to let re-frame properly update it's state.

File: src/status_im/contexts/wallet/send/select_address/view.cljs (hunk 5 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/select_address/view.cljs]: That's right, when we save code and app re-renders, `useEffect`s of components inside pages that are loaded but are deep in the navigation stack are triggered, causing some undesired behavior. We may revisit usage of useEffect in some components, but at the meantime it doesn't hurt to add this check.

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/events.cljs:55]: It's super interesting, indeed. We are updating the db also in our main `:navigate-to` event. Here https://github.com/status-im/status-mobile/blob/01d1ff0cfb0a863d294937dea91b892237aa7c49/src/status_im/contexts/shell/jump_to/events.cljs#L121-L155
 and here https://github.com/status-im/status-mobile/blob/972a88e7ccc9fd5fc697caa42919079a4da73859/src/status_im/navigation/events.cljs#L18-L25

I've read the discussion, really interesting data shared there BTW. If I understood correctly, the db is updated properly, but the problems appear when using subscriptions in the mount phase. What if you dispatch the event without delay instead of using effect? That's how navigation events are used though the app, and may have caused the issue in that PR, not sure.

But wondering and interesting to see how much of performance trade-offs have this db updates before navigating, and how we can improve this in the future.

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater!

**ISSUE 1  Receiver address loading has stucked after it was scanned**

Steps:

1. Open Status
2. Login
3. Open wallet
4. Select an account
5. Select Send
6. Input an address by scaning QR-code of another user

**Actual result:**
Continue button is disabled, loading icon near address
photo_2024-01-29_11-58-50

**Expected result:** 
address should be loaded successfully and Continue button should become active

Additional details: iOS and Android

**Comment by briansztamfater** [comment]
> Hi @briansztamfater!
> 
> **ISSUE 1 Receiver address loading has stucked after it was scanned**
> 
> Steps:
> 
> 1. Open Status
> 2. Login
> 3. Open wallet
> 4. Select an account
> 5. Select Send
> 6. Input an address by scaning QR-code of another user
> 
> **Actual result:** Continue button is disabled, loading icon near address photo_2024-01-29_11-58-50
> 
> **Expected result:** address should be loaded successfully and Continue button should become active
> 
> Additional details: iOS and Android

Hi @mariia-skrypnyk, thanks for testing! Issue should be fixed now 💪 Let me know if you find anything else

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs:55]: > What if you dispatch the event without delay instead of using effect?

It seems the `:dispatch` is not enough, we need even more delay, at least 1ms and sometimes it is still happening.

File: src/status_im/contexts/wallet/send/select_address/view.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/select_address/view.cljs]: Oh, now I see :thinking: 

Interesting, and probably not easy to give a general fix.

File: src/status_im/navigation/events.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/status_im/navigation/events.cljs]: thanks for the clarification!

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater !
Thanks for the fix with address loading.
Let me show you what I've found next:

**ISSUE 2 No routs after user put assets amount** 

**Steps**

1. Open Status
2. Login
3. Open wallet
4. Select an account
5. Select Send
6. Input an address
7. Select a token
8. Input some amount

**Actual result:**
No routs and Continue button is disabled

https://github.com/status-im/status-mobile/assets/147824399/1e3eca48-6b32-4fa4-a965-27f405b2209c


**Expected result:**
Routs appeared after user put assets amount

**Comment by mariia-skrypnyk** [comment]
> Hi @briansztamfater ! Thanks for the fix with address loading. Let me show you what I've found next:
> 
> **ISSUE 2 No routs after user put assets amount**
> 
> **Steps**
> 
> 1. Open Status
> 2. Login
> 3. Open wallet
> 4. Select an account
> 5. Select Send
> 6. Input an address
> 7. Select a token
> 8. Input some amount
> 
> **Actual result:** No routs and Continue button is disabled
> 
>  IMG_6550.MP4 
> **Expected result:** Routs appeared after user put assets amount

I returned to this scenario and saw this as a result of the same steps:
photo_2024-01-30_12-05-12

strange behaviour anyway

**Comment by mariia-skrypnyk** [comment]
**ISSUE 3 Continue button doesn't become active 1-2 seconds before address is set and checked**

**Steps**

Open Status
Login
Open wallet
Select an account
Select Send
Input an address

**Actual result:**
Continue button doesn't become active 1-2 seconds before address is set and checked

https://github.com/status-im/status-mobile/assets/147824399/9a645440-b9e9-4e63-bf0d-2cd66749446a

**Expected result:** 
As an app user I feel  myself uncomfortable to wait so long. It would be great if you find the way to improve this time.

**Comment by briansztamfater** [comment]
Hey @mariia-skrypnyk, thanks for testing again. Regarding issue 2, I think that's happening on develop branch, at least I was able to reproduce it there. Can you check?

About issue 3, I think it will be solved on #18626, so let's wait until that one is merged so I can rebase and then we can resume testing on this one.

**Comment by mariia-skrypnyk** [comment]
> Hey @mariia-skrypnyk, thanks for testing again. Regarding issue 2, I think that's happening on develop branch, at least I was able to reproduce it there. Can you check?
> 
> About issue 3, I think it will be solved on #18626, so let's wait until that one is merged so I can rebase and then we can resume testing on this one.

Thanks @briansztamfater ! Make sense!
And regarding the issue 2: I see we do have [this](https://github.com/status-im/status-mobile/issues/18652) issue reported so I think no need to mention it in this PR.

**Comment by mariia-skrypnyk** [comment]
> Hey @mariia-skrypnyk, thanks for testing again. Regarding issue 2, I think that's happening on develop branch, at least I was able to reproduce it there. Can you check?
> 
> About issue 3, I think it will be solved on #18626, so let's wait until that one is merged so I can rebase and then we can resume testing on this one.

Hi @briansztamfater !

I see you are going to merge this https://github.com/status-im/status-mobile/pull/18626 so I am near to re-test Issue 3.
Let me know when I can start!

**Comment by briansztamfater** [comment]
@mariia-skrypnyk ready to re-test 💪

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk ready to re-test 💪

@briansztamfater Thanks! Can you do a rebase please?

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater thanks for your fix! 👍 
Failed tests are not related to your PR.

Please, feel free to merge.
