### PR TITLE
fix visibility dropdown alignment in new ui

### LINKED ISSUE #13758: Visibility status dropdown is not aligning in new design
Original Report https://github.com/status-im/status-mobile/pull/13747#issuecomment-1204048691

Regression from https://github.com/status-im/status-mobile/pull/13717

image

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/13758

status: ready

### CODE REVIEW

File: src/status_im/subs.cljs [hunk 1]
```diff
@@ -1576,7 +1576,7 @@
  :<- [:home-items-show-number]
  (fn [[search-filter filtered-chats communities view-id home-items-show-number]]
    (if (or (= view-id :home)
-           (and config/new-ui-enabled? (= view-id :chat-stack)))
+           (and @config/new-ui-enabled? (= view-id :chat-stack)))
```
Comment (Parveshdhull) [inline src/status_im/subs.cljs:1579]: Not related to PR, but a separate small bug reported [here](https://github.com/status-im/status-mobile/pull/13747#discussion_r935414648)

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hi @Parveshdhull, thanks for PR!
Can you take a look at the conflicting file before I start testing, please?

**Comment by qoqobolo** [comment]
@Parveshdhull thanks for reporting the issue and for the fix!
PR is tested and can be merged.
