### PR TITLE
fix(wallet)_: collectible route cleanup on navigating back from TX confirmation page

### LINKED ISSUE #21882: "Context Canceled" Error and "No Routes Found" message on Collectible Send flow when using device back button
follow up for https://github.com/status-im/status-mobile/pull/21871

### Steps to Reproduce:
1. Navigate to the Collectible Send Flow.
2. Proceed to the Collectible Confirmation TX Send Page.
3. Tap the device's Back Button to navigate back.
4. Re-enter the Collectible Confirmation TX Send Page.

### Actual Result:
A "Context canceled" error and a "No routes found" message are displayed.

https://github.com/user-attachments/assets/51621109-ffdb-4ed1-812b-a4ced1fcaad9

### Expected Result:
The user can re-enter the confirmation TX send page without encountering errors

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1LDJzz331PdbbkBl0OcRbtFsWzXRB0Den/view?usp=drive_link

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21882

### Summary

This PR fixes routes not cleaned properly (`Context Canceled` and `No Routes Found` errors thrown on generating the next route) when the user navigates back from the TX confirmation screen using the device's back button/gesture.

### Platforms

- Android
- iOS

##### Prerequisite: A wallet account with multiple collectibles

- Open Status
- Navigate to the Wallet Tab
- Tap any collectible and enter the Send flow
- Complete the flow until the TX confirmation screen
- Navigate back using the device's back button or gesture
- Try to complete the flow again (reaching the TX confirmation page)
- Verify the `Context Canceled` and `No Routes Found` error messages are not shown

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/collectible/utils.cljs [hunk 1]
```diff
@@ -2,14 +2,15 @@
...
 (defn collectible-balance
   ([{:keys [ownership]} address]
-   (let [balance (some #(when (= address (:address %))
-                          (js/parseInt (:balance %)))
-                       ownership)]
-     (if (js/Number.isNaN balance) 0 balance))))
+   (->> ownership
+        (some #(when (= address (:address %))
+                 (:balance %)))
+        utils.number/parse-int)))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/collectible/utils.cljs:13]: Small refactoring of collectible balance util method based on https://github.com/status-im/status-mobile/pull/21871#discussion_r1900847647

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:1]: The only changes on this screen are 
 - Removed the let var `on-close` as the navigate-back and clean-up events are separated
 - Removed the `fn` wrap as the functional compiler is the default
 - Moved the clean-up event to unmount (previously it was in a separate `let` var), as the event is not called when the user uses the device's back button/gesture.

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 2]
```diff
@@ -210,125 +212,124 @@
...
+                                   :name                (:name account)
+                                   :address             (utils/get-shortened-address
+                                                         (:address
+                                                          account))}
+        user-props                {:full-name to-address
+                                   :address   (utils/get-shortened-address
+                                               to-address)}
+        sign-on-keycard?          (get-in transaction-for-signing
+                                          [:signingDetails :signOnKeycard])]
+    (hot-reload/use-safe-unmount #(rf/dispatch [:wallet/clean-route-data-for-collectible-tx]))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:254]: Clean up event on unmount

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 3]
```diff
@@ -210,125 +212,124 @@
...
+       (when (and (send-utils/tx-type-collectible? transaction-type)
+                  first-route)
+         (rf/dispatch [:wallet/build-transaction-for-collectible-route])))
+     [first-route])
+    [rn/view {:style {:flex 1}}
+     [floating-button-page/view
+      {:footer-container-padding 0
+       :header                   [quo/page-nav
+                                  {:icon-name           :i/arrow-left
+                                   :on-press            events-helper/navigate-back
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:271]: Separated navigate back and clean up event (moved to unmount)

**Review by briansztamfater — APPROVED** [review]
LGTM!

**Review by mohsen-ghafouri — APPROVED** [review]
Nice stuff

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid still reproducible on IOS if the following steps are performed:

### Steps:
1. Open multi collectible (ERC 1150)-> navigate to confirmation tx page
2. Open collectible (ERC 720) -> navigate to confirmation tx page
3. Go back using device's back button -> navigate to confirmation tx page again

### Actual result:
A "Context canceled" error and a "No routes found" message are displayed.

https://github.com/user-attachments/assets/0b3f2f1c-0640-41be-915b-8f7d93b8fde2

### Device:
iPhone 11 Pro Max, IOS 17

### Logs:
[logs.zip](https://github.com/user-attachments/files/18298865/logs.zip)

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - please retest 🙏 . It should be fixed now.

**Review by vkjr — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@smohamedjavid Thank you for PR. No issues from my side. PR is ready to be merged
