### PR TITLE
Account selection: Implement features related to editing shared addresses

### LINKED ISSUE #18835: Changes are saved when closing Addresses for permissions screen by swiping
**Steps:** 

1. Open community
2. Go to Addresses for permissions screen 
3. Unselect some address
4. Swipe down the screen
5. Re open Addresses for permissions screen and see if changes are saved

**Expected result:** changes should not be saved unless if user has not tapped 'Confirm changes button'

**Actual result:** changes are saved

https://github.com/status-im/status-mobile/assets/97245802/10dd0755-6fdf-4c0f-91b9-29b71a15cca3

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #18844: Move request to join UI state out of community object
Keeping the community request-to-join related data in the app-db under the community object is unnecessary and will cause unintended re-renders, as we are subscribing to the community object in various places. Our goal is to move the UI state of the request-to-join flow to a separate root-level objects indexed by community ID, so the UI changes won't affect the community object.

### Data we need to move out of the community object
- airdrop-address
- previous-permission-addresses
- selected-permission-addresses
- previous-share-all-addresses?
- share-all-addresses?

Move the data stored in the above keys to `:communities/<key> { community-id {}}`

### LINKED ISSUE #18931: Account selection: the 'Addresses for permissions' jumping when updating the 'Eligible to join as X' section
# Bug Report

Follow-up from https://github.com/status-im/status-mobile/pull/18919, originally reported here: https://github.com/status-im/status-mobile/pull/18919#issuecomment-1956492434
cc @ilmotta 

## Problem 

_Minor UI regression that's happening because the section "Eligible to join as X" appears and disappears while the check sent to status-go is happening, and because now we use a bottom sheet, which adjusts its height to the content._

[jumpy.webm](https://github.com/status-im/status-mobile/assets/46027/215a20fe-4230-4b70-b681-be21f2ab891c)

#### Expected behavior

The bottom sheet doesn't jump

### Reproduction

1. Open `Addresses for permissions`
2. Select and deselect accounts to update the section `Eligible to join as X`

### Additional Information

- Status version: https://github.com/status-im/status-mobile/pull/18919#issuecomment-1956524033
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #18975: Edit shared addresses
As a user
I want to be able to edit my shared addresses
So I can let the community know in case of new addresses
So I can remove addresses that I have lost access to

### Description

We want the user to be able to edit his managed addresses, the UI is almost identical to when selecting accounts.
Main differences:

- You are a `role` is displayed

This relies on saving the "Share all future addresses"

### Questions

- https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15340-290340&mode=design&t=j9xL4xn1wE0KKjY0-4 I 
I don't understand the difference above, other than the "no relevant tokens"

### Designs

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15340-274636&mode=design&t=j9xL4xn1wE0KKjY0-4

Partially depends on: https://github.com/orgs/status-im/projects/116/views/1?pane=issue&itemId=54295818

### PR DESCRIPTION
**Pull request by ilmotta**
- Fixes https://github.com/status-im/status-mobile/issues/18844
- Fixes https://github.com/status-im/status-mobile/issues/18931
- Fixes https://github.com/status-im/status-mobile/issues/18975
- Fixes https://github.com/status-im/status-mobile/issues/18835

### Summary

This larger than usual PR attempts to implement all flows for editing shared addresses (see [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15340-270835&mode=design&t=gEgvqCtOPBL3BDM3-0)).

- Joining community flows should behave just as in `develop`.
- Editing addresses is only allowed behind a feature flag, which you can enable in `Profile > Feature Flags > edit-account-selection`. The flag is disabled by default. The goal is to enable or remove it once QAs deem the feature stable enough, thus not in this PR.

Note: I apologize for such a large diff to review. It's very unusual on my part and I don't endorse such practice. There are two reasons for this exception: the main one is that I'll be completely off for a month, so no PRs from me for a while ;) The other is that, while working for this PR, I realized many refactors were needed and they had to be consistently done, which would be difficult with multiple PRs and would require multiple QA passes.

### A few other fixes/improvements

- [x] We do less in event `:communities/handle-community`, which can be triggered numerous times. Overly dispatching there can be the cause of unwanted slow downs due to the amount of time spent computing derived data (e.g. getting revealed accounts) unnecessarily. As aligned with @cammellos, it's better if we call certain RPC endpoints only when really needed (e.g. in the mount phase of a component).
- [x] I fixed most of https://github.com/status-im/status-mobile/issues/18844, but not all. The issue can probably be closed. We still store in the community instance the _revealed accounts_ data. The technique to fix is repeatable, i.e. store in the app-db whatever data is needed, indexed by the community ID in a new root key.
- [x] In the screen to select addresses to share, local state is used, and the global state is only mutated once the user confirms. This helped solve issue https://github.com/status-im/status-mobile/issues/18835.
- [x] In account selection screens, fully migrated away from Reagent atoms.
- [x] Added a temporary global state for checking permissions, so that we can safely find the highest permission role while the user hasn't confirmed. This helped solve https://github.com/status-im/status-mobile/issues/18835.
- [x] We were using the `:checking?` state to decide if the confirmation button should be disabled while the request to check permissions to status-go had not finished. But because the time it takes for status-go to check permissions is very fast, for the user, it meant they would see the confirmation button flash on screen and things could jump around as well. The `:checking?` state is useful under the hood in the event handlers, but shouldn't be used in the UI because, generally speaking, loading indicators shouldn't be used for things that finish too quickly because they will be perceived as flashes on screen. They will also **negatively affect the performance of the initial mount phase** because there will be 3 render passes (off by default, then on, then off). Solves issue https://github.com/status-im/status-mobile/issues/18931
- [x] I tried to move events out of `communities/events.cljs` file that were more strongly related to account selection. I also moved account selection subs out of `status-im.subs.communities`. I think it's time we follow the steps of the wallet team and how they are breaking apart events, subs, data-store, schemas, etc.
- [x] Instead of dispatching 3 async requests to status-go to join a community or to edit shared addresses, I used a new approach in this repo where the individual RPC calls are promisified and then a single re-frame effect is used. With the help of promesa macros, things are easier to reuse and hopefully read as well. A similar strategy will eventually be used in contract tests.

### User flows

The following is a list of user flows I tested while working on this PR.

- User tries to join communities with/without various permissions just to see if there was any regression.
- While editing shared addresses, users can:
  - Toggle "Share all current and future addresses". This is only partially implemented because the choice is not persisted in the backend (related issue https://github.com/status-im/status-mobile/issues/18976).
  - See relevant tokens.
  - Select/deselect addresses to share and see the highest permission role text change on the fly.
  - If the user makes changes to the address selection and press the back button, they are asked if they want to discard changes before proceeding.
  - If the request to join is pending approval, and if the user deselects all addresses to share, then they are immediately given the option/button to "Cancel request". If canceled, they are redirected to the home screen.
  - If the user has already joined the community, and if the user deselects all addresses to share, then they are immediately given the option/button to "Leave community". If canceled, they are redirected to the home screen.
  - If the addresses to share do not include the previously selected airdrop address, the first available (selected) address will be used automatically for airdrops.

### Important

When the user changes to a lower role while selecting/deselecting addresses, the "Confirm changes" button should be displayed, but going to a higher role, a slider and authentication mechanism should be used (see in [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16113-149606&mode=design&t=XCiBLOkxsecZRTdL-0)).

We can't fulfill this requirement right now because every single call to status-go to update addresses (or set the airdrop address) require signing some data, thus requiring some form of authentication. This point is not critical, but should be brought to designers' attention (for the record I talked with Mario about this, but it was before I was certain of how status-go was operating).

### Areas that may be impacted

In theory, nothing should be impacted. As long as the community joining flows behave the same, editing is behind a feature flag and should cause no harm.

### Steps to test

1. Log in and enable the feature flag `Profile > Feature Flags > edit-account-selection`.
2. Try to join any community and the account selection flows will start. No regressions should happen here.
3. For editing, go to the community overview screen on a joined or pending community, open the drawer and press on "Edit shared addresses".

The most important part to test from a QA perspective is if there are no regressions while trying to select addresses to join a community. Editing is less critical to get 100% right because it's behind a disabled feature flag.

Besides that, for testing the features related to edit shared addresses, I suggest going over the entirety of the page [Figma > Manage shared addresses](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15340-270835&mode=design&t=gEgvqCtOPBL3BDM3-0).

Since this is a large unit of work and blocks other devs from collaborating in other PRs without massive rebase issues, we can try to fix only the most critical issues in  this PR, but if other, less important ones are found we should probably log separately.

status: ready

### CODE REVIEW

File: src/quo/components/drawers/bottom_actions/view.cljs [hunk 1]
```diff
@@ -38,8 +39,8 @@
    :owner        :i/crown})
 
 (defn- view-internal
-  [{:keys [actions description description-text error-message role button-one-label button-two-label
-           blur? button-one-props button-two-props theme scroll? container-style]}]
+  [{:keys [actions description description-text description-top-text error-message role button-one-label
```
Comment (ilmotta) [inline src/quo/components/drawers/bottom_actions/view.cljs:42]: FYI: In order to display a slider in the bottom actions component, we'll need to make it more general and not limited to only have instances of `quo/button`. I haven't created an issue yet.

File: src/status_im/contexts/communities/actions/accounts_selection/effects.cljs [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+
+        (vector? callback-or-event)
+        (rf/dispatch (conj callback-or-event result))))
+
+(defn- sign-and-call-endpoint
+  [{:keys [community-id password pub-key
+           addresses-to-reveal airdrop-address
+           on-success on-error
+           callback]}]
+  (-> (p/let [sign-params (generate-requests-for-signing pub-key community-id addresses-to-reveal)
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/accounts_selection/effects.cljs:69]: FYI: Instead of dispatching intermediary events to make RPC calls, we make all 3 calls be part of a single re-frame effect and then compose the 3 operations that have been promisified neatly with `promesa.core/let`.

File: src/status_im/contexts/communities/actions/accounts_selection/effects.cljs [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+   (fn [p-resolve p-reject]
+     (rpc/call
+      {:method     :wakuext_signData
+       :params     [(map #(assoc % :password password) sign-params)]
+       :on-success p-resolve
+       :on-error   #(p-reject (str "failed to sign data\n" %))}))))
+
+(defn- edit-shared-addresses-for-community
+  [community-id signatures addresses-to-reveal airdrop-address]
+  (p/create
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/accounts_selection/effects.cljs:30]: FYI: @cammellos this is the idea we were talking about recently. Given the size of this PR, I preferred to not change anything in `native-module.core`, and instead manually promisified here. I will probably attempt to do this while using this technique for contract tests, if nobody attacks this problem until then.

File: src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs [hunk 4]
```diff
@@ -36,96 +41,313 @@
...
+                                         (i18n/label :t/leave-community)
+
+                                         :else
+                                         (i18n/label :t/confirm-changes))
+                 :description-top-text (cond
+                                         (and pending? highest-role)
+                                         (i18n/label :t/eligible-to-join-as)
+
+                                         (and joined (= highest-role unmodified-role))
+                                         (i18n/label :t/you-are-a)
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs:323]: FYI: A minor detail, but currently it doesn't read well to see "You're a Admin". It should be "You're an Admin". To solve this, we would need to make our translation use the correct article.

File: src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs [hunk 5]
```diff
@@ -1,41 +1,81 @@
...
+  [{:keys [address emoji] :as account}
+   _ _
+   [community-id airdrop-address can-edit-addresses?]]
+  (let [airdrop-address? (= address airdrop-address)
+        on-press
+        (when-not airdrop-address?
+          (fn []
+            (if can-edit-addresses?
+              (rf/dispatch
+               [:password-authentication/show
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs:22]: FYI: I don't remember if we have a GH issue already, but it would be good to get rid of this hardcoded mechanism to authenticate and use biometrics if that's the user's choice.

File: src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs [hunk 6]
```diff
@@ -1,41 +1,81 @@
...
+      :on-press      on-press}]))
 
 (defn view
   []
-  (let [{id :community-id}          (rf/sub [:get-screen-params])
-        {:keys [name images color]} (rf/sub [:communities/community id])
-        selected-accounts           (rf/sub [:communities/selected-permission-accounts id])
-        airdrop-address             (rf/sub [:communities/airdrop-address id])]
+  (let [{id :community-id}        (rf/sub [:get-screen-params])
+        {:keys [name logo color]} (rf/sub [:communities/for-context-tag id])
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/airdrop_addresses/view.cljs:46]: FYI: In our pursue to optimize the app, I noticed a few places always need the name, logo and color to display the community context tag component. Instead of subscribing to the whole community and destructure, here we subscribe only to a subset of the community.

File: src/status_im/contexts/communities/events.cljs [hunk 7]
```diff
@@ -34,15 +35,12 @@
       {:db (assoc-in db
             [:communities id]
             (assoc community :last-opened-at (max last-opened-at previous-last-opened-at)))
-       :fx [[:dispatch [:communities/initialize-permission-addresses id]]
```
Comment (ilmotta) [inline src/status_im/contexts/communities/events.cljs]: FYI: When a community needs to be reconciled into the app-db, we now don't further compute the revealed accounts and initiate the permissions addresses. Doing this is rather inefficient for a community entity that can change frequently. Instead, these events are called somewhere closer to where the view that needs them will be mounted, using, for example, `rn/use-mount`.

File: src/status_im/contexts/communities/events.cljs [hunk 8]
```diff
@@ -430,16 +333,17 @@
...
 
 (defn get-revealed-accounts
-  [{:keys [db]} [community-id]]
+  [{:keys [db]} [community-id on-success]]
   (let [{:keys [joined fetching-revealed-accounts]
-         :as   community} (get-in db [:communities community-id])]
-    (when (and community joined (not fetching-revealed-accounts))
+         :as   community} (get-in db [:communities community-id])
+        pending?          (get-in db [:communities/my-pending-requests-to-join community-id])]
+    (when (and community (or pending? joined) (not fetching-revealed-accounts))
```
Comment (ilmotta) [inline src/status_im/contexts/communities/events.cljs:335]: FYI: Revealed addresses should also be fetched when there are pending requests to join.

**Review by ibrkhalil — APPROVED** [review]
Thank you very much Icaro for this beautiful piece of worK!

**Review by ajayesivan — COMMENTED** [review]
Incredible work, @ilmotta! A huge thank you for taking the time to add all those comments ❤️ Your attention to detail is greatly appreciated!

Everything looks good except I was not able to save the address changes while the request is in the pending state. I was getting the following error.

```zsh
 ERROR  2024-03-13T06:43:46.372Z ERROR [status-im.contexts.communities.actions.accounts-selection.events:99] - failed to edit shared addresses {:event :communities/edit-shared-addresses,
 :community-id
 "0x02248bd63ce67757df1ce720727f856d29a8a80fe4b77e1dff56e61e1be86384ec",
 :error {:code -32000, :message "not part of the community"}}
```

The community I'm using had the 'request to join required' option enabled.

**Comment by ilmotta** [comment]
> Incredible work, @ilmotta! A huge thank you for taking the time to add all those comments ❤️ Your attention to detail is greatly appreciated!
> 
> Everything looks good except I was not able to save the address changes while the request is in the pending state. I was getting the following error.
> 
> ```shell
>  ERROR  2024-03-13T06:43:46.372Z ERROR [status-im.contexts.communities.actions.accounts-selection.events:99] - failed to edit shared addresses {:event :communities/edit-shared-addresses,
>  :community-id
>  "0x02248bd63ce67757df1ce720727f856d29a8a80fe4b77e1dff56e61e1be86384ec",
>  :error {:code -32000, :message "not part of the community"}}
> ```
> 
> The community I'm using had the 'request to join required' option enabled.

Thank you for the kind words @ajayesivan 😍 

I've seen this issue before. I'll have a look and see if there's anything to fix on our end. Thanks for reporting that and how to reproduce.

**Comment by pavloburykh** [comment]
> I've seen this issue before. I'll have a look and see if there's anything to fix on our end. Thanks for reporting that and how to reproduce.

Hi @ilmotta! Should we start manual qa or better wait for the fix of the issue reported by Ajay?

**Comment by ilmotta** [comment]
@ajayesivan, here's my update about the issue you mentioned that you can't edit addresses while in pending state.

I have no explanation about why I could successfully edit addresses while waiting for approval from a community owner, and I did this dozens of times while developing the feature. Maybe it's something to do with me testing for a long time on an old community where I joined and left many times.

The thing is that status-go does not support editing shared addresses while the user isn't a member of the community because it checks if the public key is present using `community.HasMember`. Here is the source https://github.com/status-im/status-go/blob/afd72ace28ed6629297820af73053cea3e73e63b/protocol/messenger_communities.go#L1252-L1254

Also to confirm that, I checked that this error is always happening for me too, and that the community member isn't updated in the backend until the user joins.

-----

What do you think about the following plan? cc @cammellos 

1. We keep the code I wrote to support pending flows, but I disable the option in the drawer so as to not confuse QAs. It seems wasteful to throw away what is done just to redo again very soon. In theory, the client code won't need to change because we simply pass addresses to `wakuext_editSharedAddressesForCommunity` and we check if it's in the pending state with the presence of request IDs in `:communities/my-pending-requests-to-join`, both apparently established solutions. We merge this unit of work.
2. We update status-go in a separate PR to support editing shared addresses for users that are not yet members of the community. Therefore, we would need to go beyond the current check `!community.HasMember(m.IdentityPublicKey())`.

What do you guys think? Is this is a good course of action?

**Comment by ilmotta** [comment]
> > I've seen this issue before. I'll have a look and see if there's anything to fix on our end. Thanks for reporting that and how to reproduce.
> 
> Hi @ilmotta! Should we start manual qa or better wait for the fix of the issue reported by Ajay?

@pavloburykh, what changes in terms of testing is that status-go doesn't support editing shared addresses while the request to join is pending approval. So the best is to ignore pending flows and skip directly to the joined state.

So the scope of testing for this PR would be:

- Verify regressions are not introduced to join communities.
- Verify editing shared addresses after joining a community work as expected. Note about this, some accounts stubbornly couldn't be used in my tests. You may see a failure with some accounts, so I suggest you select and deselect other accounts if you see an error saying "Oops, wrong password". Btw this error doesn't mean the password is incorrect, it's just that we aren't handling errors gracefully and that is also not designed in Figma.

Just a reminder Pavlo that editing shared addresses is behind a disabled feature toggle.

**Comment by cammellos** [comment]
> What do you think about the following plan? cc @cammellos

We keep the code I wrote to support pending flows, but I disable the option in the drawer so as to not confuse QAs. It seems wasteful to throw away what is done just to redo again very soon. In theory, the client code won't need to change because we simply pass addresses to wakuext_editSharedAddressesForCommunity and we check if it's in the pending state with the presence of request IDs in :communities/my-pending-requests-to-join, both apparently established solutions. We merge this unit of work.
We update status-go in a separate PR to support editing shared addresses for users that are not yet members of the community. Therefore, we would need to go beyond the current check !community.HasMember(m.IdentityPublicKey()).
What do you guys think? Is this is a good course of action?

Yes, this looks like a good plan, `pending` state editing of addresses is roughly a corner case, so it's fine to address separately imo, thanks for the very detailed pr and explanation!

**Comment by cammellos** [comment]
@pavloburykh  @ilmotta maybe we could do only regression testsing on this PR for now and keep the feature disabled and merge if no regressions are found, and then once it's in, we can go through proper QA? that takes away the need of rebasing and unblocks others that are working on similar path of the code, what do you think?

**Comment by pavloburykh** [comment]
> @pavloburykh @ilmotta maybe we could do only regression testsing on this PR for now and keep the feature disabled and merge if no regressions are found, and then once it's in, we can go through proper QA? that takes away the need of rebasing and unblocks others that are working on similar path of the code, what do you think?

I agree with @cammellos. That would give us more time to test the feature properly without rush and worrying about rebasing and other stuff.

**Comment by pavloburykh** [comment]
> @pavloburykh, what changes in terms of testing is that status-go doesn't support editing shared addresses while the request to join is pending approval. So the best is to ignore pending flows and skip directly to the joined state.
> 
> So the scope of testing for this PR would be:
> 
> * Verify regressions are not introduced to join communities.
> * Verify editing shared addresses after joining a community work as expected. Note about this, some accounts stubbornly couldn't be used in my tests. You may see a failure with some accounts, so I suggest you select and deselect other accounts if you see an error saying "Oops, wrong password". Btw this error doesn't mean the password is incorrect, it's just that we aren't handling errors gracefully and that is also not designed in Figma.
> 
> Just a reminder Pavlo that editing shared addresses is behind a disabled feature toggle.

@ilmotta thank you for the helpful details. Everything is clear and sounds good to me.

**Review by ajayesivan — APPROVED** [review]

**Comment by ajayesivan** [comment]
Thanks, @ilmotta, for looking into the issue. I agree with @cammello's suggestion to merge this PR after verifying the join flow. We can test the edit flow later once it's integrated into the develop branch and create separate issues if any problems arise. This seems like the best course of action since it will help avoid rebase issues for the whole team.

**Review by jo-mut — APPROVED** [review]

**Comment by qoqobolo** [comment]
I checked this PR with the disabled feature toggle, so I didn't check the feature itself and have done only some regression testing.
There what was found:

### ISSUE 1: [Android only] UI elements on the `Account selection` bottom sheets disappear after background

**Steps:**
1. Press `Join community`
2. Go to `Addresses for permissions` 
3. Send the app to the background

The same thing happens on the `Request to join` bottom sheet

https://github.com/status-im/status-mobile/assets/67952253/ae0e5419-d4f9-496d-914c-8b20004ad708

### ISSUE 2: Tokens stop displaying when turning on the `Share all current and future addresses` toggle

Checked on nightly, it works fine there.

https://github.com/status-im/status-mobile/assets/67952253/c1deb912-be1d-4176-810d-b4ec6f45aa09

### ISSUE 3: `Share all current and future addresses` toggle doesn't update your eligibility to join the community if first you deselected the account that allowed you to join the community and then switched the toggle on

**Steps:**
1. Create an additional wallet account
2. Open community
3. Go to `Addresses for permissions`
4. Turn the toggle OFF
5. Deselect the account with the necessary token (here you'll see the message: _These addresses don't contain tokens needed to join_)
6. Switch the toggle ON

**Actual result:** you still see the message "_These addresses don't contain tokens needed to join_" and don't see your tokens. 

https://github.com/status-im/status-mobile/assets/67952253/8452b7c8-b205-4eaa-ad66-9dbaf99a3c0c

**Expected result/nightly:**
The message disappears, you can see your tokens

https://github.com/status-im/status-mobile/assets/67952253/57d2b4a8-ca17-4c5c-9b8d-bcafa544eaa3

**Comment by clauxx** [comment]
@qoqobolo added fixes to Issue 2 and 3. For the first issue, it should be fixed [here](https://github.com/status-im/status-mobile/pull/19274).

**Comment by ilmotta** [comment]
> @qoqobolo added fixes to Issue 2 and 3. For the first issue, it should be fixed [here](https://github.com/status-im/status-mobile/pull/19274).

@clauxx, @qoqobolo, ISSUE 2 is not really an issue. Relevant tokens should only be displayed when the toggle to share all addresses is off. The theory is that the user doesn't care/doesn't need to know specific values because they don't need to decide which accounts should be shared. Reference in Figma https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16113-140139&mode=design&t=rSuunTAjyWBzUJvL-0

I'm going to be completely off soon. Just wanted to point this out before leaving. Thanks everyone. Thanks @clauxx for taking over the PR.

Edit: @clauxx, just realized that it would be a good idea to not even fetch balances on mount if the toggle is enabled (currently on line 257 of `addresses_for_permissions/view.cljs`).

**Comment by qoqobolo** [comment]
> ISSUE 2 is not really an issue. Relevant tokens should only be displayed when the toggle to share all addresses is off.

@ilmotta ah thank you for pointing that out! I mistook this for a bug, since I compared it with nightly, and not with the design of the account selection feature. And on nightly it looks like this

Screenshot 2024-03-15 at 18 54 01

But here's the design and the comment with this nuance 

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-288742&mode=design&t=w07z41OpQHy4Kod5-4

@clauxx sorry you had to fix this and we need it back :(

**Comment by qoqobolo** [comment]
There is actually another issue that looks like a regression, but I need your opinion on it:

### ISSUE 4: The `Confirm changes` button becomes active for a second when I deselect the account with a relevant token

Sometimes the `Confirm changes` button remains active for a second in PR so I can quickly press it (user can do it intuitively), which will lead to a weird state of the community where I can neither join it (since the needed account is no longer shared with the community), nor edit shared addresses even with enabled feature toggle, because if I understand correctly, until you have joined the community, this functionality should not be shown in the context drawer (I didn't find such scenario in figma).

This is how it works on nightly: when I deselect the account, the button becomes inactive immediately. This also feels like the eligibility status updates faster

https://github.com/status-im/status-mobile/assets/67952253/e6b0b620-1b53-4db8-b79d-bbe7edf0a034

And this is how it works in PR: the button "blinks" every time I deselect the account

https://github.com/status-im/status-mobile/assets/67952253/be85a102-bf1a-4c62-86d1-26f9234d7bc5

---

There is another issue with this button in nightly: if I quickly select and deselect an account, the button will remain active, which will also result in unnecessary behavior.


https://github.com/status-im/status-mobile/assets/67952253/43e46be2-402c-4ca5-9ba5-d6878e5a27c7



A similar bug was fixed earlier in this issue https://github.com/status-im/status-mobile/issues/18859

So I think both of these bugs could be fixed separately.
What do you think @ilmotta (sorry for the ping if you're already afk, just ignore it) @cammellos @clauxx ?

**Comment by ilmotta** [comment]
@qoqobolo, about ISSUE 4, I think it's related to the fix I implemented in this PR for issue https://github.com/status-im/status-mobile/issues/18931. It was intentional and you have a great eye!

I tried to explain in the PR description, but it's not easy. The thing is that in `develop`, when the user selects or deselects any checkbox, the UI immediately re-renders because an in-flight request to status-go is checking if the user is allowed to join. The button is immediately disabled. But this solution doesn't work well with the new approach where the UI state is managed by React & re-frame, because it causes a horrible flash of the confirm button and it causes 3 re-renders on every select/deselect of a checkbox. So I changed that, I made the confirm changes button not react immediately as if it's a loading indicator. That way, the flash was gone, but now it means a fast user could try to press on confirm changes while the check hasn't finished. But good news is that the button only continues/confirms if no request to check permissions is on the way. Of course, that means, if the user is fast enough and the check hasn't finished, they will need to press twice.

The solution in `develop` also causes the issue I fixed in this PR https://github.com/status-im/status-mobile/issues/18931. And the new approach also solved https://github.com/status-im/status-mobile/issues/18835 (forgot to add to the PR description)

Okay, but you're sharing a video showing there's kind of a flash still! There are ways to improve or maybe completely fix, but I think we should resolve in a separate issue and think carefully how we want to do it. Just to log here: we should also optimize the way to check for permissions and only process the last response from status-go, similar to what I did while typing URLs in the message composer.

Sorry if this is all very technical. In summary, we can improve or even fix the behavior of the confirm changes button, but it would be much better to do in a separate PR.

**Review by yqrashawn — APPROVED** [review]

**Comment by qoqobolo** [comment]
> @qoqobolo, about ISSUE 4, I think it's related to the fix I implemented in this PR for issue #18931. It was intentional and you have a great eye!
> 
> I tried to explain in the PR description, but it's not easy. The thing is that in `develop`, when the user selects or deselects any checkbox, the UI immediately re-renders because an in-flight request to status-go is checking if the user is allowed to join. The button is immediately disabled. But this solution doesn't work well with the new approach where the UI state is managed by React & re-frame, because it causes a horrible flash of the confirm button and it causes 3 re-renders on every select/deselect of a checkbox. So I changed that, I made the confirm changes button not react immediately as if it's a loading indicator. That way, the flash was gone, but now it means a fast user could try to press on confirm changes while the check hasn't finished. But good news is that the button only continues/confirms if no request to check permissions is on the way. Of course, that means, if the user is fast enough and the check hasn't finished, they will need to press twice.
> 
> The solution in `develop` also causes the issue I fixed in this PR #18931. And the new approach also solved #18835 (forgot to add to the PR description)
> 
> Okay, but you're sharing a video showing there's kind of a flash still! There are ways to improve or maybe completely fix, but I think we should resolve in a separate issue and think carefully how we want to do it. Just to log here: we should also optimize the way to check for permissions and only process the last response from status-go, similar to what I did while typing URLs in the message composer.
> 
> Sorry if this is all very technical. In summary, we can improve or even fix the behavior of the confirm changes button, but it would be much better to do in a separate PR.

Thanks for the detailed explanation @ilmotta ! I will create a separate task for this improvement.

---

@clauxx would you mind resolving the conflict and reverting the fix for [ISSUE 2](https://github.com/status-im/status-mobile/pull/19177#issuecomment-1999518940) (since as Icaro mentioned that behavior was changed on purpose), please? 
I'll recheck the PR one more time after that and we'll merge it.
Thanks!

**Comment by clauxx** [comment]
> @ilmotta Edit: @clauxx, just realized that it would be a good idea to not even fetch balances on mount if the toggle is enabled (currently on line 257 of addresses_for_permissions/view.cljs). 

added in [cba461a](https://github.com/status-im/status-mobile/pull/19177/commits/cba461a1b019d14a473baa72180b8818073dfb37)

**Comment by clauxx** [comment]
>@clauxx would you mind resolving the conflict and reverting the fix for https://github.com/status-im/status-mobile/pull/19177#issuecomment-1999518940 (since as Icaro mentioned that behavior was changed on purpose), please?
I'll recheck the PR one more time after that and we'll merge it.
Thanks!

@qoqobolo done :)

**Comment by qoqobolo** [comment]
So, the situation today is as follows. 
Today I cannot fully test the flows required for this PR for the following reasons:

- something happened to the join flow for communities created on desktop - membership requests sometimes get stuck in the `pending` state, and you can’t do anything about it. So the flow of selecting accounts and sending a request looks good, but I can’t make sure that the user is actually joining the community.
But the same thing also happens in nightly. We are trying to investigate this and will soon create ab issue, but the investigation is hampered by the following issues:
- sometimes minting tokens gets stuck in the `Minting...` state forever (known problem on desktop). This makes it more difficult to check on new users and communities.
- also something happens with the balance display on the desktop on the test network

I also want to mention here another found issue, which will be logged separately: if you _very quickly_ deselect an account with relevant tokens, the status will not be updated (you will still be `eligible to join community as a member`). 

But when testing previous builds of this PR, no serious regression was found.
Therefore, I think that this PR can be merged; we should keep the feature toggle disabled (since the feature itself has not been fully tested).

The QA team will continue to test all account selector functionality in develop, when things become clearer regarding joining communities, and make sure everything works as expected before the presentation.
cc @cammellos 

@clauxx please merge it. 
Thank you!
