### PR TITLE
[#19232] - Fix derivation path generation

### LINKED ISSUE #19232: No ability to create additional ETH account after removal
### Steps:
1. Go to the wallet and create an additional ETH account (e.g., "test account 2"). (The current account is created with Derivation path `m/44/60/0/0/1` for this account).
2. Create one more ETH account (e.g., "test account 3").
3. Remove "test account 2".
4. Go to the account creation flow.
5. Check the Derivation path on the color picker screen during ETH account creation (The current account is created with Derivation path `m/44/60/0/0/2` instead of `m/44/60/0/0/1`).
6. Try to finish the account creation.

### Actual Result:
- The Derivation path for the new account is incorrect.
- The account is not created after confirming the slide to create account button.

https://github.com/status-im/status-mobile/assets/52490791/e523a4fc-f59c-4c9e-a716-2787adbdff00

### Expected Result:
- The Derivation path for the newly created account should be the same as it was when the account was removed.
- The account should be created successfully.

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14589082/Status-debug-logs.zip)

### LINKED ISSUE #19472: Incorrect derivation path for newly generated keypair accounts and theirs derived acccounts
### Steps:
1. Create an account with a newly generated keypair (see flow [here](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-596827&mode=design&t=iugkFHlUKh8btaCh-0) how to generate keypair)
2. Check the derivation path for newly created account

### Actual result:
The number is incremented at the end for the Derivation path for keypair account and = m/44/60'/0'/0/`<incremented account number>`
 
### Expected result:
The derivation path for master (keypair) accounts should not have an incremented number at the end; it should be m/44/60'/0'/0/0. Only accounts that are derived from the master (keypair) accounts should have an incremented path.

For example, if a user has two generated keypairs and two additional accounts  derived for each keypair account then derivation path hierarchy should looks so:

- Keypair account first: m/44/60'/0'/0/0
  - Test account 2 (derived from Keypair account first): m/44/60'/0'/0/1
  - Test account 3 (derived from Keypair account first): m/44/60'/0'/0/2
- Keypair account second: m/44/60'/0'/0/0
  - Test account 4 (derived from Keypair account second): m/44/60'/0'/0/1
  - Test account 5 (derived from Keypair account second): m/44/60'/0'/0/2

discussed in https://discord.com/channels/1210237582470807632/1217175448828514344/1224605345461047326
in the same way it works for Desktop.

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #19232
fixes #19472

### Summary

The original issue was about fixing derivation paths (#19232)
 but while trying to solve it, I found more bugs that didn't let me proceed, so now this PR is fixing everything.

Please keep in mind that:
- https://github.com/status-im/status-mobile/issues/19375

is still an issue, we need to clarify some things with desktop, but it's too much for this PR.

### Fixes in this PR

- :white_check_mark: The derivation path for derived accounts is incremented correctly, even if a derived account is removed.
- :white_check_mark: Now new keypairs are actually and properly generated.
- :white_check_mark: Now we can create derived accounts for new keypairs and they properly start at the zero index (`m/44'/60'/0'/0/0`) and they are incremented according to its keypair (again, keep in mind these accounts cannot be removed).

Also refactored the code, e.g I moved some code to events, updated the related tests,  improve the name of some events, etc.

#### Platforms

- Android
- iOS

#### Derivation Path

- Open Status
- Create a new account
- Go to wallet tab -> Add some new derived accounts for the existing (default) keypair
- Remove some of them
- Add new accounts

All should work as expected, so that #19232  is no longer reproducible.

#### Keypair generation and derived accounts

- Open Status
- Create a new account
- Go to wallet tab -> Add some new derived accounts for the existing (default) keypair
- Add as many keypairs as you wish
  To do this:
    1. Press on "Edit"
    
         
    2. Press on `+`
    
         
    3. Generate new keypair
    
        

- Add derived accounts for those new keypairs 
  **Note**: the UI to pick the keypair sometimes may not work as expected make sure the keypair is being properly selected, this is a different issue

Everything should work and the derivation paths are incremented according to the keypair selected.

NOTE for QA: @churik Has more context on these issues, since we already talked about it.

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/create_account/view.cljs [hunk 1]
```diff
@@ -56,46 +56,44 @@
...
-            {:keys [new-keypair]}                 (rf/sub [:wallet/create-account])
-            keypairs                              (rf/sub [:wallet/keypairs])
-            selected-keypair-uid                  (rf/sub [:wallet/selected-keypair-uid])
-            placeholder                           (i18n/label :t/default-account-placeholder)
-            derivation-path                       (utils/get-derivation-path
-                                                   number-of-accounts)
-            keypair                               (some #(when (= (:key-uid %) selected-keypair-uid)
-                                                           %)
-                                                        keypairs)
-            primary-keypair?                      (= selected-keypair-uid (:key-uid (first keypairs)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/create_account/view.cljs]: These calculations are completely based on values returned by subscriptions, so I moved them to derived subs

File: src/status_im/contexts/wallet/events/accounts.cljs [hunk 2]
```diff
@@ -0,0 +1,19 @@
+(ns status-im.contexts.wallet.events.accounts
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events/accounts.cljs]: Added new namespace because this new event is related to accounts.

I didn't move the others that are related because it'd add a lot of noise to this PR.

**Comment by J-Son89** [comment]
@OmarBasem - since this pr is around derivation paths and you have a lot of knowledge in that area, do you think you could give it a quick happy path test on the functionality added?
Just install the pr build and report back if things worked/didn't work etc, nothing too strenuous of a test, like 5/ 10 mins checking 👍 
If you don't have time today/next few days, perhaps someone else in @status-im/wallet-mobile-devs can take a look. 
(let's try limit ourselves to helping test 1 pr per week for the moment, so if you've already tested one / or are testing a pr then please let others volunteer)

File: src/status_im/contexts/wallet/create_account/view.cljs [hunk 3]
```diff
@@ -118,7 +116,8 @@
                                                                (create-existing-keypair-account
                                                                 password)))
                                       :auth-button-label   (i18n/label :t/confirm)
-                                      :disabled?           (empty? @account-name)
+                                      :disabled?           (or (empty? @account-name)
+                                                               (= "" @derivation-path))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/create_account/view.cljs]: Why would `derivation-path` be an empty string?

**Review by OmarBasem — COMMENTED** [review]
Thanks for your PR @ulisesmac!

I have tried testing out the PR. I tried to create a new keypair and a new account and it worked fine. But when I tried to create another account using one of the existing keypairs it did not work. After I enter the password it gets stuck -- nothing happens.


https://github.com/status-im/status-mobile/assets/29354102/abec3ef1-70b2-4e22-9cfa-3f4abbd72592

**Comment by ulisesmac** [comment]
> Thanks for your PR @ulisesmac!
> 
> I have tried testing out the PR. I tried to create a new keypair and a new account and it worked fine. But when I tried to create another account using one of the existing keypairs it did not work. After I enter the password it gets stuck -- nothing happens.
> 
> 
> 
> 

@OmarBasem thank you so much for spotting this issue!

Yeah, makes sense, since I'm not considering that case, I thought it wasn't implemented. I'll revisit the implementation and fix it.

**Comment by ulisesmac** [comment]
> Thanks for your PR @ulisesmac!
> 
> I have tried testing out the PR. I tried to create a new keypair and a new account and it worked fine. But when I tried to create another account using one of the existing keypairs it did not work. After I enter the password it gets stuck -- nothing happens.
> IMG_4506.MP4

Hey @OmarBasem  @J-Son89 , a quick update on it, I'm currently working on it.

The new account generation based on a keypair is incomplete or buggy in develop. No matter if we pick any keypair,  the code always generates an account for the root/main/primary? keypair stored, the one for our main account.

Besides the account creation, I think the keypair picker needs a lot of work, sometimes it's confusing what is being picked.

[Screencast from 2024-04-08 17-42-34.webm](https://github.com/status-im/status-mobile/assets/90291778/b30c34dd-e663-4aa7-92e0-da4e9b814340)

It took me a while to realize what the problems were and how to properly use it, as said before, I'm working on actually creating an account given a selected keypair. 

TBH I believe this is kind of a separate issue, but I don't want to merge this implementation without being complete, also because it'll require an immediate follow-up, so I'm addressing it in this PR. :+1:

**Comment by OmarBasem** [comment]
> The new account generation based on a keypair is incomplete or buggy in develop.

@ulisesmac it is working fine for me on develop. It was QA'ed in this PR https://github.com/status-im/status-mobile/pull/19333. Creating account from new keypair or an existing keypair works as expected.

**Comment by J-Son89** [comment]
> > The new account generation based on a keypair is incomplete or buggy in develop.
> 
> @ulisesmac it is working fine for me on develop. It was QA'ed in this PR #19333. Creating account from new keypair or an existing keypair works as expected.

yeah it's a little unclear to me what issues exactly you are pointing to @ulisesmac ? 🤔 
It's more design related?

**Comment by ulisesmac** [comment]
@OmarBasem @J-Son89 

It's unclear for me what is the correct flow to derive an address for a keypair. I'll explain develop behaviour with a (replicable) example.

Expected(?) (Status Desktop behaves like this):

1. User adds account to Primary KP 
  -> new acc in Primary KP with deriv. path `m/44'/60'/0'/0/1`
2. User adds account to Primary KP 
  -> new acc in Primary KP with deriv. path `m/44'/60'/0'/0/2`
3. User creates a Secondary KP 
  -> new acc in Secondary KP with deriv. path `m/44'/60'/0'/0/0`
4. User adds account to Secondary KP 
  -> new acc in Secondary KP with deriv. path `m/44'/60'/0'/0/1`
5. User adds account to Secondary KP 
  -> new acc in Secondary KP with deriv. path `m/44'/60'/0'/0/2`
6. User adds account to Primary KP 
  -> new acc in Primary KP with deriv. path `m/44'/60'/0'/0/3`
  
Current (status mobile behavior):

1. User adds account to Primary KP 
  -> new acc in Primary KP with deriv. path `m/44'/60'/0'/0/1`
2. User adds account to Primary KP 
  -> new acc in Primary KP with deriv. path `m/44'/60'/0'/0/2`
3. User creates a Secondary KP 
  -> new acc in Secondary KP with deriv. path `m/44'/60'/0'/0/3` :warning: 
4. User adds account to Secondary KP 
  -> new acc in Secondary KP with deriv. path `m/44'/60'/0'/0/4` :warning: 
5. User adds account to Secondary KP 
  -> new acc in Secondary KP with deriv. path `m/44'/60'/0'/0/5` :warning: 
6. User adds account to Primary KP 
  -> new acc in Primary KP with deriv. path `m/44'/60'/0'/0/6` :warning: 
  
And all accounts marked with :warning: are generated in the same way we generate accounts for Primary KP, so the Secondary KP is just another set of Primary KP addresses. If we attempt to generate the missing `m/44'/60'/0'/0/3` Primary KP address, we'll get an exception saying it has been already created.

**Comment by ulisesmac** [comment]
@J-Son89  @OmarBasem 
Just to provide more context, I found this problem been already reported:

- #19472

**Comment by OmarBasem** [comment]
@ulisesmac I think you are referring to a different issue. Creating a new account from a new keypair or an existing keypair works as expected on develop. Whether the derivation path is accurate or not shouldn't affect the functionality.

File: src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs [hunk 4]
```diff
@@ -24,7 +24,7 @@
                                           :on-auth-success       on-auth-success
                                           :on-auth-fail          on-auth-fail
                                           :auth-button-label     auth-button-label}]))
-                         (into [] (concat [theme] dependencies)))]
+                         (vec (conj dependencies on-auth-success on-auth-fail)))]
```
Comment (ulisesmac) [inline src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs:27]: This functon is wrapped on `rn/use-callback` but it wasn't receiving the `on-auth-success` callback as a dependency, leading to potential bugs (I faced one), now I added it

File: src/status_im/contexts/wallet/add_account/add_address_to_watch/confirm_address/view.cljs [hunk 5]
```diff
@@ -38,8 +38,7 @@
                                :disabled?           (string/blank? @account-name)
                                :accessibility-label :confirm-button-label
                                :on-press            #(rf/dispatch [:wallet/add-account
-                                                                   {:sha3-pwd     nil
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/add_account/add_address_to_watch/confirm_address/view.cljs:41]: 👍

File: src/status_im/constants.cljs [hunk 6]
```diff
@@ -208,6 +208,8 @@
 (def ^:const path-ledger-live "m/44'/60'")
 (def ^:const path-keepkey "m/44'/60'")
 
+(def ^:const wallet-initial-derivation-path "m/44'/60'/0'/0/0")
```
Comment (ulisesmac) [inline src/status_im/constants.cljs]: The derivation path by default for new accounts associated to new keypairs :eyes:

File: src/status_im/contexts/wallet/add_account/add_address_to_watch/confirm_address/view.cljs [hunk 7]
```diff
@@ -38,8 +38,7 @@
...
-                                                                    :type         :watch
+                                                                   {:type         :watch
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/add_address_to_watch/confirm_address/view.cljs:41]: Just removed the `sha3-pwd` that is passing `nil`. It's not needed and it's not a good practice because the `:or` destructuring (if present) may be ignored.

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs [hunk 8]
```diff
@@ -43,33 +51,45 @@
...
-  [{:keys [db]} [{:keys [new-keypair]}]]
-  {:db (assoc-in db [:wallet :ui :create-account :new-keypair] new-keypair)
-   :fx [[:dispatch [:navigate-back-to :screen/wallet.create-account]]]})
-
-(rf/reg-event-fx :wallet/new-keypair-created new-keypair-created)
-
-(defn new-keypair-continue
+(defn store-account-generated
+  [{:keys [db]} [{:keys [new-account-data keypair-name]}]]
+  (let [new-account (update new-account-data :mnemonic security/mask-data)]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/events.cljs:61]: Now I'm masking the seedphrase all the time and just unmasking when it's sent

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs [hunk 9]
```diff
@@ -43,33 +51,45 @@
...
-            :keypair-name keypair-name}]]}))
+           {:mnemonic-phrase (security/safe-unmask-data seed-phrase)
+            :paths           [constants/wallet-initial-derivation-path]
+            :on-success      (fn [new-account-data]
+                               (rf/dispatch [:wallet/store-account-generated
+                                             {:new-account-data new-account-data
+                                              :keypair-name     keypair-name}]))}]]}))
 
-(rf/reg-event-fx :wallet/new-keypair-continue new-keypair-continue)
+(rf/reg-event-fx :wallet/generate-account-for-keypair generate-account-for-keypair)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/events.cljs]: Changed the event name:
`:wallet/new-keypair-continue` -> `:wallet/generate-account-for-keypair`.

Regarding to the event, it doesn't create the keypair, just generates the data for it and the account, they will be created later.

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs [hunk 10]
```diff
@@ -80,6 +100,21 @@
...
+          [{:method     "accounts_resolveSuggestedPathForKeypair"
+            :params     [keypair-uid]
+            :on-success on-success
+            :on-error   (fn [error]
+                          (log/error
+                           "Failed to resolve next path derivation path"
+                           {:event  :wallet/next-derivation-path
+                            :method "accounts_resolveSuggestedPathForKeypair"
+                            :error  error
+                            :params keypair-uid}))}]]]}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/events.cljs:116]: This is a new call, we need it to properly avoid 
- https://github.com/status-im/status-mobile/issues/19472

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs [hunk 11]
```diff
@@ -105,3 +140,53 @@
...
+              :on-success [:wallet/add-account-success new-address]
+              :on-error   #(log/error "Failed to add Keypair and create account" %)}]]]})))
+
+(defn import-and-create-keypair-with-account
+  [{db :db} [{:keys [password account-preferences]}]]
+  (let [account-data      (-> db :wallet :ui :create-account :new-keypair :new-account-data)
+        unmasked-mnemonic (security/safe-unmask-data (:mnemonic account-data))
+        unmasked-password (security/safe-unmask-data password)]
+    {:fx [[:json-rpc/call
+           [{:method     "accounts_importMnemonic"
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/events.cljs:170]: Before creating the account, we import the new keypair generated

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs [hunk 12]
```diff
@@ -105,3 +140,53 @@
  :wallet/clear-private-key-data
  (fn [{:keys [db]} _]
    {:db (update-in db [:wallet :ui :create-account] dissoc :private-key :public-address)}))
+
+(rf/reg-event-fx
+ :wallet/create-keypair-with-account
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/events.cljs:145]: This event is the one that actually creates the new account.

File: src/status_im/contexts/wallet/add_account/create_account/key_pair_name/view.cljs [hunk 13]
```diff
@@ -52,8 +52,8 @@
                                                :import-private-key
                                                (not-implemented/alert)
 
-                                               :new-key-pair
-                                               (rf/dispatch [:wallet/new-keypair-continue
+                                               :new-keypair
+                                               (rf/dispatch [:wallet/generate-account-for-keypair
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/key_pair_name/view.cljs:56]: Renamed `key-pair` to `:keypair` to make it consistent to our existing names

File: src/status_im/contexts/wallet/effects.cljs [hunk 14]
```diff
@@ -2,15 +2,18 @@
...
+ (fn [{:keys [mnemonic-phrase paths on-success]
+       :or   {paths []}}]
+   (let [phrase (condp #(%1 %2) mnemonic-phrase
+                  string? mnemonic-phrase
+                  coll?   (string/join " " mnemonic-phrase)
+                  (log/error "Unexpected value " mnemonic-phrase))]
+     (native-module/create-account-from-mnemonic
+      {:MnemonicPhrase phrase
+       :paths          paths}
+      on-success))))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/effects.cljs:19]: Modified this effect to:
- Include `paths` to derive
- Be more general, the `on-success` callback is passed instead of hardcoded

File: src/status_im/contexts/wallet/events.cljs [hunk 15]
```diff
@@ -209,30 +202,11 @@
...
-(defn add-keypair-and-create-account
-  [_ [{:keys [sha3-pwd new-keypair]}]]
-  (let [lowercase-address (if (:address new-keypair)
-                            (string/lower-case (:address new-keypair))
-                            (:address new-keypair))]
-    {:fx [[:json-rpc/call
-           [{:method     "accounts_addKeypair"
-             :params     [sha3-pwd new-keypair]
-             :on-success [:wallet/add-account-success lowercase-address]
-             :on-error   #(log/info "failed to create keypair " %)}]]]}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events.cljs:234]: These events were fixed and moved to the `create-account.events` namespace.

File: src/status_im/constants.cljs (hunk 6 above)
Comment (smohamedjavid) [reply src/status_im/constants.cljs]: 🙏

File: src/status_im/subs/wallet/wallet.cljs [hunk 16]
```diff
@@ -165,6 +170,22 @@
...
+   (some #(when (= (:key-uid %) selected-keypair-uid)
+            %)
+         keypairs)))
+
+(rf/reg-sub
+ :wallet/selected-primary-keypair?
+ :<- [:wallet/keypairs]
+ :<- [:wallet/selected-keypair-uid]
+ (fn [[keypairs selected-keypair-uid]]
+   (= selected-keypair-uid (:key-uid (first keypairs)))))
```
Comment (smohamedjavid) [inline src/status_im/subs/wallet/wallet.cljs]: IMO, we should check if the key pair type is `profile` for the primary/default key pair. The first keypair check could go wrong. WDYT?

File: src/status_im/contexts/wallet/add_account/create_account/utils.cljs [hunk 17]
```diff
@@ -1,19 +1,29 @@
...
+                           :type       :seed
+                           :path       constants/wallet-initial-derivation-path
+                           :public-key (:publicKey account-to-create)
+                           :name       account-name
+                           :emoji      emoji
+                           :colorID    color
+                           :hidden     false}]
+    {:key-uid                    keyUid
+     :name                       keypair-name
+     :type                       :seed
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/add_account/create_account/utils.cljs:26]: For later - This (keypair type) should be received in the args as we have `seed` (recovery phrase), `key` (private key), and `profile`.

**Review by smohamedjavid — APPROVED** [review]
Nice work! 🚀 @ulisesmac 🙌 

Thank you for fixing this!

File: src/status_im/subs/wallet/wallet.cljs (hunk 16 above)
Comment (ulisesmac) [reply src/status_im/subs/wallet/wallet.cljs]: I checked it based on the previous implementation, I wasn't aware of that key meaning that!

Thank you @smohamedjavid ! I'll fix it.

File: src/status_im/contexts/wallet/add_account/create_account/utils.cljs (hunk 17 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_account/create_account/utils.cljs:26]: Ok, I wasn't aware of the different types, I'll take it into consideration. Thank you!

File: src/status_im/constants.cljs (hunk 6 above)
Comment (OmarBasem) [reply src/status_im/constants.cljs]: @ulisesmac we already have this defined:
```
(def ^:const path-wallet-root "m/44'/60'/0'/0")
(def ^:const path-default-wallet (str path-wallet-root "/0"))
```

You could rename it if you want

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs (hunk 10 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/add_account/create_account/events.cljs:116]: @ulisesmac was this the root of the problem?

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs [hunk 18]
```diff
@@ -57,125 +54,216 @@
...
+            :set-account-color   set-account-color
+            :set-emoji           set-emoji
+            :state               state
+            :keypair-name        keypair-name}]
+          [derive-account-variant
+           {:customization-color customization-color
+            :on-change-text      on-change-text
+            :set-account-color   set-account-color
+            :set-emoji           set-emoji
+            :state               state}])))))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/add_account/create_account/view.cljs:269]: Why did you choose these 2 variants approach? I see considerable duplication in the views

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs [hunk 19]
```diff
@@ -57,125 +54,216 @@
...
+        state             {:account-name  account-name
+                           :account-color account-color
+                           :emoji         emoji}]
+    (fn []
+      (let [customization-color    (rf/sub [:profile/customization-color])
+            ;; Having a keypair means the user is importing it or creating it.
+            {:keys [keypair-name]} (rf/sub [:wallet/create-account-new-keypair])]
+
+        (rn/use-unmount #(rf/dispatch [:wallet/clear-create-account]))
+
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/add_account/create_account/view.cljs:255]: Empty line

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs [hunk 20]
```diff
@@ -57,125 +54,216 @@
...
+           :customization-color customization-color}]]))))
+
+(defn view
+  [_]
+  (let [account-name      (reagent/atom "")
+        account-color     (reagent/atom (rand-nth colors/account-colors))
+        emoji             (reagent/atom (emoji-picker.utils/random-emoji))
+        on-change-text    #(reset! account-name %)
+        set-account-color #(reset! account-color %)
+        set-emoji         #(reset! emoji %)
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/add_account/create_account/view.cljs:245]: Since we are at it, these reagent atoms can be refactored to react's state

**Review by OmarBasem — COMMENTED** [review]
Thanks @ulisesmac for fixing this issue! 🚀 

Left some small comments

**Comment by qoqobolo** [comment]
Hi @ulisesmac, thanks a lot for the fixes!
I started testing and now need your clarification/confirmation on the fix for https://github.com/status-im/status-mobile/issues/19232 and how we should generate a derivation path for a newly created account after removing a previous one. 

---

Case:

1. Create a new profile
2. Go to wallet > Add some new derived accounts for the existing (default) keypair, e.g Acc1 (derivation path m/44'/60'/0'/0/1) and Acc2 (m/44'/60'/0'/0/2)
3. Remove Acc1 (m/44'/60'/0'/0/1)
4. Add Acc3

The expected result **in the issue** is saying:

"The Derivation path for the newly created account should be the same **_as it was when the account was removed_**"
i.e. in our case, it should be m/44'/60'/0'/0/1 for Acc3

Could you please confirm, that is NOT correct?

IIRC we asked you about this on the offsite, and your answer was that if the account is removed, we should continue to generate new accounts with derivation paths in the same order, that is for Acc3 it should be m/44'/60'/0'/0/3 (and that's how it works both in nightly and PR)

---

I'm asking for a clarification again because the description of this PR indicates that https://github.com/status-im/status-mobile/issues/19232 is fixed and you mentioned there that 

> The derivation path for derived accounts is incremented correctly, even if a derived account is removed.

However, I don't see any changes in this PR compared to nightly. And on the other hand, it looks expected to me. 

PR:

https://github.com/status-im/status-mobile/assets/67952253/f02053f6-c974-4dc1-87ce-8efa7b23ed7c

Does it mean that only the part of the issue where the UI froze when creating a new account was fixed?
Please help me solve this puzzle :)


I'll update the issue description if needed just to make it clear. 
Thanks!

**Comment by ulisesmac** [comment]
Hi @qoqobolo 
Thanks for testing!

Sorry for not being clear enough in this PR, I'll explain it with more detail.

>  I started testing and now need your clarification/confirmation on the fix for #19232 and how we should generate a derivation path for a newly created account after removing a previous one.
> 
> Case:
> 
>     1. Create a new profile
> 
>     2. Go to wallet > Add some new derived accounts for the existing (default) keypair, e.g Acc1 (derivation path m/44'/60'/0'/0/1) and Acc2 (m/44'/60'/0'/0/2)
> 
>     3. Remove Acc1 (m/44'/60'/0'/0/1)
> 
>     4. Add Acc3


Yeah, I think these steps aren't not enough to replicate the issue

> 
> The expected result **in the issue** is saying:
> 
> "The Derivation path for the newly created account should be the same **_as it was when the account was removed_**" i.e. in our case, it should be m/44'/60'/0'/0/1 for Acc3
> 
> Could you please confirm, that is NOT correct?

Exactly, this is **NOT** correct.
The expected result should be `m/44'/60'/0'/0/3` for Acc 3

> 
> IIRC we asked you about this on the offsite, and your answer was that if the account is removed, we should continue to generate new accounts with derivation paths in the same order, that is for Acc3 it should be m/44'/60'/0'/0/3 (and that's how it works both in nightly and PR)
> 

Yeah, `m/44'/60'/0'/0/3` should be the next expected derivation path, I confirmed it with Alisher some weeks ago.

> and that's how it works both in nightly and PR

Maybe that's because of the specific case you tested, but they don't behave the same, I recorded a video showing the error in the latest of develop:

[Screencast from 2024-05-22 10-35-26.webm](https://github.com/status-im/status-mobile/assets/90291778/148215f4-e6c4-4b58-b036-8c680d2e2fa9)

And this is the same case in this PR:

[Screencast from 2024-05-22 10-42-38.webm](https://github.com/status-im/status-mobile/assets/90291778/54c55956-13ef-40e6-b7f6-8f055daa48ab)


> Does it mean that only the part of the issue where the UI froze when creating a new account was fixed? Please help me solve this puzzle :)

Yes, I fixed the UI freezing, but the issue's description isn't correct, sorry, I should've updated it to properly describe the problem.

------------------------------------

Now, regarding to this PR, the issue shown in the first video I shared becomes worse when we generate new keypairs, the derivation path just makes no sense when deriving new accounts for new keypairs. This is being fixed in this PR.

Additionally, in develop it looks as if we are generating new keypairs, but we are not, so this PR also fixes the keypair generation, this fix is very important, but I'm not sure what you can do to test that there ARE NOT new keypairs added in develop. 

It can be seen as an internal fix in the app, the important thing is that now new keypairs and new derived accounts are working.

File: src/status_im/constants.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/constants.cljs]: Thank you @OmarBasem ! I fixed it.

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs (hunk 10 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_account/create_account/events.cljs:116]: The root of the problem to fix the derivation path, yes.

But it's not the root of the problem to properly create new keypairs.

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs (hunk 11 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_account/create_account/events.cljs:170]: This step was important when we create a new keypair @OmarBasem

File: src/status_im/subs/wallet/wallet.cljs (hunk 16 above)
Comment (ulisesmac) [reply src/status_im/subs/wallet/wallet.cljs]: Thank you, now I fixed it.

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs (hunk 18 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_account/create_account/view.cljs:269]: Hi @OmarBasem 

I abstracted the views as much as I could so that the amount of code duplicated is small, I could have abstracted one step more to eliminate the duplication, but IMO the code was worse.

The reason is it was mixing two flows:
- Create a derived account for existing keypair
- Create a new keypair an derive a first account

Depending on the flow we need some different things, so, to make this logic clearer, I decided to split it into 2 variants.

Previously, it was hard to understand why we were using some subscriptions if we only want to derive an account, so I hope this change helps the reading/understanding of the functionality.

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs (hunk 19 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_account/create_account/view.cljs:255]: They were left on purpose, to visually separate the `use-unmount` from the hiccup.  is this against the guidelines? :thinking:

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs (hunk 20 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_account/create_account/view.cljs:245]: Well, I mostly refactored the state management instead of re-think it, I also thought about it but they aren't equivalent.

As you can see, I'm passing atoms to the children components, and I'm just `deref`ing inside the children, so that this component is not re-rendered when ratoms change.

If we change this approach to react's use-state, we will re-render everything on each value changed, we could try to get a similar result, but that's a bit out of scope of this PR.

There are some other screens still using ratoms, IMO this screen can be changed when we focus on completely remove ratoms from the codebase.

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs (hunk 18 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/add_account/create_account/view.cljs:269]: > Previously, it was hard to understand why we were using some subscriptions if we only want to derive an account

Oh I see, makes sense 👍

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs (hunk 19 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/add_account/create_account/view.cljs:255]: > is this against the guidelines?

I am not sure if we have guidelines for new lines, but I haven't seen that style in the codebase 

cc @ilmotta

**Review by OmarBasem — APPROVED** [review]

**Comment by qoqobolo** [comment]
@ulisesmac thank you very much for the detailed explanation! Everything is clear and I see that the issue is deeper than it seemed before

> Additionally, in develop it looks as if we are generating new keypairs, but we are not, so this PR also fixes the keypair generation, this fix is very important, but I'm not sure what you can do to test that there ARE NOT new keypairs added in develop.

Yes, unfortunately, I don't know either but if you checked it yourself, it should be enough. 

Regarding testing the PR, I've checked the following cases:
1. removing Acc 2 and adding Acc 4 (that we mentioned above)
2. creating a new key pair and adding new derived accounts for it (without removing them due to https://github.com/status-im/status-mobile/issues/19375)
3. cases 1 and 2 on a profile recovered from a seed phrase
4. cases 1 and 2 on synced devices (there is an interesting issue: if you create a new keypair on a primary device, you can't add a new derived account for it on a secondary device. But it also exists in develop, I'll investigate and log it separately)

What I couldn't test is the same cases for the `Import keypair using recovery phrase` scenario. Please check this question [on Discord](https://discord.com/channels/1210237582470807632/1217175477395914893/1243144182667939873) when you're online, will wait for your answer (in case you have some context) and log it as well if needed.

And let me know if you have smth else in mind that I can test. 
Thank you!

**Review by mohsen-ghafouri — APPROVED** [review]
Remove key pair works fine with this PR. thanks

**Comment by ulisesmac** [comment]
> 4\. cases 1 and 2 on synced devices (there is an interesting issue: if you create a new keypair on a primary device, you can't add a new derived account for it on a secondary device. But it also exists in develop, I'll investigate and log it separately)

This one is very interesting, I guess that's because you need to provide the seed phrase for every new keypair you added. and probably you are not able to send transactions too.

I think those flows are being covered by the Wallet Settings team, but just guessing that's the issue.

CC: @smohamedjavid any idea of what might be the issue here?

**Comment by ulisesmac** [comment]
> What I couldn't test is the same cases for the Import keypair using recovery phrase scenario. Please check this question [on Discord](https://discord.com/channels/1210237582470807632/1217175477395914893/1243144182667939873) when you're online, will wait for your answer (in case you have some context) and log it as well if needed.

@qoqobolo

Yeah, we already clarified that and we'll open an issue for it, basically it wasn't properly updated in a past PR and it also needs some fixes that are being done in this PR.

The test cases are good enough, thanks for taking the time! :+1:

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs (hunk 19 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/add_account/create_account/view.cljs:255]: We don't have hard rules about blank lines. Zprint is configured to respect blank lines so we give some room for interpretation. It's all based on common sense right now. But as @OmarBasem said, we usually don't add a blank line between the final let form and the body of the component. On the other hand, the blank line after `use-unmount` I usually consider adding myself, but many times I forget.

**Comment by smohamedjavid** [comment]
You are right @ulisesmac.

> 4. cases 1 and 2 on synced devices (there is an interesting issue: if you create a new keypair on a primary device, you can't add a new derived account for it on a secondary device. But it also exists in develop, I'll investigate and log it separately)

@qoqobolo - If the primary device creates any new keypair, the secondary device will get only the key pair details without the keystore file. The secondary device should import the missing keypair from the device it was created (primary device in our case) or import using the Recovery phrase or Private key to perform any transactions on those accounts.

P.S. A sneak peek of the feature. We can check the missing keypairs in settings `profile > wallet > key pairs and accounts`. We need to enable the feature flag `keypairs-and-accounts` under settings.

**Comment by qoqobolo** [comment]
@ulisesmac @smohamedjavid thanks for your clarifications guys!

@ulisesmac no issues from my side, PR can be merged, thanks again for the amazing work!

**Comment by churik** [comment]
@ulisesmac @qoqobolo 
thank you for providing clear explanations, it really matters in particular case!

Amazing work!!!
