### PR TITLE
[#22010] fix: wrong selected account for bridging

### LINKED ISSUE #22010: Assets received in the wrong account after bridging
### Preconditions:
- Restore a profile where `Account 1` and `Account 2` are present.

### Steps to reproduce:
1. Go to the Bridge Setup page using `Account 1`.
2. Switch to `Account 2`
3. Perform the transaction.

### Actual result:
Assets are received in `Account 1` instead of `Account 2`.

https://github.com/user-attachments/assets/153e2bbc-256a-4e8f-a46b-aa07efda0fe1

current tx In blockchain https://arbiscan.io/tx/0x847d68e064bea1288f3f67214a8854ba0b1bc6f6157dabf9995a16ea534805cc

current tx in hopper https://explorer.hop.exchange/?transferId=0xdbe2f504c6756df05896b56b0b2477aad948f10b0c4e3c3afe95080152487f89

Image

### Expected result:
Assets should be received in `Account `2,.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1wgjfYNRkgkXeMM7LWjbtDSW7keiioTG8/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #22010

## Summary
Assets received in the wrong account after bridging

### Areas that may be impacted

- Bridge flow

### Preconditions:
- Restore a profile where `Account 1` and `Account 2` are present.

### Steps to reproduce:
1. Go to the Bridge Setup page using `Account 1`.
2. Switch to `Account 2`
3. Perform the transaction.

status: ready

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im/contexts/wallet/events.cljs [hunk 1]
```diff
@@ -77,7 +77,11 @@
 
 (rf/reg-event-fx :wallet/switch-current-viewing-account
  (fn [{:keys [db]} [address]]
-   {:db (assoc-in db [:wallet :current-viewing-account-address] address)}))
+   (let [{:keys [tx-type]} (db/send db)
+         bridge-tx?        (= tx-type :tx/bridge)]
+     {:db (cond-> db
+            :always    (assoc-in [:wallet :current-viewing-account-address] address)
+            bridge-tx? (update-in db-path/send assoc :to-address address))})))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/events.cljs:84]: ideally, instead of adding send specific updates here, we could have to-address always be the same as the current-viewing-address. But, given the send flow is a bit convoluted, might be not as straightforward, so it depends if it's hard to do.

**Comment by Horupa-Olena** [comment]
Hi @mohsen-ghafouri ! Thanks for your PR!
I've finished testing. If you make any changes, please let me know and I'll retest it.

File: src/status_im/contexts/wallet/events.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/events.cljs:84]: Indeed, I attempted to make the bridge independent, but it's not feasible since the send and bridge share the same logic and UI. Separating them would require some refactoring.

**Comment by mohsen-ghafouri** [comment]
Hey @Horupa-Olena. thanks for testing, there won't be more changes. if it's good I can merge it.

**Comment by Horupa-Olena** [comment]
> Hey @Horupa-Olena. thanks for testing, there won't be more changes. if it's good I can merge it.

@mohsen-ghafouri Yes, PR can be merged.

I tested:
- bridge flow with changing account (keycard user, restored account)
- quick reggresion for send and swap flow with changing account

File: src/status_im/contexts/wallet/events.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/events.cljs:84]: I have some topics to discuss in DX meeting, and if all good we can improve logic in a refactoring PR.
