### PR TITLE
fix ios blur blue overlay

### LINKED ISSUE #14903: Improve bottom tabs blur overlay
### Summary

leftovers from https://github.com/status-im/status-mobile/pull/14783

1. Currently blur view is creating blue overlay in ios, we should fix that. (more [details](https://github.com/status-im/status-mobile/pull/14783#discussion_r1084603578))
2. Better transition between blurred bottom tabs & normal bottom tabs. Currently, we are changing to blurred bottom tabs when the shell has more than 6 cards. We should use animations and transitions with a scroll position (design input required)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/14903

### Summary
PR fixes fix ios blur blue overlay in on-boarding, shell bottom tabs, and top bar.

### Testing
PR only changes color values, so testing is not required.
Design review is also probably not helpful, because we are not able to implement blur overlay for the above screens as same as Figma. We are just opting for the next best option.
This is discussed with the design team in meeting and we agreed that the current color & blur calibration is good enough for now as it is very hard (or maybe not possible) to get the same result as Figma.

status: ready

### CODE REVIEW

File: src/status_im2/contexts/onboarding/common/overlay/style.cljs [hunk 1]
```diff
@@ -1,5 +1,6 @@
 (ns status-im2.contexts.onboarding.common.overlay.style
```
Comment (Parveshdhull) [inline src/status_im2/contexts/onboarding/common/overlay/style.cljs]: Maybe we should try to get rid of this namespace. The background component itself has a property to show a dark overlay, And I think we used that in the original implementation.
Not sure why we created another overlay, maybe because the component doesn't support showing/hiding overlay as runtime (not sure though), if this is the case we should fix/implement that.

Also animation of navigation to "I'm new to Status" is different from [Figma](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=3672-369971&mode=design&t=47MYAAKGdvdrV9WK-0). (Not sure if they are updated recently)
(We maybe can get rid of this namespace while implementing Figma animations)

File: src/quo2/foundations/colors.cljs [hunk 2]
```diff
@@ -133,6 +133,11 @@
 (def neutral-95-opa-70-blur neutral-95-opa-70)
 (def neutral-100-opa-70-blur neutral-100-opa-70)
 
+;;;;Blur-IOS
+;; https://github.com/status-im/status-mobile/issues/14903
+(def neutral-80-opa-80-blur-ios "#1E2430CC")
```
Comment (J-Son89) [inline src/quo2/foundations/colors.cljs]: Perhaps we can just use the same def/variable but put the platform check in the color? Wdyt? It could still be a def too because the check is only needed once, right?

Comment (J-Son89) [reply src/quo2/foundations/colors.cljs]: I.e
(def neutral-80-opa-80-blur (if platform/ios? ... ... )

Comment (Parveshdhull) [reply src/quo2/foundations/colors.cljs]: This looked safer choice, because `neutral-80-opa-80-blur` also being used at few other places. Not sure we have similar problems at those places too.

Comment (J-Son89) [reply src/quo2/foundations/colors.cljs]: Do we know when we should be using this color and not the other one?

Perhaps we can make the name specifics by the use case. E.g
 neutral-80-opa-80-blur-overlay

Comment (Parveshdhull) [reply src/quo2/foundations/colors.cljs]: Actually I was opting for safe side, because differences are very hard to notice.

If you see in below images, bottom buttons in right one is little bluish
<div align="center">
Screenshot
Screenshot
</div>

But I checked the design and in figma buttons are not bluish, so I think we have similar problems at other places too. Its probably safe to just replace uses of blur color completely.
Done, thank you

**Review by siddarthkay — APPROVED** [review]

File: src/status_im2/contexts/onboarding/common/overlay/view.cljs [hunk 3]
```diff
@@ -61,7 +62,7 @@
       :style          (style/blur-container opacity)}
      [blur/view
       {:blur-amount   @blur-amount
-       :blur-radius   25
+       :blur-radius   (if platform/android? 25 10)
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/common/overlay/view.cljs:65]: hmm, curios. How about we put these `blur-radius` and `blur-amounts` in quo2.foundations.blur and have them saved as variables? 🤔 same for 30/20. Would be great if these are common discrepancies between ios and android and then we remove all these individual uses of the platform check

Comment (Parveshdhull) [reply src/status_im2/contexts/onboarding/common/overlay/view.cljs:65]: Hi @J-Son89, that's a nice suggestion, it will make blur consistent across the app.

But in the current PR, I only focused on blur color and tried to make it the same as Figma ([as much as possible](https://github.com/status-im/status-mobile/issues/14903#issuecomment-1682883951)). Blur parameters still has arbitrary values (just close enough)
We probably need to do the same with blur where we try different values until get the same (satisfactory) output. Putting these values in separate files will probably be a little misleading and will make other developers use them with confidence (while these are not right/perfect)

We probably need to figure out a system to map, Figma blur values with react-native blur values and then put them in the file, so they can be used across the app (probably will need significant research and time investment). wdyt?

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/common/overlay/view.cljs:65]: Yep, that's some good points. I definitely agree that we would benefit if we can figure out some standardised configurations for blur (provided they actually work for our use cases) - so best to leave as a point of research as you said 👍
