### PR TITLE
[#21652] The main part of a backup flow is missing at Keycard migrati…

### LINKED ISSUE #21652: The main part of a backup flow is missing at Keycard migration flow and Create User flow
# Bug Report
https://github.com/status-im/status-mobile/pull/21467
https://github.com/status-im/status-mobile/pull/21623

## For developer:
**It's already implemented in the wallet when creating new keypair, UI should be reused** 

## Problem 
[comment]: # (A problem description)

We only have two first screens of flow and then backup is successfully done.
A big part of flow is missing.

### Reproduction

A) Migration

1. Install the app
2. Create a user
3. Go to Profile -> Keycard
4. Start the migration flow till you see screen with a backup

B) Create user 

1. Install the app
2. Create a user with empty Keycard

#### Actual behavior

https://github.com/user-attachments/assets/0b15e53b-b59c-4cde-ab15-620ccd216406

#### Expected behavior

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3369-58996&node-type=frame&t=4Osm8WMs7FB6Q0iU-0

Image

### Additional Information

- Status version: [nightly 20](https://github.com/status-im/status-mobile/pull/21467)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21652

QA: please also check new keypair creation in the wallet

### CODE REVIEW

File: src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs [hunk 1]
```diff
@@ -98,7 +97,7 @@
                                                   (reset! show-error? true))))]
           [rn/view {:style {:flex 1}}
            [quo/page-nav
-            {:icon-name           :i/arrow-left
+            {:icon-name           :i/close
              :on-press            #(rf/dispatch [:navigate-back])
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs:130]: Does this change affect the wallet UX? For example, does the wallet-flow for backing up the seed-phrase still need a back-arrow?

cc @smohamedjavid

**Review by seanstrom — APPROVED** [review]
Looks good ✅ 

Left one small comment about how the UI may change wallet-UX, but I'm not sure.

File: src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs:130]: it was wrong before, it's modal but it had back arrow, so it's fixed now

**Review by smohamedjavid — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer !

As we have changes in design it would be great if we ad these parts to our keycard migration backup flow:

**1) restriction to make a screenshot**

Screenshot 2025-01-09 at 09 06 26

**2) `Complete backup` drawer**

Screenshot 2025-01-09 at 09 12 58

**3) `Verify your backup `drawer**

Screenshot 2025-01-09 at 09 05 45

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3395-33010&m=dev

This flow relates specifically to the keycard functionality. At the moment, the `create account` flow is outdated and awaiting an update.

**Comment by flexsurfer** [comment]
thanks @mariia-skrypnyk 2 - fixed, please make separate tasks for 1 and 3

**Comment by mariia-skrypnyk** [comment]
Hey @flexsurfer !

Please, fix 2 small issues:

1) there is a typo in design, we need to use "recovery phrase"
2) text should not exceed the boarder

Screenshot 2025-01-09 at 11 38 00

Screenshot 2025-01-09 at 11 35 52

**Comment by flexsurfer** [comment]
thanks @mariia-skrypnyk 1 fixed , for 2 pls create follow up because it seems like it's a different component we need to create or fix current component

**Comment by mariia-skrypnyk** [comment]
Thanks @flexsurfer !
E2E fails are not related and PR can be merged.

**Comment by mariia-skrypnyk** [comment]
Followups:

- [x] Restriction to make a screenshot
- [x] Cancel of Complete backup drawer logic
- [ ] Verify your backup drawer
- [x] Text exceeds the boarder of Confirmation backup
