### PR TITLE
Show token requirements only when membership permissions are present.

### LINKED ISSUE #18502: Adding `admin` permissions / minting Owner token makes the community token gated for any user
# Bug Report

## Problem 

If I create a community and add permission for becoming an `admin` and invite a mobile user there who does not have the required tokens, then the community will look like a `token-gated` one for them, although no permissions were added for becoming a `member`. 

Community permissions:

Screenshot 2024-01-15 at 12 29 34

What the mobile user (who does not have the required tokens) sees when opening this community:

Screenshot 2024-01-15 at 12 28 28

Screenshot 2024-01-15 at 12 29 03

#### Expected behavior

The community looks like a not-token-gated one for such users

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-284611&mode=design&t=g70SAiz9D6OgM1VU-4

Screenshot 2024-01-15 at 12 32 29

### Reproduction

**Desktop user:**
1. Create a community on desktop
2. Go to community settings > `Permissions` > `Add new permission`
3. Select any token (the mobile user **should not** have this token)
4. In `Is allowed to` select `Become an admin`
5. Click `Create permission` 
6. Add Mobile user to contacts and invite them to the community

**Mobile user:**
1. Open the community from the invite
2. Check the community page

### Additional Information

- Status mobile version: nightly 15/01
- Operating System: Android, iOS
- Status desktop version: 0.15.0 https://github.com/status-im/status-desktop/releases/tag/0.15.0

---

### Note

This case is also relevant for communities with a minted Owner token:

if you create a community and mint Owner token there, it'll "become" (will look like) a token-gated community for any user.

#### Steps to reproduce will be:
**Desktop user:**
1. Create a community on desktop
2. Go to community settings > `Tokens` > `Mint Owner token`
3. Do not add any permissions manually
4. Invite Mobile user to the community

**Mobile user:**
1. Open the community from the invite
2. Check the community page

Screenshot 2024-01-15 at 12 41 57

Mentioning this case here to make sure it'll be covered when fixing the issue.

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #18502 

Note: I haven't tested this fix with minted tokens. (edit: tested with minted tokens and it works)

status: ready

### CODE REVIEW

**Review by alwx — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

File: src/status_im/contexts/communities/events.cljs [hunk 1]
```diff
@@ -59,6 +59,9 @@
       (update :chats <-chats-rpc)
       (update :token-permissions seq)
       (update :categories <-categories-rpc)
+      (assoc :membership-permissions?
+             (some #(= (:type %) constants/community-token-permission-become-member)
```
Comment (ilmotta) [inline src/status_im/contexts/communities/events.cljs]: I think this logic should be unified, but it's being duplicated. See https://github.com/status-im/status-mobile/blob/ed3cb4257234f0917531d64c6543587ef42ed5fb/src/status_im/subs/communities.cljs#L311-L313

I would define a function in `data_store/communities.cljs`, unit test it and reuse it in the subscription I shared above, and also here.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 2]
```diff
@@ -191,7 +191,7 @@
            :accessibility-label :show-request-to-join-screen-button
            :customization-color color
            :icon-left :i/communities}
-          (i18n/label :t/request-to-join-community)]))
+          (i18n/label :t/request-to-join)]))
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs:172]: The line below is suspicious too. Anything based on the `token-permissions` collection may be buggy.

https://github.com/status-im/status-mobile/blob/ed3cb4257234f0917531d64c6543587ef42ed5fb/src/status_im/contexts/communities/overview/view.cljs#L196

This other place is also suspicious:

https://github.com/status-im/status-mobile/blob/ed3cb4257234f0917531d64c6543587ef42ed5fb/src/status_im/contexts/communities/events.cljs#L75

**Review by ilmotta — COMMENTED** [review]
Thanks @ajayesivan. It would be best if we consistently fixed the way we deal with token-permissions. There are a few other places that deserve investigation and which process the community `token-permissions` without any filtering.

**Review by yqrashawn — APPROVED** [review]

**Review by FFFra — APPROVED** [review]

**Comment by ilmotta** [comment]
Hey folks, please have another look at this PR because I had to make quite a few changes.

Here is the acceptance criteria I focused on:

<details>
<summary>Acceptance criteria</summary>

```
- Given a community doesn't have permissions
- When Alice opens the community overview screen
- Then she can see the Request to join button
```

```
- Given a community with membership permissions
- When Alice doesn't fulfill the requirements
- Then she's not allowed to request to join
- And she sees "You're not eligible to join"
```

```
- Given a community with role permissions (member, admin, owner, master)
- When Alice opens the community overview screen
- Then she doesn't see channels listed
```

```
- Given a community with membership permissions
- When Alice fulfills the requirements
- Then she's allowed to request to join and select addresses to join
- And she sees "You're eligible to join as Member"
```

```
- Given a community with membership permissions and admin permissions
- When Alice fulfills all requirements
- Then she's allowed to request to join and select addresses to join
- And she sees "You're eligible to join as Admin"
```

```
- Given a community with admin permissions
- When Alice fulfills all requirements
- Then she's allowed to request to join and select addresses to join
- And she sees "You're eligible to join as Admin"
```
</details>

- The overview screen temporarily/quickly shows the state where the user is not eligible to join. Once the permissions data is fetched, it correctly displays the token requirements and the text "You're eligible to join as X". We need to check if Figma has this situation covered of a loading state. If not, for the moment we can simply not show the permissions' summary while we're still fetching, otherwise it looks ugly. I can create an issue tomorrow.

@yqrashawn, I believe you mentioned something about having a new endpoint in status-go for the highest permission role, so I didn't touch the bug I saw today. Basically, when there's only one admin permission, the subscription `:community/token-gated-overview` is returning `2` (`member`), but should be `1` (`admin`) in the `:highest-permission-role` value. Here's this case in [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-284676&mode=design&t=GkPXh1C9jw7RlAe0-0). The same problem happens for a community with tokens, the sub is returning `1` (member) as the highest permission role instead of 5/6 (token master/token owner).

File: src/status_im/contexts/communities/overview/view.cljs [hunk 3]
```diff
@@ -137,119 +109,112 @@
    [rn/view
     [quo/icon :i/info {:no-color true}]]])
 
-(defn token-gates
-  []
-  (fn [{:keys [id color]}]
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs:142]: FYI: Changed from form-2 to form-1 component.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 4]
```diff
@@ -137,119 +109,112 @@
...
+  [{:keys [id color joined permissions role-permissions? can-join?] :as community}]
+  (let [pending?        (rf/sub [:communities/my-pending-request-to-join id])
+        access-type     (get-access-type (:access permissions))
         unknown-access? (= access-type :unknown-access)
         invite-only?    (= access-type :invite-only)]
     [:<>
      (when-not (or joined pending? invite-only? unknown-access?)
-       (if membership-permissions?
-         [token-gates community]
+       (if role-permissions?
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs:162]: FYI: _Role permissions_ is the name we have found to better represent what in Figma is named _Token Gated_. We believe _Token Gated_ doesn't correctly capture the intent of the permissions because a community can have non-membership permissions that also kind of token gate the community, since the user has to consider them before joining.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 5]
```diff
@@ -137,119 +109,112 @@
...
-  (when (or pending? joined)
-    [rn/view {:style {:position :absolute :top 12 :right 12}}
-     [quo/status-tag
-      {:status {:type (if joined :positive :pending)}
-       :label  (if joined
-                 (i18n/label :t/joined)
-                 (i18n/label :t/pending))}]]))
+(defn- status-tag
+  [community-id joined]
+  (let [pending? (rf/sub [:communities/my-pending-request-to-join community-id])]
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs:182]: FYI: I moved `pending?` down the tree of components instead of having it at the top `view` component to avoid having to re-render everything.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 6]
```diff
@@ -279,25 +244,24 @@
...
         (when (and (seq tags) (not collapsed?))
           [quo/community-tags
            {:tags            tags
             :last-item-style style/last-community-tag
             :container-style style/community-tag-container}])
-        [join-community community pending?]]
-       (when (or (and (seq token-permissions) joined)
-                 (empty? token-permissions))
+        [join-community community]]
+       (when (or joined (not membership-permissions?))
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs:261]: FYI: This requirement is captured from:

1. https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-284739&mode=design&t=GkPXh1C9jw7RlAe0-0
2. https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=11308-429045&mode=design&t=GkPXh1C9jw7RlAe0-0

File: src/status_im/contexts/communities/actions/request_to_join/view.cljs [hunk 7]
```diff
@@ -23,10 +23,8 @@
 (defn- view-internal
   [{:keys [theme]}]
   (fn []
-    (let [{:keys [name
-                  id
-                  images]} (rf/sub [:get-screen-params])
-          {:keys [color]}  (rf/sub [:communities/community id])]
+    (let [{:keys [id]}                (rf/sub [:get-screen-params])
+          {:keys [color name images]} (rf/sub [:communities/community id])]
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/request_to_join/view.cljs:27]: FYI: It's buggy to rely on `:get-screen-params` for dynamic data because we 99% of the time we close over values within an event handler in the view, hence if `name` or `images` change in the community instance in the app-db while the user is on this screen, the UI won't update.

**Review by ibrkhalil — APPROVED** [review]

**Review by FFFra — APPROVED** [review]
This is fantastic! Please inform me once it's merged. 🚀

**Review by jo-mut — APPROVED** [review]
