### PR TITLE
Account selection: Use bottom sheet component

### LINKED ISSUE #18617: Account selection: no animation when closing Addresses For Permissions modal
# Bug Report

No closing animation is displayed when the "Addresses for permissions" modal is closed.

#### Expected behavior

We show a closing animation as usual.

### Reproduction

1. Enable flag community-accounts-selection-enabled?.
2. Open the new Request to join screen of any community
3. Press on `Join as .*`
4. Press `Cancel` or `Confirm changes`.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #18619: Account selection: drawer is always expanded
# Bug Report

The screens "Addresses for permissions" and "Address for airdrops" are always expanded, even if there's only one address.

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/18617
Fixes https://github.com/status-im/status-mobile/issues/18619

### Summary

Use bottom sheet component as designed in [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16409-98076&mode=design&t=jrVNb3JnWNurJwP8-0).

Additionally

- [x] Fixed incorrect code passing a function instance to a style prop, which leads to incorrect appearance for `settings.category.reorder.view/view`.
- [x] Optimized Reagent a little bit by extracting functions that need to close over the community ID to the mount phase. That way, we avoid regenerating function instances on every re-render and Reagent can avoid a bit of re-work.

### Review notes

The challenge for this PR was to make the scrollable content work inside a bottom sheet, while supporting the designs for a fixed (always visible) header and footer. Using `:flex 1` (as is today) in the bottom sheet `content` wrapper doesn't work. We need to tell the bottom sheet `content` to have a max height.

### Demo

As expected, the bottom sheet component auto adjusts to its content. Also, notice when the "Cancel" button is pressed, there's an animation (which on Android & `develop` doesn't currently happen to me).

[feature-correct.webm](https://github.com/status-im/status-mobile/assets/46027/5aa2784a-d07e-40e0-8749-da69c1a79179)

#### Platforms

- Android
- iOS

### Steps to test

Besides the two bugs being fixed by this PR, it's recommended to check how other bottom sheets are being displayed. I checked (on Android) usages of other bottom sheets and couldn't find any regression. Special care for iOS should be taken because I can't test in it.

status: ready

### CODE REVIEW

File: src/status_im/common/bottom_sheet/view.cljs [hunk 1]
```diff
@@ -57,10 +57,16 @@
...
+  (oops/oget event "nativeEvent.layout.height"))
+
 (defn- f-view
   [_ _]
-  (let [sheet-height (reagent/atom 0)
-        item-height  (reagent/atom 0)]
+  (let [sheet-height     (reagent/atom 0)
+        item-height      (reagent/atom 0)
+        set-sheet-height #(reset! sheet-height (get-layout-height %))
+        set-item-height  #(reset! item-height (get-layout-height %))]
```
Comment (ibrkhalil) [inline src/status_im/common/bottom_sheet/view.cljs]: Nice, More performant to have state updates defined outside render fn.

File: src/status_im/contexts/communities/actions/accounts_selection/view.cljs [hunk 2]
```diff
@@ -5,81 +5,92 @@
...
-       [community-rules/view id]]]
-     [rn/view {:style (style/bottom-actions)}
-      [quo/slide-button
-       {:size                :size-48
-        :track-text          (i18n/label :t/slide-to-request-to-join)
-        :track-icon          :i/face-id
-        :customization-color color
-        :on-complete         #(join-community-and-navigate-back id)}]]]))
+  (let [{id :community-id}             (rf/sub [:get-screen-params])
+        show-addresses-for-permissions (fn []
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/accounts_selection/view.cljs:18]: FYI: This is a performance optimization pattern we can apply more often. The community ID or most IDs for that matter will never change, so we can extract the community ID to a `let` binding on the mount phase. Along with that, we can then extract anonymous functions that are re-created on every render that need to close over the community ID, therefore allowing Reagent to detect that the arguments passed to hiccup components are the same when it compares args for the current and new render.

File: src/quo/components/settings/category/reorder/view.cljs [hunk 3]
```diff
@@ -16,9 +16,9 @@
   (reagent/flush))
 
 (defn- reorder-category-internal
-  [{:keys [label data blur? theme]}]
+  [{:keys [label data blur? theme container-style]}]
   (reagent/with-let [atom-data (reagent/atom data)]
-    [rn/view {:style style/container}
+    [rn/view {:style (merge (style/container label) container-style)}
```
Comment (ilmotta) [inline src/quo/components/settings/category/reorder/view.cljs:21]: FYI: `style/container` is a function, so this is currently a bug. I just made this component identical in behavior to its cousin `settings.category.settings.view`.

**Review by ibrkhalil — APPROVED** [review]
lgtm

File: src/status_im/contexts/communities/actions/accounts_selection/view.cljs [hunk 4]
```diff
@@ -5,81 +5,92 @@
     [react-native.gesture :as gesture]
     [status-im.common.password-authentication.view :as password-authentication]
     [status-im.contexts.communities.actions.accounts-selection.style :as style]
+    [status-im.contexts.communities.actions.addresses-for-permissions.view :as addresses-for-permissions]
```
Comment (J-Son89) [inline src/status_im/contexts/communities/actions/accounts_selection/view.cljs:8]: btw, I'm trying to comment this as close to the ns as possible. 

Is this accounts selection really communities specific?? 

Will there be other areas in the application where we want to select the specific accounts??

For example purchasing ens names might have some feature similar to this needed?

cc @clauxx

Comment (ilmotta) [reply src/status_im/contexts/communities/actions/accounts_selection/view.cljs:8]: @J-Son89, I think this question could be redirected to a designer or to the PO if you want to be really certain.

My current understanding and what I remember from interactions with designers is that the account selection is very specific to communities and the UI is built for this use case. So even if we have a similar account selection feature like you mentioned, they would probably redesign some important parts. For example, in the account selection screen, the elements displayed are all tied to the concept of token permissions, which is stored at the community level.

**Review by yqrashawn — APPROVED** [review]
LGTM

**Comment by ajayesivan** [comment]
Unable to test iOS PR build due to this issue: https://github.com/status-im/status-mobile/issues/18898


https://github.com/status-im/status-mobile/assets/19279756/19f6c1f1-362e-4366-a5f2-a19f390c4cc8

**Comment by yqrashawn** [comment]
> Unable to test iOS PR build due to this issue: #18898
> RPReplay_Final1708496317.MP4

Is this a newly created community?

**Comment by ajayesivan** [comment]
@yqrashawn created last week.

**Comment by yqrashawn** [comment]
> @yqrashawn created last week.

can you share the community link here, I tried OCR but the page is broken

**Comment by qoqobolo** [comment]
Hi @ilmotta , thanks for the fixes!
There are some issues that need to be fixed/discussed, take a look, please:

### ISSUE 1: The `Addresses for permissions` bottom sheet is not closed when confirming changes

**Steps:**
1. Open `Addresses for permissions`
2. Disable the `Share all addresses `toggle
3. Tap `Confirm changes`

**OS:** Android, iOS

https://github.com/status-im/status-mobile/assets/67952253/e19817fc-5f66-4dd1-a89b-9bd06565e173

**Comment by qoqobolo** [comment]
### ISSUE 2: Bottom space/navigation bar color issue on Android

First, please watch the videos, paying attention to the color change of the navigation bar, especially when opening the `Addresses for permissions` bottom sheet:

**PR (color is changed to black when opening the `Addresses for permissions` bottom sheet):**

https://github.com/status-im/status-mobile/assets/67952253/9a224891-04d5-44c2-8037-ca8a370ef290

**Nightly (color is not changed):**

https://github.com/status-im/status-mobile/assets/67952253/68a4577e-1a25-4f9a-902b-df349a498a0b

The thing is that thanks to changing the color of the navigation bar in PR, another issue became noticeable - that there is actually no bottom spacing under the `slider` button on Android.

In general, the issue of changing the color of the navigation bar throughout the app should be investigated separately, as the behavior is clearly incorrect in some places.

But I have two questions/options within this PR:

1. How do you feel about adding bottom spacing on Android here, although this is not directly related to the PR.
This is especially noticeable on devices where, when switching to gesture navigation, there is no Home (navigation) bar. For example, here is my Huawei, no space at the bottom at all:

Screenshot 2024-02-21 at 12 50 09


2. Second option: fix the change of the color of the navigation bar **when opening the `Addresses for permissions` bottom sheet**, since it was introduced here.
In this case, the problem of missing bottom spacing will be less noticeable, and we can fix it later

3. Fix both problems here :) if you have some capacity of course

I hope my explanation isn't too complicated and confusing. Feel free to ask any questions to clarify everything.

**Comment by ilmotta** [comment]
@qoqobolo, I just noticed the following minor UI regression that's happening because the section "Eligible to join as X" appears and disappears while the check sent to status-go is happening, and because now we use a bottom sheet, which adjusts its height to the content.

This can be fixed in a separate issue to speed up our process to merge this one because we have quite a few people touching the same files and rebasing has been painful. Would that be fine for you?

[jumpy.webm](https://github.com/status-im/status-mobile/assets/46027/215a20fe-4230-4b70-b681-be21f2ab891c)

**Comment by ilmotta** [comment]
> How do you feel about adding bottom spacing on Android here, although this is not directly related to the PR.

I would prefer if we can fix in a follow-up because it's already in develop. Do we have an issue for that already? I can surely get it done this week.

> Second option: fix the change of the color of the navigation bar when opening the Addresses for permissions bottom sheet

I'm gonna have a look and fix this problem in this PR :) Good finding!

> The Addresses for permissions bottom sheet is not closed when confirming changes

I believe I just fixed this one after rebasing a pushing a few minutes ago.

Maybe to avoid interrupting you too much, once I fix the bar color bug you could do another review pass to see if everything is fixed (except the bottom space issue).

**Comment by qoqobolo** [comment]
Everything sounds great, thanks @ilmotta!

> I would prefer if we can fix in a follow-up because it's already in develop. Do we have an issue for that already? I can surely get it done this week.

We don't have it logged yet. I will create an issue and assign you.

> This can be fixed in a separate issue to speed up our process to merge this one because we have quite a few people touching the same files and rebasing has been painful. Would that be fine for you?

Yes, totally. Just to make sure: you mean this "jumping" of the bottom sheet when its height is changing, right? I'll create an issue for this as well.

**Comment by ilmotta** [comment]
> Yes, totally. Just to make sure: you mean this "jumping" of the bottom sheet when its height is changing, right? I'll create an issue for this as well.

Exactly that @qoqobolo. Thank you!

**Comment by ilmotta** [comment]
@qoqobolo, I tested the bottom bar color in latest `develop` and I could see the same bug (see video below). Can I fix this problem in the next follow-up? Edit: tested directly on the Android emulator.

[bug in develop.webm](https://github.com/status-im/status-mobile/assets/46027/8017002f-47d5-4a67-8914-d29bbc28f8cf)

**Comment by qoqobolo** [comment]
> I tested the bottom bar color in latest develop and I could see the same bug (see video below). Can I fix this problem in the next follow-up? Edit: tested directly on the Android emulator.
 
@ilmotta on the video you don't open the `Addresses for permissions` bottom sheet, only `Request to join`. 
But I'm referring to this particular screen, it is where the color changes in a different way than in develop: 

Screenshot 2024-02-21 at 13 59 12

Could you check this again please? You need to open the addresses list itself

**Comment by ilmotta** [comment]
> Could you check this again please? You need to open the addresses list itself

@qoqobolo. I see now. Eyes bleed.

**Comment by ilmotta** [comment]
@qoqobolo: I found why the status bar issue is happening now, but I also found that the problem exists in develop for any bottom sheet. I'll try to explain what I mean by _bottom sheet_ because it confused me for a long time, but maybe you already know this. Please, bear with me.

In the table below, as a user, can they differentiate what's a _bottom sheet component_ and what's a _sheet screen_? Both are strikingly similar, but they don't share code.

<table>
  <thead>
    <tr>
      <th>Sheet screen</th>
      <th>Bottom sheet component</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

With that terminology in mind, I can tell you what this PR did. It essentially changed the _Addresses for permissions_ and _Airdrop address_ _sheet screens_ to be _bottom sheets_. This came with its own set of challenges, because as I shared previously, they look the same sometimes (when bottom sheets are expanded) but their code is completely different.

What I have found in develop is that whenever the status bar color is white, when any _bottom sheet_ is opened, the status bar color will change to dark. The video below shows you the bug and the reproduction steps:

1. Set OS theme to light.
2. Open the app and open any chat.
3. Change OS theme from light to dark.
4. Change OS theme from dark to light. Now you should see the status bar is white.
5. Press the 3 dots button to open a bottom sheet. The status bar color will change to dark.

[bug in status bar color for any bottom sheet.webm](https://github.com/status-im/status-mobile/assets/46027/e3c3d509-93b9-4279-a38b-186c8937907d)

The same bug can be reproduced from other parts of the app.

Therefore, the bug started to appear now in this PR because we're using a _bottom sheet_ to select addresses and not a _sheet screen_.

I would say we should flag this bug outside the scope of the account selection epic and then we can take a careful look on it because it may be tricky to solve. But once we do, it would fix all instances of the bug.

**Comment by qoqobolo** [comment]
@ilmotta whoa.. this difference between `Sheet screen` and `Bottom sheet component` is completely new to me, so thank you very much for the explanation and investigation the issue.
I noticed that some similar screens/bottom sheets still have some differences, as in your screenshot for example, but I had no idea that they could affect the app's behavior so differently.

Just out of curiosity and for better understanding: is the `close` (`x`) button a `Sheet screen` indicator? Or can `Bottom sheets` sometimes have it too?

Screenshot 2024-02-21 at 16 27 25

---

It is definitely out of the scope of the account selection epic in this case. We'll take care of logging it separately. 

Please let me know when Issue 1 is fixed, I will check the PR again.
Thank you!

**Comment by ilmotta** [comment]
> Please let me know when Issue 1 is fixed, I will check the PR again.

Issue 1 is resolved now @qoqobolo :)

> It is definitely out of the scope of the account selection epic in this case. We'll take care of logging it separately.

Thanks a lot. My guess is that this is an old problem.

> Just out of curiosity and for better understanding: is the close (x) button a Sheet screen indicator? Or can Bottom sheets sometimes have it too?

It should be a good indicator too. Another one is to see if the "sheet" adjusts to the content height until it's expanded. When we see that in Figma or in the app, it means it should use/be our in house _bottom sheet_ component, and not really a modal (in the RN terminology).

**Comment by qoqobolo** [comment]
Thanks for the insights @ilmotta! 🙏

> Issue 1 is resolved now @qoqobolo :)

Confirming that this one is fixed, but I found another one:

### ISSUE 3: `Cancel request to join` / `Leave community` bottom sheets do not fully expand

There might be other places but I only managed to find these two.

**Steps:**
1. Request to join a community
2. Open the three dots menu on the community overview screen
3. `Cancel request to join`

Or try to leave the community if you've already joined it.

**Actual result**

image

https://github.com/status-im/status-mobile/assets/67952253/70c3c0fc-aa07-4049-b716-4332ae2e4292

**Expected result**

image

**Comment by ilmotta** [comment]
@qoqobolo, you surely prevented a bad bug from being introduced, thank you. I rewrote the buggy implementation I originally created to find the max height of the bottom sheet. I checked many cases of bottom sheets, including when there's a currently selected item, such as when we long press on a chat message. They all looked good.

I know it looks dreadfully simple on the outside, but under the hood it was tricky to get a bottom sheet with scrollable content and a fixed header & footer. It is uncommon in the app (couldn't find a single example actually) because we tend to avoid _bottom sheets_ with complex components for performance reasons.

Example video with fix applied:

[Screen_recording_20240223_001102.webm](https://github.com/status-im/status-mobile/assets/46027/eec69cb5-91f1-463b-9ddb-338735d4fd1b)

**Comment by qoqobolo** [comment]
Thanks for the fix @ilmotta!
Now we have a problem with e2e - they can't find the `Add a contact` button here:

Screenshot 2024-02-23 at 14 36 39

Could you check if the accessibility ID has been changed for it, please? That was `accessibility_id="add-a-contact"`

Also, is it possible that this happened to buttons in other bottom sheets?

**Comment by ilmotta** [comment]
> Also, is it possible that this happened to buttons in other bottom sheets?

@qoqobolo This appears to be a specific problem for the e2e test runner because the buttons are all clickable. No accessibility IDs were changed.

Because I can't reproduce, all I can think of is to try another _something_, but this something is really hard to come up with. Does this problem happen for any clickable element on bottom sheets in the e2e tests or just for the add a contact button?

**Comment by qoqobolo** [comment]
> Does this problem happen for any clickable element on bottom sheets in the e2e tests or just for the add a contact button?

Unfortunately, I can’t say because it seems that this button is the first one that is clicked on the bottom sheets in the app in tests (all interactions between users begin with adding a contact), and since all tests fail because of this, it is not clear what would happen next.

We need @yevh-berdnyk's help with this issue. 
I'll let you know as soon as I have some updates.
Sorry for this delay.

**Comment by yevh-berdnyk** [comment]
> > Also, is it possible that this happened to buttons in other bottom sheets?
> 
> @qoqobolo This appears to be a specific problem for the e2e test runner because the buttons are all clickable. No accessibility IDs were changed.
> 
> Because I can't reproduce, all I can think of is to try another _something_, but this something is really hard to come up with. Does this problem happen for any clickable element on bottom sheets in the e2e tests or just for the add a contact button?

hi @ilmotta 
I can see that that the bottom sheet element is fully absent in the app source of this PR's build.
Here is how it looks like in the nightly build:
Screenshot 2024-02-23 at 16 56 00

The same thing happened to the bottom sheet for communities creation.

**Comment by ilmotta** [comment]
Thanks @qoqobolo and @yevh-berdnyk.

@yevh-berdnyk, somewhere in the tree, there should be the bottom sheet content because it's being rendered. At least as far as I checked the e2e video the "Add a contact" button is displayed in this PR's build. Nothing in the tree was changed, except for the view that wraps the bottom sheet content is now positioned absolutely where before it was relatively. I'm pretty sure it has to do with that.

But since the implementation is correct and it's only a failure in the e2e tests, it would be ideal if the e2e could be adapted. I'm not sure if I can find a solution that works in the implementation and in e2e, but I'll try and get back here to share my findings.

**Comment by yevh-berdnyk** [comment]
> Thanks @qoqobolo and @yevh-berdnyk.
> 
> @yevh-berdnyk, somewhere in the tree, there should be the bottom sheet content because it's being rendered. At least as far as I checked the e2e video the "Add a contact" button is displayed in this PR's build. Nothing in the tree was changed, except for the view that wraps the bottom sheet content is now positioned absolutely where before it was relatively. I'm pretty sure it has to do with that.
> 
> But since the implementation is correct and it's only a failure in the e2e tests, it would be ideal if the e2e could be adapted. I'm not sure if I can find a solution that works in the implementation and in e2e, but I'll try and get back here to share my findings.

I can't find the elements from  the bottom sheet neither by the text nor by the accessibility id. If the accessibility id is changed then please provide it and I'll change it in the tests. Anyways the best practise is to use accessibility ids in the tests instead of adapting them somehow.

**Comment by ilmotta** [comment]
@yevh-berdnyk, accessibility IDs are kept intact in this PR. Truly, nothing changed in any of the bottom sheet's contents, except for the absolute positioning of the bottom sheet content, which should be the cause of our problems.

I can't think of any other reason, but as I said I'll have a look and see if I can make the code work for the e2e tests. Though I'm not hopeful :/

**Comment by qoqobolo** [comment]
> I can't think of any other reason, but as I said I'll have a look and see if I can make the code work for the e2e tests. Though I'm not hopeful :/

Screenshot 2024-02-23 at 17 43 20

**Comment by qoqobolo** [comment]
> Does this problem happen for any clickable element on bottom sheets in the e2e tests or just for the add a contact button?

> At least as far as I checked the e2e video the "Add a contact" button is displayed in this PR's build.

@ilmotta just one more detail: apparently, the changes affected more clickable elements on bottom sheets.
We still have tests where adding to contacts is not required, and the tests failed to create a community there, which also happens with the use of bottom sheets. 

You can see an example here
https://app.eu-central-1.saucelabs.com/tests/00c10089b1604a96a7e3dad878ab1b72?auth=b6604219209f996fd1481fcda6913958#41

**Comment by ilmotta** [comment]
@qoqobolo, @VolodLytvynenko, we went from 0% to 12% successful tests. Looks bad still. Do you know if the situation improved by chance or because of my latest attempt to fix for e2e tests? https://github.com/status-im/status-mobile/pull/18919/commits/0b53bb88edadb19a6d212d3e470d44fc974a89e2

Edit: I see this other PR had the same success/fail rate https://github.com/status-im/status-mobile/pull/18971. So apparently e2e tests don't have the regression caused by the bottom sheet component?

**Comment by qoqobolo** [comment]
@ilmotta yes, it definitely got better! Tests find the `Add a contact` button now. Thank you very much for the magic you did to fix this!

> Edit: I see this other PR had the same success/fail rate https://github.com/status-im/status-mobile/pull/18971. So apparently e2e tests don't have the regression caused by the bottom sheet component?

But yes, tests are now failing because of this issue in develop: https://github.com/status-im/status-mobile/issues/18992 :( We need to wait for the fix to check e2e in this PR.

**Comment by ilmotta** [comment]
> @ilmotta yes, it definitely got better! Tests find the `Add a contact` button now. Thank you very much for the magic you did to fix this!
> 
> > Edit: I see this other PR had the same success/fail rate #18971. So apparently e2e tests don't have the regression caused by the bottom sheet component?
> 
> But yes, tests are now failing because of this issue in develop: #18992 :( We need to wait for the fix to check e2e in this PR.

No problem in waiting @qoqobolo. Let's see if the magic will stand another QA strike! ;)

**Comment by qoqobolo** [comment]
Hi @ilmotta, https://github.com/status-im/status-mobile/issues/18992 has been fixed, so could you rebase this PR and rerun e2e please?

**Comment by qoqobolo** [comment]
> Failed tests (43)
Click to expand
Expected to fail tests (1)
Click to expand
Passed tests (4)
Click to expand

Ignore these results, we have [another global issue](https://discord.com/channels/1103692771585433630/1103692773363810317/1212695233909755936)...

**Comment by ilmotta** [comment]
> Ignore these results, we have [another global issue](https://discord.com/channels/1103692771585433630/1103692773363810317/1212695233909755936)...

@qoqobolo, do you think it will be feasible to test this PR manually again until tomorrow? Maybe it's prudent to skip e2e results this time? I'm asking this because someone merged a PR recently that forced me to do a manual rebase. Also because @ajayesivan already has cooked one other PR and he's just waiting for this one to be merged to avoid further code conflicts.

No pressure really, just checking my own expectations.

**Comment by qoqobolo** [comment]
> Maybe it's prudent to skip e2e results this time?

@ilmotta unfortunately, we cannot merge this particular PR without making sure that it does not break the tests, so we need fresh results. I'm really sorry about bad luck of this PR :(

> do you think it will be feasible to test this PR manually again until tomorrow?

Yes, that's what I was going to do today. And the good news that [the issue with peers ](https://github.com/status-im/status-mobile/pull/18919#issuecomment-1970810499) is already fixed, so I can both check the PR manually and rerun e2e. 
I'll let you know the results later today.
Thank you for understanding!

**Comment by qoqobolo** [comment]
UPD: I can't test it even manually because Waku is broken again.
We're waiting for the fix.

**Comment by ilmotta** [comment]
@qoqobolo got it. I'll shut up! Let's not of course break the test suite. Thanks for the updates!

**Comment by qoqobolo** [comment]
Thanks for waiting @ilmotta !

Unfortunately, [Issue 3](https://github.com/status-im/status-mobile/pull/18919#issuecomment-1959553064) is back, both for leaving the community from the community overview screen and from the communities home screen:

Screenshot 2024-03-01 at 16 11 04

The same thing also happens for the bottom sheet with a list of users who put a reaction. 

To reproduce this:
1. Set a reaction
2. Long press the reaction 

Screenshot 2024-03-01 at 16 12 31

And the third place where I currently can see this is an image preview on long-press in the chat:
1. Send a photo
2. Long tap the photo

Screenshot 2024-03-01 at 16 14 49

**Comment by ilmotta** [comment]
@qoqobolo, I tried yet another solution, even simpler. This one I fully tested in all cases and there's no bug. Let's see now!

---

I noticed a bug while testing, and it exists in `develop` too. It was introduced by commit 047e45d2a37c8fd3683c31f68edb5437aa673157. cc @flexsurfer in case you're not aware yet

Notice how the selected item appears only when the bottom sheet is going to be closed.

[new bug in develop.webm](https://github.com/status-im/status-mobile/assets/46027/d4a699fb-2e2a-4b9d-be62-d32500ac8c25)

**Comment by flexsurfer** [comment]
yes sorry it should be fixed soon

**Comment by ilmotta** [comment]
> yes sorry it should be fixed soon

No worries at all, thank you @flexsurfer

**Comment by qoqobolo** [comment]
Can't believe it but it seems this PR is ready to be merged 😱😳
@ilmotta thank you for your patience and awesome work!

**Comment by ilmotta** [comment]
> Can't believe it but it seems this PR is ready to be merged 😱😳 @ilmotta thank you for your patience and awesome work!

Unbelievable @qoqobolo. This PR really tested our tenacity! I thank you for your patience.
