### PR TITLE
fix display name issues

### LINKED ISSUE #15500: Issues related to 'Display name' resolving
### Problem:
If a new user is just created, then his 'display name' is not resolved immediately if to open his profile. Sometimes it takes 3-5 minutes

### Preconditions:
User_B:  sets display name during onboarding

### Steps to reproduce:
1. User_A: Go to 'add contact' page -> Paste chat key of User_B into 'ENS or Chat key' 
2. Tap "view profile" button
3. Check contact name resolving

### Actual result:
- "Display name" of newly created contact is not resolved on the 'User found' section and on the profile page
image

- "Display name" of newly created contact is not resolved on the opened user profile
image

https://user-images.githubusercontent.com/52490791/227979653-60b9c6a6-80e2-4a53-888d-8596025324f5.mp4

### Expected result:
The display name of the contact is shown

### Additional info:
This issue is reproducible in cases if User_A pastes the chat key of User_B which has just been created (1-3 minutes ago)

### PR DESCRIPTION
**Pull request by Parveshdhull**
partially fixes https://github.com/status-im/status-mobile/issues/15500
(Issue 2, 4 & 5)

status: ready

### CODE REVIEW

File: src/status_im2/contexts/onboarding/profiles/view.cljs [hunk 1]
```diff
@@ -181,7 +181,7 @@
        :accessibility-label :forget-password-button
        :override-theme      :dark
        :style               style/forget-password-button}
-      (i18n/label :t/forget-password)]
+      (i18n/label :t/forgot-password)]
```
Comment (Parveshdhull) [inline src/status_im2/contexts/onboarding/profiles/view.cljs:184]: cc: @J-Son89

**Review by briansztamfater — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull thank you for the fixes. PR is tested and ready to be merged
