### PR TITLE
Fix UX issue while spamming the copy button on share shell tab.

### LINKED ISSUE #15926: UX Issue with copy button on share tab
# Bug Report 

Originally discovered by @pavloburykh in https://github.com/status-im/status-mobile/pull/15782

## Problem 
On share tab you have the ability to spam the copy button right next to emoji hash.
 
Screenshot 2023-05-17 at 7 41 15 AM

This produces an array of toast notifications which is probably not the best UX. 
There should either be a cool down period after the button is pressed or a some other way to prevent this multiple toasts appearing but also keeping in mind that the user is not prevented from copying the emoji hash whenever they want.

Maybe one way to prevent this is to check if the same value exists in clipboard we do not allow the user to press the button 🤔

cc @John-44 @pedro-et 

#### Actual behaviour

https://github.com/status-im/status-mobile/assets/97245802/0ce03844-bacd-4bac-ae75-3e10f226f609

- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by siddarthkay**
fixes #15926

### Summary
Few UX improvements were made to share shell screen:

1. Modified `copy-text-and-show-toast` to first dismiss existing toasts before dispatching a new toast notification.
3. Dispatch and chill when the share tab is opened from home screen.

#### Platforms
- Android
- iOS

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

**Comment by siddarthkay** [comment]
@pavloburykh : This is a follow up to : https://github.com/status-im/status-mobile/pull/15782 which you had tested.

File: src/status_im2/contexts/share/events.cljs [hunk 1]
```diff
@@ -4,12 +4,22 @@
             [quo2.foundations.colors :as colors]))
 
 (rf/defn copy-text-and-show-toast
+  "This function will copy the text to a clipboard maintained by re-frame
```
Comment (ilmotta) [inline src/status_im2/contexts/share/events.cljs]: Hey @siddarthkay, I think there's a problem with the existing approach that we both missed in our conversation.

Let's imagine the following:

1. The user copies the emoji hash in status-mobile. The user correctly sees the toast. Pressing again, nothing is showed, perfect.
2. Then the user switches to another app and copy something else there, thus replacing what's currently in the global clipboard.
3. The user goes back to Status and presses copy again, but no toast will be displayed and the text won't be copied.

So I think we should revisit this PR's solution.

Comment (siddarthkay) [reply src/status_im2/contexts/share/events.cljs]: Hi @ilmotta : Thanks for thinking through this one. I knew something like this would happen and that is why the clipboard I'm maintaining in re-frame is separate from the global clipboard on the app  😉 
So we probably do not need to worry about this case 👍🏻

Comment (ilmotta) [reply src/status_im2/contexts/share/events.cljs]: I tested this exact flow, and it clearly seems to be a bug from the user's perspective @siddarthkay.

[untitled.webm](https://github.com/status-im/status-mobile/assets/46027/1ad5758c-97ac-46a8-b6ed-fc6c166ce622)

Comment (siddarthkay) [reply src/status_im2/contexts/share/events.cljs]: ohh good catch! will look into it @ilmotta 
nice edge case you've discovered!

Comment (pavloburykh) [reply src/status_im2/contexts/share/events.cljs]: @siddarthkay please, let me know when this one will be addressed. after that I will take PR into testing. thank you!

Comment (siddarthkay) [reply src/status_im2/contexts/share/events.cljs]: @ilmotta : I got rid of the whole clipboard approach, the new approach is much neater :)

Comment (siddarthkay) [reply src/status_im2/contexts/share/events.cljs]: @pavloburykh : this PR is ready for testing again.

File: src/status_im2/contexts/share/events.cljs [hunk 2]
```diff
@@ -4,12 +4,18 @@
...
+  toast notifications spamming on the screen"
   {:events [:share/copy-text-and-show-toast]}
-  [cofx text-to-copy post-copy-message]
+  [{:keys [db] :as cofx} {:keys [text-to-copy post-copy-message]}]
   (rf/merge cofx
             {:copy-to-clipboard text-to-copy}
+            (toasts/close :successful-copy-toast-message)
             (toasts/upsert
              {:icon           :correct
+              :id             :successful-copy-toast-message
```
Comment (ilmotta) [inline src/status_im2/contexts/share/events.cljs:13]: Since now we're passing the `id`, why do we need to call `toasts/close` @siddarthkay? I thought `upsert` with the same ID would just replace the existing one, so there would be no need to close it first.

Comment (siddarthkay) [reply src/status_im2/contexts/share/events.cljs:13]: @ilmotta : fair enough, i just saw your explanation on the issue, yeah the `toasts/close` was an overkill on my part.

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@siddarthkay thanx for the fix! LGTM. 

Just wanted to clarify regarding second part of the issue originally reported [here](https://github.com/status-im/status-mobile/pull/15782#issuecomment-1548069115): 

**Multiple tap on share button opens several bottom sheets on Android**

Will this one be addressed separately? 

https://github.com/status-im/status-mobile/assets/97245802/c486482f-c479-4ad3-98a4-6bba9ba0b973

**Comment by siddarthkay** [comment]
Hi @pavloburykh : yep I'll address that separately, it involves moving around a native share component to status-im2 namespace so I'll raise another PR for it 👍🏻

**Comment by pavloburykh** [comment]
> Hi @pavloburykh : yep I'll address that separately, it involves moving around a native share component to status-im2 namespace so I'll raise another PR for it 👍🏻

Thank you! current PR is ready for merge.
