### PR TITLE
fix: Marking AC notification as read does not affect correspondent me…

### LINKED ISSUE #18050: Marking AC notification as read does not affect correspondent message in chat
This feature is implemented on [go](https://github.com/status-im/status-go/pull/4337) side but currently not working on mobile.  cc @qfrank 

**Steps:**

1. Generate community AC notification for User A
2. User A marks notification as read in AC
3. Check if corresponding message is marked as read in community

**Actual result:** marking AC notification as read does not affect correspondent message in chat. Unread indicator still remains in community and community channel

[Status-debug-logs (86).zip](https://github.com/status-im/status-mobile/files/13527652/Status-debug-logs.86.zip)

https://github.com/status-im/status-mobile/assets/97245802/910c7ce9-2792-465e-a324-aa1373b272ec

**Expected result:** marking message as read (marking all as read) in AC should affect corresponding messages in communities/group chats. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by qfrank**
fixes #18050

status: ready

### CODE REVIEW

File: src/status_im/chat/models/loading.cljs [hunk 1]
```diff
@@ -192,6 +193,8 @@
 
 (rf/defn load-messages
   [{:keys [db now] :as cofx} chat-id]
+  (println "(get-in db [:pagination-info chat-id :messages-initialized?])"
```
Comment (ilmotta) [inline src/status_im/chat/models/loading.cljs]: Probably a leftover from dev work? If not, please change to use the logger.

File: src/status_im2/contexts/shell/activity_center/events.cljs [hunk 2]
```diff
@@ -124,7 +124,9 @@
 
 (rf/defn mark-as-read-success
   {:events [:activity-center.notifications/mark-as-read-success]}
-  [cofx notification]
+  [cofx {:keys [chat-id] :as notification}]
+  (when chat-id
+    (rf/dispatch [:chats-list/load-chat chat-id]))
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/events.cljs]: @qfrank we shouldn't make events stateful. Calling dispatch is either done inside effects like `:json-rpc/call` or in views.

The code should probably be like this (I roughly tested it). And you will need to update the unit test when using `reg-event-fx` instead of `rf/defn`.

```diff
modified   src/status_im2/contexts/shell/activity_center/events.cljs
@@ -122,12 +122,13 @@
                       :on-error   [:activity-center/process-notification-failure notification-id
                                    :notification/mark-as-read]}]}))
 
-(rf/defn mark-as-read-success
-  {:events [:activity-center.notifications/mark-as-read-success]}
-  [cofx {:keys [chat-id] :as notification}]
-  (when chat-id
-    (rf/dispatch [:chats-list/load-chat chat-id]))
-  (notifications-reconcile cofx [(assoc notification :read true)]))
+(defn mark-as-read-success
+  [_ [{:keys [chat-id] :as notification}]]
+  {:fx [(when chat-id
+          [:dispatch [:chats-list/load-chat chat-id]])
+        [:dispatch [:activity-center.notifications/reconcile [(assoc notification :read true)]]]]})
+
+(rf/reg-event-fx :activity-center.notifications/mark-as-read-success mark-as-read-success)
 
 (rf/defn mark-as-unread
   {:events [:activity-center.notifications/mark-as-unread]}
modified   src/status_im2/contexts/shell/activity_center/events_test.cljs
@@ -69,7 +69,7 @@
                   (fn [& args]
                     (reset! f-args args)
                     :result)]
-      (is (= :result (events/mark-as-read-success cofx notif)))
+      (is (= :result (events/mark-as-read-success cofx [notif])))
       (is (= [cofx [(assoc notif :read true)]]
              @f-args)))))
```

Notice here we use a feature from `:fx` explicitly documented by re-frame, where nil values are ignored, so we can conveniently & conditionally build the vector of effects to be dispatched in order.

If you want to keep using `rf/defn` here to be consistent with the namespace, you'd need to use `rf/merge`.

Comment (qfrank) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: thank you for your reviewing! updated according your comment 🙂 @ilmotta

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/shell/activity_center/events.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: Thanks, PR approved already!

**Comment by churik** [comment]
@qfrank thank you for PR!

There is still an issue if instead of "Making notification as read" we are using "Mark All notification as read"


https://github.com/status-im/status-mobile/assets/4557972/c808bf37-d04f-47af-97bf-a7a393f688ad

It can be fixed separately, as there are some cases with several communities, unread CRs, etc.

What do you think?

**Comment by qfrank** [comment]
let me fix it separately, could you help creating separate issue to track? thank you @churik
