### PR TITLE
fix cannot add existing ENS owned by user

### LINKED ISSUE #18557: Cannot add existing ENS owned by user ("Username does not belong to you" error appears)
**Steps:** 

1. Recover a user who owns ENS
2. Open Legacy settings
3. Tap ENS usernames
4. Try to add existing ENS owned by this user 
5. Observe the result

**Actual result:** "Username does not belong to you" error appears despite ENS is owned by user. I have tried to add ENS that are owned on Mainnet and Goerli networks but result is the same. 

https://app.ens.domains/pavlotest.eth

[Status-debug-logs (95).zip](https://github.com/status-im/status-mobile/files/13975713/Status-debug-logs.95.zip)
photo_2024-01-18 13 04 57

https://github.com/status-im/status-mobile/assets/97245802/51e6b086-1bea-4f83-a63c-6fed765648d0

photo_2024-01-18 13 06 54

**Expected result:** user is able to add ENS which he owns. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/18557

status: ready

### CODE REVIEW

File: src/legacy/status_im/ens/core.cljs [hunk 1]
```diff
@@ -231,7 +231,7 @@
   [db]
   (into #{}
         (remove #(= (:type %) :watch)
-                (map #(eip55/address->checksum (:address %)) (get db :profile/wallet-accounts)))))
+                (map #(eip55/address->checksum (:address (last %))) (get-in db [:wallet :accounts])))))
```
Comment (smohamedjavid) [inline src/legacy/status_im/ens/core.cljs]: @Parveshdhull - The accounts are stored in a key-value (address-account) fashion inside `:wallet :accounts` instead of storing as an array in `:profile/wallet-accounts`.

```suggestion
                (map #(eip55/address->checksum (:address %)) (vals (get-in db [:wallet :accounts]))))))
```

**Review by smohamedjavid — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thank you foe the fix! Failed e2e are not PR related. Ready for merge.
