### PR TITLE
Bottom Sheet Fixes

### LINKED ISSUE #17588: Bottom Sheet bottom spacing doesn't match the design
# Bug Report

The bottom sheet spacing is a bit higher compared to the designs.

#### Expected behaviour

The bottom spacing of the bottom sheet should match the design (should be using the bottom safe area height of the device)

### Reproduction

1. Open Status
2. Long press on any message or community to open the bottom sheet
3. Check the bottom spacing

### Additional Information

- Status version: nightly [08/10]
- Operating System: iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #17588

### Summary

This PR fixes the following issues in the bottom sheet:

1. the sheet is cut off at the bottom in the `shell` (dark blur) theme (the drawers in the onboarding/login flow)

| Bug  | Fix
| --- | --- |
|  |  |

2. the incorrect background in the `shell` (dark blur) theme (the drawers in the onboarding/login flow)

| Bug  | Fix
| --- | --- |
|  |  |

3. the spacing at the bottom is doubled

| Bug  | Fix
| --- | --- |
|  |  |

4. the gradient cover is not shown in the bottom sheet

| Bug  | Fix
| --- | --- |
|  |  |

### Review notes

The recent bottom sheet changes (d5a71e2ce08579919ee3cf8d5f9b535a5d17b91b) have broken the background of the `shell` dark blur variant and gradient cover usage. This PR fixes those bugs.

### Testing notes

The whole application needs to be tested as it updates the bottom sheet core file. A design review is not required as these are bug fixes.

### Platforms

- Android
- iOS

### Steps to test

It is advisable to test the whole application due to core file changes.

#### Gradient Cover component (not used in any screen)

- Open Status
- Navigate to `Quo2 preview > gradient > gradient cover`
- Tap on the `See in bottom sheet` button

status: ready

### CODE REVIEW

File: src/status_im2/common/bottom_sheet/view.cljs [hunk 1]
```diff
@@ -74,9 +74,6 @@
             bottom                  (if sheet-bottom-margin
```
Comment (OmarBasem) [inline src/status_im2/common/bottom_sheet/view.cljs]: I think @jo-mut was working on fixing the extra space at the bottom?

Comment (jo-mut) [reply src/status_im2/common/bottom_sheet/view.cljs]: this pr. addresses the issue https://github.com/status-im/status-mobile/pull/17547

Comment (smohamedjavid) [reply src/status_im2/common/bottom_sheet/view.cljs]: Thanks for the update @jo-mut.

I checked your PR. It resolves the bottom spacing, but the background color on the shell (dark blur) theme and gradient cover is fixed in this PR. 

I guess, I should wait for your PR to get merged. To include your fixes in this PR.

Comment (jo-mut) [reply src/status_im2/common/bottom_sheet/view.cljs]: thats fine with me thank @smohamedjavid

**Review by jo-mut — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fixes @smohamedjavid!
Have a couple of questions about the bottom sheet background

### Q1
This is the background color of the drawers on Android, It's still different from what the desirable color (looks too blue and dark). But could you remind me if this is an issue with blur on Android? I think it has been mentioned before that this cannot be fixed, is this still relevant?

photo_2023-10-11_13-58-12

photo_2023-10-11_13-58-16

### Q2

In this PR, the background color of the bottom sheet is not updated on the `Create a profile` page (when you add a photo) both on Android and iOS. Is this expected?
Screenshot 2023-10-11 at 14 10 25

Screenshot 2023-10-11 at 14 13 05

### Q3

The color of the bottom sheet on the profile selection page on Android has some kind of artifact, apparently again due to blur.
It's hard to see in the original screenshot, but I brightened it up in a photo editor to make it clear what I'm talking about. Is it possible to fix this?
photo_2023-10-11_14-15-25

photo_2023-10-11_14-15-34

**Comment by jo-mut** [comment]
there is this space between the bottom sheet and the selected-item

**Comment by qoqobolo** [comment]
> there is this space between the bottom sheet and the selected-item

@jo-mut hm, I can't reproduce it. What device are you using?
Were there any specific steps to reproduce?
Does the issue persist after relogin/reopening the app?

**Comment by jo-mut** [comment]
> > there is this space between the bottom sheet and the selected-item
> 
> @jo-mut hm, I can't reproduce it. What device are you using? Were there any specific steps to reproduce? Does the issue persist after relogin/reopening the app?

the issue seems to be persistent 
I am able to reproduce this on ios simulator

1. Launch app
2. Long press a community on community home screen to launch the bottom sheet
3. Notice the extra bottom margin
4. Also when you long press on a shot message item to launch the bottom sheet
5. Notice the extra bottom margin

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (jo-mut) [reply src/status_im2/common/bottom_sheet/view.cljs]: @smohamedjavid https://github.com/status-im/status-mobile/blob/43c73d849c64d3c2b083a26c8e395adad71dd8bd/src/status_im2/common/bottom_sheet/view.cljs#L73

removing this code `(:bottom insets)` from the following line will solve the issue on the extra margin

Comment (jo-mut) [reply src/status_im2/common/bottom_sheet/view.cljs]: and also remove `(:bottom insets)`  in this line too and that should fix the issue in this pr
https://github.com/status-im/status-mobile/blob/43c73d849c64d3c2b083a26c8e395adad71dd8bd/src/status_im2/common/bottom_sheet/view.cljs#L74

> (:bottom insets)

**Comment by smohamedjavid** [comment]
Hi @qoqobolo - Thanks for testing the PR!

Below I have answered your questions

> Q1
This is the background color of the drawers on Android, It's still different from what the desirable color (looks too blue and dark). But could you remind me if this is an issue with blur on Android? I think it has been mentioned before that this cannot be fixed, is this still relevant?

You are right, this is an issue with blur on Android. I have attached a screenshot from a PR build from 27th September (I happened to have it in my pixel)

| Login  | Onboarding
| --- | --- |
|  |  |

> Q2
In this PR, the background color of the bottom sheet is not updated on the Create a profile page (when you add a photo) both on Android and iOS. Is this expected?

Yes, The bottom sheet in the "Create a profile" screen is not updated yet. I can update it in this PR if required.

> Q3
The color of the bottom sheet on the profile selection page on Android has some kind of artifact, apparently again due to blur.
It's hard to see in the original screenshot, but I brightened it up in a photo editor to make it clear what I'm talking about. Is it possible to fix this?

I could able to see the issue. The blur actually creates some issues here. I will try to reproduce and fix it in this PR.

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im2/common/bottom_sheet/view.cljs]: Thanks @jo-mut - I will add the fix in this PR 👍

**Comment by qoqobolo** [comment]
Thanks for the answers @smohamedjavid ! 

> Yes, The bottom sheet in the "Create a profile" screen is not updated yet. I can update it in this PR if required

It's up to you. It would be nice to fix it as well, but creating a follow-up issue would be okay too 👍

Figma link for reference https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2316-259092&mode=design&t=kmll7DJYW7pfFoEv-4

Could you also take a look at the issue reported by @jo-mut?
Maybe it's only reproducible on emulators 🤔

**Comment by smohamedjavid** [comment]
Hi @qoqobolo

I have fixed the bottom sheet in the `create profile` screen (Q2). 

Additionally, I have fixed the blur issue in Android (Q3). 

<hr />

> Could you also take a look at the issue reported by @jo-mut?

Sure, I have pushed the fix right now. 

Please retest and let me know if you find any issues. Thanks!

**Comment by qoqobolo** [comment]
@smohamedjavid thank you!

And another bottom sheet using the wrong theme: in the activity center.
How do you feel about fixing this now as well? :)

| PR  | Figma
| --- | --- |
| Screenshot 2023-10-11 at 17 41 53 | Screenshot 2023-10-11 at 17 42 20 |

https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=5387-526165&mode=design&t=IbnqWzZ1D0GVyw1S-4

**Comment by smohamedjavid** [comment]
> And another bottom sheet using the wrong theme: in the activity center.
How do you feel about fixing this now as well? :)

Is this the final one? 😢 

I will push the fix now 👍

**Comment by qoqobolo** [comment]
> Is this the final one? 😢

I hope so 😅 
There are also other drawers with the wrong color, but they are only visible in the dark theme. So I decided to report only this one for now. We will add the rest as follow-ups if we find them later.
Thank you very much for another fix! Don't see any other issues.
I'll quickly recheck the latest build and let you know when it's ready to go!

**Comment by smohamedjavid** [comment]
> There are also other drawers with the wrong color, but they are only visible in the dark theme. So I decided to report only this one for now. We will add the rest as follow-ups if we find them later.

If the issue is caused due to this PR, I'm happy to fix it in this PR.

> I'll quickly recheck the latest build and let you know when it's ready to go!

Thanks again @qoqobolo! 😄

**Comment by qoqobolo** [comment]
> If the issue is caused due to this PR, I'm happy to fix it in this PR.

Yeah, I know! I'm mostly referring to elements that haven't been updated yet.

So, LGTM, PR can be merged.
Thanks for your work @smohamedjavid!
