### PR TITLE
bug #4485 - shows warning when scanned qr code changes pre-selected a…

### LINKED ISSUE #4485: 'Scan QR' changes value in Asset field to ETH (e.g. SNT -> ETH)
### Description

*Type*: Bug

*Summary*: 
Wrong asset might be set after user scanned QR code: if asset was set to anything else than ETH then after scanning it becomes ETH. It means that user can send ETH instead of tokens if this change will not be noticed, e.g 20 ETH instead of 20 SNT

#### Expected behavior
Values in all other fields besides Recipient remain the same after Scan QR code was used

#### Actual behavior
1. Asset filed contains ETH (this is wrong because user already selected other value)
2. Value in the Amount field is not changed
3. Recipient contains scanned address value

### Reproduction
From 0.32 https://app.testfairy.com/projects/4803622-status/builds/8357948/sessions/77/?accessToken=H-fuRBWjDPzcZJmbKnxtd-/TCPg
- Open Status and Sign in
- Open Wallet -> Send Transaction 
- First, change Asset from ETH to STT
- Enter amount 0.02
- After asset and amount got new values tap on Specify Recipient field -> Scan QR code
- Scan valid QR code
- Check values in fields Asset and amount

### Additional Information
* Status version: nightly build May 24
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8357948/sessions/77/?accessToken=H-fuRBWjDPzcZJmbKnxtd-/TCPg">TestFairy: Status build-6010+ (6010) @77</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #4485 

### Summary:

In Wallet Send, if user sets asset to anything other than ETH and then proceeds to scan the QR, metadata from the scanned QR will overwrite the asset to ETH. This PR adds a validation warning to let the user know about the change.

### Steps to test:
See #4485

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/send/db.cljs [hunk 1]
```diff
@@ -7,8 +7,9 @@
 (spec/def ::to (spec/nilable string?))
 (spec/def ::to-name (spec/nilable string?))
 (spec/def ::amount-error (spec/nilable string?))
+(spec/def ::asset-error (spec/nilable string?))
 (spec/def ::amount-text (spec/nilable string?))
-(spec/def ::password (spec/nilable string?))
+(spec/def ::password (spec/nilable (constantly true)))
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/db.cljs]: Is that change intended?

Comment (goranjovic) [reply src/status_im/ui/screens/wallet/send/db.cljs]: Good catch, no. This was temporary workaround for the spec issue with masked password. Just a sec

**Comment by goranjovic** [comment]
Included changes from #4489 so that this PR is testable

**Review by jeluard — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]
LGTM!

**Comment by goranjovic** [comment]
screenshot_20180528-163827

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/bpuTTM for branch PR-4499

<blockquote><div><strong><a href="https://i.diawi.com/bpuTTM">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/pyB3CT for branch PR-4499

<blockquote><div><strong><a href="https://i.diawi.com/pyB3CT">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
@goranjovic Gas limit is not changed to default when Asset is changed from token to ETH. This might lead to higher tx fee, because tokens have Gas limit set to 105000 and ETH has limit 21000. Can we adjust gas limit too, so when Asset is changed to ETH then gas limit is changed from 105000 to 21000?

**Comment by goranjovic** [comment]
It would have no effect on transaction fee, but I changed it to switch to default ether transaction gas in order not to confuse the user.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/fsySYR for branch PR-4499

<blockquote><div><strong><a href="https://i.diawi.com/fsySYR">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/QE6gCX for branch PR-4499

<blockquote><div><strong><a href="https://i.diawi.com/QE6gCX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
@goranjovic on new PR build:
- initial issue is fixed
- issue with gas limit fixed
- new issue 1: Gas limit for sending tokens is set to 21 000 (it's too low) when use "Enter recipient address". Steps: on send transaction set Asset = STT, value 0.001, in Choose recipient use "Enter recipient address" and paste valid address. After this check value in Gas limit
- new issue 2: if try to scan wrong QR code (e.g. public key instead of address), then address is not changed, asset remains STT but gas limit becomes 21 000

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/BfsTdk for branch PR-4499

<blockquote><div><strong><a href="https://i.diawi.com/BfsTdk">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/yZSBA7 for branch PR-4499

<blockquote><div><strong><a href="https://i.diawi.com/yZSBA7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
