### PR TITLE
Fix the bug and remove requests

### LINKED ISSUE #5306: Send button is disabled in request message if cancel sending and send other amount from Wallet to the same contact
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Send button is disabled but user didn't send requested amount. It happens if user taped on Send button, closed Send transaction screen without sending funds, opens Wallet and send other transaction to the same recipient (e.g. 0 ETH instead of request 500 STT).

screenshot_20180726-141548

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Send button is active. It should become disabled only if user sends exact amount and currency with help of this button.
#### Actual behavior
[comment]: # (Describe what actually happened.)
Send button is disabled
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
From 00:40 https://app.testfairy.com/projects/4803622-status/builds/8537431/sessions/4397166304/?accessToken=dGP-4QqQEP86Op74G3GSSVh9RWc
- Open Status
- In 1:1 chat with user X get a request message, e.g Request of 444 STT 
- Tap on send button in the request message and tap on send button in the input field to get Send transaction screen 
-  tap on "<" button to close Send transaction screen (note you haven't sent anything)
- Return to Home tab from 1:1 chat 
- Go to Wallet  -> Send transaction and send same user X another amount, e.g 0 ETH
- Close wallet and open 1:1 chat with user X
- Check if you can tap on the button Send in Request message of 444 STT 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build from July 26 https://jenkins.status.im/job/status-react/job/nightly/522/
* Operating System: Android and iOS. Checked on real Galaxy S6 (Android 6.0.1), Pixel XL (Android 8.1.0) and Iphone 7 plus (iOS 11.4.1)

#### Logs
[geth (5).log](https://github.com/status-im/status-react/files/2231862/geth.5.log)

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8537431/sessions/4397166304/?accessToken=dGP-4QqQEP86Op74G3GSSVh9RWc">TestFairy: Status 0.9.24 (6255) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/522/">status-react » nightly #522 [Jenkins]</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #5306 

Also removes outdated markup from the request command (unnecessary `view` block, conditional markup originally meant for the group command which is not implemented now).
It also removes request db object + events altogether, which greatly simplifies things, because now, the same functionality is done via simple boolean `answered?` flag in request message parameters.

### Testing notes (optional):
Ensure that #5306 is not happening anymore. Also make sure that request message is still displayed correctly in all cases (even between app restarts) and test migration from develop (or last released version) to this PR with couple of requests in the history (both answered and unanswered).

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

File: src/status_im/chat/commands/impl/transactions.cljs [hunk 1]
```diff
@@ -369,67 +378,55 @@
...
-             " "
-             timestamp-str)]]
-          (when-not outgoing
-            [react/view
-             [react/view transactions-styles/command-request-separator-line]
-             [react/view transactions-styles/command-request-button
-              [react/text {:style    (transactions-styles/command-request-button-text answered?)
-                           :on-press on-press-handler}
-               (i18n/label (if answered? :command-button-sent :command-button-send))]]])]]]])))
+          markup            [react/view (transactions-styles/command-request-message-view outgoing)
```
Comment (yenda) [inline src/status_im/chat/commands/impl/transactions.cljs:388]: couldn't it be defined as a view in screens or component, taking params as input ?

**Review by yenda — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]
