### PR TITLE
[bug] fix #2128 No feedback on insufficient funds from unsigned

### LINKED ISSUE #2054: Scientific notation for amount is shown on Sent Transaction screen if opened from Unsigned tab or from chat
### Description

*Type*: Bug

*Summary*: Scientific notation for amount is shown on Sent Transaction screen  if it's opened from Unsigned tab or from chat via send command:
screenshot_20171009-184433

#### Expected behavior
Amount is shown in usual format, e.g. `0.00000007`
#### Actual behavior
 Scientific notation for amount is shown `7e-8`

### Reproduction

- Open Status
- Open 1-1 chat
- send to Jarrad 0.1 eth

### Additional Information
* Status version: develop  0.9.10-179-g3225d1a2
* Operating System: 
Real device iPhone 6s, iOs 10.3.1
Real device iPhone 7 plus, iOs 11.0.2
Real device Google Pixel XL, Android 8.0

### LINKED ISSUE #2128: No feedback on insufficient funds if send transaction from Unsigned
*Type*: Bug

*Summary*: Transaction is in the Unsigned list and its sum is more than wallet balance. Currently, user can open a transaction, sign it, provide a password and there is no feedback about insufficient funds. There is the same password popup shown to the user.

It's expected that if there are less funds then in unsigned transaction amount then
1. Sign Transaction should be disabled.  
2. `Insufficient funds` error should be shown above Amount field.

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/6823766/sessions/2/?accessToken=0JqVem9n8RpvLHMTUWSUQAA-G3w
- Open Status
- Open Wallet and create an unsigned transaction with amount that is more than you have (e.g. amount is 10 when wallet balance is 0.1)
- Open Transactions -> Unsigned and tap on Sign under the new transaction

### Additional Information
* Status version: develop
* Operating System: 
Real device iPhone 6s, iOs 10.3.1
Real device Samsung Galaxy S6, Android 6.0.1

### LINKED ISSUE #2132: Unsigned transactions from 1 account are shown for another account on the same device
### Description

*Type*: Bug

*Summary*: There are 2 accounts in the app. When account 1 adds some unsigned transaction then it's shown also in the list for unsigned transactions of account 2. would expect that only the "creator" of the unsigned transaction has it in the Unsigned list and other accounts do not.

### Reproduction
There are 2 accounts in the app  
- Open Status as account 1
- add transaction to Unsigned from the Wallet
- switch users
- sign in as account 2
- open list of Unsigned transactions and check if there is a new transaction from account 1 (it's expected that there will be no such transaction)

### Additional Information
* Status version: develop
* Operating System: 
Real device iPhone 6s, iOs 10.3.1

### PR DESCRIPTION
**Pull request by yenda**
fixes #2128 
fixes #2054
fixes #2132 (by merging PR)

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
- move current unsigned-transaction to wallet
- move some logic from view to subscriptions and events

### Steps to test:
- Open Status
- Create transaction with insufficient funds and sign later
- Sign transaction from unsigned and check that the Sign transaction action is disabled and warning about insufficient funds is shown

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/choose_recipient/events.cljs [hunk 1]
```diff
@@ -6,12 +6,12 @@
 (handlers/register-handler-db
   :wallet/toggle-flashlight
   (fn [db]
-    (let [flashlight-state (get-in db [:wallet/send-transaction :camera-flashlight])
+    (let [flashlight-state (get-in db [:wallet :send-transaction :camera-flashlight])
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/choose_recipient/events.cljs:9]: `send-transaction` was in wallet ns, and it shouldn't be in wallet map, could you elaborate?

**Comment by flexsurfer** [comment]
@yenda i can see a lot of changes which are not in the scope of this PR, could you move refactoring in another PR or commit?

File: src/status_im/ui/screens/wallet/navigation.cljs [hunk 2]
```diff
@@ -20,8 +20,4 @@
   [db [event]]
   (if (= event :navigate-back)
     db
-    (dissoc db :wallet/send-transaction)))
-
-(defmethod navigation/preload-data! :wallet-send-transaction-modal
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/navigation.cljs:25]: why did you delete this?

File: src/status_im/ui/screens/wallet/send/db.cljs [hunk 3]
```diff
@@ -18,10 +18,10 @@
 (spec/def ::camera-flashlight #{:on :off})
 (spec/def ::camera-permitted? boolean?)
 (spec/def ::in-progress? boolean?)
-(spec/def ::from-chat? boolean?)
+(spec/def ::from-chat? (spec/nilable boolean?))
 
 (spec/def :wallet/send-transaction (allowed-keys
                                      :opt-un [::amount ::to-address ::to-name ::amount-error ::password
-                                              ::waiting-signal? ::signing? ::transaction-id ::later?
+                                              ::waiting-signal? ::signing? ::id ::later?
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/db.cljs:25]: `transaction-id` is more clear

File: src/status_im/ui/screens/wallet/transactions/events.cljs [hunk 4]
```diff
@@ -25,35 +25,31 @@
...
+                  (assoc-in [:wallet :send-transaction :id] id))}
+         (if (get-in db [:wallet :send-transaction :waiting-signal?])
+           ;;sending from wallet
+           {:dispatch [:wallet.send-transaction/transaction-queued id]}
+           ;;sending from chat
+           {:dispatch [:navigate-to-modal :wallet-send-transaction-modal id :from-chat]})))
       {:discard-transaction id})))
 
-;TRANSACTION FAILED signal from status-go
+                                        ;TRANSACTION FAILED signal from status-go
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/transactions/events.cljs]: indentation

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/wallet/send/db.cljs (hunk 3 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/send/db.cljs:25]: there was a mix of id and transaction-id I just settled on id but yeah can switch to transaction-id

File: src/status_im/ui/screens/wallet/navigation.cljs (hunk 2 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/navigation.cljs:25]: because it is not needed anymore

File: src/status_im/ui/screens/wallet/choose_recipient/events.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/choose_recipient/events.cljs:9]: two main reasons for me are
- it makes it easier to clear out when switching accounts
- less top-level subscriptions

File: src/status_im/ui/screens/wallet/send/db.cljs (hunk 3 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/send/db.cljs:25]: the main reason I settled for id is because that is how the field is called in unsigned-transactions list

File: src/status_im/ui/screens/wallet/send/subs.cljs [hunk 5]
```diff
@@ -1,27 +1,76 @@
...
+            [status-im.i18n :as i18n]
+            [status-im.utils.money :as money]
+            [status-im.utils.hex :as utils.hex]))
+
+(re-frame/reg-sub ::send-transaction
+  :<- [:wallet]
+  (fn [wallet]
+    (:send-transaction wallet)))
+
+(re-frame/reg-sub :wallet.send/camera-dimensions
```
Comment (yenda) [inline src/status_im/ui/screens/wallet/send/subs.cljs:12]: camera stuff could go in a camera key since only once view consumes the three anyway but I kept that for later

File: src/status_im/ui/screens/wallet/choose_recipient/events.cljs (hunk 1 above)
Comment (janherich) [reply src/status_im/ui/screens/wallet/choose_recipient/events.cljs:9]: I agree with @yenda on this

**Comment by yenda** [comment]
2 bugs I need to fix:

- [x] - X action should cancel with send command in chat
- [x] - similar label than the one in transaction details should be shown when transaction expires

File: src/status_im/ui/screens/wallet/transactions/events.cljs [hunk 6]
```diff
@@ -21,39 +21,35 @@
...
+        (merge
+         {:db (-> db
+                  (assoc-in [:wallet :transactions-unsigned id] transaction)
+                  (assoc-in [:wallet :send-transaction :id] id))}
+         (if (get-in db [:wallet :send-transaction :waiting-signal?])
+           ;;sending from wallet
+           {:dispatch [:wallet.send-transaction/transaction-queued id]}
+           ;;sending from chat
+           {:dispatch [:navigate-to-modal :wallet-send-transaction-modal id :from-chat]})))
       {:discard-transaction id})))
```
Comment (janherich) [inline src/status_im/ui/screens/wallet/transactions/events.cljs]: Why is `:from-chat?` not set anymore when signal from go about queued transaction arrives ? It's necessary so closing modal correctly  removes transaction from unsigned-queue (and discards it).

**Review by janherich — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/wallet/transactions/events.cljs (hunk 6 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/transactions/events.cljs]: thanks I was going to investigate why it doesn't close anymore as you can see in my comment above.

File: src/status_im/ui/screens/wallet/choose_recipient/events.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/choose_recipient/events.cljs:9]: the idea to have ns keywords is to find usages , and `:wallet/wallet` for wallet screen,  `:wallet/send-transaction` for send-transaction screen, tbh can't see how it makes it harder to clear out

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by jeluard** [comment]
@yenda Please rebase

**Comment by annadanchenko** [comment]
1. if type amount and than select recipient then typed amount becomes “0.000”. Expected: typed amount stays in the field

**Comment by yenda** [comment]
@annadanchenko if I am not mistaken this bug is also in develop so it is not related to this PR

**Comment by annadanchenko** [comment]
Created a separate bug as older develop build was used by me and Eric was using the recent develop brunch with the bug described below, see #2189 

@yenda it's not in the develop. 

Steps to reproduce:
- open wallet
- tap Send
- in Amount type 123
- tap on Recipient
- Select from contact Jarrad
- check amount on Send screen: in develop it's still 123, in this PR it's 0.

TF session from develop (OK): https://app.testfairy.com/projects/4803622-status/builds/6870654/sessions/8/?accessToken=H4Q/1FaXg31061/NVej95a6g2pE
TF session from this PR (not OK): https://app.testfairy.com/projects/4803622-status/builds/6879704/sessions/4/?accessToken=shMeY4FH1-yBNyHZvupRNF0j7pw
