### PR TITLE
fix: ensure clean-up state after send transaction confirmation

### LINKED ISSUE #21251: "eq() not a number: <0.01" Error shown after transaction confirmation
Follow up for https://github.com/status-im/status-mobile/pull/21235

### Steps:
1. Open account
2. Go to the routes generation page -> confirm a transaction

### Actual result:
The user is redirected to the activity page, where the error message "eq() not a number: <0.01" is displayed.

image

### Expected result:
The transaction should be confirmed without showing any error messages
### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (7).zip](https://github.com/user-attachments/files/16947924/logs.7.zip)

### PR DESCRIPTION
**Pull request by seanstrom**
partially fixes https://github.com/status-im/status-mobile/issues/21251

### Summary

* This PR attempts to resolve some issues that have been occurring after sending a transaction.
  * BigNumber errors for `"<0.01"`
    * It seems we're storing this string `"<0.01"` for some wallet ui state, but that state can be accidentally used with BigNumber calculations, which can exceptions.
    * Here's where we inject this string into the ui state: https://github.com/status-im/status-mobile/blob/69664322b8ea01a87e7762c24dcace3c6f917991/src/status_im/contexts/wallet/send/utils.cljs#L67
    * And here's where we are referencing that value: https://github.com/status-im/status-mobile/blob/2f3d3fc7f90bfddc12d8a21bf6202e5af4c5dcb6/src/quo/components/wallet/summary_info/view.cljs#L33-L40
  * Suggest Routes being received after the send transaction is already confirmed
    * It seems like we weren't configuring the wallet send screen to finish requesting the suggested routes data after the user has confirmed the transaction. And as we would continue to receive more suggested route results, the calculations would run with the existing wallet ui state, and that would eventually do some BigNumber comparisons with the string `"<0.01"` which would cause things to throw.
* Ideally, we would refactor the code in a way that avoids saving `"<0.01"` into the database, perhaps we can save an separate keyword like `:less-than-something` to indicate the same thing. Maybe this would avoid potential number comparison issues in the future.

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Login as user with funds
- Navigate to wallet home screen
- Open account with funds
- Press the "send" button to start a transaction
- Choose an account for receiving the transaction
- Input an amount of funds below `0.01`, like `0.001`
- Review and Confirm the transaction

#### Before Changes
 
https://github.com/user-attachments/assets/3fff742e-0e1d-45f3-9096-7e9c4bb76384

#### After Changes

https://github.com/user-attachments/assets/d1e4b91c-f640-49cd-a476-aa4329104b1d

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/send_amount/view.cljs [hunk 1]
```diff
@@ -2,11 +2,13 @@
   (:require
     [quo.theme]
     [status-im.contexts.wallet.send.input-amount.view :as input-amount]
+    [status-im.setup.hot-reload :as hot-reload]
     [utils.i18n :as i18n]
     [utils.re-frame :as rf]))
 
 (defn view
   []
+  (hot-reload/use-safe-unmount #(rf/dispatch [:wallet/stop-get-suggested-routes]))
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/send/send_amount/view.cljs:11]: Here we're configuring the wallet send screen to dispatch the `:wallet/stop-get-suggested-routes` event when unmounting the component. Without this, it seems that we'll continue to receive suggested route signals, which can cause some glitches because we're re-processing stale wallet send UI state.

File: src/utils/money.cljs [hunk 2]
```diff
@@ -60,7 +60,9 @@
 (defn equal-to
   [n1 n2]
   (when-let [^js bn1 (bignumber n1)]
-    (.eq ^js bn1 n2)))
+    (try
+      (.eq ^js bn1 n2)
+      (catch :default _ false))))
```
Comment (seanstrom) [inline src/utils/money.cljs]: Here we're attempting to prevent exceptions from being thrown because of the BigNumber library failing to do a comparison. Perhaps we should not catch all exceptions here, but I think it's safer to assume that any failure would mean the comparison failed, which would mean the two things are not equal.

But maybe there's a better way to handle these exceptions, thoughts?

**Review by seanstrom — COMMENTED** [review]
Self Review 📑

**Comment by shivekkhurana** [comment]
Hi, this issue comment was made into a separate issue and assigned to @vkjr 
https://github.com/status-im/status-mobile/issues/21251

@seanstrom your changes look good, if @vkjr has nothing against it we can go forward and use this PR.

**Comment by seanstrom** [comment]
@shivekkhurana thanks I've updated the PR with the link to the issue 👍 

@vkjr based on some of the exceptions I saw when debugging, it could be still useful to refactor the code to avoid saving the `"<0.01"` into the re-frame database. This PR does not change any of that code, it sorta prevents the exceptions from happening as much, but it could be better to re-structure things. Let me know what you think 🙏

**Review by vkjr — APPROVED** [review]

File: src/utils/money.cljs (hunk 2 above)
Comment (vkjr) [reply src/utils/money.cljs]: @seanstrom, I think that we can avoid try/catch which is not common in our codebase by checking both arguments with `(bignumber?)` before calling `.eq`, wdyt?

**Review by vkjr — APPROVED** [review]

**Comment by vkjr** [comment]
@seanstrom, thanks for the PR, it will stop us from having exception. And I will investigate how that "<0.01" makes its way to that function, it shouldn't happen)
cc @shivekkhurana

**Comment by vkjr** [comment]
As @seanstrom correctly assumed, the fail happens because `re-frame` compares previous and new db value and in previous value stored BigNumber, whereas new values is a string that can't be converted to digit. As a result `equal-to` called with incorrect string as an argument and throws exception.

Throwing exception is expected and covered by tests by @ilmotta [here](https://github.com/status-im/status-mobile/pull/20614/files#diff-68c6c023432f03bf818ff1f88948314fcfeea90e49456e7bc4f167e14122057bR23), but I think that overall BigNumber is too fragile and we shouldn't allow it to throw exception. Because result of `(equal-to some-bignumber "invalid-string")` can easily be `false` and that will be logically correct.

So my suggestion is to wrap all functions in `utils/money` with extra checks to avoid any unexpected exceptions. Because as a developer I want to pass random staff into functions and be sure they will survive)
Something like this:
```clojure
(defn equal-to
  [n1 n2]
  (when-let [^js bn1 (bignumber n1)]
    (when-let [^js bn2 (bignumber n2)]
      (.eq ^js bn1 ^js bn2))))
```
Wdyt, @seanstrom @ilmotta @shivekkhurana ?

File: src/utils/money.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/utils/money.cljs]: I am not sure what is the best approach, but I've recently updated `greater-than` `less-than` and `greater-than-or-equals` functions with a `bignumber?` check. The check was only needed on the first argument to avoid the error. We could use the same approach on `equal-to` for consistency.

**Review by ilmotta — APPROVED** [review]
> Ideally, we would refactor the code in a way that avoids saving "<0.01" into the database, perhaps we can save an separate keyword like :less-than-something to indicate the same thing. Maybe this would avoid potential number comparison issues in the future.

Thanks a lot for helping with this bug @seanstrom. I was kind of expecting us to fix the root cause to avoid further problems. Even the names `to-network-values-for-ui` and `from-network-values-for-ui` are good hints that they shouldn't be stored in the app-db. Perhaps not too risky to fix the problem because the values are only used by one event which is dispatched from only one place after a signal arrives. The event also has one unit test, that should help a bit.

But of course, could be a follow-up PR, but would be nice if we never stored formatted data in the app-db, unless there's a good reason, like a performance concern where it's very expensive to recompute in subs and the computed data is read heavy much more than write heavy in the UI.

File: src/utils/money.cljs (hunk 2 above)
Comment (vkjr) [reply src/utils/money.cljs]: @briansztamfater, I also think that everything should be wrapped in checks, including second argument, because for `equal-to` second argument causes exception. I wrote an example down below.

**Comment by ilmotta** [comment]
> So my suggestion is to wrap all functions in `utils/money` with extra checks to avoid any unexpected exceptions. Because as a developer I want to pass random staff into functions and be sure they will survive) Something like this:

I fully agree @vkjr. Throwing an exception is quite bad for users because they bubble up in the whole stack. The bignumber library can throw for various reasons, probably not only because the inputs are not instances of bignumbers. It would be a good idea to take a look at the docs or implementation to see the possible causes of errors because we may need to wrap in a `try/catch` in some cases.

The other thing we should do ideally is to have a proper layer (data store ns) that always decodes data from status-go into the proper data types for Clojure. If a string arrives and it's supposed to be a bignum, it shouldn't flow throughout the system for too long as a raw string because eventually it can easily reach code that thinks it's a proper number. I've personally faced this problem multiple times in a previous Clojure project.

We extended `BigNumber` with `IEquiv` and `IComparable`, which should help us store them in the app-db and nicely manipulate them. More importantly, it means that if we store bignums in the app-db, re-frame will do the equalities correctly (something we were doing wrong some time ago and caused all subs caches to be invalidated whenever they had instances of bignums) https://github.com/status-im/status-mobile/blob/1190fc80697d9665113715093c9fcaa5b173e593/src/utils/money.cljs#L65

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -91,8 +87,8 @@
                      assoc
                      :suggested-routes          suggested-routes-data
                      :route                     chosen-route
-                     :from-values-by-chain      from-network-values-for-ui
-                     :to-values-by-chain        to-network-values-for-ui
+                     :from-values-by-chain      from-network-amounts-by-chain
+                     :to-values-by-chain        to-network-amounts-by-chain
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/send/events.cljs:91]: Here's where we were storing the UI strings inside the re-frame state. Now we'll store the original data and do the conversions inside the UI components.

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 4]
```diff
@@ -142,7 +143,7 @@
      [quo/summary-info
       {:type          summary-info-type
        :networks?     true
-       :values        network-values
+       :values        (send-utils/network-values-for-ui network-values)
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:146]: Here's one place we were using the UI strings inside network-values, because summary-info will use the string "<0.01" to determine if some UI should be shown. Not sure what the original intent of that code would be, but perhaps that code could be changed too.

File: src/utils/money.cljs [hunk 5]
```diff
@@ -42,25 +42,35 @@
...
+  [n1 n2]
+  (when-let [[^js bn1 ^js bn2] (->bignumbers n1 n2)]
     (.lessThan ^js bn1 bn2)))
 
 (defn equal-to
   [n1 n2]
-  (when-let [^js bn1 (bignumber n1)]
-    (.eq ^js bn1 n2)))
+  (when-let [[^js bn1 ^js bn2] (->bignumbers n1 n2)]
+    (.eq ^js bn1 bn2)))
```
Comment (seanstrom) [inline src/utils/money.cljs]: Here we're adding some additional checks for big number instances when using our big number utility functions. Let me what you think 🙏

**Review by seanstrom — COMMENTED** [review]
More self review after updates 📖 
Please have a look when you have a chance 🙏 
cc @vkjr @briansztamfater @ilmotta

File: src/utils/money.cljs (hunk 5 above)
Comment (vkjr) [reply src/utils/money.cljs]: I love this approach!

**Comment by vkjr** [comment]
@seanstrom, thanks for the improvements! 🙏

**Comment by mariia-skrypnyk** [comment]
Hey @seanstrom !

Thanks for your fix.
Checked on both platforms and looks good.
Great job as usual!
PR cam be merged.

File: src/utils/money.cljs [hunk 6]
```diff
@@ -42,25 +42,35 @@
   [x]
   (instance? BigNumber x))
 
+(defn ->bignumber
+  [n]
+  (if (bignumber? n) n (bignumber n)))
+
+(defn ->bignumbers
```
Comment (ilmotta) [inline src/utils/money.cljs:49]: This function is only used for 1 pair of inputs at a time. Also, for a low-level construct to build instances, I think we should skip the overhead of varargs and processing `nums` twice with `map` and `every?`.

Because `->bignumber` (singular) conveniently returns a BigNumber instance or nil, I think we can skip completely the extra `->bignumbers` (plural) function because we can create a vector on the fly, like this:

```clojure
;; PR implementation
(defn less-than
  [n1 n2]
  (when-let [[^js bn1 ^js bn2] (->bignumbers n1 n2)]
    (.lessThan ^js bn1 bn2)))

;; Suggestion
(defn less-than
  [n1 n2]
  (when-let [[^js bn1 ^js bn2] [(->bignumber n1) (->bignumber n2)]]
    (.lessThan bn1 bn2)))
```

The suggestion is still as readable, if not more due to the elimination of the extra indirection.

In terms of benchmarks, this simple change can reduce the time by almost 50% in my tests of `less-than`. Our conversion of numbers is relatively slow already because we always normalize numbers with `money/normalize`, which is very odd to be a default. I actually found the original commit that introduced normalization by default and it really makes no sense anymore https://github.com/status-im/status-mobile/commit/06650aecbb because this was added to conveniently allow to add commas in gas inputs, but the vast majority of cases shouldn't need the slow regex processing we do to instantiate bignums.

**Review by ilmotta — APPROVED** [review]
@seanstrom, PR LGTM. My only suggestion is that we avoid making BigNumber instances even slower.

File: src/utils/money.cljs (hunk 6 above)
Comment (ilmotta) [reply src/utils/money.cljs:49]: Just to be clear @seanstrom, I wouldn't touch the normalization part in this PR. I just wanted to illustrate that creating BigNumber instances is already slow, but this is a part of the code where we should make things fast.

Comment (seanstrom) [reply src/utils/money.cljs:49]: @ilmotta Okay sounds good, I'll try refactoring the code to not use `varargs` and avoid doing multiple passes on list of bignum inputs.

One thing to note is that this code:
```clojure
(defn less-than
  [n1 n2]
  (when-let [[^js bn1 ^js bn2] [(->bignumber n1) (->bignumber n2)]]
    (.lessThan bn1 bn2)))
```

Might not work the same with `when-let` because we're always returning a vector, and we want to coerce/check if each number is a big number (I think).
Initially `->bignumbers` was a function that used two `when-let` expressions check if both numbers were bignumbers, but I ended up refactoring to varargs stuff. Though maybe that function is doing too much, and refactoring that function to use transducers might not be worth it either. So I'll reverting back to the double `when-let` like this:

```Clojure
(defn ->bignumbers
  [n1 n2]
  (when-let [bn1 (->bignumber n1)]
    (when-let [bn2 (->bignumber n2)]
      (when (and (bignumber? bn1) (bignumber? bn2))
        [bn1 bn2]))))
```

This way we still return the vector of numbers when both numbers are valid big numbers. Thoughts?

Comment (seanstrom) [reply src/utils/money.cljs:49]: On a side note, maybe we can update that normalising code to check if the input is a string? Because if the input is not a string I don't think it will have commas present when coerced to a string. That way we may be able to avoid the extra normalising logic for numeric inputs. 💭

Comment (ilmotta) [reply src/utils/money.cljs:49]: Nice catch @seanstrom, definitely my snippet wouldn't work and I didn't test *properly the snippet I shared. Your new snippet seems correct 👍🏼 What I like about using an optimized arity-2 implementation like what we are doing now is that we can always add arity-x in a backwards compatible way, similar to how `cljs.core/+` works.

> On a side note, maybe we can update that normalising code to check if the input is a string?

I had the impression (no evidence now) that most values we pass to `->bignumber` are strings, so maybe this wouldn't be too effective?

From that original old commit I shared, I think the solution wasn't the best because cleaning up user input is a distant concern for a utility such as `money` instantiating bignums.

In the few cases where a bignum has to be created from user input, then the UI code can do the clean-up/normalization explicitly. This would be the best I think, because in all other cases bignums should be instantiated from proper bignum strings sent from the backend, and those shouldn't have formatting chars like `,`.

But probably safer if my suggestion or yours is applied in a separate PR?

Comment (seanstrom) [reply src/utils/money.cljs:49]: Yup yup I think it's better to tweak the normalising logic in a separate pr 👍 
And yeah the two-arity refactor is very nice, thank you 🙌
