### PR TITLE
Fix missing avatar and name in members of the community channels and group chats

### LINKED ISSUE #20431: No user's name in system message in a Group chat if he is not your contact
# Bug Report

### Reproduction

1. Login as `user A` with a lot of contacts
2. Login as a newly created `user B` (on another device or create a multiaccount)
3. As `user A` create a group chat with User B and +1 contact
4. As `User B` open group chat from step 3 and look at system message

#### Expected behavior
System message contains user's names that all are visible

#### Actual behavior
No user's name in system message in a Group chat if he is not your contact

Screenshot 2024-06-11 at 11 39 58

### Additional Information

- Status version: nightly 11/06
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #20520: Communities: Missing avatar and name in members of the Status community
# Bug Report

## Problem

The community channel members' list may contain contacts where no data exists except their public key. For example, in the Status community channel `#general`, there are around 55 such contacts out of ~220 in total.

### Expected Behavior

We would like to display a better fallback when members (contacts) don't have any associated information, except their public key. We have verified that this is a technical limitation and that there's nothing we can do.

We can at least mimic what the desktop app does:

- Always show a ring. We have the key, so this is possible.
- Show the first character of the key instead of no initials and an empty avatar circle.
- Show the compressed key. We still fallback to the public key.

**NOTE**: Consider investigating why the desktop app doesn't suffer from the same problem as mobile. What are we doing differently?

### Actual Behavior

As you can see below, contacts with only their public key available are shown with empty avatars (using the profile's customization color as fallback) and the name section is empty.

### Reproduction

1. Open Status community > Channel > View members.

### Additional Information

- Status version: nightly
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20520
fixes https://github.com/status-im/status-mobile/issues/20431

status: ready

### CODE REVIEW

File: src/native_module/core.cljs [hunk 1]
```diff
@@ -331,6 +331,11 @@
              :key input-key})
   (.deserializeAndCompressKey ^js (encryption) input-key callback))
 
+(defn serialize-legacy-key
+  "serialize-legacy-key compresses an old format public key (0x04...) to the new one zQ..."
```
Comment (ilmotta) [inline src/native_module/core.cljs]: I would just take away the name of the function from the docstring because that's a Go convention.

File: src/status_im/subs/contact/utils.cljs [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+(defn replace-contact-image-uri
+  [{:keys [contact port public-key font-file theme]}]
+  (let [{:keys [images ens-name customization-color]} contact
+        images
+        (reduce (fn [acc image]
+                  (let [image-name (:type image)
+                        clock      (:clock image)
+                        options    {:port port
+                                    :ratio pixel-ratio/ratio
+                                    :public-key
```
Comment (ilmotta) [inline src/status_im/subs/contact/utils.cljs]: Since you're touching this function, could you format the key and values to be on the same line?

**Review by ilmotta — APPROVED** [review]
Looks miles better than what's in `develop` 🚀

**Comment by ilmotta** [comment]
@Parveshdhull, do you see any connection about the fixes being made here and this other issue? https://github.com/status-im/status-mobile/issues/17229 The video in that PR description is helpful.

**Comment by Parveshdhull** [comment]
> @Parveshdhull, do you see any connection about the fixes being made here and this other issue? #17229 The video in that PR description is helpful.

Hi @ilmotta I am not sure but some of the issues mentioned in https://github.com/status-im/status-mobile/issues/17229 might have been fixed in the PR.

> You will see bunch of users with pub keys with absent profile icons etc

**1.** As we are modifying subscription which returns `:chats/photo-path` icons for mentions probably fixed.

image

**2.** In this case, the empty mention might have been fixed.

But I think it all depends if these components are using these subscriptions or not. I guess once this PR is merged, we can update https://github.com/status-im/status-mobile/issues/17229 or create a new issue with a changed scope. wdyt?

**Comment by ilmotta** [comment]
> But I think it all depends if these components are using these subscriptions or not. I guess once this PR is merged, we can update https://github.com/status-im/status-mobile/issues/17229 or create a new issue with a changed scope. wdyt?

Good idea 👍🏼 Thanks!

**Comment by VolodLytvynenko** [comment]
I am currently blocked in testing of this PR due to Waku issues.

**Comment by VolodLytvynenko** [comment]
hi @Parveshdhull thank you for PR. One issue is found
## PR_ISSUE 1: {e...gth} is shown instead of display name within removal account drawer

### Steps:
1. Go to login page
2. Open list of accounts
3. Open remove drawer
4. Check display name within drawer

### Actual result:
{e...gth} is shown instead of the display name within the removal account drawer.
image

### Expected result:
Display name is shown within removal account drawer

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by Parveshdhull** [comment]
Thank you @VolodLytvynenko for finding this issue. Should be fixed now.

**Comment by VolodLytvynenko** [comment]
sorry. It seems I missed this additional issue during previous testing session. Could you take a look it please?

## ISSUE 2: The list of mentions is not shown or shown with significant delay if a lot of members are in the chat

### Steps:
1. Open a chat with a large number of members. (In my case, I was not able to create such a large number of members to reproduce this issue. Therefore, the better recommendation is to open or dogfood the Status community for this case.)
2. Type "@" to mention a member.

### Actual result:
The list of mentions is not shown or appears with a significant delay.

In the record for comparison how it works in the current PR (till 20th second) and in the last nightly (from 20th second).

Android: 

https://github.com/status-im/status-mobile/assets/52490791/d67b6b23-a019-439e-8f33-a93caaa22cdb

IOS: 

https://github.com/status-im/status-mobile/assets/52490791/68d8c2ed-2097-433b-a61e-28ab5ecacf2e

### Expected result:
The list of mentions should be shown promptly without delay.


### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

**Comment by Parveshdhull** [comment]
Thank you @VolodLytvynenko for reporting the issue.

> In the record for comparison how it works in the current PR (till 20th second) and in the last nightly (from 20th second).

Weird, I was trying another PR build and got the same result (long delay). Maybe PR itself adds some delay, but from quick testing, it seems the issue might already be in `develop` or something related to PR builds, but I'm not sure.

<details>
<summary>Comparison Videos</summary>
Current PR before 1:00 and another PR after 1:00

https://github.com/status-im/status-mobile/assets/17097240/c5b89409-7f93-4556-a01c-212f66f0dce1

</details>

**Comment by Parveshdhull** [comment]
In the PR

image

In develop
image

cc @flexsurfer @cammellos

**Comment by Parveshdhull** [comment]
@VolodLytvynenko  Issue 2 doesn't seem related to PR, I think we need to address it separately

**Comment by Parveshdhull** [comment]
We only show 15 mentions at a time, not sure why we are returning whole members list on call of `wakuext_chatMentionOnChangeText` with text "@".
I think returning first 15 matches will be enough, wdyt? @flexsurfer @cammellos 

UPD: Created an issue https://github.com/status-im/status-mobile/issues/20722

**Comment by VolodLytvynenko** [comment]
> Weird, I was trying another PR build and got the same result (long delay). Maybe PR itself adds some delay, but from quick testing, it seems the issue might already be in `develop` or something related to PR builds, but I'm not sure.
> 
> Comparison Videos

@Parveshdhull You are right. This happens within PR builds. But  I can't reproduce it within last develop. Thank you!

**Comment by VolodLytvynenko** [comment]
@Parveshdhull thank you for PR. No issues from my side. PR is ready to be merged

**Review by flexsurfer — COMMENTED** [review]
hey @Parveshdhull didn't `multiformatSerializePublicKey` work ?

**Comment by Parveshdhull** [comment]
Thank you @flexsurfer for reviewing the PR.

> hey @Parveshdhull didn't `multiformatSerializePublicKey` work ?

I think `multiformatSerializePublicKey` will also work. What do you recommend, should we use `multiformatSerializePublicKey` instead?

**Comment by Parveshdhull** [comment]
> I think multiformatSerializePublicKey will also work.

I just tried `multiformatSerializePublicKey`, with legacy public keys and outBase as "z" (as https://github.com/status-im/status-mobile/blob/866b854ee0d05b926f7b88d02b3d4334eb7af8ff/src/status_im/constants.cljs#L398)

not sure if I am using it wrong, but it giving this error

image

**Comment by Parveshdhull** [comment]
As this PR is already tested, maybe we can explore uses of `multiformatSerializePublicKey` in a separate issue/PR. wdyt?

(btw, We are currently not using this function in client code so might be problem with function itself.)

**Comment by Parveshdhull** [comment]
It seems legacy keys is supported by this function
https://github.com/status-im/status-go/blob/02b822802c12f956c037ffdb23494f1e02f035d6/api/multiformat/utils.go#L112

but not sure why error

**Comment by Parveshdhull** [comment]
image

image


(If I am understanding correctly, it seems legacy keys are not supported)

**Comment by Parveshdhull** [comment]
So I think we need to modify `multiformatSerializePublicKey` to support legacy key, but that's different task. Wdyt @flexsurfer

**Comment by Parveshdhull** [comment]
image

Ok, roller coaster.  that seems like typo in comment
https://stackoverflow.com/questions/68841740/how-to-find-the-best-or-good-enough-base-point-g-on-ecc-curve

Anyway, for the time being I think we should just go with `serializeLegacyKey` as `multiformatSerializePublicKey` giving unsupported key type error
