### PR TITLE
[#18554] incorrect drawer for non community members

### LINKED ISSUE #18554: Incorrect drawer for non-members in community chat
### Steps:
1. Open a community where you are a member.
2. Send some messages.
3. Leave the community.
4. Open the channel of the current community.
5. Long-tap on your message.

### Actual result:
Community non-members see the following options in the drawer after the message is long-tapped:
- Ability to react.
- Edit message.
- Pin/Unpin.
- Delete for everyone.
image

### Expected result:
Community non-members should see the drawer as per the [design](https://www.figma.com/file/apCsJHT8J58JXbJD2igtbd/Context-Drawers-for-Mobile?type=design&node-id=1-3573&mode=design&t=iq6aSpK2V9nagAdj-0), excluding the ability to show reactions. Reference to design team reply [here](https://discord.com/channels/624634427930312714/842696205213368331/1197485033309622332).

### ENV:
Nightly [18 Jan 2024]

### LINKED ISSUE #21384: Scroll Down Button overlaps with the "join community to post" drawer in the community
# Bug Report

### Reproduction

1. Open the app.
2. Navigate to a community where you haven't joined.
3. Open the general chat (or any chat with a lot of messages).
4. Scroll to the bottom of the chat.

#### Expected behavior
The Scroll Down Button should be positioned above the drawer to avoid overlap.

#### Actual behavior
The Scroll Down Button overlaps with the "join community to post" drawer as in [design](https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=8137-561892&node-type=frame&t=PBIJevWQ2GUPGFg9-0)
Image
Image

### Additional Information

- Status version: nightly 4.10.24
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21384
fixes #18554

### Summary

This PR fixes the modal shown for non-members that sent a message in a community in a chat:

https://github.com/user-attachments/assets/63096804-9136-465a-8078-4e9d2faa8fe9

There are some missing options, such as "forward", but they haven't been implemented yet.

Addintionally fixes:
- #21384

iOS | Android
 

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
idk probably it's better to avoid formatting changes, it's much harder to review

**Review by flexsurfer — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by ulisesmac** [comment]
> idk probably it's better to avoid formatting changes, it's much harder to review

Sorry, I forgot to add a self review, I'll add it now

File: src/status_im/contexts/chat/messenger/messages/drawers/view.cljs [hunk 1]
```diff
@@ -99,76 +99,90 @@
...
+                                  (not= content-type constants/content-type-image)
+                                  (or community-member? (not community?)))
+        delete-for-me?       (and community-member?
+                                  (not (or deleted? deleted-for-me? bridge-message)))
+        delete-for-everyone? (and community-member?
+                                  (or (not deleted?)
+                                      outgoing
+                                      (and community? can-delete-message-for-everyone?)
+                                      (and group-chat group-admin?)
+                                      (not bridge-message)))]
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/messages/drawers/view.cljs]: Modified this logic to properly handle the shown options

File: src/status_im/contexts/chat/messenger/messages/drawers/view.cljs [hunk 2]
```diff
@@ -99,76 +99,90 @@
...
+    (cond-> []
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/messages/drawers/view.cljs:129]: changed:

```clojure
(concat
  (when something? [:a])
  (when foo? [:b])
  (when bar? [:c]))
```

to:

```clojure
(cond-> []
  something? (conj :a)
  foo?       (conj :b))
```

File: src/status_im/contexts/chat/messenger/messages/drawers/view.cljs [hunk 3]
```diff
@@ -209,21 +223,24 @@
...
+          {main-actions   :main
+           danger-actions :danger
+           admin-actions  :admin} (group-by :type actions)]
       [:<>
        ;; REACTIONS
-       (when (and (not= outgoing-status :sending) (not (or deleted? deleted-for-me?)))
+       (when (and (or community-member?)
+                  (not= outgoing-status :sending)
+                  (not (or deleted? deleted-for-me?)))
          [reactions {:chat-id chat-id :message-id message-id}])
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/messages/drawers/view.cljs]: Needed to limit the reactions to only community members

File: src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/style.cljs [hunk 4]
```diff
@@ -1,9 +1,13 @@
...
+            [status-im.contexts.shell.jump-to.constants :as shell.constants]))
 
-(def shell-button-container
+(defn shell-button-container
+  [able-to-send-messages?]
   {:z-index 1
-   :bottom  shell.constants/floating-shell-button-height})
+   :bottom  (+ (safe-area/get-bottom)
+               (when-not able-to-send-messages? 46)
+               shell.constants/floating-shell-button-height)})
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/style.cljs]: This is the second fix about the scroll to bottom button in chats

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/style.cljs]: This 46 is suspicious @ulisesmac, do you know if it can be calculated to be the sum of other known values?

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/style.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/style.cljs]: Thanks for noticing @ilmotta 

This is the height of the bottom drawer that says "requst to join". It's specified in figma. I can name it, do you think that'd be better?

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/messages/scroll_to_bottom/style.cljs]: It's a large and specific number @ulisesmac, that's why it caught my attention. Usually if it's 4, 8, 12, 20 we know they are just standard spacing values, but 46 I thought could be a magic number. Numbers that are tied to a specific component width/height are usually good candidates be defined as vars. One reason is that if designers change in Figma we won't be able to easily/safely adjust in the code.

**Comment by pavloburykh** [comment]
Hey @ulisesmac ! Is PR ready for QA? If yes could you please add `request manual qa` label please? Thanks.

**Comment by pavloburykh** [comment]
@ulisesmac thanks for the PR

### ISSUE 1 group/1-1 chats drawer missing options

**Actual result:** 

**1:1 chat**
own message drawer missing following options:
1. Reactions
2. Edit
3. Pin
4. Delete for me
5. Delete for everyone 

other's messages drawer is missing following options:
1. Reactions
2. Pin
3. Delete for me

**group chat**
own message drawer missing following options:
1. Reactions
2. Edit
3. Pin
4. Delete for me
5. Delete for everyone 

other's messages drawer is missing following options:
1. Reactions
2. Delete for me

photo_2024-11-08 17 57 25

**Expected result:** 

someone's message drawer:
photo_2024-11-08 17 58 10
own message drawer:
photo_2024-11-08 17 58 07

**Comment by ulisesmac** [comment]
@pavloburykh Thank you for testing it, I'll solve them, I forgot to check the implementation for 1:1 chats.

**Comment by ulisesmac** [comment]
@pavloburykh  fixed.

Could you please test it again?

BTW, I also fixed the order of the items showed, according to figma, we should display:
1. Reply
2. Edit

But we show:
1. Edit
2. Reply

So it's fixed too.

**Comment by pavloburykh** [comment]
@ulisesmac thanks for the PR. Issues are fixed, failed e2e are not PR related. Ready for merge.
