### PR TITLE
Fix & optimize shadows foundation

### LINKED ISSUE #16526: Foundation Shadows are not updated when theme changes
# Problem

The current implementation in namespace `quo2.foundations.shadows` has one bug and one important optimization technique that can be applied.

1. The vars `normal-scale` or `inverted-scale` and `inner-shadow` are not functions. This is a bug, because their values won't change when the application theme changes between dark & light modes.
2. The current implementation generates unnecessary GC pressure due to the constant re-creation of a large map and also rather expensive calls to `colors/alpha` (this function is not even memoized).

### Solution

There are not that many usages of `quo2.foundations.shadows`, so it's a good opportunity to rethink a little bit its API. A single function `get` could be exposed that would efficiently get (using `get-in`) the shadow values from a statically defined map of all possible shadows (dark/light modes & normal/inverted shadows). This would solve both of the problems previously described.

### Resources

[Figma Foundations > Shadows](https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=624-752&mode=design&t=EcFQjn8F4Bukxhn0-0)

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/16526

### Summary

In this PR:

- [x] Fix (implementation & usages): theme changes were not causing shadows to be reevaluated.
- [x] Optimization: define all possible shadow values at compile time. Good to reduce cycles on garbage collection since recreating the shadow map all the time is unnecessary and also to save cycles on computing colors since calls to `colors/alpha` are not memoized. You'll probably like this @ulisesmac 
- [x] API redesign: unify access to Design System shadows in a single function.

None of the actual shadow values changed, so I don't expect any visual changes.

#### API rationale

The `quo2.foundations.shadows` namespace reflects what's in the [Design System > Foundations > Shadows](https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=624-965&mode=design&t=CvIotdjbHKHcHjpd-0). Figma users see these shadows in other components as in the screenshot below, e.g. `Shadow/Normal/Light/03`. Notice the *weight* of the shadow is shown as a number (not the semantic name in Figma, e.g. `intense`, `strong`):

So to make things as easy as possible, I opted for exposing a single public function named `get`, which receives arguments in order of frequency of usage and which expects shadow weights as numbers so that devs don't need to mentally translate 1 to `:soft`, or 3 to `:intense`.

```clojure
;; Returns a map describing a shadow for the current theme, normal (not inverted) and weight 1.
(shadows/get 1)

;; Same as before, but returns a map for weight 2.
(shadows/get 2)

;; Shadow map for weight 4 and light theme.
(shadows/get 4 :light)

;; Shadow map for weight 1, dark theme and inverted.
(shadows/get 4 :dark true)
```

#### Review notes

This PR is not concerned with the actual values of the shadows, i.e. if they're correct. I assumed the original code values were correct.

### Platforms

- Android
- iOS

### Areas that may be impacted

None.

### Steps to test

Check the components using the foundations shadows, for example, `Quo Preview > notifications > toast`.

status: ready

### CODE REVIEW

File: src/quo2/foundations/shadows.cljs [hunk 1]
```diff
@@ -1,66 +1,74 @@
 (ns quo2.foundations.shadows
+  (:refer-clojure :exclude [get])
   (:require [quo2.foundations.colors :as colors]
-            [quo2.theme :as theme]))
+            [quo2.theme :as quo.theme]))
 
-(defn- get-inverted
-  [inverted? number]
-  (if inverted? (* -1 number) number))
+(def ^:private shadows
```
Comment (ulisesmac) [inline src/quo2/foundations/shadows.cljs:6]: Yes, I like it :love_you_gesture: :laughing:

File: src/quo2/foundations/shadows.cljs [hunk 2]
```diff
@@ -1,66 +1,74 @@
...
-                :shadow-offset  {:width  0
-                                 :height (get-inverted inverted? 16)}
-                :shadow-opacity 1
-                :shadow-radius  16
-                :elevation      13}}))
-
-(def normal-scale (get-scales false))
-
-(def inverted-scale (get-scales true))
+(defn get
```
Comment (ulisesmac) [inline src/quo2/foundations/shadows.cljs:60]: Looks better, I was thinking about a function called `get-shadows` instead of just `get`, because of shadowing the `get` fn in the `shadows` namespace, but since we are giving meaninful `:as` names while requiring, it would be worse (I prefer `shadows/get` more than `shadows/get-shadows`) .

I mean, I agree to this change unless a better name other than `get` is found

**Review by ulisesmac — APPROVED** [review]
Hey @ilmotta looks nice! :smile: 

I am just not sure about the API yet, 
for an exposed API, I try to avoid just passing boolean values, because when you read it is not clear.

When I read:
`(shadows/get 1 :light true)` or
`(shadows/get 1 :light false)`

I just think is not very clear.
What about giving another pair of keywords? `:inverted` and `:normal` and if not provided, default as `:normal`?
I think this will look better:

`(shadows/get 1 :light :inverted)` 
`(shadows/get 1 :light :normal)`, same as `(shadows/get 1 :light)`


and, also when Iread this piece of code:
```clojure
(merge 
  (shadows/get 1 theme)
  {:background-color   (colors/theme-colors colors/neutral-80-opa-70 colors/white-opa-70 theme)
   :flex-direction     :row
   :padding-vertical   8
   :padding-horizontal 12})
```
I was thinking is not clear enough :thinking: , but  I am not sure which one is better:
1. 
```clojure 
(shadows/get 2)
(shadows/get 3 :dark)
(shadows/get 3 :dark true)
```
2.
```clojure
(shadows/get :weight 2)
(shadows/get :weight 3 :theme :dark)
(shadows/get :weight 3 :theme :dark :inverted? true)
```
3.
```clojure
(shadows/get {:weight 2})
(shadows/get {:weight 3 :theme :dark})
(shadows/get {:weight    3
              :theme     :dark
              :inverted? true})
```

they are more clear as they are more verbose, :thinking:  wdyt? I know is hard

File: src/quo2/foundations/shadows.cljs (hunk 2 above)
Comment (ilmotta) [reply src/quo2/foundations/shadows.cljs:60]: I think it's quite idiomatic to use `get` or any other core function when using `:refer-clojure :exclude`. Since we're doing this, we're not shadowing the var really because it was removed from the env.

I'd be happy with other names, but I gotta say @ulisesmac, `shadows/get` is neat since that's all there is to this namespace. I almost went for `shadows/get-shadows`, but felt the repeated name was meh. In the codebase we have plenty of uses of `:refer-clojure` + `:exclude` so I guess it's all good 🤷🏼

**Comment by ilmotta** [comment]
> Hey @ilmotta looks nice! smile
> 
> I am just not sure about the API yet, for an exposed API, I try to avoid just passing boolean values, because when you read it is not clear.
> 
> When I read: `(shadows/get 1 :light true)` or `(shadows/get 1 :light false)`
> 
> I just think is not very clear. What about giving another pair of keywords? `:inverted` and `:normal` and if not provided, default as `:normal`? I think this will look better:
> 
> `(shadows/get 1 :light :inverted)` `(shadows/get 1 :light :normal)`, same as `(shadows/get 1 :light)`
> 
> they are more clear as they are more verbose, thinking wdyt? I know is hard

@ulisesmac, your reflections were my own as well. I don't like booleans in function calls too, unless it's pretty obvious, but I opted for this signature because I assumed most shadows are not inverted and the majority would be just `(shadows/get weight theme)`.

The signature I like the most is `(shadows/get 1 {:theme :dark :inverted? true})`, but I thought reviewers would say it's too verbose.

The suggestion `(shadows/get :weight 3 :theme :dark :inverted? true)` I personally dislike because it was sort of a hack in Clojure for many years to take var args to be able to eliminate the map brackets. Nowadays the newest Clojure version supports this style of code but I still find it bad. I remember I once shared an article from Stuart Sierra where he goes in more detail.

But I think we're very much aligned that explicitness is better in the long run than conciseness for APIs that are used that often.

I think the required argument should be part of the function arity, i.e. the weight shouldn't be optional, but the theme and inverted props are optional and could be passed as keys in the second (optional) argument.

I would be happy with `(shadows/get 1 {:theme :dark :inverted? true})`, wdyt?

**Comment by ulisesmac** [comment]
>  assumed most shadows are not inverted and the majority would be just (shadows/get weight theme)

I think in that case, it would be the same if we just change it by `:normal` and `:inverted` kws.

> I think the required argument should be part of the function arity, i.e. the weight shouldn't be optional, but the theme and inverted props are optional and could be passed as keys in the second (optional) argument.
> 
> I would be happy with (shadows/get 1 {:theme :dark :inverted? true}), wdyt?

I understand about the required argument, but I also think that `weight`, `theme` and `inverted` are all of them charactersitics of a shadow, so it seems a little strange to split them into multiple arguments :thinking: 

at this moment I'd prefer `(shadows/get 1 :light :inverted)`, just my opinion, is hard. Please feel free to pick whatever you think is better :+1: 

Btw, do you have the Stuart Sierra link about varargs?
thanks!

**Review by jo-mut — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]
Clean and neat 🚀 

This PR changes might help us fix #15434 with the help of inverted shadows.

**Comment by ilmotta** [comment]
> Clean and neat rocket
> 
> This PR changes might help us fix #15434 with the help of inverted shadows.

Good to hear @smohamedjavid

**Comment by ilmotta** [comment]
> at this moment I'd prefer `(shadows/get 1 :light :inverted)`, just my opinion, is hard. Please feel free to pick whatever you think is better +1

I get it. I like your suggestion too @ulisesmac. Yes, it's hard because it's an arbitrary decision in many ways. I'll adapt the code to be a 1-to-3-arity function. 1-arity is just the weight (as a number), 2-arity weight and theme and 3-arity the last argument for inversion should be a keyword, not a boolean (it's better indeed).

> Btw, do you have the Stuart Sierra link about varargs? thanks!

Sure https://stuartsierra.com/2015/06/01/clojure-donts-optional-arguments-with-varargs. Clojure 1.11 has support for kwargs (https://clojure.org/reference/special_forms#keyword-arguments) but I still think it was a questionable decision from the core team. I'm not alone as far as I read some comments...

------

Edit: Commit that changed the function signature https://github.com/status-im/status-mobile/pull/16553/commits/7bd07ac8ab74f98869770021beda847406d502ed

**Review by J-Son89 — APPROVED** [review]
