### PR TITLE
fix(wallet)_: Stop route calculation

### LINKED ISSUE #21043: Edit button is doulbed if try again button is tapped a few times
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Recover a user with available assets on at least two networks.
2. Navigate to the routes generation page.
3. Enter a value that is available on both networks (e.g., if the user has 1 ETH on Optimism and 1 ETH on Arbitrum, enter 1.5 ETH).
4. Tap the "Try Again" button multiple times.

### Actual Result:
The "Edit" button appears multiple times on the screen.

image

### Expected Result:
The "Edit" button should be displayed only once, regardless of how many times the "Try Again" button is tapped

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16610842/Status-debug-logs.zip)

### LINKED ISSUE #21249: 'Undefined not a function' error is constantly shown after transaction confirmation
Follow up for https://github.com/status-im/status-mobile/pull/21235

### Steps:
1. Go to the routes generation page
2. Build the route
3. Go to a transaction confirmation page
4. Go back to the wallet main page or confirm the transaction

### Actual result:
'Undefined not a function' error is constantly shown

https://github.com/user-attachments/assets/2fd26a54-8f4e-405f-8c78-9ce4d3079fb9

### Expected result:
no errors are shown

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16945706/Status-debug-logs.zip)

### LINKED ISSUE #21250: The сonfirmation keyboard auto-closes while entering the password
Follow up for https://github.com/status-im/status-mobile/pull/21235

Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Navigate to the transaction confirmation page.
2. Attempt to enter the password.

### Actual Result:
The confirmation keyboard constantly auto-closes, preventing the user from entering the password properly.

Pixel 7a, Android 13

https://github.com/user-attachments/assets/450a660b-9cec-4d32-92d7-02dccdb7c653

iPhone 11 Pro Max, IOS 17

https://github.com/user-attachments/assets/53b48b90-82fd-4948-a97b-cac95b5012fb

### Expected Result:
The keyboard should remain open, allowing the user to enter the password without interruptions

### Logs:
[logs (6).zip](https://github.com/user-attachments/files/16947601/logs.6.zip)

### LINKED ISSUE #21251: "eq() not a number: <0.01" Error shown after transaction confirmation
Follow up for https://github.com/status-im/status-mobile/pull/21235

### Steps:
1. Open account
2. Go to the routes generation page -> confirm a transaction

### Actual result:
The user is redirected to the activity page, where the error message "eq() not a number: <0.01" is displayed.

image

### Expected result:
The transaction should be confirmed without showing any error messages
### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (7).zip](https://github.com/user-attachments/files/16947924/logs.7.zip)

### LINKED ISSUE #21254: Wrong UI is shown after changing the token or account on the routes generation page
follow up for https://github.com/status-im/status-mobile/pull/21235

### Steps:
1. Go to routes generation page
2. Build the route
3. Tap the asset to open asset list
4. Change the asset or account via account switcher

### Actual result:
The previous route is still shown

https://github.com/user-attachments/assets/d2f942eb-58f4-4c6f-b41c-9b9ff2bdb9ca

### Expected result:
The previous route is not shown when asset is changed
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16655-177511&node-type=frame&t=oUNwiDs8Zn9W1JsO-0

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21249
fixes #21043
fixes #21251
fixes #21250
fixes #21254

### Summary

This PR 
- stops route calculation when the user
  - changes from account
  - changes the send (input) amount
  - goes back from the routes calculation page
  - after the transaction is successfully submitted
  - goes back from tx confirmation page for collectibles
- Prevents the keyboard being dismissed while entering the password on the transaction confirmation page
- Fixes multiple edit tiles/boxes added to receiver routes

### Review notes

Most of the regression bugs introduced in https://github.com/status-im/status-mobile/pull/21235 were due to a constant route signal, which was not stopped when the user moved away from the send flow. Additionally, The routes need to be stopped after a transaction is made, as we use the `createMultiTransaction` RPC which doesn't stop it (this is stopped in newer transaction RPCs/flows). 

### Testing notes

This PR fixes only the above-mentioned issues and if any bugs are discovered, please help us verify against the latest develop 🙏 . This PR aims to stabilize the send flows.

### Platforms

- Android
- iOS

##### Prerequisites: A profile (wallet account) with multiple assets (tokens/collectibles) across different networks

- Open Status
- Navigate to Wallet tab > Send
- Select a token and enter a value which is available in all three networks
- Verify the edit tile/box is shown only once
- Change the from account and verify the inputs and routes are cleaned up
- Change the token and verify the input and routes are cleaned up
- Go back from the routes calculation page or tx confirmation page and verify no errors are thrown
- Select any token/collectible to send 
- Verify the password can be entered without the keyboard being dismissed
- Verify the transaction is made successfully and no errors are thrown after that while the user is in the wallet tab 

status: ready

### CODE REVIEW

**Comment by clauxx** [comment]
@smohamedjavid I just noticed that your PR also fixes the issue I fixed [here](https://github.com/status-im/status-mobile/pull/21301), with the keyboard hiding on the tx confirmation screen. Just an FYI, since my PR is going through QA atm.

**Comment by smohamedjavid** [comment]
@clauxx - Thank you for the fix 🙏. Apologies for catching up late with the PR. 

It looks like we both approached it differently. The routes include the gas fee which can be changed and if the user is on tx confirmation screen for a while, the gas possibly could be updated (with a higher or lower fee). Since the desktop app doesn't have the tx confirmation screen/modal, the routes generation modal shows the updated one. That's why I added the active-screen check on the route generation page and let the tx confirmation show the updated gas fee. Let me know what you think.

**Comment by clauxx** [comment]
> @clauxx - Thank you for the fix 🙏. Apologies for catching up late with the PR.
> 
> It looks like we both approached it differently. The routes include the gas fee which can be changed and if the user is on tx confirmation screen for a while, the gas possibly could be updated (with a higher or lower fee). Since the desktop app doesn't have the tx confirmation screen/modal, the routes generation modal shows the updated one. That's why I added the active-screen check on the route generation page and let the tx confirmation show the updated gas fee. Let me know what you think.

Yeah it makes sense. Out of curiosity, since route generation is pretty taxing and makes quite a few JSON-RPC calls, wouldn't it be better to occasionally call `wallet_getSuggestedFees` to calculate the fees instead, since we don't need to generate routes after confirming on the input screen?

**Comment by smohamedjavid** [comment]
> Yeah it makes sense. Out of curiosity, since route generation is pretty taxing and makes quite a few JSON-RPC calls, wouldn't it be better to occasionally call `wallet_getSuggestedFees` to calculate the fees instead, since we don't need to generate routes after confirming on the input screen?

Honestly, that's how it was a couple of weeks ago. We fetch the routes once and that's it. Users can able to retry only if no routes are found. But, the recent changes in the routes RPC made it emit the routes signals with updated gas after certain blocks (could be sooner or later). This is good in one way that the user can see the updated gas fee or new best route (if any) but it's a bit heavy for a device like Mobile to process in a very short time. It doesn't necessarily need to emit a signal after certain blocks. It can be at a fixed interval of 10 seconds like how most crypto wallet apps do. Nevertheless, this is something that needs to be done in status-go. We can revisit it.

**Review by briansztamfater — APPROVED** [review]
Great work @smohamedjavid!

**Comment by clauxx** [comment]
@smohamedjavid makes sense! I'll close my PR then, but could you add the issue with the keyboard here as well?

**Review by alwx — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -556,7 +559,11 @@
               (assoc-in [:wallet :ui :send :just-completed-transaction?] true)
               (assoc-in [:wallet :transactions] transaction-details)
               (assoc-in [:wallet :ui :send :transaction-ids] transaction-ids))
-      :fx [[:dispatch
+      :fx [;; Remove wallet/stop-and-clean-suggested-routes event when we move to new transaction
+           ;; submission process as the routes as stopped by status-go
+           [:dispatch
+            [:wallet/stop-and-clean-suggested-routes]]
+           [:dispatch
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/send/events.cljs:562]: One thing came to mind when reading through the code: 
* What should we do when something fails?
  * For example, if the transaction fails, we may still be subscribing to suggested-routes because it seems we start listening for suggested-routes but only stop if the transaction succeeds.

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/events.cljs:562]: If the `createMultiTransaction` RPC throws an error, the user could see a toast message of the error. The user would still be on the tx confirmation page. We don't actually clean the data in app-db and allow the users to submit the transaction again if required. 

https://github.com/status-im/status-mobile/blob/f94be17b1133599aea32b9c6186448305833fb0e/src/status_im/contexts/wallet/send/events.cljs#L655-L663

If the user decides to go back (not performing the transaction), he/she will go back through the routes page, which will stop fetching the routes.

Comment (seanstrom) [reply src/status_im/contexts/wallet/send/events.cljs:562]: Ah nice that makes sense, thank you for clarifying 🙏 

Is it possible for the user to cancel their transaction, by navigating backwards or something, and if they can/do will they still be subscribing to the suggested routes? I ask because I had noticed in the wallet-send flow for tokens, that we start subscribing but I'm not sure if we have an event for unsubscribing when cancelling. Thoughts?

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/events.cljs:562]: There is no explicit cancel transaction in our UI which closes the transaction flow completely (like in the desktop).
If the user decides not to perform the transaction after reaching tx confirmation page, he/she needs to navigate back. We would stop the route generation (cancelling subscription to the routes).

Also in collectible tx flow the route generation screen is skipped and the user is taken to the tx confirmation page. That's why we have this check to stop the routes when the user navigates back from the tx confirmation page.

https://github.com/status-im/status-mobile/pull/21306/files#diff-089fb8d72eefa455e3dc6437b0bc11c3ca3cc0fb4063e20f129b09929aeae3a9R730-R732

Let me know If that answers your question.

Comment (seanstrom) [reply src/status_im/contexts/wallet/send/events.cljs:562]: Ah yes that makes sense! Nice stuff ✅

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @smohamedjavid !

Thanks for such a huge number fixed issues.
I've started to test all of them one by one and I see that https://github.com/status-im/status-mobile/issues/21249 is still present in PR build.

My device is Samsung A34 (Android 14.0)

https://github.com/user-attachments/assets/601015e4-c6a2-4c79-8231-2c60fd07a8ec

Logs: 
[Status-debug-logs navigation.zip](https://github.com/user-attachments/files/17128800/Status-debug-logs.navigation.zip)

**Comment by smohamedjavid** [comment]
Thanks for testing the PR @mariia-skrypnyk 🙏 

Could you help me check the issue? It should be fixed now. 

I can see from the video that the back navigation is happening so fast (tapping the back button faster), and the event to stop the route is in the queue (which is the root cause). I have updated the event to be dispatched immediately which will prevent these scenarios too. 👍

**Comment by mariia-skrypnyk** [comment]
Hey @smohamedjavid !

Thanks for analysing this issue.
Sad to say it still exist.

Issue starts from 0:35 sec

https://github.com/user-attachments/assets/f65ca080-6186-4adb-bd5d-218e49112ad1

I propose you to merge this PR as it contains a lot of necessary fixes that are amazing!
I will create a followup on this tricky leftover.

**Comment by smohamedjavid** [comment]
@mariia-skrypnyk - Thanks again for testing 🙏 

> I propose you to merge this PR as it contains a lot of necessary fixes that are amazing!
I will create a followup on this tricky leftover.

Sure, Let's merge this PR and I will check that issue as a follow-up 👍
