### PR TITLE
[#20562]  fix "not enough assets" case in  send screen

### LINKED ISSUE #20562: The "Not enough assets to pay gas fees" message is below 'fees' and 'Recipient gets' section
### Steps:
1. Recover user with available assets
2. Enter a max value into the routes generation page

### Actual result:
- The "Not enough assets to pay gas fees" message is below 'fees' and 'Recipient gets' section
- Try again button is shown
image

### Expected result:
image

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15329-122613&t=IkBLWZnxdyOqwZLn-0

### ENV:
Nightly 25 Jun 2024

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20562

### Summary

This PR fixes:
- The UI, the content wasn't matching figma 
- The events and view logic, since this case wasn't properly identified.

DEMOS:

1. Accounts with zero ETH and some EUROC

Before:

https://github.com/user-attachments/assets/180b7437-8dea-4e3a-8d8c-3d5ce36639c7

Now:

https://github.com/user-attachments/assets/6c582d41-1b00-4382-85dd-9d74697f4107

2. Another account with a regular balance, trying to send almost everything so that the user can't cover fees:

https://github.com/user-attachments/assets/cd956f10-88ad-4b32-a3ae-a83500d47b0c

### Testing notes
Please, test that this PR doesn't introduce a regression, the logic implemented is a bit complex and I'm not too familiar with the screen, so it'd be really helpful if you confirm twice.

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

- Wallet send input screen

status: ready

### Risk

A regression in any implemented case for the send input amount screen.

### CODE REVIEW

File: src/utils/money.cljs [hunk 1]
```diff
@@ -47,11 +47,10 @@
...
 (defn ->bignumbers
-  [n1 n2]
-  (when-let [bn1 (->bignumber n1)]
-    (when-let [bn2 (->bignumber n2)]
-      (when (and (bignumber? bn1) (bignumber? bn2))
-        [bn1 bn2]))))
+  [& numbers]
+  (let [transformed-numbers (map ->bignumber numbers)]
+    (when (every? bignumber? transformed-numbers)
+      transformed-numbers)))
```
Comment (ulisesmac) [inline src/utils/money.cljs:53]: Made this function more general, so it works as before but now we can pass any number of numbers, before only accepted 2

File: src/status_im/subs/wallet/wallet.cljs [hunk 2]
```diff
@@ -126,18 +126,23 @@
...
-                                     (filter #(not (contains? (set disabled-from-chain-ids)
-                                                              (:chain-id %))))
-                                     (map :chain-id)
-                                     set)]
+   (let [token                    (:token wallet-send)
+         disabled-from-chain-ids? (set disabled-from-chain-ids)
+         enabled-from-chain-ids   (->> networks
+                                       (map :chain-id)
+                                       (remove disabled-from-chain-ids?)
+                                       set)]
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/wallet.cljs:145]: This is just a code style refactor, it does the same.

with this refactor:
1. We avoid calling `set` on the same `disabled-from-chain-ids` on each iteration, now it's called once
2. `filter ` + `not` -> `remove`
3. use the advante of the data-type being a set, so we don't need to call `contains?`

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 3]
```diff
@@ -365,39 +371,44 @@
...
+                                 :on-press            (cond
+                                                        should-try-again?
+                                                        #(rf/dispatch [:wallet/start-get-suggested-routes
+                                                                       {:amount        amount-in-crypto
+                                                                        :updated-token token-by-symbol}])
+                                                        sending-to-unpreferred-networks?
+                                                        #(show-unpreferred-networks-alert on-confirm)
+                                                        :else
+                                                        #(on-confirm amount-in-crypto))
+                                 :customization-color current-color}
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:411]: Added the missing customization color for this button. The customization color is the one picked for the wallet account.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 4]
```diff
@@ -365,39 +371,44 @@
...
        [estimated-fees
         {:loading-routes? loading-routes?
          :fees            fee-formatted
          :amount          amount-text}])
-     (cond
-       show-no-routes?   [no-routes-found]
-       not-enough-asset? [not-enough-asset])
+     (when show-no-routes?
+       [no-routes-found])
      [quo/bottom-actions
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:391]: Changed the UI structure to match figma

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 5]
```diff
@@ -365,39 +371,44 @@
       {:token                                     token-by-symbol
        :send-amount-in-crypto                     amount-in-crypto
        :valid-input?                              valid-input?
-       :token-not-supported-in-receiver-networks? token-not-supported-in-receiver-networks?
+       :token-not-supported-in-receiver-networks? unsupported-token-in-receiver?
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:374]: reanamed the var
`token-not-supported-in-receiver-networks?` to  `unsupported-token-in-receiver?`

The first one is too large and it made oru code formatting uglier :(

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 6]
```diff
@@ -154,143 +174,129 @@
...
+                                                  (string/upper-case constants/mainnet-short-name)
+                                                  enabled-from-chain-ids])
+        not-enough-asset?                (insufficient-asset-amount?
+                                          {:enough-assets?        enough-assets?
+                                           :token-symbol          token-symbol
+                                           :owned-eth-token       owned-eth-token
+                                           :input-state           input-state
+                                           :no-routes-found?      no-routes-found?
+                                           :limit-exceeded?       limit-exceeded?
+                                           :sender-network-values sender-network-values})
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: Fixed this logic and moved it to a separate funciton, this namespace already has a lot of logic to handle. We must consider a refactor

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 7]
```diff
@@ -140,6 +140,26 @@
...
+        input-at-max-owned-amount? (money/equal-to
+                                    (controlled-input/value-bn input-state)
+                                    (controlled-input/upper-limit-bn input-state))
+        exceeded-input             (if eth-selected?
+                                     input-at-max-owned-amount?
+                                     zero-owned-eth?)]
+    (and (or no-routes-found? limit-exceeded?)
+         (seq sender-network-values)
+         (or exceeded-input (not enough-assets?)))))
+
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: These two functions extract a bit of the logic of the giant let mentioned below

File: src/status_im/contexts/wallet/send/events.cljs [hunk 8]
```diff
@@ -509,40 +521,43 @@
...
+           (log/error "failed to get suggested routes (async)"
+                      {:event :wallet/handle-suggested-routes
+                       :error error-message}))
+         {:fx [[:dispatch
+                (cond
+                  (and failure? swap?) [:wallet/swap-proposal-error error-message]
+                  failure?             [:wallet/suggested-routes-error error-message]
+                  swap?                [:wallet/swap-proposal-success (fix-routes data)]
+                  :else                [:wallet/suggested-routes-success (fix-routes data)
+                                        enough-assets?])]]})))))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:560]: Modified this event to make the logic a bit clearer, hoping now it's easier to understand since we don't have many conditions to check.

It's been also fixed to properly support the error code `WR-002` returned by the status-go when the user doesn't have enough assets

File: src/status_im/contexts/wallet/send/events.cljs [hunk 9]
```diff
@@ -509,40 +521,43 @@
...
+
+(def ^:private candidates-fix
+  (comp ->old-route-paths remove-invalid-bonder-fees-routes))
+
+(defn- fix-routes
+  [data]
+  (-> data
+      (data-store/rpc->suggested-routes)
+      (update :best best-routes-fix)
+      (update :candidates candidates-fix)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:537]: Just some constant functions that were extracted from the event below

File: src/status_im/contexts/wallet/send/events.cljs [hunk 10]
```diff
@@ -28,95 +28,108 @@
...
-              :type :negative
-              :text error-message}]]]})))
+   {:db (-> db
+            (update-in [:wallet :ui :send] dissoc :route)
+            (update-in [:wallet :ui :send :sender-network-values]
+                       send-utils/reset-loading-network-amounts-to-zero)
+            (update-in [:wallet :ui :send :receiver-network-values]
+                       send-utils/reset-loading-network-amounts-to-zero)
+            (assoc-in [:wallet :ui :send :loading-suggested-routes?] false)
+            (assoc-in [:wallet :ui :send :suggested-routes] {:best []}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:127]: This is a non-related refactor. I noticed we extracted the data, modified it, and the stored it in the same location. I refactored to use `update-in` and we get the same result with less code

File: src/status_im/contexts/wallet/send/events.cljs [hunk 11]
```diff
@@ -28,95 +28,108 @@
...
+             :suggested-routes          {:best []}
+             :enough-assets?            false)
+      (update :sender-network-values send-utils/reset-loading-network-amounts-to-zero)
+      (update :receiver-network-values send-utils/reset-loading-network-amounts-to-zero)))
+
+(rf/reg-event-fx
+ :wallet/suggested-routes-success
+ (fn [{:keys [db]} [suggested-routes-data enough-assets?]]
+   (if-not enough-assets?
+     {:db (update-in db [:wallet :ui :send] add-not-enough-assets-data (:best suggested-routes-data))}
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:45]: This is the call to add a specific db state when there're enough assets to pay gas fees.

We needed to implement a different state because previously this case was considered an error and the route wasn't returned, we need the route in order to extract the highlighted data here:

image

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 12]
```diff
@@ -140,6 +140,26 @@
...
+           sender-network-values enough-assets?]}]
+  (let [eth-selected?              (= token-symbol (string/upper-case constants/mainnet-short-name))
+        zero-owned-eth?            (money/equal-to (:total-balance owned-eth-token) 0)
+        input-at-max-owned-amount? (money/equal-to
+                                    (controlled-input/value-bn input-state)
+                                    (controlled-input/upper-limit-bn input-state))
+        exceeded-input             (if eth-selected?
+                                     input-at-max-owned-amount?
+                                     zero-owned-eth?)]
+    (and (or no-routes-found? limit-exceeded?)
```
Comment (vkjr) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:159]: I think we can join two `(or)` in one here without losing any logic

**Review by vkjr — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @ulisesmac !

Thanks for PR.

E2E caught issue that doesn't exist on develop.

**ISSUE 1: "Sending to unpreferred network" drawer appears in any transaction scenario**

Steps:

1. Login
2. Go to `Wallet` -> `Send`
3. Use different addresses types in Send to screen

- arb1:0xbce36f66a8cd99f1d6489cb9585146e3f3b893be

- 0xbce36f66a8cd99f1d6489cb9585146e3f3b893be
4. Type min amount and wait till routs build
5. Tap `Review send`

Actual result:

"Sending to unpreferred network" drawer appears if we try to send any transaction

https://github.com/user-attachments/assets/49e24e4a-f8dd-42d7-b545-a8e7cc93f0a5



Expected result:

"Sending to unpreferred network" drawer should appear if we try to send tokens using networks that are not preferabl for a receiver. How it works on develop: 

We send token to arb1:0xbce36f66a8cd99f1d6489cb9585146e3f3b893be and in Routs Generation screen edit To and choose not only Arbitrium but also Optimism for example. In this case drawer appears correctly.
If we do not change To Transaction Confirmation screens opens with no drawer:


https://github.com/user-attachments/assets/7de057ec-7f79-418b-ba40-dc6d078fb680

**Comment by ulisesmac** [comment]
@mariia-skrypnyk Thank you so much for testing it.

It was actually an issue introduced in this PR. Thanks for noticing!
It's been fixed, could you please re-test it?

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 12 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs:159]: Hi @vkjr 

Thanks for the comment!

The expression is:
```clojure
(and (or no-routes-found? limit-exceeded?)
     (seq sender-network-values)
     (or exceeded-input? (not enough-assets?)))
```

I understand you are suggesting to do:
```clojure
(and (or no-routes-found?
         limit-exceeded?
         exceeded-input?
         (not enough-assets?))
     (seq sender-network-values))
```

But it doesn't is logically equivalent, if we rename the vars as `v1`, `v2`, `v3` and `v4`, (to make them easier to understand), this:

```clojure
(and (or v1 v2)
     (or v3 v4))
```

is not the same as:
```clojure
;; With `or` unified:
(and (or v1 v2 v3 v4))

;; Same as:
(or v1 v2 v3 v4)
```

for instance:
```clojure
(let [v1   false
      v2   false
      v3   true
      v4   true
      ex-1 (and (or v1 v2)
                (or v3 v4))
      ex-2 (or v1 v2 v3 v4)]
  (= ex-1 ex-2))
  
;; => false
```

**Comment by mariia-skrypnyk** [comment]
Hey @ulisesmac!
Thanks for your fix.
Now it works as expected.

PR can be merged!
Thanks!
________________________________________
UPD: issue below is a feature:)

Regarding main PR fix I have only one issue 👇

Screenshot 2024-10-16 at 11 36 54

In PR there is `Add ETH` button instead of `Buy ETH` as on design [here](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15329-122613&t=IkBLWZnxdyOqwZLn-0).

Screenshot 2024-10-16 at 11 40 25

**Review by smohamedjavid — APPROVED** [review]
