### PR TITLE
fix: mark all notifications as read not work well

### LINKED ISSUE #18098: "Making notification as read" doesn't erase them in unread counters
Follow up on https://github.com/status-im/status-mobile/pull/18058

There is still an issue if instead of "Making notification as read" we are using "Mark All notification as read"

https://github.com/status-im/status-mobile/assets/4557972/c808bf37-d04f-47af-97bf-a7a393f688ad

It can be fixed separately, as there are some cases with several communities, unread CRs, etc.

What do you think?

_Originally posted by @churik in https://github.com/status-im/status-mobile/issues/18058#issuecomment-1842919906_

### PR DESCRIPTION
**Pull request by qfrank**
fixes #18098

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/status_im2/contexts/shell/activity_center/events.cljs [hunk 1]
```diff
@@ -156,14 +156,16 @@
...
-  [{:keys [db]}]
+(defn mark-all-as-read-success
+  [{:keys [db]} [{:keys [chats] :as _messenger-response}]]
   {:db (-> (reduce (fn [acc notification-type]
                      (assoc-in acc [:activity-center :unread-counts-by-type notification-type] 0))
                    db
                    types/all-supported)
-           (update :activity-center dissoc :mark-all-as-read-undoable-till))})
+           (update :activity-center dissoc :mark-all-as-read-undoable-till))
+   :fx (map #(vector :dispatch [:chats-list/load-chat-success %]) chats)})
```
Comment (smohamedjavid) [inline src/status_im2/contexts/shell/activity_center/events.cljs]: I guess we need to use `mapv`  as it will return a vector than `map` which returns a list.

Comment (qfrank) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: emm.. but i tested with `map` and it works well?  @smohamedjavid

Comment (smohamedjavid) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: Oh! I didn't know that it supports list too. 
I was under the impression that it supports vectors only. Apologies.

**Review by smohamedjavid — APPROVED** [review]
LGTM! Thanks for the fix @qfrank 🚀

File: src/status_im2/contexts/shell/activity_center/events.cljs (hunk 1 above)
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/events.cljs]: @qfrank, the best here is to avoid dispatching one `:chats-list/load-chat-success` for every chat instance because users will certainly accumulate many unread mention/reply notifications from different channels.

All `:chats-list/load-chat-success` does is merge a chat back into the app db. One potential solution is: extract the function body of `:chats-list/load-chat-success` and reuse it directly in `:activity-center.notifications/mark-all-as-read-success`, so that the app db is updated without any extra event in the chain.

This was probably the main reason `rf/merge` was devised, to help reuse code from different events and avoid dispatching too much. We can achieve the same with plain Clojure by reusing functions across events.

For this particular case it may not be a big deal because maybe re-frame will handle the events in batches just fine and the UI will have time to change. Though since the list of `chats` can grow unbounded and each `chat` map is big, this could likely hurt the UX for future users.

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/shell/activity_center/events.cljs (hunk 1 above)
Comment (qfrank) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: > One potential solution is: extract the function body of :chats-list/load-chat-success and reuse it directly in :activity-center.notifications/mark-all-as-read-success

Yes, i was also considering the performance issue when creating this PR 😅, but i was struggling what's the best place to put the reusable code. WDYT? @ilmotta

Comment (ilmotta) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: @qfrank The best place we have IMO for isolating the responsibility of dealing with transformations from RPC responses and performing any other kind of transformation for these domain entities is `status-im.data-store`. We often use namespaces there to rename keywords, but we can go much further. Code in that directory is 100% decoupled from re-frame, simple, immutable and testable functions for handling domain entities. It's in the old directory, we should move it someday/soon. Some guidelines could be helpful in the future too.

Moving domain code outside events is also helpful for unit testing them, since there's a strong _culture_ to not test events in the mobile team.

The other advantage of writing domain code outside event namespaces is that you won't get cyclic dependency errors as easily. Same goes for subscriptions, but at least for subs we kind of test them nowadays. I would love if re-frame was used only for what it does best. Who knows, re-frame could be replaced in the future in certain parts of the app, things evolve.

Edit: Just cc'ing a few more folks to give some awareness. @J-Son89 @cammellos @yqrashawn

Comment (J-Son89) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: Thanks @ilmotta - can we please start using the same approach but in status-im2 🙏

Comment (qfrank) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: As we already have `data-store.chats/<-rpc` and the rest we need is just updating `db` , so i didn't add extra changes into `data-store` , pls let know if you're happy with the latest change 🙂 @ilmotta

File: src/status_im2/contexts/shell/activity_center/events.cljs [hunk 2]
```diff
@@ -156,14 +156,20 @@
                         :on-error   [:activity-center/process-notification-failure nil
                                      :notification/mark-all-as-read]}]})))
 
-(rf/defn mark-all-as-read-success
-  {:events [:activity-center.notifications/mark-all-as-read-success]}
-  [{:keys [db]}]
+(defn merge-chats
+  [db chats]
+  (reduce (fn [db' {:keys [chat-id] :as chat}] (update-in db' [:chats chat-id] merge chat)) db chats))
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/events.cljs]: @qfrank, I would usually add a few line breaks for improved readability. Lisps can get confusing with many expressions on the same line because we need to use indentation to make sense of the tree structure.

```clojure
(defn merge-chats
  [db chats]
  (reduce (fn [db' {:keys [chat-id] :as chat}]
            (update-in db' [:chats chat-id] merge chat))
          db
          chats))
```

But we can achieve the same more succinctly I think:

```clojure
(defn merge-chats-2
  [db chats]
  (update db :chats merge (utils.collection/index-by :chat-id chats)))
```

This gives the same results, which could be a unit test ;)

```clojure
(let [db    {:chats {"0x1" {:chat-id "0x1"}
                     "0x2" {:chat-id "0x2"}
                     "0x3" {:chat-id "0x3"}}}
      chats [{:chat-id "0x1" :clock 11}
             {:chat-id "0x3" :clock 33}]]
  (= (merge-chats db chats)
     (merge-chats-2 db chats)))
```

File: src/status_im2/contexts/shell/activity_center/events.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/contexts/shell/activity_center/events.cljs]: Neat @qfrank, thanks for working on this improvement. I left a separate comment as another suggestion if you like it.

**Comment by VolodLytvynenko** [comment]
Hey @qfrank could you please rebase current and the status go PR https://github.com/status-im/status-go/tree/chore/return_chats_after_mark_notifications_read?

**Comment by qfrank** [comment]
> Hey @qfrank could you please rebase current and the status go PR https://github.com/status-im/status-go/tree/chore/return_chats_after_mark_notifications_read?

Sorry for the delay, just back, rebased 🙂 @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> > Hey @qfrank could you please rebase current and the status go PR https://github.com/status-im/status-go/tree/chore/return_chats_after_mark_notifications_read?
> 
> Sorry for the delay, just back, rebased 🙂 @VolodLytvynenko

Hey @qfrank apologies for the delay, this time from my side.  I've just returned from vacation. Could you please rebase the Status go and the current PR once more?

**Comment by qfrank** [comment]
> > > Hey @qfrank could you please rebase current and the status go PR https://github.com/status-im/status-go/tree/chore/return_chats_after_mark_notifications_read?
> > 
> > 
> > Sorry for the delay, just back, rebased 🙂 @VolodLytvynenko
> 
> Hey @qfrank apologies for the delay, this time from my side. I've just returned from vacation. Could you please rebase the Status go and the current PR once more?

done 🙂 @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
@qfrank Thank you for PR. Ready to be merged
