### PR TITLE
Fix for multiple header spacings on onboarding screens

### LINKED ISSUE #15628: Onboarding screens' header elements overlay status bar (Android)
Followup of https://github.com/status-im/status-mobile/pull/15467 cc @flexsurfer 

**Steps:**

1. Install Status App
2. Go through onboarding screens
3. Pay attention header elements (back button) overlay status bar 

photo_2023-03-29 17 56 31

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
fixes https://github.com/status-im/status-mobile/issues/15628

⚠️ I didn't focus on "Profile password" screen because it's terribly structured and because it has a scroll view that doesn't work properly — it looks more like a prototype at this stage. This screen should be re-made the same way as "Create profile" screen — with all the appropriate spacings and listeners.

#### Platforms

- Android
- iOS

##### Functional

- onboarding

status: ready

### CODE REVIEW

**Comment by alwx** [comment]
Still waiting for this one to be reviewed :)

File: src/status_im2/contexts/onboarding/create_profile/view.cljs [hunk 1]
```diff
@@ -95,13 +86,13 @@
                 (oops/ocall will-hide-listener "remove"))))
           [])
          [rn/view {:style style/page-container}
+          [navigation-bar/navigation-bar {:top navigation-bar-top}]
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/create_profile/view.cljs:89]: Curious, did you check with design team that this is expected scroll behaviour?

**Review by J-Son89 — APPROVED** [review]
Nice one @alwx 😀

File: src/status_im2/contexts/onboarding/create_password/view.cljs [hunk 2]
```diff
@@ -189,11 +190,18 @@
...
     (fn []
-      [:<>
-       [background/view true]
-       [rn/scroll-view
-        {:ref                     #(reset! scroll-view-ref %)
-         :style                   style/overlay
-         :content-container-style style/content-style}
-        [navigation-bar/navigation-bar {:on-press-info #(js/alert "Info pressed")}]
-        [password-form {:scroll-to-end-fn scroll-to-end-fn}]]])))
+      [safe-area/consumer
```
Comment (ulisesmac) [inline src/status_im2/contexts/onboarding/create_password/view.cljs]: Hi @alwx 

I suggest not to create a reagent component on the fly in an inline function:

```clojure
[safe-area/consumer
  (fn [props] ;; <- this component
   [ ;; view code
    ])]
```

This could lead us to a performance downgrade and problems while using hooks (https://github.com/status-im/status-mobile/issues/15552#issue-1649290578), and I would also suggest to use the pattern I commented there.

Another option, probably more clean (I'm not sure yet) would be to use the `useSafeAreaInsets` hook since I think you only need that `top` value, so probly using a hook requires less refactoring.

**Comment by qoqobolo** [comment]
Thanks @alwx, PR can be merged.
