### PR TITLE
Fix: missing community logo in Activity Center

### LINKED ISSUE #17157: No community avatar in notifications in activity center
# Bug Report

## Problem 

Community avatar is not displayed in notifications in AC anymore. For example, when you, as an admin, receive a membership request, or when your membership request is approved by admin. 

#### Expected behavior
Can see community photo in notifications in AC

#### Actual behavior

Screenshot 2023-08-31 at 14 57 35

### Reproduction

1. UserA: create a `require approval` community on mobile or desktop, add a thumbnail image, share the community with UserB
2. UserB: send a membership request to the community
3. UserA: check the activity center and the community avatar in the received notification; approve the request
4. UserB: check the notification in AC

### Additional Information

- Status version: nightly 31/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/17157

### Summary

The bug was caused, again, by the fact that the component `react-native/image` source was a string and it was not wrapped inside the map `{:uri "..."}`. The bug was introduced recently by commit 255a3b917265d381fed57e26422277b4cc8772e4

I decided to change `react-native.image` for good, similarly to what we do in `react-native/fast-image` so we can prevent this type of bug in the future.

https://github.com/status-im/status-mobile/blob/ebd38295c6e5715a0ee04217b248ac69f9ddceab/src/react_native/fast_image.cljs#L21

#### Platforms

- Android
- iOS

### Steps to test

_(described in the original issue)_

status: ready

### CODE REVIEW

**Review by FFFra — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]
Nice 👍

**Review by BalogunofAfrica — APPROVED** [review]
Looks good to me

File: src/react_native/core.cljs [hunk 1]
```diff
@@ -16,7 +16,17 @@
...
-(def image (reagent/adapt-react-class (.-Image ^js react-native)))
+
+(def ^:private image-native
+  (reagent/adapt-react-class (.-Image ^js react-native)))
+
+(defn image
+  [{:keys [source] :as props}]
+  [image-native
+   (if (string? source)
+     (assoc props :source {:uri source})
```
Comment (J-Son89) [inline src/react_native/core.cljs:27]: 🧠

**Review by J-Son89 — APPROVED** [review]

**Comment by qoqobolo** [comment]
@ilmotta thanks for the fix, works as expected now!
