### PR TITLE
[#15518]Show disclaimer during password creation

### LINKED ISSUE #15518: Always show the "I understand my password can't be recovered" disclaimer on password creation screen
# Bug Report

Followup of https://github.com/status-im/status-mobile/pull/15405

## Problem 

Currently, according to [design](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2241-251839&t=rSX39O9F5DHXFiNF-4), we only show the disclaimer `I understand my password can't be recovered` when the user sets the cursor to the second input field (`Repeat password`) .

But if the user after that presses on the first input field (`Type password`) again for some reason, for example, if they add more characters to the password in the second field first and then back to the first and close the keyboard, then the disclaimer, that is needed to complete this step, won't be shown on the screen, which may be a bit confusing. 

https://user-images.githubusercontent.com/67952253/228238711-138aedca-ddc2-44bd-b44e-309d24b9caf2.mp4

#### Expected behavior

We should consider the option to show the disclaimer on the screen always from the beginning / always when both password fields are filled

#### Actual behavior

The disclaimer is only shown after focusing on the second field

### Reproduction

1. Start creating a new account
2. Enter a password
3. Repeat it
4. Then focus back on the `Type password` field and try to complete the password creation flow

### Additional Information

- Status version: nightly 28/03
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by SilentCruzer**
fixes #15518

### Summary

Modified the passwrod creation screen to show the  disclaimer on the screen always from the beginning / always when both password fields are filled.

https://user-images.githubusercontent.com/73246484/231986107-b9cf102d-4df3-4534-94a8-50c64a233d61.mp4

### Review notes
- In the code, you can notice that the I moved the disclaimer part above the password validation, I moved it because I wanted to display the disclaimer above the validation text when the password was focused.
- Also another bug to be noted (apart from the current issue), from the above video you can see that the topbar is being overlapped by the status bar by a little bit. I can include that fix in this PR if its okay.

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
Onboarding

### Steps to test

- Open Status in a Fresh install
- Press I'm new to status -> Generate keys -> Continue
- When the page is open, we can see the disclaimer immediately in the bottom and it will remain there through out the process.

status: ready

### CODE REVIEW

**Review by alwx — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by Parveshdhull** [comment]
@SilentCruzer Thank you very much for PR.

Linting is broken, please run `make lint` for see issue and `make lint-fix` for fixing it.

**Comment by Parveshdhull** [comment]
> Also another bug to be noted (apart from the current issue), from the above video you can see that the topbar is being overlapped by the status bar by a little bit. I can include that fix in this PR if its okay.

This issue is already tracked in https://github.com/status-im/status-mobile/issues/15628 and will be fixed in https://github.com/status-im/status-mobile/pull/15640

**Comment by SilentCruzer** [comment]
> @SilentCruzer Thank you very much for PR.
> 
> Linting is broken, please run `make lint` for see issue and `make lint-fix` for fixing it.

Thanks, I was actually wondering on how to use the lint test. I have resolved the issue now.

**Review by briansztamfater — APPROVED** [review]

File: src/status_im2/contexts/onboarding/create_password/view.cljs [hunk 1]
```diff
@@ -162,19 +162,17 @@
...
+            {:on-change #(reset! accepts-disclaimer? %)
+             :checked?  @accepts-disclaimer?}
+            (i18n/label :t/password-creation-disclaimer)]]
+
           (when (= @focused-input :password)
             [help
              {:validations       validations
               :password-strength password-strength}])
 
-          (when (= @focused-input :repeat-password)
```
Comment (ulisesmac) [inline src/status_im2/contexts/onboarding/create_password/view.cljs:170]: Hi @SilentCruzer 

Just a small comment:

This code was thought to be more general and sets a keyword id according to the input focused (those keywords are be `:password` and `:repeat-password`), but since now we don't care about the `:repeat-password` value, we could simplify that atom and logic. The callback responsible of setting this id in the atom is `on-input-focus`.

Would you mind making that simplification, please?

**Review by ulisesmac — APPROVED** [review]
Hi @SilentCruzer !

Thank you very much for your PR! :smile: 
I added a small comment

File: src/status_im2/contexts/onboarding/create_password/view.cljs [hunk 2]
```diff
@@ -146,9 +146,9 @@
             :passwords-match?          same-passwords?
             :empty-password?           empty-password?
             :show-password-validation? @show-password-validation?
-            :on-input-focus            (fn [input-id]
+            :on-input-focus            (fn []
                                          (scroll-to-end-fn)
-                                         (reset! focused-input input-id))
+                                         (reset! focused-input :password))
```
Comment (SilentCruzer) [inline src/status_im2/contexts/onboarding/create_password/view.cljs:151]: @ulisesmac , As you mentioned since we don't need to `:repeat-password`, i have removed the parameter in `:on-input-focused` and defaulted the `input-id` to `:password`.

Is this change okay?

**Comment by churik** [comment]
Thank you for amazing work, @SilentCruzer !
Ready to be merged.

File: src/status_im2/contexts/onboarding/create_password/view.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im2/contexts/onboarding/create_password/view.cljs:151]: Yes, it's ok! thank you! :+1:
