### PR TITLE
[#21557] feat: show from account page in swap flow

### LINKED ISSUE #21557: "From" page with list of accounts not displayed when tapping swap on wallet main page with multiple accounts
### Steps to Reproduce:
1. Ensure user has at least 2 accounts set up.
2. Go to the wallet main page.
3. Tap on "Swap" for any asset.

### Actual Result:
- The "From" page does not display, preventing the user from selecting the account or asset to swap from.

### Expected Result:
- **Scenario 1:** If the user has two accounts (e.g., Account 1 and Account 2) but the selected token exists only in one of the accounts, the FROM page **should not be** displayed.
- **Scenario 2:** If the user selects a token present in both accounts, the FROM page **should be** displayed.
- **Scenario 3:** If the user has more than two accounts, and the selected token is available in some (more than one) but not all accounts, the FROM page **should** display. Accounts without the selected token should still be listed but appear disabled, as shown in the [design reference](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1691-48512&node-type=instance&m=dev).

### NOTE:
Here is a [list of test cases](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0) related to the current feature 

### OS:
iOS, Android

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21557

### Summary

The ["From" page](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1691-48512&node-type=instance&m=dev) should appear, allowing the user to choose the account for the swap.

#### Areas that maybe impacted

- Swap flow when user has multiple account

### Steps to test

1. Ensure user has at least 2 accounts set up.
2. Go to the wallet main page.
3. Tap on "Swap" for any asset.

### Result

https://github.com/user-attachments/assets/adc21d9d-3140-41ca-bfa8-51152b19e961

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/swap/from/view.cljs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    [utils.money :as money]
+    [utils.re-frame :as rf]))
+
+(defn- on-account-press
+  [account]
+  (rf/dispatch [:wallet.swap/start-from-account account]))
+
+(defn- render-fn
+  [item _ _]
+  (let [has-balance (money/greater-than (:asset-pay-balance item) (money/bignumber "0"))]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/swap/from/view.cljs]:
```suggestion
  (let [has-balance? (money/greater-than (:asset-pay-balance item) 0))]
```

File: src/status_im/subs/wallet/swap.cljs [hunk 2]
```diff
@@ -302,3 +302,24 @@
...
+ :<- [:wallet/swap-asset-to-pay]
+ (fn [[accounts asset-to-pay]]
+   (let [token-symbol (:symbol asset-to-pay)]
+     (map
+      (fn [account]
+        (let [tokens            (:tokens account)
+              filtered-tokens   (filter #(= (:symbol %) token-symbol) tokens)
+              asset-pay-balance (utils/calculate-total-token-balance filtered-tokens)
+              formatted-address @(rf/subscribe [:wallet/account-address (:address account)
+                                                (:network-preferences-names account)])]
```
Comment (smohamedjavid) [inline src/status_im/subs/wallet/swap.cljs]: I'm not sure this is right to do. Maybe we can extract that operation to separate function in network-utils ns and use it as it doesn't depend on any other subs/data. That's a pure utility method.

cc @ulisesmac

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 3]
```diff
@@ -549,3 +549,7 @@
     (:less-than-three-minutes constants/wallet-transaction-estimation) "1-3"
     (:less-than-five-minutes constants/wallet-transaction-estimation)  "3-5"
     ">5"))
+
+(defn multi-account?
```
Comment (vkjr) [inline src/status_im/contexts/wallet/common/utils.cljs]: This function is quite confusing. It is not clear what structure should be passed to it. 
Also it is very basic and used only in one place, so I'd suggest to not introduce it at all

**Review by vkjr — APPROVED** [review]

File: src/status_im/contexts/wallet/common/utils.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/common/utils.cljs]: done

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 4]
```diff
@@ -527,3 +532,15 @@
              [:dispatch [:wallet/navigate-to-account-within-stack address]])
            [:dispatch [:wallet/fetch-activities-for-current-account]]
            [:dispatch [:wallet/select-account-tab :activity]]]})))
+
+(rf/reg-event-fx :wallet.swap/start-from-account
+ (fn [{:keys [db]} [account]]
+   (let [asset-to-pay     (get-in db [:wallet :ui :swap :asset-to-pay])
+         asset-to-receive (get-in db [:wallet :ui :swap :asset-to-receive])]
+     {:fx [[:dispatch [:navigate-back]]
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/swap/events.cljs]: Can we use `:dismiss-modal :screen/wallet.swap-from` event? I think it would make the code more understandable.

File: src/status_im/navigation/screens.cljs [hunk 5]
```diff
@@ -635,6 +636,12 @@
                 :insets                 {:top? true}}
     :component wallet-swap-select-asset-to-pay/view}
 
+   {:name      :screen/wallet.swap-from
```
Comment (briansztamfater) [inline src/status_im/navigation/screens.cljs]: I would suggest a more descriptive name, for example `:screen/wallet.swap-select-account` (and update the namespace accordingly)

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 6]
```diff
@@ -14,18 +14,19 @@
...
-         account                (swap-utils/wallet-account wallet)
+         account                (or from-account (swap-utils/wallet-account wallet))
          asset-to-pay           (if (get-in data [:asset-to-pay :networks])
                                   (:asset-to-pay data)
                                   (swap-utils/select-asset-to-pay-by-symbol
                                    {:wallet                 wallet
                                     :account                account
                                     :test-networks-enabled? test-networks-enabled?
                                     :token-symbol           (get-in data [:asset-to-pay :symbol])}))
+         multi-account?         (> (count (:accounts wallet)) 0)
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/swap/events.cljs]: Perhaps you meant to check if it is greater than 1 instead of 0?

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 7]
```diff
@@ -35,34 +36,38 @@
...
-                             :on-select-network (fn [network]
-                                                  (rf/dispatch [:hide-bottom-sheet])
-                                                  (rf/dispatch
-                                                   [:wallet.swap/start
-                                                    {:asset-to-pay     asset-to-pay
-                                                     :asset-to-receive asset-to-receive
-                                                     :network          network
-                                                     :open-new-screen? open-new-screen?}]))}])}]]])})))
+      :fx (if (and multi-account? (= view-id :wallet-stack) (not from-account))
+            [[:dispatch [:open-modal :screen/wallet.swap-from]]]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/swap/events.cljs]: Quick question: From reading the code, i can understand that this opens the account selection screen (from) screen if the user has more than one account (any type). This is different in send/bridge flow. Only if the asset is available on multiple accounts, that's when we open the from screen with list of accounts that has that asset.

cc @briansztamfater

File: src/status_im/contexts/wallet/swap/events.cljs (hunk 6 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: yeah sorry just messed up after changes

File: src/status_im/subs/wallet/swap.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/subs/wallet/swap.cljs]: at first i wanted to do that but i saw this pattern in other area so i though nothing wrong to use subscribe like this, if it has any issue let me know i will extract the content to a utils

File: src/status_im/contexts/wallet/swap/events.cljs (hunk 7 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/swap/events.cljs]: Yes, we should open this modal only if the selected asset is in multiple accounts _and_ has any balance on more than one account.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: yes it's different according to QA's doc [list of test cases](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0)

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: according to design we list all accounts but show account with zero balance with disabled state

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: here is design link @smohamedjavid @briansztamfater https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1691-48506&m=dev

Comment (briansztamfater) [reply src/status_im/contexts/wallet/swap/events.cljs]: I see, but seems that the test cases differs from the designs. We should double check that cc @pavloburykh @churik

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/swap/events.cljs]: Oh, then we are doing it wrong in Send/Bridge flow i guess.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: yeah maybe just condition here has a wrong text, otherwise we have account with zero balance in design.

Comment (briansztamfater) [reply src/status_im/contexts/wallet/swap/events.cljs]: In the designs three accounts are shown, which two of them have balance, and that's why the third one is disabled. But (from my understanding) if the user has two (or more) accounts and only balance for the selected asset in only one of them, the account selection page should not be shown.

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thank you for your PR!
Can I start testing?

File: src/status_im/subs/wallet/swap.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/subs/wallet/swap.cljs]: @smohamedjavid This pattern is not the best. We aren't supposed to use `subscribe` here, we could if this were a signal function, but it's not the case.

I agree with @smohamedjavid, seems this could be a utility function, if that is too hard, then we can refactor it to be used as a signal function.

File: src/status_im/contexts/wallet/swap/from/view.cljs (hunk 1 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/swap/from/view.cljs]: we also have `(money/above-zero?)` function, will be shorter

**Comment by mohsen-ghafouri** [comment]
Hey @Horupa-Olena yes please, thanks

File: src/status_im/contexts/wallet/swap/events.cljs (hunk 7 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: I guess better to check linked issue description,  https://github.com/status-im/status-mobile/issues/21557#issue-2633022911

also list of [list of test cases](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0)

I implemented it accordingly

File: src/status_im/subs/wallet/swap.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/subs/wallet/swap.cljs]: thank you, will apply changes

File: src/status_im/contexts/wallet/swap/events.cljs (hunk 7 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/swap/events.cljs]: Implementation looks correct based in the test cases document, I am just wondering if test cases are correctly set, as design implies that the From page should be shown only if asset exist in multiple accounts, but on the document there are some test cases that expect the From page to be always shown if the user has more than one account, no matter if the asset exist on more than one account. I think we should double check test cases. cc @Horupa-Olena

File: src/status_im/subs/wallet/swap.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/subs/wallet/swap.cljs]: done

File: src/status_im/navigation/screens.cljs (hunk 5 above)
Comment (mohsen-ghafouri) [reply src/status_im/navigation/screens.cljs]: done

File: src/status_im/contexts/wallet/swap/events.cljs (hunk 4 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: done

**Review by briansztamfater — APPROVED** [review]
Code-wise, it looks good to me!

@Horupa-Olena @pavloburykh, could you check this comment and verify that we are not misrepresenting the expected behavior? Thanks 🙏  https://github.com/status-im/status-mobile/pull/21611#discussion_r1848751349

**Comment by pavloburykh** [comment]
> Code-wise, it looks good to me!
> 
> @Horupa-Olena @pavloburykh, could you check this comment and verify that we are not misrepresenting the expected behavior? Thanks 🙏 [#21611 (comment)](https://github.com/status-im/status-mobile/pull/21611#discussion_r1848751349)

@briansztamfater @mohsen-ghafouri Thank you, guys!
From my perspective, the expected behavior seems partially incorrect in both the issue [description](https://github.com/status-im/status-mobile/issues/21557#issue-2633022911) and the referenced [test cases](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0).

Here’s what I believe should be the correct behavior:

The FROM page should only appear if more than one account holds the token selected for the swap.
- **Scenario 1:** If the user has two accounts (e.g., Account 1 and Account 2) but the selected token exists only in one of the accounts, the FROM page **should not be** displayed.
- **Scenario 2:** If the user selects a token present in both accounts, the FROM page **should be** displayed.
- **Scenario 3:** If the user has more than two accounts, and the selected token is available in some (more than one) but not all accounts, the FROM page **should** display. Accounts without the selected token should still be listed but appear disabled, as shown in the [design reference](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1691-48512&node-type=instance&m=dev).

Let me know your thoughts or if we need further alignment! cc @xAlisher

**Comment by xAlisher** [comment]
Looks good to me

File: src/status_im/contexts/wallet/swap/events.cljs (hunk 7 above)
Comment (Horupa-Olena) [reply src/status_im/contexts/wallet/swap/events.cljs]: @briansztamfater Thanks for your comments! I’ll review these cases one more time.

**Comment by pavloburykh** [comment]
> Looks good to me

thank you @xAlisher

**Comment by Horupa-Olena** [comment]
> > Code-wise, it looks good to me!
> > @Horupa-Olena @pavloburykh, could you check this comment and verify that we are not misrepresenting the expected behavior? Thanks 🙏 [#21611 (comment)](https://github.com/status-im/status-mobile/pull/21611#discussion_r1848751349)
> 
> @briansztamfater @mohsen-ghafouri Thank you, guys! From my perspective, the expected behavior seems partially incorrect in both the issue [description](https://github.com/status-im/status-mobile/issues/21557#issue-2633022911) and the referenced [test cases](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0).
> 
> Here’s what I believe should be the correct behavior:
> 
> The FROM page should only appear if more than one account holds the token selected for the swap.
> 
> * **Scenario 1:** If the user has two accounts (e.g., Account 1 and Account 2) but the selected token exists only in one of the accounts, the FROM page **should not be** displayed.
> * **Scenario 2:** If the user selects a token present in both accounts, the FROM page **should be** displayed.
> * **Scenario 3:** If the user has more than two accounts, and the selected token is available in some but not all accounts, the FROM page **should** display. Accounts without the selected token should still be listed but appear disabled, as shown in the [design reference](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1691-48512&node-type=instance&m=dev).
> 
> Let me know your thoughts or if we need further alignment! cc @xAlisher

@mohsen-ghafouri @briansztamfater I agree with this behavior. If it’s implemented this way, I will start testing. 
What do you think?

**Comment by mohsen-ghafouri** [comment]
Thank you @pavloburykh , could you please correct the description of linked issue and also test case document? as it will be reference for dev and QA. 

@Horupa-Olena I need to apply some changes to cover Scenario 1, will let you know once it's ready for review.

**Comment by pavloburykh** [comment]
> Thank you @pavloburykh , could you please correct the description of linked issue and also test case document? as it will be reference for dev and QA.

@mohsen-ghafouri I have corrected issue description. Regarding the [document](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0) , @VolodLytvynenko could you please correct it, as I have View only permissions.

**Comment by VolodLytvynenko** [comment]
> > Thank you @pavloburykh , could you please correct the description of linked issue and also test case document? as it will be reference for dev and QA.
> 
> @mohsen-ghafouri I have corrected issue description. Regarding the [document](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0) , @VolodLytvynenko could you please correct it, as I have View only permissions.

I just corrected the [table](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0) thanx

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Do I understand correctly that this PR includes changes only to the swap flow? The send and bridge flows remain unchanged for now.

**Comment by mohsen-ghafouri** [comment]
Yes @Horupa-Olena it's only related to swap flow.

**Review by smohamedjavid — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
Hey @briansztamfater, Could you please check the last commit? thanks

Also here is the result 

https://github.com/user-attachments/assets/0603e78a-a051-4553-aed9-099905a0d252

**Review by briansztamfater — APPROVED** [review]
Thanks for the modifications @mohsen-ghafouri 🚀

**Comment by mohsen-ghafouri** [comment]
Hey @Horupa-Olena, it's ready for test. thanks in advance

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your work!

Unfortunately, I’m unable to trigger the From page.

I restored a profile using a seed phrase that had two accounts with assets.
I also tried to trigger the From page on a profile with two empty accounts and two imported accounts with funds. Both attempts were unsuccessful on Android and iOS.

Could you please take a look and check what might be wrong? Let me know if logs are needed.

**Comment by mohsen-ghafouri** [comment]
Hey @Horupa-Olena, a video of test would be helpful, as you can see in my last comment the result with my account is like this https://github.com/status-im/status-mobile/pull/21611#issuecomment-2489299464

swap with account that has balance worked fine for my accounts

**Comment by mohsen-ghafouri** [comment]
Just retest it with latest changes, the result is the same, you should have an asset available at least in 2 accounts to see the "From" page in swap flow 
CC @Horupa-Olena 

scenarios https://github.com/status-im/status-mobile/pull/21611#issuecomment-2487935537

https://github.com/user-attachments/assets/9e72bda5-f95a-42d7-833d-442ea516d3fc

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Sorry, I rushed to switch to another task and seem to have sent the comment without waiting for the video to upload.
Here’s the video.

https://github.com/user-attachments/assets/7ec75397-3823-43cc-b1e2-81027fa94570

**Comment by Horupa-Olena** [comment]
> Just retest it with latest changes, the result is the same, you should have an asset available at least in 2 accounts to see the "From" page in swap flow CC @Horupa-Olena
> 
> scenarios [#21611 (comment)](https://github.com/status-im/status-mobile/pull/21611#issuecomment-2487935537)
> 
>  Simulator.Screen.Recording.-.iPhone.13.-.2024-11-21.at.18.51.09.mp4

@mohsen-ghafouri I retest on last build. The same result.

**ISSUE 1:** From page not appears for multichain account

**Step**
1. Restore user profile by seed phrase
2. Turn off test network -> Log out
3. Log in
4. Add second acc in wallet
5. Longtap on ETH on owerview in wallet

**Expected results:**
Form page appears and allow chose account for swap

**Actual results:**
Form page not appears

https://github.com/user-attachments/assets/c510db5f-bd00-490b-bcb3-83e80fb97c0a

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri, I am also reproducing the [issue](https://github.com/status-im/status-mobile/pull/21611#issuecomment-2491704199) on the latest builds of current PR. I’ve tried two different users with varying numbers of accounts, some with more than three accounts holding assets. However, I am still unable to see the FROM page:

https://github.com/user-attachments/assets/b83da08e-796b-4e43-b632-1db2c92b18b9


### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
- Android Studion: Pixel XL API 33

**Comment by mohsen-ghafouri** [comment]
I might find the source if issue, it can't detect the root screen, i guess if you switch between tabs and then click on wallet tab it will start working, I just pushed a fix. will test and let you know if it's ready. 
CC @Horupa-Olena @VolodLytvynenko

**Comment by mohsen-ghafouri** [comment]
All looks good now, in latest PR's build on my iPhone device, please test and let me know @Horupa-Olena . thanks 

https://github.com/user-attachments/assets/169b8b12-010a-4703-a5ad-e26d5eba8ce4

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your fix! Everything is finally working.

https://github.com/user-attachments/assets/d1a9bf0c-d827-4b5f-b2d8-e545abc71ceb

However, I can’t fully test the entire flow and verify that the assets are swapped on the correct account (chosen on the From page) because there’s a [bug ](https://github.com/status-im/status-mobile/issues/21555)in the swap flow. I’m waiting for t[his PR](https://github.com/status-im/status-mobile/pull/21541) to resolve the issue.

I’d greatly appreciate it if you could also take a look at this [issue ](https://github.com/status-im/status-mobile/issues/21323)next, as it’s related to the Swap flow and makes sense to address after fixing the problem with the From page.

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri You can merge it PR.

**Comment by mohsen-ghafouri** [comment]
Hey @Horupa-Olena thank you for testing this PR, sure i will try to check that as well
