### PR TITLE
fix(profile)_: Truncate profile name in settings screen

### LINKED ISSUE #20459: Settings Profile name text overflow
# Bug Report

As reported in [ISSUE 1](https://github.com/status-im/status-mobile/pull/20412#issuecomment-2166613946) during QA by @mariia-skrypnyk, the name of the profile, when migrated from Status v1 to v2, can be greater than 20 characters, this can cause a text overflow in some devices.

### Expected behavior

The text doesn't overflow and is limited by the same validation limit of 20 characters used to edit a profile name.

### Reproduction

Migrate from Status v1 to v2 and choose a long random 3-word name in v1.

### Additional Information

- Status version: nightly 
- Operating System: Android

### PR DESCRIPTION
**Pull request by ilmotta**
- Fixes https://github.com/status-im/status-mobile/issues/20459

### Summary

This PR fixes the parent issue where, after migrating from v1 to v2, some user names may be too long to fit in some devices in the `Settings > Edit Profile > Name` setting. The solution was to truncate the name to the max valid length in v2, which is 20 characters.

### Review notes

I took the liberty of doing a few cheap optimizations in how settings are processed:

- Don't use entire Clojure maps as the `:key` in React. This is known to be slow because it's expensive for Clojure to generally transform a data structure into its string representation.
- Don't find the last item of a list using `last` and an equality between two maps. This will force each iteration to call `last`, which in turn will iterate over the entire list of items (we can think of the Clojure lazy seq as a linked list). Instead, we now cache the index outside the loop and do a number comparison.
- Don't pass entire props to style functions when not needed because destructuring has a cost. I wouldn't personally worry about this 99% of the time, but when there's only argument like in this PR where we were passing a single `blur?` argument, it's preferable to not use a map.

#### Areas that may be impacted

The rendering of settings items in any of the new settings screens. But to be clear, I tested and couldn't see any regression.

### Steps to test

A bit hard to test this one, but refer to the parent issue for reproduction steps with longer names coming from v1. If you have any question about testing, please ask @mariia-skrypnyk because she was the one who found this bug.

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/quo/components/settings/category/settings/view.cljs [hunk 1]
```diff
@@ -7,20 +7,23 @@
     [react-native.core :as rn]))
 
 (defn settings-category
-  [{:keys [label data container-style] :as props}]
-  (let [theme         (quo.theme/use-theme)
-        settings-item (filter identity data)]
+  [{:keys [label data blur? container-style]}]
+  (let [theme          (quo.theme/use-theme)
+        settings-items (filter identity data)
```
Comment (ajayesivan) [inline src/quo/components/settings/category/settings/view.cljs]: @ilmotta why do we need this filter here?

Comment (ilmotta) [reply src/quo/components/settings/category/settings/view.cljs]: This was already here and it's a way to eliminate non-truthy values from `data`. Another way to do I believe is `(remove nil? data)`, but I wanted to play safe and didn't change. I can change the code if you think the original is confusing.

Comment (ajayesivan) [reply src/quo/components/settings/category/settings/view.cljs]: Yes, it was confusing to me, but I figured it out 😉.

Screenshot 2024-06-20 at 16 45 37

I think `remove` will be easier to understand. However, if you think it's risky, we can keep it.

Thank you 😊

**Review by ajayesivan — APPROVED** [review]

File: src/quo/components/settings/category/settings/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/quo/components/settings/category/settings/view.cljs]: Will do it then. It was confusing for me too and it's probably not the fastest way to remove nils from a collection.

**Comment by ilmotta** [comment]
Hey @mariia-skrypnyk, just an FYI: I merged without QA because E2E test failures are not related to the changes I made and it's more expensive for QAs to verify this PR because it would be necessary to migrate from v1 to v2 and find a long enough name from the random 3-word generator, but for us devs we can directly change the code to force names longer than 20 characters. I tested the PR manually and it looks good.
