### PR TITLE
[#22111] fix: disabled bridge assets effect other list

### LINKED ISSUE #22111: Unsupported bridge assets appear as disabled on swap pages when "swap" tapped on main wallet page
### Preconditions:
User has assets that are not supported for bridging (e.g., any tokens other than ETH, DAI, USDC, or USDT).

### Steps to reproduce:
1. Go to the wallet main page.
2. Long-tap on an unsupported asset and select Bridge.
3. Navigate to the Bridge Setup page.
4. Either perform the transaction or go back to the wallet main page.
5. Tap "Swap" button on the main wallet page
6. Observe the following pages:
  - Select Asset
  - Assets to Receive
  - Assets to Pay

### Actual result:
Assets not supported for bridging are displayed as disabled on the swap pages.

https://github.com/user-attachments/assets/1f370bf4-a422-421d-a7c0-e2cee5124300

### Expected result:
Unsupported bridge assets should be shown as enabled on the all swap pages.

### Devices:
Pixel 7a (Android 13)
iPhone 11 Pro Max (iOS 17)

### ENV:
Nightly 14 Feb, 2025

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #22111

## Summary
Unsupported bridge assets appear as disabled on swap pages when "swap" tapped on main wallet page

## Testing notes

"send" also was effected by disabled bridge assets. please check that too. 

## Areas that may be impacted

Select Asset list in "swap", "send" and "bridge"

## Steps to test

1. Go to the wallet main page.
2. Long-tap on an unsupported asset and select Bridge.
3. Navigate to the Bridge Setup page.
4. Either perform the transaction or go back to the wallet main page.
5. Tap "Swap" button on the main wallet page
6. Observe the following pages:
  - Select Asset
  - Assets to Receive
  - Assets to Pay

## Result 

https://github.com/user-attachments/assets/dbdd3f18-bac3-45be-b12b-994639828a93

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/common/asset_list/view.cljs [hunk 1]
```diff
@@ -6,16 +6,17 @@
     [utils.re-frame :as rf]))
 
 (defn- asset-component
-  [{token-symbol  :symbol
-    token-name    :name
-    total-balance :total-balance
-    disabled?     :bridge-disabled?
-    fiat-value    :fiat-value
-    :as           token}
+  [{token-symbol     :symbol
```
Comment (vkjr) [inline src/status_im/contexts/wallet/common/asset_list/view.cljs]: Hey @mohsen-ghafouri! I think we have a room for improvement here.
By introducing `:list-type` property we increase logical coupling between components. We force our UI to perform application logic. That means UI can't be reused in other generic situations anymore. Also now we have to pass that new property everywhere.

To avoid coupling and cognitive overhead `asset-component` and `asset-list/view` components should be absolutely unaware about such concepts as `bridge`, `send`, `swap`. 

To do this we should move the decision on whether token is `disabled?` to `:wallet/current-viewing-account-tokens-filtered` subscription. Inside the subscription we have all information about app state and can make informed decision. The only thing UI should receive is `disabled?` property. 
No mentions of `bridge`, `swap`. etc.. required.
Wdyt?

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/common/asset_list/view.cljs]: Hey @VolodLytvynenko thank for your feedback, I believe it make sense, let me see if there is any data in `:wallet/current-viewing-account-tokens-filtered` to detect if consumer is `:bridge` or not. i think i can use current view id but will check in detail.

Comment (VolodLytvynenko) [reply src/status_im/contexts/wallet/common/asset_list/view.cljs]: > Hey @VolodLytvynenko thank for your feedback, I believe it make sense, let me see if there is any data in `:wallet/current-viewing-account-tokens-filtered` to detect if consumer is `:bridge` or not. i think i can use current view id but will check in detail.

@vkjr Just tagging you in case you didn’t receive a notification. There are too many Volodymyrs here :)

Comment (vkjr) [reply src/status_im/contexts/wallet/common/asset_list/view.cljs]: @mohsen-ghafouri, there is for sure, that subscription depends on `:wallet/wallet-send` and it is used to assoc `bridge-disabled?` to token :)

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/common/asset_list/view.cljs]: I'm so sorry @VolodLytvynenko 🥲, my bad. @vkjr Thank you will update the PR.

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 2]
```diff
@@ -565,7 +565,8 @@
  (fn [{:keys [db]} [account]]
    (let [asset-to-pay     (get-in db [:wallet :ui :swap :asset-to-pay])
          asset-to-receive (get-in db [:wallet :ui :swap :asset-to-receive])]
-     {:fx (if asset-to-pay
+     {:db (assoc-in db [:wallet :ui :send :tx-type] :tx/swap)
```
Comment (vkjr) [inline src/status_im/contexts/wallet/swap/events.cljs]: @mohsen-ghafouri  As far as I understand, inside `[:wallet :ui :send]` path we store information only for `send` and `bridge` and `tx-type` here can be only `send` or `bridge`. 
And we have `[:wallet :ui :swap]` where goes all swap data. So putting `:tx/swap` under `[:wallet :ui :send]` is not ideal and should be avoided.

But why do we need it anyway? I do not see it used

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: @vkjr yeah at first place they shouldn't put it in `:send` but now we have some logic rely on it like in `:wallet/current-viewing-account-tokens-filtered` that used in asset list. so if in any other flow we don't correct type it send wrong filter data, like `bridge-disabled?`

Comment (briansztamfater) [reply src/status_im/contexts/wallet/swap/events.cljs]: I think we should refactor the `:wallet/current-viewing-account-tokens-filtered` subscription instead of relying on an inconsistent schema in `app-db`. Placing swap data under the `[:wallet :ui :send]` path feels like an unnecessary hack to make the subscription work in the swap flow.

Also, in the future, we might want to separate the send and bridge states, making the `:tx-type` prop unnecessary. Currently, the state for send and bridge flows is shared under `[:wallet :ui :send]` because we previously supported cross-chain sending, which involved bridging — so sharing the state made sense back then. However, since we removed cross-chain sending, it might be cleaner to maintain separate states for each flow, like `[:wallet :ui :send]` and `[:wallet :ui :bridge]`.

If we go this route, the solution proposed in this PR would likely need to be refactored again.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: So either i can rely on `view-id` or move `tx-type` to a common place like [:wallet :ui], we need to know which flow is using `:wallet/current-viewing-account-tokens-filtered`. I think if i just move `tx-type` then it will remove the confusion. wdyt? @briansztamfater @vkjr

Comment (vkjr) [reply src/status_im/contexts/wallet/swap/events.cljs]: @mohsen-ghafouri, I don't think, you need to move tx-type around. Also there is no need to rely on view-id since it is more error-prone. You probably can rely on the fact of existance of `[:wallet :ui :swap]` in rf-db, which would mean that swap is in progress.

But could you please clarify why do you need the `tx/swap` overall? I don't see it used in the code you've changed. If you only need to disable visibility of some tokens during bridge process, you can rely on `[:wallet :ui :send :tx-type]` begin `tx/bridge`. Why do you need swap flag?

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: @vkjr I found that the source of issue is the when user close bridge flow it doesn't correctly do cleanup and `tx-type` will stay as `tx/bridge` so it causes issue, I'm going to fix clean up for bridge and it will remove need for `tx/swap`

**Comment by mohsen-ghafouri** [comment]
Hey @vkjr @briansztamfater, thanks for your feedback, I found source of issue, could you please review again?

File: src/status_im/contexts/wallet/home/view.cljs [hunk 3]
```diff
@@ -105,6 +105,7 @@
                                [multiple-accounts? first-account-address])
         on-swap-press         (rn/use-callback
                                (fn []
+                                 (rf/dispatch [:wallet/clean-send-data])
```
Comment (vkjr) [inline src/status_im/contexts/wallet/home/view.cljs:108]: This is okay decision but it would be ideal to find the place where state is not cleaned after exiting bridge state and call the cleanup there. Because cleanup of bridge shouldn't be a business for swap like it is in this fix.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/home/view.cljs:108]: We are calling this event also for send action and also swap in account view. cleanup for a multistep flow is tricky and for the scope of this issue I believe this changes would be enough @vkjr.

**Review by smohamedjavid — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
LGTM!

**Review by vkjr — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Thanks for your fix!

**Test report:**

Platforms: iOS and Android
Checked: 

- Select Asset
- Assets to Receive
- Assets to Pay

Failed e2e are not related.
PR can be merged.
