### PR TITLE
fix wrong composer opacity with minimised keyboard when editing message

### LINKED ISSUE #20305: [Android] Wrong composer opacity with minimised keyboard when editing message
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/67952253/ec34317d-4d01-484c-960f-7f0990c02d30

### Reproduction

1. Open chat with some history on Android device
2. Send a message
3. Long-press the message
4. Edit
5. Collapse the keyboard
6. Scroll the chat history

### Additional Information

- Status version: RC 2.29 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20305

### Testing
Please test opacity with all (text, images, reply, edit)

status: ready

### CODE REVIEW

**Review by OmarBasem — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/composer/utils.cljs [hunk 1]
```diff
@@ -86,12 +86,8 @@
...
 
 (defn empty-input?
-  [text images link-previews? reply? audio?]
-  (and (empty? text)
-       (empty? images)
-       (not link-previews?)
-       (not reply?)
-       (not audio?)))
+  [{:keys [input-text images link-previews? reply audio edit]}]
+  (not (or (not-empty input-text) images link-previews? reply audio edit)))
```
Comment (seanstrom) [inline src/status_im/contexts/chat/messenger/composer/utils.cljs:90]: Should we check if `images` is `not-empty` too?

Comment (OmarBasem) [reply src/status_im/contexts/chat/messenger/composer/utils.cljs:90]: I think it is being checked for as `images link-previews? reply audio edit` is wrapped in a `not`

**Comment by qoqobolo** [comment]
LGTM, thanks for the fix @Parveshdhull !
