### PR TITLE
[FIX #2620] Refactored double dispatch into single event-fx

### LINKED ISSUE #2620: Back button brings user to Discover instead of Popular hashtags or Recent Statuses if Chat was opened from one of these screens
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User opens Discover -> All (in Popular hashtags), so Popular hashtags screen is opened -> tap on Chat button, so 1-1 chat is opened. After this user taps on "<" to go back. In the released 0.9.12 we go back to Popular hashtags screen. In nightly build we go back to initial Discover screen (this is wrong)

Same issue with Back button if open Chats from Recent Statuses (Discover -> All under Recent Statuses -> Chat button -> `<` button)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- If user was in Popular hashtags screen, opened Chat and goes back by tapping on `<` or Android device button then Popular hashtags screen should be shown (in the same state as before user left it)
- If user was in Recent statuses screen, opened Chat and goes back by tapping on `<` or Android device button then Recent statuses screen should be shown (in the same state as before user left it)
#### Actual behavior
[comment]: # (Describe what actually happened.)
- User was in Popular hashtags screen, opened Chat and goes back by tapping on `<` or Android device button. As a result, Discover screen is shown (not Popular hashtags)
- User was in Recent statuses screen, opened Chat and goes back by tapping on `<` or Android device button. As a result, Discover screen is shown (not Recent statuses)
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
https://app.testfairy.com/projects/4803590-status/builds/7225894/sessions/11/?accessToken=7ya5mkxXOWPOfO-24m1DqP/PqZ4
- You need to have 2 devices that added each others as contacts in Status. They also need to have some hashtags (e.g #test) in their statuses (field under username in Profile)
- Open Discover
- Tap on All in section Popular hashtags -> Popular hashtags screen will be shown
- in Popular hashtags screen tap on Chat button -> 1-1 chat with a contact is opened
- Tap on `<` button or on Android device back button
- Check the screen shown to you
- Repeat same steps for All in section Recent statuses

### Additional Information
* Status version: nightly build 96. Status version 0.9.10-422-g6d5251ad
* Operating System: 
real device Pixel XL, Android 8.0
real device iPhone 6s, iOS 10.3.1

### PR DESCRIPTION
**Pull request by nrakochy**
Fixes [#2620](https://github.com/status-im/status-react/issues/2620)

### Summary:
Refactored do event on the discovery tab into single event-fx to fix navigation routing. 

The 2nd call on the double-dispatch was failing to properly populate the `:navigate-to` event, which in turn was causing the back button to refer to the previous nav state instead of the newly updated.

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/discover/events.cljs [hunk 1]
```diff
@@ -147,6 +147,12 @@
     (fn [_ _]
       (discoveries/delete :created-at :asc 1000 200))))
 
+(handlers/register-handler-fx
+ :show-discovery
+ (fn [_ [_ tags view-id]]
+   {:dispatch-n [[:set :discover-search-tags tags]
+                 [:navigate-to view-id]]}))
```
Comment (janherich) [inline src/status_im/ui/screens/discover/events.cljs]: Can you please refactor the code to not use `:dispatch-n`, but functional composition instead?
```clj
(handlers/register-handler-db
  :show-discovery
  (fn [db [_ tags view-id]]
    (-> db
        (assoc :discover-search-tags tags)
        (navigation/navigate-to view-id))))
```
With `navigation` ns (`status-im.ui.screens.navigation`) required of course. 
The reason is that we are trying to move from imperative, side-effecty code
to something more functional, see the rationale - https://github.com/status-im/ideas/issues/31 (Point 3.)

**Review by janherich — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/discover/events.cljs [hunk 2]
```diff
@@ -1,7 +1,7 @@
 (ns status-im.ui.screens.discover.events
   (:require [re-frame.core :refer [after dispatch enrich]]
             [status-im.utils.utils :refer [first-index]]
-            [status-im.utils.handlers :refer [register-handler get-hashtags]]
+            [status-im.utils.handlers :refer [register-handler register-handler-fx get-hashtags]]
```
Comment (janherich) [inline src/status_im/ui/screens/discover/events.cljs]: How is that you `:refer` `register-handler-fx` and then use the `handlers/register-handler-fx` ?
In general we are trying to move from `:refer`-ing anything to always explicitly aliasing with `:as`

**Comment by nrakochy** [comment]
I refactored and rebased this commit. It looks like I also needed to add a nav flag to the component. I think it is in working order.

**Review by janherich — APPROVED** [review]

File: src/status_im/ui/screens/discover/views.cljs [hunk 3]
```diff
@@ -69,11 +65,10 @@
                                      :contacts        contacts}]]))
 
 (defn popular-hashtags-preview [{:keys [popular-discoveries popular-tags contacts current-account]}]
-  (let [has-content? (seq popular-tags)]
+  (let [has-content? (seq popular-tags)
+        tags (map :name popular-tags)]
```
Comment (oskarth) [inline src/status_im/ui/screens/discover/views.cljs:69]: align

**Review by oskarth — APPROVED** [review]
Just minor formatting
