### PR TITLE
[#11991] [#11994] and chat list optimization

### LINKED ISSUE #11991: No unread message indicators after navigation back to 'Chats' main view via tap on Chats tab button
# Bug Report

## Problem

There are several scenarios of navigation in app which may lead to bug when subsequent receiving messages won't have unread indicator (and message won't be visible in chat - see first scenario below)
#### Expected behavior

Unread indicator is visible always when message received in chat until user has opened chat view when message received.
#### Actual behavior

No unread indicator is visible when message received in chat and user on different view (e.g. Wallet/Profile)

https://user-images.githubusercontent.com/8749671/114703752-5d0b2500-9d2e-11eb-830e-1bd0ddf3f5d6.mov

Note: this moved separately from https://github.com/status-im/status-react/issues/11895

### Reproduction 1

* UserA and UserB joins same public chat (or group)
* UserB sends text message in public chat
* UserA taps UserB user icon to navigate to it’s profile -> and tap Chat from there to open 1-1
* UserB now sends again in public chat message(s)
* UserA navigates back to Chats
* UserA opens public chat where unread message + unread indicator displayed
**Actual result:** Message is not visible
* UserA returns back to Chats view
**Actual result:** Unread message indicator still displayed

### Reproduction 2

* UserA and UserB joins same public chat (or group or 1-1 chat) and stays on this chat view
* UserA navigates back Chats main view by tapping 'Chats' tab button (Note: taping upon any tab button navigates user to main tab view disregard where he was before)
* UserB sends message in chat
* UserA checks if unread message indicator appears

### Additional Information
- Status version: develop 1.12, release 1.12.2
- Operating System: Android and iOS

### LINKED ISSUE #11994: No chats on Home screen after reopening the app if appearance doesn't match the device settings (dark/light mode)
# Bug Report

## Problem

If switch the application to dark mode, having the device in light mode (or vice versa), then after reopening the application the existing chats will disappear from the Home screen.
To display chats again, need to switch to another tab and reopen the Home screen.

#### Expected behavior

Chats don't disappear 

#### Actual behavior

https://user-images.githubusercontent.com/67952253/114709396-d0ac3280-9d2c-11eb-8392-f3326ae8cb3e.mp4

### Reproduction

**Precondition:** there are some chats on the Home screen

- Set dark mode in device settings
- Open Status 
- `Profile` > `Appearance` > Set `Light mode`
- Close app
- Reopen Status > Check the chat list
- Navigate to another tab
- Go back to Home screen > Check the chat list

### Additional Information

- Status version: Nightly 14/04
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes: #11991
fixes: #11994
and chat list optimization

### CODE REVIEW

File: src/status_im/ui/components/chat_icon/screen.cljs [hunk 1]
```diff
@@ -10,19 +10,24 @@
...
 
+(def get-name-first-char
+  (memoize
+   (fn [name]
+     ;; TODO: for now we check if the first letter is a #
+     ;; which means it is most likely a public chat and
+     ;; use the second letter if that is the case
+     ;; a broader refactoring should clean up upstream params
+     ;; for default-chat-icon
+     (string/capitalize (if (and (= "#" (first name))
```
Comment (shivekkhurana) [inline src/status_im/ui/components/chat_icon/screen.cljs]: How about `(re-find #"[a-z]" (str/lower-case name))`. This will return the first alphabet that appears in the string.

```clojure
(re-find #"[a-z]" "#$$$Status") ; => t
(re-find #"[a-z]" (str/lower-case "#$$$Status")) ; => S

**Review by shivekkhurana — APPROVED** [review]
Great work Andrey. I hope this leads to ⚡ faster⚡ chat UI.

File: src/status_im/ui/components/chat_icon/screen.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/ui/components/chat_icon/screen.cljs]: this is really old code, don't want to touch it in this PR

**Comment by churik** [comment]
@flexsurfer 
error when tapping on Profile > Advanced > Network:
image

**Comment by flexsurfer** [comment]
thanks @churik fixed

**Comment by churik** [comment]
@flexsurfer 
### ISSUE 1: when you tap on tag message, redirected to "Unknown"

**Steps:**
1) restore multiaccount from seed phrase
2) send to any channel message with link to public chat (i.e. #status)
3) tap on tag

**Expected result:** redirected to status channel

**Actual result:**
IMAGE 2021-04-19 11:23:39

**OS:** IOS, Android

**Comment by flexsurfer** [comment]
@churik  fixed, thanks

**Comment by churik** [comment]
@flexsurfer on builds with commit https://github.com/status-im/status-react/pull/11988/commits/27953a418f28c4ca39122b4508ed61e823008ec3 issue is still reproducible

**Comment by flexsurfer** [comment]
sorry @churik now should be fixed

**Comment by churik** [comment]
@flexsurfer 
### ISSUE 2: got an error when tap on + on Profile > Advanced > Network

**Steps:**
1) restore multiaccount from seed phrase
2) open Profile > Advanced > Network
3) tap on +

**Expected result:**
can add custom network

**Actual result:**
image

**OS:** IOS, Android

**Comment by flexsurfer** [comment]
thanks @churik fixed
