### PR TITLE
Unify login flow after account recovery

### LINKED ISSUE #5286: Missing value for property 'account.address' error when account is recovered
### Description

*Type*: Bug

*Summary*: This error happens only when there was already account with chat and user logged out and recovered another account. When recover button is pressed, "ReactNativeJS: Error: No item 1 in vector of length 1" error appears and then "Missing value for property 'account.address'". The app work fine when killed and opened again. 

### Reproduction

- Install Status on Android
- Open the app and create account
- Switch to Ropsten
- Log in again to the same account
- Log out
- Recover some other account 

### Additional Information
* Status version: 0.9.23 and July 25 nightly
* Operating System: Android
* [TF session](https://app.testfairy.com/projects/4803622-status/builds/8535945/sessions/4397051344/?accessToken=O4bps9Ctd-EI9pXbc821ILyt2oI)

### Logs

```
sterfunction enter
07-24 23:37:32.458 13800 13800 E SKBD    : aeo getInstance start
07-24 23:37:32.458 13800 13800 E SKBD    : aeo sendSIPInformation state: 6   isAbstractKeyboardView :  true
07-24 23:37:32.459 13800 29437 E SKBD    : aeo sending null keyboardInfo as SIP is closed
07-24 23:37:32.460 13800 13800 E SKBD    : wj isKeyboardLayoutOrCustomSymbolActivity: privateImeOptions is null
07-24 23:37:32.529 13800 13800 E SKBD    : ahn setCurrentInputModule mCurrentInputModule index: 10
07-24 23:37:32.576 13800 13800 E SKBD    : ahn setCurrentInputModule mCurrentInputModule index: 10
07-24 23:37:32.607 13800 13800 E SKBD    : ahn setCurrentInputModule mCurrentInputModule index: 10
07-24 23:37:32.632 13800 13800 E SKBD    : ait get previous
07-24 23:37:39.432 28562 28646 E ReactNativeJS: Error: No item 1 in vector of length 1
07-24 23:37:39.432 28562 28646 E ReactNativeJS:
07-24 23:37:39.432 28562 28646 E ReactNativeJS: This error is located at:
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in home
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in reagent20
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in RCTView
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in RCTView
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in main-tabs
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in reagent19
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in RCTView
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in main
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in root
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in reagent1
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in RCTView
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in RCTView
07-24 23:37:39.432 28562 28646 E ReactNativeJS:     in t
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: Error: No item 1 in vector of length 1
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: This error is located at:
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in home
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in reagent20
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in RCTView
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in RCTView
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in main-tabs
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in reagent19
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in RCTView
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in main
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in root
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in reagent1
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in RCTView
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in RCTView
07-24 23:37:39.457 28562 28647 E unknown:ReactNative:     in t, stack:
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: vector_index_out_of_bounds@12:479619
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: array_for@12:480197
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IIndexed$_nth$arity$2@12:486163
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:145042
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$ICollection$_conj$arity$2@12:557664
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: _conj@12:144166
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:228761
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:660482
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$4@12:214798
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IReduce$_reduce$arity$2@12:220999
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$2@12:266224
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IFn$_invoke$arity$variadic@12:660416
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: G__29779_29789@12:4797750
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:2486664
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:2486676
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: in_context@12:2286730
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: deref_capture@12:2286873
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: _run@12:2307395
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: cljs$core$IDeref$_deref$arity$1@12:2312381
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: _deref@12:153854
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: deref@12:211756
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:7870414
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:2321497
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: wrap_render@12:2322178
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: do_render@12:2323360
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:2323913
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: in_context@12:2286730
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: deref_capture@12:2286873
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: run_in_reaction@12:2315206
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:2323854
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: f@143:83728
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: beginWork@143:87321
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: o@143:128242
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: a@143:128621
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: T@143:132129
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: y@143:131565
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: v@143:131402
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: h@143:130681
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: c@143:129935
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: enqueueForceUpdate@143:60452
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: forceUpdate@109:1315
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: run_queue@12:2282422
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: flush_queues@12:2283694
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: run_queues@12:2283841
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@12:2283270
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@126:1369
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: x@126:643
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: callTimers@126:2788
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: value@121:3582
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: <unknown>@121:1067
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: value@121:3009
07-24 23:37:39.457 28562 28647 E unknown:ReactNative: value@121:1039
```

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #5286

### Summary:

We had a delay to show the main screen while we are recovering account. That might lead for the node to be starting longer than this 2 seconds delay and causing all sorts of issues.
The fix is with replacing this with our typical login flow (showing the login dialog with a process indicator) right after we recovered the account. It handles node restarts gracefully.

TODO
- [x] use `merge-fx` instead of `dispatch-n` in the code

### Steps to test:
- Open Status
- Create an account, switch it to the test network. Join some noisy channel to have more stuff happening.
- Recover any account.

status: ready

### CODE REVIEW

**Comment by lukaszfryc** [comment]
@mandrigin I'm getting some other error after the recovery:

image

I do steps from https://github.com/status-im/status-react/issues/5286

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/accounts/models.cljs [hunk 1]
```diff
@@ -44,29 +45,33 @@
...
+        {:networks/keys [networks]} db
+        enriched-account (assoc account
                                 :network config/default-network
                                 :networks networks
                                 :address address)]
     {:db                 (assoc-in db [:accounts/accounts address] enriched-account)
      :data-store/base-tx [(accounts-store/save-account-tx enriched-account)]}))
 
-(defn on-account-created [{:keys [pubkey address mnemonic]} password {:keys [signing-phrase status db]}]
+(defn on-account-created [{:keys [pubkey address mnemonic]} password seed-backed-up {:keys [signing-phrase status db] :as cofx}]
```
Comment (oskarth) [inline src/status_im/ui/screens/accounts/models.cljs:58]: Why do we change signature in breaking way? As opposed to new fn or possibly adding it to map (open, doesn't change positional args)

Comment (mandrigin) [reply src/status_im/ui/screens/accounts/models.cljs:58]: it's a (or rather should be) a private method, so why not? :)

File: src/status_im/ui/screens/accounts/events.cljs [hunk 2]
```diff
@@ -32,9 +32,9 @@
 
 (handlers/register-handler-fx
  :account-created
- [re-frame/trim-v (re-frame/inject-cofx ::get-signing-phrase) (re-frame/inject-cofx ::get-status)]
+ [re-frame/trim-v (re-frame/inject-cofx :get-signing-phrase) (re-frame/inject-cofx :get-status)]
```
Comment (yenda) [inline src/status_im/ui/screens/accounts/events.cljs]: we want to stop using the trim-v coeffect

Comment (mandrigin) [reply src/status_im/ui/screens/accounts/events.cljs]: what do we want to replace it with?

**Comment by lukaszfryc** [comment]
@mandrigin overall works fine. The issue is fixed and I did not found any regressions. There is a slight delay after sign in button is pressed during recovery but I think we can live with it.

File: src/status_im/ui/screens/accounts/models.cljs (hunk 1 above)
Comment (oskarth) [reply src/status_im/ui/screens/accounts/models.cljs:58]: If it should be a private fn we should probably indicate this with `defn-`

**Comment by lukaszfryc** [comment]
@mandrigin let's wait for e2e to finish. I just scheduled them manually: https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/1469/console

<blockquote><div><strong><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/1469/console">end-to-end-tests » status-app-end-to-end-tests PR-5631 Console [Jenkins]</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
thanks!

**Review by rasom — APPROVED** [review]

File: src/status_im/ui/screens/accounts/models.cljs (hunk 1 above)
Comment (mandrigin) [reply src/status_im/ui/screens/accounts/models.cljs:58]: I agree. We will have a follow-up PR for this issue, @yenda will take over. This one fixes the issue and reduces code duplication, but for sure it could be improved further.

Comment (goranjovic) [reply src/status_im/ui/screens/accounts/models.cljs:58]: It can't be a private `defn-` because it's used from the events namespace and should be used from test namespaces. Speaking of unit tests, imo that's really the only way to address things like breaking interface changes. 

Things like using maps solve some of the issues we with too many positional args, but at the expense of reduced visibility of those params, i.e. without a spec there is no named args declaration, with specs it's hidden away.

**Review by janherich — APPROVED** [review]

File: src/status_im/ui/screens/accounts/models.cljs (hunk 1 above)
Comment (goranjovic) [reply src/status_im/ui/screens/accounts/models.cljs:58]: Luckily it's just a regular pure fn, so it can be unit tested just fine.

**Comment by lukaszfryc** [comment]
e2e tests look good 👍
