### PR TITLE
fix: notification center blur

### LINKED ISSUE #19181: Shell - Notification Center screen issues
# Design Feedback 2.27

## [Shell] Notification Center screen 
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=3%3A68309&mode=design&t=OeK3GHXzoVCNnZog-1)

- **Dark overlay** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82254&mode=design#726037677)] has a wrong color compared to design
- **Wrong color tags and date** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82254&mode=design#717844623) and [comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82254&mode=design#727298202)] might be caused by the wrong colored overlay but the tags (color green) and the date next to the notification are hard to read

Screenshot 2024-03-11 alle 16 39 44

### Reproduction

1. Open Notification Center (more visible if you set the light theme from Settings)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max, Xiaomi [Android 8.1]

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by codemaster115**
fixes #19181 

### Summary

Shell - notification screen issue
- Wrong dark overlay color
- Wrong color of tags and date caused by the above issue.

#### Platforms

- Android
- iOS

##### Functional

- activity center

### Steps to test

- Open Status
- Open Notification Center by pressing notification icon on the top-right of screen.

### Before and after screenshots comparison
Simulator Screenshot - iPhone 13 - 2024-05-01 at 05 29 27

status: ready

### CODE REVIEW

File: src/status_im/contexts/shell/activity_center/style.cljs [hunk 1]
```diff
@@ -56,5 +56,5 @@
 
 (def blur
   {:style        {:position :absolute :top 0 :left 0 :right 0 :bottom 0}
-   :overlayColor colors/neutral-80-opa-80
+   :overlayColor colors/neutral-80-opa-80-blur
```
Comment (Parveshdhull) [inline src/status_im/contexts/shell/activity_center/style.cljs:59]: 👍

**Review by Parveshdhull — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]
✅

**Comment by qoqobolo** [comment]
Hi @codemaster115, thanks for the PR!
Could you please clarify one moment that is not entirely clear from the PR description: does this PR completely fix the issue https://github.com/status-im/status-mobile/issues/19181  or only `Wrong dark overlay color`? 

The thing is that once this PR is merged, the entire issue will be closed, which will be wrong since there are several more comments from the designers besides the wrong overlay color.
In this case please update the PR description or/and the issue accordingly. 
Thank you!

**Comment by codemaster115** [comment]
> Hi @codemaster115, thanks for the PR! Could you please clarify one moment that is not entirely clear from the PR description: does this PR completely fix the issue #19181 or only `Wrong dark overlay color`?
> 
> The thing is that once this PR is merged, the entire issue will be closed, which will be wrong since there are several more comments from the designers besides the wrong overlay color. In this case please update the PR description or/and the issue accordingly. Thank you!

@qoqobolo I just updated the PR description that it completely resolved the issue.

**Comment by qoqobolo** [comment]
Thank you @codemaster115 !
I smoke-tested it, and everything looks good. E2e failures are not PR-related. 
I also think manual testing could be skipped in this PR according to the new process (please read it if you haven’t already: https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md)

So, the PR is ready for design review, @Francesca-G please check the fixes from your perspective, thank you! 🙏✨

**Review by Francesca-G — COMMENTED** [review]
Overlay color looks much better, nice job ✨

About the tag: please make sure the text and the icon are in Success/Solid/50 so they're readable as per design:

Screenshot 2024-05-03 alle 09 15 46

>
_(implementation on the left, design on the right)_

**Comment by codemaster115** [comment]
> Overlay color looks much better, nice job ✨
> 
> About the tag: please make sure the text and the icon are in Success/Solid/50 so they're readable as per design:
> 
> Screenshot 2024-05-03 alle 09 15 46
> > 
> 
> _(implementation on the left, design on the right)_

@Francesca-G Please review it again. Just fixed

**Review by Francesca-G — APPROVED** [review]
Looks good now 👍
