### PR TITLE
[FIX #3074] Combine PR scripts

### LINKED ISSUE #3074: Combine PR scripts and clean up usage of merge-external-pr.sh
This bounty has 2 requirements:

1. `./merge-external-pr.sh REPO_URL BRANCH` doesn't work (it seems like it is trying to do the push on the upstream repository). Passing in only the number of the PR does, so clean up the script to only expect that single argument so it is clearer for everyone.

2. Combine the `merge-pr.sh` and `merge-external-pr.sh` scripts, based primarily on the `external` one as it is better and clearer. This requires keeping the same checks for making sure that PRs from external contributors are verified signed by core team members and that PRs from core team members themselves are correctly signed by the developer in question. 

We are having issues checking that PRs from core team members are squashed to single commits, see [here](https://github.com/status-im/status-react/issues/3075) for ref - so make sure the same check currently working for external PRs works for ones from core team members.

The desired interface is thus: `./scripts/merge-pr.sh <PR-ID>`, which should work regardless of where the PR is hosted or if it is signed or not.

### PR DESCRIPTION
**Pull request by sebastiandelgado**
Fixes #3074 

### Summary:

- Combine merge-pr.sh and merge-external-pr.sh using merge-external-pr.sh as a base.
- Modify script interface to `./scripts/merge-pr.sh <PR-ID>` and remove options to run with `<REPO_URL> <BRANCH>` arguments.
- Works regardless of where PR is hosted (internal/external) and whether or not it is signed.
- Keeps core team signature requirement.

Status: Complete

### CODE REVIEW

File: scripts/merge-pr.sh [hunk 1]
```diff
@@ -15,30 +20,127 @@ confirm() {
...
+refresh_base_branch() {
+  git fetch $REMOTE $BRANCH
+}
+
+rebase_pr() {
+  git checkout -B $PR_LOCAL_BRANCH $PR_REMOTE_NAME/$PR_BRANCH
+  git rebase $BRANCH
+}
+
+check_is_pr_single_commit() {
```
Comment (yenda) [inline scripts/merge-pr.sh:82]: so here the idea is that you need to confirm that you want to merge if it is not a single commit because most of the time we want to squash the commits in a PR before merging, but it might be the case that we want separate commits, so there need to be a confirmation but the script should not just fail on it.

Comment (yenda) [reply scripts/merge-pr.sh:82]: To test: 
if you have 2 commits in a PR, script should ask for confirm
if you have 1 commit, it should just do the merge

Comment (sebastiandelgado) [reply scripts/merge-pr.sh:82]: Got it. Will update soon.

**Comment by sebastiandelgado** [comment]
Just tested and added a commit that adds the option for merging multiple commits instead of rejecting anything that isn't squashed. Will squash this PR when its ready.

**Comment by oskarth** [comment]
Thanks @sebastiandelgado!

>  Status: WIP. Waiting for clarification on several issues over at #3074

Could you write the outstanding questions here? Seems like most questions got resolved.

**Comment by yenda** [comment]
@sebastiandelgado Is it ready or is there still something you are working on ? Please squash the commits if it is ready. Optionnaly you can sign your commit if you know how to use gpg signatures but it is not a requirement for external contributors since a core contributor will sign them when we merge.

**Comment by sebastiandelgado** [comment]
@oskarth @yenda its ready to be landed. I just squashed the 3 commits. Let me know if anything else needs to be done on my side.

**Review by yenda — APPROVED** [review]

**Review by andytudhope — APPROVED** [review]
LGTM

**Comment by sebastiandelgado** [comment]
Thanks guys!

**Review by oskarth — APPROVED** [review]

**Comment by yenda** [comment]
successfully merged with the script of the PR

**Comment by yenda** [comment]
Actually when trying to merge a PR of mine I get this now:

```
Writing objects: 100% (12/12), 1.92 KiB | 0 bytes/s, done.
Total 12 (delta 9), reused 0 (delta 0)
remote: Resolving deltas: 100% (9/9), completed with 9 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: At least one approved review is required by reviewers with write access.
To git@github.com:status-im/status-react.git
 ! [remote rejected] develop -> develop (protected branch hook declined)
error: failed to push some refs to 'git@github.com:status-im/status-react.git'
```

**Comment by sebastiandelgado** [comment]
@yenda what branch are you trying to merge so I can try to replicate the conditions? Have you tried using the original merge-pr.sh (not the merge-external-pr.sh or the new merge-pr.sh)?

**Comment by yenda** [comment]
@sebastiandelgado I tried to merge https://github.com/status-im/status-react/pull/3120 with the new merge-pr script

**Comment by yenda** [comment]
I think it has something to do with 

```
  if [[ $(echo "$pr_info" | jq -r .maintainer_can_modify) == true ]]; then
    RW_PR_REPO=1
  else
    warn "PR does not allow 'edits from maintainers', so it will be kept open"
  fi
```

File: scripts/merge-pr.sh [hunk 2]
```diff
@@ -15,30 +20,127 @@ confirm() {
...
 
-echo "[Clean up remote branch]"
-git push origin --delete $BRANCH
+EOF
+    exit 2
+  fi
+  load_config
+  check_pr_prereq
+  get_pr_info "$@"
+  cleanup
```
Comment (yenda) [inline scripts/merge-pr.sh:135]: why is cleanup happening so early ?

**Comment by sebastiandelgado** [comment]
@yenda are you getting the 
`PR does not allow 'edits from maintainers', so it will be kept open`
warning before you get the 
`remote: error: At least one approved review is required by reviewers with write access.`
 error? 

My understanding from the original state of the script is that PRs (at least external ones) on this repo were required to enable the `maintainer_can_modify` flag from github. 

Maybe thats not the case for core contributors? #3120 has `maintainer_can_modify=false`. The point of checking for this flag is so that the external branch can be renamed to `pr-<PRid>`. So correct me if I'm wrong, but it seems that this is done for uniformity.

As far as I can tell, there are three fixes:

1. Change merge-pr.sh so that it requires that all PRs (including those by core contributors) have `maintainer_can_modify=true` by using `fatal "PR does not allow 'edits from maintainers', so it will be kept open"` instead of just using `warn` on line 59, and removing the conditional on line 104.
2. Change merge-pr.sh such that `$PR_REMOTE_NAME` and `$PR_LOCAL_BRANCH` get set to the original name of the branch (not `pr-<PRid>`), which is available at `echo "pr_info" | jq -r .head.ref`
3. Don't even check the `maintainer_can_modify` flag and always use the original branch name instead of `pr-<PRid>`

I'm more than happy to issue a second PR with whichever change you prefer. Let me know what you think!

**Comment by yenda** [comment]
@sebastiandelgado  wouldn't it also be possible to differentiate the external and core contributors PR ?

**Comment by yenda** [comment]
@sebastiandelgado I am getting the warning before yes sorry I missed the question.

**Comment by sebastiandelgado** [comment]
@yenda thanks for clarifying. You're right about being able to differentiate between external and core contributors from the github API.

I made a new PR #3155 which checks for this condition. I tested it on my dummy repo which I think has the same settings as status-im/status-react (including the required review), so it *should* work. 

Maybe its worth it for you to test this when trying to merge another PR before we approve it? Let me know what you think.

File: scripts/merge-pr.sh (hunk 2 above)
Comment (sebastiandelgado) [reply scripts/merge-pr.sh:135]: This cleanup statement is at the same place it was at originally. The intention here is to checkout develop and remove any leftover branches created in a previous failed attempt at running this script with the same PR-id.
