### PR TITLE
[#18739] Fix ENS resolution

### LINKED ISSUE #18739: ENS resolution depends on build instead of testnet mode
### Problem
Currently, ENS resolution is tied to the builds. In PRs, testnet ENS addresses are resolved, regardless of the testnet toggle's state. In Nightly builds, mainnet ENS addresses are resolved, regardless of the testnet toggle. The intention of this issue is to make ENS resolving related to the testnet toggle

### Steps:
1. Open Nightly
2. Enable the Testnet toggle
3. Go to the wallet -> open any eth address -> tap 'send'  
4. Type any eth address (example: qoqobolo.stateofus.eth) on "Send to" screen

### Actual result:
ENS resolution is not dependent on the selected selected testnet toggle

https://github.com/status-im/status-mobile/assets/52490791/59da6842-b641-46e7-9af5-e0d04ad7e3eb

### Expected result:
The ENS resolving depends on the selected  testnet toggle in Advanced -> testnet mode
- If testnet toggle is enabled, then testnet ENS should be resolved
- If testnet toggle is disabled, then mainnet ENS should be resolved

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-192865&mode=design&t=MMs1GoYDn4hNtbL6-0

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #18739 

### Summary

This PR fixes the ENS resolution, now it is based on the test network and goerli enabled settings.

Example, `qoqobolo.stateofus.eth` only exists on testnet goerli, so in the following video:
1. Attempts to resolve it out of testnet, it fails.
2. Enables testnet and attempts to resolve it, it fails.
3. Enables Goerli as default testnet and attempts to resolve it, it succeds.

[Screencast from 2024-03-13 12-28-59.webm](https://github.com/status-im/status-mobile/assets/90291778/15b55391-8377-4402-97df-a2dbb4b514a2)

This PR affects the ENS resolution on two places:

- In the "Send to" screen (shown in video),
- In the "Add address to watch" screen while using an ENS.

### Review notes

While solving this issue I found the internal config name to enable goerli was the keyword `:is-goerli-enabled?`, this is not following Clojure naming for booleans, so I renamed it to just `:goerli-enabled?`. This makes the diff a bit dirtier, sorry if that makes the review more difficult.

I added that change as a separate commit, so if you think it shouldn't be applied, I can easily revert it. :+1: 

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to wallet tab
- Try ENS resolution on the "Send to" screen (as shown in the video) and in the "Add address to watch" screen.

Note: We don't have any other place where ENS are being resolved in the wallet tab.

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/events.cljs [hunk 1]
```diff
@@ -275,46 +275,50 @@
...
-                  (boolean result)))}))
+   (let [suggestion (if result
+                      [{:type     item-types/address
+                        :ens      ens
+                        :address  (eip55/address->checksum result)
+                        :networks [:ethereum :optimism]}]
+                      [])]
+     {:db (-> db
+              (assoc-in [:wallet :ui :search-address :local-suggestions] suggestion)
+              (assoc-in [:wallet :ui :search-address :valid-ens-or-address?] (boolean result)))})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events.cljs:327]: This is just a refactor

File: src/status_im/contexts/wallet/events.cljs [hunk 2]
```diff
@@ -275,46 +275,50 @@
...
               :params     [chain-id ens]
               :on-success #(rf/dispatch [:wallet/set-ens-address % ens])
               :on-error   (fn []
                             (if (= domain ".stateofus.eth")
-                              (rf/dispatch [:wallet/search-ens input chain-id cb ".eth"])
+                              (rf/dispatch [:wallet/search-ens input on-error-fn ".eth"])
                               (do
                                 (rf/dispatch [:wallet/set-ens-address nil ens])
-                                (cb))))}]]]})))
+                                (on-error-fn))))}]]]})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events.cljs]: We no longer receive `chain-id`, it was extracted from a subscription and the passed to this event. Here I'm directly extracting the `chain-id` from the `db`, and now it depends on the testnet settings.

Additionally, we received `cb` but it was unclear what it was, it's an on-error callback, so renamed it to `on-error-fn`

File: src/status_im/contexts/wallet/accounts/add_account/address_to_watch/events.cljs [hunk 3]
```diff
@@ -33,9 +33,10 @@
 
 (rf/reg-event-fx
  :wallet/get-address-details
- (fn [{:keys [db]} [address-or-ens]]
-   (let [request-params [constants/ethereum-mainnet-chain-id address-or-ens]
-         ens?           (string/includes? address-or-ens ".")]
+ (fn [{db :db} [address-or-ens]]
+   (let [ens?           (string/includes? address-or-ens ".")
+         chain-id       (utils/short-name->id db :eth)
+         request-params [chain-id address-or-ens]]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/accounts/add_account/address_to_watch/events.cljs]: Fixing the ENS resolution while adding an address to watch :eyes:

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/profile/settings/events.cljs [hunk 4]
```diff
@@ -71,13 +71,14 @@
...
+(rf/reg-event-fx
+ :profile.settings/toggle-goerli-test-network
  (fn [{:keys [db]}]
-   (let [value      (get-in db [:profile/profile :is-goerli-enabled?])
+   (let [value      (get-in db [:profile/profile :goerli-enabled?])
          on-success #(rf/dispatch [:logout])]
      {:fx [[:ui/show-confirmation
             {:content   (i18n/label :t/goerli-testnet-toggle-confirmation)
-             :on-accept #(rf/dispatch [:profile.settings/profile-update :is-goerli-enabled?
+             :on-accept #(rf/dispatch [:profile.settings/profile-update :goerli-enabled?
```
Comment (smohamedjavid) [inline src/status_im/contexts/profile/settings/events.cljs]: @ulisesmac - I guess the `status-go` expects that key `is-goerli-enabled?`

https://github.com/status-im/status-go/blob/afd72ace28ed6629297820af73053cea3e73e63b/multiaccounts/settings/columns.go#L395-L399

https://github.com/status-im/status-go/blob/afd72ace28ed6629297820af73053cea3e73e63b/multiaccounts/settings/structs.go#L217

File: src/status_im/contexts/wallet/events.cljs [hunk 5]
```diff
@@ -275,46 +275,50 @@
...
-                      :address  (eip55/address->checksum result)
-                      :networks [:ethereum :optimism]}]
-                    []))
-        (assoc-in [:wallet :ui :search-address :valid-ens-or-address?]
-                  (boolean result)))}))
+   (let [suggestion (if result
+                      [{:type     item-types/address
+                        :ens      ens
+                        :address  (eip55/address->checksum result)
+                        :networks [:ethereum :optimism]}]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/events.cljs:323]: Quick question: (I know this is not related to the PR)
Any reason why we set networks for ENS addresses? 

@J-Son89

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 6]
```diff
@@ -220,9 +220,12 @@
...
 (defn short-name->id
-  [short-name testnet-enabled? goerli-enabled?]
-  (let [chain-id-map (get-chain-id testnet-enabled? goerli-enabled?)]
-    (get chain-id-map short-name)))
+  ([db short-name]
+   (let [{:keys [test-networks-enabled? goerli-enabled?]} (:profile/profile db)]
+     (short-name->id short-name test-networks-enabled? goerli-enabled?)))
+  ([short-name testnet-enabled? goerli-enabled?]
+   (let [chain-id-map (get-chain-id testnet-enabled? goerli-enabled?)]
+     (get chain-id-map short-name))))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/common/utils.cljs]: I have refactored this function to accept both short name (`opt`) and full name (`optimism`) in my WIP PR
https://github.com/status-im/status-mobile/pull/19150/files#diff-7c546e10d0478f5b2a86af59d724db93577c9e81eae2b51826680873ffc5f412R203

File: src/status_im/contexts/profile/settings/events.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/settings/events.cljs]: @smohamedjavid thanks for the reference!

Ok, I guess the "react field name" should have been `goerli-enabled?` instead of `is-goerli-enabled?` :cry: 
We should keep it as before then.

Fortunately, I expected a reason like this, so it's easy to rollback these changes.

File: src/status_im/contexts/wallet/events.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/events.cljs:323]: I'm not sure why they are being hardcoded :thinking:, since this is being used in the "Send to" screen, I guess these networks are the valid ones for the address resolved.

@OmarBasem should have more context about this

File: src/status_im/contexts/profile/settings/events.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/settings/events.cljs]: Done!

File: src/status_im/contexts/wallet/events.cljs (hunk 5 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/events.cljs:323]: I don't remember if I added this line by mistake or it was copied but it probably shouldn't be hardcoded

**Review by OmarBasem — APPROVED** [review]

File: src/status_im/contexts/profile/settings/events.cljs (hunk 4 above)
Comment (smohamedjavid) [reply src/status_im/contexts/profile/settings/events.cljs]: I agree @ulisesmac. I know it's frustrating, we have to make changes in status-go first and make changes in clients' apps in one shot.

Additionally, renaming the DB column (altering the table) is not supported in iOS. We have to create a new column (`goerli_enabled`) and use it.

There should be a guideline for these things (naming variables and such) in `status-go` just as we have for `mobile`.

Comment (J-Son89) [reply src/status_im/contexts/profile/settings/events.cljs]: 100% @smohamedjavid - that would be great to see if it doesn't already exist!

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac could you resolve existing conflicts?

**Comment by ulisesmac** [comment]
@VolodLytvynenko  done :+1:

**Comment by yevh-berdnyk** [comment]
e2e failures are not related to this PR

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for PR. No issues form my side. Ready to be merged
