### PR TITLE
fix small Keycard-related bugs

### LINKED ISSUE #10793: When changing name on adding new account is wallet in keycard multiaccount, 6-digit keyboard is displayed along with native keyboard
# Bug Report

## Problem
photo_2020-06-10 11 10 21

#### Expected behavior
native keyboard is closed

#### Actual behavior
custom keyboard is shown with native

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create multiaccount with keycard
- Go to wallet
- Tap on "Add account"
- Change name
- Tap Next

### Additional Information

- Status version: release 1.4
- Operating System: Android

### LINKED ISSUE #11060: Message "Your keycard is frozen" is shown on the wallet screen in just recovered non-keycard multiaccount, if user also has keycard multiaccount with frozen card
# Bug Report

## Problem

If keycard was frozen (during any flow when PIN is required) and after that user recovers non-keycard multiaccount, the message "Your keycard is frozen" on the Wallet screen will be shown in non-keycard multiaccount.
After relogin the message disappears. 

#### Expected behavior

There is no message "Your keycard is frozen" in non-keycard multiaccount.

#### Actual behavior

Снимок экрана 2020-08-10 в 11 47 20 AM

### Reproduction

- Log in to keycard multiaccout
- Wallet -> Send transaction -> Set a valid amount of ETH -> Tap Sign with keycard
- Enter invalid PIN three times
- Tap "Dismiss" in pop-up "Keycard is frozen"
- Log out
- Recover non-keycard multiaccount with seed phrase and log in
- Open wallet screen

### Additional Information

- Status version: Nightly 10/08
- Operating System: Android 10

### PR DESCRIPTION
**Pull request by bitgamma**
Fixes #10793.
Fixes #11060.

### CODE REVIEW

File: src/status_im/ui/screens/keycard/subs.cljs [hunk 1]
```diff
@@ -203,6 +203,5 @@
 (re-frame/reg-sub
  :keycard/frozen-card?
  (fn [db]
-   (let [{:keys [pin-retry-counter]}
-         (get-in db [:keycard :application-info])]
-     (zero? pin-retry-counter))))
+   (when (common/keycard-multiaccount? db)
+     (zero? (get-in db [:keycard :application-info :pin-retry-counter])))))
```
Comment (flexsurfer) [inline src/status_im/ui/screens/keycard/subs.cljs]: its similar to `(and (common/keycard-multiaccount? db) (zero? (get-in db [:keycard :application-info :pin-retry-counter])))`

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/keycard/subs.cljs (hunk 1 above)
Comment (bitgamma) [reply src/status_im/ui/screens/keycard/subs.cljs]: thanks, indeed the version ``and`` makes more sense, fixed.
