### PR TITLE
fix: handle limit event

### LINKED ISSUE #18980: Private group chat events are not displayed as per designs
The event in a private group chat are not displayed as per figma:
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3722-536851&mode=design&t=pDNuiUdIWvcyq3kb-4

### LINKED ISSUE #19206: User is allowed to to add more than 19 members to group chat
# Bug Report

## Problem 

The maximum number of group members should be limited to 20, including the group creator.

#### Expected behavior

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3720-548968&mode=design&t=MiwpT60QOS46oBU1-4

Screenshot 2024-03-12 at 15 24 14

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/c674a041-cf9b-4615-9173-87468d4aed5b

### Reproduction

1. Add 19+ contacts
2. Create a group chat with all of them

### Additional Information

- Status version: nightly 12/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
Fixes https://github.com/status-im/status-mobile/issues/18980

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Handles the limit event when creating a new group chat
- Adds toast for when the limit is surpassed
- Adds new translation for group chat limit

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- group chats

### Steps to test

- Open Status
- Go to chat tab
- Click the + button in the top right to start a new chat
- Add more than the limit of 19 contacts to raise the event

status: ready 

max group contact reached
[^Changed contact limit to 3 for demo purposes]

### CODE REVIEW

File: src/status_im/contexts/chat/home/new_chat/view.cljs [hunk 1]
```diff
@@ -52,10 +52,25 @@
...
+                                       [:toasts/upsert
+                                        {:id   :remove-nickname
+                                         :type :negative
+                                         :text (i18n/label :t/new-group-limit
+                                                           {:max-contacts
+                                                            constants/max-group-chat-contacts})}]))
+                                    (if
+                                      user-selected?
+                                      (re-frame/dispatch [:deselect-contact public-key])
+                                      (re-frame/dispatch [:select-contact public-key])))]
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/home/new_chat/view.cljs]: Hi @BalogunofAfrica, Thank you fixing this issue.

Can we use something like this?

```
selected-contacts-count (rf/sub [:selected-contacts-count])
on-toggle               (fn []
                          (if
                              user-selected?
                            (re-frame/dispatch [:deselect-contact public-key])
                            (do
                              (when (= constants/max-group-chat-contacts selected-contacts-count)
                                (rf/dispatch
                                 [:toasts/upsert
                                  {:id   :remove-nickname
                                   :type :negative
                                   :text (i18n/label :t/new-group-limit
                                                     {:max-contacts
                                                      constants/max-group-chat-contacts})}]))
                              (re-frame/dispatch [:select-contact public-key])))]
```

Comment (Parveshdhull) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: - Unnecessary calculation when deselecting
- Little confusing

Comment (Parveshdhull) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: Unless I am still confused by what & why we are doing like this :thinking:

Comment (Parveshdhull) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: Also, should we use useCallback Here?

File: src/status_im/constants.cljs [hunk 2]
```diff
@@ -120,6 +120,7 @@
 
 (def ^:const min-password-length 6)
 (def ^:const max-group-chat-participants 20)
+(def ^:const max-group-chat-contacts (dec max-group-chat-participants))
```
Comment (Parveshdhull) [inline src/status_im/constants.cljs]: `participants` or `contacts` I guess they both represent same thing. It will also might create confusion, better to do this `dec` where it is used or we can find a proper name for this

Comment (BalogunofAfrica) [reply src/status_im/constants.cljs]: `participants` is everyone in the group with the user inclusive, while `contacts` is the contacts of the user (not inclusive)

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 1 above)
Comment (BalogunofAfrica) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: We wouldn't benefit that much from `useCallback` here, since the component that uses it is not memoized itself

cc: @flexsurfer

File: src/status_im/constants.cljs (hunk 2 above)
Comment (BalogunofAfrica) [reply src/status_im/constants.cljs]: We could also call it :
- `max-group-chat-external-participants` (seems too verbose)
- `max-group-chat-peers` (peers could mean something else)

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: all components memoized by default we don't need to memoize them manually, so we should use use-callback or use-memo when needed

Comment (BalogunofAfrica) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: In this context, the component only re-renders when `user-selected?` or `selected-contacts-count` changes.

And those two values are used in the callback (hence dependency), I don't think we would benefit, since `useCallback` would return a new reference anyways when those two values change.

Comment (flexsurfer) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: i don't have an opinion yet, but you're right about this context, but i feel like if we won't use hook, it might lead to not using it at all, so i would say better to have it even if won't be more effective, at least it shows that dev knew how it works when implemented it and dependencies for this function clearly visible

Comment (BalogunofAfrica) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: I understand the concern, but applying `useMemo` or `useCallback` (by default) without context increases our memory footprint.

File: src/status_im/constants.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/constants.cljs]: i would say it's not a constant, it's more like a logic, so i would move `max-group-chat-contacts (dec max-group-chat-participants))` , and in the context it will be more clear , name won't be confusing

File: src/status_im/contexts/chat/home/new_chat/view.cljs [hunk 3]
```diff
@@ -52,10 +52,23 @@
...
   (fn [{:keys [public-key] :as item}]
-    (let [user-selected? (rf/sub [:is-contact-selected? public-key])
-          on-toggle      #(if user-selected?
-                            (re-frame/dispatch [:deselect-contact public-key])
-                            (re-frame/dispatch [:select-contact public-key]))]
+    (let [user-selected?          (rf/sub [:is-contact-selected? public-key])
+          selected-contacts-count (rf/sub [:selected-contacts-count])
+          on-toggle               (fn []
+                                    (if
+                                      user-selected?
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/home/new_chat/view.cljs]: little bit hard to read, better `(if user-selected?` in one line

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 1 above)
Comment (BalogunofAfrica) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: > all components memoized by default we don't need to memoize them manually, so we should use use-callback or use-memo when needed

If all components are memoized by default, wouldn't passing a map like this defeat the purpose of memoization? 🤔

```clj
[quo/button
     {:icon-only?          true
      :type                :grey
      :background          :blur
      :size                32
      :accessibility-label :close-scan-qr-code
      :on-press            #(rf/dispatch [:navigate-back])}
     :i/arrow-left]]
```

Since the map would get a new reference and be created anew in every render

File: src/status_im/contexts/chat/home/new_chat/view.cljs [hunk 4]
```diff
@@ -49,13 +49,27 @@
                                (rf/dispatch [:open-modal :new-contact]))}
       (i18n/label :t/add-a-contact)]]))
 
+(def ^:private max-group-chat-contacts (dec constants/max-group-chat-participants))
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/home/new_chat/view.cljs]: As we have `selected-contacts-count` for comparison, should we use something like `contacts-selection-limit`?

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: yes, all handlers should be moved to use-callback, this is our biggest problem that didn't strict before

Comment (flexsurfer) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: > I understand the concern, but applying `useMemo` or `useCallback` (by default) without context increases our memory footprint.

i don't think impact will be big, but not doing this will impact performance a lot, so when we realize that all devs understand how to use memoization tools, we can make it less strict

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/chat/home/new_chat/view.cljs [hunk 5]
```diff
@@ -49,13 +49,27 @@
...
 (defn contact-item-render
   [_]
   (fn [{:keys [public-key] :as item}]
-    (let [user-selected? (rf/sub [:is-contact-selected? public-key])
-          on-toggle      #(if user-selected?
-                            (re-frame/dispatch [:deselect-contact public-key])
-                            (re-frame/dispatch [:select-contact public-key]))]
+    (let [user-selected?          (rf/sub [:is-contact-selected? public-key])
+          selected-contacts-count (rf/sub [:selected-contacts-count])
+          on-toggle               (fn []
```
Comment (ilmotta) [inline src/status_im/contexts/chat/home/new_chat/view.cljs]: `on-toggle` here could have been refactored into a separate event. To keep the UI simpler and the logic of the handler easily unit testable :)

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 5 above)
Comment (Parveshdhull) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: Also, components will not get triggered by `:selected-contacts-count` sub, as this can be easily accessible in event. Great suggestion :clap:

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im/contexts/chat/home/new_chat/view.cljs]: > yes, all handlers should be moved to use-callback, this is our biggest problem that didn't strict before

I wholeheartedly disagree with this guideline to always use `useCallback`, as I explained in detail in these comments https://github.com/status-im/status-mobile/pull/19033#discussion_r1508871398 https://github.com/status-im/status-mobile/pull/19033#discussion_r1508131403

This guideline should be revisited IMO. I'll use `useCallback` a lot of times, but not always. It's literally unnecessary to always use it and it causes hard to debug issues in React apps, even when used by experienced devs (caching is hard).

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica please, rebase your PR.

**Comment by mariia-skrypnyk** [comment]
Hi @BalogunofAfrica !

ISSUE 1: No toast is shown when limit is reached

Steps: 
1. Login to app (User with 20+ contacts)
2. Go to Messages +
3. Create new chat
4. Choose 19+ contacts

Actual result: no banner

https://github.com/status-im/status-mobile/assets/147824399/4c13c03e-2779-4321-bc2b-61932371fc09

Expected result: banner appeared after user chose 20 and more contacts

**Comment by mariia-skrypnyk** [comment]
**SUGGESTION: User should not be able to check 20+ contacts during chat creation**

**Actual result:** user can add 20 contacts and banner appears on the 20th "checked" but user still can add more and more contacts.

https://github.com/status-im/status-mobile/assets/147824399/77981f06-fd30-4816-aa7a-6310e865a66f


**Idea:** let the banner appear once user addd 20th contact and then adding users will be disabled. As it works in chats -> adding images from the gallery. User see banner appeared when he tries to add 7th image. Image adding is disabled after 6 images.

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica Thanks.
Failed e2e are not related and I move PR to the design review by @Francesca-G.

**Review by Francesca-G — APPROVED** [review]
Approving and adding follow up required for comments not related to the event limit

Review [here](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7/Review-Messages-%2F-Mobile?type=design&node-id=61%3A6689&mode=design&t=rNVlhZLM2sEQc1Nm-1) :)

**Comment by BalogunofAfrica** [comment]
> Approving and adding follow up required for comments not related to the event limit
> 
> Review [here](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7/Review-Messages-%2F-Mobile?type=design&node-id=61%3A6689&mode=design&t=rNVlhZLM2sEQc1Nm-1) :)

All reviews here are addressed in this PR: https://github.com/status-im/status-mobile/pull/19054

**Comment by BalogunofAfrica** [comment]
@mariia-skrypnyk Can this be merged?

**Comment by mariia-skrypnyk** [comment]
Hi @Francesca-G ! [Here](https://github.com/status-im/status-mobile/pull/19066#issuecomment-1985650326) I've made a suggestion. @BalogunofAfrica already implemented it. Let me know does it meets your vision?

**Comment by Francesca-G** [comment]
> Hi @Francesca-G ! [Here](https://github.com/status-im/status-mobile/pull/19066#issuecomment-1985650326) I've made a suggestion. @BalogunofAfrica already implemented it. Let me know does it meets your vision?

Sounds good to me 👍
Only thing we should add is the toast behavior if the user tries to select other members past the 19/19 limit, following the image selection logic.

Example here:


https://github.com/status-im/status-mobile/assets/122543089/74292ef9-8f03-4fd5-9ca8-f0c955bcd89d

>
As you can see if the user tries to select an image after reaching the 6/6 limit the toast keeps reappearing, in case the user missed it or couldn't read it.

Hope this helps!

**Comment by mariia-skrypnyk** [comment]
Hi @BalogunofAfrica!

Please, let me know when Francesca's comment will be implemented. 

And I want to add one more point to add : red color while reaching a limit.
Screenshot 2024-03-13 at 10 51 47
Thanks!

**Comment by Francesca-G** [comment]
@mariia-skrypnyk @BalogunofAfrica 
Mario confirmed this behavior: 

- user selects members up to 19 and then creates the group ➡️ 19/19 number stays grey, this isn't an error: a user is allowed to create a group with 19 members

- user selects members up to 19 and then tries to tap on the 20th member ➡️ 19/19 number becomes red, toast appears

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica thanks for a such quick update!
I've checked and works as expected.

Please, @Francesca-G review today's approved logic.
These your review details mentioned [here](https://github.com/status-im/status-mobile/pull/19066#pullrequestreview-1930567226) will be done in this PR: https://github.com/status-im/status-mobile/pull/19054

**Review by Francesca-G — APPROVED** [review]
Looks good ✨

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica please, merge 👍
