### PR TITLE
bug #4952 - moved the wrong password tooltip a bit up to make the fie…

### LINKED ISSUE #4835: "Wrong password" validation message partially overlaps "Enter password" placeholder in sign transaction screen
### Description

*Type*: Bug

*Summary*: wrong password validation message overlaps "Enter password" placeholder when sign transaction (or sign message for DApp)

#### Expected behavior
no overlapping

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Log in
- Open wallet 
- Tap on send transaction, fill Recipient and amount with valid data
- Tap on Sign transaction
- Paste wrong password
- Erase password

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build [19/06/18](https://i.diawi.com/BbxVyx)
* Operating System: iOS 11, IPhone 7

### LINKED ISSUE #4952: Сannot enter valid password if "Wrong password" is shown and keyboard is hidden (send transaction screen)
### Description
*Type*: Bug
*Summary*: after validation error "Wrong password" if your keyboard is already hidden (you tapped on "Done" or "Back"  after entering password) - you cannot set focus on password field to open keyboard again.

#### Expected behavior
can focus on password field and edit password; keyboard is opened.

#### Actual behavior
cannot focus on password field, so cannot sign transaction
done

### Reproduction

- Open Status
- Go to Wallet 
- Tap on Send Transaction
- Enter wrong password
- Tap on "Done" on keyboard (Android and IOS) or on Back (Android only) to hide keyboard
- Tap on sign transaction
- try to edit password

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: beta
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #4952 
also fixes #4835 

### Summary:

The "Wrong password" tooltip was blocking access to the password field, making it unfocusable if the user ever loses focus on it. This PR fixes the immediate issue by moving the tooltip just a little bit up.

### Steps to test:
see #4952 

status: ready

### CODE REVIEW

**Comment by goranjovic** [comment]
screenshot-2018-07-27_14 31 11 506

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 1]
```diff
@@ -56,7 +56,7 @@
          :accessibility-label    :enter-password-input
          :auto-capitalize        :none}]
        (when wrong-password?
-         [tooltip/tooltip (i18n/label :t/wrong-password)])]]]))
+         [tooltip/tooltip (i18n/label :t/wrong-password) {:bottom-value -20}])]]]))
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/views.cljs]: Could this be defined in `styles`?

**Review by jeluard — APPROVED** [review]

**Comment by flexsurfer** [comment]
@goranjovic something wrong, this tooltip should be above the whole panel, looks like it has been moved to another container

**Comment by goranjovic** [comment]
@flexsurfer It didn't really make sense, because even before this change it was hiding the text a little bit.

You mean like this?

screenshot-2018-07-27_14 31 11 506

**Comment by flexsurfer** [comment]
@goranjovic yes you can find it in Zeplin https://zpl.io/bL4KqX7
image

**Review by denis-sharypin — CHANGES_REQUESTED** [review]
@goranjovic  thanks! Please, follow @flexsurfer  example above. Also, the style of the tooltip should be a bit different. In the tooltip that we use during the onboarding, it has a red background. Can we use it here as well?

**Comment by goranjovic** [comment]
@denis-sharypin @flexsurfer updated:

screenshot-2018-07-30_16 01 48 78

**Review by flexsurfer — APPROVED** [review]

**Review by denis-sharypin — APPROVED** [review]

**Comment by asemiankevich** [comment]
https://github.com/status-im/status-react/issues/4952 and https://github.com/status-im/status-react/issues/4835 are fixed here. Also UI looks good!
image

image
