### PR TITLE
Composer collapsing when editing canceled/done

### LINKED ISSUE #17433: The composer remains expanded when the cancel button is tapped during message editing or after sending message with picture and long description
#### Expected behavior
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=8666-42639&mode=design&t=0tR9e9C8vBDJzDXT-0
In the case of message editing, if the cancel button is tapped, the composer should return to its original state.
Discussed with the design team:
image

#### Actual behavior
The composer remains expanded even after tapping the cancel button during message editing.

https://github.com/status-im/status-mobile/assets/52490791/4f5dc70c-49b4-4072-954a-243be1cf109c

### Reproduction
1. Start editing a long message in the composer.
2. Tap the cancel button.

### Additional Information
- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #17825: Composer focuses when re-entering with unfinished edit/reply
# Bug Report

When editing/replying to a message and leaving the chat without finishing and re-entering the chat, the composer is focused and the keyboard appears. It should behave as it does when leaving the chat with an unfinished message (not editing) - not focused. 

NOTE for the devs, most likely the issue is in the `...chat.composer.effects/use-edit` and `.../use-reply` effects and we need a condition for re-entering the screen.

https://github.com/status-im/status-mobile/assets/21865759/6c0e7137-1686-48eb-8783-6b47ba0382a0

#### Expected behavior

The input is not focused when re-entering the screen.

#### Actual behavior

The input is focused when re-entering the screen.

### Reproduction

1. Start editing/replying to a message
2. Hide the composer
3. Go back to the chat list
4. Re-enter the chat
5. The composer is focused

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #17433 
fixes #17825

### Summary

Fixed issues:
1. The composer not collapsing when the user cancels editing a message (by pressing x)
2. The keyboard not hiding when the user cancel editing
3. The composer not expanding when the user starts editing a message

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Open chat
- Select own message and press "Edit message"
- The composer should expand (issue 3.)
- Press x to cancel (issues 1. 2.)

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/composer/edit/view.cljs [hunk 1]
```diff
@@ -30,20 +30,18 @@
     {:size                24
      :icon-only?          true
      :accessibility-label :edit-cancel-button
-     :on-press            (fn []
-                            (utils/cancel-edit-message state)
-                            (rf/dispatch [:chat.ui/cancel-message-edit]))
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/edit/view.cljs:35]: Are you sure dispatch event not needed?

File: src/status_im2/contexts/chat/composer/handlers.cljs [hunk 2]
```diff
@@ -87,10 +87,11 @@
                                                     max-height)
           new-height   (min new-height max-height)]
       (reset! content-height content-size)
-      (when (utils/update-height? content-size height max-height maximized?)
+      (when (utils/update-height? content-size height max-height)
         (reanimated/animate height new-height)
+        (reanimated/set-shared-value last-height new-height)
         (reanimated/set-shared-value saved-height new-height))
-      (when (= new-height max-height)
+      (when (>= new-height max-height)
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/handlers.cljs]: `new-height` should never exceed `max-height` as above we are using `new-height   (min new-height max-height)`

**Comment by OmarBasem** [comment]
Hi @clauxx, thanks for your PR

I noticed an issue when trying to edit or reply, that the composer does not animate smoothly. Notice if the composer is blurred and then when trying to focus it animates smoothly. But when trying to edit a message the composer moves up suddenly

https://github.com/status-im/status-mobile/assets/29354102/6a8dd00c-a6bb-4002-a1bf-93ece06cac7e

File: src/status_im2/contexts/chat/composer/edit/view.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im2/contexts/chat/composer/edit/view.cljs:35]: I added it to `utils/cancel-edit-message`

**Comment by clauxx** [comment]
> Hi @clauxx, thanks for your PR
> 
> I noticed an issue when trying to edit or reply, that the composer does not animate smoothly. Notice if the composer is blurred and then when trying to focus it animates smoothly. But when trying to edit a message the composer moves up suddenly
> 
>  IMG_0.3.MOV

@OmarBasem  Tried to smooth it out a bit, as it looked a bit worse when the input changed size, but the issue seems to not be related to this PR, as that was the case before it as well. This happens when focusing the input imperatively with the ref, as you can notice when replying to a message as well. We should have another issue for this, which would fix it everywhere we focus imperatively.

Also, added another fix to a bug I noticed, where the input had the wrong height after canceling edit.

File: src/status_im2/contexts/chat/composer/keyboard.cljs [hunk 3]
```diff
@@ -20,18 +21,28 @@
...
+        end-h                    (oops/oget event "endCoordinates.height")
+        diff                     (- end-h start-h)
+        max-height-diff          (- max-height diff)
+        curr-text                @text-value
+        almost-expanded?         (> (reanimated/get-shared-value height) max-height-diff)
+        ;; NOTE: the `keyboardWillChangeFrame` is dispatched sometimes when blurring (the input)
+        ;; with a diff of 103, which we don't want to react to as it causes the input to increase.
+        ;; 60 is an arbitrary number to avoid that, but still include the emoji keyboard difference
+        ;; (with some buffer).
+        smaller-than-emoji-diff? (< diff 60)]
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/keyboard.cljs]: what is `almost-expanded?` and `smaller-than-emoji-diff` ? I think there was no problem in `handle-emoji-kb-ios` ?

Comment (clauxx) [reply src/status_im2/contexts/chat/composer/keyboard.cljs]: `almost-expanded?` is the same condition we had before, just moved it inside `let`.  For `smaller-than-emoji-diff?` I tried to narrow down the condition for the emoji keyboard switch, as sometimes it would fire without toggling the emoji keyboard and as a result changing the animated height.

Comment (OmarBasem) [reply src/status_im2/contexts/chat/composer/keyboard.cljs]: @clauxx where did the value `60` come from in ` smaller-than-emoji-diff? (< diff 60)`

Comment (clauxx) [reply src/status_im2/contexts/chat/composer/keyboard.cljs]: @OmarBasem There's an inline comment above it that states it's an arbitrary value. It's somewhere in the middle between the emoji kb diff ~40 and the one we're avoiding 103.

Comment (OmarBasem) [reply src/status_im2/contexts/chat/composer/keyboard.cljs]: @clauxx the emoji kb diff will be different for different devices. Better not use such a value.

Comment (clauxx) [reply src/status_im2/contexts/chat/composer/keyboard.cljs]: That's why I left a buffer there of ~20. We could remove it and if it becomes an issue later figure out a better solution.

**Review by OmarBasem — APPROVED** [review]

**Comment by OmarBasem** [comment]
> We should have another issue for this, which would fix it everywhere we focus imperatively.

@clauxx is there an open issue for that?

**Comment by clauxx** [comment]
@OmarBasem Now it seems to animate fine 🤷 

https://github.com/status-im/status-mobile/assets/21865759/037e8832-c59e-421c-a39a-4bb4f17ffcfc

**Comment by clauxx** [comment]
Also opened two other issues I noticed while fixing this one #17827 and #17825

**Comment by OmarBasem** [comment]
> @OmarBasem Now it seems to animate fine 🤷

Okay good :)

Good work 🚀

**Comment by pavloburykh** [comment]
@clauxx thank you for your work and logging [these](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1794578387) issues. 

Please take a look at the issue related to this PR. 

### ISSUE 1 Mention turns into public key when editing a message containing mention

**Steps:** 

1. Open any chat
2. Send a message with mention
3. Open editing of the message
4. Pay attention at how mention looks like

**Actual result:** mention turns into public key 


https://github.com/status-im/status-mobile/assets/97245802/86ebba10-c179-4a85-a0c4-6e8d2d2ed012



**Expected result:** mention does not turn into pub key

**Comment by clauxx** [comment]
> @clauxx thank you for your work and logging [these](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1794578387) issues.
> 
> Please take a look at the issue related to this PR.
> 
> ### ISSUE 1 Mention turns into public key when editing a message containing mention
> **Steps:**
> 
> 1. Open any chat
> 2. Send a message with mention
> 3. Open editing of the message
> 4. Pay attention at how mention looks like
> 
> **Actual result:** mention turns into public key
> 
>  telegram-cloud-document-2-5352944957936122007.mp4 
> **Expected result:** mention does not turn into pub key

@pavloburykh Good catch! Fixed it below. 

@OmarBasem please have a look on the latest commit, as I had to move the logic from `edit-mentions` to `use-edit` to fix this. Before it was working fine cause `edit-mentions` would run after `use-edit`, but since `use-edit` state changes happen in the timeout, they switched order. Moved it to `use-edit` as it seemed unnecessary to have them separate, but lmk if that's not the case.

EDIT: also accidentally closed the issue 🤷

**Comment by pavloburykh** [comment]
@clauxx thank you for fixing ISSUE 1. 

Please, take a look at ISSUE 2

### ISSUE 2 Cursor is located at the beginning of the message when open editing (Android)

Reproducing on Android 12, Samsung Galaxy A52

**Steps:** 

1. Send a message
2. Open message editing
3. Pay attention at the cursor location

**Actual result:** cursor is located at the beginning of the message


https://github.com/status-im/status-mobile/assets/97245802/88d15fea-1db3-4f95-a561-3558fb49b526

**Expected result:** cursor should be located at the end of the message


https://github.com/status-im/status-mobile/assets/97245802/89e4d25b-1e8d-4d58-ae85-37de1a22ad25

File: src/status_im2/contexts/chat/composer/effects.cljs [hunk 4]
```diff
@@ -106,21 +106,34 @@
...
+                                    ""
+                                    input-with-mentions)
+           edit-text        (if mention? mention-text (get-in edit [:content :text]))
+           text-value-count (count @text-value)
+           inject-edit-text (fn []
+                              (reset! text-value edit-text)
+                              (reset! saved-cursor-position (if (zero? text-value-count)
+                                                              (count edit-text)
+                                                              text-value-count))
+                              (.setNativeProps ^js @input-ref (clj->js {:text edit-text})))]
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/composer/effects.cljs]: Just mentioning since you're touching this region of text, not a suggestion for change. Calling methods on atoms that are initialized as `nil` can be dangerous, we've seen people had problems with this because the ref will only be set after one render pass, so we usually need to to wrap them in `(when @input-ref ...)`.

**Review by ilmotta — APPROVED** [review]
Sorry for the delayed review @clauxx. I don't have much to add, LGTM.

**Comment by clauxx** [comment]
@pavloburykh Please have a look again! Should be fixed now.

**Comment by pavloburykh** [comment]
@clauxx thank you, ISSUE 2 is fixed. 

Unfortunately it turned out that [ISSUE 1](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1794761472)is still reproducible. 

It is not reproducible every time and for some reason it is easier for me to reproduce on IOS (iPhone X, IOS 16.1) though I also sometimes reproducing on Android (Samsung Galaxy A52, Android 12)

**Video from IOS:**


https://github.com/status-im/status-mobile/assets/97245802/1d352c26-bc0e-4b1f-aec9-c2d4489dbe43

**Video from Android:** at the end of the video after several tries I have managed to reproduce mention turning into pub key


https://github.com/status-im/status-mobile/assets/97245802/42e00064-7382-4c9c-8ed5-7050ee3004f4

**Comment by pavloburykh** [comment]
### ISSUE 3 Sometimes composer elements overlap input field with text when open editing (IOS)

Reproduced only on IOS (iPhone X, IOS 16.1)

**Steps:** 

1. Send multiline message
2. Perform scroll so that the part of multiline message is located behind the composer
3. Longtap on message
4. Select Edit
5. See if composer looks correct

**Actual result:** sometimes composer appears to be broken and its elements overlap input field with text

photo_2023-11-07 16 43 05

https://github.com/status-im/status-mobile/assets/97245802/1ead7b60-6bda-4a79-a523-8a65bb061309

**Comment by clauxx** [comment]
@pavloburykh Can you check if issues 1 and 3 are fixed please? 

Also found another issue that was there before this PR. When the composer is maximized and you're entering text into the new line, for the first 2-3 characters, the text jumps up and after ~3rd character the cursor/text comes back. I could only reproduce it on iOS 17.x though. You can see the behaviour in the video below.

https://github.com/status-im/status-mobile/assets/21865759/74dcc752-002c-45b0-ac83-de2dcb99adaa

**Comment by clauxx** [comment]
@pavloburykh there's small issue with the commits you rebased. They're not verified, as in the commits are not signed, so they can't be merged. There's a [doc](https://github.com/status-im/status-mobile/blob/233d1b3261f76067c93e51b84acbd1a9c6382d49/doc/starting-guide.md#configure-gpg-keys-for-signing-commits) on how to set it up, but if you have questions or need help with that let me know. After that when you rebase them again, they would appear with a `Verified` tag next to the commit hash/id.

**Comment by pavloburykh** [comment]
> @pavloburykh there's small issue with the commits you rebased. They're not verified, as in the commits are not signed, so they can't be merged. There's a [doc](https://github.com/status-im/status-mobile/blob/233d1b3261f76067c93e51b84acbd1a9c6382d49/doc/starting-guide.md#configure-gpg-keys-for-signing-commits) on how to set it up, but if you have questions or need help with that let me know. After that when you rebase them again, they would appear with a `Verified` tag next to the commit hash/id.

hmm. I didn't expect that commits that were added from develop during rebase are not signed. The problem is that we need to keep PR rebased during testing and running e2e. So I performed rebase directly from github (not manually) using the build in feature below because PR was 10 commits behind develop. 
#17611  move status-im utils universal-links core by flexsurfer · Pull Request #17855 · status-im:status-mobile 2023-11-09 19-54-37

**Comment by pavloburykh** [comment]
We used to rebase PRs this way and seems everything was fine before.

**Comment by pavloburykh** [comment]
When you will rebase the branch before merge should it fix current issue with unverified commits, correct?

**Comment by clauxx** [comment]
@pavloburykh So when you use `Update with rebase`, Github add your account as the co-author of all the commits from the PR. The issue is that your account doesn't have a GPG key associated with it, which makes all the commits in the PR un-mergeable, as you can see below. I discussed with @VolodLytvynenko seems like he managed to set it up, so maybe he could help.

image

> When you will rebase the branch before merge should it fix current issue with unverified commits, correct?

Not sure, will have to see when somebody pushes to develop again. Don't know if during the rebase Github will keep you as co-author and keep it as unverified, but if it wasn't an issue before then maybe it's ok. But even so, would be good to have everybody who adds/rebases commits to use signed commits for that, otherwise would have to do it manually (which can get annoying sometimes when the PR is open for long) or wait for develop updates to do it through Github.

**Comment by pavloburykh** [comment]
> Not sure, will have to see when somebody pushes to develop again.

ok, will see. In my case I have GPG key set up. I have used to perform manual rebases and also commited e2e changes into develop and everything worked fine. Maybe there is some issue with association of my GPG key when I perform rebase directly from github.

**Comment by pavloburykh** [comment]
And thank you for the fixes and the issue with text jumping in composer that pointed out. I will check everything tomorrow and provide a feedback.

**Comment by pavloburykh** [comment]
Hey @clauxx 

Regarding [ISSUE 1](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1794761472) - it is much better now but public key is still visible for a moment when opening message editing. See video below from IOS


https://github.com/status-im/status-mobile/assets/97245802/a8411b1a-e7b1-4c52-987d-f95d950a1e98

**Comment by pavloburykh** [comment]
Also, there is another issue related to cancelling editing which has not been described in the initial ticket https://github.com/status-im/status-mobile/issues/17433 It would be great to take care of it in scope of this PR as well. WDYT @clauxx 

### ISSUE 4 The fold down editing composer expands unexpectedly when cancelling editing

**Steps:** 

1. Send a long multiline message
2. Open message editing
3. Fold down the composer
4. Tap [x] button to cancel editing
5. Observe the composer behaviour 

**Actual result:** empty composer gets expanded. Faded background above the composer


https://github.com/status-im/status-mobile/assets/97245802/4fee3d3d-8337-41ea-a175-909f4732a249

**Expected result:** composer should not expand.

**Comment by pavloburykh** [comment]
@clauxx I see there is one fore issue described in [this](https://github.com/status-im/status-mobile/issues/17433#issuecomment-1745284625) comment. Did you have a chance to look at it. Let me know if you prefer to log it separately. 

### ISSUE 5 Wrong composer hight after sending image with long description (IOS)

Reproducing on IOS 16.7.2 iPhoneX

**Steps:** 

1. Paste a long text into composer
2. Add an image
3. Send the message
4. Background app
5. Return from background
6. Pay attention at the composer size

**Actual result:** composer hight is wrong  

photo_2023-11-10 12 25 22

https://github.com/status-im/status-mobile/assets/97245802/7785f040-1b89-46ed-9cde-1c9834e9e2f4

**Comment by pavloburykh** [comment]
> Also found another issue that was there before this PR. When the composer is maximized and you're entering text into the new line, for the first 2-3 characters, the text jumps up and after ~3rd character the cursor/text comes back. I could only reproduce it on iOS 17.x though. You can see the behaviour in the video below. 

Unfortunately failed to reproduce this issue on my IOS 16.7.2 iPhone X. We need to log with mentioning IOS 17.x in the issue description. Will do that.

**Comment by clauxx** [comment]
@pavloburykh I think will be best to split these into separate issues, as long as there are no regressions. What do you think?

**Comment by pavloburykh** [comment]
> @pavloburykh I think will be best to split these into separate issues, as long as there are no regressions. What do you think?

Do you mean all of them? 

Cause [this](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1805442058) one is definitely regression. What do you think about trying to improve this behaviour in scope of this PR? 

At the same time I agree that the rest of the issues can be logged separately. Will do that as soon as this PR is merged.

**Comment by clauxx** [comment]
> > @pavloburykh I think will be best to split these into separate issues, as long as there are no regressions. What do you think?
> 
> Do you mean all of them?
> 
> Cause [this](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1805442058) one is definitely regression. What do you think about trying to improve this behaviour in scope of this PR?
> 
> At the same time I agree that the rest of the issues can be logged separately. Will do that as soon as this PR is merged.

Yeah, I meant the ones that are not regressions. Will look at the first issue later today/over the weekend, but when working on it don't remember it behaving this way 😞. Will try on some other devices I guess.

**Comment by OmarBasem** [comment]
> > @clauxx thank you for your work and logging [these](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1794578387) issues.
> > Please take a look at the issue related to this PR.
> > ### ISSUE 1 Mention turns into public key when editing a message containing mention
> > **Steps:**
> > 
> > 1. Open any chat
> > 2. Send a message with mention
> > 3. Open editing of the message
> > 4. Pay attention at how mention looks like
> > 
> > **Actual result:** mention turns into public key
> > telegram-cloud-document-2-5352944957936122007.mp4
> > **Expected result:** mention does not turn into pub key
> 
> @pavloburykh Good catch! Fixed it below.
> 
> @OmarBasem please have a look on the latest commit, as I had to move the logic from `edit-mentions` to `use-edit` to fix this. Before it was working fine cause `edit-mentions` would run after `use-edit`, but since `use-edit` state changes happen in the timeout, they switched order. Moved it to `use-edit` as it seemed unnecessary to have them separate, but lmk if that's not the case.
> 
> EDIT: also accidentally closed the issue 🤷

@clauxx Sorry missed the mention.
There is no problem moving that logic to `use-edit` 👍

**Comment by churik** [comment]
Found one regression issue that wasn't captured before:
### ISSUE 6: edited message content in composer is reset when you re-open the chat

**Steps:**
1) Send message
2) Start to edit it
3) Go back and reopen the chat

**Expected result:**
Text in composer is unchanged 

**Actual result:**
the text gets back to the initial message content

https://github.com/status-im/status-mobile/assets/4557972/fbff623c-d838-4374-805e-620458f65b4c

**OS:** IOS, Android

**The issue is not reproducible with the current nightly.**
Video from nightly build:

https://github.com/status-im/status-mobile/assets/4557972/68fcd299-9220-4fce-adf4-c61da7c1e7f3

**Comment by clauxx** [comment]
@churik @pavloburykh @OmarBasem 

Fixed issue 6 and (hopefully) issue 1 is also fixed. It's a bit difficult to reproduce cause it was happening kinda randomly, but couldn't reproduce it at all after the fix. 

Additionally, noticed there was an issue with hiding the keyboard when closing a reply, similar to what we had here. Dealt with it here cause it was a quick fix.

@ibrkhalil There was a release blocker issue here for which I needed changes from [your PR](https://github.com/status-im/status-mobile/pull/17882), so I merged it here to make the QA process quicker. Hope that's fine by you ☺️.

And lastly, remembered that this PR also fixed another composer issue: https://github.com/status-im/status-mobile/issues/17361

**Comment by churik** [comment]
@clauxx  @ibrkhalil 
thank you for work.
I believe the composer's behavior now became a way more reliable, but https://github.com/status-im/status-mobile/issues/17361 is not fixed there and regression about [ISSUE 1](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1794761472) is reproducible for me.

https://github.com/status-im/status-mobile/issues/17361 video:

https://github.com/status-im/status-mobile/assets/4557972/553f0d7c-abb0-43d9-9cd1-41d5e3c74959

[ISSUE 1](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1794761472)  video: 

https://github.com/status-im/status-mobile/assets/4557972/f1db5b01-b52e-4285-bcfc-a33529142db2

both issues are very nice to fix, but not critical for PR. I can create them separately and we'll fix it in the next release, what do you think?

**Comment by clauxx** [comment]
@churik yepp, i guess i musunderstood the first one with the composer height. The issue 1 is weird, i think it makes sense to fix them separately. Can you assign them to me please?

**Comment by churik** [comment]
Please, cherry-pick your commit in release branch too.
Thank you, I created https://github.com/status-im/status-mobile/issues/17929  and assigned it to you

**Comment by clauxx** [comment]
@churik Can it be merged?

**Comment by churik** [comment]
@clauxx can you cherry-pick it to release branch?

**Comment by clauxx** [comment]
@churik on it. Have some issue with my GPG keys that I'm trying to fix since an hour, so can't push the cherry-picked commit. Will check with Andrea if he can do the cherrypicking on his side.

**Comment by clauxx** [comment]
@churik it's done!
