### PR TITLE
fix: no routes are found in case of valid amount in fiat is entered

### LINKED ISSUE #18561: No routes are found in case of valid amount in fiat is entered
I believe the root-cause of the bug is that after switching input to fiat the app still validates this amount as if we would enter amount in crypto.  

**Steps:** 

1. Open sending token screen
2. Switch to input in fiat
3. Enter the amount that would be valid in fiat but not valid in crypto
4. See if routes are found

**Actual result:** No routes are found. 

https://github.com/status-im/status-mobile/assets/97245802/f6b9d92e-faf7-4eca-b0ae-6914766d4172

**Expected result:** routes are found

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #19999: "underfined is not a function" error is shown after attempt to find routes
### Problem:
When attempting to find routes after recovering the user with some assets, an "undefined is not a function" error is shown. Unfortunately, the exact steps to reproduce this issue were not determined, hope the logs might help

### Steps:
1. Recover the user with some assets
2. Go to send assets flow
3. Enter long value (ex: 0.0000001) into routes searching screen

### Actual result:
 "Undefined is not a function" error is shown after attempting to find routes.

https://github.com/status-im/status-mobile/assets/52490791/fc130f6c-4cd4-4064-b176-5b205bd746ec

### Expected result:
No errors should be shown.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (4).zip](https://github.com/status-im/status-mobile/files/15296706/logs.4.zip)

### ENV:
Nightly 13 May 2024

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18561 
fixes #19999

### Summary

This PR fixes a bug that makes no routes being fetched when the users switch the input mode to display values in fiat and a valid amount in fiat is entered. Also fixed some minor but noticeable bugs that appeared after fixing the main bug:

- Visual overflow of the suffix text of the input when swapping mode to fiat and the number is too big. Needed to refactor a bit the views and styles of Token Input component.
- Don't allow the user to use more decimals than the token supports.
- Fiat character symbol was not showing in the conversion.
- Fiat character symbol was not used when showing the max amount.
- Many trailing zeroes issues when leading with large numbers.
- Routes being fetched when swapping to fiat, and vise versa

#### Demo

https://github.com/status-im/status-mobile/assets/18485527/c67ae017-b134-4813-b716-99ba9167ef8f

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Login
- Go to wallet
- Select an account
- Tap on Send button
- Select an asset where the user has funds on
- Tap on switch button on the input to display values in fiat
- Enter a valid amount in fiat
- Wait for routes to be loaded
- Verify correct behavior of input and routes loading

status: ready

### CODE REVIEW

File: src/quo/components/wallet/token_input/style.cljs [hunk 1]
```diff
@@ -12,30 +12,22 @@
   {:padding-horizontal 20
```
Comment (OmarBasem) [inline src/quo/components/wallet/token_input/style.cljs:12]: I am curious what are the styling changes for as I don't see ui-related problem in the issue description

**Comment by OmarBasem** [comment]
Hey @briansztamfater, can you please review your code a little bit to explain are the other bugs being fixed?

Also would be good if you can add a video to PR description.

**Comment by J-Son89** [comment]
🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  20000 pr's 🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉

File: src/utils/number.cljs [hunk 2]
```diff
@@ -29,3 +30,13 @@
   if `num` exceeds a given bound, then returns the bound exceeded."
   [number lower-bound upper-bound]
   (max lower-bound (min number upper-bound)))
+
+(defn remove-trailing-zeroes
```
Comment (J-Son89) [inline src/utils/number.cljs:34]: probably should add a test to cover this functionality? 🤔 

is this really core "numbers" or is it more specific to the wallet also? 🤔

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 3]
```diff
@@ -202,12 +202,15 @@
           :disabled-chain-ids disabled-from-chain-ids})
         show-routes? (not-empty sender-network-values)]
     (rn/use-effect
-     #(when (and active-screen? (> (count token-available-networks-for-suggested-routes) 0))
-        (fetch-routes input-value valid-input? 2000))
+     (fn []
+       (when (and active-screen?
+                  (> (count token-available-networks-for-suggested-routes) 0)
+                  (not lock-fetch-routes?))
+         (fetch-routes value valid-input? 2000)))
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/routes/view.cljs]: btw what is 2000 here? perhaps it's better to put this in a named var, or instead use a map for the arguments so it's obvious of the uses without looking at the function

File: src/quo/components/wallet/token_input/view.cljs [hunk 4]
```diff
@@ -92,36 +84,49 @@
                                         (oops/oget "nativeEvent.selection")
                                         (js->clj :keywordize-keys true)
                                         (on-selection-change))))]
-    (fn [{:keys [token customization-color show-keyboard? crypto? currency value error? selection]
+    (fn [{:keys [token customization-color show-keyboard? crypto? currency value error? selection
+                 handle-on-swap]
           :or   {show-keyboard? true}}]
```
Comment (J-Son89) [inline src/quo/components/wallet/token_input/view.cljs:85]: it can be quite hard to distinguish what changes you have actually made in code blobs like this. 
It would be nice if you could leave some comments to help find the changes :)

File: src/quo/components/wallet/token_input/view.cljs [hunk 5]
```diff
@@ -92,36 +84,49 @@
...
+         [rn/view {:style (style/input-container window-width)}
+          [rn/pressable
+           {:style    style/text-input-container
+            :on-press focus-input}
+           [rn/text-input
+            (cond-> {:style                    (style/text-input theme error?)
+                     :placeholder-text-color   (style/placeholder-text theme)
+                     :auto-focus               true
+                     :ref                      set-ref
+                     :placeholder              "0"
```
Comment (J-Son89) [inline src/quo/components/wallet/token_input/view.cljs:104]: is this placeholder correct? Probably should be an i81n label so it can be set.

File: src/status_im/constants.cljs [hunk 6]
```diff
@@ -513,3 +513,7 @@
 (def ^:const community-joined-notification-type "communityJoined")
 
 (def ^:const default-telemetry-server-url "https://telemetry.status.im")
+
+(def currency-symbols
```
Comment (J-Son89) [inline src/status_im/constants.cljs]: hmm, do we not already have currencies already defined somewhere? 🤔 
I don't think we need to start adding this list. What exactly did you need it for? 
cc @smohamedjavid

File: src/quo/components/wallet/token_input/view.cljs [hunk 7]
```diff
@@ -92,36 +84,49 @@
...
-                    :on-selection-change      handle-selection-change
-                    :selection                (clj->js selection)}
-             controlled-input?       (assoc :value value)
-             (not controlled-input?) (assoc :default-value value-internal))]]
-         [token-label
-          {:theme theme
-           :text  (if crypto? token currency)
-           :value (if controlled-input? value value-internal)}]]))))
+      (let [theme        (quo.theme/use-theme)
+            window       (rn/get-window)
```
Comment (J-Son89) [inline src/quo/components/wallet/token_input/view.cljs]: nit:
why not?
`window-width (:width (rn/get-window))`

File: src/quo/components/wallet/token_input/style.cljs [hunk 8]
```diff
@@ -12,30 +12,22 @@
...
 
-(def text-input-container
-  {:position :absolute
-   :top      0
-   :bottom   0
-   :left     40 ; token image size + margin
-   :right    0})
+(defn input-container
+  [window-width]
+  {:width        (- window-width 120)
```
Comment (J-Son89) [inline src/quo/components/wallet/token_input/style.cljs:28]: what is 120 related to?

File: src/utils/number.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/utils/number.cljs:34]: Well, this function was already in a common file for wallet, but moved to a utils as it is a general purpose function and needed to use it un token input component

Comment (J-Son89) [reply src/utils/number.cljs:34]: Good point 😅

File: src/quo/components/wallet/token_input/view.cljs (hunk 7 above)
Comment (briansztamfater) [reply src/quo/components/wallet/token_input/view.cljs]: Why not? :D
Will modify

File: src/status_im/constants.cljs (hunk 6 above)
Comment (briansztamfater) [reply src/status_im/constants.cljs]: Hmmm I found one in `quo.foundations.common`. Not sure if we should use it from status-im namespace?

File: src/quo/components/wallet/token_input/style.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/quo/components/wallet/token_input/style.cljs:12]: Well, the main issue doesn't specify UI bugs, but after fixing the main issue, some other issues started to be more noticeable. For instance:

- Visual overflow of the suffix text of the input when swapping mode to fiat and the number is too big. Needed to refactor a bit the views and styles of Token Input component.
- Don't allow the user to use more decimals than the token supports.
- Fiat character symbol was not showing in the conversion.
- Fiat character symbol was not used when showing the max amount.
- Many trailing zeroes issues when leading with large numbers.
- Routes being fetched when swapping to fiat, and vise versa

Added this in the description, will add some comments also to specify those changes.

File: src/quo/components/wallet/token_input/style.cljs
Comment (briansztamfater) [inline src/quo/components/wallet/token_input/style.cljs:1]: There was a bug that makes a visual overflow of the suffix text of the input when swapping mode to fiat and the number is too big. So I refactored a bit this component to fix those issues.

File: src/quo/components/wallet/token_input/style.cljs (hunk 8 above)
Comment (briansztamfater) [reply src/quo/components/wallet/token_input/style.cljs:28]: Token icon width + swap button width + spacing.

I will add a comment to make it more clear.

File: src/quo/components/wallet/token_input/view.cljs [hunk 9]
```diff
@@ -12,15 +12,17 @@
...
 
 (defn fiat-format
   [currency num-value conversion]
   (str (get common/currency-label currency) (.toFixed (* num-value conversion) 2)))
 
 (defn crypto-format
   [num-value conversion crypto-decimals token]
-  (str (.toFixed (/ num-value conversion) (or crypto-decimals 2))
+  (str (number/remove-trailing-zeroes
+        (.toFixed (/ num-value conversion) (or crypto-decimals 2)))
```
Comment (briansztamfater) [inline src/quo/components/wallet/token_input/view.cljs:24]: Numbers can be of 0.000100000, so need to remove trailing zeroes

File: src/quo/components/wallet/token_input/view.cljs [hunk 10]
```diff
@@ -92,36 +84,49 @@
...
+             :text  (if crypto? token currency)
+             :value (if controlled-input? value value-internal)}]]]
+         [button/button
+          {:icon                true
+           :icon-only?          true
+           :size                32
+           :on-press            handle-on-swap
+           :type                :outline
+           :accessibility-label :reorder}
+          :i/reorder]]))))
```
Comment (briansztamfater) [inline src/quo/components/wallet/token_input/view.cljs:121]: Moved button to this view, not sure why it was outside of it, but refactored to fix `token-label` overflowing when the input is too large.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 11]
```diff
@@ -6,25 +6,32 @@
...
   [amount currency]
   (str amount
        " "
        (some-> currency
                name
                string/upper-case)))
 
+(defn- make-limit-label-fiat
+  [amount currency-symbol]
+  (str currency-symbol amount))
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:35]: Formatting for fiat was incorrect.

Previously it showed like: `100 EUR`, now it should show like `€100`

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 12]
```diff
@@ -199,22 +230,40 @@
...
+                                       (make-limit-label-fiat current-limit
+                                                              (get constants/currency-symbols
+                                                                   fiat-currency)))})
            :conversion      conversion-rate
            :show-keyboard?  false
-           :value           (controlled-input/input-value input-state)
-           :on-swap         #(reset! crypto-currency? %)
+           :value           input-amount
+           :on-swap         (fn [swap-to-crypto-currency?]
+                              (set-just-toggled-mode? true)
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:306]: Currently, when input value changes and the value is valid, routes are fetched. When swapping, the input value changes, the value is valid because it is still the same value in crypto, but routes should not be fetched.

This flag is used to prevent routes being fetched when swapping.

File: src/quo/components/wallet/token_input/style.cljs (hunk 8 above)
Comment (J-Son89) [reply src/quo/components/wallet/token_input/style.cljs:28]: You can also just put 120 in a named def

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 13]
```diff
@@ -248,11 +303,22 @@
...
            :on-press             (fn [c]
-                                   (when-not loading-routes?
-                                     (set-input-state #(controlled-input/add-character % c))))
+                                   (let [new-text      (str input-amount c)
+                                         max-decimals  (if @crypto-currency? crypto-decimals 2)
+                                         regex-pattern (str "^\\d*\\.?\\d{0," max-decimals "}$")
+                                         regex         (re-pattern regex-pattern)]
+                                     (when (and (not loading-routes?)
+                                                (re-matches regex new-text))
+                                       (debounce/clear-all)
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:380]: We need to clear the debounce queue to prevent unnecessary routes fetching.

File: src/quo/components/wallet/token_input/view.cljs (hunk 5 above)
Comment (briansztamfater) [reply src/quo/components/wallet/token_input/view.cljs:104]: I think it is fine, the placeholder should be "0" in this case as this is the token amount input

File: src/quo/components/wallet/token_input/view.cljs (hunk 4 above)
Comment (briansztamfater) [reply src/quo/components/wallet/token_input/view.cljs:85]: The main reason is this one https://github.com/status-im/status-mobile/pull/20000/files#r1601228153

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 14]
```diff
@@ -94,91 +102,111 @@
...
+            confirm-disabled?                           (or (nil? route)
+                                                            (empty? route)
+                                                            (string/blank? input-amount)
+                                                            (<= input-num-value 0)
+                                                            (> input-num-value current-limit))
+            amount                                      (if @crypto-currency?
+                                                          input-amount
+                                                          (number/remove-trailing-zeroes
+                                                           (.toFixed (/ input-amount conversion-rate)
+                                                                     crypto-decimals)))
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: Even if we are in "fiat mode", we need to calculate the equivalent in crypto token because it is what we are actually sending / bridging. Fiat values are just for visual representation.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 15]
```diff
@@ -94,91 +102,111 @@
...
+            send-amount                                 (rf/sub [:wallet/wallet-send-amount])
+            amount-text                                 (str (.toFixed (js/parseFloat send-amount)
+                                                                       (min token-decimals 6))
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: This is the amount string we show to the user. We cap the decimals to 6 to not overflow.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 16]
```diff
@@ -188,6 +216,9 @@
          (fn []
            (set-input-state #(controlled-input/set-upper-limit % current-limit)))
          [current-limit])
+        (rn/use-effect
+         #(when input-error (debounce/clear-all))
+         [input-error])
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:280]: This is a bit out of scope, we can move it to another PR, but I think it is fine to leave it here as it includes many minor fixes for the input.

Let's say user wants to send SNT, the balance is 10 SNT.
Then the user starts typing "1", causing an event to fetch routes is debounced to dispatch in 2 seconds.
Then the user types another "1", now the input shows "11". But the user has only 10 SNT, so the input enters in an error state.
Because the first event was already in the dispatch queue, routes will be fetched with amount of "1" even if the user continued typing an invalid amount.

So, calling `debounce/clear-all` fixes that.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 17]
```diff
@@ -248,11 +303,22 @@
            :left-action          :dot
            :delete-key?          true
            :on-press             (fn [c]
-                                   (when-not loading-routes?
-                                     (set-input-state #(controlled-input/add-character % c))))
+                                   (let [new-text      (str input-amount c)
+                                         max-decimals  (if @crypto-currency? crypto-decimals 2)
+                                         regex-pattern (str "^\\d*\\.?\\d{0," max-decimals "}$")
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:376]: When typing, we limit the input to allow decimals up to the decimals amount of the token or 2 if it is a fiat amount.

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 3 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/routes/view.cljs]: It is an arbitrary time for debouncing-dispatch fetch routes event. Here https://github.com/status-im/status-mobile/pull/19100 we changed it to 2000, I can add it in a named var of course.

**Comment by briansztamfater** [comment]
@J-Son89 @OmarBasem added more context all over the PR, also improved the description describing related issues that were fixed here and added a demo video

File: src/quo/components/wallet/token_input/view.cljs (hunk 9 above)
Comment (J-Son89) [reply src/quo/components/wallet/token_input/view.cljs:24]: a test maybe?

File: src/status_im/constants.cljs (hunk 6 above)
Comment (J-Son89) [reply src/status_im/constants.cljs]: This I'm not sure of, but we get the symbol from the sub I think, which comes from Status-Go. 
I don't think we should add this map tbh, probably need to nuke the one in quo.foundations.common too

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 3 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/send/routes/view.cljs]: I think just a map for params explains it.
```
(fetch-routes {:value value 
                         :valid-input? valid-input?
                         :debounce-ms 2000})
```

**Review by J-Son89 — APPROVED** [review]
looks nice and smooth in the video ✨

File: src/quo/components/wallet/token_input/style.cljs (hunk 8 above)
Comment (OmarBasem) [reply src/quo/components/wallet/token_input/style.cljs:28]: What if we change the token icon width, the styling here will probably break. I think we need to have those 3 styles defined (and be used in the relevant components), and then the sum defined.

Or maybe there could be another approach without using that number here

File: src/quo/components/wallet/token_input/view.cljs (hunk 9 above)
Comment (OmarBasem) [reply src/quo/components/wallet/token_input/view.cljs:24]: Would be good to add a test for the `remove-trailing-zeroes` util

File: src/quo/components/wallet/token_input/view.cljs [hunk 18]
```diff
@@ -92,36 +84,49 @@
...
-         [token-label
-          {:theme theme
-           :text  (if crypto? token currency)
-           :value (if controlled-input? value value-internal)}]]))))
+      (let [theme        (quo.theme/use-theme)
+            window       (rn/get-window)
+            window-width (:width window)]
+        [rn/pressable
+         {:style    {:width          "100%"
+                     :flex-direction :row}
```
Comment (OmarBasem) [inline src/quo/components/wallet/token_input/view.cljs:90]: Could be moved to style file

File: src/status_im/constants.cljs (hunk 6 above)
Comment (OmarBasem) [reply src/status_im/constants.cljs]: I think they were added temporarily. We need to fetch currencies data from status-go (probably settings team will work on that)

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 19]
```diff
@@ -199,22 +230,40 @@
...
-           :value           (controlled-input/input-value input-state)
-           :on-swap         #(reset! crypto-currency? %)
+           :value           input-amount
+           :on-swap         (fn [swap-to-crypto-currency?]
+                              (set-just-toggled-mode? true)
+                              (reset! crypto-currency? swap-to-crypto-currency?)
+                              (set-input-state
+                               #(controlled-input/set-input-value
+                                 %
+                                 (let [value     (controlled-input/input-value %)
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: This close usages of `%` can be confusing

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 17 above)
Comment (OmarBasem) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:376]: Probably better to refactor this regex pattern to constants file

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 3 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/routes/view.cljs]: I think this number 2000 is used in multiple places, we can refactor it to a constants file

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 20]
```diff
@@ -94,91 +102,111 @@
...
+                                                         [:wallet/wallet-send-sender-network-values])
+            suggested-routes                            (rf/sub [:wallet/wallet-send-suggested-routes])
+            routes                                      (when suggested-routes
+                                                          (or (:best suggested-routes) []))
+            no-routes-found?                            (and
+                                                         (every-network-value-is-zero?
+                                                          sender-network-values)
+                                                         (not (nil? routes))
+                                                         (not loading-suggested-routes?))
+            input-error                                 (controlled-input/input-error input-state)]
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: I mentioned this recently, but just to draw attention to how it keeps getting longer. We have subs, dispatch events, utils, and defined values mixed together. We need to put some thought into cleaning it up a bit @J-Son89 @ulisesmac

**Review by OmarBasem — COMMENTED** [review]
@briansztamfater thanks for adding clarifications to your code. Left some comments 👍

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 11 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs:35]: I think that depends on the language/region?

I've seen in some places in Europe they use `100 €` and in USA and Mexico we use `€ 100`.

So we might need to move this to translations

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 19 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: Yes, better to give a name to that var.

@briansztamfater I prefer to follow the approach @ilmotta  once shared with me: use the shorthand (`#()`) only when its a simple one liner function, otherwise prefer to use `(fn [])` because it's clearer what is received or even if it's empty it's clearer than looking for a `%` in the function.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 20 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: @OmarBasem 
Sorry, I don't get it, do you mean that we have events, subs, utils and `def`s defined in the same file?

File: src/quo/components/wallet/token_input/view.cljs [hunk 21]
```diff
@@ -60,18 +62,8 @@
...
-   [rn/text-input
-    {:max-length  12
-     :style       style/text-input-dimensions
-     :editable    false
-     :placeholder "0"
-     :opacity     0
-     :value       value}]
-   [token-name-text theme text]])
+  [{:keys [theme text]}]
+  [token-name-text theme text])
```
Comment (ulisesmac) [inline src/quo/components/wallet/token_input/view.cljs]: This component seems just like a wrapper for `token-name-text` do we need it? maybe we can use `token-name-text` directly?

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 20 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: I agree there are lots of var definitions in this file, it is getting bigger and it deserves a refactor.
Not sure if we want to refactor now? Maybe it is too risky as it is a complex and core component for wallet, I would vote for refactor once we have a stable version so we can easily revert commits in case we break things while refactoring. But I am also open to listen to other opinions, no strong opinion on this tbh.

File: src/utils/number.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/utils/number.cljs:34]: Now that we have a focus on this function, maybe we can simplify the logic a bit?
```clojure
(let [[integral fractional] (string/split (str num) #"\.")
      fractional-fixed      (some-> fractional
                              (string/replace #"0+$" ""))]
  (if fractional
    (str integral "." fractional-fixed)
    integral))
```

I think in this implementation is clearer what we do to the number :eyes:  wdyt?

**Review by ulisesmac — APPROVED** [review]
Hey @briansztamfater thanks for the PR and for addressing the bugs found!

The video and code look really good besides a couple of small comments.
 :100:
Maybe we want to ask QA to confirm the bugs have been properly solved

File: src/status_im/constants.cljs (hunk 6 above)
Comment (smohamedjavid) [reply src/status_im/constants.cljs]: @briansztamfater @J-Son89 

We use the existing list from `legacy.status-im.utils.currency` ns for currency list display and selection. But, it's needs to be fetched from `status-go` as @OmarBasem mentioned, to serve as a single point of truth for both Mobile and Desktop.

I believe those APIs are `wallet_getCachedCurrencyFormats` and `wallet_fetchAllCurrencyFormats`.

> (probably settings team will work on that)

Not sure about that. 😅

Comment (briansztamfater) [reply src/status_im/constants.cljs]: I ended up using `:profile/currency-symbol` and `:profile/currency` subs. No need for those maps from what I've seen, so I also removed `quo.foundations.common` file which only has that definition and was only used on Token Input.

Comment (J-Son89) [reply src/status_im/constants.cljs]: Thank you @briansztamfater

File: src/quo/components/wallet/token_input/view.cljs (hunk 7 above)
Comment (briansztamfater) [reply src/quo/components/wallet/token_input/view.cljs]: Done

**Comment by yevh-berdnyk** [comment]
> ## 87% of end-end tests have passed


e2e failures are not related to the PR

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 22]
```diff
@@ -127,112 +134,121 @@
...
+            receiver-networks (rf/sub [:wallet/wallet-send-receiver-networks])
+            receiver-preferred-networks (rf/sub
+                                         [:wallet/wallet-send-receiver-preferred-networks])
+            receiver-preferred-networks-set (set receiver-preferred-networks)
+            sending-to-unpreferred-networks? (not (every? (fn [receiver-selected-network]
+                                                            (contains?
+                                                             receiver-preferred-networks-set
+                                                             receiver-selected-network))
+                                                          receiver-networks))
+            input-error (controlled-input/input-error input-state)]
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: > @OmarBasem
Sorry, I don't get it, do you mean that we have events, subs, utils and defs defined in the same file?

@ulisesmac I mean this long list of definitions which is a mix of event, subs, utils, and values, could introduce bugs in the future and could be harder to debug. We need to have more separation of concerns here

**Comment by pavloburykh** [comment]
Hey @briansztamfater! Thanks for the PR. I see that you have pushed recently some changes. Is that just rebasing or additional changes?

**Comment by briansztamfater** [comment]
> Hey @briansztamfater! Thanks for the PR. I see that you have pushed recently some changes. Is that just rebasing or additional changes?

Hey @pavloburykh, just rebasing, PR can be tested

**Comment by pavloburykh** [comment]
@briansztamfater thanks for the fixes. PR is ready for merge.
