### PR TITLE
Fixes for Request to Join Community bottom sheet

### LINKED ISSUE #16117: Community Overview - Request to join bottom sheet - UI issues
Remove info box

Movie_Recording_2023-05-30_16-25-14

 - "Joining the community will reveal your public addresses to the node owner ", should be visible at the bottom of communities
 

 Communities_for_Mobile_Figma_2023-05-30_16-27-13

 - cancel, request to join buttons margin revisited.

designs:
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7644-599205&t=Tj6dedxK42Xfuh36-4

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/16117

### Summary

This PR fixes a bunch of UI issues to match what's in [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1733-125697&t=3ssa500fwGvUqiTL-0).

- [x] Fix typo in the Request to Join Communities' text.
- [x] Fix bottom sheet handle colors. They had the incorrect transparency.
- [x] Fix incorrect *Request to Join* bottom sheet top margin.
- [x] Remove touchable opacity from `disclaimer` quo2 component. It should use touchable without feedback. This also fixes the problem on the on onboarding flow since both screens use the same disclaimer component.
- [x] Add missing final disclaimer after accept/reject buttons.

### Notes

[Figma > Mobile App > Communities for Mobile](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1733-125697&t=3ssa500fwGvUqiTL-0) is outdated and will be changed soon, but what's important for this PR is that the final disclaimer `Joining the community will reveal your public addresses to the node owner` must always be shown, with/without token gated communities.

After this PR I will create a separate issue related to changes that will be needed to make the `Request to Join` button work with upcoming changes in status-go that the desktop team is working on.

Also don't worry about the captchas, we won't use them and Figma will soon be updated.

### Before

<table>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

### After

<table>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

### Steps to test

- Create a community and invite Alice.
- Log in as Alice and request to join the community. A bottom sheet will be displayed.

status: ready

### CODE REVIEW

File: src/status_im2/contexts/communities/actions/request_to_join/view.cljs [hunk 1]
```diff
@@ -28,19 +28,15 @@
                     requested-to-join-at]} (rf/sub [:get-screen-params])
             pending?                       (rf/sub [:communities/my-pending-request-to-join id])
             is-open?                       (not= 3 (:access permissions))]
```
Comment (jo-mut) [inline src/status_im2/contexts/communities/actions/request_to_join/view.cljs]: could be just `open?` instead

File: src/quo2/components/selectors/disclaimer/view.cljs [hunk 2]
```diff
@@ -6,7 +6,7 @@
 
 (defn view
   [{:keys [checked? blur? accessibility-label container-style on-change]} label]
-  [rn/touchable-opacity
+  [rn/touchable-without-feedback
    {:on-press            on-change
     :accessibility-label "disclaimer-touchable-opacity"}
```
Comment (jo-mut) [inline src/quo2/components/selectors/disclaimer/view.cljs]: could be 
```clojure 
:disclaimer-touchable-opacity

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/communities/actions/community_rules_list/view.cljs [hunk 3]
```diff
@@ -30,28 +29,18 @@
...
+     :weight :medium
+     :size   :paragraph-2}
+    (str index ". ")]
+   [quo/text
+    {:style               style/community-rule-text
+     :accessibility-label :communities-rule-index
+     :weight              :medium
      :size                :paragraph-2}
-    content]])
+    (str title ": " content)]])
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/actions/community_rules_list/view.cljs:43]: hmm should this be an `i18n` label with 2 params title and content? 🤔

File: translations/en.json [hunk 4]
```diff
@@ -1203,6 +1203,7 @@
     "repeat-puk": "Repeat new 12-digit PUK",
     "report-bug-email-template": "1. Issue Description\n{{description}}\n\n\n2. Steps to reproduce\n{{steps}}\n\n\n3. Attach screenshots that can demo the problem, please\n",
     "request-processed-after-node-online": "Your request will be processed once the community owner node is back online.",
+    "request-to-join-disclaimer": "Joining the community will reveal your public addresses to the owner",
```
Comment (J-Son89) [inline translations/en.json:1206]: looking at the designs, I think this might only need to be shown if the community is token gated. Can you verify this?

**Comment by J-Son89** [comment]
There was also one other issue in that the buttons margin is wrong on that bottom sheet.
In "src/status_im2/contexts/communities/actions/request_to_join/style.cljs" can you remove 
`margin-horizontal` from `bottom-container`.

```
(defn bottom-container
  []
  {:margin-horizontal 20
   :padding-top       32
   :flex-direction    :row
   :align-items       :center
   :justify-content   :space-evenly})
   ```
   
   I checked out your branch on Figma and applied this and it's correct 👍

File: src/status_im2/common/bottom_sheet/styles.cljs [hunk 5]
```diff
@@ -1,13 +1,14 @@
...
+            [quo2.theme :as theme]
             [status-im.utils.platform :as platform]))
 
 (defn handle
   [override-theme]
   {:width            32
    :height           4
    :background-color (colors/theme-colors colors/neutral-100 colors/white override-theme)
-   :opacity          0.05
+   :opacity          (if theme/dark? 0.1 0.05)
```
Comment (J-Son89) [inline src/status_im2/common/bottom_sheet/styles.cljs]: maybe it's better to use `theme-value` from "src/quo2/theme.cljs" as I think it will be easier to adjust that in the long run if needs be

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/communities/actions/community_rules_list/view.cljs (hunk 3 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/actions/community_rules_list/view.cljs:43]: I think none of this code is production ready. All the community rules are hardcoded in English in a Clojure var, and I kept it that way because the goal of the PR is to just fix UI issues.

I will create an issue to improve this, but I don't know how valuable it will be to add to the translations, given community rules will eventually be dynamic, or are they going to be fixed?

File: src/status_im2/contexts/communities/actions/request_to_join/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/actions/request_to_join/view.cljs]: Sure, though the PR's goal is to just fix bugs. I'll make this change ;)

File: src/quo2/components/selectors/disclaimer/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/quo2/components/selectors/disclaimer/view.cljs:11]: > There was also one other issue in that the buttons margin is wrong on that bottom sheet. In "src/status_im2/contexts/communities/actions/request_to_join/style.cljs" can you remove `margin-horizontal` from `bottom-container`.
> 
> ```
> (defn bottom-container
>   []
>   {:margin-horizontal 20
>    :padding-top       32
>    :flex-direction    :row
>    :align-items       :center
>    :justify-content   :space-evenly})
> ```
> 
> I checked out your branch on Figma and applied this and it's correct +1

Great, I'll double-check and apply this fix. Thanks

File: src/status_im2/contexts/communities/actions/community_rules_list/view.cljs (hunk 3 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/actions/community_rules_list/view.cljs:43]: Yea afaik you are right the rules will be dynamic eventually

File: translations/en.json (hunk 4 above)
Comment (ilmotta) [reply translations/en.json:1206]: The PR's `Notes` section has all the context related to this point.

> [Figma > Mobile App > Communities for Mobile](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1733-125697&t=3ssa500fwGvUqiTL-0) is outdated and will be changed soon, but what's important for this PR is that the final disclaimer Joining the community will reveal your public addresses to the node owner must always be shown, with/without token gated communities.
>
>After this PR I will create a separate issue related to changes that will be needed to make the Request to Join button work with upcoming changes in status-go that the desktop team is working on.

**Comment by ilmotta** [comment]
> There was also one other issue in that the buttons margin is wrong on that bottom sheet. In "src/status_im2/contexts/communities/actions/request_to_join/style.cljs" can you remove `margin-horizontal` from `bottom-container`.
> 
> ```
> (defn bottom-container
>   []
>   {:margin-horizontal 20
>    :padding-top       32
>    :flex-direction    :row
>    :align-items       :center
>    :justify-content   :space-evenly})
> ```
> 
> I checked out your branch on Figma and applied this and it's correct +1

Thanks @J-Son89, I'll apply this fix as well.

**Review by smohamedjavid — APPROVED** [review]

File: translations/en.json (hunk 4 above)
Comment (ilmotta) [reply translations/en.json:1206]: Issue created https://github.com/status-im/status-mobile/issues/16196
