### PR TITLE
[#14245] Fix read/unread notifications filter

### LINKED ISSUE #14245: Incorrect read/unread filter behavior
## Problem 

The read/unread toggle button is currently behaving as a toggle that **only** displays either read or unread notifications.

#### Expected behavior

The toggle button should display either unread notifications or notifications in any state (both read and unread).

#### Resources

- https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18681

### PR DESCRIPTION
**Pull request by rasom**
fix #14245 

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/activity_center/views.cljs [hunk 1]
```diff
@@ -25,6 +26,14 @@
 
 (defmulti notification-component :type)
 
+;; TODO(rasom): should be removed as soon as all notifications types covered
+(defmethod notification-component :default
+  [{:keys [type]}]
+  [rn/view {:style {:width 300, :height 100}}
+   [rn/text
+    (gstring/format
+     "I exist just to avoid crashing for no reason. I'm sorry. Type %d" type)]])
```
Comment (ilmotta) [inline src/status_im/ui/screens/activity_center/views.cljs:35]: I think we don't need to tell Clojure devs that `defmulti` requires a default case, just like `case`, otherwise an exception is thrown if no match is found.

File: src/status_im/ui/screens/activity_center/views.cljs [hunk 2]
```diff
@@ -25,6 +26,14 @@
 
 (defmulti notification-component :type)
 
+;; TODO(rasom): should be removed as soon as all notifications types covered
+(defmethod notification-component :default
```
Comment (ilmotta) [inline src/status_im/ui/screens/activity_center/views.cljs:30]: FYI: Although I wrote the solution with a multimethod, it'll die soon. In the branch I'm working on right now I had to split different notifications into different files for two reasons: code conflicts because we're touching the same file... and second and most important, because the identity verification notification has to be rendered also in a bottom sheet.

File: src/status_im/activity_center/core.cljs [hunk 3]
```diff
@@ -86,18 +86,23 @@
   (and (some? cursor)
        (not= cursor start-or-end-cursor)))
 
-(defn- filter-status->rpc-method
-  [filter-status]
-  (if (= filter-status :read)
-    "wakuext_readActivityCenterNotifications"
-    "wakuext_unreadActivityCenterNotifications"))
+(def ^:const status-read 1)
```
Comment (ilmotta) [inline src/status_im/activity_center/core.cljs:89]: Do you have a doc reference as to why we should tell the compiler these things are constants? Does it bring any meaningful performance improvement?

**Review by ilmotta — APPROVED** [review]
Good call to use a different endpoint `wakuext_activityCenterNotificationsBy`.

File: src/status_im/activity_center/core.cljs (hunk 3 above)
Comment (rasom) [reply src/status_im/activity_center/core.cljs:89]: > Does it bring any meaningful performance improvement?

it doesn't

File: src/status_im/ui/screens/activity_center/views.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/ui/screens/activity_center/views.cljs:35]: It's just to emphasise without checking the code that this should be removed asap.

Comment (ilmotta) [reply src/status_im/ui/screens/activity_center/views.cljs:35]: It was funny to read it :smile: I just try to avoid comments explaining how something in the language works, so that's why I bothered you with this.
