### PR TITLE
[#17533] fix: 'Sign in' page overlaps 'Main' page

### LINKED ISSUE #17533: 'Sign in' page overlaps 'Main' page after closing Find sync code bottom sheet via system back button (Android)
**Precondition:** 'Status' app is installed and opened.

**Steps to reproduce:**
1. Tap 'Sign in' tab;
2. Tap 'Find sync code' tab;
3. Tap 'Back' system button

**Actual result:** 'Sign in' page overlaps 'Main' page. 
Screenshot_20230929-232403_Status

https://github.com/status-im/status-mobile/assets/97245802/6fe1bb2d-64fe-497a-90c5-eba19cf3c100

**Expected result:** 'Find sync code' bottom sheet is collapsed. 'Sign in' page is displayed correctly.

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17533

'Sign in' page overlaps 'Main' page after closing Find sync code bottom sheet via system back button (Android)

#### Platforms
- Android

### Steps to test

1. Tap 'Sign in' tab;
2. Tap 'Find sync code' tab;
3. Tap 'Back' system button

### Result 
[Screen_recording_20231010_184911.webm](https://github.com/status-im/status-mobile/assets/71308738/889394c6-77a8-45ff-9325-b2a0e2d3595c)

status: ready

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 1]
```diff
@@ -311,17 +311,20 @@
...
           (rn/use-effect
            (fn []
-             (rn/hw-back-add-listener reset-animations-fn)
-             #(rn/hw-back-remove-listener reset-animations-fn))
-           [])
+             (when (= view-id :sign-in-intro)
+               (rn/hw-back-add-listener reset-animations-fn))
+             #(when (= view-id :sign-in-intro)
+                (rn/hw-back-remove-listener reset-animations-fn)))
+           [view-id])
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: I think there's no need to do double `when`.

```clojure
(rn/use-effect
 (fn []
   (when (= view-id :sign-in-intro)
     (rn/hw-back-add-listener reset-animations-fn)
     #(rn/hw-back-remove-listener reset-animations-fn)))
 [view-id])
```

what about this?  would work?

**Review by ulisesmac — APPROVED** [review]

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: i think cleanup will never get called to remove the back listener as it is defined but never returned from the effect function @ulisesmac

Comment (ulisesmac) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: I think the cleanup callback is returned by `when` and it should work.
But anyway, it was just a suggestion about code structure.

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: yes, that's correct and thank you for suggestion, resolved

**Comment by mohsen-ghafouri** [comment]
@churik Rebased

**Comment by churik** [comment]
Sorry for the delay! Was distracted with other tasks

**Comment by churik** [comment]
Thank you for the fix!
