### PR TITLE
fix(group-chat): Missing group chat name when clearing chat history

### LINKED ISSUE #21639: Group chat name is missing in confirming clear history dialog
# Bug Report

## Problem 
Open group chat > options > clear history, there is an icon and name is missing

#### Expected behavior
can see group name

#### Actual behavior
Image

### Reproduction

1. Create group chat 
2. Open it
3. Tap options > Clear history

### Additional Information

- Status version: nightly 19/11/2024
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/21639

### Summary

Fix missing group name when user chooses drawer option to clear chat history from within the group chat screen.

### Areas that may be impacted

Chat option to clear history.

### Steps to test

Please refer to the reproduction steps specified in the issue. With the fix applied, you should see the group chat name in the drawer when you try to clear the history from the list of group chats and from within each group chat options drawer.

status: ready

### CODE REVIEW

File: src/status_im/subs/chats.cljs [hunk 1]
```diff
@@ -171,29 +171,26 @@
...
-                  :chat-name
-                  :synced-to
-                  :synced-from
-                  :community-id
-                  :emoji
-                  :description])
-    :empty-chat?
-    (not (:last-message current-chat)))))
+ (fn [chat]
+   {:able-to-send-message? (:able-to-send-message? chat)
```
Comment (ilmotta) [inline src/status_im/subs/chats.cljs:177]: In mobile apps using CLJS I prefer to reserve `select-keys` only for cases where the list of keys is dynamic. Here we know the fixed set of keys, so I extract directly. Destructuring made the code look longer because the destructured keys span over multiple lines, plus the returned map.

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im/subs/chats.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/subs/chats.cljs:177]: We know `select-keys` and `merge` are expensive operations, so this change makes a lot of sense :+1:

**Review by ulisesmac — APPROVED** [review]
Thanks for this PR @ilmotta !

**Comment by Horupa-Olena** [comment]
@ilmotta Thank you for your PR!
Everything looks great! The PR is ready to be merged.

photo_2024-11-29_13-30-31
photo_2024-11-29_13-30-27

**Review by seanstrom — APPROVED** [review]
