### PR TITLE
Set up logging correctly

### LINKED ISSUE #15475: User gets stuck on "Generating keys" screen after trying to restore account (2 cases)
Followup of https://github.com/status-im/status-mobile/pull/15452 cc @cammellos 

User gets stuck on "Generating keys" screen in 2 cases

**Case 1** 

**User tries to restore account that has already been restored**

**Steps:** 
1. Create/restore an account
2. Logout
3. Proceed to the new Account restore flow
4. Try to restore account from that already exists
5. Observe user gets stuck on "Generating keys" screen

**Case 2** **User tries to restore account that has been restored before on current device **BUT** has been subsequently removed from Profile list** 

**Steps:** 
1. Create/restore an account
2. Logout
3. Open Profile list screen
4. Remove existing profile
5. Proceed to the new Account restore screen
6. Try to restore account that has been removed on step 4
7. Observe user gets stuck on "Generating keys" screen

https://user-images.githubusercontent.com/97245802/227537367-7baffb4f-2034-4076-81d3-54be042df9d2.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #15514: Geth log is not created if using new onboarding flow
# Bug Report

## Problem 
Currently `geth.log` is not created if using `Generate new key` flow
When using the old `Generate keys` flow, `geth.log` appears on device.

It is a blocker for finishing e2e for new flow as they expect `geth.log` to be always there.

#### Expected behavior
1) `DEBUG` log level is set by default for PR and e2e builds
2) `geth.log` is created after creating new multiaccount
#### Actual behavior
1) log level is `INFO`
2) no `geth.log` until manual change Log Level

### Reproduction

1) Open Status
2) Create multiaccount using `Generate new key` flow
3) Look up for a log here: `/storage/emulated/0/Android/data/im.status.ethereum/files/Download/`

### Additional Information

- Status version: nightly 28/03/23
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #15532: Unable to generate QR code using valid password after creating/restoring account until relogin
Followup of https://github.com/status-im/status-mobile/pull/15503 cc @cammellos 

**Steps:** 

1. Create/restore multiaccount
2. Try to generate sync QR using valid password
3. See if QR will be generated

**Actual result:** receiving "Try again" bottom sheet despite valid password has been entered. After performing relogin QR is generated successfully. 

[Status-debug-logs (26).zip](https://github.com/status-im/status-mobile/files/11098509/Status-debug-logs.26.zip)

https://user-images.githubusercontent.com/97245802/228481969-c60cc0ad-24b2-47c3-8ccd-b39bf9f24e10.mp4

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by cammellos**
On android, we were not passing the right directory, it also adds a couple of extra fields to the config.

Fixes: #15514
Fixes: https://github.com/status-im/status-mobile/issues/15532
Fixes: #15475 (case 2)

### CODE REVIEW

File: modules/react-native-status/ios/RCTStatus/RCTStatus.m [hunk 1]
```diff
@@ -882,7 +882,7 @@ - (void) migrateKeystore:(NSString *)accountData
     return rootUrl.path;
 }
 
-RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD(logFilePath) {
+RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD(logFileDirectory) {
```
Comment (rasom) [inline modules/react-native-status/ios/RCTStatus/RCTStatus.m:885]: I suppose this method should just return an empty string for it to work properly, checking now

Comment (cammellos) [reply modules/react-native-status/ios/RCTStatus/RCTStatus.m:885]: why is that? (i am not super famiilar with ios directory structure)

Comment (rasom) [reply modules/react-native-status/ios/RCTStatus/RCTStatus.m:885]: downstream (on `status-go` side) it is used as a relative path and it would result in some weird `/User/...the entire path from the root` path which will start in app's root dir (not system root). So if we just use `@""` here it should be fine.

I checked it, but it still doesn't work because `status-go` PR (with default `get.log`) is not added to this PR, if we use that branch I suppose it will work just fine. Currently I only confirmed that we need to return an empty string here as otherwise we get that weird structure.

File: src/status_im2/contexts/onboarding/events.cljs [hunk 2]
```diff
@@ -92,12 +92,14 @@
                          :wakuV2Nameserver         "1.1.1.1"
                          :logLevel                 (when log-enabled? config/log-level)
                          :logEnabled               log-enabled?
-                         :logFilePath              (status/log-file-path)
+                         :logFilePath              (status/log-file-directory)
```
Comment (qfrank) [inline src/status_im2/contexts/onboarding/events.cljs:96]: i think we should reference [updateConfig](https://github.com/status-im/status-react/blob/006b11d508f76bf0ef23fdb18af5f1ab39f98309/modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java#L216) , and we need add extra param `logDir` to request, there is a such logical in [status-go](https://github.com/status-im/status-go/blob/e9482e3974a2f82bd6a23f0c9e861b5bca23f472/api/geth_backend.go#L1057) , have `logFilePath` is not enough.
for ios, we could reference [prepareDirAndUpdateConfig](https://github.com/status-im/status-react/blob/006b11d508f76bf0ef23fdb18af5f1ab39f98309/modules/react-native-status/ios/RCTStatus/RCTStatus.m#L436) that how it set value for `LogDir` and `LogFile`

Comment (cammellos) [reply src/status_im2/contexts/onboarding/events.cljs:96]: mmh, not sure I follow, before we sent 2 parameters, the filename & the path, now we only send a single one, since I don't think there's need to send the filename, it's fine to hardcode to `geth.log`, I checked on android and the two nodeconfig are identical, but I think I am misunderstanding your point :) , would you mind elaborating please?

Comment (qfrank) [reply src/status_im2/contexts/onboarding/events.cljs:96]: according to [this](https://github.com/status-im/status-go/blob/e9482e3974a2f82bd6a23f0c9e861b5bca23f472/api/geth_backend.go#L1057) , if we only set nodeConfig. LogFile and nodeConfig.LogDir is empty, nodeConfig.LogFile will be overwrite with `rootDataDir+nodeConfig.LogFile , that's not we want right? rootDataDir is already a absolute path, nodeConfig.LogFile you passed(status/log-file-directory) is also a absolute path, so you know .. :) @cammellos

**Review by rasom — APPROVED** [review]

File: src/status_im2/contexts/onboarding/events.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im2/contexts/onboarding/events.cljs:96]: I think we set it, https://github.com/status-im/status-go/pull/3358/files#diff-a000fb44bf83c0af6a0ae08c002167ca516892e992f4e528ed53236f51b7e717R96 , logfilepath sets logdir, so we should get the right path, do you agree?

Comment (qfrank) [reply src/status_im2/contexts/onboarding/events.cljs:96]: oh,  sorry, i didn't know the existence of PR for status-go you mentioned(you didn't invite me to review), so pls ignore my previous comments 🥲

**Review by qfrank — APPROVED** [review]

**Comment by pavloburykh** [comment]
@cammellos hi! Do we need to include this PR during branch cut today?

**Comment by cammellos** [comment]
@pavloburykh yes, please

**Comment by churik** [comment]
@cammellos installed build with https://github.com/status-im/status-mobile/commit/437198aa1da34fc6145517e009a50048d4d72588 commit and still after "Generate keys" flow no `geth.log` created in `/storage/emulated/0/Android/data/im.status.ethereum.pr` dir
Can you please take a look?

**Comment by churik** [comment]
Also with this fix for `geth.log` we may remove paths to old flows in the same PR.

**Comment by cammellos** [comment]
@churik on it, thank you

**Comment by churik** [comment]
Tests are fixed in https://github.com/status-im/status-mobile/pull/15510 
PR is tested and ready to be merged.

Some tests are blocked due to known issue #15500
