### PR TITLE
Add send collectible fee validation (and small send collectible fixes)

### LINKED ISSUE #22213: No fee validation and no network is displayed on confirmation screen when sending collectible from account with 0 eth
**Preconditions:** User has Account A which holds some collectibles but 0 eth (no eth to cover fee)

**Steps:** 

1. Initiate collectible send flow from Account A
2. Proceed to confirmation screen
3. On confirmation screen pay attention if there is fee validation
4. On confirmation screen pay attention if network is shown
5. See if user can confirm transaction 

**Actual result:** 

1. No fee validation, user can proceed with confirming transaction
2. No network is shown on confirmation screen
3. User can confirm transaction which will fail with fee error
4. If transaction has been initiated from Overview screen, user will get additional `re-matches must match against a string.` error after confirming transaction and redirection to activity tab

See video below

https://github.com/user-attachments/assets/09c71ba9-0f33-4d69-96b4-46eb6a2ee2c4

**Expected result:** 

1. Fee validation should be shown, user shouldn't be able to proceed with confirming transaction
2. Network should be shown on confirmation screen

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by clauxx**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #22213 

## Summary
1. when not enough fee assets to send collectible:
   a. show the "Not enough assets to pay gas fees" alert banner
   b. highlight the fee
   c. disable the slider
2. when no routes were found to send collectible:
   a. show the "No routes found ..." alert banner
   b. disable the slider
3. while fetching routes for collectible, the footer should be consistent with the other flows, i.e.:
  a. removed activity loader
  b. show transaction details banner (est. time, max fees, recipient gets) in loading state
  c. show disabled slide button
4. show the network summary when sending collectible (can be shown only after the routes were loaded)
5. fixed the collectible name in the title overflowing outside the screen if it's too long (with ellipsis).

[comment]: # (Can be ready or wip)
status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -31,68 +31,73 @@
...
+         {:keys [token collectible token-display-name
+                 receiver-network-values
+                 sender-network-values tx-type]} (get-in db [:wallet :ui :send])
+         token-decimals                          (if collectible 0 (:decimals token))
+         native-token?                           (and token (= token-display-name "ETH"))
+         to-network-amounts-by-chain             (send-utils/network-amounts-by-chain
+                                                  {:route          chosen-route
+                                                   :token-decimals token-decimals
+                                                   :native-token?  native-token?
+                                                   :receiver?      true})]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/events.cljs:57]: the only change in this event is moving these definitions above the `enough-assets?` condition, so that we get the network information if there's no assets also.

**Review by briansztamfater — APPROVED** [review]

File: src/status_im/contexts/wallet/data_store.cljs [hunk 2]
```diff
@@ -272,7 +272,7 @@
      :amount-out                (:amount-out new-path)
      :approval-contract-address (:approval-contract-address new-path)
      :approval-required         (:approval-required new-path)
-     :estimated-time            (:estimated-time new-path)
+     :estimated-time            (:tx-estimated-time new-path)
```
Comment (vkjr) [inline src/status_im/contexts/wallet/data_store.cljs]: thanks for spotting this!

**Review by vkjr — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/status_im/contexts/wallet/data_store.cljs (hunk 2 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/data_store.cljs]: I think I'll revert this commit and add time estimation changes with a separate PR. Seems like time estimations is shown in seconds now, so might need more than just this.

Made a separate issue: https://github.com/status-im/status-mobile/issues/22254

**Review by smohamedjavid — APPROVED** [review]

**Review by shivekkhurana — APPROVED** [review]

**Comment by pavloburykh** [comment]
@clauxx thanks for the PR! Please take a look at the issues below. 

### ISSUE 1 Fee validation is cleared after changing fee settings

**Preconditions:** User has Account A which holds some collectibles but 0 eth (no eth to cover fee)

**Steps:** 

1. Initiate collectible send flow from Account A
2. Proceed to confirmation screen (fee validation should be applied)
3. Change transaction fee setting (select another fee value)
4. See if validation is still applied

**Actual result:** validation is reset. Slider is active and user can proceed with signing transaction. 


https://github.com/user-attachments/assets/1e35fb09-a89b-4e43-93ee-363a194f977a

**Comment by pavloburykh** [comment]
### ISSUE 2 Est time is not shown on confirmation screen

**Steps:** 

1. Proceed to transaction confirmation screen. It can be any type of transaction (send/swap/bridge)
2. See if Est time is shown

**Actual result:** Est time is not shown. Previously (in current develop) we have shown Est time, but there was no value which is also not okay. So from one point removing `Est time` seems to be a good temporary solution until we figure out which value we should pass there. But from PR description I see that the intention was to pass a valid value, that's why I am logging current behaviour as a bug. 

> show the estimated time (wasn't shown in any flow for some reason)
a. instead of the exact minutes (e.g. 15 min), show the intervals (e.g. 1-2 min, 3-5 min, >5 min) like we do for dapp transactions

photo_2025-03-10 16 46 42


**Expected result:** I am not sure what is the expected result here and which Est time value should we show. Should this value come from backend using the same method we use for dapp transactions or here we should use some other method? Or should we use hardcoded value of Est time? 

When we select fee in transaction setting, the time value seems to be hardcoded there (see screenshot below). Should we user the same hardcoded values from transaction settings on confirmation screen or rely on some estimated time that is calculated on the backend? 

photo_2025-03-10 16 46 38

**Comment by clauxx** [comment]
@pavloburykh 

on **ISSUE 1**: Seems like the issue comes from status-go, and also it should be reproducible not only for collectibles but also for the regular send flow. Seems like when we are changing the transaction settings, we don't check the account balance for the next route that is sent. I made a status-go [PR](https://github.com/status-im/status-go/pull/6429) to add the check (cc: @saledjenic), but I think it can be fixed on mobile as a follow-up, WDYT?

on **ISSUE 2**: I removed the estimated time changes from this PR in favor of a separate [PR](https://github.com/status-im/status-mobile/pull/22258), but forgot to update the description, sorry.

UPDATE: additionally, found a bug when no routes are found and attempting to change the tx settings, it would fail. I disabled the button for this case in the PR below.

**Comment by pavloburykh** [comment]
@clauxx thank you for looking at the issues. PR is tested and ready for merge.

> on ISSUE 1: Seems like the issue comes from status-go, and also it should be reproducible not only for collectibles but also for the regular send flow.

In regular send flow I cannot generate the same case, because user cannot proceed to review screen (with transaction settings button) if there is validation error on previous setup screen. See video below. 


https://github.com/user-attachments/assets/99e54726-ddcc-411f-bec5-819f9671525d


 > I think it can be fixed on mobile as a follow-up, WDYT? 

Sure, I have logged a followup https://github.com/status-im/status-mobile/issues/22324


**What has been tested:** 

1. https://github.com/status-im/status-mobile/issues/22213 is fixed
2. Verified everything listed in PR [summary](https://github.com/status-im/status-mobile/pull/22232#issue-2894196087)
3. Performed send tokens/collectibles transactions, bridge, swap to make sure there is no regression.
