### PR TITLE
[#17333] fix: disable ring for small avatar

### LINKED ISSUE #17333: Identifier rings are displayed on small avatars in deleted message/delete chat drawer/delete profile drawer
### Steps:
**User A:**
1. Go to any chat
2. Send message
3. Remove the message by 'delete for everyone' option

**User B:**
1. Check the removed message
2. Check the clear/delete chat drawer
3. Check the delete profile drawer

### Actual result:
the rings are shown on the following avatars:
-  Removed message
image

-  Clear/delete chat drawer
image

- Delete profile drawer 
image

### Expected result:
The identifier rings should not be displayed on small avatars

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17333

The identifier rings should not be displayed on small avatars like deleted message, delete chat and delete profile

Result: 

status: ready

### CODE REVIEW

File: src/utils/image_server.cljs [hunk 1]
```diff
@@ -144,6 +144,7 @@
   [{:keys [port public-key key-uid theme ring? length size background-color color
            font-size font-file uppercase-ratio indicator-size indicator-border
            indicator-center-to-edge indicator-color full-name ring-width]}]
+  (js/console.log (str "get-initials-avatar-uri " size))
```
Comment (ajayesivan) [inline src/utils/image_server.cljs]: @mohsen-ghafouri please remove the console log.

**Review by ajayesivan — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fix @mohsen-ghafouri , LGTM!
Let's wait for the design review.

**Comment by mohsen-ghafouri** [comment]
@status-im/design-team could you please check this?

File: src/utils/image_server.cljs [hunk 2]
```diff
@@ -98,7 +98,7 @@
    "&indicatorCenterToEdge="
    (* indicator-center-to-edge status-im2.common.pixel-ratio/ratio)
    "&addRing="
-   (if ring? 1 0)
+   (if (or (not ring?) (= size 20)) 0 1)
```
Comment (yqrashawn) [inline src/utils/image_server.cljs]: Hey there!
Could you provide more information about this? I'm trying to understand if this is here to prevent the `ring?` function from being overridden by the `override-ring?` function.

We need to come up with a better solution if that's the case.

**Review by Francesca-G — APPROVED** [review]
Looks good as far as I could test ✨

File: src/utils/image_server.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/utils/image_server.cljs]: according to QA request we should disable ring for small size. @yqrashawn

Comment (yqrashawn) [reply src/utils/image_server.cljs]: I recommend implementing this at https://github.com/status-im/status-mobile/blob/a9b63e0f22afdd9817114b09408255df54ea4bcc/src/quo2/components/avatars/user_avatar/view.cljs#L101 if that's the case

**Review by yqrashawn — APPROVED** [review]
LGTM
