### PR TITLE
Bug: save button behind keyboard in iOS #924

### LINKED ISSUE #924: Save button is hidden behind keyboard
*Type*: Bug
*Summary*: Save button is hidden behind keyboard if type Name for New group chat or New contacts group

#### Expected behavior
Save button is shown above the keyboard, as it's in Android
save in android

#### Actual behavior
[comment]: # (Describe what actually happened.)
Save button is behind a keyboard. So user needs to tap on Return and than on Save
no save button if keyboard
save if no keyboard

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and login
- Open Chats
- Tap on plus icon
- Tap on New croup chat
- Select any contact and tap Next
- Type Name of the chat
- Check for Save button

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  0.9.4d25
* Operating System: iOS

### PR DESCRIPTION
**Pull request by GustavoNunes**
fixes #924 

### Summary:
Save button now shows correctly above the virtual keyboard when it pops up, in all screens containing it:
- Create group chat
- Group chat settings
- Add contact to group chat
- Create contact group
- Edit contact group
- Edit profile

status: ready

### CODE REVIEW

**Comment by GustavoNunes** [comment]
@rasom,
I fixed this in a straightforward way, however here are some thoughts:
- If there are more places/screens that need this treatment, I feel that using `keyboard-avoiding-view` explicitly in multiple places is not right (the individual components shouldn't care about this).
 A possible solution is to use this in the topmost `view`, so this will be fixed everywhere. I felt however that such a wide-reaching change could introduce more bugs, and would need some extensive testing. Maybe this should be done further down the road?
- Android was already covered without this (using android:windowSoftInputMode="adjustResize"). But instead of using a different solution for each platform, we could drop this Android-specific option and rely only on `keyboard-avoiding-view`. I don't know if this is worth the trouble though, this would also be wide-reaching.

**Comment by flexsurfer** [comment]
I found that adjustResize can be reason of https://github.com/status-im/status-react/issues/656, we can try to use `keyboard-avoiding-view` there

**Comment by flexsurfer** [comment]
@GustavoNunes for example how it works on login screen https://github.com/status-im/status-react/blob/3437f79d82a6d91d6964c741a2f309cadde9a70a/src/status_im/accounts/login/screen.cljs#L59  https://github.com/status-im/status-react/blob/30fb48523e9a027723f9cf870618453b2cbab24a/src/status_im/accounts/login/styles.cljs#L28

**Comment by flexsurfer** [comment]
@GustavoNunes we need to fix all the screens that use `confirm-button`

**Comment by GustavoNunes** [comment]
I extended the fix to the other screens, thanks @flexsurfer! 
PR Ready again

File: src/status_im/new_group/views/chat_group_settings.cljs [hunk 1]
```diff
@@ -65,7 +67,8 @@
    type [:get :group-type]]
   (let [save-btn-enabled? (and (s/valid? ::v/name new-chat-name)
                                (not= new-chat-name chat-name))]
-    [view st/group-container
+    [(if ios? keyboard-avoiding-view view) (merge {:behavior :padding}
```
Comment (flexsurfer) [inline src/status_im/new_group/views/chat_group_settings.cljs]: have you tried to look how `keyboard-avoiding-view` works on Android?

Comment (GustavoNunes) [inline src/status_im/new_group/views/chat_group_settings.cljs]: It works fine, but Android already has its global solution in place (see my comment above) and the 2 don't play nice together
