### PR TITLE
Getting rid of `status-im.multiaccounts.core` + removing three word random names

### LINKED ISSUE #17227: 3 random name instead of public key in mention
**Area:** communities' channels/group chats

**Preconditions:** 

1. User A is mutual contact with User B and User C. 
2. User B and User C are not mutual contacts

**Steps:** 

1. User A creates community and invites User B and User C
2. User B joins the community and **goes offline**
3. User C joins the community
4. Open mentions list by User C in #general channel of newly joined community (See User's B pub key)
5. User C mentions User B
6. Observe how pub key mention is displayed

**Actual result:**
3 random name instead of pub key is displayed when User C mentioning User B

[User_C_logs.zip](https://github.com/status-im/status-mobile/files/12559203/User_C_logs.zip)

Monosnap 2023-09-08 13-14-05

https://github.com/status-im/status-mobile/assets/97245802/d16c629e-4a19-40b6-8cde-780905349f14

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #17285: Remove usage of status-im.multiaccounts.core in status-im2
Remove or replace usage of status-im.multiaccounts.core in status-im2

### LINKED ISSUE #17313: 3 random name is displayed as 1-1 chat name during loading of chats list
**Steps:** 

1. Create 1-1 chat
2. Open Chats tab
3. Perform re-login
4. Pay attention at 1-1 chat names after login (at the moment of chat list loading)

**Actual result:** 3 random name is displayed as 1-1 chat name for a moment until chat list is loaded

Below video in slow-mo

https://github.com/status-im/status-mobile/assets/97245802/1b2a945b-7b0d-4533-9e62-4accff7db247

**Expected result:** 3 random names should not be displayed in any place in the app. User's public key should be shown until Displaye name/ENS/nickname is loaded. 

**Additional info:**

This issue has been initially reported by @jo-mut here https://discord.com/channels/1103692771585433630/1103692773363810317/1153270331222536192

In his case there is additional weird bug: group icon is displayed in front of 1-1 chat until it is loaded. None of QAs were able to reproduce this issue. In our case icon is not displayed until chat list is loaded. 

Screenshot from @jo-mut phone. 

simulator_screenshot_94D2F4F1-A7FF-41DA-816C-D9FD5

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by alwx**
- fixes #17313 
- fixes #17285
- fixes https://github.com/status-im/status-mobile/issues/17227
- gets rid of three word random names
- gets rid of identicon / gfycat
- cleans things up

Extra follow-up issues: https://github.com/status-im/status-mobile/issues/17441 & https://github.com/status-im/status-mobile/issues/17616

#### Platforms

- Android
- iOS

##### Functional

- everywhere where the avatars and usernames are used :)

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/profile/user/views.cljs [hunk 1]
```diff
@@ -202,7 +201,7 @@
                                         {:view     :share-chat-key
                                          :address  (or compressed-key
                                                        public-key)
-                                         :ens-name preferred-name}])
+                                         :ens-name display-name}])
```
Comment (qfrank) [inline src/status_im/ui/screens/profile/user/views.cljs]: after bought first ens name, it will set `preferred-name` rather than `display-name` to ens name, here just used `display-name` instead of `preferred-name`, does this mean we should discard using `preferred-name` ? cc @cammellos @Samyoul

File: src/status_im/ui/screens/profile/user/views.cljs [hunk 2]
```diff
@@ -220,12 +219,8 @@
                                                                          has-picture)}])
                               :color     (user-avatar.style/customization-color customization-color
                                                                                 (theme/get-theme))
-                              :title     (multiaccounts/displayed-name account)
-                              :photo     (multiaccounts/displayed-photo account)
+                              :title     display-name
+                              :photo     (contact.core/displayed-photo account)
```
Comment (qfrank) [inline src/status_im/ui/screens/profile/user/views.cljs]: i feel a little strange here since we're using the namespace `contact.core` to get a profile photo although profile does have similarity with contact.

File: src/status_im2/common/home/top_nav/view.cljs [hunk 3]
```diff
@@ -23,23 +23,34 @@
...
-                               :unread-indicator/new  :mention ; should be :notification TODO
-                                                               ; https://github.com/status-im/status-mobile/issues/17102
-                               nil)]
+  (let [{:keys [public-key primary-name] :as account} (rf/sub [:profile/multiaccount])
+        online?                                       (rf/sub [:visibility-status-updates/online?
+                                                               public-key])
+        customization-color                           (rf/sub [:profile/customization-color])
+        avatar                                        {:online?         online?
+                                                       :full-name       primary-name
+                                                       :profile-picture (contact.core/displayed-photo
```
Comment (qfrank) [inline src/status_im2/common/home/top_nav/view.cljs]: same feeling here

File: src/status_im2/subs/contact.cljs [hunk 4]
```diff
@@ -228,15 +226,18 @@
  (fn [[contact] _]
    (:blocked contact)))
 
+;; TODO(alwx):
```
Comment (qfrank) [inline src/status_im2/subs/contact.cljs]: could you add a description here or link an issue if you want do it in a separate PR?

**Comment by qfrank** [comment]
Thanks for your PR, especially replaced the worst name `multiaccount` to a clear name `profile`

File: src/status_im2/common/home/top_nav/view.cljs [hunk 5]
```diff
@@ -23,23 +23,34 @@
...
+                                                                         account)}
+        network-type                                  (rf/sub [:network/type])
+        unread-count                                  (rf/sub [:activity-center/unread-count])
+        indicator                                     (rf/sub [:activity-center/unread-indicator])
+        notification-type                             (case indicator
+                                                        :unread-indicator/seen :mention-seen ; should be
```
Comment (ilmotta) [inline src/status_im2/common/home/top_nav/view.cljs]: These auto-formatted code comments are too ugly @alwx. Could you move the side comment to a separate line using `;;`?

File: src/status_im2/contexts/profile/data/events.cljs [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+         (if (or (= theme-type constants/theme-type-dark)
+                 (and (= theme-type constants/theme-type-system)
+                      (theme/device-theme-dark?)))
+           [:dark :light colors/neutral-100]
+           [:light :dark colors/white])]
+     (theme/set-theme theme)
+     (re-frame/dispatch [:change-shell-status-bar-style
+                         (if (shell.utils/home-stack-open?) status-bar-theme :light)])
+     (when reload-ui?
+       (rf/dispatch [:dissmiss-all-overlays])
```
Comment (ilmotta) [inline src/status_im2/contexts/profile/data/events.cljs]: Since you're using this event and it has only 1 usage, could you fix the typo?

File: src/status_im2/contexts/profile/data/events.cljs [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+       (hot-reload/reload)
```
Comment (ilmotta) [inline src/status_im2/contexts/profile/data/events.cljs]: This reload call should not run in production, so I think we should check if we're in debug mode.

File: src/status_im2/contexts/profile/data/events.cljs [hunk 8]
```diff
@@ -0,0 +1,157 @@
...
+                  constants/theme-type-dark)]
+    {:profile.data/switch-theme-fx [theme view-id false]}))
+
+(rf/defn get-profile-picture
+  {:events [:profile.data/get-profile-picture]}
+  [cofx]
+  (let [key-uid (get-in cofx [:db :profile/profile :key-uid])]
+    {:json-rpc/call [{:method     "multiaccounts_getIdentityImages"
+                      :params     [key-uid]
+                      :on-success #(re-frame/dispatch [:profile.data/update-local-picture %])}]}))
```
Comment (ilmotta) [inline src/status_im2/contexts/profile/data/events.cljs]: You can replace `on-success` or `on-error` callbacks with just the event vector. I explained this idea in detail in https://github.com/status-im/status-mobile/blob/a17efa7299822c6dc0642fdb180381c32e3afa0e/src/status_im2/common/json_rpc/events.cljs#L28-L51

It's the same idea used by other effects, like https://github.com/day8/re-frame-http-fx

```clojure
(rf/defn get-profile-picture
  {:events [:profile.data/get-profile-picture]}
  [cofx]
  (let [key-uid (get-in cofx [:db :profile/profile :key-uid])]
    {:json-rpc/call [{:method     "multiaccounts_getIdentityImages"
                      :params     [key-uid]
                      :on-success [:profile.data/update-local-picture]}]}))
```

File: src/status_im2/contexts/profile/data/events.cljs [hunk 9]
```diff
@@ -0,0 +1,157 @@
...
+  (if path
+    (string/replace-first path #"file://" "")
+    (log/warn "[native-module] Empty path was provided")))
+
+(re-frame/reg-fx
+ :profile.data/blank-preview-flag-changed
+ (fn [flag]
+   (native-module/set-blank-preview-flag flag)))
+
+(re-frame/reg-fx
```
Comment (ilmotta) [inline src/status_im2/contexts/profile/data/events.cljs]: I think `effects` shouldn't be mixed in the `events` namespace. There's no decision about where to put them, but I think a good start is to create an `contexts/profile/data/effects.cljs`. People already get confused with what's an effect or event and they serve very different purposes. What do you guys think? @flexsurfer @J-Son89 @ulisesmac

**Review by ilmotta — APPROVED** [review]
Great work @alwx. Slay the dragons!

File: src/status_im2/contexts/profile/data/events.cljs (hunk 9 above)
Comment (J-Son89) [reply src/status_im2/contexts/profile/data/events.cljs]: Sounds good to me

File: src/native_module/core.cljs [hunk 10]
```diff
@@ -431,19 +431,6 @@
     ;; in unknown scenarios we also consider the device rooted to avoid degrading security
     :else (callback true)))
 
-(defn generate-gfycat
-  "Generate a 3 words random name based on the user public-key, synchronously"
-  [public-key]
-  (log/debug "[native-module] generate-gfycat")
-  (when (validators/valid-public-key? public-key)
-    (.generateAlias ^js (status) public-key)))
```
Comment (flexsurfer) [inline src/native_module/core.cljs:439]: probably then its better to remove native code as well in this PR

File: src/status_im/events.cljs [hunk 11]
```diff
@@ -118,7 +118,7 @@
   (let [current-theme-type (get-in cofx [:db :profile/profile :appearance])]
     (when (and (multiaccounts.model/logged-in? db)
                (= current-theme-type status-im2.constants/theme-type-system))
-      {:multiaccounts.ui/switch-theme-fx
+      {:profile.data/switch-theme-fx
```
Comment (flexsurfer) [inline src/status_im/events.cljs]: wondering why is it data?

File: src/status_im/ui/screens/default_sync_period_settings/view.cljs [hunk 12]
```diff
@@ -20,7 +20,7 @@
    {:active    (= value id)
     :accessory :radio
     :title     (get titles id)
-    :on-press  #(re-frame/dispatch [:multiaccounts.ui/default-sync-period-switched id])}])
+    :on-press  #(re-frame/dispatch [:profile.data/update-multiaccount-value :default-sync-period id])}])
```
Comment (flexsurfer) [inline src/status_im/ui/screens/default_sync_period_settings/view.cljs]: why is it still `multiaccount-value` ?

File: src/status_im/ui/screens/profile/user/views.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/profile/user/views.cljs]: yes i feel like we have a confusion with the profile and contact, they should be kinda similar

Comment (flexsurfer) [reply src/status_im/ui/screens/profile/user/views.cljs]: dunno if this should be addressed in a separate PR

File: src/status_im2/common/password_authentication/view.cljs [hunk 13]
```diff
@@ -11,16 +11,16 @@
   []
   (let [entered-password (reagent/atom "")]
     (fn []
-      (let [account                (rf/sub [:profile/multiaccount])
-            {:keys [error button]} (rf/sub [:password-authentication])]
+      (let [{:keys [primary-name] :as account} (rf/sub [:profile/multiaccount])
```
Comment (flexsurfer) [inline src/status_im2/common/password_authentication/view.cljs]: `:profile/multiaccount` - what's that?

Comment (flexsurfer) [reply src/status_im2/common/password_authentication/view.cljs]: it seems like it was me who added this, but probably by mistake we shouldn't have multiaccount word name anymore

File: src/status_im2/contexts/profile/data/events.cljs (hunk 9 above)
Comment (flexsurfer) [reply src/status_im2/contexts/profile/data/events.cljs]: yeah i agree, we need a decision, i would vote for having effects.cljs and `:effect/` ns

File: src/status_im2/contexts/profile/data/events.cljs [hunk 14]
```diff
@@ -0,0 +1,157 @@
...
+            [react-native.platform :as platform]
+            [status-im.multiaccounts.update.core :as multiaccounts.update]
+            [status-im2.common.theme.core :as theme]
+            [status-im2.constants :as constants]
+            [status-im2.contexts.shell.jump-to.utils :as shell.utils]
+            [status-im2.setup.hot-reload :as hot-reload]
+            [taoensso.timbre :as log]
+            [utils.re-frame :as rf]))
+
+;; TODO(alwx): this function must be removed once the old bottom sheet is completely removed
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/data/events.cljs]: just wondering how bottom sheet is related to profile? why is it here ?

File: src/status_im2/contexts/profile/data/events.cljs [hunk 15]
```diff
@@ -0,0 +1,157 @@
...
+(rf/defn hide-legacy-bottom-sheet
+  [{:keys [db]}]
+  {:db                               (assoc db :bottom-sheet/show? false)
+   :dismiss-bottom-sheet-overlay-old nil})
+
+(defn- clean-path
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/data/events.cljs]: this should be probably in the utils ns

File: src/status_im2/contexts/profile/data/events.cljs [hunk 16]
```diff
@@ -0,0 +1,157 @@
+(ns status-im2.contexts.profile.data.events
+  (:require [clojure.string :as string]
+            [native-module.core :as native-module]
+            [quo2.foundations.colors :as colors]
+            [re-frame.core :as re-frame]
+            [react-native.platform :as platform]
+            [status-im.multiaccounts.update.core :as multiaccounts.update]
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/data/events.cljs]: why do we still keep multiaccounts? or we'll have more PRs on multiaccounts? and we move only core in this PR

File: src/status_im2/contexts/profile/data/events.cljs (hunk 9 above)
Comment (ulisesmac) [reply src/status_im2/contexts/profile/data/events.cljs]: Completely agree!

File: src/status_im2/common/password_authentication/view.cljs (hunk 13 above)
Comment (alwx) [reply src/status_im2/common/password_authentication/view.cljs]: renamed it to `:profile/profile-with-image` (there is `:profile/profile` already so I guess the new name is very accurate)

File: src/status_im/events.cljs (hunk 11 above)
Comment (alwx) [reply src/status_im/events.cljs]: renamed to `profile.settings` — I think it makes much more sense

File: src/status_im/ui/screens/default_sync_period_settings/view.cljs (hunk 12 above)
Comment (alwx) [reply src/status_im/ui/screens/default_sync_period_settings/view.cljs]: fixed

File: src/status_im2/contexts/profile/data/events.cljs (hunk 9 above)
Comment (alwx) [reply src/status_im2/contexts/profile/data/events.cljs]: Done

File: src/status_im/ui/screens/profile/user/views.cljs (hunk 1 above)
Comment (alwx) [reply src/status_im/ui/screens/profile/user/views.cljs]: I reverted this change. All the updates to how we handle `preferred-name` vs `display-name` vs `primary-name` will be handled in a separate issue/PR.

File: src/status_im2/contexts/profile/data/events.cljs (hunk 14 above)
Comment (alwx) [reply src/status_im2/contexts/profile/data/events.cljs]: Removed

File: src/status_im2/common/home/top_nav/view.cljs (hunk 3 above)
Comment (alwx) [reply src/status_im2/common/home/top_nav/view.cljs]: Fixed!

File: src/status_im/ui/screens/profile/user/views.cljs (hunk 2 above)
Comment (alwx) [reply src/status_im/ui/screens/profile/user/views.cljs]: Fixed!

File: modules/react-native-status/nodejs/status.cpp [hunk 17]
```diff
@@ -354,38 +354,6 @@ void _StopCPUProfiling(const FunctionCallbackInfo<Value>& args) {
 
 }
 
-void _Identicon(const FunctionCallbackInfo<Value>& args) {
```
Comment (siddarthkay) [inline modules/react-native-status/nodejs/status.cpp:357]: Curious to know @alwx did you nuke this manually ? Asking because this file is autogenerated :)

File: modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java [hunk 18]
```diff
@@ -1269,31 +1254,6 @@ public void identiconAsync(final String seed, final Callback callback) throws JS
         executeRunnableStatusGoMethod(() -> Statusgo.identicon(seed), callback);
     }
 
-    @ReactMethod
-    public void generateAliasAndIdenticonAsync(final String seed, final Callback callback) {
```
Comment (siddarthkay) [inline modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java:1273]: nice cleanup!

**Review by siddarthkay — APPROVED** [review]
Apart from an unexpected EOF at `status_im2/contexts/profile/settings/effects.cljs`
The nuking looks good to me!
Good work @alwx !

File: src/status_im/wallet/core.cljs [hunk 19]
```diff
@@ -464,8 +464,7 @@
                       {:from               (wallet.utils/get-default-account (:profile/wallet-accounts
                                                                               db))
                        :to                 (or (get-in db [:contacts/contacts identity])
-                                               (-> identity
-                                                   contact.db/public-key->new-contact
+                                               (-> {:public-key identity}
```
Comment (flexsurfer) [inline src/status_im/wallet/core.cljs]: redundant thread macro

File: src/status_im/wallet/core.cljs [hunk 20]
```diff
@@ -511,8 +510,7 @@
   (let [identity (:current-chat-id db)
         {:keys [ens-verified name] :as contact}
         (or (get-in db [:contacts/contacts identity])
-            (-> identity
-                contact.db/public-key->new-contact
+            (-> {:public-key identity}
```
Comment (flexsurfer) [inline src/status_im/wallet/core.cljs]: same redundant ->

File: src/status_im/wallet/core.cljs [hunk 21]
```diff
@@ -539,8 +537,7 @@
                       :wallet/prepare-transaction
                       {:from             (wallet.utils/get-default-account (:profile/wallet-accounts db))
                        :to               (or (get-in db [:contacts/contacts identity])
-                                             (-> identity
-                                                 contact.db/public-key->new-contact
+                                             (-> {:public-key identity}
```
Comment (flexsurfer) [inline src/status_im/wallet/core.cljs]: same redundant ->

File: src/status_im2/common/password_authentication/view.cljs [hunk 22]
```diff
@@ -2,25 +2,25 @@
...
+            [status-im2.contexts.profile.core :as profile.core]
             [native-module.core :as native-module]))
 
 (defn view
   []
   (let [entered-password (reagent/atom "")]
     (fn []
-      (let [account                (rf/sub [:profile/multiaccount])
-            {:keys [error button]} (rf/sub [:password-authentication])]
+      (let [{:keys [primary-name] :as account} (rf/sub [:profile/profile-with-image])
```
Comment (flexsurfer) [inline src/status_im2/common/password_authentication/view.cljs]: :as profile

File: src/status_im2/contexts/profile/core.cljs [hunk 23]
```diff
@@ -0,0 +1,7 @@
+(ns status-im2.contexts.profile.core)
+
+(defn photo
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/core.cljs]: hm looks more like utils ?

File: src/status_im2/contexts/profile/settings/effects.cljs [hunk 24]
```diff
@@ -0,0 +1,39 @@
...
+  (fn [flag]
+    (native-module/set-blank-preview-flag flag)))
+
+(re-frame/reg-fx
+  :profile.settings/webview-debug-changed
+  (fn [value]
+    (when platform/android?
+      (native-module/toggle-webview-debug value)))
+
+  (re-frame/reg-fx
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/settings/effects.cljs]: formatting

**Review by flexsurfer — APPROVED** [review]
awesome work! thanks

**Comment by VolodLytvynenko** [comment]
Hi @alwx take a look a found issue:

## ISSUE 1: Display Name is Shown Instead of ENS After Recovering an ENS User
### Steps to Reproduce:
1. Recover a user who has backed up an ENS name.

### Actual Behavior:
The display name is displayed within the chat after a message is sent, and within the profile
image
image

### Expected Behavior:
The ENS name should be shown instead of the display name.

**Comment by VolodLytvynenko** [comment]
@alwx integration tests failed https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-17384/22/consoleText. Could you take a look?

**Comment by VolodLytvynenko** [comment]
@alwx One question: you mentioned that the current task https://github.com/status-im/status-mobile/issues/17285  is fixed. What impact can this fix have or this is also related to the display names?

**Comment by alwx** [comment]
@VolodLytvynenko it's ready to be rechecked.

Regarding https://github.com/status-im/status-mobile/issues/17285: it doesn't really have any impact because it's mostly about restructuring — most of the functions that were in that namespace were moved to other places. But what has an impact is the removal of three word random names.

**Comment by VolodLytvynenko** [comment]
hi @alwx unfortunately the additional issues are detected. Take a look please:

## ISSUE 2: Mentioning in a community or group doesn't show display name
### Steps:
1. `User A` creates group or community and invites `User B` and `User C`
2. `User B` joins the community and **goes offline** 
3. `User C` joins the community
4.  Open mentions list by `User C` 
5. `User C` mentions `User B`
6. Observe how mention is shown

### Actual result:
Space is shown instead of mention

https://github.com/status-im/status-mobile/assets/52490791/ce5875ee-74d5-4d7a-b7d0-daec121b15de


### Expected result:
Display name is shown instead of space

### Additional info:
This issue is reproducible in about 30% of cases. If the issue is not reproducible, try adding an additional User D, and so on, then the current user should checks the list of suggestions.

**Comment by VolodLytvynenko** [comment]
The [issue 1](https://github.com/status-im/status-mobile/pull/17384#issuecomment-1764660423)  is fixed partially. The recovered ENS already shown in the profile, but the display name still shown in the chat after current user sends the message 

### Steps to Reproduce:
1. Recover a user who has backed up an ENS name.
2. Send the message in any chat
3. Observe your ENS in the sent message

### Actual result:
The display name is displayed within the chat after a message is sent

https://github.com/status-im/status-mobile/assets/52490791/1dc06218-6148-4aa0-b457-35346505e8e0

image



### Expected result:
The ENS name should be shown instead of the display name.

**Comment by alwx** [comment]
@VolodLytvynenko it's ready to be retested

**Comment by VolodLytvynenko** [comment]
Hi @alwx unfortunately [issue 2](https://github.com/status-im/status-mobile/pull/17384#issuecomment-1768158055) still reproducing. The steps are the same as described in the current issue:

https://github.com/status-im/status-mobile/assets/52490791/106af6d6-b872-4ab9-a981-0f3494f8f54f

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13120570/Status-debug-logs.1.zip)

**Comment by churik** [comment]
https://github.com/status-im/status-mobile/pull/17384#issuecomment-1777561457  can be also fixed by https://github.com/status-im/status-mobile/pull/17232 (at least for community)

So I think it might be a consequence of https://github.com/status-im/status-mobile/issues/17229

**Comment by alwx** [comment]
@VolodLytvynenko I think it's completely fixed by that PR @churik is referring to. I will update my PR to make it point to that Go PR to make it possible for you to check.

**Comment by alwx** [comment]
@VolodLytvynenko ready!

**Comment by alwx** [comment]
@VolodLytvynenko check it again, please

**Comment by VolodLytvynenko** [comment]
Hi @alwx  unfortunately [issue 2](https://github.com/status-im/status-mobile/pull/17384#issuecomment-1768158055) still reproducing, not so often as previously. I have created at least 5-7 new accounts to reproduce it. The steps are the same as described in the current:


https://github.com/status-im/status-mobile/assets/52490791/4ba494be-7c6d-423c-b5a1-469cfc049f97



### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13217766/Status-debug-logs.zip)

### ENV:
- Real device: iPhone 11 Pro Max, IOS 16
- Real device: Pixel 7a, Andoid 13

**Comment by VolodLytvynenko** [comment]
The [issue 1](https://github.com/status-im/status-mobile/pull/17384#issuecomment-1768158560) is also still reproduced. The recovered ENS already shown in the profile, but the display name still shown in the chat after current user sends the message


### Actual result:
The display name is displayed within the chat after a message is sent

how the recovered user with ENS is resolved on the current PR: 
- The ENS is "longensnamevovahahahaha.stateofus.eth", but the 'Display name' is shown instead

https://github.com/status-im/status-mobile/assets/52490791/a215f5f2-875b-475e-8a77-9d57f7e179d2

### Expected result:
The ENS name should be shown instead of the display name.

how the same recovered user with ENS is resolved on the last nightly: 

https://github.com/status-im/status-mobile/assets/52490791/28862338-7ff5-4ce6-96db-3b3d4afdd70f

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/13217862/logs.zip)

### ENV:
- Real device: iPhone 11 Pro Max, IOS 16
- Real device: Pixel 7a, Andoid 13

**Comment by alwx** [comment]
@VolodLytvynenko thanks for testing. For me it seems to be on the Go side :/
Is it possible to reproduce this on the current develop build as well?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko thanks for testing. For me it seems to be on the Go side :/ Is it possible to reproduce this on the current develop build as well?

Hi @alwx The [issue 1](https://github.com/status-im/status-mobile/pull/17384#issuecomment-1768158560) is reproducible only in this PR. On the last nightly it is not reproducible for me

**Comment by alwx** [comment]
@VolodLytvynenko I finally managed to update how preferred name extraction works — the issue should finally be fixed. Could you please take a look?

**Comment by VolodLytvynenko** [comment]
Hi @alwx You did it! :) Thank you for your hard work and patience. Issue 1 and 2 are fixed. PR is ready to be merged

**Comment by flexsurfer** [comment]
image
