### PR TITLE
Use `customization-color` to inherit custom colour for notification dots / counter

### LINKED ISSUE #16784: Inherit custom colour for unread notification dots
# Bug Report

#### Expected behavior
Custom color applied to:

- tabs inside the activity center
- notifications inside the activity center
- tabs on home screens (e.g. `Contacts`)
- main bottom tabs `Communities`, `Chats`, `Wallet`, `Browser` (currently they inherit the color, but it needs to be checked if the refactoring is needed; see [comment](https://github.com/status-im/status-mobile/issues/16784#issuecomment-1663637196) below)

Screenshot 2023-08-03 at 14 06 53
Screenshot 2023-08-03 at 14 07 15

### PR DESCRIPTION
**Pull request by alwx**
fixes #16784

- updates `activity-log` component to use `customization-color`
- updates `notification-dot` to use `customization-color`
- updates `tabs` and `tab`
- updates all the usages of these components throughout the codebase

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/notification_dot.cljs [hunk 1]
```diff
@@ -4,12 +4,18 @@
 
 (def ^:const size 8)
 
+(defn dot-background-color
+  [customization-color]
+  (if customization-color
+    (colors/custom-color-by-theme customization-color 50 60)
+    (colors/theme-colors colors/primary-50 colors/primary-60)))
```
Comment (ilmotta) [inline src/quo2/components/notifications/notification_dot.cljs]: Should the notification dot be themeable and should we pass the current `theme` to `theme-colors` instead of relying on the user's theme?

**Review by ilmotta — APPROVED** [review]
Code LGTM! 💯

File: src/quo2/components/notifications/notification_dot.cljs [hunk 2]
```diff
@@ -4,12 +4,18 @@
```
Comment (J-Son89) [inline src/quo2/components/notifications/notification_dot.cljs]: is this component for the notification dot?? If so it doesn't exist in the codebase but is used in many components for quo2 - perhaps we can move it to something like
src/quo2/components/common/notification_dot.cljs ? so we can mostly keep the mapping for design system components structure consistent with Figma?

Additionally can we put it into view and style files?

File: src/quo2/components/notifications/notification_dot.cljs (hunk 1 above)
Comment (J-Son89) [reply src/quo2/components/notifications/notification_dot.cljs]: something to note, this function `colors/custom-color-by-theme` is not setup to work with new theming mechanism, I think for now it's better to use
```
(colors/theme-colors
 (colors/custom-color customization-color 50)
  (colors/custom-color customization-color 60)
  theme)
  ```
  
  and theme value should be gotten from a prop or probably easier again to pass using `with-theme` hoc similiar to other quo2 components

File: src/status_im2/contexts/chat/home/view.cljs [hunk 3]
```diff
@@ -146,8 +138,18 @@
              :scroll-shared-value scroll-shared-value}])
          [:f> common.home.banner/animated-banner
           {:content             banner-data
+           :customization-color customization-color
            :scroll-ref          scroll-ref
-           :tabs                (get-tabs-data (pos? (count pending-contact-requests)))
+           :tabs                [{:id                  :tab/recent
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/home/view.cljs:143]: why move the function here? imo it was easier to read having it separate

**Review by ulisesmac — APPROVED** [review]
Nice 👍👍

**Comment by qoqobolo** [comment]
hey @alwx, could you rebase it against the fresh develop, please? The commit with the bug has been reverted.

**Comment by churik** [comment]
@qoqobolo rebased

**Comment by churik** [comment]
Thanks!
e2e failures are known not related to PR.
Tested basic flows, LGTM!

**Devices:**
- IPhone 14 Pro (IOS 16.5.1)
- Google Pixel 7A (Android 13)

File: src/quo2/components/common/notification_dot/view.cljs [hunk 4]
```diff
@@ -0,0 +1,11 @@
+(ns quo2.components.common.notification-dot.view
+  (:require [react-native.core :as rn]
+            [quo2.components.common.notification-dot.style :as style]))
+
+(defn notification-dot
```
Comment (J-Son89) [inline src/quo2/components/common/notification_dot/view.cljs]: nit we can just wrap this with the `with-theme` HOC so we don't have to pass `theme` as a prop 👍

File: src/quo2/components/notifications/activity_log/style.cljs [hunk 5]
```diff
@@ -46,8 +46,11 @@
    :margin-left    8
    :color          colors/neutral-40})
 
-(def unread-dot
-  {:background-color colors/primary-50
+(defn unread-dot
+  [customization-color]
+  {:background-color (if customization-color
+                       (colors/custom-color customization-color 50)
```
Comment (J-Son89) [inline src/quo2/components/notifications/activity_log/style.cljs]: I would assume this should be `(colors/custom-color customization-color 60)` since it's in the dark mode?

**Review by J-Son89 — APPROVED** [review]
