### PR TITLE
fix: toast style

### LINKED ISSUE #14702: Missing blur effect and shadow in toast component
# Bug Report

There are missing blur effect and shadow in current implementation of toast component

Details and related discussion at https://github.com/status-im/status-mobile/pull/14618#issuecomment-1370614039

Figma: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=7337%3A236708&t=nmPQOHE4r0t3rI13-4

### PR DESCRIPTION
**Pull request by yqrashawn**
resolves #14702

1. add blur and shadow
2. invert undo count down circle (dark/light)
3. fix toast action (the undo section) background
4. fix icon for join/leave community

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/toast.cljs [hunk 1]
```diff
@@ -52,18 +54,25 @@
...
-                                :border-radius    12}
-                               override-theme)}
+  [rn/view
+   {:style (merge {:padding-left 12 :padding-right 12} container-style)}
+   [blur/view
+    {:style         (merge-theme-style :container
+                                       (merge
+                                        (:shadow-1 shadows/normal-scale)
+                                        {:flex-direction   :row
+                                         :width            "100%"
```
Comment (flexsurfer) [inline src/quo2/components/notifications/toast.cljs]: `:flex 1` instead width should be used

**Review by flexsurfer — APPROVED** [review]

File: src/quo2/components/notifications/toast.cljs (hunk 1 above)
Comment (yqrashawn) [reply src/quo2/components/notifications/toast.cljs]: fixed
