### PR TITLE
fix: hardware induced back actions

### LINKED ISSUE #20182: Call on-close for hardware induced back actions
We currently call the `on-close` function when pressing on the X button on the top bar. This can cause bugs for hardware induced back actions (hardware back button, or swipe gesture). We need to make sure we call `on-close` on unmount

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/20182

### Summary

This PR fixes hardware induced back actions in wallet. Currently we had the `on-close` function to be called when pressing on the `X` button. This can cause bugs when navigation back using hardware button or swipe gesture. The `on-close` function need to be called `on-unmount` instead.

### Demo

Example fix: currently in develop when disabling a network on send-amount screen then navigation back with hardware button, then going to send screen again, the network will stay disabled. The below video shows fix for that:

https://github.com/status-im/status-mobile/assets/29354102/664cc098-6273-49bd-99ab-e54f55786a13

### CODE REVIEW

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by J-Son89** [comment]
should we add some other teams as a reviewer to this pr because whatever approach we take for this we should probably standardise across the app? 🤔

**Comment by OmarBasem** [comment]
Hey @status-im/mobile-devs, I would appreciate someone from outside wallet having a look on this PR since that bug could be present in other parts of the app also. In this PR I fixed the `on-close` callings inside wallet, and I can make another PR for messenger and communities screens if needed.

**Review by Parveshdhull — APPROVED** [review]

**Comment by Parveshdhull** [comment]
Hi @OmarBasem, Thank you very much great work. PR lgtm :tada: 

> In this PR I fixed the on-close callings inside wallet, and I can make another PR for messenger and communities screens if needed.

I don't think the community has any on-close callback. The current solution in PR looks ok to me, but if you check https://github.com/status-im/status-mobile/pull/13379/files we used approach of registering/removing `navigate-back-handler` in mount/unmount for chat screen.

I don't remember technical details about why we did that but I do remember there were a few edge cases related to chat screen when timing was important. Like quickly reopening the chat screen and maybe un-mount getting dispatched at wrong time or something and ending up with blank chat etc. So current solution works, but probably more robust solution is to registering/removing `navigate-back-handler` in mount/unmount. 

Probably @flexsurfer might have more info.

**Comment by flexsurfer** [comment]
yes, this might lead to issues when closing and opening screen

**Comment by OmarBasem** [comment]
Thanks for your input @Parveshdhull! 

> So current solution works, but probably more robust solution is to registering/removing navigate-back-handler in mount/unmount.

What about using swipe gesture on iOS? `hw-back-add-listener` does not handle that I think. (for chat screen we don't have swipe gesture, but for other screens we have swipe gesture) 

cc @flexsurfer

**Comment by Parveshdhull** [comment]
> What about using swipe gesture on iOS? hw-back-add-listener does not handle that I think

Yes, ios is problematic. You can find more details in this PR reviews https://github.com/status-im/status-mobile/pull/16035.

Initialy I also [opted](https://github.com/status-im/status-mobile/pull/16035#discussion_r1206956818) for `[:chat/close]` on umount. But then we discussed that it can also fail, so finally decided to just disable swipe. So either we disable swipe or accept that it can sometime break.

**Comment by Parveshdhull** [comment]
Maybe we can use both solutions :thinking:. that way atleast android will be robust.

**Comment by OmarBasem** [comment]
> so finally decided to just disable swipe

@Parveshdhull I think this is not ideal. Personally as an iOS user I always use gestures for navigating. I rarely use top bar buttons.

> Maybe we can use both solutions 🤔. that way atleast android will be robust.

I don't think this is ideal either, it introduces complexities to the code. I think the way it is okay for now (I also think that exiting and re-entering the screen quickly is likely to happen more on chat screen than other screens). I have opened an issue to investigate that problem further and find a more robust solution that works on both platforms https://github.com/status-im/status-mobile/issues/20226 👍

File: src/status_im/contexts/wallet/send/from/view.cljs [hunk 1]
```diff
@@ -31,10 +30,11 @@
 (defn view
   []
   (let [accounts (rf/sub [:wallet/accounts-without-watched-accounts])]
+    (rn/use-unmount on-close)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/from/view.cljs]: This approach has a problem while developing.

When the code is hot-reloaded the components are unmounted, so this will move us to the root of the app, making really hard to develop.

cc: @OmarBasem @Parveshdhull  @ilmotta 

I think we should instead use a callback maybe provided by the navigation library

Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/from/view.cljs]: @OmarBasem Have you tried hot-realoading the code after these changes?

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/from/view.cljs]: Thanks @ulisesmac, you are right, this can cause a problem while developing. I will look into it.

**Comment by ulisesmac** [comment]
@OmarBasem 

Maybe we should remove the `request-manual-qa` lable until a reliable solution is found? and also move this PR to draft

**Comment by clauxx** [comment]
The only thing I have for this approach is that there might be cases where swiping a modal down and explicitly pressing X should have different behaviours (e.g. in wallet connect, swiping a request down ignores the request while pressing X sends a rejection to the dapp).

cc @xAlisher are there many cases where pressing X and swiping a modal down would have different effects/behaviours?

**Comment by OmarBasem** [comment]
Hey guys,

So I have solved the problem by using `componentDidDisappear` event listener from react-native-navigation. This approach works well in the different cases:

- When pressing on UI 'X' button
- When pressing on Android hardware back button
- When using swipe back gesture on iOS

Also, the works well in release and development mode. The handler won't get called when hot refreshing in development mode.

Using the handler would be as follows:
```
  (rn/use-effect
   (fn []
     (let [listener    {:componentDidDisappear #(rf/dispatch [:wallet/close-account-page])}
           unsubscribe (navigation/reg-comp-listener listener view-id)]
       #(.remove unsubscribe)))
   [])
   ```

But to make using it easier I created a custom hook `use-nav-unmount`, its usage is as follows:
```
(rn/use-nav-unmount #(rf/dispatch [:wallet/close-account-page]) view-id)
```

Let me know what you guys think.

cc @ulisesmac @Parveshdhull @flexsurfer @status-im/mobile-devs

**Comment by OmarBasem** [comment]
> The only thing I have for this approach is that there might be cases where swiping a modal down and explicitly pressing X should have different behaviours (e.g. in wallet connect, swiping a request down ignores the request while pressing X sends a rejection to the dapp).
> 
> cc @xAlisher are there many cases where pressing X and swiping a modal down would have different effects/behaviours?

@clauxx If there is a case where pressing on the X button needs to execute extra logic, you can attach that logic to the on-press call of the button

**Comment by flexsurfer** [comment]
> `componentDidDisappear` event listener from react-native-navigation

this happens too late, it will happen after a new screen is opened, so it will break the logic , see https://github.com/wix/react-native-navigation/issues/7350 , I tried to solve this long time ago, but there is no good solution, we need to to move to react-navigation lib anyway, where it can be done

**Comment by flexsurfer** [comment]
it might lead to some difficult to reproduce bugs, but in most cases it will work

**Comment by OmarBasem** [comment]
> > `componentDidDisappear` event listener from react-native-navigation
> 
> this happens too late, it will happen after a new screen is opened, so it will break the logic , see [wix/react-native-navigation#7350](https://github.com/wix/react-native-navigation/issues/7350) , I tried to solve this long time ago, but there is no good solution, we need to to move to react-navigation lib anyway, where it can be done

@flexsurfer I think needing to know about transition animation when navigating back is an edge case. But yeah we need to migrate to `react-navigation` at some time. For now I think this is a good enough solution.

**Comment by flexsurfer** [comment]
> > > `componentDidDisappear` event listener from react-native-navigation
> > 
> > 
> > this happens too late, it will happen after a new screen is opened, so it will break the logic , see [wix/react-native-navigation#7350](https://github.com/wix/react-native-navigation/issues/7350) , I tried to solve this long time ago, but there is no good solution, we need to to move to react-navigation lib anyway, where it can be done
> 
> @flexsurfer I think needing to know about transition animation when navigating back is an edge case. But yeah we need to migrate to `react-navigation` at some time. For now I think this is a good enough solution.

it's not about  transition animation it's about timing, if you close the screen, and open it again quickly, it is possible to  reproduce easily, componentDidDisappear might happen when this screen has already opened again, which is wrong

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem Nice catch on the issue! Thank you for identifying it. Here are the issues found:

## ISSUE 1: [Android] The user is not navigated to the next page after selection of token

### Steps:
1. Paste any valid eth address into 'send to' page
2. Go to assets selection page
3. Select asset

### Actual result:
- The user is not navigated to the next page after asset selection 
- Upon returning to the 'send to' page, a validation message indicates that the address is invalid

https://github.com/status-im/status-mobile/assets/52490791/a816d188-8b19-4159-af88-9bcd60573cad

### Expected result:
The user is navigated to the next page


### OS: 
Android
### Devices:
- Pixel 7a, Android 13

**Comment by VolodLytvynenko** [comment]
> Hi @OmarBasem Nice catch on the issue! Thank you for identifying it. Here are the issues found:
> 
> ## ISSUE 1: [Android] The user is not navigated to the next page after selection of token
> ### Steps:
> 1. Paste any valid eth address into 'send to' page
> 2. Go to assets selection page
> 3. Select asset
> 
> ### Actual result:
> * The user is not navigated to the next page after asset selection
> * Upon returning to the 'send to' page, a validation message indicates that the address is invalid
> 
>  next_page.mp4 
> ### Expected result:
> The user is navigated to the next page
> 
> ### OS:
> Android
> 
> ### Devices:
> * Pixel 7a, Android 13

This issue is reproducible on IOS as well, but in different way. On IOS user always navigated to the 'sent to' page again after asset selection

https://github.com/status-im/status-mobile/assets/52490791/af325950-085c-4e74-ad05-f3507c874272

**Comment by OmarBasem** [comment]
> > > > `componentDidDisappear` event listener from react-native-navigation
> > > 
> > > 
> > > this happens too late, it will happen after a new screen is opened, so it will break the logic , see [wix/react-native-navigation#7350](https://github.com/wix/react-native-navigation/issues/7350) , I tried to solve this long time ago, but there is no good solution, we need to to move to react-navigation lib anyway, where it can be done
> > 
> > 
> > @flexsurfer I think needing to know about transition animation when navigating back is an edge case. But yeah we need to migrate to `react-navigation` at some time. For now I think this is a good enough solution.
> 
> it's not about transition animation it's about timing, if you close the screen, and open it again quickly, it is possible to reproduce easily, componentDidDisappear might happen when this screen has already opened again, which is wrong

@flexsurfer are you sure about this? I tried the following and `nav-unmount` seems to execute faster than react's unmount:
```
        (rn/use-unmount (fn []
                          (println "unmount")
                          (rf/dispatch [:wallet/close-account-page])))
        (rn/use-nav-unmount (fn []
                              (println "nav unmount")
                              (rf/dispatch [:wallet/close-account-page])) view-id)
```

**Comment by OmarBasem** [comment]
So it seems `navigate-to-within-stack` doesn't work well with `componentDidDisappear` (it gets called whether pushing or poping). For now I will be using the new nav hook on the wallet account screen only (as I think it is important for that screen's back actions to be handled properly to avoid unexpected behaviours from having an incorrectly stored `current-viewing-account-address`)

**Comment by OmarBasem** [comment]
@VolodLytvynenko thanks for your testing. Please check now

**Comment by J-Son89** [comment]
> So it seems `navigate-to-within-stack` doesn't work well with `componentDidDisappear` (it gets called whether pushing or poping). For now I will be using the new nav hook on the wallet account screen only (as I think it is important for that screen's back actions to be handled properly to avoid unexpected behaviours from having an incorrectly stored `current-viewing-account`)

Why are we qa'ing the pr while there's active discussion on the approach used?
Is there consensus on the implementation? 🤔

**Comment by OmarBasem** [comment]
> > So it seems `navigate-to-within-stack` doesn't work well with `componentDidDisappear` (it gets called whether pushing or poping). For now I will be using the new nav hook on the wallet account screen only (as I think it is important for that screen's back actions to be handled properly to avoid unexpected behaviours from having an incorrectly stored `current-viewing-account`)
> 
> Why are we qa'ing the pr while there's active discussion on the approach used? Is there consensus on the implementation? 🤔

@J-Son89 This approach is a proposal, so good to get it QA'ed early. The bug found by @VolodLytvynenko means it won't work with `navigate-to-within-stack`, which saves us some discussions I think. If we will proceed forward with this approach now it's usage will be limited to modal or stack screens (excluding nested stacks in modals)

File: src/react_native/core.cljs [hunk 2]
```diff
@@ -189,6 +190,15 @@
   [handler]
   (use-mount (fn [] handler)))
 
+(defn use-nav-unmount
```
Comment (flexsurfer) [inline src/react_native/core.cljs]: better to move this to `status-im.navigation.hooks`

**Review by flexsurfer — CHANGES_REQUESTED** [review]
just wondering why `rn/use-unmount` can't be used?

**Comment by OmarBasem** [comment]
> just wondering why `rn/use-unmount` can't be used?

@flexsurfer because of this https://github.com/status-im/status-mobile/pull/20183#discussion_r1619394309

**Comment by flexsurfer** [comment]
> > just wondering why `rn/use-unmount` can't be used?
> 
> @flexsurfer because of this [#20183 (comment)](https://github.com/status-im/status-mobile/pull/20183#discussion_r1619394309)

there should be no unmount on hot reload, we just need to fix that
I see here two problems, first is that not only unmount triggered, but react state is lost and second instead of fixing that we're implementing something complex for production just because devexp is bad 

give me some time, I'll try to fix that

**Comment by ulisesmac** [comment]
> > > just wondering why `rn/use-unmount` can't be used?
> > 
> > 
> > @flexsurfer because of this [#20183 (comment)](https://github.com/status-im/status-mobile/pull/20183#discussion_r1619394309)
> 
> there should be no unmount on hot reload, we just need to fix that I see here two problems, first is that not only unmount triggered, but react state is lost and second instead of fixing that we're implementing something complex for production just because devexp is bad
> 
> give me some time, I'll try to fix that

@flexsurfer It's expected that unmount is triggered because shadow remounts/re-creates the components in the edited namespace.

But yeah, we could create another hook that skips itself when it's a shadow-cljs unmount and not a "user" unmount

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem the issue 1 is fixed. But for now, the initial issue is reproduced 

## PR_ISSUE 2: The network shown as disabled after the hardware back action

### Steps:
1. Go to routes generation page
2. Enter available value
3. Disable any network
4. Go back using hardware back button or gesture
5. Return to routes generation page

### Actual result:
The network is left as disabled

https://github.com/status-im/status-mobile/assets/52490791/87e20ed6-4ccf-4669-98e2-d875a7002974

### Expected result:
The networks are enabled

### Devices:
- Pixel 7a, Android 13

**Comment by OmarBasem** [comment]
> Hi @OmarBasem the issue 1 is fixed. But for now, the initial issue is reproduced

@VolodLytvynenko that's actually expected since I was saying we would have to limit that solution to the account screen https://github.com/status-im/status-mobile/pull/20183#issuecomment-2159825476 But anyways you can pause testing for now. I will let you know when all the discussions are resolved. Thanks!

**Comment by VolodLytvynenko** [comment]
@OmarBasem  thank you for update. Just one more place where the issue occurs if the hardware back button is used 

## ISSUE 3: [Android] The confirmation bridging page is shown instead of routes generation screen if the hardware back button is previously used

### Steps: 
1. Recover user with available assets on L1 mainnet (NOTE: on sepolia it does not work)
2. Go to bridge flow
3. Select the network in 'Bridge to' page (The best stable option is Optimism)
4. Enter an available value into input field to generate Beridge route L1-L2 (optimism)
5. Go to the confirmation bridging page after routes will be generated
6. Go back to 'Bridge to' page using the hardware back button or use the back gesture
7. Select any network

### Actual result:
User is navigated to the confirmation bridging page, skipping the routes generation page

https://github.com/status-im/status-mobile/assets/52490791/6ad2d008-ad77-45c4-b77e-c215d019d90f

### Expected result:
User is navigated to the routes navigation page

### Devices:
- Pixel 7a, Android 13

**Comment by flexsurfer** [comment]
Sorry for the delay @OmarBasem @ulisesmac, I did a little research. First, some technical information: when you make a change in a CLJS file, shadow-cljs tracks this and compiles all namespaces where changes were made or which require namespaces with changes. Thus, we have new functions. Then, we initiate a re-render of the root component, and since the function is new, React considers it a new component and remounts it. Consequently, the local state is reset for this component, and lifecycle events occur, triggering unmount and mount. Therefore, this is absolutely correct behavior and should not be changed, as it could lead to inconsistency in the state. It is correct to use `rn/unmount` in this case, and the developer should take care to comment out the code in unmount if they want to do so while working on the component. However, for special cases where we are sure we don't want `rn/unmount` to trigger on hotreload, I propose using the following code:
`(hot-reload/use-safe-unmount handler)`
Where:
```clojure
(defn use-safe-unmount
  [handler]
  (let [prev-cnt @cnt]
    (if js/goog.DEBUG
      (rn/use-unmount #(when (= prev-cnt @cnt) (handler)))
      (rn/use-unmount handler))))
```

**Comment by VolodLytvynenko** [comment]
One more issue related to the hardware back button on the collectibles flow

## PR_ISSUE 4: The confirmation transaction page is shown missing account selection and send to pages if hardware back button is used during collectible sending flow

### Steps:
1. Open collectible -> tap 'send' -> go to a confirmation transaction page
2. Go back using hardway back button to the list of collectibles
3. Tap 'send' on any collectilbe

### Actual result:
The user is navigated to the confirmation transaction page, skipping the account selection and send to pages.


https://github.com/status-im/status-mobile/assets/52490791/8a5c1b6a-ebd0-4144-b697-c5f39972a66e



### Expected result:
- The user is navigated to the account selection page initially if 'send' is tapped on the wallet overview.
- The user is navigated to the send to page if 'send' is tapped on the opened account.


### Devices:
- Pixel 7a, Android 13

**Comment by OmarBasem** [comment]
> Sorry for the delay @OmarBasem @ulisesmac, I did a little research. First, some technical information: when you make a change in a CLJS file, shadow-cljs tracks this and compiles all namespaces where changes were made or which require namespaces with changes. Thus, we have new functions. Then, we initiate a re-render of the root component, and since the function is new, React considers it a new component and remounts it. Consequently, the local state is reset for this component, and lifecycle events occur, triggering unmount and mount. Therefore, this is absolutely correct behavior and should not be changed, as it could lead to inconsistency in the state. It is correct to use `rn/unmount` in this case, and the developer should take care to comment out the code in unmount if they want to do so while working on the component. However, for special cases where we are sure we don't want `rn/unmount` to trigger on hotreload, I propose using the following code: `(hot-reload/use-safe-unmount handler)` Where:
> 
> ```clojure
> (defn use-safe-unmount
>   [handler]
>   (let [prev-cnt @cnt]
>     (if js/goog.DEBUG
>       (rn/use-unmount #(when (= prev-cnt @cnt) (handler)))
>       (rn/use-unmount handler))))
> ```

@flexsurfer thank you for taking the time to look into this issue.

> (rn/use-unmount #(when (= prev-cnt @cnt) (handler)))

If I understand correctly that line will prevent triggering unmount on hot reload, but it will work normally when unmounting the component like navigating back, correct?

**Comment by flexsurfer** [comment]
> If I understand correctly that line will prevent triggering unmount on hot reload, but it will work normally when unmounting the component like navigating back, correct?

correct

**Comment by OmarBasem** [comment]
@flexsurfer I have updated the PR to use the new method `use-safe-unmount`. Please re-review

**Comment by OmarBasem** [comment]
@VolodLytvynenko can you please take a look at the current builds? The issues above should be fixed

**Review by flexsurfer — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem thank you for fixes. Take a look additional issues

## PR_ISSUE 5: it seems the back button is tapped twice

### Steps:
1. Go to 'Send To' page
2. Tap 'back' button on UI
3. Go to routes generation page
4. Tap 'back' button on UI

### Actual result:
When the 'back' button is tapped, the next screen is quickly shown, and then the following screen is shown, causing the user to be navigated back two screens after back is tapped on the following screens:
- "Sent To" page
- "Routes generation" page

https://github.com/status-im/status-mobile/assets/52490791/7c32c4db-6c3a-4ce9-9b8b-626db371333b

https://github.com/status-im/status-mobile/assets/52490791/f5b566f5-e394-4d66-b95e-a4a55fc43018

### Expected result:
User should be navigated back on correct screen

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 6: Wrong navigation after assets sending

### Steps:
1. Send collectible
2. Send token

### Actual result:
- User is navigated to collectible detailed page after collectible is sent

https://github.com/status-im/status-mobile/assets/52490791/0ac0978e-5a14-4c6d-a80c-d610bdf3697f

- [Android] User is navigated to wallet overview page after token is sent

https://github.com/status-im/status-mobile/assets/52490791/19f32827-9f97-4c7c-b9ca-639d722dfab3




### Expected result:
User is navigated to the activity tab of the account from which the current collectible or asset is sent

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by OmarBasem** [comment]
@VolodLytvynenko thanks for your testing.
 Issue 5 is fixed.
 Issue 6 I am currently not able to check it as I need some ETH. On develop does it navigate to the the activity tab after the transaction is complete?

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem thank you for PR.
✅ [issue 1](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2157974049) is fixed
✅ i[ssue 2](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2161358869) is fixed
✅ [issue 3](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2164666849) is fixed
✅ [issue 4](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2164666849) is fixed

🔴  [issue 5](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2167611974) is not fixed. Still  back is appealing twice

### Steps:
case 1: Open acc -> tap 'send' -> tab [x] to go back or back by hardware back action

https://github.com/status-im/status-mobile/assets/52490791/ea5d41b0-fecf-4927-bd0e-642da9110db8

case 2: Open acc -> tap 'bridge' -> go to bridge routes page ->  tab [x] to go back or back by hardware back action

https://github.com/status-im/status-mobile/assets/52490791/9b7184ae-470f-463c-ade8-2e05f01a8778

### Actual result:
back navigation action is performed twice

### Expected result:
back navigation action is performed once

**Comment by VolodLytvynenko** [comment]
## ISSUE 7: The user is navigated to empty account after transaction confirmation

### Steps:
1. Go to wallet main page 
2. Scan address QR using Univeral scanner OR long press the asset on the main wallet page 
3. Go to transaction confirmation page
4. Confirm transaction

### Actual result:
User is navigated to the activity page of empty account (no balances, no transactions in activity tab, no assets)

https://github.com/status-im/status-mobile/assets/52490791/32b71bce-4e1b-426f-bacf-5a7e604628cb

### Expected result:
User is navigated to the activity page of the accoun from which the transaction is sent

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16109423/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
🔴 [issue 6](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2167644306) is not fixed in case of sending assets from the opened account

### Steps:
1. Open account
2. Long press the asset and press 'send' or tap 'send' button on the accoun page
3. Confirm transaction

### Actual result:
User is navigated to the main page of wallet

https://github.com/status-im/status-mobile/assets/52490791/017bbbfe-ee26-452e-b10e-c7595404a81e

### Expected result:
User is navigated to the activity page of the accoun from which the transaction is sent

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by VolodLytvynenko** [comment]
## ISSUE 8: "From" page is missing when asset is long tapped on the main wallet page
### Steps:
1. Go to the wallet main page.
2. Open account
3. Tap "send" button
4. Go back to wallet main page
5. Long tap the asset OR scan address using universal scanner
6. Tap the 'send' option.

### Actual Result:
The user is navigated directly to the 'send to' page.

https://github.com/status-im/status-mobile/assets/52490791/e16c1f3c-b036-4006-8a1f-8dd09052e93e

### Expected Result:
The user is navigated to the "From" page where the account can be selected.

How it works on nightly:

https://github.com/status-im/status-mobile/assets/52490791/bbb42bb9-7551-4050-9151-9864e32b267b

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

**Comment by VolodLytvynenko** [comment]
This issue is related to navigation and is also present on the latest development build. It might be better to fix it separately. Let me know if it's better to create a follow-up for this

## ISSUE 9: User is navigated to transaction confirmation page if asset is selected during collectible sending flow

### Steps:
1. Go to wallet
2. Open account
3. Tap 'send'
4. Select collectible on the "Select assets" page
5. Go back to "Select assets" page
6. Select token

### Actual result:
User is navigated directly to confirmation transaction page after token 

https://github.com/status-im/status-mobile/assets/52490791/faee5b1c-7014-4a80-8fa2-85b6035c049d

### Expected result:
User is navigated to route generation page 


### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by OmarBasem** [comment]
@VolodLytvynenko thanks for your testing.

> 🔴 https://github.com/status-im/status-mobile/pull/20183#issuecomment-2167611974 is not fixed. Still back is appealing twice

That was on a different screen, but should be fixed now.

The other issues I am not able to reproduce. I am getting the correct expected behaviour. Can you please re-check these issues?

Also, if there is an issue reproducible on develop, then better open a separate issue for it.

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem unfortunatly
[issue 7](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2210766922) is still reproducible. Hope logs might help with what is going on. 
User is navigated to empty account after transaction confirmation if send flow is started with QR code scanning by universal scanner or from main wallet page

### Steps:
1. Go to wallet main page 
2. Scan the address QR using Univeral scanner OR long press the asset on the main wallet page 
3. Go to transaction confirmation page
4. Confirm transaction

### Actual result:
User is navigated to the activity page of empty account (no balances, no transactions in activity tab, no assets)

https://github.com/status-im/status-mobile/assets/52490791/32b71bce-4e1b-426f-bacf-5a7e604628cb

### Expected result:
User is navigated to the activity page of the accoun from which the transaction is sent

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16109423/Status-debug-logs.zip)

**Comment by J-Son89** [comment]
> This issue is related to navigation and is also present on the latest development build. It might be better to fix it separately. Let me know if it's better to create a follow-up for this
> 
> ## ISSUE 9: User is navigated to transaction confirmation page if asset is selected during collectible sending flow
> ### Steps:
> 1. Go to wallet
> 2. Open account
> 3. Tap 'send'
> 4. Select collectible on the "Select assets" page
> 5. Go back to "Select assets" page
> 6. Select token
> 
> ### Actual result:
> User is navigated directly to confirmation transaction page after token
> 
>  assets-collectible.mp4 
> ### Expected result:
> User is navigated to route generation page
> 
> ### Devices:
> * Pixel 7a, Android 13
> * iPhone 11 Pro Max, IOS 17

Is this a bug, or is it because the user only has one of that collectible?

**Comment by VolodLytvynenko** [comment]
> Is this a bug, or is it because the user only has one of that collectible?

Hi @J-Son89 I might have misunderstood your question. This bug is reproducible when the user has any kind of collectible.

**Comment by J-Son89** [comment]
Oh sorry I see the issue now, yeah that's a big :)

**Comment by VolodLytvynenko** [comment]
[issue 5](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2167611974) is not fixed. Still back is appealing twice in the following cases:

### Steps:
case 1: Open wallet Maine page -> open collectible -> tap 'send' -> tab [x] to go back or back by hardware back action

https://github.com/status-im/status-mobile/assets/52490791/b76b4091-1f36-464a-83a7-1e00b9f0860b

case 2: go to bridge routes generation page -> tab [x] to go back or back by hardware back action

https://github.com/status-im/status-mobile/assets/52490791/666753a8-55cb-469f-aa65-1bec1bf4d3eb

### Actual result:
back navigation action is performed twice

### Expected result:
back navigation action is performed once

**Comment by VolodLytvynenko** [comment]
✅ [issue 6](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2167644306) is fixed

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
✅ [Issue 8](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2210789953) is fixed

**Comment by OmarBasem** [comment]
@VolodLytvynenko thanks for your continued testing.

The other cases of issue 5 should be fixed now.
Issue 7 is also fixed.

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem 
[issue 7](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2210766922) is still reproducible, but this time it occurs if we take a different path.


User is Navigated to empty account after transaction confirmation if send flow is started with QR Code scanning by Universal Scanner or from Main Wallet Page and transaction is Sent from derived or Imported Account

### Steps:
1. Go to wallet main page
2. Create additional account (additional account can be derived from master account or imported via seed phrase) 
3. Scan the address QR using Universal scanner OR long press the asset on the main wallet page 
4. Select the additional account from which created in step 2
5. Go to transaction confirmation page
6. Confirm transaction

### Actual result:
User is navigated to the activity page of empty account (no balances, no transactions in activity tab, no assets)

https://github.com/status-im/status-mobile/assets/52490791/cc01b51e-8d5b-4478-83a5-8b553ecac613


### Expected result:
User is navigated to the activity page of the account from which the transaction is sent

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16129103/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
hi @OmarBasem it seems I found the steps which help to reproduce this [issue 7](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2210766922)

### Preconditions:
The user has 2 wallet accounts with available assets

### Steps:
1. Go to wallet main page
2. Scan the address QR using Universal scanner OR long press the asset on the main wallet page
3. Select `account 1` on the FROM screen
4. Go to the routes generation page
5. Select `account 2` using account switcher
6. Generate the route and confirm transaction

### Actual result:
User is navigated to the activity page of empty account (no balances, no transactions in activity tab, no assets). After the `receive` button is tapped on the empty page, the "error cannot read property `h` of null" is shown and app does not respond anymore

https://github.com/status-im/status-mobile/assets/52490791/35537be5-bbc4-4a4c-a3f8-dad7e61704cc


### Expected result:
User is navigated to the activity page of the account from which the transaction is sent

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, IOS 17

### Logs:
[logs (3).zip](https://github.com/user-attachments/files/16133645/logs.3.zip)

**Comment by VolodLytvynenko** [comment]
hi @OmarBasem take a look, after last commit the 🔴 [issue 5](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2167611974) comes back. 

### Steps:
1. Go to send to page
2. Tap back


### Actual result:
back navigation action is performed twice

https://github.com/status-im/status-mobile/assets/52490791/fdff905f-a6aa-4000-8701-b52f1b7f0bf7

### Expected result:
back navigation action is performed once

**Comment by VolodLytvynenko** [comment]
🔴 [issue 6](https://github.com/status-im/status-mobile/pull/20183#issuecomment-2167644306) comes back as well. User is navigated to main wallet page in case of sending assets from the opened account

### Steps:
1. Open account
2. Long press the asset and press 'send' or tap 'send' button on the accoun page
3. Confirm transaction

### Actual result:
User is navigated to the main page of wallet

https://github.com/status-im/status-mobile/assets/52490791/017bbbfe-ee26-452e-b10e-c7595404a81e

### Expected result:
User is navigated to the activity page of the accoun from which the transaction is sent

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by VolodLytvynenko** [comment]
hi @OmarBasem still issue related to navigation to the activity tab exists. 

### PR_ISSUE 10: User is navigated to the assets page instead of the activity tab after sending confirmation.
### Steps:
1. Open an account (this step is required).
2. Long press asset and type 'send' or tap 'send' button shown above accounts
3. Go to transaction confirmation page
4. Confirm the transaction

### Actual result:
- After the transaction sends confirmation, the assets tab is shown as opened

https://github.com/status-im/status-mobile/assets/52490791/cff77601-686c-4b0a-b70f-c1fe2e96834a

- Additionally: On IOS the main wallet page blinks after the transaction is confirmed

https://github.com/status-im/status-mobile/assets/52490791/57c620b5-271d-4f30-b061-eab5c39e3b5f


### Expected result:
After the transaction sends confirmation, the activity tab is shown as opened

**Comment by VolodLytvynenko** [comment]
hi @OmarBasem issues are fixed. PR is ready to be merged. Thank you for your hard work and patience!

**Comment by OmarBasem** [comment]
> hi @OmarBasem issues are fixed. PR is ready to be merged. Thank you for your hard work and patience!

Finally!! Thank you @VolodLytvynenko for your testing and patience also! :)
