### PR TITLE
fix: Wrong UI for network preferences bottom sheet

### LINKED ISSUE #19463: Wrong UI for network preferences bottom sheet
### Steps:
1. Tap 'Share' button
2. Open the 'wallet' tab -> Multichain -> Open preferences drawer

### Actual result:
image

### Expected result:
image

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19463

This PR fixes incorrect UI details in the network preferences:

1. Address display
2. Mainnet to be selected by default
3. button text

Screenshot_20240402_141910_Status

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/common/qr_codes/view.cljs [hunk 1]
```diff
@@ -44,6 +44,7 @@
   [network]
   (case network
     :ethereum "eth:"
```
Comment (shivekkhurana) [inline src/status_im/common/qr_codes/view.cljs]: I think we should get some helped methods for managing network ids for addresses, like `eth:`, `arb:` etc. 

I used strings in another PR. We can make this a constant, and then get a helper function to give a network id, something like:

```clj
(defn network-ids [network-id-constants]
  (join network-id-constants ":"))

(network-ids [constants/eth-network-id constants/arb-network-id])
```

File: src/status_im/contexts/wallet/account/share_address/view.cljs [hunk 2]
```diff
@@ -34,7 +34,8 @@
   [selected-networks]
   (let [on-save       (fn [chain-ids]
                         (rf/dispatch [:hide-bottom-sheet])
-                        (reset! selected-networks (map utils/id->network chain-ids)))
+                        (reset! selected-networks (map #(if (= % 1) :mainnet (utils/id->network %))
+                                                       chain-ids)))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/account/share_address/view.cljs:38]: I am wondering why did we change the naming of the ethereum network in db to `mainnet`. This has caused several instances where ethereum network needs to be handled with a condition, also like [this](https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs#L50) and [this](https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs#L148)

cc @J-Son89 @smohamedjavid @briansztamfater

Comment (J-Son89) [reply src/status_im/contexts/wallet/account/share_address/view.cljs:38]: I'm not sure, but in the designs it's sometimes mainnet and sometimes Ethereum so that might have affected why. 
Sounds good to choose one 👍

File: src/status_im/common/qr_codes/view.cljs (hunk 1 above)
Comment (shivekkhurana) [reply src/status_im/common/qr_codes/view.cljs]: The constants are already present in this PR: https://github.com/status-im/status-mobile/pull/19150/files

Comment (OmarBasem) [reply src/status_im/common/qr_codes/view.cljs]: Thanks @shivekkhurana I will update it

File: src/status_im/contexts/wallet/account/share_address/view.cljs (hunk 2 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/account/share_address/view.cljs:38]: I have opened an issue https://github.com/status-im/status-mobile/issues/19481

**Comment by OmarBasem** [comment]
This PR fixes a few UI details which I think are straightforward, I think we can skip QA. wdyt @J-Son89 ?

**Comment by J-Son89** [comment]
> This PR fixes a few UI details which I think are straightforward, I think we can skip QA. wdyt @J-Son89 ?

Yeah seems good to me!

File: src/status_im/contexts/wallet/account/share_address/view.cljs (hunk 2 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/account/share_address/view.cljs:38]: @OmarBasem - I believe we were using `Ethereum` as a display name (maybe accidentally from the beginning) instead of `Mainnet` (as per design).

Additionally, this issue was fixed in the PR https://github.com/status-im/status-mobile/pull/19150. It's waiting for Manual QA 😓 . 

IMO, These issues are created due to using the `:ethereum` keyword directly across the codebase. We should use it from the constant ns. It helps a lot in changing later if we do.

Comment (OmarBasem) [reply src/status_im/contexts/wallet/account/share_address/view.cljs:38]: > Additionally, this issue was fixed in the PR https://github.com/status-im/status-mobile/pull/19150. It's waiting for Manual QA 😓 .

Oh okay good to know the issue has already been addressed
