### PR TITLE
fix: wrong navigation bar color in transparent screens

### LINKED ISSUE #18450: Android (Gooogle Pixel7): opening "Jump To" leads to a white google pixel panel on Activity centre (should be black)
On Android (Gooogle Pixel7): opening "Jump To" leads to a white google pixel panel on Activity centre (should be black)

### PR DESCRIPTION
**Pull request by codemaster115**
fixes #18450 

### Summary
Opening 'Jump to' leads to the wrong navigation color

### Testing notes
You can see the video of this case in #17636 

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

status: ready

### CODE REVIEW

**Review by Parveshdhull — DISMISSED** [review]

File: src/status_im/navigation/options.cljs [hunk 1]
```diff
@@ -81,6 +81,7 @@
 
 (def transparent-screen-options
   (merge
+   (statusbar-and-navbar-root)
```
Comment (Parveshdhull) [inline src/status_im/navigation/options.cljs:84]: We are overriding `statusBar` key in the end. So I am little confused, how this is fixing the issue.

Comment (codemaster115) [reply src/status_im/navigation/options.cljs:84]: For these screens, it doesn't override the option.

Comment (Parveshdhull) [reply src/status_im/navigation/options.cljs:84]: I meant, we just have here
```
(merge
{:statusBar ...}
{:statusBar ...})
```

So basically, no effect on result.

Comment (codemaster115) [reply src/status_im/navigation/options.cljs:84]: actually not status bar, it's for navigation bar.

Comment (Parveshdhull) [reply src/status_im/navigation/options.cljs:84]: Thank you for clearing. As https://github.com/status-im/status-mobile/issues/17636 was highlighting issues related to status-bar I got confused with that.

Should we just remove `statusBar` key then? As we are already merging with above function

Comment (codemaster115) [reply src/status_im/navigation/options.cljs:84]: Yeah, I don't think we need `statusBar` key.

Comment (Parveshdhull) [reply src/status_im/navigation/options.cljs:84]: Cool, please remove old `statusBar` key then.

**Review by Parveshdhull — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @codemaster115 Thank you for PR. Unfortunately, One more way to get wrong status bar color on jump to page

## ISSUE 1: [IOS] Status bar color issue after relogin on 'jumpto' page

### Steps:
1. Select light mode
2. Go to jump to page (stay on this page)
3. Relogin

### Actual result:
The status bar color is merged with the background.

image

https://github.com/status-im/status-mobile/assets/52490791/f6319571-640e-4861-b401-d9c6a676218f

### Expected result:
The status bar color is not merged and remains distinct from the background."

**Comment by VolodLytvynenko** [comment]
hey @codemaster115 should the navigation bar color be fixed only on jump to and activity center in range of this PR?
For now, one more place where the navigation bar is with wrong color

## ISSUE 1: [Android] The white navigation bar is shown on syncing page
### Steps: 
1. Go to appearance -> enable light mode 
2. Open syncing page

### Actual result:

The white navigation bar color shown on syncing page when light mode is enabled

https://github.com/status-im/status-mobile/assets/52490791/8be20560-4af7-44a4-a8a9-bd3bfb7cf15c


### Expected result:
The black navigation bar color shown on syncing page when light mode is enabled

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: [Android] The white navigation bar is shown during sync process
### Steps: 
1.  Enable light mode in device settings
2. `User A` Generates the sync QR code
3. `User B` scans the QR
4. Check the navigation panel during sync process

### Actual result:

The white navigation bar color shown on syncing process on the following pages:
- On enable biometrics screen
- On enable notifications screen
- 'Welcome back' screen


https://github.com/status-im/status-mobile/assets/52490791/38127e6a-efd1-4f2e-af07-3d5c225060f7



### Expected result:
The black navigation bar color shown on syncing process

**Comment by codemaster115** [comment]
@VolodLytvynenko Addressed your two comments, so please review again. Thanks.

**Comment by VolodLytvynenko** [comment]
Hey @codemaster115 . Thank you for PR. Issue 1 is fixed. Unfortunately [issue 2](https://github.com/status-im/status-mobile/pull/18451#issuecomment-1893644302) still reproduced. The white navigation bar is displayed during sync flow

### Steps:
1. Enable light 

### Steps: 
1.  Enable light mode in device settings
2. `User A` Generates the sync QR code
3. `User B` scans the QR
4. Check the navigation panel during sync process

### Actual result:
The white navigation bar color shown on syncing process on the following pages:
- On enable biometrics screen
- On enable notifications screen
- 'Welcome back' screen

https://github.com/status-im/status-mobile/assets/52490791/b01a5799-67ce-4f10-8350-dbbaf59c1eac


### Expected result:
The white navigation bar color shown on syncing process

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13960990/Status-debug-logs.1.zip)

**Comment by VolodLytvynenko** [comment]
Sorry, I missed one more place. 

## ISSUE 3: The white navigation bar is shown when gallery is opened

### Steps:
1. Enable light mode
2. Open any chat
3. Open gallery

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/63a10875-e3a0-40e1-aa8e-67a5b7f46e8d

### Expected result:
Black navigation bar is shown when gallery is opened

**Comment by codemaster115** [comment]
@VolodLytvynenko Addressed the above 2 issues.

**Comment by VolodLytvynenko** [comment]
Hey @codemaster115 both [issue 2](https://github.com/status-im/status-mobile/pull/18451#issuecomment-1895400692), [issue 3](https://github.com/status-im/status-mobile/pull/18451#issuecomment-1895407981) still reproduced on Pixel 7a, Android 14. Could you check it please?

**Comment by VolodLytvynenko** [comment]
> Hey @codemaster115 both [issue 2](https://github.com/status-im/status-mobile/pull/18451#issuecomment-1895400692), [issue 3](https://github.com/status-im/status-mobile/pull/18451#issuecomment-1895407981) still reproduced on Pixel 7a, Android 14. Could you check it please?

**Comment by codemaster115** [comment]
Hi, @VolodLytvynenko. I just checked on my emulator(the same version) but it isn't reproduced.
Here are also my screenshots.
Screenshot_1705670259
Screenshot_1705670397

**Comment by VolodLytvynenko** [comment]
> Hi, @VolodLytvynenko. I just checked on my emulator(the same version) but it isn't reproduced. Here are also my screenshots. Screenshot_1705670259 Screenshot_1705670397

@codemaster115 Thank you. I will recheck one more time now

**Comment by VolodLytvynenko** [comment]
Hey @codemaster115, you are right. The issue no longer exists in the latest build. My apologies, it seems I might have installed an old build, which is strange. No issues from my side anymore. PR is ready to be merged
