### PR TITLE
Fix "Offline" section in group chat members #19883

### LINKED ISSUE #19881: Patch "Manage members" entry in group chat
We should patch the functionality (already implemented) "Manage members" in the private group chat context menu to land on the actual functionality

### LINKED ISSUE #19883: Change "Offline" section in group chat members
The "Offline" section in group chat->View members->Manage members section should be changed to just show:
"Members" (there should not be an "online"/"offline" section, only "members"). As it looks the behavior is buggy and is better to simplify instead of fixing for now.

### LINKED ISSUE #19895: Remove option "Add members" from group chat details in case you're already not member of this group
# Bug Report

## Problem 

"Add members" option shouldn't be available in group chat details in case you're already not member of this group

#### Expected behavior

no Add members (or it is disabled)

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/054439da-62b7-4a2a-aaf8-4093aa771f14

### Reproduction

1. User A: create a group chat
2. User A: remove User B from Group chat
3. User B: check Croup details > Add members

### Additional Information

- Status version: nightly 03/05/24
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #19883
fixes #19895
fixes #19881

Actually offline/online sections have been fixed not removed, cc @qoqobolo 

1) Fixed offline/online sections for group chat details
2) Fixed manage members button for admin on group details screen and added it to context menu (renamed "add members" to "manage members")
3) Fixed section list sorted by the first letter for manage members screen

### CODE REVIEW

File: src/status_im/common/home/actions/view.cljs [hunk 1]
```diff
@@ -365,23 +365,22 @@
           :sub-label           nil
           :chevron?            false}))
 
-;; TODO(OmarBasem): to be implemented.
+;; TODO): to be implemented.
```
Comment (Parveshdhull) [inline src/status_im/common/home/actions/view.cljs]: please remove todo, if it addressed

File: src/status_im/common/home/actions/view.cljs [hunk 2]
```diff
@@ -428,18 +427,15 @@
    (when public?
      (when config/show-not-implemented-features?
        (share-group-entry)))])
-
+(def a 1)
```
Comment (Parveshdhull) [inline src/status_im/common/home/actions/view.cljs]: leftover

File: src/status_im/subs/contact.cljs [hunk 3]
```diff
@@ -358,9 +359,20 @@
 (re-frame/reg-sub
  :contacts/group-members-sections
  (fn [[_ chat-id]]
-   [(re-frame/subscribe [:contacts/contacts-by-chat chat-id])])
- (fn [[members]]
-   (let [admins  (filter :admin? members)
+   [(re-frame/subscribe [:contacts/contacts-by-chat chat-id])
+    (re-frame/subscribe [:visibility-status-updates])
+    (re-frame/subscribe [:multiaccount/public-key])
+    (re-frame/subscribe [:multiaccount/current-user-visibility-status])])
```
Comment (Parveshdhull) [inline src/status_im/subs/contact.cljs:365]: should we move this functionality to `re-frame/subscribe [:contacts/contacts` itself?

File: src/quo/components/community/channel_actions/view.cljs [hunk 4]
```diff
@@ -8,9 +8,10 @@
...
-      [:<>
-       [channel-action/view action]
-       (when (not= action (last actions))
-         [rn/view {:width 16}])])
+      (when action
+        ^{:key index}
+        [:<>
+         [channel-action/view action]
+         (when (not= action (last actions))
+           [rn/view {:width 16}])]))
```
Comment (ibrkhalil) [inline src/quo/components/community/channel_actions/view.cljs]: Since we're touching this part of the code, Should we add this style to a `:style` key in the prop map?

File: src/status_im/subs/contact.cljs (hunk 3 above)
Comment (flexsurfer) [reply src/status_im/subs/contact.cljs:365]: good question, first i wanted to do it, but it should be a separate issue

**Comment by flexsurfer** [comment]
@Parveshdhull @ibrkhalil thank you for the review, all comments have been addressed

**Review by Parveshdhull — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Comment by qoqobolo** [comment]
> Actually offline/online sections have been fixed not removed, cc @qoqobolo

Could you please edit the PR by adding a **detailed** description of what exactly was changed here, so that it would be completely clear during testing?
Thank you

**Comment by flexsurfer** [comment]
@qoqobolo done

**Comment by qoqobolo** [comment]
Thanks @flexsurfer, it's really helpful 🙏

### ISSUE 1: The `Manage members` list is not scrollable on Android

I faced an issue on Android that the `Manage members` list is not scrollable, but it's also reproducible in develop.
Would you like to fix it in this PR or it'd be better to log and fix it separately?

**Steps:**
1. Create a group chat
2. Go to `Manage members`
3. Try to scroll down the list

**Device:** Pixel 7a

https://github.com/status-im/status-mobile/assets/67952253/e413ef54-9a2a-4830-a37c-2155c19b0c93

**Comment by flexsurfer** [comment]
thannk @qoqobolo fixed

**Comment by qoqobolo** [comment]
### ISSUE 2: `Add members` instead of `Manage members` when you open this bottom sheet from the context menu

If you create a group chat, open it and go to the context menu > `Manage members`, the `Add members` bottom sheet will be opened instead. None of your contacts will be selected there.
But you open the `Manage members` screen from Group details and then re-open it from the context menu, it'll change to `Manage members` (see the video)

**Steps:**
1. Create a group chat
2. Right after creating press `...` on the group chat screen > `Manage members`
Actual result: `Add members` bottom sheet with no selected contacts
3. Go to group details > `Manage members`
4. Go to the chat screen again > `...` > `Manage members`

https://github.com/status-im/status-mobile/assets/67952253/421e9a81-bf93-4c64-9fcb-72fabc37b261

**Comment by flexsurfer** [comment]
thanks @qoqobolo fixed

**Comment by qoqobolo** [comment]
Thanks for your work @flexsurfer, LGTM now!
PR can be merged.
