### PR TITLE
[#18865] fix: separate edit bio and set bio, update number of profile name characters

### LINKED ISSUE #18788: Updated number of characters in profile name
### Summary

Updated the number of characters in the profile name from 24 to 20 to match with desktop

https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?type=design&node-id=4409-366944&mode=design&t=cHaO9cP4pscMTHNp-4

### effected area

- create profile
- edit profile name

### LINKED ISSUE #18865: Display different toast for update bio and set bio
### Description
follow up for #18765 and Figma comment https://github.com/status-im/status-mobile/pull/18765#:~:text=state%2C%20as%20commented-,here,-%40mohsen%2Dghafouri%20can

I think we should consider treating the 2 cases separately:

- no bio: the button is disabled at first -> type and save -> toast says "Bio added"
- pre-existing bio: possibility to clear it (button is active even if there's no text) -> save -> toast says "Bio updated" (screenshots on the left column)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #18865
fixes #18788

### Summary

Separate the toast message for set bio and edit bio, and update character number in set profile name 

status: ready

### CODE REVIEW

File: src/status_im/contexts/profile/edit/bio/events.cljs [hunk 1]
```diff
@@ -1,22 +1,26 @@
...
 (defn edit-profile-bio
-  [{:keys [db]} [bio]]
-  {:db (assoc-in db [:profile/profile :bio] bio)
-   :fx [[:json-rpc/call
-         [{:method     "wakuext_setBio"
-           :params     [bio]
-           :on-success [:profile/edit-profile-bio-success]}]]]})
+  [{:keys [db]} [new-bio]]
+  (let [{:keys [bio]} (:profile/profile db)]
+    {:db (assoc-in db [:profile/profile :bio] new-bio)
```
Comment (smohamedjavid) [inline src/status_im/contexts/profile/edit/bio/events.cljs]: Maybe we should update the app-db on-success (If the RPC fails, the user would get a perception that the Bio is updated).

File: src/status_im/contexts/profile/edit/bio/events.cljs [hunk 2]
```diff
@@ -1,22 +1,26 @@
...
+     :fx [[:json-rpc/call
+           [{:method     "wakuext_setBio"
```
Comment (J-Son89) [inline src/status_im/contexts/profile/edit/bio/events.cljs:26]: @cammellos, should we start adding contract tests for all new rpc calls? It's rather simple :)

Comment (cammellos) [reply src/status_im/contexts/profile/edit/bio/events.cljs:26]: Sure, makes sense, thanks for pointing this out, @mohsen-ghafouri would you mind creating a contract test for this? @J-Son89 can point you in the right direction

Comment (J-Son89) [reply src/status_im/contexts/profile/edit/bio/events.cljs:26]: for sure, 
I added the first set of tests in 
https://github.com/status-im/status-mobile/pull/18665

please see the wallet tests - https://github.com/status-im/status-mobile/pull/18665/files#diff-a5de5130c6b8a61e01a9fc957ec5546595fcee043de147bd890a732183b45587

you can probably just add a similar ns, like `tests.contract-test.profile-test`

to run the tests, you can run `make test-contract`.

In these test we want to test the rpc requests that we make to status go, but please do so for only the use cases that we use, we don't want to cover cases beyond our use cases 👌 

Any further questions, feel to reach out. Probably we will need to add more documentation etc, any and all feedback will be welcome there too

Comment (mohsen-ghafouri) [reply src/status_im/contexts/profile/edit/bio/events.cljs:26]: is it like integration test that i added here? what's the difference as it will test both app side and rpc endpoint? @J-Son89 
https://github.com/status-im/status-mobile/blob/9362d12bbddea497f4efc943f0510d3194e1d09d/src/tests/integration_test/profile_test.cljs#L60

Comment (J-Son89) [reply src/status_im/contexts/profile/edit/bio/events.cljs:26]: @mohsen-ghafouri - this doc https://www.notion.so/Contract-Test-d47d85b444a94776998767133ab143d7
should describe in further detail the use case.

The TLDR is that Integration tests some of our code too and ensures that certain events etc fire properly and have some e2e like approaches. 
Contract tests are purely testing the RPC result from Status-Go endpoints and are there to ensure that Status-Go don't add breaking changes to any rpc requests that we are using, and more importantly for how we are using them. i.e we are locking in the api that we care about 👍

File: src/status_im/contexts/profile/edit/bio/events.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/profile/edit/bio/events.cljs]: @smohamedjavid resolved

File: src/status_im/contexts/profile/edit/bio/events.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/profile/edit/bio/events.cljs:26]: Added @J-Son89, could you please check again?

File: src/tests/contract_test/profile_test.cljs [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+
+(deftest profile-set-bio-contract
+  (h/log-headline :contract/wakuext_setBio)
+  (rf-test/run-test-async
+   (h/with-app-initialized
+    (h/with-account
+     (contract-utils/call-rpc-endpoint
+      {:rpc-endpoint "wakuext_setBio"
+       :params       ["new bio"]
+       :on-error     #(is (nil? %))})
```
Comment (J-Son89) [inline src/tests/contract_test/profile_test.cljs]: just curious, if you change this to 
`:on-error #(is (not (nil? %))`
does the test fail?

Comment (mohsen-ghafouri) [reply src/tests/contract_test/profile_test.cljs]: it will pass but if api throws any error then RPC will call on-error and test will fail

**Comment by mohsen-ghafouri** [comment]
@J-Son89 @smohamedjavid Could you please double check?

File: src/status_im/constants.cljs [hunk 4]
```diff
@@ -106,7 +106,7 @@
 (def ^:const command-state-transaction-sent 7)
 
 (def ^:const profile-default-color :blue)
-(def ^:const profile-name-max-length 24)
+(def ^:const profile-name-max-length 20)
```
Comment (J-Son89) [inline src/status_im/constants.cljs:109]: this is also used on create profile page?

Comment (mohsen-ghafouri) [reply src/status_im/constants.cljs:109]: yes, moved all logic to one place

**Review by J-Son89 — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Thanks for your PR!
Everything looks fine from my side. As it were followups from design review I'll move it to their recheck.
@Francesca-G

**Review by Francesca-G — APPROVED** [review]
Looks good now ✨
