### PR TITLE
[#20828] feat: display toast for all wallet connect actions

### LINKED ISSUE #20828: Not all toasts are shown for Wallet Connect
# Bug Report

## Problem 
[comment]: # (A problem description)
We're currently not showing all toasts based on the current [design](https://www.figma.com/design/HOJ4lV2ko3jzMjorsDzaoP/Wallet-%2F-dApp-notifications?node-id=0-1&t=LhhTwRIpZ9vjjb9w-0). Should include all the toasts/ephemeral from the "dApps interactions" category.

#### Expected behavior
All relevant toasts from the design are shown

#### Actual behavior
Most toasts from the design are not shown

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #20828

### Summary

rel to this closed PR #20870

In this PR we show toasts when:

- disconnecting dapp (was there already, just updated text)
- disconnecting dapp failed (was there already, just updated text)
- connecting to dapp successful
- rejecting connection
- sign request rejected
- sign request confirmed
- transaction request rejected
- transaction request confirmed

#### Areas that maybe impacted
 
- Dapp communication

status: ready

### CODE REVIEW

**Review by clauxx — APPROVED** [review]
Looks good :+1:

File: src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs [hunk 1]
```diff
@@ -143,35 +143,52 @@
...
      {:fx (concat
            (when-not response-sent?
              [[:effects.wallet-connect/reject-session-proposal
                {:web3-wallet web3-wallet
                 :proposal    (or proposal request)
-                :on-success  #(log/info "Wallet Connect session proposal rejected")
+                :on-success  (fn []
+                               (log/info "Wallet Connect session proposal rejected")
+                               (rf/dispatch [:toasts/upsert
+                                             {:type :positive
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs:189]: Should this toast be of type `:positive` if the session proposal was rejected?

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs:189]: Since this isn’t an error and the user intended to reject the session, we can confirm it was successfully rejected by `:positive` type IMO.

**Comment by mariia-skrypnyk** [comment]
Hey @mohsen-ghafouri !

Thanks for your PR!

1) Have a question regarding such toast:

**disconnecting dapp** 
when we manually in Status app decline a connection request

Screenshot 2024-11-04 at 15 03 57

Shouldn't it be like we see here in Decline section:

https://www.figma.com/design/HOJ4lV2ko3jzMjorsDzaoP/Wallet-%2F-dApp-notifications?node-id=0-1&node-type=canvas&m=dev

Screenshot 2024-11-04 at 15 04 16

2) Please, help me to figure out how can I manually trigger such activity?

**disconnecting dapp failed**

**Comment by mohsen-ghafouri** [comment]
Hello @mariia-skrypnyk, thanks for testing! Manually disconnecting a dapp is different from declining a connection request—each has its own message.

As for the 2nd point, it’s unlikely to trigger unless the WalletConnect library throws an error, which should be rare. Just thinking out loud—if you disconnect a dapp on the dapp side first, would trying to disconnect it again in Status throw any error? 🤔

**Comment by clauxx** [comment]
> ... if you disconnect a dapp on the dapp side first, would trying to disconnect it again in Status throw any error? 🤔

@mohsen-ghafouri disconnecting from the dapp side would trigger a `session_delete` event on the wallet side immediately (or on the next WC initialization if app is closed), so AFAIK the user shouldn't even get the chance to disconnect from the wallet. But we did have client-side bugs a while back where it did error out when trying to disconnect an already disconnected dapp.

**Comment by mariia-skrypnyk** [comment]
> Manually disconnecting a dapp is different from declining a connection request—each has its own message.

So @mohsen-ghafouri in my 1. point I see the correct toast when I decline connection request?

> if you disconnect a dapp on the dapp side first, would trying to disconnect it again in Status throw any error? 🤔

In practice if I disconnect connection on the dApp side then in app connection disconnects automatically and dissapears from the connection list.

Did you have a chance to catch the **disconnecting dapp failed** toast on your dev side? I want to make sure it works in case I can’t emulate this situation manually.

**Comment by mohsen-ghafouri** [comment]
Hey @mariia-skrypnyk i tried to record video for different scenarios, i hope it helps.

In first video : 

- I declined first request
- for second request i approved and dApp successfully connected
- at the end i manually disconnect the dApp successfully

https://github.com/user-attachments/assets/c80d8428-cb07-4ef9-b0e8-783d2d4fcbf8

in second video i could programmatically produce the fail situation that user can't disconnect the dapp and here is the result 


https://github.com/user-attachments/assets/5e1ac7f4-b658-409d-803c-8f6a4b85fe0b

**Comment by mariia-skrypnyk** [comment]
Thanks @mohsen-ghafouri !

1. Now it's clear for me, thanks, your video helped.
2. I see no such validation text in Figma : Failed to disconnect... Can you show me the source of it or it was not made by you?
3. I found that we do not have such toast when disconnect on the dApp side (connect just dissapears from the list with no toast) : 


https://github.com/user-attachments/assets/0a4e4da4-5a02-41bd-b4f4-e84708e70cfc
Can we add this toast?

Everything else is fine all places you've mentioned in a PR.

**Comment by mohsen-ghafouri** [comment]
@mariia-skrypnyk About point 2, there were some conversation about tech limitation and other stuff that @clauxx did with design team, some are available in figma file https://www.figma.com/design/HOJ4lV2ko3jzMjorsDzaoP/Wallet-%2F-dApp-notifications?node-id=1-81335&t=yTFW0izl574K99Tp-4. 

In this PR i just added changes from #20870 with just made it compatible with latest code base changes.

about point 3 there is no requirement that i'm aware about it. we just wanted to show toast for user action that they do inside the status app IMO.

**Comment by mariia-skrypnyk** [comment]
Thanks @mohsen-ghafouri !

2. Ok, thanks for all comments and hystory.
3. We have such requirement in Figma https://www.figma.com/design/HOJ4lV2ko3jzMjorsDzaoP/Wallet-%2F-dApp-notifications?node-id=0-1&node-type=canvas&m=dev

Screenshot 2024-11-05 at 14 21 09

Screenshot 2024-11-05 at 14 20 59

Is it in a scope of your PR?

**Comment by mohsen-ghafouri** [comment]
Sure @mariia-skrypnyk i will update PR, also i couldn't find any reference about display account name when user disconnect from dApp, so i will update text to `Disconnected from {dapp name}`

**Comment by mariia-skrypnyk** [comment]
Hey @mohsen-ghafouri !

Please use this design https://www.figma.com/design/mLyiYPXqu8KetdQONOlZpV/dApp-Interactions?node-id=780-12729&node-type=frame&m=dev for disconnection case.

Discussion is here https://discord.com/channels/1210237582470807632/1274068685266489434/1303689180643065887

**Comment by mohsen-ghafouri** [comment]
Hey @clauxx could you please my last commit? not sure if there is any other way to access to dApp name and account name.

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 2]
```diff
@@ -537,3 +537,10 @@
     (:less-than-three-minutes constants/wallet-transaction-estimation) "1-3"
     (:less-than-five-minutes constants/wallet-transaction-estimation)  "3-5"
     ">5"))
+
+(defn get-account-by-session
+  [db session]
+  (let [accounts                (get-in db [:wallet :accounts])
+        session-account-address (first (:accounts session))
+        [_ address]             (network-utils/split-network-full-address session-account-address)]
+    (get-account-by-address (vals accounts) address)))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/common/utils.cljs]: this util seems specific to wallet-connect, since you're passing the session. You could either move it to the wallet-connect ns or pass the address instead of the session (but then you already have `get-account-by-address` that does almost the same thing)

**Comment by clauxx** [comment]
> Hey @clauxx could you please my last commit? not sure if there is any other way to access to dApp name and account name.

yeah looks good! left just one comment

**Review by alwx — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
Hey @mariia-skrypnyk, I applied changes. but ios pipeline has issue. whenever they resolve the problem. it's ready for test again.

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri thanks !

Ping me please in case you found first that iOS build is ready.

**Comment by mohsen-ghafouri** [comment]
Hey @mariia-skrypnyk it's ready for test.

**Comment by mariia-skrypnyk** [comment]
Thanks @mohsen-ghafouri !

PR can be merged!
