### PR TITLE
[#16111] - toast animation & dismiss

### LINKED ISSUE #16111: Toasts - UI Fixes - dismiss (android issue) and exit animation
Needs an exit animation - cc @xAlisher should have this created already

dismiss for android is not working - is this fixable?

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #16111

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
This PR adds the animation and gesture to show and dismiss animations respectively.

[Video on Android](https://github.com/status-im/status-mobile/assets/90291778/74a14fb0-a8a6-481a-80ee-137d63d02955)

### Review notes

The code for animation was already created but commented out because they were causing a flickering, please check https://github.com/status-im/status-mobile/issues/14752

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- log in
- Trigger different notifications across the app, e.g. mute a chat, send a friend request, etc

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/toast/view.cljs [hunk 1]
```diff
@@ -21,8 +21,7 @@
 
 (defn toast-undo-action
   [duration on-press override-theme]
-  [toast-action-container
-   {:on-press on-press :accessibility-label :toast-undo-action}
+  [toast-action-container {:on-press on-press :accessibility-label :toast-undo-action}
```
Comment (ulisesmac) [inline src/quo2/components/notifications/toast/view.cljs:24]: Just small refactor

File: src/quo2/components/notifications/toast/view.cljs [hunk 2]
```diff
@@ -31,17 +30,17 @@
 
 (defn- toast-container
   [{:keys [left title text right container-style override-theme]}]
-  [rn/view
-   {:style (merge style/box-container container-style)}
+  [rn/view {:style (merge style/box-container container-style)}
```
Comment (ulisesmac) [inline src/quo2/components/notifications/toast/view.cljs:33]: Small refactor

File: src/quo2/components/notifications/toast/view.cljs [hunk 3]
```diff
@@ -57,7 +56,7 @@
          :style               (style/text override-theme)
          :accessibility-label :toast-content}
         text])]
-    (when right right)]])
+    right]])
```
Comment (ulisesmac) [inline src/quo2/components/notifications/toast/view.cljs:59]: Small refactor: `(when right right)` is the same as `right` in this case

File: src/status_im2/common/toasts/animation.cljs [hunk 4]
```diff
@@ -0,0 +1,57 @@
+(ns status-im2.common.toasts.animation
```
Comment (ulisesmac) [inline src/status_im2/common/toasts/animation.cljs:1]: Refactor: New namespace with toast animation related stuff

File: src/status_im2/common/toasts/view.cljs [hunk 5]
```diff
@@ -1,89 +1,56 @@
...
-            [react-native.background-timer :as background-timer]
+            [status-im2.common.toasts.animation :as animation]
             [status-im2.common.toasts.style :as style]
             [utils.re-frame :as rf]))
 
 (defn toast
-  [id]
-  (let [{:keys [type] :as toast-opts} (rf/sub [:toasts/toast id])]
+  [toast-id]
+  (let [{:keys [type] :as toast-opts} (rf/sub [:toasts/toast toast-id])]
```
Comment (ulisesmac) [inline src/status_im2/common/toasts/view.cljs:14]: var rename `id` -> `toast-id` to make it clearer

File: src/status_im2/common/toasts/view.cljs [hunk 6]
```diff
@@ -1,89 +1,56 @@
...
+      (let [duration     (or (rf/sub [:toasts/toast-cursor toast-id :duration]) 3000)
+            on-dismissed (or (rf/sub [:toasts/toast-cursor toast-id :on-dismissed]) identity)
+            create-timer #(reset! timer (background-timer/set-timeout close-toast duration))
+            translate-y  (reanimated/use-shared-value 0)
+            pan-gesture  (animation/pan-gesture {:clear-timer           clear-timer
+                                                 :create-timer          create-timer
+                                                 :translate-y           translate-y
+                                                 :close-toast           close-toast
+                                                 :set-dismissed-locally set-dismissed-locally
+                                                 :dismissed-locally?    @dismissed-locally?})]
```
Comment (ulisesmac) [inline src/status_im2/common/toasts/view.cljs:36]: Mainly moved this logic to animation namespace to make it easier to read and separate animation stuff

File: src/status_im2/common/toasts/view.cljs [hunk 7]
```diff
@@ -1,89 +1,56 @@
...
-                   {:transform [{:translateY translate-y}]}
-                   style/each-toast-container)}
-          [toast id]]]))))
+          {:entering animation/slide-in-up-animation
+           :exiting  animation/slide-out-up-animation
+           :layout   animation/linear-transition
+           :style    (reanimated/apply-animations-to-style
+                      {:transform [{:translateY translate-y}]}
+                      style/each-toast-container)}
+          [toast toast-id]]]))))
```
Comment (ulisesmac) [inline src/status_im2/common/toasts/view.cljs:49]: Add the toast animations and gesture handler

File: src/status_im2/common/toasts/view.cljs [hunk 8]
```diff
@@ -1,89 +1,56 @@
...
-  (let [toasts-ordered (:ordered (rf/sub [:toasts]))]
-    [into
-     [rn/view
-      {:style style/outmost-transparent-container}]
-     (doall
-      (map (fn [id] ^{:key id} [:f> f-container id]) toasts-ordered))]))
+  (->> (rf/sub [:toasts])
+       :ordered
+       (into [rn/view {:style style/outmost-transparent-container}]
+             (map #(with-meta [:f> f-container %] {:key %})))))
```
Comment (ulisesmac) [inline src/status_im2/common/toasts/view.cljs:56]: `into` here was called using `[ ]` instead of `( )`.

Also since we are using `into` we don't need that `doall` call for `map`.
so just refactored to use into and `map` in its xf form.

FYI, another possible refactor would be:

```clojure
[rn/view
 (map (fn [] ,,,)
      toast-ordered)]
```

We don't need `doall` unless we are using `deref` (`@`) inside the `map` function and and `rn/view` works well if we pass a clojure lazyseq (i.e. it doesn't throw any warnings and renders the expected children).

But  I'm using `into` since it was the intented function to be used.

File: src/status_im2/navigation/core.cljs [hunk 9]
```diff
@@ -180,7 +180,10 @@
                                  opts)}})))
 
 ;; toast
-(navigation/register-component "toasts" (fn [] views/toasts) js/undefined)
+(navigation/register-component "toasts"
+                               #(gesture/gesture-handler-root-hoc views/toasts
+                                                                  #js {:flex 0})
+                               (fn [] views/toasts))
```
Comment (ulisesmac) [inline src/status_im2/navigation/core.cljs]: here `:flex 0` is the same as `flex: 0 0 auto` in CSS.
We need this to override the HOC default layour which is `flex 1`.

If we don't override this property, then the toast layout will catch all taps/gestures, so no other action would be available until the toast disappears

File: src/quo2/components/notifications/toast/view.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo2/components/notifications/toast/view.cljs:59]: right!

File: src/status_im2/navigation/core.cljs (hunk 9 above)
Comment (J-Son89) [reply src/status_im2/navigation/core.cljs]: hmm, this seems like it might be worth adding a comment in the code? WDYT?

**Review by J-Son89 — APPROVED** [review]
great stuff @ulisesmac !

File: src/status_im2/navigation/core.cljs (hunk 9 above)
Comment (ulisesmac) [reply src/status_im2/navigation/core.cljs]: Yes! I will add it, I think it's worth it

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac thank you for PR. No issues from my side. Ready to be merged
