### PR TITLE
chat: fix #1390, selection OOB

### LINKED ISSUE #1390: App crashes if delete part of recipient name and select it from suggestions again [send]
### Description

*Type*: Bug

*Summary*: In send or request commands: delete part of the recipient name, suggestions will show, select same recipient -> app crashes

#### Expected behavior
Recipient name is updated in input field
#### Actual behavior
app crashes

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7Y1gwNFN1eDlPUEk
- Open Status
- Open 1-1 chat
- tap on send or request command
- select recipient name
- tap on delete key on the keyboard to delete part of the name (enough to delete 1 character)
- suggestions are shown with recipient name again
- in suggestions, tap on the name -> crash

### Log
[logcrash45.log.txt](https://github.com/status-im/status-react/files/1114962/logcrash45.log.txt)

### Additional Information
* Status version: 0.9.8-56-gd743691+
* Operating System:  Real device Samsung Galaxy S6, Android 6.0.1

### PR DESCRIPTION
**Pull request by oskarth**
fixes #1390 

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
When the input field includes an unmatched " in the input-text, there's a mismatch between the parsed command-args and the length of the text field, causing text selection to be out of bounds. By bounding the new selection to a maximum of the input text length, this is avoided.

#### Example 1 (bad case):

command-args: ["/request" "Abandoned Worried Wolf"]
input-text: "/request \"Abandoned Worried Wolf"]
new-sel: (before PR): 33 
**new-sel: (after PR): 32**

#### Example 2 (good case):
command-args: ["/request" "Abandoned Worried Wolf"]
input-text "/request \"Abandoned Worried Wolf\""
new-sel: (before PR): 33 
new-sel: (after PR): 33

### Steps to test:
- Open Status
- Chat with a user that has many parts in their name (e.g. "Abandoned Worried Wolf")
- Type `/request` and select the user in the suggestions area
- Delete part of the name include the ending `"`
- Click suggestion area
- Notice that it no longer crashes on Android

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: <ready>

### CODE REVIEW

File: src/status_im/chat/handlers/input.cljs [hunk 1]
```diff
@@ -388,7 +388,8 @@
               new-sel      (->> command-args
                                 (take (+ 3 arg-pos))
                                 (input-model/join-command-args)
-                                (count))
+                                (count)
```
Comment (janherich) [inline src/status_im/chat/handlers/input.cljs]: Very minor style point, but parenthesis around `(count)` here are actually superflous, the same can be written as:
```clj
(->> command-args
     (take (+ 3 arg-pos))
     (input-model/join-command-args)
     count
     (min (count input-text)))
```
