### PR TITLE
[#14689] Link previews in chat

### LINKED ISSUE #14689: Port link preview to the new UI
# Bug Report
When any link, there is no preview UI.

#### Actual behaviour
There should be a preview UI :)

### Designs

https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=3190%3A312784&t=IIfupgRbcRTImf7b-0

### PR DESCRIPTION
**Pull request by alwx**
Fixes #14689

This PR re-introduces link previews for chat messages and requests to show link previews when a message with a support link is sent to a chat. All the required UI components are ported to a new design.

Screenshot 2023-01-16 at 14 52 15

Screenshot 2023-01-16 at 14 42 55

### Summary

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

#### Platforms

- Android
- iOS

##### Functional

- chats
- link preview settings

### Steps to test

- Open Status
- Send any supported link to a chat
- Make sure the preview or a request to display preview gets displayed

status: ready

### CODE REVIEW

**Comment by jakubgs** [comment]
The iOS builds for this PR are being built on `x86_64` Macs rather than `aarch64` ones. Please rebase.

File: src/status_im2/contexts/chat/messages/link_preview/events.cljs [hunk 1]
```diff
@@ -89,31 +17,86 @@
...
+  {:db            (assoc-in db [:communities/resolve-community-info community-id] true)
+   :json-rpc/call [{:method     "wakuext_requestCommunityInfoFromMailserver"
+                    :params     [community-id]
+                    :on-success #(rf/dispatch [::community-resolved community-id %])
+                    :on-error   #(do
+                                   (rf/dispatch [::community-failed-to-resolve community-id])
+                                   (log/error "Failed to request community info from mailserver"))}]})
+
+(rf/defn save-link-preview-whitelist
+  {:events [::link-preview-whitelist-received]}
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/link_preview/events.cljs]: we decided to do not use namespaced events https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md#subscription-names-and-event-names

File: src/status_im2/contexts/chat/messages/link_preview/events.cljs [hunk 2]
```diff
@@ -89,31 +17,86 @@
...
+             :link-previews-enabled-sites
+             (if enabled?
+               (conj (get multiaccount :link-previews-enabled-sites #{}) site)
+               (disj (get multiaccount :link-previews-enabled-sites #{}) site))
+             {})))
+
+(rf/defn enable-all
+  {:events [:chat.ui/enable-all-link-previews]}
+  [{{:keys [multiaccount]} :db :as cofx} link-previews-whitelist enabled?]
+  (rf/merge cofx
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/link_preview/events.cljs]: redundant merge

File: src/status_im2/contexts/chat/messages/link_preview/events.cljs [hunk 3]
```diff
@@ -89,31 +17,86 @@
...
-              :link-previews-whitelist
-              whitelist)})
+(defn cache-community-preview-data
+  [{:keys [id] :as community}]
+  (rf/dispatch [::cache-link-preview-data (community-link id) community]))
+
+(rf/defn enable
+  {:events [:chat.ui/enable-link-previews]}
+  [{{:keys [multiaccount]} :db :as cofx} site enabled?]
+  (rf/merge cofx
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/link_preview/events.cljs]: redundant merge

File: src/status_im2/contexts/chat/messages/link_preview/events.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/link_preview/events.cljs]: for all cases in this namespace

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs [hunk 4]
```diff
@@ -0,0 +1,161 @@
+(ns status-im2.contexts.chat.messages.link-preview.view
+  (:require
+   [clojure.string :as string]
+   [i18n.i18n :as i18n]
+   [reagent.core :as reagent]
+   [react-native.core :as rn]
+   [status-im.constants :as constants]
+   [status-im2.contexts.chat.messages.link-preview.events]
+   [status-im2.contexts.chat.messages.link-preview.style :as style]
+   [quo2.components.buttons.button :as quo2.button]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/link_preview/view.cljs]: in status-im2 we request quo2.core as quo and then use it quo/button

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 5]
```diff
@@ -1,6 +1,11 @@
...
-  (:require [status-im.ui2.screens.chat.messages.message :as old-message]))
+  (:require
+   [react-native.core :as rn]
+   [status-im.ui2.screens.chat.messages.message :as old-message]
+   [status-im2.contexts.chat.messages.link-preview.view :as link-preview]))
 
 (defn text-content
   [message-data]
-  [old-message/render-parsed-text message-data])
+  [rn/view {:flex-direction :column}
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: `:flex-direction :column` is by default so no need to specify it

File: src/status_im2/contexts/chat/messages/link_preview/events.cljs (hunk 1 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/link_preview/events.cljs]: Even for something that shouldn't be used outside the namespace? Interesting but okay.

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/link_preview/events.cljs]: yeah, just simpler to do not use it at all, less questions and confusions

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs [hunk 6]
```diff
@@ -0,0 +1,161 @@
...
+                 [rn/view (style/separator)]
+                 [rn/image
+                  {:source              {:uri thumbnailUrl}
+                   :style               (style/image (select-keys preview-data [:height :width]))
+                   :accessibility-label :member-photo}]])]])))})))
+
+(defn link-preview-enable-request
+  []
+  [rn/view (style/link-preview-enable-request-wrapper)
+   [rn/view {:margin 0}
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/link_preview/view.cljs]: Is this required?

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/link_preview/view.cljs]: looks like redundant. its 0 by default

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs [hunk 7]
```diff
@@ -0,0 +1,161 @@
...
+                 [rn/view (style/separator)]
+                 [rn/image
+                  {:source              {:uri thumbnailUrl}
+                   :style               (style/image (select-keys preview-data [:height :width]))
+                   :accessibility-label :member-photo}]])]])))})))
+
+(defn link-preview-enable-request
+  []
+  [rn/view (style/link-preview-enable-request-wrapper)
+   [rn/view
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/link_preview/view.cljs]: redundant view?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs (hunk 7 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/link_preview/view.cljs]: removed it!

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+(defn link-preview-loader
+  [link]
+  (let [cache (rf/sub [:link-preview/cache])]
+    (reagent/create-class
+     {:component-did-mount
+      (fn []
+        (rf/dispatch [:chat.ui/load-link-preview-data link]))
+      :reagent-render
+      (fn []
+        (when-let [{:keys [site title thumbnailUrl error] :as preview-data} (get cache link)]
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/link_preview/view.cljs]: Maybe in `:chat.ui/cache-link-preview-data` event, we rename this key to `thumbnail-url`. We use kebab case everywhere, and this exception of the camel case looks weird

**Review by Parveshdhull — APPROVED** [review]
PR lgtm, thank you

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs [hunk 9]
```diff
@@ -0,0 +1,160 @@
...
+          (when-not community
+            (rf/dispatch [:chat.ui/resolve-community-info community-id]))))
+      :reagent-render
+      (fn []
+        (when-let [community (get cache community-link)]
+          [community-preview community]))})))
+
+(defn link-preview-loader
+  [link]
+  (let [cache (rf/sub [:link-preview/cache])]
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/link_preview/view.cljs]: why we are subscribing to the complete cache here? Can we pass the link to the subscription and only subscribe to that?

**Comment by VolodLytvynenko** [comment]
Hi @alwx thank you for the fixes. The preview looks well. Only one issue is found. Thanx!

**ISSUE 1: The preview is not shown up right away after the link is pasted and sent**

**Steps to reproduce:**
1. Go to -> Privacy and security -> chat link preview -> enable "youtube"
2. Open chat
3. Paste any youtube link

**Actual result:**
A preview of the link is not shown up right away unless the chat is reopened
https://user-images.githubusercontent.com/52490791/212941001-4dbe1cf0-cc3c-4531-bb61-ca85fbf9a710.mp4

**Expected result:**
A preview of the link is shown up right away after the message sending

**ENV:** iPhone 11 Pro Max, Huawei p20 light

**Comment by VolodLytvynenko** [comment]
**ISSUE 2. The preview link is not shown if the user opens the chat after relogin**

**Steps to reproduce:**
1. Go to -> Privacy and security -> chat link preview -> enable "youtube"
2. Open chat
3. Paste any youtube link
4. Log out
5. Login -> Open chat again

**Actual result:**
The preview links are not shown if the chat is initially opened.  (it is shown only after the secondary chat reopens)
https://user-images.githubusercontent.com/52490791/212952506-50c2bd2c-8064-41c2-9150-682c252adc6d.mp4


**Expected result:**
The preview links are shown if the chat is initially opened.

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs (hunk 8 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/link_preview/view.cljs]: Done! (used `camel-snake-kebab` library for it because it was added to the project already)

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs (hunk 9 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/link_preview/view.cljs]: Fixed!

**Comment by alwx** [comment]
@VladimrLitvinenko could you take a look again? Those issues have been fixed.

File: src/status_im2/contexts/chat/messages/link_preview/view.cljs (hunk 8 above)
Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/link_preview/view.cljs]: thank you

File: src/react_native/reanimated.cljs [hunk 10]
```diff
@@ -90,8 +79,10 @@
 ;; so first convert kebab case styles into camel case styles
 (defn apply-animations-to-style
   [animations style]
-  (let [animations (map-keys kebab-case->camelCase animations)
-        style      (apply dissoc (map-keys kebab-case->camelCase style) (keys animations))]
+  (let [animations (utils.collection/map-keys csk/->camelCaseString animations)
```
Comment (flexsurfer) [inline src/react_native/reanimated.cljs:82]: could you please elaborate on this change? cc @Parveshdhull

Comment (Parveshdhull) [reply src/react_native/reanimated.cljs:82]: I think we are migrating to library function instead of using ours. This should ok for now.
But while fixing [issue](https://github.com/status-im/status-mobile/issues/14756) (nil value in reanimated style crashing at runtime), I am also cleaning `apply-animations-to-style` function, so we don't need to convert this anymore, this will be handled by worklet itself. [code](https://github.com/status-im/status-mobile/commit/248b41022e11c80a1cac0e5d8a6e6db828b0127f)

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko could you take a look again? Those issues have been fixed.

hi. @alwx I can't download the builds. Could you check it please in the PR?

**Comment by alwx** [comment]
@VladimrLitvinenko ready now

**Comment by VolodLytvynenko** [comment]
@alwx Thank you for quick reply! I see some conflicts in the PR. Could you resolve them please?

**Comment by alwx** [comment]
@VladimrLitvinenko sorry, that's a bit annoying because I just did that and now something got merged again. Resolved the merge, the build will be ready soon.

**Comment by alwx** [comment]
@VladimrLitvinenko done

**Comment by VolodLytvynenko** [comment]
@alwx thank you for the fixes. Tests are passed. PR is ready to be merged!
