### PR TITLE
[#21305] fix: sort assets by value and collectibles by name

### LINKED ISSUE #21305: SNT is always shown in top on  'select assets', 'bridge', 'Asset to Pay', 'Asset to Receive' pages
### Steps:
1. Open account -> tap 'send' -> Go to  'select assets' page
2. Open account -> tap 'bridge' -> Go to  'bridge' page
3. Go to swap page -> open 'Asset to Pay', 'Asset to Receive' pages

### Actual result:
SNT is always shown at top on the 'select assets', 'bridge', 'Asset to Pay', 'Asset to Receive' pages
image

### Expected result:
Assets are ordered  in descending order of the fiat value on the 'select assets' and 'bridge' pages

- [ ] Default ordering should be by balance in descending order
- [ ] Collectibles should be by collection alphabetically in ascending order (A->Z)
 
discussed with @pedro-et 
https://discord.com/channels/624634427930312714/852533718790570015/1260505506280116335

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 23 Sep, 2024

### LINKED ISSUE #21636: Assets not sorted by fiat balance on "assets to pay" and "assets to receive" screens
### Steps:
1. Go to swap
2. Open "assets to pay" screen 
3. Open "assets to receive" screen 

### Actual result:
Assets not sorted by fiat available balance in descending order

Image

### Expected result:
Assets should be sorted by fiat available balance in descending order on "assets to pay" and "assets to receive" screens
https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=43-170626&node-type=frame&t=M5nVcC6Sxn3Nuue6-0

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 18 Nov, 2024

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21305
also fixes #21636

and I believe it will close this https://github.com/status-im/status-mobile/issues/21636 as well. CC @alwx

## Summary
Assets are ordered in descending order of the fiat value on the 'select assets' and 'bridge' pages

- Default ordering should be by balance in descending order
- Collectibles should be by collection alphabetically in ascending order (A->Z)

### Areas that may be impacted

- collectible list tab
- asset list tab
- select asset and collectible screen

## Steps to test

1. Open account -> tap 'send' -> Go to 'select assets' page
2. Open account -> tap 'bridge' -> Go to 'bridge' page
3. Go to swap page -> open 'Asset to Pay', 'Asset to Receive' pages

### Result

https://github.com/user-attachments/assets/128317b7-b8fc-4d1d-9dc2-9582d52ce392

status: ready

### CODE REVIEW

**Comment by mohsen-ghafouri** [comment]
I believe it will close this https://github.com/status-im/status-mobile/issues/21636 as well. CC @alwx

File: src/status_im/contexts/wallet/collectible/utils.cljs [hunk 1]
```diff
@@ -79,3 +79,10 @@
                      acc)))
                {})
        vals))
+
+(defn sort-collectibles-by-name
+  [collectibles]
+  (sort-by (fn [collectible]
+             (let [name (-> collectible :collectible-data :name)]
+               [(if (or (nil? name) (empty? name)) 1 0) name]))
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/collectible/utils.cljs]: If name is a string, you might want to use `seq` function to check for `nil`

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/utils.cljs]: done

**Review by alwx — APPROVED** [review]

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanks for the PR. Please take a look at the issue

### ISSUE 1 Some collectibles are not sorted by name

**Actual result:** on the video below you can see collectibles `deadpool`, `deBridge..` are displayed in the end of the list after after collectibles starting with letter `V`.

[Status-debug-logs - 2025-01-20T144616.425.zip](https://github.com/user-attachments/files/18477488/Status-debug-logs.-.2025-01-20T144616.425.zip)


https://github.com/user-attachments/assets/52a7e973-253c-4994-8851-d3a46cc83fdf


**Expected result:** collectibles should be sorted in alphabetical order (desc).

**Comment by mohsen-ghafouri** [comment]
Hey @pavloburykh thank for testing it, could you please check again?

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanks for the fix. PR is ready for merge.
