### PR TITLE
fix(communities): view-only channels unsupported

### LINKED ISSUE #22083: "View only" permission channels are not supported on mobile
# Bug Report

## Problem 
"View only" channels are shown as locked on mobile

#### Expected behavior
permission to channel is granted

#### Actual behavior
channel is locked 
On video I demonstrate how I change it to "View and post" and permission is granted 

https://github.com/user-attachments/assets/6bde1595-2be7-48e6-a4c0-5ffc69d3410f

### Reproduction
Prerequisites: user has assets to verify token gated permission (i.e. 1 USDc)

1.  On desktop: create a community and set up the permission "View only" for channel 
2. On mobile: open community page and check the permission for the channel

Community link for reproduction: https://status.app/c/G60AAMQn9ucHlP6925rYAXQrlLU6m10eqF1rbbWWJYEH_MwP-Huok3XrDP6mCW7Sn5Sc2f28vSVZ6A3k-LB-5HJ7Wd-vW3zuGH5f8OSm3TcMykgqyO5yu8qDK3-H6hQSG-d8w5CgQqFKGKByNBaQ9v2Nzv14w_cdUBE-WsiXMrVGjGa1EA==#zQ3shtJ8A3rxUZWcfWDL3vKYQBt3jMPTuf44dJUGfjZjsek66 

If user is required, ping me (note for QA: User `core..`)

### Additional Information

- Status version: nightly 13/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #22083 

## Summary

This PR adds support for view-only channels by fixing bugs related to it.

## Review notes
Some code reformating were also performed.

## Testing notes
You can use the community in the issue description to test this feature.

### Platforms

- Android
- iOS

### Areas that may be impacted

Chats in general. The changes affect locked/unlocked channels and the permissions to reply in chats, so please, focus on this areas.

status: ready

### CODE REVIEW

File: src/legacy/status_im/data_store/communities.cljs [hunk 1]
```diff
@@ -25,7 +25,7 @@
                       (case k
                         "tokenGated"              :token-gated?
                         "canPost"                 :can-post?
-                        "can-view"                :can-view?
+                        "canView"                 :can-view?
                         "hideIfPermissionsNotMet" :hide-if-permissions-not-met?
```
Comment (ulisesmac) [inline src/legacy/status_im/data_store/communities.cljs:29]: the `can-view` key never appeared, we were handling this prop wrongly, maybe due to an update on the status-go response?

File: src/status_im/contexts/chat/events.cljs [hunk 2]
```diff
@@ -47,7 +47,8 @@
 (defn group-chat?
   ([chat]
    (and (multi-user-chat? chat)
-        (not (:public? chat))))
+        (not (:public? chat))
+        (not= (:chat-type chat) constants/community-chat-type)))
   ([cofx chat-id]
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/events.cljs:52]: This predicate returned a false positive, since a community-chat is a multi-user-chat and is not public

File: src/status_im/contexts/communities/events.cljs [hunk 3]
```diff
@@ -348,16 +347,16 @@
 
 (defn navigate-to-community-chat
   [{:keys [db]} [chat-id pop-to-root? community-id]]
-  (let [community-id (or community-id (get-in db [:chats chat-id :community-id]))]
-    (merge
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/events.cljs:352]: Just removed this merge :eyes:

File: src/status_im/contexts/communities/overview/view.cljs [hunk 4]
```diff
@@ -235,34 +235,29 @@
...
+         {:tags            tags
+          :last-item-style style/last-community-tag
+          :container-style style/community-tag-container}])
+      [join-community community]]
+     (when (or joined (not membership-permissions?))
+       [channel-list-component
+        {:on-category-layout              on-category-layout
+         :community-id                    id
+         :on-first-channel-height-changed on-first-channel-height-changed}
+        (add-handlers-to-categorized-chats id chats-by-category joined-or-spectated)])]))
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/overview/view.cljs:248]: Unnecesary form-2 component

File: src/status_im/subs/chats.cljs [hunk 5]
```diff
@@ -123,35 +123,38 @@
...
+
+         (not group-chat)
+         (assoc
+          :contact-request-state (get-in contacts [chat-id :contact-request-state])
+          :able-to-send-message?
+          (and
+           (or (get-in inputs [chat-id :metadata :sending-contact-request])
+               (= constants/contact-request-state-mutual
+                  (get-in contacts [chat-id :contact-request-state])))
+           (not (contains? blocked-users-set chat-id)))))))))
```
Comment (ulisesmac) [inline src/status_im/subs/chats.cljs]: Highly suspect this `cond->` should be reworked, or make sure its clauses are always fully exclusive. With communities, the first statement:

```clojure
(and (chat.events/community-chat? current-chat)
              (get-in community [:chats relative-chat-id :can-post?]))
```

returned `false` and the 2nd one:
```clojure
(and (chat.events/group-chat? current-chat)
              (member? my-public-key current-chat))
```
returned `true`.

So we were setting `able-to-send-message?` as `true` by satisfying the wrong clause.

I didn't reworked this in order to keep the diff smaller and avoid new posible bugs. If we face another problem due to this code, we can reconsider it

File: src/status_im/subs/chats.cljs [hunk 6]
```diff
@@ -123,35 +123,38 @@
...
-        :contact-request-state (get-in contacts [chat-id :contact-request-state])
-        :able-to-send-message?
-        (and
-         (or
-          (get-in inputs [chat-id :metadata :sending-contact-request])
-          (= constants/contact-request-state-mutual
-             (get-in contacts [chat-id :contact-request-state])))
-         (not (contains? blocked-users-set chat-id))))))))
+     ;; 68 Is the length of the community-id prefix in the `chat-id`
+     (let [relative-chat-id (-> current-chat :chat-id (subs 68))]
```
Comment (ilmotta) [inline src/status_im/subs/chats.cljs]: @ulisesmac this logic is already present in the function `data-store/community-chat-id->channel-id`.

File: src/status_im/contexts/chat/events.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im/contexts/chat/events.cljs:52]: Good catch!

**Review by ilmotta — APPROVED** [review]

File: src/status_im/subs/chats.cljs (hunk 5 above)
Comment (ilmotta) [reply src/status_im/subs/chats.cljs]: Great points @ulisesmac. Before changing legacy code, it is said that we should strive to cover with unit tests first, and only then refactor, otherwise we risk introducing regressions by our incomplete understanding of the implementation. This book touches on this https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052

**Review by seanstrom — APPROVED** [review]

File: src/status_im/subs/chats.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/subs/chats.cljs]: Thanks for the book reference @ilmotta :100:

File: src/status_im/contexts/chat/events.cljs (hunk 2 above)
Comment (vkjr) [reply src/status_im/contexts/chat/events.cljs:52]: This logic of detecting if chat is a group chat looks suspiciously complicated. There is a `constants/private-group-chat-type`. Can't we compare `(:chat-type chat)` to it like we do in `(public-chat?)`

File: src/status_im/subs/chats.cljs [hunk 7]
```diff
@@ -123,35 +124,40 @@
...
-       (assoc
-        :contact-request-state (get-in contacts [chat-id :contact-request-state])
-        :able-to-send-message?
-        (and
-         (or
-          (get-in inputs [chat-id :metadata :sending-contact-request])
-          (= constants/contact-request-state-mutual
-             (get-in contacts [chat-id :contact-request-state])))
-         (not (contains? blocked-users-set chat-id))))))))
+     ;; 68 Is the length of the community-id prefix in the `chat-id`
```
Comment (vkjr) [inline src/status_im/subs/chats.cljs:133]: Looks like this constant is not used in the code anymore and comment can be dropped (or moved in a place where this information is relevant), wdyt?

**Review by vkjr — APPROVED** [review]

File: src/status_im/contexts/chat/events.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/events.cljs:52]: Hey @vkjr 

Thanks for the suggestion. I'm aware of that constant, but we have 6 different types of chats and I don't know them all. also I'm not willing to change the condition here since more bugs could arise.

Instead I preferred to just patch to avoid the existing false positive

Comment (vkjr) [reply src/status_im/contexts/chat/events.cljs:52]: @ulisesmac, bur from you runtime inspection, does the value of `(:chat-type chat)` is equal to `constants/private-group-chat-type` in a case that you fixed?
Also maybe it worth adding some testcases, at least for already made fix if we know that this part is fragile, wdyt?

Comment (ulisesmac) [reply src/status_im/contexts/chat/events.cljs:52]: > bur from you runtime inspection, does the value of (:chat-type chat) is equal to constants/private-group-chat-type in a case that you fixed?

I didn't checked for those values.

> Also maybe it worth adding some testcases, at least for already made fix if we know that this part is fragile, wdyt?

Sure, I can add the test case for `group-chat?` fn

**Comment by pavloburykh** [comment]
@ulisesmac thanks for the PR. Please take a look at the issues below. 

### ISSUE 1 Reactions are displayed in message longtap menu in view only channels

This is probably some old issue, not related directlly to PR. But would be nice to be fixed in scope of current PR. It's up to you @ulisesmac 

**Steps:** 

1. Join view only channels
2. Longtap on any message in channel
3. See if reactions are displayed in longtap menu

**Expected result:** reactions should not be displayed, as user cannot set reactions in view only channel

**Actual result:** reactions are displayed, despite user cannot apply them in view only channel


https://github.com/user-attachments/assets/9e998271-333a-4564-bbe5-b41f9ca63f49

**Comment by pavloburykh** [comment]
@ulisesmac @ilmotta Wanted to share my experience regarding testing permissions. In some aspects it is quite painful because permission updates seem to work very bad. Below I will describe couple of cases. These issues are not related to current PR, so probably should be investigated separately. 

### Case 1 Updates of channel permissions on Admins side are not applied for Mobile member until he re-joins community

**Preconditions:** 

Mobile user is a member of community and has access to token gated channel (meets requirements). 

**Steps:** 

1. Admin control node updates permission to the channel so Mobile user does not meet requirements anymore
2. See if channel becomes locked for Mobile user

**Actual result:** channel is not locked, user can enter the channel view and post messages depending on channel permissions. Permissions are updated only after user leaves and re-joins community from scratch (see video below). 

The same situation in other directions: admin updates permission so mobile member who previously didn't meet requirements now meets them but still does not have access to the channel. 

https://github.com/user-attachments/assets/406f4c91-d5e1-4609-8308-22790f041ba1


### Case 2 Removing/adding the additional wallet account which holds tokens required for channel permission does not impact accessibility of token gated channels

**Preconditions:** 

Mobile user imports wallet account which holds required tokens for access in token gated channel

**Steps:** 

1. User joins community with token gated channels. User has access to token gated channels because he holds enough tokens on imported wallet account. 
2. User removes wallet account which holds required tokens
3. See if user still has access to token gated channels

**Expected result:** user should loose access to token gated channel as he no longer holds required tokens

**Actual result:** user still has access to token gated channel despite he does not meet requirements anymore. Moreover, even if user leaves and then re-joins community he will still have access to channels. Looks like if user once shared imported account during initial community join this account somehow caches on backend side and system acts like user still has this account despite it has been already removed. 

Same works in other side: if Mobile member previously didn't have access to token gated channel, he will not get this access even after importing wallet account which holds required tokens.

**Comment by pavloburykh** [comment]
There might be more cases, those are only some of them. Just wondering, at which point permission updates on control node side should be applied for community members? And at which point updates on community member side should be applied on control node side? Probably it sometimes may take a lot of time, but how much? Or maybe there are some existing issues on client side which result in problems related to sending/receiving data to/from control node.

**Comment by pavloburykh** [comment]
Basically, this PR has fixed initial issue with View-only permission not been working at all on mobile. But when I proceed with more deeper testing of permissions I am just facing global issues (as described above) and probably not related to this PR.

**Comment by ilmotta** [comment]
@ulisesmac @pavloburykh If you uncovered many issues outside the scope of the PR, I think it's still valuable to capture them as issues outside this PR (unless they are already documented). If it's difficult to QA, it's probably going to be bad for users, so let's endure some of the pain. But perhaps then, let's not try to merge this PR necessarily if it's difficult, but since we are here, we can use this PR for learning purposes to help build up the (bug) scope regarding token gated communities.

Given our goal of validating community features to users and marketing it, with the help of the Desktop team, we may need to actually fix some of these issues in 2.34 or later. If not, understanding how problematic the features operate, the investigation from QA can at least be more evidence of how we should consider simplifying/removing certain token-gated features.

Does that sound good and is the plan clear in your opinion?

**Comment by ulisesmac** [comment]
@ilmotta Since I'm already paying attention to communities, I can help to solve the issues.

I'd prefer to have the issues reported separately, merge this PR and then fix them gradually.
Also we might need to align with designers and (maybe Volo?) to clarify the requirements on this feature.

**Comment by ilmotta** [comment]
> @ilmotta Since I'm already paying attention to communities, I can help to solve the issues.
> 
> I'd prefer to have the issues reported separately, merge this PR and then fix them gradually. Also we might need to align with designers and (maybe Volo?) to clarify the requirements on this feature.

@ulisesmac Token gated channels are full of problems as far as we've seen and most fixes will require changes in status-go. The expertise on fixing some of these bugs lie in the Desktop team members, but we can help as well. I agree on reporting bugs unrelated to your PR in separate issues, that would be helpful for us to understand better the full scope. @pavloburykh 

But in 2.34 we won't be able to work much on token-gated related bugs. Next Monday we will have a call with the Desktop team and Design team to review the product briefs (high-level features defined by Volo) that we will need to work on in 2.34 and I can tell you we will be busy with the upcoming features and the other bugs we already have on our plate :)

Once you finish this PR, a good one that I got approval for our team to work for a few days is https://github.com/status-im/status-mobile/issues/21896 or https://github.com/status-im/status-mobile/issues/21649.

**Comment by pavloburykh** [comment]
@ulisesmac thank you for the PR. I agree with @ilmotta that probably most of the described above issues are related to status-go. I will log them separately so we can investigate once we decide it to be a priority. 

Current PR is rested and ready for merge. 

**What has been tested:** 

1. View-only channel permission support has been added (https://github.com/status-im/status-mobile/issues/22083 is fixed). User can view channel history but cannot post. 
2. Checked different kinds of permissons (i.e view only, veiw and post, anyone can view only etc) with different kinds of tokens including minted ones.
3. Smoke checked token gated communities (become a member permission)


I have logged a separate issue related to channel permissions where I described couple of bugs which probably have common root cause https://github.com/status-im/status-mobile/issues/22296. I can log separate issues for each bug if needed. I am not even sure this is something which should be handled by mobile team, it is probably related to status-go as has been mentioned by @ilmotta and we are living with those issues for quite a long time I suppose. 

Another issue which I have logged https://github.com/status-im/status-mobile/issues/22297 is related to mobile and can fixed depending on priorities. I consider it to be low priority but feel free to prioritise @ilmotta in case you disagree.
