### PR TITLE
Fix chat lightbox shadow appearing when scrolling

### LINKED ISSUE #17555: Unwanted shadow effect when scrolling image description (IOS)
Originally reported in 1.25 review https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=3hX9TSRmmYFkJJHJ-0#567102205

Reproducing on iPhone X, IOS 16.7

**Steps:** 

1. Open any chat
2. Send a message containing image and about 9 lines if text
3. Open the sent image
4. Start scrolling the image description 
5. Continue scrolling after the whole description is expanded
6. Pay attention at shadow effect which appears during scrolling

**Actual result:** 

photo_2023-10-05 12 22 40

https://github.com/status-im/status-mobile/assets/97245802/7c7ca489-ca3f-4978-9e23-7e56ef7c2749

**Expected result:** shadow should not appear

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #17555

### Summary

Removed the "rogue" shadow effect, which happens when the message inside the lightbox component is fully expanded and the user scrolls the content further (bounce effect).

Additionally, I noticed a few differences with the [designs](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372864&mode=design&t=OEAQFb3NKTeqDUlR-4) so added a few changes to the gestures/styles, namely:
1. Gestures felt a bit weird because of using scrollview together with the pan handler e.g. can't drag down overflowing text since the scrollview takes over the touches from the pan handler (which is needed to allow scrolling the text up)
2. Background opacity was "re-starting" on text (that doesn't get to the top of the screen) if dragging it repeatedly when already fully expanded
3. When scrolling off-screen, the "draggable" bar should be hiding behind the header together with the text
4. Text can't be dragged lower that the initial position anymore (was causing issues with opacity, etc)
5. Changed the top/bottom gradients according to designs
6. Pressing text that covers the whole screen will move it below the header, meaning also that pressing it when it is already scrolled behind the header will move it to the top as well. This is helpful for _really_ long text, so the user can get to the beginning by pressing on it while being consistent with the expanding behaviour.
7. Fixed styles and removed gestures for one-lined text, according to designs

@OmarBasem since you worked on it originally, please have a look to make sure I didn't miss/break anything.

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open any chat
- Send a message containing image and about 9 lines if text
- Open the sent image
- Start scrolling the image description
- Continue scrolling after the whole description is expanded
- Pay attention at shadow effect which appears during scrolling

### Before and after screenshots comparison

https://github.com/status-im/-mobile/assets/21865759/f44b07f2-7637-4e78-89e0-cd1ab98e6a73

| Figma (if available) | iOS (if available)    | Android (if available)
| --- | --- | --- |
| Please embed Image/Video here of the before and after.  |     | Please embed Image/Video here of the before and after. |

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/lightbox/bottom_view.cljs [hunk 1]
```diff
@@ -49,15 +49,15 @@
...
 (defn bottom-view
   [messages index scroll-index insets animations derived item-width props state]
   (let [padding-horizontal (- (/ item-width 2) (/ c/focused-image-size 2))]
     [reanimated/linear-gradient
-     {:colors [colors/neutral-100-opa-100 colors/neutral-100-opa-50]
-      :start  {:x 0 :y 1}
-      :end    {:x 0 :y 0}
-      :style  (style/gradient-container insets animations derived)}
+     {:colors   [colors/neutral-100-opa-100 colors/neutral-100-opa-80 colors/neutral-100-opa-0]
+      :location [0.2 0.9]
```
Comment (clauxx) [inline src/status_im2/contexts/chat/lightbox/bottom_view.cljs:57]: NOTE: spreading out the gradient to darken the bottom image list

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 2]
```diff
@@ -36,25 +37,31 @@
...
+                          constants/top-view-height))]
+    (reanimated/apply-animations-to-style
+     {:opacity (reanimated/interpolate derived-value
+                                       [max-height (+ max-height constants/line-height)]
+                                       [0 1])
+      :top     (reanimated/interpolate top
+                                       [0 (- max-height)]
+                                       [initial-top (- initial-top max-height)]
+                                       {:extrapolateLeft  "clamp"
+                                        :extrapolateRight "clamp"})}
```
Comment (clauxx) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs:52]: NOTE: sticking the top gradient under the header after scrolling past it

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 3]
```diff
@@ -36,25 +37,31 @@
...
-                 constants/text-margin
-                 (* constants/line-height 2))
-    :z-index  1}))
+  [{:keys [derived-value]} {:keys [top]} insets max-height]
+  (let [initial-top (- (+ (:top insets)
+                          constants/top-view-height))]
+    (reanimated/apply-animations-to-style
+     {:opacity (reanimated/interpolate derived-value
+                                       [max-height (+ max-height constants/line-height)]
+                                       [0 1])
```
Comment (clauxx) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs:47]: NOTE: making sure the top gradient is only visible once reaching the header (> `max-height`)

File: src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs [hunk 4]
```diff
@@ -8,23 +8,32 @@
...
+         (let [event-value     (oops/oget e "translationY")
+               old-value       (reanimated/get-shared-value saved-top)
+               new-value       (+ old-value event-value)
+               progress        (/ (- new-value) max-height)
+               upper-boundery? (< new-value (- full-height))
+               lower-boundary? (and (> new-value (- constants/text-min-height))
+                                    (pos? event-value))]
+           (when (and (not upper-boundery?) (not lower-boundary?))
+             (reanimated/set-shared-value overlay-opacity progress)
+             (reanimated/set-shared-value derived-value (- new-value))))))
```
Comment (clauxx) [inline src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs]: NOTE: adding boundaries so that the text can't be scrolled lower than its initial position and higher than the size of the text.

File: src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs [hunk 5]
```diff
@@ -8,23 +8,32 @@
...
       (gesture/on-end
        (fn []
-         (if (or (> (- (reanimated/get-shared-value derived-value))
-                    (reanimated/get-shared-value saved-top))
+         (if (or (and
+                  (not (> (reanimated/get-shared-value derived-value) max-height))
+                  (> (- (reanimated/get-shared-value derived-value))
+                     (reanimated/get-shared-value saved-top)))
```
Comment (clauxx) [inline src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs]: NOTE: don't hide the text if scrolling down the text hidden behind the header

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs [hunk 6]
```diff
@@ -33,50 +27,62 @@
...
+         [gesture/gesture-detector
+          {:gesture (-> (gesture/gesture-tap)
+                        (gesture/enabled expanding-message?)
+                        (gesture/on-start (fn []
+                                            (utils/expand-sheet animations
+                                                                expanded-height
+                                                                max-height
+                                                                overlay-z-index
+                                                                expanded?
+                                                                text-sheet-lock?))))}
```
Comment (clauxx) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: NOTE: using the tap gesture instead of the `touchable-opacity`, since it was behaving weirdly i.e. not all taps were always recognised after the scroll changes. I guess it's due to the pointer events being hijacked by the pan handler.

**Review by ajayesivan — APPROVED** [review]
LGTM! Nice work @clauxx 🎉

**Comment by OmarBasem** [comment]
Hi @clauxx, thanks for your PR!

I have checked the builds and I noticed a bug. Pulling the text drawer up and down (without releasing touch) makes the images unscrollable. That's probably because the background opacity component is still displayed on top.

**Comment by OmarBasem** [comment]
> Hi @clauxx, thanks for your PR!
> 
> I have checked the builds and I noticed a bug. Pulling the text drawer up and down (without releasing touch) makes the images unscrollable. That's probably because the background opacity component is still displayed on top.

I noticed when dragging the text drawer down, it doesn't go down to the very end (part of the third line is visible). So that's why the background opacity component is still visible preventing scrolling

**Comment by ilmotta** [comment]
@clauxx, one thing that confused me happened a few times. In this video I scroll to the last line, and then I start pulling from the center side of the screen to scroll up, but as you can see, my gesture is sometimes detected to start closing the expanded text and then I need to scroll right on top of the text to not trigger the closing gesture.

[scroll-behavior.webm](https://github.com/status-im/status-mobile/assets/46027/ceb9501e-59a9-463c-ab48-31785a1fa304)

**Comment by clauxx** [comment]
> @clauxx, one thing that confused me happened a few times. In this video I scroll to the last line, and then I start pulling from the center side of the screen to scroll up, but as you can see, my gesture is sometimes detected to start closing the expanded text and then I need to scroll right on top of the text to not trigger the closing gesture.
> 
>  scroll-behavior.webm

Ooof, this doesn't look right. Have to test it on android again. Thanks!

**Comment by clauxx** [comment]
> > @clauxx, one thing that confused me happened a few times. In this video I scroll to the last line, and then I start pulling from the center side of the screen to scroll up, but as you can see, my gesture is sometimes detected to start closing the expanded text and then I need to scroll right on top of the text to not trigger the closing gesture.
> > scroll-behavior.webm
> 
> Ooof, this doesn't look right. Have to test it on android again. Thanks!

@ilmotta Weird. Tried on an android simulator and it looks fine (except for the missing gradient at the bottom, which will fix). Are you sure you're on the latest commit?

https://github.com/status-im/status-mobile/assets/21865759/2af81ce8-79eb-499f-b815-a91e58ad59c6

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 7]
```diff
@@ -13,10 +13,11 @@
     :left     0
     :right    0}))
 
-(def text-style
+(defn text-style
+  [expanding-message?]
   {:color             colors/white
    :margin-horizontal 20
-   :margin-bottom     constants/text-margin
+   :align-items       (if expanding-message? nil :center)
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs]: Suggestion

```clojure
(when-not expanding-message? :center)
```

File: src/status_im2/contexts/chat/lightbox/style.cljs [hunk 8]
```diff
@@ -70,6 +70,7 @@
     :overflow       :visible
     :bottom         0
     :padding-bottom (:bottom insets)
+    :padding-top    c/bottom-view-extra-gradient
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/style.cljs]: I sometimes see `constants/*` and sometimes `c/*`. It would be good to be consistent. The choice in the past had been for the longer name `constants/*`. Just so you know next time you see such code, it's not your responsibility in this PR to fix though :)

File: src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs [hunk 9]
```diff
@@ -8,23 +8,32 @@
...
+                                    (pos? event-value))]
+           (when (and (not upper-boundery?) (not lower-boundary?))
+             (reanimated/set-shared-value overlay-opacity progress)
+             (reanimated/set-shared-value derived-value (- new-value))))))
       (gesture/on-end
        (fn []
-         (if (or (> (- (reanimated/get-shared-value derived-value))
-                    (reanimated/get-shared-value saved-top))
+         (if (or (and
+                  (not (> (reanimated/get-shared-value derived-value) max-height))
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs]: `(reanimated/get-shared-value derived-value))` is called 5 times within `on-end`, it's better to extract to a local binding.

File: src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs [hunk 10]
```diff
@@ -8,23 +8,32 @@
...
+                          (when (not expanded?)
+                            (reanimated/animate gradient-opacity 0))))
       (gesture/on-update
        (fn [e]
-         (let [new-value     (+ (reanimated/get-shared-value saved-top) (oops/oget e "translationY"))
-               bounded-value (max (min (- new-value) expanded-height) constants/text-min-height)
-               progress      (/ (- new-value) max-height)]
-           (reanimated/set-shared-value overlay-opacity progress)
-           (reanimated/set-shared-value derived-value bounded-value))))
+         (let [event-value     (oops/oget e "translationY")
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs]: We can use keywords too as the args to `oget`. The only practical advantage I can think of is that keywords are allocated only once, so `:translationY` would be allocated once and reused.

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs [hunk 11]
```diff
@@ -13,13 +13,7 @@
...
 
-(defn bar
-  [text-height]
-  (when (> text-height (* constants/line-height 2))
-    [rn/view {:style style/bar-container}
-     [rn/view {:style style/bar}]]))
-
-(defn text-sheet
+(defn- text-sheet
   [messages overlay-opacity overlay-z-index text-sheet-lock?]
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs:17]: Just commenting for awareness, but it's up to you if you want to do anything about this. It wasn't introduced by your PR.

I was curious to see why we needed the collection `messages`, and it turns out only the first one is needed, and only `chat-id` and `content` keys are used. Reagent can perform significantly better the simpler the args we pass to components because the equality checks become cheaper, so it decides quicker if any given component should be recomputed. `message` is a data structure with a bunch of data.

It's not a measurable problem in isolation for the most part, but it's a good practice I think we should try to better follow. This practice is well documented too.

**Review by ilmotta — APPROVED** [review]
@clauxx, very good work in this PR! It feels smoother in my tests too when compared to develop.

About my bug report, I must have tested in the wrong branch or wrong revision because I could not reproduce again. Sorry to cause any trouble.

You are aware of the shadow issue, but I'm approving the PR in advance because I don't have anything else to add.

File: src/status_im2/contexts/chat/lightbox/style.cljs (hunk 8 above)
Comment (clauxx) [reply src/status_im2/contexts/chat/lightbox/style.cljs]: I think in smaller PRs it could be viable to add consistency like this. Will keep in mind for the future.

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs (hunk 7 above)
Comment (clauxx) [reply src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs]: btw recently found out GH has a suggestion feature from which small fixes like this can be committed quickly
```suggestion
   :align-items       (when-not expanding-message? :center)
```

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs (hunk 11 above)
Comment (clauxx) [reply src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs:17]: Yeah it looked weird to me as well. Also with the lack of typing, I think we should be more explicit through the props we're passing. Hopefully with `malli` we'll think twice before passing unnecessary data, although I see this being an issue more with components outside quo2.

**Comment by clauxx** [comment]
> Hi @clauxx, thanks for your PR!
> 
> I have checked the builds and I noticed a bug. Pulling the text drawer up and down (without releasing touch) makes the images unscrollable. That's probably because the background opacity component is still displayed on top.

@OmarBasem Fixed the issue. Also removed the worklet for the text-sheet as it seems unnecessary, as the same can be achieved through an interpolation which makes it more readable (at least for me 😄), but let me know if it had a different purpose.

**Review by OmarBasem — APPROVED** [review]
Good job! 🚀

**Comment by OmarBasem** [comment]
> > Hi @clauxx, thanks for your PR!
> > I have checked the builds and I noticed a bug. Pulling the text drawer up and down (without releasing touch) makes the images unscrollable. That's probably because the background opacity component is still displayed on top.
> 
> @OmarBasem Fixed the issue. Also removed the worklet for the text-sheet as it seems unnecessary, as the same can be achieved through an interpolation which makes it more readable (at least for me 😄), but let me know if it had a different purpose.

It's fine, that was it's purpose, since you are using interpolation now so it's not a problem

File: src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs [hunk 12]
```diff
@@ -68,5 +82,5 @@
 
 (defn init-derived-animations
   [{:keys [derived-value]}]
-  {:height (worklet/text-sheet derived-value true)
-   :top    (worklet/text-sheet derived-value false)})
+  {:height derived-value
+   :top    (reanimated/interpolate derived-value [0 1] [0 -1])})
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs:94]: Are you interpolating the `top` value between `0` and `-1` ?

Comment (clauxx) [reply src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs:94]: I'm using interpolation to flip the `derived-value`. Since the interpolation is not clamped, it will be applied to the entire range of values.

**Comment by VolodLytvynenko** [comment]
Hi @clauxx thank you for PR. Take a look the found issues:

## ISSUE 1: Autoscrolls occurs after tapping a link at the bottom part of opened image
### Steps to Reproduce:
1. Send a message with the following characteristics:
  - Contains a long text, at least 400 characters
  - Includes a link (Note: The link should be located in the bottom part of the message)
  - Contains an attached image
2. Open the image.
3. Tap on the link.

### Actual Result:
After tapping the link, when it's located at the bottom, a minor scrolling action occurs.

https://github.com/status-im/status-mobile/assets/52490791/0c8017dd-ed73-4c99-9dce-180121c6ed6a

### Expected Result:
Tapping a link should not trigger any scrolling.

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: [IOS] Slightly visible gap between shadow and bottom of the opened image
### Steps:
1. Send the message with the image
2. Open the image
3. Check the bottom part of the screen of opened image

### Actual result:
The slightly visible gap is shown between the shadow and the bottom part of the screen of the opened image.

image

### Expected result:
There should be no gap between the shadow and the bottom part of the screen of the opened image.

### Device:
- Real device iPhone 11 Pro Max, IOS 16

**Comment by VolodLytvynenko** [comment]
I've also identified additional issues related to the opened image, and it appears that they are present in the latest develop version as well. While I can see that you've fixed some extra issues in the current PR, could you please take a look to see if these can be fixed within the scope of this PR, or if it's better to address them separately?

## ISSUE 3: Elements such as the share button and close button do not appear on the image screen after the image is tapped.

### Steps to Reproduce:
1. Send an image in the chat.
2. Open the image.
3. Tap the image to hide the elements such as the share button and close button.
4. Scroll on the image a bit.
5. Tap on the image again to make the elements reappear.

### Actual Result:
The elements: "share" button and "close" button, do not reappear on the image screen after the image is tapped.

https://github.com/status-im/status-mobile/assets/52490791/2a37cf1c-0650-4e9b-ad60-af10e6c9bf36


### Expected Result:
The elements should reappear after the image is tapped again.

### ENV:
- real device: iPhone 11 Pro max, IOS 16
- real device: Pixel 7a, Android 13

**Comment by VolodLytvynenko** [comment]
## ISSUE 4: Elements persist on image screen after tapping and scrolling text

### Steps to Reproduce:
1. Send an image within a chat that includes long text
2. Open the image.
3. Scroll through the text, ensuring it doesn't cover the entire image .
4. Tap on the image in an area not covered by the text.

### Actual Result:
Elements like the "share" and "close" buttons remain visible on the image screen even after tapping the image.

https://github.com/status-im/status-mobile/assets/52490791/1ad9d9bc-817d-47e7-b4e8-bb73b8fb21ca


### Expected Result:
The elements should disappear after tapping the image.

### Environment:
Real device: iPhone 11 Pro Max, iOS 16
Real device: Pixel 7a, Android 13

**Comment by clauxx** [comment]
@OmarBasem @ilmotta @ajayesivan @VolodLytvynenko FYI pushed 3 new commits for the QA issues.

**Comment by VolodLytvynenko** [comment]
Hi @clauxx thank you for PR. Issues are fixed. Take a look please a failed integrations test https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-17664/11/consoleText

Hi @Francesca-G Could you take a look please current PR?

**Comment by clauxx** [comment]
> Hi @clauxx thank you for PR. Issues are fixed. Take a look please a failed integrations test https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-17664/11/consoleText
> 
> Hi @Francesca-G Could you take a look please current PR?

Thank you! Done!

**Comment by VolodLytvynenko** [comment]
@clauxx Apologies. Hold on merging this PR after the design review, please. Need to rerun and investigate e2e one more time. I let you know if everything is alright

**Comment by VolodLytvynenko** [comment]
@clauxx е2е failures are not related to this PR. Ready to be merged from my side again :) Thank you!

**Comment by clauxx** [comment]
> @clauxx е2е failures are not related to this PR. Ready to be merged from my side again :) Thank you!

@VolodLytvynenko Thank you! 

@Francesca-G the PR is ready for design review

**Review by Francesca-G — COMMENTED** [review]
Here's the Figma [frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=7288%3A15294&mode=design&t=iSKJKYDuAZDvPL9D-1) with the design review :)

**Comment by clauxx** [comment]
@VolodLytvynenko @Francesca-G  adjusted based on the design feedback

**Review by Francesca-G — APPROVED** [review]
Shadow looks good now 👍

Adding follow up required label because of the handle, as you can see it looks too visible compared to design:

Screenshot 2023-10-27 alle 09 22 40
Screenshot 2023-10-27 alle 09 22 50

**Comment by clauxx** [comment]
> Shadow looks good now 👍
> 
> Adding follow up required label because of the handle, as you can see it looks too visible compared to design:
> 
> Screenshot 2023-10-27 alle 09 22 40 Screenshot 2023-10-27 alle 09 22 50

@Francesca-G fixed it here, as it's not worth a follow-up issue for this small change. If I have your approval, I guess it can be merged, right @VolodLytvynenko?

**Comment by churik** [comment]
@clauxx merge it!

**Comment by clauxx** [comment]
@VolodLytvynenko there's small issue with the commits you co-authored. They're not `verified`, as in the commits are not signed, so they can't be merged. There's a [doc](https://github.com/status-im/status-mobile/blob/233d1b3261f76067c93e51b84acbd1a9c6382d49/doc/starting-guide.md#configure-gpg-keys-for-signing-commits) on how to set it up, but if you have questions or need help with that let me know. I fixed it here by hand-picking the commits, but it's easier for the future if all commits are verified when co-authoring.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko there's small issue with the commits you co-authored. They're not `verified`, as in the commits are not signed, so they can't be merged. There's a [doc](https://github.com/status-im/status-mobile/blob/233d1b3261f76067c93e51b84acbd1a9c6382d49/doc/starting-guide.md#configure-gpg-keys-for-signing-commits) on how to set it up, but if you have questions or need help with that let me know. I fixed it here by hand-picking the commits, but it's easier for the future if all commits are verified when co-authoring.

Hi @clauxx just added the GPG keys. Thanx!
