### PR TITLE
[#16481] Fix unread badge group chats

### LINKED ISSUE #16481: Unread counter is shown instead of unread badge for regular messages in a group chat and chat tab
### Steps to reproduce:
1. Be a member of a group chat.
2. Send a non-mention message to the group chat.
3. Check the display of the unread indicator.

### Actual result:
The unread counter is shown instead of an unread badge for non-mention messages in the group chat and chat tab
image
image

### Expected result:
- An unread badge should be displayed instead of the unread counter for regular (non-mention and non-reply) messages in the group chat

-  An unread badge should be displayed instead of the unread counter for regular (non-mention and non-reply) messages in the chat tab

image

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1424-342207&mode=design&t=gmnAl5Vb0rMg8CJ9-0

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #16481

### Summary

This PR fix the badge showed for group chats, instead of showing a counter when a non-mention message arrives, now shows the gray dot as in [designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=10732-130432&mode=design&t=Z6hZDu3Ilwu46l04-4).

now:
image

before:
image

Also this PR fixes:

- The badge component was not using customization color
- The badge component was not correctly aligned vertically and horizontally
- Since the badge component was misaligned, the text was not using the expected ellipsis, not it is using it.

An image showing the differences in the previous screens:
image

### Review notes

I added two `TODO`s in the code, I wanted to use the `grey-dot` component but it's not exposed as part of the quo2 library, so I noticed, actually, this component to show 1:1 chats should be part of our library, instead, it is being created in `status-im2.contexts`.

I created an issue to solve it:
#16611

To solve this issue, I copied the gray button styles and added a note to be deleted when the component is moved to  the quo2 library.

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- group chats

### Steps to test

- Open Status
- Create a chat group.
 - Send a message (without mention) in the chat group. the notification badge in the group listing for other uses should be a gray dot.
- Mention a user within the chat group, look at the notification should be a badge with the number of unread mentions
- Send a normal message to a user, the notification should be a badge with the number of unread messages.

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/info_count.cljs [hunk 1]
```diff
@@ -3,22 +3,27 @@
...
+(defn- counter-style
+  [customization-color overwritten-styles]
+  (merge {:width            16
+          :height           16
+          :position         :absolute
+          :right            22
+          :border-radius    6
+          :justify-content  :center
+          :align-items      :center
+          :background-color (colors/custom-color-by-theme customization-color 50 60)}
```
Comment (ulisesmac) [inline src/quo2/components/notifications/info_count.cljs:15]: Small refactor and now receives customization-color

File: src/status_im2/contexts/chat/home/chat_list_item/style.cljs [hunk 2]
```diff
@@ -21,15 +21,31 @@
...
-   :top      16})
-
 (defn timestamp
   [muted?]
-  {:color       (or (when muted?
-                      colors/neutral-50)
-                    (colors/theme-colors colors/neutral-50 colors/neutral-40))
+  {:color       (if muted?
+                  colors/neutral-50
+                  (colors/theme-colors colors/neutral-50 colors/neutral-40))
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/home/chat_list_item/style.cljs:28]: Small refactor, `or` + `when` -> `if`

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs [hunk 3]
```diff
@@ -208,16 +208,40 @@
      {:color color
       :size  :medium}]))
 
+(defn notification
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/home/chat_list_item/view.cljs:211]: This is the main component added:
it handles which badge show. the previous implementation was not taking into account `unviewed-mentions-count` for group chats

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs [hunk 4]
```diff
@@ -208,16 +208,40 @@
...
+    [rn/view {:style style/notification-container}
+     (cond
+       muted
+       [icons/icon :i/muted {:color colors/neutral-40}]
+
+       (and group-chat unread-mentions?)
+       [quo/info-count
+        {:style               {:position :relative :right 0}
+         :customization-color customization-color}
+        unviewed-mentions-count]
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: the component `quo/info-count` is defining its styles using an `:absolute` positioning by default and setting `:right` as `22`, so I'm overwriting them.

It makes hard to correctly fit this component in any UI.

I think we shouldn't define quo library components's main layout as `:absolute`  (i.e., we can use `:absoulte` but just internally in the component).

wdyt guys?

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs [hunk 5]
```diff
@@ -229,15 +253,7 @@
        :full-name display-name
        :color     color
        :muted?    muted}]
-     [rn/view {:style {:margin-left 8}}
+     [rn/view {:style style/chat-data-container}
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/home/chat_list_item/view.cljs:258]: I modified this container to fix the aligment

File: src/quo2/components/notifications/info_count.cljs [hunk 6]
```diff
@@ -3,22 +3,27 @@
...
-             {:style (merge {:width            16
-                             :height           16
-                             :position         :absolute
-                             :right            22
-                             :border-radius    6
-                             :justify-content  :center
-                             :align-items      :center
-                             :background-color (colors/theme-colors colors/primary-50 colors/primary-60)}
-                            (:style props))})
+     [rn/view (merge props {:style (counter-style customization-color style)})
```
Comment (ibrkhalil) [inline src/quo2/components/notifications/info_count.cljs]: I think assoc is a better candidate here, It's only a single key/value pair.

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs [hunk 7]
```diff
@@ -208,16 +208,40 @@
      {:color color
       :size  :medium}]))
 
+(defn notification
+  [{:keys [muted group-chat unviewed-messages-count unviewed-mentions-count]}]
+  (let [customization-color (rf/sub [:profile/customization-color])
+        unread-messages?    (> unviewed-messages-count 0)
+        unread-mentions?    (> unviewed-mentions-count 0)]
```
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: `pos?` can be used here

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 4 above)
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: I see duplocation between this case and the one at line 232, Can we add their checks in an `(or ` function?
Or make the default of the cond?

**Review by ibrkhalil — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 4 above)
Comment (ilmotta) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: It's a reasonable suggestion @ulisesmac. `:position :relative` is the default, we can remove it here.

File: src/quo2/components/notifications/info_count.cljs [hunk 8]
```diff
@@ -3,22 +3,27 @@
...
+
 (defn info-count
   ([amount]
    (info-count {} amount))
-  ([props amount]
+  ([{:keys [customization-color style]
+     :or   {customization-color :blue}
+     :as   props}
+    amount]
    (when (> amount 0)
```
Comment (ilmotta) [inline src/quo2/components/notifications/info_count.cljs]: Suggestion: Use `pos?`

File: src/quo2/components/notifications/info_count.cljs (hunk 1 above)
Comment (ilmotta) [reply src/quo2/components/notifications/info_count.cljs:15]: I was going to suggest passing a `theme` to `custom-color-by-theme`, but then I realized this function is not truly themeable because it uses `(theme/dark?)` inside.

- I just created this issue https://github.com/status-im/status-mobile/issues/16669

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: Oh the problem is the default styles are setting `:position :absolute` inside the component, so I'm overwriting them using this `:position :relative`

File: src/quo2/components/notifications/info_count.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/quo2/components/notifications/info_count.cljs]: Nice suggestion @ibrkhalil 
I was pretty much copying and moving the previous code so I didn't notice. :+1:

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: @ibrkhalil 
I'm not a big fan of using `pos?` for saying a number is greater than zero. I know it means the same but to me, using `pos?` makes me think about the value, and I start thinking what about `neg?` and also `zero?` could this value be negative?.

So, unless we always prefer to avoid `(> number 0)`, I'd prefer to keep it.

wdyt?

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: Oh no, they are not duplicated:

this one is:
```clojure
(and group-chat unread-mentions?)
       [quo/info-count
        {:style               {:position :relative :right 0}
         :customization-color customization-color}
        unviewed-mentions-count]
```

the other one:
```cojure
unread-messages?
       [quo/info-count
        {:style               {:position :relative :right 0}
         :customization-color customization-color}
        unviewed-messages-count]
```

The differences are the conditions: 
- `unread-messages?` vs `unread-mentions?`
-  `unviewed-mentions-count` vs `unviewed-messages-count`

the thing they share is the `info-count` component.

Also, the default case is `nil`, that happens when we have no notifications (so we don't draw a muted icon, a gray dot or a counter).

@ibrkhalil  WDYT?

File: src/quo2/components/notifications/info_count.cljs (hunk 8 above)
Comment (ulisesmac) [reply src/quo2/components/notifications/info_count.cljs]: @ilmotta  As I said to @ibrkhalil.

I prefer to use `pos?` when the value can also be `neg?`, for me, it looks pretty straighforward saying "more than zero?" than "is this positive?", despite they are the same, unless we are always avoiding using `(> n 0)`.

Comment (yqrashawn) [reply src/quo2/components/notifications/info_count.cljs]: The Clojure style guide recommends `pos?` over `> 0`, I think we should always avoid `(> n 0)`

**Review by yqrashawn — APPROVED** [review]
LGTM!

**Review by smohamedjavid — APPROVED** [review]
🚀

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 7 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: Personally, pos? is way more readable to me.

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: Can we extract this into a var?
```clojure
[quo/info-count
 {:style               {:position :relative :right 0}
  :customization-color customization-color}
```

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: Fixed!

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: @ibrkhalil 

I also thought about creating this as a separate component, but I think it's not worth it.

- That `info-count` is overriding its styles, but nothing important, just technical debt.
- If I create a separate component, it will just look as a wrapper, it will not add meaningful view code.
- This will be fixed when https://github.com/status-im/status-mobile/issues/16611 is solved.

So right now, I think is better to keep it as is.

File: src/quo2/components/notifications/info_count.cljs (hunk 8 above)
Comment (ulisesmac) [reply src/quo2/components/notifications/info_count.cljs]: @yqrashawn I didn't notice before, thanks.

I changed them.
@ibrkhalil

**Review by ibrkhalil — APPROVED** [review]
Thank you

**Comment by qoqobolo** [comment]
@ulisesmac and this one also needs to be rebased :)
Thank you!

**Comment by ulisesmac** [comment]
> @ulisesmac and this one also needs to be rebased :) Thank you!

@qoqobolo Done! :)

**Comment by churik** [comment]
@ulisesmac 
### ISSUE 1: can't see the unread indicator on 1-1 chat 

**Steps:**
1) User A: add User B as a contact
2) User A: send a couple of messages to the user B

**Expected result:**
user B: can see the unread indicator

**Actual result:**

https://github.com/status-im/status-mobile/assets/4557972/f48705b2-275d-46b9-a470-a460f1eadbf2

**OS:** IOS, Android
The same is about group chats - no unread indicator on mentions. There is a chance that rebase broke the implementation.


### Question 2: would it be possible in this PR is possible to customize the color of the unread badge on Activity Centre and on the community or should I create a follow-up?

 
IMAGE 2023-07-24 11:35:22

**Comment by ulisesmac** [comment]
Thanks for reviewing @churik 

About issue 1:
Yes, I pushed an error while solving PR's comments, now it's fixed.

about issue 2:
I tried to solve it, but I noticed the components used are different, so it'd need a different solution. Since our PRs only push one commit to `develop`, it'd be better to address the fix in a separate PR (commit).

**Comment by churik** [comment]
@Francesca-G ready for design review, good to do from QA side, thanks!

**Review by Francesca-G — APPROVED** [review]

**Comment by ulisesmac** [comment]
> @Francesca-G ready for design review, good to do from QA side, thanks!

Hey @churik, @Francesca-G has already approved this PR, could you please add the "tested ok" label if this is ready to be merged?

Thanks! :)
