### PR TITLE
Disable translations - only use English for the moment until designs are stable and translations are correct

### LINKED ISSUE #16058: Disable translations - only use English for the moment until designs are stable and translations are correct
Currently a lot of the translations in the application are half way finished or are incorrect. For this reason it is better to just use English translations only for the time being so that translations can be enabled properly later.

** This does not mean developers should skip using translation strings etc ** - these mechanisms are essential to later add translations once they are correctly done and verified.

### PR DESCRIPTION
**Pull request by alwx**
Fixes #16058

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/setup/i18n_resources.cljs [hunk 1]
```diff
@@ -1,9 +1,11 @@
...
   (:require [clojure.string :as string]
-            [utils.i18n :as i18n]
-            [react-native.languages :as react-native-languages]))
+            [utils.i18n :as i18n]))
 
-(def default-device-language (react-native-languages/get-lang-keyword))
+;; FIXME: that should be replaced with `(react-native-languages/get-lang-keyword)`
+;; in order for languages/translations to work
+;; see https://github.com/status-im/status-mobile/issues/16058 for details
+(def default-device-language :en)
```
Comment (J-Son89) [inline src/status_im2/setup/i18n_resources.cljs:8]: 👍

**Review by J-Son89 — APPROVED** [review]
nice 😎

**Comment by pavloburykh** [comment]
@alwx thanx! Ready to be merged.
