### PR TITLE
fix: audio recording bugs while scroll in chat

### LINKED ISSUE #15889: [Android] "Failed to send a message {:code-32000}" error occurs when attempting to send audio as result all next sent audios are empty
### Steps to reproduce:
1. Send multiple long text messages to enable scrolling in the chat.
2. Begin recording audio by holding down the 'record' button.
3. Scroll within the chat while the audio is being recorded.
4. Release the 'record' button to stop recording.
5. Send the recorded audio by tapping the  'record' button.

### Actual result:
- The audio recording remains on hold after step 4
- The error message "Failed to send a message {:code-32000}" is displayed after step 5
- Subsequent audio messages sent are empty. (can't be played)

https://github.com/status-im/status-mobile/assets/52490791/c418485c-ebbc-44db-8638-23e7ec07205a

### Expected result:
- The recorded audio should be successfully sent without any error messages
- The audio should be shown as ready to be sent in the composer as soon as 'record' button is released
image

- Subsequent audio messages should contain the appropriate audio content.

### Additional info:
The error is not shown for some devices.  As a result, subsequent audio messages will be still sent as empty after steps of this issue
 
### Device:
- Huawei p20 light

### logs:
[Status.log](https://github.com/status-im/status-mobile/files/11464254/Status.log)
https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0

### Env:
- Nightly [12 May 2023]

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #15889 

### Summary

There are some issues when holding touch to record audio and scrolling at the same time with another finger, but there's no sense on allowing the user that behaviour, so limited scrolling capability of the chat while the user is recording an audio unless recording is locked.

#### Platforms

- Android
- iOS

### Steps to test

1. Send multiple long text messages to enable scrolling in the chat.
2. Begin recording audio by holding down the 'record' button.
3. Check user can't scroll the chat while recording
4. Release the 'record' button to stop recording.
5. Send the recorded audio by tapping the  'record' button.
6. Check audio sends correctly

status: ready

### CODE REVIEW

File: src/status_im/chat/models/input.cljs [hunk 1]
```diff
@@ -66,6 +66,11 @@
   (let [current-chat-id (or chat-id (:current-chat-id db))]
     {:db (assoc-in db [:chat/inputs current-chat-id :audio] audio)}))
 
+(rf/defn set-recording
+  {:events [:chat.ui/set-recording?]}
```
Comment (vkjr) [inline src/status_im/chat/models/input.cljs]: I'd suggest naming the event `:chat.ui/set-recording`, without the question mark, or `:chat.ui/set-recording-flag`.
For me the question mark in the name of a setter is a bit disorienting since I read it with a questioning intonation)

**Review by vkjr — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]
Hey @briansztamfater 

**Non-blocking comment:**

From an end-users perception, disabling scrolling may give the wrong impression that scrolling is stuck.

The user (who doesn't have time to send a text message/reply) may respond to a chat message(s) by recording and sending a voice message. Scrolling through messages while recording gives a sense of which messages, or things to mention in the voice message, as the user won't be prepared on what to record before hitting the record button. Scrolling through chat when recording behaviour is existing in apps like WhatsApp and Telegram.

We can investigate later why the audio recorder is affected by the scrolling.

**Comment by briansztamfater** [comment]
> Hey @briansztamfater
> 
> **Non-blocking comment:**
> 
> From an end-users perception, disabling scrolling may give the wrong impression that scrolling is stuck.
> 
> The user (who doesn't have time to send a text message/reply) may respond to a chat message(s) by recording and sending a voice message. Scrolling through messages while recording gives a sense of which messages, or things to mention in the voice message, as the user won't be prepared on what to record before hitting the record button. Scrolling through chat when recording behaviour is existing in apps like WhatsApp and Telegram.
> 
> We can investigate later why the audio recorder is affected by the scrolling.

In my experience, WhatsApp disables scrolling unless audio recording is locked. I replicated the same behavior, so user still can lock the audio recording so he/she can release the record button and continue scrolling while recording. But of course we can revisit this later if this temporarily fixes the issues, just thought of a quick fix for this release :).

File: src/status_im/chat/models/input.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/chat/models/input.cljs]: Thanks for the suggestion, done

**Comment by smohamedjavid** [comment]
> In my experience, WhatsApp disables scrolling unless audio recording is locked. I replicated the same behavior, so user still can lock the audio recording so he/she can release the record button and continue scrolling while recording. But of course we can revisit this later if this temporarily fixes the issues, just thought of a quick fix for this release :).

I was actually referring to the lock behaviour of the recorder. Sorry, I didn't make it clear. I'm glad you added that behaviour. 

Duly appreciated! @briansztamfater! 😃 

<hr/>

@briansztamfater - The commits are unsigned, you might need to amend your signature.

**Comment by VolodLytvynenko** [comment]
hi @briansztamfater thank you for fixes. No issues from my side. Ready to be merged
