### PR TITLE
[#22567] fix: sign transactions from partially operable account

### LINKED ISSUE #22567: Unable to sign transactions from derived accounts restored from Waku
# Bug Report

### Preconditions:
The user has a backed-up derived account (from the default keypair) and expects this account to be restored along with the default account during the recovery process (Recovery phrase for user by request). 

### Reproduction

1. Log in using the recovery phrase.
2. Enable Password authentication on the onboarding screen.
3. After restore, the following accounts should be displayed:
-  Account 1 (default keypair)
-  Account 2 (derived account from the default keypair)
4. Initiate a Send/Swap/Bridge transaction from Account 2.
5. Sign the transaction.

#### Expected behavior
The transaction is successfully signed, processed, and recorded on the blockchain. The account balances are updated accordingly.

#### Actual behavior
An unknown error occurs (no error message displayed) when trying to signed the **Send/Swap/Bridge** transaction. The transaction does not go through.

https://github.com/user-attachments/assets/e3f9f95f-d555-4981-8610-b8c757252601

### Additional Information

- The issue occurs only when the account is restored with two accounts on the default keypair and pasword authentication is enabled during onboarding.
- If a transaction is initiated from Account 1 or an imported account under the same conditions, it is processed successfully without any errors.

- Status version: nightly 
- Operating System: Android, iOS

Logs:

https://drive.google.com/file/d/1e1vqagxHUS0LZZwsaCWOHzq2FDDxevjp/view?usp=sharing

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #22567

## Summary

There is an issue with make partially operable account fully operable. and it throws error when user try to sign a transaction. 

### Areas that may be impacted

- Swap/Bridge/Send for restored account.

## Steps to test

1. Log in using the recovery phrase.
2. Enable Password authentication on the onboarding screen.
3. After restore, the following accounts should be displayed:
-  Account 1 (default keypair)
-  Account 2 (derived account from the default keypair)
4. Initiate a Send/Swap/Bridge transaction from Account 2.
5. Sign the transaction.

## Result 

https://github.com/user-attachments/assets/04d19299-befb-41cf-a8ca-b7a5d04dd750

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Comment by shivekkhurana** [comment]
cc: @Horupa-Olena

File: src/status_im/contexts/wallet/data_store.cljs [hunk 1]
```diff
@@ -117,9 +117,11 @@
 
 (defn partially-operable-accounts?
   [accounts]
-  (->> accounts
-       (some #(= :partially (:operable %)))
-       boolean))
+  (boolean
+   (some (fn [[_ account]]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/data_store.cljs]: nit: Could de-structure the `operable` key here as we have only one usage in the whole function.

**Review by smohamedjavid — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your fix! All work fine, so **PR can be merged.**

The Send/Swap/Bridge flow was tested on the following account types:

- Derived after restore
- Derived and added manually
- Default account (regression)
- Imported account
