### PR TITLE
fix #13642: Cannot sign in on claim.lens.xyz

### LINKED ISSUE #13642: Cannot sign in on claim.lens.xyz
# Bug Report

## Problem

Sign in process doesn't work with dapp browser.
Note I switched to Polygon PoS mainnet for this dapp.

#### Expected behavior

Signing in is possible. 

Note it works with Trust wallet:

#### Actual behavior

Once the wallet is connected, taping "browser" should open the signature pop up (see above) but nothing happens.

### Reproduction

Go to https://claim.lens.xyz/

Tap "Connect Wallet"

Tap "Browser"

Allow connection

Tap "Browser": nothing happens

### Additional Information

- Status version: 1.19.0
- Operating System: Android

I use a keycard.

Network parameters:

### PR DESCRIPTION
**Pull request by qfrank**
fixes #13642

### CODE REVIEW

**Review by Parveshdhull — COMMENTED** [review]
Hi @qfrank , Thank you very much for the PR.

File: resources/js/provider.js [hunk 1]
```diff
@@ -188,7 +188,12 @@
         if (!this._events[name]) {
           return
         }
-        this._events[name].forEach(cb => cb(data));
+        this._events[name].forEach(cb => {
+            try{
+                cb(data)
+            } catch(e){
+                setTimeout((()=>{throw e}))
+            }});
```
Comment (Parveshdhull) [inline resources/js/provider.js:196]: Hi frank, Thank you very much for the PR.

I guess you are using `setTimeout` to throw the error just that it shouldn't stop the current js thread? Please can you explain, what is the benefit of doing that, can we just use an empty block here?

Comment (Parveshdhull) [inline resources/js/provider.js:198]: I guess you are using `setTimeout` to throw the error, so that it shouldn't stop the current js thread. Please can you explain, what is the benefit of doing that, can we just use an empty block here?

**Review by Parveshdhull — APPROVED** [review]
Hi Thanks for adding comment. PR looks good to me. Thank you

**Comment by qoqobolo** [comment]
@qfrank thank you for the fix!
Tested on Android and iOS, with regular and Keycard accounts. E2e test failures are not PR-related.
It can be merged.

**Review by cammellos — APPROVED** [review]
