### PR TITLE
Dynamically calculate composer height to adjust the spacing on the bottom of the list

### LINKED ISSUE #16153: [Android] Auto-scrolling to the bottom after tapping the composer
introduced by https://github.com/status-im/status-mobile/pull/15204
cc: @alwx

### Steps to reproduce:
1. Open a chat with a significant number of messages.
2. Scroll to any position within the chat view.
3. Tap on the composer to begin typing a message.

### Actual result:
After tapping on the composer, the chat view automatically scrolls to the bottom, bringing the latest messages into view

https://github.com/status-im/status-mobile/assets/52490791/3ec48d1f-c3a2-499c-ba62-6b089890cb8f

### Expected result:
Tapping on the composer should not trigger an automatic scroll to the bottom of the chat view.

### Device: 
- Real device: Pixel 7a, Android 13
- Android Emulator: Pixel XL API 29

### PR DESCRIPTION
**Pull request by alwx**
Currently the spacing on the bottom is fixed (it uses `composer.constants/composer-default-height`) which is a problem because composer doesn't actually have a fixed height.

This PR makes it use the dynamucally calculated height in order to make sure composer never overlaps the content and always leaves the right amount of space.

Tagging @OmarBasem here to double check if the calculation is done right.

Also fixes https://github.com/status-im/status-mobile/issues/16153

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: wip

### CODE REVIEW

File: src/status_im2/subs/chat/chats.cljs [hunk 1]
```diff
@@ -140,6 +141,24 @@
...
+          composer.constants/reply-container-height)
+        (when editing-message
+          composer.constants/edit-container-height)
+        (when (seq sending-image)
+          composer.constants/images-container-height)
+        (when (seq link-previews)
+          composer.constants/links-container-height)
+        composer.constants/bar-container-height
+        composer.constants/actions-container-height))))
+
```
Comment (OmarBasem) [inline src/status_im2/subs/chat/chats.cljs:161]: Did you include the text height inside the composer somewhere?

Comment (alwx) [reply src/status_im2/subs/chat/chats.cljs:161]: isn't it `input-content-height`? (line 150)

**Review by OmarBasem — APPROVED** [review]
LGTM!

**Comment by pavloburykh** [comment]
@alwx thanx for the PR. Please take a look at the issues:

### ISSUE 1 Chat history overlapped by expanding composer results in empty area on collapsing the composer

**Steps:** 

1. Open composer
2. Start entering multiline message to expand the composer
3. Collapse composer
4. Observe how the area which was behind the composer looks like

**Actual result:** empty area after closing expanded composer


https://github.com/status-im/status-mobile/assets/97245802/14e195b4-be86-4354-ad1c-1f05798f7033

Platforms: IOS/Android

**Comment by pavloburykh** [comment]
### ISSUE 2 Content above composer is being pushed with twitching while composer is expanding

@alwx this PR introduces new feature: content remains above the composer while it is expanding. 

When composer is pushing content twitching is kinda visible which causes poor UX. Is it possible to make animation more smooth?  

**Actual result:** 

https://github.com/status-im/status-mobile/assets/97245802/1f8893ee-e097-4da6-9655-a99384ed6d01

**Expected result** this is an example of animation from Discord mobile app

 
https://github.com/status-im/status-mobile/assets/97245802/642a4bb1-1330-42a3-8aa8-c286a3e744c3

**Comment by OmarBasem** [comment]
> @alwx thanx for the PR. Please take a look at the issues:
> 
> ### ISSUE 1 Chat history overlapped by expanding composer results in empty area on collapsing the composer
> **Steps:**


@alwx chat content shouldn't move up like that when the composer is expanding. That's a bottom sheet composer. It should expand over the content not under it.

https://vimeo.com/727812151

**Comment by pavloburykh** [comment]
### ISSUE 3 User is scrolled to the bottom of the chat after sending edited message

**Steps:** 

1. Scroll up to some of your previous messages in chat history
2. Edit and send updated message
3. See if user has been auto-scrolled to the bottom of the chat

**Actual result:** user is scrolled to the bottom of the chat

https://github.com/status-im/status-mobile/assets/97245802/1240a2e1-71ea-48a8-aec8-71a4d901ab54

**Expected result:** scroll should be remained at the edited message

**Comment by pavloburykh** [comment]
> > @alwx thanx for the PR. Please take a look at the issues:
> > ### ISSUE 1 Chat history overlapped by expanding composer results in empty area on collapsing the composer
> > **Steps:**
> 
> @alwx chat content shouldn't move up like that when the composer is expanding. That's a bottom sheet composer. It should expand over the content not under it.
> 
> https://vimeo.com/727812151

@OmarBasem @alwx please before making any changes on this see chat history with design team starting from this message https://discord.com/channels/624634427930312714/928625369542713396/1122880564127617114

**Comment by pavloburykh** [comment]
@alwx just in case you missed, I will leave here the quotes from conversation between @OmarBasem and @John-44 with @pedro-et :

Omar:

> @Pedro previously the behavior we had in app was to push content up, then we changed it to that the composer grows over content to match the designs and this video https://vimeo.com/727812151 .  Most messengers do push the content up, but I think we should also take into consideration that we can have a full screen composer. I think from the designs the intended behavior seemed to have a "drawer composer" that grows over content, and which can be dragged from a handle (similar to options menu drawers)

> Maybe we can have a mix of both. Push content up till a certain threshold (half the screen maybe), then the composer can continue growing over the content

Pedro: 

> thats what i was suggesting

John:

> @Omar Basem what you are suggesting sounds like a good idea to me

@alwx If you will have any additional questions regarding this, please contact the design team for details.

**Comment by pavloburykh** [comment]
@alwx hi! Please, ping me up when PR will be ready for re-test.

**Comment by OmarBasem** [comment]
Hi @pavloburykh,

As requested by Andrea, I will be taking over this PR as we will be cutting off the release branch by the end of the week and Alex is currently off.

The design team still did not confirm the chat-list/composer behavior when the composer is expanding, and we need to see some designs/videos for that. So for now, I have reverted it to what it was before (composer grows over content).

This PR has an important fix for Android https://github.com/status-im/status-mobile/issues/16153 so let's get it merged

**Comment by churik** [comment]
cc @Francesca-G

**Comment by Francesca-G** [comment]
> cc @Francesca-G

as confirmed by Pedro and John on discord and [here](https://github.com/status-im/status-mobile/pull/16235#issuecomment-1612919707) we have 3 possible behaviors:

- if at the bottom: the composer pushes content up.
- if on scroll: the composer still pushes content up until a certain threshold (half the screen maybe, as suggested by Omar) to allow users to reply to a message and still see the message they're replying to, as much as possible. This will eventually be impossible if the message we're typing becomes too long, in that case (after the threshold) the composer will cover the whole screen. 
- If the user manually stretches by dragging the handle it shouldn't push content up.

Hope this helps :)

**Comment by OmarBasem** [comment]
Thank you @Francesca-G !

**Comment by OmarBasem** [comment]
@pavloburykh I have opened a separate issue https://github.com/status-im/status-mobile/issues/16484 for the mentioned description above by Francesca. I think it would be better to work on that separately as it is a new feature rather than a bug. There are other bugs with the TopBar which may be better to prioritize for now.

**Comment by pavloburykh** [comment]
> a separate issue #16484 for the mentioned description above by Francesca. I think it would be better to work on that separately as it is

Thank you @OmarBasem ! I am off till Tuesday, so @churik will kindly take a look at current PR and approve it if the above [ISSUE 1](https://github.com/status-im/status-mobile/pull/16235#issuecomment-1607568691) is not reproducible after reverting. Thank you @OmarBasem and @churik !

**Comment by OmarBasem** [comment]
Hi @churik, could you please check if PR is ready for merge?

**Comment by alwx** [comment]
@pavloburykh @OmarBasem sorry for missing all the fun — I'm currently on vacation (today is the last day), that's why I was not paying much attention to what's happening here. You can either proceed with this PR today or wait for me until tomorrow — any option is fine for me.

**Comment by churik** [comment]
https://github.com/status-im/status-mobile/issues/16153 and https://github.com/status-im/status-mobile/pull/16235#issuecomment-1607568691 are not reproducible anymore, thank you
