### PR TITLE
fix no request for permission for push notifications when you enable them in app settings

### LINKED ISSUE #19833: [Android] No request for permission for push notifications when you enable them in app settings
Looks like the issue is device-specific. Can reproduce it only for Pixel 7a, Android 13

If you skip enabling push notifications on onboarding and then enable them in the app settings, they will appear enabled, but in fact they are not.
In this case, permission is not requested, which means notifications are not enabled in the device's settings > they won't work.

### Steps:
1. Onboard tapping 'maybe latter' button on the allow notification screen
2. Go to profile
3. Open notification
4. Enable 'Local notification' toggle

### Actual result:
The notification permissions are not enabled

https://github.com/status-im/status-mobile/assets/52490791/b957a8e3-50ff-4d25-bd02-0a9eb856fc38

### Expected result:
The notification permissions are enabled

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/15160393/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/19833

status: ready

### CODE REVIEW

File: src/status_im/contexts/onboarding/enable_notifications/view.cljs [hunk 1]
```diff
@@ -36,7 +35,7 @@
                                 {:permissions [:post-notifications]
                                  :on-allowed  #(log/info "push notification permissions were allowed")
                                  :on-denied   #(log/error "user denied push notification permissions")}])
-                              (rf/dispatch [:push-notifications/switch true platform/ios?])
+                              (rf/dispatch [:push-notifications/switch true])
```
Comment (Parveshdhull) [inline src/status_im/contexts/onboarding/enable_notifications/view.cljs:38]: https://github.com/status-im/status-mobile/blob/5ee5d705675f5f0378124311cc69fd1501612b8e/src/legacy/status_im/ui/screens/notifications_settings/events.cljs#L50-L51

`platform/ios?` is redundant

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fix @Parveshdhull, PR can be merged.
