### PR TITLE
Wallet - Add token filter and prices fallback for fiat amount calculation

### LINKED ISSUE #18355: Wallet - App crashes on token calculation
# Bug Report

The app crashes on the wallet tab with the error:

>  BigNumber Error: times() not a number: null

### Reproduction

1. Open the Status app
2. Add a watch-only account `0xcf2272205cc0cf96cfbb9dd740bd681d1e86901e`
3. Navigate to the wallet tab

### Expected behaviour

The app should not crash

### Additional Information

- Status Version: nightly [2023/12/30] 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18355

### Summary

This PR:
- Adds a filter to remove tokens with no name or symbol to prevent displaying tokens with no data
- Adds a fallback value (zero) for token fiat value calculation and to prevent crash on token price calculation

### Review notes

Regarding fallback value, we can improve the UI/UX by showing a warning icon next to the token name that the prices are unavailable. That's something that requires design development, probably for later.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to the Wallet tab
- Verify the token and token prices are displayed without any crash

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/events.cljs [hunk 1]
```diff
@@ -121,13 +121,20 @@
       (update :balances-per-chain update-vals #(update % :raw-balance money/bignumber))
       (update :balances-per-chain update-keys (comp utils.number/parse-int name))))
 
+(defn- remove-tokens-with-empty-values
+  [tokens]
+  (remove
+   #(or (string/blank? (:symbol %)) (string/blank? (:name %)))
+   tokens))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events.cljs]: What is the reason for status-go to return these tokens without names or symbols?

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/events.cljs]: It could be due to the market provider being down or it can be a custom token in the address which `status-go` is unable to fetch the data at that moment.

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 2]
```diff
@@ -90,10 +90,13 @@
...
-                                          [currency :price]
-                                          (get-in market-values-per-currency
-                                                  [constants/profile-default-currency :price]))
+  (let [price                     (or (get-in market-values-per-currency
+                                              [currency :price])
+                                      (get-in market-values-per-currency
+                                              [constants/profile-default-currency :price])
+                                      ;; NOTE: adding fallback value (zero) in case prices are
+                                      ;; unavailable and to prevent crash on calculating fiat value
+                                      0)
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/common/utils.cljs:99]: If prices are unanavailable then maybe we can filter them out (like below) ? Just displaying zero would be an incorrect price I think

File: src/status_im/contexts/wallet/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/events.cljs]: But we get a balance, isn't it weird that just the name or symbols are missing?

the total balance calculation then won't be correct :thinking: is it expected  in this case? WDYT about adding a warning or something to it?

File: src/status_im/contexts/wallet/common/utils.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/common/utils.cljs:99]: I don't think we should filter them as they may be custom tokens that have not market value yet. But I agree we should not show 0 as price, maybe add `nil` value and do not show any price in the UI would be a better choice IMO.

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/common/utils.cljs:99]: Yes, we shouldn't be filtering out because the market value is unavailable. To create a good UX, we can discuss with the Design team displaying a warning icon next to the token name to indicate that the token price is unavailable or similar.

File: src/status_im/contexts/wallet/events.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/events.cljs]: Yes, It's weird that the balances are returned but not the name or symbol. The issue is that we deal with uncertain tokens. I added this token filter as the desktop app has a similar one to remove the tokens with no name or symbol.

IMO, the total balance calculation would be correct (atleast) for the tokens displayed (with all required values such as name, symbol,...etc).

> WDYT about adding a warning or something to it?

Yes, Ulises. That's my next step. Displaying a warning/error icon would improve the UX. This is worth discussing with the design team.

**Review by ulisesmac — APPROVED** [review]
Looks good.

@smohamedjavid

**Review by OmarBasem — APPROVED** [review]

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the PR. I have not faced any crashes in this PR. Though I have not been able to reproduce it in develop as well. Ready for merge.

**Comment by smohamedjavid** [comment]
> @smohamedjavid thanx for the PR. I have not faced any crashes in this PR. Though I have not been able to reproduce it in develop as well. Ready for merge.

Thank you for testing the PR @pavloburykh!
The crash hardly ever happened. This fix will help us prevent it.
