### PR TITLE
bug #4123 - fixes incorrect number of decimals for tokens, fixes inco…

### LINKED ISSUE #4123: Insufficient funds error shown when sending ATT tokens with positive balance
### Description

*Type*: Bug

*Summary*: Can't send `ATT` tokens from wallet to recent recipient having 100 tokens on my balance

#### Expected behavior
I can send `ATT` tokens from wallet when my token balance is greater than zero and i have enough ETH to pay the gas

#### Actual behavior
`Insufficient funds` error shown when sending ATT tokens from the wallet

image

image

### Reproduction

- Open Status
- Faucet some funds
- Request some ATT tokens
- Go to wallet - Send transaction
- Specify recipient 
- Select ATT from Asset list
- Specify amount

### Additional Information
* Status version: nightly 367
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by goranjovic**
partially addresses #4123

### Summary:

This PR fixes a number of bugs with sending tokens:

- incorrect network id lookup that prevents user from sending tokens
- incorrect handling of  number of decimals depending on token info (previously assumed 18 for all tokens like ether-wei)
- fixes amount formatting due to decimals where needed
- removes ATT since its transfer method works in a confusing way for testing (transfer adds funds to recipient, but doesn't remove the same funds for sender)
- changes other test tokens to include multiple decimal counts to make testing of this or any other related bugs easier

### Testing notes (optional):

I'm also submitting a PR for Simple Dapp with updated token addresses. Until it is deployed you'll have to use the old way to get tokens - send 0 eth to the following addresses:

```
HND - 0xdee43a267e8726efd60c2e7d5b81552dcd4fa35c
LXS - 0x703d7dc0bc8e314d65436adf985dda51e09ad43b
ADI - 0xe639e24346d646e927f323558e6e0031bfc93581
WGN - 0x2e7cd05f437eb256f363417fd8f920e2efa77540
MDS - 0x57cc9b83730e6d22b224e9dc3e370967b44a2de0
```

Don't forget to increase gas! (Sorry)

### Steps to test:
- Request assets
- Send assets to other participants
- Check tx history
- Check etherscan

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/subs.cljs [hunk 1]
```diff
@@ -86,3 +86,9 @@
          (fn [db [_ item-id]]
            (let [item-animation (get-in db [:chat-animations item-id])]
              (if (some? item-animation) (:delete-swiped item-animation) nil))))
+
+(reg-sub :get-current-account-network
+         (fn [{:keys [network] :as db} [_]]
+           (let [a (get-in db [:account/account :networks network])]
+             #_(js/alert a)
```
Comment (jeluard) [inline src/status_im/ui/screens/subs.cljs]: We can probably simplify this block?

Comment (yenda) [inline src/status_im/ui/screens/subs.cljs]: I suppose it was for debug purposes can you clean up ?

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 2]
```diff
@@ -29,7 +29,7 @@
                     #()))
 
 (defn- send-tokens [{:keys [web3 from to value gas gas-price symbol network]}]
-  (let [contract (:address (tokens/symbol->token (ethereum/network->chain-keyword network) symbol))]
+  (let [contract (:address (tokens/symbol->token (keyword (ethereum/network-names network)) symbol))]
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/events.cljs:32]: This was a regression from another PR? `network-names` sounds weird if it returns a single name?

File: src/status_im/ui/screens/wallet/components/views.cljs [hunk 3]
```diff
@@ -195,15 +196,15 @@
      ;; Otherwise, user might want to fix his input and autocorrection will give more harm than good.
      ;; Positive check is because we don't want to replace unfinished 0.000 with just plain 0, that is annoying and
      ;; potentially dangerous on this screen (e.g. sending 7 ETH instead of 0.0007)
-     {:default-value  (if (empty? amount-text) (str (money/to-fixed (money/wei->ether amount))) amount-text)}
+     {:default-value  (if (empty? amount-text) (str (money/to-fixed (money/internal->formatted amount symbol decimals))) amount-text)}
```
Comment (yenda) [inline src/status_im/ui/screens/wallet/components/views.cljs]: line is too long

File: src/status_im/utils/money.cljs [hunk 4]
```diff
@@ -90,6 +90,20 @@
   (when-let [bn (bignumber n)]
     (.dividedBy bn (bignumber (from-decimal decimals)))))
 
+(defn unit->token [n decimals]
+  (when-let [bn (bignumber n)]
+    (.times bn (bignumber (from-decimal decimals)))))
+
+(defn formatted->internal [n symbol decimals]
```
Comment (jeluard) [inline src/status_im/utils/money.cljs]: Can you add some doc? Also why does `internal` refers to?

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 5]
```diff
@@ -192,8 +194,15 @@
    (when advanced?
      [advanced-cartouche transaction modal?])])
 
-(defn- send-transaction-panel [{:keys [modal? transaction scroll advanced? symbol]}]
-  (let [{:keys [amount amount-text amount-error signing? to to-name sufficient-funds? in-progress? from-chat?]} transaction
+(defn update-amount-fn [timeout symbol decimals token]
+  (fn [amount]
+    (when @timeout
+      (utils/clear-timeout @timeout))
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/views.cljs]: Can you detail this part?

**Review by jeluard — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/wallet/send/events.cljs (hunk 2 above)
Comment (goranjovic) [reply src/status_im/ui/screens/wallet/send/events.cljs:32]: Yes, but I couldn't fix one without the other because intermediate solution would be so broken it's dangerous.

File: src/status_im/ui/screens/subs.cljs (hunk 1 above)
Comment (goranjovic) [reply src/status_im/ui/screens/subs.cljs]: Good catch

File: src/status_im/utils/money.cljs (hunk 4 above)
Comment (goranjovic) [reply src/status_im/utils/money.cljs]: Yes, indeed. This whole ns needs a refactor. Too many opportunities to get confused.

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 5 above)
Comment (goranjovic) [reply src/status_im/ui/screens/wallet/send/views.cljs]: Which one, timeout? Sure I can, though it wasn't introduced in this PR

File: src/status_im/ui/screens/subs.cljs (hunk 1 above)
Comment (goranjovic) [reply src/status_im/ui/screens/subs.cljs]: Yeah, it's just some leftover debugging crap. I'll remove it

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/sN6FU4 for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/sN6FU4">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 5 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs]: Oh OK didn't see it in GH diff view. If you can add a quick comment on the top of your head would be nice?

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/7N1j7v for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/7N1j7v">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 5 above)
Comment (goranjovic) [reply src/status_im/ui/screens/wallet/send/views.cljs]: yep

Comment (goranjovic) [reply src/status_im/ui/screens/wallet/send/views.cljs]: Even better, I can remove the whole function. It's unused after the rebase

**Comment by goranjovic** [comment]
@yenda @jeluard updated

**Review by mandrigin — APPROVED** [review]
LGTM

File: src/status_im/ui/screens/wallet/send/events.cljs (hunk 2 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/events.cljs:32]: Sounds good! Name is weird but we can address that later.

File: src/status_im/utils/money.cljs [hunk 6]
```diff
@@ -90,6 +90,32 @@
...
+  (when-let [bn (bignumber n)]
+    (.times bn (bignumber (from-decimal decimals)))))
+
+;;NOTE(goranjovic) - We have two basic representations of values that refer to cryptocurrency amounts: formatted and
+;; internal. Formatted representation is the one we show on screens and include in reports, whereas internal
+;; representation is the one that we pass on to ethereum network for execution, transfer, etc.
+;; The difference between the two depends on the number of decimals, i.e. internal representation is expressed in terms
+;; of a whole number of smallest divisible parts of the formatted value.
+;;
+;; E.g. for Ether, it's smallest part is wei or 10^(-18) of 1 ether
```
Comment (jeluard) [inline src/status_im/utils/money.cljs:103]: Got it. So it's wei except wei don't exist for tokens :)

**Review by jeluard — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/nEzrM7 for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/nEzrM7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/utils/money.cljs (hunk 6 above)
Comment (goranjovic) [reply src/status_im/utils/money.cljs:103]: It's wei if token has 18 decimals. It's cents if it has two decimals, etc...

Comment (mandrigin) [reply src/status_im/utils/money.cljs:103]: ❤️ how this note explains the code below!

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/sXBD9N for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/sXBD9N">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/V8t9a3 for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/V8t9a3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by mandrigin — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/w6T7Zz for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/w6T7Zz">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/YAZRGu for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/YAZRGu">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
This works fine

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/HhjKsK for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/HhjKsK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/vX4YUK for branch PR-4428

<blockquote><div><strong><a href="https://i.diawi.com/vX4YUK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
