### PR TITLE
Don't parse unused identicon in android pn

### LINKED ISSUE #17160: PNs delivery sometimes takes > 60 sec
# Bug Report

## Problem 
e2e blocker - it fails a lot of cases from time to time, I do not think it makes sense to wait for PN > 60 sec.

Possible solutions:
- extend the wait time for PNs (worst way, will 
- check for message status (should be Delivered as far as I know) from sender and only after that start checking PNs

or to look at message reliability :)

#### Expected behavior
Can get PN

#### Actual behavior
I can see that the message was delivered at [14:35](https://app.eu-central-1.saucelabs.com/tests/0df04e279e954b47bebe8557f6b99160?auth=8edfc18798123b56cb6d764e5ce4a722#320) (it might be earlier, no option to check now), so it took > 90 sec for message to be delivered

### Reproduction

1. Device2: 12:45 > message is sent [step](https://app.eu-central-1.saucelabs.com/tests/1a7ca875d68c4598b96720807ab54d9c?auth=37ab191f1ae8ab05f069372f3fb8f7eb#224)
2. Device1: 12:51 > start to wait for PNs [step](https://app.eu-central-1.saucelabs.com/tests/0df04e279e954b47bebe8557f6b99160?auth=8edfc18798123b56cb6d764e5ce4a722#299)
3. Device1: 13:48 > No PN > device considers test as failed.

Device1 log (receiver): [logcat (23).log](https://github.com/status-im/status-mobile/files/12487073/logcat.23.log)
Device1 geth.log: [test_1_1_chat_push_emoji_geth1.log](https://github.com/status-im/status-mobile/files/12487079/test_1_1_chat_push_emoji_geth1.log)

Device2 log (sender): [logcat (22).log](https://github.com/status-im/status-mobile/files/12487055/logcat.22.log)
Device2 geth.log: [test_1_1_chat_push_emoji_geth2.log](https://github.com/status-im/status-mobile/files/12487076/test_1_1_chat_push_emoji_geth2.log)

### Additional Information

- Status version: nightly 31/08/23
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by cammellos**
Removes parsing of identicon from notification, which won't be showing it anymore (it's a bit more complicated to add the actual image, so removing for now).

I am trying to set up unit tests for this part, but getting into some issues, as this is a blocker, I will send the PR for review now

Fixes: #17160

### CODE REVIEW

File: modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java [hunk 1]
```diff
@@ -684,13 +684,9 @@ private Bitmap getCircleBitmap(Bitmap bitmap) {
     }
     
     private Person getPerson(Bundle bundle) {
-      String base64Image = bundle.getString("icon").split(",")[1];
-      byte[] decodedString = Base64.decode(base64Image, Base64.DEFAULT);
-      Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);
+     String name = bundle.getString("name");
 
-      String name = bundle.getString("name");
```
Comment (siddarthkay) [inline modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java:691]: looks good! tiny nitpick on placing a TODO comment or link to issue here :)

**Review by siddarthkay — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]
LGTM

> I am trying to set up unit tests for this part, but getting into some issues

Just out of curiosity, which problems @cammellos? Or better yet, what were you trying to test?

**Comment by cammellos** [comment]
> LGTM
> 
> > I am trying to set up unit tests for this part, but getting into some issues
> 
> Just out of curiosity, which problems @cammellos? Or better yet, what were you trying to test?


I am trying to test the native java code we use for push notifications, ie this file:
```
modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
```

This is mocked in our unit tests, and only tested through e2e tests.
I would like to add some unit tests so that at least we can verify the behavior (it would not most likely have caught this, since this was a breaking change in status-go, but at least there's a way to test this as there's already a fair amount of logic)

Problems have mostly to do with dependencies etc, but I have solved them now, though I am still working through mocking/etc in the actual test

**Comment by ilmotta** [comment]
> > LGTM
> > > I am trying to set up unit tests for this part, but getting into some issues
> > 
> > 
> > Just out of curiosity, which problems @cammellos? Or better yet, what were you trying to test?
> 
> I am trying to test the native java code we use for push notifications, ie this file:
> 
> ```
> modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java
> ```
> 
> This is mocked in our unit tests, and only tested through e2e tests. I would like to add some unit tests so that at least we can verify the behavior (it would not most likely have caught this, since this was a breaking change in status-go, but at least there's a way to test this as there's already a fair amount of logic)
> 
> Problems have mostly to do with dependencies etc, but I have solved them now, though I am still working through mocking/etc in the actual test

👍🏼 Cool, definitely valuable to have unit test coverage there.

File: modules/react-native-status/android/src/test/java/im/status/ethereum/pushnotifications/PushNotificationHelperTest.java
Comment (briansztamfater) [inline modules/react-native-status/android/src/test/java/im/status/ethereum/pushnotifications/PushNotificationHelperTest.java:1]: 🚀

**Review by briansztamfater — APPROVED** [review]
It's excellent to see the implementation of unit tests for relevant Android native code. This is a great initiative, and I'm looking forward to delving deeper into this aspect.

I didn't find any major issues with the code. LGTM 👍

**Comment by siddarthkay** [comment]
Hi @cammellos : I really like this attempt of adding tests to native android code!
 
I see you've added some `gradle` dependencies and for `nix` to be happy you will have to run `make nix-update-gradle` and push those deps.

This PR will  require those 3 files will that get auto generated : 
- `deps.list`
- `deps.urls`
- `deps.json`

**Comment by siddarthkay** [comment]
~~I tried to run tests locally and I saw a `jsc-android` error so you may have to add that as a dependency : 
(It was my local environment)~~

Tests ran successfully on my machine `make android-test` took ~ 35 mins the 1st time

Screenshot 2023-09-05 at 1 52 05 PM

Second time they took ~ 11 mins

Screenshot 2023-09-05 at 2 22 35 PM

File: Makefile [hunk 2]
```diff
@@ -349,6 +349,14 @@ test: ##@test Run tests once in NodeJS
 	yarn shadow-cljs compile test && \
 	node --require ./test-resources/override.js target/test/test.js
 
+android-test: jsbundle
+android-test: export TARGET := android
+android-test:
+	yarn install
+	yarn shadow-cljs compile mocks && \
```
Comment (siddarthkay) [inline Makefile]: Although I'm not 100% sure if this is needed

Comment (siddarthkay) [reply Makefile]: I mean compiling mocks and a target of jsbundle

Comment (cammellos) [reply Makefile]: not needed, I meant to remove it, jsbundle is needed (or rather, it doesn't work otherwise, but it might be possible not to run it, not sure)

Comment (siddarthkay) [reply Makefile]: > it might be possible not to run it

interesting! worth exploring. Thanks for the explanation.

**Review by jakubgs — APPROVED** [review]

**Comment by churik** [comment]
@cammellos 
definitely an improvement in comparison with the current `develop`.
also rechecked PNs on Andoroid 13 - works as expected, including fetching from offline, so likely `702808` fail will be addressed separately in PR.

Thank you for the fix, awesome work!
Glad that e2e are still finding hard-to-chase issue regardless of their stability.
