### PR TITLE
Fix chat permission-context

### LINKED ISSUE #16975: Drop shadow is missing in Permissions Context drawer component
**Design:** https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2465-44216&mode=design&t=F8V2TGmGKXuQPtf8-0
**Use Case:** https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8364-515022&mode=design&t=ksqF2RHDZcIUB1j8-0

- [ ] We are currently using permission context drawer component in messages screen for contact request drawer.
Original component and use case both are missing drop shadows.
- [ ] Apart from drop shadows, margins are also wrong. There is more space at the bottom of drawer in designs then implementation. 

#### Screenshots

<div align="center">

</div>

(feel free to close the issue, if already logged)

### LINKED ISSUE #19224: Communities - Wrong permission context in an Open Community channel
# Design Feedback 2.27

## [Communities] Wrong permission context in an Open Community channel
**Wrong permission context** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=123:76550&mode=design#729071586)] When opening a channel of an Open Community you're not a member of, the permission context has wrong icon and copy:

Screenshot 2024-03-13 alle 11 45 45

#### Expected behavior
Screenshot 2024-03-13 alle 11 46 18

### Reproduction

1. Open an Open Community you're not a member of
2. Open an Open Channel

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19224
fixes #16975

### Summary

Fixes included:
1. Improved `permission-context` quo component based on design requirements
2. Updated the `permission-context` preview
3. Moved unnecessary subscriptions from composer into the child using them
4. Refactored chat drawer logic
5. Added "Join community to post" if chat in community
6. Added blur view
7. Added shadow that works with android as well (with `react-native-shadow-2`)

> I had a hard time to find all the possible states and flows of the `permission-context` component in the chat (e.g community request pending, community request denied, etc.), if we even have them.
 
##### Functional

- 1-1 chats
- public chats
- group chats
- community channels

### Steps to test

- Open Status
- open community you're not part of
- press "join community to post"

### Screenshots
Before and after (android):

status: ready

### CODE REVIEW

**Comment by clauxx** [comment]
oops, forgot about the tests. Converted to draft for now.

**Review by flexsurfer — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Great that now permission context contains a correct icon. 👏

As regarding the permission-context design I see that it doesn't look as described [here](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2500-41324&mode=design&t=mf0ysNc6sOqzesrg-0). 

**Design**
Screenshot 2024-04-04 at 13 16 19

**iPhone 13**
Screenshot 2024-04-04 at 13 14 54

As for me it has a grey color where "Join community to post" is located. 

**Android** looks fine as for me
Screenshot 2024-04-04 at 13 27 12

Let me know is it a correct version or not. In case "yes" I'll move this PR to the design review.
Thanks!

**Comment by clauxx** [comment]
@mariia-skrypnyk should be fine now. Please have a look

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Now ok from my side.
Thanks!
Move it to @Francesca-G review.

**Review by FFFra — APPROVED** [review]
Great work!

**Review by Francesca-G — APPROVED** [review]
Looks good to me 👍

Please check the shadow because it looks like it's a bit harsher / bigger than design, but it's a minor detail:

Screenshot 2024-04-05 alle 18 15 54

>
(Implementation on the right)

File: src/quo/components/drawers/permission_context/view.cljs [hunk 1]
```diff
@@ -1,13 +1,101 @@
...
+     :token-value  token-value
+     :token-symbol token-symbol}]
+   [text/text {:style {:margin-left 3}}
+    (i18n/label :t/hold-to-post-2)]])
+
+(defn- token-group
+  [blur? idx group]
+  ^{:key idx}
+  [rn/view {:style style/token-group}
+   (when-not (= idx 0)
```
Comment (ibrkhalil) [inline src/quo/components/drawers/permission_context/view.cljs]: Can be `(zero? idx)`

File: src/quo/components/drawers/permission_context/view.cljs [hunk 2]
```diff
@@ -1,13 +1,101 @@
...
+        [number-tag/view
+         {:size   :size-24
+          :number "9999" ;; show the options tag
+          :blur?  blur?
+          :type   :rounded}]])
+     [text/text {:style {:margin-left 3}}
+      (i18n/label :t/hold-to-post-2)]]))
+
+(defn- view-internal
+  [{:keys [on-press blur? type container-style] :as props}]
```
Comment (ibrkhalil) [inline src/quo/components/drawers/permission_context/view.cljs]: Can be destructured in a way that doesn't shadow clojure vars.

File: src/quo/components/drawers/permission_context/view.cljs [hunk 3]
```diff
@@ -1,13 +1,101 @@
...
+          :overlay-color (colors/theme-colors colors/white-70-blur colors/neutral-95-opa-70-blur)
+          :blur-type     :transparent}])
+      [button/button
+       {:type      :ghost
+        :size      24
+        :on-press  on-press
+        :icon-left (when (= type :action)
+                     (:action-icon props))}
+       (condp = type
+         :action                (:action-label props)
```
Comment (ibrkhalil) [inline src/quo/components/drawers/permission_context/view.cljs:95]: action-label can be destructured.

File: src/quo/components/drawers/permission_context/view.cljs [hunk 4]
```diff
@@ -1,13 +1,101 @@
...
+          :blur-amount   20
+          :blur-radius   (if platform/ios? 20 10)
+          :overlay-color (colors/theme-colors colors/white-70-blur colors/neutral-95-opa-70-blur)
+          :blur-type     :transparent}])
+      [button/button
+       {:type      :ghost
+        :size      24
+        :on-press  on-press
+        :icon-left (when (= type :action)
+                     (:action-icon props))}
```
Comment (ibrkhalil) [inline src/quo/components/drawers/permission_context/view.cljs:93]: Can be destructured.

File: src/status_im/contexts/chat/messenger/composer/view.cljs [hunk 5]
```diff
@@ -172,12 +172,10 @@
...
   [props]
-  (let [{:keys [chat-id
-                contact-request-state
-                group-chat
-                able-to-send-message?]
-         :as   chat} (rf/sub [:chats/current-chat-chat-view])]
-    (when (seq chat)
+  (let [current-chat-id       (rf/sub [:chats/current-chat-id])
+        able-to-send-message? (rf/sub [:chats/able-to-send-message?])]
+    (when (seq current-chat-id)
```
Comment (ibrkhalil) [inline src/status_im/contexts/chat/messenger/composer/view.cljs]: current-chat-id is a string
We can use `(when-not (string/blank? current-chat-id)`

**Review by ibrkhalil — APPROVED** [review]

File: src/quo/components/drawers/permission_context/view.cljs (hunk 3 above)
Comment (clauxx) [reply src/quo/components/drawers/permission_context/view.cljs:95]: I did this on purpose, as `:action-label` and `:action-icon` are specific to the `:action` type. Same for the other types, just there I used `select-keys` to extract the prop.

File: src/quo/components/drawers/permission_context/view.cljs (hunk 4 above)
Comment (clauxx) [reply src/quo/components/drawers/permission_context/view.cljs:93]: replied above for this as well

File: src/status_im/contexts/chat/messenger/composer/view.cljs (hunk 5 above)
Comment (clauxx) [reply src/status_im/contexts/chat/messenger/composer/view.cljs]: You can also use `seq` to check if a string is empty as well. It's more compact and don't have to require `string`

Comment (ibrkhalil) [reply src/status_im/contexts/chat/messenger/composer/view.cljs]: But it's not ideal, As `string/blank?` is faster.
CC: @flexsurfer

Comment (ibrkhalil) [reply src/status_im/contexts/chat/messenger/composer/view.cljs]: I think the convention here is to stick with it for strings.

Comment (clauxx) [reply src/status_im/contexts/chat/messenger/composer/view.cljs]: wasn't aware of it being faster. Since this is happening in the chat it's better to go with the quicker one. Thanks @ibrkhalil

**Comment by mariia-skrypnyk** [comment]
@clauxx ping me please if there are changes to test.

**Comment by clauxx** [comment]
> @clauxx ping me please if there are changes to test.

There were no significant changes in the last commit, so it should be fine :+1:
