### PR TITLE
Wrong number of collectibles in the list and they are mixed up [#4904]

### LINKED ISSUE #4904: Wrong number of collectibles in the list and they are mixed up
### Description

I have 19 cryptostrikers
image

 , if i press and open a list there are only **5** of them listed
, if i close and open again **8** of them listed
,if i close and open again, they **mixed up**

image

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #4904

1) bug in `token-of-owner-by-index` only 10 first token can be received successfully from blockchain - fixed
2) bug with http requests on ios, it's bad practice to call a lot of small http requests in a row, better one and big, so it's possible to request only 3 tokens on ios - fixed
3) only one collectible has id, other collectible views mixed up , so wrong collectible picture or wrong description or name - fixed
4) 0 collectibles shown after select token in the wallet - fixed
5) etheremon collectible can't be opened in browser - fixed
6) only 20 CK will be shown - incresed up to 100

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/views.cljs [hunk 1]
```diff
@@ -25,7 +25,7 @@
             [status-im.ui.screens.profile.contact.views :as profile.contact]
             [status-im.ui.screens.profile.group-chat.views :as profile.group-chat]
             [status-im.ui.screens.profile.photo-capture.views :refer [profile-photo-capture]]
-            [status-im.ui.screens.wallet.collectibles.views :as collectibles]
+            [status-im.ui.screens.wallet.collectibles.views :refer [collectibles-list]]
```
Comment (goranjovic) [inline src/status_im/ui/screens/views.cljs:28]: why `:as` -> `:refer` ?

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/views.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/views.cljs:28]: just to be consistent with all other imports , we use `:refer` in this file, so , maybe we should refactor all this file then

**Comment by Serhy** [comment]
Builds https://i.diawi.com/gx6Usn and https://i.diawi.com/2FHNpA were tested with @flexsurfer. No regressions were noticed (failed autotest re-run and confirmed as false failed, addressed and should be fixed now)



<blockquote><div><strong><a href="https://i.diawi.com/gx6Usn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/2FHNpA">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
