### PR TITLE
[#20463] Multiple fixes on Collectibles

### LINKED ISSUE #20229: Unable to open collectible detailed page after backgrounding
### Description:
After adding watch-only accounts containing a sufficient amount of collectibles, attempting to open any collectible's detailed page after being in the background for 3-5 minutes does not work.

### Steps:
1. Add watch only account with a sufficient amount of collectibles: (example: `0x8d51191dd7e371bd88ab9797b11b03da3084de6e`, `0x8d2413447ff297d30bdc475f6d5cb00254685aae`) 
2. Relogin to fetch all collectibles
3. Background the app for 3-5 minutes.
4. Return to the collectibles section.
5. Attempt to open any collectible's detailed page.

### Actual result:
The collectibles detailed page is not opened

https://github.com/status-im/status-mobile/assets/52490791/46c636e8-0d52-4a6f-88d6-b6e1c79457a5

### Expected result:
A collectible detailed page is opened

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/15480962/Status-debug-logs.2.zip)

### LINKED ISSUE #20463: [IOS] "Unsupported file" shown on detailed collectible view for some collectibles while images are fetched on list view
### Steps:
1. Restore a user with collectibles from this https://testnets.opensea.io/collection/the-monkey-chainz collection or add the address as watch only '0xeD620C9dC11401b63B35Dfe8e93F2b11DB0F6F9e' (NOTE: current collectibles are on the testnet)
2. Go to collectibles tab
3. Open collectible to see the detailed view

### Actual result:
"Unsupported file" message is shown on the detailed collectibles view, while the images are fetched on the list view.

https://github.com/status-im/status-mobile/assets/52490791/13de5823-8acb-4a09-b5a9-db8279892b55

### Expected result:
If the collectible image is fetched on the list view, it should also be fetched for the detailed view.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/15837245/Status-debug-logs.zip)

### ENV:
Nightly 14 Jun 2024

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #20463
fixes #20229 

## Summary

This PR implements various fixes related to the collectibles.

- :white_check_mark:  #20463 - But it's important to note that it is an status-go issue, sometimes Status go returns data for the listing but not when the collectible is selected. This has been addressed client-side.

- :white_check_mark:  #20229  - This is due to Status-go no longer anwering to calls, the navigation depended on the status-go response, now this has been changed, so this issue has been solved.

### Additional fixes

- :white_check_mark: Unknown variant has been implemented and it's being used in the collectible listing:

    

- :white_check_mark: We were displaying the collection name instead of the collectible name and sometimes we just displayed a blank collectible:

    Before vs Now:
     

- :white_check_mark: The experience of opening a collectible is now smoother:
    Before (we had a blink):

    https://github.com/status-im/status-mobile/assets/90291778/fb9a14b6-f3cb-409b-b909-30d682e37041

    Now:

    https://github.com/status-im/status-mobile/assets/90291778/330b1118-73fd-4340-b940-11c3338101f8

### Review notes
Some other refactorings/renamings to subs were made. They are being mentioned in the self-review

status: ready

### CODE REVIEW

File: src/quo/components/profile/collectible_list_item/style.cljs [hunk 1]
```diff
@@ -60,8 +60,13 @@
...
 
-(def card-detail-text
-  {:flex 1})
+(defn card-detail-text
+  [empty-name? theme]
+  {:flex         1
+   :margin-right 8
+   :color        (if empty-name?
+                   (colors/theme-colors colors/neutral-50 colors/neutral-40 theme)
+                   (colors/theme-colors colors/neutral-100 colors/white theme))})
```
Comment (ulisesmac) [inline src/quo/components/profile/collectible_list_item/style.cljs:69]: Needed for the "Unknown" variant

File: src/quo/components/profile/collectible_list_item/style.cljs [hunk 2]
```diff
@@ -115,6 +120,7 @@
   [{:opacity opacity}
    {:flex           1
     :flex-direction :row
+    :column-gap     8
     :opacity        default-opacity-for-image}])
```
Comment (ulisesmac) [inline src/quo/components/profile/collectible_list_item/style.cljs:124]: We had an empty view as separator, instead now the code is using `column-gap`

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 3]
```diff
@@ -93,31 +94,43 @@
...
+
+        :else
         [collection-avatar/view
          {:size        :size-20
           :on-start    #(set-load-time (fn [start-time] (- (datetime/now) start-time)))
-          :on-load-end #(on-load-avatar {:set-state      set-state
-                                         :load-time      load-time
-                                         :loader-opacity loader-opacity
-                                         :avatar-opacity avatar-opacity})
+          :on-load-end set-avatar-loaded
```
Comment (ulisesmac) [inline src/quo/components/profile/collectible_list_item/view.cljs:121]: Fixes to avoid the blank collectibles

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 4]
```diff
@@ -11,38 +11,24 @@
...
+  (reanimated/animate loader-opacity 0 loader-out)
+  (reanimated/animate image-opacity 1 image-in))
 
 (defn on-load-error
-  [set-state]
-  (js/setTimeout (fn []
-                   (set-state (fn [prev-state] (assoc prev-state :image-error? true))))
-                 error-wait-time))
+  [set-error]
+  (js/setTimeout set-error error-wait-time))
```
Comment (ulisesmac) [inline src/quo/components/profile/expanded_collectible/view.cljs:27]: Simplified the calculations for the animation, it's still looks good but the implementation is a bit simpler

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 5]
```diff
@@ -137,7 +125,8 @@
       [:square? {:optional true} [:maybe boolean?]]
       [:counter {:optional true} [:maybe string?]]
       [:on-press {:optional true} [:maybe fn?]]
-      [:on-collectible-load {:optional true} [:maybe fn?]]]]]
+      [:on-collectible-load {:optional true} [:maybe fn?]]
+      [:gradient-color-index {:optional true} [:maybe keyword?]]]]]
```
Comment (ulisesmac) [inline src/quo/components/profile/expanded_collectible/view.cljs:129]: New prop, previously the gradient color was always the same

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 6]
```diff
@@ -166,39 +160,58 @@
...
    (let [request-id               0
          collectible-id-converted (cske/transform-keys transforms/->PascalCaseKeyword collectible-id)
          data-type                (collectible-data-types :details)
          request-params           [request-id [collectible-id-converted] data-type]]
-     {:db (assoc-in db [:wallet :last-collectible-aspect-ratio] aspect-ratio)
+     {:db (assoc-in db
+           [:wallet :ui :collectible]
+           {:details        collectible
+            :aspect-ratio   aspect-ratio
+            :gradient-color gradient-color})
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs:176]: Moved the collectible data to `:wallet :ui :collectible`, instead of `:wallet :last-collectible...`

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 7]
```diff
@@ -166,39 +160,58 @@
...
        (log/error "failed to get collectible details"
                   {:event    :wallet/get-collectible-details-done
                    :response response})))))
 
 (rf/reg-event-fx
- :wallet/clear-last-collectible-details
+ :wallet/clear-collectible-details
  (fn [{:keys [db]}]
-   {:db (update-in db [:wallet] dissoc :last-collectible-details :last-collectible-aspect-ratio)}))
+   {:db (update-in db [:wallet :ui] dissoc :collectible)}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs:214]: Events were renamed to remove the word `last`, that `last` word is misleading, since we don't have multiple collectibles or a first one.

Now the events and keys are just referring to it as `:collectible`. and the route in the dB is `:wallet :ui :collectible`

File: src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs [hunk 8]
```diff
@@ -64,7 +62,12 @@
...
-   [traits-section]])
+  [collectible]
+  (let [owner-account (rf/sub [:wallet/collectible-details-owner collectible])
+        traits        (-> collectible :collectible-data :traits)]
+    [:<>
+     [info
+      {:chain-id (-> collectible :id :contract-id :chain-id)
+       :account  owner-account}]
+     (when (pos? (count traits))
+       [traits-section traits])]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs:73]: Made this component more flexible and reusable, previously we had subscriptions that only worked as extractors, now when we want to extract a value we just do it from the `collectible` received.

File: src/status_im/subs/wallet/collectibles.cljs [hunk 9]
```diff
@@ -91,35 +90,36 @@
...
+     (:details $)
+     (assoc $ :preview-url (preview-url $)))))
 
 (re-frame/reg-sub
- :wallet/last-collectible-details-chain-id
- :<- [:wallet/last-collectible-details]
+ :wallet/collectible-aspect-ratio
+ :<- [:wallet/collectible]
  (fn [collectible]
-   (get-in collectible [:id :contract-id :chain-id])))
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/collectibles.cljs:110]: This subscription is not needed, it is just working as an extractor, and a deep one (because of `get-in` these extractions are only being used in a component that already has access to the `collectible`, so using these subs makes the code harder to track

File: src/status_im/subs/wallet/collectibles.cljs [hunk 10]
```diff
@@ -91,35 +90,36 @@
...
-   (let [address (:address (first (:ownership collectible)))
-         account (get-in wallet [:accounts address])]
-     account)))
+ :wallet/collectible-details-owner
+ :<- [:wallet/accounts]
+ (fn [accounts [_ collectible]]
+   (let [collectible-address (-> collectible :ownership first :address)]
+     (some #(when (= (:address %) collectible-address)
+              %)
+           accounts))))
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/collectibles.cljs:124]: Updated this sub to receive the collectible we want to use, this change makes this sub reusable

Comment (ulisesmac) [reply src/status_im/subs/wallet/collectibles.cljs:124]: Also it's been modified to depend on `wallet/accounts` instead of just the `:wallet` (which is updated very often)

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 11]
```diff
@@ -21,7 +22,7 @@
 (def cached-load-time 200)
 (def error-wait-time 800)
 
-(defn on-load-end
+(defn animate-loading-image
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs:25]: Can be private?

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 12]
```diff
@@ -11,38 +11,24 @@
...
 
-(def timing-options-out 650)
-(def timing-options-in 1000)
-(def first-load-time 500)
-(def cached-load-time 200)
+(def loader-out 650)
+(def image-in 1000)
 (def error-wait-time 800)
 
 (defn on-load-end
```
Comment (OmarBasem) [inline src/quo/components/profile/expanded_collectible/view.cljs:20]: can be private

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 13]
```diff
@@ -11,38 +11,24 @@
...
-       (set-state (fn [prev-state]
-                    (assoc prev-state :image-loaded? true))))
-     first-load-time)
-    (set-state (fn [prev-state]
-                 (assoc prev-state :image-loaded? true)))))
+  [{:keys [loader-opacity image-opacity]}]
+  (reanimated/animate loader-opacity 0 loader-out)
+  (reanimated/animate image-opacity 1 image-in))
 
 (defn on-load-error
```
Comment (OmarBasem) [inline src/quo/components/profile/expanded_collectible/view.cljs:25]: can be private

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 14]
```diff
@@ -67,62 +53,64 @@
...
+                                     :image-opacity  image-opacity}))
+        :on-error    #(on-load-error set-error)
+        :on-load     on-collectible-load}]
+      (when counter
+        [counter-view counter])
+      [rn/view {:style (style/collectible-border theme)}]]]))
+
 (defn view-internal
   [{:keys [container-style square? on-press counter image-src native-ID supported-file?
-           on-collectible-load aspect-ratio]}]
```
Comment (OmarBasem) [inline src/quo/components/profile/expanded_collectible/view.cljs:72]: private

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 15]
```diff
@@ -166,39 +160,58 @@
...
+           ;; By doing it, we skip a blink while visiting the collectible detail page.
+           [:dispatch-later
+            {:ms       1
+             :dispatch [:navigate-to :screen/wallet.collectible]}]]})))
+
+(defn- keep-not-empty-value
+  [old-value new-value]
+  (if (or (string/blank? new-value) (nil? new-value))
+    old-value
+    new-value))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/collectible/events.cljs:195]: [NIT]: I think should be `keep-non-empty-value`

File: src/status_im/contexts/wallet/home/tabs/view.cljs [hunk 16]
```diff
@@ -17,9 +17,7 @@
                               :name  (:name collectible-data)
                               :image (:uri preview-url)}])}]))
 
-(defn- on-collectible-press
-  [{:keys [id]} aspect-ratio]
-  (rf/dispatch [:wallet/get-collectible-details id aspect-ratio]))
+(def on-collectible-press #(rf/dispatch [:wallet/navigate-to-collectible-details %]))
```
Comment (vkjr) [inline src/status_im/contexts/wallet/home/tabs/view.cljs:20]: I'd name this by functionality and not by place of invocation, `navigate-to-details` maybe.

**Review by vkjr — APPROVED** [review]

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 17]
```diff
@@ -166,39 +160,58 @@
...
                           (log/error "failed to request collectible"
-                                     {:event  :wallet/get-collectible-details
+                                     {:event  :wallet/navigate-to-collectible-details
                                       :error  error
-                                      :params request-params}))}]]]})))
+                                      :params request-params}))}]]
+           ;; We delay the navigation because we need re-frame to update the DB on time.
+           ;; By doing it, we skip a blink while visiting the collectible detail page.
+           [:dispatch-later
+            {:ms       1
```
Comment (BalogunofAfrica) [inline src/status_im/contexts/wallet/collectible/events.cljs:188]: Any reason why `1ms` why chosen specifically? Or would the delay of 1ms be sufficient because we can't tell how long re-frame would take to finish the job?

Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/events.cljs:188]: I used 1ms because we just need this to be dispatched in the following "batch" of executions. For that moment, the re-frame db changes are ready.

**Comment by mariia-skrypnyk** [comment]
Hi @ulisesmac !
Checked both fixes and now it looks good as expected.
Thanks for your work!
PR can be merged.
