### PR TITLE
[#21939] fix: handle sign message after dapp pairing

### LINKED ISSUE #21939: Faling connection to dapp (CoinMarketCap)
# Bug Report

## Problem 
[comment]: # (A problem description)
When attempting to connect to https://coinmarketcap.com pairing succeeds, but it fails on the next step during authentication via `personal_sign`.  Also the message is not visible to the user on the signing modal.

It seems like the issue is that most dapps send the `personal_sign` data as hex already, while here they send it as UTF-8. We should check if the data is sent as hex before hashing it, and if it's not - hex it ourselves. The same with displaying it - only decode it to UTF-8 if it is hex encoded.

#### Expected behavior
Can see the authentication message (message signing) and connect to CoinMarketCap successfully.

#### Actual behavior
Can't see the message nor connect to CoinMarketCap 

### Reproduction

1. Go to https://coinmarketcap.com
2. Press Connect
3. Open Status app and log in
4. Scan the QR code
5. Approve pairing
6. The dapp should react and prompt a captcha puzzle
7. When done, it should send a `personal_sign` request
8. The request message will be empty (!)
9. After approving signing via password/biometrics/keycard, it should show an error (!)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21939

## Summary
Can't see the message nor connect to CoinMarketCap

### Areas that may be impacted

- Dapp pairing and personal sign

## Steps to test

1. Go to https://coinmarketcap.com/
2. Press Connect
3. Open Status app and log in
4. Scan the QR code
5. Approve pairing
6. The dapp should react and prompt a captcha puzzle
7. When done, it should send a personal_sign request

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/wallet_connect/events/session_requests.cljs [hunk 1]
```diff
@@ -61,14 +62,17 @@
  :wallet-connect/process-personal-sign
  (fn [{:keys [db]}]
    (let [[raw-data address] (data-store/get-db-current-request-params db)
-         parsed-data        (native-module/hex-to-utf8 raw-data)]
+         hex-message        (if (utils-address/has-hex-prefix? raw-data)
+                              raw-data
+                              (native-module/utf8-to-hex raw-data))
+         parsed-data        (native-module/hex-to-utf8 hex-message)]
```
Comment (vkjr) [inline src/status_im/contexts/wallet/wallet_connect/events/session_requests.cljs]: Looks like if `hex-message` is false, we will make utf8-to-hex conversion and than back :)
can it be replaced with?
```clojure
parsed-data (if (utils-address/has-hex-prefix? raw-data)
                    (native-module/hex-to-utf8 raw-data)
                    raw-data)
```

**Review by vkjr — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @mohsen-ghafouri thank you for PR. No issues from my side. PR is ready to be merged

**Comment by VolodLytvynenko** [comment]
Forgot to summarize the manual testing that was done:
- The flow described in the PR description using Keycard and Manual Signature.
- Various connection methods suggested by the tool: https://se-sdk-dapp.vercel.app/.
- Connection scenarios where the dapps should prompt signatures one by one, tested with Uniswap and 1inch.
- Ensured there are no regressions.
