### PR TITLE
[#12321] No redirect from "Confirm the passcode" screen while resetti…

### LINKED ISSUE #12321: No redirect from "Confirm the passcode" screen while resetting Keycard with the mnemonic if card was frozen during tx signing
# Bug Report

## Problem 

If Keycard was frozen during tx signing, and User tries to reset it with mnemonic, then after confirmation of the passcode, this screen won't be closed.

#### Expected behavior

"Confirm the passcode" screen is closed after confirmation, redirect to Wallet tab

#### Actual behavior

https://user-images.githubusercontent.com/67952253/126186584-29d4b946-f535-4a51-89f3-b97068aad500.mp4

### Reproduction

1. Open Status
2. Open Wallet > Send transaction 
3. Enter invalid passcode three times
4. Tap "Reset with mnemonic"
5. Enter seed phrase
6. Create a new and confirm 6-digit passcode

### Additional Information

- Status version: nightly 19/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #12321

### CODE REVIEW

**Review by bitgamma — APPROVED** [review]

File: src/status_im/keycard/backup_key.cljs [hunk 1]
```diff
@@ -16,6 +16,7 @@
   (fx/merge cofx
             {:db (-> db
                      (assoc-in [:keycard :creating-backup?] backup-type))}
+            (navigation/change-tab :profile)
```
Comment (bitgamma) [inline src/status_im/keycard/backup_key.cljs]: does this work when creating a recovery card from logged out state? (through the "lost or frozen keycard" link in the login screen)

Comment (flexsurfer) [reply src/status_im/keycard/backup_key.cljs]: good point
