### PR TITLE
[#18458] Token input fixes

### LINKED ISSUE #18458: Erratic behavior of entered numbers in the input field on send page
Follow up https://github.com/status-im/status-mobile/pull/17786

### Steps:
1. Enter data rapidly into the send textboxin the send asset input field

### Actual result:
The numbers appear to jump or behave erratically upon entry into the text box, especially when entered quickly.

https://github.com/status-im/status-mobile/assets/52490791/9faa1386-897a-4575-9eb3-99f06c07d1d9

### Expected result::
Data entry into the text box should occur smoothly without any erratic behavior,

### ENV:
- Real device: Pixel 7a, Android 13

### LINKED ISSUE #18459: Inability to Input new value before the previous value on the send assets page
introduced in https://github.com/status-im/status-mobile/pull/19750

### Steps:
1. Enter any single number into the ETH textbox (e.g., "2").
2. Move the cursor before the entered data and input another value (e.g., "1").

### Actual result:
The new value (e.g., "1") is appended after the previous value (e.g., resulting in "21"). The new value is not inserted before the previous entry.

https://github.com/status-im/status-mobile/assets/52490791/867c9a51-46af-4ed0-87c6-1fc3f07a1732

### Expected result:
The new value (e.g., "1") should be inputted before the previous value (e.g., should display "12"), allowing the user to insert values in between existing entries.

cc: @vkjr

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #18458 

### Summary

This PR solves the flickering we were having in the token input component:

before (taken by @VolodLytvynenko):

https://github.com/status-im/status-mobile/assets/52490791/9faa1386-897a-4575-9eb3-99f06c07d1d9

now: 

[Screencast from 2024-01-16 00-12-59.webm](https://github.com/status-im/status-mobile/assets/90291778/4a683572-0f1c-463f-9b4a-a0af2b90597f)

**Note**: I'm taking multiple issues to improve the token input component, I was thinking about solving all of them in a single PR, but it's a lot of work/refactoring, I decided that it was better to open smaller PRs.

### Review notes

I also modified the preview screen, so that our custom keyboard is used to test this input.

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Own an account that is able to send tokens
- Go to to wallet tab -> pick the account to send tokens -> press on the send icon/button -> pick an account to send -> use the token input

**Important** this issue is only addressing the flickering, not the rest of the issues, they will be addressed separately.

Also notice that
-  #18495

is not caused or addressed by this PR.

status: ready

### CODE REVIEW

File: src/quo/components/wallet/token_input/view.cljs [hunk 1]
```diff
@@ -7,85 +7,121 @@
...
-  (let [num-value (if (string? value) (parse-double (or value "0")) value)]
+  (let [num-value (if (string? value)
+                    (or (parse-double value) 0)
+                    value)]
     (if crypto?
       (str (get common/currency-label currency) (.toFixed (* num-value conversion) 2))
-      (str (.toFixed (/ num-value conversion) 2) " " (string/upper-case (or (clj->js token) ""))))))
+      (str (.toFixed (/ num-value conversion) 2)
+           " "
+           (string/upper-case (or (clj->js token) ""))))))
```
Comment (ulisesmac) [inline src/quo/components/wallet/token_input/view.cljs]: We need a function that takes token symbols (`:eth`) and return some user friendly string ("ETH"), I thought it already existed, but I couldn't find it.

These conversions are very error-prone, and they've given us some runtime crashes

File: src/status_im/contexts/preview/quo/wallet/token_input.cljs [hunk 2]
```diff
@@ -24,17 +25,29 @@
...
+        :full-screen?              true
+        :component-container-style {:flex            1
+                                    :justify-content :space-between}}
+       [quo/token-input (assoc @state :value @value)]
+       [quo/numbered-keyboard
+        {:container-style {:padding-bottom (safe-area/get-top)}
+         :left-action     :dot
+         :delete-key?     true
+         :on-press        set-value
+         :on-delete       delete}]])))
```
Comment (ulisesmac) [inline src/status_im/contexts/preview/quo/wallet/token_input.cljs:53]: Added the `numbered-keyboard` to test this input in the preview screen.
It required to modify the `preview-container`, now receives a `full-screen?` boolean

cc: @ilmotta

File: src/quo/components/wallet/token_input/style.cljs [hunk 3]
```diff
@@ -16,27 +16,56 @@
...
+   :right    0})
+
+(def text-input-dimensions
+  (assoc typography/heading-1
+         :font-weight  "600"
+         :margin-left  8
+         :margin-right (if platform/ios? 6 4)
+         :padding      0
+         :height       "100%"))
+
```
Comment (OmarBasem) [inline src/quo/components/wallet/token_input/style.cljs]: I am not sure all these changes is necessary. Ref: https://github.com/status-im/status-mobile/pull/18522#pullrequestreview-1822742080

Comment (ulisesmac) [reply src/quo/components/wallet/token_input/style.cljs]: @OmarBasem 

Thanks for sharing.
 I replied there about the design not being the same while solving the flickering.
 
 I tried many things, such as:
 - Trying to set the token name (e.g. "ETH") as an absolute container and tracking the width of the input, but it lead to one frame of delay, which looked realled bad.
 - Set "ETH" as part of the input's text, but it became editable
 
 so I realized this one was the best to avoid flickering, it doesn't have a 1 frame delay and it doesn't change the designs.

File: src/quo/components/wallet/token_input/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/quo/components/wallet/token_input/view.cljs]: Good point @ulisesmac. I have noticed that too in status-mobile. String manipulation in Clojure doesn't follow nil punning like collection functions do. It's a common source of error. I think the error prone aspect also comes from the lack of this knowledge. 

I believe it's one of the reasons we have functions like `safe-trim` or `safe-replace`, because some mobile developers got tired of these nil pointer exceptions and the need to remember to check for nils, so they decided to wrap core cljs string functions. I did this too.

But these wrapping functions in `utils.string` are a fragile solution and require this effort to wrap cljs functions and make the code more verbose (longer function names).

To me, all of us should just remember that almost anything can be nil in mobile, therefore, string manipulation should be considered unsafe without `some->` or `or`.

**Review by J-Son89 — APPROVED** [review]

File: src/quo/components/wallet/token_input/style.cljs (hunk 3 above)
Comment (OmarBasem) [reply src/quo/components/wallet/token_input/style.cljs]: Thank you @ulisesmac for the clarification. Closed my PR.

**Review by OmarBasem — APPROVED** [review]

File: src/quo/components/wallet/token_input/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/quo/components/wallet/token_input/view.cljs]: Yes, sounds good, but, is there a way to override the string implementation?

TBH, I see this as a ClojureScript error, they are not consistent with their implementation, see `string/blank?`:
image

They are calling `gstring/makeSafe` why not call it in other places too?

I think it'd be ok if we just override some cljs.core implementations to add a call to `makeSafe`. I know, probably not the best, but IMO they are also not doing the best.

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM

**Comment by VolodLytvynenko** [comment]
Hey @ulisesmac thank you for PR. This issue related to flickering is fixed. One minor additional issue is found which is addressed by this PR

## ISSUE 1: [IOS] The asset label is initially too close to 0 value

### Steps:
1. Open input assets screen

### Actual result:
image

https://github.com/status-im/status-mobile/assets/52490791/9864cbe8-d2f2-4104-839b-5d3d2684ff83

### Expected result:
image
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=220-148036&mode=design&t=gxwE0s3OwFbp1Ybn-0

### Device:
iPhone 11 Pro max, IOS 16

**Comment by ulisesmac** [comment]
> Hey @ulisesmac thank you for PR. This issue related to flickering is fixed. One minor additional issue is found which is addressed by this PR
> ## ISSUE 1: [IOS] The asset label is initially too close to 0 value
 
> iPhone 11 Pro max, IOS 16

Hey @VolodLytvynenko 
Thaks for testing, will fix it soon!

**Comment by vkjr** [comment]
@ulisesmac, could you please extend the PR description and describe what approach you used to reduce flickering? I think that could be beneficial for the future. For example when someone will be solving similar problem and looking for related PRs)

**Comment by ulisesmac** [comment]
@VolodLytvynenko 
Now it has been fixed, could you please test it again?

Here's the iOS version working:

https://github.com/status-im/status-mobile/assets/90291778/c97e0071-b202-4cd5-b647-40405652723c

And Android:

[Screencast from 2024-01-19 22-00-07.webm](https://github.com/status-im/status-mobile/assets/90291778/59a1d62a-7458-4377-80a2-89eaa1f65181)

**Comment by ulisesmac** [comment]
> @ulisesmac, could you please extend the PR description and describe what approach you used to reduce flickering? I think that could be beneficial for the future. For example when someone will be solving similar problem and looking for related PRs)

 @vkjr 
Yeah, sorry, I missed the details this time.

The reason the input was flickering wasn't due to a state update or state propagation issue (like reagent re-renders). (cc: @Rende11 you may remember this).

The issue was that the input's width was growing as the user typed, it seems this is something we should always avoid and instead set a fixed input width.

But we can't set a fixed width because that token name ("ETH", "RARE", etc) should be right after the amount, and a fixed width will move the token name to the end. (check Omar's attempt, he showed some pictures).

The first solution I tried was making that token name track the input's layout dimensions, The problem with this approach is that we have a very noticeable 1 frame delay, and lead to problems to render the first frame when there's no input dimensions.

So I solved it by creating a "phantom" copy of the input on top of the actual input, opacity zero, no pointer events and not being able to be edited. It makes the exact spacing for "RARE"/"ETH"/... to be correctly placed.

In the code the component is the function called `token-label`.

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for PR. No issue from my side. PR ready to be merged
