### PR TITLE
fix - Button colors have become darker

### LINKED ISSUE #18762: Button colors have become darker
# Bug Report

## Problem 

Most likely regression from https://github.com/status-im/status-mobile/pull/18517
@mohsen-ghafouri could you check what colors are actually correct, please?

photo_2024-02-08_13-04-43

image

#### Expected behavior
colors are lighter

#### Actual behavior
colors are too dark

### Additional Information

- Status version: nightly 08/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #18762 

This issue was introduced by my [PR](https://github.com/status-im/status-mobile/pull/18513) when I tried to replace the deprecated `colors/custom-color` function with `colors/resolve-color`. I have reverted the change.

status: ready

### CODE REVIEW

File: src/quo/components/buttons/button/properties.cljs [hunk 1]
```diff
@@ -5,10 +5,10 @@
 (def backgrounds #{:photo :blur})
 
 (defn- custom-color-type
-  [customization-color icon-only? theme]
+  [customization-color icon-only?]
   {:icon-color                  colors/white-opa-70
    :label-color                 colors/white
-   :background-color            (colors/resolve-color customization-color theme)
+   :background-color            (colors/custom-color customization-color 50)
```
Comment (ajayesivan) [inline src/quo/components/buttons/button/properties.cljs]: I'm not sure how to replace this deprecated function. @J-Son89 If you have some insights please let me know.

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: hmm I don't think this is the issue, what you had before is correct actually

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: `:background-color (colors/resolve-color customization-color theme)` should work

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: in fact, you are kind of hard coding "light" theme here (colors/custom-color customization-color 50)
 so this can't be right

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: My bad! 🙃 
This is actually correct. 
We should hardcode this as theme light here `(colors/resolve-color customization-color :light)`

The reason we do this is because we need the button to handle both customization-colors and community colors. However with community colors we only receive a light themed version of the community color (i,e a `-50` variant of that color). For that reason we use a shadow overlay to get the `-60` variant.

**Review by J-Son89 — APPROVED** [review]
nice one @ajayesivan!

File: src/quo/components/buttons/button/properties.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/quo/components/buttons/button/properties.cljs]: Hi @J-Son89,
I am still little confused. So if for communities we are only receiving light themed version and use shadow overlay for 60 variants, what about other places?

Shouldn't button accept theme value, and we pass/hard coding as per use case?

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: the theming is used but it is used in the overlay which is in the button

Comment (Parveshdhull) [reply src/quo/components/buttons/button/properties.cljs]: Like in reported issue, we use/hard code dark theme

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: more details here:
https://github.com/status-im/status-mobile/pull/16536

perhaps the issue is more informative - https://github.com/status-im/status-mobile/issues/16396

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs:11]: Screenshot 2024-02-09 at 13 15 06

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: Screenshot 2024-02-09 at 15 01 43

Comment (Parveshdhull) [reply src/quo/components/buttons/button/properties.cljs]: Thank you for links, now I see how theme/overlay is used. It is used inside button itself, I thought it was part of community use cases.

**Review by Parveshdhull — APPROVED** [review]

File: src/quo/components/buttons/button/properties.cljs (hunk 1 above)
Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: Thanks @Parveshdhull, let me know if there's any further doubts! 
I think it's best @ajayesivan adds a comment to that line about this and if you can take a look to confirm it's clear enough that would be very helpful :)

Comment (Parveshdhull) [reply src/quo/components/buttons/button/properties.cljs]: > I think it's best @ajayesivan adds a comment to that line

or on the top of `custom-color-type` function, maybe something like?

`;; Note: We are hardcoding light theme as background here and then applying overlay when needed (for dark themes and pressed states). We do this because for communities we only have one color (light theme version).`

Comment (J-Son89) [reply src/quo/components/buttons/button/properties.cljs]: yep perfect, and if we can link this issue too that might help - https://github.com/status-im/status-mobile/issues/16396

**Comment by qoqobolo** [comment]
@ajayesivan thanks for the fix, LGTM!
PR can be merged.
