### PR TITLE
Remove not-implemented box from sticker/emoji messages

### LINKED ISSUE #19226: Remove `not-implemented` box from emoji/sticker message components
# Bug Report

## Problem 
[comment]: # (A problem description)
Remove `not-implemented` box from emoji/sticker message components and move them out of legacy

#### Expected behavior
No red box around emoji/sticker messages

#### Actual behavior
Red box around emoji/sticker messages

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19226 

##### Functional

- 1-1 chats
- public chats
- group chats
- notification center

### Steps to test

- Open Status
- login
- enter chat that has an emoji message
- enter chat that has a sticker sent from desktop

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by BalogunofAfrica — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/messages/content/sticker/view.cljs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+(ns status-im.contexts.chat.messenger.messages.content.sticker.view
+  (:require [react-native.core :as rn]
+            [react-native.fast-image :as fast-image]))
+
+(defn sticker-message
```
Comment (cammellos) [inline src/status_im/contexts/chat/messenger/messages/content/sticker/view.cljs]: if we are only using content, (or even better, just `sticker -> url`) can we pass only that?

Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/content/sticker/view.cljs]: done

File: src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+(ns status-im.contexts.chat.messenger.messages.content.emoji.view
+  (:require [react-native.core :as rn]
+            [status-im.contexts.chat.messenger.messages.content.emoji.style :as style]))
+
+(defn emoji-message
+  [{:keys [content last-in-group? pinned]} {:keys [in-pinned-view?]}]
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs]: why can't we just use one map here?

File: src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs [hunk 3]
```diff
@@ -0,0 +1,10 @@
+(ns status-im.contexts.chat.messenger.messages.content.emoji.view
+  (:require [react-native.core :as rn]
+            [status-im.contexts.chat.messenger.messages.content.emoji.style :as style]))
+
+(defn emoji-message
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs]: nit, can we change this to `view` - the ns should be emoji-message.view.

then when you use it, it will be.
`[emoji-message/view ...]`

File: src/status_im/contexts/chat/messenger/messages/content/sticker/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/chat/messenger/messages/content/sticker/view.cljs]: same here, can we make this `view` and perhaps update ns if it improves readability 👍

File: src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs (hunk 2 above)
Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs]: for consistency. Other message components pass both the message data and message context as separate maps. It would be better to only pass the subset of props that it needs, i agree

**Review by J-Son89 — APPROVED** [review]

File: src/legacy/status_im/ui/screens/chat/message/legacy_view.cljs [hunk 4]
```diff
@@ -145,23 +144,6 @@
      [rn/text {:style (style/status-text)}]
      (-> content :parsed-text peek :children))]])
 
-;; EMOJI
```
Comment (J-Son89) [inline src/legacy/status_im/ui/screens/chat/message/legacy_view.cljs:148]: 🙌

File: src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im/contexts/chat/messenger/messages/content/emoji/view.cljs]: I think it makes sense to only pass the parameters it needs (positional probably faster, but less explicit), it's very static content, so we won't have to change it often

**Comment by clauxx** [comment]
@cammellos @J-Son89 addressed your comments

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs [hunk 5]
```diff
@@ -199,10 +201,13 @@
                [content.text/text-content message-data context]
 
                constants/content-type-emoji
-               [not-implemented/not-implemented [old-message/emoji message-data]]
+               [emoji-message/view
+                (-> message-data
```
Comment (cammellos) [inline src/status_im/contexts/chat/messenger/messages/content/view.cljs]: sorry, neatpick :)
because is the chat view, we might want to squeeze as much perf as possible, so maybe best to just create a new object instead of `select-keys` + `assoc` i.e

```
{:content (:content message-data)
 :last-in-group? (:last-in..... messag-data)
...
:in-pinned-view? (:in-pinned-view? context)}

```

just looking at a very rough perf difference:
```
user=> (defn extract-data-2 [m] {:a (:a m) :b (:b m) :c (:c m) :g "g"})
#'user/extract-data-2
user=> (defn extract-data-1 [m] (-> m (select-keys [:a :b :c]) (assoc :g "g")))
#'user/extract-data-1
user=> (def message-data {:a "a" :b "b" :c "c" :d "d" :e "e" :f "f"})
#'user/message-data
user=> (time (dotimes [_ 10000] (extract-data-1 message-data)))
"Elapsed time: 5.786936 msecs"
nil
user=> (time (dotimes [_ 100000] (extract-data-1 message-data)))
"Elapsed time: 87.96445 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-1 message-data)))
"Elapsed time: 735.203584 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-1 message-data)))
"Elapsed time: 848.839143 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-1 message-data)))
"Elapsed time: 757.222673 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-1 message-data)))
"Elapsed time: 717.327672 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-2 message-data)))
"Elapsed time: 109.881926 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-2 message-data)))
"Elapsed time: 89.065761 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-2 message-data)))
"Elapsed time: 162.977585 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-2 message-data)))
"Elapsed time: 171.493888 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-2 message-data)))
"Elapsed time: 118.874594 msecs"
nil
user=> (time (dotimes [_ 1000000] (extract-data-2 message-data)))
"Elapsed time: 111.5382 msecs"
```

avoiding select-keys+assoc is 6/7 times faster, and it doesn't (imo) impact readability so much

Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: thanks for pointing out. Didn't consider this :+1:

**Review by cammellos — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Can you please rebase with resolving conflicts?
Thanks!

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Thanks for your PR.
Despite the fact that this PR didn't require verification from our side, I checkув and everything looks great. 
Thank you for your work!
