### PR TITLE
bug #4737 and #4736 android back button issues with send

### LINKED ISSUE #4736: Amount from the previous transaction is sent instead of current amount
### Description

*Type*: Bug

*Summary*:
Amount from unsuccessful attempt to sign transaction is sent if trigger another transaction and sign it with correct password.

#### Expected behavior
If new transaction is initiated then data is used for this new transaction, not from previous one

#### Actual behavior
Amount from previous attempt to sign transaction with wrong password is sent when new transaction with other amount is signed with correct password

### Reproduction
see from 00:18 https://app.testfairy.com/projects/4803622-status/builds/8486364/sessions/4393851190/?accessToken=Zkyymys0L36x2oS25MWsUZYcHDM
geth log: 
[other tx geth.log](https://github.com/status-im/status-react/files/2095604/other.tx.geth.log)

1.  in 1:1 chat: use /send 0.04 ETH 
2. on Send transaction screen provide wrong password and tap Sign transaction. As a result, error "Wrong password" is shown
3. use "<" button or device back button on Android to return to same 1:1 chat. 
4. in same 1:1 chat use /send 0.000013 ETH and tap send button
5. Note that Send Transaction screen will be shown with Wrong password error. This is probably when it gets wrong.
6. Provide valid password and tap send

As a result, 1:1 chat contains second message with 0.000013 ETH but in fact 0.4 ETH is sent
chat
history

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly june 12
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8486364/sessions/4393851190/?accessToken=Zkyymys0L36x2oS25MWsUZYcHDM">TestFairy: Status 0.9.19 (6047) @152</a></strong></div></blockquote>

### LINKED ISSUE #4737: Several send messages are shown for 1 transaction if use device back button in 1:1 chat
### Description

*Type*: Bug

*Summary*: Extra send message for 1 transaction is shown in 1:1 chat each time when use Android device back button and tap Got it. No extra transaction is sent. Recipient also gets extra send messages in 1:1 chat.
chat1
history1

#### Expected behavior
send message in 1:1 chat is shown only when actual transaction was sent

#### Actual behavior
several send messages are shown in 1:1 chat for 1 transaction

### Reproduction
from 00:16 https://app.testfairy.com/projects/4803622-status/builds/8486364/sessions/4393853570/?accessToken=ZVuHy/rCD/ttmRLPUWbLgNfEKF0
- Open Status
- Open 1:1 chat
- send 0.005 ETH and sign transaction. 
- Tap on Got it to return to 1:1 chat. New send message with 0.005 ETH is sent in the chat
- in 1:1 chat tap Android device back button. As a result, screen with Got it button is shown
- tap Got it again. As a result, new send message 0.005 ETH is sent in the chat. Recipient also sees second message. This is wrong as no second transaction was sent
- Check transaction history in the Wallet: there is only 1 transaction with 0.005 ETH

### Additional Information
* Status version: nightly build June 12
* Operating System: Android 

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8486364/sessions/4393853570/?accessToken=ZVuHy/rCD/ttmRLPUWbLgNfEKF0">TestFairy: Status 0.9.19 (6047) @156</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #4736 
fixes #4737 

### Summary:

Fixes two bugs in chat /send flow that happen when user uses android back button:

#4736

If user tries to sign the transaction A with an incorrect password, then goes back to chat starts transaction B and signs it successfully, A will appear in transaction history (and actually be sent, but B will be displayed in chat history.

The fix is to both transfer and display B in this case. 

#4737 

If user successfully completes a chat /send and then manually navigates back from chat to "Transaction sent" screen and taps "Got it" again, a duplicate payment message will appear.

The fix is not to navigate the user back to "Transaction sent", but to Wallet Send screen. 

### Steps to test:
- see #4736 and #4737

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Review by janherich — APPROVED** [review]

File: src/status_im/chat/events/shortcuts.cljs [hunk 1]
```diff
@@ -16,6 +16,9 @@
   (merge {:db (-> db
                   (send.events/set-and-validate-amount-db (:amount params) :ETH 18)
                   (choose-recipient.events/fill-request-details (transaction-details contact))
+                  (assoc-in [:wallet :send-transaction :id] nil)
```
Comment (rasom) [inline src/status_im/chat/events/shortcuts.cljs]: `(update-in [:wallet :send-transaction] dissoc :id :password :wrong-password?)` or we need to have `nil` there?

Comment (goranjovic) [reply src/status_im/chat/events/shortcuts.cljs]: No idea really, I just saw `nil`s in the repl in the "happy" use case and used that without thinking too much.
It really shouldn't make a difference, so I'll give it a shot since it's a lot cleaner

**Comment by annadanchenko** [comment]
there are 2 other issues that also happen on nightly build, so they are not fixed here nor introduced :)
1. If  cancel transaction signing then it's possible to edit readonly recipient, asset and amount
2. if use Back button on signing tx from DApp then no Send transaction screen is shown for any action in the DApp that should trigger new transaction. Reporting them now
