### PR TITLE
fix crash on logout

### LINKED ISSUE #7139: Crash on enabling/disabling logs or on logout on recovered account after first login
### Description

*Type*: Bug

*Summary*: have a crash when enable\disable logs after first login on recovered account. It is simplest way to reproduce crash on logout - it still happens sometimes when I tap on logout. 
After several crashes I started get constant crash on logout - log in attached files.

#### Expected behavior
no crash

#### Actual behavior
Crash

### Reproduction

- Install status (fresh installation)
- Restore account
- Log in
- Enable logs in advanced settings
- Log in again
- Disable logs in advanced settings

### Additional Information
* Status version: release 0.9.0, rc #1 [https://ci.status.im/job/status-react/job/release/job/release%252Fdesktop%252F0.9.0/1/]
* Operating System: Mac OsX
* Video: http://take.ms/9vq1Z

#### Logs

[Status.log](https://github.com/status-im/status-react/files/2691561/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2691562/geth.log)
**Log for constant crash on logout:** [Status.log](https://github.com/status-im/status-react/files/2694098/Status.log)

Reported to crash repo.

### PR DESCRIPTION
**Pull request by rasom**
fix #7139

The error was caused by the crash on `status-go` side, which happened when RPC calls were executed without running node. 

It first appeared during #6886, [this comment](https://github.com/status-im/status-react/pull/6886#issuecomment-446328428). The reason why this crash happened at `#6886` is that user were allowed to log out from the account before `Statusgo.Login` callback, which caused a race condition when some RPC calls were sent right before stopping the node, that caused the panic (btw it wasn't 100% reproducible, depended on the number of chats in the account and some randomness). When `logout` button became disabled until `Statusgo.Login` callback the crash stopped to be reproducible in #6886.

Then, most likely, it became an issue again after #7032. After this PR the node with dummy configs is not started anymore (and most likely it received most of "late" RPC calls before this change) after logging out and some of RPC calls (like removing shh filters) can be executed after `Statusgo.StopNode` call. It wasn't 100% reproducible on all devices/accounts, but chances to get that crash were higher if account contained more chats (most likely because having N chats means removing N filters on logging out). It was also close to 100% reproducible on the desktop, not sure why. 

Implementation:
1. The first suggestion was to `StopNode` only after all [`.stopWatching`](https://github.com/status-im/status-react/blob/56817e1cabd7c8657eec36f6f0c96e12ed0c485a/src/status_im/transport/filters.cljs#L12) calls are done, but this only lowered probability of the crash, but didn't fix the issue.
2. Another suggestion was to prevent RPC calls after `StopNode` call, but it also only lowered probability of the crash.
3. So the last resort was [a fix on status-go side](https://github.com/status-im/status-go/pull/1329), and it actually worked.

status: ready

### CODE REVIEW

**Comment by churik** [comment]
Still reproducible on build #4.
Steps for me:
- login \ logout with existing account (logs were enabled) -> crash
[Status 14.56.57.log](https://github.com/status-im/status-react/files/2695095/Status.14.56.57.log)
- Log in -> disable logs -> crash 
[Status.log](https://github.com/status-im/status-react/files/2695100/Status.log)

**Comment by churik** [comment]
Oh, nice! tell me when this one can be retested

**Comment by rasom** [comment]
@churik please test it now

**Comment by churik** [comment]
@rasom I can say for sure that crash is not reproducible anymore. Will test more thoroughly tomorrow morning, so feel free to move it to "To Test"
Thank you for finding the reason and communicating with go-team to make this fix. For now I'll launch autotests

**Review by mandrigin — APPROVED** [review]

File: src/status_im/transport/filters.cljs [hunk 1]
```diff
@@ -72,7 +74,10 @@
...
- (fn [filters]
+ (fn [[filters callback]]
    (doseq [[chat-id filter] filters]
-     (when filter (remove-filter! {:chat-id chat-id
-                                   :filter filter})))))
+     (when filter (remove-filter!
+                   {:chat-id          chat-id
+                    :filter           filter
+                    :success-callback false})))
+   (callback)))
```
Comment (pedropombeiro) [inline src/status_im/transport/filters.cljs:83]: @rasom isn't there the possibility that `callback` is called too early here? Wouldn't it be more correct to pass a function to `.stopWatching` that would do a countdown of the callbacks remaining?

Comment (rasom) [reply src/status_im/transport/filters.cljs:83]: yep, that's most likely the case

**Comment by churik** [comment]
also fixes https://github.com/status-im/status-react/issues/7101 (needed branch from status-go is included to this commit) and https://github.com/status-im/status-react/issues/7115 (is not reproducible anymore on PR build)

File: src/status_im/transport/filters.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/transport/filters.cljs:83]: i would polish this in a separate PR as it most likely wouldn't fix the current issue because of the queue of polling requests which still can cause RPC call after `StopNode`, just because we have too many requests when account contains, let's say, 100 chats.  On the other hand, it can make logging out much slower on android devices, for instance, so better to work on it separately.

**Comment by churik** [comment]
Tested on Mac OSx, Windows:
- create account
- recover account
- log out (quick)
- log out while offline
- disable\enable logging
- switching mailservers

Tested on IOS:
- create account
- recover account
- log out (quick)
- log out while offline
- changing fleet
- switching on bootnodes
- adding and switching to custom mailserver
- changing network
- changing logging level
- switching mailservers

OK to merge from me.

**Comment by rasom** [comment]
@cammellos @siphiuel @yenda @PombeirP still need one more approval

**Review by pedropombeiro — APPROVED** [review]
lgtm as we're going to fix the callback issue in a future PR

**Comment by adambabik** [comment]
Please wait a bit. There is a problem. I accidentally merged develop to 0.17 branch and it contains all new updates. However, as it looks fine, I would keep it. 

We should just update `STATUS_GO_VERSION` to `0.19.x` (can provide a new build very soon).

**Comment by pedropombeiro** [comment]
@adambabik develop contains a signature change to `NotifyUsers` so we should avoid merging that before https://github.com/status-im/status-react/pull/6893 is merged

**Comment by cammellos** [comment]
@adambabik unless push notifications pull request had been merged  https://github.com/status-im/status-react/pull/6893 , current HEAD of develop in status-go is not compatible (`NotifyUsers` changed public interface), so probably won't work

**Comment by rasom** [comment]
@adambabik let's then have another build for `0.17.10-beta` with only one commit on top of `0.17.9-beta`

**Comment by adambabik** [comment]
I see, ok then let's wait for the next build.

**Comment by adambabik** [comment]
Let's use https://github.com/status-im/status-go/releases/tag/0.17.10-beta.1.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by Serhy** [comment]
With the latest Android build (StatusIm-181220-045332-56817e-pr.apk - 7th build in Jenkins) I've got app crash when login out (Bootnode enable/disable and changing loglevel second time while trying to reproduce)
Last 50 lines in geth.log before crash happened:

[gethBootNodeSwitchOnOff.log](https://github.com/status-im/status-react/files/2698577/geth20v2222222222222.log)

**Comment by rasom** [comment]
@Serhy can't see anything useful in that log... can you test the latest build?

**Comment by churik** [comment]
OK to merge from me (retested on IOS and Mac Os). 
Waiting for @Serhy check

**Comment by Serhy** [comment]
@rasom checking latest build now...

Meanwhile some more info: I was not able to reproduce with 3 NEW different accounts having 3 public chats each with message history with numerous times of loginout and relogins between three (logout via Bootnode switch On/Off, Network change, simple 'Log Out'). However once I recovered my own account with transaction histrory, i've got the app crash issue when network change. Keeping steps with logs here (Note: geth.log and logcat history is ~20 seconds before blank screen appeared after network change).


These were my last steps on Android 7 (confirmed on Android 6 before too)
1) Create new account UserA
2) Recover existing account with transaction history UserB
3) Relogin to UserA
4) Switch network to Rinkeby but do not log into UserA account
5) Login to UserB
6) Switch network to Rinkeby
7) Login to UserA. Log out.
8) Login to UserB and switch network to Ropsten right after login. 

[LogCat.txt](https://github.com/status-im/status-react/files/2698742/LogCatwhenswitchedtoRopstenFromRinkeby.txt)
[gethLogBeforeNetworkSwtich.log](https://github.com/status-im/status-react/files/2698743/gethBeforeNetworkSwtich.log)

**Comment by Serhy** [comment]
I've retested latest build (https://ci.status.im/job/status-react/job/prs/job/android/view/change-requests/job/PR-7144/9/artifact/StatusIm-181220-113527-b133e5-pr.apk), as well as the nightly develop and was able to reproduce there an app crash too. 
It's looking like as https://github.com/status-im/status-react/issues/6952 
`I have also experience blank screen, crashes and error displayed related to app-db being nil`
Same on my side, sometimes the next error appears:
screenshot 2018-12-20 at 16 11 00

Below are the logs from Android when above error appeared:

[geth_log_DEBUG.log](https://github.com/status-im/status-react/files/2699166/geth21.log)
[logcat_full_device_when_fx_defn_db_nil_after_logout.txt](https://github.com/status-im/status-react/files/2699179/logcat_full_device_when_fx_defn_db_nil.txt)

Above happened when I was trying to log out via Network change quick enought after login. 
Also I wasn't to catch this issues when login out via `Log Out` button (after it becomes active) - only with "forced" logout (network change/bootnodes change/logLevel update).

<blockquote></blockquote>

**Comment by rasom** [comment]
@Serhy most likely this happens because node is stopped before it actually finished startup, checking it now.

**Comment by rasom** [comment]
see dozens of
```
12-20 17:04:35.179 31165 31253 W ReactNativeJS: WARN [status-im.ui.screens.wallet.events:119] - Wrong decimals for token RDN at address 0x255aa6df07540cb5d3d297f0d0d4d84cb52bc8e6 - set to 18 but detected as 0
```
like warnings, and also 
```
12-20 17:05:00.089 31165 31253 E ReactNativeJS: ERROR [status-im.models.transactions:284] - failed to run transaction sync Error: Assert failed: Must have all necessary data to run background transaction sync
12-20 17:05:00.089 31165 31253 E ReactNativeJS: (and web3 account-address network network-status account app-state wallet chats)
```

**Comment by rasom** [comment]
@Serhy let's try it now. Advanced settings are hidden until the user is fully logged in.

**Comment by Serhy** [comment]
Latest builds tested on Android6, Android7, iOS, MacOS. Indeed i'm not able to reproduce it now!
So along with the Log out button (which is disabled until full login), - `Advanced options` are hidden. 
Once it's available, any activity requires account logout (Network change, Bootnode enabling/disabling, Fleet change, LogLevel change, account Log Out) does not crash the app and I was able to login and proceed using Status.

Loog good to me!

**Comment by Serhy** [comment]
Waiting for Windows build job to succeed...
