### PR TITLE
[#22029] fix: bridge button when there is single account

### LINKED ISSUE #22029: Bridge button does not navigate user to bridge flow if only one account is available
### Steps to reproduce:
1. Restore a user with one account.
2. Tap "Bridge" on the wallet main page.

### Actual result:
The user is not navigated to the Bridge Flow.

https://github.com/user-attachments/assets/be44ee2a-872a-4609-8185-b43e57c55c26

### Expected result:
The user should be properly navigated to the Bridge Flow after tapping "Bridge".

### Environment:
OS: iOS, Android

### Devices:
Pixel 7a (Android 13)
iPhone 11 Pro Max (iOS 17)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #22029

## Summary
The user should be properly navigated to the Bridge Flow after tapping "Bridge".

### Areas that may be impacted

- Bridge flow

## Steps to test
[comment]: #  (Specify exact steps to test if there are such)

1. Restore a user with one account.
2. Tap "Bridge" on the wallet main page.

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/events.cljs [hunk 1]
```diff
@@ -436,9 +436,10 @@
 (rf/reg-event-fx
  :wallet/start-bridge
  (fn [{:keys [db]}]
-   (let [view-id (:view-id db)]
+   (let [view-id (:view-id db)
```
Comment (vkjr) [inline src/status_im/contexts/wallet/events.cljs]: Could you please elaborate a bit what happens here? it is not quite clear why we use `or` between `view-id` and `address`

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/events.cljs]: @vkjr it starts bridge before when user was in accounts list, but in case there is only one account we just set that account and immediately start the the flow. so here i just added a check for either user in accounts list or already has a selected account.

Comment (vkjr) [reply src/status_im/contexts/wallet/events.cljs]: This looks logically incorrect. We should be doing `or` between similar entities. For example `(or :one-screen-id :another-screen-id). 

Also if event `start-bridge` was fired, the bridge flow should start. Instead we can check the conditions in the place where this event was triggered and not to call it if conditions aren't met.

When we put conditionals of this type inside the event we are tying our application flow code to the UI which can change and this is not good, we already can see that this makes changes more complicated :)

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/events.cljs]: @vkjr thanks for your feedback, I see your point. However, if you look at the conditions inside the implemented events, you’ll notice that they involve different entities, meaning they also serve as a safeguard.

For `start-bridge`, I agree, it makes sense that if the event is fired, the flow should start, so I’ve updated the code accordingly.

File: src/status_im/contexts/wallet/home/view.cljs [hunk 2]
```diff
@@ -94,9 +94,10 @@
                                  (rf/dispatch [:wallet/clean-send-data])
                                  (when-not multiple-accounts?
                                    (rf/dispatch [:wallet/switch-current-viewing-account
-                                                 first-account-address]))
-                                 (rf/dispatch [:wallet/start-bridge])
+                                                 first-account-address])
+                                   (rf/dispatch [:wallet/start-bridge]))
```
Comment (vkjr) [inline src/status_im/contexts/wallet/home/view.cljs:101]: Will bridge be started when there are multiple accounts? Looks like it was moved under `(when-not multiple-accounts?)` condition

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/home/view.cljs:101]: Yes @vkjr, when there are multiple accounts it will set trx type to bridge and navigate to select accounts screen, and after select account it will start the bridge.

Comment (vkjr) [reply src/status_im/contexts/wallet/home/view.cljs:101]: I see, thanks for the explanation!
Btw, what do you think about putting the info above as a comment to that code section? 
On recent sync we were discussing that a lot of information is in our heads and we can put more in the comments to make developer lives easier.
This piece of information seems to be just right for adding to the comment to help the next reader :)

**Review by vkjr — APPROVED** [review]

File: src/status_im/contexts/wallet/home/view.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/home/view.cljs:101]: Yes, makes sense. Here actually the conditions pretty much explain themselves, but I’ll check if we can add any more meaningful information.
thanks for your feedback

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/home/view.cljs:101]: added

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri thank you for PR. No issues from my side. PR is ready to be merged
