### PR TITLE
[#3946] Improved webview error rendering

### LINKED ISSUE #3946: Improve "oops, error" placeholder in Status browser
### Description
*Type*: Feature

*Summary*: The "oops, error" that appears when url could not be reached could be improved. Let's at least improve the text, center it and make it similar to other placeholders we have.   

#### Expected behavior

Let's use placeholder like: _Oops, this site can't be reached. Status could not found the server "wrongservername.com"_ and center it same way as it's done in other screens:

How Safari does it: 

### Reproduction
- Open Status
- Go to dapp browser (new chat, join public chat) and type a wrong url

### Additional Information
* Status version: nightly, April 20
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by jeluard**
fixes #3946

### Summary:

Improve webview error rendering. Note the data itself is incorrect (error code always -1). This will be addressed in another PR.

UPD: not always, same URL (http://j in my case) - shows error code -1 on Android and -1003 on IOS.

### Steps to test:
- Open Status
- Navigate an incorrect URL
- See the new error rendering

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/browser/styles.cljs [hunk 1]
```diff
@@ -42,9 +42,13 @@
    :justify-content :center})
 
 (def web-view-error
-  {:justify-content :center
-   :align-items     :center
-   :flex-direction  :row})
+  {:flex 1
```
Comment (flexsurfer) [inline src/status_im/ui/screens/browser/styles.cljs]: hm how did you make commit with wrong style?

**Review by flexsurfer — APPROVED** [review]

**Comment by jeluard** [comment]
@flexsurfer Map values alignments is not checked by style checker. Fixed now.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/VHdQMJ for branch PR-4302

<blockquote><div><strong><a href="https://i.diawi.com/VHdQMJ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/1bwC9c for branch PR-4302

<blockquote><div><strong><a href="https://i.diawi.com/1bwC9c">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by rasom — APPROVED** [review]
