### PR TITLE
Fix: slide button

### LINKED ISSUE #18894: [Bug] - Fix Slider button so that it can be enabled/renabled properly, adjust it's use on Wallet Create Account page
Currently if you use the Slider button and disable it, it will then not slide after being reenabled. 

On the Create Wallet Account Page it is mandatory the user inputs a name for a new account, thus the slide button should be disabled. Currently this is not possible, as the slider will not work properly then.

Note:
The slide button is used in many places, be sure to check those are not breaking too with this solution

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/18894

This PR fixes the `disabled?` prop for the slide button where the slide button wouldn't slide after changing `disabled?` from true to false

Parts affected: 
- Wallet account creation page. Demo below:

https://github.com/status-im/status-mobile/assets/29354102/78feb76f-ab34-4501-84bf-b918e358fcaf

### CODE REVIEW

File: src/quo/components/buttons/slide_button/view.cljs [hunk 1]
```diff
@@ -33,7 +32,8 @@
                  theme
                  type
                  blur?]}]
-      (let [x-pos             (reanimated/use-shared-value 0)
+      (let [gestures-disabled? (reagent/atom disabled?)
```
Comment (clauxx) [inline src/quo/components/buttons/slide_button/view.cljs]: I think reagent atoms should live outside the function in [Form 2 components](https://github.com/reagent-project/reagent/blob/master/doc/CreatingReagentComponents.md#form-2--a-function-returning-a-function). Maybe instead of moving the ratom inside the fn, the atom could be updated from a `use-effect` hook whenever the prop changes?

Comment (OmarBasem) [reply src/quo/components/buttons/slide_button/view.cljs]: You are right @clauxx, fixed!

**Review by clauxx — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
nice one @OmarBasem.

Minor detail, as you have this shown in the video attached but the description should mention that this affects the create account page and should be tested there 👍

**Review by ulisesmac — APPROVED** [review]
Looks good @OmarBasem !


Just one question, in the video, at the end, some schema errors are shown, are they related to this PR?

**Comment by OmarBasem** [comment]
> Looks good @OmarBasem !
> 
> Just one question, in the video, at the end, some schema errors are shown, are they related to this PR?

Nope not related. I will try to see where they come from and open an issue

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Thanks for your PR!
As @J-Son89 mentioned [here](https://github.com/status-im/status-mobile/issues/18894) : 

> it is mandatory the user inputs a name for a new account, thus the slide button should be disabled. 

I have an issue:

**ISSUE 1: Slide button on Create Account is enabled if user didn't enter account name**

**Steps:**
1) Install app
2) Go to Wallet
3) Try to create new Account
4) Do not change Account Name placeholder and slide 

**Actual result:** slide button is active

https://github.com/status-im/status-mobile/assets/147824399/f9224bff-c5e8-44bf-9a3b-cb8d33a15005


**Expected result:** slide button should be disabled

**Comment by OmarBasem** [comment]
@mariia-skrypnyk thanks for your testing! It should be working as expected now

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !
Can you please rebase your PR?

**Comment by OmarBasem** [comment]
> Hi @OmarBasem ! Can you please rebase your PR?

Done!

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !
New issue appeared on both platforms:

**ISSUE 2: User can not "slide" the slide button on Create Account screen**

**Steps:** 

1. Install app
2. Go to Wallet
3. Try to create new Account
4. Enter name
5. Try to slide "Slide to create account" button

**Actual result:** button is active but nothing happens when user tries to slide it
**Expected result:** button is active and user can slide it to finish account creation

**Comment by OmarBasem** [comment]
Thank you @mariia-skrypnyk for your testing and sorry for not noticing this. It is fixed now!

File: src/quo/components/buttons/slide_button/view.cljs [hunk 2]
```diff
@@ -14,10 +14,10 @@
     [react-native.reanimated :as reanimated]))
 
 (defn drag-gesture
-  [x-pos gestures-disabled? set-gestures-disabled disabled? track-width sliding-complete?
+  [x-pos disabled? track-width sliding-complete?
    set-sliding-complete
    on-complete reset-fn]
-  (let [gestures-enabled? (not (or disabled? gestures-disabled?))]
+  (let [gestures-enabled? (not disabled?)]
```
Comment (flexsurfer) [inline src/quo/components/buttons/slide_button/view.cljs]: let is not needed, just use `(not disabled?)` directly

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !
Failed e2e are not related to your PR.
Please, go ahead and merge!
