### PR TITLE
[#19176] fix: onboarding illustration design issue

### LINKED ISSUE #19176: Onboarding - Illustration issues
# Design Feedback 2.27

## [Onboarding] Sign in by Syncing screen
Figma frame of the review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=1%3A32044&mode=design&t=OeK3GHXzoVCNnZog-1)

- **Enable Notifications** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=1:32044&mode=design#727627393)] illustration has spacing issues on bigger screens, resulting in the illustration being too close to the screen margins

Screenshot 2024-03-11 alle 15 38 34

>
- **Welcome to Status** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35487&mode=design#726014345)] illustration is stretched on bigger screens

Screenshot 2024-03-11 alle 15 41 01

### Reproduction

1. Complete the Onboarding flow

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #19176

### Summary

- Enable Notifications [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=1:32044&mode=design#727627393)] illustration has spacing issues on bigger screens, resulting in the illustration being too close to the screen margins

- Welcome to Status [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35487&mode=design#726014345)] illustration is stretched on bigger screens

#### Areas that maybe impacted

- Onboarding

### Steps to test

- Complete the Onboarding flow

status: ready

### CODE REVIEW

File: src/status_im/contexts/onboarding/welcome/style.cljs [hunk 1]
```diff
@@ -8,10 +8,15 @@
...
 
 (defn page-illustration
-  [width]
-  {:width         width
-   :margin-top    12
-   :margin-bottom 4})
+  [{:keys [width height]}]
+  {:width  width
+   ;; Aspect ratio 2:3
+   :height (/ height 1.5)})
```
Comment (BalogunofAfrica) [inline src/status_im/contexts/onboarding/welcome/style.cljs]: Aspect ratio can be specified as a key in the styles

```suggestion
  {:width  width
   :aspect-ratio 1.5
   :height height})
```

Comment (mohsen-ghafouri) [reply src/status_im/contexts/onboarding/welcome/style.cljs]: thanks, resolved

**Review by BalogunofAfrica — APPROVED** [review]
LGTM

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa could you please check test result?

**Comment by VolodLytvynenko** [comment]
I have rerun failed tests

**Comment by VolodLytvynenko** [comment]
hi @mohsen-ghafouri Thank you for PR. e2e failures are not PR-related

**Comment by mohsen-ghafouri** [comment]
Hi @Francesca-G, could you please review this?

**Review by Francesca-G — APPROVED** [review]
