### PR TITLE
Unread indicator on community channel

### LINKED ISSUE #14906: No unread indicator on community channels
# Bug Report

## Problem 
Regression from https://github.com/status-im/status-mobile/pull/14799
No unread indicator is shown on channels inside community

#### Expected behavior
unread indicator is shown

#### Actual behavior

https://user-images.githubusercontent.com/4557972/214795870-527c24ea-a214-4d7f-9f8f-8a3f41af38f1.mp4

### Reproduction
**Prerequisites:** `User A` and `User B` are members of the same community 
1) User A: sends a message to the community channel while User B is on the messages home screen
2) User B: check unread indicator in community page

### Additional Information

- Status version: nightly 26/01/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by vkjr**
fixes #14906 

### Summary

Unread indicator added to channels with unread messages

Screenshot 2023-02-01 at 15 19 12

### Steps to test
**Prerequisites**: User A and User B are members of the same community

User A: sends a message to the community channel while User B is on the messages home screen
User B: check unread indicator in community page

status: ready

### CODE REVIEW

File: src/quo2/components/list_items/channel.cljs [hunk 1]
```diff
@@ -59,6 +61,10 @@
                 (not muted?)
                 (not (pos? (int mentions-count)))
                 unread-messages?)
-       [quo2.icons/icon :i/channel-notification
-        {:size     20
-         :no-color true}])]]])
+       [rn/view
+        {:style {:width            8
```
Comment (ilmotta) [inline src/quo2/components/list_items/channel.cljs]: Nothing major, but you could extract the styles to a new `style.cljs` namespace.

**Review by ilmotta — APPROVED** [review]
Always nice to the see accompanying unit tests so I don't have to guess and read char by char what the layer-3 sub is doing :wave:

File: src/quo2/components/list_items/channel.cljs (hunk 1 above)
Comment (vkjr) [reply src/quo2/components/list_items/channel.cljs]: Sure!

File: src/quo2/components/list_items/channel.cljs [hunk 2]
```diff
@@ -59,6 +62,5 @@
                 (not muted?)
                 (not (pos? (int mentions-count)))
                 unread-messages?)
-       [quo2.icons/icon :i/channel-notification
-        {:size     20
-         :no-color true}])]]])
+       [rn/view
```
Comment (J-Son89) [inline src/quo2/components/list_items/channel.cljs]: maybe it's better to make this a reusable component that can also be used in other components? 🤔 that is if we have this dot on other components?

File: src/status_im2/subs/communities.cljs [hunk 3]
```diff
@@ -219,18 +219,23 @@
...
                 category
                 #(vec (conj %1 %2))
-                {:name    name
-                 :emoji   emoji
-                 :locked? (or (not joined) (not can-post?))
-                 :id      id})))
+                {:name             name
+                 :emoji            emoji
+                 :unread-messages? (pos? unviewed-messages-count)
+                 :locked?          (or (not joined) (not can-post?))
```
Comment (J-Son89) [inline src/status_im2/subs/communities.cljs:237]: hmm, locked? is in reference to token-gating. Maybe we just change this to `false` and add a TODO with a github issue to immplement this with token gating? wdyt?

**Review by J-Son89 — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

File: src/status_im2/subs/communities.cljs (hunk 3 above)
Comment (vkjr) [reply src/status_im2/subs/communities.cljs:237]: `locked?` is for showing that small icon that informs that channel can't be open. And as far as I understand, it is not only about token gating. It is also locked when you did not join the community

Comment (J-Son89) [reply src/status_im2/subs/communities.cljs:237]: I think we should double check that with designers. I would assume you can not join any locked channel if you are not a member of a community.

Comment (J-Son89) [reply src/status_im2/subs/communities.cljs:237]: And it would be locked when you have not joined either way because the channel is locked by some token permissions. I could have it wrong however, but let's sync with designers on this

Comment (vkjr) [reply src/status_im2/subs/communities.cljs:237]: Yeah, good idea! will write this down to ask on a next syncup!

Comment (J-Son89) [reply src/status_im2/subs/communities.cljs:237]: Cool 🤙

File: src/quo2/components/list_items/channel.cljs (hunk 2 above)
Comment (vkjr) [reply src/quo2/components/list_items/channel.cljs]: Yes, we have it in `community_list_view.cljs`. I didn't create a separate component, but moved this style on the level of components and reused it in both places, wdyt?

Comment (J-Son89) [reply src/quo2/components/list_items/channel.cljs]: ah okay, it looks good actually. The only thing I would recommend is to put it in a named folder otherwise the file "src/quo2/components/style.cljs" will just become a plethora of random styles.

How about "src/quo2/components/common-styles/unread-grey-dot-style.cljs" or something like this

Comment (J-Son89) [reply src/quo2/components/list_items/channel.cljs]: alternatively put it in a "src/quo2/components/common/unread-grey-dot folder with a view and style and then the view can just be `[rn/view {:style components-style/unread-grey-dot}]`. Personally I think this is better 👍 I guess it's how it's being re used in community_list_view (and potentially other components)

Comment (vkjr) [reply src/quo2/components/list_items/channel.cljs]: Hm, for me, tbh, it seems more convenient to have a common style file exactly for the sake of collecting different unrelated styles that can be placed on the top level. In fact any of our `style` files is a collection of quite unrelated styles. But I don't mind grouping as you suggested either)

Comment (J-Son89) [reply src/quo2/components/list_items/channel.cljs]: Hmm, yeah I personally would be strongly against a file of random styles. It will just become a dumping group for random styles that have nothing to do with each other. Just my opinion ofc

**Comment by VolodLytvynenko** [comment]
Hi, @vkjr Thank you for PR. The unread badge is shown now

I am not sure if the defect below is in the scope of this PR. Let me know if it should be created separately as follow-up and merge it please if it so

**ISSUE 1: The unread indicator is shown instead of the count of unread mentions if a user is mentioned**

**Prerequisites:** 
1. User A and User B are members of the same community
2. User B sent one message in the community channel (this step is needed for the ability to create mentions)

**Steps to reproduce:**
User A: sends a message with mention of UserB to the community channel while User B is on the messages home screen
User B: check the count of unread mentions on a community page

**Actual result**
The unread indicator is shown
image

**Expected result**
count of unread mentions is shown instead of unread indicator if at least 1 mention is unread
image

**Comment by vkjr** [comment]
@VladimrLitvinenko, the counter just wasn't implemented yet, so I would suggest making it a scope for the next PR, that will be next one)

**Comment by J-Son89** [comment]
Counter component should be in quo2 library already.
It's in quo2/components/counter/counter.cljs

**Comment by vkjr** [comment]
@J-Son89, I know) I just prefer to have smaller separate PRs that are easier to review. Because even adding existing components means changing subscriptions and adding tests)

**Comment by J-Son89** [comment]
> @J-Son89, I know) I just prefer to have smaller separate PRs that are easier to review. Because even adding existing components means changing subscriptions and adding tests) 

Ok cool, I misinterpreted your last message. All good 👍.
Thanks for clarifying!

**Comment by VolodLytvynenko** [comment]
@vkjr created https://github.com/status-im/status-mobile/issues/14970 follow up about unread mentions separately. No issues from my side. Could you merge this PR, please?

**Comment by vkjr** [comment]
> Ok cool, I misinterpreted your last message. All good 👍. Thanks for clarifying!

Sorry, I phrased it incorrectly) I meant that displaying that component in a new community UI is not implemented yet)

p.s. made a grey dot a separate component)

**Comment by vkjr** [comment]
> @vkjr created #14970 follow up about unread mentions separately. No issues from my side. Could you merge this PR, please?

Thank you for creating an issue!
