### PR TITLE
bug #3877 - no longer possible to sign messages with empty password

### LINKED ISSUE #3877: Can sign transaction without entering password if it was entered previously and canceled
### Description

*Type*: Bug

*Summary*: User can sign transaction with empty password if password was entered previously but transaction was cancelled

#### Expected behavior
User must enter password if password field is empty. Button Sign Transaction should be not active if password field is empty. If user taps on inactive Sign Transaction then nothing should happen

#### Actual behavior
User can sign transaction when password field is empty. For this user needs to send transaction, enter password in the popup, cancel it and Sign transaction again
### Reproduction
You need to have some funds in the Wallet
- Open Status
- Open Wallet
- tap on Send Transaction
- as recipient select Recent recipients -> Jarrad
- as amount type 0
- tap Sign Transaction
- type valid password in the popup
- DO NOT tap on Sign transaction to continue, tap on Cancel
- tap Sign Transaction again
- Note that password field is empty. Tap on Sign Transaction
- Observe if transaction is sent (in my case it is because Transaction sent screen is shown). It's expected that transaction will not be sent as user didn't provide password when Signing transaction second time
https://app.testfairy.com/projects/4803590-status/builds/8112310/sessions/19/?accessToken=CMu2Ps5klJMfgvS7uhwqi6xLIzk

### Additional Information
* Status version: nightly build Apr 16
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8112310/sessions/19/?accessToken=CMu2Ps5klJMfgvS7uhwqi6xLIzk">TestFairy: Status 0.9.16 (2429) @19</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3877 

### Summary:

This PR clears the password when signing is cancelled. Also, Sign button is now disabled when 
password is empty (tapping it does nothing as opposed to giving "Wrong password" which was previously the case).

### Steps to test:
See #3877 

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by jeluard — APPROVED** [review]
Do we allow empty password during account creation?

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 1]
```diff
@@ -266,7 +266,8 @@
 (defn discard-transaction
   [{:keys [db]}]
   (let [{:keys [id]} (get-in db [:wallet :send-transaction])]
-    (merge {:db (update-in db [:wallet :send-transaction] merge clear-send-properties)}
+    (merge {:db (-> db  (update-in [:wallet :send-transaction] merge clear-send-properties)
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/events.cljs]: maybe better to add `:password` to `clear-send-properties` ?

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 2]
```diff
@@ -285,9 +286,10 @@
 (handlers/register-handler-fx
   :wallet/cancel-signing-modal
   (fn [{:keys [db]} _]
-    {:db (update-in db [:wallet :send-transaction] assoc
-                    :signing? false
-                    :wrong-password? false)}))
+    {:db (-> db (update-in [:wallet :send-transaction] assoc
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/events.cljs]: why don't just add `:password nil` to `assoc`?

**Review by flexsurfer — CHANGES_REQUESTED** [review]

**Comment by goranjovic** [comment]
@flexsurfer Gotcha

@jeluard  No

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]
