### PR TITLE
fix: non supported network warning is shown on the bridge flow

### LINKED ISSUE #20080: Caution about non supported network is shown on the bridge flow  when entering total assets amount on multiple networks
### Steps:
1. Recover user with available assets on at least 2 networks.
2. Go to bridge flow.
3. Select any network to bridge.
4. Enter an assets amount equal to the total assets on both networks.
5. Disable some built networks in FROM section if step 4 didn't help.

### Actual result:
The message "<token> is not available on the recipient receiver's desired networks" is shown

https://github.com/status-im/status-mobile/assets/52490791/1124b07e-11a7-4c95-b7d2-0c13133bc3b4

### Expected result:
- The message about not supported netwroks should not be shown.
- If a selected asset is not supported for some networks, then the network should be shown as disabled on the BRIDGE TO page.
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=10681-293746&t=lAeEb8aEH7xlNcXW-0
image

- If the entered amount is equal to the total assets on 2-3 networks, then the appropriate bridge should be built https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=10275-135653&t=lAeEb8aEH7xlNcXW-0
image

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #20080 

### Summary

This PR fixes warning about non supported networks being shown in the bridge flow, and disables unavailable networks for token in the `Bridge token to` screen.

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Recover user with available assets on at least 2 networks.
- Go to bridge flow.
- Select any network to bridge.
- Enter an assets amount equal to the total assets on both networks.
- Disable some built networks in FROM section if step 4 didn't help.
- Verify non supported network warning wasn't shown
- Verify unsupported token network are disabled in the Bridge to... screen

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/bridge/bridge_to/view.cljs [hunk 1]
```diff
@@ -8,27 +8,38 @@
...
+          fiat-formatted              (utils/get-standard-fiat-format crypto-value
+                                                                      currency-symbol
+                                                                      fiat-value)
+          token-networks              (network-utils/network-list token networks)
+          token-networks-ids          (mapv #(:chain-id %) token-networks)
+          token-networks-ids-set      (set token-networks-ids)
+          token-available-on-network? (contains? token-networks-ids-set chain-id)]
       [quo/network-list
-       {:label         (name network-name)
+       {:theme         theme
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: we don't need to pass theme this way. The provider does it. 

The problem in that component is the schema was not updated to remove it.

Comment (J-Son89) [reply src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: see: https://github.com/status-im/status-mobile/pull/20099/files

Comment (briansztamfater) [reply src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: Nice, the solely purpose of adding this change was to remove schema errors. I'll remove this and update the schema then

File: src/status_im/contexts/wallet/bridge/bridge_to/view.cljs [hunk 2]
```diff
@@ -8,27 +8,38 @@
...
+                                       {:currency currency
+                                        :balance  balance
+                                        :token    token})
+          fiat-formatted              (utils/get-standard-fiat-format crypto-value
+                                                                      currency-symbol
+                                                                      fiat-value)
+          token-networks              (network-utils/network-list token networks)
+          token-networks-ids          (mapv #(:chain-id %) token-networks)
+          token-networks-ids-set      (set token-networks-ids)
+          token-available-on-network? (contains? token-networks-ids-set chain-id)]
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: do you really need `token-networks`, `token-networks-ids`, `token-networks-ids-set`?

seems like this should all be done in the sub for `token-available-on-network?` ??

Comment (J-Son89) [reply src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: or at least a util for that 🤔

File: src/status_im/contexts/wallet/bridge/bridge_to/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: yep for sure, but just as an FYI passing theme as a prop will actually do nothing because the component gets it from the context provider.
you'll have to remove in the respective component test too 👍

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/bridge/bridge_to/view.cljs (hunk 2 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: imo the let binding should just include the minimal data needed by the view's props. Other data can be taken out to utils or subs

Also this can help with allowing us to write tests for the underlying logic that prepares the props

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 3]
```diff
@@ -226,9 +226,11 @@
...
             receiver-network-values                   (rf/sub
                                                        [:wallet/wallet-send-receiver-network-values])
-            token-not-supported-in-receiver-networks? (every? #(= (:type %) :not-available)
-                                                              (filter #(not= (:type %) :add)
-                                                                      receiver-network-values))
+            tx-type                                   (rf/sub [:wallet/wallet-send-tx-type])
+            token-not-supported-in-receiver-networks? (and (not= tx-type :tx/bridge)
+                                                           (every? #(= (:type %) :not-available)
+                                                                   (filter #(not= (:type %) :add)
+                                                                           receiver-network-values)))
```
Comment (BalogunofAfrica) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: I think that `every` and `filter` operation can be simplified with threading for readability. What do you think?

```cljs
 token-not-supported-in-receiver-networks? (and (not= tx-type :tx/bridge)
                                                (->> receiver-network-values
                                                     (remove #(= (:type %) :add))
                                                     (every? #(= (:type %) :not-available))))
```

Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: Thanks for the suggestion, updated!

File: src/status_im/contexts/wallet/bridge/bridge_to/view.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/bridge/bridge_to/view.cljs]: Yep, simplified the approach

**Review by OmarBasem — APPROVED** [review]

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hey @briansztamfater, thanks for the fix!
Could you take a look at the issue pls, I couldn't reproduce it in develop:

### ISSUE 1: Cursor disappears from the amount field when you start typing

It appears again if you set the focus on the field by tapping it

**Steps:**
1. Go to `Bridge` 
2. Start typing in the amount field
3. Pay attention to the cursor 

**Actual result (PR):**

https://github.com/status-im/status-mobile/assets/67952253/48a33a25-a0ac-4779-b085-096557c94a32

**Expected result (nightly):**


https://github.com/status-im/status-mobile/assets/67952253/91306e9e-aff8-48fe-8fd7-a4138dc862e1

**Comment by briansztamfater** [comment]
Hey @qoqobolo thanks for testing! Does that only happens on Android or also on iOS?

**Comment by ulisesmac** [comment]
> Hey @qoqobolo thanks for testing! Does that only happens on Android or also on iOS?

@briansztamfater Should we open an issue instead? seems this input has been changed and now is having problems

**Comment by briansztamfater** [comment]
Actually, I was able to reproduce it on develop on iOS Simulator. I think this was introduced after merging #20099. Can you please check @qoqobolo?

If it a new issue, yes, we should log it and work on it separately @ulisesmac cc @J-Son89

**Comment by qoqobolo** [comment]
> Actually, I was able to reproduce it on develop on iOS Simulator. I think this was introduced after merging #20099. Can you please check @qoqobolo?
> 
> If it a new issue, yes, we should log it and work on it separately @ulisesmac cc @J-Son89

@briansztamfater yep, I can see this issue now on today's nightly, will log it separately. 
Thanks for the fix, PR can be merged.
