### PR TITLE
fix React has detected a change in the order of Hooks

### LINKED ISSUE #22388: React has detected a change in the order of Hooks
# Bug Report

## Problem 

In the PR:
- https://github.com/status-im/status-mobile/pull/22346

we replaced re-frame subscriptions in favor of React context to handle screen parameters. The replacement can't be done directly since React Hooks have [some rules](https://react.dev/reference/rules/rules-of-hooks), while re-frame subscriptions are a lot more flexible.

The following exception is thrown due to this replacement:
```
 ERROR  Warning: React has detected a change in the order of Hooks called by status_im.contexts.wallet.add_account.create_account.new_keypair.confirm_backup.view.view. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://react.dev/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useRef                     useRef
3. useEffect                  useEffect
4. useContext                 useEffect
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in status_im.contexts.wallet.add_account.create_account.new_keypair.confirm_backup.view.view
    in RCTView (created by View)
    in View (created by quo.context.provider)
    in quo.context.provider
    in reagent19 (created by gestureHandlerRootHOC(reagent19))
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by gestureHandlerRootHOC(reagent19))
    in gestureHandlerRootHOC(reagent19) (created by WrappedComponent)
    in WrappedComponent
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in confirm-backup-on-shell(RootComponent)
```

#### Expected behavior

Not throwing any exception, perform the replacement carefully considering the previous subscription usage

#### Actual behavior

Throwing an exception, React relies a lot on the hook call order, so this may lead to unexpected results.

### Reproduction

Mount the screen `confirm-backup.view` in any of its flows (or navigating through a REPL).
Besides the reported incidence, we must make sure it doesn't happen in another view.

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/22388

### Testing Note:

This is a small refactoring, so it shouldn't have broken anything, but please conduct a light test on the following:
- Opening and closing of the lightbox (image viewer) in chat
- The 'Introduce Yourself' prompt for new accounts is working as expected, including the ability to update the name."
- Community members list is opening correctly
- Wallet - add address to watch
- Confirm seed phrase backup screen is working as expected

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs [hunk 1]
```diff
@@ -118,23 +118,23 @@
...
   []
-  (let [random-indices         (random-selection)
-        quiz-index             (reagent/atom 0)
-        incorrect-count        (reagent/atom 0)
-        show-error?            (reagent/atom false)
-        {:keys [on-success
-                on-try-again
-                masked-seed-phrase
-                back-button?
-                theme shell?]} (quo.context/use-screen-params)
```
Comment (Parveshdhull) [inline src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs:129]: Thank you, @ulisesmac, for reporting this issue. For some reason, only this use case was triggering a warning. However, as a precautionary measure, I have migrated all other uses as well.

**Comment by ulisesmac** [comment]
@Parveshdhull Thanks for fixing it, probably it was the only one because only there we used it along with other hooks.

**Review by ulisesmac — APPROVED** [review]

File: src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs [hunk 2]
```diff
@@ -118,23 +118,23 @@
...
       (rn/use-mount
        (fn []
          (native-module/get-random-mnemonic #(reset! random-phrase (string/split % #"\s")))))
       (when-not (empty? @random-phrase)
-        (let [current-word-index            (get random-indices
+        (let [{:keys [on-success
+                      on-try-again
+                      masked-seed-phrase
+                      back-button?
+                      theme shell?]}        (quo.context/use-screen-params)
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs]: @Parveshdhull isn't conditional usage of hooks discouraged by React? Won't this generate a warning? I find very confusing to see the usage of form-2 Reagent components to manage state mixed with hooks, but I imagine you didn't want to refactor intentionally to not increase the scope of the PR?

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs]: Thank you @ilmotta, fixed.

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull ! ☺️

Thanks for keeping eye on such updates!

Tested both platforms slightly and triggered full cycle of test.
No fails by PR's fault.

**Checked:**

🙌Opening and closing of the lightbox (image viewer) in chat
🙌**The 'Introduce Yourself' prompt for new accounts is working as expected, including the ability to update the name.**
🙌**Community members list is opening correctly**
🌨️ **Wallet - add address to watch** - had no chance to check as this feature is disabled for now but will keep in mind for future
🙌**Confirm seed phrase backup screen is working as expected**

PR can be merged! 🥳
