### PR TITLE
Fixed various wallet UI inconsistencies

### LINKED ISSUE #1801: UI issues in new Wallet on Transactions History tab
Issues:
1. Grey colour of the icons for incoming/outgoing transactions. Expected: as in design: green for incoming, blue for outgoing. Both Android and iOS.
2. No "phone icons" on iOS (carrier, time, battery percentage..)
3. Tab titles "Unsigned/History" are too small on iOS
4. Postponed/Pending sections are always empty now - remove them or check with design team how to show they are empty... Now there are 2 words on the screen where it's not clear they are Section titles. both Android and iOS
5. If pull down list of the transaction then no loading indicator is shown, on iOS
6. ">" icon on the right side of transaction is of different colour (not light grey but dark grey) and size. both Android and iOS
7. There is no line under tabs Unsigned/History with blue line under active tab. In the design there is such line. both Android and iOS
8. There should be no line between header with word Transaction and the rest of the screen

img_0582

Design (iOS):

screen shot 2017-09-09 at 15 50 30

Design (issues 7,8 - should be as in design below 2, 1)
screen shot 2017-09-09 at 15 58 01

real iOS device iPhone 7 plus
develop build 0.9.11d77

### PR DESCRIPTION
**Pull request by jeluard**
fixes #1801

### Steps to test:
- Open Status
- Navigate to wallet tab
- Make sure all UI glitches detailed in #1801 are fixed

status: ready

### CODE REVIEW

File: src/status_im/components/list/styles.cljs [hunk 1]
```diff
@@ -50,6 +56,7 @@
 
 (def section-header
   {:font-size       14
-   :margin-vertical 2
-   :margin-top      16
+   :color           styles/color-gray4
+   :margin-top      (if platform/ios? 10 11)
```
Comment (rasom) [inline src/status_im/components/list/styles.cljs]: can't we use `defstyles` for this?

Comment (jeluard) [reply src/status_im/components/list/styles.cljs]: Done

**Review by rasom — APPROVED** [review]

**Comment by annadanchenko** [comment]
on build #5 of `Branch bug/#1801` same issue exists on same devices
