### PR TITLE
Fix syncing flow navigation and designs

### LINKED ISSUE #21765: Sync flow does not reflect simplified onboarding changes
# Bug Report

### Reproduction

1. On Device A, open the sync code screen.
2. On Device B, select Log In by syncing.
3. Scan the QR code from Device A.
4. Complete the sync process successfully and observe the final screens.

#### Expected behavior
After the **Syncing profile...** screen, the user should be redirected directly to the wallet page.

#### Actual behavior
After the **Syncing profile...** screen:
- A screen appears showing information about which devices are syncing.
- Additional steps appear prompting the user to enable notifications.

https://github.com/user-attachments/assets/41f1bc7d-247c-4bf1-ab5e-a9487620c1f0

### Additional Information
- **The Syncing profile... and Oops, something’s wrong! screens do not match the expected design.**

https://github.com/user-attachments/assets/7c933ae7-0c52-4284-ad1a-be14c4cf2a74

- Status version: nightly 05.12.24
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21765

### Video

https://github.com/user-attachments/assets/cff8674a-86a2-496f-9a5e-e09128796dd8

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
Based on your perceptions https://github.com/status-im/status-mobile/issues/21765#issuecomment-2565206328, it would be good to take the opportunity from this PR and issue to see if the biometrics screen should be re-added or not to the onboarding after syncing is complete. Maybe it was a mistake in Figma. I think we should show the biometrics step in order to be more consistent with what other apps do after initial account set-up, but we better hear from designers as well. Not a blocker for this PR 👍🏼

Thank you @Parveshdhull

**Comment by Parveshdhull** [comment]
Thank you @ilmotta

> but we better hear from designers as well

Added a comment/question in figma - https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY?node-id=15071-95173&m=dev#1081016843

**Comment by pavloburykh** [comment]
> Thank you @ilmotta
> 
> > but we better hear from designers as well
> 
> Added a comment/question in figma - https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY?node-id=15071-95173&m=dev#1081016843

Thank you @Parveshdhull! Alisher has replied in Figma:
`Thank you for noticing. I’ve restored the biometric flow.`

@Parveshdhull based on that, would you mind re-add biometric screen in this PR or you prefer to do it separately?

**Comment by Parveshdhull** [comment]
> @Parveshdhull based on that, would you mind re-add biometric screen in this PR or you prefer to do it separately?

Thank you very much @pavloburykh for taking the PR for testing. I will re-add the bio-metric screen in the same PR.

File: src/status_im/contexts/onboarding/syncing/progress/view.cljs [hunk 1]
```diff
@@ -43,30 +42,29 @@
 (defn try-again-button
   [profile-color logged-in?]
   [quo/bottom-actions
-   {:actions (if logged-in? :one-action :two-actions)
+   {:actions (if logged-in? :one-action :two-vertical-actions)
     :blur? true
-    :button-one-label (i18n/label :t/recovery-phrase)
-    :button-one-props {:type                :primary
+    :container-style {:height (when-not logged-in? 116)}
```
Comment (ulisesmac) [inline src/status_im/contexts/onboarding/syncing/progress/view.cljs:47]: Can we give a name to this 116? 
I'm wondering what does it mean, I guess it's a sum of different UI elements because it's a big number. I also wonder if it's considering how it looks on different platforms.

**Review by ulisesmac — APPROVED** [review]
Thank you for this PR @Parveshdhull !

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, @ilmotta

I was hoping that re-adding the biometric screen would only require a small change, but it seems that’s not the case.

- The `Syncing Complete` screen had a different navigation root, but since we removed it, the "Enable Biometric" screen now allows the user to navigate back to the syncing progress screen, which we don’t want. One possible solution is to use the `Enable Biometric` screen as a navigation root as well.

- However, according to Figma, we need to display the biometric screen before syncing is complete (which wasn’t the case prior to this PR).

To achieve this, I **had to make** several changes, which will require another review. I’ve created a [separate PR](https://github.com/status-im/status-mobile/pull/21890) for this
(PR is almost complete, I just need to polish the "try again" flow for syncing).

I will finish that PR once this one is merged. Pavlo, please go ahead with testing. Thank you!

File: src/status_im/contexts/onboarding/syncing/progress/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/contexts/onboarding/syncing/progress/view.cljs:47]: Thank you @ulisesmac for reviewing the PR. I have added a label here - https://github.com/status-im/status-mobile/pull/21890/files#diff-d6d12a107e3ffe116d992ea055af107e6b7c68f5f3084958999d739b01f15dfe

**Comment by pavloburykh** [comment]
@Parveshdhull thanks you! 

> However, according to Figma, we need to display the biometric screen before syncing is complete (which wasn’t the case prior to this PR).

I think we should better confirm with @xAlisher if this has been made intentionally. I have some doubts based on the fact, that in case of Sync fallback https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15644-50720&m=dev we still have another Enable biometric step. And this step does not make sense since we have already enable/disabled biometrics right after scanning QR code. So, we either need to remove Biometric step from Sync fallback flow or move Enable biometric step (in standard Sync flow) after syncing is complete screen like it was before.

**Comment by ilmotta** [comment]
@Parveshdhull I was also expecting the biometrics step to be the final step as we discussed in this PR, i.e. only after syncing is complete. Worth re-checking as @pavloburykh suggested.

**Comment by pavloburykh** [comment]
@Parveshdhull based on discussion with @xAlisher  biometric step has been moved after syncing is complete (as it was before) https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=16409-27876&m=dev

Please tell, if you still prefer to make those changes in separate PR or now it is okay to implement here. Sorry for initial confusion.

**Comment by Parveshdhull** [comment]
Thank you very much @pavloburykh for getting this resolved.

Let's handle this leftover in a separate PR. That PR introduces a few other changes and refactors that I want to keep.

**Comment by pavloburykh** [comment]
> Thank you very much @pavloburykh for getting this resolved.
> 
> Let's handle this leftover in a separate PR. That PR introduces a few other changes and refactors that I want to keep.

Thanks @Parveshdhull This PR is ready for merge.
