### PR TITLE
fix(wallet)_: token decimals in activities

### LINKED ISSUE #21728: Asset value displays as 0 in Activity Tab after sending transaction
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Send asset (in my case USDT with 26 value on L1)
2. Check balances in the activity tab

### Actual result:
The asset is shown with 0 value

https://github.com/user-attachments/assets/a98cc672-3a22-4c42-aafb-58840ed5f8d1

### Expected result:
The sent asset should display its correct value in the Activity tab, matching the amount sent.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs (9).zip](https://github.com/user-attachments/files/17976423/Status-debug-logs.9.zip)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21728

### Summary

This PR fixes asset values that are shown as 0 in wallet activities.

### Review notes

The issue happens only for tokens that are NOT 18 decimals such as USDT, USDC.e, WBTC, ACH, etc. 

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Perform an ERC20 token transfer / bridge / swap of tokens that are not 18 decimals
- Verify the value is shown as expected in the activity entry

status: ready

### CODE REVIEW

File: src/status_im/subs/wallet/activities.cljs [hunk 1]
```diff
@@ -19,20 +18,20 @@
...
 
 (defn- hex->amount
-  [hex-str]
-  (-> hex-str
-      hex->number
-      money/wei->ether
-      (money/with-precision precision)
-      str))
+  [hex-str token-symbol token-decimals]
+  (let [native-token? (= token-symbol "ETH")]
```
Comment (shivekkhurana) [inline src/status_im/subs/wallet/activities.cljs]: This hardcoded "ETH" should be a constant somewhere.

File: src/status_im/subs/wallet/activities.cljs [hunk 2]
```diff
@@ -85,29 +84,61 @@
...
+                                                       [:tokens-by-symbol symbol-out
+                                                        :decimals])
+                                 :amount       amount-out)))
 
       activity-constants/wallet-activity-type-bridge
       (assoc base-activity
              :tx-type    :bridge
-             :amount-out (get-token-amount token-out amount-out))
+             :amount-out (get-token-amount
+                          (assoc token-out
```
Comment (vkjr) [inline src/status_im/subs/wallet/activities.cljs]: This `assoc` code repeats 5 times in conjunction with `(get-token-amount)`, so we can move it inside the function. wdyt?

Comment (smohamedjavid) [reply src/status_im/subs/wallet/activities.cljs]: Yes, we need to prevent the DRY code 🙏 . I will clean up 👍

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM

File: src/status_im/subs/wallet/activities.cljs [hunk 3]
```diff
@@ -65,12 +64,25 @@
       {:type :address :address address})))
 
 (defn- process-base-activity
-  [{:keys [timestamp sender recipient token-in token-out chain-id-in chain-id-out activity-status]
+  [{:keys [timestamp sender recipient token-in token-out amount-in amount-out symbol-in symbol-out
```
Comment (vkjr) [inline src/status_im/subs/wallet/activities.cljs:67]: @smohamedjavid, I have a question regarding `activity` structure. Are there situations when `symbol-in` is different from `(:symbol token-in)`? Because it looks like redundancy if no.

**Review by vkjr — APPROVED** [review]

File: src/status_im/subs/wallet/activities.cljs (hunk 3 above)
Comment (smohamedjavid) [reply src/status_im/subs/wallet/activities.cljs:67]: No @vkjr - The `token-in` or `token-out` map will have only the `token-type`, `chain-id` and `address` (token address) keys. Not the symbol of the token.

Comment (vkjr) [reply src/status_im/subs/wallet/activities.cljs:67]: @smohamedjavid, thanks for clarification!

**Review by clauxx — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
@smohamedjavid  Thanks for youe PR.

Everything looks good, PR can be merged.
photo_2024-12-04_15-31-30
photo_2024-12-04_15-31-27
