### PR TITLE
[#19178] fix: jump card responsive

### LINKED ISSUE #19178: Shell - Jump To Cards on larger screens
# Design Feedback 2.27

## [Shell] Jump To Cards issues on larger screens
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=3%3A68309&mode=design&t=OeK3GHXzoVCNnZog-1)

- **Card width** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=3:68309&mode=design#711284823)] caused an aligment problem on bigger screens, because of fixed size of switcher cards. 
💡**Solution:** cards need to adapt to fill space [[new design](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=8993%3A7010&mode=design&t=aEFxmw4URRjpf9Di-1) provided]
- **Card placeholder** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35440&mode=design#726039149)] when there's no open Jump To tabs need to increase to fill width of device accordingly

Screenshot 2024-03-11 alle 16 00 59

### Reproduction

1. Open **Jump To** on a device larger than design

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #19178

### Summary

cards need to adapt to fill space

#### Areas that maybe impacted

- Shell

### Steps to test

- Open Jump To on a device larger than design

### Result

status: ready

### CODE REVIEW

File: src/status_im/contexts/shell/jump_to/components/switcher_cards/style.cljs [hunk 1]
```diff
@@ -1,6 +1,10 @@
 (ns status-im.contexts.shell.jump-to.components.switcher-cards.style
   (:require
-    [quo.foundations.colors :as colors]))
+    [quo.foundations.colors :as colors]
+    [react-native.core :as rn]))
+
+(def screen-width (:width (rn/get-window)))
+(def card-size (- (/ screen-width 2) 28))
```
Comment (Parveshdhull) [inline src/status_im/contexts/shell/jump_to/components/switcher_cards/style.cljs]: hi @mohsen-ghafouri, Thank you very much for fixing this issue. 

- Please can you elaborate this calculations?
- Also can we pass, screen-width or card-size in function itself. (I have seen some bugs where calling rn function for getting info like dimensions at start of app returned nil or wrong value)

Comment (mohsen-ghafouri) [reply src/status_im/contexts/shell/jump_to/components/switcher_cards/style.cljs]: Hi @Parveshdhull, I calculate the width by dividing the total width by 2 and subtracting the space from it, as the list has 2 columns.

At first, I used `width (rf/sub [:dimensions/window-width])` in the parent function, but I thought it an unnecessary dependency for the child component. If (rn/get-window) isn't consistently reliable, I'll opt to use `:dimensions/window-width` in the main function instead.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/shell/jump_to/components/switcher_cards/style.cljs]: but if the issue is only happens at start of app, here in shell should be safe, no?

Comment (Parveshdhull) [reply src/status_im/contexts/shell/jump_to/components/switcher_cards/style.cljs]: > subtracting the space from it

Please can you share figma screenshot which space. Sorry, I was having hard time finding 28 gap.

> 'll opt to use :dimensions/window-width in the main function instead.

you can use still use `(rn/get-window)` in the main function.

> but if the issue is only happens at start of app, here in shell should be safe

We are defining these using def, they will be called at the start of app.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/shell/jump_to/components/switcher_cards/style.cljs]: here is figma, there is 20px horizontal margin and 15px gap between cards, i found 28 almost match design. 
https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=8993-7010&mode=design&t=FTeaoJXs89VddmIu-0

okay let me use `(rn/get-window)` in parent func

Comment (mohsen-ghafouri) [reply src/status_im/contexts/shell/jump_to/components/switcher_cards/style.cljs]: @Parveshdhull could you please check again? i also made calculation more clear

File: src/status_im/contexts/shell/jump_to/components/switcher_cards/view.cljs [hunk 2]
```diff
@@ -294,32 +294,35 @@
 
 (defn card
   [{:keys [type] :as data}]
-  (cond
-    (= type shell.constants/empty-card) ; Placeholder
-    [empty-card]
+  (let [screen-width (:width (rn/get-window))
+        ;; 2 column, 20px horizontal margin, 15px gap
+        card-size    (rn/use-memo #(/ (- screen-width 55) 2) [screen-width])]
```
Comment (Parveshdhull) [inline src/status_im/contexts/shell/jump_to/components/switcher_cards/view.cljs]: to me here use of use-memo don't look much beneficial.
- This will be cached for all switcher cards
- This is not a big calculation, and switcher cards don't change that often.

**Review by Parveshdhull — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa could you please check tests result and if all good lets move it to design review step. thanks

**Comment by VolodLytvynenko** [comment]
Hello @mohsen-ghafouri !
The e2e results are reviewed, the failed tests are not related to the PR.

hi @Francesca-G could you please take a look at the current PR?

**Review by Francesca-G — APPROVED** [review]
✨ Nice job
