### PR TITLE
Signing with standard-auth (incl. keycard signing)

### LINKED ISSUE #21575: Keycard - Sign authorization requests
Sign authorization requests. For example sharing wallet addresses with community.

Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=409-58818&t=VFIzh8BRInCRKpP9-1

### LINKED ISSUE #21936: "java.lang.illegalArgumentException: 16 > 0" when signing ERC-20 bridge transaction with keycard
### Preconditions:
- User has some ERC-20 assets (e.g., DAI on Arbitrum).
- User has enough ETH to cover gas fees.

### Steps to reproduce:
1. Restore the wallet using a keycard.
2. Navigate to the bridge flow.
3. Attempt to bridge an ERC-20 asset.
4. Sign the transaction using the keycard.

### Actual result:
The app shows the error: "java.lang.illegalArgumentException:" and then crashes.

https://github.com/user-attachments/assets/50092868-9f9c-42c8-b8dc-9c114bb7e1eb

### Expected result:
The transaction should be signed successfully, and the app should not crash.

### Devices:
Pixel 7a (Android 13)
iPhone 11 Pro Max (iOS 17)

### Logs:
https://drive.google.com/file/d/1HKl9gvjuD3b3Kv9_QPmYyaKemzcafi1f/view?usp=sharing

### ENV:
nightly 15 Jan, 2025

### PR DESCRIPTION
**Pull request by clauxx**
fixes #21575
fixes #21936 

## Summary
Adding support for signing to `standard-auth` with the keycard keypair, keycard encryption key, biometrics and password. This allows to delegate the decision of how to sign and signing itself to standard-auth events, similar to how it is during authentication, at the cost of some refactoring. Additionally, added support for joining communities and editing shared addresses using the keycard.

Also, fixed #21936, but wasn't aware we had an issue for it. The cause was signing with the keycard in parallel (when there's more things to sign), which would appear mostly for bridge txs and joining communities with multiple accounts.

In sum, the changes included are:
1. Signing with `:standard-auth/authorize-and-sign`, so we don't have to use both `:on-complete` and `:on-auth-success` to handle keycard signing 
a. added schemas and tests
b. refactored places that used both `:on-complete` and `:on-auth-success` for the keycard (most changes are in the `create-account` namespace)
c. the changes should make it easy to add support for biometrics for keycard profiles in the future
2. Fix #21936 by signing with the keycard in sequence instead of in parallel by adding a macro (very strange that promesa doesn't have that built in :|)
3. Make standard-auth more flexible and less reliant on `standard-auth/slide-button`, so that we can use the events when needed:
a. resetting the slide-button "complete" state is now done in `quo/slide-button` instead, as it should be, since there's no cases when it shouldn't reset.
b. moved the "track-icon" logic into a sub, so that it can be used with `quo/slide-button` (or other purposes if needed)
4. added support for join community and edit shared addresses with community (with schemas and tests)
a. removed dead code for joining community without choosing shared addresses

## Review notes
There are quite a few changes here, mainly due to how coupled signing and handling of signatures was in many places.

> Additionally, this PR is not based on develop (for now) due to this PR (https://github.com/status-im/status-mobile/pull/22019), which required changes to the send/swap transaction flows. As a result, yesterday me and @vkjr got on a call and discussed how to minimize the conflicts and rebased my changes on top of his, since it would get merged quicker most likely (mostly affected send/swap only).

## Testing notes
This PR does a few changes on standard-auth, so the testing scope would be all types of authentication (biometric/password/keycard)

### Areas that may be impacted
1. Send/Swap
2. Login (with password/biometrics/keycard)
3. Create/Restore/Migrate keycard profile
4. Dapps signing
5. Create wallet account
6. Join community
7. Edit shared addresses with community (atm it's hidden behind a feature flag, but can be enabled from the settings and tested)

[comment]: # (Can be ready or wip)
status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
thanks @clauxx , tests are failed , could you take a look pls

File: src/quo/components/buttons/slide_button/view.cljs [hunk 1]
```diff
@@ -26,8 +26,9 @@
                              (reanimated/set-shared-value x-pos clamped-x)
                              (when (and reached-end? (not sliding-complete?))
                                (set-sliding-complete true)
+                               (js/setTimeout reset-fn 500)
```
Comment (flexsurfer) [inline src/quo/components/buttons/slide_button/view.cljs]: could you please elaborate

File: src/status_im/common/promesa/core.clj [hunk 2]
```diff
@@ -0,0 +1,15 @@
+(ns status-im.common.promesa.core
```
Comment (flexsurfer) [inline src/status_im/common/promesa/core.clj]: looks more like util?

File: src/status_im/contexts/keycard/effects.cljs [hunk 3]
```diff
@@ -70,16 +71,20 @@
        (promesa/then (keycard.utils/get-on-success args))
        (promesa/catch (keycard.utils/get-on-failure args)))))
 
-(rf/reg-fx :effects.keycard/sign-hashes
- (fn [{:keys [hashes pin path on-success] :as args}]
-   (-> (promesa/all
-        (for [hash-data hashes]
+(rf/reg-fx :effects.keycard/sign-messages
```
Comment (flexsurfer) [inline src/status_im/contexts/keycard/effects.cljs]: could you pls elaborate on why name was changed

File: src/status_im/contexts/keycard/sign/events.cljs [hunk 4]
```diff
@@ -2,24 +2,39 @@
...
-                  {:pin        keycard-pin
-                   :path       path
-                   :hashes     hashes
-                   :on-success (fn [signatures]
-                                 (rf/dispatch [:keycard/disconnect])
-                                 (when on-success (on-success signatures)))
-                   :on-failure on-failure}]))}]]]})))
+                 [:keycard/sign-messages
+                  {:pin           keycard-pin
+                   :messages-data (add-paths-to-signing-data db messages)
```
Comment (flexsurfer) [inline src/status_im/contexts/keycard/sign/events.cljs]: could you pls elaborate on why add-paths-to-signing-data was added

File: src/status_im/contexts/settings/wallet/events.cljs [hunk 5]
```diff
@@ -146,6 +146,7 @@
   {:fx [[:dispatch
          [:standard-auth/authorize-with-password
           {:blur?             true
+           :skip-biometric?   true
```
Comment (flexsurfer) [inline src/status_im/contexts/settings/wallet/events.cljs]: this a little bit confusing, it says with password but skip-biometric? true is needed

File: src/status_im/common/standard_authentication/utils.cljs [hunk 6]
```diff
@@ -0,0 +1,46 @@
+(ns status-im.common.standard-authentication.utils
+  (:require [clojure.string :as string]
+            [status-im.common.keychain.events :as keychain]))
+
+(defn keycard-pairing?
```
Comment (flexsurfer) [inline src/status_im/common/standard_authentication/utils.cljs]: yes we check if it's a keycard profile by pairing prop, but better to name this keycard-profile?

File: src/quo/components/buttons/slide_button/view.cljs (hunk 1 above)
Comment (clauxx) [reply src/quo/components/buttons/slide_button/view.cljs]: we used to do this timed out reset with the on-complete prop inside `standard-auth/slide-button`, but most usages of slide button were through standard-auth anyways and it tied us to using the standard-auth version of slide button. Now though we have places where authorization shouldn't happen when sliding is complete, but as a result of e.g. a signal triggered by sliding. This makes the standard-auth slide button a bit useless, so this move was to make it easier to use the quo slide button without losing the reset functionality.

File: src/status_im/common/standard_authentication/utils.cljs [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+                               (->> (:accounts kp)
+                                    (map :address)
+                                    set))]
+    (-> keypairs
+        vals
+        find-keycard-keypair
+        keypair-addresses
+        (contains? (string/lower-case address)))))
+
+(defn profile-keypair-on-keycard?
```
Comment (flexsurfer) [inline src/status_im/common/standard_authentication/utils.cljs]: if there is keycard-pairing means profile's keypair on keycard

File: src/status_im/contexts/keycard/effects.cljs (hunk 3 above)
Comment (clauxx) [reply src/status_im/contexts/keycard/effects.cljs]: it seemed more generic at the time, since I assumed we won't only sign hashes, but it seems like that's not case. Will revert.

EDIT:

NVM, i remembered the reason. `messages` here is a vector of maps e.g.:
```clj
{:message "test"
 :address "0x01"}
```

maybe you have a better name for it, but `hashes` no longer works IMO.

File: src/status_im/contexts/keycard/sign/events.cljs (hunk 4 above)
Comment (clauxx) [reply src/status_im/contexts/keycard/sign/events.cljs]: before this only signed using one address. To join communities, we should sign a message for each account, hence the paths.

File: src/status_im/contexts/settings/wallet/events.cljs (hunk 5 above)
Comment (clauxx) [reply src/status_im/contexts/settings/wallet/events.cljs]: Indeed, I think a better name would be `:hide-biometrics-button?`. WDYT?

File: src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs [hunk 8]
```diff
@@ -6,20 +6,44 @@
...
+        prepared-hash                 (rf/sub [:wallet-connect/prepared-hash])]
+    [rn/view {:style style/auth-container}
+     [standard-authentication/slide-button
+      {:sign-payload        [{:address address
+                              :message prepared-hash}]
+       :size                :size-48
+       :track-text          slide-button-text
+       :disabled?           (and (not prepared-hash) disabled?)
+       :customization-color customization-color
+       :on-auth-success     on-auth-success
```
Comment (flexsurfer) [inline src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs]: if we have sign-payload then there will be on-sign-success, so probably it should be just on-success ? without auth, so it will work for auth and sign

Comment (flexsurfer) [reply src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs]: idk actually , so just by adding `sign-payload` it's not just standard-authentication anymore, we now have signing mechanism inside standard-authentication, little bit confusing

Comment (flexsurfer) [reply src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs]: so probably it's better to have separate component wrapper, like signing/slide-button which will wrap standard-authentication/slide-button

Comment (clauxx) [reply src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs]: agreed, given that the slide button was stripped of logic, now it's easier to have two separate ones. Thanks!

File: src/status_im/common/standard_authentication/utils.cljs (hunk 7 above)
Comment (clauxx) [reply src/status_im/common/standard_authentication/utils.cljs]: wait, so how do we differentiate these two cases you mentioned in this [comment](https://github.com/status-im/status-mobile/pull/21785#discussion_r1878321726)?

If I understood correctly, the case where the "profile is keycard", the keypair is not stored on the keycard but on the device, so we get the password (encryption-key) from the keycard and sign with the keypair from the device. I assumed that this case would be when we have a `keycard-pairing`, but the profile keypair has no `keycards`.

Comment (flexsurfer) [reply src/status_im/common/standard_authentication/utils.cljs]: so there might be next options

1) profile - keycard (password on keycard, we get it with PIN from keycard) keycard-pairing? true
a)wallet default account is derived from keycard keypair
b)wallet account 2 is derived from new keypair on device

2) profile - NOT keycard (user enters password or we get it from biometric)  keycard-pairing? false
a)wallet default account is derived from keypair  on device
b)wallet account 2 is derived from new keypair on keycard

so when we want to sign something we need to check if wallet account is derived from keypair on keycard or on device, if its keycard we use auth (PIN) on keycard and sign on keycard, if its on device we need to get password, and here we need to check if it's keycard profile, if it is we need to auth (PIN) on keycard and then sign on device with password from keycard

File: src/status_im/contexts/keycard/effects.cljs (hunk 3 above)
Comment (flexsurfer) [reply src/status_im/contexts/keycard/effects.cljs]: when did this change? there used to be hashes?

File: src/status_im/common/standard_authentication/utils.cljs (hunk 7 above)
Comment (flexsurfer) [reply src/status_im/common/standard_authentication/utils.cljs]: so basically auth is returning password, but if keypair for address is on keycard there is no auth stage, we directly sign with the pin

File: src/status_im/common/standard_authentication/events.cljs [hunk 9]
```diff
@@ -1,93 +1,137 @@
...
-      (on-auth-success-callback))))
+(defn authorize-and-sign
+  [{:keys [db]} [{:keys [sign-payload on-sign-success on-sign-error] :as args}]]
+  (let [keypairs                            (get-in db [:wallet :keypairs])
+        keycard-pairing?                    (utils/keycard-pairing? db)
+        keycard-keypair?                    (->> sign-payload
+                                                 first
+                                                 :address
+                                                 (utils/keycard-address? keypairs))
+        keycard-signing?                    (and keycard-pairing? keycard-keypair?)
```
Comment (flexsurfer) [inline src/status_im/common/standard_authentication/events.cljs]: remove `(and keycard-pairing?`

File: src/status_im/contexts/keycard/effects.cljs (hunk 3 above)
Comment (flexsurfer) [reply src/status_im/contexts/keycard/effects.cljs]: lets rename to payload better

File: src/status_im/common/promesa/core.clj (hunk 2 above)
Comment (clauxx) [reply src/status_im/common/promesa/core.clj]: done

File: src/status_im/contexts/keycard/effects.cljs (hunk 3 above)
Comment (clauxx) [reply src/status_im/contexts/keycard/effects.cljs]: done

File: src/status_im/common/standard_authentication/utils.cljs (hunk 6 above)
Comment (clauxx) [reply src/status_im/common/standard_authentication/utils.cljs]: done

File: src/status_im/common/standard_authentication/utils.cljs (hunk 7 above)
Comment (clauxx) [reply src/status_im/common/standard_authentication/utils.cljs]: fixed the condition :+1:

File: src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs (hunk 8 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/wallet_connect/modals/common/footer/view.cljs]: added separate slide-auth and slide-sign components

File: src/status_im/common/standard_authentication/events.cljs (hunk 9 above)
Comment (clauxx) [reply src/status_im/common/standard_authentication/events.cljs]: done :+1:

**Comment by clauxx** [comment]
@flexsurfer addressed all your comments (most are in separate commits)

File: src/status_im/common/promesa/utils.clj [hunk 10]
```diff
@@ -1,4 +1,4 @@
-(ns status-im.common.promesa.core
+(ns status-im.common.promesa.utils
```
Comment (flexsurfer) [inline src/status_im/common/promesa/utils.clj]: this util looks more general, so it shouldn't  be under status-im, it could go into utils ns

File: src/status_im/common/standard_authentication/events.cljs [hunk 11]
```diff
@@ -77,7 +74,7 @@
 
 (defn authorize
   [{:keys [db]} [args]]
-  (let [keycard-pairing? (utils/keycard-pairing? db)
+  (let [keycard-pairing? (utils/keycard-profile? db)
```
Comment (flexsurfer) [inline src/status_im/common/standard_authentication/events.cljs]: keycard-pairing? should be changed as well

File: src/status_im/common/standard_authentication/events.cljs [hunk 12]
```diff
@@ -104,7 +101,7 @@
 
 (defn fallback-for-biometrics
   [{:keys [db]} [args]]
-  (let [keycard-pairing? (utils/keycard-pairing? db)]
+  (let [keycard-pairing? (utils/keycard-profile? db)]
```
Comment (flexsurfer) [inline src/status_im/common/standard_authentication/events.cljs]: keycard-pairing? should be changed as well

File: src/status_im/common/standard_authentication/slide_auth.cljs [hunk 13]
```diff
@@ -0,0 +1,35 @@
+(ns status-im.common.standard-authentication.slide-auth
+  (:require
+    [quo.core :as quo]
+    [quo.theme :as quo.theme]
+    [react-native.core :as rn]
+    [utils.re-frame :as rf]))
+
+(defn view
+  [{:keys [track-text customization-color auth-button-label on-auth-success on-auth-fail
```
Comment (flexsurfer) [inline src/status_im/common/standard_authentication/slide_auth.cljs]: here it also could be just on-success without auth because it's slide-auth

**Review by flexsurfer — APPROVED** [review]
thank you, left a few minor comments

**Comment by clauxx** [comment]
@flexsurfer I addressed these as well. 

Regarding QA, I think we should hold off from testing it till https://github.com/status-im/status-mobile/pull/22019 is merged, otherwise we'll have to do it twice since this PR is based off from it.

**Comment by flexsurfer** [comment]
> @flexsurfer I addressed these as well.
> 
> Regarding QA, I think we should hold off from testing it till #22019 is merged, otherwise we'll have to do it twice since this PR is based off from it.

thank you, that's up to you, but this PR should be tested anyway so i would keep qa label but move to the review for now

**Comment by churik** [comment]
Note to @status-im/mobile-qa : wait until https://github.com/status-im/status-mobile/pull/22019 is merged, start testing after that

**Comment by pavloburykh** [comment]
@clauxx thanks for the PR. 

https://github.com/status-im/status-mobile/pull/22019 has been already merged into develop. Could you please rebase current PR and resolve conflicts so we can start testing? Thanks.

**Comment by clauxx** [comment]
@pavloburykh rebased :+1: 

cc: @flexsurfer i added a [new commit](https://github.com/status-im/status-mobile/pull/22049/commits/523c2acac2623b09589ef2af16230c96eca3f467) which fixes joining communities, since it seems like it requires legacy signatures (where the v component is 27/28), while it's not needed anywhere else (usually v is 0 or 1). Otherwise, it would fail to verify the signatures and the join request would be stuck at "Joining".

**Comment by mariia-skrypnyk** [comment]
Hey @clauxx !

Thanks for your PR.

Observing now that there is no ability to sign transactions with a Keycard.
Please, look at details below:

## Issue 1: Empty error toast after try to sign swap/send/bridge/wc transaction by a Keycard user with imported key pair

**Steps:**

1. Create keycard user (Onbording -> Create user with an empty Keycard)
2. Import key pair with assets from Wallet -> Add Acount -> Import using recovery phrase
3. Go to Swap - > sign swap
4. Go to Send -> sign send
5. Go to Bridge -> sign bridge
6. Go to WC -> Connect with imported acc -> sign transaction

**Result:**

There is a red toast at the top of the screen.
No redirect to Activity tab.

👆 signing transactions WORKS if user is restored via Keycard and his key pair have assets BUT if we create a user with NO assets using empty Keycard and then import Account 2 with assets then Account 2 can not sign anything


Screenshot 2025-02-21 at 16 18 00

[Sign_logs.zip](https://github.com/user-attachments/files/18909443/Sign_logs.zip)
[WC_logs.zip](https://github.com/user-attachments/files/18912317/WC_logs.zip)

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 2: "Cannot read property 'h'" error displayed when setting up bio authentication

### Steps:
1. Login to the app without enabling bio authentication  
2. Open profile -> password
3. Set up bio authentication  

### Actual result:
"Cannot read property 'h'" error displayed when setting up bio authentication

https://github.com/user-attachments/assets/de254474-396a-4b20-bfc3-5770a5778e90

### Expected result:
No error is shown. bio authentication  is enabled


### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1fHPs94f-GbTmJI9PMDG97uEM-YUyhA5V/view?usp=drive_link

**Comment by Horupa-Olena** [comment]
## PR_ISSUE 3: Biometric authentication signing fails when joining a community

Biometric authentication signing does not work when trying to join a Status community.
Additionally, this issue is reproducible if a user initially had biometric authentication enabled and then switched to password authentication. In this case, signing also fails.

### Steps:

1. Log in to the app with biometric authentication enabled.
2. Try to join a community 
3. Leave this community
4. Try to join this community again

### Actual result:
Signing fails, and the request to join the community is not sent.

https://github.com/user-attachments/assets/8203e30d-5d84-469f-b0d8-fd7dce7171ff

### Expected result:
Signing is successful, and the request to join the community is sent.


### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 15
- iPhone SE, IOS 18

### Logs
From IOS, where sign was with password, after disabled bio aut: [logs (20).zip](https://github.com/user-attachments/files/18913112/logs.20.zip)
Logs from ANdroid with bio auth: 
[Status-debug-logs.zip](https://github.com/user-attachments/files/18913208/Status-debug-logs.zip)

**Comment by clauxx** [comment]
@VolodLytvynenko @mariia-skrypnyk @Horupa-Olena 

thanks for testing. I'm back from the sick leave and will look at the issues today

**Comment by pavloburykh** [comment]
> @VolodLytvynenko @mariia-skrypnyk @Horupa-Olena
> 
> thanks for testing. I'm back from the sick leave and will look at the issues today

Thank you @clauxx! Take your time. Currently the whole QA team is busy with release testing, so we will be able to get back to this PR after we done with release. As has been discussed with Icaro, we decided to include current PR in future 2.33.1 release.

**Comment by clauxx** [comment]
@pavloburykh thanks, let me know when you start testing it again. Fixed issues 1 and 2, but 3 I couldn't reproduce and can't see the error in the recording/logs.

**Comment by pavloburykh** [comment]
> @pavloburykh thanks, let me know when you start testing it again. Fixed issues 1 and 2, but 3 I couldn't reproduce and can't see the error in the recording/logs.

Thanks @clauxx! We are going to proceed with re-testing today.

**Comment by Horupa-Olena** [comment]
> ## PR_ISSUE 3: Biometric authentication signing fails when joining a community
> Biometric authentication signing does not work when trying to join a Status community. Additionally, this issue is reproducible if a user initially had biometric authentication enabled and then switched to password authentication. In this case, signing also fails.
> 
> ### Steps:
> 1. Log in to the app with biometric authentication enabled.
> 2. Try to join a community
> 3. Leave this community
> 4. Try to join this community again
> 
> ### Actual result:
> Signing fails, and the request to join the community is not sent.
> 
>  video_2025-02-21_19-20-08.mp4 
> ### Expected result:
> Signing is successful, and the request to join the community is sent.
> 
> ### OS:
> IOS, Android
> 
> ### Devices:
> * Pixel 7a, Android 15
> * iPhone SE, IOS 18
> 
> ### Logs
> From IOS, where sign was with password, after disabled bio aut: [logs (20).zip](https://github.com/user-attachments/files/18913112/logs.20.zip) Logs from ANdroid with bio auth: [Status-debug-logs.zip](https://github.com/user-attachments/files/18913208/Status-debug-logs.zip)

@clauxx Hi! Thanks for your fixes!
This issue occurs when I join (or am added to) a community, leave it, and then try to join again (update description also)
In cases where I join a community for the first time, the biometric signature works fine, and nothing freezes.

So please take another look at this issue. Thanks!

**Comment by VolodLytvynenko** [comment]
Hi @clauxx could you please take a look at one more issue? Unfortunately, I missed it in the previous build. Now, I have found the steps

## PR_ISSUE 4: 'continue' text missing on continue button when importing additional account via seed phrase

### Preconditions:
Set up manual input for signature for user

### Steps to reproduce:
1. Go to the wallet.
2. Start importing an additional account using a seed phrase.
3. Check the continue button within the "Signing with auth" overlay.
 
### Actual result:
The continue button is missing the 'continue' text
image

### Expected result:
The continue button is shown with the 'continue' text

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by mariia-skrypnyk** [comment]
Hey @clauxx !

My part of testing was a `Keycard scenarios` on iOS/Android such as:


1. Send/Swap/Bridge
2. Login
3. Create/Restore profile
4. Migrate/reset/backup keycard profile
5. dAps signing
6. Create wallet account
7. Join community

Everything works fine on my side.
Thanks!

**Comment by clauxx** [comment]
> > ## PR_ISSUE 3: Biometric authentication signing fails when joining a community
> > Biometric authentication signing does not work when trying to join a Status community. Additionally, this issue is reproducible if a user initially had biometric authentication enabled and then switched to password authentication. In this case, signing also fails.
> > ### Steps:
> > 
> > 1. Log in to the app with biometric authentication enabled.
> > 2. Try to join a community
> > 3. Leave this community
> > 4. Try to join this community again
> > 
> > ### Actual result:
> > Signing fails, and the request to join the community is not sent.
> > video_2025-02-21_19-20-08.mp4
> > ### Expected result:
> > Signing is successful, and the request to join the community is sent.
> > ### OS:
> > IOS, Android
> > ### Devices:
> > 
> > * Pixel 7a, Android 15
> > * iPhone SE, IOS 18
> > 
> > ### Logs
> > From IOS, where sign was with password, after disabled bio aut: [logs (20).zip](https://github.com/user-attachments/files/18913112/logs.20.zip) Logs from ANdroid with bio auth: [Status-debug-logs.zip](https://github.com/user-attachments/files/18913208/Status-debug-logs.zip)
> 
> @clauxx Hi! Thanks for your fixes! This issue occurs when I join (or am added to) a community, leave it, and then try to join again (update description also) In cases where I join a community for the first time, the biometric signature works fine, and nothing freezes.
> 
> So please take another look at this issue. Thanks!

@Horupa-Olena Sorry I still can't reproduce it. Can you send a recording of the process? but not a screen recording since the authentication is hidden there and I can't make out what's happening. @mariia-skrypnyk @VolodLytvynenko do you also experience this?

BTW, how many keypairs do you have? I see you're sharing 4 accounts. Are they all derived from the same keypair?

**Comment by clauxx** [comment]
@VolodLytvynenko fixed issue 4 in the last commit. Please have a look

**Comment by pavloburykh** [comment]
> @Horupa-Olena Sorry I still can't reproduce it. 

Cannot reproduce eather.

**Comment by pavloburykh** [comment]
@clauxx JFYI: we were unable to check edit shared accounts flows because of the existing issue https://github.com/status-im/status-mobile/issues/22257

I think it is fine, because editing shared accounts is feature flagged and not a priority for us now cc @ilmotta

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Will try to reproduce ISSUE 3.
Let you know.

**Comment by mariia-skrypnyk** [comment]
@clauxx sorry, can not see this issue on my side.

**Comment by clauxx** [comment]
@pavloburykh @ilmotta is it ok to merge it?

**Comment by pavloburykh** [comment]
> @pavloburykh @ilmotta is it ok to merge it?

I think we can merge it. We will explore Olena's issue separately and log it if it is valid.  cc @Horupa-Olena 

**What has been tested:** 

Singing by different methods (passwort/biometry/keycard) of the following actions:

1. Send/Swap/Bridge
2. Login 
3. Create/Restore
4. Migrate/reset/backup keycard profile
5. Dapps signing
6. Create wallet account
7. Join community
