### PR TITLE
Switcher and Bottom Tabs Animations and UI Performance Improvements

### LINKED ISSUE #13440: Switcher cover doesnt render corners
# Bug Report

## Problem 
The switcher cover doesn't render in the corners on large phones.

Screenshot_20220601-174150_Status PR

### Reproduction

1) Open Status version with switcher on a large phone
2) open switcher

### Additional Information

- Status version: PR
- Operating System: Android, iOS

### LINKED ISSUE #13452: Implement React Native Reanimated V2
_Research issue for the implementation of react-native-reanimated v2_

# Summary:
Currently we are only using reanimated v1 API's and only version is bumped in `package.json`. We should Implement and use React Native Reanimated v2, at-least for newer animations for redesign.

## Project Setup:
Configure project as per v2 [installation guidelines](https://docs.swmansion.com/react-native-reanimated/docs/2.1.x/installation#android) and import API's.

### Issue 1:
[useAnimatedStyle](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle) hook is one of the main element of reanimated v2. But when we use this hook like:
```
(reanimated/use-animated-style (fn [] #js {:width 100}))
```
It throws [error](https://github.com/software-mansion/react-native-reanimated/issues/1090):
```
Cannot convert undefined value to object
```
Screenshot:
Screenshot

this error is only shown in the older version, like `2.1.0`, `2.2.0`, etc. newer versions don't show errors due to [this](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/src/reanimated2/hook/useAnimatedStyle.ts#L412) check, but the app just crashes with these logs

```
06-05 01:21:19.812 12779 12779 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Tried to synchronously call function {G__75911} from a different thread.
06-05 01:21:19.812 12779 12779 F DEBUG   : 
06-05 01:21:19.812 12779 12779 F DEBUG   : Occurred in worklet location: /home/parvesh_monu/Desktop/ArchFiles/React/status-react/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (492:18)
06-05 01:21:19.812 12779 12779 F DEBUG   : 
06-05 01:21:19.812 12779 12779 F DEBUG   : Possible solutions are:
06-05 01:21:19.812 12779 12779 F DEBUG   : a) If you want to synchronously execute this method, mark it as a Worklet
06-05 01:21:19.812 12779 12779 F DEBUG   : b) If you want to execute this method on the JS thread, wrap it using runOnJS
06-05 01:21:19.812 12779 12779 F DEBUG   :   at void com.swmansion.reanimated.AndroidErrorHandler.raise(java.lang.String) (AndroidErrorHandler.java:6)
```

### Cause
This error occurs because `useAnimatedStyle` expects [worklet](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets) as an argument ([ref](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedStyle#updater-function)), while we are just passing a simple function.

While setting project we are also adding [react-native-reanimated/plugin](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin), which is supposed to convert the passed argument to `worklet` automatically ([ref](https://github.com/software-mansion/react-native-reanimated/blob/b4ee4ea9a1f246c461dd1819c6f3d48440a25756/plugin.js#L7)), which is not happening for us.

### Issue 2
There is also another way to create [worklet](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets) for reanimated v2. Using directives

```
function someWorklet(greeting) {
  'worklet';
  console.log("Hey I'm running on the UI thread");
}
```
This will also not work for clojure script, because even if I add "worklet" string, something like
```
(defn someWorklet [greeting]
    "worklet"
    (js/console.log "Hey I'm running on the UI thread"))
```
compiler will strip it out. It seems [react-native-reanimated/plugin](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin) is more tailored toward javascript syntax and not working in cljs.

There is also a babel [plugin](https://www.npmjs.com/package/babel-plugin-assign-directive) available for using directive in cljs, but unfortunately it don't work in shadow-cljs.

### Possible Solutions
1. One workaround can be to not rely on directive and the library can just provide a function to manually create worklets. Function is already there just not yet completely implemented ([ref](https://github.com/software-mansion/react-native-reanimated/issues/3131)). One drawback of this is we have to maintain fork branch for the implementation for now, because even if change gets merged in parent, we can't use that because after version `2.4.0`, latest versions of library needs gradlePluginVersion=4.2.2 and gradle 6.
2. Create or fix plugin so that directive also work for shadow-cljs. (?)

### Related Refs:
- [Original Issue](https://github.com/software-mansion/react-native-reanimated/issues/1090)
- [Stackoverflow Question](https://stackoverflow.com/questions/72500152/interop-how-to-use-javascript-directive-in-clojurescript)
- [Issue Comment](https://github.com/software-mansion/react-native-reanimated/issues/1090#issuecomment-1146681621)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-react/issues/13452
fixes https://github.com/status-im/status-react/issues/13440

### Summary

- Implemented Reanimated V2
- Migrated Switcher animations to Reanimated V2
- Added bottom tabs & Stacks Animations
- Improved bottom tabs, tab changing performance
- Polished android & IOS UI

### Testing
Please test PR for any regressions.
Also, PR includes a new source folder(js) for `worklets`, please let me know if this is creating an issue for the nightly build. (No need for retesting, just let me know if the nightly build is failing)

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
```
[2022-06-10T00:20:26.493Z] Error: Unable to resolve module `../js/worklet_factory.js` from `app/index.js`: 
[2022-06-10T00:20:26.493Z] 
[2022-06-10T00:20:26.493Z] None of these files exist:
[2022-06-10T00:20:26.493Z]   * js/worklet_factory.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```
Not sure why the file is not found on the Jenkins build, working great locally. 

**UPD**: fixed (nix configuration files needed to be updated)

File: src/status_im/switcher/switcher.cljs [hunk 1]
```diff
@@ -1,44 +1,64 @@
...
+           touchable-animated-style       (reanimated/apply-animations-to-style
+                                           {:transform [{:scale button-touchable-scale}]}
+                                           touchable-original-style)
+           close-button-animated-style    (reanimated/apply-animations-to-style
+                                           {:opacity close-button-opacity}
+                                           close-button-original-style)
+           switcher-button-animated-style (reanimated/apply-animations-to-style
+                                           {:opacity switcher-button-opacity}
+                                           switcher-button-original-style)]
+       (reagent/as-element
```
Comment (Parveshdhull) [inline src/status_im/switcher/switcher.cljs]: I liked the reagent's shorthand `[:f>` for creating [functional components](https://reactjs.org/docs/components-and-props.html#function-and-class-components), but for some reason it is not working, (only in android PR build) and giving runtime error `TypeError: Cannot read property 'indexOf' of null`. 
So using this `[:> (fn [] ... (reagent/as-element` method for now.

Not only for `[:f>`, if I use any non existing shorthand like `[:x>`, it still gives same error. But in local build if I use non existing shorthand it gives error, non matching tag used. So it looks like it is not understanding these shorthand's in android PR build.

Any thought, why that might be happening?

File: .clj-kondo/config.edn [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {:lint-as {status-im.utils.views/defview  clojure.core/defn
            status-im.utils.views/letsubs  clojure.core/let
-           reagent.core/with-let          clojkure.core/let
+           reagent.core/with-let          clojure.core/let
```
Comment (Parveshdhull) [inline .clj-kondo/config.edn:3]: typo?

**Comment by Parveshdhull** [comment]
I will work on polishing UI and animations in the same PR because merging in the current state feels a little broken. I will ping for testing and review later once PR will be ready.

**Comment by du82** [comment]
Any plans to speed the animations up? The one for the switcher is quite slow, which kinda removes the purpose of switching quickly between things

**Comment by Parveshdhull** [comment]
> Any plans to speed the animations up? The one for the switcher is quite slow, which kinda removes the purpose of switching quickly between things

Hi @du64, Thank you very much for the feedback and checking out the PR.

Currently, the switcher is still in the experimentation/development phase, and we don't have a clear picture of its performance with all switcher cards.
Once everything will be implemented, we will have better idea.
And then we can easily tweak animation duration(currently 300 ms) and can use whichever value gives best optimum experience. Thank you

File: src/status_im/switcher/switcher_container.cljs [hunk 3]
```diff
@@ -28,7 +28,5 @@
                     :num-columns               2
                     :key-fn                    str}]]))
 
-(defn container [view-id switcher-screen-radius toggle-switcher-screen]
-  [rn/view {:style (styles/switcher-screen-container
-                    view-id switcher-screen-radius)}
-   [switch-screen toggle-switcher-screen]])
+(defn tabs [toggle-switcher-screen]
```
Comment (flexsurfer) [inline src/status_im/switcher/switcher_container.cljs:31]: why tabs is needed , why not `switch-screen` directly?

File: src/status_im/switcher/cards/messaging_card.cljs [hunk 4]
```diff
@@ -7,7 +7,7 @@
             [status-im.switcher.cards.styles :as styles]))
 
 (defn on-press [id toggle-switcher-screen]
-  (toggle-switcher-screen)
+  (js/setTimeout toggle-switcher-screen 100)
```
Comment (flexsurfer) [inline src/status_im/switcher/cards/messaging_card.cljs:12]: could you add a comment pls

File: src/quo2/reanimated.cljs [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+    (->> (map string/capitalize (rest words))
+         (apply str (first words))
+         keyword)))
+
+(defn map-keys [f m]
+  (->> (map (fn [[k v]] [(f k) v]) m)
+       (into {})))
+
+;; Worklets
+(def worklet-factory (js/require "../js/worklet_factory.js"))
```
Comment (flexsurfer) [inline src/quo2/reanimated.cljs]: can it be in `:require` ? `["../js/worklet_factory.js" :as worklet-factory]`

Comment (flexsurfer) [reply src/quo2/reanimated.cljs]: btw why it's not inside src folder?

File: src/quo2/reanimated.cljs [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+;; so first convert kebab case styles into camel case styles
+(defn apply-animations-to-style [animations style]
+  (let [animations (map-keys kebab-case->camelCase animations)
+        style      (apply dissoc (map-keys kebab-case->camelCase style) (keys animations))]
+    (use-animated-style
+     (.applyAnimationsToStyle ^js worklet-factory (clj->js animations) (clj->js style)))))
+
+;; Animators
+(defn animate-shared-value-with-timing [anim val duration easing]
+  (set-shared-value anim (with-timing val (clj->js {:duration duration
```
Comment (flexsurfer) [inline src/quo2/reanimated.cljs]: clj->js is slow, probably better to use `(js-obj "foo" 1 "bar" 2)` here

File: src/quo2/reanimated.cljs [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+
+;; Worklets
+(def worklet-factory (js/require "../js/worklet_factory.js"))
+
+;;;; Component Animations
+
+;; kebab-case styles are not working for worklets
+;; so first convert kebab case styles into camel case styles
+(defn apply-animations-to-style [animations style]
+  (let [animations (map-keys kebab-case->camelCase animations)
```
Comment (flexsurfer) [inline src/quo2/reanimated.cljs:57]: could you elaborate why map-keys and kebab-case->camelCase

File: src/status_im/switcher/constants.cljs [hunk 8]
```diff
@@ -2,31 +2,51 @@
...
 
 ;; TODO(parvesh) - use different height for android and ios(Confirm from Design)
 (defn bottom-tabs-height []
   (if platform/android? 55 80))
 
-;; TODO - move to switcher/utils.cljs
 (defn dimensions []
   (<sub [:dimensions/window]))
+
+(def tabs '("communities" "chats" "wallet" "browser"))
```
Comment (flexsurfer) [inline src/status_im/switcher/constants.cljs]: why not vector ?

File: src/status_im/switcher/animation.cljs [hunk 9]
```diff
@@ -1,47 +1,67 @@
...
+                                    switcher-screen-bottom
+                                    (+ constants/switcher-container-height-padding
+                                       constants/switcher-height-offset)))
+
+
+;;;; Bottom Tabs & Home Stack Animations
+
+
+(defn bottom-tab-on-press [shared-values selected-tab-id]
+  (let [selected-tab (get (string/split (name selected-tab-id) #"-") 0)]
```
Comment (flexsurfer) [inline src/status_im/switcher/animation.cljs]: thats strange to do it each time on press, better to have a map ?

File: src/status_im/switcher/animation.cljs [hunk 10]
```diff
@@ -1,47 +1,67 @@
...
+    (doseq [tab constants/tabs]
+      (let [selected-tab?              (= tab selected-tab)
+            tab-opacity-shared-value   (get shared-values (keyword (str tab "-tab-opacity")))
```
Comment (flexsurfer) [inline src/status_im/switcher/animation.cljs]: same here

File: src/status_im/switcher/bottom_tabs.cljs [hunk 11]
```diff
@@ -1,30 +1,68 @@
...
+                                                shared-values
+                                                (keyword (str tab "-tab-opacity")))}
+                                     {})}
+            [icons/icon icon (styles/bottom-tab-icon :bottom-tabs-selected-tab)]]]
+          [rn/view {:style bottom-tab-original-style}
+           [icons/icon icon (styles/bottom-tab-icon :bottom-tabs-non-selected-tab)]]))))])
+
+(defn tabs [shared-values icons-only?]
+  [rn/view {:style (styles/bottom-tabs icons-only?)}
+   [bottom-tab :main-icons/redesign-communities "communities" icons-only? shared-values]
```
Comment (flexsurfer) [inline src/status_im/switcher/bottom_tabs.cljs]: why do you need string name ?

Comment (flexsurfer) [reply src/status_im/switcher/bottom_tabs.cljs]: why not keyword ?

File: src/status_im/switcher/bottom_tabs.cljs [hunk 12]
```diff
@@ -1,30 +1,68 @@
...
-  [rn/touchable-opacity {:style          {:padding 15}
-                         :active-opacity 1
-                         :on-press       #(bottom-tab-pressed tab-id)}
-   [icons/icon icon (styles/bottom-tab-icon
-                     (if (= tab-id @selected-tab-id)
-                       :bottom-tabs-selected-tab
-                       :bottom-tabs-non-selected-tab))]])
+(defn bottom-tab [icon tab icons-only? shared-values]
+  [:>
+   (fn []
```
Comment (flexsurfer) [inline src/status_im/switcher/bottom_tabs.cljs:41]: could you elaborate why `[:> (fn []`

File: src/status_im/switcher/home_stack.cljs [hunk 13]
```diff
@@ -0,0 +1,67 @@
...
+  [:<>
+   [stack-view :communities-stack shared-values (if platform/ios? 47 0)]
+   [stack-view :chats-stack shared-values (if platform/ios? 47 0)]
+   [stack-view :browser-stack shared-values 0]
+   [stack-view :wallet-stack shared-values 0]])
+
+(defn home []
+  [:>
+   (fn []
+     (let [selected-tab   (get (string/split (name @bottom-tabs/selected-tab-id) #"-") 0)
```
Comment (flexsurfer) [inline src/status_im/switcher/home_stack.cljs]: `string/split (name` doesn't look good , probably there is a better way

File: src/status_im/switcher/switcher.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/switcher/switcher.cljs]: could you provide an example ? 

also you could try to set
```
:static-fns true
:fn-invoke-direct true
```

Comment (Parveshdhull) [reply src/status_im/switcher/switcher.cljs]: > could you provide an example ?

```
(defn child-comp []
  [:f> (fn []
         [react/view])])
```

If I use above child comp inside any parent component, then the PR build app crashes at runtime with `TypeError: Cannot read property 'indexOf' of null`, but If I use

```
(defn child-comp []
  [:> (fn []
        (reagent/as-element
         [react/view]))])
```

Then it just works, not sure why first one is failing

> also you could try to set
> ```
> :static-fns true
> :fn-invoke-direct true
> ```

it is already there, https://github.com/status-im/status-react/blob/9f9b896eb7fcfac60d55b33a3744480b13d2ba8d/shadow-cljs.edn#L64

File: src/status_im/switcher/switcher_container.cljs (hunk 3 above)
Comment (Parveshdhull) [reply src/status_im/switcher/switcher_container.cljs:31]: Hi, currently we have only a switcher screen in the tab, that's why
  ```
  (defn tabs [toggle-switcher-screen]
    [switch-screen toggle-switcher-screen])
  ```
  But it is more like a placeholder for now, once the swipable tabs and other screens are implemented it will be something like
  ```
  (defn tabs [toggle-switcher-screen]
    [swipeable-tabs
      [switch-screen toggle-switcher-screen]
      [share-screen]
      [scan-center-screen]
      [activity-center-screen]])
  ```

File: src/quo2/reanimated.cljs (hunk 5 above)
Comment (Parveshdhull) [reply src/quo2/reanimated.cljs]: > can it be in :require ? ["../js/worklet_factory.js" :as worklet-factory]

js directive are not working with :require https://github.com/status-im/status-react/issues/13452#issuecomment-1150540973

> btw why it's not inside src folder?

moved to src

File: src/quo2/reanimated.cljs (hunk 7 above)
Comment (Parveshdhull) [reply src/quo2/reanimated.cljs:57]: Hi, I think kebab case only works with clojure due to reagent, but as worklets are inside js file which is directly processed by metro instead of shadow-cljs (due to js/require for directives) only camel case works there

File: src/status_im/switcher/bottom_tabs.cljs (hunk 11 above)
Comment (Parveshdhull) [reply src/status_im/switcher/bottom_tabs.cljs]: oh I missed this change, doing now

Comment (Parveshdhull) [reply src/status_im/switcher/bottom_tabs.cljs]: done

File: src/status_im/switcher/switcher.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/switcher/switcher.cljs]: i mean in :dev build. to see if its a reason

File: nix/mobile/android/release.nix [hunk 14]
```diff
@@ -52,7 +52,7 @@ in stdenv.mkDerivation rec {
       root = path;
       include = [
         "package.json" "yarn.lock" "metro.config.js"
-        "resources/.*" "translations/.*"
+        "resources/.*" "translations/.*" "src/js/.*" ".babelrc"
```
Comment (flexsurfer) [inline nix/mobile/android/release.nix]: but src should be included , no ?

File: src/mocks/js_dependencies.cljs [hunk 15]
```diff
@@ -308,7 +308,7 @@
     "react-native-share" react-native-share
     "@react-native-community/async-storage" async-storage
     "react-native-svg" react-native-svg
-    "../js/worklet_factory.js" worklet-factory
+    "../src/js/worklet_factory.js" worklet-factory
```
Comment (flexsurfer) [inline src/mocks/js_dependencies.cljs:311]: ./js/worklet_factory.js ?

File: src/quo2/reanimated.cljs [hunk 16]
```diff
@@ -47,7 +47,7 @@
        (into {})))
 
 ;; Worklets
-(def worklet-factory (js/require "../js/worklet_factory.js"))
+(def worklet-factory (js/require "../src/js/worklet_factory.js"))
```
Comment (flexsurfer) [inline src/quo2/reanimated.cljs:50]: ./js/worklet_factory.js ?

File: nix/mobile/android/release.nix (hunk 14 above)
Comment (jakubgs) [reply nix/mobile/android/release.nix]: No, it should not be necessary, since this is the Android Gradle build.
Are we sure this change shouldn't go to `nix/mobile/android/jsbundle/default.nix`?

Comment (Parveshdhull) [reply nix/mobile/android/release.nix]: Hi, @jakubgs `jsbundle/default.nix` already has `"src/.*"` but android build still complains about file not found. It only works when added to 'release.nix`

File: src/quo2/reanimated.cljs (hunk 16 above)
Comment (Parveshdhull) [reply src/quo2/reanimated.cljs:50]: For some reason `js/require` is only working with `../src/js/worklet_factory.js`

"https://user-images.githubusercontent.com/17097240/175988135-909b2ee2-a4fe-4ad5-ae84-1aaf30bdc953.mp4"

> Github video player is unable to play this video, only playing locally

File: src/status_im/switcher/switcher.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/switcher/switcher.cljs]: **Fixed**: _Adding solution for reference_

CI build was using a different version of the reagent (0.10.0), than the dev build(1.0.0). And `:f>` is only available in `1.0.0+` versions.
`make nix-update-clojure` fixed the issue.

Thank you @flexsurfer and @Jakubgs

**Review by flexsurfer — APPROVED** [review]
great job!

File: nix/mobile/android/release.nix (hunk 14 above)
Comment (jakubgs) [reply nix/mobile/android/release.nix]: What file does it complain about exactly?

**Comment by qoqobolo** [comment]
Hey @Parveshdhull! Thanks for all this work you've done!

### ISSUE 1: The switcher button has become white in dark mode when active
Do we consider this a regression? Asking, since it works differently in the develop.

**Steps:**
1. Create an account
2. Enable New UI
3. Enable dark mode on your device
4. Reopen the app 
5. Open switcher

Screenshot 2022-06-28 at 10 28 07

**Comment by Parveshdhull** [comment]
Hi @qoqobolo, Thanks for testing the PR and finding the issue.
Issue should be fixed now.

File: nix/mobile/android/release.nix (hunk 14 above)
Comment (Parveshdhull) [reply nix/mobile/android/release.nix]: So for using JavaScript Directives for creating [reanimated worklets](https://stackoverflow.com/questions/72500152/how-to-use-reanimated-worklet-directive-in-clojurescript/72513996) in the clojure project, I needed to use the js file.

For that, I created a new file `src/js/worklet-factory.js`. But when the android app is built it complains that this [file is not found](https://github.com/status-im/status-react/pull/13470#issuecomment-1151745897). 

This file is in the `"src/.*"` directory which we bundle in `nix/mobile/android/jsbundle/default.nix`, still it complains. Maybe because of how it is [imported](https://github.com/status-im/status-react/pull/13470#discussion_r907148059), this file acts more like a separate module.

**Comment by qoqobolo** [comment]
@Parveshdhull thanks, PR can be merged

File: nix/mobile/android/release.nix (hunk 14 above)
Comment (jakubgs) [reply nix/mobile/android/release.nix]: Then if only `src/js/worklet-factory.js` is necessary, why are you adding all of `src`?

**Review by jakubgs — APPROVED** [review]
