### PR TITLE
Wallet/#11570 non archival node

### LINKED ISSUE #11570: Make sure wallet history and transfers watching works with a custom RPC node
# Bug Report

## Problem

Currently when a custom RPC node is set historical data can't be fetched and that makes wallet's history unusable. Also in case if a new tx is sent we don't watch for confirmation.

#### Expected behavior

[comment]: # (Describe what you expected to happen. Please include designs if possible.)
We should give a user an option to keep using our own infura RPC for historical transfers or (if that's a privacy concern for the user) to use a custom RPC only for recent history and for watching new transfers. 

#### Actual behavior

[comment]: # (Describe what actually happened. Please include screenshots if possible.)
As history can't be fetched (unless the user provides an archival node, which is unlikely) and error is shown and new transactions are not watched properly.

### PR DESCRIPTION
**Pull request by rasom**
fix #11570

### CODE REVIEW

File: src/status_im/ethereum/core.cljs [hunk 1]
```diff
@@ -93,6 +93,9 @@
 (defn network->chain-keyword [network]
   (chain-id->chain-keyword (network->chain-id network)))
 
+(defn custom-rpc-node? [{:keys [id]}]
+  (= 45 (count id)))
```
Comment (rasom) [inline src/status_im/ethereum/core.cljs]: Probably there is a better way to say that the node is custom. Otherwise magic value should be extracted.

File: src/status_im/subs.cljs [hunk 2]
```diff
@@ -898,8 +905,8 @@
  :<- [:multiaccount]
  (fn [[contacts multiaccount] [_ id identicon]]
    (let [contact (or (get contacts id)
-                     (when (= id (:public-key multiaccount)
```
Comment (rasom) [inline src/status_im/subs.cljs:916]: Unrelated to PR but cljfmt did not allow me to create a new commit with this code.

File: src/status_im/ui/screens/wallet/account/views.cljs [hunk 3]
```diff
@@ -214,7 +214,7 @@
 
 (views/defview account []
   (views/letsubs [{:keys [name address] :as account} [:multiaccount/current-account]
-                  fetching-error [:wallet/fetching-error]]
+                  fetching-error          [:wallet/fetching-error]]
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/account/views.cljs]: To be reverted

File: src/status_im/ui/screens/wallet/transactions/views.cljs [hunk 4]
```diff
@@ -106,15 +106,44 @@
        {:style {:color colors/blue}}
        (i18n/label :t/check-on-etherscan)]]]))
 
+(defn custom-node []
+  [react/view
+   {:style {:flex             1
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/transactions/views.cljs]: map values alignment

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/wallet/transactions/views.cljs (hunk 4 above)
Comment (rasom) [reply src/status_im/ui/screens/wallet/transactions/views.cljs]: fixed
