### PR TITLE
show button background on scroll

### LINKED ISSUE #16181: Wrong background around "Continue" button on Create Profile screen (design review)
Change the background according to design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428189441))
Figma Notes:
This background is wrong:
Only has to appear when button covers top content (colours)
It's too dark, check design here: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=6345%3A327366&t=azdmhomknDfXwYtl-1

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by jo-mut**
fixes #16181

Navigate to Create Profile screen
Blur background is applied should the keyboard overlap the color-picker

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]
Looks good to me.

**Comment by VolodLytvynenko** [comment]
Hi @jo-mut unfortunatly one issue if found:
## ISSUE 1: Background blur not applied when keyboard overlaps color picker

### Actual result:
- Real device: iPhone SE
image

- Real device: Huawei p20 light
image

### Expected result:
image

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=6345-327102&mode=design&t=OGysN5b1vfOllcI9-0

### Devices:
- Real device:  iPhone SE
- Real device: Huawei p20 light, android 9
- Android studio device: Pixel XL API 29

File: src/status_im2/contexts/onboarding/create_profile/view.cljs [hunk 1]
```diff
@@ -48,19 +49,34 @@
     :else                        nil))
 
 (defn button-container
-  [keyboard-shown? children]
+  [keyboard-shown? background? children]
   [rn/view {:style {:margin-top :auto}}
    (if keyboard-shown?
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/create_profile/view.cljs]: perhaps use `cond` to keep this structure flat 👍

File: src/status_im2/contexts/onboarding/create_profile/view.cljs [hunk 2]
```diff
@@ -48,19 +49,34 @@
...
+         {:style style/blur-button-container})
+        children])
      [rn/view {:style style/view-button-container}
       children])])
 
+(defn show-button-background
+  [keyboard-shown?]
+  (let [{:keys [keyboard-height]} (hooks/use-keyboard)
+        window-height             (rf/sub [:dimensions/window-height])
+        remaining-screen-height   (- window-height keyboard-height)]
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/create_profile/view.cljs]: should this not include the height of the button container? 
```
(- window-height keyboard-height button-container)]
```
because that would be the marking of the line

Comment (jo-mut) [reply src/status_im2/contexts/onboarding/create_profile/view.cljs]: yeah this seems to be why in some devices its not working as expected

**Review by rahulpsingh — APPROVED** [review]

**Comment by jo-mut** [comment]
@VolodLytvynenko  Works okay now

**Comment by pavloburykh** [comment]
Hey @jo-mut ! Why this PR has been closed?

**Comment by churik** [comment]
@Francesca-G approve if that's acceptable:
IPhone 12 Mini:
IMAGE 2023-07-12 17:16:11
Google Pixel 7A:
IMAGE 2023-07-12 17:16:49

**Comment by J-Son89** [comment]
The pixel 7a is wrong here -> border around button should only be showing if it will cover the color picker (or whatever the bottom page content is)

**Comment by churik** [comment]
thanks @J-Son89 
Please, @jo-mut  ping QA after https://github.com/status-im/status-mobile/pull/16432#issuecomment-1632746157 is fixed, thanks!

**Review by Francesca-G — COMMENTED** [review]
@churik everything looks good besides what @J-Son89 already pointed out.
Not only the bottom action background should only be visible when the button overlaps the colors but the background is also too dark compared to design.

Feel free to mention me again once it's fixed :)

Check design [here](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=6345%3A327102&mode=design&t=7rixrOPEqCh9LTgz-1)

Profile

**Comment by jo-mut** [comment]
@J-Son89 I have updated this pr and tested it on a large screen device. Works fine now both ios and android. The issue on pixel 7a should be resolved

**Comment by VolodLytvynenko** [comment]
Hi @jo-mut. Thank you for PR. For Pixel 7a the issue is resolved now. The background border is shown only if 'continue' buttons overlaps the background. But still background is too dark for android devices as mentioned here https://github.com/status-im/status-mobile/pull/16432#pullrequestreview-1527989959 

## ISSUE 2: Background section is too dark for 'continue' button on Android devices when the 'continue' button overlaps the color picker

### Actual result:
The background section behind the 'continue' button appears to be too dark
image

### Expected result:
The blur is applied for background section where the 'continue' button is located 
image
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=6345-327102&mode=design&t=2InnCUVBbIiQiTJU-0

### Device:
Android Studio: Pixel XL API 29

**Comment by J-Son89** [comment]
@VolodLytvynenko, @jo-mut blur on android is a much larger issue. so I think here it's just using a normal view and that is why it's darker. I think we discussed this with design team and they never provided a better alternative color. There is some work to try a new package for blur (Expo blur) which might improve things but that is beyond the scope of this pr. As long as the background is showing when it should, then all is good here 👍

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko, @jo-mut blur on android is a much larger issue. so I think here it's just using a normal view and that is why it's darker. I think we discussed this with design team and they never provided a better alternative color. There is some work to try a new package for blur (Expo blur) which might improve things but that is beyond the scope of this pr. As long as the background is showing when it should, then all is good here 👍

Got it. Thank you for your explanation. I will provide feedback soon if no additional issues are found

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: [IOS] Delayed blurred background resolving when the profile page is initially opened

### Steps:
1. Go to Create profile page after the app launched
2. Observe the background resolving

### Actual result:
The blurred background behind the 'continue' button takes some time to resolve
iPhone SE

https://github.com/status-im/status-mobile/assets/52490791/e7179162-68df-4dcf-a4c4-300075f49a51

iPhone Mini

https://github.com/status-im/status-mobile/assets/52490791/1d1d7fb8-4d82-4a59-a1f0-25848d055a1b



### Expected result:
The blurred background behind the 'continue' button should be resolved and load smoothly

### NOTE: 
After the keyboard is opened a few times, the background delay disappears. So, the issue is reproducible after the initial opening of the profile page on iOS devices

### Device:
- iPhone SE, IOS 16
- iPhone 12 mini

@qoqobolo thanks for finding it

**Comment by jo-mut** [comment]
@VolodLytvynenko I managed to fix this. you can have a look

The case for when the background shows

https://github.com/status-im/status-mobile/assets/28704507/340d8da5-fd62-430b-b11c-eb4c71cd4f51


The case for when the backgroun is not shown

https://github.com/status-im/status-mobile/assets/28704507/ae349349-a873-4e7e-b10d-5177b4b415ca

**Comment by VolodLytvynenko** [comment]
Hi @Francesca-G, the PR is ready for review. Could you please check it?
NOTE: The issue you mentioned about the black background still appearing for Android devices is still present, as discussed [here](https://github.com/status-im/status-mobile/pull/16432#pullrequestreview-1527989959). However, this is currently beyond the scope of this PR. You can find more details in this comment: https://github.com/status-im/status-mobile/pull/16432#issuecomment-1645592696

**Review by Francesca-G — APPROVED** [review]
The button background looks good, so I'm approving!

I might have found a problem: I'm able to scroll the section enough so that the button isn't overlapping anymore and in that case the background stays even if it shouldn't.
If this is a problem we need to address please add the follow up required label 🙏

https://github.com/status-im/status-mobile/assets/122543089/38a8d225-4870-4fbc-8630-47b907beeab3

**Comment by VolodLytvynenko** [comment]
@jo-mut Thank you for PR. Created a separate follow up https://github.com/status-im/status-mobile/issues/16925 
PR is ready to be merged

**Comment by jo-mut** [comment]
@pavloburykh  I have made the fix for that. Works fine now

https://github.com/status-im/status-mobile/assets/28704507/8b77761b-e370-411e-a0a4-c99c136f49cf
