### PR TITLE
Change password inside new settings

### LINKED ISSUE #19111: Add "Change password" screen to settings
# Bug Report

## Problem 
[comment]: # (A problem description)
Add the "Change password" screen to the settings according to the current state of the designs (might change in the future). The design is not very different from the onboarding "Create password" screen, so we're not loosing much by just adding it but we're gaining the ability to change the password at least.

[Design link](https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?type=design&node-id=6638-397016&mode=design&t=buA3cDaY8vTO0BeZ-4)
> Discussed with @cammellos and decided to add it to this crew's project
#### Expected behavior

Can change the password from the new settings

#### Actual behavior

Cannot change the password from the new settings

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19111 

### Summary
- Added the new `change password` screens according to the current designs (which might change as they're not final)
  - some parts were taken from the `status-im.contexts.onboarding.create-password.view` ns
  - didn't add the `enable biometrics` step
  - didn't add illustrations as the desings are not done yet
- Added the `password-tips` quo component

#### Platforms

- Android
- iOS

##### Functional

- settings

### Steps to test

- Open Status
- open settings
- password
- change-password

status: ready

### CODE REVIEW

File: src/native_module/utils.cljs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+      (if error (rej error) (res result)))))
+
+(defn promisify-native-module-call
+  [func & args]
+  (promesa/create
+   (fn [res rej]
+     (->> (promisify-callback res rej)
+          (conj [])
+          (concat args)
+          (apply func)))))
```
Comment (clauxx) [inline src/native_module/utils.cljs]: @cammellos in order to use native module calls as promises, added this utility (used in `src/native_module/core.cljs`). Wanted to know if this would be a good way to handle this and whether there are better alternatives.

Comment (cammellos) [reply src/native_module/utils.cljs]: it looks ok to me, maybe leave out the extra `conj` since it's redundant?

`(->> [(promisify....)]
         (concat args)
         ....)`

File: src/status_im/contexts/preview/quo/password/password_tips.cljs [hunk 2]
```diff
@@ -0,0 +1,33 @@
+(ns status-im.contexts.preview.quo.password.password-tips
+  (:require
+    [quo.core :as quo]
+    [quo.foundations.colors :as colors]
+    [reagent.core :as reagent]
+    [status-im.contexts.preview.quo.preview :as preview]))
+
+(def tips [:lower-case? :upper-case? :numbers? :symbols?])
+
+(defn make-init-state
```
Comment (cammellos) [inline src/status_im/contexts/preview/quo/password/password_tips.cljs]: this can be def, and I think if you really want it to generate it like that, then it makes sense to avoid `4`, since I take you want to have the same number, I think a reduce would just do in this case:

```
(def make-init-state
   (reduce (fn [acc tip] (assoc acc tip false)) {} tips))
```

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+
+(defn- password-validations
+  [password]
+  (let [validations (juxt utils.string/has-lower-case?
+                          utils.string/has-upper-case?
+                          utils.string/has-numbers?
+                          utils.string/has-symbols?)]
+    (->> password
+         (validations)
+         (zipmap [:lower-case? :upper-case? :numbers? :symbols?]))))
```
Comment (cammellos) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: could you reuse the `tips` definition here?

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+
+(defn view
+  [{:keys [customization-color]}]
```
Comment (cammellos) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: if it only needs customization color, i would only pass that one

File: src/status_im/contexts/profile/settings/screens/password/change_password/old_password_form.cljs [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+    [status-im.constants :as constant]
+    [status-im.contexts.profile.settings.screens.password.change-password.events]
+    [status-im.contexts.profile.settings.screens.password.change-password.style :as style]
+    [utils.i18n :as i18n]
+    [utils.re-frame :as rf]
+    [utils.security.core :as security]
+    [utils.string :as utils.string]))
+
+(defn view
+  [{:keys [customization-color]}]
```
Comment (cammellos) [inline src/status_im/contexts/profile/settings/screens/password/change_password/old_password_form.cljs]: same, if only needs customization, we should subscribe to it only and pass only this one

File: src/status_im/contexts/profile/settings/screens/password/change_password/view.cljs [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+     [rn/pressable
+      {:key        :change-password
+       :on-press   rn/dismiss-keyboard!
+       :accessible false
+       :style      {:flex 1}}
+      [quo/page-nav
+       {:margin-top top
+        :background :blur
+        :icon-name  :i/arrow-left
+        :on-press   #(rf/dispatch [:navigate-back])}]
```
Comment (cammellos) [inline src/status_im/contexts/profile/settings/screens/password/change_password/view.cljs]: this one can be `def` to avoid re-rendering `page-nav` if `view` re-renders

File: src/status_im/navigation/screens.cljs [hunk 7]
```diff
@@ -452,9 +455,24 @@
...
+     :component settings-password/view}
+
+    {:name      :screen/change-password
+     :options   (merge
+                 options/transparent-modal-screen-options
+                 {:theme :dark})
+     :component change-password/view}
+
+    {:name      :screen/change-password-loading
+     :options   (merge
```
Comment (cammellos) [inline src/status_im/navigation/screens.cljs]: no need to `merge`, assoc is variadic
`(assoc options/.... :theme :dark
                               :popGesture ...
                               `

**Comment by clauxx** [comment]
@cammellos addressed your comments in the last commit

File: src/quo/components/password/password_tips/style.cljs~
Comment (seanstrom) [inline src/quo/components/password/password_tips/style.cljs~:1]: Tiny comment:
Is this a backup file?

File: src/quo/components/selectors/disclaimer/style.cljs [hunk 8]
```diff
@@ -3,16 +3,16 @@
     [quo.foundations.colors :as colors]))
 
 (defn container
-  [blur?]
+  [blur? theme]
```
Comment (seanstrom) [inline src/quo/components/selectors/disclaimer/style.cljs]: Maybe we can pass a map here?

File: src/status_im/contexts/onboarding/create_password/view.cljs [hunk 9]
```diff
@@ -112,7 +113,7 @@
                           #(utils.string/at-least-n-chars? % 10))]
     (->> password
          (validations)
-         (zipmap [:lower-case? :upper-case? :numbers? :symbols? :long-enough?]))))
+         (zipmap (conj constant/password-tips :long-enough?)))))
```
Comment (seanstrom) [inline src/status_im/contexts/onboarding/create_password/view.cljs]: Should `:long-enough?` also be included in the constant password-tips?

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 10]
```diff
@@ -0,0 +1,161 @@
...
+    [utils.re-frame :as rf]
+    [utils.security.core :as security]
+    [utils.string :as utils.string]))
+
+(def ^:private strength-status
+  {1 :very-weak
+   2 :weak
+   3 :okay
+   4 :strong
+   5 :very-strong})
```
Comment (seanstrom) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: Maybe this could also be a constant?

File: src/native_module/utils.cljs [hunk 11]
```diff
@@ -0,0 +1,21 @@
...
+                    error))]
+      (if error (rej error) (res result)))))
+
+(defn promisify-native-module-call
+  [func & args]
+  (promesa/create
+   (fn [res rej]
+     (->> [(promisify-callback res rej)]
+          (concat args)
+          (apply func)))))
```
Comment (seanstrom) [inline src/native_module/utils.cljs]: This is pretty neat! 🙌

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs [hunk 12]
```diff
@@ -0,0 +1,18 @@
...
+            [promesa.core :as promesa]
+            [status-im.common.keychain.events :as keychain]
+            [utils.re-frame :as rf]
+            [utils.security.core :as security]))
+
+(rf/reg-fx
+ :effects.change-password/change-password
+ (fn [{:keys [key-uid old-password new-password on-success on-fail]}]
+   (let [hash-masked-password (fn [pw]
+                                (-> pw security/safe-unmask-data native-module/sha3))
```
Comment (seanstrom) [inline src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: Can we extract this function into a static function?

File: src/status_im/contexts/profile/settings/screens/password/change_password/events.cljs [hunk 13]
```diff
@@ -0,0 +1,77 @@
...
+            [taoensso.timbre :as log]
+            [utils.re-frame :as rf]
+            [utils.security.core :as security]))
+
+(rf/reg-event-fx
+ :change-password/verify-old-password
+ (fn [_ [entered-password]]
+   (let [hashed-password (-> entered-password
+                             security/safe-unmask-data
+                             native-module/sha3)]
```
Comment (seanstrom) [inline src/status_im/contexts/profile/settings/screens/password/change_password/events.cljs]: Can we re-use this composition of functions as a static function?

File: src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs [hunk 14]
```diff
@@ -0,0 +1,51 @@
...
+  (:require [quo.core :as quo]
+            [react-native.core :as rn]
+            [react-native.safe-area :as safe-area]
+            [status-im.contexts.profile.settings.screens.password.change-password.style :as style]
+            [utils.i18n :as i18n]
+            [utils.re-frame :as rf]))
+
+;; NOTE: The duration of the password change depends on the device hardware, so to avoid
+;; quick changes in UI when mounted, we're waiting for a bit.
+(def ^:private minimum-loading-time 5000)
```
Comment (seanstrom) [inline src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs:11]: Do we have a way of knowing or measuring the maximum time a device would need to change a password?

File: src/status_im/contexts/profile/settings/screens/password/change_password/style.cljs [hunk 15]
```diff
@@ -0,0 +1,64 @@
...
+(def password-tips
+  {:flex-direction    :row
+   :margin-horizontal 20
+   :justify-content   :space-between})
+
+(def bottom-part
+  {:position :absolute
+   :bottom   0
+   :left     0
+   :right    0})
```
Comment (seanstrom) [inline src/status_im/contexts/profile/settings/screens/password/change_password/style.cljs]: Does this pin to the bottom correctly when the testnet mode banner is active?

**Review by seanstrom — COMMENTED** [review]
Nice stuff 🙌 
Left some small comments, I'll doing another pass soon 🙏

File: src/status_im/contexts/onboarding/create_password/view.cljs (hunk 9 above)
Comment (clauxx) [reply src/status_im/contexts/onboarding/create_password/view.cljs]: don't think so, since it's not a "tip" but a validation rule. Was also confused by it initially cause it doesn't really belong here, but didn't want to add more changes than needed

File: src/quo/components/selectors/disclaimer/style.cljs (hunk 8 above)
Comment (clauxx) [reply src/quo/components/selectors/disclaimer/style.cljs]: usually we use maps when we pass more arguments cause then it's more readable. Seems fine to just pass 2 args 
 here IMO cause it's just a function, what do you think?

File: src/quo/components/password/password_tips/style.cljs~
Comment (clauxx) [reply src/quo/components/password/password_tips/style.cljs~:1]: yep, thanks for catching this. gotta add this to gitignore for the future

File: src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs (hunk 14 above)
Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs:11]: It should be proportional to the size of the database so the more communities/chats/contacts/collectibles the user has, the longer it should take

File: src/status_im/contexts/profile/settings/screens/password/change_password/style.cljs (hunk 15 above)
Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/style.cljs]: Not sure, will have to check. I guess we'd need a generic solution for this as I saw it mentioned a few times already.

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 12 above)
Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: I added one a while back to the security ns but forgot about it :brain: . Will use it here and in the case below

File: src/quo/components/selectors/disclaimer/style.cljs (hunk 8 above)
Comment (seanstrom) [reply src/quo/components/selectors/disclaimer/style.cljs]: I'm fine with two arguments 👍
maybe it more around 3 or more args when a map can be used?

File: src/native_module/core.cljs [hunk 16]
```diff
@@ -536,11 +537,16 @@
...
-  (log/debug "[native-module] change-database-password")
-  (init-keystore
-   key-uid
-   #(.reEncryptDbAndKeystore ^js (encryption) key-uid current-password# new-password# callback)))
+  ([key-uid current-password# new-password#]
+   (native-utils/promisify-native-module-call reset-password
+                                              key-uid
+                                              current-password#
+                                              new-password#))
+  ([key-uid current-password# new-password# callback]
```
Comment (ilmotta) [inline src/native_module/core.cljs]: @clauxx, I'm surprised to see the usage of `#` as a suffix. This is very confusing to me because `foo#` is used to auto generate symbols inside syntax quotes (in macros). But here it's being used inside a function. I would highly discourage this practice.

File: src/native_module/utils.cljs [hunk 17]
```diff
@@ -0,0 +1,21 @@
...
+(defn- promisify-callback
+  [res rej]
+  (fn [result]
+    (let [error (let [{:keys [error]} (types/json->clj result)]
+                  (when-not (string/blank? error)
+                    error))]
+      (if error (rej error) (res result)))))
+
+(defn promisify-native-module-call
+  [func & args]
```
Comment (ilmotta) [inline src/native_module/utils.cljs]: It's more idiomatic to name it `f` https://guide.clojure.style/#idiomatic-names.

File: src/status_im/contexts/preview/quo/password/password_tips.cljs [hunk 18]
```diff
@@ -0,0 +1,29 @@
...
+  [tip]
+  {:key  tip
+   :type :boolean})
+
+(def descriptor
+  (map make-tip-descriptor constant/password-tips))
+
+(defn view
+  []
+  (let [state (reagent/atom init-state)]
```
Comment (ilmotta) [inline src/status_im/contexts/preview/quo/password/password_tips.cljs:22]: @clauxx, do you know what's the decision about using Reagent atoms. I'm asking this because this is green code. I've been off for a few weeks and I thought we should be using React's local state.

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs [hunk 19]
```diff
@@ -0,0 +1,18 @@
+(ns status-im.contexts.profile.settings.screens.password.change-password.effects
+  (:require [native-module.core :as native-module]
+            [promesa.core :as promesa]
+            [status-im.common.keychain.events :as keychain]
+            [utils.re-frame :as rf]
+            [utils.security.core :as security]))
+
+(rf/reg-fx
+ :effects.change-password/change-password
```
Comment (ilmotta) [inline src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: FYI: The IDs of effects, events, and subs can be written in the same line as `rf/reg-*`. This facilitates grepping in the project line by line (without requiring other lines for context). We already added the rules to zprintrc.

Multiple times per day, when I search for a "re-frame ID" I want to easily find where the thing is registered (file + line). If the ID is on the same line as `reg-*`, I can quickly differentiate the registration call from the many usages. I can also add `reg` in the search and I'll get precise hits without needing more lines of context while grepping.

For the sake of consistency, it would be great if we could tell zprint to force this style for us automatically. Meanwhile, we can do this manually.

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 20]
```diff
@@ -0,0 +1,161 @@
...
+       (i18n/label :t/password-creation-tips-4)]]]))
+
+(defn- password-validations
+  [password]
+  (let [validations (juxt utils.string/has-lower-case?
+                          utils.string/has-upper-case?
+                          utils.string/has-numbers?
+                          utils.string/has-symbols?)]
+    (->> password
+         (validations)
```
Comment (ilmotta) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: I like the symmetry of always adding parentheses. But we stick with the Clojure Style Guide for simplicity in this repo, and parentheses should only be added if necessary https://guide.clojure.style/#threading-macros-and-optional-parentheses

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 21]
```diff
@@ -0,0 +1,161 @@
...
+         (zipmap constant/password-tips))))
```
Comment (ilmotta) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: I would rather prefer if this implicit dependency between `password-tips` and the order of functions passed to `juxt` didn't exist because it's more fragile.

The code below does the same and it's significantly simpler. The coupling between the values in `password-tips` and the types of validations is now explicit and no implicit order exists. I see beauty in using `juxt` with `zipmap`, but it's convoluted here imo.

```clojure
{:lower-case? (has-lower-case? password)
 :upper-case? (has-upper-case? password)
 :numbers?    (has-numbers? password)
 :symbols?    (has-symbols? password)}
```

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs [hunk 22]
```diff
@@ -0,0 +1,18 @@
...
+ (fn [{:keys [key-uid old-password new-password on-success on-fail]}]
+   (let [hash-masked-password (fn [pw]
+                                (-> pw security/safe-unmask-data native-module/sha3))
+         old-password-hashed  (hash-masked-password old-password)
+         new-password-hashed  (hash-masked-password new-password)]
+     (-> (native-module/reset-password key-uid old-password-hashed new-password-hashed)
+         (promesa/then #(keychain/save-user-password! key-uid new-password-hashed))
```
Comment (ilmotta) [inline src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs:15]: `promesa` as an alias looks so verbose. I see we changed the alias here 53874c8343ef173a43a089916aaf4008f0c0fdf4 🤷🏼 Okay... I hope we can rename it soon to just `p` as it's the alias almost everybody uses with promesa.

**Review by ilmotta — COMMENTED** [review]
Hey @clauxx, I wasn't added as a reviewer, but I felt like sharing a few comments 😈

File: src/quo/components/selectors/disclaimer/view.cljs [hunk 23]
```diff
@@ -3,21 +3,23 @@
...
-     {:type                :checkbox
-      :accessibility-label accessibility-label
-      :blur?               blur?
-      :checked?            checked?
-      :on-change           on-change}]
-    [text/text
-     {:size  :paragraph-2
-      :style style/text}
-     label]]])
+  (let [theme (quo.theme/use-theme)]
```
Comment (vkjr) [inline src/quo/components/selectors/disclaimer/view.cljs]: You might need `use-theme-value` here, because `use-theme` returns map `{:theme "light"}`

File: src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs [hunk 24]
```diff
@@ -0,0 +1,51 @@
...
+       (when-not done?
+         [quo/information-box
+          {:type  :error
+           :style {:margin-top 12}
+           :icon  :i/info}
+          (i18n/label :t/change-password-loading-warning)])]
+      (when done?
+        [quo/logout-button
+         {:container-style style/logout-container
+          :on-press        (fn []
```
Comment (vkjr) [inline src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs]: `rn/use-callback` can be used here
[accordingly to doc/ui-guidelines.md](https://arc.net/l/quote/juitulwc)

File: src/status_im/contexts/preview/quo/password/password_tips.cljs [hunk 25]
```diff
@@ -0,0 +1,29 @@
...
+    [quo.core :as quo]
+    [quo.foundations.colors :as colors]
+    [reagent.core :as reagent]
+    [status-im.constants :as constant]
+    [status-im.contexts.preview.quo.preview :as preview]))
+
+(def init-state
+  (reduce (fn [acc tip] (assoc acc tip false)) {} constant/password-tips))
+
+(defn make-tip-descriptor
```
Comment (vkjr) [inline src/status_im/contexts/preview/quo/password/password_tips.cljs]: Can be private

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 26]
```diff
@@ -0,0 +1,161 @@
...
+        meet-requirements?                             (and (not empty-password?)
+                                                            long-enough?
+                                                            same-passwords?
+                                                            disclaimer-accepted?)
+        error?                                         (and show-validation?
+                                                            (not same-passwords?)
+                                                            (not empty-password?))
+
+        ;; handlers
+        on-change-password                             (fn [new-value]
```
Comment (vkjr) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs:92]: A lot of `rn/use-callback` calls can be added here ;)

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: Just wanted to share that I like the style added by @clauxx in this case, I feel it more comfortable. @ilmotta  Do we really want to add a strict code style for this case?

Comment (ilmotta) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: @ulisesmac, tbh I think either style is fine. Really, the only reason I prefer the other way is because of its practical benefit (at least to me, a few times every day).

I have a theory as to why our repo uses the IDs on the second line. By default, text editors will format arguments to s-exps spanning over multiple lines aligned with the function name. This adds unnecessary indentation that's undesirable in some cases. For example, like this:

```clojure
(rf/reg-event-fx :change-password/submit
                 (fn [{:keys [db]}]
                   ...))
``` 

The way Clojure devs usually deal with this problem without a specific formatting rule from an external too is to either add a line break after `reg-event-fx` (what we did and still do) or, when the team is small, have devs add a formatting rule in their editor (easy in Emacs).

But we have zprint for a while and we already added the rules to support this style in `zprintrc`.

> Do we really want to add a strict code style for this case?

Style rules are always questionable. For this one I think yes, it literally simplifies grepping to find definition and/or usages. But as I said, I don't know if it's possible to have a rule for this because we have in our `zprintrc` that we respect line breaks as much as possible, hence if the dev puts the ID on a separate line zprint won't complaint.

Comment (vkjr) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: +1 for leaving the event names on the same line. For the same reason that Icaro stated.

Comment (ulisesmac) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: For me it's easy to configure the code style of `rf/reg-event-fx` locally, but I still prefer the two line version.

idk, probably this should be voted.

Personally, I'm used to the two line style and I like it too much. same for re-frame subs. BTW what is the a reason behind you don't keep `reg-sub` and the id in the same line? why is it only applied to `reg-event-fx` and `reg-fx`? @vkjr @ilmotta

File: src/native_module/core.cljs (hunk 16 above)
Comment (seanstrom) [reply src/native_module/core.cljs]: I think those `#` were meant to be a short-hand for `hash`. Should we say `hash`, `sha`, or something else instead?

Comment (seanstrom) [reply src/native_module/core.cljs]: For context, here's [an explanation about the macro stuff](https://www.braveclojure.com/writing-macros/#:~:text=In%20this%20example%2C%20you%20create,resolves%20similarly%2C%20and%20so%20on.)

File: src/status_im/subs/settings.cljs [hunk 27]
```diff
@@ -0,0 +1,20 @@
+(ns status-im.subs.settings
+  (:require [re-frame.core :as rf]))
+
+(rf/reg-sub
+ :settings/change-password-current-step
+ :<- [:settings/change-password]
+ (fn [change-password]
```
Comment (flexsurfer) [inline src/status_im/subs/settings.cljs:6]: it could be just keyword, because it's a function , so 
```clojure
(rf/reg-sub
 :settings/change-password-current-step
 :<- [:settings/change-password]
 :current-step)
 ```

File: src/quo/components/selectors/disclaimer/view.cljs (hunk 23 above)
Comment (flexsurfer) [reply src/quo/components/selectors/disclaimer/view.cljs]: good catch, i knew that, never do something for the future, which makes your life harder in present

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (ilmotta) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: @ulisesmac, maybe my initial message was confusing. I wrote `reg-*` to mean all re-frame registration functions receive IDs, and those can always go on the same line as the reg function. This includes `reg-sub` for sure.

Just like the Clojure style guide, what @vkjr and I are advocating is based on a practical advantage. In terms of aesthetics both are fine by me.

Look how useless a line grep looks as of today. There's no easy way to find a keyword that's a `reg-sub` (the same problem applies to other re-frame registration calls).



Now look what happens when the IDs are written on the same line. I can easily filter and find the definition of any re-frame registration call (if our entire codebase was respecting this style).

File: src/status_im/subs/settings.cljs (hunk 27 above)
Comment (cammellos) [reply src/status_im/subs/settings.cljs:6]: no, this I believe does not work, we tried that before, it's because you will get a second argument (the event name or whatever), which means that it will default to it if what it finds is nil, we tried that in the past and got bitten.

`(:blah {:not-present 1} :something) -> :something` that's what you will hit if `change-password?` does not have that key (so I would avoid, even if we think the key will always go there, as it looks like a very natural pattern, but breaks unexpectedly)

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (ilmotta) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: > idk, probably this should be voted.

I agree with you. In this thread it's just a few of us, but it's been useful because it's the first time I remember we talk about this. I think Emacs users are suffering more from this style choice due to how grep results are presented line by line in the minibuffer.

File: src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs (hunk 24 above)
Comment (cammellos) [reply src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs]: this should be `defed` outside of the function, rather than use callback, as it doesn't depend on any argument looks like?

File: src/native_module/core.cljs (hunk 16 above)
Comment (ilmotta) [reply src/native_module/core.cljs]: > I think those `#` were meant to be a short-hand for `hash`. Should we say `hash`, `sha`, or something else instead?

@seanstrom, yes I think we should definitely not add `#` at the end of names in functions.

Comment (clauxx) [reply src/native_module/core.cljs]: will remove that :+1:

File: src/status_im/contexts/preview/quo/password/password_tips.cljs (hunk 18 above)
Comment (clauxx) [reply src/status_im/contexts/preview/quo/password/password_tips.cljs:22]: so we **are** moving away from ratoms and new code shouldn't include them, but in the case of preview screens there's no way around them cause the preview-container component needs the state to be a ratom for now.

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: I would also vote for this cause it's been a bit of a guessing game finding event/sub definitions, but I think this should be enforced by the formatter to get consistent results.

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs (hunk 21 above)
Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: it was mostly a copy paste from the create-password ns, but I agree with you. Will change it :+1:

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 22 above)
Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs:15]: I'm with you on [this](https://github.com/status-im/status-mobile/pull/19332#pullrequestreview-1957353284) :smiling_face_with_tear:

File: src/quo/components/selectors/disclaimer/view.cljs (hunk 23 above)
Comment (clauxx) [reply src/quo/components/selectors/disclaimer/view.cljs]: Can we instead change it so `use-theme` returns the value instead of the map? It doesn't seem to be used anywhere else, other than internally or by mistake

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs (hunk 26 above)
Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs:92]: not sure all of them should be memoised. Most of the re-rendering in this screen will happen due to input value changes and these handlers will be re-created anyways. That's why I only memoised the ones that don't depend on the input values.

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (vkjr) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: The inconvenience also exists in VSCode, not only in emacs:

Screenshot 2024-04-10 at 15 19 44

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs (hunk 26 above)
Comment (vkjr) [reply src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs:92]: As far as I understand, use/callback allows you to avoid re-creating functions. You can specify the value as a dependency and its change will be taken into account

Comment (clauxx) [reply src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs:92]: yes, but the functions will be re-created and memoised again when the dependencies change. So with an input value as a dependency, it will still re-create the functions and will memoise them on every input change. Usually it doesn't matter, cause we get the input value as an argument, but here we have two inputs and each `on-change` handler function depends on the value of the other.

**Review by vkjr — APPROVED** [review]

File: src/quo/components/selectors/disclaimer/view.cljs (hunk 23 above)
Comment (ilmotta) [reply src/quo/components/selectors/disclaimer/view.cljs]: Originally the intention was to use a map to support more themeable data so to speak, but this never happened until now, so it makes sense to return the value directly. @J-Son89 probably knows better the original intention

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs (hunk 21 above)
Comment (ilmotta) [reply src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: Thanks @clauxx. I learned from the original code that `zipmap` with `juxt` returns a map, which I must say I had to experiment in the REPL to believe.

File: src/quo/components/selectors/disclaimer/view.cljs (hunk 23 above)
Comment (J-Son89) [reply src/quo/components/selectors/disclaimer/view.cljs]: Yep that was it. Fine to change from my side 👍

Comment (clauxx) [reply src/quo/components/selectors/disclaimer/view.cljs]: @J-Son89 @ilmotta Then I'll deprecate `use-theme-value` and will add a `use-theme` that does the same thing. Will rename the original `use-theme` to smth else. Or is it better done in a separate PR with a mass rename?

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (ilmotta) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: > I think this should be enforced by the formatter to get consistent results.

Well, let's summon @yqrashawn for zprint stuff! My rough guess is that it can be tricky.

@yqrashawn, do you know if it's possible to tell zprint to prefer to keep re-frame IDs (keywords passed to `reg-sub`, `reg-event-fx`, etc) in the same line as the function call while we still use `:respect-nl` in the config?

File: src/quo/components/selectors/disclaimer/view.cljs (hunk 23 above)
Comment (J-Son89) [reply src/quo/components/selectors/disclaimer/view.cljs]: Can't it just be done in one swoop?
Is there really that many uses of use-theme? Should be a considerably quick and safe refactor to do,no?

Comment (clauxx) [reply src/quo/components/selectors/disclaimer/view.cljs]: atm there's 70 usages of use-theme

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: @ilmotta OK, got it.

I honestly haven't looked for `reg-*`, it's just not part of my workflow, I usually look for a keyword (the event/sub ID) being used in a `dispatch`, reg-*, `sub`, etc, and I get all the results related:

image


But since you'll have a benefit from it, either is fine for me.

Comment (ilmotta) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: @ulisesmac, call it an obsession, but folks in Emacs tend to be obsessed to do things with minimal results on screen. I understand it's very different from IntelliJ workflows, which I used for many years too. I understand how you do global searches and how it's efficient for you.

Thank you for understanding the problem, which is not everybody's problem. Your point of view is probably shared with others in the team.

I'll set up a place where we can vote outside this PR.

File: src/quo/components/selectors/disclaimer/view.cljs (hunk 23 above)
Comment (clauxx) [reply src/quo/components/selectors/disclaimer/view.cljs]: Created a follow-up [issue](https://github.com/status-im/status-mobile/issues/19602)

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 19 above)
Comment (yqrashawn) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: logged here https://github.com/status-im/status-mobile/issues/17641#issue-1943865259
I'll look into it, see if it's possible

I look for keyword instead of reg-xxx as well
I tried to implement something like find definition for rf event keys in emacs (based on ripgrep) before but failed
I just use my emacs default ripgrep setup for now

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Thanks for your PR.

There are several design issues that I see in botha cases: Testnet mode on/off.

**Comment by mariia-skrypnyk** [comment]
**ISSUE 1: Continue button and info block are hidden behind the keyboard**

**Steps:** 

1. Login to app 
2. Go to Profile -> Password -> Change password
3. Put any data into `Current password field`
4. Try to find `Continue button` and `info block`

**Expected result:** `Continue button` and `info block` are placed above the keyboard
https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?type=design&node-id=6638-397016&mode=design&t=qWxcdJ9qiX4L8C0U-0
Screenshot 2024-04-15 at 14 07 50

**Actual result:** `Continue button` and `info block` are hidden behind the keyboard
Screenshot 2024-04-15 at 14 10 29

**Devices:** iOS 13 (17.3.1) Samsung A34 (14.0)

**Comment by mariia-skrypnyk** [comment]
**ISSUE 2: Continue button and info block are placed too low**

**Steps:**

1. Login to app
2. Go to Profile -> Password -> Change password
3. Put any data into Current password field
4. Tap `return` on the keyboard
5. Try to find `Continue button` and `info block`

**Expected result:**
Onboarding `Create Password screen`
photo_2024-04-15_14-27-46

**Actual result:** Continue button and info block are placed too low

Testnet on
photo_2024-04-15_14-00-26 (2)

Testnet off
photo_2024-04-15_14-38-22

**Comment by mariia-skrypnyk** [comment]
**Issue 1** and **Issue 2** also take place in the next step of `Change password screen` during setting New password
Design example:
Screenshot 2024-04-15 at 14 44 51

**Comment by clauxx** [comment]
@mariia-skrypnyk Hey! Fixed the issues (hopefully), please have a look!

File: src/native_module/utils.cljs [hunk 28]
```diff
@@ -0,0 +1,21 @@
...
+                  (when-not (string/blank? error)
+                    error))]
+      (if error (rej error) (res result)))))
+
+(defn promisify-native-module-call
+  [f & args]
+  (promesa/create
+   (fn [res rej]
+     (->> [(promisify-callback res rej)]
+          (concat args)
```
Comment (ibrkhalil) [inline src/native_module/utils.cljs:22]: Can't we just add `args` to the vector on line 19?

File: src/native_module/utils.cljs [hunk 29]
```diff
@@ -0,0 +1,21 @@
+(ns native-module.utils
+  (:require
+    [clojure.string :as string]
+    [promesa.core :as promesa]
+    [utils.transforms :as types]))
+
+(defn- promisify-callback
+  [res rej]
+  (fn [result]
+    (let [error (let [{:keys [error]} (types/json->clj result)]
```
Comment (ibrkhalil) [inline src/native_module/utils.cljs]: Same name declarations are a bit confusing here, Can we rename the exterior declaration of `error` to be something like `error-or-nil`

File: src/quo/components/password/password_tips/view.cljs [hunk 30]
```diff
@@ -0,0 +1,30 @@
...
+     [:lower-case? :boolean]
+     [:upper-case? :boolean]
+     [:numbers? :boolean]
+     [:symbols? :boolean]]
+    [:any]]])
+
+(defn- view-internal
+  [{:keys [lower-case? upper-case? numbers? symbols?]}]
+  [rn/view {:style style/password-tips}
+   [tips/view {:completed? lower-case?}
```
Comment (ibrkhalil) [inline src/quo/components/password/password_tips/view.cljs:21]: Should we rename `completed?` to `valid?`, If it's meant for validating the input.

File: src/status_im/contexts/onboarding/create_password/view.cljs [hunk 31]
```diff
@@ -6,6 +6,7 @@
     [react-native.core :as rn]
     [react-native.safe-area :as safe-area]
     [reagent.core :as reagent]
+    [status-im.constants :as constant]
```
Comment (ibrkhalil) [inline src/status_im/contexts/onboarding/create_password/view.cljs]: Isn't the convention is to require constants as `constants`?

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs [hunk 32]
```diff
@@ -0,0 +1,17 @@
+(ns status-im.contexts.profile.settings.screens.password.change-password.effects
+  (:require [native-module.core :as native-module]
+            [promesa.core :as promesa]
+            [status-im.common.keychain.events :as keychain]
+            [utils.re-frame :as rf]
+            [utils.security.core :as security]))
+
+(rf/reg-fx :effects.change-password/change-password
+ (fn [{:keys [key-uid old-password new-password on-success on-fail]}]
+   (let [hash-masked-password (fn [pw]
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: nit: I think we had a guideline a while back to avoid using abbreviations.

File: src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs [hunk 33]
```diff
@@ -0,0 +1,54 @@
...
+       :style (style/loading-container insets)}
+      [quo/page-nav]
+      [quo/page-top
+       (cond-> {:description :text}
+         (not done?) (assoc
+                      :title            (i18n/label :t/change-password-loading-header)
+                      :description-text (i18n/label :t/change-password-loading-description))
+         done?       (assoc
+                      :title            (i18n/label :t/change-password-done-header)
+                      :description-text (i18n/label :t/change-password-done-description)))]
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/loading.cljs]: nit: We might not need to thread here
```clj
{:title            (if done? `:t/option-1` `:t/option-2`)
 :description-text (if done? `:t/option-1` `:t/option-2`
:description       :text)}
```

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 34]
```diff
@@ -0,0 +1,154 @@
...
+(defn- password-with-hint
+  [{{:keys [text status shown]} :hint :as input-props}]
+  [:<>
+   [quo/input
+    (-> input-props
+        (dissoc :hint)
+        (assoc :type  :password
+               :blur? true))]
+   [rn/view {:style style/info-message}
+    (when shown
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: nit: Should this be `shown?`

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 35]
```diff
@@ -0,0 +1,154 @@
...
+                      colors/white-70-blur)
+        :icon-color (when (= status :default)
+                      colors/white-70-blur)}
+       text])]])
+
+(defn- calc-password-strength
+  [validations]
+  (->> (vals validations)
+       (filter true?)
+       (count)))
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: Against clojure style guide
Ref: https://github.com/bbatsov/clojure-style-guide?tab=readme-ov-file#threading-macros-and-optional-parentheses

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 36]
```diff
@@ -0,0 +1,154 @@
...
+        (dissoc :hint)
+        (assoc :type  :password
+               :blur? true))]
+   [rn/view {:style style/info-message}
+    (when shown
+      [quo/info-message
+       {:type       status
+        :size       :default
+        :icon       (if (= status :success) :i/positive-state :i/info)
+        :text-color (when (= status :default)
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: nit: I'd declare `(= status :default)` in a `let` binding to avoid repeating it.

File: src/status_im/contexts/onboarding/create_password/view.cljs [hunk 37]
```diff
@@ -109,10 +103,10 @@
                           utils.string/has-upper-case?
                           utils.string/has-numbers?
                           utils.string/has-symbols?
-                          #(utils.string/at-least-n-chars? % 10))]
+                          #(utils.string/at-least-n-chars? % constant/new-password-min-length))]
     (->> password
          (validations)
```
Comment (ibrkhalil) [inline src/status_im/contexts/onboarding/create_password/view.cljs]: Against clojure style guide
Ref: https://github.com/bbatsov/clojure-style-guide?tab=readme-ov-file#threading-macros-and-optional-parentheses

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 38]
```diff
@@ -0,0 +1,154 @@
...
+        [disclaimer-accepted? set-disclaimer-accepted] (rn/use-state false)
+        [focused? set-focused]                         (rn/use-state false)
+        [show-validation? set-show-validation]         (rn/use-state false)
+
+        ;; validations
+        validations                                    (password-validations password)
+        long-enough?                                   (utils.string/at-least-n-chars?
+                                                        password
+                                                        constant/new-password-min-length)
+        empty-password?                                (empty? password)
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: I'd use `clojure.string/blank?`, Use might enter whitespace.

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 39]
```diff
@@ -0,0 +1,154 @@
...
+                                                            same-passwords?
+                                                            disclaimer-accepted?)
+        error?                                         (and show-validation?
+                                                            (not same-passwords?)
+                                                            (not empty-password?))
+
+        ;; handlers
+        on-change-password                             (fn [new-value]
+                                                         (set-password new-value)
+                                                         (when (and (seq new-value)
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: I'd use the complement of `clojure.string/blank?`
```clj
(complement str/blank?)
```

User might enter whitespace.

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 40]
```diff
@@ -0,0 +1,154 @@
...
+                                                                    (= (count new-value)
+                                                                       (count repeat-password)))
+                                                           (set-show-validation true)))
+        on-change-repeat-password                      (fn [new-value]
+                                                         (set-repeat-password new-value)
+                                                         (when (and (seq new-value)
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: I'd use the complement of `clojure.string/blank?`
```clj
(complement str/blank?)
```

File: src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs [hunk 41]
```diff
@@ -0,0 +1,154 @@
...
+        on-submit                                      (fn []
+                                                         (rf/dispatch
+                                                          [:change-password/confirm-new-password
+                                                           (security/mask-data password)]))]
+    [:<>
+     [rn/view {:style style/form-container}
+      [password-with-hint
+       {:hint           {:text   (i18n/label :t/password-creation-hint)
+                         :status (if long-enough? :success :default)
+                         :shown  true}
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/new_password_form.cljs]: nit
`shown -> shown?`

File: src/status_im/contexts/profile/settings/screens/password/change_password/old_password_form.cljs [hunk 42]
```diff
@@ -0,0 +1,56 @@
...
+(defn view
+  []
+  (let [error                   (rf/sub [:settings/change-password-error])
+        customization-color     (rf/sub [:profile/customization-color])
+        [password set-password] (rn/use-state "")
+        on-change-password      (fn [new-value]
+                                  (when error
+                                    (rf/dispatch [:change-password/reset-error]))
+                                  (set-password new-value))
+        meet-requirements?      (and (seq password)
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/old_password_form.cljs]: I'd use the complement of `clojure.string/blank?`
```clj
(complement str/blank?)
```

File: src/status_im/contexts/profile/settings/screens/password/change_password/style.cljs [hunk 43]
```diff
@@ -0,0 +1,63 @@
...
+
+(def warning-container
+  {:margin-top 12})
+
+(defn loading-container
+  [insets]
+  {:flex            1
+   :justify-content :space-between
+   :padding-top     (:top insets)
+   :padding-bottom  (:bottom insets)})
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/style.cljs]: nit: These values can be destructured on line 33.

File: src/status_im/contexts/profile/settings/screens/password/change_password/view.cljs [hunk 44]
```diff
@@ -0,0 +1,53 @@
...
+(defn- navigate-back
+  []
+  (rf/dispatch [:navigate-back]))
+
+(defn view
+  []
+  (let [{:keys [top]} (safe-area/get-insets)
+        current-step  (or (rf/sub
+                           [:settings/change-password-current-step])
+                          :old-password)]
```
Comment (ibrkhalil) [inline src/status_im/contexts/profile/settings/screens/password/change_password/view.cljs]: Can the subscription provide the default value?
I think it makes sense to make the value calculation as much as possible on the subscription end.

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !
Thanks for your fix!
It helped me a lot during my next testing iteration.
  
1) Please, let me know should your PR include these validation rules?
Screenshot 2024-04-16 at 14 41 47
Screenshot 2024-04-16 at 14 41 57

2) In case `Testnet mode` is `on` we do not see `Continue button` but screen looks correct if`Testnet mode` is `off`.
So, as we have designs when `Testnet mode` is `off` I suppose we can leave this issue as it is or try to fix it in followup if there is any way.

Screenshot 2024-04-16 at 14 52 08

**Comment by mariia-skrypnyk** [comment]
**ISSUE 3: Change password screen blocks overlap if user put emoji into password fields**

**Device:** iOS 13 (17.3.1) 
**Steps:**

1. Login to app
2. Go to Profile -> Password -> Change password
3. Add emoji to  Current password field (keyboard will contain Emoji's if you tap on eye icon in  Current password field)
4. Move to the next screen and do the same with New password

**Actual result:**

Screenshot 2024-04-16 at 15 10 23

https://github.com/status-im/status-mobile/assets/147824399/d2aeb6ba-efe2-49a7-9c51-afbc94d0c4f4

**Expected result:** screend look as designed [here](https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?type=design&node-id=6638-399494&mode=design&t=BfkU4hR8rhb0Bw9Y-0).

Screenshot 2024-04-16 at 15 12 13
Screenshot 2024-04-16 at 15 12 26

**Comment by mariia-skrypnyk** [comment]
As this feature will be updated by additional steps in future I suppose we can skip design review for the current PR.
@clauxx Please add design review label in case feature will be totally finished in on of PRs.

**Comment by clauxx** [comment]
> As this feature will be updated by additional steps in future I suppose we can skip design review for the current PR. @clauxx Please add design review label in case feature will be totally finished in on of PRs.

@mariia-skrypnyk thanks for the review. I think we can completely avoid the issue above by disabling the emoji keyboard, since we don't use it on the login screen either.

**Comment by mariia-skrypnyk** [comment]
> since we don't use it on the login screen either

I've tested this case as I it is included in onboarding create password scope.
I really don't mind of disabling if you discuss it with designers/team.

I have several more issues for Android, will add them in 20 min.

**Comment by mariia-skrypnyk** [comment]
**Issue 4: Titles "Keep up"/"Re-encription" are moved to the right**

**Devices:** Samsung A34 (14.0)

**Steps:** 

1. Login to app
2. Go to Profile -> Password -> Change password
3. Go through all steps till the last screens

**Expected result:**

Screenshot 2024-04-16 at 16 01 20
Screenshot 2024-04-16 at 16 01 28

https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?type=design&node-id=6286-3943&mode=design&t=BfkU4hR8rhb0Bw9Y-0

**Actual result:**

Screenshot 2024-04-16 at 15 58 33
Screenshot 2024-04-16 at 15 58 44

**Comment by mariia-skrypnyk** [comment]
**Issue 5: White screen appears after user moves from Change password to "Keep app open" sceen**

Devices: Samsung A34 (14.0)

**Steps:**

1. Login to app
2. Go to Profile -> Password -> Change password
3. Go through all steps till the last screens

**Expected result:** no white screen appears 
**Actual result:**  
*Please, keep in mind how many overlaps are on Android screens.
Hope they will be also fixed.

https://github.com/status-im/status-mobile/assets/147824399/5c83346d-64ab-421e-ba3a-ca3c55c5f71d

**Comment by mariia-skrypnyk** [comment]
**Issue 6: No "Keep up"/"Re-encription" screens for iOS**

**Device: iOS 13 (17.3.1)
Steps:**

1. Login to app
2. Go to Profile -> Password -> Change password
3. Go through all steps till the last screens

**Expected result:** 
current logic is added
Screenshot 2024-04-16 at 15 48 27

**Actual result:** Change password screen is the last screen of the current feature for iOS

https://github.com/status-im/status-mobile/assets/147824399/94d66fc1-95f3-461f-80c7-867daf1e8152

File: src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs (hunk 32 above)
Comment (ilmotta) [reply src/status_im/contexts/profile/settings/screens/password/change_password/effects.cljs]: It's been a general agreement in the team for a few years apparently, but I couldn't find as a guideline. Either way, good feedback @ibrkhalil

File: src/native_module/utils.cljs (hunk 28 above)
Comment (clauxx) [reply src/native_module/utils.cljs:22]: args is a seq though, so adding it to the vector as you suggested will be `['(arg1 arg2 arg3) (promisify-callback res rej)]` while we need `[arg1 arg2 arg3 (promisify-callback res rej)]`

File: src/quo/components/password/password_tips/view.cljs (hunk 30 above)
Comment (clauxx) [reply src/quo/components/password/password_tips/view.cljs:21]: this is already a large PR and don't want to add changes to other places. The designs also have it as completed, but I agree that it's not the best prop name.

Comment (ilmotta) [reply src/quo/components/password/password_tips/view.cljs:21]: Just complementing the discussion here @ibrkhalil and @clauxx. A while ago I remember I had covered this case in the Quo guidelines, copied here:

> Adhere to the **same component properties and values** used in a Figma component
> when translating it to Clojure. This means using the same names for props and
> the same values. If the Figma property is a boolean, use a question mark suffix
> to make the name more idiomatic in Clojure.
> 
> -- /src/quo/README.md

**Comment by clauxx** [comment]
@mariia-skrypnyk Can you have a look at it again please?

**Comment by mariia-skrypnyk** [comment]
@clauxx please resolve conflicts and I'll finish testing today.

**Comment by clauxx** [comment]
> @clauxx please resolve conflicts and I'll finish testing today.

@mariia-skrypnyk Yes, I'm currently running tests locally for another branch, and it's been 20 minutes already 😨. As soon as it's done will fix the conflicts.

NOTE: accidentally edited you comment 😅

**Comment by cammellos** [comment]
@clauxx is this ready to be tested again?

**Comment by clauxx** [comment]
@cammellos @mariia-skrypnyk yes ready for testing

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

As we keep our Test mode banner we still need to figure out how to deal with `Continue` and `Confirm password` buttons that are hidding behind the keyboard. Maybe @Parveshdhull can help with an idea?

This issue is not visible on my screenshots (security restriction) but I can show you it on video:

We have two places on `iOS` where buttons are hidden: 

1) `Continue` button
2) `Confirm password` button


https://github.com/status-im/status-mobile/assets/147824399/23aeef12-9f13-4706-aa79-b8db61e386b6


https://github.com/status-im/status-mobile/assets/147824399/860ba1c1-17a8-48d4-ae42-8ef7fbeadda5

Android doesn't contain such issue as there is a scroll there and `Continue` and `Confirm password` buttons are visible by reducing visible part of red warning message.
Let me show you:


https://github.com/status-im/status-mobile/assets/147824399/e1acd54b-9ed7-4f77-a130-92e7671b7019

**ISSUE 7:** Additional screens are blinking after logout

**Steps**

1. Login to app
2. Go to Profile -> Change Password
3. Go through steps till Logout

**Actual result:**

https://github.com/status-im/status-mobile/assets/147824399/73ddbf7b-4ed2-4f16-89b7-b3ca5232e8fa

**Expected result:** no such blinking screens

**Comment by Parveshdhull** [comment]
hi @clauxx this should fix issue 6.
https://github.com/status-im/status-mobile/blob/8c26125e52c262eb909f094c400f3e61148fbd49/src/status_im/contexts/profile/edit/bio/view.cljs#L45

File: src/status_im/contexts/profile/settings/screens/password/change_password/view.cljs [hunk 45]
```diff
@@ -0,0 +1,38 @@
...
+       :accessible false
+       :style      {:flex 1}}
+      [quo/page-nav
+       {:margin-top top
+        :background :blur
+        :icon-name  :i/arrow-left
+        :on-press   navigate-back}]
+      [rn/keyboard-avoiding-view
+       {:style                  {:flex 1}
+        :keyboardVerticalOffset (- (safe-area/get-bottom))}
```
Comment (Parveshdhull) [inline src/status_im/contexts/profile/settings/screens/password/change_password/view.cljs]: here, in ios also subtract `alert-banners-top-margin`, that should fix the issue.

**Comment by cammellos** [comment]
@mariia-skrypnyk issue 7 seems to be low-priority, would it be fine to address separately and merge it if that's the only issue left?

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk issue 7 seems to be low-priority, would it be fine to address separately and merge it if that's the only issue left?

Sure 🙌

**Comment by clauxx** [comment]
@mariia-skrypnyk @Parveshdhull @cammellos @J-Son89  I pushed a fix, but it's a bit annoying that we have to add such changes due to the alert banner alone. Also, among other issues, when building new features where the test-mode banner doesn't matter (e.g. here), we have to always keep it in mind and check if the UI is messed up since the banner is also disabled on debug builds by default. I remember there was a thread about the banner topic, but not sure if there was any resolution and hopefully we can get back to it soon and figure out a way that is less ... intrusive.

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Thanks for you effort in this PR!

1) I have one iOS issue. It is overlapping of validation message on my iOS 13 in case NO Testnet banner:
Screenshot 2024-05-07 at 10 38 58

2) Am I right that the best decision here is scroll, yes? 
 It is a situation when keyboard is opened and second password field hides beside it.
 

https://github.com/status-im/status-mobile/assets/147824399/a81b6abc-c8f8-4ea6-b218-82bf3c28aea5

@clauxx I am going to check PR on iPhone SE and see no blockers to merge it after.
Above 1) issue I can create as followup if needed. Just let me know.

**Comment by clauxx** [comment]
> Hi @clauxx !
> 
> Thanks for you effort in this PR!
> 
> 1. I have one iOS issue. It is overlapping of validation message on my iOS 13 in case NO Testnet banner:
> 
> Screenshot 2024-05-07 at 10 38 58
> 2. Am I right that the best decision here is scroll, yes?
>    It is a situation when keyboard is opened and second password field hides beside it.
> 
>  IMG_9047.MP4 
> @clauxx I am going to check PR on iPhone SE and see no blockers to merge it after. Above 1) issue I can create as followup if needed. Just let me know.

@mariia-skrypnyk Yeah might be better to handle this as a follow-up. Thank you :)

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Checked on iPhone SE, found minor issue, will add to follow up.

Failed tests are not related, please merge!
