### PR TITLE
wallet overview: design review fixes

### LINKED ISSUE #16886: Design review: wallet overview
- [ ] 1. "spacing" (time frame: 3 month in screenshot)
- [ ] 2. "the danger color looks darker, I think this is danger/60 (for dark theme), instead of danger/50" (light theme)
- [ ] 3. "I know it's a placeholder but the spacing between balance value and network rectangle doesn't match design"
- [ ] 4. "spacing" (in skeleton loading bars)
- [ ] 5. "this is danger/50 instead of danger/60" (dark theme)

[design review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3446%3A227419&mode=design&t=fxku3lC2V9UiKVNu-1)

Screen Shot 2023-08-04 at 10 50 29 AM

### PR DESCRIPTION
**Pull request by erikseppanen**
fixes #16886

- [X] 1. "spacing" (time frame: 3 month in screenshot) (marked complete, but appears to be correct already)
- [X] 2. "the danger color looks darker, I think this is danger/60 (for dark theme), instead of danger/50" (light theme)
- [X] 3. "I know it's a placeholder but the spacing between balance value and network rectangle doesn't match design"  (marked complete, but appears to be correct already)
- [X] 4. "spacing" (in skeleton loading bars)
- [X] 5. "this is danger/50 instead of danger/60" (dark theme)

Screen Shot 2023-08-17 at 3 34 45 PM

### CODE REVIEW

File: src/quo2/components/wallet/wallet_overview/style.cljs [hunk 1]
```diff
@@ -20,8 +24,10 @@
    :height        32})
 
 (defn color-metrics
-  [metrics]
-  (if (= metrics :positive) colors/success-50 colors/danger-50))
+  [metrics theme]
+  (if (= metrics :positive)
+    colors/success-50
```
Comment (J-Son89) [inline src/quo2/components/wallet/wallet_overview/style.cljs]: Probably success needs to be themed too?

Comment (J-Son89) [reply src/quo2/components/wallet/wallet_overview/style.cljs]: Also it's better to use the semantic name here:success and :danger, double check these values in the color file but that's the way to go imo 👍

File: src/quo2/components/wallet/wallet_overview/view.cljs [hunk 2]
```diff
@@ -107,7 +107,7 @@
                  :margin-right 8}}
        (time-frame time-frames)]
       (when (and (= state :default) (not= metrics :none))
-        [view-metrics metrics currency-change percentage-change])])])
+        [view-metrics metrics currency-change percentage-change theme])])])
```
Comment (J-Son89) [inline src/quo2/components/wallet/wallet_overview/view.cljs]: Consider using a map here instead

File: src/quo2/components/wallet/wallet_overview/style.cljs (hunk 1 above)
Comment (erikseppanen) [reply src/quo2/components/wallet/wallet_overview/style.cljs]: oh you're right, I didn't notice that! I'll fix that...

Comment (erikseppanen) [reply src/quo2/components/wallet/wallet_overview/style.cljs]: fixed/done

File: src/quo2/components/wallet/wallet_overview/view.cljs (hunk 2 above)
Comment (erikseppanen) [reply src/quo2/components/wallet/wallet_overview/view.cljs]: Thanks for your review @J-Son89!

done

**Review by codemaster115 — APPROVED** [review]
👍 LGTM, @erikseppanen

**Review by J-Son89 — APPROVED** [review]

**Comment by erikseppanen** [comment]
@Francesca-G Appreciate your review of this component

**Review by yqrashawn — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by J-Son89** [comment]
@erikseppanen - I believe @Francesca-G is on pto and back Monday

**Review by Francesca-G — APPROVED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3446%3A227419&mode=design&t=AOlIGzDJkyOzHvkm-1) with the review, please refer to review 2 :)
