### PR TITLE
[#16846] fix: resolve communities home design feedbacks

### LINKED ISSUE #16846: Design review: communities home
- [ ] 1. Joined, Pending, Opened looks smaller than at designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510253373)  
- [ ] 2. `Discover` there's a stroke and the shadow is missing **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254368)  

- [ ] 3. Glow in Communities is almost like a shadow around the titles in white mode **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254973)  

- [ ] 4. Spacing between communities in the list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258492)  
- [ ] 5. The unread indicator dot looks bigger than in the designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258717)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #16846

1. Joined, Pending, Opened looks smaller than at designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510253373)

 2. Discover there's a stroke and the shadow is missing (Android only) - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254368)

 4. Spacing between communities in the list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258492)

 5. The unread indicator dot looks bigger than in the designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258717)

status: ready

### CODE REVIEW

File: src/quo2/components/community/banner/style.cljs [hunk 1]
```diff
@@ -1,22 +1,21 @@
...
-   :justify-content   :space-between
-   :background-color  (colors/theme-colors colors/white colors/neutral-90 theme)
-   :flex-direction    :row
-   :margin-horizontal 20
-   :margin-top        8
-   :margin-bottom     8
-   :height            56
-   :padding-right     12})
+  (merge
+   (shadows/get (if platform/ios? 2 4) theme)
```
Comment (cammellos) [inline src/quo2/components/community/banner/style.cljs]: you can use `assoc` as it's variadic. `merge` implies generally that you don't know the keys of the second parameter.

```
(assoc
  (shadows/get (if....))
   :border-radius 16
   :justify-content :space....)
```

If you were to swap the parameters for example, if you would want to use `merge`

```
(merge
   {:border-radius 16
    ....}
   (shadows/get (if...)))
```

But  `assoc` should be used when keys are known

**Review by cammellos — COMMENTED** [review]
looks ok to me, but I'll defer to the UI experts for an approval :)

**Review by ilmotta — APPROVED** [review]
LGTM, but I didn't review the UI because I think this PR should be verified by a designer, just to be sure we fixed all the bugs in scope :)

**Review by vkjr — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
The PR is set for design review, @Francesca-G . Thanks in advance!

**Review by Francesca-G — COMMENTED** [review]
It looks good besides the discover card shadow:
the shadow doesn't match the design on Android and in both iOS and Android there's a line cutting it off at the bottom (see screens)

iOS:
Screenshot 2023-08-24 alle 13 11 04

Android:
Screenshot 2023-08-24 alle 13 11 13

Design:
Screenshot 2023-08-24 alle 13 11 20

**Review by ajayesivan — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@OmarBasem can you please check my last commit, i believe it will close this [issue](https://github.com/status-im/status-mobile/issues/17098) as well, thanks

**Comment by mohsen-ghafouri** [comment]
@Francesca-G resolved, please check again 🙏

**Comment by Francesca-G** [comment]
> @Francesca-G resolved, please check again 🙏

iOS looks good now :)
Android has this narrow shadow that looks like a stroke if you're not zoomed in, which I've seen before, so I think it's a known issue

Screenshot_2023-08-25-08-25-54-441_im status ethereum pr

**Comment by mohsen-ghafouri** [comment]
@Francesca-G can you please check android again, shadow structures for Android and iOS differ, leading to slight UI variations between the platforms. but it shouldn't be like a stroke anymore.

File: src/status_im2/common/home/banner/view.cljs [hunk 2]
```diff
@@ -11,6 +12,8 @@
             [status-im2.common.home.view :as common.home]
             [utils.re-frame :as rf]))
 
+(def card-banner-overflow (reagent/atom :visible))
```
Comment (J-Son89) [inline src/status_im2/common/home/banner/view.cljs:16]: while I'm sure there already many in the codebase, imo we should still avoid adding global ratoms like this.
Is it possible to make this local to the component using it?

cc: @ulisesmac, @ilmotta

File: src/status_im2/common/home/banner/view.cljs [hunk 3]
```diff
@@ -78,4 +81,7 @@
 
 (defn set-scroll-shared-value
   [{:keys [shared-value scroll-input]}]
-  (reanimated/set-shared-value shared-value scroll-input))
+  (reanimated/set-shared-value shared-value scroll-input)
+  (let [new-overflow (if (<= scroll-input 3) :visible :hidden)]
```
Comment (J-Son89) [inline src/status_im2/common/home/banner/view.cljs]: what is `3` referring to? perhaps you could put it in a named def to provide some context of what this value represents

File: src/status_im2/common/home/banner/view.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im2/common/home/banner/view.cljs:16]: @J-Son89 I acknowledge the concern, but due to the atom's usage and changes happen in different area, local usage isn't feasible. If you have any suggestions on how to address this, I'd greatly appreciate your input.

File: src/status_im2/common/home/banner/view.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/status_im2/common/home/banner/view.cljs]: @J-Son89 it's a threshold, sure will move it to a def

File: src/status_im2/common/home/banner/view.cljs (hunk 2 above)
Comment (J-Son89) [reply src/status_im2/common/home/banner/view.cljs:16]: If this is possible with passing props but it would be horrible to do so, then perhaps we can create a react context to make this ratom available in it's nested components/ where it's being used? 🤔

**Comment by Francesca-G** [comment]
> @Francesca-G can you please check android again, shadow structures for Android and iOS differ, leading to slight UI variations between the platforms. but it shouldn't be like a stroke anymore.

It differs from the design as you said but at least it doesn't look like a stroke anymore, it looks better :)

**Review by Francesca-G — APPROVED** [review]
We should find a way to make shadows on Android as close as possible to the design, but in the meantime it looks ok

**Comment by OmarBasem** [comment]
> @OmarBasem can you please check my last commit, i believe it will close this [issue](https://github.com/status-im/status-mobile/issues/17098) as well, thanks

If @Francesca-G approves then it's okay :)

File: src/status_im2/common/home/banner/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im2/common/home/banner/view.cljs:16]: I don't know, it's always feasible to use local ratoms. If the state is "too global" and we want to avoid prop drilling, we can just move the state to the re-frame layer.

Comment (mohsen-ghafouri) [reply src/status_im2/common/home/banner/view.cljs:16]: Yeah, using the scroll input here seems to have a worse impact, especially given that this atom is only used in the banner section. I've taken care to ensure that we only change its value when necessary to avoid any potential performance issues.

Comment (mohsen-ghafouri) [reply src/status_im2/common/home/banner/view.cljs:16]: as I discussed with @J-Son89 i'm going to close this PR with current approach until we find a better solution for this topic

Comment (ilmotta) [reply src/status_im2/common/home/banner/view.cljs:16]: Sure @mohsen-ghafouri, thanks for the clarification.

**Comment by pavloburykh** [comment]
> We should find a way to make shadows on Android as close as possible to the design, but in the meantime it looks ok

hi @mohsen-ghafouri!

For some reason i do not observe any shadows around Discover community card on Android 12 Samsung Galaxy A52. 

Everything remained as it was before the fix. 

I have checked latest nightly and 4 last android builds from this PR. Could you please take a look?

photo_2023-08-28 14 11 13

**Comment by mohsen-ghafouri** [comment]
@pavloburykh Yes, there's an issue with newer Android versions regarding shadows. We were testing the shadow on Android 8.1 and didn't catch it. My apologies for the oversight. I've addressed this in the following [PR](https://github.com/status-im/status-mobile/pull/17128).
