### PR TITLE
fix: no avatar for the first message in 1-1 chat

### LINKED ISSUE #17345: No user avatar is shown for the first messages in 1-1 chat after accepting contact request
# Bug Report

## Problem 
[comment]: # (A problem description)
The first messages sent after accepting contact request do not contain avatar

#### Expected behavior

can see the icon for User2

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/5827fae1-4034-4a1c-b164-5cda2de45930

### Reproduction

1. User1: send contact request
2. User2: accept contact request
3. User2: send message

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by codemaster115**
fixes #17345 

### Summary

Fix the first messages sent after accepting contact request do not contain avatar

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats

### Steps to test
1. User1: send contact request
2. User2: accept contact request
3. User2: send message

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/list/events.cljs [hunk 1]
```diff
@@ -30,6 +31,13 @@
        :one-to-one?       (= constants/message-type-one-to-one message-type)
        :system-message?   (boolean
                            (or
+                            (#{constants/content-type-system-text
```
Comment (cammellos) [inline src/status_im2/contexts/chat/messages/list/events.cljs]: maybe we can define this top of the file or somewhere?

Comment (codemaster115) [reply src/status_im2/contexts/chat/messages/list/events.cljs]: Do you think what naming would be good fit for it? I was thinking of `system-message?`, but this keyword is used as parameter in several functions. 🤔

Comment (cammellos) [reply src/status_im2/contexts/chat/messages/list/events.cljs]: `is-system-message?` maybe? 
since sets are functions that would work both ways.

`(def is-system-message? #{constants....})`

Comment (codemaster115) [reply src/status_im2/contexts/chat/messages/list/events.cljs]: I agree

File: src/status_im2/contexts/chat/messages/list/events.cljs [hunk 2]
```diff
@@ -5,6 +5,17 @@
     [utils.re-frame :as rf]
     [utils.red-black-tree :as red-black-tree]))
 
+(defn- is-system-message?
```
Comment (cammellos) [inline src/status_im2/contexts/chat/messages/list/events.cljs]: sets are functions, as they implement `iFn`. https://clojure.org/reference/data_structures#Sets 

So you can just do

`(def is-system-message? #{constants/....})`

and it can be used in the same way you are using it below:

`(is-system-message? content-type)`

Comment (codemaster115) [reply src/status_im2/contexts/chat/messages/list/events.cljs]: Aha, that makes sense. 🙏

File: src/status_im2/contexts/chat/messages/list/events.cljs [hunk 3]
```diff
@@ -5,6 +5,15 @@
...
     [utils.red-black-tree :as red-black-tree]))
 
+(def is-system-message?
+  #{constants/content-type-system-text
+    constants/content-type-community
+    constants/content-type-system-message-mutual-event-accepted
+    constants/content-type-system-message-mutual-event-removed
+    constants/content-type-system-message-mutual-event-sent
+    constants/content-type-system-pinned-message}
+)
```
Comment (cammellos) [inline src/status_im2/contexts/chat/messages/list/events.cljs]: trailing parentheses

File: src/status_im2/contexts/chat/messages/list/events.cljs [hunk 4]
```diff
@@ -30,6 +39,7 @@
        :one-to-one?       (= constants/message-type-one-to-one message-type)
        :system-message?   (boolean
```
Comment (cammellos) [inline src/status_im2/contexts/chat/messages/list/events.cljs]: actually, sorry, maybe 

```
(def is-system-message-content-type?
  #{constants/content-type-system-text
    constants/content-type-community
     ...)

(defn is-system-message? [content-type message-type]
  (or
    (is-system-message-content-type? content-type)
    (= constants/message-type....)))
```

is clearer

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
@codemaster115 
thank you for your work!! PR is ready to be merged
