### PR TITLE
fix: banner images/colors in shell

### LINKED ISSUE #16112: Jump To - Banner images/colors for cards are not correct
banner images for jump to cards should be adjusted - 
channel color, other persons color or community image

### PR DESCRIPTION
**Pull request by codemaster115**
fixes #16112 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Incorrect banner images/colors on the shell screen

### Review notes
You can check it on the shell screen.
For now, 1:1 chat card is not available to show exact colors since it needs to be done in the back-end side.

### Testing notes

simulator_screenshot_61C72BF0-E0A5-4294-AC06-AA8094EE91D1

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

#### Areas that maybe impacted
Shell screen

### Steps to test

- Open Status
- Click the `Jump To` button in the bottom center.
- You can check several shell cards with proper images/colors except for 1:1 chat.

status: ready

### CODE REVIEW

File: src/quo2/foundations/colors.cljs [hunk 1]
```diff
@@ -246,7 +246,8 @@
             base-color    (get-in colors-map
                                   [(if (= color-keyword :yinyang)
                                      (if (theme/dark?) :yang :yin)
-                                     (keyword color)) suffix])]
+                                     (keyword color)) suffix]
+                                  color)]
```
Comment (Parveshdhull) [inline src/quo2/foundations/colors.cljs]: hi @codemaster115, Thank you very much for your work.
Why we are returning color keyword here?

File: src/status_im2/contexts/shell/cards/style.cljs [hunk 2]
```diff
@@ -15,6 +15,7 @@
   {:width            160
    :height           160
    :border-radius    16
+   :overflow         :hidden
```
Comment (Parveshdhull) [inline src/status_im2/contexts/shell/cards/style.cljs]: why this is needed?

File: src/status_im2/contexts/shell/cards/view.cljs [hunk 3]
```diff
@@ -190,8 +190,8 @@
      [rn/view {:style (style/base-container color-50)}
       (when banner
         [rn/image
-         {:source (:source banner)
-          :style  {:width 160}}])
```
Comment (Parveshdhull) [inline src/status_im2/contexts/shell/cards/view.cljs]: Please also confirm changes related to quo2 components in quo2 preview screens. This change will breaks banner in the preview

File: src/quo2/foundations/colors.cljs (hunk 1 above)
Comment (codemaster115) [reply src/quo2/foundations/colors.cljs]: @Parveshdhull In case of color value is literal like hex, it will return `nil` value instead of the origin.

File: src/status_im2/contexts/shell/cards/style.cljs (hunk 2 above)
Comment (codemaster115) [reply src/status_im2/contexts/shell/cards/style.cljs]: It's necessary to make the banner image's border-radius.

File: src/quo2/foundations/colors.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/quo2/foundations/colors.cljs]: If we already have a hex value, why do we even want to use this function?
Shouldn't this function should be used only when we have the color keyword and want color hex?

File: src/status_im2/contexts/shell/cards/view.cljs (hunk 3 above)
Comment (codemaster115) [reply src/status_im2/contexts/shell/cards/view.cljs:194]: In preview screen, `banner` value is boolean, not image source.

File: src/quo2/foundations/colors.cljs (hunk 1 above)
Comment (codemaster115) [reply src/quo2/foundations/colors.cljs]: To use predefined colors in the Status theme together, it's appropriate to use this function.

File: src/status_im2/subs/shell.cljs [hunk 4]
```diff
@@ -74,7 +74,7 @@
   [chat id communities]
   {:title               (:chat-name chat)
    :avatar-params       {}
-   :customization-color (or (:customization-color chat) :primary)
+   :customization-color (or (:color chat) :primary)
```
Comment (J-Son89) [inline src/status_im2/subs/shell.cljs:92]: hmm, perhaps we can put :primary in a const for it's use case here. e.g default shell header color

**Review by J-Son89 — APPROVED** [review]
Looks good to me @codemaster115!

**Comment by flexsurfer** [comment]
hey @codemaster115 could you pls rebase and resolve conflicts thx

**Comment by flexsurfer** [comment]
ping @codemaster115

**Comment by pavloburykh** [comment]
@codemaster115 please, rebase the PR and resolve conflicts. After that it will be taken into testing. Thanx.

**Comment by pavloburykh** [comment]
@codemaster115 please, rebase the PR and resolve conflicts

**Comment by codemaster115** [comment]
> @codemaster115 please, rebase the PR and resolve conflicts

@pavloburykh Sorry for the late reply. It's rebased now.

**Comment by churik** [comment]
Currently, it works like this
(channel colors are still not implemented on community screens, so this is video to show the params of community on desktop):


https://github.com/status-im/status-mobile/assets/4557972/079147c4-e549-4d55-befd-1d2010648c43

сс @Francesca-G - can we review it from a design perspective? 
Thanks!

@codemaster115 

There is one issue the background banner of the community is applied to other communities too.
The issue is not critical, as it is not expected that communities may be created without banner but in general worth looking at  - may be it is an easy fix.

### ISSUE 1: wrong background banner is applied for the community card in Jump to
**Prerequisites:** user is a member of 2 communities (1 with banner, 1 without banner) 
**Steps:**
1) go to any channel to community A with banner 
2) go to any channel to community B without banner
3) open "Jump to"

**Actual result:** community banner of community A applied to community B

**OS:** IOS, Android

https://github.com/status-im/status-mobile/assets/4557972/249b81e0-4e9a-4f44-ac20-4244d73b18c0

**Comment by codemaster115** [comment]
@churik Thanks for your testing. I will fix the issue soon.

**Review by Francesca-G — COMMENTED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3330%3A268598&mode=design&t=pLZFBtdML4mIwXFa-1) with the design review :) 
I've also created a couple of separate issues for further feedback on Jump To

**Comment by codemaster115** [comment]
@churik The issue is fixed now.

**Review by Francesca-G — APPROVED** [review]

**Comment by churik** [comment]
Thank you for review and fixing the issue!

PR is tested and ready to be merged.

**Review by churik — APPROVED** [review]
