### PR TITLE
fix: calibrate duration calculation of recorded audio

### LINKED ISSUE #15365: The duration of recorded audio is shown as more than 2 minutes after audio message sending
Follow up for https://github.com/status-im/status-mobile/issues/13530

#### Steps to reproduce:
1. Go to any chat
2. Long Tap "record" icon and hold unless the recording will be finished
3. Tap 'send' button

#### Actual result:
The max duration of the sent audio record = 2:03 or more

https://user-images.githubusercontent.com/52490791/225405807-718c9fd4-ec35-4ba9-8960-1815e403f143.mp4

#### Expected result:
The max duration of the sent audio record = 2:00

#### Devices:
- IOS, Android

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #15365

### Summary

Remove usage of JavaScript `setInterval` for calculating audio duration as it is not reliable due to single threaded nature of JavaScript and instead take advantage of metering callback from audio toolkit library + timestamp diff calculations.

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Open a chat
- Record audio until max duration is reached
- Send it
- Check audio duration is 2:00 and not more

status: ready

### CODE REVIEW

**Comment by briansztamfater** [comment]
Some component tests broken with these changes, working on the fixes

File: src/quo2/components/record_audio/record_audio/view.cljs [hunk 1]
```diff
@@ -211,13 +211,43 @@
            (fn []
              (audio/destroy-recorder @recorder-ref)
              (reset! recorder-ref nil))
+           recorder-on-meter
+           (fn []
+             (let [current-timestamp  (.now js/Date)
```
Comment (ilmotta) [inline src/quo2/components/record_audio/record_audio/view.cljs]: Prefer to use `(utils.datetime/timestamp)` if possible. It should work without modification to do math with ms precision. For example https://github.com/status-im/status-mobile/blob/de86586208aa61577aa9f22665e849d574e79a1c/src/status_im/ui/screens/communities/community.cljs#L32

File: src/quo2/components/record_audio/record_audio/view.cljs [hunk 2]
```diff
@@ -211,13 +211,43 @@
...
+                   recording-duration (- current-timestamp
+                                         @start-recording-timestamp)]
```
Comment (ilmotta) [inline src/quo2/components/record_audio/record_audio/view.cljs]: Maybe to be extra precise, we should name these bindings with the millisecond unit. It's usually a good practice, as you did with some other bindings.

- `current-timestamp` -> `current-timestamp-ms` or `now-ms`
- `start-recording-timestamp` -> `start-recording-timestamp-ms` or `recording-start-ms` (noun first, since it's not a function, and it pairs well with another binding you named `recording-length-ms`).

**Review by ilmotta — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hi @briansztamfater thanx for the PR. Please, take a look at some minor issues

### ISSUE 1 Max audio duration is 1:59 instead of 2:00 for Android

**Steps:** 

1. Record max duration audio on Android
2. See what is max duration of recorded audio

**Expected result:** 2:00

**Actual result:** 1:59


https://user-images.githubusercontent.com/97245802/230612366-818ff107-d0e3-4f5f-a797-cc14511fa3ab.mp4

**Comment by pavloburykh** [comment]
### ISSUE 2 Max duration of recorded audio changes from 2:00 to 2:01 after playing and fast forwarding to the end (IOS)

**Steps:**

1. Record max duration audio on IOS
2. Send audio
3. Play and fast forward audio to the end
4. See what duration is shown after farwarding

**Expected result:** duration remains 2:00

**Actual result:** duration changed to 2:01


https://user-images.githubusercontent.com/97245802/230613313-e4cd7d91-376b-4096-860b-905ee6f86c42.mp4

**Comment by briansztamfater** [comment]
Thanks for testing @pavloburykh, I'll check those issues and let you know once ready to test again

**Comment by briansztamfater** [comment]
@pavloburykh issues should be fixed now, I tested myself on my iOS and Android physical devices, an iPhone 13 Pro and Xiaomi Mi 10T. Let me know how testing goes.

**Comment by pavloburykh** [comment]
> @pavloburykh issues should be fixed now, I tested myself on my iOS and Android physical devices, an iPhone 13 Pro and Xiaomi Mi 10T. Let me know how testing goes.

Thanx @briansztamfater. [ISSUE 1](https://github.com/status-im/status-mobile/pull/15543#issuecomment-1500270328) is fixed. 

Though I am still reproducing [ISSUE 2](https://github.com/status-im/status-mobile/pull/15543#issuecomment-1500270421) - max duration for IOS is 2:01 or 2:02 instead of 2:00 (see screenshot and video below):

photo_2023-04-11 10 35 49


https://user-images.githubusercontent.com/97245802/231088999-6017bf6f-cd69-4381-80bd-4e24c8c083b1.mp4

**Comment by briansztamfater** [comment]
@pavloburykh hmm I see. Sometimes it works for me, but sometimes got 2:01 too on iOS. 😕  I will check and try to find a solution. Thanks again for testing.

**Comment by briansztamfater** [comment]
I'll rebase and resume this PR once #15594 gets merged, so we can be sure it is properly tested with the new audio message component

**Comment by churik** [comment]
@briansztamfater 
hey, new composer is already merged, PR can be rebased and tested, thank you!

**Comment by briansztamfater** [comment]
@churik Sure I will resume this one, thanks!

**Comment by briansztamfater** [comment]
@qoqobolo @pavloburykh resumed this PR, should be ready to test now, let me know how testing goes :)

**Comment by pavloburykh** [comment]
@briansztamfater thanx for the PR. Looks good to me. 

Although I have faced one issue which I reproduced only once. 

I think there is no sense to block PR because of it

### ISSUE 1 Audio with duration of 2 minutes is displayed with duration 00:00

Unfortunately there are no clear steps for reproduction. During testing one of the recorded audios appeared to have this bug. 


https://github.com/status-im/status-mobile/assets/97245802/17ac51f6-3abf-41e3-a442-efb16f4c5cd9

**Comment by pavloburykh** [comment]
@briansztamfater please, let me know if re-test will be needed as a result of resolving of new appeared conflicts in src/quo2/components/record_audio/record_audio/__tests__/record_audio_component_spec.cljs
src/quo2/components/record_audio/record_audio/view.cljs

**Comment by flexsurfer** [comment]
hey @briansztamfater still relevant?

**Comment by briansztamfater** [comment]
Yep, will rebase and merge

**Comment by flexsurfer** [comment]
ping @briansztamfater

**Comment by flexsurfer** [comment]
read for merge
