### PR TITLE
Match the changes in collectibles api in status-go

### LINKED ISSUE #17936: Support traits on collectible info page (upgrade to new API)
## Problem 

Traits are implemented in [status-go PR](https://github.com/status-im/status-go/pull/4331) and already supported by collectible info page but switching to that `status-go` version causes mobile app crash after login

### Reproduction

1. switch to status-go PR
2. start Status app

### PR DESCRIPTION
**Pull request by vkjr**
fixes #17936

### Summary

Collectible api was changed by [this status-go PR](https://github.com/status-im/status-go/pull/4290/files).
This PR updates the mobile code to match the changes.

### Review notes
Latest `status-go` commit used, not sure if it is better to use the commit from PR with API changes.

status: ready

### CODE REVIEW

File: src/status_im2/contexts/wallet/collectible/view.cljs [hunk 1]
```diff
@@ -112,9 +112,11 @@
...
 (defn view
   []
-  (let [collectible-details                              (rf/sub [:wallet/last-collectible-details])
-        {:keys [name description preview-url traits id]} collectible-details
-        chain-id                                         (get-in id [:contract-id :chain-id])]
+  (let [collectible                                               (rf/sub
+                                                                   [:wallet/last-collectible-details])
+        {:keys [id collectible-data preview-url collection-data]} collectible
+        {:keys [traits description]}                              collectible-data
+        chain-id                                                  (get-in id [:contract-id :chain-id])]
```
Comment (J-Son89) [inline src/status_im2/contexts/wallet/collectible/view.cljs]: should we have a sub to access this data instead?

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/wallet/collectible/view.cljs (hunk 1 above)
Comment (vkjr) [reply src/status_im2/contexts/wallet/collectible/view.cljs]: good idea, will update it!

File: src/status_im2/contexts/wallet/events.cljs [hunk 2]
```diff
@@ -231,18 +232,37 @@
 
 (rf/reg-event-fx :wallet/store-last-collectible-details store-last-collectible-details)
 
+(def collectible-data-types
```
Comment (ilmotta) [inline src/status_im2/contexts/wallet/events.cljs:247]: It's very helpful during refactors to see private vars with the metadata because then we feel much safer to move things around knowing we're not missing usages. clojure-lsp helps a lot, but I don't fully trust it at all times because it's easy to get in a situation where the cache is stale while changing a lot of code.

File: src/status_im2/contexts/wallet/events.cljs [hunk 3]
```diff
@@ -231,18 +232,37 @@
...
                               [(chain/chain-id db)]
                               (map :address (:profile/wallet-accounts db))
                               collectibles-filter
                               start-at-index
-                              collectibles-request-batch-size]]
-     {:json-rpc/call [{:method     "wallet_filterOwnedCollectiblesAsync"
+                              collectibles-request-batch-size
+                              data-type
+                              fetch-criteria]]
+     {:json-rpc/call [{:method     "wallet_getOwnedCollectiblesAsync"
```
Comment (ilmotta) [inline src/status_im2/contexts/wallet/events.cljs]: I've noticed we are having trouble following the re-frame guideline for using only `:db` and `:fx` in the returned map (https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md#registering-event-handlers). A lot of events in the repo only dispatch one effect (plus maybe the `:db`) so maybe we should relax that guideline. I would prefer if we had only one way of doing something and following re-frame's best practices, but it's tedious to comment in PRs to reinforce this guideline, so realistically speaking we should consider relaxing that guideline if we can't properly enforce it.

**Review by ilmotta — APPROVED** [review]
