### PR TITLE
Fixes for the Community Channel avatar component

### LINKED ISSUE #16327: Incorrect Channel Avatar background
# Problem

Unless my eyes can't see the 10% blue in light mode in my emulator, the Community Channel Avatars are not rendered as in Figma.

## Actual

Background is white or transparent.

## Expected

Background should be a light blue.

## Resources

[Figma > screen example](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-405574&t=aX6zgxCZpQkj548k-0)

[Figma > component](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=399-20709&t=sEa0sBNlpHwxZxzf-0)

### LINKED ISSUE #16332: Fallback to letters when Community Channels don't have emojis
# Bug

Currently, when a _Community Channel_ doesn't have an emoji, an empty circle is displayed. We should fallback to letters, just like in the Desktop app.

### Expected

In Desktop, one letter is used, and we should use that as a reference.

### Reference

[Design System > Channel Avatar](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=399-20709&t=sEa0sBNlpHwxZxzf-0)

### PR DESCRIPTION
**Pull request by ilmotta**
- Fixes https://github.com/status-im/status-mobile/issues/16332
- Fixes https://github.com/status-im/status-mobile/issues/16327

### Summary

Another step on the journey to fix the Community overview screen. This time around, I'm fixing:

- [x] Community channels may not have an emoji, and in such cases, it should fall back to a single letter. The component was recently updated in [Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=399-20709&mode=design&t=UZYVQAGns9IVRxew-0) after this concern was brought up to designers.
- [x] The default (fallback) color to be used in the list of community channels should be the **community color,** not a default `primary-50` as was before. It's a subtle change because the colors are rendered at 10% transparency.
- [x] Rewrote the `channel-avatar` component to follow guidelines. 

### Examples

<table>
  <thead>
    <tr>
        <th>Before</th>
        <th>After</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

### How to test

- Open a community with lots of channels, ideally with a mix of custom colors.
- Check the quo2 preview `avatar` > `channel-avatar`.

### Resources

- [Design System > Avatars > Channel Avatar](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=399-20709&mode=design&t=vt6rTZgV5rgSqgfO-0)
- [Communities for Mobile > Channels](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=12697-455084&mode=design&t=urMJx8grNxPPA59i-0)

status: ready

### CODE REVIEW

File: src/quo2/components/avatars/user_avatar/view.cljs [hunk 1]
```diff
@@ -1,22 +1,9 @@
...
-  (:require [clojure.string :as string]
-            [quo2.components.avatars.user-avatar.style :as style]
+  (:require [quo2.components.avatars.user-avatar.style :as style]
             [quo2.components.markdown.text :as text]
             [react-native.core :as rn]
-            [react-native.fast-image :as fast-image]))
-
-(defn trim-whitespace [s] (string/join " " (string/split (string/trim s) #"\s+")))
-
-(defn- extract-initials
```
Comment (ilmotta) [inline src/quo2/components/avatars/user_avatar/view.cljs:10]: FYI: I needed the same behavior in the other `channel-avatar` component, so I extracted the function, simplified it a little bit and unit tested it.

File: src/quo2/components/list_items/channel.cljs [hunk 2]
```diff
@@ -14,10 +14,11 @@
 
 (defn list-item
   [{:keys [locked? mentions-count unread-messages?
-           muted? is-active-channel? emoji channel-color]
-    :or   {channel-color colors/primary-50}
+           muted? is-active-channel? emoji channel-color
+           default-color]
     :as   props}]
-  (let [standard-props (apply dissoc props custom-props)
+  (let [channel-color  (or channel-color default-color)
```
Comment (ilmotta) [inline src/quo2/components/list_items/channel.cljs:19]: FYI: ClojureScript doesn't allow the default value in `:or` to refer to one of the destructured keys, so I had to do the logic in the `let` macro. I haven't checked if Clojure JVM has this limitation too.

File: src/quo2/components/avatars/channel_avatar/view.cljs [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+  then the default color should be the community custom color.
+
+  :locked? - nil/bool (default nil) - When true/false display a locked/unlocked
+  icon respectively. When nil does not show icon.
+
+  :full-name - string (default nil) - When :emoji is blank, this value will be
+  used to extract the initials.
+
+  :amount-initials - int (default 1) - Number of initials to be extracted
+  from :full-name when :emoji is blank.
```
Comment (ajayesivan) [inline src/quo2/components/avatars/channel_avatar/view.cljs]: I'm skeptical about adding an `int` option to control the number of initial letters.

From my understanding, there are only 2 valid options 1 letter or 2 letters. When I looked at the design what I understood is that when the channel avatar is big we should display 2 letters and when it is small 1 letter.
Screenshot 2023-06-24 at 12 52 59

Also, when displaying two letters on a small avatar the second letter is being cut off in some cases.

File: src/quo2/components/avatars/channel_avatar/style.cljs [hunk 4]
```diff
@@ -0,0 +1,26 @@
+(ns quo2.components.avatars.channel-avatar.style
+  (:require [quo2.foundations.colors :as colors]))
+
+(def lock-icon-size 12)
+
+(defn outer-container
+  [{:keys [big? color]}]
+  {:width            (if big? 32 24)
+   :height           (if big? 32 24)
+   :border-radius    (if big? 32 24)
```
Comment (ibrkhalil) [inline src/quo2/components/avatars/channel_avatar/style.cljs]: Do you think it's worth it to have these values as variables?

File: src/quo2/components/avatars/channel_avatar/style.cljs [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+   :justify-content  :center
+   :align-items      :center
+   :background-color (colors/theme-alpha color 0.1 0.1)})
+
+(defn lock-container
+  [{:keys [big?]}]
```
Comment (ibrkhalil) [inline src/quo2/components/avatars/channel_avatar/style.cljs]: It's only one variable, Why do we need a map?

File: src/utils/string.cljs [hunk 6]
```diff
@@ -38,3 +39,12 @@
...
   (>= (count s) n))
+
+(defn get-initials
+  "Returns `n` number of initial letters from `s`, all uppercased."
+  [s n]
+  (let [words (-> s str string/trim (string/split #"\s+"))]
+    (->> words
+         (take n)
+         (map (comp string/upper-case str first))
+         (string/join))))
```
Comment (ibrkhalil) [inline src/utils/string.cljs]: Omittable parenthesis around `string/join`.

**Review by ibrkhalil — APPROVED** [review]
lgtm 🚀

**Review by ajayesivan — APPROVED** [review]

File: src/quo2/components/avatars/channel_avatar/view.cljs (hunk 3 above)
Comment (yqrashawn) [reply src/quo2/components/avatars/channel_avatar/view.cljs]: there's `size` -> `amount-initials` logic in `user-avatar` https://github.com/status-im/status-mobile/pull/16379/files#diff-89879ff7bdd5d29334dbca769f65209502d91884ecbd9436f99fbd9f4946931bR11
don't know if this applies to `channel-avatar`

File: src/utils/string_test.cljs [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+   ""    nil           1
+   ""    ""            0
+   ""    "ab"          0
+   ""    ""            1
+   "A"   "ab"          1
+   "A"   " ab  "       1
+   "A"   "a b"         1
+   "AB"  "a b"         2
+   "ABC" "a b c d"     3
+   "ABC" " a  b  c  d" 3))
```
Comment (yqrashawn) [inline src/utils/string_test.cljs:19]: maybe add another one `"A" "ab" 2`?

**Review by yqrashawn — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

File: src/quo2/components/avatars/channel_avatar/view.cljs [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+    :number-of-lines     1
+    :ellipsize-mode      :clip
+    :weight              :semi-bold
+    :style               {:color color}}
+   (utils.string/get-initials full-name amount-initials)])
+
+(defn- lock
+  [locked? big?]
+  ;; When `locked?` is nil, we must not display the unlocked icon.
+  (when (boolean? locked?)
```
Comment (cammellos) [inline src/quo2/components/avatars/channel_avatar/view.cljs:23]: I would probably use a keyword instead of `nil/false/true`, maybe a bit less error prone? but I don't feel strongly about it, either is fine, it's well documented in any case, but could be a bit unexpected

Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/view.cljs:23]: I completely agree @cammellos, but this would be a refactor since the original code used a boolean to represent 3 states. I felt the PR was growing more than I wanted.

File: src/utils/string.cljs (hunk 6 above)
Comment (ilmotta) [reply src/utils/string.cljs]: Yeah, you noticed that! I prefer to use parenthesis on multiline args because the code is perfectly aligned, and it carries the same syntax from another Lisp I love, Emacs Lisp. But forget what I said, I'll stop being stubborn, it's in the CSG https://guide.clojure.style/#threading-macros-and-optional-parentheses

File: src/quo2/components/avatars/channel_avatar/style.cljs (hunk 5 above)
Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/style.cljs]: I don't use this criteria to decide when to use a map with functions that are components. I see the map as props, like in React, one argument, one map. But I honestly don't follow this rule by the book, nor do I think others should.

But, as you can see, in this case it's unnecessary, but my own preferences were used in a place where it wasn't needed (not a component).

I'll change it, thanks!

File: src/quo2/components/avatars/channel_avatar/style.cljs (hunk 4 above)
Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/style.cljs]: Sure, it's worth it :)

File: src/quo2/components/avatars/channel_avatar/view.cljs (hunk 3 above)
Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/view.cljs]: > Also, when displaying two letters on a small avatar the second letter is being cut off in some cases.

The cut off with the single letter in Figma is weird and I'll double-check if that's what designers really wanted. The cut off with two letters shouldn't happen, I'll fix this.

> there's size -> amount-initials logic in user-avatar

Yes, I based the solution on the `amount-initials` of the other avatar as you pointed out @yqrashawn. I think what @ajayesivan is saying is that we can use the `big?` parameter as a way to decide if one or two letters should be used. I'll revisit the code and see if I can improve it a bit. Thanks for the review guys.

Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/view.cljs]: The final code is cleaner now after I removed the `amount-initials` parameter, thanks again.

**Comment by ilmotta** [comment]
FYI: This PR is blocked, waiting for the design team to fix the component [Channel Avatar in Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=399-20709&mode=design&t=As17D4fdkFcWD3Gl-0).

**Comment by ilmotta** [comment]
Hi @Francesca-G. This PR is ready go through a design review. I hope the PR's description is sufficient to understand the scope of the work. If not, feel free to ping me here or on Discord. Thanks!

File: src/quo2/components/avatars/channel_avatar/view.cljs [hunk 9]
```diff
@@ -0,0 +1,58 @@
...
+      :style               (style/lock-container big?)}
+     [icons/icon (if locked? :i/locked :i/unlocked)
+      {:color           (colors/theme-colors colors/neutral-50 colors/neutral-40)
+       :container-style style/lock-icon
+       :size            12}]]))
+
+(defn view
+  "Options:
+
+  :big? - bool (default nil) - Container size
```
Comment (J-Son89) [inline src/quo2/components/avatars/channel_avatar/view.cljs]: hmm, should we use actual sizes instead?

File: src/quo2/components/avatars/channel_avatar/view.cljs [hunk 10]
```diff
@@ -0,0 +1,58 @@
...
+  :color - color (default nil) If the component is used for a community channel,
+  then the default color should be the community custom color.
+
+  :locked? - nil/bool (default nil) - When true/false display a locked/unlocked
+  icon respectively. When nil does not show icon.
+
+  :full-name - string (default nil) - When :emoji is blank, this value will be
+  used to extract the initials.
+  "
+  [{:keys [big? emoji color locked? full-name]}]
```
Comment (J-Son89) [inline src/quo2/components/avatars/channel_avatar/view.cljs]: we use `customization-color` in all other components for this. Can we keep it consistent?

**Comment by churik** [comment]
Thank you for calling @Francesca-G 
From the perspective of QA it is ready to merge, this is how it looks now (red is the colour of the community):
Mobile:
IMAGE 2023-07-05 17:42:18
Desktop:
image

**Comment by J-Son89** [comment]
@churik the emoji looks off centre there? 🤔 is this right @ilmotta ?
Screenshot 2023-07-05 at 16 45 03

File: src/quo2/components/avatars/channel_avatar/view.cljs (hunk 10 above)
Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/view.cljs]: Yeah, makes sense.

**Comment by ilmotta** [comment]
> @churik the emoji looks off centre there? 🤔 is this right @ilmotta ? Screenshot 2023-07-05 at 16 45 03

It's obviously not right, but at the same I've never seen this problem in my tests. I'll need to look further.

**Comment by ilmotta** [comment]
Thanks for checking this PR @churik!

**Comment by J-Son89** [comment]
> > @churik the emoji looks off centre there? 🤔 is this right @ilmotta ? Screenshot 2023-07-05 at 16 45 03
> 
> 
> 
> It's obviously not right, but at the same I've never seen this problem in my tests. I'll need to look further.

Perhaps there's an extra space there?

File: src/quo2/components/avatars/channel_avatar/view.cljs (hunk 9 above)
Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/view.cljs]: @J-Son89, if you ask me this question my first instinct is to say yes, because "magic sizes" being passed as arguments are a leaking abstraction IMO. If another designer decides to change a single pixel, many calling sites will need to change. I think the code should be more resilient to arbitrary changes in the design system.

I prefer semantic names, but at the same time, I don't like that each component uses different names to mean different sizes. But man I dislike those 32/20/etc numbers flying around as arguments in the repo...

Comment (J-Son89) [reply src/quo2/components/avatars/channel_avatar/view.cljs]: Yep, I can agree to that. We can leave for now but I think we should figure out a consistent approach some point soon.

My point here was rather than 'big',
having :size with values :big or :small 
But component can be adjust easily if more sizes are added

**Comment by ilmotta** [comment]
@J-Son89, I could only reproduce the centralization issue after adding a whitespace as you correctly guessed. The emoji is definitely centralized without the trailing space. For performance reasons, I'm hesitant to add a call to `string/trim` in the input, also because I think the text should always be trimmed by the backend at write time.

This is what I reproduced by adding a single whitespace at the end.



@churik, do you know if the emoji had any extraneous whitespace? If the emoji text was copied, maybe it was copied in a different encoding and was stored in status-go without any cleanup.

File: src/quo2/components/avatars/channel_avatar/view.cljs (hunk 9 above)
Comment (ilmotta) [reply src/quo2/components/avatars/channel_avatar/view.cljs]: Good suggestion for changing from `big?` to `:size` 👍🏼 I'll apply it now.

> Yep, I can agree to that. We can leave for now but I think we should figure out a consistent approach some point soon.

💯

**Comment by churik** [comment]
@ilmotta I set emoji to channel from Desktop. I can invite you to this community if you share public key with me, and I'll recheck one more time to be sure

**Comment by ilmotta** [comment]
> @ilmotta I set emoji to channel from Desktop. I can invite you to this community if you share public key with me, and I'll recheck one more time to be sure

@churik, in order to save you some time, I'll try to do this verification using the desktop app myself. I'll let you know of the results.

**Comment by Francesca-G** [comment]
> Hi @Francesca-G. This PR is ready go through a design review. I hope the PR's description is sufficient to understand the scope of the work. If not, feel free to ping me here or on Discord. Thanks!

Here's the reviewed [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3271%3A192285&mode=design&t=ixIMCSzgq37t9aYx-1) :)
As you can see I managed to only review the Android PR, the iOS version should be coming in the next few days (once I get my new iPhone all set up). I will leave another comment once that one is ready!

**Comment by ilmotta** [comment]
@churik, @Francesca-G has confirmed the centering issue too. Although I still think something fishy is going on in the way emojis are stored coming from Desktop. Thank you all for reporting, I'll see what I can do.

**Comment by ilmotta** [comment]
@churik, @Francesca-G, @J-Son89, I have reproduced the issue about the emoji spacing if emojis are set using the Desktop app. The problem is actually on the status-go side, because status-go should always clean up text sent from Status' clients before storing it, but since it doesn't, emojis are being stored with an extra right whitespace. Good guess @J-Son89! See screenshot:



I don't think we should fix anything on the mobile side because the bug is on the data itself. I can create an issue on GitHub for status-go and fix it there.

@Francesca-G, as we talked in private, I'll create other GitHub issues based your feedback in Figma. Specifically about this PR's scope, I don't see any other feedback I can work on. Could you approve this PR if there's nothing else in scope to fix?

**Comment by Francesca-G** [comment]
> @churik, @Francesca-G, @J-Son89, I have reproduced the issue about the emoji spacing if emojis are set using the Desktop app. The problem is actually on the status-go side, because status-go should always clean up text sent from Status' clients before storing it, but since it doesn't, emojis are being stored with an extra right whitespace. Good guess @J-Son89! See screenshot:
> 
> 
> I don't think we should fix anything on the mobile side because the bug is on the data itself. I can create an issue on GitHub for status-go and fix it there.
> 
> @Francesca-G, as we talked in private, I'll create other GitHub issues based your feedback in Figma. Specifically about this PR's scope, I don't see any other feedback I can work on. Could you approve this PR if there's nothing else in scope to fix?

Sure! And thank you for creating the separate issues :)

**Review by Francesca-G — APPROVED** [review]
