### PR TITLE
Layout updates/fixes for pinned messages bar

### LINKED ISSUE #16089: Messaging - In chat - Pinned messages ui bugs
See photo of app (left) vs designs (right)
Posts__Attachments_for_Mobile_Figma_2023-05-30_13-57-25

- pinned message banner should be transparent with blur 
- pinned message icon needs to be adjusted
- should show counter, even if only 1 pinned message

designs:
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=2215-106934&t=GEOti7l3Z5VTvbDA-0

### PR DESCRIPTION
**Pull request by alwx**
1) Adds blurred background for pinned messages banner
2) Adds the counter (or rather makes sure it's always there)
3) The icons were actually correct, we decided that it should always be a rounded pin icon (cc @pedro-et)

Screenshot_20230605-111507

Fixes https://github.com/status-im/status-mobile/issues/16089

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/navigation/style.cljs [hunk 1]
```diff
@@ -17,33 +16,47 @@
...
+   :height           navigation-bar-height
+   :background-color (colors/theme-colors colors/white-opa-70 :transparent)
+   :display          :flex
+   :flex-direction   :row
+   :overflow         :hidden})
+
+(defn animated-background-view
+  [enabled? animation]
+  (reanimated/apply-animations-to-style
+   (when enabled?
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/navigation/style.cljs]: We can probably check for `enabled?` around the `apply-animations-to-style`, so that if `enabled?` is false there's no need to call the reanimated hook.

File: src/status_im2/contexts/chat/messages/pin/banner/style.cljs [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+   :left     0
+   :right    0
+   :top      top-offset})
+
+(defn animated-pinned-banner
+  [top-offset enabled? animation]
+  (reanimated/apply-animations-to-style
+   (when enabled?
+     {:opacity animation})
+   (pinned-banner top-offset)))
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/pin/banner/style.cljs:41]: Quick one https://guide.clojure.style/#terminate-files-with-a-newline

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/navigation/style.cljs (hunk 1 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/navigation/style.cljs]: it would lead to issues with hooks — after the re-render you need to have the same amount of hooks

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/navigation/style.cljs]: Oh that's right, this is super important.

**Comment by pavloburykh** [comment]
@alwx thanx for the PR. Please take a look at the following issues: 

### ISSUE 1 Cannot move cursor/call context menu inside composer [ANDROID]

Reproduced on Andrdoid 12, Samsung Galaxy A52

**Steps:** 

1. Open chat
2. Focus on input field, type some text
3. Try to move cursor/call context menu to select/copy/paste text

**Actual result:** cannot move cursor/call context menu inside composer 


https://github.com/status-im/status-mobile/assets/97245802/24c9fc35-7d51-46f5-93f1-972a262ff997

**Comment by pavloburykh** [comment]
### ISSUE 2 Mention suggestion list is not visible when composer is fully expanded

**Steps:** 

1. Open chat
2. Expand composer
3. Type @ to call mention suggestion list
4. Pay attention if list is visible

**Actual result:** list is not visible, as it is located above the expanded composer. 


https://github.com/status-im/status-mobile/assets/97245802/7799cfde-1f92-497c-b58a-19249a53e5ef


**Expected result:** I am not sure what is expected result in this case. Need input from @status-im/design-team

**Comment by pavloburykh** [comment]
### ISSUE 3 Sometimes top bar/pin banner are not shown after opening chat until user scrolls scren/focuses on chat input

**Steps:** 

1. Open a new chat (do not use the old one) 
2. Generate some chat history until top bar appears
3. Close chat
4. Re-open chat
5. See if top bar is shown

**Actual result:** sometimes top bar/pin banner are not show after opening chat until user scrolls scren/focuses on chat input. See video below


https://github.com/status-im/status-mobile/assets/97245802/59cb385e-6a37-4631-98fb-08330d922d42

**Comment by pavloburykh** [comment]
### ISSUE 4 Mentions suggestion list is not scrollable [Andrdoid]

Reproduced on Android 12, Samsung A52

**Preconditions:** User is a member of community/group with lot of memberes (in order to be able to generate scrollable mention list)

**Steps:** 

1. Open commubnity channel/group chat
2. Type @ to call mentions list
3. Try to scroll through the list
4. Observe the result

**Actual result:** unable to scroll though the mentions list


https://github.com/status-im/status-mobile/assets/97245802/916c8ebc-0a5c-458c-a632-4fa1929f95b6

**Comment by pavloburykh** [comment]
### ISSUE 5 Pin bar color differs from the design

**Actual result:** 

**IOS:** looks close to the design
photo_2023-06-06 18 59 03

**Android:** is darker than on design
photo_2023-06-06 18 59 06

**Expected result:** 

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3425-413560&t=6AGYbwlWUktZTTRE-0

Posts   Attachments for Mobile – Figma 2023-06-06 18-56-49

**Comment by alwx** [comment]
@pavloburykh please recheck!

I've for sure fixed the composer stuff that was introduced in this PR (the issues that are about mentions/suggestions being not visible due to incorrect z-index) & I also fixed the color of pinned messages bar (it might be slightly different on Android anyway just because the library for the blur works differently there, and we can do nothing about that)

Issue 3 has nothing to do with this particular PR though — better to document it somewhere else. I also cannot say much about the composer — this PR *only* updates the z-index of the composer relative to the top bar. If something is wrong with the composer and if something is broken in its functionality then it should be documented somewhere else, and I have no detailed knowledge about the composer because it was not me who was working on it.

**Comment by pavloburykh** [comment]
hi @alwx ! Have you got a chance to look at [ISSUE 4](https://github.com/status-im/status-mobile/pull/16179#issuecomment-1579043773)? It is still reproducible and it is highlikely introduced by this PR as I am not reproducing it in develop branch. 

On the video below I am switching between latest nightly build and latest PR build. You can observe that scrolling mentions list in PR build results in scrolling chat history instead mentions list. At the same time nightly build works fine. We neeed to address it in this PR otherwise a new bug will be introduced to develop. 


https://github.com/status-im/status-mobile/assets/97245802/7cfe3bc2-1bf8-449b-8732-3d1d7432e466

**Comment by pavloburykh** [comment]
@alwx the same situation has [ISSUE 1](https://github.com/status-im/status-mobile/pull/16179#issuecomment-1579029818)

On the video below you can observe that the bug is not reproducible in nightly build but reproducible in current PR. So we need to address it here otherwise a new issue will be introduced to develop. 

https://github.com/status-im/status-mobile/assets/97245802/ebba02a4-ba6e-4c9f-9e39-921017173917

**Comment by pavloburykh** [comment]
> If something is wrong with the composer and if something is broken in its functionality then it should be documented somewhere else, and I have no detailed knowledge about the composer because it was not me who was working on it.

@alwx I understand your consern. But as you see according to the videos above - some of composer bugs have been introduced by this PR. As I am not aware of technical part I can propose to discuss it with the team and ask for help someone who has experience working with composer. WDYT? 

cc @cammellos cc @flexsurfer cc @OmarBasem

**Comment by OmarBasem** [comment]
> If something is wrong with the composer and if something is broken in its functionality then it should be documented somewhere else

All features of the composer was QA tested before merging, and as @pavloburykh mentioned it is working on nightly, so there doesn't seem to be something wrong with the composer. This issue is introduced from this PR. We can see what's wrong and fix it. It could be something with z-indexes.

File: src/status_im2/contexts/chat/composer/style.cljs [hunk 3]
```diff
@@ -77,6 +77,10 @@
                                   (if link-previews? constants/links-container-height 0)
                                   (if (seq images) constants/images-container-height 0))
           :padding-bottom      (when @maximized? 0)}))
+
+(def container
+  {:z-index 5})
+
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/style.cljs]: @alwx the newly introduced issues are from the `z-index`. You can revert it for now and I will look into it in another issue to not block other fixes

Comment (alwx) [reply src/status_im2/contexts/chat/composer/style.cljs]: Ok, will leave it up to you to fix the positioning

**Comment by alwx** [comment]
Ok, @OmarBasem and @pavloburykh, removing the positioning fix from here, now it has absolutely nothing to do with the positioning and composer. Let's merge the pinned messages fixes if they are fine to not block other fixes that depend on it.

**Comment by pavloburykh** [comment]
@alwx ready for merge.
