### PR TITLE
Fix: Messages/Author component overflow

### LINKED ISSUE #17217: Long Nicknames and display names overlap other chat elements
### Steps:
1. `User A` sets a nickname for `User B`
2. `User A` checks the following places
3. `User B` sends a message to `User A`
4. `User A` checks in the following places:
  - In first line of message
  - In the chat preview
  - Contacts tab
  - 'new chat' overlay

### Actual result: 
Nickname overlaps the display name in the following places:
-  In first line of message
image
-  In the chat previewimage
- Contacts tab
image
- 'new chat' overlay
image

### Expected result: 
The display name should be shown in the right part after the nickname.
image

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #17217

### Summary
This PR addresses the issue where the author component content wraps to the next line. The resolution involves truncating the 'name' and 'nickname' properties when a user has an excessively long name or nickname that cannot be displayed in a single line along with other elements of the author component.

Also, the max length of the nickname has been updated from 32 to 24 characters.

Component Design: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=3155-49848&mode=design&t=jKNZPvqSUr16cw4d-4

Usages with Long Nickname & Name: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1731-399787&mode=design&t=BLuW5gDHsKo5Pjpi-4

### Testing notes
Nickname truncation will stop once the width of the nickname reaches 40px. Beyond this point, we will initiate truncation of the 'name' property.

Relevant message from the designer(Mario): https://discord.com/channels/624634427930312714/928625369542713396/1153355805496709211

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
Places where the author component is used
- Chat list
- Chat messages
- Contacts page

status: ready

### CODE REVIEW

File: src/quo2/components/messages/author/style.cljs [hunk 1]
```diff
@@ -2,30 +2,44 @@
...
+  [muted? theme]
+  {:color       (if muted?
+                  colors/neutral-50
+                  (colors/theme-colors colors/neutral-100 colors/white theme))
+   :flex-shrink 1})
+
+(defn secondary-name
+  [theme]
+  {:padding-top 1
+   :flex-shrink 999999
```
Comment (ajayesivan) [inline src/quo2/components/messages/author/style.cljs]: The requirement is to truncate the nickname(secondary-name) and stop truncation when it reaches a width of 40px. Subsequently, we begin truncating the name. While this approach may not be flawless, setting a high flex-shrink value causes the nickname to shrink at a faster rate. Based on my testing, this results in the name starting to truncate when the nickname reaches the min-width(40px).

If you have any alternative suggestions to address this issue, please feel free to share.

File: src/quo2/components/list_items/user_list.cljs [hunk 2]
```diff
@@ -49,8 +48,8 @@
      :profile-picture photo-path
      :online?         online?
      :size            :small}]
-   [rn/view {:style {:margin-left 8}}
-    [author/author
+   [rn/view {:style {:margin-horizontal 8 :flex 1}}
```
Comment (ibrkhalil) [inline src/quo2/components/list_items/user_list.cljs]: Should this be in a style.cljs file?

File: src/status_im/ui/screens/profile/contact/views.cljs [hunk 3]
```diff
@@ -131,7 +133,7 @@
          {:style {:align-self :flex-end
                   :margin-top 16
                   :color      colors/gray}}
-         (str (count @entered-nickname) " / 32")]]
+         (str (count @entered-nickname) " / " nickname-max-length)]]
```
Comment (ibrkhalil) [inline src/status_im/ui/screens/profile/contact/views.cljs]: Are we sure we are always going to use english numbers?
I mean, Should this be using i18n?

File: src/quo2/components/list_items/user_list.cljs (hunk 2 above)
Comment (ajayesivan) [reply src/quo2/components/list_items/user_list.cljs]: The current implementation of user-list component is not using the view, style file structure. I have created a separate issue to track the refactor: https://github.com/status-im/status-mobile/issues/17415

File: src/status_im/ui/screens/profile/contact/views.cljs (hunk 3 above)
Comment (ajayesivan) [reply src/status_im/ui/screens/profile/contact/views.cljs]: We are using this approach to display numbers in various contexts. For instance, we follow a similar pattern in the title input component. Additionally, even in cases where the displayed text includes numbers, we typically pass the actual number value directly from the code. For example: https://github.com/status-im/status-mobile/blob/9479f02b39c0d7b8c53c0b6160f553df77f5acdc/translations/en.json#L2133

**Review by clauxx — APPROVED** [review]
lgtm, but i noticed that the author component initials are not visible with the dark theme. Not sure if related or if there's already an issue for this.

**Comment by ajayesivan** [comment]
> i noticed that the author component initials are not visible with the dark theme

@clauxx Could please share on which screen you are facing this issue and if possible a screenshot.

**Comment by clauxx** [comment]
> > i noticed that the author component initials are not visible with the dark theme
> 
> @clauxx Could please share on which screen you are facing this issue and if possible a screenshot.

it was in the preview for `:list-items/user-list`

**Comment by ajayesivan** [comment]
@clauxx Thanks for the review and sharing the screenshots. It's a pre-existing issue related to the usage of `user-avatar` component. A related issue is already tracked here: https://github.com/status-im/status-mobile/issues/17208

File: src/status_im/ui/screens/profile/contact/views.cljs [hunk 4]
```diff
@@ -18,6 +18,8 @@
             [utils.i18n :as i18n]
             [utils.re-frame :as rf]))
 
+(def ^:private nickname-max-length 24)
```
Comment (smohamedjavid) [inline src/status_im/ui/screens/profile/contact/views.cljs]: It's good to have this var placed in `status-im2.constants` ns.

Additionally, we have an existing constants `profile-name-max-length` which holds the same value `24`. Not sure if this is the same.

Comment (ajayesivan) [reply src/status_im/ui/screens/profile/contact/views.cljs]: As mentioned by John [here](https://discord.com/channels/624634427930312714/928625369542713396/1151464141735870544). Max length is the same for both profile name & nickname. @smohamedjavid I have updated the code to use `profile-name-max-length` here too.

Comment (smohamedjavid) [reply src/status_im/ui/screens/profile/contact/views.cljs]: Thank you @ajayesivan! 🚀

**Comment by yqrashawn** [comment]
> lgtm, but i noticed that the author component initials are not visible with the dark theme. Not sure if related or if there's already an issue for this.

It should be fixed in https://github.com/status-im/status-mobile/pull/17430

**Comment by VolodLytvynenko** [comment]
Hi @ajayesivan thank you for PR. Here are a found issues:

## ISSUE 1: The maximum length for a nickname is still 32 characters when setting it up within a 1-1 chat, instead of the expected 24 characters.

### Steps:
1. Open 1-1 chat -> tap 3 dots '...' in right corner
2. Set up nickname with more than 24 characters

### Actual result:
the nickname can be set with up to 32 characters when setting it up within a 1-1 chat. 

image

### Expected result:
Nickname is set up with 24 character

**Comment by VolodLytvynenko** [comment]
Not sure if this issue is within the scope of this PR. Should we address it here, or would it be better to fix it in a separate follow-up?

## ISSUE 2: The contact badge is not shown in a 1-1 chat if a user has a long ENS or display name.

### Steps:
1. `User A` Set up a long display name during onboarding
2. `User B` open 1-1 chat with `User A`
3. `User B` check name of `User A` in upper area of opened 1-1 chat

### Actual result:
In a 1-1 chat, when a user has a long ENS or display name, the contact badge is not displayed. 

image


### Expected result:
The contact badge should still be displayed

image

**Comment by ajayesivan** [comment]
@VolodLytvynenko I have fixed both the issues. Could you please test again.

Thanks!

**Comment by VolodLytvynenko** [comment]
Hi @ajayesivan thank you for the fixes. No issues from my side


Hi @Francesca-G could you please review this PR? If you don't have a user with a long ENS name to check how long ENS names are truncated, you can use the following seed phrase: `fatigue inquiry accident utility today tone renew steak lawn reject found lawn` for recovery. Please note that the recovered user with ENS will be resolved only after at least 1 message is sent in a 1-1 chat and at least 1-2 minutes of waiting.

Let me know if you need any help with the recovery of user with the current ENS or anything else related to this PR

**Review by Francesca-G — COMMENTED** [review]
Here's the [design review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6338%3A50422&mode=design&t=cf6XAwavgbnOhVOW-1) :)

**Comment by ajayesivan** [comment]
Fixed all design review issues except the following one,
Screenshot 2023-10-11 at 09 48 36

It seems like an issue with the React Native Text Component. I will investigate further and update here.

**Comment by ajayesivan** [comment]
Followup issue: https://github.com/status-im/status-mobile/issues/17684
