### PR TITLE
Input fixes (#1067, #676), #1110

### LINKED ISSUE #676: No automatic scroll to cursor location for long messages
When a user types a long message, there is no automatic scroll to the cursor location (so that the focus remains on the text just typed).

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/83

### LINKED ISSUE #1067: Keyboard is not shown if tap on input field with several lines of text
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Input field contains several lines of text. If tap on chat then keyboard is hidden. If tap on the text then keyboard is not shown (this is issue). Only if tap on the end of the last line then keyboard is shown. Text:
Short line [my comment: hit Enter to go to next line]
Next line started after hit enter and goes to the new line without any enter  [my comment: hit Enter to go to next line]
This is again started with enter and goes to new line without enter

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If tap on any place in the input field then keyboard is shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
If tap on the text of several lines then keyboard is not shown. Only if tap on the end of the last line then keyboard is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7MHNWbXNXOGhFejA
- Open Status
- Open 1-1 chat
- Type text as in description. Do not type comments in []
- Tap on chat screen. Keyboard will be hidden
- Tap on first or second lines of the text. Expected: Keyboard is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6d76
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by alwx**
React Native 0.40+ gave us an ability to fix #676 because the blocking issue (https://github.com/facebook/react-native/issues/6552) has been resolved.

This PR also fixes #1067 by adding an `input-touch-handler` and #1110 by cleaning data on re-login.

All these issues are related to input text, so I decided to create one single PR instead of several ones.

### CODE REVIEW

File: src/status_im/chat/handlers.cljs [hunk 1]
```diff
@@ -223,12 +221,23 @@
...
     (assoc db :loaded-chats (chats/get-all))))
 
-;TODO: check if its new account / signup status / create console chat
 (register-handler :initialize-chats
   [(after #(dispatch [:load-unviewed-messages!]))
    (after #(dispatch [:load-default-contacts!]))]
   ((enrich initialize-chats) load-chats!))
 
+(register-handler :reload-chats
+  [{:keys [chats] :as db} _]
```
Comment (rasom) [inline src/status_im/chat/handlers.cljs]: `(fn ... )` is missed

Comment (alwx) [inline src/status_im/chat/handlers.cljs]: This PR is not finished yet :) It's marked as "in progress", and has one known issue.

**Comment by alwx** [comment]
Now it's done.

**Comment by annadanchenko** [comment]
Issue: If tap on first line of the text in input field then cursor does not move to the place of tap, as expected. If long tap on word in a first line then menu "Select All.." is not shown. In both cases, cursor stays on its place. If perform same actions on second line in the input text then it works fine.

**Comment by annadanchenko** [comment]
Can't verify that #1067 is fixed in this PR because #1057 is not included in the build (or does not work - if tap on chat then keyboard is not hidden)

**Comment by alwx** [comment]
The code has been updated. Please, check it.

**Comment by annadanchenko** [comment]
testing new build

**Comment by annadanchenko** [comment]
1. #1067 verified OK on iOS. On Android it's not applicable.
2. Issue "If tap on first line of the text in input field then cursor does not move to the place of tap" verified OK on both Android and iOS

### Issue
4th line is not visible if proceed typing, user need to scroll to it. Issue is only on Android, iOS is fine.
Steps:
1. In 1-1 chat start typing any text so it goes to 4th line.
Currently: third line is shown, 4th line is not visible but typed text is there
Expected: 4th line is visible 
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7WEhrZnpIc3lGZlk

**Comment by alwx** [comment]
@annadanchenko see the last build, I've fixed it

**Comment by annadanchenko** [comment]
@alwx Issues 1 "4th line is not visible if proceed typing" and 2 "2nd line text is cut in the bottom" are OK now. 
New issue (didn't check it before) but it does not exist in today's develop build:
If text keyboard is opened and 
1. long tap on text in the chat to get "Copy" menu - nothing happens except keyboard is hidden.
2. tap on "Requesting X ETH" then /send is not shown with numeric keyboard. Instead, text keyboard is hidden. So, user need to tap again on  "Requesting X ETH" to get /send X in input field.
It looks like on any tap in chat, text keyboard is hidden but these 2 cases above need special handling
