### PR TITLE
fix: wrong color stroke in profile setting

### LINKED ISSUE #19300: Wrong color stroke around the avatar in Profile settings [Android]
# Design Feedback 2.27

## [Android] Stroke around the avatar in Profile setting has wrong color
**Stroke** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#719375463)] around the user avatar has a different color than the rest of the card. The problem is also visible when scrolling [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#719381744)]: the lighter colored stroke stays around the user avatar picture as it gets smaller

Screenshot 2024-03-18 alle 09 59 45

Screenshot 2024-03-18 alle 10 00 10

#### Expected behavior

Screenshot 2024-03-18 alle 10 00 57

Screenshot 2024-03-18 alle 10 02 22

### Reproduction

1. Open the profile settings by tapping the avatar picture at the bottom left of the screen
2. Scroll the profile settings

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by codemaster115**
fixes #19300 

### Summary

Stroke around the avatar in profile setting is wrong.

#### Platforms
- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

### Steps to test

1. Open the profile settings by tapping the avatar picture oon the top-left of the screen
2. Scroll the profile settings

### Before and after screenshots comparison
Simulator Screenshot - iPhone 13 - 2024-04-26 at 05 28 52

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]
Thank you for the great work!

**Review by mohsen-ghafouri — APPROVED** [review]
I understand it's a bit tricky because the border needs to be both blurred and transparent, which can be challenging to achieve. Simulating the border color to match the background also seems difficult. Overall, LGTM :) nice work

File: src/status_im/navigation/view.cljs [hunk 1]
```diff
@@ -71,7 +71,7 @@
            background-color            (or (get-in options [:layout :backgroundColor])
                                            (when sheet? :transparent))
            app-theme                   (rf/sub [:theme])
-           theme                       (or theme app-theme)]
+           theme                       (or app-theme theme)]
```
Comment (flexsurfer) [inline src/status_im/navigation/view.cljs]: screen theme should have a priority

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/contexts/profile/settings/header/view.cljs [hunk 2]
```diff
@@ -42,22 +42,24 @@
...
-                                         :theme   :dark
-                                         :content (fn [] [visibility-sheet/view])}])}
-        status-title]]]
-     [quo/text-combinations
-      {:title-accessibility-label :username
-       :container-style           style/title-container
-       :emoji-hash                emoji-string
-       :description               bio
-       :title                     full-name}]]))
+      [quo.theme/provider :dark
```
Comment (flexsurfer) [inline src/status_im/contexts/profile/settings/header/view.cljs]: no need to have provider :dark here because the screen has a dark theme

**Comment by VolodLytvynenko** [comment]
Hey @codemaster115 . Thank you for PR. Take a look at the found issue

## PR_ISSUE 1: Wrong UI on shell screens when light mode is enabled
### Actual result:
Activity Center
image
Sync QR generation page
image
Wallet share QR page
image

### Expected result:
[Activity Center](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=3652-456275&mode=design&t=q0VW3vGaLQ9MeIYs-0)
[Sync QR generation page](https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-178207&mode=design&t=BR9fpZCFZPjOfJrJ-0)
[Wallet share QR page](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=8994-38139&mode=design&t=q0VW3vGaLQ9MeIYs-0)

File: src/status_im/navigation/view.cljs (hunk 1 above)
Comment (codemaster115) [reply src/status_im/navigation/view.cljs]: But if so, I think it's impossible to resolve this issue since the screen has to use the app theme(light or dark) for the avatar component.
Do we have a solution to use both of them at the same time?

Comment (flexsurfer) [reply src/status_im/navigation/view.cljs]: you can use `(rf/sub [:theme])`

Comment (codemaster115) [reply src/status_im/navigation/view.cljs]: Aha, that makes sense.

**Review by flexsurfer — APPROVED** [review]

**Comment by codemaster115** [comment]
> Hey @codemaster115 . Thank you for PR. Take a look at the found issue
> 
> ## PR_ISSUE 1: Wrong UI on shell screens when light mode is enabled
> ### Actual result:
> Activity Center image Sync QR generation page image Wallet share QR page image
> 
> ### Expected result:
> [Activity Center](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=3652-456275&mode=design&t=q0VW3vGaLQ9MeIYs-0) [Sync QR generation page](https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-178207&mode=design&t=BR9fpZCFZPjOfJrJ-0) [Wallet share QR page](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=8994-38139&mode=design&t=q0VW3vGaLQ9MeIYs-0)

@VolodLytvynenko Please check again. Thanks

**Comment by VolodLytvynenko** [comment]
Hi @codemaster115 thank you for quick issue fix :) No issues from my side

@Francesca-G could you please take a look current PR?

**Review by Francesca-G — COMMENTED** [review]
Stoke color looks fixed, but now it seems like the alignment between the avatar picture and the name is off

As you can see here:

Screenshot 2024-05-01 alle 15 02 32

>
Design:

Screenshot 2024-05-01 alle 15 02 51

**Review by Francesca-G — APPROVED** [review]
