### PR TITLE
chore: first pass at fixing collectibles transition

### LINKED ISSUE #19678: Follow-up: Add Animation to New Collectible UI
# Feature Issue

The transition of changing the state of collectible from loading to showing the actual collectible is very quick. There should be an animation for it.

#19140 
Follow up ticket for #19528

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/19678

This pr smoothes the transition for the collectibles cards loading to a loaded image.

On implementing I realised there is an issue when the image is already loaded as the image is cached and will load quite quickly anyway. To handle this I am measuring the load time. This works fine if the user only has a small number of images.

With help from @ulisesmac we also discovered a bug where the collectibles were re rendering a lot on scroll. This is also addressed in this pr and the overall scrolling experience is a lot smoother now.

Latest reference video:

https://github.com/status-im/status-mobile/assets/22799766/7ae86321-c672-4bdc-9d92-7b3a652c53e0

Note: The animations being slower looks better for one load, but if the user goes back and forth from the tabs several times then it just becomes a bit irritating after a while.

### CODE REVIEW

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 1]
```diff
@@ -54,56 +64,83 @@
...
+                                   {:aspect-ratio 1})}
          [rn/image
-          {:style       style/image
-           :on-load-end #(set-state (fn [prev-state] (assoc prev-state :image-loaded? true)))
-           :on-error    #(set-state (fn [prev-state] (assoc prev-state :image-error? true)))
+          {:style      style/image
+           :on-load-start #(set-load-time (fn [start-time] (- (datetime/now) start-time)))
+
+
+           :on-load-end (if (> load-time 200)
```
Comment (shivekkhurana) [inline src/quo/components/profile/collectible_list_item/view.cljs]: `on-load-start` and `on-load-end` can be moved to external functions. It has readability benefits and the potential to save renders.

**Comment by shivekkhurana** [comment]
The image transition is almost perfect. Made me feel that we somehow loaded colors before hand. 

The name and the logo seem to flicker in. A skeleton there will be nice too.

**Comment by J-Son89** [comment]
> The image transition is almost perfect. Made me feel that we somehow loaded colors before hand. 
> 
> 
> 
> The name and the logo seem to flicker in. A skeleton there will be nice too.

Thanks, will add that!

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: Yep for sure, I will add those types of details once I'm happy with the approach. This was just first pass 👌

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 2]
```diff
@@ -121,30 +170,43 @@
 (defn- image-view
   [{:keys [avatar-image-src community? counter state set-state
            gradient-color-index image-src supported-file?]}]
-  (let [theme (quo.theme/use-theme)]
+  (let [theme                     (quo.theme/use-theme)
```
Comment (J-Son89) [inline src/quo/components/profile/collectible_list_item/view.cljs:173]: I manually tested this for type image as well 👍

File: src/status_im/config.cljs [hunk 3]
```diff
@@ -105,23 +105,6 @@
 (def fast-create-community-enabled?
   (enabled? (get-config :FAST_CREATE_COMMUNITY_ENABLED "0")))
 
-(def default-multiaccount
```
Comment (J-Son89) [inline src/status_im/config.cljs:108]: unused 👍

File: src/status_im/contexts/wallet/common/collectibles_tab/view.cljs [hunk 4]
```diff
@@ -48,17 +49,25 @@
...
-        :num-columns              2
-        :render-fn                (fn [item index]
-                                    (render-fn item
-                                               index
-                                               current-account-address
-                                               on-collectible-press
-                                               on-collectible-long-press))
-        :on-end-reached           on-end-reached
-        :on-end-reached-threshold 4}])))
+      ;; TODO:
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/common/collectibles_tab/view.cljs]: @ulisesmac - what to do here, should we create a follow up issue? 🤔

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 5]
```diff
@@ -10,13 +10,39 @@
...
+    [utils.datetime :as datetime]
     [utils.i18n :as i18n]))
 
+(def timing-options-out 650)
+(def timing-options-in 1000)
+
+(defn on-load-end
+  [{:keys [load-time set-state loader-opacity image-opacity]}]
+  (reanimated/animate-shared-value-with-timing loader-opacity 0 timing-options-out :easing1)
+  (reanimated/animate-shared-value-with-timing image-opacity 1 timing-options-in :easing1)
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: Could be changed to
```
(reanimated/animate loader-opacity 0 timing-options-out)
(reanimated/animate image-opacity 1 timing-options-in)
```

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 6]
```diff
@@ -10,13 +10,39 @@
...
+                    (assoc prev-state :image-loaded? true))))
+     500)
+    (set-state (fn [prev-state]
+                 (assoc prev-state :image-loaded? true)))))
+
+(defn on-load-error
+  [set-state]
+  (js/setTimeout (fn []
+                   (set-state (fn [prev-state] (assoc prev-state :image-error? true))))
+                 800))
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: Some magic numbers not defined (200, 500, 800)

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 7]
```diff
@@ -10,13 +10,39 @@
...
+
 (defn- fallback-view
-  [{:keys [label theme]}]
-  [rn/view
-   {:style (style/fallback {:theme theme})}
+  [{:keys [label theme image-opacity]}]
+  [reanimated/view
+   {:style (reanimated/apply-animations-to-style
+            {:opacity image-opacity}
+            (style/fallback {:theme theme}))}
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: Our guideline for `apply-animations-to-style` is to use it in the `style` file

Also we made a recent update to support passing an array of styles instead of using `apply-animations-to-style` https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md#pass-a-vector-of-styles-to-reanimated-view

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 8]
```diff
@@ -34,16 +60,20 @@
...
-  [gradients/view
-   {:theme           theme
-    :container-style (style/loading-image theme)
-    :color-index     gradient-color-index}])
+  [{:keys [theme gradient-color-index loader-opacity]}]
+  [reanimated/view
+   {:style (reanimated/apply-animations-to-style
+            {:opacity loader-opacity}
+            (style/loading-image theme))}
+   [gradients/view
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: same here regarding `reanimated/apply-animations-to-style`

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 9]
```diff
@@ -34,16 +60,20 @@
...
+    {:theme           theme
+     :container-style (style/loading-image theme)
+     :color-index     gradient-color-index}]])
 
 (defn- card-details
-  [{:keys [community? avatar-image-src collectible-name theme state set-state]}]
+  [{:keys [community? avatar-image-src collectible-name theme state set-state image-opacity]}]
   [rn/view {:style style/card-details-container}
-   (cond (not (:avatar-loaded? state))
+   (cond (and not community? (not (:avatar-loaded? state)))
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: Shouldn't this `not` be inside paranthesis `()` ?

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 10]
```diff
@@ -54,64 +84,83 @@
            {:type :communities
             :size :size-20}
            [avatar-image-src]]
-          [rn/view {:style {:width 8}}]
+
+          [reanimated/view
+           {:style (reanimated/apply-animations-to-style
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: same here regarding `reanimated/apply-animations-to-style`

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 11]
```diff
@@ -54,64 +84,83 @@
...
-    [text/text
-     {:size            :paragraph-1
-      :weight          :semi-bold
-      :ellipsize-mode  :tail
-      :number-of-lines 1
-      :style           style/card-detail-text}
-     collectible-name]]])
+           collectible-name]]
+         :else [reanimated/view
+                {:style (reanimated/apply-animations-to-style
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: same here regarding `reanimated/apply-animations-to-style`

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 12]
```diff
@@ -54,64 +84,83 @@
...
 
 (defn- card-view
   [{:keys [avatar-image-src collectible-name community? counter state set-state
            gradient-color-index image-src supported-file?]}]
-  (let [theme (quo.theme/use-theme)]
+  (let [theme                     (quo.theme/use-theme)
+        loader-opacity            (reanimated/use-shared-value (if supported-file? 1 0))
+        image-opacity             (reanimated/use-shared-value (if supported-file? 0 1))
+        [load-time set-load-time] (rn/use-state (datetime/now))
+        supported-file-styles     (reanimated/apply-animations-to-style
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: Same `reanimated/apply-animations-to-style`

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 13]
```diff
@@ -121,30 +170,43 @@
 (defn- image-view
   [{:keys [avatar-image-src community? counter state set-state
            gradient-color-index image-src supported-file?]}]
-  (let [theme (quo.theme/use-theme)]
+  (let [theme                     (quo.theme/use-theme)
+        loader-opacity            (reanimated/use-shared-value (if supported-file? 1 0))
+        image-opacity             (reanimated/use-shared-value (if supported-file? 0 1))
+        [load-time set-load-time] (rn/use-state (datetime/now))
+        supported-file-styles     (reanimated/apply-animations-to-style
```
Comment (OmarBasem) [inline src/quo/components/profile/collectible_list_item/view.cljs]: Same `reanimated/apply-animations-to-style`

File: src/status_im/contexts/wallet/common/collectibles_tab/style.cljs [hunk 14]
```diff
@@ -4,3 +4,7 @@
 (def list-container-style
   {:margin-horizontal 12
    :padding-bottom    constants/floating-shell-button-height})
+
+(def collectible-container
+  {:padding 8
+   :width   "50%"})
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/common/collectibles_tab/style.cljs]: Could `flex` work here? (maybe `:flex 0.5`)

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 10 above)
Comment (ajayesivan) [inline src/quo/components/profile/collectible_list_item/view.cljs]: Under the hood, `reanimated/apply-animations-to-style` uses a hook.
https://github.com/status-im/status-mobile/blob/3c4f72c061bb697e3e0a973898f87275beeb2a98/src/react_native/reanimated.cljs#L120-L123
Here, we are calling it inside a condition, which is not ideal and can cause issues (see [Rules of Hooks](https://react.dev/reference/rules/rules-of-hooks)).

You are likely familiar with the hook rules, but the current function name doesn't indicate that it involves a hook.

I believe we decided to rename the function so that it starts with `use-`. cc: @Parveshdhull, @ulisesmac

Comment (Parveshdhull) [reply src/quo/components/profile/collectible_list_item/view.cljs]: > and can cause issues

Probably can throw error like https://github.com/status-im/status-mobile/issues/16140

Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: good point @ajayesivan. We should really update the naming for that method soon 👍

File: src/status_im/contexts/wallet/common/collectibles_tab/style.cljs (hunk 14 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/common/collectibles_tab/style.cljs]: will try. 👍

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 9 above)
Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: yes, will double check this. Thanks!

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 5 above)
Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: sounds good 👍

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 7 above)
Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: @OmarBasem - imo this guideline is most likely wrong and a bad idea. 
As @ulisesmac pointed out recently, this function `apply-animations-to-style` is actually using a hook and should really be called `use-animated-styles` or something of this sort. 
Hiding this in the style file is likely to lead to bugs (see @ajayesivan's comment below) and we should keep it in the view/ perhaps reconsider the format in how we pass these styled values.

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 10 above)
Comment (Parveshdhull) [reply src/quo/components/profile/collectible_list_item/view.cljs]: logged an issue https://github.com/status-im/status-mobile/issues/20110

Comment (ajayesivan) [reply src/quo/components/profile/collectible_list_item/view.cljs]: Thank you @Parveshdhull

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 7 above)
Comment (OmarBasem) [reply src/quo/components/profile/collectible_list_item/view.cljs]: @J-Son89 I see, but are we still using the function `apply-animations-to-style` tho? What I currently see in the guidelines is we pass an array of styles: 
```
     {:style [{:opacity   opacity
               :transform [{:translate-x scroll-x}]}
              {:flex-direction :row}]}
```

Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: aha, so you mean just remove the use of `apply-animations-to-style ` completely? 
That sounds better if so 👍

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 15]
```diff
@@ -34,77 +75,85 @@
...
-       :image       avatar-image-src}]
-     [rn/view {:style {:width 8}}]]
-    [text/text
-     {:size            :paragraph-1
-      :weight          :semi-bold
-      :ellipsize-mode  :tail
-      :number-of-lines 1
-      :style           style/card-detail-text}
-     collectible-name]]])
+  (let [loader-opacity            (reanimated/use-shared-value 1)
```
Comment (J-Son89) [inline src/quo/components/profile/collectible_list_item/view.cljs:88]: @OmarBasem - good spot on this section, was all a bit wrong but I have since refactored and fixed it. (I think it was my issue to begin with 😅 )

**Comment by J-Son89** [comment]
use of apply-animations-to-style wasn't needed so I removed it in this pr 👍

File: src/status_im/contexts/wallet/common/collectibles_tab/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/common/collectibles_tab/view.cljs]: I think so, we can create a follow-up to improve the code and performance, it's not creating problems so we can address it when we have more time :+1:

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/quo/components/profile/collectible_list_item/view.cljs]: > @OmarBasem - imo this guideline is most likely wrong and a bad idea. As @ulisesmac pointed out recently, this function `apply-animations-to-style` is actually using a hook and should really be called `use-animated-styles` or something of this sort. Hiding this in the style file is likely to lead to bugs (see @ajayesivan's comment below) and we should keep it in the view/ perhaps reconsider the format in how we pass these styled values.

@J-Son89 @OmarBasem @Parveshdhull Yeah, we need to update the guidelines and rename the animated functions to add the prefix `use-`

Comment (ulisesmac) [reply src/quo/components/profile/collectible_list_item/view.cljs]: > aha, so you mean just remove the use of `apply-animations-to-style ` completely? That sounds better if so 👍

@J-Son89 Be careful, actually the vector syntax doesn't behave exaclty the same in all cases. I've learnt by experience that it requires a default value in the regular styles section, otherwise sometimes the animation looks inconsistent at the beginning, this is only needed if your animation doesn't behave as expected:

Example, if we want to animate the opacity, you should provide the "initial" opacity in the regular styles:
```clojure
[reanimated/view
 {:style [;; Regular styles:
          {,,,
           :opacity 0 ;; This is the opacity at the beginning of the animation
           ,,,}
          ;; Animated styles:
          {,,,
           :opacity my-shared-value
           ,,,}
          ]}]
```

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 10 above)
Comment (ulisesmac) [reply src/quo/components/profile/collectible_list_item/view.cljs]: Oh, I've seen @Parveshdhull already added the issue, Thank you!

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 7 above)
Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: thanks @OmarBasem - yeah I think I noticed this alright. Strange, I'll update the uses here because likely it will affect. Thanks for the heads up 🙏

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 9 above)
Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: addressed this, thanks for spotting!

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 7 above)
Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs]: added a default value to each style using opacity. all looks good now 👍

File: src/quo/components/profile/collectible_list_item/view.cljs (hunk 15 above)
Comment (OmarBasem) [reply src/quo/components/profile/collectible_list_item/view.cljs:88]: No worries, thanks for fixing :)

**Review by OmarBasem — APPROVED** [review]
Thanks for refactoring reanimated styles. LGTM!

File: src/quo/components/profile/collectible_list_item/style.cljs [hunk 16]
```diff
@@ -5,18 +5,22 @@
...
-   :border-color     (colors/theme-colors colors/neutral-20 colors/neutral-80 theme)
-   :border-width     1
-   :border-radius    container-border-radius
-   :width            "100%"
-   :aspect-ratio     1
-   :align-items      :center
-   :justify-content  :center})
+  [{:keys [theme opacity]}]
+  [{:opacity opacity}
+   {:opacity          default-opacity-for-image
```
Comment (ulisesmac) [inline src/quo/components/profile/collectible_list_item/style.cljs:14]: :+1:  nice you added these default values

File: src/quo/components/profile/collectible_list_item/style.cljs [hunk 17]
```diff
@@ -91,8 +105,20 @@
...
+  [{:opacity opacity}
+   {:flex           1
+    :flex-direction :row
+    :opacity        default-opacity-for-image}])
+
+(defn supported-file
+  [opacity]
+  [{:opacity opacity}
+   {:aspect-ratio 1
+    :opacity      default-opacity-for-image}])
```
Comment (ulisesmac) [inline src/quo/components/profile/collectible_list_item/style.cljs:124]: Good to see the vector syntax is being used :+1:  it's great because when it's possible to be used, it removes the complexities of dealing with a hook :+1:

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 18]
```diff
@@ -34,77 +75,85 @@
...
+          :image       avatar-image-src}])
+      [rn/view {:style {:width 8}}]
+      [text/text
+       {:size            :paragraph-1
+        :weight          :semi-bold
+        :ellipsize-mode  :tail
+        :number-of-lines 1
+        :style           style/card-detail-text}
+       collectible-name]]
+     (when (not (:avatar-loaded? state))
```
Comment (ulisesmac) [inline src/quo/components/profile/collectible_list_item/view.cljs:114]: `when-not` :eyes:

File: src/status_im/contexts/wallet/account/tabs/view.cljs [hunk 19]
```diff
@@ -11,6 +11,22 @@
...
+  (rf/dispatch [:show-bottom-sheet
+                {:content (fn []
+                            [options-drawer/view
+                             {:name  (:name collectible-details)
+                              :image (:uri preview-url)}])}]))
+
+(defn- on-end-reached
+  []
+  (rf/dispatch [:wallet/request-collectibles-for-current-viewing-account]))
+
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/account/tabs/view.cljs:29]: BTW, this was part of the solution to avoid the re-renders, previously they weren't stable references, so they caused a re-render on every collectible

**Review by ulisesmac — APPROVED** [review]
I like how they look on the video :100: 

the code looks good too :+1:

**Review by ajayesivan — APPROVED** [review]
Nice work @J-Son89 🎉

**Comment by mariia-skrypnyk** [comment]
Hey @J-Son89 !

Thanks for the PR.
The loading of images looks really smoother.
Failed e2e are not related, you can merge your PR.

**Comment by J-Son89** [comment]
Thanks @mariia-skrypnyk and thanks  @ulisesmac for the help on this pr 💪🏼

File: src/quo/components/profile/collectible_list_item/view.cljs [hunk 20]
```diff
@@ -10,13 +10,54 @@
...
     [react-native.core :as rn]
+    [react-native.reanimated :as reanimated]
     [schema.core :as schema]
+    [utils.datetime :as datetime]
     [utils.i18n :as i18n]))
 
+(def timing-options-out 650)
+(def timing-options-in 1000)
+(def first-load-time 500)
+(def cached-load-time 200)
```
Comment (BalogunofAfrica) [inline src/quo/components/profile/collectible_list_item/view.cljs:21]: curious about how this time was estimated

Comment (J-Son89) [reply src/quo/components/profile/collectible_list_item/view.cljs:21]: Just visual experimentation really

Comment (BalogunofAfrica) [reply src/quo/components/profile/collectible_list_item/view.cljs:21]: Okay, would it make sense if this was moved to a constant file?
