### PR TITLE
bug #5120 - fixes crash in wallet send if collectibles are enabled

### LINKED ISSUE #5120: "BigNumber error: div() nut a number: null" navigating to Asset list having collectible
***Type***: Bug

***Summary***: `BigNumber error: div() nut a number: null` appears followed by the app crash when contact with enabled collectable asset navigates to `Wallet` -> `Send transaction` -> `Asset` screen

#### Expected behavior
Only ERC20 tokens (with ETH) are displayed on `Wallet` -> `Send transaction` -> `Asset` even if contact enabled collectibles (CryptoKitty/CryptoStriker/Etheremon)

#### Actual behavior
"BigNumber error: div() nut a number: null" error followed by the app crash navigating to `Wallet` -> `Send transaction` -> `Asset` if user has enabled any of CryptoKitty/CryptoStriker/Etheremon to display in Wallet main screen

screen shot 2018-07-10 at 16 05 14

### Reproduction

- Open Status and create an account
- Switch to Mainnet network (if you are on Ropsten)
- Navigate to `Wallet` -> `Manage Assets`(top-right button)
- Enable CryptoKitties, Cryptostrikers and Etheremon asset
- Navigate to `Wallet` -> `Send transsaction` 
- Tap `Asset` option

### Additional Information
* Status version: Develop 0.9.21 (6186), Release 0.9.22
* Operating System: Android and iOS

#### Logs

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4395996176/?accessToken=890DC0OkBEUJe9f8jrZi87usD3g

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4395996176/?accessToken=890DC0OkBEUJe9f8jrZi87usD3g">TestFairy: Status 0.9.21 (6186) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #5120

### Summary:

Fixes the crash in Wallet send > Choose asset when collectibles are enabled - by filtering out collectibles from the list of sendable tokens.

### Steps to test:
see #5120

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by janherich — APPROVED** [review]

File: src/status_im/ui/screens/wallet/subs.cljs [hunk 1]
```diff
@@ -111,6 +111,11 @@
                   (fn [[balance visible-assets]]
                     (map #(assoc % :amount (get balance (:symbol %))) visible-assets)))
 
+(re-frame/reg-sub :wallet/transferrable-assets-with-amount
+                  :<- [:wallet/visible-assets-with-amount]
+                  (fn [all-assets]
+                    (filter #(not (:nft? %)) all-assets)))
```
Comment (dmitryn) [inline src/status_im/ui/screens/wallet/subs.cljs:117]: shorter version would be:
```clj
(remove :nft? all-assets)
```

Comment (goranjovic) [reply src/status_im/ui/screens/wallet/subs.cljs:117]: Indeed, but it doesn't matter too much now. I'm going to post a separate refactor PR to add token `:type` field with values `:erc20`, `:erc721` etc.

**Comment by Serhy** [comment]
Builds https://i.diawi.com/gz5yka and https://i.diawi.com/CrUFiX looks good!
No collectables present when navigate to Wallet -> Send tx -> Asset, no collectables are in the list of assets for chat commands (send/request). Failed autotests tested and confirmed as false Failure (addressed for fixing)
Ready for merge, @goranjovic !
