### PR TITLE
Spacing between codeblocks and regular text + fixes for "edited at" message

### LINKED ISSUE #15288: No space between codeblock and regular text below it within one message
followup of https://github.com/status-im/status-mobile/pull/15190

**Steps:**

1. Send a message containing codeblock and regular text below the codeblock (see video below)
2. See if there is space (padding) between codeblock and regular text below

Expected result: there should be stadard padding like between other lines in message

**Actual result:** no space. 

photo_2023-03-06 18 33 42

https://user-images.githubusercontent.com/97245802/223172868-b499324d-9ad3-4dbc-93ba-527915980561.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #15289: A separate "Edited" mark is displayed for every codeblock within one edited message
Followup of https://github.com/status-im/status-mobile/pull/15190

**Steps:**

1. Send a message containing codeblock (there might be several codeblocks within one message) and regular text
2. Edit message
3. See how many "Edited" marks are displayed for such message

**Expected result:** one "Edited" mark should be displayed for one entire mesage

**Actual result:** "Edited" mark is displayed for every codeblock within one edited message. 

photo_2023-03-06 18 24 23

https://user-images.githubusercontent.com/97245802/223170325-768600c1-d8d9-4d9c-8060-1615fdb4e77b.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
Fixes https://github.com/status-im/status-mobile/issues/15288
Fixes https://github.com/status-im/status-mobile/issues/15289

Screenshot 2023-03-10 at 14 04 42

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 1]
```diff
@@ -1,13 +1,22 @@
 (ns status-im2.contexts.chat.messages.content.text.style
   (:require [quo2.foundations.colors :as colors]))
 
+(def spacing-between-blocks 10)
+
+(def parsed-text-block
+  {:transform [{:translateY -4}]})
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: could you elaborate why you have to use  transform ?

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 2]
```diff
@@ -64,58 +64,43 @@
...
-                    :children
-                    conj
-                    {:literal (str " (" (i18n/label :t/edited) ")")
-                     :type    :edited}))))
+(defn edited-tag
+  []
+  [quo/text
+   {:weight :medium
+    :style  (style/edited-tag)}
+   (str " (" (i18n/label :t/edited) ")")])
```
Comment (briansztamfater) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: I think we should remove the space string before opening parenthesis and use margins in the styles for spacing instead.

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 3]
```diff
@@ -64,58 +64,43 @@
...
-(defn add-edited-tag
-  [parsed-text]
-  (update parsed-text
-          (dec (count parsed-text))
-          (fn [last-literal]
-            (update last-literal
-                    :children
-                    conj
-                    {:literal (str " (" (i18n/label :t/edited) ")")
-                     :type    :edited}))))
```
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: Can you elaborate on the removal of this function ?

**Review by ibrkhalil — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 3 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Well, edited tag can be added directly when there is a field `edited-at` in the provided text — no need to call `update` inside `update` to add the tag explicitly.

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Design requirements are to add the tag right after the last piece of text .. Inline if possible

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 1 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: You're right, will replace it with margin

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 3 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Ok well, if the requirement was to write it inline if possible then check the latest commit, now it should be good.

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Great work Alex!
Thank you
I'll review it in a bit

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 4]
```diff
@@ -64,58 +64,55 @@
...
+  (let [items-count (count parsed-text)
+        last-item   (get parsed-text (dec items-count))
+        edited-tag  {:literal (str "(" (i18n/label :t/edited) ")")
+                     :type    :edited}]
```
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: Duplicated decalaration .. You already have it defined at line 90

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 5]
```diff
@@ -64,58 +64,55 @@
...
 (defn render-parsed-text
   [{:keys [content edited-at]}]
-  (reduce (fn [acc e]
-            (render-block acc e edited-at))
-          [:<>]
-          (cond-> (:parsed-text content)
-            edited-at add-edited-tag)))
+  [rn/view {:style style/parsed-text-block}
+   (reduce (fn [acc e]
+             (render-block acc e))
```
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: Can be `(reduce render-block` (Without adding the anonymous function)

**Review by ibrkhalil — CHANGES_REQUESTED** [review]
Small refactors, But otherwise great work

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 6]
```diff
@@ -1,13 +1,22 @@
 (ns status-im2.contexts.chat.messages.content.text.style
   (:require [quo2.foundations.colors :as colors]))
 
+(def spacing-between-blocks 10)
+
+(def parsed-text-block
+  {:margin-top -4})
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs:7]: using a negative margin looks suspicious

Comment (alwx) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs:7]: why? it's because each paragraph has a margin-top set
and this particular offset is for the whole block itself, to compensate the margin-top offset for the first paragraph

**Comment by pavloburykh** [comment]
@alwx thanx for the fix! PR is tested and ready to be merged.
