### PR TITLE
[#18595] Implement collectible header with animations

### LINKED ISSUE #18595: Collectible scroll view header is buggy
# Bug Report

## Problem 

When a user visits the collectible scroll view, the blur header has an erratic behavior

#### Expected behavior

Designs:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-318949&mode=design&t=o9pEMRpAgIbY54R4-4

image

image

image

#### Actual behavior

[Screencast from 2024-01-22 23-29-02.webm](https://github.com/status-im/status-mobile/assets/90291778/a1ac8a3f-0089-4f64-ab4b-914049c060ca)

### Reproduction

1. Go to wallet tab
2. Add an account owning collectibles
3. Click on a collectibe to see its details.

### Additional Information

It seems we are inheriting this issues from a reused component for communities, we need to check the differences and create one that behaves well for the wallet.

One difference I've noticed at the moment is that we don't need to make it appear with an animation (from top to bottom), so the left and right buttons don't need to change.

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #18595 

This PR is the continuation of: 
- https://github.com/status-im/status-mobile/pull/19783

It was merged but it lacks of e2e tests and QA. Also @mohsen-ghafouri found some issues in the compilation.

The PR had dev approvals, in this PR we want to identify and solve the compilation issues

status: WIP

### CODE REVIEW

**Comment by ulisesmac** [comment]
Replying to what @OmarBasem  said in the previous PR:

> don't we need QA or design review for this PR?

I'm not sure about QA since it is just a visual change, and we implemented this during the offsite, we had Mario's feedback and approval about the animations, behavior and timings.

cc: @J-Son89 wdyt? should we ask for QA and design review?

**Comment by ulisesmac** [comment]
@ajayesivan 

We had some issues compiling because of the JS worklet location, but AFAIK it was solved, now @mohsen-ghafouri found a compilation issue :thinking:  any idea of what is happening?

**Comment by J-Son89** [comment]
> Replying to what @OmarBasem  said in the previous PR:
> 
> 
> 
> > don't we need QA or design review for this PR?
> 
> 
> 
> I'm not sure about QA since it is just a visual change, and we implemented this during the offsite, we had Mario's feedback and approval about the animations, behavior and timings.
> 
> 
> 
> cc: @J-Son89 wdyt? should we ask for QA and design review?

Since it's a large pr and we had design feedback already maybe it's best to get merged and we can adjust minor details as part of a larger ensign review?

**Comment by OmarBasem** [comment]
> Replying to what @OmarBasem said in the previous PR:
> 
> > don't we need QA or design review for this PR?
> 
> I'm not sure about QA since it is just a visual change, and we implemented this during the offsite, we had Mario's feedback and approval about the animations, behavior and timings.
> 
> cc: @J-Son89 wdyt? should we ask for QA and design review?

If the PR is just adjusting some visuals, and had no previous problems with animation performance then fine. Otherwise, better go through QA imo.

**Comment by ajayesivan** [comment]
> @ajayesivan
> 
> We had some issues compiling because of the JS worklet location, but AFAIK it was solved, now @mohsen-ghafouri found a compilation issue 🤔 any idea of what is happening?

Not sure whats going on. I didn't face any issues while development. I will check and update you.

**Comment by ajayesivan** [comment]
Running this PR was throwing the flowing error on launch,
image

This issue was due to the requires in the `wallet_connect/utils.cljs` file being sorted incorrectly.

https://github.com/status-im/status-mobile/blob/91c347f6f5cd50f4f78fea5c40cb4df792d92540/src/status_im/contexts/wallet/wallet_connect/utils.cljs#L1-L9

even though `#_{:clj-kondo/ignore [:unsorted-required-namespaces]}` is added running `make lint-fix` is sorting it.

cc: @mohsen-ghafouri

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 1]
```diff
@@ -149,3 +214,41 @@
...
+    [rn/view {:style (style/background-color theme)}
+     [animated-header
+      {:scroll-amount scroll-amount
+       :title-opacity title-opacity
+       :page-nav-type :title-description
+       :picture       preview-uri
+       :title         collectible-name
+       :description   collection-name
+       :theme         theme}]
+     [reanimated/scroll-view
```
Comment (Parveshdhull) [inline src/status_im/contexts/wallet/collectible/view.cljs:248]: hi, why this is reanimated view instead of simple view?

File: src/js/worklets/header_animations.js [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+const BLUR_MIN = 1;
+const BLUR_MAX = 15;
+
+export const useBlurAmount = (sharedValue) =>
+  useDerivedValue(() =>
+    parseInt(interpolate(sharedValue.value, [CLAMP_MIN, CLAMP_MAX], [BLUR_MIN, BLUR_MAX], Extrapolation.CLAMP)),
+  );
+
+export function useLayerOpacity(sharedValue, from, to) {
+  return useAnimatedStyle(() => ({
```
Comment (Parveshdhull) [inline src/js/worklets/header_animations.js:20]: This approach has few drawbacks.
1. I am not sure if situation is changed, but changes in js code were not visible until app restarted
2. Also for consistency we should stick to a single approach. If we use this approach everywhere we will have three files, view, simple style, and animated style, for all animations and we have several animations.

**Comment by ulisesmac** [comment]
@OmarBasem 

> If the PR is just adjusting some visuals, and had no previous problems with animation performance then fine. Otherwise, better go through QA imo.

The animation perf is good :+1:  so yeah, let's skip QA for this one

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/view.cljs:248]: Hi @Parveshdhull !

If you are referring to the `reanimated/scroll-view`, the reason is we  are capturing its `on-scroll` callback to animate a shared-value, since we wanted it to properly report the data, I thought it was better to use the reanimated one.

File: src/js/worklets/header_animations.js (hunk 2 above)
Comment (ulisesmac) [reply src/js/worklets/header_animations.js:20]: > I am not sure if situation is changed, but changes in js code were not visible until app restarted

It hasn't changed :cry: and I know, it's a shame that we need to restart the app, I'm not sure if the REPL works to reload the JS requires.

> Also for consistency we should stick to a single approach. If we use this approach everywhere we will have three files, view, simple style, and animated style, for all animations and we have several animations.

Yes, I'm not a big fan of this approach too, that's why I first tried to solve it in a different way:
- https://github.com/status-im/status-mobile/pull/18795

although, I don't exactly like it, it solves the following existing problems:

1. We are always transforming CLJS styles to JS (which we know is expensive)
2. `apply-animations-to-style` is using a hook inside, but devs don't know it, and we can find A LOT of usages of this hook as a regular function, so it's not declared at the beginning, for example.
3. Our `interpolate-value` is not just a call to reanimated's interpolate (which is just a regular function), it hides a hook (`useDerivedValue`) so it has the same problems as mentioned in `2` Additionally,  we are making the code more complex, since instead of interpolate directly inside a `useAnimatedStyle`, we generate derived values with our `interpolate`. transform CLJS -> JS values, then pass them to `apply-animations-to-style` and transform them again.


To show the complexity added because of our wrappers, take a look at this piece of code (taken from the PR I mentioned, it is/was used to animate the avatar size).

#### With our wrappers 

```clojure
(defn f-avatar
  [...]
  ;; Interpolate, which is creating a derived value, it's a hook but looks as a regular function
  (let [image-scale-animation       (reanimated/interpolate scroll-y
                                                            scroll-animation-input-range
                                                            [1 0.4]
                                                            header-extrapolation-option)
        ;; 2nd interpolate usage, CLJS->JS transform, and useDerivedValue hook implied
        image-top-margin-animation  (reanimated/interpolate scroll-y
                                                            scroll-animation-input-range
                                                            [0 20]
                                                            header-extrapolation-option)
        ;; 3rd interpolate usage, CLJS->JS transform, and useDerivedValue hook implied
        image-side-margin-animation (reanimated/interpolate scroll-y
                                                            scroll-animation-input-range
                                                            [0 -20]
                                                            header-extrapolation-option)
        theme                       (quo.theme/get-theme)]
    [reanimated/view
     ;; `style/avatar-container` Looks just as a regular function, but it is/was using
     ;; `apply-animations-to-style`, which is terrible, because that's a hook, and we
     ;; aren't declaring it at the top, also it looks as a style fn, but it does more.
     {:style (style/avatar-container theme
                                     image-scale-animation
                                     image-top-margin-animation
                                     image-side-margin-animation)}
     ...]))
```

#### Without our wrappers

```clojure
(defn f-avatar
  [...]
  (let [theme            (quo.theme/get-theme)
        avatar-animation (worklets/use-avatar-animation scroll-y input-range #js[1 0.4] #js[0 20] #[0 -20])]
    [reanimated/view {:style [(style/avatar-container theme) ;; <- actually only styles
                              avatar-animation]}
     ...]))
```

```js
export function useAvatarAnimation(scrollY, inputRange, range1, range2, range3) {
  return useAnimatedStyles(() => (
      {
        transform: [
// Simplifyed calcs, maybe there were some other operations, but we can perform the interpolate here
// No need of extra sharedValues created with `useDerivedValue`
          {scale: interpolate(scrollY.value, inputRange.value, range1)},
          {translateX: interpolate(scrollY.value, inputRange.value, range2)},
          {translateX: interpolate(scrollY.value, inputRange.value, range3)}
        ]
      })
  )
}
```

The code is smaller and more straightforward, additionally, we are following the recommended practices for hooks.


@Parveshdhull WDYT?

**Comment by ulisesmac** [comment]
@status-im/mobile-qa  We'll skip QA for this one, but could you please make sure the e2e test are passing? thanks!

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/contexts/wallet/collectible/view.cljs:248]: hi Thank you for giving the context.
Most probably we will not get any benefit using reanimated here, unless we are using `animated-scroll-handler` something like https://github.com/status-im/status-mobile/blob/8f0840e913506c0c32157f403e72f5ecb80768b0/src/status_im/contexts/chat/messenger/messages/list/view.cljs#L418

File: src/js/worklets/header_animations.js (hunk 2 above)
Comment (Parveshdhull) [reply src/js/worklets/header_animations.js:20]: Thank you very much for sharing detailed explanation and example.

From your example, it seems for the use case of interpolate it looks simpler to just define whole style in js.
But for other use case, I think we should use wrapper for now.
Otherwise we will lose the ability of hot reloading style related changes. And debugging and developing will be harder.

> apply-animations-to-style is using a hook inside, but devs don't know it, and we can find A LOT of usages of this hook as a regular function, so it's not declared at the beginning,

I think this problem can be easily solved. We just need to communicate to devs and add to guideline.

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/collectible/view.cljs:248]: I mean there's a very common standard in react to add 'use-' as a prefix to any hook

File: src/js/worklets/header_animations.js (hunk 2 above)
Comment (J-Son89) [reply src/js/worklets/header_animations.js:20]: There's already a standard in react to prefix hooks with 'use-'

Comment (Parveshdhull) [reply src/js/worklets/header_animations.js:20]: We probably should rename this wrapper then. thank you @J-Son89

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/view.cljs:248]: Thanks for the suggestion, I'll try removing it and using a normal scroll view to check if it behaves the same :+1:

File: src/js/worklets/header_animations.js (hunk 2 above)
Comment (ulisesmac) [reply src/js/worklets/header_animations.js:20]: @Parveshdhull we could:

1. Rename the wrappers adding `use-...` to the ones that involve a hook and keep using them.
2. Be aware that sometimes writing a worklet directly in JS may be cleaner and simpler in terms of code, so we can take the JS approach, for example, for complex animations (like the ones having multiple interpolations).

wdyt?

I've tried to create worklets in CLJS in different ways and I've got partially working results. I'm just trying to find a way to improve our animated code and API :upside_down_face:

Comment (Parveshdhull) [reply src/js/worklets/header_animations.js:20]: sounds good to me. Thank you for looking into this.

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]
Tested on iOS. LGTM!

**Comment by yevh-berdnyk** [comment]
> @status-im/mobile-qa We'll skip QA for this one, but could you please make sure the e2e test are passing? thanks!

Hi @ulisesmac, thanks for the PR! E2E failures are not related
