### PR TITLE
[Fix] Crash on onboarding due to nil value

### LINKED ISSUE #16883: App crashes with "Doesn't support name" error during onboarding (BLOCKER)
**Steps:** 

1. Install app
2. Tap I'm new to Status
3. Observe an error

**Actual result:** 

[Status-debug-logs (46).zip](https://github.com/status-im/status-mobile/files/12259384/Status-debug-logs.46.zip)

photo_2023-08-04 12 40 41

https://github.com/status-im/status-mobile/assets/97245802/b83e90d8-1636-4338-aecb-2124514fac5f

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #16883

### Summary

This PR fixes the crash on the `New to status` screen to due usage of `when` inside the vector which produces `nil` value.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to the `New to status` screen
- Check whether the app crashes or not

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/contexts/onboarding/new_to_status/view.cljs [hunk 1]
```diff
@@ -110,19 +110,20 @@
...
-                                :on-press        #(rf/dispatch [:navigate-to
-                                                                :quo2-preview])})
-                             {:type            :grey
-                              :icon            :i/info
-                              :icon-background :blur
-                              :on-press        #(rf/dispatch
-                                                 [:show-bottom-sheet
-                                                  {:content getting-started-doc
-                                                   :shell?  true}])}]}]])
+     :right-section-buttons (cond-> [{:type            :grey
```
Comment (ilmotta) [inline src/status_im2/contexts/onboarding/new_to_status/view.cljs:113]: The more future proof solution is to change `right-section-buttons` to deal with nils (just filter them out), since it's quite common to use `when` to build up vectors. For example, re-frame even mentions this as one of the features of its `:fx` effect. 

> if any element of :fx is nil, it will be ignored. This allows effects to be conditionally included via a when (an example is given above)
>
> -- https://day8.github.io/re-frame/releases/2020/

Although `cond->` is just fine, the better fix imo is to make `page-nav` more resilient.

**Review by ilmotta — APPROVED** [review]
LGTM @smohamedjavid. Just left a comment that's not a blocker at all.

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the fix

Tested e2e, universal pr builds (on android and ios), nightly build (on ios). Was not able to test nighty build on android and release builds on ios and android, because builds are failing for some reason when trying to build manually in jenkins. But it is not PR problem I guess. 

Let's merge this PR.

File: src/status_im2/contexts/onboarding/new_to_status/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/onboarding/new_to_status/view.cljs:113]: > if any element of :fx is nil, it will be ignored. This allows effects to be conditionally included via a when (an > example is given above)

This is really helpful. Thanks for sharing!

I agree @ilmotta. We should this filter in all the component which receives a vector to prevent these types of crashes.

I faced this same issue when I was refactoring the action-drawer component, I added a filter to prevent it.
https://github.com/status-im/status-mobile/blob/e5b6378e1575f12c91de1db829395625613bac4a/src/quo2/components/drawers/action_drawers/view.cljs#L98

> the better fix imo is to make page-nav more resilient

I will add the filter in a separate PR 👍

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/new_to_status/view.cljs:113]: @ulisesmac is looking into that component I believe :)

Comment (ulisesmac) [reply src/status_im2/contexts/onboarding/new_to_status/view.cljs:113]: Yes, I will improve our page-nav component 👍
