### PR TITLE
[#7537] fix Contact stuck on login screen

### LINKED ISSUE #7537: Contact stuck on login screen after Status opened with autologin enabled [iOS]
***Type***: Bug

***Summary***: Contact stuck on login screen after Status opened with autologin enabled. 
If to tap `<` ->  `Other accounts` to return to Sign In screen and try to create new account - user stuck on endless 'Creating your account...' screen
If to tap `<` ->  `Other accounts` -> tap on account, where no autologin enabled, - user appears on Home screen right away.

All fine with Android 6.0.1 (Galaxy Note 4)

#### Expected behavior
Contact logged in to account after Status opened with autologin enabled. 

#### Actual behavior
Contact stuck on login screen after Status opened with autologin enabled. 
screenshot 2019-02-20 at 18 30 34

### Reproduction
- Install Status
- Create new account
- Log out of account.
- Log in to account with enabled 'Set password until logout' option
- Close Status
- Open Status

### Additional Information
* Status version: Develop 
* Operating System: iOS 12.1.2

#### Logs

[StatusiOSConsoleLog.log](https://github.com/status-im/status-react/files/2885535/StatusiOSConsoleLog.log)

### PR DESCRIPTION
**Pull request by rasom**
fix #7537

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

File: src/status_im/init/core.cljs [hunk 1]
```diff
@@ -203,8 +203,18 @@
...
-            (navigation/navigate-to-cofx :home nil)
+            (cond->
+             {:notifications/request-notifications-permissions nil}
+
+              platform/ios?
+              ;; on ios navigation state might be not initialized yet when
+              ;; navigate-to call happens.
+              ;; That's why it should be delayed a bit.
+              (assoc :dispatch-later
+                     [{:ms       1
```
Comment (cammellos) [inline src/status_im/init/core.cljs:213]: is this 1 ms arbitrary or you just want it to be executed in the next tick?

Comment (rasom) [reply src/status_im/init/core.cljs:213]: Right, we need to execute it on the next tick.

Comment (yenda) [reply src/status_im/init/core.cljs:213]: is there a callback when navigation state is initialized? In any case it seems like this should be handled in navigation namespace

Comment (rasom) [reply src/status_im/init/core.cljs:213]: there is no callback

There is probably a better way to handle this but this should be enough for fixing a bug before release. We can invest more time in "proper" fix later.

Comment (yenda) [reply src/status_im/init/core.cljs:213]: can you please add a TODO in the code and create a ticket for it then? Because I really wouldn't want this to become permanent code

Comment (rasom) [reply src/status_im/init/core.cljs:213]: sure

Comment (rasom) [reply src/status_im/init/core.cljs:213]: done

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
Tested on IOS 11.4.1 (Iphone 7), Iphone XS  and Android 8.0, Android 6.1 (regression. 
The issue is not reproducible (checked on one account, on app with several accounts, closing app on different screens - wallet, profile); also as a regression checked log out and changing networks.

Waiting for e2e results and mac os build (infrastructure problem)
