### PR TITLE
fix(wallet): token max value not updated when switching

### LINKED ISSUE #21184: [IOS] Token value and max fee not updated on the routes generation page
### Steps:
1. Recover a user with tokens available on at least two networks.
2. Go to the assets selection page.
3. Select any asset (in my case I selected SNT with a total amount of 9).
4. Proceed to the routes generation page.
5. Change the selected token.
6. Disable some networks in the "From" section.

### Actual Result:
- The previous token's value is still displayed, even after selecting a different token.
- The max value still reflects the total amount across all available networks, despite network disabling.

https://github.com/user-attachments/assets/3069c557-eb3b-47e7-ad87-901c90e5cc8f

### Expected Result:
The token value and max fee should update correctly based on the selected token and enabled/disabled networks.

### Devices:
iPhone 11 Pro Max, iOS 17

### Logs:
[logs (3).zip](https://github.com/user-attachments/files/16874226/logs.3.zip)

### ENV:
Nightly 6, Sep 2024

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21184

### Summary

This PR fixes the max value that is not updated when the user switches the token in the input amount screen

#### Platforms

- Android
- iOS

##### Prerequisites: User with multiple tokens (balance > 0)

- Open Status
- Navigate to the Wallet tab
- Navigate to `send > select assets`
- Select any asset
- Continue to the route generation
- Change the selected token by tapping on the token image (displayed left to the input amount)
- Verify the max value is updated

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 1]
```diff
@@ -291,6 +286,15 @@
...
          #(.remove app-keyboard-listener))))
     (hot-reload/use-safe-unmount on-navigate-back)
+    (rn/use-effect
+     (fn []
+       (set-input-state
+        #(-> %
+             (controlled-input/set-upper-limit
+              (utils/cut-crypto-decimals-to-fit-usd-cents
+               (or default-limit-crypto token-balance)
+               conversion-rate)))))
```
Comment (mohsen-ghafouri) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: Just wondering if `conversion-rate` always uses the updated value and never refers to an old value, as it depends on token

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM, just left a question.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: Yes, it will use the updated value as the token is changed 👍

Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: @smohamedjavid the comment from @mohsen-ghafouri is interesting, should we add `token` as dependecy for this `use-effect`? or directly `conversion-rate` and `token-balance`?

I'm just having some questions, not suggesting a change

**Review by ulisesmac — APPROVED** [review]
Looks good :+1: 

Thank you for addressing these issues, the send flow is very important for the wallet :+1:

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: The token-symbol is unique and sufficient to detect changes in the selected token (token map) as the conversion-rate (market price) is inside the token (map). We can pass the whole token map but I felt it's a lot for the deps.

**Comment by VolodLytvynenko** [comment]
Hey @smohamedjavid, the original issue is fixed, but there are some additional cases where the max value isn't updated. Could you address these within this PR, or would it be better to handle them separately?

- Max value is not updated when switching accounts.
- Max value is not updated after a network is disabled (in this case, the max value should only reflect the max value of remaining available networks, excluding the disabled one).

https://github.com/user-attachments/assets/fb3a0808-ef65-4393-b793-541cb4dc84e1

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: Thanks @smohamedjavid

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Thank you for testing the PR 🙏 
The issues you have listed above should be fixed now. Let me know if you find anything else 🙏 Thanks again!

**Comment by VolodLytvynenko** [comment]
@smohamedjavid Thank you for fixes. Take a look please one more found issue

## ISSUE 2: Max value is updated incorrectly when the balance is shown in fiat and any network is disabled
### Steps:
1. Go to the routes generation page using the ETH token.
2. Build any route.
3. Tap switch current button to show balances in fiat
4. Disable any network in the "FROM" section.

### Actual result:
The max value is not updated correctly when the balance is displayed in fiat after disabling a network. This causes the entered value to be highlighted in red, indicating that the user doesn't have enough assets to rebuild the route for another enabled networks.

(Example my user has:
1. On L1: 1.16 ETH = 2789 USD
2. On L2 (Opt): 0.41 ETH = 993 USD
3. On L2 (Arb): 0.54 ETH = 131 USD

But after disabling any network, the max value = 1.22 usd)

https://github.com/user-attachments/assets/8813e790-f8e9-4074-aeef-c429781e9259

### Expected result:
The max value should be updated accurately based on the available balance after any network is disabled/enabled.

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Issue 2 should be fixed now 🙏 . Please check.

**Comment by VolodLytvynenko** [comment]
@smohamedjavid Thank you for the PR. No issues from my side, but I did notice one more place where the max value isn’t updated after the account is changed. If it's better to fix this separately, then the PR can be merged.

## ISSUE 3: Max value is not updated when the account is switched on the swap page
### Steps:
1. Go to the swap page 
2. Switch to another account with a different balance.

### Actual result:
The max value is not updated to reflect the balance of the newly switched account.

https://github.com/user-attachments/assets/d270d302-565a-4e9c-a478-ef6b108973b6


### Expected result:
The max value should update immediately when the account is switched, reflecting the correct token balance of the new account.

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

**Review by vkjr — APPROVED** [review]

**Comment by smohamedjavid** [comment]
Sure @VolodLytvynenko, we will fix it separately 👍 Thank you for testing the PR 🙏
