### PR TITLE
disable chat swipe back navigation in ios

### LINKED ISSUE #16034: [iOS] Messages are marked as read in 1-1 and group chats on the chat screen after first opening the chat and before relogin
# Bug Report

## Problem 

The unread indicator instantly appears and disappears for new messages in 1-1 and group chats on iOS, while the user opens the chat once with a new message, and then gets back to the chat screen.
It works fine after relogin until opening the chat. 

https://github.com/status-im/status-mobile/assets/67952253/8902cae7-440b-443a-978a-5f8ba1c6ceec

### Reproduction

1. UserA: open the chat home screen
2. UserB: send a message to 1-1 chat with UserA
3. UserA: open the chat, tap the `back` button
4. UserB: send another message in the chat
5. UserA: keep an eye on the unread indicator 

### Logs
[geth.log](https://github.com/status-im/status-mobile/files/11574742/geth.log)

### Additional Information

- Status version: RC 1.23 `#5`
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/16034

### Summary

While navigating back using swipe in ios, `navigate-back-handler` don't get called and chat never gets closed.

### Testing
So now we are remove chat from db, when chat screen is not visible, like going back to home screen.
Is there any other screen we can open without closing chat screen, like having chat screen in background?
In that case this solution might create problem. Please let me know if there are any such cases.

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
> So now we are remove chat from db, when chat screen is not visible, like going back to home screen.

I guess more robust solution would be to add this in `reg-component-did-appear-listener` and dispatching `close-chat` when appeared screen is :chat-stack or :shell. But then db will get spam with :close-chat events. (Also community chats will be marked as read, until community is closed, so not good)

or finding out why `navigate-back-handler` not getting called in ios

**Comment by Parveshdhull** [comment]
> or finding out why navigate-back-handler not getting called in ios

might be related to upgrade (if this behavior is new)

**Comment by churik** [comment]
I tested all scenarios that we found for the issue reproduction - none is working for me, so the issue is fixed from my POV.

Thank you for jumping in and for amazing work, as always @Parveshdhull !
Let's wait for e2e and merge PR.

> Is there any other screen we can open without closing chat screen, like having chat screen in background?

For now only images selection, all composer elements, chat options in future. What issues can is cause?

File: src/status_im2/navigation/core.cljs [hunk 1]
```diff
@@ -51,6 +52,11 @@
      (when-not @state/curr-modal
        (reset! state/pushed-screen-id view-id)))))
 
+(navigation/reg-component-did-disappear-listener
```
Comment (flexsurfer) [inline src/status_im2/navigation/core.cljs]: unfortunately, this won't work, because `did-disappear-listener` is very late, this is our pain point, we need to listen for swipe on ios, same how we do with back button on android

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im2/navigation/core.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im2/navigation/core.cljs]: so it will be possible to swipe quick and open chat, and `did-disappear-listener` will happen and chat screen will be broken

**Comment by Parveshdhull** [comment]
> For now only images selection, all composer elements, chat options in future.

Hi, they are fine, they are just modals. Issue will only happen if we open overlapping screen.

> What issues can is cause?

Chat will be closed, probably will show Unknown contact.

File: src/status_im2/navigation/core.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im2/navigation/core.cljs]: > so it will be possible to swipe quick and open chat, and `did-disappear-listener` will happen and chat screen will be broken

Yes, this can be problematic. @churik please can you check if this is reproducible for you?

Comment (flexsurfer) [reply src/status_im2/navigation/core.cljs]: it was reported before so its possible

Comment (Parveshdhull) [reply src/status_im2/navigation/core.cljs]: apparently this is[ known issue](https://stackoverflow.com/questions/63444571/how-to-detect-swipe-back-event-in-iphone-react-native), and solution is to rely on navigation listeners (which doesn't work for us).
Another solution I can try is to call :chat/close on unmount

Comment (Parveshdhull) [reply src/status_im2/navigation/core.cljs]: yup it works, will push changes

**Comment by Parveshdhull** [comment]
Thank you very much @flexsurfer and @churik, pushed new solution.
Please also test on android

File: src/status_im2/contexts/chat/messages/view.cljs [hunk 2]
```diff
@@ -84,8 +74,5 @@
 (defn chat
   []
   (reagent/create-class
-   {:component-did-mount    (fn []
-                              (rn/hw-back-remove-listener navigate-back-handler)
-                              (rn/hw-back-add-listener navigate-back-handler))
-    :component-will-unmount (fn [] (rn/hw-back-remove-listener navigate-back-handler))
+   {:component-will-unmount (fn [] (rf/dispatch [:chat/close]))
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/view.cljs]: i don't remember why but this won't work as well, there are lots of edge cases., the only way is to dispatch on swipe :(

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/chat/messages/view.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: > the only way is to dispatch on swipe :(

Any suggestion on how to detect that?

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: Means is there any event, or have to use gesture handler etc,?

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/view.cljs]: no probably its not possible, and i disabled swipe, but someone enabled it

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: btw, if its working for now, can we keep this solution for release? Because once https://github.com/status-im/status-mobile/pull/15893 is merged, we will have our own navigation for this screen, so don't need to rely on these events.

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: > i disabled swipe, but someone enabled it

maybe we should disable it back?

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/view.cljs]: let's just disable swipe then

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: sounds good

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/view.cljs]: > can we keep this solution

its not a solution, its even worse, because chat will be broken

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: Please can you create a PR for disabling swipe for ios, or point me in the direction. I am not finding option in navigation docs.

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: https://wix.github.io/react-native-navigation/api/options-preview ? probably

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/view.cljs]: https://wix.github.io/react-native-navigation/api/options-root/#popgesture

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/view.cljs]: Thank you

**Review by flexsurfer — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by churik** [comment]
Thanks for amazing work!
e2e failures are known not related to PR.
Tested basic flows, LGTM!

We found one more way to reproduce this issue, but this flow is not that crucial, so ready to be merged.

**Devices:**
- IPhone 12 Mini (IOS 16)
- BlackView BV5200 Pro (Android 12)
