### PR TITLE
[Fix] Currency on recovered profile

### LINKED ISSUE #18199: Fiat currency marks not displayed for accounts and assets of old recovered users
### Steps:
1. Recover the old user created before 14.12.2023
2. Open wallet
3. Check fiat currency for account and assets

### Actual result:
Upon accessing the wallet of old recovered user account created before December 14, 2023, the fiat currency marks do not appear. 
image

### Expected result:
The fiat currency marks should be visibly displayed alongside accounts and assets. 
image

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14294229/logs.zip)

### Additional info:
Please, refer to me directly if you need seed phrase of old account

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18199

### Summary

This PR fixes the currency symbol not shown on the recovered profile.

### Review Notes

The bug is caused by to assoc setting value without data sanitization.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Recover any profile created before 14.12.2023
- Verify the currency symbol is shown on the Wallet

status: ready

### CODE REVIEW

File: src/legacy/status_im/data_store/settings.cljs [hunk 1]
```diff
@@ -51,3 +51,10 @@
       (visibility-status-updates/<-rpc-settings)
       (set/rename-keys {:compressedKey :compressed-key
                         :emojiHash     :emoji-hash})))
+
+(defn rpc->setting-value
```
Comment (J-Son89) [inline src/legacy/status_im/data_store/settings.cljs:55]: is there any reason we need to have this in legacy folder? seems like something we can move to profile/datastore.cljs ?

Comment (J-Son89) [reply src/legacy/status_im/data_store/settings.cljs:55]: and start the migration! :)

**Review by qfrank — APPROVED** [review]

File: src/legacy/status_im/data_store/settings.cljs [hunk 2]
```diff
@@ -51,3 +51,10 @@
...
+  [{:keys [name] :as setting}]
+  (condp = name
+    :currency (update setting :value keyword)
+
```
Comment (OmarBasem) [inline src/legacy/status_im/data_store/settings.cljs:59]: empty NL

File: src/legacy/status_im/data_store/settings.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/legacy/status_im/data_store/settings.cljs:55]: > is there any reason we need to have this in legacy folder? seems like something we can move to profile/datastore.cljs ?

I placed it in the `legacy.*` ns as the RPC data helpers for settings are used from it.
https://github.com/status-im/status-mobile/blob/9ff70ed9900336ce782169979c8d9922a0709bb8/src/status_im/contexts/profile/login/events.cljs#L86
https://github.com/status-im/status-mobile/blob/9ff70ed9900336ce782169979c8d9922a0709bb8/src/legacy/status_im/data_store/settings.cljs#L38

Moving the data-store for settings to `status-im.*` ns would be easy when we do it.

cc @flexsurfer

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid thank you for PR. No issues from my side. PR can be merged
