### PR TITLE
Fix transaction time estimation (and added route malli schema)

### LINKED ISSUE #22254: Time estimation for transactions not shown
# Bug Report

## Problem 
[comment]: # (A problem description)
On status-go's router, time estimations have changed from `EstimatedTime` to `TxEstimatedTime`. With the new changes, the time is expressed in seconds instead of minute intervals.

- [ ] Estimations are shown in seconds with 5 second increments
- [ ] If the estimation is unknown, show a default (e.g. `>60s`)
- [ ] Show estimations larger than a minute with `>60s`
- [ ] Show real time estimations for the normal/fast/urgent transaction settings (currently hard coded values)

#### Expected behavior
Estimated time is shown in seconds

#### Actual behavior
Estimated time is not shown

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #22254

## Summary
[comment]: # (Summarise the problem and how the pull request solves it)
1. showing time estimations
2. time estimations are shown in seconds
3. time estimations default to ">60s" if it is unknown
4. real time estimations are used for the transaction settings (normal/fast/urgent) instead of hardcoded
5. added schemas for the router, which should make sure we identify status-go changes in the router data faster and avoid bugs staying unnoticed
6. moved some of the route/path data transformations into a separate namespace (together with the schemas)

[comment]: # (Can be ready or wip)
status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/data_store.cljs [hunk 1]
```diff
@@ -226,60 +227,34 @@
...
-        suggested-levels-for-max-fees-per-gas (:suggested-levels-for-max-fees-per-gas new-path)]
+  (let [to-bignumber (fn [k] (-> new-path k money/bignumber))]
     {:approval-fee              (to-bignumber :approval-fee)
      :approval-l-1-fee          (to-bignumber :approval-l-1-fee)
      :bonder-fees               (to-bignumber :tx-bonder-fees)
      :token-fees                (to-bignumber :tx-token-fees)
      :from                      (:from-chain new-path)
      :amount-in-locked          (:amount-in-locked new-path)
      :amount-in                 (:amount-in new-path)
-     :max-amount-in             (:max-amount-in new-path)
```
Comment (clauxx) [inline src/status_im/contexts/wallet/data_store.cljs:248]: this value is not used anywhere and is not present in the router data. Seems to be from the previous router version.

File: src/status_im/contexts/wallet/router/core.cljs [hunk 2]
```diff
@@ -0,0 +1,87 @@
+(ns status-im.contexts.wallet.router.core
+  (:require [schema.core :as schema]
+            [status-im.contexts.wallet.router.schema :as router.schema]
+            [status-im.contexts.wallet.send.transaction-settings.core :as transaction-settings]
+            [status-im.contexts.wallet.send.utils :as send-utils]))
+
+(def ^:private gwei-precision 6)
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/router/core.cljs]: Maybe move this to constants ?

File: src/status_im/contexts/wallet/router/schema.cljs [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+  [:map {:closed? true}
+   [:low ?hex]
+   [:medium ?hex]
+   [:high ?hex]
+   [:low-estimated-time :int]
+   [:medium-estimated-time :int]
+   [:high-estimated-time :int]
+   [:low-priority ?hex]
+   [:medium-priority ?hex]
+   [:high-priority ?hex]])
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/router/schema.cljs]: `?hex` could live in the common namespace and be used as `:schema.common/hex` as this can promote reusability of foundational types.

File: src/status_im/contexts/wallet/wallet_connect/modals/send_transaction/view.cljs [hunk 4]
```diff
@@ -114,6 +114,6 @@
          :container-style style/data-item
          :title           (i18n/label :t/est-time)
          :subtitle        (if estimated-time
-                            (i18n/label :t/time-in-mins {:minutes estimated-time})
+                            (i18n/label :t/time-in-sec {:seconds (str estimated-time)})
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/wallet_connect/modals/send_transaction/view.cljs:117]: Just a quick question, do we really need `str` or will `i18n/label` handle numbers just fine? My impression was that we could remove `str` here and in other similar usages.

File: src/status_im/subs/wallet/send.cljs [hunk 5]
```diff
@@ -242,3 +242,12 @@
  :<- [:wallet/tx-settings-fee-mode-user]
  (fn [[route value-set-by-user]]
    (or value-set-by-user (:tx-fee-mode (first route)))))
+
+(rf/reg-sub
+ :wallet/send-estimated-time
+ :<- [:wallet/send-best-route]
+ (fn [route]
+   (when route
+     (-> route
```
Comment (ilmotta) [inline src/status_im/subs/wallet/send.cljs]: Possibly a good use of `some->` to remove the `when`.

File: src/status_im/contexts/wallet/router/schema.cljs [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+   :tx-fee-mode/custom
+   :tx-fee-mode/normal
+   :tx-fee-mode/fast
+   :tx-fee-mode/urgent])
+
+(def ^:private ?hex
+  [:and :string [:re #"^0x[0-9a-fA-F]+$"]])
+
+(def ^:private ?suggested-levels-for-max-fees-per-gas
+  [:map {:closed? true}
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/router/schema.cljs]: Is there a reason this map in particular is closed?

File: src/status_im/contexts/wallet/router/core.cljs [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+     :eip-1559-enabled         true
+     :base-fee                 (to-gwei tx-base-fee)
+     :max-priority-fee-per-gas (to-gwei tx-priority-fee)
+     :l-1-gas-fee              (to-gwei tx-l-1-fee)
+     :tx-max-fees-per-gas      (to-gwei tx-max-fees-per-gas)}))
+
+(schema/=> transaction-gas-fees
+  [:=>
+   [:cat router.schema/?route]
+   [:map {:closed? true}
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/router/core.cljs:93]: Why close the schema if the data is coming from status-go? If the producer adds keys, the consumer will break (fail instrumentation).

File: src/status_im/contexts/wallet/router/core.cljs [hunk 8]
```diff
@@ -0,0 +1,87 @@
...
+  (:require [schema.core :as schema]
+            [status-im.contexts.wallet.router.schema :as router.schema]
+            [status-im.contexts.wallet.send.transaction-settings.core :as transaction-settings]
+            [status-im.contexts.wallet.send.utils :as send-utils]))
+
+(def ^:private gwei-precision 6)
+
+(defn- to-gwei
+  [amount]
+  (send-utils/convert-to-gwei amount gwei-precision))
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/router/core.cljs]: Side note about the name `convert-to-gwei`. This function should ideally live in a separate namespace because it has nothing to do with send utilities. Once the separate namespace exists, its name will support a better API naming scheme that's more idiomatic. For example, `eth-unit/->gwei` or `eth-money/->gwei`

File: src/status_im/contexts/wallet/router/core.cljs [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+  (-> route
+      :tx-gas-fee-mode
+      transaction-settings/gas-rate->tx-fee-mode))
+
+(schema/=> transaction-fee-mode
+  [:=>
+   [:cat router.schema/?route]
+   router.schema/?fee-modes])
+
+(defn transaction-estimated-time
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/router/core.cljs:52]: I don't see any unit tests in the PR @clauxx. It's concerning that we are relying exclusively on manual tests from QA and that after so many discussions in our teams we still struggle with something so basic. The problem didn't originate from this PR, I understand you are already doing amazing work with adding the schemas 💯 I would at least cover with unit tests the data store functions because that's our basic contract where data is returned exactly as we want and it's all pure without the shenanigans of re-frame and state management.

I leave it up to you to judge when/how to approach this feedback.

Comment (ilmotta) [reply src/status_im/contexts/wallet/router/core.cljs:52]: Side note: the schema generators could then be used to generate large maps and then assoc/dissoc only as needed. It's an approach I've used/verified in Status (and in a past job) and can get a long way in helping reduce the noise in tests so that we can focus on the important test arrangement and assertions.

File: src/status_im/contexts/wallet/router/core.cljs (hunk 2 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/router/core.cljs]: will remove it since we already have a constant there

File: src/status_im/contexts/wallet/router/schema.cljs (hunk 6 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/router/schema.cljs]: it's a leftover, cause at the beginning I added schemas only for the router fields we use, so I closed this one since we use all the fields. Later on I decided to cover all the fields though. Also agree that on our side schemas should be open for data coming from external sources e.g. status-go

File: src/status_im/contexts/wallet/router/core.cljs (hunk 7 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/router/core.cljs:93]: this is the schema for the return value, so IMO it should be closed so it fails in case we add new fields on the client side.

File: src/status_im/contexts/wallet/router/core.cljs (hunk 9 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/router/core.cljs:52]: fully agreed on the tests here and good call on schema generators. Buuut, there was an issue with the regex schema (`:re` is used in the hex schema), which doesn't have a generator in cljs. I added a default return value for the generator, but lmk if you see a better solution.

File: src/status_im/contexts/wallet/router/core.cljs (hunk 8 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/router/core.cljs]: I'm not sure if we need to add another namespace for it, given that we have the `money` one already for dealing with crypto/fiat. At the same time, it seems like `convert-to-gwei` is used only here, so we might not even need an util for it and can just move it to this ns, wdyt?

**Comment by clauxx** [comment]
@shivekkhurana @ilmotta i addressed your review comments, so please have another look

File: src/status_im/contexts/wallet/router/schema.cljs (hunk 6 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/router/schema.cljs]: Thanks @clauxx, makes sense to me.

File: src/status_im/contexts/wallet/router/core.cljs (hunk 7 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/router/core.cljs:93]: Good call 👍🏼

File: src/status_im/contexts/wallet/router/core.cljs (hunk 8 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/router/core.cljs]: The existing `money` namespace could be used as well as you pointed out. I tend to personally not like to decide where functions should live based on usage, but rather about the purpose of namespaces. The router shouldn't know or have the responsibility of handling crypto conversions directly, so from that angle `convert-to-gwei` feels out of place, even if it's used only by this namespace (for now).

File: src/status_im/contexts/wallet/router/core.cljs (hunk 9 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/router/core.cljs:52]: Correct @clauxx there's this extra challenge with generators for regexps. I thought Malli in CLJS had support for generating strings from regexps. I see now in the source there's a generator, but only for Clojure https://github.com/metosin/malli/blob/0.17.0/src/malli/generator.cljc#L193. And the problem was also attacked for clojure.spec https://github.com/miner/strgen

Your solution for works well for now 👍🏼 Thanks!

File: src/status_im/contexts/wallet/router/router_test.cljs [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+    (let [route (update-in generated-route
+                           [:suggested-levels-for-max-fees-per-gas]
+                           dissoc
+                           :low                   :medium
+                           :high                  :low-estimated-time
+                           :medium-estimated-time :high-estimated-time)]
+      (is (thrown? js/Error (router/transaction-fees-by-mode route)))))
+
+  (testing "fees and estimated time are correctly grouped by fee mode"
+    (let [route    (update-in generated-route
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/router/router_test.cljs]: Super nice to see this namespace using generators 👏🏼 

A nitpick is that the tests don't care if the route was generated automatically or manually, so perhaps a more common and appropriate name could be just `default-route`.

File: src/status_im/contexts/wallet/router/router_test.cljs [hunk 11]
```diff
@@ -0,0 +1,116 @@
...
+     (match? expected-fee-mode
+             (-> generated-route
+                 (assoc :tx-gas-fee-mode gas-rate)
+                 router/transaction-fee-mode))
+     :tx-fee-mode/normal constants/gas-rate-low
+     :tx-fee-mode/fast   constants/gas-rate-medium
+     :tx-fee-mode/urgent constants/gas-rate-high
+     :tx-fee-mode/custom constants/gas-rate-custom))
+
+  (testing "fails due to schema validation"
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/router/router_test.cljs]: It's a bit unusual to see these tests about failing schemas because malli instrumentation in our project and many others are not enabled in production, so it's a bit like "testing tests". The driving force of automatic verification of schemas would be the normal tests, based on valid production scenarios.

**Review by ilmotta — APPROVED** [review]
Very nice work with Malli @clauxx 💯

**Review by vkjr — APPROVED** [review]

**Comment by vkjr** [comment]
Amazing job! Thank you! 🥳

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/status_im/contexts/wallet/data_store.cljs [hunk 12]
```diff
@@ -232,60 +233,35 @@
...
      :approval-required         (:approval-required new-path)
-     :estimated-time            (:estimated-time new-path)
      :to                        (:to-chain new-path)
      :approval-amount-required  (:approval-amount-required new-path)
      ;;  :cost () ;; tbd not used on desktop
      :gas-amount                (:tx-gas-amount new-path)
      :router-input-params-uuid  (:router-input-params-uuid new-path)
-     :tx-fee-mode               (transaction-settings/gas-rate->tx-fee-mode (:tx-gas-fee-mode
-                                                                             new-path))}))
+     :gas-fees                  (router/transaction-gas-fees new-path)
```
Comment (vkjr) [inline src/status_im/contexts/wallet/data_store.cljs:255]: @clauxx, it looks like all the router functions are used only in the `data_store.cljs` file. I'm wondering if we can have a folder `data_store` and pull router and this file under it since this is all about dealing with `status-go` data structures. Wdyt?

Comment (clauxx) [reply src/status_im/contexts/wallet/data_store.cljs:255]: it's true that it's currently only consumed by the data-store, we can use the current ns to also add functions that operate on the data structures we create there, (e.g. operations on the router fees). Moving everything under data-store would make that difficult, so IMO there's more value to having a separate router ns.

File: src/status_im/contexts/wallet/router/router_test.cljs (hunk 11 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/router/router_test.cljs]: good point actually, will remove :+1:

File: src/status_im/contexts/wallet/router/router_test.cljs (hunk 10 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/router/router_test.cljs]: done :+1:

File: src/status_im/contexts/wallet/data_store.cljs (hunk 12 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/data_store.cljs:255]: I agree that functions that operate on route data structure better to be kept together and we need a place for this. 

But here we in fact speak about 2 different `route` structures:
- there is a `route` structure that we receive from `status-go`
- there is a `route` structure that we create on `status-mobile` side by renaming and rearranging the keys of that structure from `status-go`.

`route` from `status-go` is something unstable - it may change uncontrollably by other team so it is kind of 3rd party.
`route` on `status-mobile` should be a stable structure that we rely on in our application logic. 

It is possible that we will replace `status-go` route with some 3rd party provider (which is ongoing investigation). In this case the ideal situation would be if we can forget about `route` from `status-go`, receive the new `route` from other provider but convert it to the `status-mobile` `route` of the _same_ shape. That would leave all our internal application logic intact. 

When you speak about adding functions "that operate on the data structures" - it is about `status-mobile` `route`. We can group a lot of functions that operate on it together and that will be a part of application logic. So it is a stable functionality of our application.

But `data_store` is  a place where we _create_ `status-mobile` `route` structure from unstable 3rd party source. It is not core part of our app, not part of its usecases, it is more infrastructure part and it can be fully replaced when router provider changed.

So by saying all this I just want to highlight that all functions that are now in `router.cljs`, they are kind of on infrastructure side, belonging to data-store and they will be rewritten if we change the router provider. While functions that operate on `status-mobile` `route` for sure should be grouped together but they are totally different logical entities.

It is not really important to reorganize anything here but I think it is important to recognize the difference :)

Comment (ilmotta) [reply src/status_im/contexts/wallet/data_store.cljs:255]: In agreement with your points @vkjr.

> route from status-go is something unstable - it may change uncontrollably by other team so it is kind of 3rd party.

Just about this point, we should be in full control as well of what happens to the router implementation in status-go. Moreover, when we upgrade status-go in status-mobile, we should verify the status-go merge commits in `develop` to decide what needs to be adapted. We also have direct influence on approving or blocking PRs in status-go. All PRs affecting the router should have direct approval from the Mobile & Desktop Wallet teams, so they shouldn't change uncontrollably. cc @shivekkhurana 

Therefore, the analogy with a third-party for status-go only goes so far. We could also resurrect the contract tests initiative (and possibly change the original approach we did in cljs).

**Comment by yevh-berdnyk** [comment]
Hi @clauxx, @pavloburykh, I've updated e2e tests, other failures are not related to the PR

**Comment by pavloburykh** [comment]
@clauxx thanks for the PR. I have not found any critical issues, PR is ready for merge. 

There was one small issue which I have faced only once, and couldn't reproduce again, so I think we can ignore it: estimated time for selected fee inside transaction settings differed from estimated time shown on review screen. 

https://github.com/user-attachments/assets/05292efd-88f8-4c6a-94b3-860a87677c8e

@clauxx when merging could you please also include [commit](https://github.com/status-im/status-mobile/pull/22258/commits/8e661dc3d551db3a937fa546e44da4c6c7b514a3) by @yevh-berdnyk with e2e fixes which she recently pushed in current branch (thank you @yevh-berdnyk)? 

**What has been tested:** 

1. Showing time estimations on send/bridge review screens
2. Time estimations are shown in seconds
3. Time estimations default to ">60s" if it is unknown
4. Real time estimations are used for the transaction settings (normal/fast/urgent) instead of hardcoded
5. Performed send/bridge/swap transactions to ensure there is no regression
6. Perfromed swap transaction via Dapp (1inch), ensured time estimation is not broken when signing transactions triggered by dapps connected via wallet connect.

File: src/status_im/contexts/wallet/data_store.cljs (hunk 12 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/data_store.cljs:255]: @ilmotta, I fully agree with your points. 
To clarify the word "uncontrollable" I'd like to draw the difference between more local project-level view and more global product-level view.

At product level - `status-mobile`, `status-desktop` and `status-go` are all the parts of the same "Status app". And of course at this level changes in `status-go` aren't "uncontrollable". They are driven by our common goals and mobile team has impact on what is changed.

At project level `status-go` and `status-mobile` are different projects. And `status-go` interface changes not only to reflect the needs of `status-mobile`, but also as a result of `status-desktop` needs, or its own `status-go` needs (like refactoring). So when I say that "`status-go` changes are uncontrollable" I mean that they are happen sometimes without `status-mobile` request and `status-mobile` is in reactive position to those changes.
 
So this changing nature of `status-go` is a reason why data structures in `status-mobile` shouldn't be a copy of `status-go` structures. They should be internal data structures that are convenient for `status-mobile` consumption. This way the surface of changes needed to react on `status-go` change will be minimal.

Comment (ilmotta) [reply src/status_im/contexts/wallet/data_store.cljs:255]: > They should be internal data structures that are convenient for status-mobile consumption. 

Yep 💯 Pretty much all systems I've coded in required an anti-corruption layer at certain points and status-mobile is no different. From Oct 2022, but even before that as soon as I joined I was trying to direct our focus on creating an anti-corruption layer https://github.com/status-im/status-mobile/pull/14125#issuecomment-1273457463. It's great to see we are going in that direction now o/

Comment (vkjr) [reply src/status_im/contexts/wallet/data_store.cljs:255]: @ilmotta, I'm very up for moving in this direction. In the architecture [proposed](https://www.notion.so/Application-logic-layers-18c8f96fb65c805a9a53c4f132c0a696?pvs=4) on DX calls the `infrastructure` is exactly this "anti-corruption" layer that converts external inputs that can change or can be replaced into internal `application` data-structure that are relative stable and application-specific.
