### PR TITLE
The select assets screen is shown when token is going to be sent which available on both watch-only and regular account #19745

### LINKED ISSUE #19745: The select assets screen is shown when  token is going to be sent which available on both watch-only and regular account
can be taken after merge of https://github.com/status-im/status-mobile/pull/19515

### Steps to reproduce:
1. Restore an account with available assets on both regular and watch-only accounts.
2. Long tap on the asset 
3. Select an address to 'send to'
4. Check next page

### Actual result:
The 'Select assets' page is shown (at 13 seconds into the recording below), despite the asset having already been selected in step 3

https://github.com/status-im/status-mobile/assets/52490791/51afec6b-0175-4a6f-af67-71c0e62af1ff

### Expected result:
The 'Select assets' page should be skipped since the asset has already been selected.

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by mmilad75**
fixes #19745 

The issue was after selecting an asset to send, all of the accounts was shown, even if an account didn't have the selected asset. When selecting an account without having the selected asset, when checking the assets of the selected account in the `Select Asset` screen in order to skip it, the result of it was null, so the skipping was ignored and the `Select Asset` was rendered and shown.

Now by removing the accounts without the selected asset, the issue is fixed.

https://github.com/status-im/status-mobile/assets/55688834/23769075-25ad-4a8b-9da2-adca899c5e20

### CODE REVIEW

**Comment by ulisesmac** [comment]
Hello @mmilad75 

Could you please write a description about what is being solved and what was the strategy applied to solve it?

I can see the UI shows 0 Uniswap but it still displays one account in the `send-to` page. Should we remove the Send to action for tokens where the balance is zero?

cc: @J-Son89

File: src/status_im/contexts/wallet/wallet_connect/utils.cljs [hunk 1]
```diff
@@ -1,10 +1,10 @@
 (ns status-im.contexts.wallet.wallet-connect.utils
   ;; NOTE: Not sorting namespaces since @walletconnect/react-native-compat should be the first
   #_{:clj-kondo/ignore [:unsorted-required-namespaces]}
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/wallet_connect/utils.cljs]: revert 🙏

Comment (J-Son89) [reply src/status_im/contexts/wallet/wallet_connect/utils.cljs]: linting is auto updating this btw 🦀

**Comment by J-Son89** [comment]
> Hello @mmilad75
> 
> Could you please write a description about what is being solved and what was the strategy applied to solve it?
> 
> I can see the UI shows 0 Uniswap but it still displays one account in the `send-to` page. Should we remove the Send to action for tokens where the balance is zero?
> 
> cc: @J-Son89

yep I agree, although the issue often captures the description well. imo it's best to capture in a description what the pr does become some details can change and it makes it easier for the reviewer and the QA to get a quick context of what is happening/ what to check etc 👍

**Comment by briansztamfater** [comment]
Not related to this PR in particular but in the video it is noticeable that we are showing the X button at the top-left in screens when action is navigate back. We should show an X only when the action is dismissing the modal (in this case, only the `From` should only have an X, `Send to` should have a back arrow ◀️).

**Comment by mmilad75** [comment]
> Hello @mmilad75
> 
> Could you please write a description about what is being solved and what was the strategy applied to solve it?
> 
> I can see the UI shows 0 Uniswap but it still displays one account in the `send-to` page. Should we remove the Send to action for tokens where the balance is zero?
> 
> cc: @J-Son89

If we want to skip the assets with 0 balance, it should be handled in every situation. I don't think it's a good idea to skip it in one place and leave it as the same in other places.

WDYT? @ulisesmac @J-Son89

**Comment by mmilad75** [comment]
> Hello @mmilad75
> 
> Could you please write a description about what is being solved and what was the strategy applied to solve it?
> 
> I can see the UI shows 0 Uniswap but it still displays one account in the `send-to` page. Should we remove the Send to action for tokens where the balance is zero?
> 
> cc: @J-Son89

I added the description

**Comment by mmilad75** [comment]
> Not related to this PR in particular but in the video it is noticeable that we are showing the X button at the top-left in screens when action is navigate back. We should show an X only when the action is dismissing the modal (in this case, only the `From` should only have an X, `Send to` should have a back arrow ◀️).

Thanks for noticing it. I will fix it in this PR

File: src/status_im/subs/wallet/wallet.cljs [hunk 2]
```diff
@@ -332,6 +337,19 @@
  (fn [accounts]
    (remove :watch-only? accounts)))
 
+(rf/reg-sub
+ :wallet/accounts-with-current-asset
+ :<- [:wallet/accounts-without-watched-accounts]
+ :<- [:wallet/wallet-send-token-symbol]
+ :<- [:wallet/wallet-send-token]
+ (fn [[accounts token-symbol token]]
```
Comment (ilmotta) [inline src/status_im/subs/wallet/wallet.cljs:413]: Hey guys, historically, I find myself having to comment too frequently on PRs about missing unit tests for layer-3 subs. This recommendation is in our guidelines and I believe we should be more strict about following it (reasons below).

> Test [layer-3 subscriptions](https://day8.github.io/re-frame/subscriptions/) by
actually subscribing to them, so reframe's signal graph gets validated too.
>
> -- https://github.com/status-im/status-mobile/blob/634dd747681b14c44d3ec8d13d7b44ca251480b0/doc/new-guidelines.md#subscription-tests

These tests are powerful because we test using the subscription machinery on purpose instead of just testing the sub handler. Our macro `deftest-sub` helps with that. This means that if any of the input subscriptions, say `:wallet/wallet-send-token` change, the output of its calculation will be picked up by the tests of this sub `:wallet/accounts-with-current-asset`.

This means that by covering layer-3 subs with unit-tests, we are covering the subscription graph of the app, and they can all affect each other, giving us a useful layer of protection.

cc @J-Son89

**Comment by ulisesmac** [comment]
> > Hello @mmilad75
> > Could you please write a description about what is being solved and what was the strategy applied to solve it?
> > I can see the UI shows 0 Uniswap but it still displays one account in the `send-to` page. Should we remove the Send to action for tokens where the balance is zero?
> > cc: @J-Son89
> 
> If we want to skip the assets with 0 balance, it should be handled in every situation. I don't think it's a good idea to skip it in one place and leave it as the same in other places.
> 
> WDYT? @ulisesmac @J-Son89

Makes sense @mmilad75, let's keep it and if it's undesired, then we'll remove it from everywhere :+1:

**Review by ulisesmac — APPROVED** [review]
Hey @mmilad75 

The fix looks good, actually it was a pending taks after I merged the wizard PR, so thank you for taking care of it :+1:

File: src/status_im/subs/wallet/wallet.cljs (hunk 2 above)
Comment (mmilad75) [reply src/status_im/subs/wallet/wallet.cljs:413]: I added the tests @ilmotta

File: src/status_im/subs/wallet/wallet_test.cljs [hunk 3]
```diff
@@ -12,6 +12,14 @@
 (use-fixtures :each
               {:before #(reset! rf-db/app-db {})})
 
+(def ^:private accounts-with-tokens
```
Comment (ilmotta) [inline src/status_im/subs/wallet/wallet_test.cljs:15]: A quick side note @mmilad75. In theory, we shouldn't worry about encapsulation (private/public vars) in namespaces that won't ever be required elsewhere (like test namespaces) because there's no API to be exposed. The same argument works for preview namespaces. In these namespaces, everything can be public. Consider that nobody needs to refactor a component preview namespace or a test namespace and take in consideration vars exposed from them.

cc'ing @ulisesmac @briansztamfater just to give some visibility :)

File: src/status_im/subs/wallet/wallet_test.cljs [hunk 4]
```diff
@@ -456,6 +464,46 @@
...
+                    :network-preferences-names #{}
+                    :customization-color       nil}]))))
+
+  (testing "returns the accounts list with the current asset using token"
+    (swap! rf-db/app-db
+      #(-> %
+           (assoc-in [:wallet :accounts] accounts-with-tokens)
+           (assoc-in [:wallet :ui :send :token] {:symbol "ETH"})))
+    (let [result (rf/sub [sub-name])]
+      (is (match? result
```
Comment (ilmotta) [inline src/status_im/subs/wallet/wallet_test.cljs:486]: In this repo, the majority of the assertions are `(= expected actual)` or `(match? expected actual)` not the other way around as it's used here. It's just a consistency thing, not that one is way is wrong. Although in the newest version of clj-kondo, it even has a new linter that will check the expected argument appears first by default (https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#equals-expected-position). We can't use this linter version yet.

File: src/status_im/subs/wallet/wallet_test.cljs [hunk 5]
```diff
@@ -456,6 +464,46 @@
...
+    (swap! rf-db/app-db
+      #(-> %
+           (assoc-in [:wallet :accounts] accounts-with-tokens)
+           (assoc-in [:wallet :ui :send :token-symbol] "SNT")))
+    (let [result (rf/sub [sub-name])]
+      (is (match? result (vals accounts-with-tokens)))))
+
+  (testing "returns the accounts list when there is no current asset"
+    (swap! rf-db/app-db
+      #(-> %
```
Comment (ilmotta) [inline src/status_im/subs/wallet/wallet_test.cljs:502]: Here we don't need the anonymous function because there's only one assoc-in.

**Review by ilmotta — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thank you @mmilad75, PR can be merged!
