### PR TITLE
fix UI freeze issue

### LINKED ISSUE #15310: UI freezes when changing theme in profile, clicking on tabs opens wrong screens
UPD: more details in the comments below

---

Currently there are no clear steps how to reproduce the bug. Having an assumption that it is somehow related to user with enabled PNs. Bug has been reproduced on Android after opening app that has been backgrounded for a while, right after receiving PN. Needs further investigation. 

For now, I attached video and logs. 

Below video demonstrates 2 issues:

1. Wallet bottom sheet opens on tapping on AC icon
2. Buttons/elements on community screen are not responding

[Status-debug-logs (22).zip](https://github.com/status-im/status-mobile/files/10945929/Status-debug-logs.22.zip)

https://user-images.githubusercontent.com/97245802/224423679-dfc23719-21f8-4abd-adb5-bf6ce00cbcb2.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/15310

### Summary
Pointer events not working well once view recreated using hot-reload. Actually UI not freezing only allowing touch events on wrong screen. (More [details](https://github.com/status-im/status-mobile/issues/15310#issuecomment-1514600454))

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

File: src/js/worklets/shell.js [hunk 1]
```diff
@@ -18,11 +18,11 @@ export function stackOpacity (stackId, selectedStackId) {
   );
 }
 
-export function stackPointer (stackId, selectedStackId) {
+export function stackZIndex (stackId, selectedStackId) {
   return useDerivedValue(
     function () {
       'worklet'
-      return selectedStackId.value == stackId ? "auto" : "none";
+      return selectedStackId.value == stackId ? 10 : 9;
```
Comment (J-Son89) [inline src/js/worklets/shell.js:25]: this seems like something that might benefit from having a comment explaining. Or at least put `10` and `9` in some variables that describe what is going on here. 
Curious of why you selected 10 and 9? 🤔

**Review by J-Son89 — APPROVED** [review]

File: src/js/worklets/shell.js (hunk 1 above)
Comment (Parveshdhull) [reply src/js/worklets/shell.js:25]: > Curious of why you selected 10 and 9?

Because, 10 > 9, no particular reason :)

Docs: https://reactnative.dev/docs/layout-props#zindex
Mighty z-index: https://www.digitalocean.com/community/tutorials/css-z-index
Somewhat related Discussions:
https://github.com/status-im/status-mobile/pull/13620#discussion_r962209277
https://github.com/status-im/status-mobile/pull/13620#discussion_r962210040

<details>
<summary> Usage in our project: (Filtered Unique) </summary>



</details>

> this seems like something that might benefit from having a comment explaining. Or at least put 10 and 9 in some variables that describe what is going on here.

suggestions are welcome

**Comment by qoqobolo** [comment]
~Finally~  looks good to me :D
@Parveshdhull thanks again for your great work!
PR can be merged.
