### PR TITLE
Messages read back button

### LINKED ISSUE #16151: Messages are marked as read automatically in chats if using back button
# Bug Report

## Problem 
Was introduced in https://github.com/status-im/status-mobile/pull/15204 (cc @alwx )
Previously existed with swipe back button and was fixed at release scope in https://github.com/status-im/status-mobile/pull/16035

#### Expected behavior
messages are read immediately 

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/f1a4c206-0e37-4e8b-8b0b-ce4a11463f93

### Reproduction

1) Open Status, open 1-1 chat
2) Go back using `back` button at top header
3) receive new messages

### Additional Information

- Status version: nightly 02/06/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by vkjr**
fixes #16151 #16183

### Summary

- fixed issue when all new messages immediately marked as read in a chat where the "back" button was used
- "edit community" action replaced with toast until new screens are available

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im2/contexts/communities/actions/community_options/view.cljs [hunk 1]
```diff
@@ -105,8 +105,7 @@
   {:icon                :i/edit
    :label               (i18n/label :t/edit-community)
    :accessibility-label :edit-community
-   :on-press            #(rf/dispatch [:communities/open-edit-community id]
-                                      (rf/dispatch [:hide-bottom-sheet]))})
+   :on-press            #(js/alert (str "implement action" id))})
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/actions/community_options/view.cljs]: It would be nice if we could make a standardized alert for these features so the message/ui is always the same. Maybe we could start with this pr as it's small in scope, similar to how we are using the red border in the app

Comment (vkjr) [reply src/status_im2/contexts/communities/actions/community_options/view.cljs]: @J-Son89, I don't mind. For me, the action id in that alert doesn't look necessary. We can use something simple like "not implemented". Wdyt?
cc @qoqobolo

Comment (J-Son89) [reply src/status_im2/contexts/communities/actions/community_options/view.cljs]: I guess it doesn't really matter what we use if we have a common function /component as we then only have to update it in one place 😀 
That sounds good to me 👍

Comment (flexsurfer) [inline src/status_im2/contexts/communities/actions/community_options/view.cljs]: lets just remove this button, we don't need it

**Review by flexsurfer — CHANGES_REQUESTED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@vkjr thanx for the PR! Issue with read messages is partially fixed but there is another way how it can be still reproduced:

### ISSUE Messages are read automatically if user closed chat by following community link

**Preconditions:** User A and B are contacts. 

**Steps:** 

1. User A shares community to User B (create community - longtap on community - share community)
2. User B follows community link from 1-1 chat (as a result User B will be redirected to community screen)
4. User A sends some messages in 1-1 chat
5. See if messages are not read for User B in 1-1 chat

**Actual result:** messages are read automatically. 


https://github.com/status-im/status-mobile/assets/97245802/c823b4d4-d449-4ca6-a984-b66a2c42dd48

**Comment by vkjr** [comment]
@pavloburykh, thanks for the finding! Fixed)

**Comment by pavloburykh** [comment]
@vkjr thanx for the fixes! Ready for merge. Failed e2e are not PR related.
