### PR TITLE
[#18280] Fix token images not being displayed

### LINKED ISSUE #18280: The logos are not fetched for assets
### Steps:
1. Recover the user with tokens
2. Take a look at the logos

### Actual result:
Logos 
image

### Expected result:
How it worked in Nightly [21 Dec 2023]
image

### ENV:
Nightly [22 Dec 2023]

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #18280

### Summary

Fixes the problem of token images not being displayed:

image

And also is able to receive `nil` values, cc: @J-Son89

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Go to wallet tab
- Test token images are displayed as before

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

File: src/quo/components/utilities/token/loader.cljs [hunk 1]
```diff
@@ -3,12 +3,13 @@
...
 
 (def ^:private tokens (loader/resolve-tokens))
+(def ^:private safe-lower-case (comp string/lower-case str))
 
 (defn- get-token-image*
   [token]
   (let [token-symbol (cond-> token
                        (keyword? token) name
-                       :always          (comp string/lower-case str))]
+                       :always          safe-lower-case)]
```
Comment (OmarBasem) [inline src/quo/components/utilities/token/loader.cljs:12]: I am curious, isn't that the same thing?

Comment (briansztamfater) [reply src/quo/components/utilities/token/loader.cljs:12]: I am curious too!

Comment (smohamedjavid) [reply src/quo/components/utilities/token/loader.cljs:12]: The bug is actually due to passing the `token` to the `comp` macro (due to using `cond->`) instead of performing the composite function on it.

When we use `cond->`, it passes the `token` as the first argument to `comp`, which includes the token as one of the composite functions, rather than performing the result composite function on the token.

Moving it to separate variables ensures it.

**Review by smohamedjavid — APPROVED** [review]

**Review by OmarBasem — APPROVED** [review]

File: src/quo/components/utilities/token/loader.cljs (hunk 1 above)
Comment (OmarBasem) [reply src/quo/components/utilities/token/loader.cljs:12]: Thanks @smohamedjavid !

Comment (shivekkhurana) [reply src/quo/components/utilities/token/loader.cljs:12]: That's such a fine detail.

**Review by shivekkhurana — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks @ulisesmac , LGTM!
PR can be merged.

**Review by vkjr — APPROVED** [review]

File: src/quo/components/utilities/token/loader.cljs [hunk 2]
```diff
@@ -3,12 +3,13 @@
   (:require [clojure.string :as string]))
 
 (def ^:private tokens (loader/resolve-tokens))
+(def ^:private safe-lower-case (comp string/lower-case str))
```
Comment (ilmotta) [inline src/quo/components/utilities/token/loader.cljs:6]: @ulisesmac, I think ideally this function should've been defined in `utils.string`. There we already have other `safe-*` functions.
