### PR TITLE
Fix chat navigation buttons when scrolling to top

### LINKED ISSUE #19095: Fix the background of navbar buttons in chat header
# Bug Report

## Problem 
[Design feedback](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=8065:58901&mode=design#644977141) follow-up

Currently the buttons in the chat navigation bar use the `:blur` background while in the designs the background should become `:photo` (has a lighter color) when scrolled to the top.

#### Expected behavior

The navigation buttons (back/more) in the chat have the :photo background while the navbar is transparent (i.e scrolled to the top) and :blur when opaque (i.e. while scrolling through messages)

#### Actual behavior
The navigation buttons always have the :blur background

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19095 

### Summary
The navigation buttons (back/more) in the chat have the :photo background while the navbar is transparent (i.e scrolled to the top) and :blur when opaque (i.e. while scrolling through messages)

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Login
- Open chat
- Scroll to top
- Navigation buttons should change background from `:blur` to `:photo` as header becomes transparent

### Before and after screenshots comparison

https://github.com/status-im/status-mobile/assets/21865759/146331fe-3ab9-47ef-a102-3b787967d147

status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/messages/navigation/view.cljs [hunk 1]
```diff
@@ -103,15 +104,20 @@
...
         top-insets                           (safe-area/get-top)
         top-bar-height                       messages.constants/top-bar-height
-        navigation-view-height               (+ top-bar-height top-insets)]
-    (reanimated/set-shared-value all-loaded? all-loaded-sub)
+        navigation-view-height               (+ top-bar-height top-insets)
+        reached-top?                         (messages.worklets/use-messages-scrolled-to-top
+                                              distance-from-list-top
+                                              top-bar-height)
+        button-background                    (if reached-top? :photo :blur)]
+    (rn/use-effect (fn [] (reanimated/set-shared-value all-loaded? all-loaded-sub))
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/navigation/view.cljs:121]: hi @flexsurfer, Do we have `use-sub-as-shared-value` feature?

File: src/utils/worklets/chat/messenger/messages.cljs [hunk 2]
```diff
@@ -5,3 +5,9 @@
 (defn messages-list-on-scroll
   [distance-from-list-top chat-list-scroll-y callback]
   (.messagesListOnScroll ^js worklets distance-from-list-top chat-list-scroll-y callback))
+
+(defn use-messages-scrolled-to-top
+  "Returns true if `distance-from-list-top` (animated value) crossed the threshold.
+  e.g. reaching the very top would need a threshold of `0`"
```
Comment (Parveshdhull) [inline src/utils/worklets/chat/messenger/messages.cljs]: Or we can use just another name for this? Maybe something like, `.....-scrolled-to-threshold`

**Review by Parveshdhull — APPROVED** [review]
lgtm, thank you for fixing this.

File: src/status_im/contexts/chat/messenger/messages/navigation/view.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/navigation/view.cljs:121]: is this to avoid the re-render when `all-loaded-sub` changes?

File: src/utils/worklets/chat/messenger/messages.cljs (hunk 2 above)
Comment (clauxx) [reply src/utils/worklets/chat/messenger/messages.cljs]: yeah that's a good point :+1:

File: src/status_im/contexts/chat/messenger/messages/navigation/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/contexts/chat/messenger/messages/navigation/view.cljs:121]: yes, I think we don' have this feature yet.
Related discussion - https://discord.com/channels/1103692771585433630/1172149795956203530/1210158688699027507

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/navigation/view.cljs:121]: > hi @flexsurfer, Do we have `use-sub-as-shared-value` feature?

not yet :( https://github.com/status-im/status-mobile/issues/18946

**Review by flexsurfer — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx ! Thanks for your fix!
Main scenario works great.

I have found such behaviour and wonder if it is related or/and could be mentioned here in this PR.

ISSUE 1: navigation button change it's blur background when reopening chat and scroll

Steps: 

1. Login to app
2. Add 2 or more contacts
3. Create Group Chat
4. Send messages and images to create scrollable content
5. Reopen group chat and scroll

Actual result: navigation button change it's blur background when reopening chat and scroll. It firstly has much transparent  background as it changes after. 

https://github.com/status-im/status-mobile/assets/147824399/4d5ba280-f453-4166-b336-c67dbfec65fb

https://github.com/status-im/status-mobile/assets/147824399/f176bced-29f1-4ea5-a761-805a845a2c01

**Comment by clauxx** [comment]
@mariia-skrypnyk i'm not sure if understand the issue from the videos

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk i'm not sure if understand the issue from the videos

Yes @clauxx , sorry. It it's not so obvious as I thought.
Let me show you on a screenshots:

it is the same chat and the same navigation icon on the background (x) but after starting to scroll and after you move to the start of conversation at the top of the chat

start
Screenshot 2024-03-11 at 15 58 57
after
Screenshot 2024-03-11 at 15 58 35

**Comment by mariia-skrypnyk** [comment]
> > @mariia-skrypnyk i'm not sure if understand the issue from the videos
> 
> Yes @clauxx , sorry. It it's not so obvious as I thought. Let me show you on a screenshots:
> 
> it is the same chat and the same navigation icon on the background (x) but after starting to scroll and after you move to the start of conversation at the top of the chat
> 
> start Screenshot 2024-03-11 at 15 58 57 after Screenshot 2024-03-11 at 15 58 35

 @clauxx were my details useful?

**Comment by clauxx** [comment]
> @clauxx were my details useful?

@mariia-skrypnyk sorry yes, got caught up with a different issue. It's much clearer from the screenshots :+1:

**Comment by clauxx** [comment]
@mariia-skrypnyk have a look again please

**Comment by mariia-skrypnyk** [comment]
Thanks @clauxx !
Navigation button is fixed now. Great job!

I observe such issue appeared in new build (Android). 
I've checked previous one and nightly and it's ok there.
Let me show you.

**ISSUE 2: Group details block reloads when user scrolls from the bottom to the top**

**Steps:**

1. Login to app
2. Add 2 or more contacts
3. Create Group Chat
4. Send messages and images to create scrollable content
5. Reopen group chat and scroll from the bottom to the top. Look at group details block during scrolling:
Screenshot 2024-03-13 at 15 19 59

https://github.com/status-im/status-mobile/assets/147824399/5a3e9267-fd5d-438b-8a56-0378cc7b788b

**Actual result:** Group details block reloads and user see it's blinking
**Expected result:** Group details block isn't reloading while scrolling

**Comment by clauxx** [comment]
@mariia-skrypnyk this isn't caused by this PR

**Comment by mariia-skrypnyk** [comment]
@clauxx thanks for investigating it, will move PR to the design review by @Francesca-G after e2e test.

**Review by Francesca-G — APPROVED** [review]
Looks good to me ✨
