### PR TITLE
[#21999] fix: disable manual auto refresh as new endpoint include auto refresh

### LINKED ISSUE #21999: "Сannot resolve route id" error is shown when attempting to approve or swap after the auto-refresh.
### Steps to reproduce:
1. Navigate to the Swap page.
2. Open the Approval or Swap Confirmation page.
3. Wait 10 seconds until the auto-refresh is triggered.
4. Attempt to approve or perform the swap transaction.

### Actual result:
The error "Cannot resolve route ID" is displayed when attempting to approve or swap after the auto-refresh.

https://github.com/user-attachments/assets/6d018357-684e-4017-bc70-a53345bd7612

### Expected result:
The transaction should proceed successfully after auto-refresh

### Environment:
Nightly 29 Jan, 2025

### Devices:
Pixel 7a (Android 15)
iPhone 11 Pro Max (iOS 17)

### Logs:
https://drive.google.com/file/d/1nZu0tVyrhBtX5RNPnCpcQ0z9MQ7hG7tU/view?usp=drive_link

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21999 

## Summary
The error "Cannot resolve route ID" is displayed when attempting to approve or swap after the auto-refresh.

### Areas that may be impacted

- Swap flow ( approval and Confirmation)

## Steps to test

1. Navigate to the Swap page.
2. Open the Approval or Swap Confirmation page.
3. Wait 10 seconds until the auto-refresh is triggered.
4. Attempt to approve or perform the swap transaction.

## Result 

https://github.com/user-attachments/assets/0670b381-111c-4ebf-86bd-50ca5fdd18ba

status: ready

### CODE REVIEW

**Comment by mohsen-ghafouri** [comment]
when we call `build-transactions-from-route` it will stop swap auto refresh logic, i need to move that logic to last step.

**Review by alwx — APPROVED** [review]
👍

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 1]
```diff
@@ -411,32 +411,31 @@
...
-         max-slippage      (get-in db [:wallet :ui :swap :max-slippage])]
-     {:fx [[:dispatch
-            [:wallet/build-transactions-from-route
-             {:request-uuid last-request-uuid
-              :slippage     max-slippage}]]
-           [:dispatch
-            [:wallet.swap/set-sign-transactions-callback-fx
-             [:dispatch [:open-modal :screen/wallet.swap-set-spending-cap]]]]]})))
+ (fn [_]
+   {:fx [[:dispatch [:open-modal :screen/wallet.swap-set-spending-cap]]]}))
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/swap/events.cljs]: Given we are just dispatching another event in the effects, maybe this event is not necessary anymore, and we could dispatch `:open-modal` directly instead.

**Review by briansztamfater — APPROVED** [review]

File: src/status_im/contexts/wallet/swap/events.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: Good point, applied .

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanks for the PR. Just curious, have you managed to identify if [sql: database is closed](https://github.com/status-im/status-mobile/issues/21999#issuecomment-2671354798) error is indeed related to the initial `Сannot resolve route id` issue? Just want to make sure it is related and does not have any other root cause in this case.

**Comment by mohsen-ghafouri** [comment]
Hey @pavloburykh, I saw that comment, but couldn't reproduce the issue in this PR. so i'm not sure if it's related to swap auto refresh or might be a regression of another changes.

**Comment by VolodLytvynenko** [comment]
hi @mohsen-ghafouri I noticed that autorefresh is not happening at all after waiting for 10 seconds. Previously, it was indicated by a loading state on the confirmation page
Is this an issue, or does autorefresh now happen implicitly without any visible UI indication?

**Comment by pavloburykh** [comment]
@mohsen-ghafouri I see there some conflicts in this PR. Please, let us know if PR needs to be re-tested after resolving.

**Comment by mohsen-ghafouri** [comment]
Hey @VolodLytvynenko, we now get update in the background and not manually refresh swap anymore. so there is no visible indicator for refresh. 

@pavloburykh the transaction settings has been merged and that might effect the swap flow. so please do another test. thanks

**Review by shivekkhurana — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
HI @mohsen-ghafouri take a look found issue in the latest build

## PR_ISSUE 1: "slide to swap" button is disabled

### Steps:
1. Go to swap confirmation page

### Actual result:
"slide to swap" button is disabled
image

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by mohsen-ghafouri** [comment]
Hey @VolodLytvynenko, thanks for checking it. could you please test again?

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri thank you for fixes. No issues from my side. PR is ready to be merged

**Comment by VolodLytvynenko** [comment]
Apologies. I hurried up to confirm merging the current PR, because  E2E tests is not run. Just restarted e2e tests. Will need an additional 30 minutes

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri e2e failure is not PR related. PR can be merged
