### PR TITLE
[#16846] fix: resolve glow issue in communities home

### LINKED ISSUE #16846: Design review: communities home
- [ ] 1. Joined, Pending, Opened looks smaller than at designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510253373)  
- [ ] 2. `Discover` there's a stroke and the shadow is missing **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254368)  

- [ ] 3. Glow in Communities is almost like a shadow around the titles in white mode **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254973)  

- [ ] 4. Spacing between communities in the list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258492)  
- [ ] 5. The unread indicator dot looks bigger than in the designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258717)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #16846

 3. Glow in Communities is almost like a shadow around the titles in white mode (Android only) - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254973)

Android

status: ready

### CODE REVIEW

File: src/status_im2/common/home/banner/view.cljs [hunk 1]
```diff
@@ -33,12 +33,13 @@
        :blur-type     (theme/theme-value (if platform/ios? :light :xlight) :dark)
        :overlay-color (if open-sheet?
                         (colors/theme-colors colors/white colors/neutral-95-opa-70)
-                        (theme/theme-value nil colors/neutral-95-opa-70))}]]))
+                        (theme/theme-value nil colors/neutral-95-opa-70))}
+      children]]))
```
Comment (ilmotta) [inline src/status_im2/common/home/banner/view.cljs]: @mohsen-ghafouri, If `banner-card-blur-layer` can accept multiple components as children, then we need to use a pattern like `[into [blur/view ...] children]` and change the function signature to be variadic, or at least that's the common convention.

But since `banner-card-blur-layer` only receives a child, I think we should rename `children` to `child` and avoid the unnecessary variadic signature.

File: src/status_im2/common/home/banner/style.cljs [hunk 2]
```diff
@@ -30,13 +34,15 @@
...
 (defn banner-card-hiding-layer
-  []
-  {:z-index     2
-   :position    :absolute
-   :top         0
-   :right       0
-   :left        0
-   :padding-top (safe-area/get-top)})
+  [scroll-shared-value]
+  (reanimated/apply-animations-to-style
```
Comment (ilmotta) [inline src/status_im2/common/home/banner/style.cljs:38]: @mohsen-ghafouri, could you share more details about why we need to change animation code to fix this blur issue?

Comment (mohsen-ghafouri) [reply src/status_im2/common/home/banner/style.cljs:38]: @ilmotta  blur view has an animation that moves it upwards during scroll mode. And to ensure the content inside the scroll remains in position, I need to apply a reverse translate.

Comment (ilmotta) [reply src/status_im2/common/home/banner/style.cljs:38]: Thanks!

File: src/status_im2/common/home/banner/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/common/home/banner/view.cljs]: In other words, the word `children` implies it's a collection, but a collection can't directly be added to a view. We get an exception. So that's the reasoning behind using the word in the singular or changing the function signature and code to properly deal with multiple child components.

Comment (mohsen-ghafouri) [reply src/status_im2/common/home/banner/view.cljs]: got it, thanks

**Review by ilmotta — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by OmarBasem** [comment]
@mohsen-ghafouri I think you mentioned in the chat that the glow issue is fixed by wrapping the content with another blur view. I don't see that being done here, or is this something else?

**Comment by mohsen-ghafouri** [comment]
> @mohsen-ghafouri I think you mentioned in the chat that the glow issue is fixed by wrapping the content with another blur view. I don't see that being done here, or is this something else?

@OmarBasem yes that one had some side effect issue, so instead of adding a new blur view i just moved the title content inside the current blur view.

**Review by OmarBasem — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
PR is ready for design review, @Francesca-G 🙂

**Review by Francesca-G — APPROVED** [review]
