### PR TITLE
Don't load chat view until chat is fetched

### LINKED ISSUE #19659: Channel fetching screen issues
Channel screen which appears in fetching state looks broken

**Steps:** 

1. Open any community which has not been opened/fetched on this account before
2. Open any channel while data is being fetched
3. Observe the result

**Expected result:** I have not found corresponding designs. Please, contact design team. 

**Actual result:** 

### ISSUE 3 'Add <no value> as contact to send a message' is displayed in footer

photo_2024-04-16 12 59 39

### ISSUE 4 Channel avatars are missing on community overview screen

photo_2024-04-16 12 59 43

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19659

### Video

https://github.com/status-im/status-mobile/assets/17097240/1b302014-2bdf-4775-8231-dd0e362b4e3f

### Testing
Issue 1, 2, 3 should be fixed

status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 1]
```diff
@@ -114,20 +114,20 @@
 
 (defn list-footer-avatar
   [{:keys [distance-from-list-top display-name online? profile-picture theme group-chat color
-           emoji chat-type chat-name last-message]}]
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs:117]: For chat screen we have a special subscription `:chats/current-chat-chat-view` which returns selected keys only to avoid unnecessary re-renders.

But in the sub we are also returning :last-message, which I think is one the most active key in chat object.

**Review by seanstrom — APPROVED** [review]
Looks good ✅ 
Nice change for turning `last-message` into `empty-chat?` 🙌

File: src/status_im/contexts/chat/messenger/messages/view.cljs [hunk 2]
```diff
@@ -13,13 +13,15 @@
...
-  (let [alert-banners-top-margin (rf/sub [:alert-banners/top-margin])]
-    [rn/keyboard-avoiding-view
-     {:style                    style/keyboard-avoiding-container
-      :keyboard-vertical-offset (- (if platform/ios? alert-banners-top-margin 0) (:bottom insets))}
-     [list.view/messages-list-content props]
-     [messages.navigation/view props]
-     [composer.view/composer props]]))
+  (let [alert-banners-top-margin (rf/sub [:alert-banners/top-margin])
+        chat-exist?              (rf/sub [:chats/current-chat-exist?])]
+    (when chat-exist?
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/messenger/messages/view.cljs:18]: empty screen will be opened?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/messages/view.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im/contexts/chat/messenger/messages/view.cljs:18]: Thank you @flexsurfer for reviewing PR.
As you can see here https://github.com/status-im/status-mobile/blob/12515a49046938f688a75e89316e0d4149933dc5/src/status_im/contexts/chat/messenger/messages/view.cljs#L45, chat view is above placeholder/loading skeleton. So until chat is fetched user will just see loading skeleton.

**Comment by J-Son89** [comment]
can you include a video/ some screenshots of how this looks? 
Will give a better understanding of how these changes work then 👍

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 3]
```diff
@@ -114,20 +114,20 @@
...
+           emoji chat-type chat-name empty-chat?]}]
   (let [scale              (reanimated/interpolate
                             distance-from-list-top
-                            [0 (if (seq last-message) messages.constants/header-container-top-margin 0)]
+                            [0 (if empty-chat? 0 messages.constants/header-container-top-margin)]
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs:120]: no strong opinions but maybe it's better to abstract to a helper function?

File: src/status_im/subs/chats.cljs [hunk 4]
```diff
@@ -169,23 +169,31 @@
...
+                  :chat-name
+                  :synced-to
+                  :synced-from
+                  :community-id
+                  :emoji
+                  :description])
+    :empty-chat?
+    (not (:last-message current-chat)))))
+
+(re-frame/reg-sub
```
Comment (J-Son89) [inline src/status_im/subs/chats.cljs:192]: can we include unit tests to cover our subs?
cc @ilmotta

Comment (ilmotta) [reply src/status_im/subs/chats.cljs:192]: @J-Son89, @Parveshdhull, we have this guideline already in the repo:

```
#### Subscription tests

Test [layer-3 subscriptions](https://day8.github.io/re-frame/subscriptions/) by
actually subscribing to them, so reframe's signal graph gets validated too.
```

But there's currently no mention of when a layer-3 should be tested. The easiest guideline is to always test layer-3 subs of course, but this one in this PR is actually so trivial that it's fine not to test it. Testing it would be almost like testing Clojure itself.

This sub is what I like to think as an `extractor from a layer-3 sub`, and because we don't test extractor subs (layer-2), to me it seems fine to not test extractors from layer-3 subs as well.

Does any of that make sense to you guys?

Comment (J-Son89) [reply src/status_im/subs/chats.cljs:192]: sure, I was also wondering if the original layer-3 has tests covering it. 
Makes sense not to test the extractor subs ofc 👍

**Comment by Parveshdhull** [comment]
Thank you @ilmotta and @J-Son89 for reviewing PR.

It seems `(boolean current-chat)` was not enough for checking existence of the chat. Because even when there was no chat with `current-chat-id` in `:chats`, `chats/current-chat-chat-view` still had some values like `:able-to-send-message?`. Probably being added here
https://github.com/status-im/status-mobile/blob/d658fcf3db8724999d76c128976ffd5bd8cceb66/src/status_im/subs/chats.cljs#L134

So updated the subscription to `(boolean (:chat-id current-chat))` and added tests accordingly.

> can you include a video/ some screenshots of how this looks?

Updated the PR description with the video. thank you

File: src/status_im/contexts/wallet/wallet_connect/utils.cljs [hunk 5]
```diff
@@ -1,10 +1,10 @@
 (ns status-im.contexts.wallet.wallet-connect.utils
   ;; NOTE: Not sorting namespaces since @walletconnect/react-native-compat should be the first
   #_{:clj-kondo/ignore [:unsorted-required-namespaces]}
-  (:require ["@walletconnect/react-native-compat"]
-            ["@walletconnect/core" :refer [Core]]
-            ["@walletconnect/web3wallet" :refer [Web3Wallet]]
+  (:require ["@walletconnect/core" :refer [Core]]
+            ["@walletconnect/react-native-compat"]
```
Comment (Parveshdhull) [inline src/status_im/contexts/wallet/wallet_connect/utils.cljs]: File updated by `make lint-fix`

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the PR! It looks good to me. 

The only problem I am thinking about is that there is no way to close this screen on IOS while cannel is in loading state. 

On Android we can only go back by using system back button. 

Maybe we still need to show close button in top left corner? WDYT?

photo_2024-05-16 14 33 23

**Comment by Parveshdhull** [comment]
> Maybe we still need to show close button in to left corner? WDYT?

yes, that sounds good. Pushing changes with close button

**Comment by Parveshdhull** [comment]
> Pushing changes with close button

done, please let me if looks ok

**Comment by pavloburykh** [comment]
> > Pushing changes with close button
> 
> done, please let me if looks ok

Thanks @Parveshdhull! Looks good to me. 

Please, take a look at another issue

### ISSUE 1 Skeleton remains after channel has been fetched, channel icon, header are wrong

**Steps:** 

1. Open any channel which has not been opened/fetched by this account before
2. Wait until channel is fetched 
3. Observe the result

**Actual result:** Skeleton remains after channel has been fetched, channel icon is wrong

photo_2024-05-16 17 56 13

https://github.com/status-im/status-mobile/assets/97245802/3340e068-62dc-4b02-97cd-de392633803a

**Comment by pavloburykh** [comment]
Thanks for the PR @Parveshdhull! It is ready for merge now. 

ISSUE 1 is not related to this PR and is fixed by @Parveshdhull here https://github.com/status-im/status-mobile/pull/20093
