### PR TITLE
[16137] Disable text description in lightbox for now

### LINKED ISSUE #16137: remove description when gallery is opened to prevent display issue
# Bug Report

## Problem 
Issue to prevent https://github.com/status-im/status-mobile/issues/16107 - best way not to show it for now

https://user-images.githubusercontent.com/22799766/242329994-280e16e1-d907-4441-9ddf-a16ebfba206c.png

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16137

### Summary

Need to disable text preview in lightbox when opening an image/album for better UX

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/lightbox/bottom_view.cljs [hunk 1]
```diff
@@ -49,14 +49,14 @@
...
-  (let [text               (get-in (first messages) [:content :text])
+  (let [_text              (get-in (first messages) [:content :text])
         padding-horizontal (- (/ item-width 2) (/ c/focused-image-size 2))]
     [reanimated/linear-gradient
      {:colors [:black :transparent]
       :start  {:x 0 :y 1}
       :end    {:x 0 :y 0}
       :style  (style/gradient-container insets animations derived)}
-     [rn/text {:style style/text-style} text]
+     #_[rn/text {:style style/text-style} text]
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/lightbox/bottom_view.cljs]: there should also be an issue to reenable this feature. 

Can you leave a TODO with that issue? If the follow up issue does not exist please create one 👍

**Comment by OmarBasem** [comment]
I don't think this is needed. I am currently working on this feature anyways.

**Comment by ibrkhalil** [comment]
> I don't think this is needed. I am currently working on this feature anyways.

Alright, Closing as it'll be fixed by you Omar.
Thank you

**Comment by J-Son89** [comment]
@ibrkhalil, @OmarBasem as part of current descoping process removing this feature was requested so we can focus on other priorities without halfway baked UX implementations. Afaik You should reopen this pr @ibrkhalil and @OmarBasem you should park working on that feature and focus on other decided priorities. 
Maybe confirm with @cammellos or @qoqobolo

**Comment by ibrkhalil** [comment]
> @ibrkhalil, @OmarBasem as part of current descoping process removing this feature was requested so we can focus on other priorities without halfway baked UX implementations. Afaik You should reopen this pr @ibrkhalil and @OmarBasem you should park working on that feature and focus on other decided priorities. Maybe confirm with @cammellos or @qoqobolo

Reopening it just in case we needed to hide it for next release.

**Comment by qoqobolo** [comment]
@ibrkhalil @OmarBasem confirming that we should disable text description in lightbox for now

**Review by OmarBasem — APPROVED** [review]

File: src/status_im2/contexts/chat/lightbox/bottom_view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/contexts/chat/lightbox/bottom_view.cljs]: I think we should not disable code like this. We should at least define a boolean var and use it to switch on/off the feature. Even if we're just temporarily disabling it, the var approach is just as easy as using `#_` and much clearer for other devs.

**Review by ilmotta — CHANGES_REQUESTED** [review]

**Comment by OmarBasem** [comment]
@J-Son89 @qoqobolo just wondering why are we parking development on the images lightbox. Isn't it part of the one-to-one chats?

**Comment by ibrkhalil** [comment]
@ilmotta I actually felt code smell when doing it :)
Thanks for correcting me Icaro 🚀

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/chat/lightbox/bottom_view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im2/contexts/chat/lightbox/bottom_view.cljs]: It would be nice to have a common variable for this, like `disabled-features`. We can reuse this across similar places in the app so that we can easily find them 👍

**Comment by J-Son89** [comment]
> @J-Son89 @qoqobolo just wondering why are we parking development on the images lightbox. Isn't it part of the one-to-one chats?

@OmarBasem as I understand it, we are not parking development on the lightbox, only the text preview on lightbox images. Apologies if my previous message was unclear/confusing. Let's discuss on discord server if there's still some doubts :)

**Comment by qoqobolo** [comment]
Hey @ibrkhalil, could you rebase this PR, please?
Thanks

**Comment by ibrkhalil** [comment]
> Hey @ibrkhalil, could you rebase this PR, please? Thanks

Done, Thank you

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil PR is tested and ready to be merged. Thank you!
