### PR TITLE
[#22522] fix: apply new router changes

### LINKED ISSUE #22522: `Paraswap: Unable to build transaction (1001)` error sometimes occurs when setting up swap transaction
### Steps:
1. Go to setup swap screen
2. Select any tokens 
4. See if there are no errors and you can proceed to Review Swap step

### Actual result: 
`Paraswap error: Unable to build transaction (1001)`

Assets and network on which the issue is reproducible:
- On L1: ETH -> USDC, DAI -> ETH
- On L2 arb and opt it is not so often reproducible as on L1, but reproduced once or ARB with DAI -> ETH
- On BSC: BNB -> ETH @pavloburykh encountered on BSC when tested [this](https://github.com/status-im/status-mobile/pull/22417) PR

https://github.com/user-attachments/assets/8fc928a3-a8e1-402c-9866-b9426081e284

### Logs:
[logs](https://drive.google.com/file/d/19Arto6lAc4leFC_Wn_vfX2xZ5t4R3bn6/view?usp=drive_link)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #22522

## Summary
 
There are some changes in build transaction route and get suggested route, here is more details https://github.com/status-im/status-go/pull/6548#issue-3012148909

### Areas that may be impacted

- Swap, Send

## Steps to test

1. Go to setup swap screen
2. Select any tokens 
4. See if there are no errors and you can proceed to Review Swap step

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -551,58 +551,64 @@
...
-                                         :tokenID              token-id
-                                         :toTokenID            to-token-id
-                                         :disabledFromChainIDs disabled-from-chain-ids
-                                         :disabledToChainIDs   disabled-to-chain-ids
-                                         :gasFeeMode           gas-rates
-                                         :fromLockedAmount     {}
-                                         :username             (:username args)
-                                         :publicKey            (:publicKey args)
-                                         :packID               (:packID args)}]]
+                 network bridge-to-chain-id max-slippage]
```
Comment (mohsen-ghafouri) [inline src/status_im/contexts/wallet/send/events.cljs:549]: I only added `max-slippage` here and pass it to api params as `:slippagePercentage`

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 2]
```diff
@@ -123,49 +123,57 @@
...
-                                    :addrTo               to-address
-                                    :tokenID              pay-token-id
-                                    :toTokenID            receive-token-id
-                                    :disabledFromChainIDs disabled-from-chain-ids
-                                    :disabledToChainIDs   disabled-to-chain-ids
-                                    :gasFeeMode           gas-rates
-                                    :fromLockedAmount     from-locked-amount
-                                    :amountOut            (or amount-out-hex "0x0")}
-                                   amount-in (assoc :amountIn amount-in-hex))]]
+                network max-slippage]
```
Comment (mohsen-ghafouri) [inline src/status_im/contexts/wallet/swap/events.cljs:140]: Here is also the same changes to get `max-slippage` and pass it to api params as `:slippagePercentage`

**Review by clauxx — APPROVED** [review]
Looks good 👍

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanks for the PR. Please take a look at the issue. 

### ISSUE 1 Activity tab is empty after performing send/swap/bridge transactions

@mohsen-ghafouri I believe this is PR related bug, because it is not reproducible on latest nightly build. 

**Steps:** 

1. Perform send/swap/bridge transaction
2. Check activity tab and see if tx has appeared in tx history

**Expected result:** tx has appeared in Activity tab

**Actual result:** Activity tab is empty 

[logs](https://drive.google.com/file/d/1TqGluEfLm2X4Xl-HaMQRUeginGAX_vhz/view?usp=drive_link)

https://github.com/user-attachments/assets/5a5fceeb-a94f-4b44-bb3a-f6181739f00f

**Comment by pavloburykh** [comment]
**UPDATE:** [ISSUE 1](https://github.com/status-im/status-mobile/pull/22556#issuecomment-2829846145) is reproducible on Desktop as well, so this is a backend issue. 

Video from Desktop https://drive.google.com/file/d/1Gfwa3VNkTa1UZgBgv-A_Cxx7Q0AwjkTL/view?usp=drive_link

**Review by shivekkhurana — APPROVED** [review]

**Comment by pavloburykh** [comment]
### ISSUE 2 `failed to build transaction after 3 retries` sometimes appears while building route on swap

@saledjenic unfortunately this error is still appearing from time to time. 

Please see screenshot and video below. 

**Steps:** 

1. Go to swap
2. Enter amount
3. See if route has been build without errors

**Actual result:** `failed to build transaction after 3 retries` error still appears from time to time

[Logs](https://drive.google.com/file/d/1u-brBPZuuEOfO17NfKBZmr6F0ckPYqe8/view?usp=drive_link)

photo_2025-04-28 10 43 18

https://github.com/user-attachments/assets/863440ac-afca-4b90-b08c-d1fa8ffed398

**Comment by VolodLytvynenko** [comment]
@saledjenic The [issue 2](https://github.com/status-im/status-mobile/pull/22556#issuecomment-2834282312) is very often reproducible for me as well, and it exists on Desktop too (I'm quite sure it's the same error, although on Desktop it either displays differently or there might be an additional error overlapping it :).
There are no exact steps to reproduce it, but it happens frequently - approximately every 5th try 

image

**Comment by pavloburykh** [comment]
@mohsen-ghafouri we have decided to merge this PR and continue testing in BNB chain PR. So let's merge it.

**Comment by mohsen-ghafouri** [comment]
Thanks @pavloburykh, waiting for status-go PR to be merged.
