### PR TITLE
[#15741] Fix error on tapping pinned message

### LINKED ISSUE #15741: Error when tapping on pinned message inside pinned messages bottom sheet (IOS)
# Bug Report

## Problem 
Follow up on #15689

#### Expected behavior
no error

#### Actual behavior
IMAGE 2023-04-25 16:49:20

### Reproduction

**Steps:**
1) tap on the pinned message inside pinned bottom sheet

### Additional Information

- Status version: nightly 26/04/23
- Operating System: iOS
- Logs: [logs (33).zip](https://github.com/status-im/status-mobile/files/11323768/logs.33.zip)

### PR DESCRIPTION
**Pull request by rasom**
fix #15741

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 1]
```diff
@@ -97,7 +97,7 @@
           :style               {:border-radius 16
                                 :opacity       (if (and outgoing (= outgoing-status :sending)) 0.5 1)}
           :on-press            (fn []
-                                 (if (and platform/ios? @keyboard-shown)
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: @rasom, I understand the scope is for a fix, but what's going on under the hood is more important imo. The atom should be defined in the first place, so the fix to me should be somewhere else.

I traced the argument `keyboard-shown` and found a place where it's not passed as an arg https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/chat/menus/pinned_messages/view.cljs#L20

Unfortunately hiccup is a bit nasty, because `[message/message-with-reactions message context]` is a vector, there's nothing checking that the `message/message-with-reactions` arity is wrong. Look what I get if I change the vector to a function call, I get a warning from clj-kondo and the code won't actually compile.

` invalid-arity status-im2.contexts.chat.messages.content.view/message-with-reactions is called with 2 args but expects 3 (lsp)
`

So I think the correct fix is to fix the bad hiccup https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/chat/menus/pinned_messages/view.cljs#L20 and pass along the `keyboard-shown` atom. You'll need to create it and pass it as the render-data of the flat-list https://github.com/status-im/status-mobile/blob/0649c66ddef3334da34888a60c57109246163d55/src/status_im2/contexts/chat/menus/pinned_messages/view.cljs#L51

These days I hardly like hiccup... so much trouble for so little, anyway.

Comment (OmarBasem) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: @ilmotta is there something bad with passing `(atom false)` as a third argument to https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/chat/menus/pinned_messages/view.cljs#L20 ?

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: I think it's fine @OmarBasem, as long as we respect the function arity and don't pass an atom as `undefined` it's better.

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: Maybe for the future, not in this PR, but the "perfect" fix could be to avoid passing `keyboard-shown` all the way down do other components and instead use a hook right at the place where it's needed. The hook would probably be similar or identical to the one we discussed these days here https://github.com/status-im/status-mobile/pull/15736#discussion_r1176616926

Comment (OmarBasem) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: @ilmotta I don't think that would be a better solution. The `keyboard-shown` value is needed when pressing on a message. Defining the hook in the message component we would create a new hook for every message.

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: Correct, hooks are cheap, but not that cheap. For long lists of things it's not a good idea, good point :)

Comment (rasom) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: hey guys, changed it to `(atom false)`, thanks

**Review by ilmotta — APPROVED** [review]
Thanks for taking the time to try a different fix @rasom.

**Review by OmarBasem — APPROVED** [review]
