### PR TITLE
Fix seen statuses

### LINKED ISSUE #4425: No 'Seen' message status on sender side after message receiver read it in 1-1 chat
***Type***: Bug

***Summary***: There is no 'Seen' status next to the message on sender side after message receiver read the message. 
In the https://github.com/status-im/status-react/issues/4395 we fixed the part to actually receive messages. This issue dedicated to returning back 'Seen' status.

#### Expected behavior
'Seen' message status displayed on sender side once the actual message is read by the receiver. 

#### Actual behavior
No 'Seen' message status (Always 'Sent') displayed on sender side once the actual message is read by the receiver. 

### Reproduction

- Open Status on Device1 and Device2
- Create Contact1 and Contact2 respectively
- Contact1 sends a contact request to Contact2
- Both contacts navigate to 1-1 chat screen
- Contact1 sends a text/emoji/request/send message

### Additional Information
* Status version: Develop (nightly 402nd Jenkins build)
* Operating System: Android and iOS

#### Logs

TF session for message sender:  https://app.testfairy.com/projects/4803590-status/builds/8359082/sessions/24/?accessToken=mKG-UltoxGHHcJdj3cEE79gpgGU
TF session for message receiver: https://app.testfairy.com/projects/4803622-status/builds/8358999/sessions/54/?accessToken=hGlYT95dSVuUcDu-8facKsM8YmM

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8359082/sessions/24/?accessToken=mKG-UltoxGHHcJdj3cEE79gpgGU">TestFairy: Status build-6008-6-g502e8b99 (2667) @24</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8358999/sessions/54/?accessToken=hGlYT95dSVuUcDu-8facKsM8YmM">TestFairy: Status build-6009+ (6009) @54</a></strong></div></blockquote>

### LINKED ISSUE #4486: More than one "/request" or "/sent" message is shown when app is opened from notification
### Description

*Type*: Bug

*Summary*: When the app is opened from notification with "/request" message, the message is shown couple of times in a row. Also, it sticks to the bottom of the chat even when new messages are sent or received. I could not reproduce it for other types of messages than "/request". 

It's worth nothing that it happens after "connecting to peers" and "fetching messages" statuses appear. 

#### Expected behavior
Only one "/request" message is shown. 

#### Actual behavior
More than one "/request" messages are shown when app is opened from the notification.

### Reproduction

- Open Status on 2 devices
- Create 1:1 chat
- Device A: Open 1:1 chat and then put app in background
- Device B: Request tokens in 1:1 chat (send "/request" message) from device A
- Device A: Open the incoming notification 

### Additional Information
* Status version: nightly, 28 May
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #4425 

### Summary:

Quick and dirty fix, just passing `:js-obj` through cofx (that's quite fitting, as the raw message is just co-effect cause in the handler), so it's omitted from id generation, and id's are consistent. 
Please check if it fixes #4486 as well, as it's quite likely.

### Testing notes (optional):
Check that the bug doesn't happen anymore, + check that message de-duplication still works the same as before.

status: ready

### CODE REVIEW

File: src/status_im/data_store/core.cljs [hunk 1]
```diff
@@ -21,9 +21,7 @@
   (data-source/change-account address new-account? encryption-key handler))
 
 (defn- perform-transactions [raw-transactions realm]
-  (let [success-events (->> raw-transactions
-                            (map :success-event)
-                            (filter identity))
+  (let [success-events (keep :success-event raw-transactions)
```
Comment (cammellos) [inline src/status_im/data_store/core.cljs:24]: thanks, did not know that!

File: src/status_im/chat/core.cljs [hunk 2]
```diff
@@ -1,20 +1,23 @@
...
+                  (fn [new-db message-id]
+                    (assoc-in new-db
+                              [:chats chat-id
+                               :messages message-id
+                               :user-statuses sender]
+                              :seen))
+                  db
+                  seen-messages-ids)]
+      {:db            new-db
+       :data-store/tx [(messages-store/update-messages-tx
```
Comment (cammellos) [inline src/status_im/chat/core.cljs]: I take this is something we were not doing before, and this fixes it, correct?

**Review by cammellos — APPROVED** [review]
Looks good to me,
messages will not be acknowledge to status go if we don't have `tx` as mentioned, not sure if it's worth a comment, but in any case not an issue at all.

File: src/status_im/chat/core.cljs (hunk 2 above)
Comment (rasom) [reply src/status_im/chat/core.cljs]: yes, we didn't update message's status before, which was a bug

File: src/status_im/transport/handlers.cljs [hunk 3]
```diff
@@ -22,21 +22,30 @@
...
       (message/receive status-message (or chat-id sig) sig cofx))))
 
-(defn- js-array->list [array]
+(defn- js-array->seq [array]
   (for [i (range (.-length array))]
     (aget array i)))
 
+(defn- add-messages-confirmation [fx js-messages]
+  ;; TODO janherich: we are ignoring `:data-store/base-tx` queue, revisit later
+  (if-let [transactions (:data-store/tx fx)]
```
Comment (rasom) [inline src/status_im/transport/handlers.cljs]: for 1-1 and pubchat messages only `:chat-received-message/add` will be added to fx, so this is not going to work

Comment (rasom) [inline src/status_im/transport/handlers.cljs]: also transactions is not used

**Review by rasom — CHANGES_REQUESTED** [review]
see comments

File: src/status_im/transport/handlers.cljs (hunk 3 above)
Comment (janherich) [reply src/status_im/transport/handlers.cljs]: Good point, thanks !

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/4p57B1 for branch PR-4442

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/VrELkt for branch PR-4442

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/2AJySP for branch PR-4442

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/J7Urdj for branch PR-4442

**Comment by janherich** [comment]
@rasom please review again, I degraded it to simple fix because fix is needed quite urgently (two release blockers attached to it), better solution requires through re-factoring and re-thinking the protocol (to actually adapt it to batch processing), I will write about that more in slack.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/m4v12Q for branch PR-4442

<blockquote><div><strong><a href="https://i.diawi.com/m4v12Q">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/VPkMrj for branch PR-4442

<blockquote><div><strong><a href="https://i.diawi.com/VPkMrj">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
> better solution requires through re-factoring and re-thinking the protocol (to actually adapt it to batch processing)

and also resolving of cyclic deps related to `:chat-received-message/add` in the first place ¯\\_(ツ)_/¯

**Comment by janherich** [comment]
@rasom True, but that's just matter of shuffling the namespaces and re-organising code little bit, no changes in function/protocol signatures or implementation.

**Review by rasom — APPROVED** [review]

**Comment by mandrigin** [comment]
@janherich can you rebase it, please?

**Comment by janherich** [comment]
@mandrigin Done

**Comment by mandrigin** [comment]
@janherich 
```
-                             (add-message-fn (cond-> message
+                             (add-message-fn (cond-> message
                                                public-key
                                                (assoc :user-statuses {public-key (if current-chat? :seen :received)})
                                                (not clock-value)
```
1 file(s) formatted incorrectly

unnecessary space after `(cond-> message `
