### PR TITLE
Reset database if version is 0.9.18

### LINKED ISSUE #4409: "Realm file decryption failed" error after app upgrade from release 0.9.18 to develop version
***Type***: Bug

***Summary***: `Unable to open a realm at path 'data/data/im.status.ethereum/filesdefault.realm': Realm file decryption failed` error appears when I open the app after upgrade from Release 0.9.18 to Develop build (`build-6009+` nightly 402th Jenkins build)

#### Expected behavior
No error after upgrade

#### Actual behavior
Error appears when I open the app after upgrade

screen shot 2018-05-24 at 10 06 49

### Reproduction

- Install Status 0.9.18 release version
- Upgrade to nightly build and open the app

### Additional Information
* Status version: `build-6009+` nightly 402th Jenkins build
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4409

### Summary:

The code will try to open an encrypted realm.
If it fails will try to open an unencrypted realm.

If that is successful we reset the database and create an encrypted version.

We ensure it is unencrypted as we don't want to reset the database if a IO error occurred on step 1.

### Testing notes (optional):

Should ask you to reset from 0.9.18, but update cleanly from 0.9.19/nightlies

status: ready

### CODE REVIEW

File: src/status_im/data_store/realm/core.cljs [hunk 1]
```diff
@@ -20,18 +20,18 @@
         (aset arr i (aget key i)))
       (.-buffer arr))))
 
-(defn realm-version
+(defn unencrypted-realm?
+  [file-name]
+  (boolean
+   (.schemaVersion rn-dependencies/realm file-name)))
```
Comment (jeluard) [inline src/status_im/data_store/realm/core.cljs]: Can you detail this function? Not sure how version and encryption are related.

File: src/status_im/data_store/realm/core.cljs [hunk 2]
```diff
@@ -20,18 +20,18 @@
...
-        (log/info "Attempting to read encrypted file failes")))
-    (try
-      (.schemaVersion rn-dependencies/realm file-name)
-      (catch js/Object e
-        (log/info "Attempting to read unencrypted file failed")))))
+  ;; we need to try this if previous version was using unencrypted database
+  (try
+    (.schemaVersion rn-dependencies/realm file-name (to-buffer encryption-key))
+    (catch js/Object e
+      (log/info "Attempting to read encrypted file failes"))))
```
Comment (jeluard) [inline src/status_im/data_store/realm/core.cljs]: Can we improve error handling? What if this fails ?
(I realize you didn't introduce this)

File: src/status_im/data_store/realm/core.cljs [hunk 3]
```diff
@@ -51,14 +51,29 @@
...
     (.close realm)))
 
-(defn migrate-realm [file-name schemas encryption-key]
-  (let [current-version (realm-version file-name encryption-key)]
-    (doseq [schema schemas
-            :when (> (:schemaVersion schema) current-version)
-            :let [migrated-realm (open-realm schema file-name encryption-key)]]
-      (close migrated-realm)))
+(defn reset-realm [file-name schemas encryption-key]
+  (utils/show-popup "Important: Wallet Upgrade" "The Status Wallet will be upgraded in this release. The 12 mnemonic words will generate different addresses and whisper identities (public key). Given that we changed the algorithm used to generate keys and addresses, it will be impossible to re-import accounts created with the old algorithm in Status. Please create a new account.")
```
Comment (jeluard) [inline src/status_im/data_store/realm/core.cljs]: Should this not be called outside of `reset`?

**Review by jeluard — CHANGES_REQUESTED** [review]

File: src/status_im/data_store/realm/core.cljs [hunk 4]
```diff
@@ -51,14 +51,29 @@
...
+          :when (> (:schemaVersion schema) current-version)
+          :let [migrated-realm (open-realm schema file-name encryption-key)]]
+    (close migrated-realm))
+  (open-realm (last schemas) file-name encryption-key))
+
+(defn migrate-realm [file-name schemas encryption-key]
+  (let [encrypted-version (encrypted-realm-version file-name encryption-key)
+        ;; If it's unencrypted reset schema
+        unencrypted?      (and (not encrypted-version)
+                               (unencrypted-realm? file-name))]
```
Comment (janherich) [inline src/status_im/data_store/realm/core.cljs]: What will happen if this is fresh install without any previous schema - won't `unencrypted?` be true ? 
If yes, will it work fine, or crash on the `reset-realm` schema (+ show confusing pop-up) ?

File: src/status_im/data_store/realm/core.cljs (hunk 1 above)
Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: We are just trying to open the file, to make sure it is unencrypted, basically we only care if it's successful or not.

File: src/status_im/data_store/realm/core.cljs (hunk 4 above)
Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: that's interesting, it seems like you are right, I had tested it on my local android and worked fine, but will make sure it works.

File: src/status_im/data_store/realm/core.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: In this case it's ok for us to fail, we want to detect unencrypted versions of realm, so we can reset them, once we remove the code I agree error handling should be made more robust.

File: src/status_im/data_store/realm/core.cljs (hunk 1 above)
Comment (jeluard) [reply src/status_im/data_store/realm/core.cljs]: I can think of others reason for this call to fail than just being unencrypted. Maybe we can find a better name? Or a safer method?

File: src/status_im/data_store/realm/core.cljs (hunk 3 above)
Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: not sure, it used to be there I have reintroduced it ( it seems resetting realm is a single purpouse thing, only applies for this release, should be throwaway code), but don't mind putting it outside.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/s7XwyV for branch PR-4503

<blockquote><div><strong><a href="https://i.diawi.com/s7XwyV">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/data_store/realm/core.cljs (hunk 2 above)
Comment (jeluard) [reply src/status_im/data_store/realm/core.cljs]: What about returning nil only and not logging then?

File: src/status_im/data_store/realm/core.cljs (hunk 3 above)
Comment (jeluard) [reply src/status_im/data_store/realm/core.cljs]: We might find other needs for this in the future. I would not expect that kind of side effects when calling a `reset` function.

File: src/status_im/data_store/realm/core.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: you mean just remove the log statement? (we need the schema version if it we manage to decrypt it)

Comment (jeluard) [reply src/status_im/data_store/realm/core.cljs]: Right in the catch

Comment (jeluard) [reply src/status_im/data_store/realm/core.cljs]: Hopefully this function does not only return nil :sweat_smile:

**Comment by jeluard** [comment]
Can we take this opportunity to add some simple doc to `realm` function? This would help improving the overall quality of this ns that requires some love :)

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/dcHStq for branch PR-4503

<blockquote><div><strong><a href="https://i.diawi.com/dcHStq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@jeluard yes, I will test everything works ( is still wip, I needed an image to test on a real device), and add some docs to the namespace

File: src/status_im/data_store/realm/core.cljs (hunk 4 above)
Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: Weirdly enough it just works, I can't really say why from the code (possibly because opening an empty realm will succede and return a version of `0`? ). But will make sure that is the case ,good shout.

Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: Yes, opening an empty realm does not fail, and return a schema version of `-1`

Comment (janherich) [reply src/status_im/data_store/realm/core.cljs]: Actually I know why, calling version on empty realm returns -1, I just remembered. It's probably worth documenting somewhere...

**Review by janherich — APPROVED** [review]

**Comment by cammellos** [comment]
@jeluard updated with docstrings and some tests

File: src/status_im/data_store/realm/core.cljs [hunk 5]
```diff
@@ -51,14 +57,35 @@
...
 
+(defn migrate-realm
+  "Migrate realm if is a compatible version or reset the database"
+  [file-name schemas encryption-key]
+  (let [encrypted-version (encrypted-realm-version file-name encryption-key)
+        ;; If it's unencrypted reset schema
+        unencrypted?      (and (not encrypted-version)
+                               (unencrypted-realm? file-name))]
+    (cond
+      encrypted-version (migrate-schemas file-name schemas encryption-key encrypted-version)
```
Comment (mandrigin) [inline src/status_im/data_store/realm/core.cljs]: is it fine to call `migrate-schemas` if `encrypted-version` is -1?

**Review by mandrigin — APPROVED** [review]
LGTM

File: src/status_im/data_store/realm/core.cljs (hunk 5 above)
Comment (cammellos) [reply src/status_im/data_store/realm/core.cljs]: I believe so,  I haven't changed that logic + I have tested multiple times on clean installations

**Comment by jeluard** [comment]
@cammellos Awesome thanks for the effort!

**Review by jeluard — APPROVED** [review]

File: src/status_im/data_store/realm/core.cljs (hunk 5 above)
Comment (mandrigin) [reply src/status_im/data_store/realm/core.cljs]: I would add a comment though, because it _looks_ like this case with -1 was just forgotten.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/SMKUoS for branch PR-4503

<blockquote><div><strong><a href="https://i.diawi.com/SMKUoS">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/yGqsQ7 for branch PR-4503

<blockquote><div><strong><a href="https://i.diawi.com/yGqsQ7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@cammellos all looks good 👍
I tested upgrading from 0.9.18 (Android, iOS) as well as from develop (iOS). I also checked some scenarios around it like recovering account, creating additional new account, etc.
