### PR TITLE
Disable scroll to the bottom button when composer is active.

### LINKED ISSUE #17364: 'Scroll down' button is not hidden behind the top bar when the composer is expanded [iOS]
# Bug Report

### Reproduction

1. Open a chat with some history
2. Scroll up until the `Scroll down` arrow-button appears
3. Expand the composer

iPhone SE
Screenshot 2023-09-20 at 17 51 08

iPhone 11 pro max
Screenshot 2023-09-20 at 17 51 31

iPhone 12 mini
Screenshot 2023-09-20 at 17 51 56

#### Expected behavior

This is how it works on Android: the `Scroll down` button is hidden behind the top bar

https://github.com/status-im/status-mobile/assets/67952253/10a8923c-306c-419e-8f56-1a40a491157b

### Additional Information

- Status version: nightly 20/09
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17364

Fixes a UX issue that made the scroll to the bottom button go to the top of the screen when composer is expanded.

| Figma (if available) | iOS (if available)    | Android (if available)
| --- | --- | --- |
| Please embed Image/Video here of the before and after.  |   |
Please embed Image/Video here of the before and after. |

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/composer/sub_view.cljs [hunk 1]
```diff
@@ -47,7 +47,8 @@
          :label               (i18n/label :t/jump-to)
          :style               {:align-self :center}}}
        {}]]
-     (when @show-floating-scroll-down-button?
+     (when (and (not @focused?)
+                @show-floating-scroll-down-button?)
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/sub_view.cljs:51]: Two things:

1. Should the scroll down button not be visible at all when focused?
2. If so, we can update `@show-floating-scroll-down-button?` to not be true unless the composer is not focused

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/composer/sub_view.cljs:51]: 1 yes
2 okay good idea will do

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/composer/sub_view.cljs:51]: Okay, When I started to implement the solution I realised that I'd have to get the composer state in the messages list state or vice versa, Which I don't think is a good idea.
We're going to have to pass the state of the composer (Where it's focused or not) to the messages list logic
What do you think about it?

Comment (OmarBasem) [reply src/status_im2/contexts/chat/composer/sub_view.cljs:51]: You can get if the input is focused using this subscription: `(:focused? (rf/sub [:chats/current-chat-input]))`

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/composer/sub_view.cljs:51]: Nice, Thanks

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/composer/sub_view.cljs:51]: Done, I couldn't use that subscription inside the on-scroll because it's executed only on scroll.
But I did it using another approach.

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/composer/sub_view.cljs:51]: @OmarBasem Kindly take another look.

File: src/status_im2/contexts/chat/composer/handlers.cljs [hunk 2]
```diff
@@ -18,10 +18,12 @@
    {:keys [text-value focused? lock-selection? saved-cursor-position gradient-z-index]}
    {:keys [height saved-height last-height opacity background-y gradient-opacity container-opacity]
     :as   animations}
-   {:keys [max-height] :as dimensions}]
+   {:keys [max-height] :as dimensions}
+   show-floating-scroll-down-button?]
   (reset! focused? true)
   (rf/dispatch [:chat.ui/set-input-focused true])
   (reanimated/animate height (reanimated/get-shared-value last-height))
+  (reset! show-floating-scroll-down-button? false)
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/handlers.cljs]: [nitpick]: Please move this line to the bottom of the function just for sake of organization

**Review by OmarBasem — APPROVED** [review]
Looks good 👍

File: src/status_im2/contexts/chat/composer/handlers.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/composer/handlers.cljs]: Will do before merging

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil the issue is still reproducible if the following steps are used:

## ISSUE 1: 'Scroll down' button is not hidden when the composer is active

### Steps:
1. Open a chat with some **long** history
2. Scroll up until the Scroll down arrow-button appears
3. Tap the composer while the chat is scrolling

### Actual result:
'Scroll down' button is not hidden when the composer is activated while the chat is scrolling

https://github.com/status-im/status-mobile/assets/52490791/ef893dba-f576-4098-b118-cbf1acedcccf

### Expected result:
The scroll down button is hidden if the if composer is active

### Device:
- IPhone 11 pro max, IOS 16
- Pixel 7a, Android 13

**Comment by ibrkhalil** [comment]
> hi @ibrkhalil the issue is still reproducible if the following steps are used:
> 
> ## ISSUE 1: 'Scroll down' button is not hidden when the composer is active
> ### Steps:
> 1. Open a chat with some **long** history
> 2. Scroll up until the Scroll down arrow-button appears
> 3. Tap the composer while the chat is scrolling
> 
> ### Actual result:
> 'Scroll down' button is not hidden when the composer is activated while the chat is scrolling
> 
>  scroll.mp4 
> ### Expected result:
> The scroll down button is hidden if the if composer is active
> 
> ### Device:
> * IPhone 11 pro max, IOS 16
> * Pixel 7a, Android 13

Fixed

**Comment by VolodLytvynenko** [comment]
@ibrkhalil Thank you for the fixes. No issues from my side. Ready to be merged
