### PR TITLE
Lightbox text sheet

### LINKED ISSUE #15389: "No protocol method DateTimeProtocol plus- defined for type null:" error on opening a sent image in chat
@OmarBasem probably a regression of some of recent PRs related to images

**Steps:**

1. Open any chat
2. Send a message containing image
3. Try to open image after sending

**Expected result:** image opens, no error

**Actual result:** "No protocol method DateTimeProtocol plus- defined for type null:" error appears, image is not opened. In case with messages containing more than 1 image - it is able to open them after re-entering chat, when images start showing as an album. See video below. 

[Status-debug-logs (23).zip](https://github.com/status-im/status-mobile/files/10991266/Status-debug-logs.23.zip)

https://user-images.githubusercontent.com/97245802/225630479-38a6f686-cce4-4059-ab45-344a6709667d.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #16106: Messaging - In Chat - View photo features
~background color not correct~. - Edit (Omar): done

text is not correct, verify size/designs - Edit (Omar): @J-Son89 implementing the text drawer seems to be the only remaining part in the lightbox screen. Should I implement it now?

top buttons not working/implemented yet (perhaps a follow-up issue) - Edit (Omar): https://github.com/status-im/status-mobile/pull/16268, https://github.com/status-im/status-mobile/pull/16224, and https://github.com/status-im/status-mobile/issues/16403

There should be padding/margin on the side of photos - Edit (Omar): currently having padding on the side causes problems with Shared element transition animation on iOS. I will wait for it until we upgrade RNN and reanimated versions (dependent on RN 0.71+)

Composer_for_Mobile_Figma_2023-05-30_17-17-01

Designs
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372677&t=uEhz2B0QJkxAitDo-4

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/16106
Also fixes: https://github.com/status-im/status-mobile/issues/15389

This PR implements text sheet in the lightbox.

Designs video: https://vimeo.com/728803861

Demo video:

https://github.com/status-im/status-mobile/assets/29354102/246fa9dd-4915-4e97-93d3-2e44aad84ca1

### CODE REVIEW

**Comment by OmarBasem** [comment]
Hi @Francesca-G
Can I please get a design review for this PR?

Here is the iOS build: https://i.diawi.com/bRbDnn
Here is the Android build: https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230704-094303-43fc02-pr16471-universal.apk
Designs video: https://vimeo.com/728803861

And you can also see a demo video in the description above.

File: src/quo2/foundations/colors.cljs [hunk 1]
```diff
@@ -88,6 +88,8 @@
 (def neutral-100-opa-5 (alpha neutral-100 0.05))
 (def neutral-100-opa-10 (alpha neutral-100 0.1))
 (def neutral-100-opa-30 (alpha neutral-100 0.3))
+(def neutral-100-opa-50 (alpha neutral-100 0.5))
+
```
Comment (ilmotta) [inline src/quo2/foundations/colors.cljs]: Extra line

File: src/status_im2/contexts/chat/lightbox/constants.cljs [hunk 2]
```diff
@@ -16,4 +16,11 @@
...
 
-(def ^:const image-description-in-lightbox? false)
+;;; TEXT SHEET
+(def ^:const text-min-height 68)
+
+(def ^:const text-margin 12)
+
+(def ^:const bar-container-height 20)
+
+(def ^:const line-height 22)
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/constants.cljs:15]: Just my style preference, but I think a long list of constants can be more tightly packed, like so:

```clojure
(ns status-im2.contexts.chat.lightbox.constants)

(def ^:const small-image-size 40)
(def ^:const focused-extra-size 16)
(def ^:const focused-image-size (+ small-image-size focused-extra-size))
(def ^:const small-list-height 80)
(def ^:const small-list-padding-vertical 12)
(def ^:const top-view-height 56)
(def ^:const separator-width 16)
(def ^:const drag-threshold 100)

;;; TEXT SHEET

(def ^:const text-min-height 68)
(def ^:const text-margin 12)
(def ^:const bar-container-height 20)
(def ^:const line-height 22)
```

File: src/status_im2/contexts/chat/lightbox/style.cljs [hunk 3]
```diff
@@ -77,8 +78,24 @@
...
+   {:opacity overlay-opacity}
+   {:background-color colors/neutral-100-opa-70
+    :position         :absolute
+    :top              0
+    :bottom           0
+    :z-index          @overlay-z-index
+    :left             0
+    :right            0}))
+
+;; This is needed so that text does not show in the bottom inset part as it is transparent
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/style.cljs]: I think this comment would be easier to comprehend if you moved it to where the function is used. I had to inspect the hiccup in `bottom-view` to figure out.

File: src/status_im2/contexts/chat/lightbox/style.cljs [hunk 4]
```diff
@@ -77,8 +78,24 @@
...
+
+(defn background
+  [{:keys [overlay-opacity]} {:keys [overlay-z-index]}]
+  (reanimated/apply-animations-to-style
+   {:opacity overlay-opacity}
+   {:background-color colors/neutral-100-opa-70
+    :position         :absolute
+    :top              0
+    :bottom           0
+    :z-index          @overlay-z-index
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/style.cljs]: I think it's better in general if we keep style namespaces free of state as much as we can, i.e. `deref` the argument `overlay-z-index` before passing its value to `background`.

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 5]
```diff
@@ -0,0 +1,64 @@
+(ns status-im2.contexts.chat.lightbox.text-sheet.style
+  (:require [quo2.foundations.colors :as colors]
+            [react-native.reanimated :as reanimated]
+            [status-im2.contexts.chat.lightbox.constants :as c]))
+
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs:5]: Extra line

**Comment by ilmotta** [comment]
@OmarBasem, I'm reviewing your PR now, but meanwhile I wanted to share that on the Android emulator it doesn't look right.

1. The text handle can't be moved up past the point shown on the screenshot, i.e. it doesn't go to the very top if I drag it.
2. The bottom list of image thumbnails is cut off, not like the iOS video you recorded.

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+(def bar-container
+  {:height          c/bar-container-height
+   :left            0
+   :right           0
+   :top             0
+   :z-index         1
+   :justify-content :center
+   :align-items     :center})
+
+(defn bar
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs]: This can be a `def`.

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+    :z-index  1}))
+
+(def bottom-gradient
+  {:position :absolute
+   :left     0
+   :right    0
+   :height   28
+   :bottom   0
+   :z-index  1})
+
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs]: Extra line

File: src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+                            (reset! expanded? false)
+                            (js/setTimeout #(reset! overlay-z-index 0) 300))
+                          (reanimated/set-shared-value saved-top
+                                                       (- (reanimated/get-shared-value derived-value))))
+                        (when (= (reanimated/get-shared-value derived-value) expanded-height)
+                          (reset! expanded? true))))))
+
+(defn expand-sheet
+  [{:keys [derived-value overlay-opacity saved-top]} expanded-height max-height overlay-z-index
+   expanded?]
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs]: The list of arguments doesn't look good due to the max line rule of the formatter. I would suggest adding a line break after the first argument.

```clojure
(defn expand-sheet
  [{:keys [derived-value overlay-opacity saved-top]}
   expanded-height max-height overlay-z-index expanded?]
  (reanimated/animate derived-value expanded-height)
  (reanimated/animate overlay-opacity (/ expanded-height max-height))
  (reanimated/set-shared-value saved-top (- expanded-height))
  (reset! overlay-z-index 1)
  (reset! expanded? true))
```

On the other hand, I prefer if the function signature was a single map of props because there are too many positional args. I would do the same to the function signature of `sheet-gesture`.

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+        {:content        content
+         :chat-id        chat-id
+         :style-override style/text-style
+         :on-layout      #(utils/on-layout % text-height)}]]]]))
+
+(defn view
+  [messages {:keys [overlay-opacity]} {:keys [overlay-z-index]}]
+  (let [text-height (reagent/atom 0)
+        expanded?   (reagent/atom false)]
+    [:f> text-sheet messages text-height expanded? overlay-opacity overlay-z-index]))
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: When defining state in `let` bindings, we should define a new renderer to be a proper form-2 component.

```clojure
(defn view
  []
  (let [text-height (reagent/atom 0)
        expanded?   (reagent/atom false)]
    (fn [messages {:keys [overlay-opacity]} {:keys [overlay-z-index]}]
      [:f> text-sheet messages text-height expanded? overlay-opacity overlay-z-index])))
```

**Comment by OmarBasem** [comment]
Thanks for the feedback @ilmotta. Can you please let me know if you are facing any of these issues on a physical device?

> not like the iOS video you recorded.

Btw this is on Android 😉

**Comment by ilmotta** [comment]
> Thanks for the feedback @ilmotta. Can you please let me know if you are facing any of these issues on a physical device?
> 
> > not like the iOS video you recorded.
> 
> Btw this is on Android 😉

@OmarBasem, on the real device I see the thumbnail list is correct, which is good, but I would still check why it's incorrectly displayed on the emulator because AFAIR it used to work some commits ago in `develop`.

The handle issue not scrolling to the top is worse on the real device. It seems to go up only up to 50% of the available screen, so something with the max height calculation is going on. It's on Android 13.

**Comment by OmarBasem** [comment]
@ilmotta how big is the text you are using? It expands only as big as the text

An example from the designs with a paragraph of text:

Screenshot 2023-07-04 at 16 12 30

**Comment by ilmotta** [comment]
> @ilmotta how big is the text you are using? It expands only as big as the text

Perfect then @OmarBasem, I thought the handle would always go up to max if the user wanted.

I noticed something that's more of a UX issue. If I start the drag from the first line, most of the time it starts scrolling the text, not expanding, but this is undesirable because the user doesn't want to scroll two lines of text. It happened a couple times on the real device too when I scroll with my thumb. Since it's easy to reproduce, I think it's worth investigating and hopefully fixing it.

[device-2023-07-04-091954.webm](https://github.com/status-im/status-mobile/assets/46027/88d27515-77bc-44b3-aacf-72e54747eed3)

File: src/status_im2/contexts/chat/lightbox/style.cljs (hunk 4 above)
Comment (OmarBasem) [reply src/status_im2/contexts/chat/lightbox/style.cljs]: @ilmotta There were times (other parts) when the style did not update properly (or an argument passed to a function) when I passes the state already derefed. It worked only when passing it un-refed. Do you have an idea why?

File: src/status_im2/contexts/chat/lightbox/style.cljs [hunk 10]
```diff
@@ -77,8 +78,23 @@
...
    :justify-content    :center})
 
-(def text-style
-  {:color             colors/white
-   :align-self        :center
-   :margin-horizontal 20
-   :margin-vertical   12})
+
+(defn background
+  [{:keys [overlay-opacity]} {:keys [overlay-z-index]}]
```
Comment (ajayesivan) [inline src/status_im2/contexts/chat/lightbox/style.cljs]: Wouldn't it be better to move destructuring out of the function and receive it as `[overlay-opacity overlay-z-index]`? This way, the background function doesn't have to worry about the vectors.

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+        derived                   (utils/init-derived-animations animations)]
+    [gesture/gesture-detector
+     {:gesture (utils/sheet-gesture animations expanded-height max-height overlay-z-index expanded?)}
+     [reanimated/touchable-opacity
+      {:active-opacity 1
+       :on-press #(utils/expand-sheet animations expanded-height max-height overlay-z-index expanded?)
+       :style (style/sheet-container derived)}
+      [bar text-height]
+      ;[rn/view {:style {:background-color :red
+      ;                  :position :absolute}}]
```
Comment (ajayesivan) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: Can you remove the commented code

File: src/status_im2/contexts/chat/lightbox/style.cljs (hunk 10 above)
Comment (OmarBasem) [reply src/status_im2/contexts/chat/lightbox/style.cljs]: The reason I made it this way is to make it easier to receive any other args (from `animations` or `state` maps) in case needed in the future

File: src/status_im2/contexts/chat/lightbox/style.cljs (hunk 4 above)
Comment (ilmotta) [reply src/status_im2/contexts/chat/lightbox/style.cljs]: There are differences between deref'ing reactive atoms and where we do it, if we deref inside the style function, then reagent will re-run the function if the state changes, if you deref on the parent component, then the style function will not "necessarily" be called again depending on the how the parent component uses it. I don't think this is the cause tbh. Maybe "some" reagent renderer is not defined properly. I'd need to investigate too.

**Comment by ajayesivan** [comment]
On Android, when I click and drag the top handle and stop it somewhere in the middle, the handle becomes fixed at that position. Subsequently, scrolling the text doesn't update the handle's position until I manually drag it again.

I expected the handle to scroll to the top and stay there, regardless of scrolling the text directly. The current UX feels a bit peculiar to me. Is this intended behavior?

https://github.com/status-im/status-mobile/assets/19279756/a4e232d0-b44b-44fd-a8b2-634fe1d33784

**Comment by OmarBasem** [comment]
@ajayesivan please check the latest build

**Comment by OmarBasem** [comment]
@ilmotta issue is fixed

**Comment by ajayesivan** [comment]
> On Android, when I click and drag the top handle and stop it somewhere in the middle, the handle becomes fixed at that position. Subsequently, scrolling the text doesn't update the handle's position until I manually drag it again.
> 
> I expected the handle to scroll to the top and stay there, regardless of scrolling the text directly. The current UX feels a bit peculiar to me. Is this intended behavior?
> 
>  Photo-Lightbox.mp4

I haven't encountered the above issue in the latest build, which is great. However, I'm finding it challenging to close the text. It seems like the tap area for the handler might be too small or there could be some other issue related to its interaction.


https://github.com/status-im/status-mobile/assets/19279756/05dda5d2-5918-4862-806a-b88bc07b82ed

**Comment by ilmotta** [comment]
@OmarBasem, I tested the last commit 81b0693a0, and I'm having the same issue described by @ajayesivan, the handle gesture is sometimes not triggered.

[handle.webm](https://github.com/status-im/status-mobile/assets/46027/c0e56a8c-2b86-4baf-8f70-4f05b900bd4d)

**Comment by Francesca-G** [comment]
> Hi @Francesca-G Can I please get a design review for this PR?
> 
> Here is the iOS build: https://i.diawi.com/bRbDnn Here is the Android build: https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230704-094303-43fc02-pr16471-universal.apk Designs video: https://vimeo.com/728803861
> 
> And you can also see a demo video in the description above.

Hi! Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3263%3A192125&mode=design&t=nFFT6NRiCFmf0hY5-1) with some design comments :)

I also recorded some issues I've found on Android, when having long text: the image I open gets cut out and as you can see (besides the scrollable text) once the drawer handle reaches the top of the screen I can no longer pull it down to its starting position

https://github.com/status-im/status-mobile/assets/122543089/8722e7ec-8d84-4699-a0cf-54572adb5cde

**Comment by ulisesmac** [comment]
Hello @OmarBasem 

I checked the styles for the `bar` component, it has border that I can't find on the [figma desings](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-373155&mode=design&t=MvovRJj9nqxsQnbY-4):

The border:
image

figma:
image

in `status-im2.contexts.chat.lightbox.text-sheet.view/bar`

it has:
```clojure
(def bar
  {:width            32
   :height           4
   :border-radius    100
   :background-color colors/white-opa-40
   :border-width     0.5 ;; <-
   :border-color     colors/neutral-100}) ;; <-
```

another important thing is that drawer bar is a component itself:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2500-41337&mode=design&t=UXyAVMBrxRRsNpMD-4

So I think is better to create that component in the proper namespace to avoid future code duplication.

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 12]
```diff
@@ -0,0 +1,61 @@
+(ns status-im2.contexts.chat.lightbox.text-sheet.style
+  (:require [quo2.foundations.colors :as colors]
+            [react-native.reanimated :as reanimated]
+            [status-im2.contexts.chat.lightbox.constants :as c]))
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs]: I think we prefer longer and more descriptive names, so I'd suggest to  change `c` by `constants`

File: src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+   :justify-content :center
+   :align-items     :center})
+
+(def bar
+  {:width            32
+   :height           4
+   :border-radius    100
+   :background-color colors/white-opa-40
+   :border-width     0.5
+   :border-color     colors/neutral-100})
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/text_sheet/style.cljs:36]: I added a separate comment about this `bar` and its styles :eyes:

File: src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs [hunk 14]
```diff
@@ -0,0 +1,66 @@
...
+  (reanimated/animate overlay-opacity (/ expanded-height max-height))
+  (reanimated/set-shared-value saved-top (- expanded-height))
+  (reset! overlay-z-index 1)
+  (reset! expanded? true))
+
+(defn on-scroll
+  [e expanded? {:keys [gradient-opacity]}]
+  (if (and (> (oops/oget e "nativeEvent.contentOffset.y") 0) @expanded?)
+    (reanimated/animate gradient-opacity 1)
+    (reanimated/animate gradient-opacity 0)))
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/text_sheet/utils.cljs]: Same as before @ilmotta mentioned, you could try to `deref` the atom before calling this function, I think this should exactly the same:

```clojure
;; Instead of calling like this:
(utils/on-scroll e expanded? {,,,})

;; call it like this:
(utils/on-scroll e @expanded? {,,,})
```

doing this, we don't propagate the complexity of knowing `expanded?` is an atom and not just a boolean

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs [hunk 15]
```diff
@@ -0,0 +1,68 @@
...
+    [status-im2.contexts.chat.lightbox.constants :as c]
+    [status-im2.contexts.chat.lightbox.text-sheet.style :as style]
+    [status-im2.contexts.chat.lightbox.text-sheet.utils :as utils]
+    [status-im2.contexts.chat.messages.content.text.view :as message-view]))
+
+(defn bar
+  [text-height]
+  (when (> @text-height (* c/line-height 2))
+    [rn/view {:style style/bar-container}
+     [rn/view {:style style/bar}]]))
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: Please try to deref this `text-height` atom before and not inside this function, I know this (currently) is an internal component, but there's no need to pass an atom here, IMO, most of the time, if we avoid passing atoms to subcomponents the code is simpler.

Think about treating `bar` as a separate component, if we want to reuse it, we can't use it as:

```clojure
[bar 200]
```

it will crash with an exception about IDeref protocol, so we must call it as follows:

```clojure
[bar (atom 200)]
```

But there's no need of doing that for this component.

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs [hunk 16]
```diff
@@ -0,0 +1,68 @@
...
+
+(defn text-sheet
+  [messages text-height expanded? overlay-opacity overlay-z-index]
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: Please receive and pass these properties in a single map, maps are more open and flexible and also we want to be consistent with other components and usually in React the properties are passed in a single object as first param

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs [hunk 17]
```diff
@@ -0,0 +1,68 @@
...
+         :chat-id        chat-id
+         :style-override style/text-style
+         :on-layout      #(utils/on-layout % text-height)}]]]]))
+
+(defn view
+  []
+  (let [text-height (reagent/atom 0)
+        expanded?   (reagent/atom false)]
+    (fn [messages {:keys [overlay-opacity]} {:keys [overlay-z-index]}]
+      [:f> text-sheet messages text-height expanded? overlay-opacity overlay-z-index])))
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: I think this component could receive a single map containing 3 keys:
`:messages`, `:animations` and `:state`.
 instead of receiving three maps. Keep in mind that the standard for react components is to pass properties as first param and children as the followingm I'm not super strict about this, but in this case I think we don't need to pass 3 different maps.
 
 wdyt?

Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: Our `view` component is creating and just passing atoms, IMO we are mixing responsibilites of each component., again IMO,

- `view` its purpose is just being a wrapper to expose an API without the necessity of using `:f>` when calling,
- `text-sheet` its purpose is create the component itself.

but it seems we are splitting the main component in two, view is creating a local state and just passing it, that's not required.

we have the following:
```clojure
(defn text-sheet [map-1 map-2 map-3 atom-1 atom-2]
  (let [#_bindings]
    ;; the component
    ))

(defn view
  []
  (let [atom-1 (reagent/atom 0)
        atom-2 (reagent/atom false)]
    (fn [map-1 map-2 map-3]
      [:f> text-sheet map-1 map-2 map-3 atom-1 atom-2])))
```

but I'd prefer to move it to the following structure:

```clojure
(defn text-sheet [_]
  (let [atom-1 (reagent/atom 0)
        atom-2 (reagent/atom false)])
  (fn [props] ;; with the proper destructuring
    (let [#_bindings])
    ;; the component
    ))

(defn view [props]
  [:f> text-sheet props])
```

The benefits I see are:
 - It's clear that `view` is just a wrapper, and just use it like that
 - If we remove the use of `:f>` later, the refactor will be easier
 - The atoms are created and used only in the function that needs them
 - We are receiving a single properties map, as most of the components we create
 
 What do you think? @OmarBasem

File: src/status_im2/contexts/chat/lightbox/top_view.cljs [hunk 18]
```diff
@@ -43,9 +43,10 @@
         (anim/animate top-view-bg colors/neutral-100-opa-0)))))
 
 (defn drawer
-  [content]
-  (let [uri (http/replace-port (:image content)
-                               (rf/sub [:mediaserver/port]))]
+  [messages index]
+  (let [{:keys [content]} (nth messages @index)
+        uri               (http/replace-port (:image content)
+                                             (rf/sub [:mediaserver/port]))]
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/top_view.cljs]: Do we know what's the type of `messages`? if it's a vector, we could use `get`. The problem with `nth` is it throws an exception unless `not-found` is passed.

For this component I can see we are not using that `index` atom for swapping/resetting its value, so it's better not to pass that atom, just derefing the value before calling this `drawer` component, i.e.
`[drawer messages index]` -> `[drawer messages @index]`


same for `share-image` below

File: src/status_im2/contexts/chat/lightbox/view.cljs [hunk 19]
```diff
@@ -102,17 +104,18 @@
...
-  [{:keys [messages index]}]
-  (let [props (utils/init-props)
-        state (utils/init-state messages index)]
-    (fn [{:keys [messages index]}]
+  []
+  (let [{:keys [messages index]} (rf/sub [:get-screen-params])
+        props                    (utils/init-props)
+        state                    (utils/init-state messages index)
+        callback                 (fn [e]
+                                   (on-viewable-items-changed e props state))]
```
Comment (ulisesmac) [inline src/status_im2/contexts/chat/lightbox/view.cljs]: What does this function do?
naming something as `callback` is almost the same as calling it `function`, so it'd be good to rename it with what it does in terms of components/view. e.g. navigate-to-somewhere or scroll-to-somewhere

**Review by ulisesmac — COMMENTED** [review]
Hello @OmarBasem 
thanks for the PR! :+1: 
I added some comments mainly related to code structure.


I noticed you updated the issue #16471 with:
> There should be padding/margin on the side of photos - Edit (Omar): currently having padding on the side causes problems with Shared element transition animation on iOS. I will wait for it until we upgrade RNN and reanimated versions (dependent on RN 0.71+)

Could you please elaborate on the problems you had and what are we expecting to be solved when we upgrade reanimated?

It'd be good to open a separate issue with enough detail about it.

File: src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs (hunk 17 above)
Comment (OmarBasem) [reply src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: Well, I have no strong opinion about this. For nonreusable components that will be used only once I prefer multiple args over a map, as passing it as a map can make it less clean IMO. When using a map it would become `[text-sheet/view {:messages messages :animations animations :state state}]` instead of just `[text-sheet/view messages animations state]`, and then ofc it would have to be destructured twice, for example, destructuring to get the animations map, then another destructure to get the key inside of it.

Comment (OmarBasem) [reply src/status_im2/contexts/chat/lightbox/text_sheet/view.cljs]: I agree @ulisesmac. Thanks for the detailed explanation

File: src/status_im2/contexts/chat/lightbox/top_view.cljs (hunk 18 above)
Comment (OmarBasem) [reply src/status_im2/contexts/chat/lightbox/top_view.cljs]: `messages` is a `List`

**Comment by OmarBasem** [comment]
Thanks for your review @Francesca-G !

I have replied to your comments on Figma and fixed the issues. As for that issue in the video (image incorrect dimensions) I have opened a separate issue https://github.com/status-im/status-mobile/issues/16490 for that to investigate it.

**Comment by OmarBasem** [comment]
@ajayesivan @ilmotta I have increased the handlebar touch area a little. Please check it and let me know how is it now.

**Comment by OmarBasem** [comment]
> I checked the styles for the bar component, it has border that I can't find on the [figma desings](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-373155&mode=design&t=MvovRJj9nqxsQnbY-4):

@ulisesmac if there is a white image the handle bar will be invisible. @Francesca-G can you please confirm if any style changes needs to be done for the handle bar in order to not be invisible over white images?

**Comment by OmarBasem** [comment]
> noticed you updated the issue https://github.com/status-im/status-mobile/pull/16471 with:

@ulisesmac having these margins on iOS causes the shared element transition to not execute properly. It seems to ignore any given margins, so the image gets cut out while animating. Upgrading RNN may fix the problem. Also, Reanimated v3 has a new shared element transition feature, which may work better than that one of RNN. I will open an issue for that.

**Comment by ilmotta** [comment]
> @ajayesivan @ilmotta I have increased the handlebar touch area a little. Please check it and let me know how is it now.

Much better now. Thanks @OmarBasem

**Review by ilmotta — APPROVED** [review]

**Comment by ulisesmac** [comment]
> > noticed you updated the issue https://github.com/status-im/status-mobile/pull/16471 with:
> 
> @ulisesmac having these margins on iOS causes the shared element transition to not execute properly. It seems to ignore any given margins, so the image gets cut out while animating. Upgrading RNN may fix the problem. Also, Reanimated v3 has a new shared element transition feature, which may work better than that one of RNN. I will open an issue for that.

@OmarBasem 
As I told you before, I have tried solving this, and I didn't find a problem with margins, I shrinked the image container when the image was shown, and on user tap, I expanded the image container (to become full screen).

Is this the same approach you tried?

My main problem was that the code was complex, and I couldn't get a clean solution.

**Comment by OmarBasem** [comment]
@ulisesmac can you show me a branch please (I also had a solution that wasn't very clean)

Anyways it's not part of this PR. Opened an issue https://github.com/status-im/status-mobile/issues/16503

I have a solution that may work. I will try to make a PR now and see how it goes

Edit: found a clean solution and fixed it. Will make PR after this one is merged. 👍

**Comment by ajayesivan** [comment]
@OmarBasem Sometimes the background gradient is not disappearing when closing the drawer. Not sure how to reproduce this issue, it happens randomly. Please check the video
https://github.com/status-im/status-mobile/assets/19279756/a89d6bfb-60c8-430e-93ed-3b92f2cfebd4

**Comment by OmarBasem** [comment]
Thanks @ajayesivan, fixed it!

**Review by ajayesivan — APPROVED** [review]
LGTM! Nice work 🎉

**Comment by pavloburykh** [comment]
@OmarBasem thanx for the PR. Please take a look at following issue. 

### ISSUE 1 Lagging Scroll Behavior on iOS after Expanding of the lightbox text sheet

Reproducing on iPhone X, IOS 14.1

**Steps:** 

1. Send an image with long text
2. Open lightbox
3. Expand text sheet and try to scroll

**Actual result:** 
it is hard see on video but actual behaviour is following:

When expanding the text sheet and attempting to scroll, the scrolling functionality is severely limited. It only allows for scrolling 1-2 lines per gesture, making it difficult to navigate through the text efficiently.

However, after some time, the scroll behavior suddenly starts working as expected without any lag, enabling smooth scrolling to the very bottom of the text.

Upon collapsing and subsequent re-expansion of the text sheet, the scrolling functionality starts lagging again, restricting the smooth and responsive scrolling experience.


https://github.com/status-im/status-mobile/assets/97245802/6b30c941-1e43-4d31-9ea2-566dcfb2c31a

**Comment by pavloburykh** [comment]
> ISSUE 1 Lagging Scroll Behavior in iOS after Expanding of lightbox text sheet

@OmarBasem here is one more video related to this. 

Here you can see incorrect scroll behaviour on IOS. Also there is another problem: sometimes scrolling results in collapsing of text sheet. 


https://github.com/status-im/status-mobile/assets/97245802/b49a8d44-1928-4c5b-ad84-3cbea144021d

**Comment by OmarBasem** [comment]
Thanks for your testing @pavloburykh 

How big is this text in the video?

If you use big text that is slightly bigger than the screen length does it lag the same?

**Comment by pavloburykh** [comment]
> Thanks for your testing @pavloburykh
> 
> How big is this text in the video?
> 
> If you use big text that is slightly bigger than the screen length does it lag the same?

Here is a new video with text which is slightly bigger than the screen size (1827 chars) and it is still laggy

https://github.com/status-im/status-mobile/assets/97245802/e45fb1d5-387a-4ed6-a0c4-51ec14bcbf7a

**Comment by pavloburykh** [comment]
@OmarBasem @Francesca-G I have another question: 

Currently user is able to start scrolling text only when text sheet is fully expanded. Unless it is fully expanded - scrolling gesture will result in resizing of the text sheet, despite user is not touching handler area. Is it a correct behaviour?


https://github.com/status-im/status-mobile/assets/97245802/d19726f2-78a0-466d-ae81-902a04f39720

**Comment by pavloburykh** [comment]
### ISSUE 2 Fading of long text is missing within text sheet

**Expected result:** 

https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-373181&mode=design&t=aXS4RfjELHOmhqMz-0

Composer for Mobile – Figma 2023-07-06 16-47-37

**Actual result:** 


https://github.com/status-im/status-mobile/assets/97245802/a580b40e-7045-4026-a31c-1d348a6fb748

**Comment by ulisesmac** [comment]
> @ulisesmac can you show me a branch please (I also had a solution that wasn't very clean)
> 
> Anyways it's not part of this PR. Opened an issue https://github.com/status-im/status-mobile/issues/16503
> 
> I have a solution that may work. I will try to make a PR now and see how it goes
> 
> Edit: found a clean solution and fixed it. Will make PR after this one is merged. 👍 

Awesome @OmarBasem  👏👏 😁

**Comment by OmarBasem** [comment]
Hi @pavloburykh,

I am still not able to reproduce issue 1. Have you tried on different devices?

Regarding issue 2, the fading gradient is there but in the video you are showing the image is a little short, so the area behind that fade part is already dark, so it is hard to see. It will be more visible if you use a longer image as in the video below

https://github.com/status-im/status-mobile/assets/29354102/3ee0f77b-4fb3-4703-bcff-cce79f3e6b4c


> Currently user is able to start scrolling text only when text sheet is fully expanded. Unless it is fully expanded - scrolling gesture will result in resizing of the text sheet, despite user is not touching handler area. Is it a correct behaviour?

That's the behaviour shown in the video https://vimeo.com/728803861

**Comment by pavloburykh** [comment]
> Hi @pavloburykh,
> 
> I am still not able to reproduce issue 1. Have you tried on different devices?

@churik hi! Could you please check on your device? Thank you!

**Comment by pavloburykh** [comment]
> > Currently user is able to start scrolling text only when text sheet is fully expanded. Unless it is fully expanded - scrolling gesture will result in resizing of the text sheet, despite user is not touching handler area. Is it a correct behaviour?
> 
> That's the behaviour shown in the video https://vimeo.com/728803861

Thanx @OmarBasem ! On given video I do not observe the example of behaviour when user tries to scroll not fully expanded text sheet. It shows only fully expanded option. @Francesca-G could you please confirm that the [described](https://github.com/status-im/status-mobile/pull/16471#issuecomment-1623701105) behaviour is correct? thank you!

**Comment by churik** [comment]
@pavloburykh @OmarBasem can't reproduce ISSUE 1 it on IPhone 14 Pro, IOS 16.5.

**Comment by pavloburykh** [comment]
@OmarBasem since [ISSUE 1 ](https://github.com/status-im/status-mobile/pull/16471#issuecomment-1623564814) is reproducible only on my iPhone X, IOS 14.1 we can ignore it for now. 

I would like to wait for @Francesca-G approve on [this](https://github.com/status-im/status-mobile/pull/16471#issuecomment-1623701105) question. After that PR will be ready for merge.

**Comment by Francesca-G** [comment]
> @OmarBasem @Francesca-G I have another question:
> 
> Currently user is able to start scrolling text only when text sheet is fully expanded. Unless it is fully expanded - scrolling gesture will result in resizing of the text sheet, despite user is not touching handler area. Is it a correct behaviour?
> 
>  telegram-cloud-document-2-5273821833458626144.mp4

@pavloburykh Yes, that's the correct behavior :)

**Comment by pavloburykh** [comment]
@OmarBasem @Francesca-G thank you! PR is ready for merge.
