### PR TITLE
[#17572] fix: 'Join Community' notification is not getting dismissed

### LINKED ISSUE #17572: 'Join Community' notification is not getting dismissed
After joining a community, the 'Join Community' notification remains persistent in the notification center, even after accessing the community. Additionally, tapping on the notification has no effect.

Reported in Design Feedback - [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:77614&mode=design#567160171).

### Steps to Reproduce:
- Join a new community.
- Open the notification center.
- Tap on the 'Join Community' notification.
- Open the community.

**Expected behavior**
The same thing should happen as with notifications for replies/mentions:

- when pressed, you should be redirected to the community;
- after which the notification should become read;
- if you go to the community after joining without going to the activity center, then the notification should also become read.

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17572

### Summary

After joining a community, the 'Join Community' notification remains persistent in the notification center, even after accessing the community. Additionally, tapping on the notification has no effect.

### Steps to test

1. Join a new community.
2. Open the notification center.
3. Tap on the 'Join Community' notification.
4. Open the community.

### Before and after screenshots comparison

- When  user navigate to community

https://github.com/status-im/status-mobile/assets/71308738/2e3f2639-e9ee-43cf-ac58-8eef9510f66b

- When  user click on joined community notification

https://github.com/status-im/status-mobile/assets/71308738/76d71073-431e-441a-b5e5-074ea80726fd

- When  user click on kicked from community notification
https://github.com/status-im/status-mobile/assets/71308738/cd2932fa-521c-457a-9af9-e811db362741

status: ready

### CODE REVIEW

File: src/status_im2/contexts/shell/activity_center/events.cljs [hunk 1]
```diff
@@ -202,6 +202,14 @@
      :utils/dispatch-later [{:dispatch [:activity-center.notifications/mark-all-as-read]
                              :ms       undo-time-limit-ms}]}))
 
+(defn mark-read-community-overview
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/events.cljs]: @mohsen-ghafouri, the only reason we need to define public functions for the event handlers is when we want to unit test them (to make them accessible from the test namespace) or when they need to be called with the deprecated pattern `rf/merge`. In this namespace we see a lot of public functions defined for events because they have unit tests.

Therefore, here it's more idiomatic re-frame if you inline the handler in the call to `reg-event-fx`.

File: src/status_im2/contexts/shell/activity_center/events.cljs [hunk 2]
```diff
@@ -202,6 +202,14 @@
...
+  [_ community-id]
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/events.cljs]: This argument `community-id` is not quite right. Re-frame events in `status-mobile` expect the second argument to be a vector, and then we need to always destructure. I know this is confusing, with `rf/defn` it was exactly as you coded, but with `reg-event-fx` it's normal re-frame, like in the official docs.

It should be:

```clojure
(re-frame/reg-event-fx :activity-center/mark-read-community-overview
 (fn [_ [community-id]]
   ...))
```

In the current implementation, if you try to print the `community-id` arg, and assuming it's value is `"foo"`, it will be printed as `["foo"]`, because it's not vector-destructured. The code is working now because you passed `community-id` directly to `:params`, but this is a trick ;)

File: src/status_im2/contexts/shell/activity_center/events.cljs [hunk 3]
```diff
@@ -202,6 +202,14 @@
...
+  {:json-rpc/call [{:method     "wakuext_markCommunityNotificationRead"
+                    :params     community-id
+                    :on-success [:activity-center.notifications/fetch-unread-count]}]})
+
+(re-frame/reg-event-fx :chat.ui/mark-read-community-overview mark-read-community-overview)
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/events.cljs]: The keyword qualification `:chat.ui` is not what this namespace uses (this is from old code I think), so should be `:activity-center/*` or `:activity-center.notifications/*`

File: src/status_im2/navigation/events.cljs [hunk 4]
```diff
@@ -21,7 +22,9 @@
   (rf/merge
    cofx
    {:db         (all-screens-params db go-to-view-id screen-params)
-    :dispatch-n [[:hide-bottom-sheet]]}
+    :dispatch-n [[:hide-bottom-sheet]
+                 (when (= go-to-view-id shell.constants/community-screen)
```
Comment (ilmotta) [inline src/status_im2/navigation/events.cljs]: I see this `navigate-to` event as a general utility, so we shouldn't couple it with specific screens.

We can probably dispatch this event when the community overview screen is loaded, more or less here https://github.com/status-im/status-mobile/blob/aa6d44bee18c92a39c6e6da8b2199cb6dadd5647/src/status_im2/contexts/communities/overview/view.cljs#L359

You will need to convert the component to a Reagent form-2 component. It's a common technique we use to do something effectful when some component is mounted.

```clojure
(defn overview
  []
  (rf/dispatch :mark-as-read)
  (fn [id]
    ...))
```

**Comment by mohsen-ghafouri** [comment]
@ilmotta Thank you for all the informative feedbacks; it has been incredibly helpful. could you please check again.

**Review by alwx — APPROVED** [review]
Great work!

**Review by ilmotta — APPROVED** [review]
Code looks nice @mohsen-ghafouri!

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanx for the PR. Please take a look at the issue

### ISSUE 1 AC notification should not appear is request has been accepted while user is still on the same community screen

Steps: 

1. User A (admin) invites User B to community
2. User B sends community request and remains on community home screen
3. User A accepts the request (manually or automatically depending on community type)
4. Wait until community status is changed to joined for User B and joined toast appears
5. Check if there is joined notification for User B in AC

**Actual result:** notification remains unread in AC


https://github.com/status-im/status-mobile/assets/97245802/52b057fa-6556-41d9-9b37-d7522c3edf75


**Expected result:** notification should be read

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1386-110589&mode=design&t=ADd4EY6Unj7Ny4cU-0)

Communities for Mobile – Figma 2023-11-10 18-09-37

**Comment by mohsen-ghafouri** [comment]
thanks @pavloburykh.  resolved,  could you please check again ?

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you for the fix. No issues from my side. 

Before merge I would like to ask you to rebase both go and mobile branches because status go is quite outdated. After that I will re-run e2e to make sure go develop will not introduce any unexpected issues.

**Comment by mohsen-ghafouri** [comment]
@pavloburykh done

**Comment by pavloburykh** [comment]
@mohsen-ghafouri unfortunately after rebasing go branch we are facing 2 blocking issues:

### ISSUE 1 Contact requests are not delivered

### ISSUE 2 Endless manual logout

Below is video and logs for both issues

[CR_receiver_Anndroid.zip](https://github.com/status-im/status-mobile/files/13340946/CR_receiver_Anndroid.zip)
[CR_sender_IOS.zip](https://github.com/status-im/status-mobile/files/13340947/CR_sender_IOS.zip)


https://github.com/status-im/status-mobile/assets/97245802/0ae9a52a-9b7b-4f8e-afe5-d97f2ab5e382

@mohsen-ghafouri please confirm that those issues are not related to PR changes or some problems during rebasing.

**Comment by pavloburykh** [comment]
@mohsen-ghafouri facing the same issues in another PR containing go changes https://github.com/status-im/status-mobile/pull/17892 So the issue is definitely the broken go branch

**Comment by mohsen-ghafouri** [comment]
@pavloburykh yeah i was checking and i couldn't find anything in my code related to login part and i thought so . okay shall i wait for a fix?

**Comment by pavloburykh** [comment]
> okay shall i wait for a fix?

Yes. You can follow the discussion in here https://discord.com/channels/1103692771585433630/1103692773363810317/1173923198748868688 @mohsen-ghafouri

**Comment by mohsen-ghafouri** [comment]
@pavloburykh could you please recheck

**Comment by pavloburykh** [comment]
> @pavloburykh could you please recheck

it turned out that release go branch already contains those 2 blockers. So we will wait until they are fixed.

**Comment by pavloburykh** [comment]
hey @mohsen-ghafouri! We decided to exclude this PR from release. It means that it will be remained blocked until https://github.com/status-im/status-mobile/issues/17899 and https://github.com/status-im/status-mobile/issues/17898 are fixed in go develop. After that we will get back to this PR and merge it into develop. Thank you and sorry for confusion.

**Comment by pavloburykh** [comment]
Hey @mohsen-ghafouri! Time to come back to this PR)) Could you please base it again against develop branch (both go and mobile)? Cause currently it is based on release branches. After that I will re-run e2e and hopefully we will be able to merge it.

**Comment by mohsen-ghafouri** [comment]
Hey @pavloburykh it's ready

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you! PR is ready for merge.
