### PR TITLE
fix Jump to button not responding in chat after app returns from background

### LINKED ISSUE #17079: [Android] "Jump to" button not responding in chat after app returns from background
introduced by https://github.com/status-im/status-mobile/pull/16981

### Steps:
1. Open any chat.
2. Send the app into the background. (background should be active for at least 1 minute)
3. Return the app from the background.
4. Tap the 'Jump to' button.

### Actual Result:
The "Jump to" button does not redirect to the intended screen after being tapped.

https://github.com/status-im/status-mobile/assets/52490791/27594b75-b3e7-476c-b886-5a822b9536a2

### Expected Result:
The "Jump to" button should correctly redirect to the "Jump to" screen after being tapped

### Devices:
- Real device: Pixel 7a, Android 13
- Android Emulator: Pixel 6 Pro API 31

### logs:

[Status.log](https://github.com/status-im/status-mobile/files/12406772/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12406773/geth.log)

CC: @Parveshdhull

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/17079

### Summary
I think the problem was that we had two floating shell buttons (one for jump-to and one for scroll-to-bottom), and the scroll-to-bottom one always overlapped the jump-to one. And for some reason, it sometimes stopped propagating touch events.

status: ready

### CODE REVIEW

**Comment by VolodLytvynenko** [comment]
HI @Parveshdhull thank you for PR. The issue is still reproducible and still randomly without exact steps

https://github.com/status-im/status-mobile/assets/52490791/acdb91d4-7f62-4678-9463-abc9bcd8b3af

### Devices:
- Android studio: Pixel 6 Pro API 31
- Real device: Pixel 7a, Android 13

### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/12417474/android_logcat.txt)

File: src/status_im2/contexts/chat/composer/sub_view.cljs [hunk 1]
```diff
@@ -48,10 +48,12 @@
...
          :style               {:align-self :center}}}
        {}]]
-     [quo/floating-shell-button
-      (when @messages.list/show-floating-scroll-down-button
-        {:scroll-to-bottom {:on-press messages.list/scroll-to-bottom}})
-      {}]]))
+     (when @messages.list/show-floating-scroll-down-button
+       [quo/floating-shell-button
+        {:scroll-to-bottom {:on-press messages.list/scroll-to-bottom}}
+        {:position :absolute
```
Comment (siddarthkay) [inline src/status_im2/contexts/chat/composer/sub_view.cljs]: tiny nit pick : styles could be moved over to `status-im2.contexts.chat.composer.style`

**Review by siddarthkay — APPROVED** [review]
nice

File: src/status_im2/contexts/chat/composer/sub_view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im2/contexts/chat/composer/sub_view.cljs]: done, thank you

**Review by OmarBasem — APPROVED** [review]

**Comment by qoqobolo** [comment]
@Parveshdhull thank you for this fix, great job!
I am not able to reproduce the issue manually anymore, e2e also look good (thanks @pavloburykh and @yevh-berdnyk for helping me figure out the results). 
Let's merge it!
