### PR TITLE
Show "Added to group chat" notifications

### LINKED ISSUE #14744: No unread indicator on activity center for mentions and replies
# Bug Report

## Problem 
The unread indicator does not appear on the activity center bell if the user was mentioned or received a reply in a chat.

#### Expected behavior
For mentions and replies: unread indicator on the activity center (blue dot)

#### Actual behavior

No unread indicator

https://user-images.githubusercontent.com/67952253/211585627-ae9c4359-88f2-4eb2-a498-b564290d99ce.mp4

### Reproduction

1. UserA and UserB join a community
2. UserA opens the home screen
3. UserB mentions UserA in the community
4. UserA checks the activity center bell

### Additional Information

- Status version: nightly 10/01/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ilmotta**
Partially implements https://github.com/status-im/status-mobile/issues/14712
Fixes #14744

### Summary

This PR implements the first, among what will probably be many different kinds of membership notifications. For this PR, I started with implementing a particular flow for private group chats because it's already supported by `status-go` (albeit I had to make some changes, see [PR in status-go](https://github.com/status-im/status-go/pull/3088).

1. `A` and `B` are mutual contacts.
2. `A` creates a private group chat with `B` as member.
3. `B` sees the group chat in the app, but doesn't interact with it.
4. `B` reinstalls the app (remember to back up the seed phrase).
5. `A` mentions `B` in the group chat.
6. `B` should see a group chat notification, which can be accepted/declined.

- [x] Also fixes #14744 @qoqobolo 

### Demo

In the video I'm simulating the steps outlined in the *Summary*, but using the approach described in *Steps to test*, because it's way easier to iterate during development.

[demo.webm](https://user-images.githubusercontent.com/46027/212470798-c135d229-948d-4ba5-98db-ee73cc5495cd.webm)

### Review Notes

Some changes had to be made in `status-go` ([PR](https://github.com/status-im/status-go/pull/3088)), namely:

- According to [Figma](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=3806%3A586901&t=xLTAjLXjG1UtorpI-0), users should be able to see `accepted` group chat notifications. Until now, `status-go` hardcoded that `accepted` notifications would *not* be returned in query results, and so it would be impossible to show them to users. This was changed and now the RPC endpoint accepts an additional filter. The implementation on the backend is backwards compatible so as to not break Status desktop.
- The `Membership` tab needs to display various types of notifications (group chat, community, etc), but the membership type doesn't exist on the backend. To overcome this constraint, this PR makes the membership type a logical/virtual type, i.e. a Clojure set of types. `status-go` was changed to support querying for multiple notification types (also backwards compatible).

#### Platforms

- Android
- iOS

### Steps to test

Please, follow the steps described in the Summary and you should be able to test.

But during development, I followed these steps (recommended by @cammellos). I documented them here for reference.

1. Checkout `feature/e2e` in status-go. Apply the diff below.
2. `cd cmd/e2e && ./e2e`
3. This will create a temporary account automatically, let's call it `A`.
4. On another device, create account `B`.
5. Follow the steps documented in https://github.com/status-im/status-go/blob/bdc406ea2e6eb990ce5c0fed7ea2e84b63c92139/cmd/e2e/README.md#L2 in order for user `A` to create a group chat with `B` as member. Don't make `A` and `B` mutual contacts.
6. On `B`'s device, a notification should appear, and `B` should be able to accept or decline the "invitation" (actually *invitation* is another concept and related to another feature).

```diff
modified   cmd/e2e/main.go
@@ -283,6 +283,11 @@ func defaultNodeConfig(installationID string) (*params.NodeConfig, error) {
    nodeConfig.NetworkID = 1
    nodeConfig.LogLevel = "ERROR"
    nodeConfig.DataDir = "/ethereum/mainnet_rpc"
+        nodeConfig.HTTPEnabled = true
+        nodeConfig.HTTPPort = 8545
+        nodeConfig.HTTPHost = "localhost"
+        nodeConfig.HTTPVirtualHosts = []string{"localhost"}
+
         nodeConfig.APIModules = "wakuext,ext,waku"

    nodeConfig.UpstreamConfig = params.UpstreamRPCConfig{
modified   protocol/messenger_group_chat.go
@@ -26,17 +26,17 @@ func (m *Messenger) validateAddedGroupMembers(members []string) error {
        }

        contact, _ := m.allContacts.Load(contactID)
-		if contact == nil || !(contact.Added && contact.HasAddedUs) {
-			return ErrGroupChatAddedContacts
-		}
+                if contact == nil {
+                  contact, err = buildContactFromPkString(contactID)
+                  if err != nil {
+                    return err
+                  }
+                }
    }
    return nil
 }

 func (m *Messenger) CreateGroupChatWithMembers(ctx context.Context, name string, members []string) (*MessengerResponse, error) {
-	if err := m.validateAddedGroupMembers(members); err != nil {
-		return nil, err
-	}

    var response MessengerResponse
    logger := m.logger.With(zap.String("site", "CreateGroupChatWithMembers"))
```

status: ready

### CODE REVIEW

File: src/status_im/chat/models/loading.cljs [hunk 1]
```diff
@@ -69,15 +68,15 @@
 
 (rf/defn handle-mark-all-read-successful
   {:events [::mark-all-read-successful]}
-  [cofx]
-  (activity-center/notifications-fetch-unread-count cofx))
+  [_]
+  {:dispatch [:activity-center.notifications/fetch-unread-count]})
```
Comment (ilmotta) [inline src/status_im/chat/models/loading.cljs:72]: FYI: I had to switch to `:dispatch` because the compiler failed due to a circular dependency.

File: status-go-version.json [hunk 2]
```diff
@@ -3,7 +3,7 @@
     "_comment": "Instead use: scripts/update-status-go.sh <rev>",
     "owner": "status-im",
     "repo": "status-go",
-    "version": "v0.122.1",
-    "commit-sha1": "d60c1d00ed93d4340ab06a32ce062dd7e67e67c0",
-    "src-sha256": "1452a1n5fijcpq56mxaaacjx4091mpxkq62qi1b2xiy91ll6ik5f"
+    "version": "cd32a6422598c22749beef56a4bff9dd9025ee03",
```
Comment (ilmotta) [inline status-go-version.json]: FYI: This is going to be changed once the PR is approved. See related status-go PR https://github.com/status-im/status-go/pull/3088

**Comment by ilmotta** [comment]
Reviewers @alwx, @rasom, @vkjr, @flexsurfer, @smohamedjavid, @J-Son89.

Please, let me know if this PR looks good. I guess it got lost in limbo ;) Thank you!

File: src/status_im/chat/models/loading.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/chat/models/loading.cljs:72]: why not dispatch `fetch-unread-count` directly?

File: src/status_im/chat/models/loading.cljs [hunk 3]
```diff
@@ -69,15 +68,15 @@
...
 
 (rf/defn handle-mark-all-read-in-community-successful
   {:events [::mark-all-read-in-community-successful]}
   [{:keys [db] :as cofx} chat-ids]
   (rf/merge cofx
-            {:db (reduce mark-chat-all-read db chat-ids)}
-            (activity-center/notifications-fetch-unread-count)))
+            {:db       (reduce mark-chat-all-read db chat-ids)
+             :dispatch [:activity-center.notifications/fetch-unread-count]}))
```
Comment (flexsurfer) [inline src/status_im/chat/models/loading.cljs:79]: yeah i see, here as well, do you know why we have a circular dependency, is it temporary while we're in moving process, is it possible to resolve now ?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/chat/models/loading.cljs (hunk 3 above)
Comment (ilmotta) [reply src/status_im/chat/models/loading.cljs:79]: @flexsurfer, this is unfortunately a known downside of treating event handlers as functions as we do. It's very common to have events that need to dispatch to other events, and circular dependencies can easily happen. I had similar issues in past projects.

Similarly, when codebases use namespaced keywords, circular dependencies are also common, and that's one big reason why Clojure 1.11 supports the new `:as-alias` option, which only resolves keywords `::` for expansion, but doesn't actually load the namespace.

Comment (flexsurfer) [reply src/status_im/chat/models/loading.cljs:79]: yeah that's interesting, somehow we didn't have much  circular dependencies in the project before, i remember only a few cases in that case we have to move event to separate namespace

Comment (ilmotta) [reply src/status_im/chat/models/loading.cljs:79]: > yeah that's interesting, somehow we didn't have much circular dependencies in the project before, i remember only a few cases in that case we have to move event to separate namespace

That's correct, most of the time we can rearrange the namespaces to accommodate for circular dependencies. It works well for the most part.

**Review by smohamedjavid — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ilmotta thank you for the PR. Could you please take a look at recent IOS and Android e2e builds https://github.com/status-im/status-mobile/pull/14785#issuecomment-1382735714 They have not been build after your recent commits. I have tried re-built them manually but they failed.

File: src/status_im2/contexts/activity_center/notification/membership/view.cljs [hunk 4]
```diff
@@ -0,0 +1,41 @@
+(ns status-im2.contexts.activity-center.notification.membership.view
+  (:require [i18n.i18n :as i18n]
```
Comment (flexsurfer) [inline src/status_im2/contexts/activity_center/notification/membership/view.cljs]: [utils.i18n :as i18n]

Comment (ilmotta) [reply src/status_im2/contexts/activity_center/notification/membership/view.cljs]: Oh no, this one went through the cracks! Let me check if there are other bad usages in the activity center and fix them.

Comment (ilmotta) [reply src/status_im2/contexts/activity_center/notification/membership/view.cljs]: Fixed already, thanks

**Comment by ilmotta** [comment]
> @ilmotta thank you for the PR. Could you please take a look at recent IOS and Android e2e builds [#14785 (comment)](https://github.com/status-im/status-mobile/pull/14785#issuecomment-1382735714) They have not been build after your recent commits. I have tried re-built them manually but they failed.

@pavloburykh, builds should be green now. They were just flaky I guess, because I just rebased and pushed again.

**Comment by pavloburykh** [comment]
@ilmotta thanx for the PR. Additional respect for detailed Summary, that is really helpful and makes our work much more easier and productive! 

I am currently in the middle of testing the PR and got some questions, would appreciate your comment on that :

### Question 1
According to [Steps](https://github.com/status-im/status-mobile/pull/14785#issue-1533248031) provided in Summary, group chat notification should appear for recovered user when he is mentioned in the group. But currently notification appears also in case if any message is sent in the group, not only mention. Should we consider with behaviour as expected? 

https://user-images.githubusercontent.com/97245802/213474471-cd35f9f7-8d66-4b32-9f58-7f8b638c9165.mp4

[receiver_1.zip](https://github.com/status-im/status-mobile/files/10457851/receiver_1.zip)
[sender_1.zip](https://github.com/status-im/status-mobile/files/10457852/sender_1.zip)

### Question 2
Should user be removed from group in case he declines group notification?

https://user-images.githubusercontent.com/97245802/213478927-962026c2-b5cc-421a-9fae-1927239a1948.mp4

### Question 3
Currently, the flow with group notifications works only in case if recovered user is mentioned in group by the user who is not in his contact list yet. 
If users are mutual contacts after recovery, then group will appear right in the chats list without any notifications in AC. 
Is this behaviour correct? 


https://user-images.githubusercontent.com/97245802/213493685-799559fb-259f-4ba0-a0cd-f17260e8e442.mp4

**Comment by pavloburykh** [comment]
### ISSUE 1 Group notification is not deleted from AC in case if user was removed from the group

I understand that this is can be considered as an edge case. @ilmotta if you decide that it is better to handle it in separate PR - let me know and I will log a separate issue. 

**Steps:** 

1. Generate group notification for User A
2. Remove User A from group before he accepts/declines group notification
3. See if group notification is still displayed for User A in AC

**Actual result:** group notification is still displayed for User A in AC. Though is case of accepting notification group will not appear in the list which is expected behaviour as he is no more the member of the group

**Expected result:** group notification should be removed if user has been removed from the group. 


https://user-images.githubusercontent.com/97245802/213486276-398562da-3595-4bdf-b6c5-93458e010ad3.mp4

**Comment by ilmotta** [comment]
>@ilmotta thanx for the PR. Additional respect for detailed Summary, that is really helpful and makes our work much more easier and productive!

Good to know :) I'll try to keep the standard for my future PRs!

### Question 1

>But currently notification appears also in case if any message is sent in the group, not only mention. Should we consider with behaviour as expected?

Good catch. I think this is confusing and wrong for users.  I have an idea about how to fix this, but it might be better to do it in a separate issue because it's related to status-go (not much we can do on the client side). I can create the issue for us.

### Question 2

>Should user be removed from group in case he declines group notification?

From what Andrea told me, the user is given the *Decline* option to function as a sort of anti-spam feature. And it means the user doesn't care about the group. But now that you ask, it makes sense to me to also leave the group.

I'll take your feedback to designers. Give me some days @pavloburykh, and I think I'll get an answer about what should be done, but I guess it's better to consider this an improvement/fix for a separate issue, which I can create for us.

### Question 3

>If users are mutual contacts after recovery, then group will appear right in the chats list without any notifications in AC. Is this behaviour correct?

You got it right, the next rounds of development on private group chat notifications should improve this behavior. If users are mutual contacts the notification should appear as well.

### Issue 1

I agree with you, the notification should disappear. I can capture your feedback in a separate issue, as the fix might not be that trivial. Thanks!

**Comment by pavloburykh** [comment]
@ilmotta thanx for your answers. Don't worry about logging separate issues, I will do it by myself  when I finish with this PR tomorrow and it will be merged into develop. Just ping me up when you receive feedback from designers regarding Question 2 and I will log it after that.

**Comment by ilmotta** [comment]
> @ilmotta thanx for your answers. Don't worry about logging separate issues, I will do it by myself when I finish with this PR tomorrow and it will be merged into develop. Just ping me up when you receive feedback from designers regarding Question 2 and I will log it after that.

Excellent, thanks @pavloburykh. I'll keep you posted about Question 2.

**Comment by ilmotta** [comment]
@pavloburykh, could you verify if issue https://github.com/status-im/status-mobile/issues/14744 has been fixed by this PR? In theory it should, but I only tested the fix during development.

**Comment by pavloburykh** [comment]
> @pavloburykh, could you verify if issue #14744 has been fixed by this PR? In theory it should, but I only tested the fix during development.

yeah, this issue is fixed. thank you!

**Comment by pavloburykh** [comment]
@ilmotta Please, take a look at the following case
### ISSUE 2 Group notifs from group member appear automatically for recovered user even if no messages were sent to the group

**Preconditions:** 
User A and User B are mutual contacts
User A and User C are mutual contacts

**Steps:** 
1. User A creates a group and invites User B and User C
2. User B deletes app
4. User B re-installs app and recovers the account
5. No messages are sent to the group by User A or User C
6. User B opens AC
7. See if there are any group notifs in AC for User B

**Actual result:** User B sees group notif  "User C has added User B to the group"

**Expected result:** User B should receive group notifs only in case if he is mentioned or due to temporary issue - if some message is being sent to the group. 


https://user-images.githubusercontent.com/97245802/213689981-287e1d1f-0ab3-49b4-aca1-a93a58864737.mp4

[group_notif_receiver.zip](https://github.com/status-im/status-mobile/files/10466009/group_notif_receiver.zip)

**Comment by ilmotta** [comment]
> 

I'll investigate this one @pavloburykh. I want to at least understand what would the fix look like and if it's on the client or backend side.

**Comment by ilmotta** [comment]
@pavloburykh, I did try to replicate `Issue 2` following your exact steps and preconditions, but the behavior seems correct: After B reinstalls the app, the only notification B sees is a pending contact request from A, which is correct. B has no notifications about the group chat. I tried closing and reopening the app after B accepts the pending contact request from A, but still, no group chat notifications appeared.

I followed the steps by creating accounts A and C on a real smartphone (deployed with this PR's apk) and B in the emulator (so I could easily reinstall the development version). That's the only difference I can think of compared to what you did, but it shouldn't matter right?

How did you perform step 1? *User A creates a group and invites User B and User C*

I did it in one go as per the screenshot below. What do you think we should do?

**Comment by cammellos** [comment]
> @ilmotta Please, take a look at the following case
> 
> ### ISSUE 2 Group notifs from group member appear automatically for recovered user even if no messages were sent to the group
> **Preconditions:** User A and User B are mutual contacts User A and User C are mutual contacts
> 
> **Steps:**
> 
> 1. User A creates a group and invites User B and User C
> 2. User B deletes app
> 3. User B re-installs app and recovers the account
> 4. No messages are sent to the group by User A or User C
> 5. User B opens AC
> 6. See if there are any group notifs in AC for User B
> 
> **Actual result:** User B sees group notif "User C has added User B to the group"
> 
> **Expected result:** User B should receive group notifs only in case if he is mentioned or due to temporary issue - if some message is being sent to the group.
> 
>  telegram-cloud-document-2-5355270596827555045.mp4 
> [group_notif_receiver.zip](https://github.com/status-im/status-mobile/files/10466009/group_notif_receiver.zip)

@pavloburykh @ilmotta this can happen, but it's going to be hard to replicate through the UI, it depends on quite a few things (we can elaborate but probably separately).

Just to make sure though, the user ultimately in this case, regained access to the group chat, is that correct?

If so, seems like it's still a desirable behavior, we can polish this flow as well, but since it's fairly rare (restoring through seed phrase on the same device should happen rarely), seems like we could address separately, what do you think?

**Comment by ilmotta** [comment]
>Just to make sure though, the user ultimately in this case, regained access to the group chat, is that correct?

Correct @cammellos. In my experiments for Issue 2, the user always regained access, either by a mention or by any other message in the group chat. The only difference with the mention is that it generates a notification. Unfortunately, I just couldn't replicate the weird case shared by @pavloburykh where User B is also notified about some random User C not in their contact list.

In terms of future improvements, it would be really nice if after users reinstall the app, previous group chats are displayed automatically. Right now users have to wait for someone to send a message in the group chat and/or to mention them, otherwise the group chat doesn't appear in the Groups List. This is counter-intuitive for most users who are used to think that this metadata is automatically synced back in the UI.

>If so, seems like it's still a desirable behavior, we can polish this flow as well, but since it's fairly rare (restoring through seed phrase on the same device should happen rarely)

It's rare, but maybe not that much. Status-mobile developers will reinstall on the same device more frequently, but fine, we're the exception :laughing: With the current behavior, me (as a user) will probably keep a list of my private group chats in a note, along with people I can ping to mention me "to add me back".

>seems like we could address separately, what do you think?

:+1:

**Comment by pavloburykh** [comment]
> How did you perform step 1? _User A creates a group and invites User B and User C_

@ilmotta thanks for investigation and trying to replicate the issue. My bad, I had missed some details that might be essential in this case. 

First of all - I create Users A and C one one device (IOS) and therefore switching between them. The reason why I do so is that I always experience problems with delivering messages from emulator to physical devices, that's why I try use only physical devices during manual testing. I have only 2 physical devices - 1 IOS and 1 Android, so I have to switch between account if I am testing more than 2 accounts. 

So, in my case more accurate steps will look as following: 

**Steps:** 
1. Create group by User A (in my case IOS) and add User B (in my case Android) during group creation
2. Logout by User A and create User C on this device (IOS)
3. Send contact request from User C to User A (don't forget to copy User's A chat key before that)
4. Logout by User C and switch to User A
5. Accept User’s C contact request by User A
6. Add User C as a new member to the existing group by admin User A: longtap on group in the chats list - Group details - Manage members - select User C from the list - Save. 
7. User B deletes app
8. User B re-installs app and recovers the account
9. No messages are sent to the group by User A or User C
10. User B opens AC
11. **THIS IS IMPORTANT STEP: switch form User A to User C, i.e. logout User A and login by User C**
12. See if there are any group notifs from User C in AC for User B

**Actual result:** In the moment when I login User C, User B receives group notif  "User C has added User B to the group"

**Expected result:** User B should receive group notifs only in case if he is mentioned or due to temporary issue - if some message is being sent to the group. 

On video below you will see a moment when User B recovers the account, enters AC and receives group notif right after User C logins the account


https://user-images.githubusercontent.com/97245802/213873963-298a90b2-f7a9-40f5-94a7-1f9792fd27bb.mp4

[User_B.zip](https://github.com/status-im/status-mobile/files/10472403/User_B.zip)
[User_C.zip](https://github.com/status-im/status-mobile/files/10472404/User_C.zip)

**Comment by pavloburykh** [comment]
@ilmotta followup issue to the described [ISSUE 2](https://github.com/status-im/status-mobile/pull/14785#issuecomment-1399268469) which I haven't faced this issue before, but faced it today when I have been re-investigating ISSUE 2

### ISSUE 3 "Cannot read property 'g' of undefined" error on Accept of group notif

**Steps:** 
1. Perform step from [ISSUE 2](https://github.com/status-im/status-mobile/pull/14785#issuecomment-1399268469)
2. Try to Accept group notif

**Actual result:** "Cannot read property 'g' of undefined" on Accept of group notif. Though no error on Decline

**Expected result:** no error, group appears in chats list


https://user-images.githubusercontent.com/97245802/213873562-78a0bf4e-b1ec-4d5c-805e-02cbbbe44c79.mp4

@ilmotta Please, check the logs I have attached, maybe you will be able to see the rootcause. 
[error_on_accept_group_notif.zip](https://github.com/status-im/status-mobile/files/10472427/error_on_accept_group_notif.zip)

**Comment by pavloburykh** [comment]
> > seems like we could address separately, what do you think?

@ilmotta @cammellos a totally agree. But still, let me take a deeper look at [ISSUE 3](https://github.com/status-im/status-mobile/pull/14785#issuecomment-1399270058) on Monday, cause it seems more serious for me as User is unable to accept group request. I want to figure out how often it happens and what are exact preconditions for that. As for now, I have replicated it following steps from [ISSUE 2](https://github.com/status-im/status-mobile/pull/14785#issuecomment-1399268469)

Sorry, I really don't want to block PR form merge, but it is better to figure out this problem before merging.

**Comment by pavloburykh** [comment]
@ilmotta FYI I have updated video in [ISSUE 2](https://github.com/status-im/status-mobile/pull/14785#issuecomment-1399268469) because I've added wrong one when I posted comment at first time.

**Comment by pavloburykh** [comment]
> ### ISSUE 3 "Cannot read property 'g' of undefined" error on Accept of group notif


@ilmotta could you please take a look at this issue? It turned out that it is reproducible following standard steps that you have left in the [Summary](https://github.com/status-im/status-mobile/pull/14785#issue-1533248031) 

This bug appeared in latest PR builds from 2023-01-20. I haven't faced the issue when I tested previous builds from 2023-01-18. 

**Update on actual result**: "Cannot read property 'g' of undefined" on Accept of group notif. Group notif disappears (marked as read) from AC after reopening of the AC. Unread notification badge remains on AC icon. Group chat does not appear in chats list after accepting this group notif. Group appears in the list after more messages are sent into the group by User A. 


https://user-images.githubusercontent.com/97245802/214029883-5e22b3b8-09d8-442c-a14a-1e36243bb8eb.mp4

[Status-debug-logs (21).zip](https://github.com/status-im/status-mobile/files/10479215/Status-debug-logs.21.zip)

**Comment by ilmotta** [comment]
Hey @pavloburykh, I'm on top of this PR now, and thanks for the thorough analysis.

**Comment by ilmotta** [comment]
> > ### ISSUE 3 "Cannot read property 'g' of undefined" error on Accept of group notif
> 
> @ilmotta could you please take a look at this issue? It turned out that it is reproducible following standard steps that you have left in the [Summary](https://github.com/status-im/status-mobile/pull/14785#issue-1533248031)
> 
> This bug appeared in latest PR builds from 2023-01-20. I haven't faced the issue when I tested previous builds from 2023-01-18.
> 
> **Update on actual result**: "Cannot read property 'g' of undefined" on Accept of group notif. Group notif disappears (marked as read) from AC after reopening of the AC. Unread notification badge remains on AC icon. Group chat does not appear in chats list after accepting this group notif. Group appears in the list after more messages are sent into the group by User A.
> 
>  telegram-cloud-document-2-5366181514566444860.mp4 
> [Status-debug-logs (21).zip](https://github.com/status-im/status-mobile/files/10479215/Status-debug-logs.21.zip)

@pavloburykh, could you please double-check Issue 3? It should be fixed now. At least pressing on Accept/Decline shouldn't throw an error. Unfortunately, sometimes a git rebase is successful, but the code actually has a bug, which was the case here.

**Comment by pavloburykh** [comment]
> @pavloburykh, could you please double-check Issue 3? It should be fixed now. At least pressing on Accept/Decline shouldn't throw an error. Unfortunately, sometimes a git rebase is successful, but the code actually has a bug, which was the case here.

thanx @ilmotta I have re-checked. Error is not thrown on Accept/Decline. 
But still facing following behaviour on Accept action: 
1. Group notif disappears (marked as read) from AC only after reopening of the AC. Unread notification badge remains on AC icon. 
2. Group chat does not appear in chats list after accepting this group notif. It appears in the list only after more messages are sent into the group by User A.

https://user-images.githubusercontent.com/97245802/214042789-1cd0a882-9687-48e9-8c11-649ea6b8ddbd.mp4

[Status-debug-logs_receiver.zip](https://github.com/status-im/status-mobile/files/10479798/Status-debug-logs_receiver.zip)

**Comment by ilmotta** [comment]
> > @pavloburykh, could you please double-check Issue 3? It should be fixed now. At least pressing on Accept/Decline shouldn't throw an error. Unfortunately, sometimes a git rebase is successful, but the code actually has a bug, which was the case here.
> 
> thanx @ilmotta I have re-checked. Error is not thrown on Accept/Decline. But still facing following behaviour on Accept action:
> 
> 1. Group notif disappears (marked as read) from AC only after reopening of the AC. Unread notification badge remains on AC icon.
> 2. Group chat does not appear in chats list after accepting this group notif. It appears in the list only after more messages are sent into the group by User A.
> 
>  telegram-cloud-document-2-5366181514566445155.mp4 
> [Status-debug-logs_receiver.zip](https://github.com/status-im/status-mobile/files/10479798/Status-debug-logs_receiver.zip)

Issue 3 should be fully resolved now @pavloburykh. I managed to accept/decline and see the groups appear on the Group List, as well as seeing the AC's unread count to behave correctly.

**Comment by ilmotta** [comment]
>1. Create group by User A (in my case IOS) and add User B (in my case Android) during group creation
>2. Logout by User A and create User C on this device (IOS)
>3. Send contact request from User C to User A (don't forget to copy User's A chat key before that)
>4. Logout by User C and switch to User A
>5. Accept User’s C contact request by User A
>6. Add User C as a new member to the existing group by admin User A: longtap on group in the chats list - Group details - Manage members - select User C from the list - Save. 
>7. User B deletes app
>8. User B re-installs app and recovers the account
>9. No messages are sent to the group by User A or User C
>10. User B opens AC
>11. **THIS IS IMPORTANT STEP: switch form User A to User C, i.e. logout User A and login by User C**
>12. See if there are any group notifs from User C in AC for User B

@pavloburykh, I have good news! I could reproduce the detailed steps you shared. So it seems `status-go` generates a notification for all members of a group chat telling them when someone else was added to the group chat. Whether we want this or not is a subject for another discussion I guess, but it's the current behavior in `status-go` and I just committed an update to support this.

In practice, when C is added to a group chat where A and B were already members, after B reinstalls, B also sees a notification saying that C was added.

You should see something like the screenshot below where I logged as `B` after reinstall and `Quickwitted` is user `C` and `Remorseful` is `A` (the group admin). Seems about right, what do you say?

**Comment by pavloburykh** [comment]
> Issue 3 should be fully resolved now @pavloburykh. I managed to accept/decline and see the groups appear on the Group List, as well as seeing the AC's unread count to behave correctly.

@ilmotta thanx for resolving ISSUE 3. I have checked and confirm that it has been fixed.

**Comment by pavloburykh** [comment]
@ilmotta I saw your comment regarding ISSUE 2, but seems like it is deleted now. Should I check your fix for ISSUE 2 or you need some more time for additional changes? Anyway, PR LGTM now, I can log the rest of issues separately as we agreed above.

**Comment by ilmotta** [comment]
> @ilmotta I saw your comment regarding ISSUE 2, but seems like it is deleted now. Should I check your fix for ISSUE 2 or you need some more time for additional changes? Anyway, PR LGTM now, I can log the rest of issues separately as we agreed above.

Sorry about that, I had to delete the comment because it was actually incorrect. I could reproduce the steps you outlined about Issue 2. It's definitely an issue IMO, but the fix is entirely on the backend. I tried a fix now, but I just reverted it.

> Anyway, PR LGTM now, I can log the rest of issues separately as we agreed above.

Agreed, and I think the fix should be deprioritized for a little while until we nail the release on Feb. Would that be okay in your opinion? Edit: I'm suggesting this because this is a somewhat edge case, but it's ugly for users, we should definitely fix this at some point.

**Comment by pavloburykh** [comment]
> Agreed, and I think the fix should be deprioritized for a little while until we nail the release on Feb. Would that be okay in your opinion? 

@ilmotta totally agree with you. Those are edge cases with low priority. We might want to look at them for rc-2,  definitely not rc-1. Thanks for your work!
