### PR TITLE
chore: slider button - add error type, blur variant and fix small ui bug

### LINKED ISSUE #17444: Quo 2 slide button - implement missing variants and fix some minor UI issues
The quo2 Slider button is missing some variants - blur

Additionally fix these UI issues.

**ISSUE 2 Biometric icon appears when sliding to the end**
https://github.com/status-im/status-mobile/pull/16916#issuecomment-1708485109
Screenshot 2023-09-28 at 12 20 53

ISSUE 3 Placeholder text partially remains visible for a moment behind the slider
https://github.com/status-im/status-mobile/pull/16916#issuecomment-1708485670
Screenshot 2023-09-28 at 12 21 44

additionally ensure the api is matching figma as agreed in the best practices
update it's uses in the application

These issues were caught in the pr https://github.com/status-im/status-mobile/pull/16916

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/17444

This pr adds the blur variant for the slider button. 

It also adds the blur. Note - with the blur & error variant - I have not implemented the changing background color yet as that will involve some further in put from design on what is expected of the color transition. Something I only discovered while implementing these changes. Will create a follow up for that.

blur

blur and type danger

Syncing Page:

**To Test:**
only changes to slider button so wherever this is used in the app - currently only in the syncing screens (afaik)

design review: 
check the slider button in quo2 preview

### CODE REVIEW

File: src/quo2/components/buttons/slide_button/animations.cljs [hunk 1]
```diff
@@ -22,7 +22,7 @@
 (defn- track-cover-interpolation
   [track-width thumb-size]
   {:in  [0 1]
-   :out [(/ thumb-size 2) track-width]})
+   :out [(/ thumb-size 1.8) track-width]})
```
Comment (J-Son89) [inline src/quo2/components/buttons/slide_button/animations.cljs]: @clauxx wdyt? 🤔

File: src/quo2/components/buttons/slide_button/animations.cljs [hunk 2]
```diff
@@ -22,7 +22,7 @@
 (defn- track-cover-interpolation
   [track-width thumb-size]
   {:in  [0 1]
-   :out [(/ thumb-size 2) track-width]})
+   :out [thumb-size track-width]})
```
Comment (J-Son89) [inline src/quo2/components/buttons/slide_button/animations.cljs]: @clauxx wdyt?

Comment (clauxx) [reply src/quo2/components/buttons/slide_button/animations.cljs]: I think smth like this would be better, to assure the cover moves together with the right edge of the thumb, so on quick slides it's less likely that it would be visible on the other side:

```clj
(defn- track-cover-interpolation
  [track-width thumb-size]
  {:in  [0 1]
   :out [thumb-size (+ track-width thumb-size)]})
```
Here's the before `[thumb-size track-width]` and after `[thumb-size (+ track-width thumb-size)]` _(red is the cover)_:

Screenshot 2023-10-03 at 13 23 07
Screenshot 2023-10-03 at 13 22 25

Comment (clauxx) [reply src/quo2/components/buttons/slide_button/animations.cljs]:
```suggestion
   :out [thumb-size (+ track-width thumb-size)]})
```

File: src/status_im2/contexts/quo_preview/buttons/slide_button.cljs [hunk 3]
```diff
@@ -1,39 +1,57 @@
...
+                       (reset! complete? true)
+                       (js/setTimeout #(reset! complete? false) 50))
+                     [(:size @state)])
       [preview/preview-container
        {:state                     state
         :descriptor                descriptor
-        :component-container-style {:align-items :center}}
+        :component-container-style (when-not @blur? (:align-items :center))
+        :blur?                     @blur?
+        :show-blur-background?     true}
```
Comment (clauxx) [inline src/status_im2/contexts/quo_preview/buttons/slide_button.cljs:40]: If blur is only for the dark theme, should add the `blur-dark-only?` prop as well.

File: src/quo2/components/buttons/slide_button/animations.cljs (hunk 2 above)
Comment (J-Son89) [reply src/quo2/components/buttons/slide_button/animations.cljs]: thanks, and I appreciate the very clear images! :)

File: src/status_im2/contexts/quo_preview/buttons/slide_button.cljs (hunk 3 above)
Comment (J-Son89) [reply src/status_im2/contexts/quo_preview/buttons/slide_button.cljs:40]: imo, this feature would have benefitted from discussion before being merged/moved forward. This `blur-dark-only?` option ignores that there is also `blur-light-only` (at least I think there is some cases). Not to mention that there is many incorrect configurations of components possible on the preview screens. The button is a good example of this and a better alternative (imo) is to block incorrect configurations via disabling the descriptors for relevant options. This would of course benefit a lot if Mali gets added to the codebase. 

Having this discussion was mentioned here (although I'm not sure if the pr with this feature had got merged before, I assume it had so no big deal): 
https://github.com/status-im/status-mobile/pull/17271#issuecomment-1717450276
response  - https://github.com/status-im/status-mobile/pull/17271#issuecomment-1717517944
response  - https://github.com/status-im/status-mobile/pull/17271#issuecomment-1717914905

imo it should be commonplace to discuss with those interested in the team before we add new features to the preview screens as they tend to effect everyone, and with a team so large it takes a while to make later refactors once a feature starts getting used.

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM

**Review by clauxx — APPROVED** [review]
Looks good!

**Comment by pavloburykh** [comment]
@J-Son89 thanx for the PR. Please take a look at the issue

### ISSUE 1 Blurred slider is barely visible in light mode

**Preconditions:** app has light mode on

**Steps:** 

1. Open Quo2 preview
2. Set Blur mode
3. Pay attention at slider

**Actual result:** 

Slider is barely visible

photo_2023-10-10 14 32 54


**Expected result:** 

[Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=19085-205591&mode=design&t=VlGzFYC1mRn7Tkyb-0)

Design System for Mobile – Figma 2023-10-10 14-49-26

**Comment by J-Son89** [comment]
Thanks @pavloburykh - that's expected but not desirable :). There is no `blur` variant for light theme. 
I didn't block this incorrect configuration from being possible as currently @ilmotta has an open discussion to include a generic tool to our codebase which will help us prevent incorrect configurations being possible in these preview screens.

**Comment by pavloburykh** [comment]
> Thanks @pavloburykh - that's expected but not desirable :)

Thank you @J-Son89! Could you please rebase the PR as it is quite outdated. After that we will need to re-run e2e as they failed due to a problem of outdated branch.

**Comment by J-Son89** [comment]
@pavloburykh - done! apologies I thought I did that this morning. :/

**Comment by pavloburykh** [comment]
@J-Son89 e2e are okay. Ready for design review cc @Francesca-G

**Review by Francesca-G — APPROVED** [review]
Looks good ✨

@pavloburykh I saw you already noticed the light blur issue, so I didn't leave any comment on that. A quick update about the copy of the button overall, as clarified [here](https://discord.com/channels/624634427930312714/1034750698086207498/1160922125096464404), we should always use "Slide" instead of sign (which was featured in some wallet designs).
Examples:
- Slide to reveal code
- Slide to create account
- Slide to reveal phrase
- Slide to bridge _(previously "Slide to sign")_

**Review by BalogunofAfrica — APPROVED** [review]
