### PR TITLE
[15902] BUGFIX - Resolve public keys into the user's name in the confirmation drawer

### LINKED ISSUE #15902: Public keys in image description instead of usernames
# Bug Report
![Uploading 238396943...]

## Problem 
Username shows as PK in image preview

image

#### Expected behavior
Username should be resolved into his selected name or nickname

#### Actual behavior
Username shows PK instead of user's name

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #15902 

### Summary

Fixes wrong OR operator on confirmation drawer of destructive actions on chat items on the home screen.

status: ready

### CODE REVIEW

**Review by alwx — APPROVED** [review]

File: src/status_im2/common/confirmation_drawer/view.cljs [hunk 1]
```diff
@@ -34,9 +34,9 @@
                     profile-picture name]} context
             id                             (or chat-id public-key)
             display-name                   (or
-                                            name
                                             (when-not group-chat
-                                              (rf/sub [:contacts/contact-name-by-identity id])))
+                                              (rf/sub [:contacts/contact-name-by-identity id]))
```
Comment (ilmotta) [inline src/status_im2/common/confirmation_drawer/view.cljs:38]: This is the kind of thing we should have a subscription for, so that we can avoid code duplication to handle the logic for display names.

**Review by ilmotta — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil thank you for your PR. unfortunately one issue is still reproduced

## ISSUE 1: User's chatkey is shown instead of display name/ENS/nickname when the image is opened
### Steps to Reproduce:
1. Open a chat conversation.
2. Send the image with the mention
3. Tap on an image

### Actual Result:
When the image is opened, the user's chatkey is displayed instead of their display name, ENS or nickname.
image

### Expected Result:
When the image is opened, the user's display name, ENS, or nickname should be shown instead of their chatkey.

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil thank you for your PR. unfortunately one issue is still reproduced
> 
> ## ISSUE 1: User's chatkey is shown instead of display name/ENS/nickname when the image is opened
> ### Steps to Reproduce:
> 1. Open a chat conversation.
> 2. Send the image with the mention
> 3. Tap on an image
> 
> ### Actual Result:
> When the image is opened, the user's chatkey is displayed instead of their display name, ENS or nickname. image
> 
> ### Expected Result:
> When the image is opened, the user's display name, ENS, or nickname should be shown instead of their chatkey.

I think we're gpoi

**Comment by ibrkhalil** [comment]
> > Hi @ibrkhalil thank you for your PR. unfortunately one issue is still reproduced
> > ## ISSUE 1: User's chatkey is shown instead of display name/ENS/nickname when the image is opened
> > ### Steps to Reproduce:
> > 
> > 1. Open a chat conversation.
> > 2. Send the image with the mention
> > 3. Tap on an image
> > 
> > ### Actual Result:
> > When the image is opened, the user's chatkey is displayed instead of their display name, ENS or nickname. image
> > ### Expected Result:
> > When the image is opened, the user's display name, ENS, or nickname should be shown instead of their chatkey.
> 
> I think we're going to disable the text preview for now as @OmarBasem  is still working on features here, But I will add the resolving of the public-key->name here too.

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil thank you for your PR. unfortunately one issue is still reproduced
> 
> ## ISSUE 1: User's chatkey is shown instead of display name/ENS/nickname when the image is opened
> ### Steps to Reproduce:
> 1. Open a chat conversation.
> 2. Send the image with the mention
> 3. Tap on an image
> 
> ### Actual Result:
> When the image is opened, the user's chatkey is displayed instead of their display name, ENS or nickname. image
> 
> ### Expected Result:
> When the image is opened, the user's display name, ENS, or nickname should be shown instead of their chatkey.

This will require creating another endpoint on status-go to resolve mentions for a message, Instead of the current implementation which only concerns resolving them for composer.
I'll start working on this but let's please make it a separate issue from this one as it's a bit different.

**Comment by ibrkhalil** [comment]
> > Hi @ibrkhalil thank you for your PR. unfortunately one issue is still reproduced
> > ## ISSUE 1: User's chatkey is shown instead of display name/ENS/nickname when the image is opened
> > ### Steps to Reproduce:
> > 
> > 1. Open a chat conversation.
> > 2. Send the image with the mention
> > 3. Tap on an image
> > 
> > ### Actual Result:
> > When the image is opened, the user's chatkey is displayed instead of their display name, ENS or nickname. image
> > ### Expected Result:
> > When the image is opened, the user's display name, ENS, or nickname should be shown instead of their chatkey.
> 
> This will require creating another endpoint on status-go to resolve mentions for a message, Instead of the current implementation which only concerns resolving them for composer. I'll start working on this but let's please make it a separate issue from this one as it's a bit different.

Sorry for this, I actually realized I can reuse the same endpoint/logic we use when rendering textual messages.
This is fixed.

**Comment by ibrkhalil** [comment]
BLOCKED: Until we fix the image description view in Lightbox

File: src/status_im2/contexts/chat/lightbox/bottom_view.cljs [hunk 2]
```diff
@@ -50,15 +50,17 @@
...
      {:colors [:black :transparent]
       :start  {:x 0 :y 1}
       :end    {:x 0 :y 0}
       :style  (style/gradient-container insets animations derived)}
-     (when constants/image-description-in-lightbox?
-       [rn/text {:style style/text-style} text])
+     [message-view/render-parsed-text
+      {:content        content
+       :chat-id        chat-id
+       :style-override style/text-style}]
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/lightbox/bottom_view.cljs:63]: imo this approach could be improved upon here.
this prop drilling of some static styles and then later using it at boolean to set an override color to some nested text as white.

Can you give some more context to what you are trying to achieve here so we can try to approach this differently?

File: src/status_im2/common/confirmation_drawer/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im2/common/confirmation_drawer/view.cljs:38]: can we either add this as part of this pr, or create a follow up issue so it can be addressed?

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 3]
```diff
@@ -75,15 +75,17 @@
 
 
 (defn render-block
-  [blocks {:keys [type literal children]} chat-id]
+  [blocks {:keys [type literal children]} chat-id style-override]
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs:94]: see my comment above 👍

**Review by J-Son89 — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/chat/lightbox/bottom_view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/lightbox/bottom_view.cljs:63]: I want to be able to use the same text styles in the text preview part of lightbox.

I thought I can reuse the same text rendering logic there.

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/lightbox/bottom_view.cljs:63]: If we were to create a separate implementation of this to not hardcode the props, We'd still face duplication.

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 4]
```diff
@@ -75,15 +75,17 @@
...
   (case (keyword type)
     :paragraph
     (conj blocks
           [rn/view {:style style/paragraph}
            (reduce
             (fn [acc e]
               (render-inline acc e chat-id))
-            [quo/text]
+            [quo/text
+             {:style {:color (when (seq style-override)
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: (sorry for comment jumping). This here is my main concern as it couples the text color changing to when this `style-override` prop is used which is a bit unexpected.

One alternative is to just pass the `container-style` and `text-style` as 
props to `render-parsed-text` function like this:

```
(defn render-parsed-text
  [{:keys [content chat-id edited-at container-style text-style]} ]
  ^{:key (:parsed-text content)}
  [rn/view {:style container-style}
   (reduce (fn [acc e]
             (render-block acc e chat-id text-style))
           [:<>]
           (cond-> (:parsed-text content)
             edited-at
             add-edited-tag))])

(defn text-content
  [message-data]
  [rn/view
   [render-parsed-text (assoc message-data :container-style style/parsed-text-block)]
   [link-preview/view message-data]])
   ```
   
   and so in your file it would be:
   ```
   [message-view/render-parsed-text
      {:content        content
       :chat-id        chat-id
       :container-style style/text-style ;consider changing this name of variable :)
       :text-style {:color colors/white}]
   ```
    
   The only thing then that is still a bit off to me is why this text-style is also not applied to the other cases in the `render-text-block` function, i.e:   `:edited-block`,  `:blockquote`,  `:codeblock`. However maybe that's fine for now. 
   
   Anyway I'll leave it to you for how best to approach it as you know this code better :)

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: You're totally right, I considered the other types of textual message in the process.

**Comment by churik** [comment]
@ibrkhalil 
can you please resolve conflicts and notify QA when the PR is unblocked and ready to be tested? 
thanks!

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Fixed

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs:94]: It was just a notation by Icaro, Nothing to be done here.

**Comment by VolodLytvynenko** [comment]
Hi, @ibrkhalil issue 1 is fixed. Thank you! One more issue has been identified, but I'm unsure if it is within the scope of this PR. Please let me know if it would be better to address it in a separate follow-up.

## ISSUE 2: "Changing onViewableItemsChanged error on the fly is not supported" error shown when tapping on a mention within an opened image
### Steps:
1. Send image with the mention
2. Open the image
3. Tap the mention

### Actual result:
When tapping on a mention within the opened image, an error message is displayed: "Changing onViewableItemsChanged error on the fly is not supported".

https://github.com/status-im/status-mobile/assets/52490791/6aaff7f4-2a5f-42f4-a979-34b6fc47c376

### Expected result:
The mention navigates the user to the appropriate profile

### logs:
[Status.log](https://github.com/status-im/status-mobile/files/11867610/Status.log)
https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0

**Comment by ibrkhalil** [comment]
> Hi, @ibrkhalil issue 1 is fixed. Thank you! One more issue has been identified, but I'm unsure if it is within the scope of this PR. Please let me know if it would be better to address it in a separate follow-up.
> 
> ## ISSUE 2: "Changing onViewableItemsChanged error on the fly is not supported" error shown when tapping on a mention within an opened image
> ### Steps:
> 1. Send image with the mention
> 2. Open the image
> 3. Tap the mention
> 
> ### Actual result:
> When tapping on a mention within the opened image, an error message is displayed: "Changing onViewableItemsChanged error on the fly is not supported".
> 
>  error_mention.mp4 
> ### Expected result:
> The mention navigates the user to the appropriate profile
> 
> ### logs:
> [Status.log](https://github.com/status-im/status-mobile/files/11867610/Status.log) https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0

Let's do this as a follow up, As it's not related and also it'll require testing on multiple devices

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 5]
```diff
@@ -9,87 +9,106 @@
...
-           {:weight :medium
-            :style  {:font-size 11 ; Font-size must be used instead of props or the
-                                   ; styles will clash with original message text
-                     :color     (colors/theme-colors colors/neutral-40
-                                                     colors/neutral-50)}}
-           literal])
-    :status-tag
-    (let [community-id (rf/sub [:community-id-by-chat-id chat-id])]
+  [units {:keys [type literal destination]} chat-id style-override]
+  (let [show-as-plain-text? (seq style-override)]
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs:13]: this could just be the prop value instead, would be slightly nicer as you don't couple style override to this.
e.g
```
(defn render-inline
  [units {:keys [type literal destination]} chat-id show-as-plain-text? ]
  ...
 ```
 
```
(render-inline {...} "chat-id" (seq style-override)) ...
```

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil, thank you for the fixes. Sorry for the testing delay. No issues from my side. Ready to be merged
