### PR TITLE
Error when tap on Terms of use during Onboarding flow #20239

### LINKED ISSUE #20239: Error when tap on Terms of use during Onboarding flow
# Bug Report

### Reproduction

1. Install app
2. Tap on Terms of use on Intro screen

#### Actual behavior
Cannot set property 'reagent-compiler2' of null error
Screenshot 2024-05-29 at 11 57 33

#### Expected behavior
Screenshot 2024-05-29 at 11 55 51

https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465-88185&t=jQQHDemuPVlCtWel-0

[status_logs.zip](https://github.com/status-im/status-mobile/files/15482634/status_logs.zip)

### Additional Information

- Status version: release 2.29 and nightly 28/05
- Operating System: Android/iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #20241: Implement terms of service view on onboarding
As a user
I want to be able to read the terms of service
So I understand the implications of using the status app

### Description
We should implement this screen, previously it was pointing at a url that no longer exists.

https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465-88185&t=jQQHDemuPVlCtWel-0

Please check with legal if the desktop terms are good enough, otherwise check if they can provide some.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #20239
fixes [#20241](https://github.com/status-im/status-mobile/issues/20241)

image

Note: Font style not fully implemented, no headers, gradient on scroll not implemented

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

File: src/status_im/contexts/onboarding/intro/view.cljs [hunk 1]
```diff
@@ -44,9 +44,13 @@
...
       (i18n/label :t/by-continuing-you-accept)]
      [quo/text
-      {:on-press #(debounce/throttle-and-dispatch [:open-modal :privacy-policy] 1000)
-       :size     :paragraph-2
-       :weight   :regular
-       :style    style/highlighted-text}
+      {:on-press
+       #(debounce/throttle-and-dispatch
+         [:browser.ui/open-url
+          "https://raw.githubusercontent.com/status-im/status-desktop/master/ui/imports/assets/docs/terms-of-use.mdwn"]
```
Comment (J-Son89) [inline src/status_im/contexts/onboarding/intro/view.cljs]: should we put it in a constant? 🤔

Comment (flexsurfer) [reply src/status_im/contexts/onboarding/intro/view.cljs]: i don't think so, it's a temporary solution, so as less as possible changes should be done

**Review by jo-mut — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fix @flexsurfer! PR can be merged
