### PR TITLE
[WIP] Fix bot subscriptions

### LINKED ISSUE #2220: Fee value is not changing if move slider after amount is typed
### Description

*Type*: Bug

*Summary*: For send command in chat: if move Fee slider to the max/min value when amount is already typed then fee value is not changing. For example, you typed "2" as amount and default value is 0.0004200. Than you move slider to the max position -> fee value is not changing and is 0.0004200. This is wrong, as fee should increase.

Note 1: if type amount after slider is moved then fee value is changed (expected). For example, you have deleted typed amount, moved slider to max position and type "2" as amount -> fee value is changing from 0.0004200 to 0.0008644.

Note2: this functionality works fine in released 0.9.11

#### Expected behavior
User typed amount, moved slider to max (or min) position -> fee value is increased (decreased)  
#### Actual behavior
User typed amount, moved slider to max (or min) position -> fee value is the same as default 

### Reproduction
https://app.testfairy.com/projects/4803590-status/builds/6901604/sessions/3/?accessToken=Et40fGBE85h-tbSOVXSc1Lpkk6c

- Open Status
- Open 1-1 chat
- tap on /send
- wait for suggestions with Fee slider to be shown. Remember the default fee value 
- type some amount, e.g "2". Remember the fee value for it
- move fee slider to the right (faster). wait 1 minute to see if fee value will be changed (it's expected to be greater than previous default value)
-  move fee slider to the left (cheaper). wait 1 minute to see if fee value will be changed

### Additional Information
* Status version: develop  0.9.11d272
* Operating System: 
Real device iPhone 6s, iOs 10.3.3
Real device Samsung Galaxy S6, android 6.0.1

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #2220 and maybe couple of other bugs

### Summary:

Too tired to provide proper explanation of the causes and fix, will do it in the morning.

### Steps to test:
- Exercise `/send` command in 1-1 and group chats

status: wip

### CODE REVIEW

File: resources/js/bots/transactor_personal/bot.js [hunk 1]
```diff
@@ -62,13 +62,25 @@ function amountParameterBox(params, context) {
...
+    try {
+
+        status.setDefaultDb({
+            transaction: txData,
+            calculatedFee: calculateFee(sliderValue, txData),
+            feeExplanation: getFeeExplanation(sliderValue),
+            sliderValue: sliderValue
+        });
 
+    } catch (err) {
```
Comment (jeluard) [inline resources/js/bots/transactor_personal/bot.js:74]: How about only having `calculateFee` in try/catch so that the call to `setDefaultDb` is not duplicated?

File: src/status_im/bots/events.cljs [hunk 2]
```diff
@@ -59,6 +50,28 @@
   [{:keys [current-chat-id] :as app-db}]
   (assoc-in app-db [:bot-db current-chat-id] nil))
 
+(def ^:private keywordize-vector (partial mapv keyword))
+
+;; TODO(janherich): do something with this horrible triple nested reduce so it's more readable
+(defn add-active-bot-subscriptions
```
Comment (jeluard) [inline src/status_im/bots/events.cljs:56]: Please introduce smaller functions. 

Also add tests to make sure we don't introduce regressions.

File: src/status_im/bots/events.cljs [hunk 3]
```diff
@@ -74,25 +87,11 @@
...
-                    (assoc-in opts [:subscriptions sub-name] keywordized-sub-path))))
-     db
-     subscriptions)))
-
-(handlers/register-handler-db
   ::calculated-subscription
   [re-frame/trim-v]
   (fn [db [{:keys                  [bot path]
             {:keys [error result]} :result}]]
+    (log/debug (str "Subs-chck result - Bot: " bot " Path: " path " Result: " (or error result)))
```
Comment (jeluard) [inline src/status_im/bots/events.cljs]: Do we want to keep that?

**Review by jeluard — DISMISSED** [review]

**Comment by jeluard** [comment]
I can see a number of `TODO` left. Do you plan to address them now? If not it would help to have some issues to keep track of those.

File: src/status_im/native_module/impl/module.cljs [hunk 4]
```diff
@@ -143,50 +144,20 @@
...
-  "Calls to jail are executed ne by one with interval-between-calls,
-  which reduces chances of response shuffling"
-  []
-  (go-loop [_ nil]
-    (let [next-call (last @jail-calls)]
-      (swap! jail-calls butlast)
-      (when next-call
-        (execute-call next-call)))
-    (recur (<! (timeout interval-between-calls)))))
+;; TODO(janherich): temporal solution, should be fixed on status-go side
```
Comment (flexsurfer) [inline src/status_im/native_module/impl/module.cljs]: maybe it's already fixed on go side and we can remove this?

**Review by flexsurfer — CHANGES_REQUESTED** [review]
agree with @jeluard comments

File: src/status_im/native_module/impl/module.cljs (hunk 4 above)
Comment (flexsurfer) [reply src/status_im/native_module/impl/module.cljs]: @janherich yes. it was fixed https://github.com/status-im/status-go/issues/372, so we can remove this temporal solution

Comment (rasom) [reply src/status_im/native_module/impl/module.cljs]: @flexsurfer 
1. PR is still wip, idk guys why you started reviewing 
2. This code still looks useful because it increases the number of calls to the jail 

@janherich 
`dedupe` will not work for calls, because they all are different at least because of `:callback` property. We probably could write our own transducer here.

Comment (janherich) [reply src/status_im/native_module/impl/module.cljs]: @rasom Yes, I will do it, `(dedupe)` is a super quick solution, but we can't do the same thing as before (deduplicate on basis of `[jail-id path]` alone) because it partially broke subscriptions (in addition to another recent command-loading changes which totally broke subscriptions).
The reason why is that when you had more then one subscription dependent on common property (such as `feeValue` and `feeExplanation` dependent on `[:sliderValue])`, only one subscription call went through, all other were discarded by the de-duplication code previously there (because the `[jail-id path]` tuple is the same for all subscriptions from one bot).
And once I removed de-duplication from the former code, I realised it performed jail calls in opposite order (when there was more then one "waiting") + never properly cleaned the "waiting queue" so I decided to re-write it to something much simpler which is doing the same thing.

File: src/status_im/bots/events.cljs (hunk 2 above)
Comment (janherich) [reply src/status_im/bots/events.cljs:56]: Technically we can't introduce regression to functionality which is totally broken and not working and all (as are bot subscriptions currently in develop) :) 
But I get your point, will introduce smaller functions and some basic tests.

File: resources/js/bots/transactor_personal/bot.js (hunk 1 above)
Comment (janherich) [reply resources/js/bots/transactor_personal/bot.js:74]: I didn't put much thought to that as I was simply making sure that `transactor_personal`/`transactor_group` code is the same and behaving consistently, I can certainly do that.

File: src/status_im/native_module/impl/module.cljs (hunk 4 above)
Comment (rasom) [reply src/status_im/native_module/impl/module.cljs]: tbh to make it work properly with subscriptions, i mean old code, we just need to add one condition there. Just in case if writing of a proper solution with transducer will take too much time.

Comment (janherich) [reply src/status_im/native_module/impl/module.cljs]: @rasom I thought the same as well but it's not true, see the last paragraph of the comment above - once the de-duplication is working in a way that more then one call is "waiting to be executed" (after de-duplication) the calls are performed in wrong (opposite) order + there always seems to be one extra old call which is executed with the newest one.

Comment (rasom) [reply src/status_im/native_module/impl/module.cljs]: >  there always seems to be one extra old call which is executed with the newest one.

can't reproduce this, though ordering and `:subscription` problem can be fixed with this code
https://github.com/status-im/status-react/commit/3107a9936401c3db3117d8bd97b55bb11a3a0c69

the rest stuff is related to proper handling of the callback

File: src/status_im/bots/events.cljs (hunk 2 above)
Comment (rasom) [reply src/status_im/bots/events.cljs:56]: Let's do this in separate PR

**Review by flexsurfer — APPROVED** [review]

**Review by rasom — APPROVED** [review]
