### PR TITLE
fix: wallet home loading state

### LINKED ISSUE #20265: wallet: improve loading after login
Currently the initial loading of the wallet on login goes as follows.

It starts off balance 0
then goes to loading state 
and then loaded (see video)

Expected: It should just go straight to loading state

see:
https://github.com/status-im/status-mobile/assets/22799766/9d1dd661-64ab-4caf-bc5d-8fce6d45ecf3

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/20265

### Summary
This PR fixes loading state when starting wallet. Previously it starts at 0, then goes to loading state, then displays data. Now it starts at loading state immediately.

Skipping QA as it is a simple fix.

### Demo

https://github.com/status-im/status-mobile/assets/29354102/1b7942ef-d590-44fd-8698-88da2feaae27

### CODE REVIEW

File: src/status_im/contexts/wallet/db.cljs [hunk 1]
```diff
@@ -6,4 +6,5 @@
    :selected-networks (set constants/default-network-names)})
 
 (def defaults
-  {:ui {:network-filter network-filter-defaults}})
+  {:ui {:network-filter network-filter-defaults
+        :tokens-loading? true}})
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/db.cljs:10]: I have made changes to this key in PR: https://github.com/status-im/status-mobile/pull/20160

Comment (OmarBasem) [reply src/status_im/contexts/wallet/db.cljs:10]: @smohamedjavid I don't see any changes to the file: `wallet/db.cljs` in the mentioned PR: https://github.com/status-im/status-mobile/pull/20160

Comment (OmarBasem) [reply src/status_im/contexts/wallet/db.cljs:10]: I see you renamed the event, but the key's name in the db is still the same right?

Comment (ulisesmac) [reply src/status_im/contexts/wallet/db.cljs:10]: @OmarBasem  have you considered modifying the subscription instead?
In the subscription you could say:
 if it's `nil` or `true`   -> loading
 if `false` -> loaded.
 
 ofc, you should carefully check that this solution works all the time and we don't have unexpected loading cases.

BTW, this is a common issue for `loding?` flags, sometimes I prefer instead a `ready?` flag.

Comment (OmarBasem) [reply src/status_im/contexts/wallet/db.cljs:10]: > if it's nil or true -> loading

@ulisesmac why should we modify the subscription and have an extra condition check? I think simply setting `:tokens-loading? true` is cleaner, as we want the wallet to be in loading state when it starts

**Comment by J-Son89** [comment]
Great work @OmarBasem! 🙌 

Some questions more so for a follow up issue. 

On loading should we change the + account card button to a loading one of the users customization color?
- a bit of effort for sure but maybe it will look better? 🤔  or some alternative suggestions?
i.e this screen:
Screenshot 2024-06-04 at 11 09 24

Also the content tends to jump a bit going from loading to loaded. Does anyone have any suggestions for how we can improve this? Perhaps animations or identify what content on screen causes this to happen and fix that in place?

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/db.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/db.cljs:10]: Setting a value in db as `true` has the problem that before dispatching that event, the key is `nil`, for loading states sometimes is not the best.

We don't need to modify the subscription, I was just asking if you already considered that approach.

Please, take the approach that solves the problem better 👍

**Comment by OmarBasem** [comment]
> On loading should we change the + account card button to a loading one of the users customization color?

@J-Son89 We can do that. It would be even better if we can go the loading state of the accounts cards directly without having that state where there is only the plus card

> Also the content tends to jump a bit going from loading to loaded

I noticed going from the state of having the plus icon to the accounts loading, the content gets pushed down, then when loaded pushed up. I have opened an issue to investigate these 2 problems: https://github.com/status-im/status-mobile/issues/20328

**Review by briansztamfater — APPROVED** [review]
LGTM

**Comment by OmarBasem** [comment]
Hey @status-im/mobile-qa, can you please check e2e?

**Comment by pavloburykh** [comment]
> Hey @status-im/mobile-qa, can you please check e2e?

Hey @OmarBasem! Failed e2e are not PR related. We still experience issues on Waku side, that's why bunch of tests are failing. Ready for merge.
