### PR TITLE
Resolve username to ENS after 1-1 chat opened by ENS search

### LINKED ISSUE #12027: Username not resolved to ENS right after 1-1 chat opened after username search from 'Start new chat' by ENS
# Bug Report

## Problem

When searching user by ENS name from 'Start new chat' we display user ENS name found. But when tap upon username item from profile search and navigating to 1-1 chat view - there is a default three-word name displays.
Later, if ENS name synced in chat, - it's correctly updated as chat name. However, it makes sense to display ENS name right away since user have searched ENS.

#### Expected behavior

ENS name shown as username of 1-1 chat after user was found by ENS name in 'Start new chat'

#### Actual behavior

https://user-images.githubusercontent.com/8749671/115562948-aecc2600-a2bf-11eb-8982-8e3741377757.mov

### Reproduction

- Open Status and create new account
- Open `(+)` -> `Start new chat` -> type 'statuse2e'
- Tap on found user to open 1-1 chat

### Additional Information
- Status version: develop/release 1.13
- Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #12027 

### Summary

We need to resolve username to ENS after 1-1 chat opened by ENS search. This PR approach is to get the ens name from `contacts/new-identity` db key if exists, and include it in `contacts/contact-two-names-by-identity` returning contact. Also include ens-name as default nickname if adding to contacts from the chat.

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats

### Steps to test

- Open Status
- Tap on +
- Start new chat
- Search user by ENS
- Start chat with ENS user

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Comment by qoqobolo** [comment]
@briansztamfater

#### ISSUE 1: ENS name changes to a 3-random name in the chat list when focusing on the search field, if 1-1 chat with this user was started using `+`> `Start new chat`
Also, ENS name changes to 3-random in the chat list when pressing on `Start new chat` (video 2).


https://user-images.githubusercontent.com/67952253/117827045-f1ef3880-b270-11eb-856c-f1c757d7334e.mp4


https://user-images.githubusercontent.com/67952253/117827060-f4519280-b270-11eb-9b91-5df3bf6ebcf2.mp4


**Steps:**

**_Case 1:_**
- Open Status
- Tap `+` button on the Home screen > `Start new chat`
- Enter ENS
- Open 1-1 chat
- Open the Home screen
- Set focus to search field

**_Case 2:_**
- Open Status
- Tap `+` button on the Home screen > `Start new chat`
- Enter ENS
- Open 1-1 chat
- Open the Home screen
- Tap `+` button on the Home screen > tap `Start new chat` and pay attention to ENS in the chat list

Operating System: Android, iOS

**Comment by briansztamfater** [comment]
Good catch @qoqobolo, I will work on both issues and let you know.

**Comment by briansztamfater** [comment]
@qoqobolo Just pushed the fix but issue will persist when closing and reopening the app for non-contact chats. Let me know if I should work on persistence for ENS names, that should fix that case too.

**Comment by briansztamfater** [comment]
@qoqobolo Fixes are pushed. Let me know if other issue arises!

**Comment by qoqobolo** [comment]
@briansztamfater thanks for fix!
Yeah, it would be nice to have this case fixed as well, if it's not much trouble for you, because it is quite visible to users.

**Comment by qoqobolo** [comment]
@briansztamfater 

### ISSUE 2: ENS is displayed as a nickname in user's profile if User1 adds to contacts User2 via `+ Add to contacts` in the 1-1 chat view;
After removing ENS from the nickname field 3-random name is displayed in user's profile until he is re-added to contacts.

### ISSUE 3: ENS changes to 3-random and back in user's profile view depending on adding to contacts and adding nickname

**_Steps (for both issues):_** 
- `+` button > `Start new chat` > Start 1-1 chat with ENS-user (e.g. `ditest`)
- Tap `...` at the top right > `View profile` to check how the username is displayed (currently it's 3-random name)
- Return to the chat view and tap `+ Add to contacts` at the top of the chat view
- Tap `...` at the top right > `View profile` to check how the username is displayed (ENS)
- Clear nickname field > Tap `Done` (name turns to 3-random again)


https://user-images.githubusercontent.com/67952253/118134234-fd259e00-b401-11eb-9be5-925892315337.mp4

**Comment by briansztamfater** [comment]
@qoqobolo Fixed both and should be also fixed the issue when closing / reopening the app

**Comment by qoqobolo** [comment]
@briansztamfater thank you! All three issues have been fixed, great!
But a few more problems were found :(
Please let me know if any of them are not PR-related and should be logged and fixed separately. Thank you for your patience.

### ISSUE 4: ENS names aren't resolved in the mention list if chat with ENS user was started by `Start new chat` button

**_Steps:_**
- `+` button > `Start new chat` > Start 1-1 chat with ENS-user (e.g. ditest)
- Type `@`

Screenshot 2021-05-14 at 09 29 35

### ISSUE 5: ENS names are displayed in different ways on different screens of the app
ENS is displayed with the `.stateofus.eth` domain in the chat view and user's profile and with `@` (without domain) in contacts and on the `Start new chat` screen if a user was added to contacts.

https://user-images.githubusercontent.com/67952253/118237461-a10d5900-b497-11eb-96e0-5e30d90a4504.mp4

### ISSUE 6: Can't use the search field on the Home screen to search for a chat with an ENS user if this chat was started using the `Start new chat` button
For chats that were started in other ways (from contacts or public chat, for instance) the search works fine.

https://user-images.githubusercontent.com/67952253/118241063-006d6800-b49c-11eb-903d-f42dc04d7651.mp4

### ISSUE 7: ENS isn't shown in `Group info` if 1-1 chat with this ENS user was started by `Start new chat` button and then he was added to contacts and to group chat

**_Steps:_**
- Start new chat with ENS user using `Start new chat` button
- Tap `+ Add to contacts` on the top of the chat view
- Navigate to profile > Contacts > Add to contacts another ENS user
- Open Home screen > Create a group chat with both contacts
- Open group info

### ISSUE 8: ENS isn't shown in `Contacts` if the user was added to contacts from the chat view, which was started using the "Start new chat" button

**_Steps:_**
- Start new chat with ENS user using `Start new chat` button
- Tap `+ Add to contacts` on the top of the chat view
- Navigate to `Profile` > `Contacts`
 
https://user-images.githubusercontent.com/67952253/118243224-7a9eec00-b49e-11eb-8a68-697e4e0afcbe.mp4

### ISSUE 9: Can send ETH directly to ENS name in 1-1 chat if 1-1 chat with this ENS user was started by `Start new chat` button
Commands in 1-1 chat work fine if chat was started in a different way. 

**_Steps:_**
- Start new chat with ENS user using `Start new chat` button
- Open transaction dialog in 1-1 chat (`+` button at the bottom left)
- Tap `Send transaction`, enter valid amount of ETH
- Tap `Next`
**Expected behavior:** "Sign with password/Keycard" bottom sheet is opened, no address request is sent
**Actual behavior:** "Address requested" message is sent

Screenshot 2021-05-14 at 10 39 35

**Comment by briansztamfater** [comment]
@qoqobolo Hey! No problem, PR is getting bigger than expected but I will check one by one if they are related to these changes.

**Comment by briansztamfater** [comment]
@qoqobolo New issues should be fixed now. Let me know how it goes :)

File: src/status_im/add_new/core.cljs [hunk 1]
```diff
@@ -33,21 +33,26 @@
...
-                                            :searching
-                                            (and (string/blank? new-identity) (not new-ens-name))
-                                            :empty
-                                            error
-                                            :error
-                                            :else
-                                            :valid)
-                          :error      error
-                          :ens-name   (resolver/ens-name-parse new-ens-name)})}
+      (merge {:db (as-> db $
```
Comment (flexsurfer) [inline src/status_im/add_new/core.cljs]: could you please elaborate on using `as->`. here ? thanks

File: src/status_im/chat/models/loading.cljs [hunk 2]
```diff
@@ -20,17 +20,26 @@
...
-                  [:start-profile-chat (get-in db [:multiaccount :public-key])]]}))
+        chats (merge old-chats chats)
+        chats-v (vals chats)
+        ens-names (get db :contacts/ens-names)]
+    (fx/merge cofx
+              {:db (assoc db :chats chats
+                          :chats/loading? false)
+               :dispatch-n [[:chat/start-timeline-chat]
+                            [:start-profile-chat (get-in db [:multiaccount :public-key])]]}
+              (doseq [chat chats-v]
```
Comment (flexsurfer) [inline src/status_im/chat/models/loading.cljs]: this is somehting really wrong, i don't understand this

File: src/status_im/contact/db.cljs [hunk 3]
```diff
@@ -116,6 +116,10 @@
   ([db public-key]
    (active? (get-in db [:contacts/contacts public-key]))))
 
+(defn add-ens-name
+  [contact ens-name]
+  (if ens-name (assoc-in contact [:name] ens-name) contact))
```
Comment (flexsurfer) [inline src/status_im/contact/db.cljs]: why `assoc-in` ?

File: src/status_im/subs.cljs [hunk 4]
```diff
@@ -1192,11 +1193,14 @@
...
-   (let [contacts-with-one-to-one (if (= chat-type constants/one-to-one-chat-type)
+ :<- [:contacts/ens-names]
+ (fn [[{:keys [chat-id users chat-type]} contacts blocked {:keys [name preferred-name public-key]} ens-names]]
+   (let [ens-name? (when ens-names (get ens-names chat-id))
+         contacts-with-one-to-one (if (= chat-type constants/one-to-one-chat-type)
                                     (assoc contacts chat-id (get contacts chat-id (-> chat-id
                                                                                       contact.db/public-key->new-contact
-                                                                                      contact.db/enrich-contact)))
+                                                                                      contact.db/enrich-contact
+                                                                                      (contact.db/add-ens-name ens-name?))))
```
Comment (flexsurfer) [inline src/status_im/subs.cljs]: you can just use `(get ens-names chat-id)` directly here

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/chat/models/loading.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/chat/models/loading.cljs]: we cant fx/merge doseq

Comment (flexsurfer) [reply src/status_im/chat/models/loading.cljs]: why do we want to doseq all chats? i believe we need to verify only one entered name ?

Comment (briansztamfater) [reply src/status_im/chat/models/loading.cljs]: When closing / opening the app the ens-names on chats are lost so the main idea was to check ens-names and verify them again for each chat that was started through ENS search. I'm open to other approaches as this is not one I'm proud of.

Comment (flexsurfer) [reply src/status_im/chat/models/loading.cljs]: > When closing / opening the app the ens-names on chats are lost 

hm why are they lost ?

File: src/status_im/add_new/core.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/add_new/core.cljs]: Was to add an if statement inside the macro, but I'm pretty sure there are better ways to do it

Comment (flexsurfer) [reply src/status_im/add_new/core.cljs]: `cond->` ?

File: src/status_im/chat/models/loading.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/chat/models/loading.cljs]: If user is not saved to contacts after initializing a chat, ens name is lost. I'm trying to figure out why that's happening, but maybe we could investigate that in another issue and simplify this PR, because that is happening right now also when starting a chat with an ENS user from the search bar.

File: src/status_im/add_new/core.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/add_new/core.cljs]: That looks way cleaner :)

**Comment by briansztamfater** [comment]
@qoqobolo @flexsurfer  Hey so I just simplified this PR as I think I over engineered at first. There's one issue that I detected but maybe would be a good idea to cover it in another issue, and it is when you don't add ENS user to contacts, the ENS name is lost after closing / opening the app. But that's already happenning when starting a chat with an ENS user from the search bar, so I would file a new issue and investigate there. Let me know what do you think.

**Comment by qoqobolo** [comment]
@briansztamfater okay, I'll log a new issue with that case.

As for the previous problems - they are all fixed. Thanks for your great work!
PR is ready to be merged.

**Review by flexsurfer — APPROVED** [review]
