### PR TITLE
[#21060] Photo preview in mentions

### LINKED ISSUE #21060: No photo preview in mention notifications from Group chat/ communities
# Bug Report

### Reproduction
1. Open a group chat or community in User 1
2. Mention a User 2 in a message and include a photo in the same message
3. Login as User 2 and open Activity center
4. Observe the notification received by the mentioned User 2

#### Expected behavior
The notification should display a preview of the photo included in the mention

#### Actual behavior
The notification does not display a photo preview, only the text of the mention

https://github.com/user-attachments/assets/92fc047a-8f90-48aa-baa9-1b3804453935

### Additional Information
- Status version: release
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21060

### Summary

This PR adds support to display image previews in the activity center for mentions.

Demo:

image

#### Platforms

- Android
- iOS

 #### Areas that maybe impacted

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Create a group chat and tag the user `A` in a message containing photos
- Log in as `A` and check the activity center, the notifications should contain the photos shown.

status: ready

### CODE REVIEW

File: src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs [hunk 1]
```diff
@@ -9,25 +9,45 @@
...
-          (map-indexed (fn [index {:keys [type literal destination]}]
-                         ^{:key index}
-                         (case type
-                           "mention" [quo/text
-                                      {:style style/mention-text
-                                       :size  :paragraph-1}
-                                      (str "@" (rf/sub [:messages/resolve-mention literal]))]
-                           "link"    destination
-                           literal))
-                       parsed-text-children))))
```
Comment (ulisesmac) [inline src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs:30]: Refactored this component.

- `map-indexed` is not needed since we are already using `into`

- The metadata added is probably doing nothing since it's wrapping a `case` expression, to make it work we should use `with-meta`, but `literal` is a string, and it doesn't support `with-meta` so the code is almost doing nothing it has been simplified and split into smaller functions

File: src/status_im/contexts/shell/activity_center/view.cljs [hunk 2]
```diff
@@ -24,7 +24,7 @@
     [utils.re-frame :as rf]))
 
 (defn notification-component
-  [{:keys [type] :as notification} index]
+  [{notification-type :type :as notification} index]
   (let [extra-fn (rn/use-callback
```
Comment (ulisesmac) [inline src/status_im/contexts/shell/activity_center/view.cljs:28]: Modified the destructuring to avoid shadowing `cljs.core/type`

File: src/status_im/contexts/shell/activity_center/view.cljs [hunk 3]
```diff
@@ -36,23 +36,23 @@
     ;; AC after pressing the bell icon can be high.
```
Comment (ilmotta) [inline src/status_im/contexts/shell/activity_center/view.cljs]: @ulisesmac, since are doing some changes in this function, I think we can remove this entire comment because it refers to a call way down below to `rn/delay-render`. But I'd say the comment is redundant because the function `rn/delay-render` is pretty clear already.

**Review by ilmotta — APPROVED** [review]
Code looks better, and nice little feature 👍🏼

**Comment by mariia-skrypnyk** [comment]
Hi @ulisesmac !

Thanks for your PR. Really nice feature!
I checked on both platforms and only have one question:

If a user receives notification and goes straight to AC he sees how images appears inside of a received notification.
In my example I have 6 images sent to me.
*on my video I am already in AC but this loading also could be catched if you receive notification and open AC in 1-2 sec after.

https://github.com/user-attachments/assets/f915af21-1fbf-4d0b-b91a-3d47d30ebdf6

From user perspective I am waiting that notification will contain all content that was sent to me.
What do you think?

cc @ilmotta

File: src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs [hunk 4]
```diff
@@ -9,25 +9,45 @@
...
+     {:style style/mention-text
+      :size  :paragraph-1}
+     (str "@" mention)]))
+
+(defn- parsed-text->hiccup
+  [{:keys [literal destination] message-type :type}]
+  (case message-type
+    "mention" [mention-text literal]
+    "link"    destination
+    literal))
```
Comment (seanstrom) [inline src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs:25]: I would it be possible/advisable to convert message-type into a keyword when we decode the message?

**Review by seanstrom — APPROVED** [review]
A little late to this review, but thought I'd leave a small note/comment. Thank you for the PR ✅

File: src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs:25]: I think it could be, but we could break existing usages of it. I preferred to keep it as it was.

It isn't normal for us because we usually use keywords, but in this case it isn't too noisy IMO

Comment (seanstrom) [reply src/status_im/contexts/shell/activity_center/notification/mentions/view.cljs:25]: yup yup makes sense 👍

**Comment by ilmotta** [comment]
> If a user receives notification and goes straight to AC he sees how images appears inside of a received notification. In my example I have 6 images sent to me. *on my video I am already in AC but this loading also could be catched if you receive notification and open AC in 1-2 sec after.

@mariia-skrypnyk @ulisesmac, From the video, I'm assuming the problem is that images are visibly being loaded in stages and the user can notice that? Does this problem always happen when the AC is opened or does it happen only when the AC is already open and a new notification with images arrive? If the former, then there's a minor bug in our implementation, but if the latter then I would say it's an acceptable UX for now because the majority of the time users will receive notifications when the AC is closed.

File: src/status_im/contexts/shell/activity_center/view.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/status_im/contexts/shell/activity_center/view.cljs]: Removed :+1:

**Comment by mariia-skrypnyk** [comment]
Thanks @ilmotta for taking a look into it.

It happens in both case: if you open AC right after notification is received and if you are already in AC.

https://github.com/user-attachments/assets/e4592b4f-d2c7-48cb-8b59-ec600f20f65d

I do not think that it is a common situation when user will go to AC so quickly but anyway wanted to highlight such behaviour.

**Comment by mariia-skrypnyk** [comment]
@ulisesmac think you can merge your PR in any case.
If image loading will be defined as a follow up I will create it separately.
Thanks.

**Comment by ilmotta** [comment]
> @ulisesmac think you can merge your PR in any case. If image loading will be defined as a follow up I will create it separately. Thanks.

Thank you @mariia-skrypnyk, well spotted UX issue 👍🏼

**Comment by ulisesmac** [comment]
> > @ulisesmac think you can merge your PR in any case. If image loading will be defined as a follow up I will create it separately. Thanks.
> 
> Thank you @mariia-skrypnyk, well spotted UX issue 👍🏼 

I'm not sure if we know (from status-go) if a message with images is being delivered or it has been completely delivered.

Additionally, AFAIK we don't have a loading state for these notifications 🤔

So I don't know if we can actually solve it.

**Comment by ilmotta** [comment]
@ulisesmac @mariia-skrypnyk I tried to reproduce this loading problem but I couldn't on an iPhone 14. See video below, everything is smooth.

Looks like an edge case we can log in a separate issue for the sake of documentation, but ignore it (not solve it).

https://github.com/user-attachments/assets/a80f0121-fc35-4084-b2b8-ede78bd6be07

----

> Additionally, AFAIK we don't have a loading state for these notifications 🤔

I think that's correct, when notifications arrive from a signal they are complete and there's nothing else to load or wait to be loaded.

**Comment by ulisesmac** [comment]
> @ulisesmac @mariia-skrypnyk I tried to reproduce this loading problem but I couldn't on an iPhone 14. See video below, everything is smooth.
> 
> Looks like an edge case we can log in a separate issue for the sake of documentation, but ignore it (not solve it).
> RPReplay_Final1725472632.mp4
> 
> > Additionally, AFAIK we don't have a loading state for these notifications 🤔
> 
> I think that's correct, when notifications arrive from a signal they are complete and there's nothing else to load or wait to be loaded.

@ilmotta  

The problem appears only when the message is being delivered.

It's due to the app being on the process of receiving the images. So to replicate it you should receive a message with images and open the AC ASAP, if the message has been already received and we open the AC, it won't happen again.

**Comment by ilmotta** [comment]
> It's due to the app being on the process of receiving the images. So to replicate it you should receive a message with images and open the AC ASAP, if the message has been already received and we open the AC, it won't happen again.

In that case I think it's not worth trying to solve this problem because we can safely assume most of the time users will be outside the AC, using other features, so by the time they open the AC everything is probably already loaded in memory.

Does that sound reasonable to you @mariia-skrypnyk?

**Comment by mariia-skrypnyk** [comment]
> Does that sound reasonable to you @mariia-skrypnyk?

Absolutely!
