### PR TITLE
Various fixes on messaging

### LINKED ISSUE #16894: Misaligned contact icon - comment here
related to: https://github.com/status-im/status-mobile/issues/16867

figma review comment - https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3817-74882&mode=design&t=7oGIJsujWlrIaN19-4

### LINKED ISSUE #16904: Add emojis icon color is not aligned - comment here

### LINKED ISSUE #16908: Name in reply message is too small - comment here

### LINKED ISSUE #16927: Composer > Reply - username is smaller than in design - comment here

### LINKED ISSUE #16928: Composer > `Type something` is too dark - comment here

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #16894 

Alignment of contact icon in the author component was aligned to baseline instead of being center-aligned.
Check a message of a contact and see the message author row, the contact icon should now be center aligned with the author name (and public key was similarly misaligned to the baseline).

Fixes: #16904

Color of add emojii was off
When there's a post with an emojii, the button to add an emojii was of the wrong color.

Fixes: #16908
Fixes: #16927

Reply author name size was wrong in both composer and message

Fixes: #16928

Color of input placeholder in chat was not as per designs

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

File: src/quo2/components/reactions/reaction.cljs [hunk 1]
```diff
@@ -18,7 +18,7 @@
       {:size  20
        :color (if dark?
```
Comment (J-Son89) [inline src/quo2/components/reactions/reaction.cljs]: We should get theme from the theme context provider in these components - is it possible to add as these changes?

Ícaros docs pr should describe how it works or you can check the button component

Comment (J-Son89) [reply src/quo2/components/reactions/reaction.cljs]: Same for other uses of theme and colors/theme-color function.

colors/theme-color requires a 3rd parameter of 'theme'. While we migrate everything to this approach this param will be optional but eventually it will be mandatory to pass.

Comment (cammellos) [reply src/quo2/components/reactions/reaction.cljs]: Could you please check if that's the correct way to do it?
I have only done `add-reaction` since `reaction` is not using theme looks like, not sure whether we should do it even if it doesn't, let me know what's best.
thanks

Comment (J-Son89) [reply src/quo2/components/reactions/reaction.cljs]: Yep looks good!

Also theme-colors is used in src/status_im2/contexts/chat/composer/view.cljs so should probably do similar there.

Comment (cammellos) [reply src/quo2/components/reactions/reaction.cljs]: mmh, is a bit unhappy about it if I try the same (invalid hook call), would it be ok if I leave it as it is for this PR, as I think it might require a bit more shuffling around? Otherwise happy to do it

Comment (J-Son89) [reply src/quo2/components/reactions/reaction.cljs]: Yeah of course, leave if it's causing hassle. We'll eventually get around to these files and make the adjustments for these. 👍

**Comment by cammellos** [comment]
@Francesca-G could you please have a look at the issues above? they should be fixed in the  current build.
(size of emojii boxes is still off in this PR, will be addressed in a separate PR).
Thank you!

**Review by Francesca-G — COMMENTED** [review]
Here's the [design review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3679%3A38431&mode=design&t=cN7t8rDQdERrKPEM-1), please refer to review 2 :)

**Comment by cammellos** [comment]
Thanks for the review @Francesca-G I have changed the placeholder text and create separate issues for the spacing between composer and message & for the icons color, and @J-Son89 is looking into it. It looks like when blur is applied to the composer the color of the icons (and also of the placeholder) changes, but it should be set to the correct values.
Could you please check if the placeholder text is ok now? If that's ok I would merge this and address the other issues separately.

Thank you!

**Comment by Francesca-G** [comment]
@cammellos it looks correct :)
Thank you!

**Review by Francesca-G — APPROVED** [review]
