### PR TITLE
Communities - Show modal title and community context tag

### LINKED ISSUE #18025: Communities: show name of community when joining a community
As a user joining a community
I want to see the community name
So that I don't mistakenly join the wrong community

### Scope

- Community name header (Request to join and name of community)

### Designs

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-287058&mode=design&t=SLL48C9SGaqsXbS9-0

Depends on: #17969

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/18025

### Summary

This is a quick PR to make the account selection screen more in line with Figma, but more importantly to show the community context tag and a screen title.

The feature is behind a feature toggle , disabled in `develop`.

#### Demo

There's a known bug where the background of the context tag extends up to the available width of the parent container. This PR is not fixing that.

[Screen_recording_20231205_124555.webm](https://github.com/status-im/status-mobile/assets/46027/7e7c8244-3ca1-4c9b-a88a-b6503d4c98af)

#### Areas that may be impacted

None because the feature toggle is disabled in `develop`. e2e tests will be run as usual.

### Steps to test

1. Enable toggle `status-im2.config/community-accounts-selection-enabled?`
2. Send a community invite to someone and press "Request to join" in the community overview screen.

status: ready

### CODE REVIEW

**Review by yqrashawn — APPROVED** [review]
LGTM

**Review by ajayesivan — COMMENTED** [review]
Screenshot 2023-12-06 at 16 21 11

Is the full width of community context tag expected?

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 1]
```diff
@@ -185,7 +185,7 @@
          [quo/button
           {:on-press
            (if config/community-accounts-selection-enabled?
-             #(rf/dispatch [:open-modal :community-account-selection community])
+             #(rf/dispatch [:open-modal :community-account-selection {:community-id id}])
              #(rf/dispatch [:open-modal :community-requests-to-join community]))
```
Comment (FFFra) [inline src/status_im2/contexts/communities/overview/view.cljs:189]: Should we pass the argument as line above?
instead of `comunity` we use `{:community-id id}`?

**Review by FFFra — APPROVED** [review]
LGTM! Just left a comment.

Great job1

**Comment by ilmotta** [comment]
> There's a known bug where the background of the context tag extends up to the available width of the parent container. This PR is not fixing that.

I mentioned this in the PR description @ajayesivan:

> There's a known bug where the background of the context tag extends up to the available width of the parent container. This PR is not fixing that.

I've seen this problem somewhere, it's not right.

**Comment by ajayesivan** [comment]
Thank you @ilmotta. I missed that part 🙃

**Review by ajayesivan — APPROVED** [review]

File: src/status_im2/contexts/communities/overview/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/overview/view.cljs:189]: The `community` map is huge, even containing encoded images. We should avoid passing it around if possible because the data (screen params) is going to be stored in the app db and used by a subscription and the view too. This puts more stress on re-frame and Reagent to compute if something needs to rendered. So here I changed the code to pass the community ID to the screen params so that the view layer can get the community from a subscription.

**Comment by ilmotta** [comment]
@status-im/mobile-qa, I merged this PR because all its code runs behind a disabled feature toggle (we enable only during development). For the next couple weeks we will probably continue to rely mostly on e2e tests and our manual checks to make sure we respect the feature toggle and not cause any regression. The flows for joining communities shouldn't be affected at all.

In the cases where we do touch code outside the toggle's umbrella we will definitely ask for your reviews :)
