### PR TITLE
Fix for "Pending requests" label not being shown in light mode

### LINKED ISSUE #15659: No "pending requests" placeholder is shown on contacts tab fro Android in white mode
# Bug Report

## Problem 

IMAGE 2023-04-14 17:11:35

### Reproduction

1) Open Status
2) Send/ receive CR

### Additional Information

- Status version: nightly 14/04/23
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
Fixes #15659 

#### Platforms

- Android
- iOS

##### Functional

- contacts

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im2/contexts/chat/home/contact_request/view.cljs [hunk 1]
```diff
@@ -45,8 +45,12 @@
    [rn/view {:style (style/contact-requests-icon)}
     [quo/icon :i/pending-user {:color (colors/theme-colors colors/neutral-50 colors/neutral-40)}]]
    [rn/view {:style {:margin-left 8}}
-    [rn/text {:weight :semi-bold} (i18n/label :t/pending-requests)]
-    [rn/text
+    [quo/text
+     {:size   :paragraph-1
+      :weight :semi-bold
+      :style  {:color (colors/theme-colors colors/black colors/white)}}
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/home/contact_request/view.cljs]: `colors/neutral-100`

Comment (Parveshdhull) [reply src/status_im2/contexts/chat/home/contact_request/view.cljs]: not sure why colors/black is in colors file, there is no such color in [foundations file](https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?node-id=3056-75&t=zFgYafIsWDWMpQjJ-0) for app theme use case

**Comment by churik** [comment]
Can be merged without e2e, looks great to me.

**Devices:**
- IPhone 12 Mini (IOS 16)
- Xiaomi Mi Note 9 Pro (Android 10)
