### PR TITLE
fix: avatar alignment

### LINKED ISSUE #18827: The avatar is on the wrong place in the opened 1-1
### Steps:
1. Open 1-1 with messages
2. Scroll a bit to the down
3. Check avatar

### Actual result:
The avatar is located above the display name
image

### Expected result:
The avatar is located on the same line as a display name
image

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8451-543358&mode=design&t=i0Ojj0uIoJWoDvQP-0

### ENV:
Nightly [14 Feb 2024]

### PR DESCRIPTION
**Pull request by jo-mut**
Fixes https://github.com/status-im/status-mobile/issues/18827

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Handles the limit event when creating a new group chat
- Fixes avatar/username alignment
- Adds animation for avatar/username when scrolling up ([ref](https://discord.com/channels/624634427930312714/928625369542713396/1213089049103835259))

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats

### Steps to test

- Open Status
- Go to chat tab
- Start 1:1 chat with a contact
- When you have enough content more than the screen, scroll to the bottom
- Observe animation and alignment for avatar/username

status: ready 

Avatar Alignment Fix

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 1]
```diff
@@ -133,6 +132,30 @@
...
+        left (reanimated/interpolate distance-from-list-top
+                                     [0 messages.constants/header-container-top-margin]
+                                     [4 50]
+                                     messages.constants/default-extrapolation-option)]
+    [reanimated/view
+     {:style (style/user-name top left)}
+     [rn/view
+      {:style {:align-items    :center
+               :flex-direction :row
+               :margin-top     (if group-chat 94 52)}}
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Please move this to styles file

**Review by Parveshdhull — APPROVED** [review]
Thank you for implementing this animation.

- Avatar is overlapping Name
- Probably we also want to decrease/animate gap between pins banner and top bar

Please request design review before merging.


https://github.com/status-im/status-mobile/assets/17097240/94aac7c9-8b24-490b-b985-d1be05f2a531

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 2]
```diff
@@ -211,16 +232,12 @@
...
-       {:style {:flex-direction :row
-                :margin-top     (if group-chat 94 52)}}
-       [quo/text
-        {:weight          :semi-bold
-         :size            :heading-1
-         :style           {:flex-shrink 1}
-         :number-of-lines 1}
-        display-name]
-       [contact-icon contact theme]]
+      [:f> f-username
```
Comment (ajayesivan) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Do we still need `:f>`?

> From [ui-guidelines](https://github.com/status-im/status-mobile/blob/develop/doc/ui-guidelines.md)
> `:f>` not needed anymore, all components are functional by default

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 3]
```diff
@@ -133,6 +132,28 @@
        :profile-picture profile-picture
        :size            :big}]]))
 
+(defn f-username
```
Comment (ajayesivan) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Since all components are functional by default, the `f-` naming convention doesn't make sense

cc: @flexsurfer

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs]: yes thanks

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs]: no `:f>` is not needed anymore

**Comment by mariia-skrypnyk** [comment]
Hi @BalogunofAfrica!

Thanks for your implementation!
I also saw avatar overlapping during animation.
Now
Screenshot 2024-03-21 at 13 09 51

Design
Screenshot 2024-03-21 at 12 37 16

So will adress it to the design team.

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica thanks for initiative to disable current animation in a Group Chats.
Please, make sure you will check these points mentioned [here.](https://discord.com/channels/624634427930312714/1213089049103835259/1220345779584106536)
You just need to tag me in case PR will be ready to test again. 🙏

**Review by ajayesivan — APPROVED** [review]

**Comment by BalogunofAfrica** [comment]
Hi @Parveshdhull @mariia-skrypnyk I have updated the PR to also animate the gaps between the pins.

But I did notice an issue that was introduced from Reanimated 3.6.0, I have reported it here: https://github.com/status-im/status-mobile/issues/19387.

Animating gaps/margins causes the animation to be janky.

**Comment by mariia-skrypnyk** [comment]
Hi @BalogunofAfrica !

I've checked animation.
iOS looks good for me.
Android jumps.

https://github.com/status-im/status-mobile/assets/147824399/3cd1887a-a134-4653-ac8c-c644bb7f674c

I think we should send it to the design review. Probably Android should be analysed how to fix in future.
@Francesca-G please, look how it works for you.

**Review by Francesca-G — COMMENTED** [review]
[Here](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7/Review-Messages-%2F-Mobile?type=design&node-id=248%3A7228&mode=design&t=SrliZ3ctILaI9uYl-1) is the review, I also have a recording to better understand the comments:


https://github.com/status-im/status-mobile/assets/122543089/624419c6-4b8f-4f6d-923a-3a2478320f91

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica please tag me when I can retest 🙏

**Comment by BalogunofAfrica** [comment]
> @BalogunofAfrica please tag me when I can retest 🙏

Hi @mariia-skrypnyk You can re test. Android Jank is related to https://github.com/status-im/status-mobile/issues/19387.

**Comment by BalogunofAfrica** [comment]
Hi @Francesca-G, I have addressed all comments save the dot size.

For that, the identicon and dot are generated as one single image, which is what we can animate to scale. 

We can not animate the dot separately.

**Comment by Francesca-G** [comment]
> Hi @Francesca-G, I have addressed all comments save the dot size.
> 
> For that, the identicon and dot are generated as one single image, which is what we can animate to scale.
> 
> We can not animate the dot separately.

can we create a separate issue to find a solution to this? 🙏

**Comment by mohsen-ghafouri** [comment]
we already have a similar open issue for indicator size https://github.com/status-im/status-mobile/issues/18257

**Comment by BalogunofAfrica** [comment]
> we already have a similar open issue for indicator size #18257

Thanks @mohsen-ghafouri  🙏

cc: @Francesca-G

**Comment by BalogunofAfrica** [comment]
@mariia-skrypnyk Can this be merged?

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica yes, please!
