### PR TITLE
fix(wallet)_: token supported networks

### LINKED ISSUE #20988: Bridging of assets is blocked unless user has a positive balance of this asset ("Network is not available")
### Preconditions:
Recover user that has an asset on  network 1 only (current asset should not be ETH, DAI, or SNT)

### Steps:
1. Recover user with assets that are supported on 3 networks (Example: USDC)
2. Go to the routes generation page
3.Attempt to bridge assets from the network where the user holds assets to another network.

### Actual result:
**On send page:** "Network is not available" is shown in the TO section for the receiver, even though asset (a token available on all networks) is selected for sending.

https://github.com/user-attachments/assets/e8567210-8210-4c4a-9fd9-455345f933b2

**On Bridge Page:** The user cannot select networks on which they do not hold the asset (e.g., if the user has USDC on Optimism, they cannot select Arbitrum or Mainnet for bridging).

Image

### Expected result:
The app should allow the user to select networks where the asset is supported, even if the user does not have an available balance on those networks.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16548840/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #20988

### Summary

This PR fixes the networks/chains supported by the token based on the token list fetched from status-go instead of relying on the `balance-per-chain` map as status-go returns balance for chains only if there is a positive balance.

### Platforms

- Android
- iOS

#### Functional

- wallet/transactions

##### Prerequisites: A wallet account with a token balance on one network 

- Open Status
- Navigate to `Wallet > Account > Bridge`
- Verify the supported networks by each token is displayed below each token
- Upon selecting a token, verify the token supported networks are selectable even if there is no balance on that network/chain
- Navigate to `Wallet > Account > Send`
- Verify the tokens are displayed correctly with networks supported by the token
- Navigate to the routes generation page and verify `Not available` text is not shown on the receiver side
- Verify the transaction can be performed

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 1]
```diff
@@ -511,3 +513,19 @@
...
+  [{:keys [balances-per-chain token-supported-chains]}]
+  (reduce
+   (fn [result chain-id]
+     (if (contains? result chain-id)
+       result
+       (assoc result
+              chain-id
+              {:chain-id    chain-id
+               :raw-balance (money/->bignumber 0)
+               :balance     "0"})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/utils.cljs]: nit: since this map is constant, I'd create it outside of this `reduce`, in a `let`.

File: src/status_im/contexts/wallet/common/utils/networks.cljs [hunk 2]
```diff
@@ -62,13 +62,13 @@
...
 (defn network-list
-  [{:keys [balances-per-chain]} networks]
+  [chain-ids networks]
   (into #{}
         (mapv (fn [chain-id]
                 (first (filter #(or (= (:chain-id %) chain-id)
                                     (= (:related-chain-id %) chain-id))
                                networks)))
-              (keys balances-per-chain))))
+              chain-ids)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/utils/networks.cljs]: I know this code already existed, but there's a big room for improvement, for example: `first + filter` -> `some` and using the transducer syntax for `into` or just use `(set)` instead of `(into #{})`

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -390,18 +390,21 @@
                  receiver-networks disabled-from-chain-ids
                  from-locked-amounts bridge-to-chain-id]
           :or   {token updated-token}} (get-in db [:wallet :ui :send])
+         bridge-tx? (= tx-type :tx/bridge)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs]: :+1:

File: src/status_im/contexts/wallet/swap/utils.cljs [hunk 4]
```diff
@@ -59,23 +59,27 @@
...
   [{:keys [wallet account test-networks-enabled? token-symbol]}]
-  (let [networks (-> (get-in wallet [:networks (if test-networks-enabled? :test :prod)])
-                     (network-utils/sorted-networks-with-details))
-        token    (->> account
-                      :tokens
-                      (filter #(= token-symbol (:symbol %)))
-                      first)]
-    (assoc token :networks (network-utils/network-list token networks))))
+  (let [networks         (-> (get-in wallet [:networks (if test-networks-enabled? :test :prod)])
+                             (network-utils/sorted-networks-with-details))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/swap/utils.cljs]: nit: We are using `->` for only one step:

```clojure
(-> (get-in wallet [])
    (do-something)
```

Better to extract `wallet`, since threading macros of only one step do not have a big benefit:

```clojure
(-> wallet
    (get-in [])
    (do-something)
```
```

File: src/status_im/subs/wallet/wallet.cljs [hunk 5]
```diff
@@ -443,27 +451,31 @@
...
-                                                           chain-ids
-                                                           (filter #(some #{(:chain-id %)} chain-ids)))
-                                      :available-balance (utils/calculate-total-token-balance token)
-                                      :total-balance     (utils/calculate-total-token-balance
-                                                          token
-                                                          chain-ids))))
-                            (filter (fn [{:keys [networks]}]
-                                      (pos? (count networks))))
-                            (remove #(when hide-token-fn (hide-token-fn constants/swap-tokens-my %))))
+         tokens        (->>
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/wallet.cljs]: the usual Clojure code style for `->>` is putting the threaded var next to `->>`:

```clojure
;; Do:
(->> a
     (f)
     (g))
;; Don't:
(->> 
  a
  (f)
  (g))
```

File: src/status_im/subs/wallet/wallet.cljs [hunk 6]
```diff
@@ -443,27 +451,31 @@
...
+                                                                networks)
+                                                        chain-ids
+                                                        (filter #(some #{(:chain-id %)} chain-ids)))
+                                   :available-balance (utils/calculate-total-token-balance token)
+                                   :total-balance     (utils/calculate-total-token-balance
+                                                       token
+                                                       chain-ids))))
+                         (filter (fn [{:keys [networks]}]
+                                   (pos? (count networks))))
+                         (remove #(when hide-token-fn (hide-token-fn constants/swap-tokens-my %))))
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/wallet.cljs]: We can save another iteration by joining this `filter` + `remove` into a single one. (actually we can even join the previous `map` by using `keep`, but it's highly probable that the readability will be worse).

**Review by ulisesmac — COMMENTED** [review]
Hi @smohamedjavid thanks for you PR!

I added some minor comments related to the code.

**Review by clauxx — COMMENTED** [review]
hey @smohamedjavid, I noticed this PR adds changes in similar places as [this one](https://github.com/status-im/status-mobile/pull/21403), just as an FYI. 

Also, wondering if it's possible to isolate the changes in one place only, for instance: when we get the token data from status-go, can we update `balances-per-chain` to include the missing chains? I may be missing context here though, just wondering if the other changes are necessary.

**Comment by smohamedjavid** [comment]
> hey @smohamedjavid, I noticed this PR adds changes in similar places as [this one](https://github.com/status-im/status-mobile/pull/21403), just as an FYI.

@clauxx - thanks for the heads up 👍  I guess I missed the context. I was under the impression that we need to display the supported networks below each token as we used to display (depending on the balance-per-chain key). I guess I will change it. Please merge your PR and I will make changes on top of it.

> Also, wondering if it's possible to isolate the changes in one place only, for instance: when we get the token data from status-go, can we update `balances-per-chain` to include the missing chains? I may be missing context here though, just wondering if the other changes are necessary.

That was my first thought too. I was under the impression that the status-go returns the balance even if it's zero in supported chains for all tokens, but it's different for non-default tokens (`ETH SNT STT DAI` are default tokens). I was inclined to status-go, but I don't want to introduce any bugs close to release.

I will quickly add the missing chain while we save it to the app-db. I need to ensure the token list (as we depend on it for supported chains for each token) is fetched before we fetch the tokens for each account so that we can add any missing chains in balance-per-chain. I will make a quick update.

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 7]
```diff
@@ -494,10 +494,12 @@
     (sort-by (juxt :symbol priority) tokens)))
 
 (defn tokens-with-balance
-  [tokens networks chain-ids]
+  [tokens networks token-supported-chains chain-ids]
```
Comment (vkjr) [inline src/status_im/contexts/wallet/common/utils.cljs]: When I read name `token-supported-chains` my brain splits it like "[token-supported] [chains]" which is quite confusing because I can't figure out what are chains that are supported by tokens :)
I'd suggest to rename all similar variables, keywords and functions (17 entries) to make them easier to understand:
'token-supported-chains' -> 'chains-supported-by-token'
'token-supported-chains-by-symbol' -> 'supported-chains-by-token-symbol'
Wdyt?

File: src/status_im/contexts/wallet/data_store.cljs [hunk 8]
```diff
@@ -72,11 +72,32 @@
...
+  "Adds any missing chain balance (0) to the balance-per-chain map based on token supported chains as
+   status-go returns balance for that chain only if the balance is positive."
+  [balances-per-chain supported-chains]
+  (let [zero-balance-per-chain (fn [chain-id]
+                                 {:chain-id    chain-id
+                                  :raw-balance (money/->bignumber 0)
+                                  :balance     "0"})]
+    (reduce
+     (fn [result chain-id]
+       (if (contains? result chain-id)
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/data_store.cljs:85]: is `contains?` usage correct ? shouldn't it be `some` ?

File: src/status_im/contexts/wallet/tokens/events.cljs [hunk 9]
```diff
@@ -68,9 +78,10 @@
             :on-error   [:wallet.tokens/fetch-prices-failed]}]]
      :db (-> db
              (assoc-in [:wallet :tokens]
-                       {:sources    (:sources tokens)
-                        :by-address (-> tokens :by-address vals)
-                        :by-symbol  (-> tokens :by-symbol vals)})
+                       {:sources                    (:sources tokens)
+                        :supported-chains-by-symbol supported-chains-by-symbol
+                        :by-address                 (-> tokens :by-address vals)
+                        :by-symbol                  by-symbol-vals})
```
Comment (alwx) [inline src/status_im/contexts/wallet/tokens/events.cljs:86]: The only thing that confuses me a little is that we're saving`:supported-chains-by-symbol` inside a structure called `:tokens`
Maybe it'd be better for it all to be saved in `[:wallet :chains-by-symbol]` instead?

**Review by alwx — APPROVED** [review]

File: src/status_im/contexts/wallet/data_store.cljs (hunk 8 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/data_store.cljs:85]: Yep, it's correct as we need to check whether the key (chain-id) exists.

https://clojuredocs.org/clojure.core/contains_q

File: src/status_im/contexts/wallet/tokens/events.cljs (hunk 9 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/tokens/events.cljs:86]: Since we group the chains IDs (by symbol) depending on the tokens list, I felt placing that data under the `:wallet :tokens` seems reasonable.

File: src/status_im/contexts/wallet/events.cljs [hunk 10]
```diff
@@ -345,8 +348,7 @@
                            :Prod
                            data-store/rpc->network)
                      data)}]
-     {:fx [[:dispatch [:wallet.tokens/get-token-list]]]
-      :db (assoc-in db [:wallet :networks] network-data)})))
+     {:db (assoc-in db [:wallet :networks] network-data)})))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/events.cljs]: is there any kind of dependency between the `:wallet/get-ethereum-chains` and `:wallet.tokens/get-token-list` events? I would assume that the `:wallet/get-token-list` event was dispatched in `:wallet/get-ethereum-chains-success` due to that.

File: src/status_im/contexts/wallet/tokens/events.cljs (hunk 9 above)
Comment (clauxx) [inline src/status_im/contexts/wallet/tokens/events.cljs:86]: Not a change you introduced, but what's the point of grouping the tokens by _symbol_ and by _address_ (as a `map` of symbols/tokens and token data), if we end up dismissing that and use the vector of token data? I assume it was originally done to make extraction of token data easier/quicker, without having to go through the entire list of tokens. Here though, it seems like we are storing the tokens as a vector in the db three times, and it's not clear to me why. The token list is pretty large, so storing it 3 times seems excessive tbh.

There's also quite a bit of data here that we're fetching/storing, which I guess was added for swaps, but I'm not sure if this data ends up being used anywhere. Specifically, `:details-per-token`, `:prices-per-token`, `:market-values-per-token`.

cc: @status-im/wallet-mobile-devs (in case anyone knows the reason)

**Review by clauxx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid could you please resolve existing conflicts? thanx!

**Review by shivekkhurana — APPROVED** [review]

File: src/status_im/contexts/wallet/tokens/events.cljs [hunk 11]
```diff
@@ -20,38 +20,48 @@
...
+                                                           :tokens       tokens
+                                                           :chain-ids    chain-ids}))))
+                                           {:sources    []
+                                            :by-address {}
+                                            :by-symbol  {}}
+                                           data)
+        symbols                    (->> tokens
+                                        :by-symbol
+                                        keys
+                                        (remove utils.address/address?))
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/tokens/events.cljs]: We recently made a refactor on this here #21453, so make sure to include it when rebasing

File: src/status_im/contexts/wallet/events.cljs (hunk 10 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/events.cljs]: I found out there is a dependency (chain-ids based on testnet mode) on the success of the token-list event. I have reverted this change. It seems that the previous change in this PR worked as well because of the response times of both events -`get-ethereum-chains` (very quick) and `get-token-list` (takes a bit of time). Anyhow, this works as expected.

File: src/status_im/contexts/wallet/tokens/events.cljs (hunk 9 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/tokens/events.cljs:86]: I guess @alwx is the best person to answer.

**Comment by smohamedjavid** [comment]
> hi @smohamedjavid could you please resolve existing conflicts? thanx!

@VolodLytvynenko - Done 👍

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid thank you for PR. take a look at found issue:

## ISSUE 1: Network drawer shows networks with 0 balances

### Steps:
1. Restore user with assets on a specific network (excluding DAI, ETH, SNT).
2. Go to the wallet page.
3. Long tap the asset and tap "swap."

### Actual result:
The network drawer displays networks where the asset isn't present.

Example: I have Chainlink on Optimism only, but I see Mainnet and Arbitrum in the network selection drawer as well

https://github.com/user-attachments/assets/451e83eb-e0a0-4855-8e29-5330b046c1c4



### Expected result:
The drawer should only show networks where the selected asset exists. In case if user has assets only on one network, then current user should be navigated directly to the swap page. See on nightly

https://github.com/user-attachments/assets/c3c33577-c8a8-4522-8d58-4f58cfa42c6a

#### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Thanks for testing the PR 🙏 . The issue 1 should be fixed now. Please retest.

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: 'Not available' shown in TO section if token isn't available on selected network

### Steps:
1. Restore user with a token available on one or two networks. (However this token should be supported on the all networks. Example: ETH, DAI etc)
2. Go to the send flow.
3. Try to build a route.

### Actual result:
User can't build a bridge route on the send page for a network where the asset isn't available.

Example: In my case the user has DAI on the L1 network, but in the "send to" page, Optimism and Arbitrum are shown as 'Not available' in the TO section.

image

### Expected result:
The networks should be shown as available on send to page in case if user even does not have assets on current networks



### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - The issue 2 should be fixed now. Please retest. 🙏

**Comment by VolodLytvynenko** [comment]
@smohamedjavid Thank you for fixes. Unfortunatly one more place related to this issue is introduced after last commit, however can be considered as follow up

## PR_ISSUE 3: Token shown as 'Not available' in "edit preferences" drawer despite being supported


### Steps::
1. Restore user with a token available on one or two networks. (However this token should be supported on the all networks. Example: ETH, DAI etc)
2. Go to the send flow.
3. Try to build a route.
4. Tap "edit" button to enable "edit preferences" drawer

https://github.com/user-attachments/assets/56fb5350-1735-4269-ae4f-67179fb26c14


### Actual result:
The token is shown as 'Not available' in the "edit preferences" drawer, even though the token is supported on the selected networks.

image


### Expected result:
The token should be shown as supported in the "edit preferences" drawer if it is supported on those networks

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Issue 3 should be fixed now. Please retest. 🙏

**Comment by VolodLytvynenko** [comment]
Unfortunately can't understand the root cause of this issue. I will send you the user and the assets where this happens

## PR_ISSUE 4: 'Not available' still shown in TO section


### Actual result:
image


### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

File: src/status_im/contexts/wallet/tokens/events.cljs (hunk 9 above)
Comment (alwx) [reply src/status_im/contexts/wallet/tokens/events.cljs:86]: The original idea was to copy this logic from desktop :) It was part of a bigger issue and I assumed that it's better to do all of it at once.

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Issue 4 should be fixed now. Please retest 🙏

**Review by ulisesmac — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. No issues from my side. PR can be merged
