### PR TITLE
fix sending/requestion ETH from Wallet dapp #1414 

### LINKED ISSUE #1414: Transaction amount is lost when performing it via SEND option through Wallet [send]
*Type*: Bug

*Summary*: SEND command is not fully integrated with Wallet 

#### Actual behavior
error “Amount should be specified” is shown if send ether from wallet

### Reproduction

- Open Status
- Sync the app
- Request some ETH
- Add any contact to contact list ( i was using the other one I have on my device)
- Go to wallet
- click Open wallet
- enter any appropriate amount in SEND field and click SEND button
- select a contact from the contact list

### Additional Information
* Status version:  http://artifacts.status.im:8081/artifactory/pull-requests/im.status.ethereum-7eeb9c.apk
* Operating System: Android 6.0.1
* Video https://drive.google.com/open?id=0B7h1U1joPifRUW8xS1JkMEduY0U
#### Logs
[05-07-2017 logcat.txt](https://github.com/status-im/status-react/files/1124897/05-07-2017.logcat.txt)

### PR DESCRIPTION
**Pull request by rasom**
fix #1414

Also contains fix for view components that were subscribing on `:chat-properties` and didn't work properly after migration to new version of re-frame.

status: ready

### CODE REVIEW

File: src/status_im/chat/views/toolbar_content.cljs [hunk 1]
```diff
@@ -61,35 +61,33 @@
...
+  (letsubs [group-chat    [:chat :group-chat]
+            name          [:chat :name]
+            chat-id       [:chat :chat-id]
+            contacts      [:chat :contacts]
+            public?       [:chat :public?]
+            show-actions? [:chat-ui-props :show-actions?]
+            accounts      [:get :accounts]
+            contact       [:get-in [:contacts @chat-id]]
+            sync-state    [:get :sync-state]
+            creating?     [:get :creating-account?]]
```
Comment (jeluard) [inline src/status_im/chat/views/toolbar_content.cljs]: Later we should figure out if there are better options to subscribe many times.

Comment (flexsurfer) [inline src/status_im/chat/views/toolbar_content.cljs]: @jeluard could you elaborate what do you mean?

Comment (rasom) [inline src/status_im/chat/views/toolbar_content.cljs]: @flexuser we need subscription which will return map with with necessary elements of `chat`'s map. I will add it soon.

Comment (flexsurfer) [inline src/status_im/chat/views/toolbar_content.cljs]: oh ok, thanks

Comment (jeluard) [inline src/status_im/chat/views/toolbar_content.cljs]: Right! Plus it's considered [bad practise](https://github.com/Day8/re-frame/blob/master/docs/SubscriptionsCleanup.md#a-final-faq) by `re-frame` team.

Comment (rasom) [inline src/status_im/chat/views/toolbar_content.cljs]: eh, tbh we have discussed this maybe a year ago, I mean that "bad practise" thing. And decided to keep using `:get` and `:get-in`. I can't say that we had huge problems because of these subscriptions, in the end it is "not perfectly declarative" code against tons of similar subscriptions, I would choose first.

Comment (jeluard) [inline src/status_im/chat/views/toolbar_content.cljs]: Fine with me! As long as it's part of _our_ best practises.
