### PR TITLE
[Fix] Sorting of Chat list items

### LINKED ISSUE #15960: New chats/chats with new messages should be moved to the top of the chat list
# Bug Report

## Problem 
Currently, all new chats are added to the bottom of the chat list. The chat stays in the same position even if a new message arrives.

#### Expected behavior
New chats/chats with new messages are moved to the top of the chat list

#### Actual behavior
New chats are at the bottom of the list; as new messages are received, the position of the chat in the list does not change

https://github.com/status-im/status-mobile/assets/67952253/8464ed74-b6f4-4e77-84e0-32707ca213e3

### Reproduction

1. UserA adds UserB and UserC to contacts (1-1 chats are created automatically)
2. UserA creates group chats with UserB and UserC (group1, group2)
3. UserA opens the chat screen
4. UserB and UserC send messages to the chats

### Additional Information

- Status version: nightly 19/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15960

### Summary

This PR fixes/adds the sorting of chat list items to display the recent chat on the top.
Refer to #15960 for a detailed description of the bug.

#### Platforms

- Android
- iOS

#### Steps to test

- Have more than 3 chats (1-1 Chats, and Group Chats) on the chat list
- Receive messages from other users/groups
- Check if the recent chat moves to the top of the list

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/home/view.cljs [hunk 1]
```diff
@@ -22,11 +22,12 @@
...
-(defn filter-items-by-tab
+(defn filter-and-sort-items-by-tab
   [tab items]
-  (if (= tab :tab/groups)
-    (filter :group-chat items)
-    (filter :chat-id items)))
+  (let [key (if (= tab :tab/groups) :group-chat :chat-id)]
+    (->> items
+         (filter key)
+         (sort-by :timestamp >))))
```
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/home/view.cljs:30]: Are we sure all possible chat items have a `:timestamp` key that is not `nil`?

Comment (ajayesivan) [reply src/status_im2/contexts/chat/home/view.cljs:30]: If there is a possibility of having `nil` timestamps, I believe it would be appropriate to display those items last. In such cases, should we consider adding additional sorting parameters? If not necessary, I believe the current implementation should suffice.

**Review by ajayesivan — APPROVED** [review]

File: src/status_im2/contexts/chat/home/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/chat/home/view.cljs:30]: > Are we sure all possible chat items have a `:timestamp` key that is not nil?

@ibrkhalil - As far as I checked, there is no possibility of `nil` for `:timestamp`, even for newly accepted contact requests or joined groups.

**Comment by smohamedjavid** [comment]
@jakubgs - The iOS build fails due to storage issues. 
```
/Users/jenkins/workspace/status-mobile: No space left on device
```
Appreciate your help on this 😄 

#### EDIT: The builds work fine now.

File: src/status_im2/contexts/chat/home/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/home/view.cljs:30]: Nice, Thanks Mohamed!

**Review by ibrkhalil — APPROVED** [review]
🆗

**Review by flexsurfer — APPROVED** [review]

**Comment by VladimrLitvinenko** [comment]
Hi, @smohamedjavid thank you for PR. here are found issues:
## ISSUE 1: The 'pending' CR does not turn into the 'accepted' in the 1-1 chat

### Steps to reproduce:
1. User_A: Sends the contact request (CR) to User_B
2. User_B: Accept CR
3. Open 1-1 chat

### Actual result:
The 'pending' and 'accepted' statuses are shown
image

### Expected result:
Only the 'accepted' system message is shown in 1-1
image

**Comment by VolodLytvynenko** [comment]
@smohamedjavid sorry.  Ignore please If you have seen a reported issue in this PR. Already removed it. It looks like this issue is not related to this PR

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid . Thank you for the fixes. PR is ready to be merged
