### PR TITLE
fix: transaction fails when signed from auto-restored derived account after seed phrase recovery with biometric authentication enabled

### LINKED ISSUE #22000: Transaction fails when signed from auto-restored derived account after seed phrase recovery with biometric authentication enabled
# Bug Report

### Preconditions:
The user has a backed-up derived account (from the default keypair) and expects this account to be restored along with the default account during the recovery process (Recovery phrase for user by request). 

### Reproduction

1. Log in using the recovery phrase.
2. Enable BIO authentication on the onboarding screen.
3. After restoration, the following accounts should be displayed:
-  Account 1 (default keypair)
-  Account 2 (derived account from the default keypair)
4. Initiate a Send/Swap/Bridge transaction from Account 2.
5. Sign the transaction.

#### Expected behavior
The transaction is successfully signed, processed, and recorded on the blockchain. The account balances are updated accordingly.

#### Actual behavior
An unknown error occurs (no error message displayed) when trying to signed the **Send/Swap/Bridge** transaction. The transaction does not go through.

https://github.com/user-attachments/assets/93299856-86ee-403e-8bc8-878905d77c6d

https://github.com/user-attachments/assets/fc69c78c-615a-4194-a199-e4f88c6d284b

### Additional Information

- The issue occurs only when the account is restored with two accounts on the default keypair and BIO authentication is enabled during onboarding.
- If a transaction is initiated from Account 1 or an imported account under the same conditions, it is processed successfully without any errors.
- If the authentication method is switched to password authentication (via settings or onboarding) and a transaction is made from Account 2, it goes through successfully.

- Status version: nightly 
- Operating System: Android, iOS

Logs:

[logs (19).zip](https://github.com/user-attachments/files/18591337/logs.19.zip)

Account 2 Address: 0x238c754b9119892836a8e0d62cfe3f8720522425
Imported Account Address:0xfc6327a092f6232e158a0dd1d6d967a2e1c65cd5

LOgs (4/02/25):

[Status-debug-logs (11).zip](https://github.com/user-attachments/files/18656890/Status-debug-logs.11.zip)

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #22000 

## Summary

This PR fixes an issue where the on-auth-success function is passed to the :keychain/get-user-password event but is not called with the user's password when biometric authentication succeeds. As a result, authentication appeared successful, but transactions failed to go through, leading to confusing error toasts when confirming send or bridge transactions.

Additionally, this PR includes a safeguard for handling partially operable accounts, as identified during debugging (thanks @smohamedjavid for your findings).

### Platforms

- Android
- iOS

#### Functional

- wallet / transactions

## Steps to test

- Check linked issue which contains specific steps on how to reproduce this issue.

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/status_im/common/standard_authentication/events.cljs [hunk 1]
```diff
@@ -80,12 +82,20 @@
...
-            [:keychain/get-user-password [key-uid on-auth-success]])
+            [:keychain/get-user-password
+             [key-uid
+              (fn [password]
+                (if has-partially-operable-accounts?
+                  (rf/dispatch [:wallet/make-partially-operable-accounts-fully-operable
+                                {:password   password
+                                 :on-success #(on-auth-success password)
+                                 :on-error   #(on-auth-success password)}])
+                  (on-auth-success password)))]])
```
Comment (clauxx) [inline src/status_im/common/standard_authentication/events.cljs]: We already have a [function that handles partially operable accounts](https://github.com/status-im/status-mobile/blob/45b09603d2b3c3f88030eda79b1e9562c2b00043/src/status_im/common/standard_authentication/events.cljs#L13) in this ns, it just wasn't used added for the biometrics authorization for some reason. Maybe it would be better to re-use it here?

Comment (pavloburykh) [reply src/status_im/common/standard_authentication/events.cljs]: @clauxx thank you for the review. @briansztamfater I will wait with testing until this comment is resolved. Please, ping me up once PR is ready. Moving PR to REVIEW column for now.

File: src/status_im/common/standard_authentication/events.cljs [hunk 2]
```diff
@@ -57,7 +57,8 @@
 
 (defn authorize-with-biometric
   [_ [{:keys [on-auth-success on-auth-fail on-close] :as args}]]
-  (let [args-with-biometric-btn
+  (let [has-partially-operable-accounts? (rf/sub [:wallet/has-partially-operable-accounts?])
```
Comment (vkjr) [inline src/status_im/common/standard_authentication/events.cljs]: `authorize-with-biometric` is an event function, so we shouldn't call the subscription from it, instead we can access the db directly. [re-frame wiki](https://github.com/day8/re-frame/wiki/FAQ#1-why-cant-i-access-subscriptions-from-event-handlers)

**Review by vkjr — CHANGES_REQUESTED** [review]
Please remove sub outside the event, thanks!

File: src/status_im/common/standard_authentication/events.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/common/standard_authentication/events.cljs]: I saw the function, but we can't use it directly without doing some general refactor on the auth events or auth logic itself. That function is called as a callback when the password bottom sheet succeeds and also as a callback on other events, and it does some other additional dispatch calls, which would require changes on this event if we want to use it.

IMO, this namespaces deserves a general refactor as it has many mixed logics (bottom sheets, functions passthrough, confusing event dispatching for different auth methods), but probably out of scope of this PR.

File: src/status_im/common/standard_authentication/events.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/common/standard_authentication/events.cljs]: Removed!

**Review by vkjr — APPROVED** [review]

File: src/status_im/common/standard_authentication/events.cljs (hunk 1 above)
Comment (vkjr) [reply src/status_im/common/standard_authentication/events.cljs]: @briansztamfater, @clauxx  I also vote for refactoring, because in generic `standard_authentication` namespace we'd better to not have any notion of `accounts`. Maybe we can call `:wallet/make-partially-operable-accounts-fully-operable` somewhere else?
This is a coupling that we do not really need. Authentication is a low-level thing, on that level no application entities should come up.

File: src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs [hunk 3]
```diff
@@ -11,28 +11,31 @@
...
+                                          (fn []
+                                            (rf/dispatch [:standard-auth/authorize
+                                                          {:auth-button-icon-left auth-button-icon-left
+                                                           :theme theme
+                                                           :blur? blur?
+                                                           :biometric-auth? biometric-auth?
+                                                           :on-auth-success on-auth-success
+                                                           :on-auth-fail on-auth-fail
+                                                           :auth-button-label auth-button-label
+                                                           :has-partially-operable-accounts?
```
Comment (clauxx) [inline src/status_im/common/standard_authentication/standard_auth/slide_button/view.cljs]: I don't think the authorize event needs to know about partially operable accounts, especially since it causes changes everywhere it's used. I'd rather keep it as it was inside the event, otherwise this way this hack is spreading all over the place.

**Comment by pavloburykh** [comment]
Hey @briansztamfater! Please, let me know when review comment are resolved and PR is ready for testing. Thanks!

**Comment by briansztamfater** [comment]
> Hey @briansztamfater! Please, let me know when review comment are resolved and PR is ready for testing. Thanks!

@pavloburykh we can start testing!

File: src/status_im/common/standard_authentication/events.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/common/standard_authentication/events.cljs]: @briansztamfater the solution you added doesn't really decouple it, you just moved the sub to all instances where standard-auth is used, but we still dispatch `:wallet/make-partially-operable-accounts-fully-operable` inside standard auth. If we don't refactor it properly then I think best would be to isolate this hack in one place, if it has to be in standard auth, due to the need to make the check before every auth interaction, so be it. Makes no sense to spread the sub everywhere. 
cc: @vkjr

**Review by clauxx — CHANGES_REQUESTED** [review]
@briansztamfater please address the comments

**Comment by pavloburykh** [comment]
> @briansztamfater please address the comments

@briansztamfater as there are some more unresolved comments I will stop manual QA for now. Please ping me up once all comments are resolved and PR is ready for testing. Moving PR to REVIEW column.

File: src/status_im/common/standard_authentication/events.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/common/standard_authentication/events.cljs]: @clauxx If you mean to roll back [the last commit](https://github.com/status-im/status-mobile/pull/22040/commits/261793b9027ce6aff992c7c154908ed2008ebc0e) until this namespace is properly refactored, I'm fine with that. I don't have strong opinions on it, let's just discuss and agree on the best approach with @vkjr for now, since he explicitly requested moving the sub outside the event. I also don't want this PR to get stuck in a black hole.

Comment (clauxx) [reply src/status_im/common/standard_authentication/events.cljs]: we should definitely roll back the previous commit and in no way do I suggest to refactor standard auth even more. How about extracting everything related to partially operable accounts in this ns (standard-auth/events) into a separate event and leave a comment about it not belonging in standard-auth (not sure if we can cleanly refactor it at the moment) e.g:

```cljs
(defn- partially-operable-accounts?
  [accounts]
  (->> accounts
       (some #(= :partially (:operable %)))
       boolean))

(rf/reg-fx
 :effects.standard-auth/on-auth-success
 (fn [on-auth-success]
   (when on-auth-success
     (on-auth-success))))

(rf/reg-event-fx
 :standard-auth/migrate-partially-operable-accounts
 (fn [{:keys [db]} [masked-password on-success]]
   (let [on-auth-success-callback         #(on-success masked-password)
         has-partially-operable-accounts? (-> (get-in db [:wallet :accounts])
                                              partially-operable-accounts?)]
     {:fx [(if has-partially-operable-accounts?
             [:dispatch
              [:wallet/make-partially-operable-accounts-fully-operable
               {:password   masked-password
                :on-success on-auth-success-callback
                :on-error   on-auth-success-callback}]]
             [:effects.standard-auth/on-auth-success on-auth-success-callback])]})))
```

This event could be dispatched in both instances (password and biometrics), it's isolated in case we will want to move it elsewhere, and doesn't require any api changes for standard-auth or any major refactors. WDYT @vkjr @briansztamfater ?

Comment (vkjr) [reply src/status_im/common/standard_authentication/events.cljs]: @briansztamfater, @clauxx, when I mentioned that we need to get rid of `rf/sub`, I meant that we can get the same information from `rf-db` which is accessible in `(authorize-with-biometric)` function.

```clojure
(rf/reg-event-fx :standard-auth/authorize-with-biometric authorize-with-biometric)
```
Since `authorize-with-biometric` defined as event handler, it will get cofx as the first argument.

So instead of current declaration:
```clojure
(defn authorize-with-biometric
  [_ [{:keys [on-auth-success on-auth-fail on-close has-partially-operable-accounts?] :as args}]]
  ```
  
  We can rewrite it with:
  ```clojure
(defn authorize-with-biometric
  [ {:db db} [{:keys [on-auth-success on-auth-fail on-close has-partially-operable-accounts?] :as args}]]
  ```
And directly get into database to fetch `has-partially-operable-accounts?` value.

For sure we better not transfer this argument all the way from the view.

Comment (briansztamfater) [reply src/status_im/common/standard_authentication/events.cljs]: Thanks for the suggestions @clauxx @vkjr. Please check [this commit](https://github.com/status-im/status-mobile/pull/22040/commits/b47361c837726f8d02ee47dfdae4753ac6d99653).

I used mostly Cristian's suggestions, although I needed to adapt the logic from the password authentication code. The good thing is that the sub is not needed anymore, so I removed it completely.

**Review by clauxx — APPROVED** [review]
Looks good!

**Comment by pavloburykh** [comment]
@briansztamfater thanks for the PR. Please take a look at the issue below. 

### ISSUE 1 Cannot import new keypair or sign transaction from imported account using Keycard

**Steps:** 

1. Migrate user to keycard
2. Try to import new keypair OR try to sign any transaction from imported account using Keycard (in this case you should import account before migrating to keycard)
3. Observe the result

**Actual result:** cannot import new keypair or sign transaction from imported account using Keycard. Pin code drawer remains open after scanning Keycard/ 

[logs.zip](https://github.com/user-attachments/files/18784492/logs.zip)


https://github.com/user-attachments/assets/398b772a-06ea-4ef1-a59b-ee607df85c75


https://github.com/user-attachments/assets/8fc8c84e-fd47-450d-a035-18c0c1f0e280

**Comment by briansztamfater** [comment]
@pavloburykh thanks for testing, issue should be fixed now! Let me know if you find anything else

**Comment by clauxx** [comment]
> @pavloburykh thanks for testing, issue should be fixed now! Let me know if you find anything else

what are the changes for the fix? due to the amend+force-push, I can't see what changed since the last time I reviewed.

**Comment by briansztamfater** [comment]
> > @pavloburykh thanks for testing, issue should be fixed now! Let me know if you find anything else
> 
> what are the changes for the fix? due to the amend+force-push, I can't see what changed since the last time I reviewed.

I was returning the `on-auth-success-callback` function in `handle-password-success` instead of calling the function.

**Comment by pavloburykh** [comment]
@briansztamfater thanks for the fix. No other issues from my side. In case @clauxx does not have any additional questions, PR is ready for merge. 

What has been tested (IOS/Android): 

1. Signing transactions via biometry using derived restored account is fixed. 
2. Tested signing transactions via password/biometry/keycard from different types of accounts, i.e default, derived from default, imported, derived from imported
3. Adding different types of accounts via pasword/keycard/biometry
4. Signing transactions by different methods, from different types of accounts via synced user 
5. Importing partially operable accounts via keycard, signing transactions from such accounts
6. Setting up biometry works as before

**Comment by briansztamfater** [comment]
@pavloburykh thanks for verifying the fix. @clauxx let me know if we can merge!

**Comment by clauxx** [comment]
all good from my side :+1:
