### PR TITLE
fix multiple set view-id events dispatched

### LINKED ISSUE #18811: Set the value of set-view-id when opening up modals
# Bug Report

## Problem 
Set the view-id to force applying the status-bar color when opening modals

#### Expected behavior
Set the value of set-view-id when opening up modals to apply the status bar color

#### Actual behavior
CleanShot 2024-02-13 at 23 10 11

### Reproduction

1. Open any modal

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/18811

related to: https://discord.com/channels/1103692771585433630/1103692773363810317/1212833784869683300 (@flexsurfer)
> after navigating to screen there are set-view-id :shell-stack events twice

Every time app reloaded, `reg-modal-dismissed-listener` was being called and was behaving strange and firing set-view-id event multiple times (same times the app refreshed). Issue was in debug only.

@ibrkhalil Thank you for [reporting](https://github.com/status-im/status-mobile/pull/18785#discussion_r1487418159) wrong view-id for settings screen. Most probably this was caused by this same bug, where we are getting set-view-id being called multiple times and leading to wrong value. I checked Android and its working now. If you have access to IOS, please let me know if its right for you too. Thank you

### Testing
No manual testing is required for the PR. 

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im/navigation/core.cljs [hunk 1]
```diff
@@ -11,86 +11,88 @@
...
- (fn [] views/toasts))
-
-;;;; Bottom sheet
-
-(navigation/register-component
- "bottom-sheet"
- (fn [] (gesture/gesture-handler-root-hoc views/bottom-sheet))
- (fn [] views/bottom-sheet))
+(defonce
+  _
```
Comment (J-Son89) [inline src/status_im/navigation/core.cljs]: should we not just have a navigation init function that registers these somewhere in the app?

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/navigation/core.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/navigation/core.cljs]: Done, moved to `status-im.core`.
Functions called in `defonce` were being called just before `init` function, So hopefully it will not have any side effect and will work same. cc @flexsurfer @J-Son89

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/navigation/core.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/navigation/core.cljs]: nice, looks good to me!

**Comment by Parveshdhull** [comment]
@status-im/mobile-qa Please can you look into failed tests?

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull the failures are not PR related. Thank you for PR. If no necessity to test it manually then PR can be merged. Thank you
