### PR TITLE
[#21436] List of users overlap composer input

### LINKED ISSUE #21436: Dropdown list of users overlaps the message input field when mentioning a user in empty chat in community
# Bug Report

### Reproduction

1. Join and open the chat list in the Status community.
2. Select a chat with no messages or just a few messages.
3. Try to mention a user by typing "@" in the message input field.
4. Observe the dropdown list that appears.

#### Expected behavior
The dropdown list should appear above the message input field, allowing the user to continue typing without obstruction.

#### Actual behavior
The dropdown list overlaps the message input field, making it inconvenient to type.

https://github.com/user-attachments/assets/724ff3d9-7483-4475-b829-df10b974bf2c

### Additional Information

- Status version: nightly 2.30.0 (20241014020839)
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21436

### Summary

This PR fixes the styles so that the input is no longer covered.

While solving this, I noticed we were updating the mention's state asynchronously, and it looked as follows:

https://github.com/user-attachments/assets/288dae61-5755-42d7-92b7-80b464ab1aba

Screenshots (to check how the mentions are aligned):

 ->  ->  ->  -> 

Not it's been fixed and looks as follows:

https://github.com/user-attachments/assets/6ea22835-70f3-4c70-a380-95032b230211

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Create a group chat with multiple participants
- Clean the chat history
- Try to tag someone (now it works without overlapping the content)

status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 1]
```diff
@@ -230,7 +230,8 @@
                                              distance-from-list-top
                                              chat-list-scroll-y
                                              (on-scroll-fn distance-atom layout-height)))
-        :style                             {:background-color (colors/theme-colors colors/white
+        :style                             {:height           "100%"
+                                            :background-color (colors/theme-colors colors/white
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs:229]: This is the layout fix for the reported issue

File: src/status_im/contexts/chat/messenger/composer/mentions/style.cljs [hunk 2]
```diff
@@ -2,29 +2,38 @@
...
-     :shadow-offset  {:width 0 :height (colors/theme-colors 8 12 theme)}}
-    {:elevation 10}))
+(defn- add-shadow
+  [theme styles]
+  (cond-> styles
+    platform/ios? (assoc :shadow-radius (colors/theme-colors 30 50 theme)
+                         :shadow-opacity (colors/theme-colors 0.1 0.7 theme)
+                         :shadow-color colors/neutral-100
+                         :shadow-offset {:width 0 :height (colors/theme-colors 8 12 theme)})
+    :else (assoc :elevation 10)))
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/composer/mentions/style.cljs]: Modified this to use `assoc` instead of `merge` :eyes:

File: src/status_im/contexts/chat/messenger/composer/mentions/style.cljs [hunk 3]
```diff
@@ -2,29 +2,38 @@
...
+  [{:opacity opacity}
+   (add-shadow theme
+               {:position         :absolute
+                :top              (- (+ 8 top))
+                :left             8
+                :right            8
+                :border-radius    16
+                :z-index          4
+                :max-height       constants/mentions-max-height
+                :background-color (colors/theme-colors colors/white colors/neutral-95 theme)})])
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/composer/mentions/style.cljs:40]: I tried several ways to solve the rendering issue in the mentions component, but nothing else worked. 

The problem is caused by our `apply-animations-to-style` wrapper, seems its usage delays the rendering of its stytles ~1 frame.

By avoiding its usage, we get the component state updated on time, here we are using the vector syntax introduced a while ago.

CC: @ilmotta

File: src/status_im/contexts/chat/messenger/composer/mentions/style.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/mentions/style.cljs]: Here I think `cond->` is more convoluted to read than a simple `if` macro.

```clojure
(defn- add-shadow
  [theme styles]
  (if platform/ios?
    (assoc styles
           :shadow-radius  (colors/theme-colors 30 50 theme)
           :shadow-opacity (colors/theme-colors 0.1 0.7 theme)
           :shadow-color   colors/neutral-100
           :shadow-offset  {:width 0 :height (colors/theme-colors 8 12 theme)})
    (assoc styles :elevation 10)))
```

File: src/status_im/contexts/chat/messenger/composer/mentions/view.cljs [hunk 4]
```diff
@@ -35,10 +35,9 @@
          (set-suggestions-state suggestions)
          (js/setTimeout #(set-suggestions-state suggestions) 300))
        (reanimated/animate opacity (if suggestions? 1 0)))
-     [suggestions?])
-    [reanimated/view
-     {:style (style/container opacity top theme)}
-     [rn/flat-list
+     [suggestions])
+    [reanimated/view {:style (style/container opacity top theme)}
+     [reanimated/flat-list
```
Comment (ilmotta) [inline src/status_im/contexts/chat/messenger/composer/mentions/view.cljs]: What do we gain by using a flat list here instead of the macro `for`? I checked with a simple `for` and it all works the same apparently, including the animation.

Related to your comment https://github.com/status-im/status-mobile/pull/21641#discussion_r1849112868, we should consider removing micro animation code in certain places if they get in our way during development at this stage of the product. I'm not saying we should always do that with micro animations. Here, you fought a battle related to state synchronization between two sources as you and I talked in private. This `view` component contains workarounds that make the code brittle.

The code below is much simpler and delivers the same experience in my opinion. Or perhaps my suggested code has a flaw, but I couldn't see.

```clojure
(defn view
  [layout-height]
  (let [suggestions (rf/sub [:chat/mention-suggestions])
        theme       (quo.theme/use-theme)
        top         (min constants/mentions-max-height
                         (* (count suggestions) 56)
                         (- @layout-height
                            (+ (safe-area/get-top)
                               messages.constants/top-bar-height
                               5)))]
    [rn/view {:style (style/container top theme)}
     (for [user (vals suggestions)]
       ^{:key (:key user)}
       [mention-item user])]))
```

Anyway, this is just a light suggestion to remove the micro animation to simplify, but since you solved the problem it's okay to keep the animation @ulisesmac.

**Review by ilmotta — APPROVED** [review]
Thanks for this important fix!

File: src/status_im/contexts/chat/messenger/composer/mentions/view.cljs (hunk 4 above)
Comment (clauxx) [reply src/status_im/contexts/chat/messenger/composer/mentions/view.cljs]: > What do we gain by using a flat list here instead of the macro for? I checked with a simple for and it all works the same apparently, including the animation.

I think without the flatlist we wouldn't get the scroll if the list is large, but unsure if we want that. We could limit the amount of results we show also if we don't want the scroll, might make it lighter to re-render.

**Review by clauxx — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/composer/mentions/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/messenger/composer/mentions/view.cljs]: > What do we gain by using a flat list here instead of the macro for? I checked with a simple for and it all works the same apparently, including the animation.

@ilmotta A flat-list is lazy, it's built to render a lot of items, it just renders what you see (window-size) and some windows above and below (it's configurable). Having a `for` inside a `scroll-view` (to keep the scrolling) will render all possible suggestions at once. Not the best for this use case.

Comment (ulisesmac) [reply src/status_im/contexts/chat/messenger/composer/mentions/view.cljs]: @ilmotta 
Thanks for your simplification. I think the opacity animation gives a slightly smoother experience, ofc, I'd like to improve the code by removing that `use-effect`, but I think we will need this hook in any animated component. Also, since the problem is solved I'd prefer to keep it.

We can explore ways to make this cleaner later, since in the future we will add animations to our app to make its usage more enjoyable.

File: src/status_im/contexts/chat/messenger/composer/mentions/style.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/messenger/composer/mentions/style.cljs]: Haha :sweat_smile: I completely agree! I'll update it :+1:  Thanks

File: src/status_im/contexts/chat/messenger/composer/mentions/view.cljs (hunk 4 above)
Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/mentions/view.cljs]: The list of mentions is limited by 10 items I think.

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/mentions/view.cljs]: In which case the flatlist is unnecessary. https://github.com/status-im/status-mobile/pull/21131

Comment (ulisesmac) [reply src/status_im/contexts/chat/messenger/composer/mentions/view.cljs]: Cool, then we can use a scrollview! I'll change it.

**Comment by churik** [comment]
@ulisesmac please move it to testing when it is ready, would be nice to have it in 2.32

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac, thank you for the PR! The issue with the suggestion list overlapping the composer when a large amount of data is still reproducible. However, I believe this might be out of scope for the current PR. Please let me know if that's the case, and I can create a follow-up for this.

## ISSUE 1: The suggestion list overlaps composer when large data Is added

### Steps:
1. Go to composer
2. Add resolvable link
3. Attach images
4. Enter @ to see the suggestion list

### Actual result:
The suggestion list overlaps the composer

https://github.com/user-attachments/assets/24f97ab5-23cf-44c4-89d9-c184eb9e50f6


### Expected result:
The suggestion list should not overlap the composer

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by ulisesmac** [comment]
> Hi @ulisesmac, thank you for the PR! The issue with the suggestion list overlapping the composer when a large amount of data is added is still reproducible. However, I believe this might be out of scope for the current PR. Please let me know if that's the case, and I can create a follow-up for this.
> ## ISSUE 1: The suggestion list overlaps composer when large data Is added
> ### Steps:
> 
>     1. Go to composer
> 
>     2. Add resolvable link
> 
>     3. Attach images
> 
>     4. Enter @ to see the suggestion list
> 
> 
> ### Actual result:
> 
> The suggestion list overlaps the composer
> composer.mp4
> ### Expected result:
> 
> The suggestion list should not overlap the composer
> ### Devices:
> 
>     * Pixel 7a, Android 13
> 
>     * iPhone 11 Pro Max, IOS 17


This bug is interesting, I think we don't have designs for this edge case, probably we should display the mentions just above the composer and the mentions should grow up to the size of the chat screen left.

Fixing this might require some calculations and making the mentions resizable.

@VolodLytvynenko Yes, please let's open a follow-up since we need to confirm with designers. CC: @ilmotta wdyt?

**Comment by VolodLytvynenko** [comment]
@ulisesmac Thank you for your work. No other issues from my side.  PR is ready to be merged.  [ISSUE 1](https://github.com/status-im/status-mobile/pull/21641#issuecomment-2501546756) is created as a follow up https://github.com/status-im/status-mobile/issues/21692

**Comment by ilmotta** [comment]
> Fixing this might require some calculations and making the mentions resizable.
>
> @VolodLytvynenko Yes, please let's open a follow-up since we need to confirm with designers. CC: @ilmotta wdyt?

Good idea @ulisesmac 👍🏼
