### PR TITLE
fix wrong counter color in jump-to screen

### LINKED ISSUE #17553: Wrong counter color in jump-to screen
### Screenshot
image
image

### Figma Link
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:66732&mode=design#570710701
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:66732&mode=design#570707788

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/17553

### Testing (Design)
In the design review, both the bottom nav and top bar counter color are reported as wrong, but I tried printing color and using a color picker and it looks like the top bar in the jump-to screen is using the right color. Maybe it is fixed in develop after release. Please let me know if this is not the case

status: ready

### CODE REVIEW

File: src/status_im2/contexts/shell/jump_to/components/bottom_tabs/view.cljs [hunk 1]
```diff
@@ -1,10 +1,11 @@
 (ns status-im2.contexts.shell.jump-to.components.bottom-tabs.view
-  (:require [utils.re-frame :as rf]
+  (:require [quo2.core :as quo]
+            [quo2.theme :as theme]
```
Comment (J-Son89) [inline src/status_im2/contexts/shell/jump_to/components/bottom_tabs/view.cljs]: nit import as quo.theme to avoid clashes with `theme` prop - (perhaps it won't matter in this file though 🤔 )

**Review by J-Son89 — APPROVED** [review]

**Review by Francesca-G — APPROVED** [review]
Looks good now :)

**Comment by Parveshdhull** [comment]
> 2. [test_group_chat_mute_chat](https://ethstatus.testrail.net/index.php?/tests/view/3249489)
> New messages counter near chats tab button is 1 after unmute, but should be 2

(not sure if its known, or caused by PR)

@status-im/mobile-qa, Please can you check failed tests

**Comment by qoqobolo** [comment]
> (not sure if its known, or caused by PR)

yeah it's known, e2e failures are not related to the PR changes @Parveshdhull
