### PR TITLE
fix: allow auto-correct to update message text before sending message

### LINKED ISSUE #21774: [iOS] Send button disappears after typed text сalls autocomplete suggestions
# Bug Report

## Problem 
[comment]: # (A problem description)

### Reproduction

1. Login to app
2. Open 1-1 chat (group chat, community channel)
3. Start type some text like I do on my video

https://github.com/user-attachments/assets/da58f2b8-98be-4871-b435-7b5021802eac

#### Actual behavior

After sending text that was highlighed then next text would lost Send button

#### Expected behavior

Send button should be present in every case

### Additional Information

- Status version: nightly 06/12
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #21774

## Summary
[comment]: # (Summarise the problem and how the pull request solves it)

* This PR attempts to resolve an issue with the chat text-input when using auto-correct on iOS.
  * The initial issue mentioned in #21774 seems to be caused by auto-correct replacing the text after the message has been sent and the text-input cleared.
* This PR resolves the issue by allowing the auto-correct feature to change the text before sending the message.
  * This functionality seems to match what happens in other chat apps on iOS like Messages, Signal, and WhatsApp.

### Platforms
[comment]: # (Optional. Specify which platforms should be tested)

- Android
- iOS

### Areas that may be impacted
[comment]: # (Optional. Specify if some specific areas need to be tested, such as 1-1 chats)

#### Functional

- 1-1 chats
- public chats
- group chats
- auto-correct in chat (iOS)

### Steps to test
[comment]: #  (Specify exact steps to test if there are such)

- Ensure auto-correct is enabled on device keyboard
- Open Status mobile app
- Open a chat
- Type a message with typo that is detected by auto-correct
  - For example, the message "Yesh" would be recommended to be "Yeah"
- Press the send message button
- Review which message text was sent in chat log

### Screen Capture after changes on iOS

https://github.com/user-attachments/assets/5bb82f45-1371-4128-978d-e4d730184aa1

[comment]: # (Can be ready or wip)
status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/composer/actions/view.cljs [hunk 1]
```diff
@@ -30,7 +30,11 @@
         contact-customization-color (when (= chat-type constants/one-to-one-chat-type)
                                       (rf/sub [:contacts/contact-customization-color-by-address
                                                chat-id]))
-        on-press                    (rn/use-callback #(send-message input-ref edit btn-opacity) [edit])]
+        on-press                    (rn/use-callback
+                                     (fn []
+                                       (js/requestAnimationFrame
+                                        #(send-message input-ref edit btn-opacity)))
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: Thank you @seanstrom for fixing this issue. Please can you add a comment to explain how this fixes the issue.

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/composer/actions/view.cljs [hunk 2]
```diff
@@ -30,7 +30,11 @@
         contact-customization-color (when (= chat-type constants/one-to-one-chat-type)
                                       (rf/sub [:contacts/contact-customization-color-by-address
                                                chat-id]))
-        on-press                    (rn/use-callback #(send-message input-ref edit btn-opacity) [edit])]
+        on-press                    (rn/use-callback
+                                     (fn []
+                                       (js/requestAnimationFrame
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: probably would be better to use setTimeout?

File: src/status_im/contexts/chat/messenger/composer/actions/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: I wonder if there's any benefit in using `reagent/next-tick` which does have some usages in the repo.

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/composer/actions/view.cljs [hunk 3]
```diff
@@ -18,6 +19,19 @@
...
+   
+   The usage `reagent/next-tick` will effectively schedule the `send-message`
+   function to run after any final modifications have been to the text-input.
+
+   For example on iOS, tools like auto-correct will attempt to modify the
+   text-input when pressing the send button. Using `reagent/next-tick` allows
+   for that modification to happen and the related event dispatches to resolve
+   before call the `send-message` function."
+  [params]
+  (reagent/next-tick #(send-message params)))
```
Comment (seanstrom) [inline src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: After some testing around, I noticed that we can use `reagent/next-tick`, which I think internally uses `requestAnimationFrame`.

Originally, I attempted to use `setTimeout` with timeout value of zero, which did not work. I then slightly increased the amount to 10ms and then 100ms. At around 100ms I was able to achieve the desired results, but I imagine that 100ms is only coincidentally working because of the speed of my device and the limited amount of stuff happening for updating text-input and dispatching re-frame events.

I think the usage of `reagent/next-tick` or `requestAnimationFrame` is primarily to wait for text-input and re-frame events to resolve before calling `send-message`. Based on the [react-native documentation on requestAnimationFrame](https://reactnative.dev/docs/timers#timers), it seems that the `send-message` function will run after all the frames have flushed.

That being said, I'm not certain this gives us the behaviour we want when there could be a lot of activity happening on the screen, and somehow that stalls sending the message since we're waiting for the frames to flush.

cc @flexsurfer @ilmotta @Parveshdhull

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: What you said makes sense to me. With these things I always check the documentation, but always check the actual behavior anyway because it's somewhat unpredictable given other things affecting rendering. Hence, beyond the technicalities of requestAnimationFrame or reagent next-tick, if you tested and it works, I think it's good to go @seanstrom.

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: reagent uses fake next-tick for non web apps
```
(defn fake-raf [f]
  (js/setTimeout f 16))

(def next-tick
  (if-not is-client
    fake-raf
```
    

and we found out this work not really good, and we replaced it with `(set! batching/fake-raf #(js/setTimeout % 0))`

so `reagent/next-tick` will work similar to `(js/setTimeout % 0)`

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: setTimeout 500 usually works

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: btw this doesn't look like a proper solution, we want send button to be as responsive as possible, we shouldn't implement something general here

**Review by flexsurfer — CHANGES_REQUESTED** [review]
we need to find a proper solution

**Comment by flexsurfer** [comment]
i'm not sure why a message is being sent, when we press on suggestion it should be just replaced and not autosent right?

File: src/status_im/contexts/chat/messenger/composer/actions/view.cljs (hunk 3 above)
Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: @flexsurfer a timeout of 500ms will probably wait longer than `next-tick` in practice, though I'll try to measure how long it takes for the callback to fire with `next-tick` and `requestAnimationFrame`.

---

You're correct, under the hood `next-tick` does not use `requestAnimationFrame`, though it does some more stuff than just a pure `setTimeout` call with zero. It seems to schedule the callback on some internal queues and then use the fake-raf to schedule callbacks when flushing ratoms and batching a render.

And while comparing `next-tick` to `setTimeout` with zero, the `setTimeout` solution doesn't work as intended, it still has the same issue we're trying to resolve.

---

As far as the proper solution, I agree that we should have a better way to only delay send-message when we know the auto-correct feature is active, but at the moment I'm not sure how to do that. I've tried using the text-selection APIs to detect if some text is about to be replaced (highlighted), but that doesn't seem to work since the auto-correct feature is not technically selecting the text.

So if we have a way to detect the auto-correct feature, then we can avoid this general delay, or we can even only do it on iOS if this behaviour is exclusive to iOS but I'm not sure about that either.

**Comment by seanstrom** [comment]
> i'm not sure why a message is being sent, when we press on suggestion it should be just replaced and not autosent right?

Yeah good question, it seems iOS will auto-correct the text while editing if someone presses the space-key, the return-key, or the send button. I'm not sure how it's integrating into this, but it might be detecting taps near the suggestions area or the keyboard (?)

File: src/status_im/contexts/chat/messenger/composer/actions/view.cljs (hunk 3 above)
Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: Digging a little deeper into this I've noticed that a `setTimeout` of 10ms or 16ms, does seem to work. What's surprising is that a `setTimeout` of 1ms seems to work, but not 0ms. Even weirder, `setTimeout` with `-1` also works.

Side Notes:
* I also tried `setImmediate`, just to double check, and this also does not seem to work.
* I wonder if reagent internally is still the version of fake-raf with 16ms delay somehow (?)

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: We are talking about workaround options in this thread, so as long as the workaround works it's fine. @seanstrom I take the `next-tick` option didn't work? I thought from your message that it did https://github.com/status-im/status-mobile/pull/22278#discussion_r1991122308

Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: @ilmotta at runtime I notice that `next-tick` does work. Though I think it's not suppose to work because we're attempting to override its behaviour elsewhere in the code to use a setTimeout with 0ms instead of 16ms. From what I tested setTimeout with 0ms does not work for this, so I'm confused if that override is working.

That being said, while I like `next-tick`, it might be risky to rely on it for this use-case since it might break later-on if that override is fixed or changed later. So maybe requestAnimationFrame or requestIdleCallback is safer (?). If we use requestAnimationFrame, maybe we can create a utility named `next-frame` or `next-paint`. Thoughts?

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: I'll add more questions than answers @seanstrom.

> From what I tested setTimeout with 0ms does not work for this, so I'm confused if that override is working.

I did a quick check on the behavior of 3 different functions. I was surprised by the results of `reagent.core/next-tick` and I encourage you guys to try out. I would love to understand why `reagent.core/next-tick` prints with a lot less delay than `setTimeout`, but I stopped digging at this point.

```clojure
(comment
  ;; On average prints every 3ms, rarely 4ms
  (doseq [_ (range 100)]
    (batching/fake-raf
     (fn []
       (println (utils.datetime/timestamp))))))

(comment
  ;; Prints multiple times in sub-millisecond differences.
  (doseq [_ (range 100)]
    (reagent.core/next-tick
     (fn []
       (println (utils.datetime/timestamp))))))

(comment
  ;; Sometimes prints every 1ms, sometimes 2ms, and slightly less with a 3ms difference.
  (doseq [_ (range 100)]
    (goog.async.nextTick
     (fn []
       (println (utils.datetime/timestamp))))))

```

-------

I did a bit of digging to uncover the history behind this workaround with the fake-raf, the fork of re-frame in Status, and so on.

For reference, this is the PR that stopped using Status' fork of re-frame.

- https://github.com/status-im/status-mobile/pull/10403/files#diff-f92f80f277ada2cf686cb5c439f424f6ad0b0939e5fe3e452cb8e27b103b8be6R13

We override `(set! interop/next-tick js/setTimeout)`. The original code in re-frame uses `goog.async.nextTick`. The documentation from Google says:

> Fires the provided callbacks as soon as possible after the current JS execution context. setTimeout(…, 0) takes at least 4ms when called from within another setTimeout(…, 0) for legacy reasons.
>
> -- https://google.github.io/closure-library/api/goog.async.nextTick.html

Can you help us understand why we need to override this setting @flexsurfer `goog.async.nextTick` seems to be better, or no? From this [image from PR
#10403](https://user-images.githubusercontent.com/11790366/79976955-c9e23b00-849d-11ea-8d11-81e00d9b6cb2.png) it appears as if `goog.async.nextTick` is actually taking longer than `setTimeout` 0?

Function `goog.async.nextTick` uses `setImmediate`, which as far as I understood take precedence over setTimeout 0, but only if there's no I/O involved. But I only read about this for the Node environment and its event loop.

-----

> That being said, while I like next-tick, it might be risky to rely on it for this use-case since it might break later-on if that override is fixed or changed later

But who's going to change the override in practice? This type of change would need to be carefully reviewed in a PR @seanstrom. And this override exists for ages already in the repo.

I suggest we timebox trying an alternative solution, because if you found a solution that works, let's stick with that. None of the solutions proposed look clean anyway. @flexsurfer please keep this in mind given you rejected the PR.

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: i rejected PR because it doesn't solve original issue, which is "message shouldn't be sent on auto-correct"

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: https://github.com/status-im/status-mobile/pull/10403

Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: I think the setTimeout with 16ms is meant simulate waiting for the next frame, assuming we're rendering at around 60fps. But that assumes we would be drawing at 60fps, and some devices could potentially draw faster (unless constrained).

Typically when I've used setTimeout with 0ms (or setImmediate) it's to schedule something on the next tick of the event loop. This is done with the intention that everything happening in the current event loop queue will finish and I can assume it's done by the next event loop tick.

In the case with the auto-correct and text-input stuff, it doesn't seem like everything is finished by the next tick in the event loop since we likely have the react-native event dispatch and then the re-frame event dispatches to set the input state. Perhaps we're only coincidentally waiting long enough, but we'll need some kind of debounce handling if auto-correct decides to change the text at the last moment.

---

Ideally, I would have some kind of event or method for waiting for the text-input to resolve to its final state. For example, it would be nice if the text input ref allowed us to ask: "are you ready?" and then send the message.

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: @seanstrom correct me if I got things wrong, you said the solution currently committed works. I take by "work" we mean it resolves the PR and the message won't be sent without resolving the auto-correct issue. If that's not the case, then I agree with @flexsurfer the PR is not ready for merging.

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: About the behavioral difference between `reagent/next-tick` and `setTimeout`, it looks like the delays are *mostly* coming from the timestamp call, which is quite slow as we know.

```clojure
(doseq [_ (range 100)]
  (println (utils.datetime/timestamp)))
;; LOG 1741795717050
;; LOG 1741795717051
;; LOG 1741795717051
;; LOG 1741795717052
;; LOG 1741795717054
;; LOG 1741795717057
;; LOG 1741795717059
;; LOG 1741795717061
```

The way I measured leads to this problem. The best is to collect the initial and final time and then subtract and divide to get an average. But this will still lead to an interesting question, why is `reagent/next-tick` behaving so abnormally to print the timestamps? It almost looks as if it caches for a while, then advances. Could be related to how it has flags to control when the schedule runs, although it should be use using `setTimeout` with 0, it still does extra work as we can see from all the different flush calls.

Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: @ilmotta @flexsurfer the original issue is as follows:
* When typing a message, if the auto-correct is actively highlighting a word inside the text-input iOS, and then the user presses the send message button, the message is sent but the text-input is left a weird state.
  * The weird state involves the text-input being populated with the auto-corrected version of the text, but with the send key hidden. This is because the app thinks we sent the message and does not understand that auto-correct has changed the text after the user pressed the send button.
* The solution in this PR is to wait for auto-correct to change the text before sending the message.
  * The original issue requested that the send button would be showing if the text-input was populated, not that we don't send the message when auto-correct is activated.
  * The reason this PR implements the waiting logic is because the behaviour matches other usages of auto-correct interacting with chat app text-inputs.

Currently, the changes in the PR will wait for auto-correct to resolve and then send the message. Though, there is some question about how consistent this will perform, it currently works from my testing on a iOS device.

Comment (ilmotta) [reply src/status_im/contexts/chat/messenger/composer/actions/view.cljs]: @seanstrom my 2 cents/suggestion: mark the PR as draft and align with QA that you need help verifying the fix works in real devices. You already found a fix for iOS based on your testing. Meanwhile, investigate if there is a better solution as @flexsurfer suggests, if there isn't, then the PR should advance in the pipeline.

**Comment by mariia-skrypnyk** [comment]
Hi @seanstrom !

Thanks for your fix!

Tested on:

- iOS/Android
- 1-1, group chats

Failed e2e is not related.
PR can be merged.

**Comment by seanstrom** [comment]
For future readers:

We've looked into the code a little more and discovered that the overrides that we've used for setting the `fake-raf` function for reagent is not working as we had thought. Meaning that the current behaviour of reagent `next-tick` is to use a `setTimeout` with a 16ms delay.

I'll also be publishing a separate PR to remove the override code, since it's not currently working as intended, and changing reagent's `fake-raf` to now work as a `setTimeout` with 0ms could cause subtle bugs throughout the code.

**Comment by seanstrom** [comment]
Given [what we know now about reagent's `next-tick` behaviour](https://github.com/status-im/status-mobile/pull/22278#issuecomment-2729903019), and double checking the fix with QA, are we okay to pass this PR?

cc @flexsurfer @ilmotta

**Review by flexsurfer — APPROVED** [review]
thank you @seanstrom , lets please add condition for ios only

**Comment by seanstrom** [comment]
@mariia-skrypnyk I've pushed up some small tweaks to this PR.
Should we re-test the PR or are we okay to merge?

**Comment by mariia-skrypnyk** [comment]
Thanks @seanstrom !

Will check on dev.
