### PR TITLE
fix input issues

### LINKED ISSUE #19038: Sometimes cursor jumps back when typing fast in the name input filed (IOS)
reproducing on iPhone X, IOS 16.7.5

**Steps:** 

1. Open onboarding Create profile screen
2. Start typing name fast
3. See cursor's behaviour

**Actual result:** Sometimes cursor jumps back when typing name fast. Also sometimes cursor starts lagging when deleting inout value. 

https://github.com/status-im/status-mobile/assets/97245802/495b97d9-fd5a-426d-ba95-f224d5c89f10

### Additional Information

- Status version: nightly 
- Operating System: iOS

### LINKED ISSUE #19050: The scanned valid ETH address is not pasted into the "Send to" page field after QR scanning.
### Steps:
1. Go to the Send to page
2. Scan eth address

### Actual result:
The scanned valid eth is not pasted into the Send to page field

https://github.com/status-im/status-mobile/assets/52490791/500e1cc2-04d5-439e-9d41-b9822be02b13

### Expected result:
The scanned valid eth address should be automatically pasted into the "Send to" page field.

### Devices:
IOS, Android

### ENV:
nightly 29 Feb 2024

### LINKED ISSUE #19158: Unable to input data into the "Send To" page
### Steps:
1. Go to the Sent to page
2. Attempt to input more than 2 characters into the input field.

### Actual result:
Only 1 character can be inputted into the field.

https://github.com/status-im/status-mobile/assets/52490791/6017cf23-573a-4f98-ab1e-0b8ba9992788

### Expected result:
The user should be able to input more than 1 character into the "Send To" input field.

### ENV:
nightly  [8 Mar 2024]

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #19158
fixes #19038
fixes #19050

so basically there are two points
1) if we set a value we must control it, and update on every text change, I didn't know that and used ref instead of state
2) dafaultValue works strangely, it works like value, so it updates value, but it shouldn't, so we should control this as well and not use state or reactive atom for defaultValue, it should be a constant

### CODE REVIEW

File: src/status_im/common/emoji_picker/view.cljs [hunk 1]
```diff
@@ -189,6 +187,7 @@
                                                               @search-text))))
                                    constants/search-debounce-ms)
         on-change-text            (fn [text]
+                                    (println "on change" text)
```
Comment (Parveshdhull) [inline src/status_im/common/emoji_picker/view.cljs]: leftover

**Review by Parveshdhull — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
Nice!

**Comment by VolodLytvynenko** [comment]
@flexsurfer Thank you for PR. No issues from my side. PR is ready to be merged
