### PR TITLE
fix role is not updated correctly when unselecting accounts

### LINKED ISSUE #19407: Role is not updated correctly if user unselects several accounts with required tokens one by one
**Preconditions:** 

1. Let's say we have a community with 2 separate membership permissions: 0.01 ETH to become a member and 10 STT to become a member
2. Mobile User has 3 Accounts A, B, C. He holds 0.01 ETH on Account A and 10 STT on Account B, Account C is without tokens.

**Steps:** 

1. Open Addresses for permissions screen by Mobile user 
2. Quickly unselect Account A and Account B holding required tokens for membership permissions
3. See if error will be displayed 'This address does not contain tokens needed to join'

**Expected result:** 'This address does not contain tokens needed to join' should be displayed. 

**Actual result:** Eligible to join as Member is displayed.

[Status-debug-logs - 2024-03-26T194203.246.zip](https://github.com/status-im/status-mobile/files/14762492/Status-debug-logs.-.2024-03-26T194203.246.zip)

https://github.com/status-im/status-mobile/assets/97245802/64bc6d30-0dbf-441e-ae4a-a442399737d3

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19407

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs [hunk 1]
```diff
@@ -73,19 +73,25 @@
...
-    {:db (update db :communities/permissions-checks-for-selection dissoc community-id)}
-    {:db (assoc-in db [:communities/permissions-checks-for-selection community-id :checking?] true)
-     :fx [[:json-rpc/call
-           [{:method     :wakuext_checkPermissionsToJoinCommunity
-             :params     [{:communityId community-id :addresses addresses}]
-             :on-success [:communities/check-permissions-to-join-during-selection-success
-                          community-id]
-             :on-error   [:communities/check-permissions-to-join-during-selection-failure
-                          community-id addresses]}]]]}))
+  (let [request-id (hash addresses)]
```
Comment (cammellos) [inline src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs]: I think we should use either a random number or something else, `hash` of addresses seems a bit risky an a bit overloaded, though it should be fine

Comment (Parveshdhull) [reply src/status_im/contexts/communities/actions/addresses_for_permissions/events.cljs]: done, thank you

File: src/status_im/common/json_rpc/events.cljs [hunk 2]
```diff
@@ -83,8 +83,8 @@
                               (.-result response-js)
                               (transforms/js->clj (.-result response-js)))]
                  (if (vector? on-success)
-                   (rf/dispatch (conj on-success result))
-                   (on-success result)))))))))))
+                   (rf/dispatch (conj on-success result (.-id response-js)))
+                   (on-success result (.-id response-js))))))))))))
```
Comment (ilmotta) [inline src/status_im/common/json_rpc/events.cljs]: @Parveshdhull, the docstring is now outdated.

This part:

```
When a function, it will be called with the transformed response as the sole
argument. When a vector, it is expected to be a valid re-frame event vector,
and the event will be dispatched with the transformed response conj'ed at the
end.
```

**Review by ilmotta — APPROVED** [review]

File: src/status_im/common/json_rpc/events.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im/common/json_rpc/events.cljs]: updated, thank you

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the PR. Ready for merge.
