### PR TITLE
Various fixes for Contact Request flows (2nd attempt)

### LINKED ISSUE #15679: Contact Request issues
# Problem

Contact Request flows are incredibly difficult to get right, so more fixes are on the way in status-go from PR https://github.com/status-im/status-go/pull/3379.

Resolving this issue means to:

- [ ] Make sure status-mobile works well with the upcoming status-go changes.
- [ ] Stop using `wakuext_addContact`, prefer `wakuext_sendContactRequest`.

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/15679

### Summary

A quick and dirty PR that serves two purposes:

- [x] Make sure status-mobile works well with the upcoming status-go changes in PR https://github.com/status-im/status-go/pull/3379.
- [x] Replace calls to `wakuext_addContact` with `wakuext_sendContactRequest`. This is what's been aligned with the desktop team, as we will go on to remove `wakuext_addContact` in the near future.

Note: **Once this PR has been approved and tested by QAs, the status-go PR will be merged first**, business as usual, and I'll update the `status-go-version.json` file to point to an actual status-go tag.

### Out of scope

Refactoring; improvements in the existing code; UX.

#### Platforms

- Android
- iOS

### Steps to test (for QAs)

Contact request flows may be impacted. The status-go PR https://github.com/status-im/status-go/pull/3379 describes the changes being introduced, but perhaps for good measure all important CR flows should be double-checked in mobile.

status: ready

### CODE REVIEW

File: src/status_im/contact/chat.cljs [hunk 1]
```diff
@@ -11,7 +11,7 @@
   (let [{:keys [public-key ens-name]} new-identity]
     (rf/merge cofx
               #(if new-contact?
-                 (contact/add-contact % public-key nickname ens-name)
+                 (contact/send-contact-request % public-key)
```
Comment (ibrkhalil) [inline src/status_im/contact/chat.cljs:14]: `send-contact-request` expects one argument right ?

Comment (ilmotta) [reply src/status_im/contact/chat.cljs:14]: Confusing as it is this `rf/merge` keeps causing trouble... Anyway, the function `send-contact-request` is a special one, in the sense that it was defined by the macro `rf/defn` and it must be called with the first argument as the `cofx`.

Comment (ibrkhalil) [reply src/status_im/contact/chat.cljs:14]: Okay cool

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im2/contexts/contacts/events.cljs [hunk 2]
```diff
@@ -75,16 +75,20 @@
...
-                      :on-success  #(rf/dispatch [:sanitize-messages-and-process-response %])
-                      :on-error    #(log/error "failed to add contact" public-key %)}]}))
+(rf/defn send-contact-request
+  {:events [:contact.ui/send-contact-request]}
+  [{:keys [db]} id]
+  (when (not= id (get-in db [:multiaccount :public-key]))
+    {:json-rpc/call
+     [{:method      "wakuext_sendContactRequest"
+       :js-response true
+       :params      [{:id id :message "Please add me to your contacts"}]
```
Comment (J-Son89) [inline src/status_im2/contexts/contacts/events.cljs]: Should this message be i18n?

**Review by J-Son89 — APPROVED** [review]

**Review by yqrashawn — APPROVED** [review]

File: src/status_im2/contexts/contacts/events.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im2/contexts/contacts/events.cljs]: As of today (`develop`), the message was/is hardcoded in `status-go`, so I decided to keep it hardcoded in mobile as well since I believe sending contact requests will be redesigned at some point (?) But let me translate this real quick!

Edit: The screen that automatically sends the request with the hardcoded message is this one, and it'll be redesigned:

Comment (ilmotta) [reply src/status_im2/contexts/contacts/events.cljs]: Translation done :)

**Comment by qoqobolo** [comment]
Hi @ilmotta, could you update the `status-go-version.json` file to resolve a conflict, please?

**Comment by ilmotta** [comment]
> Hi @ilmotta, could you update the `status-go-version.json` file to resolve a conflict, please?

@qoqobolo, just rebased :) Thanks for reviewing this PR. I might be a bit slower today to reply, since I'm off.

It's worth mentioning that in PRs like this one, where the dev has changed `status-go-version.json` on purpose to point to a specific revision, the conflict Github points out is sort of meaningless, because when rebasing, the dev will always replace whatever comes from `develop` with the hardcoded status-go revision anyway. Therefore, if it's the only file Github is saying has a conflict, it's safe to ignore it's recommendation to rebase. Edit: this paragraph is only true while the PR is under test by you or other QAs because after the QA approval the dev should obviously rebase against `develop` before merging anything.

**Comment by qoqobolo** [comment]
> It's worth mentioning that in PRs like this one, where the dev has changed status-go-version.json on purpose to point to a specific revision, the conflict Github points out is sort of meaningless, because when rebasing, the dev will always replace whatever comes from develop with the hardcoded status-go revision anyway. Therefore, if it's the only file Github is saying has a conflict, it's safe to ignore it's recommendation to rebase. Edit: this paragraph is only true while the PR is under test by you or other QAs because after the QA approval the dev should obviously rebase against develop before merging anything.

Totally makes sense, thanks for the detailed explanation as always @ilmotta! 

Regarding the PR itself, found one issue so far that looks like a regression (testing is still in progress). Please take a look when you have time.

### ISSUE 1: `0x...` key is displayed  instead of a display name in the toast when your CR is accepted

**Steps to reproduce:**
1. UserA: send CR to UserB
2. UserB: accept CR
3. UserA: pay attention to the toast `[Username] accepted your contact request`

**Expected result:** the user's display name is shown in place of [Username]
**Actual result:** the key is shown instead

Screenshot 2023-04-21 at 16 46 11

---
Also, I have a question. 
In the [status-go PR description](https://github.com/status-im/status-go/pull/3379#issue-1655856015) I see two following points:

Screenshot 2023-04-21 at 17 38 05

However, on the mobile side, it currently doesn't work like that:
1. Chat only automatically appears on the CR sender's side 
5. The default CR message is still displayed at the top of the history for both users (screenshot below)

Screenshot 2023-04-21 at 17 29 23

Is it expected for now for mobile? Let me know, if we need to summon MishkaRogachev to clarify this.

**Comment by MishkaRogachev** [comment]
@qoqobolo thanks for testing!

1. We have quite similar [issue](https://github.com/status-im/status-desktop/issues/10400). But i suspect this is desktop application side issue. Contact details are null only for pending outgoing notification, other states work well.
2. Chat should appear for both sides, i've updated tests to ensure this working

**Comment by ilmotta** [comment]
> ISSUE 1: 0x... key is displayed instead of a display name in the toast when your CR is accepted

@qoqobolo, I swear I've seen ISSUE 1 happen in other branches a couple times, since I wasn't surprised when I read you reported ISSUE 1. I tried to reproduce now in `develop`, but I couldn't. Maybe my memory is playing tricks with me.

> The default CR message is still displayed at the top of the history for both users (screenshot below)

I wouldn't know that without further investigation @qoqobolo. Tbh I don't know what's the expected behavior either.

**Comment by qoqobolo** [comment]
Okay, now we have three points that need clarification/rechecking.

**1. ISSUE 1**

> I swear I've seen ISSUE 1 happen in other branches a couple times, since I wasn't surprised when I read you reported ISSUE 1. I tried to reproduce now in develop, but I couldn't. Maybe my memory is playing tricks with me.

Hmm, never seen this before the current PR. Asked other QAs, and they didn't see that either.
There used to be a bug where the toast displayed a 3-random name instead of a display name, that's the closest thing that comes to my mind.
@ilmotta can you check if this issue can be fixed here, please? Or I can log this separately as a follow-up after this PR is merged.  
WDYT?

---

And two mismatches between the behavior in current PR and the [status-go PR](https://github.com/status-im/status-go/pull/3379):

**2. Chat appears for both users after becoming mutual contacts**

@MishkaRogachev just fixed this issue in the status-go PR. @ilmotta  could you update this PR so I can test the fix on our side, please?

**3. No default CR message in chat should appear (currently, the default CR message is still displayed at the top of the history for both users on mobile)**

@cammellos could you help us define what is the expected behavior for mobile right now?
Should these go changes be applied to mobile in the current PR as well? Or we can add this behavior later (in which case I will file the issue separately).

---

Other than that, I didn't find any other issues, the PR looks good.

**Comment by cammellos** [comment]
@qoqobolo 3 can be addressed separately, we can clarify the behavior with the UX team.

2 should be addressed here, since @MishkaRogachev already made the changes I believe

1 probably we want to understand why it happens if we are to merge and just figure out if it's due to this PR or no

**Comment by qoqobolo** [comment]
Thank you @cammellos

**Comment by cammellos** [comment]
@ilmotta @MishkaRogachev regarding 1) I believe the code is using `Name` property in notification.

This is probably ok for toasts, since they are very ephemeral, but not ok for permanent notifications, as the name change (not sure whether we use it or not actually, but worth checking).

But this indicates that `Name` on a notification is probably the chat id, which is not what we want in most cases, @MishkaRogachev could you check in status-go with a test if that's the case?

Thank you

**Comment by MishkaRogachev** [comment]
> @ilmotta @MishkaRogachev regarding 1) I believe the code is using `Name` property in notification.
> 
> This is probably ok for toasts, since they are very ephemeral, but not ok for permanent notifications, as the name change (not sure whether we use it or not actually, but worth checking).
> 
> But this indicates that `Name` on a notification is probably the chat id, which is not what we want in most cases, @MishkaRogachev could you check in status-go with a test if that's the case?
> 
> Thank you

Sure, i will check that notification's name matches `contact.PrimaryName()` for all notifications related with contact requests

**Comment by ilmotta** [comment]
> Hmm, never seen this before the current PR. Asked other QAs, and they didn't see that either.

You're right @qoqobolo, maybe it was really just my mind playing tricks, or probably I've seen this issue while creating this PR and thought it existed in `develop` as well.

@MishkaRogachev and @qoqobolo, I've updated this PR to point to the latest revision from the status-go PR and tested on two devices. It seems ISSUE 1 is indeed fixed. I haven't tested the other issues though.

Thanks @cammellos for helping us understand what to do.

**Comment by MishkaRogachev** [comment]
> > Hmm, never seen this before the current PR. Asked other QAs, and they didn't see that either.

I suppose there can be more similar cases, when we expect `GetActivityCenterNotificationByID` will return notification with valid name. But we don't store name in the database. I don't have strong opinion on this subject because we don't use `Name` property of notification on the desktop

**Comment by qoqobolo** [comment]
Confirming that Issue 1 is fixed and chats appear on both sides now.
No other issues were found.
Thanks everyone for your awesome work @ilmotta @MishkaRogachev @cammellos!
PR can be merged.
