### PR TITLE
[#20571] fix: cleanup save address on mount

### LINKED ISSUE #20571: Scanned address doesn't contain chain on Add address screen
# Bug Report

#20475

### Steps:

- Login to app
- Go to Profile -> Wallet -> Saved addresses
- Tap on +
- Tap on scan icon
- Scan any QR that contain chains
- Tap Continue
- Look if your scanned address contains chain or not

*issue is not 100% reproducible but I could catch it if I change networks on network preferences of address that I am scanning, aprox 2-3 tries from 15-20 scans

More details https://github.com/status-im/status-mobile/pull/20475#issuecomment-2180400288

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #20571

### Summary

Cleanup save address and scanned address events in mount save address screen

#### Areas that maybe impacted

- Scan address to save address
- Edit saved address

### Steps to test

- Open profile setting
- Open Wallet setting
- Click on Saved adresses
- Click on +
- Click on Scan icon

status: ready

### CODE REVIEW

File: src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs [hunk 1]
```diff
@@ -161,7 +161,9 @@
                                                (rf/dispatch
                                                 [:open-modal :screen/settings.save-address]))
                                              [address ens-name? address-or-ens])]
-    (rn/use-unmount #(rf/dispatch [:wallet/clear-address-to-save]))
+    (rn/use-mount (fn []
+                    (rf/dispatch [:wallet/clean-scanned-address])
```
Comment (smohamedjavid) [inline src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs:167]: One small addition: I would suggest dispatching the same event before we take the user to the scanner page (in `on-scan-address`)

Comment (mohsen-ghafouri) [reply src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs:167]: @smohamedjavid Done

**Review by smohamedjavid — APPROVED** [review]
🚀

**Comment by qoqobolo** [comment]
Thanks for the fix @mohsen-ghafouri!
PR can be merged.

**Review by seanstrom — APPROVED** [review]
