### PR TITLE
[Fix] Scroll to bottom on editing a message

### LINKED ISSUE #16496: User is scrolled to the bottom of the chat after sending edited message
# Bug Report

## Problem 
Follow up on #16235 

#### Expected behavior
scroll should be remained at the edited message

#### Actual behavior
user is scrolled to the bottom of the chat

https://github.com/status-im/status-mobile/assets/97245802/1240a2e1-71ea-48a8-aec8-71a4d901ab54

### Reproduction

1. Scroll up to some of your previous messages in chat history
2. Edit and send updated message
3. See if user has been auto-scrolled to the bottom of the chat

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #16496

### Summary

This PR fixes (by skipping) the scroll to the bottom of messages when the user edits any message from the top of the chat.

### Platforms

- Android
- iOS

#### Prerequisites: Have at least one contact and a chat history with that contact.

- Open Status
- Open a chat with a long list of messages
- Try to edit a message from the top of the list
- Send the edited message
- Check whether the chat scrolls to the bottom.

status: ready

### CODE REVIEW

**Review by OmarBasem — APPROVED** [review]

File: src/status_im2/contexts/chat/composer/actions/view.cljs [hunk 1]
```diff
@@ -58,14 +59,14 @@
...
+     :on-press            #(send-message props state animations window-height edit)}
     :i/arrow-up]])
 
 (defn send-button
-  [props {:keys [text-value] :as state} animations window-height images?]
+  [props {:keys [text-value] :as state} animations window-height images? edit]
   (let [btn-opacity (reanimated/use-shared-value 0)
         z-index     (reagent/atom (if (and (empty? @text-value) (not images?)) 0 1))]
-    [:f> f-send-button props state animations window-height images? btn-opacity z-index]))
+    [:f> f-send-button props state animations window-height images? btn-opacity z-index edit]))
```
Comment (alwx) [inline src/status_im2/contexts/chat/composer/actions/view.cljs:69]: I'd say it's too many arguments at this point, probably better to move them to a map instead

**Review by alwx — APPROVED** [review]

File: src/status_im2/contexts/chat/composer/actions/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/chat/composer/actions/view.cljs:69]: I agree @alwx. We need to use a map. We will do the refactor separately as we need to do complete testing on messaging/composer.

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the PR! Tested and ready for merge.
