### PR TITLE
[Fixes: #11545] Don't update browser if nil

### LINKED ISSUE #11544: Error "v must satisfy IVector" if open a website in browser, tap back several times and open browser tabs
# Bug Report

## Problem

Error "v must satisfy IVector" appears if open a website, i.e. bbc.com, in the Status browser, tap back several times and then navigate to browser tabs. 

#### Expected behavior

No error

#### Actual behavior

ezgif com-gif-maker (16)

### Reproduction

- Open some website in Status browser, i.e. bbc.com
- Tap the back button until the Browser screen is open
- Tap the Tabs icon

### Additional Information

- Status version: Nightly 14/12
- Operating System: Android, iOS

### LINKED ISSUE #11545: Tab with the last viewed website appears after navigating to the Tabs view from the Browser screen on Android
# Bug Report

## Problem

"About:blank" tab appears if open browser tabs screen after installing the app, without navigating to any websites before.
If close it and re-login it will appear again.
If open a website in the Status browser, i.e. google.com, then navigate to the Tabs view, tap "Close all" or close the last viewed website, navigate to the Browser tab and return to the Tabs view, the tab with the last viewed website will appear in the list again.

#### Expected behavior

No tabs if the tab list was cleared before

#### Actual behavior

ezgif com-gif-maker (18)

### Reproduction

- Open google.com in the Status browser
- Tap the Tabs icon 
- Tap Close all
- Navigate to Browser screen
- Tap the Tabs icon 

### Additional Information

- Status version: Nightly 14/12
- Operating System: Android

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #11545
Fixes: #11544

The two issues were caused by the same bug, essentially if
`navigation-state-changed` event was fired (it's debounced) when the tab
had been closed, the browser would be updated with a `nil` id, causing
all sort of issues as it had not history etc.

This commit ensures that no changes are made if the browser is nil.

### Testing

Tabs usage, I have little context on the feature, so I just verified it works more or less as it did before.

status: ready

### CODE REVIEW

File: src/status_im/browser/core.cljs [hunk 1]
```diff
@@ -189,12 +189,13 @@
...
-                      (assoc browser
-                             :history new-history
-                             :history-index new-index)))))
+    (when history
+      (let [new-history (conj (subvec history 0 (inc history-index)) url)
+            new-index   (dec (count new-history))]
+        (update-browser cofx
+                        (assoc browser
+                               :history new-history
+                               :history-index new-index))))))
```
Comment (shivekkhurana) [inline src/status_im/browser/core.cljs:198]: This can be condensed using `when-let`

```clojure
(when-let [history (:history browser)]
  (let [history-index ...
        new-history ...
        new-index ...]
    ...))
```

**Review by shivekkhurana — APPROVED** [review]
