### PR TITLE
Fix slow scrolling on chat screen

### LINKED ISSUE #16185: [Android] Scroll starts lagging in a chat with a long message
### Bug Description:
After leaving or performing long tap-on reactions in a long message, the app experiences a lag and slow performance.

### Steps to Reproduce:
1. Open a chat conversation with a long message 
2. Leave all reactions on the message
3. Perform a long tap on a few reactions in the message.
4. Tap each reaction randomly on the 'who sent' screen
5. Scroll the message that is shown upper of 'who sent' screen
6. Observe the app's performance.

### Actual Result:
Upon leaving, long-tapping the reactions on a message or tapping the reactions within 'who sent' page, the app lags and exhibits noticeable performance degradation

https://github.com/status-im/status-mobile/assets/52490791/6649be0f-d040-4981-8922-bfaa5d0856e7

### Expected Result:
The app should remain responsive and perform smoothly after interacting with reactions.

### Device:
- Real device: Pixel 7a, Android 13

### ENV:
Nightly 5 Jun 2023

### PR DESCRIPTION
**Pull request by rasom**
fix #16185 

This is a known RN issue, it was already fixed by @flexsurfer in the old implementation but still had to be added to a new one.

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
@VladimrLitvinenko @qoqobolo 

That is not a fix at the moment, but I want to verify whether that problem with inverted flat list is related. Here the list of messages will not be reverted (thus new messages on the top), but please check scrolling on that Pixel device and let me know how it works.

Thanks!

**Comment by qoqobolo** [comment]
Scrolling is smooth in this PP in chats with large messages on my Pixel, no lagging, works great.
Thanks @rasom

**Comment by rasom** [comment]
@qoqobolo could you please test it once again on a new build?

**Comment by qoqobolo** [comment]
> @qoqobolo could you please test it once again on a new build?

Looks even creepier, but still works fast.

**Comment by rasom** [comment]
@qoqobolo I'm sorry I forgot to push changes which should fix creepiness. The next build should look better

**Comment by rasom** [comment]
@qoqobolo should be ready now

**Comment by qoqobolo** [comment]
@rasom still good in the latest build https://github.com/status-im/status-mobile/commit/46ad5d66a3f23350f42c9f29a1283562f8c719f7

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 1]
```diff
@@ -184,7 +184,10 @@
                                                      [30 125]
                                                      [14 0]
                                                      header-extrapolation-option)]
-    [rn/view {:flex 1}
+    [rn/view
+     (cond-> {:flex 1}
+       platform/android?
+       (assoc :scaleY -1))
```
Comment (alwx) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: why `cond->` though? isn't it easier to do something like `{:flex 1 :scaleY (if platform/android? -1 1)}`?

(same goes for everything else below)

**Review by alwx — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/list/view.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im2/contexts/chat/messages/list/view.cljs]: Well technically the nesting level is the same, the number of words is the same. One pair of brackets instead of another magic value. I see very little difference and I prefer `cond->` here.

Comment (rasom) [reply src/status_im2/contexts/chat/messages/list/view.cljs]: just extracted it to a separate fn

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 2]
```diff
@@ -166,6 +166,13 @@
   [props]
   [:f> f-list-footer-avatar props])
 
+;;TODO(rasom) https://github.com/facebook/react-native/issues/30034
+(defn- add-inverted-y-android
+  [style]
+  (cond-> style
+    platform/android?
+    (assoc :scaleY -1)))
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: I believe we can use kebab case here.

**Comment by qoqobolo** [comment]
LGTM, thanks for the fix @rasom!
