### PR TITLE
[#20971] fix: app crash when collectible max limit is nan

### LINKED ISSUE #20971: [IOS] App doesn't respond after ERC 1155 collectible is attempting to be send
Unfortunately this issue happens randomly, no exact step to reproduce it. Hope the logs might help
### Steps:
1. Scan wallet QR using a universal scanner
2. Go to collectible send flow 
3. Select any ERC 1155 collectible

### Actual result:
- The collectible is shown with NaN and without an image.
- The app does not respond.

https://github.com/user-attachments/assets/d28f0f5e-7993-45c8-a499-dba7d1a33cf3

### Expected Result:
The collectible should be displayed with the correct information and image.

### Devices:
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (2).zip](https://github.com/user-attachments/files/16520805/logs.2.zip)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #20971

### Summary

App doesn't respond after ERC 1155 collectible is attempting to be send

#### Platforms

- iOS

#### Areas that maybe impacted

- Send Collectible 

### Steps to test

- Scan wallet QR using a universal scanner
- Go to collectible send flow
- Select any ERC 1155 collectible

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Review by alwx — APPROVED** [review]

File: src/status_im/contexts/wallet/collectible/utils.cljs [hunk 1]
```diff
@@ -6,11 +6,12 @@
...
-  (-> collectible
-      :ownership
-      first
-      :balance
-      js/parseInt))
+  (let [balance (-> collectible
+                    :ownership
+                    first
+                    :balance
+                    js/parseInt)]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/collectible/utils.cljs:13]: can use `utils.number/parse-int` helper, that already has 0 as a default

**Review by clauxx — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanks for the fix. Ready for merge and cherrypicking. cc @churik @cammellos

**Comment by ilmotta** [comment]
FYI: @mohsen-ghafouri, corresponding PR to update our release branch is open https://github.com/status-im/status-mobile/pull/20998 and waiting for this PR to be merged first, so we can cherry-pick.

File: src/status_im/contexts/wallet/collectible/utils.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/utils.cljs:13]: Sorry i saw it late, as QA already tested, i will try to apply it in next PR

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/utils.cljs:13]: oh btw `integer?` condition didn't help to catch ##NAN, this was only workaround.

**Comment by mohsen-ghafouri** [comment]
@ilmotta merged.

File: src/status_im/contexts/wallet/collectible/utils.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/collectible/utils.cljs:13]: @mohsen-ghafouri, if possible, could you share an example where `integer?` doesn't work? `(parse-int js/NaN)` returns the default value 0 as expected.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/utils.cljs:13]: I see, i used `integer?` without using parse-int so it didn't work
