### PR TITLE
[fix #3057] fix chat-contact.identity must be of type string error

### LINKED ISSUE #3057: Error chat-contact.identity must be of type 'string', got 'object' shown for group chat members after new member is added
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: Error ```chat-contact.identity must be of type 'string', got 'object' (['0x0428c9d6c1aaaa8369a7c63819684f30e34396dc0907d49afeac85a0a774ccb919b3482097d992e66bcc538e7a0c6acf874c77748f396f53c0a102e10d1a37765b'])``` is shown to all group chat members after admin added new member. If close the error then can continue using the app
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New member is added, info about X added Y is shown in the group chat,
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error message is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Add 1 contact, it should add you as a contact too
- Create group chat with that 1 contact
- send some hi message
- edit Settings and add Jarrad to the group members
- check on other device if there any error shown

From 1:08 https://app.testfairy.com/projects/4803622-status/builds/7512524/sessions/4/?accessToken=RBWKtxNivaRwMwIAr-8P4tzzhgU

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release build 56 and nightly build for Jan 16
[comment]: # Android and iOS
real devices Galaxy S6 and iPhone 6s. Android 6.0.1, iOs 10.33.3

### PR DESCRIPTION
**Pull request by yenda**
fixes #3057
status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Comment by oskarth** [comment]
@yenda guessing you used this to experiment or something? Seems like the it got auto closed when remove-jenkins-hack branch was deleted/closed - would you mind updating it? Can't seem to reopen it (presumably because target branch is gone)

File: src/status_im/protocol/handlers.cljs [hunk 1]
```diff
@@ -179,19 +179,19 @@
 
 (re-frame/reg-fx
   ::participant-invited-to-group-message
-  (fn [{:keys [chat-id current-identity identity from message-id timestamp]}]
+  (fn [{:keys [group-id current-identity identity from message-id timestamp]}]
```
Comment (oskarth) [inline src/status_im/protocol/handlers.cljs:184]: Can you explain this change? I thought chat-id was used for "group id" as well. Can we check for presence of these in pre condition maybe?

File: src/status_im/protocol/handlers.cljs [hunk 2]
```diff
@@ -495,13 +495,12 @@
...
     (let [admin (get-in chats [group-id :group-admin])]
       (when (= from admin)
-        (merge
-          {::participant-invited-to-group-message {:group-id group-id :current-public-key current-public-key
-                                                   :identity identity :from from :message-id message-id
-                                                   :timestamp timestamp}}
-          (when-not (and (= current-public-key identity) has-contact?)
-            {:db (update-in db [:chats group-id :contacts] conj {:identity identity})
-             ::chats-add-contact [group-id [identity]]}))))))
+        (merge {::participant-invited-to-group-message {:group-id group-id :current-public-key current-public-key
```
Comment (oskarth) [inline src/status_im/protocol/handlers.cljs:510]: This is a bit hard to read, has anything materially changed here? If no, can we leave it alone? If yes, can we maybe put some of this stuff in lets / use threading etc?

**Review by oskarth — COMMENTED** [review]
Small changes so if it fixes problems that's good, just some comments/questions

File: src/status_im/protocol/handlers.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/protocol/handlers.cljs:184]: it comes from the event I changed below, group-id is in the payload not chat-id, maybe @janherich knows better I just fixed it because chat was empty and after fixing the initial bug I was getting the system messages such as "x added y" into a random chat (probably the default one for a nil public address)

File: src/status_im/protocol/handlers.cljs (hunk 2 above)
Comment (yenda) [reply src/status_im/protocol/handlers.cljs:510]: the last statement: identity was in a vector before

File: src/status_im/protocol/handlers.cljs (hunk 1 above)
Comment (janherich) [reply src/status_im/protocol/handlers.cljs:184]: @oskarth for protocol communication, `:chat-id` is present in 1-1 chats and `:group-id` in group chats payloads (with no `:chat-id` in payload).
I think that our data model in app-db (for chats) and protocol messages is unnecessary complicated and could be simpler and less error prone. 
It seems like it started by having `1-1` chat's and then "bolting" on additional data for group chats, without reconsidering it.
Imho just `:chat-id` everywhere with optional flag `:group?`/`:public?` would be totally sufficient.

Comment (oskarth) [reply src/status_im/protocol/handlers.cljs:184]: > :chat-id is present in 1-1 chats and :group-id in group chats payloads (with no :chat-id in payload).

Seems very error prone. Can we turn this into a pre-condition in this PR? As well as make a bounty to fix code base wide?

> Imho just :chat-id everywhere with optional flag :group?/:public? would be totally sufficient.

Agree, I think this could also be bounty. Suspect changing app db schema like this is a bit more work than just adding pre-conditions to catch this class of bug (hence suggesting two bounties, even though this would likely at least partially replace need for former).

Comment (janherich) [reply src/status_im/protocol/handlers.cljs:184]: @oskarth I actually planned to do it while I was refactoring the message model (together with delivery status updates, so touching protocol as well), but the problem is that any changes in protocol will either make:

* Older app version incompatible with newer app version
* Introduce a lot of special handling in newer version which has to except protocol messages from older and newer app version alike (so checking for both `:chat-id` and `:group-id`...)

Given that bloated code and accidental complexity is enemy number 1, I decided against it, unless we drop the constraint of supporting everything we developed in the past (realm migrations are similar case) :)

Comment (oskarth) [reply src/status_im/protocol/handlers.cljs:184]: >  planned to do it
> problems

Guessing you refer to bounty 2 here, not 1. Yes agree, I think this is why it is long-term, we can figure out best upgrade path. But we can skip bounty 2 and only do bounty 1 if it isn't worth it.

> unless we drop the constraint of supporting everything we developed

We could consider this, but I think with a better upgrade store (realm read app start, better use of realm) then it should be specced pure function and errors at startup if we can't go from S0 -> S1.

**Comment by yenda** [comment]
@oskarth since it is fixing the problem can we move it to test and leave the code improvement/fixing root cause to another PR/bounty ?

**Comment by oskarth** [comment]
@yenda Yes sure

**Comment by asemiankevich** [comment]
----------------
Branch: PR-3063
Android: https://i.diawi.com/4V3Puy
iOS: https://i.diawi.com/mtBANM
