### PR TITLE
[#16437] fix sync qr code not recognized after trying again

### LINKED ISSUE #16437: Android can't be synced when scanning sync QR code if 'try again' button is tapped, until the 'sync QR page' is refreshed
### Steps to Reproduce:
1. Generate an invalid QR code (the sync code which has been already used)
2. Navigate to the sync QR page using the Android
3. Point the camera at the sync QR code.
4. Tap the 'Try Again' button when the 'Oops something wrong' is shown
5. Point the camera at the sync QR code again

### Actual Result:
After tapping the 'Try Again' button, the sync process does not proceed when the camera is pointed on the sync QR code again 

https://github.com/status-im/status-mobile/assets/52490791/44b041e4-049e-4b75-bad6-2ec5840cddf7

### Expected Result:
When the 'Try Again' button is tapped, the sync process should resume and attempt to sync the Android device with the QR code. 

### Note:
 The issue prevents successful syncing when the 'Try Again' button is tapped, and the sync QR page must be manually reopened

### Devices:
- Real device: Pixel 7a, Android 13
- Real device: Huawei p20 light, Android 9

### ENV:
Nightly [27 Jun 2023]

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #16437

### Summary

This PR solves the problem of the QR code not being recognized after the attempt failed and the user pressed the "try again" button.

### Review notes
This PR has important refactoring changes and the solution involves subscribing this component to the lifecycle react methods provided by react native navigation:
https://wix.github.io/react-native-navigation/7.25.4/api/events/#registercommandlistener

I added a helper function, that I'd like it to be a macro to make things easier, but I'm not sure, since adding a macro could make developer lifes harder sometimes, so I want to get your opinion. Please read the comments in the code of this PR.

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

- Onboarding
- Create a new account

### Steps to test

Generate a valid but expired QR code for syncing, you can use this:
image

- Open Status in a fresh install
- Click  Sign in button
- Scan the code using the phone/emulator
- An error will be shown
- Click try again button
- You are now able to rescan the code again.

status: ready

### CODE REVIEW

File: src/react_native/navigation.cljs [hunk 1]
```diff
@@ -89,3 +89,8 @@
          (reset! constants {:top-bar-height     (.-topBarHeight consts)
                             :bottom-tabs-height (.-bottomTabsHeight consts)
                             :status-bar-height  (.-statusBarHeight consts)})))
+
+(defn bind-component
+  [^js/Object this component-id]
+  (set! (. this -navigationEventListener)
+    (.. Navigation events (bindComponent this component-id))))
```
Comment (ulisesmac) [inline src/react_native/navigation.cljs:96]: This function allow us to create a react class and use the react-native-navigation lifecycle methods to detect when a component has appeared or disappeared from user's screen

File: src/status_im2/contexts/syncing/scan_sync_code/animation.cljs [hunk 2]
```diff
@@ -0,0 +1,61 @@
+(ns status-im2.contexts.syncing.scan-sync-code.animation
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/animation.cljs:1]: Just moved the animation code from `view` to this namespace, since it was hard to read ther. I hope now it's clearer

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 3]
```diff
@@ -48,8 +50,8 @@
   []
   (rf/dispatch [:syncing/preflight-outbound-check #(reset! preflight-check-passed? %)]))
 
-(defn- f-header
-  [{:keys [active-tab read-qr-once? title title-opacity subtitle-opacity reset-animations-fn animated?]}]
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs:40]: `read-qr-once?` was an atom to control the callbacks dispatched by the camera-kit component, it dispatched the `on-read` function many times before we navigated.

Now it's not required

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 4]
```diff
@@ -119,12 +121,7 @@
         :data           [{:id 1 :label (i18n/label :t/scan-sync-qr-code)}
                          {:id 2 :label (i18n/label :t/enter-sync-code)}]
         :on-change      (fn [id]
-                          (reset! active-tab id)
-                          (reset! read-qr-once? false))}]]]))
-
-(defn- header
-  [props]
-  [:f> f-header props])
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: We don't need this wrapper, we use `:f>` wrappers to expose an API, for internal component use, we can directly use  the `:f>` call

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 5]
```diff
@@ -255,136 +252,102 @@
...
+(defn- check-qr-code-and-navigate
+  [event set-qr-code-succeeded]
   (let [connection-string        (string/trim (oops/oget event "nativeEvent.codeStringValue"))
         valid-connection-string? (sync-utils/valid-connection-string? connection-string)]
     (if valid-connection-string?
-      (debounce/debounce-and-dispatch [:syncing/input-connection-string-for-bootstrapping
-                                       connection-string]
-                                      300)
+      (do
+        (set-qr-code-succeeded)
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: `set-qr-code-succeeded` is a function that will change a control atom, we need it to not scanning the qr code more than once.

The behaviour is similar to the  previous `read-qr-once?`  atom, but now it is handled by the `compnentDidAppear` method

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 6]
```diff
@@ -255,136 +252,102 @@
...
+      :on-read-code #(check-qr-code-and-navigate % set-qr-code-succeeded)}]]
+   [hole-view/hole-view
+    {:style style/hole
+     :holes [(merge qr-view-finder {:borderRadius 16})]}
+    [blur/view
+     {:style            style/absolute-fill
+      :blur-amount      10
+      :blur-type        :transparent
+      :overlay-color    colors/neutral-80-opa-80
+      :background-color colors/neutral-80-opa-80}]]])
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: Small refactor:

This `render-camera` component has a `when` and it could return `nil`. Instead of creating a component that is returning nil, now `render-camera` always renders the camera, and the condition to show it or not is when calling it.

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 7]
```diff
@@ -255,136 +252,102 @@
...
 
-(defn f-view
-  [{:keys [title show-bottom-view? background animated?]}]
-  (let [insets             (safe-area/get-insets)
-        active-tab         (reagent/atom 1)
-        qr-view-finder     (reagent/atom {})
-        render-camera?     (reagent/atom false)
-        torch?             (reagent/atom false)
-        app-state-listener (atom nil)]
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs:272]: We don't need this `app-state-listener` atom, explanation below

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 8]
```diff
@@ -255,136 +252,102 @@
...
+(defn- reset-animations-and-navigate-fn
+  [{:keys [render-camera? show-camera?] :as params}]
+  (letfn [(reset-fn []
+            (rf/dispatch [:navigate-back])
+            (when @dismiss-animations (@dismiss-animations))
+            (animation/reset-animations params))]
     (fn []
-      (let [camera-ref (atom nil)
-            read-qr-once? (atom false)
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: These atoms shouldn't be declared in the render function since they will be recreated in each render

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 9]
```diff
@@ -255,136 +252,102 @@
...
-        qr-view-finder     (reagent/atom {})
-        render-camera?     (reagent/atom false)
-        torch?             (reagent/atom false)
-        app-state-listener (atom nil)]
+(defn- reset-animations-and-navigate-fn
+  [{:keys [render-camera? show-camera?] :as params}]
+  (letfn [(reset-fn []
+            (rf/dispatch [:navigate-back])
+            (when @dismiss-animations (@dismiss-animations))
+            (animation/reset-animations params))]
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs:279]: Refactor: just extracted the animations to a separate function to make the reading of the main view function easier

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 10]
```diff
@@ -255,136 +252,102 @@
...
-            content-opacity (reanimated/use-shared-value (if animated? 0 1))
-            content-translate-y (reanimated/interpolate subtitle-opacity [0 1] [85 0])
+      (reset! render-camera? false)
+      (js/setTimeout reset-fn (if show-camera? 500 0)))))
+
+(defn- set-listener-torch-off-on-app-inactive
+  [torch-atm]
+  (let [set-torch-off-fn   #(when (not= % "active") (reset! torch-atm false))
+        app-state-listener (.addEventListener rn/app-state "change" set-torch-off-fn)]
+    #(.remove app-state-listener)))
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs:288]: Again a refactor. just extracted this effect callback to a separate function

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 11]
```diff
@@ -255,136 +252,102 @@
...
-                                                              0
-                                                              :easing4))
-               (if show-camera? 500 0)))]
-        (rn/use-effect (fn []
-                         (reset! app-state-listener
-                           (.addEventListener rn/app-state
-                                              "change"
-                                              #(when (and (not= % "active") @torch?)
-                                                 (reset! torch? false))))
-                         #(.remove @app-state-listener)))
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs:330]: About the `app-state-listener` atom removal:

it's not required to be an atom, just a `let` binding:

```clojure
(let [res (.addEventListener something "something else" fn-callback)]
  #(.remove res))
```

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 12]
```diff
@@ -434,5 +403,14 @@
...
+  (let [qr-code-succeed? (reagent/atom false)]
+    (navigation.util/create-class-and-bind
+     "sign-in-intro"
+     {:component-did-appear (fn set-qr-code-failed [_this]
+                              (reset! qr-code-succeed? false))}
+     (fn [props]
+       (let [new-pops (assoc props
+                             :qr-code-succeed?      @qr-code-succeed?
+                             :set-qr-code-succeeded #(reset! qr-code-succeed? true))]
+         [:f> f-view new-pops])))))
```
Comment (ulisesmac) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: This is the important part of the solution:

I am using the new helper function I mentioned in this PR description. as I said before, I'd like it to be a macro.

It will reset the atom `qr-code-suceeed?` to `false` each time this screen is shown to the user, so we can read the code again.

In react-native-navigation, the screen components are not unmounted when we navigate to another screen within the same stack, it means:
- the Cleanup function in `use-effect`
- the `finally` statement in `with-let`
- the componentWillUnmount() method

will not be called until the screen is detached from navigation hierarchy, but in cases like this (where we want to go back and we expect the screen state is reset) we need to use the `componentDidAppear` method given by `react-native-navigation`.

Now that this has been noticed, I think we will start using these extended lifecycle methods more often, so I decided to create a helper function.

File: src/status_im2/navigation/util.cljs [hunk 13]
```diff
@@ -0,0 +1,42 @@
+(ns status-im2.navigation.util
```
Comment (ulisesmac) [inline src/status_im2/navigation/util.cljs:1]: I didn't know where to add this new function without adding dependency problems, so I created this namespace.

Please take a look at the function and give any feedback you think will enhance it.

Do you think a macro would be good?
we could avoid repetition and I like it, but at the same time, I don't like existing macros like `defview` that we had in the previous codebase since they add a layer of complexity to our components.
wdyt? :thinking:

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs (hunk 8 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: @ulisesmac - The `on-read-code` function from the `react-native-camera-kit` library is called as long as a QR code is in the frame of the camera (or the user is focusing on it). To prevent this, we added the `read-qr-once?` atom within the render and reset it after 3 seconds on a successful read.

This also allows the user to scan any QR code after 3 seconds if they accidentally scanned the wrong one. 

The present code will result in endless error toasts if the user scans a wrong PR.

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 14]
```diff
@@ -434,5 +403,14 @@
              flashlight-icon])]]))))
 
 (defn view
-  [props]
-  [:f> f-view props])
+  [_props]
+  (let [qr-code-succeed? (reagent/atom false)]
+    (navigation.util/create-class-and-bind
+     "sign-in-intro"
```
Comment (smohamedjavid) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: I believe the name should be received in a prop because we use this view (as the screen) in two places:

1. Sign In
2. Scan sync code

Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: Should we match it with the name declared in `screens.cljs`?
https://github.com/status-im/status-mobile/blob/eb3de978cef417673fabe21eb1c60fc72f905e27/src/status_im2/navigation/screens.cljs#L210

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs (hunk 8 above)
Comment (J-Son89) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: Hmm, is there any way to add a unit test (component spec fine) to ensure this feature is retained?

Comment (ulisesmac) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: @smohamedjavid 
The present code is using a different approach without using the atom in the render function and also fixing the bug for this issue.

What would be a wrong QR?
Do you know if that endless toast behavior is reproducible in this branch? Could you please tell me how to reproduce it?

Thank you so much!

Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: @ulisesmac 

> What would be a wrong QR?

A QR code which is NOT a sync QR (QR data would start with `cv2:`). 

> Do you know if that endless toast behavior is reproducible in this branch? Could you please tell me how to reproduce it?

Yes, Kindly download and install this PR build (https://github.com/status-im/status-mobile/pull/16746#issuecomment-1646374593) into your device. Point your device at any QR code from the internet.

It doesn't need to be a wrong QR. The camera library fires the `on-read-code` method (with QR data) as long as a QR is in focus. This will happen with the correct sync QR too (initiates the local pairing repeatedly by calling the native module as long as a Correct Sync QR is in focus).

<hr />

I fixed a similar issue https://github.com/status-im/status-mobile/issues/15970 (PR: https://github.com/status-im/status-mobile/pull/16012) with the help of `view-id` in `app-db`.

Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: > Hmm, is there any way to add a unit test (component spec fine) to ensure this feature is retained?

I don't know as this is a ratom inside render (not a prop). But, I will see if we can add a check. 

P.S. I would add a comment explaining why we need it.

Comment (ulisesmac) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: @smohamedjavid 

The problem I see with a non-reactive atom within the render function is that we are not able to know what's the value stored by the atom: Let's say we reset the atom, then we `deref` it, if a re-render happens just before, our value will be missed.

Thanks for noticing this case, I didn't test with a wrong QR (so bad).

I added a reagent  control atom to avoid multiple calls to `on-read` (not inside the render function), also the toast call is using `debounce-and-dispatch` in the same way that when we are navigating. :+1: 

The commit where I added is 2279613f7f249bc90eecc3c8c8d90e00bb829358,
please review again and approve if this is ok for you, otherwise we can check what else is missing :)

Thanks!

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs (hunk 14 above)
Comment (ulisesmac) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: Done, the `screen-name` is received as a parameter

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs (hunk 8 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs:275]: This seems to be working fine. 👍 

Thanks, @ulisesmac!

**Review by smohamedjavid — APPROVED** [review]

**Comment by churik** [comment]
@ulisesmac 
after scanning invalid QR > try again I was redirected to success screen (both IOS and Android)

Example of QR:
invalid_qr


Actual result: 

https://github.com/status-im/status-mobile/assets/4557972/2b3f09c3-de73-4a41-884e-62c38c7097e6

**Comment by ulisesmac** [comment]
> @ulisesmac after scanning invalid QR > try again I was redirected to success screen (both IOS and Android)
> 
> Example of QR: invalid_qr
> 
> Actual result:
> FILE.2023-07-28.14.38.21.mp4

Hi @churik 
Could you please share the QR used to test? I tried with the given QR and I couldn't replicate the issue.

Also, is this an issue present in develop or introduced in this PR? since this PR is not touching the code of clicking that button.

Thanks!

**Comment by churik** [comment]
Ok, may be I misunderstood something, but I followed the steps mentioned in https://github.com/status-im/status-mobile/issues/16437

I used QR mentioned https://github.com/status-im/status-mobile/pull/16746#issuecomment-1655623200 and I got the same behavior in nightly and in this PR (so Sign In > Scan QR > Try again > Syncing - nothing happens, I cannot scan QR again)
image
Reproducible **only on Android.** (apologies for not mentioning it earlier)

**Comment by ulisesmac** [comment]
> Ok, may be I misunderstood something, but I followed the steps mentioned in #16437
> 
> I used QR mentioned [#16746 (comment)](https://github.com/status-im/status-mobile/pull/16746#issuecomment-1655623200) and I got the same behavior in nightly and in this PR (so Sign In > Scan QR > Try again > Syncing - nothing happens, I cannot scan QR again) image Reproducible **only on Android.** (apologies for not mentioning it earlier)

Hello again @churik 

I tested this flow on develop. I selected  the option "Add existing Status profile" on the "Profiles on device" screen and I replicated the issue you mentioned. So it seems this flow is broken on develop, that's not related to this PR, so let's create an issue if it doesn't exist yet.

To test this PR, you can open Status in a fresh install and select the "sign in" option. I updated the PR's description and added a QR to test, but it can also be replicated with the QR you added.

Could you please test it again? thanks!

**Review by jo-mut — APPROVED** [review]

**Comment by churik** [comment]
@ulisesmac 
Now in this PR:

1) Sign in
2) Scan QR provided in the description here: https://github.com/status-im/status-mobile/pull/16746#issue-1816530045 - Nothing happens.

https://github.com/status-im/status-mobile/assets/4557972/a23241ac-d891-4e21-8214-3b5f60815723

Logs: 
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/12260355/Status-debug-logs.1.zip)

Also from the video here: https://github.com/status-im/status-mobile/pull/16746#issuecomment-1655623200 I can see that I repeated exact steps from description: https://github.com/status-im/status-mobile/pull/16746#issue-1816530045, so frankly still not sure what I was doing wrong here in order to reproduce the issue

**Comment by ulisesmac** [comment]
> @ulisesmac 
> 
> Now in this PR:
> 
> 
> 
> 1) Sign in
> 
> 2) Scan QR provided in the description here: https://github.com/status-im/status-mobile/pull/16746#issue-1816530045 - Nothing happens.
> 
> 
> 
> https://github.com/status-im/status-mobile/assets/4557972/a23241ac-d891-4e21-8214-3b5f60815723
> 
> 
> 
> Logs: 
> 
> [Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/12260355/Status-debug-logs.1.zip)
> 
> 
> 
> Also from the video here: https://github.com/status-im/status-mobile/pull/16746#issuecomment-1655623200 I can see that I repeated exact steps from description: https://github.com/status-im/status-mobile/pull/16746#issue-1816530045, so frankly still not sure what I was doing wrong here in order to reproduce the issue
> 
> 

Hmmm... 🤔 I will check, thanks!

**Comment by ulisesmac** [comment]
> > @ulisesmac
> > Now in this PR:
> > 
> > 1. Sign in
> > 2. Scan QR provided in the description here: [[#16437] fix sync qr code not recognized after trying again #16746 (comment)](https://github.com/status-im/status-mobile/pull/16746#issue-1816530045) - Nothing happens.
> > 
> > 
> >   
> >     
> >     
> > 
> >     FILE.2023-08-04.13.49.30.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > Logs:
> > [Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/12260355/Status-debug-logs.1.zip)
> > Also from the video here: [#16746 (comment)](https://github.com/status-im/status-mobile/pull/16746#issuecomment-1655623200) I can see that I repeated exact steps from description: [#16746 (comment)](https://github.com/status-im/status-mobile/pull/16746#issue-1816530045), so frankly still not sure what I was doing wrong here in order to reproduce the issue
> 
> Hmmm... thinking I will check, thanks!

@churik  A quick update on this.
The screen is not stuck, something is actually happening, but it takes too long (I guess is something related to a network timeout).
This issue is also happening on `develop`, the only one difference is that on develop the camera remains active and on this branch, I'm turning off the camera once the code has been recognized (to avoid multiple code recognitions).
I'm reproducing the issue you mention in develop in the following video:

https://github.com/status-im/status-mobile/assets/90291778/bbf80a98-27dc-4514-a5fc-57b84a571d19



I think it's still possible to test this PR (maybe with another QR, or using the one you posted as example), and we can report these problems as separate issues. It seems this flow has to be carefully reworked, but it wasn't the original scope of this issue/PR.

**Comment by churik** [comment]
Ok, seems I finally managed to test the flow, as it seems that if I scan Pr from https://github.com/status-im/status-mobile/pull/16746#issue-1816530045 it can stuck in processing like https://github.com/status-im/status-mobile/pull/16746#issuecomment-1665982732 and if I try to scan invalid QR after (which I posted here https://github.com/status-im/status-mobile/pull/16746#issuecomment-1664635378) I got an error > and then after try again I redirected to the `Syncing device` (like https://github.com/status-im/status-mobile/pull/16746#issuecomment-1655623200)

It is OK if these are separate issues, let's merge this one and I re-test flow and report several more issues.
