### PR TITLE
Biometrics button on login screen

### LINKED ISSUE #17996: Login - add biometric auth button on login screen when user has biometrics on a given account
Currently if the user has biometrics set for a given account and tries to login to that account it will attempt to login using biometrics immediately, however if this fails there is no way to retrigger this at the moment. 

See the designs https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2854-301456&mode=design&t=0uP54u0Cy92NvvJ7-4

### PR DESCRIPTION
**Pull request by clauxx**
fixes #17996

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
When logging in, there should be a biometry button (if enabled) next to the password input. Also, when _switching_ to a profile with enabled biometry, the biometric check will be triggered automatically as shown in the [Figma flow](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=4357-629774&mode=design&t=BQMm19QBvOvDm0UD-4).

#### Platforms

- Android
- iOS

##### Functional

- login
- switch profile
- biometry

status: ready

### CODE REVIEW

File: src/status_im2/contexts/profile/login/events.cljs [hunk 1]
```diff
@@ -180,18 +180,22 @@
   {:keychain/get-auth-method [key-uid
                               #(rf/dispatch [:profile.login/get-auth-method-success % key-uid])]})
 
+(rf/reg-event-fx
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/login/events.cljs]: could you elaborate? this looks strange

File: src/status_im2/contexts/profile/events.cljs [hunk 2]
```diff
@@ -27,6 +27,13 @@
             {:db (assoc db :profile/profiles-overview profiles)}
             (profile-selected key-uid)))
 
+(rf/reg-event-fx
+ :profile/switch-profile
+ (fn [{:keys [db]} [key-uid]]
+   {:db db
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/events.cljs]: :db db is redundant

File: src/status_im2/contexts/profile/events.cljs [hunk 3]
```diff
@@ -27,6 +27,13 @@
...
+    :fx [[:dispatch [:profile/profile-selected key-uid]]
```
Comment (flexsurfer) [inline src/status_im2/contexts/profile/events.cljs]: same here, its better just dispatch in the view no need in the `:profile/switch-profile` event

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im2/common/standard_authentication/password_input/view.cljs [hunk 4]
```diff
@@ -29,19 +30,30 @@
 (defn- view-internal
   [{:keys [default-password theme shell?]}]
   (let [{:keys [error processing]} (rf/sub [:profile/login])
+        auth-method                (rf/sub [:auth-method])
```
Comment (J-Son89) [inline src/status_im2/common/standard_authentication/password_input/view.cljs]: In my pr I was passing this in as a prop 🤔 No strong preferences, we could keep this input purer however and pass everything in as a prop 🤔 https://github.com/status-im/status-mobile/pull/17992/files

File: src/status_im2/contexts/profile/login/events.cljs [hunk 5]
```diff
@@ -218,8 +222,7 @@
  (fn [{:keys [db]} [code]]
    (let [key-uid (get-in db [:profile/login :key-uid])]
      {:db db
-      :fx [[:dispatch [:init-root :profiles]]
-           (if (= code "NOT_ENROLLED")
+      :fx [(if (= code "NOT_ENROLLED")
```
Comment (J-Son89) [inline src/status_im2/contexts/profile/login/events.cljs]: should we have these NOT_ENROLLED etc saved as constants somewhere?

**Review by J-Son89 — APPROVED** [review]
looks good to me

File: src/status_im2/common/standard_authentication/password_input/view.cljs (hunk 4 above)
Comment (clauxx) [reply src/status_im2/common/standard_authentication/password_input/view.cljs]: I'd say unless it's used higher in the tree, mught be better to use the sub directly where it's used. I see very often 'subscription' maps passed as props all over the place, even when a sub is needed in one single child somewhere down the tree. What do you think?

Comment (J-Son89) [reply src/status_im2/common/standard_authentication/password_input/view.cljs]: For me it's fine either way 👍

File: src/status_im2/contexts/profile/login/events.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im2/contexts/profile/login/events.cljs]: When logging in, we need `:biometric/authenticate` with the same success/fail callbacks in two different places, so the dispatch was moved in a separate event so it can be re-used. Removed it in favor of using `:biometric/authenticate` directly in the view.

File: src/status_im2/common/standard_authentication/password_input/view.cljs [hunk 6]
```diff
@@ -49,6 +49,7 @@
          {:container-style style/auth-button
           :on-press        on-press-biometrics
           :icon-only?      true
+          :background      :blur
```
Comment (J-Son89) [inline src/status_im2/common/standard_authentication/password_input/view.cljs]: this should probably be passed as a prop and defaulted to false. wdyt? I think in some flows this could be incorrect 🤔

File: src/status_im2/contexts/profile/profiles/view.cljs [hunk 7]
```diff
@@ -206,8 +208,14 @@
         :profile-picture     profile-picture
         :card-style          style/login-profile-card}]
       [standard-authentication/password-input
-       {:shell?           true
-        :default-password password}]]
+       {:shell?              true
+        :on-press-biometrics (fn []
```
Comment (J-Son89) [inline src/status_im2/contexts/profile/profiles/view.cljs]: is this correct? Have you handled the case where biometrics fails -> password input shows, then you press biometric authenticate again and let it fail -> password input shows then you press biometric authenticate again ... (to infinity :) )

File: src/status_im2/common/biometric/constants.cljs [hunk 8]
```diff
@@ -0,0 +1,6 @@
+(ns status-im2.common.biometric.constants)
```
Comment (flexsurfer) [inline src/status_im2/common/biometric/constants.cljs]: we have status-im2.constants for all constants

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/common/standard_authentication/password_input/view.cljs (hunk 6 above)
Comment (clauxx) [reply src/status_im2/common/standard_authentication/password_input/view.cljs]: The text input has `:blur?` enabled as well. Do we have cases where the input is used without the blur?

File: src/status_im2/contexts/profile/profiles/view.cljs (hunk 7 above)
Comment (clauxx) [reply src/status_im2/contexts/profile/profiles/view.cljs]: Not sure I understand the flow 😄

Comment (J-Son89) [reply src/status_im2/contexts/profile/profiles/view.cljs]: I might be wrong let me test out your branch 😀

**Review by siddarthkay — APPROVED** [review]

File: src/status_im2/common/standard_authentication/password_input/view.cljs (hunk 6 above)
Comment (J-Son89) [reply src/status_im2/common/standard_authentication/password_input/view.cljs]: here is the designs for syncing auth - https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=1112-146720&mode=design&t=ioE4htigtApMxrtn-4 
which is in blur and in this it has it.

for wallet:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2340-519746&mode=design&t=JoUGHMyoLfjV00Ay-4

in wallet it is not using blur
Screenshot 2023-12-11 at 14 35 08

**Comment by churik** [comment]
@clauxx please, rebase your PR to current develop, thanks!

**Comment by clauxx** [comment]
@churik sorry I found some issues in this PR. Removing it from QA for now.

**Comment by clauxx** [comment]
@churik fixed the issues and aligned with develop. It's moved to E2E now.

**Comment by churik** [comment]
@clauxx Thank you for your work!
I do not see the issues in these particular flows, tried using with and without biometric authentication on defferent flows (account creation / restore / sync) on both Android and IOS.

e2e failures are not related to particular PR.

@Francesca-G 
Steps to see the change:
- create multi-account (with biometric auth enabled)
- close the app
- fail to login (so in case of Face ID point your phone to the wall, and when "Auth failed" appears, tap on "Cancel")
- create a new account with no  biometric auth enabled
- manual log out
- if you switch to the first one, the biometric check will be triggered automatically

**Review by Francesca-G — APPROVED** [review]
looks good ✨
