### PR TITLE
Wallet: token input conversion

### LINKED ISSUE #18499: Send flow: input amount screen incorrect rate conversion
On the send input screen, 2 props passed to the screen: `rate limit` seem to be always nil https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/send/input_amount/view.cljs#L57

This causes conversion result when input is in fiat to be incorrect.

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/18499, https://github.com/status-im/status-mobile/issues/18538

This PR fixes the coversion rate from crypto to fiat used in the token input component.

Also fixes the crypto decimal places used in the token input component.

https://github.com/status-im/status-mobile/assets/29354102/6c1a4948-35fe-4b64-a171-e7768159999a

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

File: src/quo/components/wallet/token_input/view.cljs [hunk 1]
```diff
@@ -14,11 +14,13 @@
     [reagent.core :as reagent]))
 
 (defn calc-value
-  [crypto? currency token value conversion]
+  [crypto? currency token value conversion crypto-decimals]
```
Comment (J-Son89) [inline src/quo/components/wallet/token_input/view.cljs]: We should avoid functions with 3+ positional args, better to use a map imo

File: src/quo/components/wallet/token_input/view.cljs [hunk 2]
```diff
@@ -14,11 +14,13 @@
...
   (let [num-value (if (string? value) (parse-double (or value "0")) value)]
     (if crypto?
       (str (get common/currency-label currency) (.toFixed (* num-value conversion) 2))
-      (str (.toFixed (/ num-value conversion) 2) " " (string/upper-case (or (clj->js token) ""))))))
+      (str (.toFixed (/ num-value conversion) (or crypto-decimals 2))
```
Comment (J-Son89) [inline src/quo/components/wallet/token_input/view.cljs]: Imo it would be nice to separate the two functions of the if,
e. calc-crypto and calc-fiat 
So it's
(if crypto?
   (calc-crypto ...)
   (calc-fiat ...))
And just reads nicely 👌

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 3]
```diff
@@ -65,6 +65,12 @@
              "")
            ""))))
 
+(defn get-crypto-decimals-count
+  [{:keys [market-values-per-currency]}]
+  (let [price          (get-in market-values-per-currency [:usd :price])
+        one-cent-value (if (pos? price) (/ 0.01 price) 0)]
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/common/utils.cljs:71]: Should price be a big number?

Cc @ulisesmac

**Comment by pavloburykh** [comment]
@OmarBasem thanks for the PR. 

Could you please provide some details on this fix? 

> Also fixes the crypto decimal places used in the token input component.

Can you show with screenshot examples how it was before the fix and how it is now? So far it is not clear for me what has been changed in terms of this fix. Thank you!

**Comment by OmarBasem** [comment]
Hi @pavloburykh,

Both fixes are for the same component in the video.

> This PR fixes the coversion rate from crypto to fiat used in the token input component.

If you try to send a token you would notice the conversion rate when you switch fiat/crypto on that screen is currently incorrect.

> Also fixes the crypto decimal places used in the token input component.

Currently if you choose to send ETH for example you would see on that screen that ETH is shown using so many decimal places. That current behaviour incorrect.

If something is still unclear please let me know

**Comment by pavloburykh** [comment]
> If something is still unclear please let me know

Thanks for the answer @OmarBasem! Just curious why would we want to limit decimals amount on send token screens? In this case - it will not show the accurate amount of tokens. Where do we get the requirements on how many decimals we should show? 

For example, in this PR we show 5 decimals for ETH and 2 decimals for DAI though both tokens may have 18 decimals. 

Sorry, maybe I have missed some discussion on this topic, would appreciate if you share the links if such exist. I need this info to be sure in expected result otherwise my testing can not be valid. The [Designs](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=8599-130208&mode=design&t=VwI6dYDyCRF0pVIW-0) are showing 2 decimals for ETH which is completely weird.

**Comment by pavloburykh** [comment]
@OmarBasem meanwhile I have faced the issue and I am not sure if it is PR related. I cannot  reproduce it on nightly.

### ISSUE 1 Cannot read property 'eq' of null error when selecting token for sending (Android)

So far reproducing only on Android (Samsung Galaxy A52, Android 12)

**Steps:** 

1. Recover user with tokens
2. Open wallet - Send - My accounts - Select account - Select token
3. Observe the result

**Actual result:** Cannot read property 'eq' of null error appears. It does not happen every time. 

[Status-debug-logs (95).zip](https://github.com/status-im/status-mobile/files/13976926/Status-debug-logs.95.zip)
photo_2024-01-18 15 03 52

https://github.com/status-im/status-mobile/assets/97245802/351c7013-9190-4609-86b9-e2eb6baa2a69





**Expected result:** no error

**Comment by pavloburykh** [comment]
> > If something is still unclear please let me know
> 
> Thanks for the answer @OmarBasem! Just curious why would we want to limit decimals amount on send token screens? In this case - it will not show the accurate amount of tokens. Where do we get the requirements on how many decimals we should show?
> 
> For example, in this PR we show 5 decimals for ETH and 2 decimals for DAI though both tokens may have 18 decimals.
> 
> Sorry, maybe I have missed some discussion on this topic, would appreciate if you share the links if such exist. I need this info to be sure in expected result otherwise my testing can not be valid. The [Designs](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=8599-130208&mode=design&t=VwI6dYDyCRF0pVIW-0) are showing 2 decimals for ETH which is completely weird.

@OmarBasem **UPDATE:** I have found this info https://github.com/status-im/status-desktop/issues/8640  Will consider it to be a source of truth.

**Comment by OmarBasem** [comment]
> @OmarBasem UPDATE: I have found this info https://github.com/status-im/status-desktop/issues/8640 Will consider it to be a source of truth.

@pavloburykh Yeah that's the information. Btw, this information comes from status-go so you don't have to worry about math details.

Regarding issue 1, is this issue reproducible on develop cause we are facing a similar issue on develop in debug mode (a crash after selecting token which doesn't happen everytime) and there is currently another PR that should fix it https://github.com/status-im/status-mobile/pull/18532

**Comment by pavloburykh** [comment]
@OmarBasem thank you for clarification. PR is ready to be merged.

File: src/status_im/contexts/wallet/common/utils.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/common/utils.cljs:71]: Yeah, I think `price` should be. 

JS numbers' implementation sometimes have an unexpected behaviour. since we are dealing with money, better to be safe :+1:

Comment (689886sali) [reply src/status_im/contexts/wallet/common/utils.cljs:71]: Yeah, I think price should be.

JS numbers' implementation sometimes have an unexpected behaviour. since we are dealing with money, better to be safe 👍
