### PR TITLE
[Fix] Seen state in Activity Center when it is open

### LINKED ISSUE #16306: The notification badge does not appear gray on the AC bell when a message is received while the AC is open
### Steps to Reproduce:
1. Open the Activity Centre.
2. Keep the Activity Centre open.
3. Receive a new message.
4. Close AC
5. Check the notification badge

### Actual Result:
When a new message is received while the AC is open, the notification badge on the AC bell does not appear gray. It remains in the unread color

https://github.com/status-im/status-mobile/assets/52490791/fc341191-9953-4612-990e-2d6dac96bc08

### Expected Result:
When a new message is received while the AC is open, the notification badge on the AC bell should appear gray.
image

### ENV:
- Nightly 19 Jun 2023

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #16306

### Summary

This PR fixes the seen state of notifications if the user is in the Activity Center screen while receiving a new notification.

### Platforms

- Android
- iOS

### Areas impacted

- Activity Center

### Steps to test

- Open Status
- Navigate to the Activity Center
- Keep the Activity Center open
- Receive any Activity Center notification (Contact Request, Mentions, Replies,...etc)
- Close the Activity Center
- Check the colour of the unread counter on the Notification Bell Icon

status: ready

### CODE REVIEW

File: src/status_im2/contexts/shell/activity_center/events.cljs [hunk 1]
```diff
@@ -102,7 +102,10 @@
 (rf/defn reconcile-seen-state
   {:events [:activity-center/reconcile-seen-state]}
   [{:keys [db]} seen?]
-  {:db (assoc-in db [:activity-center :seen?] seen?)})
+  (cond-> {:db (assoc-in db [:activity-center :seen?] seen?)}
+
+    (= (:view-id db) :activity-center)
```
Comment (J-Son89) [inline src/status_im2/contexts/shell/activity_center/events.cljs:107]: I understand using `view-id` can be necessary but it is so prone to introducing simple bugs. I think it's best to cover this with a test 👍

**Review by siddarthkay — APPROVED** [review]
except for existing comment this PR looks good to me!

**Review by J-Son89 — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]
Good one @smohamedjavid!
