### PR TITLE
[#21389] fix: display correct amount without rounding

### LINKED ISSUE #21389: Incorrect max value rounding on routes generation page (Bridge and Send pages)
### Steps:
1. Recover a user with available assets that require rounding (e.g., 1.149 DAI in my case).
2. Go to the routes generation page in the send or bridge flow.
3. Check the max value displayed.

### Actual result:
The max value is rounded up (e.g., 1.149 DAI is rounded to 1.15), confusing the user. So, when the user enters 0.96, they receive an incorrect error message: "Fee greater than estimated."

Image

### Expected result:
The max value should be rounded down (e.g., to 1.14) to avoid confusing the user about the sum he owns

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21389

## Summary

Display correct amount without rounding

### Areas that may be impacted

- Send and Bridge

## Steps to test

1. Recover a user with available assets that require rounding (e.g., 1.149 DAI in my case).
2. Go to the routes generation page in the send or bridge flow.
3. Check the max value displayed.

### Result 

https://github.com/user-attachments/assets/5cb5f5c9-f74f-46e2-b3a5-075ba1a2e587

status: ready

### CODE REVIEW

File: src/utils/number.cljs [hunk 1]
```diff
@@ -97,3 +97,18 @@
   [num decimal-count]
   (let [decimal-part (second (string/split (str num) #"\."))]
     (or (nil? decimal-part) (<= (count decimal-part) decimal-count))))
+
+(defn format-decimal-fixed
```
Comment (vkjr) [inline src/utils/number.cljs:101]: Thanks for adding a docstring! 🙏

**Review by vkjr — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri,

We have an additional issue related to rounding when the balance is displayed in fiat currency. However, other dApps also do not allow sending such values and handle it through validation.

Perhaps we should consider handling it as well, though maybe not within the scope of the current PR. What do you think?
### Steps:
1. Go to send set up flow
2. Set up balances showing in fiat
3. Enter max value

### How it works in Status:

https://github.com/user-attachments/assets/64eac335-6758-4018-93b4-948f80eb00ef

### How it works in MM:

https://github.com/user-attachments/assets/89bf9729-90dd-4ce2-bf08-687a51a373e6

**Comment by VolodLytvynenko** [comment]
@Mohsen-Ghafouri No other issues from my side. The case mentioned in [this comment](https://github.com/status-im/status-mobile/pull/22272#issuecomment-2721078439) can be considered a separate task and fixed separately. PR can be merged

**Comment by mohsen-ghafouri** [comment]
Thanks @VolodLytvynenko, yes now that both QA and reviewers approved this PR already, i will take care of that case in separate issue. 
https://github.com/status-im/status-mobile/issues/22291
