### PR TITLE
Add contact form fixes (#405)

### LINKED ISSUE #405: Add Contact Form Broken
In latest `develop` it seems the add contact form has broken?

add-new-contact-form

### PR DESCRIPTION
**Pull request by alwx**
Fixes #405

screen shot 2016-11-03 at 00 17 27

### CODE REVIEW

File: src/status_im/contacts/views/new_contact.cljs [hunk 1]
```diff
@@ -89,22 +91,24 @@
...
-   [view
-    [status-bar]
-    [toolbar {:background-color :white
-              :nav-action       {:image   {:source {:uri :icon_back}
-                                           :style  icon-back}
-                                 :handler #(dispatch [:navigate-back])}
-              :custom-content   toolbar-title
-              :actions          (toolbar-actions new-contact-identity account error)}]]
+   [status-bar]
+   [toolbar {:background-color toolbar-background1
```
Comment (jarradh) [inline src/status_im/contacts/views/new_contact.cljs]: could `toolbar-background1` be more descriptive?
