### PR TITLE
Back button doesn't work on recover screen Bug/#675

### LINKED ISSUE #675: Back button doesn't work on recover screen
Back button in top left corner does not return users to login screen.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/112
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/150
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/112

### PR DESCRIPTION
**Pull request by flexsurfer**
The reason of this bug
```
; add accounts screen to history ( maybe there is a better way ? )
  (dispatch [:navigate-to-clean :accounts])
```

should be a better way, I think better to add :accounts key into the :navigation-stack at the app initialization, but i don't know app's structure well, so, it needs to be refactored i think

fixes #675

### CODE REVIEW

**Comment by jarradh** [comment]
thanks @flexsurfer !

**Comment by rasom** [comment]
https://github.com/status-im/status-react/issues/675#issuecomment-271140741 i'm a bit confused by this comment. And I just tried back button on recover screen in `develop` and it works fine. Is there any problem with back button and how can it be reproduced in `develop`?

**Comment by flexsurfer** [comment]
@rasom  the problem is , there is no recover screen in the :navigation-stack, it will be added on each action, for example on login screen opening etc. so if you go to login screen then back and then to recover it works, but if you go to recover immediately after app initialization, recover screen will not be added in  :navigation-stack and back button will not work

**Comment by flexsurfer** [comment]
@rasom i don't know maybe was a reason to do not add :acoounts in the :navigation-stack on the app initialization, just then there would be no reason to call each time (dispatch [:navigate-to-clean :accounts])

**Comment by rasom** [comment]
ok, i see, thanks. 

> should be a better way, I think better to add :accounts key into the :navigation-stack at the app initialization, but i don't know app's structure well, so, it needs to be refactored i think

^ that's a better idea, we just need something like this
```clojure

(def default-view :accounts)

(def app-db {
             ...
             :view-id                    default-view
             :navigation-stack           (list default-view)
             ...})
```

**Comment by rasom** [comment]
> accounts->recovery->back
^ this scenario doesn't work right after launching app, when `:navigation-stack` is empty

That's why I mentioned changes to `app-db`, and there is a chance that we need to make only this changes to fix the problem.

File: src/status_im/accounts/handlers.cljs [hunk 1]
```diff
@@ -129,11 +129,13 @@
   (let [accounts (->> (accounts-store/get-all)
                       (map (fn [{:keys [address] :as account}]
                              [address account]))
-                      (into {}))]
+                      (into {}))
+        view (if (empty? accounts)
```
Comment (flexsurfer) [inline src/status_im/accounts/handlers.cljs]: we can't add default view in the app-db, because we decide here which view will be first, so on the first launch it will be :chat

File: src/status_im/accounts/screen.cljs [hunk 2]
```diff
@@ -43,8 +43,6 @@
 
 (defn create-account [event]
   (dispatch-sync [:reset-app])
-  ; add accounts screen to history ( maybe there is a better way ? )
-  (dispatch [:navigate-to-clean :accounts])
```
Comment (flexsurfer) [inline src/status_im/accounts/screen.cljs]: and this dispatch  is superfluous

File: src/status_im/accounts/views/account.cljs [hunk 3]
```diff
@@ -12,7 +12,6 @@
             [status-im.accounts.styles :as st]))
 
 (defn on-press [address]
-  (dispatch [:navigate-to-clean :accounts])
```
Comment (flexsurfer) [inline src/status_im/accounts/views/account.cljs]: and this dispatch is superfluous

**Comment by flexsurfer** [comment]
> accounts->recovery->back
> ^ this scenario doesn't work right after launching app, when :navigation-stack is empty
i've tested all , 1)account creation from scratch - works well

**Comment by rasom** [comment]
Oh ok, I mixed up the device, sorry.
