### PR TITLE
[#12684] Messages disappear from Timeline if join public chat and ope…

### LINKED ISSUE #12684: Messages disappear from Timeline if join public chat and open Timeline tab while public chat history is loading
# Bug Report

## Problem 

If post a message to Timeline, join a public chat, and quickly navigate to the Timeline tab while public chat history is loading, then timeline messages disappear when public chat history is loaded.
If send another message to Timeline or re-open the Timeline tab, the messages will be restored.

#### Actual behavior

https://user-images.githubusercontent.com/67952253/135993184-3f78e0c7-266b-41b0-ac55-b9c3ea9988ac.mp4

### Reproduction

1. Post smth to Timeline
2. Open the home screen and join a public chat, e.g. #status
3. Quickly navigate to the Timeline tab

### Additional Information

- Status version: nightly 5/10
- Operating System: Android, iOS

[geth.log](https://github.com/status-im/status-react/files/7284408/geth.log)
[Status.log](https://github.com/status-im/status-react/files/7284410/Status.log)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #12684

### CODE REVIEW

File: src/status_im/contact/core.cljs [hunk 1]
```diff
@@ -39,27 +39,35 @@
...
-                           (conj [::contact.block/contact-blocked contact chats])
-
-                           (contact.db/blocked? db public-key)
-                           (conj [::contact.block/contact-unblocked public-key])))
-                       contacts)})
+  (let [{:keys [events offload]}
+        (reduce
+         (fn [acc {:keys [public-key] :as contact}]
+           (cond-> acc
+             (and (:added contact) (not (get-in db [:contacts/contacts public-key :added])))
```
Comment (rasom) [inline src/status_im/contact/core.cljs]: Can we extract `(:added contact)` to `added` and `(get-in db [:contacts/contacts public-key :added])` to `was-added` to make conditions a bit more readable?

Comment (rasom) [reply src/status_im/contact/core.cljs]: same for `blocked`/`was-blocked`

File: src/status_im/contact/core.cljs [hunk 2]
```diff
@@ -39,27 +39,35 @@
...
+
+             (and (:blocked contact) (not (contact.db/blocked? db public-key)))
+             (-> (update :events conj [::contact.block/contact-blocked contact chats])
+                 (assoc :offload true))
+
+             (and (contact.db/blocked? db public-key) (not (:blocked contact)))
+             (-> (update :events conj [::contact.block/contact-unblocked public-key])
+                 (assoc :offload true))))
+         {:events []
+          :offload false}
```
Comment (rasom) [inline src/status_im/contact/core.cljs]: Can it just be replaced with `(seq events)`? Apparently if there is at least one event `:offload` is always `true`. That would also simplify code inside `reduce`.

File: src/status_im/contact/core.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/contact/core.cljs]: sure

File: src/status_im/contact/core.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/contact/core.cljs]: if contact was removed there is no event

Comment (flexsurfer) [reply src/status_im/contact/core.cljs]: i also don't like this code, but didn't find a better way

Comment (rasom) [reply src/status_im/contact/core.cljs]: > if contact was removed there is no event

but it is `true` in all causes now, no?

Comment (rasom) [reply src/status_im/contact/core.cljs]: oh I see

Comment (flexsurfer) [reply src/status_im/contact/core.cljs]: ok `:dispatch-n` should ignore nil., so we could add nil for contact removal case

Comment (rasom) [reply src/status_im/contact/core.cljs]: We also could just use set instead of vector for events and then adding multiple `[:offload-messages constants/timeline-chat-id]` wouldn't be an issue.

Comment (flexsurfer) [reply src/status_im/contact/core.cljs]: ok i found even better solution

Comment (flexsurfer) [reply src/status_im/contact/core.cljs]: @rasom check it now

File: src/status_im/contact/core.cljs [hunk 3]
```diff
@@ -39,27 +39,34 @@
...
+             (cond-> acc
+               (and added (not was-added))
+               (conj [:start-profile-chat public-key])
+
+               (and blocked (not was-blocked))
+               (conj [::contact.block/contact-blocked contact chats])
+
+               (and was-blocked (not blocked))
+               (conj [::contact.block/contact-unblocked public-key]))))
+         [[:offload-messages constants/timeline-chat-id]]
```
Comment (rasom) [inline src/status_im/contact/core.cljs:61]: I still think that a set instead of vector and explicit adding of `[:offload-messages constants/timeline-chat-id]` when it is really necessary would be better

Comment (flexsurfer) [reply src/status_im/contact/core.cljs:61]: but it really necessary for all cases, so it will be just duplicated for each condition, and will be noisy

Comment (rasom) [reply src/status_im/contact/core.cljs:61]: ok, I see. In code you just added there is no `(and (not added) was-added)` cause, we don't need it?

Comment (flexsurfer) [reply src/status_im/contact/core.cljs:61]: we need it, fixed

**Review by rasom — APPROVED** [review]
