### PR TITLE
[#21669] [iOS] "Oops, this is not a Keycard" screen appears if user d…

### LINKED ISSUE #21669: [iOS] "Oops, this is not a Keycard" screen appears if user didn't scan his card properly
# Bug Report
https://github.com/status-im/status-mobile/pull/21623

## Problem 
[comment]: # (A problem description)

Scanning during the final step before redirecting to the app takes longer (3-5 seconds) compared to the initial step of the Sign up with Keycard flow.

This delay causes an issue where users, assuming the scanning process has frozen, may lose patience and move or remove their card prematurely during the scanning process. In case such situation occurs we have an issue described below.

### Reproduction

1. `Factory reset` keycard or use empty one.
2. Open Status > Create profile > Use Keycard
3. In the Create profile on empty Keycard screen, press `Scan Keycard`
4. In the Keycard is empty screen, press `Let's go!` to create a new profile.
5. Backup recovery phrase and continue.
6. Create pin
7. In the Ready to add key pair to Keycard screen, press` Ready to Scan`
8. Do not wait till the card is scanned and take it away after 1 sec of scanning
9. Scan card once more

#### Expected behavior

User can use ` Ready to Scan` option and scan his card successfully

#### Actual behavior

1. User sees "Oops, this isn`t a Keycard" screen
2. User shouldn't remove his PIN in case he somehow returns to the PIN screen, PIN should be empty.

https://github.com/user-attachments/assets/ce6a3552-61c6-418c-89d9-642103cd1f24

### Additional Information

- Status version: (https://github.com/status-im/status-mobile/pull/21623)
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21669

for QA: please test on ios and Android, keycard library has been updated to latest version

### CODE REVIEW

File: src/status_im/contexts/keycard/nfc/sheets/events.cljs [hunk 1]
```diff
@@ -1,28 +1,23 @@
...
            [:show-nfc-sheet nil]]}
      {:effects.keycard.ios/start-nfc
-      {:on-success
-       (fn []
-         (log/debug "nfc started successfully. next: show-connection-sheet")
-         (rf/dispatch [:keycard.ios/on-start-nfc-success args]))
-       :on-failure
-       (fn []
-         (log/debug "nfc failed star starting. not calling show-connection-sheet"))}})))
+      {:on-success #(rf/dispatch [:keycard.ios/on-start-nfc-success args])}})))
```
Comment (seanstrom) [inline src/status_im/contexts/keycard/nfc/sheets/events.cljs:15]: Should we also dispatch an event for the failure case? Perhaps we can show a toast or display something to suggest nfc is not working?

**Review by seanstrom — APPROVED** [review]
Nice stuff, left one comment about adding some error handling 👍

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer !

PR is tested on both platforms.
I didn't catch issue anymore.
Fill free to merge.

**Review by siddarthkay — APPROVED** [review]
