### PR TITLE
fix: reply with album

### LINKED ISSUE #15318: Image is shown as a separate message if current image is sent as a reply
#### Steps to reproduce:
1. Go to any chat
2. Sent the message
3. Long tap the message -> tap 'reply' option -> attach the image
4. Tap 'send' button

#### Actual result:
The image is shown as a separate message

https://user-images.githubusercontent.com/52490791/220424838-07785378-ae50-4487-afd2-c79a45313ab8.mp4

#### Expected result:
The image is shown as a reply

#### Env: 
Nightly: 13 Mar 2023

### PR DESCRIPTION
**Pull request by yqrashawn**
resolve #15318

reason

1. no `:response-to` in image message when mobile->go (do we support reply with image before album added?)
2. no `:response-to` (in `:content`) in `albumize-messages` when build `:message-list` from `:messages` 

status: ready

### CODE REVIEW

File: src/status_im2/subs/chat/messages.cljs [hunk 1]
```diff
@@ -112,27 +112,37 @@
...
+                                                            :deleted? (:deleted? message)
+                                                            :deleted-for-me? (:deleted-for-me? message)
+                                                            :deleted-by (:deleted-by message)
+                                                            :from (:from message)
+                                                            :timestamp-str (:timestamp-str message)
+                                                            :content-type constants/content-type-album}
+                                                           response-to
+                                                           (assoc-in [:content :response-to] response-to)
+                                                           quoted-message
+                                                           (assoc :quoted-message quoted-message)))
```
Comment (OmarBasem) [inline src/status_im2/subs/chat/messages.cljs]: why `assoc`? You can add them to the map like the rest of the keys right? (for consistency)

Comment (yqrashawn) [reply src/status_im2/subs/chat/messages.cljs]: fixed

**Review by OmarBasem — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by pavloburykh** [comment]
@yqrashawn thanx for the fix. Ready to be merged.
