### PR TITLE
fix: jump-to button positioning

### LINKED ISSUE #19980: Jump to overlaps last asset item in the list on Wallet screen
Looks like leftover from https://github.com/status-im/status-mobile/pull/19732 cc @OmarBasem 

**Steps:** 

1. Login account with long list of assets
2. Open wallet tab
3. Scroll assets list to the bottom
4. Pay attention at Jump to button location

**Actual result:** 

https://github.com/status-im/status-mobile/assets/97245802/1076a6cc-17e0-47f8-a15d-df020ff23eff

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19980

### Summary
This PR fixes regression from https://github.com/status-im/status-mobile/pull/19831 that caused jump-to button to overlap with list items

Also fixes jump-to position on account where it was positioned at `0` from the bottom

### CODE REVIEW

File: src/status_im/contexts/wallet/home/view.cljs [hunk 1]
```diff
@@ -86,25 +86,26 @@
...
+                                   :metrics           :none
+                                   :balance           formatted-balance
+                                   :networks          networks
+                                   :dropdown-on-press #(rf/dispatch [:show-bottom-sheet
+                                                                     {:content network-filter/view}])}]
+                                 (when (ff/enabled? ::ff/wallet.graph)
+                                   [quo/wallet-graph {:time-frame :empty}])
+                                 [render-cards cards account-list-ref]
+                                 [render-tabs tabs-data set-selected-tab selected-tab]]
+       :content-container-style style/list-container
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/home/view.cljs:107]: That line is the only change in this block: `:content-container-style style/list-container`

**Review by ibrkhalil — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Thanks for your fix.
Looks good from my side.
Failed e2e are not related.

You can merge your PR 🙌
