### PR TITLE
Fix chat UI element colors

### LINKED ISSUE #18830: The colors of elements in channel are not dependent on the color of selected channel/community
### Steps:
1. Create a community using Desktop by selecting a particular color (e.g., yellow).
2. Create a channel without selecting any color for the current chat.
3. Create channels for the community by selecting a particular color (e.g., red).
4. Open both chats.

### Actual result:
The elements such as 'pin messages' and 'mute chat' sections within the opened channels are always blue, regardless of the color selected for current channel
image

### Expected result:
- The elements such as 'pin messages' and 'mute chat' sections within the opened channels should correspond to the color of the channel. 
- If the channel color is not selected, then the color should correspond to the color of the community.
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16878-284491&mode=design&t=7Tn1KyOImK6WxCdl-0

### ENV:
Nightly [14 Feb 2024]

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #18830 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

This PR attempts resolve the issue described in #18830 where the mobile chat UI uses the incorrect color for chat/channels when viewing the chat/channel messages. The cause of the issue seems to be related to a color constant being passed around instead of the correct chat/channel color or community color.

### Testing notes

This PR attempts to use the community color as a fallback color when the chat color may not be present. However, I'm not sure how to create a channel without a color, so I'm not able to manually test that scenario. But the code has been written to support using the community color if the chat color is missing, which aligns with the suggested behavior described in #18830.

#### Platforms

- Android
- iOS

##### Functional

- community chats
- 1-on-1 chats
- other chats?

### Steps to test

A few pieces are needed to setup the test scenario for this PR. The steps for reproducing the issue are based on the ones in #18830.

1. Create a Community on Status desktop (and choose a community color)
2. Create a chat/channel on Status desktop (and choose a chat color)
3. Invite the Status mobile user to the created community and join the community on mobile
4. Open community on mobile and view the created community chat/channel

### Before and after screenshots comparison

The attached screen captures will showcase an existing community with a configured color, and some existing chat/channels with their own configured colors. Note, there may be an unrelated bug when displaying the community chat-list view where the colors don't match their channel colors. If this is a bug, I will create a separate issue for it soon.

#### Before Chat Color Fixes

https://github.com/status-im/status-mobile/assets/2845768/19ab919c-8450-4585-9875-b9b030264677

#### After Chat Color Fixes 

https://github.com/status-im/status-mobile/assets/2845768/869d2f38-2e01-4c5f-a1aa-2d1d21be3f5b

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 1]
```diff
@@ -185,8 +186,8 @@
                                 messages.constants/top-bar-height
                                 messages.constants/header-container-top-margin)
         background-color     (colors/theme-colors
-                              (colors/custom-color cover-bg-color 50 20)
-                              (colors/custom-color cover-bg-color 50 40)
+                              (colors/custom-color chat-color 50 20)
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Hi @seanstrom - I think we deprecated `custom-color`. instead if you can use `resolve-color method.
The end result should be 
```
      (colors/resolve-color chat-color theme 20)
       (colors/resolve-color chat-color theme 40)
```

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 2]
```diff
@@ -285,10 +286,11 @@
     (reset! distance-atom new-distance)))
 
 (defn f-messages-list-content
-  [{:keys [insets distance-from-list-top content-height layout-height cover-bg-color distance-atom
+  [{:keys [insets distance-from-list-top content-height layout-height distance-atom
            chat-screen-layout-calculations-complete? chat-list-scroll-y]}]
   (let [theme                    (quo.theme/use-theme-value)
         chat                     (rf/sub [:chats/current-chat-chat-view])
+        community-color          (rf/sub [:communities/community-color (:community-id chat)])
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Hi @seanstrom, Thank you very much for fixing this.

Please can we use something like this,
```
community-channel?  (= constants/community-chat-type chat-type) ;; Move from Line 141 here
customization-color (if community-channel?
                      (rf/sub [:communities/community-color (:community-id chat)])
                      :turquoise) ;; TODO - Needs to update
```
This screen is also used for 1-1 chats, and we probably also need to customize this color for 1-1 and until then we should use some fallback

File: src/status_im/subs/communities.cljs [hunk 3]
```diff
@@ -36,6 +36,12 @@
  (fn [communities [_ id]]
    (get-in communities [id :chats])))
 
+(re-frame/reg-sub
```
Comment (J-Son89) [inline src/status_im/subs/communities.cljs:39]: I think also want to add a small test for new subs 👍

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs (hunk 2 above)
Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Ah thank you for catching that 🙏, I'll update that now.

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs (hunk 1 above)
Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Sounds good will do 👍

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 4]
```diff
@@ -167,9 +167,10 @@
                                                                          muted?)))}]}]))
 
 (defn f-list-footer
-  [{:keys [chat distance-from-list-top cover-bg-color theme]}]
+  [{:keys [chat distance-from-list-top theme customization-color]}]
   (let [{:keys [chat-id chat-name emoji chat-type
-                group-chat]} chat
+                group-chat color]} chat
+        chat-color           (or color customization-color)
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: leftover?

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 5]
```diff
@@ -285,10 +285,15 @@
...
-  [{:keys [insets distance-from-list-top content-height layout-height cover-bg-color distance-atom
+  [{:keys [insets distance-from-list-top content-height layout-height distance-atom
            chat-screen-layout-calculations-complete? chat-list-scroll-y]}]
   (let [theme                    (quo.theme/use-theme-value)
         chat                     (rf/sub [:chats/current-chat-chat-view])
+        community-channel?       (= constants/community-chat-type (:chat-type chat))
+        customization-color      (if community-channel?
+                                   (or (:color chat)
+                                       (rf/sub [:communities/community-color (:community-id chat)]))
+                                   :turquoise)
```
Comment (seanstrom) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs:296]: @Parveshdhull Does this seem right?

Comment (seanstrom) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs:296]: I think I may have misunderstood you're earlier comment, but I think you want to resolve customization-color here instead of somewhere else right?

**Review by Parveshdhull — APPROVED** [review]
Thank you @seanstrom, lgtm!

**Review by jo-mut — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@seanstrom Thank you for the PR and the quality of your work. If I'm not mistaken, this is your first PR that is going to be merged :) Congratulations! And a separate respect for the detailed description of the PR

One question: Is it possible for channels in the channel list view to inherit the color of the channel instead of the community color? Currently, all channels inherit the color of the community. Or better to implement this in separate PR?

### Steps:
1. Create red color community
2. Create green channel
3. Check the color of green channel in the list of channels

### Actual result:
All channel avatars inherit the color of the community.
image

### Expected result:
Channels avatars inherit the color of the channel which is set up during creation/update

**Comment by VolodLytvynenko** [comment]
If the described feature in https://github.com/status-im/status-mobile/pull/18941#issuecomment-1972883147 better to implement separately, then PR can be merged. i will create a separate task

**Comment by seanstrom** [comment]
@VolodLytvynenko thank you ❤️, really appreciate your kind words 🙏

Regarding the channel list colors: I do have a small fix for that ready to go, so I wouldn't mind squeezing it in here if that works 👍. Btw, does any issue already exist for that bug?

**Comment by seanstrom** [comment]
@VolodLytvynenko Just read your latest comment, I'll hold off on adding anything to this PR. Please send me the link to that new issue when you have a chance 🙏

**Comment by VolodLytvynenko** [comment]
@seanstrom As far as I investigated, the channel avatars in the list view should inherit the color of the community, which is how it currently works. There's no need for issue creation, the current behavior is correct. Thank you!
