### PR TITLE
Show unread indicator on Activity Center tabs

### LINKED ISSUE #14852: Show unread badge on Activity Center tabs
# Problem

When users receive notifications and they open the AC, they have no way to tell which tab the notification belongs. They have two cumbersome alternatives:

- Open the `All` tab and search for the new unread notification. This is okay for most users, but the ones with lots of notifications of varying types can find the process tedious.
- Open each tab until the desired notification is visible and the user can decide what to do about it.

## Solution

- Show the unread badge on each tab containing one or more unread notifications.
- The badge should disappear if there are no unread notifications.
- Don't show the badge on the `All` tab.

## References

- https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18681&t=wwEILzdU13eKAvtW-0

### LINKED ISSUE #14882: Notification dot doesn't use a cutout as in Figma
# Bug Report

From the point of view of the Design System, the current implementation of notification dots over tabs use a hardcoded background color to create the illusion of a cutout. This can be considered a bug, because it never worked with blurred backgrounds.

### Expected solution

Use an actual cutout on the corner of the tab. Unfortunately in ReactNative the solution requires using an SVG because there's no support for the CSS `clip-path` property.

### References

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=57%3A13215&t=mzgyr5OSrRuJKUhH-0

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/14852
Fixes https://github.com/status-im/status-mobile/issues/14882

### Summary

- [x] Fixes https://github.com/status-im/status-mobile/issues/14852
- [x] Fixes https://github.com/status-im/status-mobile/issues/14882
- [x] Refactors `tab` component to follow new guidelines.
- [x] Improves preview area for tabs to optionally show notification dots.
- [x] Refactors `tabs` component: break the component into smaller chunks; remove duplication between scrollable & non-scrollable tabs; update outdated docstring;
- [x] Adds accessibility labels to tabs.

<table>
  <thead>
    <tr>
      <th>Cutout with light theme on the background</th>
      <th>Cutout with dark theme on the background</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>activity-center-light-theme</td>
      <td>activity-center-dark-theme</td>
    </tr>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Cutout in non-scrollable tabs</th>
      <th>Notification dots in preview area</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>messages-home-screen</td>
      <td>preview</td>
    </tr>
  </tbody>
</table>

### Review notes

1. Figma specifies the notification dot should have a cutout on the corner of tabs. In ReactNative we can achieve the desired effect with an SVG because it doesn't support the CSS `clip-path` property.
2. I faced a dreadful, [known issue](https://github.com/facebook/react-native/issues/3121) in ReactNative, where `:overflow :visible` doesn't work on components inheriting from ScrollView (e.g. FlatList). Hence why this PR adds a slight padding to the top of scrollable tabs and then offset by a negative margin. It works pretty well in practice :) I tried all sorts of things to fix this, but none of them work in our ReactNative version.

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/quo_preview/tabs/tabs.cljs [hunk 1]
```diff
@@ -13,10 +13,21 @@
                :value "32"}
               {:key   24
                :value "24"}]}
+   {:label "Show unread indicators?"
```
Comment (OmarBasem) [inline src/status_im2/contexts/quo_preview/tabs/tabs.cljs:16]: There are a few string labels. Not sure if they are displayed in the UI. If so, may need translation.

**Review by OmarBasem — APPROVED** [review]
Looks good!

File: src/status_im2/contexts/quo_preview/tabs/tabs.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/contexts/quo_preview/tabs/tabs.cljs:16]: These are just for the preview area :)

File: src/quo2/components/tabs/tab/view.cljs [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+   {:width    width
+    :height   height
+    :view-box (str "0 0 " width " " height)
+    :fill     :none}
+   [svg/path
+    {:fill-rule :evenodd
+     :clip-rule :evenodd
+     :fill      background-color
+     :d
+     "M11.4683 6.78094C11.004 6.92336 10.511 7 10 7C7.23858 7 5 4.76142 5 2C5 1.48904 5.07664 0.995988 5.21906 0.531702C4.68658 0.350857 4.13363 0.213283 3.56434 0.123117C2.78702 0 1.85801 0 0 0V32C1.85801 32 2.78702 32 3.56434 31.8769C7.84327 31.1992 11.1992 27.8433 11.8769 23.5643C12 22.787 12 21.858 12 20V12C12 10.142 12 9.21298 11.8769 8.43566C11.7867 7.86637 11.6491 7.31342 11.4683 6.78094Z"}]])
```
Comment (J-Son89) [inline src/quo2/components/tabs/tab/view.cljs]: curious of how we generated this svg? 🤔

**Review by J-Son89 — APPROVED** [review]

File: src/quo2/components/tabs/tab/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/quo2/components/tabs/tab/view.cljs]: I only realized how to obtain this SVG after seeing that ReactNative doesn't support the CSS `clip-path` property, which Figma uses. But, you can export the clipped path layer as SVG in Figma, and then it just works. Pretty cool!

The only thing to note @J-Son89 is that some layers can't be exported as SVG if they're the leaves of the DOM tree, so I had to export the parent DOM node. And it only worked by using the layer's panel.

Comment (J-Son89) [reply src/quo2/components/tabs/tab/view.cljs]: ok cool, maybe we can show this at Mondays meeting so other devs/designers are aware it's possible? 🤔

Comment (ilmotta) [reply src/quo2/components/tabs/tab/view.cljs]: That'd be cool, I agree. It took me ages to realize this was the only viable solution.

**Comment by ilmotta** [comment]
@status-im/mobile-qa, this PR is improving how the unread indicators are rendered to match cutouts in the corner of tabs (as in Figma). The changes should be harmless and shouldn't affect any flows, but I'm seeing an e2e test related to unread indicators fail.

Could you help me understand if the following e2e test is affected by the changes in this PR and how we can fix it?

```
Device 1: Find Button by accessibility id: close-activity-center
Device 1: Tap on found: Button
medium/test_activity_center.py:235: in test_activity_center_decline_contact_request_no_pn
    self.errors.verify_no_errors()
base_test_case.py:188: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Unread indicator on contacts tab or on activity center is not shown!
```

**Comment by pavloburykh** [comment]
> Could you help me understand if the following e2e test is affected by the changes in this PR and how we can fix it?

Hi @ilmotta ! Thanx for your work. It seems that accessibility id for contacts tab unread badge has been lost after refactoring. E2E is looking for element with accessibility-id 'notification-dot'.

**Actual:**
actual_result

**Expected:**
expected_result

Also, I noticed that contacts tab element right part visually differs (smaller) than the rest part of element. On Android emulator it looks divided from the main part of the element.

**Image from emulator:**
actual_result png 2023-01-27 11-05-13

**Image from physical device (Samsung Galaxy A52, Android 11):**

photo_2023-01-27 11 08 14

**Comment by ilmotta** [comment]
Thank you @pavloburykh. The independent right side piece is the appropriate solution to have a cutout on the corner of tabs, so that's why you're seeing the separate DOM element.

I can see on a real mobile phone the issue of having a tiny little space. That's a deal breaker... The other issue on `(Samsung Galaxy A52, Android 11)` I couldn't reproduce unfortunately, but I'm sure it's there.

Tough problem, I'll see what I can do.

**Comment by ilmotta** [comment]
@pavloburykh, after countless hours, I had to resort to various workarounds due to the way SVGs were being rendered by ReactNative. I was able to eventually reproduce both of the issues you reported and fix them.

The accessibility label should be visible too.

Please, let me know if it's all good on your testing devices :)

**Comment by pavloburykh** [comment]
> @pavloburykh, after countless hours, I had to resort to various workarounds due to the way SVGs were being rendered by ReactNative. I was able to eventually reproduce both of the issues you reported and fix them.

@ilmotta thanx for your investigation and efforts! I wish I could help somehow to make the process of your reproduction less painful. If I can help in future - please let me know.

> The accessibility label should be visible too.

Thanx, accessibility label is visible now!  

> Please, let me know if it's all good on your testing devices :)

Unfortunately, currently the separation of DOM elements has become visible on my physical device `Samsung Galaxy A52, Android 11`
photo_2023-01-30 10 15 34

I will ask other QAs to check on their devices and provide you an update. 


**Also, I got one more question:** should unread indicator be displayed on "All" tab? On screenshot below you can see Contact request. There is unread indicator on "Contact request" tab but no indicator on "All" tab. 

photo_2023-01-30 10 27 18

**Comment by ilmotta** [comment]
>@ilmotta thanx for your investigation and efforts! I wish I could help somehow to make the process of your reproduction less painful. If I can help in future - please let me know.

Hey @pavloburykh, I guess I'm lucky in the sense that I have a Samsung to reproduce the issues you found on A52. Or so I thought ;) So perhaps one thing devs and QA teams can try is to test on identical smartphone models or very similar ones. Just as we have a standard iPhone model for designs, we could have 1 or 2 standard Android models that are good representatives of Status' Android user audience. Or maybe we do have a "standard" Android model but I don't know :)

Another useful alternative is to have a Nix shell for running Android Studio, with a common hardware profile that we can all use. This would immensely help for those cases where QAs report an issue they found in their emulators, but devs use a different hardware profile or Android Studio version and then are out of luck. This was in fact what happened in this PR for me, i.e. I could only reproduce the issues you reported in a real smartphone, but you were able to see them in the emulator.

>Unfortunately, currently the separation of DOM elements has become visible on my physical device Samsung Galaxy A52, Android 11

I find the current solution unacceptable if it looks bad on A52. I'll give today another try with another trick. I'll timebox until tomorrow. If nothing works I'll talk to designers to find a middle-ground design without the cutout :man_shrugging:

>Also, I got one more question: should unread indicator be displayed on "All" tab?

I intentionally didn't add the indicator to the all tab. I'll double-check with designers, thanks!

**Comment by pavloburykh** [comment]
> Another useful alternative is to have a Nix shell for running Android Studio, with a common hardware profile that we can all use. This would immensely help for those cases where QAs report an issue they found in their emulators, but devs use a different hardware profile or Android Studio version and then are out of luck. This was in fact what happened in this PR for me, i.e. I could only reproduce the issues you reported in a real smartphone, but you were able to see them in the emulator.

@ilmotta that might be a good solution. Another way QAs can help with reproduction of bugs which are found on emulator is providing the exact Configuration of specific virtual device from Android Studio. As for current issue - it is just barely visible on my emulator. I mean this small size differens (about 1 px) of right DOM element (see screenshot below). 

Android Emulator - my_emu_nex_API_32:5554 2023-01-30 13-57-01

> I find the current solution unacceptable if it looks bad on A52. I'll give today another try with another trick. I'll timebox until tomorrow. If nothing works I'll talk to designers to find a middle-ground design without the cutout 🤷‍♂️
>
Thanx @ilmotta! I've asked QA team to check the issue on their devices and it turned out that no one could reproduce it. 
Devices which were used: Huawei p20 light (Android 9),  iPhone 11 Pro Max (IOS: 15.5), Pixel 2, Huawei P40 lite, iPhone SE, Xiaomi Mi Note 9. 

Unfortunately we don't have another Samsung device in order to check. So for now - it is reproducible only on my `Samsung Galaxy A52`.  


> I intentionally didn't add the indicator to the all tab. I'll double-check with designers, thanks!

Thanx!

**Comment by ilmotta** [comment]
@pavloburykh, I timeboxed other solutions, but in the end, `react-native-svg` and/or ReactNative renders artifacts depending on factors outside our control. They're bugs actually, but nothing we can do unfortunately.

Given most models are rendering correctly, what do you think we proceed with the merge? If other users report UI issues we can get back to this problem.

>should unread indicator be displayed on "All" tab?

I double-checked this, the `All` tab should not show the indicator. Reference: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=5387%3A523340&t=Aaa1rp5e2V04Hkqr-0

**Comment by pavloburykh** [comment]
> Given most models are rendering correctly, what do you think we proceed with the merge?

Agree, according to current statistics of devices facing the issue we are good to leave it as it is for now. As for merging - I need some more time for testing as I haven't had a chance yet to test deeply new indicators itself. I believe that will provide full feedback on PR tomorrow.  

> I double-checked this, the `All` tab should not show the indicator. Reference: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=5387%3A523340&t=Aaa1rp5e2V04Hkqr-0

Cool, thanx for clearing this out @ilmotta!

**Comment by ilmotta** [comment]
> > Given most models are rendering correctly, what do you think we proceed with the merge?
> 
> Agree, according to current statistics of devices facing the issue we are good to leave it as it is for now. As for merging - I need some more time for testing as I haven't had a chance yet to test deeply new indicators itself. I believe that will provide full feedback on PR tomorrow.
> 
> > I double-checked this, the `All` tab should not show the indicator. Reference: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=5387%3A523340&t=Aaa1rp5e2V04Hkqr-0
> 
> Cool, thanx for clearing this out @ilmotta!

Awesome, I'll be waiting for your feedback. Thank you!

**Comment by pavloburykh** [comment]
@ilmotta please, take a look at the following issue

### ISSUE 1 Unread indicator for AC tabs "Admin", "Mentions", "Replies" is not displayed after re-login until user opens this tabs

**Steps:** 

1. Generate unread indicator for AC tabs "Admin", "Mentions", "Replies"
2. Open AC and make sure that they are displayed
3. Keep notifications unprocessed (unread)
4. Perform relogin
5. Open AC and see if tab indicators are still there

**Actual result** Unread indicators are not displayed until tab is opened. The only tab which has unread indicator is "Contact requests" tab.

**Expected result:** Unread indicators are displayed until notifications are processed. 

[Status-debug-logs (25).zip](https://github.com/status-im/status-mobile/files/10548985/Status-debug-logs.25.zip)

https://user-images.githubusercontent.com/97245802/215832389-0785d177-660e-4670-9c31-707d13230fa0.mp4

**Comment by pavloburykh** [comment]
### ISSUE 2 Unread indicator for "Mentions", "Replies" is not reset until user opens the tab despite notification has already been read in chat

**Steps:**

1. Generate unread mentions and replies
2. Open chat containing unread messages and read them
3. Open AC
4. Pay attention if unread indicators for "Mentions", "Replies" tabs are reset

**Actual result:** indicators are still displayed. They disappear only after tab is opened. In case if user is redirected to the chat containing unread replies/mentions directly from those tabs - indicators are reset correctly. 

**Expected result:** indicators should be reset as soon as user reads unread messages. 

[Status-debug-logs (26).zip](https://github.com/status-im/status-mobile/files/10549132/Status-debug-logs.26.zip)

https://user-images.githubusercontent.com/97245802/215836365-15b0db25-e05a-4b14-a328-5e710cf7a737.mp4

**Comment by ilmotta** [comment]
@pavloburykh, thanks a lot for another round of reviews. `Issue 1` and `Issue 2` should be fixed now. The original implementation was flawed.

**Comment by pavloburykh** [comment]
@ilmotta thanx for the fixes! I will perform re-test and provide an update soon. Meanwhile, could you please take a look at e2e build, it has failed for some reason https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fandroid-e2e/detail/PR-14883/9/pipeline

**Comment by pavloburykh** [comment]
@ilmotta looks like @alwx has already merged his PR https://github.com/status-im/status-mobile/pull/14923 
Could you please rebase the changes and after that I will continue with testing of this PR? Thanx!

**Comment by pavloburykh** [comment]
> @ilmotta thanx for the fixes! I will perform re-test and provide an update soon. Meanwhile, could you please take a look at e2e build, it has failed for some reason https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fandroid-e2e/detail/PR-14883/9/pipeline

It could be some global issue with e2e builds, cause similar issue has been observed in this PR https://github.com/status-im/status-mobile/pull/14923 which has been just merged. Though, better to make sure that it is not related to any PR changes.

**Comment by ilmotta** [comment]
> > @ilmotta thanx for the fixes! I will perform re-test and provide an update soon. Meanwhile, could you please take a look at e2e build, it has failed for some reason https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fandroid-e2e/detail/PR-14883/9/pipeline
> 
> It could be some global issue with e2e builds, cause similar issue has been observed in this PR #14923 which has been just merged. Though, better to make sure that it is not related to any PR changes.

@pavloburykh, just rebeased. Let's hope the build succeeds. It's a network timeout when trying to upload the binaries, unfortunately not much we can do. If it fails again I'll try to contact Jakob.

**Comment by ilmotta** [comment]
@pavloburykh, I reached out to Jakob, and it looks like SauceLabs had an incident just today https://status.saucelabs.com/incidents/717grdmrkc2y that might be related the 504s we're getting.

Right now their status page says it's all green (https://status.saucelabs.com/), but I just tried rerunning the CI build and the upload still timeout. Therefore there's not much we can do on our end. I saw other PRs are being impacted as well :/

Can you open a ticket in SauceLabs? Is it worth it? Are you blocked by this infra issue to test the PR?

**Comment by pavloburykh** [comment]
@ilmotta thanx for your work! PR is tested and ready to be merged.

**Comment by pavloburykh** [comment]
> Can you open a ticket in SauceLabs? Is it worth it? Are you blocked by this infra issue to test the PR?

@ilmotta thank you for update. It turned out that @churik is already on this issue and in process of communication with SauceLab.

**Comment by ilmotta** [comment]
> > Can you open a ticket in SauceLabs? Is it worth it? Are you blocked by this infra issue to test the PR?
> 
> @ilmotta thank you for update. It turned out that @churik is already on this issue and in process of communication with SauceLab.

Good news! Sorry this PR took way longer than I anticipated, I learned some lessons ;) See you on the next one

**Comment by pavloburykh** [comment]
> Good news! Sorry this PR took way longer than I anticipated, I learned some lessons ;) See you on the next one

That's totally fine, there has been delay with testing from my side too. You are doing a great job)) See on next one!

File: src/quo2/components/tabs/segmented_tab.cljs [hunk 3]
```diff
@@ -1,5 +1,5 @@
 (ns quo2.components.tabs.segmented-tab
-  (:require [quo2.components.tabs.tab :as tab]
+  (:require [quo2.components.tabs.tab.view :as tab]
```
Comment (siddarthkay) [inline src/quo2/components/tabs/segmented_tab.cljs:2]: @ilmotta : This change seems to have broken the segmented control in latest develop 

This is how the segmented control looked like before :
Screenshot 2023-02-03 at 2 28 50 PM

This is how it looks like now : 
Screenshot 2023-02-03 at 2 31 06 PM

Comment (siddarthkay) [reply src/quo2/components/tabs/segmented_tab.cljs:2]: well i wouldn't say its _broken_ broken, but yeah the width of the selected control used to be much larger before :) 
ref : https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=57%3A13214&t=sG7k2uT3px0fV2Lb-0

Comment (ilmotta) [reply src/quo2/components/tabs/segmented_tab.cljs:2]: Thank you @siddarthkay. I'll investigate and try to fix this.

Comment (pavloburykh) [reply src/quo2/components/tabs/segmented_tab.cljs:2]: @ilmotta @siddarthkay hi! is this problem somehow visible in current UI? Just want to understand if I have missed it during testing.

Comment (siddarthkay) [reply src/quo2/components/tabs/segmented_tab.cljs:2]: @pavloburykh : no, this component is hardly used anywhere and I only found it while working on a new screen.
I could see the broken in the sandbox that we have for quo2 preview :)

Comment (ilmotta) [reply src/quo2/components/tabs/segmented_tab.cljs:2]: This issue will definitely be fixed by mid next week @pavloburykh. It should be a quick one, but hopefully as Sid said it's not impacting anything, so lower priority.

Comment (pavloburykh) [reply src/quo2/components/tabs/segmented_tab.cljs:2]: got it! thanx @ilmotta @siddarthkay
