### PR TITLE
[#17218] fix: android channel name ellipsis completely

### LINKED ISSUE #17218: [Android] The name of channel is not shown when channel is opened
### Problem 
The channel name is not displayed when the channel is opened for Android devices. This problem doesn't seem to follow a specific pattern and occurs inconsistently. In the steps, I have given exams with which exact channel names, the current issue is reproducible

### Reproduction
1. Create the channel in the community using the Desktop with the following names:
 - max_channel_length_wdddd
 - A-B-C-D-E-F-G-H-I-2-Kddd
 
2. Share the current community with a mobile user [Android]
3. Open the channels

### Actual behavior
Three dots are shown instead of the channel name in the opened channel
image

### Expected behavior
The channel name is shown into the opened channel

### ENV:
- Status version: nightly 
- Operating System: Android

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17218

In Android, when we use :number-of-lines 1 for long text that doesn't have any space between words, it will ellipsis the entire text.

**Actual behavior**
Three dots are shown instead of the channel name in the opened channel

**Expected behavior**
The channel name is shown into the opened channel

Before:

After:

#### Platforms
- Android

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 1]
```diff
@@ -229,7 +236,7 @@
            :size            :heading-1
            :style           {:margin-top (if group-chat 54 12)}
            :number-of-lines 1}
-          display-name
+          (truncate-display-name display-name)
```
Comment (ajayesivan) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: I'm not sure about truncating the display name to a fixed length of 22. Did you try changing the `name-container`'s `flex-direction` property to `column`? from my understanding, there is no need for using row there. Correct me if I'm wrong.

**Review by ajayesivan — COMMENTED** [review]
I think you can fix this issue without resorting to manual truncation. I recently worked on a [similar issue](https://github.com/status-im/status-mobile/pull/17078) where I didn't face this problem on Android. If that's not possible I may also need to test my changes again.

File: src/status_im2/contexts/chat/messages/list/view.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/list/view.cljs]: @ajayesivan display-name is inside `quo/text` with `:number-of-lines 1` and it causes issue on android. 
but in case i also tried `column` in `name-container` and it didn't help

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/list/view.cljs]: resolved

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 2]
```diff
@@ -223,7 +224,7 @@
              :display-name    display-name
              :online?         online?
              :profile-picture photo-path}])]
-        [rn/view {:style style/name-container}
+        [rn/view
```
Comment (ajayesivan) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: Wondering if we need the outer view at all.

**Review by ajayesivan — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/list/view.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/list/view.cljs]: removed

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 3]
```diff
@@ -2,6 +2,7 @@
   (:require
     [quo2.core :as quo]
     [quo2.foundations.colors :as colors]
+    [quo.platform :as platform]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: `react-native.platform` should be used, quo shouldn't be used in status-im2

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: resolved

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Thanks for your work!
e2e failures are known not related to PR.
Tested basic flows, LGTM!

**Devices:**
- IPhone 14 Pro (IOS 16.5.1)
- Google Pixel 7A (Android 13)
