### PR TITLE
Communities - Channel list should not be shown for token-gated communities

### LINKED ISSUE #17836: Communities - Channel list should not be shown for token-gated communities
# Bug Report

## Problem 

Users can see the channel list in token-gated communities.

#### Expected behavior

Token-gated communities should not display the categorized channel list.

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=14009-569565&mode=design&t=CYSZhcyPISfU2ds1-0

#### Actual behavior

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=14004-106709&mode=design&t=CYSZhcyPISfU2ds1-0

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by FFFra**
fix: #17836

Figma design: 

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=14009-569565&mode=design&t=CYSZhcyPISfU2ds1-0

### Demo

https://github.com/status-im/status-mobile/assets/5999878/f33452bc-e85e-4279-97b1-3d9e82837a20

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 1]
```diff
@@ -273,12 +273,15 @@
             :last-item-style style/last-community-tag
             :container-style style/community-tag-container}])
         [join-community community pending?]]
+       
+       (when (or (and token-permissions joined)
+               (not token-permissions))
        [channel-list-component
```
Comment (clauxx) [inline src/status_im2/contexts/communities/overview/view.cljs]: Indentation looks a bit weird here. I guess a format will fix it.

**Review by clauxx — APPROVED** [review]

File: src/status_im2/contexts/communities/overview/view.cljs (hunk 1 above)
Comment (FFFra) [reply src/status_im2/contexts/communities/overview/view.cljs]: tks, I will take a look also a good opportunity to fix again my auto format!

Comment (FFFra) [reply src/status_im2/contexts/communities/overview/view.cljs]: fixed =)

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM 👍🏻

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 2]
```diff
@@ -273,12 +273,14 @@
             :last-item-style style/last-community-tag
             :container-style style/community-tag-container}])
         [join-community community pending?]]
-       [channel-list-component
-        {:on-category-layout              on-category-layout
-         :community-id                    id
-         :community-color                 color
-         :on-first-channel-height-changed on-first-channel-height-changed}
-        (add-handlers-to-categorized-chats id chats-by-category joined)]])))
+       (when (or (and token-permissions joined)
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/overview/view.cljs]: Even if this code works, since `token-permissions` is a sequence, it's more robust and idiomatic to use `seq` to check something is there. 

```clojure
(and (seq token-permissions) joined)
```

See from example below that if a collection is empty, it is truthy. If you check using just `(and token-permissions ...)` you are checking the value is either not nil or not false, but an empty sequence is truthy.

```clojure
(or [] :default-value) ; => []
```

We do the same thing here https://github.com/status-im/status-mobile/blob/c150070cfef83b5b9b9470cfa87bdd2c2a2414e0/src/status_im2/contexts/communities/overview/view.cljs#L181

Comment (FFFra) [reply src/status_im2/contexts/communities/overview/view.cljs]: Make sense, thanks!

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 3]
```diff
@@ -273,12 +273,14 @@
...
             :container-style style/community-tag-container}])
         [join-community community pending?]]
-       [channel-list-component
-        {:on-category-layout              on-category-layout
-         :community-id                    id
-         :community-color                 color
-         :on-first-channel-height-changed on-first-channel-height-changed}
-        (add-handlers-to-categorized-chats id chats-by-category joined)]])))
+       (when (or (and (seq token-permissions) joined)
+                 (not (seq token-permissions)))
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/overview/view.cljs]: `(not (seq` can be replaced by `empty?` https://github.com/clojure/clojure/blob/clojure-1.11.1/src/clj/clojure/core.clj#L6246

**Review by ilmotta — APPROVED** [review]

**Comment by churik** [comment]
Thanks for your amazing work!
e2e failures are known not related to PR.
Tested basic flows, LGTM!

**Devices:**
- IPhone 14 Pro (IOS 16.5.1)
- Google Pixel 7A (Android 13)

Please, cherry-pick your fix to release branch too, thank you!

**Comment by FFFra** [comment]
Thank you so much, team!
