### PR TITLE
fix: max value is zero for some tokens

### LINKED ISSUE #19646: USDC assets not available for sending
### Steps:
1. Restore user with USDC (in my case USDC is available on Optimism and on Arbitrium)
2. Select USDC as asset for sending
3. Go to the send page

### Actual result:
The value is not available for sending.

image

https://github.com/status-im/status-mobile/assets/52490791/01bf9ec7-f49e-41cd-90b6-0860efee4df1

### Expected result:
The value is available for sending

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Additional info:
- Current USDC is available in my case on two networks, on Optimism 1.28 and on arbitrium 1.27, you can check it in Watch-only `0xed620c9dc11401b63b35dfe8e93f2b11db0f6f9e`
- Feel free to reach out to me directly if you need a user with collectibles. I will provide the seed phrase

### LINKED ISSUE #19739: The assets can't be sent on 'send to' page when an asset is selected on account overview page
Can be taken after the merge of https://github.com/status-im/status-mobile/pull/19515

### Steps:
1. Restore the user with available assets (example: eth)
2. Go to the account overview page
3. Long tap on the asset -> send
4. Select account with available assets to send from (eth)
5. Navigate to sent to page

### Actual result:
User sees 0 assets on the 'send to' page.

https://github.com/status-im/status-mobile/assets/52490791/27f047b6-a356-4fcc-9638-925f31cbe5ff

### Expected result:
User sees available assets on the 'sent to' page and can sent assets

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### LINKED ISSUE #19813: Max Amount is zero if user tries to send ETH to his another account
# Bug Report

#### Expected behavior
Max amount is equal to the real amount of tokens user has

#### Actual behavior
Max Amount is zero.
Issue reproduces only on Tetiana's account.
Please, ask a seed phrase ONLY in case you are going to work on this issue as it is a private account with real money.

https://github.com/status-im/status-mobile/assets/147824399/ff1d6587-e71f-4953-9b13-6b447e6c6da8

### Reproduction

1. Login to app as a user with real ETH tokens
2. Go to Wallet
3. Create one more account
4. Go to Send -> ETH
5. Select your second account as a receiver

### Additional Information

- Status version: nightly 25/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #19646 
fixes #19813
fixes #19739

### Summary

This PR fixes an issue where max value is 0 for some tokens and prevents it to send them

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

#### Case 1
- Open Status
- Login with an account with USDC and other tokens with same symbol
- Go to Wallet
- Select account
- Tap on Send
- Select an address
- Select USDC
- Verify user can type a valid amount

#### Case 2
- Login with an account with available assets (example: ETH)
- Go to the account overview page
- Long tap on the asset -> send
- Select account with available assets to send from (ETH)
- Navigate to sent to page
- Verify user can send assets

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hi @briansztamfater! Could you please rebase the PR and resolve existing conflicts? Thank you!

**Comment by briansztamfater** [comment]
> Hi @briansztamfater! Could you please rebase the PR and resolve existing conflicts? Thank you!

Yep, on it! @pavloburykh

File: src/status_im/contexts/wallet/send/input_amount/component_spec.cljs [hunk 1]
```diff
@@ -40,15 +40,16 @@
...
-                                                    :networks [{:source           879
-                                                                :short-name       "eth"
-                                                                :network-name     :mainnet
-                                                                :abbreviated-name "Eth."
-                                                                :chain-id         1
-                                                                :related-chain-id 1
-                                                                :layer            1}]}
-   :wallet/current-viewing-account-tokens-filtered {:balances-per-chain         {1 {:raw-balance
+   :wallet/wallet-send-token                       {:symbol                     :eth
+                                                    :networks                   [{:source 879
```
Comment (vkjr) [inline src/status_im/contexts/wallet/send/input_amount/component_spec.cljs:44]: Looks like formatting needs one more run of `make lint-fix`)

**Review by vkjr — APPROVED** [review]

**Comment by briansztamfater** [comment]
@pavloburykh rebase done

**Comment by pavloburykh** [comment]
@briansztamfater thank you for the fixes. PR is ready for merge.
