### PR TITLE
Communities - Token gated community fixes

### LINKED ISSUE #17267: Separate channel and community requirements
# Bug Report

## Problem 
Potential members of token-gated communities can't see whether they can join a community or not, and they can join even if they don't meet the requirements.

#### Expected behavior
3. User1: can see that meets the requirement

#### Actual behavior
3. You hold 0 from 1.000000 SNT

https://github.com/status-im/status-mobile/assets/4557972/211351d2-da92-4e52-a6e4-74f7e1473dfd

5. User2 shouldn't be able to enter a channel
7. Error in sending a message
IMAGE 2023-09-12 18:22:47

### Reproduction

1. Desktop: create a token-gated community with the following permission:
image
2. Invite User1 (meets the requirement) and User2 (doesn't meet the requirement)
3. User1: check the community invite and join the community
5. User2: check the community invite and join community
6. User1: send message 
7. User2: send message

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Logs of user2: 

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/17267

### Summary

- [x] Fix: when there are only channel token permissions, don't show the text "You hold 0 of these:" because there are no requirements to show.
- [x] Fix: do not show channel token permissions when the user wants to join a community. In other words: only "become admin", "become member", "become token master", and "become token owner" are taken in consideration.
- [x] Fix: render correct channel lock icon in 3 states (no permission, with permissions and locked and with permissions and unlocked).
- [x] Fix: Previously, before having joined a community, all channels had a lock icon closed, now the lock icon is only closed when there's a permission set, otherwise no icon is shown (the lock is never open before the user joins the community).
- [x] Fix: small UI spacing fix, only display community tags component when there's at least one tag.
- [x] Bonus fix: community Overview and Discover screens top bar had a regression, see the screenshots.

To keep things manageable given the sheer amount of bugs related to token gating, this PR only focuses on the bare minimum usage of the permissions' system. Minted owner tokens were completely ignored for this PR.

<table>
  <thead>
    <tr>
      <th>Before</th>
      <th>After</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Before</th>
      <th>After</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

### What about the trailing zeros problem?

We know we want to better format the number `0.00100000`, but the problem is that this value arrives from status-go already as a string. I would like to fix this issue in a separate PR, with more care, given that the formatted output varies depending on the locale. Additionally, there are good practices to format large numbers to users and I couldn't figure out from Figma alone the full requirements.

### Other known bugs

While working on the fixes, many bugs popped up, some of which could be caused on the mobile side.

- It's currently unclear how the "View only" permission works because it doesn't force a read-only mode on its affected channels.
- Sometimes it is necessary to close and reopen the mobile app for the request to join screen to show the correct token requirements. Sometimes it works.
- Sometimes it is necessary to re-add a member to a token gated community, otherwise the old permissions are still used after using the community invite.
- There are visible mobile UI bugs in the token gated component because it's not implemented as in Figma. For example, the join community button should be part of the design system, not the screen, and by doing that, other fixes would follow naturally.
- Sometimes after having left a community, I would be added to it automatically again.

Auto-join token-gated community bug:

[auto-join-bug.webm](https://github.com/status-im/status-mobile/assets/46027/36e80684-a0ff-498e-82cd-8dfb1d119e6c)

At one point or another, I reach a state where I can see the community in my list of communities I joined even though I'm not listed in the desktop app as a member, and when I try to open any channel it says "You are not a member of this group". The only way to restore to the correct behavior is to leave the community on mobile and request to join again. I think this bug can be achieved while restoring from a seed phrase, but I don't have the exact reproduction steps yet.

#### Platforms

- Android
- iOS

#### Areas that may be impacted

- Community overview, before and after joining a community.

### Steps to test

This PR was developed and tested using the Goerli network and with the `testnet` flag enabled in the Desktop client.

Please, ignore for the scope of this PR minted owner tokens and master tokens. The focus was only on the most basic permissions for communities and channels.

I intend to define proper test cases in the near future, but for the time being, these are the cases I mostly tested:

- Non token-gated communities.
- Token-gated only with "Become member" permission.
- Token-gated only with channel permissions.
- Token-gated with a mix of "Become member", "Become admin", "View only" and "View and post".

For each case I checked:

- Are the channel lock icons correct?
- Can the user open locked channels? Can the user open unlocked ones?
- Can the user leave and join a community using the previous invite? What about a new one?
- Can admins and members exchange messages in the community channels with/without permissions?

status: ready

### CODE REVIEW

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 1]
```diff
@@ -206,15 +206,16 @@
...
-        :sticky-header  [render-sticky-header
-                         {:selected-tab  selected-tab
-                          :scroll-height scroll-height}]}
+       {:theme            theme
+        :on-scroll        #(reset! scroll-height %)
+        :navigate-back?   :true
+        :height           (if (> @scroll-height 360)
+                            208
+                            148)
+        :background-color (colors/theme-colors colors/white colors/neutral-95)
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/view.cljs:215]: FYI: Fix from past regression, here I'm just bringing back the missing background color.

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 2]
```diff
@@ -82,23 +83,23 @@
...
-        :on-layout #(on-category-layout name (int (layout-y %)))}
-       (when-not (= constants/empty-category-id category-id)
-         [quo/divider-label
-          {:on-press     #(collapse-category community-id category-id collapsed?)
-           :chevron-icon (if collapsed? :i/chevron-right :i/chevron-down)
-           :chevron      :left}
-          name])
-       (when-not collapsed?
-         (into [rn/view {:style {:padding-horizontal 8 :padding-bottom 8}}]
-               (map #(channel-chat-item community-id community-color %))
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/overview/view.cljs:100]: FYI: `doall` is unnecessary and Reagent components shouldn't be called as functions, this can cause problems.

**Review by ajayesivan — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by clauxx — APPROVED** [review]

**Comment by churik** [comment]
@ilmotta AMAZING WORK!
Working like a charm with `Become a member` + channel permissions.

However, found one issue in regards to `Become an admin` - if you set this permission (screenshot with it is attached) 
image
from mobile you can see that you're eligible to join even with zero balance:
IMAGE 2023-11-03 16:14:55

and you're able to view and post in channels.

**Comment by ilmotta** [comment]
> and you're able to view and post in channels.

Thank you for quickly reviewing the build @churik! Yes, that looks completely wrong.

What's interesting is that the backend agrees with mobile and allows the user to join and post, even without the minimum balance. Let's see what's going on! 🏃🏼‍♂️ 🏃🏼

**Comment by ilmotta** [comment]
@churik, here's all I got about the admin permission bug you found.

My understanding (and I believe yours) is that "Become an admin" should supersede the "Become a member" permission, therefore, if a community has only one permission to "Become an admin" like we're testing here, then the user should not be able to join unless they hold enough tokens.

I could confirm the **admin permission is being completely ignored as a means of controlling access if there are no member permissions**. This is exactly the case you found!

Here's the proof in status-go:

https://github.com/status-im/status-go/blob/953ed4c8e4b85374d736b051091d97f6b5254d13/protocol/communities/permission_checker.go#L107

The code in status-go shows that the if there are no member permissions, the second check that actually have admin permissions is ignored due to the logical `OR`.

Therefore, a fix is needed in status-go. Nice catch! I can work on that after this PR is merged.

**Comment by ajayesivan** [comment]
@ilmotta Regarding the admin permission, if that's the case, how can I create an open community where anyone can join without any restrictions, while still maintaining an admin-level permission only?

**Comment by churik** [comment]
@ajayesivan not sure if I understood the question.
The permission is called "Become an admin", therefore it allows someone who meets the requirements to become an admin. I don't think that there was set of permissions that allow anybody to join, but the admin has to meet the requirements - it hasn't been done I believe

But who knows! I'll clarify the requirements.

**Comment by churik** [comment]
thank you @ilmotta 
I'll also warn the desktop QAs about this and ask the design team.
As Ajay mentioned, there is a chance that these 2 sets of permissions ("Become a member" and "Become an admin") can be combined. In this case, it might be the bug in how we handle "Become an admin" permission - we should hide it (based on https://github.com/status-im/status-mobile/pull/17799#issuecomment-1792626262) and allow any user to join the community in this case. 

I'll investigate and create an issue about that - I believe it might be separate, as the most important permissions for now are "Become a member" + channel permissions.

**Comment by ilmotta** [comment]
Thanks @ajayesivan and @churik. I agree with the points you raised. The requirements are not super clear, the wording is confusing. I believe this confusion will be passed on to users eventually, but maybe designs will evolve until then.

I still tend to read "become an admin" as "become an admin member", but it seems the "member" word should not be implied. "Become an admin" seems to be just a permission to control privilege escalation.

If we confirm the admin permission is as @ajayesivan said, the fix on mobile should be simple and can be done in this PR.

**Comment by ilmotta** [comment]
> I'll investigate and create an issue about that - I believe it might be separate, as the most important permissions for now are "Become a member" + channel permissions.

Also good @churik 👍🏼, if you are okay with that we can fix separately.

File: src/status_im2/contexts/communities/overview/view.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im2/contexts/communities/overview/view.cljs:100]: @ilmotta 
> Reagent components shouldn't be called as functions, this can cause problems.

I disagree with this, it depends on what you want to achieve.
We convert a function into a Regent component when we call it using `[]` instead of `()`.
In this case, this piece of code is just mapping a function over chats to return hiccup that looks like:

```clojure
[rn/view {:style {:padding-horizontal ,,,}}
  [rn/view [quo/channel ,,,]] ; <-- begins the result of mapping
  [rn/view [quo/channel ,,,]]
  [rn/view [quo/channel ,,,]]
  ,,,
  ]
```
So I see no problem that could be caused here.

If you want to change the implementation to return a sequence with the `:key` metadata, maybe (IDK) you are getting a React warning about duplicating keys, since the hiccup returned with this change is:

```clojure
[rn/view {:style {:padding-horizontal ,,,}}
 (
  ^{:key id-1} [channel-chat-item ,,,]
  ^{:key id-2} [channel-chat-item ,,,]
  ^{:key id-3} [channel-chat-item ,,,]
  ,,,
 )
]
```
and the new Reagent component `channel-chat-item` returns:

```clojure
[rn/view {:key id} ; <-- this is using the same id
  [quo/channel ,,,]
```

so we have two components with the same id

File: src/status_im2/subs/communities.cljs [hunk 3]
```diff
@@ -209,14 +209,36 @@
...
-   joined
+(defn- get-chat-token-permissions
+  [{community-id :id permissions :token-permissions} chat-id]
+  (let [chat-composite-id (str community-id chat-id)]
+    (->> permissions
+         (map second)
+         (filter (fn [{composite-ids :chat_ids}]
+                   (some (fn [composite-id]
+                           (= composite-id chat-composite-id))
+                         composite-ids))))))
```
Comment (ulisesmac) [inline src/status_im2/subs/communities.cljs]: if `permissions` is a map, we could use `vals` instead of `(map second)` to get the list of values.

File: src/status_im2/subs/communities.cljs [hunk 4]
```diff
@@ -209,14 +209,36 @@
...
+  "Returns the chat lock state.
+
+  - Nil:   no lock  (there are no permissions for the chat)
+  - True:  locked   (there are permissions and can-post? is false)
+  - False: unlocked (there are permissions and can-post? is true)"
+  [community {chat-id :id can-post? :can-post?}]
+  (let [chat-permissions (get-chat-token-permissions community chat-id)]
+    (if (empty? chat-permissions)
+      nil
+      (not can-post?))))
```
Comment (ulisesmac) [inline src/status_im2/subs/communities.cljs]: About the value returned to identify the chat lock state, I think it's not the best to mix return types that could be confused, I'm not against returning `nil`, but I think it's not the best to return `nil` when the other possible returned values are `true` and `false`.

Seems not easy to read/understand to check for `(nil? (get-chat-lock-state ,,,)`, `(true? (get-chat-lock-state ,,,)` and `(false? (get-chat-lock-state ,,,)`.

I'd suggest to return a keyword: `:no-lock`, `:locked`  and `:unlocked`.

File: src/status_im2/subs/communities.cljs [hunk 5]
```diff
@@ -232,40 +254,35 @@
...
-            {})
-           (sort-by (comp :position second))
-           (map (fn [[k v]]
-                  [k (update v :chats #(sort-by :position %))])))]
-
+         (->> chats
+              (reduce reduce-fn {})
+              (sort-by (comp :position second))
+              (map (fn [[k v]]
+                     [k (update v :chats #(sort-by :position %))])))]
```
Comment (ulisesmac) [inline src/status_im2/subs/communities.cljs:291]: :+1:

**Review by ulisesmac — COMMENTED** [review]
Hey @ilmotta !

I left some comments, sorry for the late review

File: src/status_im2/subs/communities.cljs (hunk 3 above)
Comment (ilmotta) [reply src/status_im2/subs/communities.cljs]: Unfortunately it's not a map @ulisesmac, it's a tuple permission id and the permission.

File: src/status_im2/subs/communities.cljs (hunk 4 above)
Comment (ilmotta) [reply src/status_im2/subs/communities.cljs]: I agree @ulisesmac, but this is the expectation in the quo component that actually uses this argument. If I do as you suggest, which I prefer, than the view will need to do extra transformation for the component, so in the end we would end up with more code and duplication.

Ideally the component should be refactored as well to not use `nil` to mean "no lock", but I prefer to not do this in this PR if possible.

Edit: Given that you commented, I will try to make this improvement in future iterations, because I'll surely be "around" the code using this subscription and the aforementioned component :)

File: src/status_im2/contexts/communities/overview/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/overview/view.cljs:100]: Correct @ulisesmac, here it's not a problem I believe, that's why I said *can cause problems*. I still prefer to almost never treat component functions as normal functions, unless maybe when playing in the REPL or doing something more advanced.

Although there's more than one way to do the same thing, I don't see a reason to call the component as a function and I prefer hiccup all the way whenever possible.

**Comment by ilmotta** [comment]
> Hey @ilmotta !
> 
> I left some comments, sorry for the late review

No worries, and thank you for reviewing @ulisesmac!

**Review by ulisesmac — APPROVED** [review]

**Comment by ilmotta** [comment]
@churik, in accordance to the [documentation](https://www.notion.so/Roles-and-permissions-11eeb193eaad4786b5cf190a831e956f?pvs=4#d17c62cb335b4585985816a9dd7e03b8) about the permission system written by @glitchminer, I just updated this PR to **not** treat "Become an admin" as a membership permission. The app behaves as follows:

```
Given that a community is *only* token gated by one or more admin permissions,
When a user is invited to that community,
They are allowed to join because there's no member permission.
```

Here's how the app should look with only admin permissions. They're not shown and the button is enabled. Quick note: this case is not covered in Figma, but looks okay for now as we are focusing on the behavior first.

**Comment by FFFra** [comment]
Amazing job!!!

**Comment by churik** [comment]
@ilmotta 
I retested it and seems we got a regression in regards to channel permissions.
Now lock icons are always shown on channels and user doesn't have access to them regardless they meet a requirements or not.

From the video below:
user has > 600 SNT on balance, trying to access the following community:
- 5 SNT to `View` `5_SNT_view` channel
- 5 SNT to `View and post` `5_SNT_view_post` channel
Tested on testnet/mainnet

https://github.com/status-im/status-mobile/assets/4557972/327bb5de-ef2a-42ca-a016-1fa90b3e2617

**Comment by ilmotta** [comment]
> @ilmotta I retested it and seems we got a regression in regards to channel permissions. Now lock icons are always shown on channels and user doesn't have access to them regardless they meet a requirements or not.
> 
> From the video below: user has > 600 SNT on balance, trying to access the following community:
> 
> * 5 SNT to `View` `5_SNT_view` channel
> * 5 SNT to `View and post` `5_SNT_view_post` channel
>   Tested on testnet/mainnet
> 
>  FILE.2023-11-07.15.10.57.mp4

Now you tell me why on earth, the flows that have bugs are the ones we don't check because devs trust their "instincts" too much 🤷🏼 

Jokes aside, thank you @churik, will check and fix. Hopefully it will be the last issue.

**Comment by ilmotta** [comment]
@churik: updates :) We were baffled today that even after going back to the commit that was supposed to work, even rolling back some commits in status-go too, unfortunately we could not get back to a state where the lock icon was correct because status-go would always return unexpected values to the `canPost` flag we were using.

We realized the current solution for the lock icons can't understand token permissions and that whatever worked in tests in this PR was by chance or mistake.

The good news is that we have a solid solution that can understand `view only` and `view and post` permissions. The solution is more involved, but will be pushed hopefully tomorrow, we will let you know.

**Comment by ilmotta** [comment]
@churik, we believe the PR is ready for another round of QA.

Here's a working example with minted tokens and a few channel permissions (you may need to open the image to see in higher resolution).



### Notes

- There's an open issue to not show the channel list in the token gated overview screen, unless the user has already joined. So for the moment, we can the channel list, but soon we'll only be able to check the lock icons after joining. We confirmed with Mario this should be the behavior. https://github.com/status-im/status-mobile/issues/17836
- The channel lock icons require checking if the account has enough resources. This now requires a separate RPC request to status-go, which can take a few seconds (1-3s usually). While the response hasn't arrived, no lock icons can be shown.

### Test cases

We used a few test cases to make sure everything is correct. For the expected results, assume the user has 0.5 eth.

```
| Become member       | none                                       |
| Channel permissions | none                                       |
| Expected            | Enabled button "Request to join community" |

| Become member       | 1 eth           |
| Channel permissions | none            |
| Expected            | Disabled button |

| Become member  | 0.01 |
| #view-only     | none |
| #view-and-post | none |
| Expected       | Enabled button "Join Community" |

| Become member  | none              |
| #view-only     | 10 eth            |
| #view-and-post | none              |
| Expected       | #view-only locked |

| Become member  | none                 |
| #view-only     | 10 eth               |
| #view-and-post | 10 eth               |
| Expected       | both channels locked |

| Become member  | none                                       |
| #view-only     | 10 eth                                     |
| #view-and-post | 0.01 eth                                   |
| Expected       | #view-only locked #view-and-post open lock |

| Become member  | none     |
| #view-only     | 0.01 eth |
| #view-and-post | 0.01 eth |
```

**Comment by pavloburykh** [comment]
@ilmotta thank you for the fixes

Regarding this comment

> At one point or another, I reach a state where I can see the community in my list of communities I joined even though I'm not listed in the desktop app as a member, and when I try to open any channel it says "You are not a member of this group". The only way to restore to the correct behavior is to leave the community on mobile and request to join again. I think this bug can be achieved while restoring from a seed phrase, but I don't have the exact reproduction steps yet.

In my case I always get "You are not a member of this group" for both "view only"/"view and post" channels thought permission requirements are met. 

I have tried to re-join community but it didn't help. 

All of token gated communities are newly created, mobile user who joins the community is not restored from seed phrase.

### ISSUE 1 "You are not a member of this group" in "view only"/"view and post" for user who meets permission requirements

**Steps:** 

1. Create token gated community: set permissions "view only" or "view and post" for one of the channel
2. Share community to mobile user. Mobile user should meet permission requirements. 
3. Join community by mobile user
4. Open channel with permissions by mobile user
5. Observe the result

**Actual result:** "You are not a member of this group" is displayed in the bottom. User is not able to view or post messages in the channel. 

[Status-debug-logs (80).zip](https://github.com/status-im/status-mobile/files/13308303/Status-debug-logs.80.zip)

Status Desktop 2023-11-09 14-49-09


https://github.com/status-im/status-mobile/assets/97245802/44c9ba59-ab07-4e1a-a34c-0973c6d89ed9

**Comment by ilmotta** [comment]
Hi @pavloburykh :)

This last problem we're seeing here is related to status-go alone, and it's out of scope for us to fix in this PR. I'll try to explain, because it's confusing.

If you look at the history of this PR's comments, you'll notice that icon locks were actually working when we opened the PR, even @churik could confirm, but then @churik reported we introduced a regression. We investigated, and even after rolling back the supposed regression commit (in this PR's branch) the code stopped working, probably because we rebased against `develop` and something changed in status-go.

Here's a proof. Video `A` is recorded pointing to `develop` 595b1cfc405e88c3476b214db50a3ee51bf45106, a commit merged just 19h ago. In it, we see I have enough money in the wallet, but the icon is displayed locked and I can't even open the chat. So a regression in status-go actually broke our mobile develop because this used to work a few days ago, I tested this exact flow dozens of times.

In video `B`, we see the fixed implementation for lock icons, but then, when I open the chat, we see the message "You are not a member of this group". That's because the chat screen is still using other mechanisms that don't play well with token gated communities. Something definitely changed in status-go, and in this PR we suffered from these changes, and our fix is only for the chat list and their icons, but the chat screens will need fixes as we can see.

I hope this clears up any confusion. We should definitely work on a fix, but it would be preferable to do this in a separate issue that we can play right after this one if it's the top priority.

`Video A` (bug in develop introduced while this PR was under review)

[bug develop.webm](https://github.com/status-im/status-mobile/assets/46027/d02f424f-8426-470e-b5fe-e2bef147af24)

`Video B` (working lock icons, allow chats to be open, but chat screens need separate fixes due to recent status-go changes)

[better with bug in chat.webm](https://github.com/status-im/status-mobile/assets/46027/d34a588a-edd0-4ca5-9e25-a1b229315015)

**Comment by pavloburykh** [comment]
@ilmotta in fact I am unable to pass happy flow for become member permission. 

### ISSUE 2 Unable to become member of community though member requirements are met

**Preconditions:** community has set permission requirements for becoming community member. Mobile user meets the requirements

**Case 1:** community that requires admin manual approval

**Steps:** 

1. Desktop user shares community to mobile user
2. Mobile user sends community join request
3. Desktop admin receives notification about join request
4. Admin user approves the request
5. Observe the result

**Actual result:** 

Approving of join request results for admin in the message below

Status Desktop 2023-11-09 15-35-58

**Screenshot from community permissions screen:**

Status Desktop 2023-11-09 15-44-16

**Video from mobile user who sends community request:** 


https://github.com/status-im/status-mobile/assets/97245802/4f639386-d486-4f91-8340-b3df85423266


**Expected result:** admin should be able to approve the request as mobile user meets permission requirements


**Case 2: does not require admin's manual approval**


**Steps:** 

1. Desktop user shares community to mobile user
2. Stay online by Desktop admin control node
3. Mobile user sends community join request
4. See if community status has automatically changed to Joined

**Actual result:** community remains in Pending status. 


https://github.com/status-im/status-mobile/assets/97245802/ae44bb08-ef34-460a-b6c2-26a1c75c69a8


**Expected result:** community status should be automatically changed Joined for mobile user.

**Comment by pavloburykh** [comment]
@ilmotta I believe that [ISSUE 2](https://github.com/status-im/status-mobile/pull/17799#issuecomment-1803905065) can be also related to the new bug introduced in status-go you are mentioning [here](https://github.com/status-im/status-mobile/pull/17799#issuecomment-1803900995), correct?

**Comment by ilmotta** [comment]
> @ilmotta I believe that [ISSUE 2](https://github.com/status-im/status-mobile/pull/17799#issuecomment-1803905065) can be also related to new bug introduced in status-go you are mentioning [here](https://github.com/status-im/status-mobile/pull/17799#issuecomment-1803900995), correct?

Yes @pavloburykh, we have started to see this error happen in the last few days. Other devs could also confirm, like @ajayesivan and @FFFra in their own tests. Unfortunately, in the last few days it has become increasingly difficult to join a community, something we did dozens of times right before opening this PR.

Edit: it's definitely new changes in status-go, things we haven't touched or are outside the control of the mobile code base.

**Comment by pavloburykh** [comment]
@ilmotta thank you so much for your work on this PR and all explanations. I believe we are ready to merge it. 

Are we currently tracking somewhere the above status-go issues?

**Comment by ilmotta** [comment]
> @ilmotta thank you so much for your work on this PR and all explanations. I believe we are to merge it.
> 
> Are we currently tracking somewhere the above status-go issues?

We were kind of waiting for QA to finish, so that we can make sense of all issues that are left to do because things were so unpredictable with communities. So the answer is no @pavloburykh, the issues still need to be created. If you already have some investigated, could we ask you to create them? We will then create any remaining ones (if any) that you haven't created yet.

Thank you for the quick reviews here o/

**Comment by ajayesivan** [comment]
@pavloburykh I have already created an issue for [case 1](https://github.com/status-im/status-mobile/pull/17799#issuecomment-1803905065): https://github.com/status-im/status-mobile/issues/17861

**Comment by pavloburykh** [comment]
> @pavloburykh I have already created an issue for [case 1](https://github.com/status-im/status-mobile/pull/17799#issuecomment-1803905065): #17861

Thank you @ajayesivan ! I have updated your issue with the case of no approval required community and the issue with "view only"/"view and post" channels
