### PR TITLE
[#19401] Wallet share QR code multiple fixes  

### LINKED ISSUE #19401: Share Wallet: error when scrolling between multiple QR codes
# Bug Report

## Problem 
**Cannot read property 'x' of undefined** error is shown when swiping accounts on Share Wallet screen

#### Expected behavior
Can scroll wallet accounts without any errors

#### Actual behavior

https://github.com/status-im/status-mobile/assets/29711298/3640eda6-0305-454c-90d7-28ac87ae74fd

Also on Android an address is cropped:

Screenshot 2024-03-26 at 13 38 47

On iOS it's not possible to swipe at all, error is shown immediately:
 

https://github.com/status-im/status-mobile/assets/29711298/536d2e68-2f4c-46c0-90be-9fbe4331f3da

### Reproduction

1. Add an additional account in the wallet
2. On the Home view click Show QR Code button
3. Click Wallet tab
4. Try swiping left and right to navigate between different accounts

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #19401

### Summary

The issues reported are:

- Exception while scrolling - No longer reproducible  :white_check_mark: 

- Image cropped in Android - Fixed :white_check_mark: 

  Reported vs now:
  Screenshot 2024-03-26 at 13 38 47 

Additionally,  solves some other bugs noticed while checking the code.

- The QR no longer blinks:

  Before:

  [Screencast from 2024-03-27 13-15-39.webm](https://github.com/status-im/status-mobile/assets/90291778/55c92416-eb2d-40db-813b-52c086c18b42)

  Now:

  [Screencast from 2024-03-27 13-16-50.webm](https://github.com/status-im/status-mobile/assets/90291778/78486196-d863-44be-8640-0a6c36e495a6)

- The bottom indicators (white dots) weren't accurately showing the focused QR:

  Before:
  
  [Screencast from 2024-03-27 14-53-05.webm](https://github.com/status-im/status-mobile/assets/90291778/8307e089-a3b7-40c1-89fe-a76c661e3d13)
  
  Now:
  
  [Screencast from 2024-03-27 14-53-45.webm](https://github.com/status-im/status-mobile/assets/90291778/44c2be74-7e80-4565-b817-88f74975ad49)

  
- Other code improvements

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Log in and click on the QR code icon
  image

- Change between tabs as showed in the videos.

status: ready

### CODE REVIEW

File: src/status_im/subs/general.cljs [hunk 1]
```diff
@@ -120,12 +120,12 @@
...
  :dimensions/window-width
  :<- [:dimensions/window]
- :width)
+ :-> :width)
 
 (re-frame/reg-sub
  :dimensions/window-height
  :<- [:dimensions/window]
- :height)
+ :-> :height)
```
Comment (ulisesmac) [inline src/status_im/subs/general.cljs:128]: Changed this style, based on re-frame reg-sub docs:


... 
For example, a significant number of subscriptions exist only to get a value
from the `input-values`. As shown below, this subscription will simply retrieve
the value associated with the `:foo` key in our db:

```clojure
(reg-sub
 :query-id
 (fn [db _]    ;; :<---- trivial boilerplate we might want to skip over
   (:foo db)))
```

This is slightly more boilerplate than we might like to do,
as we can use a keyword directly as a function, and we might like to do this:

```clojure
(reg-sub
 :query-id
 :foo)  ;; :<---- This could be dangerous. If `:foo` is not in db, we get the `query-vector` instead of `nil`.
```

By using `:->` our function would not contain the `query-vector`, and any
missing keys would be represented as such:

```clojure
(reg-sub
 :query-id
 :-> :foo)
```

This form allows us to ignore the `query-vector` if our `computation-function`
        has no need for it, and be safe from any accidents. Any 1-arity function can be provided,
and for more complicated use cases, `partial`, `comp`, and anonymous functions can still be used.

cc: @flexsurfer 
I've seen this is mostly used in the legacy code, should we remove them in a later refactor?
I believe `(rn/get-window)` is able to give us the same results without need to use re-frame.

File: src/status_im/contexts/shell/share/wallet/view.cljs [hunk 2]
```diff
@@ -79,54 +82,54 @@
...
-         [rn/view
-          {:style {:margin-top 20}}
-          (indicator-list (count accounts) @current-index)])])))
+      (let [accounts     (rf/sub [:wallet/accounts])
+            num-accounts (count accounts)
+            on-scroll    (rn/use-callback
+                          (fn [e]
+                            (let [offset-x (oops/oget e "nativeEvent.contentOffset.x")
+                                  index    (qr-code-visualized-index offset-x qr-code-size num-accounts)]
+                              (reset! current-index index))))]
```
Comment (ulisesmac) [inline src/status_im/contexts/shell/share/wallet/view.cljs:119]: This function works to calculate the highlighted dot below the QR codes, it has been changed to properly return the focused dot,

File: src/status_im/contexts/shell/share/wallet/view.cljs [hunk 3]
```diff
@@ -79,54 +82,54 @@
...
-         :shows-horizontal-scroll-indicator false
-         :on-scroll                         (fn [e]
-                                              (reset! current-index (js/Math.ceil
-                                                                     (/ e.nativeEvent.contentOffset.x
-                                                                        width))))
-         :render-fn                         render-item}]
-       (when (> (count accounts) 1)
-         [rn/view
-          {:style {:margin-top 20}}
-          (indicator-list (count accounts) @current-index)])])))
```
Comment (ulisesmac) [inline src/status_im/contexts/shell/share/wallet/view.cljs:132]: It was called as list instead of component, it's been fixed and also simplified

File: src/quo/components/share/share_qr_code/view.cljs [hunk 4]
```diff
@@ -188,21 +188,21 @@
...
                                   (clojure.set/rename-keys {:type :share-qr-type}))]
     [quo.theme/provider {:theme :dark}
      [rn/view
       {:accessibility-label :share-qr-code
        :style               style/outer-container
-       :on-layout           on-layout}
+       :on-layout           (when-not provided-width on-layout)}
       [rn/view {:style {:background-color style/overlay-color}}
-       (when component-width
+       (when (:component-width props)
```
Comment (ulisesmac) [inline src/quo/components/share/share_qr_code/view.cljs:205]: This component is able to receive `:width`, if provided we no longer need `on-layout`, it's being used to  skip the blink shown in the description's video

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/shell/share/profile/view.cljs [hunk 5]
```diff
@@ -16,16 +16,18 @@
...
+        customization-color   (rf/sub [:profile/customization-color])
+        abbreviated-url       (address/get-abbreviated-profile-url
+                               universal-profile-url)
+        emoji-hash-string     (string/join emoji-hash)]
     [rn/scroll-view
      {:content-container-style {:padding-bottom 16}}
      [rn/view {:style style/qr-code-container}
       [qr-codes/share-qr-code
        {:type                :profile
+        :width               (- window-width (* style/screen-padding 2))
```
Comment (ulisesmac) [inline src/status_im/contexts/shell/share/profile/view.cljs:30]: Provided to skip the blink in the profile QR

File: src/status_im/contexts/shell/share/wallet/view.cljs [hunk 6]
```diff
@@ -62,10 +64,11 @@
                                   :port        (rf/sub [:mediaserver/port])
                                   :qr-size     qr-size
                                   :error-level :highest})]
-        [rn/view {:style {:height qr-size :width width :margin-left (if (zero? index) 0 -30)}}
+        [rn/view {:style {:width window-width :margin-left (if (zero? index) 0 -30)}}
          [rn/view {:style style/qr-code-container}
           [quo/share-qr-code
            {:type                :wallet
+            :width               (- window-width (* style/screen-padding 2))
```
Comment (ulisesmac) [inline src/status_im/contexts/shell/share/wallet/view.cljs:71]: Provided to skip the blink in the wallet QRs

**Comment by J-Son89** [comment]
Thanks for the well described/documented pr. 🙏

**Comment by VolodLytvynenko** [comment]
HI @ulisesmac just curious, how did you get the case when your address became white? This screen is from the description https://github.com/status-im/status-mobile/pull/19425#issue-2211899174
image

**Review by smohamedjavid — APPROVED** [review]
Nice work! 🙌

**Review by clauxx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac thank you for the fix! Ready for merge and cherrypicking.

**Comment by ulisesmac** [comment]
> HI @ulisesmac just curious, how did you get the case when your address became white? This screen is from the description [#19425 (comment)](https://github.com/status-im/status-mobile/pull/19425#issue-2211899174) image

Hi @VolodLytvynenko !

You just need to create a wallet account in desktop and use the Yin Yang theme color

**Comment by J-Son89** [comment]
Just an fyi we haven't added support for yin-yang yet but we can figure it out in the offsite @ulisesmac - we have most of the solution from before when we discussed it in Porto
