### PR TITLE
Fix reaction images and implement Selectors > Reactions component

### LINKED ISSUE #16045: Fix red borders and use correct reaction icons
# Problem

- [ ] Sad icon is outdated.
- [ ] Red borders can be removed.

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/16045

### Summary

This PR fixes reaction images and implements the component `Selectors > Reactions` that, for some reason, wasn't implemented as a separate quo2 component as per [Figma](https://www.figma.com/file/qLLuMLfpGxK9OfpIavwsmK/Iconset?type=design&node-id=942-218&t=cqTr12Q3zVHaLoap-0).

#### Drawer

<table>
  <thead>
    <tr>
      <th>🐛🐜</th>
      <th>Fixed</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

### Review notes

Reaction images in the Design System are not icons, so that's why you are seeing a bunch of icons removed from `icons2`. The directory `resources/images/reactions` already existed, and so I used images from that directory instead.

#### Platforms

- Android
- iOS

### Steps to test

- Open any chat and try to react. Try also to open the message drawer to see the fixed reactions.
- You can also check out the previews in `Selectors > reactions`.

status: ready

### CODE REVIEW

File: src/quo2/components/reactions/resource.cljs [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+  (:require-macros [quo2.components.reactions.resource :refer [resolve-all-reactions]]))
+
+(def ^:private reactions
+  (resolve-all-reactions))
+
+(defn get-reaction
+  [reaction]
+  (assert (keyword? reaction) "Reaction should be a keyword")
+  (assert (= "reaction" (namespace reaction))
+          "Reaction keyword should be namespaced with :reaction")
```
Comment (J-Son89) [inline src/quo2/components/reactions/resource.cljs:11]: why not `:r/` ? 🤔 we have `i` for icon, `t` for translation already

Comment (J-Son89) [reply src/quo2/components/reactions/resource.cljs:11]: either way, do we need to update docs?

File: src/quo2/components/selectors/reactions/view.cljs [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+                 accessibility-label]
+          :or   {accessibility-label :reaction}}]
+      [rn/touchable-without-feedback
+       {:accessibility-label accessibility-label
+        :on-press            (fn [e]
+                               (swap! pressed? not)
+                               (when on-press
+                                 (on-press e)))}
+       [rn/view
+        {:test-ID (if @pressed? :pressed :released)
```
Comment (J-Son89) [inline src/quo2/components/selectors/reactions/view.cljs]: should we use an accessibility label instead?

**Review by J-Son89 — APPROVED** [review]
nit: this pr could be split into two - one for adding component to quo2 (no QA needed - quick merge) the second to add the app code (which would need QA)
It's fine as is but just a thought for future work 👍

**Review by J-Son89 — APPROVED** [review]
nit: this pr could be split into two - one for adding component to quo2 (no QA needed - quick merge) the second to add the app code (which would need QA)
It's fine as is but just a thought for future work 👍

File: src/quo2/components/reactions/resource.cljs (hunk 1 above)
Comment (ilmotta) [reply src/quo2/components/reactions/resource.cljs:11]: I thought about this @J-Son89, but icons are ubiquitous and often used statically, whereas reactions are mostly dynamic content, so we'll rarely use them as we use icons. Thus, IMO saving characters would hurt readability.

File: src/quo2/components/selectors/reactions/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/quo2/components/selectors/reactions/view.cljs]: I opted for a test-ID because the accessibility ID is already used in the touchable above, and this one would have no purpose except for the component spec. I can change to `accessibility-id` though :)

**Review by flexsurfer — APPROVED** [review]

File: src/quo2/components/selectors/reactions/view.cljs [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+         :style   (merge (style/container @pressed?)
+                         container-style)}
+        [rn/image
+         {:source (reactions.resource/get-reaction emoji)
+          :style  {:width 20 :height 20}}]]])))
```
Comment (ulisesmac) [inline src/quo2/components/selectors/reactions/view.cljs:25]: Missing empty extra line at the end of the file

File: src/quo2/components/selectors/reactions/view.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/quo2/components/selectors/reactions/view.cljs]: Why do we need to expose the pressed state of a view through `:test-ID`?
I think if we want to test if something has been pressed, we can use a mock callback and some RTL functions.

Probably this is not the best use of `:test-ID` :thinking:  wdyt?

File: src/quo2/components/selectors/reactions/view.cljs [hunk 4]
```diff
@@ -0,0 +1,26 @@
+(ns quo2.components.selectors.reactions.view
+  (:require [quo2.components.reactions.resource :as reactions.resource]
+            [quo2.components.selectors.reactions.style :as style]
+            [react-native.core :as rn]
+            [reagent.core :as reagent]))
+
+(defn view
+  [_ {:keys [start-pressed?]}]
+  (let [pressed? (reagent/atom start-pressed?)]
+    (fn [emoji
```
Comment (ulisesmac) [inline src/quo2/components/selectors/reactions/view.cljs:10]: About the function signature, why are we receiving the emoji as a separate parameter?

I thnk it'd be more consistent if we receive everything inside a single parameter map,

**Review by ulisesmac — COMMENTED** [review]
Nice :+1: 

 I left some comments :)

File: src/quo2/components/selectors/reactions/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/quo2/components/selectors/reactions/view.cljs]: FYI: So in the end, after talking to @ulisesmac, I removed these assertions because they're testing an internal implementation.

**Review by ulisesmac — APPROVED** [review]

File: src/quo2/components/selectors/reactions/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/quo2/components/selectors/reactions/view.cljs]: FYI: So in the end, after talking to @ulisesmac, I removed these assertions because they're testing an internal implementation.

**Comment by pavloburykh** [comment]
@ilmotta thank you for the PR! Looks good to me. 

One small request: could you please add old acc ids for each of the reactions (both under the message and within the drawer). 

**Expected result:** 

In e2e we are using the following ones: emoji-picker-1, emoji-picker-2; emoji-picker-3; emoji-picker-4; emoji-picker-5; emoji-picker-6

Appium 2023-06-01 15-23-25

**OR** if it is more comfortable for you then you can leave new acc ids "emoji-reaction-1" (2,3,4,5,6) but please also add them for the reactions within the drawer, cause currently there are no ids there. 

Appium 2023-06-01 15-40-07

Appium 2023-06-01 15-58-43


If option with leaving new ids is more comfortable for you, please let me know and I will update e2e accordingly. Thank you.

**Comment by ilmotta** [comment]
> One small request: could you please add old acc ids for each of the reactions (both under the message and within the drawer).

No problem @pavloburykh, thanks for promptly testing the PR. Just curious, are the suffixes 1, 2, 3 necessary or can you query the structure yourself to get the emoji you want? Like, from your end, can you query the third emoji without developers having to add the numbers at the end of the accessibility labels?

I'm asking this because if devs can just add a fixed accessibility label, like `emoji-picker` and then on the QA end you choose the index you want, it would be slightly easier for us than having to create dynamic accessibility labels like `emoji-picker-1` and so on.

Edit: Talked with @churik now, I'll change the labels to `emoji-thumbs-up`, `emoji-thums-down`, etc, since she told me it's more reliable for automating the tests instead of indexes.

**Comment by pavloburykh** [comment]
> Edit: Talked with @churik now, I'll change the labels to `emoji-thumbs-up`, `emoji-thums-down`, etc, since she told me it's more reliable for automating the tests instead of indexes.

Sounds good! Thank you @ilmotta and @churik
