### PR TITLE
[17634] Start rendering syncing UI ASAP

### LINKED ISSUE #17634: Indicate progress and error in case of syncing devices
# Bug Report

## Problem 
Currently app just stuck on the same screen in case of syncing / getting error

#### Expected behavior
1) Syncing is shown as per design [here](https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179660&mode=design&t=XLVqA7gTpM88imPD-4) 

2) In case of error[]( https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179641&mode=design&t=XLVqA7gTpM88imPD-4) - or at least display an error somehow in a raw format

#### Actual behavior
Video: https://github.com/status-im/status-mobile/assets/4557972/649b3f41-629e-4327-9df4-1d5774c0a23a

### Reproduction

1. Try to sync for example devices on different networks
2. Observe the result

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17634

### Summary

Handle error when syncing fails and also show the UI immediately this happens.

There's a possibility that syncing fails/starts before showing the UI to indicate it's processing.
This PR fixes that.

status: ready

Unfortunately I don't have the ability to post before and after of this as I don't have access to multiple WiFi networks to test.

### CODE REVIEW

File: src/status_im/signals/core.cljs [hunk 1]
```diff
@@ -30,18 +30,19 @@
...
-        receiver?                       (= role constants/local-pairing-role-receiver)
+        receiver?                       (or (= role constants/local-pairing-role-receiver)
+                                            receiving-device?)
         sender?                         (= role constants/local-pairing-role-sender)
         connection-success?             (and (= type
                                                 constants/local-pairing-event-connection-success)
                                              (= action
                                                 constants/local-pairing-action-connect))
-        error-on-pairing?               (contains? constants/local-pairing-event-errors type)
+        error-on-pairing?               (get constants/local-pairing-event-errors type :generic-error)
```
Comment (qfrank) [inline src/status_im/signals/core.cljs]: i'm surprised we didn't use `error` from `event` to check if there is an error , intead we check `type`

File: src/status_im2/contexts/syncing/events.cljs [hunk 2]
```diff
@@ -52,27 +53,35 @@
...
+                includes-error? #(string/includes? res "error")]
             (rf/dispatch [:syncing/update-role constants/local-pairing-role-receiver])
             (native-module/input-connection-string-for-bootstrapping
              connection-string
              config-map
-             #(log/info "Initiated local pairing"
-                        {:response %
-                         :event    :syncing/input-connection-string-for-bootstrapping}))))]
+             (fn [res]
+               (signals/handle-local-pairing-signals
```
Comment (qfrank) [inline src/status_im2/contexts/syncing/events.cljs]: the function name `signals/handle-local-pairing-signals` is only used for handling local pairing signals rather than returning value from `InputConnectionStringForBootstrapping` , i'm very struggling for such usage. 🥹

File: src/status_im2/contexts/syncing/events.cljs [hunk 3]
```diff
@@ -52,27 +53,35 @@
...
+          (let [config-map      (.stringify js/JSON
+                                            (clj->js
+                                             {:receiverConfig
+                                              {:kdfIterations config/default-kdf-iterations
+                                               :nodeConfig final-node-config
+                                               :settingCurrentNetwork config/default-network
+                                               :deviceType platform/os
+                                               :deviceName
+                                               (native-module/get-installation-name)}}))
+                includes-error? #(string/includes? res "error")]
```
Comment (smohamedjavid) [inline src/status_im2/contexts/syncing/events.cljs]: I think you have intended to use the `%` (percentage) for receiving the argument as this is an anonymous function.

Additionally, I believe the argument received in the callback is an object/map which will contain an `error` key. We can use that to check and dispatch a toast if the error key value is non-empty.

File: src/status_im/signals/core.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/signals/core.cljs]: We have a generic error check in the signals. But we haven't added the complete error flows in the mobile yet.

https://github.com/status-im/status-mobile/blob/55b233c528da4a6ece3b3a28cc50fa7e298eba05/src/status_im/signals/core.cljs#L84-L88

We can remove the `error-on-pairing?` var (and the condition) to freely dispatch the toast if there is any error received in the local pairing signals.

File: src/status_im2/contexts/syncing/events.cljs (hunk 2 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/events.cljs]: @ibrkhalil - Using the signal ns for handling response/data other than signals is not a good approach. 

We can create a separate re-frame event for the callback. We can log and check the response and dispatch a toast if needed.

Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/events.cljs]: The callback in the `input-connection-string-for-bootstrapping` is executed after the completion of local pairing events/signals. If there is any error while initiating, the callback will be executed without the signals/events. It's good to have the callback handled in a separate event.

File: src/status_im2/contexts/syncing/events.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/syncing/events.cljs]: I thought since JSON is returned as a string, We could just search all of it for an error.
Instead of converting it to CLJS structures like maps and then only checking specific keys.

**Comment by ibrkhalil** [comment]
I am currently working on something else, Going to get back to this discussion later today.

File: src/status_im2/contexts/syncing/events.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/syncing/events.cljs]: I agree, Going to refactor it later today.

File: src/status_im2/contexts/syncing/events.cljs [hunk 4]
```diff
@@ -52,27 +53,40 @@
...
+          (let [config-map      (.stringify js/JSON
+                                            (clj->js
+                                             {:receiverConfig
+                                              {:kdfIterations config/default-kdf-iterations
+                                               :nodeConfig final-node-config
+                                               :settingCurrentNetwork config/default-network
+                                               :deviceType platform/os
+                                               :deviceName
+                                               (native-module/get-installation-name)}}))
+                includes-error? (fn [json-str]
```
Comment (flexsurfer) [inline src/status_im2/contexts/syncing/events.cljs]: this should be defined function outside handler

File: src/status_im2/contexts/syncing/events.cljs [hunk 5]
```diff
@@ -52,27 +53,40 @@
...
+                                      (and (not (nil? error-value)) (not (empty? error-value))))))]
             (rf/dispatch [:syncing/update-role constants/local-pairing-role-receiver])
             (native-module/input-connection-string-for-bootstrapping
              connection-string
              config-map
-             #(log/info "Initiated local pairing"
-                        {:response %
-                         :event    :syncing/input-connection-string-for-bootstrapping}))))]
+             (fn [res]
+               (signals/handle-local-pairing-signals
```
Comment (ibrkhalil) [inline src/status_im2/contexts/syncing/events.cljs]: This view needs to be abstracted so that it's not only specified for usage only by signals.

File: src/status_im2/contexts/syncing/events.cljs [hunk 6]
```diff
@@ -52,27 +69,29 @@
...
+                                          :deviceName
+                                          (native-module/get-installation-name)}}))]
             (rf/dispatch [:syncing/update-role constants/local-pairing-role-receiver])
             (native-module/input-connection-string-for-bootstrapping
              connection-string
              config-map
-             #(log/info "Initiated local pairing"
-                        {:response %
-                         :event    :syncing/input-connection-string-for-bootstrapping}))))]
+             (fn [res]
```
Comment (flexsurfer) [inline src/status_im2/contexts/syncing/events.cljs]: im not sure why anon function is needed, why `handle-connection-string-error` can't be used directly

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/contexts/syncing/events.cljs [hunk 7]
```diff
@@ -36,6 +37,24 @@
                                        :custom-bootnodes-enabled? false}}]
     (node/get-multiaccount-node-config db)))
 
+(defn- includes-error?
+  [json-str]
+  (let [data (-> json-str
+                 js/JSON.parse
+                 (js->clj :keywordize-keys true))]
+    (-> (get data :error)
+        (#(and (not (nil? %)) (boolean (seq %)))))))
```
Comment (smohamedjavid) [inline src/status_im2/contexts/syncing/events.cljs]: We can use the `json->clj` from `utils.transform` ns as it has the `keywordize-keys` config.

Additionally, we can write this function

```clojure
(defn- includes-error?
  [json-str]
  (-> json-str
      transforms/json->clj
      (get :error "") ;; we set the empty string as a fallback so that we can skip the `nil?` check
      not-empty)) ;; `not-empty` on empty string would result in `nil`

```

File: src/status_im2/contexts/syncing/events.cljs [hunk 8]
```diff
@@ -36,6 +37,24 @@
...
+
+(defn- handle-connection-string-error
+  [res]
```
Comment (smohamedjavid) [inline src/status_im2/contexts/syncing/events.cljs:48]: It's a good practice to log the response for debugging purposes.

```clojure
#(log/info "[local-pairing] input-connection-string-for-bootstrapping callback"
           {:response res
            :event    :syncing/input-connection-string-for-bootstrapping})
```

File: src/status_im2/contexts/syncing/events.cljs [hunk 9]
```diff
@@ -52,27 +71,26 @@
...
+                                          :deviceName
+                                          (native-module/get-installation-name)}}))]
             (rf/dispatch [:syncing/update-role constants/local-pairing-role-receiver])
             (native-module/input-connection-string-for-bootstrapping
              connection-string
              config-map
-             #(log/info "Initiated local pairing"
-                        {:response %
-                         :event    :syncing/input-connection-string-for-bootstrapping}))))]
+             handle-connection-string-error)))]
```
Comment (smohamedjavid) [inline src/status_im2/contexts/syncing/events.cljs]: I would suggest renaming this method to ` input-connection-string-callback` as this is a callback.

File: src/status_im2/contexts/syncing/events.cljs [hunk 10]
```diff
@@ -52,27 +71,26 @@
 (rf/defn initiate-local-pairing-with-connection-string
   {:events       [:syncing/input-connection-string-for-bootstrapping]
    :interceptors [(re-frame/inject-cofx :random-guid-generator)]}
-  [{:keys [random-guid-generator db]} connection-string]
+  [{:keys [random-guid-generator db] :as cofx} connection-string]
```
Comment (smohamedjavid) [inline src/status_im2/contexts/syncing/events.cljs]: I guess we are not using the `cofx`. We can remove it.

**Comment by siddarthkay** [comment]
Hmm @BalogunofAfrica : I see that all what we're doing here in this PR is identifying the error and displaying a toast asap.
could you pls update the PR title that matches this change and maybe some minimalistic description would also help.

**Review by siddarthkay — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil the issue is resolved when scanning a valid sync QR code. However, there's still no response when a specific environment is used, such as having different networks for devices.

### ISSUE 1: [IOS] The error is not shown when devices use different networks while QR scanning

### Steps:
1. Android and IOS devices connected to different networks
2. Android generates its QR code.
3. iOS device scans the QR.

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/9254cda3-0116-4de1-9e6b-a7367878c94d


### Expected result:
The error should be shown

### Devices:
- iPhone 11 Pro max, IOS 16.6

### Additional info:
Unfortunately, I can't share logs when this screen is stuck. Tapping the 'Share Logs' option is unresponsive while the issue is occurring on iOS. In the case of Android scanning the QR, this issue is not reproducible, and Android syncs successfully.

**Review by qfrank — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@ibrkhalil One question: Should the sync process page be implemented in the scope of this PR, as described in the expected result of the related issue https://github.com/status-im/status-mobile/issues/17634#issue-1942118633, or will it be implemented separately? For now, the old screen is still being displayed.

### Actual result:
image

### Expected result:
https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179660&mode=design&t=XLVqA7gTpM88imPD-4

image

**Comment by BalogunofAfrica** [comment]
@VolodLytvynenko The scope of this PR is to show the progress while syncing and an error if one occurs.

I think it would be implemented separately

**Comment by VolodLytvynenko** [comment]
According to [this comment](https://github.com/status-im/status-mobile/issues/17634#issuecomment-1806768628), I propose merging this PR. Currently, there is no response from `status-go` for IOS, and we need to wait until it's implemented there. Merging this PR makes sense, especially since it works well for Android. After the response will be implemented on the Status go part, we can return to this issue. 
@ibrkhalil @BalogunofAfrica WDYT?
