### PR TITLE
Fix send no bonder fee included

### LINKED ISSUE #21097: Wallet does not account bonder fee in transactions which include Hop bridging
Our wallet currently does not account for the bonder fee, which results in the following discrepancies:

**1. Incorrect Calculation of Maximum Amount:** The maximum amount available for transfer is inaccurately displayed, leading to confusion for users.

**2. Misleading Final Value(which has higher priority):** The final amount received by users is not accurately reflected, particularly in transactions involving smaller amounts. For instance, when sending 0.5 DAI from Optimism to Arbitrum, users are shown that the receiver will receive 0.497 DAI. However, the actual amount received is only 0.23642046 DAI due to the bonder fee deducted by the Hop bridge (so on small amount it can easily be more 50% of the initial value)

While this discrepancy may be less noticeable in larger transactions, it  misleads users and undermines their trust in our platform.

**Steps:** 

1. Perform transaction which includes bridging. For example: send 0.5 DAI from Optimism to Arbitrum
2. Before Signing the transaction pay attention what final receiver amount is shown on Confirmation screen in Status App
3. Compare the actual received amount to the amount shown on confirmation screen after transaction is completed.  

**Actual result:** 

1. 0,497 DAI is shown in `Receiver gets`

photo_2024-08-21 10 00 46

2. Actual amount received by receiver is 0.23426246 DAI

received

Link to transaction at hop explorer https://explorer.hop.exchange/?transferId=0x86e020584d98b600cde1f2d284b90162de2b2e773229adccfe6126b7ac9c5a29

[Status-debug-logs - 2024-08-21T101234.382.zip](https://github.com/user-attachments/files/16687466/Status-debug-logs.-.2024-08-21T101234.382.zip)

### Additional Information

- Status version: nightly, release
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by clauxx**
fixes #21097

### Summary

For the "Recipient gets" field, show the `estimated-received` amount that takes into account the bonder fee, which would be equivalent to `amount-in - tx-token-fees` according to [this line](https://github.com/status-im/status-go/blob/2c430568b108b5080852dd60e669b92ac5631865/services/wallet/router/pathprocessor/processor_bridge_hop.go#L425).

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/utils.cljs [hunk 1]
```diff
@@ -61,6 +61,22 @@
...
+           amount             (money/with-precision
+                               (if native-token?
+                                 (money/wei->ether estimated-received)
+                                 (money/token->unit estimated-received
+                                                    token-decimals))
+                               6)
+           chain-id           (get-in path [:to :chain-id])]
+       (update acc chain-id money/add amount)))
+   {}
+   route))
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/utils.cljs]: Would be great to add some unit tests for this function

File: src/status_im/contexts/wallet/send/utils.cljs [hunk 2]
```diff
@@ -61,6 +61,22 @@
...
+  [{:keys [route token-decimals native-token?]}]
+  (reduce
+   (fn [acc path]
+     (let [estimated-received (:estimated-received path)
+           amount             (money/with-precision
+                               (if native-token?
+                                 (money/wei->ether estimated-received)
+                                 (money/token->unit estimated-received
+                                                    token-decimals))
+                               6)
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/utils.cljs]: We are using this `6` value for limiting decimals in many places, would be great to add a constant for it.

Comment (clauxx) [reply src/status_im/contexts/wallet/send/utils.cljs]: done :+1:

File: src/status_im/contexts/wallet/send/utils.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/send/utils.cljs]: done :+1:

**Review by ulisesmac — APPROVED** [review]
LGTM

**Review by briansztamfater — APPROVED** [review]

**Comment by clauxx** [comment]
@status-im/mobile-qa ready for testing

**Comment by pavloburykh** [comment]
@clauxx thanks for the PR. Unfortunately testing of this PR is partially blocked because L2 - L1 transactions are constantly failing in blockchain. It seems to be some third party issue (on hopper side) and I have logged a separate ticket on this https://github.com/status-im/status-mobile/issues/21180 .

At the same time I was able to perform L2-L2 (Arbitrum - Optimism).

So far, I have 1 question: is it expected that we show different values in `Recepient gets` and within Recepient route element? 

Shouldn't we show in both places the final value from `Recepient gets`?

photo_2024-09-05 13 01 16

**Comment by clauxx** [comment]
> @clauxx thanks for the PR. Unfortunately testing of this PR is partially blocked because L2 - L1 transactions are constantly failing in blockchain. It seems to be some third party issue (on hopper side) and I have logged a separate ticket on this #21180 .
> 
> At the same time I was able to perform L2-L2 (Arbitrum - Optimism).
> 
> So far, I have 1 question: is it expected that we show different values in `Recepient gets` and within Recepient route element?
> 
> Shouldn't we show in both places the final value from `Recepient gets`?
> ...

@pavloburykh Not sure which way is best, but I understand your UX concern. I used the Hop exchange (which we use as well) as reference and it looks the same there (see screenshot below). I can adjust so both values are the same if needed.

cc: @shivekkhurana @xAlisher

image

**Comment by clauxx** [comment]
@shivekkhurana @xAlisher can you have a look at the question above please? Not very urgent though, since fully testing this PR is still blocked.

**Comment by VolodLytvynenko** [comment]
I'll check this PR tomorrow, it seems like we've been unblocked

**Comment by VolodLytvynenko** [comment]
Hi  @clauxx  Could you please resolve conflicts and rebase the current PR? Thanx

**Comment by xAlisher** [comment]
image
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=17541-134301&t=1HJbDbCP3YWf6d0M-1

@shivekkhurana

**Comment by clauxx** [comment]
@xAlisher just to confirm, the "To" value will be larger than the "Bridged to ..." value

**Comment by pavloburykh** [comment]
> Hi @clauxx Could you please resolve conflicts and rebase the current PR? Thanx

@VolodLytvynenko before re-testing this PR we need to get latest go in mobile, cause we need this fix https://github.com/status-im/status-go/pull/5915 So please, do not start re-testing until go version is bumped in mobile develop (we will need to rebase this PR once again after it is done). I will ping you up once it will be ready.

**Comment by clauxx** [comment]
@VolodLytvynenko Also, i'll have to add the new design for the bonder fee, so I'll remove it from testing for now.

**Comment by xAlisher** [comment]
@clauxx @pavloburykh, please note that this is just a draft for now. If it works for you, I'll need to get approval from @pedro-et before moving forward.

**Comment by pavloburykh** [comment]
> @clauxx @pavloburykh, please note that this is just a draft for now. If it works for you, I'll need to get approval from @pedro-et before moving forward.

@clauxx @xAlisher are those UI changes critical for us in terms of 2.31? 

The point is that we would like to include current PR into release and we are about to cut release branch soon. Maybe we can proceed with new UI improvement separately in order not to block this PR from testing and merging? WDYT? 

cc @churik

**Comment by churik** [comment]
I'd say it is nice-to-have for 2.31 and would postpone it to the next release, I'd vote for fixing the functional issue first.

**Comment by clauxx** [comment]
> I'd say it is nice-to-have for 2.31 and would postpone it to the next release, I'd vote for fixing the functional issue first.

In that case if there are no issues then, we can merge, right?

**Comment by xAlisher** [comment]
> @xAlisher are those UI changes critical for us in terms of 2.31?

I do not think it's critical. Anyway design is updated and approved https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=17541-134301&t=ZIS94nOLdZlNKOl5-1

**Comment by pavloburykh** [comment]
> In that case if there are no issues then, we can merge, right?

@clauxx we still need to check L1-L2 bridge. I am waiting for bumping go version in mobile develop. We will ping you up once PR is ready for merge. Thank you.

**Comment by pavloburykh** [comment]
@clauxx sorry, can I ask you to rebase one more time. Status go has been updated in mobile develop and we need those fixes to test the PR. I have tried to rebase myself by there are conflicts that should be resolved.

**Comment by clauxx** [comment]
> @clauxx sorry, can I ask you to rebase one more time. Status go has been updated in mobile develop and we need those fixes to test the PR. I have tried to rebase myself by there conflicts that should be resolved. 

no worries, done 👍

**Comment by pavloburykh** [comment]
Unfortunately L1-L2 transactions still failing so this issue is valid https://github.com/status-im/status-mobile/issues/21180 and it blocks us from testing L1-L2 bridge in this PR.  @churik @shivekkhurana I am not sure what to do with that. It seems to be third party issue, but it blocks us from properly testing this PR. Do you consider we can skip L1-L2 check in order to unblock this PR? 

@clauxx At the same time, I see issue related to calculation of Recipient gets value when building L1-L2 routes, please take a look at the issues below. 

### ISSUE 1 NaN `Recipient gets` value when bridging L1 - L2 Optimism

**Steps:** 

1. Build routes from L1 to L2 Optimism (I used Eth for testing)
2. Pay attention at Recipient gets value

**Actual result:** NaN value

photo_2024-10-11 19 26 11
[Status-debug-logs - 2024-10-11T192357.595.zip](https://github.com/user-attachments/files/17345312/Status-debug-logs.-.2024-10-11T192357.595.zip)

https://github.com/user-attachments/assets/0fa3718b-2db2-4d70-a589-0ec3871f46b3

**Comment by pavloburykh** [comment]
### ISSUE 2 `Recipient gets` value is larger than `To` value when bridging L1 - L2 Arbitrum

@clauxx this one is reproducible in develop as well. I guess it would be nice to handle it in scope of this PR. WDYT?

**Steps:** 

1. Built L1 - L2 Arbitrum route (I used Eth for testing)
2. Compare To and Recipient gets values

**Actual result:** Recipient gets is larger than To value

[Status-debug-logs - 2024-10-11T193530.378.zip](https://github.com/user-attachments/files/17345404/Status-debug-logs.-.2024-10-11T193530.378.zip)

photo_2024-10-11 19 35 58

File: src/quo/components/settings/data_item/view.cljs [hunk 3]
```diff
@@ -55,26 +55,36 @@
...
+      title]
+     (when title-icon
+       [icons/icon title-icon
+        {:accessibility-label :title-icon
+         :size                12
+         :color               (if blur?
+                                colors/neutral-40
+                                (colors/theme-colors colors/neutral-50
+                                                     colors/neutral-40
+                                                     theme))}])]))
```
Comment (clauxx) [inline src/quo/components/settings/data_item/view.cljs:74]: changes to quo according to [design](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=17540-134158&t=2msz3vUxSiuclXfG-4)

File: src/status_im/contexts/wallet/data_store.cljs [hunk 4]
```diff
@@ -212,13 +212,12 @@
 
 (defn new->old-route-path
   [new-path]
-  (let [bonder-fees (:tx-bonder-fees new-path)
-        token-fees  (+ (money/wei->ether bonder-fees)
-                       (money/wei->ether (:tx-token-fees new-path)))]
+  (let [bonder-fees (-> new-path :tx-bonder-fees money/bignumber)
+        token-fees  (-> new-path :tx-token-fees money/bignumber)]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/data_store.cljs:237]: `:tx-token-fees` is the difference between `:amount-in` and the value the receiver gets ("estimated-received"), so it already includes the bonder fees

File: src/status_im/contexts/wallet/send/input_amount/estimated_fees.cljs [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+              :subtitle        amount}
+
+       (= tx-type :tx/bridge)
+       (assoc
+        :title-icon :i/info
+        :title      (i18n/label :t/bridged-to
+                                {:network full-name})
+        :on-press   show-bonder-fee-info))]))
+
+(defn view
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/input_amount/estimated_fees.cljs:47]: extracted the `estimated-fees` component into its own namespace, cause the `input-amount.view` namespace was getting too crowded. Added subscriptions only for the `received-amount`, but the fees should also be moved into subs and used here at some other point.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 6]
```diff
@@ -165,7 +137,6 @@
   ;; for component tests only
   [{default-on-confirm       :on-confirm
     default-limit-crypto     :limit-crypto
-    default-crypto-decimals  :crypto-decimals
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:168]: the component tests are stubbing this value, so we no longer need the default here.

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 7]
```diff
@@ -247,20 +247,22 @@
...
-                                     :else network-value-type)]
+                  (let [status           (cond (and (= network-value-type :not-available)
+                                                    loading-routes?
+                                                    token-not-supported-in-receiver-networks?)
+                                               :loading
+                                               (= network-value-type :not-available)
+                                               :disabled
+                                               :else network-value-type)
+                        amount-formatted (-> (rf/sub [:wallet/send-amount-formatted total-amount])
+                                             (str " " token-symbol))]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/routes/view.cljs]: using consistent formatting of the values based on the calculated `token-decimals`. Otherwise the `total-amount` can be shown as bigger than the `out-amount` due to rounding, which is wrong.

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 8]
```diff
@@ -165,10 +165,11 @@
     :subtitle        subtitle}])
 
 (defn- transaction-details
-  [{:keys [estimated-time-min max-fees token-display-name amount to-network route
+  [{:keys [estimated-time-min max-fees to-network route
            transaction-type]}]
   (let [route-loaded?             (and route (seq route))
-        loading-suggested-routes? (rf/sub [:wallet/wallet-send-loading-suggested-routes?])]
+        loading-suggested-routes? (rf/sub [:wallet/wallet-send-loading-suggested-routes?])
+        amount                    (rf/sub [:wallet/send-total-amount-formatted])]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:172]: showing same `total-amount` on the `transaction-confirmation` screen as on the `input-amount` one

File: src/status_im/contexts/wallet/send/utils.cljs [hunk 9]
```diff
@@ -43,21 +41,67 @@
...
+
+(defn- path-amount-out
+  [path]
+  (if (-> path :bridge-name (= constants/bridge-name-hop))
+    (let [{:keys [token-fees bonder-fees amount-in]} path]
+      (-> amount-in
+          money/from-hex
+          (money/sub token-fees)
+          (money/add bonder-fees)))
+    (-> path :amount-out money/from-hex)))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/utils.cljs]: for the bridge out amount, we should show the value with the fees substracted, but not the bonder-fees, which are accounted for in the `estimated-received` value. This matches how [hop displays the bridge calculations](https://app.hop.exchange/#/send?sourceNetwork=ethereum&destNetwork=arbitrum&token=ETH).

File: src/status_im/subs/wallet/wallet.cljs [hunk 10]
```diff
@@ -153,7 +153,8 @@
 (rf/reg-sub
  :wallet/wallet-send-token-symbol
  :<- [:wallet/wallet-send]
- :-> :token-symbol)
+ (fn [{:keys [token-symbol token]}]
+   (or token-symbol (:symbol token))))
```
Comment (clauxx) [inline src/status_im/subs/wallet/wallet.cljs:158]: seems like the send flow is initialized with either the `token-symbol` or the `token`, depending on where the flow has started.

**Comment by clauxx** [comment]
@briansztamfater @ulisesmac @shivekkhurana please have another look, as there are a few new changes in this PR since you last reviewed it.

File: src/status_im/contexts/wallet/send/input_amount/estimated_fees.cljs [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+   (when (ff/enabled? ::ff/wallet.advanced-sending)
+     [rn/view {:style style/estimated-fees-content-container}
+      [quo/button
+       {:icon-only?          true
+        :type                :outline
+        :size                32
+        :inner-style         {:opacity 1}
+        :accessibility-label :advanced-button
+        :disabled?           loading-routes?
+        :on-press            #(js/alert "Not implemented yet")}
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/send/input_amount/estimated_fees.cljs]: We have a common/not-implemented function somewhere. That is useful for a grep lookup of things that are not implemented.

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 12]
```diff
@@ -247,20 +247,22 @@
...
-                                     :disabled
-                                     :else network-value-type)]
+                  (let [status           (cond (and (= network-value-type :not-available)
+                                                    loading-routes?
+                                                    token-not-supported-in-receiver-networks?)
+                                               :loading
+                                               (= network-value-type :not-available)
+                                               :disabled
+                                               :else network-value-type)
+                        amount-formatted (-> (rf/sub [:wallet/send-amount-fixed total-amount])
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/send/routes/view.cljs:257]: `rf/sub` like this feels odd. do we compute and `sub` like this at other places ?

afaik, `rf/sub` is similar to `useState` hook, so it should be called at the top level. Derivative values should be computed separately.

File: src/status_im/contexts/wallet/send/utils.cljs [hunk 13]
```diff
@@ -43,21 +41,67 @@
   [route]
   (money/wei->ether (reduce money/add (map calculate-gas-fee route))))
 
+(defn- path-amount-in
+  [path]
+  (-> path :amount-in money/from-hex))
+
+(defn- path-amount-out
+  [path]
+  (if (-> path :bridge-name (= constants/bridge-name-hop))
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/send/utils.cljs]: [Opinion]

Thread macro feels redundant:
`(= (:bridge-name path) constnats/bridge-name-hop)` is more clear.

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 12 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/send/routes/view.cljs:257]: `rf/sub` just derefs the atom returned by `rf/subscribe`, so there's no hooks anywhere. I've seen it used in a few places, but not sure if  `(-> ...)` results in a different scope when compiled to js.

```clj
(def sub (comp deref re-frame/subscribe))
```

**Review by shivekkhurana — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
Impressive job!

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 12 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/routes/view.cljs:257]: The subscribe returns a ratom, as long as it's used in a reactive context, everything should be fine 👍, no need to be tied to hook's limitations

As a good practice, is always easier if subscriptions are in a single area (e.g. a `let` in the top) than spread along a giant component (I'm not suggesting a code change here).

File: src/status_im/subs/wallet/wallet.cljs (hunk 10 above)
Comment (ulisesmac) [reply src/status_im/subs/wallet/wallet.cljs:158]: You are right.

This is because a `token` is a map with balances and `token-symbol` is just the symbol. In some flows we want to send a token but we don't know the account to pick it yet, so we start the flow and the account is picked later.

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/routes/view.cljs]: @clauxx unless it's worse in terms of code strucuture, I'd prefer that the subscription already returned the whole computed value, so that we avoid calculations on the view.

**Comment by ulisesmac** [comment]
@clauxx 

Added a reply to some comments, but everything still looks fine :+1:  Thanks for the PR!

**Comment by clauxx** [comment]
@pavloburykh ready to be QA'd again :+1:

**Comment by pavloburykh** [comment]
> @pavloburykh ready to be QA'd again 👍

Thank you for the fix @clauxx! The release 2.31 scope is already overloaded, and we don’t want to extend the testing time, so we've decided to move the PR to the next release 2.32. We will get back to testing this PR once we finish with release 2.31 testing.

**Comment by clauxx** [comment]
@pavloburykh yeah makes sense :+1:. LMK when you'll be able to pick it up afterwards

**Comment by pavloburykh** [comment]
@clauxx thanks for the PR! ISSUES 1 and 2 are fixed. Please take a look at the new issues:

### ISSUE 3 `cannot unmarshal hex string without 0x prefix...` in case of L1 - L2 (Arb) transaction

**Steps:** 

1. Initiate L1 - L2 (Arb) transaction
2. Confirm transaction
3. Observe the error

**Actual result:** `cannot unmarshal hex string without 0x prefix...` error

[Status-debug-logs - 2024-11-01T140435.945.zip](https://github.com/user-attachments/files/17599404/Status-debug-logs.-.2024-11-01T140435.945.zip)

photo_2024-11-01 14 04 51

https://github.com/user-attachments/assets/07d614cb-456b-4d02-99f1-ba6eac18da1a

**Comment by pavloburykh** [comment]
### ISSUE 4 Recepient gets = To value in case of L1 - L2 (opt) transaction

**Steps:** 

1. Build L1 - L2 (opt) routes
2. Compare Recepient gets and To values

**Expected result:** Recepient gets should be less than To value taking into consideration boundary fee

**Actual result:** Recepient gets = To value

photo_2024-11-01 14 12 26

**Comment by pavloburykh** [comment]
### ISSUE 5 Sometimes Recepient gets value is less than boundary fee

I have reproduced the issue when building L2 - L1 route. It is not reproducible every time. 

**Steps:** 

1. Build L2 - L1 route using small amount of tokens (i.e 0.0001 eth)
2. See if `Bounder fee cannot exceed amount` error appears

**Actual result:** sometimes `Bounder fee cannot exceed amount` error does not appear. Routes are successfully build. Recepient gets value is less than amount of fees which user will pay. 

photo_2024-11-01 14 17 06


**Expected result:** in case if bounder fee exceeds transaction amount user usually get `Bounder fee cannot exceed amount` error and is not able to proceed with transaction

photo_2024-11-01 14 21 29

**Comment by clauxx** [comment]
@pavloburykh everything is broken :boom:. I guess some recent changes :|, will have a look.

Regarding ISSUE 4, we are rounding the amount by taking into account the value of the token. I guess for bridge specifically we can skip that and show more decimals, WDYT?

**Comment by pavloburykh** [comment]
### ISSUE 6 `To` value on Details screen is less than `To` value on Networks screen in case of L2 (opt) - L2 (Arb) 

**Steps:** 

1. Build L2 (opt) - L2 (Arb) routes
2. Compare `To` value on Networks and Details screens

**Actual result:** `To` value on Details screen is less than `To` value on Networks screen


https://github.com/user-attachments/assets/c0191a54-73cd-4bc1-b337-ec8fa9689f8a

**Comment by pavloburykh** [comment]
> Regarding ISSUE 4, we are rounding the amount by taking into account the value of the token. I guess for bridge specifically we can skip that and show more decimals, WDYT?

@clauxx I am not sure if there is a problem in roundings in this particular case. As you can see on screenshot below, in case of L1 - L2 (Arb) transaction, with the same amount of 0.001 eth, Recepient gets value looks correct (0.0001 - fee = 0.00088). 

photo_2024-11-01 14 45 11


But in case of L1 - L2 (opt) as described in the [ISSUE 4](https://github.com/status-im/status-mobile/pull/21116#issuecomment-2451788140) 0.001 eth value remains the same. I have an assumption that Recepient gets value in this case does not take into consideration boundary fee for some reason.

**Comment by clauxx** [comment]
> I am not sure if there is a problem in roundings in this particular case. As you can see on screenshot below, in case of L1 - L2 (Arb) transaction, with the same amount of 0.001 eth, Recepient gets value looks correct (0.0001 - fee = 0.00088).

image

On hop's exchange you can see that the bonder fee is very small when bridging to Optimism, so the received value (0.0009999) gets rounded up. I agree though that we should show the value closer to what it is, so will look into the rounding issue.

**Comment by pavloburykh** [comment]
> On hop's exchange you can see that the bonder fee is very small

oh, indeed. Sorry, I should have checked the actual fee on hopper's side first. I was sure that it is higher than it turned out to be.

**Comment by clauxx** [comment]
@pavloburykh on issue 5, where sometimes the received amount is less than the bonder fees, it seems to be the expected behavior, since the comparison is not with the estimated received, but with the amount sent ("From"). Should it be otherwise, as in compare the bonder fee amount with the estimated received? If yes, we'll have to handle it on the client side, as there will be no error toast coming from the router/provider.

**Comment by pavloburykh** [comment]
> @pavloburykh on issue 5, where sometimes the received amount is less than the bonder fees, it seems to be the expected behavior, since the comparison is not with the estimated received, but with the amount sent ("From"). Should it be otherwise, as in compare the bonder fee amount with the estimated received? If yes, we'll have to handle it on the client side, as there will be no error toast coming from the router/provider.

Thanks for the explanation @clauxx in case the comparison is with the amount sent ("From") then I guess the behaviour is expected.

**Comment by clauxx** [comment]
@pavloburykh Issue 6 and 3 should be fixed now. The formatting of the bridge values so they're not rounded (as they are now) might take some refactoring (which i started, but it was getting out of hand already), so might be better to get it in a separate PR, WDYT?

**Comment by pavloburykh** [comment]
@clauxx thanks a lot for your work on this PR. Issues 3 and 6 are fixed. 

> The formatting of the bridge values so they're not rounded (as they are now) might take some refactoring (which i started, but it was getting out of hand already), so might be better to get it in a separate PR, WDYT?

Sure, I have logged a separate followup issue and assigned you to it https://github.com/status-im/status-mobile/issues/21580

PR is ready for merge now.

**Comment by churik** [comment]
@clauxx can we merge this one?

**Comment by clauxx** [comment]
> @clauxx can we merge this one?

Yes, if the ios build passes then can be merged
