### PR TITLE
fix: handle unknown contract community

### LINKED ISSUE #20092: "Discover communities" is not loading or loading exteremely slowly
# Bug Report

## Problem 
The issue is not reproducible on status-desktop, so need investigation how it is loaded on desktop side; 
it is reproducible on latest ststus-go version (in https://github.com/status-im/status-mobile/pull/20060)

If it gets loaded once, it stays in the curated communities directory.

#### Expected behavior
can see communities

#### Actual behavior
image

### Reproduction

1. Create new account
2. Open Discover communities

### Additional Information

- Status version: nightly 17/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
Logs: [logs (83).zip](https://github.com/status-im/status-mobile/files/15348882/logs.83.zip)
```
ERROR[05-16|15:00:21.027|github.com/status-im/status-go/protocol/messenger_curated_communities.go:49]                                       failed to get curated communities from contract error="fallback failed with 'Post \"https://optimism-goerli.infura.io/v3/40ec14d9d9384d52b7fbcfecdde4e2c0\": dial tcp: lookup optimism-goerli.infura.io: no such host'. run error was 'Post \"https://optimism-goerli.infura.io/v3/40ec14d9d9384d52b7fbcfecdde4e2c0\": dial tcp: lookup optimism-goerli.infura.io: no such host'"
```

### PR DESCRIPTION
**Pull request by yqrashawn**
-------

fixes #20092

### Summary

status-go give mobile this discover community list looks like this
```clj
    {:communities                 {"a" {:id "a"}}
     :contractFeaturedCommunities ["a" "b"]
     :contractCommunities         ["a" "b" "c"]
     :unknownCommunities          ["b" "c"]}
```

we save it into db like this, discover community view will stay loading forever since there's only one community in the list and it's unknown
```clj
    {:featured         {"a" {:id "a"}} ;; cause there's no known data about "b" and "c"
     :other            {}}
```

this PR save the unknown communities into db and update them into `featured` or `other` once their `"community.found"` signal received
```clj
    {:featured         {"a" {:id "a"}}
     :other            {}
     :unknown-featured '("b")
     :unknown-other    '("c")}
```

### Testing notes
- won't work in testnet mode testnet RPC is broken
- I got `endpoint xxxxxx has passed its daily relay limit` on mainnet (in geth.log), this prevents status-go fetching the list as well, which leads to infinite loading
  - I fixed this by changing the `POKT_TOKEN` to a newly created one, not sure if PR/nightly build uses different token

#### Platforms
- iOS
- macOS

#### Areas that maybe impacted
discover community

### Steps to test
- create a new account, make sure testnet mode is off
- open the discover community view

status: ready

### CODE REVIEW

**Comment by yqrashawn** [comment]
https://github.com/status-im/status-mobile/assets/15090582/315be2dc-15eb-4517-9987-bbe70f393c09

File: src/status_im/common/signals/events.cljs [hunk 1]
```diff
@@ -84,7 +83,9 @@
       (local-notifications/process cofx (transforms/js->clj event-js))
 
       "community.found"
-      (link-preview/cache-community-preview-data (transforms/js->clj event-js))
+      (let [community (transforms/js->clj event-js)]
+        {:fx [[:dispatch [:chat.ui/cache-link-preview-data-by-community community]]
```
Comment (flexsurfer) [inline src/status_im/common/signals/events.cljs]: why do we use dispatch here?

File: src/status_im/contexts/chat/messenger/messages/link_preview/events.cljs [hunk 2]
```diff
@@ -19,6 +19,10 @@
                                                                          data)))]
      {:db (assoc-in db [:profile/profile :link-previews-cache] link-previews-cache)})))
 
+(rf/reg-event-fx :chat.ui/cache-link-preview-data-by-community
+ (fn [_ [community]]
+   {:fx [[:dispatch [:chat.ui/cache-link-preview-data (community-link (:id community)) community]]]}))
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/messenger/messages/link_preview/events.cljs]: why double dispatch is needed?

File: src/status_im/common/signals/events.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/common/signals/events.cljs]: `cache-link-preview-data` fx should be used directly here

**Review by ilmotta — APPROVED** [review]
Thanks for the PR description and adding tests @yqrashawn.

Except for the things @flexsurfer already commented, I'm approving in advance because the code LGTM.
I

**Comment by yqrashawn** [comment]
Thanks for the review, I've addressed your feedback. @flexsurfer

File: src/status_im/common/signals/events.cljs [hunk 3]
```diff
@@ -84,7 +84,9 @@
       (local-notifications/process cofx (transforms/js->clj event-js))
 
       "community.found"
-      (link-preview/cache-community-preview-data (transforms/js->clj event-js))
+      (let [community (transforms/js->clj event-js)]
+        (link-preview/cache-community-preview-data community)
+        (rf/dispatch [:discover-community/maybe-found-unknown-contract-community community]))
```
Comment (flexsurfer) [inline src/status_im/common/signals/events.cljs]: if we still want to use dispatch it should be :fx :dispatch

Comment (yqrashawn) [reply src/status_im/common/signals/events.cljs]: I've updated the code, do you mean like this?

File: src/status_im/common/signals/events.cljs [hunk 4]
```diff
@@ -84,7 +84,9 @@
       (local-notifications/process cofx (transforms/js->clj event-js))
 
       "community.found"
-      (link-preview/cache-community-preview-data (transforms/js->clj event-js))
+      (let [community (transforms/js->clj event-js)]
+        (link-preview/cache-community-preview-data community)
+        {:fx [[:dispatch [:discover-community/maybe-found-unknown-contract-community community]]]})
```
Comment (flexsurfer) [inline src/status_im/common/signals/events.cljs:89]: sorry for the confusion, here you have to dispatch `cache-community-preview-data`  as well as it was in the first iteration of your PR.

**Comment by pavloburykh** [comment]
@yqrashawn thanks for the PR! Failed e2e are not PR related. Ready for merge and cherrypick into release branch cc @jo-mut
