### PR TITLE
[FIX #4335] Make unread badge touchable (aka fat finger fix)

### LINKED ISSUE #4335: Touchable area is too small in chat toolbar with unread messages badge
The unread messages badge should be touchable so that the touchable area isn't reduced when there is unread messages and stays the same size as when there isn't unread messages.

### PR DESCRIPTION
**Pull request by yenda**
fix #4335 

Unread message badge is not touchable which reduces the surface area
that can be used to go back from a chat when user has unread messages

This gives user the impression that he needs to tap many times to go
back and that the UI lags because a smaller area is touchable when
users have unread messages

screenshot from 2018-05-17 01-15-21
screenshot from 2018-05-17 01-16-23

screenshot from 2018-05-17 01-42-40
screenshot from 2018-05-17 01-42-28

screenshot from 2018-05-17 01-18-51
screenshot from 2018-05-17 01-19-14

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/9B2oGP for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/9B2oGP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/yh4XdW for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/yh4XdW">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
@yenda why 3 commits here?

File: src/status_im/ui/components/toolbar/styles.cljs [hunk 1]
```diff
@@ -59,9 +59,10 @@
   {:width  24
    :height 24})
 
-(def nav-item-button
+(defnstyle nav-item-button [unread-messages?]
```
Comment (rasom) [inline src/status_im/ui/components/toolbar/styles.cljs]: can be just `defn` btw

**Review by rasom — CHANGES_REQUESTED** [review]
please rebase it onto develop

**Comment by yenda** [comment]
@rasom there was 3 commits because I was making a special build for Chad to test performance issues. I still need to fix dapps screen there is a misalignement now I will update this PR later

**Comment by yenda** [comment]
@jeluard I add you to the review because you are the last one who touched these components, I was wondering if you have an opinion on a better way to do this

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/WJ8RoW for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/WJ8RoW">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/FmV7R3 for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/FmV7R3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/ui/components/toolbar/styles.cljs [hunk 2]
```diff
@@ -88,6 +89,6 @@
 (def ios-content-item {:position :absolute :right 40 :left 40})
 
 (def counter-container
-  {:position :absolute
+  {:padding-horizontal 3
```
Comment (jeluard) [inline src/status_im/ui/components/toolbar/styles.cljs]: Please align values

**Review by jeluard — COMMENTED** [review]
Looks fine to me!
Just make sure you address both comments (Roman's and mine)

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/3ahmva for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/3ahmva">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/SeaZ9T for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/SeaZ9T">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by denis-sharypin — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/CiZyap for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/CiZyap">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/MH2Kz6 for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/MH2Kz6">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by yenda** [comment]
@rasom is it ok now ?
@denis-sharypin are the design ok ? I updated the screenshot, I realigned the dapp icon it was a bit off to the top even on current release

**Comment by denis-sharypin** [comment]
@yenda everything is okay! Thanks, Eric

**Review by jeluard — APPROVED** [review]

**Comment by jeluard** [comment]
@rasom Can you review again?

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/BWdNmX for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/BWdNmX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/Nmny2Y for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/Nmny2Y">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by rasom — APPROVED** [review]

**Comment by asemiankevich** [comment]
LGTM, however the improvement is hardly visible on iOS

**Comment by yenda** [comment]
@asemiankevich do you mean the tap area is still small or it was already including the unread messages badge ?

**Comment by asemiankevich** [comment]
@yenda well i think the problem here is that the badge is small itself)
