### PR TITLE
bug #4917 and #4914 - not showing message in chat after wallet send

### LINKED ISSUE #4914: Sent transaction from Wallet is shown in Console / Public chats
### Description

***Type***: Bug

***Summary***: Message about sent funds is shown in the chat that is placed as the very first element on Home screen. Means:
- if Transaction sender has public chat as the place where he sent the message prior to sent Transaction from wallet (so public chat at the top of list on Home screen) -> `/send` message transaction will be shown in this public chat
- if Transaction sender has Console as the place where he sent the message prior to sent Transaction from wallet (so Console at the top of list on Home screen)-> `/send` message transaction will be shown in Console

#### Expected behavior
Message with sent transaction is not shown in any chat. Recipient receives sent tokens.

#### Actual behavior
Transaction sent from Wallet that is reflected in public chat:

screen shot 2018-06-22 at 19 59 54

Message with sent transaction is shown in Status Console. Recipient doesn't receive tokens
image

### Reproduction #1 (when `/send` message shown in Console)
- Open Status
- Create an account
- Add a contact
- Navigate to profile and switch on development mode (under Advanced button)
- Switch network to Ropsten with upstream RPC
- After login request /faucet in Status Console (**Note**: at this stage Console is the very first element on Home screen)
- After receiving funds request STT in the Status Test DApp (Plus button -> Open DApp -> Status Test DApp -> Open -> Assets -> Request STT)
- Wait for STT to be received
- Proceed to wallet and set up it
- Open Manage assets, select Modest Test Token and click Done button
- Click Send transaction button
- Select asset -> Modest Test Token
- Input 1 in amount field - Isufficient funds error is shown
- Choose recipient -> Contacts -> select a contact
- Change asset to STT
- Input 1 in amount field againg as it was cleaned
- Sign transaction
- Navigate to the Home view and open Status Console

### Reproduction #2 (when `send` message for TX sent from wallet appears in Public chat)

1) Open Status on Device1 (iOS) and Device2 (Android)
2) Create Contact 1 (iOS) and Contact 2 (Android) and request ETH and tokens for them.
3) Both contacts edded each other in contacts (Contact1 sends contact request to Contact2)
4) Contact2 sends `/request ETH 0.0003` in 1-1 chat to Contact1
5) Contact1 taps the `/request` message and sends the requested amount to Contact1 (basically a usual reply to `/request ETH` message)
6) Contact1 and Contact2 joins the same unique public chat (e.g. `#everythingisok`) and exchange messages there
7) Now, Contact1 (iOS) navigates to Wallet -> Send Transaction screen.
8) Contact1 sends STT to Contact2 (tap 'Specify recipient -> Contacts -> shoose Contact2 -> Asset -> STT -> Specif amount = 33 -> Advanced -> finaly `Sign Tx`
9) Check on both devices whether `/send` message is present in public chat

### Additional Information
* Status version: 0.9.21 (6108), node a339d7e
* Operating System: iPhone 8+, iOS 11.3.1, iPhoneX(iOS 11.2.5), Android

TF session for Console case : https://app.testfairy.com/projects/4803590-status/builds/8503790/sessions/4394604944?source=latest-sessions

TF session for Contact1 above  from **Reproduction 2** from 1:13:10 here: https://app.testfairy.com/projects/4803590-status/builds/8504019/sessions/4394617675/?accessToken=fSARMCXpN2amHCvgr-R-J3vu0bE
TF session when Contact2 above from **Reproduction 2** (and Contact1 as well actually) sees transaction in public chat: from 59:50 
 https://app.testfairy.com/projects/4803622-status/builds/8504010/sessions/4394618703/?accessToken=S9L3d8I-bkz37QWkjC9OlsllVJU

### LINKED ISSUE #4917: Message with incorrect asset and amount in chat for transaction sent from wallet
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: Message with incorrect amount and asset is shown in one-to-one chat for both sender and recipient if transaction was sent from wallet and previous one was sent in one-to-one chat for transaction request. Message contains asset and amount as the previous transaction

#### Expected behavior
No message in one-to-one chat about a transaction which was sent from wallet

#### Actual behavior
Both sender and recipient gets message in one-to-one chat about the last transaction which was sent from wallet. Message contains 1 STT but 0.0003 ETH was sent

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on 2 devices and create 2 accounts
- Users A and B add each other as contacts
- User A requests 1 STT in one-to-one chat with user B
- User B sends 1 STT to request from one-to-one chat with user A
- User B navigates to wallet and sends 0.00003 ETH to user A (Send transaction -> Choose recipient from contacts -> Set amount to 0.00003 -> Sign transaction)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.21 (6108) node a339d7e
* Operating System: Android, iOS

TF sessions:
[sender](https://app.testfairy.com/projects/4803590-status/builds/8504019/sessions/4394622731?source=latest-sessions)
[recipient](https://app.testfairy.com/projects/4803622-status/builds/8504010/sessions/4394622559?source=latest-sessions)

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #4917 
fixes #4914 

### Summary:

A recent regression caused chat messages to be sent after Wallet Send. Those messages are currently supposed to only be generated after `/send` command, not directly from Wallet. Since this is not yet supported, what happened instead was that an old payment message would appear in the last chat the user interacted with.

This PR reintroduces the condition that app should only send payment messages if the transaction was initiated from chat.

### Steps to test:
see #4917 and #4914

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 1]
```diff
@@ -289,11 +289,17 @@
...
-        (if modal?
+        (cond
+          modal?
           (cond-> {:dispatch [:navigate-back]}
             (= method constants/web3-send-transaction)
             (assoc :dispatch-later [{:ms 400 :dispatch [:navigate-to-modal :wallet-transaction-sent-modal]}]))
-          {:dispatch [:execute-stored-command]}))))))
+
+          from-chat?
+          {:dispatch [:execute-stored-command]}
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/events.cljs:299]: How about some comment to clarify the flow?

**Review by jeluard — APPROVED** [review]
