### PR TITLE
Bug/The second request becomes inactive if tap on the third one (#1394)

### LINKED ISSUE #1394: The second request becomes inactive if tap on the third one when receiving 3 requests in a row  [Send]
### Description

*Type*: Bug

*Summary*: If the user sends several request one-by-one in 1-1 chat. The reciever answers on them in the order: the first one, the third one. The second one gets unavalable. The third one can be answered twice.

#### Expected behavior
All requests can be accepted and answered once.

#### Actual behavior
If the user answers the requests in the next order: the first one, the third one (1. 0.0041; 3. 0.043). The second request gets inactive (2. 0.042). The third one is active twice (3. 0.043).  
This bug was reproduced on Android emulator (Android  6.0).  The request was sent from the device  with Android 5.0.
The bug is reproducible if the user answers the request not more than in a few minutes after requesting.  

### Reproduction
1. Launch Status app on the Android device (Sender of the requests)
2. Login with valid credentials
3. Go to 1-1- chat
4. Request 3 amounts in the following order: 1. 0.0041; 2. 0.042;  3. 0.043
5. Launch Status app on the Android emulator (Reciever of the request). 
6. Login with valid credentials
7. Go to 1-1- chat
8. Answer the requests in order 1. 0.0041; 3. 0.043

Video: https://drive.google.com/file/d/0B0pYIvdvIoAHemhPLTZyQUI3bVU/view

### Additional Information

* Status version: 0.9.8-56-gd743691+
* Operating System: Android 6.0

### PR DESCRIPTION
**Pull request by flexsurfer**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #1394

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

File: src/status_im/chat/models/input.cljs [hunk 1]
```diff
@@ -88,13 +88,13 @@
...
                       (first))]
-         {:command  command
-          :metadata (if (not= :any to-message-id)
-                      (assoc input-metadata :to-message-id to-message-id)
-                      input-metadata)
-          :args     (if (empty? seq-arguments)
-                      (rest command-args)
-                      seq-arguments)}))))
+           {:command  command
+            :metadata (if (and (nil? (:to-message-id input-metadata)) (not= :any to-message-id))
```
Comment (flexsurfer) [inline src/status_im/chat/models/input.cljs]: gave priority to (:to-message-id input-metadata)

File: src/status_im/chat/views/message/request_message.cljs [hunk 2]
```diff
@@ -83,11 +80,14 @@
             command  (if (and params command)
                        (merge command {:prefill        prefill
                                        :prefill-bot-db (or prefill-bot-db prefillBotDb)})
-                       command)]
+                       command)
+            on-press-handler  (if (:execute-immediately? command)
+                                #(dispatch [:execute-command-immediately command])
+                                (when (and (not @answered?) status-initialized?)
```
Comment (rasom) [inline src/status_im/chat/views/message/request_message.cljs]: `status-initialized?` should be dereferenced here.

Comment (flexsurfer) [inline src/status_im/chat/views/message/request_message.cljs]: yes, thank you
