### PR TITLE
Community display picture & cover image style fixes

### LINKED ISSUE #14974: Community rendering problems
The top of the white area should be rounded, and the community icon should be a perfect circle, not an oval.

Version: Latest nightly
Device: OnePlus Nord N20 5G China Edition

Screenshot_2023-02-02-12-26-40-32_65ad86f86fd2321a85272a99323da10f

### PR DESCRIPTION
**Pull request by ajayesivan**
Fixes #14974 

### Summary
- Community display image rendered as oval instead of circle shape - fixed by increasing the border-radius.
- Community background top round issue on Android - Android doesn't support `overflow: visible` on scroll view children's. Fixed by using `margin-bottom` instead of the `overflow` property.

#### Before(issue)
Before

#### After(fix)
After

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
- Community overview pages

### Steps to test
- Open a community overview page and check the display picture and cover image.

status: ready

### CODE REVIEW

File: src/status_im2/common/scroll_page/view.cljs [hunk 1]
```diff
@@ -146,7 +146,7 @@
           [rn/view {:style {:height 151}}
            [rn/image
             {:source cover-image
-             :style  {:overflow :visible
+             :style  {:margin-bottom -16
```
Comment (flexsurfer) [inline src/status_im2/common/scroll_page/view.cljs:152]: margin-bottom can't be negative, it doesn't look right

Comment (ajayesivan) [reply src/status_im2/common/scroll_page/view.cljs:152]: In `scroll-view` child elements, the `overflow: visible` property will not work as expected on Android. However, using negative values for the margin property can provide a solution that works across both platforms, even though it is not ideal.

Comment (flexsurfer) [reply src/status_im2/common/scroll_page/view.cljs:152]: but it doesn't look like a proper solution, more like a hack, just wondering why its not possible to have proper solution

Comment (ajayesivan) [reply src/status_im2/common/scroll_page/view.cljs:152]: Our goal is to overlap the bottom white area over the cover image. To achieve this instead of using a negative value for the `margin-bottom` property on this element, alternative solutions could be to utilize a negative value for either the `margin-top` or `top` property of the white area.

File: src/status_im2/common/scroll_page/style.cljs [hunk 2]
```diff
@@ -58,7 +58,7 @@
   [animation]
   (reanimated/apply-animations-to-style
    {:transform [{:scale animation}]}
-   {:border-radius    40
+   {:border-radius    50
```
Comment (ilmotta) [inline src/status_im2/common/scroll_page/style.cljs:61]: It's nice that you found a fix, but I must say I don't understand why the shape was oval if `40` is half of the width and height of the display picture `80`. Something should be going on, because we have lots of places in the code where the formula `border-radius = square-side/2` gives a perfect circle.

File: src/status_im2/common/scroll_page/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/common/scroll_page/view.cljs:152]: @flexsurfer, I had the same problem recently and had to resort to the same workaround @ajayesivan did. I don't think there's another way, I've tried all sorts of things, but in the end, in our current RN version this is a known bug. https://github.com/facebook/react-native/issues/31218

@ajayesivan, have you tried passing the prop [removeClippedSubviews](https://reactnative.dev/docs/flatlist#removeclippedsubviews)? There's a big warning in the documentation, so even if that works we should carefully double-check for side-effects on different Android models.

File: src/status_im2/common/scroll_page/style.cljs (hunk 2 above)
Comment (ajayesivan) [reply src/status_im2/common/scroll_page/style.cljs:61]: Here, the element's width is not just 80, it's 80 + 4 (with 2 pixels of padding on each side). As a result, a border radius of 40 won't result in a perfect circle. A border radius of 44 would have been sufficient, but to account for slight variations in rendering on different platforms, such as iOS, a border radius of 50 was used for safety.

File: src/status_im2/common/scroll_page/view.cljs (hunk 1 above)
Comment (ajayesivan) [reply src/status_im2/common/scroll_page/view.cljs:152]: I tried `removeClippedSubviews`, but it didn't produce the desired result.

File: src/status_im2/common/scroll_page/style.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im2/common/scroll_page/style.cljs:61]: Oh that's true, thanks for the explanation @ajayesivan.

**Review by ilmotta — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
looks like we need the negative margin-bottom for the moment. @ilmotta, @flexsurfer maybe we can track to update these once we have migrated to a newer version of RN. WDYT?

**Comment by ilmotta** [comment]
> looks like we need the negative margin-bottom for the moment. @ilmotta, @flexsurfer maybe we can track to update these once we have migrated to a newer version of RN. WDYT?

Good idea. In the workaround I did back then I added an explanation as a comment https://github.com/status-im/status-mobile/blob/develop/src/quo2/components/tabs/tabs.cljs#L158

**Comment by ajayesivan** [comment]
> looks like we need the negative margin-bottom for the moment. @ilmotta, @flexsurfer maybe we can track to update these once we have migrated to a newer version of RN. WDYT?

I can add a comment like @ilmotta did. Should I also create a new issue to track this?

**Comment by ajayesivan** [comment]
I have added an explanation for the workaround in the comments.

**Comment by ilmotta** [comment]
> I have added an explanation for the workaround in the comments.

Thanks @ajayesivan.

>I can add a comment like @ilmotta did. Should I also create a new issue to track this?

I think it's fine without a new issue. This is not the first, nor the last workaround due to some weirdness in RN or the myriad of its dependencies. Unless it's something more critical, I think the code comment gives enough context for future collaborators.

**Comment by ajayesivan** [comment]
@flexsurfer Would it be possible to merge this PR, or is there anything blocking?

**Comment by flexsurfer** [comment]
@ajayesivan we're waiting for manual testing from QA, unfortunately, they are busy with the release currently :(

**Comment by ajayesivan** [comment]
> @ajayesivan we're waiting for manual testing from QA, unfortunately, they are busy with the release currently :(

Understood, thanks for the update.

**Comment by VolodLytvynenko** [comment]
hi @ajayesivan Could you please rebase the PR?

**Comment by ajayesivan** [comment]
@VladimrLitvinenko Rebased 👍

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko Rebased 👍

@ajayesivan Some integration tests failed https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Ftests/detail/PR-15047/6/pipeline . Could you fix it, please?

**Comment by ajayesivan** [comment]
> > @VladimrLitvinenko Rebased 👍
> 
> @ajayesivan Some integration tests failed https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Ftests/detail/PR-15047/6/pipeline . Could you fix it, please?

I don't have access to this. Let me run it locally and see what's happening.

**Comment by ajayesivan** [comment]
@VladimrLitvinenko

No testing failed when I ran `make test` locally. Not sure what's going on here.

Screenshot 2023-02-20 at 21 33 15

Can I get access to Jenkins?

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko
> 
> No testing failed when I ran `make test` locally. Not sure what's going on here.
> 
> Screenshot 2023-02-20 at 21 33 15
> 
> Can I get access to Jenkins?

@ajayesivan My apologies. I gave you the wrong link. Check this https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-15047/6/consoleText

**Comment by Parveshdhull** [comment]
Linting is failed, you can check errors using `make lint` and fix manually or using `make lint-fix`

**Comment by Parveshdhull** [comment]
> @ajayesivan My apologies. I gave you the wrong link. Check this https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-15047/6/consoleText

Only status members have access to jenkins pipeline

**Comment by ajayesivan** [comment]
> Linting is failed, you can check errors using `make lint` and fix manually or using `make lint-fix`

I have fixed the formatting.

**Comment by ajayesivan** [comment]
@Parveshdhull It seems like tests are still failing, could you please check and share what's happening?

**Comment by Parveshdhull** [comment]
> @Parveshdhull It seems like tests are still failing, could you please check and share what's happening?

Tests are fine, its the ios build that failed. (Fail not related to PR)
@jakubgs Please can you take a look why ios build is failing. Tried replaying no luck

**Comment by jakubgs** [comment]
Looks like the issue is specific to [macm1-01-ms](https://ci.status.im/manage/computer/macm1-01-ms/) which is our only remaining M1 host from MacStadium, which I intend to replace with a Hetzner host, but they have non available at this time. No idea what is wrong with it but it seems to be failing in a way that leaves nothing useful in terms of logs.

I'm just going to adjust labels so mobile builds don't run on `macm1-01-ms` for now.

**Comment by Parveshdhull** [comment]
> I'm just going to adjust labels so mobile builds don't run on macm1-01-ms for now.

thank you

**Comment by VolodLytvynenko** [comment]
@ajayesivan thank you for your work. No issues from my side. Could you merge it to develop, please?

**Comment by ajayesivan** [comment]
> @ajayesivan thank you for your work. No issues from my side. Could you merge it to develop, please?

I don't have permission to merge. @flexsurfer / @ilmotta Could someone please merge this PR?
