### PR TITLE
 fix community overview screen bannner height

### LINKED ISSUE #15097: Community overview banner height
## Problem 
The community overview screen has the height of the community banner cut out by the page navigation of the same screen.

#### Expected behavior
The community overview banner height should cover the overview screen as shown in the figma designs
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=8092%3A553565&t=C4ELHOSDA3lCRbYd-1

#### Actual behavior

Screenshot 2023-02-15 at 23 14 08

### PR DESCRIPTION
**Pull request by jo-mut**
fixes #15097

### Summary
This PR corrects the height of community banner in the overview screen

Screenshot 2023-02-22 at 14 21 39

### CODE REVIEW

File: src/quo2/components/navigation/page_nav.cljs [hunk 1]
```diff
@@ -5,7 +5,8 @@
             [quo2.components.icon :as icons]
             [quo2.components.markdown.text :as text]
             [quo2.foundations.colors :as colors]
-            [react-native.core :as rn]))
+            [react-native.core :as rn]
+            [status-im.utils.platform :as platform]))
```
Comment (J-Son89) [inline src/quo2/components/navigation/page_nav.cljs]: please don't use code from status_im in quo2 , this functionality should already be somewhere better in the codebase -> I believe it was migrated to react-native.platform.

Also, we should not be using code from status_im or status_im2 in quo2. As we are treating quo2 as a standalone component library. So if code is needed in both status_im2 and quo2 it should be moved higher up the codebase somewhere into src/utils etc

Comment (jo-mut) [reply src/quo2/components/navigation/page_nav.cljs]: this is actually i mistake I will correct that

File: src/status_im2/common/scroll_page/view.cljs [hunk 2]
```diff
@@ -36,7 +36,7 @@
    top-nav
    title-colum
    navigate-back?]
-  (let [input-range         (if platform/ios? [-47 10] [0 92])
+  (let [input-range         (if platform/ios? [-47 10] [0 10])
```
Comment (J-Son89) [inline src/status_im2/common/scroll_page/view.cljs:39]: changes to this component also affect the chat messages pages too, right? Can you also verify that all pages using this component are not affected by this adjustment.

File: src/status_im2/contexts/communities/overview/style.cljs [hunk 3]
```diff
@@ -1,20 +1,18 @@
...
    :margin-top     20})
 
 (def blur-channel-header
-  {:position         :absolute
-   :top              (if platform/ios? 56 60)
-   :height           34
-   :right            0
-   :left             0
-   :flex             1
-   :background-color :transparent})
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/overview/style.cljs:17]: curious, why did you remove transparent?

**Review by J-Son89 — APPROVED** [review]
looks much better, nice one @jo-mut  👍

File: src/status_im2/common/scroll_page/view.cljs (hunk 2 above)
Comment (jo-mut) [reply src/status_im2/common/scroll_page/view.cljs:39]: this component is not currently being used in messages only discover community and  community home screen. The animation looks much better across all screens al though they may need some improvement especially when messages implements this functionality

**Review by vkjr — APPROVED** [review]

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 4]
```diff
@@ -195,7 +195,9 @@
    featured-communities
    view-type]
   (fn []
-    [rn/view {:padding-horizontal 20}
+    [rn/view
+     {:padding-horizontal 20
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/view.cljs]: Quick reminder: put the styles inside a `:style` map instead of mixing them with the rest of the component props. I added a note to update the guidelines with this convention.

**Review by ilmotta — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @jo-mut let me know when PR is ready for tests! Thanx

**Comment by jo-mut** [comment]
@VladimrLitvinenko yes you can proceed with this one. its ready

**Comment by VolodLytvynenko** [comment]
hi @jo-mut. Thanx for your work. PR is tested. No issues from my side. Could you merge it, please?
