### PR TITLE
fix: entering two zeros in a row in the 'Amount' field in wallet

### LINKED ISSUE #19908: Error when entering two zeros in a row in the 'Amount' field in wallet
# Bug Report

### Reproduction

1. Open wallet
2. Go to the `Send` flow
3. Select a recipient and an asset
4. In the amount field enter 0 two times

#### Expected behavior

The field displays just one "0"

#### Actual behavior

Screenshot 2024-05-06 at 13 14 05

https://github.com/status-im/status-mobile/assets/67952253/5aaec290-98b3-4d6b-b0db-ae2ba0193dcf

### Additional Information

- Status version: nightly 6/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19908

This PR fixes an issue that caused a crash when typing zeroes in the input amout on the send screen.

Skipping QA as it is a simple fix.

Demo:

https://github.com/status-im/status-mobile/assets/29354102/1784ad30-ff6c-4b47-9429-b2d7a4f8dfee

### CODE REVIEW

**Comment by OmarBasem** [comment]
Simple fix, I think can skip QA

cc @J-Son89

File: src/status_im/common/controlled_input/utils.cljs [hunk 1]
```diff
@@ -78,9 +78,10 @@
 
 (defn add-character
   [state character]
-  (when (can-add-character? state character)
+  (if (can-add-character? state character)
```
Comment (J-Son89) [inline src/status_im/common/controlled_input/utils.cljs:81]: is this all to handle the custom keyboard?
We should really raise this with the design team as something to reconsider as it seems to be a bug factory that we could easily avoid :)

Comment (J-Son89) [reply src/status_im/common/controlled_input/utils.cljs:81]: also this looks good but since this is in /common/ I wonder is this code used elsewhere and if so is this the expected behaviour for these uses?

Comment (OmarBasem) [reply src/status_im/common/controlled_input/utils.cljs:81]: > is this all to handle the custom keyboard?

@J-Son89 Yes 🤷‍♂️ 

> We should really raise this with the design team as something to reconsider as it seems to be a bug factory

Agreed! I think @vkjr worked on this, maybe he can share his thoughts also (and maybe @ulisesmac)

> also this looks good but since this is in /common/

It is used in the send screen only. 
The fix here is to return the same state if the character cannot be added. Previously was returning `nil` hence the crash.

Comment (J-Son89) [reply src/status_im/common/controlled_input/utils.cljs:81]: yeah let's collate of all the lists and issues this brings in. I believe it's also a big takeaway from accessibility of the end user.  @shivekkhurana was discussing something like this before.

**Review by J-Son89 — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem  !

I am moving back your PR to the corresponding column as it doesn't meet the requirements outlined here:
https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md

Please, make sure your fix should/shouldn't be tested by QA's and add necessary information to PR's description.
Thanks! 🙏

**Comment by OmarBasem** [comment]
Thanks @mariia-skrypnyk, updated the description.

**Comment by mariia-skrypnyk** [comment]
> Thanks @mariia-skrypnyk, updated the description.

Thanks @OmarBasem for adding label and description! 🙌🤗

**Comment by mariia-skrypnyk** [comment]
Will review e2e and let you know! @OmarBasem

**Comment by OmarBasem** [comment]
Hey @mariia-skrypnyk, is this good to merge?

**Comment by mariia-skrypnyk** [comment]
Hey @OmarBasem !

Thanks for your patience! Just needed to manually check some moments.
Yes, please merge.
Good job! 👍

File: src/status_im/common/controlled_input/utils.cljs (hunk 1 above)
Comment (vkjr) [reply src/status_im/common/controlled_input/utils.cljs:81]: Hey!
I just found this discussion since was on vacation. 
Yes, if we continue to use custom keyboard, the controlled-input will be reused everywhere, this is the idea. But if in general we can reconsider using custom keyboard - I think it is even better)
