### PR TITLE
Fix failing ERC-1155 collectible transactions

### LINKED ISSUE #20973: ERC-1155 Collectible not sent successfully within etherscan on L1
### Steps:
1. Send an ERC-1155 Collectible using L1
2. Check the transaction status on Etherscan.

### Actual result:
- The collectible is not sent, even though the fee is estimated as 0.6 USD and the user has 17 USD available.
- The collectible shows an error within Etherscan. Example transaction https://etherscan.io/tx/0xadcc10dc9743c71ea564dc1567e9c644fd0e1f5079fe8a0f03484c5bb4b6243f
image

### Expected result:
Collectible is sent

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Release 2.30

### PR DESCRIPTION
**Pull request by clauxx**
fixes #20973 

### Summary

For some reason we were parsing the `token-id` into an int, which caused a significant loss of precision (see below) and we ended up with a different `token-id` altogether. As a result, the collectible was not found in the contract balance and the tx failed with  `ERC1155: insufficient balance for transfer` or `can't substract more than there is`. 

Most likely non-ERC1155 transactions were not failing due to smaller `token-id`s, which didn't lead to the loss of precision from `js/parseInt`.

```cljs
(-> "49303604037254424499205758826317261461258103209481173801878855324184340332571"
    js/parseInt ;; => 4.9303604037254426E76
    utils.money/to-hex
    ;; Converting token-id back
    utils.money/bignumber
    utils.money/to-string)
;; => "49303604037254426018823311161424344263693657511051997943531504659167293997056"
```

#### Platforms

- Android
- iOS

##### Functional
- wallet / transactions

### Steps to test

- Open Status
- Go to collectibles
- Open an ERC-1155 collectible (e.g. any from [here](https://rarible.com/collection/0xb66a603f4cfe17e3d27b87a8bfcad319856518b8/items))
- Send collectible
- Check etherscan if tx succeeded

status: ready

### CODE REVIEW

**Review by vkjr — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/utils/hex.cljs [hunk 1]
```diff
@@ -25,3 +26,14 @@
   [:=>
    [:cat :string]
    :string])
+
+(defn number-to-hex
+  [value]
+  (->> value
```
Comment (ilmotta) [inline src/utils/hex.cljs:32]: Similar to `normalize-hex`, could be a good idea to make `number-to-hex` respect nil punning.

**Review by ilmotta — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
Good catch, thanks for the fix. LGTM!

**Comment by pavloburykh** [comment]
@clauxx thank you for the fix! This PR is ready for merge and cherry pick into release branch.
