### PR TITLE
Bug/wallet request screen ui issues 1855

### LINKED ISSUE #1855: Wallet Request screen UI issues [1526]
### Description

*Type*: Bug

*Summary*: issues found and to be fixed for https://github.com/status-im/status-react/issues/1526

#### Actual behavior

- [x]  CR code should not be scrollable and must be centered.
- [x]  Wallet amount is not shown
- [x]  Amount field doesn't highlight in focus
- [x]  Contacts screen looks wrong on Android (2.1 can't be fixed because https://github.com/facebook/react-native/issues/7474)
- [ ]  Amount rules (let's create separate issue for this because design is needed)

## 1. iOS/Android:

Currently max length of the amount: 15 characters including separator (./,). This is different from the amount user can type for /send command in chat. It should be consistent in both places and seems like Wallet is a place to adjust:
1.1 Expected: Amount before separator - seems like can be of any length or I can't find the limit
1.2 Expected: Amount after separator - should be not more than 18 digits after comma (e.g 0.123456789012345678). Currently, it's possible to enter only 13 digits after comma (e.g. 0.1234567890123)
1.3 "0" is now not allowed as a sum to send. In some cases, it's valid to send "0" (e.g https://contribute.status.im/sgt.html ), so it should be fine to request it too.

## 2. Android
2.1. Select contact screen, top part with phone icons (carrier, battery status, time) is on black background. Expected: white background, black text/icons
2.2 There is some empty space between "Contacts" heading
image

### Additional Information
* Status version: 0.9.10-98-g82f6a82b+
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #1855 #1829

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

File: env/dev/env/android/main.cljs [hunk 1]
```diff
@@ -15,7 +15,7 @@
   (re-frame.core/dispatch [:load-commands!]))
 
 (figwheel/watch-and-reload
-  :websocket-url "ws://localhost:3449/figwheel-ws"
```
Comment (jeluard) [inline env/dev/env/android/main.cljs]: Can you leave this change out?

File: src/status_im/android/platform.cljs [hunk 2]
```diff
@@ -20,6 +20,10 @@
                            :modal       {:height       0
                                          :bar-style    "light-content"
                                          :color        styles/color-black}
+                           ;;TODO because this bug in RN https://github.com/facebook/react-native/issues/7474
+                           :modal-white {:height       0
+                                         :bar-style    "light-content"
+                                         :color        styles/color-black}
```
Comment (jeluard) [inline src/status_im/android/platform.cljs:26]: Looks like color is wrong?

File: src/status_im/ui/screens/wallet/components/styles.cljs [hunk 3]
```diff
@@ -18,10 +18,12 @@
    :line-height    16
    :letter-spacing -0.2})
 
-(defstyle amount-container
+(defnstyle amount-container [active]
   {:margin-top       8
    :height           52
-   :background-color styles/color-white-transparent-3
+   :background-color (if active
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/components/styles.cljs]: Maybe rename to `active?`

File: src/status_im/ui/screens/wallet/request/views.cljs [hunk 4]
```diff
@@ -36,34 +36,36 @@
...
-   [react/view styles/separator]
-   [react/view styles/buttons-container
-    [vi/icon :icons/share {:color :white :container-style styles/share-icon-container}]
-    [react/text {:style      styles/button-text
-                 :font       (if platform/android? :medium :default)
-                 :uppercase? (get-in platform/platform-specific [:uppercase?])} (i18n/label :t/share)]
-    [react/view {:flex 1}]
-    [react/touchable-highlight {:on-press send-request}
-     [react/view styles/send-request-container
+  (views/letsubs [scroll (atom nil)]
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/request/views.cljs]: Can you add some comment detailing what this scroll logic is doing?

File: src/status_im/ui/screens/wallet/request/views.cljs [hunk 5]
```diff
@@ -36,34 +36,36 @@
...
+     [react/view styles/separator]
+     [react/view styles/buttons-container
+      [vi/icon :icons/share {:color :white :container-style styles/share-icon-container}]
       [react/text {:style      styles/button-text
                    :font       (if platform/android? :medium :default)
-                   :uppercase? (get-in platform/platform-specific [:uppercase?])} (i18n/label :t/send-request)]
-      [vi/icon :icons/forward {:color :white :container-style styles/forward-icon-container}]]]]])
\ No newline at end of file
+                   :uppercase? (get-in platform/platform-specific [:uppercase?])} (i18n/label :t/share)]
+      [react/view {:flex 1}]
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/request/views.cljs]: You can use `components.styles/flex`

File: src/status_im/ui/screens/wallet/request/views.cljs [hunk 6]
```diff
@@ -36,34 +36,36 @@
...
+      [react/touchable-highlight {:on-press send-request}
+       [react/view styles/send-request-container
+        [react/text {:style      styles/button-text
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/request/views.cljs]: This logic for text component is repeated several times in the codebase. It would make sense to create a small component for this.

**Review by jeluard — CHANGES_REQUESTED** [review]

File: env/dev/env/android/main.cljs (hunk 1 above)
Comment (flexsurfer) [reply env/dev/env/android/main.cljs]: yeah, usually i do

File: src/status_im/android/platform.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/android/platform.cljs:26]: why?

Comment (flexsurfer) [reply src/status_im/android/platform.cljs:26]: if you mean it should be white, but it doesn't work on Android, and black looks better than default gray

File: src/status_im/ui/screens/wallet/components/styles.cljs (hunk 3 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/components/styles.cljs]: sure

File: src/status_im/ui/screens/wallet/request/views.cljs (hunk 4 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/request/views.cljs]: sure

File: src/status_im/ui/screens/wallet/request/views.cljs (hunk 5 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/request/views.cljs]: sure

File: src/status_im/ui/screens/wallet/request/views.cljs (hunk 6 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/request/views.cljs]: sure

File: src/status_im/android/platform.cljs (hunk 2 above)
Comment (jeluard) [reply src/status_im/android/platform.cljs:26]: Hmm ok. BTW this issue is related https://github.com/status-im/status-react/issues/1829
Maybe you can fix it at the same time?

Comment (flexsurfer) [reply src/status_im/android/platform.cljs:26]: sure

**Comment by flexsurfer** [comment]
@jeluard thanks, done

**Review by jeluard — APPROVED** [review]
