### PR TITLE
[FIX #1731] Prepare configuration allowing to fail build

### LINKED ISSUE #1731: Make sure compilation warnings fail the build
Default ClojureScript compiler configuration does not let build fail when warnings are found.

This is not useful in our case are warnings are always errors.

See:

* http://jakemccrary.com/blog/2015/12/19/clojurescript-treat-warnings-as-errors/
* https://github.com/emezeske/lein-cljsbuild/blob/master/README.md#custom-warning-handlers

### PR DESCRIPTION
**Pull request by jeluard**
### Summary:

Improve `warnings` visibility (red color).
Prepare configuration for failing build on warnings. This is not enabled yet due to one of our dependency generating warnings.

### Steps to test:
- Execute production build
- See wrnings being printed in red

status: ready

### CODE REVIEW

File: src/status_im/utils/build.clj [hunk 1]
```diff
@@ -0,0 +1,10 @@
+(ns status-im.utils.build
+  (:require [cljs.analyzer :as ana]))
```
Comment (rasom) [inline src/status_im/utils/build.clj]: let's use `analyzer` instead of `ana` here

**Review by rasom — APPROVED** [review]

File: src/status_im/utils/build.clj (hunk 1 above)
Comment (jeluard) [reply src/status_im/utils/build.clj]: Done
