### PR TITLE
[Fix] Error on opening "How to scan" bottom sheet

### LINKED ISSUE #16032: `723 is not ISeqable` error popup is thrown when trying to open `How to scan` bottom sheet
# Bug Report

`723 is not ISequable` error popup is thrown when trying to open the `How to scan` bottom sheet

### Expected behaviour

The `How to pair` bottom sheet should open without any errors.

### Actual behaviour

The `723 is not ISequable` error is thrown when trying to open the `How to scan` bottom sheet.

### Reproduction

1) Open Status
2) Log in to your existing account
3) Navigate to `Profile > Syncing`.
4) Navigate to the `Setup Syncing` screen by tapping the `+` button on the top right.
5) Now, tap on the `How to scan` button

### Additional Information

- Status Version: nightly [26/05]
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #16032

### Summary

This PR fixes the `723 is not ISeqable` error popup that is thrown when trying to open the `How to scan` bottom sheet.

The issue is caused due to the `empty?` check on the photo in `context-tag`. The picture data is either a string (web URL, base64) or a number (local asset). It is never a sequence. So, replaced the `empty?` check with `nil?` as it's more appropriate. I have checked the context usage across the application, everything works fine.

#### Platforms

- Android
- iOS

### Steps to test

1) Open Status
2) Log in to your existing account
3) Navigate to `Profile > Syncing`.
4) Navigate to the `Setup Syncing` screen by tapping the `+` button on the top right.
5) Tap on the `How to scan` button

status: ready

### CODE REVIEW

File: src/status_im2/contexts/syncing/how_to_pair/view.cljs [hunk 1]
```diff
@@ -49,7 +49,8 @@
      (i18n/label (:label value))]))
 
 (defn render-item
-  [i item]
+  [i list-item]
+  ^{:key i}
```
Comment (smohamedjavid) [inline src/status_im2/contexts/syncing/how_to_pair/view.cljs:53]: Additionally, Added the key to the iterations as the metro bundler throws a lot of warnings.

File: src/status_im2/contexts/syncing/how_to_pair/view.cljs [hunk 2]
```diff
@@ -60,7 +61,11 @@
      {:size   :label
       :weight :medium
       :style  style/list-icon-text} i]]
-   (map #(render-element %) item)])
+   (map-indexed (fn [idx item]
+                  ^{:key idx}
+                  [:<>
+                   (render-element item)])
```
Comment (flexsurfer) [inline src/status_im2/contexts/syncing/how_to_pair/view.cljs]: it should be just 

^{:key idx}
[render-element item]

Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/how_to_pair/view.cljs]: Updated!

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the fix! Please, take a look at following issues

### ISSUE 1 "Failed to set 'journal_mode' pragma" when generating forgot password error on login screen
I am not reproducing the bug on latest nightly, so assume it is PR related. 

**Steps:** 

1. Open login screen
2. Try to login using wrong password
3. Observe the error

**Actual result:** 

"Failed to set 'journal_mode' pragma"  error

photo_2023-05-26 18 36 15

**Expected result:** "Wrong password" error is displayed

photo_2023-05-26 18 39 03

**Comment by pavloburykh** [comment]
### ISSUE 2 Light swipebar of "How to Pair" bottom sheet when light theme is enabled

**Actual result:** 

photo_2023-05-26 18 40 46

**Expected result:** swipebar should be dark regardless which theme is enabled

https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179333&t=vexuSRNlRBUL0zFD-0

Syncing for Mobile – Figma 2023-05-26 18-41-44

**Review by erikseppanen — APPROVED** [review]

**Comment by smohamedjavid** [comment]
@pavloburykh - Thanks a lot for testing the PR!

> ISSUE 1 "Failed to set 'journal_mode' pragma" when generating forgot password error on login screen

This issue is not related to this PR. I have checked the latest `develop` branch locally. I could able to reproduce it. I guess the nightly is not updated yet. Please check any other latest PR builds.

I guess it's good to have a separate issue where we can look at it.

> ISSUE 2 Light swipebar of "How to Pair" bottom sheet when light theme is enabled

The issue is fixed. Kindly retest.

Thanks again!

**Comment by pavloburykh** [comment]
> This issue is not related to this PR. I have checked the latest `develop` branch locally. I could able to reproduce it. I guess the nightly is not updated yet. Please check any other latest PR builds.

Thank you @smohamedjavid! Indeed, it is already in latest develop. I have logged a separate issue for that https://github.com/status-im/status-mobile/issues/16038


[ISSUE 2](https://github.com/status-im/status-mobile/pull/16033#issuecomment-1564584638) is fixed! PR is ready for merge. Thank you for your work.

**Comment by smohamedjavid** [comment]
> > This issue is not related to this PR. I have checked the latest `develop` branch locally. I could able to reproduce it. I guess the nightly is not updated yet. Please check any other latest PR builds.
> 
> Thank you @smohamedjavid! Indeed, it is already in latest develop. I have logged a separate issue for that #16038
> 
> [ISSUE 2](https://github.com/status-im/status-mobile/pull/16033#issuecomment-1564584638) is fixed! PR is ready for merge. Thank you for your work.

Thanks again for testing the PR!
