### PR TITLE
[#21354] Exception when navigating back from route generation

### LINKED ISSUE #21354: 'Undefined not a function' error is shown after quick back navigation
# Bug Report
follow up from https://github.com/status-im/status-mobile/pull/21306

**Steps:**

1. Go to the routes generation page
2. Build the route
3. Go to a transaction confirmation page
4. Go back to the wallet main page or confirm the transaction

#### Actual behavior

https://github.com/user-attachments/assets/5ede3057-7ebf-46c5-a028-626bf9a2a120

#### Expected behavior

No errors

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21354 

### Summary

This PR solves the exception when fastly navigating back once the routes arrive. 

The problem happened because the `conversion-rate` used to calculate the `fiat->crypto` value (calculated in the view ns :warning:), was `nil` when navigating back.

Video of the issue solved:

https://github.com/user-attachments/assets/28b2f853-8d03-4ebc-90f0-99b56ab26579

### Review notes

The component `status-im.contexts.wallet.send.input-amount.view/view` needs a refactor, there a lot of calculations made in the view and the `let` bindings to understand the logic of it is giant.

#### Platforms

- Android
- iOS

### Steps to test

Please follow the video in the issue description and check is no longer reproducible.

status: ready

### CODE REVIEW

**Comment by ulisesmac** [comment]
@mariia-skrypnyk  
The reproduction of the issue is a bit tricky, since you reported it, it'd be great if you test that it's been fixed

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 1]
```diff
@@ -158,16 +158,14 @@
         active-screen?                            (= view-id current-screen-id)
         bottom                                    (safe-area/get-bottom)
         [crypto-currency? set-crypto-currency]    (rn/use-state initial-crypto-currency?)
-        on-navigate-back                          on-navigate-back
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:161]: Redundant  binding

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 2]
```diff
@@ -158,16 +158,14 @@
...
                                                     (rf/dispatch [:wallet/set-token-amount-to-send
                                                                   {:amount   amount
                                                                    :stack-id current-screen-id}]))
         {fiat-currency :currency}                 (rf/sub [:profile/profile])
-        {token-symbol :symbol
+        {token-symbol   :symbol
          token-networks :networks
-         :as
-         token}                                   (rf/sub [:wallet/wallet-send-token])
+         :as            token}                    (rf/sub [:wallet/wallet-send-token])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:168]: Just a code style fix

File: src/status_im/contexts/wallet/send/send_amount/view.cljs [hunk 3]
```diff
@@ -10,8 +10,7 @@
   [input-amount/view
    {:current-screen-id      :screen/wallet.send-input-amount
     :button-one-label       (i18n/label :t/review-send)
-    :enabled-from-chain-ids (rf/sub
-                             [:wallet/wallet-send-enabled-from-chain-ids])
+    :enabled-from-chain-ids (rf/sub [:wallet/wallet-send-enabled-from-chain-ids])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/send_amount/view.cljs:13]: Again, just a code style fix

File: src/utils/money.cljs [hunk 4]
```diff
@@ -239,9 +239,12 @@
...
   [crypto fiat-price]
-  (when-let [^js bn (bignumber crypto)]
-    (-> (.times bn ^js (bignumber fiat-price))
-        (with-precision 2))))
+  (let [^js crypto-bn     (bignumber crypto)
+        ^js fiat-price-bn (bignumber fiat-price)]
+    (when (and crypto-bn fiat-price-bn)
+      (-> crypto-bn
+          (.times fiat-price-bn)
+          (with-precision 2)))))
```
Comment (ulisesmac) [inline src/utils/money.cljs:248]: Now the implementation checks that both numbers are bignumbers.

I considered to use `fnil` as:

```clojure
(fnil bignumber 0)
```

But I was afraid that it broke existing usages where we relied on:

```clojure
(bignumber nil) ;; => nil
```

**Review by briansztamfater — APPROVED** [review]
LGTM

**Review by shivekkhurana — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ulisesmac thank you for the PR. Ready for merge.
