### PR TITLE
fix: profile screen initial avatar alignment

### LINKED ISSUE #18383: Login/Profile Switch Screen Avatar Initial Alignment Issue
There is an alignment problem with avatars on the Login/Profile Switch screen. The initial is not centered.

### Steps to Reproduce:
- Open the app.
- Navigate to the Login/Profile Switch screen.
- Observe the avatar alignment issue.

### PR DESCRIPTION
**Pull request by yqrashawn**
fixes #18383

### Summary

`:uppercase-ratio` is missing for some reason
add schema for `utils.image-server/get-initials-avatar-uri` (only required params) based on status-go impl https://github.com/status-im/status-go/blob/a8357dceacd1b737952660272bf80251df19b8f8/server/handlers.go#L583-L602

#### Areas that maybe impacted
- login profile
- profile selection
when user avatar is initial avatar

status: ready

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]
LGTM! Nice Job @yqrashawn 🎉

File: src/utils/image_server.cljs [hunk 1]
```diff
@@ -182,6 +183,20 @@
...
+     [:port int?]
+     [:color string?]
+     [:background-color string?]
+     [:size number?]
+     [:ratio float?]
+     [:uppercase-ratio number?]
+     [:font-size number?]
+     [:font-file string?]]]
+   [:string]])
+
```
Comment (ajayesivan) [inline src/utils/image_server.cljs]: ❤️

**Review by ibrkhalil — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @yqrashawn Thank you for your work. No issues from my side. PR is ready to be merged

**Comment by VolodLytvynenko** [comment]
@yqrashawn Take a look please the failed integration tests https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18426/4/consoleText
