### PR TITLE
Chat fixes based on design feedback

### LINKED ISSUE #17532: Design review: chats / colors and spacings
Figma: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6142-39869&mode=design&t=F1FEhvRES6X5T8vX-0

1. Incorrect colors and spacings
Screenshot 2023-10-04 at 16 00 52
Screenshot 2023-10-04 at 16 01 07

---

2. Weird empty state 
3. Missing mute button
Screenshot 2023-10-04 at 16 01 43

---

4. Time, name and chatkey are not aligned as in designs
Screenshot 2023-10-04 at 16 02 54

### PR DESCRIPTION
**Pull request by clauxx**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #17532 

### Summary

Chat fixes:
1. Fixed the chat "avatar header" position to the top (see video)
2. Fixed system message avatar margin
3. Fixed spacing between "grouped" messages from the same contact (see video)
4. Show decorated message when long pressing a "grouped" message (see video)
5. Added chat muting button & functionality (see video)
6. Changed composed placeholder color
7. Adjusted the chat header animation based on the [reference from the design team](https://vimeo.com/803434748) (see video)
8. Assuring there's no "weird states" of the header when: chat opened; keyboard shown; incoming message; incoming message while keyboard shown;
9. Removed layout animation (the header was increasing in height when the avatar was shrinking) which makes the performance *a bit better* and is not triggering `on-content-change` unnecessarily.

NOTE: This doesn't fix all composer issues, but I tried to fix as much as possible. There may be edge-cases I didn't consider which might still put the header in a "weird state" (especially on Android), but I couldn't find them.

Another thing that wasn't fixed was using the customisation color of the contact as the chat color as it would require more work on status-go side and is outside the scope of the current issue. There is a separate issue that would deal with that [here](https://github.com/status-im/status-mobile/issues/18048).

https://github.com/status-im/status-mobile/assets/21865759/4fef6db9-ecb4-4e11-9d2c-0ff2a5f81389

https://github.com/status-im/status-mobile/assets/21865759/bf6aa1a5-d9eb-4def-b717-0ac38c13b04b

https://github.com/status-im/status-mobile/assets/21865759/09f42ff8-dcec-4508-90db-ef8b79e8994a

https://github.com/status-im/status-mobile/assets/21865759/942a03e2-b785-45b4-81c9-c909b11498be

https://github.com/status-im/status-mobile/assets/21865759/4a26ba54-125a-4461-a2dd-f12ef647310a

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 1]
```diff
@@ -308,123 +327,150 @@
...
+                 :messages-view-height        messages-view-height
+                 :big-name-visible?           big-name-visible?}]
+       :data messages
+       :render-data {:theme           theme
+                     :context         context
+                     :keyboard-shown? keyboard-shown?
+                     :insets          insets}
+       :render-fn render-fn
+       :on-viewable-items-changed on-viewable-items-changed
+       :on-content-size-change
```
Comment (clauxx) [inline src/status_im2/contexts/chat/messages/list/view.cljs:365]: It's a bit difficult to tell what changed in this diff due to the formatting changes, but most of it is in `:on-content-size-change` and the addition of `:content-container-style`

**Review by OmarBasem — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for your work @clauxx!

### ISSUE 1: Mute chat instead of Mute channel button in a community channel

Screenshot 2023-12-07 at 12 35 37

Figma

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=2991-135923&mode=design&t=BNOrJp1Ubuh61q6o-4

Screenshot 2023-12-07 at 12 36 19

There is no example in the designs yet of what the top of the channel should look like, so I’m adding this example. [Mario confirmed](https://discord.com/channels/624634427930312714/928625369542713396/1182282472227098685) that this is the expected button

**Comment by qoqobolo** [comment]
### ISSUE 2: Weird chat avatar header behavior on Pixel 7a when there is no/little message history

You probably were referring to this issue in the PR description:

>NOTE: This doesn't fix all composer issues, but I tried to fix as much as possible. There may be edge-cases I didn't consider which might still put the header in a "weird state" (especially on Android), but I couldn't find them.

So this issue is easily reproducible on Google Pixel 7a (which we consider as an Android device standard). 

**Steps:**
1. Add a contact
2. Open 1-1 chat

When I open the chat, the header and avatar are in state as if the chat was scrolled up a little. Sometimes a couple of expands of the composer fix this. In the chat with some history it works fine. 

See the video

https://github.com/status-im/status-mobile/assets/67952253/9286c7e9-05e1-4e3a-a746-2cd1b3fcf72b

Could you take a look at this as well? Or we can log this as a separate issue.

**Comment by Parveshdhull** [comment]
Hi @clauxx,
Thank you very much for your awesome work.
I just noticed the changes in the `messages.list.view` file you are making.

I am refactoring the whole chat screen in https://github.com/status-im/status-mobile/pull/18055, and changing the chat screen layout structure (positions of items, migration from reagent atoms etc.)

This means these fixes will not work anymore, once that PR is merged.

Sorry for the delayed review, but please can we hold this PR's development until PR merged?
cc: @qoqobolo

**Comment by clauxx** [comment]
> Hi @clauxx, Thank you very much for your awesome work. I just noticed the changes in the `messages.list.view` file you are making.
> 
> I am refactoring the whole chat screen in #18055, and changing the chat screen layout structure (positions of items, migration from reagent atoms etc.)
> 
> This means these fixes will not work anymore, once that PR is merged.
> 
> Sorry for the delayed review, but please can we hold this PR's development until PR merged? cc: @qoqobolo

I would rather hold on the refactor instead to get the design fixes out in the next release, but I guess @qoqobolo or @churik can help with this better.

**Comment by Parveshdhull** [comment]
> I would rather hold on the refactor instead to get the design fixes out in the next release, but I guess @qoqobolo or @churik can help with this better.

We can go ahead with this PR, but in this PR we are fixing the issue for old navigation screen which is not properly implemented and replaced in optimization PR. As soon as the that PR is merged, these fixes will be redundant.
So these fixes will only work for the time horizon in which optimization PR is not merged(as the release is quite far).
But it will create several conflicts in optimization PR and will duplicate QA testing time.
(I am ok with conflicts, if you want to go ahead, as this PR is also addressing few other issues apart from navigation)

**Comment by clauxx** [comment]
> > I would rather hold on the refactor instead to get the design fixes out in the next release, but I guess @qoqobolo or @churik can help with this better.
> 
> We can go ahead with this PR, but in this PR we are fixing the issue for old navigation screen which is not properly implemented and replaced in optimization PR. As soon as the that PR is merged, these fixes will be redundant. So those fixes will only work for the time horizon in which optimization PR is not merged(as the release is quite far). But it will create several conflicts in optimization PR and will duplicate QA team time. (I am ok with conflicts, if you want to go ahead, as this PR is also addressing few other issues apart from navigation)


Cheers. I agree with the navigation point, but would be happy to join your refactoring effort and help out. As I mentioned in your PR, I'd be open to have a crew that would focus on improving the quality of the code and UX of the chat if you plan to continue work on it.

**Comment by qoqobolo** [comment]
Hey guys @clauxx @Parveshdhull, thanks for your input!

It seems to me that the most right and logical option is to merge this PR with all the fixes _excluding_ the fixes for navigation. This PR includes many other important fixes for the chat view, and @clauxx you did a great job. 

But since the navigation is currently being refactored by @Parveshdhull and the PR is almost ready, it looks like there is no point in doing a double work for all of us.
@clauxx  would you be happy with reverting the navigation changes in this PR?

@Parveshdhull could you clarify please what you mean by this point:
> So those fixes will only work for the time horizon in which optimization PR is not merged(as the release is quite far).

I don’t quite understand, what does the release have to do with it?🤔

**Comment by Parveshdhull** [comment]
Hi, thank you very much for your input. This was related to above message.

> I would rather hold on the refactor instead to get the design fixes out in the next release

https://github.com/status-im/status-mobile/pull/18059#issuecomment-1849432567

**Comment by Parveshdhull** [comment]
> So those fixes will only work for the time horizon in which optimization PR is not merged(as the release is quite far).

oops, I meant these fixes. As Optimization PR will replace them, before release.

**Comment by clauxx** [comment]
> Hey guys @clauxx @Parveshdhull, thanks for your input!
> 
> It seems to me that the most right and logical option is to merge this PR with all the fixes _excluding_ the fixes for navigation. This PR includes many other important fixes for the chat view, and @clauxx you did a great job.
> 
> But since the navigation is currently being refactored by @Parveshdhull and the PR is almost ready, it looks like there is no point in doing a double work for all of us. @clauxx would you be happy with reverting the navigation changes in this PR?
> 
> @Parveshdhull could you clarify please what you mean by this point:
> 
> > So those fixes will only work for the time horizon in which optimization PR is not merged(as the release is quite far).
> 
> I don’t quite understand, what does the release have to do with it?🤔

Thanks! Not exactly sure which are the navigation changes here, but I assume it's the top header that appears/disappears when scrolling. If so, the only thing I changed here is the moment it starts animating, which is one line I think. I would keep it as a future reference to be able to compare the behaviour of the chat post-refactor, as the animation behaves as it does in the reference video from the design team I mentioned in the description.

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 2]
```diff
@@ -276,21 +293,23 @@
...
+  [{:keys [scroll-y-animated-value
+           content-size-animated-value
+           animate-topbar-opacity?
+           on-end-reached?
+           animate-topbar-name?]}]
+  (fn [new-scroll-y new-content-size]
+    (when (and @on-end-reached? (pos? new-scroll-y))
       (reset! on-end-reached? false))
-    (if (< topbar-visible-scroll-y-value scroll-distance)
+    (if (< topbar-visible-scroll-y-value new-scroll-y)
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/list/view.cljs:301]: Hi, for reference related changes (more details checkout changes in https://github.com/status-im/status-mobile/pull/18055)

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 3]
```diff
@@ -131,36 +132,38 @@
...
-                                                            header-extrapolation-option)
-        image-top-margin-animation  (reanimated/interpolate scroll-y
-                                                            scroll-animation-input-range
-                                                            [0 40]
-                                                            header-extrapolation-option)
-        image-side-margin-animation (reanimated/interpolate scroll-y
-                                                            scroll-animation-input-range
-                                                            [0 -20]
-                                                            header-extrapolation-option)]
+  (let [image-scale-animation  (reanimated/interpolate scroll-y
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/list/view.cljs:153]: here

**Comment by qoqobolo** [comment]
> Thanks! Not exactly sure which are the navigation changes here, but I assume it's the top header that appears/disappears when scrolling. If so, the only thing I changed here is the moment it starts animating, which is one line I think. I would keep it as a future reference to be able to compare the behaviour of the chat post-refactor, as the animation behaves as it does in the reference video from the design team I mentioned in the description.

Ah okay, thanks for the explanation, I thought there were a lot more changes regarding navigation👍
In this case, we still need to fix [ISSUE 1](https://github.com/status-im/status-mobile/pull/18059#issuecomment-1845189296) and [ISSUE 2](https://github.com/status-im/status-mobile/pull/18059#issuecomment-1845627154) can be ignored for now (@Parveshdhull maybe it's worth paying attention to this specific case in your PR). 

And I'll be able to re-check the whole PR one more time tomorrow (I'm on sick leave today).
After this, the PR will be sent for design review and merged (if there are no issues). 

After this, https://github.com/status-im/status-mobile/pull/18055 will be rebased and we will take it for testing.

@Parveshdhull @clauxx does it sound good to you?

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 4]
```diff
@@ -304,123 +323,150 @@
...
+       :keyboard-should-persist-taps :always
+       :on-scroll-begin-drag #(do
+                                (rf/dispatch [:chat.ui/set-input-focused false])
+                                (rn/dismiss-keyboard!))
+       :on-momentum-scroll-begin state/start-scrolling
+       :on-momentum-scroll-end state/stop-scrolling
+       :scroll-event-throttle 16
+       :on-scroll (fn [event]
+                    (let [content-size-y
+                          (- (oops/oget event "nativeEvent.contentSize.height")
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/list/view.cljs:435]: btw, please can you elaborate this change?
This was already a separate function, why we are moving it here? (this will unnecessary increase the size of flat list function. Which is already quite big and harder to maintain.

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 5]
```diff
@@ -304,123 +323,150 @@
...
         recording?                            (rf/sub [:chats/recording?])
-        all-loaded?                           (rf/sub [:chats/all-loaded? (:chat-id chat)])
         {:keys [show-floating-scroll-down-button?
+                messages-scroll-y-value-initialized?
                 messages-view-height
-                messages-view-header-height]} inner-state-atoms]
+                messages-view-header-height]} inner-state-atoms
+        scroll-handler                        (use-scroll-handler
+                                               {:animate-topbar-name? animate-topbar-name?
+                                                :animate-topbar-opacity? animate-topbar-opacity?
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/list/view.cljs:332]: these are removed

File: src/status_im2/contexts/chat/messages/list/view.cljs (hunk 4 above)
Comment (clauxx) [reply src/status_im2/contexts/chat/messages/list/view.cljs:435]: So there's the `scroll-y` animated value that is used for interpolating the header avatar and navigation animations. It is mainly set during `on-scroll`, but we need to control it from `on-content-size-change` as well because `on-scroll` is not called on the initial render of the screen, when messages are incoming and when the keyboard is shown. Since the logic for showing/hiding the navigation header was in that `on-scroll` fn, I had to abstract it into a separate function that is used by both `on-scroll` and `on-content-size-change` and what was added here is what is uncommon between the two. I could extract it into another function if that helps readability.

**Comment by pavloburykh** [comment]
> As soon as the that PR is merged, these fixes will be redundant.
So these fixes will only work for the time horizon in which optimization PR is not merged(as the release is quite far).
But it will create several conflicts in optimization PR and will duplicate QA testing time.

@clauxx @Parveshdhull maybe we can create a separate branch that will include commits from both of your PRs and check if the fixes from this PR will still work? Because if they will not work as was mentioned by @Parveshdhull then I am not sure if it makes sense to merge this PR first as we will need provide new fixes based on https://github.com/status-im/status-mobile/pull/18055 changes. Correct me if I am wrong guys.

**Comment by clauxx** [comment]
> > Thanks! Not exactly sure which are the navigation changes here, but I assume it's the top header that appears/disappears when scrolling. If so, the only thing I changed here is the moment it starts animating, which is one line I think. I would keep it as a future reference to be able to compare the behaviour of the chat post-refactor, as the animation behaves as it does in the reference video from the design team I mentioned in the description.
> 
> Ah okay, thanks for the explanation, I thought there were a lot more changes regarding navigation👍 In this case, we still need to fix [ISSUE 1](https://github.com/status-im/status-mobile/pull/18059#issuecomment-1845189296) and [ISSUE 2](https://github.com/status-im/status-mobile/pull/18059#issuecomment-1845627154) can be ignored for now (@Parveshdhull maybe it's worth paying attention to this specific case in your PR).
> 
> And I'll be able to re-check the whole PR one more time tomorrow (I'm on sick leave today). After this, the PR will be sent for design review and merged (if there are no issues).
> 
> After this, #18055 will be rebased and we will take it for testing.
> 
> @Parveshdhull @clauxx does it sound good to you?

Sounds good. Can't tackle ISSUE 2 yet anyways, cause I don't have the device to test it, but will order it soon.

**Comment by clauxx** [comment]
> > As soon as the that PR is merged, these fixes will be redundant.
> > So these fixes will only work for the time horizon in which optimization PR is not merged(as the release is quite far).
> > But it will create several conflicts in optimization PR and will duplicate QA testing time.
> 
> @clauxx @Parveshdhull maybe we can create a separate branch that will include commits from both of your PRs and check if the fixes from this PR will still work? Because if they will not work as was mentioned by @Parveshdhull then I am not sure if it makes sense to merge this PR first as we will need provide new fixes based on #18055 changes. Correct me if I am wrong guys.

@pavloburykh  I think it's fine. I'll help @Parveshdhull with fixing conflicts if needed and will check for regressions agains this PR's changes.

**Comment by clauxx** [comment]
@qoqobolo Fixed ISSUE 1, but since you're out sick today, maybe @pavloburykh can have a look instead.

**Comment by pavloburykh** [comment]
> @qoqobolo Fixed ISSUE 1, but since you're out sick today, maybe @pavloburykh can have a look instead.

@clauxx thank you! ISSUE 1 is fixed. I have checked the PR and consider it to be ready for design review as soon as e2e run will be finished. I will post the update here.

**Comment by pavloburykh** [comment]
@clauxx I see there is a conflict in src/status_im2/contexts/chat/messages/list/view.cljs Please let us know if something should be re-tested after resolving of the conflict.

**Comment by clauxx** [comment]
@pavloburykh done. Can you test if it all works on android as expected, as I don't have a device to test on atm and the emulator is acting weird.

**Comment by qoqobolo** [comment]
Thanks @clauxx, checked the latest build on iOS and Android devices, looks good to me.
@Francesca-G PR is ready for design review, thank you!

**Review by Francesca-G — COMMENTED** [review]
Here's the [design review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=8065%3A58901&mode=design&t=gv0MnVcExvcN5Emp-1) :)

Another thing I noticed, when opening the chat from the list we still have the name animation in the top nav, even though there's no need. If there's enough messages the name should just be visible in the top nav, without any animation

https://github.com/status-im/status-mobile/assets/122543089/30cb0457-5fcd-4fde-8b53-ff32d32ee4da

**Comment by clauxx** [comment]
@Francesca-G Thank you for the review. I will make a follow-up issue to tackle these to avoid further merge conflicts.
