### PR TITLE
Use blurred background for all type `shell?` bottom sheets

### LINKED ISSUE #17571: Incorrect drawer style - notification center options
The drawer style doesn't match the design.

Activity center -> open three dots menu

Design review comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:66732&mode=design#570505117).

Initially reported in Design feedback 1.24 - https://github.com/status-im/status-mobile/issues/16841 - issue 5

Maybe related to https://github.com/status-im/status-mobile/issues/15513, cc: @flexsurfer

### PR DESCRIPTION
**Pull request by ibrkhalil**
image

fixes #17571 

### Summary
Fixes the drawer style inside activity center
status: ready

### CODE REVIEW

File: src/status_im/common/bottom_sheet/view.cljs [hunk 1]
```diff
@@ -106,7 +106,11 @@
                     {:transform [{:translateY translate-y}]}
                     (style/sheet insets window-height selected-item))}
            (when shell?
-             [blur/ios-view {:style style/shell-bg}])
+             [blur/ios-view
+              {:style         style/shell-bg
+               :blur-radius   blur-radius
+               :blur-type     :transparent
+               :overlay-color :transparent}])
```
Comment (smohamedjavid) [inline src/status_im/common/bottom_sheet/view.cljs]: I'm afraid this would affect the sheets which use `shell?` (most sheets in onboarding do use the `shell` theme).

File: src/status_im/contexts/shell/activity_center/drawer/view.cljs [hunk 2]
```diff
@@ -20,4 +20,9 @@
                                       :text       (i18n/label :t/notifications-marked-as-read
                                                               {:count unread-count})
                                       :theme      :dark})])
-                     (rf/dispatch [:hide-bottom-sheet]))}]]]))
+                     (rf/dispatch [:hide-bottom-sheet]))}
+       {:icon     :i/settings
+        :label    (i18n/label :t/chat-notification-preferences)
+        :on-press (fn []
+                    (rf/dispatch [:navigate-to :notifications-settings])
+                    (rf/dispatch [:hide-bottom-sheet]))}]]]))
```
Comment (smohamedjavid) [inline src/status_im/contexts/shell/activity_center/drawer/view.cljs]: On the initial implementation, the `Notification settings` option is not added to the drawer (despite the Design showing the option) as the notification settings page is not designed/built yet.

The screen `notifications-settings` (which navigate to) is from legacy code. I'm not sure we need this option now.

File: src/status_im/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im/common/bottom_sheet/view.cljs]: I think I'll add a new prop for this blurring only.

File: src/status_im/contexts/shell/activity_center/drawer/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im/contexts/shell/activity_center/drawer/view.cljs]: Okay, Will remove it.

File: src/status_im/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im/common/bottom_sheet/view.cljs]: Done

File: src/status_im/contexts/shell/activity_center/drawer/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im/contexts/shell/activity_center/drawer/view.cljs]: Done

File: src/status_im/common/bottom_sheet/view.cljs [hunk 3]
```diff
@@ -106,7 +106,14 @@
                     {:transform [{:translateY translate-y}]}
                     (style/sheet insets window-height selected-item))}
            (when shell?
-             [blur/ios-view {:style style/shell-bg}])
+             [blur/ios-view
+              (cond-> {:style style/shell-bg}
+                blur-bg? (assoc :blur-radius
```
Comment (ilmotta) [inline src/status_im/common/bottom_sheet/view.cljs]: This `assoc` call is kind of unreadable with each argument on its own line instead of each key & value pair on each line.

File: src/status_im/common/bottom_sheet/view.cljs [hunk 4]
```diff
@@ -106,7 +106,14 @@
...
+                                blur-radius
+                                :blur-type
+                                :transparent
```
Comment (ilmotta) [inline src/status_im/common/bottom_sheet/view.cljs]: FYI: I can't verify the implications of forcing the blur type and overlay color as transparent because I don't have iOS.

Comment (ibrkhalil) [reply src/status_im/common/bottom_sheet/view.cljs]: Would it be okay if QA validate it, And also I am going to try to test all sheets.

File: src/status_im/common/bottom_sheet/view.cljs (hunk 3 above)
Comment (smohamedjavid) [reply src/status_im/common/bottom_sheet/view.cljs]: Maybe we can move the `assoc` next line.

File: src/status_im/common/bottom_sheet/view.cljs (hunk 4 above)
Comment (smohamedjavid) [reply src/status_im/common/bottom_sheet/view.cljs]: A quick design question: If the sheet with the type `shell?` requires a transparent background, does it apply to all sheets with this type? If yes, we can update the style of this style.

Comment (ibrkhalil) [reply src/status_im/common/bottom_sheet/view.cljs]: Got a response from design, Every shell? sheet should be blurred.

**Review by smohamedjavid — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by ibrkhalil** [comment]
@status-im/mobile-qa

**Comment by pavloburykh** [comment]
> @status-im/mobile-qa

Hey @ibrkhalil! Please move PR from REVIEW to E2E column once it has been reviewed and approved.

**Comment by qoqobolo** [comment]
Hey @ibrkhalil , thanks for the fix, looks great on iOS.
But I've got a question about Android.

This is how the AC bottom sheet looks on Android in this PR, the bottom sheet color is too dark:

image

However, afaik this is a known and common issue throughout the app (logged out state, user profile, etc): 

image
image

Do you happen to have any updates on whether we should focus on this now?
Cc'ing @Francesca-G as well, maybe you also can share your opinion on this from a design perspective?

**Comment by Francesca-G** [comment]
> Do you happen to have any updates on whether we should focus on this now? Cc'ing @Francesca-G as well, maybe you also can share your opinion on this from a design perspective?

Yes, I can confirm the bottom sheet color is too dark on Android. It seems to also be connected to blur, a recurring problem with dark theme and blur effect throughout the app

**Comment by qoqobolo** [comment]
> It seems to also be connected to blur, a recurring problem with dark theme and blur effect throughout the app

Yes, I believe this is the case. But maybe we could adapt the design (e.g. bottom sheet color) in some way until the blur issue is fixed? Or should we keep it as it is for now?
Just want to make sure that we have an agreement on this matter before the design review🙌

**Comment by mariia-skrypnyk** [comment]
> But maybe we could adapt the design (e.g. bottom sheet color) in some way until the blur issue is fixed? Or should we keep it as it is for now?
Just want to make sure that we have an agreement on this matter before the design review🙌

@Francesca-G let me know what works the best for you? Thanks!

**Comment by qoqobolo** [comment]
Added this item for discussion on the Fit & Finish offsite: https://www.notion.so/Fit-Finish-Co-working-event-April-24-5d2edf9c37224488a32c314cf56059a2 
So let's postpone making any decisions on this matter for now 👌
cc @mariia-skrypnyk @Francesca-G @ibrkhalil

**Comment by mariia-skrypnyk** [comment]
Hi @ibrkhalil !

iOS looks good! So I move your PR to the design review for @Francesca-G approve.

**Review by Francesca-G — APPROVED** [review]
The blurred background looks good ✨
