### PR TITLE
fix scroll to bottom button is shown on chat reopen

### LINKED ISSUE #20003: Scroll to bottom button is shown on chat reopen
### Summary

https://github.com/status-im/status-mobile/assets/17097240/c1300295-0888-4bb3-8bf0-5c39ee57a18e

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20003

status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/messages/view.cljs [hunk 1]
```diff
@@ -23,17 +23,21 @@
...
-                        :distance-from-list-top (reanimated/use-shared-value 0)
-                        :chat-list-scroll-y (reanimated/use-shared-value 0)
-                        :chat-screen-layout-calculations-complete?
-                        chat-screen-layout-calculations-complete?}]
+  (let [screen-loaded?         (rf/sub [:shell/chat-screen-loaded?])
+        distance-from-list-top (reanimated/use-shared-value 0)
+        chat-list-scroll-y     (reanimated/use-shared-value 0)
+        props                  {:insets (safe-area/get-insets)
+                                :content-height (atom 0)
+                                :layout-height (atom 0)
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/view.cljs:31]: when value of `screen-loaded?` changing simple atoms are getting reinitialized, but shared values are retaining their values.

**Review by flexsurfer — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@Parveshdhull thank you for PR. No issues from my side. Ready to be merged
