### PR TITLE
Fix desktop release popup

### LINKED ISSUE #7100: Add some texts according to security review
# Problem
After security review (notes are here:  https://notes.status.im/zn74OjGLQx2V5ctqSTatgA) several changes should be done:

- [ ]  display disclaimer on download “Expect changes, vulnerabilities" 
Should be done on page with links to download release.

- [x] recovery page should include “Exposes funds associated with keys” 
Should be done on "Sign in to another account" page 

- [x] and login page “This is alpha software” -  it must appear at the start, before user created account.
jlfsljjlfkd

<blockquote><div><strong><a href="https://notes.status.im/zn74OjGLQx2V5ctqSTatgA">Desktop Release Security Questions - CodiMD</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by vkjr**
Paritally fixes #7100

### Summary:
Warning message shown at first app launch, not after user logged in.
Added clarifying text to recover page

#### Platforms (optional)
- macOS
- Linux
- Windows

#### Areas that maybe impacted (optional)
**Functional**
- account recovery
- new account

### Steps to test:
- Open Status
- Check that release warning message appeared
- Open recovery page, check that additional text present
- Close Status
- Open Status again and ensure warning message not shown

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/desktop/views.cljs [hunk 1]
```diff
@@ -10,12 +10,26 @@
...
 
 (enable-console-print!)
 
 (views/defview main []
-  (views/letsubs [view-id [:get :view-id]]
+  (views/letsubs [view-id [:get :view-id]
+                  version [:get-app-version]]
+    {:component-did-mount
+     (fn []
+       (when platform/desktop?
```
Comment (flexsurfer) [inline src/status_im/ui/screens/desktop/views.cljs]: this view only used in desktop so you don't need this check

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/desktop/views.cljs (hunk 1 above)
Comment (vkjr) [reply src/status_im/ui/screens/desktop/views.cljs]: good point, thanks!

**Review by rasom — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
Tested on Mac OSx and Windows. Can't see message after closing and reopening app.

**Comment by churik** [comment]
@vkjr OK to merge from my side to develop branch and to `release/desktop/0.9.0`

**Comment by vitvly** [comment]
Merged to both.

**Comment by vkjr** [comment]
@siphiuel, thank you!
