### PR TITLE
fix: fixes error message on login page

### LINKED ISSUE #16038: "Failed to set 'journal_mode' pragma" when generating forgot password error on login screen
**Steps:** 

1. Open login screen
2. Try to login using wrong password
3. Observe the error

**Actual result:** 

"Failed to set 'journal_mode' pragma"  error

photo_2023-05-26 18 36 15

**Expected result:** "Wrong password" error is displayed

photo_2023-05-26 18 39 03

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #16038 

### Summary

Fixed error message on login

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Type a wrong password on login page
- Verify correct error message

status: ready

### CODE REVIEW

File: src/status_im2/contexts/onboarding/profiles/view.cljs [hunk 1]
```diff
@@ -221,7 +221,7 @@
           {:type :error
            :size :default
            :icon :i/info}
-          error]
+          (i18n/label :t/wrong-password)]
```
Comment (flexsurfer) [inline src/status_im2/contexts/onboarding/profiles/view.cljs]: it's not always wrong password

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/onboarding/profiles/view.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im2/contexts/onboarding/profiles/view.cljs]: Should we make that visible to the end user?

Comment (flexsurfer) [reply src/status_im2/contexts/onboarding/profiles/view.cljs]: yes, because why would we want to confuse user with the wrong error? he might think app is hacked or smthg

Comment (briansztamfater) [reply src/status_im2/contexts/onboarding/profiles/view.cljs]: Hm right, we should check error messages either way so to be more user friendly, but for this case let's wait for 
@pavloburykh logs so maybe we can fix it on status-go side. I couldn't reproduce it by myself

Comment (pavloburykh) [reply src/status_im2/contexts/onboarding/profiles/view.cljs]: @briansztamfater @flexsurfer attached logs from nightly build here https://github.com/status-im/status-mobile/issues/16038#issuecomment-1576528847

**Review by flexsurfer — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im2/contexts/onboarding/profiles/view.cljs [hunk 2]
```diff
@@ -178,7 +179,11 @@
   (let [{:keys [key-uid name customization-color error
                 processing password]} (rf/sub [:multiaccounts/login])
         sign-in-enabled?              (rf/sub [:sign-in-enabled?])
-        profile-picture               (rf/sub [:multiaccounts/login-profiles-picture key-uid])]
+        profile-picture               (rf/sub [:multiaccounts/login-profiles-picture key-uid])
+        error                         (if (or (= error "file is not a database")
+                                              (string/starts-with? error "failed to set "))
+                                        (i18n/label :t/wrong-password)
+                                        error)]
```
Comment (briansztamfater) [inline src/status_im2/contexts/onboarding/profiles/view.cljs]: Not an ideal solution IMO, we should have a better error system on status-go, but implemented same approach as status-desktop as of now (https://github.com/status-im/status-desktop/pull/10840/files)

Comment (ilmotta) [reply src/status_im2/contexts/onboarding/profiles/view.cljs]: Agreed @briansztamfater, it's quite painful :sob: to see this style of error checking being merged because it's unreliable. If somebody in status-go changes the error strings, we'll silently fallback to a generic error to the user.

I think this problem is sufficiently important to deserve an issue in status-mobile and/or status-go. @Samyoul / @cammellos might have thought about this problem already of "how to expose errors to clients".

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/onboarding/profiles/view.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im2/contexts/onboarding/profiles/view.cljs]: https://github.com/status-im/status-go/issues/3576

**Comment by pavloburykh** [comment]
@briansztamfater hello! Do I understand correctly that current PR is not ready for testing and we should wait until addressing the issue on status go side?

**Comment by briansztamfater** [comment]
> @briansztamfater hello! Do I understand correctly that current PR is not ready for testing and we should wait until addressing the issue on status go side?

@pavloburykh I think we can start testing, but probably we'll refactor with a better implementation

**Comment by pavloburykh** [comment]
> @pavloburykh I think we can start testing, but probably we'll refactor with a better implementation

Thanx @briansztamfater ! Please take a look at the following blocker

### ISSUE 1 "Cannot read property "lastIndexOf" of null" error on app re-opening

**Steps:** 

1. Create/restore multiaccount
2. Close app
3. Reopen the app
4. Observe an error

**Actual result:** "Cannot read property "lastIndexOf" of null" error on app re-opening. User is unable to use the app. 

photo_2023-06-08 18 14 16

https://github.com/status-im/status-mobile/assets/97245802/45342c2c-ab0d-4b70-b5bf-2fbd87828788

**Comment by briansztamfater** [comment]
> > @pavloburykh I think we can start testing, but probably we'll refactor with a better implementation
> 
> Thanx @briansztamfater ! Please take a look at the following blocker
> 
> ### ISSUE 1 "Cannot read property "lastIndexOf" of null" error on app re-opening
> **Steps:**
> 
> 1. Create/restore multiaccount
> 2. Close app
> 3. Reopen the app
> 4. Observe an error
> 
> **Actual result:** "Cannot read property "lastIndexOf" of null" error on app re-opening. User is unable to use the app.
> 
> photo_2023-06-08 18 14 16
> 
>  telegram-cloud-document-2-5192813995727269177.mp4

Hi @pavloburykh, sorry about that, and thanks for testing. Issue should be resolved now.

**Comment by pavloburykh** [comment]
@briansztamfater thanx for the fix. Ready for merge.
