### PR TITLE
[fix #5604] Fixed the problem of tooltips being cropped on the android platform.

### LINKED ISSUE #5604: Password tooltip showed in account creation is cropped out
### Description

*Type*: Bug

*Summary*: Password tooltip is cut off in the password confirmation screen:

#### Expected behavior
Tooltip is fully visible.

#### Actual behavior
Tooltip is below the logo area.

### Reproduction

- Provide different passwords while creating a new account

### Additional Information
* Status version: 0.9.25
* Operating System: Android, iOS
* Tested on Android

### PR DESCRIPTION
**Pull request by wolfgangshilei**
Fixes #5604 

### Summary:

Tooltips on three screens: account/create, account/login and wallet/transaction-fee are known to be cropped out. In the former two screens, the fixes incur no visible UI changes; in the last screen, the tooltips are shifted down by 8 points.

### Steps to test:
- Open Status on android platform
- Press the "Create new Account" button, enter a valid password, then press "Next"
- In the "Confirm" input box, enter a different password, then press "Next". 
- Verify that the tooltip is fully shown.
- Select an account to sign in and enter a wrong password, press "SIGN IN"
- Wait and verify that the tooltip is fully shown.
- Sign in your account and navigate to Wallet -> Send Transaction -> Advanced -> Transaction Fee.
- Delete the default values in the "Gas limit" and "Gas price" input boxes.
- Verify that both tooltips are fully shown.

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/accounts/login/styles.cljs [hunk 1]
```diff
@@ -36,5 +36,7 @@
    :color      colors/text-light-gray
    :margin-top 8})
 
-(def password-container
-  {:margin-top 24})
+(defstyle password-container
+  {:margin-top 24
+   :android {:margin-top 11
+             :padding-top 13}})
```
Comment (goranjovic) [inline src/status_im/ui/screens/accounts/login/styles.cljs]: please align the map values

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/accounts/create/styles.cljs [hunk 2]
```diff
@@ -42,9 +43,11 @@
   {:size      82
    :icon-size 34})
 
-(def input-container
+(defstyle input-container
   {:margin-horizontal 16
-   :margin-top        105})
+   :margin-top        105
+   :android           {:padding-top 13
```
Comment (flexsurfer) [inline src/status_im/ui/screens/accounts/create/styles.cljs:49]: i believe @goranjovic meant `:androuid` map values, so it should be 
```
{:padding-top 13
 :margin-top  92
```

**Comment by flexsurfer** [comment]
could you please resolve conflicts, and squash commits, thanks

File: src/status_im/ui/screens/accounts/create/styles.cljs (hunk 2 above)
Comment (wolfgangshilei) [reply src/status_im/ui/screens/accounts/create/styles.cljs:49]: Do you mean that the map should begin from the next line?  
I think, however, the current version is consistent with relevant code in the code base.
Have I missed something? :-)

Comment (flexsurfer) [reply src/status_im/ui/screens/accounts/create/styles.cljs:49]: 13 and 92 should be aligned

File: src/status_im/ui/screens/accounts/login/styles.cljs [hunk 3]
```diff
@@ -37,7 +37,9 @@
    :margin-top 8})
 
 (def password-container
-  {:margin-top 24})
+  {:margin-top 24
+   :android    {:margin-top 11
+                :padding-top 13}})
```
Comment (flexsurfer) [inline src/status_im/ui/screens/accounts/login/styles.cljs]: same here

File: src/status_im/ui/screens/accounts/create/styles.cljs (hunk 2 above)
Comment (wolfgangshilei) [reply src/status_im/ui/screens/accounts/create/styles.cljs:49]: Yes, I see the point. I aligned them now. Please let me know if there is any other issue concerning my change. Thanks

**Comment by jakubgs** [comment]
You will have to rebase develop to make this work with out new CI setup.

**Comment by yenda** [comment]
@wolfgangshilei Thanks for your contribution ! Could you rebase on develop and squash your commit please so that the CI can make a build for testing ?

**Comment by wolfgangshilei** [comment]
@yenda I have rebased on develop and made a new commit. CI build is successful.

**Review by vitvly — APPROVED** [review]

**Comment by vitvly** [comment]
@wolfgangshilei thanks for moving this forward! There is one more obstacle - can you please GPG-sign your commit?

**Comment by wolfgangshilei** [comment]
Something is wrong with the GPG signature, and I am trying to fix it. Sorry for that

**Comment by lukaszfryc** [comment]
@wolfgangshilei looks great. Thanks!

**Review by Aninyamos99 — COMMENTED** [review]
<img src="https://github.com/pyhoon/Register-User-B4A/blob/master/APK/Demo1.png"
