### PR TITLE
[#3582] No "Add to contact" button when conversation was started from public chat

### LINKED ISSUE #3582: No "Add to contact" button when conversation was started from public chat
### Description
*Type*: Bug

*Summary*: There is no "Add to contact" button when chat is opened after clicking "Start conversation" in profile screen.

#### Expected behavior
"Add to contact" button is shown for the other person when conversation was started from public chat

#### Actual behavior
"Add to contact" is not visible in this case. See steps to reproduce.

### Reproduction
a. device A, B: install the app and join the same public chat
b. device A: send a message
c. device B: see the message, click on the device A profile and start a conversation
d. device A: should see new chat
When chat is opened there should be „Add to contact” button (just as it is present when starting 1-1 chat with a new person) 

### Additional Information
* Status version: #3547
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by cammellos**
Fixes #3582 

### Summary:

When in a 1-to-1 with a user not in the contact list we don't check whether the contact is not existing, we only checked whether is was `pending?`. This PR adds a check to also show the message when the contact does not exist.

status: ready

### CODE REVIEW

File: src/status_im/chat/screen.cljs [hunk 1]
```diff
@@ -44,7 +45,7 @@
       [toolbar/actions [{:icon      :icons/options
                          :icon-opts {:color :black}
                          :handler   #(on-options chat-id name group-chat public?)}]]]
-     [add-contact-bar]]))
+     (when-not public? [add-contact-bar public?])]))
```
Comment (jeluard) [inline src/status_im/chat/screen.cljs]: Parameter could be `false` then for more clarity?

**Review by jeluard — APPROVED** [review]

File: src/status_im/chat/screen.cljs (hunk 1 above)
Comment (cammellos) [reply src/status_im/chat/screen.cljs]: wait, that's not meant to be there, sorry

Comment (cammellos) [reply src/status_im/chat/screen.cljs]: good spot

File: src/status_im/chat/screen.cljs [hunk 2]
```diff
@@ -44,7 +45,7 @@
       [toolbar/actions [{:icon      :icons/options
                          :icon-opts {:color :black}
                          :handler   #(on-options chat-id name group-chat public?)}]]]
-     [add-contact-bar]]))
+     (when-not public? [add-contact-bar])]))
```
Comment (flexsurfer) [inline src/status_im/chat/screen.cljs]: as i understand we want to show only for 1-1 chat? so we should check  `group-chat` too

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/chat/screen.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im/chat/screen.cljs]: correct, thanks

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]
