### PR TITLE
Community channel avatar is missing on Channel screen

### LINKED ISSUE #19450: Community channel avatar is missing on Channel screen
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
Community channel avatar contains correct color and chosen emoji

#### Actual behavior
No emoji, cross is visible
Screenshot 2024-03-29 at 13 13 56

### Reproduction

1. Login to app
2. Open any community
3. Choose any channel and open it
4. Look at channel's avatar

### Additional Information

- Status version: nightly 29/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #19450 

### Summary
Adds the initial letter of the 'general' community channel on the avatar, And adds the emoji to the avatar for community channels.

status: ready

### CODE REVIEW

File: src/status_im/constants.cljs [hunk 1]
```diff
@@ -484,3 +484,5 @@
 (def ^:const alert-banner-height 40)
 
 (def ^:const status-hostname "status.app")
+
+(def ^:const default-community-channel-name "general")
```
Comment (ajayesivan) [inline src/status_im/constants.cljs]: Why do we need a default channel name constant? Can't we just use the channel name?

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 2]
```diff
@@ -112,27 +113,32 @@
...
      (if group-chat
        [quo/group-avatar
         {:customization-color color
          :size                :size-80
          :picture             profile-picture
-         :override-theme      :dark}]
+         :emoji               (when (and (not (string/blank? emoji))
+                                         community-channel?)
+                                emoji)
+         :chat-name           constants/default-community-channel-name}]
```
Comment (ajayesivan) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Channel avatar shows 'G' instead of 'T'

File: src/status_im/constants.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im/constants.cljs]: It's because the first channel we have by default when creating a new community is called general.

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Interesting, I thought any channel created must have an emoji.
Taking a look.

Comment (ajayesivan) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Emoji is not mandatory

File: src/status_im/constants.cljs (hunk 1 above)
Comment (ajayesivan) [reply src/status_im/constants.cljs]: Yeah, but shouldn't that name be in the community object? I think the channel list in the community overview screen was properly displaying the 'G' without these constants. That's why I asked.

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im/contexts/chat/messenger/messages/list/view.cljs]: Sorry missed that, Fixed

File: src/status_im/constants.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im/constants.cljs]: Fixed

**Review by ajayesivan — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil thanks for the PR. Please take a look at the issues


### ISSUE 1 Emoji is displayed outside channel avatar

**In this state there is a duplicated emoji outside avatar:**

photo_2024-04-04 14 04 18


**In this state there is wrong icon inside avatar, emoji displayed outside:**
photo_2024-04-04 14 04 26

**Comment by pavloburykh** [comment]
### ISSUE 2 Wrong channel icon

Instead this icon we should display letter or emoji if it is added

photo_2024-04-04 14 10 59

**Comment by pavloburykh** [comment]
### ISSUE 3 Long channel name is totally cut

photo_2024-04-04 14 13 06
photo_2024-04-04 14 13 08

**Comment by ibrkhalil** [comment]
I guess the Figma frame would be really helpful when implementing this
CC: @Francesca-G

**Comment by Francesca-G** [comment]
> I guess the Figma frame would be really helpful when implementing this CC: @Francesca-G

The principle is the same as the 1:1 / Group chats with long names
[Figma link](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3720%3A549580&mode=design&t=0d8qjEEZL5OoVa9K-1)

Screenshot 2024-04-08 alle 09 56 48

>
The name should be truncated with ellipsis **...** after reaching the maximum amount of characters.

Let me know if I need to request a specific screen for this case :)

**Comment by ibrkhalil** [comment]
> > I guess the Figma frame would be really helpful when implementing this CC: @Francesca-G
> 
> 
> 
> The principle is the same as the 1:1 / Group chats with long names
> 
> [Figma link](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3720%3A549580&mode=design&t=0d8qjEEZL5OoVa9K-1)
> 
> 
> 
> Screenshot 2024-04-08 alle 09 56 48
> 
> 
> 
> >
> 
> The name should be truncated with ellipsis **...** after reaching the maximum amount of characters.
> 
> 
> 
> Let me know if I need to request a specific screen for this case :)

Thank you!
What about the emoji part?

**Comment by ibrkhalil** [comment]
> > > I guess the Figma frame would be really helpful when implementing this CC: @Francesca-G
> > 
> > 
> > The principle is the same as the 1:1 / Group chats with long names
> > [Figma link](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3720%3A549580&mode=design&t=0d8qjEEZL5OoVa9K-1)
> > Screenshot 2024-04-08 alle 09 56 48
> > > 
> > 
> > 
> > The name should be truncated with ellipsis **...** after reaching the maximum amount of characters.
> > Let me know if I need to request a specific screen for this case :)
> 
> Thank you! What about the emoji part?

Got answer in DM, Emoji should remain in avatar container and shouldn't show next to channel-name

**Comment by ibrkhalil** [comment]
> ### ISSUE 3 Long channel name is totally cut
> photo_2024-04-04 14 13 06 photo_2024-04-04 14 13 08

Couldn't reproduce issue 3, Issues 1 and 2 are fixed

**Comment by pavloburykh** [comment]
> Couldn't reproduce issue 3

Please join and check in this community https://status.app/c/ixmACjIKEE5ldyBjb21tdW5pdHkgMSASDmN4Y3h6Y3h6Y3h6enhjGAMiByNERjQzNDUqAwABAgM=#zQ3shWQuxzW3NsSxSA4VExZjLKDRMUwLDuEXdfcRHbQ1aDjeC

It has channel with long name

**Comment by ibrkhalil** [comment]
> https://status.app/c/ixmACjIKEE5ldyBjb21tdW5pdHkgMSASDmN4Y3h6Y3h6Y3h6enhjGAMiByNERjQzNDUqAwABAgM=#zQ3shWQuxzW3NsSxSA4VExZjLKDRMUwLDuEXdfcRHbQ1aDjeC

image
Maybe it was fixed with my other changes.

**Comment by pavloburykh** [comment]
> Maybe it was fixed with my other changes.

Maybe it is related to 'Test mode' banner. Can you check with test mode enabled please?

**Comment by ibrkhalil** [comment]
> > Maybe it was fixed with my other changes.
> 
> Maybe it is related to 'Test mode' banner. Can you check with test mode enabled please?

image

**Comment by pavloburykh** [comment]
@ibrkhalil cool, thanks. I will check fixes later today.

**Comment by pavloburykh** [comment]
@ibrkhalil thank you for the fixes. Looks good to me. I think this PR is worth design review cc @Francesca-G

**Review by Francesca-G — COMMENTED** [review]
[Here](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M/Review-Communities-%2F-Mobile?type=design&node-id=75%3A92095&mode=design&t=mwTxjtf22JGJS77G-1) is the design review. Nice job so far 👍

**Comment by ibrkhalil** [comment]
> [Here](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M/Review-Communities-%2F-Mobile?type=design&node-id=75%3A92095&mode=design&t=mwTxjtf22JGJS77G-1) is the design review. Nice job so far 👍

Thank you so much Fransesca!
I added a subtle shadow, As I couldn't get the exact values for the shadow from Figma.
And I added the description and I fixed the edge case shown [here](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=75-92095&mode=design#762470636)

Can we please have [this](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=75-92095&mode=design#762474006) as a followup?, Also it needs more explanation on the issue is.

**Comment by Francesca-G** [comment]
> Thank you so much Fransesca! I added a subtle shadow, As I couldn't get the exact values for the shadow from Figma.

The shadow of the card is the **Shadow/Inverted/Light/02** from our design system, and needs fixing 🙏
As you can see it doesn't match design as it is now:

Screenshot 2024-04-09 alle 10 27 50

Screenshot 2024-04-09 alle 10 28 24

>
--------------------
> And I added the description and I fixed the edge case shown [here](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=75-92095&mode=design#762470636)
> 
Thank you, it is better but still not fixed. As you can see there's an overlapping of the top nav bar that needs to be fixed. I left a more in depth [comment](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=93-1886&mode=design#763334020) about it

Screenshot 2024-04-09 alle 10 35 09

>
>
--------------------
> Can we please have [this](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=75-92095&mode=design#762474006) as a followup?, Also it needs more explanation on the issue is.

Sure, we can have it as a follow up 👍
**Issue:** the Card shouldn't "cut" the channel avatar in the exact middle.
The avatar is 80px (blue rectangle) but the card meets the avatar at 44px (red rectangle), not at the exact middle:


Screenshot 2024-04-09 alle 10 40 50


>
The red guideline is where the card should stop.
As you can see here it looks like the card reaches the exact middle (40px instead of 44), so it looks shorter than design


Screenshot 2024-04-09 alle 10 50 47


>
Hopefully that's clearer, feel free to ping me if you have any further questions ☺️

**Comment by ibrkhalil** [comment]
> > Thank you so much Fransesca! I added a subtle shadow, As I couldn't get the exact values for the shadow from Figma.
> 
> The shadow of the card is the **Shadow/Inverted/Light/02** from our design system, and needs fixing 🙏 As you can see it doesn't match design as it is now:
> 
> Screenshot 2024-04-09 alle 10 27 50 Screenshot 2024-04-09 alle 10 28 24
> > 
> 
> > And I added the description and I fixed the edge case shown [here](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=75-92095&mode=design#762470636)
> 
> Thank you, it is better but still not fixed. As you can see there's an overlapping of the top nav bar that needs to be fixed. I left a more in depth [comment](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=93-1886&mode=design#763334020) about it
> 
> Screenshot 2024-04-09 alle 10 35 09
> > 
> 
> > Can we please have [this](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M?type=design&node-id=75-92095&mode=design#762474006) as a followup?, Also it needs more explanation on the issue is.
> 
> Sure, we can have it as a follow up 👍 **Issue:** the Card shouldn't "cut" the channel avatar in the exact middle. The avatar is 80px (blue rectangle) but the card meets the avatar at 44px (red rectangle), not at the exact middle:
> 
> Screenshot 2024-04-09 alle 10 40 50
> > 
> 
> The red guideline is where the card should stop. As you can see here it looks like the card reaches the exact middle (40px instead of 44), so it looks shorter than design
> 
> Screenshot 2024-04-09 alle 10 50 47
> > 
> 
> Hopefully that's clearer, feel free to ping me if you have any further questions ☺️

I added the shadow and fixed the first issue, Can we please have the avatar centering as a follow up?

**Comment by Francesca-G** [comment]
> I added the shadow and fixed the first issue, Can we please have the avatar centering as a follow up?

Shadow looks good now 👍
Sure, feel free to address them in separate issues!
