### PR TITLE
[#16378] Channel unread counter space

### LINKED ISSUE #16378: Communities - Incorrect spacing on the channel's unread counter
# Problem

As you can see below, the counter is more or less right aligned with the *joined* status, but this is wrong.

In reality, it should look like this:

### Resources

- [Figma > Communities for Mobile example](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1386-110589&mode=design&t=oaamvdSwpdeyIOtp-0)
- [Figma > Design System > List Items > Channel](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=411-18564&mode=design&t=348fBqECv2IUbpLe-0)

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #16378

### Summary

This PR solves the problem with the alignment of the unread counter in channels.

Android:

before | after

Android-before Android-after

iOS:

before | after
iOS-before iOS-now

To check how it looks compared to [expected designs](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=6605-604639&mode=design&t=ODMV6CCoyLEHTuVr-4), here is an overlay using iOS iPhone 11 Pro:

before:

PR-image-prev

now:

PR-image

the counter is still not perfect, but it seems it's due to not being allowed to correctly center some items, check next section (review notes)

### Review notes

Additional checks for the `divider-label` and `channel` components are required.
Currently, the `divider-label` component is not using correct styles, so I'm overwriting them (the component allows to do it) to properly match the UI.
I opened:  
- #16461
- #16462 

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

 - Communities overview

### Steps to test
(there might be different ways to test, this is just a suggested one, we will need two status accounts and a community 

- (Account 1) - Create a new community or join into an existing one
- (Account 2) - Join to the same community as before 
- (Account 1) - Mention Account 2 or tag everyone in a channel in the community
- (Account 2) - Check the community overview and you will see the unread counter

status: ready

### CODE REVIEW

File: src/quo2/components/dividers/divider_label.cljs [hunk 1]
```diff
@@ -1,8 +1,8 @@
 (ns quo2.components.dividers.divider-label
-  (:require [quo2.theme :as theme]
-            [quo2.components.icon :as icons]
+  (:require [quo2.components.icon :as icons]
             [quo2.components.markdown.text :as markdown.text]
             [quo2.foundations.colors :as colors]
+            [quo2.theme :as theme]
             [react-native.core :as rn]))
```
Comment (ulisesmac) [inline src/quo2/components/dividers/divider_label.cljs:6]: Sorted requires

File: src/quo2/components/dividers/divider_label.cljs [hunk 2]
```diff
@@ -36,18 +36,18 @@
...
-                                    :padding-bottom     padding-bottom
-                                    :padding-horizontal 16
-                                    :align-items        :center
-                                    :flex-direction     :row}
+       :style               (merge {:border-top-width 1
+                                    :border-top-color border-and-counter-bg-color
+                                    :padding-top      padding-top
+                                    :padding-bottom   padding-bottom
+                                    :padding-left     16
+                                    :padding-right    16
```
Comment (ulisesmac) [inline src/quo2/components/dividers/divider_label.cljs:48]: `:padding-horizontal` was set, and since these styles are not correct (in figma the padding right is 20 for this component) I'm overriding the padding right.

The problem is the padding-left & right are ignored in React Native if `padding-horizontal` is set. So the component looks the same but allows to override those paddings with this change

image

File: src/quo2/components/list_items/channel.cljs [hunk 3]
```diff
@@ -1,12 +1,11 @@
...
   (:require [quo2.components.avatars.channel-avatar :as channel-avatar]
+            [quo2.components.common.unread-grey-dot.view :refer [unread-grey-dot]]
             [quo2.components.counter.counter :as quo2.counter]
             [quo2.components.icon :as quo2.icons]
             [quo2.components.markdown.text :as quo2.text]
             [quo2.foundations.colors :as colors]
-            [quo2.theme :as theme]
-            [react-native.core :as rn]
-            [quo2.components.common.unread-grey-dot.view :refer [unread-grey-dot]]))
+            [react-native.core :as rn]))
```
Comment (ulisesmac) [inline src/quo2/components/list_items/channel.cljs:8]: Sorted requires and stopped using `quo2.theme`

File: src/quo2/components/list_items/channel.cljs [hunk 4]
```diff
@@ -21,22 +20,20 @@
...
+      {:style (cond-> {:height          48
+                       :border-radius   12
+                       :flex-direction  :row
+                       :justify-content :space-between
+                       :align-items     :center
+                       :width           "100%"
+                       :padding-left    12
+                       :padding-right   12}
+                is-active-channel? (assoc :background-color
+                                          (colors/theme-alpha channel-color 0.05 0.05)))}
```
Comment (ulisesmac) [inline src/quo2/components/list_items/channel.cljs:32]: Refactor: `:display` property is not required and  change `merge` + `when` by `cond->` + `assoc`

File: src/quo2/components/list_items/channel.cljs [hunk 5]
```diff
@@ -21,22 +20,20 @@
...
       [rn/view
-       {:display             :flex
-        :flex-direction      :row
-        :justify-content     :flex-start
-        :align-items         :center
+       {:style               {:flex-direction  :row
+                              :justify-content :flex-start
+                              :align-items     :center}
```
Comment (ulisesmac) [inline src/quo2/components/list_items/channel.cljs:36]: Refactor: Missing `:style` key for styles

File: src/quo2/components/list_items/channel.cljs [hunk 6]
```diff
@@ -45,30 +42,25 @@
          :emoji-background-color (colors/theme-alpha channel-color 0.1 0.1)
          :emoji                  emoji}]
        [quo2.text/text
-        {:style  (merge {:margin-left 12}
-                        (when (and (not locked?) muted?)
-                          {:color (if (theme/dark?) colors/neutral-60 colors/neutral-40)}))
+        {:style  (cond-> {:margin-left 12}
+                   (and (not locked?) muted?)
+                   (assoc :color (colors/theme-colors colors/neutral-40 colors/neutral-60)))
```
Comment (ulisesmac) [inline src/quo2/components/list_items/channel.cljs:47]: Refactor: changed `(if (theme/dark) ...` for `theme-colors`. Also added a `cond->`

File: src/quo2/components/list_items/channel.cljs [hunk 7]
```diff
@@ -45,30 +42,25 @@
...
+             :color           colors/neutral-40
+             :container-style {:margin-right 1 :margin-top 2}}]
+
+           (pos? (int mentions-count))
+           [rn/view {:style {:margin-right 2 :margin-top 2}}
+            [quo2.counter/counter {:override-bg-color channel-color}
+             mentions-count]]
+
+           unread-messages?
+           [unread-grey-dot :unviewed-messages-public])])]]))
```
Comment (ulisesmac) [inline src/quo2/components/list_items/channel.cljs:66]: Refactor, we had:
 
 ```clojure
 [rn/view 
 (when a
   ,,,)
 (when (and (not a) b)
   ,,,)
 (when (and (not a) (not b) c)
   ,,,)
 ]
 ```
 and now:
 
 ```clojure
 [rn/view
 (cond
   a ,,,
   b ,,,
   c ,,,)
 ]
 ```

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 8]
```diff
@@ -9,15 +9,15 @@
...
+            [status-im2.common.scroll-page.view :as scroll-page]
             [status-im2.constants :as constants]
+            [status-im2.contexts.communities.actions.chat.view :as chat-actions]
             [status-im2.contexts.communities.actions.community-options.view :as options]
             [status-im2.contexts.communities.overview.style :as style]
             [status-im2.contexts.communities.overview.utils :as utils]
             [utils.i18n :as i18n]
-            [utils.re-frame :as rf]
-            [status-im2.contexts.communities.actions.chat.view :as chat-actions]))
+            [utils.re-frame :as rf]))
```
Comment (ulisesmac) [inline src/status_im2/contexts/communities/overview/view.cljs:20]: Sorted requires

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 9]
```diff
@@ -57,48 +71,28 @@
...
+        :key       category-id
+        ;; on-layout fires only when the component re-renders, so
+        ;; in case the category hasn't changed, it will not be fired
+        :on-layout #(on-category-layout name (int (layout-y %)))}
+       (when-not (= constants/empty-category-id category-id)
+         [quo/divider-label
+          {:container-style  {:padding-left   16
+                              :padding-right  20
+                              :padding-top    6 ; Because of border width of 1
+                              :padding-bottom 7}
```
Comment (ulisesmac) [inline src/status_im2/contexts/communities/overview/view.cljs:87]: Divider label overwriten styles, this won't be required when  #16462 is addressed.

the `:padding-top` is 6 because that `divider-label` component has a border-top-width of 1, which affects the total height of the component

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 10]
```diff
@@ -57,48 +71,28 @@
...
-             (assoc chat
-                    :muted?
-                    channel-muted?
-                    :on-long-press
-                    (fn []
-                      (rf/dispatch [:show-bottom-sheet
-                                    {:content       (fn [] [actions/chat-actions chat false])
-                                     :selected-item (fn []
-                                                      [quo/channel-list-item chat])}])))]])])])])
+   (doall
```
Comment (ulisesmac) [inline src/status_im2/contexts/communities/overview/view.cljs:74]: `doall` to avoid warning about deref on lazy-seq

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 11]
```diff
@@ -57,48 +71,28 @@
...
-            [quo/channel-list-item
-             (assoc chat
-                    :muted?
-                    channel-muted?
-                    :on-long-press
-                    (fn []
-                      (rf/dispatch [:show-bottom-sheet
-                                    {:content       (fn [] [actions/chat-actions chat false])
-                                     :selected-item (fn []
-                                                      [quo/channel-list-item chat])}])))]])])])])
```
Comment (ulisesmac) [inline src/status_im2/contexts/communities/overview/view.cljs:101]: Refactored and extracted to `channel-chat-item` fn

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 12]
```diff
@@ -317,21 +311,20 @@
...
-      (let [{:keys [name images id] :as community}
-            (rf/sub [:communities/community id])
-            pending? (rf/sub [:communities/my-pending-request-to-join id])
-            cover {:uri (get-in images [:banner :uri])}
-            logo {:uri (get-in images [:thumbnail :uri])}]
+      (let [{:keys [name images id]
+             :as   community} (rf/sub [:communities/community id])
+            pending?          (rf/sub [:communities/my-pending-request-to-join id])
+            cover             {:uri (get-in images [:banner :uri])}
+            logo              {:uri (get-in images [:thumbnail :uri])}]
```
Comment (ulisesmac) [inline src/status_im2/contexts/communities/overview/view.cljs:327]: Improves let binding alignment

File: src/quo2/components/list_items/channel.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo2/components/list_items/channel.cljs:8]: actually I think you need to use `quo2.theme` here. Ideally anywhere we use `colors/theme-colors` function the 3rd parameter `theme` will be passed. Eventually we will have to do this here anyway so you may as well do it now.
i.e wrap this component in `with-theme` HOC so that it has access to `theme` prop and then pass it as a param to `theme-colors` function.

**Review by J-Son89 — APPROVED** [review]
nice work @ulisesmac and thanks for the detailed review comments 🙌

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 13]
```diff
@@ -57,48 +71,28 @@
...
+        :on-layout #(on-category-layout name (int (layout-y %)))}
+       (when-not (= constants/empty-category-id category-id)
+         [quo/divider-label
+          {:container-style  {:padding-left   16
+                              :padding-right  20
+                              :padding-top    6 ; Because of border width of 1
+                              :padding-bottom 7}
+           :label            name
+           :on-press         #(collapse-category community-id category-id collapsed?)
+           :chevron-icon     (if collapsed? :main-icons/chevron-right :main-icons/chevron-down)
```
Comment (smohamedjavid) [inline src/status_im2/contexts/communities/overview/view.cljs]: Not related to this PR, can you help us update the `:main-icons` to `:i`?

https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md#icons

**Review by smohamedjavid — APPROVED** [review]

File: src/quo2/components/list_items/channel.cljs (hunk 7 above)
Comment (ilmotta) [reply src/quo2/components/list_items/channel.cljs:66]: I prefer the `when` style actually for this kind of code :) It's personal preference. One practical advantage of a series of `when`s is that `when` is a proper s-exp and I can very easily manipulate it with structural editing and folding, things I use all the time, whereas with the `cond` macro there's no surrounding parenthesis because the macro wants to be "lighter in syntax". Usually the `cond` macro requires adding blank lines between sections to make up for the lack of structure (IMO). Such is not the case in CL...

Also the surrounding condition `(when-not locked? ...)` in the new code could be used just as well in the original code.

It's my nitpick. I love `cond`, just not here as much :)

**Review by ilmotta — APPROVED** [review]
Easy to review PR thanks to the explanations. Thanks @ulisesmac

File: src/quo2/components/list_items/channel.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/quo2/components/list_items/channel.cljs:66]: I extracted the `locked?` condition because if it's true, in the previous code, we would be returning:

`[rn/view {,,,} nil]`

In this case, the UI looks the same if we just return `nil`. Do you still think I should add that `not locked?` for each one?

And talking about `when`. I use structural editing all the time, and I haven't faced problems manipulating `cond`'s pairs.🤔

I added this refactoring because if you read the new `cond` code, since conditions are simpler, it's easier (IMO) to understand what we are checking to return a specific hiccup.

Anyway, I'm always open to revert these kinds of changes since it's a matter of tastes, so if you find it worse, please let me know 👍

File: src/status_im2/contexts/communities/overview/view.cljs (hunk 13 above)
Comment (ulisesmac) [reply src/status_im2/contexts/communities/overview/view.cljs]: Yes, I will do it!

File: src/quo2/components/list_items/channel.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/quo2/components/list_items/channel.cljs:8]: Thank you so much for noticing this @J-Son89 !

I'd prefer to address it in  #16461, since that issue is going to refactor and check the styles, I updated this issue to mention it. :+1:

File: src/status_im2/contexts/communities/overview/view.cljs (hunk 13 above)
Comment (ulisesmac) [reply src/status_im2/contexts/communities/overview/view.cljs]: @smohamedjavid  Fixed it! :+1:

File: src/quo2/components/list_items/channel.cljs (hunk 7 above)
Comment (ilmotta) [reply src/quo2/components/list_items/channel.cljs:66]: I think the refactor makes sense @ulisesmac. My point was that even when some duplication can be removed (as you did), I sometimes lean more on the side of convenience to manipulate the s-exps. Maybe my tools are rusty?

> And talking about when. I use structural editing all the time, and I haven't faced problems manipulating cond's pairs.

There's no pair in the `cond` that I can manipulate as a single expression in Clojure, so I don't understand how you manipulate the "pair". In CL `cond` looks like this:

```lisp
(cond ((> 3 4) "variant 1")
      ((> 4 2) "variant 2")
      (t "always valid variant"))
```

The same in Clojure would look like:

```clojure
(cond (> 3 4) "variant 1"
      (> 4 2) "variant 2"
      :else "always valid variant")
```

So Clojure uses less parentheses. But this slight "simplification" affects me on a daily basis, for example:

- I can't easily copy/cut the pair *test* AND *result*.
- I can't fold the pair *test* AND *result* because there's no s-exp to fold, I either fold the *test* OR the *result*.
- I can't comment/uncomment the *test* AND *result*.
- The *test* and *result* are not inside a list, so I can't for example *raise* it, etc.

> Anyway, I'm always open to revert these kinds of changes since it's a matter of tastes, so if you find it worse, please let me know

I never suggest reverting things that I think are personal preference. To me, if it's personal preference and it's aligned with what the rest of the codebase does there's nothing wrong with the person's choice. That's why I started saying it's a nitpick.

Please, keep the code @ulisesmac :)

**Comment by qoqobolo** [comment]
Thanks for your work @ulisesmac!
PR can be merged.

File: src/quo2/components/list_items/channel.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/quo2/components/list_items/channel.cljs:66]: @ilmotta I understand your problems manipulating the code, I use intelliJ + Cursive and if I want to do something with the pair I just need to select the pair, not as straightforward as if it were an s-exp, but not bad.

I recorded a small video manipulating this cond, I don't find it hard to manipulate.

[Screencast from 2023-07-04 15-37-42.webm](https://github.com/status-im/status-mobile/assets/90291778/03273bf1-4edf-499c-954c-76c84aeca2cb)

Comment (ilmotta) [reply src/quo2/components/list_items/channel.cljs:66]: Thank you @ulisesmac, it's definitely easier on your side. I see you expand the region to get the two expressions (test and result).

@yqrashawn, IIRC you use Lispy in Emacs. How do you select or manipulate in general pairs of expressions that are not surrounded by parentheses? For example the key + value of a map, or the test + result of a `cond`, or the `let` binding name + value, etc.
