### PR TITLE
fix: communities review

### LINKED ISSUE #17566: Design Review: Communities
- [ ] 1. Icon in tag look too big - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:55521&mode=design#567061210)
- [ ] 2. All channels have a lock icon - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569667689)
- [ ] 3. if community name doesn't fit it should be on 2 lines - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569675478). This may need design input.
- [ ] 4. if there's no category for the channels we shouldn't display this "none" category at the top - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569678148)

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
Fixes https://github.com/status-im/status-mobile/issues/17566

### Platform:
- Android
- iOS

Figma review: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=Vz0i3Zn5tJ0daoMs-0#569667689

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/overview/view.cljs [hunk 1]
```diff
@@ -262,9 +263,13 @@
      :margin-bottom 12}
     :avatar logo
     :title title
-    :description description
-    :title-accessibility-label :community-title
-    :description-accessibility-label :community-description}])
+    :title-number-of-lines 2
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs]: Formatting here looks strange.

Suggestion

```clojure
(defn community-header
  [title logo description]
  [quo/text-combinations
   {:container-style                 {:margin-top    (if logo
                                                       12
                                                       (+ scroll-page.style/picture-radius
                                                          scroll-page.style/picture-border-width
                                                          12))
                                      :margin-bottom 12}
    :avatar                          logo
    :title                           title
    :title-number-of-lines           2
    :description                     description
    :title-accessibility-label       :community-title
    :description-accessibility-label :community-description}])
```

File: src/quo/components/tags/tag.cljs [hunk 2]
```diff
@@ -47,13 +48,22 @@
...
        :color           icon-color}])
    (when (= type :emoji)
-     [text/text
-      {:style {:margin-right 4}
-       :size  (case size
-                32 :paragraph-1
-                24 :paragraph-2
-                nil)}
-      resource])
+     (let [image-emoji? (int? resource)]
```
Comment (ilmotta) [inline src/quo/components/tags/tag.cljs]: This part is a bit convoluted. What about this:

```clojure
(defn- emoji-comp
  [size resource]
  (let [width (case size
                32 20
                24 12
                nil)]
    (if (string? resource)
      [rn/text {:style {:margin-right 4 :font-size width}}
       resource]
      [rn/image
       {:source resource
        :style  (cond-> {:margin-right 4}
                  (= size 32) (assoc :width width :height 20)
                  (= size 24) (assoc :width width :height 12))}])))

;; Then use it:
(when (= type :emoji)
  [emoji-comp size resource])
```

Changes:

- Break apart components, this allows Reagent to completely skip processing the `emoji-comp` if props other than `size` and `resource` change.
- `cond->` instead of `merge` + `case`.
- `react-native.core/image` instead of `legacy.status-im.ui.components.react`.

**Review by ilmotta — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hey @BalogunofAfrica, could you resolve the conflict and also specify what exactly from https://github.com/status-im/status-mobile/issues/17566 and [Figma review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=Vz0i3Zn5tJ0daoMs-0#569667689) fixes this PR, please?
Unfortunately, it is not clear from the PR title and description :(
Thank you!

**Comment by BalogunofAfrica** [comment]
> Hey @BalogunofAfrica, could you resolve the conflict and also specify what exactly from #17566 and [Figma review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=Vz0i3Zn5tJ0daoMs-0#569667689) fixes this PR, please? Unfortunately, it is not clear from the PR title and description :( Thank you!

Hi @qoqobolo! 

This PR addresses all the points raised in https://github.com/status-im/status-mobile/issues/17566.

Just to be clear I have copied everything with figma link and marked them here:

- [x] 1. Icon in tag look too big - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:55521&mode=design#567061210)
- [x] 2. All channels have a lock icon - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569667689)
- [x] 3. if community name doesn't fit it should be on 2 lines - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569675478). This may need design input.
- [x] 4. if there's no category for the channels we shouldn't display this "none" category at the top - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569678148)

**Comment by qoqobolo** [comment]
> This PR addresses all the points raised in https://github.com/status-im/status-mobile/issues/17566.

Ah okay, from the comments in the issue, I understood that some of them were fixed in different PRs.
Thanks for the clarification!

**Comment by BalogunofAfrica** [comment]
> > This PR addresses all the points raised in #17566.
> 
> Ah okay, from the comments in the issue, I understood that some of them were fixed in different PRs. Thanks for the clarification!

Yeah @clauxx had worked on 2 of the items but didn't raise a PR. So I cherry picked his commits (b5b6038daa3f069ecb6e0c7ef7ced87506a5bb52 and 37b4cd2a8cbbfd0d751a4fe8fdbfba9f875e98da) and completed the items.

**Comment by qoqobolo** [comment]
@BalogunofAfrica thanks for the fixes! PR is still in testing but looks good to me so far.
I have a question. 
I just noticed and logged this issue related to the community page: https://github.com/status-im/status-mobile/issues/18706

It's also reproducible in develop, but I wanted to ask you what do you think about fixing it in this PR as it looks related (if there is an easy fix ofc). Could you take a look at this?

image

**Comment by BalogunofAfrica** [comment]
> @BalogunofAfrica thanks for the fixes! PR is still in testing but looks good to me so far. I have a question. I just noticed and logged this issue related to the community page: #18706
> 
> It's also reproducible in develop, but I wanted to ask you what do you think about fixing it in this PR as it looks related (if there is an easy fix ofc). Could you take a look at this?
> 
> image

I would address it in this PR

**Comment by qoqobolo** [comment]
> I would address it in this PR

Thank you very much!
Please let me know when it's ready for testing.

**Comment by BalogunofAfrica** [comment]
> > I would address it in this PR
> 
> Thank you very much! Please let me know when it's ready for testing.

@qoqobolo its ready for testing

**Comment by mariia-skrypnyk** [comment]
> > > I would address it in this PR
> > 
> > 
> > Thank you very much! Please let me know when it's ready for testing.
> 
> @qoqobolo its ready for testing

Hi @BalogunofAfrica !
Thanks for your fix in removing this "Community admin will review your request" text.
According to the [design ](https://www.figma.com/file/2z9YfUWCK5OQ0UeyLImmOK/Joining-channels-and-communities?type=design&node-id=195-339170&mode=design&t=CMl8tb4s7BO0oPZx-0) we do not use it neither for Pending nor for Joined statuses. 
Failed e2e tests are not related to this PR. 
Ready to be checked by the design team. @Francesca-G

**Review by Francesca-G — COMMENTED** [review]
Here's the [design review](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M/Review-Communities-%2F-Mobile?type=design&node-id=13%3A55092&mode=design&t=QS4tlYP4KuA85ZxR-1) :)

**Comment by BalogunofAfrica** [comment]
@mariia-skrypnyk Can this be merged, I would create a follow up issue for @Francesca-G's review.

**Comment by mariia-skrypnyk** [comment]
> Here's the [design review](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M/Review-Communities-%2F-Mobile?type=design&node-id=13%3A55092&mode=design&t=QS4tlYP4KuA85ZxR-1) :)

Hi @Francesca-G !
As this PR was regarding these issues:
1. Icon in tag look too big - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:55521&mode=design#567061210)
 2. All channels have a lock icon - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569667689)
 3. if community name doesn't fit it should be on 2 lines - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569675478). This may need design input.
 4. if t[here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569678148)'s no category for the channels we shouldn't display this "none" category at the top - comment here

Are you ok that it will be merged and your review feedback will be included to the followup issue created by @BalogunofAfrica?

**Comment by Francesca-G** [comment]
> Are you ok that it will be merged and your review feedback will be included to the followup issue created by @BalogunofAfrica?

Sure, works for me 👍
