### PR TITLE
Fix compressed key ellipsis

### LINKED ISSUE #16047: Adjust compressed ellipsis public key display
The ellipsis of compressed keys are not according to designs.

### PR DESCRIPTION
**Pull request by siddarthkay**
fixes #16047

### Summary

This PR does the following:
- Moves `get-abbreviated-profile-url` from shell share view into `utils.address` and update its usage.
- Adds `get-shortened-compressed-key` to `utils.address` and update the code using `get-shortened-key` to now use `get-shortened-compressed-key` instead.

### Testing notes
This PR ensures that the ellipsis on public key is now as per designs. 

#### Platforms
- Android
- iOS

status: ready

### CODE REVIEW

File: src/utils/address.cljs [hunk 1]
```diff
@@ -14,3 +14,28 @@
   [address]
   (when address
     (get-shortened-key (eip55/address->checksum (ethereum/normalized-hex address)))))
+
+(defn get-abbreviated-profile-url
```
Comment (cammellos) [inline src/utils/address.cljs:18]: You want to cover  both functions with unit tests

Comment (siddarthkay) [reply src/utils/address.cljs:18]: Added a bunch of tests :)

File: src/utils/address_test.cljs [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+
+(deftest test-get-abbreviated-profile-url
+  (testing "Check if the function returns the correct abbreviated profile URL"
+    (is (= "join.status.im/u/zQ3sh...aimrdYpzeFUa"
+           (utils.address/get-abbreviated-profile-url
+            "join.status.im/u/"
+            "zQ3shPrnUhhR42JJn3QdhodGest8w8MjiH8hPaimrdYpzeFUa")))
+
+    (testing "Check if the function handles empty public key"
```
Comment (J-Son89) [inline src/utils/address_test.cljs]: I think these test descriptions could be clearer.
e.g
"Check value is nil if the function input is empty public key"

**Review by vkjr — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Review by ajayesivan — COMMENTED** [review]
@siddarthkay It appears that the usage has not been updated in all places. Is this within the scope of this PR, or is it unrelated to the changes being made?

**Comment by siddarthkay** [comment]
Hey @ajayesivan : good catch, yes this should be in scope. I'll fix this. Thanks

**Comment by pavloburykh** [comment]
Hey @siddarthkay ! Is PR ready for testing?

**Comment by siddarthkay** [comment]
Hi @pavloburykh : yes PR is ready for testing.

**Review by ajayesivan — APPROVED** [review]

**Review by rahulpsingh — APPROVED** [review]

**Comment by pavloburykh** [comment]
@siddarthkay thanx for the PR! Please take a look at the following issue

### ISSUE 1 Share button overlaps chat key in Share screen (Android)

Reproducing on Android 12, Samsung Galaxy A52

photo_2023-07-07 13 24 22

**Comment by siddarthkay** [comment]
Hi @pavloburykh : Thanks for testing and finding this issue.

This issue is resolved in this PR : https://github.com/status-im/status-mobile/pull/16257
I am waiting to first add blur components to quo2 and once discussion with design team is completed on blur I will mark that PR ready for testing..

**Comment by pavloburykh** [comment]
> Hi @pavloburykh : Thanks for testing and finding this issue.
> 
> This issue is resolved in this PR : #16257 I am waiting to first add blur components to quo2 and once discussion with design team is completed on blur I will mark that PR ready for testing..

Cool, thanx @siddarthkay ! I thought that this is PR related bug as I do not reproduce it in develop branch.

**Comment by siddarthkay** [comment]
Right @pavloburykh  this PR does update the number of characters of the link to profile( to match format of designs). 

However https://github.com/status-im/status-mobile/pull/16257 fixes padding and alignment issues which takes care of the overlap.

**Comment by pavloburykh** [comment]
@siddarthkay thank you! no more issues from my side. Ready for merge.
