### PR TITLE
fix: long press & bg color animation for deleted message

### LINKED ISSUE #17390: Can't 'Delete for everyone' and unpin the message that was 'Deleted for me'
# Bug Report

## Problem 

The feature was added in [this PR](https://github.com/status-im/status-mobile/pull/15689)

> it also adds the ability to Delete message for everyone that have Deleted for me (discussed with John) and the ability of unpin messages that have been deleted for me.

But it doesn't work anymore, there is no way to long-press the system message:

https://github.com/status-im/status-mobile/assets/67952253/1906bb62-44d0-482e-bea6-2c6db2b63d6c

#### Expected behavior
- The user can unpin `Deleted for me` message
- The user can `Delete for everyone` the message that was `Deleted for me`

#### Actual behavior
Long press on system messages doesn't work > you cannot take any action on such messages

### Reproduction

1. Open chat
2. Send a message
3. Pin the message
4. `Delete for me` the message
5. Open `Pinned messages` and try to unpin that message
6. Open chat again and try to `Delete for everyone` the `deleted for me` message

### Additional Information

- Status version: nightly 22/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by yqrashawn**
fixes #17390

### Summary

fix long press menu and on delete bg color animation for deleted (for me) message

### Review notes

recommend to review commit by commit

commit 1: system_message.cljs -> system_message/view.cljs and some cleanup
commit 2: extract style from system_message/view.cljs, add system_message/style.cljs
commit 3: add on long press and bg color animation

#### Areas that maybe impacted
deleted (for me) message in 1-1 chat, community channel and pinned message

### Before and after screenshots comparison

simulator_screenshot_784BA980-3EE4-4D3E-8776-F8777B6A5EB2

https://github.com/status-im/status-mobile/assets/15090582/41b3294f-2644-498b-b0df-e4886d631adb

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/menus/pinned_messages/view.cljs [hunk 1]
```diff
@@ -21,10 +20,8 @@
               (first community-images)))))
 
 (defn message-render-fn
-  [{:keys [deleted? deleted-for-me?] :as message} _ _ context]
-  (if (or deleted? deleted-for-me?)
-    [content.deleted/deleted-message message context]
-    [message/message message context (atom false)]))
```
Comment (yqrashawn) [inline src/status_im2/contexts/chat/menus/pinned_messages/view.cljs:28]: `message/message` has this duplicate `(if (or deleted? deleted-for-me?) ...)` as well

File: src/quo2/components/messages/system_message/view.cljs [hunk 2]
```diff
@@ -177,13 +150,38 @@
...
+       style/system-message-deleted-animation-end-bg-color
+       0
+       :linear
+       1000))
+
+    [wrapper
+     {:style         (if animate-bg-color?
+                       animated-style
+                       style/system-message-wrapper)
+      :on-long-press on-long-press}
```
Comment (flexsurfer) [inline src/quo2/components/messages/system_message/view.cljs:183]: are you sure on-long-press and background are needed for all system messages?

Comment (flexsurfer) [reply src/quo2/components/messages/system_message/view.cljs:183]: where does this animated background come from? do we have documentation for this?

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 3]
```diff
@@ -205,18 +205,23 @@
...
-                {:content       (drawers/reactions-and-actions message-data context)
-                 :selected-item (fn []
-                                  [rn/view {:pointer-events :none}
-                                   [user-message-content
-                                    {:message-data    message-data
-                                     :context         context
-                                     :keyboard-shown? keyboard-shown?
-                                     :show-reactions? true
-                                     :show-user-info? true}]])}]))
+                (cond-> {:content (drawers/reactions-and-actions message-data context)}
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: seems like cond is redundant, `if` can be used for :selected-item value

File: src/quo2/components/messages/system_message/view.cljs (hunk 2 above)
Comment (yqrashawn) [reply src/quo2/components/messages/system_message/view.cljs:183]: They are not needed by other system messages, only deleted (for me) message
it's just the UI already done in system message, long press and animation both affect the UI so I choose to put them in system message

animated background design is at https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=5713-624109&mode=design&t=TVdUm1nRzpSVoy6k-4

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 3 above)
Comment (yqrashawn) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: fixed, thanks

**Review by flexsurfer — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @yqrashawn, thank you for the PR. I've found only one issue, but it could be considered a follow-up. It's up to you whether it's better to fix it within the scope of this PR or separately

## ISSUE 1: When a message is removed by the "Delete for You" option, it cannot be long-pressed and removed by the "Delete for Everyone" option if the current message is not pinned.

### Steps to Reproduce:
1. Open a chat.
2. Send a message.
3. Remove the message by `Delete for you` option
4. Try to long-press the current message 
5. Observe that there is no option to remove it for everyone.

### Actual Behavior:
Currently, the "Delete for Me" option cannot be long-pressed and removed by the "Delete for Everyone" option for unpinned messages.

### Expected Behavior:
Users should be able to long-press a "deleted for me" message and have the option to "Delete for Everyone," even if the message is not pinned

**Comment by yqrashawn** [comment]
Remaining issues
~1. pin deleted for me message within undo timer will undelete the message~
~2. delete undo delete undo ... pinned deleted-for-me message cause a message UI bug~

**Comment by yqrashawn** [comment]
added code that disables long press action menu for deleted (for me) messages within the undo timer

action within undo timer cause lots issue
deleted (for me) status are stored locally in client side within undo timer
actions (pin, unpin, prev delete timer timedout) that change messages states during undo timer and sync them to status-go leads to conflict states between synced-back status-go data and client local data

so I added code that disables long press action menu for deleted (for me) messages within undo timer
action menu will show up on long press as usual once the undo toast disappears
is this ok? @John-44

**Comment by John-44** [comment]
> added code that disables long press action menu for deleted (for me) messages within the undo timer
> 
> action within undo timer cause lots issue deleted (for me) status are stored locally in client side within undo timer actions (pin, unpin, prev delete timer timedout) that change messages states during undo timer and sync them to status-go leads to conflict states between synced-back status-go data and client local data
> 
> so I added code that disables long press action menu for deleted (for me) messages within undo timer action menu will show up on long press as usual once the undo toast disappears is this ok? @John-44

This sounds good to me :-)   But really it's a question for @pedro-et @mariocnovoa @xAlisher

**Comment by yqrashawn** [comment]
> so I added code that disables long press action menu for deleted (for me) messages within undo timer
@VolodLytvynenko all designers confirmed at https://discord.com/channels/624634427930312714/975775548007678033/1161542718347026443

ready to test again

**Comment by VolodLytvynenko** [comment]
Hi @yqrashawn thank you for your work. No issues from my side anymore. PR is ready to be merged

**Comment by yqrashawn** [comment]
rebased, waiting for e2e
