### PR TITLE
fix: inability to input data while routes are loading

### LINKED ISSUE #20230: Inability to input data while routes are loading
### Description:
When attempting to generate routes and input additional data simultaneously, the input does not respond. This hinders user interaction and may lead to frustration.

### Steps:
1. Go to the routes generation page.
2. Enter a valid value to generate routes.
3. While routes are generating, attempt to enter another value.

### Actual result:
The data input does not respond while routes generation

https://github.com/status-im/status-mobile/assets/52490791/51cd3d8b-b0a5-49f6-85a2-7a88eb2a1e09

### Expected result:
Users should be able to input data even while routes are generated. potential solution: Refresh the route generation when new data is being entered or stop it if an exceeded value is entered

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/20230

### Summary
This PR fixes inability to update input while routes are loading

### Demo

https://github.com/status-im/status-mobile/assets/29354102/47b68d9a-9672-4e79-aa8f-78d78aca3468

### CODE REVIEW

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 1]
```diff
@@ -376,18 +376,15 @@
                                      max-decimals  (if crypto-currency? crypto-decimals 2)
                                      regex-pattern (str "^\\d*\\.?\\d{0," max-decimals "}$")
                                      regex         (re-pattern regex-pattern)]
-                                 (when (and (not loading-routes?)
-                                            (re-matches regex new-text))
+                                 (when (re-matches regex new-text)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:379]: To safetly implement this change, isn't enough just removing this condition.

We should also ignore/cancel/discard the pending request previously sent since it's not valid anymore.

Ideally, we would like:

1. User enters `0.001`
2. We ask for the routes and the input loads
3. While loading, user enters `0.002`
4. We ask for the NEW routes and the input loads
5. We receive the routes for `0.002` and the input stops loading

But with this implementation we will get:

1. User enters `0.001`
2. We ask for the routes and the input loads
3. While loading, user enters `0.002`
4. **Routes for `0.001` are received and stored in re-frame** (also maybe this makes the UI to blink and create a misleading db state)
5. We ask for the NEW routes and the input loads
6. We receive the routes for `0.002` and the input stops loading

So, what will happen if while executing `5` the request fails or takes too long to return? are the routes received in `4` interpreted as valid even if they come from a stale input value?

I think we should update the mechanism to ask for routes. Once an input has changed its value while the routes are being fetched, we should discard, cancel or ignore the request and response for those routes and ask for a new ones.

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs:379]: > We should also ignore/cancel/discard the pending request previously sent since it's not valid anymore.

@ulisesmac I think we are already doing that. @briansztamfater can you please correct me if I am wrong, isn't [that line](https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/send/events.cljs#L28) checking if the suggested route response in the right one using the timestamp?

> also maybe this makes the UI to blink

That blinking is another issue, it's from the bug introduced to the input component recently

Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs:379]: Thank you Omar, as long as this behavior is covered, everything is ok 👍

**Comment by J-Son89** [comment]
maybe you could provide a quick overview in the description of what was causing the bug and how you addressed it?

**Comment by J-Son89** [comment]
looks fine to me, but would be nice if @briansztamfater could give this a quick check 👌

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 2]
```diff
@@ -376,18 +376,15 @@
...
                                    (debounce/clear-all)
                                    (set-just-toggled-mode? false)
                                    (set-input-state #(controlled-input/add-character % c)))))
        :on-delete            (fn []
-                               (when-not loading-routes?
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:385]: @J-Son89 just removed this condition to allow typing while loading

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs:379]: > > We should also ignore/cancel/discard the pending request previously sent since it's not valid anymore.
> 
> @ulisesmac I think we are already doing that. @briansztamfater can you please correct me if I am wrong, isn't [that line](https://github.com/status-im/status-mobile/blob/develop/src/status_im/contexts/wallet/send/events.cljs#L28) checking if the suggested route response in the right one using the timestamp?

I think that should effectively cover this case. But anyway let's have @status-im/mobile-qa be aware of this case so it is properly tested suring manual QA 👍

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 3]
```diff
@@ -376,18 +376,15 @@
...
-                                 (debounce/clear-all)
-                                 (set-just-toggled-mode? false)
-                                 (set-input-state controlled-input/delete-last)))
+                               (debounce/clear-all)
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:384]: We should be sure `:wallet/clean-suggested-routes` is called if the value is invalid, I think this line should cover the case but just to be sure https://github.com/status-im/status-mobile/blob/24194fb34e6d9a7a5692a54d7de8882910d3dc9e/src/status_im/contexts/wallet/send/routes/view.cljs#L27

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 4]
```diff
@@ -376,18 +376,15 @@
...
+                               (set-just-toggled-mode? false)
+                               (set-input-state controlled-input/delete-last))
        :on-long-press-delete (fn []
-                               (when-not loading-routes?
-                                 (debounce/clear-all)
-                                 (set-just-toggled-mode? false)
-                                 (set-input-state controlled-input/delete-all)))}]]))
+                               (debounce/clear-all)
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:389]: We should check if https://github.com/status-im/status-mobile/blob/24194fb34e6d9a7a5692a54d7de8882910d3dc9e/src/status_im/contexts/wallet/send/routes/view.cljs#L27 is also called too in this case

**Review by briansztamfater — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem thank you for PR. No issues from my side. PR is ready to be merged
