### PR TITLE
[#20189]  Activity tab fixes

### LINKED ISSUE #20113: Error TaskQueue:Error with task: Doesn't support name appears after navigating to Activity tab (IOS)
cc @OmarBasem  looks like related to Activity tab. 

Unfortunately there are no steps for reproduction. Issue occurs randomly. So far I have faced on IOS only. 

**Steps:** 

1. Perform token transaction
2. After confirming the transaction go back to Account screen
3. Open Activity tab
4. See if error appears

**Actual result:** sometimes ```TaskQueue:Error with task: Doesn't support name``` appears 

photo_2024-05-20 16 54 14
[status_logs (6).zip](https://github.com/status-im/status-mobile/files/15377864/status_logs.6.zip)

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #20189: App crashes with 'Name no supported' error after navigation to Activity tab
Crash is reproducible on specific account. Please contact me in DM and I will provide a seed phrase. 

**Steps:**

1. Recover given user
2. Switch to testnet
3. Go to `Account 1`
4. Open Activity tab
5. Observe the result

**Actual result:** App crashes with 'Name no supported' error. Transaction history is not fetched. 

**Expected result:** no crash. transaction history is fetched. 
[Status-debug-logs - 2024-05-27T154024.157.zip](https://github.com/status-im/status-mobile/files/15456126/Status-debug-logs.-.2024-05-27T154024.157.zip)

https://github.com/status-im/status-mobile/assets/97245802/fb90ba80-2614-4f36-9c29-c613799cb59a

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20189 
fixes #20113

### Summary

This PR solves the crashes. Additionally I found some issues related to the activity tab, so they are being sovled in this PR:

### Some transactions had a "Custom" network when it was done on Mainnet

Before vs now:
  
 
### Missing circle in `wallet-activity` component

Before vs now:
  

### Missing horizontal padding around the activity items
(noticeable while pressing an item)

Before vs now:
 
 
 Figma:
 image

### Wrong report of transactions

The account is: 
image

The `from` and `to` values weren't right in receive:

Now:

### Code refactor

The calculations were made in the view, now they've been moved to a subscription and also the mechanism (temporary) now asks for the last 35 events of the `current-viewing-account` when it's visited, instead of just asking for 20 events in total for all the registered accounts.

### Review notes

 The activity tab only supports **Send** and **Receive** transactions.

Sometimes the data looks bad, this is being investigated by the desktop team.
Example: Transaction of an ERC-1155 collectible:

image

Addittionally, a similar mechanism to the implemented in collectibles is needed to properly implement paging in the activity tab, but we aren't focusing on this yet.

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Recover an account with transactions
- Look at the activity tab

status: ready

### CODE REVIEW

File: src/quo/components/wallet/wallet_activity/style.cljs [hunk 1]
```diff
@@ -54,10 +54,17 @@
...
+  [theme]
+  {:width           33
+   :height          33
+   :padding         1
+   :border-width    1
+   :border-radius   16
+   :border-color    (colors/theme-colors colors/neutral-20 colors/neutral-80 theme)
+   :margin-top      8
+   :justify-content :center
+   :align-items     :center})
```
Comment (ulisesmac) [inline src/quo/components/wallet/wallet_activity/style.cljs]: The missing circle, the height was 32 but changed to 33 because the border radius

File: src/quo/components/wallet/wallet_activity/style.cljs [hunk 2]
```diff
@@ -85,6 +92,6 @@
 
 (def icon-status-container
   {:position :absolute
-   :bottom   0
-   :right    0})
+   :bottom   -1
+   :right    -1})
```
Comment (ulisesmac) [inline src/quo/components/wallet/wallet_activity/style.cljs]: Same here, it's -1 to bne aligned with the border radius

File: src/quo/components/wallet/wallet_activity/view.cljs [hunk 3]
```diff
@@ -78,7 +78,7 @@
               :width        12
               :height       12
               :borderRadius 6}]}
-    [icon/icon (transaction-icon transaction)
+    [icon/icon (transaction-icon transaction :i/placeholder)
```
Comment (ulisesmac) [inline src/quo/components/wallet/wallet_activity/view.cljs]: Some transactions didn't properly set the `transaction-type`, so while rendering this function returned `nil`, causing a crash.

Now the types are being properly set, but I added a placeholder just to make sure the app doesn't crash in case we don't pass the type again.

File: src/status_im/contexts/wallet/account/view.cljs [hunk 4]
```diff
@@ -25,10 +25,13 @@
...
-      (let [{:keys [name color formatted-balance
-                    watch-only?]} (rf/sub [:wallet/current-viewing-account])
-            customization-color   (rf/sub [:profile/customization-color])]
-        (rn/use-unmount #(rf/dispatch [:wallet/close-account-page]))
+      (let [{:keys [name color formatted-balance watch-only?
+                    address]}   (rf/sub [:wallet/current-viewing-account])
+            customization-color (rf/sub [:profile/customization-color])]
+
+        (rn/use-mount
+         #(rf/dispatch [:wallet/fetch-activities-for-current-account address]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/account/view.cljs]: Remove the `use-unmount` to navigate back because it'll make the app hard to develop.

Added the event to fetch activities for the current account

File: src/status_im/contexts/wallet/common/activity_tab/events.cljs [hunk 5]
```diff
@@ -0,0 +1,45 @@
+(ns status-im.contexts.wallet.common.activity-tab.events
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/activity_tab/events.cljs:1]: These events were slightly changed and  moved to the activity-tab events, previously they were general

File: src/status_im/contexts/wallet/common/activity_tab/view.cljs [hunk 6]
```diff
@@ -1,61 +1,42 @@
...
-      :third-tag-prefix  (constants/third-tag-prefix activity-type)
-      :third-tag         {:type    :address
-                          :address (if receiving-activity? sender recipient)}
-      :fourth-tag-prefix (constants/fourth-tag-prefix activity-type)
-      :fourth-tag        {:size         24
-                          :type         :network
-                          :network-logo (quo.resources/get-network (chain/chain-id->chain-keyword
-                                                                    chain-id))
-                          :network-name (chain/chain-id->chain-name chain-id)}
-      :blur?             false}]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/activity_tab/view.cljs:58]: Fixed and moved all of these calculations to a subscription :eyes:

File: src/status_im/contexts/wallet/common/activity_tab/view.cljs [hunk 7]
```diff
@@ -1,61 +1,42 @@
...
+  [{:keys [transaction] :as activity}]
+  (case transaction
+    (:send :receive) [send-and-receive-activity activity]
+    nil))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/activity_tab/view.cljs:39]: Just preparing the code to handle the future transactions

File: src/status_im/contexts/wallet/signals.cljs [hunk 8]
```diff
@@ -37,9 +37,10 @@
        "wallet-blockchain-status-changed"         {:fx [[:dispatch
                                                          [:wallet/blockchain-status-changed
                                                           (transforms/js->clj event-js)]]]}
-       "wallet-activity-filtering-done"           {:fx [[:dispatch
-                                                         [:wallet/activity-filtering-done
-                                                          (transforms/js->clj event-js)]]]}
+       "wallet-activity-filtering-done"           {:fx
+                                                   [[:dispatch
+                                                     [:wallet/activity-filtering-for-current-account-done
+                                                      (transforms/js->clj event-js)]]]}
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/signals.cljs:43]: Changed because now (temporary) we process activites per account, not for all the accounts

File: src/status_im/subs/wallet/activities.cljs [hunk 9]
```diff
@@ -1,26 +1,82 @@
...
+     (->> current-viewing-account-address
+          (get activities)
+          (keep #(process-activity-by-type chain-id->network-name %))
+          (group-by (fn [{:keys [timestamp]}]
+                      (datetime/timestamp->relative-short-date (* timestamp 1000))))
+          (map (fn [[date activities]]
+                 {:title     date
+                  :data      activities
+                  :timestamp (:timestamp (first activities))}))
+          (sort-by (fn [{:keys [timestamp]}] (- timestamp)))))))
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/activities.cljs:82]: Added `:wallet/network-details` to properly report the involved network.
Also `process-activity-by-type` is having all the calculations previously made in the view file.

File: src/status_im/subs/wallet/send.cljs [hunk 10]
```diff
@@ -40,14 +41,15 @@
...
-                                           (= sender current-viewing-account-address))
-                                         all-transactions)]
-     (set (map :recipient users-sent-transactions)))))
+ (fn [[all-activities current-viewing-account-address]]
+   (let [address-activity (get all-activities current-viewing-account-address)]
+     (->> address-activity
+          (keep (fn [{:keys [activity-type recipient]}]
+                  (when (= constants/wallet-activity-type-send activity-type)
+                    recipient)))
+          (distinct)))))
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/send.cljs:52]: This subscription needed the sub changed in this PR (activities for current account), so now it's adapted to return the same data but with less calculations.

Previously it executed:
 `mapcat` -> `filter` -> `map` -> `set`
 
 Now: 
 `keep` -> `distinct`

File: src/status_im/subs/wallet/activities.cljs [hunk 11]
```diff
@@ -1,26 +1,82 @@
...
+ :wallet/activities-for-current-viewing-account
  :<- [:wallet/all-activities]
  :<- [:wallet/current-viewing-account-address]
- (fn [[activities current-viewing-account-address]]
-   (->> activities
-        (filter (fn [{:keys [sender recipient activity-type]}]
-                  (let [receiving-activity? (= activity-type constants/wallet-activity-type-receive)
-                        relevant-address    (if receiving-activity? recipient sender)]
-                    (= relevant-address current-viewing-account-address))))
-        (distinct)
```
Comment (OmarBasem) [inline src/status_im/subs/wallet/activities.cljs:21]: Is `distinct` not required, even as a safety check? (there was this [bug ](https://github.com/status-im/status-mobile/pull/19906#issuecomment-2110074516))

**Review by OmarBasem — APPROVED** [review]
Great work @ulisesmac !

**Review by smohamedjavid — APPROVED** [review]
🚀 Nice work!

File: src/status_im/subs/wallet/activities.cljs (hunk 11 above)
Comment (ulisesmac) [reply src/status_im/subs/wallet/activities.cljs:21]: Previously we were using all accounts transactions and filtering the ones where the address appeared, that's why we needed to use `distinct`.

Now the activities in re-frame are stored by account, so there's no place for duplicates :)

**Comment by pavloburykh** [comment]
@ulisesmac thanks for the PR. Please take a look at the issue

### ISSUE 1 Part of the circle of wallet activity component is visible inside icon

**Actual result:** 

photo_2024-06-11 18 14 00
photo_2024-06-11 18 18 26

**Expected result:**

https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=1070-283956&t=anvkH9JJ7pD08uNb-0

Wallet for Mobile – Figma 2024-06-11 18-22-13

**Comment by ulisesmac** [comment]
Hi @pavloburykh 

Thanks for testing, I completely missed these states while fixing the ring.
The component has been updated, here are some screenshots:

Screenshot from 2024-06-11 14-47-23 Screenshot from 2024-06-11 14-46-56 Screenshot from 2024-06-11 14-46-45 Screenshot from 2024-06-11 14-46-34 Screenshot from 2024-06-11 14-46-25

**Comment by pavloburykh** [comment]
> Thanks for testing, I completely missed these states while fixing the ring.
> The component has been updated, here are some screenshots:

@ulisesmac thanx for the fix. PR is ready for merge.

**Review by vkjr — APPROVED** [review]
