### PR TITLE
fixed dark border around the community logo 

### LINKED ISSUE #17565: Dark border around community display picture
A dark border around the community display-picture in the request to join the community screen.

Review comment: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:55521&mode=design#567052004

### Steps to reproduce
- Open a community with a light display picture.

Already reported in the 1.24 design review https://github.com/status-im/status-mobile/issues/16862 (issue 2) and fixed, but somehow it's been reintroduced.

Reproducible on both iOS & Android

### PR DESCRIPTION
**Pull request by jo-mut**
This PR removes the dark border around the community logo on communities page. The bug is only reproducible when the user has not yet joined the community

fixes https://github.com/status-im/status-mobile/issues/17565

Before & After screen shots
Screenshot 2023-12-28 at 12 49 44

### CODE REVIEW

File: src/status_im/common/scroll_page/style.cljs [hunk 1]
```diff
@@ -58,15 +58,16 @@
...
-   {:border-radius picture-diameter
-    :border-width  picture-border-width
-    :border-color  (colors/theme-colors colors/white colors/neutral-95)
-    :position      :absolute
-    :top           (- (+ picture-radius picture-border-width))
-    :left          (+ (/ picture-radius 2) picture-border-width)}))
+   {:border-radius    picture-diameter
+    :border-width     picture-border-width
+    :border-color     (colors/theme-colors colors/white colors/neutral-95)
+    :background-color (colors/theme-colors colors/white colors/neutral-95 theme)
```
Comment (Parveshdhull) [inline src/status_im/common/scroll_page/style.cljs]: hi @J-Son89, this use case looks a little inconsistent to me. The `theme-colors` function works even if we don't pass the theme param, as the global theme will be used.
So should we only pass the theme when we are overwriting the global theme, like in a shell, or always pass (though we might not have access to the theme param)? wdyt?

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im/common/scroll_page/style.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/common/scroll_page/style.cljs]: (unrelated to pr)

Comment (J-Son89) [reply src/status_im/common/scroll_page/style.cljs]: I believe we should always pass the 3rd param. Unfortunately that function theme-colors was created with the ratom referenced inside it and it was harder to refactor all older uses/ prevent people from not passing it. 
Imo in the ideal case the page theme (from context) or global theme (from ratom) would be passed as a param and we keep theme-color function pure.
Theme should be accessible all places within the app so there's no issue with that, one exception is the status bar for navigation but we will have to look for a solution to that.
Cc @ilmotta 

@jo-mut can you update the uses here to pass theme along?

**Review by siddarthkay — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by jo-mut** [comment]
@Francesca-G I worked on this and looks now. You could take a look and maybe confirm

**Comment by Francesca-G** [comment]
> @Francesca-G I worked on this and looks now. You could take a look and maybe confirm

looks good to me as well ✨

**Comment by mariia-skrypnyk** [comment]
Hi @jo-mut! Thanks fro your PR!
I've tested it both on iOS and Android and can agree that no dark border around the community logo anymore!
So you can merge it! 

Can I ask you for a small comment like "design review is required" for your future PR's in case it is needed. 
If you'll do so, for us -QA's it is a flag to move your PR to the Design review column after testing. As it's better not to involve designers to comment PR's that are not tested yet. Hope it make sense! Thanks!

**Comment by jo-mut** [comment]
@mariia-skrypnyk I may have just missed a step and involved the design review earlier. Just as a point of clarification you mean, the design review comes after pr is QA tested is that what you mean?

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk I may have just missed a step and involved the design review earlier. Just as a point of clarification you mean, the design review comes after pr is QA tested is that what you mean?

Thanks @jo-mut for your comment. Yes, if you PR needs a design review this step comes after QA's testing. We involve designers by dragging the card to the Design review column. You can find all this described in this doc [here. ](https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md)
