### PR TITLE
Text input fixes (#1020, #1021, #1024, #1026)

### LINKED ISSUE #1020: Double /phone command
[comment]: # (Please replace ... with your information. Remove < and >)

### Description
image

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

And also in suggestions, there are /phone request and /phone command

### PR DESCRIPTION
**Pull request by alwx**
Fixes #1020, #1021, #1024, #1026

### CODE REVIEW

File: src/status_im/chat/handlers.cljs [hunk 1]
```diff
@@ -237,6 +237,7 @@
         commands-loaded? (if js/goog.DEBUG
                            false
                            (get-in db [:chats chat-id :commands-loaded]))]
+    (log/debug "ALWX chat-id" chat-id)
```
Comment (rasom) [inline src/status_im/chat/handlers.cljs]: Please, remove this message
