### PR TITLE
Wallet: fix nested scrollviews warning

### LINKED ISSUE #18700: Wallet: VirtualizedLists should never be nested inside plain ScrollViews
# Bug Report

## Problem 
The screen "Send to"
image

Is always showing the following error, we should fix it before it breaks something.

Error:
```
 VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. 
VirtualizedList@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:87160:36
FlatList@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:86424:36
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:257487:48
react_native.gesture.flat_list
status_im.contexts.wallet.send.select_address.tabs.view.my_accounts
status_im.contexts.wallet.send.select_address.tabs.view.view_internal
quo.theme.f_with_theme
G__28196
RCTView
View@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:69307:43
RCTView
View@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:69307:43
RCTScrollView
ScrollView@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:78276:36
ScrollView
RCTView
View@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:69307:43
status_im.common.floating_button_page.view.view
status_im.contexts.wallet.send.select_address.view.f_view
status_im.contexts.wallet.send.select_address.view.view
RCTView
View@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:69307:43
quo.theme.provider
reagent20
RNGestureHandlerRootView
GestureHandlerRootView
gestureHandlerRootHOC(reagent20)
WrappedComponent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:197538:84
RCTView
View@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:69307:43
RCTView
View@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:69307:43
AppContainer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:69151:36
```

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/18700

This PR fixes nested scrollviews warning

Changed screens:
Screenshot_20240205_101901_Status
Screenshot_20240205_101910_Status
Screenshot_20240205_101922_Status

### CODE REVIEW

File: src/status_im/contexts/wallet/send/select_asset/view.cljs [hunk 1]
```diff
@@ -93,28 +93,24 @@
         on-close       #(rf/dispatch [:navigate-back-within-stack :wallet-select-asset])]
     (fn []
       [rn/safe-area-view {:style style/container}
-       [rn/scroll-view
-        {:content-container-style      {:flex 1}
-         :keyboard-should-persist-taps :handled
-         :scroll-enabled               false}
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/select_asset/view.cljs:99]: I guess we need to move the prop (`keyboard-should-persist-taps`) to the outer scroll view.

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/select_asset/view.cljs:99]: @smohamedjavid I don't think there is an outer scroll view (there shouldn't be, that's what's causing the problem :) ) 

That prop is on the FlatList of the assets list

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/select_asset/view.cljs:99]: My bad. I overlooked.

**Review by smohamedjavid — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by J-Son89** [comment]
nit: can we make use of <image src="" width="300px" /> for images in pr descriptions to make it easier to see the images together? 
size is just an example but a little smaller than it is now  :)

**Comment by OmarBasem** [comment]
> nit: can we make use of  for images in pr descriptions to make it easier to see the images together?
size is just an example but a little smaller than it is now :)

I don't get what you mean. Are you asking to make the images smaller?
