### PR TITLE
fix: test networks short-name->id

### LINKED ISSUE #18693: `short-name->id` function for test networks
The function `short-name->id` is not working for test networks resulting in incorrect receiver preferences networks in test mode

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/18693

This PR fixes the function `short-name->id` to work for test networks also.

### CODE REVIEW

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 1]
```diff
@@ -195,10 +195,20 @@
    constants/arbitrum-chain-id      :arbitrum
    constants/arbitrum-test-chain-id :arbitrum})
 
-(def short-name->id
-  {:eth  constants/mainnet-chain-id
-   :opt  constants/optimism-chain-id
-   :arb1 constants/arbitrum-chain-id})
+(defn get-chain-id
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/common/utils.cljs]: Probably we can make it private.

**Review by smohamedjavid — APPROVED** [review]
