### PR TITLE
Fix for sender's name, profile icon, chat key, timestamp being lost for messages that contain images

### LINKED ISSUE #15392: Sender's name, profile icon, chat key, timestamp are lost for messages that contain images
**Steps:** 

1. Open any chat
2. Send a message containing image/images
3. See if sender's name, profile icon, chat key, timestamp are displayed for the sent message

**Expected result:** sender's name, profile icon, chat key, timestamp are displayed for the sent message

**Actual result:** sender's name, profile icon, chat key, timestamp are are lost for image messages

photo_2023-03-16 17 02 50

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
Fixes #15392

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

File: src/status_im2/subs/chat/messages.cljs [hunk 1]
```diff
@@ -102,63 +102,58 @@
...
-                    pinned-by      (when pinned (or (message :pinned-by) (pinned-message :pinned-by)))
-                    message        (assoc message :pinned pinned :pinned-by pinned-by)]
+                    pinned (if pinned-message true (some? (message :pinned-by)))
+                    pinned-by (when pinned (or (message :pinned-by) (pinned-message :pinned-by)))
+                    message (assoc message :pinned pinned :pinned-by pinned-by)]
                 (merge message %)))
             %)
          message-list)))
 
 (defn albumize-messages
```
Comment (alwx) [inline src/status_im2/subs/chat/messages.cljs:113]: The change to `albumize-messages` is the only important change; the rest is a code style fix applied automatically because for some reason it was broken

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@alwx thanx for the fix. PR is ready to be merged after resolving conflicts. @alwx let me know if re-test will be required after resolving conflicts in src/status_im2/subs/chat/messages.cljs
