### PR TITLE
[Fix] QR Viewfinder overlap with segmented tabs in Sign in

### LINKED ISSUE #15567: Sign in - QR code viewfinder is overlapping with segmented tabs on Android
# Bug Report

The QR code viewfinder in Sign In is overlapping with segmented tabs.

Screenshot_20230403-203510

Screenshot_1680534562

### Expected behaviour

The QR code viewfinder should not overlap with segmented tabs.

### Reproduction

1) Open Status
2) Navigate to `Sign-in`
3) Enable the Camera

### Additional Information

- Status Version: nightly 
- Operating System: Android

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15567

### Summary

This PR fixes the overlap of the QR code viewfinder with segmented tabs.

Screenshot_1680534596

### Review notes

This bug is caused in Android due to the recent changes of allowing the screens to draw behind the status bar of Android. The fix is to add the status bar height to the hole view `y` coordinate.

### Platforms

- Android

### Steps to test

- Open Status
- Navigate to `Sign In`
- Enable the Camera by giving Camera Permission

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/onboarding/sign_in/view.cljs [hunk 1]
```diff
@@ -85,14 +85,22 @@
...
-                 (let [layout      (js->clj (oops/oget event "nativeEvent.layout")
-                                            :keywordize-keys
-                                            true)
-                       view-finder (assoc layout :height (:width layout))]
-                   (reset! qr-view-finder view-finder)))}])
+  (let [status-bar-height (rn/status-bar-height)]
+    [rn/view
+     {:style     style/qr-view-finder
+      :on-layout (fn [event]
+                   (let [layout      (js->clj (oops/oget event "nativeEvent.layout")
```
Comment (briansztamfater) [inline src/status_im2/contexts/onboarding/sign_in/view.cljs]: You may want to use `js->clj` from `utils.transforms` namespace

**Review by briansztamfater — APPROVED** [review]

File: src/status_im2/contexts/onboarding/sign_in/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/onboarding/sign_in/view.cljs]: Updated 👍  Thanks, @briansztamfater!

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the fix. Ready to be merged.
