### PR TITLE
Wallet UX: fix sticking errors and enable more frequent refreshes

### LINKED ISSUE #1777: Error Data Loading error is shown in new wallet
### Description

*Type*: Bug

*Summary*: Error message is shown in new wallet and the asset is not updated . I can see recent values for %, asset and USD only when I re-launch the app however the error message is still in place

#### Actual behavior
Error Data loading message is shown,

image

### Solution (maybe)

- [ ] separate the different errors in the wallet
- [ ] clear the error in case of success
- [ ] show better error message ?

### Reproduction

- Open Status
- Create account
- /faucet some ETG
- go to new wallet tab

### Additional Information
* Status version: 0.9.10-63-g03a9a844+
* Operating System: Android, iOS

#### Logs
[logcat 0709.txt](https://github.com/status-im/status-react/files/1284187/logcat.0709.txt)

### PR DESCRIPTION
**Pull request by yenda**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #1777

### Summary:
- fix wallet errors that were sticking when refresh occurred
- add separate errors for transaction history fetching with visual feedback
- update wallet when going on wallet tab
- update transaction list when opening transaction modal

### Steps to test:
- Open Status
- go to wallet tab
- kill network
- refresh wallet assets
- check error is shown
- go to transaction history
- check error is shown
- restart network
- refresh transaction history
- check error is gone
- go back to wallet tab
- refresh
- check error is gone
[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### Relevant issues for this PR
- #1786 A general mechanism to feed errors back to user
- #1785 Handle timeout for network failure in utils.utils/http-get and http-post

### CODE REVIEW

File: src/status_im/ui/screens/wallet/events.cljs [hunk 1]
```diff
@@ -18,107 +19,114 @@
...
-  :refresh-wallet
+  :update-wallet
   (fn [{{:keys [web3 accounts/current-account-id network] :as db} :db} [_ a]]
     {:get-balance {:web3          web3
                    :account-id    current-account-id
-                   :success-event :update-balance
+                   :success-event :update-balance-success
                    :error-event   :update-balance-fail}
-     :dispatch    [:load-prices]
+     :dispatch    [:update-prices]
```
Comment (janherich) [inline src/status_im/ui/screens/wallet/events.cljs]: Why is this distinct dispatch instead of calling (extracted) `:update-prices` handler function and merging its effects into `:update-wallet` handler effects ?

File: src/status_im/ui/screens/wallet/navigation.cljs [hunk 2]
```diff
@@ -0,0 +1,13 @@
+(ns status-im.ui.screens.wallet.navigation
+  (:require [re-frame.core :as re-frame]
+            [status-im.ui.screens.navigation :as navigation]))
+
+(defmethod navigation/preload-data! :wallet
+  [db _]
+  (re-frame/dispatch [:update-wallet])
```
Comment (janherich) [inline src/status_im/ui/screens/wallet/navigation.cljs:7]: We should revisit how `navigation/preload-data!` is implemented, because currently, it forces you to go async (dispatch event) whenever something impure has to happen during navigation. 
Just a note, it's certainly not in scope of this PR to solve it.

File: src/status_im/components/styles.cljs [hunk 3]
```diff
@@ -20,6 +20,7 @@
 (def color-gray6 "#212121")
 (def color-gray7 "#9fa3b4")
 (def color-gray8 "#6E777E")
+(def color-gray9 "#E9EBEC")
```
Comment (jeluard) [inline src/status_im/components/styles.cljs:23]: We have a serious gray problem !!

File: src/status_im/ui/screens/wallet/events.cljs [hunk 4]
```diff
@@ -18,107 +19,114 @@
          (on-error err))))
     (on-error "web3 or account-id not available")))
 
+(defn assoc-error-message [db error-type err]
+  (assoc-in db [:wallet :errors error-type] (or (when err (str err))
+                                                :unknown-error)))
+
+(defn clear-error-message [db error-type]
+  (update-in db [:wallet :errors] dissoc error-type))
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/events.cljs:27]: Maybe make a note/ticket to figure out some generic mechanism.

File: src/status_im/ui/screens/wallet/events.cljs [hunk 5]
```diff
@@ -18,107 +19,114 @@
...
+        (clear-error-message :transaction-update)
         (assoc-in [:wallet :transactions] transactions)
         (assoc-in [:wallet :transactions-loading?] false))))
 
 (handlers/register-handler-db
   :update-transactions-fail
   (fn [db [_ err]]
     (log/debug "Unable to get transactions: " err)
-    (-> (assoc-error-message db :error)
+    (-> db
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/events.cljs:97]: Any specific reason for this?

File: src/status_im/ui/screens/wallet/events.cljs [hunk 6]
```diff
@@ -18,107 +19,114 @@
...
+        (assoc-error-message :transactions-update err)
         (assoc-in [:wallet :transactions-loading?] false))))
 
 (handlers/register-handler-db
-  :update-balance
+  :update-balance-success
   (fn [db [_ balance]]
     (-> db
+        (clear-error-message :balance-update)
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/events.cljs]: So the error message is cleared only when a response is received?
Why not clear it when the request is triggered?

File: src/status_im/ui/screens/wallet/history/styles.cljs [hunk 7]
```diff
@@ -1,14 +1,30 @@
 (ns status-im.ui.screens.wallet.history.styles
-  (:require [status-im.components.styles :as st]))
+  (:require [status-im.components.styles :as styles]))
+
+(def error-container
+  {:align-self       :center
+   :justify-content  :center
+   :border-radius    4
+   :padding-top      4
+   :padding-bottom   4
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/history/styles.cljs]: You can use `padding-vertical` here.

**Review by jeluard — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/wallet/events.cljs (hunk 5 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/events.cljs:97]: for using the threading macro (readability) or for the separate error message ?

File: src/status_im/ui/screens/wallet/events.cljs (hunk 6 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/events.cljs]: good idea

File: src/status_im/ui/screens/wallet/navigation.cljs (hunk 2 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/navigation.cljs:7]: I think at some point we will move to a react-native navigation library so this will all change

File: src/status_im/ui/screens/wallet/events.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/events.cljs]: I made a change tell me if it was you meant

File: src/status_im/ui/screens/wallet/events.cljs (hunk 4 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/events.cljs:27]: ok I will make a note, we could indeed have an error key that follows such pattern for all possible error that need to be fed back to the user

File: src/status_im/ui/screens/wallet/events.cljs (hunk 1 above)
Comment (janherich) [reply src/status_im/ui/screens/wallet/events.cljs]: Not really, what I meant was to extract `:update-prices` handler into named function, like this:
```clj
(defn update-prices [db]
  {:get-prices  {:from "ETH"
                 :to   "USD"
   :success-event :update-prices-success
   :error-event   :update-prices-fail}
   :db (assoc db :prices-loading? true)}))

;; This handler registration is only necessary when `:update-prices` ever gets called as result of user action
(handlers/register-handler-fx
  :update-prices
  (fn [{:keys [db]} _]
    (update-prices db)))
```
Then in the `:update-wallet` handler, instead of indicating dispatch, you can do:
```clj
(merge {:web3          web3
        :account-id    current-account-id
        :success-event :update-balance-success
        :error-event   :update-balance-fail}
       (update-prices db)))
````

File: src/status_im/components/styles.cljs (hunk 3 above)
Comment (yenda) [reply src/status_im/components/styles.cljs:23]: yes probably maybe we should report that to the design team, but here I just used the color that was in zepplin and it wasn't already there

File: src/status_im/ui/screens/wallet/events.cljs (hunk 5 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/events.cljs:97]: About not using `(assoc-error-message db :error)` as initial value.

Comment (yenda) [reply src/status_im/ui/screens/wallet/events.cljs:97]: I suppose it is a matter of style, I prefer to use the simple variable as first argument of the macro. It's macro compile time anyway.

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/wallet/events.cljs (hunk 5 above)
Comment (oskarth) [reply src/status_im/ui/screens/wallet/events.cljs:97]: I generally agree with @yenda, it's clear that "I'm doing this set of transformations/operations to this one thing". Increases code clarity imo.

**Review by janherich — APPROVED** [review]

**Review by rasom — APPROVED** [review]
