### PR TITLE
Fixed issues with styling in pinned messages panel.

### LINKED ISSUE #16090: Messaging - In Chat - Pinned Messages List UI bugs
For the pinned messages list there are some bugs

Posts__Attachments_for_Mobile_Figma_2023-05-30_14-05-58

wrong backround on message, should not have purple/grey background
margins/padding incorrect - icon and username are not aligned

divider line missing in implementation

Designs:
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=5303-942869&t=uMckyCQiwcLeQldG-4

### PR DESCRIPTION
**Pull request by rahulpsingh**
fixes #16090 

### Summary

 - Fixed issues with styling in pinned messages panel.

### Screenshots

| Android | iOS |
| --- | ----------- |
| Screenshot Android | Screenshot iOS |

#### Platforms

- Android
- iOS

##### Functional

- Chat

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/menus/pinned_messages/view.cljs [hunk 1]
```diff
@@ -8,7 +8,8 @@
             [status-im2.contexts.chat.menus.pinned-messages.style :as style]
             [utils.i18n :as i18n]
             [utils.re-frame :as rf]
-            [react-native.gesture :as gesture]))
+            [react-native.gesture :as gesture]
+            [quo.design-system.spacing :as spacing]))
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/menus/pinned_messages/view.cljs]: hmm, we should not be using anything from `quo` namespace

Comment (J-Son89) [reply src/status_im2/contexts/chat/menus/pinned_messages/view.cljs]: but we do have a spacings in foundation which is not in our codebase for some reason 🙃 https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=624-350&mode=design&t=xed0yo4wQPZIiuWa-0

File: src/status_im2/contexts/chat/menus/pinned_messages/view.cljs [hunk 2]
```diff
@@ -51,7 +52,7 @@
          :render-fn   message-render-fn
          :footer      [rn/view {:style (style/list-footer bottom-inset)}]
          :key-fn      list-key-fn
-         :separator   quo/separator}]
+         :separator   [quo/separator {:style {:margin-vertical (:tiny spacing/spacing)}}]}]
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/menus/pinned_messages/view.cljs]: I don't quite know what this `quo/separator` component is. I can't quite see it in the design system. Perhaps it should be just moved to status_im2.common?

Comment (rahulpsingh) [reply src/status_im2/contexts/chat/menus/pinned_messages/view.cljs]: Yes, I'll move it to status_im2.common. That should be a good idea. Thank you!!

File: src/quo2/components/spacing.cljs [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+   :space-3  6
+   :space-4  8
+   :space-5  10
+   :space-6  12
+   :space-7  16
+   :space-8  20
+   :space-9  24
+   :space-10 32
+   :space-11 40
+   :space-12 56})
```
Comment (ibrkhalil) [inline src/quo2/components/spacing.cljs]: Instead of memorizing which `:spacing-d` to use, I think using integers as keywords is OK in this map. Also, I didn't find tokens for the spacing in Figma.
Something like
```clj
(def spacing
  {0  0
   2  2
   4  4
   6  6
   8  8
   10 10
   12 12
   16 16
   20 20
   24 24
   32 32
   40 40
   56 56})
```

Comment (rahulpsingh) [reply src/quo2/components/spacing.cljs]: @ibrkhalil  We can find the spacing tokens here: https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=624-350&mode=design&t=xed0yo4wQPZIiuWa-0. Just to confirm, Do you mean to change for example: `:spacing-2` to just `:4` or something like `:spacing-4` instead?

Comment (J-Son89) [reply src/quo2/components/spacing.cljs]: Hmm can you put these seconds in quo2.foundations.spacings to align with Figma? They should also keep the semantic name as to couple as described in figma foundations 👌

Comment (J-Son89) [reply src/quo2/components/spacing.cljs]: cc @ilmotta as it's a topic we discussed recently to some degree

Comment (ibrkhalil) [reply src/quo2/components/spacing.cljs]: I didn't see that spacing file before :) @rahulpsingh
Well as longs at it's tokenized then it's nice to have them tokenized here too!

**Review by ibrkhalil — APPROVED** [review]

File: src/quo2/components/spacing.cljs (hunk 3 above)
Comment (rahulpsingh) [reply src/quo2/components/spacing.cljs]: > Hmm can you put these seconds in quo2.foundations.spacings to align with Figma? They should also keep the semantic name as to couple as described in figma foundations 👌

Sure, yes!! I'll update the spacing to `quo2.foundations.spacings`.

File: src/quo2/foundations/spacing.cljs [hunk 4]
```diff
@@ -0,0 +1,16 @@
+(ns quo2.foundations.spacing)
+
+(def get-spacing
```
Comment (ilmotta) [inline src/quo2/foundations/spacing.cljs]: In Clojure, it's more idiomatic to name maps as nouns, not as verbs (even though maps can be used as functions).

Since the namespace is `spacing`, using `spacing/get-spacing` is redundant.

I also don't see the value of using a keyword if it's basically used as an index. I would just use a number. I think that's what @ibrkhalil meant in another comment.

I suggest we change `get-spacing` to just `get` (and remember to use `:refer-clojure` and `:exclude` in case we need the `cljs.core/get` in the same namespace).

```clojure
;; Instead of
(:space-4 spacing/get-spacing)

;; suggestion
(spacing/get 4)
```

--------

But to be honest I don't yet understand this spacing foundation in Figma. It says there the value is a multiplier (of 4 in Figma), but in this PR it's being used as a fixed value. I think it's a good idea to confirm with designers what do they mean by this spacing foundation and **how they use it** in practice because up until this point we haven't used in quo2. @J-Son89, @rahulpsingh

Comment (J-Son89) [reply src/quo2/foundations/spacing.cljs]: Yep I agree @rahulpsingh can you check with design if/how they are using this 👍

Comment (rahulpsingh) [reply src/quo2/foundations/spacing.cljs]: Yes, the values here should be multiplier(of 4). I will implement it in the suggested way.

Thank you!! 👍

Comment (rahulpsingh) [reply src/quo2/foundations/spacing.cljs]: This needs some decisions as well and can be done in separate ticket. I just created a ticket for this: https://github.com/status-im/status-mobile/issues/16508

**Review by ajayesivan — APPROVED** [review]

File: src/quo2/foundations/spacing.cljs (hunk 4 above)
Comment (J-Son89) [reply src/quo2/foundations/spacing.cljs]: Thanks @rahulpsingh !

**Comment by VolodLytvynenko** [comment]
hi @rahulpsingh thank you for PR. No issues from my side. Ready to be merged
