### PR TITLE
[#20909] fix: dapp wrong network refusal

### LINKED ISSUE #20909: 👁️ Cannot read property `responseSessionRequest` of null
Related comment: https://github.com/status-im/status-mobile/pull/20693#issuecomment-2228288723

Steps (exactly the same as in the comment above):

1. Connect to https://react-app.walletconnect.com/ using testnetwork (Sepolia)
2. Disable testmode and login the app
3. Trigger `personal_sign` event
4. Try to sign the event
5. Observe the result

Screenshot 2024-07-25 at 14 29 21

_Originally posted by @qoqobolo in https://github.com/status-im/status-mobile/issues/20799#issuecomment-2250208801_

### LINKED ISSUE #20910: 📛 Triggering request while being on wrong network results in `Doesn't support name error`
**Steps:** 

1. Connect to dApp using testnet (I used https://react-app.walletconnect.com/ for testing)
2. Disable testnet in mobile app
3. Trigger testnet event in dApp 
4. Observe the error in Status app

**Actual result:** `Doesn't support name error` error appears. It will appear on every relogin. App is completely frozen and thus unusable. 

photo_2024-07-24 14 30 17

<ShivekKhurana> I was not able to reproduce this in dev builds. Maybe it applies to release? Opening the issue we can understand and fix it.

_Originally posted by @pavloburykh in https://github.com/status-im/status-mobile/issues/20799#issuecomment-2247682461_

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #20909
fixes #20910
### Summary

No error is shown when signing the event when user's network differs from event network

#### Areas that maybe impacted

- Dapps communication when network differ

### Steps to test

- Connect to https://react-app.walletconnect.com/ using testnetwork (Sepolia)
- Disable testmode and login the app
- Trigger personal_sign event
- Observe the result

#### Before
Dapp was stuck in pending request modal and no notification in the app
image

#### After 

Screenshot 2024-08-23 at 18 48 24
Screenshot 2024-08-23 at 18 48 24

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/wallet_connect/core.cljs [hunk 1]
```diff
@@ -50,7 +50,11 @@
 
 (defn get-session-dapp-metadata
   [proposal]
-  (get-in proposal [:params :proposer :metadata]))
+  (let [metadata (get-in proposal [:params :proposer :metadata])
+        origin   (get-in proposal [:verifyContext :verified :origin])]
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/wallet_connect/core.cljs:54]: Can get the url right here:

```clj
(get-in proposal [:verifyContext :verified :origin :url])
```

and later instead of `{:url origin}`, just `origin`

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/core.cljs:54]: the origin is the url and just to create the same structure like :metadata i put it like this {:url origing}, we use this func like this
`[{:keys [name url]} (wallet-connect-core/get-session-dapp-metadata proposal)]`

**Review by clauxx — APPROVED** [review]

File: src/status_im/contexts/wallet/wallet_connect/responding_events.cljs [hunk 2]
```diff
@@ -114,8 +114,9 @@
 
 (rf/reg-event-fx
  :wallet-connect/send-response
- (fn [{:keys [db]} [{:keys [result error]}]]
-   (when-let [{:keys [id topic] :as event} (get-in db [:wallet-connect/current-request :event])]
+ (fn [{:keys [db]} [{:keys [request result error]}]]
+   (when-let [{:keys [id topic] :as event} (or request
+                                               (get-in db [:wallet-connect/current-request :event]))]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/wallet_connect/responding_events.cljs:120]: Is `request` always available for this function?

If so, then the `when-let` could just be a single let. Otherwise, could you please share in which cases this function returns `nil` due to `when-let`?

File: src/status_im/contexts/wallet/wallet_connect/core.cljs [hunk 3]
```diff
@@ -50,7 +50,11 @@
...
+    (if metadata
+      metadata
+      {:url origin})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/wallet_connect/core.cljs]: Nit:
`(if 'a 'a 'b)` -> `(or 'a 'b)`

**Review by ulisesmac — COMMENTED** [review]
Hi @mohsen-ghafouri, thanks for your PR! I left a couple of comments related to code. I'm not familiar with the logic so please consider adding another reviewer

File: src/status_im/contexts/wallet/wallet_connect/responding_events.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/responding_events.cljs:120]: for this i'm not aware about all possible scenario and it was there already, but either request should be available or should be something in db. maybe with when-let is safer, no?

Comment (ulisesmac) [reply src/status_im/contexts/wallet/wallet_connect/responding_events.cljs:120]: It was there because, I guess, it was possible that the info in `db` was not set, but now we are also receiving `request` as parameter so I thought at least one of those would always be passed.

If we are unsure, then we can keep `when-let` 👍

**Review by ulisesmac — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

The behaviour of this logic looks for me not the same.

**ISSUE 1: Error appears when we trigger personal_sign request**

**Steps:**

1. Login on Testnet mode
2. Wake a connect with https://react-app.walletconnect.com/
3. Go to Profile -> Wallet and change network to Mainnet
4. Go to Account from what you've connected in sep 2.
5. Trigger personal_sign request

**Actual result:**

Screenshot 2024-09-05 at 10 09 34

Screenshot 2024-09-05 at 10 02 27

https://github.com/user-attachments/assets/4e6f9b53-83de-481e-90db-5fedf3baaafe

[logs.zip](https://github.com/user-attachments/files/16886174/logs.zip)

**Expected result:**

No errors and stuckings.
Just a toast as in PR description.

**Comment by mohsen-ghafouri** [comment]
Hey @mariia-skrypnyk, thank you for checking this. but i cannot reproduce the issue, here is how i tested the flow. 

please let me know if it's always reproducible or not, or how can i increase the chance to see it. 



https://github.com/user-attachments/assets/3ed13fd7-ddc3-4398-a11b-010893e82a82

**Comment by mohsen-ghafouri** [comment]
Also please consider this issue for testing so we can close it if not reproducible anymore #20910

**Comment by mariia-skrypnyk** [comment]
Hey @mohsen-ghafouri !

Rechecked this issue.
I have a thought that this error appears because of no currency issue I've reported here https://github.com/status-im/status-mobile/issues/21190

My steps are the same : 
1) connect to WC on a Testnet
2) switch to mainnet
3) trigger personal_sign

As You can see on my video toast that you implemented appears right after balance finally get the currency (00:36 sec on the video) :

https://github.com/user-attachments/assets/9a07704a-66d9-49c0-9423-9fc001a91280

 My device is iPhone 13 (17.6.1)

**Comment by mohsen-ghafouri** [comment]
I see, @mariia-skrypnyk if when currency loaded it works fine then let's merge this PR and i will check that issue under https://github.com/status-im/status-mobile/issues/21190

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri sounds like a plan!

Thanks, PR ready to be merged.
