### PR TITLE
Fix auth slider resetting when wallet connect signing is finished

### LINKED ISSUE #20228: Fix auth slider resetting when wallet connect signing is finished
# Bug Report

## Problem 
[comment]: # (A problem description)

Fix the auth slider resetting when the wallet connect signing is finished. 

https://github.com/status-im/status-mobile/assets/21865759/f1d6a669-51c7-4d58-8c4b-785285aeb24e

#### Expected behavior
The slider stays in place when the modal hides

#### Actual behavior
The slider moves back when the modal hides

### Reproduction

1. Connect to a dapp via wallet connect (e.g. https://react-app.walletconnect.com/)
2. Send a signing/transaction request
3. Slide the auth slider and auth with password or biometrics
4. Notice the slider resetting when the modal hides

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
Fixes https://github.com/status-im/status-mobile/issues/20228

#### Platforms

- Android
- iOS

##### Functional

- wallet connect

status: ready

### CODE REVIEW

File: src/quo/components/buttons/slide_button/view.cljs [hunk 1]
```diff
@@ -54,9 +54,10 @@
         on-track-layout               (rn/use-callback
                                        #(set-track-width (oops/oget % "nativeEvent.layout.width")))
         reset-fn                      (rn/use-callback
-                                       (fn []
+                                       (fn [reset-to-end-position?]
                                          (set-sliding-complete false)
-                                         (animations/reset-track-position x-pos)))
+                                         (animations/reset-track-position
+                                          (if reset-to-end-position? track-width x-pos))))
```
Comment (seanstrom) [inline src/quo/components/buttons/slide_button/view.cljs]: Do we always want to reset the x-position when we reset the slider? For example, what should happen if we fail to authenticate and we need to reset the slider?

**Comment by seanstrom** [comment]
@alwx Thanks for fixing this 🙏

File: src/quo/components/buttons/slide_button/view.cljs (hunk 1 above)
Comment (clauxx) [reply src/quo/components/buttons/slide_button/view.cljs]: From what I see, it would reset it to the "end" only when successful, and if failed, it would go back to the initial `x-pos`. Correct me if I'm wrong @alwx.

**Review by clauxx — APPROVED** [review]
Looks good, but we definitely need QA testing on this.

File: src/quo/components/buttons/slide_button/view.cljs (hunk 1 above)
Comment (alwx) [reply src/quo/components/buttons/slide_button/view.cljs]: The idea here is that the tracker has two positions — the zero position and the end position, and everything else is basically a transformation from one position to another.
In the case of a failure we want to move back to the zero position, and in the case of a success we want to move to the end position (we should already be there but we do it for extra safety). That's basically what this code does. If `reset-to-end-position?` is true then we move it to the end position; we move it to the zero position otherwise.

**Comment by alwx** [comment]
For QA: probably the easiest way of testing it is through quo components library (I've added a boolean value `reset-to-end-position?`). You can also test it as a part of wallet connect feature.

File: src/quo/components/buttons/slide_button/view.cljs (hunk 1 above)
Comment (seanstrom) [reply src/quo/components/buttons/slide_button/view.cljs]: I suppose what I'm thinking is that we could only call the reset function when we know we want to reset from the end-position to the start-position. But I'm not sure how many changes that would require to make that possible, thoughts?

**Comment by seanstrom** [comment]
For QA: the main areas that I'm aware of that would be affected would include:
* Creating a key-pair / account
* Wallet transactions (?)
* Importing a key-pair
  * I initially added some code to always reset the slider when closing the authentication modal because we would need to reset the slider if something failed. So attempting to import a key-pair with an incorrect (but valid) recovery-phrase would be a good test case.

**Review by seanstrom — APPROVED** [review]
Looks good ✅ 
I left a small comment about a potential refactor, but it's not a blocker for me, thanks again for fixing this 🙏

**Comment by qoqobolo** [comment]
@alwx thanks for the fix and PR and @seanstrom for the potentially affected areas!
Unfortunately, the scope of the PR is still not completely clear for me. 

The title says: "Fix auth slider resetting **when wallet connect signing** is finished". 

Does this mean that in other places where the slider is used, the behavior should also change?

I'm asking because I see that, for example, when signing a transaction, the slider does not reset (this is expected, if I understand correctly), but when creating an account, it returns to the zero position after biometrics/entering password (see the video below on 0:07), although the action is successful🤔
Is this expected or should it be fixed in this PR?


https://github.com/status-im/status-mobile/assets/67952253/cb72e8a2-f1e0-40f0-866f-bb563b2717f9

---

> For QA: probably the easiest way of testing it is through quo components library (I've added a boolean value reset-to-end-position?)

@alwx It behaves a bit weird there :) please check the videos from Android and iOS:


https://github.com/status-im/status-mobile/assets/67952253/96a8bccd-d7a6-493e-8354-f20091b14755


https://github.com/status-im/status-mobile/assets/67952253/7c2613b3-7d6f-410f-aa0b-5333aa09608f

As you can see, on iOS it feels like it doesn't really respect the option I select, and on Android it's just hidden behind the pop-up🤷🏻

---

> You can also test it as a part of wallet connect feature.

@alwx Hmm I tried to enable the feature flag, but got this message when pressing the plus button:
Screenshot 2024-07-01 at 14 08 22

Am I doing smth wrong? Could you tell me how can I try it?

---
I am sorry if I'm missing something, but I'm a bit confused😅🙈
Some clarifications will be greatly appreciated!

**Comment by alwx** [comment]
@qoqobolo it should work the way it worked before for all other situations except wallet connect transactions, there was no goal to change the behaviour for other cases.

Regarding the connected dapps alert: this is expected, we haven't implemented this functionality yet (I will do in the next day or so in my PR). Currently if you want to add the dapp you can use a general QR code scanner.

Regarding how it works in quo design library: I will update it later today and will let you know.

**Comment by qoqobolo** [comment]
> @qoqobolo it should work the way it worked before for all other situations except wallet connect transactions, there was no goal to change the behaviour for other cases.
> 
> Regarding the connected dapps alert: this is expected, we haven't implemented this functionality yet (I will do in the next day or so in my PR). Currently if you want to add the dapp you can use a general QR code scanner.
> 
> Regarding how it works in quo design library: I will update it later today and will let you know.

Aha, thanks a lot for clarifying it @alwx, it's all more clear now 👍

**Comment by alwx** [comment]
@qoqobolo now it's fixed. You can check quo design library — this is how it works there now (should not reset to start pos when signing transactions)

https://github.com/status-im/status-mobile/assets/911127/d53a2a79-5fcd-443c-9981-1f401a882397

**Comment by mariia-skrypnyk** [comment]
Hey @alwx !

Some substitution on the QA field 😉
Thanks for your PR details.
I've checked slider behaviour from the quo preview.
Also went through places where regression could appear.
All looks good except one place that I can not check because of bug reported in https://github.com/status-im/status-mobile/issues/20609.
I will check this slider there as soon as it will be fixed in the develop.
But as for now your PR can be merged.
