### PR TITLE
[BUG #1991] Make sure provided eth address is valid

### LINKED ISSUE #1991: Wallet: implement validation for scanned QR code and copypasted content in Choose recipient flow
### Description

*Type*: Bug

*Summary*: Need to add validation for scanned QR code and copy pasted content when selecting recipient on Choose Recipient screen

#### Expected behavior
- choose recipient -> scan QR code with opened qr scanner -> popup should be shown for all scnned content except valid account address
- choose recipient -> use address from clipboard ->popup should be shown for all previously copied content except valid account address

In both above listed cases recipient field should not be populated with incorrect content until user scans/copies valid account address

### Additional Information
* Status version: 0.9.10-159-g4b6f920e+ (1716)
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by jeluard**
fix for #1991

### Summary:
Properly handle incorrect recipient address

### Steps to test:
- Open Status
- Navigate wallet / send screen
- Provide an incorrect recipient either from clipboard or qr-code
- Validtae a popup appears and no recipient is set

status: ready

### CODE REVIEW

**Review by x-goose-x — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 1]
```diff
@@ -37,22 +37,25 @@
...
+        valid-address? (update-address-and-name address name)
+        (not valid-address?) (assoc :show-error (i18n/label :t/wallet-invalid-address))))))
 
 (handlers/register-handler-fx
   :wallet-open-send-transaction
-  (fn [{db :db} [_ address name]]
-    {:db         (choose-address-and-name db address name)
-     :dispatch-n [[:navigate-back]
-                  [:navigate-back]]}))
+  (fn [all [_ address name]]
```
Comment (yenda) [inline src/status_im/ui/screens/wallet/send/events.cljs]: it's `cofx` to keep re-frame linguo but what does this change bring ? I find it clearer to have a litteral map over a constructed map

Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/events.cljs]: It allows to reuse `update-address-and-name` here and above.

Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/events.cljs]: Changed to `cofx`

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 2]
```diff
@@ -37,22 +37,25 @@
 
 ;;;; Handlers
 
-(defn choose-address-and-name [db address name]
-  (update db :wallet/send-transaction assoc :to-address address :to-name name))
+(defn update-address-and-name [all address name]
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/send/events.cljs]: let's use `cofx` here as well?

Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/events.cljs]: Done

**Review by rasom — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/events.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/send/events.cljs]: I don't get it, it was already used in both places, it just changed a literal map into a constructed one

**Comment by yenda** [comment]
I don't get it, it was already used in both places, it just changed a literal map into a constructed one

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 3]
```diff
@@ -37,22 +37,25 @@
...
 (handlers/register-handler-fx
   :choose-recipient
-  (fn [{:keys [db]} [_ address name]]
-    (let [{:keys [view-id]} db]
-      (cond-> {:db (choose-address-and-name db address name)}
-        (= :choose-recipient view-id) (assoc :dispatch [:navigate-back])))))
+  (fn [{{:keys [web3] :as db} :db} [_ address name]]
+    (let [{:keys [view-id]} db
+          valid-address? (.isAddress web3 address)]
+      (cond-> {:db db}
```
Comment (yenda) [inline src/status_im/ui/screens/wallet/send/events.cljs]: this could be achieved with a let binding for new-db without the need to return a constructed map

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 4]
```diff
@@ -37,22 +37,25 @@
...
+        (not valid-address?) (assoc :show-error (i18n/label :t/wallet-invalid-address))))))
 
 (handlers/register-handler-fx
   :wallet-open-send-transaction
-  (fn [{db :db} [_ address name]]
-    {:db         (choose-address-and-name db address name)
-     :dispatch-n [[:navigate-back]
-                  [:navigate-back]]}))
+  (fn [cofx [_ address name]]
+    (assoc (update-address-and-name cofx address name)
```
Comment (yenda) [inline src/status_im/ui/screens/wallet/send/events.cljs]: leaving this as it was

**Review by yenda — CHANGES_REQUESTED** [review]

**Comment by asemiankevich** [comment]
https://github.com/status-im/status-react/issues/2035 is logged to make a decision for error handling

**Review by yenda — APPROVED** [review]
