### PR TITLE
[Fix] QR scanner scanning QR when user moved to next screen

### LINKED ISSUE #15970: [IOS] Continuous QR code scanning even after "Oops something wrong" page is displayed
follow up of https://github.com/status-im/status-mobile/pull/15658

### Steps to reproduce:
1. Point the camera at an invalid QR code. (In this case, use the sync code that has been used before)
2. Do not tap the "Try again" button and keep the camera pointed at the QR code when the "Oops something wrong" page is displayed.

### Actual result:
The IOS device continues to scan the QR code.

(on the current record I don't tap 'Try again' button till to 12th second)

https://github.com/status-im/status-mobile/assets/52490791/f51d55fd-8fde-4113-b44a-bd6be1cfcb38

### Expected result:
The IOS device should stop scanning the QR code until the "Try again" button is tapped.

### Device:
- iPhone 11 Pro Max, iOS 16

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15970

### Summary

This PR fixes the QR scanner that scans the QR code when the user is moved to the next screen (`:syncing-progress`). 

The bug was caused when due to the navigational stack. The "QR scanner" screen will be behind the "Syncing devices" screen, and the QR scanner reset after 3 seconds to scan/process any QR code. The fix was to ensure the scanner scan/process the data only when the user is on the "QR scanner" screen.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to `Sign in`
- Enable access to the camera
- Point the camera at an invalid QR code. (for instance, a QR code that has been used before)
- Check if the user gets redirected again to the `Something went wrong` screen more than once.

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 1]
```diff
@@ -201,19 +202,21 @@
...
-                                                   (reset! read-qr-once? false))
-                                                 3000)
-                                  (check-qr-code-data data)))
-            scan-qr-code-tab? (= @active-tab 1)
-            show-camera?      (and scan-qr-code-tab? @camera-permission-granted?)
-            show-holes?       (and show-camera?
-                                   (boolean (not-empty @qr-view-finder)))]
+      (let [camera-ref                       (atom nil)
+            read-qr-once?                    (atom false)
+            user-in-syncing-progress-screen? (= view-id :syncing-progress)
```
Comment (flexsurfer) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: i believe is the proper solution to close qr screen. why is it active?

**Review by flexsurfer — CHANGES_REQUESTED** [review]

**Comment by smohamedjavid** [comment]
> i believe is the proper solution to close qr screen. why is it active?

@flexsurfer 

This is due to the navigational structure of the stack navigation.

Let's say we have screens A, B, C,...etc.

On stack navigation, when the user moves from `A -> B`, the screen `B` is added to the top of the stack (which is visible to the user). When the user navigates back, the screen B is popped from the stack. The previous screen (`A`) is visible to the user.

That's why the camera on the previous screen is active. Once the syncing is completed successfully, we reset the whole stack with `:init-root`. That's where the screen so far the user has been destroyed.

When the QR scans any sync code, it moves to `:syncing-progress` screen. Here, the syncing can be successful or not. In case of not successful, we should allow the user to go back.

To prevent the QR scanner to process any further data. I believe checking the `view-id` would be the best solution.

**Review by flexsurfer — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid . Thank you for PR. 
The issue is still reproducible
## ISSUE 1: Continuous QR code scanning even after "Oops something wrong" page is displayed

### Steps to reproduce:
1. Point the camera at an invalid QR code. (In this case, use the sync code that has been used before)
2. Do not tap the "Try again" button and keep the camera pointed at the QR code when the "Oops something wrong" page is displayed.

### Actual result:
The IOS device continues to scan the QR code.

(I don't tap 'try again' button on the record)

https://github.com/status-im/status-mobile/assets/52490791/b179f802-503e-4467-8b15-d27fcc571b7d



### Expected result:
The IOS device should stop scanning the QR code until the "Try again" button is tapped.

### Device:
- iPhone 11 Pro Max, iOS 16

**Comment by smohamedjavid** [comment]
@VladimrLitvinenko - Kindly retest.

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid Thank you for the fixes. PR is ready to be merged
