### PR TITLE
fix: App gets stuck on syncing process screen when scanning QR code v…

### LINKED ISSUE #18113: App gets stuck on syncing process screen when scanning  QR code via recovered profile with different passwords
### Preconditions:
- `User A` is recovered on both `Device 1` and `Device 2 `devices
- During onboarding both users create different passwords

### Steps:
`Device 1` on the generates sync QR
`Device 2`  goes to "Syncing" -> [+] button -> tap 'Scan or enter sync code code' -> scan the QR code

### Actual result:
Upon scanning the QR code via a recovered profile with different passwords, the app gets stuck in the syncing devices process

https://github.com/status-im/status-mobile/assets/52490791/a8e4c1b9-7505-4d65-ad91-082f4bcc83db

### Expected result:
The devices should be synced. However the passwords should not be synced in such case.

Example:
 **Given** `UserA` is restored ion `Device 1` with the password "12345"
    **And** `UserA` is restored on `Device 2` with the password "99999999999"
    **When** `UserA` syncs `Device 2` with `Device 1`
    **Then** the devices should be synchronized
    But the passwords for `UserA` on `Device 1` ("12345") and `Device 2` ("99999999999") should not be synchronized

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13600847/Status-debug-logs.1.zip)

### ENV:
- Nightly 7 Dec 2023

### PR DESCRIPTION
**Pull request by qfrank**
fixes #18113 

This PR caches the SHA3 password from login, enabling the syncing feature to use it.

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/profile/login/events.cljs [hunk 1]
```diff
@@ -49,6 +52,10 @@
   {:events [:profile.login/local-paired-user]}
   [{:keys [db]}]
   (let [{:keys [key-uid password]} (get-in db [:syncing :profile])
+        login-sha3-password        (get-in db [:syncing :login-sha3-password])
+        password                   (if-not (nil? login-sha3-password) ;; already login
```
Comment (alwx) [inline src/status_im2/contexts/profile/login/events.cljs]: I don't get the comment, you meant something like "already logged in"?

**Review by alwx — APPROVED** [review]

File: src/status_im2/contexts/profile/login/events.cljs (hunk 1 above)
Comment (qfrank) [reply src/status_im2/contexts/profile/login/events.cljs]: sorry for the confusion, i'll update it to "already logged in"

**Review by smohamedjavid — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank thank you for the fix. Overall looks good to me besides one issue. 

### ISSUE 1 Random crashes occur during manual logout

@qfrank this one might be not PR related. It is difficult to check if it exists in develop cause there are no clear steps of how to reproduce. Last time I have reproduced it following below steps in PR. Maybe something will be clear based on attached logs. 


**Steps:** 

1. Recover User A on Device 1 and Device 2. Set different passwords and Enable biometrics for both devices during recovery (not sure if it is important step)
2. Sync Devices
3. Change profile picture on Device 1, add some community on Device 2 (also not sure if this step is important)
4. Perform manual logout on devices
5. See if app has not crashed on logout

**Actual result:** sometimes (both IOS and Android) crash on manual logout. 

[logcat_151223.log.zip](https://github.com/status-im/status-mobile/files/13685497/logcat_151223.log.zip)

[Status-debug-logs (90).zip](https://github.com/status-im/status-mobile/files/13685499/Status-debug-logs.90.zip)

https://github.com/status-im/status-mobile/assets/97245802/fef2f67f-90fa-42df-98c4-b92ba5890ffb

**Comment by qfrank** [comment]
thank you @pavloburykh good catching! it's not related to my PR, the cause is relate to waku.go, i can fix it in a separate PR when i'm back or maybe someone else can pick it up. cc @cammellos 

```
12-15 14:53:58.687 14067     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
12-15 14:53:58.687 14067     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x77715d63c0]
12-15 14:53:58.687 14067     0 E Go      : 
12-15 14:53:58.687 14067     0 E Go      : goroutine 455 [running]:
12-15 14:53:58.687 14067     0 E Go      : github.com/status-im/status-go/wakuv2.(*Waku).broadcast(0x40001c0f00)
12-15 14:53:58.687 14067     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:1060 +0x40
12-15 14:53:58.687 14067     0 E Go      : created by github.com/status-im/status-go/wakuv2.(*Waku).Start
12-15 14:53:58.687 14067     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:1270 +0x7c4
```

**Comment by cammellos** [comment]
maybe @vitvly could you have a look please? I take  @richard-ramos is pretty busy these days :)

**Comment by pavloburykh** [comment]
@qfrank @cammellos I guess it is not super urgent. I will log this issue and someone can have a look once have capacity for it.

**Comment by vitvly** [comment]
@pavloburykh @cammellos yes sure, i'll check and fix.

**Comment by pavloburykh** [comment]
> @pavloburykh @cammellos yes sure, i'll check and fix.

Thank you @vitvly! I have created a separate issue for that https://github.com/status-im/status-mobile/issues/18202

**Comment by pavloburykh** [comment]
@qfrank no other issues from my side. Failed e2e are related to data delivery issue. Ready for merge. Thank you!
