### PR TITLE
Quo2: fix reaction styles

### LINKED ISSUE #16907: Emojis boxes is bigger than in design - comment here
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=4744%3A458642&mode=dev

The emoji reaction box is bigger than in the designs, also the `+` button should be of a different size, while for now they are all of the same size.

### PR DESCRIPTION
**Pull request by clauxx**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #16907 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Based on the following feedback [comment](https://github.com/status-im/status-mobile/issues/16867#issuecomment-1668238295), the size of the reaction and add-reaction components were off from the designs. Additionally, fixed the  colors based on the Design System [component](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=12375-140482&mode=design&t=yCB1iamzGDM7IP5j-4).

### Testing notes

1. Noticed that the `Use Case` property from the Design System is not included in the component. Could be added as a follow up issue.
2. Additional to the sizes, fixed the background/border colors as they were different from the designs

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Check the component in the `Preview` menu

status: ready

### CODE REVIEW

File: src/quo2/components/reactions/reaction.cljs [hunk 1]
```diff
@@ -12,31 +12,32 @@
   [rn/touchable-opacity
```
Comment (J-Son89) [inline src/quo2/components/reactions/reaction.cljs:12]: Nit: the name space of this component is wrong - it's not to do with your changes but perhaps while you are working on these files you can migrate it to the correct location? 
I.e these should be in .selectors. To match figma and the name should match that of figma.

Comment (J-Son89) [reply src/quo2/components/reactions/reaction.cljs:12]: Additionally these files should only export one component and it seems like this file has two in it, can we adjust that and map with fi hmm a 1-1 as we have in the rest of our components? Makes things easier to maintain and to understand what we have in place etc 🙂

File: src/status_im2/contexts/quo_preview/reactions/react.cljs [hunk 2]
```diff
@@ -27,11 +27,14 @@
...
-         {:padding-vertical 60
-          :justify-content  :center
+         {:width            100
+          :padding-vertical 60
+          :justify-content  :space-evenly
           :flex-direction   :row
           :align-items      :center}
-         [quo2.reaction/reaction @state]
-         [quo2.reaction/add-reaction @state]]]])))
+         [quo/reaction @state]
```
Comment (J-Son89) [inline src/status_im2/contexts/quo_preview/reactions/react.cljs:39]: Same for these preview screens, we should only have one design system component per preview screen- could you fix this here or as a follow up? 🙏

Comment (clauxx) [reply src/status_im2/contexts/quo_preview/reactions/react.cljs:39]: was thinking the same. I think as a follow-up might be better, cause the component also seems incomplete (is missing a prop from the DS)

Comment (J-Son89) [reply src/status_im2/contexts/quo_preview/reactions/react.cljs:39]: Sounds great, maybe we can some simple unit tests in that too and align some other best practices :)

**Review by J-Son89 — APPROVED** [review]

**Comment by pavloburykh** [comment]
Ready for design review cc @Francesca-G

**Review by Francesca-G — APPROVED** [review]
The component looks good when tested in a chat, reacting to a message but when I open it from the Quo2 Preview -> selectors -> select-reactions it looks different:

IMG_0670

is this supposed to happen? 
(Also, once I opened it I had to close the application, because there was no back button in the preview).

Moreover, we should discuss with Pedro and the rest of the team about a solution for the emoji library. We're supposed to use twemoji, so the component is correct, but since we're using system emoji for the time being we should adapt the component to the system ones, to be consistent. Otherwise we will have reactions with twemoji + system emojis in messages.

@OmarBasem -  this sounds related to recent nav bar changes, do you know if that's all working fine? 
_is this supposed to happen? 
(Also, once I opened it I had to close the application, because there was no back button in the preview)._

with respect to twemoji etc @smohamedjavid has researched this area a lot recently and can probably provide some input on this? 🤨

**Comment by clauxx** [comment]
@Francesca-G Sorry, didn't add the exact location in the preview. The component was originally located in the wrong place (under `reactions` instead of `selectors`) and will fix that in a follow-up. Also the component is missing the `Use Case` property, so might as well add it in the follow-up as well. What do you think?

**Comment by Francesca-G** [comment]
@clauxx sure, adding the follow up required tag

**Comment by smohamedjavid** [comment]
> is this supposed to happen? (Also, once I opened it I had to close the application, because there was no back button in the preview).

We need to update the preview screen for reactions (`status-im2.contexts.quo-preview.selectors.reactions` ns) to use the new `preview-container` component which has the navigation bar. Apologies for that. Gesture navigation (back) would work on Quo2 previews.

> with respect to twemoji etc @smohamedjavid has researched this area a lot recently and can probably provide some input on this? 🤨

@Francesca-G - The team decided to defer Twemoji integration in the mobile. It will be implemented post-MVP. We will be using the default emojis from the OS (Android or iOS) until then.

**Comment by Francesca-G** [comment]
> @Francesca-G - The team decided to defer Twemoji integration in the mobile. It will be implemented post-MVP. We will be using the default emojis from the OS (Android or iOS) until then.

Ok good, so we should adapt the react component so that it aligns with the default emojis and we have a consistent style throughout :)

**Comment by smohamedjavid** [comment]
> > @Francesca-G - The team decided to defer Twemoji integration in the mobile. It will be implemented post-MVP. We will be using the default emojis from the OS (Android or iOS) until then.
> 
> Ok good, so we should adapt the react component so that it aligns with the default emojis and we have a consistent style throughout :)

I believe the Twemoji (and default emojis) is not applicable to the reactions as the reaction emojis are unique and limited to 6. These emojis are the same as the desktop despite the desktop uses Twemoji.
https://www.figma.com/file/qLLuMLfpGxK9OfpIavwsmK/Iconset?type=design&node-id=942%3A218&mode=design&t=POPE62tL4H0Dd0YU-1

**Comment by Francesca-G** [comment]
@smohamedjavid as mentioned by Pedro, ideally the reaction emojis should be the same as what the user can send in messages, so we should adapt this component to OS emojis. Is that possible?

**Comment by smohamedjavid** [comment]
> @smohamedjavid as mentioned by Pedro, ideally the reaction emojis should be the same as what the user can send in messages, so we should adapt this component to OS emojis. Is that possible?

It's possible. We need to remove the existing custom reaction images/emojis and add the equivalent default OS emoji for the reaction.

BTW this is a completely new change and requires separate testing effort. We will need a separate issue to track it.

cc: @flexsurfer

**Comment by clauxx** [comment]
@cammellos @J-Son89 can you please merge it? I'm not authorized 😢

**Comment by OmarBasem** [comment]
> this sounds related to recent nav bar changes, do you know if that's all working fine?
is this supposed to happen?

The file `status-im2.contexts.quo-preview.selectors.reactions` seems got missed in the migrations. It needs to be wrapped with the new preview container.

**Comment by clauxx** [comment]
> > this sounds related to recent nav bar changes, do you know if that's all working fine?
> > is this supposed to happen?
> 
> The file `status-im2.contexts.quo-preview.selectors.reactions` seems got missed in the migrations. It needs to be wrapped with the new preview container.

Can take care of that in the [follow-up](https://github.com/status-im/status-mobile/issues/17245) issue
