### PR TITLE
Fix `reagent.config/kv-conf` extracting `name` from non-named props

### LINKED ISSUE #22335: "Doesn't support name: 1" error after select asset on Send flow
# Bug Report

### Reproduction

1. Login to app
2. Tap `Send` on `Wallet Home` screen 
3. Choose `From` and `To`
4. Choose asset

#### Actual behavior

"Doesn't support name: 1" error.

Image

https://github.com/user-attachments/assets/20dc9491-e6cd-4efc-b025-083dcf5fd1b2

[error_send.zip](https://github.com/user-attachments/files/19342210/error_send.zip)

Potential reason could be https://github.com/status-im/status-mobile/pull/22298

#### Expected behavior

Asset has chosen successfully and user is redirected to the next screen.
### Additional Information

- Status version: nightly 19/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #22335

## Summary
This PR fixes the implementation to convert prop keys recently added in 
- https://github.com/status-im/status-mobile/pull/22298

## What happened?

In short, we are passing numbers as props to a React component (not a reagent one!). Since numbers aren't a valid React prop name, I built the impl of `reagent.config/kv-conv` with that assumption. Now it's fixed by allowing numbers as prop names.

### Explanation (if you are interested)

There were three major issues:

1. :bug:  I used the function `name` in `kv-conv`, and a number was passed as prop name (1) so it threw the exception trying to do `(name 1)`, In case you didn't know:

   ```js
   <Component 123="Hello" /> // ❌ This is invalid JSX
   ```
   
2. :bug:  Why did the app crash? - you may wonder

    It crashed because **a component in the background was re-rendered**, yes, it's very strange (why do we want to re-render a component that is not shown to the user?). 
    
    When the component is shown it has valid props, then we navigate and 3 screens later, the component re-renders with invalid props. Here's a video showing the data passed to a `flat-list` in its `render-data` prop, I change the bg color so it's easier to see what's the component.
    
    https://github.com/user-attachments/assets/f55c8518-7087-4929-9143-8ba3998d2202

   The namespace is `status-im.contexts.wallet.send.from.view`. I'm not sure what's the intended flow, but `render-data` has `token` as `nil` the first time and then it's populated, internally it's only used to ask `(nil? token)`, so instead of passing all the token data, we could use `some?` or `nil?` to get a boolean. 
   cc: @status-im/wallet-mobile-devs 
   ```clojure
   :render-data {:general-flow?   general-flow?
                 :collectible-tx? collectible-tx?
                 :collectible     collectible
                 :token           token} ;; `nil` when showed to the user, 3 screens later, a map with balances
   ```

3. :bug:  **Wait, but `flat-list` is a reagent component (wrapping RN FlatList), why is it crashing?**

    Yes, it shouldn't break, only React components are passed through `kv-conv`, the issue here is that `:render-data` isn't listed as a custom prop of our wrapper `react-native.flat-list`:
    ```clojure
    (defn dissoc-custom-props
      [props]
      (dissoc props :data :header :footer :empty-component :separator :render-fn :key-fn :on-drag-end-fn))
    ```
     it was missing, in this PR it has also been added, `:render-data` should never reach the original React Native's FlatList.

## Testing notes

The issue is no longer reproducible, but it'd be great that you give a navigation and usage through the app, everything should work as before.

status: ready

### CODE REVIEW

File: src/react_native/flat_list.cljs [hunk 1]
```diff
@@ -25,7 +25,16 @@
...
+  (dissoc props
+   :data
+   :header
+   :footer
+   :empty-component
+   :separator
+   :render-fn
+   :key-fn
+   :on-drag-end-fn
+   :render-data))
```
Comment (ulisesmac) [inline src/react_native/flat_list.cljs:37]: `:render-data` added :eyes:

File: src/reagent/config.cljs [hunk 2]
```diff
@@ -12,10 +12,11 @@
 (defn kv-conv
   [convert-in-vectors?]
   (fn [o k v]
-    (let [recursively-convert-in-vectors? (or convert-in-vectors?
-                                              (.hasOwnProperty *keys-to-convert* (name k)))]
```
Comment (ulisesmac) [inline src/reagent/config.cljs:16]: Avoids using `name` on `k`

**Review by ilmotta — APPROVED** [review]
Very helpful PR description @ulisesmac, thank you for promptly fixing the problem. Worth adding the label `request-manual-qa` just in case.

**Review by mohsen-ghafouri — APPROVED** [review]
Thanks for detailed explanations.

**Review by alwx — APPROVED** [review]

**Review by clauxx — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for PR. PR is ready to be merged. Tested flows:
- Sending Collectibles, Swap, Assets, Bridge using long tap on Wallet Main Page
- Sending Collectibles, Swap, Assets, Bridge  using 'Send', 'bridge', 'swap' Buttons from Wallet Main page
- Sending Collectibles, Swap, Assets, Bridge  using long tap an Opened Account
- Sending Collectibles, Swap, Assets, Bridge using 'Send', 'bridge', 'swap' Button in an Opened Account
- Sending Collectibles, Assets, from Universal QR Code
