### PR TITLE
[#16254] Add new system messages in chat history when accepting a con…

### LINKED ISSUE #16254: Add new system messages in chat history when accepting a contact request
# Bug Report

## UPDATE

For now, we only should show the `[Alicia] is now a contact` message both for sender and receiver of CR after the CR approval. 

Design: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1694%3A380446&t=53g6tG6gOO7nUzqh-1

Screenshot 2023-06-13 at 12 56 52

Additional requirement:

> Contact request card and "You sent a contact request to..." message should not appear in the conversation, only in notification center, so we can hide/delete from here

---
Three scenarios where new systems messages are needed:

#### 1. Alice sends CR to Bob for the first time

1. Bob receives a notification in AC
2. 1-1 chat is NOT opened for both users
3. Bob accepts CR
4. 1-1 chat is created for Bob and Alice
5. Alice can see her message sent with CR and the system message “Bob now is a contact”
6. Bob can see Alice’s message received with CR and 

#### 2. Bob removes Alice from contacts 

1. The input field is disabled in the chat for Bob and Alice
2. Alice can see “Add Bob as a contact to send message” in place of the input field (this will be a clickable button) and the system message “Bob removed you as a contact”
3. Bob can see “Add Alice as a contact to send message” in place of the input field (this will be a clickable button) and the system message “Alice removed as a contact”

#### 3. Alice sends another CR to Bob

1. Bob receives a notification in AC
2. 1-1 chat is opened for both users BEFORE the CR is accepted
3. Bob can open chat and accept/reject CR inside the chat (there will be corresponding buttons)
4. Bob can see the system message “Alice sent you a contact request” and the message received with CR from Alice below it
5. Alice can see the system message “You sent a contact request to Bob” and the message sent with CR to Bob below it

### Designs

Sender side
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8364%3A515046&t=867Xk6LqWfKYzLK9-1

Receiver side
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8364%3A600326&t=867Xk6LqWfKYzLK9-1

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #16254

### CODE REVIEW

File: src/quo2/components/messages/system_message.cljs [hunk 1]
```diff
@@ -83,51 +75,48 @@
...
-  [{:keys [state pinned-by child timestamp-str labels]}]
+  [{:keys [state pinned-by child]}]
   [rn/view
    {:flex-direction :row
     :flex           1
     :align-items    :center}
    [sm-icon
-    {:icon    :main-icons/pin
+    {:icon    :i/pin
      :color   :primary
```
Comment (J-Son89) [inline src/quo2/components/messages/system_message.cljs]: I think this use of primary color is wrong - it should be based on `customization-color`

File: src/quo2/components/messages/system_message.cljs [hunk 2]
```diff
@@ -31,15 +31,6 @@
           ((theme/get-theme) themes)
```
Comment (J-Son89) [inline src/quo2/components/messages/system_message.cljs]: it would be great if we could update this component to current best practices while here, e.g use new theming approach, style and view namespaces etc 👍

File: src/quo2/components/messages/system_message.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/quo2/components/messages/system_message.cljs]: could you elaborate?

File: src/quo2/components/messages/system_message.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/quo2/components/messages/system_message.cljs]: do we have documentation on how to do that?

File: src/quo2/components/messages/system_message.cljs (hunk 1 above)
Comment (J-Son89) [reply src/quo2/components/messages/system_message.cljs]: in the designs the color here is based upon users color (or probably chat color too for groups etc)
Screenshot 2023-07-26 at 15 03 32

so probably this should be 
```
:color (colors/theme-color 
(colors/custom-color customization-color 50 5)
(colors/custom-color customization-color 60 5)
theme
```
where customization-color is a prop passed in

File: src/quo2/components/messages/system_message.cljs (hunk 2 above)
Comment (J-Son89) [reply src/quo2/components/messages/system_message.cljs]: for the new theming or which part?

for the new theming the simplest way is to wrap the outer component in with-theme HOC and it will pass theme to the first param if it's a map (it should be as a react convention) then you can use that in the component - value of theme is really being passed down from a react context provider
e.g:
```
(:require [quo2.theme :as quo.theme])
...

(defn- view-internal [{:keys [theme]}]
...
 [rn/view {:style {
    :background-color (colors/theme-color colors/white colors/neutral-100 theme)
 }}])

(def view (quo.theme/with-theme view-internal))
```
cc @smohamedjavid in case I missed anything

File: src/quo2/components/messages/system_message.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/quo2/components/messages/system_message.cljs:117]: it's handled in `icon-avatar` component

File: src/quo2/components/messages/system_message.cljs [hunk 3]
```diff
@@ -4,41 +4,13 @@
...
-            [react-native.reanimated :as reanimated]))
-
-(def themes-landed
-  {:pinned  colors/primary-50-opa-5
-   :added   colors/primary-50-opa-5
-   :deleted colors/danger-50-opa-5})
+            [utils.i18n :as i18n]
+            [quo2.theme :as quo.theme]))
 
 (def themes
```
Comment (J-Son89) [inline src/quo2/components/messages/system_message.cljs]: maybe "text-color" is a better name here?
also consider doing 
```
(defn text-color [theme]
  (colors/theme-colors colors/neutral-100 colors/white theme))
 ```
 as this is how we are mostly using this across the codebase now

File: src/quo2/components/messages/system_message.cljs [hunk 4]
```diff
@@ -82,52 +52,53 @@
...
   [rn/view
    {:align-items    :center
     :flex-direction :row}
    [sm-icon
-    {:icon    :main-icons/add-user
-     :color   :primary
-     :opacity (if (= state :landed) 0 5)}]
-   [sm-user-avatar (:image (first mentions))]
+    {:icon    :i/add-user
+     :color   (or customization-color :primary)
```
Comment (J-Son89) [inline src/quo2/components/messages/system_message.cljs]: 👍

File: src/quo2/core.cljs [hunk 5]
```diff
@@ -213,6 +212,12 @@
 (def markdown-list quo2.components.markdown.list.view/view)
 (def text quo2.components.markdown.text/text)
 
+;;;; MESSAGES
+(def system-message-added quo2.components.messages.system-message/system-message-added)
```
Comment (J-Son89) [inline src/quo2/core.cljs]: oh please let's avoid these types of exports from quo2.core. This should be handled by the component. 
It is much easier to configure the components correctly if we just align them with Figma properties and naming conventions.
In the Figma designs there is only one component so let's only export one - this way devs do not need to figure out which one to use - it is already matching figma 

Here is it is better that we have one component and separate this with a `type` prop as it is done in Figma
Screenshot 2023-07-27 at 11 35 26

For example we can differentiate this by `type` like this
"system-message-added quo2.components.messages.system-message/view.cljs"
```
(:require
 [quo2.components.messages.system-message :as system-message-removed]
 [quo2.components.messages.system-message-pinned :as system-message-pinned]
 [quo2.components.messages.system-message-deleted :as system-message-deleted]
 [quo2.components.messages.system-message :as system-message-added])

(defn view [{:keys [type] :as props}]
  (case type
    :added-short <type needed here>
    :added-long <type needed here>
    :contact-request <type needed here>
    :pinned-text  [system-message-pinned props]
    :deleted [system-message-deleted props]
    :deleted-and-action <type needed here>
    :pinned-gifs <type needed here>
    :pinned-photos <type needed here>))
```

cc @erikseppanen @ilmotta @OmarBasem @smohamedjavid

Comment (flexsurfer) [reply src/quo2/core.cljs]: actually, it was implemented with types, but it's kinda weird, because they are completely different components, and just hiding case inside component is kinda weird, but if we have a consensus I'm fine to change this

Comment (J-Son89) [reply src/quo2/core.cljs]: yeah I agree that it is weird and sometimes leading to less "smart" code, but it is much easier to see that a component is configured correctly on the screen if we follow this approach.

For example looking at the Page Nav component being used on the communities page - 



if the page nav component was created correctly we could then look at the code and easily see that the configuration is correct - however if “random” names for the component props were used we then would have to manually check how to get the components to match up with the designs when using them - this then leads to lots of misuses of the design system components 

There are also a tonne of our components which are not properly encapsulating styles, colors etc and have too broad an api, hopefully this approach can help to reduce that too as we align better with what is in the Design System.

Comment (flexsurfer) [reply src/quo2/core.cljs]: in my experience its useless, our goal as developers to make code as simple and clean as possible, it should be convenient for developers, we don't care about figma, when I want to use a component I just look at the implementation in the code, not in figma, imho
regarding figma, we already tried but it didn't work, designers change a lot, and there is no consistency in naming, some designers name some do not, etc etc, so idea is good but it won't work, imho

Comment (flexsurfer) [reply src/quo2/core.cljs]: actually in most cases "components" is used only once, so they are not really components, they won't be used or changed in time, so we should keep ourselves calm here and don't overthink this much :)

Comment (J-Son89) [reply src/quo2/core.cljs]: I would have to disagree on this. I've been refactoring a lot of components lately and the amount of misuses of components/code is mind blowing. So many components are just using overrides for color and text etc when they should be encapsulated and achieved with some configuration - imo we for the most part have not been using the design system properly as of yet.

As the project and team grows these problems will only grow further and it will become a mess to deal with.

Sure in some cases it might be a burden, however imo the likelihood of other devs using the design system correctly increases the more components aligned with this approach.

It is true that the designers can change the components but that is really a separate issue and a process that definitely needs improvement 👍

Comment (flexsurfer) [reply src/quo2/core.cljs]: probably for some components type can be used, but here it's useless

Comment (flexsurfer) [reply src/quo2/core.cljs]: > I've been refactoring a lot of components lately and the amount of misuses of components/code is mind blowing. 

i don't think the reason is in figma props naming :)

Comment (ilmotta) [reply src/quo2/core.cljs]: @flexsurfer, there was a retrospective recently where the entire team had the chance to discuss these points and it was decided that we'll try to match much more strictly what's in the DS. Edit: Maybe you weren't in the meeting and we failed to communicate this decision.

The guideline **for quo2 code** would be (is) as simple as it gets:

> Adhere to the properties and structure of the Figma component to establish the Quo2 component's folder organization, filename, and customizable properties that impact its variations.

There's no "if" or exceptions. Even for a team of our size I think it makes for an easy to follow convention. It simplifies designer's reviews and code reviews. There's no funny business, just straight out boring code.

As @J-Son89 said, it's indeed mind-blowing the amount of bugs in quo2. The hypothesis we want to verify is that this guideline will ensure we drift less from the true source of truth of the Design System, which is Figma, not the code.

If you think we should re-evaluate this decision as a team, I think it'll be more more inclusive and productive to have it outside this PR, because there are other people that could participate more easily.

-----

For an example of a component that was recently rewritten with this guideline in mind, take a look at `quo2.components.list-items.community.view` in https://github.com/status-im/status-mobile/pull/16527. The designer gave positive feedback about how easy it was to review it in the preview area when all the variations could be easily checked because all names matched. That's one of the basic points of having a DS. As a developer, I felt the same, I could more easily verify the 20+ variations in the code. And I guess reviewers could also more easily double-check things.

Comment (flexsurfer) [reply src/quo2/core.cljs]: thanks for the detailed explanation, somehow I didn't participate in that discussion

Comment (ilmotta) [reply src/quo2/core.cljs]: Sorry @flexsurfer, I take as feedback to me as well that we should make sure decisions are not lost in the myriad of topics discussed in retros and should be communicated again in Discord, for example, so if someone was in time-off or couldn't participate, we give them a chance to also share their opinion.

As usual with new guidelines, let's give it a chance for a little while. It seems like a good direction for many of us, but we can all be wrong.

File: src/quo2/components/drawers/permission_context/style.cljs [hunk 6]
```diff
@@ -2,7 +2,9 @@
   (:require [quo2.foundations.colors :as colors]))
 
 (def radius 20)
-(def container
+
+(defn container
+  []
```
Comment (J-Son89) [inline src/quo2/components/drawers/permission_context/style.cljs:8]: we should pass theme here 
```
  [theme]
  {:flex-direction          :row
   :background-color        (colors/theme-colors colors/white colors/neutral-90 theme)
   ```

File: src/quo2/components/drawers/permission_context/view.cljs [hunk 7]
```diff
@@ -8,5 +8,5 @@
   [rn/touchable-highlight
    {:on-press       on-press
     :underlay-color (colors/theme-colors :transparent colors/neutral-95-opa-70)
```
Comment (J-Son89) [inline src/quo2/components/drawers/permission_context/view.cljs]: same here `(colors/theme-colors :transparent colors/neutral-95-opa-70 theme)`

File: src/quo2/components/messages/system_message.cljs [hunk 8]
```diff
@@ -136,40 +107,19 @@
...
-                              :background-color   sv-color}
-                             style))}
-     [system-message-content message labels]]))
+(def system-message-pinned (quo.theme/with-theme system-message-pinned-internal))
 
 (defn system-message
-  [message]
-  [:f> f-system-message message])
+  [{:keys [type] :as data}]
+  (case type
```
Comment (J-Son89) [inline src/quo2/components/messages/system_message.cljs]: I think we need to default case with `nil` right @ilmotta ? 🤔

**Review by J-Son89 — APPROVED** [review]
Looks good @flexsurfer, left one or two points which would be nice to check.

Thanks for making the changes, I realise now that perhaps you were away when some of this discussion was happening. As @ilmotta said, we can try this approach to see how it improves over the next while and if there are better alternatives then we can always update the approach - at the very least it seems to be making devs more aware of how to properly interact with Figma 👍

File: src/quo2/components/messages/system_message.cljs (hunk 8 above)
Comment (ilmotta) [reply src/quo2/components/messages/system_message.cljs]: We should, the app crashes and the user sees a white screen of death when no condition matches. It's not worth IMO risking not adding a `nil` or some other default value.

File: src/quo2/components/drawers/permission_context/style.cljs (hunk 6 above)
Comment (flexsurfer) [reply src/quo2/components/drawers/permission_context/style.cljs:8]: this is not related to this PR, this component should be refactored, so this will be addresses in another PR

File: src/quo2/components/messages/system_message.cljs (hunk 8 above)
Comment (flexsurfer) [reply src/quo2/components/messages/system_message.cljs]: thank you guys, I'm a little bit lost after vacation :)

**Review by smohamedjavid — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the PR! Please take a look at the following issue

### ISSUE 1 New system messages are not displayed in chat preview

**Steps:** 

1. Generate new CR system message 
2. Check if system message is displayed within chat preview (chat list and Jump to card)

**Actual result:** new system messages are not displayed within chat preview. 

https://github.com/status-im/status-mobile/assets/97245802/802c838c-bc28-4519-9e85-e0b695d87c16

photo_2023-07-31 13 16 31
photo_2023-07-31 13 16 34

**Comment by pavloburykh** [comment]
### ISSUE 2 System message about removal is not displayed for user who has removed contact

**Steps:**

1. User A removes User B from contacts
2. See if system message "User B removed as a contact" is displayed for User A

**Actual result:** message is not displayed

**Expected result:** message is displayed

Messages for Mobile – Figma 2023-07-31 14-10-26

**Comment by pavloburykh** [comment]
### ISSUE 3 Incorrect icon for removal contact system messages

**Actual result:**

Currently removal messages have the same icon as add contact system messages 

photo_2023-07-31 14 17 21

**Expected result:** 

According to the design, removal icon should be different

Messages for Mobile – Figma 2023-07-31 13-40-18

**Comment by pavloburykh** [comment]
### ISSUE 4 Message about incoming CR is not displayed in chat for receiver / Wrong text in bottom sheet for CR receiver

**Expected result:** 

Messages for Mobile – Figma 2023-07-31 13-56-55

**Actual result:** no system message about incoming CR. Bottom sheet has wrong text: "Add <user name> as contact to send message" instead of "<username> sent you contact request"

photo_2023-07-31 14 01 26

**Comment by pavloburykh** [comment]
### ISSEUE 5 Extra space between last message and bottom sheet in chat

Potential followup

**Expected result:** 

Messages for Mobile – Figma 2023-07-31 14-11-07

**Actual result:** 

photo_2023-07-31 14 27 46

**Comment by pavloburykh** [comment]
### ISSEUE 6 Jump to button is not displayed in chat until users become contacts

Potential followup

**Expected result:** 

Messages for Mobile – Figma 2023-07-31 14-29-22

**Actual result:** 

photo_2023-07-31 14 31 06

**Comment by pavloburykh** [comment]
### ISSUE 7 Deleted message icon is dispositioned

**Actual result:** 

photo_2023-07-31 15 42 37

**Expected result:** 

screenshot from latest nightly

photo_2023-07-31 15 43 46

**Comment by flexsurfer** [comment]
- [x] ISSUE 1 New system messages are not displayed in chat preview
- [x] ISSUE 2 System message about removal is not displayed for user who has removed contact
- [x] ISSUE 3 Incorrect icon for removal contact system messages
- [x] ISSUE 4 Message about incoming CR is not displayed in chat for receiver / Wrong text in bottom sheet for CR receiver
- [x] ISSEUE 5 Extra space between last message and bottom sheet in chat
- [x] ISSEUE 6 Jump to button is not displayed in chat until users become contacts
- [x] ISSUE 7 Deleted message icon is dispositioned

**Comment by flexsurfer** [comment]
thank @pavloburykh all should be fixed now

**Comment by pavloburykh** [comment]
@flexsurfer thank you for the fixes! 

Please take a look at these issues

### [ISSUE 1](https://github.com/status-im/status-mobile/pull/16775#issuecomment-1658082399) New system messages are not displayed in chat preview
is fixed partially. 

chat preview is still not displayed for contact removal messages


https://github.com/status-im/status-mobile/assets/97245802/85a53bdc-991b-40a5-9a49-f407a26ce75c

Also, preview is not displayed within cards in Jump to section

photo_2023-08-03 12 30 46

**Comment by pavloburykh** [comment]
### ISSUE 8 CR system messages do not not generate unread counters in 1-1 chat

Here is discussion with design team https://discord.com/channels/624634427930312714/975775548007678033/1136605269644808304

**Expected result:** unread counters should be generated

**Actual result:** unread counters are not generated

**Comment by pavloburykh** [comment]
Agreed with @flexsurfer to create followup for remained issues: 

1. Missing counters for "you were removed from contact" and "now is contact" system messages
2. Preview is not shown for "you were removed from contact"/"you removed from contact" system messages

@Francesca-G please review the PR form your side. If there will be no additional issues please move to merge column. 

@flexsurfer please, wait for @Francesca-G review before merging. Thank you!

**Review by Francesca-G — COMMENTED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3987%3A67544&mode=design&t=v1JhjszkroixFZv6-1) with the design review :)

**Comment by flexsurfer** [comment]
thanks @pavloburykh @Francesca-G 

- [x] design doesn't have identicon ring
- [x] remove icon not updated
- [x] no icon for drawer button

message that I sent with the contact request didn't appear in the chat, will be addressed later in followup

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the fixes. @Francesca-G could you please re-check?

**Review by Francesca-G — APPROVED** [review]
Here's the [updated review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3987%3A67544&mode=design&t=EldrzNxuhf9ost99-1) :)

**Comment by flexsurfer** [comment]
thanks @Francesca-G , button is standard component, so we can't change the icon size, regarding ring, probably will be addressed here https://github.com/status-im/status-mobile/pull/16193

**Comment by churik** [comment]
@flexsurfer 
did you create an issue follow-up based on the design review?

Based on https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md > Design review, all follow-up issues have to be created when PR is merged and linked to the original PR.

**Comment by flexsurfer** [comment]
> did you create an issue follow-up based on the design review?

no, I did not, according to my comment there were two issues, one is not an issue, and second there was already an issue
