### PR TITLE
Show correct drawer message for pending community request

### LINKED ISSUE #20477: Pending state of community is shown like "Join community to post" from the channel
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
"Pending", so I can't send one more request to join 

(I believe this is the link to figma https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=16118-150665&t=P1oxeCVSjIooqdCl-4 , so it should be "Request to join community pending" and no action is shown when you tap on it)

#### Actual behavior

"Join community to post" and the flow is triggering again on tapping
https://github.com/status-im/status-mobile/assets/4557972/d98b3a75-1563-4429-8298-c001321c5e7b

### Reproduction

1. Create user profile
2. Send a request to join to Status community
3. Open any available channel

### Additional Information

- Status version: nightly 17/06/24
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20477

status: ready

### CODE REVIEW

File: src/status_im/navigation/transitions.cljs [hunk 1]
```diff
@@ -44,15 +44,15 @@
 (def stack-slide-transition
   {:push {:content {:translationX {:from     (:width (rn/get-window))
                                    :to       0
-                                   :duration 200}}}
+                                   :duration 250}}}
```
Comment (Parveshdhull) [inline src/status_im/navigation/transitions.cljs:47]: small change related to https://discord.com/channels/624634427930312714/948957499829149747/1252555238414614589
(change is too small and doesn't seem worth different issue or PR)

**Review by flexsurfer — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @Parveshdhull !

Thanks for your fix. Everything looks good from my side.
Failed e2e are not related and you can merge your PR.
