### PR TITLE
[14677, 14673, 14672, 14671, 14664] Fix bottom sheet dismissal problems

### LINKED ISSUE #14664: Active keyboard does not fold down after opening chat bottom sheets and overlapps them
**Steps:**

1. Open any chat
2. Send a message
3. Make input field active in order to open keyboard
4. Longtap on message to open bottom sheet with message options (reproducible with other chat bottom sheets too, e.g. "pinned messages", images list pop up)
5. Observe the result

**Actual result:** 

Keyboard remains opened and overlaps message options bottom sheet

**Expected result:**

Keyboard folds down after opening message options bottom sheet

https://user-images.githubusercontent.com/97245802/209945284-63a6d31e-f326-4f19-84f5-e9b3796061c4.mp4

https://user-images.githubusercontent.com/97245802/209945301-eeb31475-391b-4aec-80fe-62c258669c6c.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #14677: The removing pop up is too much expanded during chats removing and clearing
**Steps to reproduce:**
1. Create 1-1 chat or group chat
2. Long tap on the current chat
3. Select 'clear history' or 'delete chat' option

**Actual result:**
The pop up is too much expanded
image

**Expected result:**
image

**ENV:** nightly v.1.20.2 (20221230030828)

### PR DESCRIPTION
**Pull request by ibrkhalil**
The PR makes the bottom sheet uses Re-frame's DB instead of local state, This makes it's configuration accessible from any part of the app, And fixes and issues that happens when two bottom sheets are opened after one another, The height doesn't have enough time to get calculated properly .. So we dismiss the older bottom-sheet synchronously and queue the dispatching of the new one to give it a chance to calculate it's content height.

fixes #14677, #14673, #14672, #14671, #14664
status: ready

### CODE REVIEW

**Comment by ibrkhalil** [comment]
Sorry @flexsurfer, These changes rely on each other .. I tried to break them up into different PRs, But couldn't do them all separately

**Comment by flexsurfer** [comment]
[no-contacts-dark@2x.png] is not an icon, its an image, should be required in resources

File: src/status_im2/subs/general.cljs [hunk 1]
```diff
@@ -198,6 +198,22 @@
  (fn [seed]
    (or seed {:step :intro})))
 
+(re-frame/reg-sub
```
Comment (flexsurfer) [inline src/status_im2/subs/general.cljs]: you shouldn't register subscription with the same name , you already have root subscription with this name, only root subscriptions can "read" db, other subscriptions must be based on other subscriptions not on db, and better to move default values to view, btw only animation-delay 450 is usefull, in others you don't need to set them to nil or false

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs [hunk 2]
```diff
@@ -7,7 +7,8 @@
             [status-im.react-native.resources :as resources]
             [status-im2.contexts.communities.menus.request-to-join.style :as style]
             [utils.re-frame :as rf]
-            [utils.requests :as requests]))
+            [utils.requests :as requests]
+            status-im2.common.bottom-sheet.view))
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: you don't need to require it here

File: src/status_im2/contexts/chat/group_details/view.cljs [hunk 3]
```diff
@@ -76,7 +77,7 @@
            deselected-members      (rf/sub [:group-chat/deselected-members])]
        [rn/view {:style {:height (- window-height (:top safe-area))}}
         [rn/touchable-opacity
-         {:on-press            #(rf/dispatch [:bottom-sheet/hide])
+         {:on-press            #(rf/dispatch [:dismiss-bottom-sheet])
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/group_details/view.cljs]: just wondering why don't we keep `:bottom-sheet/hide` ?

File: src/status_im/events.cljs [hunk 4]
```diff
@@ -324,3 +325,57 @@
...
+  {:events [:bottom-sheet/keyboard-was-shown?]}
+  [{:keys [db]} value]
+  {:db (assoc-in db [:bottom-sheet/config :keyboard-was-shown?] value)})
+
+(rf/defn bottom-sheet-did-expand
+  {:events [:bottom-sheet/did-expand]}
+  [{:keys [db]} value]
+  {:db (assoc-in db [:bottom-sheet/config :expanded?] value)})
+
+(rf/defn bottom-sheet-gesture-running?
```
Comment (flexsurfer) [inline src/status_im/events.cljs]: you could have one event like `:bottom-sheet/update-config {:gesture-running? true}`

File: src/status_im/events.cljs [hunk 5]
```diff
@@ -324,3 +325,57 @@
...
+  {:events [:bottom-sheet/reset]}
+  [{:keys [db]}]
+  {:db (assoc db
+              :bottom-sheet/config
+              {:content-height      nil
+               :show-bottom-sheet?  nil
+               :keyboard-was-shown? false
+               :expanded?           false
+               :gesture-running?    false
+               :animation-delay     500})})
```
Comment (flexsurfer) [inline src/status_im/events.cljs]: in some places it's 450 in some 500, we should have it only once in constants

File: src/status_im/events.cljs [hunk 6]
```diff
@@ -324,3 +325,57 @@
...
+
+(re-frame/reg-fx
+ :dismiss-bottom-sheet-fx
+ (fn [[on-cancel animation-delay]]
+   (re-frame/dispatch [:bottom-sheet/show-quo2-bottom-sheet false])
```
Comment (flexsurfer) [inline src/status_im/events.cljs]: what is `show-quo2-bottom-sheet` ?

File: src/status_im/events.cljs [hunk 7]
```diff
@@ -324,3 +325,57 @@
...
+      (re-frame/dispatch [:bottom-sheet/hide-navigation-overlay])
+      (re-frame/dispatch [:bottom-sheet/reset])
+      (when (fn? on-cancel) (on-cancel)))
+    (or animation-delay 450))))
+
+(rf/defn dismiss-bottom-sheet
+  {:events [:dismiss-bottom-sheet]}
+  [{:keys [db]} on-cancel]
+  (let [animation-delay (get-in db [:bottom-sheet/config :animation-delay])]
+    {:dismiss-bottom-sheet-fx [on-cancel animation-delay]}))
```
Comment (flexsurfer) [inline src/status_im/events.cljs]: this doesn't looks correct, we shouldn't dispatch in fx, so you could update show-quo2-bottom-sheet value right here in the db, and use dispatch-later

File: src/status_im2/contexts/chat/group_details/view.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/group_details/view.cljs]: It makes the bottom sheet disappear, Dismiss bottom sheet makes it scroll downwards until it's gone

Comment (flexsurfer) [reply src/status_im2/contexts/chat/group_details/view.cljs]: i mean just event name why don't keep same event name

File: src/status_im/events.cljs (hunk 7 above)
Comment (ibrkhalil) [reply src/status_im/events.cljs]: Done

File: src/status_im/events.cljs (hunk 6 above)
Comment (ibrkhalil) [reply src/status_im/events.cljs]: Bad naming, Fixed

File: src/status_im2/contexts/chat/group_details/view.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/group_details/view.cljs]: Should I use the functionality in `:dismiss-bottom-sheet` in the old event `:bottom-sheet/hide` ?

Comment (flexsurfer) [reply src/status_im2/contexts/chat/group_details/view.cljs]: yes i don't see why not

Comment (flexsurfer) [reply src/status_im2/contexts/chat/group_details/view.cljs]: we have only one version of bottom sheet now

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/group_details/view.cljs]: Understood, Fixing

File: src/status_im2/subs/general.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/subs/general.cljs]: Fixed

File: src/status_im/bottom_sheet/core.cljs [hunk 8]
```diff
@@ -20,7 +20,9 @@
 (rf/defn hide-bottom-sheet
   {:events [:bottom-sheet/hide]}
   [{:keys [db]}]
-  {:db (assoc db :bottom-sheet/show? false)})
+  {:db (-> db
+           (assoc :bottom-sheet/show? false)
```
Comment (flexsurfer) [inline src/status_im/bottom_sheet/core.cljs]: why do we need two flags ?

File: src/status_im/group_chats/core.cljs [hunk 9]
```diff
@@ -208,6 +208,11 @@
   [{:keys [db]} id]
   {:db (update db :group/selected-contacts conj id)})
 
+(rf/defn clear-contacts
+  {:events [:clear-contacts]}
+  [{:keys [db]} id]
```
Comment (flexsurfer) [inline src/status_im/group_chats/core.cljs]: id is redundant

File: src/status_im/bottom_sheet/core.cljs (hunk 8 above)
Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: I wanted to not break the old one, But I think I'll remove the older one cause it does not work with the new bottom-sheet

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: yes we should have only one implementation

File: src/status_im/group_chats/core.cljs (hunk 9 above)
Comment (ibrkhalil) [reply src/status_im/group_chats/core.cljs]: Done

File: src/status_im/bottom_sheet/core.cljs (hunk 8 above)
Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Done

**Comment by flexsurfer** [comment]
btw, as you are doing this could we move it to status-im2 ?

File: src/status_im/chat/models.cljs [hunk 10]
```diff
@@ -453,8 +453,10 @@
     :content             (i18n/label :t/clear-history-confirmation-content)
     :confirm-button-text (i18n/label :t/clear-history-action)
     :on-accept           #(do
```
Comment (flexsurfer) [inline src/status_im/chat/models.cljs]: this one can be simpler, do is redundand and better to use fn for parent function and # inside

```clojure
(fn []
      (rf/dispatch [:bottom-sheet/hide
                              #(re-frame/dispatch [:chat.ui/clear-history chat-id false]))]))}})

File: src/status_im/browser/core.cljs [hunk 11]
```diff
@@ -562,7 +562,7 @@
   [{:keys [db] :as cofx} address]
   (rf/merge cofx
             {:browser/clear-web-data nil}
-            (bottom-sheet/hide-bottom-sheet)
+            (bottom-sheet/hide-bottom-sheet nil)
```
Comment (flexsurfer) [inline src/status_im/browser/core.cljs]: better to make this parameter optional, so we don't need to provide nil

File: src/status_im/bottom_sheet/core.cljs [hunk 12]
```diff
@@ -17,10 +18,32 @@
...
+               :keyboard-was-shown? false
+               :expanded?           false
+               :gesture-running?    false
+               :animation-delay     constants/bottom-sheet-animation-delay})})
+
 (rf/defn hide-bottom-sheet
   {:events [:bottom-sheet/hide]}
-  [{:keys [db]}]
-  {:db (assoc db :bottom-sheet/show? false)})
+  [{:keys [db]} on-cancel]
```
Comment (flexsurfer) [inline src/status_im/bottom_sheet/core.cljs]: you can do it like this [{:keys [db]} & [{:keys [on-cancel]]]

better to have a map with options instead of just one callback

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: I tried this but got an artiy warning

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: mhm so it won't work with defn macro?

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: btw warning is fine when we use it inside fx/merge

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: No, Multi-Arity and Variadic functions are not working with `rf/defn`

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: then we need to find another solution, because providing nil by default won't work well

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: There's a conditional inside :bottom-sheet/hide that checks the type of the callback
But for the sake of DRY, This isn't the best solution ..

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: What solutions do you suggest for passing a callback ?

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Should I make another version of the same event which receives a callback and use it where needed ?
More like a global 'hide-sheet-and-dispatch'

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: yep, sounds good

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Kindly look at how it looks now

File: src/status_im/bottom_sheet/core.cljs [hunk 13]
```diff
@@ -33,16 +33,23 @@
...
+  {:bottom-sheet/hide nil
+   :dispatch-later [{:dispatch [:bottom-sheet/reset on-cancel]
                      :ms       constants/bottom-sheet-animation-delay}]})
 
 (rf/defn hide-bottom-sheet-navigation-overlay
   {:events [:bottom-sheet/hide-navigation-overlay]}
   [{}]
-  {:hide-bottom-sheet nil})
+  {:hide-bottom-sheet-and-dispatch nil})
```
Comment (flexsurfer) [inline src/status_im/bottom_sheet/core.cljs]: is this intentional?

File: src/status_im/bottom_sheet/core.cljs (hunk 12 above)
Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: nice thanks

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: the only thing im not sure why `on-cancel` , it  doesn't look like `on-cancel` from code

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: the naming i mean

Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: it looks more like `on-did-hide` or `on-hide-finished`

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Okay, Will rename it and test it

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Okay, Will rename it and test it

Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Please check

File: src/status_im/bottom_sheet/core.cljs (hunk 13 above)
Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Yes

File: src/status_im/bottom_sheet/core.cljs [hunk 14]
```diff
@@ -20,27 +21,31 @@
 
 (rf/defn reset-bottom-sheet
```
Comment (flexsurfer) [inline src/status_im/bottom_sheet/core.cljs]: could you please move bottom sheet related events to status-im2 ?

File: src/status_im/chat/models.cljs [hunk 15]
```diff
@@ -517,8 +518,9 @@
     :content             (i18n/label :t/delete-chat-confirmation)
     :confirm-button-text (i18n/label :t/delete)
     :on-accept           #(do
```
Comment (flexsurfer) [inline src/status_im/chat/models.cljs]: same here as change above

File: src/status_im/events.cljs [hunk 16]
```diff
@@ -324,3 +324,9 @@
     {::async-storage/get {:keys keys
                           :cb   #(re-frame/dispatch
                                   [:information-box-states-loaded hashes %])}}))
+
+(rf/defn update-bottom-sheet-config
```
Comment (flexsurfer) [inline src/status_im/events.cljs]: this also move in the same place in status-im2

File: src/status_im/bottom_sheet/core.cljs (hunk 14 above)
Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: Okay

File: src/status_im/bottom_sheet/core.cljs (hunk 13 above)
Comment (flexsurfer) [reply src/status_im/bottom_sheet/core.cljs]: could you elaborate then? why not directly just dispatch hide ?  and remove :bottom-sheet/hide-navigation-overlay

File: src/status_im/chat/models.cljs (hunk 15 above)
Comment (ibrkhalil) [reply src/status_im/chat/models.cljs]: Done

File: src/status_im/events.cljs (hunk 16 above)
Comment (ibrkhalil) [reply src/status_im/events.cljs]: Done

File: src/status_im/bottom_sheet/core.cljs (hunk 13 above)
Comment (ibrkhalil) [reply src/status_im/bottom_sheet/core.cljs]: This was an effect call to remove the overlay, But I mistyped it, Sorry for that
Please check now

File: src/status_im2/common/bottom_sheet/events.cljs [hunk 17]
```diff
@@ -0,0 +1,56 @@
+(ns status-im2.common.bottom-sheet.events
```
Comment (flexsurfer) [inline src/status_im2/common/bottom_sheet/events.cljs:1]: nice, thanks

Comment (flexsurfer) [reply src/status_im2/common/bottom_sheet/events.cljs:1]: don't forget to add it to setup events

Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/events.cljs:1]: Okay

File: src/status_im/ui/screens/browser/options/views.cljs [hunk 18]
```diff
@@ -81,7 +81,7 @@
             :accessibility-label :share
             :icon                :main-icons/share
             :on-press            (fn []
-                                   (re-frame/dispatch-sync [:bottom-sheet/hide])
+                                   (re-frame/dispatch [:bottom-sheet/hide])
```
Comment (flexsurfer) [inline src/status_im/ui/screens/browser/options/views.cljs]: this most likely was intentional, could you rollback?

File: src/status_im/ui/screens/home/sheet/views.cljs [hunk 19]
```diff
@@ -28,7 +27,7 @@
      {:type                :icon
       :theme               :icon
       :accessibility-label :universal-qr-scanner
-      :on-press            #(hide-sheet-and-dispatch
+      :on-press            #(rf/dispatch
```
Comment (flexsurfer) [inline src/status_im/ui/screens/home/sheet/views.cljs]: are you sure we don't need hide-sheet-and-dispatch here ?

File: src/status_im/ui/screens/home/sheet/views.cljs [hunk 20]
```diff
@@ -51,13 +50,13 @@
...
      :on-press            #(hide-sheet-and-dispatch [:open-modal :new-public-chat])}]
-   (when @(rf/subscribe [:communities/enabled?])
+   (when (rf/sub [:communities/enabled?])
      [quo/list-item
       {:theme               :accent
        :title               (i18n/label :t/communities-alpha)
        :accessibility-label :communities-button
        :icon                :main-icons/communities
-       :on-press            #(hide-sheet-and-dispatch [:navigate-to :communities])}])
+       :on-press            #(rf/dispatch [:navigate-to :communities])}])
```
Comment (flexsurfer) [inline src/status_im/ui/screens/home/sheet/views.cljs]: same here

File: src/status_im/ui/screens/home/sheet/views.cljs [hunk 21]
```diff
@@ -68,40 +67,38 @@
...
      :icon-color                   (colors/theme-colors colors/neutral-50 colors/neutral-40)
-     :accessibility-label          :add-a-contact
+     :accessibility-label          :connect-with-users
      :subtitle                     (i18n/label :t/enter-a-chat-key)
      :subtitle-color               colors/neutral-50
      :icon                         :i/add-user
-     :on-press                     #(hide-sheet-and-dispatch [:open-modal :new-contact])}]])
-
+     :on-press                     (fn []
+                                     (rf/dispatch [:bottom-sheet/hide-and-dispatch
```
Comment (flexsurfer) [inline src/status_im/ui/screens/home/sheet/views.cljs]: you have hide-sheet-and-dispatch function in this ns

File: src/status_im2/navigation/core.cljs [hunk 22]
```diff
@@ -265,7 +265,7 @@
 
 ;; BOTTOM SHEETS
 (re-frame/reg-fx :show-bottom-sheet (fn [] (show-overlay "bottom-sheet")))
```
Comment (flexsurfer) [inline src/status_im2/navigation/core.cljs]: then show should be renames as well

File: src/status_im2/common/home/actions/view.cljs [hunk 23]
```diff
@@ -43,11 +43,11 @@
 
 (defn mute-chat-action
   [chat-id]
-  (hide-sheet-and-dispatch [::chat.models/mute-chat-toggled chat-id true]))
+  (rf/dispatch [::chat.models/mute-chat-toggled chat-id true]))
```
Comment (flexsurfer) [inline src/status_im2/common/home/actions/view.cljs]: i think we should keep hide-sheet-and-dispatch here as well

File: src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs [hunk 24]
```diff
@@ -9,9 +9,7 @@
 
 (defn- hide-bottom-sheet-and-dispatch
   [event]
-  (rf/dispatch [:bottom-sheet/hide])
-  (rf/dispatch [:dismiss-keyboard])
-  (rf/dispatch event))
+  (rf/dispatch [:bottom-sheet/hide-and-dispatch #(rf/dispatch :dismiss-keyboard event)]))
```
Comment (flexsurfer) [inline src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs]: something wrong here

File: src/status_im2/navigation/core.cljs (hunk 22 above)
Comment (ibrkhalil) [reply src/status_im2/navigation/core.cljs]: Renamed

File: src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs (hunk 24 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs]: Fixed, Thanks for noting this! :)

File: src/status_im2/subs/root.cljs [hunk 25]
```diff
@@ -37,6 +37,7 @@
 (reg-root-key-sub :bottom-sheet/show? :bottom-sheet/show?)
```
Comment (flexsurfer) [inline src/status_im2/subs/root.cljs]: do we still need other keys except config?

File: src/status_im2/navigation/core.cljs [hunk 26]
```diff
@@ -264,8 +264,8 @@
                  (fn [] (dissmiss-overlay "visibility-status-popover")))
 
 ;; BOTTOM SHEETS
-(re-frame/reg-fx :show-bottom-sheet (fn [] (show-overlay "bottom-sheet")))
-(re-frame/reg-fx :hide-bottom-sheet (fn [] (dissmiss-overlay "bottom-sheet")))
+(re-frame/reg-fx :display-bottom-sheet (fn [] (show-overlay "bottom-sheet")))
```
Comment (flexsurfer) [inline src/status_im2/navigation/core.cljs]: i meant it should be similar names hide-bottom-sheet-overlay and show-bottom-sheet-overlay

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs [hunk 27]
```diff
@@ -123,8 +123,8 @@
          {:accessibility-label :join-community-button
           :on-press            (fn []
                                  (if can-join?
-                                   (do (rf/dispatch [::communities/join id])
-                                       (rf/dispatch [:bottom-sheet/hide]))
+                                   (rf/dispatch [:bottom-sheet/hide-and-dispatch
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: im not sure i understand the point of this change, i believe we want to dispatch event as soon as possible and do not wait for bottom sheet closing

File: src/status_im2/contexts/communities/menus/community_options/view.cljs [hunk 28]
```diff
@@ -6,8 +6,7 @@
 
 (defn hide-sheet-and-dispatch
   [event]
-  (rf/dispatch [:bottom-sheet/hide])
-  (rf/dispatch event))
+  (rf/dispatch [:bottom-sheet/hide-and-dispatch #(rf/dispatch event)]))
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/menus/community_options/view.cljs]: what's the point of this change?

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs (hunk 27 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: The new bottom sheet that was done by Chris Pader
Doesn't act nicely when we dispatch a bottom sheet and another one is already shown
we need to close the showing one first and dispatch showing a new one

File: src/status_im2/contexts/communities/menus/community_options/view.cljs (hunk 28 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/communities/menus/community_options/view.cljs]: Same as previous comment, Every time we need to dispatch/show a bottom-sheet we need to make sure no bottom-sheet is showing

File: src/status_im2/navigation/core.cljs (hunk 26 above)
Comment (ibrkhalil) [reply src/status_im2/navigation/core.cljs]: Ookie Dookie

File: src/status_im2/subs/root.cljs (hunk 25 above)
Comment (ibrkhalil) [reply src/status_im2/subs/root.cljs]: There's some older components that rely on older keys, We're going to need to refactor this moving forward ..

Comment (ibrkhalil) [reply src/status_im2/subs/root.cljs]: I don't think such a refactor should happen in this PR, Because this PR is already big and is solving a specific problem and the refactor is going to be big

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs (hunk 27 above)
Comment (flexsurfer) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: yeah then we need to fix bottom sheet, because it's just a hack, we shouldn't care about that in the code, bottom sheet should care about that itself

Comment (ibrkhalil) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: I think resetting the bottom-sheet and launching a new one is not a hack .. And that's making the bottom-sheet adjust by itself

**Comment by VolodLytvynenko** [comment]
**NOTES for QA:**
- Check the ability to scroll users on the Group details -> 'Manage members' page for android
- Check if the bottom sheet is visible  fully within pinned messages 
image
- Check the [confirm selection] button on image selection
image

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs (hunk 27 above)
Comment (flexsurfer) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: yes i mean we can't make a rule and make all other code more complex, there will be different cases when new bottom sheet will be opened async without closing the current one, so bottom sheet should take care of this case

Comment (flexsurfer) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: it should be simple to implement

File: src/status_im/group_chats/core.cljs [hunk 29]
```diff
@@ -213,6 +213,11 @@
   [{:keys [db]} id]
   {:db (update db :group/selected-contacts conj id)})
 
+(rf/defn clear-contacts
+  {:events [:clear-contacts]}
```
Comment (ilmotta) [inline src/status_im/group_chats/core.cljs]: Suggestion for the name of the event to follow guidelines:

```clojure
:group-chat.clear-contacts
```

File: src/status_im/ui/screens/bottom_sheets/views.cljs [hunk 30]
```diff
@@ -7,11 +7,17 @@
...
+            [status-im2.contexts.chat.messages.pin.list.view :as pin.list]
+            [reagent.core :as reagent]
+            [status-im2.contexts.chat.messages.drawers.view :as drawers]
+            [react-native.core :as react]
+            [status-im.ui.screens.multiaccounts.sheets :as multiaccounts-sheet]))
 
 (defn bottom-sheet
   []
-  (let [{:keys [show? view options]} @(re-frame/subscribe [:bottom-sheet])
+  (let [dismiss-bottom-sheet-callback #(re-frame/dispatch [:bottom-sheet/hide])
```
Comment (ilmotta) [inline src/status_im/ui/screens/bottom_sheets/views.cljs]: Can you use `utils.re-frame/dispatch` instead?

File: src/status_im/ui/screens/bottom_sheets/views.cljs [hunk 31]
```diff
@@ -46,7 +52,22 @@
...
-     (when content
-       [content (when options options)])]))
+          (merge {:content pin.list/pinned-messages-list})
+
+          (= view :drawer/reactions)
+          (merge {:content drawers/reactions})
+
+          (= view :generate-a-new-key)
+          (merge {:content multiaccounts-sheet/actions-sheet}))]
+    (reagent/create-class
```
Comment (ilmotta) [inline src/status_im/ui/screens/bottom_sheets/views.cljs]: Would be nice to see the functional only approach being used in new code instead of class components.

>Do I need to rewrite all my class components?
>
>No. There are [no plans](https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy) to remove >classes from React — we all need to keep shipping products and can’t afford rewrites. **We recommend trying >Hooks in new code**.
>
>-- https://reactjs.org/docs/hooks-faq.html#do-i-need-to-rewrite-all-my-class-components

File: src/status_im/ui2/screens/chat/components/new_chat/view.cljs [hunk 32]
```diff
@@ -31,88 +37,94 @@
...
+             :start-a-new-chat? true
+             :on-toggle         on-toggle}])]
+        (when contacts-selected?
+          [toolbar/toolbar
+           {:show-border? false
+            :center       [button/button
+                           {:type                :primary
+                            :accessibility-label :next-button
+                            :style               (style/chat-button safe-area)
+                            :on-press            #(do
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/components/new_chat/view.cljs]: Style: `(fn [] ...)`

File: src/status_im2/common/bottom_sheet/events.cljs [hunk 33]
```diff
@@ -0,0 +1,56 @@
...
+  (:require [utils.re-frame :as rf]
+            [status-im2.constants :as constants]
+            [react-native.background-timer :as timer]))
+
+(rf/defn show-bottom-sheet
+  [{:keys [db]} {:keys [view options]}]
+  {:show-bottom-sheet-overlay nil
```
Comment (ilmotta) [inline src/status_im2/common/bottom_sheet/events.cljs]: Hey, for the sake of knowledge sharing, the recommended way for event handlers to dispatch effects is different. The way we dispatch in Status is kind of deprecated. Seeing the effect being dispatched with a `nil` argument is weird.

>In fact, with v1.1.0 best practice changed to event handlers should only return two effects :db and :fx, in which case :db was always done first and then :fx, and within :fx the ordering is sequential. This new approach is more about making it easier to compose event handlers from many smaller functions, but more specificity around ordering was a consequence.
>
>-- https://github.com/day8/re-frame/blob/master/docs/Effects.md#order-of-effects

On top of this, as far as I've tried, our convention to use `rf/defn` and `rf/merge` don't work with `:fx`. Just one among other reasons to reconsider (in the future) our current guidelines about registering and dispatch events & effects.

cc @flexsurfer

File: src/status_im2/common/bottom_sheet/events.cljs [hunk 34]
```diff
@@ -0,0 +1,56 @@
...
+  [{:keys [db]} on-closing-animation-finished]
+  (timer/set-timeout #(when (fn? on-closing-animation-finished)
+                        (on-closing-animation-finished))
+                     (+ 50 constants/bottom-sheet-animation-delay))
+  {:dispatch [:bottom-sheet/hide]})
+
+(rf/defn update-bottom-sheet-config
+  {:events [:bottom-sheet/update-config]}
+  [{:keys [db]} {:keys [config value]}]
+  {:db (assoc-in db [:bottom-sheet/config config] value)})
```
Comment (ilmotta) [inline src/status_im2/common/bottom_sheet/events.cljs]: Please, keep the newline character at the end of files. This is in the Clojure Style Guide.

File: src/status_im2/contexts/communities/menus/community_options/view.cljs (hunk 28 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/menus/community_options/view.cljs]: I find this a bit odd. Can't we just make the bottom sheet events do the right thing entirely? Shouldn't they be responsible for also hiding any existing bottom sheet without the caller having to worry about this?

**Comment by ilmotta** [comment]
@ibrkhalil, next time, could you try to open smaller PRs, solving less issues simultaneously? It's really difficult for devs and reviewers to work on big PRs.

File: src/status_im/group_chats/core.cljs (hunk 29 above)
Comment (flexsurfer) [reply src/status_im/group_chats/core.cljs]: you mean `:group-chat/clear-contacts` ?

File: src/status_im/navigation/core.cljs [hunk 35]
```diff
@@ -358,7 +358,7 @@
                              (fn [] (gestureHandlerRootHOC views/sheet-comp))
                              (fn [] views/sheet-comp)))
 
-(re-frame/reg-fx :show-bottom-sheet (fn [] (show-overlay "bottom-sheet")))
+(re-frame/reg-fx :display-bottom-sheet-overlay (fn [] (show-overlay "bottom-sheet")))
 (re-frame/reg-fx :hide-bottom-sheet (fn [] (dissmiss-overlay "bottom-sheet")))
```
Comment (flexsurfer) [inline src/status_im/navigation/core.cljs]: both fx names should be consistent, :dissmiss-bottom-sheet-overlay

File: src/status_im/ui/screens/multiaccounts/views.cljs [hunk 36]
```diff
@@ -41,8 +40,7 @@
 
 (defn topbar-button
   []
-  (re-frame/dispatch [:bottom-sheet/show-sheet
-                      {:content sheets/actions-sheet}]))
+  (re-frame/dispatch [:bottom-sheet/show-sheet :generate-a-new-key {}]))
```
Comment (flexsurfer) [inline src/status_im/ui/screens/multiaccounts/views.cljs]: could you elaborate on this change?

File: src/status_im/ui2/screens/chat/components/new_chat/styles.cljs [hunk 37]
```diff
@@ -13,4 +14,9 @@
...
    :margin-bottom   36
    :justify-content :center
-   :align-items     :center})
\ No newline at end of file
+   :align-items     :center})
+
+(defn chat-button
+  [{:keys [bottom]}]
+  {:position :absolute
+   :bottom   (- bottom 50)})
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/components/new_chat/styles.cljs]: this looks like a hack, could you elaborate?

File: src/status_im2/navigation/core.cljs [hunk 38]
```diff
@@ -264,8 +264,8 @@
                  (fn [] (dissmiss-overlay "visibility-status-popover")))
 
 ;; BOTTOM SHEETS
-(re-frame/reg-fx :show-bottom-sheet (fn [] (show-overlay "bottom-sheet")))
-(re-frame/reg-fx :hide-bottom-sheet (fn [] (dissmiss-overlay "bottom-sheet")))
+(re-frame/reg-fx :display-bottom-sheet-overlay (fn [] (show-overlay "bottom-sheet")))
+(re-frame/reg-fx :hide-bottom-sheet-overlay (fn [] (dissmiss-overlay "bottom-sheet")))
```
Comment (flexsurfer) [inline src/status_im2/navigation/core.cljs]: dissmiss-bottom-sheet-overlay

File: src/status_im2/contexts/chat/photo_selector/style.cljs [hunk 39]
```diff
@@ -1,6 +1,6 @@
 (ns status-im2.contexts.chat.photo-selector.style
-  (:require [quo2.foundations.colors :as colors]
-            [react-native.platform :as platform]))
+  (:require [quo.platform :as platform]
+            [quo2.foundations.colors :as colors]))
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/photo_selector/style.cljs]: please rollback

File: src/status_im2/contexts/chat/messages/drawers/view.cljs [hunk 40]
```diff
@@ -146,9 +152,8 @@
               :title               (:label action)
               :accessibility-label (:label action)
               :icon                (:icon action)
-              :on-press            #(do
-                                      (when on-press (on-press))
-                                      (rf/dispatch [:bottom-sheet/hide]))}]))
+              :on-press            #(do (rf/dispatch [:bottom-sheet/hide])
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/drawers/view.cljs]: (fn []

File: src/status_im2/contexts/chat/group_details/view.cljs [hunk 41]
```diff
@@ -93,10 +93,14 @@
           {:style               {:flex 1}
            :accessibility-label :save
            :on-press            (fn []
-                                  (rf/dispatch [:group-chats.ui/add-members-pressed])
-                                  (js/setTimeout #(rf/dispatch [:group-chats.ui/remove-members-pressed])
-                                                 500)
-                                  (rf/dispatch [:bottom-sheet/hide]))
+                                  (rf/dispatch
+                                   [:bottom-sheet/hide])
+                                  #(do
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/group_details/view.cljs]: anon function and do not needed here

File: src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs [hunk 42]
```diff
@@ -10,7 +10,6 @@
 (defn- hide-bottom-sheet-and-dispatch
   [event]
   (rf/dispatch [:bottom-sheet/hide])
-  (rf/dispatch [:dismiss-keyboard])
```
Comment (flexsurfer) [inline src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs:13]: why?

File: src/status_im/ui/screens/bottom_sheets/views.cljs [hunk 43]
```diff
@@ -1,17 +1,22 @@
 (ns status-im.ui.screens.bottom-sheets.views
```
Comment (flexsurfer) [inline src/status_im/ui/screens/bottom_sheets/views.cljs]: why do we still need this file? we should have only one bottom sheet in status-im2

File: src/status_im/ui/screens/bottom_sheets/views.cljs [hunk 44]
```diff
@@ -1,17 +1,22 @@
...
+            [status-im2.contexts.chat.messages.pin.list.view :as pin.list]
+            [react-native.core :as react]))
 
 (defn bottom-sheet
   []
-  (let [{:keys [show? view options]} @(re-frame/subscribe [:bottom-sheet])
+  (let [dismiss-bottom-sheet-callback (fn []
+                                        (re-frame/dispatch [:bottom-sheet/hide])
+                                        true)
+        {:keys [show? view options]} @(re-frame/subscribe [:bottom-sheet])
```
Comment (flexsurfer) [inline src/status_im/ui/screens/bottom_sheets/views.cljs]: rf/sub

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/group_chats/core.cljs (hunk 29 above)
Comment (ibrkhalil) [reply src/status_im/group_chats/core.cljs]: Renamed to `:group-chat/clear-contacts`

File: src/status_im/ui/screens/bottom_sheets/views.cljs (hunk 30 above)
Comment (ibrkhalil) [reply src/status_im/ui/screens/bottom_sheets/views.cljs]: Done

File: src/status_im/ui/screens/bottom_sheets/views.cljs (hunk 31 above)
Comment (ibrkhalil) [reply src/status_im/ui/screens/bottom_sheets/views.cljs]: Done

File: src/status_im2/common/bottom_sheet/events.cljs (hunk 33 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/events.cljs]: I really like the idea of sequential execution in this new approach, It'll solve problems with race conditions in which I needed to use callbacks a lot of times

File: src/status_im2/common/bottom_sheet/events.cljs (hunk 34 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/events.cljs]: Done

File: src/status_im/navigation/core.cljs (hunk 35 above)
Comment (ibrkhalil) [reply src/status_im/navigation/core.cljs]: Done

File: src/status_im/ui/screens/multiaccounts/views.cljs (hunk 36 above)
Comment (ibrkhalil) [reply src/status_im/ui/screens/multiaccounts/views.cljs]: This change was when I specified preset heights for sheets, reverting

File: src/status_im/ui2/screens/chat/components/new_chat/styles.cljs (hunk 37 above)
Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/components/new_chat/styles.cljs]: I need to pull down the 'Chat with' button to make it match the design
before and after
image
image

File: src/status_im2/contexts/chat/photo_selector/style.cljs (hunk 39 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/photo_selector/style.cljs]: Done

File: src/status_im2/navigation/core.cljs (hunk 38 above)
Comment (ibrkhalil) [reply src/status_im2/navigation/core.cljs]: Done

File: src/status_im2/contexts/chat/messages/drawers/view.cljs (hunk 40 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/drawers/view.cljs]: Done

File: src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs (hunk 42 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/activity_center/notification/contact_verification/view.cljs:13]: I moved the hiding of keyboard to happen when opening bottom sheet, So this is unneeded anymore

File: src/status_im/ui/screens/bottom_sheets/views.cljs (hunk 44 above)
Comment (ibrkhalil) [reply src/status_im/ui/screens/bottom_sheets/views.cljs]: Done

File: src/status_im/ui/screens/bottom_sheets/views.cljs (hunk 43 above)
Comment (ibrkhalil) [reply src/status_im/ui/screens/bottom_sheets/views.cljs]: I moved the code inside of it to `sheets.cljs` namespace in `status-im2`

File: src/status_im/ui2/screens/chat/components/new_chat/styles.cljs (hunk 37 above)
Comment (flexsurfer) [reply src/status_im/ui2/screens/chat/components/new_chat/styles.cljs]: but you've made the position absolute , so its not only y position its also z position

File: src/status_im2/common/bottom_sheet/events.cljs [hunk 45]
```diff
@@ -0,0 +1,30 @@
+(ns status-im2.common.bottom-sheet.events
+  (:require [utils.re-frame :as rf]))
+
+(rf/defn show-bottom-sheet
+  [{:keys [db]} {:keys [view options]}]
+  {:dispatch                  [:dismiss-keyboard]
```
Comment (flexsurfer) [inline src/status_im2/common/bottom_sheet/events.cljs:6]: mhm im not sure, what if we'll have a case when we don't want to dismiss a keyboard? but i think in such cases we could open it again in the new sheet, ok

File: src/status_im2/common/bottom_sheet/sheets.cljs [hunk 46]
```diff
@@ -47,6 +52,12 @@
 
           (= view :pinned-messages-list)
           (merge {:content pin.list/pinned-messages-list}))]
-    [bottom-sheet/bottom-sheet opts
-     (when content
-       [content (when options options)])]))
+    [:f>
+     (fn []
+       (quo.react/effect! (fn []
```
Comment (flexsurfer) [inline src/status_im2/common/bottom_sheet/sheets.cljs]: we shouldn't use quo in status-im2, we have rn/use-effect

File: src/status_im2/common/bottom_sheet/events.cljs [hunk 47]
```diff
@@ -0,0 +1,30 @@
...
+    :options options}))
+
+(rf/defn hide-bottom-sheet
+  {:events [:bottom-sheet/hide]}
+  [{:keys [db]}]
+  {:db                           (assoc db :bottom-sheet/show? false)
+   :dismiss-bottom-sheet-overlay nil})
+
+(rf/defn hide-bottom-sheet-navigation-overlay
+  {:events [:bottom-sheet/hide-navigation-overlay]}
```
Comment (flexsurfer) [inline src/status_im2/common/bottom_sheet/events.cljs:28]: where is this used? why fx can't be used directly ?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/common/bottom_sheet/events.cljs (hunk 47 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/events.cljs:28]: [Here](https://github.com/status-im/status-mobile/blob/0bd93851bbe54c655b646bec5e824937d3bd5eef/src/status_im2/common/bottom_sheet/view.cljs#L101)

File: src/status_im2/common/bottom_sheet/sheets.cljs (hunk 46 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/sheets.cljs]: Done

File: src/status_im/ui2/screens/chat/pin_limit_popover/view.cljs [hunk 48]
```diff
@@ -0,0 +1,64 @@
...
+           {:accessibility-label :close-pin-limit-popover
+            :active-opacity      1
+            :on-press            #(rf/dispatch [:pin-message/hide-pin-limit-modal chat-id])
+            :style               {:position :absolute
+                                  :top      16
+                                  :right    16}}
+           [quo/icon :i/close
+            {:color (colors/theme-colors colors/white colors/neutral-100)
+             :size  12}]]])))])
+
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/pin_limit_popover/view.cljs]: Extra lines

File: src/status_im2/common/bottom_sheet/sheets.cljs [hunk 49]
```diff
@@ -47,6 +51,12 @@
 
           (= view :pinned-messages-list)
           (merge {:content pin.list/pinned-messages-list}))]
-    [bottom-sheet/bottom-sheet opts
-     (when content
-       [content (when options options)])]))
+    [:f>
+     (fn []
+       (rn/use-effect (fn []
+                        (rn/hw-back-add-listener dismiss-bottom-sheet-callback)
```
Comment (ilmotta) [inline src/status_im2/common/bottom_sheet/sheets.cljs:57]: `BackHandler` is only meaningful for Android. How does this `use-effect` is working for iOS? Shouldn't we check if the platform is Android before using `BackHandler`? Reference: https://reactnative.dev/docs/backhandler#addeventlistener

File: src/status_im2/subs/contact.cljs [hunk 50]
```diff
@@ -111,6 +112,23 @@
         (sort-by
          #(visibility-status-utils/visibility-status-order (:public-key %))))))
 
+(re-frame/reg-sub
+ :contacts/sorted-and-grouped-by-first-letter
```
Comment (ilmotta) [inline src/status_im2/subs/contact.cljs:116]: Missing tests for this layer-3 subscription ;)

**Comment by pavloburykh** [comment]
@ibrkhalil hi! Could you please move this PR to E2E column when all review comments will be resolved? thanx.

File: src/status_im2/common/bottom_sheet/sheets.cljs (hunk 49 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/sheets.cljs:57]: Good point :)
I think it's not that important for iOS since it doesn't have a physical back button .. Users can dismiss the bottom-sheet by clicking the overlay and continue using the app .. But this does nothing on iOS like you said Icaro

File: src/status_im2/subs/contact.cljs (hunk 50 above)
Comment (ibrkhalil) [reply src/status_im2/subs/contact.cljs:116]: Copying the tests from the other PR

Comment (ibrkhalil) [reply src/status_im2/subs/contact.cljs:116]: Added

File: src/status_im2/contexts/communities/menus/community_options/view.cljs (hunk 28 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/communities/menus/community_options/view.cljs]: The is changed now

File: src/status_im/ui2/screens/chat/components/new_chat/styles.cljs (hunk 37 above)
Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/components/new_chat/styles.cljs]: This is reverted

**Comment by pavloburykh** [comment]
@ibrkhalil thanx for the PR. Please, take a look at following issues. Please, let me know which of them are not in scope of PR and I will log them separately. 

### ISSUE 1 Only part of existing contacts are displayed in contact list of New chat screen

**Preconditions:** for reproduction you need to take User with at least 10+ contacts. 

**Steps:** 

1. Tap Chats bottom tab
2. Tap plus button to open Adding new chat bottom sheet
3. Tap New chat
4. See if all existing contacts are displayed in contacts list on New chat screen

**Actual result:**  Only part of existing contacts are displayed in contact list of New chat screen. Due to this issue I could not verify that https://github.com/status-im/status-mobile/issues/14671 is fully fixed as I was not able to generate a long contact list to check scrolling. 

**Expected result:** All existing contacts are displayed in contacts list of New chat screen.


https://user-images.githubusercontent.com/97245802/214350443-fe8a7923-34fd-48eb-997f-0edf5ef107c2.mp4

[Status-debug-logs (21).zip](https://github.com/status-im/status-mobile/files/10492014/Status-debug-logs.21.zip)

**Comment by pavloburykh** [comment]
### ISSUE 2 Checkmark in contact list of New chat screen does not appear/disappear if checkbox area is not tapped for checking/unchecking

**Preconditions:** User has at least 1 contact

**Steps:** 
1. Tap Chats bottom tab
2. Tap plus button to open Adding new chat bottom sheet
3. Tap New chat
4. Try to check contact by tapping not directly on checkbox but on contact element itself. 
5. Observe the result

**Actual result:** checkmark does not appear, but in fact. contact has been check, as Start new chat button appears. The same behaviour with uncheck action. 

**Expected result:** not sure about expected behaviour. There are 2 options:
1. Checkmark appears in checkbox when contact element is tapped even if not directly in the area of checkbox. 
OR
2. It should be possible to check/uncheck contact only by tapping directly on checkbox. Such behaviour has contact list on Manage group members screen. 

What is definitely expected - is that checking/unchecking of elements in the list should be the same  in Manage group members screen and New chat screen which is different now. 



[Status-debug-logs (22).zip](https://github.com/status-im/status-mobile/files/10492117/Status-debug-logs.22.zip)

https://user-images.githubusercontent.com/97245802/214353742-eb566dc1-c630-4a27-8c88-f6b697fca91a.mp4

**Comment by pavloburykh** [comment]
### ISSUE 3 State of checkboxes in contact list of New chat screen is not reset after its reopening

**Preconditions:** User has some contacts in his contact list

**Steps:**
1. Tap Chats bottom tab
2. Tap plus button to open Adding new chat bottom sheet
3. Tap New chat
4. Check contacts from the list
5. Close bottom sheet and re-open on New chat screen
6. See the state of checkboxes

**Actual result:** state of checkboxes has not been reset after re-opening. If to try more check/uncheck actions we can see that state of checkboxes is randomly saved after re-opening. Can be observed on attached video. 

**Expected result:** state of checkboxes should be reset after re-opening? If some other behaviour is expected, please let me know @ibrkhalil.

[Status-debug-logs (23).zip](https://github.com/status-im/status-mobile/files/10492204/Status-debug-logs.23.zip)

https://user-images.githubusercontent.com/97245802/214356171-149b5469-7566-426d-a746-bf1afe4c9ec0.mp4

**Comment by pavloburykh** [comment]
### ISSUE 4 Sync new device bottom sheet is fully overlapped by keyboard on set password step

**Steps:**

1. Tap Browser (Profile) bottom tab
2. Tap Syncing - Setup Syncing
3. Observe the result

**Actual result:** Sync new device bottom sheet is fully overlapped by keyboard on set password step

**Expected result:** Sync new device bottom sheet is not overlapped by keyboard on set password step


https://user-images.githubusercontent.com/97245802/214362812-a6d54892-29f5-4e13-acbd-75d8d2a9a8c8.mp4

**Comment by pavloburykh** [comment]
### ISSUE 5 Bottom sheet is stuck for a moment before to be fully closed

**Steps:**

1. Open any bottom sheet
2. Close it by tapping outside the bottom sheet area (not by dragging down)
3. Pay attention at animation at the moment before bottom sheet is fully fold down

**Actual result:** animation stucks for a moment before full fold down of bottom sheet. I compared the behaviour with nightly and have not reproduced such behaviour so I assume it to be PR related. 

**Expected result:** bottom sheets are closing smoothly


https://user-images.githubusercontent.com/97245802/214364626-c639df53-2d1f-410f-a795-7ece29f43df3.mp4

**Comment by pavloburykh** [comment]
### ISSUE 6 Manage group members contact list is not scrollable

**Preconditions:** User has at least 7+ (depending on device screen size) contacts in his contact list in order to test scrolling

**Steps:**
1. Create group chat
2. Open Manage members screen: longtap on group in chats list - Group details - Manage members
3. Try to scroll contact list
4. Observe the result

**Actual result:** Manage group members contact list is not scrollable

**Expected result:** Manage group members contact list is scrollable


https://user-images.githubusercontent.com/97245802/214370215-7294e2ad-a572-478a-ae09-0933f78356c3.mp4

**Comment by pavloburykh** [comment]
this one might not be related to bottom sheet but composer. Tell me if so and I will log it separately

### ISSUE 7 Input field is not visible on editing/replying message

**Steps:**

1. Open chat
2. Send a message
3. Try to edit/reply the message
4. See if input field is visible

**Actual result:** Input field is not visible. It becomes visible after starting typing

**Expected result:** Input field is visible


https://user-images.githubusercontent.com/97245802/214374070-8d708fff-b8e6-4843-a2c4-87e49cf42086.mp4

**Comment by flexsurfer** [comment]
hey @qoqobolo seems like our old "friend" here in the issue7

**Comment by pavloburykh** [comment]
### ISSUE 8 Confirm selection/Save/Chat with.. buttons are located to high from the bottom of the screen

Confirm selection - is button from gallery screen
Save - button from Manage group members screen
Chat with../Setup group chat - button from New chat screen

photo_2023-01-24 20 19 15
photo_2023-01-24 20 19 18
photo_2023-01-24 20 19 21

**Comment by pavloburykh** [comment]
@ibrkhalil could you please also resolve existing conflicts in `src/status_im2/common/bottom_sheet/view.cljs` and
`src/status_im2/constants.cljs` ? Thanx!

**Comment by ibrkhalil** [comment]
> @ibrkhalil could you please also resolve existing conflicts in `src/status_im2/common/bottom_sheet/view.cljs` and
> 
> `src/status_im2/constants.cljs` ? Thanx!

Okay Pavlo
I think the new chat list has only mutual contacts, are you sure the missing contacts are mutual?
And the text input issue is not related to this PR

**Comment by pavloburykh** [comment]
@ibrkhalil 
> I think the new chat list has only mutual contacts, are you sure the missing contacts are mutual? 

Currently we do not display any contacts in the list until they become mutual, so basically I am sure about that. 

> And the text input issue is not related to this PR

Got it, thanx. will log a separate issue on that.

**Comment by qoqobolo** [comment]
> hey @qoqobolo seems like our old "friend" here in the issue7

Yep, this guy [looks familiar](https://github.com/status-im/status-mobile/pull/14758#issuecomment-1381827602).
Now I can say that for me it reproduces constantly again on my Huawei only from today's nightly. Tomorrow I'll log it separately and look in more detail.

**Comment by ibrkhalil** [comment]
Issue 2 and 3 are solved [here](https://github.com/status-im/status-mobile/pull/14790/files)

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @ibrkhalil Thanx for the fixes. I see that IOS and integration tests builds are failed. Could you please take a look at that? Thanx.

**Comment by pavloburykh** [comment]
@ibrkhalil Thanx for the fixes. Please, take a look at the following issues. 

### ISSUE 9 Group members are displayed unselected on Manage members screen. As a result - unable to remove members from the group. 

**Steps:** 

1. Create a group chat
2. Open manage members screen
3. Pay attention if group members are displayed as selected in the list. 

**Actual result:** Group members are displayed unselected. As a result - unable to remove members from the group. 

**Expected result:** Group members should be displayed selected in the contact list of Manage members screen. 


https://user-images.githubusercontent.com/97245802/214819824-3369e724-e949-43df-8e4a-b262391b17db.mp4

**Comment by pavloburykh** [comment]
### ISSUE 10 Tapping on own name in the list of group members results in appearing Save button

**Steps:** 

1. Create a group
2. Open manage group screen
3. Tap on own name
4. Observe the result

**Actual result:** Save button appears. 

**Expected result:** should be clarified by designers if we need to show own name in contact list of Manage members screen. If yes - then we need to fix current behaviour when Save button appears, because user cannot select/unselect himself from the group. If no - then we need to hide user's own name from the list. 


https://user-images.githubusercontent.com/97245802/214825593-247d525a-4410-4616-b40b-4891daa61dfd.mp4

**Comment by pavloburykh** [comment]
### [ISSUE 8](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402387978) is partially fixed. 

Bottom area for Chat with../Setup group chat buttons on Start new chat screen is still too large. 


https://user-images.githubusercontent.com/97245802/214826245-2f92ae43-e6c2-4a9b-9391-dd3d967aec2c.mp4

**Comment by pavloburykh** [comment]
### [ISSUE 4](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402306659) is not fixed

**Comment by pavloburykh** [comment]
### ISSUE 11 New chat/Add contact bottom sheet seems to much expanded

I guess there is to much space below "Add contact". See screenshot below. 

photo_2023-01-26 17 15 29

**Comment by pavloburykh** [comment]
@ibrkhalil from my perspective, the issue that better to be fixed before merging is [ISSUE 4](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402306659). 
[ISSUE 10](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1404879604) is critical but in fact it is not related to current PR but to https://github.com/status-im/status-mobile/pull/14790 which has been merged into develop yesterday. So I guess I will log it separately. 

Rest of the issues can be fixed as followups is order not to block the PR. 

Another blocker is failed IOS build. We cannot merge PR until both platforms will be tested. Are there any updates from Jacob regarding failed IOS? I see that this is kind a global problem. 

Tell me WDYT?

**Comment by pavloburykh** [comment]
@ibrkhalil **UPDATE:**

It turned out that this issue https://github.com/status-im/status-mobile/issues/14664 has already been fixed by @flexsurfer in his PR https://github.com/status-im/status-mobile/pull/14911 which has been recently merged into develop. 

So I guess you need to remove this fix from your code.

**Comment by ibrkhalil** [comment]
> @ibrkhalil from my perspective, the issue that better to be fixed before merging is [ISSUE 4](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402306659). [ISSUE 10](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1404879604) is critical but in fact it is not related to current PR but to #14790 which has been merged into develop yesterday. So I guess I will log it separately.
> 
> Rest of the issues can be fixed as followups is order not to block the PR.
> 
> Another blocker is failed IOS build. We cannot merge PR until both platforms will be tested. Are there any updates from Jacob regarding failed IOS? I see that this is kind a global problem.
> 
> Tell me WDYT?

I agree to try to not block the PR, I have added more fixes if you can kindly check .. Thanks!

**Comment by ibrkhalil** [comment]
> ### ISSUE 11 New chat/Add contact bottom sheet seems to much expanded
> I guess there is to much space below "Add contact". See screenshot below.
> 
> photo_2023-01-26 17 15 29

That's the minimum height of bottom sheet, We can override it to make it look nicer @flexsurfer WDYT ?

**Comment by pavloburykh** [comment]
> I agree to try to not block the PR, I have added more fixes if you can kindly check .. Thanks!

@ibrkhalil thanx! Could you please specify what exact fixes have been added and what issues have been left for followups?

**Comment by ibrkhalil** [comment]
> > I agree to try to not block the PR, I have added more fixes if you can kindly check .. Thanks!
> 
> @ibrkhalil thanx! Could you please specify what exact fixes have been added and what issues have been left for followups?

Issues 9, 10, 4
Follow ups: 8, 11 as they require design team input

**Comment by pavloburykh** [comment]
@ibrkhalil Unfortunately still cannot verify fixes on IOS, as builds keep failing.

**Comment by ibrkhalil** [comment]
> @ibrkhalil Unfortunately still cannot verify fixes on IOS, as builds keep failing.

Please check now

**Comment by pavloburykh** [comment]
@ibrkhalil please, take a look. 

### ISSUE 12 Reactions bottom sheet is empty
Did not reproduce issue in nightly build so I suppose this is a PR bug. @ibrkhalil let me know if it is a quick fix. If not - we may think about separate follow up in order not to block this PR. 

**Steps:** 

1. Start any chat
2. Send a message
3. Put some reaction to the message
4. Open reactions bottom sheet by taping + button near existing reaction
5. See if there are any reactions icons

**Actual result:** Reactions bottom sheet is empty

**Expected result:** reaction icons are displayed


https://user-images.githubusercontent.com/97245802/215534780-d92fa687-cae3-4757-b8f7-48c289a167c3.mp4

**Comment by pavloburykh** [comment]
@ibrkhalil this one also can be a follow up if it is not an easy fix

### ISSUE 13 Sometimes selected contacts are not displayed among the list of members of future group on group creation screen (step)

It is not reproducible 10 out of 10. Try following steps and see video below. On the video I captured the bug after couple of initial tries of reproduction, so watch the video to the end. 

**Steps:** 

1. Open new chat bottom sheet (screen with list of contacts)
2. Quickly select couple of contacts
3. Quickly unselect previously selected contacts
4. Again Quickly select those contacts
5. Tap create group chat button
6. See if selected contacts are displayed in the list during next step of group creation

**Actual result:** selected members are not displayed in the list during group creation. The list is empty - group with 1 user (admin) will be created. 

**Expected result:** all selected contacts are displayed in the list of future group


https://user-images.githubusercontent.com/97245802/215540209-cc99371f-6a2a-46d5-a5d6-9c4aa40fdf61.mp4

[unchecked_group_members.zip](https://github.com/status-im/status-mobile/files/10537974/unchecked_group_members.zip)

**Comment by pavloburykh** [comment]
@ibrkhalil 
ISSUES 9, 10, 4 are fixed. Let me know if you prefer to fix ISSUES 12 and 13 as followups. If so - PR is ready to be merged.

**Comment by ibrkhalil** [comment]
> @ibrkhalil ISSUES 9, 10, 4 are fixed. Let me know if you prefer to fix ISSUES 12 and 13 as followups. If so - PR is ready to be merged.

Thank you so much Pavlo for the very thorough review
I fixed issue 12 .. We can log issue 13 separately and I can pick it up later after I finish deletion of pinned messages
