### PR TITLE
Handle long names in system messages

### LINKED ISSUE #16345: Deal with longer names in messages
# Bug Report

It's illustrated on the screenshot below — in this particular case the name should be truncated to fit one line of text but the problem with that is there is some extra text, and that text shouldn't be truncated, only the name itself.
So it should be something like `alwx ww... pinned a message`, and that text should fit the entire width available.

Screenshot 2023-06-21 at 16 30 27

The previous solution (before this PR: https://github.com/status-im/status-mobile/pull/16188) was to always truncate manually (`(utils/truncate-str pinned-by 18)`) but that solution is terrible because the screens are different, and localizations are different as well.
It seems like there is no good solution to this problem out-of-box: you can add `flex: 1` to the author name but in this case it won't really work good with short names, and there will always be some spacing. What I'm thinking of is some function to measure the space available but I'm not sure that it's worth it because it will take quite some time to write something like that.

Please note that the solution should work not only for pinned messages but also for deleted messages (and all other types in `quo2.components.messages.system-message`)

### Reproduction

1) Open Status
2) Create/restore an account with long name
3) Observe the truncation of the name in messages

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #16345 

### Summary
Truncate user name in system messages when a user's name is lengthy and cannot be fully displayed along with the system message in a single line.

### Testing notes
- System Messages Component: Quo2 Preview -> Messages -> System Messages
- Following System message types in the chat
  - pinned
  - contact-request
  - added (user added)
  - removed (user removed)

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
- Chat

status: ready

### CODE REVIEW

File: src/quo2/components/messages/system_message.cljs [hunk 1]
```diff
@@ -155,12 +161,12 @@
                 :color   (or customization-color :primary)
                 :opacity 5}
     :timestamp timestamp}
-   [rn/view
+   [rn/view {:style {:flex-shrink 1}}
     [rn/view
      {:flex-direction :row
-      :flex-wrap      :wrap
-      :height         18.2}
```
Comment (ajayesivan) [inline src/quo2/components/messages/system_message.cljs:162]: @ibrkhalil I've noticed the addition of this `height` in [your PR here](https://github.com/status-im/status-mobile/pull/16997/files#diff-07804a4aa53d86bfec5907032607dc58b11e0e4a1a1d5801625c0be2ad27f738R162). I'm uncertain about its purpose; please advise if its removal could cause any problems.

File: src/quo2/components/messages/system_message.cljs [hunk 2]
```diff
@@ -70,7 +70,6 @@
    [rn/view
     {:align-self     :center
      :flex-direction :row
-     :margin-right   40 ;; dirty hack, flexbox won't work as expected
```
Comment (ajayesivan) [inline src/quo2/components/messages/system_message.cljs:73]: @flexsurfer, I've taken out this line and encountered no problems. However, I could be overlooking something. Please review and inform me if its removal triggers any issues.

Comment (flexsurfer) [reply src/quo2/components/messages/system_message.cljs:73]: i think that's fine, because you've changed the layout of elements and you have `:flex-shrink 0`

**Review by flexsurfer — COMMENTED** [review]
it seems like at least time element is not aligned properly

File: src/quo2/components/messages/system_message.cljs [hunk 3]
```diff
@@ -49,7 +49,7 @@
 (defn split-text
   [label theme add-pred?]
   (let [color (text-color theme)]
-    [:<>
+    [rn/view {:style {:flex-direction :row :flex-shrink 0 :align-items :center}}
```
Comment (FFFra) [inline src/quo2/components/messages/system_message.cljs:52]: If possible, I would suggest moving this to a separate style file

File: src/quo2/components/messages/system_message.cljs [hunk 4]
```diff
@@ -102,13 +101,17 @@
    [rn/view
     {:flex-direction :row
      :align-items    :center
-     :flex-wrap      :wrap}
-    [rn/view {:flex-direction :row :align-items :center}
+     :flex-shrink    1
+     :flex-wrap      :nowrap}
+    [rn/view {:flex-direction :row :align-items :center :flex-shrink 1}
```
Comment (FFFra) [inline src/quo2/components/messages/system_message.cljs:106]: same here and the others

File: src/quo2/components/messages/system_message.cljs [hunk 5]
```diff
@@ -136,13 +139,16 @@
    [rn/view
     {:flex-direction :row
      :align-items    :center
-     :flex-wrap      :wrap}
+     :flex-shrink    1
+     :flex-wrap      :nowrap}
     (when-not incoming? [split-text "Contact request sent to" theme false])
```
Comment (FFFra) [inline src/quo2/components/messages/system_message.cljs:143]: Do we have a translation for this string?

File: src/quo2/components/messages/system_message.cljs [hunk 6]
```diff
@@ -136,13 +139,16 @@
...
      [sm-user-avatar display-name photo-path]
      [text/text
-      {:weight :semi-bold
-       :size   :paragraph-2}
+      {:weight          :semi-bold
+       :number-of-lines 1
+       :style           {:flex-shrink 1}
+       :size            :paragraph-2}
       display-name]]
     (when incoming? [split-text "sent you a contact request" theme true])]])
```
Comment (FFFra) [inline src/quo2/components/messages/system_message.cljs]: Do we have a translation for this string?

**Review by FFFra — COMMENTED** [review]
Some small comments. Probable to be addressed in the next PR as you mentioned =)

File: src/quo2/components/messages/system_message.cljs [hunk 7]
```diff
@@ -70,7 +70,6 @@
    [rn/view
     {:align-self     :center
      :flex-direction :row
```
Comment (mmilad75) [inline src/quo2/components/messages/system_message.cljs:74]: Is there a reason that the styles are in the same file and not in a separate file?

Comment (mmilad75) [reply src/quo2/components/messages/system_message.cljs:74]: Other components have a structure like this:
```
component-name
 - view.cljs
 - style.cljs
```

Why this one is not like that?

**Comment by ajayesivan** [comment]
Hi @FFFra @mmilad75, This component predates our current file structure for view and style separation. In this PR, I'm addressing the long name issue only. I've opened a separate [issue](https://github.com/status-im/status-mobile/issues/17076) to track the component's refactoring, which I plan to address in a subsequent PR.

**Comment by mohsen-ghafouri** [comment]
LGTM, nice work 👍🏻

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM, nice work :)

**Review by FFFra — APPROVED** [review]

**Comment by ajayesivan** [comment]
@flexsurfer fixed timestamp alignment

Screenshot 2023-08-31 at 18 40 29

**Review by alwx — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@ajayesivan i think you PR is also related to 1 comment in this [Issue](https://github.com/status-im/status-mobile/issues/16867), right?

**Comment by ajayesivan** [comment]
> @ajayesivan i think you PR is also related to 1 comment in this [Issue](https://github.com/status-im/status-mobile/issues/16867), right?

@mohsen-ghafouri This PR only fixes the issue in the system-message component. We have to handle the one in #16867 separately.

**Review by BalogunofAfrica — APPROVED** [review]
LGTM, Well done 👍

**Comment by VolodLytvynenko** [comment]
Hi @ajayesivan thank you for PR. here a list of found issues:

## ISSUE 1: [Android] User Display Name not truncated in system notification after message removal
### Steps:
1. `User_A` with long display name sends the message
2. `User_A` removes the message by 'delete for everyone' option
3. `User_B` Checks the chat

### Actual result:
The user's display name is not truncated in the system notification after the message has been removed. As a result, the time of the message sending is out of the screen.

image

### Expected result:
The display name should be truncated in the system notification to ensure that the time of message sending is visible on the screen.

### Devices:
- Real device: Pixel 7a, Android 13
- Android studio: Pixel 6 Pro API 31

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: The timestamp is shown before 'sent you a contact request' system message if user CR sender is with long display name

### Steps:
1. `User_A` with long display  sends the CR to `User B`
2. `User_B` accepts the CR
3. `User_B` Checks the 1-1 chat

### Actual result:
The timestamp is shown before 'sent you a contact request'
image

### Expected result:
The timestamp is shown after 'sent you a contact request'
image

### Devices:
- Real device: Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 16
- Android studio: Pixel 6 Pro API 31

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: [Android] Big gap when message is pinned and in system contact acceptance message
### Steps:
1. `User A` with max length display name sends a CR to `User B`
2. `User B` accepts the CR (now check the 1-1 chat)
3. `User A` pins the message
4. `User B` checks the 1-1 chat

### Actual result:
The display name is truncated too early, causing a gap in the following places:

1. Big gap before 'now a contact' system message
image

2. Big gap in the pinned system message
image

### Expected result:
The display name should be truncated in time to prevent these gaps from appearing

**Comment by VolodLytvynenko** [comment]
## ISSUE 4: Nickname overlaps the display name
### Steps:
1. `User A` sets a nickname for `User B`
2. `User A` checks the following places
3. `User B` sends a message to `User A`
4. `User A` checks in the following places:
  - In first line of message
  - In the chat preview
  - Contacts tab
  - 'new chat' overlay

### Actual result: 
Nickname overlaps the display name in the following places:
-  In first line of message
image
-  In the chat previewimage
- Contacts tab
image
- 'new chat' overlay
image

### Expected result: 
The display name should be shown in the right part after the nickname.
image

**Comment by ajayesivan** [comment]
@VolodLytvynenko Resolved issues 1, 2, and 3. This PR specifically addresses the long name issue within the System Messages component, and issue 4 is unrelated to this component.

I think it's more appropriate to address issue 4 in a separate PR, as it appears to be closely related to the first issue in this Design review: https://github.com/status-im/status-mobile/issues/16867. If you think otherwise, please do let me know.

**Comment by VolodLytvynenko** [comment]
> I think it's more appropriate to address issue 4 in a separate PR, as it appears to be closely related to the first issue in this Design review: #16867. If you think otherwise, please do let me know.

Hi, @ajayesivan thank you for the PR and for your patience. I completely agree with you. This issue is my fault. I didn't notice that it already exists on the latest nightly, which means it's not related to this PR. I will report it separately. Thank you!

No issues from my side anymore.

@Francesca-G kindly, could you please take a look?

**Review by Francesca-G — APPROVED** [review]
Long names look good :)

Here are a couple of [comments](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=5405%3A60916&mode=design&t=BDoOZi5nqysJ4w6R-1) all related to the missing avatar in the contact messages

**Comment by ajayesivan** [comment]
I have created a follow-up issue for the missing user avatar issue: https://github.com/status-im/status-mobile/issues/17208
