### PR TITLE
[#5449] Activity loading indicator persist staying on Android

### LINKED ISSUE #5449: Activity loading indicator persist staying on Android webview when navigating between screens in Dapps
***Type***: Bug

***Summary***: When contact navigates in Dapps between different views, - often webview stuck with continuously loading indicator (with a greyed out background) even it's visible that page was updated. It blocks further Dapp usage until webview refresh or re-navigate to Dapp again from Home screen. 
Often occurs with usual navigation in CryptoKitties, BountyNetwork Dapps. See steps to reproduce on how to "force" the issue.
Note: it's all fine with iOS webview (tested on iPhoneX)

#### Expected behavior
Activity loading indicator disappears once the page loaded in webview

#### Actual behavior
Activity loading indicator persist staying on Android webview when navigating between screens in Dapps 

### Reproduction
- Open Status and create new account
- Navigate to `Open Dapp` -> `CryptoKitties`
- On the  Cryptokitties there is `Search` and `Catalogue` links. Tap any of it. 
- Tap quick between `Search` and `Catalogue`

### Additional Information
* Status version: Develop `0.9.26 (6362) node 03bf6e3`
* Operating System: Android

#### Logs

See TF session from 00:35 - 01:00 or 01:45-end https://app.testfairy.com/projects/4803622-status/builds/8553713/sessions/4398290122/?accessToken=8QLtiMn8DU7E9EmAgrBkpnSV-jc 

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8553713/sessions/4398290122/?accessToken=8QLtiMn8DU7E9EmAgrBkpnSV-jc">TestFairy: Status 0.9.26 (6362) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #5449

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/browser/views.cljs [hunk 1]
```diff
@@ -82,7 +83,8 @@
 
 (defn on-navigation-change [event browser]
   (let [{:strs [url loading]} (js->clj event)]
-    (re-frame/dispatch [:update-browser-options {:loading? loading}])
+    (when platform/ios?
```
Comment (jeluard) [inline src/status_im/ui/screens/browser/views.cljs:86]: Can you add a comment detailing why this is ios only?

**Review by jeluard — APPROVED** [review]

**Comment by Serhy** [comment]
Builds https://i.diawi.com/7i8QmH (iOS) and Android (https://i.diawi.com/8GpRc3) tested on Android 6.0.1, 7.0, 8.0 and all works fine! 
Disabling webview loader on Andorid - no more #5449 issue on Android platform. Behavior on iOS left the same.
Autotests reviewed and confirmed as not related to current changed and we'll review separately them for fix. 

<blockquote><div><strong><a href="https://i.diawi.com/7i8QmH">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/8GpRc3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by Serhy — APPROVED** [review]
