### PR TITLE
[FIX #3123] ui: fix network field overflow on long network names in profile

### LINKED ISSUE #3123: Network field does not fit screen size on new profile (small screens)
### Description

*Type*: Bug

*Summary*: Due to full network name the length of it does not fit screen size and is written in 2 lines which looks as a bug. Low prio as I am not sure if the range of supported screens / devices is changed , maybe we dont support iPhone 5S anymore

#### Actual behavior
image

### Reproduction

- Open Status
- Tap profile tab

Additional Information
* Status version: latest develop
* Operating System: iOS
* Device iPhone 5S 4"

### PR DESCRIPTION
**Pull request by ihor-lev**
fixes #3123 

### Summary

Introduced proportions between field title and value and ellipsis endings on text overflow.

Note: In case of longer network names, this bug may be probably reproducible even with latest ios/android devices.

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Comment by goranjovic** [comment]
Hi @ikysylevych - thanks for the contribution!

**Comment by jeluard** [comment]
@ikysylevych If you feel like it you can extract this as a component ! We certainly have this need for others texts.

**Review by jeluard — APPROVED** [review]

**Comment by ihor-lev** [comment]
@jeluard I'm still learning the project structure, don't want to break things. But I hope I could extract it to a separate component soon.

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/profile/views.cljs [hunk 1]
```diff
@@ -215,8 +215,10 @@
    [react/view styles/settings-item
     [react/text {:style styles/settings-item-text}
      (i18n/label label-kw)]
-    [react/text {:style      styles/settings-item-value
-                 :uppercase? component.styles/uppercase?} value]
+    (when-not (string/blank? value)
+      [react/text {:style           styles/settings-item-value
+                   :number-of-lines 1
+                   :uppercase?      component.styles/uppercase?} value])
```
Comment (yenda) [inline src/status_im/ui/screens/profile/views.cljs]: can you put value on the next line please ?

**Review by yenda — APPROVED** [review]

File: src/status_im/ui/screens/profile/views.cljs (hunk 1 above)
Comment (ihor-lev) [reply src/status_im/ui/screens/profile/views.cljs]: it's done. thanks.

**Comment by asemiankevich** [comment]
Branch: PR-3345
Android: https://i.diawi.com/qfte3X
iOS: https://i.diawi.com/qQSFdt

**Comment by jeluard** [comment]
@ikysylevych Could you squash your commits?

**Comment by ihor-lev** [comment]
@jeluard I squashed my commits. Thanks!

**Comment by jeluard** [comment]
@ikysylevych Thanks!
