### PR TITLE
Wallet Activity: transactions are not sorted by time #20808

### LINKED ISSUE #20808: Wallet Activity: transactions are not sorted by time
# Bug Report

#### Expected behavior
Transactions are sorted by date and time

#### Actual behavior
The last transaction is shown below the earlier one

### Reproduction

1. Recover an account with transactions
2. Navigate to Wallet
3. Select an account with transactions
4. Click Activity tab

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mmilad75**
fixes #20808

https://github.com/user-attachments/assets/e267d2e6-116e-46ee-8dd8-07aa41808068

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
good stuff @mmilad75! 🙌

**Review by vkjr — APPROVED** [review]

File: src/status_im/subs/wallet/activities.cljs [hunk 1]
```diff
@@ -115,13 +115,13 @@
...
-                                     (sort :timestamp))]
+                                     (sort-by :timestamp))]
      (->> address-activities
           (keep #(process-activity-by-type chain-id->network-name %))
           (group-by (fn [{:keys [timestamp]}]
                       (datetime/timestamp->relative-short-date (* timestamp 1000))))
           (map (fn [[date activities]]
                  {:title     date
-                  :data      activities
+                  :data      (reverse activities)
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/activities.cljs:125]: Can we skip the `reverse` if we provide `>` or `<` in the `sort-by` call?

**Review by ulisesmac — APPROVED** [review]
Good work @mmilad75 !

File: src/status_im/subs/wallet/activities.cljs (hunk 1 above)
Comment (mmilad75) [reply src/status_im/subs/wallet/activities.cljs:125]: I tried that and a lot of other methods, but none of them worked.

Comment (ilmotta) [reply src/status_im/subs/wallet/activities.cljs:125]: The following code uses the idiom `#(compare %2 %1)`, this is a common way to pass a comparator to reverse the results of `sort-by`. With that, we can remove the `reverse` call, the subtraction workaround and the extra `sort-by` at the end, seems worth it. Tests still pass :)

```clojure
(defn activities-for-current
  [[activities current-viewing-account-address network-details]]
  (let [chain-id->network-name (update-vals (group-by :chain-id network-details)
                                            (comp :network-name first))
        address-activities     (->> (get activities current-viewing-account-address)
                                    (vals)
                                    (sort-by :timestamp #(compare %2 %1)))]
    (->> address-activities
         (keep #(process-activity-by-type chain-id->network-name %))
         (group-by (fn [{:keys [timestamp]}]
                     (datetime/timestamp->relative-short-date (* timestamp 1000))))
         (map (fn [[date activities]]
                {:title     date
                 :data      activities
                 :timestamp (:timestamp (last activities))})))))
```

File: src/status_im/subs/wallet/activities.cljs [hunk 2]
```diff
@@ -115,13 +115,13 @@
                                              (comp :network-name first))
          address-activities     (->> (get activities current-viewing-account-address)
                                      (vals)
-                                     (sort :timestamp))]
+                                     (sort-by :timestamp))]
      (->> address-activities
           (keep #(process-activity-by-type chain-id->network-name %))
           (group-by (fn [{:keys [timestamp]}]
                       (datetime/timestamp->relative-short-date (* timestamp 1000))))
```
Comment (ilmotta) [inline src/status_im/subs/wallet/activities.cljs:122]: It's probably fine, but just so you know, this is a _time bomb_ because the relative date depends on the concept of now and on the timezone. Here you can check how we use `with-redefs` to force the dynamic var `cljs-time.core/*ms-fn*` to point to a stable now.

https://github.com/status-im/status-mobile/blob/4b7c906df27fd3bdf90dd80048cff5f87b139514/src/utils/datetime_test.cljs#L145-L149

I remember seeing this type of problem in our pipeline and in general in my experience.

----

On a tangent, in some sense, one could say the subscription is stateful because the subscription output can vary based on the current time. In re-frame, for example, we inject the current timestamp via an interceptor to avoid this:

https://github.com/status-im/status-mobile/blob/4b7c906df27fd3bdf90dd80048cff5f87b139514/src/status_im/setup/interceptors.cljs#L12

But it's okay as is, just felt like mentioning it's not ideal.

**Review by ilmotta — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @mmilad75 !

Thanks for your PR!
Right now I am blocked to test it because of https://github.com/status-im/status-mobile/issues/20861
Hope it will be fixed soon and I check your fix.

File: src/status_im/subs/wallet/activities.cljs (hunk 1 above)
Comment (mmilad75) [reply src/status_im/subs/wallet/activities.cljs:125]: I also tried this method :( but still not working.

Comment (ilmotta) [reply src/status_im/subs/wallet/activities.cljs:125]: The tests are passing @mmilad75, I checked that for this snippet. In which way it's not working?

Comment (mmilad75) [reply src/status_im/subs/wallet/activities.cljs:125]: I tried `(sort-by :timestamp #(compare %2 %1))` but still the tests were failing 🤔

Comment (mmilad75) [reply src/status_im/subs/wallet/activities.cljs:125]: Oh. Got it now. I will try again

Comment (mmilad75) [reply src/status_im/subs/wallet/activities.cljs:125]: I checked this. There is still one issue with it. It's sorting activities inside each day, but the days are not sorted. `(sort-by (fn [{:keys [timestamp]}] (- timestamp)))` this line of code is still needed.

Comment (ilmotta) [reply src/status_im/subs/wallet/activities.cljs:125]: In that case, it would be good then to update the test to capture this requirement and falsify the snippet I shared, because the tests were passing. Well, it was all very interesting, thanks @mmilad75

Comment (mmilad75) [reply src/status_im/subs/wallet/activities.cljs:125]: @ilmotta I will do so. Thanks for checking man

**Comment by churik** [comment]
we can skip manual qa for this Pr given issues with displaying activity.
Thank you for attaching video
