### PR TITLE
fix(wallet)_: Fee mode and custom TX fields for non EIP 1559 TX

### LINKED ISSUE #22577: Predefined amount from the previous swap is set in Asset From field
follow up for https://github.com/status-im/status-mobile/pull/22417

**Steps:** 
1. Do any swap on BNB chain
2. Go to swap one more time

### Actual result:
Amount in Asset From is set from the previous swap

https://github.com/user-attachments/assets/5bb86484-de25-47e0-be4e-7fce16f4b553

**Expected result:**
Asset From field is empty

### Logs:
https://drive.google.com/file/d/1PZxIQqm2gPfXdnl_Y_dKhORoOQUu1ep0/view?usp=drive_link

### LINKED ISSUE #22578: Custom fee values are empty + est fee is the same for all options (normal/fast/urgent) on BSC chain
follow up for https://github.com/status-im/status-mobile/pull/22417
reproducible both on desktop and mobile

**Steps:** 

1. Go to swap/send review screen on BSC chain
2. Open transaction settings
3. Check est fee value for normal/fast/urgent options
4. Open custom settings
5. Check default values in custom settings

**Actual result:** 

1. Estimated fee value is the same for normal/fast/urgent options
2. Custom settings values are empty

**Video from mobile:**

https://github.com/user-attachments/assets/8c20e0ef-6510-4bdb-931c-6a9dff82c340

**Video from desktop:**

https://github.com/user-attachments/assets/b4b5b5ad-d0b4-4a8c-9511-4757a70b359d

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #22578
fixes #22577

status-go PR: https://github.com/status-im/status-go/pull/6582

## Summary
This PR:
 - fixes custom TX settings fields shown for non-EIP-1559 TX (Eg, BSC chain TX)
     - Shows Gas Price, Gas Amount, and Nonce for non-EIP-1559 TX
     - Shows Base Fee, Priority Fee, Gas Amount and Nonce for EIP-1559 TX
 - shows only Fast (medium) gas fee mode along with custom mode for non-EIP-1559 TX
 - fixes swap amount persisted after swap TX

### Platforms

- Android
- iOS

#### Functional

- wallet / transactions
- dapps / app browsing

## Steps to test

- Open Status
- Navigate to Wallet
- Prepare a non-EIP-1559 TX (BSC chain) and reach the TX confirmation page
- Navigate to TX settings
- Verify that only Fast Mode is shown along with custom mode
- Verify in Custom mode, the field Gas Price is shown instead of Base fee and Priority fee
- Perform a Swap TX and navigate back to Swap flow again
- Verify the amount from the last swap is not persisted 

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]
Nice work, LGTM.

File: src/status_im/contexts/wallet/common/transaction_settings/gas_price/view.cljs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+                                                                   current-gas-price})
+                                           :status    :default}))
+
+(defn view
+  []
+  (let [gas-price           (rf/sub [:wallet/tx-settings-gas-price])
+        current-gas-price   (rf/sub [:wallet/tx-settings-gas-price-route])
+        suggested-gas-price (rf/sub [:wallet/tx-settings-suggested-gas-price])
+        spectrum            {:low  (* 0.9 suggested-gas-price)
+                             :high (* 1.2 suggested-gas-price)}
```
Comment (mohsen-ghafouri) [inline src/status_im/contexts/wallet/common/transaction_settings/gas_price/view.cljs:36]: It would be great to have a const for these number to understand why we use these values (0.9, 1.2).

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/common/transaction_settings/gas_price/view.cljs:36]: We allow the user to go low (-10%) or high (+20%) of the suggested gas price. This logic is aligned with the Desktop. I will add a comment next to it. 👍

Comment (shivekkhurana) [reply src/status_im/contexts/wallet/common/transaction_settings/gas_price/view.cljs:36]: We can still move it to constants right ? 

`(def low-10%)` and `(def high-20%)`

**Review by shivekkhurana — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid Could you please update the current PR to point to the latest commit of the Status-go PR? Thank you!

**Comment by VolodLytvynenko** [comment]
@smohamedjavid @saledjenic thank you for PR. No issues from my side. PR can be merged

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - The TX settings fields for Status Network Sepolia have been updated.

Despite Status Network is EIP 1559 compatible, it will be fully gasless. 
But at the moment, its base fee is 0, it has a priority fee greater than 0.

We allow the user to edit only the priority fee for Status Network transactions. Please check.
One last check and we can merge this PR 🙏

**Comment by VolodLytvynenko** [comment]
@smohamedjavid thank you for the fixes. PR is ready to be merged

**Comment by smohamedjavid** [comment]
One last merge
