### PR TITLE
[14681] Make checkbox select contacts correctly in new chat flow

### LINKED ISSUE #14681: Chekbox new implementation not working properly
There is a new implementation for the `checkbox` component in `quo2.components.selectors.selectors` which has broken some functionalities in some places (add members screen). It seems that the `on-press` is not firing.

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14681
status: ready

### CODE REVIEW

File: src/status_im2/common/contact_list_item/view.cljs [hunk 1]
```diff
@@ -6,7 +6,8 @@
             [status-im2.contexts.chat.home.chat-list-item.style :as style]
             [utils.address :as utils.address]
             [utils.re-frame :as rf]
-            [reagent.core :as reagent]))
+            [reagent.core :as reagent]
+            [quo.react :as react]))
```
Comment (flexsurfer) [inline src/status_im2/common/contact_list_item/view.cljs]: quo can't be used in status-im2

File: src/status_im2/common/contact_list_item/view.cljs [hunk 2]
```diff
@@ -25,28 +26,36 @@
...
+                                    (if start-a-new-chat?
+                                      (on-toggle true @checked? public-key)
+                                      (if-not member?
+                                        (if selected
+                                          (rf/dispatch [:select-participant public-key true])
+                                          (rf/dispatch [:deselect-participant public-key true]))
+                                        (if selected
+                                          (rf/dispatch [:undo-deselect-member public-key true])
+                                          (rf/dispatch [:deselect-member public-key true])))))]
+    [:f>
```
Comment (flexsurfer) [inline src/status_im2/common/contact_list_item/view.cljs:40]: whats the point of using :f> here ?

File: src/status_im2/common/contact_list_item/view.cljs [hunk 3]
```diff
@@ -25,28 +26,36 @@
...
+       [rn/touchable-opacity
+        {:on-press #(rf/dispatch [:bottom-sheet/show-sheet
+                                  {:content (fn [] [actions/actions item extra-data])}])
+         :style    {:position :absolute
+                    :right    20}}
+        (if (= icon :options)
+          [quo/icon :i/options
+           {:size  20
+            :color (colors/theme-colors colors/neutral-50 colors/neutral-40)}]
+          (react/use-memo
```
Comment (flexsurfer) [inline src/status_im2/common/contact_list_item/view.cljs]: is it related to the issue? or its jut for performance ?

File: src/status_im2/common/contact_list_item/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im2/common/contact_list_item/view.cljs:40]: To use react hooks (use-memo)

File: src/status_im2/common/contact_list_item/view.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/common/contact_list_item/view.cljs]: Yes, It's related .. This is actually the solution .. To re-render the checkbox everytime it's updated

File: src/status_im2/common/contact_list_item/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/common/contact_list_item/view.cljs]: Done

File: src/status_im2/common/contact_list_item/view.cljs (hunk 3 above)
Comment (flexsurfer) [reply src/status_im2/common/contact_list_item/view.cljs]: are we sure it's a proper solution and not a hack ?

Comment (flexsurfer) [reply src/status_im2/common/contact_list_item/view.cljs]: still open question

Comment (ibrkhalil) [reply src/status_im2/common/contact_list_item/view.cljs]: Because of the current implementation of the check box, Yes I think it is proper

Comment (flexsurfer) [reply src/status_im2/common/contact_list_item/view.cljs]: could we fix checkbox ?

Comment (ibrkhalil) [reply src/status_im2/common/contact_list_item/view.cljs]: Okay :)

Comment (flexsurfer) [reply src/status_im2/common/contact_list_item/view.cljs]: nice ,thanks

File: src/status_im2/common/contact_list_item/view.cljs [hunk 4]
```diff
@@ -25,28 +25,36 @@
...
-                                  (on-toggle true @checked? public-key)
-                                  (if-not member?
-                                    (if selected
-                                      (rf/dispatch [:select-participant public-key true])
-                                      (rf/dispatch [:deselect-participant public-key true]))
-                                    (if selected
-                                      (rf/dispatch [:undo-deselect-member public-key true])
-                                      (rf/dispatch [:deselect-member public-key true])))))}])]))
+                                                  member?))
+        on-check                  (fn [selected]
```
Comment (J-Son89) [inline src/status_im2/common/contact_list_item/view.cljs]: it can be `selected?` ??

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/common/contact_list_item/view.cljs (hunk 3 above)
Comment (J-Son89) [reply src/status_im2/common/contact_list_item/view.cljs]: what's the issue with checkbox?? and yes let's fix the problem at the source :)

**Review by flexsurfer — COMMENTED** [review]
fix checkbox

**Review by flexsurfer — CHANGES_REQUESTED** [review]
fix checkbox

File: src/status_im2/common/contact_list_item/view.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/status_im2/common/contact_list_item/view.cljs]: Done

File: src/status_im2/common/contact_list_item/view.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/common/contact_list_item/view.cljs]: When clicking a contact, the checkbox doesn't get selected (Although the selection logic executes) .. You have to click really accurately on the checkbox

File: src/quo2/components/selectors/selectors.cljs [hunk 5]
```diff
@@ -70,45 +70,44 @@
 
 
 (defn checkbox
-  [{:keys [default-checked?]}]
+  [{:keys [default-checked? on-change disabled? blurred-background? container-style]}]
   (let [checked? (reagent/atom (or default-checked? false))]
-    (fn [{:keys [on-change disabled? blurred-background? container-style]}]
```
Comment (ibrkhalil) [inline src/quo2/components/selectors/selectors.cljs:75]: The main issue was returning a function instead of hiccup

**Comment by ibrkhalil** [comment]
> fix checkbox

Found what the issue was, Returning a function instead of hiccup for checkbox
we might need to do the same for other selectors

File: src/quo2/components/selectors/selectors.cljs (hunk 5 above)
Comment (flexsurfer) [reply src/quo2/components/selectors/selectors.cljs:75]: no, its intentional, default-checked? and checked? should be outside of render function, it seems like you're trying to use default-checked? for changing value which is wrong

Comment (ibrkhalil) [reply src/quo2/components/selectors/selectors.cljs:75]: We can make a functional component if we want to return a function
```clj
(defn checkbox
  [{:keys [default-checked?]}]
  (let [checked? (reagent/atom (or default-checked? false))]
    [:f>
     (fn [{:keys [on-change disabled? blurred-background? container-style]}]
       [rn/touchable-without-feedback
        {:on-press (handle-press disabled? on-change checked?)}
        [rn/view
         {:style (merge
                  container-style
                  {:height 20
                   :width  20})}
         [rn/view
          {:style               {:flex             1
                                 :border-radius    6
                                 :border-width     (if @checked? 0 1)
                                 :background-color (cond
                                                     @checked?
                                                     (get-color @checked? disabled? blurred-background?)
                                                     blurred-background?
                                                     (colors/theme-colors
                                                      colors/white-opa-5
                                                      colors/white-opa-10)
                                                     :else
                                                     (colors/theme-colors
                                                      colors/white
                                                      colors/neutral-80-opa-40))
                                 :border-color     (if @checked?
                                                     :none
                                                     (get-color @checked? disabled? blurred-background?))}
           :accessibility-label (str "checkbox-" (if @checked? "on" "off"))
           :accessibility-role  :checkbox
           :testID              "checkbox-component"}
          (when @checked?
            [rn/view
             {:style
              {:height 20
               :width  20}}
             [icons/icon :i/check-small
              {:size  20
               :color colors/white}]])]]])]))
```

Comment (flexsurfer) [reply src/quo2/components/selectors/selectors.cljs:75]: this is the same, you have to return a render function not a component, it doesn't matter functional component or hiccup

Comment (flexsurfer) [reply src/quo2/components/selectors/selectors.cljs:75]: so checkbox implementation is fine, problem in usage

**Comment by pavloburykh** [comment]
### QA NOTES: 

In scope of this PR please make sure that [ISSUE 2](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402250221) and [ISSUE 3](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402265764) are fixed.

File: src/quo2/components/selectors/selectors.cljs (hunk 5 above)
Comment (ibrkhalil) [reply src/quo2/components/selectors/selectors.cljs:75]: Kindly take a look

File: src/quo2/components/selectors/selectors.cljs [hunk 6]
```diff
@@ -68,46 +69,51 @@
...
-            :width  20}}
-          [icons/icon :i/check-small
-           {:size  20
-            :color colors/white}]])]]]))
+          {:style (merge
+                   container-style
+                   {:height 20
+                    :width  20})}
+          [rn/view
+           {:style               {:flex             1
```
Comment (flexsurfer) [inline src/quo2/components/selectors/selectors.cljs]: would be cool to move styles to style ns, i know not related but as we touch this part anyway

File: src/status_im2/common/contact_list_item/view.cljs [hunk 7]
```diff
@@ -47,6 +50,7 @@
             :color (colors/theme-colors colors/neutral-50 colors/neutral-40)}]
           [quo/checkbox
            {:default-checked?    @checked?
```
Comment (flexsurfer) [inline src/status_im2/common/contact_list_item/view.cljs]: i think no need to use :default-checked? because it will be replaced by :checked? anyway in the compoennt

File: src/quo2/components/selectors/selectors.cljs [hunk 8]
```diff
@@ -34,10 +33,12 @@
 
 (defn checkbox-prefill
   [{:keys [default-checked?]}]
-  (let [checked? (reagent/atom (or default-checked? false))]
-    (fn [{:keys [on-change disabled? blurred-background? container-style]}]
+  (let [internal-checked? (reagent/atom (or default-checked? false))]
+    (fn [{:keys [on-change disabled? blurred-background? container-style checked?]}]
+      (when (and (not (nil? checked?)) (not= @internal-checked? checked?))
+        (reset! internal-checked? checked?))
       [rn/touchable-without-feedback
```
Comment (flexsurfer) [inline src/quo2/components/selectors/selectors.cljs]: (let [checked? (or checked? @internal-checked?)]

File: src/quo2/components/selectors/selectors.cljs [hunk 9]
```diff
@@ -139,25 +145,27 @@
 
 (defn radio
   [{:keys [default-checked?]}]
-  (let [checked? (reagent/atom (or default-checked? false))]
-    (fn [{:keys [on-change disabled? blurred-background? container-style]}]
+  (let [internal-checked? (reagent/atom (or default-checked? false))]
+    (fn [{:keys [on-change disabled? blurred-background? container-style checked?]}]
+      (when (and (not (nil? checked?)) (not= @internal-checked? checked?))
+        (reset! internal-checked? checked?))
       [rn/touchable-without-feedback
```
Comment (flexsurfer) [inline src/quo2/components/selectors/selectors.cljs]: (let [checked? (or checked? @internal-checked?)]

File: src/quo2/components/selectors/selectors.cljs [hunk 10]
```diff
@@ -166,33 +174,35 @@
...
 
 (defn toggle
   [{:keys [default-checked?]}]
-  (let [checked? (reagent/atom (or default-checked? false))]
-    (fn [{:keys [on-change disabled? blurred-background? container-style]}]
+  (let [internal-checked? (reagent/atom (or default-checked? false))]
+    (fn [{:keys [on-change disabled? blurred-background? container-style checked?]}]
+      (when (and (not (nil? checked?)) (not= @internal-checked? checked?))
+        (reset! internal-checked? checked?))
       [rn/touchable-without-feedback
```
Comment (flexsurfer) [inline src/quo2/components/selectors/selectors.cljs]: (let [checked? (or checked? @internal-checked?)]

File: src/quo2/components/selectors/selectors.cljs (hunk 8 above)
Comment (ibrkhalil) [reply src/quo2/components/selectors/selectors.cljs]: Done

File: src/quo2/components/selectors/selectors.cljs (hunk 10 above)
Comment (ibrkhalil) [reply src/quo2/components/selectors/selectors.cljs]: Done

**Review by flexsurfer — APPROVED** [review]

**Comment by ibrkhalil** [comment]
> ### QA NOTES:
> In scope of this PR please make sure that [ISSUE 2](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402250221) and [ISSUE 3](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1402265764) are fixed.

Sorry Pavlo, I forgot and merged this PR after testing it thoroughly .. Kindly take a look and tell me what you think

**Comment by pavloburykh** [comment]
> Sorry Pavlo, I forgot and merged this PR after testing it thoroughly .. Kindly take a look and tell me what you think

Hi @ibrkhalil ! Got a [bug](https://github.com/status-im/status-mobile/pull/14791#issuecomment-1404879604) that might be related to this PR. I have logged it in PR with bottom sheets issues but I can log it as separate issue as it is not related to that PR.
