### PR TITLE
No browsing history kept on iOS [#5078]

### LINKED ISSUE #5078: No browsing history kept for particular Dapps (CryptoKitties,CryptoFighters,CryptoStrikers etc) on iOS
***Type***: Bug

***Summary***: Status app browser on iOS does not track and keep the browsing history in particular Dapps. 
**Note:** It's all fine on Android app browser. Also there are similar Dapps in status curated list which are fine on iOS.
See steps to reproduce for CryptoKitties (where history is not tracked) and Etheremon dapp (where history is tracked and kept fine).

#### Expected behavior
Browsing history is tracked and saved when I navigate through CryptoKitties in status app browser on iOS

#### Actual behavior
No browsing history tracked and kept for particular Dapps from the Status curated Dapp list. List of "affected" Dapps (comparing to the Metamask's behavior and Android app browser):
LocalEthereum, CryptoCribs, OpenSea, NameBazaar, The Bounties Network, CryptoKitties, CryptoFighters, Etherbots, CryptoStrikers, Cent, Purrbook, Hexel, ETHLend, SmartZ

### Reproduction

- Open Status on iOS and create an account
- Navigate to `Open Dapps` -> `CryptoKitties` -> `Open`
- from CryptoKitties homepage navigate to Marketplace -> Page 2 -> Page 3
- Check if the browser history kept and you are able to navigate back via `Back` browser button
- _(Optional)_ Repeat all above for Etheremon Dapp to see that behavior is correct there.

### Additional Information
* Status version: Develop 0.9.21 (6168) node a339d7e
* Operating System: iOS

#### Logs

TF session: https://app.testfairy.com/projects/4803590-status/builds/8517663/sessions/4395646328/?accessToken=PDHFz1AiCyKSkL5dhoHxJ7ZyylA

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #5078

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/browser/events.cljs [hunk 1]
```diff
@@ -10,78 +9,95 @@
...
+    (assoc-in (update-browser-fx cofx browser)
+              [:db :browser/options :dont-store-history-on-nav-change?]
+              false)
+
+    :else
+    (let [history-index (:history-index browser)
+          history       (:history browser)
+          history-url   (try (nth history history-index) (catch js/Error _))
+          new-history   (if (not= history-url url)
+                          (conj (subvec history 0 (inc history-index))
```
Comment (jeluard) [inline src/status_im/ui/screens/browser/events.cljs]: Worth a separate fn with proper name?

File: src/status_im/ui/screens/browser/events.cljs [hunk 2]
```diff
@@ -10,78 +9,95 @@
...
+     (update-browser-and-navigate cofx browser))))
+
+(handlers/register-handler-fx
+ :open-url-in-browser
+ [re-frame/trim-v]
+ (fn [cofx [url]]
+   (let [browser {:browser-id    (random/id)
+                  :name          (i18n/label :t/browser)
+                  :history-index 0
+                  :history       [(http/normalize-and-decode-url url)]}]
```
Comment (jeluard) [inline src/status_im/ui/screens/browser/events.cljs:50]: Some parts in common with code above. Introduce a fn?

File: src/status_im/ui/screens/browser/views.cljs [hunk 3]
```diff
@@ -64,6 +63,13 @@
    [react/view styles/web-view-loading
     [components/activity-indicator {:animating true}]]))
 
+(defn on-bridge-message [message browser]
+  (let [{:strs [type navState]} (js->clj (.parse js/JSON message))
+        {:strs [url title]} navState]
```
Comment (jeluard) [inline src/status_im/ui/screens/browser/views.cljs]: `title` not used?

File: src/status_im/ui/screens/browser/views.cljs [hunk 4]
```diff
@@ -74,59 +80,62 @@
...
+          {:ref                                   #(reset! webview %)
+           :source                                {:uri url}
+           :java-script-enabled                   true
+           :bounces                               false
+           :local-storage-enabled                 true
+           :start-in-loading-state                true
+           :render-error                          web-view-error
+           :render-loading                        web-view-loading
+           :on-bridge-message                     #(on-bridge-message % browser)
+           ;:on-navigation-state-change            #(on-navigation-change % browser)
```
Comment (jeluard) [inline src/status_im/ui/screens/browser/views.cljs]: Remove?

File: test/cljs/status_im/test/models/browser_history.cljs [hunk 5]
```diff
@@ -1,117 +0,0 @@
-(ns status-im.test.models.browser-history
```
Comment (jeluard) [inline test/cljs/status_im/test/models/browser_history.cljs:1]: No more tests?

**Review by jeluard — CHANGES_REQUESTED** [review]

File: test/cljs/status_im/test/models/browser_history.cljs (hunk 5 above)
Comment (flexsurfer) [reply test/cljs/status_im/test/models/browser_history.cljs:1]: yeah no model, and now it's super simple code, nothing to test

Comment (cammellos) [reply test/cljs/status_im/test/models/browser_history.cljs:1]: @flexsurfer there's much to test `browser-back` `browser-forward` `update-browser-history-tx`, if we don't start adding tests to the codebase (instead of removing them :) ) it makes it harder for everyone to modify and improve it

**Review by cammellos — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/browser/events.cljs [hunk 6]
```diff
@@ -95,3 +111,21 @@
  (fn [{:keys [db]} [browser-id]]
    {:db            (update-in db [:browser/browsers] dissoc browser-id)
     :data-store/tx [(browser-store/remove-browser-tx browser-id)]}))
+
+(handlers/register-handler-fx
+ :browser-nav-back
+ [re-frame/trim-v]
+ (fn [cofx [browser]]
+   (let [back-index (:history-index browser)]
+     (when (not (zero? back-index))
```
Comment (rasom) [inline src/status_im/ui/screens/browser/events.cljs]: `(when (pos?`?

File: src/status_im/ui/screens/browser/events.cljs [hunk 7]
```diff
@@ -95,3 +111,21 @@
...
+       (assoc-in (update-browser-fx cofx (assoc browser :history-index (dec back-index)))
+                 [:db :browser/options :dont-store-history-on-nav-change?] true)))))
+
+(handlers/register-handler-fx
+ :browser-nav-forward
+ [re-frame/trim-v]
+ (fn [cofx [browser]]
+   (let [forward-index (:history-index browser)]
```
Comment (rasom) [inline src/status_im/ui/screens/browser/events.cljs]: we could destruct browser at params declaration, not a big deal though

File: src/status_im/ui/screens/browser/views.cljs [hunk 8]
```diff
@@ -64,6 +63,13 @@
    [react/view styles/web-view-loading
     [components/activity-indicator {:animating true}]]))
 
+(defn on-bridge-message [message browser]
+  (let [{:strs [type navState]} (js->clj (.parse js/JSON message))
+        {:strs [url title]} navState]
+    (when (= type "navStateChange")
+      (when (not= "about:blank" url)
```
Comment (rasom) [inline src/status_im/ui/screens/browser/views.cljs]: might be `and` instead of the second `when`

File: src/status_im/ui/screens/browser/views.cljs [hunk 9]
```diff
@@ -74,59 +80,62 @@
...
-      [react/touchable-highlight {:on-press            #(browser-history/forward browser)
-                                  :disabled            (not (browser-history/can-go-forward? browser))
-                                  :style               (merge styles/forward-button (if (not (browser-history/can-go-forward? browser)) styles/disabled-button))
-                                  :accessibility-label :next-page-button}
-       [react/view
-        [vector-icons/icon :icons/arrow-right]]]]
-     (when-not dapp?
-       [tooltip/bottom-tooltip-info
-        (i18n/label :t/browser-warning)])]))
+    (let [can-go-back?    (not (zero? history-index))
```
Comment (rasom) [inline src/status_im/ui/screens/browser/views.cljs]: again, can we use `pos?` here? or index can be negative?

File: src/status_im/ui/screens/browser/views.cljs [hunk 10]
```diff
@@ -74,59 +80,62 @@
...
+        [react/touchable-highlight {:on-press            #(re-frame/dispatch [:browser-nav-back browser])
+                                    :disabled            (not can-go-back?)
+                                    :style               (when (not can-go-back?) styles/disabled-button)
+                                    :accessibility-label :previou-page-button}
+         [react/view
+          [vector-icons/icon :icons/arrow-left]]]
+        [react/touchable-highlight {:on-press            #(re-frame/dispatch [:browser-nav-forward browser])
+                                    :disabled            (not can-go-forward?)
+                                    :style               (merge styles/forward-button
+                                                                (when (not can-go-forward?) styles/disabled-button))
```
Comment (rasom) [inline src/status_im/ui/screens/browser/views.cljs]: `when-not`

File: src/status_im/ui/screens/browser/events.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/browser/events.cljs]: too many params  and too small function don't worth it from my pov

File: src/status_im/ui/screens/browser/events.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/browser/events.cljs:50]: do you mean for creating new browser map?

File: src/status_im/ui/screens/browser/views.cljs (hunk 8 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/browser/views.cljs]: there will be more types, will be condition

File: src/status_im/ui/screens/browser/events.cljs (hunk 2 above)
Comment (jeluard) [reply src/status_im/ui/screens/browser/events.cljs:50]: Right

File: src/status_im/ui/screens/browser/events.cljs (hunk 1 above)
Comment (jeluard) [reply src/status_im/ui/screens/browser/events.cljs]: Small fns are never an issue :) Mostly useful to understand what this thing is doing. Or maybe a small comment?

**Comment by flexsurfer** [comment]
@jeluard @cammellos done!

**Review by cammellos — APPROVED** [review]
@flexsurfer thanks!

**Review by jeluard — APPROVED** [review]

**Comment by Serhy** [comment]
Builds apk https://i.diawi.com/qyRJgF and ipa https://i.diawi.com/CNoPMe has been tested on iOS (11.2.5) and Andorid (6.0, 7.0)
Those Dapps which failed to track history before (outlines in the respective issue) are working now, yes (with one issue though - see the (II) item below). But major regressions introduced at the same time:

@flexsurfer, few issues we faced here:

I) Those Dapps which kept the browsing history fine on iOS before (e.g. Etheremons, CryptoPunks) AND webpages (like google.com / wikipedia.org) - does not keep browsing history not only on iOS but on Android as well now.
To reproduce: 
1) Navigate to google.com -> search something -> navigat to any of the links avaialble on page and check if Back button active
2) Navigate to CryptoPunks -> Writing -> check whether browser `Back' button is active

II) No browsing history cut off when user navigates to any link from the middle of his browsing history. It becomes a bit confusing for where browser navigates then. See the scenario:

1) Open status and create an account
2) Navigate to Open Dapps`  -> `CryptoKitties` -> `Open`
3) From CryptoKitties home screen navigate to Marketplace (you appear on Page #1)
4) Scroll down and navigate to Page 2 -> then Page 3 -> then Page 4 - then Page 5 (Note: so at this point 6 records in the browsing history)
5) Tap browser `Back` button 
6)Tap browser `Back` button again (you appear on 3rd page)
7) Tap on any Kitty label to navigate to its details screen
**Actual result:** Fwd browser button is available. 
**Expected result:** Fwd browser button is disabled. Browsing history with all links used after 3rd CryptoKitties page in the current example is flushed.

8) Tap `->` Fwd browser button now
*Actual result:* 4th page appears
9) Tap `<-` Back browser button
*Actual result:* 3rd page appears

III) On the Home page screen any Dapp/web page has instead of the actual last visited URL the 'Dapp' labels
screen shot 2018-07-09 at 20 05 59


TF session showing all three issues above: https://app.testfairy.com/projects/4803622-status/builds/8518521/sessions/4395906530/?accessToken=vP/BJVyUO/qs6g8pUdSj7vkIwc4

**Comment by flexsurfer** [comment]
thanks @Serhy , fixed

**Comment by Serhy** [comment]
@flexsurfer latest changes look really good! We keep the history now on iOS and Android app browsers for Dapps/websites and I was able to navigate through history with Back/Fwd browser buttons! 

However, there are issues we need to look at:
1) Upgrading on the version with current changes flushes the history of previously used Dapp/Browser items. But the Dapp/Browser elements are kept on Home screen. Navigating to Dapp with such empty history leads to error followed by app crash:
**Steps to reproduce:**
* Install the 0.9.22 release app and create new account
* Navigate to Open Dapp -> CryptoKitties -> Open
* Upgrade to the app version (Android build https://i.diawi.com/ETn3YX / iOS build https://i.diawi.com/j6hSws)
* Log in to the same account. (Note: CryptoKitties Dapp item is on Home screen) 
* Tap on CryptoKitties from Home screen
**Actual result:**  `TypeError: re-find must match against a string` error appears.

screen shot 2018-07-11 at 17 06 57

TF session from 01:00 https://app.testfairy.com/projects/4803622-status/builds/8521278/sessions/4396102337/?accessToken=ayUtWG7xTPNwdt5g8TCNi1zkS8g

2) On Android app browser, there is a weird behavior with 'OpenSea' dapp: it keep return user back to particular crypto asset detail screen if it has been navigated to at least once. Please, see steps to reproduce:
* Open Status on Android and create new account
* Navigate to `Open Dapps` -> `OpenSea` -> `Open`
* Tap 'Explore the sea' button (You'll land on summary screen of erc721 items)
* Tap on the first item you see
* Tap `Back` app browser button and wait up to 10-15 seconds
TF session https://app.testfairy.com/projects/4803622-status/builds/8521278/sessions/4396102794/?accessToken=bHaMZqWOJmVZrPNBoxuGu2NMnKs

Note: iOS app browser it looks good here. On latest nightly I could not reproduce the same issue with the steps above (no auto-return back when I don't touch anything), but browser history for OpenSea looks a bit weird on nightly develop build as well - just need to navigate between summary/detail screens of this Dapp a bit more. (I'm OK if consider to fix it separately off this PR changes)

<blockquote><div><strong><a href="https://i.diawi.com/ETn3YX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/j6hSws">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8521278/sessions/4396102337/?accessToken=ayUtWG7xTPNwdt5g8TCNi1zkS8g">TestFairy: Status 0.9.23 (6192) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8521278/sessions/4396102794/?accessToken=bHaMZqWOJmVZrPNBoxuGu2NMnKs">TestFairy: Status 0.9.23 (6192) @2018</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
@Serhy fixed

**Comment by Serhy** [comment]
All above issues are fixed!
Users on iOS and Android are able now to navigate in Status withing Dapps and we keep the browsing history. After re-login / app restart - we keep browsing history as well!

Thanks a lot @flexsurfer! Lets merge!
