### PR TITLE
Fix drawer message according to desings

### LINKED ISSUE #19053: Fix message from long-press bottom sheet
# Bug Report
Fix issues with the message component when shown above the bottom sheet after long-press, based on the [design feedback](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=8065:58901&mode=design#645028150)

- fix spacings
- remove identicon
- remove emojis from message

### LINKED ISSUE #19164: Message preview issue with long-tapped messages
### Steps:
1. Send a short text message to the chat
2. Send a long text message to the chat
3. Long tap both messages to observe the preview

### Actual result:
- The message preview is not shown for the short text message when long-tapped.
- The message preview overlaps the status bar for the long message when long-tapped.

https://github.com/status-im/status-mobile/assets/52490791/1acc3c69-1d16-4344-bc1b-294f10094f55

### Expected result:
Message preview is shown and does not overlap the status bar
- In case if text message is long, then preview message has ability to be scrolled

image

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=2847-340020&mode=design&t=Fk3u6oBtYJeOESRM-0

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19053
fixes #19164

### Summary

Fix issues with the message component when shown above the bottom sheet after long-press, based on the [design feedback](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=8065:58901&mode=design#645028150)

- fixed bottom-sheet not showing the selected-item
- fix spacings
- remove identicon
- remove emojis from message

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Open chat
- Long press on a message

### Before and after screenshots comparison

<div style="display: flex; flex-direction: row">

</div>
status: ready

### CODE REVIEW

File: src/status_im/common/bottom_sheet/view.cljs [hunk 1]
```diff
@@ -62,24 +62,33 @@
            gradient-cover? customization-color hide-handle? blur-radius]
     :or   {border-radius 12}}]
   (let [theme                             (quo.theme/use-theme-value)
-        sheet-height                      (rn/use-ref-atom 0)
-        item-height                       (rn/use-ref-atom 0)
+        [sheet-height set-sheet-height]   (rn/use-state 0)
+        handle-sheet-height               (rn/use-callback (fn [e]
+                                                             (when (= sheet-height 0)
+                                                               (set-sheet-height
+                                                                (.-nativeEvent.layout.height ^js e)))))
```
Comment (clauxx) [inline src/status_im/common/bottom_sheet/view.cljs]: @flexsurfer we should be using state here (and below), otherwise it won't re-render the `selected-item` will not be visible.

Comment (flexsurfer) [reply src/status_im/common/bottom_sheet/view.cljs]: but then you need to pass it as dep for `use-callback`

**Review by flexsurfer — APPROVED** [review]
nice!

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs [hunk 2]
```diff
@@ -75,11 +75,11 @@
...
-  (let [[primary-name _]     (rf/sub [:contacts/contact-two-names-by-identity chat-id])
-        contact              (rf/sub [:contacts/contact-by-address chat-id])
-        photo-path           (when (seq (:images contact)) (rf/sub [:chats/photo-path chat-id]))
-        customization-color  (rf/sub [:profile/customization-color])
-        {:keys [public-key]} (rf/sub [:profile/profile])]
+  (let [[primary-name _]    (rf/sub [:contacts/contact-two-names-by-identity chat-id])
+        contact             (rf/sub [:contacts/contact-by-address chat-id])
+        photo-path          (when (seq (:images contact)) (rf/sub [:chats/photo-path chat-id]))
+        customization-color (rf/sub [:profile/customization-color])
+        public-key          (rf/sub [:multiaccount/public-key])]
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/messages/content/view.cljs]: I thought we moved away from :multiaccount,  right @flexsurfer ?

Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: i was meaning to ask why some subs in the same ns are called both profile and multiaccount. `:multiaccount/public-key` is still heavily used though.

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: cc @alwx

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: idk probably leftovers, we shouldn't use `:multiaccount` any longer

Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: there's 22 uses of `:multiaccount/public-key` and hundreds of `:multiaccount/...`, so would be best to not do it in this pr imo

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: yes, it should be a separate refactoring

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: but we shouldn't revert any change, @clauxx why `:profile/profile` changed to  `:multiaccount/public-key` in this PR?

Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: Because there's no need to subscribe to the entire profile when we only need the `public-key` from it. We use a layer-3 subscription instead to avoid re-renders when something unrelated changes in `:profile/profile`.

I can add a `:profile/public-key` sub or can leave it until the `:multiaccount` one is renamed, either works for me.

Comment (flexsurfer) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: as you're changing this i would say better to do it properly then, pls add `:profile/public-key` sub, thank you

Comment (clauxx) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: done. Also added a small comment that `:multiaccount/public-key` is deprecated.

**Review by flexsurfer — APPROVED** [review]
thank you

File: src/status_im/subs/profile.cljs [hunk 3]
```diff
@@ -81,12 +81,20 @@
...
+;; DEPRECATED
+;; use `:profile/public-key` instead
 (re-frame/reg-sub
  :multiaccount/public-key
  :<- [:profile/profile]
  (fn [{:keys [public-key]}]
    public-key))
 
+(re-frame/reg-sub
+ :profile/public-key
```
Comment (J-Son89) [inline src/status_im/subs/profile.cljs:94]: Should we add a corresponding test for this?

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/subs/profile.cljs (hunk 3 above)
Comment (clauxx) [reply src/status_im/subs/profile.cljs:94]: done

**Comment by pavloburykh** [comment]
@clauxx thanx for the PR. Could you please rebase and resolve existing conflicts so we proceed with testing? Thank you.

**Comment by clauxx** [comment]
@pavloburykh the conflicts are fixed :+1:

**Comment by flexsurfer** [comment]
added https://github.com/status-im/status-mobile/issues/19164 as fixed

**Comment by pavloburykh** [comment]
> @pavloburykh the conflicts are fixed 👍

@clauxx thank you! Could you please also take a look why integration tests are failing https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-19056/10/consoleText ?

**Comment by clauxx** [comment]
> > @pavloburykh the conflicts are fixed 👍
> 
> @clauxx thank you! Could you please also take a look why integration tests are failing https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-19056/10/consoleText ?

Sometimes the tests job seems to times out. I re-ran it and it passed now.

**Comment by VolodLytvynenko** [comment]
Hey @clauxx thank you for PR. Take a look please the found issue:

## ISSUE 1: [IOS] Lack of spacing between message preview and drawer
### Steps:
1. Send long text message
2. Long tap the message
3. Check the space between the drawer and message preview

### Actual result:
There is no spacing between the message preview and the drawer.

image

### Expected result:
The space is shown between the message preview and drawer
image

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=2847-340020&mode=design&t=mBvFqDQNMee7Hoh8-0

**Comment by clauxx** [comment]
@VolodLytvynenko if you look at this [design](https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=5713-623970&mode=design&t=IWofEoiArX6inSkG-4) for instance, when the message doesn't fit it goes below the bottom sheet.

**Comment by VolodLytvynenko** [comment]
Got it @clauxx , thank you. Now I see. The current case occurs only when a user taps their own message and only when using an iOS device.

 However there is opposite thing , in the case of Android or when an iOS user long-taps a long message from other users, the spacing is shown.

Could you fix it please?

## ISSUE: Spacing between message preview and drawer is shown on Android or when a user on iOS long taps long text messages of other users.

### Steps:
1. `User A` Sends long text message
2. `User B`Long taps the message of `User A`
3. Check the space between the drawer and message preview

### Actual result:
- Spacing is shown between the message preview and the drawer for Android devices when any long message is long-tapped.
- Spacing is shown between the message preview and the drawer for iOS devices when a user long-taps a message of other users.

IOS record 

https://github.com/status-im/status-mobile/assets/52490791/ce556374-404b-4003-b3a1-411226f78784

Android record

https://github.com/status-im/status-mobile/assets/52490791/812bbe9d-97f9-4698-8a61-9fac8e0e6a4e

### Expected result:
No spacing is shown when  long text message is long tapped
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=5713-623970&mode=design&t=jnAqgK6WEgBU1Y6a-0

**Comment by clauxx** [comment]
@VolodLytvynenko well I think the reason for that is that own messages have more options in the menu and less space for the message, so there's no gap if the message doesn't fit. It is basically dependent on the available space for the message. In the android example you showed, the screen is longer so both fit together with the space.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko well I think the reason for that is that own messages have more options in the menu and less space for the message, so there's no gap if the message doesn't fit. It is basically dependent on the available space for the message. In the android example you showed, the screen is longer so both fit together with the space.

Hi @clauxx thank you for clarification. No other additional issues from my side. PR can be merged. Thanx!

**Comment by clauxx** [comment]
@Francesca-G can you have a look as well please?

**Review by Francesca-G — COMMENTED** [review]
Here's the [review](https://www.figma.com/file/GPBPvV3LacCuNoknEQkqCi/Review-Posts-%26-Attachments-%2F-Mobile?type=design&node-id=1%3A26739&mode=design&t=fr1258J7Xmx6DFxY-1) frame :)

**Comment by clauxx** [comment]
@Francesca-G please have a look again

**Review by Francesca-G — APPROVED** [review]
Looks good ✨

**Review by alwx — APPROVED** [review]
