### PR TITLE
[#21902] Reimplement community overview

### LINKED ISSUE #21902: Communities - UI artifacts in the community header
# Bug Report

## Problem 

Before Status 2.32.0, opening a community wasn't exactly smooth, but in 2.32.0 I always see a noticeable side-effect in the community header when opening it. This is quite distracting.

#### Expected behavior

There should be no artifacts in the community header. The opening animation of a community doesn't necessarily need to be perfectly smooth at 60fps either. This issue is about the weirdness going on in the community header.

#### Actual behavior

https://github.com/user-attachments/assets/5f4ee041-5130-48a2-a24f-5d2b0d350abb

### Reproduction

1. Open any community.

### Additional Information

- Status version: 2.32.0 
- Operating System: iOS 18.1, iPhone 14 Pro Max (maybe the same problem exists on some Android models, but I didn't check)

### LINKED ISSUE #22236: Multiple bugs in the community overview page
# Bug Report

## Problem 

The community overview lacks of some features and its performance can be improved.

Some of the issues found so far are:

### 2. Missing stats in the expanded version

https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=15967-248458&m=dev

### 4. Performance: re-renderings even while scrolling the page

https://github.com/user-attachments/assets/6c3d7abd-a365-4e0e-af75-0b15577c2a0f

#### Expected behavior

Comply with the expected features in figma and improve the performance

### Reproduction

- Just open a community

### Additional Information

- Operating System: Android, iOS

### Notes

These have been found while investigating
- #21902
So the plan is to address the issues listed (and the new found ones, if there are more) in this screen altogether

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #21902 
fixes #22236

## Summary

This PR re implements the community overview page since it had multiple bugs (from design impl, to code and performance).

figma: https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=10275-397889&m=dev

Test on Emulator:

https://github.com/user-attachments/assets/9bc62404-220e-4079-8f6a-9826b8237e7a

iOS device:

https://github.com/user-attachments/assets/f7631855-6a06-46fb-8986-a05f647e663d

Android device:

https://github.com/user-attachments/assets/2eebb013-4d71-4045-ba9d-b358efaff3f2

## Testing notes

Please visit different communities on different devices to make sure everything looks ok. It took more time to make sure the UI looks fine on different devices with different configurations.

Please test all previous features are still working at least as before. I'd highly appreciate any bug report on it.

### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Comment by ulisesmac** [comment]
Please ignore the changes in ddb8c534da9ac5336c837c42637505b1a6b230d7, this was built on top of the solution for 
- https://github.com/status-im/status-mobile/pull/22226
for convenience.

You can get the main diff at  b65d2a40be26c7309bb9b620799444cd623223e2

File: src/status_im/contexts/communities/overview/view.cljs [hunk 1]
```diff
@@ -100,240 +41,420 @@
...
-    (assoc :on-press      (when joined-or-spectated
-                            (fn []
-                              (rf/dispatch [:dismiss-keyboard])
-                              (debounce/throttle-and-dispatch
-                               [:communities/navigate-to-community-chat (str community-id id)]
-                               1000)))
-           :on-long-press #(rf/dispatch
-                            [:show-bottom-sheet
-                             {:content (fn []
-                                         [chat-actions/actions chat false])}])
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/overview/view.cljs:194]: This was defined but never used, later this value is completely ignored

File: src/status_im/contexts/communities/overview/view.cljs [hunk 2]
```diff
@@ -100,240 +41,420 @@
...
-                                          (reset! first-channel-height height))]
-    (fn [id joined name images]
-      (let [theme                 (quo.theme/use-theme)
-            cover                 {:uri (get-in images [:banner :uri])}
-            logo                  {:uri (get-in images [:large :uri])}
-            collapsed?            (and initial-joined? joined)
-            first-category-height (->> @categories-heights
-                                       vals
-                                       (apply min)
-                                       (+ @first-channel-height))
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/overview/view.cljs:301]: This returns a `NaN`, `@categories-heights` is a map of `{id(string) -> maps}`, the logic here was completely lost maybe due to multiple refactors

File: src/status_im/contexts/communities/overview/view.cljs [hunk 3]
```diff
@@ -359,16 +480,12 @@
...
   [id]
-  (let [id (or id (rf/sub [:get-screen-params :community-overview]))]
+  (let [community-id    (or id (rf/sub [:get-screen-params :community-overview]))
+        community       (rf/sub [:communities/community community-id])
+        start-expanded? (not (:joined community))]
     [rn/view {:style style/community-overview-container}
-     [community-card-page-view id]]))
+     (if community
+       [community-overview community-id start-expanded?]
+       [community-fetching-placeholder community-id])]))
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/overview/view.cljs]: It's a lot of code, but hopefully now it's easier to read since it's divided in multiple separate components, any code readability suggestion is welcome

File: src/status_im/subs/chats.cljs [hunk 4]
```diff
@@ -1,6 +1,7 @@
 (ns status-im.subs.chats
```
Comment (ulisesmac) [inline src/status_im/subs/chats.cljs]: Please ignore

File: src/status_im/contexts/communities/events.cljs [hunk 5]
```diff
@@ -20,8 +20,7 @@
 (defn handle-community
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/events.cljs]: Ignore this one too

**Comment by du82** [comment]
This is really good looking, a much needed improvement!

I just wish there was basic file sharing ability and voice messages to make the chat features actually competitive

File: src/status_im/contexts/communities/overview/style.cljs [hunk 6]
```diff
@@ -1,42 +1,142 @@
...
-(defn channel-list-component
-  []
-  {:margin-top    8
-   :margin-bottom (+ 21 shell.constants/floating-shell-button-height)
-   :flex          1})
+  {:flex 1})
+
+(defn header-cover-image
+  [background-color]
+  {:width            "100%"
```
Comment (flexsurfer) [inline src/status_im/contexts/communities/overview/style.cljs:17]: could you pls elaborate on why "100%" is needed

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/communities/overview/style.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/style.cljs:17]: Sure! @flexsurfer 
Since I'm not providing `flex 1` (I'm giving a fixed height), I preferred to just ask the container to use all of its width.

File: src/status_im/contexts/communities/overview/style.cljs [hunk 7]
```diff
@@ -1,42 +1,142 @@
...
+   :padding-bottom 20
+   :padding-top    (when-not tags? 20)})
+
+(def request-to-join-as
+  {:padding-left   20
+   :padding-right  20
+   :padding-top    4
+   :padding-bottom 25})
+
+(defn chanel-listing
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/style.cljs]: Missing `n`

File: src/status_im/contexts/communities/overview/style.cljs [hunk 8]
```diff
@@ -1,42 +1,142 @@
...
+  [theme]
+  (let [height (- (:height (rn/get-window))
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/style.cljs]: Nitpick, but I find a little odd to see a style function pulling data like the safe area. I see this responsibility & data coming from the component.

File: src/status_im/subs/chats.cljs [hunk 9]
```diff
@@ -123,35 +124,40 @@
...
+     ;; 68 Is the length of the community-id prefix in the `chat-id`
+     (let [relative-chat-id (some-> current-chat
+                                    :chat-id
+                                    data-store.chats/community-chat-id->channel-id)]
+       (cond-> current-chat
+
+         (and (chat.events/community-chat? current-chat)
+              (get-in community [:chats relative-chat-id :can-post?]))
+         (assoc :able-to-send-message? true)
+
```
Comment (ilmotta) [inline src/status_im/subs/chats.cljs:142]: Extra line

File: src/status_im/contexts/communities/overview/view.cljs [hunk 10]
```diff
@@ -100,240 +41,420 @@
...
+                                     :headerHeight               header-height
+                                     :expandHeaderThreshold      expand-header-threshold
+                                     :sheetDisplacementThreshold sheet-displacement-threshold
+                                     :expandHeaderLimit          expand-header-limit})
+        flat-list-ref          (reanimated/use-animated-ref)
+        _ (worklets/use-scroll-to
+           #js {:animatedRef       flat-list-ref
+                :scrollAmount      scroll-amount
+                :expandHeaderLimit expand-header-limit})
+        community              (rf/sub [:communities/community community-id])
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs]: The `:communities/community` subscription is deprecated.

https://github.com/status-im/status-mobile/blob/8f990732c1fafdde19f5dbc90f41f362a819e2b3/src/status_im/subs/communities.cljs#L21-L23

File: src/status_im/contexts/communities/overview/view.cljs [hunk 11]
```diff
@@ -100,240 +41,420 @@
...
+      :style                   [(style/chanel-listing theme) channels-styles]
+      :data                    flatten-channels
+      :content-container-style (when platform/ios?
+                                 {:padding-bottom (safe-area/get-bottom)})
+      :sticky-header-indices   categories-indexes
+      :scroll-enabled          false
+      :render-fn               render-fn
+      :key-fn                  :id}]))
+
+
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs]: Extra line

File: src/status_im/contexts/communities/overview/view.cljs [hunk 12]
```diff
@@ -100,240 +41,420 @@
...
+              :community-logo community-logo)]
+      [quo/page-nav
+       (assoc base-props
+              :type       :no-title
+              :background :photo)])))
+
+(defn- header
+  [community-id scroll-amount]
+  (let [header-opacity          (worklets/use-header-opacity
+                                 #js {:scrollAmount               scroll-amount
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs]: I was wondering about making worklet functions support idiomatic Clojure with kebab keys and a CLJS map. A wrapper function called for every var defined in `utils.worklets.communities` with `clj->js` should be more than fast enough for small data structures such as one-level deep small arg maps.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 13]
```diff
@@ -100,240 +41,420 @@
...
+                                      :expandHeaderThreshold      expand-header-threshold
+                                      :sheetDisplacementThreshold sheet-displacement-threshold})
+        opposite-header-opacity (worklets/use-opposite-header-opacity header-opacity)
+        nav-content-opacity     (worklets/use-nav-content-opacity
+                                 #js {:scrollAmount               scroll-amount
+                                      :sheetDisplacementThreshold sheet-displacement-threshold
+                                      :expandHeaderLimit          expand-header-limit})
+        community               (rf/sub [:communities/community community-id])]
```
Comment (ilmotta) [inline src/status_im/contexts/communities/overview/view.cljs]: Similar to another comment I made in the review, please consider replacing any usage of this subscription. The community map can change too often from signals. This sub usage is deprecated.

File: src/status_im/subs/communities.cljs [hunk 14]
```diff
@@ -364,6 +364,45 @@
...
+     (assoc (dissoc category :chats)
+            :render-as
+            render-as))))
+
+(defn- mark-as-channel
+  [channel]
+  (assoc channel :render-as :channel))
+
+(re-frame/reg-sub
+ :communities/flatten-channels-and-categories
```
Comment (ilmotta) [inline src/status_im/subs/communities.cljs:390]: @ulisesmac We can make an effort to write at least simple unit tests for layer-3 subs. This function is not trivial. See our testing guideline https://github.com/status-im/status-mobile/blob/7e343bdb55123f66fc4b57d4ea9613a213fdfbbe/doc/tests/tests-overview.md#L99

Interestingly, the status-go repo is getting a testing policy https://github.com/status-im/status-go/pull/6413 from @Samyoul. Because in status-mobile we are failing to unit test tons of code which is reaching `develop`, it seems to me we need to re-align about our minimum quality gates.

Unfortunately ClojureScript doesn't help much for introducing a test coverage step in the CI.

cc @clauxx @vkjr

**Review by ilmotta — COMMENTED** [review]
Excellent results in this PR @ulisesmac! It's a bit too large to review, but I shared what I could as feedback.

File: src/status_im/contexts/communities/overview/view.cljs (hunk 10 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/view.cljs]: @ilmotta  
Interesting comment, I didn't notice, it was used before so I used it.

I was aware of this risk, so if you check the code, I never pass the `community` extracted to children, only specific keys, and also the callbacks and values are memoized,  so I'd confidently say it'll re-render the UI just when it's needed.

Being said that,
Do you think I should derive subscriptions from this one to others with a more reduced scope? I'd happily do it if so.

File: src/status_im/contexts/communities/overview/view.cljs (hunk 12 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/view.cljs]: Yes, I'd say indeed it'll be fast. 


Actually, transforming  kebab-case  prop keys -> camelCase keys is what reagent does very well with its `.impl` functions, you know, it implements a cache, so it's super fast.

I wanted to keep camelCase keys because writing JS with kebab-case is very weird (even more than Clojure with camelCase IMO). 

Please, let's chat about it, so we can compare perspectives and reach a middle ground :+1:

File: src/status_im/subs/communities.cljs (hunk 14 above)
Comment (ulisesmac) [reply src/status_im/subs/communities.cljs:390]: For sure!
Thanks for pointing it out, I'll add a unit test for this one

**Comment by ulisesmac** [comment]
> This is really good looking, a much needed improvement!
> 
> I just wish there was basic file sharing ability and voice messages to make the chat features actually competitive

@du82 Thanks for the comment!

Yes, people nowadays use audio messages too often, but due to our decentralized nature it may involve some challenges. I asked the team about it and it's something we'll evaluate, not right now but soon.

**Comment by du82** [comment]
> > This is really good looking, a much needed improvement!
> > I just wish there was basic file sharing ability and voice messages to make the chat features actually competitive
> 
> @du82 Thanks for the comment!
> 
> Yes, people nowadays use audio messages too often, but due to our decentralized nature it may involve some challenges. I asked the team about it and it's something we'll evaluate, not right now but soon.

Audio messages were available in v1.X, and so far v2.x is a downgrade. It has less functionality and feels like crypto capitalism is consuming the messaging app. The default tab used to be messaging, and now that's an afterthought.

File: src/status_im/contexts/communities/overview/style.cljs (hunk 6 above)
Comment (seanstrom) [reply src/status_im/contexts/communities/overview/style.cljs:17]: Could we also use `flex: 1` combine with a `flex-direction: row` ?

File: src/quo/components/navigation/page_nav/style.cljs [hunk 15]
```diff
@@ -32,12 +32,10 @@
...
-  [min-size?]
-  (merge
-   {:flex-grow  1
-    :flex-basis 1}
-   (when min-size?
-     {:min-height 32})))
+  [min-size? centered-content?]
+  (cond-> {}
+    centered-content? (assoc :flex-grow 1 :flex-basis 1)
+    min-size?         (assoc :min-height 32)))
```
Comment (seanstrom) [inline src/quo/components/navigation/page_nav/style.cljs]: Small nitpick:

maybe we can format these kind of assocs with a map-like structure?
for example:
```clojure
(defn right-content
   [min-size? centered-content?]
   (cond-> {}
     centered-content? (assoc :flex-grow 1 
                              :flex-basis 1)
     min-size?         (assoc :min-height 32)))
```

**Review by seanstrom — COMMENTED** [review]
@ulisesmac thanks for the PR 🙌 

I left a few comments, but my main comment would be about the new worklet file `worklets/communities.js`.

I'm wondering if we should extract some of these special number values and pass them as arguments into the JS functions from the ClojureScript functions. Not sure if that's possible, but it seems we can pass in a map with some animation configuration data.

For example, instead of hard-coding `-42.5` we'll try to name that value and pass it in as an argument. Though, I would imagine we don't need to do this for every number, like `0`, `1`, and `-1` are probably safe to keep in JS since those are likely generic animation configuration. But the special animation configuration could be passed as an argument(s). Thoughts?

File: src/status_im/contexts/communities/overview/view.cljs (hunk 10 above)
Comment (ilmotta) [reply src/status_im/contexts/communities/overview/view.cljs]: I'm sure you were careful, but even then, the community entity from status-go can be updated if the members change or a tiny timestamp changes, and both would trigger unnecessary work in the view layer, and community changes can happen rather frequently.

> Do you think I should derive subscriptions from this one to others with a more reduced scope? I'd happily do it if so.

Yes, that would be the idea @ulisesmac. It's as if `:communities/community` should be a private function sort of.

File: src/status_im/contexts/communities/overview/view.cljs (hunk 12 above)
Comment (ilmotta) [reply src/status_im/contexts/communities/overview/view.cljs]: I'm not strong on this particular point @ulisesmac, more like an idea for a cleaner API. Basically:

1. `worklets/use-header-opacity` is a CLJS function and as such, would ideally take CLJS maps with kebab case.
2. The implementation of a worklet is JS and as such, to feel idiomatic should use camel case.

That's why I suggested a translation layer could be nice because performance would likely be acceptable, and both worlds CLJS & JS would write idiomatic code. Does this clarify that in my suggestion you wouldn't be writing JS with kebab case?

File: src/status_im/contexts/communities/overview/style.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/style.cljs:17]: Yep, we could @seanstrom, but it works this way, Usually when dealing with images we need to provide a more specific fixed size, instead of a dynamic one (flex). It works this way, I'd keep it as is. wdyt?

File: src/status_im/contexts/communities/overview/style.cljs (hunk 8 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/style.cljs]: Well, it's also about calculating the height (a style prop) of the component. I personally don't think is wrong but I don't have a strong opinion on it, so I removed it

File: src/status_im/contexts/communities/overview/view.cljs (hunk 10 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/view.cljs]: Done!

File: src/status_im/contexts/communities/overview/view.cljs (hunk 12 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/view.cljs]: I added a function that wraps worklets to add this API, the transformations are memoized.

If we create new worklets with multiple params that require passing maps/JS objects as I did, we can abstract it and reuse it

File: src/status_im/subs/communities.cljs (hunk 14 above)
Comment (ulisesmac) [reply src/status_im/subs/communities.cljs:390]: Unit test added :)

File: src/quo/components/navigation/page_nav/style.cljs (hunk 15 above)
Comment (ulisesmac) [reply src/quo/components/navigation/page_nav/style.cljs]: Yes, we usually (and our lint-fix task) formats like that, in this case I deliberately wanted to keep it inline since it's a short map. Do you think this pattern is wrong?

File: src/utils/worklets/communities.cljs [hunk 16]
```diff
@@ -0,0 +1,33 @@
+(ns utils.worklets.communities
+  (:require [goog.object :as gobj]
+            [react-native.utils :as utils]
+            [taoensso.timbre :as log]))
+
+(def worklets (js/require "../src/js/worklets/communities.js"))
```
Comment (ilmotta) [inline src/utils/worklets/communities.cljs]: Can be private?

File: src/utils/worklets/communities.cljs [hunk 17]
```diff
@@ -0,0 +1,33 @@
...
+(defn- transform-args
+  [f]
+  (fn [& args]
+    (apply f (map utils/kebab-case-map->camelCase-obj args))))
+
+(defn- worklet-wrapper
+  [worklet-name]
+  (if-let [worklet-fn (gobj/get worklets worklet-name)]
+    (transform-args worklet-fn)
+    (log/error "Non-existing worklet!"
```
Comment (ilmotta) [inline src/utils/worklets/communities.cljs]: Here I would throw an error right away instead of logging, similar to how we changed Malli schemas to throw during app setup in case they are invalid. We know that if `worklet-wrapper` received a non-existent worklet name it's a developer mistake and it's risky to proceed and merge by mistake. The def'ed var will be nil because `log/error` returns nil. In release builds the caller of these vars won't check if they are nullable and thus we would risk exceptions in production.

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/communities/overview/view.cljs (hunk 12 above)
Comment (ilmotta) [reply src/status_im/contexts/communities/overview/view.cljs]: Just left a quick comment about the worklet name runtime check @ulisesmac https://github.com/status-im/status-mobile/pull/22293#discussion_r2003562391 Nice to see the improved API for CLJS!

File: src/quo/components/navigation/page_nav/style.cljs (hunk 15 above)
Comment (seanstrom) [reply src/quo/components/navigation/page_nav/style.cljs]: I don't think it's wrong, though I think it's easier to glance at map structure than an inline structure. For me, the inline structure reminds me of a sequence of things, but in this case we know we mean it's a sequence of key-values. 

For example, here's another way of looking at it:
```clojure
(def thing {:flex-grow 1 :flex-basis 1}

(def other {:flex-grow 1
            :flex-basis 1}
```

Even though it's a small map, I would still prefer seeing each key-value on its own line just for readability. Though it's not a big deal, since as you say it's a small map 🗺️

File: src/status_im/contexts/communities/overview/view.cljs [hunk 18]
```diff
@@ -2,95 +2,55 @@
...
+    [utils.re-frame :as rf]
+    [utils.worklets.communities :as worklets]))
 
-(defn- add-category-height
-  [categories-heights category height]
-  (swap! categories-heights assoc category height))
+;; NOTE: values compared against `scroll-amount` to trigger animations.
+(def expand-header-threshold
+  "Dragging distance to collapse/extend the community."
+  150)
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/overview/view.cljs:26]: Hey @seanstrom 

I find very difficult to name all the values passed, those values are just style values needed to match designs due to animations, also I don't think giving names to those is significantly helpful.

Instead, I named the configurable props for animations and I'm passing them to the worklets. Since maybe the names aren't clear enough, I added a docstring to these so they can be configured more easily.

wdyt? is that enough?

**Comment by mariia-skrypnyk** [comment]
Temporary blocked by https://github.com/status-im/status-mobile/pull/22350

**Comment by mariia-skrypnyk** [comment]
Hi @ulisesmac !

Thanks for your fixes in this PR.
I've checked both platforms and did smoke of communities.
UI moments looks much better!

We need to wait some fixes in e2e tests.
Let you know when PR could be merged.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 19]
```diff
@@ -100,235 +60,430 @@
...
-                                        12
-                                        (+ scroll-page.style/picture-radius
-                                           scroll-page.style/picture-border-width
-                                           12))
-                                      :margin-bottom 12}
-    :avatar                          logo
-    :title                           title
-    :title-number-of-lines           2
-    :description                     description
-    :title-accessibility-label       :community-title
```
Comment (yevh-berdnyk) [inline src/status_im/contexts/communities/overview/view.cljs:222]: Hi @ulisesmac, could you please return this accessibility label, because it's used in e2e tests. Thanks!

**Comment by ulisesmac** [comment]
@yevh-berdnyk @mariia-skrypnyk 

I returned the missing accessibility labels, sorry, I missed some of them because this is a completely new implementation.

**Comment by ulisesmac** [comment]
@seanstrom I reformatted the  map,  thanks for the review :+1:

**Comment by seanstrom** [comment]
@ulisesmac sorry for the delay, just read your comment about the naming of those special arguments.

I think what you have is good, and I think your reasoning about the trouble with naming things is very valid. I suppose naming things might be a workaround for just wanting to write these JavaScript functions in ClojureScript haha. Though I imagine that's not currently possible since those worklets run in a separate environment then our main app.

I wonder if later on we can experiment with adding another shadow-cljs build for the worklets in our app. Not sure if that would help or hurt things, but it could be a fun thing side-quest 🧙

**Review by seanstrom — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Thanks @ulisesmac for your patience!
PR finally can be merged!

File: src/status_im/contexts/communities/overview/view.cljs [hunk 20]
```diff
@@ -354,16 +516,12 @@
...
-         :as   community} (rf/sub [:communities/community id])]
-    (if community
-      [community-scroll-page id joined name images]
-      [community-fetching-placeholder id])))
-
 (defn view
   [id]
-  (let [id (or id (quo.context/use-screen-params))]
+  (let [community-id (or id (rf/sub [:get-screen-params :community-overview]))
+        community    (rf/sub [:communities/community-overview community-id])
```
Comment (Parveshdhull) [inline src/status_im/contexts/communities/overview/view.cljs:522]: hi @ulisesmac, Thank you very much for improving the community screen.

While addressing conflicts, please ensure that you are not reverting any changes. Here, we are reintroducing `:get-screen-params` in the community screen.

Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/view.cljs:522]: I'll fix it in my next PR, thanks for noticing
