### PR TITLE
[#20513] Fix last mesage overlapped with "join community" button

### LINKED ISSUE #20513: "Join community to post" overlaps the last message in chat when there are pinned messages on IOS
# Bug Report

## Problem 
When the user is not joined, last message in channel might be overlapped by "Join community to post" when there is pinned message.

#### Expected behavior
can see the last message

#### Actual behavior
IMAGE 2024-06-19 17:36:13

### Reproduction

1. Open Status community 
2. Check several channels

### Additional Information

- Status version: nightly 
- Operating System: iOS (so far can't see it on Android)

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20513

### Summary

This PR fixes the "join community to post" overlapped.

Fixed on iOS:

https://github.com/user-attachments/assets/01aea338-a28f-4205-ad43-5367b462b3a9

Still working on Android:

https://github.com/user-attachments/assets/1dbe5abe-781a-47b1-a80f-30f0abdc7063

### Review notes
I changed the way we applied the spacing, previously we created a white space behind the "join community to post" drawer, so the blur wasn't properly applied on iOS. If it was increased, the blur wouldn't be noticeable. 

The paddings are now applied as part of `:content-container-style` of flat-list.

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

Please check that these

- 1-1 chats
- Community chats
- Group chats

Still look as expected.

### Steps to test

You will need two communities: 
1- where the user is joined, and
2- where the user is still not joined.

You can use this one to test the NOT joined case:

https://status.app/c/G00AAGS9TbI9mSR-ZNmFrhRjNuEeXAAbcAIUaLLJyjMOG3ACJQ12oIHD78QhzO9s_T5bUeU7rnATWJg3mGgTUemrAg==#zQ3shjkJRet5c6BEspn9Y4UT4ZCU3LqnAt1rMmoVMuPwJRWCM

- Open Status
- Go to the not joined community
- Open the general chat (or any chat with more messages)
- Scroll to bottom and see that the message is no longer overlapped
- For the joined community, a 1-1 chat, and a group chat:
  - Scroll to the bottom and check nothing is cropped or overlapped.

status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/messages/list/style.cljs [hunk 1]
```diff
@@ -1,82 +1,25 @@
...
-(defn bio-and-actions
-  [top]
-  (reanimated/apply-animations-to-style
-   {:top top}
-   {:row-gap 16}))
-
-(defn permission-context-sheet
-  [margin-bottom?]
-  {:flex          3 ;; Pushes composer to bottom
-   :margin-bottom (when margin-bottom? permission-context-height)})
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/messages/list/style.cljs:82]: Moved the margins here to inner paddings, as mentioned in the PR description

Comment (ulisesmac) [inline src/status_im/contexts/chat/messenger/messages/list/style.cljs:82]: Removed unused functions, these weren't removed in 
- https://github.com/status-im/status-mobile/pull/21313 

So I'm removing them now

**Review by clauxx — APPROVED** [review]
Looks good :+1:

**Comment by Horupa-Olena** [comment]
@ulisesmac Thanks for your fix. You can merge this PR
