### PR TITLE
Fix networks on select asset screen

### LINKED ISSUE #19534: The network labels identifier depends on whether the token is supported on the current network on send assets page
### Steps:
1. Recover user with some assets on particular network (example: eth)
2. Go to "send assets" page
3. Check network label

### Actual result:
The network labels identifier depends on whether the token is supported on the current network.

The ETH in this case has all three labels because it is supported on both L1 and L2, regardless of whether the user has ETH on only one network
image

### Expected result:
The network labels identifier should depend on whether the user owns the token.

discussed with design team https://discord.com/channels/624634427930312714/852533718790570015/1225517260685312041

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19534

### Summary

We should only show the networks underneath tokens for which the user has a balance (for the same token). Before we used to show all networks which support the token.

### Testing notes
This should affect both the send and bridge flows

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
> ### Testing notes
> This should affect both the send and bridge flows

This function is also used in swaps, so I'd suggest to also smoke test swaps https://github.com/status-im/status-mobile/blob/f539bb5ca28e248686c4b2533ffc8ed83be44db1/src/status_im/contexts/wallet/swap/utils.cljs#L68

Other than that, LGTM

**Comment by VolodLytvynenko** [comment]
@clauxx thank you for PR. Take a look at the issues:


At first, it seemed like the issue wasn't related to the current PR, but eventually, it turned out to be connected. Previously, the network selection was always shown for default tokens like SNT, ETH, and DAI. However, now, the network selector only appears for tokens with a balance greater than 0

## ISSUE 1: An incorrect network selector is shown for default tokens (SNT, ETH, DAI) if long tap on token and tap 'swap'

### Steps:
1. Create or restore a user with 0 tokens for SNT, ETH, DAI assets
2. Go to the wallet main page
3. Long tap asset -> tap "swap"


### Actual result:

https://github.com/user-attachments/assets/323f61d7-72a6-4bd5-bfb2-b0ac50165c8f


### Expected result:
The "Swap" option should not be shown or should be disabled for tokens with 0 value until the user holds a balance on any network.

https://discord.com/channels/1210237582470807632/1270072144067563520/1293947917635424338

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by clauxx** [comment]
@VolodLytvynenko I also noticed that pressing send on an asset with 0 balance does nothing. We should hide that as well, right?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko I also noticed that pressing send on an asset with 0 balance does nothing. We should hide that as well, right?

@clauxx Right. If you can do it within the scope of this PR, that would be awesome. Here’s the design prepared recently: [Figma link](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1537-44904&node-type=frame&t=cUld4XEd1ZVnBcR6-0). For tokens with 0 balances, we should not show the "Send," "Bridge," and "Swap" options. Discussed with design team [here](https://discord.com/channels/1210237582470807632/1270072144067563520/1295355758199967816)

**Comment by clauxx** [comment]
@briansztamfater please have a look again, as there are some changes related to swaps.

@VolodLytvynenko added the changes you mentioned :+1:  Please have another look

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@clauxx  thank you for PR. No issues from my side. PR is ready to be merged

File: src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs [hunk 1]
```diff
@@ -26,7 +26,7 @@
                          (let [pay-token-symbol (:symbol token)
                                asset-to-receive (if (= pay-token-symbol "SNT") eth-token snt-token)]
                            (rf/dispatch [:wallet.swap/start
-                                         {:asset-to-pay     token
+                                         {:asset-to-pay     {:symbol pay-token-symbol}
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs:29]: Can you elaborate on why is this change needed?

Comment (clauxx) [reply src/status_im/contexts/wallet/swap/select_asset_to_pay/view.cljs:29]: Opening the swap screen crashes with the same 'toLowerCase' error without this change. It's rather difficult to debug though, but I assume it's because we were passing the token with a subset of the networks (the ones with balance), while the swap screen may be expecting all networks there. By passing the symbol only, we're forcing the token to be "rebuilt" with all the networks, but in case you know what could be the issue, there could be a better solution to this.
