### PR TITLE
[Fix] Broken wallet account emoji when syncing devices

### LINKED ISSUE #18640: Broken wallet icon after sync with desktop
**Steps:** 

1. User A (Desktop) generates sync QR
2. User B (mobile) scans sync QR
3. Wait until sync process is completed
4. Check how wallet icon looks like in different places (i.e. wallet QR, wallet screens etc)

**Actual result:** 

photo_2024-01-26 15 21 00
photo_2024-01-26 15 21 03
photo_2024-01-26 15 21 06
photo_2024-01-26 15 21 10

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18640

### Summary

This PR fixes the broken wallet account emoji when syncing devices by adding a sanitization method for the wallet account emoji. The desktop can handle both variants (raw emoji and img tag) and this PR adds the same for mobile. 

### Review notes

Since the Desktop uses Twemoji, it is used to save the account emoji in img tag in status-go. It was fixed to save only the emoji instead of img tag. Somehow, the img tag is still propagated from the desktop. It will be debugged by the desktop team later (as this issue is not a priority at this moment). Additionally, this fix (sanitization) would help prevent such issues from happening from backup restore in mobile.

### Platforms

- Android
- iOS

#### Prerequisite: Create a user in Desktop

- Open Status
- Sync the mobile app with the Desktop for the newly created user
- Verify the account emojis displayed across the application are not broken (or displaying an HTML img tag)

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/data_store.cljs [hunk 1]
```diff
@@ -22,6 +22,12 @@
   [account]
   (assoc account :watch-only? (= (:type account) :watch)))
 
+(defn- sanitize-emoji
+  [emoji]
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/data_store.cljs:29]: maybe we should add a comment to the purpose of this

**Review by J-Son89 — APPROVED** [review]

**Review by shivekkhurana — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid, thank you for PR. No issues from my side. PR is ready to be merged
