### PR TITLE
[15166] Show message edited status

### LINKED ISSUE #15166: The 'edited' mark is not shown after the message is updated
**Steps to reproduce:**
1. Go to any chat
2. Send the message
3. long tap on message -> Edit message -> Update the text -> Send the message
4. Check the message

**Actual result:**
The 'edited' mark is not shown

**Expected result:**
The 'edited' mark is shown

**ENV:** Nightly [22 Feb 2023]

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #15166 

This PR checks the `edited-at` property of a message and if it exists .. Shows `edited` instead of `sent` in the message status component

Review comment:
I tested to use `cond->` but it didn't seem to work when matching equality test, i.e `(= ..`

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 1]
```diff
@@ -91,15 +91,16 @@
                                                          context)}]))
 
 (defn user-message-content
-  [{:keys [content-type quoted-message content outgoing outgoing-status] :as message-data}
+  [{:keys [content-type quoted-message content outgoing outgoing-status edited-at] :as message-data}
    {:keys [chat-id] :as context}]
   [:f>
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: Since you're touching this function, it looks like we don't need `:f>` here, because no hooks are being used.

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: Okay, Will do it .. Thanks Icaro

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 2]
```diff
@@ -91,15 +91,14 @@
                                                          context)}]))
 
 (defn user-message-content
-  [{:keys [content-type quoted-message content outgoing outgoing-status] :as message-data}
+  [{:keys [content-type quoted-message content outgoing outgoing-status edited-at] :as message-data}
    {:keys [chat-id] :as context}]
-  [:f>
    (let [show-delivery-state? (reagent/atom false)]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: formatting looks off

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: Fixed, Thanks

**Comment by VolodLytvynenko** [comment]
Hi, @ibrkhalil look like some integration tests are failed https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230228-091805-ced1fa-pr15190-tests.log. Could you fix it?

**Comment by ibrkhalil** [comment]
> Hi, @ibrkhalil look like some integration tests are failed https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230228-091805-ced1fa-pr15190-tests.log. Could you fix it?

Does the integration tests expect the message edited message state?

**Comment by VolodLytvynenko** [comment]
> > Hi, @ibrkhalil look like some integration tests are failed https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230228-091805-ced1fa-pr15190-tests.log. Could you fix it?
> 
> Does the integration tests expect the message edited message state?

@ibrkhalil Got it. I didn't know that was the only problem. Could you also rebase the PR, please?

**Comment by pavloburykh** [comment]
@ibrkhalil please take a look at the following issues. 

### ISSUE 1 Message statuses are not updated until chat reopening

**Steps:**

1. Start any chat
2. Send message
3. See if status of message will change from Sending (message with opacity) to Sent/Delivered
4. Reopen chat
5. See if status of message status has been updated

**Expected result:** message statuses are being updated without chat reopening

**Actual result:** message stucks in Sending status until chat reopening. 


https://user-images.githubusercontent.com/97245802/221911578-ab95bbbb-5d5f-4220-9e2f-75cc945fc57e.mp4

**Comment by pavloburykh** [comment]
### ISSUE 2 Edited message is not updated until chat reopening

**Steps:**

1. Start any chat
2. Send message
3. Edit message
4. See if message has been updated
5. Reopen chat
6. See if message has been updated

**Expected result:** edited message has been updated without chat reopening

**Actual result:** edited message has been updated only after chat reopening


https://user-images.githubusercontent.com/97245802/221915291-d2e4f65c-9383-4ff4-8744-e54bdf34577a.mp4

**Comment by pavloburykh** [comment]
### ISSUE 3 Edited mark is not displayed next to the edited messages

Initial bug with message edited mark is still reproducible

**Steps:** 

1. Open any chat
2. Edit message (take into consideration issue 2 above)
3. See if edited mark is displayed for edited message

**Expected result:** edited mark is displayed next to the edited message

**Actual result:** edited mark is not displayed next to the edited messages


https://user-images.githubusercontent.com/97245802/221916606-94e446c8-9f53-499c-b350-18bc5cee8768.mp4

**Comment by briansztamfater** [comment]
Hi @pavloburykh @ibrkhalil as far as I remember from conversations with @pedro-et, Delivery States and Edited mark are different things. Edited mark should always be shown next to the message in-line if applicable and delivery states only when touching the message, and for some seconds, below de message.

> pedro.et — 02/02/2023 3:43 PM
> https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=3277%3A336019&t=hTfMetZ8wHlAF7Qh-1
> sent and delivered states are always bellow with icon
> edited is text in a adifferent format in the same line if it fits
> Brian Sztamfater — 02/02/2023 3:45 PM
> I see, so 'edited' mark and delivery states are different things
> 'edited' should be permanently shown right?
> and delivery states are shown on a single tap with the icon below, and just for 3 seconds
> pedro.et — 02/02/2023 3:46 PM
> yes

I added an implementation in #14949 but perhaps it is broken now, but I'd suggest to review the expected behavior of the Edited status. Of course I may be wrong but I checked few weeks ago, so dismiss my message if you already checked it -- As there are no screenshots / Figma links in the description of this PR or the issue I may have misunderstood it, let me know if that is the case

**Comment by pavloburykh** [comment]
> Edited mark should always be shown next to the message in-line if applicable 

Hey @briansztamfater thank you for your comment. You are absolutely correct. That is the behaviour which we expect to see as a result of current fix. Edited mark used to be shown next to the edited message before, but at some moment it was broken. That is how current issue appeared.

**Comment by briansztamfater** [comment]
@pavloburykh Great just wanted to check because I didn't find a visual reference in the issue, and the PR description confused me, thanks Pavlo!

**Comment by ibrkhalil** [comment]
> 

This comment is really helpful Brian, Thank you so much
Okay .. I'll look into why it was broken

**Comment by ibrkhalil** [comment]
Thanks Brian
I found the issue
And sorry Pavlo, For some weird reason .. My recent changes got reverted by GitHub .. So you didn't see any changes

**Comment by ibrkhalil** [comment]
> Thanks Brian I found the issue And sorry Pavlo, For some weird reason .. My recent changes got reverted by GitHub .. So you didn't see any changes

This is it after I found the issue
image

**Comment by ibrkhalil** [comment]
PR Ready to be reviewed
@pavloburykh @VladimrLitvinenko

**Comment by pavloburykh** [comment]
> PR Ready to be reviewed @pavloburykh @VladimrLitvinenko

@ibrkhalil all of the PR builds are failed, so we are not able to test. Please take a look at the issue.

**Comment by pavloburykh** [comment]
@ibrkhalil IOS build still failing https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-15190/12/consoleText

**Comment by ibrkhalil** [comment]
> @ibrkhalil IOS build still failing https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-15190/12/consoleText

It's a Jenkins bug, Jakub will fix it later today after currently running builds finish

**Comment by ibrkhalil** [comment]
> @ibrkhalil IOS build still failing https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-15190/12/consoleText

It's successful now

**Comment by pavloburykh** [comment]
> It's successful now

Great! Thank you @ibrkhalil

**Comment by pavloburykh** [comment]
@ibrkhalil please, take a look at the new issue
### ISSUE 4 Message delivery states (sent/delivered) are not shown upon tap on message

**Steps:** 

1. Open chat
2. Send a message
3. Wait until message will be sent
4. Tap on message
5. See if message delivery state (sent/delivered) is shown under the message

**Expected result:** message delivery state is shown. Below video is from develop branch

https://user-images.githubusercontent.com/97245802/222142191-bf6d6166-6a94-4db2-b0dd-8a1ef5b06999.mp4


**Actual result:** message delivery state is not shown

https://user-images.githubusercontent.com/97245802/222142147-960d1936-f3bf-482c-b005-662e178d3b77.mp4

**Comment by ibrkhalil** [comment]
> @ibrkhalil please, take a look at the new issue
> 
> ### ISSUE 4 Message delivery states (sent/delivered) are not shown upon tap on message
> **Steps:**
> 
> 1. Open chat
> 2. Send a message
> 3. Wait until message will be sent
> 4. Tap on message
> 5. See if message delivery state (sent/delivered) is shown under the message
> 
> **Expected result:** message delivery state is shown. Below video is from develop branch
> 
> **Actual result:** message delivery state is not shown

Fixed

**Comment by pavloburykh** [comment]
@ibrkhalil thanx! Issues 1,2,3,4 are fixed. Please have a look at issue 5

### ISSUE 5 Edited mark is displayed next to every line within one multiline message

**Steps:**

1. Send multiline message. This message should contain spaces (empty lines) between lines with text. See video below. 
2. Edit message
3. See how many Edited marks will be displayed for edited message

**Expected result:** 1 edited mark should be displayed for 1 edited message

**Actual result:** Edited mark is displayed next to every line within one multiline message


https://user-images.githubusercontent.com/97245802/222214247-ae9e95d7-bcb0-424e-b86b-6a728c633e53.mp4

**Comment by ibrkhalil** [comment]
Fixed and also .. @ilmotta @flexsurfer 
Kindly take a look at last commit if you have the time

**Comment by ibrkhalil** [comment]
And editing doesn't work for photo with text .. Please add a ticket for it when you have time to test it @pavloburykh

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 3]
```diff
@@ -73,10 +74,25 @@
...
+                                      (update (:parsed-text content)
+                                              (- parsed-text-count 1)
+                                              (fn [last-literal]
+                                                (update last-literal
+                                                        :children
+                                                        conj
+                                                        {:literal [rn/text (style/edited-style)
+                                                                   (str " (" (i18n/label :t/edited) ")")]
+                                                         :type    :edited}))))]
+    (conj (reduce (fn [acc e]
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: `conj` is being called here with only one argument. This will do nothing to the return value of `reduce`. We can probably remove it.

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 4]
```diff
@@ -73,10 +74,25 @@
...
 (defn render-parsed-text
-  [{:keys [content]}]
-  (reduce render-block
-          [:<>]
-          (:parsed-text content)))
+  [{:keys [content edited-at]}]
+  (let [parsed-text-count           (when edited-at
+                                      (count (:parsed-text content)))
+        parsed-text-with-edited-tag (when edited-at
+                                      (update (:parsed-text content)
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: I think we should explore in a future work using a subscription for pre-processing `message-data`. Only once the data is ready to be transformed to hiccup the view components should get into the action. This can help with performance. Right now `render-parsed-text` is a bit heavy on logic.

I've noticed every time I send any text, single char or more, the top-level view component `text-content` and all its children render 3 times. Something we should probably review if we want to improve even further the performance.

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 5]
```diff
@@ -55,11 +56,11 @@
   [blocks {:keys [type ^js literal children]}]
   (case (keyword type)
     :paragraph
-    (conj blocks
-          (reduce
-           render-inline
-           [quo/text]
-           children))
+    (conj (conj blocks
+                (reduce
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: This formatting looks odd, maybe just inline them since they're all short names:

```clojure
(conj (conj blocks
            (reduce render-inline [quo/text] children)))
```

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 6]
```diff
@@ -73,10 +74,25 @@
...
-  [{:keys [content]}]
-  (reduce render-block
-          [:<>]
-          (:parsed-text content)))
+  [{:keys [content edited-at]}]
+  (let [parsed-text-count           (when edited-at
+                                      (count (:parsed-text content)))
+        parsed-text-with-edited-tag (when edited-at
+                                      (update (:parsed-text content)
+                                              (- parsed-text-count 1)
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: Nitpick: as you know, you can use `dec`.

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 7]
```diff
@@ -92,81 +92,80 @@
...
+    [rn/touchable-highlight
+     {:accessibility-label (if (and outgoing (= outgoing-status :sending))
+                             :message-sending
+                             :message-sent)
+      :underlay-color      (colors/theme-colors colors/neutral-5 colors/neutral-90)
+      :style               {:border-radius 16
+                            :opacity       (if (and outgoing (= outgoing-status :sending)) 0.5 1)}
+      :on-press            (fn []
+                             (when (and outgoing
+                                        (not (= outgoing-status :sending))
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: Nitpick: `not=` instead of `(not (= ...`

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 8]
```diff
@@ -17,3 +18,27 @@
   {:background-color (colors/theme-colors colors/neutral-5 colors/white-opa-5)
    :border-width     1
    :border-color     (colors/theme-colors colors/neutral-20 colors/white-opa-20)})
+
+(defn message-default-style
+  []
+  {:font-family    "Inter-Regular"
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: I think we should use `foundations/typography` here and remove the duplicated properties. Like this:

```clojure
(defn message-default-style
  []
  (assoc typography/paragraph-1 :color (colors/theme-colors colors/neutral-100 colors/white)))
```

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 9]
```diff
@@ -17,3 +18,27 @@
...
+(defn edited-style
+  []
+  (cond->
+    (update (default-text-style)
+            :style
+            assoc
+            :color (colors/theme-colors colors/neutral-40 colors/neutral-50)
+            :font-size 13
+            :line-height 18.2
+            :letter-spacing (typography/tracking 13))))
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: Again here I think we should not duplicate what's well defined in the `typography/paragraph-2` var. You can just merge the properties.

```clojure
(defn edited-style
  []
  (-> (default-text-style)
      (update :style assoc :color (colors/theme-colors colors/neutral-40 colors/neutral-50))
      (update :style merge typography/paragraph-2)))
```

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 10]
```diff
@@ -1,6 +1,7 @@
 (ns status-im2.contexts.chat.messages.content.text.style
-  (:require
-    [quo2.foundations.colors :as colors]))
+  (:require [quo2.foundations.colors :as colors]
+            [quo2.foundations.typography :as typography]
+            [status-im.ui.components.react :as react]))
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: status-im shouldn't be used in status-im2

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 8 above)
Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: yes there shouldn't be any custom styles

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 11]
```diff
@@ -92,81 +92,80 @@
...
-    :accessibility-label :chat-item}
-   (when pinned-by
-     [pin/pinned-by-view pinned-by])
-   (if (#{constants/content-type-system-text constants/content-type-community
-          constants/content-type-contact-request}
-        content-type)
-     [system-message-content message-data]
-     [user-message-content message-data context])
-   [reactions/message-reactions-row chat-id message-id messages-ids]])
+  (let [show-delivery-state? (reagent/atom false)]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: this atom should be inside `user-message-content` component

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 12]
```diff
@@ -92,81 +92,80 @@
 
 (defn user-message-content
   [{:keys [content-type quoted-message content outgoing outgoing-status] :as message-data}
-   {:keys [chat-id] :as context}]
-  [:f>
-   (let [show-delivery-state? (reagent/atom false)]
-     (fn []
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/view.cljs:91]: you can remove :f but you have to keep atom here and keep render function, just move all parameters from component to render function

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 12 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/view.cljs:91]: Keeping atom here without `:f>` broke showing message status

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 11 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: This only affects the message edited notation

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 12 above)
Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/content/view.cljs:91]: ok then we should fix that :)

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Was testing another solution and forgot to remove it .. Thanks for noting it out!

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: I kept adding checks to prevent the calculation of the edited message body on non edited messages

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 12 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/view.cljs:91]: The fix I got on the top of my head was to move the atom in it's parent

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 10 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: Oh, Missed the import .. Okay

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 12 above)
Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/content/view.cljs:91]: you have to keep atom here and keep render function, just move all parameters from component to render function

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/content/view.cljs:91]:
```clojure
(defn user-message-content
  [_ _]
   (let [show-delivery-state? (reagent/atom false)]
     (fn [{:keys [content-type quoted-message content outgoing outgoing-status] :as message-data}
          {:keys [chat-id] :as context}]
```

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/view.cljs:98]: https://media.tenor.com/9hd9gB_WFqIAAAAC/sniper-pubg.gif

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: But you're correct .. We need to somehow cache the result of the message rendering computation for subsequent renders

**Comment by pavloburykh** [comment]
> And editing doesn't work for photo with text .. Please add a ticket for it when you have time to test it

@ibrkhalil thanx for pointing out the issue. It is known, we will log it today. 

> Fixed and also .. @ilmotta @flexsurfer Kindly take a look at last commit if you have the time

@ibrkhalil thanx for the fixes. Please, let me know when all review comments will be resolved and PR will be ready for re-test.

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 13]
```diff
@@ -73,10 +74,25 @@
...
+  (let [parsed-text-count           (when edited-at
+                                      (count (:parsed-text content)))
+        parsed-text-with-edited-tag (when edited-at
+                                      (update (:parsed-text content)
+                                              (dec parsed-text-count)
+                                              (fn [last-literal]
+                                                (update last-literal
+                                                        :children
+                                                        conj
+                                                        {:literal [rn/text (style/edited-style)
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: quo/text should be used here

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 14]
```diff
@@ -73,10 +74,25 @@
     blocks))
 
 (defn render-parsed-text
-  [{:keys [content]}]
-  (reduce render-block
-          [:<>]
-          (:parsed-text content)))
+  [{:keys [content edited-at]}]
+  (let [parsed-text-count           (when edited-at
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: parsed-text-count is redundant

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 15]
```diff
@@ -73,10 +74,25 @@
...
+                                      (count (:parsed-text content)))
+        parsed-text-with-edited-tag (when edited-at
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: better to move this in separate function

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 16]
```diff
@@ -73,10 +74,25 @@
...
+                                      (update (:parsed-text content)
+                                              (dec parsed-text-count)
+                                              (fn [last-literal]
+                                                (update last-literal
+                                                        :children
+                                                        conj
+                                                        {:literal [rn/text (style/edited-style)
+                                                                   (str " (" (i18n/label :t/edited) ")")]
+                                                         :type    :edited}))))]
+    (reduce (fn [acc e]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: redundant `(fn [acc e]`

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 17]
```diff
@@ -73,22 +73,22 @@
...
-                                              (fn [last-literal]
-                                                (update last-literal
-                                                        :children
-                                                        conj
-                                                        {:literal [rn/text (style/edited-style)
-                                                                   (str " (" (i18n/label :t/edited) ")")]
-                                                         :type    :edited}))))]
-    (reduce (fn [acc e]
-              (render-block acc e))
+  (let [parsed-text-with-edited-tag (when edited-at
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: parsed-text-with-edited-tag is redundant

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: We only calculate it when there's an `edited-at` timestamp

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: I removed the `let` declaration if that's what you meant .. And added it's content directly

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: yep

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 18]
```diff
@@ -72,11 +73,24 @@
...
+                     :type    :edited}))))
+
 (defn render-parsed-text
-  [{:keys [content]}]
+  [{:keys [content edited-at]}]
   (reduce render-block
           [:<>]
-          (:parsed-text content)))
+          (if edited-at
+            (add-edited-tag content)
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]:
```clojure
(cond-> (:parsed-text content)
                 edited-at
                  add-edited-tag)
```

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 19]
```diff
@@ -72,11 +73,24 @@
            [quo/text (subs literal 0 (dec (count literal)))]])
     blocks))
 
+(defn add-edited-tag [content]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: parsed-text

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 18 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: This is literally what `cond->` was created for :)

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 20]
```diff
@@ -72,11 +73,23 @@
            [quo/text (subs literal 0 (dec (count literal)))]])
     blocks))
 
+(defn add-edited-tag [parsed-text]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: btw just realized this should be done on the go side

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Oh 🤦🏻‍♂️

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: I was chatting with Pedro yesterday about the performance drawbacks of adding the `(Edited)` appended to the last piece of text rather than at a fixed location on the bottom right for example like this
image
But I did what I can to do the proposed design .. But you're right .. Calculations should be on `status-go` but the thing is this will force status-desktop to have the same message body for showing `(Edited)` status and they'll have to change how they did .. I think they did on the client-side
WDYT ?

Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: yes thats fine

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: What do you think about this @cammellos?

Comment (cammellos) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: I am a bit uneasy about changing `parsedText`, since `parsedText` contains text that's generated from the user, and here we are appending something that is not user generated but metadata.

Having said that, I don't see any other cleaner solution (I thought about using the reduce step instead of modifying, but the result is not much better).

Whether to move it in status-go, I would delay the decision. `ParsedText` is stored in the database, and if we add `Edited` to it, it means we can't easily go back, since migrating it would be really annoying. 
We could generate it on fly when serializing the message, that's ok, but I'd hold on for now until we are sure this is the right approach. So I would leave a comment saying precisely that, that we should move it to status-go once we are sure this is how both mobile/desktop wants it to be.

As a side note `add-editet-tag` does not seem to take into consideration code blocks/quotes, since if the message ends with one of those, it does not use `children`.

Try with a message such as:

```
this is a code block
```

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Added the case for codeblocks/blockquotes
image

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: @flexsurfer kindly take another look

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 21]
```diff
@@ -64,19 +65,38 @@
...
+            [quo/text (style/edited-style)
+             (str " (" (i18n/label :t/edited) ")")]))
 
     :codeblock
     (conj blocks
           [rn/view {:style (merge style/block (style/code))}
-           [quo/text (subs literal 0 (dec (count literal)))]])
+           [quo/text (subs literal 0 (dec (count literal)))]]
+          (when edited-at
+            [quo/text (style/edited-style)
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: properties should be used instead of styles

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Sorry for missing this, long time bugfixing and using quo 😂
Will fix

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: > properties should be used instead of styles

🎯

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: Done

**Review by flexsurfer — APPROVED** [review]

**Comment by ibrkhalil** [comment]
> > And editing doesn't work for photo with text .. Please add a ticket for it when you have time to test it
> 
> 
> 
> @ibrkhalil thanx for pointing out the issue. It is known, we will log it today. 
> 
> 
> 
> > Fixed and also .. @ilmotta @flexsurfer Kindly take a look at last commit if you have the time
> 
> 
> 
> @ibrkhalil thanx for the fixes. Please, let me know when all review comments will be resolved and PR will be ready for re-test. 

Kindly take another look

**Comment by ibrkhalil** [comment]
> > > And editing doesn't work for photo with text .. Please add a ticket for it when you have time to test it
> > 
> > 
> > 
> > @ibrkhalil thanx for pointing out the issue. It is known, we will log it today. 
> > 
> > 
> > 
> > > Fixed and also .. @ilmotta @flexsurfer Kindly take a look at last commit if you have the time
> > 
> > 
> > 
> > @ibrkhalil thanx for the fixes. Please, let me know when all review comments will be resolved and PR will be ready for re-test. 
> 
> Kindly take another look

Will fix the build and ping you

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil added an issue related to text editing here https://github.com/status-im/status-mobile/issues/15154#issuecomment-1451966743

**Comment by ibrkhalil** [comment]
> hi @ibrkhalil added an issue related to text editing here [#15154 (comment)](https://github.com/status-im/status-mobile/issues/15154#issuecomment-1451966743)

Apparently, When the user edits an image with a photo .. The photo gets lost .. So the team have added a constaint to prevent editing a photo with text on status-go [here](https://github.com/status-im/status-go/blob/999d8c0ee0f2274c58b5a2de3beddab7feaabd16/protocol/messenger_messages.go#L19) .. Happy to investigate in a subsequent issue

PR ready to be reviewed

**Comment by pavloburykh** [comment]
@ibrkhalil Thanx for the fixes. Please take a look at the new issue

### ISSUE 6 Padding is removed for edited text (Android only)

Reproducible only on Android (Samsung Galaxy A52, Android 12)

**Steps:** 

1. Open any chat
2. Send text message
3. Edit message
4. Pay attention at padding between edited text and chat key/timestamp above the message. 

**Expected result:** padding between elements remains after editing text

**Actual result:** padding is removed after editing message

photo_2023-03-06 10 26 00

https://user-images.githubusercontent.com/97245802/223056436-540286ef-d80c-411c-82f8-01182c734a31.mp4

**Comment by ibrkhalil** [comment]
> @ibrkhalil Thanx for the fixes. Please take a look at the new issue
> 
> ### ISSUE 6 Padding is removed for edited text (Android only)
> Reproducible only on Android (Samsung Galaxy A52, Android 12)
> 
> **Steps:**
> 
> 1. Open any chat
> 2. Send text message
> 3. Edit message
> 4. Pay attention at padding between edited text and chat key/timestamp above the message.
> 
> **Expected result:** padding between elements remains after editing text
> 
> **Actual result:** padding is removed after editing message
> 
> photo_2023-03-06 10 26 00

Fixed

**Comment by pavloburykh** [comment]
@ibrkhalil all builds are failed

**Comment by ibrkhalil** [comment]
> @ibrkhalil all builds are failed

Just rebased

**Comment by pavloburykh** [comment]
@ibrkhalil thanx for fixing issue 6. Please, take a look at issue 7

### ISSUE 7 Reply UI is broken: connector element is missing 

**Steps:** 

1. Open any chat
2. Send message
3. Reply to the message
4. Compare reply UI in the PR build to the UI from designs or nightly build. 

**Expected result:** below screenshot is from latest nightly build

photo_2023-03-06 12 03 46

**Actual result:** connector element is missing 
photo_2023-03-06 12 07 13

**Comment by pavloburykh** [comment]
### ISSUE 8 Link previews are not updated for edited links until chat reopening

**Steps:**

1. Open any chat
2. Send message containing link (for example some Youtube link)
3. Enable previews for links
4. Edit message: replace link with some other link
5. See if link preview is updated for edited link

**Expected result:** Link preview is updated after editing link

**Actual result:** preview is updated only after chat re-opening 


https://user-images.githubusercontent.com/97245802/223087448-46a016dd-1b83-4be6-a901-7ff831c09515.mp4

**Comment by ibrkhalil** [comment]
> ### ISSUE 8 Link previews are not updated for edited links until chat reopening
> **Steps:**
> 
> 1. Open any chat
> 2. Send message containing link (for example some Youtube link)
> 3. Enable previews for links
> 4. Edit message: replace link with some other link
> 5. See if link preview is updated for edited link
> 
> **Expected result:** Link preview is updated after editing link
> 
> **Actual result:** preview is updated only after chat re-opening

Fixed, Sorry I messed this up while rebasing .. that's why it was introduced

**Comment by pavloburykh** [comment]
@ibrkhalil issue 7 is fixed, thanx. But [issue 8](https://github.com/status-im/status-mobile/pull/15190#issuecomment-1455890426) is still reproducible

**Comment by pavloburykh** [comment]
@ibrkhalil one more minor issue

### ISSUE 9 No space between "edited" mark end edited code block

**Steps:** 

1. Open any chat
2. Send message with code markdown
3. Edit message preserving code markdown
4. See if there is space (padding) between edited code block and "Edited" mark

**Actual result:** no space (padding) between edited code block and "Edited" mark

photo_2023-03-06 13 28 20

**Comment by ibrkhalil** [comment]
> @ibrkhalil one more minor issue
> 
> ### ISSUE 9 No space between "edited" mark end edited code block
> **Steps:**
> 
> 1. Open any chat
> 2. Send message with code markdown
> 3. Edit message preserving code markdown
> 4. See if there is space (padding) between edited code block and "Edited" mark
> 
> **Actual result:** no space (padding) between edited code block and "Edited" mark
> 
> photo_2023-03-06 13 28 20

What's the exact content of this message ?
I couldn't reproduce issue 8 or 9
I enabled all youtube link previews in settings btw

**Comment by pavloburykh** [comment]
@ibrkhalil 
> What's the exact content of this message ?
> I couldn't reproduce issue 8 or 9
> I enabled all youtube link previews in settings btw

Here is video demonstration of both 8 and 9 issues. I am reproducing it in the last successful PR build. Pay attention that 2 last PR build stacks are failed. 


https://user-images.githubusercontent.com/97245802/223132675-568febb8-e153-46ef-b709-693939b8140f.mp4

**Comment by ibrkhalil** [comment]
> @ibrkhalil
> 
> > What's the exact content of this message ?
> > I couldn't reproduce issue 8 or 9
> > I enabled all youtube link previews in settings btw
> 
> Here is video demonstration of both 8 and 9 issues. I am reproducing it in the last successful PR build. Pay attention that 2 last PR build stacks are failed.

Thank you so much for this video Pavlo!
Fixed

**Comment by pavloburykh** [comment]
@ibrkhalil [ISSUE 9](https://github.com/status-im/status-mobile/pull/15190#issuecomment-1455962049) is fixed. 

[ISSUE 8](https://github.com/status-im/status-mobile/pull/15190#issuecomment-1455890426) is still reproducible in latest build.

**Comment by pavloburykh** [comment]
Please, take a look at few more minor issues

### ISSUE 10 A separate "Edited" mark is displayed for every codeblock within one edited message

**Steps:**

1. Send a message containing codeblock (there might be several codeblocks within one message) and regular text
2. Edit message
3. See how many "Edited" marks are displayed for such message

**Expected result:** one "Edited" mark should be displayed for one entire mesage

**Actual result:** "Edited" mark is displayed for every codeblock within one edited message. 

photo_2023-03-06 18 24 23


https://user-images.githubusercontent.com/97245802/223170325-768600c1-d8d9-4d9c-8060-1615fdb4e77b.mp4

**Comment by pavloburykh** [comment]
### ISSUE 11 No space between codeblock and regular text below it within one massage

**Steps:**

1. Send a message containing codeblock and regular text below the codeblock (see video below)
2. See if there is space (padding) between codeblock and regular text below

Expected result: there should be stadard padding like between other lines in message

**Actual result:** no space. 

photo_2023-03-06 18 33 42


https://user-images.githubusercontent.com/97245802/223172868-b499324d-9ad3-4dbc-93ba-527915980561.mp4

**Comment by pavloburykh** [comment]
@ibrkhalil issues 10 and 11 are minor issues. If you prefer, we can address them in separate folloups in order not to block this PR from merging. 

But regarding [ISSUE 8](https://github.com/status-im/status-mobile/pull/15190#issuecomment-1455890426) I would fix it in this PR, as it has been introduced by it. Not reproducible in develop for me.

**Comment by pavloburykh** [comment]
@ibrkhalil thanx. Issue 8 is fixed. Issues 10 and 11 will be logged as followups. PR is ready to be merged.
