### PR TITLE
fix: wallet send navigation flow

### LINKED ISSUE #19697: Wrong navigation wallet flow if back button from transaction confirmation page is tapped
### Steps:
1. Go to assets sending page
2. Enter the available asset value and navigate to the transaction confirmation page.
3. Tap the 'back' button until the 'send to' or 'select assets' page is opened.
4. If the 'send to' page is opened, tap the account. If the 'select assets' page is opened, tap the asset.

### Actual result:
The confirmation page is opened instead of returning to the assets sending page.

https://github.com/status-im/status-mobile/assets/52490791/be890807-39e8-4406-b560-e9539223e218

https://github.com/status-im/status-mobile/assets/52490791/12b906ef-bc7b-44dd-a8df-7002334f8b40

### Expected result:
The assets sending page is opened (page where user can enter assets amount)

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19697

### Summary
This PR fixes the send navigation flow where the asset select screen or the input amount screen gets skipped after reaching the transaction page then pressing back, then going through the flow again.

### Demo

https://github.com/status-im/status-mobile/assets/29354102/280ce15d-c42e-4a6b-93f0-82b640597af9

### CODE REVIEW

File: src/status_im/contexts/wallet/send/flow_config.cljs [hunk 1]
```diff
@@ -18,10 +18,7 @@
     :skip-step? (fn [db] (some? (get-in db [:wallet :ui :send :recipient])))}
    {:screen-id  :screen/wallet.select-asset
     :skip-step? (fn [db] (or (token-selected? db) (collectible-selected? db)))}
-   {:screen-id  :screen/wallet.send-input-amount
-    :skip-step? (fn [db]
-                  (or (not (token-selected? db))
-                      (some? (get-in db [:wallet :ui :send :amount]))))}
+   {:screen-id :screen/wallet.send-input-amount}
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/send/flow_config.cljs]: I think `input-amount` screen should never be skipped

File: src/status_im/contexts/wallet/send/select_asset/view.cljs [hunk 2]
```diff
@@ -67,6 +67,7 @@
                          (rf/dispatch [:wallet/clean-selected-token])
                          (rf/dispatch [:wallet/clean-selected-collectible])
                          (rf/dispatch [:navigate-back]))]
+    (rn/use-unmount #(rf/dispatch [:wallet/clean-selected-token]))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/send/select_asset/view.cljs]: When going back from the select asset screen we need to clean the selected token

Comment (J-Son89) [reply src/status_im/contexts/wallet/send/select_asset/view.cljs]: yep this is the main thing! 🙏

File: src/status_im/contexts/wallet/send/flow_config.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/send/flow_config.cljs]: yeah seems right to me too!

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/send/flow_config.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/flow_config.cljs]: When we want to send a collectible instead of a regular token, we don't navigate to `:screen/wallet.send-input-amount`. For collectibles with balance greater than 1 (could be ERC-1155 or community tokens), we have `:screen/wallet.select-collectible-amount`. Am I missing something?

Comment (J-Son89) [reply src/status_im/contexts/wallet/send/flow_config.cljs]: Nope, you're correct Brian! 
I forgot about that

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/flow_config.cljs]: Thanks @briansztamfater! Updated it to skip when `tx-type` is collectible

Comment (J-Son89) [reply src/status_im/contexts/wallet/send/flow_config.cljs]: We don't want that either, because there are multiple collectibles.
But in the case of multiple collectibles the screen is different

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/flow_config.cljs]: @J-Son89 @briansztamfater is there a case where we need to navigate to `:screen/wallet.send-input-amount` when sending a collectible?

File: src/status_im/contexts/wallet/send/flow_config.cljs [hunk 3]
```diff
@@ -18,10 +18,8 @@
     :skip-step? (fn [db] (some? (get-in db [:wallet :ui :send :recipient])))}
    {:screen-id  :screen/wallet.select-asset
     :skip-step? (fn [db] (or (token-selected? db) (collectible-selected? db)))}
-   {:screen-id  :screen/wallet.send-input-amount
-    :skip-step? (fn [db]
-                  (or (not (token-selected? db))
-                      (some? (get-in db [:wallet :ui :send :amount]))))}
+   {:screen-id :screen/wallet.send-input-amount
+    :skip-step? (fn [db] (= (get-in db [:wallet :ui :send :tx-type]) :collectible))}
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/flow_config.cljs:22]: Maybe use `(collectible-selected? db)`

**Review by briansztamfater — APPROVED** [review]

File: src/status_im/contexts/wallet/send/flow_config.cljs (hunk 3 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/flow_config.cljs:22]: @briansztamfater I can use it, but why is it's logic that way it is -- Is there a case where we can have a collectible-stored`:wallet :ui :send :collectible` and the value of `:wallet :ui :send :tx-type` is not `:collectible` ?

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Thanks for your navigation fix!
Checked on both platforms, works good 🙌.

Failed e2e are not related.
You can merge your PR.
