### PR TITLE
Fix account-card component UI

### LINKED ISSUE #17449: Fix account-card component UI
The UI should be pixel-perfect according to this design:

[Designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=19513-197699&mode=design&t=IN4sK2eDaNyuyJ19-0)

### PR DESCRIPTION
**Pull request by mmilad75**
fixes #17449 

### Summary

|Android|iOS|
|-|-|
|Screenshot 2023-10-09 at 16 36 08Screenshot 2023-10-09 at 16 35 59|Screenshot 2023-10-09 at 15 57 27Screenshot 2023-10-09 at 15 57 41|

### CODE REVIEW

File: src/quo2/components/wallet/account_card/component_spec.cljs [hunk 1]
```diff
@@ -38,6 +38,11 @@
       (h/render [account-card/view data])
       (h/is-truthy (h/get-by-text empty-username))))
 
+  (h/test "Renders Missing Keypair"
+    (let [data (get-test-data :missing-keypair false false false true)]
```
Comment (J-Son89) [inline src/quo2/components/wallet/account_card/component_spec.cljs]: it's hard to see what the test data is with this permutation of true/false. 
Could you refactor the function `get-test-data` and instead take a map? we can then just add `true` for the values we are setting and leave out the `false` values as it will default to `nil` anyway. will make it much easier to read these tests 👍

Comment (mmilad75) [reply src/quo2/components/wallet/account_card/component_spec.cljs]: Sure

File: src/quo2/components/wallet/account_card/style.cljs [hunk 2]
```diff
@@ -3,32 +3,37 @@
...
     colors/white))
 
 (defn card
-  [{:keys [customization-color watch-only? metrics? theme pressed?]}]
+  [{:keys [customization-color type theme pressed?]}]
   {:width              162
-   :height             (if metrics? 88 68)
-   :background-color   (if watch-only?
-                         (colors/theme-colors colors/neutral-80-opa-5 colors/neutral-95 theme)
+   :background-color   (when (not= :watch-only type)
```
Comment (J-Son89) [inline src/quo2/components/wallet/account_card/style.cljs]: @mmilad75 can this be handled with the custom-color overlay? we used it before on some component we worked on together

Comment (J-Son89) [reply src/quo2/components/wallet/account_card/style.cljs]: this would make it work with the current colors mechanism. 

one thing to note about it is that the colors are always using the -50 suffix when there is opacity in the color resolver. I have this addded to the internal mechanism here: 
https://github.com/status-im/status-mobile/pull/17567/files#diff-2ad5069d9e72acebf9104695abaf82e7264cc4bfa13187904738f39003b61e9b

and that's why I think the overlay is needed as this will add /remove the 10% opacity to these colors that is used here.

File: src/quo2/components/wallet/account_card/style.cljs [hunk 3]
```diff
@@ -102,3 +111,25 @@
 
 (def metrics-icon-container
   {:margin-left 4})
+
+(defn gradient-start-color
+  [theme]
+  (colors/theme-colors
+   (colors/custom-color :army 50 0)
```
Comment (J-Son89) [inline src/quo2/components/wallet/account_card/style.cljs]: these should be using `customization-color` prop and not fixed `:army` key

File: src/quo2/components/wallet/account_card/style.cljs [hunk 4]
```diff
@@ -102,3 +111,25 @@
...
+   colors/white-opa-2
+   theme))
+
+(def gradient-end-color
+  (colors/custom-color :army 50 6))
```
Comment (J-Son89) [inline src/quo2/components/wallet/account_card/style.cljs]: same here, needs `customization-color`

File: src/status_im2/contexts/quo_preview/wallet/account_card.cljs [hunk 5]
```diff
@@ -72,14 +74,24 @@
      :emoji               "🍑"}
 
     :watch-only
-    {:name             "Alisher account"
+    {:name             "Ben’s fortune"
```
Comment (J-Son89) [inline src/status_im2/contexts/quo_preview/wallet/account_card.cljs]: Bens been hijacking accounts 🔪

File: src/quo2/components/wallet/account_card/view.cljs [hunk 6]
```diff
@@ -96,12 +108,11 @@
...
             :on-press-out on-press-out
             :style        (style/card {:customization-color customization-color
-                                       :watch-only?         watch-only?
-                                       :metrics?            metrics?
+                                       :type                type
                                        :theme               theme
                                        :pressed?            @pressed?})
             :on-press     on-press}
-           (when (and customization-color (not watch-only?))
+           (when (and customization-color (and (not watch-only?) (not missing-keypair?)))
```
Comment (J-Son89) [inline src/quo2/components/wallet/account_card/view.cljs]: hmm, I think you try use this here and instead provide  20% opacity to the overlay. this mechanism will do the rest ( I hope 🙏 ) :)

File: src/quo2/components/wallet/account_card/style.cljs (hunk 2 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/style.cljs]: The `customization-colors/overlay` component is already used in the component but serving a different purpose.

Comment (J-Son89) [reply src/quo2/components/wallet/account_card/style.cljs]: yes but I think it still needs to get used for this use case here, pretty sure it's the same concept just using opacity which should get passed to the overlay in these cases

Comment (J-Son89) [reply src/quo2/components/wallet/account_card/style.cljs]: Oh actually, sorry the opacity does not need to get added to the overlay. It's actually in the background color. But you still use the overlay and just a set value of 20% opacity ok the background color. The overlay should do the test I think. We should try this out anyway 👍

File: src/quo2/components/wallet/account_card/style.cljs (hunk 3 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/style.cljs]: Done

File: src/quo2/components/wallet/account_card/style.cljs (hunk 4 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/style.cljs]: Done

File: src/status_im2/contexts/quo_preview/wallet/account_card.cljs (hunk 5 above)
Comment (mmilad75) [reply src/status_im2/contexts/quo_preview/wallet/account_card.cljs]: Yeah :D

File: src/quo2/components/wallet/account_card/view.cljs [hunk 7]
```diff
@@ -155,10 +172,11 @@
 (defn- view-internal
   [{:keys [type] :as props}]
   (case type
```
Comment (J-Son89) [inline src/quo2/components/wallet/account_card/view.cljs]: pretty sure this could be:
```

  (case type
    (:watch-only :default :empty :missing-keypair) [user-account props]
    :add-account [add-account-view props]
    nil)
```

File: src/quo2/components/wallet/account_card/component_spec.cljs [hunk 8]
```diff
@@ -6,7 +6,7 @@
 (def empty-username "Account 1")
 
 (defn get-test-data
-  [type watch-only? empty-type? loading? metrics?]
+  [{:keys [type watch-only? empty-type? loading? metrics?] :or {metrics? true}}]
```
Comment (J-Son89) [inline src/quo2/components/wallet/account_card/component_spec.cljs]: given that this is only a component test it's not such a big issue, however imo when creating an api it is better to default the value to false. 
consider changing the name to the negation and remove the default value. e.g:  use`:no-metrics?` instead.
it's strange to have to set `false` to a prop value.

File: src/quo2/components/wallet/account_card/view.cljs [hunk 9]
```diff
@@ -53,39 +53,52 @@
...
-     {:color (colors/theme-colors (if watch-only? colors/neutral-50 colors/white-opa-70)
+     {:color (colors/theme-colors (if (or (= :missing-keypair type)
+                                          (= :watch-only type))
+                                    colors/neutral-50
+                                    colors/white-opa-70)
                                   colors/white-opa-70
                                   theme)
       :size  16}]]])
 
+(defn- gradiant-overview
```
Comment (ilmotta) [inline src/quo2/components/wallet/account_card/view.cljs]: Typo -> `gradient`

File: src/quo2/components/wallet/account_card/view.cljs [hunk 10]
```diff
@@ -114,19 +126,24 @@
...
            (when metrics?
              [rn/view {:style style/metrics-container}
-              [metrics-percentage watch-only? theme percentage-value]
+              [metrics-percentage type theme percentage-value]
               (when (not= :empty type)
-                [metrics-info watch-only? theme amount])])])))))
+                [metrics-info type theme amount])])
+           (when watch-only?
+             [gradiant-overview theme customization-color])
+          ])))))
```
Comment (ilmotta) [inline src/quo2/components/wallet/account_card/view.cljs]: This line should me joined with the previous one.

File: src/quo2/foundations/colors.cljs [hunk 11]
```diff
@@ -109,6 +109,7 @@
 
 ;; with transparency
 (def white-opa-0 (alpha white 0))
+(def white-opa-2 (alpha white 0.02))
```
Comment (ilmotta) [inline src/quo2/foundations/colors.cljs]: I couldn't find this 2% value in Figma https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?type=design&node-id=619-5995&mode=design&t=u3UMGJzY0MPaJBIW-0

If it's not there, why is it being added here and used in the component?

To be fair, `white-opa-95` was already here before your PR, and it's also not in the foundations Figma file too, but it's better if we don't make things worse, i.e. the namespace should only have colors that match Figma Foundations exactly.

File: src/quo2/components/wallet/account_card/style.cljs [hunk 12]
```diff
@@ -102,3 +111,26 @@
...
+  {:position      :absolute
+   :bottom        0
+   :top           0
+   :left          0
+   :right         0
+   :border-radius 16})
+
+(defn alert-icon-color
+  [theme]
+  (colors/theme-colors colors/neutral-50 colors/white theme))
```
Comment (ilmotta) [inline src/quo2/components/wallet/account_card/style.cljs]: No big deal @mmilad75, but there's a recommendation in the guidelines to not define component properties in the `style` ns. https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md#dont-define-properties-in-styles-ns

These functions like `alert-icon-color` or `gradient-end-color` that are not returning maps are being used for component properties. One could argue the color is also a style, but another one could argue that the color is pre-processed in the icon component before being used, so it's not used "directly" as a style prop.

When we want to clean up the `view` namespace from component properties, we have been moving them to a `<component>/properties.cljs` file.

File: src/quo2/components/wallet/account_card/view.cljs (hunk 7 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/view.cljs]: Done

File: src/quo2/components/wallet/account_card/component_spec.cljs (hunk 8 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/component_spec.cljs]: Done

File: src/quo2/components/wallet/account_card/view.cljs (hunk 9 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/view.cljs]: Done

File: src/quo2/components/wallet/account_card/view.cljs (hunk 10 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/view.cljs]: Done

File: src/quo2/components/wallet/account_card/style.cljs (hunk 12 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/style.cljs]: Done

File: src/quo2/foundations/colors.cljs (hunk 11 above)
Comment (mmilad75) [reply src/quo2/foundations/colors.cljs]: Done. The designs were changed to `neutral-95`

File: src/quo2/components/wallet/account_card/style.cljs (hunk 2 above)
Comment (mmilad75) [reply src/quo2/components/wallet/account_card/style.cljs]: The overlays are different in different conditions, that's why I used a custom overlay for this component. I don't think it can be done by the `custom-overlay`

Comment (J-Son89) [reply src/quo2/components/wallet/account_card/style.cljs]: Yeah I reached out to @mariocnovoa  to address this. Leave it for now and we will come back to this component once design has a solution for it

**Review by ilmotta — APPROVED** [review]
PR LGTM 🚀

File: src/quo2/components/wallet/account_card/style.cljs (hunk 12 above)
Comment (ilmotta) [reply src/quo2/components/wallet/account_card/style.cljs]: Awesome!

File: src/quo/components/wallet/account_card/properties.cljs [hunk 13]
```diff
@@ -0,0 +1,20 @@
+(ns quo.components.wallet.account-card.properties
```
Comment (OmarBasem) [inline src/quo/components/wallet/account_card/properties.cljs:1]: What is this properties file? Why are not these in `style` ?

**Review by OmarBasem — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

File: src/quo/components/wallet/account_card/properties.cljs (hunk 13 above)
Comment (ilmotta) [reply src/quo/components/wallet/account_card/properties.cljs:1]: Probably because the values are not being used in style maps directly (section `Don't define properties in styles ns` in the guidelines). To me, they shouldn't be in the `style` ns, and could be directly on the same `view` file or in the properties file as @mmilad75 did.

Comment (mmilad75) [reply src/quo/components/wallet/account_card/properties.cljs:1]: Yes

File: src/quo/foundations/colors.cljs [hunk 14]
```diff
@@ -110,6 +110,7 @@
 
 ;; with transparency
 (def white-opa-0 (alpha white 0))
+(def white-opa-2 (alpha white 0.02))
```
Comment (J-Son89) [inline src/quo/foundations/colors.cljs]: we can remove this now?

**Review by J-Son89 — APPROVED** [review]

File: src/quo/foundations/colors.cljs (hunk 14 above)
Comment (mmilad75) [reply src/quo/foundations/colors.cljs]: Yes, right

**Comment by pavloburykh** [comment]
@mmilad75 no issues from my side. ready for design review. cc @Francesca-G

**Review by Francesca-G — APPROVED** [review]
Component looks good, adding follow up required due to some vertical spacing issues, as commented [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3446%3A227419&mode=design&t=kA27Mrb2uvtnpopA-1) :)

**Review by Francesca-G — APPROVED** [review]
