### PR TITLE
Show the users that the keycard feature will be coming soon

### LINKED ISSUE #19547: Show the users that the keycard feature will be coming soon
# Bug Report

## Problem 
During onboarding, when pressing on the keycard feature, we show the "not implemented" alert. We should either disable the button or let the user know that the feature will be coming soon. Best is to discuss with the design team (maybe there could be a generic solution to show "coming soon" functionality within the app).

#### Expected behavior
The keycard onboarding flow shows the "not implemented" alert

#### Actual behavior
The user can see that the feature will be coming soon

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #19547

Designers decided to just hide the button for now

### CODE REVIEW

File: src/status_im/contexts/onboarding/new_to_status/view.cljs [hunk 1]
```diff
@@ -49,12 +49,13 @@
                                  [:screen/onboarding.enter-seed-phrase
                                   :screen/onboarding.new-to-status]])}]
       [rn/view {:style style/space-between-suboptions}]
-      [quo/small-option-card
-       {:variant  :icon
-        :title    (i18n/label :t/use-keycard)
-        :subtitle (i18n/label :t/use-keycard-subtitle)
-        :image    (resources/get-image :use-keycard)
-        :on-press #(js/alert "TODO: to be implemented")}]]]))
+      (when config/show-not-implemented-features?
```
Comment (ibrkhalil) [inline src/status_im/contexts/onboarding/new_to_status/view.cljs:52]: This doesn't show that the feature is coming soon, This'll hide the button based on the feature flag's value.

Comment (flexsurfer) [reply src/status_im/contexts/onboarding/new_to_status/view.cljs:52]: yes, that was a decision just hide a button

**Review by ibrkhalil — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by churik** [comment]
Hello!
The e2e results are reviewed, the failed tests are not related to the PR.
PR can proceed to the next stage, thanks
