### PR TITLE
[#15655] Resolve messages with markdown on Jump To screen

### LINKED ISSUE #15277: Uncompressed chat key is displayed instead of mention  in message preview within Shell tab
**Steps:**

1. Open any chat
2. Send message containing mention
3. Tap "Jump to" button to open Shell screen
4. Pay attention at  message preview within closed chat tab

**Expected result:** mention is displayed in message preview

**Actual result:** Uncompressed chat key is displayed in message preview

photo_2023-03-07 12 23 22

https://user-images.githubusercontent.com/97245802/223394661-e6fb10a4-0dc9-4c05-874c-1c9c14a5aeea.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #15655: Markdown symbols are shown on "Jump to" screen
# Bug Report

## Problem 
If the last message in chat contains markdown, raw text is shown in "Jump to"
Monosnap 2023-04-14 13-01-56

#### Expected behavior
can see text with applied markdown

### Reproduction

1) Open Status
2) Send a message with a markdown (i.e. in `__`)
3) Tap on "Jump to"

### Additional Information

- Status version: nightly 14/04/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by rasom**
fix #15655 
fix #15277

status: ready

### CODE REVIEW

File: src/status_im2/utils/simple_message_resolver.cljs [hunk 1]
```diff
@@ -0,0 +1,24 @@
+(ns status-im2.utils.simple-message-resolver
```
Comment (J-Son89) [inline src/status_im2/utils/simple_message_resolver.cljs]: nit: why not `status-im2.utils.message-resolver` -> do we have other variants of message resolvers?

File: src/status_im2/contexts/shell/cards/view.cljs [hunk 2]
```diff
@@ -46,13 +47,21 @@
...
      (case content-type
        constants/content-type-text
-       [quo/text
-        {:size            :paragraph-2
-         :weight          :regular
-         :number-of-lines 1
-         :ellipsize-mode  :tail
-         :style           style/last-message-text}
-        data]
+       (if (:parsed-text data)
```
Comment (J-Son89) [inline src/status_im2/contexts/shell/cards/view.cljs]: consider putting in a let var

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/utils/simple_message_resolver.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/utils/simple_message_resolver.cljs]: Related to this, even if we had other variants, in Clojure I think it's more common to avoid namespace proliferation, since it's not like we need one class for each file, or in other words, one resolver for each file. Probably as you suggested @J-Son89 is enough to be future proof in case other resolvers need to be defined.

File: src/status_im2/utils/simple_message_resolver.cljs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+  (:require [utils.re-frame :as rf]))
+
+(defn resolve-message
```
Comment (ilmotta) [inline src/status_im2/utils/simple_message_resolver.cljs]: @rasom, would you mind adding a unit test for this function? I actually think you had created one from another PR, no? Or at least it was very similar to this implementation.

File: src/status_im2/utils/simple_message_resolver.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im2/utils/simple_message_resolver.cljs]: We have some, at least two other cases. The naming is kind of arbitrary here, I can generalise it to `message-resolver` but I don't want to work on moving other cases of it to this ns (at least not under this PR).

File: src/status_im2/contexts/shell/cards/view.cljs (hunk 2 above)
Comment (rasom) [reply src/status_im2/contexts/shell/cards/view.cljs]: kind of fixed

File: src/status_im2/utils/simple_message_resolver.cljs (hunk 3 above)
Comment (rasom) [reply src/status_im2/utils/simple_message_resolver.cljs]: well it is already in this PR, I just renamed test's ns

Comment (ilmotta) [reply src/status_im2/utils/simple_message_resolver.cljs]: You're right about that! Sorry ;)

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/utils/simple_message_resolver.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im2/utils/simple_message_resolver.cljs]: renamed namespace

**Review by Parveshdhull — APPROVED** [review]
Great work :tada: 
Probably also fixes https://github.com/status-im/status-mobile/issues/15277

**Comment by rasom** [comment]
@Parveshdhull yes it should, thanks

**Comment by churik** [comment]
Thanks for your amazing work!
e2e failures are not related to PR.
Tested Jump to on different types of chat and different messages.

**Devices:**
- IPhone 12 Mini (IOS 16)
- Xiaomi Mi Note 9 Pro (Android 10)
