### PR TITLE
[#18495] Fix token not ready for next screen

### LINKED ISSUE #18469: [Android] Native keyboard remains opened after navigating to Send Asset screen
### Steps:
1. Open select assets page
2. Tap on the 'search assets' input field to enable the keyboard.
3. Leave the keyboard open and select some asset to navigate to the send asset screen.

### Actual result:
After going to the send asset screen, the device's native keyboard remains open resulting 2 keyboards showing

https://github.com/status-im/status-mobile/assets/52490791/d17a77b7-7f84-40de-9324-6fd97b839246

### Expected result:
The device's native keyboard should not be enabled

### Device:
Real device: Pixel 7a, Android 13

### ENV:
Nightly [11 Jan 2024]

### LINKED ISSUE #18493: Send flow: "maxiumum call stack exceeded" error on the input_amount screen
The above error happens randomly when reaching the input_amount screen in debug mode.

Steps to reproduce:

Just going normally through the send flow: 
1. Enter address
2. Select token
3. Upon reaching the input_amount screen you may get that error

### LINKED ISSUE #18495: Send flow: Asset need to be selected twice
When going back from send_input screen to select_asset screen to choose a different asset, the selected asset does not update. 

The user needs to go back again and select the asset again (twice)

### LINKED ISSUE #18524: Wrong asset is shown on the 'sent assets' screen
### Steps:
1. Go to the 'select assets' screen.
2. Select any asset (now the user is navigated to the send asset page where the selected asset is not shown initially).
3. Go back to the 'select assets' screen.
4. Select any other asset.

### Actual result:
- No asset is shown after the initial asset selection. (After step 2. See 3rd  second on the record)
- The previously selected asset is shown (After step 4. Ethereum is selected but DAI is shown instead, see 7th second on the record)

https://github.com/status-im/status-mobile/assets/52490791/11036214-7627-4158-8477-0d3ec877a4ff

### Expected result:
The selected asset should be shown.

### Device:
iPhone 11 Pro max, IOS 16

### Logs:

[logs.zip](https://github.com/status-im/status-mobile/files/13947449/logs.zip)

### ENV:
NIghtly [16 Jan 2024]

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #18495
fixes #18524
fixes #18493

Update:
 fixes #18469

### Summary

This PR fixes the exception thrown whilke picking an asset to send in this screen:
image

And after that, we needed to pick twice the same token in order to actually send it, now it works fine.

### Review notes
The behavior happened because re-frame didn't had the db changes ready before navigating, IDK why this is happening.

### Steps to test

- Open Status
- Add an address owning assets
- Select the added account, click on the send button, pick another adddress to send, pick an asset

The behavior is now fixed. 

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -46,20 +46,24 @@
...
+(rf/reg-event-fx
+ :wallet/send-select-token
  (fn [{:keys [db]} [{:keys [token stack-id]}]]
    {:db (-> db
             (update-in [:wallet :ui :send] dissoc :collectible)
             (assoc-in [:wallet :ui :send :token] token))
-    :fx [[:navigate-to-within-stack [:wallet-send-input-amount stack-id]]]}))
+    :fx [[:dispatch-later
+          {:ms       1
+           :dispatch [:navigate-to-within-stack [:wallet-send-input-amount stack-id]]}]]}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs]: For some reason, when we navigate and read the `:token` value from a sub, re-frame doesn't have the value ready, it's `nil`, for following queries to the sub it is already populated.

Using `:dispatch-later` was the only one solution I found that worked, I also tried `:dispatch` as:
```clojure
:fx [[:dispatch [:navigate-to-within-stack [...]]]]
```
But it wasn't enough.

cc: @ilmotta 
Re-frame is supposed to first perform the `:db` update and then the `:fx` but it seems this is not the case :thinking: 

If this is happening here, I think this also happens in other screens, we noticed it because we are using this value to initialize a component (in a reagent form-2). In our case, a component throws an exception if we don't pass the expected value

File: src/status_im/contexts/wallet/send/select_asset/view.cljs [hunk 2]
```diff
@@ -17,22 +17,21 @@
...
-          fiat-value       (utils/total-token-fiat-value currency token)
-          fiat-formatted   (utils/get-standard-fiat-format crypto-formatted currency-symbol fiat-value)]
-      [quo/token-network
-       {:token       (:symbol token)
-        :label       (:name token)
-        :token-value (str crypto-formatted " " (:symbol token))
-        :fiat-value  fiat-formatted
-        :networks    (:networks token)
-        :on-press    on-press}])))
+  [token _ _ {:keys [currency currency-symbol]}]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/select_asset/view.cljs:20]: It was a form-2 component, but it wasn't needed. :eyes:  I've seen this pattern a few times in our code, let's try to fix it if we find it :smile:

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 3]
```diff
@@ -94,7 +94,11 @@
                                         (if (> num-value current-limit-amount)
                                           (reset! input-value (str current-limit-amount))
                                           (reset! input-value v))
-                                        (reagent/flush))))]
+                                        (reagent/flush))))
+        on-navigate-back          (fn []
+                                    (rf/dispatch [:wallet/clean-selected-token])
+                                    (rf/dispatch
+                                     [:navigate-back-within-stack :wallet-send-input-amount]))]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: Just added a callback that clears the picked token when we navigate back

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 4]
```diff
@@ -29,11 +29,11 @@
 (defn valid-input?
   [current v]
   (let [max-length          12
-        length-owerflow?    (>= (count current) max-length)
+        length-overflow?    (>= (count current) max-length)
         extra-dot?          (and (= v dot) (string/includes? current dot))
         extra-leading-zero? (and (= current "0") (= "0" (str v)))
         non-numeric?        (re-find not-digits-or-dot-pattern (str v))]
-    (not (or non-numeric? extra-dot? extra-leading-zero? length-owerflow?))))
+    (not (or non-numeric? extra-dot? extra-leading-zero? length-overflow?))))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:37]: just a typo :eyes:

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/send/events.cljs]: Thanks for copying me @ulisesmac. I would like to investigate this problem as well, unfortunately this week I can't. It's not clear to me either why that happened, but we should find the root cause. Maybe if we find what's going on we can avoid such workarounds. A GH issue seems appropriate too.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 5]
```diff
@@ -103,31 +107,28 @@
...
-                                                           100)))
-                       [@input-value])
-        [rn/view
-         {:style style/screen}
+        (rn/use-effect
+         (fn []
+           (rf/dispatch [:wallet/clean-suggested-routes])
+           (when-not (or (empty? @input-value)
+                         (<= input-num-value 0)
+                         (> input-num-value (:amount @current-limit)))
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: Shouldn't the current limit amount be included in the dependencies' vector?

File: src/status_im/contexts/wallet/send/select_asset/view.cljs [hunk 6]
```diff
@@ -17,22 +17,21 @@
...
+  (let [on-press         #(rf/dispatch [:wallet/send-select-token
+                                        {:token    token
+                                         :stack-id :wallet-select-asset}])
+        token-units      (utils/total-token-units-in-all-chains token)
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/send/select_asset/view.cljs:24]: Not from your PR, but I wonder if we are putting too much computation on the view layer. The fact that we hide them inside `wallet.common.utils` doesn't change anything. Ideally, we should design the views to use subscriptions and benefit from caching. It may not be a trivial refactor because best would be to not use subscriptions inside the component rendered by `flat-list`.

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs]: Yeah! I'll open the issue, I was thinking that maybe the subs were too many, and they take longer to propagate than the rendering of the screen (weird, since maybe the screen is heavier) :thinking:

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: I Just modified the code style here :eyes: 

But here's my guess based on what I read, but I don't fully know the internals of this component, I think @briansztamfater or @J-Son89 are more involved.

My perspective:

This `current-limit` atom is the thing being initialized with the values from the problematic sub, I tried removing it, but noticed it wasn't too different.

`current-limit` is not an atom "directly" updated by the user, it just stores a two key map with `:amount` and `:currency`, it changes its values based on a `crypto?` predicate:

```clojure
 (reset! current-limit (if crypto?
                        {:amount   limit-crypto
                         :currency token-symbol}
                        {:amount   limit-fiat
                         :currency currency}))
```

Since the values of this map aren't dynamic (they are being gathered from subs inside the "on mount" part of a `from-2` component), I think they could just be regular vars:

```clojure
(let [crypto-limit {:amount   limit-crypto
                    :currency token-symbol}
      fiat-limit   {:amount   limit-fiat
                    :currency currency}])
```

And use them based on `crypto?`.

So,  this `use-effect` isn't directly listening to changes in `current-limit`, `current-limit` works like a place to store values, so maybe it's not needed to add it to the dependency vector.

File: src/status_im/contexts/wallet/send/select_asset/view.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/select_asset/view.cljs:24]: Regarding to performance, I haven't  noticed any problem, even in users with many tokens.

Actually, recently I compared the performance (as a regular user) with other flat-list we use (such as channel list in a community or the contacts list) and this one behaves really good.

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/send/events.cljs]: perhaps for now this deserves a comment to explain why :) (in the codebase)

File: src/status_im/contexts/wallet/send/select_asset/view.cljs (hunk 6 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/send/select_asset/view.cljs:24]: I wasn't saying it's a problem now, good to hear it's good! o/

Theoretically we could get better performance with subscriptions, but it's not always true because comparing large data structures to get a cache hit isn't cheap, and our mobile client passes a ton of data around.

This is yet another thing we could all design better, subscriptions shouldn't return too much, ideally only the minimum the views need. Many times we subscribe to large data structures when we only need a few values, this is quite bad.

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs]: Yeah! I will add it @J-Son89

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 5 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: It's a lot of context to ask from a dev to know why the amount is not in the deps vector. But it's your call @ulisesmac :)

Side note: I've fixed so many bugs due to missing dependencies in `useEffect` that, by default, I always prefer to add dynamic values used inside `useEffect` in its deps vector. There are even linters forcing this rule. There are exceptions for sure, but I tend to start with this safer practice.

**Review by briansztamfater — APPROVED** [review]

**Comment by ulisesmac** [comment]
Update, since the change to solve:
- #18469

Was very small, I decided to add it in this PR

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs]: @J-Son89  done!

**Review by OmarBasem — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by pavloburykh** [comment]
**QA notes:**

Check [issue](https://github.com/status-im/status-mobile/pull/18539#issuecomment-1898458585) is not reproducible in this PR.

**Comment by pavloburykh** [comment]
@ulisesmac thanks for the PR. 

Please, do not forget to move PRs from REVIEW to E2E column once PR is reviewed and ready for QA. 

Could you please rebase current PR, resolve conflicts and after that move to E2E column to trigger e2e run? Thank you.

**Comment by ulisesmac** [comment]
> @ulisesmac thanks for the PR.
> 
> Please, do not forget to move PRs from REVIEW to E2E column once PR is reviewed and ready for QA.
> 
> Could you please rebase current PR, resolve conflicts and after that move to E2E column to trigger e2e run? Thank you.

Done! thanks

**Review by vkjr — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac , thank you for the PR. Unfortunately, the issue mentioned in https://github.com/status-im/status-mobile/pull/18532#issuecomment-1904093147 is still occurring, but this time on iOS. Unfortunately, I can't find the exact steps to reproduce it. For me, it happens randomly. Hope logs can show what going wrong

### ISSUE 1: [IOS] null is not an object (evaluating 'i.eq') error when selecting token for sending

### Steps:
1. Recover user with tokens
2. Open wallet - Send - My accounts - Select account - Select token
3. Observe the result

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/eec2ad0d-19e4-4d43-909c-92c7bf8ec3ce

### Expected result: 
No error after token selection

### Device:
iPhone 11 Pro max, IOS 16

### Logs:
[status_logs (1).zip](https://github.com/status-im/status-mobile/files/14035393/status_logs.1.zip)

**Comment by VolodLytvynenko** [comment]
Can't find exact steps to reproduce this issue. Sometimes it is required to go through the steps at least 10 times to reproduce it. Hope logs can help.

## ISSUE 2: Inability to enter value in the input field on the send assets page

### Steps:
1. Recover user with tokens
2. Open wallet - Send - My accounts - Select account - Select token
3. Navigate back ->  Select another token
4. Attempt to input some available value.


### Actual result
The entered value is not displayed in the input field.



https://github.com/status-im/status-mobile/assets/52490791/62e1a47e-1936-472c-bd23-f08d5aa6ba38

### Expected Result:
The entered value should be displayed in the input field.

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14035399/Status-debug-logs.zip)

**Comment by ulisesmac** [comment]
Hi @VolodLytvynenko 

Thanks for your exhausting work on this PR.

I'll investigate it and solve it!

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs]: @ilmotta @J-Son89 

Just a quick update on this.

As reported by QA, seems this hack isn't working all the time, setting a custom timeout (like 16 or 32ms) is something I don't want to do, so I'll investigate the root cause or fix this issue in other ways than just delaying a dispatch.

**Comment by ulisesmac** [comment]
@J-Son89 @ilmotta @vkjr @briansztamfater @OmarBasem @smohamedjavid  I'll take some of your minutes :sweat_smile: 

Tagging all of you since I found a reason and a fix, I'd like to get your feedback about the fix.

As I thought before, this isn't an isolated issue. It's happening at least in another place within the app. I'll try to be too clear and give you all the context.

### What is happening?

We use a re-frame event to transfer info from one screen to other, then the event "calls" the effect `:navigate-to-within-stack` to navigate to the desired screen (we it do all the time, we set the parameters for the next screen to render and then navigate to it).

his is the event:  :eyes:  
```clojure
(rf/reg-event-fx
 :wallet/send-select-token
 (fn [{:keys [db]} [{:keys [token stack-id]}]]
   {:db (assoc-in db [:wallet :ui :send :token] token) ; <- we store in the DB
    :fx [[:navigate-to-within-stack [:wallet-send-input-amount stack-id]]]})) ; <- we navigate
```

The problem is that the following screen is using this info to initialize a reagent atom. The initialization ocurrs only once (at mount), so the sub has only one chance to have the value ready to be read.

Simplified version of the component:
```clojure
(defn component []
  (let [sub-value (rf/sub [:send-token]) ; executed only once
        my-atom   (reagent/atom sub-value)] ; if `sub-value` is `nil`, this atom 
                                            ; won't be properly initialized
    (fn []
      ,,,
      @my-atom
      ,,,
      )))

```

The result is that the sub is slower than the navigation, so it doesn't has the value ready :cry: and we have an exception.

### Why?

Re-frame is supposed to update the `:db` first, and then execute the `:fx`s  listed, so this behavior is strange at first sight. The db should be just ready.

Well, I investigated the reason and re-frame actually has the `:db` ready, the problem is the subscription propagation, the navigation is faster than the subscription propagation :disappointed: ... or at least that's what I thought at the beginning, so I printed the timestamp when the subscription handlers were executed.

Three subs are involved `:ui`, `:send` and `:send-token`

When the event was executed I got the following printed:

```
 LOG  Running "wallet-send-input-amount" with {"initialProps":{"componentId":"wallet-send-input-amount"},"rootTag":601}
 
 LOG  1705499859502 "COMPONENT MOUNTED!"  <- called when the component is initialized
 LOG  -------------------------------------------
      :wallet/wallet-send-token nil <- the value returned by the sub (nil)
      -------------------------------------------
 LOG  1705499859527 "UI sub " <- when :ui is ran
 LOG  1705499859529 "SEND sub"  <- when :send is ran
 LOG  1705499859529 "SEND TOKEN sub" <- when :send-token is ran
```

We can see there's a difference of ~25ms between `"COMPONENT MOUNTED!"` and `"UI sub"` :thinking: 

But if we use `:dispatch-later` to navigate something interesting happens:
```clojure
:fx [[:dispatch-later
      {:ms       1 ;<- just adding 1ms
       :dispatch [:navigate-to-within-stack [:wallet-send-input-amount stack-id]]}]]
```

```
LOG  1705500255393 "UI sub " 
LOG  1705500255395 "SEND sub"
LOG  1705500255395 "SEND TOKEN sub" <- we have the sub executed first
LOG  Running "wallet-send-input-amount" with {"initialProps":{"componentId":"wallet-send-input-amount"},"rootTag":681}
LOG  1705500255416 "COMPONENT MOUNTED!" <- the component mounts
LOG  -------------------------------------------
     :wallet/wallet-send-token {:description "Status Network Token (SNT)"} <- and we have the value ready! :smile: 
     -------------------------------------------
```

We get a difference of ~21ms between `"UI sub" and `"COMPONENT MOUNTED!", so it's clear the difference isn't due to  re-frame's slowness, since just by adding `1ms` we managed to get re-frame ready first.

(It's important to say that this approach doesn't always work, a few times 1ms is not enough.)

My conclusion is that the navigation locks the JS thread for some ms (around 20ms, probably one frame?). and it is executed ASAP, it's not waiting until the end of the current tick.

I found other place within the app that is doing the same:

Picking a collectible:

[Screencast from 2024-01-24 20-46-00.webm](https://github.com/status-im/status-mobile/assets/90291778/20b4fde1-1028-49d5-b17a-9741cf42c0d0)

Well, it's true that the db should be cleaned when leaving the screen, but it also let us see that for a moment we can see the previous re-frame value, and it's too noticeable!, but re-frame isn't that slow!, the explanation for this to happen could be again that the navigation is locking the JS thread.

### Solution

Since the navigation is an animation, and we want to first perform the tasks (mainly re-frame stuff) in the current tick and then navigate, the most obvious function to use is `js/requestAnimationFrame` (or `reagent.core/after-render` :speak_no_evil:).

So I did it. I wrapped the `navigate` and `navigate-to-within-stack` (in the ns `status-im.navigation.effects`) in a `requestAnimationFrame`.

The result in the collectibles:

[Screencast from 2024-01-24 20-54-33.webm](https://github.com/status-im/status-mobile/assets/90291778/a40610cd-4af8-446c-b452-b0eb12e1faf6)

It worked!
Also this PR's issue is solved, and we no longer need that `:dispatch-later` :partying_face: 

### Now what?

Is this a good solution? I tested the app as a regular user and didn't find any issue, but... will this fix create other problems? wdyt?

[Request Animation Frame docs](https://reactnative.dev/docs/animations#requestanimationframe)

**Comment by OmarBasem** [comment]
Thank you so much @ulisesmac for the extensive analysis!

> We get a difference of ~21ms between "UI sub" and "COMPONENT MOUNTED!", so it's clear the difference isn't due to re-frame's slowness, since just by adding 1ms we managed to get re-frame ready first.

I think this is common with timeouts in JS threads. Using something like `(js/setTimeout #() 1) will take more than 1ms to execute -- roughly will take 20ms.

> Since the navigation is an animation, and we want to first perform the tasks (mainly re-frame stuff) in the current tick and then navigate

I have faced a similar problem before when working with the lightbox. I needed to have some state ready in the db before the navigation, so I wrapped `navigate-to` with `reagent/next-tick` and it worked well:
```
(rf/defn navigate-to-lightbox
  {:events [:chat.ui/navigate-to-lightbox]}
  [{:keys [db]} shared-element-id screen-params]
  (reagent/next-tick #(rf/dispatch [:navigate-to :lightbox screen-params]))
  {:db (assoc db :shared-element-id shared-element-id)})
  ```
 
  Regarding `js/requestAnimationFrame` it seems to be a good solution also. Maybe you can try testing how many ms does it take in comparison to `reagent/next-tick` (if it will work)

**Comment by ulisesmac** [comment]
@Parveshdhull since you've been working a lot with the navigation, it'd be really good to have your feedback on this: https://github.com/status-im/status-mobile/pull/18532#issuecomment-1909279658

**Comment by ilmotta** [comment]
@ulisesmac, your analysis makes sense to me, and seems good. But I can't tell the implications further down the road.

In general I tend to avoid subscriptions in the mount phase because it turns the component non-reactive. It creates these sort of problems where we start to worry about the order things are rendered because we only have one chance to the get the correct value from the subscription. There are use cases where the subscription can be used in the mount phase, but they should be quite rare.

So I wonder if that sub in the mount phase is really how we should be doing this. But anyway, your idea about delaying navigation in the next tick seems good by me. But @Parveshdhull is our specialist :)

See my recent comment here https://github.com/status-im/status-mobile/pull/18517#discussion_r1463534067

**Comment by Parveshdhull** [comment]
Hi @ulisesmac, Thank you very much for pinging me and thank you for sharing you research.

> I found other place within the app that is doing the same: Picking a collectible:

In the case of collectible, we are seeing last collectible because we are requesting data from status-go.
```
(rf/dispatch [:wallet/get-collectible-details id])
(rf/dispatch [:navigate-to :wallet-collectible])
```
And there are several other steps before we have data. 
`signal received` -> `:wallet/get-collectible-details-done` -> `:wallet/store-last-collectible-details` then db is updated.
We probably should show a loading screen while we are fetching data.

 > The result is that the sub is slower than the navigation, so it doesn't has the value ready 😢 and we have an exception

Please can you clarify, what kind of exception and how to reproduce it.

```
(let [sub-value (rf/sub [:send-token]) ; executed only once
       my-atom   (reagent/atom sub-value)]
```
Probably it is just a example, but I am little curious why reagent atom? why shouldn't we directly use sub-value?

**Comment by Parveshdhull** [comment]
Hi @OmarBasem, Thank you very much for sharing your input and code.

> (reagent/next-tick #(rf/dispatch [:navigate-to :lightbox screen-params]))

This seems wrong to me, we should not make another dispatch call directly inside event.
We should create an effect, and move this dispatch call their.

**Comment by ulisesmac** [comment]
Hey @Parveshdhull 

>And there are several other steps before we have data.
signal received -> :wallet/get-collectible-details-done -> :wallet/store-last-collectible-details then db is updated.

Yeah, I think the Js/requestAnimationFrame just gave enough time to get a response on time :thinking: 

> We probably should show a loading screen while we are fetching data.

I think we should navigate once we have the data, not before requesting it.

> Please can you clarify, what kind of exception and how to reproduce it.

The exception and reproduction:
https://github.com/status-im/status-mobile/pull/18532#issuecomment-1907611733

Basically, we are performing some operations on the data stored in the reagent atom, when the atom has `nil`, we tray to do some operations on `nil` and the component breaks.

> Probably it is just a example, but I am little curious why reagent atom? why shouldn't we directly use sub-value?

The code is a little complex and too noisy to add it here, but it's in `status-im.contexts.wallet.send.input-amount.view` and the function is `f-view-internal`.

Yeah, it's just an example The sub value is used to initialize the atom. Then the component operates using the atom (with `swap!` or `reset!`)

**Comment by ulisesmac** [comment]
@ilmotta 

> In general I tend to avoid subscriptions in the mount phase because it turns the component non-reactive. It creates these sort of problems where we start to worry about the order things are rendered because we only have one chance to the get the correct value from the subscription. There are use cases where the subscription can be used in the mount phase, but they should be quite rare.

Yes, I thought the same, like in the first place the sub shouldn't be there, actually, my first attempt was to refactor the component, but I was thinking we wouldn't be not solving the main problem :thinking:  just avoiding it.

Probably we can define a pattern for this kind of screens, like:

"If you want initialize a reagent atom with a subscription's value, it means it shouldn't be a reagent atom, it should keep as  a subscription and just update the value inside (use `rf/dispatch` or `rf/dispatch-sync` instead of `reset!` or `swap!` to update the value)."


:thinking:

**Comment by ilmotta** [comment]
> @ilmotta
> 
> > In general I tend to avoid subscriptions in the mount phase because it turns the component non-reactive. It creates these sort of problems where we start to worry about the order things are rendered because we only have one chance to the get the correct value from the subscription. There are use cases where the subscription can be used in the mount phase, but they should be quite rare.
> 
> Yes, I thought the same, like in the first place the sub shouldn't be there, actually, my first attempt was to refactor the component, but I was thinking we wouldn't be not solving the main problem 🤔 just avoiding it.
> 
> Probably we can define a pattern for this kind of screens, like:
> 
> "If you want initialize a reagent atom with a subscription's value, it means it shouldn't be a reagent atom, it should keep as a subscription and just update the value inside (use `rf/dispatch` or `rf/dispatch-sync` instead of `reset!` or `swap!` to update the value)."
> 
> 🤔

I've noticed places initializing local state from subscriptions, often to copy the state from re-frame. The idea being that if the user goes back or closes the current screen, the global state is still intact. It's similar to how I've seen many times devs copying global state in the Redux store using `setState`, but at least in Redux apps we wouldn't see the state being copied outside the "renderer", but here with Reagent this is a possibility and can cause bugs.

And yes, there's a clean solution just using re-frame.

But... I think it's okay to subscribe at mount phase when we subscribe to data that can't possibly change. For example, this should be totally fine because the community ID from the screen params will never change.

```clojure
(defn view
  []
  (let [{id :community-id} (rf/sub [:get-screen-params])]
    (rf/dispatch [:foo id])
    (fn []
      ...)))
```

Now that Reagent is endangered, I'm a bit wary about investing energy into it. Makes me kind of sad... Let's see the next chapters...

**Comment by Parveshdhull** [comment]
> The exception and reproduction: [#18532 (comment)](https://github.com/status-im/status-mobile/pull/18532#issuecomment-1907611733)

I tried following the steps mentioned in the video on the emulator and device, but unfortunately, the issue was not reproducible for me.

I don't know why `:wallet/wallet-send-token` was nil in those cases, but I think the main problems are in `utils.money` and `status-im.contexts.wallet.common.utils`. We have so many js function calls there, without nil checks, I think we should fix them first. (I am not sure, but after adding those nil checks there, UI might look ok even if the token value is nil for 25ms)

Maybe @flexsurfer has seen this situation 👇
- Did we encounter a situation like this where we were navigating and updating the db in the same event, and once the screen was opened corresponding subscription was nil initially (then updated with some delay of ~25ms)?
- What problems did that cause? And how did we handle them?

More info in https://github.com/status-im/status-mobile/pull/18532#issuecomment-1909279658 https://github.com/status-im/status-mobile/pull/18532#issuecomment-1907611733 https://github.com/status-im/status-mobile/pull/18532#issuecomment-1910502741

> I think we should navigate once we have the data, not before requesting it.

Probably something to discuss with the design team, but freezing UI while data is getting fetched seems like bad UX. We have loading skeletons, indicators, etc. for this.

Also, it seems like an implementation problem in the case of the "Picking a collectible" situation. In my testing, I only saw status-go calls differ in traits, etc, other than that we already have required data in db that we can use instead of waiting from status-go. (probably we should create an issue for this)

**Comment by ulisesmac** [comment]
> Probably something to discuss with the design team, but freezing UI while data is getting fetched seems like bad UX. We have loading skeletons, indicators, etc. for this.

I think we won't be freezing the UI, just moving the navigation animation (that seems to lock the UI JS thread) to the end of the tick. It won't happen when we fetch data, it'll happen when we navigate.

We could instead create code to avoid this behavior, and that's ok too. but I think we won't be addressing the real problem. (actually, it was my first approach)

**Comment by ulisesmac** [comment]
So wdyt guys?
should I instead refactor the screen to avoid the issue with the subscription?

**Comment by ilmotta** [comment]
> So wdyt guys? should I instead refactor the screen to avoid the issue with the subscription?

@ulisesmac I don't know if I can be of any help in this discussion, but subscriptions called in the mount phase are almost always a bug waiting to happen because it turns the component non-reactive. That sort of breaks the React and re-frame paradigm and weird stuff start to happen.

Subs `:profile/profile`, `:wallet/wallet-send-token`, and `:wallet/wallet-send-loading-suggested-routes?` shouldn't be called in the mount phase. Even if this doesn't solve your issue, I think it's the way to go.

**Comment by ulisesmac** [comment]
@ilmotta yeah, I agree it's better to have code in that way.

**Comment by ulisesmac** [comment]
@Parveshdhull @ilmotta @OmarBasem @J-Son89 @briansztamfater 

Pinging you again, because this might be another problem related to navigating before letting re-frame propagate its state:

https://github.com/status-im/status-mobile/pull/18593#discussion_r1467911635

**Comment by ilmotta** [comment]
> @Parveshdhull @ilmotta @OmarBasem @J-Son89 @briansztamfater
> 
> Pinging you again, because this might be another problem related to navigating before letting re-frame propagate its state:
> 
> [#18593 (comment)](https://github.com/status-im/status-mobile/pull/18593#discussion_r1467911635)

Hey @ulisesmac, me again :)

Something tells me we should just not have these issues if the code assumed that data will **_eventually arrive_** and **_out of order due_** to the asynchronicity of React Navigation, RPC requests, JS timers here and there, animations and so on.

> Effects in `:fx` are actioned in order, so the dispatched events will be queued and, later handled, in order supplied. FIFO.
>
> -- https://github.com/day8/re-frame/blob/39adca93673f334dc751ee2d99d340b51a9cc6db/docs/api-builtin-effects.md#-dispatch

Hence, each individual effect may cause other operations to be scheduled, which will, in turn be processed in a separate queue or they will dispatch async operations (e.g. Navigation).

With this principle in mind, if our views are all properly subscribing to data, it shouldn't matter if the navigation finishes before the state is propagated, because the screen will react accordingly. If we want to avoid the view from flashing on screen with empty elements, then as @Parveshdhull said, we have techniques for loading indicators.

So to summarize my long train of thought, I believe by implementing the bare bones good practices to use re-frame (or any Redux app for that matter) we will arrive at something that just works, e.g no subs in the mount phase to initialize local state.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 7]
```diff
@@ -67,14 +68,14 @@
...
 
-(rf/reg-event-fx :wallet/send-select-token
+(rf/reg-event-fx
+ :wallet/send-select-token
  (fn [{:keys [db]} [{:keys [token stack-id]}]]
    {:db (assoc-in db [:wallet :ui :send :token] token)
-    :fx [[:dispatch-later
-          {:ms       1
-           :dispatch [:navigate-to-within-stack [:wallet-send-input-amount stack-id]]}]]}))
+    :fx [[:navigate-to-within-stack [:wallet-send-input-amount stack-id]]]}))
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/events.cljs:89]: Thanks @ulisesmac for warning about this PR and discussion! We need to update DB when navigating, so fx might not be what we want here. This would be replaced with a `dispatch` if we merge #18593, so better to reach to a common agreement before merging any of these PRs to avoid unnecessarily reverting changes. Context: https://github.com/status-im/status-mobile/pull/18593#discussion_r1468103430

Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/events.cljs:89]: Also, another topic, probably for other PR, but it is confusing to have navigation effects and events with same naming, like https://github.com/status-im/status-mobile/blob/972a88e7ccc9fd5fc697caa42919079a4da73859/src/status_im/navigation/events.cljs#L55 and https://github.com/status-im/status-mobile/blob/602b27105bcc4960a8748dd60af6bdc8967559c0/src/status_im/navigation/effects.cljs#L91
.......
or
.......

https://github.com/status-im/status-mobile/blob/972a88e7ccc9fd5fc697caa42919079a4da73859/src/status_im/navigation/events.cljs#L34 and https://github.com/status-im/status-mobile/blob/602b27105bcc4960a8748dd60af6bdc8967559c0/src/status_im/navigation/effects.cljs#L78

We should rename events to have navigation / namespace prefix as per our guidelines https://github.com/status-im/status-mobile/blob/5cc027a1f58a35f4b7980612a9080a621d134d6f/doc/new-guidelines.md#L364-L372

so events are like `:navigation/navigate-back`, `:navigation/navigate-back-to`, `:navigation/navigate-to`, `:navigation/navigate-to-within-stack`, etc, or even better they could be improved as `:navigation/pop`, `:navigation/pop-to`, `:navigation/push`, `:navigation/push-within-stack`, etc, to comply with common nomenclature for stack navigations

**Comment by ulisesmac** [comment]
It seems the approach the team want to take is to make the view reactive to these values.

TBH  I don't agree, if the `requestAnimationFrame` approach doesn't hurt, I'd take it, because I'm sure we will face these problems in other places too, or probably we are already facing them and devs are just silently doing some hacks.

@ilmotta 
> If we want to avoid the view from flashing on screen with empty elements, then as @Parveshdhull said, we have techniques for loading indicators.

Having a loading indicator for views that expect incoming data is completely OK, but having a loader for local state propagation is too much IMO.

In this case the user picks a token to make a transaction, then we navigate and the new view will "load" for ~25 ms, after that we'll show the token the user previously picked. No network calls or storage read involved in this process and we are "loading" or blinking. I think designing/implementing a loader component for these 25 ms is too much.

At least for me, prod builds are facing this issue almost all the time. So I'm going to solve it with a temporary blink and I'll open another issue to check what kind of loader we'll show.

**Comment by ilmotta** [comment]
> Having a loading indicator for views that expect incoming data is completely OK, but having a loader for local state propagation is too much IMO.

Completely agree here @ulisesmac, for local state sounds like a smell to have a loading indicator. Loading indicators should be used sparingly. Anything under ~100-200ms and it might be better to just not show the information until the data is ready, otherwise the user will see the indicator flash on screen pretty rapidly.

The thing to me is to understand what are the minimum data necessary to render the screen. It's about the granularity of the loading strategy. If the data also includes local state, so be it. The point is that the user shouldn't see too many elements flashing on screen (especially big ones) or see temporarily incomplete values while the data hasn't arrived (a problem we currently have when fetching permissions for a community).

Spotify on iOS happily shows me big 3 dots when the screen is not cached yet, and pop in small elements that arrive 1-2s later. Our designers don't like this approach, so sometimes it's also about personal preference.

Whatever the best UX is, that's where we should go 👍🏼

**Comment by ulisesmac** [comment]
Thanks to everyone for the effort reviewing this PR.

@VolodLytvynenko This PR is ready to get reviewed again, the issue is solved, however, there's a short blink when we visit the screen, it'll be addressed separately when this PR gets merged

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac. PR is tested and ready to be merged. Thank you for your work!
