### PR TITLE
fix: quo2 floating-shell-button click through

### LINKED ISSUE #15812: [IOS] Hard to open chat located in the bottom of the list behind 'jump to' button
### Steps to reproduce:
1. Create a few chats to show the last on the bottom of the screen
2. Try to tap on the last chat

### Actual result:
Hard to open chat located in the bottom of the list

https://user-images.githubusercontent.com/52490791/236162568-42ab3f11-9c78-4f63-96f5-0b11d25110a5.mp4

### Expected result:
Chat is opened

### Device:
iPhone 11 Pro Max, Ios 16

### ENV:
Nightly: 4 May 2023

### PR DESCRIPTION
**Pull request by ajayesivan**
fix #15812

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im2/contexts/chat/composer/utils.cljs [hunk 1]
```diff
@@ -114,7 +114,7 @@
 
 (defn calc-shell-neg-y
   [insets maximized? extra-height]
-  (let [padding 6
+  (let [padding 12
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/utils.cljs:117]: Why this change?

Comment (ajayesivan) [reply src/status_im2/contexts/chat/composer/utils.cljs:117]: Previously the `floating-shell-button` had a padding of `5px` which I removed in this PR. To compensate for this modification, I have adjusted the padding here.

**Review by flexsurfer — APPROVED** [review]

**Review by OmarBasem — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ajayesivan thank you for your work. PR is ready to be merged
