### PR TITLE
[#21483] fix: update collectible amounts after sending

### LINKED ISSUE #21483: Multicollectible amount is not updated after transaction until relogin
**Steps:** 

1. Send multicollectible from Account A to internal Account B
2. See if collectible amount has been updated after pull to refresh

**Actual result:** amount is not updated until relogin
[Status-debug-logs - 2024-10-22T175917.000.zip](https://github.com/user-attachments/files/17478377/Status-debug-logs.-.2024-10-22T175917.000.zip)

https://github.com/user-attachments/assets/7723c96b-cc43-44b2-8475-b1c12ade2668

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21483

### Summary

Multicollectible amount is not updated after transaction until relogin

#### Areas that maybe impacted

- Send collectible

### Steps to test

1. Send multicollectible from Account A to internal Account B
2. See if collectible amount has been updated after pull to refresh

### Note for Test
As you can see in the video, receiving the updated balance may take some time (in my case, approximately 50 seconds). Once a signal confirming the ownership transfer is received, the balance will be updated accordingly

### Result

https://github.com/user-attachments/assets/5b171042-a413-4971-9aa6-bad3885fd53f

status: ready

### CODE REVIEW

**Comment by churik** [comment]
Thank you for work!
@mohsen-ghafouri can we resolve conflicts here?

**Comment by mohsen-ghafouri** [comment]
Hi @churik, I will do it today

**Comment by mohsen-ghafouri** [comment]
@smohamedjavid could you please review when you can?

File: src/status_im/contexts/wallet/collectible/utils.cljs [hunk 1]
```diff
@@ -6,12 +6,21 @@
             [taoensso.timbre :as log]
             [utils.number :as utils.number]))
 
+(defn- total-collectible-balance
+  ([ownership]
+   (reduce (fn [total {:keys [balance]}]
+             (+ total (or (js/parseInt balance) 0)))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/collectible/utils.cljs]: `utils.number/parse-int` would be a good choice here

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 2]
```diff
@@ -282,28 +299,33 @@
...
+   {:db (assoc-in db
+         [:wallet :ui :collectible]
+         {:details        collectible
+          :aspect-ratio   aspect-ratio
+          :gradient-color gradient-color})
+    :fx [[:dispatch [:wallet/get-collectibles-by-unique-id-async collectible-id]]
+         ;; We delay the navigation because we need re-frame to update the DB on time.
+         ;; By doing it, we skip a blink while visiting the collectible detail page.
+         [:dispatch-later
+          {:ms       17
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/collectible/events.cljs]: This value looks odd. Is it arbitrary, or was it calculated?
Since `:dispatch-later` relies on JavaScript's `setTimeout` to schedule the call to `dispatch`, and `setTimeout` is not precise, should we round this value?

What do you think?

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -398,8 +398,12 @@
...
  :wallet/build-transaction-for-collectible-route
  (fn [{:keys [db]}]
-   (let [last-request-uuid (get-in db [:wallet :ui :send :last-request-uuid])]
-     {:db (update-in db [:wallet :ui :send] dissoc :transaction-for-signing)
+   (let [last-request-uuid     (get-in db [:wallet :ui :send :last-request-uuid])
+         collectible-unique-id (get-in db [:wallet :ui :send :collectible :unique-id])]
+     {:db (->
+            db
+            (update-in [:wallet :ui :send] dissoc :transaction-for-signing)
+            (assoc-in [:wallet :ui :collectibles :pending collectible-unique-id] true))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/events.cljs:406]: IMO `wallet/transaction-success` or `wallet/transactions-sent-signal-received` would be a better place to add this.

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 4]
```diff
@@ -171,16 +171,33 @@
...
 (rf/reg-event-fx
  :wallet/collectible-ownership-update-finished
- (fn [{:keys [db]} [{:keys [accounts chainId]}]]
+ (fn [{:keys [db]} [{:keys [accounts chainId message]}]]
    (let [address            (first accounts)
          pending-chain-ids  (get-in db [:wallet :ui :collectibles :updating address])
          updated-chain-ids  (disj pending-chain-ids chainId)
-         all-chain-updated? (and (some? pending-chain-ids) (empty? updated-chain-ids))]
+         all-chain-updated? (and (some? pending-chain-ids) (empty? updated-chain-ids))
+         collectible-id     (data-store/rpc->collectible-id message)]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/collectible/events.cljs:179]: I have a feeling that this might cause a bug because we are taking only the first entry. Instead, it should be a set of unique IDs where we can check if the pending collectible id is present in it and dispatch the events accordingly. WDYT?

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 5]
```diff
@@ -70,7 +70,7 @@
    (let [current-collectible-idx (get-in db [:wallet :accounts account :current-collectible-idx] 0)
          collectibles-filter     nil
          data-type               (collectible-data-types :header)
-         fetch-criteria          {:fetch-type            (fetch-type :fetch-if-not-cached)
+         fetch-criteria          {:fetch-type            (fetch-type :fetch-if-cache-old)
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/collectible/events.cljs:73]: 👌

**Review by smohamedjavid — COMMENTED** [review]
Looks good overall. Just some minor comments.

File: src/status_im/contexts/wallet/collectible/utils.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/collectible/utils.cljs]: IMO, we should always use BigNumber when calculating balances. In this case, it shouldn’t be a deal-breaker in 99% of cases since balances are whole numbers with no decimals, and users generally don’t own many collectibles. However, for safety and consistency, we should use BigNumber.

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/events.cljs]: I didn’t write this part and I’m not aware of the reasoning behind choosing this number. As for rounding it, I think it could be a good idea if setTimeout’s precision is a concern.

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/send/events.cljs:406]: @smohamedjavid i wanted to add it in better place but as we do cleanup after closing the modal, we don't have access to this data after that. here it was the only option IMO.

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 4 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/events.cljs:179]: Sorry, I didn’t quite get the issue. I’m storing all collectible unique IDs in [:wallet :ui :collectibles :pending], so it’s not just the first entry. There can be more than one pending collectible. When here it receives the data, if it’s in the pending list, it will trigger the event to update it

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/collectible/events.cljs:179]: Oh no, I meant inside the `rpc->collectible-id` method. 

https://github.com/status-im/status-mobile/pull/21867/files#diff-ae92efa2ffeee3a951e8e834cb41e863add18e0d33a3b03ad573dd6ba6148e05R305

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/events.cljs:406]: If I'm not mistaken, the transaction clean-up events are dispatched inside the `wallet/transaction-success` event. We could get this same information on that event and update the `app-db`.

One other reason to move this `assoc-in` to one of those events is that we build the transaction as soon as the user is on the TX confirmation/summary screen. If the user somehow decides to leave the flow, then this app-db update is misleading.

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 4 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/events.cljs:179]: As far i saw it only give data about one collectible (added/updated/removed), do we have real example of getting information about multi collectible at one event?

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/send/events.cljs:406]: I can see `:wallet/clean-selected-collectible` being called in places like closing the send view or selecting another account. IMO, storing the pending collectible here carries less risk, and since we store very light data in the pending section, any misleadings wouldn’t cause critical issues. WDYT?

File: src/status_im/contexts/wallet/collectible/utils.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/utils.cljs]: Here, I think `utils.number/parse-int` is a better choice since collectible balance is just a count without decimals. If we use bignumber, we need to be careful with operations like +, as they might cause unintended behavior.

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/collectible/events.cljs]: I think we should round it to 20 ms, we are using this value for similar purposes on other flows.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/collectible/events.cljs]: Done

**Comment by mohsen-ghafouri** [comment]
@briansztamfater @smohamedjavid Could you please check it again?

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 4 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/collectible/events.cljs:179]: True that. It will return only one collectible data after the transaction is done. Maybe the scenario I'm thinking is a bit edge case, like during that time of fetching in status-go, if that account received any collectable from any other account (between the fetching interval), the status-go signals will include both collectible details too. Nevertheless, that is something we can do to improve later after we refactor the collectible data in app-db.

It's good for now. Thanks for the fix! @mohsen-ghafouri 🙌

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/events.cljs:406]: I'm sorry. The word misleading misleads 😅 . I meant to say that updating the app-db even before the transaction is placed is overhead, as this update is done when the user goes to the TX summary/confirmation screen, and the user can go back to wallet home from there (w/o submitting the TX). So, the app-db update without the actual transaction getting placed is something we can avoid.

I agree that the `:wallet/clean-selected-collectible` event is called as part of page (TX flow screens) unmounts. But, the TX flow screen is dismissed in `wallet/end-transaction-flow` event, which is dispatched part of `wallet/transaction-success` event where we will have access to collectible sent. That's why I was suggesting that place. WDYT?

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/send/events.cljs:406]: @smohamedjavid `:wallet/clean-selected-collectible` it's not only called in TX flow screen, it can be called from other places, please check the usage, it triggers if user close some views (like select asset view, send from view, etc). 
so having some no really pending transaction in app-db has less burden than missing an update IMO. wdyt?

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/send/events.cljs:406]: My point is if user while waiting to get `transaction-success` event, try to navigate around and it will cause that collectible data being missed.

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/events.cljs:406]: > so having some no really pending transaction in app-db has less burden than missing an update IMO. wdyt?

I was concerned if the user leaves the send flow without placing the TX. Then, this will trigger fetching that particular collectible data by ID, which we will update the app-db (in the accounts collectible list and the detailed collectible data for the detail screen) with the same data. It's fine, we will explore this later to make it efficient.

> My point is if user while waiting to get transaction-success event, try to navigate around and it will cause that collectible data being missed.

I agree. It's something we should not allow until we get the TX response (success/failed).

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/send/events.cljs:406]: yes i agree, this is not the perfect solution but the only workaround i found for now. we can definitely improve it. thank for all your feedbacks 🙏

**Comment by VolodLytvynenko** [comment]
hi @mohsen-ghafouri Thank you for the PR! This PR has improvements compared to the latest develop. The multicollectible amount now updates after a refresh.

However, some issues were found. Please take a look at them.

## PR_ISSUE 1: Multi-collectible amount not updated for receiver until relogin

### Steps to reproduce:
1. `User A` sends a multi-collectible to `User B`.
2. `User B` performs a pull-to-refresh.

### Actual result:
The multi-collectible amount is not updated for User B after refreshing. (in my case the collectible is sent 5 minuts ago, however amount refresh happens only after relogin)

https://github.com/user-attachments/assets/b7eb985b-a1a4-4bc8-8d97-9050e51ca5c6

### Expected result:
The multi-collectible amount should update correctly after the refresh.

### Devices:
Pixel 7a (Android 13)
iPhone 11 Pro Max (iOS 17)

### Additional info:
Same issue is related to single-collectible (non-multicollectible)

### Logs:
[logs.zip](https://github.com/user-attachments/files/18768487/logs.zip)

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko Based on my tests, the receiver isn’t getting any transaction activity or event updates, so it’s not possible to update the amount for it.

CC @shivekkhurana @smohamedjavid Do you have any updates regarding transaction activity and collectible ownership changes for the receiver?

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 2: Removed account’s collectibles still included in total count on main page of wallet

### Preconditions:
The user has two accounts:
- Account 1: Holds 10 of the same collectibles.
- Account 2: Holds 5 of the same collectibles.

### Steps to reproduce:
1. Remove Account 2.
2. Check the collectibles count on the main wallet page.

### Actual result:
The main wallet page still displays the total sum of collectibles from both accounts, even after removing Account 2.

https://github.com/user-attachments/assets/fc6dad1e-4238-43b3-bdef-53027fbe96a2


### Expected result:
The collectibles count should update correctly, reflecting only the remaining collectibles in Account 1.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1lPkYhjP2fBXoS9Y8YR0vBWKwujbu_J2W/view?usp=drive_link

**Comment by mohsen-ghafouri** [comment]
I believe issue 2 is reproducible on develop branch as well. so not exactly related to send flow @VolodLytvynenko, i might solve it in another follow up PR.

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri 
> I believe issue 2 is reproducible on develop branch as well. so not exactly related to send flow @VolodLytvynenko, i might solve it in another follow up PR.

Indeed. Just reproduced this [issue 2](https://github.com/status-im/status-mobile/pull/21867#issuecomment-2654062313) on develop as well. No other issues from my side.

it's okay if [issue 1](https://github.com/status-im/status-mobile/pull/21867#issuecomment-2653723508)  will be fixed in a separate follow-up. Let me know if this will be addressed in this PR, otherwise, the PR can be merged

**Comment by mohsen-ghafouri** [comment]
Thanks @VolodLytvynenko, i'm just waiting for guys feedback and if there is no solution for it at the moment I will create and log them in a separate issue.

**Comment by mohsen-ghafouri** [comment]
After discussion, I will create follow up issues for reported issues.
