### PR TITLE
The [Cancel] and [Join] buttons are hidden within 'Join Community' overlay

### LINKED ISSUE #14955: The [Cancel] and [Join] buttons are hidden  within 'Join Community' overlay
# Bug Report

## Problem 
The [Cancel] and [Join] buttons are out of the screen for some devices on the 'Join Community' overlay

**Preconditions:**
User didn't join to the status community yet

**Steps to reproduce:**
1. Go to the communities page
2. Tap 'Opened' tab
3. Tap Status
4. Tap [Join Community] button
5. Check opened 'Join Community' overlay

#### Actual behavior
[Cancel] and [Join] buttons  are hidden
image

#### Expected behavior
[Cancel] and [Join] buttons  are shown
image

### Additional Information
- Status version: nightly 1 Feb 2023 [2612]
- Operating System: Android version 9, Huawei P20 light

### PR DESCRIPTION
**Pull request by alwx**
Makes 'Join Community' overlay scrollable.
Fixes https://github.com/status-im/status-mobile/issues/14955

### Summary

Because of the safe-area inset that's always added to the overlay on the bottom, scrollable overlays did look a bit ugly — so this PR also adds an option `bottom-safe-area-spacing?` (set to `true` by default) that when set to `false` removes the inset which makes it possible for scrollable components to handle insets manually (for example, inside a scroll-view component itself).

#### Platforms

- Android
- iOS

##### Functional

- bottom sheets

Status: ready

### CODE REVIEW

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs [hunk 1]
```diff
@@ -1,6 +1,7 @@
 (ns status-im2.contexts.communities.menus.request-to-join.view
   (:require [quo.react-native :as rn]
             [quo2.core :as quo]
+            [quo.components.safe-area :as safe-area]
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: quo shouldn't be used in new designs, we have safe-area in react-native namespace

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs [hunk 2]
```diff
@@ -1,6 +1,7 @@
 (ns status-im2.contexts.communities.menus.request-to-join.view
   (:require [quo.react-native :as rn]
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: please replace quo here as well as you're making changes in this ns anyway

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs [hunk 3]
```diff
@@ -76,57 +77,64 @@
...
-        is-open?         (not= 3 (:access permissions))]
-    (fn []
-      [rn/scroll-view {:style style/page-container}
-       [rn/view
-        {:style style/title-container}
+  (let [agreed-to-rules? (reagent/atom false)]
+    [:f>
+     (fn []
+       (let [{window-height :height} (rn/use-window-dimensions)
+             safe-area               (safe-area/use-safe-area)
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: if its a drawer component and it's opened in bottom sheet i would say that bottom sheet should take care about safe-area

Comment (J-Son89) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: Yes I agree, this is implemented before the new bottom sheet was ready so it's using the old bottom sheet. @alwx, I think the better solution is to implement this with the new bottom sheet and then we only fix this once.

Comment (alwx) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: @J-Son89 it uses `status-im2.common.bottom-sheet.view` if that's what you're talking about. Is it the new one?

Comment (alwx) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: @flexsurfer how do you propose to do this? The drawer component indeed cares about the safe-area and adds a spacing in the bottom of the screen but the problem is we actually don't need this spacing because our component contains a scroll-view that should all be scrollable (and unnecessary spacing makes it look weird)
In fact, I just implemented it similarly to `status-im2.contexts.chat.group-details.view` which is also a bottom sheet view.

Comment (J-Son89) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: @ibrkhalil can you point us where the new one is :D

Comment (alwx) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: @J-Son89 I do feel like `status-im2.common.bottom-sheet.view` is in fact the new one (the latest changes to it were done a week ago)

Comment (J-Son89) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: yep it looks like it! Sorry for delayed response. It was created by @chrispader and seems he is first on the commits for it 👍

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs (hunk 2 above)
Comment (alwx) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: Done!

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs (hunk 1 above)
Comment (alwx) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: fixed!

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs (hunk 3 above)
Comment (alwx) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs]: Left it as it was because we need to control `safe-area` within the component for reasons explained above.

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs [hunk 4]
```diff
@@ -73,60 +74,72 @@
...
-       [rn/view
-        {:style style/title-container}
+  (let [agreed-to-rules? (reagent/atom false)]
+    [safe-area/consumer
+     (fn [insets]
+       [:f>
+        (fn []
+          (let [{window-height :height} (rn/use-window-dimensions)
+                is-open?                (not= 3 (:access permissions))]
+            [rn/scroll-view {:style {:max-height (- window-height (:top insets))}}
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/menus/request_to_join/view.cljs:91]: i feel like something wrong is here, why content should care about max height? bottom sheet should care about this cc @ibrkhalil

Comment (flexsurfer) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs:91]: also im not sure about `window-height` , bottom sheet should never go so high, probably it should be a modal screen then ?

**Comment by flexsurfer** [comment]
i'll left comment in the issue

**Comment by alwx** [comment]
Ok, closing this one because we decided to implement the new component instead of fixing this bug.
More details here: https://github.com/status-im/status-mobile/issues/14955

**Comment by alwx** [comment]
Reopening the PR because it seems like we want to merge the hotfix before the proper component is implemented.
cc @churik

File: src/status_im2/contexts/communities/menus/request_to_join/view.cljs (hunk 4 above)
Comment (alwx) [reply src/status_im2/contexts/communities/menus/request_to_join/view.cljs:91]: We will focus on developing a new component later on, now we need a quick fix (as per today's retro meeting). Here is the issue for a separate modal screen: https://github.com/status-im/status-mobile/issues/14564

**Review by flexsurfer — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
