### PR TITLE
fix empty community in the community list

### LINKED ISSUE #13194: Empty community appears in the community list after joining a public chat containing community links
# Bug Report

## Problem 
When joining a public chat containing invite community links, you may notice that the chat view blinks first (apparently, invite previews blink), and then if you open the community list, all those communities will be in the list with another `0 members` community. 

#### Actual behavior

https://user-images.githubusercontent.com/67952253/159529606-df7b4dd8-7ef8-47e7-aebb-8f6d67211dc6.mp4

### Reproduction

1. On device1 create a community and post an invite link in a public chat
2. Create an account on device2 and join the public chat
3. On device2 tap the `+` button on the home screen > Communities (you may need to reopen the public chat and the community list again) 

### Additional Information

- Status version: nightly 22/03
- Operating System: Android, iOS

### Logs
[geth.log](https://github.com/status-im/status-react/files/8326205/geth.log)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-react/issues/13194

# Summary
PR fixes empty community in the community list

Earlier, we used to return community in response to the `resolve-community-info` call. 
Currently, we are using signals for returning the resolved community, and returning nil in an on-success event.

### CODE REVIEW

File: src/status_im/chat/models/link_preview.cljs [hunk 1]
```diff
@@ -49,8 +49,10 @@
   {:events [::community-resolved]}
   [{:keys [db] :as cofx} community-id community]
   (fx/merge cofx
-            {:db       (community-resolved db community-id)
-             :dispatch [::cache-link-preview-data (community-link community-id) community]}
+            (merge
```
Comment (cammellos) [inline src/status_im/chat/models/link_preview.cljs]: I think you can use `assoc` / `cond->`
```
(cond-> {:db (community-resolved db community-id)}
     (nil? community) (assoc :dispatch [::...
```
but `merge` works as well (it just generally signals that you don't know exactly what the value of the second argument is)

**Review by cammellos — APPROVED** [review]

File: src/status_im/communities/core.cljs [hunk 2]
```diff
@@ -84,7 +84,8 @@
 
 (fx/defn handle-community
   [{:keys [db]} {:keys [id] :as community}]
-  {:db (assoc-in db [:communities id] (<-rpc community))})
+  (when-not (nil? id)
```
Comment (flexsurfer) [inline src/status_im/communities/core.cljs]: `when-not id` will work as well, nil? is redundant here

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@Parveshdhull thanks for the quick fix!

I noticed that in your fix, previews of invite links also started resolving again (this was broken before).  But the review is displayed only when opening a public chat for the first time, after relogin, the previews are no longer displayed.  I waited about 15 minutes to resolve again, but for some reason only the link I posted today, has been re-resolved.

I'm not sure that this is within the scope of this PR. WDYT?
Screenshot 2022-03-23 at 15 24 45

**Comment by Parveshdhull** [comment]
@qoqobolo thanks for testing PR.

Yes, Preview should also resolve on relogin 🤔. I will see what is causing issue and will fix. Thanks
