### PR TITLE
[#16118] bottom nav tab notification color

### LINKED ISSUE #16118: App home page, fix community notification color
Small ui bug on app home page where communities notification is the wrong color, should be grey and not blue.

Movie_Recording_2023-05-30_16-37-56

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #16118

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

This PR fixes the notification color, it should be customization color, it was confirmed by Mario.

image

#### Platforms

- Android
- iOS

### Steps to test

- Open Status 
- Create different profiles using different customization colors
- Log in
- Receive a notification
- The notification has the customization color

status: ready

### CODE REVIEW

File: src/quo2/components/navigation/bottom_nav_tab/view.cljs [hunk 1]
```diff
@@ -1,10 +1,11 @@
-(ns quo2.components.navigation.bottom-nav-tab
+(ns quo2.components.navigation.bottom-nav-tab.view
```
Comment (ulisesmac) [inline src/quo2/components/navigation/bottom_nav_tab/view.cljs:1]: Moved content from previous namespace to new files split in `.view` and `.styles`

File: src/quo2/components/navigation/bottom_nav_tab/view.cljs [hunk 2]
```diff
@@ -77,19 +81,10 @@
...
+            :style               styles/notification-counter}
            counter-label]
-          [rn/view
-           {:style {:width            8
-                    :height           8
-                    :border-radius    4
-                    :top              6
-                    :left             51
-                    :position         :absolute
-                    :background-color colors/primary-50}}]))]]))
```
Comment (ulisesmac) [inline src/quo2/components/navigation/bottom_nav_tab/view.cljs:92]: Moved these styles to `styles` ns

File: src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs [hunk 3]
```diff
@@ -36,7 +37,15 @@
...
-    :type  :text}])
+    :type  :text}
+
+   {:label   "Customization color"
+    :key     :customization-color
+    :type    :select
+    :options (map (fn [[k _]]
+                    {:key   k
+                     :value (string/capitalize (name k))})
+                  colors/customization)}])
```
Comment (ulisesmac) [inline src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs:48]: Since the component now supports customization color, it has been added as a property to the preview screens

File: src/status_im2/contexts/shell/bottom_tabs.cljs [hunk 4]
```diff
@@ -19,15 +19,21 @@
...
-   (assoc (get notifications-data stack-id)
-          :test-ID             stack-id
-          :icon                icon
-          :icon-color-anim     (get
-                                shared-values
-                                (get shell.constants/tabs-icon-color-keywords stack-id))
-          :on-press            #(animation/bottom-tab-on-press stack-id)
-          :accessibility-label (str (name stack-id) "-tab"))])
+  (let [{:keys [key-uid]}   (rf/sub [:multiaccount])
+        customization-color (or (:color (rf/sub [:onboarding-2/profile]))
```
Comment (J-Son89) [inline src/status_im2/contexts/shell/bottom_tabs.cljs]: why do we have 2 subs? Can't we just have one that works :)

File: src/quo2/components/navigation/bottom_nav_tab/view.cljs [hunk 5]
```diff
@@ -26,9 +27,12 @@
     :on-press               bottom-tab on-press function
     :pass-through?          true/false
     :icon-color-anim        reanimated shared value
+    :customization-color    Customization color for the notification mark
   "
   [{:keys [icon new-notifications? notification-indicator counter-label
-           on-press pass-through? icon-color-anim accessibility-label test-ID]}]
+           on-press pass-through? icon-color-anim accessibility-label test-ID
+           customization-color]
+    :or   {customization-color :blue}}]
```
Comment (J-Son89) [inline src/quo2/components/navigation/bottom_nav_tab/view.cljs:35]: hmm, I would prefer no default in the component, we should add the default in colors/custom-color function instead? There should also be a defined constant with this value. I think @Parveshdhull added it recently.

Ideally we avoid adding this default value multiple times all over the codebase.

File: src/quo2/components/navigation/bottom_nav_tab/view.cljs [hunk 6]
```diff
@@ -77,19 +81,10 @@
         (if (= notification-indicator :counter)
           [counter/counter
            {:override-text-color colors/white
-            :override-bg-color   colors/primary-50
-            :style               {:position :absolute
-                                  :left     48
-                                  :top      2}}
+            :override-bg-color   (colors/custom-color customization-color 60)
```
Comment (J-Son89) [inline src/quo2/components/navigation/bottom_nav_tab/view.cljs:84]: maybe outside the scope, but perhaps good to create a follow up issue to track -> 
counter needs to use `customization-color` prop instead of override-bg-color. It should just be passed through, and in that component it can call colors/custom-color itself

File: src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs [hunk 7]
```diff
@@ -36,7 +37,15 @@
                :value :unread-dot}]}
    {:label "Counter Label"
     :key   :counter-label
-    :type  :text}])
+    :type  :text}
+
+   {:label   "Customization color"
+    :key     :customization-color
+    :type    :select
+    :options (map (fn [[k _]]
```
Comment (J-Son89) [inline src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs:45]: do we need the `_` argument there?

Comment (ibrkhalil) [reply src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs:45]:
```clj
 (map (fn [k] ...) (keys colors/customization)
```

Comment (ulisesmac) [reply src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs:45]: @J-Son89 Yes, We need it, even if ClojureScript is more permissive, I'd add it as a good practice.

@ibrkhalil Thanks for the suggestion, in fact I already thought about that option but I didn't take it because it requires to travel 2 times the collection instead of one (at cost of a destructuring), I mean:

`(keys colors/customization)` creates a new seq based on a map, and
`(map (fn [k] ,,,)` creates a new seq based on the previous seq

Instead `(map (fn [k _],,,) colors/customization)` is a single pass on the seq to create it.

I understand this is a very small optimization, I just didn't feel confortable traveling twice when adding a destructuring avoids it.

File: src/quo2/components/navigation/bottom_nav_tab/view.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/quo2/components/navigation/bottom_nav_tab/view.cljs:84]: Yes, I think it should be a new issue, I've just created it: #16261

File: src/status_im2/contexts/shell/bottom_tabs.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im2/contexts/shell/bottom_tabs.cljs]: As I told you before, this is a pattern existing across the code, so I created an issue to fix it everywhere: #16263 :)

File: src/quo2/components/navigation/bottom_nav_tab/view.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/quo2/components/navigation/bottom_nav_tab/view.cljs:35]: I tried to use that constant but I get the following error from the linter:

```
WARNING: re-frame, status-im are not allowed in quo2 components

./src/quo2/components/navigation/bottom_nav_tab/view.cljs:            [status-im2.constants :as constants]
```

> we should add the default in colors/custom-color function instead? 

Yes, probably as an infrastructure change, we could do it, but out of scope for this PR IMO. :+1:

Comment (J-Son89) [reply src/quo2/components/navigation/bottom_nav_tab/view.cljs:35]: Sure, we can make a large issue for cleaning up some of the colors pieces 👍

**Comment by ulisesmac** [comment]
@J-Son89 @ibrkhalil if the code is good enough, could you please approve so this can be reviewed by QA?
thanks!

**Review by J-Son89 — APPROVED** [review]

**Review by yqrashawn — APPROVED** [review]

File: src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs (hunk 7 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/quo_preview/navigation/bottom_nav_tab.cljs:45]: Agree that your solution is more performant, Amazing job!
I like the optimize where I can mindset, Keep it up.

**Review by ibrkhalil — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hey @ulisesmac there is a conflict now, could you resolve it pls 🙏

**Comment by ulisesmac** [comment]
> Hey @ulisesmac there is a conflict now, could you resolve it pls pray

Hey @qoqobolo this PR has solved the conflicts and is updated :+1:

**Comment by qoqobolo** [comment]
Thanks for your work @ulisesmac!
Looks good to me, PR can be merged.
