### PR TITLE
[#21853] fix: check deeplink pending request after wallet connect loaded

### LINKED ISSUE #21853: "cannot read property" error is displayed on profiles list page when the Dapp attempts to send a signature
### Steps:
1. Connect to the Dapp(in my case Uniswap)  using universal scanner 
2. Log out
3. Make any transaction Using Dapp (approve or swap)

### Actual result:
A "cannot read property" error is displayed when the Dapp attempts to send a signature
Image

### Expected result:
No errors are shown

There is another [issue](https://github.com/status-im/status-mobile/pull/21833#issuecomment-2557013966) which might be related to current one. Please ping me up if the issues are unrelated and I will log a separate one. 

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs.zip](https://github.com/user-attachments/files/18201787/logs.zip)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21853

### Summary

- "cannot read property" error is displayed on profiles list page
- Handle pending dapp pair request after wallet connect loaded successfully 

#### Areas that maybe impacted

- Dapps interactions

### Test Note 

Regarding the issue discussed in [PR #21833](https://github.com/status-im/status-mobile/pull/21833#issuecomment-2557013966), here’s an explanation of how dApp requests are handled and the current limitations:

### Handling dApp Requests
1. **Event Listener**  
   - The app registers an event listener to handle incoming dApp requests.  
   - However, this listener is only registered **after** the wallet screen loads. If a request is sent **before** the listener is active, it will not be processed.

2. **Deep Link**  
   - Currently, **pairing requests** from a dApp can be handled through deep links, where the dApp sends a URI containing the pairing information to the app.  
   - However, **sign requests** are **not** handled through deep links. This means any signing request (e.g., transactions or message signing) that is initiated via deep link will not work if user is not logged in already.   
   - If the app is launched through a deep link for a **pairing** request, the process works as expected, as shown in the video below.

3. **Push Notification** *(Not Yet Implemented)*  
   - Push notifications are intended to handle scenarios where the app is closed, and the request is sent to a different device.  
   - The issue in [PR #21833](https://github.com/status-im/status-mobile/pull/21833#issuecomment-2557013966) highlights this limitation. Currently, push notifications are not supported for **any type of request**.

for [PR #21833](https://github.com/status-im/status-mobile/pull/21833#issuecomment-2557013966) we can have a separate issue so i can discuss it with @clauxx and check for any solution.

### Steps to test

1. Connect to the Dapp(in my case Uniswap) using universal scanner
5. Log out
6. Make any transaction Using Dapp (approve or swap)

### Result

https://github.com/user-attachments/assets/75110d50-cddd-4364-859b-53f9c14481aa

status: ready

### CODE REVIEW

**Comment by mohsen-ghafouri** [comment]
for https://github.com/status-im/status-mobile/pull/21833#issuecomment-2557013966 we can have a separate issue so i can discuss it with @clauxx and check for any solution.

File: src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs [hunk 1]
```diff
@@ -15,11 +15,14 @@
...
-             :on-fail     #(log/error "Failed to pair with dApp" {:error %})
-             :on-success  #(log/info "dApp paired successfully")}]]})))
+     (if web3-wallet
+       {:db (dissoc db :wallet-connect/waiting-pair-url)
+        :fx [[:effects.wallet-connect/pair
+              {:web3-wallet web3-wallet
+               :url         url
+               :on-fail     #(log/error "Failed to pair with dApp" {:error %})
+               :on-success  #(log/info "dApp paired successfully")}]]}
+       {:db (assoc db :wallet-connect/waiting-pair-url url)}))))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs]: It's a bit difficult to understand why we're assoc/dissoc-ing the `waiting-pair-url` here you know the context already.

I'd suggest to isolate the usage of `waiting-pair-url` inside 2 events so its purpose is clearer (see an attempt below). The `process-deeplink` event would be dispatched by the universal-links handler (`status-im.common.universal-links`), while the `pair-with-pending-deeplink` would be dispatched in `:wallet-connect/on-init-success`. I assume the other changes (in `:wallet-connect/send-response` and `:wallet-connect/pair`), as well as the delay from the deeplink handler, wouldn't be necessary anymore, but let me know if that's not the case. 

Also renamed it to `:wallet-connect/pending-url` as "pending" seems more fitting than "waiting", but that's just a nitpick.
```clj 
(rf/reg-event-fx
 :wallet-connect/process-deeplink
 (fn [{:keys [db]} [url]]
   (let [web3-wallet (get db :wallet-connect/web3-wallet)]
     (if web3-wallet
       {:fx [[:dispatch [:wallet-connect/on-scan-connection url]]]}
       {:db (assoc db :wallet-connect/pending-url url)}))))

(rf/reg-event-fx
 :wallet-connect/pair-with-pending-deeplink
 (fn [{:keys [db]}]
   (when-let [pending-url (get db :wallet-connect/pending-url)]
     {:db (dissoc db :wallet-connect/pending-url)
      :fx [[:dispatch [:wallet-connect/on-scan-connection pending-url]]]})))
```

File: src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs [hunk 2]
```diff
@@ -121,22 +121,23 @@
...
-               :on-error    (fn [error]
-                              (log/error "Failed to send Wallet Connect response"
-                                         {:error                error
-                                          :method               method
-                                          :event                :wallet-connect/send-response
-                                          :wallet-connect-event event}))
-               :on-success  (fn []
-                              (rf/dispatch [:wallet-connect/redirect-to-dapp])
-                              (log/info "Successfully sent Wallet Connect response to dApp"))}]]}))))
+       (when web3-wallet
```
Comment (clauxx) [inline src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs]: why is this needed? When would we send a response without the web3-wallet already initialized?

File: src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs]: Make sense will apply changes.

File: src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs]: the only reason for this issue https://github.com/status-im/status-mobile/issues/21853#issue-2751138384 when i was checking it was this event triggered before web3-wallet have initiated

Comment (clauxx) [reply src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs]: might be that it's no longer needed, since we're not supposed to process requests without logging in i.e. without web3-wallet being initialized.

**Comment by shivekkhurana** [comment]
@mohsen-ghafouri Please use `wallet-core` label on PRs for better visibility.

**Review by clauxx — APPROVED** [review]

File: src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs]: Sorry was busy with another issue, I just removed it and will do test if i can still reproduce the issue.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/events/session_responses.cljs]: removed

**Comment by mohsen-ghafouri** [comment]
@shivekkhurana I also checked the event listener to see if it sends pending requests, but it doesn’t work. Only events after registration are being received.

```clojure
[:effects.wallet-connect/register-event-listener
            [web3-wallet
             constants/wallet-connect-session-request-event
             #(rf/dispatch [:wallet-connect/on-session-request %])]]
```

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanks for the PR. Unfortunately the initial [issue](https://github.com/status-im/status-mobile/issues/21853) is still reproducible. 


### ISSUE 1 "cannot read property" error is displayed on profiles list page when generating event on Dapp's side

**Steps:** 

1. Connect to any Dapp (I used https://se-sdk-dapp.vercel.app/ for testing)
2. Logout 
3. While on Profile list/Login screen generate any event on Dapp's side

**Actual result:** "cannot read property..." error appears. At the same time, user is able to sign pending event after login. 

[Status-debug-logs - 2025-01-10T153439.251.zip](https://github.com/user-attachments/files/18377775/Status-debug-logs.-.2025-01-10T153439.251.zip)


https://github.com/user-attachments/assets/9761650c-a400-49a1-9be3-544f62e85032

**Review by vkjr — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
Hey @pavloburykh thanks for testing it, could you please check again?

**Comment by mohsen-ghafouri** [comment]
Hey @clauxx i added an unregister event in last commit to resolve mentioned issue, JFYI if you have any feedback.

File: src/status_im/contexts/wallet/wallet_connect/events/core.cljs [hunk 3]
```diff
@@ -58,6 +58,23 @@
...
+             #(rf/dispatch [:wallet-connect/on-session-proposal %])]]
+           [:effects.wallet-connect/unregister-event-listener
+            [web3-wallet
+             constants/wallet-connect-session-request-event
+             #(rf/dispatch [:wallet-connect/on-session-request %])]]
+           [:effects.wallet-connect/unregister-event-listener
+            [web3-wallet
+             constants/wallet-connect-session-delete-event
+             #(rf/dispatch [:wallet-connect/on-session-delete %])]]]})))
+
```
Comment (clauxx) [inline src/status_im/contexts/wallet/wallet_connect/events/core.cljs]: @mohsen-ghafouri not sure if this right, since you're passing a different handler when un-registering the event, and usually js event emitters unregister handlers by function reference. Here the content of the handlers (when registering and unregistering) is the same, but the function references are different. You can extract the handlers and pass them to the `(register/unregister)-event-listeners` fx.

Comment (pavloburykh) [reply src/status_im/contexts/wallet/wallet_connect/events/core.cljs]: @mohsen-ghafouri could please ping me up once review comments are resolved. After that I will continue testing. Thanks.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/wallet_connect/events/core.cljs]: Done @pavloburykh @clauxx

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you for the fixes. PR is ready to be merged. 

> for https://github.com/status-im/status-mobile/pull/21833#issuecomment-2557013966 we can have a separate issue so i can discuss it with @clauxx and check for any solution.

I have logged a separate issue on that https://github.com/status-im/status-mobile/issues/21935
