### PR TITLE
Fix account edit confirmation button

### LINKED ISSUE #18791: Wallet: "Update account name" button hides when user edited his account name
# Bug Report

## Problem 
[comment]: # (A problem description)
As a user am trying to edit account name. Firstly I thought that "Update account name" button hides behind the keyboard but when I closed it I saw that button disappears by the same way as keyboard did. 

#### Expected behavior
"Update account name" button is visible and active 

#### Actual behavior
"Update account name" button hides when user edited his account name

https://github.com/status-im/status-mobile/assets/147824399/c4a6ee83-1a35-4c37-82c3-1f7169f00a99

### Reproduction

- Open Status
- Create a profile
- Navigate to the Wallet tab
- Create a new Wallet account (Eg: Account 2)
- Edit the name of the Account 2 and save it

### Additional Information

- Status version: nightly 12/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #18834: Incorrect button displayed in address editing flow
### Steps:
1. Go to the editing address flow
2. Check the button 

### Actual result:
The  'Update account name' button is shown
image

### Expected result:
The 'Confirm' button is shown
image
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=884-221816&mode=design&t=UpPzIv5dbKLxD0yp-0

### Additional info:
The same issue applies to the editing flow of watch-only accounts.

### PR DESCRIPTION
**Pull request by clauxx**
fixes #18834
fixes #18791

### Summary
On the account edit screen, always show the confirmation button, even if the input is focused. Also, fixed the issue with the text in the button.

#### Platforms

- Android
- iOS

##### Functional

- edit account

### Steps to test

- Open Status
- Create a profile
- Navigate to the Wallet tab
- Open account
- Press account options
- Press edit account

### Demo

https://github.com/status-im/status-mobile/assets/21865759/3bce84dd-c274-4032-8dab-3aba0ba40d04

status: ready

### CODE REVIEW

**Comment by J-Son89** [comment]
any chance of a photo/video to see this in action?

File: src/status_im/contexts/wallet/edit_account/view.cljs [hunk 1]
```diff
@@ -80,10 +79,8 @@
           :on-change-color     #(on-change-color % account)
           :on-change-emoji     #(on-change-emoji % account)
           :section-label       :t/account-info
-          :on-focus            #(reset! show-confirm-button? true)
-          :on-blur             #(reset! show-confirm-button? false)
-          :bottom-action?      @show-confirm-button?
-          :bottom-action-label :t/update-account-name
+          :bottom-action?      true
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/edit_account/view.cljs]: btw, was this something confirmed with designers??
cc @mariia-skrypnyk, @smohamedjavid, @pavloburykh ?
I recall asking about this but they seemed to have a different opinion? I think it's the better way to go 👍 

(also do we even need this `bottom-action?` prop then @smohamedjavid ?

**Comment by clauxx** [comment]
> any chance of a photo/video to see this in action?

Added to the description

File: src/status_im/contexts/wallet/edit_account/view.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/edit_account/view.cljs]: didn't confirm with the designers, but according to the [designs](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=884-221816&mode=design&t=CHEqdE4Rry3Cw1Qq-4), the button should always be visible, even if the input is focused.

also removed the `bottom-action?` as it's not needed anymore.

File: src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs [hunk 2]
```diff
@@ -30,7 +31,9 @@
       {:customization-color account-color
        :container-style     (style/gradient-cover-container margin-top)}]
      (into
-      [:<>
+      [rn/scroll-view
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs]: I think we should use the floating_button_page component on this screen instead, it's the same behaviour required on many of these wallet screens 👍

File: src/status_im/contexts/wallet/edit_account/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/edit_account/view.cljs]: > I recall asking about this but they seemed to have a different opinion? I think it's the better way to go

Yes @J-Son89, during our first wallet demo, Pedro mentioned revisiting the edit account screen as it was misleading the user by showing confirmation for name and not for emoji or color.

> also do we even need this bottom-action? prop then @smohamedjavid

It's best we confirm it with the design on the behaviour of the bottom action.

> but according to the [designs](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=884-221816&mode=design&t=CHEqdE4Rry3Cw1Qq-4), the button should always be visible, even if the input is focused.

No @clauxx, when the user enters the edit account screen (link to [design](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=878%3A238236&mode=design&t=aspeO6VTr8x0xYhs-1)), we don't show the button until the input is focused or name is changed.

File: src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs (hunk 2 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs]: changed it to using floating-button-page. Had to add an extra prop so @ulisesmac could you also have a look, since u also worked on it?

File: src/status_im/contexts/wallet/edit_account/view.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/edit_account/view.cljs]: @smohamedjavid i see. I added the changes. So I guess the logic from the designs would be that the button is not visible only when the text wasn't changed and the keyboard is not visible, right?

File: src/status_im/common/floating_button_page/view.cljs [hunk 3]
```diff
@@ -52,7 +52,8 @@
      :remove-listeners    remove-listeners}))
 
 (defn view
-  [{:keys [header footer customization-color footer-container-padding gradient-cover?]
+  [{:keys [header footer customization-color footer-container-padding header-container-padding
```
Comment (J-Son89) [inline src/status_im/common/floating_button_page/view.cljs]: maybe actually - header-container-style and we pass  a map with padding in that?
and probably should do the same for footer (but we do this in follow up)

Comment (clauxx) [reply src/status_im/common/floating_button_page/view.cljs]: done 👍

File: src/status_im/contexts/wallet/edit_account/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/edit_account/view.cljs]: Right, @clauxx.

I know this is a bit off compared to other places in the application. Hopefully, they should update the design to keep the button all time (in a disabled state) and enable it when there is a change in name, color or emoji.

File: src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs [hunk 4]
```diff
@@ -1,34 +1,43 @@
 (ns status-im.contexts.wallet.common.screen-base.create-or-edit-account.view
   (:require [quo.core :as quo]
+            quo.theme
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs]: Our style for all the requires is inside `[]`

File: src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs [hunk 5]
```diff
@@ -1,34 +1,43 @@
...
+                                  :on-press   #(rf/dispatch [:navigate-back])}]
+      :footer                   (when-not hide-bottom-action?
+                                  (if custom-bottom-action
+                                    custom-bottom-action
+                                    [quo/button
+                                     (merge
+                                      {:size 40
+                                       :type :primary}
+                                      bottom-action-props)
+                                     (i18n/label bottom-action-label)]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/screen_base/create_or_edit_account/view.cljs]: Could we move this to the upper let?
It'll simplify the code

File: src/status_im/contexts/wallet/edit_account/view.cljs [hunk 6]
```diff
@@ -114,3 +113,5 @@
                                                                   :new-value   chain-ids}))
                                                  :watch-only? watch-only?}])}]))
            :container-style style/data-item}]]))))
+
+(defn view [] [:f> f-view])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/edit_account/view.cljs]: No longer needed :)

**Review by ulisesmac — APPROVED** [review]
LGTM :+1:

File: src/status_im/contexts/wallet/edit_account/view.cljs (hunk 6 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/edit_account/view.cljs]: there's a hook inside though
```clj
{:keys [keyboard-shown]} (hooks/use-keyboard) ;; line 66
```

Comment (ulisesmac) [reply src/status_im/contexts/wallet/edit_account/view.cljs]: Funcitonal components have been enabled by default in a recent PR, so we no longer need to differenciate them

Comment (clauxx) [reply src/status_im/contexts/wallet/edit_account/view.cljs]: ahh right, thanks :+1:

**Review by smohamedjavid — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

File: src/status_im/contexts/wallet/edit_account/view.cljs [hunk 7]
```diff
@@ -35,34 +36,34 @@
...
+                                (save-account {:account     account
+                                               :updated-key :emoji
+                                               :new-value   edited-emoji})))
+        on-confirm-name     (fn [account]
+                              (rn/dismiss-keyboard!)
+                              (save-account {:account     account
+                                             :updated-key :name
+                                             :new-value   @edited-account-name}))]
     (fn []
       (let [{:keys [name emoji address color watch-only? default-account?]
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/edit_account/view.cljs:56]: nit: we can destructure name as wallet-name to avoid shadowing `clojure.core/name`

**Comment by qoqobolo** [comment]
Thanks for the fixes @clauxx!
PR can be merged.
