### PR TITLE
bugs #4724 and #5131 - fixed by adding wallet onboarding for dapp txs

### LINKED ISSUE #4724: User should be redirected to wallet onboarding before signing transaction in dapp
### Description

*Type*: Bug

*Summary*: If user haven't seen wallet onboarding yet, he should be redirected to it before signing transaction in dapp. Currently, he can sign it before seeing the wallet onboarding which is incorrect. 

Also, currently, when he finally goes to wallet and finishes the onboarding, an empty send transaction screen is shown for no reason. 

#### Expected behavior
User is redirected to wallet onboarding before dapp signing transaction. It's already work like this for "/send" in chat.

#### Actual behavior
User can sign dapp transaction before finishing wallet onboarding.

### Reproduction

- Install and open Status
- Create a new account
- Switch to Ropsten and enable dev mode
- Sign a transaction in the test dapp. For instance, request STT
- Go to wallet and complete onboarding

### Additional Information
* Status version: nightly, 12 June
* Operating System: Android, iOS

### LINKED ISSUE #5131: `Error: Doesn't support name` if open Send transaction from Dapp and then go to Wallet for 1st time
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: "Error: Doesn't support name" if open Send Transaction screen from Dapp then open Wallet for 1st time.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Wallet screen is opened
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error is shown, if close it then white screen instead of Wallet, so user needs to restart app. After this Wallet screen is shown fine.
``` 
00:57 E/ReactNativeJS: Error: Doesn't support name: 
00:57 E/ReactNativeJS: 
00:57 E/ReactNativeJS: This error is located at:
00:57 E/ReactNativeJS:     in asset-selector
00:57 E/ReactNativeJS:     in reagent97
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTScrollView
00:57 E/ReactNativeJS:     in ScrollView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in reagent4
00:57 E/ReactNativeJS:     in reagent93
00:57 E/ReactNativeJS:     in reagent92
00:57 E/ReactNativeJS:     in send-transaction
00:57 E/ReactNativeJS:     in reagent116
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in main
00:57 E/ReactNativeJS:     in root
00:57 E/ReactNativeJS:     in reagent1
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in t
```
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4396006482/?accessToken=-k29U03VA5vrIlYq8g-7i-Yvs9g
1. Install app
2. create new account and switch to ropsten
3. open Test Dapp and request STT -> Send transaction screen is shown
4. close Send transaction screen and close Dapp
5. tap on Wallet tab
6. confirm that you wrote down sign in phrase and proceed to wallet -> currently error is shown. if close it then white screen so need to restart app

Note 1: error does not happen if Wallet screen was opened before opening Send transaction from Dapp. So, if user completes onboarding in the Wallet screen (writes down sign phrase) then no errors.

Note2: error does not happen if initiate tx from chat (/send command): onboarding screen is shown. If user completes onboarding, closes Send Transaction and opens Wallet then no error.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly from Jul 11 and of July 10 https://jenkins.status.im/job/status-react/job/nightly/487/ Didn't try older nightlies

* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4396006482/?accessToken=-k29U03VA5vrIlYq8g-7i-Yvs9g">TestFairy: Status 0.9.21 (6186) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/490/">status-react » nightly #490 [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/487/">status-react » nightly #487 [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://jenkins.status.im/job/status-react/job/nightly/490/">status-react » nightly #490 [Jenkins]</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #4724 
fixes #5131 

### Summary:

Adds Wallet Onboarding redirection for dapp transactions. That also fixes #5131 because it invalidates its conditions.

### Steps to test:
- try sending a dapp transaction for the first time and then go to Wallet
- try onboarding from chat `/send` and directly from Wallet

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/accounts/events.cljs [hunk 1]
```diff
@@ -155,19 +155,22 @@
  (fn [cofx [_ dev-mode]]
    (accounts.utils/account-update {:dev-mode? dev-mode} cofx)))
 
-(defn wallet-set-up-passed [db cofx]
+(defn wallet-set-up-passed [db modal? cofx]
   (let [transaction (get-in db [:wallet :send-transaction])]
     (merge
-     {:db (navigation/navigate-back db)}
+     (when-not modal?
```
Comment (flexsurfer) [inline src/status_im/ui/screens/accounts/events.cljs]: `if` ?

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
- [ ] 
`Request STT` (and other options) are not calling `Send transaction` screen after i complete onboarding in the following case:

1. Open status
2. Switch to ropsten
3. Open Simple dapp and Requset Ropsten ETH
4. Tap Request STT
5. Check that onboarding screen is shown
6. Complete onboarding
7. Tap cancel on the `Sign transaction screen`
8. Tap Request STT again

As a result - Sign Transaction screen is not shown. 

Next two issues appear after i perform steps above:

- [ ]  can't sign transaction from wallet - nothing happens when tapping Sign transaction button (iOS). NOTE: was able to send txn once from Android and it resulted in showing Send transaction screen twice, but cant repro it now because can't sent transaction from wallet at all.

- [ ] can't sign transaction from 1x1 chat - nothing happens when tapping Sign transaction button (iOS)

NOTE: all the issues are not reproducible after app restart

**Comment by goranjovic** [comment]
Looking at it

**Comment by yevh-berdnyk** [comment]
@goranjovic I've pushed an update for e2e tests

**Comment by goranjovic** [comment]
@asemiankevich pushed the fix

**Comment by asemiankevich** [comment]
@goranjovic 

image


``` 03:56 E/unknown:ReactNative: Error: Doesn't support name: 
03:56 E/unknown:ReactNative: 
03:56 E/unknown:ReactNative: This error is located at:
03:56 E/unknown:ReactNative:     in asset-selector
03:56 E/unknown:ReactNative:     in reagent92
03:56 E/unknown:ReactNative:     in RCTView
03:56 E/unknown:ReactNative:     in RCTView
03:56 E/unknown:ReactNative:     in RCTScrollView
03:56 E/unknown:ReactNative:     in ScrollView
03:56 E/unknown:ReactNative:     in RCTView
03:56 E/unknown:ReactNative:     in RCTView
03:56 E/unknown:ReactNative:     in reagent12
03:56 E/unknown:ReactNative:     in reagent88
03:56 E/unknown:ReactNative:     in reagent87
03:56 E/unknown:ReactNative:     in send-transaction
03:56 E/unknown:ReactNative:     in reagent86
03:56 E/unknown:ReactNative:     in RCTView
03:56 E/unknown:ReactNative:     in main
03:56 E/unknown:ReactNative:     in root
03:56 E/unknown:ReactNative:     in reagent1
03:56 E/unknown:ReactNative:     in RCTView
03:56 E/unknown:ReactNative:     in RCTView
03:56 E/unknown:ReactNative:     in t, stack:
03:56 E/unknown:ReactNative: name@12:685478
03:56 E/unknown:ReactNative: <unknown>@12:7263921
03:56 E/unknown:ReactNative: <unknown>@12:2313541
03:56 E/unknown:ReactNative: wrap_render@12:2314198
03:56 E/unknown:ReactNative: do_render@12:2315380
03:56 E/unknown:ReactNative: <unknown>@12:2315933
03:56 E/unknown:ReactNative: in_context@12:2278750
03:56 E/unknown:ReactNative: deref_capture@12:2278893
03:56 E/unknown:ReactNative: run_in_reaction@12:2307226
03:56 E/unknown:ReactNative: <unknown>@12:2315874
03:56 E/unknown:ReactNative: f@136:83728
03:56 E/unknown:ReactNative: beginWork@136:87321
03:56 E/unknown:ReactNative: o@136:128242
03:56 E/unknown:ReactNative: a@136:128621
03:56 E/unknown:ReactNative: T@136:132129
03:56 E/unknown:ReactNative: y@136:131565
03:56 E/unknown:ReactNative: v@136:131402
03:56 E/unknown:ReactNative: h@136:130681
03:56 E/unknown:ReactNative: c@136:129935
03:56 E/unknown:ReactNative: enqueueForceUpdate@136:60452
03:56 E/unknown:ReactNative: forceUpdate@198:1315
03:56 E/unknown:ReactNative: run_queue@12:2274442
03:56 E/unknown:ReactNative: flush_queues@12:2275714
03:56 E/unknown:ReactNative: run_queues@12:2275861
03:56 E/unknown:ReactNative: <unknown>@12:2275290
03:56 E/unknown:ReactNative: <unknown>@118:1369
03:56 E/unknown:ReactNative: x@118:643
03:56 E/unknown:ReactNative: callTimers@118:2788
03:56 E/unknown:ReactNative: value@113:3582
03:56 E/unknown:ReactNative: <unknown>@113:1067
03:56 E/unknown:ReactNative: value@113:3009
03:56 E/unknown:ReactNative: value@113:1039
03:56 I/HwPointEventFilter: do not support AFT because of no config
03:56 E/ConnectivityManager.CallbackHandler: callback not found for RELEASED message
```
Steps:

- Open status
- Switch to ropsten
- Open Simple dapp and Requset Ropsten ETH
- Tap Request STT
- Check that onboarding screen is shown
- Complete onboarding

**Comment by goranjovic** [comment]
@asemiankevich pushed the fix

**Comment by asemiankevich** [comment]
confirm https://github.com/status-im/status-react/issues/4724 and https://github.com/status-im/status-react/issues/5131 are fixed there


- [x] check onboarding screen is shown when trying to complete txn to dapp without completing onboarding before (new / recovered account) 
- [x] check onboarding screen is not shown for dapp txn when completed before in wallet 
- [x] can complete txn to dapp after onboarding called from dapp completed 
- [x] user can sign message to dapp without completing the onboarding 
- [x] onboarding screen still shown when trying to send from chat
- [x] onboarding screen shown when opening wallet (account created / recovered)

One problem i noticed it that onboarding screen is shown twice when sending ETH from wallet. Steps:
1. Recover account
2. Scan any code to start chatting
3. Send ETH
4. Complete onboarding
5. Complete the transaction
6. Tap got it and pay attention onboarding is shown again

@goranjovic could you please take a look?

**Comment by goranjovic** [comment]
@asemiankevich pushed the fix, should be fine now (fingers crossed)

**Comment by yevh-berdnyk** [comment]
@goranjovic , @asemiankevich imo wallet onboarding should be present for signing a message from a DApp because we show a transaction phrase there.

Steps:
- Open Status Test DApp
- Click Transactions button
- Click Sign message button

**Comment by asemiankevich** [comment]
I dont see any major issues with this PR . Lets merge it for now

**Comment by asemiankevich** [comment]
i believe we dont show onboarding for signing message because it is not a real transaction @goranjovic wdyt? good callout from @yevh-berdnyk that user does see those 3 words when signing message to dapp but how does he know if this phrase is right or not since he did not complete onboarding yet?

**Comment by goranjovic** [comment]
@yevh-berdnyk @asemiankevich  I agree that message signing should also be intercepted with onboarding, but unless something is broken in this PR, we can handle that separately. Creating a new issue for it: #5341

**Comment by asemiankevich** [comment]
@goranjovic great lets merge it!
