### PR TITLE
fix subs bug

### LINKED ISSUE #15678: subscriptions leak
:sub/run
:toasts/toast-cursor
0.56 ms

:sub/run
:toasts
0.10 ms

:sub/run
:toasts

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #15678

sometimes you can see in re-frisk subscriptions run in the loop, that means there is a mistake in usage, and we should find and fix that

image

PS: actually it didn't solve the problem, so the review is on hold

PS2: fixed , so subscription must be called only by reagent when its initializing the view, but in this case it was run in the dismiss function outside of reagent context , which leads to subscription leak 

ready for review

### CODE REVIEW

File: src/status_im2/common/toasts/view.cljs [hunk 1]
```diff
@@ -43,7 +43,7 @@
       [:f>
        (fn []
          (let [duration (or (rf/sub [:toasts/toast-cursor id :duration]) 3000)
-               on-dismissed #((or (rf/sub [:toasts/toast-cursor id :on-dismissed]) identity) id)
+               on-dismissed (or (rf/sub [:toasts/toast-cursor id :on-dismissed]) identity)
```
Comment (flexsurfer) [inline src/status_im2/common/toasts/view.cljs:46]: this is the fix

File: src/status_im2/common/toasts/view.cljs [hunk 2]
```diff
@@ -80,7 +80,7 @@
                                      (create-timer)))))]
            ;; create auto dismiss timer, clear timer when unmount or duration changed
            (rn/use-effect (fn [] (create-timer) clear-timer) [duration])
-           (rn/use-unmount on-dismissed)
+           (rn/use-unmount #(on-dismissed id))
```
Comment (ilmotta) [inline src/status_im2/common/toasts/view.cljs:83]: Why do we need to pass the `id` here and create the anonymous function? It's questionable because the subscription `[:toasts/toast-cursor id :on-dismissed]` already returns a function that has access to the `id` value and the `identity` function doesn't care about any argument in this case.

I'm just wondering why it wouldn't work using just `(rn/use-unmount on-dismissed)`.

**Review by ilmotta — APPROVED** [review]
Good catch and fix @flexsurfer

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/common/toasts/view.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im2/common/toasts/view.cljs:83]: @yqrashawn ?

Comment (yqrashawn) [reply src/status_im2/common/toasts/view.cljs:83]: It's just to handle situations where id and on-dismissed are both dynamically generated and hard or not elegant enough to pass the id to the on-dismissed fn. 
It might be a premature optimization.
