### PR TITLE
Resolve schema issues for Context Tag when joining a Community

### LINKED ISSUE #18912: Schema error: tags/context-tag component
### Steps to reproduce
- Open a community link (overview screen)
- Click request to join button
- Slide the "Slide to request to join" Button

### Error
```
 LOG  -- Schema error at quo.components.tags.context-tag.view/view-internal ----

Invalid function arguments:
  [{:full-name "Test 2",
    :profile-picture {:fn #object[#object[Function]]},
    :size 24,
    :theme :light}]

Input Schema:
  [:catn [:props [:multi {#} [#] [#] [#] [#] ...]]]

Errors:
  {:in [0 :profile-picture],
   :message "should be an integer",
   :path [:props :malli.core/default :profile-picture 0 0 0],
   :schema :int,
   :value {:fn #object[#object[Function]]}}
  {:in [0 :profile-picture],
   :message "should be a string",
   :path [:props :malli.core/default :profile-picture 0 0 1],
   :schema :string,
   :value {:fn #object[#object[Function]]}}
  {:in [0 :profile-picture :uri],
   :message "missing required key",
   :path [:props
          :malli.core/default
          :profile-picture
          0
          0
          2
          ...],
   :schema [:map [:uri [#]]],
   :type :malli.core/missing-key,
   :value nil}

------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #18912 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

This PR attempts to resolve the schema issues described in issue #18912.

* The cause of the issue seems to be related to mismatch of schema definitions. 
  * For example, the **user-avatar** component assumes a `profile-picture` could be an `image-source` or a `profile-picture-fn-obj`, but the **context-tag** component does not allow for a `profile-picture-fn-obj` value. Which leads to schema errors when passing along a `profile-picture-fn-obj` value through the **context-tag** component and into the **user-avatar** component.
  * Note: `profile-picture-fn-obj` is structured as a map that contains a function, and that function receives a map and returns a URI string.
  * For context, here's the call site of the `profile-picturn-fn` in the **user-avatar** component: https://github.com/status-im/status-mobile/blob/cfaed80066bca4ecb8386afc10684dfdd5399b61/src/quo/components/avatars/user_avatar/view.cljs#L84-L102

#### Platforms

- Android
- iOS

##### Functional

- joining communities
- context-tag components

### Steps to test
In order to reproduce the schema errors, the mobile app will need a few pieces setup. The attached screenshots will showcase the steps to reproduce the error and verify the changes. And the following steps are based on these [instructions](https://discord.com/channels/1103692771585433630/1209562159143587910). Another note, 
1. Create a community
2. Invite the mobile app user to the community
3. Open the community on mobile
4. Press the "Request to Join" button
5. Slide the "Slide to request to join" button
6. A bottom sheet should appear asking for a password and the schema errors should be visible in the console.

#### Before the schema changes to **context-tag** component
https://github.com/status-im/status-mobile/assets/2845768/43a4481d-6170-4700-8fff-a41daa299b24

#### After the schema changes to **context-tag** component
https://github.com/status-im/status-mobile/assets/2845768/d07a8b86-c17d-4463-8db4-628821493fee

status: ready

### CODE REVIEW

File: src/quo/components/avatars/user_avatar/view.cljs [hunk 1]
```diff
@@ -40,6 +40,7 @@
    :color            intials avatar text color
    :size             intials avatar radius
    :ring?            render ident ring around avatar? NOTE: this option may not work if override-ring? is not nil}
+   :ring-width       the ring width
```
Comment (J-Son89) [inline src/quo/components/avatars/user_avatar/view.cljs]: we should just delete this doc string in favor of Malli, however it's best to do a check and make sure there's no important comments there.

File: src/quo/components/tags/context_tag/schema.cljs [hunk 2]
```diff
@@ -1,5 +1,6 @@
 (ns quo.components.tags.context-tag.schema
-  (:require [malli.core :as malli]))
+  (:require [malli.core :as malli]
+            [quo.components.avatars.user-avatar.schema :refer [?profile-picture]]))
```
Comment (J-Son89) [inline src/quo/components/tags/context_tag/schema.cljs]: hmm, to me it looks like the profile picture schema is not living in the correct place if it's reused in 2 places but set beside a specific component? should it not be somewhere more generic? 

@ilmotta, @clauxx do we have some structure we want to apply for situations like this?

File: src/quo/components/avatars/user_avatar/schema.cljs [hunk 3]
```diff
@@ -0,0 +1,21 @@
+(ns quo.components.avatars.user-avatar.schema)
+
+(def ^:private ?profile-picture-fn-params
+  [:map
+   [:length :int]
+   [:full-name :string]
+   [:font-size :int]
+   [:indicator-size {:optional true} [:maybe :int]]
+   [:indicator-color {:optional true} [:maybe :string]]
+   [:override-theme :schema.common/theme]
```
Comment (J-Son89) [inline src/quo/components/avatars/user_avatar/schema.cljs]: we certainly don't want override theme props anymore, can you change this to `theme`? 
probably doc string was outdated.

File: src/quo/components/tags/context_tag/schema.cljs (hunk 2 above)
Comment (clauxx) [reply src/quo/components/tags/context_tag/schema.cljs]: could be added to the common schema registry maybe?

File: src/quo/components/avatars/user_avatar/schema.cljs [hunk 4]
```diff
@@ -0,0 +1,21 @@
+(ns quo.components.avatars.user-avatar.schema)
```
Comment (clauxx) [inline src/quo/components/avatars/user_avatar/schema.cljs]: might as well add a schema for user-avatar if already adding this

File: src/quo/components/tags/context_tag/schema.cljs (hunk 2 above)
Comment (J-Son89) [reply src/quo/components/tags/context_tag/schema.cljs]: I think we need a better structure than just common. 
At the very least 
common/category-1
common/category-2
Etc, otherwise we just end up with a load of random schemas lumped in together

Comment (clauxx) [reply src/quo/components/tags/context_tag/schema.cljs]: we do have 2 categories so far: `schema.common` and `schema.re-frame`. For a separate category, just create a new namespace inside `schema`. Maybe smth like `schema.quo`?

Comment (J-Son89) [reply src/quo/components/tags/context_tag/schema.cljs]: great, glad to hear! 
Whatever you guys advise 👍

**Review by J-Son89 — APPROVED** [review]
assuming you'll make the changes requested 👍 

Nice work @seanstrom 🚀

File: src/quo/components/avatars/user_avatar/schema.cljs (hunk 3 above)
Comment (seanstrom) [reply src/quo/components/avatars/user_avatar/schema.cljs]: I think in this case **profile-picture-fn** will expect `override-theme`. For example, the **profile-picture-fn** could be the value returned from the [`get-initials-avatar-uri-fn`](https://github.com/status-im/status-mobile/blob/28f43acb833e302dbd0d013ebe4c8e1cce538e6a/src/utils/image_server.cljs#L199): https://github.com/status-im/status-mobile/blob/28f43acb833e302dbd0d013ebe4c8e1cce538e6a/src/utils/image_server.cljs#L199-L230

Comment (J-Son89) [reply src/quo/components/avatars/user_avatar/schema.cljs]: Ab okay, that's also some code that needs adjustment. We moved away from override theme approach a while back

File: src/quo/components/avatars/user_avatar/view.cljs (hunk 1 above)
Comment (seanstrom) [reply src/quo/components/avatars/user_avatar/view.cljs]: Okay sounds good, I've revised the docstring to contain a small warning, since the warning may still be useful. Let me know what you think 🙏

File: src/quo/components/tags/context_tag/schema.cljs (hunk 2 above)
Comment (seanstrom) [reply src/quo/components/tags/context_tag/schema.cljs]: Nice! I've created a `schema.quo` namespace, lmk what you think 🙏

File: src/quo/components/avatars/user_avatar/schema.cljs (hunk 3 above)
Comment (seanstrom) [reply src/quo/components/avatars/user_avatar/schema.cljs]: I think in this case there are some re-frame subs that initialise the `profile-picture-fn` with a `:theme`, and then later some rendering logic is allowed override that initial theme. 

This makes me wonder:
* Should I rename the field `override-theme` to `theme`?
* Or should I refactor the code to remove the overriding logic?
  * Is there a clear preference on who should control the theme?
  
Depending on the changes that should be made, I may split them into a separate PR, lmk your thoughts when you can 🙏

File: src/quo/components/tags/context_tag/schema.cljs (hunk 2 above)
Comment (ilmotta) [reply src/quo/components/tags/context_tag/schema.cljs]: Sorry if I'll just repeat what I already said somewhere, but I think `schema.common` is not the right place to put a schema just because it's used a handful of times in the app. Maybe we should rename that namespace because `common` is a word I regret to have used. Common means for many people common to 2 or more things, but in that namespace I remember I meant really something reaaaally common and general. If possible, not tied to any particular domain of the app (profile is tied).

I like `schema.quo`. It is short and better for separating concerns.

> @ilmotta, @clauxx do we have some structure we want to apply for situations like this?

I think the structure should continue to grow more organically because we have mostly used it for quo components. Once/if we start to use schemas touching more domain entities, I believe our preferences will probably shift. But my personal take on your question is that I prefer to separate schemas by the most stable and closest bounded context they are in (quo being a bit of an exception, but it could be seen as a context too).

File: src/quo/components/avatars/user_avatar/schema.cljs (hunk 4 above)
Comment (seanstrom) [reply src/quo/components/avatars/user_avatar/schema.cljs]: If I'm moving the schema definitions into the `schema.quo` namespace, is alright if I skip this for now?

**Review by ilmotta — APPROVED** [review]
Nice one @seanstrom!

File: src/schema/quo.cljs [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+(def ^:private ?profile-picture
+  [:or
+   :schema.common/image-source
+   [:map
+    [:fn [:=> [:cat ?profile-picture-fn-params] :string]]]])
+
+
+(defn register-schemas
+  []
+  (registry/register ::profile-picture ?profile-picture))
```
Comment (clauxx) [inline src/schema/quo.cljs]: to keep it consistent, might be better to use `::profile-picture-source`

**Review by clauxx — APPROVED** [review]
Good job 👍

File: src/schema/quo.cljs (hunk 5 above)
Comment (seanstrom) [reply src/schema/quo.cljs]: Yup yup will do 👍

File: src/quo/components/tags/context_tag/schema.cljs (hunk 2 above)
Comment (J-Son89) [reply src/quo/components/tags/context_tag/schema.cljs]: sounds good @ilmotta , common and utils are two hellish naming conventions in any codebase 😆

File: src/quo/components/avatars/user_avatar/schema.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo/components/avatars/user_avatar/schema.cljs]: sounds like we should do it in a separate pr/issue, could you create an issue to track this? 🙏

File: src/quo/components/avatars/user_avatar/schema.cljs (hunk 4 above)
Comment (clauxx) [reply src/quo/components/avatars/user_avatar/schema.cljs]: yep 👍

File: src/quo/components/avatars/user_avatar/schema.cljs (hunk 3 above)
Comment (seanstrom) [reply src/quo/components/avatars/user_avatar/schema.cljs]: yup yup will do 👍

File: src/quo/components/avatars/user_avatar/view.cljs [hunk 6]
```diff
@@ -25,32 +25,11 @@
...
-  #RRGGBBAA
-  rgb(255,255,255)
-  rgba(255,255,255,0.1) note alpha is 0-1
-
-  the reason we use the `profile-picture-fn` here is to separate
-  logic (pubkey, key-uid... in subs) and style (color, size... in this component)"
+   WARNING:
+   When calling the `profile-picture-fn` and passing the `:ring?` key, be aware that the `profile-picture-fn`
+   may have an `:override-ring?` value. If it does then the `:ring?` value will not be used.
+   For reference, refer to the `utils.image-server` namespace for these `profile-picture-fn` are generated."
```
Comment (yqrashawn) [inline src/quo/components/avatars/user_avatar/view.cljs:32]: 👍

**Review by yqrashawn — APPROVED** [review]
LGTM
