### PR TITLE
fix: avoid re-renders inside contact-list for new-chat sheet

### LINKED ISSUE #20532: Contact list reloads when selecting/unselecting contacts (Android)
Android only. Reproducing on Android 12, Samsung Galaxy A52

Areas affected: default contact list, contact list in group chat

**Steps:** 

1. Open contact list
2. Select/unselect contacts
3. Try scrolling contact list

**Actual result:** looks like contact list is reloading after selecting/unselecting contacts which leads to scrolling gets stuck or list does not react on tap. 

https://github.com/status-im/status-mobile/assets/97245802/43c9cb20-fb00-4d48-8123-a8ebf36bf816

- Status version: nightly 
- Operating System: Android

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes https://github.com/status-im/status-mobile/issues/20532

### Summary

* This PR attempts to fix the contact list re-rendering issue when panning in the contact list or selecting a contact from the contact list inside the New Chat screen.
  * It seems that the contact-list is inside a bottom-sheet, and the bottom-sheet supports a drag gesture for closing the sheet. When this gesture occurs, it seems we attempt to prevent scrolling in the scroll-view by setting `:scroll-enabled` to `false`. However, when this prop is changed the scroll-view will re-render all the list items, which can cause the contact images to flicker and it seems to interfere with selecting a contact.
    * Here's a snippet of the code that handles setting the `scroll-enabled` reagent atom: https://github.com/status-im/status-mobile/blob/014f44683554ae7678b875a1ca14e452c01154c4/src/status_im/common/bottom_sheet_screen/view.cljs#L16-L36
  * One solution would be to re-write the drag gesture or the composition of the gesture handler with a scroll view. It's possible this could be done in a way that avoids disabling the scrolling and causing a re-render in the scroll-view.
  * Another solution would be to avoid setting `scroll-enabled` for the contact list, which solves the re-rendering issue, but does not allow the drag gesture to override the scroll gesture.
  * In this PR we currently use the second approach, which matches the way we implement this functionality for the manage-embers screen for group chats.
    * Note, the drag gesture still will work on the top portion of the bottom-sheet, and the user can still close the sheet by pressing the "X" icon.

#### Platforms

- Android
- iOS

##### Functional

- Creating a new-chat

### Steps to test
- Open the Status Mobile app
- Login to a profile
- Navigate to the messenger home screen
- Press the "+" icon and select "New Chat" from the bottom drawer
- If there's a contact list with many contacts, attempt to scroll the contact list by scrolling up and down
- Attempt to select a contact from the contact list
- Attempt to close the bottom-sheet by pulling the top of the bottom sheet down

### Before and after screenshots comparison

Note, that in these screen recordings I've intentionally duplicated my contacts in the contact list because I didn't have enough contacts added to my profiles. So that's why there's repeated data and multiple items selected when selecting a single contact.

| Status  | iOS (if available)    | Android (if available)
| --- | --- | --- |
| Before |  <video src="https://github.com/user-attachments/assets/81181dd2-5d37-46cc-8696-bc12477c3d04" /> | <video src="https://github.com/user-attachments/assets/83ebf959-f086-4119-a57f-e1a83ea8b4e9" />  |
| After  | <video src="https://github.com/user-attachments/assets/7fbb8e10-fb81-4044-9d88-f65f000ca447" />  | <video src="https://github.com/user-attachments/assets/46f27d41-530b-4f20-a54c-b10d4bfdd57e" /> |

status: ready

### CODE REVIEW

**Comment by ulisesmac** [comment]
Hi @seanstrom !

Thank you for this PR.

The avatar component blinks all over the app, I was recently working in the onboarding and found the avatar is using:

https://github.com/status-im/status-mobile/blob/a1e3bb3bd6906c8b74f0f9ded660e9f9d8a8095e/src/quo/components/common/no_flicker_image.cljs#L35

but I don't think that approach is being effective. 

I also noticed this avatar rerender flickering in my latest PR:

- https://github.com/status-im/status-mobile/pull/21641 (if you want to check it)

----------------------------------------------

About the solution, I have several things to say.

A `flat-list` shouldn't re-render its content when we disable/enable its scroll. Are we sure a plain React Native's `FlatList` behaves like that? we have a wrapper that I've always suspected is doing some extra computations, so I'd start answering this question. If the blame is from our wrapper:

We could check what are the dependencies causing the re-renders and fix them (or directly fix the wrapper).

Otherwise, even though the flat-list items are being re-rendered, the avatar is receiving the exact same props, so we are probably passing some extra data that is causing the re-render.

So, I'd say the root cause and solution both rely in a deeper issue. WDYT?

**Comment by seanstrom** [comment]
@ulisesmac I decided to take a deeper look at what was happening inside these components based on your feedback.

There seems to be a variety of issues, which I've tried to address in some new changes. For example:
* We need to use a memoized function inside our flat-list/section-list wrapper, because otherwise we'll be passing a new function reference whenever it re-renders.
* We need to use a memoized function when passing around the `on-scroll` handler to bottom-sheets, otherwise we'll be passing a new function reference to the section-list / flat-list wrapper on each render.
* And it seems like we've been generating/formatting urls to profile images on each render, which should have been fine, but it seems we were embedding a timestamp in the url. And that that timestamp seemed to be generated on each render from inside the format function. So if the user avatar component would re-render, then the image would reload because the timestamp would change. Moving forward we'll allow for passing in the timestamp to the function instead of generating one from the inside.

Thank you again for the feedback! It helped uncover some weird glitches that may now be resolved, and it seems we can even keep using `scroll-enabled` 🙌

File: src/react_native/gesture.cljs [hunk 1]
```diff
@@ -112,17 +113,21 @@
            render-fn]
     :or   {sticky-section-headers-enabled true}
     :as   props}]
-  (let [data (flatten-sections sections)]
+  (let [data        (flatten-sections sections)
+        render-item (rn/use-callback
+                     (fn [p1 p2 p3 p4]
```
Comment (ilmotta) [inline src/react_native/gesture.cljs:118]: What is `p4` if there are only 3 deps?

File: src/status_im/contexts/chat/home/new_chat/view.cljs [hunk 2]
```diff
@@ -136,8 +133,8 @@
          :render-section-header-fn contact-list/contacts-section-header
          :render-section-footer-fn contact-list/contacts-section-footer
          :content-container-style  {:padding-bottom 70}
-         :render-fn                render-fn
-         :scroll-enabled           @scroll-enabled?
+         :render-fn                contact-item-render
+         :render-data              {:set-has-error set-has-error}
```
Comment (ilmotta) [inline src/status_im/contexts/chat/home/new_chat/view.cljs:137]: This is exactly the fix I found here https://github.com/status-im/status-mobile/issues/21658#issuecomment-2492104289 coincidentally. Thanks for the fix @seanstrom

**Review by ilmotta — APPROVED** [review]

File: src/react_native/gesture.cljs (hunk 1 above)
Comment (seanstrom) [reply src/react_native/gesture.cljs:118]: So I think `p1` `p2` `p3` `p4` are the arguments that are passed to the render function. So in this case `p1` is the item in the list, `p2` is the index, `p3` is a reference to the separators in the list, and `p4` is the render-data that's passed from the list component.

More details can be found here: https://github.com/status-im/status-mobile/blob/afe90d0ec989c23e0bb3b41725fa67366fe721e4/src/react_native/flat_list.cljs#L8-L13

Comment (ilmotta) [reply src/react_native/gesture.cljs:118]: Thanks, my brain farted and was confused with `use-callback`.

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/home/new_chat/view.cljs:137]: And the same I'm applying in my WIP for:
- https://github.com/status-im/status-mobile/issues/21658

@seanstrom Are you fixing all the avatar usages in this PR or just this one? I'm asking because we don't want to duplicate work

**Comment by ulisesmac** [comment]
@seanstrom 

Great! seems you've found the underlying issues :tada: 

For:

>    We need to use a memoized function inside our flat-list/section-list wrapper, because otherwise we'll be passing a new function reference whenever it re-renders.

>    We need to use a memoized function when passing around the on-scroll handler to bottom-sheets, otherwise we'll be passing a new function reference to the section-list / flat-list wrapper on each render.

This is what I was recently talking about with @ilmotta, at the end seems problems are related to passing unstable references. Let's just be careful about adding extra complexity to the implementations, just in case that happens.

>  And it seems like we've been generating/formatting urls to profile images on each render, which should have been fine, but it seems we were embedding a timestamp in the url. And that that timestamp seemed to be generated on each render from inside the format function. So if the user avatar component would re-render, then the image would reload because the timestamp would change. Moving forward we'll allow for passing in the timestamp to the function instead of generating one from the inside.

Great finding!
We could ask what is the purpose of that timestamp and if it could be simplified. cc: @ilmotta Do you know why do we need it?

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 2 above)
Comment (seanstrom) [reply src/status_im/contexts/chat/home/new_chat/view.cljs:137]: This PR is only intending to fix the usage of the reloading of the avatar images inside the contact-list view for a new-chat, but it's possible that some of the changes related to the image source uri will affect other usages too.

**Comment by ilmotta** [comment]
> We could ask what is the purpose of that timestamp and if it could be simplified. cc: ilmotta Do you know why do we need it?

@ulisesmac @seanstrom I don't see the `clock` URL parameter being used by the `handlers.ParseImageParams` function in status-go, which is used to process endpoints like `/accountImages` and `/contactImages`. It looks like a leftover in the mobile client which was useful in the past, but can be safely removed now. I'd still check if everything works before removing `clock`.

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/home/new_chat/view.cljs:137]: Got it, then I'll continue with

- #21658 

Once this PR is merged. Thanks for all the fixes

**Review by ulisesmac — APPROVED** [review]

**Comment by seanstrom** [comment]
@ilmotta I think `clock` in some cases is being used to invalidate the local image cache, for example, if a contact changes their profile image then it seems we use the clock query param to create a new image-uri so we can refetch the image locally.

Here's a snippet of code related to the contact images: https://github.com/status-im/status-mobile/blob/d98de2efbf28b5b3dfbd73db859a4d18390dd940/src/status_im/subs/contact/utils.cljs#L10-L25

---

So my thought is to allow for clock to be passed as a param, but still avoid automatically creating new clock values on each render (what was happening before). Thoughts?

**Comment by ilmotta** [comment]
> @ilmotta I think `clock` in some cases is being used to invalidate the local image cache, for example, if a contact changes their profile image then it seems we use the clock query param to create a new image-uri so we can refetch the image locally.
> 
> Here's a snippet of code related to the contact images:
> 
> https://github.com/status-im/status-mobile/blob/d98de2efbf28b5b3dfbd73db859a4d18390dd940/src/status_im/subs/contact/utils.cljs#L10-L25
> 
> So my thought is to allow for clock to be passed as a param, but still avoid automatically creating new clock values on each render (what was happening before). Thoughts?

Makes sense now to me, thanks for sharing that @seanstrom. I'm not sure I understood your idea, is it that you want to decouple the URL generation part from rendering a contact in various places?

Somewhat related, one of the problems I see in the design of the contacts subscriptions, in particular the sub `:contacts/contacts` is that many other subs depend on this sub (and thus from from the output of `replace-contact-image-uri`, and whenever the clock value of any image changes, an expensive cascade of subs are invalidated, even though they don't care about the clock or image URLs. @clauxx @vkjr this is yet another example of pulling too much from subs.

**Comment by Horupa-Olena** [comment]
@seanstrom Thank you for your PR!
Everything looks good, and the PR is ready to be merged.

**Comment by seanstrom** [comment]
Hey @ilmotta 👋 

> 
> Makes sense now to me, thanks for sharing that @seanstrom. I'm not sure I understood your idea, is it that you want to decouple the URL generation part from rendering a contact in various places?
> 

So in some places of the code we pass the `:clock` value as a param (contact images), but for the other image uri (initials image, and other avatar images) we would generate a new clock timestamp each time the avatar component would re-render. Meaning that we never passed a clock param when generating those image uri, and they would generate their own and that would cause the image to be refetched locally (causing a flicker I think).

Moving forward, we would not generate the timestamps anymore when formatting the image uri, and instead we would pass a clock param to those functions, just like we do when generating contact image uri. That's what this PR does atm, but I wanted to make sure that sounded okay since we were considering removing the clock param from those functions.

**Comment by ilmotta** [comment]
> Hey @ilmotta 👋
> 
> > Makes sense now to me, thanks for sharing that @seanstrom. I'm not sure I understood your idea, is it that you want to decouple the URL generation part from rendering a contact in various places?
> 
> So in some places of the code we pass the `:clock` value as a param (contact images), but for the other image uri (initials image, and other avatar images) we would generate a new clock timestamp each time the avatar component would re-render. Meaning that we never passed a clock param when generating those image uri, and they would generate their own and that would cause the image to be refetched locally (causing a flicker I think).
> 
> Moving forward, we would not generate the timestamps anymore when formatting the image uri, and instead we would pass a clock param to those functions, just like we do when generating contact image uri. That's what this PR does atm, but I wanted to make sure that sounded okay since we were considering removing the clock param from those functions.

All clear, thanks for the explanation 💯

**Comment by churik** [comment]
@seanstrom 
can we merge this, please?
