### PR TITLE
fix: resolve activity centre design feedback

### LINKED ISSUE #16841: Design review: activity centre
- [ ] 1. Dot is overlapping with the timestamp on "Request hasn't been accepted" notification - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510053049)  
- [ ] 2. Spacing in AC notifications doesn't match the design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510052712)

- [ ] 3.  on the `Accepted` label status tag padding is different from design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#511248488)
- [ ] 4. wrong spacing in contact request AC notification between username and text - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#511247483)
- [ ] 5. No blur on the bottom drawer  comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510053488) 
suppose it might be a part of https://github.com/status-im/status-mobile/issues/15513 or https://github.com/status-im/status-mobile/issues/16722 (just an assumption, not sure)

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
fixes https://github.com/status-im/status-mobile/issues/16841

- [x] 1. Dot is overlapping with the timestamp on "Request hasn't been accepted" notification - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510053049)  
- [x] 2. Spacing in AC notifications doesn't match the design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510052712)
- [x] 3. on the `Accepted` label status tag padding is different from design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#511248488)
- [x] 4. wrong spacing in contact request AC notification between username and text - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#511247483)
- [ ] 5. Deferred to @flexsurfer 
- [x] 6. Text isn't centred in the decline/accept buttons - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=4909:50437&mode=design#538594339)  
- [x] 7. Customization colors in shell theme are the dark theme ones (orange/60 in this case)- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=4909:50437&mode=design#538599185)

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/activity_log/style.cljs [hunk 1]
```diff
@@ -39,11 +39,13 @@
 
 (defn title
   []
-  {:color colors/white})
+  {:color     colors/white
+   :max-width "80%"})
```
Comment (ilmotta) [inline src/quo2/components/notifications/activity_log/style.cljs]: In the DS, the title is adjusted automatically based on the horizontal space left after showing the timestamp, unread dot and the icon. I think using the percentage is not the way to go.

Comment (flexsurfer) [inline src/quo2/components/notifications/activity_log/style.cljs]: percentage should be never used , only fixed margins or paddings

**Review by siddarthkay — APPROVED** [review]
Looks good to me!

**Review by flexsurfer — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Review by Francesca-G — COMMENTED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=4909%3A50437&mode=design&t=0E6TzxJdZKlSVaul-1) with the design review :)

**Comment by qoqobolo** [comment]
Hi @BalogunofAfrica, thanks for your great work!
I will test the PR manually once [Francesca's review comments](https://github.com/status-im/status-mobile/pull/17105#pullrequestreview-1597738621) are resolved as well so that I check the final build.
So could you ping me here when it's done, please?
Thanks!

**Comment by BalogunofAfrica** [comment]
Hi @Francesca-G I have updated the PR

**Review by Francesca-G — APPROVED** [review]
The user tag shouldn't have the identicon ring 
(it didn't have it previously, so I don't know what happened)

Screenshot 2023-08-29 alle 15 49 12

Besides that it looks good :)

**Comment by qoqobolo** [comment]
> The user tag shouldn't have the identicon ring
(it didn't have it previously, so I don't know what happened)

@Francesca-G this issue should be probably fixed in [this PR](https://github.com/status-im/status-mobile/pull/17034). 
I will clarify this moment there with @yqrashawn.

@BalogunofAfrica please don't merge this PR for now, please, I'm waiting for the results of the e2e tests.
I will let you know.

**Comment by BalogunofAfrica** [comment]
> The user tag shouldn't have the identicon ring (it didn't have it previously, so I don't know what happened)
> 
> Screenshot 2023-08-29 alle 15 49 12
> Besides that it looks good :)

The ring was added in this PR https://github.com/status-im/status-mobile/pull/16962 which addressed this issue https://github.com/status-im/status-mobile/issues/16577

**Comment by qoqobolo** [comment]
Thanks for the fixes and for waiting @BalogunofAfrica!
PR can be merged.

**Comment by BalogunofAfrica** [comment]
Thank you @qoqobolo
