### PR TITLE
fix(wallet)_: Send flow from saved address and QR scanner

### LINKED ISSUE #20878: The FROM page is shown when user goes to send flow using scanner
Follow up for https://github.com/status-im/status-mobile/pull/20773

### Precondition:
User has only one account

### Steps:
1. Goes to scanner -> scan the wallet QR

### Actual result:
User sees the 'account 1' in from page

https://github.com/user-attachments/assets/66f06ead-a7b1-436f-aec0-54683201dc1b

### Expected result:
The user is navigated directly to the send flow page if user has only 1 account and uses scanner during send flow

### ENV:
Nightly 25 Jul 2024

### LINKED ISSUE #21898: Send flow is broken when it's started from Saved Addresses
# Bug Report

Send flow is broken when it's started from Saved Addresses

## Problem 

https://github.com/user-attachments/assets/2ebd5b13-26d5-4100-a9a8-8f5445355bd0

#### Expected behaviour

The user should be allowed to pick the wallet account to send from and should be able to send assets from it.

#### Actual behaviour

The user can not pick the account to send from, instead taken to the assets page where the default account assets are shown, but can not generate a route or send after selecting an asset.

### Reproduction

1. Open Status
2. Navigate to `Profile > Wallet > Saved Addresses`
3. Add a new saved address if the profile doesn't have any
4. Tap on the saved address and tap on `Send to <SAVED_ADDRESS_NAME>`
5. Select any asset and enter an amount

### Additional Information

- Status Version: nightly [08/01]
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21898
fixes #20878

### Summary

This PR:
 - fixes send flow from saved addresses
 - adds back send flow from general QR scanner

| Single Account | Multiple Accounts  | Entry from QR Scanner
| --- | --- | --- |
| <video src="https://github.com/user-attachments/assets/72ac7370-ecf2-4083-b187-8319d94664d3" />  | <video src="https://github.com/user-attachments/assets/41d88e9a-d43e-4162-9a1b-61ec49284efb" />  | <video src="https://github.com/user-attachments/assets/ffcdcefd-bbe0-4ea5-9e7e-945546b849ca" /> |

### Testing notes

A quick test of the send flow from the Wallet tab is appreciated

### Platforms

- Android
- iOS

##### From Saved Addresses

- Open Status
- Navigate to `Profile > Wallet > Saved Addresses`
- Add a new saved address if it is empty
- Tap on any saved address and tap on `Send to <SAVED_ADDRESS_NAME>`
- Verify the user is taken to the account selection (`From`) page if the user has more than one operable accounts
- Verify the user is taken to the select asset page (default account) if the user has only one account
- Verify the routes are generated after asset selection and can be sent successfully

##### From QR Scanner

- Open Status
- Tap on scanner icon (`[-]`) on the profile navigation header
- Scan a valid address
- Verify the user is taken to the account selection (`From`) page if the user has more than one operable accounts
- Verify the user is taken to the select asset page (default account) if the user has only one account
- Verify the routes are generated after asset selection and can be sent successfully

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -116,6 +116,44 @@
...
+                          [:wallet/wizard-navigate-forward
+                           {:current-screen stack-id
+                            :start-flow?    true
+                            :flow-id        :wallet-send-flow}])}]]]})))
+
+(rf/reg-event-fx
+ :wallet/init-send-flow-for-address
+ (fn [_ [args]]
+   {:fx [[:dispatch [:wallet/clean-send-data]]
+         [:dispatch [:wallet/open-send-flow args]]]}))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/events.cljs]: We clean the send data before user goes into the flow. This ensure no data from any other flows is left and also to prevent any bugs.

File: src/status_im/contexts/wallet/send/from/view.cljs [hunk 2]
```diff
@@ -4,71 +4,78 @@
...
-      :header                   [account-switcher/view
-                                 {:on-press      #(rf/dispatch [:navigate-back])
-                                  :margin-top    (safe-area/get-top)
-                                  :switcher-type :select-account}]}
+      :header                   [quo/page-nav
+                                 {:type       :no-title
+                                  :icon-name  :i/close
+                                  :on-press   events-helper/navigate-back
+                                  :margin-top (safe-area/get-top)
+                                  :background :blur}]}
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/from/view.cljs:72]: We don't need account switcher on the from page

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM 🔥

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/send/events.cljs]: Is `:wallet/open-send-flow` the only way the send flow is started? If so, we could include the cleaning once in there, since it seems to be required every time we start the flow.

**Review by shivekkhurana — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for taking in work implementing this universal scanner send flow.

Unfortunately, one issue is found

## ISSUE 1: Empty accounts appear in 'FROM' accounts list and asset amounts are missing after long tap

### Steps to reproduce:
1. Open the wallet with available assets.
2. Add multiple accounts, including accounts without assets.
3. Navigate to the main wallet page 
4. Long-tap on an asset which is present on at least 2 accounts

### Actual result:
- Empty accounts are included in the 'from' accounts list.
- Current accounts lack displayed asset amounts.

https://github.com/user-attachments/assets/1411ab2e-c1fa-4b66-87c9-d32c21a8a272

### Expected result:
- Only accounts with assets should be enabled in the 'from' accounts list, empty accounts should be disabled
- Current accounts should display their respective asset amounts correctly.

image

### Additional info:
Here are test cases for current PR:

Send flow with universal scanner https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=42731251#gid=42731251

Send flow with long tap on main page
https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 2: Wrong navigation after new account is selected in the FROM accounts list page 

### Precondition:
The user has at least 2 accounts with some assets

### Steps:
1. Scan valid account using a universal scanner
2. Go to send flow 
3. Go back to list of accounts
4. Select some account again


### Actual result:
The user is navigated directly to the page routes generation page missing the select assets page and network preferences

https://github.com/user-attachments/assets/704ef6d8-a3d0-4fd6-a2db-39631afc0a19

### Expected result:
The user is navigated to select the assets page 

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/events.cljs]: No @clauxx, as far as i checked, we have other entry points which we need to cover. We can unify the event into this which we need to explore later.

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Both Issue 1 & 2 should be fixed now 🙏 Please retest

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. No issues from my side. PR is ready to be merged
