### PR TITLE
[17377-17378] Fix reply view in activity center showing only one phot…

### LINKED ISSUE #17377: No text in notification in AC when receiving a reply with image and text description
# Bug Report

Perhaps this issue might be combined with https://github.com/status-im/status-mobile/issues/17378 when fixing

### Reproduction

1. UserA and UserB: join a community
2. UserA: send a message and go to the activity center
3. UserB: reply to the message with an image and some text
4. UserA: check the notification in AC

#### Expected behavior
Figma: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=599-22025&mode=design&t=Byre7HXLbBvEh6dG-0

Screenshot 2023-09-21 at 12 23 51

#### Actual behavior

No text in the notification

https://github.com/status-im/status-mobile/assets/67952253/5dd21a97-24b9-4db0-bacf-aac0a46afac2

Screenshot 2023-09-21 at 12 26 46

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17377 #17378 

iOS             |  Android
:-------------------------:|:-------------------------:
image  |  image

Fixes an issue that happened when a user replied to another user in community channel, The activity logs component only rendered a single image (If they were multiple in the reply, Only one would show) and didn't show the text in the reply if it was with an image

Presumably, Might need a design review since it's an extension of the previoulsy implemented component
status: ready

### CODE REVIEW

File: src/quo2/components/notifications/activity_logs_photos/view.cljs [hunk 1]
```diff
@@ -1,14 +1,24 @@
 (ns quo2.components.notifications.activity-logs-photos.view
   (:require [react-native.core :as rn]
+            [quo2.components.markdown.text :as quo2.text]
```
Comment (smohamedjavid) [inline src/quo2/components/notifications/activity_logs_photos/view.cljs]: We can use it as' text' since we don't have to impose quo2 again in the alias.

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs [hunk 2]
```diff
@@ -54,11 +61,11 @@
 (defn view
   [{:keys [notification set-swipeable-height customization-color] :as props}]
   (let [{:keys [author chat-name community-id chat-id
-                message read timestamp]} notification
-        community-chat?                  (not (string/blank? community-id))
-        community                        (rf/sub [:communities/community community-id])
-        community-name                   (:name community)
-        community-image                  (get-in community [:images :thumbnail :uri])]
+                message read timestamp albumMessages]} notification
```
Comment (smohamedjavid) [inline src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: It's good that we rename the `albumMessages` key to `album-messages` (kebab case) when we rename the rest of the notification keys.
https://github.com/status-im/status-mobile/blob/a99ae74da7373328fc8378bbbc9eec2ac0a6e94e/src/status_im/data_store/activities.cljs#L55-L68

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs [hunk 3]
```diff
@@ -14,16 +14,23 @@
...
+    (let [images           (or albumMessages message)
+          image-urls       (if albumMessages
+                             (mapv #(get % :image) images)
+                             [(get-in message [:content :image])])
+          image-local-urls (mapv (fn [url]
+                                   {:uri (url/replace-port url (rf/sub [:mediaserver/port]))})
+                                 image-urls)
+          photos           (when image-local-urls image-local-urls)]
+      [quo/activity-logs-photos
+       {:photos photos
```
Comment (smohamedjavid) [inline src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: I believe we can pass `image-local-urls` directly here. WYDT?

File: src/quo2/components/notifications/activity_logs_photos/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/quo2/components/notifications/activity_logs_photos/view.cljs]: Okay

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: Yup

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs [hunk 4]
```diff
@@ -14,16 +14,22 @@
...
                                  (get-in message [:content :text])]
 
     constants/content-type-image
-    (let [image           (get-in message [:content :image])
-          image-local-url (url/replace-port image (rf/sub [:mediaserver/port]))
-          photos          (when image-local-url [{:uri image-local-url}])]
-      [quo/activity-logs-photos {:photos photos}])
+    (let [images           (or album-messages message)
+          image-urls       (if album-messages
+                             (mapv #(get % :image) images)
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: You can use `(map :image images)`. `mapv` is also unnecessary.

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs [hunk 5]
```diff
@@ -14,16 +14,22 @@
...
+                             [(get-in message [:content :image])])
+          image-local-urls (mapv (fn [url]
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: Just `map` is sufficient. Any reason to use `mapv`?

File: src/quo2/components/notifications/activity_logs_photos/view.cljs [hunk 6]
```diff
@@ -1,14 +1,24 @@
...
-   (map-indexed
-    (fn [index photo]
-      ^{:key index}
-      [rn/image
-       {:source photo
-        :style  (style/photo index)}])
-    photos)])
+  [{:keys [photos message-text]}]
+  [:<>
+   (when (seq message-text)
```
Comment (ilmotta) [inline src/quo2/components/notifications/activity_logs_photos/view.cljs]: If `message-text` is a string, why we do check if it exists using `seq`? `string/blank?` is faster than `seq` in a microbenchmark I ran now. It's also a bit more correct for strings, because `(seq "   ")` will be truthy for strings containing only whitespace.

```clojure
(seq "    ")
;; => (" " " " " " " ")
```

File: src/quo2/components/notifications/activity_log/view.cljs [hunk 7]
```diff
@@ -75,22 +75,27 @@
...
-     [text/text
-      {:style               style/message-body
-       :accessibility-label :activity-message-body
-       :size                :paragraph-1
-       :number-of-lines     body-number-of-lines}
-      body]
-     body)])
+  (let [{:keys [photos text]} (when (vector? body) ;; When the prop is a reagent component with text, Get
+                                                   ;; that component's props.
+                                (second body))
```
Comment (ilmotta) [inline src/quo2/components/notifications/activity_log/view.cljs]: We can use the fact that `and` is an expression.

```clojure
(and (vector? body) (second body))
```

And we can replace the comment with a small private function, which I think is cleaner than a comment:

```clojure
(defn- hiccup-props
  [hiccup]
  (and (vector? hiccup) (second hiccup)))

;; If we want to be more correct, check if the second argument is actually a map.
(defn- hiccup-props
  [hiccup]
  (when (and (vector? hiccup)
             (map? (second hiccup)))
    (second hiccup)))

;; in activity-message
(let [{:keys [photos message-text]} (hiccup-props body)
      ...]
  ...)
```

By the way, I checked if Reagent gave us a simple function to extract props from hiccup, but it doesn't have that, `reagent.core/props` expects a component instance.

File: src/quo2/components/notifications/activity_log/view.cljs [hunk 8]
```diff
@@ -75,22 +75,27 @@
...
-      title])
-   (if (string? body)
-     [text/text
-      {:style               style/message-body
-       :accessibility-label :activity-message-body
-       :size                :paragraph-1
-       :number-of-lines     body-number-of-lines}
-      body]
-     body)])
+  (let [{:keys [photos text]} (when (vector? body) ;; When the prop is a reagent component with text, Get
```
Comment (ilmotta) [inline src/quo2/components/notifications/activity_log/view.cljs]: It should be `message-text` instead of `text`.

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs (hunk 5 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: I wanted to ensure that Clojure will go through the whole list, I had bad unexpected experiences with laziness :)
Okay, Using map

File: src/quo2/components/notifications/activity_log/view.cljs (hunk 8 above)
Comment (ibrkhalil) [reply src/quo2/components/notifications/activity_log/view.cljs]: Apologies, Missed renaming the var here to not shadow quo2/text.

**Comment by ibrkhalil** [comment]
@ilmotta @smohamedjavid 
Thank you so much for taking the time to do a review.
I did the comments, Kindly take another look.

**Review by smohamedjavid — APPROVED** [review]
LGTM 🚀 

Nice Work! 

P.S. I believe this file needs to be removed.

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs (hunk 5 above)
Comment (ilmotta) [reply src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: I understand your concern, but `map` should be fine for the majority of the cases, certainly for pure functions (which should be the vast majority of our hiccup building functions). I guess many Clojure devs would prefer if laziness wasn't the default, me for example :)

If we end up obsessing about realizing lazy sequences by transforming them into vectors then the code quality will suffer. We better embrace laziness to build hiccup and define pure functions as much as possible, don't pass atoms directly to functions if possible, use re-frame, etc.

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs [hunk 9]
```diff
@@ -14,16 +14,22 @@
...
-    (let [image           (get-in message [:content :image])
-          image-local-url (url/replace-port image (rf/sub [:mediaserver/port]))
-          photos          (when image-local-url [{:uri image-local-url}])]
-      [quo/activity-logs-photos {:photos photos}])
+    (let [images           (or album-messages message)
+          image-urls       (if album-messages
+                             (map :image images)
+                             [(get-in message [:content :image])])
+          image-local-urls (map (fn [url]
+                                  {:uri (url/replace-port url (rf/sub [:mediaserver/port]))})
```
Comment (ilmotta) [inline src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: @ibrkhalil, in general we shouldn't use subscriptions as if they are normal function calls. Re-frame even produces a warning when `re-frame.core/subscribe` is called in a non-reactive context in some occasions. I haven't checked if it produces a warning here.

It's also a good idea in general to move side-effects outside functions that produce lazy sequences, and our `rf/sub` utility in fact derefs a reaction.

I would say extract `(rf/sub [:mediaserver/port])` to a separate local binding, outside the `map` function.

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs [hunk 10]
```diff
@@ -106,4 +112,4 @@
 
                                                       :else
                                                       nil)
-                              :body                 (get-message-content message)}}]]]))
+                              :body                 (get-message-content message album-messages)}}]]]))
```
Comment (flexsurfer) [inline src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: pass (rf/sub [:mediaserver/port]) here as parameter

**Comment by churik** [comment]
@ibrkhalil 
please, move it to testing when all review commits are resolved, thanks!

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs (hunk 9 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: Done, Thank you

File: src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs (hunk 10 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs]: Done, Thank you

**Review by ilmotta — APPROVED** [review]
Code LGTM 🚀

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil, thank you for PR. No issues from my side. PR is ready to be merged
