### PR TITLE
fix: show network card with zero value on the sender side if the router does not return a route for that network

### LINKED ISSUE #20143: If route is found but doesn't use balance from a valid network, the network card is not shown
# Problem

Currently, if a route is found but doesn't use balance from a valid network, the network card is not shown on the sender side.

## Actual behavior

The network card is not shown on the sender side, therefore the user wouldn't be able to long-tap the card to lock an amount to that network.

## Expected behavior

If user has balance of the selected token greater than zero for that network, the network card is shown with 0 value, even if the route does not include that network.

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #20143

### Summary

This PR implements showing network cards with 0 value on the sender side if the account has balance for that token that network when the router does not return a route for that network.

##### User has ETH on Mainnet, Optimism and Arbitrum

https://github.com/status-im/status-mobile/assets/18485527/f7a7d734-757d-41b2-81d4-9242ec51b136

##### User has SNT only on Mainnet

https://github.com/status-im/status-mobile/assets/18485527/a25884c4-09d9-4f7f-b524-d7db3f2937ee

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Log in
- Go to wallet
- Select an account
- Tap on Send button
- Select an address
- Select a token that has balance in many networks
- Enter a valid amount
- If router does not return a route for that network, network should still be shown on the sender side with 0 value

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/events.cljs [hunk 1]
```diff
@@ -42,8 +43,18 @@
          [:dispatch [:wallet/show-account-created-toast address]]]}))
 
 (rf/reg-event-fx :wallet/switch-current-viewing-account
- (fn [{:keys [db]} [address]]
-   {:db (assoc-in db [:wallet :current-viewing-account-address] address)}))
+ (fn [{:keys [db]} [{:keys [address network-details update-balance?]}]]
+   (let [current-token (-> db :wallet :ui :send :token)
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/events.cljs]: hmm I would like to push back against this change. We're taking a very simple and effective method and coupling it with some send related logic. 
Can we handle this some other way? - maybe just a separate event being fired for this particular action? 🤔 

cc @smohamedjavid

**Comment by ulisesmac** [comment]
Hey @briansztamfater 
In your example
**User has ETH on Mainnet, Optimism and Arbitrum**
I have a two questions:
1. Why do we show Mainnet and Optimism as pressable cards if they show `0`? and what means that after pressing them they become disabled?

2. Why when pressing Optimism on the sender side it enables Optimism on the recipient side if on the sender it becomes disabled?

File: src/status_im/contexts/wallet/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/events.cljs]: @J-Son89  @briansztamfater 

According to the comment in this event:
```
;; When switching accounts, if there is a selected token we need to update
;; it to reflect balances of the new account
```

Seems more as a task for a subscription, the subscription that extracts the token from
 `[:wallet :ui :send :token]`
could also receive the current-viewing-account and add the extra data needed.

wdyt?

File: src/status_im/contexts/wallet/send/utils.cljs [hunk 2]
```diff
@@ -67,10 +67,24 @@
...
+  [{:keys [balances-per-chain disabled-chain-ids only-with-balance?]}]
   (let [disabled-set (set disabled-chain-ids)]
     (->> balances-per-chain
+         (filter (fn [[_ {:keys [raw-balance]}]]
+                   (or (not only-with-balance?)
+                       (and only-with-balance?
+                            (and (money/bignumber? raw-balance)
+                                 (money/greater-than raw-balance (money/bignumber "0")))))))
          (filter (fn [[_ {:keys [chain-id]}]]
                    (not (contains? disabled-set chain-id))))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/utils.cljs]: We can only use one `and` in the filter condition:
```clojure
(filter (fn [[_ {:keys [raw-balance]}]]
            (or (not only-with-balance?)
                (and only-with-balance?
                     (money/bignumber? raw-balance)
                     (money/greater-than raw-balance (money/bignumber "0"))))))
```

Have you consider extending the filter below instead of creating a new one? I think performing two filters is more expensive :thinking:

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -338,32 +344,42 @@
...
-                                                         (filter
-                                                          #(not= bridge-to-chain-id %)
-                                                          token-available-networks-for-suggested-routes)
-                                                         token-available-networks-for-suggested-routes)
+                                  {:valid-networks
+                                   (if (= transaction-type :tx/bridge)
+                                     (filter
+                                      #(not= bridge-to-chain-id %)
+                                      sender-token-available-networks-for-suggested-routes)
+                                     sender-token-available-networks-for-suggested-routes)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs]: Small comment, consider using `remove` instead of `filter ` + `not` + `predicate`.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 4]
```diff
@@ -338,32 +344,42 @@
...
-                                                       (filter
-                                                        #(= bridge-to-chain-id %)
-                                                        token-available-networks-for-suggested-routes)
-                                                       token-available-networks-for-suggested-routes)
+                                    {:valid-networks
+                                     (if (= transaction-type :tx/bridge)
+                                       (filter
+                                        #(= bridge-to-chain-id %)
+                                        receiver-token-available-networks-for-suggested-routes)
+                                       receiver-token-available-networks-for-suggested-routes)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs]: This function/event looks very complex, it'd be great if we solve this problem in smaller functions with meaningful names, I know this is out of scope of this PR, but IMO this function needs to be refactored to be easier to understand and maintain.

**Comment by briansztamfater** [comment]
> Hey @briansztamfater In your example **User has ETH on Mainnet, Optimism and Arbitrum** I have a two questions:
> 
> 1. Why do we show Mainnet and Optimism as pressable cards if they show `0`? and what means that after pressing them they become disabled?
> 2. Why when pressing Optimism on the sender side it enables Optimism on the recipient side if on the sender it becomes disabled?

Hey @ulisesmac, let me answer those questions!

1. After implementing #16974, we will have the ability to long press the cards to lock an specific amount. If user has balance for that network, even if the routes does not include that network, we need to show it with 0 value so user could long press it to lock an amount and re-calculate routes.
2. Currently, when disabling a network on the sender side, we show 0 value on the receiver side, as shown for example [in this Figma design](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=2436-520431&t=b94H5Js0xUt561VK-4). We are currently in talks with @xAlisher reviewing the expected behavior for the routes UI, so this may or may not change. We can raise a new PR with the changes if expected behavior changes.

File: src/status_im/contexts/wallet/send/events.cljs (hunk 4 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/events.cljs]: Agree, we should even write tests for these events. Will file an issue for it.

File: src/status_im/contexts/wallet/send/utils.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/utils.cljs]: Yeah, I've considered that option, thought that it was more "readable" even if it is a bit less performant, but I have no strong opinion on this tbh, I will change it to have only one filter :)

Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/utils.cljs]: We can create two functions to make it more readable, something like

```clojure
(filter (fn [my-data]
          (and (check-conditions-1 my-data)
               (check-conditions-2 my-data)))
```

If you take this approach, just make sure to provide good names :)

File: src/status_im/contexts/wallet/events.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/events.cljs]: I think it makes sense, will try to refactor this and let you know!

**Comment by briansztamfater** [comment]
> > Hey @briansztamfater In your example **User has ETH on Mainnet, Optimism and Arbitrum** I have a two questions:
> > 
> > 1. Why do we show Mainnet and Optimism as pressable cards if they show `0`? and what means that after pressing them they become disabled?
> > 2. Why when pressing Optimism on the sender side it enables Optimism on the recipient side if on the sender it becomes disabled?
> 
> Hey @ulisesmac, let me answer those questions!
> 
> 1. After implementing [Implement Send page > Long tap to edit amount send through an specific network #16974](https://github.com/status-im/status-mobile/issues/16974), we will have the ability to long press the cards to lock an specific amount. If user has balance for that network, even if the routes does not include that network, we need to show it with 0 value so user could long press it to lock an amount and re-calculate routes.
> 2. Currently, when disabling a network on the sender side, we show 0 value on the receiver side, as shown for example [in this Figma design](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=2436-520431&t=b94H5Js0xUt561VK-4). We are currently in talks with @xAlisher reviewing the expected behavior for the routes UI, so this may or may not change. We can raise a new PR with the changes if expected behavior changes.

FYI, regarding question 2, we talked today with Alisher and cards in the receiver side with 0 won't be shown anymore, but will raise a separate PR with all the discussed changes once they are 100% defined and represented in designs 👍 .

File: src/status_im/contexts/wallet/send/events.cljs (hunk 4 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/events.cljs]: Created #20162

**Comment by briansztamfater** [comment]
@J-Son89 @ulisesmac just addressed the comments, can you please re-check?

File: src/status_im/contexts/wallet/events.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/events.cljs]: I removed this logic, send the updated token from subscription to `:wallet/get-suggested-routes` event

**Review by ulisesmac — APPROVED** [review]
Thanks for the explanation and for adressing the comments @briansztamfater 

Looks good

File: src/status_im/contexts/wallet/send/utils.cljs [hunk 5]
```diff
@@ -67,12 +67,25 @@
...
+  (reduce
+   (fn [acc chain-id]
+     (let [route-value (get network-values chain-id)]
+       (assoc acc chain-id (or route-value (money/bignumber "0")))))
+   {}
+   all-possible-chain-ids))
+
 (defn token-available-networks-for-suggested-routes
-  [{:keys [balances-per-chain disabled-chain-ids]}]
+  [{:keys [balances-per-chain disabled-chain-ids only-with-balance?]}]
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/utils.cljs:80]: I would say `only-with-balance` is not very clear. What is the purpose of this variable ? 🤔

File: src/status_im/contexts/wallet/send/events.cljs [hunk 6]
```diff
@@ -322,9 +328,9 @@
                          (when (empty? receiver-network-values) :receiver-network-values)))})))
 
 (rf/reg-event-fx :wallet/get-suggested-routes
- (fn [{:keys [db now]} [{:keys [amount]}]]
+ (fn [{:keys [db now]} [{:keys [amount updated-token]}]]
    (let [wallet-address (get-in db [:wallet :current-viewing-account-address])
-         token (get-in db [:wallet :ui :send :token])
+         token (or updated-token (get-in db [:wallet :ui :send :token]))
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/events.cljs:333]: do we need both `token` and `updated-token`? why not just one of these? 🤔

**Review by J-Son89 — APPROVED** [review]

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater !

Thanks for your PR.
I've tested and cards with zero looks good on both platforms.

Failed e2e are not related, you can merge your PR.
