### PR TITLE
[#16156] Top bar flashing

### LINKED ISSUE #16156: Top bar flashes on iOS after quickly scrolling to the top in the chat
Introduced by https://github.com/status-im/status-mobile/pull/15204
cc: @alwx 

### Steps to reproduce:
1. Open a chat with a significant amount of messages.
2. Perform a quick scroll to the top by swiping upwards rapidly.

### Actual result:
The top bar of the screen flashes briefly during the quick scroll action

https://github.com/status-im/status-mobile/assets/52490791/268fcce1-90d2-4e5a-be8a-c6a4f13a16e9

### Expected result:
The top bar remains stable and does not flash during the quick scroll action

### Devices:
- iPhone 11 Pro max, IOS 16

### PR DESCRIPTION
**Pull request by rasom**
fix #16156

status: ready

The issue is caused by `chats/all-loaded?` sub being updated faster then the list of messages, thus Top Bar behaves like all messages are loaded (technically they are, but in app-db, not in the view) and animation is started. In order to prevent this we need to avoid reaction on `all-loaded?` change.

### CODE REVIEW

**Comment by rasom** [comment]
So it actually fixes the issue but I'm wondering whether it should be written differently, for instance by just adding some `atom` with "delay" in view directly. Although this approach with app-db looks simpler to me.

**Comment by flexsurfer** [comment]
idk looks like a hacky workaround, probably worth spending some time on the proper fix

**Comment by rasom** [comment]
@flexsurfer thanks for the comment, any suggestions what would be a proper fix?

**Comment by flexsurfer** [comment]
> @flexsurfer thanks for the comment, any suggestions what would be a proper fix?

yeah, a proper fix would be a fix without a hacky workaround :) sorry, that's the only answer I have. In this fix, it confuses me that we duplicate the variable, so we have to manage this variable, but its the same variable but with delayed value, so probably we need to find how to fix `technically they are, but in app-db, not in the view` i don't know, to answer i need to investigate this issue

**Comment by rasom** [comment]
imo the fix is going to be similar to this PR (unless we will somehow make this animation to react on something different from `scroll-y`, which is unlikely). The question is whether it is fine to have it in the `app-db`, or we want to move it to some local state. That local state thing might end up introducing more bugs (mostly because that's state per chat and not so local in reality). I see three option atm
- this fix
- similar fix but directly in view (some local state)
- disabling animation
The first option is fine for me, but if there no any reasonable arguments why it won't work or what problems it might introduce let's proceed to testing.

**Comment by rasom** [comment]
ok i'll try another one

**Comment by rasom** [comment]
@flexsurfer another attempt, does it look better?

**Comment by flexsurfer** [comment]
> @flexsurfer another attempt, does it look better?

yes, now it looks like a hack, not like a hacky workaround :)

**Comment by rasom** [comment]
@flexsurfer definitely an improvement. Hack, hook, who cares.

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 1]
```diff
@@ -257,11 +258,14 @@
...
 (defn messages-list-content
-  [{:keys [chat insets scroll-y cover-bg-color keyboard-shown?]}]
+  [{:keys [chat insets scroll-y cover-bg-color keyboard-shown? shared-all-loaded?]}]
   (let [context     (rf/sub [:chats/current-chat-message-list-view-context])
         messages    (rf/sub [:chats/raw-chat-messages-stream (:chat-id chat)])
         recording?  (rf/sub [:chats/recording?])
         all-loaded? (rf/sub [:chats/all-loaded? (:chat-id chat)])]
+    ;; NOTE(rasom): Top bar needs to react on `all-loaded?` only after messages
+    ;; rendering, otherwise animation flickers
+    (react/effect! #(reset! shared-all-loaded? all-loaded?))
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: `rn/use-effect` should be used instead

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 2]
```diff
@@ -326,14 +331,17 @@
       :keyboard-vertical-offset (- (:bottom insets))}
 
      (when header-comp
-       [header-comp {:scroll-y scroll-y}])
+       [header-comp {:scroll-y scroll-y
+                     :all-loaded? all-loaded?}])
 
-     [messages-list-content
+     [:f>
+      messages-list-content
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: could please add `f` to  `f-messages-list-content`

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 3]
```diff
@@ -326,14 +331,17 @@
...
       {:chat            chat
        :insets          insets
        :scroll-y        scroll-y
        :cover-bg-color  cover-bg-color
-       :keyboard-shown? keyboard-shown}]
+       :keyboard-shown? keyboard-shown
+       :shared-all-loaded?     all-loaded?}]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: formatting

File: src/status_im2/contexts/chat/messages/navigation/view.cljs [hunk 4]
```diff
@@ -14,11 +14,12 @@
             [status-im2.common.home.actions.view :as actions]))
 
 (defn f-navigation-view
-  [{:keys [scroll-y]}]
+  [{:keys [scroll-y all-loaded?]}]
   (let [{:keys [group-chat chat-id chat-name emoji
                 chat-type]
          :as   chat}             (rf/sub [:chats/current-chat-chat-view])
-        all-loaded?              (rf/sub [:chats/all-loaded? chat-id])
+        ;;all-loaded?              (rf/sub [:chats/all-loaded? chat-id])
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/navigation/view.cljs]: leftover

**Review by flexsurfer — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by rasom** [comment]
ok something went wrong

**Review by ajayesivan — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@rasom Thank you for your fixes. PR is tested and can be merged
