### PR TITLE
[#3958] implemented transactions queue

### LINKED ISSUE #3958: Convert tokens fails in Bancor DApp because only 1 transaction out of 2 is signed in Status
### Description

*Type*: Bug

*Summary*: `Convert tokens` fails in Bancor DApp because it creates 2 transactions but only 1 can be signed by Status. 

Tried 10 times to convert SNT to BNT and other tokens, all attempts failed. In the same time if buy same token for ETH then it works fine (probably, because only one signing request is created when purchasing with ETH)

geth.log if search by `request` (2 signing requests created, only 1 of them is completed):
```
t=2018-04-22T14:20:35+0000 lvl=info msg="signing request is created" package=status-go/sign.PendingRequests   ID=c46b3c4a-aa61-4080-a705-9a88d4c43eb9
t=2018-04-22T14:20:35+0000 lvl=info msg="signing request is created" package=status-go/sign.PendingRequests   ID=67ad4b67-489c-4277-9c40-232ac98a8061
t=2018-04-22T14:20:42+0000 lvl=info msg="complete sign request"  package=status-go/sign.PendingRequests   id=67ad4b67-489c-4277-9c40-232ac98a8061
t=2018-04-22T14:20:43+0000 lvl=info msg="completed sign request " package=status-go/sign.PendingRequests      id=67ad4b67-489c-4277-9c40-232ac98a8061   response="[88 236 132 251 17 172 249 75 129 101 190 135 112 211 171 191 51 166 228 78 28 206 244 68 236 147 50 12 205 187 86 195]" err=nil


```

#### Expected behavior
Both transaction requests can be signed, so user can convert tokens in Bancor DApp

#### Actual behavior
"Oh no" error is shown in the DApp, user lost some ETH on 1 failed transaction, second transaction was never done

### Reproduction
Prerequisite: you need to have about 30 SNT and 0.01 ETH in your Wallet in Status app

- Open Status
- In Home tab tap on "+" and select Open DApp
- Tap on Bancor, tap Open
- When Bancor DApp is loaded: on Tokens tab tap on BNT token
- On Token Summary page tap on Buy button
- select Localhost and tap Next button
- In "Pay with" field tap on dropdown with ETH. As a result, there is a list of tokens shown, select SNT there. As a result, there is SNT instead of ETH next to PAY WITH field
- In Enter Amount type "30" (so 30 SNT)
- Receive field will be automatically filled in with BNT amount that can be purchased
- Tap Next button
- "You are almost there" screen is shown with SNT -> BNT amount and Transaction fee. In my case, fee was about 0.005 ETH
- tap Proceed button
- Send Transaction screen from Status Wallet will be shown. Tap on Sign Transaction, enter password and tap Sign Transaction. As a result, Transaction sent screen is shown. Tap Got it
- Proceed button becomes inactive and there is spinning indicator shown for quite some time. 
- Check if it ends successfully (there is confirmation in Bancor Dapp shown, Transaction id shown that you can watch, eventually BNT sent to your account). In my case it wasn't: Oh, no Error is shown

### Logs
Geth log: [geth (10).log.zip](https://github.com/status-im/status-react/files/1935720/geth.10.log.zip)
TestFairy session (start from 4:11) https://app.testfairy.com/projects/4803622-status/builds/8149726/sessions/31/?accessToken=4H5yLZvP7OEKASMBtpUm6Y2CLWc
 

### Additional Information
* Status version: nightly build Apr 22
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #3958

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 1]
```diff
@@ -102,67 +102,81 @@
...
-                                     :on-completed on-transactions-completed}}))))
-
-      (= method constants/web3-personal-sign)
-
-      (let [{:keys [data]} args]
-        {:db (-> db
-                 (assoc-in [:wallet :transactions-unsigned id] {:data data :id id})
-                 (assoc-in [:wallet :send-transaction] {:id id :method method}))
-         :dispatch [:navigate-to-modal :wallet-sign-message-modal]}))))
+  (fn [{:keys [db now]} _]
```
Comment (cammellos) [inline src/status_im/ui/screens/wallet/send/events.cljs]: This function seems to be ripe for being extracted and tested it seems :)

**Review by cammellos — APPROVED** [review]

**Comment by annadanchenko** [comment]
#3958 is fixed (can convert SNT -> BNT and SNT -> BAT). Also checked that can sell and purchase tokens for ETH on mainnet
