### PR TITLE
[#15578] fix code snippet

### LINKED ISSUE #15578: Fix & refactor code snippet component
# Bug Report

The code snippet's preview screen is crashing, we need this component to solve #15004 
Also it'd be good to split the code into different view and style files.

## Problem 
[comment]: # (A problem description)

When the preview screen is shown, it prints the following exception:

```
 Invariant Violation: View config getter callback for component `code` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in code (created by SyntaxHighlighter)
    in pre (created by SyntaxHighlighter)
    in SyntaxHighlighter (created by quo2.components.code.snippet.snippet)
    in quo2.components.code.snippet.snippet (created by status_im2.contexts.quo_preview.code.snippet.cool_preview)
    in RCTView (at View.js:34)
    in View (created by status_im2.contexts.quo_preview.code.snippet.cool_preview)
    in RCTView (at View.js:34)
    in View (created by status_im2.contexts.quo_preview.code.snippet.cool_preview)
    in TouchableWithoutFeedback (created by status_im2.contexts.quo_preview.code.snippet.cool_preview)
    in status_im2.contexts.quo_preview.code.snippet.cool_preview (created by react_native.flat_list.flat_list)
    in RCTView (at View.js:34)
    in View (at VirtualizedList.js:980)
    in VirtualizedCellWrapper (at VirtualizedList.js:977)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at VirtualizedList.js:1329)
    in VirtualizedList (at FlatList.js:624)
    in FlatList (created by react_native.flat_list.flat_list)
    in react_native.flat_list.flat_list (created by status_im2.contexts.quo_preview.code.snippet.preview_code_snippet)
    in RCTView (at View.js:34)
    in View (created by status_im2.contexts.quo_preview.code.snippet.preview_code_snippet)
    in status_im2.contexts.quo_preview.code.snippet.preview_code_snippet (created by reagent181)
    in RCTView (at View.js:34)
    in View (created by reagent181)
    in reagent181 (created by Context.Consumer)
    in react_native.safe_area.consumer (created by reagent160)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:50)
    in SafeAreaProvider (created by reagent160)
    in reagent160 (at gestureHandlerRootHOC.tsx:13)
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:23)
    in GestureHandlerRootView (at gestureHandlerRootHOC.tsx:12)
    in gestureHandlerRootHOC(reagent160) (created by WrappedComponent)
    in WrappedComponent (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39), js engine: hermes

```

#### Expected behavior

Show the component as [designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=5626-159428&t=avnAO7hTidrTl6KV-4)

#### Actual behavior

Screen crashes

### Reproduction

1) Open Status
2) Navigate to Quo2.0 Preview
3) Code -> Snippet

### Additional Information

- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #15578

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

This component was making the preview screen (and any other screen where used) crash, this PR:
1. Fix that error
2. Fix some wrong styles according to [designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=5626-159428&t=zTo0OaxEPCGIWE4u-0)
3. Refactors the code a little + split the code into `view` and `style` files.

I'll add comments to explain important changes.

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to Quo2 Components -> Code -> Snippet

status: ready

### CODE REVIEW

File: src/quo2/components/code/code/style.cljs [hunk 1]
```diff
@@ -0,0 +1,84 @@
+(ns quo2.components.code.code.style
+  (:require [quo2.foundations.colors :as colors]))
+
+;; Example themes:
+;; https://github.com/react-syntax-highlighter/react-syntax-highlighter/tree/master/src/styles/hljs
+(defn theme
```
Comment (ulisesmac) [inline src/quo2/components/code/code/style.cljs:6]: `theme` was a map, now it's a function (since it uses `color-theme-colors`) and I used `case` because we don't need to compute all colors to only extract one key (as we'd do if it were a map).

File: src/quo2/components/code/snippet.cljs [hunk 2]
```diff
@@ -1,175 +1,110 @@
...
-           :line-number  {:color colors/neutral-40}}
-   :dark  {:hljs-comment {:color colors/neutral-60}
-           :hljs-title   {:color (colors/custom-color :blue 60)}
-           :hljs-keyword {:color (colors/custom-color :green 60)}
-           :hljs-string  {:color (colors/custom-color :turquoise 60)}
-           :hljs-literal {:color (colors/custom-color :turquoise 60)}
-           :hljs-number  {:color (colors/custom-color :turquoise 60)}
-           :line-number  {:color colors/neutral-40}}})
-
-(defn- text-style
```
Comment (ulisesmac) [inline src/quo2/components/code/snippet.cljs:33]: This function is now in the `style` ns, and it was simplified a lot

File: src/quo2/components/code/snippet.cljs [hunk 3]
```diff
@@ -1,175 +1,110 @@
...
+    [text/text
+     {:style  (style/text-style ["line-number"])
+      :weight :code
+      :size   :paragraph-2}
+     line-number]]
+   children])
+
 (defn- code-block
   [{:keys [rows line-number-width]}]
-  [into [:<>]
```
Comment (ulisesmac) [inline src/quo2/components/code/snippet.cljs:62]: This `into` was being called using `[]` instead of `()`

File: src/quo2/components/code/snippet.cljs [hunk 4]
```diff
@@ -1,175 +1,110 @@
...
-            border-color          (colors/theme-colors
-                                   colors/neutral-20
-                                   colors/neutral-80)
-            rows                  (bean/->clj rows)
-            font-scale            (:font-scale (rn/use-window-dimensions))
-            max-rows              (or max-lines (count rows)) ;; Cut down on rows to process.
-            max-line-digits       (-> rows count (min max-rows) str count)
-            ;; ~ 9 is char width, 18 is width used in Figma.
-            line-number-width     (* font-scale (max 18 (* 9 max-line-digits)))
-            max-text-height       (some-> max-lines
```
Comment (ulisesmac) [inline src/quo2/components/code/snippet.cljs:98]: We're no longer using `max-text-height` or any other height related calculation, this was creating a bug where if you said you want to show `n` lines from a fragment of code, sometimes it was showing less than `n` depending on the screen size. Now it's fixed

The problem was due to this height calculation, this height is supposing the  height of a drawn line is constant, but on smaller screens, a line could be drawn using a bigger size. e.g.

The folowing code:
```clojure
#_line-1 (let [a nil]
#_line-2  [button/button {:override-background-color (style/button-background-color)} :main-icons/copy]
#_line-3  nil)
```
Has 3 lines, this code will calculate a specific height, but if the phone screen is not wider enough to show the second line in one single drawn line, the view won't be shown as expected. Depending on screen's width, it cold be shown as:
```clojure
#_line-1 (let [a nil]
#_line-2  [button/button {:override-background-color (style/button-
#_line-2 background-color)} :main-icons/copy]
#_line-3  nil)
```
or
```clojure
#_line-1 (let [a nil]
#_line-2  [button/button {:override-background
#_line-2 -color (style/button- background-color
#_line-2 )} :main-icons/copy]
#_line-3  nil)
```

causing the user sees less lines than requested

File: src/quo2/components/code/snippet.cljs [hunk 5]
```diff
@@ -1,175 +1,110 @@
...
-                                          (* font-scale 18)) ;; 18 is font's line height.
-            truncated?            (and max-text-height (< max-text-height @text-height))
-            maybe-mask-wrapper    (if truncated?
-                                    [masked-view/masked-view
```
Comment (ulisesmac) [inline src/quo2/components/code/snippet.cljs:102]: It was using a masked view over a linear-gradient, it was a good idea, the puprose of this was to add this gradient at the bottom of the component when the fragment is truncated:
image

The problem was that mask was being applied to the full code view, and according to designs, that gradient is only 47 units height. The gradient was being applied from 75% of the view  to 100%, it looked ok on small fragments, but on larger ones it started to look different than designs.

I removed the use of a mask and just added a linear gradient drawn over the bottom of the fragment

File: src/quo2/components/code/snippet.cljs [hunk 6]
```diff
@@ -1,175 +1,110 @@
...
   [{:keys [language max-lines on-copy-press]} children]
   [highlighter/highlighter
    {:language          language
-    :renderer          (wrap-renderer-fn
-                        native-renderer
-                        {:max-lines     max-lines
-                         :on-copy-press #(when on-copy-press
-                                           (on-copy-press children))})
-    ;; Default props to adapt Highlighter for react-native.
-    ;;:CodeTag           react-native/View
```
Comment (ulisesmac) [inline src/quo2/components/code/snippet.cljs:170]: During a cleanup this code was commented, it was causing the screen to crash. Since these properties are mandatory for react native, I added them directly to its wrapper, so we don't need to specify them on each future use

File: src/quo2/components/code/snippet.cljs [hunk 7]
```diff
@@ -1,175 +1,110 @@
...
-    ;;:PreTag            react-native/View
+    :renderer          (fn [^js/Object props]
+                         (reagent/as-element
+                          [:f> native-renderer
+                           {:rows          (-> props .-rows bean/->clj)
+                            :on-copy-press #(when on-copy-press (on-copy-press children))
+                            :max-lines     max-lines}]))
     :show-line-numbers false
-    :style             #js {}
```
Comment (ulisesmac) [inline src/quo2/components/code/snippet.cljs:173]: We don't need it to be #js objects, since we'are using `adapt-react-class`

File: src/status_im2/contexts/quo_preview/code/snippet.cljs [hunk 8]
```diff
@@ -26,6 +26,23 @@
         s.logger.Error(\"failed to set Server.port\", zap.Error(err))
         return
     }
+
```
Comment (ulisesmac) [inline src/status_im2/contexts/quo_preview/code/snippet.cljs:29]: Just added more lines to the example, they are the same as those shown in designs

File: src/quo2/components/code/code/style.cljs [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+    :hljs-number  (colors/custom-color-by-theme :turquoise 50 60)
+    :line-number  colors/neutral-40
+    nil))
+
+(defn text-style
+  [class-names]
+  (let [text-color (->> class-names
+                        (map keyword)
+                        (some #(when-let [text-color (theme %)]
+                                 text-color)))]
```
Comment (ibrkhalil) [inline src/quo2/components/code/code/style.cljs]: Just a suggestion
We're trying to move away from using anonymous function literal `#` and use `fn` for better readability.

File: src/quo2/components/code/code/style.cljs [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+   :border-width     1
+   :border-radius    16})
+
+(def gradient-container
+  {:position :absolute
+   :bottom   0
+   :left     0
+   :right    0
+   :z-index  1})
+(def gradient {:height 48})
```
Comment (ibrkhalil) [inline src/quo2/components/code/code/style.cljs]: A line seperating `(def gradient {:height 48})` would be nice.

File: src/quo2/components/code/code/style.cljs [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+  {:position         :absolute
+   :bottom           0
+   :top              0
+   :left             (+ line-number-width 7 7)
+   :width            1
+   :z-index          2
+   :background-color (border-color)})
+
+(def line {:flex-direction :row})
+(defn line-number
```
Comment (ibrkhalil) [inline src/quo2/components/code/code/style.cljs]: Need extra line

File: src/quo2/components/code/snippet.cljs [hunk 12]
```diff
@@ -1,175 +1,110 @@
...
-          {:style {:position :absolute
-                   :bottom   8
-                   :right    8}}
-          [button/button
-           {:icon     true
-            :type     :grey
-            :size     24
-            :on-press on-copy-press}
-           :main-icons/copy]]]))))
+(defn- calc-line-numer-width
```
Comment (J-Son89) [inline src/quo2/components/code/snippet.cljs]: you have a typo here: numer -> number

File: src/quo2/components/code/code/style.cljs [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+  {:margin-right 20 ; 8+12 margin
+   :width        width})
+
+(def copy-button
+  {:position :absolute
+   :bottom   8
+   :right    8
+   :z-index  1})
+
+(defn gradient-color [] (colors/theme-colors colors/white "#1b273d"))
```
Comment (J-Son89) [inline src/quo2/components/code/code/style.cljs]: should the color be in the colors file? 🤔

Comment (ulisesmac) [reply src/quo2/components/code/code/style.cljs]: I've just checked it and it's neutral-80 :facepalm:  I'll fix it!

**Review by ibrkhalil — APPROVED** [review]
Non blocking comments

File: src/quo2/components/code/code/style.cljs (hunk 9 above)
Comment (ulisesmac) [reply src/quo2/components/code/code/style.cljs]: Oh wow, why are we doing that?

When multiple parameters are receivied I'd say it's better to use `fn`, but I wouldn't remove the entire use of  `#()`. :sweat_smile: 

I solved it for this PR.

Comment (ibrkhalil) [reply src/quo2/components/code/code/style.cljs]: To be able to add a name for our parameters
It was usually because of [this](https://github.com/bbatsov/clojure-style-guide#no-multiple-forms-in-function-literals) but I think we I tried to tell you about it just in a generative way

Comment (ulisesmac) [reply src/quo2/components/code/code/style.cljs]: I already looked at the link you sent, and it doesn't apply to this segment of code since it mentions when we have multiple forms:
do:
```clojure
(fn [x]
  (form-1 x)
  (form-2 x)
  (form-3 x))
```
instead of:
```clojure
#(do
   (form-1 %)
   (form-2 %)
   (form-3 %))
```

But my code only had one form, `when-let`:

```clojure
#(when-let [var (a-fn %)]
   var) 
```

Also, it was receiving only one parameter, I think it was straightforward.

Anyway, thanks for providing the link :)

**Review by OmarBasem — APPROVED** [review]
LGTM!
