### PR TITLE
Fix statusbar color on dark screens

### LINKED ISSUE #17636: Status system top bar wrong colour issues
# Bug Report
Below are the cases when status top bar appears to have the wrong color

## Problem 

- [ ] 1) **IOS:** The system bar on "Jump To" is black: 

Monosnap 2023-10-13 18-00-33

- [ ] 2) Navigation from activity center to jump to leads to black status-bar color

https://github.com/status-im/status-mobile/assets/4557972/e0be86a7-1d57-4fe4-aefc-9e1b6736e3f1

- [ ] 3) Wrong status top bar color when opening AC/Share screen after onboarding (Android 12, Samsung Galaxy A52)

**Preconditions:** light mode is on on the device

**Steps:** 

1. Proceed with onboarding
2. Open Share/AC screen after onboarding
3. Close the screen
4. Pay attention at status top bar

**Actual result:** status top bar color is wrong. After app reopening issue is not reproducible. 

https://github.com/status-im/status-mobile/assets/97245802/9347eb8f-cc4a-4526-8ecd-e9cc15208bdd

- [ ] 4) Wrong status top bar color after switching device theme (Android 12, Samsung Galaxy A52)

Might be global problem with theme changing. 

**Steps:** 

1. Switch device theme while being logged in the account
2. Pay attention at status top bar

**Actual result:** status top bar color is wrong. Status top bar color becomes correct after app re-opening. 

https://github.com/status-im/status-mobile/assets/97245802/176310d6-2ad9-4dc4-8085-634909ddd58a

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17636
CleanShot 2024-02-11 at 18 51 53
CleanShot 2024-02-11 at 18 55 49

### Summary

Fixes bad system bar color on different views, By removing the usage of wix/react-native-navigation to control the status bar and controlling it directly using the react-native status bar module.

status: ready

### CODE REVIEW

File: src/quo/theme.cljs [hunk 1]
```diff
@@ -59,3 +59,40 @@
   [component]
   (fn [& args]
     (into [:f> f-with-theme component] args)))
+
+(def previous-screen (atom nil))
```
Comment (ibrkhalil) [inline src/quo/theme.cljs]: Needed because when a view is a modal and is minimized, We go back to the shell view (Making statusbar black) and within milliseconds we go to the view we wanted to visit
(Happend only on appearence and syncing settings)

File: src/quo/theme.cljs [hunk 2]
```diff
@@ -59,3 +59,40 @@
...
+
+(def ^:private dark-screens
+  #{:shell :share-shell :activity-center :camera-screen :settings :settings-password :settings-syncing
+    :edit-profile})
+
+(def ^:private ignored-screens
```
Comment (ibrkhalil) [inline src/quo/theme.cljs]: Ignore changing the statusbar on these screens when navigating to prevent changing twice.

File: src/quo/theme.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/quo/theme.cljs]: We need to store previous screen becuase the transition when closing the settings modal triggers the statusbar color change twice.

File: src/status_im/contexts/syncing/syncing_devices_list/view.cljs [hunk 3]
```diff
@@ -18,12 +19,15 @@
...
                                                    other-devices)]
+    (quo.theme/handle-status-bar-dark-screen)
     [rn/view {:style style/container-main}
      [quo/page-nav
       {:type       :no-title
        :background :blur
        :icon-name  :i/arrow-left
-       :on-press   #(rf/dispatch [:navigate-back])}]
+       :on-press   (fn []
+                     (reset! quo.theme/previous-screen nil)
```
Comment (ibrkhalil) [inline src/status_im/contexts/syncing/syncing_devices_list/view.cljs]: We need to clear previous screen when closing this view to prevent bad behavior on the currently open shell-stack screen.
It's not the best way to do it, And I'd appreciate any ideas.

File: src/quo/theme.cljs [hunk 4]
```diff
@@ -59,3 +59,42 @@
   [component]
   (fn [& args]
     (into [:f> f-with-theme component] args)))
+
+(def previous-screen (atom nil))
+
+(def ^:private change-statusbar-color-delay 150)
+
+(def ^:private dark-screens
```
Comment (Parveshdhull) [inline src/quo/theme.cljs]: Hi @ibrkhalil,
Thank you very much for looking into this issue and finding this cool solution. From the video, your shared solution looks promising.

1. We don't need to keep track of each screen which will require light status bar color, we can just manually call the function when needed.
- For theme, please add `rn/set-status-bar-style theme` to `profile.settings/switch-theme-fx`
- For manual changes we have an event `:change-shell-status-bar-style`, please add the corresponding effect and this `set-staus-bar-style` call their. (feel free to rename the event)
2. why `change-statusbar-color-delay 150`? I think there should not be a delay, but better to discuss with the design team.
3. `set-status-bar-style "light-content" true`. Why true? Please can you try with both `animated?` true and false, and see what's the difference and which one should we keep (discuss with the design team.

**Review by Parveshdhull — CHANGES_REQUESTED** [review]

File: src/quo/theme.cljs (hunk 4 above)
Comment (Parveshdhull) [reply src/quo/theme.cljs]: > We don't need to keep track of each screen

We are keeping track of dark theme screens by adding options in `status-im.navigation.screens` file. (For camera we have in `status-im.navigation.options` file for some reason).

Adding `handle-status-bar-screens` as effects inside screen don't look nice to me. I think it should be part of navigation itself.

Comment (Parveshdhull) [reply src/quo/theme.cljs]: I guess we probably need to keep track, as `navigtion.screens` options are probably not enough and little scattered.

How about, keep track of dark status bar screens but instead of adding `handle-status-bar-screens` as effect in every screen, we make this call.
1. Inside `profile.settings/switch-theme-fx` for theme changes
2. Inside `:set-view-id-fx` (this will cover all, navigation to screens, modal and navigation back)

Something like `(rn/set-status-bar-style (if (get screens/dark-screens view-id) "light-content" "dark-content")`. wdyt?

Btw, did you tried using keywords here for "light-content"?

Comment (Parveshdhull) [reply src/quo/theme.cljs]: > Inside :set-view-id-fx

In this way, we can also get rid of `change-shell-status-bar-style` event.

Comment (Parveshdhull) [reply src/quo/theme.cljs]: As navigation-bar and status-bar changes go together, it will be really awesome if we can also consider it while applying these solutions.

Comment (J-Son89) [reply src/quo/theme.cljs]: _"(For camera we have in status-im.navigation.options file for some reason)."_ - @Parveshdhull - we should move this to screens. 
What do you mean scattered btw?

Comment (J-Son89) [reply src/quo/theme.cljs]: I agree with Parvesh though we already have this information and should keep it in one place 👍

File: src/quo/theme.cljs [hunk 5]
```diff
@@ -59,3 +59,42 @@
...
+                   (if (dark?)
+                     "light-content"
+                     "dark-content")
+                   true)
+                 change-statusbar-color-delay))
+
+(defn handle-status-bar-dark-screen
+  []
+  (js/setTimeout #(rn/set-status-bar-style "light-content" true) change-statusbar-color-delay))
+
```
Comment (J-Son89) [inline src/quo/theme.cljs]: tbh I dont think these files really relate to "theme".
I think you should make a new file for these and put them in somewhere like navigation/status_bar.cljs 👍 
I think it would be better suited as it's very specific to the application where as quo/theme is a generic theme utility 👍

File: src/status_im/contexts/chat/messenger/camera/view.cljs [hunk 6]
```diff
@@ -99,7 +100,9 @@
 
 (defn bottom-area
   [{:keys [flash camera-type] :as args}]
-  (let [back        #(rf/dispatch [:navigate-back])
+  (let [back        (fn []
+                      (quo.theme/handle-status-bar-screens-per-theme)
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/camera/view.cljs]: why do we need to use this function here? 🤔 

Seems like a lot to handle if we need to do this in the application in random places 🤔

File: src/status_im/contexts/chat/messenger/camera/view.cljs [hunk 7]
```diff
@@ -120,8 +123,10 @@
         on-press               #(retake flash uri)
         use-photo              (fn []
                                  (rf/dispatch [:photo-selector/camera-roll-pick {:uri @uri}])
-                                 (rf/dispatch [:navigate-back]))]
+                                 (rf/dispatch [:navigate-back]))
+        current-screen         (rf/sub [:navigation/current-screen-id])]
     (handle-orientation current-orientation rotate)
+    (rn/use-effect #(quo.theme/handle-status-bar-screens current-screen))
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/camera/view.cljs]: is there a clear pattern of when/ why we need this?

File: src/status_im/contexts/chat/messenger/camera/view.cljs (hunk 6 above)
Comment (Parveshdhull) [reply src/status_im/contexts/chat/messenger/camera/view.cljs]: Yes, I think better solution would be to just update status bar color in `:set-view-id-fx` ([ref](https://github.com/status-im/status-mobile/pull/18785#discussion_r1485644048))
This way we will be able to handle all navigation's (screens/modals) and navigation back without manually adding to screens using effects.

File: src/quo/theme.cljs (hunk 4 above)
Comment (Parveshdhull) [reply src/quo/theme.cljs]: > What do you mean scattered btw?

I mean we do have information stored in screens file, but its not clear. Means there is no clear pattern to differentiate just based on passed options.

Some of dark-screen Ibrahem added here, has these options in screens file
`options/transparent-screen-options`, `options/dark-screen`, `options/camera-screen`.

Maybe we can just add some kind of flag or something as prop to differentiate them, `dark? true`

Comment (J-Son89) [reply src/quo/theme.cljs]: Oh I would have thought they all have a prop like that/ resolve to have a prop like that. Either way let's make that happen we should only be tracking this info once and it seems the best place for it is somewhere in navigation/

Comment (J-Son89) [reply src/quo/theme.cljs]: Screenshot 2024-02-12 at 10 39 06

I thought we had that because this already as this is how we are using the `theme` for the theme provider here 👍

Comment (Parveshdhull) [reply src/quo/theme.cljs]: Thank you for screenshot, I see now, even though they are using different options they all have `:theme :dark` param (except camera screen). We can also add there and just use data stored in screens file then.

Comment (J-Son89) [reply src/quo/theme.cljs]: Yep seems we need to clean up camera screen to use a consistent approach

**Comment by ibrkhalil** [comment]
I added refactors according to the things you pointed out guys
Please take a look when you have a minute
CC: @Parveshdhull @J-Son89

File: src/status_im/navigation/options.cljs [hunk 8]
```diff
@@ -138,7 +138,8 @@
                                                                       :factor 1.5}}]}}})
 
 (def camera-screen
-  {:navigationBar {:backgroundColor colors/black}})
```
Comment (J-Son89) [inline src/status_im/navigation/options.cljs:141]: Can't we just move this to screens here?

**Comment by J-Son89** [comment]
Looks great @ibrkhalil! Nice job 🙌🏼

File: src/status_im/navigation/effects.cljs [hunk 9]
```diff
@@ -117,8 +134,10 @@
 
 (defn open-modal
   [component]
-  (let [{:keys [options]} (get views/screens component)
-        sheet?            (:sheet? options)]
+  (let [{:keys [options name]} (get views/screens component)
+        sheet?                 (:sheet? options)
+        screen-theme           (:theme options)]
+    (set-status-bar-color screen-theme name)
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs]: hi, why we still need to add this here? Is a specific modal not covered by `:set-view-id-fx`?

File: src/status_im/navigation/effects.cljs [hunk 10]
```diff
@@ -8,12 +10,27 @@
...
+     true))
+  (reset! previous-screen view-id))
+
 (rf/reg-fx :set-view-id-fx
  (fn [view-id]
-   (rf/dispatch [:screens/on-will-focus view-id])
-   (when-let [{:keys [on-focus]} (get views/screens view-id)]
-     (when on-focus
-       (rf/dispatch on-focus)))))
+   (let [screen-theme (get-in (get views/screens view-id) [:options :theme])]
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs]: Can we just use `(get-in views/screens [view-id :options :theme]`?

File: src/status_im/navigation/effects.cljs [hunk 11]
```diff
@@ -8,12 +10,27 @@
     [taoensso.timbre :as log]
     [utils.re-frame :as rf]))
 
+(def previous-screen (atom nil))
+
+(defn- set-status-bar-color
+  [theme view-id]
+  (when-not (= @previous-screen :settings-syncing)
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs]: Please can you elaborate, why we still need to store previous-screen?

Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: When we select the syncing item from the settings screen, As the settings modal is closing we actually go back to shell before we open the screen we chose, And that causes the statusbar color to flicker from white to black and then to white again.

This is a workaround to it.

File: src/status_im/navigation/effects.cljs (hunk 10 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Fixed.

File: src/status_im/navigation/effects.cljs (hunk 9 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: I think the settings one

File: src/status_im/navigation/effects.cljs (hunk 11 above)
Comment (Parveshdhull) [reply src/status_im/navigation/effects.cljs]: It looks like some kind of bug. I don't think we should close settings screen while opening syncing screen.
(we can confirm this with the design team, but it is somewhat obvious)

Please remove workaround, we can create an issue and address this navigation issue in follow up pr.

File: src/status_im/navigation/effects.cljs (hunk 9 above)
Comment (Parveshdhull) [reply src/status_im/navigation/effects.cljs]: this also looks like navigation issue, please log it, we can address this in follow up PR

File: src/status_im/navigation/effects.cljs (hunk 11 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Logged https://github.com/status-im/status-mobile/issues/18810

File: src/status_im/navigation/effects.cljs (hunk 9 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Logged https://github.com/status-im/status-mobile/issues/18811

File: src/status_im/navigation/effects.cljs [hunk 12]
```diff
@@ -8,12 +10,23 @@
...
-   (rf/dispatch [:screens/on-will-focus view-id])
-   (when-let [{:keys [on-focus]} (get views/screens view-id)]
-     (when on-focus
-       (rf/dispatch on-focus)))))
+   (let [screen-theme (get-in views/screens [view-id :options :theme])]
+     (set-status-bar-color screen-theme)
+     (rf/dispatch [:screens/on-will-focus view-id])
+     (when-let [{:keys [on-focus]} (get views/screens view-id)]
+       (when on-focus
+         (rf/dispatch on-focus))))))
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs]: Can we use something like,
```
(rf/dispatch [:screens/on-will-focus view-id])
(when-let [{:keys [on-focus options]} (get views/screens view-id)]
     (set-status-bar-color (:theme options))
     (when on-focus
       (rf/dispatch on-focus)))
```

File: src/status_im/navigation/effects.cljs [hunk 13]
```diff
@@ -56,7 +68,8 @@
                                   options
                                   (if (:topBar options)
                                     (options/merge-top-bar (options/topbar-options) options)
-                                    {:topBar {:visible false}}))}})))
+                                    {:topBar {:visible false}}))}})
+    (dismiss-all-modals)))
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs]: why we move this?

File: src/status_im/navigation/effects.cljs [hunk 14]
```diff
@@ -117,11 +130,12 @@
...
 (defn open-modal
   [component]
-  (let [{:keys [options]} (get views/screens component)
-        sheet?            (:sheet? options)]
+  (let [{:keys [options name]} (get views/screens component)
+        sheet?                 (:sheet? options)]
     (if @state/dissmissing
       (reset! state/dissmissing component)
       (do
+        (set-view-id name)
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs]: Please also add todo here, (Will be removed in https://github.com/status-im/status-mobile/issues/18811).
`component-did-appear-listener` should have called this function. We have to look into that and see why that didn't happen, and then we can remove this.

**Comment by Parveshdhull** [comment]
Hi @ibrkhalil, Thank you very much for finding this fix and your patience. After removing delay it looks much better.

Please can you check ios build. Its working nice for settings screen, but for shell status-bar color is not changing.

File: src/status_im/navigation/effects.cljs (hunk 13 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Apologies, It was an attempt to fix the navigation issue of closing modals when navigating but I forgot to remove it.
Removing.

File: src/status_im/navigation/effects.cljs (hunk 12 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Sure

File: src/status_im/navigation/options.cljs (hunk 8 above)
Comment (ibrkhalil) [reply src/status_im/navigation/options.cljs:141]: Done

File: src/status_im/navigation/effects.cljs (hunk 14 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Done

File: src/status_im/navigation/effects.cljs (hunk 12 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Done

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil, Thank you very much for finding this fix and your patience. After removing delay it looks much better.
> 
> Please can you check ios build. Its working nice for settings screen, but for shell status-bar color is not changing.

Couldn't reproduce, unfortunately.

**Comment by Parveshdhull** [comment]
> Couldn't reproduce, unfortunately.

Thank you for giving it another try. Maybe QA team can take a look.

**Review by Parveshdhull — APPROVED** [review]
Thank you for your awesome work.

File: src/status_im/navigation/effects.cljs [hunk 15]
```diff
@@ -1,5 +1,7 @@
 (ns status-im.navigation.effects
   (:require
+    [quo.theme :as quo.theme]
```
Comment (J-Son89) [inline src/status_im/navigation/effects.cljs]: nit: `[quo.theme]`

File: src/status_im/navigation/effects.cljs [hunk 16]
```diff
@@ -8,10 +10,20 @@
     [taoensso.timbre :as log]
     [utils.re-frame :as rf]))
 
+(defn- set-status-bar-color
```
Comment (J-Son89) [inline src/status_im/navigation/effects.cljs:13]: maybe we should just keep this function "pure" and pass only theme in.

```
defn- set-status-bar-color
  [theme]
  (rn/set-status-bar-style
   (quo/theme-value
     "dark-content"
     "light-content"
     theme)
   true))
```
```
(rf/reg-fx :set-view-id-fx
 (fn [view-id]
   (rf/dispatch [:screens/on-will-focus view-id])
   (when-let [{:keys [on-focus options]} (get views/screens view-id)
   page-theme (:theme options)
   user-theme (quo.theme/get-theme)
   ]
     (set-status-bar-color (or page-theme user-theme))
     (when on-focus
       (rf/dispatch on-focus)))))
```

File: src/status_im/navigation/effects.cljs [hunk 17]
```diff
@@ -117,11 +129,12 @@
...
 (defn open-modal
   [component]
-  (let [{:keys [options]} (get views/screens component)
-        sheet?            (:sheet? options)]
+  (let [{:keys [options name]} (get views/screens component)
+        sheet?                 (:sheet? options)]
     (if @state/dissmissing
       (reset! state/dissmissing component)
       (do
+        (set-view-id name) ; TODO Will be removed in #18811
```
Comment (J-Son89) [inline src/status_im/navigation/effects.cljs]: can you instead use the github link for TODO's 👍

**Review by J-Son89 — APPROVED** [review]

File: ios/StatusIm/Info.plist [hunk 18]
```diff
@@ -133,7 +133,7 @@
 		<string>UIInterfaceOrientationLandscapeRight</string>
 	</array>
 	<key>UIViewControllerBasedStatusBarAppearance</key>
-	<true/>
+	<false/>
```
Comment (briansztamfater) [inline ios/StatusIm/Info.plist:136]: This might affect the Splash Screen on iOS, let's be sure it is properly tested

File: src/status_im/navigation/effects.cljs (hunk 16 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs:13]: Brilliant point, Doing it now.

File: src/status_im/navigation/effects.cljs (hunk 15 above)
Comment (ibrkhalil) [reply src/status_im/navigation/effects.cljs]: Done

**Comment by pavloburykh** [comment]
@ibrkhalil hello. Thanx for the PR. Reminder: please do not forget to move PRs on the board. If PR has passed review and is ready for testing it should be moved from Review to E2E column. Otherwise QA team will high-liklely miss your PR and there will be additional delay with testing. QAs are monitoring PRs from E2E column. PRs from Review column are generally assumed to be not yet ready for QA testing.

**Comment by mariia-skrypnyk** [comment]
@ibrkhalil thanks for your PR!

Please, take a look on this issue:

**ISSUE 1: status bar element are dark on the dark theme on Jump to screen**

**Actual result:**
Screenshot 2024-02-26 at 12 39 11

**Expected result:**
Screenshot 2024-02-26 at 12 40 58

**Comment by ibrkhalil** [comment]
> @ibrkhalil thanks for your PR!
> 
> Please, take a look on this issue:
> 
> **ISSUE 1: status bar element are dark on the dark theme on Jump to screen**
> 
> **Actual result:** Screenshot 2024-02-26 at 12 39 11
> 
> **Expected result:** Screenshot 2024-02-26 at 12 40 58

Should be fixed now.

**Comment by mariia-skrypnyk** [comment]
Hi @ibrkhalil !

Thanks for your fix. PR can be merged.
