### PR TITLE
fix(wallet): Collectibles not fetched for new and recovered accounts

### LINKED ISSUE #18613: Collectibles not displayed after account recovery and after watch only account is added until relogin
### Steps:
1. Add watch only account or restore account with collectibles
2. Go to the 'collectibles' tab

### Actual result:
The collectibles are not displayed until the user performs a re-login.

### Expected result:
The collectibles should be immediately visible after resoter or as soon as the watch only account is added 

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/14040937/Status-debug-logs.1.zip)

### Additional info:
Feel free to reach out to me directly if you need a user with collectibles.  I will provide the seed phrase.

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18613

### Summary

This PR fixes collectibles not fetched for newly added or recovered accounts.

### Review notes

When we call the `wallet_getCollectiblesAsync` RPC, it returns the cached data from the DB. For the newly added address, the collectible is not fetched for those addresses and is not cached in the DB. So, immediately we get an empty response with an updating state and the last fetched timestamp (which would be -1 for those addresses). 

status-go fetches the collectibles in the background and signals the client with `wallet-collectibles-ownership-update-*`. When the mobile receives it, it checks for any added (cached in the DB) collectibles and requests for collectibles for that chain id. The `wallet-collectibles-ownership-update-*` sends only the contract address and token ID of the collectibles added/updated/removed. Later, we can check for updated or removed collectibles and act on them accordingly on the mobile.

Another problem is that when the accounts (apart from the default wallet account) are added from the backup data, they do not initiate the collectable fetching in the status-go which is fixed in this PR: https://github.com/status-im/status-go/pull/5739

The status-go fix is to send an event on adding/removing accounts from processing the backed-up data to initiate collectibles fetch in the background.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Recover a profile with wallet accounts with collectibles
- Verify the collectibles are fetched

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/signals.cljs [hunk 1]
```diff
@@ -29,6 +29,16 @@
...
 
+       "wallet-collectibles-ownership-update-finished"
+       {:fx [[:dispatch
+              [:wallet/collectible-ownership-update-finished
+               (transforms/js->clj event-js)]]]}
+
+       "wallet-collectibles-ownership-update-finished-with-error"
+       {:fx [[:dispatch
+              [:wallet/collectible-ownership-update-finished-with-error
+               (transforms/js->clj event-js)]]]}
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/signals.cljs:40]: This may happen if the collectible provider (Alchemy/Opensea/Rarible) token is not set or expired.

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 2]
```diff
@@ -131,6 +137,50 @@
...
+              [:wallet/request-new-collectibles-for-account
+               {:request-id (-> (get-unique-collectible-request-id 1) first)
+                :account    address
+                :chain-ids  [chainId]
+                :amount     collectibles-request-batch-size}]])]})))
+
+(rf/reg-event-fx
+ :wallet/set-collectibles-fetching-status
+ (fn [{:keys [db]} [address chain-ids]]
+   {:db (assoc-in db [:wallet :ui :collectibles :fetching address] chain-ids)}))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/collectible/events.cljs]: Setting the chain-ids as the value instead of the boolean value to know which chains are been fetched. Later this can be used to show any loading indicator or info box that collectibles are loading.

The `wallet-collectibles-ownership-update-` signal is received for all addresses as status-go updates the collectible ownership data cache in some interval/action. This chain-ids data would help to identify the new addresses and chains that have been updated and the pending ones.

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 3]
```diff
@@ -131,6 +137,52 @@
...
+                 :error    message})
+     {:db (cond-> db
+            (some? chain-ids)
+            (update-in [:wallet :ui :collectibles :fetching address] disj chainId))})))
+
+(rf/reg-event-fx
+ :wallet/collectible-ownership-update-finished
+ (fn [{:keys [db]} [{:keys [accounts message chainId]}]]
+   (let [address                (first accounts)
+         {:keys [added]}        (transforms/json->clj message)
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/collectible/events.cljs]: The message contains `added`, `updated` and `removed` keys which will have an array of maps with the contract address and token ID of the collectible. Later, we can handle the `updated` or `removed` keys and update the data in app-db for all addresses. For now, we focus on addresses which were never fetched.

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 4]
```diff
@@ -131,6 +137,56 @@
               :account    current-viewing-account
               :amount     collectibles-request-batch-size}]]]})))
 
+(rf/reg-event-fx
+ :wallet/collectible-ownership-update-finished-with-error
+ (fn [{:keys [db]} [{:keys [accounts message chainId]}]]
+   (let [address   (first accounts)
+         chain-ids (some-> (get-in db [:wallet :ui :collectibles :fetching address])
+                           (disj chainId))]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: I thin the regular `->` works the same as `some->` here

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 5]
```diff
@@ -131,6 +137,56 @@
...
+     (log/error "[wallet] collectibles ownership update failed"
+                {:address  address
+                 :chain-id chainId
+                 :error    message})
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: I think we have an effect to log errors

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 6]
```diff
@@ -131,6 +137,56 @@
...
+
+            (seq updated-chain-ids)
+            (assoc-in [:wallet :ui :collectibles :fetching address] updated-chain-ids)
+
+            added-for-new-address?
+            (assoc-in [:wallet :ui :collectibles :pending-requests] (inc pending-requests)))
+      :fx [(when added-for-new-address?
+             [:dispatch
+              [:wallet/request-new-collectibles-for-account
+               {:request-id (-> (get-unique-collectible-request-id 1) first)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: IMO, it's better to not use -> with only one step

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 7]
```diff
@@ -144,20 +200,32 @@
  (fn [{:keys [db]} [{:keys [message]}]]
    (let [{:keys [offset ownershipStatus collectibles
                  hasMore]} (transforms/json->clj message)
+         ownershipStatus   (update-keys ownershipStatus name)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: It's not a great idea to shadow vars 👀

In general this is an avoided practice in Clojure

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 8]
```diff
@@ -144,20 +200,32 @@
...
-         owner-address     (some->> ownershipStatus
-                                    first
-                                    key
-                                    name)]
+         ;; collectibles are never fetched and cached for this address before
+         new-account?      (->> ownership-status
+                                vals
+                                (every?
+                                 #(and (= (:state %) (ownership-state :updating))
+                                       (= (:timestamp %) -1))))]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: Maybe it's better to move this to a named function so that we avoid using `#()` in a non-one-liner function and we give a name to this predicate.

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 9]
```diff
@@ -144,20 +200,32 @@
...
      {:db (cond-> db
             :always       (assoc-in [:wallet :ui :collectibles :pending-requests] pending-requests)
             owner-address (update-fetched-collectibles-progress owner-address
                                                                 collectibles
                                                                 offset
-                                                                hasMore))
+                                                                (if new-account? nil hasMore)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: `when-not`

**Review by ulisesmac — COMMENTED** [review]
Hey @smohamedjavid , I left some comments, mostly related to code

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 10]
```diff
@@ -62,7 +58,11 @@
                                   amount
                                   data-type
                                   fetch-criteria]]
-     {:fx [[:json-rpc/call
+     {:db (cond-> db
+            reset-collectibles?
+            (update-in [:wallet :ui :collectibles :reset-collectibles-request-ids]
+                       #(conj (or % #{}) request-id)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs:64]: So, do we store the request-ids that were reset?

btw, consider using `fnil` on `conj` instead that `or`

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 11]
```diff
@@ -62,7 +58,11 @@
...
+      :fx [[:json-rpc/call
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: So, do we store the request-ids that were reset?

btw, consider using `fnil` on `conj` instead that `or`

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 12]
```diff
@@ -83,81 +83,183 @@
...
  :wallet/request-collectibles-for-all-accounts
  (fn [{:keys [db]} [{:keys [new-request?]}]]
-   (let [accounts                 (->> (get-in db [:wallet :accounts])
-                                       (filter (fn [[_ {:keys [has-more-collectibles?]}]]
-                                                 (or (nil? has-more-collectibles?)
-                                                     (true? has-more-collectibles?))))
-                                       (keys))
-         num-accounts             (count accounts)
-         collectibles-per-account (quot collectibles-request-batch-size num-accounts)
+   (let [updating-collectibles-addresses (-> (get-in db [:wallet :ui :collectibles :updating])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: Consider renaming `:updating` to `:updating-addresses` or something better that makes clear enough what this key means. It's too verbose, but we are doing it in the sake of clarity and maintainability

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 13]
```diff
@@ -83,81 +83,183 @@
...
+                                             keys
+                                             set)
+         accounts                        (->> (get-in db [:wallet :accounts])
+                                              (filter (fn [[_ {:keys [has-more-collectibles?]}]]
+                                                        (or (nil? has-more-collectibles?)
+                                                            (true? has-more-collectibles?))))
+                                              (keys))
+         ;; filter the addresses which are requested before and the collectibles are updating
+         filtered-addresses              (seq (clojure.set/difference (set accounts)
+                                                                      updating-collectibles-addresses))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: I think we don't need that `seq` on `filtered-addresses`.

btw, don't we have a better name for it? maybe something like "pending-addresses-to-..." idk, I just feel like "filtered addresses" is too general :thinking:

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 14]
```diff
@@ -83,81 +83,183 @@
...
+(rf/reg-event-fx :wallet/request-collectibles-for-account request-collectibles-for-account)
 
 (rf/reg-event-fx
  :wallet/request-collectibles-for-current-viewing-account
  (fn [{:keys [db]} _]
-   (let [current-viewing-account (-> db :wallet :current-viewing-account-address)
-         [request-id]            (get-unique-collectible-request-id 1)]
-     {:db (assoc-in db [:wallet :ui :collectibles :pending-requests] 1)
+   (let [current-viewing-account (-> db :wallet :current-viewing-account-address)]
+     {:fx [[:dispatch [:wallet/request-collectibles-for-account {:address current-viewing-account}]]]})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: If this is the only one usage for `:wallet/request-collectibles-for-account`, IMO we don't need it to be a re-frame event.

`:wallet/request-collectibles-for-account` is not using the re-frame's db, we could remove the event, just keep the function `request-collectibles-for-account` and call it inside  `:wallet/request-collectibles-for-current-viewing-account`. 

We could even remove the function if it's an unnecessary abstraction and just put the logic inside `:wallet/request-collectibles-for-current-viewing-account`

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 15]
```diff
@@ -83,81 +83,183 @@
...
+ (fn [{:keys [db]} [{:keys [accounts message chainId]}]]
+   (let [address           (first accounts)
+         pending-chain-ids (-> (get-in db [:wallet :ui :collectibles :updating address])
+                               (disj chainId))]
+     {:db (cond-> db
+            (empty? pending-chain-ids)
+            (update-in [:wallet :ui :collectibles :updating] dissoc address)
+
+            (seq pending-chain-ids)
+            (assoc-in [:wallet :ui :collectibles :updating address] pending-chain-ids))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: This one looks more like an `if` :thinking:  I personally prefer to use `cond->` as a macro to handle multiple possible simultaneous transformations on a value, not as a way to handle an `if` on a value. IMO, an `if` is easier to read:
```clojure
(if (seq pending-chain-ids)
  (assoc-in db [:wallet :ui :collectibles :updating address] pending-chain-ids)
  (update-in db [:wallet :ui :collectibles :updating] dissoc address))
```

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 16]
```diff
@@ -83,81 +83,183 @@
...
       :fx [[:dispatch
-            [:wallet/request-new-collectibles-for-account
-             {:request-id request-id
-              :account    current-viewing-account
-              :amount     collectibles-request-batch-size}]]]})))
+            [:wallet/log-rpc-error
+             {:event  :wallet/collectible-ownership-update-finished-with-error
+              :params {:address  address
+                       :chain-id chainId}}
+             message]]]})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: I think this event checks if there's an error while fetching the collectibles for certain address on a specific chain-id, and if there are no more pending chain-ids for an address, we remove it from `:updating` on re-frame. am I right?

I'd suggest renaming this event to something more meaningful in terms of its work, currently I think it just makes reference to where it's used ("`finished-with-error`"), another option can be adding a comment inside the event handler to make the understainding easier.

wdyt?

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/events.cljs]: I sent you a DM giving a possible solution for it, it consists of indexing the collectibles using the `hash` function.

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 17]
```diff
@@ -83,81 +83,183 @@
...
+         pending-chain-ids      (get-in db [:wallet :ui :collectibles :updating address])
+         added?                 (some? added)
+         added-for-new-address? (and added? (seq pending-chain-ids))
+         updated-chain-ids      (disj pending-chain-ids chainId)]
+     {:db (cond-> db
+            (empty? updated-chain-ids)
+            (update-in [:wallet :ui :collectibles :updating] dissoc address)
+
+            (seq updated-chain-ids)
+            (assoc-in [:wallet :ui :collectibles :updating address] updated-chain-ids))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: Same comment as before about using an `if`

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 18]
```diff
@@ -83,81 +83,183 @@
...
+             message]]]})))
+
+(rf/reg-event-fx
+ :wallet/collectible-ownership-update-finished
+ (fn [{:keys [db]} [{:keys [accounts message chainId]}]]
+   (let [address                (first accounts)
+         {:keys [added]}        (transforms/json->clj message)
+         pending-chain-ids      (get-in db [:wallet :ui :collectibles :updating address])
+         added?                 (some? added)
+         added-for-new-address? (and added? (seq pending-chain-ids))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: To check if the collectible is added for a new address, is it enough checking `(seq pending-chain-ids)`?

@smohamedjavid , Could you please elaborate on this, it's unclear for me :sweat_smile:

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 19]
```diff
@@ -83,81 +83,183 @@
...
+            (empty? updated-chain-ids)
+            (update-in [:wallet :ui :collectibles :updating] dissoc address)
+
+            (seq updated-chain-ids)
+            (assoc-in [:wallet :ui :collectibles :updating address] updated-chain-ids))
+      :fx [(when added-for-new-address?
+             [:dispatch
+              [:wallet/request-collectibles-for-account
+               {:address             address
+                :reset-collectibles? true}]])]})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: Could you please explain how the `:reset-collectibles?` flag/mechanism works?

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 20]
```diff
@@ -83,81 +83,183 @@
...
+
+(rf/reg-event-fx
+ :wallet/collectibles-data-updated
+ (fn [{:keys [db]} [{:keys [message]}]]
+   (let [collectibles-by-address           (->> message
+                                                transforms/json->clj
+                                                data-store/rpc->collectibles
+                                                (group-by #(-> % :ownership first :address)))
+         update-collectibles-in-account-fn (fn [existing-collectibles updated-collectibles]
+                                             (let [idxd-existing (utils.collection/index-by
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: Not suree if `idxd` is a clear reduced form for `indexed` :thinking: 

This is a pure function, so we could use complete names an define this function outside this event handler, wdyt?

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 21]
```diff
@@ -83,81 +83,183 @@
...
+ (fn [{:keys [db]} [address chain-ids]]
+   {:db (assoc-in db [:wallet :ui :collectibles :updating address] chain-ids)}))
 
 (defn- update-fetched-collectibles-progress
-  [db owner-address collectibles offset has-more?]
+  [db owner-address collectibles offset has-more? reset-collectibles?]
   (-> db
-      (assoc-in [:wallet :ui :collectibles :fetched owner-address] collectibles)
+      (update-in [:wallet :accounts owner-address :collectibles]
+                 #(if reset-collectibles? collectibles (reduce conj (or % []) collectibles)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: btw, sometimes I feel we abuse of the one-liner `if` statement, it's usually clearer if we add a new line when complex  s-forms appear, I personally try to only use it as a one-liner when the forms are very simple.

I mean this one reads better:
```clojure
(if reset-collectibles?
  collectibles
  (reduce ... collectibles))
```

Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs]: This is maybe another place to use `fnil` :smile:

File: src/status_im/contexts/wallet/data_store.cljs [hunk 22]
```diff
@@ -262,3 +263,10 @@
      ;;  :cost () ;; tbd not used on desktop
      :token-fees                token-fees
      :gas-amount                (:tx-gas-amount new-path)}))
+
+(defn rpc->collectibles
+  [collectibles]
+  (->> collectibles
+       (cske/transform-keys transforms/->kebab-case-keyword)
+       (map #(assoc % :unique-id (collectible-utils/get-collectible-unique-id %)))
+       vec))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/data_store.cljs:276]: In the future, having the collectibles as a hash map is gonna be easier than having a vector/list, since it's data that must be constantly updated

**Review by ulisesmac — COMMENTED** [review]
Hey Javid, 
Now I did a major review, there are interesting changes and I left some questions to understand what's going on.

Good job :+1:  :+1:  :+1:

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. Usually the collectibles are fetched, but not all. I can share in DM the seed phrase of a user that has such a collectibles. 

## ISSUE 1: Incomplete  fetching of collectibles after user is restored

### Steps:
1. Restore user
2. Check collectibles

### Actual result:

https://github.com/user-attachments/assets/b85af491-a578-4343-9504-0eb4265be68a

### Expected result:
Collectibles are fetched after account is restored

### Additional info:
Note 1: Previously, refreshing the wallet or relogging resolved such issues, but currently, only relogging helps.
Note 2: This issue seems to affect collectibles on the testnet. It’s unclear if it’s related to specific collectibles or networks.
Note 3: The same issue is reproducible on the desktop platform. (waited ~20 minutes, but collectibles were shown in loading state) 
image

### Mobile logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/16562062/Status-debug-logs.zip)

### Desktop logs:
[desktop logs.txt](https://github.com/user-attachments/files/16562351/desktop.logs.txt)

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Thanks for testing the PR 🙏 

The issue should be fixed now. The fix includes a status-go [update](https://github.com/status-im/status-go/pull/5739).

**Comment by VolodLytvynenko** [comment]
Hey @smohamedjavid, unfortunately, I wasn't able to check this PR. yesterday just came back from vacations. I'll take a look at it today. Could you please rebase the current PR and the Status Go PR [here](https://github.com/status-im/status-go/tree/fix/send-account-event-on-handling-backedup-accounts)?

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - No worries. I have rebased both PRs 👍

**Comment by VolodLytvynenko** [comment]
@smohamedjavid Thank you for PR. No issues from my side. PR is ready to be merged
