### PR TITLE
fix icon missing regression

### LINKED ISSUE #13904: Icons missing from most menus
# Bug Report

## Problem 
Regression from https://github.com/status-im/status-mobile/pull/13607

Screenshot 2022-08-31 at 16 46 19

Screenshot 2022-08-31 at 16 50 23

Screenshot 2022-08-31 at 16 51 26

#### Expected behavior
Menu with icons 

Screenshot 2022-08-31 at 16 47 26

### Reproduction

1. Open Status 
2. Navigate to different menus in the app (Home screen, Wallet, Browser, etc.)

### Additional Information

- Status version: version with merged https://github.com/status-im/status-mobile/pull/13607
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by siddarthkay**
fixes #13904

### Summary

This fixes an icon render issue which was introduced after refactoring the list-item quo component.

#### Platforms

- Android
- iOS

### Steps to test

Check all broken icons

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

File: src/quo/components/list/item.cljs [hunk 1]
```diff
@@ -86,7 +86,7 @@
          icon
 
          (keyword? icon)
-         (if new-ui?
+         (when new-ui?
```
Comment (Parveshdhull) [inline src/quo/components/list/item.cljs]: Hi, this is not the right way to fix this issue.
`(if cond a b)`
returns a when cond is true and b when false
`(when cond a b)`
`when` always returns last value when true and else nil.
here a is component is for new-ui and b is component for old-ui.
So yes, returning old-ui component will look like it fixes the issue. But it will break for new-ui.
(We need to check why cond (new-ui?) is true in case of old-ui)

**Review by Parveshdhull — CHANGES_REQUESTED** [review]

File: src/quo/components/list/item.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/quo/components/list/item.cljs]: Also, when `new-ui?` is true, why empty space is shown instead of icon?

Comment (siddarthkay) [reply src/quo/components/list/item.cljs]: > Hi, this is not the right way to fix this issue. `(if cond a b)` returns a when cond is true and b when false `(when cond a b)` `when` always returns last value when true and else nil. here a is component is for new-ui and b is component for old-ui. So yes, returning old-ui component will look like it fixes the issue. But it will break for new-ui. (We need to check why cond (new-ui?) is true in case of old-ui)



Makes sense, I will look into why `new-ui?` is `true`

Comment (siddarthkay) [reply src/quo/components/list/item.cljs]: After more debugging I found out that the ` new-ui? ` code block in items component which was introduced  does nothing good either for new-ui or for old ui and hence I have removed it and icons work fine for both new/old ui.

@jo-mut  can you confirm please?

Comment (jo-mut) [reply src/quo/components/list/item.cljs]: removing the `new-ui?` would solve the regression but the same problem would not be on the redesign because icons  for the old component dont work with the redesign

**Review by flexsurfer — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by pavloburykh** [comment]
hi @siddarthkay! Could you please rebase this branch to latest develop? Thanx!

**Comment by siddarthkay** [comment]
Hi @pavloburykh : I've rebased the branch on latest develop

**Comment by siddarthkay** [comment]
Rebase latest develop on my branch
328n9a

**Comment by pavloburykh** [comment]
@siddarthkay hey, please let me know when PR will be ready for test. cause I started testing and have run e2e but I see that new rebase commits are still coming.

**Comment by siddarthkay** [comment]
> @siddarthkay hey, please let me know when PR will be ready for test. cause I started testing and have run e2e but I see that new rebase commits are still coming. 

Hi @pavloburykh : ready to test now :)

**Comment by pavloburykh** [comment]
@siddarthkay  thanx for the fix. Ready for merge.
