### PR TITLE
[#17647] fix: generate keys title overlap

### LINKED ISSUE #17647: Missing "Generating keys" screen in the onboarding animation on iOS
# Bug Report

## Problem 

The `Generating keys...` seems to be overlapped by the `Saving keys to device...` screen in the onboarding illustration.
See the screenshot and video below. 

Screenshot 2023-10-16 at 11 46 53

https://github.com/status-im/status-mobile/assets/67952253/d57f661b-9bba-4f42-9a4c-1dd17a81c4ef

#### Expected behavior

Video from Android

https://github.com/status-im/status-mobile/assets/67952253/fdf99c24-395d-46cd-a795-63713548a1c9

Screenshot 2023-10-16 at 11 53 09

### Reproduction

1. Install Status on iOS
2. Create and confirm your password
3. Keep an eye on the `Generating keys` animation

### Additional Information

- Status version: nightly 13/10
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17647

### Summary

The Generating keys... seems to be overlapped by the Saving keys to device... screen in the onboarding illustration.
See the screenshot and video below.

### Steps to test

1. Install Status on iOS
2. Create and confirm your password
3. Keep an eye on the Generating keys animation

status: ready

https://github.com/status-im/status-mobile/assets/71308738/f49e6498-2486-4c84-bbf4-ffaa1a69b5ba

### CODE REVIEW

File: src/status_im2/contexts/onboarding/generating_keys/view.cljs [hunk 1]
```diff
@@ -54,7 +54,7 @@
                                                            "easing"   (:linear reanimated/easings))))))
   (reanimated/set-shared-value keys-saved-opacity
                                (reanimated/with-delay
-                                4600
+                                5100
```
Comment (BalogunofAfrica) [inline src/status_im2/contexts/onboarding/generating_keys/view.cljs]: LGTM. Just one question. This number is just by trial right?

Comment (Parveshdhull) [inline src/status_im2/contexts/onboarding/generating_keys/view.cljs]: Please can you elaborate, how these values are calculated?
Also, should we store them as constants?

Comment (flexsurfer) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs]: yes magic numbers, we need to understand what's behind them, and if these numbers will work different on different devices

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs]: @Parveshdhull I'm not certain which documentation they referred to when considering the time settings. I just tried to correct some miscalculations related to time that are causing overlaps.

sure will move them to constant values

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs]: @BalogunofAfrica i think so, i couldn't find any docs related to these amounts, so i just tried to resolve overlapping between steps

Comment (Parveshdhull) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs]: > @Parveshdhull I'm not certain which documentation they referred to when considering the time settings.

Probably @J-Son89 can help you out. https://github.com/status-im/status-mobile/pull/16415

We need to figure out how they are calculated, otherwise trial based solution might break on another device.

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs]: @flexsurfer @Parveshdhull so these numbers introduced in this [PR](https://github.com/status-im/status-mobile/pull/16415), @J-Son89 could you please advice?

**Review by flexsurfer — APPROVED** [review]

**Review by BalogunofAfrica — APPROVED** [review]

File: src/status_im2/contexts/onboarding/generating_keys/view.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs]: @Parveshdhull i just moved these numbers to some proper constant values and waiting for Jamie to clarify

**Review by ilmotta — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im2/contexts/onboarding/generating_keys/view.cljs [hunk 2]
```diff
@@ -10,6 +10,12 @@
     [status-im2.contexts.onboarding.generating-keys.style :as style]
     [utils.i18n :as i18n]))
 
+(def first-title-display-time 2000)
+(def second-title-start-time 2500)
+(def second-title-display-time 1000)
+(def third-title-start-time 5100)
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/generating_keys/view.cljs]: @mohsen-ghafouri this looks good. As far as I recall there was nothing particularly special about these numbers other than we left time for each animation to run. @briansztamfater worked on this with the designers and we found these times to work. This looks good here 👍

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/onboarding/generating_keys/view.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs]: Thanks @J-Son89 for the clarification

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you for the PR. Please take a look at the following issue

### ISSUE 1 "Generating keys" screen is missing during onboarding (IOS)

Reproducing on iPhone X, IOS 16.1

**Steps:** 

1. Proceed with onboarding
2. Pay attention if "Generating keys" screen is shown after "Enable biometrics" step

**Actual result:** "Generating keys" screen is missing. "Saving keys" screen is shown after  "Enable biometrics" step


https://github.com/status-im/status-mobile/assets/97245802/360a98f1-034e-474d-a7d3-52b4d051666a

**Expected result:** "Generating keys" screen should be shown before "Saving keys" screen. 

Screenshot 2023-10-16 at 11 53 09

**Comment by mohsen-ghafouri** [comment]
Thanks for testing this issue @pavloburykh , could you please check again 

https://github.com/status-im/status-mobile/assets/71308738/d0b446cb-9b10-40be-807f-586c7ba16e72

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you for the fix. 

Now "Generating keys" screen appears. But it seems that it is changed by "Saving keys" screen too fast. WDYT? 


https://github.com/status-im/status-mobile/assets/97245802/bb9e74cf-849c-48a3-9e65-adf097269353

For comparison, here how it looks on Android

https://github.com/status-im/status-mobile/assets/97245802/d5165dcd-0789-4eb8-b19e-e5b332eabea9

**Comment by mohsen-ghafouri** [comment]
@pavloburykh yes i found there is a delay related to navigation in iOS that causes losing some time at the beginning (it happens randomly, sometime it's faster like the video i sent) . it can be better after #17241.

**Comment by pavloburykh** [comment]
>  it can be better after #17241.

cool. Then we are ready to merge the PR. Thank you @mohsen-ghafouri
