### PR TITLE
Fix UI freezing when image is opened from activity center

### LINKED ISSUE #16706: UI  is freezing if quickly open reply with image from activity center and try to open image
# Bug Report

## Problem 
UI freezing has been observed in certain flows, and while we have identified one reliable method to reproduce the issue, it is likely to affect other areas as well.

#### Expected behavior
no freeze;
the app gets back to normal after reopening

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/087c404b-8b8c-4950-b1df-160ac6752c80

### Reproduction
**Prerequisites:** user A (android) and user B are members of the same community

1) User A: send message to the community 
2) User B: reply to user A with an image
3) User A: open the activity center and quickly tap on the image
4) User A: continue to work with an app > navigate back, open community, etc

### Additional Information

- Status version: nightly 
- Operating System: Android
- Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12071744/Status-debug-logs.zip)

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/16706

### Summary
We are directly [using](https://github.com/status-im/status-mobile/blob/e99f6de4340411da0982e94a09ea8ac1da557f0c/src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs#L13C1-L13C1) components created for messaging inside the activity center. And apart from the visible view, those components also have stuff like `on-press` and `on-long-press` events, etc.
Not sure if we want to process those events, But If yes we need to properly implement that, we can't navigate to the lightbox and open the image, without opening the chat screen.

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/activity_log/view.cljs [hunk 1]
```diff
@@ -165,6 +165,7 @@
     :as   props}]
   [rn/view
    {:accessibility-label :activity
+    :pointer-events      :none
```
Comment (siddarthkay) [inline src/quo2/components/notifications/activity_log/view.cljs]: just a tiny nit pick, add a comment explaining why pointer events were disabled. 
and  a todo block to remove this code when a proper fix is implemented.

**Review by siddarthkay — APPROVED** [review]

File: src/quo2/components/notifications/activity_log/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/quo2/components/notifications/activity_log/view.cljs]: Hi @siddarthkay,
Thank you very much for reviewing PR. Added a comment to explain the addition of `:pointer-events`.

> and a todo block to remove this code when a proper fix is implemented.

I don't think we need a todo here. That was just a question to understand why we are using message components like this. Means, are their any use cases where we want touch events to dispatch touch callbacks implemented for messaging screens? **If yes**, we need to do that properly.

**Comment by churik** [comment]
@Parveshdhull 
cannot accept the contact request (nothing happens when tapping on Accept)


https://github.com/status-im/status-mobile/assets/4557972/ada7d650-5443-45f8-b2de-71ba0ffbe705


The reason why I actually submitted the issue now is that perhaps it could explain/help with other UI freezes which are not easily reproducible.

If it is not, the issue itself is not that common and we can definitely postpone it.

**Comment by Parveshdhull** [comment]
Hi @churik, thank you very much for testing the PR.

> If it is not, the issue itself is not that common and we can definitely postpone it.

Yeah sounds good, I will fix the contact request issue and we can include this in the next release.

> The reason why I actually submitted the issue now is that perhaps it could explain/help with other UI freezes which are not easily reproducible.

UI freeze depends on the flow where it happened. If other freezes also happening due to this particular bug, they should be fixed. But we can't know that for sure. There may or may not be other bugs. But whenever a UI freeze issue happens  (even randomly), please report it. Even if it is not reproducible, we will know the flow and location of where it happened.

**Comment by churik** [comment]
> But whenever a UI freeze issue happens (even randomly), please report it. 

we would love too, but it seems really random. but ofc we will keep an eye on it!

**Comment by smohamedjavid** [comment]
Apologies, I just saw this PR now.

Just sharing a note.

> #### Summary
>We are directly [using](https://github.com/status-im/status-mobile/blob/e99f6de4340411da0982e94a09ea8ac1da557f0c/src/status_im2/contexts/shell/activity_center/notification/reply/view.cljs#L13C1-L13C1) components created for messaging inside the activity center. And apart from the visible view, those components also have stuff like on-press and on-long-press events, etc.
Not sure if we want to process those events, But If yes we need to properly implement that, we can't navigate to the lightbox and open the image, without opening the chat screen. Disabled the propagation of touch events to fix the issue. Maybe we should also separate those components.

@Parveshdhull - During the implementation of replies, there was no design for all content types. So, the messenger components were used for the time being. 

Right now, we have the designs for that.

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=13336-165824&mode=design&t=KadcnKQ0KDgiTGqv-0

Once these designs are implemented, these issues will not occur. 

The issue to track is https://github.com/status-im/status-mobile/issues/16054

**Comment by Parveshdhull** [comment]
Hi @smohamedjavid, Thank you very much for information and link.
I will add the implement missing image component and will use that.

File: src/quo2/components/notifications/activity_log/view.cljs [hunk 2]
```diff
@@ -165,6 +165,9 @@
     :as   props}]
   [rn/view
    {:accessibility-label :activity
+    ;; don't propagate touch events to child views (message component)
+    ;; https://github.com/status-im/status-mobile/issues/16706
+    :pointer-events      :none
```
Comment (ilmotta) [inline src/quo2/components/notifications/activity_log/view.cljs]: @Parveshdhull, I'm afraid we can't add `:pointer-events :none` to the top-level view, otherwise button events don't work (e.g. Accept/Decline buttons for contact requests). I tested this case just now.

**Comment by Parveshdhull** [comment]
Hi @smohamedjavid, @ilmotta,
Thank you very much for your input. I updated the PR and removed use of `:pointer-events:none`. And replaced the use of `status-im2.contexts.chat.messages.content.image.view ` with `quo/activity-logs-photos`. Please let me know if anything else needs to be changed.

File: src/quo2/components/notifications/activity_log/style.cljs [hunk 3]
```diff
@@ -25,11 +26,12 @@
...
   {:color colors/white})
 
-(def message-container
+(defn message-container
+  [content-type]
   {:border-radius      12
    :margin-top         12
    :padding-horizontal 12
-   :padding-vertical   8
+   :padding-vertical   (if (= content-type constants/content-type-image) 12 8)
```
Comment (smohamedjavid) [inline src/quo2/components/notifications/activity_log/style.cljs]: Not sure about this condition's flexibility for other content types. 

I think we have only two variants `8` (used on text) and `12` (images, stickers). We can use a boolean to toggle between them depending on the type.  Not for this PR. We will need this once we update the designs for other content types.

**Review by smohamedjavid — APPROVED** [review]
Great work! @Parveshdhull!

**Review by ilmotta — APPROVED** [review]
> Thank you very much for your input. I updated the PR and removed use of :pointer-events:none. And replaced the use of status-im2.contexts.chat.messages.content.image.view with quo/activity-logs-photos. Please let me know if anything else needs to be changed.

Thanks for the explanation. Great fix @Parveshdhull 🚀

File: src/quo2/components/notifications/activity_log/style.cljs (hunk 3 above)
Comment (Parveshdhull) [reply src/quo2/components/notifications/activity_log/style.cljs]: Hi @smohamedjavid,
Thank you very much for your input. Updated the condition as per your suggestion. And also instead of passing content-type, passed :attachment prop as per figma.

@ilmotta not sure if there is an issue, but we probably should create [Activity logs attachments](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=13336-165824&mode=design&t=CmCRjqjhp4xfwVGF-0) component and refactor and also simplify activity logs component. wdyt?

**Comment by qoqobolo** [comment]
@Parveshdhull thanks a lot for the fix!
I've got a question.

In the discussion above I see that the new component has been added for images in the activity center. But it does not display the image itself sent in the community. Is this expected for now?

Screenshot 2023-07-26 at 13 14 46

**Comment by Parveshdhull** [comment]
Hi, @qoqobolo,
Thank you very much for testing the PR.

The issue of missing sent image is also reproducible for me in develop. Please can you check, probably it's different issue.

Means, image is visible randomly. Sometimes image disappear after reopening of app or activity centre

File: src/quo2/components/notifications/activity_log/style.cljs (hunk 3 above)
Comment (ilmotta) [reply src/quo2/components/notifications/activity_log/style.cljs]: > not sure if there is an issue, but we probably should create [Activity logs attachments](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=13336-165824&mode=design&t=CmCRjqjhp4xfwVGF-0) component and refactor and also simplify activity logs component. wdyt?

@Parveshdhull, I totally agree, we need to catch up to the latest changes in the DS and the activity log component is a bit outdated too (based on the guidelines).

**Comment by qoqobolo** [comment]
> Means, image is visible randomly. Sometimes image disappear after reopening of app or activity centre

Yeah, I was about to write that the issue of missing images is only reproducible after reopening AC in develop. After this, if you tap on the missing image it leads to UI freezing.

So, this issue with frozen UI is not reproducible in this PR. And if I reopen AC or the app, nothing happens, it works just fine.

But the image is not displayed the first time AC is opened in PR (while in the develop the image is displayed on the first opening).

_But_ 😅 there is another issue with image replies: notification does not appear **at all** in AC if I send a reply with an image **from desktop to mobile** (I haven't logged it yet). 
It looks like image replies are broken on some other level.

---

So speaking of this
> But the image is not displayed the first time AC is opened (while in the develop the image is displayed on the first opening).

If you are sure that it is not this PR that introduces this, then we can log this missing image issue separately.
WDYT?

**Comment by Parveshdhull** [comment]
> If you are sure that it is not this PR that introduces this, then we can log this missing image issue separately.
 
Yup, it doesn't look related to PR, as the image is visible if a notification is received while the activity center is open. (So component is working ok)

But still, I am not sure about the issue's cause. It might be related to the media server. Probably better to explore it separately.


https://github.com/status-im/status-mobile/assets/17097240/79cd7743-94e5-439f-8736-06cc4e3a664f

**Comment by qoqobolo** [comment]
@Parveshdhull okay, thanks again for your work and patience! 🙏
PR can be merged.
