### PR TITLE
Fix: Wallet Home jumping

### LINKED ISSUE #20328: Wallet: prevent jumping when changing loading state
Video: https://github.com/status-im/status-mobile/pull/20297#issue-2330187160

Two things can be improved:

1. Skip the state where there is only a plus icon, and go to cards loading state.
2. Fix jumping going from loading state to loaded.

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/20328

### Summary
This PR fixes 2 issues on wallet home:
1. Loading cards being delayed about one second before they appear
2. Content jumping when changing from loading state to loaded

### Demo
- Android

https://github.com/status-im/status-mobile/assets/29354102/8a6fefea-2458-445f-b714-8c277bbd4dcb

- iOS

https://github.com/status-im/status-mobile/assets/29354102/23109380-8b97-4d48-9696-078443f2b0f2

### CODE REVIEW

File: src/status_im/contexts/profile/login/events.cljs [hunk 1]
```diff
@@ -142,6 +141,7 @@
            (when (and new-account? (not recovered-account?))
              [:dispatch [:wallet-legacy/set-initial-blocks-range]])
            [:dispatch [:ens/update-usernames ensUsernames]]
+           [:dispatch [:wallet/initialize]]
```
Comment (OmarBasem) [inline src/status_im/contexts/profile/login/events.cljs:147]: Initialize wallet earlier so that we have the wallet cards ready to be in loading state when the user lands on the home screen

Comment (J-Son89) [reply src/status_im/contexts/profile/login/events.cljs:147]: cc @smohamedjavid

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/profile/login/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/login/events.cljs:147]: @OmarBasem this is what I was referring to in your previous PR when I mentioned the `ready?` flag  or changing the subscription to check for `nil` values and take it as "loading".

Now we are initializing the wallet earlier, IMO doing this just to have a loading state is not great, instead we could modify the subscription.

File: src/quo/components/wallet/wallet_overview/style.cljs [hunk 2]
```diff
@@ -2,12 +2,13 @@
...
 
-(def container-info
+(defn container-info
+  [{:keys [metrics]}]
   {:padding-horizontal 20
    :padding-top        12
    :padding-bottom     32
    :flex-grow          1
-   :max-height         98})
+   :height             (if (= metrics :none) 78 98)})
```
Comment (ulisesmac) [inline src/quo/components/wallet/wallet_overview/style.cljs:11]: Where does these numbers come from?

It'd be great to also test it on iOS 👍

File: src/status_im/contexts/profile/login/events.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/profile/login/events.cljs:147]: how could the modified subscription look/act @ulisesmac ? 🤔

Comment (ulisesmac) [reply src/status_im/contexts/profile/login/events.cljs:147]: @J-Son89 if the key doesn't exist, it should take it as "loading". e.g.

```clojure
(rf/reg-sub
 :wallet/loading?
 :<- [:wallet]
 (fn [db]
   (get db :loading? true)))
   
;; or

(rf/reg-sub
 :wallet/loading?
 :<- [:wallet]
 (fn [db]
   (or (nil? (:loading? db))
       (:loading? db))))
```

Another option is to create a sub `:wallet/ready?` (`tokens-ready?`, or whatever we want), so if it has `nil` or `false` it'd be the same.

Comment (OmarBasem) [reply src/status_im/contexts/profile/login/events.cljs:147]: > this is what I was referring to in your previous PR when I mentioned the ready?

@ulisesmac I am not sure what does the `tokens-loading?` has to do with the issue here? The problem here is that wallet initialize takes a little time and we don't know yet how many cards to display as loading. When we initialize a little earlier, we get the data on time, and we know how many cards to display as loading

File: src/quo/components/wallet/wallet_overview/style.cljs (hunk 2 above)
Comment (OmarBasem) [reply src/quo/components/wallet/wallet_overview/style.cljs:11]: @ulisesmac It comes from Figma.

I tested on iOS and it renders correctly 👍

Comment (OmarBasem) [reply src/quo/components/wallet/wallet_overview/style.cljs:11]: Added iOS demo to the description

File: src/status_im/contexts/profile/login/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/login/events.cljs:147]: @OmarBasem  OK!, thanks for the clarification. Yes, the loading state is not related.

> When we initialize a little earlier, we get the data on time, and we know how many cards to display as loading

Doesn't it depends on the network and maybe we still have the same issue?

Comment (OmarBasem) [reply src/status_im/contexts/profile/login/events.cljs:147]: > Doesn't it depends on the network and maybe we still have the same issue?

@ulisesmac If the network was very slow then the cards may be delayed for a split second. We can ask design team for a design for that state like grey cards, but probably not a priority now.

Comment (smohamedjavid) [reply src/status_im/contexts/profile/login/events.cljs:147]: > Initialize wallet earlier so that we have the wallet cards ready to be in loading state when the user lands on the home screen

As for the loading state, we already set the `token-loading? true` when app-db is initialized.

https://github.com/status-im/status-mobile/blob/0d6bd9c15df6e985f01903d44478241a1a0cfe7c/src/status_im/db.cljs#L22


> When we initialize a little earlier, we get the data on time, and we know how many cards to display as loading

The `:wallet/get-accounts` inside `:wallet/initialize` will be faster (just a read/fetch from DB) but `:wallet/get-wallet-tokens` will be slower as it includes the updated tokens balances and market values for the user's preferred currency. There is no guarantee that the request will be faster and the user will see loaded tokens upon landing in the wallet tab. If the account(s) has no tokens, it will be faster but if the account(s) has some tokens, it will take some time. It depends on the network as well.

IMO, the loading state for tokens in the wallet apps is normal after login.

Comment (ulisesmac) [reply src/status_im/contexts/profile/login/events.cljs:147]: @OmarBasem 
OK! and do you still think it's worth moving the wallet initialization?

Does moving the initialization has a side effect? like making the login slower or something?

Comment (J-Son89) [reply src/status_im/contexts/profile/login/events.cljs:147]: do we need to batch the wallet initilization?
i.e split out certain parts? like get account data immediately but get token data slightly later? 🤔

Comment (J-Son89) [reply src/status_im/contexts/profile/login/events.cljs:147]: I will say the first impression of the wallet seems a lot smoother in this video. Nice one @OmarBasem! :)

Comment (OmarBasem) [reply src/status_im/contexts/profile/login/events.cljs:147]: > As for the loading state, we already set the token-loading? true when app-db is initialized.

@smohamedjavid the problem in this PR is not about the loading state, but not having the account cards to display as loading, so what happens is like the below screenshot (you can also [see video](https://github.com/status-im/status-mobile/pull/20297#issue-2330187160) here)

Screenshot 2024-06-06 at 09 18 06

> The :wallet/get-accounts inside :wallet/initialize will be faster (just a read/fetch from DB)

what do you mean by that? I see that `:wallet/get-accounts` is an rpc call.


> @OmarBasem
OK! and do you still think it's worth moving the wallet initialization?

@ulisesmac Yeah I think moving the wallet initialization makes it look smoother as @J-Son89 said

> do we need to batch the wallet initilization?
i.e split out certain parts? like get account data immediately but get token data slightly later? 🤔

FYI guys, there are still further optimizations that can be done to this initialization regarding loading time as described in the following issue https://github.com/status-im/status-mobile/issues/20275

Comment (smohamedjavid) [reply src/status_im/contexts/profile/login/events.cljs:147]: @J-Son89 - That's how it's happening right now. All the fetching tokens, and collectibles and checking recent history are happening upon success call of get-accounts.

> @smohamedjavid the problem in this PR is not about the loading state, but not having the account cards to display as loading, so what happens is like the below screenshot (you can also https://github.com/status-im/status-mobile/pull/20297#issue-2330187160 here)

Thanks for the explanation @OmarBasem  🙏 

I see what you mean. Since we take the user to the shell tab immediately after login (while we wait for the account's data), this issue is most likely to be experienced. There is no loading screen after login like the desktop app which gives a user some UI to look at while we prepare the data for them.

Additionally, I looked at the issue https://github.com/status-im/status-mobile/issues/20275, the accounts data we get from status-go is the bare minimal data. We can look into other areas such as assets for each account to check for performance bottlenecks. 👍

**Review by ulisesmac — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @OmarBasem !

Thanks for your PR.

I see that zero still appears before loading state but you was working on it here https://github.com/status-im/status-mobile/pull/20297#issue-2330187160
Please let me show you how it looks : 


https://github.com/status-im/status-mobile/assets/147824399/5e9ca906-9c81-44d7-95d2-e1e0176572af

Please, let me know if it is a correct behaviour or not. 
Thanks!

**Comment by OmarBasem** [comment]
Thanks for your testing @mariia-skrypnyk. It seems the issue was re-introduced by a recently merged PR. It should be fixed now.

**Comment by mariia-skrypnyk** [comment]
Thanks @OmarBasem !
Fixed now.

Will rerun e2e and let you know.

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Tested and now it is good!
Thanks!
Can be merged!
