### PR TITLE
[#17507] fix: image placeholder issue in create-profile

### LINKED ISSUE #17507: Image/image placeholder stops being displayed after background on the "Create profile" screen [iOS]
# Bug Report

## Problem 

Screenshot 2023-10-04 at 12 14 03

https://github.com/status-im/status-mobile/assets/67952253/d007d69d-e4b3-41b5-a70c-5e0f8f6bcf60

### Reproduction

1. Install Status on your iOS device
2. On the intro screen lock the device screen/send the app to background
3. Wait ~ 2 munites
4. Open the app
5. Press `I'm new to Status` > `Generate keys`

or

1. Install Status on your iOS device
2. On the `Create profile` screen lock the device screen/send the app to background
3. Wait ~ 2 munites
4. Open the app
5. Go back
6. Press `Generate keys`

### Additional Information

- Status version: nightly 4/10
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17507

Reproduction

1. Install Status on your iOS device
2. On the intro screen lock the device screen/send the app to background
3. Wait ~ 2 munites
4. Open the app
5. Press I'm new to Status > Generate keys

it was hard to reproduce but now it should be fine, i noticed sometime the port has been missed for mediaserver ,so i try to avoid calling mediaserver when user doesn't have any avatar there

status: ready

### CODE REVIEW

File: src/status_im2/contexts/onboarding/create_profile/view.cljs [hunk 1]
```diff
@@ -171,11 +171,7 @@
                                        {:content (fn []
                                                    [method-menu/view on-change-profile-pic])
                                         :shell?  true}]))
-              :image-picker-props  {:profile-picture     (or
-                                                          @profile-pic
-                                                          (rf/sub
-                                                           [:profile/onboarding-placeholder-avatar
-                                                            @profile-pic]))
+              :image-picker-props  {:profile-picture     @profile-pic
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/create_profile/view.cljs:175]: hmm, is this right? the sub is there because we want to hydrate the data if the user navigates backwards. 
e.g user sets profile picture, then user navigates forward to create password, then user navigates back to create profile page ->
expected the profile picture should be set as before 👍

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/onboarding/create_profile/view.cljs:175]: Thanks @J-Son89  as I checked if you go to next screen (set password) and the click on back button you still can see the selected avatar photo. please let me know if i should check any other scenario 

https://github.com/status-im/status-mobile/assets/71308738/e52099ab-8c0b-4b76-84a4-1ba61f890d08

Comment (yqrashawn) [reply src/status_im2/contexts/onboarding/create_profile/view.cljs:175]: hi, the `or` logic here is for rendering initial avatars when no image set 
https://github.com/status-im/status-mobile/blob/b70a6c300eef969a7665d22281ba98ec470d1efb/src/status_im2/subs/profile.cljs#L27

I believe this will break initial avatar

Comment (yqrashawn) [reply src/status_im2/contexts/onboarding/create_profile/view.cljs:175]: The reason for the issue might be (just a guess) image server port changed when back to foreground. media server before login is started at https://github.com/status-im/status-go/blob/21ddaa4b9f57288ed99fed04db528f3790b7bd2f/node/get_status_node.go#L210

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/onboarding/create_profile/view.cljs:175]: @yqrashawn yes as i mentioned the issue is related to the port but i can't see any issue with this changes as `user-avatar` already handled initial avatar according to full-name.
```
(if (and full-name (not (or profile-picture-fn profile-picture)))
       [initials-avatar props]
...
```

Comment (yqrashawn) [reply src/status_im2/contexts/onboarding/create_profile/view.cljs:175]: oh, i see

**Review by yqrashawn — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
Hey @VolodLytvynenko i moved this PR to E2E test step but it didn't run them, JFYI

**Comment by VolodLytvynenko** [comment]
> Hey @VolodLytvynenko I moved this PR to E2E test step but it didn't run them, JFYI

Hi @mohsen-ghafouri The e2e run still in process. Sometimes it happens if a few PRs are moved to E2E at the same time which might cause the queue. 
image
The e2e  queue you can check [here](https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs/)

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri thank you for your work. Issues in e2e are not related to the current PR. Ready to be merged

**Review by J-Son89 — APPROVED** [review]
