### PR TITLE
Fix invalid schemas

### LINKED ISSUE #19537: Fix invalid malli schemas
# Bug Report

## Problem 
Across the app we have some malli schemas that are invalid showing up in the logs:

Some that I caught are in:
- `quo.components.wallet.token-input.schema`
```clj
ERROR Failed to instrument function {:schema-id quo.components.wallet.token-input.view/view-internal,
 :error
 #error {:message ":malli.core/child-error", :data {:type :malli.core/child-error, :message :malli.core/child-error, :data {:type :maybe, :properties nil, :children [:string :keyword], :min 1, :max 1}}},
 :function #'quo.components.wallet.token-input.view/view-internal}
```
- `status-im.contexts.communities.actions.accounts-selection.effects`
```clj
ERROR [status-im.contexts.communities.actions.accounts-selection.effects:?] - Failed to instrument function {:symbol
 #object[status_im$contexts$communities$actions$accounts_selection$effects$sign_and_call_endpoint],
 :error
 #error {:message ":malli.core/invalid-schema", :data {:type :malli.core/invalid-schema, :message :malli.core/invalid-schema, :data {:schema #object[cljs$core$object_QMARK_]}}}}
```
#### Expected behavior
1. no invalid malli schemas

#### Actual behavior
1. errors with invalid malli schemas

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19537

### Summary

Fix invalid malli schemas

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/actions/accounts_selection/effects.cljs [hunk 1]
```diff
@@ -81,7 +81,7 @@
    [:cat
     [:map {:closed true}
      [:community-id string?]
-     [:password [:maybe [:or string? object?]]]
+     [:password [:maybe [:or string? security/?masked-password]]]
```
Comment (ibrkhalil) [inline src/status_im/contexts/communities/actions/accounts_selection/effects.cljs:84]: Thanks for this, I had no idea what's the type of the password to use in my PR.

**Review by ibrkhalil — APPROVED** [review]
Merge away!

**Review by J-Son89 — APPROVED** [review]
