### PR TITLE
Fix edit message 

### LINKED ISSUE #13726: UI Component - Editing
This issue is to track the creation of the component: Editing

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=4170%3A78081

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #13726 

### Summary

Fix edit message implementation which was broken after implementing the new message input

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Open a chat
- Long tap on a message
- Select "Edit message"
- Edit a message and send

status: ready

### CODE REVIEW

File: src/status_im/ui2/screens/chat/composer/input.cljs [hunk 1]
```diff
@@ -137,13 +139,56 @@
...
+         (assoc-in [:chat/inputs-with-mentions chat-id] hydrated-mentions)
+         (assoc-in [:chats/mentions chat-id :mentions] info))}))
+
 (defn text-input [{:keys [set-active-panel refs chat-id sending-image on-content-size-change]}]
   (let [cooldown-enabled? (<sub [:chats/current-chat-cooldown-enabled?])
         mentionable-users (<sub [:chats/mentionable-users])
         timeout-id (atom nil)
         last-text-change (atom nil)
         mentions-enabled (get @mentions-enabled chat-id)]
-
```
Comment (ibrkhalil) [inline src/status_im/ui2/screens/chat/composer/input.cljs]: Unnecessary change maybe ?

**Review by ibrkhalil — APPROVED** [review]
Looks beautiful to me

**Comment by VolodLytvynenko** [comment]
Hi, @briansztamfater thank you for PR!
 Please, rebase it to the current develop

File: src/status_im/ui2/screens/chat/components/edit/view.cljs [hunk 2]
```diff
@@ -0,0 +1,27 @@
+(ns status-im.ui2.screens.chat.components.edit.view
+  (:require [re-frame.core :as rf]
+            [react-native.core :as rn]
+            [quo2.foundations.colors :as colors]
+            [quo2.components.icon :as icons]
+            [quo2.components.markdown.text :as text]
+            [quo2.components.buttons.button :as button]
+            [status-im.i18n.i18n :as i18n]
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/components/edit/view.cljs]: [i18n.i18n :as i18n]

File: src/status_im/ui2/screens/chat/components/edit/view.cljs [hunk 3]
```diff
@@ -0,0 +1,27 @@
+(ns status-im.ui2.screens.chat.components.edit.view
+  (:require [re-frame.core :as rf]
+            [react-native.core :as rn]
+            [quo2.foundations.colors :as colors]
+            [quo2.components.icon :as icons]
+            [quo2.components.markdown.text :as text]
+            [quo2.components.buttons.button :as button]
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/components/edit/view.cljs]: use quo2.core

File: src/status_im/ui2/screens/chat/components/edit/view.cljs [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+            [status-im.i18n.i18n :as i18n]
+            [status-im.ui2.screens.chat.components.edit.style :as style]))
+
+(defn edit-message []
+  [rn/view {:style style/container}
+   [rn/view {:style style/content-container}
+    [icons/icon :i/connector {:size            16
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/components/edit/view.cljs]: quo/icon

File: src/status_im/ui2/screens/chat/components/edit/view.cljs [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+                              :color           (colors/theme-colors colors/neutral-40 colors/neutral-60)
+                              :container-style style/icon-container}]
+    [rn/view {:style style/text-container}
+     [text/text {:weight :medium
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/components/edit/view.cljs]: quo/text

File: src/status_im/ui2/screens/chat/components/edit/view.cljs [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+                 :size   :paragraph-2}
+      (i18n/label :t/editing-message)]]]
+   [button/button {:width               24
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/components/edit/view.cljs]: quo/button

File: src/quo2/foundations/colors.cljs [hunk 7]
```diff
@@ -91,6 +91,11 @@
 (def white-opa-90 (alpha white 0.9))
 (def white-opa-95 (alpha white 0.95))
 
+;;;;Black
+
+;;Solid
+(def black "#000")
```
Comment (J-Son89) [inline src/quo2/foundations/colors.cljs]: hmm, did you double check with the design team that we want this and it's not just something that was left over when they adjusted the colors?

File: src/status_im/ui2/screens/chat/components/edit/style.cljs [hunk 8]
```diff
@@ -0,0 +1,26 @@
+(ns status-im.ui2.screens.chat.components.edit.style)
+
+(def container
+  {:flex-direction      :row
+   :height              24
+   :accessibility-label :edit-message})
```
Comment (J-Son89) [inline src/status_im/ui2/screens/chat/components/edit/style.cljs]: hmm I don't think `accessibility-label` is part of `style` prop.
imo things that go in style.cljs files should not be anything outside of - style props https://reactnative.dev/docs/view-style-props

So in your component it should be:

```
style.cljs
(def container
  {:flex-direction      :row
   :height              24})
   
  view.cljs 
[rn/view {
 :style style/container
 :accessibility-label :edit-message
}
```
cc @OmarBasem , @ilmotta , @flexsurfer wdyt?

Comment (flexsurfer) [reply src/status_im/ui2/screens/chat/components/edit/style.cljs]: yes its not, it should be outside styles

File: src/status_im/ui2/screens/chat/composer/input.cljs [hunk 9]
```diff
@@ -137,13 +139,56 @@
...
+ :set-input-text
+ (fn [[chat-id text]]
+    ;; We enable mentions
+   (swap! mentions-enabled assoc chat-id true)
+   (on-text-change text chat-id)
+    ;; We update the key so that we force a refresh of the text input, as those
+    ;; are not ratoms
+   (force-text-input-update!)))
+
+(fx/defn set-input-text
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/composer/input.cljs]: There's quite a bunch of important things happening in this event handler. To paraphrase the re-frame docs:

> Event Handlers - most of your testing focus will be here because this is where most of the logic lives
> Subscription Handlers - often not a lot to test here. Only [Layer 3](https://github.com/day8/re-frame/blob/master/docs/subscriptions.md) subscriptions need testing.

In the end, I think we should strive to at least write tests for things that touch the app db, especially for non-trivial event handlers like this one. Another way of helping with testability of this event handler is to extract the data processing logic to a separate function and unit test it.

File: src/status_im/ui2/screens/chat/components/edit/style.cljs (hunk 8 above)
Comment (briansztamfater) [reply src/status_im/ui2/screens/chat/components/edit/style.cljs]: Of course you are right, left over, will remove it

File: src/quo2/foundations/colors.cljs (hunk 7 above)
Comment (briansztamfater) [reply src/quo2/foundations/colors.cljs]: I'll double check with the design team :)

File: src/status_im/ui2/screens/chat/composer/input.cljs (hunk 9 above)
Comment (briansztamfater) [reply src/status_im/ui2/screens/chat/composer/input.cljs]: Yeah, actually I just moved this event handler from the old input component to the new one, and I need a bit more understanding of why (and if) this is needed, because it has mostly logic for mentions (which is not part of this issue, so maybe it could be simplified, but IDK if this is something needed for mentions in the redesign or if the logic will change, so probably we don't want to spend extra energy on figuring this out at this stage / PR).

Currently what matters for this fix is the `set-input-text` `fx` which forces the text input to update, so I removed that event handler and update the code to trigger it from other event handler (`:chat.ui/edit-message`).

If we need the mentions logic we can add it and refactor it, need to check if we have issues created and designs for mentions. I will create them if we don't have them.

Comment (ilmotta) [reply src/status_im/ui2/screens/chat/composer/input.cljs]: Okay, I understand the context now @briansztamfater, and thanks for creating related issues o/

May I give a suggestion to help reviewers understand the scope of the PR? If the code being added is mostly a copy of something, we can let reviewers know by adding an FYI Github comment or just a quick explanation on the PR description. This way reviewers can better judge when to suggest improvements.

File: src/status_im/ui2/screens/chat/composer/input.cljs [hunk 10]
```diff
@@ -137,13 +137,28 @@
...
+(defn force-text-input-update!
+  "force-text-input-update! forces the
+  input to re-render, necessary when we are setting value"
+  []
+  (swap! chat-input-key inc))
+
+(re-frame/reg-fx
+ :set-input-text
+ (fn [[chat-id text]]
+    ;; We enable mentions
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/composer/input.cljs]: I think the code is very self-explanatory that we don't need these comments, but it might be just me.

**Review by ilmotta — APPROVED** [review]

File: src/quo2/foundations/colors.cljs (hunk 7 above)
Comment (briansztamfater) [reply src/quo2/foundations/colors.cljs]: Actually I double checked designs and we are good using `neutral-100`. Just updated PR with this change

File: src/status_im/ui2/screens/chat/composer/input.cljs (hunk 9 above)
Comment (briansztamfater) [reply src/status_im/ui2/screens/chat/composer/input.cljs]: Sure, I'll add a note on the PR in following similar cases. Thanks for the suggestion!

**Comment by VolodLytvynenko** [comment]
Hi, @briansztamfater thank you for the PR. Please, take a look at the following issues.
Could you please also rebase to the latest develop?

**ISSUE 1: The [x] button is not tappable if too much text is trying to be edited**

**Steps to reproduce:**
1. Go to any chat
2. Send a message in the chat (the text  of the message should contain at least 1500 chars)
3. Tap 'edit' on the 
4. Try to tap [x] button

**Actual result:**
The button is not tappable
https://user-images.githubusercontent.com/52490791/203529797-b6e284b8-eb40-4166-87c2-9ace0004f7e0.mp4


**Expected result:**
The button is tappable

**ENV:**  1) Device: Galaxy S21. OS: 11

**ISSUE 2: The input textbox is shown fully on the screen after [x] is tapped within a long  message**

**Steps to reproduce:**
1. Go to any chat
2. Send a message in the chat (the text  of the message should contain at least 500 chars)
3. Tap 'edit' on the 
4. TTap [x] button

**Actual result:**
The input is shown on the whole screen after [x] is tapped
image

https://user-images.githubusercontent.com/52490791/203533795-e4ee80c0-61c2-48f4-a774-74af794683cc.mp4

**Expected result:**
image

**ENV:** IPhone 11 Pro.  OS: 15

**Comment by briansztamfater** [comment]
Thanks @VladimrLitvinenko for your testing, I'm working on those fixes (and the rebase). Will let you know once done.

**Comment by briansztamfater** [comment]
@VladimrLitvinenko Issues should be fixed now, also rebased to develop. Let me know if something else arises. Thanks!

**Comment by VolodLytvynenko** [comment]
Hi @briansztamfater thank  you for the fixes
Some issues are still reproduced

**ISSUE 1: The [x] button is not tappable if too much text is trying to be edited**

**Steps to reproduce:**
1. Go to any chat
2. Send a message in the chat (the text of the message should contain at least 1500 chars)
3. Tap 'edit' button on the current message
4. Try to tap [x] button

**Actual result:**
The button is not tappable
https://user-images.githubusercontent.com/52490791/203966021-7321db63-e112-4a97-848e-a4cb001c873f.mp4


**Expected result:**
The button is tappable

**ENV:** 
list of devices:
- **Device:** Samsung Galaxy S20 **OS:** 10
- **Device:**  Redmi Note 11 **OS:** 11
-  **Device:** Google Pixel 7 **OS:** 13

**ISSUE 2 The [x] button is shifted to the upper corner**
1. Go to any chat
2. Send a message in the chat (the text of the message should contain at least 1500 chars)
3. Tap 'edit' button on the current message


**Actual result:**
The [x] button is shifted to the upper corner
image

**Expected result:**
image
**ENV:** IPhone 11 Pro. OS: 15

**Comment by briansztamfater** [comment]
Hi @VladimrLitvinenko, thanks for the testing. Added more padding for the maximum height of the bottom sheet, also tested in Android the button issue with these devices and it worked fine:

- Pixel 5 (Emulator) 
- Samsung Galaxy A52 (Android 12)
- Xiaomi Mi 10T (Android 10)

Could you please retest with the latest build? Thanks a lot!

**Comment by VolodLytvynenko** [comment]
@briansztamfater thank you for your work. PR is tested and ready to be merged

**Comment by du82** [comment]
The top bar should be transparent like the space below it

Screenshot_2022-11-25-15-23-56-69_65ad86f86fd2321a85272a99323da10f

**Comment by du82** [comment]
Text is showing up white on white

Screenshot_2022-11-25-15-32-57-10_65ad86f86fd2321a85272a99323da10f

**Comment by VolodLytvynenko** [comment]
@briansztamfater sorry, missed one additional issue. had to return it to the contributor column due it
**ISSUE 3. The text is removed from the input textbox after 'edit' button is tapped when IOS is used**
**Steps to reproduce:**
1. Go to any chat
2. Send a message
3. Edit the message

**Actual result:**
The message disappears after the 'edit' button is tapped

image

**Expected result:**
The message is still shown within the input textbox
image

**ENV:** IPhone 11 pro OS: 15

@briansztamfater could you check also the issue below?  Currently, I see this Is reproducible for this PR, but for today's development it is not broken.
**ISSUE 4 the clear story pop-up is shifted**

**Steps to reproduce:**
1. Create 1-1 chat
2. Go to list of chats
3. Tap on the created chat and hold unless modal will be shown
4. Tap 'clear history' button

**Actual result:**
The clear history pop up is shifted
image

**Expected result:**
image

**ENV:** Both android and IOS

**Comment by briansztamfater** [comment]
@VladimrLitvinenko issues should be fixed now (hopefully) just updated could you re-test? Let me know if something else arises during testing.

**Comment by VolodLytvynenko** [comment]
> Text is showing up white on white
> 
> Screenshot_2022-11-25-15-32-57-10_65ad86f86fd2321a85272a99323da10f

Hi, @du64 . It looks like a high priority issue. Thank you for your notice. But couldn't be able to reproduce it.
Could you provide more details? Which device do you use?

**Comment by VolodLytvynenko** [comment]
@briansztamfater PR is tested and ready to be merged. Thank you!

**Comment by VolodLytvynenko** [comment]
@briansztamfater Just a quick reminder regarding the process on the board: when PR is ready for testing (either after initial work or after some bug fixes), you can also move it from CONTRIBUTOR column back to E2E or REVIEW (if PR requires Review) column. QAs are monitoring PRs from E2E column and take it into test if it is approved and has request-manual-qa label. Also, for those PRs that return after bug fixes you can remove label Tested-Issues which is set by QAs before moving PR with bugs to CONTRIBUTOR column. Thank you!

File: src/status_im/ui2/screens/chat/composer/view.cljs [hunk 11]
```diff
@@ -160,6 +162,12 @@
                                       (reanimated/set-shared-value bg-opacity (reanimated/with-timing 0)))
                                     (reanimated/set-shared-value translate-y (reanimated/with-timing (- y)))
                                     (reanimated/set-shared-value shared-height (reanimated/with-timing (min y max-height)))))
+              (quo.react/effect! #(when (and (not edit) (= (:state @context) :max))
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/composer/view.cljs:165]: this looks weird, why is it separate effect, i see that we set same properties twice, but with different values , im not sure how it will work

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/ui2/screens/chat/composer/view.cljs (hunk 11 above)
Comment (flexsurfer) [reply src/status_im/ui2/screens/chat/composer/view.cljs:165]: ok too late

Comment (flexsurfer) [reply src/status_im/ui2/screens/chat/composer/view.cljs:165]: but still we need to address that

**Comment by flexsurfer** [comment]
@VladimrLitvinenko @briansztamfater seems like after this PR was merged, there are some bugs
