### PR TITLE
Bottom of scrollable area hidden by nav bug (#635)

### LINKED ISSUE #635: Bottom of scrollable area hidden by nav
We should pad this so you can scroll/see full list even if just hidden.

97069e800f190afe1070d9213e1e2d70_original

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/100

### PR DESCRIPTION
**Pull request by flexsurfer**
one more magic number, can't find why react-native-swiper positioned wrong
fix #635

### CODE REVIEW

File: src/status_im/discover/styles.cljs [hunk 1]
```diff
@@ -26,9 +26,6 @@
 (def section-spacing
   {:padding 16})
 
-(def scroll-view-container
-  {:bounces false})
-
 ;; Popular
```
Comment (flexsurfer) [inline src/status_im/discover/styles.cljs]: fix for https://github.com/status-im/status-react/issues/694
