### PR TITLE
fix(wallet): Remove redirection to "send flow" when the user scans an address QR code

### LINKED ISSUE #20972: User redirected to confirmation page instead of 'Send to' page during collectible sending
### Steps:
1. Scan wallet QR using universal scanner
2. Go to a transaction confirmation page
3. Go back to wallet main page
4. Open collectible -> tap 'send' button

### Actual result:
The user is redirected to the confirmation page, skipping the 'send to' page.

https://github.com/user-attachments/assets/fadd5a4e-787c-4edb-af11-ffbc13b348b3

### Expected result:

The user should be redirected to the 'send to' page.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
- 
### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/16521185/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20972 

### Summary

The new flow looks as follows:

https://github.com/user-attachments/assets/da8abbd2-3e2c-4fa9-acae-4969e3133510

### Review notes
The previous implementations has been commented out because we may fix it in the future.

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Scan a QR code from another wallet address
- Press on copy
- Close the modal

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

File: src/test_helpers/unit.cljs [hunk 1]
```diff
@@ -12,9 +12,10 @@
     [re-frame.events :as rf-events]
     [re-frame.registrar :as rf-registrar]
     [re-frame.subs :as rf-subs]
-    [taoensso.timbre :as log] ;; We must require this namespace to register the custom cljs.test
-                              ;; directive `match-strict?`.
+    [taoensso.timbre :as log]
     test-helpers.matchers))
+;; We must require `test-helpers.matchers` this namespace to register the custom cljs.test
```
Comment (shivekkhurana) [inline src/test_helpers/unit.cljs:17]: This comment is messing up with my linter 🙃

File: src/status_im/contexts/shell/qr_reader/sheets/scanned_wallet_address.cljs [hunk 2]
```diff
@@ -1,33 +1,40 @@
...
+(defn- on-press
+  [address]
+  ;; Originally, the flow went to the send flow, but it has been removed to avoid bugs. Please check
+  ;; https://github.com/status-im/status-mobile/issues/20972. The previous code has been commented
+  ;; out.
+  (clipboard/set-string address)
+  (rf/dispatch [:toasts/upsert
+                {:type :positive
+                 :text (i18n/label :t/address-copied)}])
+  #_(let [[_ split-address] (network-utils/split-network-full-address address)]
```
Comment (vkjr) [inline src/status_im/contexts/shell/qr_reader/sheets/scanned_wallet_address.cljs]: If we want to leave the commented piece in the code for future use, I'd suggest to make refactoring that will help next developer to understand what happens:
- rename `on-press` to more meaningful `copy-address`
- create `send-to-address` handler, move there old sending code and comment it out
- leave `send` menu option in action-drawer with `:on-press send-to-address` but comment it out

With these changes the future developer will quickly grasp what is going on here and will need only to uncomment things to get it back to work, wdyt?

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for PR. No issues from my side. PR is ready to be merged

File: src/status_im/contexts/shell/qr_reader/sheets/scanned_wallet_address.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/contexts/shell/qr_reader/sheets/scanned_wallet_address.cljs]: Thanks for the suggestion @vkjr
