### PR TITLE
Profile with ENS fixes

### LINKED ISSUE #20511: ENS name not applied after local pairing the account from status-desktop
# Problem

I use `sirotin.eth` ENS name with my account in status-desktop. I used local pairing to pair this account with mobile app. 

After pairing, my display name on mobile is `sirotin.eth`. But
- the identicon ring is there
- I'm able to edit the display name, as it wouldn't be an ENS name

IMG_3721

But I see that there is ENS support in general. `ducheng.eth` doesn't have an identicon ring:
IMG_3724

# App info

App version: `2.29.20425 (20240617141826)`
App commit: c20a2da267973f7403655fe4524dfc9bd4a8fbcd
Node version: `StatusIM/v0.180.30/ios-arm64/go1.21.8`

### LINKED ISSUE #20616: User can override ENS name
# Bug Report

## Problem 

A user should not be able to override the Profile name if the account has a ENS name set.

Note: parent issue where the bug was reported https://github.com/status-im/status-mobile/issues/20511

#### Expected behavior

We haven't implemented ENS management in the mobile app (see in [Figma](https://www.figma.com/design/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?node-id=5009-307275&t=n5GiM01GJYdtz3LB-0)), which would give mobile users more flexibility, hence the best we should offer now to avoid erroneous behavior is to disallow users from editing the Profile name when the ENS name exists.

The simplest solution is to make the `Name` field non-pressable and and to hide the `:i/chevron-right` icon.

#### Actual behavior

User can edit the name even when ENS name exists.

### Reproduction

1. Sync from desktop with an account with ENS name.
2. Go to `Profile > Edit Profile > Name`
3. Edit the Profile name.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #20616
fixes #20511

### Summary

This PR:
 - fixes profile with ENS can edit their name
 - fixes identicon ring is shown for the profile with ENS
 - updates the profile URL for the profile with ENS to `https://status.app/u/CwSACgcKBUphdmlkAw==#zQ3shv264Sq3zcK8smDNJXxmrjfpdyvd5FPHEm2zHb7cXgjwR` as `https://status.app/u#<ENS_NAME>.eth` is NOT resolved by the [status-go](https://github.com/status-im/status-go/blob/48ebe24f8e986c174e8e933404b81a7d6a3beb3e/protocol/messenger_share_urls.go#L429-L432). Desktop app uses normal URL with data (not the URL with ENS) for ENS profiles.

| Before | After |
| --- | --- | 
|  |  | 
|  |  | 
#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Create/restore a profile with ENS (Sync profile with Desktop or upgrade an ENS user from v1 to v2)
- Navigate to `Profile` and verify the Identicon ring is not shown
- Navigate to `Profile > Edit profile` and verify the name is not editable
- Share a link to your profile and verify it is resolved when you paste it in chats or open it in the browser

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/common/validation.cljs [hunk 1]
```diff
@@ -1,7 +1,8 @@
 (ns status-im.contexts.wallet.common.validation
-  (:require [status-im.constants :as constants]))
+  (:require [clojure.string :as string]
+            [status-im.constants :as constants]))
 
-(defn ens-name? [s] (boolean (re-find constants/regx-ens s)))
+(defn ens-name? [s] (if (string/blank? s) false (boolean (re-find constants/regx-ens s))))
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/common/validation.cljs]: Nitpick: could use `and`:

```clojure
(and (not (string/blank? s))
     (boolean (re-find constants/regx-ens s)))
```

File: src/status_im/common/universal_links.cljs [hunk 2]
```diff
@@ -178,13 +178,15 @@
   [{:keys [db]} [{:keys [public-key on-success]}]]
   (let [profile-public-key (get-in db [:profile/profile :public-key])
         profile?           (or (not public-key) (= public-key profile-public-key))
-        ens-name?          (if profile?
-                             (get-in db [:profile/profile :ens-name?])
-                             (get-in db [:contacts/contacts public-key :ens-name]))
+        ;; ens-name?          (if profile?
```
Comment (ilmotta) [inline src/status_im/common/universal_links.cljs]: @smohamedjavid, what is the intention in keeping code and some unit tests commented in this PR? Would help if we had a comment explaining why we keep the dead code, but even better would be to delete all this code and remove disabled tests and create a GH issue.

**Review by ilmotta — APPROVED** [review]

File: src/status_im/common/universal_links.cljs (hunk 2 above)
Comment (smohamedjavid) [reply src/status_im/common/universal_links.cljs]: I just left it in case we bring it back later, but it looks like it will not happen anytime soon (until the ENS code is refactored in status-go). I will remove it as it's a small code update. 👍

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM :)

**Review by seanstrom — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid could you please rebase current PR and resolve existing conflicts?

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid, thank you for the PR. I'm not sure about the full scope of this PR, but I wanted to report additional 2 issues related to ENS resolving. If these are not related to this PR, it can be merged as is

## ISSUE 1: ENS Name and Identicon rings not resolved on the login page
### Steps:
1. Recover a user with an ENS  name.
2. Navigate to the login page.

### Actual Result:
The display name is shown instead of the ENS name.
Identicon rings are incorrectly displayed on the login page.

https://github.com/user-attachments/assets/d2240f90-61e7-4a16-a176-e11c4819be7d

### Expected Result:
The ENS name should be resolved and displayed on the login page.
Identicon rings should not be shown on the login page.

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: The ENS is not resolved for receiver

### Steps:
1. Recover `User A` with an ENS name.
2. Send a message from `User A` to `User B` in any chat.
3. Check the resolving of `User A's` ENS name from `User B's` perspective.

### Actual result:
User B sees the display name of User A instead of the ENS name.

https://github.com/user-attachments/assets/bb4cb5ba-4ea8-4a9f-b738-4c3cf4829cd1

### Expected result:
User B should see User A's ENS name correctly resolved instead of the display name.


### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by smohamedjavid** [comment]
Hey @VolodLytvynenko - Thanks for testing the PR 🙏 I have rebased & resolved the conflicts.

> thank you for the PR. I'm not sure about the full scope of this PR, but I wanted to report additional 2 issues related to ENS resolving. If these are not related to this PR, it can be merged as is

The PR addresses (fixes) only the issues mentioned in the description. About the issues discovered

> ISSUE 1: ENS Name and Identicon rings not resolved on the login page

This requires some update on status-go as the ENS name of the profile is not sent to UI before login.

> ISSUE 2: The ENS is not resolved for receiver

We can check this issue later in a follow-up as I believe this is something with recovered accounts.

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. No issues from my side. PR is ready to be merged
