### PR TITLE
Clear amount when switching assets

### LINKED ISSUE #4852: Wrong amount can be sent after scanning QR code if token was selected as Asset (0.0000555 instead of 555 ETH is sent)
===========
### Description

*Type*: Bug

*Summary*: Wrong amount, e.g. 0.0000555 instead of 555 ETH will be sent if:
1. provide 555 and WGN token in Send transaction screen
2. scan QR code for Recipient (as a result, Asset will be changed to ETH  and warning is shown - it's expected). Note that amount is not changed and is still 555
3. sign transaction. it should be not possible as user does not have 555 ETH in the wallet but it's possible now
As a result, 0.0000555 ETH is sent while Send transaction screen shown 555 ETH
see from 00:17 https://app.testfairy.com/projects/4803622-status/builds/8500248/sessions/4394435878/?accessToken=QHEA6HwwwQskN25rePuvOY-a3YY

#### Expected behavior
1. if there is not enough funds: Validation error is shown that there is insufficient funds. 
2. if there is enough funds then correct amount is sent, same as typed in Amount field (so 555 not 0.0000555)

#### Actual behavior
0.0000555 ETH is sent when Amount field shows 555 and user has only 0.1 ETH
 

### Additional Information
* Status version: nightly build June 20
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8500248/sessions/4394435878/?accessToken=QHEA6HwwwQskN25rePuvOY-a3YY">TestFairy: Status 0.9.21 (6078) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #4852 

### Summary:

Whenever we scan recipient through QR code, symbol is always set to ETH (due to compatibility issue, we have to retain such behaviour), so whenever some other symbol/amount was selected before, we have to clear it - it makes no sense to that anyone would send 500 `SNT` to some person he/she has in mind, scans the person QR code, which changes the symbol to `ETH` (unexpected action for user) and he/she would still want to sent the same amount with different symbol... that's downright dangerous and it's always safer to just clear the amount whenever scanning QR code produces symbol change.

### Testing notes (optional):
test that #4852 is not happening anymore

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
lgtm

**Review by cammellos — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]
lgtm

File: src/status_im/ui/screens/wallet/choose_recipient/events.cljs [hunk 1]
```diff
@@ -35,16 +35,20 @@
       (when (ethereum/address? s)
         {:address s :chain-id chain-id})))
 
-(defn changed-asset-warning [cofx old-symbol new-symbol]
-  (assoc-in cofx [:db :wallet :send-transaction :asset-error]
-            (i18n/label :t/changed-asset-warning {:old old-symbol :new new-symbol})))
+;; NOTE(janherich) - whenever changing assets, we want to clear the previusly set amount/amount-text
+(defn changed-asset [fx old-symbol new-symbol]
+  (-> fx
+      (assoc-in [:db :wallet :send-transaction :amount] nil)
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/choose_recipient/events.cljs:41]: might be `(update-in [:db :wallet :send-transaction] dissoc :amount :amount-text)` for first two forms,
or just
```clojure
(update-in fx [:db :wallet :send-transaction] assoc
           :amount nil
           :amount-text nil
           :asset-error (i18n/label :t/changed-asset-warning {:old old-symbol :new new-symbol}))
```

**Review by rasom — APPROVED** [review]
