### PR TITLE
fix wrong community logo position when scrolling down the channel list

### LINKED ISSUE #20391: [Android] Wrong community logo position when scrolling down the channel list
# Bug Report

### Reproduction

1. Open a community with lots of channels
2. Scroll down to the position when the community banner is hidden

#### Actual behavior

Screenshot 2024-06-07 at 10 39 51

#### Expected behavior

https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=15105-144017&t=ZvLvcs3t338WXdln-4

Screenshot 2024-06-07 at 10 40 04

### Additional Information

- Status version: nightly 7/06
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20391

### Summary
Related to: https://github.com/status-im/status-mobile/pull/19943
For aligning networks in center we modified page-nav component and that also changed position in other screens (community-log)

### Testing
Please let me know if position is broken in any of the screen where logo/component in page-nav supposed to align in center
Ex.
image

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/common/account_switcher/view.cljs [hunk 1]
```diff
@@ -35,6 +35,7 @@
       :on-press            on-press
       :accessibility-label accessibility-label
       :networks            networks
+      :align-center?       true
```
Comment (Parveshdhull) [inline src/status_im/contexts/wallet/common/account_switcher/view.cljs:38]: Please feel free to suggest better name, I am out of ideas.

**Review by jo-mut — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @Parveshdhull !

Thanks for your fix!
I've checked places that could be affected and all looks good.
Hope nothing missed.

Failed e2e are not related to your PR and it can be merged.
