### PR TITLE
[16827] Disable transparent video looping

### LINKED ISSUE #16827: Extra frames at the end of the "Generating keys" animation
# Bug Report

The issue was originally found and reported by @Francesca-G in [this comment](https://github.com/status-im/status-mobile/pull/16816#pullrequestreview-1556336990). 

One point: I'm not sure that the process of generating and saving keys always takes the same time. In that case, what should we show when one animation cycle is completed?

## Problem 

There's a frame that shouldn't be there at the end of the `key saving` animation, as you can see after the key has been grabbed by the end and goes inside the device the particles appear once again at the end of the animation, for a couple of frames.

https://github.com/status-im/status-mobile/assets/122543089/d5728659-0b11-4289-995e-6662ca549684

The animation should end here:
IMG_0292

### Additional Information

- Status version: nightly 1/08
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16827 
status: ready

### CODE REVIEW

**Review by briansztamfater — APPROVED** [review]

File: src/status_im2/contexts/onboarding/generating_keys/view.cljs [hunk 1]
```diff
@@ -125,7 +125,8 @@
      :container-style   {:top  40
                          :left 20}
      :layers            (:generate-keys resources/parallax-video)
-     :disable-parallax? true}]
+     :disable-parallax? true
+     :enable-looping?   false}]
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: nit: this feels slightly odd to me, because here the default of something called `enable-*` is "true", so it's already set and in essence the prop is more to disable then enable. 
imo it should be defaulted to `false` and we have to set it to "true" or the name of the prop should be `disable-looping?`

Comment (ibrkhalil) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: We need to default is to true, Because in every other implementation that we have for the transparent video it is looping.

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: Yes but in the sake of a (in my opinion) coherent api I would say this is worth it.
Additionally we can just change the name of the prop so that it suits the use case here since we are also creating the package. 
It's a minor detail but imo details like this add value. 
Cc @briansztamfater

Comment (ibrkhalil) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: The prop name on the native side is `loop`, And we can name the CLJS one as we please.
We can call it `disable-label?` and on the prop negate it.
Doing that now

Comment (ibrkhalil) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: Just realized, It'll be more confusing xD
```clj 
:loop   (not disable-looping?)
```

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: ah got it. cool, thanks @ibrkhalil!

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: I mean, we can just enable looping on the 2 uses where it is used too

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: mostly my concern was with the package, so whatever you go with is fine. I see now that the real api is `loop` 👍

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/onboarding/generating_keys/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: Created a PR [here](https://github.com/status-im/react-native-transparent-video/pull/5) to rename it

Comment (ibrkhalil) [reply src/status_im2/contexts/onboarding/generating_keys/view.cljs:129]: I think I'll make that PR a draft for now, And we can continue this task

**Comment by qoqobolo** [comment]
Hey @ibrkhalil, thanks for the fix, looks good to me!
Passing the PR on to Francesca for design review 👁️ 👁️

**Review by Francesca-G — APPROVED** [review]
