### PR TITLE
[fix #3091] fix edit group chat contact list

### LINKED ISSUE #3091: Error undefined is not a function (evaluating 'i(e)') shown when tapping more link in group chat
### Description

*Type*: Bug

*Summary*: Having more than 4 member in a group chat I can go to settings and should be able to view all members in the chat by tapping `more` link. When I do that i receive an error `undefined is not a function (evaluating 'i(e)')`

#### Expected behavior
List of members can be viewed

#### Actual behavior
image

### Reproduction

- Open Status
- Create goup chat with more than 4 memers
- Open this group chat
- Tap chat avatar
- Tap settings
- Tap `more` link

### Additional Information
* Status version: release 0.9.13, also happens in last develop  0.9.11d598 (2155) 
* Operating System: Android, iOS
* https://app.testfairy.com/projects/4803590-status/builds/7533374/sessions/6/?accessToken=-7E6IbEAUAi9fQOFRObSo/qeJ9o

### PR DESCRIPTION
**Pull request by dmitryn**
Fixes #3091 

### Summary

Fixes screen group chat contacts list edit.

Renames `renderRow` attribute to `render-fn` to comply with `flat-list` accepted attributes.

Please refer to #3091 for the details.

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/group/edit_contacts/views.cljs [hunk 1]
```diff
@@ -23,11 +23,10 @@
   [react/view {:flex 1}
    [list/flat-list {:data                      contacts
                     :enableEmptySections       true
-                    :renderRow                 (fn [contact]
-                                                 [contact-view {:contact        contact
-                                                                :extended?      extended?
-                                                                :extend-options (extend-options contact)}])
-
+                    :render-fn (fn [contact]
```
Comment (yenda) [inline src/status_im/ui/screens/group/edit_contacts/views.cljs]: @dmitryn nice but fix the style please

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
Branch: PR-3107
Android: https://i.diawi.com/un52vj
iOS: https://i.diawi.com/rd6sNJ
