### PR TITLE
fix(wallet)_: tx data cleanup after send or bridge tx

### LINKED ISSUE #21767: [Android] Networks are zeroing after going back from bridge setup page
#### Steps to Reproduce:
1. Navigate to the Bridge page.
2. Go back to the previous screen.

### Actual Result:
On the Bridge to screen, networks display zero balances and become disabled.

https://github.com/user-attachments/assets/ddba7d06-abbc-4f41-b417-13609e266ce1

### Expected Result:
Networks should remain enabled and display their correct balances after returning from the Bridge page.

### ENV:
Nightly 6 Dec, 2024

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/18035485/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21767

### Summary

This PR fixes the token/networks going to zero/disabled in the "Bridge to" screen when the user navigates back from the input screen.

### Review notes

The bug is a regression from https://github.com/status-im/status-mobile/issues/21720. This PR reverts part of the changes in #21720 as the TX state cleanup on the amount input page affects the Send/Bridge flow when navigating back from the input amount screen and the navigation glitch on completing the transaction.

This PR fixes original issue #21720 by creating a `div` method with a nil wrap.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to Wallet tab > Account
- Open the Bridge flow and select an asset and network to bridge to
- Navigate back from the input amount page
- Verify the Networks (Bridge to) screen doesn't go to zero/disabled 
- Navigate back to Wallet home
- Verify the Send/Bridge transaction is placed successfully using the input of crypto or fiat amount

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 1]
```diff
@@ -258,8 +258,6 @@
                                              (set-input-state
                                               #(controlled-input/->crypto % conversion-rate)))
                                            (set-crypto-currency (not crypto-currency?)))]
-    (rn/use-unmount
-     #(rf/dispatch [:wallet/clean-up-transaction-flow]))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:262]: On send flow (`To Address -> Asset -> Amount`), if you navigate back from the input amount, it causes a minor recursion bug where the user goes back to Asset and upon selecting the asset, the user is taken to selecting address again as the to address is cleaned up.

File: src/utils/money.cljs [hunk 2]
```diff
@@ -285,10 +285,14 @@
...
   (.round (.mul ^js bn1 bn2) 0))
 
-(defn div
+(defn- div*
   [bn1 bn2]
   (.dividedBy ^js bn1 bn2))
 
+(def div
+  "Divides with defaults, this version is able to receive `nil` and takes them as 0."
+  (fnil div* (bignumber 0) (bignumber 1)))
```
Comment (smohamedjavid) [inline src/utils/money.cljs:294]: Added `fnil` wrapper with 0 and 1 values produces 0 (because 0 divided by 0 will provide **NaN**).

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs:262]: mm good point :+1: . And there's no other screen we can put this in, since the flows can have different entry points. Hopefully we can figure out a way to structure these flows/screens to be able to clean-up on unmount eventually, so we no longer rely on delayed clean-ups when done.

**Review by clauxx — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -629,9 +630,11 @@
 (rf/reg-event-fx :wallet/end-transaction-flow
  (fn [{:keys [db]}]
    (let [address (get-in db [:wallet :current-viewing-account-address])]
-     {:fx [[:dispatch [:dismiss-modal :screen/wallet.transaction-confirmation]]
-           [:dispatch [:wallet/navigate-to-account-within-stack address]]
-           [:dispatch [:wallet/select-account-tab :activity]]]})))
+     {:fx [[:dispatch [:wallet/navigate-to-account-within-stack address]]
+           [:dispatch [:wallet/select-account-tab :activity]]
+           [:dispatch-later
+            [{:ms       20
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/send/events.cljs:635]: Why do we need to delay the cleanup ?

**Review by shivekkhurana — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/events.cljs:635]: As far as I know, this was an existing approach to the delay the cleanup to give time for the screen navigation.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs:262]: I agree, @clauxx. It's a bit tricky. It's not just the delayed cleanup but also the different clean-up events scattered across the screens/flows. We will research this delayed approach and create a solution post 2.32 release 👍

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid thank you for PR. Take a look found issue:

## ISSUE 1: Empty Activity Tab Displayed After Bridge Transaction
### Steps to Reproduce:
1. Long tap asset on wallet main page -> tap bridge
2. Perform a bridge transaction.

### Actual Result:
User is navigated to the empty account: Activity tab which empty; assets are not shown on this account

https://github.com/user-attachments/assets/c1812f15-c7f0-4288-a8c4-17f442723598

### Expected Result:
User is navigated to the account: 
- Within activity tab the transaction is shown

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### logs:
[logs (2).zip](https://github.com/user-attachments/files/18041351/logs.2.zip)

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - [Issue 1](https://github.com/status-im/status-mobile/pull/21770#issuecomment-2523757769) should be fixed now :pray: Can you help me retest?

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. No issues from my side. PR is ready to be merged
