### PR TITLE
[bug] fix #2403 can't recover account

### LINKED ISSUE #2403: Can't recover account , error `invalid arity:2` shown
### Description

*Type*: Bug

*Summary*: Error `invalid arity:2` shown when recovering account in latest develop as well as setting up password

#### Expected behavior
I can recover account either from profile or within `recover` button 

#### Actual behavior
image

image

### Reproduction

- Open Status
- Click Recover button while your new account is setting up
- Go to Main screen within Switch Users and click Recover Access

### Additional Information
* Status version: `0.9.10-352-ga95d1189+` develop
* Operating System: Android, iOS
* https://saucelabs.com/beta/tests/0543673b01f64df5ac78ce935d6a97c7/commands#10

### PR DESCRIPTION
**Pull request by yenda**
addresses #2403 

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/components/toolbar/view.cljs [hunk 1]
```diff
@@ -118,8 +118,9 @@
 
 (defn simple-toolbar
   "A simple toolbar whose content is a single line text"
-  ([] (simple-toolbar nil))
-  ([title] (toolbar nil default-nav-back [content-title title])))
+  ([] (simple-toolbar nil nil))
+  ([title] (simple-toolbar nil title))
+  ([style title] (toolbar style default-nav-back [content-title title])))
```
Comment (oskarth) [inline src/status_im/ui/components/toolbar/view.cljs]: Don't change order of args in multi-arity functions, break expectations and easily leads to bugs.

**Review by oskarth — CHANGES_REQUESTED** [review]

File: src/status_im/ui/components/toolbar/view.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/ui/components/toolbar/view.cljs]: That's a component, if we follow that logic we should rewrite all the components that take an optional style ?

Comment (yenda) [reply src/status_im/ui/components/toolbar/view.cljs]: Also it's a pretty urgent bug to fix because all the builds from current develop are untestable until this is merged

Comment (yenda) [reply src/status_im/ui/components/toolbar/view.cljs]: Maybe an assert on the first argument `(or (nil? style) (map? style))` would be enough to prevent bugs ?

Comment (oskarth) [reply src/status_im/ui/components/toolbar/view.cljs]: > rewrite all the components that take an optional style ?

Idiomatic in Clojure to deal with optional stuff is to append positionally, use a map, or `& opts`. I don't think we should generally let ad hoc JS convention seep into Clojure more than necessary.

> Also it's a pretty urgent bug to fix because all the builds from current develop are untestable until this is merged
  
Ok, I didn't realize this. And seems like we use this component a bunch so less likely to break things by this change. Oh well.

**Review by oskarth — APPROVED** [review]
Approving to unblock develop, but disagree with these type of function signatures as noted above.

**Comment by oskarth** [comment]
Looked at where we use `simple-toolbar` more and it should stay simple. The bug AFAIK is just in recover account: `(ns status-im.ui.screens.accounts.recover.views`

```
[toolbar/simple-toolbar {:modal? modal?} ;; XXX
        (i18n/label :t/recover-access)]
```
Should be replaced by:

```
(toolbar  {:modal? modal?} default-nav-back [content-title  (i18n/label :t/recover-access)])
```

With appropriate imports from `status-im.ui.components.toolbar.view`.

**Review by oskarth — CHANGES_REQUESTED** [review]
See comment for what IMO is correct fix not to make a simple thing more complex.

**Comment by oskarth** [comment]
Alternatively, you can also introduce a `(defn simple-modal-toolbar [title])` function as a component in toolbar ns

**Review by oskarth — APPROVED** [review]

File: src/status_im/ui/components/toolbar/view.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/ui/components/toolbar/view.cljs]: >  don't think we should generally let ad hoc JS convention

that's rather hiccup thing, no? Ability to skip styles map. And it's quite convenient imo.

Comment (oskarth) [reply src/status_im/ui/components/toolbar/view.cljs]: @rasom This is true. To me it is a bit different because it's always in Hiccup vector forms, so there isn't a lot of room for variability. There is only `[:foo ...` or `[:foo style ...`. At least AFAIR, might be wrong. In this case, and similar cases in this namespace, there are more positional arguments and we do it for some components/fns but not all, etc.

**Review by rasom — APPROVED** [review]
