### PR TITLE
[Fix] Wallet - Route not fetching

### LINKED ISSUE #18652: Unable to find routes for asset transfer
### Steps:
1. Recover the user with available assets to sent
2. Go to the send page
3. Attempt to send the available amount

### Actual result:
Routes for the asset transfer are not found (no matter testnet or mainnet network is used)

https://github.com/status-im/status-mobile/assets/52490791/7f2f60f0-e00c-4217-a336-20ad9e1282e8

### Expected result:
Routes are found

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14237135/logs.zip)

### ENV:
Nightly 12.02.2024

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18652

### Summary

This PR fixes the route not fetched bug on the send flow.

### Review notes

The bug is actually caused by the receiver network being nil and it sends the same to `status-go`.

### Platforms

- Android
- iOS

##### Functional

- wallet/transactions

### Steps to test

- Open Status
- Navigate to the Wallet tab
- Try to send some tokens to any other accounts
- Verify routes are fetched
- Verify the transaction is successful

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -60,7 +60,9 @@
  (fn [{:keys [db]} [{:keys [address token recipient stack-id]}]]
    (let [[prefix to-address] (utils/split-prefix-and-address address)
          prefix-seq          (string/split prefix #":")
-         selected-networks   (mapv #(utils/short-name->id (keyword %)) prefix-seq)]
+         selected-networks   (->> prefix-seq
+                                  (remove string/blank?)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:64]: It'd be good to have this logic as a separate function that takes an address and returns the networks found in it. I think it'll be a common functionality.

We can do that in a later refactor

**Review by ulisesmac — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/send/events.cljs:64]: Might be good to track this in an issue 👌

**Review by vkjr — APPROVED** [review]

**Comment by OmarBasem** [comment]
@smohamedjavid what is the issue exactly because routes functionality and editing the receiver's networks is generally working? Can you show us video of the bug?

**Review by briansztamfater — APPROVED** [review]
Maybe we should link #18652?

**Comment by smohamedjavid** [comment]
> @smohamedjavid what is the issue exactly because routes functionality and editing the receiver's networks is generally working? 

@OmarBasem - The issue is happening on addresses which don't have any prefixes (network preferences). On fetching the suggested routes, we pass an array with nil (as there are no network preferences in the address) to `status-go` which in turn returns no routes.

Left is the bug and right is the fix


Now this fix will work for both addresses with network prefixes and without network prefixes.

> Can you show us video of the bug?

Please check: https://github.com/status-im/status-mobile/issues/18652

**Comment by smohamedjavid** [comment]
@status-im/mobile-qa Appreciate it if this PR could be fast-tracked to unblock other issues/PRs.

**Comment by pavloburykh** [comment]
@smohamedjavid thank you for the fix. PR is ready for merge.

**Comment by smohamedjavid** [comment]
> @smohamedjavid thank you for the fix. PR is ready for merge.

Thank you for testing it real quick @pavloburykh!
