### PR TITLE
fix: nav conflicts when return from bg from link

### LINKED ISSUE #17790: Sometimes PN does not redirect user into correct chat if some other chat was opened at the moment of redirection (Android)
Followup of https://github.com/status-im/status-mobile/pull/17721 cc @yqrashawn 

Reproducing on Android 12, Samsing Galaxy A52. Bug is not reproducible every time

**Preconditions:** User A (Android) turns on push notifications

**Steps:** 

1. User A opens 1-1 chat with User B
2. User A closes the app
3. User B sends mention/reply to User A in community channel
4. User A taps on PN 
5. See if User A is redirected into community cahnnel

**Actual result:** sometimes User A remains on 1-1 chat screen and is redirected to the channel. At the same time, the message in channel appears as read despite User A in fact has not opened the channel. 

https://github.com/status-im/status-mobile/assets/97245802/5ecbbb36-928a-4491-beb9-7dd446452a13

[Status-debug-logs (76).zip](https://github.com/status-im/status-mobile/files/13226198/Status-debug-logs.76.zip)

**Expected result:** User A should be redirected to the right chat upon PN. 

### Additional Information

- Status version: nightly 
- Operating System: Android

### PR DESCRIPTION
**Pull request by yqrashawn**
fixes #17790

### Summary

the issue is caused by conflicts between `:chat/open-last-chat` and chat triggered by universal/deep link (notification)
PR add `:universal-links/handling` mark to db when app is triggered by universal/deep link
and skip `:chat/open-last-chat` when the mark exists

### Testing notes
affects trigger app open with deep/universal link while there's already existing chat view

### Steps to test

same steps in #17790

status: ready

### CODE REVIEW

**Comment by yqrashawn** [comment]
https://github.com/status-im/status-mobile/assets/15090582/0c4c9f09-b231-4fe6-a885-f9b56022de49

File: src/status_im/utils/universal_links/core.cljs [hunk 1]
```diff
@@ -158,6 +162,16 @@
   (log/info :store-url-for-later)
   {:db (assoc db :universal-links/url url)})
 
+(rf/defn handling
+  {:events [:universal-links/remove-handling]}
```
Comment (flexsurfer) [inline src/status_im/utils/universal_links/core.cljs]: event name is the same as for remove-handling

Comment (yqrashawn) [reply src/status_im/utils/universal_links/core.cljs]: fixed, thanks

**Review by flexsurfer — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @yqrashawn Thanx for PR. An additional issue is found.

## ISSUE 1: Chat not opening after reopening the app

### Steps:
1. Open any chat
2. Close the app
3. Reopen the app

### Actual result:
User is not navigated to the chat


https://github.com/status-im/status-mobile/assets/52490791/d266b514-9b5c-49fc-a132-badc79ba1325



### Expected result:
User should be taken to the chat upon reopening the app.


### ENV:
 IOS/ Android

**Review by Parveshdhull — APPROVED** [review]

**Comment by yqrashawn** [comment]
Thanks @VolodLytvynenko, ISSUE 1 fixed now

**Comment by VolodLytvynenko** [comment]
hi @yqrashawn thank you for your fix. PR is tested and ready to be merged
