### PR TITLE
Wallet - Initialize event, refactor networks data and bug fix

### LINKED ISSUE #17985: Event to initialize new wallet
# Problem

The old wallet is planned to be removed for the 1.27 release, and currently, we are using `:wallet-legacy/initialize` to initialize our wallet.

We want to create a new re-frame event to initialize our wallet and get rid of the unused stuff.

## Implementation

Please align with @rasom or @flexsurfer if there are questions about old wallet behavior.

Please try to focus on readability and clean code while implementing this event since it's highly probable that it's going to be revisited many times in the future. - we are trying to make it easier to maintain - :)

### LINKED ISSUE #18368: Updating the network preferences for an account in test net mode, the production network preferences are updated
# Bug Report

## Problem 

When updating the network preferences for an account in the test net mode, the production network preferences are updated.

### Expected behaviour

The network preferences for test net should NOT update the preferences for production.

### Reproduction

1. Open the Status app
2. Switch to Test net mode
3. Navigate to the Wallet tab
4. Update the network preferences of any account with any network
8. Switch back to live
9. Check the network preferences of the account you have updated

### Additional Information

- Status Version: nightly [2024/01/03] 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #17985
fixes #18368

### Summary

This PR:
 - Introduces new event `:wallet/initialize` to group events that need to be called on login
 - Refactors wallet networks to use the nested structure in re-frame
 - Fixes a bug when updating the testnet network preferences of an account the production network preferences update

### Platforms

- Android
- iOS

### Steps to test

Please do a quick test of the wallet, as this PR does a minor refactor.

#### To test the bug fix

1. Open the Status app
2. Switch to Test net mode
3. Navigate to the Wallet tab
4. Update the network preferences of any account with any network
8. Switch back to live
9. Check the network preferences of the account you have updated
10. Verify the production network preferences are not updated

status: ready

### CODE REVIEW

File: src/status_im/subs/wallet/wallet.cljs [hunk 1]
```diff
@@ -60,11 +59,6 @@
  :<- [:wallet/wallet-send]
  :-> :token)
 
-(rf/reg-sub
```
Comment (J-Son89) [inline src/status_im/subs/wallet/wallet.cljs]: you sure you should delete this?

File: src/status_im/subs/wallet/wallet.cljs [hunk 2]
```diff
@@ -79,15 +73,13 @@
...
- (fn [[wallet network-details]]
-   ;; TODO(@rende11): `testnet?` value would be relevant after this implementation,
-   ;; https://github.com/status-im/status-mobile/issues/17826
-   (let [testnet? false]
-     (->> wallet
-          :accounts
-          vals
-          (map #(assoc-network-preferences-names network-details % testnet?))
-          (sort-by :position)))))
+ :<- [:profile/test-networks-enabled?]
```
Comment (J-Son89) [inline src/status_im/subs/wallet/wallet.cljs:80]: 🙌

File: src/status_im/subs/wallet/wallet.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/subs/wallet/wallet.cljs]: I checked for the usage. It's an unused subscription.
If it's needed, I will revert it 👍

Comment (J-Son89) [reply src/status_im/subs/wallet/wallet.cljs]: aha, actually I think this is a duplicate. 🤔 
In this pr https://github.com/status-im/status-mobile/pull/18242/files#diff-8bd46e272f87626708b0cb26f20ee2f21d87c4d3197fd2e761a751cac235e9f3 I moved it to src/status_im/subs/wallet/send.cljs

Comment (smohamedjavid) [reply src/status_im/subs/wallet/wallet.cljs]: No worries if it's handled. I will revert this part. 👍

File: src/status_im/contexts/wallet/events.cljs [hunk 3]
```diff
@@ -213,13 +213,13 @@
...
-                           data-store/<-rpc)
+                           data-store/rpc->network)
                      data)
           :prod (map #(->> %
                            :Prod
-                           data-store/<-rpc)
+                           data-store/rpc->network)
                      data)}]
-     {:db (assoc db :wallet/networks network-data)})))
+     {:db (assoc-in db [:wallet :networks] network-data)})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events.cljs:204]: :+1:

File: src/status_im/subs/wallet/networks.cljs [hunk 4]
```diff
@@ -4,10 +4,16 @@
...
+ :-> :networks)
+
+(re-frame/reg-sub
+ :wallet/networks-by-mode
  :<- [:wallet/networks]
- (fn [networks [_ test?]]
-   (get networks (if test? :test :prod))))
+ :<- [:profile/test-networks-enabled?]
+ (fn [[networks test-networks-enabled?]]
+   (get networks (if test-networks-enabled? :test :prod))))
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/networks.cljs:16]: :100:

**Review by ulisesmac — APPROVED** [review]
Nice :100:

**Review by OmarBasem — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
Nice work @smohamedjavid 💪 !

**Comment by qoqobolo** [comment]
Thanks @smohamedjavid, LGTM!
PR can be merged.
