### PR TITLE
Fix collectible/token icon and name on addresses for permissions screen

### LINKED ISSUE #18824: Minted ERC20/ERC721 tokens have a broken icons on 'Addresses for permissions' screen
**Steps:**

1. Open community that has minted ERC20 and ERC721 tokens in permission requirements
2. Open 'Addresses for permissions' screen
3. See how ERC20 and ERC721 tokens look like within relevant tokens

**Actual result:**

ERC20 token misses icon
ERC721 is displayed with some mocked icon and without name

photo_2024-02-14 16 54 55
photo_2024-02-14 16 55 02

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #18824 

### Summary

Fixes an issue with addresses for permissions sheet didn't have images for collectibles.

status: ready

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]

**Comment by jo-mut** [comment]
@ibrkhalil just curious on the screen shot you attached to this PR. One of the icon is just squre while the others are rounded

**Review by jo-mut — APPROVED** [review]

**Comment by ibrkhalil** [comment]
> @ibrkhalil just curious on the screen shot you attached to this PR. One of the icon is just squre while the others are rounded


I thought about it too when implementing the PR, But I thought I'd leave it to QA and design reviews to decide what it should look like.

File: src/status_im/subs/communities.cljs [hunk 1]
```diff
@@ -406,3 +406,11 @@
     (re-frame/subscribe [:communities/airdrop-address community-id])])
  (fn [[accounts airdrop-address]]
    (first (filter #(= (:address %) airdrop-address) accounts))))
+
+(re-frame/reg-sub :communities/token-requirements-images
+ :<- [:communities]
+ (fn [communities [_ community-id]]
+   (->> (get-in communities [community-id :tokens-metadata])
+        (map (fn [{sym :symbol image :image}]
```
Comment (ilmotta) [inline src/status_im/subs/communities.cljs:422]: I think it's better to listen to only a particular community, like the other subs do, they use the sub `:communities/community`.

File: src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs [hunk 2]
```diff
@@ -32,22 +31,24 @@
...
+      (assoc :amount        (str (money/token->unit amount decimals))
+             :token         (:symbol balance)
+             :token-img-src (token-images-map sym)))))
 
 (defn- account-item
   [{:keys [color address name emoji]} _ _
    {:keys [selected-addresses community-id share-all-addresses? community-color]}]
-  (let [balances (rf/sub [:communities/permissioned-balances-by-address community-id address])]
+  (let [balances         (rf/sub [:communities/permissioned-balances-by-address community-id address])
+        token-images-map (rf/sub [:communities/token-requirements-images community-id])]
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: A suggestion I have is to rename the sub to `:communities/token-images-by-symbol`, and rename the binding to `images-by-symbol` for example. Suffixing the type of the data structure (`map` in this case) is unconventional in Clojure. The convention `x-b-y` is powerful because it tells us immediately what the map is indexed by.

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil thank you for the fix. Ready for merge.
