### PR TITLE
[#18754] fix: scrollable addresses permission list in android

### LINKED ISSUE #18754: Can't scroll through "addresses for permissions" list (Andoird)
Related to https://github.com/status-im/status-mobile/pull/18530

Reproducing on Android 12, Samsung Galaxy A52

**Steps:** 

1. Generate long list of wallets (about > 6)
2. Open any community in which you are not a member yet and eligable to join
3. Tap Join Community => Join as Member
4. Try to scroll though wallets list

**Actual result:** unable to scroll through the list

https://github.com/status-im/status-mobile/assets/97245802/6069b314-c98b-4482-b465-3ce7ca34b23e

- Status version: [nightly](https://github.com/status-im/status-mobile/pull/18530) 
- Operating System: Android

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #18754

### Summary

Can't scroll through "addresses for permissions" list (Andoird)

#### Platforms

- Android

### Result
[Screen_recording_20240213_223629.webm](https://github.com/status-im/status-mobile/assets/71308738/11ae97ec-a96b-4370-885f-72a56e3ffd4f)

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs [hunk 1]
```diff
@@ -45,7 +46,7 @@
       :container-style {:margin-bottom 8}}]))
 
 (defn view
-  []
+  [{:keys [scroll-enabled on-scroll]}]
```
Comment (J-Son89) [inline src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: nit: scroll-enabled?

I would also recommend passing the deref'd value instead here. 
It is less clear when the prop is a ratom and generally I think we want to avoid passing them along unless the value is being updated in the consuming component/view. Even then it can be better to pass a function to update it rather than the  ratom itself.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: @J-Son89 this is how bottom-sheet implemented, should i change this component? and can you give me example how to passing the deref'd value? 
https://github.com/status-im/status-mobile/blob/f762cdcf9bb66d336df65194cef637044c1360f8/src/status_im/common/bottom_sheet_screen/view.cljs#L90

Comment (J-Son89) [reply src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: thanks @mohsen-ghafouri - why can't we just do
`:scroll-enabled @scroll-enabled` ? 🤔 

of course these changes will probably affect other places that we probably need to adjust too. 
@smohamedjavid any idea if we need to pass this ratom for a particular reason?

Comment (mohsen-ghafouri) [reply src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: I'm a bit afraid of unknown side effect as this is a basic component. but as you have more experience and if it safe i can change it to ```:scroll-enabled? @scroll-enabled?``` in [bottom_sheet_screen/view.cljs](https://github.com/status-im/status-mobile/blob/f762cdcf9bb66d336df65194cef637044c1360f8/src/status_im/common/bottom_sheet_screen/view.cljs#L90) also update all usages in other screens

Comment (J-Son89) [reply src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: seems @briansztamfater added this value - https://github.com/status-im/status-mobile/pull/16319/files

From that pr it looks like it should have been done this way initially. I would be reasonably confident it's safe to update it.

Comment (mohsen-ghafouri) [reply src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: Great, let me update and test it again

Comment (mohsen-ghafouri) [reply src/status_im/contexts/communities/actions/addresses_for_permissions/view.cljs]: @J-Son89 resolved

**Review by ajayesivan — APPROVED** [review]
LGTM! Thanks for the fix @mohsen-ghafouri ❤️

**Review by Parveshdhull — APPROVED** [review]

**Comment by qoqobolo** [comment]
@mohsen-ghafouri thanks for the fix, still checking it and waiting for e2e results, but looks good to me so far.
Noticed one small but visible thing: wrong `i` icon on the `Addresses for permissions` screen

Screenshot 2024-02-15 at 13 00 05


How do you feel about fixing it here? If this is an easy fix ofc. I logged it here with a figma link https://github.com/status-im/status-mobile/issues/18840

**Comment by ilmotta** [comment]
FYI @qoqobolo: the icon bug is being fixed separately by @ajayesivan in https://github.com/status-im/status-mobile/issues/18616

**Comment by mohsen-ghafouri** [comment]
Thank you @qoqobolo, so if all good please let me know to merge it.

**Comment by qoqobolo** [comment]
@mohsen-ghafouri PR is ready for merge.
Thank you!
