### PR TITLE
Fix component tests, upgrade Jest & friends, and a few other goodies

### LINKED ISSUE #18157: Take a look at flaky component test
Component tests are flaky due to us patching the jest config at react-native here : https://github.com/status-im/status-mobile/blob/develop/nix/deps/nodejs-patched/default.nix#L60-L64

We have to do this because react-native 0.72.x uses jest 29.x and our codebase has jest 26 ( jest 26 is no longer supported btw)

as pointed here upgrading jest was a pain last time I had tried : https://github.com/status-im/status-mobile/issues/17409#issuecomment-1742650078

But to solve the flakiness that seems to be the only way forward.
We'll have to get builds working with latest version of jest and remove this patch.

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/18157
Closes https://github.com/status-im/status-mobile/pull/18235

## Summary

The main motivation for this PR was to fix all component tests after the latest RN upgrade. But this PR also brings a few Christmas gifts :santa:

**Dependency changes**

- Upgraded `Jest`: from `26.6.3` to latest `29.7.0`.
- Upgraded `@testing-library/jest-native`: from `5.3.0` to latest `5.4.3`
- Upgraded `@testing-library/react-native`: from `11.5.4` to `12.4.2`
- Removed explicit dependency on `jest-circus`, this is now the default test runner.
- Removed explicit dependency on `jest-environment-node`. This is handled by the package manager.
- Added `jest-silent-reporter` at version `0.5.0`.

### Why component tests were failing?

**Many tests** were failing because we were using RN Testing Library (RNTL) in an unreliable fashion (we still do, I haven't rewritten all of the tests, nor do I intend to). With the recent library upgrades, the unreliability was excerbated. Other times, the tests were incorrectly arranging data.

But to be fair, some degree of unreliability will always exist with RTL/RNTL, it's the nature of the beast. Next time you need to comment out a component test, consider first if the test can be rewritten in a more reliable way, even if you have your suspicions an external factor could be the cause.

### `with-redefs` does not work with async code

This one may trip you up. **Generally speaking, `with-redefs` should not be used with async code, assume the worst.** The scope of the macro will cease to exist by the time the async code runs. In many tests we were using `with-redefs`, then calling `render`, but for some components that use `use-effect`, JS timers, animations, etc it's unreliable and were the reason for failures.

I have not rewritten all usages of with-redefs in this PR. Some tests still pass with `with-redefs`, but that's by chance, it's not what you think.

Don't take my word! It's easy to reproduce:

```clojure
(defn foo []
  :foo)

(foo)
;; => :foo

(with-redefs [foo (constantly :bar)]
  (foo))
;; => :bar

(js/setTimeout
 (fn []
   (tap> [:calling-foo (foo)]))
 100)
;; Taps [:calling-foo :foo]
;; As you would expect, when running without with-redefs, it prints :foo.

;; So far so good, but whatch what happens with async code:

(with-redefs [foo (constantly :bar)]
  (js/setTimeout
   (fn []
     (tap> [:calling-foo (foo)]))
   100))
;; Taps [:calling-foo :foo]
;; ====> PROBLEM: Taps :foo, not :bar as one might expect
```

### Not waiting on `wait-for`

When `test-helpers.component/wait-for` is used, **subsequent assertions/etc should be done after the promise returned by `wait-for` is resolved**. But remember to not perform side-effects inside the `wait-for` callback (check out the docs https://callstack.github.io/react-native-testing-library/docs/api#waitfor). Most, if not all of our usages of `wait-for` were not waiting. I get the impression ClojureScript confuses JS devs, because in Javascript it's more common for devs to remember to use `await`.

Many tests do work without waiting, but I've seen time and time again tests behaving erratically while working on this PR.

We should strive for correctness over convenience if we want to minimize this class of problem, so await (use `.then`) after `wait-for`.

#### :gift: 1 - Silence Jest on demand

If you need to re-run component tests frequently, like me, you may want to reduce the output verbosity. By passing `JEST_USE_SILENT_REPORTER=true` to `make component-test` or `make component-test-watch` you will see a lot less noise and be able to focus on what really matters to you.

#### :gift: 2 - Selectively focus/disable tests

I know this is a given when using Jest outside CLJS, but because of our need to first compile CLJS to JS before running tests via Jest, we couldn't easily skip or focus on specific tests. This changes now!

From this PR onwards, we should never again have to change the list of requires in files `core_spec.cljs`. Commenting out required namespaces gives a bad DX because it causes constant rebasing issues.

This is the screenshot for skipping the only test I couldn't fix yet. I'll do it in a follow-up, or at least try :shrug:

#### :gift: 3 - Translations now work as in prod code (but only English)

Translations performed by `*-by-translation-text` can be done now without any workaround under the hood. The query functions are now linted just like `i18n/label`, which means static translation keywords must be qualified with `:t/`, which is good for consistency.

### Steps to test

There's nothing to manually test from a QA perspective. Changes were made almost exclusively in test code. I believe my manual smoke checks and e2e tests are sufficient.

status: ready

### CODE REVIEW

File: src/quo/components/colors/color_picker/view.cljs [hunk 1]
```diff
@@ -27,14 +27,18 @@
...
-                                                                               default-selected)
-                                                       :viewPosition 0.5}))
-                                   50))
+    (rn/use-effect
+     (fn []
+       (js/setTimeout
+        (fn []
+          (let [index (.indexOf colors/account-colors default-selected)]
+            (when (and @ref (>= index 0))
+              (some-> ^js @ref
```
Comment (ilmotta) [inline src/quo/components/colors/color_picker/view.cljs:36]: FYI: The component test caught two potential bugs here, 1st that the index could be -1 and then `scrollToIndex` would throw an exception, and 2nd `@ref` could be nil and then an exception would be thrown as well.

File: src/quo/components/drawers/drawer_buttons/component_spec.cljs [hunk 2]
```diff
@@ -6,14 +6,7 @@
...
 (h/describe "drawer-buttons"
-  (h/before-each
-   (fn []
-     (h/use-fake-timers)))
-
-  (h/after-each
-   (fn []
-     (h/clear-all-timers)
-     (h/use-real-timers)))
+  (h/setup-fake-timers)
```
Comment (ilmotta) [inline src/quo/components/drawers/drawer_buttons/component_spec.cljs:9]: FYI: Fake timers are a nice feature. When I tried to enable them in more places, sometimes they could help make the tests more deterministic due to the elimination of some timing issues, but tests ended up failing for other reasons. It's a tool, and as such should be used only when needed.

File: src/quo/components/graph/wallet_graph/component_spec.cljs [hunk 3]
```diff
@@ -13,7 +13,10 @@
                {:time-frame :empty}])
     (h/is-truthy (h/get-by-label-text :illustration)))
 
-  (h/test "render 1 week wallet graph"
+  ;; NOTE: Throws error:
+  ;;   _reactNative.Animated.timing(widthValue2, {
+  ;;   Cannot read properties of undefined (reading 'timing')
+  (h/test-skip "render 1 week wallet graph"
```
Comment (ilmotta) [inline src/quo/components/graph/wallet_graph/component_spec.cljs:19]: FYI: Using `h/test-skip` here shows how we can skip tests without commenting them out. This is important, for instance, if you comment all the tests in a test file, Jest will throw an error and the test suite will fail saying at least one test should exist per file.

For this particular test, as mentioned in the PR description, I couldn't fix it yet, but it's just one among so many fixed. We will find a way.

File: src/quo/components/inputs/address_input/component_spec.cljs [hunk 4]
```diff
@@ -38,47 +40,56 @@
...
   (h/test "on blur with text and blur? false"
     (with-redefs [clipboard/get-string #(% "")]
       (h/render [address-input/address-input
                  {:scanned-value "scanned value"
                   :ens-regex     ens-regex}])
-      (h/wait-for #(h/is-truthy (h/get-by-label-text :clear-button)))
-      (h/fire-event :on-focus (h/get-by-label-text :address-text-input))
-      (h/fire-event :on-blur (h/get-by-label-text :address-text-input))
-      (h/has-prop (h/get-by-label-text :address-text-input) :placeholder-text-color colors/neutral-30)))
+      (-> (h/wait-for #(h/get-by-label-text :clear-button))
```
Comment (ilmotta) [inline src/quo/components/inputs/address_input/component_spec.cljs:63]: FYI: Notice how it's unnecessary to surround `get-by-*` with `h/is-truthy` when used as a matcher for `h/wait-for. The spec for RNTL `waitFor` clearly says the predicate should throw an exception when not found and every `get-by-*` function does that. Since this is a common need, it's nice to be able to write less.

File: src/quo/components/inputs/address_input/component_spec.cljs [hunk 5]
```diff
@@ -142,11 +158,12 @@
...
-        (h/wait-for #(h/is-truthy (h/get-by-label-text :paste-button)))
+        (h/is-truthy (h/query-by-label-text :paste-button))
         (h/fire-event :press (h/get-by-label-text :paste-button))
-        (h/wait-for #(h/is-falsy (h/get-by-label-text :clear-button)))
-        (h/wait-for #(h/is-truthy (h/get-by-label-text :loading-button-container)))
-        (h/was-called on-detect-ens))))
+        (-> (h/wait-for #(h/is-falsy (h/query-by-label-text :clear-button)))
+            (.then (fn []
+                     (h/wait-for #(h/get-by-label-text :loading-button-container))))
+            (.then #(h/was-called on-detect-ens))))))
```
Comment (ilmotta) [inline src/quo/components/inputs/address_input/component_spec.cljs:166]: FYI: Notice how the next assertion must go after the promise returned by the second `wait-for` is fulfilled.

I think adding the library https://github.com/funcool/promesa to the project is starting to make even more sense to keep the syntax more clean, but I also think these few `.then` calls look just fine.

File: src/quo/components/wallet/network_routing/view.cljs [hunk 6]
```diff
@@ -86,10 +86,10 @@
 
 (defn- dashed-line
   [network-name]
-  [rn/view {:style style/dashed-line}
-   (take 19
-         (interleave (repeat [rn/view {:style (style/dashed-line-line network-name)}])
-                     (repeat [rn/view {:style style/dashed-line-space}])))])
+  (into [rn/view {:style style/dashed-line}]
```
Comment (ilmotta) [inline src/quo/components/wallet/network_routing/view.cljs:89]: FYI: I resolved almost all or all (can't remember now) of the React warnings about non-unique keys. This is one example.

File: src/status_im/contexts/chat/messages/content/audio/component_spec.cljs [hunk 7]
```diff
@@ -1,28 +1,26 @@
 (ns status-im.contexts.chat.messages.content.audio.component-spec
   (:require
-    [re-frame.core :as re-frame]
     [react-native.audio-toolkit :as audio]
     [status-im.contexts.chat.messages.content.audio.view :as audio-message]
     [test-helpers.component :as h]))
 
+;; We can't rely on `with-redefs` with async code.
+(set! audio/destroy-player #())
```
Comment (ilmotta) [inline src/status_im/contexts/chat/messages/content/audio/component_spec.cljs:8]: FYI: Using `set!` is only safe because Jest isolates tests between files, so the `audio/destroy-player` var is modified only within the scope of the tests in this file.

File: src/status_im/contexts/communities/actions/community_options/component_spec.cljs [hunk 8]
```diff
@@ -1,189 +1,123 @@
...
 
-(defn setup-subs
-  [subscriptions]
-  (doseq [keyval subscriptions]
-    (re-frame/reg-sub
-     (key keyval)
-     (fn [_] (val keyval)))))
-
 (h/describe "community options for bottom sheets"
+  (h/setup-restorable-re-frame)
```
Comment (ilmotta) [inline src/status_im/contexts/communities/actions/community_options/component_spec.cljs:7]: FYI: This setup function makes the dozens of warnings about subscriptions being redefined go away. Now each test starts with a blank canvas.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 9]
```diff
@@ -48,7 +48,6 @@
 
 (rf/reg-event-fx :wallet/send-select-amount
  (fn [{:keys [db]} [{:keys [amount]}]]
-   (js/alert "Not implemented yet")
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/send/events.cljs:51]: FYI: re-frame events shouldn't have side-effects, though we have one famous exception in the project: we call log functions :)

**Comment by ilmotta** [comment]
@OmarBasem, @J-Son89, @ulisesmac, @mmilad75, @BalogunofAfrica, @jo-mut, @ibrkhalil, @codemaster115, @siddarthkay, @mohsen-ghafouri 

I can't add more than 15 reviewers, so I'm tagging you all in this comment. Please, have a look at the PR whenever you can, the changes are relevant enough that I think I should add all core devs.

File: test/jest/jest.config.js [hunk 10]
```diff
@@ -1,25 +1,71 @@
+const transformIgnorePatterns = () => {
```
Comment (siddarthkay) [inline test/jest/jest.config.js:1]: beautiful

File: src/test_helpers/component.clj [hunk 11]
```diff
@@ -10,12 +10,40 @@
...
+      ~@body
+      js/undefined)))
+
 (defmacro test
   [description & body]
   `(js/global.test
      ~description
      (fn [] ~@body)))
 
+(defmacro test-skip
```
Comment (siddarthkay) [inline src/test_helpers/component.clj:35]: much needed! 
Thank you

File: nix/deps/nodejs-patched/default.nix [hunk 12]
```diff
@@ -56,13 +55,6 @@ stdenv.mkDerivation {
       '-Wl,--build-id=none'
   '';
 
-  # Remove when we upgrade jest to 29
```
Comment (siddarthkay) [inline nix/deps/nodejs-patched/default.nix:59]: Less patches! YAY!

**Review by siddarthkay — APPROVED** [review]
This is commendable work @ilmotta 
Thanks for taking care of this 🚀

File: src/status_im/core_spec.cljs [hunk 13]
```diff
@@ -5,6 +5,5 @@
     [status-im.contexts.communities.actions.community-options.component-spec]
     [status-im.contexts.wallet.add-address-to-watch.component-spec]
     [status-im.contexts.wallet.add-address-to-watch.confirm-address.component-spec]
+    [status-im.contexts.wallet.create-account.edit-derivation-path.component-spec]
     [status-im.contexts.wallet.send.input-amount.component-spec]))
-
-  ;; [status-im.contexts.wallet.create-account.edit-derivation-path.component-spec]
```
Comment (OmarBasem) [inline src/status_im/core_spec.cljs]: Btw there is one more test here (after rebasing)

**Review by OmarBasem — APPROVED** [review]
Thank you for fixing this @ilmotta !

File: src/quo/components/graph/wallet_graph/component_spec.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo/components/graph/wallet_graph/component_spec.cljs:19]: yep it's the way to go 👍

File: src/quo/components/inputs/address_input/component_spec.cljs (hunk 5 above)
Comment (J-Son89) [reply src/quo/components/inputs/address_input/component_spec.cljs:166]: +1 for promesa, I guess this discussion shiould be handled outside of the pr. It would be good to get a clearer understanding for the pros/cons of using that library in the project. 
cc @clauxx

File: Makefile [hunk 14]
```diff
@@ -364,6 +364,7 @@ android-test:
 component-test-watch: export TARGET := clojure
 component-test-watch: export COMPONENT_TEST := true
 component-test-watch: export BABEL_ENV := test
+component-test-watch: export JEST_USE_SILENT_REPORTER := false
```
Comment (J-Son89) [inline Makefile:367]: would be nice if we can call these with a shorthand arg, e.g 
`make component-test-watch --silent` or something to that effect.
Also this pr already does so much, so not to worry about that here 👌

**Review by mohsen-ghafouri — APPROVED** [review]
Impressive improvement 🚀

File: src/quo/components/inputs/address_input/component_spec.cljs (hunk 5 above)
Comment (ilmotta) [reply src/quo/components/inputs/address_input/component_spec.cljs:166]: Sure, outside this PR. It's like the 5th or so time I remember we kind of wish promesa was in the project. Also even an external contributor mentioned this. I used it a lot in the past, it's kind of a no-brainer.

File: src/status_im/core_spec.cljs (hunk 13 above)
Comment (ilmotta) [reply src/status_im/core_spec.cljs]: Oh thanks for catching that @OmarBasem.

File: Makefile (hunk 14 above)
Comment (ilmotta) [reply Makefile:367]: Good idea @J-Son89, but to achieve this DX is impossible I think with `make`. The argument must be passed with a variable, like `make component-test-watch ARG1=--silent`. Maybe we should start to consider scripts instead to create a better CLI, we could even write some with babashka, something to consider cc @yqrashawn

**Review by vkjr — APPROVED** [review]

**Comment by vkjr** [comment]
Amazing PR, thanks @ilmotta! 🚀 
Would it be convenient for you to extract the knowledge from this PR to some document?

**Comment by ilmotta** [comment]
> Amazing PR, thanks @ilmotta! 🚀 Would it be convenient for you to extract the knowledge from this PR to some document?

Hey @vkjr, @siddarthkay said something similar, so that's two already :) I'll try then to capture some good practices in a separate document. Will create an issue to track this progress.

Edit: Issue created https://github.com/status-im/status-mobile/issues/18287

File: src/status_im/core_spec.cljs (hunk 13 above)
Comment (ilmotta) [reply src/status_im/core_spec.cljs]: @OmarBasem, @J-Son89, when possible, please have a look at this commit I made to fix failing tests https://github.com/status-im/status-mobile/pull/18276/commits/884266bc77b913a0862d9cfae61c890b3bdcca4d. The problem appeared after I rebased, I guess from the recently merged commit 5eb0baa64dd937cbcaa8bd0eb93a56adf6498cba  

The root cause was because in `quo.components.wallet.network-bridge.view/view` we were calling `name` on a nil value, but this throws exceptions in the tests for `status-im.contexts.wallet.send.input-amount.component-spec`. I don't know if this could be a problem in production later on, but it's safer anyway to guard against calling `name` in a possibly nil value.

Comment (OmarBasem) [reply src/status_im/core_spec.cljs]: LGTM @ilmotta 👍

**Review by ibrkhalil — APPROVED** [review]

File: yarn.lock [hunk 15]
```diff
@@ -5455,27 +5029,11 @@ foreground-child@^1.5.6:
     cross-spawn "^4"
     signal-exit "^3.0.0"
 
-form-data@^3.0.0:
```
Comment (siddarthkay) [inline yarn.lock:5458]: @ilmotta : iOS builds seem to be failing because this dependency was removed from the project in this PR.
cc @yakimant @jakubgs : perhaps we should explicitly include it in our package.json since we need it for DIAWI uploads?

**Review by ajayesivan — APPROVED** [review]
🎉

File: src/quo/core_spec.cljs
Comment (ajayesivan) [inline src/quo/core_spec.cljs:1]: @ilmotta This file has some commented-out require at the top, could you please remove it

File: yarn.lock (hunk 15 above)
Comment (siddarthkay) [reply yarn.lock:5458]: should be fixed here : https://github.com/status-im/status-mobile/pull/18299

File: src/quo/core_spec.cljs
Comment (ilmotta) [reply src/quo/core_spec.cljs:1]: Thanks @ajayesivan, this was due to a rebase. It's fixed now.
