### PR TITLE
No redirect to sign in screen when back button clicked [#3903]

### LINKED ISSUE #3903: Back button should not redirect to sign in screen
### Description
*Type*: Bug

*Summary*: When user logs in and presses device back button she is being redirected to sign in screen. Instead, the app should go into the background. 

#### Expected behavior
When device back button is pressed, instead of going to sign in screen the app should go into background.

#### Actual behavior
When back button is pressed in home screen, user is redirected to sign screen. When she tries to log in again, the app crashes. 

### Reproduction
- Open Status
- Sign in and wait for the home screen to appear
- Press device back button

### Additional Information
* Status version: nightly, April 17
* Operating System: Android

### PR DESCRIPTION
**Pull request by psdp**
fixes #3903

### Summary:

When user logs in and presses device back button she is being redirected to sign in screen. Instead, the app should go into the background.

### Steps to test:

- Open Status
-   Sign in and wait for the home screen to appear
 -  Press device back button

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

File: src/status_im/ui/screens/events.cljs [hunk 1]
```diff
@@ -291,8 +291,7 @@
            (assoc db :view-id :intro :navigation-stack (list :intro))
            (let [{:keys [address photo-path name]} (first (sort-by :last-sign-in > (vals accounts)))]
              (-> db
-                 (assoc :view-id :login
-                        :navigation-stack (list :login))
```
Comment (flexsurfer) [inline src/status_im/ui/screens/events.cljs]: is it possible to return back from recovery screen?

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/events.cljs (hunk 1 above)
Comment (psdp) [reply src/status_im/ui/screens/events.cljs]: @flexsurfer fixed in `status-im.ui.screens.navigation/navigate-to-clean` now.

**Review by cammellos — APPROVED** [review]

File: src/status_im/ui/screens/accounts/login/views.cljs [hunk 2]
```diff
@@ -82,10 +82,10 @@
         (when-not can-navigate-back?
           [components.common/bottom-button
            {:label    (i18n/label :t/other-accounts)
-            :on-press #(re-frame/dispatch [:navigate-to-clean :accounts])}])
+            :on-press #(re-frame/dispatch [:navigate-to :accounts])}])
```
Comment (flexsurfer) [inline src/status_im/ui/screens/accounts/login/views.cljs]: this was a right behavior, it should be not possible to go back in this case, let's just revert this file

Comment (psdp) [reply src/status_im/ui/screens/accounts/login/views.cljs]: @flexsurfer done.

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
Thank you for contribution, @psdp!
