### PR TITLE
fix: mark :albumize? true when rebuild message

### LINKED ISSUE #15217: Albums are lost after deleting a message
Album images are sorted into separate images after deleting a message. They should stay as albums. See "issue 3" in this comment: https://github.com/status-im/status-mobile/pull/15208#issuecomment-1448467064

@yqrashawn I know you have been working on deleting messages, so I am wondering if you can take care of this issue.

The `albumize-messages` method in `status-im2.subs.chat.messages` would need to be called after deleting a message. But I am not sure where is the best place to call it.

I see that the list of messages is rebuilt after deleting a message (which causes the albums to be lost), but maybe there is a better way of doing it. I see a comment in `status-im2.contexts.chat.messages.list.events` "this is too expensive, probably we could mark message somehow and just hide it in the UI"

Dependency: https://github.com/status-im/status-mobile/pull/15208

### PR DESCRIPTION
**Pull request by yqrashawn**
fixes https://github.com/status-im/status-mobile/issues/15217

`:albumize?` of loaded messages (instead of newly sent messages) is marked true in order to display album only for loaded messages

this PR mark it `true` when `rebuild-message-list`

delete or undo delete will cause newly sent message be albumized as well, check the below video

https://user-images.githubusercontent.com/15090582/223677801-088b0fe0-0914-43c0-bfeb-60efeb0b21b0.mp4

status: ready

### CODE REVIEW

**Comment by yqrashawn** [comment]
@OmarBasem  don't know if this acceptable
Currently `rebuild-message-list` is only used in delete message related code. It's used to compute the author avatar <-> message relation
We may need to reimplement `rebuild-message-list` if we want to keep the unalbiumized state after delete/undo

**Comment by OmarBasem** [comment]
@yqrashawn not sure if this is acceptable. Better check with Pedro.

How is the behavior when sending images, then re-entering the chat?

**Comment by yqrashawn** [comment]
Hi @pedro-et, is it ok that newly sent messages get turned to album when delete and undo any message immediately? Demonstrated in the video below.


https://user-images.githubusercontent.com/15090582/223717631-ff1b850e-0fba-4d7e-b68b-c5ff299089b8.mp4

**Comment by John-44** [comment]
> Hi @pedro-et, is it ok that newly sent messages get turned to album when delete and undo any message immediately? Demonstrated in the video below.

Yes, the newly sent images should be turned into an album when the message is deleted and the deletion is then undone (by the user tapping 'undo') immediately if both of those images have been successfully sent to waku before the user taps 'undo'.

Also note that images the user as sent as part of a single message should be automatically turned into an album after all the images in the message are successfully sent.   If this isn't currently the case, @yqrashawn could you open a new issue to track this (if such an issue isn't open already), and when this is done send me the issue number?

To add some context: the reason that images are first displayed individually when a user sends multiple images in a single message, is to aid error handling in the case where some images are successfully sent and the sending of other images fails.  Once all the images in a single message are successfully sent, there is no reason not to display the images as an album on the sender side.

**Comment by OmarBasem** [comment]
@John-44 currently, images are automatically grouped into albums after re-entering the chat, or if the user was not inside the chat already. Isn't this the desired behavior?

**Comment by John-44** [comment]
> @John-44 currently, images are automatically grouped into albums after re-entering the chat, or if the user was not inside the chat already. Isn't this the desired behaviour?

@OmarBasem thanks for reminding me, yes what you have described above is exactly the desired behaviour :-)  Apologies for my goldfish 🐠 memory! ;-)

Assuming that all the images have been successfully sent by the time the user re-enters the chat of course

**Comment by yqrashawn** [comment]
So, I guess this is acceptable.

> How is the behavior when sending images, then re-entering the chat?

@OmarBasem It's not changed, same as before.

One thing to note. Delete ANY message and undo delete will both trigger images grouped into album since they are calling the same rebuild messages function.

https://user-images.githubusercontent.com/15090582/223891720-88dbab4a-deda-421d-abe9-ea591de609b0.mp4

**Comment by OmarBasem** [comment]
> Delete ANY message and undo delete will both trigger images grouped into album since they are calling the same rebuild messages function.

Oh, I think that would be weird behavior. Probably shouldn't happen. 

Why are we rebuilding the whole list when deleting a message? Why not remove that one message from the list?

**Comment by yqrashawn** [comment]
> > Delete ANY message and undo delete will both trigger images grouped into album since they are calling the same rebuild messages function.
> 
> Oh, I think that would be weird behavior. Probably shouldn't happen.
> 
> Why are we rebuilding the whole list when deleting a message? Why not remove that one message from the list?

Great question! As far as my understanding, it's used to re-compute the group message by avatar feature, check the below screenshot. 
We group multiple messages into a single author avatar if they are from the same user. We might not need to rebuild anymore since we now have a system message for deleted message. Let me check if it's required by other features.

CleanShot 2023-03-10 at 11 52 59@2x

**Comment by yqrashawn** [comment]
I think we still need to rebuild on delete. 

with rebuild message

https://user-images.githubusercontent.com/15090582/224222013-6364d873-f284-4abb-b90b-f192c44b81b7.mp4

without rebuild message

https://user-images.githubusercontent.com/15090582/224222102-caeb0e78-e16b-4091-8c9d-88899e11daa8.mp4


**situation when rebuild message is a must**

https://user-images.githubusercontent.com/15090582/224222713-46de67f2-57ef-43bb-b941-70e706f9b4a7.mp4

**Comment by yqrashawn** [comment]
@OmarBasem I think the ultimate right way is to implement albumize similar to message group.

There's `add-group-info` at https://github.com/status-im/status-mobile/blob/31993073eaff9e4fa800ffa5aaa6a8ebec883715/src/status_im2/contexts/chat/messages/list/events.cljs#L70 might give some inspiration. It's using the red black tree, so potentially we gain more performance if implemented this way.

**Comment by OmarBasem** [comment]
@yqrashawn how about we check the message before and after the deleted one if they need any modifications?

**Comment by yqrashawn** [comment]
> @yqrashawn how about we check the message before and after the deleted one if they need any modifications?

That's an option, but then we need to implement this for other features that hide or reorder messages, currently that's the message gap feature.
I'll put a bit more time into this and see if there's a better way to solve this.

**Comment by yqrashawn** [comment]
@OmarBasem fixed, this should do the trick

https://user-images.githubusercontent.com/15090582/225307149-04680476-a2ac-477c-9076-3ebbed34725f.mp4

File: src/status_im/chat/models/loading.cljs [hunk 1]
```diff
@@ -124,15 +113,28 @@
...
+                          ;; shouldn't group the images into albums. When the user exists the chat screen
+                          ;; then enters the
+                          ;; chat screen again, we now need to group the images into albums (like
+                          ;; WhatsApp). The albumize?
+                          ;; boolean is used to know whether we need to group these images into albums
+                          ;; now or not. The
+                          ;; album-id can't be used for this because it will always be there.
+                          (if (get all-messages message-id)
+                            message
+                            (assoc message :albumize? true))]
```
Comment (OmarBasem) [inline src/status_im/chat/models/loading.cljs]: are we marking all messages with `albumize`?

Comment (yqrashawn) [reply src/status_im/chat/models/loading.cljs]: Only new messages.

Comment (OmarBasem) [reply src/status_im/chat/models/loading.cljs]: So a new audio message will be marked?

Comment (yqrashawn) [reply src/status_im/chat/models/loading.cljs]: Oh I see. Will fix soon.

Comment (yqrashawn) [reply src/status_im/chat/models/loading.cljs]: Done

File: src/status_im/chat/models/loading.cljs [hunk 2]
```diff
@@ -124,15 +113,28 @@
...
+                    (let [message
+                          ;; For example, when a user receives a list of 4 image messages while inside
+                          ;; the chat screen we
+                          ;; shouldn't group the images into albums. When the user exists the chat screen
+                          ;; then enters the
+                          ;; chat screen again, we now need to group the images into albums (like
+                          ;; WhatsApp). The albumize?
+                          ;; boolean is used to know whether we need to group these images into albums
+                          ;; now or not. The
+                          ;; album-id can't be used for this because it will always be there.
```
Comment (OmarBasem) [inline src/status_im/chat/models/loading.cljs]: fix comments lining please

**Review by OmarBasem — APPROVED** [review]
Good job looks good. Have you tested it for a long list of messages? (performance is okay, and albumization does not break?)

**Comment by yqrashawn** [comment]
> Good job looks good. Have you tested it for a long list of messages? (performance is okay, and albumization does not break?)

Not tested, this should be same as in develop, right? `:albumize? true` in `:messages` won't affect anything apart from when rebuilding messages.

File: src/status_im/chat/models/loading.cljs (hunk 2 above)
Comment (yqrashawn) [reply src/status_im/chat/models/loading.cljs]: done

**Comment by OmarBasem** [comment]
> > Good job looks good. Have you tested it for a long list of messages? (performance is okay, and albumization does not break?)
> 
> Not tested, this should be same as in develop, right? `:albumize? true` in `:messages` won't affect anything apart from when rebuilding messages.

Yes should be same, but better to double check.

**Comment by pavloburykh** [comment]
Hey @yqrashawn ! Thanx for the PR. I noticed that you have pushed some new commit after PR has been taken into work by QA team. 

Please, try to request manual QA only after all necessary work is done within the PR as we might need to re-test PR from scratch when new changes are pushed depending on severity of changes. 

In case if you still need to push some additional fixes (which for sure can happen) after PR has been already taken by QAs into work, please leave a comment describing if those commits can affect functionality (cause regression) and if re-testing on new builds is needed. 

That will both help preventing missed bugs get merged into develop and save time of QAs. Thank you!

**Comment by yqrashawn** [comment]
> Hey @yqrashawn ! Thanx for the PR. I noticed that you have pushed some new commit after PR has been taken into work by QA team. 
> 
> 
> 
> Please, try to request manual QA only after all necessary work is done within the PR as we might need to re-test PR from scratch when new changes are pushed depending on severity of changes. 
> 
> 
> 
> In case if you still need to push some additional fixes (which for sure can happen) after PR has been already taken by QAs into work, please leave a comment describing if those commits can affect functionality (cause regression) and if re-testing on new builds is needed. 
> 
> 
> 
> That will both help preventing missed bugs get merged into develop and save time of QAs. Thank you! 

Hi, that's only rebase against develop.

**Comment by pavloburykh** [comment]
> Hi, that's only rebase against develop.

Cool. Thanx for clarifying @yqrashawn ! I just misunderstood and thought that this one was some additional change commit, not rebasing. Sorry for that. Rebasing is totally okay to be done at any time))) Thank you! 

fix: mark :albumize? true when rebuild message by yqrashawn · Pull Request #15286 · status-im:status-mobile 2023-03-16 10-15-00

**Comment by pavloburykh** [comment]
@yqrashawn thanx for the PR. Please take a look at the following issue

### ISSUE 1 Albums still lost after deleting message in group chats

**Steps:** 

1. Create group chat
2. Send message containing album with images
3. Re-enter chat in order images start displaying as an album
4. Send any other message
5. Delete this message
6. See if message with images still displayed as an album

**Actual result:** album is lost, images are displayed separately from each other. 


https://user-images.githubusercontent.com/97245802/225656928-19cc26f0-42e8-4cdd-925a-82da63b9d1d6.mp4

**Comment by yqrashawn** [comment]
Hi @pavloburykh, tried delete messages w/o image from me and others, can't reproduce ISSUE1

**Comment by pavloburykh** [comment]
> Hi @pavloburykh, tried delete messages w/o image from me and others, can't reproduce ISSUE1

Hi @yqrashawn Sorry, I must have messed up with builds. Just re-checked and it works correct for me. PR is ready to be merged.
