### PR TITLE
Improve and Fix Unmute Behavior for Chats and Communities

### LINKED ISSUE #20977: "Muted for.." community/channel is not unmuted after the specified time has passed
# Bug Report

## Problem 

https://github.com/user-attachments/assets/c63e9bab-2bc1-45b1-be17-13ba44173e2c

### Reproduction

1. Mute a channel for 15 mins
2. Close the app 
3. Wait >15 mins
4. Open the app 
5. Cgeck if the channel is unmuted

#### Expected behavior
The channel is automatically unmuted

#### Actual behavior

Sometimes it takes a while for the channel to unmute, sometimes it only gets unmuted after opening and closing the channel. 
The same issue is reproducible for communities

### Additional Information

- Status version: RC 2.30 https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F2.30.x/8/ 
- Operating System: Android, iOS
- Logs: 
[Archive.zip](https://github.com/user-attachments/files/16530883/Archive.zip)

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20977

#### Improvements/Bug fixes
- Previously, we only considered the timezone offset for the hour portion, which worked well for timezones with whole-hour offsets. However, for timezones with minute offsets, such as India (UTC+5:30), this approach ignored the minute component, resulting in incorrect mute timer label.
- While managing communities, we only processed communities with higher clock values, which led to ignoring signals for unmuting communities with the same clock values.

#### Status-go Improvements/Bug fixes
PR: https://github.com/status-im/status-go/pull/5720
- Execute the initial check immediately upon starting to unmute chats for which the mute timer has expired.
- If a user mutes a chat for 1 minute at 11:12:33, the client displays the mute status as lasting until 11:13. Consequently, the chat should be unmuted as soon as 11:14. Currently, the routine does not run precisely at the top of the minute (hh:mm:00), leading to inconsistencies where the mute timer may expire, but the chat remains muted. Status-go PR ensures that the unmute timer is synchronized to run exactly on the 00 seconds mark.

#### Testing
I replaced the 1-week timer with a 1-minute timer for testing purposes.

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/events_test.cljs [hunk 1]
```diff
@@ -181,9 +181,4 @@
 
     (testing "given a community with lower clock"
       (let [effects (events/handle-community {:db {:communities {community-id {:clock 3}}}} [community])]
-        (is (nil? effects))))
-
-    (testing "given a community without clock"
-      (let [community #js {:id community-id}
-            effects   (events/handle-community {} [community])]
```
Comment (Parveshdhull) [inline src/status_im/contexts/communities/events_test.cljs:188]: The test is incorrect. Instead of evaluating the community without a clock, it is currently testing the community with a clock but an empty eb.

Comment (Parveshdhull) [inline src/status_im/contexts/communities/events_test.cljs:188]: The test is incorrect. Instead of evaluating the community without a clock, it is currently testing the community with a clock but an empty db.

File: src/status_im/constants.cljs [hunk 2]
```diff
@@ -53,7 +53,7 @@
 (def ^:const mute-for-15-mins-type 1)
 (def ^:const mute-for-1-hour-type 2)
 (def ^:const mute-for-8-hours-type 3)
-(def ^:const mute-for-1-week 4)
+(def ^:const mute-for-1-week 6)
```
Comment (Parveshdhull) [inline src/status_im/constants.cljs]: Replaced the 1-week timer with a 1-minute timer for testing purposes. (Should be reverted before merging)

**Review by flexsurfer — APPROVED** [review]

**Review by qfrank — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
Hi, @Parveshdhull !
Could you please rebase both the status-go and mobile branches onto the PR so that I can test the actual builds?

**Comment by Horupa-Olena** [comment]
Thanks @Parveshdhull! 

PR can be merged!
