### PR TITLE
[Fix][#14890] Added support for pinned message notification in reply notification

### LINKED ISSUE #14890: 'No matching clause: 6' when opening AC when receiving notification that your message was pinned
# Bug Report

## Problem 

_Confirmation is needed that receiving notifications in the Activity center when your message is pinned is expected._

### Reproduction

1. UserA: add to contacts UserB, create a community, and invite UserB
2. UserB: join the community, send a message, go to the home screen
3. UserA: pin the message
4. UserB: try to open AC

#### Expected behavior
Could not find information in the designs confirming that notification in AC is expected for the member whose message was pinned by the admin.
So the likely expected result is:
- no notification
- no error

#### Actual behavior

- error
- the app freezes until relogin and opening the channel (not through AC)

https://user-images.githubusercontent.com/67952253/214590973-e565b9a9-adcd-4106-a026-33e82ec5a280.MP4

### Additional Information

- Status version: nightly 25/01
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #14890 

### Summary

This fix adds support for the pinned message notifications in the Reply type to prevent the crashing of the Activity Center. Currently, we don't have a design for pinned message notifications; hence, the red border.

Simulator Screen Shot - iPhone 14 - 2023-01-26 at 17 01 51

### Steps to reproduce

**Preconditions:** `User A` and `User B` are mutual contacts

1. User A creates a community and shares it with User B
2. User B join the community and send a message
3. User B moves to the home screen
4. User A pins the message sent by User B to the channel
5. User B receives an unread indicator in the AC and tries to open it

status: ready

### CODE REVIEW

File: src/status_im2/contexts/activity_center/notification/reply/view.cljs [hunk 1]
```diff
@@ -21,11 +22,19 @@
...
+    constants/content-type-text        (get-in message [:content :text])
 
-    constants/content-type-image   [old-message/message-content-image message]
+    constants/content-type-image       [old-message/message-content-image message]
 
-    constants/content-type-sticker [old-message/sticker message]))
+    constants/content-type-sticker     [old-message/sticker message]
+
+    ;; NOTE: The following type (system-text) doesn't have a design yet.
+    ;; We added the support for this type temporarily to prevent crashing of AC.
```
Comment (ilmotta) [inline src/status_im2/contexts/activity_center/notification/reply/view.cljs]: It would be nice to add the related issue link here. Another option would be to remove the comment and just rely on the GH issue to keep track of the work left to be done.

**Review by ilmotta — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hi @smohamedjavid, please rebase this PR against the latest develop.
Thank you!

**Review by J-Son89 — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fix @smohamedjavid!
PR can be merged.
