### PR TITLE
Top bar fixes

### LINKED ISSUE #16160: Issues related to top bar appearing in the chat
introduced by https://github.com/status-im/status-mobile/pull/15204
### Steps to reproduce:
1. Open a chat with only a few messages.
2. Start typing and sending messages in the chat. (check the tap bar during each message sending)

### Actual result:
As the user types and sends messages, the top bar of the chat screen does not appear and only the 'back' button is shown instead

https://github.com/status-im/status-mobile/assets/52490791/85c56cd0-b0f1-44f3-87dd-c32809fcdb38

### Expected result:
When the user starts typing and sending messages in a chat with only a few messages, the top bar of the chat screen should appear

### Additional info:
Sometimes the top bar does not appear even after reopening the chat if there are only a few messages in the chat. This behavior has been observed when there are approximately 10 messages in the chat.

### Device:
iPhone 11 pro max, IOS 16

### LINKED ISSUE #16163: [iOS] Flickering occurs when sending the first message in chat
Introduced by https://github.com/status-im/status-mobile/pull/15204
cc: @alwx 

### Steps to reproduce:
1. Open a chat with no previous messages
2. Send the message.

### Actual result:
When sending the first message, a flickering effect is observed in the chat screen.

https://github.com/status-im/status-mobile/assets/52490791/24e66df1-4f35-4324-b638-fc2ce5c371aa

### Expected result:
Sending the first message should not result in flickering in the chat screen.

### LINKED ISSUE #16164: [Android] Flickering occurs on Android when focusing on the input field in an empty chat screen
introduced by https://github.com/status-im/status-mobile/pull/15204
CC: @alwx 

### Steps to reproduce:
1. Open a chat screen with no previous messages
2. Tap on the input field (composer) to focus on it.

### Actual result:
When focusing on the input field in an empty chat screen on Android, a flickering effect occurs. 

https://github.com/status-im/status-mobile/assets/52490791/cd945195-c807-430b-ba38-a422f9946204

### Expected result:
Focusing on the input field in an empty chat screen on Android should not result in flickering

### Devices:
- Real device: Pixel 7a, Android 13
- Android Studio: Pixel XL API 29

### PR DESCRIPTION
**Pull request by alwx**
Fixes https://github.com/status-im/status-mobile/issues/16160
Fixes #16164
Also fixes https://github.com/status-im/status-mobile/issues/16163

### Summary

- utilizes `on-content-size-change` to update `scroll-y` value
- get rids of (almost) all of the top bar bugs — it doesn't flicker now, and it's animation gets updated properly when something changes in the layout (for example, new messages appear)

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

**Comment by alwx** [comment]
There is one known issue not directly connected to the top bar: sometimes when you send a new message the keyboard closes and it all jumps a bit.

File: src/status_im2/contexts/chat/messages/navigation/view.cljs [hunk 1]
```diff
@@ -14,42 +14,44 @@
...
+                                    (rf/sub [:chats/all-loaded? (:chat-id chat)]))
+        display-name              (if (= chat-type constants/one-to-one-chat-type)
+                                    (first (rf/sub [:contacts/contact-two-names-by-identity chat-id]))
+                                    (str emoji " " chat-name))
+        online?                   (rf/sub [:visibility-status-updates/online? chat-id])
+        contact                   (when-not group-chat
+                                    (rf/sub [:contacts/contact-by-address chat-id]))
+        photo-path                (when-not (empty? (:images contact))
+                                    (rf/sub [:chats/photo-path chat-id]))
+        opacity-animation         (reanimated/interpolate scroll-y
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/messages/navigation/view.cljs:32]: I find this whole block hard to read, perhaps you could pull these animations into helper functions?

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 2]
```diff
@@ -338,32 +352,32 @@
...
+        content-height                           (reanimated/use-shared-value 0)
         {:keys [keyboard-height keyboard-shown]} (hooks/use-keyboard)]
     (rn/use-effect
      (fn []
-       (when keyboard-shown
-         (reanimated/set-shared-value scroll-y
-                                      (+ (reanimated/get-shared-value scroll-y)
-                                         keyboard-height))))
+       (reanimated/set-shared-value scroll-y
+                                    (+ (reanimated/get-shared-value scroll-y)
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: imo it's easier to read with the if statement at the top. 
e.g
```
(reanimated/set-shared-value scroll-y
                               (if keyboard-shown
                              (+ (reanimated/get-shared-value scroll-y) keyboard-height)
                              (- (reanimated/get-shared-value scroll-y) keyboard-height))))
 ```

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 3]
```diff
@@ -251,18 +252,16 @@
...
-      [rn/view
-       (add-inverted-y-android {:background-color (colors/theme-colors colors/white colors/neutral-95)})
-       (if (= type :datemark)
-         [quo/divider-date value]
-         (if (= content-type constants/content-type-gap)
-           [message.gap/gap message-data]
-           [message/message message-data context keyboard-shown?]))])))
+    [rn/view
+     (add-inverted-y-android {:background-color (colors/theme-colors colors/white colors/neutral-95)})
+     (if (= type :datemark)
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: I see not related to this pr, but while you're here can we use `cond` here to avoid nested if's?

**Review by vkjr — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 4]
```diff
@@ -25,6 +25,7 @@
 (defonce ^:const loading-indicator-page-loading-height 100)
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/messages/list/view.cljs:25]: The value of `:scroll-event-throttle` in this file needs to be `8` to have 120 hz animations

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/list/view.cljs:25]: I partially agree with the suggestion @OmarBasem because I think we should probably be careful with this setting and not blindly use 8. Ideally, we should have a way to know if the hardware can take advantage of high refresh rates, otherwise we just make the experience worse for a bunch of users.

Obviously it's not something for this PR to implement, so I'll leave an issue open about this concern/problem in case somebody can work on it.

Comment (OmarBasem) [reply src/status_im2/contexts/chat/messages/list/view.cljs:25]: @ilmotta there is an open issue :) https://github.com/status-im/status-mobile/issues/14924

**Comment by churik** [comment]
@alwx please, ping when all comments are addressed and PR is ready for manual-qa, thanks!

File: src/status_im2/contexts/chat/messages/navigation/view.cljs (hunk 1 above)
Comment (alwx) [reply src/status_im2/contexts/chat/messages/navigation/view.cljs:32]: could you elaborate? 
all those animations are pretty different and use different values, and I think moving them to separate functions and hiding them somewhere else would make it harder to understand what's going on

**Comment by alwx** [comment]
@churik all the comments are just some minor refactoring suggestions. you can do the manual QA in the meantime

File: src/status_im2/contexts/chat/messages/navigation/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im2/contexts/chat/messages/navigation/view.cljs:32]: actually I think it's just from the smaller window in the git diff view it appears this way, looking at the file in isolation it's fine to read. So I think it's fine to leave as is 👌

**Review by J-Son89 — APPROVED** [review]

**Comment by alwx** [comment]
Note for testers: I don't expect it to be perfect in every aspect. The goal was to get rid of flickering and make the positioning of the top bar right + avoid situations when top bar is not visible when it should clearly be.

**Review by Francesca-G — COMMENTED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3350%3A274771&mode=design&t=HifnL7wq7x6ouCq2-1) with a couple of comments.

Here's also a video about a problem I still had (on iOS only), the bar didn't appear while I was typing and it took a while for it to appear:


https://github.com/status-im/status-mobile/assets/122543089/81690d95-1fdf-493b-bc5e-a5ac6dafa9a3

**Comment by pavloburykh** [comment]
> Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3350%3A274771&mode=design&t=HifnL7wq7x6ouCq2-1) with a couple of comments.
> 
> Here's also a video about a problem I still had (on iOS only), the bar didn't appear while I was typing and it took a while for it to appear:
> 
>  RPReplay_Final1689078374.mp4

Hi @Francesca-G ! Thank you for your review. This is a known issue, we also faced it during testing of this PR. I believe that it can be addressed separately in a followup (as well as comments left in [Figma](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3350%3A274771&mode=design&t=HifnL7wq7x6ouCq2-1)) cause overall top bar looks much better than before and most of the issues are gone. As we are close to cutting the release branch we would not want to block this PR. 

@alwx thank you for the fixes. Let's merge it.

**Comment by pavloburykh** [comment]
@alwx I have logged a followup with the remaining issues https://github.com/status-im/status-mobile/issues/16564

File: src/status_im2/contexts/chat/messages/list/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im2/contexts/chat/messages/list/view.cljs:25]: @ilmotta @OmarBasem 
I think there won't be a problem if we set the `scroll-event-throttle` to 8, since at much it is the screen's refresh rate.
But keep in mind this will only work on iOS, idk how to set it on Android.

please check: https://reactnative.dev/docs/0.69/scrollview#scrolleventthrottle-ios

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/list/view.cljs:25]: I agree with you @ulisesmac. We just need to be mindful IMO and not use 8 unless a significant difference can be felt in the UX, so by default start from higher values and lower only after proper experimentation. In some views doubling or tripling the frequency of events can be significant, because usually each call to the scroll event can cause a mutation in a ratom, which in turn re-renders the world.

Comment (ulisesmac) [reply src/status_im2/contexts/chat/messages/list/view.cljs:25]: I agree, completely makes sense :+1:
