### PR TITLE
fix: use custom color for confirm select

### LINKED ISSUE #17564: Design review: Posts  & Attachments - confirm selection button background color
# Bug Report
Currently the confirm selection of photos button does not implement custom color as is on the figma.
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6130:58226&mode=design#567119172

#### Expected behavior
The confirm selection button should have customization color

#### Actual behavior
The confirm selection button has blue color

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
Fixes https://github.com/status-im/status-mobile/issues/17564

### Summary
The confirm selection button in the image picker didn't use the customization color of the user's profile. This fixes it.

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by OmarBasem — APPROVED** [review]

File: src/status_im2/contexts/chat/photo_selector/view.cljs [hunk 1]
```diff
@@ -35,15 +35,16 @@
   (close))
 
 (defn confirm-button
-  [selected-images sending-image close]
+  [selected-images sending-image close customization-color]
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/photo_selector/view.cljs]: Can you make this list of args a map?

**Review by J-Son89 — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@BalogunofAfrica thank you for PR. Ready to be merged
