### PR TITLE
Fix swaps received value UI bug

### LINKED ISSUE #21462: [Android] Long numbers in swap receive field not properly displayed
### Steps:
1. Go to swap
2. Select some 18 decimals token in the receiving value

### Actual result:
- The number is not shown from the beginning in the receive field.

Pixel XL API 33 (Android studion)
image

Pixel 7a, Android 13
image

### Additional info:

[NOTE] There's an Android bug in our current version of React Native (0.73) that prevents us to position the text input at the start of it (https://github.com/facebook/react-native/issues/44171), thus will be fixed once we update to 0.74+ where this seems to be fixed (https://github.com/reactwg/react-native-releases/issues/283)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #21462

### Summary
The received value wasn't rendered properly on Android due to a RN input bug, so using a RN text component instead. Also fixed the gradient color at the end of the value if the digits overflow.

### Steps to test

- Open Status
- Open swaps
- Swap a token that results in many decimals

status: ready

### CODE REVIEW

File: src/quo/components/wallet/swap_input/view.cljs [hunk 1]
```diff
@@ -121,33 +121,38 @@
...
-                      :auto-focus               auto-focus?
-                      :on-focus                 on-input-focus
-                      :on-change-text           on-change-text
-                      :on-layout                on-layout-text-input
-                      :on-selection-change      on-selection-change
-                      :show-soft-input-on-focus show-keyboard?
-                      :default-value            default-value
-                      :placeholder              "0"}
-               controlled-input? (assoc :value value))]]
+            (if pay?
```
Comment (briansztamfater) [inline src/quo/components/wallet/swap_input/view.cljs]: Maybe, would be better to check for `disabled?` or `input-disabled?` instead of `pay?` (or both?). We might want to be able to edit the receiver value in the future. But we can be sure that if the input is disabled, using a Text component is safe.

Comment (clauxx) [reply src/quo/components/wallet/swap_input/view.cljs]: thanks, using `input-disabled?` should do it, since it's the prop that actually disables the input :+1:

Comment (clauxx) [reply src/quo/components/wallet/swap_input/view.cljs]: @briansztamfater done :+1:

**Review by briansztamfater — APPROVED** [review]
🚀

**Review by vkjr — APPROVED** [review]

**Comment by pavloburykh** [comment]
@clauxx thanks for the fix. Ready for merge.
