### PR TITLE
Fix design inconsistencies on onboarding notifications screen

### LINKED ISSUE #15492: Onboarding notifications screens design inconsistencies
followup of https://github.com/status-im/status-mobile/pull/15370 cc @jo-mut

Restore/Sync notification screens have a few differences in comparison to Create new account notification screens: different button color and welcome text.
Those differences are not taken into account in current implementation

**Steps:** 

1. Proceed onboarding using Restore account flow
2. See if onboarding notification screens correspond to the designs. Pay attention at buttons color and Welcome text

**Expected result:** 

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4338-575146&t=uK2HsSO2bYyGLnXP-0

Onboarding for Mobile – Figma 2023-03-24 13-12-50

**Actual result:** 

- buttons are red. 
- "Welcome to web3" instead of "Welcome back!" text

photo_2023-03-24 13 16 08
photo_2023-03-24 13 16 11

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
Fixes #15492

Attention: The text "Welcome back" will be shown on welcome screen in case of recovery or when using the old key generation flow (decided not to fix it for this particular case since the old flow will be removed anyway)

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/status_im2/contexts/onboarding/common/style.cljs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+  {:flex             1
+   :padding-top      (:top insets)
+   :background-color colors/neutral-80-opa-80-blur})
+
+(def title-container
+  {:justify-content    :center
+   :margin-top         12
+   :padding-horizontal default-margin})
+
+(def title-text
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/common/style.cljs]: hmm, I believe we don't want to add common stylings that are used in multiple views. It would be better to be created as common components instead since they all use the same configuration.

```
(ns status-im2.contexts.onboarding.common.components

(defn title [{:keys [accessibility-label] }]
 [quo/text
    {:accessibility-label accessibility-label
     :weight              :semi-bold
     :size                :heading-1
     :style               onboarding-style/title-text})
    ```

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/common/style.cljs]: but tbh, in the case of title component it should actually be created in quo2 as there is this standard title component:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=8824-151323&t=TiQujkTRkiSuEyu7-0

File: src/status_im2/contexts/onboarding/enable_notifications/view.cljs [hunk 2]
```diff
@@ -60,12 +61,14 @@
...
   []
-  [rn/view {:style style/enable-notifications}
-   [background/view true]
-   [navigation-bar]
-   [page-title]
-   [rn/view {:style style/page-illustration}
-    [quo/text
-     "[Illustration here]"]]
-   [enable-notification-buttons]])
+  [safe-area/consumer
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/enable_notifications/view.cljs:61]: @flexsurfer are we still going to be using safe area now that the new designs are using the full screen? I remember some conversation where we eventually will move away from this? 🤔

**Review by jo-mut — COMMENTED** [review]
looks okay to me but I agree with @J-Son89

File: src/status_im2/contexts/onboarding/enable_notifications/view.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im2/contexts/onboarding/enable_notifications/view.cljs:61]: it is still needed because we need padding for status bar

File: src/quo2/components/title/title.cljs [hunk 3]
```diff
@@ -0,0 +1,25 @@
+(ns quo2.components.title.title
```
Comment (J-Son89) [inline src/quo2/components/title/title.cljs]: We have a best practice for the quo2 namespaces.

Each component is in its Figma Category and its Figma title.
In this case it should be:

quo2.components.text-combinations.title.view
and the style file is then in 
quo2.components.text-combinations.title.style

File: src/status_im2/contexts/quo_preview/main.cljs [hunk 4]
```diff
@@ -282,6 +283,9 @@
                            {:name      :token-tag
                             :insets    {:top false}
                             :component token-tag/preview-token-tag}]
+   :title                 [{:name      :title
```
Comment (J-Son89) [inline src/status_im2/contexts/quo_preview/main.cljs]: this also should be adjusted.
It should be `:text-combinations [{:name :title...`

This keeps it aligned with Figma and easier to find components 👍

File: ios/Podfile.lock [hunk 5]
```diff
@@ -210,7 +210,7 @@ PODS:
     - React
   - react-native-blob-util (0.13.18):
     - React-Core
```
Comment (J-Son89) [inline ios/Podfile.lock]: I guess this should be reverted

File: src/quo2/components/title/style.cljs [hunk 6]
```diff
@@ -0,0 +1,18 @@
+(ns quo2.components.title.style
+  (:require
+    [quo2.foundations.colors :as colors]))
+
+(def default-margin 20)
```
Comment (J-Son89) [inline src/quo2/components/title/style.cljs]: do we need to add this? Often it is easier to add the margin/padding at the page level and then all components within that page view container can sure that padding.

File: src/status_im2/contexts/quo_preview/title/title.cljs [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+
+(defn preview-title
+  []
+  [rn/view
+   {:background-color (colors/theme-colors colors/white colors/neutral-90)
+    :flex             1}
+   [rn/flat-list
+    {:flex                      1
+     :flex-grow                 1
+     :nestedScrollEnabled       true
```
Comment (J-Son89) [inline src/status_im2/contexts/quo_preview/title/title.cljs]: these keys can be camel case, most of the new preview screens have them adjusted now.

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/quo_preview/title/title.cljs (hunk 7 above)
Comment (alwx) [reply src/status_im2/contexts/quo_preview/title/title.cljs:39]: I just copied this — it's not like I was writing this component :) but I will update.

**Comment by pavloburykh** [comment]
hi @alwx. Thanx for the PR. Please take a look at the issue below. 

### ISSUE 1 "u.call is not a function" error and crash on creating multiaccount

**Steps:** 

1. Intall app
2. Proceed with creating the account
3. See crash on Generating keys step

**Actual result:** 

photo_2023-04-04 17 19 09

https://user-images.githubusercontent.com/97245802/229822210-15e936dd-ec28-46ea-919c-23780a301f49.mp4

**Comment by pavloburykh** [comment]
@alwx JFYI, currently qa team is busy with release testing. We will proceed with PR testing as soon as we finish with release.

File: src/status_im2/contexts/onboarding/enable_notifications/view.cljs [hunk 8]
```diff
@@ -25,31 +26,23 @@
...
+  [rn/view {:style (style/buttons insets)}
    [quo/button
     {:on-press                  (fn []
                                   (rf/dispatch [::notifications/switch true platform/ios?])
                                   (rf/dispatch [:init-root :welcome]))
      :type                      :primary
      :before                    :i/notifications
      :accessibility-label       :enable-notifications-button
-     :override-background-color (colors/custom-color :magenta 60)}
+     :override-background-color (colors/custom-color :purple 60)}
```
Comment (jo-mut) [inline src/status_im2/contexts/onboarding/enable_notifications/view.cljs]: @alwx button colors in these screens are determined by the profile color. I think you might have to update this line to something like this code so that the button is updated with the color selected by the user when they are creating their profile 
```clojure
:override-background-color (colors/custom-color (:color (rf/sub [:onboarding-2/profile]) 60)
```

File: src/status_im2/contexts/onboarding/welcome/view.cljs [hunk 9]
```diff
@@ -39,17 +35,19 @@
...
+      [page-title]
+      [rn/view {:style style/page-illustration}
+       [quo/text
+        "Illustration here"]]
+      [rn/view {:style (style/buttons insets)}
+       [quo/button
+        {:on-press                  #(rf/dispatch [:init-root :shell-stack])
+         :type                      :primary
+         :accessibility-label       :welcome-button
+         :override-background-color (colors/custom-color :purple 60)}
```
Comment (jo-mut) [inline src/status_im2/contexts/onboarding/welcome/view.cljs]: same case here

**Review by jo-mut — APPROVED** [review]

**Comment by alwx** [comment]
@pavloburykh fixed!

**Comment by pavloburykh** [comment]
@alwx thanx for the fix. Ready to be merged.
