### PR TITLE
display group chat system message using new ui

### LINKED ISSUE #20488: Group chat system messages are from the old UI
# Bug Report

## Problem 
Likely related to https://github.com/status-im/status-mobile/issues/17076

#### Expected behavior
Design System for Mobile – Figma 2024-06-18 12-01-00

#### Actual behavior
IMAGE 2024-06-18 13:56:59

### Reproduction

1. Create group chat

### Additional Information

- Status version: nightly 18/06/24
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by jo-mut**
fixes https://github.com/status-im/status-mobile/issues/20488

### Summary
This pr. displays group chat system message using the new ui

### Figma

https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=11522-138410&t=nzRl5xrbCFgAZrgX-4

status: ready

### CODE REVIEW

File: src/quo/components/messages/system_message/view.cljs [hunk 1]
```diff
@@ -127,6 +127,15 @@
...
       [sm-timestamp timestamp theme]]]))
 
+(defn system-message-group
+  [{:keys [customization-color child]}]
+  [system-message-base
+   {:icon {:icon    :i/add-user
+           :color   (or customization-color :primary)
+           :opacity 5}}
+   [rn/view
+    child]])
```
Comment (ilmotta) [inline src/quo/components/messages/system_message/view.cljs]: Nitpick: this could go on the same line as `rn/view`.

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs [hunk 2]
```diff
@@ -126,14 +126,62 @@
...
+(defn render-parsed-text
+  [content]
+  (reduce (fn [acc e]
+            (resolve-group-system-message e acc))
+          [quo/text]
+          (:parsed-text content)))
+
+(defn group-system-message
+  [{:keys [chat-id timestamp-str content]} type]
+  (let [{contact-customization-color
```
Comment (ilmotta) [inline src/status_im/contexts/chat/messenger/messages/content/view.cljs]: This could be simply `{:keys [customization-color]}`, thus without the renaming.

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs [hunk 3]
```diff
@@ -126,14 +126,62 @@
...
+       :size              :xxxs
+       :ring?             false}]
+     [quo/text
+      {:weight :semi-bold
+       :style  {:margin-left 4}}
+      primary-name]]))
+
+
+(defn resolve-group-system-message
+  [{:keys [^js children]} acc]
```
Comment (ilmotta) [inline src/status_im/contexts/chat/messenger/messages/content/view.cljs]: I had the impression `(:parsed-text content)` returned CLJ data, in which case `children` here shouldn't have the `^js` type hint.

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs [hunk 4]
```diff
@@ -126,14 +126,62 @@
...
+  (conj acc
+        (reduce (fn [acc {:keys [type literal]}]
+                  (if (= type "mention")
+                    (conj acc [group-member literal])
+                    (conj acc
+                          [:<>
+                           [rn/view
+                            [quo/text literal]]])))
+                [:<>]
+                (conj children))))
```
Comment (ilmotta) [inline src/status_im/contexts/chat/messenger/messages/content/view.cljs]: The implementation of `conj` with one argument just returns the argument itself, so `conj` can be removed here.

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs [hunk 5]
```diff
@@ -126,14 +126,62 @@
...
+
+
+(defn resolve-group-system-message
+  [{:keys [^js children]} acc]
+  (conj acc
+        (reduce (fn [acc {:keys [type literal]}]
+                  (if (= type "mention")
+                    (conj acc [group-member literal])
+                    (conj acc
+                          [:<>
```
Comment (ilmotta) [inline src/status_im/contexts/chat/messenger/messages/content/view.cljs]: Looks like we don't need this wrapping `:<>`.

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs [hunk 6]
```diff
@@ -126,14 +126,62 @@
...
+       :ring?             false}]
+     [quo/text
+      {:weight :semi-bold
+       :style  {:margin-left 4}}
+      primary-name]]))
+
+
+(defn resolve-group-system-message
+  [{:keys [^js children]} acc]
+  (conj acc
```
Comment (ilmotta) [inline src/status_im/contexts/chat/messenger/messages/content/view.cljs]: The code could be a bit clearer if we avoided shadowing the outer `acc`. You could do that by not passing the `acc` to `resolve-group-system-message`.

It would look like this:

```clojure
(defn resolve-group-system-message
  [{:keys [children]}]
  (reduce (fn [acc {:keys [type literal]}]
            (if (= type "mention")
              (conj acc [group-member literal])
              (conj acc [rn/view [quo/text literal]])))
          [:<>]
          children))

(defn render-parsed-text
  [content]
  (reduce (fn [acc e]
            (conj acc (resolve-group-system-message e)))
          [quo/text]
          (:parsed-text content)))
```

**Review by ilmotta — APPROVED** [review]
I made a few minor suggestions, but from a superficial look, the UI looks good @jo-mut.

File: src/status_im/contexts/chat/messenger/messages/content/view.cljs (hunk 5 above)
Comment (jo-mut) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: there is probably a better way to achieve this with `flex-box` but without `:<>` the text is a little mis-aligned if you can notice it in the screenshot here

Screenshot 2024-07-25 at 14 26 49

Comment (jo-mut) [reply src/status_im/contexts/chat/messenger/messages/content/view.cljs]: actually your are right its not.

**Comment by mariia-skrypnyk** [comment]
Hi @jo-mut !

New UI looks much prettier!

Just a little issue:

ISSUE 1: The comma is moved to the second line

Screenshot 2024-07-26 at 12 57 32

Expected result: comma should not be moved alone to the next line

**Comment by jo-mut** [comment]
> Hi @jo-mut !
> 
> New UI looks much prettier!
> 
> Just a little issue:
> 
> ISSUE 1: The comma is moved to the second line
> 
> Screenshot 2024-07-26 at 12 57 32
> Expected result: comma should not be moved alone to the next line

thank you @mariia-skrypnyk. Let me see how to fix this one

**Comment by churik** [comment]
@mariia-skrypnyk how do you feel about merging this like it is and fixing issue as a followup, as it indeed much better?

**Comment by mariia-skrypnyk** [comment]
@churik yes, according to our situation it's worth merging as it is!
@jo-mut will create a follow up.

Please, merge your PR.
Good job!

**Comment by churik** [comment]
@jo-mut merge this one, yeey :)
