### PR TITLE
fix navigation to user profile

### LINKED ISSUE #15258: User is not navigated to the profile when clicking on their own profile link
# Bug Report

## Problem 
[comment]: # (A problem description)

User is not navigated to the profile when clicking on their own profile link.
We used browser tab for profile, so user is navigating to that

https://user-images.githubusercontent.com/17097240/223041827-4dcdf8f6-95dd-42aa-9edf-80c63c4ec16a.mp4

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/15258

status: ready

### CODE REVIEW

File: src/status_im/utils/universal_links/core.cljs [hunk 1]
```diff
@@ -109,8 +109,9 @@
   (log/info "universal-links: handling view profile" public-key)
   (cond
     (and public-key (new-chat.db/own-public-key? db public-key))
-    {:shell/change-tab-fx :browser-stack ;; Profile tab - Currently browser tab is used for profile
-     :pop-to-root-fx      :shell-stack}
+    (rf/merge cofx
+              {:pop-to-root-fx :shell-stack}
+              (navigation/navigate-to-cofx :my-profile nil))
```
Comment (ibrkhalil) [inline src/status_im/utils/universal_links/core.cljs:114]: How are we sure that there won't be a race condition between these two navigation actions?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/utils/universal_links/core.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/utils/universal_links/core.cljs:114]: cc: @flexsurfer ?

**Comment by Parveshdhull** [comment]
looks like, `test_deep_link_with_invalid_user_public_key_own_profile_key` got broken
cc: @churik

**Comment by churik** [comment]
checking, thanks!

**Comment by churik** [comment]
e2e are fixed. please mind my commit when merging.
Thank you for amazing job!

**Devices:**
- IPhone 12 Mini (IOS 14)
- Xiaomi Mi Note 9 Pro (Android 10)

File: src/status_im/utils/universal_links/core.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/utils/universal_links/core.cljs:114]: good question, in theory it might happen, because the effect is a map, and no guarantee it will be processed in order how it's in `fx/merge` macro, but this never happened, so just luck :)
