### PR TITLE
fix ios wrong status bar color in dark theme

### LINKED ISSUE #19720: status bar is black in a dark theme
Devices: iOS 13 (17.3.1) Samsung A34 (14.0)

Steps:

- Login to app
- Go to Profile-> Appearance
- Change theme to dark
- Return to Messages or Community screens

Actual result:

image

### LINKED ISSUE #20495: Wrong status bar color
Report: https://www.figma.com/design/tvE6qvOmcfJC5bjFpxJNoh?node-id=2-5#838350076

Discussion: https://discord.com/channels/1210237582470807632/1217173176086302821/1252624401732730985

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19720
fixes https://github.com/status-im/status-mobile/issues/20495

### Summary
https://github.com/status-im/status-mobile/issues/20495#issuecomment-2186858868

### Testing
Please make sure status-bar color is right after login (with, without banner, dark, light theme and both android and ios). Status bar will be broken on theme change, but it should be fixed as soon as app restarted.

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
fix was working on simulator, for some reason physical device is behaving differently. Will ping once fix is working on device.

**Comment by Parveshdhull** [comment]
Thank you @ilmotta @J-Son89 for your patience. PR is ready for review.

File: src/status_im/navigation/effects.cljs [hunk 1]
```diff
@@ -17,37 +16,36 @@
...
+                           :shell-stack
+                           view-id)]
+    [status-bar-theme nav-bar-color comp-id]))
 
 (defn reload-status-nav-color-fx
   [[view-id theme]]
   (when (and (= @state/root-id :shell-stack) view-id)
-    (let [[rnn-status-bar rn-status-bar nav-bar-color comp-id] (get-status-nav-color view-id theme)]
-      (if platform/ios?
-        (rn/set-status-bar-style rn-status-bar true)
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs:47]: removed update of status-bar color using rn. It only worked for simulator https://github.com/status-im/status-mobile/issues/20495#issuecomment-2186858868

**Review by ilmotta — APPROVED** [review]
@Parveshdhull, I'm approving this PR, but I can only check the app's behavior on Android, and on Android I couldn't find any regression. Nice work! Hopefully the fix will work on iOS.

I ignored status bar bugs as you suggested, but sharing here anyway as a reference for others.

Reproduction steps are:

1. OS in light/dark mode and app in dark mode, open the AC or Profile, then close it.
2. Notice the status bar uses the [wrong colors, dark text on dark bg](https://github.com/status-im/status-mobile/assets/46027/d76301d0-9a96-43a0-8803-3f2af0cd8765)
3. Open any bottom sheet, e.g press on the plus icon on the communities home screen. The status bar color will reset and be correct.

[status bar bug.webm](https://github.com/status-im/status-mobile/assets/46027/29cf93c9-74ac-4bca-bfb4-28bd22a9fce5)

**Comment by Parveshdhull** [comment]
Thank you very much @ilmotta for approving PR and testing.

> Reproduction steps are:

Please can you confirm you can reproduce this bug after a fresh login? As far as I know, this case only happens after changing the theme, which is out of scope and expected due to a technical bug.
(Known Issues Android - https://github.com/status-im/status-mobile/pull/19089#issue-2166896070)

**Comment by J-Son89** [comment]
@Parveshdhull testing this on ios, it seems to break on the wallet send flow. Not exactly sure why that is.
Perhaps because it starts using `navigate-to-within-stack`? 🤔

**Comment by ilmotta** [comment]
> Please can you confirm you can reproduce this bug after a fresh login? As far as I know, this case only happens after changing the theme, which is out of scope and expected due to a technical bug. (Known Issues Android - [#19089 (comment)](https://github.com/status-im/status-mobile/pull/19089#issue-2166896070))

Correct @Parveshdhull, the bug only happens if the theme was changed from within the app and disappears on relogin. It's a minor bug and not caused from this PR. I see this is well explained in that other PR :)

**Comment by Parveshdhull** [comment]
> @Parveshdhull testing this on ios, it seems to break on the wallet send flow. Not exactly sure why that is. Perhaps because it starts using `navigate-to-within-stack`? 🤔

Hi @J-Son89, Thank you very much for testing the PR. I am not able to reproduce the issue. Please can you provide a video with steps after fresh login(no theme changes).

**Comment by J-Son89** [comment]
Hey @Parveshdhull I tried to screen capture but on ios this changes the color of the status bar to red 😓 . So here is some screen shots from the flow.

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull !

Thanks for handling such tricky issues. 🫶
I saw no issues with status bar on both platforms while changing themes.
Failed e2e are not related so you can do merge!

**Comment by Parveshdhull** [comment]
> Hey @Parveshdhull I tried to screen capture but on ios this changes the color of the status bar to red 😓 . So here is some screen shots from the flow.

Thank you @J-Son89 for the screenshots. I will test the above screens and will try to reproduce the bug. If it will be reproducible, I will fix that flow in a separate PR.
