### PR TITLE
[#7135] Fix wrong password handling

### LINKED ISSUE #7135: When enter wrong password and trying to login endless spinner is shown instead of validation error
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: no validation error is shown when trying to login to app with wrong password.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
can see that I entered wrong password
wr_pass

### Reproduction
endless spinner

- Open Status
- Try to login with wrong password

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 18/12/2018
* Operating System: all
* Video: http://take.ms/DgSsV

#### Logs

```
15:35:31.597 - W - [jsserver] - [status-im.data-store.realm.core:251] - failed checking db encryption with Error: Unable to open a realm at path '/Users/curikovatm/Library/Application Support/Status/default.realm/accounts/0x03b56231b5df31258eacbe280f5ce27ab9d743b2e79f01a62a8ef94dc305af28': Realm file decryption failed.
15:35:31.597 - I - [jsserver] - [status-im.data-store.realm.core:252] - try to encrypt with old key
15:35:31.598 - W - [jsserver] - [status-im.accounts.login.core:44] - Could not change account {:message "Error: Unable to open a realm at path '/Users/curikovatm/Library/Application Support/Status/default.realm/accounts/0x03b56231b5df31258eacbe280f5ce27ab9d743b2e79f01a62a8ef94dc305af28': Realm file decryption failed.", :error :decryption-failed}
15:35:31.599 - D - [jsserver] - [status-im.utils.handlers:34] - Handling re-frame event:  :init.callback/account-change-error
15:35:33.558 - D - [jsserver] - [status-im.utils.handlers:34] - Handling re-frame event:  :mailserver/check-connection-timeout

```

### PR DESCRIPTION
**Pull request by rasom**
fix #7135 

Leftover after #7032. The node hasn't been started if the user entered a
wrong password, that's why `Statusgo.Verify` call has failed (it works
properly only with running node atm).

Implementation:
- the node is started with "dummy" configs if it's necessary to call
  `Statusgo.Verify` method
- on `Statusgo.Verify` callback node is stopped so that it can be
  started with proper configs on the next sign in attempt.

status: ready

### CODE REVIEW

File: src/status_im/node/core.cljs [hunk 1]
```diff
@@ -125,6 +125,13 @@
       :always
       (add-log-level log-level))))
 
+(defn get-node-config [db network]
```
Comment (mandrigin) [inline src/status_im/node/core.cljs]: maybe call it `get-dummy-node-config`? or `get-verification-config` with a short comment that the verification won't work if the node isn't started.

**Review by mandrigin — APPROVED** [review]
lgtm

File: src/status_im/node/core.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/node/core.cljs]: i actually restored a piece of code existed before last changes related to node management, but i don't mind to call it  `dummy-config` :)

Comment (rasom) [reply src/status_im/node/core.cljs]: honestly i would prefer to rewrite `VerifyAccountPassword` so that it can be used without running node, i suppose that's doable. Not a part of this PR though

Comment (rasom) [reply src/status_im/node/core.cljs]: changed

Comment (mandrigin) [reply src/status_im/node/core.cljs]: yeah, that is 100%, I just want to make sure that it is obvious that this code is a workaround for status-go problem

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@rasom 
If you tap on Sign in two times with wrong password -  spinner is shown an sign in button is unavailable. In any case user can edit password and sign in but I would expect that there is no spinner and  Sign in button is available.


Video: http://take.ms/tsojB
Log:
```
11:30:23.675 - D - [jsserver] - [status-im.data-store.realm.core:194] - closing account realm
11:30:23.677 - I - [jsserver] - [status-im.data-store.realm.core:245] - try to encrypt with password
11:30:23.677 - W - [jsserver] - [status-im.data-store.realm.core:251] - failed checking db encryption with Error: Unable to open a realm at path '/Users/curikovatm/Library/Application Support/Status/default.realm/accounts/0xf0c3dc4b62b887ba1784e552486f26f003d5a9f3df7c46239664863a9b98a151': Realm file decryption failed.
11:30:23.678 - I - [jsserver] - [status-im.data-store.realm.core:252] - try to encrypt with old key
11:30:23.680 - W - [jsserver] - [status-im.accounts.login.core:45] - Could not change account {:message "Error: Unable to open a realm at path '/Users/curikovatm/Library/Application Support/Status/default.realm/accounts/0xf0c3dc4b62b887ba1784e552486f26f003d5a9f3df7c46239664863a9b98a151': Realm file decryption failed.", :error :decryption-failed}
11:30:23.681 - D - [jsserver] - [status-im.utils.handlers:34] - Handling re-frame event:  :init.callback/account-change-error
11:30:23.999 - D - [RCTStatus] - ::statusGoEventCallback call - event:  {"type":"node.stopped","event":null}
11:30:23.999 - D - [RCTStatus] - ::emitStatusGoEvent call - event:  "{\"type\":\"node.stopped\",\"event\":null}"
11:30:24.002 - D - [RCTStatus] - ::onStatusGoEvent call - event:  {"type":"node.stopped","event":null}
11:30:24.005 - D - [jsserver] - [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
11:30:24.006 - D - [jsserver] - [status-im.events:777] - :event-str {"type":"node.stopped","event":null}
```

Not critical. let me know if it should be fixed separately

**Comment by rasom** [comment]
@churik just pushed a fix for this behavior

**Comment by churik** [comment]
@rasom Thanks a lot!
please, merge it and cherry pick for `release/desktop/0.9.0`

**Comment by rasom** [comment]
@churik done
