### PR TITLE
fix device theme change listener in ios

### LINKED ISSUE #15690: [IOS only] The UI is frozen after app comes back from the background when 'chat key' overlay is opened
#### Steps to reproduce:
1. Go to profile -> Open 'chat key' overlay
2. Go to the background
3. Return from the background
4. Try to tap UI elements

#### Actual result:
The UI is frozen after the app comes back from the background

https://user-images.githubusercontent.com/52490791/233143505-a0a00b55-a721-488f-a0a3-da72b8099575.mp4

#### Expected result:
UI elements are not frozen

#### ENV:
- Nightly: 18 Apr 2023

#### Device:
iPhone 11 pro max, IOS 16

### LINKED ISSUE #15708: IOS UI reloads after app comes from background
### Summary
IOS UI reloads after app comes from background

(not able to reproduce always)

https://user-images.githubusercontent.com/17097240/233444782-243bc5c5-ee52-44b3-98cb-1561a4e6ef64.MP4

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/15708
fixes https://github.com/status-im/status-mobile/issues/15690 

### Testing
Please check device theme changes in ios and Android, in foreground and background, and with and without overlay/popover
Note: On theme changing, the app state will remain the same, except for overlays/popovers, they will be dismissed

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hey @Parveshdhull, thanks for the fixes!
The [issue with the background](https://github.com/status-im/status-mobile/issues/15690) is indeed fixed, however, there is a new related bug:

### ISSUE 1: UI freezes if you open the 'chat key' popover and change device theme

**Steps:**
1. Open the 'chat key' popover
2. Change the device theme
3. Tap your name again

After this step, UI freezes until relogin.


https://user-images.githubusercontent.com/67952253/234335108-5b77f595-a75d-4429-b6cb-846d84912d96.MP4

**Comment by Parveshdhull** [comment]
hi @qoqobolo, Thank you very much for testing the PR.
Issue 1 should be fixed now

**Comment by qoqobolo** [comment]
Thank you @Parveshdhull!

We have a bit weird situation now.

In fact, Issue 1 is fixed, but I can still reproduce the freezing UI with the following steps:

1. Open profile
2. Change the device theme
3. Close profile

Sometimes you need to change the theme a couple of times to reproduce this.

And the behavior gets really weird, see the video:


https://user-images.githubusercontent.com/67952253/234538331-914e79f6-b822-4357-9f0d-a06e01016529.mp4

At first, UI is completely frozen except for the bottom tabs, but if you click on the wallet tab and then go back to the home screen and tap on the profile many times, the keyboard will open.
Also, after that, you can click on any button on the community or chat screen (i.e. `Discover` or tabs `Joined`, `Pending`, etc.), after which the `BROWSER` will open, and after that UI starts working normally again.

Screenshot 2023-04-26 at 11 56 28



And the thing is that now it is also reproduced on nightly **and** both on Android and iOS.

Yesterday, for the first time, I ran into a randomly freezing UI in [this PR](https://github.com/status-im/status-mobile/pull/15713). I did not find the exact steps to reproduce, but I notified @flexsurfer, and it was decided to investigate this bug later.

Now these two bugs have overlapped each other, and I'm not sure what we should do in this situation. What do you guys think @Parveshdhull @flexsurfer ?
Should I log it separately?

**Comment by qoqobolo** [comment]
UPD: it turned out there is a known issue https://github.com/status-im/status-mobile/issues/15310 and apparently it has nothing to do with the current PR. I'll add steps to reproduce to the issue and will check this PR briefly again, it looks good so far, I just spent some time investigating this mess.
Sorry for the fake ping!

**Comment by Parveshdhull** [comment]
Hi, thank you for finding this issue, yes it is probably same as https://github.com/status-im/status-mobile/issues/15310, I will look into that next.

**Comment by Parveshdhull** [comment]
So, I think what happens is on UI reloading, opacity and touch events of different tabs gets activated for some reason

File: src/status_im2/navigation/events.cljs [hunk 1]
```diff
@@ -140,3 +139,11 @@
                                            key-uid
                                            :keycard-pairing]))]
     {:set-root (if keycard-account? :multiaccounts-keycard :multiaccounts)}))
+
+(rf/defn dismiss-all-overlays
+  {:events [:dissmiss-all-overlays]}
+  [{:keys [db]}]
+  {:dissmiss-all-overlays-fx nil
+   :db                       (-> db
+                                 (dissoc :popover/popover)
```
Comment (flexsurfer) [inline src/status_im2/navigation/events.cljs:148]: what about bottom sheet ?

Comment (Parveshdhull) [reply src/status_im2/navigation/events.cljs:148]: hi @flexsurfer, Thank you for the reviewing PR.

I just skipped that one, because for all overlays `(navigation/dissmiss-all-overlays)` works/enough, except for above two. For these two we also have to remove them from db. (not sure why)

Comment (Parveshdhull) [reply src/status_im2/navigation/events.cljs:148]: added now
