### PR TITLE
[#20804] linear gradient exception

### LINKED ISSUE #20804: "com.facebook.react.bridge.JSApplicationIllegalArgumentException" Error on wallet page of mobile app when Desktop edits color of Watch-Only account
Unfortunately, there are no exact steps on how to reproduce this issue. Please refer to me in a DM, and I can share the seed phrase of this user.

### Steps:
1. Create user on Desktop
2. Sync with Desktop using mobile
3. Add watch only accounts on the dektop 
4. Select the following color:
image

### Actual result:
`com.facebook.react.bridge.JSApplicationIllegalArgumentException`error is shown

image

### Expected result:
No error is shown

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Additional info:
The current user can't be restored at all on the desktop 

image

### Moblie logs:
[logs.txt](https://github.com/user-attachments/files/16284666/logs.txt)

### Desktop logs:
[desktop logs.txt](https://github.com/user-attachments/files/16284711/desktop.logs.txt)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20804

## Summary

This PR adds a safety wrapper for the Linear Gradient component, as we've had multiple issues due to invalid colors being passed to the component.

Now when an invalid color is found it's substituted by `"transparent"` so that the app doesn't crash, and an error with the given wrong colors is logged.

Additionally, this PR solves another problem: we have mistakenly named the `flamingo` color in our codebase, it's called as `pink` in figma (https://www.figma.com/design/v98g9ZiaSHYUdKWrbFg9eM/Foundations?node-id=619-10064&t=aYNJmP11jE8eqoh8-0)

image

When we received `:pink` from status go it was resolved as `nil` so some components didn't render as expected (such as the `LinearGradient` crashing).

## Review notes

**IMPORTANT**
The `yin-yang` color is still not supported on mobile, but our accounts cards aren't crashing now :)

## Testing notes
- Please give a quick tour through the app, mostly focusing on places where the customization color is used.
- Before this PR, creating a profile on Desktop with the pink color and syncing it to mobile should be completely broken in terms of UI colors.

### Steps to test

- Create a Status profile
- Sync the profile on both Mobile and Desktop
- Create a watched account
- Change the color of the watched account to **pink** on Desktop
- On mobile, the wallet home account cards should look as expected
- Change the color of the watched account to **yin-yang* on Desktop
 - On mobile the account cards show transparent, but the app doesn't crash as before.

status: ready

### CODE REVIEW

File: src/quo/components/links/internal_link_card/user/view.cljs [hunk 1]
```diff
@@ -65,9 +65,8 @@
         :style               (style/container loading? theme size)}
        [loading-view theme]]
       [linear-gradient/linear-gradient
-       (assoc {:style (style/container loading? theme size)}
-              :colors
-              (linear-gradient-props theme customization-color))
+       {:style  (style/container loading? theme size)
+        :colors (linear-gradient-props theme customization-color)}
```
Comment (ulisesmac) [inline src/quo/components/links/internal_link_card/user/view.cljs:69]: Just fixing code style, this `assoc` was never needed

File: src/react_native/linear_gradient.cljs [hunk 2]
```diff
@@ -1,6 +1,39 @@
...
+                                                         (:colors props)))
+                                            [(:colors props)])]
+    (when (seq wrong-colors)
+      (log/error "Invalid color values in vector passed to Linear Gradient:"
+                 (reduce-kv (fn [s idx color]
+                              (str s "Index: " idx ", color: " (prn-str color)))
+                            "\n"
+                            wrong-colors)))
+    (into [linear-gradient* (assoc props :colors safe-colors)]
+          children)))
```
Comment (ulisesmac) [inline src/react_native/linear_gradient.cljs]: The new `linear-gradient` component. It is used exactly as before.

- It checks that the colors are given in a vector (due to the validations done on the vector).
- Checks that the colors are valid in a memoized callback, since this component might be animated, we don't want to run these validations if the colors don't change.
- Logs an error when there are invalid colors.

File: src/quo/foundations/colors.cljs [hunk 3]
```diff
@@ -239,7 +239,7 @@
                60 "#CC6438"}
    :army      {50 "#216266"
                60 "#1A4E52"}
-   :flamingo  {50 "#F66F8F"
+   :pink      {50 "#F66F8F"
                60 "#C55972"}
```
Comment (ulisesmac) [inline src/quo/foundations/colors.cljs:250]: These renames are needed to properly handle the `:pink` color coming from desktop via status-go.

File: src/react_native/linear_gradient.cljs (hunk 2 above)
Comment (ilmotta) [reply src/react_native/linear_gradient.cljs]: It looks as if most of the complication in the code is to check if the color is valid and report on invalid colors. This I think would be better handled by a schema because in release builds it's unnecessary to do these defensive checks and instrumentation is disabled in release builds. Another option if you don't want to go with the schema is to use `(when ^:boolean js/goog.DEBUG)` so the checks are elided in release builds.

What I'm suggesting is that we assume colors are correct in production and separate the code that does the runtime checks so that it's flagged behind `^:boolean js/goog.DEBUG`.

**Review by ilmotta — APPROVED** [review]

File: src/quo/foundations/colors.cljs (hunk 3 above)
Comment (smohamedjavid) [reply src/quo/foundations/colors.cljs:250]: @ulisesmac - `status-go` has `flamingo` in the constants. 

https://github.com/status-im/status-go/blob/625c11ced41e35e7893d4aecc65f03c1ee71a2f4/multiaccounts/common/const.go#L19

https://github.com/status-im/status-go/pull/4502

I guess the Desktop app hasn't changed from `:pink` to `:flamingo` or something went wrong.

Just a caution: If we change back to `pink`, this will affect the existing accounts created from mobile using the `flamingo` color.

Comment (ulisesmac) [reply src/quo/foundations/colors.cljs:250]: Hmm... 🤔

Status-go is returning the color as `:pink`, not as `:flamingo` and it exists as `:pink` on figma.

We haven't released the app officially, so I think we don't need to support accounts created with `:flamingo`. Wdyt?

I will improve this PR by adding a fallback for unknown customization colors (such as this example or the `:yin-yang` variant).

Comment (smohamedjavid) [reply src/quo/foundations/colors.cljs:250]: > Status-go is returning the color as :pink, not as :flamingo and it exists as :pink on figma.

Interesting 🤔 . My guess is the account is created from Desktop and used `pink` and it's synced with mobile which tries to find `pink` ( `flamingo`) and fails.

I guess we should change it back to `pink` in `status-go` If it's pink in the Design system. Not sure why we changed to `flamingo`. Nevertheless, we should change it back.

> We haven't released the app officially, so I think we don't need to support accounts created with :flamingo. Wdyt?

Yeah, The caution is just for QA. 

> I will improve this PR by adding a fallback for unknown customization colors (such as this example or the :yin-yang variant).

Yes, for sure.  I guess we should check with the list we support and update it to fallback (blue/primary) if we don't support. In that way, we keep the app usable without any crash. WDYT?

https://github.com/status-im/status-mobile/blob/a5c81824613ca931e9a770506b1d1c4f686cd58e/src/status_im/contexts/profile/rpc.cljs#L17

IMO, we should remove the `yin-yang` from the desktop to keep it the same as mobile.

Comment (ulisesmac) [reply src/quo/foundations/colors.cljs:250]: @smohamedjavid 

> Yes, for sure. I guess we should check with the list we support and update it to fallback (blue/primary) if we don't support. In that way, we keep the app usable without any crash. WDYT?

Yes, that's what I had in mind, that is what Desktop does, if we create an account with `:flamingo` desktop uses blue/primary.

File: src/react_native/linear_gradient.cljs [hunk 4]
```diff
@@ -1,6 +1,39 @@
...
+    [taoensso.timbre :as log]))
 
-(def linear-gradient (reagent/adapt-react-class LinearGradient))
+(def ^:private linear-gradient* (reagent/adapt-react-class LinearGradient))
+
+(defn- valid-color? [color]
+  (or (keyword? color)
+      (and (string? color)
+           (or (string/starts-with? color "#")
+               (string/starts-with? color "rgb")))))
```
Comment (briansztamfater) [inline src/react_native/linear_gradient.cljs]: Maybe useful for a color utils file

**Review by briansztamfater — APPROVED** [review]

File: src/react_native/linear_gradient.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/react_native/linear_gradient.cljs]: @ilmotta 
I'm not sure if we really want to do it.

The advantage of checking the colors on runtime is to be able to skip the exception that opened the current issue, it's better for a user that the app looks a bit different in terms of the color than completely crashes.

These exceptions have happened unexpectedly on release builds and this wrapper omits the exceptions without make them completely silent.

Comment (ulisesmac) [reply src/react_native/linear_gradient.cljs]: I pushed a change according to what you mentioned, please check it and LMK what do you think about it.

File: src/quo/foundations/colors.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/quo/foundations/colors.cljs:250]: @smohamedjavid

Instead of applying the fallback during parsing, since there'll be a lot of places where we receive a customization color and it's not only for a profile (e.g. a watched account, others' profiles, etc). I added the fallback in the foundations file, when we attempt to resolve an unknown color it fallbacks to `:blue`.

LMK if this solution fits your expectations and if you agree with it :)

File: src/react_native/linear_gradient.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/react_native/linear_gradient.cljs]: Thanks for the review @briansztamfater 

I'd prefer to move this to utils once we know it'll be reused, otherwise I think it's better to keep it here. wdyt?

File: src/react_native/linear_gradient.cljs (hunk 2 above)
Comment (ilmotta) [reply src/react_native/linear_gradient.cljs]: Thank you @ulisesmac, it's clearer now the intention of the code.

>  it's better for a user that the app looks a bit different in terms of the color than completely crashes.

100%, the app should never crash if possible.

> These exceptions have happened unexpectedly on release builds and this wrapper omits the exceptions without make them completely silent.

Just to confirm, the code you pushed now won't throw on unexpected colors? Because I completely agree with you that shouldn't happen.

File: src/react_native/linear_gradient.cljs (hunk 4 above)
Comment (briansztamfater) [reply src/react_native/linear_gradient.cljs]: I think that if we need to reuse a function in the future, we might forget that it's already defined privately in another file, leading to the risk of redeclaring the same function. Since this is a basic function for checking if a color is valid, it makes sense to move it to a utils file to avoid duplication.

However, I don't have a strong opinion on this and have already approved the PR 👍

Comment (ilmotta) [reply src/react_native/linear_gradient.cljs]: I also don't have a strong opinion, but I usually follow @briansztamfater suggestion on this topic. I like to think code should be organized based on its purpose, not on the highly volatile concept of being reusable.

**Review by smohamedjavid — APPROVED** [review]
Thanks @ulisesmac 🙌

File: src/react_native/linear_gradient.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/react_native/linear_gradient.cljs]: @ilmotta 

I've pushed changes again, the implementation doesn't crash if wrong colors are passed it only logs an error. This is the behavior for both debug and prod since we don't want to find unexpected crashes on release builds.

File: src/react_native/linear_gradient.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/react_native/linear_gradient.cljs]: I've moved it! Thanks for the feedback!

**Comment by Horupa-Olena** [comment]
Hi @ulisesmac  thanks for the PR! Checked on iOS and Android  - app works without crashing!
