### PR TITLE
[fix 3821] fix update-price to only update visible tokens

### LINKED ISSUE #3821: Wallet screen loads longer than usual because of lots of :update-prices-* events
### Description
*Type*: Bug

*Summary*: Switching to Wallet screen is really slow on the latest nightly. It takes 2-4s. Seems to be related to lots of`:update-prices-*` events being dispatched.

#### Expected behavior
Wallet screen loads as fast as usual. There are no unnecessary `:update-prices-*` events.

### Reproduction
- Open Status
- Go to Home 
- Switch to Wallet

### Additional Information
* Status version: nightly, April 10
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by yenda**
fix #3821

To test:

check if wallet works properly, check on testnet with STT and ETH if prices are displayed properly, checks if balance updates properly (compared to develop)

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/subs.cljs [hunk 1]
```diff
@@ -30,21 +32,42 @@
...
+  :<- [:get-current-account]
+  (fn [[network current-account]]
+    (let [chain (ethereum/network->chain-keyword network)]
+      (get-in current-account [:settings :wallet :visible-tokens chain]))))
+
+(re-frame/reg-sub :wallet/visible-assets
+  :<- [:network]
+  :<- [:wallet/visible-tokens-symbols]
+  (fn [[network visible-tokens-symbols]]
+    (concat [tokens/ethereum]
```
Comment (cammellos) [inline src/status_im/ui/screens/wallet/subs.cljs]: This could be `(conj tokens/ethereum (filter...)`

Comment (cammellos) [reply src/status_im/ui/screens/wallet/subs.cljs]: the other way around :)

**Review by cammellos — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]
