### PR TITLE
Fixes for screen where user locks network amounts to send

### LINKED ISSUE #20496: Lock network amount: initial value in the drawer is not predefined
# Problem

The initial value is not predefined in the drawer after network is long-pressed
Followup to [Lock network PR](https://github.com/status-im/status-mobile/pull/20413)

### Steps:
1. Go to the routes generation page
2. Enter the value that is available on at least one network
3. Long press on the network when the route is built

### Actual result:
The value is not predefined in the drawer after the network is long-pressed.

https://github.com/status-im/status-mobile/assets/52490791/e443599e-53ca-4a21-b766-6dcb8d72e2ea

### Expected result:
The value is predefined in the drawer after the network is long-pressed.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### LINKED ISSUE #20497: Lock network amount: long-press available for disabled network
# Problem

The long-press is available for disabled network
Followup to https://github.com/status-im/status-mobile/pull/20413

### Steps:
1. Go to the routes generation page
2. Enter the value that is available on at least two networks
3. Disable the network that is built (just short tap on it)
4. Long press on the disabled network

### Actual result:
The drawer is opened

https://github.com/status-im/status-mobile/assets/52490791/b54aa71e-44a6-44d0-969e-dcafff1777a0

### Expected result:
The drawer is not opened when the disabled network is long-pressed

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### LINKED ISSUE #20498: Warning message not displayed if custom value higher than entered value in routes generation page
Followup to https://github.com/status-im/status-mobile/pull/20413

### Steps:
1. Go to the routes generation page
2. Enter the value that is available on at least one network
3. Long press on the network when the route is built
4. Enter a value higher than the entered value on the routes generation page or higher than the maximum available value.

### Actual result:
"This value is higher than entered send amount" is not shown

### Expected result:
A warning message "This value is higher than entered send amount" should be displayed in cases:
- If the custom input is defined as 1 ETH and the routes generation value is defined as 0.9 ETH, 
- If the value in custom input is higher than routes generation value and higher than amount available for this particular network.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by vkjr**
fixes https://github.com/status-im/status-mobile/issues/20497
fixes https://github.com/status-im/status-mobile/issues/20496
fixes https://github.com/status-im/status-mobile/issues/20498

### Summary

- long press no more active on disabled router paths
- input field in drawer has initial value
- error message shown when input field contains valuer bigger than input field on send page

https://github.com/status-im/status-mobile/assets/5786310/1f1f3ae6-5213-4e70-b2d9-02444a1a08f1

##### Functional

- wallet / transactions

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 1]
```diff
@@ -366,7 +366,7 @@
        :on-token-press  show-select-asset-sheet}]
      [routes/view
       {:token                                     token-by-symbol
-       :input-value                               input-amount
+       :send-amount-in-crypto                     amount-in-crypto
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:372]: 👌

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 2]
```diff
@@ -133,6 +137,14 @@
                                                            (.toFixed (/ input-amount
                                                                         conversion-rate)
                                                                      crypto-decimals)))
+             amount-in-crypto-bn                        (money/bignumber amount-in-crypto)
+             send-amount-in-crypto-bn                   (money/bignumber send-amount-in-crypto)
+             lock-higher-than-send-amount?              (if (and (money/bignumber? amount-in-crypto-bn)
+                                                                 (money/bignumber?
+                                                                  send-amount-in-crypto-bn))
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/routes/view.cljs]: I find `-bn` to be a bit more confusing. Can we name it something else? perhaps we can just pass it as that? 🤔

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 3]
```diff
@@ -186,6 +198,12 @@
             :show-keyboard?  false
             :value           (controlled-input/input-value input-state)
             :on-swap         swap-between-fiat-and-crypto}]
+          (when lock-higher-than-send-amount?
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/routes/view.cljs]: what is lock-higher than. should be like `locked-greater-then-send-amount?` ?

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 4]
```diff
@@ -225,31 +244,32 @@
...
-                                         on-long-press (on-long-press chain-id)))}]])
+                  (let [status (cond (and (= type :not-available)
+                                          loading-routes?
+                                          token-not-supported-in-receiver-networks?)
+                                     :loading
+                                     (= type :not-available)
+                                     :disabled
+                                     :else type)]
+                    [rn/view
+                     {:key   (str (if receiver? "to" "from") "-" chain-id)
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/routes/view.cljs:260]: "to and "from" should be i18n labels, no? perhaps they both should take this chain-id as a param too so they're translatable?

File: translations/en.json [hunk 5]
```diff
@@ -2709,5 +2709,6 @@
     "not-enough-assets": "Not enough assets to pay gas fees",
     "send-from-network" : "Send from {{network}}",
     "define-amount-sent-from-network" : "Define amount sent from {{network}} network",
-    "dont-auto-recalculate-network": "Don't auto recalculate {{network}}"
+    "dont-auto-recalculate-network": "Don't auto recalculate {{network}}",
+    "value-higher-than-send-amount": "This value is higher than entered send amount"
```
Comment (J-Son89) [inline translations/en.json]: this text looks a bit off, perhaps we revisit? 🤔 
i.e "This value is higher than entered send amount"

should be like?

"This value is higher than entered amount to send" ??

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 3 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/send/routes/view.cljs]: thanks!

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 4 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/send/routes/view.cljs:260]: Well, it is `:key`, so it is probably unimportant. Moreover, we aren't sure how react will work with translated keys)

Comment (J-Son89) [reply src/status_im/contexts/wallet/send/routes/view.cljs:260]: Good point, I missed that

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 6]
```diff
@@ -133,6 +137,14 @@
...
                                                                         conversion-rate)
                                                                      crypto-decimals)))
+             locked-greater-then-send-amount?           (let [amount      (money/bignumber
+                                                                           amount-in-crypto)
+                                                              send-amount (money/bignumber
+                                                                           send-amount-in-crypto)]
+                                                          (if (and (money/bignumber? amount)
+                                                                   (money/bignumber? send-amount))
+                                                            (money/greater-than amount send-amount)
+                                                            false))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/routes/view.cljs]: I think this `if` can be simplified to just use the `and`:

```clojure
(and (money/bignumber? amount)
     (money/bignumber? send-amount)
     (money/greater-than amount send-amount))
```

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 7]
```diff
@@ -225,31 +244,32 @@
...
-                                       (cond
-                                         (= type :edit)
-                                         (open-preferences)
-                                         on-press (on-press chain-id total-amount)))
-                     :on-long-press #(when (not loading-routes?)
-                                       (cond
-                                         (= type :add)
-                                         (open-preferences)
-                                         on-long-press (on-long-press chain-id)))}]])
+                  (let [status (cond (and (= type :not-available)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/routes/view.cljs]: Better to destructure `type` using other name, I've seen many errors due to override clojure.core fns, such as `name`, `key` or `type`

**Review by ulisesmac — APPROVED** [review]
Looks good :+1:

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 6 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/send/routes/view.cljs]: Great suggestion, thanks!

**Comment by VolodLytvynenko** [comment]
@vkjr Thank you for PR. Just a few issues are found

## ISSUE 1: Checkbox not checked after value removal in assets customization drawer

### Steps:
1. Go to the routes generation page
2. Enter any value to build the routes
3. Long tap the network
4. Remove some last digits in the predefined value

### Actual result:
The checkbox is still shown as unchecked

https://github.com/status-im/status-mobile/assets/52490791/1df13cb5-8071-48a2-a061-bf75be231ad0

### Expected result:
The checkbox should be checked after any updates are made in the drawer, including the removal of the value

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 2: Predefined value not refreshed in drawer after asset change

### Steps:
1. Build a route on the routes generation page.
2. Long press the network and set up any value.
3. Change the asset.
4. Enter new value to build the routes
5. Long press the network again.

### Actual result:
The previous value is predefined

https://github.com/status-im/status-mobile/assets/52490791/8ce6bbaf-70f8-4dd5-a005-4a024765ce98

### Expected result:
The previous value should be refreshed after the asset is changed.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by VolodLytvynenko** [comment]
this issue is also present in develop. Could you fix this in the scope of the current PR? If not, I can create it separately

## ISSUE 3: Wrong UI of checkbox after unchecking

### Steps:
Unfortunately, there are no exact steps to reproduce this issue, but it happens very often. Just try to check and uncheck the checkbox a few times to reproduce it successfully.

### Actual result:
The UI of the checkbox is wrong after unchecking.

https://github.com/status-im/status-mobile/assets/52490791/ac9e4da0-1776-4134-b5f4-0610a0c1a481

### Expected result:
The UI of the checkbox should not be broken after unchecking.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by vkjr** [comment]
@VolodLytvynenko, thanks for the findings!

**Comment by vkjr** [comment]
@VolodLytvynenko, all issues should be resolved now)

**Comment by VolodLytvynenko** [comment]
hi @vkjr issues 1,2,3 are fixed. thank you. Sorry, I missed an additional edge case that could be an issue we need to handle. This might not be within the scope of this PR. Let me know if that's the case, and I'll create a separate issue.

### ISSUE 4: Route built incorrectly when customization drawer value exceeds total input value

### Steps: 
1. Go to the routes generation page.
2. Enter a total input value to build the route (e.g., 0.009 ETH).
3. Long press and set a value in the customization drawer to build an additional route (e.g., 0.008 ETH), checking the 'Don't recalculate' checkbox.
4. Enter a value in the total input that is less than the value set in the customization drawer (e.g., 0.001 ETH).

### Actual result:
The route is still shown as built with the following values:
- In FROM  section network still shown with 0.008 eth, in TO section 0.001 eth

https://github.com/status-im/status-mobile/assets/52490791/02962cce-6cab-4142-a67f-daf03c84b087

image


### Expected result:

Alternative Implementations:
- If a new value is entered in the total input, all customization setups should be refreshed.

OR
- Routes are not found message should be shown

OR
- We should agreed this with design team, probably additional validation message should be shown in the same way how this is implemented on Desktop:
In FROM  section the validation message is shown, route is not built
image

**Comment by vkjr** [comment]
@VolodLytvynenko, thanks for finding! I'd suggest to move this one to a separate issue and merge the PR with existing fixes, wdyt?

**Comment by VolodLytvynenko** [comment]
One more place where the customized value is not refreshed:

## PR_ISSUE 5: Predefined value not refreshed in drawer after account is changed

### Steps:
1. Restore user that has 2 accounts with available assets
2. Enter value in to total input to build the route
3. Long press the network
4. Enter in the customization some valid value with  checked 'don't recalculate' checkbox
5. Change the account
6. Enter new value in the total input (make it less than in the step 2)

### Actual result:
The route is built with predefined value from previous account 

https://github.com/status-im/status-mobile/assets/52490791/1a4919cd-b9a6-488b-98a5-c07313b59094


### Expected result:
The route is built without the predefined value from the previous account.

**Comment by VolodLytvynenko** [comment]
@vkjr, please take a look at [this issue](https://github.com/status-im/status-mobile/pull/20519#issuecomment-2200319422). If it's better to fix separately, then the PR can be merged.
