### PR TITLE
Fix loading screen for fetching community

### LINKED ISSUE #19555: Fix loading screen for fetching community
Dependent on designs for loading illustration for fetching the community.

# Bug Report
Remove the red square around fetching community when opening a newly shared community. Discuss with the design team or just make it somewhat presentable. Maybe add a button to cancel in case it takes too long or is stuck. Currently there seem to be no designs for this.

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19555

Please let me know if this looks ok or needs to be improved.

<table border="0">
 <tr>
    <td><b style="font-size:30px">Develop</b></td>
    <td><b style="font-size:30px">Fetching Community</b></td>
    <td><b style="font-size:30px">Failed to fetch</b></td>
 </tr>
 <tr>
    <td>

<div align="center">
Screenshot
</div>

</td>
    <td>

<div align="center">
Screenshot
</div>

</td>

<td> 

<div align="center">
Screenshot
</div>

</td>

 </tr>
</table>

### Testing
Please lightly test PR for fetching community screen and let me know if anything needs to be improved. (including design)

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
I am not sure if we need design review for this PR,as these designs are not implemented by design team :thinking:

**Review by clauxx — APPROVED** [review]
Thank you!

_a small preference, but i'd put the text below the image instead of the header, as I think the attention will be in the centre because of the cat 🐱. WDYT?_

**Comment by Parveshdhull** [comment]
Thank you @clauxx for reviewing the PR.

> a small preference, but i'd put the text below the image instead of the header, as I think the attention will be in the centre because of the cat 🐱. WDYT?

Yes, this is what I had initially. But without title, close button looks weird. Maybe we can use some other title for the screen :thinking:. Any suggestions?

**Comment by Parveshdhull** [comment]
> Maybe we can use some other title for the screen

Community screen? or Community Overview?

**Comment by Parveshdhull** [comment]
I think this also looks good

<div align="center">
Screenshot
</div>

**Comment by clauxx** [comment]
> Thank you @clauxx for reviewing the PR.
> 
> > a small preference, but i'd put the text below the image instead of the header, as I think the attention will be in the centre because of the cat 🐱. WDYT?
> 
> Yes, this is what I had initially. But without title, close button looks weird. Maybe we can use some other title for the screen 🤔. Any suggestions?

IMO it looks fine without a title, but up to you.

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im/contexts/communities/overview/view.cljs [hunk 1]
```diff
@@ -369,18 +370,24 @@
 
 (defn- community-fetching-placeholder
   [id]
-  (let [fetching? (rf/sub [:communities/fetching-community id])]
+  (let [theme      (quo.theme/use-theme)
+        margin-top (safe-area/get-top)
+        fetching?  (rf/sub [:communities/fetching-community id])]
     [rn/view
-     {:style               style/fetching-placeholder
+     {:style               (style/fetching-placeholder margin-top)
```
Comment (seanstrom) [inline src/status_im/contexts/communities/overview/view.cljs]: small nit 🔬 
maybe we can rename `margin-top` to `top-inset?

**Review by seanstrom — APPROVED** [review]
Looks good ✅ 
I left one tiny comment 👍 
And maybe we should double-check with design about the header title?

File: src/status_im/contexts/communities/overview/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/contexts/communities/overview/view.cljs]: done, thank you

**Comment by Parveshdhull** [comment]
Thank you @seanstrom for reviewing the PR.

> And maybe we should double-check with design about the header title?

Hi @Francesca-G as designs for loading screen while fetching community is [not available](https://github.com/status-im/status-mobile/issues/19555#issuecomment-2100125840), I have created this PR to show a temporary screen and get rid of red box. (Please check out PR description for screenshots).

Please let me know, if it looks ok or needs to be updated. Thank you

**Review by Francesca-G — APPROVED** [review]
Looks good to me 👍
only design note is that usually empty states have 2 lines, so I'd add the second line at least for the "failed" state:


Screenshot 2024-05-13 alle 14 49 54

**Comment by Parveshdhull** [comment]
Thank you @Francesca-G for checking the PR.

> so I'd add the second line at least for the "failed" state:

Updated failed state, thank you

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the PR. No issues from my side. After @Francesca-G approves PR is ready for merge.

**Comment by Parveshdhull** [comment]
Thank you very much @pavloburykh for testing the PR. I think @Francesca-G already approved the PR, so its ok to merge.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 2]
```diff
@@ -369,18 +370,25 @@
...
+     [quo/page-nav
+      {:title      "Community Overview"
+       :type       :title
+       :text-align :left
+       :icon-name  :i/close
+       :on-press   #(rf/dispatch [:navigate-back])}]
+     [quo/empty-state
+      {:image           (resources/get-themed-image :cat-in-box theme)
+       :description     (when-not fetching? (i18n/label :t/here-is-a-cat-in-a-box-instead))
+       :title           (if fetching? "Fetching community..." "Failed to fetch community")
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/overview/view.cljs:390]: @Parveshdhull, shouldn't this be in our translation files?

Comment (seanstrom) [reply src/status_im/contexts/communities/overview/view.cljs:390]: Ah yeah good catch 🙏
Most likely should be in the translation file

Comment (Parveshdhull) [reply src/status_im/contexts/communities/overview/view.cljs:390]: hi @ajayesivan, @seanstrom, Thank you for reviewing PR.

I didn't move them intentionally, as they were already in the file and I assumed that's what we do when we don't have proper designs and implementation is just temporary.
wdyt, should we move them to the translations file or handle them when implementing this placeholder when we have designs?

Comment (seanstrom) [reply src/status_im/contexts/communities/overview/view.cljs:390]: I see what you mean about these labels being temporary 👍

My only thought is that if this UI can be seen without a feature flag, then maybe the labels should be translatable. And later on if we want to change them we can decide to remove them or not. How does that sound?

Comment (Parveshdhull) [reply src/status_im/contexts/communities/overview/view.cljs:390]: sounds good, will move them to translations file in one of my PRs. thank you

Comment (seanstrom) [reply src/status_im/contexts/communities/overview/view.cljs:390]: Thank you @Parveshdhull 🙏
