### PR TITLE
Fix typed-data chainid check

### LINKED ISSUE #20939: Typed data signing fails on uniswap
# Bug Report

## Problem 
[comment]: # (A problem description)
When attempting to swap on Uniswap e.g. SNT -> DOGE, the request fails with "wrong chainId"

#### Expected behavior
The user can see the typed data signing request
#### Actual behavior
The user can't see the signing request

### Reproduction

1. Connect to uniswap
2. Try to swap SNT -> DOGE
3. Confirm transaction
4. Wait for the signing request
5. Error toast (not expected)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #20939

### Summary

For WalletConnect signTypedData requests, should only compare the typed data chainId param only if it's present in the typed data. Also different dapps send it sometimes as an int and sometimes as a string, so making sure the comparison accurate as well.

### Steps to test

- Connect to Uniswap dapp via walletconnect
- Try to swap SNT to DOGE
- Confirm transaction (not always triggered before signing typed data)
- See toast that chainId doesn't match, even though it does

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

File: src/status_im/contexts/wallet/wallet_connect/responding_events.cljs [hunk 1]
```diff
@@ -106,7 +106,11 @@
                  :method               method
                  :wallet-connect-event event
                  :event                :wallet-connect/on-sign-error})
-     {:fx [[:dispatch [:wallet-connect/dismiss-request-modal]]]})))
+     {:fx [[:dispatch [:wallet-connect/dismiss-request-modal]]
+           [:dispatch
+            [:toasts/upsert
```
Comment (shivekkhurana) [inline src/status_im/contexts/wallet/wallet_connect/responding_events.cljs:111]: Do we have a generic `something-went-wrong` toast dispatch handler ?

Comment (clauxx) [reply src/status_im/contexts/wallet/wallet_connect/responding_events.cljs:111]: Nope, we don't.

**Comment by qoqobolo** [comment]
@clauxx thanks for the fix. 
Found one minor issue in the error text on Sepolia, but since it's different from RC it might be worth taking a look

### ISSUE 1: `Expected '<no value>' but got '<no value>'` error when triggering `eth_signTypedData_v4` on testnet

**Steps:**
1. Switch to testnet 
2. Connect to https://react-app.walletconnect.com/
3. Trigger `eth_signTypedData_v4` event

**Expected error:** `Expected 'Mainnet Sepolia' but got 'Mainnet'`
**Actual error:** `Expected '<no value>' but got '<no value>'`

Would you like to fix it in this PR? Looks related to the changes here. 

**PR**

Screenshot 2024-08-01 at 14 35 46

**RC**

Screenshot 2024-08-01 at 14 36 27

**Comment by clauxx** [comment]
@qoqobolo thanks for finding this. Having a look, but should be definitely fixed here.

**Comment by clauxx** [comment]
@qoqobolo should be fixed now 👍

**Comment by qoqobolo** [comment]
Thank you @clauxx, everything looks good to me now.
PR can be merged and cherry-picked into the release branch.

File: src/status_im/contexts/wallet/wallet_connect/processing_events.cljs [hunk 2]
```diff
@@ -126,38 +126,37 @@
...
-         data-chain-id      (-> parsed-raw-data
-                                transforms/js->clj
-                                signing/typed-data-chain-id)
-         parsed-data        (try (-> parsed-raw-data
-                                     (transforms/js-dissoc :types :primaryType)
-                                     (transforms/js-stringify 2))
-                                 (catch js/Error _ nil))]
-     (cond
-       (nil? parsed-data)
+   (try
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/wallet_connect/processing_events.cljs:129]: Where can the exception be thrown? If we could add the try/catch surrounding only what can fail it would make clear where the problem can be.

Comment (clauxx) [reply src/status_im/contexts/wallet/wallet_connect/processing_events.cljs:129]: I was wondering how to do this in a cleaner way. The exception can only be thrown when parsing the JSON string here:
```clj
   (let [[address raw-data] (wallet-connect-core/get-db-current-request-params db)
         parsed-raw-data    (transforms/js-parse raw-data) ;; HERE
```
(...), but when catching we should short-circuit and return the dispatch fx. Do you have a suggestion on how to isolate it cleanly?

Comment (ilmotta) [reply src/status_im/contexts/wallet/wallet_connect/processing_events.cljs:129]: If it's the first thing to happen, you could extract to a separate function, catch and return nil and use `when-let`.

Comment (clauxx) [reply src/status_im/contexts/wallet/wallet_connect/processing_events.cljs:129]: but then we lose on the actual error, which would make it more difficult to understand the problem, no? and also `raw-data` and `address` are used later on as well.

Comment (ilmotta) [reply src/status_im/contexts/wallet/wallet_connect/processing_events.cljs:129]: Sorry I didn't look too deep.

We could return a tuple `[response, error]` like other languages do. Then that would give you room to reuse the values and also check if error exists.

```clojure
(let [[[address raw-data] err] (dangerous!)]
  (if err
    (error-effects)
    (success-effects)))
```

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/wallet/wallet_connect/processing_events.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/wallet_connect/processing_events.cljs:129]: And if you want to have a lot of fun, this talk about a condition system implemented in Clojure is too interesting https://youtu.be/zp0OEDcAro0?si=ssDADWNnSYzgam8a. Be aware of the rabbit hole!

Not the best day today, but another day, I'm sure you would enjoy and give you ideas :)
