### PR TITLE
fix error and app freezing when deselecting account one by one

### LINKED ISSUE #18753: Account selection: error and app freezing when deselecting account one by one
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/67952253/68e94bab-7c3d-4f4f-87e7-5e0a20bab0f5

### Reproduction

1. Create several accounts
2. Go to the account selection page
3. Start deselecting accounts one by one

#### Actual behavior
Error occurs and the app freezes 

#### Logs

[Status-debug-logs (85).zip](https://github.com/status-im/status-mobile/files/14199678/Status-debug-logs.85.zip)

### Additional Information

- Status version: https://github.com/status-im/status-mobile/pull/18530
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/18753

### Summary

**Note**: PR is based on https://github.com/status-im/status-mobile/pull/18530, and changes will be reverted before merging

What's fixed?
- Added null check for permission role so the app doesn't crash/freeze when selected addresses don't contain tokens needed
- Added info message `These addresses don’t contain tokens needed to join`

Out of Scope
- If the Permissions sheet is closed by swiping down instead of the cancel button then we will arrive at a [weird state](https://github.com/status-im/status-mobile/issues/18753#issuecomment-1933977943)
- Check for permissions to join the community is slow and a little inconsistent.

These issues are caused because we are changing the global state while toggling accounts instead of only updating the local state and then submitting when confirm is pressed. Probably there is a reason, why it is implemented this way. (Will log these issues)

status: ready

### CODE REVIEW

File: src/status_im/config.cljs [hunk 1]
```diff
@@ -167,5 +167,5 @@
 
 (def default-kdf-iterations 3200)
 
-(def community-accounts-selection-enabled? (enabled? (get-config :ACCOUNT_SELECTION_ENABLED "0")))
+(def community-accounts-selection-enabled? true)
```
Comment (J-Son89) [inline src/status_im/config.cljs]: can we move this to feature flags now that I merged the UI for feature flags pr? i.e https://github.com/status-im/status-mobile/pull/18602

 (not saying it has to be done in this pr)
cc @ilmotta @ajayesivan @FFFra

Comment (ajayesivan) [reply src/status_im/config.cljs]: I believe @ilmotta has done some work related to this. @ilmotta, if you don't have any objections, I can address this in a follow-up PR.

@Parveshdhull, for this PR, I suggest reverting these changes.

**Review by ajayesivan — APPROVED** [review]

**Comment by ajayesivan** [comment]
> These issues are caused because we are changing the global state while toggling accounts instead of only updating the local state and then submitting when confirm is pressed. Probably there is a reason, why it is implemented this way. (Will log these issues)

Initially, it was implemented with the[ local state](https://github.com/status-im/status-mobile/pull/18382) and later [moved to app db](https://github.com/status-im/status-mobile/pull/18430) as [discussed](https://github.com/status-im/status-mobile/pull/18382#discussion_r1442689518) with @ilmotta.

**Comment by qoqobolo** [comment]
> Out of Scope
If the Permissions sheet is closed by swiping down instead of the cancel button then we will arrive at a https://github.com/status-im/status-mobile/issues/18753#issuecomment-1933977943


@Parveshdhull FYI logged a feature request for this here: https://github.com/status-im/status-mobile/issues/18781

**Comment by Parveshdhull** [comment]
> > Out of Scope
> > If the Permissions sheet is closed by swiping down instead of the cancel button then we will arrive at a [#18753 (comment)](https://github.com/status-im/status-mobile/issues/18753#issuecomment-1933977943)
> 
> @Parveshdhull FYI logged a feature request for this here: #18781

Hi @qoqobolo, Thank you very much for taking the PR for testing.

I think the issue I am mentioning in the PR description is different from https://github.com/status-im/status-mobile/issues/18781. The issue I am reporting is that if we close account selection sheet with swipe (instead of cancel), then new changes will happen, even when we didn't press submit button.

(PS, these changes only happens locally, not updated in status-go. So will be reverted once, we reopen community. But until community reopened we have this [weird state](https://github.com/status-im/status-mobile/issues/18753#issuecomment-1933977943))

**Comment by qoqobolo** [comment]
The fix looks good to me, thanks for your work @Parveshdhull!
Do I understand correctly that this PR is not supposed to be merged?
Please do what needs to be done next :)

**Comment by qoqobolo** [comment]
> I think the issue I am mentioning in the PR description is different from https://github.com/status-im/status-mobile/issues/18781. The issue I am reporting is that if we close account selection sheet with swipe (instead of cancel), then new changes will happen, even when we didn't press submit button.

ah well, yes, now I understand what you mean, sorry.
I'll discuss with the team what we can do about it on Monday. In any case, this it's not related to your PR

**Comment by Parveshdhull** [comment]
>Do I understand correctly that this PR is not supposed to be merged?

No. As account selection feature is not enabled in develop, this PR is based on https://github.com/status-im/status-mobile/pull/18530 (As I mentioned in description). So Once the PR is tested and ready, I have to remove those commits from PR before merging.

> Please do what needs to be done next :)

Thank you 😅
