### PR TITLE
Fix incorrect background color in Community Overview screen

### LINKED ISSUE #16313: Incorrect background color in the Community overview screen
# Problem

When there are not enough community channels, the background doesn't occupy the screen's height. In fact, in Android, the background color is incorrect according to [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=8137-559113&t=GkdOR7DFgkScU1wI-0)

## Question

Open question: which color should we use when there's no community banner?

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/16313

### Summary

In this PR I'm fixing the main issue #16313, but also other correlated bugs (except for the top right button background which I couldn't resist fixing right here). This screen has even more UI bugs, but we'll fix them in other PRs.

- [x] Fix: quo2 component `navigation.page-nav` does not stretch out to the maximum available height when there are only 1 to ~6 community channels.
- [x] Fix: options menu button didn't use the correct background color (it should have 40% transparency).
- [x] Fix: Remove bottom-left & bottom-right rounded borders from the bottom of the `page-nav` container.
- [x] Fix: Remove top-left & top-right rounded borders from the screen's header.
- [x] Fix: Use correct background color in the `page-nav`, now `neutral-95` instead of `neutral-90`.

<table>
  <thead>
    <tr>
      <th>Before</th>
      <th>After</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

### Steps to test

- Create a community or open an existing one.

Suggestions:

- Test using a community with 1 channel to see the background color correctly stretches out.
- Test using a community with 10+ channels to see the community header animations are still intact.
- Test the Discover Communities screen, since the component this PR is fixing is also used in that screen. Spoiler, no changes should be visible.

status: ready

### CODE REVIEW

File: src/quo2/components/navigation/page_nav.cljs [hunk 1]
```diff
@@ -162,12 +163,13 @@
...
-                       :before         (when label icon)
-                       :size           32
-                       :override-theme icon-override-theme}
+                      {:on-press                  on-press
+                       :icon                      (not label)
+                       :type                      type
+                       :before                    (when label icon)
+                       :size                      32
+                       :override-theme            icon-override-theme
+                       :override-background-color icon-background-color}
```
Comment (ilmotta) [inline src/quo2/components/navigation/page_nav.cljs:172]: FYI: I used the exact same name `icon-background-color` that's used for the `left-section-view` component in this file. The prop was essentially missing.

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 2]
```diff
@@ -234,7 +235,9 @@
     :ellipsize-mode      :tail
     :weight              :semi-bold
     :size                :heading-1
-    :style               {:margin-top 56}}
+    :style               {:margin-top (+ scroll-page.style/picture-radius
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/overview/view.cljs:254]: FYI: I parameterized certain style values. I think this practice of magical values is one of the sources of constant bugs in the UI. The question I ask myself to decide if we need vars is: *if somebody changes the style value, will they remember to change this magical number?* If the answer is no, then ideally, vars/constants should be used.

**Review by jo-mut — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
nice @ilmotta!
