### PR TITLE
fix: assets sort order on bridge and assets screen

### LINKED ISSUE #20706: Assets are not shown in descending order of the fiat value on the 'select assets' and 'bridge' pages
### Steps:
1. Go to  'select assets' page
2. Go to the 'bridge' page

### Actual result:
Assets are not ordered  in descending order of the fiat value on the 'select assets' and 'bridge' pages
image
image

### Expected result:
Assets are ordered  in descending order of the fiat value on the 'select assets' and 'bridge' pages

discussed with 
https://discord.com/channels/624634427930312714/852533718790570015/1260505506280116335

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/20706

### Summary
This PR fixes sort order of assets on bridge and select assets screen to be in descending order of balance.

Simple fix, skipping QA.

### Demo

Before:

After:

### CODE REVIEW

File: src/status_im/subs/wallet/wallet.cljs [hunk 1]
```diff
@@ -416,7 +416,8 @@
                                      :total-balance     (utils/calculate-total-token-balance token
                                                                                              chain-ids)))
                             (:tokens account))
-         sorted-tokens (sort-by :name compare tokens)]
+         priority      #(get constants/token-sort-priority (:symbol %) 999)
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/wallet.cljs]: We have `##Inf` if you are willing to set the greatest integer: https://cljs.github.io/api/syntax/Inf

File: src/status_im/subs/wallet/wallet.cljs [hunk 2]
```diff
@@ -416,7 +416,8 @@
...
+         sorted-tokens (sort-by (juxt (comp - :balance) priority) tokens)]
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/wallet.cljs]: I think we should extract the `keyfn` function given to `sort-by` and provide it a name, It'll make easier to maintain.

Right now, I'm not sure if it's clear for everyone that this function is returning the pair of numbers:
 `[negative-balance arbitrary-priority]`
 To compare and sort them.
 
@OmarBasem  Could you please refactor this funciton? Since it'll be a pure funciton it can be defined outside the subscription.

**Review by ulisesmac — APPROVED** [review]
Thanks for the PR @OmarBasem ! :+1:  :+1:

**Review by smohamedjavid — APPROVED** [review]
