### PR TITLE
Add/Fix rebase overwritten event

### LINKED ISSUE #12548: Re-enable open-membership communities
As a user
I want to be able to create an open-membership community
So that I can embed my community on my website

### Description

We should re-enable open-membership communities (not the default option), so that we can create them and they can be embedded in dapps.

cc @D4nte

### PR DESCRIPTION
**Pull request by Jonathansoufer**
Re-enables community creation based on 2 types of membership:

- Require approval
- No requirement (Open Membership Community)

Fixes #12548 & Rebase problem based on the other PR 12883 mistakenly closed 

### Summary

This PR re-enables a feature which allows users to define three levels of community membership upon community creation. This feature was disabled by the issue #12147, and re-enabled now.
...

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
- community creation

##### Functional
- community creation

### Steps to test
- Open the app
- Create a community & specify one of the levels of membership

Status: WIP

https://user-images.githubusercontent.com/44679989/147708328-e03e204b-f57d-4759-bdcf-bbef53c7ac69.mov

### CODE REVIEW

File: src/status_im/communities/core.cljs [hunk 1]
```diff
@@ -221,12 +221,10 @@
...
   {:events [::create-confirmation-pressed]}
   [{:keys [db]}]
-  (let [{:keys [name description image]} (get db :communities/create)]
-    ;; If access is ENS only, we set the access to require approval and set the rule
-    ;; of ens only
+  (let [{:keys [name description membership image]} (get db :communities/create)]
     (let [params {:name name
                   :description description
-                  :membership constants/community-on-request-access
+                  :membership (or membership constants/community-no-membership-access)
```
Comment (Parveshdhull) [inline src/status_im/communities/core.cljs]: or is not required, we are assigning `community-no-membership-access` as default value while opening create community screen

File: src/status_im/ui/screens/profile/contact/views.cljs [hunk 2]
```diff
@@ -205,6 +205,7 @@
                                         :title    first-name
                                         :photo    (multiaccounts/displayed-photo contact)
                                         :monospace (not ens-verified)
+                                        :access second-name
```
Comment (Parveshdhull) [inline src/status_im/ui/screens/profile/contact/views.cljs]: are we using the `access` field?

**Review by Parveshdhull — APPROVED** [review]
other than above small changes, works great 🤘

File: src/status_im/communities/core.cljs (hunk 1 above)
Comment (Jonathansoufer) [reply src/status_im/communities/core.cljs]: Got it. Fixed.

File: src/status_im/ui/screens/profile/contact/views.cljs (hunk 2 above)
Comment (Jonathansoufer) [reply src/status_im/ui/screens/profile/contact/views.cljs]: Was a Left over. Fixed.

**Comment by qoqobolo** [comment]
@Jonathansoufer thanks for the PR!
Can you rebase it against the latest develop, please?

**Comment by Jonathansoufer** [comment]
> @Jonathansoufer thanks for the PR! Can you rebase it against the latest develop, please?

@qoqobolo  Done!

**Comment by qoqobolo** [comment]
@Jonathansoufer thanks!

One small remark: can I ask you to align the `Require approval` community type name in the community info view with the name in the creating community view, please?

I mean, can we have `Require approval` instead of `Request membership` to make it more precise?

Screenshot 2022-01-11 at 12 14 10


as indicated here 

Screenshot 2022-01-11 at 12 14 38

**Comment by Jonathansoufer** [comment]
> Require approval

@qoqobolo Done!

**Comment by qoqobolo** [comment]
Thanks for your work @Jonathansoufer!
LGTM, PR can be merged.
