### PR TITLE
fix: make run-ios-device script

### LINKED ISSUE #16310: `make run-ios-device DEVICE_NAME="YOUR DEVICE NAME"` fails while building with error code 65
# Bug Report

## Problem 
As reported first by @Parveshdhull and then by @igor-sirotin 
- make show-ios-devices : gives the name of attached iPhone properly
- when using the name of the connected iPhone like this : `make run-ios-device DEVICE_NAME="YOUR DEVICE NAME"` causes iOS build to fail with error code 65.

### Screenshots 

igor-ios-error

### PR DESCRIPTION
**Pull request by siddarthkay**
fixes #16310

## Summary
We used to reply on `react-native cli` and would pass a `--device` flag to deploy the debug variant of `iOS` app on connected `iPhone`.
`react-native cli` under the hood uses `ios-deploy` library to achieve this functionality.
This showed many weird issues, specifically in locating connected devices and failures at build step with ambiguous error messages.

This PR fixes it by using our custom script `run-ios-devices.sh` which does not rely on `ios-deploy`.
We use `libimobiledevice` to identify `UDID` of a connected `iPhone`.
We use `xcrun devicectl device install app` and `xcrun devicectl device process launch` to install and launch the app.

This works well with `Xcode 15` and `iOS 17.x`.
We can now remove `ios-deploy` from `iOS` shell and `nix` overlay.

## Review notes
- connect your iPhone to your Laptop via a cable
- `make run-clojure`
- `make run-ios-device` 
(note: no need to pass device name now)

## Screen recording

https://github.com/status-im/status-mobile/assets/64726664/40d5f4ff-cc1f-4865-978f-cc39279fb450

## Platforms
- iOS

status: ready

### CODE REVIEW

File: scripts/run-ios-device.sh [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+# Extract installationURL
+INSTALLATION_URL=$(echo "$DEVICECTL_OUTPUT" | grep "installationURL:" | sed -E 's/.*installationURL: (.*)/\1/')
+
+trap cleanupMetro EXIT ERR INT QUIT
+runMetro &
+waitForMetro
+
+# wait a bit after installation for the iPhone to calm down
+sleep 3
+
```
Comment (siddarthkay) [inline scripts/run-ios-device.sh]: sometimes the installed app would insta crash, 
This sleep was placed to test that.
The app sometimes still crashes, you can re-open it by tapping on the icon, not ideal DX however

Comment (siddarthkay) [reply scripts/run-ios-device.sh]: fixed with : https://github.com/status-im/status-mobile/pull/18845/commits/4e538e39e686bc72c5c5643b6dc8c2106d24d459

File: scripts/run-ios-device.sh [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+    rm -f metro-server-logs.log
+}
+
+# Using function gives a neater jobspec name.
+runMetro() {
+   nohup "${GIT_ROOT}/scripts/run-metro.sh" 2>&1 \
+        | tee metro-server-logs.log
+}
+
+waitForMetro() {
```
Comment (siddarthkay) [inline scripts/run-ios-device.sh]: I'll attempt to move `waitForMetro` , `runMetro ` and `cleanupMetro ` to a separate `scripts/lib` folder so that these 3 functions can be reused across scripts.

**Review by ajayesivan — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
🔥

**Review by alwx — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

File: scripts/run-ios-device.sh (hunk 2 above)
Comment (siddarthkay) [reply scripts/run-ios-device.sh]: cleaned up here -> https://github.com/status-im/status-mobile/pull/18845/commits/1d9191944aea879a447aabeb7e19fab0d98270f5

**Review by smohamedjavid — APPROVED** [review]

**Review by clauxx — APPROVED** [review]
Works well for me 👍

**Review by jakubgs — APPROVED** [review]
It's fine, but the inverted approach seems better.

**Comment by siddarthkay** [comment]
> but the inverted approach seems better.

I'm also in favour of the inverted approach, I'll get to this PR in sometime and I still need to rebase this to that approach.
