### PR TITLE
[#21686] User can not sign transactions after Login/Sign up flows usi…

### LINKED ISSUE #21686: User can not sign transactions after Login/Sign up flows using Keycard
# Bug Report

### Reproduction

**Part 1** (is not necessary but i've started from it just to check all the scenarios)

1. Migrate key pair to empty Keycard using such flow:

- Profile -> Keypair (use empty Keycard)

2. Login to your user from Step 1 using your Keycar
3. Go to Wallet
4. Send some assets/collectibles to check that signing is working in this scenario (Testnet/Mainnet works fine)

**Part 2**

1. Delete your Profile from Part 1
2. Use your Keycard from Part 1
3. Go to Log in -> Log in with Keycard
4. Go through Log in flow
5. Inside of your Profile send some assets/collectibles to check that signing is working ((Testnet/Mainnet no matter)

**Part 3**

1. Logout
2. Go to Create new profile
3. Use empty Keycard (Factory reset on Desktop can clear your card)
4. Go through Sign up with Keycard flow
5. Inside of your Profile send some assets/collectibles to check that signing is working (Testnet/Mainnet no matter)

#### Actual behavior

**Part 1**

-signing transactions works fine on both platforms, Testnet/Mainnet (ERC-20, not ERC-20, Collectible)

**Part 2** 

- iOS shows error and no password drawer oped

Image

- Android slide button just slides and nothing happen

https://github.com/user-attachments/assets/9445e697-b5c7-4381-a568-b9461f513054

**Part 3**

- iOS shows error and no password drawer oped
- Android shows error and no password drawer oped

Image

**Android logs:**

[Android_Keycard_Sign.zip](https://github.com/user-attachments/files/17921305/Android_Keycard_Sign.zip)

#### Expected behavior

user can sign in his transactions by his Keycard in all flows: Migration, Login and Sign up.

### Additional Information

- Status version: nightly 26/11
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21686

### CODE REVIEW

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs [hunk 1]
```diff
@@ -15,11 +15,22 @@
...
-                             :key-uid)]
+                             :key-uid)
+        keycard?        (get-in db [:profile/profile :keycard-pairing])
+        keypair         (first parsed-keypairs)]
     {:db (-> db
              (assoc-in [:wallet :keypairs] (utils.collection/index-by :key-uid parsed-keypairs))
-             (assoc-in [:wallet :ui :create-account :selected-keypair-uid] default-key-uid))}))
-
+             (assoc-in [:wallet :ui :create-account :selected-keypair-uid] default-key-uid))
+     ;; this is a temporary solution, should be done properly in statu-go instead
```
Comment (flexsurfer) [inline src/status_im/contexts/wallet/add_account/create_account/events.cljs:33]: that's how it works on desktop it's not like we're doing this only for mobile

Comment (ilmotta) [reply src/status_im/contexts/wallet/add_account/create_account/events.cljs:33]: @flexsurfer, could you elaborate in the PR description or in this comment what do you mean by _properly_? Better would be to have a GH issue detailing the problem and why this workaround is not sufficient so that other developers can come back to this problem with the full picture.

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs [hunk 2]
```diff
@@ -17,20 +17,24 @@
...
+                           :key-uid            default-key-uid
+                           :keycard-name       ""
+                           :accounts-addresses [(some #(when (:wallet %) (:address %))
+                                                      (:accounts keypair))]})]
     {:db (-> db
-             (assoc-in [:wallet :keypairs] (utils.collection/index-by :key-uid parsed-keypairs))
+             (assoc-in [:wallet :keypairs]
+                       (cond-> (utils.collection/index-by :key-uid parsed-keypairs)
+                         keycard
+                         (assoc-in [default-key-uid :keycards] [keycard])))
```
Comment (ilmotta) [inline src/status_im/contexts/wallet/add_account/create_account/events.cljs:31]: Isn't there a chance that `default-key-uid` will be nil because `some` won't
find any keypair with `:profile` type? If there's a chance, then we will `assoc` a
`nil` key into the `[:wallet :keypairs]`.

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/wallet/add_account/create_account/events.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/contexts/wallet/add_account/create_account/events.cljs:33]: i can remove this comment then, so that it doesn't embarrass anyone :) better solution would be to implement this in status-go during account creation, no need to have an extra call from "client", probably this will be implemented by desktop during onboarding refactoring

Comment (ilmotta) [reply src/status_im/contexts/wallet/add_account/create_account/events.cljs:33]: Your explanation is already clearer than the comment in the code because I see now what you mean by doing this at account creation. Thanks, up to you to judge what's best to do @flexsurfer

**Review by clauxx — APPROVED** [review]
Looks good :+1:

**Comment by mariia-skrypnyk** [comment]
Hey @flexsurfer !

Great job!
I've checked : 

Screenshot 2024-12-02 at 14 36 22

Collectibles are failed as I am blocked by https://github.com/status-im/status-mobile/issues/21702
I suggest to merge current PR and I will re-check these tests in develop.
