### PR TITLE
wallet: always displays fee with fixed precision

### LINKED ISSUE #1489: Different fee is shown for same sum after editing the sum [develop]
### Description

*Type*: Bug

*Summary*: 
Max fee to send 10 ETH is shown as "0.0008232" and later is shown as "0.0008232392" if edit the sum. If re-open screen Send transaction then again "0.0008232" is shown as max fee. It happens for non-default fee (e.g. max of min values). I would expect same fee with same precision shown for the same sum.

changed fee to max

changed sum back

#### Expected behavior
 same fee with same precision shown for the same sum.
#### Actual behavior
Max fee to send 10 ETH is shown as "0.0008232" and later is shown as "0.0008232392" if edit the sum. 

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7ZkIwSmVpMkVXRVU
- Open Status
- Open 1-1 chat
- send to a contact 10 Ether to get Send transaction screen with Fee
- move fee to be of a max or min value. In my case, I moved to to the most right position (Faster)
- remember the Fee value shown
- edit sum to be sent: make it "1". As a result, fee value is changed
- edit sum again and put it back to initial "10". Check the value for fee

### Additional Information
* Status version: develop 0.9.8-89-g20550b42+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #1489 

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
Previously, we displayed transaction fee as result of the `web3.fromWei` call without any further formatting, which sometimes caused inconsistent fee values even for the same tx amount and slider position, because they differed in precision.
This PR introduces change where transaction fee is always formatted to 7 decimal places, so it stays consistent.

### Steps to test:
- Open Status
- Open 1-1 chat
- Enter `/send` command, choose contact and enter tx value '10'
- Move tx fee slider to the right (maximal fee)
- Change the tx value to '1'
- Change the tx value to '10' again
- Observe that the fee value for tx value of '10' is always the same

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

File: bots/wallet/bot.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ function calculateFee(n, tx) {
     }
 
     var gasMultiplicator = Math.pow(1.4, n).toFixed(3);
-    return web3.fromWei(web3.eth.gasPrice * gasMultiplicator * estimatedGas, "ether");
+    return parseFloat(web3.fromWei(web3.eth.gasPrice * gasMultiplicator * estimatedGas, "ether")).toFixed(7);
```
Comment (jeluard) [inline bots/wallet/bot.js]: I'm a little surprised about fromWei result being a string. According to the [doc](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3fromwei) I would expect a number ? Then parseFloat is supposed to only accept [string](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/parseFloat) argument. 

Or is it a browser quirck? In this case we might want to check the type and parse accordingly.

Comment (janherich) [inline bots/wallet/bot.js]: No, parseFloat actually [parses numbers perfectly well](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat) (I can see that in french version of mozilla js doc, the signature reads `parseFloat(string)`, while in default english one, it's `parseFloat(value)`, very weird :))
The problem with `fromWei` is that sometimes it returns string, sometimes it's BigNumber (in my local testing, it seems to always return string the way how it's used in wallet bot), anyway I find the choice of multiple return type very poor and only complicating thing, running it through `parseFloat` makes sure it's number on which we can call `.toFixed(n)` method.

Comment (jeluard) [inline bots/wallet/bot.js]: Ahh weird I should probably not trust the french version.. Looks good to me then.
