### PR TITLE
[Fixes #6784] Fixed some ABI codec issues

### LINKED ISSUE #6784: Decoding of some smart contracts call is broken
# Problem

Call to one of Kyber's methods cannot be decoded. The type is `[uint256, uint256]`.

### PR DESCRIPTION
**Pull request by jeluard**
fixes #6784

### Summary:

Fixed some broken ABI codec

status: ready

### CODE REVIEW

File: src/status_im/utils/ethereum/abi_spec.cljs [hunk 1]
```diff
@@ -38,7 +38,7 @@
   (.hexToUtf8 utils (str "0x" x)))
 
 (defn hex-to-number [x]
-  (.hexToNumber utils (str "0x" x)))
+  (.toNumber (dependencies/Web3.prototype.toBigNumber (str "0x" x) 16)))
```
Comment (yenda) [inline src/status_im/utils/ethereum/abi_spec.cljs:41]: the idea of this lib was to avoid using web3 this defeats the purpose

Comment (jeluard) [reply src/status_im/utils/ethereum/abi_spec.cljs:41]: Unfortunately `hexToNumber` doesn't work as we expected it. Also here it's only about using BigNumber (used elsewhere like money), not web3.

File: test/cljs/status_im/test/utils/ethereum/abi_spec.cljs [hunk 2]
```diff
@@ -16,7 +16,10 @@
...
...0000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000036f6e650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000374776f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000057468726565000000000000000000000000000000000000000000000000000000"))
```
Comment (yenda) [inline test/cljs/status_im/test/utils/ethereum/abi_spec.cljs:19]: how come this test changed?

File: src/status_im/utils/ethereum/abi_spec.cljs (hunk 1 above)
Comment (jeluard) [reply src/status_im/utils/ethereum/abi_spec.cljs:41]: I could create a util function to hide it away.

File: test/cljs/status_im/test/utils/ethereum/abi_spec.cljs (hunk 2 above)
Comment (jeluard) [reply test/cljs/status_im/test/utils/ethereum/abi_spec.cljs:19]: Hmm some parenthesis issue apparently

Comment (jeluard) [reply test/cljs/status_im/test/utils/ethereum/abi_spec.cljs:19]: Oh that's because I added a test, so a parenthesis moved to next line

File: src/status_im/utils/ethereum/abi_spec.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/utils/ethereum/abi_spec.cljs:41]: just wondering why `hexToNumber` works different from our expectations, `utils` should provide functions to work with BN , so `(.toNumber (.toBN utils (str "0x" x) 16))`  should work

Comment (jeluard) [reply src/status_im/utils/ethereum/abi_spec.cljs:41]: @flexsurfer Just tried and it does not. It might be a BigNumber version issue.

**Review by flexsurfer — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by yenda — APPROVED** [review]
Can you add a comment to the BN change, why and what's TODO for future reference
