### PR TITLE
fix: bottom sheet padding

### LINKED ISSUE #16215: Too much bottom padding in bottom sheets

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/16215

This PR fixes the bottom padding in bottom sheets.

The bottom padding given to the bottom sheets in the designs is 8 (`Padding 0px, 0px, 8px, 0px`). The extra white space below is not directly part of a component design (the picture below shows the whole component bordered in purple lines -- the safe area is not part of the component). The difference in the white bottom area is due to the difference in bottom insets (safe area) on iOS and Android. This bottom inset would be different from device to device. Devices that have more curve on their edges would have bigger bottom insets. iPhones usually have more curve than Android devices, therefore their safe area at the bottom is bigger. A device with a smaller curve would have a smaller safe area (so even on iPhones with physical button like iPhone SE it wouldn't have that extra white space). Trying to manually add extra padding would mess up the component design.

Also, see https://github.com/status-im/status-mobile/issues/15885#issuecomment-1549176337 for a related explanation. 

Screenshot 2023-06-07 at 10 35 09

### CODE REVIEW

File: src/status_im2/common/bottom_sheet/styles.cljs [hunk 1]
```diff
@@ -14,7 +14,7 @@
    :margin-vertical  8})
 
 (defn sheet
-  [{:keys [top bottom]} window-height override-theme padding-bottom-override shell?]
+  [{:keys [top bottom]} window-height override-theme shell?]
```
Comment (flexsurfer) [inline src/status_im2/common/bottom_sheet/styles.cljs]: i believe `padding-bottom-override` is still needed and used, why remove it ?

**Comment by OmarBasem** [comment]
Before (Android):
Screenshot_20230607_104758_Status PR


After (Android - minimum padding of 20 applied):
Screenshot_20230607_112532_Status Debug

File: src/status_im2/common/bottom_sheet/styles.cljs [hunk 2]
```diff
@@ -25,10 +25,11 @@
    :border-top-right-radius 20
    :overflow                (when shell? :hidden)
    :flex                    1
-   :padding-bottom          (or padding-bottom-override (max 20 bottom))
+   :padding-bottom          (+ bottom 8)
```
Comment (flexsurfer) [inline src/status_im2/common/bottom_sheet/styles.cljs]: i believe designers say we should always have at least 20px padding thats why we have `(max 20 bottom)` cc @pedro-et

Comment (OmarBasem) [reply src/status_im2/common/bottom_sheet/styles.cljs]: If so I can update it (but the entries themselves also has padding, so..?)

I will ask for a design review

File: src/status_im2/common/bottom_sheet/styles.cljs (hunk 1 above)
Comment (OmarBasem) [reply src/status_im2/common/bottom_sheet/styles.cljs]: What is padding bottom override needed for?

Comment (flexsurfer) [reply src/status_im2/common/bottom_sheet/styles.cljs]: btw i think there is only one usage of it for now for removing padding at all

Comment (flexsurfer) [reply src/status_im2/common/bottom_sheet/styles.cljs]: `:padding-bottom-override 0`

File: src/status_im2/common/bottom_sheet/styles.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im2/common/bottom_sheet/styles.cljs]: we need requirements from the design team

File: src/status_im2/navigation/view.cljs [hunk 3]
```diff
@@ -69,17 +69,12 @@
         (when js/goog.DEBUG
           [reloader/reload-view])]))))
 
-; Designs require bottom inset to be bigger than safe area, otherwise it is too close to the bottom
-(defn bottom-sheet-insets
-  []
-  (assoc (safe-area/get-insets) :bottom 55))
```
Comment (flexsurfer) [inline src/status_im2/navigation/view.cljs:75]: wow what a strange code, how it was approved

File: src/status_im2/common/bottom_sheet/styles.cljs [hunk 4]
```diff
@@ -25,7 +25,7 @@
    :border-top-right-radius 20
    :overflow                (when shell? :hidden)
    :flex                    1
-   :padding-bottom          (or padding-bottom-override (max 20 bottom))
+   :padding-bottom          (or padding-bottom-override (max 20 (+ bottom 8)))
```
Comment (flexsurfer) [inline src/status_im2/common/bottom_sheet/styles.cljs]: i'm not sure about 20 btw , we should check with design team cc @J-Son89

File: src/status_im2/navigation/view.cljs (hunk 3 above)
Comment (OmarBasem) [reply src/status_im2/navigation/view.cljs:75]: Yeah very strange.. idk

File: src/status_im2/contexts/contacts/drawers/nickname_drawer/style.cljs [hunk 5]
```diff
@@ -19,9 +19,10 @@
    :justify-content :space-between
    :margin-top      20})
 
-(def nickname-container
+(defn nickname-container
+  [insets]
   {:margin-horizontal 20
-   :margin-bottom     (when platform/ios? 20)})
+   :margin-bottom     (when platform/ios? (max (:bottom insets) 20))})
```
Comment (ilmotta) [inline src/status_im2/contexts/contacts/drawers/nickname_drawer/style.cljs:25]: What do you think of creating a constant for the max bottom spacing? I see this number is used in another file.

File: src/status_im2/navigation/view.cljs (hunk 3 above)
Comment (ilmotta) [reply src/status_im2/navigation/view.cljs:75]: FYI: This is original discussion that led to this code: https://github.com/status-im/status-mobile/pull/15966/files#r1198917505

**Review by ilmotta — APPROVED** [review]
Looks much better @OmarBasem! I don't have much to comment on the code, so I'm approving, but as @flexsurfer said, we better double-check those details with designers.

File: src/status_im2/common/bottom_sheet/styles.cljs (hunk 4 above)
Comment (J-Son89) [reply src/status_im2/common/bottom_sheet/styles.cljs]: Thanks for the "@" @flexsurfer   Will get this checked 👌
