### PR TITLE
[bug] #2144 show warning when app is syncing

### LINKED ISSUE #2144: Wallet - show warning when app is syncing to tell user that it's not possible to use Wallet
Show warning when app is syncing to tell user that it's not possible to use Wallet.
@denis-sharypin can you pls update the mockup with the warning icon.

Per discussion - https://status-im.slack.com/archives/G75AL6HFS/p1507910859000298 : 
- If user attempts to tap any button or pull to refresh when the app is syncing then just display the label and ignore the requested action.
- When the app us syncing display the `Syncing` warning label

image

https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/59e494f4c25c11a0a5aa5b1d

### PR DESCRIPTION
**Pull request by yenda**
fix for #2144 

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/main/views.cljs [hunk 1]
```diff
@@ -75,10 +77,12 @@
       (i18n/label :t/wallet-total-value)]
      [change-display change]]
     [react/view {:style (merge button.styles/buttons-container styles/buttons)}
-     [btn/button {:on-press #(rf/dispatch [:navigate-to :wallet-send-transaction])
+     [btn/button {:disabled? syncing?
+                  :on-press (when-not syncing? #(rf/dispatch [:navigate-to :wallet-send-transaction]))
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/main/views.cljs]: `disabled?` already ensures `on-press` won't be called, this check is redundant.

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/wallet/styles.cljs [hunk 2]
```diff
@@ -43,10 +48,10 @@
 
 (defn button-container [enabled?]
   (merge
-    {:flex-direction :row
-     :align-items    :center}
-    (when-not enabled?
-      {:opacity 0.4})))
+   {:flex-direction :row
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/styles.cljs]: again, why does this happen?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/wallet/main/views.cljs [hunk 3]
```diff
@@ -137,10 +141,12 @@
...
             prices-loading?  [:prices-loading?]
+            sync-state       [:sync-state]
             balance-loading? [:wallet/balance-loading?]
             error-message    [:wallet/error-message?]]
-    [react/view {:style wallet.styles/wallet-container}
-     [toolbar-view]
-     [react/view components.styles/flex
-      [main-section portfolio-value portfolio-change error-message]
-      [asset-section balance prices-loading? balance-loading?]]]))
+    (let [syncing? (= sync-state :syncing)]
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/main/views.cljs]: Probably that could be another `sub`? Like `:syncing?`

File: src/status_im/ui/screens/wallet/styles.cljs (hunk 2 above)
Comment (yenda) [reply src/status_im/ui/screens/wallet/styles.cljs]: I think it's because a function name alone on a line and its arguments coming after is not very idiomatic so emacs doesn't deal with it

Comment (rasom) [reply src/status_im/ui/screens/wallet/styles.cljs]: https://github.com/bbatsov/clojure-style-guide#one-space-indent

**Review by rasom — APPROVED** [review]
