### PR TITLE
fix missing duration value in muted chat button text

### LINKED ISSUE #16768: [missing {{duration}} value] in muted chat button text
### Steps to reproduce:
1. Mute 1-1 or group chat (Until you turn it back on)
2. Long press the muted chat

### Actual result:
Caption is **Muted until [missing {{duration}} value] you turn it back on**
Screenshot 2023-07-24 at 16 55 52

### Expected result:
Caption is **Muted until you turn it back on**

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/16768

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/common/home/actions/view.cljs [hunk 1]
```diff
@@ -135,9 +135,7 @@
                                     :unmute-chat
                                     :mute-chat))
             :sub-label           (when (and muted? (some? muted-till))
-                                   (str (i18n/label :t/muted-until)
-                                        " "
-                                        (format-mute-till muted-till)))
+                                   (i18n/label :t/muted-until {:duration (format-mute-till muted-till)}))
```
Comment (J-Son89) [inline src/status_im2/common/home/actions/view.cljs:138]: 👍

**Review by J-Son89 — APPROVED** [review]

**Comment by J-Son89** [comment]
great stuff @Parveshdhull !

**Comment by VolodLytvynenko** [comment]
hi @Parveshdhull thank you for PR. No issues from my side. PR is ready to be merged
