### PR TITLE
Fix: actually run integration tests

### LINKED ISSUE #17895: Integration tests are not running
# Problem

We recently merged https://github.com/status-im/status-mobile/pull/17762, but we missed the fact that the integration tests are not running anymore.

In shadow-cljs, the regular expression looking for test namespaces expect them to end with `-test$` by default, but the code we merged don't respect this convention.

### Notes

We should probably allow each integration test namespace to run in isolation, thus `status_im2/integration_test/core.cljs` should not require other integration test namespaces.

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/17895

### Summary

Integration tests are not running anymore since https://github.com/status-im/status-mobile/pull/17762 was merged one week ago.

This PR also allows individual integration test namespaces to run if you change the `:ns-regexp` option in shadow-cljs. This is quite handy, since they are relatively slow.

#### Areas that may be impacted

None.

### Steps to test

The CI is already testing for us, just `make test`.

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

File: src/status_im/utils/test.cljs [hunk 1]
```diff
@@ -15,17 +15,21 @@
...
   (re-frame/dispatch [:signals/signal-received a]))
 
 ;; We poll for signals, could not get callback working
 (defn init!
   []
-  (.setSignalEventCallback native-status)
-  (js/setInterval (fn []
-                    (.pollSignal native-status signal-received-callback)
-                    100)))
+  (when-not @initialized?
```
Comment (ilmotta) [inline src/status_im/utils/test.cljs:27]: FYI: Here we make `init!` idempotent, so we can safely and automatically call it for every test using the macro `with-app-initialized`. This is what allows each namespace to run independently and in any order.

File: src/test_helpers/integration.cljs [hunk 2]
```diff
@@ -1,4 +1,5 @@
 (ns test-helpers.integration
+  (:require-macros [test-helpers.integration])
```
Comment (ilmotta) [inline src/test_helpers/integration.cljs:2]: FYI: Macros weren't loaded in `develop`, so nothing really worked.

**Review by J-Son89 — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]
🚀

**Comment by ilmotta** [comment]
Reviewers: @cammellos, @J-Son89, @mohsen-ghafouri, @briansztamfater

I just rebased and found that the wallet integration tests started to fail consistently. The culprit is probably the recent refactors made yesterday by commit 45df308dd0d0e2b3945a70f514dcf5fc5f596abe.

Unfortunately I couldn't get this PR merged before due to CI flakiness, hence I just moved on to other tasks.

Given that the scope of this PR is to re-enable integration tests and allow them to run independently, I just skipped the wallet integration tests to get this PR in. I'm going to create an issue to fix/re-implement them, so someone with more context can fix them.

Edit: issue to fix wallet integration tests created https://github.com/status-im/status-mobile/issues/17921

cc @ulisesmac

**Comment by ulisesmac** [comment]
> Reviewers: @cammellos, @J-Son89, @mohsen-ghafouri, @briansztamfater
> 
> I just rebased and found that the wallet integration tests started to fail consistently. The culprit is probably the recent refactors made yesterday by commit [45df308](https://github.com/status-im/status-mobile/commit/45df308dd0d0e2b3945a70f514dcf5fc5f596abe).
> 
> Unfortunately I couldn't get this PR merged before due to CI flakiness, hence I just moved on to other tasks.
> 
> Given that the scope of this PR is to re-enable integration tests and allow them to run independently, I just skipped the wallet integration tests to get this PR in. I'm going to create an issue to fix/re-implement them, so someone with more context can fix them.
> 
> Edit: issue to fix wallet integration tests created #17921
> 
> cc @ulisesmac

@ilmotta were those tests passing before you rebased?

I'm taking a look at the ns `status-im2.integration-test.wallet`, but I didn't touch any of the involved subscriptions :thinking: so I'm not sure about the root cause. 
What is the commit that disabled the integration tests?

### Edit:

:thinking:  I'm reading them, and those integrations tests are related to the previous wallet implementation (e.g. they extract the profile from `:profile/wallet-accounts` instead of `:wallet/accounts`), the PR I merged is about removing some root subs, also changed the app-db structure. So maybe that's the reason.

In any case, I think we should create new integration tests for the new wallet implementation, since these ones are not testing what we are building.

cc: @J-Son89

**Comment by ilmotta** [comment]
> > Reviewers: @cammellos, @J-Son89, @mohsen-ghafouri, @briansztamfater
> > I just rebased and found that the wallet integration tests started to fail consistently. The culprit is probably the recent refactors made yesterday by commit [45df308](https://github.com/status-im/status-mobile/commit/45df308dd0d0e2b3945a70f514dcf5fc5f596abe).
> > Unfortunately I couldn't get this PR merged before due to CI flakiness, hence I just moved on to other tasks.
> > Given that the scope of this PR is to re-enable integration tests and allow them to run independently, I just skipped the wallet integration tests to get this PR in. I'm going to create an issue to fix/re-implement them, so someone with more context can fix them.
> > Edit: issue to fix wallet integration tests created #17921
> > cc @ulisesmac
> 
> @ilmotta were those tests passing before you rebased?
> 
> I'm taking a look at the ns `status-im2.integration-test.wallet`, but I didn't touch any of the involved subscriptions 🤔 so I'm not sure about the root cause. What is the commit that disabled the integration tests?
> 
> ### Edit:
> 🤔 I'm reading them, and those integrations tests are related to the previous wallet implementation (e.g. they extract the profile from `:profile/wallet-accounts` instead of `:wallet/accounts`), the PR I merged is about removing some root subs, also changed the app-db structure. So maybe that's the reason.
> 
> In any case, I think we should create new integration tests for the new wallet implementation, since these ones are not testing what we are building.
> 
> cc: @J-Son89

It is as you said @ulisesmac. The tests were passing because this PR was working well and I ran them locally many times. After the recent changes refactors/changes in the wallet, this PR  started to fail. In the issue I created https://github.com/status-im/status-mobile/issues/17921 I mentioned we can totally remove or re-implement them if they don't make sense anymore, the wallet team can better judge the best course of action :)
