### PR TITLE
fix: `backup-recovery-phrase` check item pressability

### LINKED ISSUE #19704: backup-recovery-phrase check items pressability
On the screen `backup-recovery-phrase`, currently when pressing the checklist items, the press needs to be on the checkbox exactly. For a better user experience it would be better to make the whole item (checkbox + text) pressable

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19704

### Summary
This PR fixes a pressability issue on the `backup-recovery-phrase` screen when pressing the checklist items: the press needs to be on the checkbox exactly. For a better user experience it would be better to make the whole item (checkbox + text) pressable.

### Demo:

https://github.com/status-im/status-mobile/assets/29354102/3878b6d9-4af4-4e41-954d-14b52e8a4e27

### CODE REVIEW

**Comment by OmarBasem** [comment]
Simple fix, I think QA can be skipped

File: src/status_im/contexts/wallet/add_account/create_account/new_keypair/backup_recovery_phrase/view.cljs [hunk 1]
```diff
@@ -30,12 +30,18 @@
...
-   [quo/selectors
-    {:type                :checkbox
-     :customization-color customization-color
-     :on-change           #(swap! checked? assoc (keyword (str index)) %)}]
-   [quo/text {:style {:margin-left 12}} (i18n/label item)]])
+  (let [item-key (keyword (str index))
+        value    (get @checked? item-key)]
+    [rn/pressable
+     {:style    style/step-item
+      :hit-slop {:top 8 :bottom 8}
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/add_account/create_account/new_keypair/backup_recovery_phrase/view.cljs:37]: 💪

**Review by briansztamfater — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]
