### PR TITLE
[fix #2925] Fix invalid log level string passed in JSON to geth

### LINKED ISSUE #2925: Password request message is not shown after application is launched after install
### Description

*Type*: Bug

*Summary*: we have this issue appears from time to time and there are several issues closed for this https://github.com/status-im/status-react/issues/2049, https://github.com/status-im/status-react/issues/1130 for example and this issue is stable to reproduce in `release build ` from Jan 5 2018

https://jenkins.status.im/job/status-react/job/release/job/release%252F0.9.13/1/

#### Expected behavior
I can set up password

#### Actual behavior

image

### Reproduction
- Open Status

### Additional Information

* Status version: release build 0.9.13 from Jan 5 2018
* Operating System: Android

### PR DESCRIPTION
**Pull request by pedropombeiro**
Caused missing password prompt regression

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #2925 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
This PR implements the solution described in https://github.com/status-im/status-react/pull/2939#issuecomment-355958439, so that the JSON validation in geth doesn't fail, and there is no unexpected behavior.

### Review notes (optional):

Added code to adapt the log level in Android to make it easier to spot an error like this by marking it as ERROR instead of DEBUG. The iOS logging method `NSLog` doesn't seem to support log levels, but ideally would do the same.

### Testing notes (optional):

Should pass the test in https://github.com/status-im/status-react/issues/2925.

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

File: modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java [hunk 1]
```diff
@@ -228,7 +228,12 @@ private void doStartNode(final String defaultConfig) {
         Log.d(TAG, "Node config " + config);
 
         String res = Statusgo.StartNode(config);
-        Log.d(TAG, "StartNode result: " + res);
+        if (res.startsWith("{\"error\":\"\"")) {
+            Log.d(TAG, "StartNode result: " + res);
+        }
+        else {
```
Comment (rasom) [inline modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java:234]: Do we really need this if/else?

**Review by rasom — DISMISSED** [review]
see comment above

File: modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java (hunk 1 above)
Comment (pedropombeiro) [reply modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java:234]: @rasom While looking at this bug, more than one person missed this critical entry in the log, so it felt like something was needed to avoid the same thing happening in the future. This differentiates this log entry in case it represents an error, and hopefully helps bringing it to the attention of the developer (e.g. if we apply different colors to different log entry levels).
I agree that the implementation is hacky and can definitely use an improvement. When you question the need for the `if`, is it tied to how it's implemented, or whether it is necessary at all?

Comment (rasom) [reply modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java:234]: oh sorry, i missed d/e difference, was under impression that lines inside if/else branches are identical

**Review by rasom — APPROVED** [review]

**Comment by pedropombeiro** [comment]
@rasom: One thing I should do is have a slightly different message for the
error case, such as `"StartNode failed: "`. I'll add that change in a sec.

**Comment by pedropombeiro** [comment]
Fixed broken iOS build

**Comment by oskarth** [comment]
@PombeirP If you are confident this change works in all environments, and CI passes, please merge with:

`./scripts/merge-external-pr.sh 2946` (requires code signing).

**Comment by pedropombeiro** [comment]
@oskarth I'll need the Ubikey for that, right?

**Comment by oskarth** [comment]
Answered in PM on Slack
