### PR TITLE
fix(wallet)_: Dismiss collectible details screen after a is TX placed

### LINKED ISSUE #20701: [Android] User is navigated to the collectible detail page after collectible sending instead of the activity tab
### Steps:
1. Open an account (this step is required; don't send collectibles from the main wallet page).
2. Open collectible -> tap 'send'
3. Confirm collectible sending

### Actual result:
After the collectible sending confirmation, the collectible detailed page is shown

https://github.com/status-im/status-mobile/assets/52490791/b00f8f9b-1fb7-4706-ba0c-f4c23d291910

### Expected result:
After the collectible sending confirmation, the activity tab is shown

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs (1).zip](https://github.com/user-attachments/files/16146964/Status-debug-logs.1.zip)

### ENV:
Nightly 9 Jul, 2024

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #20701

## Summary

This PR fixes the user is not taken to the activity tab after the TX if the user enters the send flow from collectible details screen (inside the account)

## Review notes

This PR updates the opening of collectible details screen into the modal (correct navigation for the detail screen) and dismisses it on TX confirmation (just as we do for the send flow modal).

### Platforms

- Android
- iOS

##### Prerequisites: A profile/account with collectibles

- Open Status
- Navigate to Wallet > Tap on an Account > Tap Collectible tab
- Tap on any collectible to open the details screen
- Open Send flow from it and complete the transaction
- Verify the collectible details screen is dismissed when the TX is placed and taken to the activity tab

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/events.cljs [hunk 1]
```diff
@@ -41,18 +41,18 @@
...
    {:db (assoc-in db [:wallet :current-viewing-account-address] address)
-    :fx [[:dispatch [:navigate-to-within-stack [:screen/wallet.accounts :shell-stack] address]]]}))
+    :fx [[:dispatch [:navigate-to-within-stack [:screen/wallet.accounts :shell-stack]]]]}))
 
 (rf/reg-event-fx :wallet/navigate-to-new-account
  (fn [{:keys [db]} [address]]
    {:db (assoc-in db [:wallet :current-viewing-account-address] address)
     :fx [[:dispatch [:hide-bottom-sheet]]
-         [:dispatch [:navigate-to :screen/wallet.accounts address]]
+         [:dispatch [:navigate-to :screen/wallet.accounts]]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/events.cljs:55]: Minor cleanup: When the `:screen/wallet.accounts` was first created. it received the address as navigation params and displayed the account details (tokens, collectibles and other data accordingly). But, later we moved to store the address in the `:current-viewing-account-address` key in `app-db`.

**Review by mohsen-ghafouri — APPROVED** [review]
👍

**Review by clauxx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid thank you for PR. No issues from my side. PR is ready to be merged
