### PR TITLE
[Fix] Wallet - Keypair name in the about tab

### LINKED ISSUE #19382: The generated keypair name is not fetched to the about section
### Steps:
1. Create an account with a newly generated keypair (see flow [here](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-596827&mode=design&t=iugkFHlUKh8btaCh-0) how to generate keypair)
2. Open current account
3. Check the About section

### Actual result:
The default name is fetched into the About section
image

### Expected result:
The key pair name should be fetched to the About section.

Discussed with a Design team https://discord.com/channels/624634427930312714/852533718790570015/1221769793326026772

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #19382

### Summary

This PR fixes the display of the correct keypair name (where the account is generated from) in the About tab.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to the Wallet tab
- Navigate to Create Account flow
- Create a new Keypair
- Select that Keypair and generate an account
- Verify the keypair name is shown in the About tab

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/create_account/select_keypair/view.cljs [hunk 1]
```diff
@@ -74,7 +74,6 @@
         selected-keypair                        (rf/sub [:wallet/selected-keypair-uid])
         profile-picture                         (rf/sub [:profile/image])
         [selected-key-uid set-selected-key-uid] (rn/use-state selected-keypair)]
-    (rn/use-mount #(rf/dispatch [:wallet/get-keypairs]))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/create_account/select_keypair/view.cljs]: Removed the event here as the Keypair details are fetched whenever a new account is added or an account is removed. This helps in resolving this issue and also displaying the newly generated keypairs in the wallet settings later (without having to re-login).

Comment (OmarBasem) [reply src/status_im/contexts/wallet/create_account/select_keypair/view.cljs]: @smohamedjavid after you create a new keypair does it still show in the list of keypairs? (without restarting the app)

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/create_account/select_keypair/view.cljs]: Yes, @OmarBasem as we request for keypairs after account creation.

https://github.com/status-im/status-mobile/pull/19505/files#diff-694ffc2f895558df8b19c6c44a82bfdc8e8e7d8a9743243a0b66958fb39740e4R184

**Review by OmarBasem — APPROVED** [review]

**Comment by churik** [comment]
Thanks for your amazing work!
e2e failures are known not related to PR.
Tested basic flows, LGTM!

**Devices:**
- IPhone 14 Pro (IOS 16.5.1)
