### PR TITLE
Fix conditional of selection user's name in confirmation drawer

### LINKED ISSUE #16469: "Unknown" instead of username in Remove profile bottom sheet
**Steps:** 

1. Create multiaccount
2. Open Profile list screen
3. Open Remove profile bottom sheet
4. See if username is fetched

**Actual result:** username is lost. "Unknown" instead of username is displayed. 

photo_2023-07-03 13 45 31

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16469 

### Summary

Fixes an issue with conditional logic when calculating user's name
#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/status_im2/common/confirmation_drawer/view.cljs [hunk 1]
```diff
@@ -33,10 +33,14 @@
...
-                                              (rf/sub [:contacts/contact-name-by-identity id]))
-                                            name)
+            contact-name-by-identity       (when-not group-chat
+                                             (rf/sub [:contacts/contact-name-by-identity id]))
+            display-name                   (cond
+                                             (= contact-name-by-identity
+                                                "Unknown") name
+                                             (= contact-name-by-identity
+                                                nil)       name
+                                             :else         contact-name-by-identity)
```
Comment (Parveshdhull) [inline src/status_im2/common/confirmation_drawer/view.cljs:43]: We probably should prefer passed name over subscription. Should we try something like
```
(if (and name (not (starts-with 0x)) 
    name
    (rf/sub [:contacts/contact-name-by-identity id]))
```

File: src/status_im2/common/confirmation_drawer/view.cljs [hunk 2]
```diff
@@ -33,10 +33,14 @@
...
                     profile-picture name]} context
             id                             (or chat-id public-key)
-            display-name                   (or
-                                            (when-not group-chat
-                                              (rf/sub [:contacts/contact-name-by-identity id]))
-                                            name)
+            contact-name-by-identity       (when-not group-chat
+                                             (rf/sub [:contacts/contact-name-by-identity id]))
+            display-name                   (cond
+                                             (= contact-name-by-identity
```
Comment (J-Son89) [inline src/status_im2/common/confirmation_drawer/view.cljs:39]: is this common logic that is reused on other screens? Perhaps it's better in its own sub ?

Comment (ibrkhalil) [reply src/status_im2/common/confirmation_drawer/view.cljs:39]: I think `group-chat` and `name` vars both come from the context var, I'll see if I can make it more reusable.

Comment (ibrkhalil) [reply src/status_im2/common/confirmation_drawer/view.cljs:39]: After looking a bit closer, I think it's fine to have these other options away from the user's first name (group-chat and name)
Because they're data that are related to the chat and not the user specifically.

**Review by J-Son89 — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil . Thank you for PR. No issues from my side. Ready to be merged
