### PR TITLE
Wallet: Token item fixes

### LINKED ISSUE #18135: Wallet: token item names not displaying

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/18135

This PR fixes an issue where token item names were not displaying for most tokens.

Also adds a temporary label (token first letter) for tokens that do not have an icon yet.

Screenshot_20231211_101917_Status Debug

### CODE REVIEW

File: src/quo/components/utilities/token/view.cljs [hunk 1]
```diff
@@ -33,6 +35,19 @@
...
+   {:style (merge (token-style {:justify-content :center
+                                :align-items     :center
+                                :border-radius   20
+                                :border-width    1
+                                :border-color    :grey}
+                               size))}
+   [quo/text
+    {:size  :paragraph-2
+     :style {:color :grey}} "TBA"]])
+
```
Comment (OmarBasem) [inline src/quo/components/utilities/token/view.cljs]: Temporary label for tokens that we don't have their icon

File: src/quo/foundations/common.cljs [hunk 2]
```diff
@@ -3,8 +3,3 @@
 (def currency-label
   {:eur "€"
    :usd "$"})
-
-(def token-label
-  {:eth "Ethereum"
-   :snt "Status"
-   :dai "Dai"})
```
Comment (OmarBasem) [inline src/quo/foundations/common.cljs:10]: Token label was hardcoded in this map. We should instead read the name from the data we fetch.

File: src/quo/components/utilities/token/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/quo/components/utilities/token/view.cljs]: I believe the fallback is the tokens initials (confirm with design) can we handle that here?
Cc @ulisesmac

File: .clj-kondo/rewrite-clj/rewrite-clj/config.edn [hunk 3]
```diff
@@ -0,0 +1,5 @@
+{:lint-as
+ {rewrite-clj.zip/subedit-> clojure.core/->
+  rewrite-clj.zip/subedit->> clojure.core/->>
+  rewrite-clj.zip/edit-> clojure.core/->
+  rewrite-clj.zip/edit->> clojure.core/->>}}
```
Comment (J-Son89) [inline .clj-kondo/rewrite-clj/rewrite-clj/config.edn]: revert?

File: src/quo/components/list_items/token_value/view.cljs [hunk 4]
```diff
@@ -6,15 +6,15 @@
     [quo.components.markdown.text :as text]
     [quo.components.utilities.token.view :as token]
     [quo.foundations.colors :as colors]
-    [quo.foundations.common :as common]
```
Comment (J-Son89) [inline src/quo/components/list_items/token_value/view.cljs:9]: should we delete the function common/token-label too? or is it still used somewhere?

**Review by J-Son89 — APPROVED** [review]

File: src/quo/components/utilities/token/view.cljs (hunk 1 above)
Comment (OmarBasem) [reply src/quo/components/utilities/token/view.cljs]: @J-Son89 confirmed with the design team, we display the first letter. Updated the component 👍

Comment (J-Son89) [reply src/quo/components/utilities/token/view.cljs]: Thanks! 🙏

File: src/quo/components/list_items/token_value/view.cljs (hunk 4 above)
Comment (OmarBasem) [reply src/quo/components/list_items/token_value/view.cljs:9]: I deleted it :) https://github.com/status-im/status-mobile/pull/18136/files#diff-63a9cce758c7362591b282e7f9db5767fed12cb718ddc00a8a01eb44e3c9e53cL6-L10

**Review by smohamedjavid — APPROVED** [review]

File: src/quo/components/list_items/token_value/view.cljs (hunk 4 above)
Comment (J-Son89) [reply src/quo/components/list_items/token_value/view.cljs:9]: My bad for not noticing! Thanks 😀

File: src/quo/components/utilities/token/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/quo/components/utilities/token/view.cljs]: Yep, they said it's going to be a letter but there are no designs yet @J-Son89

File: src/quo/components/utilities/token/view.cljs [hunk 5]
```diff
@@ -33,6 +36,18 @@
...
 
+(defn temp-empty-symbol
+  [token size]
+  [rn/view
+   {:style (merge (token-style {:justify-content :center
+                                :align-items     :center
+                                :border-radius   20
+                                :border-width    1
+                                :border-color    :grey}
+                               size))}
```
Comment (ulisesmac) [inline src/quo/components/utilities/token/view.cljs]: Merge is just receiving one map, si it's merging nothing, we can remove it

File: src/quo/components/utilities/token/view.cljs [hunk 6]
```diff
@@ -33,6 +36,18 @@
...
+   [quo/text
+    {:style {:color :grey}} (string/capitalize (first (name token)))]])
```
Comment (ulisesmac) [inline src/quo/components/utilities/token/view.cljs]: `(string/capitalize ...)` should be in the following line (50)

**Review by ulisesmac — APPROVED** [review]
Just small comments :+1:

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem thank you for work. No issues from my side. PR is ready to be merged
