### PR TITLE
fix hidden community appears on "Opened" Tab

### LINKED ISSUE #21169: Hidden community appears on "Opened" Tab with unread message counter from 1-1 chats
# Bug Report

## Problem 
When adding a new community on the "Opened" tab, a hidden community (I assume it's a default community "Status Iny" that was later hidden) is displayed. This community pulls the unread message counter from 1-1 chats. Tapping on it shows a popup with an error, but if you long tap, it opens the menu as it would in a regular community.

### Reproduction
1. Create a new User 1.
2. Add User 2 to User 1's contact list.
3. User 2 sends an invite to a community 'Commun'.
4. User 1 joins the community.
5. User 2 send messages in 1-1 chat

#### Expected behavior
The "Opened" tab shows 2 communities: the default 'Status' and the new 'Commun'.

#### Actual behavior
The "Opened" tab shows 3 communities: the default 'Status', the new 'Commun', and one additional hidden community. This hidden community pulls the unread message counter from 1-1 chats. 

https://github.com/user-attachments/assets/6f13c250-051f-4b6b-acda-68c4fc516af3

### Additional Information

- Status version: nightly 03.09.2024 or app version: 2.29.0 (20240903020837)
- Operating System: Android, iOS
- Logs: [Status-debug-logs (8).zip](https://github.com/user-attachments/files/16850273/Status-debug-logs.8.zip)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21169

### Summary

When the community is fetched, we were calling the [handle-community](https://github.com/status-im/status-mobile/blob/337ec963b7fc8934da09f600b249567f3f177c3c/src/status_im/contexts/communities/events.cljs#L21) event with a Clojure object instead of a JavaScript object. The [<-js-map](https://github.com/status-im/status-mobile/blob/337ec963b7fc8934da09f600b249567f3f177c3c/src/utils/transforms.cljs#L21) function returns `nil` because it expects a JavaScript object, resulting in a community with a `nil` id.

**Note:** To address this issue for the future, I considered changing [<-js-map](https://github.com/status-im/status-mobile/blob/337ec963b7fc8934da09f600b249567f3f177c3c/src/utils/transforms.cljs#L21) to return the Clojure object itself instead of `nil`. However, in this particular case, this change would not have been beneficial because the [rename-communities-keys](https://github.com/status-im/status-mobile/blob/337ec963b7fc8934da09f600b249567f3f177c3c/src/legacy/status_im/data_store/communities.cljs#L58) function also expects JavaScript keys. Therefore, I did not modify the function, considering potential consequences. Still, please let me know if you think we should return the Clojure object instead of `nil`.

status: ready

### CODE REVIEW

**Comment by ilmotta** [comment]
@Parveshdhull, this bug is likely related to the issue I created some time ago https://github.com/status-im/status-mobile/issues/20762, where communities are being spectated even if the user never opened them. Once a community is spectated, it appears in the opened tab. I followed the steps to reproduce just now and the bug still exists. Does this PR solve that problem too? Maybe it's a separate fix, but I wanted to share since the following line is in the same event this PR is touching.

The correct is to only spectate if the community was intentionally opened by the user, but this is not what the code in `develop` does.

https://github.com/status-im/status-mobile/blob/fa4ea0640d408397009f505b7b8eba7e4bc3ee66/src/status_im/contexts/communities/events.cljs#L230

**Comment by Parveshdhull** [comment]
Hi @ilmotta,

Thank you very much for reviewing the PR.

> This bug is likely related to the issue I reported some time ago: [https://github.com/status-im/status-mobile/issues/20762](https://github.com/status-im/status-mobile/issues/20762), where communities are being spectated even if the user never opened them.

> Issue: (I assume it's a default community "Status Inu" that was later hidden) is displayed.

Actually, this is not the case. We are not spectating the wrong community here (such as Status Inu, etc.). This bug occurred because we were adding a community with a nil key in the database. Please checkout PR description for more details.

File: src/status_im/contexts/communities/events_test.cljs [hunk 1]
```diff
@@ -62,7 +63,7 @@
                      [:dispatch [:chat.ui/spectate-community community-id]]
                      [:dispatch
                       [:chat.ui/cache-link-preview-data "community-link+community-id"
-                       {:id community-id}]]]}
+                       (data-store.communities/<-rpc {"id" community-id})]]]}
```
Comment (ilmotta) [inline src/status_im/contexts/communities/events_test.cljs]: If the value passed to `<-rpc` is not a JS object the keys are ignored.

```clojure
;; ID is not in the output
(<-rpc {"id" "1"})
;; => {:admin-settings nil,
;;     :token-permissions nil,
;;     :categories {},
;;     :role-permissions? nil,
;;     :membership-permissions? nil,
;;     :token-images {}}

;; Correct
(<-rpc #js{"id" "1"})
;; => {:id "1",
;;     :admin-settings nil,
;;     :token-permissions nil,
;;     :categories {},
;;     :role-permissions? nil,
;;     :membership-permissions? nil,
;;     :token-images {}}
```

**Review by ilmotta — COMMENTED** [review]
> Note: To address this issue for the future, I considered changing [<-js-map](https://github.com/status-im/status-mobile/blob/337ec963b7fc8934da09f600b249567f3f177c3c/src/utils/transforms.cljs#L21) to return the Clojure object itself instead of nil. 

@Parveshdhull, I think returning the Clojure map itself as you suggest would be better because the function `transforms/<-js-map` only shallowly transforms the JS object, which means if the function receives a Clojure object, there is nothing to do. If the function was recursive it would be a different story.

> Still, please let me know if you think we should return the Clojure object instead of nil.

It would be nice to go with your proposal in this PR, not just in the future. This detail could bite us in the future.

**Comment by Parveshdhull** [comment]
Hi @ilmotta,

> It would be nice to go with your proposal in this PR, not just in the future.

I've updated the [<-js-map](https://github.com/status-im/status-mobile/blob/337ec963b7fc8934da09f600b249567f3f177c3c/src/utils/transforms.cljs#L21) function to return m itself when m is not an instance of js/Object.

However, I want to highlight that for the handle-community use case, we still need to use `:js-response true` due to the [rename-communities-keys](https://github.com/status-im/status-mobile/blob/337ec963b7fc8934da09f600b249567f3f177c3c/src/legacy/status_im/data_store/communities.cljs#L58) function.

I attempted to create a [solution](https://github.com/status-im/status-mobile/commit/9d1154d39e98c030eb19a8cb76de388f596751af) where key renaming also works even if the object is not a js instance. Unfortunately, this [approach](https://github.com/status-im/status-mobile/commit/9d1154d39e98c030eb19a8cb76de388f596751af) failed for nested keys like :chats, :members, etc., within the community object.

File: src/status_im/contexts/communities/events.cljs [hunk 2]
```diff
@@ -25,7 +25,7 @@
                   token-permissions-check id last-opened-at]
            :as   community}       (data-store.communities/<-rpc community-js)
           previous-last-opened-at (get-in db [:communities id :last-opened-at])]
-      (when (>= clock (get-in db [:communities id :clock]))
+      (when (and (>= clock (get-in db [:communities id :clock])) id)
```
Comment (flexsurfer) [inline src/status_im/contexts/communities/events.cljs]: id should be first

Comment (Parveshdhull) [reply src/status_im/contexts/communities/events.cljs]: Thank you @flexsurfer for reviewing PR. Moved id to beginning.

( I had this change in mind 😅, and made it, but apparently in wrong branch https://github.com/status-im/status-mobile/commit/9d1154d39e98c030eb19a8cb76de388f596751af#diff-63b184880cbf5c0450f717326801b4e79c54135e30c0bdffc1528b4c8fd89b65 )

**Review by flexsurfer — APPROVED** [review]

File: src/utils/transforms.cljs [hunk 3]
```diff
@@ -33,15 +33,16 @@
...
      (persistent!
       (reduce (fn [r k]
                 (let [v       (oops/oget+ m k)
                       new-key (if key-fn (key-fn k v) k)
                       new-val (if val-fn (val-fn k v) v)]
                   (assoc! r new-key new-val)))
               (transient {})
-              (js-keys m))))))
+              (js-keys m)))
+     m)))
```
Comment (ilmotta) [inline src/utils/transforms.cljs:46]: If the function is called with anything besides a Clojure map or a JS Object I think it should return nil, better would be to fail an instrumentation check with malli. Returning the input itself would probably be masking a more serious bug in the code, because why would a developer pass a different data type than a map or JS object to this function?

We could be more strict about the data type. Since this function is multi-arity and our instrumentation utilities don't work with them, we can do something simple for now. Use `(assert (or (identical? (type m) js/Object) (map? m)))` because shadow-cljs will elide assertions in release builds.

> :elide-asserts (Boolean) default to false in development and true in release builds
>
> -- https://shadow-cljs.github.io/docs/UsersGuide.html#compiler-options

**Review by ilmotta — APPROVED** [review]

File: src/utils/transforms.cljs (hunk 3 above)
Comment (Parveshdhull) [reply src/utils/transforms.cljs:46]: Hi @ilmotta, Thank you for suggestion. Added [assert](https://github.com/status-im/status-mobile/pull/21238/commits/f6e5ec0ab7b76089a2ea8c56fd3524f642b315f1), please let me know if it looks ok?

Comment (ilmotta) [reply src/utils/transforms.cljs:46]: Looks good 👍🏼

Comment (ilmotta) [reply src/utils/transforms.cljs:46]: Just a small detail @Parveshdhull, maybe let's add a check for nil, otherwise the assertion will fail in development with nil values `(assert (or (nil? m) (identical? (type m) js/Object) (map? m)))`

Comment (Parveshdhull) [reply src/utils/transforms.cljs:46]: Updated. Thank you

**Comment by pavloburykh** [comment]
@Parveshdhull thanx for the PR. Just to clarify: should this PR fix this issue as well https://github.com/status-im/status-mobile/issues/20762 or it is out of scope? 

Currently communities from Discovery screen still appear in Open tab despite user never opened them

**Steps:** 

1. Create a new user
2. Open Discovery screen and wait until curated communities (i.g Status community) are loaded
3. Do not open them
4. Go to Open tab and see if it is empty

Actual result: communities from Discovery screen appear in Open tab


https://github.com/user-attachments/assets/e21fd572-60ac-4070-8f54-69924a0dadde

**Comment by Parveshdhull** [comment]
> @Parveshdhull thanx for the PR. Just to clarify: should this PR fix this issue as well https://github.com/status-im/status-mobile/issues/20762 or it is out of scope?

Thank you @pavloburykh for taking the PR in testing. https://github.com/status-im/status-mobile/issues/20762 is out of scope and require different solution.

**Comment by pavloburykh** [comment]
> Thank you @pavloburykh for taking the PR in testing. #20762 is out of scope and require different solution.

Thank you @Parveshdhull! Could you please take a look at the issue below:

### ISSUE 1 Cannot enter channels in open communities (with manual approval required) prior to joining the community

**Steps:** 

1. Open non token gated community with manual approval required. You can use this [one](https://status.app/c/GzgAAGRy3S05LfkZChxduhOUCs3iSRLWOVIS0zzLR9Ph1fSW-zy9uPKimrN9_fFf138XIIBhlhZRPwI=#zQ3shpBwo22Au6SvVQX39L9ZM2p3Rmy17xEdTMH4hdrcLz7x3) for testing
2. Do not join the community
3. Try to enter any of community channels
4. Observe the result

**Expected result:** can enter channels in spectacular mode (can view history but cannot post messages prior to joining)

**Actual result:** cannot enter channels. In case channel has unread badge it disappears after tapping on the channel (see the video below).

[Status-debug-logs - 2024-09-18T111530.565.zip](https://github.com/user-attachments/files/17040899/Status-debug-logs.-.2024-09-18T111530.565.zip)

https://github.com/user-attachments/assets/0ff9e1de-026b-4900-bf0d-aeed367838d6

**Comment by Parveshdhull** [comment]
Thank you @pavloburykh for finding this issue. Should be fixed now.

**Comment by pavloburykh** [comment]
> test_activity_center_contact_request_decline

@Parveshdhull thank you for the fix. PR is ready for merge.

**Comment by Parveshdhull** [comment]
Thank you @pavloburykh for testing the PR. Pushed [commit](https://github.com/status-im/status-mobile/pull/21238/commits/00180ada838b4bff96286c715587f5303bdc5e65) only updates unit tests file and should not affect testing. Still, I will test the fix before merging.
