### PR TITLE
fix image long press issue and cropping

### LINKED ISSUE #16048: Images sent from desktop are cropped
# Bug Report

## Problem 
Any images, sent from desktop are cropped and resized.

#### Expected behavior

can see the whole picture

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/81245728-a157-4ef2-a38c-d57c20e047a6

### Reproduction

1) Sent any imge from desktop and try to open it on mobile device

### Additional Information

- Status version: RC 10, 1.23
- Desktop version: 0.12.0 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #16547: "Object is not a function" error in longtap on image send from Desktop client
**Preconditions:** Desktop user and Mobile user are in the same chat/community. Before reproduction make sure you are using latest available Desktop [master](https://ci.infra.status.im/job/status-desktop/job/master/) build 

**Steps:** 

1. Desktop user sends image in chat/community channel
2. Mobile user longtaps on image
3. Observe error on mobile client

**Actual result:** "Object is not a function" error appears. Besides that, opened image is cropped. 

[Status-debug-logs (39).zip](https://github.com/status-im/status-mobile/files/12003120/Status-debug-logs.39.zip)
photo_2023-07-10 17 33 53
photo_2023-07-10 17 33 58

https://github.com/status-im/status-mobile/assets/97245802/612729a6-a80f-4e8f-adc3-6bc519b10106

### Additional Information

- Desktop version: master (08 Jul 2023)
- Status version: nightly (10 Jul 2023)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/16547
fixes: https://github.com/status-im/status-mobile/issues/16048

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]
lgtm

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 1]
```diff
@@ -154,7 +154,7 @@
                [audio/audio-message message-data context]
 
                constants/content-type-image
-               [image/image-message 0 message-data context on-long-press]
+               [image/image-message 0 message-data context]
 
                constants/content-type-album
                [album/album-message message-data context on-long-press]
```
Comment (smohamedjavid) [inline src/status_im2/contexts/chat/messages/content/view.cljs:160]: Do we need to apply this fix for album type?

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im2/contexts/chat/lightbox/zoomable_image/style.cljs [hunk 2]
```diff
@@ -22,14 +22,13 @@
...
    index]
   (reanimated/apply-animations-to-style
    {:transform     [{:rotate rotate}
                     {:scale rotate-scale}]
     :opacity       (nth images-opacity index)
     :border-radius border-value}
-   {:width  image-width
-    :height image-height}))
+   {:width  screen-width
+    :height screen-height}))
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/lightbox/zoomable_image/style.cljs]: This can't be like that. It has to use `image-width` and `image-height`. Notice how the margins and border radius now disappear

File: src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs [hunk 3]
```diff
@@ -225,9 +225,10 @@
                                @set-full-height?
                                (= curr-orientation orientation/portrait))}
       [reanimated/fast-image
-       {:source    {:uri (http/replace-port (:image content) (rf/sub [:mediaserver/port]))}
-        :native-ID (when focused? :shared-element)
-        :style     (style/image dimensions animations render-data index)}]]]))
+       {:source      {:uri (http/replace-port (:image content) (rf/sub [:mediaserver/port]))}
+        :native-ID   (when focused? :shared-element)
+        :resize-mode :contain
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs]: Same comment as above

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/content/view.cljs:160]: Hi @smohamedjavid, Thank you very much for reviewing PR.

>Do we need to apply this fix for album type too?

We probably need to refactored these files for consistency, but album have both `context` and `long-press` as input
image

**Comment by OmarBasem** [comment]
@Parveshdhull as a temporary fix until desktop adds `image-width` and `image-height` we can make a check to see if the image includes `image-width` and `image-height`, if it does not, then your proposed fix to use the whole screen dimensions plus adding `contain` would work for that

**Comment by Parveshdhull** [comment]
Hi @OmarBasem, Thank you very much for reviewing the PR. Added the check to make sure zoomable image uses original implementation when image dimensions are not nil.

**Review by OmarBasem — APPROVED** [review]
Thanks for the fix 👍

**Comment by pavloburykh** [comment]
@Parveshdhull thanx for the PR! 

Please take a look at the following issue

### ISSUE 1 Longtap not working when tapping directly on image in a message with 1 image

**Steps:** 

1. Send a message with 1 image
2. Longtap on send image
3. See if context menu appears

**Actual result:** context menu does not appear. Longtap works only on tapping on area beyond the image

On video below I demonstrate a comparison of behaviour on PR and nightly builds


https://github.com/status-im/status-mobile/assets/97245802/c189ee54-cf79-4788-98df-b854e85e76c0

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, Thank you very much for testing the PR and finding the issue. Should be fixed now.

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the fix! PR is ready for merge. Failed e2e are not PR related.
