### PR TITLE
new chat fixes and improvements, sheet modal screen improvements

### LINKED ISSUE #15546: improve modal screen (sheet UI)
we have an option to open modal screen with sheet UI

```clojure
{:name      :community-requests-to-join
 :options   {:sheet? true
             :insets {:bottom? true}}
 :component join-menu/request-to-join}

rf/dispatch [:open-modal :community-requests-to-join]
```

implementation is here: `status-im2.common.bottom-sheet-screen.view` https://github.com/status-im/status-mobile/blob/6417d90e1c15e9d51c0cd851d8a9a53d189588a2/src/status_im2/common/bottom_sheet_screen/view.cljs#L49

it needs some improvements
- [x] 1) currently modal screen has its own transition animation, so we have two animations, we need to disable navigation animation
- [x] 2) it uses gesture library but some screens use react native section list which is not supported buy gesture library, so this should fixed somehow, currently gesture was moved to handle view only
- [x] 3) status bar should be behind the backdrop, currently its light
- [ ] 4) there are some screen with scrolling states
 
image

5) would be great to have a video example from the design team on how the transition should work cc @pedro-et @xAlisher 

- [ ] 6) this state looks wrong, when we pull the screen down there is no backdrop

image

cc @OmarBasem

### LINKED ISSUE #15982: "Cannot set property 'G_1' of null" error is shown after tapping 'new chat' button
### Steps:
1. Tap 'new chat' button

### Actual behavior
"Cannot set property 'G_1' of null" error is shown after tapping 'new chat' button

https://github.com/status-im/status-mobile/assets/52490791/b215d85f-ab7e-4d11-880e-622e12f6e6b4

### Expected behavior
Chats can be created

### Env:
IOS, Android

### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/11532966/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/11532967/geth.log)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes https://github.com/status-im/status-mobile/issues/15982
partially fixes https://github.com/status-im/status-mobile/issues/15546
new chat modal adjusted according latest designs
fixes drawer item separator in dark mode

### CODE REVIEW

File: src/status_im2/contexts/chat/new_chat/view.cljs [hunk 1]
```diff
@@ -0,0 +1,109 @@
+(ns status-im2.contexts.chat.new-chat.view
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/new_chat/view.cljs:1]: this namespace was moved, and not many changes in it

**Comment by OmarBasem** [comment]
Honestly, I do not think the changes to the bottom sheet screen animations is an improvement. Now the background opacity does not animate while pulling down. The sudden stop of the screen window after releasing touch while pulling down, then animating its opacity only looks weird. In my opinion, the way it currently is looks better.

We need to have a proper fix for it as mentioned here https://github.com/status-im/status-mobile/issues/15546#issuecomment-1538030754

> So probably the backdrop would have to be displayed as an overlay in another way.

**Comment by flexsurfer** [comment]
> Now the background opacity does not animate while pulling down

It's intentional, before it was weird when you pull it and there is no background at all, but we still need the demo video, currently its just our assumptions ;)

**Comment by OmarBasem** [comment]
> there is no background at all

It animates. It reaches zero opacity after a certain threshold. We can increase that threshold.

We can ask the design team also for an animation video.

**Comment by flexsurfer** [comment]
> We need to have a proper fix for it

yes currently there is no easy way to fix, because ideally, we should implement it as a bottom sheet, but the problem is there might be another bottom sheet on top, so it can't be an overlay, it steel should be a modal screen, but there is no way to animate backdrop outside the window container, so yeah, but still current implementation looks better , because before backdrop animation looked laggy

**Comment by flexsurfer** [comment]
hm actually i have an idea, i'll try something

**Comment by flexsurfer** [comment]
ok thanks @OmarBasem found a better solution, now it works and looks much better, you could try when build is ready

**Review by Parveshdhull — APPROVED** [review]

**Comment by qoqobolo** [comment]
@flexsurfer thanks for the quick fix for chats!
Look at the issue with the navigation buttons on Android please, can't reproduce it in nightly. 

### ISSUE 1: The bottom navigation buttons on Android become light after opening the activity center

**Steps:**
1. Enable `Three-key navigation` on your Android device
2. Have your device in the light mode
3. Open the community/chat screen
4. Open AC
5. Close AC

**Expected result:** the bottom navigation panel stays dark 

https://github.com/status-im/status-mobile/assets/67952253/99bca7dd-a5d0-43f6-912e-2933587e5a9b

File: src/status_im2/common/bottom_sheet_screen/style.cljs [hunk 2]
```diff
@@ -22,7 +22,8 @@
     :border-top-left-radius  20
     :border-top-right-radius 20
     :flex                    1
-    :overflow                :hidden}))
+    :overflow                :hidden
+    :padding-top             20}))
```
Comment (OmarBasem) [inline src/status_im2/common/bottom_sheet_screen/style.cljs:26]: Please remove this padding. It shouldn't be here. It doesn't look right on the photo-selector screen

**Review by OmarBasem — APPROVED** [review]
Looks better, well done 👍

File: src/status_im2/common/bottom_sheet_screen/style.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im2/common/bottom_sheet_screen/style.cljs:26]: it should be here, because handle is absolute but we should reserve the place for it, so i'll fix photo-selector screen

**Comment by qoqobolo** [comment]
Issue 1 will be logged separately.
Thank you @flexsurfer, PR can be merged.

File: src/status_im2/common/bottom_sheet_screen/style.cljs (hunk 2 above)
Comment (OmarBasem) [reply src/status_im2/common/bottom_sheet_screen/style.cljs:26]: Hey @flexsurfer, it is not fixed. Check the scrolled state: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372393&t=2auDEJpU1f8tQVGS-0
