### PR TITLE
fix: remove non operable accounts in the selection of sharing addresses with the community

### LINKED ISSUE #20624: Missing wallet accounts are not hidden from "Addresses for permissions" screen
Currently missing accounts are not hidden from "Addresses for permissions" screen. It means that user can select such accounts during joining the community which causes join request to fail. сс @smohamedjavid 

**Steps:** 

1. Login the User who has missing key pair
2. Open link of any community which is not joined yet by the user
3. Proceed joining community flow. 
4. See if there is possibility to select missing account for sharing during join

**Expected result:** we should hide missing accounts from "Addresses for permissions" list so user is unable to select such account. Solution is approved by Alisher [here](https://discord.com/channels/624634427930312714/928625369542713396/1257675582079242280)

**Actual result:** missing accounts are not hidden from "Addresses for permissions" screen. User can select such accounts during joining the community which results in join request to fail. 

[Status-debug-logs - 2024-07-02T144114.267.zip](https://github.com/user-attachments/files/16068513/Status-debug-logs.-.2024-07-02T144114.267.zip)

https://github.com/status-im/status-mobile/assets/97245802/963c5355-0fec-4de7-900a-9e6f39effa19

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #20624

### Summary

This PR removes the non-operable accounts in the `Addresses for permission` and `Airdrop address` selections while joining a community.

https://github.com/status-im/status-mobile/assets/19339952/ed9ed655-bb38-4008-a738-f82b38367660

### Testing notes

A quick check across the app to verify the non-operable accounts are not shown is appreciated.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Login with a profile with a missing key pair
- Navigate to a community that the user does not join
- Tap on request to join
- Verify the non-operable accounts are not shown to the user for selection in `Addresses for permission` and `Airdrop address`

status: ready

### CODE REVIEW

File: src/status_im/subs/wallet/wallet_test.cljs [hunk 1]
```diff
@@ -367,52 +376,55 @@
...
-          :position                  2
-          :clock                     1698945829328
-          :created-at                1698928839000
-          :operable                  :fully
-          :mixedcase-address         "0x7bcDfc75c431"
-          :public-key                "0x"
-          :removed                   false
-          :tokens                    tokens-0x3})
-        (rf/sub [sub-name])))))
+     (=
```
Comment (ilmotta) [inline src/status_im/subs/wallet/wallet_test.cljs]: Maybe back then we didn't have the `match?` clause available. Since you touched this part, could you change from `=` to `match?` please.

File: src/status_im/contexts/communities/utils.cljs [hunk 2]
```diff
@@ -17,4 +17,5 @@
   (->> (get-in db [:wallet :accounts])
        (vals)
        (remove :watch-only?)
+       (filter :operable?)
```
Comment (ilmotta) [inline src/status_im/contexts/communities/utils.cljs:20]: In trying to stay more consistent with the name you chose for the subscription `:wallet/operable-accounts-without-watched-accounts`, we could rename this function to `sorted-operable-and-without-watched-accounts` or something like that.

I'm wondering, doesn't _operable_ already captures the essence of an account where transactions can be made and which are not watched? I imagine a watch-only account can't be used for transactions. In that case, the name of the function could be just `sorted-operable-accounts`?

If you judge `operable` already ignores watch-only accounts, then we could shorten the subscription names too.

**Review by ilmotta — APPROVED** [review]
Excellent work, thank you @smohamedjavid

File: src/status_im/subs/wallet/wallet_test.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/subs/wallet/wallet_test.cljs]: For sure 👍 
Updated here: https://github.com/status-im/status-mobile/pull/20636/commits/010ced0d1f085b49595b5db7826fb0efa7592bc3

File: src/status_im/contexts/communities/utils.cljs (hunk 2 above)
Comment (smohamedjavid) [reply src/status_im/contexts/communities/utils.cljs:20]: Renamed here https://github.com/status-im/status-mobile/pull/20636/commits/fba717d0c90b37d623f4cdf94dc6c1f50135d227 👍  

> I'm wondering, doesn't operable already captures the essence of an account where transactions can be made and which are not watched? I imagine a watch-only account can't be used for transactions. In that case, the name of the function could be just sorted-operable-accounts?

The problem is the **_operable_** key alone is unreliable as we get the same key for watch-only accounts. It will be fully operable for a watch-only account (like the generated accounts). Additionally, we need to depend on the account's **_type_**.

**Review by ajayesivan — APPROVED** [review]
LGTM!

**Review by ulisesmac — APPROVED** [review]
Looks good :+1:

**Comment by pavloburykh** [comment]
@smohamedjavid thank you for the PR! Sorry for delay with testing. It is caused by Waku issues. Our e2e tests are blocked, manual testing is blocked partially as well. Once Waku resolves the issues I will proceed with testing.

**Comment by pavloburykh** [comment]
@smohamedjavid thanks for the PR. Tested and ready for merge.
