### PR TITLE
[16352] [Bugfix] New message indicator not showing on bottom navigation for unmuted chats and another bug

### LINKED ISSUE #16352: Muted chats/channels followup issues
followup of https://github.com/status-im/status-mobile/pull/15128 cc @ibrkhalil 

Issues originally reported here https://github.com/status-im/status-mobile/pull/15128#issuecomment-1601064999

### ISSUE 1 User receives PNs from muted community channel [IOS]

Reproducing on iPhone X, IOS 14.1

**Preconditions:** User A - IOS with enable PNs; User B - any other device. Users A and User B are members of the same community. 

**Steps:**

1. User A mutes community channel. 
2. User A closes the app
3. User B sends mention/rely to User A in muted commubity channel
4. See if User A receives PN

**Actual result:** User A receives PN from muted commubity channel

**Expected result:** User A should not receive PN from muted community channel

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16352 

### Summary

Fixes the latest bug on the muting issues

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by J-Son89** [comment]
Looks good @ibrkhalil, perhaps you could provide a more detailed description of the problem/ the solution you implemented or add some comments to the code to explain why you removed certain code/ why some changes were made. They're not initially so obvious of why (to me anyway :) )

File: src/status_im2/contexts/shell/jump_to/components/bottom_tabs/view.cljs [hunk 1]
```diff
@@ -39,29 +39,24 @@
...
     [reanimated/view
      {:style (style/bottom-tabs-container pass-through? (:bottom-tabs-height shared-values))}
      (when pass-through?
        [blur/view (blur-overlay-params style/bottom-tabs-blur-overlay)])
      [rn/view {:style (style/bottom-tabs)}
-      [gesture/gesture-detector {:gesture communities-double-tab-gesture}
+      [gesture/gesture-detector {:gesture (select-tab-gesture :joined)}
        [bottom-tab :i/communities :communities-stack shared-values notifications-data]]
-      [gesture/gesture-detector {:gesture messages-double-tap-gesture}
+      [gesture/gesture-detector {:gesture (select-tab-gesture :tab/recent)}
```
Comment (ibrkhalil) [inline src/status_im2/contexts/shell/jump_to/components/bottom_tabs/view.cljs]: This is just a refactor for duplicated code.

File: src/status_im2/subs/shell.cljs [hunk 2]
```diff
@@ -190,19 +190,19 @@
...
+              (-> acc
+                  (update-in [:community-stack :unviewed-messages-count] + unviewed-messages-count)
+                  (update-in [:community-stack :unviewed-mentions-count] + unviewed-mentions-count))
+
+              (and (not muted)
+                   (#{constants/private-group-chat-type constants/one-to-one-chat-type} chat-type))
+              (-> acc
+                  (update-in [:chats-stack :unviewed-messages-count] + unviewed-messages-count)
+                  (update-in [:chats-stack :unviewed-mentions-count] + unviewed-mentions-count))
+              :else
```
Comment (ibrkhalil) [inline src/status_im2/subs/shell.cljs:205]: The `cond` is better than `case`, Because if `case` failed it'll return `nil` because of the `(when)` function call.
But the new changes on the other hand will always return the accumulator even if the '(when)' call was falsey.

The issue here was that the notification indicator was failing if it found one muted chat, It returned `nil` as the value and that meant no notification dot at all.

File: status-go-version.json [hunk 3]
```diff
@@ -3,7 +3,7 @@
     "_comment": "Instead use: scripts/update-status-go.sh <rev>",
     "owner": "status-im",
     "repo": "status-go",
-    "version": "v0.159.6",
-    "commit-sha1": "f23cb4065bce9cff3cb8174a10bf9d8d49a4789f",
-    "src-sha256": "1yv24cqj2gnf2rgws39vc0j54l0dfxa6vc74iqcxgm50gd73gf6s"
+    "version": "status-mobile-16352",
+    "commit-sha1": "160094f641618de166de80c6ba22b19238e41d8c",
+    "src-sha256": "0c8hcqrr5y1kkva1xibz7dhd8crwbsypq6lc3n9mzl8dcvm98dxb"
```
Comment (ibrkhalil) [inline status-go-version.json]: [This](https://github.com/status-im/status-go/pull/3673/files#diff-12e1567f20b885c074b2a1213664d43a77fbc87c34b5dc42cdb6d4526a86460dR5839-R5847) function on `status-go` counted the number of chats we should check for notification for, Without the `return true` statement I added as a guard clause, the code added the muted chat list to the public chat list (Group chat list and Public chat list), Leading to push notifications to be sent even if the chat is muted.

**Comment by ibrkhalil** [comment]
> Looks good @ibrkhalil, perhaps you could provide a more detailed description of the problem/ the solution you implemented or add some comments to the code to explain why you removed certain code/ why some changes were made. They're not initially so obvious of why (to me anyway :) )

Thanks Jamie, I added explanation of what this PR does

**Review by J-Son89 — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil Please take a look at the following issues

### ISSUE 1 Double tap in Messages bottom tap causes crash "No matching close: tab/recent" 

**Steps:** 

1. Doubletap on messages bottom tab
2. Observe crash

**Actual result:**  "No matching close: tab/recent"  crash

photo_2023-06-27 14 52 23

https://github.com/status-im/status-mobile/assets/97245802/f61eef9b-d395-441c-82c5-d19d6813ce09

**Review by vkjr — APPROVED** [review]

**Comment by ibrkhalil** [comment]
> @ibrkhalil Please take a look at the following issues
> 
> ### ISSUE 1 Double tap in Messages bottom tap causes crash "No matching close: tab/recent"
> **Steps:**
> 
> 1. Doubletap on messages bottom tab
> 2. Observe crash
> 
> **Actual result:** "No matching close: tab/recent" crash
> 
> photo_2023-06-27 14 52 23
> 
>  telegram-cloud-document-2-5247155927705990768.mp4

Fixed

**Comment by pavloburykh** [comment]
@ibrkhalil another issue

### ISSUE 2 Unread indicator/counter from unmuted channel does not appear for community if one of community channels is muted

Preconditions: community has at least 2 channels

**Steps:** 

1. User A mutes chan 1 
2. User B mentions User A in chan 2 of the same community
3. See if unread counter appears in front of community for User A

**Actual result:** unread counter is not shown

photo_2023-06-27 15 18 17

https://github.com/status-im/status-mobile/assets/97245802/f1c27216-938f-4ea5-8856-4f14e362daf4

**Comment by ibrkhalil** [comment]
> @ibrkhalil another issue
> 
> ### ISSUE 2 Unread indicator/counter from unmuted channel does not appear for community if one of community channels is muted
> Preconditions: community has at least 2 channels
> 
> **Steps:**
> 
> 1. User A mutes chan 1
> 2. User B mentions User A in chan 2 of the same community
> 3. See if unread counter appears in front of community for User A
> 
> **Actual result:** unread counter is not shown
> 
> photo_2023-06-27 15 18 17
> 
>  telegram-cloud-document-2-5249055527316500840.mp4

Fixed

**Comment by pavloburykh** [comment]
@ibrkhalil thanx, both issues are fixed. PR will be ready for merge once e2e run is finished. I will let you know.

**Comment by pavloburykh** [comment]
@ibrkhalil ready for merge
