### PR TITLE
[#17896] Raw balances using big number

### LINKED ISSUE #17896: Error while storing wallet `raw-balances`
# Bug Report

## Problem 

~The `utils.number/parse-int` function is returning `0` or the default value given  when we attempt to parse very long numbers, such as wallet `raw-balance` values, e.g. 150 000 SNTs would be represented as `150000000000000000000000`, and:~

```clojure
(parse-int "150000000000000000000000")
;; => 0
```
~The reason is we are checking if the number is an integer using `clojure.core/integer?`, which says no.~

### Update:

While requesting and storing the `:raw-balance` for the wallet in app-db, `utils.number/parse-int` has been used, that function returns a `0` when the number is too large (e.g. 150 000 SNT, would be `"150000000000000000000000"`).

For wallet balances, we should always use big number functions (please check the ns `utils.money`).

This issue consists of updating the raw-balance stored to properly use big numbers.

#### Expected behavior

Properly store the raw balances, test with 150,000 received and other smaller and bigger amounts.

#### Actual behavior

If we receive a big raw balance, the total balance in the account cards in the wallet page report $0.00

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #17896

### Summary

The previous implementation was using js/parseInt to process the raw-balances, this PR stores them as big-number instances in re-frame.

This had some problems, if we had 100 or more units of a token, the calculations resulted in a `0`, now using bignumbers that issue has been fixed.

### Changes
- Makes `utils.money/add` able to receive `nil` values
- Store raw-balances as big number instances
- Update the balance calculation related functions to use big numbers, also now they are using existing `utils.money` functions.

### Testing notes
 
 The app should work as expected. Previously, if we had 100 or more token units, the result listed in the account cards in the wallet home page was `$0.00`. Now it shows the proper value.

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

Wallet home page in the account cards.

### Steps to test

- Open Status
- Navigate to our new wallet implementation
- Wait for it to load, the account cards should properly display the account balance if we have more than 100 token units in total for an account.

status: ready

### CODE REVIEW

File: src/status_im2/contexts/wallet/common/utils.cljs [hunk 1]
```diff
@@ -23,23 +24,23 @@
   (let [path (get-derivation-path number-of-accounts)]
     (format-derivation-path path)))
 
-(defn- calculate-raw-balance
-  [raw-balance decimals]
-  (if-let [n (utils.number/parse-int raw-balance nil)]
-    (/ n (Math/pow 10 (utils.number/parse-int decimals)))
-    0))
```
Comment (ulisesmac) [inline src/status_im2/contexts/wallet/common/utils.cljs]: `utils.money/token->unit` is able to do the same and works with big numbers, so now it is being used

File: src/status_im2/subs/wallet/wallet_test.cljs [hunk 2]
```diff
@@ -1,8 +1,9 @@
 (ns status-im2.subs.wallet.wallet-test
   (:require [cljs.test :refer [is testing use-fixtures]]
             [re-frame.db :as rf-db]
-            status-im2.subs.root
+            [status-im2.subs.root]
```
Comment (J-Son89) [inline src/status_im2/subs/wallet/wallet_test.cljs:4]: What's the difference? 🤔

File: src/status_im2/contexts/wallet/common/utils.cljs [hunk 3]
```diff
@@ -23,23 +24,23 @@
...
+                                      (total-raw-balance-in-all-chains)
+                                      (money/token->unit decimals))]
+    (money/crypto->fiat total-units-in-all-chains usd-price)))
 
-(defn calculate-balance
-  [tokens-in-account]
-  (->> tokens-in-account
-       (map (fn [token]
-              (* (total-token-value-in-all-chains token)
-                 (-> token :market-values-per-currency :usd :price))))
```
Comment (ulisesmac) [inline src/status_im2/contexts/wallet/common/utils.cljs:52]: `utils.money/crypto->fiat` does the same but supports bignumbers, so now it's being used

File: src/status_im2/contexts/wallet/common/utils.cljs [hunk 4]
```diff
@@ -1,6 +1,7 @@
 (ns status-im2.contexts.wallet.common.utils
```
Comment (ulisesmac) [inline src/status_im2/contexts/wallet/common/utils.cljs]: Besides using functions in utils.money, this file also had a refactor

File: src/status_im2/contexts/wallet/events.cljs [hunk 5]
```diff
@@ -102,17 +103,19 @@
...
+      (update :balances-per-chain update-keys (comp utils.number/parse-int name))))
 
 (rf/reg-event-fx
  :wallet/store-wallet-token
  (fn [{:keys [db]} [raw-tokens-data]]
    (let [tokens     (-> raw-tokens-data
                         (update-keys name)
                         (update-vals #(cske/transform-keys csk/->kebab-case %))
-                        (update-vals #(mapv fix-chain-id-keys %)))
+                        (update-vals #(mapv fix-balances-per-chain %)))
```
Comment (ulisesmac) [inline src/status_im2/contexts/wallet/events.cljs:124]: Here, when the token raw-balance is received it is being stored as  bignumber instances

File: src/status_im2/contexts/wallet/common/utils.cljs [hunk 6]
```diff
@@ -23,23 +24,23 @@
...
 
-(defn calculate-balance
-  [tokens-in-account]
-  (->> tokens-in-account
-       (map (fn [token]
-              (* (total-token-value-in-all-chains token)
-                 (-> token :market-values-per-currency :usd :price))))
-       (reduce +)))
+(defn calculate-balance-for-account
+  [{:keys [tokens] :as _account}]
```
Comment (J-Son89) [inline src/status_im2/contexts/wallet/common/utils.cljs:65]: Why do we need as _account? Can't it just be removed?

File: src/status_im2/subs/wallet/wallet_test.cljs [hunk 7]
```diff
@@ -84,9 +86,12 @@
...
   (testing "a map: address->balance"
     (swap! rf-db/app-db #(assoc-in % [:wallet :accounts] accounts))
+    (let [result      (rf/sub [sub-name])
+          balance-0x1 (money/bignumber 3250)
+          balance-0x2 (money/bignumber 2100)]
 
-    (is (= {"0x1" 3250 "0x2" 2100}
-           (rf/sub [sub-name])))))
+      (is (money/equal-to balance-0x1 (get result "0x1")))
+      (is (money/equal-to balance-0x2 (get result "0x2"))))))
```
Comment (ulisesmac) [inline src/status_im2/subs/wallet/wallet_test.cljs:94]: This file is now testing against bignumber instances. the function `utils.money/equal-to` is needed to check equality between them.

File: src/utils/money.cljs [hunk 8]
```diff
@@ -204,10 +204,14 @@
...
 
-(defn add
+(defn- add*
   [bn1 n2]
   (.add ^js bn1 n2))
 
+(def add
+  "Add with defaults, this version is able to receive `nil` and takes them as 0."
+  (fnil add* (bignumber 0) (bignumber 0)))
+
```
Comment (ulisesmac) [inline src/utils/money.cljs:215]: Added a more flexible version of `add`.
I'd really like to get your feedback about this change.

Comparison between this version and the previous one:
```clojure

(reduce money/add [])
;; Before:
;; Exception about null has no .add method
;; Now:
;; => (bignumber 0)

(reduce money/add [(money/bignumber 10)])
;; Before:
;; => (bignumber 10)
;; Now:
;; => (bignumber 10)

(reduce money/add [(money/bignumber 10) (money/bignumber 20) (money/bignumber 30)])
;; Before:
;; => (bignumber 60)
;; Now:
;; => (bignumber 60)

(money/add (money/bignumber 10))
;; Before:
;; Exception about no method plus() found in null
;; Now:
;; => (bignumber 10)

(money/add (money/bignumber 10) nil)
;; Before:
;; Exception about no method plus() found in null
;; Now:
;; => (bignumber 10)

(money/add nil (money/bignumber 10))
;; Before:
;; Exception about null has no .add method
;; Now:
;; => (bignumber 10)

(money/add nil nil)
;; Before:
;; Exception about null has no .add method
;; Now:
;; => (bignumber 0)
```

File: src/status_im2/subs/wallet/wallet_test.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im2/subs/wallet/wallet_test.cljs:4]: No difference, I can revert it, just wanted to  have the same style in all the requires (using `[]`)

File: src/status_im2/contexts/wallet/common/utils.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im2/contexts/wallet/common/utils.cljs:65]: Can be removed.

Just wanted to give more clarity, the function is `calculate-balance-for-account` and receives an `account`, from that `account` we extract the `tokens`.

The `_` doesn't throw warnings since in Clojure the var `_` or `_someting` mean they are named to be ignored as vars.

I can understand if that's a code style we don't want to use.

File: src/status_im2/subs/wallet/wallet_test.cljs (hunk 2 above)
Comment (J-Son89) [reply src/status_im2/subs/wallet/wallet_test.cljs:4]: no need, I was just wondering

File: src/status_im2/contexts/wallet/common/utils.cljs (hunk 6 above)
Comment (J-Son89) [reply src/status_im2/contexts/wallet/common/utils.cljs:65]: no strong opinions, I agree it's clearer this way.

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/wallet/common/utils.cljs [hunk 9]
```diff
@@ -23,23 +24,23 @@
...
-(defn- total-token-value-in-all-chains
-  [{:keys [balances-per-chain decimals]}]
+(defn- total-raw-balance-in-all-chains
+  [balances-per-chain]
   (->> balances-per-chain
-       (vals)
-       (map #(calculate-raw-balance (:raw-balance %) decimals))
-       (reduce +)))
+       (map (comp :raw-balance val))
+       (reduce money/add)))
```
Comment (smohamedjavid) [inline src/status_im2/contexts/wallet/common/utils.cljs:37]: ❤️

File: src/status_im2/contexts/wallet/common/utils.cljs [hunk 10]
```diff
@@ -23,23 +24,23 @@
...
+
+(defn- total-token-fiat-value
+  "Returns the total token fiat value taking into account all token's chains."
+  [{:keys [balances-per-chain decimals market-values-per-currency]}]
+  (let [usd-price                 (-> market-values-per-currency :usd :price)
+        total-units-in-all-chains (-> balances-per-chain
+                                      (total-raw-balance-in-all-chains)
+                                      (money/token->unit decimals))]
+    (money/crypto->fiat total-units-in-all-chains usd-price)))
```
Comment (smohamedjavid) [inline src/status_im2/contexts/wallet/common/utils.cljs:62]: Love the naming of the methods. Clean and neat. 🚀

File: src/utils/money.cljs (hunk 8 above)
Comment (smohamedjavid) [reply src/utils/money.cljs:215]: This seems like a perfect solution to me for dealing with `nil` values as we should not allow the app to crash on `nil` values. 

Thanks for comparsion @ulisesmac!

**Review by smohamedjavid — APPROVED** [review]
🚀

**Comment by churik** [comment]
@ulisesmac can you please resolve conflicts and update it? 
thank you!

**Comment by ulisesmac** [comment]
> @ulisesmac can you please resolve conflicts and update it? thank you!

@churik  No problem! done!

**Comment by churik** [comment]
@ulisesmac 
ok, one more time please and I'll prioritize your PR just right after the conflict resolve, apologies for delay:)

File: src/status_im2/subs/wallet/wallet.cljs [hunk 11]
```diff
@@ -71,21 +71,18 @@
...
-         (filter #(or (string/starts-with? (string/lower-case (:name %))
-                                           (string/lower-case query))
-                      (string/starts-with? (string/lower-case (:symbol %))
-                                           (string/lower-case query)))
-                 sorted-tokens)]
+   (let [tokens          (map (fn [token]
+                                (assoc token
+                                       :networks           (utils/network-list token networks)
+                                       :total-balance      (utils/total-token-units-in-all-chains token)
+                                       :total-balance-fiat 0))
```
Comment (ulisesmac) [inline src/status_im2/subs/wallet/wallet.cljs:78]: @churik 
For the wallet flow:
1. Select an account
2. Select Send button
3. Write an address (0x123..)
4. Select an address

the fiat balance is being returned as zero as part of this PR.

The reason is that the value has a bug in develop, and its calculation was  perfomed using code that I erased in this PR, so instead of fixing that bug here, I created an issue:
- #18067

to properly address it. And set it as zero for this PR.
cc @briansztamfater

**Comment by churik** [comment]
@ulisesmac as you mentioned that balance is 0 now (I checked it) I do not think that it is testable right now, is it true? 
For this https://etherscan.io/address/0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E
I see 
IMAGE 2023-12-05 13:16:47

I'm blocking PR for testing until the issue is resolved, let me know when it is ready, thanks!

**Comment by ulisesmac** [comment]
> @ulisesmac as you mentioned that balance is 0 now (I checked it) I do not think that it is testable right now, is it true? 
> For this https://etherscan.io/address/0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E
> I see 
> IMAGE 2023-12-05 13:16:47
> 
> I'm blocking PR for testing until the issue is resolved, let me know when it is ready, thanks!

@churik 
The balance that is zero is in the flow previously mentioned. This PR is testable besides that zero added.

As written in this PR description (in steps to test section), if you look at the account cards in wallet home, if you own more than 100 units of a token the fiat balance will show 0 in develop, but in this branch, it should return the correct fiat amount.

**Comment by churik** [comment]
@ulisesmac 
I have 667 SNT tokens and 794 RARE in my account https://etherscan.io/address/0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E
On the account card the balance is loading correctly, on PR it is 0 everywhere. 

**Nightly:**

https://github.com/status-im/status-mobile/assets/4557972/13303e8c-ba52-4ff0-92d2-ddd2bcf9d009

**PR:** 

https://github.com/status-im/status-mobile/assets/4557972/a00f33e5-742b-4791-9733-4743f89e1f84

**Comment by ulisesmac** [comment]
> @ulisesmac I have 667 SNT tokens and 794 RARE in my account https://etherscan.io/address/0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E On the account card the balance is loading correctly, on PR it is 0 everywhere.
> 
> **Nightly:**
> FILE.2023-12-06.17.49.05.mp4
> 
> **PR:**
> IMG_1884.MP4

Thanks @churik Will check it and fix it :+1:

**Comment by ulisesmac** [comment]
@churik Sorry for the delay.

We had a problem showing the balances, but now it's fixed!

About what I said related to balances:
1. It only affects to accounts card (the row of cards in wallet home screen), if you press the card, another screen will appear, that's not covered in this PR.
2. It was wrong that 100 token units show the error, they should be at least 1000 units, so if you have more than 1000 of a token, it'll be calculated wrongly and will affect the total balance in develop. In this branch the total balance will be correct.

To test it, we have two options:
1. An account with a single token that has more than 1000 units, the total balance will be wrong in develop, in this branch it'll be the correct amout.
2. An account with many tokens and more than 1000 units of certain tokens. The balance in develop will be less than the balance in this branch since in develop, those 1000 units will be taken as zero or one sometimes.

A random address I found in etherscan:
https://etherscan.io/address/0x0802dd2edd3f9fad39a9173b4595be819f201d61
the total balance in develop:
image


is less than the total balance in this branch:
image


since, as I said, the tokens being more than 1000 are not calculated correctly. This is just a small example to show the difference in calculations.

**Comment by churik** [comment]
Another account to test: https://etherscan.io/address/0x7bdf634f898ad124a9adb7a1aff95a95aa864cbb 

Just keeping here for the history, that only `total fiat amount on wallet card` on Home > Wallet is fixed, inside the account the values for tokens are still wrong.
photo_2023-12-08 13 17 45 jpeg 2023-12-08 13-18-04

**Comment by ulisesmac** [comment]
> Another account to test: https://etherscan.io/address/0x7bdf634f898ad124a9adb7a1aff95a95aa864cbb
> 
> Just keeping here for the history, that only `total fiat amount on wallet card` on Home > Wallet is fixed, inside the account the values for tokens are still wrong. photo_2023-12-08 13 17 45 jpeg 2023-12-08 13-18-04

@OmarBasem Since you are going to modify that code again, this might interest you.

I think it's due to two reasons:
- (as discussed yesterday) not taking into account all chains
- Not using bignumbers

In this PR I'm using bignumbers for the total balance calculation -it may give you a hint-, also testing with more than 1000 units per token can help.
