### PR TITLE
[Fix] Scanned address not populated in send flow

### LINKED ISSUE #18681: Scanned eth address not pasted in 'Send to' screen
### Steps:
1. Go to the 'Send to' screen
2. Open any non-default tab (for instance: 'saved' or 'my accounts')
3. type some data into the 'Send to' input field
4. Tap [x] to clear this field
5. Scan any valid eth address QR

### Actual result:
The scanned address is not pasted

https://github.com/status-im/status-mobile/assets/52490791/d8cc59c2-1f5b-40dd-b3ab-57761217052b

### Expected result:
The scanned address should be pasted into the 'Send to' input field

### ENV:
Nihglty [30 Jan 2024]

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18681

### Summary

This PR fixes the scanned address that is not pasted/populated in the "Send to" input field.

### Review notes

The bug is caused when we scan the same address again. To fix it, we clear the scanned address in `app-db` before we scan any QR.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to the Wallet tab
- Open a wallet account
- Tap on the `Send` button
- Tap on the `[-]` icon in the input field
- Scan an address
- Clear the address in the input field
- Try to scan the SAME address again
- Verify the input field is populated with the scanned address

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/send/select_address/view.cljs [hunk 1]
```diff
@@ -36,6 +36,7 @@
         :on-blur               #(reset! input-focused? false)
         :on-scan               (fn []
                                  (rn/dismiss-keyboard!)
+                                 (rf/dispatch [:wallet/clean-scanned-address])
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/select_address/view.cljs:39]: What if the user accidentally taps the scan button after scanning and dismisses the screen? Are we sure we want to always clean the scanned address when opening this screen?

Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/select_address/view.cljs:39]: Actually it might make sense becuase the scan button is hidden in favour of the clear button when there is value in the input...

**Review by ulisesmac — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @smohamedjavid !
Thanks, PR checked and can be merged!
Failed tests are not related.
