### PR TITLE
Fixed amounts for multiple collectibles

### LINKED ISSUE #20728: The count of multi collectibles is incorrectly shown on the wallet main page after sending it on the additional address
### Steps:
1. The user has 2 wallet addresses
2. Send multi collectible form "Address 1" to "Address 2"
3. Check the result within the wallet main page

### Actual result:
- The Collectible is doubled on the collectible list view
- The count of Collectibles is incorrectly  shown on the collectible detailed page (shown as 5, but in fact = 9895)

https://github.com/user-attachments/assets/634be942-ad59-4609-84e2-66b28900da8c

- The collectible count is shown incorrectly on the list view of opened "account 1" (in my case shown as 19790, but if fact = 9895)
image

### Expected result:
The collectible is not doubled on the wallet main page; On the wallet main page the counf of collectible = total count of all collectibles on all available accounts

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Notes:
Problem can be solved on `status-mobile` side but there is also a [status-go issue](https://github.com/status-im/status-go/issues/5827) that causes it.

### PR DESCRIPTION
**Pull request by vkjr**
fixes #20728

### Summary

Fixed issues with displaying multiple collectibles when they belong to different accounts

Uploading Simulator Screen Recording - iPhone 13 - 2024-09-09 at 17.10.12.mp4…

##### Functional

- wallet / transactions

### Steps to test
- The user has 2 wallet addresses
- Send multi collectible form "Address 1" to "Address 2"
- Check the result within the wallet main page

**Expected result:**
The collectible is not doubled on the wallet main page; On the wallet main page the counf of collectible = total count of all collectibles on all available accounts

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs [hunk 1]
```diff
@@ -63,7 +63,9 @@
 
 (defn view
   [collectible]
-  (let [owner-account (rf/sub [:wallet/collectible-details-owner collectible])
+  (let [owner-address (or (rf/sub [:wallet/current-viewing-account-address])
+                          (-> collectible :ownership first :address))
+        owner-account (rf/sub [:wallet-connect/account-details-by-address owner-address])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs:68]: I think all of this logic could be wrapped in a single subscription.

@vkjr could you please elaborate on which cases the `current-viewing-account` is `nil` so that we rely on `collectible`'s data? I'm also wondering why we don't always rely on `collectible`'s data

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 2]
```diff
@@ -157,12 +157,10 @@
             set-title-ref                  (rn/use-callback #(reset! title-ref %))
             animation-shared-element-id    (rf/sub [:animation-shared-element-id])
             collectible                    (rf/sub [:wallet/collectible-details])
-            collectible-owner              (rf/sub [:wallet/collectible-details-owner collectible])
+            collectible-owner              (rf/sub [:wallet/current-viewing-account])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/view.cljs:160]: Are we sure the `current-viewing-account` always refelcts the colletible owner? for example, in the wallet home screen, the `current-viewing-account` may be `nil`

File: src/status_im/subs/wallet/collectibles.cljs [hunk 3]
```diff
@@ -118,21 +119,20 @@
  :wallet/collectible-details-owner
  :<- [:wallet/accounts]
  (fn [accounts [_ collectible]]
-   (let [collectible-address (-> collectible :ownership first :address)]
-     (some #(when (= (:address %) collectible-address)
+   (let [owner-address (-> collectible :ownership first :address)]
+     (some #(when (= (:address %) owner-address)
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/collectibles.cljs:124]: :+1:

File: src/status_im/subs/wallet/collectibles.cljs [hunk 4]
```diff
@@ -118,21 +119,20 @@
...
            accounts))))
 
 (re-frame/reg-sub
  :wallet/total-owned-collectible
  :<- [:wallet/accounts-without-watched-accounts]
  (fn [accounts [_ ownership address]]
-   (let [addresses (map :address accounts)]
+   (let [addresses (if address
+                     #{address}
+                     (set (map :address accounts)))]
```
Comment (ulisesmac) [inline src/status_im/subs/wallet/collectibles.cljs:134]: nit, maybe shorter by using:
```clojure
(set (or address (map :address accounts)))
```

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 5]
```diff
@@ -244,7 +244,10 @@
                                              first
                                              key)
          ownership-status            (get ownership-status-by-address owner-address)
-         collectibles                (data-store/rpc->collectibles collectibles)
+         collectibles                (->> collectibles
+                                          data-store/rpc->collectibles
+                                          (map #(update % :ownership distinct))
+                                          vec)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs:250]: was the problem due to ownerships being duplicated? :thinking: 

Any reason behind why we receive such information from status-go?

**Review by ulisesmac — APPROVED** [review]
Hi @vkjr 

Thank you so much for opening this PR! I left some minor comments

File: src/status_im/contexts/wallet/send/select_collectible_amount/view.cljs [hunk 6]
```diff
@@ -45,9 +48,9 @@
        :status          (if incorrect-value? :error :default)
        :container-style style/network-tags-container}]
      [quo/amount-input
-      {:max-value       (controlled-input/upper-limit value)
-       :min-value       (controlled-input/lower-limit value)
-       :value           (controlled-input/numeric-value value)
+      {:max-value       (-> value controlled-input/upper-limit money/to-number)
+       :min-value       (-> value controlled-input/lower-limit money/to-number)
+       :value           (-> value controlled-input/numeric-value money/to-number)
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/select_collectible_amount/view.cljs]: I have fixed this part in https://github.com/status-im/status-mobile/pull/21209. These methods are used in multiple places (swaps, collectibles).

File: src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs (hunk 1 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/collectible/tabs/overview/view.cljs:68]: The problem with collectible data is that it has information about all the owners inside of it. And when we are interested in balance for particular owner, we need to extract it knowing owner address we are interested in.
If we store collectible as copies with different ownership records that make it harder to display them as a single item on main wallet page (I tried this approach).

`current-viewing-account` can be `nil` on main wallet page but this is totally okay. In this case we calculate collectible balance by summing balances on all accounts we own.

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 2 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/collectible/view.cljs:160]: Yes and this okay, subscription`:wallet/total-owned-collectible` takes care of this.

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 5 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/collectible/events.cljs:250]: Yes, partially it was.
Don't know the reason, I tried to investigate it in `status-go` but that took too much time, so I decided to fix it on mobile side first.

File: src/status_im/contexts/wallet/send/select_collectible_amount/view.cljs (hunk 6 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/send/select_collectible_amount/view.cljs]: Thanks!

**Comment by Horupa-Olena** [comment]
Hey @vkjr !

Thanks for PR!
Please, resolve the conflicts and rebase your PR.

**Comment by vkjr** [comment]
@Horupa-Olena, done)

**Comment by vkjr** [comment]
@Horupa-Olena, tell me if you need any help to push this PR forward!

**Comment by Horupa-Olena** [comment]
Hi @vkjr!
Thanks for the offer. I hope to get back to testing this PR soon.
I had to switch to another PR, which turned out to be more complex and extensive than I initially thought.

**Comment by Horupa-Olena** [comment]
Hi @vkjr again, I'm back. Please resolve the conflicts and rebase your PR.

**Comment by vkjr** [comment]
@Horupa-Olena , done!

**Comment by Horupa-Olena** [comment]
@vkjr 
Hi! Thanks for the PR!  
Could you please clarify whether this was supposed to be done within this PR or not: when you open collectables on the main page, only one account is displayed that has them, but there should be two.
photo_2024-09-17_17-16-36

**Comment by vkjr** [comment]
@Horupa-Olena , this shouldn't be a part of the PR. @xAlisher recently created design proposal on how to display few accounts but the last time I checked it wasn't yet approved, so no related changes here.

**Comment by Horupa-Olena** [comment]
@vkjr Unfortunately, the main bug is still present – after the transaction, collectables are duplicated on the main page,


https://github.com/user-attachments/assets/eaa7255b-1358-4d96-9b37-adc3bef979b6

**Comment by Horupa-Olena** [comment]
Hi @vkjr !
Could I re-test this PR?

**Comment by vkjr** [comment]
@Horupa-Olena, not yet. Could you please ping me in discord? I wrote some clarification questions there but not sure if it was yours account?

**Comment by vkjr** [comment]
@Horupa-Olena, fixed, please check 🙏

**Comment by Horupa-Olena** [comment]
@vkjr Thank you for your fix!

The main bug has been fixed, and you can merge the PR.

**Comment by vkjr** [comment]
@Horupa-Olena, thanks!
