### PR TITLE
fix(wallet)_: Activity tab is selected on navigating back from the swap flow

### LINKED ISSUE #21464: Activity tab opens instead of previously opened tab when returning to wallet from swap flow
### Steps:
1. Go to the wallet.
2. Open an account.
3. Navigate to the swap flow.
4. Return back to the account.

### Actual Result:
Upon returning to the wallet, the "Activity" tab is opened instead of the previously opened tab on the current account

https://github.com/user-attachments/assets/ba47dccf-5c1e-4232-97f4-3d02c7a4330f

### Expected Result:
The user should be returned to the previously opened tab (such as the "assets" or "collectibles" ) instead of the "Activity" tab.

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17
### ENV:
Nightly 18 Oct, 2024

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21464

### Summary

This PR fixes activity tab is selected when navigating back from the swap flow

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to the Wallet tab
- Open an account
- Navigate to the swap flow by tapping on the Swap button
- Return to the account page
- Verify the activity tab is not selected

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 1]
```diff
@@ -204,12 +204,6 @@
  (fn [{:keys [db]}]
    {:db (update-in db [:wallet :ui] dissoc :swap)}))
 
-(rf/reg-event-fx
- :wallet/on-swap-done
- (fn [_]
-   {:fx [[:dispatch [:wallet/select-account-tab :activity]]
-         [:dispatch [:wallet/clean-swap]]]}))
-
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/swap/events.cljs:212]: @clauxx - I have kind of reverted or modified the changes introduced in #21435 by placing back the activity tab selection on successfully placing the transaction. 

Using the `:wallet/clean-swap` event on unmount Instead of the `wallet/on-swap-done` event.

**Review by clauxx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @smohamedjavid, thank you for PR. No issues from my side. Ready to be merged
