### PR TITLE
adjust colors resolver to handle communities color

### LINKED ISSUE #17295: Broken colours issues
### ISSUE 1 Request join community button in not visible

https://github.com/status-im/status-mobile/assets/97245802/58933805-3a1a-4b5a-922c-77dec25efaeb

### ISSUE 2 Unread community channel counters are not visible

**Light mode:** 

photo_2023-09-15 12 00 35

**Dark mode:**

photo_2023-09-15 12 00 38

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/17295

also fixes: https://github.com/status-im/status-mobile/pull/17202#discussion_r1330338178

now:

### CODE REVIEW

File: src/quo2/foundations/colors_test.cljs [hunk 1]
```diff
@@ -0,0 +1,27 @@
+(ns quo2.foundations.colors-test
+  (:require [cljs.test :refer-macros [deftest testing is]]
+            [quo2.foundations.colors :as colors]))
+
+(deftest test-color-resolver
```
Comment (J-Son89) [inline src/quo2/foundations/colors_test.cljs]: Added some tests as it is the core resolver of colors

File: src/quo2/foundations/colors.cljs [hunk 2]
```diff
@@ -272,24 +272,32 @@
...
 (defn custom-color-by-theme
+
   "(custom-color-by-theme color suffix-light suffix-dark opacity-light opacity-dark)
    color         :primary/:purple/...
    suffix-light  50/60
    suffix-dark   50/60
    opacity-light 0-100 (optional)
    opacity-dark  0-100 (optional)
    theme         :light/:dark (optional)"
+  {:deprecated
```
Comment (ilmotta) [inline src/quo2/foundations/colors.cljs]: Nice! I'd prefer if we were more direct, like in the Clojure style guide, example: 

```clojure
{:deprecated "Use `theme-colors` instead"}
```

Or since we don't version the code:

```clojure
{:deprecated true :superseded-by "theme/colors"}
```

The Clojure style guide also suggest using the docstring to explain in more detail why something is deprecated if we think there's a need for that.

Well, almost anything will do, but since we basically follow the CSG, why not for the deprecation metadata :)

File: src/quo2/foundations/colors_test.cljs (hunk 1 above)
Comment (ilmotta) [inline src/quo2/foundations/colors_test.cljs]: The idiomatic naming of the test var is usually `<function-name>-test`, so `custom-color-test`, or in case you want to separate the `deftest`s, `custom-color-resolver-with-opacity-test` and `custom-color-resolver-with-default-opacity-test`.

Anything that helps the reader quickly understand which function is under test will be fine imo. Here I had to scan the assertions to be sure we were testing only `custom-color`.

**Review by ilmotta — APPROVED** [review]

File: src/quo2/foundations/colors.cljs [hunk 3]
```diff
@@ -272,24 +272,32 @@
...
+                                 :else                                (get-in colors-map
+                                                                              [color suffix]))]
         (cond
-          (and opacity hex?) (alpha color (/ opacity 100))
-          opacity            (alpha color (/ opacity 100))
-          hex?               color
-          :else              color))))))
+          (and opacity hex?) (alpha resolved-color (/ opacity 100))
+          opacity            (alpha resolved-color (/ opacity 100))
+          hex?               resolved-color
```
Comment (siddarthkay) [inline src/quo2/foundations/colors.cljs]: question : is this condition necessary ? `hex? resolved-color`
I think you already take care of that in the let binding above ?

**Review by siddarthkay — APPROVED** [review]
Apart from existing comments, this PR LGTM!

**Review by Parveshdhull — APPROVED** [review]

File: src/quo2/foundations/colors.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo2/foundations/colors.cljs]: yeah good point, I think it should be removed 👍

File: src/status_im2/contexts/shell/jump_to/utils.cljs [hunk 4]
```diff
@@ -126,7 +126,7 @@
 (defn change-shell-status-bar-style
   []
   (rf/dispatch [:change-shell-status-bar-style
-                (if (or (quo.theme/get-theme)
+                (if (or (= :dark (quo.theme/get-theme))
```
Comment (J-Son89) [inline src/status_im2/contexts/shell/jump_to/utils.cljs:129]: @Parveshdhull I added this fix here which I missed in my last pr 🙃

**Comment by J-Son89** [comment]
addressed the comments 👍

File: src/quo2/foundations/colors.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo2/foundations/colors.cljs]: thanks for spotting that @siddarthkay, also found other redundancies. was straightforward to refactor with tests in place :)

Comment (siddarthkay) [reply src/quo2/foundations/colors.cljs]: Awesome!!!

**Comment by VolodLytvynenko** [comment]
hi @J-Son89 thank you for PR. No issues from my side. Ready to be merged
