### PR TITLE
Fix QR share screen for community channel

### LINKED ISSUE #19608: Community Channel QR code coloured background moved to the left
# Bug Report

Profile (Generic)

## Problem 
[comment]: # (A problem description)
Coloured background moved to the left

#### Expected behavior

https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&mode=design&t=wQLeIxD9gkb39Kj6-0

#### Actual behavior
Community Channel QR code coloured background moved to the left
Screenshot 2024-04-10 at 18 21 13

### Reproduction

1. Login to app
2. Go to Communities -> Open any of joined
3. Long tap on any channel
4. Show QR code

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices: iOS 13 (17.3.1) Samsung A34 (14.0)

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #19608

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

* This PR attempts to fix the alignment issues and add missing UI elements when opening the QR share screen for a community channel.

#### Platforms

- Android
- iOS

##### Functional

- Sharing QR code for community channel

### Steps to test

Reproduction steps are described in #19608 

#### Before

https://github.com/status-im/status-mobile/assets/2845768/bdce346d-f701-4e0b-ac02-a118afc81fb7

#### After

https://github.com/status-im/status-mobile/assets/2845768/bca3e0b3-18ab-4987-aa35-2e20f6081fb9

status: ready

### CODE REVIEW

File: src/quo/components/share/share_qr_code/view.cljs [hunk 1]
```diff
@@ -153,7 +160,7 @@
          {:color           colors/white-opa-40
           :container-style style/watched-account-icon}])]
      [share-button {:on-press on-share-press}]]
-    (when (not= share-qr-type :profile)
+    (when (not (contains? #{:profile :channel} share-qr-type))
```
Comment (shivekkhurana) [inline src/quo/components/share/share_qr_code/view.cljs]: If it's easy to determine, have a positive if condition, ie. `(when (= % :account))`.

If not easy to determine, a more explicit `or` is preferable. `contains?` feels fragile.

File: src/status_im/contexts/communities/actions/share_community_channel/view.cljs [hunk 2]
```diff
@@ -11,9 +11,16 @@
 (defn view
   []
   (fn []
-    (let [{:keys [url chat-id]}           (rf/sub [:get-screen-params])
+    (let [params                          (rf/sub [:get-screen-params])
+          ;; NOTE(seanstrom): We need to store these screen params for when the modal closes
+          ;; because the screen params will be cleared.
+          {:keys [url chat-id]}           @(rn/use-ref-atom params)
```
Comment (shivekkhurana) [inline src/status_im/contexts/communities/actions/share_community_channel/view.cljs:19]: Since the screen params are present in re-frame state, can't we just fetch it from there whenever we need it ? 

Why create an extra copy?  What's the constraint here ?

File: src/status_im/contexts/communities/actions/share_community_channel/view.cljs [hunk 3]
```diff
@@ -11,9 +11,16 @@
...
           {:keys [color emoji chat-name]} (rf/sub [:chats/community-channel-ui-details-by-id chat-id])
-          window-width                    (rf/sub [:dimensions/window-width])]
+          on-share-community-channel      (rn/use-callback
+                                           #(rf/dispatch
+                                             [:communities/share-community-channel-url-with-data
```
Comment (shivekkhurana) [inline src/status_im/contexts/communities/actions/share_community_channel/view.cljs:23]: There is a navigate back somewhere in this component. That can be extracted to the let bind and wrapped in a `use-callback`.

Not related to your code, but a simple housekeeping win.

File: src/status_im/contexts/communities/actions/share_community_channel/view.cljs [hunk 4]
```diff
@@ -11,9 +11,16 @@
...
+                                              chat-id])
+                                           [chat-id])]
       [quo/overlay {:type :shell}
        [rn/view
         {:style {:padding-top (safe-area/get-top)}
```
Comment (shivekkhurana) [inline src/status_im/contexts/communities/actions/share_community_channel/view.cljs]: I know you didn't introduce this change, but this goes against the guidelines. 

Styles should always be in the `style` ns.

File: src/status_im/contexts/preview/quo/share/share_qr_code.cljs [hunk 5]
```diff
@@ -16,7 +16,8 @@
     :options [{:key :profile}
               {:key :wallet}
               {:key :saved-address}
-              {:key :watched-address}]}])
+              {:key :watched-address}
+              {:key :channel}]}])
 
 (def possible-networks [:ethereum :optimism :arbitrum :myNet])
```
Comment (shivekkhurana) [inline src/status_im/contexts/preview/quo/share/share_qr_code.cljs:22]: what is `:myNet` 🤔

**Review by shivekkhurana — CHANGES_REQUESTED** [review]
Requested some changes and left some comments not related to your work.

Please feel free to ignore the issues you did not introduce.

File: src/quo/components/share/share_qr_code/view.cljs (hunk 1 above)
Comment (shivekkhurana) [reply src/quo/components/share/share_qr_code/view.cljs]: Update: It's not easy to determine an exhaustive list. A negative filter is fine.

image

File: src/status_im/contexts/communities/actions/share_community_channel/view.cljs (hunk 2 above)
Comment (seanstrom) [reply src/status_im/contexts/communities/actions/share_community_channel/view.cljs:19]: The screen params are stored and then cleared from re-frame state when this view is animated to a closed state. So what will happen is that the `url` and `chat-id` will be set to `nil`, and this will cause a visual glitch with the QR code for a brief moment.

The above code is trying to prevent this visual glitch by keeping a local copy of the screen params. This way when the screen params are cleared while navigating, the QR code will still visualised with the intended `url` value.

Comment (shivekkhurana) [reply src/status_im/contexts/communities/actions/share_community_channel/view.cljs:19]: Does this apply only to this QR code (the visual glitch) or all QR codes?

**Comment by shivekkhurana** [comment]
After yesterday's conversation on `use-callback` and `use-memo`, navigate back probably doesn't need to be a callback. 

Marking as approved as none of my comments are related to your work directly.

**Review by shivekkhurana — APPROVED** [review]

File: src/status_im/contexts/communities/actions/share_community_channel/view.cljs (hunk 4 above)
Comment (clauxx) [reply src/status_im/contexts/communities/actions/share_community_channel/view.cljs]: I think there was a point about it being allowed to inline styles if its just one property

File: src/status_im/contexts/communities/actions/share_community_channel/view.cljs (hunk 2 above)
Comment (seanstrom) [reply src/status_im/contexts/communities/actions/share_community_channel/view.cljs:19]: Good question, I think most other QR codes are unaffected because we don't the screen-params for passing identifiers, they're sorta implicitly in scope for things like wallet accounts or contacts. But communities and community channels do not always have their identifiers implicitly in scope.

For example, we can navigate directly from the home screen to a community QR code, which leads to us passing the community-id through the screen params manually.

I've updated the PR to include a fix for community QR codes as well 🙏

**Review by clauxx — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @seanstrom !🙌

I am moving back your PR to the corresponding column as it doesn't meet the requirements outlined here:
https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md

Please, make sure your PR contains all necessary labels + information to PR's description.
Thanks!🙏

**Comment by seanstrom** [comment]
@mariia-skrypnyk sorry about that 🙏 
I've updated the PR with `request-manual-qa`, but I'm wondering since this is mostly visual fixes, if this is a good candidate for `skip-manual-qa`. thoughts?

**Comment by mariia-skrypnyk** [comment]
@seanstrom yes, it's a tiny issue but I'll check it as PR queue is not so big at the moment.
Thanks for highlighting it! 
Good catch!

**Comment by mariia-skrypnyk** [comment]
@seanstrom your fix is checked!
Looks good from my side.
Ready to be merged!
