### PR TITLE
Fixed incorrect margin for toolbar action buttons

### LINKED ISSUE #1792: Double arrow icon is misplaced in new wallet [develop]
### Description

*Type*: Bug

*Summary*: Double arrow icon should be centered and not top-aligned

#### Actual behavior
image

### Additional Information
* Status version: 0.9.10-75-gad7c6b85+
* Operating System: Android

### PR DESCRIPTION
**Pull request by jeluard**
fixes #1792

### Summary:

Toolbar icons are not properly aligned on Android

### Steps to test:
- Open Status
- Check toolbar action icons are properly aligned on both iOS and Android
- Make sure value change % doesn't display 2 `-` when negative

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/subs.cljs [hunk 1]
```diff
@@ -47,11 +47,11 @@
   :<- [:price]
   :<- [:last-day]
   (fn [[price last-day]]
-    (if (and price last-day)
+    (println "price" price last-day)
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/subs.cljs]: debug print

**Review by rasom — APPROVED** [review]

File: src/status_im/ui/screens/wallet/subs.cljs (hunk 1 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/subs.cljs]: Fixed

**Review by yenda — APPROVED** [review]
