### PR TITLE
fix keycard navigation bugs

### LINKED ISSUE #7891: App crashes if send transaction from chat signed with keycard
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: App crashes if send transaction from chat:

```
04-03 17:29:43.470 26863 26901 I ReactNativeJS: MESSAGE: Error: Error: Error: Error: There is no route defined for key wallet-transaction-sent.
04-03 17:29:43.470 26863 26901 I ReactNativeJS: Must be one of: 'wallet-send-transaction-modal','wallet-transaction-sent-modal','wallet-transaction-fee','hardwallet-connect','enter-pin'
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in _
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in u
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in C
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in E
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in H
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in L
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in v
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in _
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in u
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in C
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in E
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in n
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in H
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in L
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in v
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in _
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in s
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in h
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: This error is located at:
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in N
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent2
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in root
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in reagent1
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in RCTView
04-03 17:29:43.470 26863 26901 I ReactNativeJS: in c
04-03 17:29:43.470 26863 26901 I ReactNativeJS:

```

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
no crash, transaction is sent or error message explaining why it can't be sent

#### Actual behavior
[comment]: # (Describe what actually happened.)
crash

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status and sign in with keycard
* open 1:1 chat with a contact
* send 0.0001 ETHro 
* Sign transaction 
* enter valid PIN
* check if transaction is sent or error message is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 9, Pixel XL

#### Logs
[geth.log](https://github.com/status-im/status-react/files/3039469/geth.log)
[Status.log](https://github.com/status-im/status-react/files/3039470/Status.log)

### LINKED ISSUE #7897: PIN screen is shown if cancel sign message in DApp and switch to Chats tab
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: PIN screen is shown on Chats tab after user returns from PIN screen to sign a message in the DApp and taps on Chats tab

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
list of Chats is shown (or some opened chat)

#### Actual behavior
[comment]: # (Describe what actually happened.)
PIN screen is shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/open?id=1thgsPdxlsqCN4zQyppuVXQxt44n9G_k5
While on Ropsten network:

* Open Status and sign in with keycard
* Switch to DApps tab, scroll to the very end and tap on Status Test Dapp
* in Test DApp: tap on Transactions -> Sign message. As a result, Sign message screen will be shown
* tap on Sign
* DO NOT enter PIN. Tap on "<" button in top left corner to return to the Dapp
* tap on Chats icon

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: 0.12.0 apk http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190402-123212-80ef5d-pr.apk
* Operating System: Android 9, Pixel XL

#### Logs
[comment]: # (if on Android please replicate bug whilst running adb logcat)
[Status.log](https://github.com/status-im/status-react/files/3039711/Status.log)

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #7897 
fixes #7891

### Summary

* Fix bug when PIN screen is shown after tapping on chat icon
* Fix navigation bug after tx signed with keycard

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 1]
```diff
@@ -117,7 +117,8 @@
    (let [{:keys [id method public-key to symbol amount-text on-result on-error
                  send-transaction-message?]}
          (get-in db [:wallet :send-transaction])
-         db' (assoc-in db [:wallet :send-transaction :in-progress?] false)]
+         db' (assoc-in db [:wallet :send-transaction :in-progress?] false)
+         screens-before (set (take 3 (:navigation-stack db)))]
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/events.cljs]: Maybe worth a comment?

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/events.cljs (hunk 1 above)
Comment (dmitryn) [reply src/status_im/ui/screens/wallet/send/events.cljs]: @jeluard comments added

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 2]
```diff
@@ -117,7 +117,12 @@
    (let [{:keys [id method public-key to symbol amount-text on-result on-error
                  send-transaction-message?]}
          (get-in db [:wallet :send-transaction])
-         db' (assoc-in db [:wallet :send-transaction :in-progress?] false)]
+         db' (assoc-in db [:wallet :send-transaction :in-progress?] false)
+         ; NOTE: we check last 3 screens to understand if wallet modal screen was used
+         ; (not just last one, we need to account for 'Enter PIN' and 'Keycard connect' screens)
+         screens-before (set (take 3 (:navigation-stack db)))
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/events.cljs]: maybe we could use some temporary value and do not rely on `(take 3 (:navigation-stack db))` doesn't look reliably

Comment (dmitryn) [reply src/status_im/ui/screens/wallet/send/events.cljs]: @flexsurfer I can add flag `:modal?` to `:navigation/screen-params` and set/unset it every time wallet send tx flow is initialized. Is that what you had in mind?

Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/send/events.cljs]: yeah smth like that

Comment (dmitryn) [reply src/status_im/ui/screens/wallet/send/events.cljs]: @flexsurfer done, please check

**Review by rasom — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by dmitryn** [comment]
@asemiankevich ready to be tested, but e2e tests didn't run here for some reason

**Comment by asemiankevich** [comment]
@dmitryn is the PR  suppose to send tokens too?

image

**Comment by dmitryn** [comment]
@asemiankevich you get this error by sending tokens from chat?

**Comment by asemiankevich** [comment]
> @asemiankevich you get this error by sending tokens from chat?

@dmitryn yes

**Comment by dmitryn** [comment]
@asemiankevich thanks, let me check it

**Comment by dmitryn** [comment]
@asemiankevich sending tokens with keycard doesn't work in general. Looks like it was broken before this PR. I will fix it in current PR

**Comment by dmitryn** [comment]
@asemiankevich tokens sending fixed, please check 

http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190508-113821-9c9264-pr.apk

**Comment by asemiankevich** [comment]
@dmitryn weird navigation when i change network to ropsten

1. open status
2. create account with keycard 
3. login
4. profile -> dev mode -> ropsten
5. note that user is asked for PIN
6. login and notice that there is endless spinner on Chats
7. tap Profile tab -> Create PIN screen is shown
8. tap Back button and notice New network screen is shown



```
2019-05-09 11:50:45.338 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set
2019-05-09 11:50:52.078 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.ui/dev-mode-switched
2019-05-09 11:50:54.936 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:50:54.941 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:50:55.426 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :navigate-to
2019-05-09 11:50:55.436 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :network-settings nil
2019-05-09 11:50:55.982 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :network-settings
2019-05-09 11:50:55.995 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-05-09 11:50:56.007 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:73] - :main-component-did-update :network-settings
2019-05-09 11:50:56.187 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set-once
2019-05-09 11:50:57.842 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :network.ui/network-entry-pressed
2019-05-09 11:50:57.857 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :network-details {:networks/selected-network {:id "testnet_rpc", :name "Ropsten with upstream RPC", :config {:NetworkId 3, :DataDir "/ethereum/testnet_rpc", :UpstreamConfig {:Enabled true, :URL "https://ropsten.infura.io/v3/f315575765b14720b32382a61a89341a"}}, :custom? false}}
2019-05-09 11:50:58.033 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :network-details
2019-05-09 11:50:58.043 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-05-09 11:50:58.052 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:73] - :main-component-did-update :network-details
2019-05-09 11:50:58.934 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :network.ui/connect-network-pressed
2019-05-09 11:50:59.878 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :status-im.network.core/connect-success
2019-05-09 11:51:00.901 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :network.ui/save-rpc-network-pressed
2019-05-09 11:51:00.947 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.update.callback/save-settings-success
2019-05-09 11:51:00.967 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.filters:23] - :stop-watching [object Object]
2019-05-09 11:51:00.974 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.filters:23] - :stop-watching [object Object]
2019-05-09 11:51:00.980 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.logout/filters-removed
2019-05-09 11:51:01.016 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :enter-pin nil
2019-05-09 11:51:01.262 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :enter-pin
2019-05-09 11:51:01.279 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-05-09 11:51:01.296 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:73] - :main-component-did-update :enter-pin
2019-05-09 11:51:01.516 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set
2019-05-09 11:51:01.523 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :shh.callback/filter-removed
2019-05-09 11:51:01.532 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :shh.callback/filter-removed
2019-05-09 11:51:01.535 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:01.538 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"node.stopped","event":null}
2019-05-09 11:51:01.561 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set-once
2019-05-09 11:51:05.956 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-05-09 11:51:06.096 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-05-09 11:51:06.245 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-05-09 11:51:06.395 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-05-09 11:51:06.546 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-05-09 11:51:06.700 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/pin-numpad-button-pressed
2019-05-09 11:51:06.710 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet/process-pin-input
2019-05-09 11:51:10.410 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.callback/on-get-keys-success
2019-05-09 11:51:10.424 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.keychain.core:190] - initializing realm encryption key...
2019-05-09 11:51:10.426 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.keychain.core:172] - PERF initializing realm encryption key... 1557391870425
2019-05-09 11:51:10.432 4897-4969/? D/ReactNativeJS: DEBUG [status-im.data-store.core:30] - changing account to:  59e6bed76de9bdac4444268a8d5e5014b40426f2
2019-05-09 11:51:10.434 4897-4969/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:194] - closing account realm
2019-05-09 11:51:10.454 4897-4969/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:245] - try to encrypt with password
2019-05-09 11:51:10.460 4897-4969/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:247] - try to encrypt with password success
2019-05-09 11:51:10.471 4897-4969/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:274] - open-account
2019-05-09 11:51:10.473 4897-4969/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:177] - migrate-realm
2019-05-09 11:51:10.480 4897-4969/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:148] - migrate schemas 42
2019-05-09 11:51:10.484 4897-4969/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:47] - Opening realm at  /data/user/0/im.status.ethereum.pr/files/../no_backup/realm/accounts/0xbe190d046db70659d9935ae805537386c703490751e280ca52cf80783f57ea00 ...
2019-05-09 11:51:10.488 4897-4969/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:49] - Using encryption key...
2019-05-09 11:51:10.497 4897-4969/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:277] - account-realm  false
2019-05-09 11:51:10.501 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :init.callback/account-change-success
2019-05-09 11:51:10.523 4897-4969/? I/ReactNativeJS: INFO [status-im.node.core:174] - Node config:  {"ClusterConfig":{"Enabled":true,"Fleet":"eth.beta","BootNodes":["enode://43947863cfa5aad1178f482ac35a8ebb9116cded1c23f7f9af1a47badfc1ee7f0dd9ec0543417cc347225a6e47e46c6873f647559e43434596c54e17a4d3a1e4@47.52.74.140:443","enode://ebefab39b69bbbe64d8cd86be765b3be356d8c4b24660f65d493143a0c44f38c85a257300178f7845592a1b0332811542e9a58281c835babdd7535babb64efc1@35.202.99.224:443","enode://436cc6f674928fdc9a9f7990f2944002b685d1c37f025c1be425185b5b1f0900feaf1ccc2a6130268f9901be4a7d252f37302c8335a2c1a62736e9232691cc3a@174.138.105.243:443","enode://5395aab7833f1ecb671b59bf0521cf20224fe8162fc3d2675de4ee4d5636a75ec32d13268fc184df8d1ddfa803943906882da62a4df42d4fccf6d17808156a87@206.189.243.57:443"],"TrustedMailServers":["enode://74957e361ab290e6af45a124536bc9adee39fbd2f995a77ace6ed7d05d9a1c7c98b78b2df5f8071c439b9c0afe4a69893ede4ad633473f96bc195ddf33f6ce00@47.52.255.195:443","enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:443","enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","enode://da61e9eff86a56633b635f887d8b91e0ff5236bbc05b8169834292e92afb92929dcf6efdbf373a37903da8fe0384d5a0a8247e83f1ce211aa429200b6d28c548@47.91.156.93:443","enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@206.189.243.168:443","enode://7de99e4cb1b3523bd26ca212369540646607c721ad4f3e5c821ed9148150ce6ce2e72631723002210fac1fd52dfa8bbdf3555e05379af79515e1179da37cc3db@35.188.19.210:443"],"StaticNodes":["enode://d85b87dbcd251ca21bdc4085d938e54a9af3538dd6696e2b99ec9c4694bc3eb8c6689d191129f3d9ee67aac8f0174b089143e638369245c88b9b68b9291216ff@35.224.150.136:443","enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443"],"RendezvousNodes":["/ip4/206.189.243.57/tcp/30703/ethv4/16Uiu2HAmLqTXuY4Sb6G28HNooaFUXUKzpzKXCcgyJxgaEE2i5vnf","/ip4/174.138.105.243/tcp/30703/ethv4/16Uiu2HAmRHPzF3rQg55PgYPcQkyvPVH9n2hWsYPhUJBZ6kVjJgdV"]},"DataDir":"/ethereum/testnet_rpc","LogLevel":"INFO","Rendezvous":true,"WhisperConfig":{"Enabled":true,"LightClient":true,"MinimumPoW":0.001,"EnableNTPSync":true},"LogEnabled":true,"RequireTopics":{"whisper":{"Min":2,"Max":2}},"UpstreamConfig":{"Enabled":true,"URL":"https://ropsten.infura.io/v3/f315575765b14720b32382a61a89341a"},"NetworkId":3,"Name":"StatusIM","NoDiscovery":false,"ShhextConfig":{"BackupDisabledDataDir":"/data/user/0/im.status.ethereum.pr/files/../no_backup","InstallationID":"f65b9e79-fb3f-504a-af66-99455b3cb5e6","MaxMessageDeliveryAttempts":6,"MailServerConfirmations":true,"PFSEnabled":true}}
2019-05-09 11:51:10.560 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :home nil
2019-05-09 11:51:10.583 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :home
2019-05-09 11:51:10.607 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-05-09 11:51:10.617 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:73] - :main-component-did-update :home
2019-05-09 11:51:11.165 4897-4969/? D/ReactNativeJS: DEBUG [status-im.notifications.core:190] - get-fcm-token: dWB77n1qLws:APA91bFH66Msk7yllONfPDSmr83m75dYegRO95UsEyBpnPJ36SzNoiTv9mgtjJoRroLpnFbWSam0up57hsmkpltFCE_Jx_yu9Rwb-3FzRmZBi91Fpqi7PrZR6CwbgrHOtwhySp_wS2gX
2019-05-09 11:51:11.167 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :notifications.callback/get-fcm-token-success
2019-05-09 11:51:11.172 4897-4969/? D/ReactNativeJS: DEBUG [status-im.notifications.core:34] - notifications-granted
2019-05-09 11:51:11.178 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :notifications.callback/request-notifications-permissions-granted
2019-05-09 11:51:11.186 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:11.188 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"node.started","event":null}
2019-05-09 11:51:11.190 4897-4969/? D/ReactNativeJS: DEBUG [status-im.signals.core:76] - Event  node.started  not handled
2019-05-09 11:51:11.194 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:11.196 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"node.ready","event":null}
2019-05-09 11:51:11.204 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:11.206 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.started","event":null}
2019-05-09 11:51:11.209 4897-4969/? D/ReactNativeJS: DEBUG [status-im.signals.core:76] - Event  discovery.started  not handled
2019-05-09 11:51:11.212 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:11.214 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:55992","remoteAddress":"130.211.215.133:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
2019-05-09 11:51:11.221 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:11.223 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:55992","remoteAddress":"130.211.215.133:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://d85b87dbcd251ca21bdc4085d938e54a9af3538dd6696e2b99ec9c4694bc3eb8c6689d191129f3d9ee67aac8f0174b089143e638369245c88b9b68b9291216ff@35.224.150.136:443","id":"b9a315670f4aa8df31bf7051e34fbb0f5e5845d02a9d8176d65095e8fa439246","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:41354","remoteAddress":"35.224.150.136:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
2019-05-09 11:51:11.231 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.callback/on-get-application-info-success
2019-05-09 11:51:11.258 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set-once
2019-05-09 11:51:11.346 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.login.callback/login-success
2019-05-09 11:51:11.425 4897-4969/? D/ReactNativeJS: DEBUG [status-im.contact-code.core:66] - initializing contact-code
2019-05-09 11:51:11.455 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.shh:225] - PERF :shh/restore-sym-keys-batch 1557391871454
2019-05-09 11:51:11.459 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.shh:190] - PERF :add-sym-key-batch 1
2019-05-09 11:51:11.497 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.filters:27] - PERF :add-filters {:options {:privateKeyID "0x0450896d66fb854d3086411c260de1256abc2f43de9a1438e7791498f6c016dee32fc09079ff1771bec2c4915209f2a57b46c172b1a83edfa452f52aa3d01cb501", :topics ["0x84ba60fa"]}, :callback #object[c], :chat-id :discovery-topic}
2019-05-09 11:51:11.598 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:51:11.600 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:51:11.608 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :shh.callback/filters-added
2019-05-09 11:51:11.610 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.filters:81] - PERF :shh.callback/filters-added
2019-05-09 11:51:11.638 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :status-im.transport.core/sym-keys-added
2019-05-09 11:51:11.641 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.core:91] - PERF :status-im.transport.core/sym-keys-added 1
2019-05-09 11:51:11.645 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.filters:46] - PERF :shh/add-filters
2019-05-09 11:51:11.649 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.filters:27] - PERF :add-filters {:options {:topics ["0x9624ce9c"], :symKeyID "cd7e3a41b3933dafb4c69a22fa9c0c29f5eac8e0c0a6469a636fbcdd0ad3d61c"}, :callback #object[c], :chat-id "0x0450896d66fb854d3086411c260de1256abc2f43de9a1438e7791498f6c016dee32fc09079ff1771bec2c4915209f2a57b46c172b1a83edfa452f52aa3d01cb501-contact-code"}
2019-05-09 11:51:11.652 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :shh.callback/filters-added
2019-05-09 11:51:11.654 4897-4969/? D/ReactNativeJS: DEBUG [status-im.transport.filters:81] - PERF :shh.callback/filters-added
2019-05-09 11:51:11.664 4897-4969/? D/ReactNativeJS: DEBUG [status-im.mailserver.core:112] - mailserver: add-peer success true
2019-05-09 11:51:11.860 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :web3/fetch-node-version-callback
2019-05-09 11:51:11.864 4897-4969/? D/ReactNativeJS: DEBUG [status-im.mailserver.core:121] - mailserver: update-mailservers success true
2019-05-09 11:51:11.871 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :transport.callback/node-info-fetched
2019-05-09 11:51:11.903 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:11.909 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","id":"507cbf6d20917b6130d232b6aace3fad3615608ea5a06ec2cb496cfd949b7916","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51152","remoteAddress":"206.189.243.162:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:55992","remoteAddress":"130.211.215.133:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://d85b87dbcd251ca21bdc4085d938e54a9af3538dd6696e2b99ec9c4694bc3eb8c6689d191129f3d9ee67aac8f0174b089143e638369245c88b9b68b9291216ff@35.224.150.136:443","id":"b9a315670f4aa8df31bf7051e34fbb0f5e5845d02a9d8176d65095e8fa439246","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:41354","remoteAddress":"35.224.150.136:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
2019-05-09 11:51:11.957 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.ui/chaos-mode-switched
2019-05-09 11:51:12.008 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :mailserver.callback/mark-trusted-peer-success
2019-05-09 11:51:12.046 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :update-prices-success
2019-05-09 11:51:12.272 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :update-token-balance-success
2019-05-09 11:51:12.280 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :update-balance-success
2019-05-09 11:51:12.286 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :update-token-balance-success
2019-05-09 11:51:12.320 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :tribute-to-talk.callback/no-manifest-found
2019-05-09 11:51:12.492 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :mailserver.callback/generate-mailserver-symkey-success
2019-05-09 11:51:12.497 4897-4969/? D/ReactNativeJS: DEBUG [status-im.mailserver.core:416] - Mailserver: planned requests  ({:topics #{"0x84ba60fa" "0xf8946aac" "0x9624ce9c"}, :from 1557391563, :to 1557391872, :force-to? false, :gap nil, :chat-id nil})
2019-05-09 11:51:12.501 4897-4969/? D/ReactNativeJS: DEBUG [status-im.mailserver.core:288] - Adjusting mailserver request from: 1557391563 adjusted-from: 1557391543
2019-05-09 11:51:12.504 4897-4969/? I/ReactNativeJS: INFO [status-im.mailserver.core:318] - mailserver: request-messages for:   topics  #{"0x84ba60fa" "0xf8946aac" "0x9624ce9c"}  from  1557391543  force-to?  false  to  1557391872  range  309  cursor  nil  limit  2000
2019-05-09 11:51:12.515 4897-4969/? I/ReactNativeJS: INFO [status-im.mailserver.core:339] - mailserver: messages request success for topic  #{"0x84ba60fa" "0xf8946aac" "0x9624ce9c"} from 1557391563 to 1557391872
2019-05-09 11:51:12.518 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :mailserver.callback/request-success
2019-05-09 11:51:12.706 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:12.708 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"mailserver.request.completed","event":{"requestID":"0xc5fc984ea3ef888a29914eac1748fe4f87221b8c76b5831efdcc5f3e062c4c65","lastEnvelopeHash":"0x1c71a67684095edea22dd6af85f0469446a5b9c204871399ef511a2409af5395","cursor":"","errorMessage":""}}
2019-05-09 11:51:12.724 4897-4969/? I/ReactNativeJS: INFO [status-im.mailserver.core:760] - mailserver: message request  0xc5fc984ea3ef888a29914eac1748fe4f87221b8c76b5831efdcc5f3e062c4c65 completed for mailserver topics #{"0x84ba60fa" "0xf8946aac" "0x9624ce9c"} from 1557391563 to 1557391872
2019-05-09 11:51:12.729 4897-4969/? D/ReactNativeJS: DEBUG [status-im.mailserver.core:416] - Mailserver: planned requests  nil
2019-05-09 11:51:13.007 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :transport/messages-received
2019-05-09 11:51:13.098 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.ui/mainnet-warning-shown
2019-05-09 11:51:14.748 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:14.754 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51784","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","id":"507cbf6d20917b6130d232b6aace3fad3615608ea5a06ec2cb496cfd949b7916","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51152","remoteAddress":"206.189.243.162:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:55992","remoteAddress":"130.211.215.133:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://d85b87dbcd251ca21bdc4085d938e54a9af3538dd6696e2b99ec9c4694bc3eb8c6689d191129f3d9ee67aac8f0174b089143e638369245c88b9b68b9291216ff@35.224.150.136:443","id":"b9a315670f4aa8df31bf7051e34fbb0f5e5845d02a9d8176d65095e8fa439246","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:41354","remoteAddress":"35.224.150.136:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
2019-05-09 11:51:14.802 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:14.804 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://ce559a37a9c344d7109bd4907802dd690008381d51f658c43056ec36ac043338bd92f1ac6043e645b64953b06f27202d679756a9c7cf62fdefa01b2e6ac5098e@206.189.243.179:30305?discport=0","id":"16fc848ef217398e00d82144617c86a2f97b994bacccbbf8cd6e9c8c58615a61","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:36226","remoteAddress":"206.189.243.179:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51784","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","id":"507cbf6d20917b6130d232b6aace3fad3615608ea5a06ec2cb496cfd949b7916","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51152","remoteAddress":"206.189.243.162:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:55992","remoteAddress":"130.211.215.133:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://d85b87dbcd251ca21bdc4085d938e54a9af3538dd6696e2b99ec9c4694bc3eb8c6689d191129f3d9ee67aac8f0174b089143e638369245c88b9b68b9291216ff@35.224.150.136:443","id":"b9a315670f4aa8df31bf7051e34fbb0f5e5845d02a9d8176d65095e8fa439246","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:41354","remoteAddress":"35.224.150.136:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
2019-05-09 11:51:15.151 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:15.153 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://ce559a37a9c344d7109bd4907802dd690008381d51f658c43056ec36ac043338bd92f1ac6043e645b64953b06f27202d679756a9c7cf62fdefa01b2e6ac5098e@206.189.243.179:30305?discport=0","id":"16fc848ef217398e00d82144617c86a2f97b994bacccbbf8cd6e9c8c58615a61","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:36226","remoteAddress":"206.189.243.179:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51784","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","id":"507cbf6d20917b6130d232b6aace3fad3615608ea5a06ec2cb496cfd949b7916","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51152","remoteAddress":"206.189.243.162:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://9c2b82304d988cd78bf290a09b6f81c6ae89e71f9c0f69c41d21bd5cabbd1019522d5d73d7771ea933adf0727de5e847c89e751bd807ba1f7f6fc3a0cd88d997@47.52.91.239:30305?discport=0","id":"8f7e7c599f831d153f5a8ef24a1c5333f4e3320cfa0474be2f64cacc11d29e68","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:60286","remoteAddress":"47.52.91.239:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:55992","remoteAddress":"130.211.215.133:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://d85b87dbcd251ca21bdc4085d938e54a9af3538dd6696e2b99ec9c4694bc3eb8c6689d191129f3d9ee67aac8f0174b089143e638369245c88b9b68b9291216ff@35.224.150.136:443","id":"b9a315670f4aa8df31bf7051e34fbb0f5e5845d02a9d8176d65095e8fa439246","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:41354","remoteAddress":"35.224.150.136:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
2019-05-09 11:51:15.164 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:15.166 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://ce559a37a9c344d7109bd4907802dd690008381d51f658c43056ec36ac043338bd92f1ac6043e645b64953b06f27202d679756a9c7cf62fdefa01b2e6ac5098e@206.189.243.179:30305?discport=0","id":"16fc848ef217398e00d82144617c86a2f97b994bacccbbf8cd6e9c8c58615a61","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:36226","remoteAddress":"206.189.243.179:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51784","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","id":"507cbf6d20917b6130d232b6aace3fad3615608ea5a06ec2cb496cfd949b7916","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:51152","remoteAddress":"206.189.243.162:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:55992","remoteAddress":"130.211.215.133:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://d85b87dbcd251ca21bdc4085d938e54a9af3538dd6696e2b99ec9c4694bc3eb8c6689d191129f3d9ee67aac8f0174b089143e638369245c88b9b68b9291216ff@35.224.150.136:443","id":"b9a315670f4aa8df31bf7051e34fbb0f5e5845d02a9d8176d65095e8fa439246","name":"Statusd/v0.23.0-beta.10/linux-amd64/go1.10.8","caps":["shh/6"],"network":{"localAddress":"192.168.0.105:41354","remoteAddress":"35.224.150.136:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
2019-05-09 11:51:21.510 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :mailserver/check-connection-timeout
2019-05-09 11:51:25.154 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :signals/signal-received
2019-05-09 11:51:25.158 4897-4969/? D/ReactNativeJS: DEBUG [status-im.events:950] - :event-str {"type":"discovery.stopped","event":null}
2019-05-09 11:51:25.160 4897-4969/? D/ReactNativeJS: DEBUG [status-im.signals.core:76] - Event  discovery.stopped  not handled
2019-05-09 11:51:27.264 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:51:27.268 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:51:42.609 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:51:42.614 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:51:58.028 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:51:58.030 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:52:13.249 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:52:13.253 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:52:28.462 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:52:28.466 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:52:43.730 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:52:43.733 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:52:59.091 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:52:59.094 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:53:14.448 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:53:14.451 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:53:29.820 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:53:29.823 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:53:45.197 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:53:45.199 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:54:00.629 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:54:00.632 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:54:15.849 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:54:15.870 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:54:31.228 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:54:31.230 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:54:44.273 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :navigate-to
2019-05-09 11:54:44.279 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :profile-stack nil
2019-05-09 11:54:44.377 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :enter-pin
2019-05-09 11:54:44.391 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-05-09 11:54:44.403 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:73] - :main-component-did-update :enter-pin
2019-05-09 11:54:44.525 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set-once
2019-05-09 11:54:46.948 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:54:46.953 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:55:02.192 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:55:02.195 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:55:17.456 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:55:17.458 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:55:32.668 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:55:32.673 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:55:48.049 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:55:48.052 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:56:03.386 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:56:03.389 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:56:07.708 1161-1161/? V/HwNotificationManagerService: isHwSoundAllow pkg=com.google.android.gm, channelId=^nc_1_mail_anastasiya@status.im, userId=0, cfg=null
2019-05-09 11:56:07.708 1161-1161/? V/HwNotificationManagerService: isHwVibrateAllow pkg=com.google.android.gm, channelId=^nc_1_mail_anastasiya@status.im, userId=0, cfg=null
2019-05-09 11:56:07.716 1161-1161/? V/HwNotificationManagerService: isHwSoundAllow pkg=com.google.android.gm, channelId=^nc_1_mail_anastasiya@status.im, userId=0, cfg=null
2019-05-09 11:56:07.716 1161-1161/? V/HwNotificationManagerService: isHwVibrateAllow pkg=com.google.android.gm, channelId=^nc_1_mail_anastasiya@status.im, userId=0, cfg=null
2019-05-09 11:56:11.571 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.ui/chaos-mode-switched
2019-05-09 11:56:18.798 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:56:18.802 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:56:34.162 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:56:34.164 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:56:49.555 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:56:49.557 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:57:04.868 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:57:04.874 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:57:20.160 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:57:20.163 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:57:35.591 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:57:35.594 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:57:50.734 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/navigate-back-button-clicked
2019-05-09 11:57:50.744 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:86] - :navigate-back
2019-05-09 11:57:50.809 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :network-details
2019-05-09 11:57:50.820 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-05-09 11:57:50.829 4897-4969/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:73] - :main-component-did-update :network-details
2019-05-09 11:57:51.013 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:57:51.015 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:57:51.026 4897-4969/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set-once
2019-05-09 11:58:06.288 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:58:06.293 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
2019-05-09 11:58:21.721 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:247] - Syncing transactions data..
2019-05-09 11:58:21.722 4897-4969/? D/ReactNativeJS: DEBUG [status-im.models.transactions:239] - HTTP GET https://api-ropsten.etherscan.io/api?module=account&action=txlist&address=0x59e6bed76de9bdac4444268a8d5e5014b40426f2&startblock=0&endblock=99999999&sort=desc&apikey=DMSI4UAAKUBVGCDMVP3H2STAMSAUV7BYFI&q=json
```

**Comment by dmitryn** [comment]
@asemiankevich fixed, please check http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190509-201624-ea68c1-pr.apk

**Comment by asemiankevich** [comment]
@dmitryn why android e2e is never built here?

**Comment by dmitryn** [comment]
@asemiankevich it was https://github.com/status-im/status-react/pull/8079#issuecomment-489666034

**Comment by asemiankevich** [comment]
> @asemiankevich it was [#8079 (comment)](https://github.com/status-im/status-react/pull/8079#issuecomment-489666034)

yes and then 3 times failed. i will investigate

**Comment by jakubgs** [comment]
Looks like `FASTLANE_SCRIPT` is empty, but why...

**Comment by jakubgs** [comment]
Testing a fix in: https://ci.status.im/job/status-react/job/combined/job/mobile-android-e2e/500/

**Comment by asemiankevich** [comment]
@dmitryn 

in last build something not working for me still:
- i am asked for PIN when i am logging out
- i am asked for PIN when i change network
- this PIN screen is overlapped with keyboard (this is something weird)

image

**Comment by jakubgs** [comment]
I think this branch should be rebased.

**Comment by jakubgs** [comment]
It's missing this commit: https://github.com/status-im/status-react/commit/cc009a3c2cf41a6a99878d2f9eab7325473b6d3a

**Comment by dmitryn** [comment]
Rebased to current develop

**Comment by asemiankevich** [comment]
in this PR i can:
- send tokens in chat
- send tokens from wallet
- send ETH in chat
- send ETH from wallet
- perform all transactions in simpledapp.eth->transactions

Several things i noticed in this PR is this error, happens when i remove card from the phone when signing of a transaction is in progress (spinner shown). @dmitryn please take a look, probably it could be fixed in https://github.com/status-im/status-react/pull/8099 ? 


image


image

 Also, this PIN screen is now removed upon logout, due to discussion with Dmitry - this looks like bad UX, we need to discuss it more (if this functionality is ever needed).

**Comment by dmitryn** [comment]
>Several things i noticed in this PR is this error, happens when i remove card from the phone when signing of a transaction is in progress (spinner shown). @dmitryn please take a look, probably it could be fixed in #8099 ?

@asemiankevich yes, probably will be fixed there. I'll check
