### PR TITLE
bug #3441 - considering gas costs when validating send transaction ag…

### LINKED ISSUE #3441: Insufficient funds error when sending transaction with low balance
### Description

*Type*: Bug

*Summary*: Insufficient funds error when sending transaction to dApp with low balance. Logged a ticket for AuctionHouse devs https://github.com/dob/auctionhouse/issues/42. The ticket is closed for now. The problem is that gas cost is not considered when showing warnings in wallet

#### Expected behavior
Prevent signing transaction (to dApp or when sending tokens or when sending ETH) if balance is less then required to perform the transaction

#### Actual behavior

image

image

### Reproduction

- Open Status
- Having 0 balance send transaction to Auction house
- Having 0 balance send txn to any contact
- Having 0 balance send tokens to any contact

### Additional Information

* Status version: nightly 253
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3441

### Summary:

Considers estimated gas cost when validating required send transaction cost against the available balance.

### Steps to test:
- Try sending an ETH transaction with amount equal to total balance
- Try sending a token transaction without having any ETH
- Try requesting tokens from Simple Dapp without having any ETH
- Try transacting with any dapp without having any ETH

status: ready

### CODE REVIEW

**Comment by goranjovic** [comment]
Sending available amount of HND without having ETH:

screenshot-2018-07-06_16 41 53 318

Sending more HND than you have:

screenshot-2018-07-06_16 42 05 96

Sending available amount of ETH without having any extra ETH for gas:

screenshot-2018-07-06_16 46 36 79

Sending more ETH than you have:

screenshot-2018-07-06_16 46 41 895

**Review by janherich — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/subs.cljs [hunk 1]
```diff
@@ -75,25 +75,40 @@
                        send-transaction)
                      edit)))
 
+(defn check-sufficient-funds [transaction balance symbol amount]
```
Comment (cammellos) [inline src/status_im/ui/screens/wallet/send/subs.cljs:78]: It'd be good to have some tests for `check-sufficient-funds` & ` check-sufficient-gas` documenting the behavior, `wallet.send/transactions` & `wallet.send/unsigned-transaction` could also be extracted and tested

**Comment by annadanchenko** [comment]
@goranjovic there are at least 2 issues:
### issue 1
if request tokens from test Dapp and having 0 ETH then red error message is shown but `Sign transaction` button is enabled. I would expect that button is disabled

### issue 2
"Not enough ETH for gas" error is not shown if send transaction from Wallet when total fee + amount > available funds and funds are not zero and amount != funds 
see from 00:40 https://app.testfairy.com/projects/4803622-status/builds/8518521/sessions/4395906465/?accessToken=1zP7JLaGyQ7tPUqo16VOzhpIlK0
For example:
total fee = 0.000000021 ETH (gas price 0.001 Gwei and limit 21000)
amount = 0.09999999 ETH
(fee + amount = 0.100000011)
available funds = 0.1 ETH
Currently, no warning is shown. I would expect same warning shown "Not enough ETH for gas" and Sign Transaction button to be disabled (as if I would send amount of 0.1 ETH when having only 0.1 ETH available funds).

**Comment by goranjovic** [comment]
@annadanchenko pushed the fix for both issues

**Comment by annadanchenko** [comment]
Please ignore this comment
I could reproduce issue 3 on new nightly and on yesterday's nightly too, so it's not introduced in this PR and I made a mistake when reproducing it yesterday. Reported in #5131

Ignore text below:
on new build with fixes there is new issue:

### issue 3
"Error: Doesn't support name" if try to send tx from Dapp when not enough funds and then open Wallet.
Can't reproduce on nightly build from this morning 
happens on iOS and Android
Steps:
https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4396006482/?accessToken=-k29U03VA5vrIlYq8g-7i-Yvs9g
1. Install app
2. create new account and switch to ropsten
3. open Test Dapp and request STT -> Send transaction screen is shown with "Insufficient funds" error (expected)
4. close  Send transaction screen and close Dapp
5. tap on Wallet tab
6. confirm that you wrote down sign in phrase and proceed to wallet -> currently error is shown. if close it then white screen so need to restart app
```
00:57 E/ReactNativeJS: Error: Doesn't support name: 
00:57 E/ReactNativeJS: 
00:57 E/ReactNativeJS: This error is located at:
00:57 E/ReactNativeJS:     in asset-selector
00:57 E/ReactNativeJS:     in reagent97
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTScrollView
00:57 E/ReactNativeJS:     in ScrollView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in reagent4
00:57 E/ReactNativeJS:     in reagent93
00:57 E/ReactNativeJS:     in reagent92
00:57 E/ReactNativeJS:     in send-transaction
00:57 E/ReactNativeJS:     in reagent116
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in main
00:57 E/ReactNativeJS:     in root
00:57 E/ReactNativeJS:     in reagent1
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in RCTView
00:57 E/ReactNativeJS:     in t
00:57 I/ReactNativeJS: PRETTY PRINTED EXCEPTION
```

**Comment by annadanchenko** [comment]
I could reproduce issue 3 on new nightly and on yesterday's nightly too, so it's not introduced in this PR and I made a mistake when reproducing it yesterday. Reported in https://github.com/status-im/status-react/issues/5131 
So will continue to test this PR

**Comment by annadanchenko** [comment]
@goranjovic 
issue 1 is fixed (if request tokens from test Dapp and having 0 ETH then red error message is shown but Sign transaction button is enabled. I would expect that button is disabled)

issue 2 still occurs but for other amounts than initially described. 
Amounts that produce issue on new build:
funds available:       0.59999999999777 ETH
amount to be sent: 0.599978999997770048 ETH
total fee:                  0.000021 (limit 21000 and gas price 1 Gwei)
https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4396084393/?accessToken=KXOis6Y0dMoDuuOC0rKI1Fydbnc

Currently: no error "Not enough ETH for gas". if try to send amount then get popup Transaction failed
Expected: error "Not enough ETH for gas" and button Sign transaction is disabled

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8519836/sessions/4396084393/?accessToken=KXOis6Y0dMoDuuOC0rKI1Fydbnc">TestFairy: Status 0.9.21 (6186) @2018</a></strong></div></blockquote>

**Comment by goranjovic** [comment]
@annadanchenko On it

**Comment by goranjovic** [comment]
@annadanchenko This one was a rounding error, just pushed the fix.

**Comment by annadanchenko** [comment]
@goranjovic issue 2 is fixed in new build

### issue 4
Sign transaction button is disabled if Deploy contract from Test Dapp when having exact amount that is needed to pay fee. 
Amount: 0.000000000000130627 ETH
Fee:  0.000000000000130627 (limit = 130627, gas price = 0.000000001 Gwei)
TF video/log: https://app.testfairy.com/projects/4803590-status/builds/8521431/sessions/4396112499/?accessToken=mPYNyevZIUSPD7BqgtaC3L/b2iI

Steps:
1. your wallet should have exactly 0.000000000000130627 ETH
2. Open DApp -> Test Dapp -> Transactions -> Deploy simple contract
3. In Sign Transaction screen -> Advanced -> Gas price change value to 0.000000001 Gwei. Gas limit should be 130627
4. On Send transaction screen check if Sign Transaction button is enabled and that there is no error "not enough ETH for gas" (it's expected state) Currently wrong state is that Sign Transaction button is disabled
Notes:
- Found issue on iOS (didn't check on Android)
- In nightly build from today this issue does not happen - can set such values and Sign transactions for same steps

issue:



<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8521431/sessions/4396112499/?accessToken=mPYNyevZIUSPD7BqgtaC3L/b2iI">TestFairy: Status 0.9.23 (6192) @2018</a></strong></div></blockquote>

**Comment by goranjovic** [comment]
@annadanchenko pushed the new fix for the contract deployment issue

**Comment by annadanchenko** [comment]
@goranjovic please, update CHANGELOG.md and it's ok to merge after this

**Comment by goranjovic** [comment]
@annadanchenko updated changelog. merging
