### PR TITLE
fix status bar font color

### LINKED ISSUE #15742: White status bar font on certain screens in light mode
# Bug Report

## Problem 

On almost all screens of the app, except for the home screen, the status bar is invisible in a light theme.

https://user-images.githubusercontent.com/67952253/234339609-450be693-759e-4c45-89e1-4ab30a3e7e51.mp4

### Reproduction

1. Open Status
2. Start opening different screens: community, channel, chats, profile, etc

### Additional Information

- Status version: nightly 25/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/15742

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

File: src/quo2/components/inputs/title_input/style.cljs [hunk 1]
```diff
@@ -30,7 +30,7 @@
   [customization-color blur? override-theme]
   (if blur?
     (colors/theme-colors colors/neutral-100 colors/white override-theme)
-    (colors/custom-color customization-color (if (or (= :dark override-theme) colors/dark?) 60 50))))
+    (colors/custom-color customization-color (if (or (= :dark override-theme) (colors/dark?)) 60 50))))
```
Comment (J-Son89) [inline src/quo2/components/inputs/title_input/style.cljs:33]: maybe custom `color-by-theme` (in foundations/colors) should also include an override theme param?

**Review by J-Son89 — APPROVED** [review]

**Comment by qoqobolo** [comment]
@Parveshdhull thank you very much for another fix!
The e2e failures are not related to the PR, it can be merged.
