### PR TITLE
Fix contract call for communities

### LINKED ISSUE #17069: Discover communities are not fetched
This bug is not in our develop yet, but it is in status-go branch. 

We are facing the issue in couple of our PRs that are not merged yet but have changes in go

https://github.com/status-im/status-mobile/pull/17034
https://github.com/status-im/status-mobile/pull/17042

We need to wait with merging of those PRs until this bug is fixed in status go. @cammellos is already looking at it. 

**Steps:** 

1. Login multiaccount
2. Open Discover communities screen
3. See if communities are fetched

**Actual result:** communities are not fetched

[Status-debug-logs (53).zip](https://github.com/status-im/status-mobile/files/12397216/Status-debug-logs.53.zip)

https://github.com/status-im/status-mobile/assets/97245802/5706f196-ca15-45cd-8fb5-0a9f9f79e087

**Expected result:** communities are fetched

- Status version: develop 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #17114: App can be crashed after account creation
# Bug Report

## Problem 
The app can be crashed from time to time after account creation, this can be caught by e2e

NOTE: reproduced not that often as https://github.com/status-im/status-mobile/issues/16560 so supposedly another issue

#### Expected behavior
no crash

#### Actual behavior
Session: https://app.eu-central-1.saucelabs.com/tests/3c7924f0fb5b43bcb186349019909e3b?auth=1437d1dc137f19439be711ef24141c13#24

https://github.com/status-im/status-mobile/assets/4557972/8f6ff159-70d8-408d-863e-f8bc1936a50c

### Reproduction

1. Create profile

### Additional Information

- Status version: nightly 
- Operating System: Android
- Logcat:  [logcat (16).log](https://github.com/status-im/status-mobile/files/12440352/logcat.16.log)

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #17069
Fixes: #17114 

https://github.com/status-im/status-go/pull/3938

### CODE REVIEW

File: src/status_im2/contexts/communities/discover/events.cljs [hunk 1]
```diff
@@ -37,6 +37,7 @@
                  :other    (select-keys (:communities cc) other)})}))
 
 (rf/defn fetch-contract-communities
+  {:events [:fetch-contract-communities]}
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/discover/events.cljs:40]: curious, how was this even called before without an event name? 🤔

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 2]
```diff
@@ -243,9 +243,13 @@
 
 (defn discover
   []
-  (let [featured-communities (rf/sub [:communities/featured-contract-communities])]
-    [rn/view
-     {:style (style/discover-screen-container (colors/theme-colors
-                                               colors/white
-                                               colors/neutral-95))}
-     [discover-screen-content featured-communities]]))
+  (reagent/create-class
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/discover/view.cljs]: should we move away from the class components?
we could use reagent/with-let perhaps? (not 100% about this)
or a functional component with use-effect

https://reagent-project.github.io/docs/master/reagent.core.html#var-with-let
cc @ulisesmac

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/contexts/communities/discover/events.cljs (hunk 1 above)
Comment (cammellos) [reply src/status_im2/contexts/communities/discover/events.cljs:40]: It wasn't, but communities were retrieved every 10s I believe (seems to often to be honest), but I think it still best for UX to retrieve them on landing on the page, just in case

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im2/contexts/communities/discover/view.cljs]: Updated to use `use-effect`, how does it look now?

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 3]
```diff
@@ -243,9 +243,16 @@
 
 (defn discover
   []
-  (let [featured-communities (rf/sub [:communities/featured-contract-communities])]
-    [rn/view
-     {:style (style/discover-screen-container (colors/theme-colors
-                                               colors/white
-                                               colors/neutral-95))}
-     [discover-screen-content featured-communities]]))
+  [:f>
```
Comment (J-Son89) [inline src/status_im2/contexts/communities/discover/view.cljs]: I think we run into some performance issues doing this.

I think you have to do
```
(defn f-discover []
(fn []
 (rn/use-effect ...
```

```
(defn discover []
 [:f> f-discover]
```

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 2 above)
Comment (J-Son89) [reply src/status_im2/contexts/communities/discover/view.cljs]: nice!

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 3 above)
Comment (cammellos) [reply src/status_im2/contexts/communities/discover/view.cljs]: done, thank you!

**Comment by pavloburykh** [comment]
@cammellos thanx for the fix! 

Could you please clarify is the following behaviour is expected? Looks like a bug. 

### ISSUE 1 All communities are displayed as token gated

All communities (including communities from Discover communities page or newly created) are displayed as token gated. The UI flow of joining these communities is different from non-token gated. It causes all of community e2e to fail. 

**Steps:** 
1. Navigate to Discover communities page
2. Proceed with joining the community

**Actual result:** 

https://github.com/status-im/status-mobile/assets/97245802/e2aa7e78-06c3-4bd4-af3c-3e308294b182

**Expected result:** what we have in develop

https://github.com/status-im/status-mobile/assets/97245802/435d827f-f0c3-4595-9d73-a94f266570ff

**Comment by cammellos** [comment]
@pavloburykh 
Yes and no , I have just clarified the behavior with John

So from now on, any community, even if it's not token gated, will require the flow where a password is asked, so e2e tests will need to be changed as the behavior of the PR is correct (to always ask for the user password).

The communties though that are not actually token gated, should not be showing a `lock` icon (I can address it in this PR).

Does it answer your concern?

**Comment by pavloburykh** [comment]
> Does it answer your concern?

Yes, thanx for clarification @cammellos!

A few other points: 

1. As far as I understand we also need to fix "Join community" block on Home page of non-token gated communities, as they should be different and not include this text "You are eligible to join, you hold 0 of these". Correct me please if I am wrong. 

photo_2023-08-23 18 13 48

2. Would be great if designs will be updated. Maybe you have same info about this or should I ping design team? 
Because now it is unclear for me: do we need to show Community rules bottom sheet while joining or not? In current PR flow we do not show it. At the same time Figma designs include this bottom sheet BUT does not include a step with password. So now it is little bit confusing how flow should look like. 

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1424-116755&mode=design&t=pxbXwiVgpMEA1USf-0

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 4]
```diff
@@ -241,11 +228,21 @@
...
+
 (defn discover
   []
-  (let [featured-communities (rf/sub [:communities/featured-contract-communities])]
-    [rn/view
-     {:style (style/discover-screen-container (colors/theme-colors
-                                               colors/white
-                                               colors/neutral-95))}
-     [discover-screen-content featured-communities]]))
+  [:f> f-discover])
```
Comment (ulisesmac) [inline src/status_im2/contexts/communities/discover/view.cljs]: @cammellos @J-Son89 
My opinion on this:

- `f-discover` is a form-2 component, but it's not required if we are already using use-effect.
- the `use-effect` call will be only executed on mount and unmount, but we are not performing cleaning, so we only care about mount and I think it can be avoided.
- So that it's not required to be a functional component.

So I'd suggest doing this:
```clojure
(defn discover
  []
  (let [_ (rf/dispatch [:fetch-contract-communities])] ; Executed only once when the component is mounted
    (fn []
      (let [featured-communities (rf/sub [:communities/featured-contract-communities])]
        [rn/view
         {:style (style/discover-screen-container (colors/theme-colors
                                                   colors/white
                                                   colors/neutral-95))}
         [discover-screen-content featured-communities]]))))
```

(it'd be almost the same as using `reagent/with-let`)

Also, that `let` is not required, the component could look as follows:
```clojure
(defn discover
  []
  (rf/dispatch [:fetch-contract-communities]) ; The same as before, but without let
  (fn []
    (let [featured-communities (rf/sub [:communities/featured-contract-communities])]
      [rn/view
       {:style (style/discover-screen-container (colors/theme-colors
                                                 colors/white
                                                 colors/neutral-95))}
       [discover-screen-content featured-communities]])))
```

But this might break the form-2 mental model for other devs :thinking:, we could add an unused binding name (a var name starting with `_`), our linter is aware of this, so we won't get any warning:

```clojure
;; Ignored let binding:
(let [_fetch-communities (rf/dispatch [:fetch-contract-communities])]
  (fn [] ,,,))

```

Feel free to take any of those, I just think the current code looks a little more complex than needed :sweat_smile:

File: src/status_im2/contexts/communities/actions/request_to_join/view.cljs [hunk 5]
```diff
@@ -3,31 +3,35 @@
...
-            [utils.requests :as requests]))
+            [utils.re-frame :as rf]))
 
 (defn request-to-join-text
   [open?]
   (if open?
     (i18n/label :t/join-open-community)
     (i18n/label :t/request-to-join)))
 
+(defn join-community-and-navigate-back!
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/actions/request_to_join/view.cljs]: just wondering why it has `!` mark in the end

File: src/status_im2/contexts/communities/actions/request_to_join/view.cljs [hunk 6]
```diff
@@ -65,16 +69,7 @@
...
-                                       (do
-                                         (rf/dispatch [:communities/request-to-join id])
-                                         (rf/dispatch [:navigate-back]))
-                                       (do (and can-request-access?
-                                                (not pending?)
-                                                (requests/can-request-access-again?
-                                                 requested-to-join-at))
-                                           (rf/dispatch [:communities/request-to-join id])
-                                           (rf/dispatch [:navigate-back]))))
+                                     (join-community-and-navigate-back! id))
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/actions/request_to_join/view.cljs]: with could be `#()`

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 7]
```diff
@@ -241,11 +228,21 @@
         featured-communities
         @view-type]])))
 
+(defn f-discover
+  []
+  (fn []
+    (rn/use-effect
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: it's better to avoid using effects and f component, and just dispatch outside render function

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/contexts/communities/actions/request_to_join/view.cljs (hunk 5 above)
Comment (cammellos) [reply src/status_im2/contexts/communities/actions/request_to_join/view.cljs]: habit, I use it for functions that have side effects, clojure recommends it for state changing functions (`reset!` etc), but not sure we do that throughout the codebase, so I'll change it

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 4 above)
Comment (cammellos) [reply src/status_im2/contexts/communities/discover/view.cljs]: no strong opinion on my side, I'll go with the team convention, thanks!

**Comment by churik** [comment]
@cammellos 
can we rebase status-go one more time, as I have a suspicion that again in develop something has been changed, as in PR https://github.com/status-im/status-mobile/pull/17034 the "Join" page for open communities looks like:
IMAGE 2023-08-24 11:29:37

**Comment by cammellos** [comment]
@churik updated status-go!

**Comment by churik** [comment]
@cammellos 
### ISSUE 2: request to join the closed community is not received
**Prerequisites:**
user 1 and 2 are contacts
**Steps:**
1) device 1: create closed community 
2) device 1: share closed community with user 2
3) device 2: tap on community invitation > request to join closed community 
4) device 1: wait for request

**Expected result:**
can see the request to join a closed community

**Actual result:**
No request is received

**OS:** IOS, Android

**Logs:** 
[logs (54).zip](https://github.com/status-im/status-mobile/files/12430232/logs.54.zip)

**IMPORTANT NOTE:**
I suppose issue is already in status-go, as it can be reproduced on rebased version in this [PR](https://github.com/status-im/status-mobile/pull/17034)

**Comment by churik** [comment]
@cammellos 
### ISSUE3: in ~40% of cases got a crash when received a request to join the closed community.

**Prerequisites:**
user 1 and 2 are contacts
**Steps:**
1) device 1: create closed community 
2) device 1: share closed community with user 2
3) device 2: tap on community invitation > request to join closed community 
4) device 1: wait for request

**Expected result:**
can see the request to join a closed community

**Actual result:**
sometimes app crashed on device 1

**OS:** IOS, Android


**Logs:** [logs (55).zip](https://github.com/status-im/status-mobile/files/12437459/logs.55.zip)

Please, let me know if it might be related to your PR. 
Also, I noticed that the app crashes from time to time (but rarely) on receiving CR (in case it might be important)

**Comment by cammellos** [comment]
@churik do you have the raw logcat? nothing on the logs you posted unfortunately

**Comment by churik** [comment]
I'll try to reproduce it and let you know, anyway I should at least find out whether the issue is reproducible on nightly or if it is something new.

**Comment by churik** [comment]
So currently messages stopped being sent from my deviceA (Android) to deviceB(IOS):
none of the messages sent 14:00-14:17 - waited until 14:30 - no messages received.
Raw logcat of sender (Android, deviceA): 
[logcat_andr copy.txt](https://github.com/status-im/status-mobile/files/12439032/logcat_andr.copy.txt)

[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12439213/Status-debug-logs.zip)

Receiver(IOS): [logs (56).zip](https://github.com/status-im/status-mobile/files/12439060/logs.56.zip)

However, I can receive messages fine from deviceA to current desktop master.

Unfortunately, it blocks PR testing for now.

**Comment by cammellos** [comment]
Investigating the message sent:
```
t=2023-08-25T12:18:46+0000 lvl=dbug msg="Served wakuext_sendChatMessages" reqid=160 duration=16.484823ms
```

The id is:

```
t=2023-08-25T12:18:46+0000 lvl=dbug msg="sent message" id=0xa7085bc7667d03ba1a9cdc47806fcd2392b81463e48473b2bec172b72b42215d
```
Hashes are:

```
t=2023-08-25T12:18:47+0000 lvl=dbug msg="sent private messages" messageIDs=[0xa7085bc7667d03ba1a9cdc47806fcd2392b81463e48473b2bec172b72b42215d] hash=0x745102d76957f5388066dd236e5bf47eb1e402ad111840854cc3b6d8a04c2741
```

```
t=2023-08-25T12:19:16+0000 lvl=dbug msg="sent private messages" messageIDs=[0xa7085bc7667d03ba1a9cdc47806fcd2392b81463e48473b2bec172b72b42215d] hash=0xfef15e5ad2b612cf14f8b6467874ec97fe8d6785c8b8e285df4ca42ef46e207f
```

```
t=2023-08-25T12:20:19+0000 lvl=dbug msg="sent private messages" messageIDs=[0xa7085bc7667d03ba1a9cdc47806fcd2392b81463e48473b2bec172b72b42215d] hash=0xbc9453aa3a9df86f4a61f5e3a0b6e3a5eb753ada2f982f1a412a812bdfa91134
```

```
t=2023-08-25T12:22:16+0000 lvl=dbug msg="sent private messages" messageIDs=[0xa7085bc7667d03ba1a9cdc47806fcd2392b81463e48473b2bec172b72b42215d] hash=0x6c02ce323217a55eeecfce96f57260fe58efc9536c44d9d0ec3dcb614e08984e
```

**Comment by cammellos** [comment]
And they made it to the fleet:

```
docker.log:2023-08-25T12:18:46.259151+00:00 docker/nim-waku[865]: TRC 2023-08-25 12:18:46.258+00:00 waku.relay received                        topics="waku node" tid=1 file=waku_node.nim:239 peerId=16U*TCnsXV pubsubTopic=/waku/2/default-waku/proto hash=0x745102d76957f5388066dd236e5bf47eb1e402ad111840854cc3b6d8a04c2741 receivedTime=1692965926258642688 payloadSizeBytes=1052

docker.log:2023-08-25T12:19:15.814412+00:00 docker/nim-waku[865]: TRC 2023-08-25 12:19:15.814+00:00 waku.relay received                        topics="waku node" tid=1 file=waku_node.nim:239 peerId=16U*TCnsXV pubsubTopic=/waku/2/default-waku/proto hash=0xfef15e5ad2b612cf14f8b6467874ec97fe8d6785c8b8e285df4ca42ef46e207f receivedTime=1692965955814055168 payloadSizeBytes=1052

docker.log:2023-08-25T12:20:19.370431+00:00 docker/nim-waku[865]: TRC 2023-08-25 12:20:19.370+00:00 waku.relay received                        topics="waku node" tid=1 file=waku_node.nim:239 peerId=16U*TCnsXV pubsubTopic=/waku/2/default-waku/proto hash=0xbc9453aa3a9df86f4a61f5e3a0b6e3a5eb753ada2f982f1a412a812bdfa91134 receivedTime=1692966019370114560 payloadSizeBytes=1052

docker.log:2023-08-25T12:22:15.025792+00:00 docker/nim-waku[865]: TRC 2023-08-25 12:22:15.025+00:00 waku.relay received                        topics="waku node" tid=1 file=waku_node.nim:239 peerId=16U*TCnsXV pubsubTopic=/waku/2/default-waku/proto hash=0x6c02ce323217a55eeecfce96f57260fe58efc9536c44d9d0ec3dcb614e08984e receivedTime=1692966135025437952 payloadSizeBytes=1052
docker.log:2023-08-25T12:34:21.430123+00:00 docker/nim-waku[865]: TRC 2023-08-25 12:34:21.429+00:00 waku.relay received                        topics="waku node" tid=1 file=waku_node.nim:239 peerId=16U*TCnsXV pubsubTopic=/waku/2/default-waku/proto hash=0x6c02ce323217a55eeecfce96f57260fe58efc9536c44d9d0ec3dcb614e08984e receivedTime=1692966861429923584 payloadSizeBytes=1052
```

So they all made it to the fleet

**Comment by cammellos** [comment]
One thing from the receiver side's logs is that push messages didn't arrive:

The last log for a push message:
```
t=2023-08-25T12:07:29+0000 lvl=info msg="received message push" peer=16Uiu2HAmHzE3iVroJsngqwtY3aRQsDUGiUtXLbT4L9ANbbb6s47A
```

which is around 10 minutes before the message that we are looking for
Peer connectivity was always ok in that timeframe

**Comment by cammellos** [comment]
The message was finally received from store:

```
t=2023-08-25T14:23:53+0000 lvl=info msg="received waku2 store message" envelopeHash=0xfef15e5ad2b612cf14f8b6467874ec97fe8d6785c8b8e285df4ca42ef46e207f pubsubTopic=/waku/2/default-waku/proto
```
After a login/logout

So conclusion is clear it seems, the message wasn't pushed onto the receiver I believe, we could look for more logs if any error etc, but not quite sure what's available.

cc @richard-ramos @jm-clius @siphiuel

**Comment by richard-ramos** [comment]
Let's see kibana for the receiver peerID
https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h%2Fh,to:now))&_a=(columns:!(),filters:!(),index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'16Uiu2HAmED5Nop5jJdQSyniCv7mqxuqKw56cCsXcBbG2abTWzjrw'),sort:!(!('@timestamp',desc)))

**Comment by cammellos** [comment]
https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-25T13:15:00.000Z',to:'2023-08-25T15:02:17.146Z'))&_a=(columns:!(),filters:!(),index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'16Uiu2HAmVUPr6ZYDtXJsinn6SwgV2ns9E8Pa7c13zWzwkgUTpk4P'),sort:!(!('@timestamp',desc))) 

I believe this is the logs for the receiver

**Comment by richard-ramos** [comment]
image
I noticed a lot of logs to go-waku filter nodes with empty requestID, so i fixed it in this PR https://github.com/waku-org/go-waku/pull/686

**Comment by richard-ramos** [comment]
Looking at the logs, I do see the following:
image
go-waku filter node does timeout after 20s while attempting to push a message, and it this happens it will not retry sending the message. This behavior is shared both by go-waku and nwaku.

**Comment by churik** [comment]
@cammellos 
### ISSUE 4: crash when received membership request for token-gated community
**Steps:**

1) UserA: created token-gated community (used menu in mobile > Create token-gated community)
2) UserB (has to be eligible to join): request access


**Expected result:**
no crash

**Actual result:**
app on UserA device crashed
**Logcat UserA:** [logcat_andr_28.txt](https://github.com/status-im/status-mobile/files/12452889/logcat_andr_28.txt)

**OS:** Android
**Note:** after the crash can log in and approve membership request

**Comment by churik** [comment]
@cammellos works fine with 3 types of communities, created on mobile, and has an issue with `Request to join` community created on desktop (will be reported separately, will link to this issue)
Meanwhile we are trying to deal with e2e.


Also found a difference in token-gated communities - in contrast to non-token gated they do not have join community rules to accept (so the screen below is missing)
photo_2023-08-28 15 31 55
is it expected?

**Comment by cammellos** [comment]
@churik I don't think so, is it ok if we track separately?

**Comment by churik** [comment]
@cammellos yes, so far one issue for desktop and several for token-gated community. But there is one more issue (I think we need to fix it here) 

### ISSUE 6: can't see communities in `Discover` (IOS only)


https://github.com/status-im/status-mobile/assets/4557972/691119cb-00b8-4e36-afbb-ba93809a193e

**Comment by churik** [comment]
@cammellos issue with[ lost messag](https://github.com/status-im/status-mobile/pull/17091#issuecomment-1693280668)e should I track separately?

**Comment by cammellos** [comment]
> @cammellos issue with[ lost messag](https://github.com/status-im/status-mobile/pull/17091#issuecomment-1693280668)e should I track separately?

Yes, please, as it's not due to this commit

**Comment by churik** [comment]
Don't think it makes sense to report issues related to token-gated communities, as it should be aligned anyway to the next desktop version, as it was discussed - so waiting for e2e results and ready to be merged. 

Thank you for your collaboration @cammellos, it was a tough one

**Comment by churik** [comment]
@cammellos 
Unfortunately, tests caught one more possible crash after creating the account, sharing the logs below

Video: https://app.eu-central-1.saucelabs.com/tests/c946d401e6a740a19a8973b53860aaf2?auth=3b5387df568d714e10fa7eb7cd50d643#26

Logcat: 
[logcat (18).log](https://github.com/status-im/status-mobile/files/12456796/logcat.18.log)

Geth: 
[TestGroupChatMultipleDeviceMergedNewUI_geth1.log](https://github.com/status-im/status-mobile/files/12456800/TestGroupChatMultipleDeviceMergedNewUI_geth1.log)

**Comment by cammellos** [comment]
> @cammellos Unfortunately, tests caught one more possible crash after creating the account, sharing the logs below
> 
> Video: https://app.eu-central-1.saucelabs.com/tests/c946d401e6a740a19a8973b53860aaf2?auth=3b5387df568d714e10fa7eb7cd50d643#26
> 
> Logcat: [logcat (18).log](https://github.com/status-im/status-mobile/files/12456796/logcat.18.log)
> 
> Geth: [TestGroupChatMultipleDeviceMergedNewUI_geth1.log](https://github.com/status-im/status-mobile/files/12456800/TestGroupChatMultipleDeviceMergedNewUI_geth1.log)

@churik this should be fixed in the next build 
https://github.com/waku-org/go-waku/pull/691#issuecomment-1696095479 go-waku PR

could you please re-run the tests?

Thank you!

**Comment by churik** [comment]
@cammellos 
No more issues related to PR are found, and tests are partially fixed here: https://github.com/status-im/status-mobile/pull/17132, other issues are not related to changed workflow.
