### PR TITLE
Optimize chat screen navigation view

### LINKED ISSUE #17615: Muted colors of composer elements after reopening the chat
# Bug Report

## Problem 

**Steps to reproduce:**
1. Open chat
2. Enter some text to the composer
3. Close the chat
4. Open the chat

Screenshot 2023-10-11 at 18 32 20

https://github.com/status-im/status-mobile/assets/67952253/9974e8dd-5bce-43be-a68a-cc2cb0ebd286

#### Expected behavior
The colors remain vibrant, just as when the composer is simply collapsed

Screenshot 2023-10-11 at 18 44 35

https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=3758-783091&mode=design&t=v5laTH80ElB1Slcg-4

#### Actual behavior
Colors are muted

### Additional Information

- Status version: nightly 11/10
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
### Summary

required for https://github.com/status-im/status-mobile/pull/17839

This PR mostly focusing on the optimization of the chat screen navigation view. PR Simplifies implementation of navigation view, removes redundant wrappers, reagent atoms, IOS-specific hardcodings, etc.

leftovers: https://github.com/status-im/status-mobile/issues/18132

### Testing
- I have included leftover regressions etc. in the above issue, if I have missed any please let me know.
- PR also fixes https://github.com/status-im/status-mobile/issues/17615
- Please also test: https://github.com/status-im/status-mobile/pull/17785
- Theme related regressions
- Top Bar related regressions

Please also let me know how(if) PR effects performance of chat screen.

status: ready

### CODE REVIEW

File: src/js/worklets/chat/messages.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+      'top-bar-height': topBarHeight,
+      'navigation-view-height': navigationViewHeight,
+      'all-loaded?': isAllLoaded,
+    } = props;
+
+    if (isAllLoaded.value) {
+      return interpolate(
+        distanceFromListTop.value,
+        // add todo
+        [navigationViewHeight + 142, navigationViewHeight + 142 + topBarHeight],
```
Comment (Parveshdhull) [inline src/js/worklets/chat/messages.js]: 142 - Position of pinned banner for starting animation (currently decided as per hit and trial)
exact position needs to confirmed with design team ([logged](https://github.com/status-im/status-mobile/issues/18132))

File: src/status_im2/contexts/chat/messages/view.cljs [hunk 2]
```diff
@@ -1,106 +1,56 @@
...
-                                   :else (str emoji chat-name))
-        online?                  (rf/sub [:visibility-status-updates/online? chat-id])
-        photo-path               (rf/sub [:chats/photo-path chat-id])
-        back-icon                (if (= chat-type constants/one-to-one-chat-type)
-                                   :i/close
-                                   :i/arrow-left)
-        {:keys [focused?]}       (rf/sub [:chats/current-chat-input])]
+  []
+  (let [insets (safe-area/get-insets)
+        show-floating-scroll-down-button? (reagent/atom false)
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/view.cljs:23]: todo - get rid of remaining reagent atoms ([logged](https://github.com/status-im/status-mobile/issues/18132))

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 3]
```diff
@@ -325,7 +300,7 @@
        :footer                            [list-footer
                                            {:theme                       theme
                                             :chat                        chat
-                                            :scroll-y                    scroll-y
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: `scroll-y` is misleading (y position of flat list tells currently scrolled position of flat list, but we are treating it as distance-from-top)
(needs to be renamed in all files) ([logged](https://github.com/status-im/status-mobile/issues/18132))

File: src/status_im2/contexts/chat/messages/view.cljs [hunk 4]
```diff
@@ -1,106 +1,56 @@
...
+       :scroll-y          distance-from-list-top
+       :cover-bg-color    :turquoise
+       :big-name-visible? big-name-visible?
+       :inner-state-atoms inner-state-atoms}]
 
-     (when (seq chat)
-       (if able-to-send-message?
-         [:f> composer.view/composer
-          {:insets                            insets
-           :scroll-to-bottom-fn               list.view/scroll-to-bottom
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/view.cljs:93]: `scroll-to-botom-fn` needs improvement (probably should be an event)

File: src/status_im2/contexts/chat/messages/constants.cljs [hunk 5]
```diff
@@ -0,0 +1,10 @@
+(ns status-im2.contexts.chat.messages.constants)
+
+(def ^:const top-bar-height 56)
+(def ^:const pinned-banner-height 40)
+
+(def ^:const header-container-top-margin 52) ;; Design bug (48 or 52)?
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/constants.cljs]: confirm with design team ([logged](https://github.com/status-im/status-mobile/issues/18132))

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 6]
```diff
@@ -277,42 +261,33 @@
        [message/message message-data context keyboard-shown?])]))
 
 (defn scroll-handler
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: todo - use `animatedScrollHandler`

File: src/js/worklets/chat/messages.js (hunk 1 above)
Comment (flexsurfer) [reply src/js/worklets/chat/messages.js]: could you add this comment to the code?

File: src/js/worklets/chat/messages.js [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+      'distance-from-list-top': distanceFromListTop,
+      'top-bar-height': topBarHeight,
+      'navigation-view-height': navigationViewHeight,
+      'all-loaded?': isAllLoaded,
+    } = props;
+
+    if (isAllLoaded.value) {
+      return interpolate(
+        distanceFromListTop.value,
+        // add todo
```
Comment (flexsurfer) [inline src/js/worklets/chat/messages.js]: leftover?

File: src/status_im2/contexts/chat/composer/utils.cljs [hunk 8]
```diff
@@ -197,21 +197,15 @@
...
-         {:images               (seq (rf/sub [:chats/sending-image]))
-          :link-previews?       (rf/sub [:chats/link-previews?])
-          :audio                (rf/sub [:chats/sending-audio])
-          :reply                (rf/sub [:chats/reply-message])
-          :edit                 (rf/sub [:chats/edit-message])
-          :input-with-mentions  (rf/sub [:chat/input-with-mentions])
-          :input-text           (:input-text chat-input)
-          :input-content-height (:input-content-height chat-input)
-          :chat-screen-loaded?  chat-screen-loaded?})))))
+  (let [chat-input (rf/sub [:chats/current-chat-input])]
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/composer/utils.cljs:200]: i feel like it should be one subscription

Comment (flexsurfer) [reply src/status_im2/contexts/chat/composer/utils.cljs:200]: like chat/props

File: src/status_im2/contexts/chat/composer/view.cljs [hunk 9]
```diff
@@ -35,8 +36,7 @@
            background-y
            theme
            messages-list-on-layout-finished?]} props state]
-  (let [{:keys [chat-screen-loaded?]
-         :as   subscriptions}    (utils/init-subs)
+  (let [subscriptions            (utils/init-subs)
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/composer/view.cljs:41]: so here will be `props (rf/sub [:chat/props]`

**Review by flexsurfer — APPROVED** [review]
thank you! 🚀

**Comment by clauxx** [comment]
I want to check the chat behaviour, but getting an error when trying to open a chat 
```
 TypeError: null is not an object (evaluating 'sharedValue.value')

This error is located at:
    in status_im2.contexts.chat.messages.list.view.f_list_footer
    in RCTView (at View.js:32)
    in View (created by status_im2.contexts.chat.messages.list.view.list_footer)
```
Does it work for you?

**Comment by Parveshdhull** [comment]
> Does it work for you?

Hi, Thank you for checking PR. Please check latest build. In the last commit I forget to rename a key (should be fixed now)

File: src/status_im2/contexts/chat/composer/utils.cljs (hunk 8 above)
Comment (Parveshdhull) [reply src/status_im2/contexts/chat/composer/utils.cljs:200]: [logged](https://github.com/status-im/status-mobile/issues/18137), thank you.

**Comment by clauxx** [comment]
Hey @Parveshdhull, found some issues on iOS (didn't test on android).

Also, given this is a big refactor here and it has a few regressions, I'd suggest to merge the chat fixes from #18059 first, as most of the changes are happening in the `...messages.list.view` ns, and here this ns has only a rename from what I see. Also, the design changes have the `medium-priority` tag, so I wouldn't want to keep it for longer collecting conflicts.

Also, maybe it makes sense to have a chat crew if we plan on working on chat fixes in future issues, if you plan to continue working on the chat, as I have other issues there as well. Might make it easier to avoid conflicts in the future.

1. The header has a weird positioning when the contact is not a "friend" anymore
2. The content & composer isn't moved up when the keyboard is focused
3. From the design animation I think the header blur should animate "instantly", so that in the case from the screenshot, the avatar would be fully blurred.

**Comment by Parveshdhull** [comment]
Hi, thank you for testing PR. I didn't test much on iOS, issue 1 is fixed, working on issue 2. Please can you elaborate on what you mean in issue 3?

**Comment by clauxx** [comment]
> Hi, thank you for testing PR. I didn't test much on iOS, issue 1 was fixed, working on issue 2. Please can you elaborate on what you mean in issue 3?

Here's a [reference video](https://private-user-images.githubusercontent.com/21865759/287664140-09f42ff8-dcec-4508-90db-ef8b79e8994a.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODA4ODEsIm5iZiI6MTcwMjI4MDU4MSwicGF0aCI6Ii8yMTg2NTc1OS8yODc2NjQxNDAtMDlmNDJmZjgtZGNlYy00NTA4LTkwZGItZWY4Yjc5ZTg5OTRhLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA3NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNjAxN2VhNTEyZGQ2ZGUzMmJlNzExMDVmZWFiYmI3NTA1NmE0MzcxMGQ4NDc4MjUzOTcyOTJlOGMxZDJhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2Ca1ogj8LfkZyxy74zBHKdNQyMp7AvxEytQMwBjf38) that shows the animation of the top bar opacity. It animates from 0 to 1 almost instantly and doesn't show the avatar below it.

**Comment by Parveshdhull** [comment]
thank you for video, looks like it also using same scroll view based opacity (not instantly) and avatar also visible there.
Only difference is they started animation little earlier.
(design should provide us exact parameters :( not just videos, otherwise we will always have these small differences)
image

**Comment by Parveshdhull** [comment]
Issue 1 and 2 fixed, thank you very much for finding them. Issue 3 [logged](https://github.com/status-im/status-mobile/issues/18132) as requires design input.

**Comment by Parveshdhull** [comment]
hi @status-im/mobile-qa Please can you check why e2e tests are failing.

**Comment by clauxx** [comment]
> Issue 1 and 2 fixed, thank you very much for finding them. Issue 3 [logged](https://github.com/status-im/status-mobile/issues/18132) as requires design input.

Thanks! On issue 1 there's still a small UI bug with the contact footer (see the screenshot). Also there's a new thing I notices, where the navigation header's name animates and disappears when opening a chat. I guess that's expected when the chat has a history of messages and is already scrolled down, but for a chat that just started it looks a bit weird. You can see it in below in the video.




https://github.com/status-im/status-mobile/assets/21865759/b78a41e1-e924-4bd5-8622-4b5935467692

**Comment by Parveshdhull** [comment]
> Thanks! On issue 1 there's still a small UI bug

fixed, thank you.

For issue mentioned in video, Please check out PR description.
(For the purpose of avoiding conflicts, and unblocking PRs, I skiped some edge cases and added in leftover issue. We have to fix them properly instead of using old method of reagent atoms that are getting triggered in messages list effect hooks)

File: src/js/worklets/chat/messages.js [hunk 10]
```diff
@@ -0,0 +1,67 @@
+import { useDerivedValue, withTiming, interpolate } from 'react-native-reanimated';
+
+export function navigationHeaderOpacity(bigNameVisible) {
+  return useDerivedValue(function () {
+    'worklet';
+    return bigNameVisible.value ? withTiming(0) : withTiming(1);
+  });
```
Comment (clauxx) [inline src/js/worklets/chat/messages.js]: Could `bigNameVisible` be a ratom instead and avoid using the worklet, or is there a performance drawback to that?

File: src/js/worklets/chat/messages.js [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+      'navigation-view-height': navigationViewHeight,
+      'all-loaded?': isAllLoaded,
+    } = props;
+
+    if (isAllLoaded.value) {
+      return interpolate(
+        distanceFromListTop.value,
+        // 142 - Position of pinned banner for starting animation (currently decided as per hit and trial)
+        // exact position needs to confirmed with design team - https://github.com/status-im/status-mobile/issues/18132
+        [navigationViewHeight + 142, navigationViewHeight + 142 + topBarHeight],
```
Comment (clauxx) [inline src/js/worklets/chat/messages.js]: I guess before the exact number is confirmed with the design team, it could be extracted and named inside cljs, so it's clearer what it represents.

File: src/status_im2/contexts/chat/messages/list/style.cljs [hunk 12]
```diff
@@ -18,45 +16,24 @@
...
+  [scale-animation top left]
   (reanimated/apply-animations-to-style
-   {:transform     [{:scale scale-animation}]
-    :margin-top    top-margin-animation
-    :margin-left   side-margin-animation
-    :margin-bottom side-margin-animation}
-   {:align-items :flex-start}))
+   {:transform [{:scale scale-animation}]
+    :top       top
+    :left      left}
```
Comment (clauxx) [inline src/status_im2/contexts/chat/messages/list/style.cljs]: I did similar changes in my PR here, but you can overwrite them, as yours looks smoother 👍

File: src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer.cljs [hunk 13]
```diff
@@ -12,7 +12,7 @@
   [contact-id contact-request-state group-chat]
   (let [customization-color (rf/sub [:profile/customization-color])
         [primary-name _]    (rf/sub [:contacts/contact-two-names-by-identity contact-id])]
-    [rn/view
+    [rn/view {:style {:position :absolute :bottom 0 :left 0 :right 0}}
```
Comment (clauxx) [inline src/status_im2/contexts/chat/messages/contact_requests/bottom_drawer.cljs]: belongs in `styles`

**Review by clauxx — APPROVED** [review]

File: src/js/worklets/chat/messages.js (hunk 10 above)
Comment (Parveshdhull) [reply src/js/worklets/chat/messages.js]: hi, thank you for reviewing PR. Yes they are drawbacks for using reagent atoms instead of worklets.
Please checkout [discord conversation ](https://discord.com/channels/1103692771585433630/1172058578153123840/1172058769627287622)

**Comment by VolodLytvynenko** [comment]
Hey @Parveshdhull , the tests have failed because Appium cannot find the 'chat-message-input' accessibility ID, as shown  [here](https://app.eu-central-1.saucelabs.com/tests/e6ac28a9d8d041178f5d5c3662496e90?auth=5135f8f561895c9ad28512320278c91b#69) within the App source scheme. I've noticed that I am unable to find this and other elements located in the composer as well ('send' button, 'emoji' button etc). 
 Any thoughts on why this might be happening?



### Actual result:
Current PR: "chat-message-input" accessibility id is missing in the App source
When I search "chat-message-input" accessibility id in the appium inspector
image

### Expected result:
Nighlty: "chat-message-input" accessibility id is located in the App source

image
image

File: src/js/worklets/chat/messages.js (hunk 11 above)
Comment (Parveshdhull) [reply src/js/worklets/chat/messages.js]: hi, I already logged an issue will address as soon as this PR merged.

File: src/js/worklets/chat/messages.js (hunk 10 above)
Comment (clauxx) [reply src/js/worklets/chat/messages.js]: big thumb-up on the points on ratoms and subs. It's become a nuisance to understand the data dependencies of a component cause everything is passed as maps of subs or ratoms to nested children and from there on it's the wild west.

File: src/status_im2/contexts/chat/messages/list/style.cljs (hunk 12 above)
Comment (Parveshdhull) [reply src/status_im2/contexts/chat/messages/list/style.cljs]: If we are agreeing these are smoother and we should overwrite them once your PR is merged. Then please can we just remove these changes from your PR so that @status-im/mobile-qa team don't need to test them twice.

Comment (clauxx) [reply src/status_im2/contexts/chat/messages/list/style.cljs]: It's just that removing this adds back other issues, since the margin animation changes the content-size, breaking some of the behavior from `on-content-size-change`. I would rather keep it there and help with the merge conflicts caused by this. What do you think?

File: src/status_im2/contexts/chat/messages/list/view.cljs [hunk 14]
```diff
@@ -386,10 +351,8 @@
...
        :on-scroll                         (fn [event]
                                             (scroll-handler event
-                                                            scroll-y
-                                                            animate-topbar-opacity?
-                                                            on-end-reached?
-                                                            animate-topbar-name?)
+                                                            distance-from-list-top
+                                                            on-end-reached?)
                                             (on-scroll event show-floating-scroll-down-button?))
        :style                             (add-inverted-y-android
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/messages/list/view.cljs]: Btw this inverted hack is no longer needed after RN 0.72

**Review by OmarBasem — APPROVED** [review]

**Comment by Parveshdhull** [comment]
Hi, Thank you very much @flexsurfer, @OmarBasem, @clauxx for reviewing PR.
I addressed most of the leftovers & regressions, and in the process removed 9/10 reagent atoms. One unused library (`rnio`) will be removed in the next PR.

I kept all new changes in the new commit [new-changes](https://github.com/status-im/status-mobile/pull/18055/commits/cd4d2e9c24350a45b0c6bb45efae2d34ebf4d4d3), older [commit](https://github.com/status-im/status-mobile/pull/18055/commits/7ab6b3f7e1c8958b445498e53c58684b809fb7a2) only have reviewed+rebase change.

Please let me know if anything needs to be updated.

**Comment by Parveshdhull** [comment]
Hi @VolodLytvynenko,
Thank you very much for taking the PR.
I updated the PR description with the new testing scope.
Also, fixed above failing e2e test.  Please can you also check the remaining tests.

Please also let me know how(if) PR effects performance of chat screen.

**Comment by VolodLytvynenko** [comment]
Hey @Parveshdhull
Thank you for e2e issue resolve. Here are additional found issues:

## ISSUE 2: Empty space displayed between 'send' button and device's opened keyboard

### Steps:
1. Paste some long text into the composer
2. Close chat
3. Reopen chat
4. Focus composer

### Actual result:
Upon reopening the chat and focusing on the composer area, an empty space is observed between the 'send' button and opened keyboard

https://github.com/status-im/status-mobile/assets/52490791/89e22a42-1399-4b7f-9bb1-5044d5c0be0c

image

### Expected result:
No empty space is shown
image

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: [IOS] Composer data becomes invisible on iOS until composer is tapped again

### Steps:
1. Paste data containing various content types (links, long text, added images) into the composer.
2. Close the chat.
3. Reopen the chat.
4. Tap the composer to focus.

### Actual result:
Upon reopening the chat and tapping the composer to focus, the data pasted into the composer remains invisible until the composer is tapped once more

https://github.com/status-im/status-mobile/assets/52490791/543e9481-a2b0-445a-9f18-9434f5bd19e1

### Expected result:
The expected behavior involves the immediate visibility of the composer data upon reopening the chat and tapping the composer to focus

### Devices:
- iPhone 11 Pro max, IOS 16

**Comment by VolodLytvynenko** [comment]
## ISSUE 4: [Android] Premature display of top bar in initially opened 1-1 chat

### Steps to Reproduce:
1. Open an empty 1-1 chat, where either the contact request has just been accepted or the chat has been cleared.

### Actual Result:
Upon reopening the empty 1-1 chat, the small avatar and top bar appear prematurely.  
image


### Expected Result:
 large avatar at the top of the 1-1 caht should be shown when no messages are present. As messages are scrolled through, the avatar should gradually become smaller. The top bar should only be displayed after scrolling to the bottom of the chat, ensuring a smooth transition between avatar sizes before revealing the top bar.

https://github.com/status-im/status-mobile/assets/52490791/ade2979e-bc9c-44a9-85f3-78a993582ca0

### Devices:
Pixel 7a, Android 14

**Comment by VolodLytvynenko** [comment]
## ISSUE 5:Delayed display of top bar in 1-1 and community chats
### Steps:
1. Open the empty chat
2. Send message by message
3. check the top bar showing

### Actual result:
The top bar does not come on time. It is shown until the 'No pinned messages' and 'mute chat' sections are hidden

https://github.com/status-im/status-mobile/assets/52490791/90879d1d-2f42-4af3-912c-308ae0f52dc6


### Expected result:
The top bar should be shown when the 1-1 avatar is hidden

How it works on the latest nightly:

https://github.com/status-im/status-mobile/assets/52490791/29b1a92d-0158-40b4-b88a-782dc7025d2e

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

**Comment by Parveshdhull** [comment]
Thank you @VolodLytvynenko, for finding all issues.
Should be fixed in latest build.

**Comment by VolodLytvynenko** [comment]
## ISSUE 6: Keyboard not triggered when attempting to edit or reply to a message

### Steps:
1. Send message
2. Long tap message
3. Select reply or edit message option

### Actual result:
After selecting the 'reply' or 'edit message' option, the keyboard is not automatically activated 

https://github.com/status-im/status-mobile/assets/52490791/9f79956e-3f72-4fa2-8235-69807c915df1

### Expected result:
After selecting the 'reply' or 'edit message' option, the keyboard is automatically activated 

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

**Comment by Parveshdhull** [comment]
Thank you, should be fixed in next build

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull issues: 4,5,6 are fixed. Thank you. Unfortunately, some issues are still reproducible

Issue 2: https://github.com/status-im/status-mobile/pull/18055#issuecomment-1859949731 still reproducible. 

### Empty space displayed between 'send' button and device's opened keyboard
### Steps:
1. Paste some long text into the composer
2. Close chat
3. Reopen chat
4. Focus composer

### Actual result:

image

**Comment by VolodLytvynenko** [comment]
issue 3: https://github.com/status-im/status-mobile/pull/18055#issuecomment-1859975832 Still reproducible.  [IOS] Composer data becomes invisible on iOS until composer is tapped again

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

**Comment by VolodLytvynenko** [comment]
Additional issues are found:


## ISSUE 7: The top bar is not shown when sequentially messages are sent in empty chat
### Steps:
1. Open the empty chat
5. Send message by message
6. check the top bar showing

### Actual result:
The top bar fails to be shown altogether when messages are sent sequentially in the initially empty chat

https://github.com/status-im/status-mobile/assets/52490791/15305afb-eee9-4ba2-b537-0e1a5bcee595

### Expected result:
The top bar should be shown when the 1-1 avatar is hidden

How it works on the latest nightly:

https://github.com/status-im/status-mobile/assets/52490791/29b1a92d-0158-40b4-b88a-782dc7025d2e

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

**Comment by VolodLytvynenko** [comment]
Overall, the usability of the composer looks much better compared to before this PR :)

**Comment by Parveshdhull** [comment]
hi @VolodLytvynenko,
Thank you very much for finding the issue 7. Should be fixed now.

So, only issue 2&3 remains, and they both require the pasting of very long text(edge case). Will it ok, if I fix them separately?
I am currently having a hard time reproducing them, and might take some time. (In mean time conflicts might arise in code)

**Comment by Parveshdhull** [comment]
> Overall, the usability of the composer looks much better compared to before this PR :)

Awesome, music to my ears :smile: :musical_note:

**Comment by VolodLytvynenko** [comment]
hey @Parveshdhull issue 7 is fixed partially https://github.com/status-im/status-mobile/pull/18055#issuecomment-1860880174

### Steps:
1. Receive 1-3 one-line messages in 1-1 chat
2. Open the chat
3. Send the message by message or receive message by message

### Actual result:
On IOS

https://github.com/status-im/status-mobile/assets/52490791/57e1f9d9-700b-4c3f-b972-6d76e29aa464

On Android

https://github.com/status-im/status-mobile/assets/52490791/d90f041a-66d2-46a7-a0d8-8dec5a82956f

### Expected result:
The top bar should be shown when the 1-1 avatar is hidden

**Comment by VolodLytvynenko** [comment]
One more way to reproduce [issue 7](https://github.com/status-im/status-mobile/pull/18055#issuecomment-1860880174): 

### The top bar is not shown when sequentially messages are received in empty chat
### Steps:
1. `User A` opens empty chat
2. `User B` sends long content messages to `User A`
3. `User A` observes the top bar

### Actual result:
Topbar is not shown for `User A`

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull Thank you for your patience and resolving our headache regarding composer usability :) PR is ready to be merged
