### PR TITLE
[#19182] fix: shell share design feedback

### LINKED ISSUE #19182: Shell - Share screen issues
# Design Feedback 2.27

## [Shell] Sharing screen: wallet tab
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=3%3A68309&mode=design&t=OeK3GHXzoVCNnZog-1)

- **Margin** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#727565741)] between the QR code card and the tabs above it doesn't match design
- **Inverted tabs** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#727564635)] inside the share card: Legacy 🔄 Multichain
- **QRs comparison** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#726063350)] between legacy and multichain should be visually similar, right now squares are different sizes
- **Card gets cut off** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#726032931)] at the bottom

Screenshot 2024-03-11 alle 16 49 50

### Reproduction

1. Tap on the Share QR code icon on the top right of the screen

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #19182

#### Done

- Margin [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#727565741)] between the QR code card and the tabs above it doesn't match design
- Inverted tabs [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#727564635)] inside the share card: Legacy 🔄 Multichain
- Card gets cut off [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#726032931)] at the bottom

#### Follow up
Note: QR view is depend on data we pass to it, for example if we display legacy address like `eth:0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359`, then squares will be the same
- QRs comparison [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=111:82256&mode=design#726063350)] between legacy and multichain should be visually similar, right now squares are different sizes

#### Areas that maybe impacted

- [Shell] Sharing screen: wallet tab

### Steps to test

- Tap on the Share QR code icon on the top right of the screen

### Result

status: ready

### CODE REVIEW

File: src/quo/components/share/share_qr_code/view.cljs [hunk 1]
```diff
@@ -23,24 +23,24 @@
   [{:keys [on-legacy-press on-multichain-press address]}]
   [rn/view {:style style/header-container}
    [tab/view
-    {:accessibility-label         :share-qr-code-legacy-tab
```
Comment (mohsen-ghafouri) [inline src/quo/components/share/share_qr_code/view.cljs:26]: Just reverted the tab position

**Review by OmarBasem — APPROVED** [review]
Looks good!

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa could you please check test results?

**Comment by VolodLytvynenko** [comment]
I rebased and performed rerun e2e one more time

**Comment by churik** [comment]
@mohsen-ghafouri please, make `git pull` if you make some changes in PR to pick up https://github.com/status-im/status-mobile/pull/19617/commits/3b3ad5f422caa392d46faa5749202755ba5e8be8

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Failed e2e are known and not related to your PR.

**Comment by mohsen-ghafouri** [comment]
@Francesca-G could you please review this?

**Review by Francesca-G — APPROVED** [review]
Looks good to me ✨

**Review by churik — APPROVED** [review]
