### PR TITLE
[iOS] Perform preflight check for local network permission

### LINKED ISSUE #16135: [iOS] Local Network Access Permission
# Bug Report

In iOS, after the device successfully scans a valid QR code, the device tries to discover the other device (sender) in the network. The user will get a permission dialog to allow finding devices in their local network, which is **automatically** requested by the iOS. 

The user needs to accept the permission for a successful pairing. If not, the pairing process is blocked in iOS.

### Reproduction

1) Open Status
2) Tap on "Sign in"
3) Scan a sync QR code

### Additional Information

- Status Version: nightly [31/05] 
- Operating System: iOS

### Notes:

- Starting from iOS 14, we need the user’s permission to discover devices in the user’s local network. https://developer.apple.com/videos/play/wwdc2020/10110/

- This issue is reproducible only in PR/nightly/release builds. We can NOT reproduce this in debug build as this permission is requested when debug build is first opened in the mobile/simulator to load the bundle from the metro bundler.

- Unfortunately, this permission type is yet to be added to the permission library we use on mobile due to the unavailability of explicit permission APIs from [Apple](https://developer.apple.com/forums/thread/663888). We need to create some helper functions to check if required.  We need a design, something like requesting camera permission before scanning the QR, to ensure smooth and successful pairing.

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #16135

### Summary

This PR attempts to move the local network access permission which is requested in iOS upon scanning the QR, to before scanning the QR as part of a preflight check by reusing the camera permission view/UI. 

The user is nicely informed to grant local network access permission for successful pairing. 

<table>
  <tr>
    <th>
    Informing the user
    </th>
    <th>
     Requesting the permission
    </th>
  </tr>
  <tr>
    <td>
      
    </td>
    <td>
      
    </td>
  </tr>
</table>

The problem is further explained in the PR's issue. This PR is using the changes from https://github.com/status-im/status-go/pull/3565 which will create outbound traffic so that the system will trigger the permission.

This PR is rebased on top of https://github.com/status-im/status-mobile/pull/16130.
cc: @churik 

#### Known UX issue:

Upon tapping the "Enable network access" button for the first time, permission is requested. But, we don't get feedback from the user on whether the permission is granted.  So, the user needs to tap on the button again to open the QR scanner.
This is similar to existing behaviour where the user needs to scan the QR code again after granting permission.

#### Platforms

- iOS

#### Areas impacted

 - Local pairing

#### Steps to test

- Open Status
- Sign in by syncing
- Pairing works as before

status: ready

### CODE REVIEW

**Review by qfrank — APPROVED** [review]
Nice PR!

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 1]
```diff
@@ -60,26 +62,37 @@
...
-   [quo/button
-    {:before              :i/camera
-     :type                :primary
-     :size                32
-     :accessibility-label :request-camera-permission
-     :override-theme      :dark
-     :on-press            request-camera-permission}
-    (i18n/label :t/enable-camera)]])
+  [request-camera-permission perform-preflight-check]
+  (let [title-label-key       (if @camera-permission-granted?
```
Comment (J-Son89) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: maybe slightly easier to read if you abstract the variables to a helper function..
```
(defn get-description [camera-permission-granted? request-camera-permission perform-preflight-check]
  (if camera-permission-granted?
    {:title-label-key       :t/enable-access-to-local-network
     :description-label-key :t/to-pair-with-your-other-device-in-the-network
     :button-icon          :i/world
     :button-label         :t/enable-network-access
     :on-press              perform-preflight-check}
    {:title-label-key       :t/enable-access-to-camera
     :description-label-key :t/to-scan-a-qr-enable-your-camera
     :button-icon           :i/camera
     :button-label         :t/enable-camera
     :on-press request-camera-permission}))

(let [{:keys [title-label-key
              description-label-key
              button-icon
              button-label
              on-press]} (get-description @camera-permission-granted?
                                          request-camera-permission
                                          perform-preflight-check)]
  ...)
  ```

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 2]
```diff
@@ -199,7 +215,14 @@
                                                         :icon-color colors/danger-50
                                                         :override-theme :light
                                                         :text (i18n/label
-                                                               :t/camera-permission-denied)}])}]))]
+                                                               :t/camera-permission-denied)}])}]))
+        perform-preflight-check   (fn []
+                                    ;; Performing the check for the first time
+                                    ;; will trigger local network access permission in iOS.
+                                    ;; This permission is requried for local pairing
```
Comment (J-Son89) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: typo: requried -> required

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 3]
```diff
@@ -199,7 +215,14 @@
                                                         :icon-color colors/danger-50
                                                         :override-theme :light
                                                         :text (i18n/label
-                                                               :t/camera-permission-denied)}])}]))]
+                                                               :t/camera-permission-denied)}])}]))
+        perform-preflight-check   (fn []
```
Comment (J-Son89) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: consider moving this whole function to a separate defn and leave the comment with it there. Also perhaps this atom should be passed as a parameter to the function.

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 4]
```diff
@@ -215,7 +238,11 @@
                                                                 3000)
                                                  (check-qr-code-data data)))
             scan-qr-code-tab?                (= @active-tab 1)
-            show-camera?                     (and scan-qr-code-tab? @camera-permission-granted?)
+            show-camera?                     (and scan-qr-code-tab?
+                                                  (if platform/ios?
```
Comment (J-Son89) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: why the platform check?  `@preflight-check-passed?` is true on android anyway -
this could just be 

```
show-camera? (and scan-qr-code-tab? 
       @camera-permission-granted?
       @preflight-check-passed?)
       ```

**Review by J-Son89 — APPROVED** [review]
nice work 😎

**Review by Samyoul — APPROVED** [review]
So I don't feel very qualified to approve this, buuut it looks good to me

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs (hunk 4 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: Yes, It's true on Android. I forgot to update the checks inside the render.

It's updated now. 👍

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: Good one 👍

**Review by siddarthkay — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. Here are some found issues:
## ISSUE 1: Enable network access screen is not displayed after disabling 'network access' in the device settings
### Steps:
1. Go to the 'Sign in by Syncing' page
2. Tap the 'enable network access' button -> Allow local network access
3. Go to the app settings -> Disable the 'network access' toggle
4. Go to the  'Sign in by Syncing' page

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/47ac452c-f4cd-43cd-bc38-ba9d5cd5f1bc

### Expected result:
If 'Network Access' is disabled in the device settings, the enable network access screen should be shown when the user goes to the 'Sign in by Syncing' page. The user should be prompted to enable network access again to proceed with syncing.

image

### Device:
- iPhone 11 Pro, IOS 16

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: Syncing start requires tapping twice on the 'Enable Network Access' Button
### Steps to Reproduce:
1. Go to the 'Sign in by Syncing' page.
2. Tap the 'Enable Network Access' button and allow local network access.

### Actual Result:
After tapping the 'Enable Network Access' button, syncing does not start immediately. The user needs to tap the button one more time to initiate the syncing process.


https://github.com/status-im/status-mobile/assets/52490791/9cd4019b-8f1f-49a6-ad4b-1c52585412d6


### Expected Result:
When the user taps the 'Enable Network Access' button and allowes the local network permissions, syncing should start immediately without the need for an additional tap.

### Device:
- iPhone 11 Pro, IOS 16

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: 'Invalid cyphertext length' error shown when scanning the already used sync QR code
### Steps to Reproduce:
1. Scan a valid sync code that has already been used.

### Actual Result:
The 'Invalid cyphertext length' error is displayed on the 'Oops something wrong' page.
image

### Expected Result:
The 'Invalid cyphertext length' error should not be shown on the 'Oops something wrong' page when scanning an already used sync QR code.

### Devices:
- iPhone 11 Pro, iOS 16
- Pixel 7a, Android 13

### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/11686970/android_logcat.txt)

**Comment by VolodLytvynenko** [comment]
### Question:
Should a toast message be added in scope of this PR? When the user taps the 'enable network access' button after local network access has been permitted? It would be beneficial to include a 'permission denied' toast message. Currently, nothing happens when this button is tapped.

## Steps to reproduce:
1. Go to the 'Sign in by Syncing' page.
2. Tap the 'Enable Network Access' button and deny local network access.
3. Tap the 'Enable Network Access' button again.

### Actual Result:
After tapping the 'Enable Network Access' button when local network access is denied, there is no visual feedback or toast indicating the permission denial.


https://github.com/status-im/status-mobile/assets/52490791/1926438e-c79e-4b49-96e0-e1d420346c1e


### Expected Result:
If the user taps the 'Enable Network Access' button and local network access is denied, a toast or visual feedback should be shown, indicating that the permission has been denied.
image

**Comment by pavloburykh** [comment]
> ### Question:
> Should a toast message be added in scope of this PR? When the user taps the 'enable network access' button after local network access has been permitted? It would be beneficial to include a 'permission denied' toast message. Currently, nothing happens when this button is tapped.

In case when user denied access to Local network it would be better to show Permission pop up again if he taps Enable network access again. For many users it is not obvious how to enable Local network for Status app manually from device settings.

**Comment by smohamedjavid** [comment]
Hi @VladimrLitvinenko - Thanks for taking the time to test this PR!

I have added my comments to the above issues/comments. Apologies in advance for the long replies.

> ISSUE 1: Enable network access screen is not displayed after disabling 'network access' in the device settings

This may be frustrating to the user and (but definitely) to the developers. Apple doesn't provide an explicit API to check whether local network access permission is granted or denied (just like Camera, Microphone, ...etc). Even there is no API to request the permission. This permission (dialog) is requested by the iOS automatically when we create outbound traffic to the local address.

I have mentioned it in the PR's [Issue](https://github.com/status-im/status-mobile/issues/16135). Also, quoting below the answer from Apple [FAQ](https://developer.apple.com/forums/thread/663888).

> "There is no API to explicitly bring up the local network privacy alert (r. 69157424). However, you can bring it up implicitly by sending traffic to a local network address."

Also, attaching the full [FAQ link](https://developer.apple.com/forums/thread/663858) about Local Network Privacy.

Generally speaking, If the user knows to change the permission by going into Settings, the user would definitely know this is due to the denied permission. 

<hr />

> ISSUE 2: Syncing start requires tapping twice on the 'Enable Network Access' Button

Yes, That is expected due to the permission nature. We don't get any feedback from the user on whether the permission is granted or not. So, The user needs to tap on the 'Enable Network Access' Button twice.

I have mentioned it in the PR description too:

> #### Known UX issue:
>Upon tapping the "Enable network access" button for the first time, permission is requested. But, we don't get feedback from the user on whether the permission is granted. So, the user needs to tap on the button again to open the QR scanner. This is similar to existing behaviour where the user needs to scan the QR code again after granting permission.

I thought of re-running the check again after some time (like 2 sec) to see if the permission is granted. But, it is not a good solution as the user's reaction time to the permission request dialog varies, and increases the complexity. So, skipped it.

<hr />

> ISSUE 3: 'Invalid cyphertext length' error shown when scanning the already used sync QR code

There is a reason why we show the error. There was an issue reported by @churik that despite the two devices being in the same network and getting local network access, the pairing is unsuccessful (no feedback from the QR scanner). 

So, at the moment, the idea is to take the user to the error screen (display any error received from `status-go`) if the pairing failed due to network issues because previously we don't have any feedback if there is any connection error. The user would scan the QR indefinitely (stuck in the scanner screen).

We need to display appropriate messages which will be done later.

This might partially resolve issues #15957 and #15530 as mentioned by @churik.

<hr />

> Should a toast message be added in scope of this PR? When the user taps the 'enable network access' button after local network access has been permitted? It would be beneficial to include a 'permission denied' toast message. Currently, nothing happens when this button is tapped.

We can add a toast message but we (the app) won't know if the permission is granted or denied.

When we perform the check (for the first time) by creating outbound traffic to a local address, permission is automatically requested by the Operating System, but the check will be blocked. 

When the user taps on the "Enable Network Access" Button again. the checks are performed again. If the checks are successful, that's the only way for the app to know the user has granted permission.

> In case when user denied access to Local network it would be better to show Permission pop up again if he taps Enable network access again. For many users it is not obvious how to enable Local network for Status app manually from device settings.

I agree @pavloburykh. If the user has denied the access, we can NOT request it again. The user needs to enable it manually from the system settings for the Status app. This is not a good user experience but this PR is the first step to inform the user to grant access to the local network access for successful pairing rather than getting this permission request on scanning a sync QR.

**Comment by pavloburykh** [comment]
@smohamedjavid thanx a lot for the detailed explanation!

**Comment by VolodLytvynenko** [comment]
HI @smohamedjavid yeh, Thank you a lot for your work and additional respect for such a detailed explanation. No other issues from my side. PR can be merged

**Comment by VolodLytvynenko** [comment]
> I thought of re-running the check again after some time (like 2 sec) to see if the permission is granted. But, it is not a good solution as the user's reaction time to the permission request dialog varies, and increases the complexity. So, skipped it.

Agree with you, re-running the permission check after a specific time interval may not be an optimal solution. 
However, I'm wondering if there might be other approaches to address this issue. Should I create a separate ticket for this?

<hr />

Thanx @pavloburykh . Created a separate follow-up  https://github.com/status-im/status-mobile/issues/16231 regarding this point https://github.com/status-im/status-mobile/pull/16150#issuecomment-1582418101

**Comment by pavloburykh** [comment]
> Thanx @pavloburykh . Created a separate follow-up #16231 regarding this point [#16150 (comment)](https://github.com/status-im/status-mobile/pull/16150#issuecomment-1582418101)

As far as I understood from above details provided by @smohamedjavid we will not be able to implement feature described in your followup. 

I might be wrong but I am basing on this comment:

>  If the user has denied the access, we can NOT request it again. The user needs to enable it manually from the system settings for the Status app. This is not a good user experience but this PR is the first step to inform the user to grant access to the local network access for successful pairing rather than getting this permission request on scanning a sync QR.

**Comment by smohamedjavid** [comment]
> Agree with you, re-running the permission check after a specific time interval may not be an optimal solution.
However, I'm wondering if there might be other approaches to address this issue. Should I create a separate ticket for this?

> As far as I understood from above details provided by @smohamedjavid we will not be able to implement feature described in your followup.

Yes, We can not request permission again if permission has been denied in the first place. That is the generic behaviour for every permission (Camera, Microphone,...etc) across the platform. So, we can not achieve the expectation from follow-up issue #16231.

We need to think of a workaround. I need to research this a bit.


P.S. All these headaches would go away if Apple has provided an explicit API to request and check the permission.

**Comment by pavloburykh** [comment]
> Yes, We can not request permission again if permission has been denied in the first place.

@smohamedjavid but we should defenately add at least "Persmission denied" pop up. As far as I understood it is possible to implement. See an example how it works with denied Camera permission. 

1. After user rejects Camera permission - "Permission denied" pop up (toast) appears
2. If user tries to Enbale Camera access after he denied camera permission - "Permission denied" pop up (toast) also appears

https://github.com/status-im/status-mobile/assets/97245802/84599d37-161e-492f-bfa0-3892fd99bde6

But we can do it in follow up.

**Comment by smohamedjavid** [comment]
> > Yes, We can not request permission again if permission has been denied in the first place.
> 
> @smohamedjavid but we should defenately add at least "Persmission denied" pop up. As far as I understood it is possible to implement. See an example how it works with denied Camera permossion.
> 
> 1. After user rejects Camera permission - "Permission denied" pop up (toast) appears
> 2. If user tries to Enbale Camera access after he denied camera permission - "Permission denied" pop up (toast) also appears
> 
>  telegram-cloud-document-2-5195441652423994256.mp4 
> But we can do it in follow up.

Yes, I agree we should add a "Permission Denied" toast.

As mentioned earlier that there is no feedback received from the permission request. I have a workaround in mind. I will work on this as a follow-up.

Thanks, @pavloburykh @VladimrLitvinenko for the suggestions and for testing the PR!

**Comment by pavloburykh** [comment]
> Created a separate follow-up #16231 regarding this point [#16150 (comment)](https://github.com/status-im/status-mobile/pull/16150#issuecomment-1582418101)

@smohamedjavid @VladimrLitvinenko I have updated this followup. Now it is a feature request for adding "Permission denied" toast for local network permissions.
