### PR TITLE
fix: remove contact from mutual contact list after contact is blocked

### LINKED ISSUE #15279: Users are not removed from each other's contact list after blocking
#### Preconditions:
1. User_A and User_B are contacts

#### Steps to reproduce:
1. go to the contacts list as User_A
2. open the profile of User_B
3. Tap 'block' button -> Block the contact
4. Go to the list of contacts as User_A
5. Go to the list of contacts as User_B

#### Actual result:
User_B and User_A are still shown in the contact list for each other

https://user-images.githubusercontent.com/52490791/223477299-088c3336-89b7-4d56-8c35-36eb6a3318fc.mp4

#### Expected result:
User_B and User_A are not shown in the contact list for each other after blocking

#### Additional info:
The contact is not shown in the list of contacts only after  relogin

#### ENV:
 Nightly: 7 Mar 2023

### PR DESCRIPTION
**Pull request by jo-mut**
fixes #15279

### Summary
This pr removes user A (the blocked contact)  from the contact list of user B once blocked and removes user B from user A list of contacts

### CODE REVIEW

**Review by alwx — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im/contact/block.cljs [hunk 1]
```diff
@@ -60,7 +60,8 @@
                                    (:contacts/contacts db)
                                    public-key)
                                   (assoc :blocked? true
-                                         :added?   false))
+                                         :added?   false
+                                         :active?  false))
```
Comment (ibrkhalil) [inline src/status_im/contact/block.cljs:64]: Should we set the `mutual?` attribute to `false` too ?

**Comment by VolodLytvynenko** [comment]
Hi @jo-mut let me know please if this PR is ready for tests

File: src/status_im/contact/block.cljs (hunk 1 above)
Comment (jo-mut) [reply src/status_im/contact/block.cljs:64]: @ibrkhalil  does not seem to have any effect but it can be set to false since the two contacts in this context are no longer mutual the moment one becomes blocked

**Comment by jo-mut** [comment]
@VladimrLitvinenko this is ready you can proceed with the testing. Thanks

**Comment by pavloburykh** [comment]
@jo-mut thanx for the PR. 

Initial [issue](https://github.com/status-im/status-mobile/issues/15279) misses the case with contact removal after which contact list is not being updated too. Is it possible to cover contact removal case by this PR? 

### ISSUE 1 Removed contact is shown in contact list until app reopening or opening removed user profile screen
**Preconditions:** User A and User B are contacts

**Steps:** 

1. User A removes User B from contacts
2. See if User B has been removed from User's A contact list

**Actual result:** User B remains in User's A contact list until app reopening or opening removed user profile screen


https://user-images.githubusercontent.com/97245802/231152713-ad851af9-432a-4ce5-a65c-71877d4dab20.mp4

File: src/status_im/contact/block.cljs (hunk 1 above)
Comment (jo-mut) [reply src/status_im/contact/block.cljs:64]: yeah you are right

**Comment by jo-mut** [comment]
@pavloburykh currently this pr as is removes User B from User's A list of contacts. I will update the pr so that user B is also removed from user A list contact.

https://user-images.githubusercontent.com/28704507/231900020-16964a1b-3b28-415f-8573-2aedbd9540de.mov

**Comment by jo-mut** [comment]
@pavloburykh I have updated the pr so that both contact are removed from each others list but just before you run the tests I would like to take another look at status-go please hold on running tests on this for a while

**Comment by churik** [comment]
Also please note this behavior now: currently after blocking/removing a user, it disappears from the contact list only after reopening this list.
It would be nice to address this issue here as well.


Thank you!

**Comment by jo-mut** [comment]
@pavloburykh this is ready. Thanks

**Comment by flexsurfer** [comment]
hey @jo-mut could you please rebase and more to e2e

**Comment by VolodLytvynenko** [comment]
hi @jo-mut, thank you for PR. no issues from my side. PR is ready to be merged
