### PR TITLE
[Fix] Wallet - Clear input on long press delete

### LINKED ISSUE #18685: Incomplete data removal with Long Tap on 'Remove' button in 'Send Assets' Screen
Follow up for https://github.com/status-im/status-mobile/pull/18594

### Steps:
1. Go to the 'send assets' screen.
2. Enter a few numbers.
3. Long tap on the 'remove' button.

### Actual result:
Only one character is removed.

https://github.com/status-im/status-mobile/assets/52490791/b2ab54f4-bb89-418b-8068-bbc4bf89bc0d

### Expected result:
Potential solutions:
- All characters should be removed one by one when the remove button is long-tapped (example below how it is implemented for Binance).

https://github.com/status-im/status-mobile/assets/52490791/cf872d95-d508-4ce8-a19d-75c547e5cdcf

- All characters should be removed at once (an example of how it works for Metamask).

https://github.com/status-im/status-mobile/assets/52490791/e3cb31e2-155f-495b-847f-5a7f06f8d82b

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18685

### Summary

This PR allows clearing the amount input (in the send flow) by long-pressing the delete key.

https://github.com/status-im/status-mobile/assets/19339952/ea7bd817-322f-4cd5-b2cd-e51d3a2ed0c9

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Create a profile
- Navigate to the Wallet tab
- Tap on any of the accounts
- Tap on `Send`
- Select an asset
- Enter any amount in the input
- Verify on press of delete, it deletes one character
- Verify on long press of delete, it clears the input

status: ready

### CODE REVIEW

File: src/quo/components/numbered_keyboard/keyboard_key/view.cljs [hunk 1]
```diff
@@ -15,7 +15,7 @@
 (defn- view-internal
   []
   (let [pressed? (reagent/atom false)]
```
Comment (J-Son89) [inline src/quo/components/numbered_keyboard/keyboard_key/view.cljs:17]: should we add a schema to this component while we are adding new props to it? 
I think it's not in the list of components in the schema epic as I probably missed this ns when making those issues

File: src/quo/components/numbered_keyboard/keyboard_key/view.cljs [hunk 2]
```diff
@@ -24,6 +24,9 @@
           :on-press                (fn []
                                      (when on-press
                                        (on-press label)))
+          :on-long-press           (fn []
+                                     (when (fn? on-long-press)
+                                       (on-long-press label)))
```
Comment (briansztamfater) [inline src/quo/components/numbered_keyboard/keyboard_key/view.cljs:29]: Maybe just 
```
#(when (fn? on-long-press)
    (on-long-press label))
```

**Review by briansztamfater — APPROVED** [review]

**Review by OmarBasem — APPROVED** [review]

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 3]
```diff
@@ -125,6 +125,12 @@
                                       (swap! input-value delete-from-string start)
                                       (move-input-cursor input-selection (dec start)))
                                     (reagent/flush))))
+        on-long-press-delete  (fn [loading-routes?]
+                                (when-not loading-routes?
+                                  (reset! input-value "")
+                                  (reset! input-error false)
+                                  (move-input-cursor input-selection 0)
+                                  (reagent/flush)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:163]: :+1:

File: src/quo/components/numbered_keyboard/keyboard_key/view.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/quo/components/numbered_keyboard/keyboard_key/view.cljs:29]: @briansztamfater 
Previously I'd suggest the same, but some time ago @ilmotta  suggested to only use `#` for simple one-liner functions.

The reason is it takes longer for the reader to realize if `%`, (or `%1`,  `%2`, etc...) is being used and where is placed.  Instead if we have `(fn[])` we know what the function takes.

**Review by ulisesmac — APPROVED** [review]

File: src/quo/components/numbered_keyboard/keyboard_key/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/quo/components/numbered_keyboard/keyboard_key/view.cljs:17]: @J-Son89 - Can we do it in a separate PR/issue? To find and fix bugs related to those changes (if any).

Comment (J-Son89) [reply src/quo/components/numbered_keyboard/keyboard_key/view.cljs:17]: Of course!

**Comment by mariia-skrypnyk** [comment]
Hi @smohamedjavid !
Thanks for your PR!
Your fix of long press delete looks great.
But I see a new issue appeared between your PR build and today's rebased PR build. 
Let me show you.

**ISSUE 1 All elements on the screen looks like inactive "Send assets" screen**

**Steps:**

Go to Wallet -> Send
Put any exist address there
Go to the "Send assets" screen

**Actual result:**
All elements on the screen looks like inactive "Send assets" screen
photo_2024-02-08_12-58-10

**Expected result:**
Screen should look normally like everything is active

Additional info: Android 13.0

The rebase took place today and after analysis of today's merges we didn't find the strong reason :(
image_2024-02-08_14-34-24

**Comment by mariia-skrypnyk** [comment]
Hi @smohamedjavid !
I see you worked on the fix. 
Please, let me know when it will be ready for me to test.
Thanks!

**Comment by smohamedjavid** [comment]
Hi @mariia-skrypnyk!
Yes, It's ready for testing.

**Comment by mariia-skrypnyk** [comment]
@smohamedjavid Thanks for your fix!

I've checked clear input on long press and faded effect on Android.
Failed e2e tests are not related to this PR so feel free to merge it!
