### PR TITLE
[Fix] Edited wallet account name persists in other edit account screens

### LINKED ISSUE #18701: Wallet: App db not properly cleaned for accounts
# Bug Report

## Problem 
The app db is not being properly cleaned when we leave pages, an example:

[Screencast from 2024-02-01 20-08-45.webm](https://github.com/status-im/status-mobile/assets/90291778/979c4e66-df02-4a4b-8d66-7a969f4d960e)

#### Expected behavior
Load the actual account name

#### Actual behavior
Old name is loaded

### Reproduction
- check the video 

### Additional Information

These errors are happening all the time, when we navigate back we should always (or almost always) clean the app-db to avoid carrying old state.

It'd be good to have a general solution, probably execute an event after navigating back to clean a specified app-db key

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #18701

### Summary

This PR fixes the edited wallet account name that persists in other account edit screens.

The fix is simple to return a function (to re-create the screen & atoms) instead of var (which holds the atom state)

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Create a profile
- Navigate to the Wallet tab
- Create a new Wallet account (Eg: `Account 2`)
- Edit the name of the account 2 and save it
- Navigate to the Edit page of the first account
- Verify the edited name of the second account is NOT displayed in it

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
nice ✨

File: src/status_im/contexts/wallet/edit_account/view.cljs [hunk 1]
```diff
@@ -33,7 +33,8 @@
                   {:account    edited-account-data
                    :on-success #(show-save-account-toast updated-key)}])))
 
-(def view
+(defn view
+  []
   (let [edited-account-name  (reagent/atom nil)
         show-confirm-button? (reagent/atom false)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/edit_account/view.cljs:39]: Incredible that this happened and it worked.

I see the problem as atoms were permanent and didn't restared its state.

Really nice catch @smohamedjavid !

**Review by ulisesmac — APPROVED** [review]

File: src/status_im/contexts/wallet/edit_account/view.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/contexts/wallet/edit_account/view.cljs:39]: Not going to lie, took a while to figure out why the atom didn't reset 😅.

**Review by flexsurfer — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @smohamedjavid!

Thanks for your PR. 
Now wallet account name doesn't persists in other account edit screens.
Great job!
Failed e2e are not related to your PR. Please, go ahead and merge it!
