### PR TITLE
 bug/white-screen-on-contacts-page (#643)

### LINKED ISSUE #643: White screen appearing on contacts page
White screen:
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/45

Back button causing similar issue:
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/44

Steps to reproduce:
1. Tap contacts icon in tray
2. Tap back button on device
3. Tap any tray icon again

### PR DESCRIPTION
**Pull request by flexsurfer**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #643

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status on Android
- Open contacts tab
- Press back button on a device

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

File: src/status_im/navigation/handlers.cljs [hunk 1]
```diff
@@ -12,7 +12,7 @@
   (let [stack' (if (> 2 (count stack))
                  (list :chat-list)
                  (pop stack))]
-    (conj stack' view-id)))
+      (conj stack' view-id)))
```
Comment (flexsurfer) [inline src/status_im/navigation/handlers.cljs]: :(
