### PR TITLE
Fixed styling issues for mention in the chat text

### LINKED ISSUE #15693: Mentions in chat are not aligned properly with rest of the text
Design: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=3188-50051&t=n9pKlzSeSiKJFayB-4

### Screenshots
Android | iOS
-|-
Android|iOS

### LINKED ISSUE #15702: Chat mention component border radius not implemented
# Bug Report
## Problem 
The borders of the 'mention component' in the chat screen are not rounded.

#### Expected behavior
Mention component border should be rounded. Design: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=3188-50051&t=n9pKlzSeSiKJFayB-4

#### Actual behavior
Borders are not rounded.

#### Screenshots
Android | iOS
-|-
Android | iOS

### Reproduction
Open any chat screen with mentions.

### Additional Information
- Operating System: Android, iOS

This bug was introduced in this #15698 which fixed mention alignment issues.

### PR DESCRIPTION
**Pull request by rahulpsingh**
fixes #15702 

### Summary

 - Fixed styling issues for mention in the chat text

### Screenshots

| Android | iOS |
| --- | ----------- |
| Screenshot_20230424-142630 | Screenshot 2023-04-24 at 2 28 00 PM |

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @rahulpsingh , thank you for the PR, could you pls fix linting 
```
[2023-04-24T09:44:25.892Z] Configuring Nix shell for target 'default'...

[2023-04-24T09:44:27.871Z] bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

[2023-04-24T09:44:27.871Z] sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

[2023-04-24T09:44:35.939Z] linting took 7779ms, errors: 0, warnings: 0

[2023-04-24T09:44:56.301Z] Formatting required in file src/status_im2/contexts/chat/messages/content/text/style.cljs

[2023-04-24T09:44:56.301Z] Formatting required in file src/status_im2/contexts/chat/messages/content/text/view.cljs

[2023-04-24T09:45:01.824Z] Processed 1086 files, 2 of which require formatting.

[2023-04-24T09:45:01.824Z] make: *** [Makefile:307: lint] Error 2
```

**Comment by rahulpsingh** [comment]
> hey @rahulpsingh , thank you for the PR, could you pls fix linting
> 
> ```
> [2023-04-24T09:44:25.892Z] Configuring Nix shell for target 'default'...
> 
> [2023-04-24T09:44:27.871Z] bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> 
> [2023-04-24T09:44:27.871Z] sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> 
> [2023-04-24T09:44:35.939Z] linting took 7779ms, errors: 0, warnings: 0
> 
> [2023-04-24T09:44:56.301Z] Formatting required in file src/status_im2/contexts/chat/messages/content/text/style.cljs
> 
> [2023-04-24T09:44:56.301Z] Formatting required in file src/status_im2/contexts/chat/messages/content/text/view.cljs
> 
> [2023-04-24T09:45:01.824Z] Processed 1086 files, 2 of which require formatting.
> 
> [2023-04-24T09:45:01.824Z] make: *** [Makefile:307: lint] Error 2
> ```

Sure, yes!!

**Comment by cammellos** [comment]
@rahulpsingh it seems it still needs some linting, you can fix those issues by running:
`make lint-fix` / commit / push

Thank you!

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 1]
```diff
@@ -7,7 +7,10 @@
   {:margin-top -4})
 
 (def paragraph
-  {:margin-top spacing-between-blocks})
+  {:margin-top           spacing-between-blocks
+   :position             :relative
+   :text-align-vertical  :top
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: @rahulpsingh, just curious, you probably tried `:text-align-vertical :center`. Does it lead to worse or better results?

From the docs:

>Set to false to remove extra font padding intended to make space for certain ascenders / descenders. With some fonts, this padding can make text look slightly misaligned when centered vertically. For best results also set textAlignVertical to center.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 2]
```diff
@@ -20,6 +23,30 @@
...
+   :padding-horizontal  3
+   :border-radius       6
+   :margin-bottom       -3
+   :z-index             1})
+
+(def mention-tag-text
+  {:color                 (colors/theme-colors colors/primary-50
+                                               colors/primary-60)
+   :selection-color       :transparent
+   :include-font-padding  false
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: Should we add `:text-align-vertical :center` or it doesn't make much of a difference?

> For best results also set textAlignVertical to center.
>
> -- https://reactnative.dev/docs/text-style-props#includefontpadding-android

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 3]
```diff
@@ -20,6 +23,30 @@
...
+
+(def mention-tag
+  {:background-color    colors/primary-50-opa-10
+   :position            :relative
+   :padding-horizontal  3
+   :border-radius       6
+   :margin-bottom       -3
+   :z-index             1})
+
+(def mention-tag-text
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs:34]: Here we should use `defn` instead of `def` because `colors/theme-colors` rely on a Reagent atom to pick the color based on the current theme. With `def`, if the user switches theme the value of `mention-tag-text map won't be redefined.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 4]
```diff
@@ -7,7 +7,10 @@
   {:margin-top -4})
 
 (def paragraph
-  {:margin-top spacing-between-blocks})
+  {:margin-top           spacing-between-blocks
+   :position             :relative
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: I had the impression all RN components by default use `:position :relative`, so this seems unnecessary.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 5]
```diff
@@ -20,6 +23,30 @@
    :padding-left      10
    :border-left-color colors/neutral-40})
 
+(def mention-tag-wrapper
+  {:position           :relative
+   :padding-vertical   0
+   :padding-horizontal 0
+   :margin-vertical    0
+   :margin-horizontal  0
```
Comment (ajayesivan) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: @rahulpsingh  could you please help me understand why we need these styles? I think they are same as default values.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 6]
```diff
@@ -20,6 +23,30 @@
...
+   :flex-direction     :row
+   :align-items        :center})
+
+(def mention-tag
+  {:background-color    colors/primary-50-opa-10
+   :position            :relative
+   :padding-horizontal  3
+   :border-radius       6
+   :margin-bottom       -3
```
Comment (ajayesivan) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: I'm not sure about using `margin` to fix style issues. They may not look the same on all devices.

You may have noticed that in the iOS screenshot, the alignment looks perfect, but on Android, it may appear slightly off by `1` or `2px` (though this could be a matter of personal perception).

@rahulpsingh How did you land on `-3` for `margin-bottom`?

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 7]
```diff
@@ -20,6 +23,30 @@
...
+   :z-index             1})
```
Comment (ajayesivan) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: Is it necessary to use `z-index` here?

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 1 above)
Comment (rahulpsingh) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: It's not making any impact, so I removed it at all. The idea here was to remove the font padding from rest of the paragraph and make it centered so that it looks aligned in the Android devices.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 2 above)
Comment (rahulpsingh) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: It's not making any impact, so I removed it.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 3 above)
Comment (rahulpsingh) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs:34]: Sure, I used `defn` here instead of `def`.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 4 above)
Comment (rahulpsingh) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: Sure, I removed it.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 5 above)
Comment (rahulpsingh) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: I started this component with `rn/view`, so I just wanted to remove any unnecessary margin/padding which may have been defined. But it seems the above isn't making any impact so I removed it as well.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 6 above)
Comment (rahulpsingh) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: Yes, as the tag sit in the `rn/touchable-opacity` it's automatically vertically aligned. and the difference between line-height and font size is 7, so a margin bottom of 3 fixes the issue with misalignment. About this style not being applied to Android devices, it's a known bug that negative margins are inconsistent(in support) in the Android devices.

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 7 above)
Comment (rahulpsingh) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: It seemed to be a workaround for negative margins not working. But this as well doesn't do anything so removing it.

**Review by ilmotta — APPROVED** [review]
Nice to see this is fixed, thanks @rahulpsingh

**Review by ajayesivan — APPROVED** [review]
I created a PR(https://github.com/status-im/status-mobile/pull/15698) with a partial fix for this issue last week. But I think this one fixes it completely.

Great work 🎉  @rahulpsingh & Thanks for the PR.

**Review by J-Son89 — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @rahulpsingh ! Thanx for the PR. Could you please rebase it to the latest develop before we proceed with testing? Thanx!

**Comment by cammellos** [comment]
@pavloburykh rebased!

**Comment by pavloburykh** [comment]
@rahulpsingh thanx for the PR. Tested and ready to be merged.

**Comment by John-44** [comment]
The alignment of the @ mentions in the screenshots at the top or this PR looks correct in iOS, but looks incorrect for Android (because the bottom of the text in the highlighted @ mention should align with the bottom of the text that is not included in the @ mention e.g. @ mention text should be baseline aligned with non-@ mention text)

**Comment by pavloburykh** [comment]
> The alignment of the @ mentions in the screenshots at the top or this PR looks correct in iOS, but looks incorrect for Android (because the bottom of the text in the highlighted @ mention should align with the bottom of the text that is not included in the @ mention e.g. @ mention text should be baseline aligned with non-@ mention text)

Thanx for noticing @John-44 I have logged a separate issue on that https://github.com/status-im/status-mobile/issues/15745
