### PR TITLE
Prevent exception when viewing contact QR code

### LINKED ISSUE #19325: 're-find match against the string' error is shown after Show QR code option is selected when user is blocked
Follow up for https://github.com/status-im/status-mobile/pull/19246
Reference to https://github.com/status-im/status-mobile/pull/19246#issuecomment-2003655694
image

### Steps:
1. `UserA` blocks `UserB` 
2. Open right up three dots to open the drawer
3. Select 'Show QR code' option

### Actual result:
're-find match against the string' error is shown after Show QR code option is selected
image

### Expected result:
no error when 'Show QR code' option is selected

### Logs:
[logs (4).zip](https://github.com/status-im/status-mobile/files/14625213/logs.4.zip)

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #19325 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

* This PR attempts to prevent the exception mention in #19325 
* This PR modifies the `utils.address/get-abbreviated-profile-url` function to return nil if passed nil.
  * By checking for nil we can avoid the `re-find` exception mentioned in #19325
* Note that preventing the exception avoids crashing the app, but it doesn't ensure the QR screen has valid QR data.
  * The attached screenshot in this PR displays what someone would see if they opened this screen and didn't have a valid QR code presented.
  * Perhaps this is okay if we think the QR data will be eventually populated (?)

#### Platforms

- Android
- iOS

##### Functional

- Contact Profile Share QR code

### Steps to test

Steps to reproduce the issue are mentioned in #19325 

### After

Screenshot 2024-04-10 at 13 00 51

status: ready

### CODE REVIEW

File: src/utils/address.cljs [hunk 1]
```diff
@@ -46,7 +46,10 @@
   with the 1st 5 characters of the encoded data followed by an ellipsis
   followed by the last 10 characters of the compressed public key"
   [universal-profile-url]
-  (when-let [re-find-result (re-find #"^https://(status.app/u/)(.*)#(.*)$" universal-profile-url)]
+  (when-let [re-find-result (re-find #"^https://(status.app/u/)(.*)#(.*)$"
+                                     (if-not (string? universal-profile-url)
+                                       (str universal-profile-url)
+                                       universal-profile-url))]
```
Comment (ibrkhalil) [inline src/utils/address.cljs]: I'd just use the first clause by default without the `(if-not` call.

Comment (ibrkhalil) [reply src/utils/address.cljs]:
```clj
(re-find #"^https://(status.app/u/)(.*)#(.*)$" (str universal-profile-url))
```

**Review by ibrkhalil — APPROVED** [review]
lgtm, Non blocking comment

File: src/utils/address.cljs (hunk 1 above)
Comment (seanstrom) [reply src/utils/address.cljs]: I like it 👍
