### PR TITLE
fix: ensure the key pair action button opens bottom-sheet inside key pairs and accounts

### LINKED ISSUE #20609: Can't open the options menu on the "Key pairs and accounts" screen
# Bug Report

## Problem 

The `three dots` button on additional (non-default) key pairs does not respond. 

The last commit in https://github.com/status-im/status-mobile/pull/20464 has not been tested before merging, that could cause this issue cc @seanstrom 

_Note: for a missing key pair it works fine_

https://github.com/status-im/status-mobile/assets/67952253/e25478de-f5c4-40a7-9798-51de18598cf1

### Reproduction

1. Create/import an additional key pair in wallet
2. Go to `Profile` > `Wallet` > `Key pairs and accounts`
3. Press the `three dots` button on the created key pair

#### Expected behavior
The menu is opened 

Design: https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=4764-18817&t=rSuKoQaXUmT8UMXr-4

#### Actual behavior
Nothing happens

### Additional Information

- Status version: nightly 1/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #20609 

### Summary

* This PR attempts to fix an issue where the options / actions menu button for a key-pair, inside the key-pairs and accounts settings, does not open the key-pair action menu.

#### Platforms

- Android
- iOS

##### Functional

- Key pairs and Accounts settings
- Selecting a key pair when creating an account

### Steps to test

- Open Status mobile
- Navigate to the Settings screen
- Navigate to Wallet settings screen
- Navigate to Key pairs and Accounts settings screen
- Press on the "..." menu button on a existing key pair

### Screen capture after changes

https://github.com/status-im/status-mobile/assets/2845768/b7798322-b1ed-4dd3-b112-e2ea14f42a71

status: ready

### CODE REVIEW

File: src/quo/components/wallet/keypair/view.cljs [hunk 1]
```diff
@@ -101,8 +101,7 @@
                                               :selected?       selected?
                                               :container-style container-style
                                               :theme           theme))
-      :on-press       #(when (= action :selector) (on-press))
-      :pointer-events :box-only}
```
Comment (seanstrom) [inline src/quo/components/wallet/keypair/view.cljs]: Here I'm removing this `:pointer-events` prop because when it's set to `box-only` it will not allow the pointer events to hit reach the "..." menu button inside the key-pair component.

Perhaps we need to pass a configuration prop for this if we need to ensure it's `box-only` sometimes, thoughts?

**Review by seanstrom — COMMENTED** [review]
Self-review comments 📖

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/quo/components/wallet/keypair/view.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/quo/components/wallet/keypair/view.cljs]: not sure why we need it at all 🤔

Comment (smohamedjavid) [reply src/quo/components/wallet/keypair/view.cljs]: I'm not sure why it's needed in the first place 🤔 .

**Review by smohamedjavid — APPROVED** [review]

File: src/quo/components/wallet/keypair/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/quo/components/wallet/keypair/view.cljs]: I added the `box-only` because when we use it for keypair selection, other non important areas are pressable and make hard to select the proper keypair.

@seanstrom Probably we should handle the `:box-only` according to the variant displayed

Comment (seanstrom) [reply src/quo/components/wallet/keypair/view.cljs]: @ulisesmac Oh I see, so this is meant to make it simpler to press the key-pair, in that case I'll try using `(when (= action :selector) :box-only)` for that prop. Thank you for clarifying 🙏

Comment (smohamedjavid) [reply src/quo/components/wallet/keypair/view.cljs]: @ulisesmac - I suppose the `on-press` should be handled by the selector (it receives the `on-change` prop), not the parent. WDYT? This would help us prevent these pointer event tricks.

https://github.com/status-im/status-mobile/blob/8aa1cadc663642adb257df499904a59a062039b1/src/quo/components/wallet/keypair/view.cljs#L52-L56

Comment (seanstrom) [reply src/quo/components/wallet/keypair/view.cljs]: @smohamedjavid I'm not sure, but I think the intent is to make the key-pair component easier to select during the key-pair selection step. If we put the `on-press` handler on the selector, that would make the target smaller for selecting a key-pair when ideally it would be the entire key-pair UI.

**Comment by mariia-skrypnyk** [comment]
Hey @seanstrom !

Your fix looks good on both platforms.
Failed e2e are known and under investigation.
They are not related to your changes.
Please merge your PR.
Great job! 🫡🙌
