### PR TITLE
[#20463] Fix iOS can't fetch collectible error

### LINKED ISSUE #20463: [IOS] "Unsupported file" shown on detailed collectible view for some collectibles while images are fetched on list view
### Steps:
1. Restore a user with collectibles from this https://testnets.opensea.io/collection/the-monkey-chainz collection or add the address as watch only '0xeD620C9dC11401b63B35Dfe8e93F2b11DB0F6F9e' (NOTE: current collectibles are on the testnet)
2. Go to collectibles tab
3. Open collectible to see the detailed view

### Actual result:
"Unsupported file" message is shown on the detailed collectibles view, while the images are fetched on the list view.

https://github.com/status-im/status-mobile/assets/52490791/13de5823-8acb-4a09-b5a9-db8279892b55

### Expected result:
If the collectible image is fetched on the list view, it should also be fetched for the detailed view.

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/15837245/Status-debug-logs.zip)

### ENV:
Nightly 14 Jun 2024

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20463

### Summary

This is a small PR addressing the comment added by @VolodLytvynenko:

https://github.com/status-im/status-mobile/issues/20463#issuecomment-2219816210

### Review notes
The error only happens on iOS and it is due to the navigation timing on that plaform, it seems re-frame needs more time to perform the update, so now we wait more than one frame (17ms) to perform the navigation.

Additionally, a use-effect hook has been added in case the `image-src` changes while visiting the collectible details page.

status: ready

### CODE REVIEW

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 1]
```diff
@@ -79,14 +79,20 @@
...
   [{:keys [container-style square? on-press counter image-src native-ID supported-file?
            on-collectible-load aspect-ratio gradient-color-index]
     :or   {gradient-color-index :gradient-1
            on-collectible-load  (fn [])}}]
   (let [theme              (quo.theme/use-theme)
-        [error? set-error] (rn/use-state (or (nil? image-src)
-                                             (string/blank? image-src)))]
+        [error? set-error] (rn/use-state (invalid-image? image-src))]
+    (rn/use-effect #(set-error (invalid-image? image-src))
+                   [image-src])
```
Comment (ulisesmac) [inline src/quo/components/profile/expanded_collectible/view.cljs:95]: `use-effect` to react to external `image-src` changes, they may happen if the request takes too long to be received

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 2]
```diff
@@ -185,7 +185,7 @@
            ;; We delay the navigation because we need re-frame to update the DB on time.
            ;; By doing it, we skip a blink while visiting the collectible detail page.
            [:dispatch-later
-            {:ms       1
+            {:ms       17
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/events.cljs:188]: on iOS 1 ms wasn't enough, this has been increased to avoid the blinking. This is unnoticeable for the user.

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 3]
```diff
@@ -79,12 +79,20 @@
...
+                                   (colors/theme-colors colors/white-opa-0
+                                                        colors/neutral-95-opa-0
+                                                        theme)
+                                   (colors/theme-colors colors/white-opa-50
+                                                        colors/neutral-95-opa-70-blur
+                                                        theme))
+        {{preview-uri :uri}  :preview-url
+         {title :name}       :collectible-data
+         {description :name} :collection-data
+         id                  :id} (rf/sub [:wallet/collectible-details])]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/view.cljs:95]: Just a refactor, all the remaining changes are just refactors

**Review by J-Son89 — APPROVED** [review]

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 4]
```diff
@@ -79,14 +79,20 @@
         [counter-view counter])
       [rn/view {:style (style/collectible-border theme)}]]]))
 
+(defn invalid-image?
```
Comment (OmarBasem) [inline src/quo/components/profile/expanded_collectible/view.cljs:82]: should be private?

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 5]
```diff
@@ -79,14 +79,20 @@
...
+
 (defn view-internal
   [{:keys [container-style square? on-press counter image-src native-ID supported-file?
            on-collectible-load aspect-ratio gradient-color-index]
     :or   {gradient-color-index :gradient-1
            on-collectible-load  (fn [])}}]
   (let [theme              (quo.theme/use-theme)
-        [error? set-error] (rn/use-state (or (nil? image-src)
-                                             (string/blank? image-src)))]
+        [error? set-error] (rn/use-state (invalid-image? image-src))]
```
Comment (OmarBasem) [inline src/quo/components/profile/expanded_collectible/view.cljs:93]: `defn-`

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 2 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/collectible/events.cljs:188]: Is `17ms` always going to be enough? Why not a bit bigger number that would still be unnoticeable (maybe 50ms)

**Comment by mariia-skrypnyk** [comment]
Hi @ulisesmac !
Thanks for your PR.

Checked iOS fetching and it works correct on my side.

Uploading IMG_0996.MP4…

PR can be merged.

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/events.cljs:188]: Hey Omar!
This is just slightly more than a frame (running at 60fps)
Ofc I could set 50ms, but right now, as far as I tested, this works well.

**Comment by ulisesmac** [comment]
> Hi @ulisesmac ! Thanks for your PR.
> 
> Checked iOS fetching and it works correct on my side.
> 
> Uploading IMG_0996.MP4…
> 
> PR can be merged.

Thank you for testing @mariia-skrypnyk !
