### PR TITLE
Fix swap error when the flow is finished

### LINKED ISSUE #22259: "Cannot read property 'toLowerCase' " error is shown after swap transaction is performed when USD is selected as default currency
Most likely regression of https://github.com/status-im/status-mobile/pull/22245 cc @clauxx 

### Steps:

1. Make sure USD us selected as default currency
1. Perform any swap transaction

### Actual result:
"Cannot read property 'toLowerCase' " error is shown after swap transaction is performed. Issue is reproducible only when USD is selected as default currency. In case any other currence is selected as default the issue will not appear. 

https://github.com/user-attachments/assets/28d4dae2-fcf1-40f1-9741-163a91e3efe3

### Expected result:

No error is shown

### ADDITIONAL INFO:
Although an error is shown, the swap transaction is successful and does not cause any swaps failures

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1xPJH6p2FcP_qGOZVBd336mqDAcK3NW8g/view?usp=drive_link

### ENV:
Release: 5 mar, 2025

### PR DESCRIPTION
**Pull request by clauxx**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #22259

## Summary
[comment]: # (Summarise the problem and how the pull request solves it)
The value was nil when the flow is finished. Added defaults, but we need to improve the cleanup of send/swap flows, since we cleanup before the components manage to un-mount.

[comment]: # (Can be ready or wip)
status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/swap/utils.cljs [hunk 1]
```diff
@@ -67,8 +67,9 @@
...
-       :symbol
-       string/lower-case
-       keyword
-       (get updated-prices)))
+  (some->> token
+           :symbol
+           string/lower-case
+           keyword
+           (get updated-prices)
+           (or 0)))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/swap/utils.cljs]: Just a suggestion:

```suggestion
(when-let [token-symbol (some-> token
                                  :symbol
                                  string/lower-case
                                  keyword)]
    (get updated-prices token-symbol 0)))
```

**Review by smohamedjavid — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @clauxx Thank you for PR. Take a look at a found issue

## PR_ISSUE 1: Conversion is shown as 0 on swap setup page

### Steps:
1. Go to swap
2. Build some swap route (example: DAI -> ETH)
3. Check how the asset is estimated

### Actual result:
The estimated asset value is displayed as 0 (e.g., "1 = 0 DAI").
image


### Expected result:
The estimated asset value should be correctly displayed.


### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1pZxLrfrouRSAEoI-enukJ9ba3lO8XGj7/view?usp=drive_link

**Comment by clauxx** [comment]
@VolodLytvynenko sorry, my mistake. Please check again

**Review by shivekkhurana — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/status_im/contexts/wallet/swap/utils.cljs (hunk 1 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/swap/utils.cljs]: Good point. Thanks!

**Comment by VolodLytvynenko** [comment]
@clauxx Thank you for fixes. No issues from my side. PR can be merged

**Comment by clauxx** [comment]
@vkjr can u merge it please
