### PR TITLE
Fix missing effect and minor refactoring of chat events

### LINKED ISSUE #2426: Same transaction is multiplied on Unsigned screen as many times as user taps on [send]
### Description

*Type*: Bug

*Summary*: in 1x1 chat if I tap on [send] button when sending transaction many times the same txn will be multiplied in Unsigned screen even original one was proceeded. We have simialr issue with /request. I would say its a general problem - need to prevent multi-tapping right after user tapped on [send] once

on iOS Tapping multiple times on Send button makes the app unsuable. Go to 1x1 chat - > /request -> tap ~20 times green send button

https://app.testfairy.com/projects/4803622-status/builds/7170527/sessions/28/?accessToken=tsJMUzhy/tmn6-e-7ZTOenqfgc0

### Reproduction

- Open Status
- Go to 1x1 chat
- Call send command
- Enter valid values and tap green send button several times

OR 
- Open Status
- Go to 1x1 chat
- Call request command

### Additional Information

* Status version: 0.9.10-360-g190e841f+ (1917)
* Operating System: Android, iOS

#### Logs
TF : https://app.testfairy.com/projects/4803622-status/builds/7078352/sessions/9/?accessToken=6ROKNg2tagmBHVilaut8BfEgdyU

### PR DESCRIPTION
**Pull request by yenda**
Cause:
- the conditional branches of :send-current-message event for commands was not applying expected changes to :db because one of the functions transforming the effects map was not returning any db effect in some cases
- :send-current-message effect had effects even when :sending-in-progress? was true

Class of bug: missing effects
This is at least the second time I encounter this class of bugs, this is the easy one with a full effect missing but there is a more vicious variation of this bug when merging effects.

To test:
- chat should work as previously on develop

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

File: src/status_im/chat/events/commands.cljs [hunk 1]
```diff
@@ -41,7 +41,8 @@
             to          (get-in contacts [chat-id :address])
             jail-params {:parameters params
                          :context    (generate-context db chat-id to group-id)}]
-        {:call-jail {:jail-id                 jail-id
+        {:db db
```
Comment (flexsurfer) [inline src/status_im/chat/events/commands.cljs]: somewhere a little perfectionist cries :)

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/chat/events/commands.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/chat/events/commands.cljs]: It depends on the kind of perfectionnist, I consider myself one but I cry everytime I see all these extra spaces everywhere :laughing:

**Review by jeluard — CHANGES_REQUESTED** [review]
Any reason not to split this thing in smaller functions and add tests? That looks like the right place to do it!

At least the bug fixed should have a test.

**Review by jeluard — APPROVED** [review]

**Comment by yenda** [comment]
----------------
Branch: bug/#2426
Android: https://i.diawi.com/ebQKmL
iOS: https://i.diawi.com/CCkY4F

**Comment by churik** [comment]
Issue is reproducible (Android 7.0). 
https://app.testfairy.com/projects/4803622-status/builds/7274719/sessions/3/?accessToken=cMuH/IULPaQzDLqazMT4Nhw1vBk (0:55-01:30)
There are still a lot of transactions on Unsigned screen if you tap several times on blue button with /send command

**Comment by jeluard** [comment]
@churik Can you add the `Tested - Issues` label?

**Comment by churik** [comment]
currently testing of PR is blocked by #2721

**Comment by oskarth** [comment]
@yenda @churik After https://github.com/status-im/status-react/pull/2835 which partially addresses https://github.com/status-im/status-react/issues/2721, is this now unblocked for testing/fixes?

cc @rasom

**Comment by yenda** [comment]
@oskarth should be the case once conflicts are resolved

**Comment by yenda** [comment]
@janherich you made some refactoring to prepare-message so I requested a new review from you for sanity check

**Comment by yenda** [comment]
Tested on real devices and it isn't enough

File: src/status_im/chat/events/input.cljs [hunk 2]
```diff
@@ -439,42 +439,58 @@
...
+      (proceed-command chat-command message-id current-time)))
+
+(defn command-not-complete-fx
+  "command is not complete, just add space after command if necessary"
+  [db input-text]
+  {:db (cond-> db
+         (not (input-model/text-ends-with-space? input-text))
+         (set-chat-input-text constants/spacing-char :append? true))})
+
+(defn no-command-fx
```
Comment (janherich) [inline src/status_im/chat/events/input.cljs]: Not a big deal, but instead of `no-command-fx`, I would rather name this function `text-message-fx` or `plain-message-fx`.

Comment (yenda) [reply src/status_im/chat/events/input.cljs]: ok will fix, but what should we do with this PR ? It works on simulator but on device it has no effect apparently. I guess I could rename it and just consider it a refactor to make this part more readable and take another approach in a new PR ?

Comment (janherich) [reply src/status_im/chat/events/input.cljs]: Sure, it's super minor thing and I still approve the PR as it is, eq without renaming

Comment (oskarth) [reply src/status_im/chat/events/input.cljs]: How about we test + merge and then do other work in new PR?

**Comment by yenda** [comment]
@churik I removed the fix mention as it turns out it doesn't actually fix it on real devices but it is still valuable as it fixes a bug and makes code more readable for further work.

**Comment by oskarth** [comment]
Marking as medium priority for QA, not clear what bug it addresses but doesn't seem to be pure tooling/refactor.

**Comment by oskarth** [comment]
Merged to develop; tested in https://github.com/status-im/status-react/pull/2988 (same commit + 1 other). Cherry picked into release branch.

**Comment by oskarth** [comment]
Merged to develop; tested in https://github.com/status-im/status-react/pull/2988 (same commit + 1 other). Cherry picked into release branch.
