### PR TITLE
fix white screen when navigating back from a channel

### LINKED ISSUE #20313: [iOS] Can't navigate back from a community channel if opened by tag
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
User is navigated back to the community channels list

#### Actual behavior
White screen is shown, after that we need to restart the app 

https://github.com/status-im/status-mobile/assets/29711298/c392850f-22ea-4918-9365-b85bc811917e

### Reproduction

1. Create 2 or more channels in a community (channel-A and channel-B)
2. Navigate to the channel-A and send a message tagging #channel-B 
3. Click on the message with the channel tag to navigate to the channel-B
4. Click back button being inside the channel-B

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by jo-mut**
fixes https://github.com/status-im/status-mobile/issues/20313

### Summary

This issue only happens when the user navigates to a community chat from a community tag inside a chat. The user would be navigated back to the previous chat when the they choose to navigate back but we do not persist reference to the previous chat since that is not inline with the designs hence the white screen.

This pr updates the event that  navigates the user to the new community-chat to pass the `community-id` and instead of `:navigate-back`  replaces this event to navigate back to the community-overview screen with an event to directly just launch the overview screen of the community-id

The video below show the flow without the white screen issue

https://github.com/status-im/status-mobile/assets/28704507/52a33e1d-0746-4ea9-b448-989b37fafa66

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/overview/view.cljs [hunk 1]
```diff
@@ -365,7 +365,7 @@
        :type       :title
        :text-align :left
        :icon-name  :i/close
-       :on-press   #(rf/dispatch [:navigate-back])}]
+       :on-press   #(rf/dispatch [:pop-to-root :shell-stack])}]
```
Comment (Parveshdhull) [inline src/status_im/contexts/communities/overview/view.cljs]: Did you tried pressing hardware back button, instead of close button? I think we will be navigated back to community chat instead of home screen in that case.

File: src/status_im/contexts/chat/messenger/messages/view.cljs [hunk 2]
```diff
@@ -51,10 +52,11 @@
 
 (defn chat
   []
-  (let [chat-screen-layout-calculations-complete? (reanimated/use-shared-value false)
+  (let [community-id                 (rf/sub [:get-screen-params :chats])
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/view.cljs]: Better to move sub where it is used, instead of having in parent view.

File: src/status_im/contexts/chat/messenger/messages/navigation/view.cljs [hunk 3]
```diff
@@ -158,7 +158,9 @@
          :background          button-background
          :size                32
          :accessibility-label :back-button
-         :on-press            #(rf/dispatch [:navigate-back])}
+         :on-press            #(rf/dispatch (if (nil? community-id)
+                                              [:navigate-back]
+                                              [:communities/navigate-to-community-overview community-id]))}
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/navigation/view.cljs]: same hardware back button will break this.

File: src/status_im/contexts/chat/events.cljs [hunk 4]
```diff
@@ -200,9 +200,10 @@
 (rf/defn navigate-to-chat
   "Takes coeffects map and chat-id, returns effects necessary for navigation and preloading data"
   {:events [:chat/navigate-to-chat]}
-  [{db :db :as cofx} chat-id animation]
+  [{db :db :as cofx} chat-id animation community-id]
   (rf/merge cofx
-            {:dispatch [(if animation :shell/navigate-to :navigate-to) :chat chat-id animation]}
+            {:dispatch [(if animation :shell/navigate-to [:navigate-to {:community-id community-id}]) 
+                        :chat chat-id animation]}
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/events.cljs]: I am confused here, how this works :thinking:

**Review by Parveshdhull — COMMENTED** [review]
hi @jo-mut, Thank you for working on the issue.

For a quick solution, maybe we should just navigate-back when tag is pressed and navigate-to desired chat.

We can explore keeping chat screen open later.
(we probably need to update :navigate-to-chat and just remove navigation part when chat is already opened)
(Or you give it a try now, to see if works)

File: src/status_im/contexts/chat/events.cljs (hunk 4 above)
Comment (Parveshdhull) [reply src/status_im/contexts/chat/events.cljs]: oh probably it doesn't work

> we probably need to update :navigate-to-chat and just remove navigation part when chat is already opened

I think this change accidentally created this logic here. Removal of navigation part by not working.

Comment (Parveshdhull) [reply src/status_im/contexts/chat/events.cljs]: In that case, we probably don't need to call `pop-to-root` or `:communities/navigate-to-community-overview` etc. It will just work without them.

File: src/status_im/contexts/chat/events.cljs [hunk 5]
```diff
@@ -200,9 +200,10 @@
 (rf/defn navigate-to-chat
   "Takes coeffects map and chat-id, returns effects necessary for navigation and preloading data"
   {:events [:chat/navigate-to-chat]}
-  [{db :db :as cofx} chat-id animation]
+  [{db :db :as cofx} chat-id animation community-id]
   (rf/merge cofx
-            {:dispatch [(if animation :shell/navigate-to :navigate-to) :chat chat-id animation]}
+            {:dispatch [(if animation :shell/navigate-to [:navigate-to {:community-id community-id}])
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/events.cljs:205]: not directly related to PR, but I think we can also remove `:shell/navigate-to` here

**Comment by jo-mut** [comment]
@Parveshdhull thank you for your suggestions, the issue is fixed now ready for testing

**Review by Parveshdhull — APPROVED** [review]

**Comment by churik** [comment]
e2e tests are not related, store node is down.


Tested on IOS and Android, also checked system back. 

Thank you for PR, ready to merge.
