### PR TITLE
fix pinned message for community channels

### LINKED ISSUE #14875: "Cannot set property 'G_1' of null" when opening pinned messages in channel details
# Bug Report

### Reproduction

1. Create or join a community
2. Open channel list
3. Long tap on the channel > `View details` > `Pinned messages`

#### Expected behavior
No error

#### Actual behavior

https://user-images.githubusercontent.com/67952253/214336520-84692717-c04d-4a72-8056-ea834e6676bf.mp4

### Additional Information

- Status version: nightly 24/01
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/14875

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/events.cljs [hunk 1]
```diff
@@ -324,12 +324,6 @@
                             (rf/dispatch [:bottom-sheet/hide])
                             (rf/dispatch [:chat.ui/remove-chat chat-id]))}})
 
-(rf/defn navigate-to-user-pinned-messages
-  "Takes coeffects map and chat-id, returns effects necessary for navigation and preloading data"
-  {:events [:chat.ui/navigate-to-pinned-messages]}
-  [cofx chat-id]
-  (navigation/navigate-to cofx :chat-pinned-messages {:chat-id chat-id}))
```
Comment (Parveshdhull) [inline src/status_im2/contexts/chat/events.cljs:331]: `:chat-pinned-messages` screen don't exist

File: src/status_im/chat/models/input.cljs [hunk 2]
```diff
@@ -217,20 +217,24 @@
...
+     {:json-rpc/call [{:method      "wakuext_editMessage"
+                       :params      [{:id           message-id
+                                      :text         text
+                                      :content-type (if (message-content/emoji-only-content?
+                                                         {:text text :response-to quoted-message})
+                                                      constants/content-type-emoji
+                                                      constants/content-type-text)}]
+                       :js-response true
+                       :on-error    #(log/error "failed to edit message " %)
+                       :on-success  #(do (re-frame/dispatch [:sanitize-messages-and-process-response %])
```
Comment (ibrkhalil) [inline src/status_im/chat/models/input.cljs]: Please change `#(do` to `(fn []`
https://github.com/bbatsov/clojure-style-guide#no-multiple-forms-in-function-literals

**Review by ibrkhalil — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by yqrashawn — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fix @Parveshdhull, LGTM.
PR can be merged.
