### PR TITLE
Fix keycard login flow options while usign empty keycard

### LINKED ISSUE #22024: "Use as a backup keycard" option incorrectly displayed when logging in with an empty keycard during account restore flow
I believe can be introduced by https://github.com/status-im/status-mobile/pull/21990

### Steps:
1. Go to profile creation flow -> log in -> log in with key card
2. Scan empty key card

### Actual result:
The option "Use as a backup keycard" is displayed when logging in with an empty keycard

https://github.com/user-attachments/assets/ea1df290-63f8-483c-af31-e1a3c49705f5

### Expected result:
https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3369-59917&m=dev

Image

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### LINKED ISSUE #22181: [Android] Continue button is not working after entering a recovery phrase during Backup Keycard flow
# Bug Report

## Problem 
[comment]: # (A problem description)
User can not proceed next after he entered recovery pharse.
Continue is tapable but doesn't lead to the next screen.

### Reproduction

1. Install app
2. Go to `Log in` -> with Keycard
3. Scan empty Keycard
4. Choose `Backup flow`
5. Enter recovery phrase
6. Tap `Continue`

#### Actual behavior

https://github.com/user-attachments/assets/5d9f6931-a5e5-4885-badb-b9c1506cce66

#### Expected behavior

User can go next.

### Additional Information

- Status version: nightly 24/02
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/22024
fixes https://github.com/status-im/status-mobile/issues/22181

https://github.com/status-im/status-mobile/issues/22024#issuecomment-2679140503

>  I think at this point we are okay to show Create profile button to go with implementation shown in your video OR redirect user to "Backup recovery phrase flow" as it matches our current implementation of Create profile flow.

### Video

https://github.com/user-attachments/assets/c5d7fcc9-ef0f-450d-9a09-5fb235d44d94

status: ready

### CODE REVIEW

File: src/status_im/contexts/keycard/error/view.cljs [hunk 1]
```diff
@@ -22,7 +22,9 @@
 
 (defn view
   []
-  (let [error                       (rf/sub [:keycard/application-info-error])
+  (let [error                       (or (rf/sub [:keycard/application-info-error])
+                                        :keycard/error.keycard-empty)
+        logged-in?                  (rf/sub [:multiaccount/logged-in?])
```
Comment (flexsurfer) [inline src/status_im/contexts/keycard/error/view.cljs:26]: empty and non empty screen should be custom in each case, so we won't have general error screen for empty and no need to have some logic here. So now we have to many issues related to this, honestly i would fix them all in one PR in this task https://github.com/status-im/status-mobile/issues/22166 which im working on

File: src/status_im/navigation/effects.cljs [hunk 2]
```diff
@@ -164,9 +164,9 @@
                                                                                  theme)})
                                                options
                                                (when sheet?
-                                                 options/sheet-options))}}]}})
-        (state/navigation-state-push {:id   component
-                                      :type :modal})))))
+                                                 options/sheet-options))}}]}})))
+    (state/navigation-state-push {:id   component
+                                  :type :modal})))
```
Comment (Parveshdhull) [inline src/status_im/navigation/effects.cljs:169]: revert from https://github.com/status-im/status-mobile/pull/22008#discussion_r1939026085

Intended change in that PR: only push the modal to the state when opening it

Side Effect: When we quickly close the old modal and open a new one, we store the new modal in state/dismissing (Line 155) and open it after the old modal has been dismissed. However, when the new modal is opened, the view-id has not been updated yet, which leads to incorrect values for subscriptions such as :get-screen-params. Therefore, we are reverting this change to update the view-id by pushing the modal in state as soon as it is opened.

File: src/status_im/contexts/keycard/error/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/contexts/keycard/error/view.cljs:26]: hi @flexsurfer, Thank you very much for reviewing the PR.

> empty and non empty screen should be custom in each case

Yes, we should have a custom screen for each flow. This will make things simpler and less error-prone.

> I will fix them all in one PR for this task: https://github.com/status-im/status-mobile/issues/22166, which I am currently working on.

Thank you. Once the new custom screens are implemented, these changes will be redundant, and we can simply update the flows to use the new screens. However, for now, we need to make fixes to the already existing implementations.

**Review by flexsurfer — APPROVED** [review]
thanks, as a quick fix for release looks good

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull !

You did a super fix!
Great!

Test report:

- iOS/Android
- What was tested:

1. Onboarding - Login with an empty card
2. Create Profile flow
3. Sign transaction with a Keycard
4. Logout

PR can be merged!
