### PR TITLE
fixes Not visible status bar on light theme

### LINKED ISSUE #21101: [iOS] Not visible status bar on light theme
# Bug Report

#### Actual behavior

Screenshot 2024-08-21 at 13 05 39

#### Expected behavior

Screenshot 2024-08-21 at 13 06 16

### Reproduction

1. Login to app 

### Additional Information

- Status version: release 2.30
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21101

### Summary
The issue occurred because we updated the theme value after setting the root (not before), which caused the root to be initialized with the old theme value.

PR only addresses bug fixing because its urgent. Other improvements related to naming and doc-string are done in https://github.com/status-im/status-mobile/pull/21107

status: ready

### CODE REVIEW

File: src/status_im/navigation/events.cljs [hunk 1]
```diff
@@ -74,6 +74,12 @@
   [{:keys [db]} root-id]
   {:set-root [root-id (:theme db)]})
 
+(rf/defn update-theme-and-init-root
+  {:events [:update-theme-and-init-root]}
+  [_ root-id]
+  {:fx [[:dispatch [:theme/switch {:view-id root-id}]]
```
Comment (ilmotta) [inline src/status_im/navigation/events.cljs:81]: Looks like a proper solution to use ordering from `:fx` 👍🏼, but haven't tested to be sure the fix is good.

File: src/status_im/contexts/onboarding/welcome/view.cljs [hunk 2]
```diff
@@ -45,7 +45,7 @@
           :colors [colors/neutral-100-opa-0 colors/neutral-100-opa-80]}])
       [quo/button
        {:on-press            (fn []
-                               (rf/dispatch [:init-root :shell-stack])
+                               (rf/dispatch [:update-theme-and-init-root :shell-stack])
```
Comment (ilmotta) [inline src/status_im/contexts/onboarding/welcome/view.cljs:48]: It's not the first, nor will be the last time that I think we should have some convention for names of events that are sort of private and should not be used directly. Clearly from now on, dispatching `:init-root` will lead to potential bugs, so something about the name of `:init-root` should indicate that. A comment or docstring is not as potent.

And idea for us to think about :)

**Review by ilmotta — APPROVED** [review]
LGTM, thanks @Parveshdhull

File: src/status_im/contexts/onboarding/welcome/view.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im/contexts/onboarding/welcome/view.cljs:48]: Thank you @ilmotta for reminding. I wrote the docstring, but forget to add before pushing. (Added now)

Comment (Parveshdhull) [reply src/status_im/contexts/onboarding/welcome/view.cljs:48]: Created an issue, we will explore it. Thank you
https://github.com/status-im/status-mobile/issues/21108

**Comment by mariia-skrypnyk** [comment]
@Parveshdhull thanks for fix.

Ready to be merged and cherry-picked.

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull @ilmotta !

I observe the same behaviour on release iOS build.

When user change theme from dark to light the status bar becomes invisible.
It can be fixed by relogin and we discussed it previously. 
But user can not know about it and this issue is low prio but very noticeable. 
Can it be investigated once more?

**Comment by Parveshdhull** [comment]
Hi @mariia-skrypnyk,

Thank you very much for bringing up this issue.

Unfortunately, this is a limitation or bug within the library, and we are currently unable to fix it. You can find more details here: https://github.com/status-im/status-mobile/pull/15596 and https://github.com/status-im/status-mobile/pull/19089

> RNN Bug - We are also changing the status-bar-theme at runtime, but for some reason theme used at the time of root initialization has high priority and gets restored on navigation (going back from chat, etc.)

I’m not certain, but hopefully, if we migrate to the React Navigation library, this issue can be resolved. (Currently out of scope?)

cc @flexsurfer

**Comment by ilmotta** [comment]
> I'm not certain, but hopefully, if we migrate to the React Navigation library, this issue can be resolved. (Currently out of scope?)

Hey @Parveshdhull, to give some visibility here, the scope of 2.32 is still being defined. Just today Volo and I aligned that we need to proactively start to assess from scratch our push notification solution so that by 2.33 we can do something about it because it's very strategic to the success of Status, and it's not currently working in our favor. Another example, next week there will be a call to define the Keycard scope for 2.32. So as you can see, there are other things in the scope and the migration to React Navigation may need to wait a bit longer. Most likely will be in the scope 2.33.
