### PR TITLE
fix(swap): refetch swap proposal when switching account

### LINKED ISSUE #21441: Swap button enabled and approval not shown after account switch on swap page
### Problem:
After switching from Account 1 (which has enough assets and approved ERC-20 tokens) to Account 2 (which has fewer assets and non-approved ERC-20 tokens), the "Review Swap" button remains enabled, and the user can proceed to the confirmation page, even though Account 2 does not have enough assets to complete the transaction. Additionally, the approval button is not displayed for Account 2, despite the ERC-20 token being unapproved.

### Steps:
1, Recover a user with two accounts:
   - `Account 1` has an approved ERC-20 token.
   - `Account 2` has an unapproved ERC-20 token and fewer assets than `Account 1`.
2. Go to the swap page using `Account 1`.
3. Enter a valid value that is sufficient for `Account 1` but insufficient for `Account 2`.
4. Switch to `Account 2`.

### Actual Result:
- The "Review Swap" button remains enabled, and the user can proceed to the confirmation page despite insufficient assets in `Account 2`.
- The `approval` button is missing for `Account 2`, even though the ERC-20 token is unapproved.

https://github.com/user-attachments/assets/057b5779-6608-4eb1-8362-17f73b973c45

### Expected Result:
- The "Review Swap" button should be disabled after switching to an account with insufficient assets.
- The approval button should be displayed for `Account 2` to allow the user to approve the ERC-20 token before swap proceeding.

### ENV:
Nightly 15 Oct 2024

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #21441

### Summary

This PR fixes swap proposal not recalculated when switching accounts, leading to bug as the linked one because of wrong balance data

#### Demo:
https://github.com/user-attachments/assets/db38bc4e-9087-4393-a44f-30097a7d16f6

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

1. Recover a user with two accounts:
   - `Account 1` has an approved ERC-20 token.
   - `Account 2` has an unapproved ERC-20 token and fewer assets than `Account 1`.
2. Go to the swap page using `Account 1`.
3. Enter a valid value that is sufficient for `Account 1` but insufficient for `Account 2`.
4. Switch to `Account 2`.
5. Verify swap proposal is refetched or error state is shown in the amount entered is higher than the switched account balance

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/sheets/select_account/view.cljs [hunk 1]
```diff
@@ -25,12 +28,26 @@
         token                          (->> tokens
                                             (filter #(= (:symbol %) asset-symbol))
                                             first)
-        token-balance                  (get-in token [:balances-per-chain (:chain-id network) :balance])]
+        token-decimals                 (:decimals token)
```
Comment (mohsen-ghafouri) [inline src/status_im/contexts/wallet/sheets/select_account/view.cljs]: it would be great to have a util or data-store func that takes a `token` and returns `token-balance-display`, it will simplify the view logic, as other variables are currently only defined to support that

File: src/status_im/contexts/wallet/events.cljs [hunk 2]
```diff
@@ -69,7 +69,16 @@
...
+   {:db (-> db
+            (assoc-in [:wallet :current-viewing-account-address] address)
+            (update-in [:wallet :ui :swap]
+                       dissoc
+                       :last-request-uuid
+                       :swap-proposal
+                       :error-response
+                       :loading-swap-proposal?
+                       :approval-transaction-id
+                       :approved-amount))}))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/events.cljs]: it's a bit strange that we have "swap specific" functionality in the `:wallet/switch-current-viewing-account` event. Might be better to reset these fields in a declarative way in the input component's `use-effect`, since we already are using it to re-fetch the proposal.

File: src/status_im/contexts/wallet/sheets/select_account/view.cljs [hunk 3]
```diff
@@ -25,12 +28,26 @@
...
+                                         (get-in token
+                                                 [:balances-per-chain
+                                                  (:chain-id network) :raw-balance]
+                                                 0)
+                                         token-decimals))
+        display-decimals               (min token-decimals rounding-decimals)
+        token-balance-display          (number/remove-trailing-zeroes (.toFixed token-balance
+                                                                                display-decimals))
+        token-balance-display          (if (and (= token-balance-display "0")
+                                                (money/greater-than token-balance
```
Comment (clauxx) [inline src/status_im/contexts/wallet/sheets/select_account/view.cljs]: all of this belongs in a subscription, cause the component only needs/uses `token-balance-display`. There are similar changes in [this PR](https://github.com/status-im/status-mobile/pull/21116/files), but for the `send` flow.

File: src/status_im/contexts/wallet/swap/setup_swap/view.cljs [hunk 4]
```diff
@@ -335,12 +335,16 @@
...
         network                                     (rf/sub [:wallet/swap-network])
+        current-account-address                     (rf/sub [:wallet/current-viewing-account-address])
         pay-input-amount                            (controlled-input/input-value pay-input-state)
         pay-token-decimals                          (:decimals asset-to-pay)
         pay-token-balance-selected-chain            (number/convert-to-whole-number
-                                                     (get-in asset-to-pay
+                                                     (get-in asset-to-pay-with-current-account-balance
                                                              [:balances-per-chain
                                                               (:chain-id network) :raw-balance]
                                                              0)
```
Comment (clauxx) [inline src/status_im/contexts/wallet/swap/setup_swap/view.cljs]: some of this should also be moved to subscription(s), otherwise the component becomes difficult to manage. There's a [proposal PR](https://github.com/status-im/status-mobile/pull/21507) that is tackling a similar issue for the send input.

File: src/status_im/contexts/wallet/sheets/select_account/view.cljs [hunk 5]
```diff
@@ -2,11 +2,14 @@
...
             quo.theme
             [react-native.gesture :as gesture]
-            [status-im.contexts.wallet.common.utils :as wallet.utils]
             [status-im.contexts.wallet.sheets.select-account.style :as style]
             [utils.i18n :as i18n]
+            [utils.money :as money]
+            [utils.number :as number]
             [utils.re-frame :as rf]))
 
+(def ^:private rounding-decimals 4)
```
Comment (clauxx) [inline src/status_im/contexts/wallet/sheets/select_account/view.cljs:10]: should this be in `constants`, or is it specific to this screen only?

Comment (briansztamfater) [reply src/status_im/contexts/wallet/sheets/select_account/view.cljs:10]: This is specific for this component, as everywhere else we use 6 decimals

File: src/status_im/contexts/wallet/events.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/events.cljs]: It is weird, actually. I'll come up with a different approach and let you know.

**Review by mohsen-ghafouri — APPROVED** [review]
Nice work, LGTM

File: src/status_im/contexts/wallet/swap/setup_swap/view.cljs (hunk 4 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/swap/setup_swap/view.cljs]: Updated :)

File: src/status_im/contexts/wallet/sheets/select_account/view.cljs (hunk 3 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/sheets/select_account/view.cljs]: Because of token comes from account tokens array, added a utils function, which is also reused in a bunch of new subs used in swaps screen

File: src/status_im/contexts/wallet/events.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/events.cljs]: Updated!

**Review by smohamedjavid — APPROVED** [review]
Nice work!

**Comment by Horupa-Olena** [comment]
Thanks for your PR.

I’m unable to verify the fix because the swap flow is currently blocked by this issue https://github.com/status-im/status-mobile/issues/21555. This prevents testing the entire flow and being confident that the PR is bug-free. Let's temporarily pause work on this PR and return to it after the swap flow issue on the Go side is resolved.

**Review by clauxx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @briansztamfater thank you for PR. No issues from my side. PR can be merged
