### PR TITLE
fix(saved-addresses): clean QR scanned address

### LINKED ISSUE #20667: Address is automatically inserted into the "Watch-only" input field after adding it to saved addresses by scanning QR
# Bug Report

### Reproduction

1. Open Profile > Wallet > Saved addresses > +
2. Scan a QR code with an address, e.g. this one:

Screenshot 2024-07-05 at 16 19 00

3. Save the address
4. Go to wallet
5. Press the plus button > `Add address to watch`

#### Expected behavior
The input field is emty

#### Actual behavior
The address is pre-filled with the saved address

https://github.com/status-im/status-mobile/assets/67952253/a5ddbef2-3e63-4352-96b6-35eda3c7682b

### Additional Information

- Status version: nightly 5/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #20667

### Summary

This PR cleans the scanned QR address/result on the unmount of the add new saved address flow.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to `Profile > Wallet > Saved addresses > +`
- Scan a QR code with an address
- Save the address
- Navigate to the wallet tab
- Press the `+` tile/card then tap on `Add address to watch`
- Verify the scanned address is not populated in the input field

status: ready

### CODE REVIEW

File: src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs [hunk 1]
```diff
@@ -163,9 +163,8 @@
                                                (rf/dispatch
                                                 [:open-modal :screen/settings.save-address]))
                                              [address ens-name? address-or-ens])]
-    (rn/use-mount (fn []
-                    (rf/dispatch [:wallet/clean-scanned-address])
-                    (rf/dispatch [:wallet/clear-address-to-save])))
+    (rn/use-unmount #(rf/dispatch [:wallet/clean-scanned-address]))
```
Comment (smohamedjavid) [inline src/status_im/contexts/settings/wallet/saved_addresses/add_address_to_save/view.cljs:166]: Moved to unmount as we already clean the scanned address on navigating to scanner screen in saved-address

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @smohamedjavid !

Thanks for your PR!
Your fix looks good on both platforms.
Failed e2e are known and not related.
You can merge it 🙌
