### PR TITLE
Fix composer height overflow with extra content

### LINKED ISSUE #15949: Composer grows beyond max height
# Problem

Composer grows beyond the correct maximum height when the text is long and there are images or link previews at the bottom. Originally reported by @pavloburykh in this comment https://github.com/status-im/status-mobile/pull/15891#issuecomment-1552900157

[bug.webm](https://github.com/status-im/status-mobile/assets/46027/6be113d1-e753-438b-ba20-8798571bc2c4)

### Cause

It looks as if the initial max height is not being updated in *some* place, because as we can see from the video, minimizing and maximizing the composer still reuses the same, incorrect max height.

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/15949

### Summary

This PR fixes the maximum height overflow of the composer when there are images and/or link previews (any *extra content* as we call it in the code).

### Cause

The bug happened because the `on-focus` event of the composer happens before subscriptions arrive, and thus it uses the incorrect `max-height`.

Bug demo:

[bug-composer-with-image-and-long-text.webm](https://github.com/status-im/status-mobile/assets/46027/31940e18-6a8c-4d87-94af-a8b6c44ed51d)

### Fix

The fix makes the animation values of `height`, `last-height`, and `saved-height` be truncated based on the newest calculated `max-height`, and they happen in a separate `use-effect`, outside of the `on-focus` event.

This solution also works when link previews are loaded after `on-focus` is triggered automatically when the chat opens, whereas from inside `on-focus` the *seen* `max-height`  is outdated (which leads to the bug).

[fixed.webm](https://github.com/status-im/status-mobile/assets/46027/7bf366ad-c2b5-4d68-ba60-9976aaee8713)

#### Platforms

- Android
- iOS

### Steps to test

Paste a handful of lines to stretch out the composer closer to the max height and add images and/or link previews. You should *not* see the composer height overflowing.

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/composer/effects.cljs [hunk 1]
```diff
@@ -105,9 +105,23 @@
...
   (.remove ^js @keyboard-frame-listener))
 
+(defn max-height-effect
+  [{:keys [focused?]}
+   {:keys [max-height]}
+   {:keys [height saved-height last-height]}]
+  (rn/use-effect
+   (fn []
+     (when @focused?
+       (let [new-last-height (min max-height (reanimated/get-shared-value last-height))]
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/composer/effects.cljs]: can be renamed to `new-height`. 

Also, are you sure this statement is needed? Setting the height and saved-height to value of last-height in the effect instead of on-focus isn't sufficient?

**Review by OmarBasem — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/chat/composer/effects.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/contexts/chat/composer/effects.cljs]: > can be renamed to new-height.

Will do it :)

> Also, are you sure this statement is needed? Setting the height and saved-height to value of last-height in the effect instead of on-focus isn't sufficient?

Indeed @OmarBasem. The critical difference is that this effect runs when `max-height` OR `focused?` are changed, whereas `on-focus` runs only when it needs to focus and that means that it would not be using the most up-to-date max-height value because the `max-height` is calculated *slightly* after `on-focus` runs (right after subscriptions are changed).

It's easy to see:

1. Paste a large text and one unfurleable URL or an add an image.
2. Go out of the chat.
3. Open the chat again. The `on-focus` event will be triggered before the link preview or image subscription arrives. That means `on-focus` will use the outdated `max-height` and whatever happens inside `on-focus` won't react to the new `max-height` value, and that's why the UI will look broken.

Edit: None of this is obvious and I missed this problem while reviewing the new composer PRs.

Comment (ilmotta) [reply src/status_im2/contexts/chat/composer/effects.cljs]: Renamed and added a quick comment in the code. https://github.com/status-im/status-mobile/pull/15989/commits/3e8b7620bb92fe91704bc528d028697f53cc6331

Comment (OmarBasem) [reply src/status_im2/contexts/chat/composer/effects.cljs]: Thanks for the clarification! :)
