### PR TITLE
[#19516] Fix bridge flow bugs

### LINKED ISSUE #19516: Wallet - Skip steps while bridging an asset picked from an account overview
This issue is the continuation of #19410  but for bridging an asset.

### LINKED ISSUE #20106: Wallet - "Send to" flow after pressing “Confirm bridge”
# Bug Report

## Problem 

The user is redirected to the `Send to` page after pressing `Confirm bridge` instead of the bridge confirmation page. 
UI is broken when going back to the amount page. 

#### Expected behavior

https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=10232-108495&m=dev

Screenshot 2024-05-20 at 11 29 31

#### Actual behavior

https://github.com/status-im/status-mobile/assets/67952253/5d180d73-eba1-48b3-aff9-2f5ba183bef4

### Reproduction

1. Open wallet
2. Open an account
3. Press `Bridge`
4. Select asset
5. Select network
6. Enter amount
7. Press `Confirm bridge`

### Additional Information

- Status version: nightly 20/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #19516  
fixes #20106

## Summary

This PR fixes some bugs existing in the bridge flow:

### 1. "Bridge to" not showing

Develop:

[Screencast from 2024-05-27 10-53-51.webm](https://github.com/status-im/status-mobile/assets/90291778/54ac1f33-b9cf-4d27-a3b9-9bda9a73094a)

PR:

[Screencast from 2024-05-27 15-46-38.webm](https://github.com/status-im/status-mobile/assets/90291778/0428941d-bae9-4e9f-8ee8-4efb16a0707a)

### 2. Send flow appears while bridging

Please check #20106

### 5. Stale data shown in suggested routes

Develop:

[Screencast from 2024-05-27 11-26-22.webm](https://github.com/status-im/status-mobile/assets/90291778/f9771d33-c730-4c24-bbf4-3a920455172d)

PR:

[Screencast from 2024-05-27 16-05-57.webm](https://github.com/status-im/status-mobile/assets/90291778/58e18a1d-1191-4a89-8429-6576ab6cdf0f)

### 6. Support for the bridge flow starting in the wallet home screen

Develop:

[Screencast from 2024-05-27 11-35-53.webm](https://github.com/status-im/status-mobile/assets/90291778/e585cec2-649d-4f68-9400-2eaf6079ded9)

PR:

[Screencast from 2024-05-27 16-07-19.webm](https://github.com/status-im/status-mobile/assets/90291778/f5fd8209-eec6-4940-84bd-3f240e255bbd)

(Sorry, today I can't get the routes suggested to check the whole flow)

[comment]: # (Summarise the problem and how the pull request solves it)

#### Platforms

- Android
- iOS

### Steps to test

Please confirm the issues in the videos are solved and that we can successfully bridge in all cases.

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/contexts/wallet/account/view.cljs [hunk 1]
```diff
@@ -32,7 +32,9 @@
         [rn/view {:style {:flex 1}}
          [account-switcher/view
           {:type     :wallet-networks
-           :on-press #(rf/dispatch [:wallet/close-account-page])}]
+           :on-press (fn []
+                       (rf/dispatch [:wallet/clean-send-data])
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/account/view.cljs]: why we would do this here? 🤔

Comment (J-Son89) [reply src/status_im/contexts/wallet/account/view.cljs]: should this cleanup not go in the close-account-page event?

Comment (ulisesmac) [reply src/status_im/contexts/wallet/account/view.cljs]: To remove the remaining data. In the flow:

Account page -> Long press token to bridge -> Bridge -> Back.

The token selected to send is still in the DB.

We can't remove the token when going back from the `Bridge <TOKEN> to` screen because it will break the flow when we start from the bridge button in the CTAs.

Comment (J-Son89) [reply src/status_im/contexts/wallet/account/view.cljs]: Thanks 🙏

Comment (ulisesmac) [reply src/status_im/contexts/wallet/account/view.cljs]: > should this cleanup not go in the close-account-page event?

Yes, I can dispatch it inside too, I'll update it, thanks for spotting it :+1:

File: src/status_im/contexts/wallet/bridge/flow_config.cljs [hunk 2]
```diff
@@ -1,7 +1,9 @@
 (ns status-im.contexts.wallet.bridge.flow-config)
 
 (def steps
-  [{:screen-id  :screen/wallet.bridge-select-asset
+  [{:screen-id  :screen/wallet.select-from
+    :skip-step? (fn [db] (some? (get-in db [:wallet :current-viewing-account-address])))}
+   {:screen-id  :screen/wallet.bridge-select-asset
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/bridge/flow_config.cljs:6]: Added the screen to pick the sender for the bridge flow

File: src/status_im/contexts/wallet/bridge/input_amount/view.cljs [hunk 3]
```diff
@@ -13,7 +13,12 @@
     {:current-screen-id :screen/wallet.bridge-input-amount
      :button-one-label  (i18n/label :t/review-bridge)
      :button-one-props  {:icon-left :i/bridge}
+     :on-confirm        (fn [amount]
+                          (rf/dispatch [:wallet/set-token-amount-to-bridge
+                                        {:amount   amount
+                                         :stack-id :screen/wallet.bridge-input-amount}]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/bridge/input_amount/view.cljs:20]: This change is needed to fix the jump between the bridge -> send flow.

File: src/status_im/contexts/wallet/common/token_value/view.cljs [hunk 4]
```diff
@@ -65,24 +65,25 @@
...
                   (action-manage-tokens watch-only?))
                 (when (ff/enabled? ::ff/wallet.assets-modal-hide)
                   (action-hide))]
         (not watch-only?) (concat [(action-buy)
-                                   (action-send send-params)
+                                   (action-send send-or-bridge-params)
                                    (action-receive)
                                    (when (ff/enabled? ::ff/wallet.swap) (action-swap))
-                                   (action-bridge token-data)]))]]))
+                                   (action-bridge send-or-bridge-params)]))]]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/common/token_value/view.cljs]: Needed to add support to brdinge from home screen

File: src/status_im/contexts/wallet/events.cljs [hunk 5]
```diff
@@ -220,12 +220,14 @@
...
-              (assoc-in [:wallet :ui :send :to-address] to-address)
-              (assoc-in [:wallet :ui :send :tx-type] :tx/bridge))
+ (fn [{:keys [db]} [{:keys [token token-symbol stack-id]}]]
+   (let [missing-recipient? (-> db :wallet :ui :send :to-address nil?)
+         to-address         (-> db :wallet :current-viewing-account-address)]
+     {:db (cond-> db
+            :always            (assoc-in [:wallet :ui :send :tx-type] :tx/bridge)
+            token              (assoc-in [:wallet :ui :send :token] token)
+            token-symbol       (assoc-in [:wallet :ui :send :token-symbol] token-symbol)
+            missing-recipient? (assoc-in [:wallet :ui :send :to-address] to-address))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events.cljs:269]: When we bridge from the home screen, we don't know to which account we will bridge, on the other hand, when we visit an account page we already know it, this change makes this event reusable for both flows

File: src/status_im/contexts/wallet/send/events.cljs [hunk 6]
```diff
@@ -197,8 +197,8 @@
    (let [{token-networks :networks}                token
          receiver-networks                         (get-in db [:wallet :ui :send :receiver-networks])
          token-networks-ids                        (mapv #(:chain-id %) token-networks)
-         token-not-supported-in-receiver-networks? (not (some (set receiver-networks)
-                                                              token-networks-ids))]
+         token-not-supported-in-receiver-networks? (not-any? (set receiver-networks)
+                                                             token-networks-ids)]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:201]: Just an idomatic change, same logic

File: src/status_im/contexts/wallet/send/events.cljs [hunk 7]
```diff
@@ -622,23 +645,26 @@
...
+                               (assoc token
+                                      :networks      (network-utils/network-list token network-details)
+                                      :total-balance (utils/calculate-total-token-balance token))))
+         bridge-tx?        (= tx-type :tx/bridge)
+         flow-id           (if bridge-tx?
+                             :wallet-bridge-flow
+                             :wallet-send-flow)]
+     {:db (cond-> db
+            token-symbol (assoc-in [:wallet :ui :send :token] token)
+            bridge-tx?   (assoc-in [:wallet :ui :send :to-address] address))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:674]: Just makes this event reusable, it was used for sending, now it's also possible to use it for bridging

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 8]
```diff
@@ -30,51 +30,54 @@
...
          (i18n/label :t/send))]
       [quo/summary-tag
-       {:token        (if collectible? "" token-display-name)
-        :label        (str amount " " token-display-name)
-        :type         (if collectible? :collectible :token)
-        :image-source (if collectible? image-url :eth)}]]
+       (cond-> {:token (if collectible? "" token-display-name)
+                :label (str amount " " token-display-name)
+                :type  (if collectible? :collectible :token)}
+         collectible? (assoc :image-source image-url))]]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:36]: Previously we had `:image-source` receiving `:eth` which is not a valid image source, now is fixed so when we bridge the  token image is properly displayed

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 9]
```diff
@@ -30,51 +30,54 @@
...
-                  :image-source        (:source network)
-                  :customization-color network-color}]])]))
-        route)
+       (doall
+        (map-indexed
+         (fn [idx path]
+           (let [from-network             (:from path)
+                 chain-id                 (:chain-id from-network)
+                 network                  (rf/sub [:wallet/network-details-by-chain-id
+                                                   chain-id])
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:44]: the `rf/sub` has a `deref` hidden inside, and we were using it inside a lazy seq (returned by `map-indexed`) so we had a warning, adding a `doall` sovles the problem :)

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 10]
```diff
@@ -30,51 +30,54 @@
...
+                 network-name             (:network-name network)
+                 network-name-text        (name network-name)
+                 network-name-capitalized (when (seq network-name-text)
+                                            (string/capitalize network-name-text))
+                 network-color            (if (= network-name :mainnet) :ethereum network-name)]
+             (with-meta
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:50]: We were returning a lazy seq without react keys set, so I added the `with-meta` function to get rid of the warning

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 11]
```diff
@@ -126,15 +129,18 @@
...
+                          (let [network-name    (network-utils/id->network chain-id)
+                                network-keyword (if (= network-name :mainnet)
+                                                  :ethereum
+                                                  network-name)]
+                            (assoc acc
+                                   network-keyword
+                                   {:amount       amount
+                                    :token-symbol token-display-name})))
+                        {}
+                        network-values)]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:143]: Just a code refactor

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs [hunk 12]
```diff
@@ -222,6 +227,8 @@
                                            (get-in collectible [:preview-url :uri]))
             transaction-type             (:tx-type send-transaction-data)
             estimated-time-min           (reduce + (map :estimated-time route))
+            token-symbol                 (or token-display-name
+                                             (-> send-transaction-data :token :symbol))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:219]: In the bridge flow we aren't passing `token-display-name` so we extract the token value from the transaction data, by doing this we are able to display the token symbol and the token image in the transaction confirmation screen

File: src/status_im/contexts/wallet/account/view.cljs (hunk 1 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/account/view.cljs]: @ulisesmac `(rf/dispatch [:wallet/clean-send-data])` needs to be inside the `unmount`, and the x button on-press should just be `navigate-back`. Please see this PR https://github.com/status-im/status-mobile/pull/20183/

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs (hunk 12 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:219]: The default value extracts the symbol from token, could this lead to bugs if token is not set (because user is sending a collectible, for example?

**Review by briansztamfater — APPROVED** [review]

File: src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs (hunk 12 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/transaction_confirmation/view.cljs:219]: The worst case is when the data doesn't exist and `token-symbol` would be `nil`, the same as before this fix.

BTW, I tested with collectibles and everyhing is looking good.

Another thing is that this screen seems to need a refactor, mainly to make clear enough what is the data needed in each flow since this screen is being reused multiple times

File: src/status_im/contexts/wallet/account/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/account/view.cljs]: @OmarBasem Thanks, I'll check it :+1:

Comment (ulisesmac) [reply src/status_im/contexts/wallet/account/view.cljs]: Done :+1:

**Comment by ulisesmac** [comment]
@J-Son89 @OmarBasem I addressed the comments, could you please review again?
Thank you

File: src/status_im/contexts/wallet/account/view.cljs [hunk 13]
```diff
@@ -28,11 +28,14 @@
...
-        (rn/use-unmount #(rf/dispatch [:wallet/close-account-page]))
+        (rn/use-unmount (fn []
+                          (rf/dispatch [:wallet/close-account-page])
+                          (rf/dispatch [:wallet/clean-send-data])))
         [rn/view {:style {:flex 1}}
          [account-switcher/view
           {:type     :wallet-networks
-           :on-press #(rf/dispatch [:wallet/close-account-page])}]
+           :on-press (fn []
+                       (rf/dispatch [:wallet/close-account-page]))}]
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/account/view.cljs]: This would be `#(rf/dispatch navigate-back)` as now we are already dispatching `wallet/close-account-page` on unmount

**Review by OmarBasem — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im/contexts/wallet/account/view.cljs (hunk 13 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/account/view.cljs]: I think  we don't need `navigate-back` and  `close-account-page` together since `close-account-page` already goes to the root of the navigation.

So I'll keep the `on-press` as is, and the use-effect will look as:

`(rn/use-unmount #(rf/dispatch [:wallet/clean-send-data]))`

Comment (ulisesmac) [reply src/status_im/contexts/wallet/account/view.cljs]: I'll rever the suggested changes because of:
- https://github.com/status-im/status-mobile/pull/20183#discussion_r1619394309

**Comment by qoqobolo** [comment]
Hey @ulisesmac, could you pls resolve the conflict and rebase the branch? Thanks!

**Comment by ulisesmac** [comment]
> Hey @ulisesmac, could you pls resolve the conflict and rebase the branch? Thanks!

@qoqobolo  Done! :)

**Comment by VolodLytvynenko** [comment]
blocked by https://github.com/status-im/status-mobile/issues/20406

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac thank you for catching and issue fixing. 

Here is one more issue related to the navigation. But would be ok if better to fix in follow up

## ISSUE 1: [Android] The confirmation bridging page is shown instead of routes generation screen if hardware back button is previously used

### Steps: 
1. Go to the confirmation bridging page
2. Go back to 'Bridge to' page using the hardware back button or use the back gesture
3. Select any network

### Actual result:
User is navigated to the confirmation bridging page, skipping the routes generation page

https://github.com/status-im/status-mobile/assets/52490791/6ad2d008-ad77-45c4-b77e-c215d019d90f

### Expected result:
User is navigated to the routes navigation page

### Devices:
- Pixel 7a, Android 13

**Comment by VolodLytvynenko** [comment]
@ulisesmac No other issues from my side that can be related to this PR. If issue 1 is fixed within the scope of this PR, then it can be merged.

**Comment by ulisesmac** [comment]
> @ulisesmac No other issues from my side that can be related to this PR. If issue 1 is fixed within the scope of this PR, then it can be merged.

Hey @VolodLytvynenko this is due to not cleaning the state when we navigate back by another mechanism that is not pressing the back button in the UI (it can be by OS gestures or the hardware button).

This issue is present in all the wallet, and we have a potential a PR for it:
- https://github.com/status-im/status-mobile/pull/20183

So I'd say it's out of scope of this PR.

-------------
Can this PR be merged then?

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac sure. PR can be merged. Thank you!
