### PR TITLE
fix: image actions

### LINKED ISSUE #14979: Long/single tap on pictures doesn't work correctly in chat; cannot open menu/set reaction
# Bug Report

## Problem 

Interaction with pictures in chat does not work correctly again. The desired behavior is described below.
Correct behavior was added in [this PR](https://github.com/status-im/status-mobile/pull/14911/files), however the issue has returned since nightly 02/02.

#### Expected behavior

Long tap (to open action menu) works on:
- whole message area (space around the picture)
- picture itself

Single tap (to open picture) works on:
- only picture itself

https://user-images.githubusercontent.com/67952253/216579520-bd34fd2a-ade0-4774-987b-7029edce2c5d.mp4

#### Actual behavior

1. Long press doesn't work on pictures at all -> Cannot open the action menu
2. Single tap works both on the message area (space around the picture - **not expected**) and on the picture itself (**expected**)

https://user-images.githubusercontent.com/67952253/216579591-c53c24f1-74a9-4425-a9b2-787a289764d5.mp4

### Reproduction

1. Send a picture in a chat
2. Try long and single tap

### Additional Information

- Status version: since nightly 02/02 (worked fine on nightly 01/02)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/14979, https://github.com/status-im/status-mobile/issues/14920

This PR fixes action drawer not showing on-long-press for images, and fixes reactions not being delivered.

Action drawer and reactions for albums are currently blocked: https://github.com/status-im/status-mobile/issues/14995

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/content/reactions/view.cljs [hunk 1]
```diff
@@ -28,8 +30,12 @@
             :accessibility-label (str "emoji-reaction-" emoji-id)}]])
        [quo/add-reaction
         {:on-press (fn []
-                     (rf/dispatch [:dismiss-keyboard])
-                     (rf/dispatch
-                      [:bottom-sheet/show-sheet
-                       {:content (fn [] [drawers/reactions
-                                         {:chat-id chat-id :message-id message-id}])}]))}]])))
+                     ;; an album, issue: https://github.com/status-im/status-mobile/issues/14995
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/reactions/view.cljs]: The wording here is difficult to grasp. I had to open the issue to understand what this comment means. Since the issue already exists, you could remove this comment as well.

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 2]
```diff
@@ -136,20 +139,22 @@
                constants/content-type-sticker [not-implemented/not-implemented
                                                [old-message/sticker message-data]]
 
-               constants/content-type-image   [image/image-message 0 message-data context]
-
                constants/content-type-audio   [not-implemented/not-implemented
                                                [old-message/audio message-data]]
 
-               constants/content-type-album   [album/album-message message-data context]
+               constants/content-type-image   [image/image-message 0 message-data context on-long-press]
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: Just a reminder that in the `status-mobile` codebase we often add a newline between the condition and its action. It helps reduce diffs due to left alignment of the conditions and it helps reduce unnecessarily long lines.

```clojure
(case content-type
  constants/content-type-text
  [not-implemented/not-implemented
   [content.text/text-content message-data context]]

  constants/content-type-emoji
  [not-implemented/not-implemented
   [old-message/emoji message-data]])
```

File: src/status_im2/contexts/chat/messages/content/view.cljs [hunk 3]
```diff
@@ -136,20 +139,22 @@
...
+
+               constants/content-type-album   [album/album-message message-data context on-long-press]
 
                [not-implemented/not-implemented [content.unknown/unknown-content message-data]])
              (when @show-delivery-state?
                [status/status outgoing-status])]]]])))])
 
+
+
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/content/view.cljs]: Extra line. @yqrashawn, do you know if we can configure zprint to change 2+ consecutive lines to be just one newline? I see this styling issue in lots of PRs, so it'd be nice to automate.

File: src/status_im2/subs/chat/messages.cljs [hunk 4]
```diff
@@ -112,16 +112,32 @@
...
-                   albums   (cond-> albums album-id (update album-id conj message))
-                   messages (if album-id
-                              (conj (filterv #(not= album-id (:album-id %)) messages)
-                                    {:album        (get albums album-id)
-                                     :album-id     album-id
-                                     :albumize?    (:albumize? message)
-                                     :message-id   album-id
-                                     :content-type constants/content-type-album})
-                              (conj messages message))]
+             (let [album-id  (:album-id message)
```
Comment (ilmotta) [inline src/status_im2/subs/chat/messages.cljs]: This subscription is pretty heavy in logic, but I only see one test with one assertion. Could you add a couple more tests for this subscription? The reasoning is simple, if another contributor wants to change this subscription, that person will need to manually retest all the conditions, and this is no joke for the amount of things going on here.

File: src/status_im2/contexts/chat/messages/content/album/style.cljs [hunk 5]
```diff
@@ -14,12 +14,12 @@
    :overflow       :hidden})
 
 (defn image
-  [dimensions index portrait?]
+  [dimensions index portrait? count]
```
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/messages/content/album/style.cljs]: Can we rename this var `count` to avoid confusion with `clojure.core/count` ?

File: src/status_im2/contexts/chat/messages/content/reactions/view.cljs [hunk 6]
```diff
@@ -6,8 +6,10 @@
             [status-im2.contexts.chat.messages.drawers.view :as drawers]))
 
 (defn message-reactions-row
-  [chat-id message-id]
-  (let [reactions (rf/sub [:chats/message-reactions message-id chat-id])]
+  [chat-id message-id messages-ids]
+  (let [reactions (if messages-ids
+                    (apply concat (mapv #(rf/sub [:chats/message-reactions % chat-id]) messages-ids))
```
Comment (ibrkhalil) [inline src/status_im2/contexts/chat/messages/content/reactions/view.cljs]: Why do we need to use `mapv` and not `map` ?

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/content/reactions/view.cljs]: Good catch @ibrkhalil. The answer is a bit more involved.

`mapv` is the eager version of `map`, non-lazy, which means it's suitable for mapping over collections with side-effects like deref'ing an atom. But `concat` will return a lazy version of the new collection, so using `concat` *might be* pointless when used after `mapv`, and it really is in this example you pointed out.

Example:

```clojure
;; Notice concat doesn't return a vector and the type is `LazySeq`.
(concat [1 2 3]
        [4 5 6]) ; => (1 2 3 4 5 6)
```

But looking further, this code doesn't need the `apply concat` followed by `mapv`, we have the function `mapcat`.

See, both of the examples below do the same, but I find the `mapcat` version better. `mapcat` is a very useful function in many situations :)

```clojure
(apply concat [[:a :b]
               [:c :d]
               [:e :f]])

(mapcat identity [[:a :b]
                  [:c :d]
                  [:e :f]])

;; They both return (lazy structure)
;; (:a :b :c :d :e :f)
```

So to me, the final answer should be just:

```clojure
(mapcat #(rf/sub [:chats/message-reactions % chat-id]) messages-ids)
```

File: src/status_im2/contexts/chat/messages/content/album/style.cljs (hunk 5 above)
Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/content/album/style.cljs]: I agree, I usually avoid shadowing this core function given how often we use it.

File: src/status_im2/contexts/chat/messages/content/reactions/view.cljs (hunk 6 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/reactions/view.cljs]: So mapv will evaluate the sequence, but it's useless because concat will eventually return a LazySeq.
mapcat looks right to me here ..

Comment (ilmotta) [reply src/status_im2/contexts/chat/messages/content/reactions/view.cljs]: Exactly, Omar needs to create a flat list of reaction maps, but each deref'ed subscription returns an array. `mapcat` should do the job and it should perform better as well than `mapv` + `apply concat`.

Comment (OmarBasem) [reply src/status_im2/contexts/chat/messages/content/reactions/view.cljs]: Thanks @ilmotta for the explanation!

File: src/status_im2/subs/chat/messages.cljs (hunk 4 above)
Comment (OmarBasem) [reply src/status_im2/subs/chat/messages.cljs]: You are right. I have updated the test.

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/subs/chat/messages.cljs (hunk 4 above)
Comment (ilmotta) [reply src/status_im2/subs/chat/messages.cljs]: Thank you! :flying_saucer: :rocket:

**Comment by OmarBasem** [comment]
Hi @qoqobolo, PR is ready to be tested. Thanks!

**Comment by qoqobolo** [comment]
Hey @OmarBasem, thanks!
Just to make sure, is it rebased on the latest develop? If not, rebase it, please.

**Comment by OmarBasem** [comment]
> Hey @OmarBasem, thanks! Just to make sure, is it rebased on the latest develop? If not, rebase it, please.

It is rebased!

**Comment by qoqobolo** [comment]
@OmarBasem can you pls rebase again? Jakub just pushed the fix for e2e.
Thanks!

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/content/view.cljs (hunk 3 above)
Comment (yqrashawn) [reply src/status_im2/contexts/chat/messages/content/view.cljs]: Seems there's no way to do that with zprint for now. It's possible to force 1 blank line between all top-level form, not possible to format 2+ consecutive blank lines to 1 blank line.

**Comment by OmarBasem** [comment]
@qoqobolo Done!

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem thanx for the PR. The issue related to reactions is fixed. Here the list of found issues:

**ISSUE 1: "Action drawer for albums is not supported yet" is shown after a long press on the set of sent images**
**Steps to reproduce:**
1. Go to 1-1 chat -> open image selector -> select at least 2 images -> confirm selection -> send
2. Reopen the chat (only after this step the images will be sorted)
3. Long press on the sorted set of images

**Actual result:**
"Action drawer for albums is not supported yet" message is shown

https://user-images.githubusercontent.com/52490791/217501372-ab07de93-6026-414c-b37a-7eb26e74fdaa.mp4


**Expected result:**
Action drawer is shown

**ISSUE 2: Images are not sorted correctly**
**Steps to reproduce:**
1. Go to 1-1 chat -> open image selector -> select 6 images -> confirm selection -> send
3. Reopen the chat (only after this step the images will be sorted)

**Actual result:**
6 images
image

4 images
image

5 images
image


**Expected result:**
How it is shown on today's nightly. (I use the same images and the same device)
image

**Additional info:**
We have a separate ticket  https://github.com/status-im/status-mobile/issues/14840 related to wrong image sorting for some particular Android devices. But this is another issue where it is reproduced for both IOS and Androids devices as well

**ENV:** Huawei p20 light, OS version 9; iPhone 11 Pro Max, OS version 15

**Comment by OmarBasem** [comment]
Hi @VladimrLitvinenko, thanks for your reviews.

Issue 1: as it says, the action drawer for albums is not supported yet. It requires design input. Please check [PR description](https://github.com/status-im/status-mobile/pull/14996#issue-1572446938). 

Issue 2: fixed.

**Comment by VladimrLitvinenko** [comment]
> Hi @VladimrLitvinenko, thanks for your reviews.
> 
> Issue 1: as it says, the action drawer for albums is not supported yet. It requires design input. Please check [PR description](https://github.com/status-im/status-mobile/pull/14996#issue-1572446938).
> 
> Issue 2: fixed.

Got it. Thank you for fixes. No issues from my side. Could you merge this PR please?

**Comment by VolodLytvynenko** [comment]
@OmarBasem don't merge it please yet. need to check e2e tests

**Comment by OmarBasem** [comment]
@VladimrLitvinenko is it okay to merge now or what?

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko is it okay to merge now or what?

@OmarBasem just a moment. Some issues are detected by e2e tests, but @churik is trying to figure out if is it a problem with PR or some e2e configuration. Apologies for this delay. I let you know if everything is ok

**Comment by VolodLytvynenko** [comment]
@OmarBasem thank you for your patience, again :) e2e issues are not related to this PR. Could you merge it, please?

**Comment by OmarBasem** [comment]
Thank you @VladimrLitvinenko
