### PR TITLE
Fixed an issue with uninstalling non-active extensions

### LINKED ISSUE #6780: 'No protocol method...' error when trying to delete disabled extension
***Type***: Bug

There is no way to delete installed Extension when a user disabled it: `No protocol method Command.id defined for type null:` error appears.
In a case when an extension is enabled - it could be removed fine. 

#### Expected behavior
Extension deleted

#### Actual behavior
`No protocol method Command.id defined for type null:` error appears when I tap 'Delete' icon on disabled extension

screenshot 2018-11-19 at 18 35 39

 
### Reproduction

- Open Status and create new account
- Install the extension (e.g. you can use this one https://get.status.im/extension/ipfs@QmTfL8CBKGr2MYFP1NEHwsQrkDbZRHsTeJc9zjBfYqboNN)
- Navigate to 'Extensions' store list
- Unckeck checkmark on an installed extension so the last is disabled
- Swipe-left on extension item
- Tap red 'Delete' icon

### Additional Information
* Status version: delevop 0.9.31 (12620)
* Operating System: Android and iOS

<blockquote></blockquote>

### PR DESCRIPTION
**Pull request by FrederikBolding**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #6780 

### Summary:

Fixed an issue with uninstalling non-active extensions - The issue was that the non-active extensions were being attempted to be unhooked, but as they weren't active they had already been unhooked.

### Steps to test:
- Open Status
- Enable dev mode
- Go to extensions
- Install an extension
- Disable the extension
- Uninstall the extension and see that it is removed successfully

status: ready

### CODE REVIEW

File: src/status_im/extensions/registry.cljs [hunk 1]
```diff
@@ -29,10 +29,12 @@
...
 
 (fx/defn remove-from-registry
-  [{:keys [db] :as cofx} extension-key]
-  (fx/merge cofx
-            (update-hooks hooks/unhook extension-key)
-            {:db (update-in db [:account/account :extensions] dissoc extension-key)}))
+  [cofx extension-key]
+  (let [extensions     (get-in cofx [:db :account/account :extensions])]
+    (fx/merge cofx
+              (if (get-in extensions [extension-key :active?])
```
Comment (jeluard) [inline src/status_im/extensions/registry.cljs]: Could you use a when instead of the if?

File: src/status_im/extensions/registry.cljs [hunk 2]
```diff
@@ -29,10 +29,12 @@
               (update-hooks hooks/hook-in extension-key))))
 
 (fx/defn remove-from-registry
-  [{:keys [db] :as cofx} extension-key]
-  (fx/merge cofx
-            (update-hooks hooks/unhook extension-key)
-            {:db (update-in db [:account/account :extensions] dissoc extension-key)}))
+  [cofx extension-key]
+  (let [extensions     (get-in cofx [:db :account/account :extensions])]
```
Comment (jeluard) [inline src/status_im/extensions/registry.cljs]: Please remove the extra spaces :)

**Comment by FrederikBolding** [comment]
@jeluard There you go! Small formatting issues should be fixed 😄

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]
