### PR TITLE
[#17207] fix: incorrect mentions alignment in messages

### LINKED ISSUE #17207: Incorrect mentions alignment
**Steps:** 

1. Send text + mention in any chat
2. Check if mention text bottom is aligned to regular text bottom

**Actual result:**  mention text bottom is not aligned to the regular text bottom

**IOS:**
photo_2023-09-06 16 29 39

**Android:**
photo_2023-09-06 16 29 43

**Expected result:**

[Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=3188-50051&mode=design&t=4e6n7aaGkHHhVQtR-0)

Design System for Mobile – Figma 🔊 2023-09-06 16-32-14

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17207

I've noticed some issues related to the mention tag, and I'd like to provide a technical explanation that we can refer to in case we encounter similar problems in the future.

Issues:

- #15745
- #15702
- #15693
- #16108

The mention tag faces certain limitations because we're rendering a view inside a text component. Essentially, it's affected by an open issue in React Native regarding vertical alignment ([Nested View and Text vertical alignment issue](https://github.com/facebook/react-native/issues/#31955)). 

The workaround we currently employ involves trial and error to adjust the position of the mention tag so that it aligns with the text. Please note that this alignment may not be consistent across all OS versions and platforms.

Additionally, I explored an alternative solution that involves using just a text component instead of a view. However, this approach also has its limitations, particularly related to styles. For instance, nested text components don't accept properties like border radius or padding, although alignment works correctly.

So what I've done here is applied some additional improvements until the React Native team addresses the issue, or until we discover an alternative workaround or a different design approach that's implementable.

cc @pavloburykh @cammellos 

**Android** Before -> After

Android Before

Android After

**iOS** Before -> After

iOS Before

iOS After

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 1]
```diff
@@ -90,6 +87,10 @@
 
       (conj units literal))))
 
+(defn first-child-mention [children]
+    (and (= (count children) 3)
+         (empty? (:literal (first children)))
```
Comment (cammellos) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: I would use the threading operator, to avoid nesting

```
(and (= count children) 3)
     (empty? (-> children first :literal) ) ; this could also be `(empty? (get-in children [0 :literal])`
     (= :mention (-> children :type keyword)))
```

I prefer to have `(= :mention` first, as it's clearer what you want it to be

Also, are you sure about the order?

in your code it's `(:type (keyword (second children)))`, should it not be `(keyword (:type (second children)))` instead?

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: resolved

File: src/status_im2/contexts/chat/messages/content/text/style.cljs [hunk 2]
```diff
@@ -12,18 +11,14 @@
...
+(def mention-tag-wrapper
+  {:flex-direction     :row
+   :align-items        :center
+   :height             22
+   :background-color   colors/primary-50-opa-10
    :padding-horizontal 3
    :border-radius      6
-   :margin-bottom      -3
-   :height             22})
+   :transform          [{:translateY (if platform/ios? 4 6)}]})
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/style.cljs]: could you pls elaborate on why transform?

File: src/status_im2/contexts/chat/messages/content/text/view.cljs [hunk 3]
```diff
@@ -55,21 +55,18 @@
...
-         {:active-opacity 1
-          :on-press       #(rf/dispatch [:chat.ui/show-profile literal])
-          :style          style/mention-tag}
-         [quo/text
-          {:weight :medium
-           :style  style/mention-tag-text
-           :size   :paragraph-1}
-          (rf/sub [:messages/resolve-mention literal])]]])
+       [rn/touchable-opacity
+        {:active-opacity 1
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/text/view.cljs]: :active-opacity is redundant

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 2 above)
Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: @flexsurfer i explained in the PR description that margin doesn't work on nested view in android

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: It was set this way in the past, and I believe the reason is that we don't require an opacity effect when a user clicks on a mention.

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: @OmarBasem can you remember any reason for set active-opacity or i can remove it? i believe it was part of this PR https://github.com/status-im/status-mobile/pull/15799

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/content/text/style.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im2/contexts/chat/messages/content/text/style.cljs]: thanks

File: src/status_im2/contexts/chat/messages/content/text/view.cljs (hunk 3 above)
Comment (OmarBasem) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: `:active-opacity 1` is not redundant as the default `active-opacity` is 0.5. However, we are moving away from `touchable-opacity`, so you can replace it with `rn/pressable` and remove `active-opacity`

Comment (mohsen-ghafouri) [reply src/status_im2/contexts/chat/messages/content/text/view.cljs]: resolved

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanx for the PR! Alignment is much better now. 

Though I still facing alignment issues which are more visible on IOS in my case. 

## IOS 16.6, iPhone X:

photo_2023-09-07 16 17 15 jpeg 2023-09-07 16-17-33

## Android 12, Samsung Galaxy A52:

photo_2023-09-07 16 28 33 jpeg 2023-09-07 16-29-21

**Comment by churik** [comment]
@Francesca-G 
We need your help here, basically, we need to compare from designer's POV is it better in this PR than on nightly.

Thank you in advance!

**Comment by mohsen-ghafouri** [comment]
thanks @pavloburykh, as i said it involves trial and error to adjust the position, let me do another round with iPhone X

**Review by Francesca-G — APPROVED** [review]
I haven't experienced huge differences between this PR and nightly @churik but if the fixes made are to prevent misalignment that may occur with different names and mentions I think we should stick to it.

Even if I didn't have any incorrect alignment, the main issue (present in both) is the spacing between the two mentions when they're in the same 2-line text 

Screenshot 2023-09-07 alle 16 28 42

**Comment by pavloburykh** [comment]
> thanks @pavloburykh, as i said it involves trial and error to adjust the position, let me do another round with iPhone X

Thanx @mohsen-ghafouri! We decided that we are ready to merge current PR as it is, as we need it ASAP for the branch cut. 

Let's handle [these](https://github.com/status-im/status-mobile/pull/17212#issuecomment-1710162905) issues in a separate PR. I will create followup once this PR is merged.

**Comment by mohsen-ghafouri** [comment]
@pavloburykh just a few minutes i will push a new update and you can test it for the last time :)

**Comment by mohsen-ghafouri** [comment]
@pavloburykh done, please check again. 

tests from my POV
iPhone X (iOS 16.4)


Android Pixel XL Android 12

**Review by siddarthkay — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@Francesca-G I believe the issue on Android related to the space between mention tags should be improved by the latest changes. Please check my screenshot.

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you! Looks much more better now. 

Couple of issues will be logged as followup:

1. On IOS 16.6 mention is still slightly higher if located before text

photo_2023-09-07 18 45 07


2. Mentions still overlay each other

photo_2023-09-07 18 45 11

Let's merge this PR. Nice work!
