### PR TITLE
fix: route not found when attempting to transfer assets to own accounts

### LINKED ISSUE #18232: Route not found when attempting to transfer assets to additional eth account
Follow up for https://github.com/status-im/status-mobile/pull/18104

### Steps to Reproduce:

1. Restore an account with existing assets.
2. Navigate to the wallet section within the application.
3. Create an additional Ethereum address or an Ethereum watch-only address.
4. Access the main Ethereum account containing assets.
5. Tap 'Send', then 'My accounts', and select the listed account.
6. Choose any available asset and enter the valid amount for transfer.

### Actual result:
Route not found when attempting to transfer assets to an additional account

https://github.com/status-im/status-mobile/assets/52490791/16790bb3-113b-4e70-adf1-ce164166de6c

### Expected result:
The route is found when attempting to transfer assets to an additional account

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18232 

### Summary

This PR fixes routes not being fetched when attemping to send assets to an account from My Accounts tab.

- Refactor `:wallet/select-send-account-address` event to dissoc `:to-address` from db, and assoc `:send-account-address`, also moved navigation to an effect
- Refactor `:wallet/select-send-address` event to dissoc `:send-account-address` from db, and assoc `:to-address`
- In `:wallet/get-suggested-routes` event, use `:send-account-address` or `:to-address` as the sending address parameter (previously `:send-account-address` was being ignored and caused `getSuggestedRoutes` endpoint to instantly fail)

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Log in
- Go to wallet
- Be sure the user has an additional account, create a new one if not
- Go to Tap on send from an account with funds
- Tap on My Accounts tab and select an account from the logged user
- Select ETH asset
- Input some valid amount
- Check routes are loading successfully 

status: ready

### CODE REVIEW

**Review by OmarBasem — APPROVED** [review]

**Comment by J-Son89** [comment]
Could you describe what changes you made here? I know what's being done but it will be nice to understand how you are doing it 👍

**Comment by briansztamfater** [comment]
> Could you describe what changes you made here? I know what's being done but it will be nice to understand how you are doing it 👍

@J-Son89 thanks for the suggestion, updated the PR description with a better description of the changes 👍

File: src/status_im/contexts/wallet/events.cljs [hunk 1]
```diff
@@ -437,6 +437,10 @@
      (background-timer/clear-timeout current-timeout)
      {:db (assoc db :wallet/local-suggestions [] :wallet/valid-ens-or-address? false)})))
 
+(rf/reg-event-fx :wallet/clean-account-selection
+ (fn [{:keys [db]}]
+   {:db (update-in db [:wallet :ui :send] dissoc :send-account-address)}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/events.cljs:306]: Important step!

Recently I noticed when we navigate to a collectible details, for a moment, we show the previous displayed collectible details. that's because we are not cleaning the collectibles db when navigating back, so it's good we are cleaning these keys :+1:

File: src/status_im/contexts/wallet/send/events.cljs [hunk 2]
```diff
@@ -54,7 +59,8 @@
  (fn [{:keys [db now]} [amount]]
    (let [wallet-address          (get-in db [:wallet :current-viewing-account-address])
          token                   (get-in db [:wallet :ui :send :token])
-         to-address              (get-in db [:wallet :ui :send :to-address])
+         account-address         (get-in db [:wallet :ui :send :send-account-address])
+         to-address              (or account-address (get-in db [:wallet :ui :send :to-address]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:72]: We can use the `not-found` in `get-in`

`(get-in db [:a :b :c] :return-if-not-found)`

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -36,9 +32,18 @@
...
+            (update-in [:wallet :ui :send] dissoc :to-address))
+    :fx [[:navigate-to-within-stack [:wallet-select-asset stack-id]]]}))
+
 (rf/reg-event-fx :wallet/select-send-address
  (fn [{:keys [db]} [{:keys [address stack-id]}]]
-   {:db (assoc-in db [:wallet :ui :send :to-address] address)
+   {:db (-> db
+            (assoc-in [:wallet :ui :send :to-address] address)
+            (update-in [:wallet :ui :send] dissoc :send-account-address))
     :fx [[:navigate-to-within-stack [:wallet-select-asset stack-id]]]}))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:55]: I think these events only differ in the key where they store the selected address. But why do we need them? I think we could mark in `:ui :send` a boolean instead :thinking: 

about the names of the events `:wallet/select-send-address` and `:wallet/select-send-account-address` are very similar, maybe we could set a different name more descriptive to understand them better.

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater ! 
Thanks for your PR. Routes are loading successfully.
Failed e2e are not related to the PR.
