### PR TITLE
fix deleted message remains in preview at Jump to section #16374

### LINKED ISSUE #16374: Deleted message remains in preview at "Jump to" section
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/4557972/5c5ea721-0e8a-4858-a51d-10446b79b50a

#### Expected behavior
system message or previously available message in the preview

#### Actual behavior
the deleted message is shown in the preview

### Reproduction

1) Open Status
2) Send any message to a 1-1 chat
3) Delete this message 
4) Open "Jump to"

### Additional Information

- Status version: nightly 23/06/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/16374

status: ready

### CODE REVIEW

File: src/status_im2/subs/shell.cljs [hunk 1]
```diff
@@ -70,15 +83,15 @@
                            :profile-picture (when profile-picture
                                               (str profile-picture "&addRing=0"))}
      :customization-color (or (:customization-color contact) :primary)
-     :content             (get-card-content chat communities)
+     :content             (get-card-content chat communities false nil)
```
Comment (ibrkhalil) [inline src/status_im2/subs/shell.cljs]: It's up to you but it's just my personal preference, I think this function will look better if it's args are a in a map.

File: src/status_im2/subs/shell.cljs [hunk 2]
```diff
@@ -70,15 +83,15 @@
...
      :id                  id}))
 
 (defn private-group-chat-card
-  [chat id communities]
+  [chat id communities primary-name]
   {:title               (:chat-name chat)
    :avatar-params       {}
    :customization-color (or (:customization-color chat) :primary)
-   :content             (get-card-content chat communities)
+   :content             (get-card-content chat communities true primary-name)
```
Comment (ibrkhalil) [inline src/status_im2/subs/shell.cljs]: The true boolean would be more descriptive if the function used a map for it's params.

File: src/status_im2/subs/shell.cljs [hunk 3]
```diff
@@ -17,44 +19,55 @@
...
 
-         constants/content-type-community
+         (= content-type constants/content-type-community)
          (let [community (get communities (:community-id last-message))]
            {:content-type constants/content-type-community
             :data         {:avatar         (community-avatar community)
                            :community-name (:name community)}})
 
-         nil))
+         :else nil))
```
Comment (ibrkhalil) [inline src/status_im2/subs/shell.cljs]: We don't need a default/fallback card?

File: src/status_im2/subs/shell.cljs [hunk 4]
```diff
@@ -135,9 +148,18 @@
...
    [(re-frame/subscribe [:chats/chat id])
-    (re-frame/subscribe [:communities])])
- (fn [[chat communities] [_ id]]
-   (private-group-chat-card chat id communities)))
+    (re-frame/subscribe [:communities])
+    (re-frame/subscribe [:contacts/contacts])
+    (re-frame/subscribe [:multiaccount])])
+ (fn [[chat communities contacts current-multiaccount] [_ id]]
+   (let [from         (get-in chat [:last-message :from])
+         contact      (when from (multiaccounts/contact-by-identity contacts from))
```
Comment (ibrkhalil) [inline src/status_im2/subs/shell.cljs:160]: Why do we need if from exists?
Is it possible to have a message without a sender, Is that a case for system messages maybe?

**Review by ibrkhalil — APPROVED** [review]
Non blocking comments

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/subs/shell.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im2/subs/shell.cljs]: addressed, thank you

File: src/status_im2/subs/shell.cljs (hunk 4 above)
Comment (Parveshdhull) [reply src/status_im2/subs/shell.cljs:160]: Not sure, just a precaution

File: src/status_im2/subs/shell.cljs (hunk 3 above)
Comment (Parveshdhull) [reply src/status_im2/subs/shell.cljs]: subscription only returns content for the card, and default case nil was just added for the case because it would have thrown an error if a message with an unimplemented content type was received. It's not a problem with cond, removed it.

File: src/status_im2/subs/shell.cljs [hunk 5]
```diff
@@ -17,44 +19,53 @@
...
      (when last-message
-       (case (:content-type last-message)
-         (constants/content-type-text
-          constants/content-type-emoji)
+       (cond
+         (or deleted-for-me? deleted?)
          {:content-type constants/content-type-text
-          :data         (get last-message :content)}
+          :data         {:text
+                         (if (or deleted-for-me? outgoing)
```
Comment (J-Son89) [inline src/status_im2/subs/shell.cljs:31]: I'm curious of why do we have to include this logic here? is it not stored in the db or elsewhere that the message was deleted? 🤔

Comment (Parveshdhull) [reply src/status_im2/subs/shell.cljs:31]: please can you elaborate, what you mean?

Comment (J-Son89) [reply src/status_im2/subs/shell.cljs:31]: I would have expected this to be handled by the chat subscription instead, it seems like the preview message of a card should just pull in data and render it and not have any logic of what to render. Perhaps it is okay as is though.

**Comment by pavloburykh** [comment]
@Parveshdhull thanx for the fix. Rested and ready for merge.
