### PR TITLE
[fix #4282] mailserver selection bugs and random attribution for new accounts

### LINKED ISSUE #4282: Sticky random selection of mail server
### Problem

Mail servers are bound by max number of peers. To ensure a good experience for end users we want to spread usage out over several mail servers.

### Solution

Use user's public key to deterministically connect to one out of N mail servers. I.e. use a "sticky random" algorithm to spread load.

### Notes

See https://github.com/status-im/status-go/issues/950#issuecomment-389097994

### PR DESCRIPTION
**Pull request by yenda**
fix #4282
- current wnode is randomly selected for new and recovered accounts and saved
- fix bug when changing mailserver config because encryption key was not
provided for realm file
- fix bug when logging out with mixpanel tracking because
:unregister-mixpanel-tracking event was removed some time ago

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/ttkFmB for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/ttkFmB">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/TKeFXj for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/TKeFXj">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/ui/screens/offline_messaging_settings/subs.cljs [hunk 1]
```diff
@@ -1,17 +1,10 @@
...
-                  :<- [:network]
-                  :<- [:get-current-account]
-                  (fn [[network current-account]]
-                    (let [chain (ethereum/network->chain-keyword network)]
-                      (get-in current-account [:settings :wnode chain]))))
+(re-frame/reg-sub
+ :inbox/current-wnode
+ :<- [:get-current-account]
+ (fn [current-account]
+   (get current-account :wnode)))
```
Comment (cammellos) [inline src/status_im/ui/screens/offline_messaging_settings/subs.cljs]: This could possibly be just:
```
(re-frame/reg-sub
  :inbox/current-wnode
  :<- [:get-current-account]
  :wnode)
```

but it might get a default value if it's passed more than one arg and the key is not in account. But both looks good to me.

File: src/status_im/constants.cljs [hunk 2]
```diff
@@ -89,24 +86,12 @@
...
-   :rinkeby {"main" {:id     "main"
-                     :name   "Status mailserver A"
-                     :address "enode://43829580446ad138386dadb7fa50b6bd4d99f7c28659a0bc08115f8c0380005922a340962496f6af756a42b94a1522baa38a694fa27de59c3a73d4e08d5dbb31@206.189.6.48:30504"}
-             "backup" {:id      "backup"
-                       :name    "Status mailserver B"
-                       :address "enode://70a2004e78399075f566033c42e9a0b1d43c683d4742755bb5457d03191be66a1b48c2b4fb259696839f28646a5828a1958b900860e27897f984ad0fc8482404@206.189.56.154:30504"}}})
+  {"main" {:id      "main"
+           :name    "Status mailserver A"
+           :address "enode://1da276e34126e93babf24ec88aac1a7602b4cbb2e11b0961d0ab5e989ca9c261aa7f7c1c85f15550a5f1e5a5ca2305b53b9280cf5894d5ecf7d257b173136d40@167.99.209.61:30504"}
+   "backup" {:id      "backup"
```
Comment (cammellos) [inline src/status_im/constants.cljs]: At this point it does not seem to be a backup anymore, as I understand from the code it randomly choose one on create/restore account ( I understand it has a preference for `main` for existing accounts), but just by the name I would expect something called `backup` to be used when the primary fails or in special circumstances.

I would change the name to A/B, so it gives a clearer message, and we can easily add C if needed at some point, without coming up with a new name. Unless that is what is called by infrastructure, in which case possibly consistency is valuable.

@oskarth what do you think?

File: src/status_im/ui/screens/events.cljs [hunk 3]
```diff
@@ -144,6 +144,13 @@
     (fn [encryption-key]
       (re-frame/dispatch [:initialize-app encryption-key])))))
 
+(re-frame/reg-fx
+ ::get-encryption-key-fx
```
Comment (cammellos) [inline src/status_im/ui/screens/events.cljs:148]: I can't see any usage of this, ( I have found `::got-encryption-key-fx` in develop, but no `::get-encryption-key-fx` in this PR nor develop), what am I missing?

File: src/status_im/ui/screens/events.cljs [hunk 4]
```diff
@@ -252,12 +259,10 @@
    (let [{:transport/keys [chats]} db
          sharing-usage-data? (get-in db [:account/account :sharing-usage-data?])]
```
Comment (cammellos) [inline src/status_im/ui/screens/events.cljs]: I think this can now go as well, we don't use it on `logout` anymore

File: src/status_im/ui/screens/events.cljs [hunk 5]
```diff
@@ -252,12 +259,10 @@
...
      (handlers-macro/merge-fx cofx
-                              {:dispatch-n (concat [[:initialize-db encryption-key]
-                                                    [:load-accounts]
-                                                    [:listen-to-network-status]
-                                                    [:navigate-to :accounts]]
-                                                   (when sharing-usage-data?
-                                                     [[:unregister-mixpanel-tracking]]))}
```
Comment (cammellos) [inline src/status_im/ui/screens/events.cljs:260]: @jeluard I know you worked on mixpanel, this event does not seem to be used anymore, do you have any context on it or it's just dead code?

**Review by cammellos — CHANGES_REQUESTED** [review]
Looks good to me, the only 2 things I would change is removing the `sharing-usage-data?` as seems it's not used anymore, and if you could clarify `get-encryption-key-fx`, I am probably missing something here, but could not find any usage.

File: src/status_im/constants.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im/constants.cljs]: Also here is mentioned to use pubkey https://github.com/status-im/status-react/issues/4282 to select the mailserver. 

The implementation chooses at random (sticky). 

Choosing at random would help us avoiding leaking some info ( I know your public key, i know which mailserver you are using), so looks like a safe choice.

In both cases they should be evenly distributed.

Is this ok @oskarth or you wanted to make it predictable?

**Review by janherich — APPROVED** [review]

**Comment by dshulyak** [comment]
@yenda sorry for the confusion, but rinkeby is still isolated because we are using it on CI and i need to do some debugging of discovery internals before we will merge them into a single network.

we discussed removing rinkeby from the app at all, cause nobody use it. it was broken since v5 was changed to v6 and no-one noticed. should we do it and leave only ropsten and mainnet? (cc @adambabik @oskarth )

File: src/status_im/ui/screens/events.cljs (hunk 5 above)
Comment (yenda) [reply src/status_im/ui/screens/events.cljs:260]: It was all done locally apparently I forgot to force push sorry for that

**Review by dmitryn — APPROVED** [review]

**Comment by dmitryn** [comment]
It would also be good for scaling to get mailserver configuration from external source to update it on-the-fly.

**Comment by cammellos** [comment]
@oskarth to add to @dmitryn (I know this a bit off-topic), have we explored/thought about having a load balancer sitting in front of the mailservers for beta? That way we can keep the number of static nodes low, but scale it up behind the load balancers.

**Comment by adambabik** [comment]
Mail servers are regular peers and they operate on devp2p layer. It's not possible to have a simple load balancer. That wouldn't also improve anything related to the number of max peers connected to a node as load balancer would need to also connect clients as regular peers.

Simple things that we can do before RC:
1. Have a deterministic selection of mail servers from a pool based on the public key (still mail servers would need to be hardcoded),
2. Have a deterministic selection of mail servers from a pool + load the pool from an external source with fallback to local hardcoded mail servers (this also requires persistent storage of a selected mail server for a given account as the pool of mail servers can change; I guess it's done in this PR, right?)

For the public beta, we basically need to figure out a completely different architecture for mail servers. @dshulyak and I have some ideas but it's not formalized yet.

**Comment by cammellos** [comment]
@adambabik probably I am missing something, don't know much about the protocol. 

The reasoning behind my comment is:
devp2p runs on top of TCP.

Haproxy/ipvs for example can load balance long lived tcp connections (or any other transport layer load balancer) , in the number of millions.

So you just need to set `maxconn` in the backend in haproxy to 500, then you can dinamically change the number of mailservers behind. (so no mailserver will get more than 500 connections).

Or devp2p cannot be load balanced by transport layers lb ? What do you think?

**Comment by adambabik** [comment]
@cammellos it may be possible but it does not qualify under `to have a **simple** load balancer` :D It's very interesting idea though, definitely worth to explore. 

Also, the thing is that it may be perfectly fine to have a mail server with `maxPeers` set to `1000` or more. In theory, a single host can handle around 65000 TCP connections on its own. The problem is that we have no numbers right now so I would hold back before implementing anything complicated.

**Comment by cammellos** [comment]
@adambabik cool, I agree it's worth exploring.

If we are going to provide mailservers ourselves, I think the advantages of LB are that we can also let the LB to handle healthchecks (do we have any btw as of now?), and we can easily change things quickly in Beta if we see that we can't support the load. 

Having a dynamic config of peers handled application side looks like a much more complicated/custom solution to a problem that has already been solved by load balancers, unless we want to make this decentralized as well, in which case a custom solution might be necessary.

I might have a quick look at whether we can actually load balance mailserver, and I might need your assistance, if you don't mind.

**Comment by yenda** [comment]
@adambabik why does the mailserver an account uses has to be deterministic and not just random ? I shouldn't be able to guess which mailserver a user is going to use by just knowing his public address

**Comment by adambabik** [comment]
@yenda That's a good question. I had a consistency in responses at the back of my mind but it should not really matter which mail server is actually selected. 

> I shouldn't be able to guess which mailserver a user is going to use by just knowing his public address

Agree, that's not a nice property.

**Comment by yenda** [comment]
It seems we want to keep rinkeby separated so I propose to cleanup that PR and only keep random selection of mailserver and bug fixes for logout and mixpanel event for now

**Comment by adambabik** [comment]
@cammellos Yeah, that's true. With the current architecture and an LB, we could solve a few problems easily. If you'd like to explore this, I will be happy to assist. Monitoring work is currently in progress or will be in progress in the next week.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/mKbYnq for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/mKbYnq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

File: src/status_im/ui/screens/events.cljs (hunk 3 above)
Comment (cammellos) [reply src/status_im/ui/screens/events.cljs:148]: @yenda did you have a chance to look at this?

**Comment by dshulyak** [comment]
> devp2p runs on top of TCP.
Haproxy/ipvs for example can load balance long lived tcp connections (or any other transport layer load balancer) , in the number of millions.

there will be couple of problems with that approach

before two peers can communicate with each other - they will do a handshake, after handshake is finished p2p servers state changes, and only after that both peers can send messages to each other. so without handshake any message will be simply ignored by p2p listener.

another problem is that all messages are assumed to be authenticated, e.g. identity must be verifiable (and it must match to one negotiated during the handshake). the only way to achieve shared identity is too distributed private key among all mail servers behind load balancer.

even if 2nd seems solvable there are might other consequences of doing so, but the 1st probably isn't

**Comment by adambabik** [comment]
> before two peers can communicate with each other - they will do a handshake, after handshake is finished p2p servers state changes, and only after that both peers can send messages to each other. so without handshake any message will be simply ignored by p2p listener.

**Comment by adambabik** [comment]
> before two peers can communicate with each other - they will do a handshake, after handshake is finished p2p servers state changes, and only after that both peers can send messages to each other. so without handshake any message will be simply ignored by p2p listener.

But this handshake is basically exchanging some packets through the TCP socket, right? If we use sticky connections and always forward traffic to the same peer behind the proxy, it may work? This still can give use some advantages.

**Comment by dshulyak** [comment]
> But this handshake is basically exchanging some packets through the TCP socket, right? If we use sticky connections and always forward traffic to the same peer behind the proxy, it may work? This still can give use some advantages.

i forgot about sticky sessions, yeah if it is consistently routed to the same peer that part should be ok.

but mailservers still will have to use same identity, because of enode, yes? afair node id is used in p2p server as a unique identifier (e.g not whole enode, but no only part of it deriver from public key), so same mail server won't be able to connect to the other peers, making some mail server possibly isolated. worth investigating though

**Comment by cammellos** [comment]
@dshulyak I am a bit confused, is it not devp2p using long lived tcp connections?

Basically the handshake it's all through the same TCP connection (and any data exchange used the same connection), so it will obviously be routed to the same backend mailserver.
If the connection is closed, is there any state kept on either sides that would need the next session to hit the same backend? ( I thought no, a new handshake will occur etc), but as I said, know very little about the protocol.

For enode yes, you are right if there's is an association between key & ip, we'd need to share the same key among all backends.

To the docker-compose I say!

**Comment by adambabik** [comment]
> Basically the handshake it's all through the same TCP connection (and any data exchange used the same connection), so it will obviously be routed to the same backend mailserver.

It was not obvious to me as I have only worked with HTTP load balancing. I thought that there would be some multiplexing on LB level but without understanding the upper protocol it seems not possible. So it's gonna be always 1-1 between a client and backend.

> If the connection is closed, is there any state kept on either sides that would need the next session to hit the same backend?

No, each session can connect to a different backend mail server.

**Comment by cammellos** [comment]
@adambabik thanks for the answers.

I have set up a compose with haproxy, and pointing at one of the mailservers.

It seems I am able to connect with the normal `geth` client:

```
 admin.peers
[{
    caps: ["shh/6"],
    id: "1da276e34126e93babf24ec88aac1a7602b4cbb2e11b0961d0ab5e989ca9c261aa7f7c1c85f15550a5f1e5a5ca2305b53b9280cf5894d5ecf7d257b173136d40",
    name: "StatusIM/v0.9.9-/linux-amd64/go1.10.2",
    network: {
      inbound: false,
      localAddress: "127.0.0.1:53112",
      remoteAddress: "127.0.0.1:30304",
      static: true,
      trusted: false
    },
    protocols: {
      shh: "unknown"
    }
}]
```
Which looks encouraging.

Does that mean that the connection was successful ? (If I stop happroxy, the peercount goes to 0).

Is there any difference between running the normal `geth` client (in light mode), and status-go?

File: src/status_im/ui/screens/events.cljs (hunk 3 above)
Comment (yenda) [reply src/status_im/ui/screens/events.cljs:148]: @cammellos yes something was wrong with my commit a bunch of changes went missing but then I had to rework the PR anyway to account for rinkeby

**Comment by yenda** [comment]
@cammellos  sharing-usage-data? was removed and get-encryption-key-fx is for events that need an encryption key such as logout, when called without an encryption-key it gets the encryption key then is called again

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/rqn3Hz for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/rqn3Hz">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/YA7yGU for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/YA7yGU">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/oa94ej for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/oa94ej">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/LjuUST for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/LjuUST">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by oskarth** [comment]
> remove rinkeby

Sounds good.

> load balancer etc

This seems off-topic for this PR, but a LB doesn't make that much sense to me, and it's definitely not something for the beta. The goal isn't that we are running the mail servers, that's just a hack to bootstrap and enable other people to run the servers. We aren't trying to build a centralized server farm here.

The reason for making it sticky random (https://github.com/status-im/status-react/issues/4282) is to spread load in a reasonable default manner, it doesn't mean a user can't select another mail server if they so choose.

As Eric pointed out, right now it doesn't matter which server is used, so we could use random without sticky random, but this seems suboptimal given that:

a) in the future user will pay for 1 or a set of mail servers, so completely random doesn't make sense
b) we probably don't want all mail servers to store all data forever, only a subset

**Comment by oskarth** [comment]
I suggest we fork this discussion to a separate issue or thread, and more generally focus on making the minimal changes necessary to make beta usable, similar to what @adambabik suggested earlier in this thread.

**Review by cammellos — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/buyEmU for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/buyEmU">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/TeNjxM for branch PR-4286

<blockquote><div><strong><a href="https://i.diawi.com/TeNjxM">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
