### PR TITLE
[FIX #3641] Modify chat input to retain text, parameter box on blur

### LINKED ISSUE #3641: Specify amount popup maybe unexpectedly closed when trying to change the transaction fee
### Description
*Type*: Bug

*Summary*: When user tries to change a transaction fee and she taps near the slider the whole specify amount popup hides. This can be really frustrating.

#### Expected behavior
Specify amount popup does not hide when tapped.

#### Actual behavior
When you tap inside red rectangles shown on the following picture, the popup hides:

### Reproduction
- Open Status
- Open 1-1 chat
- Type "/send 0.001" and wait for the specify amount popup
- Tap somewhere on the popup

### Additional Information
* Status version: nightly, March 21
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by kwingram25**
Fixes #3641

### Summary:
Chat input now continues to show entered text and command parameter box on blur

### Steps to test:
- Open Status
- Open chat with user
- Type /send to activate command parameter box
- Tap on parameter box or messages scroll view
- The input text and parameter box should persist after keyboard closes

status: ready

### CODE REVIEW

**Review by alwx — CHANGES_REQUESTED** [review]
This PR fixes the issue, but re-introduces https://github.com/status-im/status-react/issues/3412

**Comment by kwingram25** [comment]
Added a new chat ui prop :messages-focused? to control display of expandable contents. Expandable now displays if input is focused and persists if box contents are tapped, and hides if user taps chat background or chat row.

iOS testing needed as some changes were made to device-specific keyboard behavior

**Comment by flexsurfer** [comment]
@kwingram25 could you please rebase onto develop, thanks

**Comment by kwingram25** [comment]
@flexsurfer Sorry! looks like it has the correct changes now

File: src/status_im/chat/screen.cljs [hunk 1]
```diff
@@ -87,12 +87,18 @@
...
+                    (re-frame/dispatch [:set-chat-ui-props {:messages-focused? true}])
+                    (react/dismiss-keyboard!))}
+       [react/animated-view {:style (style/message-view-animated opacity)}
+        message-view]]]))
 
 (defview messages-view [group-chat]
   (letsubs [messages           [:get-current-chat-messages]
             current-public-key [:get-current-public-key]]
+    {:component-did-mount #(re-frame/dispatch [:set-chat-ui-props {:messages-focused? true
+                                                                    :input-focused? false}])}
```
Comment (alwx) [inline src/status_im/chat/screen.cljs]: can you fix indentation here?

**Review by alwx — APPROVED** [review]
Approved, one small thing left to be done, but it's really something very very small.

**Comment by alwx** [comment]
Test team: please, make sure this PR doesn't break #3481.

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@kwingram25 please rebase and build again

**Comment by kwingram25** [comment]
Just the two passed properties, right? Should be correct now

**Comment by asemiankevich** [comment]
hey @kwingram25 i can't build it, here is the log
`Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to macos1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
		at hudson.remoting.Channel.call(Channel.java:908)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor235.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy96.execute(Unknown Source)
		at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:122)
		at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1068)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1161)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:260)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
hudson.plugins.git.GitException: Command "git merge 83876f7cf1867fa0d38385c49de11203f26f59f2" returned status code 1:
stdout: Removing src/status_im/data_store/realm/schemas/account/v23/message.cljs
Removing src/status_im/data_store/realm/schemas/account/v23/core.cljs
Auto-merging src/status_im/chat/views/message/message.cljs
Auto-merging src/status_im/chat/views/input/input.cljs
Auto-merging src/status_im/chat/screen.cljs
CONFLICT (content): Merge conflict in src/status_im/chat/screen.cljs
Removing ios/upload-dsym.sh
Removing ios/libTestFairy.a
Removing ios/TestFairy.h
Removing ios/StatusImPrefix.pch
Removing ios/StatusIm/Images.xcassets/console.imageset/console.png
Removing ios/StatusIm/Images.xcassets/console.imageset/console-2.png
Removing ios/StatusIm/Images.xcassets/console.imageset/console-1.png
Removing ios/StatusIm/Images.xcassets/console.imageset/Contents.json
Removing android/app/src/main/res/drawable-xxxhdpi/console.png
Removing android/app/src/main/res/drawable-xxhdpi/console.png
Removing android/app/src/main/res/drawable-xhdpi/console.png
Removing android/app/src/main/res/drawable-mdpi/console.png
Removing android/app/src/main/res/drawable-hdpi/console.png
Automatic merge failed; fix conflicts and then commit the result.

stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1964)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1960)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1597)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$3.execute(CliGitAPIImpl.java:697)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by kwingram25** [comment]
Ah i had to fetch other changes - looks like the conflict in screen.cljs is resolved now, that seems to be the issue you had

**Comment by jeluard** [comment]
@kwingram25 Can you rebase this PR?

**Comment by rasom** [comment]
```
Use of undeclared Var status-im.ui.components.react/touchable-without-feedback at line 91 .../src/status_im/chat/screen.cljs
```

**Comment by rasom** [comment]
@kwingram25 could you please check an error above?

**Comment by kwingram25** [comment]
Added touchable-without-feedback into react components, now works

**Comment by rasom** [comment]
there is still some problem on Jenkins, checking it now

**Comment by rasom** [comment]
it's building now, should be fine

**Comment by rasom** [comment]
Thanks for contribution, @kwingram25 !
