### PR TITLE
[15383] Add the album count attribute to message body

### LINKED ISSUE #15383: Photo album reply doesn't display the number of photos in the album
# Bug Report

## Problem 
Currently, when replying to a photo album, we only display the word "Image" in the quoted message in the composer. We should display the number of photos in the album instead. 

#### Expected behavior

`3 photos` when replying to the album with three images

Screenshot 2023-03-16 at 11 56 43

Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2839-278601&t=56KGyLmXnk2cbJ5X-4

#### Actual behavior

Screenshot 2023-03-16 at 11 57 53

### Reproduction

1. Send a photo album
2. Long press on the message > `Reply`

### Additional Information

- Status version: nightly 16/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
This PR adds the album count attribute to the message body .. So that we can know how many images are in an album

fixes #15383 

### Summary

This PR adds a key to indicate how many photos were sent in a message .. This is helpful in identifying how many images are in a message .. And then I just added logic to render the number of images on reply

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Step 1, Send a message with multiple images
- Step 2, Reply to it and check when writing the reply if the number of images will show or not
- Step 3, Send the reply and check if the count is shown with the new reply or not

Expected behaviour:
Images count to show when sending the reply and after sending it
image

Example:

status: ready

### CODE REVIEW

File: src/status_im/ui2/screens/chat/components/reply/view.cljs [hunk 1]
```diff
@@ -113,7 +114,9 @@
                                            (= constants/content-type-audio content-type))
                                    {:color (colors/theme-colors colors/neutral-50 colors/neutral-40)}))}
           (case (or content-type contentType)
-            constants/content-type-image   "Image"
+            constants/content-type-image   (if album-count
+                                             (str album-count \space "Images")
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/components/reply/view.cljs]: Missing translation ;) Please, translate the words `Sticker` and `Audio` too if you can.

Also, consider pluralizing correctly, since `1 Images` is incorrect.

Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/components/reply/view.cljs]: I'll add the translations but the case that you mentioned ahould never happen because if the message has more than one photo it'll have the `album-count` property

Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/components/reply/view.cljs]: I don't thing a message can have more than one audio message or more than one sticker, but using i18n for their names is essential

File: src/status_im/ui2/screens/chat/components/reply/view.cljs [hunk 2]
```diff
@@ -113,9 +114,11 @@
                                            (= constants/content-type-audio content-type))
                                    {:color (colors/theme-colors colors/neutral-50 colors/neutral-40)}))}
           (case (or content-type contentType)
-            constants/content-type-image   "Image"
-            constants/content-type-sticker "Sticker"
-            constants/content-type-audio   "Audio"
+            constants/content-type-image   (if album-count
+                                             (str album-count \space (i18n/label :t/images))
```
Comment (J-Son89) [inline src/status_im/ui2/screens/chat/components/reply/view.cljs]: I think it's better to put album count as part of the translation string. You never know how it will be used in a different language 
i.e
en.json
```
"images-albums-count": "{{album-count}} images"
```
reply.view.cljs
```
 (i18n/label :t/images {:album-count album-count})
```

**Review by J-Son89 — APPROVED** [review]
looks good but translation string needs adjustment imo 👍

File: src/status_im/ui2/screens/chat/components/reply/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/components/reply/view.cljs]: Good idea, Done

**Review by OmarBasem — APPROVED** [review]

**Comment by ibrkhalil** [comment]
Please take a look when you have a minute @qoqobolo

**Comment by qoqobolo** [comment]
Hi @ibrkhalil, could you rebase this PR once more please, I'll take a look at it.
Thanks!

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil, could you rebase this PR once more please, I'll take a look at it. Thanks!

Done

**Review by alwx — APPROVED** [review]

**Comment by qoqobolo** [comment]
@ibrkhalil 

### ISSUE 1: The number of images in the reply is displayed only for albums that were sent by you

If you (or another user) reply to **someone else's** album, you only see `Image` no matter how many images there are in the album.

If you reply to **your** album or someone else replies to **your** album, you will see the number of images.

**STR:**
1. UserA and UserB join a chat
2. UserA sends 2 images
3. UserB replies to this album

**Expected result:** UserB sees `Image` in the reply
**Actual result:** UserB sees `2 images` 

**OS:** Android, iOS 

https://user-images.githubusercontent.com/67952253/230422953-78e9ea81-c9e2-42fa-a514-575e455c1c64.mp4

**Comment by ibrkhalil** [comment]
> @ibrkhalil
> 
> ### ISSUE 1: The number of images in the reply is displayed only for albums that were sent by you
> If you (or another user) reply to **someone else's** album, you only see `Image` no matter how many images there are in the album.
> 
> If you reply to **your** album or someone else replies to **your** album, you will see the number of images.
> 
> **STR:**
> 
> 1. UserA and UserB join a chat
> 2. UserA sends 2 images
> 3. UserB replies to this album
> 
> **Expected result:** UserB sees `Image` in the reply **Actual result:** UserB sees `2 images`
> 
> **OS:** Android, iOS

Hey Diana, This issue was reported by Boris Melnik on Desktop team two days ago and was fixed yesterday.
I just forgot to update status-go to latest version on this PR
Apologies for that
Updated

**Comment by pavloburykh** [comment]
@ibrkhalil thanx for the fix. PR is ready to be merged.
