### PR TITLE
fix: toast style on android

### LINKED ISSUE #15178: Toasts are broken for Android devices
Looks like toasts are not fixed fully in https://github.com/status-im/status-mobile/issues/15165 @yqrashawn.
 
Please, do not hesitate asking qa team for manual testing. E2E tests do not cover every scenario. In this particular case, toasts are not covered by E2E so they would not catch bugs related to toasts. That’s why, manual testing is needed.

**Steps:**

1. Generate any toast within the app (for example toast wich is shown after contact request is received)
2. See if toast UI looks correct

**Actual result:** 
toasts are broken for Android devices
image

**Additional Information**
- Status version: nightly
- Operating System: Android

### PR DESCRIPTION
**Pull request by yqrashawn**
fix https://github.com/status-im/status-mobile/issues/15178

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/toast.cljs [hunk 1]
```diff
@@ -56,22 +56,36 @@
 
 (defn- toast-container
   [{:keys [left title text right container-style override-theme]}]
-  [rn/view {:style (merge {:margin-left 12 :margin-right 12} container-style)}
+  [rn/view
+   {:style (merge {:margin-left   12
+                   :margin-right  12
+                   :position      :relative
+                   :border-radius 12
+                   :overflow      :hidden}
```
Comment (Parveshdhull) [inline src/quo2/components/notifications/toast.cljs]: 1. `margin-horizontal` can be used
2. position `:relative` is by default https://reactnative.dev/docs/layout-props#position

Comment (yqrashawn) [reply src/quo2/components/notifications/toast.cljs]: fixed

**Review by Parveshdhull — APPROVED** [review]
