### PR TITLE
[#21658] - Avatars blinking

### LINKED ISSUE #21215: Profile - Status dropdown text is misaligned in profile settings
# Design Feedback 2.30

## [Profile] Status dropdown text is misaligned in profile settings
The status dropdown text isn't properly aligned [[Figma](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2295-16566#937853940)]

**Especially visible on Android** - there's a slight misalignment on iOS as well, way less visible

#### Expected behavior

Screenshot 2024-09-09 alle 09 43 13

#### Actual behavior

Screenshot 2024-09-09 alle 09 43 39

### Reproduction

1. Open profile settings

### Additional Information

- Operating System: Android 14
- Devices in the screenshots: Realme 10

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #21658: Avatars blink all over the app
# Bug Report

## Problem 

The avatas are constantly blinking all over the app, this leads to a bad UX and also shows that _probably_ we are re-rendering more ofthen than needed.

#### Expected behavior

Not to re-render

#### Actual behavior

Re-renders all over the app, check this video with a few examples:

https://github.com/user-attachments/assets/4e4e57c0-6b55-41aa-b89f-b80df35d9d7a

### Additional Information

This issue has been created to investigsate the root cause, there's a `no-flicker-image` component, so we should check if that is being properly  used.

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21658
fixes #21215

## Summary

This PR fixes some issues found related to the rendering of some components. The code fixes are listed in the self-review.

The main fixes are:

### 1. fast-image usages blinking

A background image for the image was added, this fix might be polemic because we are duplicating the images rendered, so feel free to share your thoughts about it. (btw, the `no-flicker-image` in the repo already does this for `rn/image`). The comparison:

Before:

https://github.com/user-attachments/assets/ed942292-0e1a-43ac-9848-4c59fa4ee5b3 

After:

https://github.com/user-attachments/assets/020033d2-5b70-427c-bfb3-2282dbda9761

### 2. Avatar not being updated in profile screen:

Before:

https://github.com/user-attachments/assets/141bffa9-de34-4002-8ea0-577c1c570555

After:

https://github.com/user-attachments/assets/d512135a-caf6-4597-ac53-6adfde5d8ee5

### 3. Fixed the avatar styles and animation.
Reported in:
- #21215

Now it follows designs and the calculations are simpler. You can see the animation also looks more stable:

Before:

https://github.com/user-attachments/assets/ccbc4b74-aa4d-4df4-8796-d4a3e04df8ed

After:

https://github.com/user-attachments/assets/2438b334-0916-448a-86b4-dd0b0fd8fb68

### 4. Fixed the ring around the avatar on Android, it changes its color. This feature still works on iOS consistently.

Before:

https://github.com/user-attachments/assets/d366b167-c575-4f56-9fea-ef6254eb6c15

After:

https://github.com/user-attachments/assets/0c4b6820-2e26-4642-973a-954fa505b05c

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/react_native/fast_image.cljs [hunk 1]
```diff
@@ -4,37 +4,56 @@
...
+        error?          (reagent/atom false)
+        previous-source (reagent/atom nil)
+        on-image-error  (fn [event on-error]
+                          (when (fn? on-error) (on-error event))
+                          (reset! error? true))
+        on-image-loaded (fn [event on-load source]
+                          (when (fn? on-load) (on-load event))
+                          (reset! loaded? true)
+                          (reset! error? false)
+                          (reset! previous-source source))]
```
Comment (ulisesmac) [inline src/react_native/fast_image.cljs]: Fast image fix :eyes:

File: src/react_native/flat_list.cljs [hunk 2]
```diff
@@ -23,19 +23,22 @@
...
-   (dissoc props :data :header :footer :empty-component :separator :render-fn :key-fn :on-drag-end-fn)))
+  (cond-> {:data (to-array data)}
+    key-fn          (assoc :keyExtractor (wrap-key-fn key-fn))
+    render-fn       (assoc :renderItem (wrap-render-fn render-fn render-data))
+    separator       (assoc :ItemSeparatorComponent (fn [] (reagent/as-element separator)))
+    empty-component (assoc :ListEmptyComponent (fn [] (reagent/as-element empty-component)))
+    header          (assoc :ListHeaderComponent (reagent/as-element header))
+    footer          (assoc :ListFooterComponent (reagent/as-element footer))
+    on-drag-end-fn  (assoc :onDragEnd (wrap-on-drag-end-fn on-drag-end-fn))
+    :always         (merge (dissoc-custom-props props))))
```
Comment (ulisesmac) [inline src/react_native/flat_list.cljs:42]: multiple `merge` -> multiple `assoc`

File: src/status_im/common/scalable_avatar/view.cljs [hunk 3]
```diff
@@ -2,30 +2,14 @@
...
-                                                            scroll-animation-input-range
-                                                            [-4 -20]
-                                                            header-extrapolation-option)]
-    [reanimated/view
-     {:style (style/wrapper {:scale        image-scale-animation
-                             :margin-top   image-top-margin-animation
-                             :margin       image-side-margin-animation
-                             :border-color border-color})}
+  (let [image-scale (reanimated/interpolate scroll-y scroll-range scale-range :clamp)]
+    [reanimated/view {:style (style/wrapper border-color image-scale)}
```
Comment (ulisesmac) [inline src/status_im/common/scalable_avatar/view.cljs:12]: Avatar animation fix

File: src/status_im/contexts/chat/home/view.cljs [hunk 4]
```diff
@@ -62,8 +62,8 @@
         :on-end-reached                    #(re-frame/dispatch [:chat/show-more-chats])
         :keyboard-should-persist-taps      :always
         :data                              items
-        :render-fn                         (fn [item]
-                                             (chat-list-item/chat-list-item item theme))
+        :render-data                       {:theme theme}
+        :render-fn                         chat-list-item/chat-list-item
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/home/view.cljs:66]: Fix rerenders on items for this flat-list

File: src/status_im/contexts/chat/home/view.cljs [hunk 5]
```diff
@@ -108,8 +107,8 @@
         :sticky-section-headers-enabled    false
         :render-section-header-fn          contact-list/contacts-section-header
         :render-section-footer-fn          contact-list/contacts-section-footer
-        :render-fn                         (fn [data]
-                                             (contact-item-render data theme))
+        :render-data                       {:theme theme}
+        :render-fn                         contact-item-render
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/home/view.cljs:111]: Fix rerenders on items for this flat-list too

File: src/status_im/contexts/profile/settings/header/style.cljs [hunk 6]
```diff
@@ -23,13 +22,8 @@
...
-    :margin-bottom side-margin-animation}
-   {:align-items   :flex-start
-    :border-width  4
-    :border-color  (colors/theme-colors colors/border-avatar-light colors/neutral-80-opa-80 theme)
-    :border-radius 100}])
+(defn avatar-border-color
+  [theme]
+  (if platform/android?
+    colors/neutral-80-opa-80 ;; Fix is not needed because Android doesn't use blur
+    (colors/theme-colors colors/border-avatar-light colors/neutral-80-opa-80 theme)))
```
Comment (ulisesmac) [inline src/status_im/contexts/profile/settings/header/style.cljs:29]: Avatar's ring fix

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM, Nice improvement 🚀

**Comment by flexsurfer** [comment]
hey @ulisesmac do you know why we didn't have `fast-image usages blinking` problem before? When and where did it come from?

File: src/status_im/contexts/profile/settings/header/style.cljs (hunk 6 above)
Comment (ilmotta) [reply src/status_im/contexts/profile/settings/header/style.cljs:29]: Worth noting that we have an issue that we can play in 2.33 to remove identity rings https://github.com/status-im/status-mobile/issues/21743

File: src/react_native/fast_image.cljs [hunk 7]
```diff
@@ -4,37 +4,56 @@
...
+     (not loaded?)                 [rn/activity-indicator {:animating true}])])
 
+(defn- get-source
+  [source]
+  (if (string? source)
+    {:uri      source
+     :priority :high}
+    source))
+
+;; NOTE: We need to use ratoms to avoid the flickering since their state is updated
```
Comment (ilmotta) [inline src/react_native/fast_image.cljs]: @ulisesmac I thought all image flickers were caused by buggy implementation (e.g. components receiving unstable function references as we both identified in https://github.com/status-im/status-mobile/issues/21658).

If the new props passed to `fast-image` are equal to previous props, Reagent would skip processing `fast-image` altogether and there would be no flicker. If you could pick one example where this workaround is needed, could you explain what's changing between render passes of `fast-image` that is causing Reagent to reprocess it?

File: src/status_im/contexts/profile/settings/header/style.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/settings/header/style.cljs:29]: This ring I'm referring to is the one showed in PR's video:

https://github.com/user-attachments/assets/d366b167-c575-4f56-9fea-ef6254eb6c15

different to the identity ring

**Comment by ulisesmac** [comment]
@ilmotta @flexsurfer 

Thank you so much for your review!
I'll explain the fix about fast-image.

> I thought all image flickers were caused by buggy implementation (e.g. components receiving unstable function references as we both identified in https://github.com/status-im/status-mobile/issues/21658).

Yeah, that's true for unnecessary rerenders, but not all image flickerings are due to this.

> If the new props passed to fast-image are equal to previous props, Reagent would skip processing fast-image altogether and there would be no flicker. If you could pick one example where this workaround is needed, could you explain what's changing between render passes of fast-image that is causing Reagent to reprocess it?

This is a side effect of the image server.

I added  videos to the description, here's an example:

We use an URL `A` to render the avatar, but when the user opens the share modal, the app switches to a background state, so the image server will change its port, so we generate an URL `B` for the avatar, so a rerender is needed even though the resource is the same (i.e. the same user image).

And now, you may wonder

> How is that related to fast-image?

The answer is that our wrapper for `fast-image` is rendering a spinner and a letter `X` as placeholders for loading and error states respectively, causing a quick blink when we swap URLs (sources). fast-image itself isn't able to swap sources without a visual blank state.

What I did in this PR is implementing a second bg image that avoids that visual blank state. It's just a visual fix.

This fix also improved the appearance of necessary re-renders. e.g. When the user `updates their profile name, the avatar blinks on develop, in this PR this no longer happens. LMK if you want me to record videos comparing the differences.

IMO this fix is relatively cheap and provides a lot the looking of the app.

> do you know why we didn't have fast-image usages blinking problem before? When and where did it come from?

The image server dynamic port is a reason, another reason is when we just update its props, so I'd say the issue has been there all the time. Maybe on some fast iOS devices the rerender is too fast to be easily perceived

**Comment by ilmotta** [comment]
Thanks @ulisesmac for the detailed answer.

The fast image cache strategy we use is the default, `immutable`. That means whenever the port changes or any other part of the URL, the cache is thrown away. This isn't good of course.

The best possible implementation I think is if we could leverage the `ETag` HTTP header because then no data is even transferred if the resource didn't change. I wonder how much/well the fast-image library supports cache headers as they say with the `web` strategy. The `ETag` value is usually a hash of the resource, which status-go would compute.

A change of port shouldn't be considered a change of resource between the client & status-go communication. But I think fast-image doesn't provide a way to customize the logic to decide when the cache is stale or not, at least as far as the official docs go.

What if we provide a custom React key that's stable between re-renders by ignoring the port change? Wouldn't that solve the flashing?

> The answer is that our wrapper for fast-image is rendering a spinner and a letter X as placeholders for loading and error states

For loading, we should ideally differenciate between fetching local resources and actual remote resources. The loading spinner should only be used for non-local resources, similar to how we avoid in UX to show spinners for resources loading in milliseconds. Images coming from the media-server are local as far as I understand.

For error states I'm not sure what to say, but it should be a rare problem that wouldn't justify flashing side-effects.

**Comment by ulisesmac** [comment]
> Thanks @ulisesmac for the detailed answer.

> 
> The best possible implementation I think is if we could leverage the `ETag` HTTP header because then no data is even transferred if the resource didn't change. I wonder how much/well the fast-image library supports cache headers as they say with the `web` strategy. The `ETag` value is usually a hash of the resource, which status-go would compute.
> 

I agree, or explore better solutions for the image-server.


> 
> What if we provide a custom React key that's stable between re-renders by ignoring the port change? Wouldn't that solve the flashing?
> 

The problem is: if we skip the rerender, how do we know when the image should have been updated?

E.g. the user actually had their profile picture updated but we ignored the rerender.


> 
> For loading, we should ideally differenciate between fetching local resources and actual remote resources. The loading spinner should only be used for non-local resources, similar to how we avoid in UX to show spinners for resources loading in milliseconds. Images coming from the media-server are local as far as I understand.
> 

For local resources we shouldn't use fast-image, I agree. But even if no spinners or error states were displayed, the fast image still shows a blink (since it throws the previous image and loads the new one)

**Comment by ilmotta** [comment]
> The problem is: if we skip the rerender, how do we know when the image should have been updated?
>
> E.g. the user actually had their profile picture updated but we ignored the rerender.

The idea is that the port number shouldn't be considered part of the cache key for FastImage or any other mechanism. If we use `React.memo` we can provide a custom comparator function that ignores the port number in the URI. I tested this solution and the blinking disappeared completely from all avatars and the share QR code screen.

Don't judge too much the following snippet @ulisesmac, but it's a starting point and seems to work well. I wouldn't be surprised if this idea is flawed. For simplification purposes I ignored loading and error conditions.

```clojure
(defn clean-port
  [uri]
  (string/replace-first uri #":\d+" ""))

(def fast-image
  (reagent/adapt-react-class
   (rn/memo
    (fn [^js props]
      (let [source (oops/oget props :source)]
        (react/createElement
         FastImage
         (js/Object.assign
          #js {}
          props
          (when (and props source)
            #js {:source (if (string? source)
                           #js {:uri      source
                                :priority "high"}
                           #js {:uri      (oops/oget source :uri)
                                :priority "high"})})))))
    (fn [prev-props next-props]
      (let [prev-uri (oops/oget prev-props :source :uri)
            next-uri (oops/oget next-props :source :uri)]
        (and prev-uri
             next-uri
             (= (remove-port prev-uri) (remove-port next-uri))))))))
```

In any case, it's not my intention to suggest this is the only way, I leave it up to you and other CCs to judge. It's good to know we have other options in the future to better fix blinking images.

**Comment by flexsurfer** [comment]
> but when the user opens the share modal, the app switches to a background state

i'm not sure i understand how that happen, could you elaborate? why does it switch to a background state in that case?

**Comment by seanstrom** [comment]
@flexsurfer I think when an iOS share-sheet opens, the OS will sorta transition the the app into an inactive/background state because share-sheet is native OS menu and outside of the app's control. I think also might happen when someone pulls down the iOS control-center from the top-right while running the app.

**Comment by seanstrom** [comment]
@ulisesmac I like the idea of having a component that maintains a background image and foreground image, that could be pretty useful for transitioning between two images!

Though I was thinking that @ilmotta's approach with using a component to ignore changes with `port` prop to also be compelling, since it would save us from needing to have a second image for each image (right?).

Also, we still have a `clock` that's useful for determining when a profile image has been changed. So we could potentially rely on the `clock` field and other source name fields to help with determining when a profiles avatar/image has changed. In the case with the initials-avatar, I think it should be the display-name (or full-name) and the `clock` field that should cause a re-render.

**Review by ilmotta — APPROVED** [review]
Even though I think there are better solutions to the blinking problem, I think your solution is practical and solves the problem without introducing performance regressions. Approved! Thanks @ulisesmac for solving this old problem!

**Comment by ulisesmac** [comment]
@flexsurfer 

> i'm not sure i understand how that happen, could you elaborate? why does it switch to a background state in that case?

It's switched to a background state because, as @seanstrom  said, the share sheet comes from the OS, so it swithces our app to bg, after the sheet is closed our app returns to foreground.

Because of this, the image server changes its ports and a re-render happens for all the images provided by the server.

**Comment by ulisesmac** [comment]
@ilmotta Thanks for remembering me `memo` is an option.

The solution you provided looks better to me since we aren't duplicating  the images shown. However, although it solves the unnecessary re-render problem, it doesn't solve the issue about swapping the image without a blink.

Thanks for approving, but I'll test your suggestion to see how it behaves :+1:  Thanks again

File: src/react_native/fast_image.cljs [hunk 8]
```diff
@@ -1,40 +1,71 @@
...
+        new-source (oops/oget new-props :source)]
+    (and old-source
+         new-source
+         (= (remove-port old-source) (remove-port new-source)))))
+
+(def fast-image
+  (-> internal-fast-image
+      (reagent/reactify-component)
+      (rn/memo compare-sources)
+      (reagent/adapt-react-class)))
```
Comment (ulisesmac) [inline src/react_native/fast_image.cljs]: @ilmotta took your suggestion here, it actually fixes the problem. Thanks!

I prefer this solution since we aren't duplicating a component. mantainability isn't hurt since `reactify-component` was used.

BTW, for some reason, reactify-component seems to ignore the functional compiler, so no hooks were used (the comment on the code has been already added).

Comment (ilmotta) [reply src/react_native/fast_image.cljs]: The way you used `reactify-component` made things much cleaner 👍🏼

File: src/react_native/fast_image.cljs [hunk 9]
```diff
@@ -1,40 +1,70 @@
...
 
-(defn placeholder
-  [style child]
-  [rn/view {:style (merge style {:flex 1 :justify-content :center :align-items :center})}
-   child])
+(defn- remove-port
+  [source]
+  (if (string? source)
+    (string/replace-first source #":\d+" "")
+    (string/replace-first (oops/oget source :uri) #":\d+" "")))
```
Comment (seanstrom) [inline src/react_native/fast_image.cljs]: I'm not sure, but does `oops/get` throw an exception if it doesn't find `:uri`?

If so, it might be worth using `goog.object/get` with a default value like: `(goog.object/get source :uri "")`

Comment (ilmotta) [reply src/react_native/fast_image.cljs]: Good question @seanstrom. Some time ago I changed the [default behavior of oops during development](https://github.com/binaryage/cljs-oops?tab=readme-ov-file#play-it-safe-during-development), which is to instrument calls and throw on missing keys. Now it just warns. In advanced compilation instrumentation in oops is disabled by default and we don't have to configure anything special.

https://github.com/status-im/status-mobile/blob/eae887e6b49974547c944c0ec3203dba1f01e8f1/src/status_im/setup/oops.cljs#L5-L12

**Comment by mariia-skrypnyk** [comment]
Hey @ulisesmac !

Will it be needed to test this PR?

**Review by seanstrom — APPROVED** [review]

**Comment by ulisesmac** [comment]
@mariia-skrypnyk Yes, please.

The testing is basically checking that the fixes listed in the description work properly and don't affect something else related.

**Review by alwx — APPROVED** [review]

**Comment by churik** [comment]
maybe it will help with https://github.com/status-im/status-mobile/issues/20982 as well?

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac take a look found issue. Unfortunately, this issue doesn't happen consistently. Hopefully, the logs will help

## PR_ISSUE 1: "No protocol methods IMAP. -dissoc defined" error is shown after onboarding

### Steps:
1. Onboard into app

### Actual result:
"No protocol methods IMAP. -dissoc defined" after onboarding error is shown

https://github.com/user-attachments/assets/60b5c7d1-6429-4891-bf15-1c9ed2184c1b

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1HKl9gvjuD3b3Kv9_QPmYyaKemzcafi1f/view?usp=drive_link

**Comment by ulisesmac** [comment]
@VolodLytvynenko Thank you so much for testing!

I've just fixed the isues!

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac thank you for the fixes. [Issue 1](https://github.com/status-im/status-mobile/pull/21782#issuecomment-2568991885) is fixed

Unfortunately, one more issue is found
## PR_ISSUE 2: 'Cannot Read Property Replace of Undefined' Error After Switching Between Testnet and Mainnet

### Steps to Reproduce:
1. Open the app.
2. Switch the app from Mainnet to Testnet, or vice versa.

### Actual Result:
The error "Cannot read property replace of undefined" is displayed.

https://github.com/user-attachments/assets/e0b3de99-b8ab-47fd-b126-6f7c175a0893

### Expected Result:
The app transitions smoothly between Mainnet and Testnet without any errors.

### Devices Tested:
Pixel 7a (Android 13)
iPhone 11 Pro Max (iOS 17)

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/18335336/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
##PR_ISSUE 3: "Cannot Read Property 'uri' of Null" Error When Opening Join Community Drawer

### Steps to Reproduce:
1. Navigate to any community where you are not currently a member.
2. Tap to join the community.
3. Open the Join Community Drawer.

### Actual Result:
Error Message: "Cannot read property 'uri' of null" is displayed every time the Join Community Drawer is opened.

https://github.com/user-attachments/assets/fc37aceb-58bc-4779-a16e-fc6702c1e4d7

### Expected Result:
The Join Community Drawer should open without errors.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/1L1rJiPT4ZsW9WRjcxTUizKkouRN-puWJ/view?usp=drive_link

**Comment by ulisesmac** [comment]
@VolodLytvynenko 
The implementation had multiple issues everywhere we imported image. It was my fault to do not properly test these places.

It's been fixed now, please re-test it.

Thanks!

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for PR. No issues from my side. PR is ready to be merged
