### PR TITLE
fix fail to open database error message when user enters the wrong password

### LINKED ISSUE #20597: "Fail to open datatbase" error if user enters incorrect password on login screen
# Bug Report

#### Actual behavior
User sees unexpected error when enters incorrect password

Screenshot 2024-06-28 at 12 43 48

[login_logs.zip](https://github.com/user-attachments/files/16028746/login_logs.zip)

#### Expected behavior
Screenshot 2024-06-28 at 13 36 46

https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2941-331293&t=RCx3SlX5MXIDrXcA-0

### Reproduction

1. Install app
2. Create a user
3. Logout
4. Enter incorrect password and try to login

### Additional Information

- Status version: nightly 28/06
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by jo-mut**
fixes https://github.com/status-im/status-mobile/issues/20597

### Summary
When the user enters the wrong password this is the full error message returned `failed to open database: failed to set `journal_mode` pragma: file is not a database`. I did not see the message startwith either `failed to set ` or `Failed` or `file is not a database` but these are the cases that have been handled by the `get-error-message` function. 

Am not sure if getting rid of all these cases and only handling the situation with `(string/starts-with? error "failed to open database")` would do be appropriate maybe the api returns differents messages sometimes. So adding an extra option statement resolves the issue

### Before and after screenshots comparison

status: ready

### CODE REVIEW

File: src/status_im/common/standard_authentication/password_input/view.cljs [hunk 1]
```diff
@@ -1,21 +1,22 @@
...
+   [utils.re-frame :as rf]
+   [utils.security.core :as security]))
 
 (defn- get-error-message
   [error]
   (if (and (some? error)
            (or (= error "file is not a database")
+               (string/starts-with? error "failed to open database")
                (string/starts-with? error "failed to set ")
                (string/starts-with? error "Failed")))
```
Comment (Parveshdhull) [inline src/status_im/common/standard_authentication/password_input/view.cljs]: Maybe just use
```
(or (= error "file is not a database")
  (string/starts-with? (string/lower-case error) "failed")
```

Comment (jo-mut) [reply src/status_im/common/standard_authentication/password_input/view.cljs]: @Parveshdhull  am wondering is there a situation when the error would not start-with `file is not a database` otherwise why would we have the other statements added before

**Review by Parveshdhull — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]
Thanks @jo-mut. Looks good for what we have in status-go right now. It's a good opportunity to mention this sort of code ideally shouldn't exist on clients. Ideally, the error returned by status-go or any backend for that matter should be a data structure, like a map containing the error message and other relevant metadata, but more importantly, it should contain the error's ID/code. Based on the stable ID, clients can decide what to do, but they never match directly against error messages because that's very fragile.

cc @Samyoul @cammellos another example related to what we talked long ago about the lack of error codes and how that can affect clients.

**Comment by jo-mut** [comment]
@ilmotta thanks, I agree with you, its quite fragile, a change of the error string being returned would mean also changing the frontend. An error code would be an optimal solution here.

**Comment by churik** [comment]
this PR can be merged, it is not implemented in automation, so nothing to check or break there. Moving to `merge`.

Thank you!

**Comment by Samyoul** [comment]
@ilmotta consider https://github.com/status-im/status-go/blob/1cdcc0dcc2dcd4b83dac3eab08b5cf73fa982032/services/wallet/router/pathprocessor/errors.go , Sale recently introduced error codes into the Wallet Router package. We can expand on this for other parts of `status-go` and tie user friendly warnings and errors to these codes, rather than relying on the underlying `status-go` error to be meaningful to the users.
