### PR TITLE
Bug/transactions ui refresh bugs (#981)

### LINKED ISSUE #981: Transactions ui-refresh bugs [iOS] [ui-refresh]
Simulator - left side, Zeplin - right side:

1. screen shot 2017-04-07 at 11 48 44

2. screen shot 2017-04-07 at 11 49 13

3. screen shot 2017-04-07 at 11 49 50

- 1. Wrong style for username in transaction item header
- 1. Wrong positions of elements inside transaction item header 
- 2. "Enter your password to ..." label doesn't exist in design
- 2. "Confirm transaction by ..." tip is absent 
- 2. Underline has wrong style
- 3. "Password" label is absent
- 3. "Wrong password" tip wrong style
- 3. Underline wrong style

### PR DESCRIPTION
**Pull request by flexsurfer**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #981

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

File: src/status_im/transactions/styles/screens.cljs [hunk 1]
```diff
@@ -81,38 +88,38 @@
...
   {:font-size   15
    :flex-shrink 1
-   :color       (if name? st/color-light-blue st/color-white)})
+   :color       (if name? common/color-light-blue common/color-white)})
 
 (defstyle details-data
-  {:margin-top       16
-   :padding          16
-   :background-color st/color-dark-blue-3
+  {:padding          20
```
Comment (GustavoNunes) [inline src/status_im/transactions/styles/screens.cljs]: The padding didn't change in the design, it is still 16

**Comment by GustavoNunes** [comment]
Also there's this tiny issue, only on Android: bottom of the text is cropped.

form

Otherwise, everything looks good on both platforms.

**Comment by flexsurfer** [comment]
thank you @GustavoNunes , fixed
