### PR TITLE
fix everyone is displaying as online in community channel and chat list

### LINKED ISSUE #14393: Everyone is displaying as online in chat (channel) view and in chat list
# Bug Report

## Problem 

The online indicator is displayed as `Online` for all users, even for inactive ones, in community channels and in the chat list (`Messages` screen). 

Screenshot 2022-11-17 at 11 28 36

#### Expected behavior
The actual online status of users is displayed

#### Actual behavior
Everyone's status is displaying as online

### Reproduction

For community:
1. Open any community channel
2. Check users' statuses and compare them with their statuses on Desktop or in contacts

Chat list:
1. Open the home screen with 1-1/group chats
2. Check the indicators

### Additional Information

- Status version: nightly 17/11
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/14393

### Summary
Fixes visibility status dot of user avatar for chat list and community channel.
And also fixes issue with visibility status popover not opening.

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Please use ios build for testing, android build is not working
ref: https://discord.com/channels/624205794384281629/626045898878877696/1045149383852826664

File: src/status_im2/subs/general.cljs [hunk 1]
```diff
@@ -12,6 +13,17 @@
...
    (get visibility-status-updates public-key)))
 
+(re-frame/reg-sub
+ :visibility-status-updates/online?
+ (fn [[_ public-key]]
+   [(re-frame/subscribe [:multiaccount/public-key])
+    (re-frame/subscribe [:visibility-status-updates/visibility-status-update public-key])])
+ (fn [[my-public-key visibility-status-update] [_ public-key]]
+   (let [visibility-status-type (:status-type visibility-status-update)]
+     (or (= public-key my-public-key)
```
Comment (flexsurfer) [inline src/status_im2/subs/general.cljs]: could you elaborate why for user we don't want to check his status and always show online ? what if he selected offline ?

Comment (Parveshdhull) [reply src/status_im2/subs/general.cljs]: hi @flexsurfer, thank you for reviewing PR. fixed

**Comment by Parveshdhull** [comment]
### Testing Request
Looks like there might be another bug, automatic status updates are not expiring. Please let me know if this is the case.

**Comment by Parveshdhull** [comment]
> ### Testing Request
> Looks like there might be another bug, automatic status updates are not expiring. Please let me know if this is the case.

Not sure if something is wrong with my PC, but received status updates clock is even higher than current clock.

**Comment by Parveshdhull** [comment]
> > ### Testing Request
> > Looks like there might be another bug, automatic status updates are not expiring. Please let me know if this is the case.
> 
> Not sure if something is wrong with my PC, but received status updates clock is even higher than current clock.

probably some issue with my pc, because clock `(datetime/timestamp)` is not evening matching with online clock `https://currentmillis.com/`

**Comment by Parveshdhull** [comment]
> > > ### Testing Request
> > > Looks like there might be another bug, automatic status updates are not expiring. Please let me know if this is the case.
> > 
> > 
> > Not sure if something is wrong with my PC, but received status updates clock is even higher than current clock.
> 
> probably some issue with my pc, because clock `(datetime/timestamp)` is not evening matching with online clock `https://currentmillis.com/`

Never mind, for some reason my emulator had different time then my pc 🤦‍♂️

File: src/status_im/ui/screens/profile/visibility_status/views.cljs [hunk 2]
```diff
@@ -25,17 +25,11 @@
   (re-frame/dispatch
    [:visibility-status-updates/delayed-visibility-status-update status-type]))
 
-;; In new ui, we are allowing switcher to overlap status-bar (draw over status bar)
-;; that's why the measure will return height including, the height of the status bar in android
-;; for calculating the correct position of the button on the profile screen, we have to decrease this height
```
Comment (Parveshdhull) [inline src/status_im/ui/screens/profile/visibility_status/views.cljs:30]: Not required anymore, probably because status bar `drawBehind=true`. IOS and android are behaving similar

File: src/status_im2/subs/general.cljs [hunk 3]
```diff
@@ -12,6 +13,18 @@
  (fn [visibility-status-updates [_ public-key]]
    (get visibility-status-updates public-key)))
 
+(re-frame/reg-sub
+ :visibility-status-updates/online?
+ :<- [:multiaccount/public-key]
+ (fn [my-public-key [_ public-key]]
+   (let [visibility-status-update
+         (if (= public-key my-public-key)
+           @(re-frame/subscribe [:multiaccount/current-user-visibility-status])
```
Comment (flexsurfer) [inline src/status_im2/subs/general.cljs]: oh im not sure you can subscribe inside subscription function looks wrong

Comment (Parveshdhull) [reply src/status_im2/subs/general.cljs]: hi, please can you check this commit, if this was right way: https://github.com/status-im/status-mobile/commit/0dfba06869b7e59e62d2ae0a3355cb5255ce3445

Comment (Parveshdhull) [reply src/status_im2/subs/general.cljs]: I deleted it because changes in users current visibility status update was affecting(calculating again) subscriptions for all other users.

Comment (flexsurfer) [reply src/status_im2/subs/general.cljs]: for me it looks like we need to add current-user-visibility-status to :visibility-status-updates/visibility-status-update

Comment (Parveshdhull) [reply src/status_im2/subs/general.cljs]: I pushed commit again for confirmation

**Review by flexsurfer — APPROVED** [review]

File: src/status_im2/subs/general.cljs (hunk 3 above)
Comment (flexsurfer) [reply src/status_im2/subs/general.cljs]: > I deleted it because changes in users current visibility status update was affecting(calculating again) subscriptions for all other users.

yes that sounds reasonable, but im not sure this might happen often in real life you need to have chat opened with lots of avatars, and change your status , so doesn't sound like a real-life case

Comment (Parveshdhull) [reply src/status_im2/subs/general.cljs]: > for me it looks like we need to add current-user-visibility-status to :visibility-status-updates/visibility-status-update

yes, that's better

Comment (flexsurfer) [reply src/status_im2/subs/general.cljs]: but your reasoning about subscriptions is really good, i like that :)

Comment (Parveshdhull) [reply src/status_im2/subs/general.cljs]: > > for me it looks like we need to add current-user-visibility-status to :visibility-status-updates/visibility-status-update
> 
> yes, that's better

done, thank you

File: src/status_im/ui/screens/profile/visibility_status/views.cljs (hunk 2 above)
Comment (J-Son89) [reply src/status_im/ui/screens/profile/visibility_status/views.cljs:30]: is there any other parts of the codebase where had issues like this?

Comment (J-Son89) [reply src/status_im/ui/screens/profile/visibility_status/views.cljs:30]: unrelated to your p.r of course :)

File: src/status_im/ui/screens/profile/visibility_status/views.cljs [hunk 4]
```diff
@@ -25,17 +25,11 @@
...
 (defn calculate-button-height-and-dispatch-popover []
   (.measure
    @button-ref
    (fn  [_ _ _ _ _ py]
```
Comment (J-Son89) [inline src/status_im/ui/screens/profile/visibility_status/views.cljs]: can we consider using named parameters instead? also what is `py`?

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/ui/screens/profile/visibility_status/views.cljs (hunk 4 above)
Comment (Parveshdhull) [reply src/status_im/ui/screens/profile/visibility_status/views.cljs]: hi @J-Son89, Thank you for reviewing PR.
py is pageY ([ref](https://github.com/facebook/react-native/blob/65975dd28de0a7b8b8c4eef6479bf7eee5fcfb93/Libraries/Renderer/shims/ReactNativeTypes.js#L18)) (Y offset to page)

But for some reason people usually prefer py. [Example 1](https://stackoverflow.com/a/32751446) [Example 2](https://stackoverflow.com/q/29828971)

changed to page-y ( but not sure if it still  understandable just by name :) )

Comment (Parveshdhull) [reply src/status_im/ui/screens/profile/visibility_status/views.cljs]: @qoqobolo, Please ignore latest commit, it will not affect testing (its only renames one variable)

File: src/status_im/ui/screens/profile/visibility_status/views.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im/ui/screens/profile/visibility_status/views.cljs:30]: > is there any other parts of the codebase where had issues like this?

Only where we are manually calculating position and can't rely on flex layout.
Example visibility popover, switcher (gone now), shell

File: src/status_im/ui/screens/profile/visibility_status/views.cljs (hunk 4 above)
Comment (Parveshdhull) [reply src/status_im/ui/screens/profile/visibility_status/views.cljs]: > but not sure if it still understandable just by name :)

still it is better than py :)

**Comment by qoqobolo** [comment]
LGTM @Parveshdhull! Ready for merge.
