### PR TITLE
Close chat when pop-to-root is called

### LINKED ISSUE #20232: Messages are automatically read in chats/channels if chat/channel is closed by redirection upon community link
Possible regression of https://github.com/status-im/status-mobile/pull/20069 cc @Parveshdhull 

**Steps:** 

1. Open any chat/channel
2. Post community link in chat
3. Follow community link
4. Close community
5. Receive messages in chat/channel
6. See if messages are not read automatically

**Actual result:** Messages are automatically read

https://github.com/status-im/status-mobile/assets/97245802/71216e46-74d0-4eb5-8e8f-c6b3193ccb70

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20232

status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/events.cljs [hunk 1]
```diff
@@ -144,19 +144,21 @@
...
-                                              (assoc-in [:chat/inputs chat-id :focused?] false))
-               :effects.async-storage/set {:chat-id nil
-                                           :key-uid nil}}
-              (link-preview/reset-all)
-              (delete-for-me/sync-all)
-              (delete-message/send-all)
-              (offload-messages chat-id))))
+  [{:keys [db] :as cofx} chat-id]
+  (let [current-chat-id (:current-chat-id db)
+        chat-id         (or chat-id current-chat-id)]
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/events.cljs:149]: I checked that `:chat/close` from `:pop-to-root` is calling first even if we are navigating to community chat from universal link. This is just a precautionary step to avoid silly race condition bugs.

File: src/status_im/contexts/chat/events.cljs [hunk 2]
```diff
@@ -144,19 +144,21 @@
...
+    (when (and current-chat-id (= chat-id current-chat-id))
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/events.cljs:150]: I checked that `:chat/close` from `:pop-to-root` is calling first even if we are navigating to community chat from universal link. This is just a precautionary step to avoid silly race condition bugs.

**Review by flexsurfer — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for quick fix! No issues from my side. Once @yevh-berdnyk approves e2e results PR can be merged and cherrypicked into release go branch cc @jo-mut. So let's wait for @yevh-berdnyk approval.

**Comment by yevh-berdnyk** [comment]
> ## 73% of end-end tests have passed

hi @Parveshdhull, thanks, e2e failures are not PR related!
