### PR TITLE
fix duplicate mention

### LINKED ISSUE #19124: Mentions are duplicated for the sender in a chat if the same mention is sent twice.
### Steps:
1. Open any chat
2. Mention any user twice or more in the message

### Actual result:
The message is shown with duplicated mentions.

https://github.com/status-im/status-mobile/assets/52490791/7e933822-c9ba-48f5-94be-12ea533674de

### Expected result:
Mentions should not be duplicated.

### Logs:
[logs (2).zip](https://github.com/status-im/status-mobile/files/14513335/logs.2.zip)

### ENV:
NIghtly [6 Mar 2024]

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19124

### Summary
For inline render components like `mention` we are nesting all views inside the text component. But parent text component has several limitations compared to the normal view component.
- If the internal text component is directly nested, then we are not able to apply styles like `border-radius`
- If we use a wrapper around that internal text component for styling, and if the internal text component rerenders due to content change then wrapper dimensions are not updated and cause [issue](https://github.com/status-im/status-mobile/issues/18432)
- If we force the rerender wrapper too using key as resolved-mention then it loses positioning and will rerender at the start of the parent text
- The only solution is force rendering of the parent itself.

### Testing Note
- Please also test https://github.com/status-im/status-mobile/issues/18432

status: ready

### CODE REVIEW

File: src/status_im/contexts/chat/messenger/messages/content/text/style.cljs [hunk 1]
```diff
@@ -14,18 +14,18 @@
 
 (defn mention-tag-wrapper
   [first-child-mention]
-  {:flex-direction :row
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/content/text/style.cljs:17]: revert of https://github.com/status-im/status-mobile/pull/19076

File: src/status_im/contexts/chat/messenger/messages/content/text/view.cljs [hunk 2]
```diff
@@ -56,16 +56,14 @@
       :mention
       (conj
        units
-       (let [resolved-mention (rf/sub [:messages/resolve-mention literal])]
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/content/text/view.cljs:60]: revert of https://github.com/status-im/status-mobile/pull/19076

File: src/status_im/contexts/chat/messenger/messages/content/text/view.cljs [hunk 3]
```diff
@@ -107,6 +105,7 @@
                 (render-inline acc e chat-id style-override mention-first))
               [quo/text
                {:size  :paragraph-1
+                :key   (rand-int 1000000) ;; https://github.com/status-im/status-mobile/pull/19203
```
Comment (Parveshdhull) [inline src/status_im/contexts/chat/messenger/messages/content/text/view.cljs:109]: only this change is new

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull !
Mentions are working correct now.
Thanks for your fix!
