### PR TITLE
Fix channel-action component

### LINKED ISSUE #19021: Fix chat action buttons pressed color
# Bug Report
From the [design review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=8065:58901&mode=design#645046711), when pressed in, the chat action button should have a darker color, according to the [design system ](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=866-26242&mode=design&t=2llHRg1afJlAPCC1-4). 

## Problem 
[comment]: # (A problem description)

#### Expected behavior
the button is darker when pressed in

#### Actual behavior
the button is light when pressed in

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19021

### Summary

For the `channel-action` component was fixed according to the [design system](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=866-26242&mode=design&t=8DbWIrF1gaxVFo7V-4):
1. The color when button is pressed in
2. The big button is using flexbox now instead of fixed width, to assure it looks right on all screens
3. Separated `channel-action` from `channel-actions`, according to the design system
4. Added preview screen for `channel-action`

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Open a chat
- Press the channel action (button should have a different color)
- (or go to preview -> community -> channel-action(s))

status: ready

### CODE REVIEW

**Comment by J-Son89** [comment]
Thanks for moving these out into separate components 🙏

File: src/quo/components/community/channel_action.cljs [hunk 1]
```diff
@@ -0,0 +1,39 @@
+(ns quo.components.community.channel-action
+  (:require
+    [quo.components.community.style :as style]
+    [quo.components.counter.counter.view :as counter]
+    [quo.components.icon :as icons]
+    [quo.components.markdown.text :as text]
+    [quo.theme :as quo.theme]
```
Comment (J-Son89) [inline src/quo/components/community/channel_action.cljs]: nit: just [quo.theme] 👍

File: src/quo/components/community/channel_action.cljs [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    [react-native.core :as rn]))
+
+(defn view
+  [{:keys [big? color label counter-value icon on-press accessibility-label disabled?]}]
+  (let [theme                  (quo.theme/use-theme-value)
+        [pressed? set-pressed] (rn/use-state false)
+        on-press-in            (rn/use-callback #(set-pressed true))
```
Comment (J-Son89) [inline src/quo/components/community/channel_action.cljs]: do we really need to wrap functions without dependencies in use-callback?

File: src/quo/components/community/channel_action.cljs [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+  (:require
+    [quo.components.community.style :as style]
+    [quo.components.counter.counter.view :as counter]
+    [quo.components.icon :as icons]
+    [quo.components.markdown.text :as text]
+    [quo.theme :as quo.theme]
+    [react-native.core :as rn]))
+
+(defn view
+  [{:keys [big? color label counter-value icon on-press accessibility-label disabled?]}]
```
Comment (J-Son89) [inline src/quo/components/community/channel_action.cljs]: please update api to `customization-color` to align with other quo components

File: src/quo/components/community/channel_action.cljs (hunk 2 above)
Comment (clauxx) [reply src/quo/components/community/channel_action.cljs]: it's to avoid re-creating the functions on every re-render

File: src/quo/components/community/style.cljs [hunk 4]
```diff
@@ -133,18 +133,24 @@
...
-  [color]
-  {:padding          12
-   :height           102
-   :flex             1
+  [{:keys [color pressed? theme]}]
+  {:flex             1
+   :padding          12
    :border-radius    16
-   :background-color (colors/custom-color color 50 10)
+   :background-color (colors/resolve-color color theme (if pressed? 20 10))
```
Comment (J-Son89) [inline src/quo/components/community/style.cljs]: hmm, this color is ever a community color (hex string)? or it is always a custom-color (:blue :army etc)?

Comment (clauxx) [reply src/quo/components/community/style.cljs]: always a custom color i think from how it was used before

File: src/quo/components/community/channel_actions.cljs [hunk 5]
```diff
@@ -1,32 +1,16 @@
 (ns quo.components.community.channel-actions
```
Comment (J-Son89) [inline src/quo/components/community/channel_actions.cljs]: can we move this to a view file.
`quo.components.community.channel-actions.view`

File: src/quo/components/community/channel_action.cljs [hunk 6]
```diff
@@ -0,0 +1,39 @@
+(ns quo.components.community.channel-action
```
Comment (J-Son89) [inline src/quo/components/community/channel_action.cljs]: can we move this to a view file.
`quo.components.community.channel-action.view`

File: src/quo/components/community/channel_actions.cljs (hunk 5 above)
Comment (J-Son89) [reply src/quo/components/community/channel_actions.cljs]: also it's better to use one style file for each component.
quo.components.community.channel-actions.view
quo.components.community.channel-actions.style 
and
quo.components.community.channel-actions.view
quo.components.community.channel-action.style

for shared styles it's better to do so through encapsulation with components 👍

File: src/quo/components/community/style.cljs (hunk 4 above)
Comment (J-Son89) [reply src/quo/components/community/style.cljs]: but like for community channels is this color based off the community color or the community channel color?
If it's community channel color than this is grand 👍

Comment (clauxx) [reply src/quo/components/community/style.cljs]: hmm idk, so far this component is only used in the chat and currently it's drilled through ~6 components starting with this :crystal_ball: 
```clj
:cover-bg-color    :turquoise
```

File: src/quo/components/community/style.cljs [hunk 7]
```diff
@@ -133,18 +133,24 @@
...
-  {:flex      1
-   :max-width (if big? 216 104)})
+(defn channel-action-container
+  [{:keys [big? disabled?]}]
+  (cond-> {:height 102}
+    disabled?  (assoc :opacity 0.3)
+    ;; NOTE: The big action has to fill the available space when there's a small
+    ;; action next to it. If alone, take an approx. proportion of space ~2/3.
+    ;; Using fixed sizes according to the designs will make it look wrong on
+    ;; all other devices.
```
Comment (Parveshdhull) [inline src/quo/components/community/style.cljs]: Hi, Thank you for fixing the issue

> If alone, take an approx. proportion of space ~2/3.

Please can you provide reference for this. Means a use case where we have it alone?

Comment (Parveshdhull) [reply src/quo/components/community/style.cljs]: Also, can something like this work?
```
(cond-> {:height 102 :flex 1}
    disabled?  (assoc :opacity 0.3)
    (not big?) (assoc :max-width 104)
```

Comment (clauxx) [reply src/quo/components/community/style.cljs]: no specific use-cases, but up until a while back, there was only one big action for the pinned messages and no mute action in the chat, but it had a fixed size back then. 

Your example will definitely work, except that the big one alone will always take up the entire space, which might look weird when testing it in the preview :man_shrugging:

Comment (clauxx) [reply src/quo/components/community/style.cljs]: maybe I can add a prop to `channel-action` for fixed/dynamic size and `channel-actions` will pass it as fixed if it's only one

Comment (Parveshdhull) [reply src/quo/components/community/style.cljs]: > but it had a fixed size back then

Ok, in that case, can we use something like

```
(cond-> {:height 102 :flex 1:max-width "Add fixed width here"}
    disabled?  (assoc :opacity 0.3)
    (not big?) (assoc :max-width 104)
```

Comment (clauxx) [reply src/quo/components/community/style.cljs]: The thing is, I don't know what `:max-width` should be. If we use the one from the designs, it will be smaller on some devices e.g. on the pixel devices we use the big button doesn't take up the entire space when used with 2 actions

File: src/status_im/contexts/preview/quo/community/channel_action.cljs [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+  []
+  (let [state (reagent/atom {:label         "Action"
+                             :icon          :i/muted
+                             :color         :blue
+                             :counter-value nil
+                             :disabled?     false
+                             :big?          true})]
+    (fn []
+      [preview/preview-container {:state state :descriptor descriptor}
+       [rn/view {:style {:flex 1 :flex-direction :row}}
```
Comment (flexsurfer) [inline src/status_im/contexts/preview/quo/community/channel_action.cljs]: current implementation for channel-action is wrong, there shouldn't be any `[rn/view {:style {:flex 1 :flex-direction :row}}` container to make component work properly, see here i have already fixed that https://github.com/status-im/status-mobile/pull/19032/files#diff-37c5c05d51d3ac0ba6b52c73251d65f42334c528ad3956e3ee6290d46df594c5
https://github.com/status-im/status-mobile/pull/19032/files#diff-78028f7d9a49eba44bc1fe0cb1fe64d62267c67faadfa15bb5b2ddc1b97bddd0

File: src/quo/components/community/style.cljs (hunk 4 above)
Comment (J-Son89) [reply src/quo/components/community/style.cljs]: ok seems good as is so.

File: src/status_im/contexts/preview/quo/community/channel_action.cljs (hunk 8 above)
Comment (clauxx) [reply src/status_im/contexts/preview/quo/community/channel_action.cljs]: thanks, fixed :+1:

File: src/quo/components/community/style.cljs (hunk 7 above)
Comment (clauxx) [reply src/quo/components/community/style.cljs]: simplified it and will see how the design review goes :smiling_face_with_tear:

File: src/quo/components/community/channel_actions/view.cljs~ [hunk 9]
```diff
@@ -0,0 +1,16 @@
+(ns quo.components.community.channel-actions
```
Comment (J-Son89) [inline src/quo/components/community/channel_actions/view.cljs~]: is this file needed?

Comment (J-Son89) [reply src/quo/components/community/channel_actions/view.cljs~]: 💣 ??

File: src/quo/components/community/style.cljs [hunk 10]
```diff
@@ -133,25 +133,6 @@
                       colors/neutral-80
```
Comment (J-Son89) [inline src/quo/components/community/style.cljs:133]: hmm this file still seems in the wrong place - 
src/quo/components/community/style.cljs is like at the folder level, can we move it to sit beside it's corresponding `view` file?

File: src/quo/components/community/channel_actions/view.cljs~ (hunk 9 above)
Comment (clauxx) [reply src/quo/components/community/channel_actions/view.cljs~]: uff apologies :D

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 11]
```diff
@@ -143,28 +143,28 @@
...
-                                                    mute-chat-label))
-                 :color               cover-bg-color
-                 :icon                (if muted? :i/activity-center :i/muted)
-                 :on-press            (fn []
-                                        (if muted?
-                                          (home.actions/unmute-chat-action chat-id)
-                                          (home.actions/mute-chat-action chat-id
-                                                                         chat-type
-                                                                         muted?)))}]}]))
+     {:container-style {:margin-top 16}
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs]: 🙏

File: src/status_im/contexts/chat/messenger/messages/list/view.cljs [hunk 12]
```diff
@@ -143,28 +143,28 @@
...
+      :actions         [{:accessibility-label :action-button-pinned
+                         :big?                true
+                         :label               (or latest-pin-text (i18n/label :t/no-pinned-messages))
+                         :customization-color cover-bg-color
```
Comment (J-Son89) [inline src/status_im/contexts/chat/messenger/messages/list/view.cljs:150]: 👍

File: src/quo/components/community/style.cljs (hunk 10 above)
Comment (clauxx) [reply src/quo/components/community/style.cljs:133]: this seems to be an old ns. This file holds styles for a bunch of components from community, so better have a separate PR to clean it up

Comment (J-Son89) [reply src/quo/components/community/style.cljs:133]: ah sorry I thought it was associated with src/quo/components/community/channel_actions/view.cljs.

yeah separate issue to fix sounds good 👍

File: src/quo/components/community/channel_actions/view.cljs~ (hunk 9 above)
Comment (clauxx) [reply src/quo/components/community/channel_actions/view.cljs~]: done :boom:

**Review by J-Son89 — APPROVED** [review]
nice one @clauxx!

File: src/status_im/contexts/preview/quo/community/channel_actions.cljs [hunk 13]
```diff
@@ -8,21 +8,22 @@
...
+    {:actions [{:big?                true
+                :label               "Pinned Messages"
+                :customization-color :blue
+                :icon                :i/pin
+                :counter-value       0}]}]
    [rn/view {:height 50}]
    [quo/channel-actions
-    {:actions [{:label "Pinned Messages" :color :blue :icon :i/pin :counter-value 5}
-               {:label "Mute chat" :color :blue :icon :i/muted}]}]
+    {:actions [{:label "Pinned Messages" :customization-color :blue :icon :i/pin :counter-value 5}
```
Comment (J-Son89) [inline src/status_im/contexts/preview/quo/community/channel_actions.cljs]: nit about the formatting, I think we generally align map keys, no?

File: src/quo/components/community/channel_action/style.cljs [hunk 14]
```diff
@@ -0,0 +1,27 @@
...
+
+(defn channel-action-container
+  [{:keys [big? disabled?]}]
+  (cond-> {}
+    disabled?  (assoc :opacity 0.3)
+    ;; NOTE: The big action has to fill the available space when there's a small
+    ;; action next to it. If alone, take an approx. proportion of space ~2/3.
+    ;; Using fixed sizes according to the designs will make it look wrong on
+    ;; all other devices.
+    big?       (assoc :flex-grow 1)
```
Comment (Parveshdhull) [inline src/quo/components/community/channel_action/style.cljs]: Hi, Thank you for addressing this. Do we need this comment? I think code is self explanatory.

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@clauxx thanx for the PR. Could you please rebase and resolve existing conflicts so we proceed with testing? Thank you.

**Comment by clauxx** [comment]
@pavloburykh done :+1:

**Comment by qoqobolo** [comment]
Thanks for the fix @clauxx!
@Francesca-G could you also check this and confirm it does look correct now, please?

**Review by Francesca-G — APPROVED** [review]
Looks good ✨
