### PR TITLE
fix: error is shown when asset is selected on select assets screen

### LINKED ISSUE #18228: An error is shown when asset is selected on select assets screen
Unfortunately, there are no specific steps to reproduce this issue. It occurs randomly and very rarely. Hopefully, the logs might help to understand what's going on

### Steps:
1. Recover the user with some assets
2. Go to select asset screen ([link](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-193169&mode=design&t=nNMPQS6vCmCJwSTJ-0) of flow how to get this 'select asset' screen)
3. Tap any asset
image

### Actual result:
Error is shown
image

### Expected result:
Error is not shown when asset is selected

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13713087/Status-debug-logs.1.zip)

### Env:
Nightly [19 Dec 2023]

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18228

### Summary

Based on the logs provided I can guess this line https://github.com/status-im/status-mobile/blob/2e684b35c50151229c9a001e942197c4fd9ed876/src/status_im/contexts/wallet/send/input_amount/view.cljs#L19 is causing a crash if for some reason the input amount screen is loaded before de DB is updated. I am adding a fallback value to token-symbol binding to prevent the crash.

Relevant logs:

```
12-19 10:14:58.410 10249 10383 D ReactNativeJS: 2023-12-19T08:14:58.409Z DEBUG [utils.re-frame:22] - Handling re-frame event:  :wallet/send-select-token
12-19 10:14:58.425 10249 10383 I ReactNativeJS: Running "wallet-send-input-amount
12-19 10:14:58.435 10249 10383 E ReactNativeJS: Error: Doesn't support name: 
12-19 10:14:58.435 10249 10383 E ReactNativeJS: 
12-19 10:14:58.435 10249 10383 E ReactNativeJS: This error is located at:
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in kLd
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in reagent86
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in Qp
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in b
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in RCTView
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in Unknown
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in rH
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in reagent85
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in RNGestureHandlerRootView
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in GestureHandlerRootView
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in gestureHandlerRootHOC(reagent85)
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in WrappedComponent
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in RCTView
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in Unknown
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in RCTView
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in Unknown
12-19 10:14:58.435 10249 10383 E ReactNativeJS:     in AppContainer, js engine: hermes
12-19 10:14:58.436 10249 10383 I ReactNativeJS: PRETTY PRINTED EXCEPTION
12-19 10:14:58.436 10249 10383 I ReactNativeJS: 
12-19 10:14:58.436 10249 10383 I ReactNativeJS: ***
12-19 10:14:58.436 10249 10383 I ReactNativeJS: NAME: "Error"
12-19 10:14:58.436 10249 10383 I ReactNativeJS: MESSAGE: Doesn't support name: 
12-19 10:14:58.436 10249 10383 I ReactNativeJS: 
12-19 10:14:58.436 10249 10383 I ReactNativeJS: Error: Doesn't support name: 
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at $f (address at index.android.bundle:1:4013989)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at OKd (address at index.android.bundle:1:7061711)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at anonymous (address at index.android.bundle:1:7063303)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at call (native)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at Jca (address at index.android.bundle:1:3989388)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at anonymous (address at index.android.bundle:1:7183299)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at lna (address at index.android.bundle:1:4091771)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at anonymous (address at index.android.bundle:1:4092614)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at Cma (address at index.android.bundle:1:4085510)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at Sma (address at index.android.bundle:1:4087720)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at mna (address at index.android.bundle:1:4092390)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at kLd (address at index.android.bundle:1:4092855)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at renderWithHooks (address at index.android.bundle:1:8655867)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at beginWork$1 (address at index.android.bundle:1:8697753)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at performUnitOfWork (address at index.android.bundle:1:8684122)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at workLoopSync (address at index.android.bundle:1:8683983)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at renderRootSync (address at index.android.bundle:1:8683865)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at performSyncWorkOnRoot (address at index.android.bundle:1:8681276)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at flushSyncCallbacks (address at index.android.bundle:1:8645475)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at scheduleUpdateOnFiber (address at index.android.bundle:1:8678401)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at updateContainer (address at index.android.bundle:1:8689422)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at anonymous (address at index.android.bundle:1:8698787)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at renderElement (address at index.android.bundle:1:8412610)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at renderApplication (address at index.android.bundle:1:8574256)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at run (address at index.android.bundle:1:8567750)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at runApplication (address at index.android.bundle:1:8568242)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at apply (native)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at __callFunction (address at index.android.bundle:1:8403644)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at anonymous (address at index.android.bundle:1:8401976)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at __guard (address at index.android.bundle:1:8402931)
12-19 10:14:58.436 10249 10383 I ReactNativeJS:     at callFunctionReturnFlushedQueue (address at index.android.bundle:1:8401934)
```

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Recover the user with some assets
- Go to select asset screen ([link](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=689-193169&mode=design&t=nNMPQS6vCmCJwSTJ-0) of flow how to get this 'select asset' screen)
- Tap any asset
- Hopefully the error is not shown anymore

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 1]
```diff
@@ -57,7 +57,7 @@
         networks                  (rf/sub [:wallet/network-details])
         token                     (rf/sub [:wallet/wallet-send-token])
         loading-suggested-routes? (rf/sub [:wallet/wallet-send-loading-suggested-routes?])
-        token-symbol              (:symbol token)
+        token-symbol              (or (:symbol token) :eth)
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: are we sure we want to default to eth? could this lead to some confusion ever? Is there a "safer" alternative if so?

Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: Not sure, but it should be imperceptible, because as soon as `:wallet/wallet-send-token` sub updates, `token-symbol` should have the correct value, which should happen really fast.

Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: @briansztamfater @J-Son89 I think the reason for this to break is something different.


This `token-symbol` is in the "on mount" part of the component, so when props change, the code isn't re executed:
```clojure
(defn component [props]
  (let [,,,
        token-symbol (or (:symbol token) :eth) ;;<- here
        ,,,]
    (fn [props]
      [rn/view ,,,]))) ;; <- instead of here
```

Also something not common is many of the involved  subs are in the "on mount" part :thinking:  It's  weird because the error is given by `make-limit-label`, if we follow the dependency chain:

`make-limit-label` -> `@current-limit` -> `token-symbol` (the var that now has a falback) -> `(rf/sub [:wallet/wallet-send-token])`

we see that the sub is declared to be only executed once, so I think the value won't be updated to have the correct one :thinking: 

Anynway, about a cleaner solution, I think about two options:

1. making the sub ` (rf/sub [:wallet/wallet-send-token])` return fallback values when the DB is empty.

2. (easier) Make the function that is breaking (`make-limit-label`) able to work with `nil` values:
```clojure
(defn- make-limit-label
  [{:keys [amount currency]}]
  (str amount " " (string/upper-case (name currency)))) ;; an option is to use `some->`
```
so we get:
```clojure
(defn- make-limit-label
  [{:keys [amount currency]}]
  (str amount " " (some-> currency name string/upper-case)))
```

But we should notice this is the same problem we have been having in other PRs about taking a token symbol and transform it to a user-friendly name, and we should do it in a more general way.

BTW another thing is we rename`token-symbol` as  `currency` in this component, that could lead to confusion, I think we usually call `currency` to fiat related vars (e.g. USD).

Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: @ulisesmac I changed the approach to yours :) LMK if that's okay so we can start testing this PR as is blocking others

**Review by ulisesmac — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater ! Thanks for your PR. 

Yes,hopefully the error is not shown anymore :)

Please, merge your fix and rebase this [PR](https://github.com/status-im/status-mobile/pull/18330)
Thanks a lot!
