### PR TITLE
Bug/communities missing data

### LINKED ISSUE #15302: Community cards UI issues (Discover community screen)
Might be followup of https://github.com/status-im/status-mobile/pull/15095 cc @jo-mut 

### ISSUE 1 Community name and description are not fetched within community card on Discover community screen (IOS only)

reproducible on IOS only

**Steps:**

1. Recover user who is member of communities created on desktop
2. Open Discover community screen
3. See if Community name and description are fetched within community card 

**Expected result:** Community name and description are fetched within community card 

**Actual result:** Community name and description are not fetched within community card 

https://user-images.githubusercontent.com/97245802/224288029-c1bd279c-4a40-4ff7-b9f8-5330e17abfc0.mp4

### PR DESCRIPTION
**Pull request by jo-mut**
fixes #15302

### Summary
This PR addresses some of the following issues

- display missing data on community cards in discover screen
- polishes on featured communities horizontal display

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im/utils/money.cljs [hunk 1]
```diff
@@ -225,8 +225,12 @@
...
   [count]
-  (if (> count 1000000)
+  (cond
+    (> count 1000000)
     (str (with-precision (/ count 1000000) 1) (i18n/label :t/M))
-    (if (and (> count 999) (< count 1000000))
-      (str (with-precision (/ count 1000) 1) (i18n/label :t/K))
-      count)))
+
+    (and (> count 999) (< count 1000000))
```
Comment (ilmotta) [inline src/status_im/utils/money.cljs]: @jo-mut, interestingly in Lisps, the `>` or `<` symbols are functions, and they accept a variable number of arguments. This might seem strange coming from other languages where `<` & `>` are "operators" that only work with two numbers.

Here in Clojure it's more idiomatic to take advantage of this. Check it out, the snippets below show that the original conditional logic you're using is identical in behavior to the new suggestion, since none of the `assert` calls throw an exception.

So in summary, you can use ` (< 999 count 1000000)` instead of ` (and (> count 999) (< count 1000000))` to represent the logic of a number *between* two others.

Edit: I forgot to add the `=` function for the assertion, but the code is still the same.

```clojure
(let [count 998]
  (assert (= (< 999 count 1000000)
             (and (> count 999) (< count 1000000)))))

(let [count 999]
  (assert (= (< 999 count 1000000)
             (and (> count 999) (< count 1000000)))))

(let [count 1000]
  (assert (= (< 999 count 1000000)
             (and (> count 999) (< count 1000000)))))

(let [count 999999]
  (assert (= (< 999 count 1000000)
             (and (> count 999) (< count 1000000)))))

(let [count 1000000]
  (assert (= (< 999 count 1000000)
             (and (> count 999) (< count 1000000)))))

(let [count 1000001]
  (assert (= (< 999 count 1000000)
             (and (> count 999) (< count 1000000)))))
```

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 2]
```diff
@@ -22,23 +21,26 @@
...
-(defn render-fn
-  [community-item _ _ {:keys [width view-type]}]
-  (let [item  (merge community-item
-                     (get mock-community-item-data :data))
-        cover {:uri (get-in (:images item) [:banner :uri])}]
+(defn community-list-item
+  [item _ _ {:keys [width view-type ids?]}]
+  (let [community (merge
+                   (if ids?
+                     (rf/sub [:communities/home-item item])
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/view.cljs]: @jo-mut, the following is just a suggestion :)

It seems we can remove the workaround where the `community-list-item` function needs to deal with a sequence of community IDs or a sequence of communities and the whole usage of the `ids?` flag. I think it's cleaner if the callers that use `community-list-item` fetch all the community maps/objects if they're just IDs.

In the code below, notice the new subscription `:communities/from-ids`. This subscription would also encapsulate the logic to use mock data or not, something that's not so good from the current `community-list-item` function, since it knows too much (it knows if the data should be mocked or not). As you know, `featured-list` would also need a similar change.

```clojure
(defn community-list-item
  [{:keys [id] :as community} _ _ {:keys [width view-type]}]
  (let [cover {:uri (get-in (:images community) [:banner :uri])}]
    (if (= view-type :card-view)
      [quo/community-card-view-item (assoc community :width width :cover cover)
       #(rf/dispatch [:navigate-to :community-overview id])]
      [quo/communities-list-view-item
       {:on-press      (fn []
                         (rf/dispatch [:communities/load-category-states id])
                         (rf/dispatch [:dismiss-keyboard])
                         (rf/dispatch [:navigate-to :community {:community-id id}]))
        :on-long-press #(rf/dispatch
                         [:bottom-sheet/show-sheet
                          {:content (fn [] [options/community-options-bottom-sheet id])}])}])))

(defn other-communities-list
  [{:keys [communities communities-ids view-type ids?]}]
  (let [communities (if ids?
                      (rf/sub [:communities/from-ids communities-ids])
                      communities)]
    [rn/view style/other-communities-container
     [rn/flat-list
      {:key-fn                       :id
       :keyboard-should-persist-taps :always
       :separator                    [rn/view {:height 16}]
       :data                         communities
       :render-fn                    community-list-item
       :contentContainerStyle        style/flat-list-container
       :render-data                  {:view-type view-type}}]]))
```

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 3]
```diff
@@ -107,9 +108,24 @@
            :shows-horizontal-scroll-indicator false
            :separator                         [rn/view {:width 12}]
            :data                              communities
-           :render-fn                         render-fn
+           :render-fn                         community-list-item
            :render-data                       {:width     @view-size
-                                               :view-type view-type}}])])))
+                                               :view-type view-type
+                                               :ids?      false}
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/view.cljs]: I couldn't find a single usage of `:ids?` as true, but it's probably just me failing to find it. Do you know where do we pass `:ids?` as true?

File: src/status_im/communities/core.cljs [hunk 4]
```diff
@@ -793,4 +793,4 @@
                                {:error        %
                                 :community-id community-id
                                 :public-key   public-key
-                                :role-id      role-id})]})
+                                :role-id      role-id})]})
```
Comment (ilmotta) [inline src/status_im/communities/core.cljs]: It'd be better if you could keep the trailing newline character, since we use the Clojure Style Guide.

**Review by ilmotta — APPROVED** [review]

File: src/status_im/utils/money.cljs (hunk 1 above)
Comment (jo-mut) [reply src/status_im/utils/money.cljs]: @ilmotta looks better this way

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 3 above)
Comment (jo-mut) [reply src/status_im2/contexts/communities/discover/view.cljs]: @ilmotta I can adapt the solution differently without using the flag in this case

Comment (ilmotta) [reply src/status_im2/contexts/communities/discover/view.cljs]: Great :100: I hope it's not too much trouble

Comment (jo-mut) [reply src/status_im2/contexts/communities/discover/view.cljs]: @ilmotta  its fine. The `:ids` flag was actually based on old code and this changed and did not notice when i pulled from develop so its fine

File: src/status_im2/common/scroll_page/view.cljs [hunk 5]
```diff
@@ -117,7 +117,7 @@
       [:<>
        [:f> scroll-page-header @scroll-height height name page-nav-right-section-buttons
         logo sticky-header top-nav title-colum navigate-back?]
-       [rn/scroll-view
+       [rn/flat-list
```
Comment (flexsurfer) [inline src/status_im2/common/scroll_page/view.cljs]: could you please elaborate on why flat-list ?

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im2/contexts/communities/discover/view.cljs]: thanks @ilmotta good point, we should avoid having subs in the item render functions

File: src/status_im2/common/scroll_page/view.cljs (hunk 5 above)
Comment (jo-mut) [reply src/status_im2/common/scroll_page/view.cljs]: @flexsurfer i preferred flat-list here because communities may end up being quite a long list which may have cause perfomance issues with scroll-view

Comment (flexsurfer) [reply src/status_im2/common/scroll_page/view.cljs]: but i don't see a data, only header is used, could you elaborate?

Comment (jo-mut) [reply src/status_im2/common/scroll_page/view.cljs]: @flexsurfer Before this was using a scroll-view and the data was a map-indexed collection which would probably have perfomance issue if the collection became quite large. The header renders a flat-list populated with communities and in this context communities of the discover screen.  Using a scroll-view in this case leads to having the warning `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation` hence why flat-list is used. The main reason why  the flat-list is used here is to avoid the warning while using a flat-list to renders discover communities

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 3 above)
Comment (ilmotta) [reply src/status_im2/contexts/communities/discover/view.cljs]: Oh nice to hear :)

File: src/quo2/components/community/community_card_view.cljs [hunk 6]
```diff
@@ -16,15 +16,13 @@
                  :height        230
                  :border-radius 20}
       :on-press on-press}
-     [rn/view
-      {:flex 1}
+     [rn/view {:flex 1}
```
Comment (smohamedjavid) [inline src/quo2/components/community/community_card_view.cljs]: Should we place the style map under `:style`?

File: src/status_im/utils/money.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im/utils/money.cljs]: In case it helps, I often think about the `<` function like you can put it *between* the numbers, like what we do in math notation. I learned about this visualization trick from an old blog post. The same logic can be used for just 2 numbers using other comparison functions, for example `(> index 10)` could be represented in math as `index > 10`, so that's how I never forgot what these comparison functions do and how they work :)

```clojure
(< 999 count 1000000)

;; Conceptually the same as this in math notation:
;; 999 < count < 1000000
```

File: src/status_im2/common/scroll_page/view.cljs (hunk 5 above)
Comment (flexsurfer) [reply src/status_im2/common/scroll_page/view.cljs]: but it doesn't make sense, children must be in the data rendered as list items, not in header?

**Review by flexsurfer — CHANGES_REQUESTED** [review]
figure out flat list usage

File: src/status_im2/common/scroll_page/view.cljs (hunk 5 above)
Comment (jo-mut) [reply src/status_im2/common/scroll_page/view.cljs]: @flexsurfer in this case I did not find another way to use a flat-list. The scroll-page component may have to be restructured to be able to render item using render-fn. 

I suggest to merge this as is at the moment and then refactor the scroll-page component so that the data is rendered as list-items as you suggested in a follow up pr. 

The challenge here the scroll-page component is to be used by different screens with the same functionality and the data may largely differ which is why I opted to just render the children in the flat-list header

Comment (flexsurfer) [reply src/status_im2/common/scroll_page/view.cljs]: i mean i don't understand why this change is needed then if it doesn't fix anything

Comment (jo-mut) [reply src/status_im2/common/scroll_page/view.cljs]: @flexsurfer maybe its not necessary but my reasoning using a `map-indexed` with scroll-view maybe okay for a small list of communities and messages but when the data is quite large there may be perfomance issue as flat-list is lazy loading while map-indexed is not. I can revert this for now as I look into how to use flat-list in this context if necessary

Comment (flexsurfer) [reply src/status_im2/common/scroll_page/view.cljs]: map-indexed with scroll-view is bad and should be never used, but i don't see any changes related to map-indexed i only see that we move content of scroll view into flat list header

**Comment by jo-mut** [comment]
@flexsurfer I reverted this change. The scroll component maybe need to be refactored for better use of flat-list. That can be handled in a follow up pr atleast so I can merge this one for the next release.

**Comment by jo-mut** [comment]
@flexsurfer I would appreciate your approval of this pr so QA can pick it up for manual testing. The suggestiong relating to flatlist on scroll-page component can be handled in a separate follow up pr

File: src/status_im/utils/money.cljs [hunk 7]
```diff
@@ -225,8 +225,12 @@
 
 (defn format-members
   [count]
-  (if (> count 1000000)
+  (cond
```
Comment (flexsurfer) [inline src/status_im/utils/money.cljs]: could you pls elaborate on this change ?

File: src/status_im/utils/money.cljs [hunk 8]
```diff
@@ -225,8 +225,12 @@
...
+    (> count 1000000)
     (str (with-precision (/ count 1000000) 1) (i18n/label :t/M))
-    (if (and (> count 999) (< count 1000000))
-      (str (with-precision (/ count 1000) 1) (i18n/label :t/K))
-      count)))
+
+    (< 999 count 1000000)
```
Comment (flexsurfer) [inline src/status_im/utils/money.cljs]: `(< 999 count 1000000)` looks wrong

File: src/status_im/utils/money.cljs (hunk 7 above)
Comment (flexsurfer) [reply src/status_im/utils/money.cljs]: `if` is better and faster than case

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 9]
```diff
@@ -120,7 +122,8 @@
    [screen-title]
    [featured-communities-header featured-communities-count]
    [featured-list featured-communities view-type]
-   [quo/separator]
+   [rn/view {:style {:margin-horizontal 20}}
+    [quo/separator]]
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: `separator ` has a style key, so no need in extra view

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 10]
```diff
@@ -107,9 +107,11 @@
            :shows-horizontal-scroll-indicator false
            :separator                         [rn/view {:width 12}]
            :data                              communities
-           :render-fn                         render-fn
+           :render-fn                         community-list-item
            :render-data                       {:width     @view-size
-                                               :view-type view-type}}])])))
+                                               :view-type view-type}
+           :contentContainerStyle             style/flat-list-container}])])))
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: kebab

File: src/status_im2/contexts/communities/discover/style.cljs [hunk 11]
```diff
@@ -68,4 +69,4 @@
    :left               0
    :justify-content    :center
    :flex               1
-   :background-color   :transparent})
+   :background-color   :transparent})
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/style.cljs]: empty line

**Review by flexsurfer — COMMENTED** [review]
please rollback all end lines

File: src/status_im2/contexts/communities/discover/view.cljs (hunk 10 above)
Comment (flexsurfer) [reply src/status_im2/contexts/communities/discover/view.cljs]: still not resolved

**Review by flexsurfer — APPROVED** [review]

**Comment by jo-mut** [comment]
@status-im/mobile-qa this is ready. Could you please have a look. thanks

**Comment by pavloburykh** [comment]
@jo-mut thanx for the fixes. 

Could you please clarify if [issue 2](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584561) and [issue 3](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584677) are in scope of this PR. Cause I am still reproducing both. Thank you.

**Comment by pavloburykh** [comment]
> @jo-mut thanx for the fixes.
> 
> Could you please clarify if [issue 2](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584561) and [issue 3](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584677) are in scope of this PR. Cause I am still reproducing both. Thank you.

@jo-mut one clarification regarding [issue 2](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584561): Background image is fetched for community card within horizontal scroll list but not fetched within vertical scroll list

https://user-images.githubusercontent.com/97245802/228280254-7b7bd1ca-e85c-4808-89b1-e6a9575f2d84.mp4

**Comment by jo-mut** [comment]
@pavloburykh  I had reverted some changes but missed to update that. Should be okay now.

**Comment by jo-mut** [comment]
> @jo-mut thanx for the fixes.
> 
> Could you please clarify if [issue 2](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584561) and [issue 3](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584677) are in scope of this PR. Cause I am still reproducing both. Thank you.

yes they both are

File: src/status_im2/contexts/communities/discover/view.cljs [hunk 12]
```diff
@@ -131,14 +133,16 @@
       (let [community-id (when communities-ids item)
             community    (if communities
                            item
-                           [rf/sub [:communities/home-item community-id]])]
+                           [rf/sub [:communities/home-item community-id]])
```
Comment (flexsurfer) [inline src/status_im2/contexts/communities/discover/view.cljs]: `(rf/sub`

**Comment by pavloburykh** [comment]
> > @jo-mut thanx for the fixes.
> > Could you please clarify if [issue 2](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584561) and [issue 3](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584677) are in scope of this PR. Cause I am still reproducing both. Thank you.
> 
> yes they both are

hi @jo-mut Still reproducing [issue 3](https://github.com/status-im/status-mobile/issues/15302#issuecomment-1463584677) in the latest PR build.

**Comment by jo-mut** [comment]
@pavloburykh my thinking is `issue 3` must only be reproducible on android but not ios. It works quite fine on ios. I am unable to test on android at the moment but once I manage I will update. Thanks

**Comment by jo-mut** [comment]
@pavloburykh `issue 3:` is now fixed.

**Comment by pavloburykh** [comment]
> @pavloburykh `issue 3:` is now fixed.

@jo-mut  thanx for the fix. 

Still not able to scroll community tabs within the card on horizontal cards list. Reproducible only on Android (Samsung Galaxy A52, Android 12)

At the same time am able to scroll tags on Vertical cards list and on community screen. 

On IOS works fine at all places. 

https://user-images.githubusercontent.com/97245802/228814342-dad4860c-f6ff-46d1-8876-022c61cab064.mp4

**Comment by jo-mut** [comment]
@pavloburykh works fine now

https://user-images.githubusercontent.com/28704507/228878110-7e1eed88-d3a6-4ca7-9295-46f8beb28b0a.mov

**Comment by pavloburykh** [comment]
@jo-mut thanx for the fixes. Ready to be merged.
