### PR TITLE
[Fix] Open app on push notification tap

### LINKED ISSUE #15998: App is not bringing to foreground when tapping on PN
# Bug Report

## Problem 
Reproduced with new **Google Pixel 7A** devices.

Nothing happens when tapping on PNs which should bring the app to the foreground, however the redirect to corresponding chat inside app is happening

#### Expected behavior
the app opens with a corresponding 1-1 chat

#### Actual behavior
https://github.com/status-im/status-mobile/assets/4557972/c1d57305-9f1a-4252-8f25-4b9510b819bf

### Reproduction

**Prerequisites:** user A and user B are contacts, user B has enabled PN

- User B: minimize the app
- User A: send a message to User B
- User B: try to tap on a message from notification center

### Additional Information

- Status version: nightly 23/05/2023
- Operating System: Android13, Google Pixel 7A

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15998

## Summary

This PR fixes the notification issue in Android, where the app is not open (bought to the foreground) when the user taps on the notification.

Log from `adb logcat`:

```
NotificationService: Indirect notification activity start (trampoline) from im.status.ethereum blocked
```

The bug is caused due to the [notification changes](https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines) introduced in **Android 12**, which restricts opening the app (starting activity) through `service` or `broadcast`.

The mobile app uses `broadcast` to receive notification actions such as `ON_TAP`, `DELETE`, and `STOP`. The broadcast receiver takes care of performing the tasks for the respective actions.

### Changes done:

- Removed the `ON_TAP` action from the broadcast and makes sure that the activity is launched from the notification builder.
- Fixed a minor type casting bug in the `createMessage` method

### Platforms

- Android

#### Prerequisites: User `A` and User `B` are mutual contacts. User `B` has enabled Push Notifications.

- User `B` minimizes the app
- User `A` send a message to User `B`
- User `B` try to tap on a message from the notification centre

#### Does the solution work in older versions of Android?

Yes, It will work. This is the standard way of opening the app on notification tap.

status: ready

### CODE REVIEW

File: modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java [hunk 1]
```diff
@@ -701,37 +695,31 @@ private Person getPerson(Bundle bundle) {
 
     private StatusMessage createMessage(Bundle data) {
         Person author = getPerson(data.getBundle("notificationAuthor"));
-        return new StatusMessage(data.getString("id"), author,  data.getLong("timestamp"), data.getString("message"));
+        long timeStampLongValue = (long) data.getDouble("timestamp");
```
Comment (smohamedjavid) [inline modules/react-native-status/android/src/main/java/im/status/ethereum/pushnotifications/PushNotificationHelper.java:698]: The following error is discovered using `adb logcat`

```java
Bundle  : Key timestamp expected Long but value was a java.lang.Double.  The default value 0 was returned.
Bundle  : Attempt to cast generated internal exception:
Bundle  : java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
                  at android.os.BaseBundle.getLong(BaseBundle.java:1289)
                  at android.os.BaseBundle.getLong(BaseBundle.java:1271)
                  at im.status.ethereum.pushnotifications.PushNotificationHelper.createMessage(PushNotificationHelper.java:704)
                  at im.status.ethereum.pushnotifications.PushNotificationHelper.addStatusMessage(PushNotificationHelper.java:765)
                  at im.status.ethereum.pushnotifications.PushNotificationHelper.handleConversation(PushNotificationHelper.java:193)
```
Added appropriate fix by type casting.

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Thanks for your amazing work!
e2e failures are known not related to PR.
Redirect is working on Android devices now.

**Devices:**
- IPhone 12 Mini (IOS 16)
- Xiaomi Mi Note 9 Pro (Android 10)
- Google Pixel 7A (Android 13)
