### PR TITLE
fix(wallet)_: Send flow for collectibles

### LINKED ISSUE #21727: User sees Select assets screen when navigates back to send collectible
# Bug Report

User sees screen he should not see in Send Collectibles flow

### Reproduction

1. Login with user who has collectibles
2. Go the the Wallet home screen
3. Go to Collectibles tab
4. Choose any Collectible and open it
5. Find Send button and tap
6. Go through Send flow: From -> Send to ->
7. Go back  to From and go next

#### Actual behavior

User sees Select assets screen he should not see in Send Collectibles flow

https://github.com/user-attachments/assets/af23dcb4-f116-4aca-8f65-a5affb359037

#### Expected behavior

No Select assets screen

### Additional Information

- Status version: nightly 02/12
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21727

### Summary

This PR fixes 

 - the send flow for collectibles (ERC721 and ERC1155)
 - picking the right balance of the ERC1155 in the send flow from the account page, based on the account viewing by the user
 - the balance of ERC1155 is sometimes incorrect if the collectible is present in more than one account of the user

https://github.com/user-attachments/assets/544e987b-048f-4284-9b87-c25c6a0d95f3

### Testing notes

This PR doesn't fix the balance of the collectible after it's been sent. It's handled in different issue: https://github.com/status-im/status-mobile/issues/21483.

### Platforms

- Android
- iOS

#### ERC721
- Open Status
- Navigate to Wallet tab > Collectibles
- Tap on any ERC721 and tap on Send
- Verify the account of the collectible is automatically selected
- Verify the user is taken to select the recipient

#### ERC1155
- Open Status
- Navigate to Wallet tab > Collectibles
- Tap on any ERC155 which is present in two accounts and tap on Send
- Verify the user is taken to select the account to send from

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/collectible/utils.cljs [hunk 1]
```diff
@@ -69,3 +67,14 @@
...
+(defn remove-duplicates-in-ownership
+  [ownership]
+  (->> ownership
+       (reduce (fn [acc {:keys [address timestamp] :as owner}]
+                 (let [existing-owner (get acc address)]
+                   (if (or (nil? existing-owner) (> timestamp (:timestamp existing-owner)))
+                     (assoc acc address owner)
+                     acc)))
+               {})
+       vals))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/collectible/utils.cljs:80]: Sometimes, the status-go returns duplicate data in the list, we do a cleanup based on the address and timestamp of the balance.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 2]
```diff
@@ -120,12 +120,13 @@
...
  (fn [{:keys [db]} [{:keys [address recipient stack-id start-flow?]}]]
    (let [[_ to-address]   (utils/split-prefix-and-address address)
+         sender           (get-in db [:wallet :current-viewing-account-address])
          collectible-tx?  (send-utils/tx-type-collectible?
                            (-> db :wallet :ui :send :tx-type))
          collectible      (when collectible-tx?
                             (-> db :wallet :ui :send :collectible))
          one-collectible? (when collectible-tx?
-                            (= (collectible.utils/collectible-balance collectible) 1))]
+                            (= (collectible.utils/collectible-balance collectible sender) 1))]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/events.cljs:129]: Picking the right balance of the collectible to send.

Previously, we took the first balance in the list, which may not be the right balance of the selected account.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -257,16 +257,22 @@
...
+               (not entry-point-wallet-home?))
+       {:db (update-in db
+                       [:wallet :ui :send]
+                       dissoc
+                       :collectible
+                       :collectible-multiple-owners?
+                       :token-display-name
+                       :amount
+                       (when (send-utils/tx-type-collectible? transaction-type)
+                         :tx-type))}))))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/events.cljs:275]: We skip cleaning the selected collectible on navigating back (the user will land on the `From` screen) from the select recipient screen if the collectible is present in multiple accounts.

File: src/status_im/contexts/wallet/send/from/view.cljs [hunk 4]
```diff
@@ -5,40 +5,56 @@
...
 
 (defn- on-account-press
-  [address network-details]
+  [address network-details collectible-tx?]
   (rf/dispatch [:wallet/select-from-account
                 {:address         address
                  :network-details network-details
                  :stack-id        :screen/wallet.select-from
-                 :start-flow?     true}]))
+                 :start-flow?     (not collectible-tx?)}]))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/send/from/view.cljs:22]: If it's a collectible tx, the flow is already started.

**Comment by mohsen-ghafouri** [comment]
Hey @smohamedjavid, would you mind also check and advice about this issue?https://github.com/status-im/status-mobile/issues/21483
when i was testing i notice that `:wallet/collectibles-data-updated` recieved wrong balance (current balance and not updated data), I also tried to fetch manually after update but that didn't work too, so IMO the only way to fix it in status-go side. wdyt?

also my draft PR https://github.com/status-im/status-mobile/pull/21867 (not working properly yet)

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM

File: src/status_im/contexts/wallet/send/events.cljs [hunk 5]
```diff
@@ -283,37 +289,48 @@
...
             (assoc-in [:wallet :ui :send :amount] 1))
-      :fx [(when (and one-collectible? recipient-set?)
-             [:dispatch [:wallet/start-get-suggested-routes {:amount 1}]])
-           [:dispatch
-            [:wallet/wizard-navigate-forward
-             {:current-screen current-screen
-              :start-flow?    start-flow?
-              :flow-id        :wallet-send-flow}]]]})))
+      :fx (if
+            ;; If the is present in multiple accounts, the user will be taken to select the address
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/events.cljs]: If the collectible*

**Review by briansztamfater — APPROVED** [review]

File: src/status_im/contexts/wallet/collectible/utils.cljs [hunk 6]
```diff
@@ -5,13 +5,11 @@
...
-                    :ownership
-                    first
-                    :balance
-                    js/parseInt)]
-    (if (js/Number.isNaN balance) 0 balance)))
+  ([{:keys [ownership]} address]
+   (let [balance (some #(when (= address (:address %))
+                          (js/parseInt (:balance %)))
+                       ownership)]
+     (if (js/Number.isNaN balance) 0 balance))))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/collectible/utils.cljs:12]: There's a helper for parsing numbers that allows to pass a default `utils.number/parse-int`

**Review by clauxx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. Unfortunately, one issue has been found, but it's okay if it will be fixed in a separate follow-up. Let me know if this will be addressed in this PR, otherwise, the PR can be merged
PR_ISSUE 1: https://github.com/status-im/status-mobile/issues/21882

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - I will fix it in a follow-up PR 👍
