### PR TITLE
Fix keycard L1-L1 transaction failing

### LINKED ISSUE #21533: `Insufficient funds...0 balance` error when signing L1-L1 transaction by keycard
**Preconditions:** account has keycard set and has tokens on L1 network. 

**Steps:** 

1. Initiate L1-L1 transaction
2. Sign transaction via keycard
3. Observe the error (NOTE: the error might not occur form the first try. Perform couple of transactions to catch it. In average 3 of 7 transactions fail with this error

**Actual result:** 

[Status-debug-logs - 2024-10-30T160628.762.zip](https://github.com/user-attachments/files/17574083/Status-debug-logs.-.2024-10-30T160628.762.zip)

Image

https://github.com/user-attachments/assets/d9793290-a1bc-41f5-b219-45daefd547bf

### Additional Information

- Status version: nightly, release 2.31
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by clauxx**
fixes #21533

### Summary

Seems like the issue is in the `v` component of the signature and the values that are passed. Looking at this [status-go function](https://github.com/status-im/status-go/blob/b329b158c8f62f5bab03be596cf4f7d7b07c96f7/services/wallet/transfer/helpers.go#L75), if the value is 1, it gets set to 0 instead, invalidating the signature. Seems like for a v of 1, we should just send "01" as it expects, instead of parsing it and sending "1".

So it makes sense that it would fail just sometimes, since when v is 0 it should work as expected, cause it's the default.

```go
		rBytes, _ := hex.DecodeString(sigDetails.R)
		sBytes, _ := hex.DecodeString(sigDetails.S)
		vByte := byte(0)
		if sigDetails.V == "01" { // here is the check, but it's weird 
			vByte = 1
		}

		desc.signature = make([]byte, crypto.SignatureLength)
		copy(desc.signature[32-len(rBytes):32], rBytes)
		copy(desc.signature[64-len(rBytes):64], sBytes)
		desc.signature[64] = vByte // otherwise becomes 0 here

```

## Testing
I checked a few times and seems to work, but don't have enough funds to test it as much

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/keycard/sign/events.cljs [hunk 1]
```diff
@@ -6,7 +6,7 @@
   [tx-hash signature]
   {tx-hash {:r (subs signature 0 64)
             :s (subs signature 64 128)
-            :v (str (js/parseInt (subs signature 128 130) 16))}})
+            :v (subs signature 128 130)}})
```
Comment (briansztamfater) [inline src/status_im/contexts/keycard/sign/events.cljs:9]: Could we move this function to a utils file?
Also, wdyt of adding unit tests for this function? I think it can serve as documentation for a complex feature like keycard.

**Comment by alwx** [comment]
We can merge this one but in the new transaction flow I already moved it to utils namespace (and fixed as well): 
https://github.com/status-im/status-mobile/pull/21541/files#diff-6379c7a5055825d77e6e5e5f78afb970e1a4bbf691173be9c91076d0fcc426f7R263

**Comment by VolodLytvynenko** [comment]
hi @clauxx thank you for PR. No issues from my side. PR is ready to be merged
