### PR TITLE
fix empty screen when opening I'm new to Status screen after closing sign in screen

### LINKED ISSUE #20213: Empty screen when opening I'm new to Status screen after closing Sing in screen
**Steps:** 

1. Open fresh installed app
2. Open Sign in screen and quickly close it
3. Open I'm new to Status screen
4. Observe the result

**Actual result:** empty screen is opened. 

https://github.com/status-im/status-mobile/assets/97245802/64b4c510-0613-48ee-8fef-8693878eed86

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/20213

### Testing Note:
Please also test https://github.com/status-im/status-mobile/issues/18369

status: ready

### CODE REVIEW

File: src/status_im/contexts/onboarding/intro/view.cljs [hunk 1]
```diff
@@ -19,19 +20,16 @@
...
+     :top-card            {:on-press            #(rf/dispatch [:open-modal
+                                                               :screen/onboarding.sign-in-intro])
                            :heading             (i18n/label :t/sign-in)
                            :animated-heading    (i18n/label :t/sign-in-by-syncing)
                            :accessibility-label :already-use-status-button}
      :bottom-card         {:on-press            (fn []
                                                   (when-let [blur-show-fn @overlay/blur-show-fn-atom]
                                                     (blur-show-fn))
-                                                  (debounce/throttle-and-dispatch
-                                                   [:open-modal :screen/onboarding.new-to-status]
```
Comment (Parveshdhull) [inline src/status_im/contexts/onboarding/intro/view.cljs:33]: we were showing blur-overlay, but because of throttle we were not able to open the screen

Comment (Parveshdhull) [reply src/status_im/contexts/onboarding/intro/view.cljs:33]: As now we already throttle all on-presses, we don't need debounce anymore.

(mobile qa, please make sure https://github.com/status-im/status-mobile/issues/18369 is still fixed)

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the fix! PR is ready for merge and cherrypickig into release branch cc @jo-mut
