### PR TITLE
[#21649] Backup recovery phrase flow into Settings

### LINKED ISSUE #21649: Old backup flow in Profile instead of new one we use in Wallet and Keycard
# Bug Report

We need to make a `Backup recovery phrase` consistency all over the app.

### Reproduction

1. Create new Profile
2. Go to Profile -> Backup recovery phrase

#### Actual behavior

Here is how old flow looks like:

Image

#### Expected behavior

Example of Backup flow design from Keycard

Image

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3369-58996&node-type=frame&t=4Osm8WMs7FB6Q0iU-0

### Additional Information

- Status version: nightly 20/11
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21649 

## Summary

This PR implements the "backup recovery phrase" flow into settings, to achieve it, the blur variant of the flow had to be implemented too.

Demo on iOS:

https://github.com/user-attachments/assets/c090aa2b-e106-42e5-ae14-e104ffb11461

on Android:

https://github.com/user-attachments/assets/df1bbfe0-be49-44f1-899d-9686865deb45

## Review notes

Please make sure other usages of this flow are still working (in wallet and keycard). The keycard flow already had multiple inconsistencies and they are reported here:
- https://github.com/status-im/status-mobile/issues/22389

### Platforms
[comment]: # (Optional. Specify which platforms should be tested)

- Android
- iOS

status: ready

### CODE REVIEW

File: src/quo/components/counter/counter/style.cljs [hunk 1]
```diff
@@ -3,31 +3,35 @@
...
 
 (defn get-color
-  [type customization-color theme]
+  [type customization-color theme blur?]
   (case type
     :default   (colors/resolve-color customization-color theme)
     :secondary (colors/theme-colors colors/neutral-80-opa-5 colors/white-opa-5 theme)
-    :grey      (colors/theme-colors colors/neutral-10 colors/neutral-80 theme)
+    :grey      (if blur?
+                 (colors/theme-colors colors/neutral-80-opa-10 colors/white-opa-10 theme)
```
Comment (ulisesmac) [inline src/quo/components/counter/counter/style.cljs:11]: Implements only the required variant for the checkboxes, this component is incomplete, it's been reported here:
- https://github.com/status-im/status-mobile/issues/22386

File: src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs [hunk 2]
```diff
@@ -32,52 +33,72 @@
...
     [:<>
      [quo/drawer-top {:title (i18n/label :t/complete-backup)}]
      [quo/text
       {:style style/cheat-description}
       (i18n/label :t/ensure-written-recovery)]
-     [quo/disclaimer
-      {:checked?        checked?
-       :container-style {:margin-horizontal 20}
-       :on-change       #(set-checked (not checked?))}
-      (i18n/label :t/written-seed-ready)]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/new_keypair/confirm_backup/view.cljs:80]: We were using a disclaimer but the designs show something different :eyes: it's been changed

File: src/status_im/contexts/profile/settings/list_items.cljs [hunk 3]
```diff
@@ -2,13 +2,38 @@
...
+         :on-success         navigate-to-challenge}]))))
 
 (defn items
-  [mnemonic?]
-  [(when mnemonic?
+  [mnemonic]
+  [(when mnemonic
      [{:title            (i18n/label :t/back-up-seed-phrase)
-       :on-press         #(rf/dispatch [:open-modal :backup-seed])
+       :on-press         (on-backup-seed-phrase-press mnemonic)
```
Comment (flexsurfer) [inline src/status_im/contexts/profile/settings/list_items.cljs]: it should be `(rn/use-callback #(on-backup-seed-phrase-press % mnemonic)`

File: src/status_im/contexts/profile/settings/list_items.cljs [hunk 4]
```diff
@@ -2,13 +2,38 @@
...
-            [utils.re-frame :as rf]))
+            [utils.re-frame :as rf]
+            [utils.security.core :as security]))
+
+(defn on-backup-seed-phrase-press
+  [mnemonic]
+  (let [end-backup            (fn []
+                                (rf/dispatch [:navigate-back-to :settings])
+                                (rf/dispatch [:my-profile/finish]))
+        navigate-to-challenge (fn [masked-seed-phrase]
```
Comment (flexsurfer) [inline src/status_im/contexts/profile/settings/list_items.cljs]: better to move to defined functions

File: src/status_im/navigation/screens.cljs [hunk 5]
```diff
@@ -1217,6 +1218,20 @@
      :options   {:insets {:top? true :bottom? true}}
      :component backup-recovery-phrase/view}
 
+    {:name      :screen/backup-recovery-phrase-on-shell
```
Comment (flexsurfer) [inline src/status_im/navigation/screens.cljs:1220]: what is on-shell ?

File: src/status_im/contexts/profile/backup_recovery_phrase/style.cljs [hunk 6]
```diff
@@ -53,8 +54,28 @@
...
+
+(def words-colum
+  {:flex             1
+   :row-gap          12
+   :padding-vertical 8})
+
+(defn seed-phrase-blur-overlay
+  [shell? theme]
+  (cond-> {:flex 1}
+    (and platform/android? shell?)   (assoc :background-color "#3f4959")
```
Comment (flexsurfer) [inline src/status_im/contexts/profile/backup_recovery_phrase/style.cljs]: this looks like some magic, why do we need all these ? and custom color not from colors ns

File: src/status_im/contexts/profile/backup_recovery_phrase/view.cljs [hunk 7]
```diff
@@ -2,123 +2,167 @@
...
     [quo.core :as quo]
     [react-native.core :as rn]
-    [reagent.core :as reagent]
+    [status-im.common.events-helper :as events-helper]
     [status-im.contexts.profile.backup-recovery-phrase.style :as style]
     [utils.i18n :as i18n]
     [utils.re-frame :as rf]
     [utils.security.core :as security]))
 
+(def ^:private step-labels
```
Comment (flexsurfer) [inline src/status_im/contexts/profile/backup_recovery_phrase/view.cljs:14]: have you refactored this screen?

**Review by flexsurfer — COMMENTED** [review]
thank you @ulisesmac , i think wile we are here, it's time to fix mnemonic as plain text in the db and secure it

File: src/status_im/contexts/profile/backup_recovery_phrase/view.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/backup_recovery_phrase/view.cljs:14]: Yes, I did, mostly refactored to make it faster to render and also use hooks instead of ratoms, and eliminate the usage of a flat list for just 4 items

File: src/status_im/contexts/profile/settings/list_items.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/settings/list_items.cljs]: We can't use the hook here, but I'll check how to memoize the fn.

File: src/status_im/navigation/screens.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/navigation/screens.cljs:1220]: The shell version of the flow, we have 3 versions:
- The one for regular screens (wallet)
- The dark one you used
- The shell version for profile settings

File: src/status_im/contexts/profile/backup_recovery_phrase/style.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/backup_recovery_phrase/style.cljs]: I forgot to add the comment 🤦‍♂️

This is the overlay opaque color calculated for Android, since we don't have blur. I calculate it by using an online calculator to add colors, but I'll check if a color already defined fits well.

Thanks for spotting it!

**Comment by ulisesmac** [comment]
> thank you @ulisesmac , i think wile we are here, it's time to fix mnemonic as plain text in the db and secure it

Yeah, I've seen it comes as a plan text string. I'll fix it 👍

**Comment by ulisesmac** [comment]
> > thank you @ulisesmac , i think wile we are here, it's time to fix mnemonic as plain text in the db and secure it
> 
> Yeah, I've seen it comes as a plan text string. I'll fix it 👍

Update:

@flexsurfer The task of properly storing the mnemonic masked and making sure no regressions are introduced, I believe should be addressed in its own issue. The current issue has a different scope and we have multiple usages of the keyword `:mnemonic` in different contexts, so it'll make the review, development and testing harder.

**Comment by ulisesmac** [comment]
@flexsurfer if all is fine, could you please approve so I can move this to review?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/profile/backup_recovery_phrase/view.cljs [hunk 8]
```diff
@@ -2,123 +2,167 @@
...
+   [quo/counter {:type :grey :blur? true}
+    index]
+   [quo/text text]])
+
+(defn words-column
+  [{:keys [starting-index words]}]
+  [rn/view {:style style/words-colum}
+   (map-indexed (fn [idx word]
+                  (let [word-number (+ starting-index idx)]
+                    (with-meta [word-item {:index word-number :text word}]
```
Comment (ilmotta) [inline src/status_im/contexts/profile/backup_recovery_phrase/view.cljs:42]: Is there a specific reason to prefer `with-meta` instead of the metadata syntax with `^{...}` ?

File: src/status_im/contexts/profile/backup_recovery_phrase/view.cljs [hunk 9]
```diff
@@ -2,123 +2,167 @@
...
-             :button-one-label (i18n/label :t/reveal-phrase)
-             :button-one-props {:disabled?           (some false? (vals @checked?))
-                                :customization-color customization-color
-                                :on-press            #(reset! revealed? true)}
-             :container-style  style/slide-button}])]))))
+  (let [{:keys             [on-success masked-seed-phrase shell? back-button?]
+         initial-revealed? :revealed?} (quo.context/use-screen-params)
+        [revealed? set-revealed]       (rn/use-state initial-revealed?)
+        reveal-seed-phrase             (rn/use-callback #(set-revealed true))
+        [seed-phrase set-seed-phrase]  (rn/use-state (or (some-> masked-seed-phrase
```
Comment (ilmotta) [inline src/status_im/contexts/profile/backup_recovery_phrase/view.cljs:129]: An interesting abstraction to think about in the future is to have a special hook that abstracts away the manual task of persisting the text masked, which is more error prone. Something like `use-masked-text`. Also the hook would always return a masked text so there would be less of a risk of pass around an unmasked text around.

**Review by ilmotta — APPROVED** [review]
LGTM @ulisesmac, nice work as usual on identifying unrelated bugs, but helping track them for future work.

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac thank you for PR. Take a look at a found issue

## ISSUE 1: Incorrect numbering shown on backup recovery phrase screen

### Steps to reproduce:
1. Go to the backup recovery phrase page.
2. Check the numbering of the seed phrase words.

### Actual result:
Words for the seed phrase are incorrectly numbered:
- First 6 words are marked as 1-6.
- Remaining words are also marked as 1-6 instead of continuing.
image

### Expected result:
Words for the seed phrase should be numbered 1-12 in total and sequentially.

File: src/status_im/contexts/profile/backup_recovery_phrase/view.cljs (hunk 8 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/backup_recovery_phrase/view.cljs:42]: I've seen multiple times the metadata doesn't survive when nested or with complex operations.

So I prefer to use the `^{...}` syntax when the expression is very simple. For this case it works in both ways

File: src/status_im/contexts/profile/backup_recovery_phrase/view.cljs (hunk 9 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/backup_recovery_phrase/view.cljs:129]: It'd be interesting to introduce something like that.

**Comment by ulisesmac** [comment]
@VolodLytvynenko Thanks for spotting it, it's fixed now

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac the issue 1 is fixed. One more issue is found. Take a look it please

## PR_ISSUE 2: [IOS] Navigation to backup recovery phrase screen is delayed

### Steps:
1. Go to profile -> Tap 'backup recovery phrase' button
 

### Actual result:
The "Backup recovery phrase" screen opens with a noticeable delay.

https://github.com/user-attachments/assets/6c9dc36d-0e21-4b70-b18f-822f0a564bdb

### Expected result:
The Backup recovery phrase screen should open instantly without delay.

### Devices:
- iPhone 11 Pro Max, IOS 17

### Logs
https://drive.google.com/file/d/11foWTuzCF_YObiYLZeDeIk2zLtOf9sPM/view?usp=drive_link

**Comment by ulisesmac** [comment]
@VolodLytvynenko the reasons for this bug are unknown, it seems if you navigate to the three bottom tabs before it solves by itself.

I changed the way the navigation screens are pushed in order to comply with designs, since it created this bug, I preferred to have the same navigation structure as the other settings. We can explore the proper nav when we migrate to another library.

Now the issue reported is solved, thanks for testing

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for fixes. PR is tested and can be merged

**Comment by VolodLytvynenko** [comment]
Tested flows:

Flows with Backup Seed Phrase
✅ Onboard via Key Card –>  Backup
✅ Back up via Profile
✅ Back up via Profile → Key Card 
✅ Generate New Keypair – Ensure the seed phrase is correctly displayed when generating a new keypair.

Verification:
✅ Check if the correct seed phrase is generated in all flows and restorable
