### PR TITLE
[#21323] fix: wrong networks when asset not available in default account

### LINKED ISSUE #21323: Incorrect Select Network appears after navigation back from the changed account
# Bug Report
Followup https://github.com/status-im/status-mobile/pull/21269
It’s better to address the current issue after or alongside Issue [#21557](https://github.com/status-im/status-mobile/issues/21557), as only once the FROM page is implemented will we be able to link the network balances drawer to the selected assets from the account chosen on the FROM page.

#### Expected behavior
The drawer with networks should display the balances of selected accounts in [FROM page list](https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=1691-48511&node-type=instance&m=dev)

#### Actual behavior
- The network drawer displays the balance related to default account (Account 1)
- The network drawer with an unexpected appearance is shown if the default account does not hold the long-tapped asset, even if the secondary account does.
Screenshot 2024-09-25 at 14 55 52

### Reproduction
1. Go to wallet main page
2. Long-tap on an asset available only on both `account 1` and `account 2`
3. Tap `swap` option.

### Additional Information
Here is a [list of test cases](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?gid=0#gid=0) related to the current feature

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21323

### Summary

The drawer with networks should display the balances of correct account

#### Areas that maybe impacted

- Swap asset

### Steps to test

- Go to wallet main page
- Long-tap on an asset available only second account, and not present in default account 
- Tap swap option.

### Result

https://github.com/user-attachments/assets/18e8c1ce-0e72-414b-9ca1-8de2e98ed13d

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/swap/events.cljs [hunk 1]
```diff
@@ -19,16 +19,17 @@
          test-networks-enabled? (get-in db [:profile/profile :test-networks-enabled?])
          view-id                (:view-id db)
          root-screen?           (or (= view-id :wallet-stack) (nil? view-id))
-         account                (or from-account (swap-utils/wallet-account wallet))
+         available-accounts     (utils/get-accounts-with-token-balance (:accounts wallet)
+                                                                       (:asset-to-pay data))
+         account                (or from-account (swap-utils/wallet-account wallet available-accounts))
```
Comment (vkjr) [inline src/status_im/contexts/wallet/swap/events.cljs]: As far as I understood, the logic for selecting account it is:
`from-account` OR `current-viewing-account` OR `(first available-accounts)`

But in current implementation this logic split in two parts. One `OR` happens here, in the event code and another `OR` inside `swap-utils/wallet-acocunt`.
I'd suggest to make it more obvious. 
We can move all the logic inside `swap-utils/wallet-account` and also rename it to something more obvious, like `swap-utils/swap-from-account`. 
Another approach is to simplify `swap-utils/wallet-account` to only contain `current-viewing-account` (and rename it appropriately and make all `OR`s inside the event code:
```clojure
[account (or from-account 
             (swap-utils/current-viewing-account)
             (first available-accounts))]
```

This will make the logic easier to comprehend by code reader. Wdyt?

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/events.cljs]: thanks @vkjr,  make sense, pushed changes

File: src/status_im/contexts/wallet/swap/utils.cljs [hunk 2]
```diff
@@ -30,33 +30,20 @@
...
-   or the first operable account."
+(defn current-viewing-account
   [wallet]
   (if-let [wallet-address (get wallet :current-viewing-account-address)]
     (-> wallet
         :accounts
         vals
         (utils/get-account-by-address wallet-address))
-    (-> wallet :accounts first-operable-account)))
+    nil))
```
Comment (vkjr) [inline src/status_im/contexts/wallet/swap/utils.cljs]: `when-let` can be used to avoid this `nil`

**Review by vkjr — APPROVED** [review]

File: src/status_im/contexts/wallet/swap/utils.cljs [hunk 3]
```diff
@@ -30,33 +30,19 @@
...
+(defn current-viewing-account
   [wallet]
-  (if-let [wallet-address (get wallet :current-viewing-account-address)]
+  (when-let [wallet-address (get wallet :current-viewing-account-address)]
     (-> wallet
         :accounts
         vals
-        (utils/get-account-by-address wallet-address))
-    (-> wallet :accounts first-operable-account)))
+        (utils/get-account-by-address wallet-address))))
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/swap/utils.cljs]: Not related to the PR changes but can't resist. Apologies.

The wallet accounts in app-db are indexed by their address. The above extraction could be:

```clojure
(get-in wallet [:accounts wallet-address])
```

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im/contexts/wallet/swap/utils.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/swap/utils.cljs]: Thanks @smohamedjavid for pointing this out. done.

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thank you for you PR!

I tested by cases from [table](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?usp=sharing) and find next issue for cases №6. Please check it

**ISSUE1: "Select network" drawer displays information for a different account than the one chosen in the "From" drawer.**
Preconditions:
2 empty account (default keypair)
2 account with token (import keypair)
Token -  Wrapped Ether.
0,00026 =0,00014 (first acc, Arb+Opt) + 0,00012 (second acc, Opt)

**Steps:**

1. Longtap on **Wrapped Ether** on owerview in wallet
2. Click on "Swap" action in menu
3. Select the second account with 0.00012 WETH
4. Observe the information displayed in the "Select network" drawer

**Expected results:**

- The "Select network" drawer should display accurate information about the account chosen in the "From" drawer.
- If the selected account has tokens on only one network, the "Select network" drawer should not appear, and the user should be redirected to the next step in the swap flow.

**Actual results:**
The "Select network" drawer displays information about a different account, specifically one with tokens on two networks, instead of the chosen account.

https://github.com/user-attachments/assets/a9782e63-4b09-4fb2-92b6-998b81fa31b2

Logs: 
[logs (8).zip](https://github.com/user-attachments/files/17949099/logs.8.zip)

**Comment by Horupa-Olena** [comment]
> @mohsen-ghafouri Thank you for you PR!
> 
> I tested by cases from [table](https://docs.google.com/spreadsheets/d/1fOg99N5f9Q0zfJQcIqllPU1RK3Y93Uy_CumzlXV1Y9M/edit?usp=sharing) and find next issue for cases №6. Please check it
> 
> **ISSUE1: "Select network" drawer displays information for a different account than the one chosen in the "From" drawer.** Preconditions: 2 empty account (default keypair) 2 account with token (import keypair) Token - Wrapped Ether. 0,00026 =0,00014 (first acc, Arb+Opt) + 0,00012 (second acc, Opt)
> 
> **Steps:**
> 
> 1. Longtap on **Wrapped Ether** on owerview in wallet
> 2. Click on "Swap" action in menu
> 3. Select the second account with 0.00012 WETH
> 4. Observe the information displayed in the "Select network" drawer
> 
> **Expected results:**
> 
> * The "Select network" drawer should display accurate information about the account chosen in the "From" drawer.
> * If the selected account has tokens on only one network, the "Select network" drawer should not appear, and the user should be redirected to the next step in the swap flow.
> 
> **Actual results:** The "Select network" drawer displays information about a different account, specifically one with tokens on two networks, instead of the chosen account.
> 
>  IMG_0077.MP4 
> Logs: [logs (8).zip](https://github.com/user-attachments/files/17949099/logs.8.zip)

@mohsen-ghafouri If needed, I can help you set up a profile to reproduce the bug on your side, or I can provide you with a seed phrase and backup. However, some setup will still be required, as accounts are currently restored randomly.

**Comment by mohsen-ghafouri** [comment]
Hey @Horupa-Olena, could you please check again? it should be fine now

https://github.com/user-attachments/assets/6640571a-3896-427b-89cc-afb8708cff92

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your fix!
Everything looks good, and the PR can be merged.
