### PR TITLE
Change view-id as per the selected bottom tab and refactor subscriptions

### LINKED ISSUE #15609: Android performance issues
Android app navigation becomes laggy and twitchy after opening a lot of different community pages. 

For reproduction you may use this user, who already has a long list of communities: rule dirt shuffle vintage trash cricket gesture door more robust fine tooth

**Steps:** 

1. Recover given above user
2. Wait until backed up communities will appear in community list
3. Open Discover community screen
4. Start opening communities from the list one by one
5. Pay attention at navigation behaviour changes while opening more community screens

**Actual result:** the more community screens are opened the more laggy navigation becomes. Navigation becomes normal again after reopening the app. 

It is slightly visible on recorded video below, better to reproduce on real device via given user:

https://user-images.githubusercontent.com/97245802/230903054-12dc5646-8ba9-4ee9-83a7-f9cd800e8f86.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/15609

### Summary
- view-id will be changed as per selected bottom tabs
 (used to make sure react doesn't change the chats list component when other tabs are selected)
- Removes some unnecessary subscription wrappers, which are not used anymore

### Testing
Please check communities & chats home list items for any regressions.
Note: When the user will be on another tab then the chats-tab, and receive any new message, it will only be updated once he/she navigates back to the chats-tab.

### CODE REVIEW

File: src/status_im2/subs/home.cljs [hunk 1]
```diff
@@ -1,38 +1,20 @@
 (ns status-im2.subs.home
```
Comment (Parveshdhull) [inline src/status_im2/subs/home.cljs:1]: Maybe we should rename home namespace to chats or some other more informative name

**Comment by Parveshdhull** [comment]
Hi @rasom, Please take a look at https://github.com/status-im/status-mobile/pull/15636/commits/18d941dc131633505d7e0e04ff029022dbba6b8f
Not sure but it might also help https://github.com/status-im/status-mobile/issues/15609#issuecomment-1507286800

**Comment by rasom** [comment]
@Parveshdhull in order to test it I need to open communities from discovery screen and currently app crashes when I'm trying to open that discovery screen

**Comment by Parveshdhull** [comment]
Thank you for finding this issue, should be fixed now

**Comment by rasom** [comment]
@Parveshdhull yep I can confirm it fixes https://github.com/status-im/status-mobile/issues/15609

**Comment by Parveshdhull** [comment]
> @Parveshdhull yep I can confirm it fixes #15609

Thank you very much for finding the problem and testing.

File: src/status_im2/subs/shell.cljs [hunk 2]
```diff
@@ -103,11 +103,18 @@
...
+
 (re-frame/reg-sub
  :shell/sorted-switcher-cards
  :<- [:shell/switcher-cards]
- (fn [stacks]
-   (sort-by :clock > (map val stacks))))
+ :<- [:view-id]
+ (fn [[stacks view-id]]
+   (if (= view-id :shell)
+     (let [sorted-shell-cards (sort-by :clock > (map val stacks))]
```
Comment (rasom) [inline src/status_im2/subs/shell.cljs:114]: @Parveshdhull can we do it in event handler on fetching cards instead of using atom? Or on handler which changes those stacks or something. If we need some pre calculated data I suppose it should happen in event handler.

File: src/status_im2/subs/home.cljs [hunk 3]
```diff
@@ -1,38 +1,20 @@
...
   (:require [re-frame.core :as re-frame]))
 
-(def memo-home-items (atom nil))
+(def memo-chats-stack-items (atom nil))
```
Comment (rasom) [inline src/status_im2/subs/home.cljs:4]: by all means computation function in `reg-sub` should be a pure function, that cashing likely shouldn't happen in subs layer

File: src/status_im2/subs/shell.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im2/subs/shell.cljs:114]: Yes, it makes sense. will change it

File: src/status_im2/subs/home.cljs (hunk 3 above)
Comment (Parveshdhull) [reply src/status_im2/subs/home.cljs:4]: should be fixed now

Comment (Parveshdhull) [reply src/status_im2/subs/home.cljs:4]: Moved caching to the view itself instead of subscription. But looks like this slightly increase render time
<details>
<summary>Caching in subscription render time</summary>

old

</details>

<details>
<summary>Caching in view render time</summary>

new


</details>

Comment (cammellos) [reply src/status_im2/subs/home.cljs:4]: probably render is also not the right place to memoize, ideally we use the re-frame subscription mechanism that already uses a cache internally?

Comment (Parveshdhull) [reply src/status_im2/subs/home.cljs:4]: For now keeping the caching in the subscription itself, due to performance. We can look more into this later on how to improve it.

**Review by cammellos — APPROVED** [review]

**Comment by Parveshdhull** [comment]
Test Commit `shouldComponentUpdate`: https://github.com/status-im/status-mobile/pull/15636/commits/f96c96d9ac7a2e388feeedd1970abdb7c4e820b4 (Not able to get caching behavior)
Test Commit `Move caching to view itself`: https://github.com/status-im/status-mobile/commit/5ee3f77bb83a47d9d3afc7d26de5af80c2a0cf77 ([Increased](https://github.com/status-im/status-mobile/pull/15636#discussion_r1166038244) render time)

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@Parveshdhull thank you for PR!
I haven't noticed any performance improvements or any regression in this PR.
Below attached video with the same user `rule dirt shuffle vintage trash cricket gesture door more robust fine tooth` with the same steps.

Nightly: 

https://user-images.githubusercontent.com/4557972/233035264-5eff6b05-bfd6-4648-83e0-42d13c86ebd6.mp4


PR build:

https://user-images.githubusercontent.com/4557972/233035459-8f39138d-a3c4-4ed1-9764-81e7ce865244.mp4

Navigation is still twitchy, screens are jumping on and off, and the animation is far from smooth.
So I wouldn't say that this PR fixes the initial issue, but if it is a required step for further investigation/improvements, we can merge it.

**Comment by Parveshdhull** [comment]
Hi @churik, Thank you very much for testing the PR.

PR makes sure that few screens(shell, home, communities) are only updated when we navigate to them (not in background). And on bonus, I was hoping it will fix #15609.

So, there are two performance-related issues.
1. App performance is slow in general (not only navigation) because screens are getting updates even when they are not in focus.
In the original issue video around (1.30 min) even the scroll is slow, probably caused by this bug, and I hope it gets fixed by the current PR.

2. Navigation is slow - twitchy and stumbled opening of screens.
So what I think happens is, when we navigate to a screen, the screen opening animation starts. And even before this animation gets completed screen gets rendered and breaks the animation in between. As far as I know, this issue is also present in the old ui (android 1.19), maybe not that visible.

We also faced a similar issue with bottom tabs, that's why we only [load](https://github.com/status-im/status-mobile/blob/46351543f10f588ed877ad7233074531303b7faf/src/status_im2/contexts/shell/animation.cljs#L167) the current tab for the first time, once the animation is complete.

I am currently not sure how to fix this issue, but as I will work on https://github.com/status-im/status-mobile/issues/15565, I hope it will also address animations related to navigation.

First I am going to try if navigation provides functionality to implement the required feature and use better animation, if not, probably the next best option will be to implement chats & communities screen as bottom tabs, and control navigation and animation ourselves.

**Comment by Parveshdhull** [comment]
Btw, is this twitchy navigation as you mentioned in the above video, is this affected by the number of communities or it is the same for even one community or chat?

**Comment by churik** [comment]
@Parveshdhull you're right, it seems not great for both cases, regardless of communities, though it seems a bit worse to me with communities (which is actually I have no idea how to check)

So as the initial issue is not reproducible for me with slowing down the scrolling, I'll ask @VladimrLitvinenko to check on his device just in case and after this PR is ready to be merged.

**Comment by churik** [comment]
There are noticeable changes on low-level android device,thanks for checking @VladimrLitvinenko

File: src/status_im2/subs/home.cljs (hunk 3 above)
Comment (ilmotta) [reply src/status_im2/subs/home.cljs:4]: Hey @cammellos, @rasom. @Parveshdhull recently mentioned this problem to me. I know it's been a while already, but here are my thoughts/findings. No action to be taken, just thoughts. This is going to be a long comment 🤷🏼 

The code in `develop` is still basically the same as when this PR was merged, so I used it as a basis to make the analysis.

> we want to keep data unchanged so react doesn't change component when we leave screen

In `develop`, when I switch between screens (1:1 chats, AC, bottom tabs, etc), the subscription `:chats-stack-items` always re-runs because it depends on the signal `:view-id`. The cost of this subscription when there's a cache hit in `memo-chats-stack-items` is fairly small, but it's not zero.

In `develop`, if we ignore the manual caching mechanism performed with `memo-chats-stack-items`, then the subscription `:chats-stack-items` is essentially a `take` call.

```clojure
(re-frame/reg-sub
 :chats-stack-items
 :<- [:chats/home-list-chats]
 :<- [:view-id]
 :<- [:home-items-show-number]
 (fn [[chats view-id home-items-show-number]]
   (take home-items-show-number chats)))
```

And upon further inspection, we see that the view layer does more computation on the results of this subscription.

```clojure
;; in component home.view/chats
(let [unfiltered-items (rf/sub [:chats-stack-items])
      items            (filter-and-sort-items-by-tab selected-tab unfiltered-items)]
  ...)
```

Therefore, the whole extra computation in `filter-and-sort-items-by-tab` is not being cached by re-frame.

After I moved all the computation to the subscription (including the current tab argument, this is important), then when I switch between bottom tabs or other screens, re-frame doesn't re-run the subscription the component `home.view/chats` never re-renders.

After switching screens, we get a hit in re-frame's subscription cache, which shows that when leaving or entering the *Messages home screen* nothing is re-computed or re-rendered. Obviously, if the user changes between `Recent` or `Groups` tabs, then the subscription will be re-computed and the view re-rendered.

```clojure
(re-frame.core/dispatch [:navigate-to :my-profile])
(re-frame.subs/cache-lookup [:chats-stack-items :tab/recent])
;; => still returns cached chats which means nothing is re-rendered or sub re-computed.
```

The new subscription looks like this:

```clojure
(re-frame/reg-sub
 :chats-stack-items
 :<- [:chats/home-list-chats]
 :<- [:home-items-show-number]
 (fn [[chats home-items-show-number] [_ tab]]
   (let [k (if (= tab :tab/groups) :group-chat :chat-id)]
     (->> chats
          (take home-items-show-number)
          (filter k)
          (sort-by :timestamp >)))))
```

Here's the example video showing the new sub at play:

[device-2023-08-10-123339.webm](https://github.com/status-im/status-mobile/assets/46027/6255e41c-3ccb-42d2-98d0-156d76e38d9a)

I measured with re-frisk and the new code delivers the same level of performance. The differences I've seen in my comparisons are more like random fluctuations, which makes me think this manual caching mechanism is not needed.

The upsides of the new code are:

- The subscription doesn't re-run on screen changes throughout the app.
- It is more idiomatic re-frame (no mutation in subscription).
- It's simpler and the whole computation can be unit tested (because it's not split between sub & view).

Side note: I micro-benchmarked the new subscription and the most expensive part is sorting, and because the collection is rather small for the value of `home-items-show-number` (e.g. 20), using a transducer didn't help because there is a negligible cost to garbage collect intermediary results. If the data coming through was already ordered by timestamp we could consider skipping sorting?

But this sorting detail is in the range of micro optimizations. I would say optimizing the individual render item component `chat-list-item/chat-list-item` can bear more fruit. For example, it unfortunately creates subscriptions for every item of the flat list; it passes the whole chat instance to the `notification` component which makes Reagent's life more difficult to diff, and so on.

Also, as far as I know, re-frame doesn't offer any mechanism to control when & how its `query-cache` is evicted (see https://github.com/day8/re-frame/blob/master/src/re_frame/subs.cljc#L46). One technique that's worth trying is playing with `reg-sub-raw` and the `on-dispose` callback. Sounds like a hack, but it's interesting nonetheless.

Complete sidetracking, but I can't help but wish https://github.com/clojure/core.memoize was available for ClojureScript, because then we would be able to use less naive memoization techniques that are less likely to grow too much, e.g. LRU or TTL semantics (see https://github.com/clojure/core.memoize/blob/master/src/main/clojure/clojure/core/memoize.clj#L398). I'm sure this would give us new guns to shoot ourselves in the foot, but I used core.memoize in the past in certain problems and it really opens some good doors.

That's all! 😅 Cheers!
