### PR TITLE
[Communities] Account selection: сan't see the entire text of the community rules

### LINKED ISSUE #18747: Account selection: сan't see the entire text of the community rules in drawer if the text is long/maximum length
# Bug Report

This is a UI bug, but logging it anyway, since designers may miss this case during the design review

To reproduce this, enter a maximum length text on the desktop in the field `Dialog for new members`

Screenshot 2024-02-07 at 14 16 26

https://github.com/status-im/status-mobile/assets/67952253/bec72cfb-0cbd-4edd-818f-df330bcada9b

### Additional Information

- Status version: https://github.com/status-im/status-mobile/pull/18530
- Desktop version: https://ci.status.im/job/status-desktop/job/nightly/179/
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by FFFra**
fixes #18747

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=15331%3A285128&mode=dev)
[Figma design for scroll:](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=16409%3A80328&mode=design&t=74XCfD0sFyTstHQo-1)

### Summary
This minor pull request addresses an issue where users were unable to scroll to the end of the Community Rules if they were too long.

#### Platforms

- Android
- iOS

##### Functional

- public chats
- group chats

### Steps to test

1. Activate the Accounts Selection feature flag.
2. Input text of maximum length into the 'Dialog for new members' field on the desktop.
3. Invite a user and attempt to join this community on a mobile device.
4. Verify that the entire text is visible without truncation.

### Before and after screenshots comparison

Before:

https://private-user-images.githubusercontent.com/67952253/302988907-bec72cfb-0cbd-4edd-818f-df330bcada9b.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTM5MDcsIm5iZiI6MTcwNzM5MzYwNywicGF0aCI6Ii82Nzk1MjI1My8zMDI5ODg5MDctYmVjNzJjZmItMGNiZC00ZWRkLTgxOGYtZGYzMzBiY2FkYTliLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyMDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZWFhYjU1ZDdlNjJhNWU0NTg3NTYwM2MwYjNlYWY5MjlkM2QzNDA5ZDAxYTc2YTI3NzZmYzZjM2E3ZWJiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4M5Nnd6YKK_x2f4DfL1lGIvRqJJZwtMUFG57DyPpAA

After:

https://github.com/status-im/status-mobile/assets/5999878/51031a50-c58b-4335-bfa9-16983d4efa55

status: ready

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]
LGTM!

**Review by J-Son89 — APPROVED** [review]

**Comment by qoqobolo** [comment]
@FFFra thanks for the fix!
It works as expected on iOS but on Android rules are still not scrollable to the bottom, could you check please?

### ISSUE 1: The original issue is reproducible on Android

Tried on Pixel 7a and Huawei P40 lite

https://github.com/status-im/status-mobile/assets/67952253/18d8851e-220b-4f9b-9ff4-91a7334cad63

**Comment by FFFra** [comment]
@qoqobolo can you please try again?

File: src/status_im/contexts/communities/actions/community_rules/view.cljs [hunk 1]
```diff
@@ -1,14 +1,19 @@
...
+    [react-native.platform :as platform]
     [status-im.contexts.communities.actions.community-rules.style :as style]
     [utils.re-frame :as rf]))
 
 (defn view
   [id]
-  (let [rules (rf/sub [:communities/rules id])]
-    [rn/view {:style style/community-rule}
+  (let [rules                 (rf/sub [:communities/rules id])
+        android-bottom-margin (if platform/android? 44 0)
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/actions/community_rules/view.cljs]: Why additional margin is required for Android?

File: src/status_im/contexts/communities/actions/community_rules/view.cljs [hunk 2]
```diff
@@ -1,14 +1,19 @@
...
+        rules-bottom-space    (+ (slide-button-utils/get-dimensions nil :size-48 :track-height)
+                                 android-bottom-margin)]
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/actions/community_rules/view.cljs]: I would recommend storing the result of the `slide-button-utils/get-dimensions` call in a variable for better readability. Additionally, renaming `rules-bottom-space` to `rules-bottom-margin` would make the code clearer, as it accurately represents its purpose as the bottom margin.

```suggestion
slide-button-height   (slide-button-utils/get-dimensions nil :size-48 :track-height)
rules-bottom-margin   (+ slide-button-height android-bottom-margin)]
```

File: src/status_im/contexts/communities/actions/community_rules/view.cljs (hunk 1 above)
Comment (FFFra) [reply src/status_im/contexts/communities/actions/community_rules/view.cljs]: Because the dimensions of the slider change according to the screen dimensions. Which causes different behave since android does not have safe area

File: src/status_im/contexts/communities/actions/community_rules/view.cljs (hunk 2 above)
Comment (FFFra) [reply src/status_im/contexts/communities/actions/community_rules/view.cljs]: oh, thats cool. I will do it. Tks!

File: src/status_im/contexts/communities/actions/community_rules/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/communities/actions/community_rules/view.cljs]: This should be using safe area then.

Comment (qoqobolo) [reply src/status_im/contexts/communities/actions/community_rules/view.cljs]: > Why additional margin is required for Android?

The bottom margin on Android is a bit too big indeed. I didn't report this now to avoid wasting time on this minor visual inconsistency in an edge case, since this issue itself is a release blocker and the margin could be fixed later. 

What do you think guys about fixing this as a follow-up? @ajayesivan @J-Son89 @FFFra 

But if this is a quick one, then it would be nice to fix it today for sure

**Comment by qoqobolo** [comment]
@FFFra also, my iPhone SE came back to life and I see the same issue there.
Could you adapt the scrolling area for iOS devices with small screens as well, please?

But again: we can also keep this as a follow-up unless it's fixed today.

### ISSUE 2: Bottom lines are not visible on a small screen device


https://github.com/status-im/status-mobile/assets/67952253/e2c76843-cfe3-49a4-9f6e-03d5dde1c622

File: src/status_im/contexts/communities/actions/community_rules/view.cljs (hunk 1 above)
Comment (FFFra) [reply src/status_im/contexts/communities/actions/community_rules/view.cljs]: @J-Son89 Yah, I tried safe area, but it has no effect in Android. Ideally we need a solution for all cases. Please let me know if any ideas

Comment (J-Son89) [reply src/status_im/contexts/communities/actions/community_rules/view.cljs]: Hmm is there a safe area elsewhere pushing this down?

Seems like you might need to remove something rather than adding it 🤔

**Comment by FFFra** [comment]
Think I've found a fix. Hold on a bit

@qoqobolo @ajayesivan @qoqobolo

**Comment by FFFra** [comment]
Hello, team. I've made another try by getting rid of `position: absolute` and using `display: flex` instead.
@qoqobolo @ajayesivan  @J-Son89  can you please take a look if that fix?

File: src/status_im/contexts/communities/actions/community_rules/view.cljs (hunk 1 above)
Comment (FFFra) [reply src/status_im/contexts/communities/actions/community_rules/view.cljs]: Actually you are right. I made another change and the other problem was a `position: absolute` ruining our lifes hahaha

File: src/status_im/contexts/communities/actions/accounts_selection/style.cljs [hunk 3]
```diff
@@ -16,13 +16,9 @@
...
-   :bottom             0
-   :left               0
-   :right              0
-   :padding-horizontal screen-horizontal-padding
-   :padding-vertical   12
-   :flex               1})
+(def bottom-actions
+  {:flex-direction    :column
+   :align-items       :flex-end
+   :margin-horizontal 15
```
Comment (ajayesivan) [inline src/status_im/contexts/communities/actions/accounts_selection/style.cljs]: We need to add `:padding-top 12`

Missing white background above the button:

Comment (ajayesivan) [inline src/status_im/contexts/communities/actions/accounts_selection/style.cljs]: Also, I think we should use `:padding-horizontal screen-horizontal-padding` instead of `margin-horizontal`. In Figma the space on left and right side of the button is 20.

**Comment by qoqobolo** [comment]
### ISSUE 3: There is no bottom margin on iPhone SE under the `Slide to request to join` button anymore


Screenshot 2024-02-16 at 16 32 42

**Review by ajayesivan — APPROVED** [review]

**Review by qoqobolo — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fixes @FFFra!
The issue 3 https://github.com/status-im/status-mobile/pull/18761#issuecomment-1948635977 is still there but let's fix it as a follow-up. Would you mind logging it pls?

PR can be merged.

**Comment by FFFra** [comment]
> Thanks for the fixes @FFFra! The issue 3 [#18761 (comment)](https://github.com/status-im/status-mobile/pull/18761#issuecomment-1948635977) is still there but let's fix it as a follow-up. Would you mind logging it pls?
> 
> PR can be merged.

I've talked to @siddarthkay and now I can run on other devices. I think I know why thats happening. Gonna make some tests and let you know. Thank you a lot!
