### PR TITLE
fix: polish new chat

### LINKED ISSUE #18981: Polish "New chat" view
### Description

The new chat view has some bits and pieces missings:
- New chat is displayed instead of new group chat when selecting multiple users
- The header with the letter is not sticky
- There's no blur under the button

Feel free to create separate issues, address separately

### Designs

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=3720-549016&mode=design&t=nplOuMxagSfPr29p-4

### LINKED ISSUE #19202: Use customization color for new chat
Use the user's set customization color for the add button and check box in the add new chat sheet

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
Fixes https://github.com/status-im/status-mobile/issues/18981
Fixes https://github.com/status-im/status-mobile/issues/19202

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Polishes the new chat UI/Sheet
- Adds appropriate text based on if it is a group chat or 1:1 chat
- Implements sticky header for `gesture/section-list` which is implemented using `gesture/flat-list (Flatlist)` from `react-native-gesture-handler`
- Adds opacity layer around button

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- group chats

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- Go to chat tab
- Click the + button in the top right to start a new chat

status: ready 

Polish New Chat

### CODE REVIEW

File: src/status_im/common/contact_list/view.cljs [hunk 1]
```diff
@@ -1,10 +1,12 @@
 (ns status-im.common.contact-list.view
   (:require
     [quo.core :as quo]
+    [quo.theme :as quo.theme]
```
Comment (seanstrom) [inline src/status_im/common/contact_list/view.cljs]: tiny comment: we may be able to have just `[quo.theme]` instead of `[quo.theme :as quo.theme]`

File: src/react_native/gesture.cljs [hunk 2]
```diff
@@ -95,13 +95,25 @@
...
+  (->> data
+       (map-indexed (fn [index item] (if (:header? item) index nil)))
+       (filter (complement nil?))
+       (vec)))
+
 (defn section-list
-  [{:keys [sections render-section-header-fn render-fn] :as props}]
+  [{:keys [sections sticky-section-headers-enabled render-section-header-fn render-fn]
+    :or   {sticky-section-headers-enabled true}
+    :as   props}]
```
Comment (seanstrom) [inline src/react_native/gesture.cljs]: I'm wondering 🤔 
Is it safe to default `sticky-section-headers-enabled` to true? It seems this has not been supported until now, so maybe it needs to be an opt-in value instead of an opt-out. Thoughts?

**Review by seanstrom — COMMENTED** [review]
Nice stuff! Just left a couple of comments, lmk what you think and I'll re-review soon.
Also is it possible to see a screenshot or gif of the results plz? 🙏

File: src/status_im/common/contact_list/view.cljs [hunk 3]
```diff
@@ -1,10 +1,12 @@
...
     [react-native.core :as rn]
     [status-im.common.contact-list.style :as style]))
 
 (defn contacts-section-header
   [{:keys [title index]}]
-  [rn/view (style/contacts-section-header (= index 0))
-   [quo/divider-label title]])
+  (let [theme (quo.theme/use-theme-value)]
+    [rn/view (style/contacts-section-header (= index 0) theme)
```
Comment (flexsurfer) [inline src/status_im/common/contact_list/view.cljs]: you could just use footer with 8px height

File: src/react_native/gesture.cljs (hunk 2 above)
Comment (BalogunofAfrica) [reply src/react_native/gesture.cljs]: For section lists, sticky headers are enabled by default. This implementation uses `FlatList` under the hood (from gesture handler) because the normal section list from react native wouldn't work (the gestures do not work) in the context of a bottom sheet (this case).

Comment (seanstrom) [reply src/react_native/gesture.cljs]: Ah I see, that makes sense, thanks for the explanation 🙏

**Review by seanstrom — APPROVED** [review]
Nice stuff! ✅

File: src/status_im/contexts/chat/home/new_chat/view.cljs [hunk 4]
```diff
@@ -99,25 +102,23 @@
...
-                                  (rf/dispatch [:chat.ui/start-chat public-key])
-                                  (rf/dispatch [:navigate-to :new-group])))}
-        (if one-contact-selected?
-          (i18n/label :t/chat-with {:selected-user primary-name})
-          (i18n/label :t/setup-group-chat))])]))
-
-(def view (quo.theme/with-theme view-internal))
+        {:key-fn                   :title
+         :sections                 (rf/sub [:contacts/filtered-active-sections])
+         :render-section-header-fn contact-list/contacts-section-header
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/home/new_chat/view.cljs:135]: :render-section-footer-fn

Comment (BalogunofAfrica) [reply src/status_im/contexts/chat/home/new_chat/view.cljs:135]: I don't understand

File: src/react_native/gesture.cljs [hunk 5]
```diff
@@ -95,13 +95,25 @@
             (into [{:title title :header? true}] data))
    sections))
 
+(defn find-sticky-indices
```
Comment (J-Son89) [inline src/react_native/gesture.cljs]: should we make it private?

File: src/status_im/common/contact_list/view.cljs [hunk 6]
```diff
@@ -1,10 +1,12 @@
 (ns status-im.common.contact-list.view
   (:require
     [quo.core :as quo]
+    [quo.theme :as theme]
```
Comment (J-Son89) [inline src/status_im/common/contact_list/view.cljs]: please use `[quo.theme]` as `theme` will class with the prop name

File: src/status_im/contexts/chat/home/new_chat/view.cljs (hunk 4 above)
Comment (flexsurfer) [reply src/status_im/contexts/chat/home/new_chat/view.cljs:135]: (defn footer []
[rn/view {:height 8})])

:render-section-footer-fn footer

instead of condition in header

File: src/status_im/contexts/chat/home/new_chat/view.cljs [hunk 7]
```diff
@@ -2,7 +2,7 @@
   (:require
     [quo.core :as quo]
     [quo.foundations.colors :as colors]
-    [quo.theme :as quo.theme]
+    [quo.theme :as theme]
```
Comment (J-Son89) [inline src/status_im/contexts/chat/home/new_chat/view.cljs]: same here

File: src/react_native/gesture.cljs (hunk 5 above)
Comment (BalogunofAfrica) [reply src/react_native/gesture.cljs]: Yeah, makes sense to have it private

File: src/status_im/common/contact_list/view.cljs [hunk 8]
```diff
@@ -1,10 +1,16 @@
 (ns status-im.common.contact-list.view
   (:require
     [quo.core :as quo]
+    [quo.theme]
     [react-native.core :as rn]
     [status-im.common.contact-list.style :as style]))
 
+(defn contacts-section-footer
```
Comment (flexsurfer) [inline src/status_im/common/contact_list/view.cljs:8]: nice

File: src/status_im/common/contact_list/view.cljs [hunk 9]
```diff
@@ -1,10 +1,16 @@
...
+  []
+  [rn/view style/contacts-section-footer])
+
 (defn contacts-section-header
-  [{:keys [title index]}]
-  [rn/view (style/contacts-section-header (= index 0))
-   [quo/divider-label title]])
+  [{:keys [title]}]
+  (let [theme (quo.theme/use-theme-value)]
```
Comment (flexsurfer) [inline src/status_im/common/contact_list/view.cljs:14]: im not sure this is efficient, could you elaborate on why the header has a different color?

Comment (BalogunofAfrica) [reply src/status_im/common/contact_list/view.cljs:14]: The header has to have a background colour set when we want to use it as a sticky header.

If we do not set a background colour, we get this overlap of the header and the items when the header sticks to the top

Simulator Screen Recording - iPhone 13 - 2024-03-01 at 06 15 17

Comment (flexsurfer) [reply src/status_im/common/contact_list/view.cljs:14]: as we have our own implementation of section-list do you think if would be possible to set the theme as a prop to section-list and pass it to the header?

**Review by flexsurfer — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @BalogunofAfrica !
Please, rebase your PR.
Thanks!

**Comment by mariia-skrypnyk** [comment]
Hi @BalogunofAfrica !
Thanks for your PR.

Polish looks great!
The only one issue I found I'll describe below:

**ISSUE 1: Contact's avatars are reloaded after user choses 1-2 contacts from the list**

**Platform:** Android only

**Steps:**
1. Login with user who has contacts
2. Go to Messages -> +
3. Create new chat
4. Choose 1-2 contacts from the list

**Actual result:** Contact's avatars are reloaded after user choses 1-2 contacts from the list

https://github.com/status-im/status-mobile/assets/147824399/007d6aee-3530-43fe-973b-ab4ffb10cc4d


**Expected result:** contact list is not updated

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica please, let me know in case you'll have updates.

**Comment by BalogunofAfrica** [comment]
> @BalogunofAfrica please, let me know in case you'll have updates.

Hi @mariia-skrypnyk!

This seems like an unnecessary re-render issue in the contact list. I have created a dedicated issue for this here https://github.com/status-im/status-mobile/issues/19130

I also noticed it on iOS, but it happened sparingly compared to Android

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica thanks for such a nice polish!
All good from my side!

I move your PR to the design review for @Francesca-G review.

**Review by Francesca-G — COMMENTED** [review]
Here's the [review](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7/Review-Messages-%2F-Mobile?type=design&node-id=47%3A60636&mode=design&t=4f8JVHmtQ4qaHLXf-1) :)

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica Hi!

Let me know when I can test your fixes. Thanks!

**Comment by BalogunofAfrica** [comment]
> Here's the [review](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7/Review-Messages-%2F-Mobile?type=design&node-id=47%3A60636&mode=design&t=4f8JVHmtQ4qaHLXf-1) :)

Hi @Francesca-G, I have addressed the custom color and bottom spacing.

The blur on the sticky header when it docks to the top has been logged as a separate [issue](https://github.com/status-im/status-mobile/issues/19201) and might be more technical to implement, so it would not be addressed in this PR. The divider comment is also related to the blur issue as I noticed in the figma that the divider's layer is blurred out when the header sticks, so it would also be addressed as part of the issue mentioned above.

**Comment by mariia-skrypnyk** [comment]
@BalogunofAfrica I've checked your fixes and they are fine from my side.
✅custom color 
✅bottom spacing

I move PR to design review by @Francesca-G .

File: src/quo/components/list_items/user.cljs [hunk 10]
```diff
@@ -19,23 +20,25 @@
...
-       :checked?            checked?
-       :accessibility-label :user-list-toggle-check
-       :disabled?           disabled?
-       :on-change           (when on-check on-check)}]
-     :close
-     [text/text "not implemented"]
-     [rn/view])])
+  (let [customization-color (rf/sub [:profile/customization-color])]
+    [rn/touchable-opacity
+     {:on-press (when on-press on-press)}
```
Comment (alwx) [inline src/quo/components/list_items/user.cljs:25]: just `:on-press on-press` will work fine as well

File: src/react_native/gesture.cljs [hunk 11]
```diff
@@ -95,13 +95,34 @@
             (into [{:title title :header? true}] data))
    sections))
 
+(defn- find-sticky-indices
+  [data]
+  (->> data
+       (map-indexed (fn [index item] (if (:header? item) index nil)))
+       (filter (complement nil?))
```
Comment (alwx) [inline src/react_native/gesture.cljs:102]: `(remove nil?)` instead of `(filter (complement nil?))` has better readability

File: src/react_native/gesture.cljs [hunk 12]
```diff
@@ -95,13 +95,34 @@
             (into [{:title title :header? true}] data))
    sections))
 
+(defn- find-sticky-indices
+  [data]
+  (->> data
+       (map-indexed (fn [index item] (if (:header? item) index nil)))
```
Comment (alwx) [inline src/react_native/gesture.cljs]: `(if (:header? item) index nil)` => `(when (:header? item) index)`

File: src/react_native/gesture.cljs (hunk 11 above)
Comment (alwx) [inline src/react_native/gesture.cljs]: `(remove nil?)` instead of `(filter (complement nil?))` has better readability

File: src/quo/components/list_items/user.cljs (hunk 10 above)
Comment (alwx) [inline src/quo/components/list_items/user.cljs]: just `{:on-press on-press}` will work fine as well

**Review by alwx — CHANGES_REQUESTED** [review]

**Review by Francesca-G — APPROVED** [review]
Looks good now ✨
@BalogunofAfrica thanks for addressing the other issues separately!

**Review by alwx — APPROVED** [review]
