### PR TITLE
Fix WalletConnect sessions disappearing

### LINKED ISSUE #21275: Dapps disappear from connected list after relogin (IOS)
Reproducing on IOS only. IPhone 15, IOS 17.6.1

**Steps:**

1. Connect to any dapp
2. Open connected Dapps list and make sure new Dapp is listed there
3. Close the app and relogin
4. Open connected Dapps list
5. See if Dapp is still displayed in the list

**Actual result:** Dapp disappeared from the list

[logs (47).zip](https://github.com/user-attachments/files/17027459/logs.47.zip)

https://github.com/user-attachments/assets/f3421aa8-2c19-4645-8fdd-4949ef992f01

### Additional Information

- Status version: nightly 
- Operating System:  iOS

### PR DESCRIPTION
**Pull request by clauxx**
fixes #21275

### Summary
The sessions were disappearing due to a bug in the session fetching logic, which was unnecessarily convoluted with multiple events. Here, the bug was fixed and the session logic was simplified into functions, which minimized the number of events we use.

Changes:
1. isolated and moved _session fetching_ and _persistance sync_ logic into one function
2. isolated and moved session disconnection logic
3. isolated and moved session approval logic
4. the bug should be fixed as a result of these changes
5. added event tests for session
 
### Testing notes
Since there are changes in session management, we should test the following flows:
1. fetching connected dapps
2. approval flow
3. disconnect dapp flow

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs [hunk 1]
```diff
@@ -119,33 +118,51 @@
...
-                                           {:error error
-                                            :event :wallet-connect/approve-session})
-                                (rf/dispatch
-                                 [:wallet-connect/reset-current-session-proposal]))}])
+                {:web3-wallet      web3-wallet
+                 :proposal-request current-proposal
+                 :session-networks session-networks
+                 :address          current-address
+                 :on-success       #(rf/dispatch [:wallet-connect/approve-session-success %])
+                 :on-fail          #(rf/dispatch [:wallet-connect/approve-session-error %])}])
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/wallet_connect/events/session_proposals.cljs:139]: Can we use `rf/call-continuation` inside the definition for `:effects.wallet-connect/approve-session`?

If we do that then we can define `:on-success` and `:on-failure` with vectors:
```clojure
[:effects.wallet-connect/approve-session
   {:web3-wallet      web3-wallet
    :proposal-request current-proposal
    :session-networks session-networks
    :address          current-address
    :on-success       [:wallet-connect/approve-session-success]
    :on-fail          [:wallet-connect/approve-session-error]}]
```

For reference, here's an example of how the effect would use `rf/call-continuation` to work promesa: https://github.com/status-im/status-mobile/blob/seanstrom/chore-refactor-screens-definitions/src/status_im/contexts/wallet/effects.cljs#L63-L68

File: src/status_im/contexts/wallet/wallet_connect/events/sessions.cljs [hunk 2]
```diff
@@ -26,116 +26,59 @@
...
+   (let [addresses (->> (get-in db [:wallet :accounts])
+                        vals
+                        sessions/filter-operable-accounts
+                        (map :address))]
+     {:fx [[:effects.wallet-connect/get-sessions
+            {:online?     (-> db :network/status (= :online))
+             :web3-wallet (get db :wallet-connect/web3-wallet)
+             :addresses   addresses
+             :on-success  #(rf/dispatch [:wallet-connect/get-sessions-success %])
+             :on-error    #(rf/dispatch [:wallet-connect/get-sessions-error %])}]]})))
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/wallet_connect/events/sessions.cljs]: Similar suggestion about using `rf/call-continuation` for this effect too 🙏

**Review by seanstrom — COMMENTED** [review]
Looking good, left a couple of comments 📓 

My main overall question is to understand a little bit more about how wallet connect events/effects are working now. For example, how do the changes resolve the issue, I think it's because of the way we structuring the effects to avoid some kind of inconsistent state, but I'm not sure.

Really like that we're defining re-usable effects too ♻️

**Review by alwx — APPROVED** [review]

**Comment by pavloburykh** [comment]
@clauxx thank you for the PR. Unfortunately I am still facing issue on IOS. 

### ISSUE 1 'Failed to get dapps connection' error and empty dapp list on relogin (IOS)

Reproducing on iPhone 15, IOS 17.6.1
**Steps:** 

1. Connect to dapp
2. Perform relogin
3. Observe the error
4. Open dapps list
5. Check if connected dapp is displayed

**Actual result:** 'Failed to get dapps connection' error. Dapps list is empty. 

[logs (48).zip](https://github.com/user-attachments/files/17209289/logs.48.zip)
photo_2024-10-01 15 14 18

File: src/status_im/contexts/wallet/wallet_connect/events/sessions.cljs [hunk 3]
```diff
@@ -26,116 +26,59 @@
...
                 (fn [sessions]
                   (->> sessions
                        (remove #(= (:topic %) topic))
-                       (into []))))
-    :fx [[:json-rpc/call
-          [{:method     "wallet_disconnectWalletConnectSession"
-            :params     [topic]
-            :on-success #(log/info "Wallet Connect session disconnected")
-            :on-error   #(log/info "Wallet Connect session persistence failed" %)}]]]}))
+                       (into []))))}))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/wallet_connect/events/sessions.cljs:89]: @seanstrom so here is the cause of the bug. This event was called when disconnecting a dapp and when syncing persisted dapps. We shouldn't be removing active sessions from the db when syncing the persisted dapps. The faulty "sync" was likely caused by the expiry date check, but hard to tell the cause since it's difficult to reproduce.

**Comment by clauxx** [comment]
@pavloburykh could you try again please? I think I found the root cause for this issue, being that the wallet was finalizing its initialization and loading the accounts after we attempt to fetch the sessions, leading to the empty list, but it's hard to tell since it's very hard to reproduce for me.

EDIT: if possible, even if the bug is fixed, could you please attach the logs?

**Comment by pavloburykh** [comment]
> @pavloburykh could you try again please? I think I found the root cause for this issue, being that the wallet was finalizing its initialization and loading the accounts after we attempt to fetch the sessions, leading to the empty list, but it's hard to tell since it's very hard to reproduce for me.
> 
> EDIT: if possible, even if the bug is fixed, could you please attach the logs?

Thanks @clauxx, ISSUE 1 is fixed now. I will proceed with the rest of testing. 

Here are the logs from my IOS 
[logs (49).zip](https://github.com/user-attachments/files/17229664/logs.49.zip)

**Comment by pavloburykh** [comment]
@clauxx thank you again for the fixes. No issues from my side. PR is ready for merge.
