### PR TITLE
Fix `div` error after amount is set as fiat

### LINKED ISSUE #21711: Unable to enter data into Input field after switching to fiat
### Steps:
1. Navigate to the Send or Bridge Flow setup page.
2. Tap the "Switch to Fiat" button.
3. Attempt to enter any value in the input field.

### Actual Result:
When the "Switch to Fiat" button is tapped, the input field displays 0.00 and does not allow the user to enter any data until the existing value is manually removed.

https://github.com/user-attachments/assets/c8c86988-b865-4d20-b972-bb51d94f05bc

### Expected Result:
After tapping the "Switch to Fiat" button, the user should be able to input values directly into the field without needing to remove any pre-filled data.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 28, 2024

### LINKED ISSUE #21720: "div() is not a number" Error when entering fiat amount with decimals on send page
### Steps to Reproduce:
1. Navigate to the send page.
2. Switch the input mode to fiat.
3. Enter an amount with decimal values in the fiat input field.
4. Perform transaction

### Actual Result:
An error message "div() is not a number" is displayed, and the transaction fails to proceed.

https://github.com/user-attachments/assets/a8692f1c-a58f-4ad8-969f-c49471cea91e

### Expected Result:
Transaction is performed with the entered fiat amount 

### Logs:
[Status-debug-logs (7).zip](https://github.com/user-attachments/files/17960023/Status-debug-logs.7.zip)

### ENV:
Nightly 29, 2024

### PR DESCRIPTION
**Pull request by clauxx**
fixes #21720
fixes #21711

### Summary

Fixes included
1. "div" error after sending transaction with amount set as fiat (due to state not being cleaned up properly)
2. (send) fixed the default value when switching input to fiat  (e.g. 0 ETH -> 0.00 USD), which pre-filled the input so the user had to remove the values manually
3. (swap) fixed the default value when flipping the sent-received amounts, which pre-filled the value to 0.00 as well

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -622,12 +622,9 @@
 (rf/reg-event-fx :wallet/end-transaction-flow
  (fn [{:keys [db]}]
    (let [address (get-in db [:wallet :current-viewing-account-address])]
-     {:fx [[:dispatch [:wallet/navigate-to-account-within-stack address]]
-           [:dispatch [:wallet/fetch-activities-for-current-account]]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/events.cljs]: `:wallet/fetch-activities-for-current-account` was removed here, since it's already called from `:wallet/navigate-to-account-within-stack`

File: src/status_im/contexts/wallet/send/events.cljs [hunk 2]
```diff
@@ -612,7 +612,7 @@
 
 (rf/reg-event-fx :wallet/clean-up-transaction-flow
  (fn [_]
-   {:fx [[:dispatch [:dismiss-modal :screen/wallet.transaction-confirmation]]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/events.cljs:615]: `[:dismiss-modal :screen/wallet.transaction-confirmation]` was moved to `:wallet/end-transaction-flow`, since it doesn't belong in the state cleanup event.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -694,7 +691,6 @@
                        :params     [{:uuid       (get-in transaction-for-signing [:sendDetails :uuid])
                                      :signatures signatures-map}]
                        :on-success (fn []
-                                     (rf/dispatch [:wallet/clean-send-data])
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/events.cljs:696]: `:wallet/clean-send-data` was moved to `:wallet/clean-up-transaction-flow`, so we don't clean up the state before the components were unmounted.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 4]
```diff
@@ -258,6 +258,8 @@
                                              (set-input-state
                                               #(controlled-input/->crypto % conversion-rate)))
                                            (set-crypto-currency (not crypto-currency?)))]
+    (rn/use-unmount
+     #(rf/dispatch [:wallet/clean-up-transaction-flow]))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:262]: cleaning up the send state when the component unmounts, so we avoid errors in calculations due to missing values.

**Review by vkjr — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]
👍

**Review by shivekkhurana — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by churik** [comment]
@clauxx can we please merge it? Thanks!
