### PR TITLE
Collectible header

### LINKED ISSUE #18595: Collectible scroll view header is buggy
# Bug Report

## Problem 

When a user visits the collectible scroll view, the blur header has an erratic behavior

#### Expected behavior

Designs:
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1355-318949&mode=design&t=o9pEMRpAgIbY54R4-4

image

image

image

#### Actual behavior

[Screencast from 2024-01-22 23-29-02.webm](https://github.com/status-im/status-mobile/assets/90291778/a1ac8a3f-0089-4f64-ab4b-914049c060ca)

### Reproduction

1. Go to wallet tab
2. Add an account owning collectibles
3. Click on a collectibe to see its details.

### Additional Information

It seems we are inheriting this issues from a reused component for communities, we need to check the differences and create one that behaves well for the wallet.

One difference I've noticed at the moment is that we don't need to make it appear with an animation (from top to bottom), so the left and right buttons don't need to change.

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #18595 

### Summary
Improve collectible header animation.

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
- Collectible detail screen

### Steps to test
- Open Status
- Navigate to the Wallet tab
- Open collectibles tab
- Open any collectible

#### Known issues
- In iOS Dark mode the header has a blue tint
- When the collectible name is very long the text overflows
- Header animation won't work as expected when the collectible is unsupported

(We will handle the above issues separately)

#### Android
Light Mode:

https://github.com/status-im/status-mobile/assets/19279756/ec9626d7-118a-4094-8024-20433c9a618e

Dark Mode:

https://github.com/status-im/status-mobile/assets/19279756/93df91b0-d96f-45ab-ba03-85e34e9f8158

#### iOS
Light Mode:

https://github.com/status-im/status-mobile/assets/19279756/32a69324-dc7f-45bc-b5e4-cc9201889a2e

Dark Mode:

https://github.com/status-im/status-mobile/assets/19279756/3b457b33-ea24-4404-b93e-c9ac382db55b

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 1]
```diff
@@ -55,14 +64,72 @@
...
     :accessibility-label :about-tab}])
 
-(defn view
+(defn animated-header
+  [{:keys [scroll-amount title-opacity
+           type picture title description theme]}]
+  (let [blur-amount   (worklets/blur-amount scroll-amount)
+        layer-opacity (worklets/layer-opacity
+                       scroll-amount
+                       (colors/theme-colors "#ffffff00" "#00000000" theme)
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs]: The colors have 100% opacity?
Why?
Why not just use transparent?

Comment (ajayesivan) [reply src/status_im/contexts/wallet/collectible/view.cljs]: Updated the code to use `transparent`. Thanks for pointing that out 😊

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 2]
```diff
@@ -84,45 +151,44 @@
...
+                                                                            [options-drawer/view
+                                                                             {:name collectible-name
+                                                                              :image
+                                                                              preview-uri}])}])}])))
+            :on-collectible-load (fn []
+                                   ;; We need to delay the measurement because the navigation has an
+                                   ;; animation
+                                   (js/setTimeout #(when @title-ref
+                                                     (.measureInWindow @title-ref set-title-bottom))
+                                                  300))}]]
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs]: Can this delay be done using the `withDelay` function of reanimated in the .js file?

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 3]
```diff
@@ -84,45 +151,44 @@
...
+         [rn/view
+          {:style {:flex             1
+                   :background-color (colors/theme-colors colors/white colors/neutral-95 theme)}}
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs]: Can these styles live in the `style.cljs` file?

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 4]
```diff
@@ -132,3 +198,47 @@
             :on-change      on-tab-change
             :data           tabs-data}]
           [tabs/view {:selected-tab @selected-tab}]]]))))
+
+(defn view
+  [_]
+  (let [title-ref          (atom nil)
+        set-title-ref      #(reset! title-ref %)
+        title-bottom-coord (atom 0)
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs]: If we need atoms, Can we please use the `rn/use-ref-atom` helper as declared in the guidelines?
## Regular atoms

In certain instances, components utilized regular atoms; however, they should now be used with `rn/use-ref-atom`

BEFORE:
```clojure
(defn view
  []
  (let [focused? (atom false)]
    (fn []
      (let [on-clear #(reset! status (if @focused? :active :default))
            on-focus #(reset! focused? true)
            on-blur  #(reset! focused? false)]))))
```

NOW:
```clojure
(defn view
  []
  (let [focused? (rn/use-ref-atom false)
        on-clear (rn/use-callback #(set-status (if @focused? :active :default)))
        on-focus (rn/use-callback #(reset! focused? true))
        on-blur  (rn/use-callback #(reset! focused? false))]))

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 5]
```diff
@@ -132,3 +198,47 @@
...
+        {:keys [top]}      (safe-area/get-insets)
+        set-title-bottom   (fn [_ y _ height]
+                             (reset! title-bottom-coord
+                               (+ y height -100 (if platform/ios? (- top) top))))]
+    (fn []
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs:211]: I don't think we need this wrapper anymore..

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 6]
```diff
@@ -132,3 +198,47 @@
...
+                    collectible-data]} collectible
+            {preview-uri :uri}         preview-url
+            {collectible-name :name}   collectible-data
+            {collection-name :name}    collection-data]
+
+        (rn/use-unmount #(rf/dispatch [:wallet/clear-last-collectible-details]))
+
+        [rn/view
+         {:style {:flex             1
+                  :background-color (colors/theme-colors colors/white colors/neutral-95 theme)}}
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs]: Can this live in the `style.cljs` file?
It is mostly a nit, but we only allow one-liners for styles in the view level.

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 7]
```diff
@@ -55,14 +64,72 @@
...
+      [reanimated/view {:style layer-opacity}
+       [quo/page-nav
+        {:type                type
+         :picture             picture
+         :title               title
+         :description         description
+         :background          :blur
+         :icon-name           :i/close
+         :accessibility-label :back-button
+         :on-press            #(rf/dispatch [:navigate-back])
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs]: I think we should we use `rn/use-callback` here.

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 8]
```diff
@@ -55,14 +64,72 @@
     :label               (i18n/label :t/about)
     :accessibility-label :about-tab}])
 
-(defn view
+(defn animated-header
+  [{:keys [scroll-amount title-opacity
+           type picture title description theme]}]
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/collectible/view.cljs]: I think it's better to destructure `type` differently to avoid clashing with Clojure's `type` function.

**Review by ibrkhalil — CHANGES_REQUESTED** [review]
Nice work, Left some nits/concerns.

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 7 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/collectible/view.cljs]: It's better to move it out from the defn altogether

File: src/js/worklets/header_animations.js [hunk 9]
```diff
@@ -0,0 +1,23 @@
...
+  useDerivedValue,
+  interpolate,
+  interpolateColor,
+  Extrapolation,
+  useAnimatedStyle,
+} from 'react-native-reanimated';
+
+export function blurAmount(sharedValue) {
+  return useDerivedValue(() => {
+    return parseInt(interpolate(sharedValue.value, [0, 60], [1, 15], Extrapolation.CLAMP));
```
Comment (FFFra) [inline src/js/worklets/header_animations.js]: Suggestion: Can we move this values to constants? Something like:

```
const CLAMP_MIN = 0;
const CLAMP_MAX = 60;
const BLUR_MIN = 1;
const BLUR_MAX = 15;
```

File: src/js/worklets/header_animations.js [hunk 10]
```diff
@@ -0,0 +1,23 @@
+import {
+  useDerivedValue,
+  interpolate,
+  interpolateColor,
+  Extrapolation,
+  useAnimatedStyle,
+} from 'react-native-reanimated';
+
+export function blurAmount(sharedValue) {
```
Comment (FFFra) [inline src/js/worklets/header_animations.js]: Suggested syntax:

```
export const blurAmount = (sharedValue) => 
  useDerivedValue(() => 
    parseInt(
      interpolate(
        sharedValue.value, 
        [CLAMP_MIN, CLAMP_MAX], 
        [BLUR_MIN, BLUR_MAX], 
        Extrapolation.CLAMP
      )
    )
  );
```

File: src/js/worklets/header_animations.js [hunk 11]
```diff
@@ -0,0 +1,23 @@
...
+  return useDerivedValue(() => {
+    return parseInt(interpolate(sharedValue.value, [0, 60], [1, 15], Extrapolation.CLAMP));
+  });
+}
+
+export function layerOpacity(sharedValue, from, to) {
```
Comment (FFFra) [inline src/js/worklets/header_animations.js]: In that case this could be:


```
export const layerOpacity = (sharedValue, fromColor, toColor) => 
  useAnimatedStyle(() => ({
    flex: 1, // Consider moving this to a higher context if applicable
    justifyContent: 'flex-end',
    backgroundColor: interpolateColor(
      sharedValue.value, 
      [CLAMP_MIN, CLAMP_MAX], 
      [fromColor, toColor], 
      'RGB'
    ),
  }));
```

**Review by FFFra — COMMENTED** [review]
Amazing job, guys! Was a pleasure to contribute to this. Just added a small suggestion to JS code 🚀

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 2 above)
Comment (clauxx) [reply src/status_im/contexts/wallet/collectible/view.cljs]: but this is not an animation. The timeout is here to make sure `measureInWindow` is called later in time

File: src/js/worklets/header_animations.js (hunk 10 above)
Comment (clauxx) [reply src/js/worklets/header_animations.js]: I'd also suggest to keep the `use` prefix for hooks, otherwise they might be misused deeper in the functions by mistake.

File: src/js/worklets/header_animations.js (hunk 11 above)
Comment (clauxx) [reply src/js/worklets/header_animations.js]: Aggreed with @FFFra, the styles that are not relevant to animations should stay in the cljs land

Comment (ulisesmac) [reply src/js/worklets/header_animations.js]: @clauxx @FFFra 
I'd prefer to keep then in the JS side, so we don't need to transform them from cljs->js which is expensive.

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 8 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/view.cljs]: changed the prop name instead

File: src/js/worklets/header_animations.js (hunk 10 above)
Comment (ulisesmac) [reply src/js/worklets/header_animations.js]: @clauxx That's a good suggestion, I'll appy it

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/view.cljs]: done

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/view.cljs]: done

File: src/js/worklets/header_animations.js (hunk 10 above)
Comment (ulisesmac) [reply src/js/worklets/header_animations.js]: @FFFra done

**Comment by ulisesmac** [comment]
@FFFra I tried your code style suggestions but they are being changed by `lint-fix`

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/view.cljs]: @ibrkhalil Thanks for pointing this out.

I moved the atoms I created to `use-ref-atom`. TBH now I feel the code more verbose and harder to understand, but it's on the guidelines.

**Comment by ulisesmac** [comment]
@clauxx @FFFra @ibrkhalil  I already solved the problems, could you please check it again?

cc: @ajayesivan

**Review by ibrkhalil — APPROVED** [review]
✅

**Comment by OmarBasem** [comment]
@ulisesmac don't we need QA or design review for this PR?

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 12]
```diff
@@ -149,3 +214,41 @@
...
+     [animated-header
+      {:scroll-amount scroll-amount
+       :title-opacity title-opacity
+       :page-nav-type :title-description
+       :picture       preview-uri
+       :title         collectible-name
+       :description   collection-name
+       :theme         theme}]
+     [reanimated/scroll-view
+      {:style     (style/scroll-view top)
```
Comment (Parveshdhull) [inline src/status_im/contexts/wallet/collectible/view.cljs:249]: hi, why this is reanimated view instead of simple view?

UPD: Didn't knew we have created a new PR, moved these comments to [there ](https://github.com/status-im/status-mobile/pull/20024#discussion_r1601423723)

File: src/js/worklets/header_animations.js [hunk 13]
```diff
@@ -0,0 +1,25 @@
...
+export const useBlurAmount = (sharedValue) =>
+  useDerivedValue(() =>
+    parseInt(interpolate(sharedValue.value, [CLAMP_MIN, CLAMP_MAX], [BLUR_MIN, BLUR_MAX], Extrapolation.CLAMP)),
+  );
+
+export function useLayerOpacity(sharedValue, from, to) {
+  return useAnimatedStyle(() => ({
+    flex: 1,
+    justifyContent: 'flex-end',
+    backgroundColor: interpolateColor(sharedValue.value, [0, 60], [from, to], 'RGB'),
```
Comment (Parveshdhull) [inline src/js/worklets/header_animations.js:23]: This approach has few drawbacks.
1. I am not sure if situation is changed, but changes in js code were not visible until app restarted
2. Also for consistency we should stick to a single approach. If we use this approach everywhere we will have three files, view, simple style, and animated style, for all animations and we have several animations.
