### PR TITLE
chat: fix input length styling after commands

### LINKED ISSUE #1354: Long parameter text overlaps input field and send button on iphone 5s
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: If i want to change/edit my phone number , i need to input correct confirmation Codes. When i input long confirmation codes, it should be shown correctly in textarea.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The confirmation codes should be shown correctly in textarea, 

#### Actual behavior
[comment]: # (Describe what actually happened.)
The confirmation codes bounds.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Edit my profile
- Click Edit phone number
- Input phone number
- Input long confirmation codes

 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9d5
* Operating System: IOS 10.3.2

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #1354 

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
This PR fixes overflowing characters after  any `/command` input if the text is too long and doesn't fit on one line together with `/command` prefix. 
The reason why it was happening was that minimal width of the input element for commands was set to 200, which together with `/command` width was often more then width of the wrapping container element.
Now the minimal width for the input element is computed by subtracting `/command` width from enclosing container-width.

### Steps to test:
- Open Status
- Open console
- Select `/confirmation-code` command and write some long number there, notice that it doesn't overflow over right edge (over `x` button) as before.

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

File: src/status_im/chat/styles/input/input.cljs [hunk 1]
```diff
@@ -82,8 +82,8 @@
    :ios                 {:line-height min-input-height
                          :left        (+ 10 left)}})
 
-(defnstyle seq-input-text [left]
-  {:min-width           200
+(defnstyle seq-input-text [left container-width]
```
Comment (jeluard) [inline src/status_im/chat/styles/input/input.cljs]: Is there a need for a min? Is it possible to shrink to 0 or negative values?

Comment (janherich) [inline src/status_im/chat/styles/input/input.cljs]: I tried it with no `:min-width` specified and the result was effectively multiline-input, where overflowing text wraps and continues on the next line. 
The problem was that this (multiline-input) for some reason broke `/command` input parsing, maybe because of `/newline` characters present in the input, so I rather retained the single-line input.

Comment (jeluard) [inline src/status_im/chat/styles/input/input.cljs]: Right single-line is perfect. 
I was more thinking something like `(max 200  (- container-width left))`Right single-like is perfect.

Comment (jeluard) [inline src/status_im/chat/styles/input/input.cljs]: Not sure if that's relevant here.

Comment (janherich) [inline src/status_im/chat/styles/input/input.cljs]: That wouldn't help at all, as you need to make `:min-width` the same as container-width minus the place take by `/command` prefix from left. 
200 was just arbitrary number, it's better to compute remaining place left for input.

Comment (jeluard) [inline src/status_im/chat/styles/input/input.cljs]: Perfect! Just wanted to ensure you had consider this point.
