### PR TITLE
chore: fix sorting of pinned messages

### LINKED ISSUE #14743: The pinned message is not updated in the chat screen if one more message is pinned
**Steps to reproduce:**
1. Go to 1-1 chat
2.  Send message "one"
3. Pin message "one" -> pinned message now shows as "one"
4. Send message "two"
5. Pin message "two"

**Actual result:**
The pinned message still shows as "one"

**Expected result:**
The pinned message is shown as "two"

**Notes:**
The pinned message updates after navigating away and back to the chat screen. But should be updated online without chat reopening

### PR DESCRIPTION
**Pull request by J-Son89**
fixes https://github.com/status-im/status-mobile/issues/14743

To test: 

go to a 1-1 chat 
send a message "Test 1"
pin message "Test 1"
send a message "Test 2"
pin message "Test 2"

expected result - "Test 2" should be shown as the pinned message on screen banner. 

Can also test other variants of this to ensure the latest pinned message is showing in the banner

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/pin/banner/view.cljs [hunk 1]
```diff
@@ -4,14 +4,12 @@
 
 (defn banner
   [chat-id]
-  (let [pinned-messages (rf/sub [:chats/pinned chat-id])
-        latest-pin-id   (-> pinned-messages
-                            vals
-                            first
-                            (get :message-id))
-        latest-pin-text (get-in (rf/sub [:chats/chat-messages chat-id])
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/messages/pin/banner/view.cljs:12]: this second sub seems unnecessary as there is access to latest-pin-text from the first sub

File: src/status_im2/subs/chat/messages.cljs [hunk 2]
```diff
@@ -156,7 +156,11 @@
  (fn [pin-messages _]
    (->> pin-messages
         vals
-        (sort-by :pinned-at <))))
+        (sort-by :pinned-at
```
Comment (J-Son89) [inline src/status_im2/subs/chat/messages.cljs]: newly pinned messages don't have `pinned-at` property until the user navigates away and back to the page so we just sort by the pinned messages with this pinned-at  value

Comment (ilmotta) [reply src/status_im2/subs/chat/messages.cljs]: I tried to understand this sorting change @J-Son89, but I couldn't :man_shrugging: The code only sorts subsequent elements in the list containing a non-nil pinned-at value. Is this really what you expected? It's weird to see sorting that doesn't sort anything *sometimes*.

```clojure
(defn pinned-at-comparator
  [a b]
  (if (and a b)
    <
    (if a b a)))

;; Nothing is sorted because there are elements with nil interspersed.
(let [pin-messages [{:id 2 :pinned-at nil}
                    {:id 5 :pinned-at 9}
                    {:id 4 :pinned-at 11}
                    {:id 3 :pinned-at nil}
                    {:id 1 :pinned-at 10}]]
  (assert (= pin-messages
             (sort-by :pinned-at
                      pinned-at-comparator
                      pin-messages))))

;; The list is sorted in ascending order because there are no elements with nil interspersed.
(assert (= [{:id 5 :pinned-at 9}
            {:id 1 :pinned-at 10}
            {:id 4 :pinned-at 11}
            {:id 2 :pinned-at nil}
            {:id 3 :pinned-at nil}]
           (sort-by :pinned-at
                    pinned-at-comparator
                    [{:id 4 :pinned-at 11}
                     {:id 1 :pinned-at 10}
                     {:id 5 :pinned-at 9}
                     {:id 2 :pinned-at nil}
                     {:id 3 :pinned-at nil}])))

```

Comment (J-Son89) [reply src/status_im2/subs/chat/messages.cljs]: yeah, I agree I should adjust. but in this particular case there will never be interspersed `nil` values because the `nil` values only get stacked on when a user is in the chat menu and pinning/un-pinning messages. After they navigate back and to the pinned-messages have a `pinned-at` value

Comment (J-Son89) [reply src/status_im2/subs/chat/messages.cljs]: so yeah, ideally there is cleaner code but this actually does exactly what I want :D

Comment (ilmotta) [reply src/status_im2/subs/chat/messages.cljs]: Cool, thanks for the info @J-Son89.

**Review by ilmotta — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thank you @J-Son89, looks good to me.
PR can be merged.

File: src/status_im2/contexts/chat/messages/pin/banner/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/pin/banner/view.cljs:12]: The second sub was to make pinned messages react to being edited @J-Son89

Comment (J-Son89) [reply src/status_im2/contexts/chat/messages/pin/banner/view.cljs:12]: Ah 😑
