### PR TITLE
Fixes issue with launching of reportApp window on application crash event.

### LINKED ISSUE #6656: No prompt for users what files should be included to crash report
### Description

*Type*: Bug
*Summary*: in order to analyze crash logs `cmd` and `.dmp` files are required, but automatically only `.dmp` file is copied, and it is not obvious for user that he need to attach `cmd` as well.
Basically, all or almost all crash reports are unusable.

#### Expected behavior
2 files are copied and attached to the issue

#### Actual behavior
1 file is copied (`.dmp`)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- got a crash
- click Report
- create issue with default text and files
- open [crash repo](https://github.com/status-im/status-react-desktop-reports/)
- check your issue (issue example https://github.com/status-im/status-react-desktop-reports/issues/43)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 08/11/2018
[comment]: # (Android or iOS.)
* Operating System: Mac OSx, Linux

### PR DESCRIPTION
**Pull request by maxhora**
Signed-off-by: Max Risuhin <risuhin.max@gmail.com>

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #6656

### Summary:

Updates crash report Windows texts to ask user to attach crash .dmp file and Status executable file.
Crash handling on Windows (depends on PR https://github.com/status-im/google-breakpad/pull/1)
Fixes issue with launching of reportApp window on application crash event.

...

status: ready

### CODE REVIEW

**Comment by SlizkovaGanna** [comment]
Tested on Mac, Linux (emulated) and Windows 10 
The window appears for Mac and Linux on application crush event, though the issue from https://github.com/status-im/status-react/issues/6656 still remains.
But for Windows 10 (real device) the app crushes right away as it should but nothing follows.
@MaxRis please fix the Windows-specific issue.

File: desktop/main.cpp [hunk 1]
```diff
@@ -272,6 +265,9 @@ int main(int argc, char **argv) {
     qInstallMessageHandler(saveMessage);
   }
 
+  int* crash_p = nullptr;
```
Comment (vkjr) [inline desktop/main.cpp]: Is this temporary code for testing? :)

**Review by vkjr — APPROVED** [review]

File: desktop/main.cpp (hunk 1 above)
Comment (maxhora) [reply desktop/main.cpp]: @vkjr yes :)

**Review by vitvly — APPROVED** [review]

**Comment by maxhora** [comment]
@SlizkovaGanna updated build is ready for verification.
- Crash catching on Windows is added.
- reportApp windows texts updated to ask user to upload exactly .dmp and Status executable.

Known issue:
- on Linux application doesn't restart on pressing "Restart and quit". Can't find the reason of why new process won't relaunch correctly and errors out silently.

Thank you!

**Comment by churik** [comment]
@MaxRis can you please also add info about required logs directly in Google form (replace`attach log files` to `attach crash.dmp and Status executable files`  )?
please fill details to report the issue 2018-12-07 11-32-24

I tested this on three platforms, will add separate issue about Linux "Restart and quit" (it is not blocker  for this PR).

**Comment by maxhora** [comment]
@churik done!
Have updated changes to not force the crash, PR should be ready to go.
