### PR TITLE
fix: unresponsive add watched address screen when entering a multi-chain address

### LINKED ISSUE #18950: Wallet - Creating a watched address account with a multichain address goes unresponsive at the confirmation screen
# Bug Report

## Problem 

Creating a watched address account with a multichain address goes unresponsive at the confirmation screen

| Enter multichain address | Confirm page where `Add watched address` btn is unresponsive |
| -- | -- |
|  |  |

⚠️ NOTE: The reason why the creation is stuck is because `status-go` doesn't accept multichain addresses on account creation. It returns the following error:
```
invalid argument 1: json: cannot unmarshal hex string without 0x prefix into Go struct field Account.address of type types.Address
```

#### Expected behaviour

The app should not accept multichain addresses on the address input (same as Desktop behaviour)

### Reproduction

1. Open Status
2. Navigate to the Wallet tab
3. Tap on `+` to add new watch address
4. Enter a multichain address (Eg: `eth:opt:arb1:0x9bf27d0c9aba562dc33bc4b60c233a6609ce2987`)
5. Tap on `Confirm` to navigate to the next screen
6. Enter a name
7. Tap on `Add watched address`

### Additional Information

- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18950

### Summary

This PR aims to fix unresponsive add watched address screen when entering a multi-chain address. The approach I took is to extract the plain address from the multi-chain address so status-go endpoint doesn't return an error and the flow continues as expected. Either way address is watched for all the available chains.

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

1. Open Status
2. Navigate to the Wallet tab
3. Tap on `+` to add new watch address
4. Enter a multichain address (Eg: `eth:opt:arb1:0x9bf27d0c9aba562dc33bc4b60c233a6609ce2987`)
5. Tap on `Confirm` to navigate to the next screen
6. Enter a name
7. Tap on `Add watched address`
8. Verify the screen is responsive and the watched address is created successfully

status: ready

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]
Nice 👌

**Review by shivekkhurana — APPROVED** [review]

File: src/status_im/contexts/wallet/add_address_to_watch/view.cljs [hunk 1]
```diff
@@ -22,6 +23,10 @@
      (or (validation/eth-address? user-input)
          (validation/ens-name? user-input))) (i18n/label :t/invalid-address)))
 
+(defn- extract-address
+  [scanned-text]
+  (first (re-seq constants/regx-address-contains scanned-text)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_address_to_watch/view.cljs]: We might want to just use `re-find` since it returns the first match.

[re-find](https://clojuredocs.org/clojure.core/re-find)
[re-seq](https://clojuredocs.org/clojure.core/re-seq)

Additionally, I'm wondering what happens when it's not found? is that case properly handled?

Comment (briansztamfater) [reply src/status_im/contexts/wallet/add_address_to_watch/view.cljs]: Thanks @ulisesmac, updated the function :)

> Additionally, I'm wondering what happens when it's not found? is that case properly handled?

That should not happen as we are calling `extract-address` with `:wallet/watch-address-validated-address` sub value, and it always returns a valid address. If there's no valid address the button is disabled and `extract-address` is never called.

Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_address_to_watch/view.cljs]: Ok :+1:  thanks for the explanation

**Review by ulisesmac — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater !
Thanks for your fix! Great job!
You can merge it.
