### PR TITLE
[#4361] Don't autocorrect incomplete and erroneous entries for transactions.

### LINKED ISSUE #4361: Typing fast on iOS amount field leads to incorrect sums
### Description

*Type*: Bug

*Summary*:  when i type fast on iOS small sums like 0,0094 it appears as 94

#### Expected behavior
when i enter anount in Amount field it is shown correctly 

#### Actual behavior
wrong amount is shown (2 instead of 0,02)

### Reproduction
- Open Status
- Go to wallet - send
- Enter 0,02 amount quickly in amount field

### LINKED ISSUE #4631: QR code buttons in custom mailservers and bootnodes are hard to tap
### Description

*Type*: Bug

*Summary*: Tapping it once always closes the keyboard but does not open the QR scanner (Android and iOS). Tapping it again does not open it sometimes as well (Android only, iOS worked fine). Maybe we should increase the tapping area?

#### Expected behavior
The QR code button looks and behaves like the button in new chat screen. Notice the big tapping area and that it's separated from the input field:
 

#### Actual behavior
Button is hard to tap.

### Reproduction

- Open Status
- Go to Profile, Advanced
- Open Mailserver option and add mailserver by scanning QR code

### Additional Information
* Status version: build from https://github.com/status-im/status-react/pull/4616
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by mandrigin**
When a user types an invalid number (like "0..0") or he just pauses during typing a long list of zeroes (0.00000<pause>), don't auto replace his text with the parsed amount.

fixes #4361 

### Steps to test:
- Open Status
- Go to wallet
- Type "0.000<pause>07".
- 0.00007 should be in the window.

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 1]
```diff
@@ -221,10 +221,15 @@
...
                                                         (when-not sufficient-funds? (i18n/label :t/wallet-insufficient-funds)))
-                                     :input-options {:default-value  (str (money/to-fixed (money/wei->ether amount)))
-                                                     :max-length     21
-                                                     :on-focus       (fn [] (when (and scroll @scroll) (utils/set-timeout #(.scrollToEnd @scroll) 100)))
-                                                     :on-change-text (update-amount-fn timeout)}}]
+                                     ;; While a user is typing something like "0.00000..." it is a very bad idea to replace it with just "0"
+                                     ;; we might break his intent. Also that keeps the text-input from interfering when a user tries to
+                                     ;; fix his typo.
+                                     :input-options (merge
+                                                     (if (pos? amount)
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/views.cljs]: We use `when` when there is a single branch.

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 2]
```diff
@@ -221,10 +221,15 @@
...
+                                                       {:default-value  (str (money/to-fixed (money/wei->ether amount)))})
+                                                     {:max-length     21
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/views.cljs]: Starting merge with static map looks more idiomatic (some swipe both merge arguments).

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 1 above)
Comment (rasom) [inline src/status_im/ui/screens/wallet/send/views.cljs]: should be `(when (pos? amount)`

**Review by rasom — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 1 above)
Comment (janherich) [reply src/status_im/ui/screens/wallet/send/views.cljs]:
```clj
(cond-> static-map
   (pos? amount) (assoc :default-value (str (money/t...))))
```
Would be good as well, I don't particularly like merging to introduce just one kv pair into map, but that's mostly matter of taste :)

Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/views.cljs]: fixed (used `when`)

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 2 above)
Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/views.cljs]: fixed

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 1 above)
Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/views.cljs]: fixed

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/jBxJ4N for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/jBxJ4N">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/f3JmRB for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/f3JmRB">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@mandrigin how about following scenario:
- Type "0.003"
- Remove last character and expect "0.00"
-> "0.00" is automatically removed by the app. The field is empty.

Should it behave like that?

**Comment by mandrigin** [comment]
@lukaszfryc hmm, I don't think so. Is it consistent?

**Comment by lukaszfryc** [comment]
@mandrigin it's weird for me that the input changes without my action. I'd just leave "0.00" and let user decide what she wants. 

I checked 0.9.18 and there, the "0.00" was removed as well but "0" was left.

**Comment by mandrigin** [comment]
@lukaszfryc the weird part is that the field becomes empty, it shouldn't happen... let me try reproducing...

**Comment by mandrigin** [comment]
@lukaszfryc found the cause of the issue, fixing...

**Comment by mandrigin** [comment]
@lukaszfryc the next build should work correctly :)

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 3]
```diff
@@ -221,10 +221,17 @@
         [components/amount-selector {:disabled?     modal?
                                      :error         (or amount-error
                                                         (when-not sufficient-funds? (i18n/label :t/wallet-insufficient-funds)))
-                                     :input-options {:default-value  (str (money/to-fixed (money/wei->ether amount)))
-                                                     :max-length     21
+                                     :input-options {:max-length     21
                                                      :on-focus       (fn [] (when (and scroll @scroll) (utils/set-timeout #(.scrollToEnd @scroll) 100)))
-                                                     :on-change-text (update-amount-fn timeout)}}]
+                                                     :on-change-text (update-amount-fn timeout)
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/views.cljs:226]: Would it make sense to refactor the whole `input-options` so that there is no duplication?

Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/views.cljs:226]: it does, there is quite a bit of duplication there, both with views and this logic.
can we do that in a follow-up PR just to unblock this release?

Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs:226]: Sure makes sense. Then I would replace the second block of comment with a TODO. Also could you create related GH issue? :sweat_smile:

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 3 above)
Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/views.cljs:226]: there is already a TODO in the request part to refactor it ;-)

Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs:226]: Ah you mean my TODO ? ;) I guess I was hoping you would fix it :D

Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/views.cljs:226]: Yeah, I'm planning to follow-up on it tomorrow.
I think it is a good exercise in Clojure for me :)

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/aLrqjT for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/aLrqjT">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/J4yqzB for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/J4yqzB">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@lukaszfryc and the next build is done ;)

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/sdP5ju for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/sdP5ju">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/AwyAJF for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/AwyAJF">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/esQwhm for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/esQwhm">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/45Wyuh for branch PR-4378

<blockquote><div><strong><a href="https://i.diawi.com/45Wyuh">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
