### PR TITLE
Fix usage of ratom to fix wallet share

### LINKED ISSUE #18874: 'no protocol method iReset' Error occurs when selecting a checkbox in the filter on the Share screen in the Wallet tab for multichain.
Error occurs when selecting a checkbox in the filter on the Share screen in the Wallet tab for multichain.

### Steps:
1. Open the "Share" screen.
2. Tap the 'wallet' tab and select multichain.
3. Tap the 'filter' button.
4. Select any checkbox.
5. Tap the 'update' button.

### Actual result:
'no protocol method iReset'  error occurs after selecting any chain.

https://github.com/status-im/status-mobile/assets/52490791/8d970b96-b645-41e6-94e3-f240dfb99cb1

### Expected result: 
No error should occur after selecting a chain.

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #18874 

### Summary
Fixes a typo related to wallet share screen.

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

File: src/status_im/contexts/shell/share/wallet/view.cljs [hunk 1]
```diff
@@ -74,7 +74,7 @@
             :emoji               (:emoji account)
             :on-multichain-press #(reset! wallet-type :multichain)
             :on-legacy-press     #(reset! wallet-type :legacy)
-            :on-settings-press   #(open-preferences @selected-networks)}]]]))))
+            :on-settings-press   #(open-preferences selected-networks)}]]]))))
```
Comment (J-Son89) [inline src/status_im/contexts/shell/share/wallet/view.cljs]: Hmm, not particularly a fan of passing ratoms through to functions. Is this something we can avoid? 
It seems better if a component can just take the value as a prop instead. Do we have a better approach for situations like this?
cc @ilmotta, @ulisesmac, @Parveshdhull

**Comment by J-Son89** [comment]
Also I think this fix is needed due to recent changes on the network preferences. Would appreciate that @smohamedjavid gets to check this before it goes to qa etc. 
cheers for the fix! 🙏

File: src/status_im/contexts/shell/share/wallet/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/contexts/shell/share/wallet/view.cljs]: Hi, In this particular scenario, we are modifying the state of current component based on what actions are performed on the next screen.
If we don't want to directly pass this ratom, we can instead pass the function that does the modification in the end ([on-save](https://github.com/status-im/status-mobile/blob/9362d12bbddea497f4efc943f0510d3194e1d09d/src/status_im/contexts/shell/share/wallet/view.cljs#L43))

**Review by smohamedjavid — APPROVED** [review]

File: src/status_im/contexts/shell/share/wallet/view.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/shell/share/wallet/view.cljs]: These functions are constant (`:on-settings-press`, `:on-legacy-press` and `on-multichain-press`) in terms of they always do the same.

Currently, each time the atoms `selected-networks` or `wallet-type` change, the component will regenerate the involved functions, but there's no need of it.

We can define them in the form-2 initializing section:
```clojure
(defn wallet-qr-code-item-internal [props]
  (let [{:keys [account width index]} props
        selected-networks             (reagent/atom [:ethereum :optimism :arbitrum])
        wallet-type                   (reagent/atom :legacy)
        on-legacy-press               #(reset! wallet-type :legacy) ;; Here
        on-settings-press             #(open-preferences @selected-networks) ;; Here
        ...
        ]
    (fn [...]
      ...)))
```

So that we will pass the exact same object (function) to the child (`quo/share-qr-code`), it helps to avoid undesired rerenders.


@J-Son89 I think sometimes it's actually needed to deref an atom inside a callback function, but most of the times we can define that function once instead of on each rerender.

**Comment by mariia-skrypnyk** [comment]
@ibrkhalil hi!

Can you please rebase your PR?

**Comment by ibrkhalil** [comment]
> @ibrkhalil hi!
> 
> Can you please rebase your PR?

Done

**Comment by mariia-skrypnyk** [comment]
Hi @ibrkhalil! Thanks for your PR!


**ISSUE 1: App crashes on Onboarding on Notifications step**

**Steps:**

1. Download app
2. Go through Onboarding
3. Choose Maybe Later on Notifications screen

**Actual result:** app crashes (10/10)
**Device:** 13 iPhone 17.3.1 version (it is important!), NO such issue on 17.2.1 BUT after update to 17.3.1 it was also reproduced on SE

**Expected result:** no crash

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil! Thanks for your PR!
> 
> **ISSUE 1: App crashes on Onboarding on Notifications step**
> 
> **Steps:**
> 
> 1. Download app
> 2. Go through Onboarding
> 3. Choose Maybe Later on Notifications screen
> 
> **Actual result:** app crashes (10/10) **Device:** 13 iPhone 17.3.1 version (it is important!), NO such issue on 17.2.1 BUT after update to 17.3.1 it was also reproduced on SE
> 
> **Expected result:** no crash

Rebased again, Hopefully that fixes the issue.
Thanks!

**Review by ulisesmac — APPROVED** [review]
Nice :+1:

**Comment by mariia-skrypnyk** [comment]
**ISSUE 2: [iOS] Error on Wallet tab of Share screen**

**Steps:**
1) Login to app
2) Go to Share-> Wallet tap
3) try to scroll the screen

**Actual result:**
Screenshot 2024-02-28 at 14 46 20

Logs are attached. 
[status_logs (1).zip](https://github.com/status-im/status-mobile/files/14434846/status_logs.1.zip)

**Expected result:** no error

**Comment by mariia-skrypnyk** [comment]
Hi @ibrkhalil !

Please, feel free to merge!
Thanks!
