### PR TITLE
fix: shell button position in chat screen

### LINKED ISSUE #16104: Messaging - In Chat - "Jump To" button should disappear when input is focused or in scrolled position
"Jump To" button should disappear when typing.

This is how it should look as in the designs - 
IMG_32DD96785060-1

Designs:
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=3101-347945&t=Yspiy1M9ZTNBqu6s-4

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/16104

This PR fixes shell button position in chat screen by making it disappear when input is focused or when in a scrolled position.

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im2/contexts/chat/composer/style.cljs [hunk 1]
```diff
@@ -109,3 +109,19 @@
    :blur-radius (if platform/ios? 20 10)
    :blur-type   (colors/theme-colors :light :dark)
    :blur-amount 20})
+
+(defn shell-container
+  [bottom translate-y]
+  (reanimated/apply-animations-to-style
+   {:bottom bottom} ; we use height of the input directly as bottom position
```
Comment (J-Son89) [inline src/status_im2/contexts/chat/composer/style.cljs]: maybe it would be easier to have this as:
```
[input-height translate-y]
  (reanimated/apply-animations-to-style
   {:bottom input-height} 
```
maybe there is less need for the comment then 🤔

**Comment by J-Son89** [comment]
Hey @OmarBasem, it should disappear on scroll on chat too? For me this is not happening 🤔  Or perhaps I have tested it wrong. 
Disappears correctly on focus 👌 
tested on iphone 11 Pro simulator btw

**Review by ilmotta — APPROVED** [review]
Looks good in my tests.

Not sure if it's tracked somewhere in another issue, but when the composer is maximized the header stays on the way. It's unrelated to this PR, but I felt like sharing anyway. @J-Son89 do you know if we have an issue?

**Comment by J-Son89** [comment]
@ilmotta not sure about that specifically but there is this issue about composer height - perhaps you can add that note there as it's related:
https://github.com/status-im/status-mobile/issues/16093

**Comment by OmarBasem** [comment]
@J-Son89 scroll a little bit and it will disappear (just when the scroll button appears)

**Comment by OmarBasem** [comment]
@J-Son89 @ilmotta that header issue is caused by the new chat screen top bar. I believe there is an open issue. cc @alwx

File: src/status_im2/contexts/chat/composer/style.cljs (hunk 1 above)
Comment (OmarBasem) [reply src/status_im2/contexts/chat/composer/style.cljs]: Better be clear I think. One might think why not make it `:height input-height`?

Comment (J-Son89) [reply src/status_im2/contexts/chat/composer/style.cljs]: If anything it is less clear that `bottom` here is input height if we only intend to use this for a single use case. `bottom` makes it seem re-useable but that comment will be misleading if this function is used elsewhere and not making use of input height.

imo using named variables makes this clearer.  In any case you can leave the comment but I think it's better if the code speaks for itself (with/without comments).

**Comment by qoqobolo** [comment]
Hi @OmarBasem, thanks for the fix!

### ISSUE 1: There is still an area above the drawer you can tap and the shell will open, even though the `Jump to` button is hidden

Not sure this is expected. 

**Steps:**
1. Open chat
2. Expand the keyboard
3. Start tapping an area where the `Jump to` button was before 

**OS:** Android, iOS

https://github.com/status-im/status-mobile/assets/67952253/dbed4ea3-8b9d-4ad0-863b-efd40af2c569

**Review by J-Son89 — APPROVED** [review]
@OmarBasem i showed this to @mariocnovoa. Looks good for now, there is a follow up feature to also make the jump to button disappear when the user is scrolling fast. I think that's what I was not seeing before, but this pr is good to go. 🙌🏼

**Comment by OmarBasem** [comment]
> @OmarBasem i showed this to @mariocnovoa. Looks good for now, there is a follow up feature to also make the jump to button disappear when the user is scrolling fast. I think that's what I was not seeing before, but this pr is good to go. 🙌🏼

Thanks @J-Son89 for the feedback.
What do you mean by when scrolling fast. The button disappears when scrolling fast too.

Btw, it would be great if you can get feedback on [this one](https://github.com/status-im/status-mobile/pull/16216) cause I am not able to reach the design team :)

**Comment by OmarBasem** [comment]
Thanks for your testing @qoqobolo !
The issue is fixed

**Comment by J-Son89** [comment]
> > @OmarBasem i showed this to @mariocnovoa. Looks good for now, there is a follow up feature to also make the jump to button disappear when the user is scrolling fast. I think that's what I was not seeing before, but this pr is good to go. 🙌🏼
> 
> 
> 
> Thanks @J-Son89 for the feedback.
> 
> What do you mean by when scrolling fast. The button disappears when scrolling fast too.
> 
> 
> 
> Btw, it would be great if you can get feedback on [this one](https://github.com/status-im/status-mobile/pull/16216) cause I am not able to reach the design team :)

Sure, will discuss with them to get a response on this 👌

**Comment by qoqobolo** [comment]
@OmarBasem thank you! Found another one

### ISSUE 2: The `Jump to` button is partially hidden behind the collapsed drawer when replying/editing the message

**Steps:**
1. Send a message
2. Reply/edit it
3. Collapse the drawer

**OS:** Android, iOS

https://github.com/status-im/status-mobile/assets/67952253/6afddd62-fd3a-4fe2-a4e9-12463553d2fb

**Comment by OmarBasem** [comment]
Thank you @qoqobolo! The issue is fixed

**Comment by qoqobolo** [comment]
LGTM! Thanks for your work @OmarBasem, PR is ready to be merged.
