### PR TITLE
[#5024] Fix for landscale layout on Backup Seed screen

### LINKED ISSUE #5024: [ipad] Button "Ok, continue" is not visible on Backup Seed Phrase screen in landscape mode
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Button "Ok, continue" is not visible on Backup Seed Phrase screen in landscape mode. Picture also seems to be of a wrong size for landscape screen.

Note: if turn to portrait mode then it's possible to tap on the button "Ok, continue" and work with app.
img-0430

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Picture and button "Ok, continue" fit screen. User can tap on the button and proceed to the Seed phrase

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
00:21 https://app.testfairy.com/projects/4803590-status/builds/8509899/sessions/4395294021/?accessToken=NKl6NYquyaGJS1FfVZD/iopAwjQ
- Open Status and login in landscape mode
- Profile -> Backup your Seed Phrase
- Try to tap on button "Ok, continue"

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: PR build https://github.com/status-im/status-react/pull/4720#issuecomment-401107276
* Operating System:  iPad mini 3, iOS 11.4

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8509899/sessions/4395294021/?accessToken=NKl6NYquyaGJS1FfVZD/iopAwjQ">TestFairy: Status 0.9.21 (6133) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #5024

### Summary:

Fix for landscale layout on Backup Seed screen

status: ready

screenshot 2018-07-17 10 24 30

### CODE REVIEW

File: src/status_im/ui/components/common/common.cljs [hunk 1]
```diff
@@ -95,10 +96,14 @@
...
      {:reagent-render
       (fn [{:keys [container-style style]} {:keys [image width height]}]
-        [react/view {:style     (merge styles/image-contain container-style)
-                     :on-layout #(reset! content-width (-> % .-nativeEvent .-layout .-width))}
-         [react/image {:source      image
-                       :resize-mode :contain
-                       :style       (merge style
-                                           {:width  @content-width
-                                            :height (/ (* @content-width height) width)})}]])})))
+        (let [{window-width :width window-height :height} @(re-frame/subscribe [:dimensions/window])]
```
Comment (flexsurfer) [inline src/status_im/ui/components/common/common.cljs]: maybe better to use `defview`?

Comment (dmitryn) [reply src/status_im/ui/components/common/common.cljs]: @flexsurfer yes, changed to defview

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by annadanchenko** [comment]
@dmitryn fix on iPad looks good. on iPhone 5s there is still an issue but I can make it as a separate bug than.

Is this fix touches only Backup seed phrase screen or it makes sense to check more screens?

**Comment by dmitryn** [comment]
@annadanchenko i will fix issue with 5s in this PR, no need to create separate issue.
I've checked all the screens i had in mind, but it would be good if you could also check them.

**Comment by dmitryn** [comment]
@annadanchenko i've pushed the fix for smaller screens (like iphone 5s), please take a look.

**Comment by annadanchenko** [comment]
thank you @dmitryn it looks good now. Please, update CHANGELOG.md and it can be merged
