### PR TITLE
Fix community header title animation

### LINKED ISSUE #19196: Community page bugs [Android]
# Design Feedback 2.27

## [Android] Community page bugs

- **Community name bug** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#719362896)] after scrolling down and back up the community name doesn't behave as expected and stays in the top nav
- **Emoji gets cut off** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#719363368)] in the first community tag

#### Expected behavior

Screenshot 2024-03-12 alle 12 55 22

#### Actual behavior

Screenshot 2024-03-12 alle 12 55 44

### Reproduction

1. Open a community you're not a member of using an Android device
2. Scroll down the channel list to see community name animation
3. Scroll back up to the top of the page

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #19196

status: ready

### CODE REVIEW

**Comment by ajayesivan** [comment]
I was unable to reproduce the bug of emojis being cut off. Let me know if you can reproduce that issue in this PR.

**Review by Parveshdhull — APPROVED** [review]

File: src/quo/components/navigation/page_nav/style.cljs [hunk 1]
```diff
@@ -14,12 +15,13 @@
...
 (defn center-content-container
   [centered? center-opacity]
-  {:flex              1
-   :margin-horizontal 12
-   :flex-direction    :row
-   :align-items       :center
-   :justify-content   (if centered? :center :flex-start)
-   :opacity           center-opacity})
+  (reanimated/apply-animations-to-style
+   (when center-opacity {:opacity center-opacity})
```
Comment (ibrkhalil) [inline src/quo/components/navigation/page_nav/style.cljs]: Curious about how this might behave if `center-opacity` is falsy.

**Review by ibrkhalil — APPROVED** [review]

File: src/quo/components/navigation/page_nav/style.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/quo/components/navigation/page_nav/style.cljs]: hi @ibrkhalil good question. It will work, we will just not have animations.

If you check
https://github.com/status-im/status-mobile/blob/6a88a34d340e43063c75082113b4f6846a98ac9d/src/js/worklets/core.js#L39
We are looping over animations map (when has keys) and then performing operations.

Comment (ulisesmac) [reply src/quo/components/navigation/page_nav/style.cljs]: Hey @ajayesivan  Looks good, I just wanted to add a comment.

The function `apply-animations-to-style` is using the `use-animated-style` hook, and hooks have some rules, such as being called at the beginning of the component.

> Don’t call Hooks inside loops, conditions, or nested functions. Instead, always use Hooks at the top level of your React function, ...

Both [old react docs](https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level)  and [new docs](https://react.dev/reference/rules/rules-of-hooks#only-call-hooks-at-the-top-level) share the same idea.

To fix this issue I can see two approaches:

1. Move this call to the top level of the parent component, compute it once, and just pass the returned animated styles to each child, I'm not completely sure, but it seems the same calculation is being done multiple times :thinking: if so, this will also slightly improve the performance.

2. Remove the hook usage and just use the vector syntax for [inline animation styles](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/glossary#animations-in-inline-styling).

besides that, the code looks fine, wdyt?

**Comment by mariia-skrypnyk** [comment]
@ajayesivan can you please resolve the conflicts and rebase your PR?

**Comment by ajayesivan** [comment]
Hi @mariia-skrypnyk, I have rebased and resolved the conflicts. Thank you!

**Comment by mariia-skrypnyk** [comment]
Hi @ajayesivan !

Thanks for your work!
I've checked tag icon issue and name moving up.
All they are fixed.

https://github.com/status-im/status-mobile/assets/147824399/fdf35c59-726e-47fb-af0a-49b67da3fc3f

Will move PR to design review by @Francesca-G 🔬.

**Review by Francesca-G — APPROVED** [review]
Looks good to me now 👍

**Review by ibrkhalil — APPROVED** [review]
