### PR TITLE
[#6307] fix each message sent before upgrade is shown twice after 0.9.29

### LINKED ISSUE #6307: Each message sent before upgrade is shown twice after upgrade from 0.9.29
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Each message sent before upgrade is shown twice after upgrade from 0.9.29
https://s3.amazonaws.com/testfairy/screenshots/4803622/8626941/109020185/14_643b03d7310e82ad5fd0f3960e8ff3224fc6032b_o.jpg
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Message is shown once
#### Actual behavior
[comment]: # (Describe what actually happened.)
Message sent once is shown twice after upgrade
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install 0.9.29 Status
- Send 3 messages to public chat, e.g. 1, 2 and 3
- Upgrade to nightly build
- open the public chat and wait for messages to be fetched.
- check how sent 1,2,3 are shown now (in my case it's 1,1,2,2,3,3)

after upgrade: https://app.testfairy.com/projects/4803622-status/builds/8626941/sessions/4403987481/?accessToken=sBz/h9vUxgG03QEz9C1nwqnEpZE

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: upgrade from 0.9.29 from playstore to nightly from Oct 14
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

<blockquote></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8626941/sessions/4403987481/?accessToken=sBz/h9vUxgG03QEz9C1nwqnEpZE">TestFairy: Status 0.9.29 (10419) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by rasom**
fix #6307

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

File: src/status_im/chat/models/message.cljs [hunk 1]
```diff
@@ -148,10 +148,13 @@
             (chat-loading/group-chat-messages chat-id (get chat->message chat-id))))
 
 (defn- add-to-chat?
-  [{:keys [db]} {:keys [chat-id clock-value message-id] :as message}]
+  [{:keys [db]} {:keys [chat-id clock-value message-id message-id-old-format] :as message}]
   (let [{:keys [deleted-at-clock-value messages not-loaded-message-ids]}
         (get-in db [:chats chat-id])]
     (not (or (get messages message-id)
+             ;; TODO(rasom): remove this condition
```
Comment (cammellos) [inline src/status_im/chat/models/message.cljs:152]: Not sure it is accurate, I am guessing your are thinking of nightlies, but if we don't include this in the next release, any user that goes to 0.9.29 -> 0.9.31 will still experience the issue (and so on) or I am missing something? have we made a decision that that's ok?
(genuinely asking not expressing my opinion on the issue).

Comment (rasom) [reply src/status_im/chat/models/message.cljs:152]: Yeah, that's true, that user will encounter this problem. 

No decisions were made, my opinion is that it is ok. But we also can keep this condition for all period while 0.9.29 will be available, for TestFlight it is 77 days from now and idk how to check this for Play Market.

Another option might be a migration for ids, but it might cause even more bugs in the result.

Comment (cammellos) [reply src/status_im/chat/models/message.cljs:152]: I would agree that is not a big deal, and seems ok to just leave the code for a bit longer.
If we do go for a migration though I think we should re-think the id generation, as the current method has the same drawbacks as the previous (namespace included / relies on consistent ordering of map keys). (maybe even worth doing now, but I understand there some time pressure).

Comment (rasom) [reply src/status_im/chat/models/message.cljs:152]: yep, there is definitely some pressure, i suppose we will just return to this again later...

Comment (rasom) [reply src/status_im/chat/models/message.cljs:152]: @cammellos, i changed comment a bit

**Review by cammellos — APPROVED** [review]

**Comment by Serhy** [comment]
@rasom still can reproduce the issue (tested on Android 7). I need just to wait long enough for messages finished to be fetched. 

1) Install 0.9.29 release build
2) Open Status and create a new account
3) Join any unique public chat (e.g. `sendasand`)
4) Send 5 text messages 
5) Close the app
6) Install https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181016-075924-befc26-pr.apk build
7) Log in to you contact previously created and wait till `Fetching messages...` disappear and check  public chat

<blockquote></blockquote>

**Comment by rasom** [comment]
@yenda @cammellos any ideas what can be wrong with this PR? When i test it locally it works fine, but when upgrading from 0.9.29 on Android it is still reproducible...

**Comment by rasom** [comment]
oh well https://github.com/status-im/status-react/blob/c017951c14ba22b12a039b57cb3e6619b3edf6f8/src/status_im/transport/message/transit.cljs#L104 `(:text content)` might be the reason

**Comment by yenda** [comment]
@rasom yes namespaces are probably not the only potential cause of problems, if the content passed to the message changes as well between version, best to replace content by :text value I guess

**Comment by rasom** [comment]
well, it seems that message id was broken before namespace renaming

**Comment by rasom** [comment]
@Serhy ready for testing again

**Comment by Serhy** [comment]
@rasom yes, looks good to me! 
Upgrade on Android 6.0.1, Android 7 (from release 0.9.29 app to latest builds here) and MacOS upgrade has no duplicated messages. 
For iOS, because of issue https://github.com/status-im/status-react/issues/6339 I wasn't able to upgrade from 0.9.29 TestFligh Rlease build to iOS build from https://github.com/status-im/status-react/pull/6313#issuecomment-430374487. So I created a build based on release/0.9.29 branch and tested based on it, which is OK.
Failed autotests reviewed and confirmed as not related to this PR (false Fail or known issues)

This one ready for merge. Thanks a lot, @rasom !
