### PR TITLE
Fix for "no routes found" on transaction confirmation page

### LINKED ISSUE #19780: Transaction fails with 'No Routes Found' message on transaction confirmation page
introduced in the https://github.com/status-im/status-mobile/pull/19750

### Steps:
1. Go to wallet
2. Go to send flow
3. Enter available asset value for assets sending
4. Attempt to confirm the transaction

### Actual result:
No routes found' message is displayed on the transaction confirmation page

https://github.com/status-im/status-mobile/assets/52490791/56646632-3612-46cd-be31-7c0b203390ed

### Expected result:
Transaction can be sent

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (7).zip](https://github.com/status-im/status-mobile/files/15091581/logs.7.zip)

cc: @vkjr

### PR DESCRIPTION
**Pull request by vkjr**
fixes #19780

### Summary
This pr fixes:
- issue with the transaction confirmation page when routes were not found.
- a problem when the value inputed by the user was displayed in red even when it doesn't exceed the limit

https://github.com/status-im/status-mobile/assets/5786310/b8f3952e-a6d2-41cc-b79c-4629bf5c377b

### Steps to test

- Go to wallet
- Go to send flow
- Enter available asset value for assets sending
- Attempt to confirm the transaction

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
all good by me, but for sure @briansztamfater's input here would be great 🙏

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 1]
```diff
@@ -115,20 +114,18 @@
...
             fiat-limit                    (.toFixed (* token-balance conversion-rate) 2)
-            current-limit                 #(if @crypto-currency? crypto-limit fiat-limit)
-            routes-can-be-fetched?        (and (= nav-current-screen-id current-screen-id)
-                                               (not
-                                                (or (empty? (controlled-input/input-value input-state))
-                                                    (<= (controlled-input/numeric-value input-state) 0)
-                                                    (> (controlled-input/numeric-value input-state)
-                                                       (current-limit)))))
+            current-limit                 (if @crypto-currency? crypto-limit fiat-limit)
+            valid-input?                  (not (or (empty? (controlled-input/input-value input-state))
```
Comment (ibrkhalil) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs]: `empty?` Won't detect whitespace
Better to use `clojure.string/blank?`

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 2]
```diff
@@ -115,20 +114,18 @@
...
                                                token-balance))
             fiat-limit                    (.toFixed (* token-balance conversion-rate) 2)
-            current-limit                 #(if @crypto-currency? crypto-limit fiat-limit)
-            routes-can-be-fetched?        (and (= nav-current-screen-id current-screen-id)
-                                               (not
-                                                (or (empty? (controlled-input/input-value input-state))
-                                                    (<= (controlled-input/numeric-value input-state) 0)
-                                                    (> (controlled-input/numeric-value input-state)
-                                                       (current-limit)))))
+            current-limit                 (if @crypto-currency? crypto-limit fiat-limit)
```
Comment (vkjr) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:117]: Current limit is no longer a function because it don't need to be

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 3]
```diff
@@ -241,12 +243,12 @@
                                                            (not-empty routes))]
 
     (rn/use-effect
-     #(when (> (count affordable-networks) 0)
-        (fetch-routes input-value routes-can-be-fetched? 2000))
-     [input-value routes-can-be-fetched?])
+     #(when (and active-screen? (> (count affordable-networks) 0))
+        (fetch-routes input-value valid-input? 2000))
+     [input-value valid-input?])
```
Comment (briansztamfater) [inline src/status_im/contexts/wallet/send/routes/view.cljs:248]: Do we actually need to react to `valid-input?`? I think passing only `input-value` would be okay.

File: src/status_im/contexts/wallet/send/routes/view.cljs [hunk 4]
```diff
@@ -202,18 +202,20 @@
       :on-press-to-network   on-press-to-network}]))
 
 (defn fetch-routes
-  [amount routes-can-be-fetched? bounce-duration-ms]
-  (if routes-can-be-fetched?
+  [amount valid-input? bounce-duration-ms]
```
Comment (vkjr) [inline src/status_im/contexts/wallet/send/routes/view.cljs:205]: This function was the cause of the problem. It was getting too generic condition `routes-can-be-fetched?` that was made from two logical conditions - if the valid is input and if we are still on the routes screen.
And when user navigated to confirmation page that condition became false which lead to clearing suggested routes.

Now in this function we rely only on input validity. And when the screen is wrong we dont't even call it.

File: src/status_im/contexts/wallet/send/input_amount/view.cljs [hunk 5]
```diff
@@ -167,8 +164,8 @@
              #(.remove app-keyboard-listener))))
         (rn/use-effect
          (fn []
-           (set-input-state #(controlled-input/set-upper-limit % (current-limit))))
-         [@crypto-currency?])
+           (set-input-state #(controlled-input/set-upper-limit % current-limit)))
+         [current-limit])
```
Comment (vkjr) [inline src/status_im/contexts/wallet/send/input_amount/view.cljs:169]: Now limit updated correctly.

File: src/status_im/contexts/wallet/send/routes/view.cljs (hunk 3 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/send/routes/view.cljs:248]: Well, theoretically we can remove it because we know that input validity depends only on input value. But that is kind of knowledge that we have outside of the component. If for some reason the validity rule will change, not having valid-input? as a dependency can cause an error

File: src/status_im/contexts/wallet/send/input_amount/view.cljs (hunk 1 above)
Comment (vkjr) [reply src/status_im/contexts/wallet/send/input_amount/view.cljs]: @ibrkhalil, fixed)

**Review by ibrkhalil — APPROVED** [review]

**Review by OmarBasem — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @vkjr, thanks for the fix!

> a problem when the value inputed by the user was displayed in red even when it doesn't exceed the limit

I think there is a PR by @mmilad75 which addresses the same issue https://github.com/status-im/status-mobile/pull/19711

Could you guys confirm and decide which fix will we use? Thank you.

**Comment by vkjr** [comment]
@pavloburykh, I believe that @mmilad75 fixed other causes of similar issue, no interference here. Plus I believe that PR should be rebased to take into account latest refactoring.

@mmilad75, could you please take a look?

**Comment by VolodLytvynenko** [comment]
Hi @vkjr, thank you for the fixes. The route fetching on the confirm page is now working correctly. The red highlight issue has also been resolved and not reproduced on real devices. However, it is still shown in Android Studio. Is this an Android Studio limitation and such issue is related only to Android Studio, or could the issue still exist on some devices?

image

[logs.txt](https://github.com/status-im/status-mobile/files/15107271/logs.txt)

### Devices:
Android Studio Pixel XL API 33

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 1: The part of a tab is shown on 'send to' page

### Steps:
1. Go to 'Send to' screen

### Actual result:
image

### Expected result:
last nighly
image

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by vkjr** [comment]
@VolodLytvynenko, don't know regarding Android Studio, let me check the code to get some guesses)
Missing tab is also a surprise, so far can't reproduce it locally.

**Comment by VolodLytvynenko** [comment]
@vkjr thank you for the PR. I don't see any issues from my side. Ready to be merged

Hi @mmilad75, it seems like the issue that was supposed to be fixed in https://github.com/status-im/status-mobile/pull/19711 is already resolved in the current PR

**Comment by vkjr** [comment]
@VolodLytvynenko , thank you!
