### PR TITLE
[#20179] collectibles page fixes

### LINKED ISSUE #20179: Wallet -Improve lmage loading on Collectibles Overview Page
Currently the collectibles loading transition is not so smooth.
Implement some improvement to this screen.

Also the "Can't fetch" variants are not displaying correctly at all and we need to display the correct variant when this happens.

The solution can be implemented similar to the collectible list item component which handles a similar usage to both of these.

**Can't fetch not correct**

https://github.com/status-im/status-mobile/assets/22799766/a510d9a0-fa96-4814-aadb-437c73d8a7be

**Current loading on overview page**

https://github.com/status-im/status-mobile/assets/22799766/3b809863-ac47-48c7-864d-0fc8a1bc55ee

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20179

along with other improvements

#### Adds the new background color expected for collectibles with transparency:
  
  Before vs Now:
  [Figma Link](https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=13212-177685&t=03vTGa5YTuFaQ2Oh-4) (we still have issues with the shadow and the blur)
  
   

#### Fix the header color while scrolling (looked dark for a moment) and the text animation in unsupported colletibles

Before (it was dark for a while and the text appears immediately):

[Screencast from 2024-05-30 14-36-58.webm](https://github.com/status-im/status-mobile/assets/90291778/861713ce-05a3-411a-bff4-c38039e1d085)

Now (the text appears once the title is covered by the header):

[Screencast from 2024-05-30 14-30-31.webm](https://github.com/status-im/status-mobile/assets/90291778/023c0b8d-6366-466a-8e79-ad5b7d59ad35)

(Sorry for the laggy videos)

#### The collectible page nav component was misaligned on Android:

[Screencast from 2024-05-30 15-35-55.webm](https://github.com/status-im/status-mobile/assets/90291778/5b0bbf76-d4f9-43ad-8e1e-12544c00ee43)

## Review and testing notes

**IMPORTANT**
In develop, the PR merged:
- #19943

Has the side effect of misaligning the collectibles header, since it modifies the page-top component.

While testing, the header will look centered instead of aligned to the left:
image

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/quo/components/profile/expanded_collectible/style.cljs [hunk 1]
```diff
@@ -7,10 +7,11 @@
...
 (defn image
-  [square? aspect-ratio]
-  {:width         "100%"
-   :aspect-ratio  (if square? 1 aspect-ratio)
-   :border-radius 16})
+  [square? aspect-ratio theme]
+  {:width            "100%"
+   :aspect-ratio     (if square? 1 aspect-ratio)
+   :border-radius    16
+   :background-color (colors/theme-colors colors/white colors/neutral-95 theme)})
```
Comment (ulisesmac) [inline src/quo/components/profile/expanded_collectible/style.cljs:14]: Just adding the background color for collectibles

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 2]
```diff
@@ -53,20 +53,22 @@
...
 
        image-error?
        [fallback-view
-        {:label   (i18n/label :t/cant-fetch-info)
-         :counter counter
-         :theme   theme}]
+        {:label    (i18n/label :t/cant-fetch-info)
+         :counter  counter
+         :theme    theme
+         :on-mount on-collectible-load}]
```
Comment (ulisesmac) [inline src/quo/components/profile/expanded_collectible/view.cljs:65]: When the collectible is unsupported or has an error, we don't use `rn/image` so the `on-collectible-load` callback responsible of meassuring the dimensions taken by the collectible is not called.

Now we call it `on-mount` of the fallback view.

cc: @ajayesivan

File: src/status_im/contexts/wallet/account/view.cljs [hunk 3]
```diff
@@ -19,7 +19,7 @@
            {:id :collectibles :label (i18n/label :t/collectibles) :accessibility-label :collectibles-tab}
            {:id :activity :label (i18n/label :t/activity) :accessibility-label :activity-tab}]
     (not watch-only?) (conj {:id :dapps :label (i18n/label :t/dapps) :accessibility-label :dapps})
-    true              (conj {:id :about :label (i18n/label :t/about) :accessibility-label :about})))
+    :always           (conj {:id :about :label (i18n/label :t/about) :accessibility-label :about})))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/account/view.cljs:21]: This is part of a `cond->` although it behaves the same, the Clojure convention is to use the keyword `:always`

File: src/status_im/contexts/wallet/account/view.cljs [hunk 4]
```diff
@@ -28,7 +28,6 @@
       (let [{:keys [name color formatted-balance
                     watch-only?]} (rf/sub [:wallet/current-viewing-account])
             customization-color   (rf/sub [:profile/customization-color])]
-        (rn/use-unmount #(rf/dispatch [:wallet/close-account-page]))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/account/view.cljs]: Removed, this change makes really difficult to develop, each time the hot reload is triggered in this namespace, the app navigates to the root of the app.

CC: @OmarBasem

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 5]
```diff
@@ -79,9 +79,9 @@
   (let [blur-amount   (header-animations/use-blur-amount scroll-amount)
         layer-opacity (header-animations/use-layer-opacity
                        scroll-amount
-                       "transparent"
+                       (colors/theme-colors colors/white-opa-0 colors/neutral-95-opa-0 theme)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/view.cljs:86]: When we animate from `transparent` to white, the animation goes through black, so now the starting color is the ending color with opacity zero.

cc: @ajayesivan

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 6]
```diff
@@ -110,8 +110,10 @@
 
 (defn on-scroll
   [e scroll-amount title-opacity title-bottom-coord]
+
   (let [scroll-y    (oops/oget e "nativeEvent.contentOffset.y")
         new-opacity (if (>= scroll-y @title-bottom-coord) 1 0)]
+    (println @title-bottom-coord scroll-y)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/view.cljs]: Leftover, I'll remove them :eyes:

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 7]
```diff
@@ -223,7 +225,8 @@
         set-title-bottom           (rn/use-callback
                                     (fn [_ y _ height]
                                       (reset! title-bottom-coord
-                                        (+ y height -100 (if platform/ios? (- top) top)))))
+                                              (+ y height -56 (when platform/ios?
+                                                                (* top -2))))))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/collectible/view.cljs]: Fix the header text animation calculations

File: src/quo/components/profile/expanded_collectible/style.cljs (hunk 1 above)
Comment (ajayesivan) [reply src/quo/components/profile/expanded_collectible/style.cljs:14]: [Figma design](https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=13212-177720&m=dev) also has a border

File: src/quo/components/profile/expanded_collectible/view.cljs (hunk 2 above)
Comment (ajayesivan) [reply src/quo/components/profile/expanded_collectible/view.cljs:65]: Make sense 👍

**Review by ajayesivan — APPROVED** [review]
Other than the missing border, everything looks good to me.

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 8]
```diff
@@ -223,7 +225,11 @@
         set-title-bottom           (rn/use-callback
                                     (fn [_ y _ height]
                                       (reset! title-bottom-coord
-                                        (+ y height -100 (if platform/ios? (- top) top)))))
+                                        (+ y
+                                           height
+                                           -56
+                                           (when platform/ios?
+                                             (* top -2))))))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/collectible/view.cljs:237]: - magic numbers: -56, -2

- What is the difference between y and height?

- Why do we have this condition for ios: `(when platform/ios? (* top -2))`

Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/view.cljs:237]: > magic numbers: -56, -2

-56 should be a magic number, it is the given height for the header.

> What is the difference between y and height?

Please check the API: https://reactnative.dev/docs/direct-manipulation#measurecallback

> Why do we have this condition for ios: (when platform/ios? (* top -2))

On iOS the content of the scroll view is rendered out of the safe area, so we add a `:margin -top` to the container, Since we added that negative margin, the scroll amount starts at `-top` instead of `0`, so we need to substract another `-top` to properly report the scroll amount.

It may be easier to grasp if you run the branch and check the printed logs (printed by the leftovers I previously mentioned).

File: src/quo/components/profile/expanded_collectible/style.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/quo/components/profile/expanded_collectible/style.cljs:14]: Thank you @ajayesivan !

Actually it was a missing style in the component (`expanded-collectible`) not only for the transparent images, so I added it :+1:

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 8 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/collectible/view.cljs:237]: > -56 should be a magic number, it is the given height for the header.

You can define it as `(def header-height 56)`, it wasn't clear to me that it is the header height

> Please check the API: https://reactnative.dev/docs/direct-manipulation#measurecallback

I understand the styling difference :) I meant make it more clear what `y` and `height` are referring to? Y of what and height of what?

> the scroll amount starts at -top instead of 0, so we need to substract another -top to properly report the scroll amount.

👍

File: src/quo/components/profile/expanded_collectible/view.cljs [hunk 9]
```diff
@@ -21,9 +20,9 @@
       :value           counter}]))
 
 (defn- fallback-view
-  [{:keys [label theme counter]}]
-  [rn/view
-   {:style (style/fallback {:theme theme})}
+  [{:keys [label theme counter on-mount]}]
```
Comment (J-Son89) [inline src/quo/components/profile/expanded_collectible/view.cljs:22]: rather than `on-mount` how about calling it something more expressive? 
We know the behaviour is `on-mount` anyway because of the hook name.
e.g `on-collectible-load` is more descriptive
`(rn/use-mount on-collectible-load)`

File: src/status_im/contexts/wallet/collectible/style.cljs [hunk 10]
```diff
@@ -80,4 +85,5 @@
 (defn background-color
   [theme]
   {:flex             1
+   :height           1500
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/collectible/style.cljs]: why do we need this number? 🤔

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 11]
```diff
@@ -233,9 +240,6 @@
         {preview-uri :uri}         preview-url
         {collectible-name :name}   collectible-data
         {collection-name :name}    collection-data]
-
-    (rn/use-unmount #(rf/dispatch [:wallet/clear-last-collectible-details]))
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/collectible/view.cljs:237]: why do you get rid of this? - also unsure why it was needed initially? 🤔

**Review by J-Son89 — APPROVED** [review]

**Review by BalogunofAfrica — APPROVED** [review]

File: src/status_im/contexts/wallet/collectible/style.cljs (hunk 10 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/collectible/style.cljs]: Oh, this is a leftover  :no_mouth:

File: src/quo/components/profile/expanded_collectible/view.cljs (hunk 9 above)
Comment (ulisesmac) [reply src/quo/components/profile/expanded_collectible/view.cljs:22]: It's a placeholder and I'd like to execute some code `on-mount` :thinking:  so I think it's a good name.

It's being called as:
```clojure
{:on-mount on-collectible-load
 ,,,}
```

Do you prefer it'd be:
```clojure
{:on-collectible-load on-collectible-load
 ,,,}
```
even though this is a placeholder without a collectible? :thinking:

**Comment by VolodLytvynenko** [comment]
Unassigned this PR from myself. Need to switch to a priority PR.

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac could you please resolve existing conflicts? Thanx

**Comment by ulisesmac** [comment]
> hi @ulisesmac could you please resolve existing conflicts? Thanx

@VolodLytvynenko Solved! :)

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac thank you for PR. Take a look at the found issues:

## PR_ISSUE 1: [IOS] Collectible images are blurred in the detailed view

### Steps:
1. Restore user with available collectibles or add a watch-only account with already available collectibles (in my case: `0xeD620C9dC11401b63B35Dfe8e93F2b11DB0F6F9e` on testnet) 
2. Go to the collectibles tab
3. Open a collectible where the image is present

### Actual result:
The image of the collectible is blurred

https://github.com/status-im/status-mobile/assets/52490791/0eee4887-fa06-48ae-b18c-880f886472b4



### Expected result:
The image of the collectible is clear.

### Devices:
- iPhone 11 Pro Max, IOS 17

### Logs
[logs.zip](https://github.com/user-attachments/files/15837521/logs.zip)

**Comment by ulisesmac** [comment]
> Hi @ulisesmac thank you for PR. Take a look at the found issues:
> ## PR_ISSUE 1: [IOS] Collectible images are blurred in the detailed view
> ### Steps:
> 
>     1. Restore user with available collectibles or add a watch-only account with already available collectibles (in my case: `0xeD620C9dC11401b63B35Dfe8e93F2b11DB0F6F9e` on testnet)
> 
>     2. Go to the collectibles tab
> 
>     3. Open a collectible where the image is present
> 
> 
> ### Actual result:
> 
> The image of the collectible is blurred
> collectibles_image.mp4
> ### Expected result:
> 
> The image of the collectible is clear.
> ### Devices:
> 
>     * iPhone 11 Pro Max, IOS 17
> 
> 
> ### Logs
> 
> [logs.zip](https://github.com/user-attachments/files/15837521/logs.zip)

Hey @VolodLytvynenko 
These collectibles are also non supported on develop. This PR is not addressing this type of unsupported collectibles.
We can look into it in a different issue, wdyt?

Just to clarify: this is due to the expanded-collectible component, and this PR is not adding support for different types to it.

**Comment by VolodLytvynenko** [comment]
> Hey @VolodLytvynenko These collectibles are also non supported on develop. This PR is not addressing this type of unsupported collectibles. We can look into it in a different issue, wdyt?
> 
> Just to clarify: this is due to the expanded-collectible component, and this PR is not adding support for different types to it.

hi @ulisesmac Apologies. In the issue https://github.com/status-im/status-mobile/pull/20281#issuecomment-2167850879, I provided the wrong record. I have now updated it. Could you please check again? It seems the updated one is related to the current PR.

**Comment by ulisesmac** [comment]
> > Hey @VolodLytvynenko These collectibles are also non supported on develop. This PR is not addressing this type of unsupported collectibles. We can look into it in a different issue, wdyt?
> > Just to clarify: this is due to the expanded-collectible component, and this PR is not adding support for different types to it.
> 
> hi @ulisesmac Apologies. In the issue [#20281 (comment)](https://github.com/status-im/status-mobile/pull/20281#issuecomment-2167850879), I provided the wrong record. I have now updated it. Could you please check again? It seems the updated one is related to the current PR.

Thanks for spotting this issue @VolodLytvynenko, now it has been solved.

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac Thank you for the PR. No issues related to the current PR from my side. I just want to highlight an issue that's also present in the develop branch. Could you take a look and decide if it's better to fix it separately or in the current PR? If it's better to fix it separately, then the PR can be merged.

## ISSUE 2: [IOS] Header сut off when viewing collectibles after swiping down

### Steps:
1. Open collectible
2. Swipe down

### Actual result:
The header is cut causing the empty place is shown 

https://github.com/status-im/status-mobile/assets/52490791/e2bc03e0-f65c-4e32-a5de-79e50d298e85

image

### Expected result:
The header is not cut off

**Comment by ulisesmac** [comment]
> hi @ulisesmac Thank you for the PR. No issues related to the current PR from my side. I just want to highlight an issue that's also present in the develop branch. Could you take a look and decide if it's better to fix it separately or in the current PR? If it's better to fix it separately, then the PR can be merged.
> ## ISSUE 2: [IOS] Header сut off when viewing collectibles if after swiping down
> ### Steps:
> 
>     1. Open collectible
> 
>     2. Swipe down
> 
> 
> ### Actual result:
> 
> The header is cut causing the empty place is shown
> collectible_header.mp4
> 
> image
> ### Expected result:
> 
> The header is not cut off

Hi @VolodLytvynenko 

When this header was implemented and shown to designers in Montenegro, they accepted this implementation, it looks cut because we cannot extend the background image indefinitely, so, we need to get design input before fixing it/opening an issue.

CC: @ajayesivan
