### PR TITLE
On password creation screen make the password disclaimer tappable

### LINKED ISSUE #15662: The 'I understand that my password cannot be recovered' consent checkbox clickable area is too small
# Bug Report
When a user tries to click on the accept consent button, The clickable area is too small.
Causing the user to click multiple times till he get it right

#### Expected behavior
The clickable should be increased or the it should be set as clicked if the user clicks on the whole rectangle

#### Actual behavior
Clickable area is too small

### Reproduction

1) Open Status
2) Generate new keys
3) Type and confirm a password
4) Try to accept consent
image

### PR DESCRIPTION
**Pull request by siddarthkay**
This PR solves a tiny UX issue on password creation screens.
Currently the password disclaimer is a tiny checkbox which has a very small tappable area : 

Screenshot_20230426-163632

This PR makes the entire row tappable so that its easier for the users to just tap the disclaimer and move forward.

https://user-images.githubusercontent.com/64726664/234567647-fb381494-4d45-47c2-ba33-079ca8f8b6fe.mov

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
Onboarding

fixes : https://github.com/status-im/status-mobile/issues/15662

status: ready

### CODE REVIEW

File: src/status_im2/contexts/onboarding/create_password/view.cljs [hunk 1]
```diff
@@ -164,11 +164,12 @@
...
           [rn/view {:style style/disclaimer-container}
-           [quo/disclaimer
-            {:blur?     true
-             :on-change #(reset! accepts-disclaimer? %)
-             :checked?  @accepts-disclaimer?}
-            (i18n/label :t/password-creation-disclaimer)]]
+           [rn/touchable-opacity {:on-press #(swap! accepts-disclaimer? not)}
+            [quo/disclaimer
+             {:blur?     true
+              :on-change #(reset! accepts-disclaimer? %)
```
Comment (cammellos) [inline src/status_im2/contexts/onboarding/create_password/view.cljs]: Is this needed now?

Comment (siddarthkay) [reply src/status_im2/contexts/onboarding/create_password/view.cljs]: yes, otherwise tap on the checkbox doesn't work 😅

Comment (siddarthkay) [reply src/status_im2/contexts/onboarding/create_password/view.cljs]: I mean an exact tap on the checkbox square area won't do anything, otherwise clicking on the row will work

Comment (siddarthkay) [reply src/status_im2/contexts/onboarding/create_password/view.cljs]: I was thinking of modifying the `[quo/disclaimer` component to incorporate this behaviour, but I am not sure of its impact on other places.

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/create_password/view.cljs]: it's probably better to just update at quo component because I'm sure it is a common issue across other screens where it's used

Comment (siddarthkay) [reply src/status_im2/contexts/onboarding/create_password/view.cljs]: @J-Son89  : addressed here https://github.com/status-im/status-mobile/pull/15757/commits/b7cca93a85c48b38994901dc80509f4d322d7e26

**Comment by siddarthkay** [comment]
Oh i broke component test 😅

```log
[2023-04-28T02:50:12.500Z] FAIL component-spec/quo2.components.selectors.disclaimer.component_spec.js
[2023-04-28T02:50:12.500Z]   ● Disclaimer tests › On change event gets fire after press
[2023-04-28T02:50:12.500Z] 
[2023-04-28T02:50:12.500Z]     expect(jest.fn()).toHaveBeenCalled()
[2023-04-28T02:50:12.500Z] 
[2023-04-28T02:50:12.500Z]     Expected number of calls: >= 1
[2023-04-28T02:50:12.500Z]     Received number of calls:    0
[2023-04-28T02:50:12.500Z] 
[2023-04-28T02:50:12.500Z]       at mock-fn (test_helpers/component.cljs:192:33)
[2023-04-28T02:50:12.500Z]       at Object.<anonymous> (quo2/components/selectors/disclaimer/
component_spec.cljs:19:21)
[2023-04-28T02:50:12.500Z] 
[2023-04-28T02:50:12.500Z]   ● Disclaimer tests › It's rendered according to its `checked?` 
property › checked? true
[2023-04-28T02:50:12.500Z] 
[2023-04-28T02:50:12.500Z]     expect(received).toBeNull()
[2023-04-28T02:50:12.500Z] 
[2023-04-28T02:50:12.500Z]     Received: {"_fiber": {"_debugHookTypes": null, "_debugID": 112,
 "_debugNeedsRemount": false, "_debugOwner": [FiberNode], "_debugSource": null, 
 "actualDuration": 0, "actualStartTime": -1, "alternate": null, "child": [FiberNode], "childLanes": 0, 
 "dependencies": null, "elementType": "View", "firstEffect": null, "flags": 0, "index": 0, "key": null, 
 "lanes": 0, "lastEffect": null, "memoizedProps": [Object], "memoizedState": null, "mode": 0, 
 "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, 
 "sibling": null, "stateNode": [Object], "tag": 5, "treeBaseDuration": 0, "type": "View", 
 "updateQueue": null}}
[2023-04-28T02:50:12.500Z] 
[2023-04-28T02:50:12.501Z]       at test-helpers.component/query-by-label-text 
(test_helpers/component.cljs:188:25)
[2023-04-28T02:50:12.501Z]       at Object.<anonymous> (quo2/components/selectors/disclaimer/
component_spec.cljs:24:19)
```

**Comment by ajayesivan** [comment]
@siddarthkay Related issue: https://github.com/status-im/status-mobile/issues/15662

**Comment by J-Son89** [comment]
> @siddarthkay Related issue: https://github.com/status-im/status-mobile/issues/15662

@siddarthkay Can you update the description with the related issue?

**Review by J-Son89 — APPROVED** [review]

**Comment by pavloburykh** [comment]
@siddarthkay thanx for the PR. Please take a look at the following issue

### ISSUE 1 Confirm password button remains inactive after checking password disclaimer

**Steps:** 

1. Proceed to password creation screen
2. Enter valid password
3. Check the disclaimer
4. See if confirm password button is active

**Actual result:** Confirm password button remains inactive after checking password disclaimer. Unable to proceed with creation of multiaccount


https://user-images.githubusercontent.com/97245802/235448585-1219c677-de58-47a8-bf31-0e0575abf49a.mp4

**Expected result:** Confirm password button is active. User is able to proceed to the next step.

**Comment by siddarthkay** [comment]
@pavloburykh : Thanks for testing and finding the grave issue.
 Issue 1 is now fixed!

**Comment by pavloburykh** [comment]
@siddarthkay thanx for the fix. Ready to be merged. Failed e2e are not PR related.
