### PR TITLE
[#12681] Enable UI for signing legacy txs on networks without eip1559

### LINKED ISSUE #12681: Network fee is not calculated at attempt to send tx from BNB custom chain
# Bug Report

## Problem 
From user report:
```
Status do not support costume chain for loading gas fee now.
1.Get in Dapps on any binance smart chain
2. it cannot do anything because loop loading gas fee.
Load gas fee and do transaction normally
```
Network fee is not calculated at attemt to send tx now, but it was calculated in release 1.15 (before EIP-1559)

#### Expected behavior
Can see that Gas Limit and Gas price is calculated
IMAGE 2021-10-04 20:38:38

#### Actual behavior
IMAGE 2021-10-04 20:42:20

### Reproduction

1) Open Status
2) Go to profile > Advanced > Network
3) Add custom network with params:
RPC URL: https://bsc-dataseed.binance.org/
Chain ID: 56
4) Connect to network
5) Try to send any tx

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)
[status_logs.zip](https://github.com/status-im/status-react/files/7280529/status_logs.zip)
```
WARN [status-im.ethereum.json-rpc:253] - :json-rpc/error eth_feeHistory :error {:code -32601, :message "the method eth_feeHistory does not exist/is not available"} :params [101 "latest" nil]
```

### PR DESCRIPTION
**Pull request by rasom**
fix #12681

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/signing/views.cljs [hunk 1]
```diff
@@ -384,15 +385,10 @@
...
-           [:signing.ui/open-fee-sheet
-            {:content        (fn []
-                               (if (eip1559/sync-enabled?)
-                                 [sheets/fee-bottom-sheet-eip1559 fee-display-symbol]
-                                 [sheets/fee-bottom-sheet fee-display-symbol]))
-             :content-height 270}])}])))
+                                        (if (eip1559/enabled?)
+                                          [sheets/fee-bottom-sheet-eip1559 fee-display-symbol]
+                                          [sheets/fee-bottom-sheet fee-display-symbol]))
+                      :content-height 270}])}])))
```
Comment (flexsurfer) [inline src/status_im/ui/screens/signing/views.cljs]: content-height is redundant

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/signing/views.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/ui/screens/signing/views.cljs]: fixed, thanks

**Comment by churik** [comment]
Can sign TX on BNB network now
