### PR TITLE
Fix for tapping on new contact from contact list

### LINKED ISSUE #14632: Tapping on new contact from Contact list leads to empty chat with skeleton
# Bug Report

## Problem 
Case with a single tap on contact from the contact list is not covered in design (https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1786%3A389868&t=o5uE8NtUSKDNyEN3-4)

Currently, if there is 1-1 chat with a contact, the user will be redirected there, otherwise, empty chat with the endless skeleton is shown

#### Expected behavior

**Possible solutions:**
- do not do anything on single tap
- open the user profile (which is not ready yet, so should be a placeholder)
- open 1-1 chat (as when the user is added to the contact list it should be already possible)

#### Actual behavior

https://user-images.githubusercontent.com/4557972/209356555-a2355f38-7600-4583-915e-b5465dff64ed.mp4

### Reproduction

1) Open Status
2) Send smbd contact request
3) Tap on it from Messages > Contacts 

### Additional Information

- Status version: nightly 23/12/22
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
fixes https://github.com/status-im/status-mobile/issues/14632

### Summary

Shows a profile when tapping on contact;
also updates the code to actually show the action sheet on long press (as it's done in designs)

#### Platforms

- Android
- iOS
- 
status: ready

### CODE REVIEW

**Comment by VladimrLitvinenko** [comment]
Hi @alwx. thank you for your contribution. Noticed that the current PR is marked as 'request manual qa', but I see some integration tests are failed. Could you check it, please?

File: src/status_im2/common/contact_list_item/view.cljs [hunk 1]
```diff
@@ -14,9 +14,7 @@
   (let [view-id (rf/sub [:view-id])]
     (when (= view-id :shell-stack)
       (rf/dispatch [:dismiss-keyboard])
-      (if platform/android?
-        (rf/dispatch [:chat.ui/navigate-to-chat-nav2 chat-id])
-        (rf/dispatch [:chat.ui/navigate-to-chat chat-id]))
+      (rf/dispatch [:chat.ui/show-profile chat-id])
```
Comment (flexsurfer) [inline src/status_im2/common/contact_list_item/view.cljs:16]: is it intentional?

Comment (alwx) [reply src/status_im2/common/contact_list_item/view.cljs:16]: yes, that's one of the things that's proposed in the issue description — to open a profile instead of opening a chat (because there might be a situation when there is no chat yet)

**Review by flexsurfer — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Comment by flexsurfer** [comment]
@alwx please do not merge if there is `qa` label
