### PR TITLE
Toast notification design fixes

### LINKED ISSUE #17540: feedback for toast notification in 1:1 chat
# Bug Report

- [ ] Wrong color and icon for error state (https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#570468876)
- [ ] Icon is not aligned with toast text (https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#567127862)
- [ ] Wrong position of toast banner (https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:43270&mode=design#567142410)

Design review here: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#570508962

### PR DESCRIPTION
**Pull request by alwx**
fixes https://github.com/status-im/status-mobile/issues/17540

#### Platforms

- Android
- iOS

##### Functional

- toasts

status: ready

### CODE REVIEW

File: src/quo/components/notifications/toast/view.cljs [hunk 1]
```diff
@@ -77,16 +76,19 @@
...
   (let [context-theme (or theme (quo.theme/get-theme))
         icon-name     (case type
-                        :positive :i/correct
-                        :negative :i/incorrect
+                        :positive (if (= theme :light)
+                                    :i/correct
+                                    :i/correct-dark)
+                        :negative (if (= theme :light)
+                                    :i/incorrect
+                                    :i/incorrect-dark)
```
Comment (smohamedjavid) [inline src/quo/components/notifications/toast/view.cljs:84]: @alwx - The best way to handle colors in icons is using SVG.

https://github.com/status-im/status-mobile/blob/ec2b95c3709d2f5c73b2000689777aaa2bb73421/src/quo/components/icons/svg.cljs#L1

This will help us reduce the clutter of images/icons needed for each theme.

**Review by smohamedjavid — COMMENTED** [review]
Nice work!

File: src/quo/components/notifications/toast/style.cljs [hunk 2]
```diff
@@ -21,13 +21,13 @@
...
-   :padding-left     10
-   :padding-right    8
-   :border-radius    12})
+  {:background-color   (colors/theme-colors colors/neutral-80-opa-70 colors/white-opa-70 theme)
+   :flex-direction     :row
+   :align-items        :center
+   :justify-content    :space-between
+   :padding-vertical   8
+   :padding-horizontal 8
+   :border-radius      12})
```
Comment (yqrashawn) [inline src/quo/components/notifications/toast/style.cljs]: This happens before.
I guess what the designer wants is align when text is shorter than the image and do not align when text is taller than the image.

Comment (yqrashawn) [reply src/quo/components/notifications/toast/style.cljs]: this breaks multiline alignment

CleanShot 2024-01-12 at 09 44 05
CleanShot 2024-01-12 at 09 47 47@2x

File: src/quo/components/notifications/toast/view.cljs (hunk 1 above)
Comment (alwx) [reply src/quo/components/notifications/toast/view.cljs:84]: Honestly, in the current form it just creates clutter somewhere else — namely in the namespace called `quo.components.icons.svg`. In addition, those icons are very hard to be replaced because instead of putting them in resources we're now writing Clojure code for them. 
I would say I'm gonna skip it for now because it feels wrong to replace an imperfect solution with something that's also imperfect and ugly.

Comment (alwx) [reply src/quo/components/notifications/toast/view.cljs:84]: Also the discussion is here: https://discord.com/channels/1103692771585433630/1103692773363810317/1195414255038648360

**Review by smohamedjavid — APPROVED** [review]

**Review by yqrashawn — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @alwx ! Thanks for your PR!

Help me to clarify the point with platforms here:

> Platforms
Android
iOS
macOS
Linux
Windows

Is it a copypaste from the form or your PR really needs to be tested on every of them?
Thanks!

**Comment by alwx** [comment]
@mariia-skrypnyk sorry, no, fixed the description

**Comment by alwx** [comment]
Any news regarding testing this one?

**Comment by mariia-skrypnyk** [comment]
> Any news regarding testing this one?

Hi @alwx !

Thanks for updating description. I am starting to test ( I was on holidays 2 days and had no ability to start earlier).

**Comment by mariia-skrypnyk** [comment]
@alwx Hi! I've looked at your fixes, looks good! Just have a question regarding this:

- [ ] Wrong position of toast banner (https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:43270&mode=design#567142410)

I see such position on Android/iOS
Screenshot 2024-01-22 at 13 01 46

Not sure if you have any additional instractions or requirements regarding the banner position but as we can see [here ](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:43270&mode=design#567142410) I suppose the banner position should overlap cross button and profile picture and name.

Screenshot 2024-01-22 at 13 03 13



Let me know what do you know/thing regarding it. Thanks.

**Comment by alwx** [comment]
@mariia-skrypnyk yes, you're right — the banner shouldn't overlap, I will check it again today.

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk yes, you're right — the banner shouldn't overlap, I will check it again today.

Hi @alwx !
Maybe we have some misunderstanding:)
Let me try to explain my thoughts:
[Here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6142-39869&mode=design&t=jkKwmxMnu3Hx1mMT-0#567142410) we have a comment regarding wrong position. 
If the right position is described on my point 2 on the screenshot below then banner **should** overlap as we can see here: banner makes cross and profile picture invisible 
Screenshot 2024-01-23 at 12 10 59

**Comment by alwx** [comment]
@mariia-skrypnyk how can I actually see this banner? I see it being shown only in combination with the popup to select images like on the video below (and there the position is correct) but not without it.

https://github.com/status-im/status-mobile/assets/911127/d678989a-37b5-4da3-a749-c59833226fc3

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk how can I actually see this banner? I see it being shown only in combination with the popup to select images like on the video below (and there the position is correct) but not without it.
> 
>  Screen.Recording.2024-01-24.at.13.03.02.mov

Hi!

Yes, tricky moment) you do all the same but without one extra action that I did do get such screen: to close the gallery while the banner appears. I did it as I wanted to reproduce the case from the design review.

If you do have requirements where this banner should be placed in this case - let me know!

https://github.com/status-im/status-mobile/assets/147824399/b66ae9fa-65c9-445d-a505-0994840136e1

**Comment by alwx** [comment]
@mariia-skrypnyk Yes but it would be super weird to relocate the banner in this case because it appeared already and appeared on a particular location. I'd say it's the intended behaviour, maybe @Francesca-G can say for sure if it's fine?

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk Yes but it would be super weird to relocate the banner in this case because it appeared already and appeared on a particular location. I'd say it's the intended behaviour, maybe @Francesca-G can say for sure if it's fine?

All I wanted is to reproduce this situation from the review:
Screenshot 2024-01-25 at 14 55 03
That's why I start asking how it should be:)
Asking designers is a good idea.

**Comment by mariia-skrypnyk** [comment]
@alwx please, can you check if Icon is aligned in the centre to the text on Android?
It looks like it not:
Screenshot 2024-01-25 at 14 59 31

**Comment by Francesca-G** [comment]
> @mariia-skrypnyk Yes but it would be super weird to relocate the banner in this case because it appeared already and appeared on a particular location. I'd say it's the intended behaviour, maybe @Francesca-G can say for sure if it's fine?

Asked the rest of the team and this is fine, the photo drawer toast is an exception and if the user happens to close the drawer by dragging it like in the video, the toast will disappear right after that so it's not a problem :)

Besides that, the placement isn't correct as you can see here, the top margin doesn't match design:

image


Pedro also spotted a couple of animation issues about the photo drawer (to be addressed in a separate PR)
"As the drawer comes up I'm not sure anything should be animating underneath. It doesn't make sense that things are animating when the drawer for photo selection is coming up or going down", referring to top bar and scroll animation

**Comment by mariia-skrypnyk** [comment]
Hi @alwx !

Will you be able to implement the changes according to design comment below?
Thanks!

> > @mariia-skrypnyk Yes but it would be super weird to relocate the banner in this case because it appeared already and appeared on a particular location. I'd say it's the intended behaviour, maybe @Francesca-G can say for sure if it's fine?
> 
> Asked the rest of the team and this is fine, the photo drawer toast is an exception and if the user happens to close the drawer by dragging it like in the video, the toast will disappear right after that so it's not a problem :)
> 
> Besides that, the placement isn't correct as you can see here, the top margin doesn't match design:
> 
> image
> 
> Pedro also spotted a couple of animation issues about the photo drawer (to be addressed in a separate PR) "As the drawer comes up I'm not sure anything should be animating underneath. It doesn't make sense that things are animating when the drawer for photo selection is coming up or going down", referring to top bar and scroll animation

**Comment by mariia-skrypnyk** [comment]
Hi @alwx !

Let me know when I can start testing!

**Comment by alwx** [comment]
@mariia-skrypnyk it's ready to be re-tested!

**Comment by mariia-skrypnyk** [comment]
Hi @alwx !
Thanks for your update!

No iOS looks great as for me:
Screenshot 2024-01-31 at 11 02 28
Screenshot 2024-01-31 at 11 03 25

But I do have question regarding Android: should it look the same there too? @Francesca-G help us please.
Now we have this banner placement for Android:
Screenshot 2024-01-31 at 11 03 07
Screenshot 2024-01-31 at 11 02 45

**Comment by alwx** [comment]
@mariia-skrypnyk that's probably incorrect but the problem is on Android it really might depend on a phone. I tested it on emulator + on Pixel 7a, the position was right but I will check again what can be done to make it look good on all the devices.

**Comment by Francesca-G** [comment]
> But I do have question regarding Android: should it look the same there too? @Francesca-G help us please. Now we have this banner placement for Android: Screenshot 2024-01-31 at 11 03 07 Screenshot 2024-01-31 at 11 02 45

Same behavior should be applied on Android :)
We have the same issue as iOS, the top margin doesn't match design as you can see:

Screenshot 2024-01-31 alle 17 18 30

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk that's probably incorrect but the problem is on Android it really might depend on a phone. I tested it on emulator + on Pixel 7a, the position was right but I will check again what can be done to make it look good on all the devices.


Thanks @alwx !

**Comment by alwx** [comment]
@mariia-skrypnyk sorry for the delay. Could you please check it again?

**Comment by mariia-skrypnyk** [comment]
Hi @alwx !
 
These places on Android look great as for me.
Screenshot 2024-02-06 at 12 36 02
Screenshot 2024-02-06 at 12 36 24

But I am not sure this one is ok:
Screenshot 2024-02-06 at 12 36 43


@Francesca-G  please, make a review of this one and let us know!

**Comment by Francesca-G** [comment]
> These places on Android look great as for me. 
Screenshot 2024-02-06 at 12 36 02 

Placement looks good here ⬆️

Screenshot 2024-02-06 at 12 36 24

Placement isn't correct in this case ⬆️ 
The toast should cover the top nav buttons and not touch the avatar as per design:

Screenshot 2024-02-06 alle 14 05 46


> But I am not sure this one is ok: 
Screenshot 2024-02-06 at 12 36 43



⬆️ Technically this isn't the correct placement but as mentioned before this only occurs when the photo drawer is open and the toast in that case is an exception. If the user happens to close the drawer by dragging it the toast will disappear right after, so it's not a problem :)

**Comment by alwx** [comment]
@mariia-skrypnyk what would you say? Does it only happen when you close the drawer after you already saw the toast? In this case I also think it's pretty normal because the toast was already placed in the right position.

**Comment by mariia-skrypnyk** [comment]
> 🤖`apk`



> @mariia-skrypnyk what would you say? Does it only happen when you close the drawer after you already saw the toast? In this case I also think it's pretty normal because the toast was already placed in the right position.

Hi @alwx !

As @Francesca-G mentioned we have 2 issues.
First one:

> Placement isn't correct in this case ⬆️
The toast should cover the top nav buttons and not touch the avatar as per design:

Screenshot 2024-02-06 at 12 36 24

Second one:
Screenshot 2024-02-06 at 12 36 43

Yes, user can get this view when he quickly closes the drawer AND also when he taps "Confirm selection" the banner is visible for some time.
Screenshot 2024-02-07 at 13 06 13

I tried to compare contact request vs images selection and we see them placed on the different line at the bottom. 
I suppose it is the needed height for Android....? 
@Francesca-G what do you think? If it is a tinny problem just leave it as it is.
Screenshot 2024-02-07 at 13 08 01

**Comment by alwx** [comment]
@mariia-skrypnyk as far as I understand, it happens ONLY when you close the image selection, so the popup actually appears on image selection screen and then stays for a couple of seconds in this state once you leave the image selection, is that correct/

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk as far as I understand, it happens ONLY when you close the image selection, so the popup actually appears on image selection screen and then stays for a couple of seconds in this state once you leave the image selection, is that correct/

yes!

**Comment by Francesca-G** [comment]
> @mariia-skrypnyk as far as I understand, it happens ONLY when you close the image selection, so the popup actually appears on image selection screen and then stays for a couple of seconds in this state once you leave the image selection, is that correct/

Yes, and we can consider this as expected behavior 👍


About the screenshot posted by @mariia-skrypnyk we still have an unsolved issue:

302975593-0904c6b9-c3f3-43f9-a976-482df0c0c415

>
The toasts should always have the same top margin, they should be aligned no matter how many lines of text they have. 
Design example:

image

**Comment by alwx** [comment]
@mariia-skrypnyk I don't think it's feasible to even call it an issue, to be honest, because it seems to be a rare case.
Our toasts currently don't support changing their positions dynamically after they are already placed — we can change that but it would require quite some work to be done with toasts, and it goes well beyond design work.

In addition, @Francesca-G wrote this:
`⬆️ Technically this isn't the correct placement but as mentioned before this only occurs when the photo drawer is open and the toast in that case is an exception. If the user happens to close the drawer by dragging it the toast will disappear right after, so it's not a problem :)`

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk I don't think it's feasible to even call it an issue, to be honest, because it seems to be a rare case. Our toasts currently don't support changing their positions dynamically after they are already placed — we can change that but it would require quite some work to be done with toasts, and it goes well beyond design work.
> 
> In addition, @Francesca-G wrote this: `⬆️ Technically this isn't the correct placement but as mentioned before this only occurs when the photo drawer is open and the toast in that case is an exception. If the user happens to close the drawer by dragging it the toast will disappear right after, so it's not a problem :)`

I totally agree!

**Comment by mariia-skrypnyk** [comment]
> > @mariia-skrypnyk as far as I understand, it happens ONLY when you close the image selection, so the popup actually appears on image selection screen and then stays for a couple of seconds in this state once you leave the image selection, is that correct/
> 
> Yes, and we can consider this as expected behavior 👍
> 
> About the screenshot posted by @mariia-skrypnyk we still have an unsolved issue:
> 
> 302975593-0904c6b9-c3f3-43f9-a976-482df0c0c415
> > 
> 
> The toasts should always have the same top margin, they should be aligned no matter how many lines of text they have. Design example:
> 
> image

@alwx will you be able to fix this one?

**Review by Francesca-G — APPROVED** [review]
@alwx it looks good like this, thank you for your patience 🙏
