### PR TITLE
Prevent overflowing of chat name and message preview in the Chat List

### LINKED ISSUE #16161: Adjustments on the chats list view in regards to long chat names / long messages previews
# Bug Report

IOS

Device: IOS12 Mini

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #16161

### Summary

This PR attempts to prevent the overflowing of chat name and message preview in the chat list by adding `flex-shrink` to the text component which displays the chat name.

### Platforms

- Android
- iOS

### Areas impacted

- Chat list

#### Prerequisites: Have at least one contact

- Open Status
- Update the nickname of a contact to a lengthy one
- Receive a long message from other contact(s) 
- check if the contact name and message text are overflowing

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

File: src/status_im2/contexts/chat/home/chat_list_item/view.cljs [hunk 1]
```diff
@@ -178,17 +177,31 @@
...
+                                         ;; space of the icon
+                                         (nil? show-verified-or-contact-icon?)
+                                         (+ (if show-unread-badge? 4.5 5.3)))]
+    [rn/view
+     {:style {:flex           1
+              :flex-direction :row}}
+     [quo/text
+      {:weight              :semi-bold
+       :accessibility-label :chat-name-text
+       :style               {:max-width (str name-text-max-width "%")}
```
Comment (OmarBasem) [inline src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: > Q: Why use max-width? why not flex: 1?

@smohamedjavid you can use `:flex-shrink 1` instead of `max-width` to achieve the same effect

Comment (smohamedjavid) [reply src/status_im2/contexts/chat/home/chat_list_item/view.cljs]: Thanks, @OmarBasem!

I haven't thought of `flex-shrink`.  I have updated 👍

**Comment by qoqobolo** [comment]
LGTM, thanks @smohamedjavid!
PR can be merged.
