### PR TITLE
[#19351] fix: animate username in profile

### LINKED ISSUE #19351: Add username animation when scrolling Profile
Currently username and avatar disappearing when scrolling though profile. We should add animation according to the designs. 

**Expected behaviour:**

https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?type=design&node-id=3773%3A221807&mode=design&t=P9vJkTofW1hDDl5l-1

**Actual behaviour:** 

 

https://github.com/status-im/status-mobile/assets/97245802/7e6050fb-3a72-409a-855c-005bb9315c1a

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #19351

### Summary

 animate username according to the designs.

#### Before

https://github.com/status-im/status-mobile/assets/71308738/d5b09606-4bf0-4b66-8e67-0d973012605f

#### After

https://github.com/status-im/status-mobile/assets/71308738/166ab0af-16cd-4f10-80e5-12a019891277

status: ready

### CODE REVIEW

**Comment by ibrkhalil** [comment]
I remember John's description for this in the chat is to start the animation once the big name starts going out of view (Once the big name touches the topbar), And to animate the small name in one go (Without making it rely on scroll progress in parent view)

**Comment by mohsen-ghafouri** [comment]
Thank you @ibrkhalil for pointing it out, I updated the code and video.

File: src/quo/components/navigation/page_nav/view.cljs [hunk 1]
```diff
@@ -85,14 +87,29 @@
...
-    title]])
+  [{:keys [centered? title center-opacity scroll-y]}]
+  (let [translate-animation (when scroll-y
+                              (header-worklet/header-content-position scroll-y
+                                                                      threshold
+                                                                      page-nav-height))
+        opacity-animation   (when scroll-y
+                              (header-worklet/header-content-opacity scroll-y threshold))]
+    [reanimated/view
+     {:style (style/center-content-container-animation {:has-animations?     (not (nil? scroll-y))
```
Comment (ibrkhalil) [inline src/quo/components/navigation/page_nav/view.cljs]: (not (nil? scroll-y))
Can be
(some? scroll-y)

**Review by ibrkhalil — APPROVED** [review]

File: src/utils/worklets/header.cljs [hunk 2]
```diff
@@ -0,0 +1,16 @@
+(ns utils.worklets.header)
+
+(def ^:private worklets (js/require "../src/js/worklets/header.js"))
```
Comment (ulisesmac) [inline src/utils/worklets/header.cljs]: I think we can give a better name to these files than just header, probably profile-header & profileHeader?

File: src/quo/components/navigation/page_nav/view.cljs [hunk 3]
```diff
@@ -85,14 +87,29 @@
...
-     :size            :paragraph-1
-     :number-of-lines 1}
-    title]])
+  [{:keys [centered? title center-opacity scroll-y]}]
+  (let [translate-animation (when scroll-y
+                              (header-worklet/header-content-position scroll-y
+                                                                      threshold
+                                                                      page-nav-height))
+        opacity-animation   (when scroll-y
+                              (header-worklet/header-content-opacity scroll-y threshold))]
```
Comment (ulisesmac) [inline src/quo/components/navigation/page_nav/view.cljs]: these worklets are using a hook inside (`useDerviedValue`) and we are conditionally wrapping them (`when`). This may lead to an exception since we must render the same amount of hooks across re-renders.

So I believe this `scroll-y` always exists otherwise the app is throwing an exception (and it's not doing it), so maybe we can remove them and probably not even mounting the component if there's no `scroll-y`

File: src/js/worklets/header.js [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+      return withTiming(1);
+    }
+  });
+}
+
+export function headerContentPosition(scrollY, threshold, topBarHeight) {
+  return useDerivedValue(function () {
+    'worklet';
+    return scrollY.value < threshold ? withTiming(topBarHeight) : withTiming(0);
+  });
```
Comment (ulisesmac) [inline src/js/worklets/header.js]: If we are writing JS code to generate the animation values, I think is better to directly use `useAnimatedStye` to return the expected styles based on `scrollY`.

I believe is an improvement since we'd get the values in a single function call so we'd avoid the overhead of multiple functions, additionally, all the logic would be in a single place.

File: src/quo/components/navigation/page_nav/view.cljs (hunk 3 above)
Comment (mohsen-ghafouri) [reply src/quo/components/navigation/page_nav/view.cljs]: yes the `scroll-y` either exist from the beginning or not, so it doesn't change during the runtime and doesn't throw any error.

File: src/js/worklets/header.js (hunk 4 above)
Comment (mohsen-ghafouri) [reply src/js/worklets/header.js]: applied, could you please check again @ulisesmac

File: src/js/worklets/profile_header.js [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+  return useAnimatedStyle(() => {
+    const opacity = scrollY.value < threshold ? withTiming(0) : withTiming(1);
+    const translateY = scrollY.value < threshold ? withTiming(topBarHeight) : withTiming(0);
+
+    return {
+      opacity: opacity,
+      transform: [{ translateY: translateY }],
+    };
+  });
+}
```
Comment (seanstrom) [inline src/js/worklets/profile_header.js]: Does this need to be defined in JS because it runs in the animation thread?

**Review by seanstrom — APPROVED** [review]
Nice stuff! 🙌

File: src/js/worklets/profile_header.js (hunk 5 above)
Comment (mohsen-ghafouri) [reply src/js/worklets/profile_header.js]: yes i forgot to add `worklet`, just added

File: src/quo/components/navigation/page_nav/view.cljs [hunk 6]
```diff
@@ -295,6 +307,7 @@
   `:title`
     - title
     - text-align: `:center` or `:left`
+    - scroll-y: a shared value (optional)
```
Comment (ulisesmac) [inline src/quo/components/navigation/page_nav/view.cljs:310]: if we have a malli schema for this component, we also need to update it, otherwise, this change is enough  :+1:

**Review by ulisesmac — APPROVED** [review]
Thank you @mohsen-ghafouri 
All looks good! :100:

File: src/js/worklets/profile_header.js (hunk 5 above)
Comment (ulisesmac) [reply src/js/worklets/profile_header.js]: I believe this looks cleaner @mohsen-ghafouri ! :)

btw,  we don't need that `worklet` directive anymore for the animated hooks, reanimated automatically converts them even if not present, but only when it detects an animated hook is being used.

File: src/quo/components/navigation/page_nav/view.cljs (hunk 6 above)
Comment (mohsen-ghafouri) [reply src/quo/components/navigation/page_nav/view.cljs:310]: no it doesn't, only i can see what defined here

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Please, rebase your PR.

**Comment by mohsen-ghafouri** [comment]
Hi @mariia-skrypnyk, done

**Comment by mariia-skrypnyk** [comment]
> to start the animation once the big name starts going out of view

@mohsen-ghafouri not sure animation looks like @ibrkhalil described here 👆.

@ibrkhalil can you show us an example?

**Comment by ibrkhalil** [comment]
> > to start the animation once the big name starts going out of view
> 
> 
> 
> @mohsen-ghafouri not sure animation looks like @ibrkhalil described here 👆.
> 
> 
> 
> @ibrkhalil can you show us an example?
> 
> 

The same behavior in chat basically, Once the big name gets halfway hidden we should animate the small name in.
https://github.com/status-im/status-mobile/assets/33176106/d80ca536-8ba9-45d2-b172-97acd67bd358

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri let me know your thought regarding Ibrahem's example. In case you are not agree or not sure maybe we need to raise this question to designers.

**Comment by mohsen-ghafouri** [comment]
@mariia-skrypnyk this is exactly like what @ibrkhalil mentioned. what's the issue? did you see the same animation i posted in the description video?

**Comment by ibrkhalil** [comment]
> @mariia-skrypnyk this is exactly like what @ibrkhalil mentioned. what's the issue? 

There's no issue, The implementation in the chat was updated recently and I wasn't aware of it's behavior so I thought it needed adjusting.

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri I love your animation. Just not sure it is exact the same as @ibrkhalil mentioned above.
I've checked from my side and move PR to @Francesca-G design review to make sure it is really what is expected.
Thanks 🙌

**Review by Francesca-G — APPROVED** [review]
Here's the [review](https://www.figma.com/file/OU646EHTHdj45z55dhxRDg/Review-Profile-%2F-Mobile?type=design&node-id=34%3A1030&mode=design&t=4XihTeehou1Ly3Xt-1)

Nice job with the animation ✨
Adding follow up required to address other issues in the screen.

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri will you have time to create followups regarding design review? 🙏

**Comment by mohsen-ghafouri** [comment]
@mariia-skrypnyk yes i will do and will remove follow up label from this PR then.
