### PR TITLE
[BUG #1990] Improved amount validation in wallet/send screen

### LINKED ISSUE #1990: Wallet: implement error handling for send amount
### Description

*Type*: Bug

*Summary*: Error handling for `send` amount should be implemented in Wallet to cover the following cases:
- user is sending amount which is bigger than actual balance
- error in web3 happened

#### Expected behavior
User-friendly error message is shown in above-listed cases

#### Actual behavior
Nothing happens for now

### Additional Information
* Status version: 0.9.10-159-g4b6f920e+ (1716)
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by jeluard**
fixes #1990

### Summary:
Fixes incorrect amount validation in wallet/send screen

### Steps to test:
- Open Status
- Navigate to wallet/send screen
- Enter an amount bigger than wallet balance: direct signing should be disabled while later should be enabled

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/db.cljs [hunk 1]
```diff
@@ -24,9 +24,12 @@
   (let [amount' (string/replace amount #"," ".")
         amount-splited (string/split amount' #"[.]")]
     (cond
-      (or (nil? amount) (= amount "") (= amount "0") (re-matches #"0[,.]0*$" amount))
+      (or (nil? amount) (= amount "") (re-matches #"0[,.]0*$" amount))
       nil
 
+      (= amount "0")
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/db.cljs:30]: zero should be valid, later user can send data with 0 amount

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 2]
```diff
@@ -1,27 +1,25 @@
 (ns status-im.ui.screens.wallet.send.views
   (:require-macros [status-im.utils.views :refer [defview letsubs]])
-  (:require [clojure.string :as str]
-            [status-im.components.react :as react]
+  (:require [clojure.string :as string]
+            [reagent.core :as r]
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/views.cljs]: reagent

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 3]
```diff
@@ -45,80 +43,92 @@
             bottom-value (animation/create-value -250)
             opacity-value (animation/create-value 0)]
     {:component-did-mount #(send.animations/animate-sign-panel opacity-value bottom-value)}
-    [react/animated-view {:style (styles/animated-sign-panel bottom-value)}
-      [react/animated-view {:style (styles/sign-panel opacity-value)}
-       [react/view styles/signing-phrase-container
-        [react/text {:style styles/signing-phrase} signing-phrase]]
-       [react/text {:style styles/signing-phrase-description} (i18n/label :t/signing-phrase-description)]
-       [react/view styles/password-container
+    [react/animated-view {:style (send.styles/animated-sign-panel bottom-value)}
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/views.cljs:45]: i think we can use `styles` in views from this ns, only if we are using another ns styles we should use `something.styles`

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 4]
```diff
@@ -45,80 +43,92 @@
...
-     [react/touchable-highlight {:on-press (when sign-enabled? #(re-frame/dispatch [:set-in [:wallet/send-transaction :signing?] true]))}
-      [react/view (wallet.styles/button-container sign-enabled?)
+     [react/touchable-highlight {:on-press (when immediate-sign-enabled? #(re-frame/dispatch [:set-in [:wallet/send-transaction :signing?] true]))}
+      [react/view (wallet.styles/button-container immediate-sign-enabled?)
        [components/button-text (i18n/label :t/transactions-sign-transaction)]
-       [vi/icon :icons/forward {:color :white :container-style wallet.styles/forward-icon-container}]]]]))
+       [vector-icons/icon :icons/forward {:color :white :container-style wallet.styles/forward-icon-container}]]]]))
+
+(defn- sufficient-funds? [amount balance]
+  (<= amount (money/wei->ether balance)))
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/views.cljs:94]: what about transaction fee?

File: src/status_im/ui/screens/wallet/transactions/views.cljs [hunk 5]
```diff
@@ -205,12 +206,16 @@
...
+  (case symbol
+    "ETH" (if amount (money/wei->str :eth amount) "...")))
+
+(defn transaction-details-header [{:keys [value date type symbol]}]
   [react/view {:style transactions.styles/transaction-details-header}
    [react/view {:style transactions.styles/transaction-details-header-icon}
     [list/item-icon (transaction-type->icon type)]]
    [react/view {:style transactions.styles/transaction-details-header-infos}
-    [react/text {:style transactions.styles/transaction-details-header-value} (str value " ETH")]
+    [react/text {:style transactions.styles/transaction-details-header-value} (pretty-print-asset symbol value)]
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/transactions/views.cljs]: because for example here `transactions.styles` is too noisy

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 6]
```diff
@@ -45,80 +43,92 @@
...
+         [react/view components.styles/flex
+          [react/view wallet.styles/choose-participant-container
+           [components/choose-recipient {:address  to-address
+                                         :name     to-name
+                                         :on-press #(re-frame/dispatch [:navigate-to :choose-recipient])}]]
+          [react/view wallet.styles/choose-wallet-container
+           [components/choose-wallet]]
+          [react/view wallet.styles/amount-container
+           [components/amount-input
+            {:error         (or amount-error (if-not sufficient-funds? "Not enough fund"))
```
Comment (flexsurfer) [inline src/status_im/ui/screens/wallet/send/views.cljs]: i18n

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/wallet/transactions/views.cljs (hunk 5 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/transactions/views.cljs]: and `transaction-details-` too, so it could be `styles/header`, `styles/header-value`

Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/transactions/views.cljs]: much easy to read

File: src/status_im/ui/screens/wallet/db.cljs (hunk 1 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/db.cljs:30]: We don't allow to provide data for now so I'd rather let this and revisit when we add it.

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 3 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs:45]: Why not.
If so we should document all of it as this is an exception to the rule we choosed.

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 4 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs:94]: Make sense.

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 6 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs]: Right

File: src/status_im/ui/screens/wallet/transactions/views.cljs (hunk 5 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/transactions/views.cljs]: I agree, I will shorten style names.

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 6 above)
Comment (rasom) [reply src/status_im/ui/screens/wallet/send/views.cljs]: `when-not` can be used here

File: src/status_im/ui/screens/wallet/send/views.cljs (hunk 4 above)
Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs:94]: I will handle this in a separate ticket.

**Comment by jeluard** [comment]
@rasom @flexsurfer I pushed changes according to your comments

**Review by flexsurfer — APPROVED** [review]
