### PR TITLE
fix incorrect unread counter is displayed when a message is removed

### LINKED ISSUE #18994: Incorrect unread counter is displayed when a message is removed
### Steps to reproduce:
`User A` sends 3 messages to `User B` (resulting in `User B` seeing 3 unread counters).
`User A` removes the last message (resulting in User B seeing 1 unread counter).
`User A` sends one more message.

### Actual result:
`User B` sees -2 messages counter when a message is removed and +2 messages counter when a message is added.

https://github.com/status-im/status-mobile/assets/52490791/2e494e23-b274-43de-9562-fa35f6716755

### Expected result:
`User B `should see -1 messages counter when a message is removed and +1  message counter when a message is added.

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/18994

status: ready

### CODE REVIEW

File: src/legacy/status_im/chat/models/message.cljs [hunk 1]
```diff
@@ -135,9 +134,7 @@
                                     message-id (:messageId removed-message)]
                                 (data-store.messages/mark-messages-seen chat-id
```
Comment (Parveshdhull) [inline src/legacy/status_im/chat/models/message.cljs:135]: Do we need this?

**Review by ibrkhalil — APPROVED** [review]

File: src/legacy/status_im/chat/models/message.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/legacy/status_im/chat/models/message.cljs:135]: No idea :)

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull  !

Thanks for your fix. Now unread counter is correct on both platforms.
You can merge your PR. Great job!
