### PR TITLE
fix: chats leaking to other profiles

### LINKED ISSUE #21696: Chat list is shared between different users
# Bug Report

## Problem 
Chat list is shared between users on one device, which leads to non-working chats that are shared

#### Expected behavior
empty chat list for user1

#### Actual behavior
chat list with preview for user1 is shown

https://github.com/user-attachments/assets/00a75b42-ad0e-4f1e-850c-99b66fc7d1f8

### Reproduction

1. Device 1: create user1 and user2
2. Device2: sent contact request to user1 
3. Device1: check user1 chat list
4. Device1: log out as user1 (via Profile) 
5. Device1: log in as user2 and check a chat list 

### Additional Information

- Status version: nightly 27/11/11
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/21696

### Summary

This PR fixes a regression introduced in PR https://github.com/status-im/status-mobile/pull/21634.

What's important is that the fix for chats leaking to other profiles was a client-side bug, not in status-go, thus no private data was leaking to other profiles. This PR keeps the existing workaround to memoize chats.

#### Areas that may be impacted

- Showing chats after login.

### Steps to test

Steps are described in the issue. Just create one profile `UserA` with 1 chat and create another profile `UserB` without chats. Close the app, login with `UserA`, logout, login with `UserB`. You will see the chat from `UserA` appears in `UserB` list of recent chats.

Check the same steps in this PR and the issue should be gone.

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Hi @ilmotta,

Thank you very much for working on the issue.

The `chats-stack-items` should have been reset with the correct list upon relogin and opening the chats tab. If this is not happening, it's most likely because the view-id is incorrect. To fix the issue, we need to correct the `view-id`.

(Alternatively, a quick solution without removing the memoization would be to reset the chats-stack-items upon logout.)

File: src/status_im/subs/chats.cljs [hunk 1]
```diff
@@ -8,20 +8,11 @@
...
+(re-frame/reg-sub :chats/chats-stack-items
  :<- [:chats/home-list-chats]
- :<- [:view-id]
  :<- [:home-items-show-number]
- (fn [[chats view-id home-items-show-number]]
-   (if (or (empty? @memo-chats-stack-items) (= view-id :chats-stack))
-     (let [res (take home-items-show-number chats)]
-       (reset! memo-chats-stack-items res)
-       res)
-     ;;we want to keep data unchanged so react doesn't change component when we leave screen
```
Comment (ulisesmac) [inline src/status_im/subs/chats.cljs]: I'm not sure what this comment is referring to. React itself doesn't change the data, and re-frame just recompute subs so it'd reach the same value.

AFAIK, Re-reframe compares using Clojure's `=`, so we don't need a stable reference.

I don't understand the usage of the atom 🤔

**Review by ulisesmac — APPROVED** [review]

File: src/status_im/subs/chats.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/subs/chats.cljs]: Hi @ulisesmac, when a user receives a message, the last-message key is updated, and the chat screen list item is refreshed.

If the user is not on the chat home screen (e.g., while chatting), this atom provides cached data to prevent unnecessary updates on the home screen.

I can see the usefulness of this, but it’s an older performance improvement, and @flexsurfer can probably provide more context.

Comment (ulisesmac) [reply src/status_im/subs/chats.cljs]: @Parveshdhull Thank you so much for the context!

I've always wondered what happens with the screens in a navigation stack that aren't focused. Are their subscriptions still mounted and running? by what you say, I infer that the answer is YES.

> when a user receives a message, the last-message key is updated, and the chat screen list item is refreshed.

I wonder what is the impact this may have, since it's just a rerender of a single chat item it might be very cheap, right? I mean, what is going on in the chat screen is a lot more complex/costly so the perf gain is probably negligible.

Thanks for the explanation @Parveshdhull!

Comment (ulisesmac) [reply src/status_im/subs/chats.cljs]: @ilmotta 

This fix made me think about the global atoms we use and if we are properly resetting all of them :thinking:

**Comment by ilmotta** [comment]
Thanks guys for reviewing this PR @ulisesmac @Parveshdhull I pushed a definitive fix and I was able to keep the memoization workaround, so the issue is solved in my tests.

I gotta say it's quite difficult to grasp code related to navigation and I don't mean anything related to the navigation library, more like our own code. For sure there's room for a serious revamp, only if we had time 😄 ⌛ 

-----

Today I dived deeper into the home chats screen code and noticed various performance problems. This led me to invest time in documenting the performance optimizations I applied. In my simulation the new implementation is much smoother than the original in `develop`. Hopefully next week I'll open a PR for more CCs to check.

I didn't want to mix optimizations with this PR because this PR is a release blocker.

**Review by ulisesmac — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im/subs/chats.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/subs/chats.cljs]: When I was working on this task, it was a significant challenge because the entire list recalculates and redraws when we swap cells. Additionally, as soon as we receive a message in any chat, that chat moves to the top of the list. For instance, if you're currently in the wallet section, you probably don't want any other process to interfere with your actions there. On the other hand, if we unload the list, returning to the chats would take a lot of time since everything would need to be recalculated, initialized, and re-rendered from scratch. Also, let's not forget that unsubscribing from subscriptions also takes time.

I can't say for sure how this is implemented right now, so it’s better to ask Parvesh. However, I am confident that this is still an issue on older Android devices.

Comment (flexsurfer) [reply src/status_im/subs/chats.cljs]: Most importantly, don’t forget: everything might look perfect to you simply because no one is actively using the app and reporting how it lags. Just take an old device and start actively using the app — with hundreds of contacts and thousands of chats — and you’ll be unpleasantly surprised at how poorly and slowly the app performs.

Comment (ilmotta) [reply src/status_im/subs/chats.cljs]: Fair points @flexsurfer 💯 Thanks for the context, this will be useful in my attempts to make some optimizations to the chat list rendering.
