### PR TITLE
Fixes for composer

### LINKED ISSUE #19855: Composer collapsed on deleting text
### Current behaviour
When the composer is fully expanded, after typing a character and then deleting that character, it collapses.

### Expected behaviour
Composer should stay expanded

### Reproducible steps:

1. Fully Expand composer
2. Type some characters
3. Delete those characters

https://github.com/status-im/status-mobile/assets/29354102/c88542eb-aca2-44a8-8e71-eaa9ca8bd913

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19855, https://github.com/status-im/status-mobile/issues/19856

### Summary
This PR fixes 2 bugs in the composer: 
1. Composer collapsed on deleting text
2. Composer rebounces when it shouldn't

### Demo
Demo fix for (Composer collapsed on deleting text):

https://github.com/status-im/status-mobile/assets/29354102/a1b84d91-6506-4738-a127-05b9499c8273

Demo fix for (Composer rebounces when it shouldn't):

https://github.com/status-im/status-mobile/assets/29354102/5830f4cf-75ed-45a4-94e2-9ab2162ed994

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im/contexts/chat/messenger/composer/effects.cljs [hunk 1]
```diff
@@ -109,7 +109,7 @@
   (rn/use-effect
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/messenger/composer/effects.cljs]: it should be use-mount then

**Comment by VolodLytvynenko** [comment]
hi @OmarBasem Thank you for PR. No issues from my side. PR is ready to be merged
