### PR TITLE
bug #2949 - resolved unset gas info after send from chat

### LINKED ISSUE #2949: 'Transaction underpriced' error at attempt to send ETH from wallet after /send command in chat
### Description
*Type*: Bug
*Summary*: after  /send command in chat I'm unable to send transaction from wallet because default transaction fee is unset:
sentrans1
At attempt to send transaction get an error:
underprice

#### Expected behavior
transaction fee 21000 * 21 Gwei (as default)
user can send transaction

#### Actual behavior
after signing get an error 'transaction failed: Transaction underpriced' 

### Reproduction

- Open Status
- Use /faucet to get 0.1 ETH
- /send any amount in 1-1 chat 
- open wallet
- tap on 'Send'
- tap on 'Choose recipient'
- scan valid QR code
- choose amount
- tap on Advanced.
-- Expected: default value (21000 * 21 Gwei (as default)) 
-- Actual: empty value
- try to sign transaction.

### Additional Information

* Status version: nightly 05/01, 0.9.11d520; release 0.9.11d530
* Operating System: Android, iOS
Transaction fee comes back to default values after relaunch the app.

#### Logs
TF (00:20-01:28): https://app.testfairy.com/projects/4803590-status/builds/7442835/sessions/26/?accessToken=EOpHYWvLcVgfUh0b5NAyTbCKrHs

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #2949

### Summary:

Gas details (price and limit) were shared between the transactions which meant that the gas info used in the current transaction will be the default gas info in the next transaction.

This can cause a problem if the previous transaction was created by a bot, i.e. `/send` command from chat. Since bots can be created externally, allowing this behavior would make it easy for the bot creator to change the default transaction settings for the unsuspecting user who rarely or never opens Advanced settings. In this case, the bug was just an inconsistency between bot send and wallet send, but it highlights why we shouldn't allow this to happen.

The risk here is in the UX - user tries a bot and suddenly sending appears broken!

The solution in this PR is to always use the same default gas price and limit, regardless of the previous transaction settings, i.e. stateless.

The other change introduced here is that now we are setting the gas limit for /send transactions in the bot code, so it is available in status-go at the time when transaction.queued signal is being sent. This means that now we are showing the gas limit just fine in Wallet signing modal.

### Steps to test:
- Get some test ether
- Send a transaction from chat
- Try sending one from Wallet
- Verify that gas info is there
- Send from Wallet
- Send another from chat
- Verify that all 3 transactions are ok

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by jeluard** [comment]
@goranjovic Does that explain the fixed bug (values were nil)? And can I still update gas details in all scenarios?

**Comment by goranjovic** [comment]
@jeluard Yes, you can update gas details for a transaction and it will be used. But when you start a new transaction you'll have the same default values as before, not the updated ones. Re, other question - thread with Adam :)

**Comment by jeluard** [comment]
@goranjovic I mean in the Advance panel, nothing was shown. Does your fix address that too?

**Comment by goranjovic** [comment]
@jeluard That's exactly what it fixes. Instead of nothing, you see the default gas limit and price. Also, transaction works ok,

**Comment by goranjovic** [comment]
@jeluard The remark about security/UX is with regard to the exact way the solution works (by not remembering gas info of old transactions)

**Comment by goranjovic** [comment]
Just noticed, this is PR is 3000th github ticket :tada:

**Review by jeluard — APPROVED** [review]

**Comment by goranjovic** [comment]
----------------
Branch: PR-3000
Android: https://i.diawi.com/7A917c
iOS: https://i.diawi.com/iBNZra

**Comment by asemiankevich** [comment]
@goranjovic no gas limit shown when sending ETH in 1x1 chat:
image

https://app.testfairy.com/projects/4803590-status/builds/7475934/sessions/6/?accessToken=68ZvRNqVrq-2db0MQxglc5agBGU

File: src/status_im/ui/screens/wallet/send/views.cljs [hunk 1]
```diff
@@ -118,7 +118,7 @@
 
 (defn- max-fee [gas gas-price]
   (when (and gas gas-price)
-    (money/wei->ether (.times gas gas-price))))
+    (money/wei->ether (.times (money/bignumber gas) gas-price))))
```
Comment (jeluard) [inline src/status_im/ui/screens/wallet/send/views.cljs]: Why this change? Isn't `gas` always a bignumber at this point?

Comment (goranjovic) [reply src/status_im/ui/screens/wallet/send/views.cljs]: It wasn't. Took me a while to figure that.

Comment (goranjovic) [reply src/status_im/ui/screens/wallet/send/views.cljs]: Not when it arrives from bot via signal anyway

Comment (jeluard) [reply src/status_im/ui/screens/wallet/send/views.cljs]: Can we make it a bignumber at the source then? All our numerical values should be bignumber, and wei when relevant, to reduce confusion potential.

**Comment by goranjovic** [comment]
@jeluard Turns out we definitely need to convert the values. I just made sure to do that in the place that makes the most sense - after we receive the signal. If you're ok with this, I'd like to move this to testing?

**Review by jeluard — APPROVED** [review]

**Comment by churik** [comment]
Gas price and limit is not shown for transaction from DApp (moved to #3022 as separate issue)
 
Steps:
1) open AuctionHouse
2) Tap on "Create auction"
3) Enter any valid name in "Name to reserve"
4) Tap on "register name"
5) On "Advanced" Send transaction screen.

**Comment by asemiankevich** [comment]
@churik i believe ^ issue is due to https://github.com/status-im/status-react/issues/2653 so the values simply are not received and it is not related to this PR. @goranjovic thoughts?

**Comment by goranjovic** [comment]
@churik @asemiankevich Indeed, this is a different issue and not fully under our control. We don't necessarily control dapp code. However, please create a new issue for it anyway, so that we can research and discuss how and what to do about it.

**Comment by churik** [comment]
### Install:

- using send command from "Wallet" screen after /send in 1-1 chat, group chat and vice versa

### Upgrade:

#### Data before upgrade:
* 1-1 chat
* console chat
####  After upgrade:
* using send command from "Wallet" screen after /send in 1-1 chat (with different fee), group chat and vice versa
