### PR TITLE
[#21828] Close the flows for adding accounts in keycard accounts

### LINKED ISSUE #21828: Close the flows for adding accounts in keycard accounts
# Bug Report

## Problem 
As https://github.com/status-im/status-mobile/issues/21819 is reproducible for keycard accounts that were upgraded from v1, the only quick fix for now is to close completely the flows until they are ready.

#### Expected behavior
Cannot add derived accounts and new keypairs

#### Actual behavior
Can add derived accounts and new keypairs, but https://github.com/status-im/status-mobile/issues/21819 is reprodycible if profile was upgraded

### Reproduction

1. Open profile
2. Migrate it to keycard 
3. Tap + 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21828

### CODE REVIEW

File: src/status_im/contexts/wallet/home/view.cljs [hunk 1]
```diff
@@ -15,19 +15,23 @@
...
-        :add-divider?        true})]]])
+  (let [keycard? (rf/sub [:keycard/keycard-profile?])]
+    [quo/action-drawer
+     [[{:icon                :i/add
+        :accessibility-label :start-a-new-chat
+        :label               (i18n/label :t/add-account)
+        :sub-label           (i18n/label :t/add-account-description)
+        :on-press            (fn []
+                               (if keycard?
+                                 (rf/dispatch [:keycard/feature-unavailable-show])
```
Comment (seanstrom) [inline src/status_im/contexts/wallet/home/view.cljs]: Can we change this line to be something like this?
```
(rf/dispatch [:keycard/feature-unavailable-show {:feature-name :chat.new-chat}])
```
This will help us with metrics that we track for which unavailable feature are people discovering.

**Review by ilmotta — APPROVED** [review]

File: src/status_im/contexts/wallet/home/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im/contexts/wallet/home/view.cljs]: Good catch @seanstrom 👍🏼

**Review by Parveshdhull — APPROVED** [review]

File: src/status_im/contexts/wallet/home/view.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/contexts/wallet/home/view.cljs]: done

**Review by seanstrom — APPROVED** [review]
