### PR TITLE
fix(wallet): native share should point to opensea link

### LINKED ISSUE #20223: Wallet - Share collectible should link to opensea
Currently the Share button in the collectible page points to the wrong resource:
Screenshot 2024-05-28 at 23 44 11

However this should point to the open sea url instead.

see designs:

https://www.figma.com/design/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?node-id=4551-43955&t=IhP7H50o2eJ5IgAt-1

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/20223

This pr updates the native share for the collectibles in wallet so that the url it points to is for the Open Sea link 
e.g https://opensea.io/assets/ethereum/0xa342f5d851e866e18ff98f351f2c6637f4478db5/93539746106169265185984122850742147987924040810729814653747710597909889193997

This has four points of entry. Home Page, Account Page, Collectible overview page, lightbox in collectible overview page.

**Home Page:** 
 

**Account Page:**
 

**In lightbox:**
 

**In overview page:**

### CODE REVIEW

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 1]
```diff
@@ -103,8 +107,12 @@
...
                                               {:content (fn []
                                                           [options-drawer/view
-                                                           {:name  title
-                                                            :image picture}])
+                                                           {:name             title
+                                                            :image            picture
+                                                            :chain-id         chain-id
+                                                            :token-id         token-id
+                                                            :contract-address contract-address
+                                                           }])
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/collectible/view.cljs]: Trailing

File: src/status_im/contexts/wallet/collectible/view.cljs [hunk 2]
```diff
@@ -190,7 +198,12 @@
                                                                             [options-drawer/view
                                                                              {:name collectible-name
                                                                               :image
-                                                                              preview-uri}])}])}])))
+                                                                              preview-uri
+                                                                              :chain-id chain-id
+                                                                              :token-id token-id
+                                                                              :contract-address
+                                                                              contract-address
+                                                                             }])}])}])))
```
Comment (OmarBasem) [inline src/status_im/contexts/wallet/collectible/view.cljs]: Trailing

**Review by OmarBasem — APPROVED** [review]

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 2 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/collectible/view.cljs]: thanks, addressed

File: src/status_im/contexts/wallet/collectible/view.cljs (hunk 1 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/collectible/view.cljs]: thanks, addressed

File: src/status_im/contexts/wallet/collectible/events.cljs [hunk 3]
```diff
@@ -187,24 +187,31 @@
...
    {:fx [[:effects.share/open
-          {:title   title
-           :message title
-           :url     uri}]]}))
+          {:options
+           {:title   title
+            :subject title
+            :message uri}}]]}))
 
 (rf/reg-event-fx :wallet/share-collectible
```
Comment (vkjr) [inline src/status_im/contexts/wallet/collectible/events.cljs:218]: I think that `in-sheet?` as an argument adds unnecessary knowledge about the outer context to this event. Instead we can pass `dispatch-timeout` and make decision of selecting `dispatch` vs `dispatch-later` based on it. And `:hide-bottom-sheet` could be called outside, where knowledge about UI details exist. This will make `:wallet/share-collectible` more flexible.
Wdyt?

Comment (J-Son89) [reply src/status_im/contexts/wallet/collectible/events.cljs:218]: yes, that's a good point! will adjust to that!

File: src/status_im/contexts/wallet/home/tabs/view.cljs [hunk 4]
```diff
@@ -10,15 +10,17 @@
...
 (defn- on-collectible-long-press
   [{:keys [preview-url collectible-details id]}]
-  (let [chain-id (get-in id [:contract-id :chain-id])
-        address  (get-in id [:contract-id :address])]
+  (let [chain-id         (get-in id [:contract-id :chain-id])
+        token-id         (:token-id id)
+        contract-address (get-in id [:contract-id :address])]
     (rf/dispatch [:show-bottom-sheet
                   {:content (fn []
                               [options-drawer/view
```
Comment (vkjr) [inline src/status_im/contexts/wallet/home/tabs/view.cljs]: In few places parameters `chain-id`, `token-id` and `contract-address` are all extracted from one `id` param before passing to `options-drawer/view`. Instead we can pass just `id` and make the extraction inside `options-drawer/view` to reduce text repetition. This will also reduce surface for changes if structure of `id` will change in a future.

**Review by vkjr — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

**Review by mmilad75 — APPROVED** [review]

File: src/status_im/contexts/wallet/home/tabs/view.cljs (hunk 4 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/home/tabs/view.cljs]: thanks for the great suggestions! Will update :)

File: src/status_im/contexts/wallet/collectible/events.cljs (hunk 3 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/collectible/events.cljs:218]: hmm on reviewing this, I think one thing to consider is that `in-sheet?` will hide the bottom sheet. 
But anyway I see there is only one use of this function and it's in a bottom sheet, so I'll just remove that parameter altogether :)

**Comment by pavloburykh** [comment]
Hey @J-Son89! Thank you for the PR. Please take a look at the issue

### ISSUE 1 After selecting app for sharing collectible link - it is opened within Status app (Android)

Android only. Reproduced on Samsung Galaxy A52, Android 12

**Steps:** 

1. Open native share for the collectibles
2. Select app for sharing
3. See if selected app has been opened in separate tab or within Status app

**Actual result:** app is opened within Status app


https://github.com/status-im/status-mobile/assets/97245802/16aaaf8f-2ec0-49a4-a50f-0e79ff7e5fda



**Expected result:** app should be opened in separate tab. Below is an example of sharing community link. 



https://github.com/status-im/status-mobile/assets/97245802/274ba590-5cb1-4edd-9687-3435911964ca

**Comment by J-Son89** [comment]
thanks @pavloburykh - was not aware of this. Will address! 🙏

**Comment by pavloburykh** [comment]
> thanks @pavloburykh - was not aware of this. Will address! 🙏

thank you @J-Son89! Please, ping me up once PR is ready for re-test.

**Comment by J-Son89** [comment]
@pavloburykh issue 1 should be addressed now. Apologies for the delay.

**Comment by pavloburykh** [comment]
@J-Son89 thank you for the fixes. Please take a look at the new issue. 

### ISSUE 2 IOS crashes when sending collectible via longtap menu

**IOS ONLY** Reproducing on iPhoneX, IOS 16.7.7


**Steps:** 

1. Open Home Page or Account Page
2. Go to Collectibles tab
3. Longtap on any collectible
4. Tap "Share collectible" 
5. Observe the result

**Actual result:** app crashes


https://github.com/status-im/status-mobile/assets/97245802/dbb274fb-b158-4691-89f1-0c96ed20a1d1

**Comment by VolodLytvynenko** [comment]
> @J-Son89 thank you for the fixes. Please take a look at the new issue.
> 
> ### ISSUE 2 IOS crashes when sending collectible via longtap menu
> **IOS ONLY** Reproducing on iPhoneX, IOS 16.7.7
> 
> **Steps:**
> 
> 1. Open Home Page or Account Page
> 2. Go to Collectibles tab
> 3. Longtap on any collectible
> 4. Tap "Share collectible"
> 5. Observe the result
> 
> **Actual result:** app crashes
> 
>  telegram-cloud-document-2-5445185058564493526.mp4

Can't reproduce it on iPhone 11 Pro max, IOS 17.5.1. Collectibles are shared without crash for me

**Comment by qoqobolo** [comment]
Can't reproduce ISSUE 2 either (iPhone SE, iOS 17.5.1)

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by pavloburykh** [comment]
@J-Son89 thank you! The issue is fixed for me. Ready for merge.
