### PR TITLE
fix: fix slide button padding on transaction confirmation page

### LINKED ISSUE #18407: Wallet: fix slide button on transaction confirmation page
The slide button on the transaction confirmation page is not sitting right. 

This is a common component - https://github.com/status-im/status-mobile/blob/develop/src/status_im/common/floating_button_page/view.cljs

and might need to be addressed within that component.

Oddly enough it sits correctly after a hot reload is triggered.

Note: 
This common component is used on many pages, please check it does not break the other uses.

After hot reload it sits perfectly

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18407 

### Summary

This PR fixes unnecessary padding on transaction confirmation page caused by wrong value being set on `KeyboardVerticalOffset` prop of `KeyboardAvoidingView` in `status-im.common.floating-button-page.view` namespace

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Log in
- Go to wallet
- Select an account
- Select Send
- Select an address
- Select an asset
- Input an amount and wait for a route to be detected
- Select confirm to go to transaction confirmation page
- Verify padding on slide button is correct

status: ready

### CODE REVIEW

File: src/status_im/common/floating_button_page/view.cljs [hunk 1]
```diff
@@ -52,7 +52,7 @@
      :remove-listeners    remove-listeners}))
 
 (defn view
-  [{:keys [header footer customization-color gradient-cover?]} &
+  [{:keys [header footer customization-color keyboard-suggestion-bar? gradient-cover?]} &
```
Comment (J-Son89) [inline src/status_im/common/floating_button_page/view.cljs]: why don't we just make this value programmatical?
ie.g `footer-container-padding` and add the safe-area as a default

File: src/status_im/contexts/wallet/add_address_to_watch/view.cljs [hunk 2]
```diff
@@ -115,24 +115,25 @@
...
-          {:customization-color customization-color
-           :disabled?           (or (string/blank? @input-value) (some? (validate @input-value)))
-           :on-press            (fn []
-                                  (rf/dispatch [:navigate-to
-                                                :confirm-address-to-watch
-                                                {:address @input-value}])
-                                  (clear-input))
-           :container-style     {:z-index 2}}
-          (i18n/label :t/continue)]}
+        {:keyboard-suggestion-bar? true
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/add_address_to_watch/view.cljs]: we should add this to transaction-progress page too 👍

File: src/status_im/common/floating_button_page/view.cljs (hunk 1 above)
Comment (briansztamfater) [reply src/status_im/common/floating_button_page/view.cljs]: It is a valid suggestion, updated the approach!

File: src/status_im/contexts/wallet/add_address_to_watch/view.cljs (hunk 2 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/add_address_to_watch/view.cljs]: With the new approach you suggested, this is now needed. Updated the code to set `footer-container-padding` to `0` and left the default value where needed.

**Review by J-Son89 — APPROVED** [review]

File: src/status_im/common/floating_button_page/view.cljs [hunk 3]
```diff
@@ -52,7 +52,8 @@
      :remove-listeners    remove-listeners}))
 
 (defn view
-  [{:keys [header footer customization-color gradient-cover?]} &
+  [{:keys [header footer customization-color footer-container-padding gradient-cover?]
+    :or   {footer-container-padding (safe-area/get-top)}} &
```
Comment (ulisesmac) [inline src/status_im/common/floating_button_page/view.cljs:56]: I've seen  you updated the usages to pass `0` to `footer-container-padding`.

So I'm wondering if we actually need this value or not. if not, can we just remove this prop then?

Comment (briansztamfater) [reply src/status_im/common/floating_button_page/view.cljs:56]: If keyboard shows autocorrect view (default behavior for inputs), it needs an extra padding, so we still need this.

Comment (ulisesmac) [reply src/status_im/common/floating_button_page/view.cljs:56]: Incredible we have to manually handle that part ._.

thanks for the explanation! :+1:

**Review by ulisesmac — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
@briansztamfater Thanks for your PR!

I've checked slide button padding and also went through a places mentioned by Jamie.

> Note:This common component is used on many pages, please check it does not break the other uses.

One more thing: yesterday me and Volodymyr made a manual rebase, not sure if everything went well. Can you check it from your side? Thanks!
After this you can do the merge.

**Comment by briansztamfater** [comment]
> @briansztamfater Thanks for your PR!
> 
> I've checked slide button padding and also went through a places mentioned by Jamie.
> 
> > Note:This common component is used on many pages, please check it does not break the other uses.
> 
> One more thing: yesterday me and Volodymyr made a manual rebase, not sure if everything went well. Can you check it from your side? Thanks! After this you can do the merge.

Thanks for testing @mariia-skrypnyk , rebase went well and also rebased again to latest develop. Merging in 3... 2... 1... 😄
