### PR TITLE
[#22194] NFC prompt text not visible

### LINKED ISSUE #22194: Auxiliary text on NFC prompt is not visible in light mode (Android only)
# Bug Report

## Summary
The auxiliary text on the NFC prompt is not visible when the user has **light mode** enabled, so user can't see what is happening to keycard

## Expected Behavior
The user should see a prompt, similar to how it appears in **dark mode**.

### Dark Mode (Expected)
Dark Mode

## Actual Behavior
In **light mode**, the auxiliary text is missing or not visible.

### Light Mode (Bug)
Light Mode

## Steps to Reproduce

1. Open an account with a keycard.
2. Switch to **light mode**.
3. Attempt to send a transaction (`Send tx` flow).
4. Observe the NFC prompt.

## Additional Information

- **App Version:**  RC 2.33 build 4
- **OS:** Android  

[comment]: # (Add logs, console errors, or additional notes if applicable.)

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #22194

## Summary
Fixes the implementation for the light theme, including:
- The button bg and text
- The color of "Ready to scan"
- The text not appearing.

Light theme look:
image

### Platforms

- Android

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/keycard/nfc/sheets/view.cljs [hunk 1]
```diff
@@ -18,11 +18,16 @@
...
+                :color         (colors/theme-colors "#8F8E94" "#9F9FA5" theme)
+                :margin-bottom 36}}
        (i18n/label :t/ready-to-scan)]
-      [rn/image
-       {:source (resources/get-image :nfc-prompt)}]
-      [rn/text {:style {:font-size 16 :color :white :margin-vertical 36}}
+      [rn/image {:source (resources/get-image :nfc-prompt)}]
+      [rn/text
+       {:style {:font-size       16
+                :color           (colors/theme-colors "#09101C" :white theme)
```
Comment (ilmotta) [inline src/status_im/contexts/keycard/nfc/sheets/view.cljs:29]: What is the rationale for hard coding colors as we do in this namespace? I see the original code already used the hex colors hard coded.

The style maps are now multiline and not in the `style` namespace as well.

Comment (ulisesmac) [reply src/status_im/contexts/keycard/nfc/sheets/view.cljs:29]: Just followed the pattern that has been kept for 4 or 5 commits (so a PR reviewer should have catch it?)

We don't use our quo.text component because this UI doesn't use it's our custom texts.
For colors, I think it's because we won't reuse them (we try to mimic an OS request).

Maybe the styles maps aren't in a separate file because they are small?

Comment (ilmotta) [reply src/status_im/contexts/keycard/nfc/sheets/view.cljs:29]: Humm, it's fine, these are small details, but consistency is important in a large code base.

**Review by vkjr — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
@ulisesmac Thank you for your PR!
I checked this prompt on different themes:
- Adding a derived account
- Importing an account
- Signing transactions

Everything works fine, and the PR can be merged!

**Comment by vkjr** [comment]
@ulisesmac, thank you! 🥳
