### PR TITLE
fix: Cannot mark as read messages in communities

### LINKED ISSUE #18023: Cannot mark as read messages in communities
Issue has been found during testing [PR](https://github.com/status-im/status-mobile/pull/17979) with updated go branch. That's why during investigation of these issues developer should use the build that is looking at current go develop branch, i.e. not our mobile develop, because we haven't updated go in our develop yet.

The bug is most likely related to these https://github.com/status-im/status-go/pull/4337 go changes. 

**Steps:** 

1. Generate unread messages in community for User A
2. By User A open communities tab
3. Longtap on community => Mark as read
4. See if unread badges disappeared in community and its channels for User A

**Actual result:**  messages remain unread, badges do not disappear. 

**Expected result:** messages should be read, unread badges should disappear from community and channels. 

[Status-debug-logs (85).zip](https://github.com/status-im/status-mobile/files/13500379/Status-debug-logs.85.zip)

https://github.com/status-im/status-mobile/assets/97245802/b6c5f842-ce9d-46de-80bf-b5c326631bbe

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by qfrank**
fixes #18023

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

File: src/status_im/chat/models/loading.cljs [hunk 1]
```diff
@@ -76,9 +76,9 @@
 
 (rf/defn handle-mark-all-read-in-community-successful
   {:events [::mark-all-read-in-community-successful]}
-  [{:keys [db] :as cofx} chat-ids]
+  [{:keys [db] :as cofx} {:keys [chats] :as messenger-response}]
```
Comment (ilmotta) [inline src/status_im/chat/models/loading.cljs]: `messenger-response` is unused.

Comment (qfrank) [reply src/status_im/chat/models/loading.cljs]: yes, i knew, just want to make it more clear that `chats` comes from where, WDYT? @ilmotta

Comment (ilmotta) [reply src/status_im/chat/models/loading.cljs]: @qfrank, in the screenshot I changed the code to use `reg-event-fx` just as a reminder that code inside `rf/defn` is not linted and that's why you have a green build.

If you want to give meaning to the destructured map, you can use `_messenger-response` or you can simply not destructure. In the mobile team we seem to be obsessed with destructuring as if it's a rule (you get feedback in PRs if you don't use it), but I've seen many Clojure devs intentionally not destructuring so that they can explicitly give a name to the argument.

Pick your poison 😉 

```clojure
;; With underscore
(rf/defn handle-mark-all-read-in-community-successful
  {:events [::mark-all-read-in-community-successful]}
  [{:keys [db] :as cofx} {:keys [chats] :as _messenger-response}]
  (rf/merge cofx
            {:db       (reduce mark-chat-all-read db (map :id chats))
             :dispatch [:activity-center.notifications/fetch-unread-count]}))

;; Without destructuring
(rf/defn handle-mark-all-read-in-community-successful
  {:events [::mark-all-read-in-community-successful]}
  [{:keys [db] :as cofx} messenger-response]
  (rf/merge cofx
            {:db       (reduce mark-chat-all-read db (map :id (:chats messenger-response)))
             :dispatch [:activity-center.notifications/fetch-unread-count]}))
```

Comment (qfrank) [reply src/status_im/chat/models/loading.cljs]: Thank you. I prefer the first one!

**Comment by pavloburykh** [comment]
@qfrank thank you for the PR!

I have question regarding the description of this go [PR](https://github.com/status-im/status-go/pull/4337#issue-1999275069) which introduced the issue

According to the description:
```
Important changes:
1. Marking Mention or Reply AC notification as read (MarkAllActivityCenterNotificationsRead and MarkActivityCenterNotificationsRead) also marks corresponding message as seen
2. Marking message as seen (MarkMessagesSeen, MarkAllRead and MarkAllReadInCommunity) also marks corresponding AC notification as read
```

Point 2 ```Marking message as seen also marks corresponding AC notification as read``` works as described on mobile. 

Point 1 ```Marking Mention or Reply AC notification as read also marks corresponding message as seen``` does not work as described on mobile. Marking AC notification as read does not affect correspondent message in chat. @qfrank do we need some additional changes on mobile side so it works as described? Can this part be included in this PR or it makes sense to work on this separately. 

Below is the video showing current behaviour. 

[Status-debug-logs (86).zip](https://github.com/status-im/status-mobile/files/13527652/Status-debug-logs.86.zip)

https://github.com/status-im/status-mobile/assets/97245802/910c7ce9-2792-465e-a324-aa1373b272ec

**Comment by qfrank** [comment]
> @qfrank thank you for the PR!
> 
> I have question regarding the description of this go [PR](https://github.com/status-im/status-go/pull/4337#issue-1999275069) which introduced the issue
> 
> According to the description:
> 
> ```
> Important changes:
> 1. Marking Mention or Reply AC notification as read (MarkAllActivityCenterNotificationsRead and MarkActivityCenterNotificationsRead) also marks corresponding message as seen
> 2. Marking message as seen (MarkMessagesSeen, MarkAllRead and MarkAllReadInCommunity) also marks corresponding AC notification as read
> ```
> 
> Point 2 `Marking message as seen also marks corresponding AC notification as read` works as described on mobile.
> 
> Point 1 `Marking Mention or Reply AC notification as read also marks corresponding message as seen` does not work as described on mobile. Marking AC notification as read does not affect correspondent message in chat. @qfrank do we need some additional changes on mobile side so it works as described? Can this part be included in this PR or it makes sense to work on this separately.
> 
> Below is the video showing current behaviour.
> 
> [Status-debug-logs (86).zip](https://github.com/status-im/status-mobile/files/13527652/Status-debug-logs.86.zip)
> 
>  telegram-cloud-document-2-5424621648504438275.mp4

i'll work on it in a separate PR @pavloburykh

**Comment by pavloburykh** [comment]
@qfrank thank you! PR is ready for merge

**Comment by pavloburykh** [comment]
> i'll work on it in a separate PR @pavloburykh

Thank you @qfrank! I have created a [ticket](https://github.com/status-im/status-mobile/issues/18050).
