### PR TITLE
[#4755] Keep the transaction source intact on errors/discards.

### LINKED ISSUE #4755: Read-only fields Amount, Asset and Recipient can be modified if cancel signinig transaction
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:

1:1 chat will show one amount (0.1 ETH) but another amount (0 ETH) was actually sent if use /send command and cancel signing transaction on Sent transaction screen. As a result, fields on the screen become editable and user can provide another amount, e.g. change 0.1 ETH to 0 ETH and after this sign transaction. Unfortunately, 1:1 will show initial amount 0.1 ETH.

It's also possible to edit fields Asset and Recipient

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
I see 2 options:
1. user can't modify values if transaction was initiated from 1:1 chat or
2. user can modify values but then 1:1 chat should show proper amount sent

#### Actual behavior
[comment]: # (Describe what actually happened.)
1:1 chat shows wrong amount used for send transaction
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
from 00:20 https://app.testfairy.com/projects/4803622-status/builds/8487381/sessions/4393923712/?accessToken=Uclx0lDmnfyCET2N6r5AfcH5YLM
- Open status
- open 1:1 chat
- send 0.01 
- on Send transaction screen tap  on Sign transaction to enter password
- tap Cancel
- check if fields Amount, Asset and Recipient are editable
- change value in Amount to 0 and Sign transaction
- check send message shown in the chat and transaction history

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly jun 13 and PR build for #4742 
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8487381/sessions/4393923712/?accessToken=Uclx0lDmnfyCET2N6r5AfcH5YLM">TestFairy: Status 0.9.19 (6054) @403</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by mandrigin**
If a tx was send from a chat, that fact is recorded in its properties, `from-chat?` property.
On errors and discards, this property was reset to `false`, hence, making any chat transaction editable if an error happens or user discards it.
This commit makes this property stay as it is.

### Steps to test:
- Open Status
- Open 1:1 chat
- Use `/send` command to show a tx screen, tap "Sign"
- Press "Cancel"
- Tx fields should still be read-only

fixes: #4755 

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by annadanchenko** [comment]
Straightforward scenario described in steps is fixed.
Unfortunately, similar issue occurs if user provided wrong password and then cancels signing -> fields become editable

Steps:
from 00:20 https://app.testfairy.com/projects/4803622-status/builds/8494723/sessions/4393960484/?accessToken=UJdP3CSJ1COGvFSZHGv/YKtnQDg 
1. In 1:1 chat send transaction
2. On Send transaction screen type wrong password
3. tap cancel
4. check that fields Amount, Recipient, Asset are editable

**Comment by mandrigin** [comment]
looking at it...

**Comment by mandrigin** [comment]
ok, basically "wrong password" unblocks the fields...

**Comment by mandrigin** [comment]
@annadanchenko fixed this specific case

File: src/status_im/ui/screens/wallet/send/events.cljs [hunk 1]
```diff
@@ -216,6 +218,7 @@
  :sign-request-failed
  (fn [{{:keys [view-id modal] :as db} :db} [_ {:keys [id method error_code error_message]}]]
    (let [send-transaction (get-in db [:wallet :send-transaction])]
+     (log/debug "igorm -> send-transaction" send-transaction)
```
Comment (goranjovic) [inline src/status_im/ui/screens/wallet/send/events.cljs]: looks good, can you just remove the debug logs?
(or did you want to merge them in?)

**Review by goranjovic — APPROVED** [review]

File: src/status_im/ui/screens/wallet/send/events.cljs (hunk 1 above)
Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/events.cljs]: oops, not only @oskarth is distracted today 😆

Comment (mandrigin) [reply src/status_im/ui/screens/wallet/send/events.cljs]: fixed
