### PR TITLE
[#18929] fix: no bottom space under the join button

### LINKED ISSUE #18929: [Android] No bottom space under the 'Slide to request to join' button
# Bug Report

## Problem 

The issue is visible when there is no bottom navigation bar on the device (e.g. Huawei, screenshot 1), or when it's black (Pixel, screenshot 2).

image

Screenshot 2024-02-21 at 13 18 42

#### Expected behavior

Figma: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-285065&mode=design&t=IsSq8UaiwKNFWKzn-4

### Additional Information

- Status version: nightly 21/02
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #18997: [Communities] There is no bottom margin on iPhone SE under the Slide to request to join button
Follow up #18761

# Bug Report
During the refactoring to fix Community rules scroll we discovered that the fix is not perfect on iPhone SE and small devices.

Please check the following [comment](https://github.com/status-im/status-mobile/pull/18761#issuecomment-1948635977)

## Problem 
There is no bottom margin on iPhone SE under the Slide to request to join button 

#### Expected behavior
Should looks like [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-285065&mode=design&t=26fIK54eJTrGJu3S-0)

image

#### Actual behavior
image

### Reproduction

1. Activate the Accounts Selection feature flag.
2. Input text of maximum length into the 'Dialog for new members' field on the desktop.
3. Invite a user and attempt to join this community on a mobile device.
4. Run the app on iPhone SE and verify that the slide is not rendering as expected
 
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #18929
fixes #18997

### Summary

No bottom space under the 'Slide to request to join' button

#### Platforms

- Android
- iOS (SE)

### Result

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/actions/accounts_selection/style.cljs [hunk 1]
```diff
@@ -16,4 +17,5 @@
   []
   {:padding-top        12
    :padding-horizontal screen-horizontal-padding
-   :background-color   (colors/theme-colors colors/white colors/neutral-95)})
+   :background-color   (colors/theme-colors colors/white colors/neutral-95)
+   :padding-bottom     (+ (safe-area/get-bottom) 12)})
```
Comment (seanstrom) [inline src/status_im/contexts/communities/actions/accounts_selection/style.cljs]: What does iOS look like with these changes? Will adding safe-area plus the bottom-padding be consistent for both platforms?

**Review by seanstrom — COMMENTED** [review]
Looks good! I left one small comment about consistency between iOS and Android.

File: src/status_im/contexts/communities/actions/accounts_selection/style.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/communities/actions/accounts_selection/style.cljs]: yes it considers the notch area (if the device has) + 12px bottom space according to the design

**Review by seanstrom — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Can you please rebase your PR?

**Review by jo-mut — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Issue on SE is fixed but new one appeared on bigger models (too big margin)

iPhone 13:

Screenshot 2024-03-06 at 13 50 58

**Comment by mohsen-ghafouri** [comment]
Thank you @mariia-skrypnyk for testing this PR, please check again.

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

iPhone is fixed thanks!

But I've compared 2 android builds: last one and previous (March 6) and on the last one I found such new issue:

**ISSUE 2: Avatar is too close to status bar**

Screenshot 2024-03-06 at 18 54 22

**ISSUE 3: bottom space under the join button on Android**

*it was not only at the last android build but I found it only now (sorry for this) while using dark theme.
I think iOS and Android should have the same bottom space. Let me know if it also works for you!

Screenshot 2024-03-06 at 18 49 33

**Comment by mohsen-ghafouri** [comment]
@mariia-skrypnyk for issue 3, in iOS there are more spaces above handler, as you can see the white area below the green section is safe area, we added the same padding(12px) in both iOS and android. 

image

for issue 2 i don't think it's related to my PR, I only apply changes to the bottom of "Request to join" screen, the screenshot doesn't seem to be related to this screen.

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk for issue 3, in iOS there are more spaces above handler, as you can see the white area below the green section is safe area, we added the same padding(12px) in both iOS and android.
> 
> image
> for issue 2 i don't think it's related to my PR, I only apply changes to the bottom of "Request to join" screen, the screenshot doesn't seem to be related to this screen.

Hi @mohsen-ghafouri !

Yes, I was not sure in issue 3.
I'll continue investigating issue 2 as it's not your interruption.
Thanks for explaining.
I'll move your PR to the design review.
@Francesca-G please, do not address status bar issue to this PR, I'll investigate it not here.
Screenshot 2024-03-06 at 18 54 22

**Review by Francesca-G — COMMENTED** [review]
Bottom margin doesn't match design, Figma comment [here](https://www.figma.com/file/18CoEYIaS6nbFxEpW1FX1M/Review-Communities-%2F-Mobile?type=design&node-id=54%3A27221&mode=design&t=IECBfOkETsCVeGwr-1)

Screenshot 2024-03-08 alle 13 59 47

**Comment by mohsen-ghafouri** [comment]
Hey @Francesca-G, thank you for reviewing this. please check this comment https://github.com/status-im/status-mobile/pull/18987#issuecomment-1981819806

this is safe area that provide by OS. we have this space also in other modals

**Review by Francesca-G — APPROVED** [review]
@mohsen-ghafouri apologies and thanks for the clarification 🙏

Looks good to me!
