### PR TITLE
[#21212] - Fix not joined options for token gated communities

### LINKED ISSUE #21212: Token gated community context drawer has wrong options
# Design Feedback 2.30

## Token gated community context drawer has wrong options
Pressing the _options_ button in a token gated community you're not a member of opens a context drawer with multiple wrong options that shouldn't be there from a UX perspective. 

#### Expected behavior

**Not joined, token gated** context drawer design [[Figma](https://www.figma.com/design/apCsJHT8J58JXbJD2igtbd/Context-Drawers-for-Mobile?node-id=791-275811&t=yNiQvqntpsdts3dx-1)]
>
Screenshot 2024-09-09 alle 09 06 58

#### Actual behavior

Screenshot 2024-09-09 alle 09 08 13

### Reproduction

1. Open a token gated community
2. Tap on the _options_ button at the top

### Additional Information

- Status version: 2.30
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21212

### Summary

This PR fixes a the options shown for token gated communities when the user isn't joined.

Options are now correct:

Additionally, changes the  "Mark as read" icon, we were using:

Screenshot from 2024-09-10 17-03-36

Now (as in figma):

Screenshot from 2024-09-10 17-03-46

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Create a new profile and visit a token gated communitiy, you can use this one:

https://status.app/c/G1EAAMTyFm0fBflGtiFYF5IgNAQzPiCADTgBCjTjlZ_tpjItNSiTKjz7Bvw2VF7r7XG_tFRcPsgFyoCnHC2MDzF5Bw==#zQ3shsQJt1uYuzLvQ1mpcDHSUnEYTV5wMmtzkoqER8kezGqAE

- Click on the 3 dots button and check the modal

status: ready

### CODE REVIEW

File: src/status_im/contexts/communities/actions/community_options/view.cljs [hunk 1]
```diff
@@ -137,13 +137,11 @@
...
-    (mark-as-read id)
-    (invite-contacts id)
-    (when token-gated? (view-token-gating id))
-    (show-qr id)
-    (share-community id)]])
+  (let [common   [(show-qr id) (share-community id)]
+        specific (if token-gated?
+                   [(invite-contacts id) (view-token-gating id)]
+                   [(view-members id) (view-rules id intro-message) (invite-contacts id)])]
+    [(concat specific common)]))
```
Comment (ulisesmac) [inline src/status_im/contexts/communities/actions/community_options/view.cljs]: When the user isn't joined we also showed the "Mark as read" button, but it's was wrong, here I'm also fixing it

**Review by ilmotta — APPROVED** [review]
Little by little, one less 🐛

**Review by seanstrom — APPROVED** [review]
Nice stuff ✅

**Comment by ulisesmac** [comment]
Hi @Francesca-G !
Could you please give it a check?

**Review by Francesca-G — COMMENTED** [review]
@ulisesmac it looks good to me, except the _"View token requirements"_ option isn't showing up in the drawer


Screenshot 2024-09-16 alle 13 34 49


>
I used the linked community to test

**Comment by mariia-skrypnyk** [comment]
Hey @ulisesmac @Francesca-G !

I also do not see "View token requirements" option neither on community from description no my testing token gated one.

**Comment by ulisesmac** [comment]
@Francesca-G @mariia-skrypnyk 

I've just checked it, the token gating was under a `show not implemeted features` flag, introduced in this PR:
https://github.com/status-im/status-mobile/pull/20240#issue-2322970873, so it wasn't shown.

Now, we need to __disable the test networks for the wallet__ and the option will appear.

Please give it a second check. Thank you.

**Comment by mariia-skrypnyk** [comment]
@ulisesmac Thanks, looks good from my side.

@Francesca-G please, check. 🙏

**Review by Francesca-G — APPROVED** [review]
thank you for the fix, looks good 👍
