### PR TITLE
Onboarding screens

### LINKED ISSUE #17129: Onboarding navigation issues
- [ ] ISSUE 1: Screens overlay when changing theme on the `Identifiers` / `Enable notifications` / `Welcome to web3` screens
- [ ] ISSUE 2: The created user is lost when going back from the `Identifiers` screen using the `swipe to the right` gesture (only Android with gestures enabled)
- [ ] ISSUE 3: The `back` button on the `Enable notifications` screen doesn't work 
- [ ] ISSUE 4: Extra `back` button on the `Enable biometrics` screen

Please let me know if some of these issues should be logged and fixed separately. 

# Bug Report

### ISSUE 1: Screens overlay when changing theme on the `Identifiers` / `Enable notifications` / `Welcome to web3` screens

**Steps:**
1. Install Status
2. Start creating a profile
3. Change mode from light to dark or vice versa on the `Identifiers` (`Enable notifications` / `Welcome to web3`)

**OS:** Android, iOS

https://github.com/status-im/status-mobile/assets/67952253/c78b70c0-6d57-431f-8051-ec8e90a96c10

### ISSUE 2: The created user is lost when going back from the `Identifiers` screen using the system back button or the `swipe to the right` gesture (only Android with gestures enabled)

**Steps:**
1. Enable gesture navigation/3-button navigation on your Android device
2. Start creating a profile
3. Right swipe on the `Identifiers` screen

**Expected result:** nothing happens, the gesture doesn't work here
**Actual result:** the `Intro` screen is opened, the created data is lost

**OS:** Android

System button: 
Screenshot 2023-08-31 at 15 06 57

Gesture:

https://github.com/status-im/status-mobile/assets/67952253/ca0e138f-7073-4898-9338-3608ac4c7e8b

### ISSUE 3: The `back` button on the `Enable notifications` screen doesn't work 

**Steps:**
1. Start creating a profile
2. On the `Enable notifications` screen tap the back button

**OS:** Android, iOS

Button in the designs: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=4338-515458&mode=design&t=pryPMWb6qYQxgOAR-4 

https://github.com/status-im/status-mobile/assets/67952253/26587f1b-cf8a-4de8-b693-24f8f7cb3d32

### ISSUE 4: Extra `back` button on the `Enable biometrics` screen

1. Start creating a profile
2. Check the back button on the `Enable biometrics` screen

**Expected result:** no back button on the screen
**Actual result:** button is added

**OS:** Android, iOS

Figma: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2884-327682&mode=design&t=pryPMWb6qYQxgOAR-4

https://github.com/status-im/status-mobile/assets/67952253/0d26e33f-a68f-49f9-9a11-76406d9a939c

### LINKED ISSUE #17151: Onboarding Flow - Layout issues in enable biometrics screen
# Problem
On Android - Elements in the onboarding flow - enable biometrics screen is not aligned as per design.
On iOS - The heading and description text is missing

Design: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2926-332255&mode=design&t=Wo8Pl9yEe4dzsNPC-4

### Screenshots

Android | iOS
-|-
 |

### LINKED ISSUE #17152: Onboarding screens layout is broken
Reproducing on IOS 16.6 iPhoneX; Android 12, Samsung Galaxy A52

1. Enable biometrics screen

photo_2023-08-31 11 05 25

2. Enable notifications screen

photo_2023-08-31 11 05 15

3. Welcome screen

photo_2023-08-31 11 05 17

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #17155: Broken back navigation on "Create profile" screen
Initially reported and fixed [here](https://github.com/status-im/status-mobile/pull/17031#issuecomment-1686031877) but for some reason bug appeared in develop after PR merge. cc @ulisesmac 

**Steps:**

1. Proceed to "Create profile" onboarding screen
2. Tap back button
3. See if user is redirected to previous step

**Actual result:** user is redirected to empty screen

https://github.com/status-im/status-mobile/assets/97245802/a95c7343-d81a-4483-9cc8-58c4ad3924ee

**Expected result:** user is redirected to previous step

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #17152
fixes #17151
fixes #17129
fixes #17155

### CODE REVIEW

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the PR. 

### ISSUE 1 Camera can not be enabled on Sign in screen

**Steps:** 

1. Open Sign in screen
2. Enable camera
3. See if camera is enabled

**Actual result:** camera is not enabled. Cannot scan QR. 


https://github.com/status-im/status-mobile/assets/97245802/4aa881fe-0709-4dee-9c19-da0b0c15c3d0

**Comment by pavloburykh** [comment]
### ISSUE 2 Wrong top margin on Enable biometrics screen

Reproduced on iPhone X IOS 16.6; Samsung Galaxy A52, Android 12

**Actual result:**

photo_2023-09-01 16 43 25

**Expected result:** 

[Figma](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2884-327682&mode=design&t=bbf7XKDhJSibJPAL-0)

Onboarding for Mobile – Figma 2023-09-01 16-44-21

**Comment by pavloburykh** [comment]
### ISSUE 3 Screens overlay when changing theme on the `Identifiers` / `Enable notifications` / `Welcome to web3` screens

@flexsurfer still reproducible. Initially Reported [here](https://github.com/status-im/status-mobile/issues/17129#issue-1869656504) as issue 1. Please see updated steps. 

**Steps:**
1. Install Status
2. Create first account
3. Proceed with creating second account on this device
5. Change mode from light to dark or vice versa on the `Identifiers` (`Enable notifications` / `Welcome to web3`) during creating of the second account

**OS:** Android, iOS


https://github.com/status-im/status-mobile/assets/97245802/66648c5f-cd9d-4901-8fbb-02c52b2f377f

**Comment by J-Son89** [comment]
@pavloburykh is the theme issue just in this or it's in develop too? I have another pr looking at theming and might have a general fix for this if so

**Comment by pavloburykh** [comment]
> @pavloburykh is the theme issue just in this or it's in develop too? I have another pr looking at theming and might have a general fix for this if so

it is in develop. It was reported here https://github.com/status-im/status-mobile/issues/17129. This PR claimed to fix the issue, that's why I mention it here.

**Comment by pavloburykh** [comment]
@J-Son89 BTW, if you have capacity could you please review and approve current PR. I started testing before approval in order to save time as we need this PR for branch cut.

File: src/quo2/components/text_combinations/style.cljs [hunk 1]
```diff
@@ -2,14 +2,10 @@
 
 (defn container
   [container-style]
-  (merge
-   {:flex              1
-    :margin-horizontal 20}
-   container-style))
+  (assoc container-style :margin-horizontal 20))
```
Comment (J-Son89) [inline src/quo2/components/text_combinations/style.cljs:5]: I think we should leave this as merge because we want to be able to overwrite the defaults imo. Otherwise the `container-style` prop does not function as expected. 
Or perhaps I have misinterpreted how `assoc` works. 
In any case `container-style` should be able to overwrite defaults

File: src/status_im2/contexts/onboarding/common/overlay/view.cljs [hunk 2]
```diff
@@ -45,9 +45,12 @@
         max-blur-amount
         2))))
 
+;; we had to register it here, because of hotreload, overwise on hotreload it will be reseted
+(defonce blur-amount (reagent/atom 0))
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/common/overlay/view.cljs:50]: is it possible to mark this private so it doesn't get used outside this file at least? 🤔

File: src/status_im2/contexts/onboarding/enable_notifications/view.cljs [hunk 3]
```diff
@@ -52,7 +52,7 @@
      [quo/page-nav
       {:background :blur
        :icon-name  :i/arrow-left
-       :on-press   #(rf/dispatch [:navigate-back-within-stack :identifiers])}]
+       :on-press   #(rf/dispatch [:navigate-back-within-stack :new-to-status])}]
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/enable_notifications/view.cljs:55]: I understand this is probably already discussed with designers etc, but seems odd to jump back to that page from enable_notications 🤔

File: src/status_im2/contexts/onboarding/intro/events.cljs [hunk 4]
```diff
@@ -0,0 +1,12 @@
+(ns status-im2.contexts.onboarding.intro.events
+  (:require [utils.re-frame :as rf]
+            [status-im2.contexts.onboarding.common.overlay.view :as overlay]
+            [status-im2.contexts.profile.profiles.view :as profiles]))
+
+(rf/defn intro-on-focus
+  {:events [:onboarding/intro-on-focus]}
+  [_]
+  (when @overlay/blur-dismiss-fn-atom
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/intro/events.cljs]: this is a ratom right? can't we pass this as a prop instead? 🤔

File: src/status_im2/navigation/core.cljs [hunk 5]
```diff
@@ -167,18 +167,11 @@
...
 (navigation/reg-button-pressed-listener
  (fn [id]
-   (cond
-     (= "dismiss-modal" id)
+   (if (= "dismiss-modal" id)
      (do
        (when-let [event (get-in views/screens [(last @state/modals) :on-dissmiss])]
          (re-frame/dispatch event))
        (dissmissModal))
-     (= "RNN.hardwareBackButton" id)
```
Comment (J-Son89) [inline src/status_im2/navigation/core.cljs:176]: do we not these for android devices back button?

File: src/status_im2/contexts/onboarding/enable_notifications/view.cljs (hunk 3 above)
Comment (briansztamfater) [reply src/status_im2/contexts/onboarding/enable_notifications/view.cljs:55]: It's the component id required by react-native-navigation to specify a stack, so it would pop to the previous screen in the stack where the component id is located, not to `:new-to-status`. The thing is that probably there is no new-to-status component in the stack if the user initiates the process from the account selection screen and not from the welcome screen in the onboarding, so we need to check if this works for that case.

**Comment by pavloburykh** [comment]
### ISSUE 4 Broken back navigation on "Create profile" screen

https://github.com/status-im/status-mobile/issues/17155 is fixed partially

Still reproducible with following **steps:**

**Preconditions:** at least 1 account is already created

1. Logout
2. Open Profiles list screen
3. Tap +
4. Select Create Profile
5. Tap back on Create profile screen
6. Observe the result

**Actual result:** user is redirected to empty screen


https://github.com/status-im/status-mobile/assets/97245802/cbe8e28d-5da5-4980-a70a-31661198f5f3

**Comment by pavloburykh** [comment]
### ISSUE 5 Onboarding layout is broken after returning from background (Android)

Reproduced on Android 12, Samsung Galaxy A52

**Steps:** 

1. Open app from the first onboarding page
2. Tap "I'm new to Status"
3. Background app
4. Return from background
5. Observe the result

**Actual result:** layout is broken 


https://github.com/status-im/status-mobile/assets/97245802/5be9c065-1d7a-44d0-b522-6648a1c8e093

**Comment by flexsurfer** [comment]
- [x] ISSUE 1 Camera can not be enabled on Sign in screen
- [x] ISSUE 2 Wrong top margin on Enable biometrics screen
- [x] ISSUE 3 Screens overlay when changing theme on the Identifiers / Enable notifications / Welcome to web3 screens
- [x] ISSUE 4 Broken back navigation on "Create profile" screen
- [x] ISSUE 5 Onboarding layout is broken after returning from background (Android)

File: src/status_im2/navigation/core.cljs (hunk 5 above)
Comment (flexsurfer) [reply src/status_im2/navigation/core.cljs:176]: this was kinda a hack, there is a proper way to listen to navigate back button

File: src/status_im2/contexts/onboarding/intro/events.cljs (hunk 4 above)
Comment (flexsurfer) [reply src/status_im2/contexts/onboarding/intro/events.cljs]: im trying to do my best, entire navigation is broken now, im just trying to fix it step by step

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/intro/events.cljs]: Yes I agree, navigation needs a lot of work. Perhaps we can start to improve this soon and figure what are the issues.

But still I don't see how using a global ratom inside a function is helping? Is it not possible to the same yet pass the ratom as a prop so at least this function remains pure ?

Comment (flexsurfer) [reply src/status_im2/contexts/onboarding/intro/events.cljs]: yes its a wrong implementation,its not possible to fix it without atom, but in proper implementation there should be no atom at all

Comment (J-Son89) [reply src/status_im2/contexts/onboarding/intro/events.cljs]: Sounds good 👍

**Review by J-Son89 — APPROVED** [review]

**Comment by flexsurfer** [comment]
thanks @pavloburykh all should be fixed now

**Review by briansztamfater — APPROVED** [review]

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the fixes. 

### ISSUE 6 Broken layout after re-opening I'm new to Status screen (IOS only)

Reproducing on IOS 16.6, iPhoneX 

**Steps:** 

1. Open Status app on initial onboarding screen
2. Open I'm new to Status screen
3. Go back
4. Open I'm new to Status screen again
5. Observe the result

**Actual result:** layout is broken


https://github.com/status-im/status-mobile/assets/97245802/0e75c8e1-dfd5-404b-a529-fd263f686a7b

**Comment by flexsurfer** [comment]
thanks @pavloburykh fixed

**Comment by pavloburykh** [comment]
@flexsurfer thanks for the PR. Failed e2e are not PR related. Ready for merge.

File: src/quo2/components/text_combinations/style.cljs (hunk 1 above)
Comment (J-Son89) [reply src/quo2/components/text_combinations/style.cljs:5]: @flexsurfer, curious of why you didn't change this? there are several uses of `container-style` prop for this component and so this can effect them.
imo it's better to set margins on the component where it's being used, otherwise we tend to be fighting with margins on the page it's being used.

Comment (flexsurfer) [reply src/quo2/components/text_combinations/style.cljs:5]: i did but in another PR https://github.com/status-im/status-mobile/pull/17215
