### PR TITLE
[Fix] Incorrect navigation to message reaction bottom sheet

### LINKED ISSUE #16184: Incorrect navigation to different reaction on 'who sent' screen after long tap
### Problem:
After performing a long tap on a specific reaction in a message, the user is navigated to a different reaction in the 'who sent' screen instead of the intended reaction.

### Steps to Reproduce:
1. Open any chat.
2. Leave a reaction on a message.
3. Long tap the reaction 
4. Check which reaction is shown as selected in the 'who sent' page.

### Actual Behavior:
The long-tapped reaction is not visually marked as selected in the 'who sent' page

(see on record. 
- In sec 3 the  👎 is long tapped, but the  👍 is selected instead. 
- On 26 second 😄 is long tapped, but   👎 is selected instead)

https://github.com/status-im/status-mobile/assets/52490791/8d6150fa-bd1e-4349-be32-a71661ca3967

### Expected Behavior:
The long-tapped reaction should be visually marked as selected in the 'who sent' page.

### Additional info:
Reproduced in 10% of cases. Try randomly long tap a few reactions to reproduce

### ENV:
- Nightly 5 Jun 2023

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #16184

### Summary

This PR fixes the incorrect navigation of the message reaction bottom sheet by ensuring the bottom sheet opens only on successful retrieval of message reaction data. 

### Platforms

- Android
- iOS

### Steps to test

- Open any chat
- Leave a reaction to a message
- Long press on any reaction to open the reaction author's bottom sheet
- Check if the reaction which is long pressed is shown as selected

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/messages/drawers/view.cljs
Comment (smohamedjavid) [inline src/status_im2/contexts/chat/messages/drawers/view.cljs:1]: Kindly Ignore these file changes for review, as this is just `lint` organised the imports.

File: src/status_im/chat/models/reactions.cljs [hunk 1]
```diff
@@ -5,7 +5,8 @@
             [status-im.transport.message.protocol :as message.protocol]
             [utils.re-frame :as rf]
             [taoensso.timbre :as log]
-            [utils.transforms :as transforms]))
+            [utils.transforms :as transforms]
+            [status-im2.contexts.chat.messages.drawers.view :as drawers]))
```
Comment (ibrkhalil) [inline src/status_im/chat/models/reactions.cljs]: Is it okay to use view namespaces in `model/events` ?
CC: @flexsurfer

**Review by ibrkhalil — COMMENTED** [review]
Thanks for the fix Mohamed!

File: src/status_im/chat/models/reactions.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/chat/models/reactions.cljs]: better to pass it as parameter in the event
`dispatch [chat/save-and-open-emoji-reaction-details (fn [] [drawers/reaction-authors reactions])`

File: src/status_im/chat/models/reactions.cljs [hunk 2]
```diff
@@ -104,33 +105,43 @@
...
+  [{:keys [db]} {:keys [message-id] :as opts}]
+  {:db            (dissoc db :chat/reactions-authors)
+   :json-rpc/call [{:method      "wakuext_emojiReactionsByChatIDMessageID"
                     :params      [(:current-chat-id db) message-id]
                     :js-response true
                     :on-error    #(log/error "failed to fetch emoji reaction by message-id: "
                                              {:message-id message-id :error %})
-                    :on-success  #(rf/dispatch [:chat/save-emoji-reaction-details
-                                                (format-response %) long-pressed-emoji])}]})
+                    :on-success  #(rf/dispatch [:chat/save-and-open-emoji-reaction-details
```
Comment (flexsurfer) [inline src/status_im/chat/models/reactions.cljs]: yeah so we need to pass on-success as parameter

File: src/status_im/chat/models/reactions.cljs (hunk 1 above)
Comment (smohamedjavid) [reply src/status_im/chat/models/reactions.cljs]: Updated

**Review by ibrkhalil — APPROVED** [review]

File: src/status_im2/contexts/chat/messages/content/reactions/view.cljs [hunk 3]
```diff
@@ -17,25 +17,14 @@
...
-                                 (map :emoji-id reactions)])
-     :selected-item           (fn []
-                                user-message-content)
-     :padding-bottom-override 0}]))
+                {:message-id           message-id
+                 :long-pressed-emoji   emoji-id
+                 :drawer-content       (fn []
+                                         [drawers/reaction-authors reactions])
+                 :user-message-content (fn []
+                                         user-message-content)}]))
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/content/reactions/view.cljs]:
```clojure
(rf/dispatch [:chat.ui/emoji-reactions-by-message-id
                {:message-id           message-id
                 :long-pressed-emoji   emoji-id
                 :on-succes (fn []
                             (rf/dispatch [:chat/save-emoji-reaction-details])
                             (rf/dispatch [:dismiss-keyboard])
                             (rf/dispatch [:show-bottom-sheet])

```

better to do like this, because its not clear why we pass `drawer-content` into `emoji-reactions-by-message-id` which should just update emoji in app-db

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/messages/content/reactions/view.cljs:27]: > ```clojure
> (rf/dispatch [:chat.ui/emoji-reactions-by-message-id
>                 {:message-id           message-id
>                  :long-pressed-emoji   emoji-id
>                  :on-succes (fn []
>                              (rf/dispatch [:chat/save-emoji-reaction-details])
>                              (rf/dispatch [:dismiss-keyboard])
>                              (rf/dispatch [:show-bottom-sheet])
> ```
> 
> better to do like this, because its not clear why we pass `drawer-content` into `emoji-reactions-by-message-id` which should just update emoji in app-db

```suggestion
(rf/dispatch [:chat.ui/emoji-reactions-by-message-id
                {:message-id           message-id
                 :long-pressed-emoji   emoji-id
                 :on-success (fn []
                             (rf/dispatch [:chat/save-emoji-reaction-details])
                             (rf/dispatch [:dismiss-keyboard])
                             (rf/dispatch [:show-bottom-sheet])
```

File: src/status_im2/contexts/chat/messages/drawers/view.cljs [hunk 4]
```diff
@@ -1,16 +1,16 @@
 (ns status-im2.contexts.chat.messages.drawers.view
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/messages/drawers/view.cljs]: pls rollback this file

**Review by flexsurfer — APPROVED** [review]
perfecto! thank you

**Review by ajayesivan — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fix and for your great work @smohamedjavid!
PR can be merged.
