### PR TITLE
[#17518] fix: try again when sync has error outside the onboarding flow

### LINKED ISSUE #17518: The app becomes stuck on sync process and 'logged in keyID not the same as keyUID in payload' error is shown when syncing via profile
### Steps:
1. User A: Generates a QR sync code (mobile or desktop user, no matter)
2. User B: Goes to Syncing  -> tap [+] -> Scan or enter sync code (now the "Oops, something went wrong" screen is shown with 'logged in keyID not the same as keyUID in payload' error)
3. Tap 'try again' button

### Actual result:
-  'logged in keyID not the same as keyUID in payload' error shown after syncing
- The app is stuck on sync process

https://github.com/status-im/status-mobile/assets/52490791/dddc0b4b-0ec9-4272-b8f5-6e22bf558a86

### Expected result:
Error should be shown and user should be able to sync new QR

### Device:
- IOS and Android

### ENV:
[4 Oct 2023]

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12803414/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17518

### Summary

try again button logic is wrong when user is not in onboarding flow and also we shouldn't show the toast message when the 'Oops something went wrong' page is displayed

### Steps to test

1. User A: Generates a QR sync code (mobile or desktop user, no matter)
2. User B: Goes to Syncing -> tap [+] -> Scan or enter sync code (now the "Oops, something went wrong" screen is shown with 'logged in keyID not the same as keyUID in payload' error)
3. Tap 'try again' button

### Result

https://github.com/status-im/status-mobile/assets/71308738/3359e1f5-cf52-4e75-885b-a69697dff94d

status: ready

### CODE REVIEW

File: src/status_im/signals/core.cljs [hunk 1]
```diff
@@ -79,13 +78,7 @@
              {:dispatch [:syncing/clear-states]}
 
              (and completed-pairing? receiver?)
-             {:dispatch [:profile.login/local-paired-user]}
-
-             (and error-on-pairing? (some? error))
-             {:dispatch [:toasts/upsert
-                         {:icon       :i/alert
-                          :icon-color colors/danger-50
-                          :text       error}]}))))
```
Comment (ibrkhalil) [inline src/status_im/signals/core.cljs]: Can we double check with design if we want to remove the toast?

**Review by ibrkhalil — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

File: src/status_im/signals/core.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/signals/core.cljs]: according to design flow and @VolodLytvynenko's comment it doesn't require any toast, [Figma](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=3450-354380&mode=design&t=miSAbq1JaEDdWPPK-4)

Comment (mohsen-ghafouri) [reply src/status_im/signals/core.cljs]: @ibrkhalil i revert this part, as QA team confirmed we should keep it

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri Thank you for the PR. I encountered an issue where the sync process page gets stuck when the 'try again' button is tapped. Unfortunately, this problem doesn't have exact steps and occurs randomly. I hope the logs can help understand what's going on. Could you please take a look

### Steps: 
1. `User A **IOS**` generate the sync QR code
2. `User B **Android**` scans the QR code during onboarding
3. `User B **Android**` log out and scans the QR code once more time (now the 'try again' button is shown)
4. `User B **Android**` taps 'try again' button

### Actual result:
The user is stuck on the 'syncing devices' page
https://github.com/status-im/status-mobile/assets/52490791/03c0e947-8784-411f-bc23-52282c7eee15


### Expected result:
The user is navigated to the scan page

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13335764/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
One question: Is it possible to fix the next issue within the scope of this PR, or would it be better to address it separately?

## ISSUE 2: [ANDROID] The camera is not activated when trying to scan again after an invalid QR code is scanned.

### Preconditions:
`device 1` and `device 2` are on the different networks


### Steps:
1. `Device 2 android` scans generated on `Device 1`
2. `Device 2 android` taps the 'try again' button


### Actual result:
`Device 2` is navigated to the scan screen, the camera is not activated in the scan section

https://github.com/status-im/status-mobile/assets/52490791/48ccfaee-0665-4f6c-810f-84debb4f6087


### Expected result:
`Device 2` should be navigated to the scan screen, the camera should be activated in the scan section, and the user should be able to try scanning once more.

**Comment by mohsen-ghafouri** [comment]
I will check it @VolodLytvynenko

File: src/status_im2/contexts/syncing/scan_sync_code/view.cljs [hunk 2]
```diff
@@ -299,8 +299,7 @@
                                          @preflight-check-passed?
                                          (boolean (not-empty @qr-view-finder)))
             camera-ready-to-scan?   (and (or (not animated?) @render-camera?)
-                                         show-camera?
-                                         (not @qr-code-succeed?))
```
Comment (mohsen-ghafouri) [inline src/status_im2/contexts/syncing/scan_sync_code/view.cljs]: @flexsurfer to resolve one issue i have to remove this condition. could you remember any reason to keep this condition here?

File: src/status_im2/contexts/onboarding/syncing/progress/view.cljs [hunk 3]
```diff
@@ -25,12 +25,15 @@
...
   [quo/button
    {:on-press            (fn []
                            (rf/dispatch [:syncing/clear-states])
-                           (rf/dispatch [:navigate-back-to
-                                         (if in-onboarding? :sign-in-intro :sign-in)]))
+                           (rf/dispatch (cond
+                                          logged-in?     [:navigate-back]
+                                          in-onboarding? [:navigate-back-to :sign-in-intro]
+                                          :else          [:navigate-replace :sign-in]
+                                        )))
```
Comment (ilmotta) [inline src/status_im2/contexts/onboarding/syncing/progress/view.cljs]: The closing parentheses should be on the previous line.

**Review by ilmotta — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko could you please test again.

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri thanx for the fixes. Issue 1,2 are fixed. One additional issue is introduced:

##  ISSUE 3: The sync process starts only after the camera is moved away from the sync QR code.
### Step:
1. Point the camera at the QR code and leave it for approximately 10-15 seconds.
2. Move the camera away from the QR code.

### Actual result:
The sync process starts only after the camera has moved away from the QR code.

https://github.com/status-im/status-mobile/assets/52490791/72832ca0-3350-4662-817e-9c956dc5c5aa


### Expected result:
The sync process should commence immediately upon the camera detecting and hovering over the sync QR code.


### Logs:

[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13377963/Status-debug-logs.1.zip)


### Device:
Pixel 7a, Android 13

**Comment by VolodLytvynenko** [comment]
One more issue, but it would be alright if it were fixed separately in a follow-up

### ISSUE 4: [Android] Sync process doesn't restart on rescanning QR after 'try again' button is tapped

### Steps:
1. `User A` Generates QR code 
2. `User B Android` is on a different network
3. `User B Android` scans the QR (now the 'Oops something went wrong' page is shown)
4. `User B Android` taps 'try again' button and scans QR code one more time

### Actual result:
After tapping 'Try Again' and rescanning the QR code, the sync process does not start


https://github.com/status-im/status-mobile/assets/52490791/7021ad00-1e10-44a6-9bae-251f5d141e58


### Expected result:
The sync process feedback should be provided

### Logs:
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/13380067/Status-debug-logs.2.zip)

**Comment by mohsen-ghafouri** [comment]
Thanks for testing this @VolodLytvynenko i will check them

**Comment by mohsen-ghafouri** [comment]
I tried to record a video but in recorded video it shows screen black, i don't know if we have something in status-mobile to prevent from screenshot/recording or my android phone sucks, could you please test again i resolved both issues @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> I tried to record a video but in recorded video it shows screen black, i don't know if we have something in status-mobile to prevent from screenshot/recording or my android phone sucks, 

Hi @mohsen-ghafouri Probably in your build, you have enabled 'Blocks screenshots' toggle. 
To check it go to: Profile -> Privacy and security ->  Blocks screenshots
image


> could you please test again i resolved both issues @VolodLytvynenko

Thank you for the fixes. Will check it now.

**Comment by mohsen-ghafouri** [comment]
Thanks @VolodLytvynenko , Here is the result,  Initially, the system syncs correctly. However, upon attempting to scan an older QR code, it triggers the failure flow: 


https://github.com/status-im/status-mobile/assets/71308738/8952e443-37fe-4c01-9ed8-edab3545f903

File: src/status_im/signals/core.cljs [hunk 4]
```diff
@@ -53,8 +55,9 @@
                                              (and (some? account) (some? password)))
         multiaccount-data               (when received-account?
                                           (merge account {:password password}))
-        navigate-to-syncing-devices?    (and (or connection-success? error-on-pairing?) receiver?)
```
Comment (smohamedjavid) [inline src/status_im/signals/core.cljs]: @mohsen-ghafouri - the `error-on-pairing?` flag does include the connection error check too along with other errors.

Comment (mohsen-ghafouri) [reply src/status_im/signals/core.cljs]: @smohamedjavid yes but if we had connection-error + other errors it will call navigate multiple times, so to avoid that i just want to check connection status

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri thank you for the fixes, and apologizes for the delay in testing. The QA team was busy with the recent release
The additional issues are found:

## ISSUE 5: [Android] No response when scanning in the same network after different network attempt

### Steps:
1. `Device 1` and `Device 2` are on the different networks
2. `Device 1` scans QR code generated on `Device 2` (now 'oops something went wrong' screen is shown)
3. `Device 1` switch on to the same network  as `Device 2`
4. `Device 1` scans the QR of  `Device 2` once more time

### Actual result:
No response is displayed after performing the second scan with Device 1.


https://github.com/status-im/status-mobile/assets/52490791/def2688f-6779-42ea-8e1e-6a756869c111

### Expected result:
The devices are synced or the response should be shown if something goes wrong

### logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13474798/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
## ISSUE 6: [IOS] No response on iOS when scanning in different networks

### Steps:
1. `Device 1 [ios]` and `Device 2` are on the different networks
2. `Device 1 [ios]` scans the QR code generated on `Device 2` 

### Actual result:
The camera picture is not displayed in the 'scan' section when attempting to scan the QR code.

https://github.com/status-im/status-mobile/assets/52490791/5c2d7a36-3700-45aa-bbe6-68e3d5633828



### Expected result:
After scanning, a response indicating unsuccessful syncing is shown

### Additional info:
Unfortunately can't provide logs in for IOS on the sync page. The share logs button does not work

**Comment by VolodLytvynenko** [comment]
## ISSUE 7: [IOS] Camera process persists after 'Oops Something Went Wrong' on iOS

### Steps:
1. `Device 1` generates a QR code that has been used once before.
2. `Device 2` scans the QR code generated by Device 1.
3. While the 'Oops Something Went Wrong' page is displayed, keep the camera pointed at the QR code from `Device 1`.

### Actual result:
The syncing process persists and continues attempting to sync while the camera is still focused on the QR code.

https://github.com/status-im/status-mobile/assets/52490791/d8a9debe-70c3-4ed7-9df3-2d810eaf90cd


### Expected result:
The syncing process should not attempt further steps when the 'Oops Something Went Wrong' page is displayed.


### Logs:
[logs (2).zip](https://github.com/status-im/status-mobile/files/13476109/logs.2.zip)

**Comment by mohsen-ghafouri** [comment]
Thank you @VolodLytvynenko , i will check them

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko could you please check again?

**Comment by VolodLytvynenko** [comment]
## ISSUE 8: [IOS]'Try Again' Button requires double tap on iOS after scanning  QR Code when users are on different networks; or scans has already used QR

### Steps:
1. `User A` operates on a different network than `User B` on iOS or `User A` generates a QR code that has already been used.
2. `User B` on iOS scans the QR code.
3. `User B` on iOS taps the 'Try again' button.

### Actual result:
Upon tapping the 'Try again' button only once, the 'Oops, something went wrong' page remains displayed.

https://github.com/status-im/status-mobile/assets/52490791/f91ead14-c7f9-4fb2-99d7-930986620816

### Expected result:
After tapping the 'Try again' button once, the user should be seamlessly redirected to the camera scanning page

### logs:
[logs.zip](https://github.com/status-im/status-mobile/files/13598695/logs.zip)

**Comment by VolodLytvynenko** [comment]
## ISSUE 9: [IOS] Camera not enabled after 'Try Again' button is tapped  when scanning QR code from different networks

### Steps:
1. `User A` operates on a different network than `User B`
2. `User B` on iOS scans the QR code.
3. `User B` on iOS taps the 'Try again' button, intending to redirect to the 'Scan QR code' page.


### Actual result:
The camera section remains disabled, displaying a grayed-out area

https://github.com/status-im/status-mobile/assets/52490791/76df75fd-5010-4448-bf43-b457e1a6a669

### Expected result:
The camera functionality should be re-enabled

### logs:
[logs.zip](https://github.com/status-im/status-mobile/files/13598695/logs.zip)

**Comment by VolodLytvynenko** [comment]
## ISSUE 10:  iOS app gets stuck on syncing devices process when no network connection
### Steps:
1. `User A` generates valid sync QR code
2. `User B` on IOS has no net connection
3. `User B` scans the QR

### Actual result:
Upon scanning the QR code without an internet connection, 'User B' becomes stuck on the syncing devices process page
image

### Expected result:
Something went wrong page should be shown for `User B` 

[logs (2).zip](https://github.com/status-im/status-mobile/files/13598697/logs.2.zip)

**Comment by VolodLytvynenko** [comment]
## ISSUE 11 [Android] Lack feedback  when scanning QR codes from different networks
### Steps:
1. `User B` on Android different net connection with `User A`
2. `User A` generates valid sync QR code
3. `User B`scans the QR
4. `User B`tap 'try again' button
5. `User B` scans the QR one more time

### Actual result:
Upon rescanning the QR code after tapping 'Try again,' the feedback is not shown to 'User B.'

https://github.com/status-im/status-mobile/assets/52490791/7150cf9c-4265-4de0-8a10-1a88267ab840

### Expected result:
The 'something went wrong' page should be shown

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13598892/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
## ISSUE 12:iOS App gets stuck on syncing devices process when scanning used QR code or on different networks
### Preconditions:
- `User A` is recovered on both `Device 1`  `Device 2` devices;
-  During onboarding both users used the same password

### Steps:
`Device 1`  on the different net connection with `User B` or `User A` generated sync QR that has already been used
`Device 2` On IOS goes to "Syncing" -> [+] button -> tap 'Scan or enter sync code code' ->  scans the QR code
`Device 2` tap 'try again' button

### Actual result:
iOS app gets stuck on syncing devices process page


https://github.com/status-im/status-mobile/assets/52490791/134268f3-c90e-4724-bcc3-a8f76fee2f0a



### Expected result:
iOS app returns to the Scan sync code page

### Logs:
[logs (4).zip](https://github.com/status-im/status-mobile/files/13599613/logs.4.zip)

**Comment by VolodLytvynenko** [comment]
Hey @mohsen-ghafouri thank you for PR. I think only the https://github.com/status-im/status-mobile/pull/17890#issuecomment-1845210552 can be fixed in scope of this PR. The remaining issues (8-11) can be addressed separately, up to you. WDYT?

**Comment by mohsen-ghafouri** [comment]
Thanks, @VolodLytvynenko, for reviewing this PR. From what I understand, these issues might be related to one single source (different network problems). I'll experiment with some scenarios.

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko after rebasing with latest changes on dev, I couldn't reproduce the issues. in both platform when user A and B are on different network , try again button works fine. in scope of this PR i couldn't find any further issue. could you please check ? 

### iOS
https://github.com/status-im/status-mobile/assets/71308738/d688384b-597d-41c3-9188-f538b2a88d95

### Android
https://github.com/status-im/status-mobile/assets/71308738/c39e0820-89fa-472b-98c3-5a120a65c92e

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko after rebasing with latest changes on dev, I couldn't reproduce the issues. in both platform when user A and B are on different network , try again button works fine. in scope of this PR i couldn't find any further issue. could you please check ?

Hi @mohsen-ghafouri indeed. The all issues are not reproducible for me anymore and PR is ready to be merged. Thank you for your work!
