### PR TITLE
fix: prevent adding more participants than the allowed group chat limit

### LINKED ISSUE #21590: Admin/Member can add more than 20 users to group chat after creation
# Bug Report

## Problem 
After creating a group chat with 20 users (the maximum allowed), it is still possible for an admin or member to add additional users, exceeding the limit of 20.

### Reproduction
1. Create a new group chat and add exactly 20 users.
2. After the group chat is created, attempt to add another user.

#### Expected behavior
The system should prevent adding more users to the group chat once it reaches the maximum limit of 20.

#### Actual behavior
An admin or member can add additional users to the group chat, exceeding the 20-user limit.
Image
Image

### Additional Information

- Status version: nightly  
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #21590 

## Summary
This PR addresses an issue where users were able to add more participants to a group chat than the allowed maximum(20). The new logic ensures that participant additions are validated against the group size limit, preventing overflows.

This PR also adds member count in the right side of Manage members header.

### Screenshots

https://github.com/user-attachments/assets/9a47c6bb-f281-4e89-94ea-3b20333fbbea

### Platforms
- Android
- iOS

#### Functional
- group chats

## Steps to test

- Open Status
- Create a group chat
- Open group chat
- Open group chat options -> Manage members
- Try adding more than 20 members

### Risk

Described potential risks and worst case scenarios.

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

File: src/status_im/contexts/chat/group/details/view.cljs [hunk 1]
```diff
@@ -15,6 +14,8 @@
     [utils.i18n :as i18n]
     [utils.re-frame :as rf]))
 
+(def ^:private maximum-selectable-contacts constants/max-group-chat-participants)
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/group/details/view.cljs]: What is the purpose of defining maximum-selectable-contacts?

File: src/status_im/contexts/chat/group/details/view.cljs [hunk 2]
```diff
@@ -26,27 +27,40 @@
...
-           item])))))
+  [{:keys [public-key] :as item} _ _ {:keys [group admin? current-pk chat-id set-has-error]}]
+  (let [{:keys [contacts]}      group
+        member?                 (contains? contacts public-key)
+        selected-contacts-count (rf/sub [:group-chat/manage-members-count chat-id])
+        [checked? set-checked]  (rn/use-state member?)
+        disabled?               (or (= current-pk public-key) (and (not admin?) member?))
+        on-toggle               (rn/use-callback
+                                 (fn [value]
+                                   (set-has-error false)
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/group/details/view.cljs]: better to move this logic to event ns, and use subscriptions for error state

File: src/status_im/subs/chats.cljs [hunk 3]
```diff
@@ -358,3 +358,14 @@
    (re-frame/subscribe [:chats/chat chat-id]))
  :->
  :image)
+
+(re-frame/reg-sub
+ :group-chat/manage-members-count
+ (fn [[_ chat-id]] [(re-frame/subscribe [:chats/chat-by-id chat-id])
+                    (re-frame/subscribe [:group-chat/selected-participants])
+                    (re-frame/subscribe [:group-chat/deselected-members])])
```
Comment (ulisesmac) [inline src/status_im/subs/chats.cljs]: This code style for functions is not common, please fix it

File: src/status_im/contexts/chat/group/details/view.cljs [hunk 4]
```diff
@@ -66,22 +82,35 @@
...
+       {:size   :heading-1
+        :weight :semi-bold}
+       (i18n/label (if admin? :t/manage-members :t/add-members))]
+      [quo/text
+       {:size   :paragraph-2
+        :weight :regular
+        :style  {:margin-bottom 2
+                 :color         (if has-error?
+                                  (colors/theme-colors colors/danger-50 colors/danger-60 theme)
+                                  (colors/theme-colors colors/neutral-40 colors/neutral-50 theme))}}
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/group/details/view.cljs]: Should be in the style ns :eyes:

File: src/status_im/contexts/chat/group/details/view.cljs [hunk 5]
```diff
@@ -56,7 +70,9 @@
         chat-id                    (quo.context/use-screen-params)
         {:keys [admins] :as group} (rf/sub [:chats/chat-by-id chat-id])
         current-pk                 (rf/sub [:multiaccount/public-key])
-        admin?                     (get admins current-pk)]
+        admin?                     (get admins current-pk)
+        selected-contacts-count    (rf/sub [:group-chat/manage-members-count chat-id])
+        [has-error? set-has-error] (rn/use-state false)]
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/group/details/view.cljs]: Hooks should be before anything, even before re-frame subs

File: src/status_im/contexts/chat/group/details/view.cljs (hunk 1 above)
Comment (ajayesivan) [reply src/status_im/contexts/chat/group/details/view.cljs]: Good catch - I initially added the `(dec)` to exclude the owner account from the selection count, but since we're displaying the owner as well, that adjustment became unnecessary. I missed removing it afterward. Thanks for pointing it out! I've cleaned it up now.

File: src/status_im/contexts/chat/group/details/view.cljs (hunk 2 above)
Comment (ajayesivan) [reply src/status_im/contexts/chat/group/details/view.cljs]: Done

File: src/status_im/subs/chats.cljs (hunk 3 above)
Comment (ajayesivan) [reply src/status_im/subs/chats.cljs]: I have updated the subscription to use `:<-` syntax. Please let me know if you had something else in mind.

**Comment by ajayesivan** [comment]
Thank you for the reviews @flexsurfer & @ulisesmac!

I have updated the PR with suggested changes. Please have another look.

File: src/status_im/contexts/chat/group/details/view.cljs (hunk 5 above)
Comment (flexsurfer) [reply src/status_im/contexts/chat/group/details/view.cljs]: @ulisesmac could you elaborate why?

File: src/status_im/contexts/chat/group/events.cljs [hunk 6]
```diff
@@ -37,3 +39,16 @@
                      :on-success  (fn [response]
                                     (rf/dispatch [:chat-updated response true])
                                     (when on-success (on-success)))}]}))
+
+(rf/reg-event-fx :group-chat/set-manage-members-error
+ (fn [{:keys [db]} [{:keys [chat-id error?]}]]
+   (merge {:db (assoc-in db
+                [:group-chat/manage-members-error chat-id]
+                error?)}
+          (when error?
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/group/events.cljs]: instead of merge , :fx should be used

Comment (ajayesivan) [reply src/status_im/contexts/chat/group/events.cljs]: Done

**Review by flexsurfer — APPROVED** [review]
thank you

File: src/status_im/contexts/chat/group/events.cljs [hunk 7]
```diff
@@ -37,3 +39,16 @@
...
+   {:db (assoc-in db
+         [:group-chat/manage-members-error chat-id]
+         error?)
+    :fx [(when error?
+           {:dispatch
+            [:toasts/upsert
+             {:type :negative
+              :text (i18n/label :t/new-group-limit
+                                {:max-contacts
+                                 constants/max-group-chat-participants})}]})]}))
```
Comment (ulisesmac) [inline src/status_im/contexts/chat/group/events.cljs]: I wonder if this actually works, AFAIK vectors and maps have a lot in common in the Clojure core impl. but here the "official" API uses a vector of vectors:

```clojure
{:fx [ [:dispatch ...] ]

;; you used a map:
{:fx [ {:dispatch ...} ]
```

File: src/status_im/contexts/chat/group/details/view.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/group/details/view.cljs]: @flexsurfer 
Just React Hooks rules:
https://react.dev/reference/rules/rules-of-hooks#only-call-hooks-at-the-top-level

as a general good practice, we should (whenever possible) define the hooks first, so it's easy to track them and we make sure they are used before any possible invalid statement.

:thinking: I always use this pattern, but now I'm wondering if it really makes sense for the rest of the team. cc: @ilmotta  wdyt?

File: src/status_im/subs/chats.cljs (hunk 3 above)
Comment (ulisesmac) [reply src/status_im/subs/chats.cljs]: Hey @ajayesivan !

I meant about code formatting. The code style for functions is:
```clojure
(fn [p1 p2 ...]
  'function-body-1
  'function-body-2)

;; and NOT:
(fn [p1 p2 ...] 'function-body-1
                'function-body-2)
```

Comment (ulisesmac) [reply src/status_im/subs/chats.cljs]: Sorry for not being clear enough with the first comment

**Review by ulisesmac — CHANGES_REQUESTED** [review]
Adding the request changes because it seems it started to be QA-ed and the review is still not ready
@ajayesivan @Horupa-Olena

File: src/status_im/contexts/chat/group/details/view.cljs (hunk 5 above)
Comment (ilmotta) [reply src/status_im/contexts/chat/group/details/view.cljs]: I had the same question as @flexsurfer. I never thought of ordering subscriptions and hooks in a particular way, except for ordering them as naturally as the binding names should feel reading top to bottom. If there's no practical issue with using subs after hooks I think we can ignore this as a kind of guideline @ulisesmac

File: src/status_im/contexts/chat/group/events.cljs (hunk 7 above)
Comment (ilmotta) [reply src/status_im/contexts/chat/group/events.cljs]: Should be vectors of effects inside `:fx` as you noticed @ulisesmac. We should be consistent as much as possible.

File: src/status_im/contexts/chat/group/details/view.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/contexts/chat/group/details/view.cljs]: OK! Sorry for the confusion added @ajayesivan

File: src/status_im/subs/chats.cljs [hunk 8]
```diff
@@ -358,3 +358,21 @@
    (re-frame/subscribe [:chats/chat chat-id]))
  :->
  :image)
+
+(re-frame/reg-sub
+ :group-chat/manage-members-count
+ :<- [:chats/chats]
```
Comment (ilmotta) [inline src/status_im/subs/chats.cljs]: Much preferable to subscribe to `:chats/chat` (singular) because we don't want to subscribe to the top-level `:chats/chats` collection.

File: src/status_im/subs/chats.cljs [hunk 9]
```diff
@@ -358,3 +358,21 @@
...
+ :<- [:group-chat/selected-participants]
+ :<- [:group-chat/deselected-members]
+ (fn [[chats selected-participants deselected-members] [_ chat-id]]
+   (let [contacts               (get-in chats [chat-id :contacts])
+         current-contacts-count (count contacts)
```
Comment (ilmotta) [inline src/status_im/subs/chats.cljs]: Aggregation subs can greatly benefit from using other subs that compute the counts. This way this `:group-chat/manage-members-count` subscription doesn't need to rely on potentially large collections on every state update of the collections. I'm not sure if we have a sub for the count of selected participants or the count of deselected members, etc, but seems worth adding those as a good practice.

File: src/status_im/subs/chats_test.cljs [hunk 10]
```diff
@@ -207,3 +207,15 @@
         :chats           chats
         :current-chat-id chat-id)
       (is (true? (rf/sub [sub-name]))))))
+
+(h/deftest-sub :group-chat/manage-members-count
```
Comment (ilmotta) [inline src/status_im/subs/chats_test.cljs:211]: Thanks for adding sub tests!

**Review by ilmotta — COMMENTED** [review]
Thanks @ajayesivan. I focused my review on a few performance areas.

File: src/status_im/subs/chats.cljs (hunk 3 above)
Comment (ajayesivan) [reply src/status_im/subs/chats.cljs]: Thank you for the clarification!

File: src/status_im/contexts/chat/group/events.cljs (hunk 7 above)
Comment (ajayesivan) [reply src/status_im/contexts/chat/group/events.cljs]: `map` also works, but I’ve updated it to `vector` as suggested to maintain consistency.

File: src/status_im/subs/chats.cljs (hunk 9 above)
Comment (ajayesivan) [reply src/status_im/subs/chats.cljs]: I’ve added separate subscriptions for selected, deselected, and current member counts, and I'm using them here.

**Comment by ajayesivan** [comment]
@ulisesmac & @ilmotta Thank you for the review! I have updated the PR with suggested changes. Let me know if there is anything else that need to be fixed or improved.

**Comment by Horupa-Olena** [comment]
@ajayesivan @ulisesmac Can I start testing after the changes are added?

**Review by ilmotta — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]
Thank you for applying the changes @ajayesivan 

Good job! :+1: :+1:

**Comment by ulisesmac** [comment]
> @ajayesivan @ulisesmac Can I start testing after the changes are added?

Sure! :)

**Comment by Horupa-Olena** [comment]
@ajayesivan Thank you for your PR!

Please check this issue.
**Issue 1: User not added to group chat after being selected on the "Manage members" screen**

This usually happens when I uncheck one user and try to add another, but it occurs randomly.
Even if the user doesn't appear in the group chat, a system message still shows that the new member was added.

**Steps to reproduce:**

1. Create a group chat with 20 members
2. Go to the Manage members screen
3. Remove one user from the list
4. Add a new user
5. Observe the member counter on the Group Details screen and the member list

**Expected result:**
The counter shows 20 members, and the list contains 20 users.

**Actual result:**
The newly added user does not appear in the group chat.

https://github.com/user-attachments/assets/84284116-034d-478e-baf8-0a576f305664

**Comment by ajayesivan** [comment]
@Horupa-Olena I'm unable to reproduce this issue. Could you please share any additional details that might help me reproduce it?

Also, this PR doesn’t touch the actual logic related to adding or removing members, so it’s unlikely that this issue is caused by changes in this PR.

Could you please test the `develop` branch and check if the issue is reproducible there as well?

**Comment by Horupa-Olena** [comment]
> @Horupa-Olena I'm unable to reproduce this issue. Could you please share any additional details that might help me reproduce it?
> 
> Also, this PR doesn’t touch the actual logic related to adding or removing members, so it’s unlikely that this issue is caused by changes in this PR.
> 
> Could you please test the `develop` branch and check if the issue is reproducible there as well?

@ajayesivan You were right — this behavior is present in develop as well. I checked the latest build.
The issue occurs less frequently, but I was able to reproduce it with the following steps:

1. Click on "..." in the chat → Manage members
2. Remove one user and add a new one.

https://github.com/user-attachments/assets/5037970d-47c9-4a1c-b74c-294cc865fc84

**Comment by Horupa-Olena** [comment]
> @Horupa-Olena I'm unable to reproduce this issue. Could you please share any additional details that might help me reproduce it?
> 
> Also, this PR doesn’t touch the actual logic related to adding or removing members, so it’s unlikely that this issue is caused by changes in this PR.
> 
> Could you please test the `develop` branch and check if the issue is reproducible there as well?

@ajayesivan If it's hard to find the root cause now, I can just log it as a follow-up issue. What do you think?

**Comment by ajayesivan** [comment]
> @ajayesivan If it's hard to find the root cause now, I can just log it as a follow-up issue. What do you think?

@Horupa-Olena That would be great. Please go ahead and log it as a follow-up issue. I’ll take a look early next week. Thanks so much for investigating the `develop` branch!

**Comment by Horupa-Olena** [comment]
> > @ajayesivan If it's hard to find the root cause now, I can just log it as a follow-up issue. What do you think?
> 
> @Horupa-Olena That would be great. Please go ahead and log it as a follow-up issue. I’ll take a look early next week. Thanks so much for investigating the `develop` branch!

@ajayesivan Thanks for your work! **PR can be merged.**

[Follow up](https://github.com/status-im/status-mobile/issues/22594) created.

**Comment by ajayesivan** [comment]
@ilmotta This PR is ready to merge — I’ve rebased it with the latest changes. Let me know if you need anything else from my side.
