### PR TITLE
bug #7724 - correctly showing password errors for sign message

### LINKED ISSUE #7724: No "wrong password" error if enter wrong password on Sign Message screen
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: On Sign message screen there is no error and nothing happens if user entered wrong password and tap Sign. Would expect error message same as when Signing transaction and entering wrong password.

Note that on 0.10.1 release issue does not happen and expected error message is shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and switch to Ropsten 
- Open Status Test Dapp
- On Transactions tap on Sign message button
- Enter wrong password and  tao on Sign. Check if there is any error message "Wrong password" shown 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly March 12. 
* Operating System: Android and iOS

#### Logs
see March 12, 16:22
[Status.log](https://github.com/status-im/status-react/files/2957574/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2957575/geth.log)

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #7724

### Summary:

Fixed bug with missing error popup for wrong password

### Steps to test:
see #7724

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/wallet/sign_message/views.cljs [hunk 1]
```diff
@@ -103,7 +103,7 @@
           nil]]]]
       [enter-password-buttons value-atom false
        #(re-frame/dispatch [:wallet/discard-transaction-navigate-back])
-       #(re-frame/dispatch [:wallet/sign-message typed? (merge screen-params @value-atom)])
+       #(re-frame/dispatch [:wallet/sign-message typed? (merge screen-params @value-atom) value-atom])
```
Comment (cammellos) [inline src/status_im/ui/screens/wallet/sign_message/views.cljs]: Interesting, I am all for local state when actually local and well encapsulated, but in this case looks like it's not local anymore, and relies on a state modification happening in a separate component/file (state is being passed around, but modified directly i.e `swap`), at this point I would just consider using the re-frame database, as there's no encapsulation effectively anymore.

another option is might be  a matter of refactoring (`views.cljs` never access state directly, but always access it through `events.cljs`, i.e `(events/wrong-password?)` `(events/sign-message! typed? screen-params)` so that `value-atom` never leaves `events.cljs` directly, but always through an API.

Not much of a big deal to be honest, but it's good to agree on a direction, what do you think?

Comment (goranjovic) [reply src/status_im/ui/screens/wallet/sign_message/views.cljs]: I agree with your point, although I'd rather fix it in a different way - pass a callback from the view code e.g. `(show-wrong-password)`. That callback can alter the state and then it's local i.e. encapsulated.

Whether or not there's a password error really is UI state and nothing more. It doesn't belong in the events code and it doesn't belong in re-frame database.

Comment (cammellos) [reply src/status_im/ui/screens/wallet/sign_message/views.cljs]: callback sounds like a good approach, best to keep the atom in the view I agree :+1:

**Comment by goranjovic** [comment]
@cammellos @dmitryn guys, please re-review - I replaced the direct atom access with a callback.

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
image
