### PR TITLE
[#17446] fix: Display name is not shown in chats after sync

### LINKED ISSUE #17446: Display name is not shown in chats after sync
# Bug Report

## Problem 
Monosnap 2023-09-28 13-46-15

#### Expected behavior
can see display name

### Reproduction

1. Device 1 generates sync QR
2. Device 2 scans QR > finish sync
3. Device 2: send message to any community

- Status version: nightly 28/09/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17446

Display name is not shown in chats after sync

### Steps to test

- Device 1 generates sync QR
- Device 2 scans QR > finish sync
- Device 2: send message to any community

### Result 

https://github.com/status-im/status-mobile/assets/71308738/9cbde03f-8e53-4eb5-b466-ae74267bf132

status: ready

### CODE REVIEW

File: src/status_im/multiaccounts/core.cljs [hunk 1]
```diff
@@ -43,10 +43,11 @@
...
   (let [me? (= (:public-key profile) contact-identity)]
     (if me?
-      [(or (:preferred-name profile)
-           (:display-name profile)
-           (:primary-name contact)
-           (gfycat/generate-gfy contact-identity))]
+      [(or
+        (when (seq (:preferred-name profile)) (:preferred-name profile))
+        (when (seq (:display-name profile)) (:display-name profile))
+        (when (seq (:primary-name contact)) (:primary-name contact))
```
Comment (ibrkhalil) [inline src/status_im/multiaccounts/core.cljs]: I think it's better to use string/blank? for strings to check for emptiness.
It's more performant.

Comment (ibrkhalil) [reply src/status_im/multiaccounts/core.cljs]:
```clj
(when-not (string/blank? (:preferred-name profile)) (:preferred-name profile))
```

Comment (mohsen-ghafouri) [reply src/status_im/multiaccounts/core.cljs]: Thanks @ibrkhalil , resolved.

File: src/status_im/multiaccounts/core.cljs [hunk 2]
```diff
@@ -43,10 +43,11 @@
...
     (if me?
-      [(or (:preferred-name profile)
-           (:display-name profile)
-           (:primary-name contact)
-           (gfycat/generate-gfy contact-identity))]
+      [(or
+        (when-not (string/blank? (:preferred-name profile)) (:preferred-name profile))
+        (when-not (string/blank? (:display-name profile)) (:display-name profile))
+        (when-not (string/blank? (:primary-name contact)) (:primary-name contact))
+        (gfycat/generate-gfy contact-identity))]
```
Comment (Parveshdhull) [inline src/status_im/multiaccounts/core.cljs]: better to use [cond](https://clojuredocs.org/clojure.core/cond) here

Comment (mohsen-ghafouri) [reply src/status_im/multiaccounts/core.cljs]: done

**Review by ibrkhalil — APPROVED** [review]
Nice job!

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanx for the fix. Ready for merge.
