### PR TITLE
fix nil value in reanimated style crashing at runtime

### LINKED ISSUE #14756: nil value in reanimated style crashing at runtime
# Problem

If there exists a nil value for any of reanimated style parameters, then it makes the app crash.
Even if nil is for direct param or nested param like, `:transform [{:style nil}]` or even when nil is the value of shared-value. (related [comment](https://github.com/status-im/status-mobile/blob/ceaa363f087ff825e5d74a9143332b9c834c9a01/src/status_im2/contexts/shell/animation.cljs#L77))

Thanks @flexsurfer for finding this

**Error:**
erro

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/14756

status: ready

### CODE REVIEW

File: src/react_native/reanimated.cljs [hunk 1]
```diff
@@ -79,17 +78,10 @@
                       (clj->js extrapolation))))
 
 ;;;; Component Animations
-
-;; kebab-case styles are not working for worklets
```
Comment (flexsurfer) [inline src/react_native/reanimated.cljs:83]: just wondering why you decided to move this to js side ?

**Review by flexsurfer — APPROVED** [review]

File: src/react_native/reanimated.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/react_native/reanimated.cljs:83]: The function we had to convert `kebab-case` to `camel-case` was only mapping direct keys, not nested keys of the transform param.
And we already iterating through maps in js side, so it made more sense to change the case of keys at that time.
