### PR TITLE
Validate rpc-url when creating a custom network

### LINKED ISSUE #4672: Can't sign in if switch to the custom network with invalid url
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Signing in continues forever, so user can't sign in after switching to the custom network with invalid url

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
1. There should be validation of the url when user tries to save new custom network.
2. On sign in step: If by any reasons network is not good enough - we can show warning after some timeout, e.g 5 minutes and propose to switch back to Ropsten, so user is not stack 
#### Actual behavior
[comment]: # (Describe what actually happened.)
Spinner with "Signing you in" is shown forever and user can't sign in
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open Profile 
- Turn on development mode
- Tap on Network
- In Network settings screen: tap on "+" button in the top right corner
- in RPC URL write some invalid url, e.g. "wrong" or valid url without http://
- In Name: "wrong network"
- Save new network settings
- Switch to this network and tap on Connect
- Sign in to your account

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build june 7
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4672 

### Summary:

Previously RPC url was not validated when creating a custom network. At login time this resulted in `status-go` crashing, leaving the user unable to login. We know validate the format so that `status-go` should not crash anymore.

This change effectively only allows RPC over http/https for custom networks.

We should eventually make the system more resilient to `status-go` crashing because of wrong network configuration ( allow user to select network configuration before logging in, log in using the last network config if node has crashed or similar), but that's not in the scope of this PR.

### Testing notes:

* Only http or https url are valid.

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

File: test/cljs/status_im/test/models/network.cljs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+  (testing "a blank url"
+    (is (not (model/valid-rpc-url? ""))))
+  (testing "a url without a protocol"
+    (is (not (model/valid-rpc-url? "something"))))
+  (testing "a url without a hostname"
+    (is (not (model/valid-rpc-url? "https://"))))
+  (testing "an http url"
+    (is (model/valid-rpc-url? "http://localhost")))
+  (testing "an https url"
+    (is (model/valid-rpc-url? "https://localhost.something.else"))))
```
Comment (dmitryn) [inline test/cljs/status_im/test/models/network.cljs]: Specifying `port` is not required? Does it use default port like `8545`?

Comment (cammellos) [reply test/cljs/status_im/test/models/network.cljs]: @dmitryn good point, our use only the default port, but I will add the port to the validation

Comment (cammellos) [reply test/cljs/status_im/test/models/network.cljs]: Actually it's loose enough the regex that it validates ok with a port, but added a test case.

File: src/status_im/models/network.cljs [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+          network                  (new-network cofx (:value name) (:value url) (:value chain))
+          new-networks             (merge {(:id network) network} (:networks account))]
+      (handlers-macro/merge-fx cofx
+                               {:db       (dissoc db :networks/manage)
+                                :dispatch [:navigate-back]}
+                               (accounts.utils/account-update {:networks new-networks})))))
+
+(defn edit [{db :db}]
+  {:db       (update-in db [:networks/manage] assoc
+                        :name  {:error true}
```
Comment (yenda) [inline src/status_im/models/network.cljs]: Not in scope of the PR because it was already there and you just moved it but I find it wierd that we set error to `true` here.

**Review by yenda — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

File: src/status_im/models/network.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im/models/network.cljs]: @yenda yes, it's a bit confusing as there are 2 places where validation is made and this one skips it (we still need to do validation at this layer), I have rationalised it a bit.

**Comment by lukaszfryc** [comment]
@cammellos when I try to add https://mainnet.infura.io/z6GCTmjdP3FETEJmMBI4, the Save is inactive. Just https://mainnet.infura.io/ works but I think the full url should be supported. 

Other than that, it works fine.

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by cammellos** [comment]
thanks @lukaszfryc I have pushed a change to address the issue, building now

**Comment by lukaszfryc** [comment]
@cammellos should IP addresses work as well (like http://84.102.34.4)? They stopped after the latest change.

**Comment by lukaszfryc** [comment]
@cammellos all works fine now 👍
