### PR TITLE
Fix safe areas all over the app

### LINKED ISSUE #21962: Last token is partially hidden on Select assets to buy/pay/receive screens (IOS only)
Reproduced on iPhone 15

**Steps:** 

1. Open Select assets to buy/pay/receive screen
2. Scroll to the end of the assets list
3. Pay attention at the last asset in the list

**Actual result:** asset is partially hidden. 

https://github.com/user-attachments/assets/f9af718f-ff62-43fb-8262-fe677f57c1ba

Image

### Additional Information

- Status version: nightly 
- Operating System:  iOS 17.6.1
- iPhone 15

### LINKED ISSUE #22395: Fix safe areas across the app
# Bug Report

## Problem 
Safe areas have been inconsistently applied everywhere, once we noticed, the discussion with designers started  and the following doc was created:

https://www.notion.so/Safe-area-discussion-1758f96fb65c800e820ec7a9f8db7d41

Designers replied with the following doc and an explanation of what was going on:
https://www.figma.com/design/3vsROK2c4n7zaPC6L8NHHI/Safe-Margins?node-id=1-20&p=f&m=dev

Basically, the padding should be considered into the iOS safe area to bring a consistent experience across apps.

## Why this has happened?

Seems a misunderstanding on the figma designs, they don't explicitly show the safe-area and we just put components next to it. Actually, it's very noticeable on iOS that our app starts to render the content below what other apps do.

We should also check the implementation on Android and provide a simple and abstracted API for safe areas that work easy on both platforms.

 We must also check what's going on with bottom safe areas and fix them.

#### Expected behavior

Check the figma file, but here's a screenshot with the fixed design compared to a WhatsApp screenshot on iPhone 16 pro

Image

#### Actual behavior

Our safe areas are below the expected position.

### Reproduction

Just open the app

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #22395
fixes https://github.com/status-im/status-mobile/issues/21962
fix partial https://github.com/status-im/status-mobile/issues/22488

## Summary
We've been using safe areas wrongly all over the app, please check the issue description if you are curious about it, but, as a summary, we put components next to the safe area, instead, we should've put them overlapped.

### **What's the amount to overlap?** 

It depends on the platform, top or bottom, and device.
For bottom is a constant `12` on all platforms.
For top is zero on Android, and the exact amount on iOS depends on the device.

This PR provides an infrastructure to fix the safe areas for all the app, with a well tested value for iPhone 16Pro, for other iPhone devices I tested using simulators so I need some (progressive, not right now) help from you.

I've always felt the buttons for the navbar were misplaced, and actually they were!, here's an image (very large, please download it if needed), that compares the old safe areas with the news introduced in this PR compared against other iOS apps: Phone, AppStore and WhatsApp, the new safe areas match and the app (IMO) feels better.

old-ios

### **How to fix safe areas for other iPhone devices**
Since I mention, I may provide a wrong value for other devices, so, if you notice a safe area doesn't match the expected distance on a certain device, just add the value to `react-native.safe-area/safe-area-top-fix` and that's all :)

~~### **Bonus: Bye Android navigation bar Color**~~
~~Modern Android apps allow us to draw behind the transparent navigation bar, and we must also handle a safe area for it, so this PR fixes that for all the screens, please check out this demo where the content is drawn behind the bottom buttons:~~
~~[transparent-nav-bar-android.webm](https://github.com/user-attachments/assets/46041687-6400-4dbb-a419-d12e6aa381d2)~~
~~This will provide a more consistent experience across platforms and a more modern look.~~

## Review notes
These changes affect all the app, so I will highly appreciate if you point issues I didn't notice

## Testing notes
Please test all screens, I checked them but I may be missing something, so I appreciate if you find issues. During these fixes, I found code hardcoding the safe area, I fixed for some of them, I'll continuously be fixing these usages as I touch different parts of the app in following issues. 

### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: android/app/src/main/java/im/status/ethereum/MainActivity.kt [hunk 1]
```diff
@@ -127,6 +130,13 @@ class MainActivity : NavigationActivity(), ActivityCompat.OnRequestPermissionsRe
 
         setSecureFlag()
 
+        val w: Window = window
+        w.statusBarColor = Color.TRANSPARENT
+        w.navigationBarColor = Color.TRANSPARENT
+        w.decorView.systemUiVisibility =
+            View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
```
Comment (ulisesmac) [inline android/app/src/main/java/im/status/ethereum/MainActivity.kt]: For full screen on Android

File: src/react_native/safe_area.cljs [hunk 2]
```diff
@@ -1,32 +1,57 @@
...
-(defn- get-static-top
-  []
-  (oops/oget StaticSafeAreaInsets "safeAreaInsetsTop"))
+(def ^:private safe-area-top-fix
+  "Subtract to the top safe area to match a standard design.
+  The values depend on our components padding (usually 12)"
+  {:android {:default 0}
+   :iphone  {62       11 ;; 16 +
+             59       12 ;; 14Pro -> 15Pro
+             :default 8}}) ;; 11 -> 14, 13mini
```
Comment (ulisesmac) [inline src/react_native/safe_area.cljs:11]: Measured by me on simulators, only iPhone 16 was a real device, if you find this measurement wrong, please contribute to it

File: src/react_native/safe_area.cljs [hunk 3]
```diff
@@ -1,32 +1,57 @@
...
+  {:top    static-top
+   :bottom static-bottom})
+
+(def ^:private static-frame
+  (:frame safe-area-context/initial-window-metrics))
+
+(defn get-top [] static-top)
+(defn get-bottom [] static-bottom)
+(defn get-insets [] static-insets)
+(defn get-window [] static-frame)
```
Comment (ulisesmac) [inline src/react_native/safe_area.cljs]: Same API as before but with values fixed

File: src/react_native/safe_area_context.cljs [hunk 4]
```diff
@@ -0,0 +1,17 @@
+(ns react-native.safe-area-context
+  (:require ["react-native-safe-area-context"
```
Comment (ulisesmac) [inline src/react_native/safe_area_context.cljs:2]: Brought this new library to properly report safe areas on Android with  the edge-to-edge mode

Comment (ulisesmac) [reply src/react_native/safe_area_context.cljs:2]: Also it contains a hook for the safe area (dynamic) and a built-in component that applies safe areas natively

File: android/app/src/main/java/im/status/ethereum/MainActivity.kt (hunk 1 above)
Comment (seanstrom) [reply android/app/src/main/java/im/status/ethereum/MainActivity.kt]: Very cool that you found this configuration 🙌 
One small note, it might be worth asking in design-discussion if they are aware of any reasons that transparency would not be okay. I can't think of any atm, but it still could be useful to let them know (if you haven't already).

File: src/react_native/safe_area.cljs (hunk 2 above)
Comment (seanstrom) [reply src/react_native/safe_area.cljs:11]: Could you elaborate a little more about these numbers?

For example, are we saying that we subtract 11 units from the top safe-area on iphone 16 models?

File: src/status_im/common/bottom_sheet/view.cljs [hunk 5]
```diff
@@ -93,20 +95,23 @@
                                                                            window-height
                                                                            on-close)
                                                        [window-height on-close])
+        {android-bottom :bottom}          (safe-area/use-safe-area)
+        top-inset                         (:top insets)
+        bottom-inset                      (if platform/ios? (:bottom insets) android-bottom)
```
Comment (seanstrom) [inline src/status_im/common/bottom_sheet/view.cljs]: Could we possibly have a hook that takes the `insets` as input and returns a modified `insets`?

I think it would basically have the same logic as what you've described here, but it would be responsible for the platform specific details instead of the view.

thoughts?

File: src/status_im/common/home/banner/style.cljs [hunk 6]
```diff
@@ -61,7 +62,7 @@
    {:transform [{:translate-y (animated-card-translation-y scroll-shared-value)}]}
    {:z-index          3
     :position         :absolute
-    :top              (+ (safe-area/get-top) 192)
+    :top              (+ (safe-area/get-top) 192 -8)
```
Comment (seanstrom) [inline src/status_im/common/home/banner/style.cljs]: Could explain why we moved the `8` to be a `-8` here?

Also should this be a constant too?

File: src/status_im/contexts/communities/overview/style.cljs [hunk 7]
```diff
@@ -18,6 +18,7 @@
    :background-color background-color
    :height           (+ 20 ;; Area hidden by sheet on top but visible with rounded borders
                         92
+                        12
                         (safe-area/get-top))})
```
Comment (seanstrom) [inline src/status_im/contexts/communities/overview/style.cljs]: Is this `12` part of the safe-areas special spacing? If so could we define a constant or function for retrieving this value?

File: src/status_im/contexts/communities/overview/style.cljs [hunk 8]
```diff
@@ -45,15 +46,15 @@
   [opposite-header-opacity]
   [rn/stylesheet-absolute-fill
    page-nav-container-base-style
-   {:top     (- (safe-area/get-top) 12) ;; -12 to place the button next to the safe-area
+   {:top     (safe-area/get-top)
```
Comment (seanstrom) [inline src/status_im/contexts/communities/overview/style.cljs]: This looks pretty nice ✨

File: src/status_im/contexts/communities/overview/view.cljs [hunk 9]
```diff
@@ -210,18 +209,21 @@
 (defn- unusable-area-height
   []
   (+ (safe-area/get-top)
+     12
      32
      11 ;;top page buttons & button's padding
      (safe-area/get-bottom)))
```
Comment (seanstrom) [inline src/status_im/contexts/communities/overview/view.cljs]: I think if this value is related to the safe-area, we should naming it as a constant so that we can change it easily later on.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 10]
```diff
@@ -210,18 +209,21 @@
...
   (- (+ scrollable-height (unusable-area-height))
-     (:height (rn/get-window))))
+     (:height (safe-area/get-window))))
 
 (defn- calc-listing-height
   []
-  (- (:height (rn/get-window)) (unusable-area-height)))
+  (- (:height (safe-area/get-window))
+     (unusable-area-height)
+     (- (safe-area/get-bottom))))
```
Comment (seanstrom) [inline src/status_im/contexts/communities/overview/view.cljs]: This is a nice example of how I think we can avoid referring to the special numbers like `12` or etc.

File: src/status_im/contexts/communities/overview/view.cljs [hunk 11]
```diff
@@ -263,7 +265,7 @@
      {:ref                     flat-list-ref
       :style                   [(style/channel-listing theme listing-height) channels-styles]
       :data                    flatten-channels
-      :content-container-style (when platform/ios? {:padding-bottom (safe-area/get-bottom)})
+      :content-container-style {:padding-bottom (safe-area/get-bottom)}
```
Comment (seanstrom) [inline src/status_im/contexts/communities/overview/view.cljs]: This is also a nice example of how we can avoid leaking platform specifics in the styles 🙌

File: src/status_im/contexts/onboarding/syncing/progress/view.cljs [hunk 12]
```diff
@@ -70,12 +71,13 @@
...
 (defn view
   [in-onboarding?]
-  (let [pairing-status    (rf/sub [:pairing/pairing-status])
-        logged-in?        (rf/sub [:multiaccount/logged-in?])
-        pairing-progress? (pairing-progress pairing-status)
-        profile-color     (or (:color (rf/sub [:onboarding/profile]))
-                              (rf/sub [:profile/customization-color]))]
-    [rn/view {:style (style/page-container in-onboarding?)}
+  (let [{:keys [top bottom]} (safe-area/get-insets)
+        pairing-status       (rf/sub [:pairing/pairing-status])
```
Comment (seanstrom) [inline src/status_im/contexts/onboarding/syncing/progress/view.cljs]: Do you think we should create a reframe subscription for this value if we're not using a hook?

File: src/status_im/contexts/profile/profiles/style.cljs [hunk 13]
```diff
@@ -25,10 +25,11 @@
...
     :right    0}))
 
-(def profiles-header
+(defn profiles-header
+  [top]
   {:flex-direction     :row
    :padding-horizontal 20
-   :padding-top        112
+   :padding-top        (+ 56 top)
    :margin-bottom      20})
```
Comment (seanstrom) [inline src/status_im/contexts/profile/profiles/style.cljs:33]: Is the value `56` related to the safe-area or the design of the view?

File: src/status_im/contexts/profile/profiles/view.cljs [hunk 14]
```diff
@@ -273,7 +277,7 @@
          :icon-left           :i/unlocked
          :disabled?           (or (not sign-in-enabled?) processing)
          :on-press            login-profile
-         :container-style     {:margin-bottom (+ (safe-area/get-bottom) 12)}}
+         :container-style     {:margin-bottom (+ bottom 12)}}
         (i18n/label :t/log-in)])]))
```
Comment (seanstrom) [inline src/status_im/contexts/profile/profiles/view.cljs:282]: Here's another spot where we can try to hide the value `12`, do you think that's possible or preferred?

**Review by seanstrom — COMMENTED** [review]
Awesome stuff! Thanks for working on this ✅ 

Left a few comments about some potential refactors or tweaks, let me know what you think when you have a chance 🙏 

Also have you tried viewing these changes on features like Keycard?
I think that feature opens most of the views inside of a nearly full-screen bottom-sheet, so I wonder how these changes could affect those screens.

File: src/react_native/core.cljs [hunk 15]
```diff
@@ -17,7 +18,18 @@
...
+
+(defn safe-area-view
+  "Safe area view is only supported on iOS, but this version receives `top?` and `bottom?`
+  to enable safe-area paddings working on android."
+  [{:keys [top? bottom?] :as props} & children]
+  (let [{:keys [top bottom]} (safe-area/get-insets)
+        new-props            (cond-> props
+                               (and platform/android? top?)    (assoc :padding-top top)
+                               (and platform/android? bottom?) (assoc :padding-bottom bottom))
+        component            (if platform/ios? safe-area-view* view)]
```
Comment (ilmotta) [inline src/react_native/core.cljs]: Not sure where else I've seen vars with asterisks in the repo, but in Clojure they remind me quite a bit about the conventions for dynamic vars (see the Clojure style guide https://guide.clojure.style/#naming-dynamic-vars) and the usage of earmuffs. Many codebases also used asterisks as a convention to differentiate stateful vars (like atoms).

This is a nitpick :) Should we make `safe-area-view*` private or is there a need to access it from the outside?

File: src/react_native/safe_area.cljs [hunk 16]
```diff
@@ -1,32 +1,57 @@
...
-    bottom
-    0))
+  (let [platform (if platform/ios? :iphone :android)]
+    (-> safe-area-bottom-fix platform :default)))
 
-(defn get-insets
-  []
-  {:top    (get-top)
-   :bottom (get-bottom)})
+(defn get-top-for-views
```
Comment (ilmotta) [inline src/react_native/safe_area.cljs]: This function and `get-bottom-for-views` are currently only used internally to build `static-top`, and `static-bottom`. Do they need to be public?

File: src/react_native/safe_area.cljs [hunk 17]
```diff
@@ -1,32 +1,57 @@
...
+  (-> safe-area-context/initial-window-metrics :insets :bottom get-bottom-for-views))
+
+(def ^:private static-insets
+  {:top    static-top
+   :bottom static-bottom})
+
+(def ^:private static-frame
+  (:frame safe-area-context/initial-window-metrics))
+
+(defn get-top [] static-top)
```
Comment (ilmotta) [inline src/react_native/safe_area.cljs]: Why do we need to wrap static values in functions? Is this preparing us for a future change? If not, can we change all calls to `get-top`, `get-bottom`, `get-insets` to be just a simple var reference like `safe-area/insets` or `safe-area/bottom` ? It's more code changes in the repo, but they are all safe to apply without breaking anything.

File: src/react_native/safe_area.cljs [hunk 18]
```diff
@@ -1,32 +1,57 @@
...
+  "Safe area top that must be used when creating screens"
+  [original-top-safe-area]
+  (- original-top-safe-area (get-top-fix original-top-safe-area)))
+
+(defn get-bottom-for-views
+  "Safe area bottom that must be used when creating screens"
+  [original-bottom-safe-area]
+  (- original-bottom-safe-area (get-bottom-fix)))
+
+
```
Comment (ilmotta) [inline src/react_native/safe_area.cljs]: Extra line

File: src/react_native/safe_area_context.cljs (hunk 4 above)
Comment (ilmotta) [reply src/react_native/safe_area_context.cljs:2]: > Brought this new library to properly report safe areas on Android with the edge-to-edge mode

From their docs: `Note that there will be breaking changes and only the latest version of react-native will be supported.` Just something for us to be aware, this could be a problem in the future.

File: src/react_native/safe_area_context.cljs [hunk 19]
```diff
@@ -0,0 +1,17 @@
...
+             :refer
+             [initialWindowMetrics SafeAreaProvider SafeAreaView
+              useSafeAreaInsets]]
+            [reagent.core :as reagent]))
+
+(def initial-window-metrics (js->clj initialWindowMetrics :keywordize-keys true))
+
+(def safe-area-provider (reagent/adapt-react-class SafeAreaProvider))
+(def safe-area-view (reagent/adapt-react-class SafeAreaView))
```
Comment (ilmotta) [inline src/react_native/safe_area_context.cljs]: I don't see any usage of this `safe-area-view` var. Leftover?

File: src/status_im/common/bottom_sheet/view.cljs [hunk 20]
```diff
@@ -7,7 +7,9 @@
     [react-native.core :as rn]
     [react-native.gesture :as gesture]
     [react-native.hooks :as hooks]
+    [react-native.platform :as platform]
     [react-native.reanimated :as reanimated]
+    [react-native.safe-area-context :as safe-area]
```
Comment (ilmotta) [inline src/status_im/common/bottom_sheet/view.cljs]: Better to consistently name the import as `safe-area-context` to not confuse with the `react-native.safe-area` namespace.

File: src/react_native/safe_area_context.cljs [hunk 21]
```diff
@@ -0,0 +1,17 @@
...
+
+(defn use-safe-area
+  []
+  (let [insets (useSafeAreaInsets)]
+    {:top    (.-top insets)
```
Comment (ilmotta) [inline src/react_native/safe_area_context.cljs]: To follow our own guidelines, we should prefer oops to access object properties.

File: src/react_native/safe_area_context.cljs [hunk 22]
```diff
@@ -0,0 +1,17 @@
...
+            [reagent.core :as reagent]))
+
+(def initial-window-metrics (js->clj initialWindowMetrics :keywordize-keys true))
+
+(def safe-area-provider (reagent/adapt-react-class SafeAreaProvider))
+(def safe-area-view (reagent/adapt-react-class SafeAreaView))
+
+(defn use-safe-area
+  []
+  (let [insets (useSafeAreaInsets)]
```
Comment (ilmotta) [inline src/react_native/safe_area_context.cljs]: From the docs

> useSafeAreaInsets offers more flexibility, but can cause some layout flicker in certain cases. Use this if you need more control over how insets are applied.
>
> -- https://appandflow.github.io/react-native-safe-area-context/usage

And that `SafeAreaView` should be the preferred way. Have you seen flickering issues?

File: src/status_im/contexts/shell/bottom_tabs/style.cljs [hunk 23]
```diff
@@ -1,21 +1,23 @@
...
-    :align-items         :center
-    :height              (utils/bottom-tabs-container-height)
-    :accessibility-label :bottom-tabs-container}])
+  (let [safe-area-bottom (-> safe-area/initial-window-metrics :insets :bottom)
+        safe-area-height (cond-> safe-area-bottom
+                           (zero? safe-area-bottom) (+ 6))]
+    [{:height height}
+     {:background-color    colors/neutral-100
+      :align-items         :center
+      :height              (+ 8 40 2 safe-area-height)
```
Comment (ilmotta) [inline src/status_im/contexts/shell/bottom_tabs/style.cljs]: Thanks for keeping the values separated. Could you add a comment or extract to vars to give meaning to them?

**Review by ilmotta — APPROVED** [review]
Thank you for your efforts in improving the UX! I couldn't find anything critical while reviewing the PR. @seanstrom already covered many points regarding hardcoded values. I experimented in Android and iOS and the app looked good.

Should we ask a design review on this PR?

**Comment by flexsurfer** [comment]
hey @ulisesmac are you sure `Bonus: Bye Android navigation bar Color` will work on all Android devices?

**Comment by churik** [comment]
@ulisesmac 
when the main review comments are addresses, please move PR to testing, or let us know when it is ready, as the regression scope is quite extensive, thank you!

**Comment by ulisesmac** [comment]
> hey @ulisesmac are you sure `Bonus: Bye Android navigation bar Color` will work on all Android devices?

Hey @flexsurfer , as far as I investigated, the APIs used were available since the Android API 21, our minSDK is set to 24 (Android 7.0). So yes, it must work, however, I requested the specs for our lowest-end device/Android version so we make sure it works well there.

File: android/app/src/main/java/im/status/ethereum/MainActivity.kt (hunk 1 above)
Comment (ulisesmac) [reply android/app/src/main/java/im/status/ethereum/MainActivity.kt]: They said actually this was the expected way to work:
https://discord.com/channels/1210237582470807632/1274068685266489434/1358865214799610126

File: src/react_native/safe_area.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/react_native/safe_area.cljs:11]: @seanstrom Exactly!
 
 the iPhone 16 reports a safe area of 62, if we subtract 11 units from the navigation bar, then we match the iOS Standard design (as in the image I shared & as pointed out by Pedro in the desired design). However, I noticed this number is not stable across different iPhone models :cry:  e.g. if we subtract 12 for an iPhone without dynamic island (11, 12, 13, 14), our navigation bar is positioned higher than it should be when compared to other iOS apps.
 
 Please, LMK if there are still questions about it. Also, any comment to improve this docstring is welcome

File: src/react_native/safe_area_context.cljs (hunk 4 above)
Comment (ulisesmac) [reply src/react_native/safe_area_context.cljs:2]: Yep, actually we are not using the latest version, the version we are using still supports 0.73. I checked the newer implementation and we can handle it without any problems.

Comment (ulisesmac) [reply src/react_native/safe_area_context.cljs:2]: BTW, in newer versions they improved their docs

File: src/status_im/common/bottom_sheet/view.cljs (hunk 5 above)
Comment (ulisesmac) [reply src/status_im/common/bottom_sheet/view.cljs]: Thanks for the suggestion @seanstrom 

However, I see it as overcomplicating the implementation. Why would we want a hook for a non-reactive value? the safe areas are defined as soon as the app starts, what is the point of using a hook knowing that hooks have some rules/limitations?

This is the only place where I used this `safe-area/use-safe-area` hook because it returns a dynamic value, the safe area is `0` when the keyboard is opened and platform's `bottom` when it's closed. This is a workaround because of our implementation of the bottom sheet + floating button + keyboard-avoiding-view ignoring the negative-offset on Android. We could fix it in a cleaner way but I didn't want to reimplement it.

Besides this usage (as far as I've seen), we always handled our safe areas as static values, no need for making it a hook.

@ilmotta this is the hook the docs are referring to when they sometimes it has a delay,it's because the hook reports the new safe areas ~1 frame after the keyboard has been opened.

File: src/status_im/common/home/banner/style.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/common/home/banner/style.cljs]: A leftover, it should have been subtracted to the `192`.And the reason is that we added a spacing of 8 that never existed on designs, this fix properly aligns the navbar as expected.

File: src/status_im/contexts/communities/overview/style.cljs (hunk 7 above)
Comment (ulisesmac) [reply src/status_im/contexts/communities/overview/style.cljs]: this `12` is just the padding of the navigation bar in any screen (but particularly on the communities overview). it must be counted to define the space to scroll.

Previously it wasn't counted because this screen was the only one that followed the expected safe areas, now with the safe-areas fixed, this component counts it.

File: src/status_im/contexts/onboarding/syncing/progress/view.cljs (hunk 12 above)
Comment (ulisesmac) [reply src/status_im/contexts/onboarding/syncing/progress/view.cljs]: I don't think so, it's just a value gathered when the app starts, we don't need to glorify it :thinking:

File: src/status_im/contexts/profile/profiles/style.cljs (hunk 13 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/profiles/style.cljs:33]: The design of the view hardcoded the top padding, for this case I just fixed the hardcoded value to match designs.

File: src/status_im/contexts/profile/profiles/view.cljs (hunk 14 above)
Comment (ulisesmac) [reply src/status_im/contexts/profile/profiles/view.cljs:282]: Oh, that `12` is because of designs, we add a padding of 12 so that the list has an empty space at the end instead of snapping to the safe area. this is just to match designs

File: src/react_native/core.cljs (hunk 15 above)
Comment (ulisesmac) [reply src/react_native/core.cljs]: Well, for dynamic vars Clojure asks to use surrounding asterisks. I've seen sometimes we use `'` at the end instead of the asterisk (e.g. `safe-area-view'`), but not sure about it.

Any suggestion on how to improve it?

I made it private :+1:

File: src/react_native/safe_area.cljs (hunk 16 above)
Comment (ulisesmac) [reply src/react_native/safe_area.cljs]: Nope, now made them private

File: src/react_native/safe_area.cljs (hunk 17 above)
Comment (ulisesmac) [reply src/react_native/safe_area.cljs]: Just wanted to keep the same API and not change all the files, but it's fine, actually it's easier to use if we just refer to the vars.

File: src/react_native/safe_area_context.cljs (hunk 19 above)
Comment (ulisesmac) [reply src/react_native/safe_area_context.cljs]: This is the native component with the applied safe areas already in it, I used it but removed its usage but preferred to keep it since it may be still useful for refactoring existing screens or on maybe new ones.

Do you think I should remove it?

File: src/status_im/common/bottom_sheet/view.cljs (hunk 20 above)
Comment (ulisesmac) [reply src/status_im/common/bottom_sheet/view.cljs]: Thanks for noticing!

File: src/react_native/safe_area_context.cljs (hunk 21 above)
Comment (ulisesmac) [reply src/react_native/safe_area_context.cljs]: done

File: src/react_native/safe_area_context.cljs (hunk 22 above)
Comment (ulisesmac) [reply src/react_native/safe_area_context.cljs]: Yep, as in the comment I tagged you before, their hook causes flickering because it's updated one frame later after the safe area actually changes.

We should be able to fix it by properly using their native-based component or by refactoring our implementation, currently there's only one usage of this hook and it doesn't cause any noticeable issue.

File: src/status_im/contexts/shell/bottom_tabs/style.cljs (hunk 23 above)
Comment (ulisesmac) [reply src/status_im/contexts/shell/bottom_tabs/style.cljs]: Comments added!

**Comment by ulisesmac** [comment]
@seanstrom 
Thank you so much for asking a lot about the values used!

About the keycard flows, I recorded a video of it being used, please check it out, looks as expected:

https://github.com/user-attachments/assets/ca800bb8-5d64-4077-8075-1106d257428b

File: src/react_native/safe_area.cljs (hunk 17 above)
Comment (ilmotta) [reply src/react_native/safe_area.cljs]: Thanks @ulisesmac, that'd be good to see if you don't mind too much doing in this PR 👍🏼

File: src/react_native/safe_area_context.cljs (hunk 19 above)
Comment (ilmotta) [reply src/react_native/safe_area_context.cljs]: I would remove because the var `safe-area-view` is sort of available in two namespaces now (`react-native.core/safe-area-view*` and here).

If the var may still be useful in the future, perhaps better is to make the `safe-area-view*` public and remove the var in `safe-area-context` ns ?

File: src/react_native/core.cljs (hunk 15 above)
Comment (ilmotta) [reply src/react_native/core.cljs]: Yeah, I've seen different naming preferences in the repo as you said. I would use a different naming scheme than the asterisks to not be too similar to the earmuffs convention from the Clojure Style Guide. The `'` at the end seems alright. Honestly, I don't have any specific preference. Usually I prefer to name things explicitly, like it could be `plain-safe-area-view` or `basic-safe-area-view`, or `base-safe-area-view`.

**Review by vkjr — APPROVED** [review]

File: src/react_native/safe_area.cljs (hunk 17 above)
Comment (ulisesmac) [reply src/react_native/safe_area.cljs]: Done

**Comment by ulisesmac** [comment]
@status-im/mobile-qa 

The comments were already addressed, I will highly appreciate your testing, since this PR affects the entire app. Thank you!

**Comment by pavloburykh** [comment]
@ulisesmac thank you for the PR. 

Please take a look at the issues. 

### ISSUE 1 Android navigation bar is transparent on Community home/Discovery/Profile screens

Tested on Android 12, Samsung Galaxy A52

**Steps:** 

1. Open community home screen (for example Status community which has a long list of channels)
2. Scroll the channels
3. Pay attention at Android navigation bar (at the bottom of the screen) while scrolling

**Actual result:** 

Android navigation bar is transparent

photo_2025-04-09 14 27 25

photo_2025-04-09 14 35 56

photo_2025-04-09 14 38 36

https://github.com/user-attachments/assets/37abe082-7de2-4470-bb78-c2dde945fe95

**Expected result:**

Android navigation bar is not transparent

photo_2025-04-09 14 33 54

**Comment by pavloburykh** [comment]
### ISSUE 2 Wrong color of Android navigation bar buttons on dark background

**Steps:** 

1. Open any screen where Android navigation bar has dark background (i.e. Messages tab) or enable dark mode
2. Pay attention at the navigation bar buttons color

**Actual result:** 

photo_2025-04-09 14 42 14


**Expected result:** 

photo_2025-04-09 14 42 17

File: src/status_im/common/bottom_sheet/view.cljs (hunk 5 above)
Comment (seanstrom) [reply src/status_im/common/bottom_sheet/view.cljs]: Ah I think I see what you mean, that this is more of a special case scenario.  Overall stuff looks good 💯

**Review by seanstrom — APPROVED** [review]

**Comment by pavloburykh** [comment]
### ISSUE 3 Content/buttons are overlapped by navigation bar on several screens (Android)

@ulisesmac probably this one is related to [ISSUE 1](https://github.com/status-im/status-mobile/pull/22445#issuecomment-2789381768), but logging separately just in case

This is not the complete list of screens, might be more places

**Edit profile**

photo_2025-04-09 17 49 03

**Backup settings**

photo_2025-04-09 17 48 56

**Privacy policy**

photo_2025-04-09 17 48 53

**Terms of use**

photo_2025-04-09 17 48 50

**Comment by ulisesmac** [comment]
@pavloburykh about the issue 1, that's expected to happen in this PR (make the navbar tranaparent).

About 2, yeah, the nav buttons should be white on dark bgs.

And about 3, thanks for noticing, that's what I wanted to identify: screens where the content is overlapped with the navbar.

I'll fix these issues and ping you, thanks for testing

**Comment by pavloburykh** [comment]
Hey @ulisesmac!

> @pavloburykh about the issue 1, that's expected to happen in this PR (make the navbar tranaparent).

Sorry, that’s my mistake - I should’ve paid closer attention to the PR description, that is totally my bad. I now see that you had already mentioned this as the expected behavior. Apologies for the confusion, and thanks for clarifying!

Please ping me up once the rest of the issues are handled so I perform the re-test. Thank you.

**Comment by ulisesmac** [comment]
A quick update, @pavloburykh the issue `2` is too related to how we handle the status-bar color (the top OS bar) and I can't rely on it since it's buggy, so I'm exploring ways to fix it, I almost reached a solution, but still need to refine it, I'll take a bit more time to deliver a proper solution.

It's been reported here in the first item: 
- https://github.com/status-im/status-mobile/issues/19311

On another topic, this issue should also be solved in the current PR:
- https://github.com/status-im/status-mobile/issues/20833

Since it reworks the safe-areas.

**Comment by ulisesmac** [comment]
Just to provide context on my previous comment about status-bar colors, here's the current implementation, it breaks on both iOS & Android (look at the OS top bar)

https://github.com/user-attachments/assets/200cdfc6-5f14-4c6b-a99d-da41046ddf8d

https://github.com/user-attachments/assets/9f34d9db-e9ec-4025-b55d-e9f9ae285f71

Please link any issues reporting the bug if any.

**Comment by pavloburykh** [comment]
> Please link any issues reporting the bug if any.

Thank you @ulisesmac. I have logged an issue https://github.com/status-im/status-mobile/issues/22488 and assigned yourself.

A have added both https://github.com/status-im/status-mobile/issues/22488 https://github.com/status-im/status-mobile/issues/20833 issues in PR description.

Fix safe areas all over the app by ulisesmac · Pull Request #22445 · status-im:status-mobile 2025-04-10 17-23-26

**Comment by ulisesmac** [comment]
@pavloburykh 

I've removed the resolution of:
- #20833

from the PR description. The reason is the app is **not ready** to properly implement the transparent navigation bar on Android, so I rolled back those changes.
:disappointed: 
I noticed there are multiple screens with wrong/hardcoded padding for Android, such as the composer, fixing them all over the app will need a lot of time, not the best right now.

Additionally, regarding to the **issue 2** you mentioned, fixing that for transparent navbars is really hard, almost fixed it but the solution was ugly, I blame the navigation library, it doesn't handle these cases well. Even on develop sometimes the navbar takes a wrong color.

The navigation lib is working to solve it, but they still have work to do, check this release:
https://github.com/wix/react-native-navigation/releases/tag/7.45.0

Starting on Android 15, apps will be required to support edge-to-edge, so if we are willing to not get stale and target newer SDKs, we must solve it, but before we must upgrade the React Native version, since the nav lib no longer supports 0.73.

While working on this PR I noticed we have a significantly tech debt, we should think about strategies to tackle it along releases CC: @ilmotta

**Comment by ulisesmac** [comment]
- https://github.com/status-im/status-mobile/issues/22488

Has been only solved for Android

**Comment by pavloburykh** [comment]
Great, thanks @ulisesmac. So do I understand correctly, that PR is ready for re-test now?

**Comment by ulisesmac** [comment]
> Great, thanks @ulisesmac. So do I understand correctly, that PR is ready for re-test now? 

Yes, it's ready!

**Comment by pavloburykh** [comment]
Thanks for the fixes @ulisesmac. No issues from my side, PR is ready for merge. 

What has been tested (Android/IOS):

1. Went through different app screens and verified UI is not broken (i.e. no regresssions)
2. Android transparent navigation bar changes were reverted, it remains with background color for now
3. https://github.com/status-im/status-mobile/issues/22488 is partially fixed (bug is fixed for Android, but remains for IOS so we should keep the issue opened)
4. https://github.com/status-im/status-mobile/issues/21962 is fixed
