### PR TITLE
Fix: navigation after transaction from settings

### LINKED ISSUE #20591: The user not navigate to acitvity tab after performing transaction from Wallet settings -> saved addresses
### Steps:
1. Recover user with available assets
2. Save any address in the wallet settings -> saved addresses
3. Perform transactions directly from "saved addresses" page

### Actual result:
The user is navigated back to "saved addresses" screen after a transaction is performed

https://github.com/status-im/status-mobile/assets/52490791/7f0bc2fb-676a-4276-b836-4843b5fe69c9

### Expected result:
The user is navigated to the activity tab of the account from which the assets were sent

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 27 Jun 2024

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/20591

### Summary

This PR fixes navigation after completing a transaction from settings. After completing a transaction it should navigate to the activity tab of the sender's account.

### Demo

https://github.com/status-im/status-mobile/assets/29354102/b8b4fa64-29e8-4c77-a648-37008055deef

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -503,13 +506,18 @@
...
 (rf/reg-event-fx :wallet/end-transaction-flow
  (fn [{:keys [db]}]
-   (let [address (get-in db [:wallet :current-viewing-account-address])]
-     {:fx [[:dispatch [:wallet/navigate-to-account-within-stack address]]
+   (let [address        (get-in db [:wallet :current-viewing-account-address])
+         from-settings? (get-in db [:wallet :ui :send :from-settings?])]
+     {:fx [(when from-settings?
+             [:dispatch [:pop-to-root :shell-stack]])
+           (if from-settings?
+             [:dispatch-later [{:ms 600 :dispatch [:wallet/navigate-to-account address]}]]
```
Comment (BalogunofAfrica) [inline src/status_im/contexts/wallet/send/events.cljs]: Any reason why `600ms` was chosen as the wait time?

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/events.cljs]: @BalogunofAfrica we want to delay `navigate-to-account` until `pop-to-root` completes. I tried using less time but it did not work.

Comment (BalogunofAfrica) [reply src/status_im/contexts/wallet/send/events.cljs]: Okay. I ask because we have a case like this in this PR also:

https://github.com/status-im/status-mobile/pull/20657#discussion_r1666951709

And `1ms` seemed to work, so it gets confusing determining the arbitrary time to wait before dispatching

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/events.cljs]: @BalogunofAfrica that's something different which you mentioned (it's just delaying navigation for re-frame to update db). Here we need pop-to-root navigation to execute first (a screen navigation takes at least 300ms), then other background tasks happening may cause further delay.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 2]
```diff
@@ -493,8 +495,9 @@
             [:wallet/end-transaction-flow]]]})))
 
 (rf/reg-event-fx :wallet/clean-up-transaction-flow
- (fn [_]
-   {:fx [[:dispatch [:dismiss-modal :screen/wallet.transaction-confirmation]]
+ (fn [_ [from-settings?]]
+   {:fx [(when-not from-settings?
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/events.cljs]: I don't think we need to couple settings to this?
why not just `dismiss-modal?` or something more relevant to this particular event.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -175,7 +175,9 @@
               (assoc-in [:wallet :ui :send :to-address] to-address)
               (assoc-in [:wallet :ui :send :address-prefix] prefix)
               (assoc-in [:wallet :ui :send :receiver-preferred-networks] receiver-networks)
-              (assoc-in [:wallet :ui :send :receiver-networks] receiver-networks))
+              (assoc-in [:wallet :ui :send :receiver-networks] receiver-networks)
+              (assoc-in [:wallet :ui :send :from-settings?] from-settings?)
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/send/events.cljs]: hmm, I'm not such a fan of this data. It seems to be _off_ to couple the navigation starting point to the send data.
I think instead we should just revisit the overall navigation flow from when a user goes from the settings page.
Probably it should immediately close the settings and then initiate the wallet sending flow, i.e that the user can't navigate back to the settings page, but rather can navigate back as far as the app home on wallet tab.

Comment (J-Son89) [reply src/status_im/contexts/wallet/send/events.cljs]: i.e this is a design issue at the core.

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (BalogunofAfrica) [reply src/status_im/contexts/wallet/send/events.cljs]: You are right that they are different context. My concern is just having an arbitrary number for the delay. Also thinking if this would work the same for this context no matter where it is used. Maybe we can have a constant for these delays, not really sure of the best way to handle them.

**Review by BalogunofAfrica — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/events.cljs]: @J-Son89 so you mean it's better to reset the shell navigation to root once the send flow started from settings, and if the user exists the send flow will just be back at the current selected tab, correct?

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs]: I don't think this `dispatch-later` is a clean approach :thinking: 

We should create a mechanism to navigate a path of routes in a general way so that we don't need to manually measure the ms. Also, I'm not sure if this time (`600`) is constant across different devices or platforms :thinking: 

@OmarBasem  Do you think this issue is a correct place to explore a more general solution?

@J-Son89 I think you've done something similar to navigate, wdyt?

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/send/events.cljs]: yeah that's what I'm thinking. I think it's best to discuss this with designers first though so they're aware of the pattern as there's probably other cases. 

Maybe there's the argument to keep things even simpler and **not** include the send flow there either :)

cc @briansztamfater

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/events.cljs]: @J-Son89 I have updated it to reset shell to root when starting send flow from settings:


https://github.com/status-im/status-mobile/assets/29354102/9f1abc7f-47f0-428b-9bff-a1dfa95733e6

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/events.cljs]: @ulisesmac we checked this with Pedro in the last stand up and he said we can reset the shell to root when starting send flow from settings (demo: https://github.com/status-im/status-mobile/pull/20676#discussion_r1671977017). Now I am using a timeout of 400ms before starting the send flow as poping to root is a navigation that takes time to execute. This approach is now a little cleaner than the previous one, and I think we can consider removing the send flow from settings in the future.

**Review by J-Son89 — APPROVED** [review]
looks great, thanks for coordinating that @OmarBasem !

File: src/status_im/contexts/wallet/send/events.cljs (hunk 1 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs]: Great!, thanks @OmarBasem

**Review by ulisesmac — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Thanks for your fix.
Looks correct on both platforms.
Failed e2e are known.
You can merge your PR.
