### PR TITLE
Fix recent album not showing count

### LINKED ISSUE #17486: "Recent" album in photo gallery misses images count
**Steps:** 

1. Open any chat
2. Open photo selector (tap on Gallery button in the composer) 
3. Open list on the albums by tapping the name of currently opened album
4. Pay attention if "Recent" album has images counter

**Actual result:** "Recent" album misses images count

photo_2023-10-03 17 49 43

**Expected result:** 

[Figma](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372320&mode=design&t=B4uH12Zwl7Sy0PYH-0) 

Composer for Mobile – Figma 2023-10-03 17-53-41

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17486 

### Summary

Fixes an issue that caused the recent album in the photo picker to not have the count of all images rendered.

status: ready

### CODE REVIEW

File: src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs [hunk 1]
```diff
@@ -61,15 +61,28 @@
 
 (defn- f-album-selector
   [{:keys [scroll-enabled on-scroll]} album? selected-album top]
-  (let [albums          (rf/sub [:camera-roll/albums])
-        albums-sections [{:title no-title :data (:smart-albums albums)}
-                         {:title (i18n/label :t/my-albums) :data (:my-albums albums)}]
-        window-height   (:height (rn/get-window))]
+  (let [albums                           (rf/sub [:camera-roll/albums])
+        add-recent-count-to-recent-album (-> albums
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs]: this should be inside subscription `:camera-roll/albums-with-count`

**Review by flexsurfer — CHANGES_REQUESTED** [review]

File: src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs]: or in `:camera-roll/albums`

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs]: I went with a new subscription of :camera-roll/total-photos-count

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/photo_selector/album_selector/view.cljs]: Kindly take a look

File: src/status_im2/contexts/chat/photo_selector/events.cljs [hunk 2]
```diff
@@ -90,7 +90,14 @@
 (rf/defn on-camera-roll-get-albums
   {:events [:on-camera-roll-get-albums]}
   [{:keys [db]} albums]
-  {:db (assoc db :camera-roll/albums albums)})
+  {:db (-> db
+           (assoc :camera-roll/albums albums)
+           (assoc :camera-roll/total-photos-count
```
Comment (flexsurfer) [inline src/status_im2/contexts/chat/photo_selector/events.cljs]: still better to move to a subscription

Comment (flexsurfer) [reply src/status_im2/contexts/chat/photo_selector/events.cljs]: sometimes its better to make this in events yes, but not in this case

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/photo_selector/events.cljs]: Okey

Comment (ibrkhalil) [reply src/status_im2/contexts/chat/photo_selector/events.cljs]: Do you mind taking another look?

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hi @ibrkhalil! Thanx for the PR. Please take a look at the issues

### ISSUE 1 Recent album count number is incorrect for IOS

**Actual result:** Recent album shows the sum of images of the rest of the albums. But in fact, Recent album includes bunch of images which do not belong to other albums. So such count logic cannot be applied for IOS 

photo_2023-10-04 16 03 51

**Expected result:** here is the actual number of images that Recent album includes. 

photo_2023-10-04 16 05 43

File: src/status_im2/subs/chat/chats.cljs [hunk 3]
```diff
@@ -438,3 +438,13 @@
...
  (fn [[chat]]
    (:muted? chat)))
+
+(re-frame/reg-sub
+ :camera-roll/total-photos-count
+ (fn [{:keys [camera-roll/albums]}]
+   (->> albums
+        :my-albums
+        (reduce
+         (fn [total-album-count curr-album]
```
Comment (J-Son89) [inline src/status_im2/subs/chat/chats.cljs]: nit: consider using current-album instead👍

**Review by J-Son89 — APPROVED** [review]

File: src/status_im2/subs/chat/chats.cljs [hunk 4]
```diff
@@ -438,3 +438,13 @@
...
+           (+ total-album-count (:count curr-album)))
+         0))))
```
Comment (OmarBasem) [inline src/status_im2/subs/chat/chats.cljs]: This is incorrect. This will not get you the total photos count, but only the total of photos that are classified into albums. The camera roll library we are using does not have an option to get the total photo count. This needs to be done in native code.

Comment (ibrkhalil) [reply src/status_im2/subs/chat/chats.cljs]: I am back Saturday and will implement it, Thanks Omar!

**Comment by ibrkhalil** [comment]
@pavloburykh 
Fixed, This is from my iPhone (Please note that we're subtracting videos from the total that shows in the Photos app)
image
image
image

File: src/status_im2/subs/chat/chats.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/status_im2/subs/chat/chats.cljs]: Done PR here

https://github.com/status-im/react-native-cameraroll/pull/2

File: src/status_im2/subs/chat/chats.cljs (hunk 3 above)
Comment (ibrkhalil) [reply src/status_im2/subs/chat/chats.cljs]: Done, Thanks Jamie.

**Comment by ibrkhalil** [comment]
Done, And as per request from @OmarBasem this adds a method that returns favorites and their count [fe93660](https://github.com/status-im/status-mobile/pull/17498/commits/fe93660b88c306231ae843c388a7b89f1f7174f0)

**Comment by pavloburykh** [comment]
@ibrkhalil please take a look at the new issue

### ISSUE 2 Scrolling through Recent album results in loading the same images over and over (Android)

Reproducing Android 12, Samsung Galaxy A52

**Steps:** 

1. Open any chat
2. Open Gallery
3. Scroll through recent album
4. See if new images are uploaded while scrolling

**Actual result:** 

1. New images are not uploaded. Same images keep uploading during scrolling
2. Switching to other albums results in showing duplicated images from Recent album

https://github.com/status-im/status-mobile/assets/97245802/987c73ed-ee19-4fc7-9b3b-fa03a06fef64

**Comment by ibrkhalil** [comment]
> @ibrkhalil please take a look at the new issue
> 
> ### ISSUE 2 Scrolling through Recent album results in loading the same images over and over (Android)
> Reproducing Android 12, Samsung Galaxy A52
> 
> **Steps:**
> 
> 1. Open any chat
> 2. Open Gallery
> 3. Scroll through recent album
> 4. See if new images are uploaded while scrolling
> 
> **Actual result:**
> 
> 1. New images are not uploaded. Same images keep uploading during scrolling
> 2. Switching to other albums results in showing duplicated images from Recent album
> 
>  telegram-cloud-document-2-5271698414512386993.mp4

Fixed.

**Comment by pavloburykh** [comment]
@ibrkhalil could you please rebase the PR and resolve conflicts?

**Comment by ibrkhalil** [comment]
> @ibrkhalil could you please rebase the PR and resolve conflicts?

Rebased, Thank you

**Comment by pavloburykh** [comment]
> Fixed.

@ibrkhalil issue is not fixed and still reproducible

https://github.com/status-im/status-mobile/assets/97245802/e9b6c2a7-74cf-48b6-ab3b-3bfb72bf2a02

One major request: please perform at least basic smoke check of your fixes to verify them before requesting manual qa. In this particular case quick smoke check would show that issue is still there. Thank you!

**Comment by ibrkhalil** [comment]
Apologies @pavloburykh
It's fixed now.

**Comment by pavloburykh** [comment]
@ibrkhalil thanx, ISSUE 2 is fixed. Please take a look at some other issues

### ISSUE 3 Recent shows 0 images when gallery is opened for the first time (IOS)

Reproducible in IOS 16.1 iPhoneX

**Steps:** 

1. Create new user
2. Open any chat
3. Open gallery
4. Go to albums list
5. Pay attention at images count of Recent album

**Actual result:** in my case it shows 0, in fact there are 6501 images inside. Count is updated after gallery re-opening

photo_2023-10-18 18 49 11


**Expected result:** 

photo_2023-10-18 18 49 14

**Comment by pavloburykh** [comment]
### ISSUE 4 Album picture shows video preview if there is video inside

**Steps:** 

1. Record any video on device
2. Open Status app - any chat - gallery view - list of albums
3. Pay attention at the album image where recorded video has been stored

**Actual result:** video preview is shown as album image. 


https://github.com/status-im/status-mobile/assets/97245802/7b17766a-3a02-4ed7-8a4e-02b179713857


**Expected result:** only images should be shown in preview as we do not show videos inside albums.

**Comment by ibrkhalil** [comment]
> @ibrkhalil thanx, ISSUE 2 is fixed. Please take a look at some other issues
> 
> ### ISSUE 3 Recent shows 0 images when gallery is opened for the first time (IOS)
> Reproducible in IOS 16.1 iPhoneX
> 
> **Steps:**
> 
> 1. Create new user
> 2. Open any chat
> 3. Open gallery
> 4. Go to albums list
> 5. Pay attention at images count of Recent album
> 
> **Actual result:** in my case it shows 0, in fact there are 6501 images inside. Count is updated after gallery re-opening
> 
> photo_2023-10-18 18 49 11
> 
> **Expected result:**
> 
> photo_2023-10-18 18 49 14

Wondering if it's a new user issue Or a permissions issue.

**Comment by pavloburykh** [comment]
> Wondering if it's a new user issue Or a permissions issue.

not sure. Could be permission issue as well. reproducing when I open gallery for the first time and granting permissions.

**Comment by ibrkhalil** [comment]
Thank you so much for your time and patience Pavlo, The last two issues should be fixed now.

**Comment by pavloburykh** [comment]
@ibrkhalil 

### ISSUE 5 "Undefined is not a function" error when opening gallery on Android

Reproducing on Android 12, Samsung Galaxy A52.

@ibrkhalil this issue could easily be found as a result of basic smoke check of the fix. 

**Steps:** 

1. Open chat
2. Open gallery
3. Observe the error

**Actual result:** "undefined is not a function" error is displayed. 

photo_2023-10-23 10 16 04
[Status-debug-logs (71).zip](https://github.com/status-im/status-mobile/files/13067170/Status-debug-logs.71.zip)

https://github.com/status-im/status-mobile/assets/97245802/6557f21d-350d-4833-8085-10f3176efb50


**Expected result:** no error

**Comment by ibrkhalil** [comment]
> @ibrkhalil
> 
> ### ISSUE 5 "Undefined is not a function" error when opening gallery on Android
> Reproducing on Android 12, Samsung Galaxy A52.
> 
> @ibrkhalil this issue could easily be found as a result of basic smoke check of the fix.
> 
> **Steps:**
> 
> 1. Open chat
> 2. Open gallery
> 3. Observe the error
> 
> **Actual result:** "undefined is not a function" error is displayed.
> 
> photo_2023-10-23 10 16 04 [Status-debug-logs (71).zip](https://github.com/status-im/status-mobile/files/13067170/Status-debug-logs.71.zip)
> 
>  telegram-cloud-document-2-5309925075145732218.mp4 
> **Expected result:** no error

Really sorry Pavlo, I forgot a silly something.
Fixing

**Comment by ibrkhalil** [comment]
Should be working now.

**Comment by churik** [comment]
@ibrkhalil 
## ISSUE 6: on Android 10 images are not shown in all albums
This is the reason for failed e2e.

https://github.com/status-im/status-mobile/assets/4557972/3f642f3a-2147-444b-bfdc-d4dcede52fe1

Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13070967/Status-debug-logs.zip)

**Comment by churik** [comment]
Cross-posting with https://github.com/status-im/status-mobile/pull/17241#issuecomment-1770512275

**Comment by ibrkhalil** [comment]
> Cross-posting with [#17241 (comment)](https://github.com/status-im/status-mobile/pull/17241#issuecomment-1770512275)

Fixed.

**Comment by pavloburykh** [comment]
@ibrkhalil something is wrong with the builds after recent rebase. Please take a look

Fix recent album not showing count by ibrkhalil · Pull Request #17498 · status-im:status-mobile 2023-10-24 14-35-39

**Comment by ibrkhalil** [comment]
@pavloburykh Should be working now, Thank you!

**Comment by pavloburykh** [comment]
> @pavloburykh Should be working now, Thank you!

@ibrkhalil is it okay that there is still warning from packages-check-bot? 

Fix recent album not showing count by ibrkhalil · Pull Request #17498 · status-im:status-mobile 2023-10-24 15-17-28

**Comment by ibrkhalil** [comment]
> > @pavloburykh Should be working now, Thank you!
> 
> @ibrkhalil is it okay that there is still warning from packages-check-bot?
> 
> Fix recent album not showing count by ibrkhalil · Pull Request #17498 · status-im:status-mobile 2023-10-24 15-17-28

It's just a warning about a library's git endpoint wanting to end with .git, But unfortunately adding .git to its path doesn't work. (And it's not required to merge, Which I think it means we can ignore it)

**Comment by pavloburykh** [comment]
@ibrkhalil thank you for the PR. Tested and ready for merge.
