### PR TITLE
fix group Image can't be set up during group creation in Android

### LINKED ISSUE #19993: [Android] Group Image can't be set up during group creation
Also, if you select/take a photo, the selected color will be reset once the group chat is created. 

### Steps:
1. Go to group creation flow
2. Set up image during group creation
3. Select color 
4. Check if the image is set up and the color is the same after the group is created

### Actual result:
The image for the group is not set up

https://github.com/status-im/status-mobile/assets/52490791/78ce5224-ed8c-4f39-9685-2daef9de02f5

### Expected result:
The image for the group is set up

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/15291219/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19993

### Testing
- Please make sure ios is working as expected 
- 19993 also reports another issue specific to iOS, where on the group creation, the image is not visible, but on reopening chat it is. This one looks somewhat timing issue, we probably are navigating to chat on group chat creation but we are updating the image later. I will explore this issue separately.

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM

File: src/status_im/contexts/chat/group_create/events.cljs [hunk 1]
```diff
@@ -30,7 +31,7 @@
  (fn [_ [{:keys [chat-id group-name color image]}]]
    {:json-rpc/call [{:method      "chat_editChat"
                      :params      ["" chat-id group-name (name color)
-                                   {:imagePath image
+                                   {:imagePath (when image (string/replace-first image #"file://" ""))
```
Comment (flexsurfer) [inline src/status_im/contexts/chat/group_create/events.cljs:34]: could  you please give some details? thanks

Comment (Parveshdhull) [reply src/status_im/contexts/chat/group_create/events.cljs:34]: hi @flexsurfer, Thank you very much for reviewing PR.

Without replacing `file://` rpc call was returning an error
image

So I used the same solution as we currently have for profile picture
https://github.com/status-im/status-mobile/blob/df939bf85fd03f1a6a1da0e2ba8d9252949d92e1/src/status_im/contexts/profile/edit/header/events.cljs#L30
(@mohsen-ghafouri probably knows why and how this works)

btw, unless I made some mistake while testing it seems group picture didn't worked for android, even in https://github.com/status-im/status-mobile/pull/19128

Comment (flexsurfer) [reply src/status_im/contexts/chat/group_create/events.cljs:34]: thank you, i was wondering why we have to do it only here and not as a general solution

Comment (Parveshdhull) [reply src/status_im/contexts/chat/group_create/events.cljs:34]: > not as a general solution

We can modify `avatar-picture-picker` itself to return the final image with the removed `file://` but it seems only status-go has a problem with `file://` and fast-image etc. don't work after removal.

Having a general solution will be great, but that probably will require some exploration to find out why status-go and mobile are processing paths differently for Android. Maybe we can look into this in a separate issue, wdyt?

Comment (Parveshdhull) [reply src/status_im/contexts/chat/group_create/events.cljs:34]: created an issue: https://github.com/status-im/status-mobile/issues/20454

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/contexts/chat/group_create/events.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/contexts/chat/group_create/events.cljs:34]: thank you

**Comment by pavloburykh** [comment]
@Parveshdhull thanks for the PR. No issues from my side. PR is ready for merge. 

BTW, regarding ```19993 also reports another issue specific to iOS, where on the group creation, the image is not visible``` - I am not reproducing it neither in develop nor in this PR. I have tried on iPhoneX, IOS 16.7.7

File: src/status_im/contexts/chat/group_create/events.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/chat/group_create/events.cljs:34]: It's not a general issue on all android versions, but by replacing "file://", it converts the URL format to a plain file path, which is more universally accepted by various Android APIs and libraries
