### PR TITLE
fix onboarding navigation to enable notification screen and blur issues

### LINKED ISSUE #20719: List of issues on Onboarding screen
# Bug Report

Here are several leftovers from https://github.com/status-im/status-mobile/pull/20503

#### Actual behavior

1) No blur on `Enable Notifications` and `Welcome to web3!` screens

Screenshot 2024-07-11 at 12 07 25 Screenshot 2024-07-11 at 12 07 35

2) No smooth transition from `Key Saved!` to `Enable Notifications` screen
Please, look what I am talking about : 

https://github.com/status-im/status-mobile/assets/147824399/7858f9cd-8477-48a9-af2e-2dd59486d705

3) Pixel 7a (Android 14) has unexpected white space at the bottom of the screen:

Screenshot 2024-07-09 at 16 29 31

### Reproduction

1. Install app
2. Tap `Let's go`
3. Go through onboarding screens

### Additional Information

- Status version: nightly 11/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by jo-mut**
fixes https://github.com/status-im/status-mobile/issues/20719

In this pr, we are navigating from generate keys screen to enable notifications screen without using `init-root` while preserving blur which is crucial for enable notification screen and welcome screen. This pr fixes the issues reported https://github.com/status-im/status-mobile/pull/20503/files#r1654635905 as a result of navigating to the notification screen using `init-root`

A side note  I removed `:screen/onboarding.enable-notifications` and `:screen/onboarding.welcome` from the roots file as they dont seem to be needed

### Summary

https://github.com/status-im/status-mobile/assets/28704507/a78cc878-7f51-459f-b2f3-7c2616aaaf26

### CODE REVIEW

**Review by flexsurfer — COMMENTED** [review]
you need to change `:onboarding/navigate-to-enable-notifications` so it will navigate with current stack

**Comment by Parveshdhull** [comment]
> :onboarding/navigate-to-enable-notifications

maybe event name is confusing, but we have `navigate-to-within-stack` 
https://github.com/status-im/status-mobile/blob/180065129fa22d271f7367b73834c5da10822f92/src/status_im/contexts/onboarding/events.cljs#L42

**Comment by flexsurfer** [comment]
and if there are some more screens after notification their stack also should be changed

**Comment by jo-mut** [comment]
@flexsurfer I think I understand you now, since the user at this point has navigated to generate-keys screen we should not use `:onboarding/navigate-to-enable-notifications` as is. This i have been missing I guess in your reviews. My bad

File: src/status_im/contexts/onboarding/events.cljs [hunk 1]
```diff
@@ -73,7 +74,8 @@
                                       :onboarding/navigated-to-enter-seed-phrase-from-screen
                                       :screen/onboarding.new-to-status)]]
                :dispatch-later [{:ms       constants/onboarding-generating-keys-animation-duration-ms
-                                 :dispatch [:init-root :screen/onboarding.enable-notifications]}]
+                                 :dispatch [:onboarding/navigate-to-enable-notifications
```
Comment (flexsurfer) [inline src/status_im/contexts/onboarding/events.cljs]: do we have only one screen? or there are more in onboarding flow after notifications?

Comment (jo-mut) [reply src/status_im/contexts/onboarding/events.cljs]: we do have the welcome screen

Comment (flexsurfer) [reply src/status_im/contexts/onboarding/events.cljs]: then it should be changed as well

Comment (jo-mut) [reply src/status_im/contexts/onboarding/events.cljs]: @flexsurfer the changes have been updated now just waiting for your approval

File: src/status_im/contexts/onboarding/enable_notifications/view.cljs [hunk 2]
```diff
@@ -38,7 +38,7 @@
                               (rf/dispatch [:push-notifications/switch true])
                               (rf/dispatch [:navigate-to-within-stack
                                             [:screen/onboarding.welcome
-                                             :screen/onboarding.enable-notifications]]))
+                                             :screen/onboarding.generating-keys]]))
```
Comment (flexsurfer) [inline src/status_im/contexts/onboarding/enable_notifications/view.cljs:41]: could you elaborate?

File: src/status_im/contexts/onboarding/identifiers/view.cljs [hunk 3]
```diff
@@ -22,7 +22,7 @@
 
 (defn- navigate-to-enable-notifications
   []
-  (rf/dispatch [:onboarding/navigate-to-enable-notifications]))
+  (rf/dispatch [:onboarding/navigate-to-enable-notifications :screen/onboarding.identifiers]))
```
Comment (flexsurfer) [inline src/status_im/contexts/onboarding/identifiers/view.cljs]: could you elaborate?

Comment (jo-mut) [reply src/status_im/contexts/onboarding/identifiers/view.cljs]: Well this screen is not needed we decided to keep the file. I changed the code here for completion.

Comment (jo-mut) [reply src/status_im/contexts/onboarding/identifiers/view.cljs]: @flexsurfer it should be `screen/onboarding.generating-keys` not `:screen/onboarding.identifiers`. I have updated that

File: src/status_im/contexts/onboarding/events.cljs [hunk 4]
```diff
@@ -40,8 +40,9 @@
                [:screen/onboarding.enable-notifications :screen/onboarding.enable-biometrics]]}))
 
 (rf/reg-event-fx :onboarding/navigate-to-enable-notifications
- (fn [{:keys [db]}]
-   {:dispatch [:navigate-to-within-stack
+ (fn [{:keys [db]} from-screen]
+   {:db       (assoc db :onboarding/navigated-to-enter-seed-phrase-from-screen from-screen)
```
Comment (flexsurfer) [inline src/status_im/contexts/onboarding/events.cljs]: could you pls elaborate on why `{:db (assoc db :onboarding/navigated-to-enter-seed-phrase-from-screen from-screen)` is needed here ?

Comment (jo-mut) [reply src/status_im/contexts/onboarding/events.cljs]: this function does not navigate from the new stack which is why I updated, the name of  db path the function could change to `onboarding/navigated-from-screen` alternatively I could also just `[:navigate-to-within-stack [:screen/onboarding.enable-notifications :screen/onboarding.generating-keys]]` and this way we dont have to update the db

**Review by flexsurfer — APPROVED** [review]

**Comment by jo-mut** [comment]
@mariia-skrypnyk this is ready for qa

**Comment by mariia-skrypnyk** [comment]
Hey @jo-mut !

Thanks for pinging me!
Looks good from my side.
Think it need a review by @Francesca-G as well.

**Review by Francesca-G — APPROVED** [review]
Looks good to me 👍
