### PR TITLE
fix: activity center notifications swipe style

### LINKED ISSUE #16081: Activity Center - Notifications - Design Review
Accept + Decline swipe -> add icons (currently using placeholder)
also there should be no margin on left or right of swipe actions (edge to edge)
accept + decline swipe action colors should match button colors

Movie_Recording_2023-05-30_13-11-02

`Figma > Shell for Mobile > Notification Center` https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=6105-546987&t=ZCmbCodo8GhbKuCu-0

### PR DESCRIPTION
**Pull request by codemaster115**
fixes #16081 
### Summary
- Replace placeholder icons in swipe action buttons (accept/decline)
- Remove margin on left and right while swipe

### Testing notes
You can send a contact request or whatever else to get a notification.
And you can check the swipe actions of the notification item.

Here is the animation that I recorded after the fixes.
https://github.com/status-im/status-mobile/assets/39961806/8ad24f04-a522-4dcd-abc2-851123fa1851

status: ready

### CODE REVIEW

File: src/quo2/components/notifications/activity_log/style.cljs [hunk 1]
```diff
@@ -6,7 +6,7 @@
    :flex-grow          1
    :align-items        :flex-start
    :padding-top        8
-   :padding-horizontal 12
+  ;;  :padding-horizontal 12
```
Comment (J-Son89) [inline src/quo2/components/notifications/activity_log/style.cljs]: Please delete unused code

Comment (vkjr) [inline src/quo2/components/notifications/activity_log/style.cljs]: We can just remove it)

**Comment by smohamedjavid** [comment]
@codemaster115 - The tests are failing due to lint. Please run `make lint-fix`.

File: src/quo2/components/notifications/activity_log/style.cljs (hunk 1 above)
Comment (codemaster115) [reply src/quo2/components/notifications/activity_log/style.cljs]: Sorry for that, I pushed the changes, but not updated them here due to the current service incident.

File: src/status_im2/contexts/activity_center/style.cljs [hunk 2]
```diff
@@ -16,8 +16,7 @@
 
 (defn notification-container
   [index]
-  {:margin-top         (if (zero? index) 0 4)
-   :padding-horizontal 8})
+  {:margin-top         (if (zero? index) 0 4)})
```
Comment (vkjr) [inline src/status_im2/contexts/activity_center/style.cljs]: Indentation flows) You will need to run a `make lint-fix` to fix small stuff like this. Otherwise, the `jenkins/pr/tests` check won't pass.

Comment (codemaster115) [reply src/status_im2/contexts/activity_center/style.cljs]: It's the same Github incident. It's already fixed on my branch, but not shown in the PR.

Comment (vkjr) [reply src/status_im2/contexts/activity_center/style.cljs]: The check itself:
Screenshot 2023-06-07 at 18 26 05

Details:
Screenshot 2023-06-07 at 18 25 50

**Review by vkjr — CHANGES_REQUESTED** [review]
lint fixes required

**Review by smohamedjavid — APPROVED** [review]
LGTM 🚀 

Except the lint issues which will be resolved as soon as Github services are back online.

Nice work @codemaster115!

File: src/status_im2/contexts/activity_center/style.cljs (hunk 2 above)
Comment (vkjr) [reply src/status_im2/contexts/activity_center/style.cljs]: > It's the same Github incident. It's already fixed on my branch, but not shown in the PR.

Then all perfect! 🤌

**Review by smohamedjavid — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
I didn't check the code so much but looked at the application and the behaviour looks correct. Nice work 👌

File: src/quo2/components/notifications/activity_log/style.cljs (hunk 1 above)
Comment (codemaster115) [reply src/quo2/components/notifications/activity_log/style.cljs]: It's already deleted. Seems like you're looking at old version.

**Review by ajayesivan — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by flexsurfer** [comment]
@J-Son89 should we test this or merge ?

**Comment by J-Son89** [comment]
I'll speak with @codemaster115 and get this sorted. I think it's all good here 👍

File: src/status_im2/contexts/activity_center/notification/common/view.cljs [hunk 3]
```diff
@@ -35,13 +35,14 @@
            interpolation-translate-x
            on-press
            swipe-button
-           swipeable-ref]}]
+           swipeable-ref
+           style]}]
```
Comment (J-Son89) [inline src/status_im2/contexts/activity_center/notification/common/view.cljs:39]: hmm do we need style as a param here or can it just be statically imported from the style file?

**Review by J-Son89 — APPROVED** [review]

**Comment by J-Son89** [comment]
@qoqobolo, @pavloburykh or @VladimrLitvinenko could one of you take a look at this pr when you have some available time :)

**Comment by VolodLytvynenko** [comment]
hi @codemaster115. Thank you for your work. Here is one found issue:

## ISSUE 1: "Accept" and "Decline" buttons display old placeholder for Join Community Request
1. User_A creates closed community
2. User_A shares current community to User_B
3. User_B sends Request to join to the community
4. User_A checks request in the AC

### Actual result:
The Accept and Decline buttons are with old placeholder for community request
image

### Expected result:
The Accept and Decline buttons are with new placeholder for community request
image

**Comment by VolodLytvynenko** [comment]
## ISSUE 2:  "Reply" and "Decline" buttons display an old placeholder for "Identity verifications" request
### Preconditions:
`A` is a desktop user (for now the "Identity verifications" requests can be sent only by desktop.)

### Steps to reproduce:
1. `A` and `B` are mutual contacts.
2. `A` sends a verification request to `B`. 
3. `A` Open the profile of the `B` 
4. `A` Click on the ellipsis (...) icon.
5. `A`  Select  "Verify identity" from the options.
6. `A` Send the verification request.
image
7. `B` Checks the "Verify identity" request in AC

### Actual result:
"Reply" and "Decline" buttons display an old placeholder for "Identity verifications" request
image
image
### Expected result:
The new placeholders are shown for "Reply" and "Decline" buttons

**Comment by codemaster115** [comment]
@VladimrLitvinenko Thanks for your review.
I fixed 2 issues and updated so please review again.

**Comment by VolodLytvynenko** [comment]
@codemaster115  Could you please resolve existing conflicts? After that, we can perform manual testing. Thanx!

**Comment by codemaster115** [comment]
> @codemaster115 Could you please resolve existing conflicts? After that, we can perform manual testing. Thanx!

@VladimrLitvinenko Done

**Comment by VolodLytvynenko** [comment]
Hi @codemaster115 Thank you for your work. Issues are fixed. PR is ready to be merged
