### PR TITLE
[#21644] fix: display zero for empty balances asset

### LINKED ISSUE #21644: Assets price estimation shows <0.01 instead of 0.00 on wallet page for empty balances assets
### Steps:
1. Create new accout 
2. Go to wallet
3. Check default assets (example: snt, dai, eth)

### Actual result:
The price for empty assets is estimated as <0.01 instead of 0.00
Image

### Expected result:
The price for empty assets is estimated as 0.00
Image
https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj/Release-Reviews?node-id=2224-52505&node-type=frame&t=vBnHYbjs4GLbtknb-0#934563934
### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17
### ENV:
Nightly 20 Nov, 2024

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21644

### Summary

The price for empty assets should estimated as 0.00

#### Areas that maybe impacted

- Wallet page -> asset list

### Steps to test

- Create new accout
- Go to wallet
- Check default assets (example: snt, dai, eth)

### Result

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 1]
```diff
@@ -294,8 +301,8 @@
         formatted-token-price    (prettify-balance currency-symbol price)
         percentage-change        (prettify-percentage-change change-pct-24h)
         crypto-value             (get-standard-crypto-format token balance prices-per-token)
-        fiat-value               (fiat-formatted-for-ui currency-symbol
-                                                        fiat-unformatted-value)]
+        fiat-value               (asset-fiat-formatted-for-ui currency-symbol
+                                                              fiat-unformatted-value)]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/common/utils.cljs]: I would suggest updating/fixing the actual `fiat-formatted-for-ui` method because this bug will be fixed in the tokens list in the home or account page, but will have the same bug in other places, like in the tx flows.

https://github.com/status-im/status-mobile/blob/763b2916292d5673fa1b9de863f987c885cb2783/src/status_im/contexts/wallet/common/utils.cljs#L267-L271

Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/common/utils.cljs]: I wanted to do but I saw many usage of that func in different area. it was used also for fees value.

Comment (smohamedjavid) [reply src/status_im/contexts/wallet/common/utils.cljs]: I believe it's needed because if the balance is 0, we can't mislead the user with `< $0.01` in the value displayed. Also, the fees are never 0, so it should be fine.

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Nice fix.
E2E looks good.
PR can be merged.

File: src/status_im/contexts/wallet/common/utils.cljs (hunk 1 above)
Comment (mohsen-ghafouri) [reply src/status_im/contexts/wallet/common/utils.cljs]: make sense, done

**Comment by mohsen-ghafouri** [comment]
Hey @mariia-skrypnyk thanks for testing it, would you mind to rerun the test again? i just pushed small changes (shouldn't effect anything but just to make sure before merging it)

**Review by vkjr — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri should I check any regression?

E2E looks good.

**Comment by mohsen-ghafouri** [comment]
No thanks @mariia-skrypnyk, it's fine.
