### PR TITLE
fix: address input multiline

### LINKED ISSUE #19788: The pasted ETH addresses in 'Send To' page is partially visible
### Steps:
1. Go to 'send to' page
2. Paste the eth address

### Actual result:
The pasted ETH address is not fully visible, making it difficult for the user to verify its correctness
image

### Expected result:
The pasted ETH address should be fully visible for the user to verify its correctness, including seeing its beginning and end.
image

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=12984%3A186636&mode=dev
### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19788

### Summary
This PR fix addresses input to support multiline.

### Demo

https://github.com/status-im/status-mobile/assets/29354102/7a45a979-e4e8-474f-9130-dd164277d39c

### CODE REVIEW

File: src/quo/components/inputs/address_input/style.cljs [hunk 1]
```diff
@@ -35,7 +36,8 @@
          :color        (colors/theme-colors colors/neutral-100 colors/white theme)
          :margin-top   (if platform/ios? 0 -4)
          :margin-right 8
-         :height       (if platform/ios? 24 40)))
+         :max-height   (+ (* input-height 2) (when platform/ios? 1))
```
Comment (shivekkhurana) [inline src/quo/components/inputs/address_input/style.cljs]: Why do we have this odd number ? Why add 1 for ios? 

Can this just be `:max-height 48` ?

**Review by shivekkhurana — CHANGES_REQUESTED** [review]

File: src/quo/components/inputs/address_input/style.cljs (hunk 1 above)
Comment (OmarBasem) [reply src/quo/components/inputs/address_input/style.cljs]: @shivekkhurana actually not needed, updated it 👍 

> Can this just be :max-height 48

48 wouldn't work. We can simply make the max-height 50

**Review by shivekkhurana — APPROVED** [review]

File: src/quo/components/inputs/address_input/style.cljs [hunk 2]
```diff
@@ -35,7 +34,8 @@
          :color        (colors/theme-colors colors/neutral-100 colors/white theme)
          :margin-top   (if platform/ios? 0 -4)
          :margin-right 8
-         :height       (if platform/ios? 24 40)))
+         :max-height   50
```
Comment (J-Son89) [inline src/quo/components/inputs/address_input/style.cljs:36]: so this component is used in quite a few places. Can we check all uses and ensure it's fine before/after? 🙏

Comment (OmarBasem) [reply src/quo/components/inputs/address_input/style.cljs:36]: @J-Son89 I see it is used only on `status-im.contexts.wallet.send.select-address.view`

File: src/quo/components/inputs/address_input/style.cljs [hunk 3]
```diff
@@ -35,7 +34,8 @@
...
+         :padding      0))
```
Comment (ulisesmac) [inline src/quo/components/inputs/address_input/style.cljs:37]: @OmarBasem Did you check how it is looking on Android? I'm asking because we used different numbers for each platform before. It'd be great if you add an screenshot (or video) for Android too :+1:

Comment (OmarBasem) [reply src/quo/components/inputs/address_input/style.cljs:37]: @ulisesmac the video is for Android :)

I have tested the branch on both platforms. That value is not a `height` value but rather `max-height` which allows each platform's input to adjust accordingly

Comment (ulisesmac) [reply src/quo/components/inputs/address_input/style.cljs:37]: You're right, thanks!

**Review by ulisesmac — APPROVED** [review]
Thanks for the PR @OmarBasem !

**Comment by qoqobolo** [comment]
Hi @OmarBasem, thanks for PR!

### ISSUE 1: Address is not aligned with the check icon on Android

Screenshot 2024-05-14 at 11 53 00

Design

Screenshot 2024-05-14 at 11 53 33

**Comment by OmarBasem** [comment]
Thanks for your testing @qoqobolo, fixed the issue!

**Comment by qoqobolo** [comment]
Thanks @OmarBasem , but it's not aligned on iOS now 🥲

image
image

Figma

https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=689-192841&m=dev

Screenshot 2024-05-15 at 15 09 26

Screenshot 2024-05-15 at 15 09 54

**Review by J-Son89 — APPROVED** [review]

**Comment by OmarBasem** [comment]
Thanks for your testing @qoqobolo! Please check now and let me know

**Comment by qoqobolo** [comment]
Thanks @OmarBasem, PR can be merged.
