### PR TITLE
[16845] Wrong buttons background color on community home screen's page nav

### LINKED ISSUE #16845: Wrong buttons' background color on community home screen when overlay layer is applied (Android)
Followup of https://github.com/status-im/status-mobile/pull/16772 cc @J-Son89 

**Steps:** 

1. Open community home page
2. Open Context menu bottom sheet
3. Pay attention at cancel/3 dots buttons' background

**Actual result:** 

photo_2023-08-01 14 36 53

https://github.com/status-im/status-mobile/assets/97245802/a16c037d-3918-4aa7-9e3c-03fd8f942e91

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1561-125067&mode=design&t=m43Z00HffrgciimR-0) 

Communities for Mobile – Figma 2023-08-01 17-30-36
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16845 

### Summary

The state of whether to show the blurred version of the buttons didn't cater for bottom sheet being open (Specifically when it's overlay is visible) And blurring on Android showed in a wrong way because of a limitation/incosistency of blurring between iOS and Android

Figma (State: Light collapsed drawer)            |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

Figma  (State: Light opened drawer)           |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

Figma (State: Dark collapsed drawer)            |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

Figma (State: Dark opened drawer)            |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

This is not 100% matching figma, But it's as close as possible.
status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

**Review by J-Son89 — COMMENTED** [review]
@ibrkhalil did you check with design about this is how it should work? 🤔 

Also I noticed in the preview images you added the community being used has no banner image, it's better to avoid testing with this community as banner images are mandatory to make and so it's better to test with a community that has one in place (i.e not generated in mobile)

**Comment by ibrkhalil** [comment]
> @ibrkhalil did you check with design about this is how it should work? thinking
> 
> Also I noticed in the preview images you added the community being used has no banner image, it's better to avoid testing with this community as banner images are mandatory to make and so it's better to test with a community that has one in place (i.e not generated in mobile)

Let me test it on a community with a banner image
I didn't check with design about it as it was just to fix the blurring of the buttons, But I agree it's better to run this by them.

**Comment by J-Son89** [comment]
> > @ibrkhalil did you check with design about this is how it should work? thinking
> > Also I noticed in the preview images you added the community being used has no banner image, it's better to avoid testing with this community as banner images are mandatory to make and so it's better to test with a community that has one in place (i.e not generated in mobile)
> 
> Let me test it on a community with a banner image I didn't check with design about it as it was just to fix the blurring of the buttons, But I agree it's better to run this by them.

yep because in the designs if the configuration of buttons  does not change based on bottom sheet opening then the issue is not related to this and it's probably just how the buttons are swapping based on scroll height of the page.

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil thank you for PR. Here is a found issue:

## ISSUE 1: Background is slightly visible for buttons when overlay layer is applied
### Steps:
1. Set banner for community
2. Open overlay
3. Check the community buttons

### Actual result:
Background for community buttons is slightly visible
https://github.com/status-im/status-mobile/assets/52490791/927c6b50-613f-49ae-a813-2ae66a9cf2a4

image

### Expected result:
The background behind the community buttons should have a lighter appearance, in accordance with the design.

image
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1506-122194&mode=design&t=G30NMgsqrioQQIy2-0

### Device:
- real device: Pixel 7a, Android 13
- - real device: iPhone 11 pro max, ios 16

**Comment by ibrkhalil** [comment]
Blocked by: https://github.com/status-im/status-mobile/issues/17017

**Comment by ibrkhalil** [comment]
@VolodLytvynenko Might be fixed in https://github.com/status-im/status-mobile/pull/17031
Let's check if it's fixed there and if so, We can close this issue/PR as resolved.

**Comment by ibrkhalil** [comment]
> @VolodLytvynenko Might be fixed in #17031 Let's check if it's fixed there and if so, We can close this issue/PR as resolved.

PR is merged, Kindly take a look @VolodLytvynenko  so that we can close this issue.

**Comment by VolodLytvynenko** [comment]
> > @VolodLytvynenko Might be fixed in #17031 Let's check if it's fixed there and if so, We can close this issue/PR as resolved.
> 
> PR is merged, Kindly take a look @VolodLytvynenko so that we can close this issue.

Thank you. I'll keep you updated if this issue persists. Otherwise, I will close this PR

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil the issue 1 is resolved. 
One more issue is introduced

## ISSUE 2: [Android] Buttons are not blurred when overlay layer is applied

### Steps
1. Open a community with a banner.
2. Open the overlay layer.

### Actual result:
The buttons in the community are not blurred when the overlay layer is applied.
image

### Expected result:
The buttons should be blurred in accordance with the design when the overlay layer is applied.
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1506-122194&mode=design&t=G30NMgsqrioQQIy2-0

### Device:
- real device: Pixel 7a, Android 13

**Comment by VolodLytvynenko** [comment]
@ibrkhalil Could you please check this new issue if it can be addressed within the scope of this PR? Let me know if it would be better to address it separately. I can create a separate follow-up for it if needed. Thank you

## ISSUE 3: The [x] button is not blurred regardless the overlay layer is applied or not
### Steps
1. Open a community with a banner.
2. Check the [x] button
3. Open the overlay layer
4. Check the [x] button

### Actual result:
The [x] button is not blurred regardless of whether the overlay layer is applied or not.

image

### Expected result:
The [x] button should be blurred in accordance with the design when the overlay layer is applied or not.

**Comment by ibrkhalil** [comment]
I rewrote the solution, Re-requesting reviews

File: src/quo2/components/buttons/button/style.cljs [hunk 1]
```diff
@@ -1,8 +1,10 @@
-(ns quo2.components.buttons.button.style)
+(ns quo2.components.buttons.button.style 
+  (:require [quo.platform :as platform]))
 
-(def blur-view
+(defn blur-view [size]
   {:position :absolute
-   :top      0
+   :height   (if platform/android? size :auto)
+   :top      (if platform/android? size 0)
```
Comment (ibrkhalil) [inline src/quo2/components/buttons/button/style.cljs]: This change is necessary to fix an incosistency between blur on iOS and Android

File: src/quo2/components/buttons/button/properties.cljs [hunk 2]
```diff
@@ -19,7 +19,7 @@
                          (colors/theme-colors colors/white-opa-40
                                               colors/neutral-80-opa-40
                                               theme))
-   :blur-type          (if (= theme :light) :light :dark)})
+   :blur-type          (if (= theme :light) :ultraThinMaterialLight :thinMaterialDark)})
```
Comment (ibrkhalil) [inline src/quo2/components/buttons/button/properties.cljs]: According to [react-native-blur repo](https://github.com/Kureev/react-native-blur#blurtype-ios-13-only) this is only affecting iOS 13+ as it's not supported on Android.

**Comment by J-Son89** [comment]
nice one @ibrkhalil, could you please check this doesn't break other uses of the background `photo` in the application?

one other instance of this is in the chat when you add photos and start scrolling

https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372350&mode=design&t=8adBwIbDQuuABOY6-0

**Comment by ibrkhalil** [comment]
> nice one @ibrkhalil, could you please check this doesn't break other uses of the background `photo` in the application?
> 
> one other instance of this is in the chat when you add photos and start scrolling
> 
> https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372350&mode=design&t=8adBwIbDQuuABOY6-0

Thanks for pointing this out Jamie!
Here's how it looks there, I don't think there's something wrong in it.

<table>
  <tr>
    <td> </td>
    <td></td>
   </tr> 
</table>

**Comment by ilmotta** [comment]
@ibrkhalil, from the screenshot you shared above on Android, the "Clear" button background is semi-transparent, whereas in Figma it's much more opaque due to the correct blur. A semi-transparent button with poor readability seems very amateurish and I think users notice this. We see black text on top of black squares and it looks bad.

If we can't show what's in Figma on Android, then I think we should have a better fallback than a semi-transparent button. cc'ing @Francesca-G here.

**Expected**:

**Comment by ibrkhalil** [comment]
> 
> 
> @ibrkhalil, from the screenshot you shared above on Android, the "Clear" button background is semi-transparent, whereas in Figma it's much more opaque due to the correct blur. A semi-transparent button with poor readability seems very amateurish and I think users notice this. We see black text on top of black squares and it looks bad.
> 
> If we can't show what's in Figma on Android, then I think we should have a better fallback than a semi-transparent button. cc'ing @Francesca-G here.
> 
> **Expected**:
> 
> 
> 

Let me try something

**Comment by ibrkhalil** [comment]
> > 
> > @ibrkhalil, from the screenshot you shared above on Android, the "Clear" button background is semi-transparent, whereas in Figma it's much more opaque due to the correct blur. A semi-transparent button with poor readability seems very amateurish and I think users notice this. We see black text on top of black squares and it looks bad.
> > If we can't show what's in Figma on Android, then I think we should have a better fallback than a semi-transparent button. cc'ing @Francesca-G here.
> > **Expected**:
> > 
> 
> Let me try something

Couldn't get it much better, Reaching to Francecsa.

**Comment by Francesca-G** [comment]
> @ibrkhalil, from the screenshot you shared above on Android, the "Clear" button background is semi-transparent, whereas in Figma it's much more opaque due to the correct blur. A semi-transparent button with poor readability seems very amateurish and I think users notice this. We see black text on top of black squares and it looks bad.
> 
> If we can't show what's in Figma on Android, then I think we should have a better fallback than a semi-transparent button. cc'ing @Francesca-G here.
> 
I agree, and on top of not looking so good the user might run into readability problems if the picture under the button is dark. 

I understand we can't 100% match the blur on Android but I suggest increasing button opacity, enough so that the black text is readable and it's closer to the more opaque iOS look/design.

**Comment by ilmotta** [comment]
@ibrkhalil, just a heads up to let us know if you already implemented the suggestion from https://github.com/status-im/status-mobile/pull/17003#issuecomment-1733300997 so we can review the PR again. Just in case you already pushed fixes and we missed them :)

**Comment by ibrkhalil** [comment]
> @ibrkhalil, just a heads up to let us know if you already implemented the suggestion from https://github.com/status-im/status-mobile/pull/17003#issuecomment-1733300997 so we can review the PR again. Just in case you already pushed fixes and we missed them :)

Thank you so much Icaro, I am waiting on @smohamedjavid to merge a PR and then I am continuing this

**Comment by smohamedjavid** [comment]
Hi @ibrkhalil - I have merged the dropdown implementation PR #17412. Thanks for the ping!

**Comment by ibrkhalil** [comment]
Figma (State: Light collapsed drawer)            |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

Figma  (State: Light opened drawer)           |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

Figma (State: Dark collapsed drawer)            |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

Figma (State: Dark opened drawer)            |  iOS |   Android
:-------------------------|-------------------------|-------------------------:
  |    | 

I fixed it using a different approach, Now the blurring doesn't affect readability a lot when the button is on top of photos.
But I'd appreciate another design review please CC: @Francesca-G 
screenshot

File: src/quo2/components/navigation/page_nav/view.cljs [hunk 3]
```diff
@@ -20,7 +20,7 @@
    :blur        :grey})
 
 (defn- page-nav-base
-  [{:keys [margin-top background on-press accessibility-label icon-name]
+  [{:keys [margin-top background on-press accessibility-label icon-name overlay-shown?]
```
Comment (J-Son89) [inline src/quo2/components/navigation/page_nav/view.cljs]: seems like a good solution, perhaps it needs a commit to explain why it is needed? 🤔

Comment (ibrkhalil) [reply src/quo2/components/navigation/page_nav/view.cljs]: You mean in the commit message or a comment?

Comment (ibrkhalil) [reply src/quo2/components/navigation/page_nav/view.cljs]: Just in case it's a comment, I'll do it now

File: src/quo2/components/navigation/page_nav/view.cljs [hunk 4]
```diff
@@ -30,15 +30,17 @@
              :icon-only?          true
              :size                32
              :on-press            on-press
-             :background          (when (button-properties/backgrounds background) background)
+             :background          (if overlay-shown?
```
Comment (J-Son89) [inline src/quo2/components/navigation/page_nav/view.cljs]: I feel like this should be 
```
(when background
 (if overlay-shown? :blur background))
```
also I don't think we need the `(button-properties/backgrounds background)` check, seems unnecessary to me 👍

File: src/quo2/components/navigation/page_nav/view.cljs [hunk 5]
```diff
@@ -48,7 +50,9 @@
                        :icon-only? icon-name
                        :size       32
                        :accessible true
-                       :background (when (button-properties/backgrounds background) background))
+                       :background (if overlay-shown?
```
Comment (J-Son89) [inline src/quo2/components/navigation/page_nav/view.cljs]: perhaps put this logic into a simple helper function and leave a comment by that function explaining it's purpose there?

File: src/quo2/components/navigation/page_nav/view.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo2/components/navigation/page_nav/view.cljs]: also a nit: perhaps `behind-overlay?` is a clearer name for this prop?  🤨

Comment (ibrkhalil) [reply src/quo2/components/navigation/page_nav/view.cljs]: Renamed

File: src/quo2/components/navigation/page_nav/view.cljs (hunk 4 above)
Comment (ibrkhalil) [reply src/quo2/components/navigation/page_nav/view.cljs]: Removed the `when` clause as evaluating (#{:foo :bar} :bar) will yield :bar or nil (if key doesn't exist), But I think that we need the check as the button component is used in a lot of places.

File: src/quo2/components/navigation/page_nav/view.cljs (hunk 5 above)
Comment (ibrkhalil) [reply src/quo2/components/navigation/page_nav/view.cljs]: We just check if the background is within a set of button types, Here's the definition of [backgrounds](https://github.com/status-im/status-mobile/blob/0531adb3ddd5a3c6e8a69c3b26f47f1105546350/src/quo2/components/buttons/button/properties.cljs#L4).

File: src/quo2/components/navigation/page_nav/view.cljs (hunk 3 above)
Comment (J-Son89) [reply src/quo2/components/navigation/page_nav/view.cljs]: Yep I meant in a comment

File: src/quo2/components/navigation/page_nav/view.cljs (hunk 5 above)
Comment (J-Son89) [reply src/quo2/components/navigation/page_nav/view.cljs]: I more so meant this because of the overlay part. It's somewhat of a design hack and so isolating to its own function and leaving the comment there hopefully makes the reason for this more apparent/easy to see

File: src/quo2/components/navigation/page_nav/view.cljs [hunk 6]
```diff
@@ -170,7 +175,13 @@
       shown-name]]))
 
 (defn- view-internal
-  [{:keys [type right-side background text-align account-switcher]
+  [{:keys [type right-side background text-align account-switcher behind-overlay?] ;; behind-overlay is
```
Comment (ilmotta) [inline src/quo2/components/navigation/page_nav/view.cljs]: @ibrkhalil, could you reformat this comment? This is too ugly.

But since you're explaining one of the function arguments, I think the comment should be in the docstring instead.

File: src/status_im2/contexts/communities/overview/view.cljs [hunk 7]
```diff
@@ -336,8 +338,8 @@
           pending?
           {:on-category-layout              (partial add-category-height categories-heights)
            :collapsed?                      collapsed?
-           :on-first-channel-height-changed
-           ;; Here we set the height of the component and we filter out the
+           :on-first-channel-height-changed ;; Here we set the height of the component and we filter out
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/overview/view.cljs]: This comment (and the lines following up) are badly formatted.

Line comments should use double semicolons, but not margin comments. See https://guide.clojure.style/#comments

**Review by ilmotta — APPROVED** [review]
Code wise, I don't have much to add. Thanks @ibrkhalil, I think now it's a matter of getting the design approved and well tested for regressions.

**Review by Francesca-G — APPROVED** [review]

**Comment by ibrkhalil** [comment]
@VolodLytvynenko Can you please take a look?
I got an OK from design.

**Comment by VolodLytvynenko** [comment]
@ibrkhalil Thank you for PR. No issues from my side. PR is ready to be merged

File: src/quo2/components/navigation/page_nav/view.cljs (hunk 5 above)
Comment (ibrkhalil) [reply src/quo2/components/navigation/page_nav/view.cljs]: I think it's better to have a comment explaining it than having a function for it.
