### PR TITLE
fix(wallet): Fix input amount step skipped while sending a token

### LINKED ISSUE #20677: User is navigated to transaction confirmation page if asset is selected during collectible sending flow
The current issue will probably be fixed with [this one,](https://github.com/status-im/status-mobile/issues/20678) as they seem to have the same root cause.

### Steps:
1. Go to wallet
2. Open account
3. Tap 'send'
4. Select collectible on the "Select assets" page
5. Go back to "Select assets" page
6. Select token

### Actual result:
User is navigated directly to confirmation transaction page after token is selected

https://github.com/status-im/status-mobile/assets/52490791/faee5b1c-7014-4a80-8fa2-85b6035c049d

### Expected result:
User is navigated to route generation page 

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly [8 Jul 2024]

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20677 

### Summary

This PR fixes the step skipped. Demo:

https://github.com/user-attachments/assets/01d2b946-70bf-4ea8-928e-ea180f0f5346

### Review notes
The bug was due to the transaction type. When we send regular tokens we don't stablish a new `tx-type` on re-frame. To fix it I'm removing the old transaction type when we pick a token.

### Steps to test

 Please check the video in the original issue

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -204,15 +204,15 @@
                                                              token-networks-ids)]
      (when (or token token-symbol)
        {:db (cond-> db
-              :always      (update-in [:wallet :ui :send] dissoc :collectible)
+              :always      (update-in [:wallet :ui :send] dissoc :collectible :tx-type)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs]: Remove the old tx type

File: src/status_im/contexts/wallet/send/events.cljs [hunk 2]
```diff
@@ -204,15 +204,15 @@
...
               :always      (assoc-in
                             [:wallet :ui :send :token-not-supported-in-receiver-networks?]
                             token-not-supported-in-receiver-networks?)
               token        (assoc-in [:wallet :ui :send :token] token)
               token        (assoc-in [:wallet :ui :send :token-display-name]
                             (:symbol token))
               token-symbol (assoc-in [:wallet :ui :send :token-symbol] token-symbol))
-        :fx [[:dispatch [:wallet/clean-suggested-routes]]
+        :fx [[:dispatch ^:flush-dom [:wallet/clean-suggested-routes]]
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs]: Needed to properly update the re-frame DB when we navigate forward, this avoids a 1-frame blink on the app

Comment (OmarBasem) [reply src/status_im/contexts/wallet/send/events.cljs]: I would suggest adding a comment about `^:flush-dom` saying why it is here as it is not used anywhere else in the app

**Review by OmarBasem — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs (hunk 2 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/send/events.cljs]: @OmarBasem Done! :)

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for PR. No issues from my side. PR is ready to be merged

**Comment by churik** [comment]
Let's merge it and include to release, very nice fix, thank you @ulisesmac !
