### PR TITLE
Show Swaps fee accurately as <0.01 when very small

### LINKED ISSUE #21721: Estimated fee on optimism is always 0.00
Might be regression of https://github.com/status-im/status-mobile/pull/21697 cc @mohsen-ghafouri 

**Steps:** 

1. Build routes for send/swap flow on optimism chain
2. Pay attention at the estimated fee value

**Actual result:** Estimated fee on optimism is always 0.00

[Status-debug-logs - 2024-11-29T150412.668.zip](https://github.com/user-attachments/files/17959518/Status-debug-logs.-.2024-11-29T150412.668.zip)
photo_2024-11-29 15 03 58
photo_2024-11-29 15 03 56

https://github.com/user-attachments/assets/ea6d664a-3786-4cfb-b714-7b9e44191af7

### PR DESCRIPTION
**Pull request by clauxx**
fixes #21721

### Summary

Usually happens with very small fees (e.g. on Optimism), where if the fee is very small e.g. $0.0001, it gets rounded to 0 when converting from crypto to fiat in `money/crypto->fiat`. This affected different places, like fees or sums of amounts, e.g. if the fiat value of tokens the user has on different networks were all smaller than $0.01, then the sum amount would've been $0.00.

### Testing notes
Make sure the places where we show fiat ($) amounts are properly formatted i.e. with two digits. I went through the flows I know of, but might've missed some.

### Screenshot

status: ready

### CODE REVIEW

File: src/status_im/contexts/wallet/common/utils.cljs [hunk 1]
```diff
@@ -279,6 +265,20 @@
...
+  [{:keys [currency currency-symbol balance token prices-per-token]}]
+  (let [price             (or (get-market-value currency token prices-per-token) 0)
+        price-zero?       (zero? price)
+        balance           (or balance 0)
+        balance-positive? (pos? balance)
+        fiat-value        (money/crypto->fiat balance price)
+        fiat-value-zero?  (money/equal-to fiat-value (money/bignumber 0))]
+    (if (and fiat-value-zero? (not price-zero?) balance-positive?)
+      (number/small-number-threshold 2 currency-symbol)
+      (fiat-formatted-for-ui currency-symbol fiat-value))))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/common/utils.cljs:280]: this line is the only change in this ns

**Review by briansztamfater — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by pavloburykh** [comment]
@clauxx thanks for the PR! Tested on Android, LGTM. Haven't checked IOS as builds are currently broken. See discussion [here](https://discord.com/channels/1210237582470807632/1217173176086302821/1313136302333493258) I guess we can skip ios testing this time in order not to block the PR.
