### PR TITLE
Fix quick transaction setting when bridging erc20 

### LINKED ISSUE #22161: Selected transaction setting is reset in bridge flow
cc @vkjr 

**Steps:** 

1. Go to bridge flow
2. Change transaction fee on confirmation screen
3. Check if value is applied (not reset)

**Actual result:** 

Fee value is reset to the default 'Fast' fee despite other fee type is selected

[Status-debug-logs (4).zip](https://github.com/user-attachments/files/18869630/Status-debug-logs.4.zip)

https://github.com/user-attachments/assets/51c12f0f-c9d4-4079-8e55-0f1259795a80

### Additional Information

- Status version: PR https://github.com/status-im/status-mobile/pull/22019
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by vkjr**
fixes #22161

## Summary
Now quick transaction settings applied when user bridges erc20

https://github.com/user-attachments/assets/fc97fcb6-17f6-47a1-a621-c19396d01910

## Review notes
The root of problem is that Bridge actually contains from 2 transactions because erc20 tokens need approval. But in UI we do not reflect this, whereas `status-go` backend of quick transaction settings made with the idea that setting should be set separately for Approval tx and for Send tx.
To hide this implementation detail from user I call `SetFeeMode` endpoint 2 times for approval and send when user selects the setting.

### Platforms

- Android
- iOS

#### Functional

- wallet / transactions
## Steps to test
[comment]: #  (Specify exact steps to test if there are such)

- Open Status
- Start bridging erc20 transaction
- Make sure selected transaction settings applied

status: ready

### CODE REVIEW

**Comment by shivekkhurana** [comment]
Why is the time estimation not visible 😅

**Comment by clauxx** [comment]
> Why is the time estimation not visible 😅

I noticed it as well and fixed it in another PR https://github.com/status-im/status-mobile/pull/22232
Seems like at some point it was renamed from `EstimatedTime` to `TxEstimatedTime` in the router and now it's in seconds instead of minute intervals.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 1]
```diff
@@ -880,23 +880,35 @@
...
-                          (log/error "failed to set quick transaction settings"
-                                     {:event  :wallet/quick-fee-mode-confirmed
-                                      :error  (:message error)
-                                      :params params}))}]]
-           [:dispatch [:wallet/mark-user-tx-settings-for-deletion]]]})))
-
+      :fx (conj set-fee-effects
+                [:dispatch [:wallet/mark-user-tx-settings-for-deletion]])})))
+(comment
+  (send-utils/path-identity {:bridge-name "hello"} false))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/send/events.cljs]: remove

**Review by clauxx — APPROVED** [review]

**Comment by vkjr** [comment]
@VolodLytvynenko, could you please take a look at this one when you have time? 🙏

**Comment by VolodLytvynenko** [comment]
unfotunatly current PR is  blocked by https://github.com/status-im/status-mobile/issues/22265

**Comment by VolodLytvynenko** [comment]
> unfotunatly current PR is blocked by #22265

Not blocker anymore https://github.com/status-im/status-mobile/issues/22265. Can perform txs on other networks. Will be enough for current PR to check functionality on L2 only and eth on L1

**Review by shivekkhurana — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @vkjr thank you for PR. No issues from my side. PR is ready to be merged
