### PR TITLE
[#20914] Fix error while bridging tokens

### LINKED ISSUE #20914: Bridging low amount of USDc leads to error and inability to see your assets
When bridging not big amount of USDc (tried 0.1, 1) - got an error, the user stayed on send tx page and all assets are disappeared at atemmpt to pull-to-refresh

In MM the limit is 10 USDc (this amount is working in Status as well)

**Please, verify what limits Hop Bridge is supporting, it can be the case for all tokens**

Consequences: 
1) was not redirected to activity page
2) tx is failed and reverted with "Fail with error 'ERC20: transfer amount exceeds allowance", example https://arbiscan.io/tx/0xa834e4772e11daf3cfe0a9afba521e7fb0c4c2280bca6483fa27bbe99c99a5f2
3) Wallet freeze at update and eventually shows 0
Re-login helps.

We need to find out what is this error about (I believe some tx limits in Hop might not be met) and prevent users from making faulty txs.

Video:

https://github.com/user-attachments/assets/953e125f-2fe4-4487-a20b-52bdc8eb04e9

Logs: 

[logs (103).zip](https://github.com/user-attachments/files/16412198/logs.103.zip)

What I get after pull-to-refresh:
IMAGE 2024-07-29 13:49:35

_Originally posted by @churik in https://github.com/status-im/status-mobile/issues/20902#issuecomment-2255722912_

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20914

### Summary

This PR solves the issue while bridging a token due to bonder fees being higher than the bridgable amount. Now it's not possible to make such transactions (the "no routes found" message will appear).

This PR is build on top of:
- https://github.com/status-im/status-mobile/pull/20924#event-13698170900

### Review notes
Please check the code changes in case an additional check is missing.

### Testing notes
Please verify the sending is working as before (I tested it and it's not affected).

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Bridge any asset, the error reported should be solved,

status: ready

### Risk

Described potential risks and worst case scenarios.

- Sending in some way is broken
- The changes affect other areas of bridging.

### CODE REVIEW

File: src/status_im/contexts/wallet/data_store.cljs [hunk 1]
```diff
@@ -213,8 +213,7 @@
   [new-path]
   (let [bonder-fees (:tx-bonder-fees new-path)
         token-fees  (+ (money/wei->ether bonder-fees)
-                       (money/wei->ether
-                        (:tx-token-fees new-path)))]
+                       (money/wei->ether (:tx-token-fees new-path)))]
     {:from                      (:from-chain new-path)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/data_store.cljs:217]: Just a code style fix

File: src/status_im/contexts/wallet/send/events.cljs [hunk 2]
```diff
@@ -105,9 +105,7 @@
          cleaned-receiver-network-values (-> (get-in db [:wallet :ui :send :receiver-network-values])
                                              (send-utils/reset-loading-network-amounts-to-zero))]
      {:db (-> db
-              (update-in [:wallet :ui :send]
-                         dissoc
-                         :route)
+              (update-in [:wallet :ui :send] dissoc :route)
               (assoc-in [:wallet :ui :send :sender-network-values] cleaned-sender-network-values)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:109]: Again, code style fix

File: src/status_im/contexts/wallet/send/events.cljs [hunk 3]
```diff
@@ -491,26 +489,48 @@
...
+                                 remove-invalid-bonder-fees-routes
+                                 remove-multichain-routes)
+           candidates-fix  (comp ->old-route-paths
+                                 remove-invalid-bonder-fees-routes)
+           routes          (-> data
+                               (first)
+                               (data-store/rpc->suggested-routes)
+                               (update :best best-routes-fix)
+                               (update :candidates candidates-fix))]
+       {:fx [[:dispatch [:wallet/suggested-routes-success routes]]]}))))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:533]: This is the important change.

The `:best` and `:candidates` routes are updated to remove the ones having `:tx-bonder-fees` higher than the amount to bridge.

I tested and the tranasctions worked. @briansztamfater Do you think we need to add an additional check to perform these updates?
As far as I tested everything was still working.

File: src/status_im/contexts/wallet/send/events.cljs [hunk 4]
```diff
@@ -491,26 +489,48 @@
...
                                              :error error}))}]}))
 
-(rf/reg-event-fx :wallet/handle-suggested-routes
+(defn- bridge-amount-greater-than-bonder-fees?
+  [{{token-decimals :decimals} :from-token
+    bonder-fees                :tx-bonder-fees
+    amount-in                  :amount-in}]
+  (let [bonder-fees      (utils.money/token->unit bonder-fees token-decimals)
+        amount-to-bridge (utils.money/token->unit amount-in token-decimals)]
+    (> amount-to-bridge bonder-fees)))
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/send/events.cljs:498]: I'm checking on the  `amount-in` value (because it sounds like the "amount in" the bridge). Is it right? should I use `amount-out` instead?

CC: @briansztamfater

Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/events.cljs:498]: `amount-in` is correct 👍

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (briansztamfater) [reply src/status_im/contexts/wallet/send/events.cljs:533]: I think the checks are okay!

**Review by briansztamfater — APPROVED** [review]
Great work @ulisesmac!

This is a useful check, though @alaibe says that routes should already be filtered in status-go, so maybe it will be fixed in status-go in future versions. I think it doesn't hurt to have this check locally though.

**Review by vkjr — APPROVED** [review]

File: src/status_im/contexts/wallet/send/events.cljs (hunk 3 above)
Comment (seanstrom) [reply src/status_im/contexts/wallet/send/events.cljs:533]: Hey @ulisesmac, just curious why are we using `first` here on `data`:
* What's the shape of data at this point, would we only ever care about the first entry?

**Review by BalogunofAfrica — APPROVED** [review]
LGTM. Tested and it works fine

**Comment by churik** [comment]
Confirmed on both Dai and USDc that can bridge small amount (L2 -> L2), fix works.

waiting for e2e and ready to be merged and cherry-picked.
