### PR TITLE
[#16861] fix: resolve discover communities design feedbacks

### LINKED ISSUE #16861: Design review: discover communities
- [ ] 1. Wrong spacing - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510267875)  
- [ ] 2. Buttons background on `x`  [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511295255)  
- [ ] 3. Wrong margin   - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510228652)  
- [ ] 4. Wrong font size - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511274377)
- [ ] 5. Card proportion **(Android only)**- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275324)
- [ ] 6. Missing shadow on card  **(Android only)**- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275579)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #16861

1. Wrong spacing - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510267875)
 2. Buttons background on x [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511295255)
 3. Wrong margin - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510228652)
 4. Wrong font size - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511274377) (it seems already handled)
 5. Card proportion (Android only)- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275324)
 6. Missing shadow on card (Android only)- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275579)

status: ready

### CODE REVIEW

**Comment by mohsen-ghafouri** [comment]
@ilmotta Could you please check this part? you recently made changes to src/quo2/components/navigation/page_nav/view.cljs 
It seems the button background is no longer transparent, so I removed it.

File: src/status_im2/contexts/communities/discover/style.cljs [hunk 1]
```diff
@@ -56,8 +57,9 @@
   {:align-items     :center
    :justify-content :center})
 
-(def render-communities-container
-  {:margin-top 100})
+(defn render-communities-container
```
Comment (ilmotta) [inline src/status_im2/contexts/communities/discover/style.cljs]: Since the platform type is not reactive, we can still keep `render-communities-container` a static map.

**Review by ilmotta — APPROVED** [review]
> @ilmotta Could you please check this part? you recently made changes to src/quo2/components/navigation/page_nav/view.cljs
It seems the button background is no longer transparent, so I removed it.

@mohsen-ghafouri, the code looks good, but I think it's better in this case to ask the designer to review this PR and make sure everything is 100% as it should be.

**Review by jo-mut — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@Francesca-G could you please review this? :)

**Review by Francesca-G — APPROVED** [review]
