### PR TITLE
Fixing bug #1706 edit profile from drawer resetting username to default

### LINKED ISSUE #1706: Username is changed to default if Profile screen was opened and user taps on status and username fields
### Description

*Type*: Bug

*Summary*: Non-default username is automatically changed to default one if Profile screen was opened and then user taps on drawer fields Status -> Username -> Status

#### Expected behavior
Non-default username stays the same

#### Actual behavior
Non-default username is changed to default one

### Reproduction
From 00:20 https://app.testfairy.com/projects/4803622-status/builds/6448715/sessions/27/?accessToken=xs4WaY8EXKtGnXSJBm8C7Alyt2M

- You need to have a user with non-default username 
- Open Status
- Open drawer
- Tap on avatar picture or on 3 dots to open Profile screen
- Tap on < icon. As a result, profile screen is closed and screen Chats is shown
- Open drawer again (tap on hamburger menu in top left corner)
- Tap on status field (cursor is shown at the end of the text)
- Tap on username field (cursor is shown at the end of the filed)
- Tap again on status field. Issue now: username is changed to default one. Expected: username stays the same

### Additional Information
* Status version: develop build  0.9.10-34-gf07eff4a+ . Can't be reproduced on released 0.9.10
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

### PR DESCRIPTION
**Pull request by yenda**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
#1706 

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)

Username is changed to default if Profile screen was opened and user taps on status and username fields

The pull request solves the bug by reworking the way state is stored for profile editing.
Before the drawer profile was in local state and the profile was in app-db. This PR puts everything into the app-db and simplifies future UX changes by defining small events for each user action.

Tests are also adapted to reflect the changes (only simple cases of status changes, maybe in the future some generative testing could be used to check more complex events, or at least more cases could be added). I also removed the phone change test because it was not a phone change test

### Behaviors tested on Android emulator

- [x] status field is unfocused and saved in drawer and unfocused in edit screen when pressing linebreak
- [x] when name is invalid the save button is not available in edit profile screen  and reverted to placeholder if saved
- [x] when name is invalid the name is shown in red in the drawer

### Additional UX improvements tested:
- [x] when name is invalid in drawer and saved it is reverted to placeholder (instead of previous name)
- [x] when exiting the edit-profile screen without saving the state is kept unless user edits from drawer (instead of lost as soon as user goes back to profile screen)
- [x] pressing the vertical dots icon in the drawer while editing name or status saves it and goes to profile screen (before it was not saving)

### Steps to test:
- Open Status
- Open drawer, go to profile screen
- Go back and tap status then username screen

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

**Review by x-goose-x — APPROVED** [review]

File: src/status_im/components/drawer/view.cljs [hunk 1]
```diff
@@ -34,60 +34,68 @@
...
+  (close-drawer)
+  (when-let [save-event @(rf/subscribe [:my-profile.drawer/save-event])]
+    (rf/dispatch [save-event]))
+  (rf/dispatch [:navigate-to :my-profile]))
+
+(defn navigate-to-accounts []
+  (close-drawer)
+  (when-let [save-event @(rf/subscribe [:my-profile.drawer/save-event])]
+    (rf/dispatch [save-event]))
+  (rf/dispatch [:navigate-to :accounts]))
```
Comment (jeluard) [inline src/status_im/components/drawer/view.cljs]: Both block of code are very similar. Maybe introduce a function?

File: src/status_im/components/drawer/view.cljs [hunk 2]
```diff
@@ -34,60 +34,68 @@
...
+
 (defview profile-picture []
-  [account [:get-current-account]]
-  [touchable-opacity {:on-press #(rf/dispatch [:navigate-to :my-profile])
-                      :style    st/user-photo-container}
-   [view
-    [ci/chat-icon (:photo-path account) {:size 52}]]])
+  (letsubs [account [:get-current-account]]
+    [touchable-opacity {:on-press #(navigate-to-profile)
```
Comment (jeluard) [inline src/status_im/components/drawer/view.cljs]: Why not just `navigate-to-profile` ?

File: src/status_im/components/drawer/view.cljs [hunk 3]
```diff
@@ -144,17 +152,13 @@
 (defn options-btn []
   [view {:style st/options-button}
    [touchable-highlight
-    {:on-press (fn []
-                 (close-drawer)
-                 (rf/dispatch [:navigate-to :my-profile]))}
+    {:on-press #(navigate-to-profile)}
```
Comment (jeluard) [inline src/status_im/components/drawer/view.cljs]: Same comment

File: src/status_im/components/drawer/view.cljs [hunk 4]
```diff
@@ -144,17 +152,13 @@
...
     [view [vi/icon :icons/options]]]])
 
 (defn switch-account []
   [view st/switch-account-container
    [touchable-highlight
-    {:on-press (fn []
-                 (close-drawer)
-                 (rf/dispatch [:navigate-to :accounts]))}
+    {:on-press #(navigate-to-accounts)}
```
Comment (jeluard) [inline src/status_im/components/drawer/view.cljs]: Same comment

File: src/status_im/ui/screens/profile/events.cljs [hunk 5]
```diff
@@ -39,43 +40,129 @@
...
+  (get-in db [:accounts/accounts current-account-id]))
+
+(handlers/register-handler-fx
+  :my-profile.drawer/edit-name
+  (fn [{:keys [db]} _]
+    (let [{:my-profile/keys [default-name edit auto-save]} db
+          {:keys [name public-key]}                        (get-current-account db)]
+      {:db (cond-> db
+             (not default-name) (assoc :my-profile/default-name (gfycat/generate-gfy public-key))
+             :always            (assoc-in [:my-profile/drawer :name] name))})))
```
Comment (jeluard) [inline src/status_im/ui/screens/profile/events.cljs:61]: I am more used to see `:else`. I don't know if we have such convention in the project.

File: src/status_im/ui/screens/profile/subs.cljs [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+  :<- [:get :my-profile/profile]
+  (fn [[current-account profile] [_ k]]
+    (or (get profile k)
+        (get current-account k))))
+
+(reg-sub :my-profile.drawer/get
+  :<- [:get-current-account]
+  :<- [:get :my-profile/drawer]
+  (fn [[current-account profile] [_ k]]
+    (or (get profile k)
```
Comment (jeluard) [inline src/status_im/ui/screens/profile/subs.cljs]: Both blocks are similar. Introduce a function?

File: src/status_im/ui/screens/profile/subs.cljs [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+
+(reg-sub :my-profile/valid-name?
+  :<- [:get :my-profile/profile]
+  (fn [profile]
+    (get profile :valid-name? true)))
+
+(reg-sub :my-profile.drawer/valid-name?
+  :<- [:get :my-profile/drawer]
+  (fn [profile]
+    (get profile :valid-name? true)))
```
Comment (jeluard) [inline src/status_im/ui/screens/profile/subs.cljs]: Same comment.

**Review by jeluard — CHANGES_REQUESTED** [review]

File: src/status_im/ui/screens/profile/events.cljs (hunk 5 above)
Comment (rasom) [reply src/status_im/ui/screens/profile/events.cljs:61]: We used `true` in some places, but i like `:always` much more than `true` tbh. And `:else` isn't quite correct here, because other branches can be executed as well.

Comment (jeluard) [reply src/status_im/ui/screens/profile/events.cljs:61]: Indeed `:always` is more appropriate for `cond->`.

File: src/status_im/ui/screens/profile/events.cljs [hunk 8]
```diff
@@ -39,43 +40,129 @@
...
+               (assoc-in [:my-profile/drawer :edit-status?] true))})))
+
+(handlers/register-handler-fx
+  :my-profile/edit-profile
+  (fn [{:keys [db]} [_ edit-status?]]
+    (let [new-db (-> db
+                     (assoc-in [:my-profile/profile :edit-status?] edit-status?)
+                     (update-in [:my-profile/profile]
+                                #(merge (select-keys (get-current-account db) db/account-profile-keys) %)))]
+      {:db new-db
```
Comment (rasom) [inline src/status_im/ui/screens/profile/events.cljs]: alignment in map

File: src/status_im/ui/screens/profile/subs.cljs (hunk 7 above)
Comment (yenda) [reply src/status_im/ui/screens/profile/subs.cljs]: I am not sure how to introduce a function there it is subscriptions, the idea is that it only recomputes when the profile or drawer changes

Comment (jeluard) [reply src/status_im/ui/screens/profile/subs.cljs]: `(or (get ..) (get ..))` is used for 2 subscriptions. This part could be abstracted?

Comment (yenda) [reply src/status_im/ui/screens/profile/subs.cljs]: I don't think it is worth trading 2 lines for a function and an indirection

**Review by rasom — APPROVED** [review]

**Comment by annadanchenko** [comment]
#1746 Default username becomes empty if open Profile screen [bug/username-changed-to-default] is introduced by this PR
still testing

**Comment by annadanchenko** [comment]
Wrong QR code (picture - if scan then no public key is recognized), no username and no avatar is shown on Show QR opened on Profile screen. Same issue for Show QR of the Public key and Address.
screenshot_20170905-111340


Test session (from 00:50) https://app.testfairy.com/projects/4803622-status/builds/6498278/sessions/3/?accessToken=Sw2XZ7nnooCNL6a49kGzIbIeia4

Steps:
- Open Status and sign in
- Open drawer
- Tap on 3 dots icon to open Profile screen
- Tap on Show QR
- Check values shown on the screen. Try to scan QR by another device with Status to add it as a contact
- Return to Profile screen
- Next to Public key tap on 3 dots and select Show QR.
- Check values shown on the screen. Try to scan QR by another device with Status to add it as a contact

On both Android and iOS, build #6 for `bug/username-changed-to-default`http://185.90.37.243:8080/job/Github%20Org%20Builder/job/status-react/job/bug%252Fusername-changed-to-default/

**Comment by yenda** [comment]
The QR code bug was caused by a missing import:

With the refactoring the navigation code got moved from events to navigation namespace and navigation namespace has to be imported in events otherwise the code is never there. In this case there was data to be pre-loaded when opening the qr-code modal window that was not anymore.

File: src/status_im/components/drawer/view.cljs [hunk 9]
```diff
@@ -34,60 +34,70 @@
 (defn open-drawer [] (.openDrawer @drawer-atom))
 (defn close-drawer [] (.closeDrawer @drawer-atom))
```
Comment (oskarth) [inline src/status_im/components/drawer/view.cljs]: What about calling this `open-drawer!` to signify side effect? Same with `close-drawer` and possibly `save-profile`.

File: src/status_im/components/drawer/view.cljs [hunk 10]
```diff
@@ -34,60 +34,70 @@
...
-                                 :number-of-lines 3
-                                 :status          (if (str/blank? previous-status)
-                                                    placeholder
-                                                    previous-status)}])]))
+
+  (letsubs [edit-status? [:my-profile.drawer/get :edit-status?]
+            status       [:my-profile.drawer/get :status]]
+    (let [placeholder (i18n/label :t/update-status)]
+      [view st/status-container
+       (if edit-status?
```
Comment (oskarth) [inline src/status_im/components/drawer/view.cljs:81]: I'd consider breaking these two vectors out into util fns so if statement is clear, no need for newline then

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/screens/profile/db.cljs [hunk 11]
```diff
@@ -6,6 +6,8 @@
             [status-im.constants :as constants]
             [status-im.utils.homoglyph :as homoglyph]))
 
+(def account-profile-keys [:name :photo-path :status])
```
Comment (oskarth) [inline src/status_im/ui/screens/profile/db.cljs:9]: Is this always used as a cursor? If so I think we should indicate it as such, e.g. `photo-status-path` or something

File: src/status_im/ui/screens/profile/edit/views.cljs [hunk 12]
```diff
@@ -24,11 +24,15 @@
...
-  (letsubs [new-profile-name [:get-in [:my-profile/edit :name]]]
+  (letsubs [profile-name [:my-profile/get :name]
+            placeholder  [:get :my-profile/default-name]]
     [react/view
-     [text-input-with-label {:label          (label :t/name)
-                             :default-value  new-profile-name
-                             :on-change-text #(dispatch [:set-in [:my-profile/edit :name] %])}]]))
+     [text-input-with-label
+      {:label          (label :t/name)
+       :default-value profile-name
```
Comment (oskarth) [inline src/status_im/ui/screens/profile/edit/views.cljs]: Align

File: src/status_im/ui/screens/profile/edit/views.cljs [hunk 13]
```diff
@@ -54,24 +58,21 @@
...
+(defview edit-profile-status []
+  (letsubs [edit-status? [:my-profile/get :edit-status?]
+            status       [:my-profile/get :status]]
     [react/view styles/edit-profile-status
      [react/scroll-view
       (if edit-status?
         [react/text-input
-         {:ref               #(reset! input-ref %)
-          :auto-focus        edit-status?
+         {:auto-focus        (if edit-status? true false)
```
Comment (oskarth) [inline src/status_im/ui/screens/profile/edit/views.cljs:69]: isn't this just `edit-status?` would consider renaming it to  `auto-focus?`

File: src/status_im/ui/screens/profile/subs.cljs (hunk 6 above)
Comment (oskarth) [reply src/status_im/ui/screens/profile/subs.cljs]: Agreed

File: src/status_im/ui/screens/profile/events.cljs [hunk 14]
```diff
@@ -39,43 +41,130 @@
...
+    (let [status (get-in db [:my-profile/drawer :status])
+          new-db (-> db
+                     (assoc-in [:my-profile/drawer :edit-status?] nil)
+                     (dissoc :my-profile/profile))]
+      (if (string/blank? status)
+        {:db new-db}
+        {:db new-db
+         :dispatch-n [[:check-status-change status]
+                      [:account-update {:status status}]]}))))
+
```
Comment (janherich) [inline src/status_im/ui/screens/profile/events.cljs:154]: Ideally we would like to have `:check-status-change` and `:account-update` refactored into pure functions and just call them there instead of the dispatch, but I understand it's not focus of this PR and it's another module (`accounts`), so it can be done later.

**Review by oskarth — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by annadanchenko** [comment]
1. Wrong QR code is fixed in last build
2. Pressing save button in edit profile screen return to profile screen - OK

New issue: #1769  picture is not saved as avatar if use Capture. After tap on camera icon Edit profile screen is shown but avatar contains old default picture

File: src/status_im/ui/screens/profile/db.cljs (hunk 11 above)
Comment (yenda) [reply src/status_im/ui/screens/profile/db.cljs:9]: it's not a cursor it is a list of keys to select from the profile when extracting profile

File: src/status_im/ui/screens/profile/edit/views.cljs (hunk 13 above)
Comment (yenda) [reply src/status_im/ui/screens/profile/edit/views.cljs:69]: I don't know about this one, the focus can be on something else, auto-focus in the app-db wouldn't be really helpful to figure our what it implies. Here it means user is editing the status field.

File: src/status_im/ui/screens/profile/events.cljs (hunk 14 above)
Comment (yenda) [reply src/status_im/ui/screens/profile/events.cljs:154]: yes it's an old part of the code where there is still ui/side-effects

**Comment by annadanchenko** [comment]
#1769 is fixed.
New issue is found in this PR, can't reproduce it on develop build: #1778 Username of the first account is changed to the username of second account on same device [bug/username-changed-to-default]

**Comment by asemiankevich** [comment]
Looks good, https://github.com/status-im/status-react/issues/1769
https://github.com/status-im/status-react/issues/1746
https://github.com/status-im/status-react/issues/1747
https://github.com/status-im/status-react/issues/1706 are not reproducible, QR issue is also fixed
