### PR TITLE
[#16322] - Carousel tap gesture

### LINKED ISSUE #16322: Onboarding - Identifiers page - no transition on tap
# Bug Report

## Problem 
Designs: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2885-319352&t=A0Jlb3RKZKdg7Xy1-4

At the moment there is no transition to the next slide when tapping on the Identifiers page
IMAGE 2023-06-20 10:06:54

### PR DESCRIPTION
**Pull request by ulisesmac**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #16322

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

Adds a tap gesture for the carousel and uses it in the identifiers onboarding screen:
 https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2926-331925&t=fnJhl0L7L7X8JCNe-4

### Review notes

Refactored the code a little

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Create a new profile
- Navigate to identifiers screen
- Tap on the text to show the following slide

status: ready

### CODE REVIEW

File: src/status_im2/contexts/onboarding/common/carousel/animation.cljs [hunk 1]
```diff
@@ -95,18 +95,21 @@
...
+  (-> (gesture/gesture-pan)
+      (gesture/max-pointers 1)
+      (gesture/on-finalize
+       (fn [event]
+         (let [next?     (< (oops/oget event "translationX") (- drag-limit))
+               previous? (> (oops/oget event "translationX") drag-limit)]
+           (when next?
+             (update-progress progress paused (get-next-progress progress)))
+           (when previous?
+             (update-progress progress paused (get-previous-progress progress))))))))
```
Comment (ulisesmac) [inline src/status_im2/contexts/onboarding/common/carousel/animation.cljs:107]: Refactored a little:

1. The code style for `->` 
2. removed `(gesture/enabled true)` since that's the default value and we are not passing any other value than true.

File: src/status_im2/contexts/onboarding/common/carousel/animation.cljs [hunk 2]
```diff
@@ -95,18 +95,21 @@
...
+
+(defn tap-gesture
+  [progress paused]
+  (-> (gesture/gesture-tap)
+      (gesture/on-end #(update-progress progress paused (get-next-progress progress)))))
```
Comment (ulisesmac) [inline src/status_im2/contexts/onboarding/common/carousel/animation.cljs:112]: New tap gesture to navigate to the following slide added

File: src/status_im2/contexts/onboarding/common/carousel/view.cljs [hunk 3]
```diff
@@ -50,15 +50,18 @@
        :progress-bar-width progress-bar-width}]]))
 
 (defn f-view
-  [{:keys [animate? progress paused? header-text background header-background swipeable?]}]
+  [{:keys [animate? progress paused? header-text background header-background gesture]}]
```
Comment (ulisesmac) [inline src/status_im2/contexts/onboarding/common/carousel/view.cljs:53]: Changed the carousel API.

Since the carousel cannot be  `tappable?` and `swipable?` at the same time, I added a `gesture` key that receives `:tappable` or `:swipeable` keywords

File: src/status_im2/contexts/onboarding/common/carousel/view.cljs [hunk 4]
```diff
@@ -68,7 +71,7 @@
            :index             index
            :header-text       header-text
            :header-background header-background}
-          (when background background)])]]
+          background])]]
```
Comment (ulisesmac) [inline src/status_im2/contexts/onboarding/common/carousel/view.cljs:74]: changed `(when background background) => background`

since unless `background` is `false` (which is not because we expect a component/vector), the expression is evaluates to the same value

File: src/status_im2/contexts/onboarding/identifiers/view.cljs [hunk 5]
```diff
@@ -41,7 +41,7 @@
        {:animate?    true
         :progress    progress
         :paused?     paused?
-        :swipeable?  false
+        :gesture     :tappable
```
Comment (ulisesmac) [inline src/status_im2/contexts/onboarding/identifiers/view.cljs:44]: Now the catousel in identifiers page is tappable

File: src/status_im2/contexts/onboarding/common/background/view.cljs [hunk 6]
```diff
@@ -79,7 +79,7 @@
        :paused?           paused?
        :header-text       header-text
        :header-background true
-       :swipeable?        true
+       :gesture           :swipeable
```
Comment (J-Son89) [inline src/status_im2/contexts/onboarding/common/background/view.cljs:82]: 👌

**Review by J-Son89 — APPROVED** [review]

**Review by rahulpsingh — APPROVED** [review]
Looks good to me 🚀

**Comment by qoqobolo** [comment]
Hey @ulisesmac, thanks for PR and adding the gesture!

Q: on iOS it only works if I tap on the text as expected, but on Android the whole screen is tappable (except for the user's card).
Should we disable it for Android?
Although it seems to me more convenient if you can tap anywhere on the screen to go to the next slide.


https://github.com/status-im/status-mobile/assets/67952253/3eee1b43-735a-4d3c-b7d1-c1edd6a6deca

**Comment by ulisesmac** [comment]
> Hey @ulisesmac, thanks for PR and adding the gesture!
> 
> Q: on iOS it only works if I tap on the text as expected, but on Android the whole screen is tappable (except for the user's card). Should we disable it for Android? Although it seems to me more convenient if you can tap anywhere on the screen to go to the next slide.
> video_2023-06-22_11-04-34.mp4

Hey @qoqobolo 

I pushed a commit to fix it, so now in Android you need to tap the text to trigger it.

**Comment by pavloburykh** [comment]
@ulisesmac thanx for the fixes! Tested, ready for merge
