### PR TITLE
[#12451] Fix copy icon in message actions

### LINKED ISSUE #12451: Redundant "!" button in the "Message actions" context menu in Timeline
# Bug Report

## Problem 

128864340-ef845617-18be-4dad-ab29-563ff5b10f80

### Reproduction

1. Post something in Timeline
2. Long tap on the message

### Additional Information

- Status version: nightly 16/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by rasom**
fix #12451

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/status/views.cljs [hunk 1]
```diff
@@ -78,7 +78,8 @@
 (defn on-long-press-fn [on-long-press content image]
   (on-long-press
    (when-not image
-     [{:on-press #(react/copy-to-clipboard
+     [{:id "copy"
```
Comment (flexsurfer) [inline src/status_im/ui/screens/status/views.cljs]: why string ?

Comment (rasom) [reply src/status_im/ui/screens/status/views.cljs]: https://github.com/status-im/status-react/blob/features%2Fsuggest-tip/src/status_im/ui/screens/chat/message/reactions_picker.cljs#L26

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/status/views.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/ui/screens/status/views.cljs]: it works with a keyword though
