### PR TITLE
[#20500] Fix derived accounts

### LINKED ISSUE #20437: "Confirm account origin" button disabled on Key Pairs page
### Description:
After going to the 'Key pairs' page, the 'Confirm account origin' button is shown as disabled by default. The button can also be disabled for non-default accounts following the steps below. This issue suggests enabling this button and not showing it as disabled at all.

### Steps:
1. Create additional account importing with seed phrase or generating with new key pair
2. Go to new account creation again -> tap "add account" -> tap "edit" 
3. Select a newly created account on Key pairs page

### Actual result:
The 'confirm account origin' button is disabled

https://github.com/status-im/status-mobile/assets/52490791/fde9bfd1-e08e-44cc-a3f1-397a9b6ac83c

### Expected result:
The 'confirm account origin' button is enabled
discussed with design team https://discord.com/channels/624634427930312714/852533718790570015/1250064411729596490
### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
Nightly 12 Jun 2024

### LINKED ISSUE #20500: Can't derive an account from a new keypair after deriving an account from default keypair
# Bug Report

If you derive an account from your default keypair, then create a new keypair and try to derive an additional account from it - you will stay on the account creation page after confirmation.
It also reproduces in reverse order: first create a new keypair and derive an account from it, and then try to derive an account from the default keypair.

### Reproduction

1. Derive an account from the default keypair (`Acc1`)
2. Create a new keypair (New KP) with an account `NKP1`
3. Try to derive another account from New KP - `NKP2`

or

1. Create a new keypair (New KP) with an account `NKP1`
2. Derive another account from New KP - `NKP2`
3. Try to derive another account from your default keypair - `Acc1`

#### Expected behavior
Acc1 is created

#### Actual behavior
Nothing happens after confirmation, you stay on the ACC creation page, Acc1 is not created

Video for the second way to reproduce: 

https://github.com/status-im/status-mobile/assets/67952253/986d44bb-bfb4-4230-ad24-1cc7889fbb48

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/15889414/Status-debug-logs.zip)

### Additional Information

- Status version: nightly 18/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #20500
fixes #20437 

### Summary

This PR fixes this error:

[failure](https://github.com/status-im/status-mobile/assets/90291778/d0a25735-2a45-4f50-a094-0ce19ab5b2e9)

Fixed in this PR:

[success-attempt](https://github.com/status-im/status-mobile/assets/90291778/8b387e46-18cf-48aa-b27e-1b3c1cef82fb)

### Review notes

Explanation of the issue that happened:
- https://github.com/status-im/status-mobile/issues/20500#issuecomment-2181886057

#### Platforms

- Android
- iOS

### Steps to test

Please check the video above

status: ready

### CODE REVIEW

File: src/quo/components/wallet/keypair/style.cljs [hunk 1]
```diff
@@ -7,14 +7,14 @@
...
-                              (colors/theme-colors colors/neutral-10 colors/neutral-80 theme)))
-          :padding-bottom 8}
+          :padding-bottom 8
+          :border-color   (cond
+                            (and selected? blur?) colors/white
+                            selected?             (colors/resolve-color customization-color theme)
+                            blur?                 colors/white-opa-5
+                            :else                 (colors/theme-colors colors/neutral-10
+                                                                       colors/neutral-80
+                                                                       theme))}
```
Comment (ulisesmac) [inline src/quo/components/wallet/keypair/style.cljs:17]: Just a refactor from 2 `if`s -> `cond`

File: src/quo/components/wallet/keypair/view.cljs [hunk 2]
```diff
@@ -94,20 +94,23 @@
...
-    {:data      accounts
-     :render-fn acc-list-card
-     :separator [rn/view {:style {:height 8}}]
-     :style     {:padding-horizontal 8}}]])
+  (let [theme (quo.theme/use-theme)]
+    [rn/pressable
+     {:style          (style/container (assoc props
+                                              :selected?       selected?
+                                              :container-style container-style
+                                              :theme           theme))
```
Comment (ulisesmac) [inline src/quo/components/wallet/keypair/view.cljs:103]: Just a refactor from `merge` -> `assoc`

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs [hunk 3]
```diff
@@ -231,7 +231,7 @@
          {:account-color      @account-color
           :slide-button-props {:on-auth-success on-auth-success
                                :disabled?       (or (empty? @account-name)
-                                                    (= "" @derivation-path)
+                                                    (string/blank? @derivation-path)
```
Comment (ulisesmac) [inline src/status_im/contexts/wallet/add_account/create_account/view.cljs:234]: Just making the code more robust

File: src/quo/components/buttons/slide_button/view.cljs [hunk 4]
```diff
@@ -71,14 +69,16 @@
...
+        gesture                       (rn/use-memo
+                                       (fn []
+                                         (drag-gesture x-pos
+                                                       disabled?
+                                                       (dimensions :usable-track)
+                                                       sliding-complete?
+                                                       set-sliding-complete
+                                                       on-complete
+                                                       reset-fn))
+                                       [sliding-complete? disabled? on-complete])]
```
Comment (ulisesmac) [inline src/quo/components/buttons/slide_button/view.cljs:81]: This is the main fix for this PR, due to maybe excesive memoization.

CC: @ilmotta

Comment (ilmotta) [reply src/quo/components/buttons/slide_button/view.cljs:81]: @ulisesmac, I would be surprised if excessive memoization was a problem simply because I never heard of this limitation. As long as there's enough memory, I would assume it would work.

Shouldn't we also pass the other args (`x-pos`, `set-sliding-complete`, etc) to the deps vector?

Comment (ulisesmac) [reply src/quo/components/buttons/slide_button/view.cljs:81]: @ilmotta oh, I meant that we are trying to memoize everything and cases like this happen (this is the second time I find this kind of issue).

> Shouldn't we also pass the other args (x-pos, set-sliding-complete, etc) to the deps vector?

I already considered it but seems they not needed since they are created internally, `on-complete` is an external value. I also think the memoization would be useless if everything was added to the vector.

Comment (ilmotta) [reply src/quo/components/buttons/slide_button/view.cljs:81]: > oh, I meant that we are trying to memoize everything and cases like this happen (this is the second time I find this kind of issue).

Sounds like an interesting problem @ulisesmac. Let's hope we can figure it out eventually with more examples creeping up. But doesn't sound like a bug React would have, so it's probably our fault at some layer.

> I also think the memoization would be useless if everything was added to the vector.

I think the main benefit for us in caching functions is to reduce the cost of Reagent processing hiccup needlessly while the values are passed down the tree. But here the props are passed directly to the leaf `gesture-detector`. Just something I think sometimes, but never investigated further.

File: src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs [hunk 5]
```diff
@@ -105,8 +105,7 @@
      [quo/bottom-actions
       {:actions          :one-action
        :button-one-label (i18n/label :t/confirm-account-origin)
-       :button-one-props {:disabled?           (= selected-keypair selected-key-uid)
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/add_account/create_account/select_keypair/view.cljs:108]: 👍

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs [hunk 6]
```diff
@@ -217,6 +216,7 @@
                                     [:wallet/derive-address-and-add-account
                                      {:password             password
                                       :derived-from-address derived-from
+                                      :key-uid              key-uid
                                       :derivation-path      @derivation-path
                                       :account-preferences  preferences}])))
                                [derived-from])]
```
Comment (smohamedjavid) [inline src/status_im/contexts/wallet/add_account/create_account/view.cljs:222]: Should we add `key-uid` to the deps?

File: src/quo/components/buttons/slide_button/view.cljs (hunk 4 above)
Comment (smohamedjavid) [inline src/quo/components/buttons/slide_button/view.cljs:81]: This is actually interesting 🤔

**Review by smohamedjavid — APPROVED** [review]
Nice work! @ulisesmac 🙌

File: src/status_im/contexts/wallet/add_account/create_account/view.cljs (hunk 6 above)
Comment (ulisesmac) [reply src/status_im/contexts/wallet/add_account/create_account/view.cljs:222]: Yeah, I'll add it :+1:

**Comment by qoqobolo** [comment]
Great job @ulisesmac!
PR can be merged. 

_* please don't forget to rebase PRs before moving them to e2e, thanks!_ 😉🙏

File: src/quo/components/wallet/keypair/view.cljs [hunk 7]
```diff
@@ -95,20 +95,23 @@
...
+      :on-press       #(when (= action :selector) (on-press))
+      :pointer-events :box-only}
+     [rn/view {:style style/header-container}
```
Comment (seanstrom) [inline src/quo/components/wallet/keypair/view.cljs:106]: Hey @ulisesmac 👋 
Do we need `pointer-events :box-only` here? I think this piece of code is causing an issue when we have a button embedded inside the key-pair component. For example, the pointer events won't reach the button and the on-press callback won't be called.
