### PR TITLE
[iOS] Wrong bottom sheet opacity on onboarding and in the activity center

### LINKED ISSUE #18924: [iOS] Wrong bottom sheet opacity on onboarding and in the activity center
# Bug Report

## Problem 

Screenshot 2024-02-21 at 10 56 25
Screenshot 2024-02-21 at 10 56 41

https://github.com/status-im/status-mobile/assets/67952253/d9302a95-b8af-4436-86c6-8fcd76c96b85

Screenshot 2024-02-21 at 13 42 36

#### Expected behavior
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=11465-89636&mode=design&t=IgjkIeUzwg9MIx0F-4

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=11465-90042&mode=design&t=n3GOfwfBFI7fRRYK-4

Screenshot 2024-02-21 at 10 57 22

https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=5387-526165&mode=design&t=aurz5WMucvztX3uc-4

Screenshot 2024-02-21 at 13 45 45

### Reproduction

1. Install Status on iOS
2. Press the `info` button on the `I'm new to Status` screen 
3. Add a photo on the next step

### Additional Information

- Status version: nightly 21/02
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
Fixes #18924

Screenshot:
Screenshot 2024-03-18 at 21 06 58

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

File: src/status_im/common/bottom_sheet/view.cljs [hunk 1]
```diff
@@ -119,7 +119,7 @@
          [blur/ios-view
           {:style         style/shell-bg
            :blur-radius   (or blur-radius 20)
-           :blur-type     :transparent
+           :blur-type     :dark
```
Comment (flexsurfer) [inline src/status_im/common/bottom_sheet/view.cljs]: dunno how it's related, because it's only for shell? true ? but in the description not shell screens. cc @Parveshdhull

**Comment by flexsurfer** [comment]
changed back to manual qa till waiting response from @alwx

File: src/status_im/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/common/bottom_sheet/view.cljs]: hi @flexsurfer, for onboarding screen we are passing :shell? true
https://github.com/status-im/status-mobile/blob/40e6c44b996af3cb457d58231a2cfc84f6ebd943/src/status_im/contexts/onboarding/new_to_status/view.cljs#L110

Comment (Parveshdhull) [reply src/status_im/common/bottom_sheet/view.cljs]: @alwx I am not sure if using :blur-type as :dark is right solution.

:dark, :light also creates dark overlay, and if you check screenshot added in description. It is blackish and don't match figma.

Comment (Parveshdhull) [reply src/status_im/common/bottom_sheet/view.cljs]: PR            |  Figma
:-------------------------:|:-------------------------:
  |

Comment (Parveshdhull) [reply src/status_im/common/bottom_sheet/view.cljs]: Fixing blur will be a little hard. 
### Quick fix

- As a background, we are passing `colors/white-opa-5`, try using `colors/white-opa-10` etc. to check if it matches the design
- Also you can play around with blur radius/amount

### Another fix (probably not priority)
For exactly matching figma design, we will need to find exact combination of blur params and background color. Values which  are used in figma can't be used directly, as :transparent applies some staturation.

More research: https://github.com/status-im/status-mobile/issues/14903
Related Discussion: https://github.com/Kureev/react-native-blur/pull/513 

We fixed blur issue for bottom tabs, as you can check in https://github.com/status-im/status-mobile/issues/14903#issuecomment-1682883951, but it took lots of time.

Comment (alwx) [reply src/status_im/common/bottom_sheet/view.cljs]: @Parveshdhull I played with values, nothing else gets even close to the designs except changing the blur amount. Changing background color makes it lighter or darker but doesn't change the blur itself. But you're right about the overlay the `:dark` value creates, it also seems to be a bad option.

I ended up updating the `:blur-amount` to 32 to get this:
Screenshot 2024-03-20 at 11 26 18

It's still slightly bluish than the design but it's gonna be hard to eliminate the blue tone simply because the button itself is blue and it's getting blurred instead of disappearing. But at least the amount of blur seems to suit better and look closer to the expected result.

Screenshot 2024-03-20 at 11 26 22

**Comment by alwx** [comment]
@Parveshdhull @flexsurfer to be honest, I don't think that blur-related issues need to be addressed somewhat separately — we know that the blur almost never looks like the designs and it's more of an issue with the component itself. My proposal would be to update the blur amount as part of this issue and create another umbrella issue for all blur-related things.

File: src/status_im/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (Parveshdhull) [reply src/status_im/common/bottom_sheet/view.cljs]: > It's still slightly bluish than the design but it's gonna be hard to eliminate the blue tone simply because the button itself is blue and it's getting blurred instead of disappearing.

It should not disappear. I think it is a design bug, I checked figma file and it don't have continue button in background.

- Little curious, why screenshot you shared don't have border-radius as screenshots in issue have. (unrelated)
- Please use another on-boarding screen or activity center for finding right value. It seems this screen is not right in figma itself.

Comment (Parveshdhull) [reply src/status_im/common/bottom_sheet/view.cljs]: > Please use another on-boarding screen or activity center for finding right value. It seems this screen is not right in figma itself.

If you think, the same value also works best for other screen, then I guess we can keep this fix for now. Thank you for fixing it.

**Review by Parveshdhull — APPROVED** [review]
Thank you for fixing it. Please make sure this :blur-amount is working also for other screens mentioned in issue. (As onboarding screen is not good for comparing due to design [bug](https://github.com/status-im/status-mobile/pull/19319#discussion_r1531866861))

**Comment by pavloburykh** [comment]
@alwx e2e are fine here. If PR does not require manual qa then it is ready for design review. cc @Francesca-G

**Comment by Francesca-G** [comment]
> If PR does not require manual qa then it is ready for design review. cc @Francesca-G

@pavloburykh I was trying to install the PR but this is where the QR code brings me

Screenshot 2024-03-28 alle 10 38 55

>
could you please check if it's a problem on my side? Thank you 🙏

**Comment by pavloburykh** [comment]
> could you please check if it's a problem on my side? Thank you 🙏

Hey @Francesca-G! IOS build was outdated. I rebased and updated the builds. Here is the latest IOS build https://i.diawi.com/cNyXgg

**Review by Francesca-G — APPROVED** [review]
looks good ✨

**Comment by churik** [comment]
@alwx can you please merge it?
