### PR TITLE
wallet(account): disable send and bridge options for assets with a 0 balance

### LINKED ISSUE #21022: Buttons "Send" and "Bridge" are displayed for tokens with 0 balance if at least one account has a positive balance for this token
# Bug Report

## Problem 

We shouldn't show the `Send` and `Bridge` buttons in the long-press menu inside an account if the balance of the token is 0.
There is a regression now - we display these buttons if one of the other accounts has a positive balance of the same token, which leads to broken flows.

https://github.com/user-attachments/assets/ac937d7b-0db0-475c-ac41-bc6d58cd6bd0

Screenshot 2024-08-12 at 13 45 59

### Reproduction

1. Recover a profile with some tokens, e.g. ETH on the default account (`Acc1`)
2. Wallet > Create a new account (`Acc2`)
3. Open `Acc2` (ETH balance = 0)
4. Long press on ETH
5. Press `Send`
6. On the `Send to` page open `My accounts`. Here you can see that you can only select `Acc2` where you are now, because the account **from which** the token is going to be sent is defined incorrectly
7. You can try to complete the process, but you will end up on the routes page since they will not be built

#### Expected behavior
No `Send` / `Bridge` buttons in the long-press menu inside an account if the balance of the token is 0

#### Actual behavior

`Send` / `Bridge` buttons are shown in the menu

### Additional Information

- Status version: RC 2.30 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/21022

In this pr I disabled the option to select `Send` or `Bridge` when long pressing an asset on the account page provided that the balance of that asset is 0.

https://github.com/user-attachments/assets/a29461e7-1e73-4995-b416-f2a1af48c6d6

Note:
There is already some incorrectly built in logic for how to handle options when the asset balance is 0. 
An example here is selecting DAI, as no account has DAI it will hide the options to send/ bridge rather than disable them.

Going forward a comprehensive and consistent solution needs to be implemented.

### CODE REVIEW

File: src/status_im/contexts/wallet/common/token_value/view.cljs [hunk 1]
```diff
@@ -69,43 +70,51 @@
...
-                                   (action-receive selected-account?)
-                                   (when (ff/enabled? ::ff/wallet.swap) (action-swap))
-                                   (when (seq (seq token-owners))
-                                     (action-bridge bridge-params))]))]]))
+     (let [show-send?   (if selected-account?
+                          (and (seq token-owners) has-balance?)
+                          (seq token-owners))
+           show-bridge? (if selected-account?
+                          (and (seq (seq token-owners)) has-balance?)
+                          (seq (seq token-owners)))]
```
Comment (clauxx) [inline src/status_im/contexts/wallet/common/token_value/view.cljs]: are the double seq intentional `(seq (seq ...))`?

Comment (J-Son89) [reply src/status_im/contexts/wallet/common/token_value/view.cljs]: that was there before so I won't change that for now. Want to lower the risk of introducing a new bug and just fix the edge case I'm handling.

File: src/status_im/contexts/wallet/common/token_value/view.cljs [hunk 2]
```diff
@@ -69,31 +71,36 @@
...
-                            {:token-symbol     token-symbol
-                             :bridge-disabled? (send-utils/bridge-disabled? token-symbol)
-                             :stack-id         :wallet-stack
-                             :start-flow?      true
-                             :owners           token-owners})]
+  (let [token-symbol           (:token token)
+        token-data             (first (rf/sub [:wallet/current-viewing-account-tokens-filtered
+                                               token-symbol]))
+        fiat-unformatted-value (get-in token [:values :fiat-unformatted-value])
+        has-balance?           (money/greater-than fiat-unformatted-value (money/bignumber "0"))
```
Comment (J-Son89) [inline src/status_im/contexts/wallet/common/token_value/view.cljs:78]: main change here is to get the unformatted balance and check it's greater than 0? 
If it's not then disable the send and bridge options - and only in the account page view

**Review by clauxx — APPROVED** [review]

File: src/status_im/contexts/wallet/common/token_value/view.cljs [hunk 3]
```diff
@@ -107,6 +114,7 @@
                                    (when (seq (seq token-owners))
                                      (action-bridge bridge-params))]))]]))
 
+
```
Comment (clauxx) [inline src/status_im/contexts/wallet/common/token_value/view.cljs]: extra space

File: src/status_im/contexts/wallet/common/token_value/view.cljs [hunk 4]
```diff
@@ -69,31 +71,36 @@
...
+                                  :owners      token-owners}
+                                 {:token-symbol token-symbol
+                                  :stack-id     :wallet-stack
+                                  :start-flow?  true
+                                  :owners       token-owners})
+        bridge-params          (if selected-account?
+                                 {:token            token-data
+                                  :bridge-disabled? (or :disabled?
+                                                        (not has-balance?)
+                                                        (send-utils/bridge-disabled? token-symbol))
```
Comment (clauxx) [inline src/status_im/contexts/wallet/common/token_value/view.cljs]: will always evaluate to `:disabled?` and the later checks will not run, since the keyword is truthy

File: src/status_im/contexts/wallet/common/token_value/view.cljs (hunk 3 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/common/token_value/view.cljs]: thanks

File: src/status_im/contexts/wallet/common/token_value/view.cljs (hunk 4 above)
Comment (J-Son89) [reply src/status_im/contexts/wallet/common/token_value/view.cljs]: thanks for spotting!

**Review by clauxx — APPROVED** [review]
Good job :+1:

**Review by vkjr — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @J-Son89 thank you for PR. No issue from my side. PR is ready to be merged
