### PR TITLE
Keycard "refactoring" fixing many issues and UI/UX 

### LINKED ISSUE #21647: [Keycard] "Keycard is not empty" screen instead of "This is a different Keycard" screen during a login with Keycard
# Bug Report
https://github.com/status-im/status-mobile/pull/21467

**Preconditions:**

make sure you have 2 Keycards with a different key pairs on it
OR
you can use one Keycard and during reproduction you will need to make Factory reset (Desktop feature) and migrate another key pair to continue testing

### Reproduction

1. Install app
2. Go to Login by using a Keycard 
3. Scan your Keycard with a key pair #1 
4. Enter PIN
5. Scan another Keycard with a key pair #2 (or factory reset -> migration)

#### Actual behavior

Image

#### Expected behavior
https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3369-58996&node-type=frame&t=oUd6hwmPFSTpwv7M-0

Image

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #21957: Scanning different key card (which is not empty) during Create Profile flow results in stuck on Preparing screen or overwriting keys on this keycard
Potentially will be fixed in scope of https://github.com/status-im/status-mobile/issues/21647 cc @flexsurfer 

**Steps:** 

1. Start Creating Profile by scanning Keycard A
2. During second (final) scan use Keycard B which is not empty
3. Observe the result

**Actual result:** 

1. Sometimes user stucks on Preparing screen
2. Sometimes profile is created successfully and Keycard B keys are overwritten

photo_2025-01-17 17 35 37

**Expected result:** It's a different key card screen should be shown. Or at least, until this screen is implemented for this flow, we should show Keycard not empty screen. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #21969: Generate Mnemonic on keycard instead of status-go
Currently Mnemonic is generated on status-go for keycard profiles, but should be generated on the keycard, generateMnemonic should be used https://github.com/keycard-tech/react-native-status-keycard/blob/master/android/src/main/java/im/status/ethereum/keycard/RNStatusKeycardModule.java#L134

Because we need card initialized to use generateMnemonic method, flow needs to be changed , backup mnemonic should be after pin creation 

Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3180-46361&t=OKyIY3Pk3zH2Aml1-1

### LINKED ISSUE #22025: incorrect screen displayed when logging in with an empty keycard
I believe can be introduced by https://github.com/status-im/status-mobile/pull/21990

### Preconditions:
imported to key card user is onboarded

### Steps:
1. Log out
2. Go to log in
3. Scan empty key card 

### Actual result:
incorrect screen displayed when logging in with an empty keycard

https://github.com/user-attachments/assets/44585521-6791-45ed-ac3a-a6965cde7456

### Expected result:
https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3908-44522&t=7Dh2kwRWS4PVRBTh-0

Image

### LINKED ISSUE #22056: [Keycard] Implementation of Keycard is full screen looks not as designed
# Bug Report

Implementation vs Design

Image

**Actual result:**

- Text differs
- Factory reset flow exist

**Expected result:** seems that design shool be changed.

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3-89231&p=f&version-id=2183852963474525226&m=dev

### LINKED ISSUE #22058: [Keycard] Keycard is not empty screen has Factory reset option implemented instead of Log in with this Keycard
# Bug Report

Implementation vs Design

Image

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3-89231&p=f&version-id=2183852963474525226&m=dev

### LINKED ISSUE #22060: [Keycard] Not implemented Extra scanning after PIN creation
# Bug Report

**Steps:**

1. Install app
2. Go to Create Profile -> Empty Keycard
3. Go through the flow till PIN creation part

**Actual result:**

No scanning part as designed

Image

User sees this screen after PIN creation

Image

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3-89231&p=f&version-id=2183852963474525226&m=dev

### LINKED ISSUE #22091: [Keycard] Keycard is full screen renaming
# Bug Report

**Steps:**

1. Install app 
2. Took a Keycard that has all slots occupied (occupation occurs when Keyard is used on 5th different devices OR used to create Profile 5 times, in this case you need to re-install app every time)
3. Go to Log in -> Log in with Keycard
4. Scan you card from step 2

**Implementation vs Design**

Image

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3038-152283&version-id=2183852963474525226&m=dev

### LINKED ISSUE #22133: Not implemented the "It’s a different Keycard" screen
# Problem

Not implemented the "It’s a different Keycard" screen

**Actual results:**
Scanning a different Keycard from the current one  does not trigger the "It’s a different Keycard" screen.

**Expected results:**
Scanning a different Keycard from the current one triggers the "It’s a different Keycard" screen.

Image

Used this Design version : https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3-89231&p=f&version-id=2183852963474525226&m=dev

### LINKED ISSUE #22135: [Keycard] Keycard is not empty screen instead of This is a different Keycard
# Bug Report

**Implementation vs Design**

Image

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=603-104817&version-id=2183852963474525226&m=dev

### PR DESCRIPTION
**Pull request by flexsurfer**
All keycard flow's except change pin have been affected.  All variants of empty and not empty screen have been implemented. Different card screen has been implemented properly for all flows.

fixes: #22166  
- [ ] tested [technical PR, not requested for manual qa]

fixes: #21969
- [x] tested 

fixes: #21957
- [x] tested

fixes: #22056
- [x] tested

fixes: #22058
- [x] tested

fixes: #22091
- [x] tested

fixes: #22060
- [x] tested

fixes: #22150
- [x] tested

fixes: #22142
- [x] tested

fixes: #22138
- [x] tested

fixes: #22145
- [x] tested

fixes https://github.com/status-im/status-mobile/issues/22157
- [x] tested

fixes https://github.com/status-im/status-mobile/issues/22135
- [x] tested

fixes https://github.com/status-im/status-mobile/issues/21647
- [x] tested

fixes https://github.com/status-im/status-mobile/issues/22025
- [x] tested

fixes https://github.com/status-im/status-mobile/issues/22133 (Most probably same, design might be outdated)
- [x] tested

Useful document: https://www.notion.so/Keycard-scanning-flows-1a48f96fb65c8067a45cef8df38b6cbe

**IMPORTANT CHANGES:**
1) Create/import, backup, migrate flows ,now have create/enter PIN as a separate flow with separate card scan
2) On create flow mnemonic generated on the card, separate scan
3) In all flows pin is masked (just security, not changes in the UI)
4) all flows now have same "error" conditional check
      1. if its a keycard
      2. if it’s the same card (working starting from 2nd scan if instance-uid is provided)
      3. if its not blocked
      4. if pairings ok

**For devs:** 

on-error is still useful, we have 3 basic errors we check always
1) isn't a keycard
2) blocked
3) unpaired

And if keycard is empty or has keys it's success, and in success handler we have all logic related to empty state or specific keys

### CODE REVIEW

File: src/status_im/contexts/keycard/unblock/events.cljs [hunk 1]
```diff
@@ -2,86 +2,89 @@
...
+                  (show-different-card)
+                  (init-with-pin masked-pin)))
+              :on-error
+              (fn [error {:keys [instance-uid]}]
+                (if (not= instance-uid (get-in db [:keycard :unblock :instance-uid]))
+                  (show-different-card)
+                  (if (or (= error :keycard/error.keycard-frozen)
+                          (= error :keycard/error.keycard-locked))
+                    (rf/dispatch [:keycard/factory-reset {:on-success #(init-with-pin masked-pin)}])
+                    (rf/dispatch [:keycard/on-application-info-error error]))))}]]]})))
```
Comment (Parveshdhull) [inline src/status_im/contexts/keycard/unblock/events.cljs]: hi @flexsurfer, Thank you very much for you great work. I Will review PR tomorrow.

> Implement on-complete event instead of on-error and on-succe

It seems we still have `on-success` and `on-error`. Is the PR still a work in progress, or will this be handled separately? If will be handled separately, should the PR title be updated?

Comment (flexsurfer) [reply src/status_im/contexts/keycard/unblock/events.cljs]: hey @Parveshdhull thank you, i'll notify you when it's ready for review, still WIP

**Comment by flexsurfer** [comment]
thanks @Parveshdhull i've implemented instance-uid for different card screens, and updated the description, yes it's still useful to have on-success and on-error handlers separately, most flows, will use only on-success

File: src/status_im/contexts/keycard/factory_reset/view.cljs [hunk 2]
```diff
@@ -10,34 +10,36 @@
...
+  [card-key-uid]
   (rf/dispatch
    [:keycard/connect
     {:theme      :dark
-     :key-uid    key-uid
-     :on-success reset-card
+     :on-success (fn [{:keys [initialized? key-uid]}]
+                   (if (and initialized? (= key-uid card-key-uid))
+                     (reset-card)
+                     (do
```
Comment (Parveshdhull) [inline src/status_im/contexts/keycard/factory_reset/view.cljs]: Hi, why do we need this check here? If we pass `key-uid` as a parameter when calling `:keycard/connect`, wouldn't that have the same effect?"

Comment (Parveshdhull) [reply src/status_im/contexts/keycard/factory_reset/view.cljs]: Then we can move `(rf/dispatch [:open-modal :screen/keycard.different-card])` to on-error section.

File: src/status_im/contexts/keycard/events.cljs [hunk 3]
```diff
@@ -145,13 +147,15 @@
                      (dissoc :application-info-error)))}))
 
 (rf/reg-event-fx :keycard/get-application-info
- (fn [_ [{:keys [key-uid on-success on-error]}]]
+ (fn [_ [{:keys [on-success on-error instance-uid key-uid]}]]
```
Comment (Parveshdhull) [inline src/status_im/contexts/keycard/events.cljs:150]: Should we add a comment here to explain when to pass instance-uid and when to pass key-uid, along with their side effects?

File: src/status_im/contexts/keycard/factory_reset/view.cljs (hunk 2 above)
Comment (Parveshdhull) [reply src/status_im/contexts/keycard/factory_reset/view.cljs]: I can't think of any alternate name, but `key-uid` and `card-key-uid` are both card uid, right? One is taken from db (stored in last scan), and one is result of fresh scan.

File: src/status_im/contexts/keycard/utils.cljs [hunk 4]
```diff
@@ -20,15 +20,17 @@
    (re-matches #".*NFCError:100.*" error)))
 
 (defn validate-application-info
-  [profile-key-uid
-   {:keys [key-uid has-master-key? paired? pin-retry-counter puk-retry-counter] :as application-info}]
+  [{:keys [has-master-key? paired? pin-retry-counter puk-retry-counter] :as application-info}
+   instance-uid
+   key-uid]
```
Comment (Parveshdhull) [inline src/status_im/contexts/keycard/utils.cljs]: Unnecessary line break

**Review by Parveshdhull — APPROVED** [review]
Thank you, @flexsurfer, for your work. Apart from a few questions, the code looks good to me. The keycard logic is like a web and hard to keep track of and understand.

Please add a few more reviewers once the PR is ready.

File: src/status_im/contexts/keycard/factory_reset/view.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/contexts/keycard/factory_reset/view.cljs]: so there is two problems, 
1) card might be reseted but without success handler, that means we need to continue process
2) empty card doesn't have key-uid, that's why reset is little bit complex

Comment (flexsurfer) [reply src/status_im/contexts/keycard/factory_reset/view.cljs]: regarding key-uid, yes probably we could pass key-uid, and compare to (:key-uid app-info) is this better?

File: src/status_im/contexts/keycard/events.cljs (hunk 3 above)
Comment (flexsurfer) [reply src/status_im/contexts/keycard/events.cljs:150]: yes, basically initialized card don't have key-uid, but if you have a few steps in the flow, you just want to track if it's the same card you started the flow, on login for example we don't care about instance, we want to login with the specific key-uid, so basically when you're developing new functionality there should be not question which one to use

**Comment by flexsurfer** [comment]
> The keycard logic is like a web

yes that's because of NFC, because we have so many edge cases , but this PR should improve it little bit

**Comment by flexsurfer** [comment]
@Parveshdhull thank you for your review, i don't think it make really sense to have another review, it will be just pain to review it for dev who are not familiar with code

**Comment by churik** [comment]
@flexsurfer Thanks for your work on this! 🙌  

Just to avoid any further confusion, we’ve decided to wait until the **design flows** are updated. This was discussed with @xAlisher, and they should be ready **early next week**.  

Once the updates are available, we’ll review the PR. Until then, I’ll temporarily block it from procceeding. 

Appreciate your patience!

**Comment by flexsurfer** [comment]
figma has been updated, ready for testing

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer !

## Issue 1: "Cannon read a property 'off" of null

Caught this issue at the end of Migration flow (Profile Settings)

Screenshot 2025-03-11 at 14 39 20

**Steps:**

1. Go to Profile -> Keycard
2. Migrate your key card
3. Do a logout

[logs_migration.zip](https://github.com/user-attachments/files/19184412/logs_migration.zip)

**Comment by flexsurfer** [comment]
hey @mariia-skrypnyk thanks, probably this issue not related to keycard and this PR and we have it in develop? i couldn't reproduce it with keycard

**Comment by Horupa-Olena** [comment]
Hi @flexsurfer !
I found issue in "[Log in" flow](https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=2991-75949&t=rOIZNHszyIacs8WS-0), please check it

**ISSUE 2: Missing profile duplicate existence check causes app freeze on "Preparing..." screen**

**Summary:**
The app does not check if the profile already exists on the device when re-logging in with a Keycard. As a result, the app freezes on the "Preparing..." screen.

**Steps to Reproduce:**
1. Log in by Keycard
2. Log out of the app
3. Attempt to log in again using a Keycard with the same profile
4. Observe the screen

**Expected Result:**
User should be redirected to the info screen and profile page after (branch "Yes" for this [condition](https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=4492-45235&t=rOIZNHszyIacs8WS-0)).

**Actual Result:**
The app missing condition ["The profile from this keycard is already added to the device."](https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=4492-45235&t=rOIZNHszyIacs8WS-0) and freezes on the "Preparing..." screen and does not proceed further.


https://github.com/user-attachments/assets/150e703a-049a-4d16-a849-c88d007aeac6

Log file: 
[Status-debug-logs (2).zip](https://github.com/user-attachments/files/19207294/Status-debug-logs.2.zip)

**Comment by flexsurfer** [comment]
thanks @Horupa-Olena , fixed

**Comment by flexsurfer** [comment]
fixed small UI issues in settings/migrate flow

**Comment by flexsurfer** [comment]
Issue 1: "Cannon read a property 'off" of null should be a separate issue, not related to keycard and this PR

**Comment by mariia-skrypnyk** [comment]
## ISSUE 3: Wrong margin and no grey background for buttons 

**Implementation vs Design**

Screenshot 2025-03-12 at 13 23 08

Issue exist in all screens when user scans not a valid Keycard

**Comment by flexsurfer** [comment]
@Horupa-Olena issue 2 is properly fixed now, there was a small change in Figma, 
condition was moved before entering pin
image

this flow now targets the same condition
image

**Comment by flexsurfer** [comment]
thanks @mariia-skrypnyk ISSUE 3: 

- [x] Wrong margin fixed

- [ ] no grey background for buttons should be discussed with @xAlisher because there is no such prop for this component in Figma

**Comment by Horupa-Olena** [comment]
**ISSUE 4: Unexpected Error Popup After Final Scan in Unblock Flow**

**Preconditions:**
1. Restore an account using the seed phrase.
2. Migrate to Keycard.
3. Block the card by entering an incorrect PIN 3 times.

**Steps to Reproduce:**
1. Initiate the Unblock flow from the "Keycard is blocked" screen.
2. Proceed through the flow until the "Ready to Unblock Keycard" screen.
3. Scan the card.

**Expected Result:**
The app should redirect to the "Keycard Unblocked" screen, and the flow should complete successfully.

**Actual Result:**
An unexpected error popup appears, and the app crashes.
image


https://github.com/user-attachments/assets/c3c606e0-16dd-4fde-9a1a-4ac0ee89842c

LOG:
[Status-debug-logs (3).zip](https://github.com/user-attachments/files/19231195/Status-debug-logs.3.zip)

**Comment by Horupa-Olena** [comment]
**ISSUE 5: Change PIN Flow Stuck on Final Scanning**

**Steps to Reproduce:**

1. Go to Profile → Keycard → Manage Keycard.
2. Perform the first card scan.
3. Select Change PIN.
4. Set a new PIN.
5. Perform the final card scan and observe.

**Expected Result:**
The flow should proceed to the next step and complete successfully.

**Actual Result:**
The flow gets stuck on the NFC prompt during the final scanning step.

https://github.com/user-attachments/assets/f518a5bb-243b-4ce5-8ccc-49f6b96db987

LOG: 
[Status-debug-logs (4).zip](https://github.com/user-attachments/files/19231761/Status-debug-logs.4.zip)

**Comment by flexsurfer** [comment]
thank you @Horupa-Olena , issue 4 and issue 5 are fixed now

**Comment by mariia-skrypnyk** [comment]
Hey @flexsurfer !

Can you please do a small UI fix:

- Factory reset description text color
- Backup description text differs

Screenshot 2025-03-14 at 12 11 52

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3038-151156&t=phRYeB5UGhRCAf3w-0

**Comment by flexsurfer** [comment]
thanks @mariia-skrypnyk fixed

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer !

Thanks for your hard work on this huge PR.
All issues were test except the first technical one.
Me and @Horupa-Olena have closed a lot of additianal issues auto-fixed with this PR too.

E2E failed is not related.
PR finally can be merged!
