### PR TITLE
bug #3638 - fixed uneditable browser address bar in ios

### LINKED ISSUE #3638: Can’t edit url in Status browser
### Description
*Type*: Bug

*Summary*: Nothing happens when I tap on the Status browser url bar on iPhones. In result I can't edit the url.
Everything works fine on Galaxy S8 (Android 7.0) 

#### Expected behavior
Url field should be focused and I should be able to edit the url

#### Actual behavior
Nothing happens when url bar is clicked

### Reproduction
- Use device like iPhone 6
- Open Status
- Open DApp with custom url like "google.com"
- Try to change the url

### Additional Information
* Status version: tested on nightly from March 20 and March 21, release/0.9.16
* Worked in 0.9.15
* Operating System: iOS
* Device: iPhone 6, iPhone 8, iPhone X

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3638

### Summary:

The issue was caused by empty list of actions that overshadowed the text input's tappable area on ios.
The solution in this PR is not to render action list when there are no actions.

### Testing notes (optional):
This PR changes how `toolbar` component works. Keep an eye on other screens and their toolbars just to see if they're still ok.

### Steps to test:
- Open browser with a custom URL
- Tap the address bar to change the url

status: ready

### CODE REVIEW

File: src/status_im/ui/components/toolbar/view.cljs [hunk 1]
```diff
@@ -121,7 +121,7 @@
        {:key (str "action-" (or image icon))}))])
 
 (defn toolbar
-  ([props nav-item content-item] (toolbar props nav-item content-item [actions [{:image :blank}]]))
+  ([props nav-item content-item] (toolbar props nav-item content-item nil))
```
Comment (flexsurfer) [inline src/status_im/ui/components/toolbar/view.cljs:124]: hm

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/components/toolbar/view.cljs (hunk 1 above)
Comment (jeluard) [reply src/status_im/ui/components/toolbar/view.cljs:124]: That `blank` was needed before to keep proper balance when no actions. Maybe it's not necessary anymore? #cleanup :D

Comment (flexsurfer) [reply src/status_im/ui/components/toolbar/view.cljs:124]: yeah i think we should rework toolbar component, i don't like these nils tbh

**Review by jeluard — APPROVED** [review]

File: src/status_im/ui/components/toolbar/view.cljs (hunk 1 above)
Comment (goranjovic) [reply src/status_im/ui/components/toolbar/view.cljs:124]: agree! also, it still works a bit different on ios even though there aren't any platform conditionals any more, so something is still weird
